environ
vocabularies NUMBERS,XBOOLE_0,ORDERS_2,MSUALG_4,OSALG_1,RELAT_1,STRUCT_0,FUNCOP_1,PBOOLE,SUBSET_1,XXREAL_0,FUNCT_1,MSUALG_1,TARSKI,EQREL_1,NAT_1,MARGREL1,PARTFUN1,FINSEQ_1,ARYTM_3,ARYTM_1,ZFMISC_1,FINSEQ_5,CARD_1,RELAT_2,ORDINAL4,NATTRA_1,YELLOW15,SETFAM_1,COH_SP,YELLOW18,WAYBEL_0,CARD_3,MSUALG_3,WELLORD1,SEQM_3,OSALG_4;
notations ZFMISC_1,TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,RELAT_2,FUNCT_1,RELSET_1,PARTFUN1,EQREL_1,SETFAM_1,XCMPLX_0,ORDERS_2,ORDERS_3,NUMBERS,NAT_1,FUNCT_2,FINSEQ_1,CARD_3,FINSEQ_2,FINSEQ_4,FINSEQ_5,FUNCOP_1,PBOOLE,STRUCT_0,WAYBEL_0,MSUALG_1,MSUALG_3,OSALG_1,OSALG_3,MSUALG_4,XXREAL_0,CKB2,CKB4,CKB7,CKB8,CKB11,CKB12,CKB14,CKB16,CKB18,CKB19,CKB21,CKB23,CKB32,CKB33,CKB36,CKB38,CKB42,CKB43,CKB44,CKB45,CKB46;
definitions TARSKI,MSUALG_3,XBOOLE_0,OSALG_1,OSALG_3,CKB2,CKB8,CKB12,CKB14,CKB16,CKB19,CKB21,CKB23,CKB32,CKB33,CKB36,CKB38,CKB42,CKB43,CKB44,CKB45,CKB46;
theorems XBOOLE_0,XBOOLE_1,FUNCT_1,FUNCT_2,PBOOLE,CARD_3,MSUALG_1,MSUALG_5,OSALG_1,OSALG_3,RELAT_2,ZFMISC_1,RELAT_1,RELSET_1,EQREL_1,MSUALG_3,MSUALG_6,MSAFREE,TARSKI,SYSREL,ORDERS_2,FINSEQ_1,FINSEQ_3,ENUMSET1,FINSEQ_5,INT_1,ORDERS_3,PARTFUN1,WAYBEL_0,GRFUNC_1,MSUALG_9,MSUALG_4,FINSEQ_2,ORDERS_1,FUNCOP_1,XREAL_1,XXREAL_0,CKB2,CKB5,CKB8,CKB12,CKB13,CKB14,CKB15,CKB16,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB31,CKB32,CKB33,CKB35,CKB36,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47;
schemes FUNCT_1,CLASSES1,NAT_1,FUNCT_2;
registrations SUBSET_1,RELAT_1,PARTFUN1,FUNCOP_1,XREAL_0,INT_1,FINSEQ_1,EQREL_1,FUNCT_1,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_3,MSUALG_4,ORDERS_3,OSALG_1,ORDINAL1,CARD_3,TOLER_1,RELSET_1,FINSEQ_2,CKB1,CKB3,CKB6,CKB9,CKB10,CKB17,CKB27,CKB28,CKB29,CKB30,CKB34,CKB37;
constructors XXREAL_0,REAL_1,NAT_1,NAT_D,EQREL_1,FINSEQ_4,FINSEQ_5,MSUALG_3,MSUALG_4,ORDERS_3,WAYBEL_0,OSALG_3,RELSET_1,CKB2,CKB8,CKB12,CKB14,CKB16,CKB19,CKB21,CKB23,CKB32,CKB33,CKB36,CKB38,CKB42,CKB43,CKB44,CKB45,CKB46;
requirements BOOLE,SUBSET,NUMERALS,REAL,ARITHM;
begin
reserve S for  locally_directed OrderSortedSign;
reserve o for (Element of (the carrier' of S));
definition
let S;
let o;
let A being  non-empty (OSAlgebra of S);
let R being (OSCongruence of A);
func OSQuotCharact (R,o) -> (Function of ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ),( ( ( OSClass R ) * (the ResultSort of S) ) . o )) means 
:Def20: (for a being (Element of ( Args (o,A) )) holds (( R #_os a ) in ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ) implies ( it . ( R #_os a ) ) = ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . a )));
existence
proof
defpred P[ set,set ]
 means
(for a being (Element of ( Args (o,A) )) holds ($1 = ( R #_os a ) implies $2 = ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . a )));
set Ca = ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o );
set Cr = ( ( ( OSClass R ) * (the ResultSort of S) ) . o );
A1: (for x being set holds (x in Ca implies (ex y being set st (y in Cr & P[ x,y ]))))
proof
set ro = ( the_result_sort_of o );
set ar = ( the_arity_of o );
let x being set;
assume x in Ca;
then consider a being (Element of ( Args (o,A) )) such that A2: x = ( R #_os a ) by CKB47:1;
take y = ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . a );
A3: o in (the carrier' of S);
then o in ( dom ( ( OSClass R ) * (the ResultSort of S) ) ) by PARTFUN1:def 2;
then A4: ( ( ( OSClass R ) * (the ResultSort of S) ) . o ) = ( ( OSClass R ) . ( (the ResultSort of S) . o ) ) by FUNCT_1:12
.= ( ( OSClass R ) . ro ) by MSUALG_1:def 2;
o in ( dom ( (the Sorts of A) * (the ResultSort of S) ) ) by A3,PARTFUN1:def 2;
then A5: ( ( (the Sorts of A) * (the ResultSort of S) ) . o ) = ( (the Sorts of A) . ( (the ResultSort of S) . o ) ) by FUNCT_1:12
.= ( (the Sorts of A) . ro ) by MSUALG_1:def 2;
then A6: (( dom ( OSQuotRes (R,o) ) ) = ( (the Sorts of A) . ro ) & ( Result (o,A) ) = ( (the Sorts of A) . ro )) by FUNCT_2:def 1,MSUALG_1:def 5;
( rng ( Den (o,A) ) ) c= ( Result (o,A) );
then A7: (( dom ( Den (o,A) ) ) = ( Args (o,A) ) & ( dom ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) ) = ( dom ( Den (o,A) ) )) by A6,FUNCT_2:def 1,RELAT_1:27;
( ( OSQuotRes (R,o) ) . ( ( Den (o,A) ) . a ) ) in ( rng ( OSQuotRes (R,o) ) ) by A6,FUNCT_1:def 3;
then ( ( OSQuotRes (R,o) ) . ( ( Den (o,A) ) . a ) ) in ( ( OSClass R ) . ro ) by A4;
hence y in Cr by A4,A7,FUNCT_1:12;
let b being (Element of ( Args (o,A) ));
reconsider da = ( ( Den (o,A) ) . a ),db = ( ( Den (o,A) ) . b ) as (Element of ( (the Sorts of A) . ro )) by A5,MSUALG_1:def 5;
A8: ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . b ) = ( ( OSQuotRes (R,o) ) . db ) by A7,FUNCT_1:12
.= ( OSClass (R,db) ) by CKB43:def 1
.= ( Class (( CompClass (R,( CComp ro )) ),db) );
assume A9: x = ( R #_os b );
(for n being Nat holds (n in ( dom a ) implies [ ( a . n ),( b . n ) ] in ( R . ( ar /. n ) )))
proof
let n being Nat;
A10: ( dom a ) = ( dom ar ) by MSUALG_3:6;
assume n in ( dom a );
then ((ex ya being (Element of ( (the Sorts of A) . ( ar /. n ) )) st (ya = ( a . n ) & ( ( R #_os a ) . n ) = ( OSClass (R,ya) ))) & (ex yb being (Element of ( (the Sorts of A) . ( ar /. n ) )) st (yb = ( b . n ) & ( ( R #_os b ) . n ) = ( OSClass (R,yb) )))) by A10,CKB42:def 1;
hence thesis by A2,A9,CKB40:1;
end;
then (ro in ( CComp ro ) & [ da,db ] in ( R . ro )) by EQREL_1:20,MSUALG_4:def 4;
then A11: [ da,db ] in ( CompClass (R,( CComp ro )) ) by CKB32:def 1;
A12: da in ( (the Sorts of A) -carrier_of ( CComp ro ) ) by CKB22:1;
y = ( ( OSQuotRes (R,o) ) . ( ( Den (o,A) ) . a ) ) by A7,FUNCT_1:12
.= ( OSClass (R,da) ) by CKB43:def 1
.= ( Class (( CompClass (R,( CComp ro )) ),da) );
hence thesis by A12,A8,A11,EQREL_1:35;
end;
consider f being Function such that A13: ((( dom f ) = Ca & ( rng f ) c= Cr) & (for x being set holds (x in Ca implies P[ x,( f . x ) ]))) from FUNCT_1:sch 5(A1);
reconsider f as (Function of ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ),( ( ( OSClass R ) * (the ResultSort of S) ) . o )) by A13,FUNCT_2:2;
take f;
thus thesis by A13;
end;
uniqueness
proof
set ao = ( the_arity_of o );
let F being (Function of ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ),( ( ( OSClass R ) * (the ResultSort of S) ) . o ));
let G being (Function of ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ),( ( ( OSClass R ) * (the ResultSort of S) ) . o ));
assume that
A14: (for a being (Element of ( Args (o,A) )) holds (( R #_os a ) in ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ) implies ( F . ( R #_os a ) ) = ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . a )))
and
A15: (for a being (Element of ( Args (o,A) )) holds (( R #_os a ) in ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ) implies ( G . ( R #_os a ) ) = ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . a )));
A16: ( dom (the Arity of S) ) = (the carrier' of S) by FUNCT_2:def 1;
then ( dom ( ( ( OSClass R ) # ) * (the Arity of S) ) ) = ( dom (the Arity of S) ) by PARTFUN1:def 2;
then A17: ( ( ( ( OSClass R ) # ) * (the Arity of S) ) . o ) = ( ( ( OSClass R ) # ) . ( (the Arity of S) . o ) ) by A16,FUNCT_1:12
.= ( ( ( OSClass R ) # ) . ao ) by MSUALG_1:def 1;
A18:now
let x being set;
assume A19: x in ( ( ( OSClass R ) # ) . ao );
then consider a being (Element of ( Args (o,A) )) such that A20: x = ( R #_os a ) by A17,CKB47:1;
( F . x ) = ( ( ( OSQuotRes (R,o) ) * ( Den (o,A) ) ) . a ) by A14,A17,A19,A20;
hence ( F . x ) = ( G . x ) by A15,A17,A19,A20;
end;
(( dom F ) = ( ( ( OSClass R ) # ) . ao ) & ( dom G ) = ( ( ( OSClass R ) # ) . ao )) by A17,FUNCT_2:def 1;
hence thesis by A18,FUNCT_1:2;
end;
end;
