environ
vocabularies XBOOLE_0,PRE_TOPC,SUBSET_1,TEX_4,RCOMP_1,TARSKI,STRUCT_0,TOPS_1,ZFMISC_1,SETFAM_1,FUNCT_1,RELAT_1,NATTRA_1,ORDINAL2,BORSUK_1,TSP_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,FUNCT_1,RELAT_1,RELSET_1,FUNCT_2,DOMAIN_1,STRUCT_0,PRE_TOPC,TOPS_1,BORSUK_1,TSEP_1,TEX_2,TEX_3,TEX_4,TSP_1,CKB1,CKB2,CKB3,CKB4,CKB6,CKB14,CKB17,CKB21,CKB33;
definitions SUBSET_1,STRUCT_0,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB6,CKB14,CKB17,CKB21;
theorems TARSKI,ZFMISC_1,FUNCT_1,FUNCT_2,PRE_TOPC,TOPS_1,BORSUK_1,TSEP_1,TOPS_3,TEX_2,TEX_3,TEX_4,TSP_1,RELAT_1,XBOOLE_0,XBOOLE_1,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB21,CKB22,CKB31,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43;
schemes TEX_2,FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,PRE_TOPC,TOPS_1,TSP_1,CKB19,CKB20,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32;
constructors TOPS_1,BORSUK_1,TSEP_1,TEX_2,TEX_4,TSP_1,TEX_3,CKB4,CKB17;
requirements BOOLE,SUBSET;
begin
reserve X for non  empty TopSpace;
reserve X0 for non  empty (maximal_Kolmogorov_subspace of X);
theorem
Lm2: (for r being  continuous (Function of X,X0) holds (r is  being_a_retraction implies (for a being (Point of X) holds (for b being (Point of X0) holds (a = b implies ( r " ( Cl { b } ) ) = ( Cl { a } ))))))
proof
let r being  continuous (Function of X,X0);
assume A1: r is  being_a_retraction;
reconsider A = (the carrier of X0) as (Subset of X) by TSEP_1:1;
let a being (Point of X);
let b being (Point of X0);
A2: b in { b } by TARSKI:def 1;
assume A3: a = b;
then ( r . a ) = b by A1,BORSUK_1:def 16;
then A4: a in ( r " { b } ) by A2,FUNCT_2:38;
A5: A is  maximal_T_0 by CKB18:1;
A6: ( r " ( Cl { b } ) ) c= ( Cl { a } )
proof
assume (not ( r " ( Cl { b } ) ) c= ( Cl { a } ));
then consider c being set such that A7: c in ( r " ( Cl { b } ) ) and A8: (not c in ( Cl { a } )) by TARSKI:def 3;
reconsider c as (Point of X) by A7;
consider d being (Point of X) such that A9: d in A and A10: ( A /\ ( MaxADSet c ) ) = { d } by A5,CKB14:def 1;
A11: { d } c= ( MaxADSet c ) by A10,XBOOLE_1:17;
( r " ( Cl { b } ) ) is  closed by PRE_TOPC:def 6;
then ( MaxADSet c ) c= ( r " ( Cl { b } ) ) by A7,TEX_4:23;
then { d } c= ( r " ( Cl { b } ) ) by A11,XBOOLE_1:1;
then A12: d in ( r " ( Cl { b } ) ) by ZFMISC_1:31;
reconsider e = d as (Point of X0) by A9;
{ c } c= ( MaxADSet c ) by TEX_4:18;
then A13: c in ( MaxADSet c ) by ZFMISC_1:31;
A14: ( Cl { b } ) c= ( Cl { a } ) by A3,TOPS_3:53;
( r . d ) = e by A1,BORSUK_1:def 16;
then e in ( Cl { b } ) by A12,FUNCT_2:38;
then A15: ( MaxADSet d ) c= ( Cl { a } ) by A14,TEX_4:23;
d in ( MaxADSet c ) by A11,ZFMISC_1:31;
then ( MaxADSet d ) = ( MaxADSet c ) by TEX_4:21;
hence contradiction by A8,A13,A15;
end;
A16: ( r " ( Cl { b } ) ) is  closed by PRE_TOPC:def 6;
( r " { b } ) c= ( r " ( Cl { b } ) ) by PRE_TOPC:18,RELAT_1:143;
then { a } c= ( r " ( Cl { b } ) ) by A4,ZFMISC_1:31;
then ( Cl { a } ) c= ( r " ( Cl { b } ) ) by A16,TOPS_1:5;
hence thesis by A6,XBOOLE_0:def 10;
end;
