environ
vocabularies NUMBERS,FUNCT_1,FUNCOP_1,TARSKI,RELAT_1,FUNCT_6,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,ORDERS_2,LATTICE3,MSUALG_5,STRUCT_0,EQREL_1,PBOOLE,LATTICES,XXREAL_0,REWRITE1,SETFAM_1,RELAT_2,WAYBEL_0,GROUP_6,YELLOW_0,ORDINAL2,CAT_1,FINSEQ_1,ARYTM_3,ABIAN,FINSEQ_2,ARYTM_1,CARD_1,ORDINAL4,NAT_1,VALUED_0,FUNCT_2,MCART_1,PARTFUN1,LATTICE5;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,RELAT_1,RELAT_2,FUNCT_1,RELSET_1,FUNCT_2,FUNCT_6,CARD_1,NUMBERS,XCMPLX_0,NAT_1,NAT_D,SETFAM_1,ORDINAL1,ORDINAL2,MCART_1,DOMAIN_1,PARTFUN1,FUNCOP_1,STRUCT_0,ORDERS_2,EQREL_1,MSUALG_5,FINSEQ_1,FINSEQ_2,SEQ_4,LATTICES,LATTICE3,BINOP_1,YELLOW_0,WAYBEL_0,YELLOW_2,ABIAN,XXREAL_0,CKB4,CKB13,CKB16,CKB18,CKB20;
definitions TARSKI,LATTICE3,FUNCOP_1,WAYBEL_0,XBOOLE_0,BINOP_1,FINSEQ_1,FINSEQ_2,CKB4,CKB13,CKB20;
theorems EQREL_1,RELAT_1,RELAT_2,FINSEQ_1,FINSEQ_2,MSUALG_5,ORDERS_2,TARSKI,ENUMSET1,ORDINAL1,ORDINAL3,WELLORD2,TREES_2,PARTFUN1,GRFUNC_1,FUNCT_6,MCART_1,FINSEQ_5,NAT_1,INT_1,BINOP_1,ZFMISC_1,FUNCT_1,FUNCT_2,FILTER_0,LATTICES,LATTICE3,YELLOW_0,YELLOW_2,YELLOW_3,YELLOW_5,WAYBEL_0,WAYBEL_1,WAYBEL_6,RELSET_1,CARD_1,FINSEQ_3,SETFAM_1,XBOOLE_0,XBOOLE_1,ORDERS_1,FUNCOP_1,XREAL_1,XXREAL_0,XXREAL_2,XREAL_0,CKB1,CKB2,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB20,CKB21;
schemes DOMAIN_1,FUNCT_2,RELSET_1,RECDEF_1,ORDINAL2,NAT_1,FINSEQ_1,CLASSES1,BINOP_1;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,PARTFUN1,FUNCOP_1,XREAL_0,CARD_1,MEMBERED,FINSEQ_1,ABIAN,STRUCT_0,LATTICES,LATTICE3,YELLOW_0,YELLOW_1,RELAT_1,XXREAL_2,RELSET_1,FINSEQ_2,FUNCT_1,CKB5,CKB14,CKB15,CKB17,CKB19;
constructors SETFAM_1,BINOP_1,DOMAIN_1,ORDINAL2,NAT_1,CLASSES1,SEQ_4,FINSOP_1,FUNCT_6,RFUNCT_3,BINARITH,ABIAN,LATTICE3,MSUALG_5,YELLOW_2,NAT_D,RELSET_1,CKB4,CKB20;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve X for non  empty set;
reserve x for set;
reserve y for set;
Lm1:now
let i being (Element of ( NAT ));
let n being (Element of ( NAT ));
let m being (Element of ( NAT ));
assume (1 <= i & i < ( n + m ));
then (((1 <= i & i < n) or (n = i & i < ( n + m ))) or (n < i & i < ( n + m ))) by XXREAL_0:1;
hence (((1 <= i & i < n) or (n = i & i < ( n + m ))) or (( n + 1 ) <= i & i < ( n + m ))) by NAT_1:13;
end;
theorem
Th14: (for x,y being set holds (for R1,R2 being Relation holds (for n,m being (Element of ( NAT )) holds ((((n <= m & R1 is_reflexive_in X) & R2 is_reflexive_in X) & (ex f being non  empty (FinSequence of X) st (( len f ) = n & x,y are_joint_by f,R1,R2))) implies (ex h being non  empty (FinSequence of X) st (( len h ) = m & x,y are_joint_by h,R1,R2))))))
proof
let x being set;
let y being set;
let R1 being Relation;
let R2 being Relation;
let n being (Element of ( NAT ));
let m being (Element of ( NAT ));
assume that
A1: n <= m
and
A2: R1 is_reflexive_in X
and
A3: R2 is_reflexive_in X;
given f being non  empty (FinSequence of X) such that
A4: ( len f ) = n
and
A5: x,y are_joint_by f,R1,R2;

A6: ( f . ( len f ) ) = y by A5,CKB20:def 1;
per cases  by A1,XXREAL_0:1;
suppose A7: n < m;

( len f ) in ( dom f ) by FINSEQ_5:6;
then y in ( rng f ) by A6,FUNCT_1:def 3;
then reconsider y9 = y as (Element of X);
reconsider i = ( m - n ) as (Element of ( NAT )) by A1,INT_1:5;
reconsider g = ( i |-> y9 ) as (FinSequence of X);
i > ( 0 ) by A7,XREAL_1:50;
then reconsider g as non  empty (FinSequence of X);
A8: 1 in ( dom g ) by FINSEQ_5:6;
reconsider h = ( f ^ g ) as non  empty (FinSequence of X);
take h;
A9: ( len g ) = ( m - n ) by CARD_1:def 7;
A10: y,y are_joint_by g,R1,R2 by A2,A3,CKB21:1;
thus ( len h ) = ( ( len f ) + ( len g ) ) by FINSEQ_1:22
.= ( n + ( m - n ) ) by A4,CARD_1:def 7
.= m;
A11: ( len g ) in ( dom g ) by FINSEQ_5:6;
thus x,y are_joint_by h,R1,R2
proof
( rng f ) <> ( {} );
then 1 in ( dom f ) by FINSEQ_3:32;
hence ( h . 1 ) = ( f . 1 ) by FINSEQ_1:def 7
.= x by A5,CKB20:def 1;
thus ( h . ( len h ) ) = ( h . ( ( len f ) + ( len g ) ) ) by FINSEQ_1:22
.= ( g . ( len g ) ) by A11,FINSEQ_1:def 7
.= y by A10,CKB20:def 1;
let j being (Element of ( NAT ));
A12: ( dom f ) = ( Seg ( len f ) ) by FINSEQ_1:def 3;
assume A13: (1 <= j & j < ( len h ));
thus (j is  odd implies [ ( h . j ),( h . ( j + 1 ) ) ] in R1)
proof
assume A14: j is  odd;
per cases  by A13,Lm1,FINSEQ_1:22;
suppose A15: (1 <= j & j < ( len f ));

then (1 <= ( j + 1 ) & ( j + 1 ) <= ( len f )) by NAT_1:13;
then ( j + 1 ) in ( dom f ) by A12;
then A16: ( f . ( j + 1 ) ) = ( h . ( j + 1 ) ) by FINSEQ_1:def 7;
j in ( dom f ) by A12,A15;
then ( f . j ) = ( h . j ) by FINSEQ_1:def 7;
hence thesis by A5,A14,A15,A16,CKB20:def 1;
end;
suppose A17: j = ( len f );

then j in ( dom f ) by FINSEQ_5:6;
then A18: ( h . j ) = y by A6,A17,FINSEQ_1:def 7;
( h . ( j + 1 ) ) = ( g . 1 ) by A8,A17,FINSEQ_1:def 7
.= y by A10,CKB20:def 1;
hence thesis by A2,A18,RELAT_2:def 1;
end;
suppose A19: (( ( len f ) + 1 ) <= j & j < ( ( len f ) + ( len g ) ));

then ( j + 1 ) <= ( ( len f ) + ( len g ) ) by NAT_1:13;
then A20: ( j + 1 ) <= ( len h ) by FINSEQ_1:22;
A21: 1 <= ( j - ( len f ) ) by A19,XREAL_1:19;
then ( 0 ) < ( j - ( len f ) ) by XXREAL_0:2;
then A22: ( ( 0 ) + ( len f ) ) < ( ( j - ( len f ) ) + ( len f ) ) by XREAL_1:6;
then reconsider k = ( j - ( len f ) ) as (Element of ( NAT )) by INT_1:5;
A23: ( j - ( len f ) ) < ( ( ( len f ) + ( len g ) ) - ( len f ) ) by A19,XREAL_1:9;
then A24: ( k + 1 ) <= ( len g ) by NAT_1:13;
j < ( j + 1 ) by XREAL_1:29;
then ( len f ) < ( j + 1 ) by A22,XXREAL_0:2;
then A25: ( h . ( j + 1 ) ) = ( g . ( ( j + 1 ) - ( len f ) ) ) by A20,FINSEQ_1:24
.= ( g . ( k + 1 ) );
1 <= ( k + 1 ) by A21,NAT_1:13;
then ( k + 1 ) in ( Seg ( len g ) ) by A24;
then A26: ( g . ( k + 1 ) ) = y by A9,FUNCOP_1:7;
k in ( Seg ( len g ) ) by A21,A23;
then ( g . k ) = y by A9,FUNCOP_1:7;
then ( h . j ) = y by A19,FINSEQ_1:23;
hence thesis by A2,A26,A25,RELAT_2:def 1;
end;
end;

assume A27: j is  even;
per cases  by A13,Lm1,FINSEQ_1:22;
suppose A28: (1 <= j & j < ( len f ));

then (1 <= ( j + 1 ) & ( j + 1 ) <= ( len f )) by NAT_1:13;
then ( j + 1 ) in ( dom f ) by A12;
then A29: ( f . ( j + 1 ) ) = ( h . ( j + 1 ) ) by FINSEQ_1:def 7;
j in ( dom f ) by A12,A28;
then ( f . j ) = ( h . j ) by FINSEQ_1:def 7;
hence thesis by A5,A27,A28,A29,CKB20:def 1;
end;
suppose A30: j = ( len f );

then j in ( dom f ) by FINSEQ_5:6;
then A31: ( h . j ) = y by A6,A30,FINSEQ_1:def 7;
( h . ( j + 1 ) ) = ( g . 1 ) by A8,A30,FINSEQ_1:def 7
.= y by A10,CKB20:def 1;
hence thesis by A3,A31,RELAT_2:def 1;
end;
suppose A32: (( ( len f ) + 1 ) <= j & j < ( ( len f ) + ( len g ) ));

then ( j + 1 ) <= ( ( len f ) + ( len g ) ) by NAT_1:13;
then A33: ( j + 1 ) <= ( len h ) by FINSEQ_1:22;
A34: 1 <= ( j - ( len f ) ) by A32,XREAL_1:19;
then ( 0 ) < ( j - ( len f ) ) by XXREAL_0:2;
then A35: ( ( 0 ) + ( len f ) ) < ( ( j - ( len f ) ) + ( len f ) ) by XREAL_1:6;
then reconsider k = ( j - ( len f ) ) as (Element of ( NAT )) by INT_1:5;
A36: ( j - ( len f ) ) < ( ( ( len f ) + ( len g ) ) - ( len f ) ) by A32,XREAL_1:9;
then A37: ( k + 1 ) <= ( len g ) by NAT_1:13;
j < ( j + 1 ) by XREAL_1:29;
then ( len f ) < ( j + 1 ) by A35,XXREAL_0:2;
then A38: ( h . ( j + 1 ) ) = ( g . ( ( j + 1 ) - ( len f ) ) ) by A33,FINSEQ_1:24
.= ( g . ( k + 1 ) );
1 <= ( k + 1 ) by A34,NAT_1:13;
then ( k + 1 ) in ( Seg ( len g ) ) by A37;
then A39: ( g . ( k + 1 ) ) = y by A9,FUNCOP_1:7;
k in ( Seg ( len g ) ) by A34,A36;
then ( g . k ) = y by A9,FUNCOP_1:7;
then ( h . j ) = y by A32,FINSEQ_1:23;
hence thesis by A3,A39,A38,RELAT_2:def 1;
end;
end;

end;
suppose n = m;

hence thesis by A4,A5;
end;
end;
