environ
vocabularies NUMBERS,FUNCT_1,FUNCOP_1,TARSKI,RELAT_1,FUNCT_6,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,ORDERS_2,LATTICE3,MSUALG_5,STRUCT_0,EQREL_1,PBOOLE,LATTICES,XXREAL_0,REWRITE1,SETFAM_1,RELAT_2,WAYBEL_0,GROUP_6,YELLOW_0,ORDINAL2,CAT_1,FINSEQ_1,ARYTM_3,ABIAN,FINSEQ_2,ARYTM_1,CARD_1,ORDINAL4,NAT_1,VALUED_0,FUNCT_2,MCART_1,PARTFUN1,LATTICE5;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,RELAT_1,RELAT_2,FUNCT_1,RELSET_1,FUNCT_2,FUNCT_6,CARD_1,NUMBERS,XCMPLX_0,NAT_1,NAT_D,SETFAM_1,ORDINAL1,ORDINAL2,MCART_1,DOMAIN_1,PARTFUN1,FUNCOP_1,STRUCT_0,ORDERS_2,EQREL_1,MSUALG_5,FINSEQ_1,FINSEQ_2,SEQ_4,LATTICES,LATTICE3,BINOP_1,YELLOW_0,WAYBEL_0,YELLOW_2,ABIAN,XXREAL_0,CKB4,CKB13,CKB16,CKB18,CKB20,CKB23,CKB25,CKB26,CKB27,CKB28,CKB29,CKB31,CKB32,CKB35,CKB37,CKB42,CKB44,CKB50,CKB51,CKB53,CKB54,CKB60,CKB67,CKB69,CKB70,CKB71,CKB73,CKB76;
definitions TARSKI,LATTICE3,FUNCOP_1,WAYBEL_0,XBOOLE_0,BINOP_1,FINSEQ_1,FINSEQ_2,CKB4,CKB13,CKB20,CKB23,CKB27,CKB28,CKB29,CKB32,CKB35,CKB37,CKB42,CKB44,CKB50,CKB51,CKB53,CKB54,CKB67,CKB69,CKB71,CKB73,CKB76;
theorems EQREL_1,RELAT_1,RELAT_2,FINSEQ_1,FINSEQ_2,MSUALG_5,ORDERS_2,TARSKI,ENUMSET1,ORDINAL1,ORDINAL3,WELLORD2,TREES_2,PARTFUN1,GRFUNC_1,FUNCT_6,MCART_1,FINSEQ_5,NAT_1,INT_1,BINOP_1,ZFMISC_1,FUNCT_1,FUNCT_2,FILTER_0,LATTICES,LATTICE3,YELLOW_0,YELLOW_2,YELLOW_3,YELLOW_5,WAYBEL_0,WAYBEL_1,WAYBEL_6,RELSET_1,CARD_1,FINSEQ_3,SETFAM_1,XBOOLE_0,XBOOLE_1,ORDERS_1,FUNCOP_1,XREAL_1,XXREAL_0,XXREAL_2,XREAL_0,CKB1,CKB2,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB20,CKB21,CKB22,CKB23,CKB24,CKB27,CKB28,CKB29,CKB32,CKB33,CKB34,CKB35,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB69,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80;
schemes DOMAIN_1,FUNCT_2,RELSET_1,RECDEF_1,ORDINAL2,NAT_1,FINSEQ_1,CLASSES1,BINOP_1;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,PARTFUN1,FUNCOP_1,XREAL_0,CARD_1,MEMBERED,FINSEQ_1,ABIAN,STRUCT_0,LATTICES,LATTICE3,YELLOW_0,YELLOW_1,RELAT_1,XXREAL_2,RELSET_1,FINSEQ_2,FUNCT_1,CKB5,CKB14,CKB15,CKB17,CKB19,CKB30,CKB36,CKB48,CKB68;
constructors SETFAM_1,BINOP_1,DOMAIN_1,ORDINAL2,NAT_1,CLASSES1,SEQ_4,FINSOP_1,FUNCT_6,RFUNCT_3,BINARITH,ABIAN,LATTICE3,MSUALG_5,YELLOW_2,NAT_D,RELSET_1,CKB4,CKB20,CKB23,CKB26,CKB27,CKB28,CKB29,CKB32,CKB35,CKB37,CKB42,CKB44,CKB50,CKB51,CKB53,CKB54,CKB60,CKB67,CKB69,CKB70,CKB71,CKB73,CKB76;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve X for non  empty set;
reserve e for (Equivalence_Relation of X);
reserve e1 for (Equivalence_Relation of X);
reserve e2 for (Equivalence_Relation of X);
reserve x for set;
reserve y for set;
reserve A for non  empty set;
reserve L for  lower-bounded LATTICE;
Lm2:now
let j being (Element of ( NAT ));
assume that
A1: 1 <= j
and
A2: j < 5;
j < ( 4 + 1 ) by A2;
then j <= 4 by NAT_1:13;
then ((((j = ( 0 ) or j = 1) or j = 2) or j = 3) or j = 4) by NAT_1:28;
hence (((j = 1 or j = 2) or j = 3) or j = 4) by A1;
end;
Lm3:now
let m being (Element of ( NAT ));
assume A1: m in ( Seg 5 );
then m <= 5 by FINSEQ_1:1;
then (((((m = ( 0 ) or m = 1) or m = 2) or m = 3) or m = 4) or m = 5) by NAT_1:29;
hence ((((m = 1 or m = 2) or m = 3) or m = 4) or m = 5) by A1,FINSEQ_1:1;
end;
Lm4:now
let A;
let L;
let d being (distance_function of A,L);
(( succ ( {} ) ) c= ( DistEsti d ) or ( DistEsti d ) in ( succ ( {} ) )) by ORDINAL1:16;
then (( succ ( {} ) ) c= ( DistEsti d ) or ( DistEsti d ) c= ( {} )) by ORDINAL1:22;
hence ( succ ( {} ) ) c= ( DistEsti d ) by CKB43:1,XBOOLE_1:3;
end;
theorem
(ex A being non  empty set st (ex f being (Homomorphism of L,( EqRelLATT A )) st (f is  one-to-one & ( type_of ( Image f ) ) <= 3)))
proof
set A = (the carrier of L);
set D = ( BasicDF L );
set S = the (ExtensionSeq of A,D);
set FS = ( union { ( ( S . i ) `1 ) where i is (Element of ( NAT )): (not contradiction) } );
A1: ( ( S . ( 0 ) ) `1 ) in { ( ( S . i ) `1 ) where i is (Element of ( NAT )): (not contradiction) };
A2: ( S . ( 0 ) ) = [ A,D ] by CKB73:def 1;
then ( ( S . ( 0 ) ) `1 ) = A by MCART_1:def 1;
then A c= FS by A1,ZFMISC_1:74;
then reconsider FS as non  empty set;
reconsider FD = ( union { ( ( S . i ) `2 ) where i is (Element of ( NAT )): (not contradiction) } ) as (distance_function of FS,L) by CKB78:1;
( alpha FD ) is  join-preserving
proof
set f = ( alpha FD );
let a being (Element of L);
let b being (Element of L);
A3:  ex_sup_of ( f .: { a,b } ),( EqRelLATT FS ) by YELLOW_0:17;
consider e3 being (Equivalence_Relation of FS) such that A4: e3 = ( f . ( a "\/" b ) ) and A5: (for x,y being (Element of FS) holds ([ x,y ] in e3 iff ( FD . (x,y) ) <= ( a "\/" b ))) by CKB32:def 1;
consider e2 being (Equivalence_Relation of FS) such that A6: e2 = ( f . b ) and A7: (for x,y being (Element of FS) holds ([ x,y ] in e2 iff ( FD . (x,y) ) <= b)) by CKB32:def 1;
consider e1 being (Equivalence_Relation of FS) such that A8: e1 = ( f . a ) and A9: (for x,y being (Element of FS) holds ([ x,y ] in e1 iff ( FD . (x,y) ) <= a)) by CKB32:def 1;
A10: ( field e2 ) = FS by ORDERS_1:12;
now
let x being set;
let y being set;
A11: b <= ( b "\/" a ) by YELLOW_0:22;
assume A12: [ x,y ] in e2;
then reconsider x9 = x,y9 = y as (Element of FS) by A10,RELAT_1:15;
( FD . (x9,y9) ) <= b by A7,A12;
then ( FD . (x9,y9) ) <= ( b "\/" a ) by A11,ORDERS_2:3;
hence [ x,y ] in e3 by A5;
end;
then A13: e2 c= e3 by RELAT_1:def 3;
A14: ( field e3 ) = FS by ORDERS_1:12;
(for u,v being set holds ([ u,v ] in e3 implies [ u,v ] in ( e1 "\/" e2 )))
proof
let u being set;
let v being set;
A15: 3 in ( Seg 5 );
assume A16: [ u,v ] in e3;
then reconsider x = u,y = v as (Element of FS) by A14,RELAT_1:15;
( FD . (x,y) ) <= ( a "\/" b ) by A5,A16;
then consider z1,z2,z3 being (Element of FS) such that A17: ( FD . (x,z1) ) = a and A18: ( FD . (z2,z3) ) = a and A19: ( FD . (z1,z2) ) = b and A20: ( FD . (z3,y) ) = b by CKB79:1;
A21: u in FS by A14,A16,RELAT_1:15;
defpred P[ set,set ]
 means
((((($1 = 1 implies $2 = x) & ($1 = 2 implies $2 = z1)) & ($1 = 3 implies $2 = z2)) & ($1 = 4 implies $2 = z3)) & ($1 = 5 implies $2 = y));
A22: (for m being Nat holds (m in ( Seg 5 ) implies (ex w being set st P[ m,w ])))
proof
let m being Nat;
assume A23: m in ( Seg 5 );
per cases  by A23,Lm3;
suppose A24: m = 1;

take x;
thus thesis by A24;
end;
suppose A25: m = 2;

take z1;
thus thesis by A25;
end;
suppose A26: m = 3;

take z2;
thus thesis by A26;
end;
suppose A27: m = 4;

take z3;
thus thesis by A27;
end;
suppose A28: m = 5;

take y;
thus thesis by A28;
end;
end;
(ex p being FinSequence st (( dom p ) = ( Seg 5 ) & (for k being Nat holds (k in ( Seg 5 ) implies P[ k,( p . k ) ])))) from FINSEQ_1:sch 1(A22);
then consider h being FinSequence such that A29: ( dom h ) = ( Seg 5 ) and A30: (for m being Nat holds (m in ( Seg 5 ) implies (((((m = 1 implies ( h . m ) = x) & (m = 2 implies ( h . m ) = z1)) & (m = 3 implies ( h . m ) = z2)) & (m = 4 implies ( h . m ) = z3)) & (m = 5 implies ( h . m ) = y))));
A31: ( len h ) = 5 by A29,FINSEQ_1:def 3;
A32: 5 in ( Seg 5 );
A33: 4 in ( Seg 5 );
A34: 1 in ( Seg 5 );
then A35: u = ( h . 1 ) by A30;
A36: 2 in ( Seg 5 );
A37: (for j being (Element of ( NAT )) holds ((1 <= j & j < ( len h )) implies [ ( h . j ),( h . ( j + 1 ) ) ] in ( e1 \/ e2 )))
proof
let j being (Element of ( NAT ));
assume A38: (1 <= j & j < ( len h ));
per cases  by A31,A38,Lm2;
suppose A39: j = 1;

[ x,z1 ] in e1 by A9,A17;
then [ ( h . 1 ),z1 ] in e1 by A30,A34;
then [ ( h . 1 ),( h . 2 ) ] in e1 by A30,A36;
hence thesis by A39,XBOOLE_0:def 3;
end;
suppose A40: j = 3;

[ z2,z3 ] in e1 by A9,A18;
then [ ( h . 3 ),z3 ] in e1 by A30,A15;
then [ ( h . 3 ),( h . 4 ) ] in e1 by A30,A33;
hence thesis by A40,XBOOLE_0:def 3;
end;
suppose A41: j = 2;

[ z1,z2 ] in e2 by A7,A19;
then [ ( h . 2 ),z2 ] in e2 by A30,A36;
then [ ( h . 2 ),( h . 3 ) ] in e2 by A30,A15;
hence thesis by A41,XBOOLE_0:def 3;
end;
suppose A42: j = 4;

[ z3,y ] in e2 by A7,A20;
then [ ( h . 4 ),y ] in e2 by A30,A33;
then [ ( h . 4 ),( h . 5 ) ] in e2 by A30,A32;
hence thesis by A42,XBOOLE_0:def 3;
end;
end;
v = ( h . 5 ) by A30,A32
.= ( h . ( len h ) ) by A29,FINSEQ_1:def 3;
hence thesis by A21,A31,A35,A37,EQREL_1:28;
end;
then A43: e3 c= ( e1 "\/" e2 ) by RELAT_1:def 3;
A44: ( field e1 ) = FS by ORDERS_1:12;
now
let x being set;
let y being set;
A45: a <= ( a "\/" b ) by YELLOW_0:22;
assume A46: [ x,y ] in e1;
then reconsider x9 = x,y9 = y as (Element of FS) by A44,RELAT_1:15;
( FD . (x9,y9) ) <= a by A9,A46;
then ( FD . (x9,y9) ) <= ( a "\/" b ) by A45,ORDERS_2:3;
hence [ x,y ] in e3 by A5;
end;
then e1 c= e3 by RELAT_1:def 3;
then ( e1 \/ e2 ) c= e3 by A13,XBOOLE_1:8;
then A47: ( e1 "\/" e2 ) c= e3 by EQREL_1:def 2;
( dom f ) = (the carrier of L) by FUNCT_2:def 1;
then ( sup ( f .: { a,b } ) ) = ( sup { ( f . a ),( f . b ) } ) by FUNCT_1:60
.= ( ( f . a ) "\/" ( f . b ) ) by YELLOW_0:41
.= ( e1 "\/" e2 ) by A8,A6,CKB12:1
.= ( f . ( a "\/" b ) ) by A4,A47,A43,XBOOLE_0:def 10
.= ( f . ( sup { a,b } ) ) by YELLOW_0:41;
hence thesis by A3,WAYBEL_0:def 31;
end;
then reconsider f = ( alpha FD ) as (Homomorphism of L,( EqRelLATT FS )) by CKB33:1;
A48: ( dom f ) = (the carrier of L) by FUNCT_2:def 1;
A49: ( Image f ) = ( subrelstr ( rng f ) ) by YELLOW_2:def 2;
A50: (ex e being (Equivalence_Relation of FS) st (e in (the carrier of ( Image f )) & e <> ( id FS )))
proof
A51: { A } <> { { A } }
proof
assume { A } = { { A } };
then { A } in { A } by TARSKI:def 1;
hence contradiction;
end;
consider A9 being non  empty set,d9 being (distance_function of A9,L),Aq9 being non  empty set,dq9 being (distance_function of Aq9,L) such that A52: Aq9,dq9 is_extension_of A9,d9 and A53: ( S . ( 0 ) ) = [ A9,d9 ] and A54: ( S . ( ( 0 ) + 1 ) ) = [ Aq9,dq9 ] by CKB73:def 1;
(A9 = A & d9 = D) by A2,A53,ZFMISC_1:27;
then consider q being (QuadrSeq of D) such that A55: Aq9 = ( NextSet D ) and A56: dq9 = ( NextDelta q ) by A52,CKB71:def 1;
( ConsecutiveSet (A,( {} )) ) = A by CKB45:1;
then reconsider Q = ( Quadr (q,( {} )) ) as (Element of [: A,A,(the carrier of L),(the carrier of L) :]);
A57: ( ( S . 1 ) `2 ) in { ( ( S . i ) `2 ) where i is (Element of ( NAT )): (not contradiction) };
( succ ( {} ) ) c= ( DistEsti D ) by Lm4;
then ( {} ) in ( DistEsti D ) by ORDINAL1:21;
then A58: ( {} ) in ( dom q ) by CKB52:1;
then ( q . ( {} ) ) in ( rng q ) by FUNCT_1:def 3;
then ( q . ( {} ) ) in { [ u,v,a9,b9 ] where u is (Element of A),v is (Element of A),a9 is (Element of L),b9 is (Element of L): ( D . (u,v) ) <= ( a9 "\/" b9 ) } by CKB50:def 1;
then consider u,v being (Element of A),a,b being (Element of L) such that A59: ( q . ( {} ) ) = [ u,v,a,b ] and ( D . (u,v) ) <= ( a "\/" b );
consider e being (Equivalence_Relation of FS) such that A60: e = ( f . b ) and A61: (for x,y being (Element of FS) holds ([ x,y ] in e iff ( FD . (x,y) ) <= b)) by CKB32:def 1;
A62: ( Quadr (q,( {} )) ) = [ u,v,a,b ] by A58,A59,CKB51:def 1;
( ( S . 1 ) `2 ) = ( NextDelta q ) by A54,A56,MCART_1:def 2;
then A63: ( NextDelta q ) c= FD by A57,ZFMISC_1:74;
A64: { { A } } in { { A },{ { A } },{ { { A } } } } by ENUMSET1:def 1;
then A65: { { A } } in ( A \/ { { A },{ { A } },{ { { A } } } } ) by XBOOLE_0:def 3;
take e;
e in ( rng f ) by A48,A60,FUNCT_1:def 3;
hence e in (the carrier of ( Image f )) by A49,YELLOW_0:def 15;
A66: ( ( S . 1 ) `1 ) in { ( ( S . i ) `1 ) where i is (Element of ( NAT )): (not contradiction) };
( ( S . 1 ) `1 ) = ( NextSet D ) by A54,A55,MCART_1:def 1;
then A67: ( NextSet D ) c= FS by A66,ZFMISC_1:74;
( new_set A ) = ( new_set ( ConsecutiveSet (A,( {} )) ) ) by CKB45:1
.= ( ConsecutiveSet (A,( succ ( {} ) )) ) by CKB46:1;
then ( new_set A ) c= ( NextSet D ) by Lm4,CKB58:1;
then A68: ( new_set A ) c= FS by A67,XBOOLE_1:1;
A69: { { A } } in ( new_set A ) by A64,XBOOLE_0:def 3;
A70: { A } in { { A },{ { A } },{ { { A } } } } by ENUMSET1:def 1;
then { A } in ( A \/ { { A },{ { A } },{ { { A } } } } ) by XBOOLE_0:def 3;
then reconsider W = { A },V = { { A } } as (Element of FS) by A68,A69;
A71: (( ConsecutiveSet (A,( {} )) ) = A & ( ConsecutiveDelta (q,( {} )) ) = D) by CKB45:1,CKB55:1;
( ConsecutiveDelta (q,( succ ( {} ) )) ) = ( new_bi_fun (( BiFun (( ConsecutiveDelta (q,( {} )) ),( ConsecutiveSet (A,( {} )) ),L) ),( Quadr (q,( {} )) )) ) by CKB56:1
.= ( new_bi_fun (D,Q) ) by A71,CKB53:def 1;
then ( new_bi_fun (D,Q) ) c= ( NextDelta q ) by Lm4,CKB62:1;
then A72: ( new_bi_fun (D,Q) ) c= FD by A63,XBOOLE_1:1;
(( dom ( new_bi_fun (D,Q) ) ) = [: ( new_set A ),( new_set A ) :] & { A } in ( new_set A )) by A70,FUNCT_2:def 1,XBOOLE_0:def 3;
then [ { A },{ { A } } ] in ( dom ( new_bi_fun (D,Q) ) ) by A65,ZFMISC_1:87;
then ( FD . (W,V) ) = ( ( new_bi_fun (D,Q) ) . ({ A },{ { A } }) ) by A72,GRFUNC_1:2
.= ( Q `4 ) by CKB37:def 1
.= b by A62,MCART_1:def 11;
then [ { A },{ { A } } ] in e by A61;
hence thesis by A51,RELAT_1:def 10;
end;
take FS;
take f;
D is  onto by CKB77:1;
then A73: ( rng D ) = A by FUNCT_2:def 3;
(for w being set holds (w in A implies (ex z being set st (z in [: FS,FS :] & w = ( FD . z )))))
proof
let w being set;
A74: ( ( S . ( 0 ) ) `1 ) in { ( ( S . i ) `1 ) where i is (Element of ( NAT )): (not contradiction) };
A75: ( ( S . ( 0 ) ) `2 ) in { ( ( S . i ) `2 ) where i is (Element of ( NAT )): (not contradiction) };
A76: ( S . ( 0 ) ) = [ A,D ] by CKB73:def 1;
then D = ( ( S . ( 0 ) ) `2 ) by MCART_1:def 2;
then A77: D c= FD by A75,ZFMISC_1:74;
assume w in A;
then consider z being set such that A78: z in [: A,A :] and A79: ( D . z ) = w by A73,FUNCT_2:11;
take z;
A = ( ( S . ( 0 ) ) `1 ) by A76,MCART_1:def 1;
then A c= FS by A74,ZFMISC_1:74;
then [: A,A :] c= [: FS,FS :] by ZFMISC_1:96;
hence z in [: FS,FS :] by A78;
z in ( dom D ) by A78,FUNCT_2:def 1;
hence thesis by A79,A77,GRFUNC_1:2;
end;
then ( rng FD ) = A by FUNCT_2:10;
then FD is  onto by FUNCT_2:def 3;
hence f is  one-to-one by CKB34:1;
(for e1,e2 being (Equivalence_Relation of FS) holds (for x holds (for y holds (((e1 in (the carrier of ( Image f )) & e2 in (the carrier of ( Image f ))) & [ x,y ] in ( e1 "\/" e2 )) implies (ex F being non  empty (FinSequence of FS) st (( len F ) = ( 3 + 2 ) & x,y are_joint_by F,e1,e2)))))) by CKB80:1;
hence thesis by A50,CKB24:1;
end;
