environ
vocabularies NUMBERS,XBOOLE_0,RLVECT_1,SUBSET_1,ARYTM_1,RLTOPSP1,REAL_1,COMPLEX1,XXREAL_0,RELAT_1,TARSKI,ARYTM_3,RUSUB_4,RLSUB_1,STRUCT_0,SUPINF_2,SETFAM_1,CARD_1,PRE_TOPC,RLVECT_2,FINSEQ_1,FUNCT_1,CARD_3,NAT_1,FUNCT_2,VALUED_1,ORDINAL4,PARTFUN1,CIRCLED1;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,COMPLEX1,FUNCT_1,SETFAM_1,PARTFUN1,FUNCT_2,XXREAL_0,REAL_1,DOMAIN_1,STRUCT_0,PRE_TOPC,RLVECT_1,RUSUB_4,CONVEX1,NAT_1,FINSEQ_1,RLSUB_1,RLVECT_2,RVSUM_1,RLTOPSP1,RUSUB_5,CKB4,CKB12,CKB13,CKB22,CKB27,CKB29,CKB30,CKB31;
definitions TARSKI,XBOOLE_0,RLTOPSP1,RVSUM_1,CKB4,CKB12,CKB13,CKB22,CKB30,CKB31;
theorems TARSKI,XBOOLE_0,XBOOLE_1,ZFMISC_1,SUBSET_1,SETFAM_1,XCMPLX_0,FUNCT_1,RLVECT_1,RUSUB_4,CONVEX1,RLTOPSP1,RVSUM_1,FINSEQ_1,RLSUB_1,RUSUB_5,RLVECT_2,CARD_1,FINSEQ_3,FINSEQ_4,CARD_2,XREAL_1,FINSOP_1,PARTFUN1,RLVECT_4,CKB1,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37;
schemes XBOOLE_0,FINSEQ_1,SUBSET_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,RLVECT_1,RLTOPSP1,VALUED_0,FINSEQ_1,CARD_1,CKB3,CKB14,CKB26,CKB28;
constructors SETFAM_1,DOMAIN_1,XXREAL_0,REAL_1,BINOP_2,COMPLEX1,FINSOP_1,RVSUM_1,RUSUB_5,CONVEX1,RLTOPSP1,RELSET_1,CKB12,CKB13,CKB22,CKB30,CKB31;
requirements BOOLE,REAL,NUMERALS,SUBSET,ARITHM;
begin
theorem
(for V being RealLinearSpace holds (for v1,v2 being (VECTOR of V) holds (for L being (Linear_Combination of { v1,v2 }) holds ((v1 <> v2 & L is  circled) implies (((( ( L . v1 ) + ( L . v2 ) ) = 1 & ( L . v1 ) >= ( 0 )) & ( L . v2 ) >= ( 0 )) & ( Sum L ) = ( ( ( L . v1 ) * v1 ) + ( ( L . v2 ) * v2 ) ))))))
proof
let V being RealLinearSpace;
let v1 being (VECTOR of V);
let v2 being (VECTOR of V);
let L being (Linear_Combination of { v1,v2 });
assume that
A1: v1 <> v2
and
A2: L is  circled;
A3: (( Carrier L ) c= { v1,v2 } & ( Carrier L ) <> ( {} )) by A2,CKB23:1,RLVECT_2:def 6;
now
per cases  by A3,ZFMISC_1:36;
suppose A4: ( Carrier L ) = { v1 };

then (not v2 in ( Carrier L )) by A1,TARSKI:def 1;
then (not v2 in { v where v is (Element of V): ( L . v ) <> ( 0 ) }) by RLVECT_2:def 4;
then ( L . v2 ) = ( 0 );
hence ((( ( L . v1 ) + ( L . v2 ) ) = 1 & ( L . v1 ) >= ( 0 )) & ( L . v2 ) >= ( 0 )) by A2,A4,CKB35:1;
end;
suppose A5: ( Carrier L ) = { v2 };

then (not v1 in ( Carrier L )) by A1,TARSKI:def 1;
then (not v1 in { v where v is (Element of V): ( L . v ) <> ( 0 ) }) by RLVECT_2:def 4;
then ( L . v1 ) = ( 0 );
hence ((( ( L . v1 ) + ( L . v2 ) ) = 1 & ( L . v1 ) >= ( 0 )) & ( L . v2 ) >= ( 0 )) by A2,A5,CKB35:1;
end;
suppose ( Carrier L ) = { v1,v2 };

hence ((( ( L . v1 ) + ( L . v2 ) ) = 1 & ( L . v1 ) >= ( 0 )) & ( L . v2 ) >= ( 0 )) by A1,A2,CKB36:1;
end;
end;
hence thesis by A1,RLVECT_2:33;
end;
