environ
vocabularies NUMBERS,NAT_1,INT_1,RELAT_1,ARYTM_3,CARD_1,XXREAL_0,SUBSET_1,ARYTM_1,INT_2,COMPLEX1,ORDINAL1,ZFMISC_1,XBOOLE_0,FINSET_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,CARD_1,FINSET_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,NAT_1,INT_1,INT_2,CKB1,CKB2,CKB3,CKB4,CKB7;
definitions CKB1,CKB2,CKB7;
theorems ORDINAL1,XCMPLX_1,XREAL_1,XXREAL_0,NAT_1,INT_1,INT_2,ABSVALUE,XREAL_0,CARD_1,ZFMISC_1,COMPLEX1,XCMPLX_0,TARSKI,CKB1,CKB2,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14;
schemes NAT_1;
registrations XXREAL_0,XREAL_0,NAT_1,INT_1,ORDINAL1,XBOOLE_0,CARD_1,ZFMISC_1;
constructors XXREAL_0,NAT_1,INT_2,REAL_1,FINSET_1,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB7;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve h for Nat;
reserve i for Nat;
reserve j for Nat;
reserve t for Nat;
theorem
Th10: ((i divides j & i divides ( j + h )) implies i divides h)
proof
assume that
A1: i divides j
and
A2: i divides ( j + h );
consider t being Nat such that A3: ( j + h ) = ( i * t ) by A2,CKB7:def 1;
consider u being Nat such that A4: j = ( i * u ) by A1,CKB7:def 1;
now
assume A5: i <> ( 0 );
then A6: h = ( ( i * ( h div i ) ) + ( h mod i ) ) by INT_1:59;
A7: ( j + ( ( i * ( h div i ) ) + ( h mod i ) ) ) = ( ( i * ( u + ( h div i ) ) ) + ( h mod i ) ) by A4;
A8: ( h mod i ) < i by A5,CKB5:1;
( j + h ) = ( ( i * t ) + ( 0 ) ) by A3;
then ( h mod i ) = ( 0 ) by A6,A7,A8,NAT_1:18;
hence thesis by A6,CKB8:1;
end;
hence thesis by A3;
end;
