environ
vocabularies NUMBERS,NAT_1,INT_1,RELAT_1,ARYTM_3,CARD_1,XXREAL_0,SUBSET_1,ARYTM_1,INT_2,COMPLEX1,ORDINAL1,ZFMISC_1,XBOOLE_0,FINSET_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,CARD_1,FINSET_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,NAT_1,INT_1,INT_2,CKB1,CKB2,CKB3,CKB4,CKB7,CKB17,CKB18,CKB19,CKB20,CKB45;
definitions CKB1,CKB2,CKB7,CKB17,CKB19;
theorems ORDINAL1,XCMPLX_1,XREAL_1,XXREAL_0,NAT_1,INT_1,INT_2,ABSVALUE,XREAL_0,CARD_1,ZFMISC_1,COMPLEX1,XCMPLX_0,TARSKI,CKB1,CKB2,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB19,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB40,CKB41,CKB42,CKB43,CKB44,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79;
schemes NAT_1,CKB21,CKB39;
registrations XXREAL_0,XREAL_0,NAT_1,INT_1,ORDINAL1,XBOOLE_0,CARD_1,ZFMISC_1;
constructors XXREAL_0,NAT_1,INT_2,REAL_1,FINSET_1,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB7,CKB18,CKB20,CKB45;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
(for a,b being Integer holds (ex s,t being Integer st ( a gcd b ) = ( ( s * a ) + ( t * b ) )))
proof
let a being Integer,b being Integer;
A1: (for a,b being Integer holds ((a > ( 0 ) & b > ( 0 )) implies (ex s,t being Integer st ( a gcd b ) = ( ( s * a ) + ( t * b ) ))))
proof
let a being Integer,b being Integer;
assume that
A2: a > ( 0 )
and
A3: b > ( 0 );
reconsider a,b as (Element of ( NAT )) by A2,A3,INT_1:3;
set M = { z where z is (Element of ( NAT )): (ex s,t being Integer st z = ( ( s * a ) + ( t * b ) )) };
defpred P[ Nat ]
 means
($1 in M & $1 <> ( 0 ));
a = ( ( 1 * a ) + ( ( 0 ) * b ) );
then A4: a in M;
then A5: (ex k being Nat st P[ k ]) by A2;
consider g being Nat such that A6: (P[ g ] & (for n being Nat holds (P[ n ] implies g <= n))) from NAT_1:sch 5(A5);
set G = { zz where zz is (Element of ( NAT )): (ex s being (Element of ( NAT )) st zz = ( s * g )) };
(ex z being (Element of ( NAT )) st (z = g & (ex s,t being Integer st z = ( ( s * a ) + ( t * b ) )))) by A6;
then consider s being Integer,t being Integer such that A7: g = ( ( s * a ) + ( t * b ) );
A8: (for x being set holds (x in M implies x in G))
proof
let x being set;
assume x in M;
then consider x9 being (Element of ( NAT )) such that A9: x9 = x and A10: (ex u,v being Integer st x9 = ( ( u * a ) + ( v * b ) ));
consider u being Integer,v being Integer such that A11: x = ( ( u * a ) + ( v * b ) ) by A9,A10;
consider r being Nat such that A12: x9 = ( ( g * ( x9 div g ) ) + r ) and A13: r < g by A6,CKB1:def 1;
A14: r in ( NAT ) by ORDINAL1:def 12;
r = ( x9 - ( g * ( x9 div g ) ) ) by A12
.= ( ( a * ( u + ( - ( s * ( x9 div g ) ) ) ) ) + ( b * ( v + ( - ( t * ( x9 div g ) ) ) ) ) ) by A7,A9,A11;
then r in M by A14;
then r = ( 0 ) by A6,A13;
hence thesis by A9,A12;
end;
(for x being set holds (x in G implies x in M))
proof
let x being set;
assume x in G;
then A15: (ex x9 being (Element of ( NAT )) st (x9 = x & (ex u being (Element of ( NAT )) st x9 = ( u * g ))));
then consider u being Integer such that A16: x = ( u * g );
x = ( ( ( u * s ) * a ) + ( ( u * t ) * b ) ) by A7,A16;
hence thesis by A15;
end;
then A17: G = M by A8,TARSKI:1;
A18: ( abs b ) = b by ABSVALUE:def 1;
A19: ( abs a ) = a by ABSVALUE:def 1;
A20: (for m being Nat holds ((m divides ( abs a ) & m divides ( abs b )) implies m divides g))
proof
(ex g9 being (Element of ( NAT )) st (g9 = g & (ex s,t being Integer st g9 = ( ( s * a ) + ( t * b ) )))) by A6;
then consider s being Integer,t being Integer such that A21: g = ( ( s * a ) + ( t * b ) );
let m being Nat;
assume that
A22: m divides ( abs a )
and
A23: m divides ( abs b );
consider u being Nat such that A24: a = ( m * u ) by A19,A22,CKB7:def 1;
consider v being Nat such that A25: b = ( m * v ) by A18,A23,CKB7:def 1;
A26: g = ( m * ( ( s * u ) + ( t * v ) ) ) by A24,A25,A21;
then ( ( s * u ) + ( t * v ) ) >= ( 0 ) by A6;
then ( ( s * u ) + ( t * v ) ) is (Element of ( NAT )) by INT_1:3;
hence thesis by A26,CKB7:def 1;
end;
b = ( ( ( 0 ) * a ) + ( 1 * b ) );
then b in M;
then (ex b9 being (Element of ( NAT )) st (b9 = b & (ex t being (Element of ( NAT )) st b9 = ( t * g )))) by A17;
then A27: g divides ( abs b ) by A18,CKB7:def 1;
(ex a9 being (Element of ( NAT )) st (a9 = a & (ex s being (Element of ( NAT )) st a9 = ( s * g )))) by A4,A17;
then g divides ( abs a ) by A19,CKB7:def 1;
then g = ( ( abs a ) gcd ( abs b ) ) by A27,A20,CKB19:def 1
.= ( a gcd b ) by INT_2:34;
hence thesis by A7;
end;
now
per cases ;
case A28: (a = ( 0 ) or b = ( 0 ));
A29: (for a,b being Integer holds (a = ( 0 ) implies ( a gcd b ) = ( abs b )))
proof
let a being Integer,b being Integer;
assume a = ( 0 );
then ( abs a ) = ( 0 ) by ABSVALUE:def 1;
then A30: ( abs b ) divides ( abs a ) by CKB11:1;
(( a gcd b ) = ( ( abs a ) gcd ( abs b ) ) & (for m being Nat holds ((m divides ( abs a ) & m divides ( abs b )) implies m divides ( abs b )))) by INT_2:34;
hence thesis by A30,CKB19:def 1;
end;
now
per cases  by A28;
case a = ( 0 );
then A31: ( a gcd b ) = ( abs b ) by A29;
now
per cases ;
case b >= ( 0 );
hence ( a gcd b ) = ( ( ( 0 ) * a ) + ( 1 * b ) ) by A31,ABSVALUE:def 1;
end;
case b < ( 0 );
hence ( a gcd b ) = ( - ( b * 1 ) ) by A31,ABSVALUE:def 1
.= ( ( ( 0 ) * a ) + ( ( - 1 ) * b ) );
end;
end;
hence thesis;
end;
case b = ( 0 );
then A32: ( a gcd b ) = ( abs a ) by A29;
now
per cases ;
case a >= ( 0 );
hence ( a gcd b ) = ( ( 1 * a ) + ( ( 0 ) * b ) ) by A32,ABSVALUE:def 1;
end;
case a < ( 0 );
hence ( a gcd b ) = ( - ( a * 1 ) ) by A32,ABSVALUE:def 1
.= ( ( ( 0 ) * b ) + ( ( - 1 ) * a ) );
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
case A33: (a <> ( 0 ) & b <> ( 0 ));
now
per cases ;
case (a >= ( 0 ) & b >= ( 0 ));
hence thesis by A1,A33;
end;
case A34: (a < ( 0 ) & b >= ( 0 ));
then ( - a ) > ( 0 ) by XREAL_1:58;
then consider s being Integer,t being Integer such that A35: ( ( - a ) gcd b ) = ( ( s * ( - a ) ) + ( t * b ) ) by A1,A33,A34;
A36: ( a gcd b ) = ( ( abs a ) gcd ( abs b ) ) by INT_2:34
.= ( ( abs ( - a ) ) gcd ( abs b ) ) by COMPLEX1:52
.= ( ( - a ) gcd b ) by INT_2:34;
( ( s * ( - a ) ) + ( t * b ) ) = ( ( ( - s ) * a ) + ( t * b ) );
hence thesis by A35,A36;
end;
case A37: (a >= ( 0 ) & b < ( 0 ));
then ( - b ) > ( 0 ) by XREAL_1:58;
then consider s being Integer,t being Integer such that A38: ( a gcd ( - b ) ) = ( ( s * a ) + ( t * ( - b ) ) ) by A1,A33,A37;
A39: ( a gcd b ) = ( ( abs a ) gcd ( abs b ) ) by INT_2:34
.= ( ( abs a ) gcd ( abs ( - b ) ) ) by COMPLEX1:52
.= ( a gcd ( - b ) ) by INT_2:34;
( ( s * a ) + ( t * ( - b ) ) ) = ( ( s * a ) + ( ( - t ) * b ) );
hence thesis by A38,A39;
end;
case (a < ( 0 ) & b < ( 0 ));
then (( - a ) > ( 0 ) & ( - b ) > ( 0 )) by XREAL_1:58;
then consider s being Integer,t being Integer such that A40: ( ( - a ) gcd ( - b ) ) = ( ( s * ( - a ) ) + ( t * ( - b ) ) ) by A1;
A41: ( a gcd b ) = ( ( abs a ) gcd ( abs b ) ) by INT_2:34
.= ( ( abs a ) gcd ( abs ( - b ) ) ) by COMPLEX1:52
.= ( ( abs ( - a ) ) gcd ( abs ( - b ) ) ) by COMPLEX1:52
.= ( ( - a ) gcd ( - b ) ) by INT_2:34;
( ( s * ( - a ) ) + ( t * ( - b ) ) ) = ( ( ( - s ) * a ) + ( ( - t ) * b ) );
hence thesis by A40,A41;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
