environ
vocabularies ORDINAL2,ORDINAL1,TARSKI,XBOOLE_0,SETFAM_1,RELAT_1,FUNCT_1,SUBSET_1,ORDINAL3;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,SETFAM_1,ORDINAL2;
definitions ORDINAL2,ORDINAL1,TARSKI,XBOOLE_0;
theorems TARSKI,XBOOLE_0,FUNCT_1,ORDINAL1,SETFAM_1,ORDINAL2,XBOOLE_1,ZFMISC_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41;
schemes ORDINAL1,ORDINAL2,XBOOLE_0;
registrations XBOOLE_0,ORDINAL1,ORDINAL2,CKB12,CKB13;
constructors SETFAM_1,ORDINAL2;
requirements SUBSET,BOOLE,NUMERALS;
begin
reserve fi for Ordinal-Sequence;
reserve A for Ordinal;
reserve C for Ordinal;
reserve x for set;
definition
let C;
let fi;
func C +^ fi -> Ordinal-Sequence means 
:Def2: (( dom it ) = ( dom fi ) & (for A holds (A in ( dom fi ) implies ( it . A ) = ( C +^ ( fi . A ) ))));
existence
proof
deffunc F(Ordinal) = ( C +^ ( fi . $1 ) );
thus (ex F being Ordinal-Sequence st (( dom F ) = ( dom fi ) & (for A holds (A in ( dom fi ) implies ( F . A ) = F(A))))) from ORDINAL2:sch 3;
end;
uniqueness
proof
let f1 being Ordinal-Sequence;
let f2 being Ordinal-Sequence;
assume that
A1: ( dom f1 ) = ( dom fi )
and
A2: (for A holds (A in ( dom fi ) implies ( f1 . A ) = ( C +^ ( fi . A ) )))
and
A3: ( dom f2 ) = ( dom fi )
and
A4: (for A holds (A in ( dom fi ) implies ( f2 . A ) = ( C +^ ( fi . A ) )));
now
let x;
assume A5: x in ( dom fi );
then reconsider A = x as Ordinal;
thus ( f1 . x ) = ( C +^ ( fi . A ) ) by A2,A5
.= ( f2 . x ) by A4,A5;
end;
hence thesis by A1,A3,FUNCT_1:2;
end;
end;
