environ
vocabularies ORDINAL2,ORDINAL1,TARSKI,XBOOLE_0,SETFAM_1,RELAT_1,FUNCT_1,SUBSET_1,ORDINAL3;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,SETFAM_1,ORDINAL2,CKB42,CKB43,CKB44,CKB45;
definitions ORDINAL2,ORDINAL1,TARSKI,XBOOLE_0,CKB42,CKB43,CKB44,CKB45;
theorems TARSKI,XBOOLE_0,FUNCT_1,ORDINAL1,SETFAM_1,ORDINAL2,XBOOLE_1,ZFMISC_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53;
schemes ORDINAL1,ORDINAL2,XBOOLE_0;
registrations XBOOLE_0,ORDINAL1,ORDINAL2,CKB12,CKB13;
constructors SETFAM_1,ORDINAL2,CKB42,CKB43,CKB44,CKB45;
requirements SUBSET,BOOLE,NUMERALS;
begin
reserve A for Ordinal;
reserve B for Ordinal;
reserve C for Ordinal;
reserve D for Ordinal;
theorem
Th55: (A <> ( {} ) implies (ex C st (ex D st (B = ( ( C *^ A ) +^ D ) & D in A))))
proof
defpred I[ Ordinal ]
 means
(ex C st (ex D st ($1 = ( ( C *^ A ) +^ D ) & D in A)));
assume A1: A <> ( {} );
A2: (for B holds (((B <> ( {} ) & B is  limit_ordinal) & (for A holds (A in B implies I[ A ]))) implies I[ B ]))
proof
( {} ) in A by A1,CKB8:1;
then A3: ( succ ( {} ) ) c= A by ORDINAL1:21;
let B;
assume that
B <> ( {} )
and
A4: B is  limit_ordinal
and
(for A holds (A in B implies I[ A ]));
defpred P[ Ordinal ]
 means
($1 in B & B in ( $1 *^ A ));
( B *^ 1 ) = B by ORDINAL2:39;
then A5: B c= ( B *^ A ) by A3,ORDINAL2:42;
A6:now
assume B <> ( B *^ A );
then B c< ( B *^ A ) by A5,XBOOLE_0:def 8;
then B in ( B *^ A ) by ORDINAL1:11;
then A7: (ex C st P[ C ]) by A4,CKB48:1;
consider C such that A8: P[ C ] and A9: (for C1 being Ordinal holds (P[ C1 ] implies C c= C1)) from ORDINAL1:sch 1(A7);
now
assume C is  limit_ordinal;
then consider C1 being Ordinal such that A10: C1 in C and A11: B in ( C1 *^ A ) by A8,CKB48:1;
C1 in B by A8,A10,ORDINAL1:10;
hence contradiction by A9,A10,A11,ORDINAL1:5;
end;
then consider C1 being Ordinal such that A12: C = ( succ C1 ) by ORDINAL1:29;
A13: C1 in C by A12,ORDINAL1:6;
then C1 in B by A8,ORDINAL1:10;
then (not B in ( C1 *^ A )) by A9,A13,ORDINAL1:5;
then consider D such that A14: B = ( ( C1 *^ A ) +^ D ) by CKB30:1,ORDINAL1:16;
thus I[ B ]
proof
take C1;
take D;
thus B = ( ( C1 *^ A ) +^ D ) by A14;
( ( C1 *^ A ) +^ D ) in ( ( C1 *^ A ) +^ A ) by A8,A12,A14,ORDINAL2:36;
hence thesis by CKB25:1;
end;

end;
(B = ( B *^ A ) implies (B = ( ( B *^ A ) +^ ( {} ) ) & ( {} ) in A)) by A1,CKB8:1,ORDINAL2:27;
hence thesis by A6;
end;
A15: (for B holds (I[ B ] implies I[ ( succ B ) ]))
proof
let B;
given C,D such that
A16: B = ( ( C *^ A ) +^ D )
and
A17: D in A;

A18:now
assume (not ( succ D ) in A);
then A19: A c= ( succ D ) by ORDINAL1:16;
take C1 = ( succ C );
take D1 = ( {} );
( succ D ) c= A by A17,ORDINAL1:21;
then A20: A = ( succ D ) by A19,XBOOLE_0:def 10;
thus ( ( C1 *^ A ) +^ D1 ) = ( C1 *^ A ) by ORDINAL2:27
.= ( ( C *^ A ) +^ A ) by ORDINAL2:36
.= ( succ B ) by A16,A20,ORDINAL2:28;
thus D1 in A by A1,CKB8:1;
end;
now
assume A21: ( succ D ) in A;
take C1 = C;
take D1 = ( succ D );
thus ( ( C1 *^ A ) +^ D1 ) = ( succ B ) by A16,ORDINAL2:28;
thus D1 in A by A21;
end;
hence thesis by A18;
end;
A22: I[ ( {} ) ]
proof
take C = ( {} );
take D = ( {} );
thus ( {} ) = ( ( {} ) +^ ( {} ) ) by ORDINAL2:27
.= ( ( C *^ A ) +^ D ) by ORDINAL2:35;
thus thesis by A1,CKB8:1;
end;
(for B holds I[ B ]) from ORDINAL2:sch 1(A22,A15,A2);
hence thesis;
end;
