environ
vocabularies XBOOLE_0,PRE_TOPC,SUBSET_1,STRUCT_0,TARSKI,TOPS_1,RCOMP_1,TSEP_1,CONNSP_1,SETFAM_1,TSEP_2;
notations TARSKI,XBOOLE_0,SUBSET_1,PRE_TOPC,STRUCT_0,TOPS_1,BORSUK_1,CONNSP_1,TSEP_1,CKB2,CKB3,CKB10;
definitions BORSUK_1,TSEP_1,XBOOLE_0,SUBSET_1,STRUCT_0,CKB2;
theorems PRE_TOPC,TOPS_1,CONNSP_1,BORSUK_1,TSEP_1,TDLAT_1,TDLAT_3,SUBSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15;
registrations STRUCT_0,PRE_TOPC;
constructors TOPS_1,CONNSP_1,BORSUK_1,TSEP_1,CKB2,CKB10;
requirements BOOLE,SUBSET;
begin
reserve X for non empty TopSpace;
reserve A1 for (Subset of X);
reserve A2 for (Subset of X);
reserve B1 for (Subset of X);
reserve B2 for (Subset of X);
theorem
Th14: ((A1,A2 constitute_a_decomposition  & B1,B2 constitute_a_decomposition ) implies ( A1 /\ B1 ),( A2 \/ B2 ) constitute_a_decomposition )
proof
assume A1: A1,A2 constitute_a_decomposition ;
then A1 misses A2 by CKB2:def 1;
then A2: ( A1 /\ A2 ) = ( {} ) by XBOOLE_0:def 7;
assume A3: B1,B2 constitute_a_decomposition ;
then A4: ( B1 \/ B2 ) = ( [#] X ) by CKB2:def 1;
B1 misses B2 by A3,CKB2:def 1;
then A5: ( B1 /\ B2 ) = ( {} X ) by XBOOLE_0:def 7;
( ( A1 /\ B1 ) /\ ( A2 \/ B2 ) ) = ( ( ( B1 /\ A1 ) /\ A2 ) \/ ( ( A1 /\ B1 ) /\ B2 ) ) by XBOOLE_1:23
.= ( ( B1 /\ ( A1 /\ A2 ) ) \/ ( ( A1 /\ B1 ) /\ B2 ) ) by XBOOLE_1:16
.= ( ( B1 /\ ( A1 /\ A2 ) ) \/ ( A1 /\ ( B1 /\ B2 ) ) ) by XBOOLE_1:16
.= ( {} X ) by A5,A2;
then A6: ( A1 /\ B1 ) misses ( A2 \/ B2 ) by XBOOLE_0:def 7;
( ( A1 /\ B1 ) \/ ( A2 \/ B2 ) ) = ( ( A1 \/ ( A2 \/ B2 ) ) /\ ( B1 \/ ( A2 \/ B2 ) ) ) by XBOOLE_1:24
.= ( ( ( A1 \/ A2 ) \/ B2 ) /\ ( B1 \/ ( B2 \/ A2 ) ) ) by XBOOLE_1:4
.= ( ( ( A1 \/ A2 ) \/ B2 ) /\ ( ( B1 \/ B2 ) \/ A2 ) ) by XBOOLE_1:4
.= ( ( ( [#] X ) \/ B2 ) /\ ( ( [#] X ) \/ A2 ) ) by A1,A4,CKB2:def 1
.= ( ( ( [#] X ) \/ B2 ) /\ ( [#] X ) ) by XBOOLE_1:12
.= ( ( [#] X ) /\ ( [#] X ) ) by XBOOLE_1:12
.= ( [#] X );
hence thesis by A6,CKB2:def 1;
end;
