environ
vocabularies NET_1,XBOOLE_0,TARSKI,ZFMISC_1,RELAT_1,FF_SIEC,STRUCT_0,PETRI;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,PARTIT_2,STRUCT_0,PETRI,NET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
definitions NET_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
theorems ZFMISC_1,RELAT_1,SYSREL,TARSKI,RELSET_1,NET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13;
registrations XBOOLE_0,RELAT_1,NET_1,STRUCT_0,PARTIT_2;
constructors TARSKI,NET_1,STRUCT_0,PETRI,PARTIT_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
requirements SUBSET,BOOLE;
begin
reserve M for Pnet;
theorem
Th13: (( Flow M ) c= [: ( Elements M ),( Elements M ) :] & ( ( Flow M ) ~ ) c= [: ( Elements M ),( Elements M ) :])
proof
A1: (the carrier of M) c= ( Elements M ) by XBOOLE_1:7;
A2: (the carrier' of M) c= ( Elements M ) by XBOOLE_1:7;
then A3: [: (the carrier of M),(the carrier' of M) :] c= [: ( Elements M ),( Elements M ) :] by A1,ZFMISC_1:96;
[: (the carrier' of M),(the carrier of M) :] c= [: ( Elements M ),( Elements M ) :] by A1,A2,ZFMISC_1:96;
then A4: ( [: (the carrier of M),(the carrier' of M) :] \/ [: (the carrier' of M),(the carrier of M) :] ) c= [: ( Elements M ),( Elements M ) :] by A3,XBOOLE_1:8;
( Flow M ) c= ( [: (the carrier of M),(the carrier' of M) :] \/ [: (the carrier' of M),(the carrier of M) :] ) by NET_1:def 2;
then ( Flow M ) c= [: ( Elements M ),( Elements M ) :] by A4,XBOOLE_1:1;
hence thesis by SYSREL:4;
end;
