environ
vocabularies XBOOLE_0,STRUCT_0,ORDERS_2,SUBSET_1,XXREAL_0,RELAT_1,RELAT_2,REWRITE1,LATTICE3,ZFMISC_1,ORDERS_1,ARYTM_3,TARSKI,LATTICES,XXREAL_2,EQREL_1,FILTER_0,PBOOLE,ORDINAL2,FINSET_1,CAT_1,WELLORD1,YELLOW_0,CARD_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_2,RELSET_1,FINSET_1,TOLER_1,ORDERS_1,DOMAIN_1,CARD_1,STRUCT_0,LATTICES,ORDERS_2,LATTICE3,CKB2,CKB3,CKB4,CKB22,CKB23,CKB24,CKB30,CKB31;
definitions STRUCT_0,RELAT_2,ORDERS_2,LATTICE3,WELLORD1,CKB2,CKB3,CKB4,CKB22,CKB23,CKB24,CKB30,CKB31;
theorems TARSKI,ZFMISC_1,RELAT_2,ORDERS_2,LATTICE3,XBOOLE_0,XBOOLE_1,STRUCT_0,CKB2,CKB3,CKB4,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB22,CKB23,CKB24,CKB25,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36;
schemes FINSET_1,RELSET_1,CKB1;
registrations XBOOLE_0,RELSET_1,FINSET_1,STRUCT_0,ORDERS_2,LATTICE3,CARD_1,ORDINAL1,CKB5,CKB6,CKB7,CKB8,CKB21,CKB26,CKB27,CKB28,CKB29;
constructors TOLER_1,REALSET2,LATTICE3,CKB22,CKB23,CKB24,CKB30,CKB31;
requirements BOOLE,SUBSET,NUMERALS;
begin
theorem
Th19: (for L being  antisymmetric RelStr holds (for a,b,c being (Element of L) holds ((c = ( a "/\" b ) &  ex_inf_of { a,b },L) iff ((c <= a & c <= b) & (for d being (Element of L) holds ((d <= a & d <= b) implies c >= d))))))
proof
let L being  antisymmetric RelStr;
let a being (Element of L),b being (Element of L),c being (Element of L);
hereby
assume that
A1: c = ( a "/\" b )
and
A2:  ex_inf_of { a,b },L;
consider c1 being (Element of L) such that A3: { a,b } is_>=_than c1 and A4: (for d being (Element of L) holds ({ a,b } is_>=_than d implies c1 >= d)) by A2,CKB34:1;
A5:now
let d being (Element of L);
assume (a >= d & b >= d);
then { a,b } is_>=_than d by CKB16:1;
hence c1 >= d by A4;
end;
(a >= c1 & b >= c1) by A3,CKB16:1;
hence ((c <= a & c <= b) & (for d being (Element of L) holds ((d <= a & d <= b) implies c >= d))) by A1,A5,LATTICE3:def 14;
end;
assume that
A6: (c <= a & c <= b)
and
A7: (for d being (Element of L) holds ((d <= a & d <= b) implies c >= d));
thus c = ( a "/\" b ) by A6,A7,LATTICE3:def 14;
now
take c;
thus c is_<=_than { a,b } by A6,CKB16:1;
let d being (Element of L);
assume d is_<=_than { a,b };
then (d <= a & d <= b) by CKB16:1;
hence c >= d by A7;
end;
hence thesis by CKB34:1;
end;
