environ
vocabularies NUMBERS,SUBSET_1,FINSEQ_1,EUCLID,SPRECT_2,RELAT_1,FINSEQ_5,FINSEQ_4,XXREAL_0,PARTFUN1,CARD_1,ARYTM_3,ARYTM_1,PRE_TOPC,TOPREAL1,JORDAN3,XBOOLE_0,FUNCT_1,GROUP_2,ORDINAL4,NAT_1,RLTOPSP1,TARSKI,RCOMP_1,SPPOL_1,FINSEQ_6,JORDAN9,PSCOMP_1,GRAPH_2,TOPREAL2,RELAT_2,MCART_1,GOBOARD1,JORDAN8,TREES_1,MATRIX_1,JORDAN1E;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,NAT_D,FUNCT_1,PARTFUN1,FINSEQ_1,FINSEQ_4,FINSEQ_5,MATRIX_1,FINSEQ_6,STRUCT_0,GRAPH_2,PRE_TOPC,TOPREAL2,CONNSP_1,COMPTS_1,RLTOPSP1,EUCLID,PSCOMP_1,SPRECT_2,GOBOARD1,TOPREAL1,SPPOL_1,JORDAN3,JORDAN8,JORDAN9,CKB8,CKB10;
definitions TARSKI,TOPREAL1,SPRECT_2,XBOOLE_0,PSCOMP_1,CKB8,CKB10;
theorems JORDAN8,PSCOMP_1,JORDAN1A,NAT_1,GOBOARD5,FINSEQ_1,FINSEQ_2,SPRECT_2,FINSEQ_4,FINSEQ_5,FINSEQ_6,GOBOARD7,SPPOL_2,REVROT_1,TOPREAL1,SPRECT_3,JORDAN5B,JORDAN3,JORDAN9,GOBOARD1,TARSKI,FINSEQ_3,FUNCT_1,TOPREAL5,JORDAN10,GRAPH_2,CARD_1,CARD_2,ENUMSET1,JORDAN1B,SPRECT_5,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,EUCLID,ORDINAL1,PARTFUN1,MATRIX_1,XREAL_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11;
registrations XBOOLE_0,RELSET_1,XXREAL_0,XREAL_0,MEMBERED,FINSEQ_1,FINSEQ_6,STRUCT_0,TOPREAL2,SPPOL_2,SPRECT_2,REVROT_1,TOPREAL6,JORDAN8,JORDAN1A,CARD_1,FUNCT_1,EUCLID,CKB12,CKB13,CKB14;
constructors PARTFUN1,XXREAL_0,NAT_1,FINSEQ_4,NEWTON,BINARITH,FINSEQ_5,CONNSP_1,REALSET2,TOPREAL2,PSCOMP_1,GRAPH_2,JORDAN3,JORDAN8,GOBRD13,JORDAN9,NAT_D,RELSET_1,REAL_1,CKB8,CKB10;
requirements NUMERALS,BOOLE,SUBSET,REAL,ARITHM;
begin
reserve n for (Element of ( NAT ));
registration
let C being  compact non  vertical non  horizontal (Subset of ( TOP-REAL 2 ));
let n being (Element of ( NAT ));
cluster ( Lower_Seq (C,n) ) ->  one-to-one  special  unfolded  s.n.c.;
coherence
proof
set f = ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) );
A26: ( L~ ( Cage (C,n) ) ) = ( L~ f ) by REVROT_1:33;
( W-min ( L~ ( Cage (C,n) ) ) ) in ( rng ( Cage (C,n) ) ) by SPRECT_2:43;
then A27: ( f /. 1 ) = ( W-min ( L~ f ) ) by A26,FINSEQ_6:92;
then ( ( W-max ( L~ ( Cage (C,n) ) ) ) .. f ) <= ( ( N-min ( L~ ( Cage (C,n) ) ) ) .. f ) by A26,SPRECT_5:23;
then ( ( N-min ( L~ ( Cage (C,n) ) ) ) .. f ) > 1 by A26,A27,SPRECT_5:22,XXREAL_0:2;
then ( ( N-max ( L~ ( Cage (C,n) ) ) ) .. f ) > 1 by A26,A27,SPRECT_5:24,XXREAL_0:2;
then A28: ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) > 1 by A26,A27,SPRECT_5:25,XXREAL_0:2;
( E-max ( L~ ( Cage (C,n) ) ) ) in ( rng ( Cage (C,n) ) ) by SPRECT_2:46;
then A29: ( E-max ( L~ ( Cage (C,n) ) ) ) in ( rng f ) by FINSEQ_6:90,SPRECT_2:43;
A30: ( len ( Lower_Seq (C,n) ) ) = ( ( ( len f ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) + 1 ) by CKB11:1;
now
let i1 being set;
let j1 being set;
assume that
A31: i1 in ( dom ( Lower_Seq (C,n) ) )
and
A32: j1 in ( dom ( Lower_Seq (C,n) ) )
and
A33: ( ( Lower_Seq (C,n) ) . i1 ) = ( ( Lower_Seq (C,n) ) . j1 )
and
A34: i1 <> j1;
reconsider i2 = i1,j2 = j1 as (Element of ( NAT )) by A31,A32;
A35: i2 in ( Seg ( len ( Lower_Seq (C,n) ) ) ) by A31,FINSEQ_1:def 3;
then i2 >= 1 by FINSEQ_1:1;
then A36: i2 = ( ( i2 -' 1 ) + 1 ) by XREAL_1:235;
A37: ( ( Lower_Seq (C,n) ) . i1 ) = ( ( Lower_Seq (C,n) ) /. i2 ) by A31,PARTFUN1:def 6
.= ( f /. ( ( i2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) ) by A29,A31,A36,FINSEQ_5:52;
A38: j2 in ( Seg ( len ( Lower_Seq (C,n) ) ) ) by A32,FINSEQ_1:def 3;
then j2 >= 1 by FINSEQ_1:1;
then A39: j2 = ( ( j2 -' 1 ) + 1 ) by XREAL_1:235;
A40: ( ( Lower_Seq (C,n) ) . j1 ) = ( ( Lower_Seq (C,n) ) /. j2 ) by A32,PARTFUN1:def 6
.= ( f /. ( ( j2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) ) by A29,A32,A39,FINSEQ_5:52;
( ( 0 ) + 1 ) <= i2 by A35,FINSEQ_1:1;
then A41: ( i2 - 1 ) >= ( 0 ) by XREAL_1:19;
i2 <= ( ( ( len f ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) + 1 ) by A30,A35,FINSEQ_1:1;
then ( i2 - 1 ) <= ( ( len f ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by XREAL_1:20;
then ( ( i2 - 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) <= ( len f ) by XREAL_1:19;
then A42: ( ( i2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) <= ( len f ) by A41,XREAL_0:def 2;
( ( 0 ) + 1 ) <= j2 by A38,FINSEQ_1:1;
then A43: ( j2 - 1 ) >= ( 0 ) by XREAL_1:19;
j2 <= ( ( ( len f ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) + 1 ) by A30,A38,FINSEQ_1:1;
then ( j2 - 1 ) <= ( ( len f ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by XREAL_1:20;
then ( ( j2 - 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) <= ( len f ) by XREAL_1:19;
then A44: ( ( j2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) <= ( len f ) by A43,XREAL_0:def 2;
( ( j2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) >= ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) by NAT_1:11;
then A45: 1 < ( ( j2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by A28,XXREAL_0:2;
( ( i2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) >= ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) by NAT_1:11;
then A46: 1 < ( ( i2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by A28,XXREAL_0:2;
per cases  by A34,XXREAL_0:1;
suppose i2 < j2;

then ( i2 - 1 ) < ( j2 - 1 ) by XREAL_1:9;
then ( i2 - 1 ) < ( j2 -' 1 ) by XREAL_0:def 2;
then ( i2 -' 1 ) < ( j2 -' 1 ) by A41,XREAL_0:def 2;
then ( ( i2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) < ( ( j2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by XREAL_1:6;
hence contradiction by A33,A37,A40,A44,A46,GOBOARD7:37;
end;
suppose j2 < i2;

then ( j2 - 1 ) < ( i2 - 1 ) by XREAL_1:9;
then ( j2 - 1 ) < ( i2 -' 1 ) by XREAL_0:def 2;
then ( j2 -' 1 ) < ( i2 -' 1 ) by A43,XREAL_0:def 2;
then ( ( j2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) < ( ( i2 -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by XREAL_1:6;
hence contradiction by A33,A37,A40,A42,A45,GOBOARD7:37;
end;
end;
hence ( Lower_Seq (C,n) ) is  one-to-one by FUNCT_1:def 4;
( E-max ( L~ ( Cage (C,n) ) ) ) in ( rng ( Cage (C,n) ) ) by SPRECT_2:46;
then A47: ( E-max ( L~ ( Cage (C,n) ) ) ) in ( rng ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) by FINSEQ_6:90,SPRECT_2:43;
hence ( Lower_Seq (C,n) ) is  special by SPPOL_2:39;
thus ( Lower_Seq (C,n) ) is  unfolded by A47,SPPOL_2:27;
let i being Nat;
let j being Nat;
assume A48: ( i + 1 ) < j;
( i + 1 ) >= 1 by NAT_1:11;
then j = ( ( j -' 1 ) + 1 ) by A48,XREAL_1:235,XXREAL_0:2;
then A49: ( LSeg (( Lower_Seq (C,n) ),j) ) = ( LSeg (f,( ( j -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) )) ) by A47,SPPOL_2:10;
now
per cases  by NAT_1:2;
suppose i > ( 0 );

then A50: i >= ( ( 0 ) + 1 ) by NAT_1:13;
then i = ( ( i -' 1 ) + 1 ) by XREAL_1:235;
then A51: ( LSeg (( Lower_Seq (C,n) ),i) ) = ( LSeg (f,( ( i -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) )) ) by A29,SPPOL_2:10;
( ( i + 1 ) - 1 ) < ( j - 1 ) by A48,XREAL_1:9;
then A52: ( ( i - 1 ) + 1 ) < ( j -' 1 ) by XREAL_0:def 2;
( i - 1 ) >= ( 0 ) by A50,XREAL_1:19;
then ( ( i -' 1 ) + 1 ) < ( j -' 1 ) by A52,XREAL_0:def 2;
then ( ( ( i -' 1 ) + 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) < ( ( j -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) by XREAL_1:6;
then A53: ( ( ( i -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) + 1 ) < ( ( j -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) );
A54: ( ( i -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) > ( ( 0 ) + 1 ) by A28,XREAL_1:8;
now
per cases ;
suppose ( ( ( j -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) + 1 ) <= ( len f );

then ( ( j -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) < ( len f ) by NAT_1:13;
then ( LSeg (( Lower_Seq (C,n) ),i) ) misses ( LSeg (( Lower_Seq (C,n) ),j) ) by A49,A51,A53,A54,GOBOARD5:def 4;
hence ( ( LSeg (( Lower_Seq (C,n) ),i) ) /\ ( LSeg (( Lower_Seq (C,n) ),j) ) ) = ( {} ) by XBOOLE_0:def 7;
end;
suppose ( ( ( j -' 1 ) + ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. f ) ) + 1 ) > ( len f );

then ( LSeg (( Lower_Seq (C,n) ),j) ) = ( {} ) by A49,TOPREAL1:def 3;
hence ( ( LSeg (( Lower_Seq (C,n) ),i) ) /\ ( LSeg (( Lower_Seq (C,n) ),j) ) ) = ( {} );
end;
end;
hence ( ( LSeg (( Lower_Seq (C,n) ),i) ) /\ ( LSeg (( Lower_Seq (C,n) ),j) ) ) = ( {} );
end;
suppose i = ( 0 );

then ( LSeg (( Lower_Seq (C,n) ),i) ) = ( {} ) by TOPREAL1:def 3;
hence ( ( LSeg (( Lower_Seq (C,n) ),i) ) /\ ( LSeg (( Lower_Seq (C,n) ),j) ) ) = ( {} );
end;
end;
hence thesis by XBOOLE_0:def 7;
end;
end;
