environ
vocabularies NUMBERS,SUBSET_1,FINSEQ_1,EUCLID,SPRECT_2,RELAT_1,FINSEQ_5,FINSEQ_4,XXREAL_0,PARTFUN1,CARD_1,ARYTM_3,ARYTM_1,PRE_TOPC,TOPREAL1,JORDAN3,XBOOLE_0,FUNCT_1,GROUP_2,ORDINAL4,NAT_1,RLTOPSP1,TARSKI,RCOMP_1,SPPOL_1,FINSEQ_6,JORDAN9,PSCOMP_1,GRAPH_2,TOPREAL2,RELAT_2,MCART_1,GOBOARD1,JORDAN8,TREES_1,MATRIX_1,JORDAN1E;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,NAT_D,FUNCT_1,PARTFUN1,FINSEQ_1,FINSEQ_4,FINSEQ_5,MATRIX_1,FINSEQ_6,STRUCT_0,GRAPH_2,PRE_TOPC,TOPREAL2,CONNSP_1,COMPTS_1,RLTOPSP1,EUCLID,PSCOMP_1,SPRECT_2,GOBOARD1,TOPREAL1,SPPOL_1,JORDAN3,JORDAN8,JORDAN9,CKB8,CKB10;
definitions TARSKI,TOPREAL1,SPRECT_2,XBOOLE_0,PSCOMP_1,CKB8,CKB10;
theorems JORDAN8,PSCOMP_1,JORDAN1A,NAT_1,GOBOARD5,FINSEQ_1,FINSEQ_2,SPRECT_2,FINSEQ_4,FINSEQ_5,FINSEQ_6,GOBOARD7,SPPOL_2,REVROT_1,TOPREAL1,SPRECT_3,JORDAN5B,JORDAN3,JORDAN9,GOBOARD1,TARSKI,FINSEQ_3,FUNCT_1,TOPREAL5,JORDAN10,GRAPH_2,CARD_1,CARD_2,ENUMSET1,JORDAN1B,SPRECT_5,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,EUCLID,ORDINAL1,PARTFUN1,MATRIX_1,XREAL_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11;
registrations XBOOLE_0,RELSET_1,XXREAL_0,XREAL_0,MEMBERED,FINSEQ_1,FINSEQ_6,STRUCT_0,TOPREAL2,SPPOL_2,SPRECT_2,REVROT_1,TOPREAL6,JORDAN8,JORDAN1A,CARD_1,FUNCT_1,EUCLID,CKB12,CKB13,CKB14,CKB15;
constructors PARTFUN1,XXREAL_0,NAT_1,FINSEQ_4,NEWTON,BINARITH,FINSEQ_5,CONNSP_1,REALSET2,TOPREAL2,PSCOMP_1,GRAPH_2,JORDAN3,JORDAN8,GOBRD13,JORDAN9,NAT_D,RELSET_1,REAL_1,CKB8,CKB10;
requirements NUMERALS,BOOLE,SUBSET,REAL,ARITHM;
begin
reserve n for (Element of ( NAT ));
theorem
Th14: (for C being  compact non  vertical non  horizontal (Subset of ( TOP-REAL 2 )) holds (for n being (Element of ( NAT )) holds ( ( len ( Upper_Seq (C,n) ) ) + ( len ( Lower_Seq (C,n) ) ) ) = ( ( len ( Cage (C,n) ) ) + 1 )))
proof
let C being  compact non  vertical non  horizontal (Subset of ( TOP-REAL 2 ));
let n being (Element of ( NAT ));
thus ( ( len ( Upper_Seq (C,n) ) ) + ( len ( Lower_Seq (C,n) ) ) ) = ( ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) + ( len ( Lower_Seq (C,n) ) ) ) by CKB9:1
.= ( ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) + ( ( ( len ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) ) + 1 ) ) by CKB11:1
.= ( ( ( ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) + ( len ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) ) - ( ( E-max ( L~ ( Cage (C,n) ) ) ) .. ( Rotate (( Cage (C,n) ),( W-min ( L~ ( Cage (C,n) ) ) )) ) ) ) + 1 )
.= ( ( len ( Cage (C,n) ) ) + 1 ) by REVROT_1:14;
end;
