environ
vocabularies NUMBERS,SUBSET_1,REAL_1,XREAL_0,ORDINAL1,XBOOLE_0,PRE_TOPC,ZFMISC_1,STRUCT_0,FUNCT_1,PSCOMP_1,SEQFUNC,SEQ_1,XXREAL_0,CARD_1,NEWTON,RELAT_1,ARYTM_3,INT_1,NAT_1,ARYTM_1,FUNCT_7,FUNCT_2,TARSKI,METRIC_1,RCOMP_1,MCART_1,SETFAM_1,ORDINAL2,TOPMETR,TMAP_1,SEQ_4,NAGATA_1,XXREAL_2,COMPLEX1,RELAT_2,VALUED_0,PCOMPS_1,PBOOLE,SERIES_1,CARD_3,VALUED_1,SEQ_2,FINSEQ_1,PREPOWER,BINOP_1,SETWISEO,FINSOP_1,ORDINAL4,CARD_5,RLVECT_3,FINSET_1,COH_SP,PARTFUN1,WELLORD1,PCOMPS_2,NATTRA_1,NAGATA_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,SETWISEO,BORSUK_1,RELAT_1,RELAT_2,ORDINAL1,XCMPLX_0,XXREAL_0,XXREAL_2,XREAL_0,FUNCT_1,COMPLEX1,REAL_1,RELSET_1,PARTFUN1,VALUED_0,VALUED_1,SEQ_1,FUNCT_2,FUNCT_3,DOMAIN_1,BINOP_1,PRE_TOPC,NAT_1,NAT_D,CARD_1,NUMBERS,FINSET_1,STRUCT_0,FINSEQ_1,PCOMPS_1,PCOMPS_2,NEWTON,TOPS_2,METRIC_1,PROB_1,SEQFUNC,PREPOWER,TOPMETR,PSCOMP_1,MEASURE6,TMAP_1,NAGATA_1,SEQ_2,SEQ_4,SERIES_1,FINSOP_1,CANTOR_1,WELLORD1,FUNCT_7,CKB2,CKB4,CKB7;
definitions FUNCT_2,TARSKI,TOPS_2,XBOOLE_0,BINOP_1,SUBSET_1,STRUCT_0,PRE_TOPC,XXREAL_2,CKB2,CKB4,CKB7;
theorems NAT_1,NEWTON,FUNCT_2,PCOMPS_1,PCOMPS_2,NAGATA_1,SUBSET_1,METRIC_6,FUNCT_3,FUNCT_1,METRIC_1,XCMPLX_1,ABSVALUE,TOPMETR,TMAP_1,BORSUK_1,XBOOLE_1,TARSKI,SETFAM_1,XBOOLE_0,TOPS_1,TOPS_2,PRE_TOPC,FINSEQ_1,CARD_4,TOPREAL6,ZFMISC_1,BINOP_1,SEQ_2,SEQ_4,SEQ_1,SERIES_1,PREPOWER,SEQFUNC,PARTFUN1,JGRAPH_2,URYSOHN1,FINSEQ_3,FINSEQ_4,FINSOP_1,SETWISEO,PROB_1,URYSOHN3,WELLORD1,WELLORD2,TBSP_1,RELAT_1,RELAT_2,YELLOW_9,FUNCT_7,RSSPACE2,RSSPACE,BHSP_5,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,NAT_D,VALUED_1,XXREAL_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10;
schemes FUNCT_2,NAT_1,SEQFUNC,FRAENKEL,BINOP_1,PCOMPS_2;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,FINSEQ_1,STRUCT_0,TOPS_1,METRIC_1,BORSUK_1,TOPMETR,MEASURE6,TOPREAL6,VALUED_0,VALUED_1,FUNCT_2,BORSUK_4,BORSUK_6,CARD_1,PRE_TOPC,FUNCT_1,PSCOMP_1;
constructors SETFAM_1,WELLORD1,FUNCT_3,SETWISEO,REAL_1,SQUARE_1,NAT_1,NAT_D,SEQM_3,PROB_1,FINSOP_1,NEWTON,PREPOWER,SERIES_1,FUNCT_7,TOPS_2,COMPTS_1,TMAP_1,CANTOR_1,PCOMPS_2,MEASURE6,URYSOHN3,NAGATA_1,SEQ_1,BORSUK_4,XXREAL_2,SEQFUNC,SEQ_4,BINOP_2,SEQ_2,RVSUM_1,PSCOMP_1,PCOMPS_1,CKB2,CKB4,CKB7;
requirements BOOLE,SUBSET,NUMERALS,REAL,ARITHM;
begin
reserve rn for  real number;
reserve z for set;
reserve T for non empty TopSpace;
reserve pmet for (Function of [: (the carrier of T),(the carrier of T) :],( REAL ));
theorem
Th7: (for pmet holds (pmet is_a_pseudometric_of (the carrier of T) implies (for x,y being (Point of T) holds (for A being non empty (Subset of T) holds ( abs ( ( ( lower_bound (pmet,A) ) . x ) - ( ( lower_bound (pmet,A) ) . y ) ) ) <= ( pmet . (x,y) )))))
proof
let pmet;
assume that
A1: pmet is_a_pseudometric_of (the carrier of T);
A2: pmet is  symmetric by A1,NAGATA_1:def 10;
let x being (Point of T),y being (Point of T);
let A being non empty (Subset of T);
A3: (for x1,y1 being (Point of T) holds ( ( ( lower_bound (pmet,A) ) . y1 ) - ( ( lower_bound (pmet,A) ) . x1 ) ) >= ( - ( pmet . (x1,y1) ) ))
proof
let x1 being (Point of T),y1 being (Point of T);
A4: ( ( dist (pmet,x1) ) .: A ) is non empty  bounded_below by A1,CKB8:1;
A5: (for rn holds (rn in ( ( dist (pmet,y1) ) .: A ) implies rn >= ( ( lower_bound ( ( dist (pmet,x1) ) .: A ) ) - ( pmet . (x1,y1) ) )))
proof
let rn;
assume rn in ( ( dist (pmet,y1) ) .: A );
then consider z such that A6: z in ( dom ( dist (pmet,y1) ) ) and A7: z in A and A8: ( ( dist (pmet,y1) ) . z ) = rn by FUNCT_1:def 6;
reconsider z as (Point of T) by A6;
A9: ( ( dist (pmet,x1) ) . z ) = ( pmet . (x1,z) ) by CKB4:def 1;
pmet is  triangle by A1,NAGATA_1:def 10;
then A10: ( ( pmet . (x1,y1) ) + ( pmet . (y1,z) ) ) >= ( pmet . (x1,z) ) by METRIC_1:def 5;
( dom ( dist (pmet,x1) ) ) = (the carrier of T) by FUNCT_2:def 1;
then ( ( dist (pmet,x1) ) . z ) in ( ( dist (pmet,x1) ) .: A ) by A7,FUNCT_1:def 6;
then ( pmet . (x1,z) ) >= ( lower_bound ( ( dist (pmet,x1) ) .: A ) ) by A4,A9,SEQ_4:def 2;
then ( ( pmet . (x1,y1) ) + ( pmet . (y1,z) ) ) >= ( ( lower_bound ( ( dist (pmet,x1) ) .: A ) ) + ( 0 ) ) by A10,XXREAL_0:2;
then ( ( pmet . (y1,z) ) - ( 0 ) ) >= ( ( lower_bound ( ( dist (pmet,x1) ) .: A ) ) - ( pmet . (x1,y1) ) ) by XREAL_1:21;
hence thesis by A8,CKB4:def 1;
end;
( ( dist (pmet,y1) ) .: A ) is non empty  bounded_below by A1,CKB8:1;
then ( ( lower_bound ( ( dist (pmet,y1) ) .: A ) ) - ( 0 ) ) >= ( ( lower_bound ( ( dist (pmet,x1) ) .: A ) ) - ( pmet . (x1,y1) ) ) by A5,SEQ_4:43;
then A11: ( ( lower_bound ( ( dist (pmet,y1) ) .: A ) ) - ( lower_bound ( ( dist (pmet,x1) ) .: A ) ) ) >= ( ( 0 ) - ( pmet . (x1,y1) ) ) by XREAL_1:17;
( lower_bound ( ( dist (pmet,y1) ) .: A ) ) = ( ( lower_bound (pmet,A) ) . y1 ) by CKB7:def 1;
hence thesis by A11,CKB7:def 1;
end;
then ( ( ( lower_bound (pmet,A) ) . y ) - ( ( lower_bound (pmet,A) ) . x ) ) >= ( - ( pmet . (x,y) ) );
then ( - ( ( ( lower_bound (pmet,A) ) . x ) - ( ( lower_bound (pmet,A) ) . y ) ) ) >= ( - ( pmet . (x,y) ) );
then A12: ( ( ( lower_bound (pmet,A) ) . x ) - ( ( lower_bound (pmet,A) ) . y ) ) <= ( pmet . (x,y) ) by XREAL_1:24;
( ( ( lower_bound (pmet,A) ) . x ) - ( ( lower_bound (pmet,A) ) . y ) ) >= ( - ( pmet . (y,x) ) ) by A3;
then ( ( ( lower_bound (pmet,A) ) . x ) - ( ( lower_bound (pmet,A) ) . y ) ) >= ( - ( pmet . (x,y) ) ) by A2,METRIC_1:def 4;
hence thesis by A12,ABSVALUE:5;
end;
