environ
vocabularies NUMBERS,REAL_1,XREAL_0,ORDINAL1,INT_1,SUBSET_1,RCOMP_1,PARTFUN1,XXREAL_1,ARYTM_1,SIN_COS,ARYTM_3,TARSKI,RELAT_1,XBOOLE_0,CARD_1,FUNCT_1,FDIFF_1,SQUARE_1,ORDINAL2,XXREAL_0,VALUED_0,VALUED_1,TAYLOR_1,PREPOWER,ORDINAL4,LIMFUNC1,SIN_COS9;
notations TARSKI,SUBSET_1,ORDINAL1,XXREAL_0,XCMPLX_0,FUNCT_1,RELSET_1,PARTFUN1,RCOMP_1,SIN_COS,RFUNCT_1,SQUARE_1,VALUED_1,NUMBERS,REAL_1,SEQ_1,FDIFF_1,XREAL_0,INT_1,SIN_COS4,PARTFUN2,FCONT_1,XBOOLE_0,TAYLOR_1,PREPOWER,LIMFUNC1,RFUNCT_2,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22;
definitions TARSKI,XCMPLX_0,LIMFUNC1,SIN_COS,VALUED_1,SQUARE_1,CKB17,CKB18,CKB19,CKB20;
theorems FDIFF_2,XCMPLX_1,FDIFF_1,RELAT_1,SIN_COS,COMPTRIG,RFUNCT_2,FCONT_1,SIN_COS4,FUNCT_1,RCOMP_1,XBOOLE_0,SQUARE_1,FCONT_3,XREAL_1,TARSKI,XBOOLE_1,FDIFF_7,ROLLE,RFUNCT_1,FCONT_2,TAYLOR_1,PREPOWER,VALUED_1,FDIFF_4,FDIFF_5,XXREAL_1,XXREAL_0,XXREAL_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB17,CKB18,CKB19,CKB20,CKB23,CKB24,CKB25,CKB26,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101,CKB102,CKB103,CKB104,CKB105,CKB106,CKB107,CKB108,CKB109,CKB110,CKB111,CKB112,CKB113,CKB114,CKB115,CKB116,CKB117,CKB118,CKB119,CKB120,CKB121,CKB122,CKB123,CKB124,CKB125,CKB126,CKB127,CKB128,CKB129;
registrations XCMPLX_0,XXREAL_0,XREAL_0,MEMBERED,RCOMP_1,RELSET_1,SIN_COS,FUNCT_1,SIN_COS6,RFUNCT_2,NUMBERS,INT_1,VALUED_0,XXREAL_2,CKB15,CKB16,CKB27,CKB28,CKB51,CKB52;
constructors REAL_1,SQUARE_1,RCOMP_1,RFUNCT_1,FDIFF_1,RFUNCT_2,FCONT_1,SIN_COS,PARTFUN2,SIN_COS4,TAYLOR_1,PREPOWER,LIMFUNC1,VALUED_1,SEQ_1,XXREAL_2,PARTFUN1,SIN_COS6,RELSET_1,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22;
requirements SUBSET,BOOLE,NUMERALS,ARITHM,REAL;
begin
reserve x for Real;
reserve y for set;
reserve Z for  open (Subset of ( REAL ));
reserve f1 for (PartFunc of ( REAL ),( REAL ));
reserve f2 for (PartFunc of ( REAL ),( REAL ));
theorem
Th102: (((Z c= ( dom ( ( 1 / 2 ) (#) ( ( ln ) * ( f1 + f2 ) ) ) ) & f2 = ( #Z 2 )) & (for x holds (x in Z implies ( f1 . x ) = 1))) implies (( ( 1 / 2 ) (#) ( ( ln ) * ( f1 + f2 ) ) ) is_differentiable_on Z & (for x holds (x in Z implies ( ( ( ( 1 / 2 ) (#) ( ( ln ) * ( f1 + f2 ) ) ) `| Z ) . x ) = ( x / ( 1 + ( x ^2 ) ) )))))
proof
assume that
A1: Z c= ( dom ( ( 1 / 2 ) (#) ( ( ln ) * ( f1 + f2 ) ) ) )
and
A2: f2 = ( #Z 2 )
and
A3: (for x holds (x in Z implies ( f1 . x ) = 1));
A4: Z c= ( dom ( ( ln ) * ( f1 + f2 ) ) ) by A1,VALUED_1:def 5;
then (for y holds (y in Z implies y in ( dom ( f1 + f2 ) ))) by FUNCT_1:11;
then A5: Z c= ( dom ( f1 + f2 ) ) by TARSKI:def 3;
then A6: ( f1 + f2 ) is_differentiable_on Z by A2,A3,CKB129:1;
(for x holds (x in Z implies ( ( ln ) * ( f1 + f2 ) ) is_differentiable_in x))
proof
let x;
assume A7: x in Z;
then ( ( f1 + f2 ) . x ) = ( ( f1 . x ) + ( f2 . x ) ) by A5,VALUED_1:def 1
.= ( 1 + ( f2 . x ) ) by A3,A7
.= ( 1 + ( x #Z ( 1 + 1 ) ) ) by A2,TAYLOR_1:def 1
.= ( 1 + ( ( x #Z 1 ) * ( x #Z 1 ) ) ) by TAYLOR_1:1
.= ( 1 + ( x * ( x #Z 1 ) ) ) by PREPOWER:35
.= ( 1 + ( x * x ) ) by PREPOWER:35;
then A8: ( ( f1 + f2 ) . x ) > ( 0 ) by XREAL_1:34,XREAL_1:63;
( f1 + f2 ) is_differentiable_in x by A6,A7,FDIFF_1:9;
hence thesis by A8,TAYLOR_1:20;
end;
then A9: ( ( ln ) * ( f1 + f2 ) ) is_differentiable_on Z by A4,FDIFF_1:9;
(for x holds (x in Z implies ( ( ( ( 1 / 2 ) (#) ( ( ln ) * ( f1 + f2 ) ) ) `| Z ) . x ) = ( x / ( 1 + ( x ^2 ) ) )))
proof
let x;
assume A10: x in Z;
then A11: ( f1 + f2 ) is_differentiable_in x by A6,FDIFF_1:9;
A12: ( ( f1 + f2 ) . x ) = ( ( f1 . x ) + ( f2 . x ) ) by A5,A10,VALUED_1:def 1
.= ( 1 + ( f2 . x ) ) by A3,A10
.= ( 1 + ( x #Z ( 1 + 1 ) ) ) by A2,TAYLOR_1:def 1
.= ( 1 + ( ( x #Z 1 ) * ( x #Z 1 ) ) ) by TAYLOR_1:1
.= ( 1 + ( x * ( x #Z 1 ) ) ) by PREPOWER:35
.= ( 1 + ( x * x ) ) by PREPOWER:35;
then ( ( f1 + f2 ) . x ) > ( 0 ) by XREAL_1:34,XREAL_1:63;
then ( diff (( ( ln ) * ( f1 + f2 ) ),x) ) = ( ( diff (( f1 + f2 ),x) ) / ( ( f1 + f2 ) . x ) ) by A11,TAYLOR_1:20
.= ( ( ( ( f1 + f2 ) `| Z ) . x ) / ( ( f1 + f2 ) . x ) ) by A6,A10,FDIFF_1:def 7
.= ( ( 2 * x ) / ( 1 + ( x ^2 ) ) ) by A2,A3,A5,A10,A12,CKB129:1;
hence ( ( ( ( 1 / 2 ) (#) ( ( ln ) * ( f1 + f2 ) ) ) `| Z ) . x ) = ( ( 1 / 2 ) * ( ( 2 * x ) / ( 1 + ( x ^2 ) ) ) ) by A1,A9,A10,FDIFF_1:20
.= ( x / ( 1 + ( x ^2 ) ) );
end;
hence thesis by A1,A9,FDIFF_1:20;
end;
