environ
vocabularies NUMBERS,SUBSET_1,STRUCT_0,FUNCT_1,GLIB_000,XBOOLE_0,FUNCT_5,RELAT_1,PARTFUN1,RELAT_2,FINSET_1,TREES_2,FINSEQ_1,XXREAL_0,ARYTM_3,TARSKI,CARD_1,FUNCT_2,ZFMISC_1,MCART_1,GRAPH_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,FUNCT_5,FINSEQ_1,FINSET_1,PARTFUN1,CARD_1,NUMBERS,NAT_1,MCART_1,XXREAL_0,STRUCT_0,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB23,CKB24,CKB27,CKB28,CKB29,CKB30;
definitions FUNCT_1,TARSKI,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB24,CKB27,CKB30;
theorems FUNCT_2,FUNCT_1,PARTFUN1,FINSEQ_1,NAT_1,ZFMISC_1,MCART_1,TARSKI,RELAT_1,FINSEQ_3,RELSET_1,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,CARD_1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB22,CKB24,CKB27,CKB30;
schemes FUNCT_2,TARSKI,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FINSET_1,XREAL_0,FINSEQ_1,ORDINAL1,STRUCT_0,CARD_1,FUNCT_2,RELSET_1,CKB1,CKB4,CKB15,CKB16,CKB17,CKB18,CKB25,CKB26;
constructors PARTFUN1,FUNCT_2,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,STRUCT_0,FUNCT_5,RELSET_1,CKB1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB23,CKB24,CKB27,CKB30;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve G for Graph;
registration
let G being Graph;
cluster  empty ->  cyclic for (Path of G);
coherence
proof
let p being (Path of G);
assume A1: p is  empty;
set x = the (Vertex of G);
A2: x in (the carrier of G);
take <* x *>;
thus ( len <* x *> ) = ( ( len p ) + 1 ) by A1,CARD_1:27,FINSEQ_1:39;
thus (for n holds ((1 <= n & n <= ( len <* x *> )) implies ( <* x *> . n ) in (the carrier of G)))
proof
let n;
assume that
A3: 1 <= n
and
A4: n <= ( len <* x *> );
n <= 1 by A4,FINSEQ_1:39;
then n = 1 by A3,XXREAL_0:1;
hence thesis by A2,FINSEQ_1:40;
end;

thus (for n holds ((1 <= n & n <= ( len p )) implies (ex x9,y9 being (Vertex of G) st ((x9 = ( <* x *> . n ) & y9 = ( <* x *> . ( n + 1 ) )) & ( p . n ) joins x9,y9)))) by A1,CARD_1:27,XXREAL_0:2;
thus thesis by FINSEQ_1:39;
end;
end;
