environ
vocabularies NUMBERS,SUBSET_1,REAL_1,XXREAL_0,CARD_1,COMPLEX1,ARYTM_1,ARYTM_3,FINSEQ_1,RELAT_1,FUNCT_1,ORDINAL2,PRE_TOPC,EUCLID,RVSUM_1,SQUARE_1,XBOOLE_0,RELAT_2,TARSKI,STRUCT_0,NAT_1,XXREAL_2,CONNSP_1,METRIC_1,CONVEX1,CONNSP_3,ZFMISC_1,SETFAM_1,RLTOPSP1,FINSEQ_2,CARD_3,SUPINF_2,BORSUK_1,XXREAL_1,BORSUK_2,GRAPH_1,TOPMETR,TREAL_1,VALUED_1,FUNCT_4,RCOMP_1,TOPREAL1,TOPS_2,PCOMPS_1,WEIERSTR,SEQ_4,XREAL_0,ORDINAL1,PARTFUN1,FUNCOP_1,BINOP_2,ORDINAL4,JORDAN3,TBSP_1,CONNSP_2,RUSUB_4,SPPOL_1,GOBOARD2,SPRECT_1,TREES_1,PSCOMP_1,GOBOARD1,MCART_1,MATRIX_1,GOBOARD9,GOBOARD5,TOPS_1,JORDAN1,SPRECT_2,JORDAN2C;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,RELAT_1,FUNCT_1,RVSUM_1,RELSET_1,PARTFUN1,FUNCT_2,ORDINAL1,CARD_1,NUMBERS,XREAL_0,XXREAL_2,COMPLEX1,SEQ_1,SEQM_3,PRE_TOPC,TOPS_1,TOPS_2,COMPTS_1,METRIC_1,BINOP_2,PCOMPS_1,CONNSP_1,CONNSP_2,TBSP_1,CONNSP_3,TOPMETR,RCOMP_1,FINSEQ_1,FINSEQ_2,DOMAIN_1,STRUCT_0,SQUARE_1,BORSUK_2,XXREAL_0,SEQ_4,FINSEQ_6,JORDAN3,BINARITH,FUNCOP_1,FUNCT_3,TREAL_1,FUNCT_4,RLVECT_1,RLTOPSP1,EUCLID,SPPOL_1,PSCOMP_1,SPRECT_1,SPRECT_2,TOPREAL1,MATRIX_1,GOBOARD1,GOBOARD2,GOBOARD5,GOBOARD9,JORDAN2B,REAL_1,NAT_1,NAT_D,WEIERSTR,CKB12,CKB14,CKB17,CKB21,CKB22,CKB37,CKB38,CKB39;
definitions TARSKI,XBOOLE_0,TOPS_2,TBSP_1,JORDAN1,EUCLID,BINOP_1,SQUARE_1,SUBSET_1,PSCOMP_1,FINSEQ_2,CONNSP_3,RVSUM_1,STRUCT_0,VALUED_1,ALGSTR_0,RLTOPSP1,XXREAL_2,CKB12,CKB14,CKB17,CKB21,CKB22,CKB37,CKB39;
theorems PRE_TOPC,CONNSP_1,EUCLID,TBSP_1,TOPREAL3,NAT_1,JGRAPH_1,JORDAN1,TOPS_2,FUNCT_2,BORSUK_1,TOPMETR,TOPREAL1,FINSEQ_2,FINSEQOP,ABSVALUE,RVSUM_1,SQUARE_1,BORSUK_2,TOPREAL5,WEIERSTR,SPPOL_1,TARSKI,SEQ_4,FUNCT_1,METRIC_1,SUBSET_1,FUNCOP_1,ZFMISC_1,FINSEQ_1,FINSEQ_4,RELAT_1,FUNCT_3,RCOMP_1,FUNCT_4,HEINE,TREAL_1,CONNSP_3,JORDAN6,COMPTS_1,TSEP_1,CONNSP_2,TOPS_1,JORDAN5D,JORDAN2B,GOBOARD1,GOBOARD2,GOBOARD5,GOBOARD6,UNIFORM1,FINSEQ_6,MATRIX_1,GOBOARD9,GOBRD12,SPRECT_1,CARD_1,CARD_2,ENUMSET1,SPRECT_2,SPRECT_3,SEQ_2,RELSET_1,XBOOLE_0,XBOOLE_1,XREAL_0,TOPRNS_1,XCMPLX_0,XCMPLX_1,BINOP_2,COMPLEX1,XREAL_1,XXREAL_0,FINSOP_1,XXREAL_1,SEQM_3,NAT_D,VALUED_1,RLTOPSP1,RLVECT_1,XXREAL_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47;
schemes NAT_1,CLASSES1;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,RELSET_1,FUNCT_2,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,FINSEQ_1,REALSET1,STRUCT_0,PRE_TOPC,TOPS_1,METRIC_1,BORSUK_1,TBSP_1,EUCLID,TOPMETR,TOPREAL1,GOBOARD2,JORDAN1,BORSUK_2,SPRECT_1,SPRECT_3,VALUED_0,FINSEQ_2,RLTOPSP1,JORDAN2B,MONOID_0,SEQ_4,SPPOL_1,CARD_1,ZFMISC_1,CKB15,CKB25,CKB26;
constructors SETFAM_1,REAL_1,SQUARE_1,NAT_1,COMPLEX1,FINSEQOP,RCOMP_1,FINSOP_1,REALSET1,BINARITH,TOPS_1,CONNSP_1,TOPS_2,COMPTS_1,TBSP_1,MONOID_0,TREAL_1,GOBOARD2,SPPOL_1,JORDAN1,PSCOMP_1,WEIERSTR,BORSUK_2,GOBOARD9,CONNSP_3,JORDAN3,JORDAN2B,SPRECT_1,SPRECT_2,SEQ_1,BINOP_2,XXREAL_2,GOBOARD1,NAT_D,SEQ_4,FUNCSDOM,CONVEX1,CKB12,CKB14,CKB17,CKB21,CKB22,CKB37,CKB38,CKB39;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve r for Real;
theorem
Th43: (for w1,w2,w3 being (Point of ( TOP-REAL n )) holds (for P being non empty (Subset of ( TOP-REAL n )) holds (for h1,h2 being (Function of ( I[01] ),( ( TOP-REAL n ) | P )) holds ((((((h1 is  continuous & w1 = ( h1 . ( 0 ) )) & w2 = ( h1 . 1 )) & h2 is  continuous) & w2 = ( h2 . ( 0 ) )) & w3 = ( h2 . 1 )) implies (ex h3 being (Function of ( I[01] ),( ( TOP-REAL n ) | P )) st ((h3 is  continuous & w1 = ( h3 . ( 0 ) )) & w3 = ( h3 . 1 )))))))
proof
let w1 being (Point of ( TOP-REAL n )),w2 being (Point of ( TOP-REAL n )),w3 being (Point of ( TOP-REAL n ));
let P being non empty (Subset of ( TOP-REAL n ));
let h1 being (Function of ( I[01] ),( ( TOP-REAL n ) | P )),h2 being (Function of ( I[01] ),( ( TOP-REAL n ) | P ));
assume that
A1: h1 is  continuous
and
A2: w1 = ( h1 . ( 0 ) )
and
A3: w2 = ( h1 . 1 )
and
A4: h2 is  continuous
and
A5: w2 = ( h2 . ( 0 ) )
and
A6: w3 = ( h2 . 1 );
(( 0 ) in [. (( 0 ) qua Real),(1 qua Real) .] & 1 in [. (( 0 ) qua Real),(1 qua Real) .]) by XXREAL_1:1;
then reconsider p1 = w1,p2 = w2,p3 = w3 as (Point of ( ( TOP-REAL n ) | P )) by A2,A3,A6,BORSUK_1:40,FUNCT_2:5;
p2,p3 are_connected  by A4,A5,A6,BORSUK_2:def 1;
then reconsider P2 = h2 as (Path of p2,p3) by A4,A5,A6,BORSUK_2:def 2;
p1,p2 are_connected  by A1,A2,A3,BORSUK_2:def 1;
then reconsider P1 = h1 as (Path of p1,p2) by A1,A2,A3,BORSUK_2:def 2;
(ex P0 being (Path of p1,p3) st (((P0 is  continuous & ( P0 . ( 0 ) ) = p1) & ( P0 . 1 ) = p3) & (for t being (Point of ( I[01] )) holds (for t9 being Real holds (t = t9 implies (((( 0 ) <= t9 & t9 <= ( 1 / 2 )) implies ( P0 . t ) = ( P1 . ( 2 * t9 ) )) & ((( 1 / 2 ) <= t9 & t9 <= 1) implies ( P0 . t ) = ( P2 . ( ( 2 * t9 ) - 1 ) ))))))))
proof
( 1 / 2 ) in { r: (( 0 ) <= r & r <= 1) };
then reconsider pol = ( 1 / 2 ) as (Point of ( I[01] )) by BORSUK_1:40,RCOMP_1:def 1;
reconsider T1 = ( Closed-Interval-TSpace (( 0 ),( 1 / 2 )) ),T2 = ( Closed-Interval-TSpace (( 1 / 2 ),1) ) as (SubSpace of ( I[01] )) by TOPMETR:20,TREAL_1:3;
set e2 = ( P[01] (( 1 / 2 ),1,( (#) (( 0 ),1) ),( (( 0 ),1) (#) )) );
set e1 = ( P[01] (( 0 ),( 1 / 2 ),( (#) (( 0 ),1) ),( (( 0 ),1) (#) )) );
set E1 = ( P1 * e1 );
set E2 = ( P2 * e2 );
set f = ( E1 +* E2 );
A7: ( dom e1 ) = (the carrier of ( Closed-Interval-TSpace (( 0 ),( 1 / 2 )) )) by FUNCT_2:def 1
.= [. ( 0 ),( 1 / 2 ) .] by TOPMETR:18;
A8: ( dom e2 ) = (the carrier of ( Closed-Interval-TSpace (( 1 / 2 ),1) )) by FUNCT_2:def 1
.= [. ( 1 / 2 ),(1 qua Real) .] by TOPMETR:18;
reconsider gg = E2 as (Function of T2,( ( TOP-REAL n ) | P )) by TOPMETR:20;
reconsider ff = E1 as (Function of T1,( ( TOP-REAL n ) | P )) by TOPMETR:20;
A9: (for t9 being Real holds ((( 1 / 2 ) <= t9 & t9 <= 1) implies ( E2 . t9 ) = ( P2 . ( ( 2 * t9 ) - 1 ) )))
proof
reconsider r1 = ( (#) (( 0 ),1) ),r2 = ( (( 0 ),1) (#) ) as Real by BORSUK_1:def 14,BORSUK_1:def 15,TREAL_1:5;
( dom e2 ) = (the carrier of ( Closed-Interval-TSpace (( 1 / 2 ),1) )) by FUNCT_2:def 1;
then A10: ( dom e2 ) = [. ( 1 / 2 ),(1 qua Real) .] by TOPMETR:18
.= { r: (( 1 / 2 ) <= r & r <= 1) } by RCOMP_1:def 1;
let t9 being Real;
assume (( 1 / 2 ) <= t9 & t9 <= 1);
then A11: t9 in ( dom e2 ) by A10;
then reconsider s = t9 as (Point of ( Closed-Interval-TSpace (( 1 / 2 ),1) ));
( e2 . s ) = ( ( ( ( r2 - r1 ) / ( 1 - ( 1 / 2 ) ) ) * t9 ) + ( ( ( 1 * r1 ) - ( ( 1 / 2 ) * r2 ) ) / ( 1 - ( 1 / 2 ) ) ) ) by TREAL_1:11
.= ( ( 2 * t9 ) - 1 ) by BORSUK_1:def 14,BORSUK_1:def 15,TREAL_1:5;
hence thesis by A11,FUNCT_1:13;
end;
A12: (for t9 being Real holds ((( 0 ) <= t9 & t9 <= ( 1 / 2 )) implies ( E1 . t9 ) = ( P1 . ( 2 * t9 ) )))
proof
reconsider r1 = ( (#) (( 0 ),1) ),r2 = ( (( 0 ),1) (#) ) as Real by BORSUK_1:def 14,BORSUK_1:def 15,TREAL_1:5;
( dom e1 ) = (the carrier of ( Closed-Interval-TSpace (( 0 ),( 1 / 2 )) )) by FUNCT_2:def 1;
then A13: ( dom e1 ) = [. ( 0 ),( 1 / 2 ) .] by TOPMETR:18
.= { r: (( 0 ) <= r & r <= ( 1 / 2 )) } by RCOMP_1:def 1;
let t9 being Real;
assume (( 0 ) <= t9 & t9 <= ( 1 / 2 ));
then A14: t9 in ( dom e1 ) by A13;
then reconsider s = t9 as (Point of ( Closed-Interval-TSpace (( 0 ),( 1 / 2 )) ));
( e1 . s ) = ( ( ( ( r2 - r1 ) / ( ( 1 / 2 ) - ( 0 ) ) ) * t9 ) + ( ( ( ( 1 / 2 ) * r1 ) - ( ( 0 ) * r2 ) ) / ( ( 1 / 2 ) - ( 0 ) ) ) ) by TREAL_1:11
.= ( 2 * t9 ) by BORSUK_1:def 14,BORSUK_1:def 15,TREAL_1:5;
hence thesis by A14,FUNCT_1:13;
end;
then A15: ( ff . ( 1 / 2 ) ) = ( P2 . ( ( 2 * ( 1 / 2 ) ) - 1 ) ) by A3,A5
.= ( gg . pol ) by A9;
(( [#] T1 ) = [. ( 0 ),( 1 / 2 ) .] & ( [#] T2 ) = [. ( 1 / 2 ),(1 qua Real) .]) by TOPMETR:18;
then A16: (( ( [#] T1 ) \/ ( [#] T2 ) ) = ( [#] ( I[01] ) ) & ( ( [#] T1 ) /\ ( [#] T2 ) ) = { pol }) by BORSUK_1:40,XXREAL_1:174,XXREAL_1:418;
( rng f ) c= ( ( rng E1 ) \/ ( rng E2 ) ) by FUNCT_4:17;
then A17: ( rng f ) c= (the carrier of ( ( TOP-REAL n ) | P )) by XBOOLE_1:1;
A18: (T1 is  compact & T2 is  compact) by HEINE:4;
( dom P1 ) = (the carrier of ( I[01] )) by FUNCT_2:def 1;
then A19: ( rng e1 ) c= ( dom P1 ) by TOPMETR:20;
(( dom P2 ) = (the carrier of ( I[01] )) & ( rng e2 ) c= (the carrier of ( Closed-Interval-TSpace (( 0 ),1) ))) by FUNCT_2:def 1;
then A20: ( dom E2 ) = ( dom e2 ) by RELAT_1:27,TOPMETR:20;
(not ( 0 ) in { r: (( 1 / 2 ) <= r & r <= 1) })
proof
assume ( 0 ) in { r: (( 1 / 2 ) <= r & r <= 1) };
then (ex rr being Real st ((rr = ( 0 ) & ( 1 / 2 ) <= rr) & rr <= 1));
hence thesis;
end;
then (not ( 0 ) in ( dom E2 )) by A8,A20,RCOMP_1:def 1;
then A21: ( f . ( 0 ) ) = ( E1 . ( 0 ) ) by FUNCT_4:11
.= ( P1 . ( 2 * ( 0 ) ) ) by A12
.= p1 by A2;
( dom f ) = ( ( dom E1 ) \/ ( dom E2 ) ) by FUNCT_4:def 1
.= ( [. ( 0 ),( 1 / 2 ) .] \/ [. ( 1 / 2 ),(1 qua Real) .] ) by A7,A8,A19,A20,RELAT_1:27
.= (the carrier of ( I[01] )) by BORSUK_1:40,XXREAL_1:174;
then reconsider f as (Function of ( I[01] ),( ( TOP-REAL n ) | P )) by A17,FUNCT_2:def 1,RELSET_1:4;
(e1 is  continuous & e2 is  continuous) by TREAL_1:12;
then reconsider f as  continuous (Function of ( I[01] ),( ( TOP-REAL n ) | P )) by A1,A4,A15,A16,A18,COMPTS_1:20,TOPMETR:20;
1 in { r: (( 1 / 2 ) <= r & r <= 1) };
then 1 in ( dom E2 ) by A8,A20,RCOMP_1:def 1;
then A22: ( f . 1 ) = ( E2 . 1 ) by FUNCT_4:13
.= ( P2 . ( ( 2 * 1 ) - 1 ) ) by A9
.= p3 by A6;
then p1,p3 are_connected  by A21,BORSUK_2:def 1;
then reconsider f as (Path of p1,p3) by A21,A22,BORSUK_2:def 2;
(for t being (Point of ( I[01] )) holds (for t9 being Real holds (t = t9 implies (((( 0 ) <= t9 & t9 <= ( 1 / 2 )) implies ( f . t ) = ( P1 . ( 2 * t9 ) )) & ((( 1 / 2 ) <= t9 & t9 <= 1) implies ( f . t ) = ( P2 . ( ( 2 * t9 ) - 1 ) ))))))
proof
let t being (Point of ( I[01] ));
let t9 being Real;
assume A23: t = t9;
thus ((( 0 ) <= t9 & t9 <= ( 1 / 2 )) implies ( f . t ) = ( P1 . ( 2 * t9 ) ))
proof
assume A24: (( 0 ) <= t9 & t9 <= ( 1 / 2 ));
then t9 in { r: (( 0 ) <= r & r <= ( 1 / 2 )) };
then A25: t9 in [. ( 0 ),( 1 / 2 ) .] by RCOMP_1:def 1;
per cases ;
suppose A26: t9 <> ( 1 / 2 );

(not t9 in ( dom E2 ))
proof
assume t9 in ( dom E2 );
then t9 in ( [. ( 0 ),( 1 / 2 ) .] /\ [. ( 1 / 2 ),(1 qua Real) .] ) by A8,A20,A25,XBOOLE_0:def 4;
then t9 in { ( 1 / 2 ) } by XXREAL_1:418;
hence thesis by A26,TARSKI:def 1;
end;
then ( f . t ) = ( E1 . t ) by A23,FUNCT_4:11
.= ( P1 . ( 2 * t9 ) ) by A12,A23,A24;
hence thesis;
end;
suppose A27: t9 = ( 1 / 2 );

( 1 / 2 ) in { r: (( 1 / 2 ) <= r & r <= 1) };
then ( 1 / 2 ) in [. ( 1 / 2 ),(1 qua Real) .] by RCOMP_1:def 1;
then ( 1 / 2 ) in (the carrier of ( Closed-Interval-TSpace (( 1 / 2 ),1) )) by TOPMETR:18;
then t in ( dom E2 ) by A23,A27,FUNCT_2:def 1,TOPMETR:20;
then ( f . t ) = ( E2 . ( 1 / 2 ) ) by A23,A27,FUNCT_4:13
.= ( P1 . ( 2 * t9 ) ) by A12,A15,A27;
hence thesis;
end;
end;

thus ((( 1 / 2 ) <= t9 & t9 <= 1) implies ( f . t ) = ( P2 . ( ( 2 * t9 ) - 1 ) ))
proof
assume A28: (( 1 / 2 ) <= t9 & t9 <= 1);
then t9 in { r: (( 1 / 2 ) <= r & r <= 1) };
then t9 in [. ( 1 / 2 ),(1 qua Real) .] by RCOMP_1:def 1;
then ( f . t ) = ( E2 . t ) by A8,A20,A23,FUNCT_4:13
.= ( P2 . ( ( 2 * t9 ) - 1 ) ) by A9,A23,A28;
hence thesis;
end;

end;
hence thesis by A21,A22;
end;
hence thesis;
end;
