environ
vocabularies NUMBERS,SUBSET_1,FUNCT_1,NAT_1,TARSKI,MEMBERED,ORDINAL1,FINSET_1,RELAT_1,AFINSQ_1,ARYTM_1,ARYTM_3,FINSEQ_1,XXREAL_0,CARD_1,XBOOLE_0,ORDINAL4,FINSEQ_5,RFINSEQ,JORDAN3,CARD_3,XCMPLX_0,AFINSQ_2,BINOP_1,SETWISEO,FINSOP_1,FUNCOP_1,BINOP_2,VALUED_0,FUNCT_2,INT_1,PRGCOR_2,XREAL_0,SEQ_1,SERIES_1,VALUED_1,RAT_1,SQUARE_1,COMPLEX1,PARTFUN3,PRE_POLY,AMISTD_1,AMISTD_2;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,XREAL_0,NUMBERS,RELAT_1,FUNCT_1,XCMPLX_0,NAT_1,FINSET_1,ORDINAL1,XXREAL_0,NAT_D,AFINSQ_1,SEQ_1,MEMBERED,VALUED_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,INT_1,BINOP_1,BINOP_2,SETWISEO,FINSOP_1,FINSEQ_1,RECDEF_1,VALUED_0,SERIES_1,RAT_1,PARTFUN3,CKB33;
definitions TARSKI,XBOOLE_0,FUNCT_1,VALUED_1,CKB33;
theorems TARSKI,FUNCT_1,NAT_1,ZFMISC_1,RELAT_1,CARD_2,XBOOLE_0,XBOOLE_1,FINSET_1,ORDINAL1,CARD_1,XREAL_1,AFINSQ_1,XXREAL_0,NAT_2,FINSEQ_2,WELLORD2,MEMBERED,VALUED_0,VALUED_1,XREAL_0,NAT_D,SERIES_1,PARTFUN3,BINOP_1,BINOP_2,SETWISEO,FUNCOP_1,FINSOP_1,FINSEQ_1,FUNCT_2,XCMPLX_0,GRFUNC_1,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB33;
schemes NAT_1,AFINSQ_1,FUNCT_2,BINOP_1,CKB8;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FUNCOP_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,BINOP_2,CARD_1,FINSEQ_1,AFINSQ_1,RELSET_1,ORDINAL3,VALUED_1,VALUED_0,MEMBERED,CKB4,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32;
constructors SERIES_1,PARTFUN3,WELLORD2,SETWISEO,REAL_1,FINSOP_1,NAT_D,RECDEF_1,BINOP_2,RELSET_1,ORDINAL4,AFINSQ_1,MATRIX_7,SQUARE_1,FINSEQ_4,BINOP_1,CKB33;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve x for set;
reserve p for XFinSequence;
theorem
Th8: (( dom p ) = ( dom ( Rev p ) ) & ( rng p ) = ( rng ( Rev p ) ))
proof
thus A1: ( dom p ) = ( len p )
.= ( len ( Rev p ) ) by CKB33:def 1
.= ( dom ( Rev p ) );
A2: ( len p ) = ( len ( Rev p ) ) by CKB33:def 1;
hereby
let x being set;
assume x in ( rng p );
then consider z being set such that A3: z in ( dom p ) and A4: ( p . z ) = x by FUNCT_1:def 3;
reconsider i = z as (Element of ( NAT )) by A3;
i < ( len p ) by A3,NAT_1:44;
then ( i + 1 ) <= ( len p ) by NAT_1:13;
then ( ( len p ) -' ( i + 1 ) ) = ( ( len p ) - ( i + 1 ) ) by XREAL_1:233;
then reconsider j = ( ( len p ) - ( i + 1 ) ) as (Element of ( NAT ));
( ( len p ) - ( i + 1 ) ) < ( len p ) by XREAL_1:44;
then A5: j in ( len ( Rev p ) ) by A2,NAT_1:44;
then ( ( Rev p ) . j ) = ( p . ( ( len p ) - ( j + 1 ) ) ) by CKB33:def 1;
hence x in ( rng ( Rev p ) ) by A4,A5,FUNCT_1:def 3;
end;
let x;
assume x in ( rng ( Rev p ) );
then consider z being set such that A6: z in ( dom ( Rev p ) ) and A7: ( ( Rev p ) . z ) = x by FUNCT_1:def 3;
reconsider i = z as (Element of ( NAT )) by A6;
i < ( len p ) by A2,A6,NAT_1:44;
then ( i + 1 ) <= ( len p ) by NAT_1:13;
then ( ( len p ) -' ( i + 1 ) ) = ( ( len p ) - ( i + 1 ) ) by XREAL_1:233;
then reconsider j = ( ( len p ) - ( i + 1 ) ) as (Element of ( NAT ));
( ( len p ) - ( i + 1 ) ) < ( len p ) by XREAL_1:44;
then A8: j in ( len ( Rev p ) ) by A2,NAT_1:44;
( ( Rev p ) . i ) = ( p . ( ( len p ) - ( i + 1 ) ) ) by A6,CKB33:def 1;
hence thesis by A1,A7,A8,FUNCT_1:def 3;
end;
