environ
vocabularies NUMBERS,SUBSET_1,FUNCT_1,NAT_1,TARSKI,MEMBERED,ORDINAL1,FINSET_1,RELAT_1,AFINSQ_1,ARYTM_1,ARYTM_3,FINSEQ_1,XXREAL_0,CARD_1,XBOOLE_0,ORDINAL4,FINSEQ_5,RFINSEQ,JORDAN3,CARD_3,XCMPLX_0,AFINSQ_2,BINOP_1,SETWISEO,FINSOP_1,FUNCOP_1,BINOP_2,VALUED_0,FUNCT_2,INT_1,PRGCOR_2,XREAL_0,SEQ_1,SERIES_1,VALUED_1,RAT_1,SQUARE_1,COMPLEX1,PARTFUN3,PRE_POLY,AMISTD_1,AMISTD_2;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,XREAL_0,NUMBERS,RELAT_1,FUNCT_1,XCMPLX_0,NAT_1,FINSET_1,ORDINAL1,XXREAL_0,NAT_D,AFINSQ_1,SEQ_1,MEMBERED,VALUED_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,INT_1,BINOP_1,BINOP_2,SETWISEO,FINSOP_1,FINSEQ_1,RECDEF_1,VALUED_0,SERIES_1,RAT_1,PARTFUN3,CKB33,CKB36,CKB47,CKB55,CKB60,CKB61,CKB75,CKB82;
definitions TARSKI,XBOOLE_0,FUNCT_1,VALUED_1,CKB33,CKB36,CKB47,CKB55,CKB60,CKB61,CKB75,CKB82;
theorems TARSKI,FUNCT_1,NAT_1,ZFMISC_1,RELAT_1,CARD_2,XBOOLE_0,XBOOLE_1,FINSET_1,ORDINAL1,CARD_1,XREAL_1,AFINSQ_1,XXREAL_0,NAT_2,FINSEQ_2,WELLORD2,MEMBERED,VALUED_0,VALUED_1,XREAL_0,NAT_D,SERIES_1,PARTFUN3,BINOP_1,BINOP_2,SETWISEO,FUNCOP_1,FINSOP_1,FINSEQ_1,FUNCT_2,XCMPLX_0,GRFUNC_1,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB33,CKB34,CKB36,CKB37,CKB38,CKB39,CKB41,CKB42,CKB43,CKB44,CKB45,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB55,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91;
schemes NAT_1,AFINSQ_1,FUNCT_2,BINOP_1,CKB8,CKB81;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FUNCOP_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,BINOP_2,CARD_1,FINSEQ_1,AFINSQ_1,RELSET_1,ORDINAL3,VALUED_1,VALUED_0,MEMBERED,CKB4,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB35,CKB40,CKB46,CKB54,CKB56,CKB77,CKB78,CKB79,CKB80;
constructors SERIES_1,PARTFUN3,WELLORD2,SETWISEO,REAL_1,FINSOP_1,NAT_D,RECDEF_1,BINOP_2,RELSET_1,ORDINAL4,AFINSQ_1,MATRIX_7,SQUARE_1,FINSEQ_4,BINOP_1,CKB33,CKB36,CKB47,CKB55,CKB60,CKB61,CKB75,CKB82;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve k for Nat;
reserve n for Nat;
reserve D for non  empty set;
reserve F for (XFinSequence of D);
reserve G for (XFinSequence of D);
reserve b for (BinOp of D);
theorem
(for bFG being (XFinSequence of D) holds (((((b is  commutative  associative & (b is  having_a_unity or ( len F ) >= 1)) & ( len F ) = ( len G )) & ( len F ) = ( len bFG )) & (for n holds (n in ( dom bFG ) implies ( bFG . n ) = ( b . (( F . n ),( G . n )) )))) implies ( b "**" ( F ^ G ) ) = ( b "**" bFG )))
proof
let bFG being (XFinSequence of D);
assume that
A1: b is  commutative  associative
and
A2: (b is  having_a_unity or ( len F ) >= 1)
and
A3: ( len F ) = ( len G )
and
A4: ( len F ) = ( len bFG )
and
A5: (for n holds (n in ( dom bFG ) implies ( bFG . n ) = ( b . (( F . n ),( G . n )) )));
set xG = ( XFS2FS G );
set xF = ( XFS2FS F );
A6: (( b "**" F ) = ( b "**" xF ) & ( b "**" G ) = ( b "**" xG )) by A2,A3,CKB90:1;
set xb = ( XFS2FS bFG );
A7: ( len xb ) = ( len bFG ) by AFINSQ_1:def 9;
A8: (for k being (Element of ( NAT )) holds (k in ( dom xb ) implies ( xb . k ) = ( b . (( xF . k ),( xG . k )) )))
proof
let k being (Element of ( NAT ));
assume that
A9: k in ( dom xb );
k in ( Seg ( len xb ) ) by A9,FINSEQ_1:def 3;
then k >= 1 by FINSEQ_1:1;
then reconsider k1 = ( k - 1 ) as (Element of ( NAT )) by NAT_1:21;
A10: k in ( Seg ( len xb ) ) by A9,FINSEQ_1:def 3;
then A11: 1 <= k by FINSEQ_1:1;
then A12: k1 = ( k -' 1 ) by XREAL_1:233;
k in ( Seg ( len xb ) ) by A9,FINSEQ_1:def 3;
then (k1 < ( k1 + 1 ) & k <= ( len xb )) by FINSEQ_1:1,NAT_1:13;
then k1 < ( len xb ) by XXREAL_0:2;
then k1 in ( dom bFG ) by A7,NAT_1:44;
then A13: ( bFG . k1 ) = ( b . (( F . k1 ),( G . k1 )) ) by A5;
A14: k <= ( len bFG ) by A7,A10,FINSEQ_1:1;
then (( bFG . ( k -' 1 ) ) = ( xb . k ) & ( F . ( k -' 1 ) ) = ( xF . k )) by A4,A11,AFINSQ_1:def 9;
hence thesis by A3,A4,A11,A14,A13,A12,AFINSQ_1:def 9;
end;
(( len xF ) = ( len F ) & ( len G ) = ( len xG )) by AFINSQ_1:def 9;
then ( b "**" xb ) = ( b . (( b "**" xF ),( b "**" xG )) ) by A1,A2,A3,A4,A7,A8,FINSOP_1:9;
then ( b "**" bFG ) = ( b . (( b "**" F ),( b "**" G )) ) by A2,A4,A6,CKB90:1;
hence thesis by A1,A2,A3,CKB88:1;
end;
