environ
vocabularies XCMPLX_0,ORDINAL1,ARYTM_3,CARD_1,NUMBERS,SUBSET_1,ARYTM_0,ARYTM_1,RELAT_1;
notations SUBSET_1,ORDINAL1,NUMBERS,ARYTM_0,XCMPLX_0;
theorems ARYTM_0,XCMPLX_0,CKB1;
registrations XCMPLX_0,ORDINAL1;
constructors FUNCT_4,ARYTM_0,XCMPLX_0;
requirements NUMERALS,SUBSET,BOOLE;
begin
theorem
Lm1: ( - ( 0 ) ) = ( 0 )
proof
( ( 0 ) + ( - ( 0 ) ) ) = ( - ( 0 ) ) by CKB1:1;
hence thesis by XCMPLX_0:def 6;
end;
