environ
vocabularies XBOOLE_0,TARSKI,RELAT_1,FUNCT_1,ZFMISC_1,SUBSET_1,MCART_1,PARTFUN1,FUNCT_2,FUNCT_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELSET_1,FUNCT_1,FUNCT_2,BINOP_1,CKB9;
definitions TARSKI,BINOP_1,CKB9;
theorems TARSKI,ZFMISC_1,FUNCT_1,FUNCT_2,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19;
schemes FUNCT_1,CKB6,CKB7;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1;
constructors BINOP_1,RELSET_1,CKB9;
requirements SUBSET,BOOLE;
begin
reserve x for set;
reserve B for set;
reserve Y for set;
theorem
(for f being Function holds (B c= ( bool ( rng f ) ) implies ( f " ( union B ) ) = ( union ( ( .: f ) " B ) )))
proof
let f being Function;
assume that
A1: B c= ( bool ( rng f ) );
A2: ( f " ( union B ) ) c= ( union ( ( .: f ) " B ) )
proof
let x;
assume A3: x in ( f " ( union B ) );
then ( f . x ) in ( union B ) by FUNCT_1:def 7;
then consider Y such that A4: ( f . x ) in Y and A5: Y in B by TARSKI:def 4;
A6: ( f " Y ) c= ( dom f ) by RELAT_1:132;
then ( f " Y ) in ( bool ( dom f ) );
then A7: ( f " Y ) in ( dom ( .: f ) ) by CKB9:def 1;
( f .: ( f " Y ) ) = Y by A1,A5,FUNCT_1:77;
then ( ( .: f ) . ( f " Y ) ) in B by A5,A6,CKB9:def 1;
then A8: ( f " Y ) in ( ( .: f ) " B ) by A7,FUNCT_1:def 7;
x in ( dom f ) by A3,FUNCT_1:def 7;
then x in ( f " Y ) by A4,FUNCT_1:def 7;
hence thesis by A8,TARSKI:def 4;
end;
( union ( ( .: f ) " B ) ) c= ( f " ( union B ) ) by CKB19:1;
hence thesis by A2,XBOOLE_0:def 10;
end;
