environ
vocabularies XBOOLE_0,TARSKI,RELAT_1,FUNCT_1,ZFMISC_1,SUBSET_1,MCART_1,PARTFUN1,FUNCT_2,FUNCT_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELSET_1,FUNCT_1,FUNCT_2,BINOP_1,CKB9,CKB24,CKB25,CKB41;
definitions TARSKI,BINOP_1,CKB9,CKB25,CKB41;
theorems TARSKI,ZFMISC_1,FUNCT_1,FUNCT_2,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45;
schemes FUNCT_1,CKB6,CKB7;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1;
constructors BINOP_1,RELSET_1,CKB9,CKB24,CKB25,CKB41;
requirements SUBSET,BOOLE;
begin
reserve x for set;
reserve X for set;
theorem
(for f being (Function of X,{ ( {} ),1 }) holds f = ( chi (( f " { 1 } ),X) ))
proof
let f being (Function of X,{ ( {} ),1 });
now
thus A1: ( dom f ) = X by FUNCT_2:def 1;
let x;
assume that
A2: x in X;
thus (x in ( f " { 1 } ) implies ( f . x ) = 1)
proof
assume x in ( f " { 1 } );
then ( f . x ) in { 1 } by FUNCT_1:def 7;
hence thesis by TARSKI:def 1;
end;

assume (not x in ( f " { 1 } ));
then (not ( f . x ) in { 1 }) by A1,A2,FUNCT_1:def 7;
then A3: (( rng f ) c= { ( {} ),1 } & ( f . x ) <> 1) by RELAT_1:def 19,TARSKI:def 1;
( f . x ) in ( rng f ) by A1,A2,FUNCT_1:def 3;
hence ( f . x ) = ( {} ) by A3,TARSKI:def 2;
end;
hence thesis by CKB41:def 1;
end;
