environ
vocabularies XBOOLE_0,TARSKI,RELAT_1,FUNCT_1,ZFMISC_1,SUBSET_1,MCART_1,PARTFUN1,FUNCT_2,FUNCT_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELSET_1,FUNCT_1,FUNCT_2,BINOP_1,CKB9,CKB24,CKB25,CKB41,CKB47,CKB48,CKB49,CKB52,CKB53,CKB58,CKB59,CKB60,CKB62,CKB63,CKB77,CKB84;
definitions TARSKI,BINOP_1,CKB9,CKB25,CKB41,CKB52,CKB53,CKB60,CKB63,CKB84;
theorems TARSKI,ZFMISC_1,FUNCT_1,FUNCT_2,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB60,CKB61,CKB63,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93;
schemes FUNCT_1,CKB6,CKB7;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,CKB64,CKB65;
constructors BINOP_1,RELSET_1,CKB9,CKB24,CKB25,CKB41,CKB47,CKB49,CKB52,CKB53,CKB58,CKB59,CKB60,CKB62,CKB63,CKB77,CKB84;
requirements SUBSET,BOOLE;
begin
reserve V for set;
reserve X for set;
reserve Y for set;
reserve Z for set;
theorem
Th95: (for f being (Function of X,Y) holds (for g being (Function of V,Z) holds [: f,g :] is (Function of [: X,V :],[: Y,Z :])))
proof
let f being (Function of X,Y);
let g being (Function of V,Z);
per cases ;
suppose A1: ([: Y,Z :] = ( {} ) implies [: X,V :] = ( {} ));

now
per cases  by A1;
suppose A2: [: Y,Z :] <> ( {} );

(( rng f ) c= Y & ( rng g ) c= Z) by RELAT_1:def 19;
then [: ( rng f ),( rng g ) :] c= [: Y,Z :] by ZFMISC_1:96;
then A3: ( rng [: f,g :] ) c= [: Y,Z :] by CKB87:1;
(Z = ( {} ) implies V = ( {} )) by A2,ZFMISC_1:90;
then A4: ( dom g ) = V by FUNCT_2:def 1;
(Y = ( {} ) implies X = ( {} )) by A2,ZFMISC_1:90;
then ( dom f ) = X by FUNCT_2:def 1;
then ( dom [: f,g :] ) = [: X,V :] by A4,CKB84:def 1;
hence thesis by A1,A3,FUNCT_2:def 1,RELSET_1:4;
end;
suppose A5: [: X,V :] = ( {} );

then (X = ( {} ) or V = ( {} ));
then (( dom f ) = ( {} ) or ( dom g ) = ( {} ));
then [: ( dom f ),( dom g ) :] = ( {} ) by ZFMISC_1:90;
then A6: ( dom [: f,g :] ) = [: X,V :] by A5,CKB84:def 1;
(( rng f ) c= Y & ( rng g ) c= Z) by RELAT_1:def 19;
then [: ( rng f ),( rng g ) :] c= [: Y,Z :] by ZFMISC_1:96;
then ( rng [: f,g :] ) c= [: Y,Z :] by CKB87:1;
hence thesis by A1,A6,FUNCT_2:def 1,RELSET_1:4;
end;
end;
hence thesis;
end;
suppose A7: ([: Y,Z :] = ( {} ) & [: X,V :] <> ( {} ));

then (Y = ( {} ) or Z = ( {} ));
then (f = ( {} ) or g = ( {} ));
then [: ( dom f ),( dom g ) :] = ( {} ) by RELAT_1:38,ZFMISC_1:90;
then A8: ( dom [: f,g :] ) = ( {} ) by CKB84:def 1;
then (( rng [: f,g :] ) = ( {} ) & ( dom [: f,g :] ) c= [: X,V :]) by RELAT_1:42,XBOOLE_1:2;
then reconsider R = [: f,g :] as (Relation of [: X,V :],[: Y,Z :]) by RELSET_1:4,XBOOLE_1:2;
[: f,g :] = ( {} ) by A8;
then R is  quasi_total by A7,FUNCT_2:def 1;
hence thesis;
end;
end;
