environ
vocabularies REAL_1,SUBSET_1,NUMBERS,INTEGRA1,RCOMP_1,RELAT_1,JGRAPH_2,ARYTM_3,CARD_1,SIN_COS,VALUED_1,ARYTM_1,FDIFF_1,FUNCT_1,SQUARE_1,PREPOWER,SIN_COS2,ORDINAL2,XXREAL_2,XXREAL_1,INTEGRA5,XBOOLE_0,PARTFUN1,TARSKI,ORDINAL4,SIN_COS4,SIN_COS9,XXREAL_0,TAYLOR_1,SIN_COS6,SEQ_4,MEASURE5;
notations TARSKI,XBOOLE_0,SEQ_1,SIN_COS,SUBSET_1,NUMBERS,VALUED_1,XXREAL_0,REAL_1,RELAT_1,PARTFUN1,PARTFUN2,RCOMP_1,RFUNCT_1,MEASURE5,MEASURE6,INTEGRA1,FCONT_1,SQUARE_1,INTEGRA5,PREPOWER,TAYLOR_1,FDIFF_1,SEQ_2,SIN_COS2,FDIFF_9,SIN_COS4,SIN_COS6,SIN_COS9,SEQ_4;
definitions SIN_COS,VALUED_1,SUBSET_1,SQUARE_1,SIN_COS4,SIN_COS6,TARSKI,FCONT_1,FDIFF_9,XBOOLE_0,SIN_COS9,RCOMP_1,LIMFUNC1,NAT_1;
theorems PARTFUN1,RFUNCT_1,FUNCT_1,FDIFF_1,FUNCT_2,SQUARE_1,XCMPLX_1,INTEGRA5,INTEGRA8,SIN_COS,FDIFF_4,TAYLOR_1,VALUED_1,FCONT_1,SIN_COS5,SIN_COS4,SIN_COS2,SIN_COS6,XXREAL_1,XBOOLE_1,FDIFF_5,FDIFF_7,FDIFF_8,FDIFF_9,SIN_COS9,PREPOWER,FDIFF_6,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74;
registrations VALUED_1,NAT_1,NUMBERS,MEMBERED,VALUED_0,INTEGRA1,INT_1,RELAT_1,ORDINAL1,FUNCT_2,RCOMP_1,FCONT_1,TOPREALB,FCONT_3,REAL_1,MEASURE5;
constructors SIN_COS,TAYLOR_1,SEQ_1,REAL_1,FDIFF_1,FCONT_1,MEASURE6,BINOP_2,SQUARE_1,PREPOWER,INTEGRA5,SIN_COS2,SEQ_4,SEQ_2,SIN_COS9,PARTFUN1,PARTFUN2,FUNCT_1,RCOMP_1,RELAT_1,SIN_COS6,RFUNCT_1,VALUED_1,FDIFF_9,SIN_COS4,LIMFUNC1,NAT_1,POWER,RELSET_1,INTEGRA1;
requirements NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve x for Real;
reserve A for non  empty  closed_interval (Subset of ( REAL ));
reserve Z for  open (Subset of ( REAL ));
reserve f for (PartFunc of ( REAL ),( REAL ));
reserve f1 for (PartFunc of ( REAL ),( REAL ));
reserve f2 for (PartFunc of ( REAL ),( REAL ));
theorem
(((((((A c= Z & Z c= ]. ( - 1 ),1 .[) & f = ( f1 - f2 )) & f2 = ( #Z 2 )) & (for x holds (x in Z implies ((( f1 . x ) = 1 & ( f . x ) > ( 0 )) & x <> ( 0 ))))) & ( dom ( arccos ) ) = Z) & Z c= ( dom ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) )) implies ( integral (( arccos ),A) ) = ( ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) . ( upper_bound A ) ) - ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) . ( lower_bound A ) ) ))
proof
assume that
A1: A c= Z
and
A2: ((Z c= ]. ( - 1 ),1 .[ & f = ( f1 - f2 )) & (f2 = ( #Z 2 ) & (for x holds (x in Z implies ((( f1 . x ) = 1 & ( f . x ) > ( 0 )) & x <> ( 0 ))))))
and
A3: ( dom ( arccos ) ) = Z
and
A4: Z c= ( dom ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) );
A5: ( ( arccos ) | A ) is  bounded by A1,A3,INTEGRA5:10;
A6: ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) is_differentiable_on Z by A2,A4,FDIFF_7:24;
A7: (for x holds (x in ( dom ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) `| Z ) ) implies ( ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) `| Z ) . x ) = ( ( arccos ) . x )))
proof
let x;
assume x in ( dom ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) `| Z ) );
then x in Z by A6,FDIFF_1:def 7;
hence thesis by A2,A4,FDIFF_7:24;
end;
( dom ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) `| Z ) ) = ( dom ( arccos ) ) by A3,A6,FDIFF_1:def 7;
then ( ( ( ( id Z ) (#) ( arccos ) ) - ( ( #R ( 1 / 2 ) ) * f ) ) `| Z ) = ( arccos ) by A7,PARTFUN1:5;
hence thesis by A1,A3,A5,A6,INTEGRA5:11,INTEGRA5:13;
end;
