environ
vocabularies NUMBERS,SUBSET_1,FINSEQ_1,RELAT_1,TREES_1,XBOOLE_0,ARYTM_3,XXREAL_0,ORDINAL4,CARD_1,FUNCT_1,TARSKI,TREES_2,TREES_9,ORDINAL1,NAT_1,FINSET_1,QC_LANG1,ZF_LANG,CLASSES2,TREES_4,QC_LANG4;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,NAT_1,RELAT_1,FUNCT_1,FUNCT_2,BINOP_1,FINSET_1,FINSEQ_1,FINSEQ_4,TREES_1,TREES_2,TREES_4,TREES_9,QC_LANG1,QC_LANG2,MCART_1,XXREAL_0,CKB3,CKB6,CKB21;
definitions TARSKI,XBOOLE_0,TREES_2,TREES_4,BINOP_1,CKB3,CKB6,CKB21;
theorems TARSKI,NAT_1,RELAT_1,FUNCT_1,FINSEQ_1,TREES_1,TREES_2,TREES_9,GRFUNC_1,QC_LANG1,QC_LANG2,XBOOLE_0,XBOOLE_1,FINSEQ_6,XREAL_1,XXREAL_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24;
schemes NAT_1,TREES_2,FINSEQ_1,TREES_9;
registrations SUBSET_1,ORDINAL1,RELSET_1,FINSET_1,XREAL_0,NAT_1,FINSEQ_1,TREES_1,TREES_2,TREES_A,TREES_9,CARD_1,RELAT_1;
constructors BINOP_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_4,TREES_4,TREES_9,QC_LANG2,RELSET_1,CKB3,CKB6,CKB21;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve m for (Element of ( NAT ));
reserve F for (Element of ( QC-WFF ));
reserve t for (Element of ( dom ( tree_of_subformulae F ) ));
reserve t9 for (Element of ( dom ( tree_of_subformulae F ) ));
theorem
Th52: ((t9 = ( t ^ <* m *> ) & ( ( tree_of_subformulae F ) . t ) is  conjunctive) implies ((( ( tree_of_subformulae F ) . t9 ) = ( the_left_argument_of ( ( tree_of_subformulae F ) . t ) ) & m = ( 0 )) or (( ( tree_of_subformulae F ) . t9 ) = ( the_right_argument_of ( ( tree_of_subformulae F ) . t ) ) & m = 1)))
proof
set G = ( ( tree_of_subformulae F ) . t );
set H = ( ( tree_of_subformulae F ) . t9 );
assume that
A1: t9 = ( t ^ <* m *> )
and
A2: G is  conjunctive;
A3: ( list_of_immediate_constituents G ) = <* ( the_left_argument_of G ),( the_right_argument_of G ) *> by A2,CKB3:def 1;
( len <* ( the_left_argument_of G ),( the_right_argument_of G ) *> ) = 2 by FINSEQ_1:44;
then A4: ( dom <* ( the_left_argument_of G ),( the_right_argument_of G ) *> ) = ( Seg 2 ) by FINSEQ_1:def 3;
A5: ( succ (( tree_of_subformulae F ),t) ) = ( list_of_immediate_constituents G ) by CKB6:def 1;
(ex q being (Element of ( dom ( tree_of_subformulae F ) )) st (q = t & ( succ (( tree_of_subformulae F ),t) ) = ( ( tree_of_subformulae F ) * ( q succ ) ))) by TREES_9:def 6;
then ( dom <* ( the_left_argument_of G ),( the_right_argument_of G ) *> ) = ( dom ( t succ ) ) by A5,A3,TREES_9:37;
then ( m + 1 ) in ( dom <* ( the_left_argument_of G ),( the_right_argument_of G ) *> ) by A1,TREES_9:39;
then A6: (( m + 1 ) = ( ( 0 ) + 1 ) or ( m + 1 ) = ( 1 + 1 )) by A4,FINSEQ_1:2,TARSKI:def 2;
per cases  by A6;
suppose A7: m = ( 0 );

H = ( ( succ (( tree_of_subformulae F ),t) ) . ( m + 1 ) ) by A1,TREES_9:40
.= ( the_left_argument_of G ) by A5,A3,A7,FINSEQ_1:44;
hence thesis by A7;
end;
suppose A8: m = 1;

H = ( ( succ (( tree_of_subformulae F ),t) ) . ( m + 1 ) ) by A1,TREES_9:40
.= ( the_right_argument_of G ) by A5,A3,A8,FINSEQ_1:44;
hence thesis by A8;
end;
end;
