environ
vocabularies NUMBERS,REAL_1,SUBSET_1,NAT_1,XBOOLE_0,XXREAL_0,FINSET_1,TARSKI,CARD_1,ARYTM_3,XREAL_0,ORDINAL1,ARYTM_1,SEQ_1,FUNCT_1,FUNCOP_1,VALUED_1,RELAT_1,SEQ_2,ORDINAL2,COMPLEX1,LIMFUNC1,FUNCT_2,INT_1,POWER,NEWTON,ASYMPT_0;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,FUNCT_1,FUNCT_2,INT_1,NAT_1,VALUED_1,SEQ_1,SEQ_2,NEWTON,POWER,FUNCOP_1,XXREAL_2,FINSET_1,LIMFUNC1,XXREAL_0,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB19,CKB20,CKB24,CKB25,CKB26,CKB27,CKB28,CKB31,CKB38,CKB53,CKB63,CKB73,CKB74,CKB75,CKB77,CKB78,CKB79,CKB84,CKB85;
definitions TARSKI,FUNCT_1,VALUED_1,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB28,CKB31,CKB38,CKB53,CKB63,CKB73,CKB74,CKB75,CKB77,CKB78,CKB79,CKB84,CKB85;
theorems TARSKI,FUNCT_2,INT_1,NAT_1,SEQ_1,SEQ_2,ABSVALUE,LIMFUNC1,POWER,PRE_FF,XREAL_0,XBOOLE_0,XCMPLX_0,XCMPLX_1,FUNCOP_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,XXREAL_2,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB28,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86;
schemes FUNCT_2,FINSEQ_1,NAT_1,CKB1,CKB2,CKB3;
registrations XBOOLE_0,ORDINAL1,RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,POWER,XXREAL_2,FUNCT_1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB16,CKB21,CKB22,CKB23,CKB29,CKB30;
constructors REAL_1,NAT_1,SEQ_2,LIMFUNC1,NEWTON,POWER,SEQ_1,VALUED_1,PARTFUN1,XXREAL_2,RELSET_1,FUNCOP_1,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB19,CKB20,CKB24,CKB25,CKB26,CKB27,CKB28,CKB31,CKB38,CKB53,CKB63,CKB73,CKB74,CKB75,CKB77,CKB78,CKB79,CKB84,CKB85;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve c for Real;
reserve d for Real;
reserve n for (Element of ( NAT ));
reserve N for (Element of ( NAT ));
reserve N1 for (Element of ( NAT ));
reserve N2 for (Element of ( NAT ));
reserve N3 for (Element of ( NAT ));
reserve x for set;
theorem
(for f,g being  eventually-nonnegative Real_Sequence holds ( max (( Big_Oh f ),( Big_Oh g )) ) = ( Big_Oh ( max (f,g) ) ))
proof
let f being  eventually-nonnegative Real_Sequence,g being  eventually-nonnegative Real_Sequence;
now
let x;
hereby
assume x in ( max (( Big_Oh f ),( Big_Oh g )) );
then consider t being (Element of ( Funcs (( NAT ),( REAL )) )) such that A1: x = t and A2: (ex f9,g9 being (Element of ( Funcs (( NAT ),( REAL )) )) st ((f9 in ( Big_Oh f ) & g9 in ( Big_Oh g )) & (for n being (Element of ( NAT )) holds ( t . n ) = ( max (( f9 . n ),( g9 . n )) ))));
consider f9 being (Element of ( Funcs (( NAT ),( REAL )) )),g9 being (Element of ( Funcs (( NAT ),( REAL )) )) such that A3: f9 in ( Big_Oh f ) and A4: g9 in ( Big_Oh g ) and A5: (for n being (Element of ( NAT )) holds ( t . n ) = ( max (( f9 . n ),( g9 . n )) )) by A2;
consider s being (Element of ( Funcs (( NAT ),( REAL )) )) such that A6: s = g9 and A7: (ex c st (ex N st (c > ( 0 ) & (for n holds (n >= N implies (( s . n ) <= ( c * ( g . n ) ) & ( s . n ) >= ( 0 ))))))) by A4;
consider d,N2 such that A8: d > ( 0 ) and A9: (for n holds (n >= N2 implies (( s . n ) <= ( d * ( g . n ) ) & ( s . n ) >= ( 0 )))) by A7;
consider r being (Element of ( Funcs (( NAT ),( REAL )) )) such that A10: r = f9 and A11: (ex c st (ex N st (c > ( 0 ) & (for n holds (n >= N implies (( r . n ) <= ( c * ( f . n ) ) & ( r . n ) >= ( 0 ))))))) by A3;
consider c,N1 such that A12: c > ( 0 ) and A13: (for n holds (n >= N1 implies (( r . n ) <= ( c * ( f . n ) ) & ( r . n ) >= ( 0 )))) by A11;
set e = ( max (c,d) );
A14: e > ( 0 ) by A12,XXREAL_0:25;
set N = ( max (N1,N2) );
A15: N >= N2 by XXREAL_0:25;
A16: N >= N1 by XXREAL_0:25;
now
let n;
assume A17: n >= N;
then A18: n >= N1 by A16,XXREAL_0:2;
then ( r . n ) <= ( c * ( f . n ) ) by A13;
then ( ( f . n ) * c ) >= ( ( 0 ) * c ) by A13,A18;
then ( f . n ) >= ( 0 ) by A12,XREAL_1:68;
then A19: ( c * ( f . n ) ) <= ( e * ( f . n ) ) by XREAL_1:64,XXREAL_0:25;
A20: n >= N2 by A15,A17,XXREAL_0:2;
then ( s . n ) <= ( d * ( g . n ) ) by A9;
then ( ( g . n ) * d ) >= ( ( 0 ) * d ) by A9,A20;
then ( g . n ) >= ( 0 ) by A8,XREAL_1:68;
then A21: ( d * ( g . n ) ) <= ( e * ( g . n ) ) by XREAL_1:64,XXREAL_0:25;
( s . n ) <= ( d * ( g . n ) ) by A9,A20;
then A22: ( s . n ) <= ( e * ( g . n ) ) by A21,XXREAL_0:2;
( e * ( g . n ) ) <= ( e * ( max (( f . n ),( g . n )) ) ) by A14,XREAL_1:64,XXREAL_0:25;
then A23: ( s . n ) <= ( e * ( max (( f . n ),( g . n )) ) ) by A22,XXREAL_0:2;
( r . n ) <= ( c * ( f . n ) ) by A13,A18;
then A24: ( r . n ) <= ( e * ( f . n ) ) by A19,XXREAL_0:2;
( e * ( f . n ) ) <= ( e * ( max (( f . n ),( g . n )) ) ) by A14,XREAL_1:64,XXREAL_0:25;
then ( r . n ) <= ( e * ( max (( f . n ),( g . n )) ) ) by A24,XXREAL_0:2;
then ( max (( r . n ),( s . n )) ) <= ( e * ( max (( f . n ),( g . n )) ) ) by A23,XXREAL_0:28;
then ( max (( r . n ),( s . n )) ) <= ( e * ( ( max (f,g) ) . n ) ) by CKB28:def 1;
hence ( t . n ) <= ( e * ( ( max (f,g) ) . n ) ) by A5,A10,A6;
(( max (( f9 . n ),( g9 . n )) ) >= ( f9 . n ) & ( f9 . n ) >= ( 0 )) by A10,A13,A18,XXREAL_0:25;
hence ( t . n ) >= ( 0 ) by A5;
end;
hence x in ( Big_Oh ( max (f,g) ) ) by A1,A14;
end;
assume x in ( Big_Oh ( max (f,g) ) );
then consider t being (Element of ( Funcs (( NAT ),( REAL )) )) such that A25: x = t and A26: (ex c st (ex N st (c > ( 0 ) & (for n holds (n >= N implies (( t . n ) <= ( c * ( ( max (f,g) ) . n ) ) & ( t . n ) >= ( 0 )))))));
consider c,N3 such that A27: c > ( 0 ) and A28: (for n holds (n >= N3 implies (( t . n ) <= ( c * ( ( max (f,g) ) . n ) ) & ( t . n ) >= ( 0 )))) by A26;
consider N1 such that A29: (for n holds (n >= N1 implies ( f . n ) >= ( 0 ))) by CKB11:def 1;
consider N2 such that A30: (for n holds (n >= N2 implies ( g . n ) >= ( 0 ))) by CKB11:def 1;
set N = ( max (N3,( max (N1,N2) )) );
defpred P[ (Element of ( NAT )),Real ]
 means
(((( f . $1 ) >= ( g . $1 ) or $1 < N) implies $2 = ( t . $1 )) & ((( f . $1 ) < ( g . $1 ) & $1 >= N) implies $2 = ( 0 )));
defpred Q[ (Element of ( NAT )),Real ]
 means
(((( f . $1 ) >= ( g . $1 ) & $1 >= N) implies $2 = ( 0 )) & ((( f . $1 ) < ( g . $1 ) or $1 < N) implies $2 = ( t . $1 )));
A31: (for x being (Element of ( NAT )) holds (ex y being (Element of ( REAL )) st P[ x,y ]))
proof
let n;
per cases ;
suppose ( f . n ) >= ( g . n );

hence thesis;
end;
suppose A32: ( f . n ) < ( g . n );

thus thesis
proof
per cases ;
suppose n < N;

hence thesis;
end;
suppose n >= N;

hence thesis by A32;
end;
end;

end;
end;
consider f9 being (Function of ( NAT ),( REAL )) such that A33: (for x being (Element of ( NAT )) holds P[ x,( f9 . x ) ]) from FUNCT_2:sch 3(A31);
A34: (for x being (Element of ( NAT )) holds (ex y being (Element of ( REAL )) st Q[ x,y ]))
proof
let n;
per cases ;
suppose A35: ( f . n ) >= ( g . n );

thus thesis
proof
per cases ;
suppose n < N;

hence thesis;
end;
suppose n >= N;

hence thesis by A35;
end;
end;

end;
suppose ( f . n ) < ( g . n );

hence thesis;
end;
end;
consider g9 being (Function of ( NAT ),( REAL )) such that A36: (for x being (Element of ( NAT )) holds Q[ x,( g9 . x ) ]) from FUNCT_2:sch 3(A34);
A37: N >= N3 by XXREAL_0:25;
A38:now
let n being (Element of ( NAT ));
per cases ;
suppose n < N;

then (( f9 . n ) = ( t . n ) & ( g9 . n ) = ( t . n )) by A33,A36;
hence ( t . n ) = ( max (( f9 . n ),( g9 . n )) );
end;
suppose A39: n >= N;

then A40: n >= N3 by A37,XXREAL_0:2;
thus ( t . n ) = ( max (( f9 . n ),( g9 . n )) )
proof
per cases ;
suppose A41: ( f . n ) >= ( g . n );

A42: ( t . n ) >= ( 0 ) by A28,A40;
(( f9 . n ) = ( t . n ) & ( g9 . n ) = ( 0 )) by A33,A36,A39,A41;
hence thesis by A42,XXREAL_0:def 10;
end;
suppose A43: ( f . n ) < ( g . n );

A44: ( t . n ) >= ( 0 ) by A28,A40;
(( f9 . n ) = ( 0 ) & ( g9 . n ) = ( t . n )) by A33,A36,A39,A43;
hence thesis by A44,XXREAL_0:def 10;
end;
end;

end;
end;
A45: g9 is (Element of ( Funcs (( NAT ),( REAL )) )) by FUNCT_2:8;
A46: N >= ( max (N1,N2) ) by XXREAL_0:25;
( max (N1,N2) ) >= N2 by XXREAL_0:25;
then A47: N >= N2 by A46,XXREAL_0:2;
now
let n;
assume A48: n >= N;
then n >= N3 by A37,XXREAL_0:2;
then A49: (( t . n ) >= ( 0 ) & ( t . n ) <= ( c * ( ( max (f,g) ) . n ) )) by A28;
n >= N2 by A47,A48,XXREAL_0:2;
then ( g . n ) >= ( 0 ) by A30;
then A50: ( ( 0 ) * ( g . n ) ) <= ( c * ( g . n ) ) by A27;
per cases ;
suppose ( f . n ) >= ( g . n );

hence (( g9 . n ) <= ( c * ( g . n ) ) & ( g9 . n ) >= ( 0 )) by A36,A48,A50;
end;
suppose A51: ( f . n ) < ( g . n );

then ( max (( f . n ),( g . n )) ) = ( g . n ) by XXREAL_0:def 10;
then ( ( max (f,g) ) . n ) = ( g . n ) by CKB28:def 1;
hence (( g9 . n ) <= ( c * ( g . n ) ) & ( g9 . n ) >= ( 0 )) by A36,A49,A51;
end;
end;
then A52: g9 in ( Big_Oh g ) by A27,A45;
A53: f9 is (Element of ( Funcs (( NAT ),( REAL )) )) by FUNCT_2:8;
( max (N1,N2) ) >= N1 by XXREAL_0:25;
then A54: N >= N1 by A46,XXREAL_0:2;
now
let n;
assume A55: n >= N;
then n >= N3 by A37,XXREAL_0:2;
then A56: (( t . n ) >= ( 0 ) & ( t . n ) <= ( c * ( ( max (f,g) ) . n ) )) by A28;
n >= N1 by A54,A55,XXREAL_0:2;
then ( f . n ) >= ( 0 ) by A29;
then A57: ( ( 0 ) * ( f . n ) ) <= ( c * ( f . n ) ) by A27;
per cases ;
suppose A58: ( f . n ) >= ( g . n );

then ( max (( f . n ),( g . n )) ) = ( f . n ) by XXREAL_0:def 10;
then ( ( max (f,g) ) . n ) = ( f . n ) by CKB28:def 1;
hence (( f9 . n ) <= ( c * ( f . n ) ) & ( f9 . n ) >= ( 0 )) by A33,A56,A58;
end;
suppose ( f . n ) < ( g . n );

hence (( f9 . n ) <= ( c * ( f . n ) ) & ( f9 . n ) >= ( 0 )) by A33,A55,A57;
end;
end;
then f9 in ( Big_Oh f ) by A27,A53;
hence x in ( max (( Big_Oh f ),( Big_Oh g )) ) by A25,A53,A45,A52,A38;
end;
hence thesis by TARSKI:1;
end;
