environ
vocabularies XBOOLE_0,FUNCT_1,TARSKI,ZFMISC_1,RELAT_1,FUNCOP_1,SUBSET_1,PARTFUN1,FUNCT_2,ORDINAL1,FUNCT_4;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,BINOP_1,PARTFUN1,FUNCOP_1,CKB11,CKB43;
definitions TARSKI,FUNCT_2,PARTFUN1,XBOOLE_0,BINOP_1,FUNCOP_1,FUNCT_1,CKB11,CKB43;
theorems TARSKI,FUNCT_1,FUNCT_2,GRFUNC_1,PARTFUN1,FUNCOP_1,ZFMISC_1,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,ENUMSET1,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56;
schemes FUNCT_1,PARTFUN1,XBOOLE_0;
registrations XBOOLE_0,RELAT_1,FUNCT_1,FUNCOP_1,RELSET_1,ZFMISC_1;
constructors PARTFUN1,BINOP_1,FUNCOP_1,RELSET_1,ORDINAL1,CKB11,CKB43;
requirements BOOLE,SUBSET;
begin
reserve x for set;
reserve x9 for set;
reserve x1 for set;
reserve x19 for set;
reserve y for set;
reserve y9 for set;
reserve y1 for set;
reserve y19 for set;
reserve z for set;
reserve z1 for set;
reserve z2 for set;
reserve f for Function;
reserve g for Function;
definition
let f;
let g;
func |:f,g :| -> Function
means
:Def3: ((for z holds (z in ( dom it ) iff (ex x st (ex y st (ex x9 st (ex y9 st ((z = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g )))))))) & (for x holds (for y holds (for x9 holds (for y9 holds (([ x,y ] in ( dom f ) & [ x9,y9 ] in ( dom g )) implies ( it . ([ x,x9 ],[ y,y9 ]) ) = [ ( f . (x,y) ),( g . (x9,y9) ) ]))))));
existence
proof
defpred P[ set,set ]
 means
(ex x st (ex y st (ex x9 st (ex y9 st ($1 = [ [ x,x9 ],[ y,y9 ] ] & $2 = [ ( f . [ x,y ] ),( g . [ x9,y9 ] ) ])))));
defpred P[ set ]
 means
(ex y st [ $1,y ] in ( dom f ));
consider D1 being set such that A1: (x in D1 iff (x in ( union ( union ( dom f ) ) ) & P[ x ])) from XBOOLE_0:sch 1;
defpred P[ set ]
 means
(ex x st [ x,$1 ] in ( dom f ));
consider D2 being set such that A2: (y in D2 iff (y in ( union ( union ( dom f ) ) ) & P[ y ])) from XBOOLE_0:sch 1;
defpred P[ set ]
 means
(ex y st [ $1,y ] in ( dom g ));
consider D19 being set such that A3: (x in D19 iff (x in ( union ( union ( dom g ) ) ) & P[ x ])) from XBOOLE_0:sch 1;
defpred P[ set ]
 means
(ex x st [ x,$1 ] in ( dom g ));
consider D29 being set such that A4: (y in D29 iff (y in ( union ( union ( dom g ) ) ) & P[ y ])) from XBOOLE_0:sch 1;
defpred P[ set ]
 means
(ex x st (ex y st (ex x9 st (ex y9 st (($1 = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g ))))));
consider D being set such that A5: (z in D iff (z in [: [: D1,D19 :],[: D2,D29 :] :] & P[ z ])) from XBOOLE_0:sch 1;
A6: (for z holds (for z1 holds (for z2 holds (((z in D & P[ z,z1 ]) & P[ z,z2 ]) implies z1 = z2))))
proof
let z;
let z1;
let z2;
assume that
z in D;
given x,y,x9,y9 such that
A7: z = [ [ x,x9 ],[ y,y9 ] ]
and
A8: z1 = [ ( f . [ x,y ] ),( g . [ x9,y9 ] ) ];

given x1,y1,x19,y19 such that
A9: z = [ [ x1,x19 ],[ y1,y19 ] ]
and
A10: z2 = [ ( f . [ x1,y1 ] ),( g . [ x19,y19 ] ) ];

A11: x9 = x19 by A7,A9,CKB1:1;
(x = x1 & y = y1) by A7,A9,CKB1:1;
hence thesis by A7,A8,A9,A10,A11,CKB1:1;
end;
A12: (for z holds (z in D implies (ex z1 st P[ z,z1 ])))
proof
let z;
assume z in D;
then consider x,y,x9,y9 such that A13: z = [ [ x,x9 ],[ y,y9 ] ] and [ x,y ] in ( dom f ) and [ x9,y9 ] in ( dom g ) by A5;
take [ ( f . [ x,y ] ),( g . [ x9,y9 ] ) ];
thus thesis by A13;
end;
consider h being Function such that A14: ( dom h ) = D and A15: (for z holds (z in D implies P[ z,( h . z ) ])) from FUNCT_1:sch 2(A6,A12);
take h;
thus A16: (for z holds (z in ( dom h ) iff (ex x st (ex y st (ex x9 st (ex y9 st ((z = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g ))))))))
proof
let z;
thus (z in ( dom h ) implies (ex x st (ex y st (ex x9 st (ex y9 st ((z = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g ))))))) by A5,A14;
given x,y,x9,y9 such that
A17: z = [ [ x,x9 ],[ y,y9 ] ]
and
A18: [ x,y ] in ( dom f )
and
A19: [ x9,y9 ] in ( dom g );

y9 in ( union ( union ( dom g ) ) ) by A19,ZFMISC_1:134;
then A20: y9 in D29 by A4,A19;
y in ( union ( union ( dom f ) ) ) by A18,ZFMISC_1:134;
then y in D2 by A2,A18;
then A21: [ y,y9 ] in [: D2,D29 :] by A20,ZFMISC_1:87;
x9 in ( union ( union ( dom g ) ) ) by A19,ZFMISC_1:134;
then A22: x9 in D19 by A3,A19;
x in ( union ( union ( dom f ) ) ) by A18,ZFMISC_1:134;
then x in D1 by A1,A18;
then [ x,x9 ] in [: D1,D19 :] by A22,ZFMISC_1:87;
then z in [: [: D1,D19 :],[: D2,D29 :] :] by A17,A21,ZFMISC_1:87;
hence thesis by A5,A14,A17,A18,A19;
end;

let x;
let y;
let x9;
let y9;
assume ([ x,y ] in ( dom f ) & [ x9,y9 ] in ( dom g ));
then [ [ x,x9 ],[ y,y9 ] ] in D by A14,A16;
then consider x1,y1,x19,y19 such that A23: [ [ x,x9 ],[ y,y9 ] ] = [ [ x1,x19 ],[ y1,y19 ] ] and A24: ( h . [ [ x,x9 ],[ y,y9 ] ] ) = [ ( f . [ x1,y1 ] ),( g . [ x19,y19 ] ) ] by A15;
A25: x9 = x19 by A23,CKB1:1;
(x = x1 & y = y1) by A23,CKB1:1;
hence thesis by A23,A24,A25,CKB1:1;
end;
uniqueness
proof
let h1 being Function,h2 being Function;
assume that
A26: (for z holds (z in ( dom h1 ) iff (ex x st (ex y st (ex x9 st (ex y9 st ((z = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g ))))))))
and
A27: (for x holds (for y holds (for x9 holds (for y9 holds (([ x,y ] in ( dom f ) & [ x9,y9 ] in ( dom g )) implies ( h1 . ([ x,x9 ],[ y,y9 ]) ) = [ ( f . (x,y) ),( g . (x9,y9) ) ])))))
and
A28: (for z holds (z in ( dom h2 ) iff (ex x st (ex y st (ex x9 st (ex y9 st ((z = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g ))))))))
and
A29: (for x holds (for y holds (for x9 holds (for y9 holds (([ x,y ] in ( dom f ) & [ x9,y9 ] in ( dom g )) implies ( h2 . ([ x,x9 ],[ y,y9 ]) ) = [ ( f . (x,y) ),( g . (x9,y9) ) ])))));
A30: (z in ( dom h1 ) implies ( h1 . z ) = ( h2 . z ))
proof
assume z in ( dom h1 );
then consider x,y,x9,y9 such that A31: z = [ [ x,x9 ],[ y,y9 ] ] and A32: ([ x,y ] in ( dom f ) & [ x9,y9 ] in ( dom g )) by A26;
( h1 . ([ x,x9 ],[ y,y9 ]) ) = [ ( f . (x,y) ),( g . (x9,y9) ) ] by A27,A32
.= ( h2 . ([ x,x9 ],[ y,y9 ]) ) by A29,A32;
hence thesis by A31;
end;
(z in ( dom h1 ) iff z in ( dom h2 ))
proof
(z in ( dom h1 ) iff (ex x st (ex y st (ex x9 st (ex y9 st ((z = [ [ x,x9 ],[ y,y9 ] ] & [ x,y ] in ( dom f )) & [ x9,y9 ] in ( dom g ))))))) by A26;
hence thesis by A28;
end;
then ( dom h1 ) = ( dom h2 ) by TARSKI:1;
hence thesis by A30,FUNCT_1:2;
end;
end;
