environ
vocabularies XBOOLE_0,FUNCT_1,TARSKI,ZFMISC_1,RELAT_1,FUNCOP_1,SUBSET_1,PARTFUN1,FUNCT_2,ORDINAL1,FUNCT_4;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,BINOP_1,PARTFUN1,FUNCOP_1,CKB11,CKB43,CKB57,CKB66;
definitions TARSKI,FUNCT_2,PARTFUN1,XBOOLE_0,BINOP_1,FUNCOP_1,FUNCT_1,CKB11,CKB43,CKB57,CKB66;
theorems TARSKI,FUNCT_1,FUNCT_2,GRFUNC_1,PARTFUN1,FUNCOP_1,ZFMISC_1,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,ENUMSET1,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB68,CKB69,CKB70;
schemes FUNCT_1,PARTFUN1,XBOOLE_0;
registrations XBOOLE_0,RELAT_1,FUNCT_1,FUNCOP_1,RELSET_1,ZFMISC_1,CKB67;
constructors PARTFUN1,BINOP_1,FUNCOP_1,RELSET_1,ORDINAL1,CKB11,CKB43,CKB57,CKB66;
requirements BOOLE,SUBSET;
begin
reserve x for set;
reserve x1 for set;
reserve x2 for set;
reserve y for set;
theorem
( (x1,x2) --> (y,y) ) = ( { x1,x2 } --> y )
proof
set F = ( (x1,x2) --> (y,y) );
set f = ( { x1 } --> y );
set g = ( { x2 } --> y );
set F9 = ( { x1,x2 } --> y );
now
thus A1: (( dom F ) = { x1,x2 } & ( dom F9 ) = { x1,x2 }) by CKB68:1,FUNCOP_1:13;
let x;
assume that
A2: x in { x1,x2 };
now
per cases  by A1,A2,CKB14:1;
suppose A3: (x in ( dom f ) & (not x in ( dom g )));

then ( F . x ) = ( f . x ) by CKB13:1;
hence (( F . x ) = y & ( F9 . x ) = y) by A2,A3,FUNCOP_1:7;
end;
suppose A4: x in ( dom g );

then ( F . x ) = ( g . x ) by CKB15:1;
hence (( F . x ) = y & ( F9 . x ) = y) by A2,A4,FUNCOP_1:7;
end;
end;
hence ( F . x ) = ( F9 . x );
end;
hence thesis by FUNCT_1:2;
end;
