environ
vocabularies NUMBERS,PRE_TOPC,SUBSET_1,SETFAM_1,PCOMPS_1,CARD_1,FINSET_1,T_0TOPSP,RELAT_1,XBOOLE_0,FUNCT_1,RCOMP_1,ORDINAL2,TOPS_2,WAYBEL23,TARSKI,RLVECT_3,STRUCT_0,ZFMISC_1,XXREAL_0,ARYTM_3,METRIC_1,CARD_5,NAGATA_1,TOPREAL7,CARD_2,MCART_1,ORDINAL1,WEIERSTR,TOPMETR,XREAL_0,ARYTM_1,COMPLEX1,XXREAL_1,TOPGEN_4,NAT_1,NEWTON,CARD_3,NATTRA_1,TOPGEN_1,TOPS_1,REAL_1,FUNCOP_1,EUCLID,FINSEQ_2,FINSEQ_1,CONNSP_1,METRIZTS,KURATO_2;
notations BINOP_1,TOPMETR,CARD_1,CANTOR_1,COMPLEX1,FINSET_1,TARSKI,XBOOLE_0,RELAT_1,SUBSET_1,ORDINAL1,NUMBERS,ZFMISC_1,XREAL_0,REAL_1,DOMAIN_1,METRIC_1,PCOMPS_1,CARD_3,KURATO_0,KURATO_2,WAYBEL23,TOPGEN_1,FUNCOP_1,XCMPLX_0,TOPS_1,CARD_2,NEWTON,BORSUK_1,NAGATA_1,TEX_2,TOPGEN_4,RCOMP_1,WEIERSTR,TOPREAL7,ORDERS_4,XXREAL_0,FUNCT_1,RELSET_1,FUNCT_2,FUNCT_3,NAT_1,FINSEQ_1,SETFAM_1,STRUCT_0,PRE_TOPC,CONNSP_1,TOPS_2,BORSUK_3,EUCLID,FINSEQ_2,CKB1;
definitions BINOP_1,CARD_3,METRIC_1,PCOMPS_1,PRE_TOPC,SUBSET_1,STRUCT_0,TARSKI,TOPS_2,XBOOLE_0,CKB1;
theorems ABSVALUE,BORSUK_1,BORSUK_5,CANTOR_1,CARD_1,CARD_2,CARD_3,CARD_4,COMPL_SP,CONNSP_1,FUNCOP_1,FUNCT_1,FUNCT_2,FUNCT_3,HAUSDORF,JGRAPH_2,JORDAN1K,MCART_1,METRIC_1,NAGATA_1,NAGATA_2,NEWTON,PARTIT1,PCOMPS_1,PCOMPS_2,PREPOWER,PRE_TOPC,PROB_1,SETFAM_1,SUBSET_1,TARSKI,TEX_2,TMAP_1,TOPGEN_1,TOPGEN_2,TOPGEN_4,TOPMETR,TOPREAL7,TOPS_1,TOPS_2,TSEP_1,TSP_1,WAYBEL23,WAYBEL29,XBOOLE_0,XBOOLE_1,XREAL_0,XREAL_1,XXREAL_0,XXREAL_1,YELLOW12,YELLOW_9,ZFMISC_1,T_0TOPSP,TOPGRP_1,RELAT_1,ORDERS_4,NUMBERS,TOPREAL6,TOPREALA,EUCLID,ORDINAL1,FINSEQ_2,YELLOW14,TOPS_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB15,CKB16,CKB18,CKB19,CKB22,CKB23,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41;
schemes BORSUK_2,CLASSES1,FRAENKEL,FUNCT_2,LMOD_7,NAT_1;
registrations TOPMETR,PRE_TOPC,PCOMPS_1,XREAL_0,SUBSET_1,STRUCT_0,TOPS_1,METRIC_1,XXREAL_0,YELLOW13,CARD_1,XBOOLE_0,FINSET_1,FUNCT_1,ORDINAL1,COMPTS_1,RELAT_1,XCMPLX_0,CARD_LAR,BORSUK_1,TOPGEN_4,MEMBERED,TOPREAL7,BORSUK_3,EUCLID,RELSET_1,KURATO_2,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB17,CKB20,CKB21,CKB24,CKB25;
constructors REAL_1,KURATO_2,CANTOR_1,TOPGEN_4,WAYBEL23,TOPGEN_1,TOPS_1,FUNCT_3,TOPREAL9,CARD_2,NEWTON,CARD_5,NAGATA_1,TEX_2,TSP_1,CONNSP_1,RCOMP_1,WEIERSTR,TOPREAL7,ORDERS_4,TOPS_2,BORSUK_3,FUNCSDOM,YELLOW13,YELLOW_2,KURATO_0,CKB1;
requirements ARITHM,BOOLE,NUMERALS,REAL,SUBSET;
begin
reserve T for TopSpace;
reserve A for (Subset of T);
reserve B for (Subset of T);
reserve G for (Subset-Family of T);
reserve TM for  metrizable TopSpace;
reserve Fm for (Subset-Family of TM);
reserve Gm for (Subset-Family of TM);
reserve iC for  infinite Cardinal;
theorem
Th23: (for B being (Basis of TM) holds ((for Fm holds ((Fm is  open & Fm is (Cover of TM)) implies (ex Gm st ((Gm c= Fm & Gm is (Cover of TM)) & ( card Gm ) c= iC)))) implies (ex underB being (Basis of TM) st (underB c= B & ( card underB ) c= iC))))
proof
let B being (Basis of TM);
assume that
A1: (for F being (Subset-Family of TM) holds ((F is  open & F is (Cover of TM)) implies (ex G being (Subset-Family of TM) st ((G c= F & G is (Cover of TM)) & ( card G ) c= iC))));
per cases ;
suppose TM is  empty;

then ( weight TM ) = ( 0 );
then consider underB being (Basis of TM) such that A2: ( card underB ) = ( 0 ) by WAYBEL23:74;
take underB;
underB = ( {} ) by A2;
hence thesis by XBOOLE_1:2;
end;
suppose A3: TM is non  empty;

set TOP = (the topology of TM);
set cT = (the carrier of TM);
consider metr being (Function of [: cT,cT :],( REAL )) such that A4: metr is_metric_of cT and A5: ( Family_open_set ( SpaceMetr (cT,metr) ) ) = TOP by PCOMPS_1:def 8;
reconsider Tm = ( SpaceMetr (cT,metr) ) as non  empty MetrSpace by A3,A4,PCOMPS_1:36;
defpred P[ set,set ]
 means
(for n being Nat holds ($1 = n implies (ex G being  open (Subset-Family of TM) st (((G c= { U where U is (Subset of TM): (U in B & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) } & G is (Cover of TM)) & ( card G ) c= iC) & $2 = G))));
A6: B c= TOP by TOPS_2:64;
A7: (for x being set holds (x in ( NAT ) implies (ex y being set st P[ x,y ])))
proof
let x being set;
assume x in ( NAT );
then reconsider n = x as Nat;
set F = { U where U is (Subset of TM): (U in B & (ex p being (Element of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) };
A8: F c= TOP
proof
let f being set;
assume f in F;
then (ex U being (Subset of TM) st ((f = U & U in B) & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))));
hence thesis by A6;
end;
then reconsider F as (Subset-Family of TM) by XBOOLE_1:1;
reconsider F as  open (Subset-Family of TM) by A8,TOPS_2:11;
cT c= ( union F )
proof
let y being set;
assume A9: y in cT;
then reconsider p = y as (Point of TM);
reconsider q = y as (Element of Tm) by A3,A4,A9,PCOMPS_2:4;
(( 2 |^ n ) > ( 0 ) & ( dist (q,q) ) = ( 0 )) by METRIC_1:1,NEWTON:83;
then A10: q in ( Ball (q,( 1 / ( 2 |^ n ) )) ) by METRIC_1:11;
reconsider BALL = ( Ball (q,( 1 / ( 2 |^ n ) )) ) as (Subset of TM) by A3,A4,PCOMPS_2:4;
BALL in ( Family_open_set Tm ) by PCOMPS_1:29;
then BALL is  open by A5,PRE_TOPC:def 2;
then consider U being (Subset of TM) such that A11: U in B and A12: p in U and A13: U c= BALL by A10,YELLOW_9:31;
U in F by A11,A13;
hence thesis by A12,TARSKI:def 4;
end;
then F is (Cover of TM) by SETFAM_1:def 11;
then consider G being (Subset-Family of TM) such that A14: G c= F and A15: (G is (Cover of TM) & ( card G ) c= iC) by A1;
take G;
let m being Nat;
assume A16: x = m;
G is  open by A14,TOPS_2:11;
hence thesis by A14,A15,A16;
end;
consider f being Function such that A17: (( dom f ) = ( NAT ) & (for e being set holds (e in ( NAT ) implies P[ e,( f . e ) ]))) from CLASSES1:sch 1(A7);
A18: ( union ( rng f ) ) c= B
proof
let b being set;
assume b in ( union ( rng f ) );
then consider y being set such that A19: b in y and A20: y in ( rng f ) by TARSKI:def 4;
consider x being set such that A21: x in ( dom f ) and A22: ( f . x ) = y by A20,FUNCT_1:def 3;
reconsider n = x as Nat by A17,A21;
(ex G being  open (Subset-Family of TM) st (((G c= { U where U is (Subset of TM): (U in B & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) } & G is (Cover of TM)) & ( card G ) c= iC) & ( f . n ) = G)) by A17,A21;
then b in { U where U is (Subset of TM): (U in B & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) } by A19,A22;
then (ex U being (Subset of TM) st ((U = b & U in B) & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))));
hence thesis;
end;
then reconsider Urngf = ( union ( rng f ) ) as (Subset-Family of TM) by XBOOLE_1:1;
(for A being (Subset of TM) holds (A is  open implies (for p being (Point of TM) holds (p in A implies (ex a being (Subset of TM) st ((a in Urngf & p in a) & a c= A))))))
proof
let A being (Subset of TM);
assume A is  open;
then A23: A in ( Family_open_set Tm ) by A5,PRE_TOPC:def 2;
let p being (Point of TM);
assume that
A24: p in A;
reconsider p9 = p as (Element of Tm) by A3,A4,PCOMPS_2:4;
consider r being Real such that A25: r > ( 0 ) and A26: ( Ball (p9,r) ) c= A by A23,A24,PCOMPS_1:def 4;
consider n being (Element of ( NAT )) such that A27: ( 1 / ( 2 |^ n ) ) <= ( r / 2 ) by A25,PREPOWER:92;
consider G being  open (Subset-Family of TM) such that A28: G c= { U where U is (Subset of TM): (U in B & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) } and A29: G is (Cover of TM) and ( card G ) c= iC and A30: ( f . n ) = G by A17;
( [#] TM ) = ( union G ) by A29,SETFAM_1:45;
then consider a being set such that A31: p in a and A32: a in G by A3,TARSKI:def 4;
a in { U where U is (Subset of TM): (U in B & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) } by A28,A32;
then consider U being (Subset of TM) such that A33: a = U and U in B and A34: (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ));
take U;
( f . n ) in ( rng f ) by A17,FUNCT_1:def 3;
hence (U in Urngf & p in U) by A30,A31,A32,A33,TARSKI:def 4;
thus U c= A
proof
let u9 being set;
consider pp being (Element of Tm) such that A35: U c= ( Ball (pp,( 1 / ( 2 |^ n ) )) ) by A34;
assume A36: u9 in U;
then reconsider u = u9 as (Element of Tm) by A3,A4,PCOMPS_2:4;
( dist (pp,u) ) < ( 1 / ( 2 |^ n ) ) by A35,A36,METRIC_1:11;
then A37: ( dist (pp,u) ) < ( r / 2 ) by A27,XXREAL_0:2;
( dist (pp,p9) ) < ( 1 / ( 2 |^ n ) ) by A31,A33,A35,METRIC_1:11;
then ( dist (p9,pp) ) < ( r / 2 ) by A27,XXREAL_0:2;
then (( dist (p9,u) ) <= ( ( dist (p9,pp) ) + ( dist (pp,u) ) ) & ( ( dist (p9,pp) ) + ( dist (pp,u) ) ) < ( ( r / 2 ) + ( r / 2 ) )) by A37,METRIC_1:4,XREAL_1:8;
then ( dist (p9,u) ) < ( ( r / 2 ) + ( r / 2 ) ) by XXREAL_0:2;
then u in ( Ball (p9,r) ) by METRIC_1:11;
hence thesis by A26;
end;

end;
then reconsider Urngf as (Basis of TM) by A6,A18,XBOOLE_1:1,YELLOW_9:32;
take Urngf;
(for x being set holds (x in ( dom f ) implies ( card ( f . x ) ) c= iC))
proof
let x being set;
assume x in ( dom f );
then reconsider n = x as (Element of ( NAT )) by A17;
(ex G being  open (Subset-Family of TM) st (((G c= { U where U is (Subset of TM): (U in B & (ex p being (Point of Tm) st U c= ( Ball (p,( 1 / ( 2 |^ n ) )) ))) } & G is (Cover of TM)) & ( card G ) c= iC) & ( f . n ) = G)) by A17;
hence thesis;
end;
then ( card ( Union f ) ) c= ( ( omega ) *` iC ) by A17,CARD_1:47,CARD_2:86;
hence thesis by A18,CKB29:1;
end;
end;
