environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,FUZZY_1,CARD_1,XXREAL_0,FUNCT_1,TARSKI,ARYTM_1,RELAT_1,PARTFUN1,XXREAL_1,INTEGRA1,SEQ_4,MEMBER_1,ARYTM_3,REAL_1,FUNCT_2,ZFMISC_1,FUNCT_3,FUZZY_2,MEASURE5;
notations TARSKI,XBOOLE_0,SUBSET_1,ZFMISC_1,NUMBERS,XXREAL_0,SQUARE_1,REAL_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCT_3,INTEGRA1,SEQ_1,RCOMP_1,SEQ_4,FUZZY_1,MEASURE5,CKB3;
definitions FUZZY_1,CKB3;
theorems TARSKI,FUNCT_1,PARTFUN1,INTEGRA1,INTEGRA2,FUZZY_1,XBOOLE_0,XREAL_1,XXREAL_0,FUNCT_3,FUNCT_2,RELAT_1,MEASURE5,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28;
schemes PARTFUN1;
registrations RELSET_1,NUMBERS,MEMBERED,INTEGRA1,XBOOLE_0,SUBSET_1,VALUED_0,MEASURE5;
constructors REAL_1,SQUARE_1,RFUNCT_1,INTEGRA1,FUZZY_1,SEQ_1,SEQ_4,RELSET_1,CKB3;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve x for set;
reserve y for set;
reserve y1 for set;
reserve y2 for set;
reserve C for non  empty set;
reserve c for (Element of C);
reserve h for (Membership_Func of C);
reserve g for (Membership_Func of C);
definition
let C being non  empty set;
let h being (Membership_Func of C);
let g being (Membership_Func of C);
func h * g -> (Membership_Func of C) means 
:Def2: (for c being (Element of C) holds ( it . c ) = ( ( h . c ) * ( g . c ) ));
existence
proof
defpred P[ set,set ]
 means
$2 = ( ( h . $1 ) * ( g . $1 ) );
A1: (for x holds (for y1 holds (for y2 holds (((x in C & P[ x,y1 ]) & P[ x,y2 ]) implies y1 = y2))));
A2: (for x holds (for y holds ((x in C & P[ x,y ]) implies y in ( REAL ))));
consider IT being (PartFunc of C,( REAL )) such that A3: ((for x holds (x in ( dom IT ) iff (x in C & (ex y st P[ x,y ])))) & (for x holds (x in ( dom IT ) implies P[ x,( IT . x ) ]))) from PARTFUN1:sch 2(A2,A1);
(for x being set holds (x in C implies x in ( dom IT )))
proof
let x being set;
A4: (ex y st y = ( ( h . x ) * ( g . x ) ));
assume x in C;
hence thesis by A3,A4;
end;
then C c= ( dom IT ) by TARSKI:def 3;
then A5: ( dom IT ) = C by XBOOLE_0:def 10;
then A6: (for c being (Element of C) holds ( IT . c ) = ( ( h . c ) * ( g . c ) )) by A3;
A7: ( rng g ) c= [. ( 0 ),1 .] by RELAT_1:def 19;
A8: ( rng h ) c= [. ( 0 ),1 .] by RELAT_1:def 19;
(for y being set holds (y in ( rng IT ) implies y in [. ( 0 ),1 .]))
proof
reconsider A = [. ( 0 ),1 .] as non  empty  closed_interval (Subset of ( REAL )) by MEASURE5:14;
let y being set;
assume y in ( rng IT );
then consider x being (Element of C) such that A9: x in ( dom IT ) and A10: y = ( IT . x ) by PARTFUN1:3;
A11: A = [. ( lower_bound A ),( upper_bound A ) .] by INTEGRA1:4;
then A12: ( 0 ) = ( lower_bound A ) by INTEGRA1:5;
A13: x in C;
then x in ( dom h ) by FUNCT_2:def 1;
then A14: ( h . x ) in ( rng h ) by FUNCT_1:def 3;
then A15: ( 0 ) <= ( h . x ) by A8,A12,INTEGRA2:1;
A16: 1 = ( upper_bound A ) by A11,INTEGRA1:5;
x in ( dom g ) by A13,FUNCT_2:def 1;
then A17: ( g . x ) in ( rng g ) by FUNCT_1:def 3;
then A18: ( g . x ) <= 1 by A7,A16,INTEGRA2:1;
( 0 ) <= ( g . x ) by A7,A12,A17,INTEGRA2:1;
then ( 0 ) <= ( ( h . x ) * ( g . x ) ) by A15,XREAL_1:127;
then A19: ( 0 ) <= ( IT . x ) by A3,A9;
( h . x ) <= 1 by A8,A16,A14,INTEGRA2:1;
then ( ( h . x ) * ( g . x ) ) <= 1 by A15,A18,XREAL_1:160;
then ( IT . x ) <= 1 by A3,A9;
hence thesis by A10,A12,A16,A19,INTEGRA2:1;
end;
then ( rng IT ) c= [. ( 0 ),1 .] by TARSKI:def 3;
then IT is (Membership_Func of C) by A5,FUNCT_2:def 1,RELAT_1:def 19;
hence thesis by A6;
end;
uniqueness
proof
let F being (Membership_Func of C);
let G being (Membership_Func of C);
assume that
A20: (for c being (Element of C) holds ( F . c ) = ( ( h . c ) * ( g . c ) ))
and
A21: (for c being (Element of C) holds ( G . c ) = ( ( h . c ) * ( g . c ) ));
A22: (for c being (Element of C) holds (c in C implies ( F . c ) = ( G . c )))
proof
let c being (Element of C);
( F . c ) = ( ( h . c ) * ( g . c ) ) by A20;
hence thesis by A21;
end;
A23: C = ( dom G ) by FUNCT_2:def 1;
C = ( dom F ) by FUNCT_2:def 1;
hence thesis by A23,A22,PARTFUN1:5;
end;
commutativity;
end;
