environ
vocabularies XBOOLE_0,ROBBINS1,SUBSET_1,ARYTM_3,LATTICES,ROBBINS2;
notations STRUCT_0,LATTICES,ROBBINS1,CKB1;
definitions CKB1;
theorems ROBBINS1,LATTICES,STRUCT_0,CKB1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB68;
registrations LATTICES,ROBBINS1,STRUCT_0,CKB2,CKB3,CKB4,CKB33,CKB66,CKB67;
constructors ROBBINS1,CKB1;
begin
reserve L for  satisfying_DN_1 non  empty ComplLLattStr;
reserve x for (Element of L);
reserve y for (Element of L);
reserve z for (Element of L);
theorem
Th59: (for L being  join-commutative  join-associative non  empty ComplLLattStr holds (L is  Robbins implies L is  satisfying_DN_1))
proof
let L being  join-commutative  join-associative non  empty ComplLLattStr;
assume L is  Robbins;
then reconsider L9 = L as  join-commutative  join-associative  Robbins non  empty ComplLLattStr;
let x being (Element of L);
let y being (Element of L);
let z being (Element of L);
let u being (Element of L);
A1: L9 is  Huntington;
then A2: ( ( z + x ) *' ( z + ( x ` ) ) ) = z by CKB68:1;
A3: ( ( ( ( x + y ) ` ) + z ) *' z ) = ( ( z + ( ( x + y ) ` ) ) *' z )
.= ( z *' ( z + ( ( x + y ) ` ) ) )
.= z by A1,ROBBINS1:21;
A4: ( ( ( ( ( x + y ) ` ) + z ) *' x ) + z ) = ( z + ( ( ( ( x + y ) ` ) + z ) *' x ) )
.= ( ( z + ( ( ( x + y ) ` ) + z ) ) *' ( z + x ) ) by A1,ROBBINS1:31
.= ( ( ( ( ( x + y ) ` ) + z ) + z ) *' ( z + x ) )
.= ( ( ( ( x + y ) ` ) + ( z + z ) ) *' ( z + x ) ) by LATTICES:def 5
.= ( ( ( ( x + y ) ` ) + z ) *' ( z + x ) ) by A1,ROBBINS1:12
.= ( ( ( ( ( ( x ` ) *' ( y ` ) ) ` ) ` ) + z ) *' ( z + x ) ) by A1,ROBBINS1:17
.= ( ( ( ( x ` ) *' ( y ` ) ) + z ) *' ( z + x ) ) by A1,ROBBINS1:3
.= ( ( z + ( ( x ` ) *' ( y ` ) ) ) *' ( z + x ) )
.= ( ( ( z + ( x ` ) ) *' ( z + ( y ` ) ) ) *' ( z + x ) ) by A1,ROBBINS1:31
.= ( ( z + x ) *' ( ( z + ( x ` ) ) *' ( z + ( y ` ) ) ) )
.= ( ( z + x ) *' ( ( ( x ` ) + z ) *' ( z + ( y ` ) ) ) )
.= ( ( z + x ) *' ( ( ( x ` ) + z ) *' ( ( y ` ) + z ) ) )
.= ( ( ( z + x ) *' ( ( x ` ) + z ) ) *' ( ( y ` ) + z ) ) by A1,ROBBINS1:16
.= ( ( ( z + x ) *' ( z + ( x ` ) ) ) *' ( ( y ` ) + z ) )
.= ( z *' ( z + ( y ` ) ) ) by A2
.= z by A1,ROBBINS1:21;
( ( ( ( ( ( x + y ) ` ) + z ) ` ) + ( ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ` ) ) ` ) = ( ( ( ( ( ( ( ( x + y ) ` ) + z ) ` ) ` ) *' ( ( ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ` ) ` ) ) ` ) ` ) by A1,ROBBINS1:17
.= ( ( ( ( ( ( x + y ) ` ) + z ) ` ) ` ) *' ( ( ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ` ) ` ) ) by A1,ROBBINS1:3
.= ( ( ( ( ( ( x + y ) ` ) + z ) ` ) ` ) *' ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ) by A1,ROBBINS1:3
.= ( ( ( ( x + y ) ` ) + z ) *' ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ) by A1,ROBBINS1:3
.= ( ( ( ( ( ( x + y ) ` ) ` ) *' ( z ` ) ) ` ) *' ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ) by A1,ROBBINS1:17
.= ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' ( x + ( ( ( z ` ) + ( ( z + u ) ` ) ) ` ) ) ) by A1,ROBBINS1:3
.= ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' ( x + ( ( ( ( ( z ` ) ` ) *' ( ( ( z + u ) ` ) ` ) ) ` ) ` ) ) ) by A1,ROBBINS1:17
.= ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' ( x + ( ( ( z *' ( ( ( z + u ) ` ) ` ) ) ` ) ` ) ) ) by A1,ROBBINS1:3
.= ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' ( x + ( z *' ( ( ( z + u ) ` ) ` ) ) ) ) by A1,ROBBINS1:3
.= ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' ( x + ( z *' ( z + u ) ) ) ) by A1,ROBBINS1:3
.= ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' ( x + z ) ) by A1,ROBBINS1:21
.= ( ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' x ) + ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' z ) ) by A1,ROBBINS1:30
.= ( ( ( ( ( ( ( x + y ) ` ) ` ) *' ( z ` ) ) ` ) *' x ) + ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' z ) ) by A1,ROBBINS1:3
.= ( ( ( ( ( x + y ) ` ) + z ) *' x ) + ( ( ( ( x + y ) *' ( z ` ) ) ` ) *' z ) ) by A1,ROBBINS1:17
.= ( ( ( ( ( x + y ) ` ) + z ) *' x ) + ( ( ( ( ( ( x + y ) ` ) ` ) *' ( z ` ) ) ` ) *' z ) ) by A1,ROBBINS1:3
.= z by A1,A3,A4,ROBBINS1:17;
hence thesis;
end;
