environ
vocabularies XBOOLE_0,ROBBINS1,SUBSET_1,ARYTM_3,LATTICES,ROBBINS2;
notations STRUCT_0,LATTICES,ROBBINS1,CKB1,CKB74,CKB75;
definitions CKB1,CKB74,CKB75;
theorems ROBBINS1,LATTICES,STRUCT_0,CKB1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB68,CKB69,CKB74,CKB75;
registrations LATTICES,ROBBINS1,STRUCT_0,CKB2,CKB3,CKB4,CKB33,CKB66,CKB67,CKB70,CKB71,CKB72,CKB73,CKB76;
constructors ROBBINS1,CKB1,CKB74,CKB75;
begin
reserve L for  satisfying_DN_1 non  empty ComplLLattStr;
reserve x for (Element of L);
reserve y for (Element of L);
reserve z for (Element of L);
registration
cluster  join-commutative  join-associative  Huntington ->  satisfying_MD_1  satisfying_MD_2 for non  empty non  empty ComplLLattStr;
coherence
proof
let L being non  empty ComplLLattStr;
assume L is  join-commutative  join-associative  Huntington;
then reconsider L9 = L as  join-commutative  join-associative  Huntington non  empty ComplLLattStr;
A1: L9 is  satisfying_MD_2
proof
let x being (Element of L9);
let y being (Element of L9);
let z being (Element of L9);
set Z = ( z + y );
A2: ( Z + ( y ` ) ) = ( z + ( y + ( y ` ) ) ) by LATTICES:def 5
.= ( z + ( Top L9 ) ) by ROBBINS1:def 8
.= ( Top L9 ) by ROBBINS1:19;
( ( ( ( x ` ) + y ) ` ) + ( z + y ) ) = ( ( ( ( x ` ) + ( ( y ` ) ` ) ) ` ) + ( z + y ) ) by ROBBINS1:3
.= ( ( x *' ( y ` ) ) + ( z + y ) ) by ROBBINS1:def 4
.= ( ( Z + x ) *' ( Z + ( y ` ) ) ) by ROBBINS1:31
.= ( Z + x ) by A2,ROBBINS1:14
.= ( y + ( z + x ) ) by LATTICES:def 5;
hence thesis;
end;
L9 is  satisfying_MD_1
proof
let x being (Element of L9);
let y being (Element of L9);
( ( ( ( x ` ) + y ) ` ) + x ) = ( ( ( ( x ` ) + ( ( y ` ) ` ) ) ` ) + x ) by ROBBINS1:3
.= ( ( x *' ( y ` ) ) + x ) by ROBBINS1:def 4
.= x by ROBBINS1:20;
hence thesis;
end;
hence thesis by A1;
end;
end;
