environ
vocabularies NUMBERS,ZFMISC_1,ALGSTR_0,VECTSP_1,RLVECT_1,PRE_POLY,XCMPLX_0,ARYTM_3,FUNCT_1,XXREAL_0,ARYTM_1,CARD_1,XBOOLE_0,SUBSET_1,MCART_1,RELAT_1,PBOOLE,TARSKI,ORDINAL1,LATTICES,POLYNOM1,FINSEQ_1,CARD_3,PARTFUN1,NAT_1,SUPINF_2,POLYNOM7,STRUCT_0,VECTSP_2,CAT_3,BAGORDER,RELAT_2,WELLORD1,FINSET_1,BROUWER,VALUED_0,ORDERS_1,ALGSTR_1,TERMORD;
notations NUMBERS,XCMPLX_0,TARSKI,XBOOLE_0,SUBSET_1,ORDERS_1,RELAT_1,CARD_1,BAGORDER,RELSET_1,FUNCT_1,PARTFUN1,FINSET_1,XXREAL_0,ORDINAL1,NAT_1,ALGSTR_1,PBOOLE,FINSEQ_1,PRE_POLY,STRUCT_0,ALGSTR_0,RLVECT_1,VFUNCT_1,MCART_1,VECTSP_1,VECTSP_2,RELAT_2,POLYNOM1,NAT_D,WELLORD1,POLYNOM7,CKB3,CKB13,CKB14,CKB15,CKB16;
definitions CKB3,CKB13,CKB14,CKB15,CKB16;
theorems TARSKI,FINSEQ_1,FUNCT_1,FUNCT_2,RELAT_1,POLYNOM1,NAT_1,BINOM,RLVECT_1,VECTSP_2,POLYNOM7,POLYNOM2,NAT_2,RELAT_2,CARD_1,CARD_2,MATRLIN,XBOOLE_0,XBOOLE_1,ORDERS_1,MCART_1,BAGORDER,WELLORD1,VECTSP_1,XREAL_1,PARTFUN1,VALUED_0,STRUCT_0,XREAL_0,PRE_POLY,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31;
schemes NAT_1;
registrations XBOOLE_0,ORDINAL1,RELSET_1,FINSET_1,XXREAL_0,XREAL_0,NAT_1,CARD_1,FINSEQ_1,STRUCT_0,VECTSP_1,ALGSTR_1,POLYNOM1,POLYNOM2,POLYNOM7,BAGORDER,VALUED_0,PRE_POLY,VFUNCT_1,FUNCT_2,FUNCT_1,CKB1,CKB2,CKB6,CKB7,CKB11,CKB12;
constructors XXREAL_0,VECTSP_2,ALGSTR_1,TRIANG_1,POLYNOM7,BAGORDER,WELLORD2,RELSET_1,POLYNOM1,BINOP_2,VFUNCT_1,CKB3,CKB13,CKB14,CKB15,CKB16;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
theorem
Th15: (for n being Ordinal holds (for T being  connected (TermOrder of n) holds (for b1,b2 being (bag of n) holds (( min (b1,b2,T) ) = ( min (b2,b1,T) ) & ( max (b1,b2,T) ) = ( max (b2,b1,T) )))))
proof
let n being Ordinal;
let T being  connected (TermOrder of n);
let b1 being (bag of n);
let b2 being (bag of n);
now
per cases ;
case A1: ( min (b1,b2,T) ) = b1;
now
per cases  by A1,CKB15:def 1;
case A2: b1 <= b2,T;
now
per cases ;
case b1 = b2;
hence ( min (b2,b1,T) ) = ( min (b1,b2,T) );
end;
case b1 <> b2;
then (not b2 <= b1,T) by A2,CKB18:1;
hence ( min (b2,b1,T) ) = ( min (b1,b2,T) ) by A1,CKB15:def 1;
end;
end;
hence ( min (b1,b2,T) ) = ( min (b2,b1,T) );
end;
case b1 = b2;
hence ( min (b2,b1,T) ) = ( min (b1,b2,T) );
end;
end;
hence ( min (b1,b2,T) ) = ( min (b2,b1,T) );
end;
case A3: ( min (b1,b2,T) ) <> b1;
A4:now
assume (not b2 <= b1,T);
then b1 <= b2,T by CKB21:1;
hence contradiction by A3,CKB15:def 1;
end;
thus ( min (b1,b2,T) ) = b2 by A3,CKB27:1
.= ( min (b2,b1,T) ) by A4,CKB15:def 1;
end;
end;
hence ( min (b1,b2,T) ) = ( min (b2,b1,T) );
now
per cases ;
case A5: ( max (b1,b2,T) ) = b1;
now
per cases  by A5,CKB16:def 1;
case A6: b2 <= b1,T;
now
per cases ;
case b1 = b2;
hence ( max (b2,b1,T) ) = ( max (b1,b2,T) );
end;
case b1 <> b2;
then (not b1 <= b2,T) by A6,CKB18:1;
hence ( max (b2,b1,T) ) = ( max (b1,b2,T) ) by A5,CKB16:def 1;
end;
end;
hence thesis;
end;
case b1 = b2;
hence ( max (b2,b1,T) ) = ( max (b1,b2,T) );
end;
end;
hence thesis;
end;
case A7: ( max (b1,b2,T) ) <> b1;
now
per cases  by CKB21:1;
case b1 <= b2,T;
hence ( max (b2,b1,T) ) = b2 by CKB16:def 1
.= ( max (b1,b2,T) ) by A7,CKB28:1;
end;
case b2 <= b1,T;
hence ( max (b2,b1,T) ) = ( max (b1,b2,T) ) by A7,CKB16:def 1;
end;
end;
hence ( max (b2,b1,T) ) = ( max (b1,b2,T) );
end;
end;
hence thesis;
end;
