environ
vocabularies PRE_TOPC,SUBSET_1,RCOMP_1,SETFAM_1,TARSKI,FINSET_1,XBOOLE_0,CARD_5,RELAT_1,ZFMISC_1,FUNCT_1,STRUCT_0,ORDINAL2,TOPS_2,FUNCT_4,COMPTS_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_3,SETFAM_1,FINSET_1,DOMAIN_1,FUNCT_4,STRUCT_0,PRE_TOPC,TOPS_2,CKB1,CKB2,CKB3,CKB4,CKB5;
definitions TARSKI,TOPS_2,XBOOLE_0,SUBSET_1,STRUCT_0,PRE_TOPC,CKB1,CKB2,CKB3,CKB5;
theorems TARSKI,SETFAM_1,FUNCT_1,FUNCT_3,ZFMISC_1,ORDERS_1,PRE_TOPC,TOPS_1,TOPS_2,RELAT_1,XBOOLE_0,XBOOLE_1,SUBSET_1,FUNCT_2,STRUCT_0,FUNCT_4,RELSET_1,FINSET_1,CKB1,CKB2,CKB3,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes MCART_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSET_1,STRUCT_0,PRE_TOPC,TOPS_1,CKB6;
constructors SETFAM_1,DOMAIN_1,FUNCT_3,FINSET_1,TOPS_2,FUNCT_4,RELSET_1,CKB1,CKB5;
requirements SUBSET,BOOLE;
begin
reserve T for TopStruct;
reserve P for (Subset of T);
reserve Q for (Subset of T);
theorem
((P is  compact & Q is  compact) implies ( P \/ Q ) is  compact)
proof
assume that
A1: P is  compact
and
A2: Q is  compact;
let F being (Subset-Family of T);
assume that
A3: F is (Cover of ( P \/ Q ))
and
A4: F is  open;
A5: ( P \/ Q ) c= ( union F ) by A3,SETFAM_1:def 11;
Q c= ( P \/ Q ) by XBOOLE_1:7;
then Q c= ( union F ) by A5,XBOOLE_1:1;
then F is (Cover of Q) by SETFAM_1:def 11;
then consider G2 being (Subset-Family of T) such that A6: G2 c= F and A7: G2 is (Cover of Q) and A8: G2 is  finite by A2,A4,CKB5:def 1;
A9: Q c= ( union G2 ) by A7,SETFAM_1:def 11;
P c= ( P \/ Q ) by XBOOLE_1:7;
then P c= ( union F ) by A5,XBOOLE_1:1;
then F is (Cover of P) by SETFAM_1:def 11;
then consider G1 being (Subset-Family of T) such that A10: G1 c= F and A11: G1 is (Cover of P) and A12: G1 is  finite by A1,A4,CKB5:def 1;
reconsider G = ( G1 \/ G2 ) as (Subset-Family of T);
take G;
thus G c= F by A10,A6,XBOOLE_1:8;
P c= ( union G1 ) by A11,SETFAM_1:def 11;
then ( P \/ Q ) c= ( ( union G1 ) \/ ( union G2 ) ) by A9,XBOOLE_1:13;
then ( P \/ Q ) c= ( union ( G1 \/ G2 ) ) by ZFMISC_1:78;
hence G is (Cover of ( P \/ Q )) by SETFAM_1:def 11;
thus thesis by A12,A8;
end;
