environ
vocabularies NUMBERS,SUBSET_1,FUNCT_1,NAT_1,TARSKI,ORDINAL1,FINSET_1,RELAT_1,AFINSQ_1,ARYTM_1,ARYTM_3,FINSEQ_1,XXREAL_0,CARD_1,XBOOLE_0,ORDINAL4,CARD_3,FINSOP_1,FUNCOP_1,BINOP_2,FUNCT_2,XREAL_0,SEQ_1,SERIES_1,VALUED_1,SQUARE_1,COMPLEX1,PARTFUN3,ZFMISC_1,CARD_FIN,REALSET1,CATALAN1,REAL_1,ORDINAL2,SEQ_2,NEWTON,PREPOWER,FUNCT_3,CATALAN2;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,XREAL_0,NUMBERS,RELAT_1,FUNCT_1,REAL_1,NAT_1,FINSET_1,ORDINAL1,XXREAL_0,NAT_D,AFINSQ_1,SEQ_1,VALUED_1,RELSET_1,DOMAIN_1,FUNCT_2,FUNCOP_1,BINOP_1,BINOP_2,RECDEF_1,SERIES_1,PARTFUN3,AFINSQ_2,ZFMISC_1,SQUARE_1,NEWTON,STIRL2_1,CARD_FIN,CATALAN1,SEQ_2,PREPOWER,COMPLEX1,QUIN_1,CKB2;
definitions TARSKI,XBOOLE_0,FUNCT_1,QUIN_1,SQUARE_1,CKB2;
theorems CATALAN1,AFINSQ_1,TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,XBOOLE_1,NAT_1,FUNCT_2,XCMPLX_1,CARD_2,INT_1,ORDINAL1,WELLORD2,CARD_1,BINOP_2,NEWTON,XREAL_1,FUNCOP_1,STIRL2_1,FUNCT_1,CARD_FIN,SERIES_1,SEQ_1,SEQ_2,COMPLEX1,SQUARE_1,ABSVALUE,RSSPACE2,POWER,PREPOWER,WSIERP_1,FIB_NUM,TIETZE,XREAL_0,SERIES_2,XXREAL_0,NAT_D,AFINSQ_2,CKB1,CKB2,CKB3,CKB4,CKB6,CKB7,CKB10,CKB11,CKB12,CKB13,CKB14;
schemes FUNCT_2,NAT_1,XBOOLE_0,STIRL2_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FUNCOP_1,FINSET_1,FRAENKEL,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,BINOP_2,CARD_1,AFINSQ_1,RELSET_1,VALUED_1,VALUED_0,MEMBERED,NEWTON,AFINSQ_2,CKB5,CKB8,CKB9;
constructors QUIN_1,PREPOWER,SERIES_1,PARTFUN3,BINOM,WELLORD2,DOMAIN_1,SETWISEO,REAL_1,NAT_D,YELLOW20,RECDEF_1,BINOP_2,RELSET_1,ORDINAL4,SEQ_1,AFINSQ_1,SQUARE_1,CATALAN1,STIRL2_1,CARD_FIN,AFINSQ_2,ABIAN,SEQ_2,CKB2;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve m for Nat;
reserve n for Nat;
reserve p for (XFinSequence of ( NAT ));
theorem
Th13: ((p is  dominated_by_0 & n <= ( ( len p ) - ( 2 * ( Sum p ) ) )) implies ( p ^ ( n --> 1 ) ) is  dominated_by_0)
proof
set q = ( n --> 1 );
assume that
A1: p is  dominated_by_0
and
A2: n <= ( ( len p ) - ( 2 * ( Sum p ) ) );
(( rng q ) c= { 1 } & { 1 } c= { ( 0 ),1 }) by FUNCOP_1:13,ZFMISC_1:7;
then A3: ( rng q ) c= { ( 0 ),1 } by XBOOLE_1:1;
( rng p ) c= { ( 0 ),1 } by A1,CKB2:def 1;
then ( ( rng p ) \/ ( rng q ) ) c= { ( 0 ),1 } by A3,XBOOLE_1:8;
hence ( rng ( p ^ q ) ) c= { ( 0 ),1 } by AFINSQ_1:26;
let m;
assume that
A4: m <= ( dom ( p ^ q ) );
now
per cases ;
suppose m <= ( dom p );

then ( ( p ^ q ) | m ) = ( p | m ) by AFINSQ_1:58;
hence thesis by A1,CKB3:1;
end;
suppose m > ( dom p );

then reconsider md = ( m - ( dom p ) ) as (Element of ( NAT )) by NAT_1:21;
A5: m = ( ( dom p ) + md );
( Sum ( md --> 1 ) ) = ( md * 1 ) by AFINSQ_2:58;
then A6: ( Sum ( p ^ ( md --> 1 ) ) ) = ( ( Sum p ) + md ) by AFINSQ_2:55;
(( dom q ) = n & ( len q ) = ( dom q )) by FUNCOP_1:13;
then ( dom ( p ^ q ) ) = ( ( len p ) + n ) by AFINSQ_1:def 3;
then ( md + ( dom p ) ) <= ( n + ( dom p ) ) by A4;
then A7: md <= n by XREAL_1:6;
then ( q | md ) = ( md --> 1 ) by CKB6:1;
then ( ( p ^ q ) | m ) = ( p ^ ( md --> 1 ) ) by A5,AFINSQ_1:59;
then ( 2 * ( Sum ( ( p ^ q ) | m ) ) ) = ( ( ( ( 2 * ( Sum p ) ) + m ) - ( dom p ) ) + md ) by A6;
then A8: ( 2 * ( Sum ( ( p ^ q ) | m ) ) ) <= ( ( ( ( 2 * ( Sum p ) ) + m ) - ( dom p ) ) + n ) by A7,XREAL_1:6;
( n - n ) <= ( ( ( len p ) - ( 2 * ( Sum p ) ) ) - n ) by A2,XREAL_1:9;
then ( m - ( ( ( len p ) - ( 2 * ( Sum p ) ) ) - n ) ) <= ( m - ( 0 ) ) by XREAL_1:10;
hence thesis by A8,XXREAL_0:2;
end;
end;
hence thesis;
end;
