environ
vocabularies XBOOLE_0,ORDINAL1,FUNCT_1,SUBSET_1,RELAT_1,TARSKI,ZF_LANG,ZF_MODEL,BVFUNC_2,CARD_1,XBOOLEAN,FUNCT_4,ARYTM_3,ZF_COLLA;
notations TARSKI,XBOOLE_0,SUBSET_1,XCMPLX_0,RELAT_1,FUNCT_1,ZF_LANG,NUMBERS,FUNCT_2,FUNCT_7,ORDINAL1,ZF_MODEL,CKB1;
definitions TARSKI,ORDINAL1,XBOOLE_0,CKB1;
theorems TARSKI,FUNCT_1,ZF_LANG,ZF_MODEL,ORDINAL1,ZFMISC_1,RELAT_1,XBOOLE_0,FUNCT_7,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
schemes TARSKI,CLASSES1,ORDINAL1,XBOOLE_0;
registrations XBOOLE_0,FUNCT_1,ORDINAL1,MEMBERED,ZF_LANG,RELSET_1;
constructors NAT_1,MEMBERED,ZF_MODEL,FUNCT_7,CKB1;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve E for non  empty set;
reserve A for Ordinal;
reserve B for Ordinal;
reserve d for (Element of E);
reserve d1 for (Element of E);
reserve d9 for (Element of E);
theorem
Th6: ((d9 in d & d in ( Collapse (E,A) )) implies (d9 in ( Collapse (E,A) ) & (ex B st (B in A & d9 in ( Collapse (E,B) )))))
proof
assume that
A1: d9 in d
and
A2: d in ( Collapse (E,A) );
d in { d1: (for d holds (d in d1 implies (ex B st (B in A & d in ( Collapse (E,B) ))))) } by A2,CKB2:1;
then (ex d1 st (d = d1 & (for d holds (d in d1 implies (ex B st (B in A & d in ( Collapse (E,B) )))))));
then consider B such that A3: B in A and A4: d9 in ( Collapse (E,B) ) by A1;
B c= A by A3,ORDINAL1:def 2;
then ( Collapse (E,B) ) c= ( Collapse (E,A) ) by CKB5:1;
hence d9 in ( Collapse (E,A) ) by A4;
thus thesis by A3,A4;
end;
