environ
vocabularies PBOOLE,ZFMISC_1,FUNCT_1,RELAT_1,XBOOLE_0,FUNCT_4,FUNCOP_1,TARSKI,FUNCT_2,FINSET_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,FUNCT_1,FUNCT_2,FINSET_1,FUNCT_4,FUNCOP_1,PBOOLE,CKB1,CKB27;
definitions PBOOLE,FUNCOP_1,CKB1,CKB27;
theorems CARD_2,SETFAM_1,FUNCOP_1,FRAENKEL,FUNCT_4,PBOOLE,FINSET_1,TARSKI,ZFMISC_1,XBOOLE_0,XBOOLE_1,PARTFUN1,RELAT_1,FUNCT_1,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45;
schemes PBOOLE;
registrations XBOOLE_0,SUBSET_1,FUNCOP_1,PRE_CIRC,CKB2,CKB28;
constructors FUNCT_4,PBOOLE,FINSET_1,RELSET_1,CKB1,CKB27;
requirements SUBSET,BOOLE;
begin
reserve I for set;
theorem
(for A,X being (ManySortedSet of I) holds (for B being  non-empty (ManySortedSet of I) holds ((X c= ( union ( A \/ B ) ) & (for Y being (ManySortedSet of I) holds (Y in B implies ( Y /\ X ) = ( [[0]] I )))) implies X c= ( union A ))))
proof
let A being (ManySortedSet of I),X being (ManySortedSet of I);
let B being  non-empty (ManySortedSet of I);
assume that
A1: X c= ( union ( A \/ B ) )
and
A2: (for Y being (ManySortedSet of I) holds (Y in B implies ( Y /\ X ) = ( [[0]] I )));
let i being set;
assume A3: i in I;
A4: (for Y9 being set holds (Y9 in ( B . i ) implies Y9 misses ( X . i )))
proof
consider M being (ManySortedSet of I) such that A5: M in B by PBOOLE:134;
let Y9 being set;
assume that
A6: Y9 in ( B . i );
( dom ( M +* ( i .--> Y9 ) ) ) = I by A3,CKB3:1;
then reconsider K = ( M +* ( i .--> Y9 ) ) as (ManySortedSet of I) by PARTFUN1:def 2,RELAT_1:def 18;
A7: ( dom ( i .--> Y9 ) ) = { i } by FUNCOP_1:13;
i in { i } by TARSKI:def 1;
then A8: ( K . i ) = ( ( i .--> Y9 ) . i ) by A7,FUNCT_4:13
.= Y9 by FUNCOP_1:72;
K in B
proof
let j being set;
assume that
A9: j in I;
now
per cases ;
case j = i;
hence thesis by A6,A8;
end;
case j <> i;
then (not j in ( dom ( i .--> Y9 ) )) by A7,TARSKI:def 1;
then ( K . j ) = ( M . j ) by FUNCT_4:11;
hence thesis by A5,A9,PBOOLE:def 1;
end;
end;
hence thesis;
end;
then ( K /\ X ) = ( [[0]] I ) by A2;
then ( ( K /\ X ) . i ) = ( {} ) by PBOOLE:5;
then ( Y9 /\ ( X . i ) ) = ( {} ) by A3,A8,PBOOLE:def 5;
hence thesis by XBOOLE_0:def 7;
end;
( X . i ) c= ( ( union ( A \/ B ) ) . i ) by A1,A3,PBOOLE:def 2;
then ( X . i ) c= ( union ( ( A . i ) \/ ( B . i ) ) ) by A3,CKB29:1;
then ( X . i ) c= ( union ( A . i ) ) by A4,SETFAM_1:42;
hence thesis by A3,CKB27:def 1;
end;
