environ
vocabularies NUMBERS,SIN_COS4,PARTFUN1,SIN_COS,ORDINAL4,REAL_1,ORDINAL1,RCOMP_1,SUBSET_1,FUNCT_1,CARD_1,FDIFF_1,ARYTM_3,SQUARE_1,ARYTM_1,PREPOWER,NEWTON,TARSKI,RELAT_1,VALUED_1,XBOOLE_0,LIMFUNC1,TAYLOR_1,XXREAL_0,NAT_1;
notations TARSKI,SUBSET_1,ORDINAL1,XXREAL_0,RELSET_1,PARTFUN1,PARTFUN2,RCOMP_1,TAYLOR_1,SIN_COS,RFUNCT_1,SQUARE_1,NUMBERS,REAL_1,NAT_1,NEWTON,VALUED_1,SEQ_1,FDIFF_1,PREPOWER,LIMFUNC1,CKB1,CKB2;
definitions SQUARE_1,LIMFUNC1,XCMPLX_0,SIN_COS,VALUED_1,CKB1,CKB2;
theorems FDIFF_2,TAYLOR_1,XBOOLE_1,XCMPLX_1,NAT_1,FDIFF_1,SQUARE_1,FDIFF_7,FDIFF_4,RFUNCT_1,PREPOWER,FDIFF_5,FUNCT_1,NEWTON,SIN_COS,RELAT_1,FDIFF_8,VALUED_1,XXREAL_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12;
registrations RELSET_1,XREAL_0,MEMBERED,RCOMP_1,INT_1,XXREAL_0,NUMBERS,ORDINAL1,XBOOLE_0,VALUED_0;
constructors REAL_1,PARTFUN1,PARTFUN2,NAT_1,LIMFUNC1,RCOMP_1,TAYLOR_1,SIN_COS,FDIFF_1,RFUNCT_1,SQUARE_1,PREPOWER,SEQ_1,VALUED_1,RELSET_1,NEWTON,CKB1,CKB2;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve x for Real;
reserve a for Real;
reserve b for Real;
reserve c for Real;
reserve Z for  open (Subset of ( REAL ));
reserve f1 for (PartFunc of ( REAL ),( REAL ));
reserve f2 for (PartFunc of ( REAL ),( REAL ));
theorem
(((Z c= ( dom ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) ) & f2 = ( #Z 2 )) & (for x holds (x in Z implies ( f1 . x ) = ( a + ( b * x ) )))) implies (( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) is_differentiable_on Z & (for x holds (x in Z implies ( ( ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) `| Z ) . x ) = ( - ( ( ( b + ( ( 2 * c ) * x ) ) * ( ( cos ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) ) / ( ( ( sin ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) ^2 ) ) )))))
proof
assume that
A1: Z c= ( dom ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) )
and
A2: f2 = ( #Z 2 )
and
A3: (for x holds (x in Z implies ( f1 . x ) = ( a + ( b * x ) )));
( dom ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) ) c= ( dom ( f1 + ( c (#) f2 ) ) ) by RELAT_1:25;
then A4: Z c= ( dom ( f1 + ( c (#) f2 ) ) ) by A1,XBOOLE_1:1;
then A5: ( f1 + ( c (#) f2 ) ) is_differentiable_on Z by A2,A3,FDIFF_4:12;
Z c= ( ( dom f1 ) /\ ( dom ( c (#) f2 ) ) ) by A4,VALUED_1:def 1;
then A6: Z c= ( dom ( c (#) f2 ) ) by XBOOLE_1:18;
A7: (for x holds (x in Z implies ( ( sin ) . ( ( f1 + ( c (#) f2 ) ) . x ) ) <> ( 0 )))
proof
let x;
assume x in Z;
then ( ( f1 + ( c (#) f2 ) ) . x ) in ( dom ( cosec ) ) by A1,FUNCT_1:11;
hence thesis by RFUNCT_1:3;
end;
A8: (for x holds (x in Z implies ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) is_differentiable_in x))
proof
let x;
assume A9: x in Z;
then ( ( sin ) . ( ( f1 + ( c (#) f2 ) ) . x ) ) <> ( 0 ) by A7;
then A10: ( cosec ) is_differentiable_in ( ( f1 + ( c (#) f2 ) ) . x ) by CKB4:1;
( f1 + ( c (#) f2 ) ) is_differentiable_in x by A5,A9,FDIFF_1:9;
hence thesis by A10,FDIFF_2:13;
end;
then A11: ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) is_differentiable_on Z by A1,FDIFF_1:9;
(for x holds (x in Z implies ( ( ( ( cosec ) * ( f1 + ( c (#) f2 ) ) ) `| Z ) . x ) = ( - ( ( ( b + ( ( 2 * c ) * x ) ) * ( ( cos ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) ) / ( ( ( sin ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) ^2 ) ) )))
proof
let x;
assume A12: x in Z;
then A13: ( ( f1 + ( c (#) f2 ) ) . x ) = ( ( f1 . x ) + ( ( c (#) f2 ) . x ) ) by A4,VALUED_1:def 1
.= ( ( f1 . x ) + ( c * ( f2 . x ) ) ) by A6,A12,VALUED_1:def 5
.= ( ( a + ( b * x ) ) + ( c * ( f2 . x ) ) ) by A3,A12
.= ( ( a + ( b * x ) ) + ( c * ( x #Z 2 ) ) ) by A2,TAYLOR_1:def 1
.= ( ( a + ( b * x ) ) + ( c * ( x |^ 2 ) ) ) by PREPOWER:36
.= ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) by NEWTON:81;
A14: ( f1 + ( c (#) f2 ) ) is_differentiable_in x by A5,A12,FDIFF_1:9;
A15: ( ( sin ) . ( ( f1 + ( c (#) f2 ) ) . x ) ) <> ( 0 ) by A7,A12;
then ( cosec ) is_differentiable_in ( ( f1 + ( c (#) f2 ) ) . x ) by CKB4:1;
then ( diff (( ( cosec ) * ( f1 + ( c (#) f2 ) ) ),x) ) = ( ( diff (( cosec ),( ( f1 + ( c (#) f2 ) ) . x )) ) * ( diff (( f1 + ( c (#) f2 ) ),x) ) ) by A14,FDIFF_2:13
.= ( ( - ( ( ( cos ) . ( ( f1 + ( c (#) f2 ) ) . x ) ) / ( ( ( sin ) . ( ( f1 + ( c (#) f2 ) ) . x ) ) ^2 ) ) ) * ( diff (( f1 + ( c (#) f2 ) ),x) ) ) by A15,CKB4:1
.= ( ( ( ( f1 + ( c (#) f2 ) ) `| Z ) . x ) * ( - ( ( ( cos ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) / ( ( ( sin ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) ^2 ) ) ) ) by A5,A12,A13,FDIFF_1:def 7
.= ( ( b + ( ( 2 * c ) * x ) ) * ( - ( ( ( cos ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) / ( ( ( sin ) . ( ( a + ( b * x ) ) + ( c * ( x ^2 ) ) ) ) ^2 ) ) ) ) by A2,A3,A4,A12,FDIFF_4:12;
hence thesis by A11,A12,FDIFF_1:def 7;
end;
hence thesis by A1,A8,FDIFF_1:9;
end;
