environ
vocabularies NUMBERS,XBOOLE_0,FINSEQ_1,FINSEQ_6,SUBSET_1,RELAT_1,FINSEQ_4,XXREAL_0,FINSEQ_5,ARYTM_1,ARYTM_3,ORDINAL4,RFINSEQ,PARTFUN1,FUNCT_1,GOBOARD5,PRE_TOPC,EUCLID,CARD_1,PSCOMP_1,TOPREAL1,SPRECT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,FUNCT_1,PARTFUN1,FINSEQ_1,FINSEQ_4,FINSEQ_5,RFINSEQ,FINSEQ_6,NAT_1,NAT_D,PRE_TOPC,EUCLID,TOPREAL1,GOBOARD5,PSCOMP_1,SPRECT_2;
definitions FUNCT_1;
theorems FINSEQ_6,FINSEQ_4,FINSEQ_5,FINSEQ_3,NAT_1,FINSEQ_1,TARSKI,GOBOARD7,RFINSEQ,REVROT_1,SPRECT_2,XBOOLE_0,XREAL_1,XXREAL_0,PARTFUN1,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB9,CKB10,CKB11;
registrations XBOOLE_0,RELSET_1,XREAL_0,FINSEQ_6,STRUCT_0,SPRECT_2,REVROT_1,ORDINAL1,FUNCT_1,FINSEQ_1,CKB8;
constructors XXREAL_0,FINSEQ_4,RFINSEQ,FINSEQ_5,GOBOARD5,PSCOMP_1,SPRECT_2,NAT_D,RELSET_1;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve f for non constant  standard special_circular_sequence;
reserve p1 for (Point of ( TOP-REAL 2 ));
reserve p2 for (Point of ( TOP-REAL 2 ));
reserve p3 for (Point of ( TOP-REAL 2 ));
theorem
Th12: (((((p1 in ( rng f ) & p2 in ( rng f )) & p3 in ( rng f )) & ( p1 .. f ) < ( p2 .. f )) & ( p2 .. f ) < ( p3 .. f )) implies ( p1 .. ( Rotate (f,p3) ) ) < ( p2 .. ( Rotate (f,p3) ) ))
proof
assume that
A1: p1 in ( rng f )
and
A2: p2 in ( rng f )
and
A3: p3 in ( rng f )
and
A4: (( p1 .. f ) < ( p2 .. f ) & ( p2 .. f ) < ( p3 .. f ));
( p1 .. f ) < ( p3 .. f ) by A4,XXREAL_0:2;
then A5: ( p1 .. ( Rotate (f,p3) ) ) = ( ( ( len f ) + ( p1 .. f ) ) - ( p3 .. f ) ) by A1,A3,CKB10:1;
(( p2 .. ( Rotate (f,p3) ) ) = ( ( ( len f ) + ( p2 .. f ) ) - ( p3 .. f ) ) & ( ( len f ) + ( p1 .. f ) ) < ( ( len f ) + ( p2 .. f ) )) by A2,A3,A4,CKB10:1,XREAL_1:6;
hence thesis by A5,XREAL_1:9;
end;
