environ
vocabularies XBOOLE_0,FUNCSDOM,VECTSP_1,CLASSES2,FUNCT_5,MCART_1,STRUCT_0,VECTSP_2,SUPINF_2,ALGSTR_0,SUBSET_1,ARYTM_3,RLVECT_1,RELAT_1,MESFUNC1,FUNCT_1,MSSUBFAM,GRCAT_1,GRAPH_1,CAT_1,MIDSP_1,ORDINAL1,CARD_1,ARYTM_1,BINOP_1,LATTICES,FUNCT_2,ZFMISC_1,MOD_2,UNIALG_1;
notations XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,BINOP_1,PARTFUN1,NUMBERS,FUNCT_2,FUNCT_5,STRUCT_0,ALGSTR_0,ORDINAL1,RLVECT_1,GROUP_1,VECTSP_1,FUNCSDOM,VECTSP_2,CLASSES2,GRCAT_1,FUNCT_3,CKB2,CKB4,CKB7,CKB8,CKB9,CKB10,CKB12,CKB13,CKB15,CKB18,CKB23,CKB24,CKB30,CKB32;
definitions RLVECT_1,STRUCT_0,GRCAT_1,VECTSP_1,ALGSTR_0,CKB2,CKB4,CKB8,CKB9,CKB10,CKB12,CKB13,CKB18,CKB23,CKB30,CKB32;
theorems BINOP_1,CLASSES2,ENUMSET1,GRCAT_1,FUNCT_2,ORDINAL1,VECTSP_1,RLVECT_1,RELAT_1,GROUP_1,FUNCOP_1,FUNCT_1,STRUCT_0,ALGSTR_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB16,CKB18,CKB20,CKB21,CKB23,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37;
schemes FUNCT_2,BINOP_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FUNCT_2,STRUCT_0,VECTSP_1,ALGSTR_1,ALGSTR_0,CLASSES2,GRCAT_1,CKB6,CKB7,CKB14,CKB17,CKB19,CKB22;
constructors ENUMSET1,PARTFUN1,VECTSP_2,GRCAT_1,FUNCOP_1,ALGSTR_1,RELSET_1,CLASSES1,CKB2,CKB4,CKB7,CKB8,CKB9,CKB10,CKB12,CKB13,CKB18,CKB23,CKB24,CKB30,CKB32;
requirements SUBSET,BOOLE,NUMERALS;
begin
reserve R for Ring;
reserve G for (LeftMod of R);
reserve f for LModMorphismStr over R;
theorem
(((( dom ( ID G ) ) = G & ( cod ( ID G ) ) = G) & (for f being  strict (LModMorphism of R) holds (( cod f ) = G implies ( ( ID G ) * f ) = f))) & (for g being  strict (LModMorphism of R) holds (( dom g ) = G implies ( g * ( ID G ) ) = g)))
proof
set i = ( ID G );
thus ( dom i ) = G;
thus ( cod i ) = G;
thus (for f being  strict (LModMorphism of R) holds (( cod f ) = G implies ( i * f ) = f))
proof
let f being  strict (LModMorphism of R);
assume that
A1: ( cod f ) = G;
set H = ( dom f );
reconsider f9 = f as (Morphism of H,G) by A1,CKB18:def 1;
consider m being (Function of H,G) such that A2: f9 = LModMorphismStr (# H,G,m #) by CKB26:1;
(( dom i ) = G & ( ( id G ) * m ) = m) by FUNCT_2:17;
hence thesis by A1,A2,CKB30:def 1;
end;

thus (for g being  strict (LModMorphism of R) holds (( dom g ) = G implies ( g * ( ID G ) ) = g))
proof
let f being  strict (LModMorphism of R);
assume that
A3: ( dom f ) = G;
set H = ( cod f );
reconsider f9 = f as (Morphism of G,H) by A3,CKB18:def 1;
consider m being (Function of G,H) such that A4: f9 = LModMorphismStr (# G,H,m #) by CKB26:1;
(( cod i ) = G & ( m * ( id G ) ) = m) by FUNCT_2:17;
hence thesis by A3,A4,CKB30:def 1;
end;

end;
