environ
vocabularies DIFF_1,ARYTM_3,ARYTM_1,FUNCT_1,SUBSET_1,NUMBERS,RELAT_1,ZFMISC_1,REAL_1,XXREAL_0,SQUARE_1,SIN_COS,VALUED_1,CARD_1,XREAL_0,POWER,ORDINAL1,SIN_COS4,XBOOLE_0,TAYLOR_1,LIMFUNC1,NEWTON;
notations ORDINAL1,XCMPLX_0,XREAL_0,REAL_1,NAT_1,SERIES_1,XXREAL_0,TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,FUNCT_1,PARTFUN1,RELAT_1,VALUED_0,VALUED_1,SEQ_1,FUNCOP_1,NAT_D,NEWTON,FUNCT_2,RELSET_1,SEQFUNC,SQUARE_1,SIN_COS,SIN_COS4,DIFF_1,DIFF_2,FDIFF_9,RFUNCT_1,COMPLEX1,MEMBERED,MEMBER_1,FUNCT_3,TAYLOR_1,POWER,PARTFUN2,LIMFUNC1;
definitions DIFF_1,VALUED_1,DIFF_2,VALUED_2,SIN_COS4,SQUARE_1,SIN_COS,FDIFF_9,XCMPLX_0,RFUNCT_1,FUNCT_1,TAYLOR_1,POWER,NEWTON,XREAL_0,TARSKI,PARTFUN1,XBOOLE_0,VALUED_0,SEQ_2,LIMFUNC1;
theorems XCMPLX_1,NEWTON,RFUNCT_1,ZFMISC_1,VALUED_1,DIFF_1,SIN_COS4,FDIFF_8,XBOOLE_0,DIFF_3,XXREAL_0,SIN_COS5,TAYLOR_1,POWER,SIN_COS,XXREAL_1,XREAL_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20;
schemes NAT_1;
registrations XBOOLE_0,RELAT_1,ORDINAL1,PARTFUN1,NUMBERS,XREAL_0,MEMBERED,VALUED_0,VALUED_1,DIFF_1,FUNCT_2,VALUED_2,RELSET_1,SQUARE_1,SIN_COS,XCMPLX_0,RFUNCT_1,FUNCT_1,TAYLOR_1,NEWTON,SEQ_2,XXREAL_0,POWER,INT_1,RCOMP_1;
constructors PARTFUN1,REAL_1,NAT_1,SEQFUNC,NEWTON,SERIES_1,MEASURE6,NAT_D,PARTFUN3,DIFF_1,SEQ_1,FUNCOP_1,RELSET_1,DIFF_2,VALUED_2,SQUARE_1,SIN_COS,SIN_COS4,FDIFF_9,XCMPLX_0,FUNCT_1,FUNCT_3,XXREAL_0,COMPLEX1,VALUED_1,RFUNCT_1,XREAL_0,PARTFUN2,SEQ_2,SIN_COS5,TAYLOR_1,POWER,RCOMP_1,LIMFUNC1,FDIFF_1,PREPOWER;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve h for Real;
reserve x for Real;
theorem
((( x + ( h / 2 ) ) in ( ( dom ( cosec ) ) /\ ( dom ( sec ) ) ) & ( x - ( h / 2 ) ) in ( ( dom ( cosec ) ) /\ ( dom ( sec ) ) )) implies ( ( cD (( ( cosec ) (#) ( sec ) ),h) ) . x ) = ( - ( 4 * ( ( ( cos ( 2 * x ) ) * ( sin h ) ) / ( ( sin ( ( 2 * x ) + h ) ) * ( sin ( ( 2 * x ) - h ) ) ) ) ) ))
proof
set f = ( ( cosec ) (#) ( sec ) );
assume A1: (( x + ( h / 2 ) ) in ( ( dom ( cosec ) ) /\ ( dom ( sec ) ) ) & ( x - ( h / 2 ) ) in ( ( dom ( cosec ) ) /\ ( dom ( sec ) ) ));
A2: (( x + ( h / 2 ) ) in ( dom ( cosec ) ) & ( x + ( h / 2 ) ) in ( dom ( sec ) )) by A1,XBOOLE_0:def 4;
A3: (( x - ( h / 2 ) ) in ( dom ( cosec ) ) & ( x - ( h / 2 ) ) in ( dom ( sec ) )) by A1,XBOOLE_0:def 4;
A4: (( ( sin ) . ( x + ( h / 2 ) ) ) <> ( 0 ) & ( ( cos ) . ( x + ( h / 2 ) ) ) <> ( 0 )) by A2,RFUNCT_1:3;
A5: (( ( sin ) . ( x - ( h / 2 ) ) ) <> ( 0 ) & ( ( cos ) . ( x - ( h / 2 ) ) ) <> ( 0 )) by A3,RFUNCT_1:3;
(( x + ( h / 2 ) ) in ( dom f ) & ( x - ( h / 2 ) ) in ( dom f )) by A1,VALUED_1:def 4;
then ( ( cD (f,h) ) . x ) = ( ( ( ( cosec ) (#) ( sec ) ) . ( x + ( h / 2 ) ) ) - ( ( ( cosec ) (#) ( sec ) ) . ( x - ( h / 2 ) ) ) ) by DIFF_1:39
.= ( ( ( ( cosec ) . ( x + ( h / 2 ) ) ) * ( ( sec ) . ( x + ( h / 2 ) ) ) ) - ( ( ( cosec ) (#) ( sec ) ) . ( x - ( h / 2 ) ) ) ) by VALUED_1:5
.= ( ( ( ( cosec ) . ( x + ( h / 2 ) ) ) * ( ( sec ) . ( x + ( h / 2 ) ) ) ) - ( ( ( cosec ) . ( x - ( h / 2 ) ) ) * ( ( sec ) . ( x - ( h / 2 ) ) ) ) ) by VALUED_1:5
.= ( ( ( ( ( sin ) . ( x + ( h / 2 ) ) ) " ) * ( ( sec ) . ( x + ( h / 2 ) ) ) ) - ( ( ( cosec ) . ( x - ( h / 2 ) ) ) * ( ( sec ) . ( x - ( h / 2 ) ) ) ) ) by A2,RFUNCT_1:def 2
.= ( ( ( ( ( sin ) . ( x + ( h / 2 ) ) ) " ) * ( ( ( cos ) . ( x + ( h / 2 ) ) ) " ) ) - ( ( ( cosec ) . ( x - ( h / 2 ) ) ) * ( ( sec ) . ( x - ( h / 2 ) ) ) ) ) by A2,RFUNCT_1:def 2
.= ( ( ( ( ( sin ) . ( x + ( h / 2 ) ) ) " ) * ( ( ( cos ) . ( x + ( h / 2 ) ) ) " ) ) - ( ( ( ( sin ) . ( x - ( h / 2 ) ) ) " ) * ( ( sec ) . ( x - ( h / 2 ) ) ) ) ) by A3,RFUNCT_1:def 2
.= ( ( ( ( ( sin ) . ( x + ( h / 2 ) ) ) " ) * ( ( ( cos ) . ( x + ( h / 2 ) ) ) " ) ) - ( ( ( ( sin ) . ( x - ( h / 2 ) ) ) " ) * ( ( ( cos ) . ( x - ( h / 2 ) ) ) " ) ) ) by A3,RFUNCT_1:def 2
.= ( ( ( ( ( sin ) . ( x + ( h / 2 ) ) ) * ( ( cos ) . ( x + ( h / 2 ) ) ) ) " ) - ( ( ( ( sin ) . ( x - ( h / 2 ) ) ) " ) * ( ( ( cos ) . ( x - ( h / 2 ) ) ) " ) ) ) by XCMPLX_1:204
.= ( ( 1 / ( ( ( sin ) . ( x + ( h / 2 ) ) ) * ( ( cos ) . ( x + ( h / 2 ) ) ) ) ) - ( 1 / ( ( ( sin ) . ( x - ( h / 2 ) ) ) * ( ( cos ) . ( x - ( h / 2 ) ) ) ) ) ) by XCMPLX_1:204
.= ( ( ( 1 * ( ( ( sin ) . ( x - ( h / 2 ) ) ) * ( ( cos ) . ( x - ( h / 2 ) ) ) ) ) - ( 1 * ( ( ( sin ) . ( x + ( h / 2 ) ) ) * ( ( cos ) . ( x + ( h / 2 ) ) ) ) ) ) / ( ( ( ( sin ) . ( x + ( h / 2 ) ) ) * ( ( cos ) . ( x + ( h / 2 ) ) ) ) * ( ( ( sin ) . ( x - ( h / 2 ) ) ) * ( ( cos ) . ( x - ( h / 2 ) ) ) ) ) ) by A4,A5,XCMPLX_1:130
.= ( ( ( cos ( ( x - ( h / 2 ) ) + ( x + ( h / 2 ) ) ) ) * ( sin ( ( x - ( h / 2 ) ) - ( x + ( h / 2 ) ) ) ) ) / ( ( ( sin ( x + ( h / 2 ) ) ) * ( cos ( x + ( h / 2 ) ) ) ) * ( ( sin ( x - ( h / 2 ) ) ) * ( cos ( x - ( h / 2 ) ) ) ) ) ) by SIN_COS4:40
.= ( ( ( cos ( 2 * x ) ) * ( sin ( - h ) ) ) / ( ( ( 1 * ( sin ( x + ( h / 2 ) ) ) ) * ( cos ( x + ( h / 2 ) ) ) ) * ( ( 1 * ( sin ( x - ( h / 2 ) ) ) ) * ( cos ( x - ( h / 2 ) ) ) ) ) )
.= ( ( ( cos ( 2 * x ) ) * ( - ( sin h ) ) ) / ( ( ( ( ( 1 / 2 ) * 2 ) * ( sin ( x + ( h / 2 ) ) ) ) * ( cos ( x + ( h / 2 ) ) ) ) * ( ( ( ( 1 / 2 ) * 2 ) * ( sin ( x - ( h / 2 ) ) ) ) * ( cos ( x - ( h / 2 ) ) ) ) ) ) by SIN_COS:31
.= ( ( - ( ( cos ( 2 * x ) ) * ( sin h ) ) ) / ( ( ( 1 / 2 ) * ( ( 2 * ( sin ( x + ( h / 2 ) ) ) ) * ( cos ( x + ( h / 2 ) ) ) ) ) * ( ( 1 / 2 ) * ( ( 2 * ( sin ( x - ( h / 2 ) ) ) ) * ( cos ( x - ( h / 2 ) ) ) ) ) ) )
.= ( ( - ( ( cos ( 2 * x ) ) * ( sin h ) ) ) / ( ( ( 1 / 2 ) * ( sin ( 2 * ( x + ( h / 2 ) ) ) ) ) * ( ( 1 / 2 ) * ( ( 2 * ( sin ( x - ( h / 2 ) ) ) ) * ( cos ( x - ( h / 2 ) ) ) ) ) ) ) by SIN_COS5:5
.= ( ( - ( ( cos ( 2 * x ) ) * ( sin h ) ) ) / ( ( ( 1 / 2 ) * ( sin ( 2 * ( x + ( h / 2 ) ) ) ) ) * ( ( 1 / 2 ) * ( sin ( 2 * ( x - ( h / 2 ) ) ) ) ) ) ) by SIN_COS5:5
.= ( - ( ( ( cos ( 2 * x ) ) * ( sin h ) ) / ( ( ( sin ( ( 2 * x ) + h ) ) * ( sin ( ( 2 * x ) - h ) ) ) * ( 1 / 4 ) ) ) )
.= ( - ( ( 1 / ( 1 / 4 ) ) * ( ( ( cos ( 2 * x ) ) * ( sin h ) ) / ( ( sin ( ( 2 * x ) + h ) ) * ( sin ( ( 2 * x ) - h ) ) ) ) ) ) by XCMPLX_1:103
.= ( - ( 4 * ( ( ( cos ( 2 * x ) ) * ( sin h ) ) / ( ( sin ( ( 2 * x ) + h ) ) * ( sin ( ( 2 * x ) - h ) ) ) ) ) );
hence thesis;
end;
