environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,XXREAL_0,CARD_1,RELAT_1,SQUARE_1,ARYTM_3,ARYTM_1,PRE_TOPC,EUCLID,RLTOPSP1,MCART_1,REAL_1,SUBSET_1,BORSUK_1,XXREAL_1,RCOMP_1,TOPMETR,STRUCT_0,XBOOLE_0,FUNCT_1,ORDINAL2,TARSKI,TOPS_1,METRIC_1,SUPINF_2,COMPLEX1,JGRAPH_3,PSCOMP_1,PCOMPS_1,JORDAN3,TOPS_2,JORDAN17,JGRAPH_2,TOPREAL2,TOPREAL1,SEQ_4,FINSEQ_1,PARTFUN1,NAT_1,JORDAN6,JORDAN5C,FUNCT_4,RELAT_2,JGRAPH_6;
notations XBOOLE_0,ORDINAL1,XCMPLX_0,COMPLEX1,TARSKI,RELAT_1,TOPS_2,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,SUBSET_1,FINSEQ_1,FINSEQ_4,SEQ_4,STRUCT_0,TOPMETR,COMPTS_1,METRIC_1,SQUARE_1,RCOMP_1,PRE_TOPC,PCOMPS_1,RLVECT_1,RLTOPSP1,EUCLID,FUNCT_4,JGRAPH_3,JORDAN5C,JORDAN6,TOPREAL2,CONNSP_1,TOPS_1,JORDAN17,JGRAPH_2,NUMBERS,XREAL_0,TOPREAL1,PSCOMP_1,REAL_1,NAT_1,SPPOL_2,XXREAL_0;
definitions TARSKI,XBOOLE_0,TOPREAL1,EUCLID,SQUARE_1,STRUCT_0,RLTOPSP1;
theorems TARSKI,XBOOLE_0,XBOOLE_1,RELAT_1,FUNCT_1,FUNCT_2,TOPS_1,TOPS_2,PRE_TOPC,TOPMETR,JORDAN6,EUCLID,JGRAPH_1,SQUARE_1,PSCOMP_1,METRIC_1,JGRAPH_2,RCOMP_1,COMPTS_1,BORSUK_1,TOPREAL1,TOPREAL3,TOPREAL5,JGRAPH_3,ABSVALUE,JORDAN7,HEINE,JGRAPH_4,JORDAN5C,JGRAPH_5,GOBOARD6,TOPREAL2,TREAL_1,FINSEQ_1,FINSEQ_3,FINSEQ_4,ZFMISC_1,NAT_1,ENUMSET1,UNIFORM1,BORSUK_4,TSEP_1,FUNCT_4,JORDAN17,GOBOARD7,XREAL_0,TOPRNS_1,COMPLEX1,XCMPLX_0,XCMPLX_1,SPPOL_2,SEQ_4,XREAL_1,XXREAL_0,XXREAL_1,XXREAL_2,RLTOPSP1,RLVECT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14;
schemes FUNCT_2,JGRAPH_2,FRAENKEL,DOMAIN_1,CLASSES1;
registrations XBOOLE_0,RELSET_1,FUNCT_2,NUMBERS,XXREAL_0,XREAL_0,SQUARE_1,MEMBERED,STRUCT_0,PRE_TOPC,TOPS_1,BORSUK_1,EUCLID,TOPMETR,TOPREAL1,TOPREAL2,SPPOL_2,PSCOMP_1,JGRAPH_2,JGRAPH_3,XXREAL_2,COMPTS_1,RLTOPSP1,MEASURE6,FUNCT_1,FINSEQ_1;
constructors FUNCT_4,REAL_1,SQUARE_1,NAT_1,COMPLEX1,RCOMP_1,FINSEQ_4,TOPS_1,CONNSP_1,TOPS_2,COMPTS_1,MONOID_0,TOPMETR,TOPREAL1,SPPOL_2,PSCOMP_1,JORDAN5C,JORDAN6,JGRAPH_2,JGRAPH_3,JORDAN17,SEQ_1,PCOMPS_1,XXREAL_2,SEQ_4,FUNCSDOM,CONVEX1,BINOP_2;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
theorem
Th20: (for X being non  empty TopSpace holds (for n being (Element of ( NAT )) holds (for g1,g2 being (Function of X,( TOP-REAL n )) holds ((g1 is  continuous & g2 is  continuous) implies (ex g being (Function of X,( TOP-REAL n )) st ((for r being (Point of X) holds ( g . r ) = ( ( g1 . r ) + ( g2 . r ) )) & g is  continuous))))))
proof
let X being non  empty TopSpace;
let n being (Element of ( NAT ));
let g1 being (Function of X,( TOP-REAL n ));
let g2 being (Function of X,( TOP-REAL n ));
assume that
A1: g1 is  continuous
and
A2: g2 is  continuous;
defpred P[ set,set ]
 means
(for r1,r2 being (Element of ( TOP-REAL n )) holds ((( g1 . $1 ) = r1 & ( g2 . $1 ) = r2) implies $2 = ( r1 + r2 )));
A3: (for x being (Element of X) holds (ex y being (Element of ( TOP-REAL n )) st P[ x,y ]))
proof
let x being (Element of X);
set rr1 = ( g1 . x );
set rr2 = ( g2 . x );
set r3 = ( rr1 + rr2 );
(for s1,s2 being (Point of ( TOP-REAL n )) holds ((( g1 . x ) = s1 & ( g2 . x ) = s2) implies r3 = ( s1 + s2 )));
hence thesis;
end;
(ex f being (Function of (the carrier of X),(the carrier of ( TOP-REAL n ))) st (for x being (Element of X) holds P[ x,( f . x ) ])) from FUNCT_2:sch 3(A3);
then consider f being (Function of (the carrier of X),(the carrier of ( TOP-REAL n ))) such that A4: (for x being (Element of X) holds (for r1,r2 being (Element of ( TOP-REAL n )) holds ((( g1 . x ) = r1 & ( g2 . x ) = r2) implies ( f . x ) = ( r1 + r2 ))));
reconsider g0 = f as (Function of X,( TOP-REAL n ));
A5: (for r being (Point of X) holds ( g0 . r ) = ( ( g1 . r ) + ( g2 . r ) )) by A4;
(for p being (Point of X) holds (for V being (Subset of ( TOP-REAL n )) holds ((( g0 . p ) in V & V is  open) implies (ex W being (Subset of X) st ((p in W & W is  open) & ( g0 .: W ) c= V)))))
proof
let p being (Point of X);
let V being (Subset of ( TOP-REAL n ));
assume that
A6: ( g0 . p ) in V
and
A7: V is  open;
A8: ( g0 . p ) in ( Int V ) by A6,A7,TOPS_1:23;
reconsider r = ( g0 . p ) as (Point of ( Euclid n )) by TOPREAL3:8;
consider r0 being  real number such that A9: r0 > ( 0 ) and A10: ( Ball (r,r0) ) c= V by A8,GOBOARD6:5;
reconsider r01 = ( g1 . p ) as (Point of ( Euclid n )) by TOPREAL3:8;
reconsider G1 = ( Ball (r01,( r0 / 2 )) ) as (Subset of ( TOP-REAL n )) by TOPREAL3:8;
reconsider r02 = ( g2 . p ) as (Point of ( Euclid n )) by TOPREAL3:8;
reconsider G2 = ( Ball (r02,( r0 / 2 )) ) as (Subset of ( TOP-REAL n )) by TOPREAL3:8;
A11: ( g1 . p ) in G1 by A9,GOBOARD6:1,XREAL_1:215;
A12: ( the TopStruct of ( TOP-REAL n ) ) = ( TopSpaceMetr ( Euclid n ) ) by EUCLID:def 8;
then reconsider GG1 = G1,GG2 = G2 as (Subset of ( TopSpaceMetr ( Euclid n ) ));
GG1 is  open by TOPMETR:14;
then G1 is  open by A12,PRE_TOPC:30;
then consider W1 being (Subset of X) such that A13: p in W1 and A14: W1 is  open and A15: ( g1 .: W1 ) c= G1 by A1,A11,JGRAPH_2:10;
A16: ( g2 . p ) in G2 by A9,GOBOARD6:1,XREAL_1:215;
GG2 is  open by TOPMETR:14;
then G2 is  open by A12,PRE_TOPC:30;
then consider W2 being (Subset of X) such that A17: p in W2 and A18: W2 is  open and A19: ( g2 .: W2 ) c= G2 by A2,A16,JGRAPH_2:10;
set W = ( W1 /\ W2 );
A20: p in W by A13,A17,XBOOLE_0:def 4;
( g0 .: W ) c= ( Ball (r,r0) )
proof
let x being set;
assume x in ( g0 .: W );
then consider z being set such that A21: z in ( dom g0 ) and A22: z in W and A23: ( g0 . z ) = x by FUNCT_1:def 6;
A24: z in W1 by A22,XBOOLE_0:def 4;
reconsider pz = z as (Point of X) by A21;
( dom g1 ) = (the carrier of X) by FUNCT_2:def 1;
then A25: ( g1 . pz ) in ( g1 .: W1 ) by A24,FUNCT_1:def 6;
reconsider aa1 = ( g1 . pz ) as (Point of ( TOP-REAL n ));
reconsider bb1 = aa1 as (Point of ( Euclid n )) by TOPREAL3:8;
( dist (r01,bb1) ) < ( r0 / 2 ) by A15,A25,METRIC_1:11;
then A26: |. ( ( g1 . p ) - ( g1 . pz ) ) .| < ( r0 / 2 ) by JGRAPH_1:28;
A27: z in W2 by A22,XBOOLE_0:def 4;
( dom g2 ) = (the carrier of X) by FUNCT_2:def 1;
then A28: ( g2 . pz ) in ( g2 .: W2 ) by A27,FUNCT_1:def 6;
reconsider aa2 = ( g2 . pz ) as (Point of ( TOP-REAL n ));
reconsider bb2 = aa2 as (Point of ( Euclid n )) by TOPREAL3:8;
( dist (r02,bb2) ) < ( r0 / 2 ) by A19,A28,METRIC_1:11;
then A29: |. ( ( g2 . p ) - ( g2 . pz ) ) .| < ( r0 / 2 ) by JGRAPH_1:28;
A30: ( aa1 + aa2 ) = x by A4,A23;
reconsider bb0 = ( aa1 + aa2 ) as (Point of ( Euclid n )) by TOPREAL3:8;
A31: ( g0 . pz ) = ( ( g1 . pz ) + ( g2 . pz ) ) by A4;
( ( ( g1 . p ) + ( g2 . p ) ) - ( ( g1 . pz ) + ( g2 . pz ) ) ) = ( ( ( ( g1 . p ) + ( g2 . p ) ) - ( g1 . pz ) ) - ( g2 . pz ) ) by EUCLID:46
.= ( ( ( ( g1 . p ) + ( g2 . p ) ) + ( - ( g1 . pz ) ) ) - ( g2 . pz ) ) by EUCLID:41
.= ( ( ( ( g1 . p ) + ( g2 . p ) ) + ( - ( g1 . pz ) ) ) + ( - ( g2 . pz ) ) ) by EUCLID:41
.= ( ( ( ( g1 . p ) + ( - ( g1 . pz ) ) ) + ( g2 . p ) ) + ( - ( g2 . pz ) ) ) by EUCLID:26
.= ( ( ( g1 . p ) + ( - ( g1 . pz ) ) ) + ( ( g2 . p ) + ( - ( g2 . pz ) ) ) ) by EUCLID:26
.= ( ( ( g1 . p ) - ( g1 . pz ) ) + ( ( g2 . p ) + ( - ( g2 . pz ) ) ) ) by EUCLID:41
.= ( ( ( g1 . p ) - ( g1 . pz ) ) + ( ( g2 . p ) - ( g2 . pz ) ) ) by EUCLID:41;
then A32: |. ( ( ( g1 . p ) + ( g2 . p ) ) - ( ( g1 . pz ) + ( g2 . pz ) ) ) .| <= ( |. ( ( g1 . p ) - ( g1 . pz ) ) .| + |. ( ( g2 . p ) - ( g2 . pz ) ) .| ) by TOPRNS_1:29;
( |. ( ( g1 . p ) - ( g1 . pz ) ) .| + |. ( ( g2 . p ) - ( g2 . pz ) ) .| ) < ( ( r0 / 2 ) + ( r0 / 2 ) ) by A26,A29,XREAL_1:8;
then |. ( ( ( g1 . p ) + ( g2 . p ) ) - ( ( g1 . pz ) + ( g2 . pz ) ) ) .| < r0 by A32,XXREAL_0:2;
then |. ( ( g0 . p ) - ( g0 . pz ) ) .| < r0 by A4,A31;
then ( dist (r,bb0) ) < r0 by A23,A30,JGRAPH_1:28;
hence thesis by A30,METRIC_1:11;
end;
hence thesis by A10,A14,A18,A20,XBOOLE_1:1;
end;
then g0 is  continuous by JGRAPH_2:10;
hence thesis by A5;
end;
