environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,XXREAL_0,CARD_1,RELAT_1,SQUARE_1,ARYTM_3,ARYTM_1,PRE_TOPC,EUCLID,RLTOPSP1,MCART_1,REAL_1,SUBSET_1,BORSUK_1,XXREAL_1,RCOMP_1,TOPMETR,STRUCT_0,XBOOLE_0,FUNCT_1,ORDINAL2,TARSKI,TOPS_1,METRIC_1,SUPINF_2,COMPLEX1,JGRAPH_3,PSCOMP_1,PCOMPS_1,JORDAN3,TOPS_2,JORDAN17,JGRAPH_2,TOPREAL2,TOPREAL1,SEQ_4,FINSEQ_1,PARTFUN1,NAT_1,JORDAN6,JORDAN5C,FUNCT_4,RELAT_2,JGRAPH_6;
notations XBOOLE_0,ORDINAL1,XCMPLX_0,COMPLEX1,TARSKI,RELAT_1,TOPS_2,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,SUBSET_1,FINSEQ_1,FINSEQ_4,SEQ_4,STRUCT_0,TOPMETR,COMPTS_1,METRIC_1,SQUARE_1,RCOMP_1,PRE_TOPC,PCOMPS_1,RLVECT_1,RLTOPSP1,EUCLID,FUNCT_4,JGRAPH_3,JORDAN5C,JORDAN6,TOPREAL2,CONNSP_1,TOPS_1,JORDAN17,JGRAPH_2,NUMBERS,XREAL_0,TOPREAL1,PSCOMP_1,REAL_1,NAT_1,SPPOL_2,XXREAL_0;
definitions TARSKI,XBOOLE_0,TOPREAL1,EUCLID,SQUARE_1,STRUCT_0,RLTOPSP1;
theorems TARSKI,XBOOLE_0,XBOOLE_1,RELAT_1,FUNCT_1,FUNCT_2,TOPS_1,TOPS_2,PRE_TOPC,TOPMETR,JORDAN6,EUCLID,JGRAPH_1,SQUARE_1,PSCOMP_1,METRIC_1,JGRAPH_2,RCOMP_1,COMPTS_1,BORSUK_1,TOPREAL1,TOPREAL3,TOPREAL5,JGRAPH_3,ABSVALUE,JORDAN7,HEINE,JGRAPH_4,JORDAN5C,JGRAPH_5,GOBOARD6,TOPREAL2,TREAL_1,FINSEQ_1,FINSEQ_3,FINSEQ_4,ZFMISC_1,NAT_1,ENUMSET1,UNIFORM1,BORSUK_4,TSEP_1,FUNCT_4,JORDAN17,GOBOARD7,XREAL_0,TOPRNS_1,COMPLEX1,XCMPLX_0,XCMPLX_1,SPPOL_2,SEQ_4,XREAL_1,XXREAL_0,XXREAL_1,XXREAL_2,RLTOPSP1,RLVECT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8;
schemes FUNCT_2,JGRAPH_2,FRAENKEL,DOMAIN_1,CLASSES1;
registrations XBOOLE_0,RELSET_1,FUNCT_2,NUMBERS,XXREAL_0,XREAL_0,SQUARE_1,MEMBERED,STRUCT_0,PRE_TOPC,TOPS_1,BORSUK_1,EUCLID,TOPMETR,TOPREAL1,TOPREAL2,SPPOL_2,PSCOMP_1,JGRAPH_2,JGRAPH_3,XXREAL_2,COMPTS_1,RLTOPSP1,MEASURE6,FUNCT_1,FINSEQ_1;
constructors FUNCT_4,REAL_1,SQUARE_1,NAT_1,COMPLEX1,RCOMP_1,FINSEQ_4,TOPS_1,CONNSP_1,TOPS_2,COMPTS_1,MONOID_0,TOPMETR,TOPREAL1,SPPOL_2,PSCOMP_1,JORDAN5C,JORDAN6,JGRAPH_2,JGRAPH_3,JORDAN17,SEQ_1,PCOMPS_1,XXREAL_2,SEQ_4,FUNCSDOM,CONVEX1,BINOP_2;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
theorem
Th14: (for X being non  empty TopSpace holds (for B being non  empty (Subset of X) holds (ex f being (Function of ( X | B ),X) st ((for p being (Point of ( X | B )) holds ( f . p ) = p) & f is  continuous))))
proof
let X being non  empty TopSpace;
let B being non  empty (Subset of X);
defpred P[ set,set ]
 means
(for p being (Point of ( X | B )) holds $2 = $1);
A1: ( [#] ( X | B ) ) = B by PRE_TOPC:def 5;
A2: (for x being (Element of ( X | B )) holds (ex y being (Element of X) st P[ x,y ]))
proof
let x being (Element of ( X | B ));
x in B by A1;
then reconsider px = x as (Point of X);
set y0 = px;
P[ x,y0 ];
hence thesis;
end;
(ex g being (Function of (the carrier of ( X | B )),(the carrier of X)) st (for x being (Element of ( X | B )) holds P[ x,( g . x ) ])) from FUNCT_2:sch 3(A2);
then consider g being (Function of (the carrier of ( X | B )),(the carrier of X)) such that A3: (for x being (Element of ( X | B )) holds P[ x,( g . x ) ]);
A4: (for p being (Point of ( X | B )) holds ( g . p ) = p) by A3;
A5: (for r0 being (Point of ( X | B )) holds (for V being (Subset of X) holds ((( g . r0 ) in V & V is  open) implies (ex W being (Subset of ( X | B )) st ((r0 in W & W is  open) & ( g .: W ) c= V)))))
proof
let r0 being (Point of ( X | B ));
let V being (Subset of X);
assume that
A6: ( g . r0 ) in V
and
A7: V is  open;
reconsider W2 = ( V /\ ( [#] ( X | B ) ) ) as (Subset of ( X | B ));
( g . r0 ) = r0 by A3;
then A8: r0 in W2 by A6,XBOOLE_0:def 4;
A9: W2 is  open by A7,TOPS_2:24;
( g .: W2 ) c= V
proof
let y being set;
assume y in ( g .: W2 );
then consider x being set such that A10: x in ( dom g ) and A11: x in W2 and A12: y = ( g . x ) by FUNCT_1:def 6;
reconsider px = x as (Point of ( X | B )) by A10;
( g . px ) = px by A3;
hence thesis by A11,A12,XBOOLE_0:def 4;
end;
hence thesis by A8,A9;
end;
reconsider g1 = g as (Function of ( X | B ),X);
g1 is  continuous by A5,JGRAPH_2:10;
hence thesis by A4;
end;
