environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,SUBSET_1,INT_1,TARSKI,ARYTM_3,XBOOLE_0,CARD_1,ARYTM_0,RELAT_1,REAL_1,ARYTM_2,ORDINAL2,ARYTM_1,ZFMISC_1,XXREAL_0,NAT_1,RAT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,ORDINAL3,ARYTM_3,ARYTM_2,NUMBERS,ARYTM_0,XCMPLX_0,XREAL_0,REAL_1,NAT_1,INT_1,ARYTM_1,XXREAL_0,CKB7,CKB8,CKB11,CKB41,CKB42;
definitions XREAL_0,TARSKI,XBOOLE_0,XCMPLX_0,ARYTM_3,CKB7,CKB8,CKB41,CKB42;
theorems INT_1,NAT_1,TARSKI,XREAL_0,XCMPLX_0,XCMPLX_1,XBOOLE_0,NUMBERS,ARYTM_3,ARYTM_0,ARYTM_2,ZFMISC_1,ARYTM_1,XREAL_1,XXREAL_0,XBOOLE_1,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB12,CKB13,CKB15,CKB16,CKB34,CKB36,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77;
schemes NAT_1;
registrations ORDINAL1,ARYTM_3,ARYTM_2,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,ORDINAL3,XBOOLE_0,CKB9,CKB10,CKB14,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB35,CKB37;
constructors FUNCT_4,ARYTM_1,ARYTM_0,XXREAL_0,REAL_1,NAT_1,INT_1,ORDINAL3,CKB8,CKB41,CKB42;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve k for (Element of ( NAT ));
reserve l for (Element of ( NAT ));
reserve m for Integer;
reserve p for Rational;
reserve q for Rational;
theorem
Th88: ((( 0 ) < p & q = ( 1 / p )) iff (( numerator q ) = ( denominator p ) & ( denominator q ) = ( numerator p )))
proof
A1:now
set x = ( denominator p );
assume that
A2: ( 0 ) < p
and
A3: q = ( 1 / p );
A4: q = ( 1 / ( ( numerator p ) / ( denominator p ) ) ) by A3,CKB48:1
.= ( ( 1 * ( denominator p ) ) / ( numerator p ) ) by XCMPLX_1:77
.= ( ( denominator p ) / ( numerator p ) );
reconsider y = ( numerator p ) as (Element of ( NAT )) by A2,INT_1:3;
A5: (not (ex k st (1 < k & (ex m st (ex l st (x = ( m * k ) & y = ( l * k )))))))
proof
assume (not thesis);
then consider k such that A6: 1 < k and A7: (ex m st (ex l st (x = ( m * k ) & y = ( l * k ))));
consider m,l such that A8: x = ( m * k ) and A9: y = ( l * k ) by A7;
now
assume (not ( 0 ) <= m);
then ( m * k ) < ( ( 0 ) * m ) by A6,XREAL_1:69;
hence contradiction by A8;
end;
then reconsider z = m as (Element of ( NAT )) by INT_1:3;
( denominator p ) = ( z * k ) by A8;
hence contradiction by A6,A9,CKB63:1;
end;
( 0 ) <> ( numerator p ) by A2,CKB72:1;
hence (( numerator p ) = ( denominator q ) & ( denominator p ) = ( numerator q )) by A4,A5,CKB64:1;
end;
now
assume that
A10: ( numerator q ) = ( denominator p )
and
A11: ( denominator q ) = ( numerator p );
thus ( 0 ) < p by A11,CKB43:1;
thus q = ( ( 1 * ( denominator p ) ) / ( numerator p ) ) by A10,A11,CKB48:1
.= ( 1 / ( ( numerator p ) / ( denominator p ) ) ) by XCMPLX_1:77
.= ( 1 / p ) by CKB48:1;
end;
hence thesis by A1;
end;
