environ
vocabularies NUMBERS,SUBSET_1,REAL_1,SEQ_1,PARTFUN1,FDIFF_1,RELAT_1,CARD_3,FUNCT_1,FINSEQ_1,FINSEQ_2,PDIFF_1,RCOMP_1,TARSKI,ARYTM_1,ARYTM_3,XREAL_0,ORDINAL1,CARD_1,XXREAL_1,VALUED_0,SEQ_2,ORDINAL2,XXREAL_0,NAT_1,FUNCT_2,VALUED_1,XBOOLE_0,COMPLEX1,FCONT_1,PDIFF_2;
notations TARSKI,SUBSET_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,XCMPLX_0,XREAL_0,COMPLEX1,ORDINAL1,NUMBERS,REAL_1,NAT_1,VALUED_0,VALUED_1,SEQ_1,SEQ_2,FINSEQ_1,FINSEQ_2,RCOMP_1,EUCLID,FDIFF_1,XXREAL_0,FCONT_1,PDIFF_1;
definitions TARSKI,EUCLID,RCOMP_1,PDIFF_1;
theorems TARSKI,XBOOLE_0,XBOOLE_1,XREAL_1,RCOMP_1,SEQ_4,SEQ_1,SEQ_2,FINSEQ_1,FINSEQ_2,RFUNCT_2,RELAT_1,FUNCT_1,FUNCT_2,PARTFUN1,FDIFF_1,VALUED_1,SEQM_3,RFUNCT_1,XCMPLX_0,XCMPLX_1,PDIFF_1,NAT_1,VALUED_0,ORDINAL1,CKB1;
schemes SEQ_1;
registrations RELSET_1,XREAL_0,MEMBERED,FDIFF_1,FUNCT_2,NAT_1,NUMBERS,XBOOLE_0,XXREAL_0,FINSEQ_1,VALUED_0,VALUED_1,ORDINAL1,SEQ_4;
constructors REAL_1,SEQ_2,PARTFUN1,RFUNCT_2,COMPLEX1,RCOMP_1,FDIFF_1,SEQ_1,NAT_1,FCONT_1,PDIFF_1,BHSP_3,VFUNCT_1,SEQM_3,RELSET_1,BINOP_2,RVSUM_1;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve x for Real;
reserve y for Real;
theorem
Th2: ((( dom ( proj (2,2) ) ) = ( REAL 2 ) & ( rng ( proj (2,2) ) ) = ( REAL )) & (for x,y being (Element of ( REAL )) holds ( ( proj (2,2) ) . <* x,y *> ) = y))
proof
set f = ( proj (2,2) );
A1: (for y being set holds (y in ( REAL ) implies (ex z being set st (z in ( REAL 2 ) & y = ( f . z )))))
proof
set x = the (Element of ( REAL ));
let y being set;
assume y in ( REAL );
then reconsider y1 = y as (Element of ( REAL ));
reconsider z = <* x,y1 *> as (Element of ( REAL 2 )) by FINSEQ_2:101;
( f . z ) = ( z . 2 ) by PDIFF_1:def 1;
then ( f . z ) = y by FINSEQ_1:44;
hence thesis;
end;
now
let x being (Element of ( REAL ));
let y being (Element of ( REAL ));
<* x,y *> is (Element of ( 2 -tuples_on ( REAL ) )) by FINSEQ_2:101;
then ( ( proj (2,2) ) . <* x,y *> ) = ( <* x,y *> . 2 ) by PDIFF_1:def 1;
hence ( ( proj (2,2) ) . <* x,y *> ) = y by FINSEQ_1:44;
end;
hence thesis by A1,FUNCT_2:10,FUNCT_2:def 1;
end;
