environ
vocabularies SUBSET_1,ARYTM_2,ARYTM_3,XBOOLE_0,ARYTM_1;
notations TARSKI,SUBSET_1,ARYTM_3,ARYTM_2;
theorems ARYTM_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
constructors ARYTM_2;
requirements SUBSET;
begin
reserve x for (Element of ( REAL+ ));
reserve y for (Element of ( REAL+ ));
reserve z for (Element of ( REAL+ ));
reconsider u = ( one ) as (Element of ( REAL+ )) by ARYTM_2:20;
theorem
Lm2: ((( x *' y ) <=' ( x *' z ) & x <> ( {} )) implies y <=' z)
proof
assume ( x *' y ) <=' ( x *' z );
then consider z0 being (Element of ( REAL+ )) such that A1: ( ( x *' y ) + z0 ) = ( x *' z ) by ARYTM_2:9;
assume A2: x <> ( {} );
then consider x1 being (Element of ( REAL+ )) such that A3: ( x *' x1 ) = ( one ) by ARYTM_2:14;
( x *' z ) = ( ( x *' y ) + ( u *' z0 ) ) by A1,ARYTM_2:15
.= ( ( x *' y ) + ( x *' ( x1 *' z0 ) ) ) by A3,ARYTM_2:12
.= ( x *' ( y + ( x1 *' z0 ) ) ) by ARYTM_2:13;
hence thesis by A2,CKB2:1,ARYTM_2:19;
end;
