environ
vocabularies PRE_TOPC,RLVECT_1,FUNCT_1,ARYTM_3,ARYTM_1,FINSEQ_1,VALUED_1,MSSUBFAM,FINSEQ_2,CARD_3,RVSUM_1,RELAT_1,COMPLEX1,SQUARE_1,RCOMP_1,PARTFUN1,NORMSP_1,XBOOLE_0,LOPBAN_1,FDIFF_1,REAL_NS1,BORSUK_1,EUCLID,NUMBERS,FUNCOP_1,STRUCT_0,UNIALG_1,EUCLID_7,MATRIXR2,RFINSEQ2,REAL_1,SUBSET_1,CARD_1,TARSKI,XXREAL_0,XXREAL_2,NAT_1,ORDINAL4,SUPINF_2,VALUED_2;
notations TARSKI,XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,SEQ_1,STRUCT_0,RLVECT_1,FINSEQ_1,FINSEQ_2,SQUARE_1,VALUED_0,VALUED_1,VALUED_2,RVSUM_1,GRCAT_1,PRE_TOPC,VFUNCT_1,NORMSP_0,NORMSP_1,EUCLID,LOPBAN_1,NFCONT_1,NDIFF_1,REAL_NS1,PDIFF_1,INTEGR15,EUCLID_7,RFINSEQ2;
definitions LOPBAN_1,RVSUM_1,EUCLID,VALUED_1,FINSEQ_1,XCMPLX_0,RFINSEQ2,VALUED_2,SQUARE_1;
theorems TARSKI,ABSVALUE,XBOOLE_0,XBOOLE_1,EUCLID,XREAL_1,XCMPLX_0,RLVECT_1,COMPLEX1,FINSEQ_1,FINSEQ_2,ORDINAL1,NAT_1,XXREAL_0,RVSUM_1,RELAT_1,FUNCT_1,VFUNCT_1,FUNCT_2,SQUARE_1,INTEGR15,FUNCOP_1,EUCLID_7,FINSEQ_4,FINSEQ_5,NORMSP_1,LOPBAN_1,PARTFUN1,PARTFUN2,NFCONT_1,NDIFF_1,REAL_NS1,VALUED_1,PDIFF_1,RFINSEQ2,RLVECT_4,JORDAN2C,GRCAT_1,NORMSP_0,VALUED_2,CKB1,CKB2,CKB3;
schemes FUNCT_2,NAT_1,FINSEQ_1,RECDEF_1;
registrations RELSET_1,STRUCT_0,XREAL_0,MEMBERED,LOPBAN_1,FUNCT_2,NAT_1,REAL_NS1,NUMBERS,XBOOLE_0,XXREAL_0,VALUED_0,EUCLID,FINSEQ_2,CARD_1,VALUED_1,VALUED_2;
constructors REAL_1,SQUARE_1,RSSPACE3,FINSEQOP,VFUNCT_1,COMPLEX1,NFCONT_1,NDIFF_1,SEQ_1,PDIFF_1,BINOP_2,MONOID_0,INTEGR15,RELSET_1,EUCLID_7,RFINSEQ2,GRCAT_1,JORDAN2B,VALUED_2;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
theorem
Th4: (for f1,f2 being (PartFunc of ( REAL m ),( REAL n )) holds (for g1,g2 being (PartFunc of ( REAL-NS m ),( REAL-NS n )) holds ((f1 = g1 & f2 = g2) implies ( f1 + f2 ) = ( g1 + g2 ))))
proof
let f1 being (PartFunc of ( REAL m ),( REAL n ));
let f2 being (PartFunc of ( REAL m ),( REAL n ));
let g1 being (PartFunc of ( REAL-NS m ),( REAL-NS n ));
let g2 being (PartFunc of ( REAL-NS m ),( REAL-NS n ));
assume A1: (f1 = g1 & f2 = g2);
((the carrier of ( REAL-NS m )) = ( REAL m ) & (the carrier of ( REAL-NS n )) = ( REAL n )) by REAL_NS1:def 4;
then reconsider g12 = ( g1 + g2 ) as (PartFunc of ( REAL m ),( REAL n ));
A2: ( ( dom f1 ) /\ ( dom f2 ) ) = ( dom g12 ) by A1,VFUNCT_1:def 1;
A5: ( f1 <++> f2 ) = ( f1 + f2 ) by INTEGR15:def 9;
(for c being set holds (c in ( dom g12 ) implies ( ( g1 + g2 ) . c ) = ( ( f1 . c ) + ( f2 . c ) )))
proof
let c being set;
assume A3: c in ( dom g12 );
then A6: c in ( dom ( g1 + g2 ) );
(c in ( dom f1 ) & c in ( dom f2 )) by A2,A3,XBOOLE_0:def 4;
then A8: (( f1 /. c ) = ( f1 . c ) & ( f2 /. c ) = ( f2 . c )) by PARTFUN1:def 6;
A4: (( f1 /. c ) = ( g1 /. c ) & ( f2 /. c ) = ( g2 /. c )) by A1,REAL_NS1:def 4;
( g12 . c ) = ( ( g1 + g2 ) /. c ) by A3,PARTFUN1:def 6
.= ( ( g1 /. c ) + ( g2 /. c ) ) by A6,VFUNCT_1:def 1;
hence thesis by A8,A4,REAL_NS1:2;
end;
hence thesis by A2,A5,VALUED_2:def 45;
end;
