environ
vocabularies NUMBERS,RLVECT_1,CONVEX2,FUNCT_2,STRUCT_0,XBOOLE_0,SUBSET_1,CARD_3,RLVECT_2,FUNCT_1,FINSEQ_1,RELAT_1,VALUED_1,TARSKI,NAT_1,XXREAL_0,CARD_1,ARYTM_3,ORDINAL4,CONVEX1,REAL_1,ARYTM_1,RFINSEQ,PARTFUN1,FINSET_1,SUPINF_2,CONVEX3;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,REAL_1,RELAT_1,FUNCT_1,FINSET_1,NAT_1,DOMAIN_1,PARTFUN1,STRUCT_0,ALGSTR_0,FUNCT_2,FINSEQ_1,RLVECT_1,RLVECT_2,RVSUM_1,CONVEX1,RFINSEQ,CONVEX2,CKB1;
definitions RVSUM_1,CKB1;
theorems RLVECT_1,RVSUM_1,FUNCT_1,FINSEQ_1,TARSKI,ZFMISC_1,XBOOLE_0,XBOOLE_1,RLVECT_2,CARD_1,FINSEQ_3,FINSEQ_4,ENUMSET1,CONVEX1,FUNCT_2,NAT_1,RFINSEQ,CONVEX2,RLVECT_3,CARD_2,FINSEQ_5,PARTFUN2,GRAPH_5,RELAT_1,XCMPLX_1,XREAL_1,XXREAL_0,FINSOP_1,ORDINAL1,PARTFUN1,VALUED_1,RLVECT_4,CKB1;
schemes NAT_1,XBOOLE_0,FINSEQ_1,CLASSES1;
registrations XBOOLE_0,ORDINAL1,RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,STRUCT_0,RLVECT_1,VALUED_0,CARD_1,RLVECT_2;
constructors DOMAIN_1,XXREAL_0,REAL_1,FINSOP_1,RVSUM_1,RFINSEQ,CONVEX1,SEQ_1,BINOP_2,RELSET_1,CKB1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
definition
let V being RealLinearSpace;
let M being non  empty (Subset of V);
func ConvexComb M -> set means 
(for L being set holds (L in it iff L is (Convex_Combination of M)));
existence
proof
defpred P[ set ]
 means
$1 is (Convex_Combination of M);
consider A being set such that A1: (for x being set holds (x in A iff (x in ( Funcs ((the carrier of V),( REAL )) ) & P[ x ]))) from XBOOLE_0:sch 1;
take A;
let L being set;
thus (L in A implies L is (Convex_Combination of M)) by A1;
assume L is (Convex_Combination of M);
hence thesis by A1;
end;
uniqueness
proof
defpred P[ set ]
 means
$1 is (Convex_Combination of M);
thus (for X1,X2 being set holds (((for x being set holds (x in X1 iff P[ x ])) & (for x being set holds (x in X2 iff P[ x ]))) implies X1 = X2)) from XBOOLE_0:sch 3;
end;
end;
