environ
vocabularies NUMBERS,RCOMP_1,SUBSET_1,REAL_1,COMPLEX1,NEWTON,ARYTM_3,RELAT_1,CARD_1,PARTFUN1,XREAL_0,ORDINAL1,SEQ_1,TAYLOR_1,XXREAL_1,ARYTM_1,TARSKI,FDIFF_1,FUNCT_1,SERIES_1,REALSET1,XBOOLE_0,SIN_COS,XXREAL_0,VALUED_0,VALUED_1,SEQ_2,ORDINAL2,CARD_3,ABIAN,TAYLOR_2;
notations TARSKI,SUBSET_1,RELAT_1,PARTFUN1,RFUNCT_2,RCOMP_1,XXREAL_0,XREAL_0,ORDINAL1,NUMBERS,COMPLEX1,REAL_1,NAT_1,FUNCT_2,VALUED_1,SEQ_1,SEQ_2,SERIES_1,FDIFF_1,SEQFUNC,NEWTON,SIN_COS,TAYLOR_1,ABIAN,CKB2;
definitions TAYLOR_1,VALUED_1,SUBSET_1,CKB2;
theorems XBOOLE_1,ABSVALUE,PARTFUN1,XCMPLX_1,RELAT_1,RCOMP_1,SEQ_1,SEQ_2,SIN_COS,SERIES_1,FUNCT_1,RFUNCT_2,NAT_1,NEWTON,POWER,FDIFF_1,FDIFF_2,TAYLOR_1,SIN_COS2,XREAL_1,RFUNCT_1,ABIAN,COMPLEX1,XXREAL_0,VALUED_1,FUNCT_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21;
schemes NAT_1;
registrations RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,RCOMP_1,XBOOLE_0,VALUED_0,VALUED_1,FUNCT_2;
constructors ARYTM_0,REAL_1,NAT_1,SEQ_2,RCOMP_1,RFUNCT_2,LIMFUNC1,FDIFF_1,COMSEQ_3,SIN_COS,ABIAN,TAYLOR_1,SEQ_1,SEQFUNC,SERIES_1,VALUED_1,RELSET_1,CKB2;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
theorem
Th20: (for n being (Element of ( NAT )) holds (for r,x being Real holds (r > ( 0 ) implies (((( ( Maclaurin (( sin ),]. ( - r ),r .[,x) ) . ( 2 * n ) ) = ( 0 ) & ( ( Maclaurin (( sin ),]. ( - r ),r .[,x) ) . ( ( 2 * n ) + 1 ) ) = ( ( ( ( - 1 ) |^ n ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) )) & ( ( Maclaurin (( cos ),]. ( - r ),r .[,x) ) . ( 2 * n ) ) = ( ( ( ( - 1 ) |^ n ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) )) & ( ( Maclaurin (( cos ),]. ( - r ),r .[,x) ) . ( ( 2 * n ) + 1 ) ) = ( 0 )))))
proof
A1: ( abs ( ( 0 ) - ( 0 ) ) ) = ( 0 ) by ABSVALUE:2;
let n being (Element of ( NAT ));
let r being Real;
let x being Real;
assume r > ( 0 );
then A2: ( 0 ) in ]. ( ( 0 ) - r ),( ( 0 ) + r ) .[ by A1,RCOMP_1:1;
then A3: ( 0 ) in ( dom ( ( cos ) | ]. ( - r ),r .[ ) ) by CKB19:1;
A4: ( dom ( ( ( - 1 ) |^ n ) (#) ( ( cos ) | ]. ( - r ),r .[ ) ) ) = ( dom ( ( cos ) | ]. ( - r ),r .[ ) ) by VALUED_1:def 5
.= ]. ( - r ),r .[ by CKB19:1;
A5: ( ( Maclaurin (( sin ),]. ( - r ),r .[,x) ) . ( ( 2 * n ) + 1 ) ) = ( ( ( ( ( diff (( sin ),]. ( - r ),r .[) ) . ( ( 2 * n ) + 1 ) ) . ( 0 ) ) * ( ( x - ( 0 ) ) |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by TAYLOR_1:def 7
.= ( ( ( ( ( ( - 1 ) |^ n ) (#) ( ( cos ) | ]. ( - r ),r .[ ) ) . ( 0 ) ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by CKB21:1
.= ( ( ( ( ( - 1 ) |^ n ) * ( ( ( cos ) | ]. ( - r ),r .[ ) . ( 0 ) ) ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by A2,A4,VALUED_1:def 5
.= ( ( ( ( ( - 1 ) |^ n ) * ( ( cos ) . ( 0 ) ) ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by A3,FUNCT_1:47
.= ( ( ( ( - 1 ) |^ n ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by SIN_COS:30;
A6: ( dom ( ( ( - 1 ) |^ n ) (#) ( ( sin ) | ]. ( - r ),r .[ ) ) ) = ( dom ( ( sin ) | ]. ( - r ),r .[ ) ) by VALUED_1:def 5
.= ]. ( - r ),r .[ by CKB19:1;
A7: ( 0 ) in ( dom ( ( sin ) | ]. ( - r ),r .[ ) ) by A2,CKB19:1;
A8: ( ( Maclaurin (( cos ),]. ( - r ),r .[,x) ) . ( 2 * n ) ) = ( ( ( ( ( diff (( cos ),]. ( - r ),r .[) ) . ( 2 * n ) ) . ( 0 ) ) * ( ( x - ( 0 ) ) |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by TAYLOR_1:def 7
.= ( ( ( ( ( ( - 1 ) |^ n ) (#) ( ( cos ) | ]. ( - r ),r .[ ) ) . ( 0 ) ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by CKB21:1
.= ( ( ( ( ( - 1 ) |^ n ) * ( ( ( cos ) | ]. ( - r ),r .[ ) . ( 0 ) ) ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by A2,A4,VALUED_1:def 5
.= ( ( ( ( ( - 1 ) |^ n ) * ( ( cos ) . ( 0 ) ) ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by A3,FUNCT_1:47
.= ( ( ( ( - 1 ) |^ n ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by SIN_COS:30;
A9: ( dom ( ( ( - 1 ) |^ ( n + 1 ) ) (#) ( ( sin ) | ]. ( - r ),r .[ ) ) ) = ( dom ( ( sin ) | ]. ( - r ),r .[ ) ) by VALUED_1:def 5
.= ]. ( - r ),r .[ by CKB19:1;
A10: ( ( Maclaurin (( cos ),]. ( - r ),r .[,x) ) . ( ( 2 * n ) + 1 ) ) = ( ( ( ( ( diff (( cos ),]. ( - r ),r .[) ) . ( ( 2 * n ) + 1 ) ) . ( 0 ) ) * ( ( x - ( 0 ) ) |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by TAYLOR_1:def 7
.= ( ( ( ( ( ( - 1 ) |^ ( n + 1 ) ) (#) ( ( sin ) | ]. ( - r ),r .[ ) ) . ( 0 ) ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by CKB21:1
.= ( ( ( ( ( - 1 ) |^ ( n + 1 ) ) * ( ( ( sin ) | ]. ( - r ),r .[ ) . ( 0 ) ) ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by A2,A9,VALUED_1:def 5
.= ( ( ( ( ( - 1 ) |^ ( n + 1 ) ) * ( ( sin ) . ( 0 ) ) ) * ( x |^ ( ( 2 * n ) + 1 ) ) ) / ( ( ( 2 * n ) + 1 ) ! ) ) by A7,FUNCT_1:47
.= ( 0 ) by SIN_COS:30;
( ( Maclaurin (( sin ),]. ( - r ),r .[,x) ) . ( 2 * n ) ) = ( ( ( ( ( diff (( sin ),]. ( - r ),r .[) ) . ( 2 * n ) ) . ( 0 ) ) * ( ( x - ( 0 ) ) |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by TAYLOR_1:def 7
.= ( ( ( ( ( ( - 1 ) |^ n ) (#) ( ( sin ) | ]. ( - r ),r .[ ) ) . ( 0 ) ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by CKB21:1
.= ( ( ( ( ( - 1 ) |^ n ) * ( ( ( sin ) | ]. ( - r ),r .[ ) . ( 0 ) ) ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by A2,A6,VALUED_1:def 5
.= ( ( ( ( ( - 1 ) |^ n ) * ( ( sin ) . ( 0 ) ) ) * ( x |^ ( 2 * n ) ) ) / ( ( 2 * n ) ! ) ) by A7,FUNCT_1:47
.= ( 0 ) by SIN_COS:30;
hence thesis by A5,A8,A10;
end;
