environ
vocabularies NUMBERS,PRE_TOPC,EUCLID,XREAL_0,ORDINAL1,COMPLEX1,ARYTM_1,CARD_1,SUPINF_2,SUBSET_1,VALUED_0,FINSEQ_1,SIN_COS,COMPLEX2,RELAT_1,XXREAL_0,ARYTM_3,REAL_1,EUCLID_3,COMPTRIG,FINSEQ_6,XCMPLX_0,MCART_1,FUNCT_1,PROB_2,SQUARE_1,RVSUM_1,RLTOPSP1,JGRAPH_6,XBOOLE_0,BORSUK_1,XXREAL_1,TOPS_2,STRUCT_0,PARTFUN1,ORDINAL2,TARSKI,ZFMISC_1,PARSP_2,PROJPL_1,TOPMETR,PCOMPS_1,METRIC_1,SIN_COS6,EUCLID_6;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,NUMBERS,XREAL_0,XXREAL_0,PARTFUN1,STRUCT_0,PRE_TOPC,SQUARE_1,VALUED_0,FINSEQ_1,FINSEQ_2,RVSUM_1,RLVECT_1,RLTOPSP1,EUCLID,SIN_COS,JGRAPH_6,COMPTRIG,COMPLEX2,TOPMETR,RCOMP_1,EUCLID_3,TOPS_2,XCMPLX_0,COMPLEX1,REAL_1,METRIC_1,PCOMPS_1,SIN_COS6,CKB21,CKB22;
definitions TARSKI,EUCLID,COMPLEX1,EUCLID_3,SQUARE_1,VALUED_1,ALGSTR_0,RLTOPSP1,CKB21,CKB22;
theorems TARSKI,XCMPLX_1,SQUARE_1,FUNCT_1,COMPLEX1,XBOOLE_0,FUNCT_2,EUCLID,COMPLEX2,XREAL_0,EUCLID_2,TOPREAL1,XREAL_1,COMPTRIG,EUCLID_3,SIN_COS,ZFMISC_1,TOPREAL9,XXREAL_0,SIN_COS6,XXREAL_1,RCOMP_1,JGRAPH_6,JORDAN5A,JORDAN2C,RELSET_1,TOPS_2,JORDAN6,BORSUK_1,JGRAPH_1,TOPMETR,METRIC_1,UNIFORM1,TOPREAL3,JGRAPH_2,TOPREAL5,PRE_TOPC,RFUNCT_2,XBOOLE_1,PARTFUN1,VALUED_1,RELAT_1,RLVECT_1,RLTOPSP1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36;
schemes CLASSES1;
registrations XBOOLE_0,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,MONOID_0,STRUCT_0,EUCLID,XCMPLX_0,TOPMETR,SQUARE_1,FUNCT_2,PRE_TOPC,METRIC_1,BORSUK_1,SIN_COS6,VALUED_0,RVSUM_1,RLTOPSP1;
constructors REAL_1,SQUARE_1,BINOP_2,MONOID_0,SEQ_1,ARYTM_0,RCOMP_1,SIN_COS,JGRAPH_6,COMPTRIG,COMPLEX2,TOPREAL1,EUCLID_3,TOPS_2,SIN_COS6,RFUNCT_2,FUNCSDOM,FUNCT_4,FUNCOP_1,SETFAM_1,CONVEX1,JORDAN2C,FINSEQOP,PCOMPS_1,COMPLEX1,CKB21,CKB22;
requirements BOOLE,SUBSET,REAL,NUMERALS,ARITHM;
begin
reserve p1 for (Point of ( TOP-REAL 2 ));
reserve p2 for (Point of ( TOP-REAL 2 ));
reserve p3 for (Point of ( TOP-REAL 2 ));
reserve p for (Point of ( TOP-REAL 2 ));
theorem
Th18: (((((|. ( p1 - p3 ) .| = |. ( p2 - p3 ) .| & p in ( LSeg (p1,p2) )) & p <> p3) & p <> p1) & (( angle (p3,p,p1) ) = ( ( PI ) / 2 ) or ( angle (p3,p,p1) ) = ( ( 3 / 2 ) * ( PI ) ))) implies ( angle (p1,p3,p) ) = ( angle (p,p3,p2) ))
proof
assume A1: |. ( p1 - p3 ) .| = |. ( p2 - p3 ) .|;
then A2: |. ( p3 - p1 ) .| = |. ( p2 - p3 ) .| by CKB2:1;
assume A3: p in ( LSeg (p1,p2) );
assume that
A4: p <> p3
and
A5: p <> p1;
assume A6: (( angle (p3,p,p1) ) = ( ( PI ) / 2 ) or ( angle (p3,p,p1) ) = ( ( 3 / 2 ) * ( PI ) ));
per cases ;
suppose A7: p1 = p2;

then ( LSeg (p1,p2) ) = { p1 } by RLTOPSP1:70;
then p = p1 by A3,TARSKI:def 1;
hence thesis by A7;
end;
suppose A8: p1 <> p2;

per cases ;
suppose A9: p <> p2;

p2 <> p3
proof
assume A10: p2 = p3;
then |. ( p3 - p1 ) .| = ( 0 ) by A2,CKB1:1;
hence contradiction by A8,A10,CKB1:1;
end;
then A11: ( euc2cpx p2 ) <> ( euc2cpx p3 ) by EUCLID_3:4;
p1 <> p3
proof
assume A12: p1 = p3;
then |. ( p2 - p3 ) .| = ( 0 ) by A1,CKB1:1;
hence contradiction by A8,A12,CKB1:1;
end;
then A13: ( euc2cpx p1 ) <> ( euc2cpx p3 ) by EUCLID_3:4;
A14: (( euc2cpx p ) <> ( euc2cpx p1 ) & ( euc2cpx p ) <> ( euc2cpx p3 )) by A4,A5,EUCLID_3:4;
A15: (( angle (p1,p,p3) ) = ( angle (p3,p,p2) ) & ( euc2cpx p ) <> ( euc2cpx p2 )) by A3,A5,A6,A9,CKB33:1,EUCLID_3:4;
A16: ( angle (p3,p1,p) ) = ( angle (p3,p1,p2) ) by A3,A5,CKB28:1
.= ( angle (p1,p2,p3) ) by A2,A8,CKB35:1
.= ( angle (p,p2,p3) ) by A3,A9,CKB27:1;
A17: ( angle (p,p3,p1) ) = ( angle (p2,p3,p) )
proof
per cases  by A16,A14,A13,A11,A15,COMPLEX2:88;
suppose ((( ( ( angle (p,p2,p3) ) + ( angle (p,p3,p1) ) ) + ( angle (p3,p,p2) ) ) = ( PI ) & ( ( ( angle (p,p2,p3) ) + ( angle (p2,p3,p) ) ) + ( angle (p3,p,p2) ) ) = ( PI )) or (( ( ( angle (p,p2,p3) ) + ( angle (p,p3,p1) ) ) + ( angle (p3,p,p2) ) ) = ( 5 * ( PI ) ) & ( ( ( angle (p,p2,p3) ) + ( angle (p2,p3,p) ) ) + ( angle (p3,p,p2) ) ) = ( 5 * ( PI ) )));

hence thesis;
end;
suppose A18: (( ( ( angle (p,p2,p3) ) + ( angle (p,p3,p1) ) ) + ( angle (p3,p,p2) ) ) = ( PI ) & ( ( ( angle (p,p2,p3) ) + ( angle (p2,p3,p) ) ) + ( angle (p3,p,p2) ) ) = ( 5 * ( PI ) ));

(( angle (p2,p3,p) ) < ( 2 * ( PI ) ) & ( angle (p,p3,p1) ) >= ( 0 )) by COMPLEX2:70;
then A19: ( ( angle (p2,p3,p) ) - ( angle (p,p3,p1) ) ) < ( ( 2 * ( PI ) ) - ( 0 ) ) by XREAL_1:14;
( ( angle (p2,p3,p) ) - ( angle (p,p3,p1) ) ) = ( 4 * ( PI ) ) by A18;
hence thesis by A19,XREAL_1:64;
end;
suppose A20: (( ( ( angle (p,p2,p3) ) + ( angle (p,p3,p1) ) ) + ( angle (p3,p,p2) ) ) = ( 5 * ( PI ) ) & ( ( ( angle (p,p2,p3) ) + ( angle (p2,p3,p) ) ) + ( angle (p3,p,p2) ) ) = ( PI ));

(( angle (p,p3,p1) ) < ( 2 * ( PI ) ) & ( angle (p2,p3,p) ) >= ( 0 )) by COMPLEX2:70;
then A21: ( ( angle (p,p3,p1) ) - ( angle (p2,p3,p) ) ) < ( ( 2 * ( PI ) ) - ( 0 ) ) by XREAL_1:14;
( ( angle (p,p3,p1) ) - ( angle (p2,p3,p) ) ) = ( 4 * ( PI ) ) by A20;
hence thesis by A21,XREAL_1:64;
end;
end;
per cases ;
suppose A22: ( angle (p,p3,p1) ) = ( 0 );

then ( angle (p1,p3,p) ) = ( 0 ) by EUCLID_3:36;
hence thesis by A17,A22,EUCLID_3:36;
end;
suppose A23: ( angle (p,p3,p1) ) <> ( 0 );

then ( angle (p1,p3,p) ) = ( ( 2 * ( PI ) ) - ( angle (p,p3,p1) ) ) by EUCLID_3:37;
hence thesis by A17,A23,EUCLID_3:37;
end;
end;
suppose A24: p = p2;

then |. ( p3 - p1 ) .| = |. ( p - p3 ) .| by A1,CKB2:1
.= |. ( p3 - p ) .| by CKB2:1;
then ( ( |. ( p3 - p1 ) .| ^2 ) + ( |. ( p1 - p ) .| ^2 ) ) = ( |. ( p3 - p1 ) .| ^2 ) by A4,A5,A6,EUCLID_3:46;
then |. ( p1 - p ) .| = ( 0 );
hence thesis by A24,CKB1:1;
end;
end;
end;
