environ
vocabularies XXREAL_0,ORDINAL1,SUBSET_1,NUMBERS,MEMBERED,XBOOLE_0,XREAL_0,ARYTM_3,TARSKI,REAL_1,XXREAL_1;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,MEMBERED,XXREAL_0,REAL_1,XREAL_0,CKB2;
definitions TARSKI,XBOOLE_0,MEMBERED,CKB2;
theorems XBOOLE_0,XXREAL_0,XBOOLE_1,TARSKI,AXIOMS,SUBSET_1,XREAL_0,XREAL_1,MEMBERED,ZFMISC_1,CKB2;
schemes CKB1;
registrations XBOOLE_0,NUMBERS,XXREAL_0,XREAL_0,MEMBERED;
constructors NUMBERS,XXREAL_0,XREAL_0,MEMBERED,CKB2;
requirements SUBSET,BOOLE;
begin
reserve r for  ext-real number;
reserve s for  ext-real number;
reserve a for (Element of ( ExtREAL ));
definition
let r;
let s;
func [.r,s .[
equals
{ a: (r <= a & a < s) };
correctness;
end;
