environ
vocabularies NUMBERS,SUBSET_1,PRE_TOPC,EUCLID,TOPREAL1,RCOMP_1,FUNCT_1,BORSUK_1,RELAT_1,TOPS_2,CARD_1,XBOOLE_0,ORDINAL2,STRUCT_0,METRIC_1,XREAL_0,ORDINAL1,ARYTM_1,ARYTM_3,SUPINF_2,RLTOPSP1,REAL_1,XXREAL_1,TARSKI,XXREAL_0,PCOMPS_1,CONNSP_2,TOPMETR,TOPS_1,COMPLEX1,BORSUK_2,GRAPH_1,PARTFUN1,TMAP_1,FCONT_1,VALUED_0,SEQ_4,XXREAL_2,FUNCT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,XXREAL_2,REAL_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,SQUARE_1,FCONT_1,RFUNCT_2,TOPMETR,BINOP_1,RCOMP_1,TOPS_1,SEQ_4,METRIC_1,CONNSP_2,STRUCT_0,TOPREAL1,PRE_TOPC,TOPS_2,COMPTS_1,RLVECT_1,RLTOPSP1,EUCLID,TMAP_1,PCOMPS_1,WEIERSTR,BORSUK_2;
definitions TARSKI,BORSUK_2,XBOOLE_0,STRUCT_0,RLTOPSP1,XXREAL_2;
theorems BORSUK_1,BORSUK_2,COMPTS_1,CONNSP_2,EUCLID,FCONT_1,FCONT_2,FUNCT_1,FUNCT_2,GOBOARD7,GOBOARD9,METRIC_1,PARTFUN2,PCOMPS_1,PRE_TOPC,RCOMP_1,RELAT_1,RFUNCT_2,SEQ_4,TARSKI,TBSP_1,TMAP_1,TOPMETR,TOPREAL1,TOPS_2,TOPS_1,WEIERSTR,TOPREAL3,RELSET_1,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,XXREAL_2,XXREAL_1,MEMBERED,CKB1,CKB2,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
schemes CLASSES1;
registrations XBOOLE_0,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,RCOMP_1,STRUCT_0,PRE_TOPC,METRIC_1,BORSUK_1,EUCLID,TOPMETR,TOPREAL1,PSCOMP_1,BORSUK_2,VALUED_0,COMPTS_1,XXREAL_2,RLTOPSP1,FCONT_1,FUNCT_2,FUNCT_1,CKB6,CKB7;
constructors REAL_1,SQUARE_1,COMPLEX1,SEQ_4,RCOMP_1,RFUNCT_2,FCONT_1,TOPS_1,TOPS_2,COMPTS_1,TMAP_1,TOPREAL1,WEIERSTR,BORSUK_2,SEQ_1,XXREAL_2,RVSUM_1,FUNCSDOM,CONVEX1,BINOP_2;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
theorem
Th16: (for a,b,c,d being Real holds (for f being (Function of ( Closed-Interval-TSpace (a,b) ),( Closed-Interval-TSpace (c,d) )) holds (((((a < b & c < d) & f is  continuous  one-to-one) & ( f . a ) = c) & ( f . b ) = d) implies (for x,y being (Point of ( Closed-Interval-TSpace (a,b) )) holds (for p,q,fx,fy being Real holds (((((x = p & y = q) & p < q) & fx = ( f . x )) & fy = ( f . y )) implies fx < fy))))))
proof
let a being Real,b being Real,c being Real,d being Real;
let f being (Function of ( Closed-Interval-TSpace (a,b) ),( Closed-Interval-TSpace (c,d) ));
assume that
A1: a < b
and
A2: c < d
and
A3: f is  continuous  one-to-one
and
A4: (( f . a ) = c & ( f . b ) = d);
A5: [. a,b .] = (the carrier of ( Closed-Interval-TSpace (a,b) )) by A1,TOPMETR:18;
A6: ( dom f ) = (the carrier of ( Closed-Interval-TSpace (a,b) )) by FUNCT_2:def 1;
( rng f ) c= ( REAL ) by MEMBERED:3;
then reconsider g = f as (PartFunc of [. a,b .],( REAL )) by A5,A6,RELSET_1:4;
reconsider g as (PartFunc of ( REAL ),( REAL )) by A5,A6,RELSET_1:5;
A7: ( g | [. a,b .] ) is  continuous by A1,A2,A3,A4,CKB23:1;
A8: ( [. a,b .] /\ ( dom f ) ) = ( [. a,b .] /\ (the carrier of ( Closed-Interval-TSpace (a,b) )) ) by FUNCT_2:def 1
.= [. a,b .] by A5;
per cases  by A1,A3,A8,A7,FCONT_2:17,XBOOLE_1:18;
suppose A9: ( g | [. a,b .] ) is  increasing;

(for x,y being (Point of ( Closed-Interval-TSpace (a,b) )) holds (for p,q,fx,fy being Real holds (((((x = p & y = q) & p < q) & fx = ( f . x )) & fy = ( f . y )) implies fx < fy)))
proof
let x being (Point of ( Closed-Interval-TSpace (a,b) )),y being (Point of ( Closed-Interval-TSpace (a,b) ));
let p being Real,q being Real,fx being Real,fy being Real;
assume that
A10: x = p
and
A11: y = q
and
A12: ((p < q & fx = ( f . x )) & fy = ( f . y ));
y in (the carrier of ( Closed-Interval-TSpace (a,b) ));
then A13: q in ( [. a,b .] /\ ( dom g ) ) by A1,A8,A11,TOPMETR:18;
x in (the carrier of ( Closed-Interval-TSpace (a,b) ));
then p in ( [. a,b .] /\ ( dom g ) ) by A1,A8,A10,TOPMETR:18;
hence thesis by A9,A10,A11,A12,A13,RFUNCT_2:20;
end;
hence thesis;
end;
suppose A14: ( g | [. a,b .] ) is  decreasing;

(a in ( [. a,b .] /\ ( dom g ) ) & b in ( [. a,b .] /\ ( dom g ) )) by A1,A5,A8,CKB20:1;
hence thesis by A1,A2,A4,A14,RFUNCT_2:21;
end;
end;
