environ
vocabularies NUMBERS,XBOOLE_0,MSUALG_1,SUBSET_1,FUNCT_1,PBOOLE,MEMBER_1,RELAT_1,STRUCT_0,CARD_3,MARGREL1,PARTFUN1,MOD_4,MSUALG_3,NAT_1,FUNCT_4,RLTOPSP1,TARSKI,REWRITE1,FUNCOP_1,FINSEQ_1,ARYTM_3,FUNCT_7,CARD_1,XXREAL_0,ORDINAL4,MSUALG_4,CIRCUIT2,MCART_1,ZFMISC_1,EQREL_1,RELAT_2,MSUALG_5,MSUALG_6;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,NAT_1,MCART_1,STRUCT_0,RELAT_1,RELAT_2,RELSET_1,EQREL_1,REWRITE1,FUNCT_1,PBOOLE,PARTFUN1,FUNCT_2,FINSEQ_1,CARD_3,FUNCOP_1,MSUALG_1,MSUALG_3,MSUALG_4,MSUALG_5,FUNCT_7,XXREAL_0,CKB1,CKB2,CKB5,CKB9,CKB13,CKB14,CKB18,CKB20,CKB25,CKB39,CKB40,CKB41,CKB49,CKB53,CKB56,CKB59,CKB73,CKB74;
definitions TARSKI,RELAT_1,REWRITE1,FUNCT_1,PBOOLE,MSUALG_3,MSUALG_4,FUNCT_7,FUNCOP_1,CKB5,CKB9,CKB14,CKB18,CKB20,CKB25,CKB39,CKB40,CKB41,CKB49,CKB53,CKB56,CKB59,CKB74;
theorems TARSKI,NAT_1,MCART_1,ZFMISC_1,RELAT_1,RELSET_1,EQREL_1,FUNCT_1,FINSEQ_1,FINSEQ_3,FUNCT_2,CARD_3,FUNCT_7,REWRITE1,PBOOLE,PRALG_2,MSUALG_3,MSUALG_4,MSUALG_5,FINSEQ_5,XBOOLE_0,PARTFUN1,RELAT_2,ORDERS_1,XREAL_1,XXREAL_0,ORDINAL1,CKB3,CKB4,CKB5,CKB6,CKB9,CKB10,CKB11,CKB12,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB49,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB74,CKB75,CKB76,CKB77,CKB78;
schemes NAT_1,RECDEF_1,RELSET_1,FUNCT_1,FINSEQ_1,CARD_3,CLASSES1,PBOOLE,PUA2MSS1,CKB32,CKB47,CKB48,CKB52;
registrations XBOOLE_0,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,FUNCOP_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,PBOOLE,REWRITE1,FUNCT_7,STRUCT_0,MSUALG_1,MSUALG_3,MSUALG_4,MSUALG_5,ORDINAL1,CARD_1,RELSET_1,CKB7,CKB8,CKB44,CKB45,CKB46,CKB50,CKB51,CKB60,CKB61,CKB62,CKB79;
constructors XXREAL_0,NAT_1,NAT_D,REWRITE1,FUNCT_7,MSUALG_3,MSUALG_5,RELSET_1,CKB2,CKB5,CKB9,CKB13,CKB14,CKB18,CKB20,CKB25,CKB39,CKB40,CKB41,CKB49,CKB53,CKB56,CKB59,CKB74;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve S for non  empty non  void ManySortedSign;
reserve A for  non-empty MSAlgebra over S;
reserve R for (ManySortedRelation of (the Sorts of A));
theorem
Th47: (for R being  invariant (ManySortedRelation of A) holds (for s1,s2 being (SortSymbol of S) holds (for a,b being (Element of A,s1) holds (a,b are_convertible_wrt ( R . s1 ) implies (for t being Function holds (t is_e.translation_of A,s1,s2 implies ( t . a ),( t . b ) are_convertible_wrt ( R . s2 )))))))
proof
let R being  invariant (ManySortedRelation of A);
let s1 being (SortSymbol of S);
let s2 being (SortSymbol of S);
let a being (Element of A,s1);
let b being (Element of A,s1);
assume ( ( R . s1 ) \/ ( ( R . s1 ) ~ ) ) reduces a,b;
then consider p being (RedSequence of ( ( R . s1 ) \/ ( ( R . s1 ) ~ ) )) such that A1: ( p . 1 ) = a and A2: ( p . ( len p ) ) = b by REWRITE1:def 3;
let t being Function;
assume that
A3: t is_e.translation_of A,s1,s2;
defpred P[ (Element of ( NAT )) ]
 means
($1 in ( dom p ) implies ( t . a ),( t . ( p . $1 ) ) are_convertible_wrt ( R . s2 ));
A4: (for i being (Element of ( NAT )) holds (P[ i ] implies P[ ( i + 1 ) ]))
proof
let i being (Element of ( NAT ));
assume that
A5: (i in ( dom p ) implies ( t . a ),( t . ( p . i ) ) are_convertible_wrt ( R . s2 ))
and
A6: ( i + 1 ) in ( dom p );
A7: i <= ( i + 1 ) by NAT_1:11;
( i + 1 ) <= ( len p ) by A6,FINSEQ_3:25;
then A8: i <= ( len p ) by A7,XXREAL_0:2;
per cases ;
suppose i = ( 0 );

hence thesis by A1,REWRITE1:26;
end;
suppose i > ( 0 );

then A9: i >= ( ( 0 ) + 1 ) by NAT_1:13;
then i in ( dom p ) by A8,FINSEQ_3:25;
then A10: [ ( p . i ),( p . ( i + 1 ) ) ] in ( ( R . s1 ) \/ ( ( R . s1 ) ~ ) ) by A6,REWRITE1:def 2;
then reconsider ppi = ( p . i ),pj = ( p . ( i + 1 ) ) as (Element of A,s1) by ZFMISC_1:87;
([ ( p . i ),( p . ( i + 1 ) ) ] in ( R . s1 ) or [ ( p . i ),( p . ( i + 1 ) ) ] in ( ( R . s1 ) ~ )) by A10,XBOOLE_0:def 3;
then ([ ( p . i ),( p . ( i + 1 ) ) ] in ( R . s1 ) or [ ( p . ( i + 1 ) ),( p . i ) ] in ( R . s1 )) by RELAT_1:def 7;
then ([ ( t . ppi ),( t . pj ) ] in ( R . s2 ) or [ ( t . pj ),( t . ppi ) ] in ( R . s2 )) by A3,CKB40:def 1;
then (( t . ppi ),( t . pj ) are_convertible_wrt ( R . s2 ) or ( t . pj ),( t . ppi ) are_convertible_wrt ( R . s2 )) by REWRITE1:29;
then ( t . ppi ),( t . pj ) are_convertible_wrt ( R . s2 ) by REWRITE1:31;
hence thesis by A5,A8,A9,FINSEQ_3:25,REWRITE1:30;
end;
end;
A11: ( len p ) in ( dom p ) by FINSEQ_5:6;
A12: P[ ( 0 ) ] by FINSEQ_3:25;
(for i being (Element of ( NAT )) holds P[ i ]) from NAT_1:sch 1(A12,A4);
hence thesis by A2,A11;
end;
