environ
vocabularies RELAT_2,ALTCAT_1,XBOOLE_0,MSUALG_6,FUNCTOR0,CAT_1,FUNCT_1,PZFMISC1,NATTRA_1,PBOOLE,STRUCT_0,SUBSET_1,REALSET1,RELAT_1,FUNCT_2,CARD_3,CAT_2,ZFMISC_1,TARSKI,FUNCTOR2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,FUNCTOR0,MCART_1,DOMAIN_1,RELAT_1,STRUCT_0,CARD_3,FUNCT_1,PBOOLE,FUNCT_2,BINOP_1,MULTOP_1,ALTCAT_1,CKB7,CKB9,CKB10,CKB11,CKB12;
definitions ALTCAT_1,BINOP_1,CKB7,CKB9,CKB10,CKB11,CKB12;
theorems MCART_1,MULTOP_1,FUNCT_2,ZFMISC_1,ALTCAT_1,PBOOLE,BINOP_1,TARSKI,ALTCAT_2,FUNCTOR0,CARD_3,XBOOLE_0,PARTFUN1,RELAT_1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes TARSKI,PBOOLE,MSSUBFAM,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,ALTCAT_1,FUNCTOR0,PBOOLE,FUNCT_1,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5;
constructors DOMAIN_1,CARD_3,FUNCTOR0,RELSET_1,CKB7,CKB9,CKB10,CKB11,CKB12;
requirements SUBSET,BOOLE;
begin
theorem
Th8: (for A,B being category holds (for F,F1,F2,F3 being (Functor of A,B) holds (((F is_transformable_to F1 & F1 is_transformable_to F2) & F2 is_transformable_to F3) implies (for t1 being (transformation of F,F1) holds (for t2 being (transformation of F1,F2) holds (for t3 being (transformation of F2,F3) holds ( ( t3 `*` t2 ) `*` t1 ) = ( t3 `*` ( t2 `*` t1 ) )))))))
proof
let A being category,B being category;
let F being (Functor of A,B),F1 being (Functor of A,B),F2 being (Functor of A,B),F3 being (Functor of A,B);
assume that
A1: F is_transformable_to F1
and
A2: F1 is_transformable_to F2
and
A3: F2 is_transformable_to F3;
let t1 being (transformation of F,F1);
let t2 being (transformation of F1,F2);
let t3 being (transformation of F2,F3);
A4: F1 is_transformable_to F3 by A2,A3,CKB8:1;
A5: F is_transformable_to F2 by A1,A2,CKB8:1;
now
let a being (object of A);
A6: <^ ( F2 . a ),( F3 . a ) ^> <> ( {} ) by A3,CKB7:def 1;
A7: (<^ ( F . a ),( F1 . a ) ^> <> ( {} ) & <^ ( F1 . a ),( F2 . a ) ^> <> ( {} )) by A1,A2,CKB7:def 1;
thus ( ( ( t3 `*` t2 ) `*` t1 ) ! a ) = ( ( ( t3 `*` t2 ) ! a ) * ( t1 ! a ) ) by A1,A4,CKB12:def 1
.= ( ( ( t3 ! a ) * ( t2 ! a ) ) * ( t1 ! a ) ) by A2,A3,CKB12:def 1
.= ( ( t3 ! a ) * ( ( t2 ! a ) * ( t1 ! a ) ) ) by A7,A6,ALTCAT_1:21
.= ( ( t3 ! a ) * ( ( t2 `*` t1 ) ! a ) ) by A1,A2,CKB12:def 1
.= ( ( t3 `*` ( t2 `*` t1 ) ) ! a ) by A3,A5,CKB12:def 1;
end;
hence thesis by A1,A4,CKB8:1,CKB13:1;
end;
