environ
vocabularies TARSKI,XBOOLE_0,SUBSET_1,FUNCT_1,RELAT_1,ZFMISC_1,ORDINAL1;
notations TARSKI,XBOOLE_0,ZFMISC_1,ENUMSET1,SUBSET_1,RELAT_1,FUNCT_1,CKB6,CKB12,CKB13,CKB15,CKB18,CKB20,CKB26;
definitions TARSKI,XBOOLE_0,RELAT_1,FUNCT_1,CKB6,CKB12,CKB13,CKB15,CKB26;
theorems TARSKI,XBOOLE_0,FUNCT_1,ZFMISC_1,ENUMSET1,RELAT_1,XBOOLE_1,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB30;
schemes XBOOLE_0,FUNCT_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,CKB7,CKB16,CKB17,CKB19,CKB29;
constructors TARSKI,ENUMSET1,SUBSET_1,FUNCT_1,CKB6,CKB12,CKB13,CKB15,CKB26;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve x for set;
reserve y for set;
reserve z for set;
theorem
Th30: (x is  ordinal implies ( union x ) is  ordinal)
proof
assume (x is  epsilon-transitive & x is  epsilon-connected);
then reconsider A = x as Ordinal;
thus (y in ( union x ) implies y c= ( union x ))
proof
assume y in ( union x );
then consider z such that A1: y in z and A2: z in x by TARSKI:def 4;
z in A by A2;
then reconsider z as Ordinal by CKB24:1;
z c= A by A2,CKB12:def 1;
hence thesis by A1,ZFMISC_1:74;
end;

let y;
let z;
assume that
A3: y in ( union x )
and
A4: z in ( union x );
consider X such that A5: y in X and A6: X in x by A3,TARSKI:def 4;
A7: X in A by A6;
consider Y such that A8: z in Y and A9: Y in x by A4,TARSKI:def 4;
reconsider X,Y as Ordinal by A9,A7,CKB24:1;
z in Y by A8;
then A10: z is Ordinal by CKB24:1;
y in X by A5;
then y is Ordinal by CKB24:1;
hence thesis by A10,CKB25:1;
end;
