environ
vocabularies TARSKI,XBOOLE_0,SUBSET_1,FUNCT_1,RELAT_1,ZFMISC_1,ORDINAL1;
notations TARSKI,XBOOLE_0,ZFMISC_1,ENUMSET1,SUBSET_1,RELAT_1,FUNCT_1,CKB6,CKB12,CKB13,CKB15,CKB18,CKB20,CKB26,CKB46,CKB49,CKB51,CKB53,CKB60;
definitions TARSKI,XBOOLE_0,RELAT_1,FUNCT_1,CKB6,CKB12,CKB13,CKB15,CKB26,CKB46,CKB49,CKB60;
theorems TARSKI,XBOOLE_0,FUNCT_1,ZFMISC_1,ENUMSET1,RELAT_1,XBOOLE_1,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB30,CKB31,CKB35,CKB36,CKB37,CKB38,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB54,CKB55,CKB57,CKB59,CKB60,CKB61;
schemes XBOOLE_0,FUNCT_1,CKB39,CKB40;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,CKB7,CKB16,CKB17,CKB19,CKB29,CKB32,CKB33,CKB34,CKB50,CKB52,CKB56,CKB58;
constructors TARSKI,ENUMSET1,SUBSET_1,FUNCT_1,CKB6,CKB12,CKB13,CKB15,CKB26,CKB46,CKB49,CKB60;
requirements SUBSET,BOOLE;
begin
reserve a for set;
reserve b for set;
reserve X for set;
reserve x for set;
reserve A for Ordinal;
reserve B for Ordinal;
reserve C for Ordinal;
reserve L for T-Sequence;
reserve L1 for T-Sequence;
scheme TSUniq { A() -> Ordinal,H(T-Sequence) -> set,L1,L2() -> T-Sequence } : L1() = L2()
provided
A1: (( dom L1() ) = A() & (for B holds (for L holds ((B in A() & L = ( L1() | B )) implies ( L1() . B ) = H(L)))))
and
A2: (( dom L2() ) = A() & (for B holds (for L holds ((B in A() & L = ( L2() | B )) implies ( L2() . B ) = H(L)))))
proof
defpred P[ set ]
 means
( L1() . $1 ) <> ( L2() . $1 );
consider X such that A3: (x in X iff (x in A() & P[ x ])) from XBOOLE_0:sch 1;
(for b holds (b in X implies b in A())) by A3;
then A4: X c= A() by TARSKI:def 3;
assume L1() <> L2();
then (ex a st (a in A() & ( L1() . a ) <> ( L2() . a ))) by A1,A2,FUNCT_1:2;
then X <> ( {} ) by A3;
then consider B such that A5: B in X and A6: (for C holds (C in X implies B c= C)) by A4,CKB36:1;
A7: B in A() by A3,A5;
then A8: B c= A() by CKB12:def 1;
then A9: ( dom ( L1() | B ) ) = B by A1,RELAT_1:62;
A10: ( dom ( L2() | B ) ) = B by A2,A8,RELAT_1:62;
A11:now
let C;
assume A12: C in B;
then (not C in X) by A6,CKB5:1;
hence ( L1() . C ) = ( L2() . C ) by A3,A8,A12;
end;
now
let a;
assume A13: a in B;
then reconsider a9 = a as Ordinal by CKB24:1;
(( L1() . a9 ) = ( L2() . a9 ) & ( ( L1() | B ) . a ) = ( L1() . a )) by A11,A9,A13,FUNCT_1:47;
hence ( ( L1() | B ) . a ) = ( ( L2() | B ) . a ) by A10,A13,FUNCT_1:47;
end;
then A14: ( L1() | B ) = ( L2() | B ) by A9,A10,FUNCT_1:2;
(( L1() . B ) = H(( L1() | B )) & ( L2() . B ) = H(( L2() | B ))) by A1,A2,A7;
hence contradiction by A3,A5,A14;
end;
