environ
vocabularies NUMBERS,XBOOLE_0,NAT_1,XCMPLX_0,VECTSP_1,SUBSET_1,FINSEQ_1,MATRIX_1,CARD_1,TREES_1,XXREAL_0,MATRIX_2,QC_LANG1,RELAT_1,SUPINF_2,ARYTM_3,MATRIX_3,FUNCT_1,ZFMISC_1,FINSEQ_2,FUNCT_2,ARYTM_1,FINSET_1,TARSKI,SGRAPH1,CARD_3,ALGSTR_0,SETWISEO,ABIAN,FINSUB_1,BINOP_1,FINSOP_1,CARD_FIN,FUNCOP_1,FUNCT_4,MATRIX11,FINSEQ_5,INT_1,GROUP_1,ABSVALUE,RVSUM_1,STRUCT_0,INCSP_1,FVSUM_1,FREEALG,FINSEQ_3,LAPLACE,CLASSES1,AFINSQ_1,PRVECT_1,RLVECT_2,LMOD_7,VALUED_1,PARTFUN1,RLVECT_3,RLSUB_1,MESFUNC1,RLVECT_5,MATRIX13,RLVECT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,NAT_D,FINSET_1,RELAT_1,RELSET_1,FUNCT_1,PARTFUN1,FUNCT_2,SETWOP_2,FINSEQ_1,BINOP_1,STRUCT_0,ALGSTR_0,FUNCOP_1,RLVECT_1,GROUP_1,VECTSP_1,SETWISEO,FINSEQ_2,MATRIX_1,FINSUB_1,MATRIX_2,FVSUM_1,FINSOP_1,GROUP_4,MATRIX_3,FINSEQ_7,FUNCT_4,SGRAPH1,NEWTON,FINSEQ_5,DOMAIN_1,MATRIX_6,MATRIX_7,MATRIX11,CARD_FIN,FINSEQ_3,LAPLACE,MEASURE6,PRVECT_1,VECTSP_4,VECTSP_6,VECTSP_7,MATRLIN,VECTSP_9,FINSEQOP;
definitions RLVECT_1,FINSEQ_2,FINSEQ_1,TARSKI,MATRIX_1,FVSUM_1,GROUP_4,MATRIX_2,MATRIX_3,MATRIX_7,MATRIX11,LAPLACE,MEASURE6,VECTSP_1,VECTSP_7,FUNCT_1,RELAT_1,STRUCT_0,ALGSTR_0,FUNCOP_1;
theorems NAT_D,CARD_1,CARD_2,CARD_FIN,COMPUT_1,ENUMSET1,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,FINSEQ_5,FINSOP_1,FINSUB_1,FRECHET,FUNCT_1,FUNCT_2,FUNCT_4,FUNCT_7,FUNCOP_1,FVSUM_1,GRAPH_2,GRAPH_5,GROUP_1,LAPLACE,MATRIX_1,MATRIX_2,MATRIX_3,MATRIX_7,MATRIX_9,MATRIX11,MATRIXR1,NAT_1,ORDINAL1,PRVECT_1,RELAT_1,RLVECT_1,SETWISEO,SETWOP_2,SGRAPH1,STIRL2_1,TARSKI,VECTSP_1,VECTSP_2,VECTSP_4,VECTSP_6,VECTSP_7,VECTSP_9,VECTSP10,WELLORD2,XBOOLE_0,XBOOLE_1,XREAL_1,ZFMISC_1,XXREAL_0,FINSEQOP,STRUCT_0,MATRIXR2,PARTFUN1,MATRLIN,XREAL_0,MEASURE6,CKB1,CKB2,CKB3,CKB4;
schemes FINSEQ_1,FINSEQ_2,FUNCT_1,FUNCT_2,NAT_1,PRE_POLY,MATRIX_1;
registrations SUBSET_1,FUNCT_1,FINSET_1,STRUCT_0,FVSUM_1,MATRIX_2,VECTSP_1,FUNCT_2,ORDINAL1,XXREAL_0,NAT_1,FINSEQ_1,RELAT_1,CARD_1,SGRAPH1,MATRIX_1,FUNCOP_1,MATRIX11,SETFAM_1,FINSEQ_2,PRVECT_1,MATRLIN,XREAL_0,XBOOLE_0,VALUED_0,VECTSP_7,RELSET_1;
constructors SETWISEO,FINSOP_1,ALGSTR_1,FVSUM_1,DOMAIN_1,SEQM_3,XXREAL_0,FINSEQ_5,GROUP_4,FINSEQ_7,WELLORD2,NEWTON,STIRL2_1,CARD_FIN,MATRIX_6,MATRIX_7,MATRIX11,LAPLACE,PRVECT_1,VECTSP_6,VECTSP_7,VECTSP_9,NAT_D,BINOP_2,MATRLIN,VALUED_0,RELSET_1,MEASURE6,SETFAM_1;
requirements ARITHM,NUMERALS,REAL,BOOLE,SUBSET;
begin
reserve i for Nat;
reserve n for Nat;
reserve K for Field;
reserve p for (FinSequence of K);
reserve M for (Matrix of n,K);
theorem
Th5: (for M being (Matrix of n,K) holds (for perm being (Element of ( Permutations n )) holds ((perm <> ( idseq n ) & (M is (Lower_Triangular_Matrix of n,K) or M is (Upper_Triangular_Matrix of n,K))) implies ( ( Path_product M ) . perm ) = ( 0. K ))))
proof
let M being (Matrix of n,K);
let p being (Element of ( Permutations n ));
assume that
A1: p <> ( idseq n )
and
A2: (M is (Lower_Triangular_Matrix of n,K) or M is (Upper_Triangular_Matrix of n,K));
reconsider p9 = p as (Permutation of ( Seg n )) by MATRIX_2:def 9;
set PP = ( Path_product M );
set PATH = ( Path_matrix (p,M) );
now
per cases  by A2;
suppose A3: M is (Lower_Triangular_Matrix of n,K);

A4: ( rng p9 ) = ( Seg n ) by FUNCT_2:def 3;
A5: ( Indices M ) = [: ( Seg n ),( Seg n ) :] by MATRIX_1:24;
consider i such that A6: i in ( Seg n ) and A7: ( p . i ) > i by A1,CKB4:1;
reconsider Pi = ( p . i ) as Nat;
( dom p9 ) = ( Seg n ) by FUNCT_2:52;
then ( p9 . i ) in ( Seg n ) by A6,A4,FUNCT_1:def 3;
then [ i,Pi ] in [: ( Seg n ),( Seg n ) :] by A6,ZFMISC_1:87;
then A8: ( M * (i,Pi) ) = ( 0. K ) by A3,A7,A5,MATRIX_2:def 4;
( len PATH ) = n by MATRIX_3:def 7;
then A9: ( dom PATH ) = ( Seg n ) by FINSEQ_1:def 3;
then ( PATH . i ) = ( M * (i,Pi) ) by A6,MATRIX_3:def 7;
hence (ex i st (i in ( dom PATH ) & ( PATH . i ) = ( 0. K ))) by A6,A9,A8;
end;
suppose A10: M is (Upper_Triangular_Matrix of n,K);

A11: ( rng p9 ) = ( Seg n ) by FUNCT_2:def 3;
A12: ( Indices M ) = [: ( Seg n ),( Seg n ) :] by MATRIX_1:24;
consider i such that A13: i in ( Seg n ) and A14: ( p . i ) < i by A1,CKB4:1;
reconsider Pi = ( p . i ) as Nat;
( dom p9 ) = ( Seg n ) by FUNCT_2:52;
then ( p9 . i ) in ( Seg n ) by A13,A11,FUNCT_1:def 3;
then [ i,Pi ] in [: ( Seg n ),( Seg n ) :] by A13,ZFMISC_1:87;
then A15: ( M * (i,Pi) ) = ( 0. K ) by A10,A14,A12,MATRIX_2:def 3;
( len PATH ) = n by MATRIX_3:def 7;
then A16: ( dom PATH ) = ( Seg n ) by FINSEQ_1:def 3;
then ( PATH . i ) = ( M * (i,Pi) ) by A13,MATRIX_3:def 7;
hence (ex i st (i in ( dom PATH ) & ( PATH . i ) = ( 0. K ))) by A13,A16,A15;
end;
end;
then ( Product PATH ) = ( 0. K ) by FVSUM_1:82;
then A17: ( PP . p ) = ( - (( 0. K ),p) ) by MATRIX_3:def 8;
(( - (( 0. K ),p) ) = ( 0. K ) or ( - (( 0. K ),p) ) = ( - ( 0. K ) )) by MATRIX_2:def 13;
hence thesis by A17,RLVECT_1:12;
end;
