environ
vocabularies NUMBERS,XBOOLE_0,NAT_1,XCMPLX_0,VECTSP_1,SUBSET_1,FINSEQ_1,MATRIX_1,CARD_1,TREES_1,XXREAL_0,MATRIX_2,QC_LANG1,RELAT_1,SUPINF_2,ARYTM_3,MATRIX_3,FUNCT_1,ZFMISC_1,FINSEQ_2,FUNCT_2,ARYTM_1,FINSET_1,TARSKI,SGRAPH1,CARD_3,ALGSTR_0,SETWISEO,ABIAN,FINSUB_1,BINOP_1,FINSOP_1,CARD_FIN,FUNCOP_1,FUNCT_4,MATRIX11,FINSEQ_5,INT_1,GROUP_1,ABSVALUE,RVSUM_1,STRUCT_0,INCSP_1,FVSUM_1,FREEALG,FINSEQ_3,LAPLACE,CLASSES1,AFINSQ_1,PRVECT_1,RLVECT_2,LMOD_7,VALUED_1,PARTFUN1,RLVECT_3,RLSUB_1,MESFUNC1,RLVECT_5,MATRIX13,RLVECT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,NAT_D,FINSET_1,RELAT_1,RELSET_1,FUNCT_1,PARTFUN1,FUNCT_2,SETWOP_2,FINSEQ_1,BINOP_1,STRUCT_0,ALGSTR_0,FUNCOP_1,RLVECT_1,GROUP_1,VECTSP_1,SETWISEO,FINSEQ_2,MATRIX_1,FINSUB_1,MATRIX_2,FVSUM_1,FINSOP_1,GROUP_4,MATRIX_3,FINSEQ_7,FUNCT_4,SGRAPH1,NEWTON,FINSEQ_5,DOMAIN_1,MATRIX_6,MATRIX_7,MATRIX11,CARD_FIN,FINSEQ_3,LAPLACE,MEASURE6,PRVECT_1,VECTSP_4,VECTSP_6,VECTSP_7,MATRLIN,VECTSP_9,FINSEQOP,CKB17,CKB43,CKB50,CKB51,CKB53,CKB54,CKB76;
definitions RLVECT_1,FINSEQ_2,FINSEQ_1,TARSKI,MATRIX_1,FVSUM_1,GROUP_4,MATRIX_2,MATRIX_3,MATRIX_7,MATRIX11,LAPLACE,MEASURE6,VECTSP_1,VECTSP_7,FUNCT_1,RELAT_1,STRUCT_0,ALGSTR_0,FUNCOP_1,CKB17,CKB54,CKB76;
theorems NAT_D,CARD_1,CARD_2,CARD_FIN,COMPUT_1,ENUMSET1,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,FINSEQ_5,FINSOP_1,FINSUB_1,FRECHET,FUNCT_1,FUNCT_2,FUNCT_4,FUNCT_7,FUNCOP_1,FVSUM_1,GRAPH_2,GRAPH_5,GROUP_1,LAPLACE,MATRIX_1,MATRIX_2,MATRIX_3,MATRIX_7,MATRIX_9,MATRIX11,MATRIXR1,NAT_1,ORDINAL1,PRVECT_1,RELAT_1,RLVECT_1,SETWISEO,SETWOP_2,SGRAPH1,STIRL2_1,TARSKI,VECTSP_1,VECTSP_2,VECTSP_4,VECTSP_6,VECTSP_7,VECTSP_9,VECTSP10,WELLORD2,XBOOLE_0,XBOOLE_1,XREAL_1,ZFMISC_1,XXREAL_0,FINSEQOP,STRUCT_0,MATRIXR2,PARTFUN1,MATRLIN,XREAL_0,MEASURE6,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB44,CKB45,CKB52,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80;
schemes FINSEQ_1,FINSEQ_2,FUNCT_1,FUNCT_2,NAT_1,PRE_POLY,MATRIX_1;
registrations SUBSET_1,FUNCT_1,FINSET_1,STRUCT_0,FVSUM_1,MATRIX_2,VECTSP_1,FUNCT_2,ORDINAL1,XXREAL_0,NAT_1,FINSEQ_1,RELAT_1,CARD_1,SGRAPH1,MATRIX_1,FUNCOP_1,MATRIX11,SETFAM_1,FINSEQ_2,PRVECT_1,MATRLIN,XREAL_0,XBOOLE_0,VALUED_0,VECTSP_7,RELSET_1,CKB46,CKB47,CKB48,CKB49;
constructors SETWISEO,FINSOP_1,ALGSTR_1,FVSUM_1,DOMAIN_1,SEQM_3,XXREAL_0,FINSEQ_5,GROUP_4,FINSEQ_7,WELLORD2,NEWTON,STIRL2_1,CARD_FIN,MATRIX_6,MATRIX_7,MATRIX11,LAPLACE,PRVECT_1,VECTSP_6,VECTSP_7,VECTSP_9,NAT_D,BINOP_2,MATRLIN,VALUED_0,RELSET_1,MEASURE6,SETFAM_1,CKB17,CKB43,CKB50,CKB51,CKB53,CKB54,CKB76;
requirements ARITHM,NUMERALS,REAL,BOOLE,SUBSET;
begin
reserve x for set;
reserve i for Nat;
reserve j for Nat;
reserve k for Nat;
reserve n for Nat;
reserve K for Field;
reserve M for (Matrix of K);
reserve P for  without_zero  finite (Subset of ( NAT ));
reserve P1 for  without_zero  finite (Subset of ( NAT ));
reserve P2 for  without_zero  finite (Subset of ( NAT ));
reserve Q for  without_zero  finite (Subset of ( NAT ));
reserve Q1 for  without_zero  finite (Subset of ( NAT ));
theorem
(for M holds (for P1 holds (for Q holds (for Q1 holds (((( card P1 ) = ( card Q1 ) & Q c= Q1) & ( Det ( EqSegm (M,P1,Q1) ) ) <> ( 0. K )) implies (ex P st ((P c= P1 & ( card P ) = ( card Q )) & ( Det ( EqSegm (M,P,Q) ) ) <> ( 0. K ))))))))
proof
let M;
let P1;
let Q;
let Q1;
assume that
A1: ( card P1 ) = ( card Q1 )
and
A2: Q c= Q1
and
A3: ( Det ( EqSegm (M,P1,Q1) ) ) <> ( 0. K );
defpred R[ Nat ]
 means
(for Q holds ((Q c= Q1 & ( card Q ) = $1) implies (ex P st ((P c= P1 & ( card P ) = ( card Q )) & ( Det ( EqSegm (M,P,Q) ) ) <> ( 0. K )))));
A4: (for k being (Element of ( NAT )) holds ((k < ( card Q1 ) & R[ ( k + 1 ) ]) implies R[ k ]))
proof
let k being (Element of ( NAT ));
assume that
A5: k < ( card Q1 )
and
A6: R[ ( k + 1 ) ];
let Q;
assume that
A7: Q c= Q1
and
A8: ( card Q ) = k;
Q c< Q1 by A5,A7,A8,XBOOLE_0:def 8;
then ( Q1 \ Q ) <> ( {} ) by XBOOLE_1:105;
then consider x such that A9: x in ( Q1 \ Q ) by XBOOLE_0:def 1;
reconsider x as non  zero (Element of ( NAT )) by A9;
reconsider Qx = ( Q \/ { x } ) as  without_zero  finite (Subset of ( NAT ));
A10: (not x in Q) by A9,XBOOLE_0:def 5;
then A11: ( card Qx ) = ( k + 1 ) by A8,CARD_2:41;
x in Q1 by A9,XBOOLE_0:def 5;
then { x } c= Q1 by ZFMISC_1:31;
then Qx c= Q1 by A7,XBOOLE_1:8;
then consider P2 such that A12: P2 c= P1 and A13: ( card Qx ) = ( card P2 ) and A14: ( Det ( EqSegm (M,P2,Qx) ) ) <> ( 0. K ) by A6,A8,A10,CARD_2:41;
A15: ( ( k + 1 ) -' 1 ) = ( ( k + 1 ) - 1 ) by XREAL_0:def 2;
x in { x } by TARSKI:def 1;
then A16: x in Qx by XBOOLE_0:def 3;
A17: (ex n st Qx c= ( Seg n )) by CKB52:1;
then A18: ( dom ( Sgm Qx ) ) = ( Seg ( card Qx ) ) by FINSEQ_3:40;
( rng ( Sgm Qx ) ) = Qx by A17,FINSEQ_1:def 13;
then consider j being set such that A19: j in ( Seg ( card Qx ) ) and A20: ( ( Sgm Qx ) . j ) = x by A18,A16,FUNCT_1:def 3;
set E = ( EqSegm (M,P2,Qx) );
reconsider j as (Element of ( NAT )) by A19;
consider i such that A21: i in ( Seg ( card Qx ) ) and A22: ( Det ( Delete (E,i,j) ) ) <> ( 0. K ) by A13,A14,A19,CKB80:1;
take P = ( P2 \ { ( ( Sgm P2 ) . i ) } );
A23: P c= P2 by XBOOLE_1:36;
A24: ( Qx \ { x } ) = Q by A10,ZFMISC_1:117;
then ( card P ) = ( card Q ) by A13,A19,A20,A21,CKB77:1;
hence thesis by A8,A11,A12,A13,A19,A20,A21,A22,A24,A23,A15,CKB77:1,XBOOLE_1:1;
end;
A25: R[ ( card Q1 ) ]
proof
let Q;
assume that
A26: Q c= Q1
and
A27: ( card Q ) = ( card Q1 );
Q = Q1 by A26,A27,CARD_FIN:1;
hence thesis by A1,A3;
end;
(for k being (Element of ( NAT )) holds (k <= ( card Q1 ) implies R[ k ])) from PRE_POLY:sch 1(A25,A4);
hence thesis by A2,NAT_1:43;
end;
