environ
vocabularies NUMBERS,SUBSET_1,PRE_TOPC,EUCLID,ARYTM_3,STRUCT_0,REALSET1,ARYTM_1,VALUED_2,TARSKI,SUPINF_2,XBOOLE_0,XREAL_0,ORDINAL1,RELAT_1,CARD_1,MONOID_0,RLVECT_1,CONVEX1,XXREAL_0,REAL_1,RLTOPSP1,MATHMORP,ALGSTR_0;
notations TARSKI,ORDINAL1,XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,DOMAIN_1,STRUCT_0,ALGSTR_0,PRE_TOPC,XREAL_0,REAL_1,RLVECT_1,RLTOPSP1,EUCLID,RUSUB_4,CKB1,CKB2,CKB3,CKB4;
definitions TARSKI,XBOOLE_0,SUBSET_1,ALGSTR_0,RUSUB_4,CKB1,CKB2,CKB3;
theorems XBOOLE_1,XCMPLX_1,TARSKI,SUBSET_1,ZFMISC_1,EUCLID,XBOOLE_0,JORDAN1,XREAL_0,XREAL_1,RLTOPSP1,RLVECT_1,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40;
registrations XBOOLE_0,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,EUCLID,RLTOPSP1,ALGSTR_0,RLVECT_1;
constructors DOMAIN_1,XXREAL_0,REAL_1,JORDAN1,CONVEX1,BINOP_2,RUSUB_4,CKB1,CKB2,CKB3;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
reserve T for non empty  Abelian  add-associative  right_zeroed  right_complementable RLSStruct;
reserve X for (Subset of T);
reserve Y for (Subset of T);
reserve B for (Subset of T);
theorem
Th34: ( ( X /\ Y ) (+) B ) c= ( ( X (+) B ) /\ ( Y (+) B ) )
proof
let x being set;
assume x in ( ( X /\ Y ) (+) B );
then consider y1 being (Point of T),y2 being (Point of T) such that A1: x = ( y1 + y2 ) and A2: y1 in ( X /\ Y ) and A3: y2 in B;
y1 in Y by A2,XBOOLE_0:def 4;
then A4: x in { ( y3 + y4 ) where y3 is (Point of T),y4 is (Point of T): (y3 in Y & y4 in B) } by A1,A3;
y1 in X by A2,XBOOLE_0:def 4;
then x in { ( y3 + y4 ) where y3 is (Point of T),y4 is (Point of T): (y3 in X & y4 in B) } by A1,A3;
hence thesis by A4,XBOOLE_0:def 4;
end;
