environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,XXREAL_0,CARD_1,RELAT_1,ARYTM_1,INT_1,ARYTM_3,SIN_COS,FUNCT_1,XXREAL_1,XBOOLE_0,SUBSET_1,REAL_1,XCMPLX_0,COMPLEX1,COMPTRIG,TARSKI,PROB_2,SQUARE_1,FINSEQ_6,COMPLEX2;
notations TARSKI,SUBSET_1,SQUARE_1,RELAT_1,SEQ_1,RCOMP_1,SIN_COS,XXREAL_0,COMPTRIG,XREAL_0,ORDINAL1,NUMBERS,INT_1,XCMPLX_0,REAL_1,COMPLEX1;
definitions SQUARE_1,XCMPLX_0;
theorems SQUARE_1,COMPLEX1,SIN_COS,COMPTRIG,XCMPLX_0,XCMPLX_1,RFUNCT_2,SIN_COS2,XREAL_0,XBOOLE_0,INT_1,ABSVALUE,XREAL_1,XXREAL_0,XXREAL_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
registrations RELSET_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,INT_1,MEMBERED,SIN_COS,VALUED_0,XBOOLE_0;
constructors FUNCT_4,ARYTM_0,REAL_1,SQUARE_1,BINOP_2,SEQ_1,RCOMP_1,RFUNCT_2,COMSEQ_3,SIN_COS,COMPTRIG,PARTFUN1,RVSUM_1,RELSET_1;
requirements BOOLE,SUBSET,REAL,NUMERALS,ARITHM;
begin
theorem
Th11: (for a being  real number holds (( sin a ) = ( 0 ) implies ( cos a ) <> ( 0 )))
proof
let a being  real number;
assume that
A1: ( sin a ) = ( 0 )
and
A2: ( cos a ) = ( 0 );
consider r being  real number such that A3: r = ( ( ( 2 * ( PI ) ) * ( - [\ ( a / ( 2 * ( PI ) ) ) /] ) ) + a ) and A4: (( 0 ) <= r & r < ( 2 * ( PI ) )) by CKB1:1,COMPTRIG:5;
A5: ( cos a ) = ( cos r ) by A3,CKB9:1;
( sin a ) = ( sin r ) by A3,CKB8:1;
then (r = ( 0 ) or r = ( PI )) by A4,A1,COMPTRIG:17;
hence thesis by A5,A2,COMPTRIG:5,COMPTRIG:18;
end;
