environ
vocabularies NUMBERS,REAL_1,SUBSET_1,NAT_1,XBOOLE_0,XXREAL_0,FINSET_1,TARSKI,CARD_1,ARYTM_3,XREAL_0,ORDINAL1,ARYTM_1,SEQ_1,FUNCT_1,FUNCOP_1,VALUED_1,RELAT_1,SEQ_2,ORDINAL2,COMPLEX1,LIMFUNC1,FUNCT_2,INT_1,POWER,NEWTON,ASYMPT_0;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,FUNCT_1,FUNCT_2,INT_1,NAT_1,VALUED_1,SEQ_1,SEQ_2,NEWTON,POWER,FUNCOP_1,XXREAL_2,FINSET_1,LIMFUNC1,XXREAL_0,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB19,CKB20,CKB24,CKB25,CKB26,CKB27,CKB28,CKB31,CKB38;
definitions TARSKI,FUNCT_1,VALUED_1,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB28,CKB31,CKB38;
theorems TARSKI,FUNCT_2,INT_1,NAT_1,SEQ_1,SEQ_2,ABSVALUE,LIMFUNC1,POWER,PRE_FF,XREAL_0,XBOOLE_0,XCMPLX_0,XCMPLX_1,FUNCOP_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,XXREAL_2,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB28,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47;
schemes FUNCT_2,FINSEQ_1,NAT_1,CKB1,CKB2,CKB3;
registrations XBOOLE_0,ORDINAL1,RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,POWER,XXREAL_2,FUNCT_1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB16,CKB21,CKB22,CKB23,CKB29,CKB30;
constructors REAL_1,NAT_1,SEQ_2,LIMFUNC1,NEWTON,POWER,SEQ_1,VALUED_1,PARTFUN1,XXREAL_2,RELSET_1,FUNCOP_1,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB19,CKB20,CKB24,CKB25,CKB26,CKB27,CKB28,CKB31,CKB38;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve c1 for Real;
reserve n for (Element of ( NAT ));
reserve N for (Element of ( NAT ));
theorem
(for c being non negative Real holds (for x,f being  eventually-nonnegative Real_Sequence holds (x in ( Big_Oh f ) implies x in ( Big_Oh ( c + f ) ))))
proof
let c being non negative Real;
let x being  eventually-nonnegative Real_Sequence,f being  eventually-nonnegative Real_Sequence;
assume x in ( Big_Oh f );
then consider t being (Element of ( Funcs (( NAT ),( REAL )) )) such that A1: x = t and A2: (ex c1 st (ex N st (c1 > ( 0 ) & (for n holds (n >= N implies (( t . n ) <= ( c1 * ( f . n ) ) & ( t . n ) >= ( 0 )))))));
consider c1,N such that A3: c1 > ( 0 ) and A4: (for n holds (n >= N implies (( t . n ) <= ( c1 * ( f . n ) ) & ( t . n ) >= ( 0 )))) by A2;
now
let n;
( ( f . n ) + ( 0 ) ) <= ( ( f . n ) + c ) by XREAL_1:7;
then ( f . n ) <= ( ( c + f ) . n ) by VALUED_1:2;
then A5: ( c1 * ( f . n ) ) <= ( c1 * ( ( c + f ) . n ) ) by A3,XREAL_1:64;
assume A6: n >= N;
then ( t . n ) <= ( c1 * ( f . n ) ) by A4;
hence (( t . n ) <= ( c1 * ( ( c + f ) . n ) ) & ( t . n ) >= ( 0 )) by A4,A6,A5,XXREAL_0:2;
end;
hence thesis by A1,A3;
end;
