environ
vocabularies DIRAF,SUBSET_1,STRUCT_0,AFF_4,INCSP_1,AFF_1,ANALOAF,RELAT_1,TARSKI,PARSP_1,XBOOLE_0,ARYTM_3,SETFAM_1,ZFMISC_1,EQREL_1,RELAT_2,ANPROJ_1,INCPROJ,MCART_1,FDIFF_1,ANPROJ_2,AFF_2,VECTSP_1,AFPROJ;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,DOMAIN_1,EQREL_1,RELSET_1,RELAT_1,RELAT_2,MCART_1,STRUCT_0,ANALOAF,DIRAF,AFF_1,AFF_4,AFF_2,PAPDESAF,INCSP_1,INCPROJ,CKB7,CKB8,CKB11,CKB12,CKB13,CKB14,CKB20,CKB21,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33;
definitions TARSKI,CKB7,CKB8,CKB11,CKB12,CKB13,CKB14,CKB20,CKB21,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33;
theorems RELAT_1,RELAT_2,TARSKI,ZFMISC_1,MCART_1,EQREL_1,AFF_1,AFF_4,INCPROJ,PAPDESAF,AFF_2,DIRAF,INCSP_1,XBOOLE_0,PARTFUN1,ORDERS_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55;
schemes RELSET_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,INCPROJ;
constructors DOMAIN_1,EQREL_1,AFF_1,AFF_2,TRANSLAC,INCPROJ,AFF_4,RELSET_1,CKB7,CKB8,CKB11,CKB12,CKB13,CKB14,CKB20,CKB21,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33;
requirements SUBSET,BOOLE;
begin
reserve AS for AffinSpace;
reserve X for (Subset of AS);
reserve Y for (Subset of AS);
reserve Z for (Subset of AS);
reserve X9 for (Subset of AS);
reserve Y9 for (Subset of AS);
reserve a for (POINT of ( IncProjSp_of AS ));
reserve b for (POINT of ( IncProjSp_of AS ));
reserve A for (LINE of ( IncProjSp_of AS ));
reserve K for (LINE of ( IncProjSp_of AS ));
reserve M for (LINE of ( IncProjSp_of AS ));
theorem
Lm2: ((((a on A & a on K) & b on A) & b on K) implies (a = b or A = K))
proof
assume that
A1: a on A
and
A2: a on K
and
A3: b on A
and
A4: b on K;
consider X such that A5: ((A = [ X,1 ] & X is  being_line) or (A = [ ( PDir X ),2 ] & X is  being_plane)) by CKB37:1;
consider X9 such that A6: ((K = [ X9,1 ] & X9 is  being_line) or (K = [ ( PDir X9 ),2 ] & X9 is  being_plane)) by CKB37:1;
assume A7: a <> b;
A8:now
given Y such that
A9: a = ( LDir Y )
and
A10: Y is  being_line;

A11:now
given Y9 such that
A12: b = ( LDir Y9 )
and
A13: Y9 is  being_line;

A14: (not Y // Y9) by A7,A9,A10,A12,A13,CKB17:1;
A15: ((M = [ Z,1 ] & Z is  being_line) implies (not (a on M & b on M)))
proof
assume that
A16: M = [ Z,1 ]
and
A17: Z is  being_line;
assume A18: (not thesis);
then Y9 '||' Z by A12,A13,A16,A17,CKB42:1;
then A19: Y9 // Z by A13,A17,AFF_4:40;
Y '||' Z by A9,A10,A16,A17,A18,CKB42:1;
then Y // Z by A10,A17,AFF_4:40;
then Y // Y9 by A19,AFF_1:44;
hence contradiction by A7,A9,A10,A12,A13,CKB17:1;
end;
then A20: Y9 '||' X by A1,A3,A5,A12,A13,CKB43:1;
A21: Y9 '||' X9 by A2,A4,A6,A12,A13,A15,CKB43:1;
A22: Y '||' X9 by A2,A4,A6,A9,A10,A15,CKB43:1;
Y '||' X by A1,A3,A5,A9,A10,A15,CKB43:1;
then X '||' X9 by A1,A2,A3,A4,A5,A6,A10,A13,A15,A14,A22,A20,A21,CKB5:1;
hence thesis by A1,A2,A3,A4,A5,A6,A15,CKB19:1;
end;
now
assume b is (Element of AS);
then reconsider y = b as (Element of AS);
A23: y in X9 by A4,A6,CKB40:1,CKB41:1;
A24: y = b;
then Y '||' X9 by A2,A4,A6,A9,A10,CKB41:1,CKB42:1;
then A25: Y // X9 by A4,A6,A10,A24,CKB41:1,AFF_4:40;
Y '||' X by A1,A3,A5,A9,A10,A24,CKB41:1,CKB42:1;
then Y // X by A3,A5,A10,A24,CKB41:1,AFF_4:40;
then A26: X // X9 by A25,AFF_1:44;
y in X by A3,A5,CKB40:1,CKB41:1;
hence thesis by A3,A4,A5,A6,A23,A26,CKB41:1,AFF_1:45;
end;
hence thesis by A11,CKB34:1;
end;
now
assume a is (Element of AS);
then reconsider x = a as (Element of AS);
A27: x = a;
A28: x in X9 by A2,A6,CKB40:1,CKB41:1;
A29: x in X by A1,A5,CKB40:1,CKB41:1;
A30:now
given Y such that
A31: b = ( LDir Y )
and
A32: Y is  being_line;

Y '||' X9 by A2,A4,A6,A27,A31,A32,CKB41:1,CKB42:1;
then A33: Y // X9 by A2,A6,A27,A32,CKB41:1,AFF_4:40;
Y '||' X by A1,A3,A5,A27,A31,A32,CKB41:1,CKB42:1;
then Y // X by A1,A5,A27,A32,CKB41:1,AFF_4:40;
then X // X9 by A33,AFF_1:44;
hence thesis by A1,A2,A5,A6,A29,A28,CKB41:1,AFF_1:45;
end;
now
assume b is (Element of AS);
then reconsider y = b as (Element of AS);
A34: y in X9 by A4,A6,CKB40:1,CKB41:1;
y in X by A3,A5,CKB40:1,CKB41:1;
hence thesis by A1,A2,A7,A5,A6,A29,A28,A34,CKB41:1,AFF_1:18;
end;
hence thesis by A30,CKB34:1;
end;
hence thesis by A8,CKB34:1;
end;
