environ
vocabularies BCIALG_1,CARD_FIL,SUBSET_1,FUNCT_1,NUMBERS,STRUCT_0,POWER,CARD_1,ARYTM_3,XBOOLE_0,XXREAL_0,FUNCOP_1,NAT_1,SUPINF_2,RELAT_1,CHORD,WAYBEL15,GROUP_4,GROUP_1,ALG_1,EQREL_1,PARTFUN1,RELAT_2,ZFMISC_1,RCOMP_1,TARSKI,BINOP_1,GROUP_6,BCIALG_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,RELAT_1,FUNCT_1,NAT_1,FUNCT_2,XXREAL_0,FUNCOP_1,BINOP_1,STRUCT_0,BCIALG_1,RELAT_2,PARTFUN1,EQREL_1,ALG_1,CKB1;
definitions XBOOLE_0,TARSKI,STRUCT_0,BCIALG_1,RELAT_1,CKB1;
theorems BCIALG_1,FUNCOP_1,NAT_1,XREAL_1,TARSKI,XBOOLE_0,RELAT_2,RELAT_1,XXREAL_0,ORDERS_1,XBOOLE_1,BINOP_1,EQREL_1,RELSET_1,ZFMISC_1,CKB1,CKB2,CKB3,CKB4;
schemes FUNCT_2,NAT_1,RELSET_1,XBOOLE_0,BINOP_1;
registrations BCIALG_1,SUBSET_1,NAT_1,RELSET_1,STRUCT_0,PARTFUN1,ORDINAL1,XREAL_0;
constructors BCIALG_1,BINOP_1,XXREAL_0,NAT_1,BINARITH,EQREL_1,RELSET_1,CKB1;
requirements NUMERALS,ARITHM,SUBSET,BOOLE;
begin
reserve X for BCI-algebra;
reserve x for (Element of X);
reserve y for (Element of X);
reserve f for (Function of ( NAT ),(the carrier of X));
reserve g for (Function of ( NAT ),(the carrier of X));
reserve j for (Element of ( NAT ));
reserve k for (Element of ( NAT ));
reserve n for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
theorem
Th4: ( (x,y) to_power ( n + 1 ) ) = ( ( (x,y) to_power n ) \ y )
proof
A1: n < ( n + 1 ) by NAT_1:3,XREAL_1:29;
consider g such that A2: ( (x,y) to_power n ) = ( g . n ) and A3: ( g . ( 0 ) ) = x and A4: (for j holds (j < n implies ( g . ( j + 1 ) ) = ( ( g . j ) \ y ))) by CKB1:def 1;
consider f such that A5: ( (x,y) to_power ( n + 1 ) ) = ( f . ( n + 1 ) ) and A6: ( f . ( 0 ) ) = x and A7: (for j holds (j < ( n + 1 ) implies ( f . ( j + 1 ) ) = ( ( f . j ) \ y ))) by CKB1:def 1;
defpred P[ set ]
 means
(for m holds ((m = $1 & m <= n) implies ( f . m ) = ( g . m )));
now
let k;
assume A8: (for m holds ((m = k & m <= n) implies ( f . m ) = ( g . m )));
let m;
assume that
A9: m = ( k + 1 )
and
A10: m <= n;
( k + 1 ) <= ( n + 1 ) by A9,A10,NAT_1:13;
then k < ( n + 1 ) by NAT_1:13;
then A11: ( f . ( k + 1 ) ) = ( ( f . k ) \ y ) by A7;
A12: k < n by A9,A10,NAT_1:13;
then ( g . ( k + 1 ) ) = ( ( g . k ) \ y ) by A4;
hence ( f . m ) = ( g . m ) by A8,A9,A12,A11;
end;
then A13: (for k holds (P[ k ] implies P[ ( k + 1 ) ]));
A14: P[ ( 0 ) ] by A6,A3;
(for n holds P[ n ]) from NAT_1:sch 1(A14,A13);
then ( f . n ) = ( g . n );
hence thesis by A5,A7,A2,A1;
end;
