environ
vocabularies BCIALG_1,CARD_FIL,SUBSET_1,FUNCT_1,NUMBERS,STRUCT_0,POWER,CARD_1,ARYTM_3,XBOOLE_0,XXREAL_0,FUNCOP_1,NAT_1,SUPINF_2,RELAT_1,CHORD,WAYBEL15,GROUP_4,GROUP_1,ALG_1,EQREL_1,PARTFUN1,RELAT_2,ZFMISC_1,RCOMP_1,TARSKI,BINOP_1,GROUP_6,BCIALG_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,RELAT_1,FUNCT_1,NAT_1,FUNCT_2,XXREAL_0,FUNCOP_1,BINOP_1,STRUCT_0,BCIALG_1,RELAT_2,PARTFUN1,EQREL_1,ALG_1,CKB1,CKB24,CKB25,CKB26,CKB27,CKB28,CKB42,CKB43,CKB44,CKB50,CKB51,CKB52;
definitions XBOOLE_0,TARSKI,STRUCT_0,BCIALG_1,RELAT_1,CKB1,CKB25,CKB26,CKB27,CKB28,CKB42,CKB43,CKB44,CKB50,CKB51,CKB52;
theorems BCIALG_1,FUNCOP_1,NAT_1,XREAL_1,TARSKI,XBOOLE_0,RELAT_2,RELAT_1,XXREAL_0,ORDERS_1,XBOOLE_1,BINOP_1,EQREL_1,RELSET_1,ZFMISC_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52;
schemes FUNCT_2,NAT_1,RELSET_1,XBOOLE_0,BINOP_1;
registrations BCIALG_1,SUBSET_1,NAT_1,RELSET_1,STRUCT_0,PARTFUN1,ORDINAL1,XREAL_0,CKB31,CKB33,CKB45;
constructors BCIALG_1,BINOP_1,XXREAL_0,NAT_1,BINARITH,EQREL_1,RELSET_1,CKB1,CKB25,CKB26,CKB27,CKB28,CKB42,CKB43,CKB44,CKB50,CKB51,CKB52;
requirements NUMERALS,ARITHM,SUBSET,BOOLE;
begin
definition
let X being BCI-algebra;
let A being (Ideal of X);
mode I-congruence of X,A
 -> (Relation of X)
means :Def12: (for x,y being (Element of X) holds ([ x,y ] in it iff (( x \ y ) in A & ( y \ x ) in A)));
existence
proof
defpred PP[ set,set ]
 means
(ex x,y being (Element of X) st (((x = $1 & y = $2) & ( x \ y ) in A) & ( y \ x ) in A));
consider P being (Relation of X) such that A1: (for x2,y2 being set holds ([ x2,y2 ] in P iff ((x2 in (the carrier of X) & y2 in (the carrier of X)) & PP[ x2,y2 ]))) from RELSET_1:sch 1;
take P;
let x2 being (Element of X),y2 being (Element of X);
([ x2,y2 ] in P implies (ex x1,y1 being (Element of X) st (((x1 = x2 & y1 = y2) & ( x1 \ y1 ) in A) & ( y1 \ x1 ) in A))) by A1;
hence ([ x2,y2 ] in P implies (( x2 \ y2 ) in A & ( y2 \ x2 ) in A));
thus thesis by A1;
end;
end;
