environ
vocabularies INCPROJ,INCSP_1,SUBSET_1,AFF_2,ANALOAF,PARTFUN1,PROJRED1,FUNCT_1,RELAT_1,TARSKI,ZFMISC_1,PROJRED2;
notations TARSKI,ZFMISC_1,SUBSET_1,DOMAIN_1,RELAT_1,RELSET_1,INCSP_1,INCPROJ,PARTFUN1,FUNCT_1,PROJRED1,CKB1,CKB2,CKB3;
definitions CKB1,CKB2,CKB3;
theorems TARSKI,INCPROJ,FUNCT_1,PROJRED1,ZFMISC_1,INCSP_1,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16;
registrations FUNCT_1,RELSET_1,INCPROJ;
constructors DOMAIN_1,PROJRED1,RELSET_1,CKB1,CKB2,CKB3;
requirements SUBSET,BOOLE;
begin
reserve IPP for  Desarguesian  2-dimensional IncProjSp;
reserve a for (POINT of IPP);
reserve b for (POINT of IPP);
reserve c for (POINT of IPP);
reserve d for (POINT of IPP);
reserve p for (POINT of IPP);
reserve pp9 for (POINT of IPP);
reserve q for (POINT of IPP);
reserve x for (POINT of IPP);
reserve y for (POINT of IPP);
reserve O1 for (LINE of IPP);
reserve O2 for (LINE of IPP);
reserve O3 for (LINE of IPP);
reserve A for (LINE of IPP);
reserve B for (LINE of IPP);
reserve C for (LINE of IPP);
reserve O for (LINE of IPP);
reserve Q for (LINE of IPP);
reserve Q1 for (LINE of IPP);
reserve Q3 for (LINE of IPP);
reserve R for (LINE of IPP);
theorem
Th15: (((((((((((((((((((((((((((((((not a on A) & (not b on B)) & (not a on C)) & (not b on C)) & (not A,B,C are_concurrent )) & c on A) & c on C) & c on Q) & (not b on Q)) & A <> Q) & a on O) & b on O) & (not B,C,O are_concurrent )) & d on C) & d on B) & a on O1) & d on O1) & p on A) & p on O1) & q on O) & q on O2) & p on O2) & pp9 on O2) & d on O3) & b on O3) & pp9 on O3) & pp9 on Q) & q <> a) & (not q on A)) & (not q on Q)) implies ( ( IncProj (C,b,B) ) * ( IncProj (A,a,C) ) ) = ( ( IncProj (Q,b,B) ) * ( IncProj (A,q,Q) ) ))
proof
assume that
A1: (not a on A)
and
A2: (not b on B)
and
A3: (not a on C)
and
A4: (not b on C)
and
A5: (not A,B,C are_concurrent )
and
A6: c on A
and
A7: c on C
and
A8: c on Q
and
A9: (not b on Q)
and
A10: A <> Q
and
A11: a on O
and
A12: b on O
and
A13: (not B,C,O are_concurrent )
and
A14: d on C
and
A15: d on B
and
A16: a on O1
and
A17: d on O1
and
A18: p on A
and
A19: p on O1
and
A20: q on O
and
A21: q on O2
and
A22: (p on O2 & pp9 on O2)
and
A23: (d on O3 & b on O3)
and
A24: pp9 on O3
and
A25: pp9 on Q
and
A26: q <> a
and
A27: (not q on A)
and
A28: (not q on Q);
set f = ( IncProj (A,a,C) );
set g = ( IncProj (C,b,B) );
set g1 = ( IncProj (Q,b,B) );
set f1 = ( IncProj (A,q,Q) );
A29: ( dom f ) = ( CHAIN A ) by A1,A3,CKB7:1;
set X = ( CHAIN A );
A30: ( dom f1 ) = ( CHAIN A ) by A27,A28,CKB7:1;
then A31: ( dom ( g1 * f1 ) ) = X by A2,A9,A27,A28,PROJRED1:22;
A32: O1 <> O2
proof
assume (not thesis);
then d on O by A11,A16,A17,A20,A21,A26,INCPROJ:def 4;
hence contradiction by A13,A14,A15,CKB1:def 1;
end;
c <> d by A5,A6,A7,A15,CKB1:def 1;
then p <> c by A3,A7,A14,A16,A17,A19,INCPROJ:def 4;
then A33: pp9 <> p by A6,A8,A10,A18,A25,INCPROJ:def 4;
A34: (for x holds (x on A implies ( ( ( IncProj (C,b,B) ) * ( IncProj (A,a,C) ) ) . x ) = ( ( ( IncProj (Q,b,B) ) * ( IncProj (A,q,Q) ) ) . x )))
proof
let x;
assume that
A35: x on A;
consider Q3 such that A36: (q on Q3 & x on Q3) by INCPROJ:def 5;
consider Q1 such that A37: (a on Q1 & x on Q1) by INCPROJ:def 5;
consider y being (POINT of IPP) such that A38: y on Q3 and A39: y on Q by INCPROJ:def 9;
consider x9 being (POINT of IPP) such that A40: x9 on Q1 and A41: x9 on C by INCPROJ:def 9;
A42:now
A43: ({ pp9,y,c } on Q & { d,x9,c } on C) by A7,A8,A14,A25,A41,A39,INCSP_1:2;
A44: ({ p,pp9,q } on O2 & { pp9,d,b } on O3) by A21,A22,A23,A24,INCSP_1:2;
A45: ({ b,a,q } on O & { x,y,q } on Q3) by A11,A12,A20,A36,A38,INCSP_1:2;
A46: ({ p,x,c } on A & { p,d,a } on O1) by A6,A16,A17,A18,A19,A35,INCSP_1:2;
assume A47: p <> x;
({ x,x9,a } on Q1 & A,O1,O2 are_mutually_different ) by A1,A16,A21,A27,A32,A37,A40,INCSP_1:2,ZFMISC_1:def 5;
then consider R such that A48: { y,x9,b } on R by A1,A3,A14,A18,A33,A47,A46,A44,A43,A45,PROJRED1:12;
A49: b on R by A48,INCSP_1:2;
consider x99 being (POINT of IPP) such that A50: (x99 on R & x99 on B) by INCPROJ:def 9;
x9 on R by A48,INCSP_1:2;
then A51: ( g . x9 ) = x99 by A2,A4,A41,A50,A49,PROJRED1:def 1;
A52: x in ( dom f1 ) by A30,A35;
y on R by A48,INCSP_1:2;
then A53: ( g1 . y ) = x99 by A2,A9,A39,A50,A49,PROJRED1:def 1;
A54: x in ( dom f ) by A29,A35;
(( f . x ) = x9 & ( f1 . x ) = y) by A1,A3,A27,A28,A35,A37,A40,A41,A36,A38,A39,PROJRED1:def 1;
then ( ( g * f ) . x ) = ( g1 . ( f1 . x ) ) by A51,A53,A54,FUNCT_1:13
.= ( ( g1 * f1 ) . x ) by A52,FUNCT_1:13;
hence thesis;
end;
now
A55: (( f1 . p ) = pp9 & ( g1 . pp9 ) = d) by A2,A9,A15,A18,A21,A22,A23,A24,A25,A27,A28,PROJRED1:def 1;
assume A56: p = x;
A57: x in ( dom f1 ) by A30,A35;
A58: x in ( dom f ) by A29,A35;
(( f . p ) = d & ( g . d ) = d) by A1,A2,A3,A4,A14,A15,A16,A17,A18,A19,A23,PROJRED1:def 1;
then ( ( g * f ) . x ) = ( g1 . ( f1 . x ) ) by A56,A55,A58,FUNCT_1:13
.= ( ( g1 * f1 ) . x ) by A57,FUNCT_1:13;
hence thesis;
end;
hence thesis by A42;
end;
A59:now
let y being set;
assume y in X;
then (ex x st (y = x & x on A));
hence ( ( g * f ) . y ) = ( ( g1 * f1 ) . y ) by A34;
end;
( dom ( g * f ) ) = X by A1,A2,A3,A4,A29,PROJRED1:22;
hence thesis by A31,A59,FUNCT_1:2;
end;
