environ
vocabularies NUMBERS,SUBSET_1,XREAL_0,ORDINAL1,POWER,CARD_1,NEWTON,XXREAL_0,SQUARE_1,RELAT_1,XBOOLE_0,ARYTM_1,ABIAN,NAT_1,ARYTM_3,PREPOWER,FIB_NUM,FUNCT_1,ZFMISC_1,MCART_1,PRE_FF,FIB_NUM3;
notations TARSKI,XBOOLE_0,SUBSET_1,SQUARE_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,ORDINAL1,NEWTON,NAT_1,MCART_1,DOMAIN_1,PREPOWER,POWER,FUNCT_2,NAT_D,PRE_FF,FIB_NUM,ABIAN,CKB13,CKB36,CKB37;
definitions SQUARE_1,CKB13,CKB37;
theorems NAT_1,MCART_1,POWER,PREPOWER,XCMPLX_1,PRE_FF,FIB_NUM,SQUARE_1,WSIERP_1,NAT_2,ABIAN,FIB_NUM2,XREAL_1,XXREAL_0,ORDINAL1,NAT_D,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52;
schemes FIB_NUM,FIB_NUM2,NAT_1;
registrations SUBSET_1,ORDINAL1,XXREAL_0,XREAL_0,SQUARE_1,NAT_1,MEMBERED,XBOOLE_0,XCMPLX_0,CKB9,CKB10,CKB22;
constructors DOMAIN_1,SQUARE_1,MEMBERED,NEWTON,PREPOWER,POWER,PRE_FF,NAT_D,ABIAN,FIB_NUM,CKB13,CKB36,CKB37;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
(for a,b,n being (Element of ( NAT )) holds ( ( ( GenFib (a,b,( n + 2 )) ) * ( GenFib (a,b,n) ) ) - ( ( GenFib (a,b,( n + 1 )) ) |^ 2 ) ) = ( ( ( - 1 ) to_power n ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ))
proof
let a being (Element of ( NAT )),b being (Element of ( NAT )),n being (Element of ( NAT ));
defpred P[ Nat ]
 means
( ( ( GenFib (a,b,( $1 + 2 )) ) * ( GenFib (a,b,$1) ) ) - ( ( GenFib (a,b,( $1 + 1 )) ) |^ 2 ) ) = ( ( ( - 1 ) to_power $1 ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) );
A1: ( GenFib (a,b,2) ) = ( GenFib (a,b,( ( 0 ) + 2 )) )
.= ( ( GenFib (a,b,( 0 )) ) + ( GenFib (a,b,( ( 0 ) + 1 )) ) ) by CKB40:1
.= ( a + ( GenFib (a,b,1) ) ) by CKB38:1
.= ( a + b ) by CKB38:1;
A2: ( GenFib (a,b,3) ) = ( GenFib (a,b,( 1 + 2 )) )
.= ( ( GenFib (a,b,1) ) + ( GenFib (a,b,( 1 + 1 )) ) ) by CKB38:1
.= ( b + ( a + b ) ) by A1,CKB38:1
.= ( ( 2 * b ) + a );
then ( ( ( GenFib (a,b,( 1 + 2 )) ) * ( GenFib (a,b,1) ) ) - ( ( GenFib (a,b,( 1 + 1 )) ) |^ 2 ) ) = ( ( ( ( 2 * b ) + a ) * b ) - ( ( a + b ) |^ 2 ) ) by A1,CKB38:1
.= ( ( ( ( 2 * b ) * b ) + ( a * b ) ) - ( ( a + b ) * ( a + b ) ) ) by WSIERP_1:1
.= ( ( - 1 ) * ( ( ( a + b ) * ( a + b ) ) - ( b * ( ( 2 * b ) + a ) ) ) )
.= ( ( ( - 1 ) to_power 1 ) * ( ( ( a + b ) * ( a + b ) ) - ( b * ( ( 2 * b ) + a ) ) ) ) by POWER:25
.= ( ( ( - 1 ) to_power 1 ) * ( ( ( a + b ) |^ 2 ) - ( b * ( GenFib (a,b,3) ) ) ) ) by A2,WSIERP_1:1
.= ( ( ( - 1 ) to_power 1 ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by A1,CKB38:1;
then A3: P[ 1 ];
A4: (for k being Nat holds ((P[ k ] & P[ ( k + 1 ) ]) implies P[ ( k + 2 ) ]))
proof
let k being Nat;
assume that
A5: P[ k ]
and
A6: P[ ( k + 1 ) ];
set d = ( ( GenFib (a,b,( k + 2 )) ) * ( GenFib (a,b,k) ) );
A7: ( ( ( - 1 ) to_power ( k + 1 ) ) + ( ( - 1 ) to_power k ) ) = ( ( ( ( - 1 ) to_power k ) * ( ( - 1 ) to_power 1 ) ) + ( ( - 1 ) to_power k ) ) by FIB_NUM2:5
.= ( ( ( ( - 1 ) to_power k ) * ( - 1 ) ) + ( ( - 1 ) to_power k ) ) by POWER:25
.= ( 0 );
( ( GenFib (a,b,2) ) |^ 2 ) = ( ( GenFib (a,b,( ( 0 ) + 2 )) ) |^ 2 )
.= ( ( ( GenFib (a,b,( 0 )) ) + ( GenFib (a,b,( ( 0 ) + 1 )) ) ) |^ 2 ) by CKB40:1
.= ( ( a + ( GenFib (a,b,1) ) ) |^ 2 ) by CKB38:1
.= ( ( a + b ) |^ 2 ) by CKB38:1;
then A8: ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) = ( ( ( a + b ) |^ 2 ) - ( b * ( GenFib (a,b,( 1 + 2 )) ) ) ) by CKB38:1
.= ( ( ( a + b ) |^ 2 ) - ( b * ( ( GenFib (a,b,1) ) + ( GenFib (a,b,( 1 + 1 )) ) ) ) ) by CKB40:1
.= ( ( ( a + b ) |^ 2 ) - ( b * ( b + ( GenFib (a,b,( ( 0 ) + 2 )) ) ) ) ) by CKB38:1
.= ( ( ( a + b ) |^ 2 ) - ( b * ( b + ( ( GenFib (a,b,( 0 )) ) + ( GenFib (a,b,( ( 0 ) + 1 )) ) ) ) ) ) by CKB40:1
.= ( ( ( a + b ) |^ 2 ) - ( b * ( b + ( a + ( GenFib (a,b,1) ) ) ) ) ) by CKB38:1
.= ( ( ( a + b ) |^ 2 ) - ( b * ( b + ( a + b ) ) ) ) by CKB38:1
.= ( ( ( ( ( a + b ) |^ 2 ) - ( b * b ) ) - ( b * a ) ) - ( b * b ) )
.= ( ( ( ( ( ( ( a * a ) + ( a * b ) ) + ( b * a ) ) + ( b * b ) ) - ( b * b ) ) - ( b * a ) ) - ( b * b ) ) by CKB5:1
.= ( ( ( a * a ) + ( a * b ) ) - ( b * b ) );
then ( d - ( ( GenFib (a,b,( k + 1 )) ) |^ 2 ) ) = ( ( ( - 1 ) to_power k ) * ( ( ( a * a ) + ( a * b ) ) - ( b * b ) ) ) by A5;
then A9: ( ( ( ( - 1 ) to_power ( k + 1 ) ) * ( ( ( a * a ) + ( a * b ) ) - ( b * b ) ) ) + ( d - ( ( GenFib (a,b,( k + 1 )) ) |^ 2 ) ) ) = ( ( ( ( - 1 ) to_power ( k + 1 ) ) + ( ( - 1 ) to_power k ) ) * ( ( ( a * a ) + ( a * b ) ) - ( b * b ) ) )
.= ( ( ( ( a * a ) + ( a * b ) ) - ( b * b ) ) * ( 0 ) ) by A7;
set c = ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) * ( GenFib (a,b,( k + 1 )) ) );
A10: ( c - ( ( GenFib (a,b,( ( k + 1 ) + 1 )) ) |^ 2 ) ) = ( ( ( - 1 ) to_power ( k + 1 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by A6;
A11: ( ( c + d ) - ( ( ( GenFib (a,b,( k + 1 )) ) + ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) |^ 2 ) ) = ( ( c + d ) - ( ( ( ( GenFib (a,b,( k + 1 )) ) |^ 2 ) + ( ( 2 * ( GenFib (a,b,( k + 1 )) ) ) * ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) ) + ( ( GenFib (a,b,( ( k + 1 ) + 1 )) ) |^ 2 ) ) ) by CKB39:1
.= ( ( ( ( ( ( - 1 ) to_power ( k + 1 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) + d ) - ( ( GenFib (a,b,( k + 1 )) ) |^ 2 ) ) - ( ( 2 * ( GenFib (a,b,( k + 1 )) ) ) * ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) ) by A10
.= ( ( ( ( ( ( - 1 ) to_power ( k + 1 ) ) * ( ( ( a * a ) + ( a * b ) ) - ( b * b ) ) ) + d ) - ( ( GenFib (a,b,( k + 1 )) ) |^ 2 ) ) - ( ( 2 * ( GenFib (a,b,( k + 1 )) ) ) * ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) ) by A8
.= ( - ( ( 2 * ( GenFib (a,b,( k + 1 )) ) ) * ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) ) by A9;
( ( ( GenFib (a,b,( ( k + 2 ) + 2 )) ) * ( GenFib (a,b,( k + 2 )) ) ) - ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) |^ 2 ) ) = ( ( ( ( GenFib (a,b,( k + 2 )) ) + ( GenFib (a,b,( ( k + 2 ) + 1 )) ) ) * ( GenFib (a,b,( k + 2 )) ) ) - ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) |^ 2 ) ) by CKB40:1
.= ( ( ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) + ( GenFib (a,b,( k + 2 )) ) ) * ( ( GenFib (a,b,k) ) + ( GenFib (a,b,( k + 1 )) ) ) ) - ( ( GenFib (a,b,( ( k + 1 ) + 2 )) ) |^ 2 ) ) by CKB40:1
.= ( ( ( ( ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) * ( GenFib (a,b,k) ) ) + c ) + d ) + ( ( GenFib (a,b,( k + 2 )) ) * ( GenFib (a,b,( k + 1 )) ) ) ) - ( ( ( GenFib (a,b,( k + 1 )) ) + ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) |^ 2 ) ) by CKB38:1
.= ( ( ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) * ( GenFib (a,b,k) ) ) + ( ( GenFib (a,b,( k + 2 )) ) * ( GenFib (a,b,( k + 1 )) ) ) ) + ( ( c + d ) - ( ( ( GenFib (a,b,( k + 1 )) ) + ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) |^ 2 ) ) )
.= ( ( ( ( GenFib (a,b,( ( k + 2 ) + 1 )) ) * ( GenFib (a,b,k) ) ) + ( ( GenFib (a,b,( k + 2 )) ) * ( GenFib (a,b,( k + 1 )) ) ) ) + ( - ( ( 2 * ( GenFib (a,b,( k + 1 )) ) ) * ( GenFib (a,b,( k + 2 )) ) ) ) ) by A11
.= ( ( ( GenFib (a,b,( ( k + 1 ) + 2 )) ) * ( GenFib (a,b,k) ) ) - ( ( GenFib (a,b,( k + 2 )) ) * ( GenFib (a,b,( k + 1 )) ) ) )
.= ( ( ( ( GenFib (a,b,( k + 1 )) ) + ( GenFib (a,b,( ( k + 1 ) + 1 )) ) ) * ( GenFib (a,b,k) ) ) - ( ( GenFib (a,b,( k + 2 )) ) * ( GenFib (a,b,( k + 1 )) ) ) ) by CKB40:1
.= ( ( ( ( GenFib (a,b,( k + 1 )) ) * ( GenFib (a,b,k) ) ) + d ) - ( ( ( GenFib (a,b,k) ) + ( GenFib (a,b,( k + 1 )) ) ) * ( GenFib (a,b,( k + 1 )) ) ) ) by CKB40:1
.= ( d - ( ( GenFib (a,b,( k + 1 )) ) * ( GenFib (a,b,( k + 1 )) ) ) )
.= ( ( ( ( - 1 ) to_power k ) * 1 ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by A5,WSIERP_1:1
.= ( ( ( ( - 1 ) to_power k ) * ( 1 to_power 2 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by POWER:26
.= ( ( ( ( - 1 ) to_power k ) * ( ( - 1 ) to_power 2 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by CKB3:1
.= ( ( ( - 1 ) to_power ( k + 2 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by FIB_NUM2:5;
hence thesis;
end;
( ( ( GenFib (a,b,( ( 0 ) + 2 )) ) * ( GenFib (a,b,( 0 )) ) ) - ( ( GenFib (a,b,( ( 0 ) + 1 )) ) |^ 2 ) ) = ( ( ( GenFib (a,b,2) ) * a ) - ( ( GenFib (a,b,1) ) |^ 2 ) ) by CKB38:1
.= ( ( ( a + b ) * a ) - ( b |^ 2 ) ) by A1,CKB38:1
.= ( ( ( a * a ) + ( b * a ) ) - ( b * b ) ) by WSIERP_1:1
.= ( ( ( a + b ) * ( a + b ) ) - ( b * ( ( 2 * b ) + a ) ) )
.= ( 1 * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( b * ( GenFib (a,b,3) ) ) ) ) by A1,A2,WSIERP_1:1
.= ( ( ( - 1 ) to_power ( 0 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( b * ( GenFib (a,b,3) ) ) ) ) by POWER:24
.= ( ( ( - 1 ) to_power ( 0 ) ) * ( ( ( GenFib (a,b,2) ) |^ 2 ) - ( ( GenFib (a,b,1) ) * ( GenFib (a,b,3) ) ) ) ) by CKB38:1;
then A12: P[ ( 0 ) ];
(for k being Nat holds P[ k ]) from FIB_NUM:sch 1(A12,A3,A4);
hence thesis;
end;
