environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,REAL_1,SUBSET_1,XBOOLE_0,PRE_TOPC,EUCLID,NAT_1,FINSEQ_1,PARTFUN1,RELAT_1,FUNCT_1,TOPMETR,STRUCT_0,SUPINF_2,CARD_1,FINSEQ_2,ARYTM_1,ARYTM_3,XXREAL_0,RFINSEQ,CARD_3,FUNCT_4,ORDINAL4,COMPLEX1,SQUARE_1,RVSUM_1,RCOMP_1,PCOMPS_1,METRIC_1,TARSKI,ORDINAL2,TOPS_2,VALUED_1,MCART_1,FUNCT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,RVSUM_1,FUNCT_1,PARTFUN1,RELSET_1,FINSEQ_1,FUNCT_2,BINOP_1,RFINSEQ,FINSEQ_2,NAT_D,STRUCT_0,MONOID_0,TOPS_2,SQUARE_1,FUNCT_7,TOPMETR,PRE_TOPC,METRIC_1,RLVECT_1,EUCLID,PSCOMP_1,PCOMPS_1,FINSEQOP,XXREAL_0;
definitions TARSKI,EUCLID,FINSEQ_2,RVSUM_1,SQUARE_1,RELAT_1,STRUCT_0,VALUED_1;
theorems TARSKI,EUCLID,TOPMETR,TOPS_1,METRIC_1,FUNCT_1,RFINSEQ,FUNCT_2,RELAT_1,TBSP_1,NAT_1,FINSEQ_3,FINSEQ_1,ABSVALUE,SQUARE_1,FINSEQ_2,TOPS_2,RVSUM_1,TOPREAL3,FUNCOP_1,FINSEQ_4,FUNCT_7,SEQ_2,PSCOMP_1,XREAL_0,XBOOLE_0,COMPLEX1,XREAL_1,XXREAL_0,FINSOP_1,PARTFUN1,NAT_D,VALUED_1,PRE_TOPC,CARD_1,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18;
schemes FUNCT_2;
registrations XBOOLE_0,RELAT_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,FINSEQ_2,FUNCT_7,STRUCT_0,METRIC_1,PCOMPS_1,EUCLID,TOPMETR,VALUED_0,FINSEQ_1,MONOID_0,CARD_1,RELSET_1,FUNCT_2,CKB2;
constructors REAL_1,SQUARE_1,COMPLEX1,FINSEQOP,FINSEQ_4,FINSOP_1,RFINSEQ,NAT_D,FUNCT_7,TOPS_2,TOPMETR,PSCOMP_1,SEQ_1,BINOP_2,NAT_1,RVSUM_1,FUNCSDOM,MONOID_0,EUCLID,PCOMPS_1;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve x for set;
reserve r for  real number;
reserve s for Real;
theorem
Th21: (for u being (Point of ( RealSpace )) holds (for r,u1 being  real number holds (u1 = u implies ( Ball (u,r) ) = { s: (( u1 - r ) < s & s < ( u1 + r )) })))
proof
let u being (Point of ( RealSpace ));
let r being  real number;
let u1 being  real number;
assume A1: u1 = u;
{ s: (( u1 - r ) < s & s < ( u1 + r )) } = { q where q is (Element of ( RealSpace )): ( dist (u,q) ) < r }
proof
A2: { q where q is (Element of ( RealSpace )): ( dist (u,q) ) < r } c= { s: (( u1 - r ) < s & s < ( u1 + r )) }
proof
let x;
assume x in { q where q is (Element of ( RealSpace )): ( dist (u,q) ) < r };
then consider q being (Element of ( RealSpace )) such that A3: x = q and A4: ( dist (u,q) ) < r;
reconsider s1 = q as Real by METRIC_1:def 13;
A5: ( abs ( u1 - s1 ) ) < r by A1,A4,TOPMETR:11;
then ( u1 - s1 ) < r by SEQ_2:1;
then ( ( u1 - s1 ) + s1 ) < ( r + s1 ) by XREAL_1:6;
then A6: ( u1 - r ) < ( ( r + s1 ) - r ) by XREAL_1:9;
( - r ) < ( u1 - s1 ) by A5,SEQ_2:1;
then ( ( - r ) + s1 ) < ( ( u1 - s1 ) + s1 ) by XREAL_1:6;
then ( ( s1 - r ) + r ) < ( u1 + r ) by XREAL_1:6;
hence thesis by A3,A6;
end;
{ s: (( u1 - r ) < s & s < ( u1 + r )) } c= { q where q is (Element of ( RealSpace )): ( dist (u,q) ) < r }
proof
let x;
assume x in { s: (( u1 - r ) < s & s < ( u1 + r )) };
then consider s such that A7: x = s and A8: ( u1 - r ) < s and A9: s < ( u1 + r );
reconsider q1 = s as (Point of ( RealSpace )) by METRIC_1:def 13;
( s - r ) < ( ( u1 + r ) - r ) by A9,XREAL_1:9;
then A10: ( ( s + ( - r ) ) - s ) < ( u1 - s ) by XREAL_1:9;
( ( u1 - r ) + r ) < ( s + r ) by A8,XREAL_1:6;
then ( u1 - s ) < ( ( s + r ) - s ) by XREAL_1:9;
then ( abs ( u1 - s ) ) < r by A10,SEQ_2:1;
then ( dist (u,q1) ) < r by A1,TOPMETR:11;
hence thesis by A7;
end;
hence thesis by A2,XBOOLE_0:def 10;
end;
hence thesis by METRIC_1:17;
end;
