environ
vocabularies NUMBERS,FINSET_1,XBOOLE_0,SUBSET_1,TARSKI,FUNCT_1,RELAT_1,FUNCOP_1,FUNCT_4,PBOOLE,FINSEQ_1,CARD_3,PARTFUN1,FUNCT_5,FUNCT_2,ZFMISC_1,FUNCT_6,NAT_1,CARD_1,ARYTM_3,MCART_1,FINSEQ_2,TREES_1,TREES_3,TREES_2,ORDINAL4,TREES_A,XXREAL_0,TREES_4,ARYTM_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,XCMPLX_0,XREAL_0,MCART_1,CARD_1,RELAT_1,FUNCT_1,FINSET_1,PARTFUN1,FUNCT_2,XXREAL_0,XXREAL_2,BINOP_1,FUNCOP_1,FUNCT_4,FUNCT_7,CARD_3,TREES_2,TREES_1,TREES_3,TREES_4,FUNCT_5,FUNCT_6,PBOOLE,FINSEQ_1,FINSEQ_2,NAT_1;
definitions TARSKI,FUNCOP_1,WELLORD2,FUNCT_1,RELAT_1,PBOOLE,XBOOLE_0,SEQ_4,FINSEQ_2,FINSET_1;
theorems TARSKI,ZFMISC_1,FINSEQ_1,FINSEQ_3,GRFUNC_1,FUNCT_1,FUNCT_2,FUNCT_4,FUNCT_5,TREES_1,TREES_2,TREES_3,TREES_4,NAT_1,RELAT_1,CARD_3,FUNCOP_1,MCART_1,PBOOLE,CARD_2,CARD_1,FUNCT_6,FINSET_1,XBOOLE_0,XBOOLE_1,XCMPLX_1,ORDERS_1,XREAL_1,XXREAL_0,XXREAL_2,XREAL_0,PARTFUN1,FUNCT_7,FINSEQ_2,CKB2,CKB3;
schemes DOMAIN_1,PBOOLE,FUNCT_1,FRAENKEL,FINSEQ_1,NAT_1,CKB1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCOP_1,FINSET_1,XREAL_0,MEMBERED,FINSEQ_1,CARD_3,PBOOLE,TREES_2,TREES_3,XXREAL_2,CARD_1,RELSET_1,TREES_1;
constructors WELLORD2,BINOP_1,FUNCT_4,SETWISEO,XXREAL_0,NAT_1,FUNCT_5,CARD_3,SEQ_4,PBOOLE,TREES_4,BINARITH,INT_1,SEQ_1,XXREAL_2,PARTFUN1,RELSET_1,FUNCT_7;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve i for set;
reserve j for set;
reserve f for Function;
scheme MSSLambda2Part { I() -> set,P[set],F,G(set) -> set } : (ex f being (ManySortedSet of I()) st (for i being (Element of I()) holds (i in I() implies ((P[ i ] implies ( f . i ) = F(i)) & ((not P[ i ]) implies ( f . i ) = G(i))))))
proof
defpred Q[ set,set ]
 means
((P[ $1 ] implies $2 = F($1)) & ((not P[ $1 ]) implies $2 = G($1)));
A1:now
let i;
assume that
i in I();
thus (ex j st Q[ i,j ])
proof
per cases ;
suppose A2: P[ i ];

take F(i);
thus thesis by A2;
end;
suppose A3: (not P[ i ]);

take G(i);
thus thesis by A3;
end;
end;

end;
consider f being (ManySortedSet of I()) such that A4: (for i holds (i in I() implies Q[ i,( f . i ) ])) from PBOOLE:sch 3(A1);
take f;
thus thesis by A4;
end;
