environ
vocabularies NUMBERS,SUPINF_1,REAL_1,COMPLEX1,CARD_1,XXREAL_0,ARYTM_1,ARYTM_3,RELAT_1,MESFUNC1,MEASURE6;
notations NUMBERS,XXREAL_0,COMPLEX1,REAL_1,SUPINF_1,SUPINF_2,MEASURE6,EXTREAL1,MESFUNC1;
definitions SUPINF_2,XXREAL_3;
theorems MEASURE6,SUPINF_2,EXTREAL1,MESFUNC1,ABSVALUE,XCMPLX_1,COMPLEX1,XREAL_1,XXREAL_0,XXREAL_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
registrations NUMBERS,XXREAL_0,XREAL_0,MEMBERED,XBOOLE_0,XXREAL_3;
constructors REAL_1,COMPLEX1,SUPINF_2,MEASURE6,EXTREAL1,MESFUNC1,SUPINF_1,BINOP_2;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve x for R_eal;
reserve y for R_eal;
theorem
|. ( x * y ) .| = ( |. x .| * |. y .| )
proof
per cases ;
suppose x = ( 0 );

then (|. x .| = ( 0 ) & |. ( x * y ) .| = ( 0 )) by EXTREAL1:def 1;
hence thesis;
end;
suppose A1: ( 0 ) < x;

now
per cases ;
suppose y = ( 0 );

then (|. y .| = ( 0 ) & |. ( x * y ) .| = ( 0 )) by EXTREAL1:def 1;
hence thesis;
end;
suppose A2: ( 0 ) < y;

then A3: |. y .| = y by EXTREAL1:def 1;
|. x .| = x by A1,EXTREAL1:def 1;
hence thesis by A1,A2,A3,EXTREAL1:def 1;
end;
suppose A4: y < ( 0 );

then A5: |. y .| = ( - y ) by EXTREAL1:def 1;
|. x .| = x by A1,EXTREAL1:def 1;
then ( |. x .| * |. y .| ) = ( - ( x * y ) ) by A5,XXREAL_3:92;
hence thesis by A1,A4,EXTREAL1:def 1;
end;
end;
hence thesis;
end;
suppose A6: x < ( 0 );

now
per cases ;
suppose y = ( 0 );

then (|. y .| = ( 0 ) & |. ( x * y ) .| = ( 0 )) by EXTREAL1:def 1;
hence thesis;
end;
suppose A7: ( 0 ) < y;

then |. y .| = y by EXTREAL1:def 1;
then A8: ( |. x .| * |. y .| ) = ( ( - x ) * y ) by A6,EXTREAL1:def 1;
|. ( x * y ) .| = ( - ( x * y ) ) by A6,A7,EXTREAL1:def 1;
hence thesis by A8,XXREAL_3:92;
end;
suppose A9: y < ( 0 );

then |. y .| = ( - y ) by EXTREAL1:def 1;
then ( |. x .| * |. y .| ) = ( ( - x ) * ( - y ) ) by A6,EXTREAL1:def 1;
then ( |. x .| * |. y .| ) = ( - ( x * ( - y ) ) ) by XXREAL_3:92
.= ( - ( - ( x * y ) ) ) by XXREAL_3:92;
hence thesis by A6,A9,EXTREAL1:def 1;
end;
end;
hence thesis;
end;
end;
