environ
vocabularies ORDINAL1,XBOOLE_0,ORDINAL2,TARSKI,SUBSET_1,ORDINAL3,ARYTM_3;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,ORDINAL2,ORDINAL3,CKB3,CKB4,CKB11,CKB20,CKB23,CKB31,CKB41,CKB51,CKB52,CKB58,CKB59,CKB67,CKB68;
definitions TARSKI,ORDINAL1,CKB3,CKB4,CKB11,CKB20,CKB23,CKB31,CKB41,CKB51,CKB52,CKB58,CKB67,CKB68;
theorems TARSKI,XBOOLE_0,ZFMISC_1,ORDINAL1,ORDINAL2,ORDINAL3,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB45,CKB46,CKB47,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68;
schemes ORDINAL1;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,ORDINAL2,ORDINAL3,CKB9,CKB10,CKB43,CKB44,CKB48;
constructors SUBSET_1,ORDINAL3,CKB3,CKB4,CKB11,CKB20,CKB23,CKB31,CKB41,CKB51,CKB52,CKB58,CKB67,CKB68;
requirements BOOLE,SUBSET,NUMERALS;
begin
reserve l for  natural Ordinal;
reserve i for  natural Ordinal;
reserve j for  natural Ordinal;
reserve k for  natural Ordinal;
theorem
Th52: ((j <> ( {} ) & l <> ( {} )) implies ( ( i / j ) + ( k / l ) ) = ( ( ( i *^ l ) +^ ( j *^ k ) ) / ( j *^ l ) ))
proof
assume that
A1: j <> ( {} )
and
A2: l <> ( {} );
A3: (( denominator ( k / l ) ) = ( RED (l,k) ) & ( denominator ( i / j ) ) = ( RED (j,i) )) by A1,A2,CKB63:1;
(( numerator ( k / l ) ) = ( RED (k,l) ) & ( numerator ( i / j ) ) = ( RED (i,j) )) by A1,A2,CKB63:1;
hence ( ( i / j ) + ( k / l ) ) = ( ( ( ( ( RED (i,j) ) *^ ( RED (l,k) ) ) +^ ( ( RED (j,i) ) *^ ( RED (k,l) ) ) ) *^ ( i hcf j ) ) / ( ( ( RED (j,i) ) *^ ( RED (l,k) ) ) *^ ( i hcf j ) ) ) by A1,A3,CKB25:1,CKB65:1
.= ( ( ( ( ( RED (i,j) ) *^ ( RED (l,k) ) ) +^ ( ( RED (j,i) ) *^ ( RED (k,l) ) ) ) *^ ( i hcf j ) ) / ( ( RED (l,k) ) *^ ( ( RED (j,i) ) *^ ( i hcf j ) ) ) ) by ORDINAL3:50
.= ( ( ( ( ( RED (i,j) ) *^ ( RED (l,k) ) ) +^ ( ( RED (j,i) ) *^ ( RED (k,l) ) ) ) *^ ( i hcf j ) ) / ( ( RED (l,k) ) *^ j ) ) by CKB32:1
.= ( ( ( ( ( RED (i,j) ) *^ ( RED (l,k) ) ) *^ ( i hcf j ) ) +^ ( ( ( RED (j,i) ) *^ ( RED (k,l) ) ) *^ ( i hcf j ) ) ) / ( ( RED (l,k) ) *^ j ) ) by ORDINAL3:46
.= ( ( ( ( RED (l,k) ) *^ ( ( RED (i,j) ) *^ ( i hcf j ) ) ) +^ ( ( ( RED (j,i) ) *^ ( RED (k,l) ) ) *^ ( i hcf j ) ) ) / ( ( RED (l,k) ) *^ j ) ) by ORDINAL3:50
.= ( ( ( ( RED (l,k) ) *^ i ) +^ ( ( ( RED (j,i) ) *^ ( RED (k,l) ) ) *^ ( i hcf j ) ) ) / ( ( RED (l,k) ) *^ j ) ) by CKB32:1
.= ( ( ( ( RED (l,k) ) *^ i ) +^ ( ( RED (k,l) ) *^ ( ( RED (j,i) ) *^ ( i hcf j ) ) ) ) / ( ( RED (l,k) ) *^ j ) ) by ORDINAL3:50
.= ( ( ( ( RED (l,k) ) *^ i ) +^ ( ( RED (k,l) ) *^ j ) ) / ( ( RED (l,k) ) *^ j ) ) by CKB32:1
.= ( ( ( ( ( RED (l,k) ) *^ i ) +^ ( ( RED (k,l) ) *^ j ) ) *^ ( k hcf l ) ) / ( ( ( RED (l,k) ) *^ j ) *^ ( k hcf l ) ) ) by A2,CKB25:1,CKB65:1
.= ( ( ( ( ( RED (l,k) ) *^ i ) +^ ( ( RED (k,l) ) *^ j ) ) *^ ( k hcf l ) ) / ( j *^ ( ( RED (l,k) ) *^ ( k hcf l ) ) ) ) by ORDINAL3:50
.= ( ( ( ( ( RED (l,k) ) *^ i ) +^ ( ( RED (k,l) ) *^ j ) ) *^ ( k hcf l ) ) / ( j *^ l ) ) by CKB32:1
.= ( ( ( ( ( RED (l,k) ) *^ i ) *^ ( k hcf l ) ) +^ ( ( ( RED (k,l) ) *^ j ) *^ ( k hcf l ) ) ) / ( j *^ l ) ) by ORDINAL3:46
.= ( ( ( i *^ ( ( RED (l,k) ) *^ ( k hcf l ) ) ) +^ ( ( ( RED (k,l) ) *^ j ) *^ ( k hcf l ) ) ) / ( j *^ l ) ) by ORDINAL3:50
.= ( ( ( i *^ l ) +^ ( ( ( RED (k,l) ) *^ j ) *^ ( k hcf l ) ) ) / ( j *^ l ) ) by CKB32:1
.= ( ( ( i *^ l ) +^ ( j *^ ( ( RED (k,l) ) *^ ( k hcf l ) ) ) ) / ( j *^ l ) ) by ORDINAL3:50
.= ( ( ( i *^ l ) +^ ( j *^ k ) ) / ( j *^ l ) ) by CKB32:1;
end;
