environ
vocabularies NAT_1,VECTSP_1,SUBSET_1,MATRIX_1,REWRITE1,RELAT_1,MESFUNC1,ALGSTR_0,ARYTM_1,FINSEQ_1,TREES_1,ARYTM_3,SUPINF_2,XXREAL_0,CARD_1,QC_LANG1,ZFMISC_1,RELAT_2,FUNCOP_1,MATRIX_2,GROUP_1,MATRIX_6;
notations TARSKI,ZFMISC_1,NUMBERS,FINSEQ_1,RLVECT_1,GROUP_1,VECTSP_1,NAT_1,STRUCT_0,MATRIX_1,MATRIX_2,MATRIX_3,MATRIX_4,XXREAL_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB15;
definitions MATRIX_4,CKB1,CKB2,CKB3,CKB15;
theorems ZFMISC_1,RLVECT_1,MATRIX_1,MATRIX_2,MATRIX_4,MATRIX_3,VECTSP_1,NAT_1,CARD_2,XXREAL_0,CKB1,CKB2,CKB3,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20;
registrations RELSET_1,XREAL_0,STRUCT_0,VECTSP_1,ORDINAL1;
constructors XXREAL_0,FVSUM_1,MATRIX_3,MATRIX_4,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB15;
begin
reserve n for Nat;
reserve K for Field;
reserve M for (Matrix of n,K);
theorem
((M is  invertible & n > ( 0 )) implies ( ( M @ ) ~ ) = ( ( M ~ ) @ ))
proof
assume that
A1: M is  invertible
and
A2: n > ( 0 );
set M1 = ( M @ );
set M2 = ( ( M ~ ) @ );
A3: (( width M ) = n & ( width ( M ~ ) ) = n) by MATRIX_1:24;
( len M ) = n by MATRIX_1:24;
then A4: ( ( ( M ~ ) * M ) @ ) = ( ( M @ ) * ( ( M ~ ) @ ) ) by A2,A3,MATRIX_3:22;
A5: ( M ~ ) is_reverse_of M by A1,CKB15:def 1;
then ( ( M ~ ) * M ) = ( 1. (K,n) ) by CKB2:def 1;
then A6: ( M1 * M2 ) = ( 1. (K,n) ) by A4,CKB18:1;
( len ( M ~ ) ) = n by MATRIX_1:24;
then ( ( M * ( M ~ ) ) @ ) = ( ( ( M ~ ) @ ) * ( M @ ) ) by A2,A3,MATRIX_3:22;
then ( M1 * M2 ) = ( M2 * M1 ) by A5,A4,CKB2:def 1;
then A7: M1 is_reverse_of M2 by A6,CKB2:def 1;
then M1 is  invertible by CKB3:def 1;
hence thesis by A7,CKB15:def 1;
end;
