environ
vocabularies REALSET1,FINSEQ_1,GROUP_3,FUNCT_1,RLSUB_1,GROUP_2,RELAT_1,GROUP_6,XBOOLE_0,QC_LANG1,GROUP_1,GRAPH_1,ARYTM_1,ARYTM_3,ZFMISC_1,NUMBERS,SUBSET_1,XXREAL_1,STRUCT_0,NEWTON,TARSKI,NAT_1,PARTFUN1,PRE_TOPC,XXREAL_0,CARD_1,GROUP_4,NATTRA_1,CARD_3,BINOP_1,GROUP_5,GRSOLV_1,GRNILP_1,BCIALG_2,ALGSTR_0;
notations TARSKI,XBOOLE_0,SUBSET_1,XCMPLX_0,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,STRUCT_0,ALGSTR_0,PARTFUN1,FINSEQ_1,ZFMISC_1,NAT_1,XXREAL_0,NUMBERS,REALSET1,DOMAIN_1,GROUP_1,GROUP_3,GR_CY_1,GRSOLV_1,GROUP_4,GROUP_5,GROUP_2,GROUP_6,CKB10,CKB20,CKB25;
definitions GROUP_2,GROUP_6,TARSKI,FINSEQ_1,GROUP_4,ALGSTR_0,GROUP_3,GROUP_5,GRSOLV_1,REALSET1,CKB20,CKB25;
theorems FINSEQ_1,GROUP_2,GROUP_3,TARSKI,GROUP_5,GROUP_6,FINSEQ_2,FUNCT_2,RELAT_1,XBOOLE_0,XBOOLE_1,NAT_1,GROUP_1,PARTFUN1,FINSEQ_3,SUBSET_1,GROUP_4,FUNCT_1,GRSOLV_1,STRUCT_0,GROUP_11,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB22,CKB23,CKB24,CKB25,CKB27,CKB28,CKB29;
schemes XBOOLE_0,FUNCT_1,FINSEQ_1,FINSEQ_2;
registrations XBOOLE_0,SUBSET_1,RELAT_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,INT_1,FINSEQ_1,STRUCT_0,GROUP_1,GROUP_2,GROUP_3,GROUP_6,GR_CY_1,ALGSTR_0,RELSET_1,CKB21,CKB26;
constructors BINOP_1,XXREAL_0,BINARITH,REALSET2,GROUP_4,GROUP_5,GRSOLV_1,RELSET_1,GR_CY_1,REALSET1,CKB10,CKB20,CKB25;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve G for Group;
reserve H for (Subgroup of G);
reserve H1 for (Subgroup of G);
reserve H2 for (Subgroup of G);
theorem
Th23: (for G being Group holds (for H,G1 being (Subgroup of G) holds (for G2 being  strict  normal (Subgroup of G) holds (for H1 being (Subgroup of H) holds (for H2 being  normal (Subgroup of H) holds ((((G2 is (Subgroup of G1) & ( G1 ./. ( (G1,G2) `*` ) ) is (Subgroup of ( center ( G ./. G2 ) ))) & H1 = ( G1 /\ H )) & H2 = ( G2 /\ H )) implies ( H1 ./. ( (H1,H2) `*` ) ) is (Subgroup of ( center ( H ./. H2 ) ))))))))
proof
let G being Group;
let H being (Subgroup of G);
let G1 being (Subgroup of G);
let G2 being  strict  normal (Subgroup of G);
let H1 being (Subgroup of H);
let H2 being  normal (Subgroup of H);
assume that
A1: G2 is (Subgroup of G1)
and
A2: ( G1 ./. ( (G1,G2) `*` ) ) is (Subgroup of ( center ( G ./. G2 ) ))
and
A3: (H1 = ( G1 /\ H ) & H2 = ( G2 /\ H ));
A4: [. G1,( (Omega). G ) .] is (Subgroup of G2) by A1,A2,CKB27:1;
A5: H2 is  strict  strict (Subgroup of H1) by A1,A3,GROUP_2:92;
then A6: ( (H1,H2) `*` ) = H2 by GROUP_6:def 1;
then reconsider I = H2 as  normal (Subgroup of H1);
reconsider J = ( H1 ./. ( (H1,H2) `*` ) ) as (Subgroup of ( H ./. H2 )) by A5,GROUP_6:28;
(for T being (Element of ( H ./. H2 )) holds (T in J implies T in ( center ( H ./. H2 ) )))
proof
let T being (Element of ( H ./. H2 ));
assume A7: T in J;
(for S being (Element of ( H ./. H2 )) holds ( S * T ) = ( T * S ))
proof
let S being (Element of ( H ./. H2 ));
consider h being (Element of H) such that A8: (S = ( h * H2 ) & S = ( H2 * h )) by GROUP_6:21;
consider h1 being (Element of H1) such that A9: (T = ( h1 * I ) & T = ( I * h1 )) by A6,A7,GROUP_6:23;
reconsider h2 = h1 as (Element of H) by GROUP_2:42;
A10: ((( @ S ) = S & ( @ T ) = T) & ( h1 * I ) = ( h2 * H2 )) by GROUP_6:2;
then A11: ( S * T ) = ( ( h * H2 ) * ( h2 * H2 ) ) by A8,A9,GROUP_6:def 3
.= ( ( h * h2 ) * H2 ) by GROUP_11:1;
A12: ( T * S ) = ( ( h2 * H2 ) * ( h * H2 ) ) by A8,A9,A10,GROUP_6:def 3
.= ( ( h2 * h ) * H2 ) by GROUP_11:1;
A13: [. h2,h .] in H by STRUCT_0:def 5;
reconsider a = h as (Element of G) by GROUP_2:42;
A14: a in ( (Omega). G ) by STRUCT_0:def 5;
H1 is (Subgroup of G1) by A3,GROUP_2:88;
then reconsider b = h1 as (Element of G1) by GROUP_2:42;
reconsider c = b as (Element of G) by GROUP_2:42;
b in G1 by STRUCT_0:def 5;
then [. c,a .] in [. G1,( (Omega). G ) .] by A14,GROUP_5:65;
then A15: [. c,a .] in G2 by A4,GROUP_2:40;
A16: ( a " ) = ( h " ) by GROUP_2:48;
( c " ) = ( h2 " ) by GROUP_2:48;
then A17: ( ( h2 " ) * ( h " ) ) = ( ( c " ) * ( a " ) ) by A16,GROUP_2:43;
( h2 * h ) = ( c * a ) by GROUP_2:43;
then A18: ( ( ( h2 " ) * ( h " ) ) * ( h2 * h ) ) = ( ( ( c " ) * ( a " ) ) * ( c * a ) ) by A17,GROUP_2:43;
A19: [. h2,h .] = ( ( ( h2 " ) * ( h " ) ) * ( h2 * h ) ) by GROUP_5:16;
[. c,a .] = ( ( ( c " ) * ( a " ) ) * ( c * a ) ) by GROUP_5:16;
then [. h2,h .] in H2 by A3,A13,A15,A18,A19,GROUP_2:82;
then ( ( h * h2 ) * H2 ) = ( ( h * h2 ) * ( [. h2,h .] * H2 ) ) by GROUP_2:113
.= ( ( h * h2 ) * ( ( ( ( h2 " ) * ( h " ) ) * ( h2 * h ) ) * H2 ) ) by GROUP_5:16
.= ( ( ( h * h2 ) * ( ( ( h2 " ) * ( h " ) ) * ( h2 * h ) ) ) * H2 ) by GROUP_2:32
.= ( ( ( ( h * h2 ) * ( ( h2 " ) * ( h " ) ) ) * ( h2 * h ) ) * H2 ) by GROUP_1:def 3
.= ( ( ( h * ( h2 * ( ( h2 " ) * ( h " ) ) ) ) * ( h2 * h ) ) * H2 ) by GROUP_1:def 3
.= ( ( ( h * ( ( h2 * ( h2 " ) ) * ( h " ) ) ) * ( h2 * h ) ) * H2 ) by GROUP_1:def 3
.= ( ( ( h * ( ( 1_ H ) * ( h " ) ) ) * ( h2 * h ) ) * H2 ) by GROUP_1:def 5
.= ( ( ( h * ( h " ) ) * ( h2 * h ) ) * H2 ) by GROUP_1:def 4
.= ( ( ( 1_ H ) * ( h2 * h ) ) * H2 ) by GROUP_1:def 5
.= ( ( h2 * h ) * H2 ) by GROUP_1:def 4;
hence thesis by A11,A12;
end;
hence thesis by GROUP_5:77;
end;
hence thesis by GROUP_2:58;
end;
