environ
vocabularies NUMBERS,SUBSET_1,FINSEQ_2,MARGREL1,CARD_1,ARYTM_3,INT_2,NAT_1,RELAT_1,XXREAL_0,INT_1,ARYTM_1,GRCAT_1,XBOOLEAN,FINSEQ_1,PARTFUN1,FUNCT_1,POWER,BINARI_3,FUNCOP_1,XBOOLE_0,BINARITH,MATRIX_1,INCSP_1,ORDINAL4,FUNCT_7,FUNCT_2,TARSKI,TREES_1,IDEA_1;
notations TARSKI,XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,INT_1,INT_2,NAT_1,NAT_D,MARGREL1,RELAT_1,FUNCT_1,FUNCOP_1,MATRIX_1,PARTFUN1,FUNCT_2,FUNCT_7,SERIES_1,FINSEQ_1,FINSEQ_2,RECDEF_1,BINARITH,BINARI_3,XXREAL_0,CKB8,CKB9,CKB12,CKB15,CKB17,CKB18,CKB19,CKB26,CKB29,CKB32,CKB33,CKB39,CKB40,CKB41;
definitions TARSKI,FINSEQ_2,XBOOLEAN,CKB8,CKB9,CKB15,CKB17,CKB18,CKB19,CKB26,CKB29,CKB32,CKB33,CKB39,CKB40,CKB41;
theorems NAT_1,NAT_2,NEWTON,INT_1,INT_2,FINSEQ_1,FINSEQ_2,FUNCT_1,FUNCT_2,FUNCT_7,FUNCOP_1,POWER,EULER_1,EULER_2,BINARITH,BINARI_3,MATRIX_1,RELSET_1,RELAT_1,XBOOLE_1,XREAL_1,XXREAL_0,XBOOLEAN,NAT_D,PARTFUN1,ORDINAL1,XREAL_0,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41;
schemes FINSEQ_1,FINSEQ_2,NAT_1,FUNCT_2;
registrations XBOOLE_0,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,XXREAL_0,XREAL_0,NAT_1,INT_1,FINSEQ_1,MARGREL1,FUNCT_7,VALUED_0,CARD_1,FINSEQ_2,RELSET_1;
constructors PARTFUN1,XXREAL_0,NAT_1,NAT_D,SERIES_1,BINARITH,WSIERP_1,FUNCT_7,MATRIX_1,BINARI_3,RECDEF_1,RELSET_1,CKB8,CKB9,CKB12,CKB15,CKB17,CKB18,CKB19,CKB26,CKB29,CKB32,CKB33,CKB39,CKB40,CKB41;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve m for (FinSequence of ( NAT ));
reserve k for (FinSequence of ( NAT ));
theorem
Th27: (( len m ) >= 4 implies (((( ( IDEAoperationA (m,k,n) ) . 1 ) is_expressible_by n & ( ( IDEAoperationA (m,k,n) ) . 2 ) is_expressible_by n) & ( ( IDEAoperationA (m,k,n) ) . 3 ) is_expressible_by n) & ( ( IDEAoperationA (m,k,n) ) . 4 ) is_expressible_by n))
proof
assume A1: ( len m ) >= 4;
then 1 <= ( len m ) by XXREAL_0:2;
then 1 in ( Seg ( len m ) ) by FINSEQ_1:1;
then 1 in ( dom m ) by FINSEQ_1:def 3;
then A2: ( ( IDEAoperationA (m,k,n) ) . 1 ) = ( MUL_MOD (( m . 1 ),( k . 1 ),n) ) by CKB39:def 1;
3 <= ( len m ) by A1,XXREAL_0:2;
then 3 in ( Seg ( len m ) ) by FINSEQ_1:1;
then 3 in ( dom m ) by FINSEQ_1:def 3;
then A3: ( ( IDEAoperationA (m,k,n) ) . 3 ) = ( ADD_MOD (( m . 3 ),( k . 3 ),n) ) by CKB39:def 1;
2 <= ( len m ) by A1,XXREAL_0:2;
then 2 in ( Seg ( len m ) ) by FINSEQ_1:1;
then 2 in ( dom m ) by FINSEQ_1:def 3;
then A4: ( ( IDEAoperationA (m,k,n) ) . 2 ) = ( ADD_MOD (( m . 2 ),( k . 2 ),n) ) by CKB39:def 1;
4 in ( Seg ( len m ) ) by A1,FINSEQ_1:1;
then 4 in ( dom m ) by FINSEQ_1:def 3;
then ( ( IDEAoperationA (m,k,n) ) . 4 ) = ( MUL_MOD (( m . 4 ),( k . 4 ),n) ) by CKB39:def 1;
hence thesis by A2,A4,A3,CKB24:1,CKB37:1;
end;
