environ
vocabularies NUMBERS,SUBSET_1,REAL_1,COMSEQ_1,COMPLEX1,RELAT_1,ARYTM_1,ARYTM_3,CARD_1,XXREAL_0,FUNCT_1,XREAL_0,ORDINAL1,XBOOLE_0,PARTFUN1,VALUED_0,VALUED_1,XXREAL_2,FUNCOP_1,SEQ_2,ORDINAL2,SEQ_1,XCMPLX_0;
notations XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,VALUED_1,SEQ_1,SEQ_2,NAT_1,COMSEQ_1,XXREAL_0,CKB3,CKB4,CKB11,CKB14,CKB15;
definitions VALUED_1,SEQ_2,PARTFUN1,CKB3,CKB4,CKB11,CKB14,CKB15;
theorems COMSEQ_1,SEQ_2,FINSEQ_2,COMPLEX1,NAT_1,SUBSET_1,FUNCT_2,XREAL_0,XCMPLX_0,XCMPLX_1,FUNCOP_1,XREAL_1,XXREAL_0,VALUED_1,CKB1,CKB2,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17;
schemes NAT_1,SEQ_1;
registrations XBOOLE_0,ORDINAL1,RELSET_1,FUNCT_2,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,VALUED_1,VALUED_0,CKB5,CKB12,CKB18;
constructors PARTFUN1,FUNCOP_1,REAL_1,SQUARE_1,NAT_1,COMPLEX1,SEQ_2,VALUED_1,SEQ_1,RELSET_1,CKB3,CKB14,CKB15;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
reserve g for (Element of ( COMPLEX ));
reserve s for Complex_Sequence;
registration
let s being  convergent Complex_Sequence;
cluster |. s .| ->  convergent for Real_Sequence;
coherence
proof
|. s .| is  convergent
proof
consider g such that A1: (for p being Real holds (( 0 ) < p implies (ex n st (for m holds (n <= m implies |. ( ( s . m ) - g ) .| < p))))) by CKB14:def 1;
take |. g .|;
let p being  real number;
assume A2: ( 0 ) < p;
p is Real by XREAL_0:def 1;
then consider n such that A3: (for m holds (n <= m implies |. ( ( s . m ) - g ) .| < p)) by A1,A2;
take n;
let m;
assume n <= m;
then |. ( ( s . m ) - g ) .| < p by A3;
then ( ( abs ( |. ( s . m ) .| - |. g .| ) ) + |. ( ( s . m ) - g ) .| ) < ( p + |. ( ( s . m ) - g ) .| ) by COMPLEX1:64,XREAL_1:8;
then ( ( ( abs ( |. ( s . m ) .| - |. g .| ) ) + |. ( ( s . m ) - g ) .| ) - |. ( ( s . m ) - g ) .| ) < ( ( p + |. ( ( s . m ) - g ) .| ) - |. ( ( s . m ) - g ) .| ) by XREAL_1:9;
hence thesis by VALUED_1:18;
end;
hence thesis;
end;
end;
