environ
vocabularies NUMBERS,XBOOLE_0,ORDERS_2,SUBSET_1,CONNSP_1,FIN_TOPO,XXREAL_0,FINTOPO3,TARSKI,ARYTM_3,ARYTM_1,CARD_1,RELAT_2,FUNCT_1,STRUCT_0,RELAT_1,NAT_1,FINSEQ_1,ZFMISC_1,FINTOPO4;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,FUNCT_1,RELSET_1,FUNCT_2,FINSEQ_1,STRUCT_0,ORDERS_2,FIN_TOPO,FINTOPO3,NAT_D,ENUMSET1,LIMFUNC1,CKB1,CKB15,CKB20,CKB21;
definitions TARSKI,FIN_TOPO,FINSEQ_1,CKB1,CKB15,CKB20,CKB21;
theorems TARSKI,FINSEQ_1,NAT_1,FUNCT_1,FUNCT_2,XBOOLE_0,XBOOLE_1,FIN_TOPO,FINTOPO3,RELAT_1,ENUMSET1,XREAL_1,XXREAL_0,ORDINAL1,RELSET_1,XREAL_0,NAT_D,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
schemes NAT_1,FUNCT_2,RELSET_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,XXREAL_0,XREAL_0,NAT_1,STRUCT_0,FIN_TOPO,ORDINAL1,FINSEQ_1;
constructors ENUMSET1,NAT_1,EQREL_1,LIMFUNC1,NAT_D,FIN_TOPO,FINTOPO3,FINSEQ_1,RELSET_1,CKB1,CKB15,CKB20,CKB21;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
definition
let n being Nat;
func Nbdc1 n -> (Relation of ( Seg n ))
means
:Def5: (for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (((((1 < i & i < n) implies ( Im (it,i) ) = { i,( i -' 1 ),( i + 1 ) }) & ((i = 1 & i < n) implies ( Im (it,i) ) = { i,n,( i + 1 ) })) & ((1 < i & i = n) implies ( Im (it,i) ) = { i,( i -' 1 ),1 })) & ((i = 1 & i = n) implies ( Im (it,i) ) = { i }))));
existence
proof
defpred P[ set,set ]
 means
(for i being (Element of ( NAT )) holds (i = $1 implies (((((1 < i & i < n) implies $2 = { i,( i -' 1 ),( i + 1 ) }) & ((i = 1 & i < n) implies $2 = { i,n,( i + 1 ) })) & ((1 < i & i = n) implies $2 = { i,( i -' 1 ),1 })) & ((i = 1 & i = n) implies $2 = { i }))));
A1: (for x being set holds (x in ( Seg n ) implies (ex y being set st (y in ( bool ( Seg n ) ) & P[ x,y ]))))
proof
let x being set;
assume A2: x in ( Seg n );
then reconsider i2 = x as (Element of ( NAT ));
A3: (1 <= i2 & i2 <= n) by A2,FINSEQ_1:1;
now
per cases  by A3,XXREAL_0:1;
case A4: (1 < i2 & i2 < n);
i2 <= ( i2 + 1 ) by NAT_1:12;
then A5: 1 < ( i2 + 1 ) by A4,XXREAL_0:2;
( i2 + 1 ) <= n by A4,NAT_1:13;
then A6: ( i2 + 1 ) in ( Seg n ) by A5;
set y0 = { i2,( i2 -' 1 ),( i2 + 1 ) };
( i2 - 1 ) > ( 0 ) by A4,XREAL_1:50;
then ( i2 -' 1 ) > ( 0 ) by XREAL_0:def 2;
then A7: ( i2 -' 1 ) >= ( ( 0 ) + 1 ) by NAT_1:13;
( i2 -' 1 ) <= i2 by NAT_D:35;
then ( i2 -' 1 ) < n by A4,XXREAL_0:2;
then A8: ( i2 -' 1 ) in ( Seg n ) by A7;
A9: y0 c= ( Seg n )
proof
let z1 being set;
assume z1 in y0;
hence thesis by A2,A8,A6,ENUMSET1:def 1;
end;
P[ x,y0 ] by A4;
hence thesis by A9;
end;
case A10: (i2 = 1 & i2 < n);
then ( i2 + 1 ) <= n by NAT_1:13;
then A11: ( i2 + 1 ) in ( Seg n ) by A10;
set y0 = { i2,n,( i2 + 1 ) };
A12: n in ( Seg n ) by A10,FINSEQ_1:1;
A13: y0 c= ( Seg n )
proof
let z1 being set;
assume z1 in y0;
hence thesis by A2,A12,A11,ENUMSET1:def 1;
end;
P[ x,y0 ] by A10;
hence thesis by A13;
end;
case A14: (1 < i2 & i2 = n);
then ( i2 - 1 ) > ( 0 ) by XREAL_1:50;
then ( i2 -' 1 ) > ( 0 ) by XREAL_0:def 2;
then A15: ( i2 -' 1 ) >= ( ( 0 ) + 1 ) by NAT_1:13;
set y0 = { i2,( i2 -' 1 ),1 };
A16: 1 in ( Seg n ) by A14;
( i2 -' 1 ) <= n by A14,NAT_D:35;
then A17: ( i2 -' 1 ) in ( Seg n ) by A15;
A18: y0 c= ( Seg n )
proof
let z1 being set;
assume z1 in y0;
hence thesis by A2,A17,A16,ENUMSET1:def 1;
end;
P[ x,y0 ] by A14;
hence thesis by A18;
end;
case A19: (i2 = 1 & i2 = n);
set y0 = { i2 };
A20: y0 c= ( Seg n )
proof
let z1 being set;
assume z1 in y0;
hence thesis by A2,TARSKI:def 1;
end;
P[ x,y0 ] by A19;
hence thesis by A20;
end;
end;
hence thesis;
end;
consider f2 being (Function of ( Seg n ),( bool ( Seg n ) )) such that A21: (for x3 being set holds (x3 in ( Seg n ) implies P[ x3,( f2 . x3 ) ])) from FUNCT_2:sch 1(A1);
consider R being (Relation of ( Seg n )) such that A22: (for i being set holds (i in ( Seg n ) implies ( Im (R,i) ) = ( f2 . i ))) by FUNCT_2:93;
take R;
let i being (Element of ( NAT ));
assume A23: i in ( Seg n );
then ( Im (R,i) ) = ( f2 . i ) by A22;
hence thesis by A21,A23;
end;
uniqueness
proof
let f1 being (Relation of ( Seg n )),f2 being (Relation of ( Seg n ));
assume that
A24: (for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (((((1 < i & i < n) implies ( Im (f1,i) ) = { i,( i -' 1 ),( i + 1 ) }) & ((i = 1 & i < n) implies ( Im (f1,i) ) = { i,n,( i + 1 ) })) & ((1 < i & i = n) implies ( Im (f1,i) ) = { i,( i -' 1 ),1 })) & ((i = 1 & i = n) implies ( Im (f1,i) ) = { i }))))
and
A25: (for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (((((1 < i & i < n) implies ( Im (f2,i) ) = { i,( i -' 1 ),( i + 1 ) }) & ((i = 1 & i < n) implies ( Im (f2,i) ) = { i,n,( i + 1 ) })) & ((1 < i & i = n) implies ( Im (f2,i) ) = { i,( i -' 1 ),1 })) & ((i = 1 & i = n) implies ( Im (f2,i) ) = { i }))));
(for x being set holds (x in ( Seg n ) implies ( Im (f1,x) ) = ( Im (f2,x) )))
proof
let x being set;
assume A26: x in ( Seg n );
then reconsider i2 = x as (Element of ( NAT ));
A27: (1 <= i2 & i2 <= n) by A26,FINSEQ_1:1;
per cases  by A27,XXREAL_0:1;
suppose A28: (1 < i2 & i2 < n);

set y0 = { i2,( i2 -' 1 ),( i2 + 1 ) };
( Im (f1,x) ) = y0 by A24,A26,A28;
hence thesis by A25,A26,A28;
end;
suppose A29: (i2 = 1 & i2 < n);

set y0 = { i2,n,( i2 + 1 ) };
( Im (f1,x) ) = y0 by A24,A26,A29;
hence thesis by A25,A26,A29;
end;
suppose A30: (1 < i2 & i2 = n);

set y0 = { i2,( i2 -' 1 ),1 };
( Im (f1,x) ) = y0 by A24,A26,A30;
hence thesis by A25,A26,A30;
end;
suppose A31: (i2 = 1 & i2 = n);

set y0 = { i2 };
( Im (f1,x) ) = y0 by A24,A26,A31;
hence thesis by A25,A26,A31;
end;
end;
hence f1 = f2 by RELSET_1:31;
end;
end;
