environ
vocabularies XBOOLE_0,TARSKI,ORDINAL1,SUBSET_1,LATTICES,CARD_FIL,FILTER_0,INT_2,PBOOLE,GROUP_6,FUNCT_1,STRUCT_0,EQREL_1,FUNCT_2,RELAT_1,WELLORD1,FILTER_1,XBOOLEAN,FINSUB_1,LATTICE2,SETWISEO,BINOP_1,FUNCOP_1,XXREAL_2,VECTSP_1,ZFMISC_1,SETFAM_1,LATTICE4;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,RELAT_1,ORDINAL1,FUNCT_1,PARTFUN1,FUNCT_2,BINOP_1,FINSUB_1,STRUCT_0,LATTICES,LATTICE2,FILTER_0,FUNCOP_1,SETWISEO,WELLORD1,FILTER_1,CKB5;
definitions TARSKI,FILTER_0,LATTICES,XBOOLE_0,STRUCT_0,CKB5;
theorems LATTICES,ZFMISC_1,FUNCT_2,FILTER_0,SETFAM_1,ORDERS_1,TARSKI,SETWISEO,LATTICE2,FUNCOP_1,FILTER_1,WELLORD1,RELAT_1,XBOOLE_1,FUNCT_1,CKB1,CKB3,CKB4,CKB5,CKB6;
schemes FUNCT_2,SETWISEO,BINOP_2,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FUNCT_2,STRUCT_0,LATTICES,FILTER_0,LATTICE2,CKB2;
constructors WELLORD1,DOMAIN_1,SETWISEO,LATTICE2,FILTER_1,GRCAT_1,FUNCOP_1,RELSET_1,FILTER_0,CKB5;
requirements BOOLE,SUBSET;
begin
reserve L1 for Lattice;
reserve L2 for Lattice;
reserve a1 for (Element of L1);
reserve b1 for (Element of L1);
reserve f for (Homomorphism of L1,L2);
theorem
Th8: (f is  one-to-one implies (a1 [= b1 iff ( f . a1 ) [= ( f . b1 )))
proof
assume A1: f is  one-to-one;
reconsider f as (Function of (the carrier of L1),(the carrier of L2));
(( f . a1 ) [= ( f . b1 ) implies a1 [= b1)
proof
assume ( f . a1 ) [= ( f . b1 );
then ( ( f . a1 ) "\/" ( f . b1 ) ) = ( f . b1 ) by LATTICES:def 3;
then ( f . ( a1 "\/" b1 ) ) = ( f . b1 ) by CKB5:def 1;
hence ( a1 "\/" b1 ) = b1 by A1,FUNCT_2:19;
end;
hence thesis by CKB6:1;
end;
