environ
vocabularies RLVECT_1,XBOOLE_0,ANALOAF,SUBSET_1,ANALMETR,ANALORT,STRUCT_0,SYMSP_1,DIRORT;
notations STRUCT_0,RLVECT_1,ANALOAF,ANALMETR,ANALORT,CKB1,CKB4,CKB6,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17;
definitions CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17;
theorems ANALMETR,ANALORT,CKB2,CKB3,CKB4,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17;
registrations ANALOAF,ANALORT,CKB5;
constructors ANALMETR,ANALORT,CKB4,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17;
begin
reserve AS for Oriented_Orthogonality_Space;
reserve u for (Element of AS);
reserve u1 for (Element of AS);
reserve v1 for (Element of AS);
reserve w for (Element of AS);
theorem
(u,u1 // w,w & w,w // u,u1)
proof
set v = the (Element of AS);
consider v1 such that A1: v1 <> v and A2: v,v1 '//' u,u1 by CKB4:def 1;
v,v1 '//' w,w by CKB4:def 1;
hence thesis by A1,A2,CKB12:def 1;
end;
