environ
vocabularies NUMBERS,SUBSET_1,COMSEQ_1,PARTFUN1,REAL_1,ORDINAL2,NAT_1,SEQ_1,FCONT_1,RELAT_1,TARSKI,SEQ_2,FUNCT_2,ARYTM_1,FUNCT_1,ARYTM_3,VALUED_1,COMPLEX1,XBOOLE_0,ORDINAL4,VALUED_0,CARD_1,XXREAL_0,XREAL_0,RCOMP_1,CFCONT_1;
notations TARSKI,XBOOLE_0,SUBSET_1,FUNCT_1,NUMBERS,XREAL_0,COMPLEX1,REAL_1,NAT_1,PARTFUN1,FUNCT_2,SEQ_1,RELSET_1,VALUED_0,VALUED_1,CFUNCT_1,COMSEQ_1,COMSEQ_2,COMSEQ_3,XXREAL_0,RECDEF_1,CKB1,CKB40;
definitions TARSKI,COMSEQ_2,COMSEQ_3,FUNCT_1,VALUED_0,VALUED_1,CKB1,CKB40;
theorems TARSKI,NAT_1,FUNCT_1,COMPLEX1,SEQ_1,SEQM_3,SEQ_4,COMSEQ_1,COMSEQ_2,COMSEQ_3,PARTFUN1,CFUNCT_1,RELAT_1,FUNCT_2,PARTFUN2,XBOOLE_0,XBOOLE_1,XCMPLX_1,XREAL_1,XXREAL_0,ORDINAL1,VALUED_1,VALUED_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49;
schemes NAT_1,RECDEF_1,FUNCT_2,CKB32;
registrations XBOOLE_0,FUNCT_1,ORDINAL1,RELSET_1,FUNCT_2,NUMBERS,XREAL_0,NAT_1,MEMBERED,VALUED_0,VALUED_1;
constructors PARTFUN1,XXREAL_0,REAL_1,NAT_1,SEQ_1,COMSEQ_2,CFUNCT_1,COMSEQ_3,RECDEF_1,SEQM_3,VALUED_1,RELSET_1,CKB1,CKB40;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve X for set;
reserve g for (Element of ( COMPLEX ));
reserve s1 for Complex_Sequence;
reserve f for (PartFunc of ( COMPLEX ),( COMPLEX ));
theorem
Th69: ((f is_continuous_on X & ( f " { ( 0 ) } ) = ( {} )) implies ( f ^ ) is_continuous_on X)
proof
assume that
A1: f is_continuous_on X
and
A2: ( f " { ( 0 ) } ) = ( {} );
A3: ( dom ( f ^ ) ) = ( ( dom f ) \ ( {} ) ) by A2,CFUNCT_1:def 2
.= ( dom f );
hence A4: X c= ( dom ( f ^ ) ) by A1,CKB40:def 1;
let g;
assume A5: g in X;
then A6: ( f | X ) is_continuous_in g by A1,CKB40:def 1;
g in ( ( dom ( f ^ ) ) /\ X ) by A4,A5,XBOOLE_0:def 4;
then A7: g in ( dom ( ( f ^ ) | X ) ) by RELAT_1:61;
now
let s1;
assume that
A8: ( rng s1 ) c= ( dom ( ( f ^ ) | X ) )
and
A9: (s1 is  convergent & ( lim s1 ) = g);
( rng s1 ) c= ( ( dom ( f ^ ) ) /\ X ) by A8,RELAT_1:61;
then A10: ( rng s1 ) c= ( dom ( f | X ) ) by A3,RELAT_1:61;
then A11: ( ( f | X ) /* s1 ) is  convergent by A6,A9,CKB1:def 1;
now
let n;
A12: ( s1 . n ) in ( rng s1 ) by VALUED_0:28;
(( rng s1 ) c= ( ( dom f ) /\ X ) & ( ( dom f ) /\ X ) c= ( dom f )) by A3,A8,RELAT_1:61,XBOOLE_1:17;
then A13: ( rng s1 ) c= ( dom f ) by XBOOLE_1:1;
A14:now
assume ( f /. ( s1 . n ) ) = ( 0c );
then ( f /. ( s1 . n ) ) in { ( 0c ) } by TARSKI:def 1;
hence contradiction by A2,A13,A12,PARTFUN2:26;
end;
( ( ( f | X ) /* s1 ) . n ) = ( ( f | X ) /. ( s1 . n ) ) by A10,FUNCT_2:109
.= ( f /. ( s1 . n ) ) by A10,A12,PARTFUN2:15;
hence ( ( ( f | X ) /* s1 ) . n ) <> ( 0c ) by A14;
end;
then A15: ( ( f | X ) /* s1 ) is  non-zero by COMSEQ_1:4;
g in ( ( dom f ) /\ X ) by A3,A4,A5,XBOOLE_0:def 4;
then A16: g in ( dom ( f | X ) ) by RELAT_1:61;
then A17: ( ( f | X ) /. g ) = ( f /. g ) by PARTFUN2:15;
now
let n;
A18: ( s1 . n ) in ( rng s1 ) by VALUED_0:28;
then ( s1 . n ) in ( dom ( ( f ^ ) | X ) ) by A8;
then ( s1 . n ) in ( ( dom ( f ^ ) ) /\ X ) by RELAT_1:61;
then A19: ( s1 . n ) in ( dom ( f ^ ) ) by XBOOLE_0:def 4;
thus ( ( ( ( f ^ ) | X ) /* s1 ) . n ) = ( ( ( f ^ ) | X ) /. ( s1 . n ) ) by A8,FUNCT_2:109
.= ( ( f ^ ) /. ( s1 . n ) ) by A8,A18,PARTFUN2:15
.= ( ( f /. ( s1 . n ) ) " ) by A19,CFUNCT_1:def 2
.= ( ( ( f | X ) /. ( s1 . n ) ) " ) by A10,A18,PARTFUN2:15
.= ( ( ( ( f | X ) /* s1 ) . n ) " ) by A10,FUNCT_2:109
.= ( ( ( ( f | X ) /* s1 ) " ) . n ) by VALUED_1:10;
end;
then A20: ( ( ( f ^ ) | X ) /* s1 ) = ( ( ( f | X ) /* s1 ) " ) by FUNCT_2:63;
A21:now
assume ( f /. g ) = ( 0c );
then ( f /. g ) in { ( 0c ) } by TARSKI:def 1;
hence contradiction by A2,A3,A4,A5,PARTFUN2:26;
end;
then ( lim ( ( f | X ) /* s1 ) ) <> ( 0c ) by A6,A9,A10,A17,CKB1:def 1;
hence ( ( ( f ^ ) | X ) /* s1 ) is  convergent by A11,A15,A20,COMSEQ_2:34;
( ( f | X ) /. g ) = ( lim ( ( f | X ) /* s1 ) ) by A6,A9,A10,CKB1:def 1;
hence ( lim ( ( ( f ^ ) | X ) /* s1 ) ) = ( ( ( f | X ) /. g ) " ) by A11,A17,A21,A15,A20,COMSEQ_2:35
.= ( ( f /. g ) " ) by A16,PARTFUN2:15
.= ( ( f ^ ) /. g ) by A4,A5,CFUNCT_1:def 2
.= ( ( ( f ^ ) | X ) /. g ) by A7,PARTFUN2:15;
end;
hence thesis by A7,CKB1:def 1;
end;
