environ
vocabularies NUMBERS,GROUP_1,GROUP_2,GRAPH_1,GROUP_6,SUBSET_1,INT_1,GR_CY_1,XXREAL_0,NEWTON,CARD_1,GROUP_4,STRUCT_0,FINSET_1,RELAT_1,ARYTM_3,NAT_1,INT_2,ALGSTR_0,ARYTM_1,FINSEQ_1,FUNCT_1,TARSKI,QC_LANG1,BINOP_2,WELLORD1,FUNCT_2,GROUP_5,PRE_TOPC,XCMPLX_0,ORDINAL1;
notations TARSKI,SUBSET_1,ORDINAL1,XCMPLX_0,RELAT_1,FUNCT_1,FUNCT_2,BINOP_1,NUMBERS,INT_1,INT_2,NAT_1,CARD_1,NAT_D,GROUP_2,DOMAIN_1,STRUCT_0,ALGSTR_0,GROUP_1,GROUP_3,GROUP_4,GROUP_5,GROUP_6,GR_CY_1,FINSEQ_1,XXREAL_0;
definitions FUNCT_1,CARD_1,TARSKI,ALGSTR_0,GR_CY_1;
theorems FUNCT_2,GROUP_1,GROUP_2,GROUP_4,GROUP_5,FUNCT_1,GROUP_6,GR_CY_1,NAT_1,INT_1,INT_2,FINSEQ_1,TARSKI,XBOOLE_0,XCMPLX_1,NEWTON,XREAL_1,ORDINAL1,NAT_D,STRUCT_0,XXREAL_0,RELAT_1,CKB1,CKB2,CKB3,CKB4;
schemes FUNCT_2,FINSEQ_1;
registrations XBOOLE_0,RELSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,FINSEQ_1,STRUCT_0,GROUP_1,GROUP_2,GR_CY_1,ORDINAL1,FINSET_1,MEMBERED;
constructors BINOP_1,DOMAIN_1,XXREAL_0,REAL_1,NAT_1,NAT_D,BINOP_2,GROUP_4,GROUP_5,GROUP_6,GR_CY_1,RELSET_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve i for Integer;
theorem
Th11: (for G being  strict Group holds (for b being (Element of G) holds ((for a being (Element of G) holds (ex i st a = ( b |^ i ))) iff G = ( gr { b } ))))
proof
let G being  strict Group;
let b being (Element of G);
thus ((for a being (Element of G) holds (ex i st a = ( b |^ i ))) implies G = ( gr { b } ))
proof
assume A1: (for a being (Element of G) holds (ex i st a = ( b |^ i )));
(for a being (Element of G) holds a in ( gr { b } ))
proof
let a being (Element of G);
(ex i st a = ( b |^ i )) by A1;
hence thesis by GR_CY_1:5;
end;
hence thesis by GROUP_2:62;
end;

assume A2: G = ( gr { b } );
let a being (Element of G);
a in ( gr { b } ) by A2,STRUCT_0:def 5;
hence thesis by GR_CY_1:5;
end;
