environ
vocabularies NUMBERS,XBOOLE_0,METRIC_1,SUBSET_1,SETFAM_1,RELAT_2,FUNCT_1,REAL_1,CARD_1,ARYTM_3,XXREAL_0,POWER,RELAT_1,SEQ_1,SEQ_2,ORDINAL2,COMPLEX1,ARYTM_1,FINSET_1,STRUCT_0,TARSKI,NAT_1,BHSP_3,REWRITE1,ALI2,PRE_TOPC,PCOMPS_1,RCOMP_1,ZFMISC_1,ORDINAL1,XXREAL_2,XREAL_0,MEASURE5,FINSEQ_1,TBSP_1;
notations TARSKI,XBOOLE_0,SUBSET_1,NUMBERS,XREAL_0,COMPLEX1,REAL_1,RELAT_1,ORDINAL1,FUNCT_1,RELSET_1,FINSEQ_1,DOMAIN_1,SETFAM_1,FUNCT_2,FINSET_1,NAT_1,STRUCT_0,PRE_TOPC,TOPS_2,SEQ_1,SEQ_2,COMPTS_1,METRIC_1,POWER,PCOMPS_1,ALI2,XXREAL_0,CKB4,CKB7,CKB8,CKB9,CKB10,CKB11,CKB18,CKB19,CKB39;
definitions COMPTS_1,TARSKI,ORDINAL1,XBOOLE_0,STRUCT_0,FINSET_1,CKB4,CKB7,CKB8,CKB9,CKB10,CKB18,CKB19,CKB39;
theorems METRIC_1,SUBSET_1,FUNCT_1,PCOMPS_1,PRE_TOPC,MEMBERED,TOPS_2,TARSKI,COMPTS_1,NAT_1,SEQ_2,ZFMISC_1,POWER,SERIES_1,ABSVALUE,FUNCT_2,SETFAM_1,FINSEQ_1,ALI2,RELSET_1,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_1,FINSET_1,XREAL_1,XXREAL_0,ORDINAL1,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB12,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB24,CKB25,CKB26,CKB27,CKB29,CKB30,CKB31,CKB32,CKB35,CKB36,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45;
schemes DOMAIN_1,SUBSET_1,NAT_1,SEQ_1,FINSET_1;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,FINSEQ_1,STRUCT_0,METRIC_1,PCOMPS_1,CKB13,CKB20,CKB21,CKB22,CKB23,CKB28,CKB33,CKB34,CKB37;
constructors SETFAM_1,DOMAIN_1,XXREAL_0,REAL_1,NAT_1,COMPLEX1,FINSEQ_1,SEQ_2,POWER,TOPS_2,COMPTS_1,PCOMPS_1,ALI2,SEQ_1,VALUED_1,RELSET_1,CKB4,CKB7,CKB8,CKB9,CKB10,CKB11,CKB18,CKB19,CKB39;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve T for  Reflexive  symmetric  triangle non empty MetrStruct;
reserve t1 for (Element of T);
reserve n for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
reserve p for (Element of ( NAT ));
reserve k for (Element of ( NAT ));
reserve r for Real;
reserve x for set;
reserve y for set;
theorem
(for S1 being (sequence of T) holds (S1 is  Cauchy implies ( rng S1 ) is  bounded))
proof
let S1 being (sequence of T);
set A = ( rng S1 );
assume S1 is  Cauchy;
then consider p such that A1: (for n holds (for m holds ((p <= n & p <= m) implies ( dist (( S1 . n ),( S1 . m )) ) < 1))) by CKB9:def 1;
defpred X[ set ]
 means
(ex n st (p <= n & $1 = ( S1 . n )));
reconsider B = { t1 where t1 is (Point of T): X[ t1 ] } as (Subset of T) from DOMAIN_1:sch 7;
defpred X[ set ]
 means
(ex n st (n <= p & $1 = ( S1 . n )));
reconsider C = { t1 where t1 is (Point of T): X[ t1 ] } as (Subset of T) from DOMAIN_1:sch 7;
reconsider B,C as (Subset of T);
A2: C is  finite
proof
set K = ( Seg p );
set J = ( { ( 0 ) } \/ K );
now
let x;
thus (x in C implies x in ( S1 .: J ))
proof
assume x in C;
then consider t1 such that A3: x = t1 and A4: (ex n st (n <= p & t1 = ( S1 . n )));
consider n such that A5: n <= p and A6: t1 = ( S1 . n ) by A4;
n in ( NAT );
then A7: n in ( dom S1 ) by FUNCT_2:def 1;
now
per cases  by NAT_1:6;
suppose n = ( 0 );

then n in { ( 0 ) } by TARSKI:def 1;
then n in J by XBOOLE_0:def 3;
hence thesis by A3,A6,A7,FUNCT_1:def 6;
end;
suppose (ex m being Nat st n = ( m + 1 ));

then 1 <= n by NAT_1:11;
then n in { k: (1 <= k & k <= p) } by A5;
then n in K by FINSEQ_1:def 1;
then n in J by XBOOLE_0:def 3;
hence thesis by A3,A6,A7,FUNCT_1:def 6;
end;
end;
hence thesis;
end;

assume x in ( S1 .: J );
then consider y such that A8: y in ( dom S1 ) and A9: y in J and A10: x = ( S1 . y ) by FUNCT_1:def 6;
reconsider y as (Element of ( NAT )) by A8;
now
per cases  by A9,XBOOLE_0:def 3;
suppose A11: y in { ( 0 ) };

( S1 . y ) is (Element of T);
then reconsider x9 = x as (Element of T) by A10;
y = ( 0 ) by A11,TARSKI:def 1;
then (ex n st (n <= p & x9 = ( S1 . n ))) by A10;
hence x in C;
end;
suppose A12: y in K;

( S1 . y ) is (Element of T);
then reconsider x9 = x as (Element of T) by A10;
y in { k: (1 <= k & k <= p) } by A12,FINSEQ_1:def 1;
then (ex k st ((y = k & 1 <= k) & k <= p));
then (ex n st (n <= p & x9 = ( S1 . n ))) by A10;
hence x in C;
end;
end;
hence x in C;
end;
hence thesis by TARSKI:1;
end;
A13: A = ( B \/ C )
proof
thus A c= ( B \/ C )
proof
let x;
assume x in A;
then consider y such that A14: y in ( dom S1 ) and A15: x = ( S1 . y ) by FUNCT_1:def 3;
reconsider y as (Element of ( NAT )) by A14;
( S1 . y ) is (Element of T);
then reconsider x9 = x as (Element of T) by A15;
per cases ;
suppose y <= p;

then (ex n st (n <= p & x9 = ( S1 . n ))) by A15;
then x in C;
hence thesis by XBOOLE_0:def 3;
end;
suppose p <= y;

then (ex n st (p <= n & x9 = ( S1 . n ))) by A15;
then x in B;
hence thesis by XBOOLE_0:def 3;
end;
end;

let x;
assume A16: x in ( B \/ C );
per cases  by A16,XBOOLE_0:def 3;
suppose x in B;

then consider t1 such that A17: x = t1 and A18: (ex n st (p <= n & t1 = ( S1 . n )));
consider n such that p <= n and A19: t1 = ( S1 . n ) by A18;
n in ( NAT );
then n in ( dom S1 ) by FUNCT_2:def 1;
hence thesis by A17,A19,FUNCT_1:def 3;
end;
suppose x in C;

then consider t1 such that A20: x = t1 and A21: (ex n st (n <= p & t1 = ( S1 . n )));
consider n such that n <= p and A22: t1 = ( S1 . n ) by A21;
n in ( NAT );
then n in ( dom S1 ) by FUNCT_2:def 1;
hence thesis by A20,A22,FUNCT_1:def 3;
end;
end;
B is  bounded
proof
set x = ( S1 . p );
(ex r st (ex t1 st ((( 0 ) < r & t1 in B) & (for z being (Point of T) holds (z in B implies ( dist (t1,z) ) <= r)))))
proof
take 1;
take x;
thus ( 0 ) < 1;
thus x in B;
let z being (Point of T);
assume z in B;
then (ex t1 st (z = t1 & (ex n st (p <= n & t1 = ( S1 . n )))));
hence thesis by A1;
end;
hence thesis by CKB24:1;
end;
hence thesis by A2,A13,CKB29:1;
end;
