environ
vocabularies NUMBERS,ZF_LANG,XBOOLE_0,SUBSET_1,FUNCT_1,ARYTM_3,CARD_1,ZF_MODEL,TARSKI,ORDINAL1,BVFUNC_2,XBOOLEAN,ZFMISC_1,CLASSES2,ZF_REFLE,CARD_3,RELAT_1,ORDINAL2,ZF_LANG1,ZFMODEL1,XXREAL_0,REALSET1,ZF_FUND1,FUNCT_2,ORDINAL4,NAT_1,ZF_FUND2;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,NAT_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,ORDINAL1,ZF_LANG,ZF_MODEL,ZFMODEL1,ORDINAL2,CARD_3,ZF_LANG1,CLASSES2,ORDINAL4,ZF_REFLE,ZF_FUND1,XXREAL_0,CKB1,CKB2;
definitions TARSKI,ORDINAL1,XBOOLE_0,CKB1,CKB2;
theorems TARSKI,NAT_1,ENUMSET1,FUNCT_1,FUNCT_2,ORDINAL1,ORDINAL2,CARD_1,CARD_2,ZF_MODEL,ZFMODEL1,ZFMODEL2,ZF_LANG1,CARD_3,ZF_REFLE,ZFREFLE1,CLASSES2,ZFMISC_1,ZF_FUND1,GRFUNC_1,RELAT_1,CLASSES1,RELSET_1,XBOOLE_0,XBOOLE_1,XREAL_1,FUNCT_7,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
schemes ZF_REFLE,NAT_1;
registrations ORDINAL1,RELSET_1,FINSET_1,XREAL_0,CARD_1,CLASSES2,ZF_LANG,ORDINAL4,FUNCT_1,ZF_FUND1,ZF_LANG1;
constructors PARTFUN1,WELLORD2,DOMAIN_1,XXREAL_0,XREAL_0,NAT_1,CLASSES1,ZFMODEL1,ZF_LANG1,ZF_REFLE,ZF_FUND1,ORDINAL4,RELSET_1,ZF_MODEL,CKB1,CKB2;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve H for ZF-formula;
reserve x for Variable;
reserve y for Variable;
theorem
Lm4: (((((not y in ( variables_in H )) & x <> ( x. ( 0 ) )) & y <> ( x. ( 0 ) )) & y <> ( x. 4 )) implies (( x. 4 ) in ( Free H ) iff ( x. ( 0 ) ) in ( Free ( Ex (( x. 3 ),( ( ( x. 3 ) 'in' x ) '&' ( ( H / (( x. ( 0 ) ),y) ) / (( x. 4 ),( x. ( 0 ) )) ) )) ) )))
proof
A1: ( x. ( 0 ) ) <> ( x. 3 ) by ZF_LANG1:76;
assume that
A2: (not y in ( variables_in H ))
and
A3: x <> ( x. ( 0 ) )
and
A4: y <> ( x. ( 0 ) )
and
A5: y <> ( x. 4 );
set G = ( ( H / (( x. ( 0 ) ),y) ) / (( x. 4 ),( x. ( 0 ) )) );
A6: ( Free ( Ex (( x. 3 ),( ( ( x. 3 ) 'in' x ) '&' G )) ) ) = ( ( Free ( ( ( x. 3 ) 'in' x ) '&' G ) ) \ { ( x. 3 ) } ) by ZF_LANG1:66
.= ( ( ( Free ( ( x. 3 ) 'in' x ) ) \/ ( Free G ) ) \ { ( x. 3 ) } ) by ZF_LANG1:61
.= ( ( { ( x. 3 ),x } \/ ( Free G ) ) \ { ( x. 3 ) } ) by ZF_LANG1:59
.= ( ( { ( x. 3 ),x } \ { ( x. 3 ) } ) \/ ( ( Free G ) \ { ( x. 3 ) } ) ) by XBOOLE_1:42;
A7: ( x. ( 0 ) ) <> ( x. 4 ) by ZF_LANG1:76;
A8:now
assume A9: ( x. 4 ) in ( Free H );
A10: ( x. 4 ) in ( Free ( H / (( x. ( 0 ) ),y) ) )
proof
now
per cases ;
suppose A11: ( x. ( 0 ) ) in ( Free H );

(not ( x. 4 ) in { ( x. ( 0 ) ) }) by A7,TARSKI:def 1;
then A12: ( x. 4 ) in ( ( Free H ) \ { ( x. ( 0 ) ) } ) by A9,XBOOLE_0:def 5;
( Free ( H / (( x. ( 0 ) ),y) ) ) = ( ( ( Free H ) \ { ( x. ( 0 ) ) } ) \/ { y } ) by A2,A11,ZFMODEL2:2;
hence thesis by A12,XBOOLE_0:def 3;
end;
suppose (not ( x. ( 0 ) ) in ( Free H ));

hence thesis by A2,A9,ZFMODEL2:2;
end;
end;
hence thesis;
end;
A13: ( x. ( 0 ) ) in { ( x. ( 0 ) ) } by TARSKI:def 1;
(not ( x. ( 0 ) ) in ( variables_in ( H / (( x. ( 0 ) ),y) ) )) by A4,ZF_LANG1:184;
then ( Free G ) = ( ( ( Free ( H / (( x. ( 0 ) ),y) ) ) \ { ( x. 4 ) } ) \/ { ( x. ( 0 ) ) } ) by A10,ZFMODEL2:2;
then A14: ( x. ( 0 ) ) in ( Free G ) by A13,XBOOLE_0:def 3;
(not ( x. ( 0 ) ) in { ( x. 3 ) }) by A1,TARSKI:def 1;
then ( x. ( 0 ) ) in ( ( Free G ) \ { ( x. 3 ) } ) by A14,XBOOLE_0:def 5;
hence ( x. ( 0 ) ) in ( Free ( Ex (( x. 3 ),( ( ( x. 3 ) 'in' x ) '&' G )) ) ) by A6,XBOOLE_0:def 3;
end;
now
assume ( x. ( 0 ) ) in ( Free ( Ex (( x. 3 ),( ( ( x. 3 ) 'in' x ) '&' G )) ) );
then (( x. ( 0 ) ) in ( { ( x. 3 ),x } \ { ( x. 3 ) } ) or ( x. ( 0 ) ) in ( ( Free G ) \ { ( x. 3 ) } )) by A6,XBOOLE_0:def 3;
then A15: (( x. ( 0 ) ) in { ( x. 3 ),x } or ( x. ( 0 ) ) in ( Free G )) by XBOOLE_0:def 5;
A16: (not ( x. ( 0 ) ) in ( variables_in ( H / (( x. ( 0 ) ),y) ) )) by A4,ZF_LANG1:184;
A17:now
assume (not ( x. 4 ) in ( Free ( H / (( x. ( 0 ) ),y) ) ));
then A18: ( x. ( 0 ) ) in ( Free ( H / (( x. ( 0 ) ),y) ) ) by A3,A1,A15,A16,TARSKI:def 2,ZFMODEL2:2;
( Free ( H / (( x. ( 0 ) ),y) ) ) c= ( variables_in ( H / (( x. ( 0 ) ),y) ) ) by ZF_LANG1:151;
hence contradiction by A4,A18,ZF_LANG1:184;
end;
( Free ( H / (( x. ( 0 ) ),y) ) ) c= ( ( ( Free H ) \ { ( x. ( 0 ) ) } ) \/ { y } ) by ZFMODEL2:1;
then (( x. 4 ) in ( ( Free H ) \ { ( x. ( 0 ) ) } ) or ( x. 4 ) in { y }) by A17,XBOOLE_0:def 3;
hence ( x. 4 ) in ( Free H ) by A5,TARSKI:def 1,XBOOLE_0:def 5;
end;
hence thesis by A8;
end;
