environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,VECTSP_1,FINSEQ_1,ARYTM_1,FUNCT_1,FINSEQ_2,ARYTM_3,EUCLID,MATRIX_1,XXREAL_0,INCSP_1,RELAT_1,TREES_1,TARSKI,XREAL_0,ORDINAL1,MATRIXR1,CARD_1,NAT_1,REAL_1,SUPINF_2,QC_LANG1,ZFMISC_1,FVSUM_1,MATRIX_3,FUNCT_2,MATRIX_2,MESFUNC1,GROUP_1,ABIAN,BINOP_1,ALGSTR_0,SETWISEO,CARD_3,RVSUM_1,FUNCT_4,AFINSQ_1,PRALG_1,PARTFUN1,MATRIXR2;
notations TARSKI,XBOOLE_0,SUBSET_1,XXREAL_0,ZFMISC_1,ORDINAL1,NAT_1,NUMBERS,ENUMSET1,SETWOP_2,XCMPLX_0,XREAL_0,REAL_1,FUNCT_1,PARTFUN1,BINOP_1,FUNCT_2,FINSEQ_1,FINSEQ_2,FINSEQ_4,FUNCT_7,STRUCT_0,ALGSTR_0,MATRIX_1,FVSUM_1,FINSEQ_7,SETWISEO,GROUP_1,MATRIX_2,MATRIX_3,MATRIX_6,MATRIXR1,EUCLID,MATRIX_7,MATRIX_4,RVSUM_1,VECTSP_1,MATRPROB,CKB9;
definitions TARSKI,MATRIX_1,STRUCT_0,RLVECT_1,VECTSP_1,MATRIXR1,FINSEQ_1,VALUED_1;
theorems MATRIX_3,VECTSP_1,MATRIX_1,MATRIX_4,GROUP_1,XREAL_0,FUNCT_1,FINSEQ_1,NAT_1,FINSEQ_7,MATRIX_2,FINSEQ_2,TARSKI,FINSOP_1,FVSUM_1,SETWISEO,XBOOLE_0,ENUMSET1,XCMPLX_0,ZFMISC_1,MATRIX_7,MATRIXR1,FINSEQ_3,XXREAL_0,RVSUM_1,ORDINAL1,MATRIX10,MATRIX11,MATRPROB,FINSEQ_4,MATRIX_9,MATRIXC1,PARTFUN1,FUNCT_7,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33;
schemes FINSEQ_4;
registrations FINSEQ_2,NAT_1,RELSET_1,MEMBERED,STRUCT_0,VECTSP_1,NUMBERS,XXREAL_0,MATRIX_2,FINSEQ_1,FVSUM_1,FINSET_1,XBOOLE_0,VALUED_0,CARD_1,FUNCT_7;
constructors XXREAL_0,FVSUM_1,BINOP_2,FINSEQ_7,SETWISEO,FINSOP_1,FINSEQ_4,MATRIX_7,MATRIXR1,MATRIX_6,REAL_1,SEQ_1,RVSUM_1,EUCLID,RELSET_1,CKB9;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
theorem
Th30: (for A,B being (Matrix of n,( REAL )) holds ( ( A * B ) @ ) = ( ( B @ ) * ( A @ ) ))
proof
let A being (Matrix of n,( REAL ));
let B being (Matrix of n,( REAL ));
A1: ( len A ) = n by MATRIX_1:24;
A2: (( width A ) = n & ( len B ) = n) by MATRIX_1:24;
A3: ( len ( A * B ) ) = n by MATRIX_1:24;
A4: ( width B ) = n by MATRIX_1:24;
A5: ( len ( B @ ) ) = n by MATRIX_1:24;
then A6: ( len ( ( B @ ) * ( A @ ) ) ) = ( len ( B @ ) ) by MATRIX_1:24;
A7: ( width ( B @ ) ) = n by MATRIX_1:24
.= ( len ( A @ ) ) by MATRIX_1:24;
A8: ( width ( A * B ) ) = n by MATRIX_1:24;
A9: ( width ( A @ ) ) = n by MATRIX_1:24;
then A10: ( width ( ( B @ ) * ( A @ ) ) ) = ( width ( A @ ) ) by MATRIX_1:24;
A11:now
let i being Nat;
let j being Nat;
A12: ( Indices ( ( A * B ) @ ) ) = [: ( Seg n ),( Seg n ) :] by MATRIX_1:24;
assume A13: [ i,j ] in ( Indices ( ( A * B ) @ ) );
then j in ( Seg ( len ( A * B ) ) ) by A3,A12,ZFMISC_1:87;
then A14: j in ( dom ( A * B ) ) by FINSEQ_1:def 3;
i in ( Seg ( width ( A * B ) ) ) by A8,A13,A12,ZFMISC_1:87;
then A15: [ j,i ] in ( Indices ( A * B ) ) by A14,ZFMISC_1:87;
( Seg ( width ( A @ ) ) ) = ( dom A ) by A1,A9,FINSEQ_1:def 3;
then j in ( dom A ) by A9,A13,A12,ZFMISC_1:87;
then A16: ( Col (( A @ ),j) ) = ( Line (A,j) ) by MATRIX_2:14;
reconsider i0 = i,j0 = j as (Element of ( NAT )) by ORDINAL1:def 12;
A17: ( Seg ( width B ) ) = ( dom ( B @ ) ) by A4,A5,FINSEQ_1:def 3;
A18: ( Indices ( ( B @ ) * ( A @ ) ) ) = [: ( Seg n ),( Seg n ) :] by MATRIX_1:24;
then [ i,j ] in [: ( dom ( B @ ) ),( Seg ( width ( A @ ) ) ) :] by A6,A10,A13,A12,FINSEQ_3:29;
then i in ( Seg ( width B ) ) by A17,ZFMISC_1:87;
then ( Line (( B @ ),i) ) = ( Col (B,i) ) by MATRIX_2:15;
hence ( ( ( B @ ) * ( A @ ) ) * (i,j) ) = ( ( Col (B,i0) ) "*" ( Line (A,j0) ) ) by A7,A13,A12,A18,A16,MATRPROB:39
.= ( ( A * B ) * (j0,i0) ) by A2,A15,MATRPROB:39
.= ( ( ( A * B ) @ ) * (i,j) ) by A15,MATRIX_1:def 6;
end;
A19: (( len ( ( B @ ) * ( A @ ) ) ) = n & ( width ( ( B @ ) * ( A @ ) ) ) = n) by MATRIX_1:24;
(( len ( ( A * B ) @ ) ) = n & ( width ( ( A * B ) @ ) ) = n) by MATRIX_1:24;
hence thesis by A19,A11,MATRIX_1:21;
end;
