environ
vocabularies XBOOLE_0,RELAT_1,SUBSET_1,FDIFF_1,TARSKI,CARD_1,ZFMISC_1,INCSP_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,DOMAIN_1,RELSET_1,NUMBERS,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12;
definitions TARSKI,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12;
theorems ENUMSET1,TARSKI,ZFMISC_1,XBOOLE_0,XBOOLE_1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19;
registrations XBOOLE_0,SUBSET_1,CKB1,CKB2;
constructors RELSET_1,DOMAIN_1,CKB1,CKB2,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12;
requirements SUBSET,BOOLE;
begin
reserve S for IncStruct;
reserve A for (POINT of S);
reserve C for (POINT of S);
reserve L for (LINE of S);
reserve F for (Subset of (the Points of S));
theorem
Th18: ((F on L & A on L) iff ( F \/ { A } ) on L)
proof
thus ((F on L & A on L) implies ( F \/ { A } ) on L)
proof
assume A1: (F on L & A on L);
let C being (POINT of S);
assume C in ( F \/ { A } );
then (C in F or C in { A }) by XBOOLE_0:def 3;
hence thesis by A1,CKB9:def 1,TARSKI:def 1;
end;

assume A2: ( F \/ { A } ) on L;
hence F on L by CKB18:1,XBOOLE_1:7;
{ A } c= ( F \/ { A } ) by XBOOLE_1:7;
then { A,A } c= ( F \/ { A } ) by ENUMSET1:29;
then { A,A } on L by A2,CKB18:1;
hence thesis by CKB13:1;
end;
