environ
vocabularies NUMBERS,SUBSET_1,XBOOLE_0,XXREAL_2,ORDINAL2,XREAL_0,ORDINAL1,XXREAL_0,SEQ_4,MESFUNC5,RELAT_1,FUNCT_1,RINFSUP1,VALUED_0,SEQ_1,ARYTM_3,TARSKI,CARD_1,ARYTM_1,SEQ_2,COMPLEX1,NAT_1,MEASURE6,REAL_1,MESFUNC1,SUPINF_2;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XREAL_0,COMPLEX1,REAL_1,XXREAL_0,RELSET_1,FUNCT_2,NAT_1,XXREAL_2,SUPINF_1,VALUED_0,SUPINF_2,SEQ_1,SEQ_2,SEQ_4,LIMFUNC1,RINFSUP1,MEASURE6,EXTREAL1,MESFUNC1,MESFUNC5;
definitions TARSKI,SUPINF_2,MESFUNC1,RINFSUP1,MEASURE6,VALUED_0,XXREAL_3;
theorems NAT_1,TARSKI,FUNCT_1,FUNCT_2,SUPINF_2,INT_1,EXTREAL2,SEQ_2,SEQ_4,RINFSUP1,XREAL_0,XBOOLE_0,MESFUNC2,XREAL_1,XXREAL_0,ORDINAL1,MESFUNC5,XXREAL_2,VALUED_0,XXREAL_3,CKB1,CKB2;
schemes FUNCT_2,DOMAIN_1;
registrations SUBSET_1,RELSET_1,XREAL_0,MEMBERED,ORDINAL1,INT_1,NUMBERS,XBOOLE_0,VALUED_0,SEQ_2,SEQ_4,XXREAL_3,FUNCT_2;
constructors REAL_1,NAT_1,DOMAIN_1,EXTREAL1,COMPLEX1,MEASURE6,MESFUNC1,PARTFUN3,LIMFUNC1,RINFSUP1,MESFUNC5,SEQ_1,SUPINF_1,SEQ_4,RELSET_1,BINOP_2,RVSUM_1;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve X for non empty (Subset of ( ExtREAL ));
reserve Y for non empty (Subset of ( REAL ));
theorem
Th3: ((X = Y & Y is  bounded_below) implies (X is  bounded_below & ( inf X ) = ( lower_bound Y )))
proof
assume that
A1: X = Y
and
A2: Y is  bounded_below;
A3: (for s being  real number holds (s in Y implies ( inf X ) <= s)) by A1,XXREAL_2:3;
(not ( +infty ) in X) by A1;
then A4: X <> { ( +infty ) } by TARSKI:def 1;
(for r being  ext-real number holds (r in X implies ( lower_bound Y ) <= r)) by A1,A2,SEQ_4:def 2;
then A5: ( lower_bound Y ) is (LowerBound of X) by XXREAL_2:def 2;
hence X is  bounded_below by XXREAL_2:def 9;
then ( inf X ) in ( REAL ) by A4,XXREAL_2:58;
then A6: ( inf X ) <= ( lower_bound Y ) by A3,SEQ_4:43;
( lower_bound Y ) <= ( inf X ) by A5,XXREAL_2:def 4;
hence thesis by A6,XXREAL_0:1;
end;
