environ
vocabularies NUMBERS,SUBSET_1,PRE_TOPC,EUCLID,ARYTM_3,STRUCT_0,REALSET1,ARYTM_1,VALUED_2,TARSKI,SUPINF_2,XBOOLE_0,XREAL_0,ORDINAL1,RELAT_1,CARD_1,MONOID_0,RLVECT_1,CONVEX1,XXREAL_0,REAL_1,RLTOPSP1,MATHMORP,ALGSTR_0;
notations TARSKI,ORDINAL1,XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,DOMAIN_1,STRUCT_0,ALGSTR_0,PRE_TOPC,XREAL_0,REAL_1,RLVECT_1,RLTOPSP1,EUCLID,RUSUB_4,CKB1,CKB2,CKB3,CKB4;
definitions TARSKI,XBOOLE_0,SUBSET_1,ALGSTR_0,RUSUB_4,CKB1,CKB2,CKB3;
theorems XBOOLE_1,XCMPLX_1,TARSKI,SUBSET_1,ZFMISC_1,EUCLID,XBOOLE_0,JORDAN1,XREAL_0,XREAL_1,RLTOPSP1,RLVECT_1,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13;
registrations XBOOLE_0,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,EUCLID,RLTOPSP1,ALGSTR_0,RLVECT_1;
constructors DOMAIN_1,XXREAL_0,REAL_1,JORDAN1,CONVEX1,BINOP_2,RUSUB_4,CKB1,CKB2,CKB3;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
reserve T for non empty  Abelian  add-associative  right_zeroed  right_complementable RLSStruct;
reserve X for (Subset of T);
reserve Y for (Subset of T);
reserve B for (Subset of T);
theorem
Th9: (X c= Y implies (( X (-) B ) c= ( Y (-) B ) & ( X (+) B ) c= ( Y (+) B )))
proof
assume A1: X c= Y;
thus ( X (-) B ) c= ( Y (-) B )
proof
let p being set;
assume p in ( X (-) B );
then consider p1 being (Point of T) such that A2: p = p1 and A3: ( B + p1 ) c= X;
( B + p1 ) c= Y by A1,A3,XBOOLE_1:1;
hence thesis by A2;
end;

let p being set;
assume p in ( X (+) B );
then (ex p1,p2 being (Point of T) st ((p = ( p1 + p2 ) & p1 in X) & p2 in B));
hence thesis by A1;
end;
