environ
vocabularies XBOOLE_0,TARSKI,RELAT_1,FUNCT_1,ZFMISC_1,SUBSET_1,MCART_1,PARTFUN1,FUNCT_2,FUNCT_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELSET_1,FUNCT_1,FUNCT_2,BINOP_1,CKB9;
definitions TARSKI,BINOP_1,CKB9;
theorems TARSKI,ZFMISC_1,FUNCT_1,FUNCT_2,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20;
schemes FUNCT_1,CKB6,CKB7;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1;
constructors BINOP_1,RELSET_1,CKB9;
requirements SUBSET,BOOLE;
begin
reserve x for set;
theorem
(for f,g being Function holds ( .: ( g * f ) ) = ( ( .: g ) * ( .: f ) ))
proof
let f being Function,g being Function;
(for x holds (x in ( dom ( .: ( g * f ) ) ) iff x in ( dom ( ( .: g ) * ( .: f ) ) )))
proof
let x;
thus (x in ( dom ( .: ( g * f ) ) ) implies x in ( dom ( ( .: g ) * ( .: f ) ) ))
proof
assume x in ( dom ( .: ( g * f ) ) );
then A1: x in ( bool ( dom ( g * f ) ) ) by CKB9:def 1;
( dom ( g * f ) ) c= ( dom f ) by RELAT_1:25;
then A2: x c= ( dom f ) by A1,XBOOLE_1:1;
then x in ( bool ( dom f ) );
then A3: x in ( dom ( .: f ) ) by CKB9:def 1;
( f .: x ) c= ( dom g ) by A1,CKB2:1;
then ( f .: x ) in ( bool ( dom g ) );
then ( f .: x ) in ( dom ( .: g ) ) by CKB9:def 1;
then ( ( .: f ) . x ) in ( dom ( .: g ) ) by A2,CKB9:def 1;
hence thesis by A3,FUNCT_1:11;
end;

assume A4: x in ( dom ( ( .: g ) * ( .: f ) ) );
then A5: x in ( dom ( .: f ) ) by FUNCT_1:11;
( ( .: f ) . x ) in ( dom ( .: g ) ) by A4,FUNCT_1:11;
then ( f .: x ) in ( dom ( .: g ) ) by A5,CKB10:1;
then A6: ( f .: x ) in ( bool ( dom g ) ) by CKB9:def 1;
x in ( bool ( dom f ) ) by A5,CKB9:def 1;
then x c= ( dom ( g * f ) ) by A6,CKB3:1;
then x in ( bool ( dom ( g * f ) ) );
hence thesis by CKB9:def 1;
end;
then A7: ( dom ( .: ( g * f ) ) ) = ( dom ( ( .: g ) * ( .: f ) ) ) by TARSKI:1;
(for x holds (x in ( dom ( .: ( g * f ) ) ) implies ( ( .: ( g * f ) ) . x ) = ( ( ( .: g ) * ( .: f ) ) . x )))
proof
let x;
assume A8: x in ( dom ( .: ( g * f ) ) );
then A9: x in ( bool ( dom ( g * f ) ) ) by CKB9:def 1;
then A10: ( f .: x ) c= ( dom g ) by CKB2:1;
( dom ( g * f ) ) c= ( dom f ) by RELAT_1:25;
then A11: x c= ( dom f ) by A9,XBOOLE_1:1;
then x in ( bool ( dom f ) );
then A12: x in ( dom ( .: f ) ) by CKB9:def 1;
thus ( ( .: ( g * f ) ) . x ) = ( ( g * f ) .: x ) by A8,CKB10:1
.= ( g .: ( f .: x ) ) by RELAT_1:126
.= ( ( .: g ) . ( f .: x ) ) by A10,CKB9:def 1
.= ( ( .: g ) . ( ( .: f ) . x ) ) by A11,CKB9:def 1
.= ( ( ( .: g ) * ( .: f ) ) . x ) by A12,FUNCT_1:13;
end;
hence thesis by A7,FUNCT_1:2;
end;
