environ
vocabularies NUMBERS,SUBSET_1,XBOOLE_0,FINSEQ_1,XXREAL_0,RELAT_1,JORDAN3,ARYTM_3,ARYTM_1,CARD_1,PARTFUN1,FUNCT_1,RCOMP_1,EUCLID,PRE_TOPC,MCART_1,PSCOMP_1,RLTOPSP1,TOPREAL1,TARSKI,GOBOARD1,REAL_1,SUPINF_2,ZFMISC_1,ORDINAL4,NAT_1,GOBOARD4,FINSEQ_6,GOBOARD5,STRUCT_0,XREAL_0,ORDINAL1,ORDINAL2,SPPOL_1,SPRECT_1,SPPOL_2,FINSEQ_5,FINSEQ_4,TOPREAL2,SPRECT_2,SEQ_4;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,REAL_1,FUNCT_1,RELSET_1,MEMBERED,PARTFUN1,FINSEQ_1,SEQ_1,STRUCT_0,FINSEQ_4,FINSEQ_5,ZFMISC_1,FINSEQ_6,NAT_1,NAT_D,PRE_TOPC,COMPTS_1,RLVECT_1,RLTOPSP1,EUCLID,TOPREAL1,TOPREAL2,GOBOARD1,GOBOARD4,SEQ_4,SPPOL_1,SPPOL_2,GOBOARD5,JORDAN3,PSCOMP_1,SPRECT_1,XXREAL_0,CKB21,CKB30,CKB31,CKB33;
definitions TARSKI,GOBOARD4,TOPREAL1,XBOOLE_0,PSCOMP_1,STRUCT_0,RLTOPSP1,CKB21,CKB30,CKB31,CKB33;
theorems FINSEQ_6,FINSEQ_4,FINSEQ_5,GOBOARD4,GOBOARD1,PSCOMP_1,FINSEQ_3,JORDAN3,NAT_1,SPPOL_1,FINSEQ_1,JORDAN4,ZFMISC_1,SPPOL_2,TOPREAL3,TARSKI,FUNCT_1,TOPREAL1,GOBOARD2,GOBOARD7,PARTFUN2,GOBOARD5,EUCLID,TOPREAL2,FUNCT_2,PRE_TOPC,RELAT_1,SPRECT_1,TOPREAL5,XBOOLE_0,XBOOLE_1,XCMPLX_1,SEQ_4,XREAL_1,XXREAL_0,PARTFUN1,CARD_1,NAT_D,RLTOPSP1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB77;
registrations RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,FINSEQ_1,STRUCT_0,PRE_TOPC,EUCLID,GOBOARD2,SPPOL_2,PSCOMP_1,SPRECT_1,XBOOLE_0,VALUED_0,FUNCT_1,RLTOPSP1,TOPREAL1,SEQ_4,MEASURE6,ZFMISC_1,CKB35,CKB42,CKB43,CKB76;
constructors PARTFUN1,XXREAL_0,REAL_1,NAT_1,FINSEQ_4,ZFMISC_1,NAT_D,FINSEQ_5,COMPTS_1,TOPREAL2,GOBOARD1,GOBOARD4,SPPOL_1,GOBOARD5,PSCOMP_1,JORDAN3,SPRECT_1,SEQ_1,SEQ_4,RELSET_1,CONVEX1,GOBOARD2,MEASURE6,CKB21,CKB30,CKB31,CKB33;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
reserve f for non  constant  standard special_circular_sequence;
theorem
Lm3: (for i holds (for j holds (((((((i in ( dom f ) & j in ( dom f )) & ( mid (f,i,j) ) is S-Sequence_in_R2) & ( f /. i ) = ( N-min ( L~ f ) )) & ( N-min ( L~ f ) ) <> ( NW-corner ( L~ f ) )) & ( f /. j ) = ( S-max ( L~ f ) )) & ( S-max ( L~ f ) ) <> ( SE-corner ( L~ f ) )) implies ( ( <* ( NW-corner ( L~ f ) ) *> ^ ( mid (f,i,j) ) ) ^ <* ( SE-corner ( L~ f ) ) *> ) is S-Sequence_in_R2)))
proof
set p = ( NW-corner ( L~ f ) );
set q = ( SE-corner ( L~ f ) );
let i;
let j;
assume that
A1: i in ( dom f )
and
A2: j in ( dom f )
and
A3: ( mid (f,i,j) ) is S-Sequence_in_R2
and
A4: ( f /. i ) = ( N-min ( L~ f ) )
and
A5: ( N-min ( L~ f ) ) <> ( NW-corner ( L~ f ) )
and
A6: ( f /. j ) = ( S-max ( L~ f ) )
and
A7: ( S-max ( L~ f ) ) <> ( SE-corner ( L~ f ) );
set g = ( <* ( NW-corner ( L~ f ) ) *> ^ ( mid (f,i,j) ) );
A8: g is S-Sequence_in_R2 by A1,A2,A3,A4,A5,CKB73:1;
(( len g ) = ( ( len <* ( NW-corner ( L~ f ) ) *> ) + ( len ( mid (f,i,j) ) ) ) & ( len ( mid (f,i,j) ) ) in ( dom ( mid (f,i,j) ) )) by A3,FINSEQ_1:22,FINSEQ_5:6;
then A9: ( g /. ( len g ) ) = ( ( mid (f,i,j) ) /. ( len ( mid (f,i,j) ) ) ) by FINSEQ_4:69;
then A10: ( g /. ( len g ) ) = ( S-max ( L~ f ) ) by A1,A2,A6,CKB9:1;
then A11: ( q `2 ) = ( ( g /. ( len g ) ) `2 ) by PSCOMP_1:53;
( ( mid (f,i,j) ) /. 1 ) = ( f /. i ) by A1,A2,CKB8:1;
then A12: ( L~ g ) = ( ( LSeg (p,( N-min ( L~ f ) )) ) \/ ( L~ ( mid (f,i,j) ) ) ) by A3,A4,SPPOL_2:20;
A13: (1 <= j & j <= ( len f )) by A2,FINSEQ_3:25;
A14: (1 <= i & i <= ( len f )) by A1,FINSEQ_3:25;
( len ( mid (f,i,j) ) ) >= 2 by A3,TOPREAL1:def 8;
then A15: (( ( LSeg (( SE-corner ( L~ f ) ),( S-max ( L~ f ) )) ) /\ ( L~ f ) ) = { ( S-max ( L~ f ) ) } & ( S-max ( L~ f ) ) in ( L~ ( mid (f,i,j) ) )) by A9,A10,JORDAN3:1,PSCOMP_1:59;
( LSeg (( g /. ( len g ) ),q) ) misses ( LSeg (p,( N-min ( L~ f ) )) ) by A10,CKB77:1;
then ( ( LSeg (q,( g /. ( len g ) )) ) /\ ( LSeg (p,( N-min ( L~ f ) )) ) ) = ( {} ) by XBOOLE_0:def 7;
then ( ( LSeg (q,( g /. ( len g ) )) ) /\ ( L~ g ) ) = ( ( ( LSeg (q,( g /. ( len g ) )) ) /\ ( L~ ( mid (f,i,j) ) ) ) \/ ( {} ) ) by A12,XBOOLE_1:23
.= { ( g /. ( len g ) ) } by A10,A15,A14,A13,JORDAN4:35,ZFMISC_1:124;
hence thesis by A7,A8,A10,A11,CKB68:1;
end;
