environ
vocabularies NUMBERS,SUBSET_1,REAL_1,INTEGRA1,XBOOLE_0,MEASURE7,CARD_1,FINSEQ_1,RELAT_1,XXREAL_0,FUNCT_1,SEQ_4,ARYTM_3,ARYTM_1,FUNCT_3,TARSKI,PARTFUN1,CARD_3,VALUED_1,XXREAL_2,XXREAL_1,INTEGRA2,SEQ_2,ORDINAL2,FINSET_1,NAT_1,FINSEQ_2,VALUED_0,FDIFF_1,XREAL_0,ORDINAL1,COMPLEX1,INT_1,ZFMISC_1,RFUNCT_3,SEQ_1,ORDINAL4,SQUARE_1,INTEGRA4,MEASURE5;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,INT_1,XXREAL_2,VALUED_0,ZFMISC_1,FUNCT_1,RELSET_1,FINSET_1,FUNCT_2,FINSEQ_1,VALUED_1,SEQ_1,RFUNCT_1,FINSEQ_2,SEQ_2,SEQ_4,RCOMP_1,FDIFF_1,SQUARE_1,RVSUM_1,MEASURE5,INTEGRA1,INTEGRA2,INTEGRA3,RFUNCT_3,PARTFUN1,XXREAL_0,CKB13;
definitions TARSKI,SQUARE_1,RVSUM_1,FINSEQ_2,VALUED_1,XXREAL_2,CKB13;
theorems SEQ_4,SUBSET_1,PARTFUN1,INTEGRA1,RFUNCT_1,FUNCT_1,FINSEQ_1,RVSUM_1,SEQ_1,SEQ_2,FDIFF_1,ABSVALUE,NAT_1,TARSKI,FINSEQ_3,INTEGRA2,INTEGRA3,SEQM_3,PARTFUN2,NAT_2,INT_1,FINSEQ_2,RFUNCT_3,RELAT_1,XREAL_0,FUNCT_2,XBOOLE_0,XBOOLE_1,XCMPLX_0,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,FINSOP_1,FUNCOP_1,VALUED_1,XXREAL_2,VALUED_0,ORDINAL1,RELSET_1,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13;
schemes FINSEQ_2,FUNCT_2;
registrations XBOOLE_0,RELAT_1,ORDINAL1,FUNCT_2,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,MEMBERED,FINSEQ_1,FINSEQ_2,INTEGRA1,VALUED_0,VALUED_1,XXREAL_2,CARD_1,SEQ_2,SEQ_4,RELSET_1,SEQM_3,MEASURE5;
constructors REAL_1,SQUARE_1,NAT_1,BINOP_2,COMPLEX1,FINSEQOP,FINSOP_1,PARTFUN2,FDIFF_1,ZFMISC_1,RFUNCT_3,INTEGRA2,SEQ_1,XXREAL_2,RVSUM_1,SEQ_4,RELSET_1,SEQ_2,INTEGRA3,CKB13;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
reserve n for (Element of ( NAT ));
reserve A for non  empty  closed_interval (Subset of ( REAL ));
theorem
Lm3: (for n holds ((n > ( 0 ) & ( vol A ) > ( 0 )) implies (ex D being (Division of A) st (( len D ) = n & (for i holds (i in ( dom D ) implies ( D . i ) = ( ( lower_bound A ) + ( ( ( vol A ) / n ) * i ) )))))))
proof
let n;
assume that
A1: n > ( 0 )
and
A2: ( vol A ) > ( 0 );
deffunc F(Nat) = ( ( lower_bound A ) + ( ( ( vol A ) / n ) * $1 ) );
consider D being (FinSequence of ( REAL )) such that A3: (( len D ) = n & (for i being Nat holds (i in ( dom D ) implies ( D . i ) = F(i)))) from FINSEQ_2:sch 1;
A4: (for i holds (for j holds (((i in ( dom D ) & j in ( dom D )) & i < j) implies ( D . i ) < ( D . j ))))
proof
let i;
let j;
assume that
A5: i in ( dom D )
and
A6: j in ( dom D )
and
A7: i < j;
( ( vol A ) / n ) > ( 0 ) by A1,A2,XREAL_1:139;
then ( ( ( vol A ) / n ) * i ) < ( ( ( vol A ) / n ) * j ) by A7,XREAL_1:68;
then ( ( lower_bound A ) + ( ( ( vol A ) / n ) * i ) ) < ( ( lower_bound A ) + ( ( ( vol A ) / n ) * j ) ) by XREAL_1:6;
then ( D . i ) < ( ( lower_bound A ) + ( ( ( vol A ) / n ) * j ) ) by A3,A5;
hence thesis by A3,A6;
end;
A8: ( dom D ) = ( Seg n ) by A3,FINSEQ_1:def 3;
reconsider D as non  empty  increasing (FinSequence of ( REAL )) by A1,A3,A4,SEQM_3:def 1;
( D . ( len D ) ) = ( ( lower_bound A ) + ( ( ( vol A ) / n ) * n ) ) by A3,A8,FINSEQ_1:3;
then A9: ( D . ( len D ) ) = ( ( lower_bound A ) + ( vol A ) ) by A1,XCMPLX_1:87;
(for x1 being set holds (x1 in ( rng D ) implies x1 in A))
proof
let x1 being set;
A10: ( ( lower_bound A ) + ( vol A ) ) = ( ( lower_bound A ) + ( ( upper_bound A ) - ( lower_bound A ) ) ) by INTEGRA1:def 5
.= ( upper_bound A );
assume A11: x1 in ( rng D );
then reconsider x1 as Real;
consider i such that A12: i in ( dom D ) and A13: ( D . i ) = x1 by A11,PARTFUN1:3;
A14: 1 <= i by A12,FINSEQ_3:25;
i <= ( len D ) by A12,FINSEQ_3:25;
then ( ( ( vol A ) / n ) * i ) <= ( ( ( vol A ) / n ) * n ) by A2,A3,XREAL_1:64;
then ( ( ( vol A ) / n ) * i ) <= ( vol A ) by A1,XCMPLX_1:87;
then A15: ( ( lower_bound A ) + ( ( ( vol A ) / n ) * i ) ) <= ( ( lower_bound A ) + ( vol A ) ) by XREAL_1:6;
( ( vol A ) / n ) > ( 0 ) by A1,A2,XREAL_1:139;
then A16: ( lower_bound A ) <= ( ( lower_bound A ) + ( ( ( vol A ) / n ) * i ) ) by A14,XREAL_1:29,XREAL_1:129;
x1 = ( ( lower_bound A ) + ( ( ( vol A ) / n ) * i ) ) by A3,A12,A13;
hence thesis by A16,A15,A10,INTEGRA2:1;
end;
then A17: ( rng D ) c= A by TARSKI:def 3;
( vol A ) = ( ( upper_bound A ) - ( lower_bound A ) ) by INTEGRA1:def 5;
then reconsider D as (Division of A) by A17,A9,INTEGRA1:def 2;
take D;
thus thesis by A3;
end;
