environ
vocabularies LATTICES,SUBSET_1,XBOOLE_0,EQREL_1,PBOOLE;
notations STRUCT_0,LATTICES,CKB1,CKB2,CKB3,CKB4,CKB5,CKB14,CKB15,CKB16;
definitions CKB1,CKB2,CKB3,CKB4;
theorems LATTICES,FILTER_0,LATTICE4,CKB1,CKB2,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
registrations LATTICES;
constructors LATTICES,CKB1,CKB2,CKB3,CKB4,CKB14,CKB15,CKB16;
begin
reserve L for 0_Lattice;
reserve X for (Element of L);
reserve Y for (Element of L);
reserve Z for (Element of L);
theorem
(X meets ( Y \ Z ) implies X meets Y)
proof
assume X meets ( Y \ Z );
then ( X "/\" ( Y \ Z ) ) <> ( Bottom L ) by CKB4:def 1;
then ( ( X "/\" Y ) "/\" ( Z ` ) ) <> ( Bottom L ) by LATTICES:def 7;
then ( X "/\" Y ) <> ( Bottom L ) by LATTICES:15;
hence thesis by CKB4:def 1;
end;
