environ
vocabularies NUMBERS,SUBSET_1,XBOOLE_0,XXREAL_0,NAT_1,ORDINAL1,CARD_1,TARSKI,ARYTM_3,ARYTM_1,FUNCT_1,RELAT_1,FUNCT_2,INT_1,FINSET_1,AFINSQ_1,BINOP_1,FINSEQ_1,FINSOP_1,CARD_3,BINOP_2,ZFMISC_1,NEWTON,REALSET1,STIRL2_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,RELAT_1,FUNCT_1,RELSET_1,ORDINAL1,SEQ_4,PARTFUN1,FINSET_1,AFINSQ_1,AFINSQ_2,XXREAL_0,FUNCT_2,NAT_1,INT_1,BINOP_1,BINOP_2,NEWTON,DOMAIN_1,CKB16,CKB17,CKB19,CKB32;
definitions TARSKI,XBOOLE_0,FUNCT_1,CKB19,CKB32;
theorems AFINSQ_1,TARSKI,FUNCT_1,XBOOLE_0,ZFMISC_1,RELAT_1,XBOOLE_1,NAT_1,FUNCT_2,AXIOMS,XCMPLX_1,CARD_2,INT_1,ORDINAL1,WELLORD2,FRAENKEL,SUBSET_1,ENUMSET1,CARD_1,BINOP_2,NEWTON,WSIERP_1,XREAL_1,XXREAL_0,XXREAL_2,AFINSQ_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50;
schemes FUNCT_2,NAT_1,INT_1,CKB29,CKB41,CKB42,CKB43;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,BINOP_2,MEMBERED,AFINSQ_1,CARD_1,VALUED_0,XXREAL_2,RELSET_1,AFINSQ_2,CKB9,CKB18;
constructors WELLORD2,DOMAIN_1,SETWISEO,REAL_1,BINOP_2,SEQ_4,NEWTON,AFINSQ_1,AFINSQ_2,RELSET_1,PARTFUN3,SEQ_1,BINOP_1,CKB16,CKB17,CKB19,CKB32;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve k for Nat;
reserve n for Nat;
reserve i for Nat;
reserve j for Nat;
reserve f for (Function of n,k);
reserve x for set;
reserve y for set;
theorem
Th41: (for f being (Function of n,k) holds (for g being (Function of ( n + 1 ),k) holds (((f is  onto  "increasing & f = ( g | n )) & ( g . n ) < k) implies (g is  onto  "increasing & ( g " { ( g . n ) } ) <> { n }))))
proof
let f being (Function of n,k);
let g being (Function of ( n + 1 ),k);
assume that
A1: f is  onto  "increasing
and
A2: f = ( g | n )
and
A3: ( g . n ) < k;
k = ( rng f ) by A1,FUNCT_2:def 3;
then consider x such that A4: x in ( dom f ) and A5: ( f . x ) = ( g . n ) by A3,FUNCT_1:def 3;
( g . n ) = ( g . x ) by A2,A4,A5,FUNCT_1:47;
then A6: ( g . x ) in { ( g . n ) } by TARSKI:def 1;
k c= ( rng g )
proof
n <= ( n + 1 ) by NAT_1:13;
then A7: n c= ( n + 1 ) by NAT_1:39;
(n = ( 0 ) iff k = ( 0 )) by A1,CKB19:def 1;
then A8: ( dom f ) = n by FUNCT_2:def 1;
let x9 being set;
assume that
A9: x9 in k;
k is (Subset of ( NAT )) by CKB8:1;
then reconsider x = x9 as (Element of ( NAT )) by A9;
( rng f ) = k by A1,FUNCT_2:def 3;
then consider y being set such that A10: y in ( dom f ) and A11: ( f . y ) = x by A9,FUNCT_1:def 3;
A12: ( dom g ) = ( n + 1 ) by A3,FUNCT_2:def 1;
( f . y ) = ( g . y ) by A2,A10,FUNCT_1:47;
hence thesis by A10,A11,A8,A7,A12,FUNCT_1:def 3;
end;
then k = ( rng g ) by XBOOLE_0:def 10;
hence g is  onto by FUNCT_2:def 3;
k = ( k + ( 0 ) );
then (for i holds (for j holds (((i in ( rng g ) & j in ( rng g )) & i < j) implies ( min* ( g " { i } ) ) < ( min* ( g " { j } ) )))) by A1,A2,CKB49:1;
hence g is  "increasing by A3,CKB19:def 1;
n <= ( n + 1 ) by NAT_1:11;
then A13: n c= ( n + 1 ) by NAT_1:39;
A14: x in n by A4;
then A15: x <> n;
( dom g ) = ( n + 1 ) by A3,FUNCT_2:def 1;
then x in ( g " { ( g . n ) } ) by A14,A13,A6,FUNCT_1:def 7;
hence thesis by A15,TARSKI:def 1;
end;
