environ
vocabularies NUMBERS,SUBSET_1,XBOOLE_0,XXREAL_0,NAT_1,ORDINAL1,CARD_1,TARSKI,ARYTM_3,ARYTM_1,FUNCT_1,RELAT_1,FUNCT_2,INT_1,FINSET_1,AFINSQ_1,BINOP_1,FINSEQ_1,FINSOP_1,CARD_3,BINOP_2,ZFMISC_1,NEWTON,REALSET1,STIRL2_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,RELAT_1,FUNCT_1,RELSET_1,ORDINAL1,SEQ_4,PARTFUN1,FINSET_1,AFINSQ_1,AFINSQ_2,XXREAL_0,FUNCT_2,NAT_1,INT_1,BINOP_1,BINOP_2,NEWTON,DOMAIN_1,CKB16,CKB17,CKB19,CKB32;
definitions TARSKI,XBOOLE_0,FUNCT_1,CKB19,CKB32;
theorems AFINSQ_1,TARSKI,FUNCT_1,XBOOLE_0,ZFMISC_1,RELAT_1,XBOOLE_1,NAT_1,FUNCT_2,AXIOMS,XCMPLX_1,CARD_2,INT_1,ORDINAL1,WELLORD2,FRAENKEL,SUBSET_1,ENUMSET1,CARD_1,BINOP_2,NEWTON,WSIERP_1,XREAL_1,XXREAL_0,XXREAL_2,AFINSQ_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76;
schemes FUNCT_2,NAT_1,INT_1,CKB29,CKB41,CKB42,CKB43,CKB56,CKB57,CKB70;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,BINOP_2,MEMBERED,AFINSQ_1,CARD_1,VALUED_0,XXREAL_2,RELSET_1,AFINSQ_2,CKB9,CKB18;
constructors WELLORD2,DOMAIN_1,SETWISEO,REAL_1,BINOP_2,SEQ_4,NEWTON,AFINSQ_1,AFINSQ_2,RELSET_1,PARTFUN3,SEQ_1,BINOP_1,CKB16,CKB17,CKB19,CKB32;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve k for Nat;
reserve n for Nat;
reserve N for non  empty (Subset of ( NAT ));
reserve x for set;
reserve y for set;
theorem
Lm5: (for n being (Element of ( NAT )) holds (for N being  finite (Subset of ( NAT )) holds (for F being (Function of N,( card N )) holds (((n in N & F is  bijective) & (for n holds (for k holds (((n in ( dom F ) & k in ( dom F )) & n < k) implies ( F . n ) < ( F . k ))))) implies (ex P being (Permutation of N) st (for k holds (k in N implies (((k < n implies ( P . k ) = ( ( F " ) . ( ( F . k ) + 1 ) )) & (k = n implies ( P . k ) = ( ( F " ) . ( 0 ) ))) & (k > n implies ( P . k ) = k)))))))))
proof
let n being (Element of ( NAT ));
let N being  finite (Subset of ( NAT ));
let F being (Function of N,( card N ));
assume that
A1: n in N
and
A2: F is  bijective
and
A3: (for n holds (for k holds (((n in ( dom F ) & k in ( dom F )) & n < k) implies ( F . n ) < ( F . k ))));
( rng F ) = ( card N ) by A2,FUNCT_2:def 3;
then reconsider F9 = ( F " ) as (Function of ( card N ),N) by A2,FUNCT_2:25;
defpred P[ set,set ]
 means
(for k holds (k = $1 implies (((k < n implies $2 = ( ( F " ) . ( ( F . k ) + 1 ) )) & (k = n implies $2 = ( ( F " ) . ( 0 ) ))) & (k > n implies $2 = k))));
A4: ( dom F ) = N by A1,FUNCT_2:def 1;
A5: ( dom F9 ) = ( card N ) by A1,FUNCT_2:def 1;
A6: (for x holds (x in N implies (ex y st (y in N & P[ x,y ]))))
proof
let x9 being set;
assume that
A7: x9 in N;
reconsider x = x9 as (Element of ( NAT )) by A7;
now
per cases  by XXREAL_0:1;
suppose A8: x < n;

then ( F . x ) < ( F . n ) by A1,A3,A4,A7;
then A9: ( ( F . x ) + 1 ) <= ( F . n ) by NAT_1:13;
( F . n ) < ( card N ) by A1,NAT_1:44;
then ( ( F . x ) + 1 ) < ( card N ) by A9,XXREAL_0:2;
then ( ( F . x ) + 1 ) in ( dom F9 ) by A5,NAT_1:44;
then A10: ( F9 . ( ( F . x ) + 1 ) ) in ( rng F9 ) by FUNCT_1:def 3;
set FF = ( ( F " ) . ( ( F . x ) + 1 ) );
P[ x9,FF ] by A8;
hence thesis by A10;
end;
suppose A11: x = n;

( 0 ) in ( dom F9 ) by A1,A5,NAT_1:44;
then A12: ( F9 . ( 0 ) ) in ( rng F9 ) by FUNCT_1:def 3;
P[ x9,( ( F " ) . ( 0 ) ) ] by A11;
hence thesis by A12;
end;
suppose x > n;

then P[ x,x ];
hence thesis by A7;
end;
end;
hence thesis;
end;
consider P being (Function of N,N) such that A13: (for x holds (x in N implies P[ x,( P . x ) ])) from FUNCT_2:sch 1(A6);
N c= ( rng P )
proof
let Px9 being set;
assume that
A14: Px9 in N;
reconsider Px = Px9 as (Element of ( NAT )) by A14;
now
per cases ;
suppose A15: Px <= n;

( rng F9 ) = N by A2,A4,FUNCT_1:33;
then consider x such that A16: x in ( dom F9 ) and A17: ( F9 . x ) = Px by A14,FUNCT_1:def 3;
( card N ) is (Subset of ( NAT )) by CKB8:1;
then reconsider x as (Element of ( NAT )) by A5,A16;
now
per cases ;
suppose A18: x = ( 0 );

A19: ( dom P ) = N by A1,FUNCT_2:def 1;
( P . n ) = ( ( F " ) . ( 0 ) ) by A1,A13;
hence thesis by A1,A17,A18,A19,FUNCT_1:def 3;
end;
suppose x > ( 0 );

then reconsider x1 = ( x - 1 ) as (Element of ( NAT )) by NAT_1:20;
A20: x1 < ( x1 + 1 ) by NAT_1:13;
x < ( card N ) by A16,NAT_1:44;
then x1 < ( card N ) by A20,XXREAL_0:2;
then A21: x1 in ( card N ) by NAT_1:44;
( card N ) = ( rng F ) by A2,FUNCT_2:def 3;
then consider y such that A22: y in ( dom F ) and A23: ( F . y ) = x1 by A21,FUNCT_1:def 3;
reconsider y as (Element of ( NAT )) by A4,A22;
A24: y in ( dom P ) by A4,A22,FUNCT_2:def 1;
A25: y < n
proof
assume y >= n;
then (y > n or y = n) by XXREAL_0:1;
then A26: x1 >= ( F . n ) by A1,A3,A4,A22,A23;
x in ( rng F ) by A2,A16,FUNCT_1:33;
then A27: ( F . Px ) = x by A2,A17,FUNCT_1:32;
(Px < n or Px = n) by A15,XXREAL_0:1;
then A28: ( F . Px ) <= ( F . n ) by A1,A3,A4,A14;
( x1 + 1 ) > x1 by NAT_1:13;
hence contradiction by A26,A27,A28,XXREAL_0:2;
end;
( ( F " ) . ( ( F . y ) + 1 ) ) = Px by A17,A23;
then ( P . y ) = Px by A13,A22,A25;
hence thesis by A24,FUNCT_1:def 3;
end;
end;
hence thesis;
end;
suppose A29: Px > n;

A30: Px in ( dom P ) by A14,FUNCT_2:def 1;
Px = ( P . Px ) by A13,A14,A29;
hence thesis by A30,FUNCT_1:def 3;
end;
end;
hence thesis;
end;
then N = ( rng P ) by XBOOLE_0:def 10;
then A31: P is  onto by FUNCT_2:def 3;
( card N ) = ( card N );
then P is  onto  one-to-one by A31,CKB76:1;
then reconsider P as (Permutation of N);
take P;
thus thesis by A13;
end;
