environ
vocabularies FUNCT_1,COMPLEX1,XBOOLE_0,XXREAL_0,VALUED_1,NAT_1,PARTFUN1,SEQ_1,ARYTM_1,ORDINAL2,ZFMISC_1,NUMBERS,CARD_1,RELAT_1,SEQFUNC,ARYTM_3,PBOOLE,RLVECT_1,SUPINF_2,RSSPACE,STRUCT_0,ALGSTR_0,VECTSP10,REALSET1,FUNCOP_1,PRE_TOPC,LPSPACE1,BINOP_1,NORMSP_1,PROB_1,MEASURE1,MEASURE2,MEASURE6,MESFUNC1,TARSKI,RFUNCT_3,SETFAM_1,MESFUNC5,MESFUNC8,IDEAL_1,SUBSET_1,FUNCT_7,PREPOWER,POWER,LPSPACE2,RSSPACE3,SEQ_2,SERIES_1,REAL_1,INTEGRA5,ORDINAL1,XREAL_0,VALUED_0,CARD_3,REWRITE1,NEWTON,XXREAL_2,METRIC_1,RELAT_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,COMPLEX1,XXREAL_0,XREAL_0,SUPINF_2,EXTREAL1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,VALUED_1,RFUNCT_3,BINOP_1,REAL_1,NAT_1,STRUCT_0,ALGSTR_0,RLVECT_1,IDEAL_1,SETFAM_1,PRE_TOPC,NORMSP_0,NORMSP_1,PROB_1,ASYMPT_0,MEASURE1,MEASURE2,MEASURE3,MEASURE6,SEQFUNC,MESFUNC1,MESFUNC2,MESFUNC5,MESFUNC6,FUNCT_7,MESFUNC8,NEWTON,PREPOWER,POWER,MESFUN6C,SEQ_1,SEQ_2,RECDEF_1,SERIES_1,RSSPACE3,LOPBAN_1,MESFUN7C,MESFUN9C,LPSPACE1,CKB3,CKB21,CKB39,CKB43,CKB47,CKB51,CKB65,CKB66,CKB67,CKB68,CKB69,CKB77,CKB78;
definitions TARSKI,STRUCT_0,ALGSTR_0,RLVECT_1,NORMSP_1,MEASURE6,MESFUN7C,MESFUNC5,MESFUNC6,SUBSET_1,LPSPACE1,XBOOLE_0,VALUED_1,RELAT_1,XCMPLX_0,NORMSP_0,CKB3,CKB21,CKB39,CKB43,CKB47,CKB51,CKB65,CKB66,CKB67,CKB68,CKB69,CKB77,CKB78;
theorems FUNCT_1,FUNCT_2,PARTFUN1,COMPLEX1,MESFUN9C,RINFSUP2,SEQ_2,SETFAM_1,LOPBAN_1,PREPOWER,XBOOLE_0,TARSKI,RELAT_1,SEQM_3,VALUED_1,SERIES_1,IDEAL_1,RLVECT_1,FUNCOP_1,XBOOLE_1,BINOP_1,SUPINF_2,MESFUNC5,MESFUNC2,EXTREAL1,MEASURE1,MESFUNC6,RFUNCT_1,XXREAL_0,ABSVALUE,MESFUNC1,MEASURE2,EXTREAL2,RSSPACE3,NORMSP_1,FUNCT_7,XREAL_1,HOLDER_1,POWER,XREAL_0,SUBSET_1,LPSPACE1,MESFUN6C,MESFUN7C,MESFUNC8,ORDINAL1,NAT_1,XCMPLX_0,XCMPLX_1,VALUED_0,XXREAL_3,SEQFUNC,MESFUNC9,SEQ_4,RELSET_1,COMSEQ_3,SEQ_1,SERIES_3,LOPBAN_3,NAGATA_2,NORMSP_0,CKB1,CKB2,CKB3,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB37,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB46,CKB47,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88;
schemes NAT_1,RECDEF_1,BINOP_1,FUNCT_2,SEQ_1,SEQFUNC;
registrations ORDINAL1,RELSET_1,NUMBERS,MEMBERED,VALUED_0,NAT_1,SUBSET_1,PARTFUN1,RLVECT_1,STRUCT_0,NORMSP_1,MEASURE1,SEQ_4,SEQ_2,MESFUN6C,MESFUNC8,LPSPACE1,XCMPLX_0,XREAL_0,XXREAL_0,VALUED_1,FUNCT_2,MESFUN7C,NORMSP_0,CKB4,CKB5,CKB18,CKB36,CKB38,CKB45,CKB48,CKB70,CKB71;
constructors EXTREAL1,REAL_1,IDEAL_1,NEWTON,MEASURE3,MEASURE6,MESFUNC2,MESFUNC6,MESFUNC9,SEQ_1,MESFUN6C,MESFUN7C,MESFUN9C,RECDEF_1,SEQ_2,EXTREAL2,RINFSUP2,FUNCT_7,SERIES_1,PREPOWER,ASYMPT_0,LPSPACE1,SUPINF_1,SEQFUNC,MESFUNC5,RSSPACE3,LOPBAN_1,MESFUNC1,RELSET_1,BINOP_2,CKB3,CKB21,CKB39,CKB43,CKB47,CKB51,CKB65,CKB66,CKB67,CKB68,CKB69,CKB77,CKB78;
requirements NUMERALS,BOOLE,SUBSET,REAL,ARITHM;
begin
reserve X for non  empty set;
reserve S for (SigmaField of X);
reserve M for (sigma_Measure of S);
reserve f for (PartFunc of X,( REAL ));
reserve g for (PartFunc of X,( REAL ));
reserve a for Real;
reserve k for  positive Real;
reserve y for (Point of ( Lp-Space (M,k) ));
theorem
Lm6: (for k being  geq_than_1 Real holds ( Lp-Space (M,k) ) is  reflexive  discerning  RealNormSpace-like  vector-distributive  scalar-distributive  scalar-associative  scalar-unital  Abelian  add-associative  right_zeroed  right_complementable)
proof
let k being  geq_than_1 Real;
set x = ( 0. ( Lp-Space (M,k) ) );
x = ( 0. ( Pre-Lp-Space (M,k) ) );
then x = ( zeroCoset (M,k) ) by CKB69:def 1;
then ( X --> ( 0 ) ) in x by CKB55:1,CKB29:1;
then (ex r being Real st ((( 0 ) <= r & r = ( Integral (M,( ( abs ( X --> ( 0 ) ) ) to_power k )) )) & ||. x .|| = ( r to_power ( 1 / k ) ))) by CKB81:1;
then consider r0 being Real such that A1: (r0 = ( Integral (M,( ( abs ( X --> ( 0 ) ) ) to_power k )) ) & ( ( Lp-Norm (M,k) ) . x ) = ( r0 to_power ( 1 / k ) ));
r0 = ( 0 ) by A1,CKB84:1;
hence ||. x .|| = ( 0 ) by A1,POWER:def 2;
now
let x being (Point of ( Lp-Space (M,k) ));
let y being (Point of ( Lp-Space (M,k) ));
let a being Real;
A2: 1 <= k by CKB3:def 1;
hereby
assume A3: ||. x .|| = ( 0 );
consider f being (PartFunc of X,( REAL )) such that A4: (f in x & (ex r being Real st (r = ( Integral (M,( ( abs f ) to_power k )) ) & ||. x .|| = ( r to_power ( 1 / k ) )))) by CKB77:def 1;
A5: f in ( Lp_Functions (M,k) ) by CKB75:1,A4;
then consider r1 being Real such that A6: ((r1 = ( Integral (M,( ( abs f ) to_power k )) ) & r1 >= ( 0 )) & ( ( Lp-Norm (M,k) ) . x ) = ( r1 to_power ( 1 / k ) )) by A4,CKB73:1;
r1 = ( 0 ) by A3,A6,POWER:34;
then ( zeroCoset (M,k) ) = ( a.e-eq-class_Lp (f,M,k) ) by A5,A6,CKB83:1,CKB59:1;
then ( 0. ( Pre-Lp-Space (M,k) ) ) = ( a.e-eq-class_Lp (f,M,k) ) by CKB69:def 1;
hence x = ( 0. ( Lp-Space (M,k) ) ) by A4,CKB81:1;
end;
consider f being (PartFunc of X,( REAL )) such that A7: (f in x & (ex r1 being Real st (r1 = ( Integral (M,( ( abs f ) to_power k )) ) & ||. x .|| = ( r1 to_power ( 1 / k ) )))) by CKB77:def 1;
A8: (( ( abs f ) to_power k ) is_integrable_on M & f in ( Lp_Functions (M,k) )) by CKB75:1,A7;
consider g being (PartFunc of X,( REAL )) such that A9: (g in y & (ex r2 being Real st (r2 = ( Integral (M,( ( abs g ) to_power k )) ) & ||. y .|| = ( r2 to_power ( 1 / k ) )))) by CKB77:def 1;
A10: (( ( abs g ) to_power k ) is_integrable_on M & g in ( Lp_Functions (M,k) )) by CKB75:1,A9;
consider s1 being Real such that A11: (s1 = ( Integral (M,( ( abs f ) to_power k )) ) & ||. x .|| = ( s1 to_power ( 1 / k ) )) by A7;
A12: (s1 = ( 0 ) implies ( s1 to_power ( 1 / k ) ) >= ( 0 )) by POWER:def 2;
(s1 > ( 0 ) implies ( s1 to_power ( 1 / k ) ) >= ( 0 )) by POWER:34;
hence ( 0 ) <= ||. x .|| by A12,A8,A11,CKB73:1;
set t = ( f + g );
set w = ( x + y );
A13: s1 >= ( 0 ) by A8,A11,CKB73:1;
consider s2 being Real such that A14: (s2 = ( Integral (M,( ( abs g ) to_power k )) ) & ||. y .|| = ( s2 to_power ( 1 / k ) )) by A9;
( f + g ) in ( x + y ) by CKB80:1,A7,A9;
then (ex r being Real st ((( 0 ) <= r & r = ( Integral (M,( ( abs t ) to_power k )) )) & ||. w .|| = ( r to_power ( 1 / k ) ))) by CKB79:1;
hence ||. ( x + y ) .|| <= ( ||. x .|| + ||. y .|| ) by CKB88:1,A2,A8,A10,A14,A11;
set t = ( a (#) f );
set w = ( a * x );
( a (#) f ) in ( a * x ) by CKB80:1,A7;
then (ex r being Real st ((( 0 ) <= r & r = ( Integral (M,( ( abs t ) to_power k )) )) & ||. w .|| = ( r to_power ( 1 / k ) ))) by CKB79:1;
then consider s being Real such that A15: (s = ( Integral (M,( ( abs t ) to_power k )) ) & ||. w .|| = ( s to_power ( 1 / k ) ));
A16: s = ( Integral (M,( ( ( abs a ) to_power k ) (#) ( ( abs f ) to_power k ) )) ) by A15,CKB24:1
.= ( ( R_EAL ( ( abs a ) to_power k ) ) * ( R_EAL s1 ) ) by A11,A8,MESFUNC6:102
.= ( ( ( abs a ) to_power k ) * s1 ) by EXTREAL1:5;
( ( abs a ) to_power k ) >= ( 0 ) by CKB7:1,COMPLEX1:46;
then ||. ( a * x ) .|| = ( ( ( ( abs a ) to_power k ) to_power ( 1 / k ) ) * ( s1 to_power ( 1 / k ) ) ) by A13,A15,A16,CKB8:1
.= ( ( ( abs a ) to_power ( k * ( 1 / k ) ) ) * ( s1 to_power ( 1 / k ) ) ) by COMPLEX1:46,HOLDER_1:2
.= ( ( ( abs a ) to_power 1 ) * ( s1 to_power ( 1 / k ) ) ) by XCMPLX_1:106;
hence ||. ( a * x ) .|| = ( ( abs a ) * ||. x .|| ) by A11,POWER:25;
end;
hence thesis by NORMSP_0:def 5,NORMSP_1:def 1,RSSPACE3:2;
end;
