environ
vocabularies RLVECT_1,ALGSTR_0,XBOOLE_0,SUBSET_1,ARYTM_1,ARYTM_3,SUPINF_2,RELAT_1,INT_2,CARD_FIL,TARSKI,GROUP_4,IDEAL_1,VECTSP_2,GROUP_1,FUNCSDOM,EQREL_1,STRUCT_0,WAYBEL20,PARTFUN1,RELAT_2,SETWISEO,FUNCT_1,MESFUNC1,BINOP_1,VECTSP_1,LATTICES,WELLORD2,ORDERS_1,WELLORD1,RING_1;
notations TARSKI,XBOOLE_0,SUBSET_1,SETWISEO,RELAT_1,RELSET_1,FUNCT_1,PARTFUN1,ALG_1,RELAT_2,EQREL_1,WELLORD1,WELLORD2,ORDERS_1,BINOP_1,DOMAIN_1,STRUCT_0,ALGSTR_0,GROUP_1,RLVECT_1,VECTSP_1,VECTSP_2,FUNCSDOM,IDEAL_1,CKB4,CKB5,CKB6,CKB7,CKB16,CKB24,CKB25;
definitions TARSKI,XBOOLE_0,RELAT_1,RLVECT_1,GROUP_1,VECTSP_1,VECTSP_2,IDEAL_1,ORDERS_1,WELLORD1,STRUCT_0,ALGSTR_0,CKB4,CKB5,CKB6,CKB7,CKB16,CKB24;
theorems VECTSP_1,TARSKI,FUNCT_1,RLVECT_1,VECTSP_2,XBOOLE_0,FUNCT_2,BINOP_1,ZFMISC_1,GROUP_1,IDEAL_1,RELAT_1,EQREL_1,SETWISEO,ORDERS_1,WELLORD2,RELAT_2,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB14,CKB15,CKB16,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB27,CKB28,CKB29,CKB30,CKB31,CKB34;
schemes EQREL_1,BINOP_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSUB_1,EQREL_1,STRUCT_0,VECTSP_1,ALGSTR_1,QUOFIELD,IDEAL_1,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB17,CKB26,CKB32,CKB33;
constructors WELLORD1,WELLORD2,BINOP_1,SETWISEO,ORDERS_1,EQREL_1,GCD_1,IDEAL_1,DOMAIN_1,RELSET_1,CKB4,CKB5,CKB6,CKB7,CKB16,CKB24;
requirements BOOLE,SUBSET;
begin
reserve R for Ring;
reserve I for (Ideal of R);
theorem
Th17: (I is  quasi-prime iff ( R / I ) is  domRing-like)
proof
set E = ( EqRel (R,I) );
A1: ( Class (E,( 0. R )) ) = ( 0. ( R / I ) ) by CKB24:def 1;
thus (I is  quasi-prime implies ( R / I ) is  domRing-like)
proof
assume A2: I is  quasi-prime;
let x being (Element of ( R / I )),y being (Element of ( R / I ));
assume that
A3: ( x * y ) = ( 0. ( R / I ) );
consider a being (Element of R) such that A4: x = ( Class (E,a) ) by CKB27:1;
consider b being (Element of R) such that A5: y = ( Class (E,b) ) by CKB27:1;
( x * y ) = ( Class (E,( a * b )) ) by A4,A5,CKB30:1;
then (( ( a * b ) - ( 0. R ) ) = ( a * b ) & ( ( a * b ) - ( 0. R ) ) in I) by A1,A3,CKB19:1,RLVECT_1:13;
then A6: (a in I or b in I) by A2,CKB4:def 1;
(( a - ( 0. R ) ) = a & ( b - ( 0. R ) ) = b) by RLVECT_1:13;
hence thesis by A1,A4,A5,A6,CKB19:1;
end;

assume A7: ( R / I ) is  domRing-like;
let a being (Element of R),b being (Element of R);
reconsider x = ( Class (E,a) ),y = ( Class (E,b) ) as (Element of ( R / I )) by CKB28:1;
A8: ( ( a * b ) - ( 0. R ) ) = ( a * b ) by RLVECT_1:13;
A9: ( Class (E,( a * b )) ) = ( x * y ) by CKB30:1;
assume ( a * b ) in I;
then ( Class (E,( a * b )) ) = ( Class (E,( 0. R )) ) by A8,CKB19:1;
then (x = ( 0. ( R / I ) ) or y = ( 0. ( R / I ) )) by A1,A7,A9,VECTSP_2:def 1;
then (( a - ( 0. R ) ) in I or ( b - ( 0. R ) ) in I) by A1,CKB19:1;
hence thesis by RLVECT_1:13;
end;
