environ
vocabularies FUNCT_1,PBOOLE,RELAT_1,FUNCT_4,FUNCOP_1,XBOOLE_0,FINSET_1,TARSKI,ZFMISC_1,PZFMISC1;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,FUNCT_1,FUNCT_4,FINSET_1,FUNCOP_1,PBOOLE,MBOOLEAN,CKB4,CKB6;
definitions FINSET_1,PBOOLE,FUNCOP_1,CKB4,CKB6;
theorems FUNCOP_1,ENUMSET1,FUNCT_4,MBOOLEAN,PBOOLE,SETWISEO,TARSKI,ZFMISC_1,RELAT_1,XBOOLE_0,PARTFUN1,CKB1,CKB2,CKB3,CKB4,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70;
schemes PBOOLE;
registrations XBOOLE_0,FUNCOP_1,FINSET_1,CKB5,CKB7;
constructors FUNCT_4,MBOOLEAN,PBOOLE,FINSET_1,RELSET_1,CKB4,CKB6;
requirements BOOLE;
begin
reserve i for set;
reserve I for set;
reserve A for (ManySortedSet of I);
reserve B for (ManySortedSet of I);
reserve X for (ManySortedSet of I);
reserve Y for (ManySortedSet of I);
theorem
((A c= X & B c= Y) implies ( [| A,Y |] /\ [| X,B |] ) = [| A,B |])
proof
assume that
A1: A c= X
and
A2: B c= Y;
now
let i;
assume A3: i in I;
then A4: ( A . i ) c= ( X . i ) by A1,PBOOLE:def 2;
A5: ( B . i ) c= ( Y . i ) by A2,A3,PBOOLE:def 2;
thus ( ( [| A,Y |] /\ [| X,B |] ) . i ) = ( ( [| A,Y |] . i ) /\ ( [| X,B |] . i ) ) by A3,PBOOLE:def 5
.= ( [: ( A . i ),( Y . i ) :] /\ ( [| X,B |] . i ) ) by A3,PBOOLE:def 16
.= ( [: ( A . i ),( Y . i ) :] /\ [: ( X . i ),( B . i ) :] ) by A3,PBOOLE:def 16
.= [: ( A . i ),( B . i ) :] by A4,A5,ZFMISC_1:101
.= ( [| A,B |] . i ) by A3,PBOOLE:def 16;
end;
hence thesis by PBOOLE:3;
end;
