environ
vocabularies STRUCT_0,XBOOLE_0,MSUALG_1,RELAT_1,PBOOLE,MEMBER_1,TARSKI,REALSET1,FUNCT_1,PZFMISC1,MSUALG_3,FUNCT_6,MSAFREE,LANG1,MCART_1,TREES_4,SUBSET_1,FUNCOP_1,PRELAMB,MSUALG_2,UNIALG_2,MARGREL1,CARD_3,NAT_1,PARTFUN1;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,RELSET_1,FUNCT_1,MCART_1,PARTFUN1,FUNCOP_1,FUNCT_6,PZFMISC1,FINSEQ_2,STRUCT_0,LANG1,FUNCT_2,CARD_3,NAT_1,TREES_4,DTCONSTR,PBOOLE,MSUALG_1,MSUALG_2,MSUALG_3,MSAFREE;
definitions MSUALG_2,MSUALG_3,PBOOLE,FUNCOP_1,TARSKI,XBOOLE_0;
theorems FUNCOP_1,FUNCT_1,FUNCT_2,FUNCT_6,MCART_1,MSAFREE,MSAFREE2,MSUALG_1,MSUALG_2,MSUALG_3,MSUHOM_1,PBOOLE,RELAT_1,CARD_3,RELSET_1,PZFMISC1,ORDINAL1,PARTFUN1,FINSEQ_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB19;
schemes MSAFREE1,PBOOLE;
registrations FUNCT_1,RELSET_1,FUNCOP_1,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_3,MSAFREE,MSSUBFAM,CKB18;
constructors PZFMISC1,MSSUBFAM,MSUALG_3,MSAFREE,RELSET_1,FINSEQ_2;
requirements SUBSET,BOOLE;
begin
reserve S for non  void non  empty ManySortedSign;
reserve U1 for  non-empty MSAlgebra over S;
reserve U2 for  non-empty MSAlgebra over S;
theorem
(for U1 being MSAlgebra over S holds (for U2 being (MSSubAlgebra of U1) holds (for B1 being (MSSubset of U1) holds (for B2 being (MSSubset of U2) holds (B1 = B2 implies ( GenMSAlg B1 ) = ( GenMSAlg B2 ))))))
proof
let U1 being MSAlgebra over S;
let U2 being (MSSubAlgebra of U1);
let B1 being (MSSubset of U1);
let B2 being (MSSubset of U2);
assume that
A1: B1 = B2;
reconsider H = ( GenMSAlg B1 ) as (MSSubAlgebra of U2) by A1,MSUALG_2:def 17;
reconsider G = ( GenMSAlg B2 ) as (MSSubAlgebra of U1) by MSUALG_2:6;
B1 is (MSSubset of G) by A1,MSUALG_2:def 17;
then A2: ( GenMSAlg B1 ) is (MSSubAlgebra of G) by MSUALG_2:def 17;
B1 is (MSSubset of H) by MSUALG_2:def 17;
then ( GenMSAlg B2 ) is (MSSubAlgebra of ( GenMSAlg B1 )) by A1,MSUALG_2:def 17;
hence thesis by A2,MSUALG_2:7;
end;
