environ
vocabularies NUMBERS,FUNCT_1,CARD_3,RELAT_1,XBOOLE_0,TARSKI,CARD_1,ZFMISC_1,SUBSET_1,PRE_TOPC,STRUCT_0,RELAT_2,FINSEQ_1,NAT_1,XXREAL_0,ARYTM_3,FINSET_1,SETFAM_1,PRALG_1,PBOOLE,FUNCOP_1,WAYBEL_3,FUNCT_4,RLVECT_2,INTEGRA1,ARYTM_1,ORDINAL4,PENCIL_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,XCMPLX_0,SETFAM_1,CARD_1,NUMBERS,NAT_1,FINSET_1,RELAT_1,DOMAIN_1,STRUCT_0,FUNCT_1,PBOOLE,FUNCT_7,WAYBEL_3,FINSEQ_1,CARD_3,PRE_TOPC,PZFMISC1,FUNCOP_1,PRALG_1,XXREAL_0,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB24,CKB25,CKB26,CKB30,CKB31,CKB32,CKB33,CKB35,CKB36,CKB37,CKB42,CKB43,CKB52,CKB57,CKB58;
definitions TARSKI,WAYBEL_3,PBOOLE,XBOOLE_0,PRALG_1,STRUCT_0,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB24,CKB26,CKB30,CKB31,CKB32,CKB33,CKB35,CKB37,CKB43,CKB52,CKB57,CKB58;
theorems TARSKI,FUNCT_1,FUNCOP_1,PBOOLE,CARD_3,PRALG_1,STRUCT_0,CARD_1,YELLOW11,ENUMSET1,FINSEQ_1,CARD_2,ZFMISC_1,NAT_1,FUNCT_7,YELLOW_6,YELLOW_8,PZFMISC1,PUA2MSS1,FINSEQ_3,RELAT_1,XBOOLE_0,XBOOLE_1,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,PARTFUN1,PRE_POLY,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB24,CKB26,CKB30,CKB31,CKB32,CKB33,CKB35,CKB37,CKB43,CKB45,CKB47,CKB48,CKB52,CKB53,CKB55,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB65,CKB66,CKB67,CKB68;
schemes FINSEQ_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSET_1,XREAL_0,CARD_3,REALSET1,PZFMISC1,STRUCT_0,YELLOW_6,ORDINAL1,CARD_1,ZFMISC_1,PRE_POLY,FUNCOP_1,CKB21,CKB22,CKB23,CKB27,CKB28,CKB29,CKB34,CKB38,CKB39,CKB40,CKB41,CKB44,CKB46,CKB49,CKB50,CKB51,CKB54,CKB56,CKB64;
constructors XXREAL_0,PZFMISC1,REALSET2,PRALG_1,WAYBEL_3,POLYNOM1,PBOOLE,FUNCT_7,FUNCT_4,RELSET_1,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB26,CKB30,CKB32,CKB33,CKB36,CKB37,CKB42,CKB43,CKB52,CKB57,CKB58;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
theorem
Th23: (for I being non empty set holds (for A being  Segre-like non trivial-yielding (ManySortedSet of I) holds (for x,y being (ManySortedSet of I) holds ((x in ( product A ) & y in ( product A )) implies (for i being set holds (i <> ( indx A ) implies ( x . i ) = ( y . i )))))))
proof
let I being non empty set;
let A being  Segre-like non trivial-yielding (ManySortedSet of I);
let x being (ManySortedSet of I),y being (ManySortedSet of I);
assume that
A1: x in ( product A )
and
A2: y in ( product A );
let i being set;
A3: ( dom A ) = I by PARTFUN1:def 2;
assume A4: i <> ( indx A );
per cases ;
suppose A5: (not i in I);

then A6: (not i in ( dom y )) by PARTFUN1:def 2;
(not i in ( dom x )) by A5,PARTFUN1:def 2;
hence ( x . i ) = ( {} ) by FUNCT_1:def 2
.= ( y . i ) by A6,FUNCT_1:def 2;
end;
suppose i in I;

then reconsider ii = i as (Element of I);
consider j being (Element of I) such that A7: (for k being (Element of I) holds (k <> j implies ( A . k ) is 1 -element)) by CKB43:def 1;
now
assume j <> ( indx A );
then ( A . ( indx A ) ) is 1 -element by A7;
hence contradiction by CKB52:def 1;
end;
then ( A . ii ) is 1 -element by A4,A7;
then consider o being set such that A8: ( A . i ) = { o } by ZFMISC_1:131;
A9: ( x . ii ) in ( A . ii ) by A1,A3,CARD_3:9;
( y . ii ) in ( A . ii ) by A2,A3,CARD_3:9;
hence ( y . i ) = o by A8,TARSKI:def 1
.= ( x . i ) by A8,A9,TARSKI:def 1;
end;
end;
