environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,MATRIX_1,FINSEQ_3,RELAT_1,FINSEQ_1,TARSKI,ARYTM_3,XXREAL_0,CARD_1,TREES_1,FUNCT_1,INCSP_1,ORDINAL4,SUBSET_1,VECTSP_1,RLVECT_2,RLVECT_3,CARD_3,ARYTM_1,SUPINF_2,RLVECT_5,FINSET_1,STRUCT_0,RLSUB_1,ALGSTR_0,PARTFUN1,RLVECT_1,ZFMISC_1,QC_LANG1,FUNCT_2,VALUED_1,PRE_POLY,FINSEQ_2,RVSUM_1,FINSEQ_4,FVSUM_1,MATRLIN,MSSUBFAM,UNIALG_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,XCMPLX_0,NAT_1,MOD_2,FINSEQ_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,FUNCT_3,STRUCT_0,ALGSTR_0,MATRIX_1,MATRIX_3,FVSUM_1,RLVECT_1,VECTSP_1,VECTSP_4,VECTSP_6,VECTSP_7,FINSET_1,FINSEQ_3,FINSEQ_2,FINSEQOP,BINOP_1,XXREAL_0,PRE_POLY,GRCAT_1,CKB1,CKB6,CKB11,CKB13,CKB14,CKB15,CKB19,CKB21,CKB33,CKB34;
definitions TARSKI,FVSUM_1,FUNCOP_1,ALGSTR_0,PRE_POLY,CKB11,CKB13,CKB14,CKB15,CKB19,CKB21;
theorems TARSKI,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,VECTSP_1,VECTSP_4,VECTSP_6,VECTSP_7,RLVECT_1,FUNCT_1,FUNCT_2,FUNCT_3,MATRIX_1,MATRIX_2,MATRIX_3,MOD_2,ZFMISC_1,NAT_1,FVSUM_1,SUBSET_1,FINSEQOP,FUNCOP_1,RELAT_1,PARTFUN2,XBOOLE_0,XBOOLE_1,RLVECT_2,ORDINAL1,PARTFUN1,PRE_POLY,GRCAT_1,CKB2,CKB3,CKB4,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44;
schemes FINSEQ_1,FINSEQ_2,FUNCT_2,MATRIX_1,NAT_1,FINSEQ_4;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,STRUCT_0,VECTSP_1,MATRIX_1,CARD_1,VECTSP_7,MOD_2,GRCAT_1,PRE_POLY,RELAT_1,FUNCT_1,FINSEQ_4,CKB12,CKB32;
constructors PARTFUN1,BINOP_1,FUNCT_3,SQUARE_1,NAT_1,VECTSP_6,VECTSP_7,MOD_2,FVSUM_1,MATRIX_3,RELSET_1,PRE_POLY,GRCAT_1,CKB1,CKB6,CKB11,CKB13,CKB14,CKB15,CKB19,CKB21,CKB33,CKB34;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve i for Nat;
reserve j for Nat;
reserve m for Nat;
reserve n for Nat;
reserve K for Field;
reserve V1 for  finite-dimensional (VectSp of K);
reserve F for (FinSequence of V1);
reserve d for (FinSequence of K);
theorem
Th38: (for M being (Matrix of n,m,(the carrier of K)) holds ((n > ( 0 ) & m > ( 0 )) implies (for p,d being (FinSequence of K) holds (((( len p ) = n & ( len d ) = m) & (for j holds (j in ( dom d ) implies ( d /. j ) = ( Sum ( mlt (p,( Col (M,j) )) ) )))) implies (for b,c being (FinSequence of V1) holds (((( len b ) = m & ( len c ) = n) & (for i holds (i in ( dom c ) implies ( c /. i ) = ( Sum ( lmlt (( Line (M,i) ),b) ) )))) implies ( Sum ( lmlt (p,c) ) ) = ( Sum ( lmlt (d,b) ) )))))))
proof
let M being (Matrix of n,m,(the carrier of K));
assume that
A1: n > ( 0 )
and
A2: m > ( 0 );
A3: ( len M ) = n by A1,MATRIX_1:23;
reconsider n1 = n,m1 = m as (Element of ( NAT )) by ORDINAL1:def 12;
let p being (FinSequence of K);
let d being (FinSequence of K);
assume that
A4: ( len p ) = n
and
A5: ( len d ) = m
and
A6: (for j holds (j in ( dom d ) implies ( d /. j ) = ( Sum ( mlt (p,( Col (M,j) )) ) )));
let b being (FinSequence of V1);
let c being (FinSequence of V1);
assume that
A7: ( len b ) = m
and
A8: ( len c ) = n
and
A9: (for i holds (i in ( dom c ) implies ( c /. i ) = ( Sum ( lmlt (( Line (M,i) ),b) ) )));
deffunc V(Nat,Nat) = ( ( ( p /. $1 ) * ( M * ($1,$2) ) ) * ( b /. $2 ) );
consider M1 being (Matrix of n1,m1,(the carrier of V1)) such that A10: (for i holds (for j holds ([ i,j ] in ( Indices M1 ) implies ( M1 * (i,j) ) = V(i,j)))) from MATRIX_1:sch 1;
A11: ( width M1 ) = ( len ( M1 @ ) ) by MATRIX_1:def 6
.= ( len ( Sum ( M1 @ ) ) ) by CKB21:def 1;
A12: ( dom d ) = ( dom b ) by A5,A7,FINSEQ_3:29;
then A13: ( dom ( lmlt (d,b) ) ) = ( dom b ) by CKB20:1;
then A14: ( len ( lmlt (d,b) ) ) = ( len b ) by FINSEQ_3:29
.= ( len ( Sum ( M1 @ ) ) ) by A1,A7,A11,MATRIX_1:23;
then A15: ( dom ( lmlt (d,b) ) ) = ( Seg ( len ( Sum ( M1 @ ) ) ) ) by FINSEQ_1:def 3;
A16: ( width M1 ) = m by A1,MATRIX_1:23;
A17: ( len M1 ) = n by A1,MATRIX_1:23;
A18: ( dom ( lmlt (d,b) ) ) = ( dom d ) by A12,CKB20:1;
A19:now
A20: ( Seg ( len ( Sum ( M1 @ ) ) ) ) = ( dom ( Sum ( M1 @ ) ) ) by FINSEQ_1:def 3;
let j being Nat;
assume that
A21: j in ( dom ( lmlt (d,b) ) );
A22: j in ( dom ( Sum ( M1 @ ) ) ) by A15,A21,FINSEQ_1:def 3;
A23: j in ( dom d ) by A12,A21,CKB20:1;
A24: (( d /. j ) = ( d . j ) & ( b /. j ) = ( b . j )) by A18,A13,A21,PARTFUN1:def 6;
( len ( Sum ( M1 @ ) ) ) = ( len ( M1 @ ) ) by CKB21:def 1;
then A25: ( dom ( Sum ( M1 @ ) ) ) = ( dom ( M1 @ ) ) by FINSEQ_3:29;
then A26: ( ( M1 @ ) /. j ) = ( ( M1 @ ) . j ) by A22,PARTFUN1:def 6
.= ( Line (( M1 @ ),j) ) by A22,A25,MATRIX_2:16;
reconsider H = ( mlt (p,( Col (M,j) )) ) as (FinSequence of K);
deffunc V(Nat) = ( ( H /. $1 ) * ( b /. j ) );
consider G being (FinSequence of V1) such that A27: (( len G ) = ( len p ) & (for i being Nat holds (i in ( dom G ) implies ( G . i ) = V(i)))) from FINSEQ_2:sch 1;
A28: ( len p ) = ( len ( Col (M,j) ) ) by A4,A3,MATRIX_1:def 8;
then A29: ( len ( (the multF of K) .: (p,( Col (M,j) )) ) ) = ( len p ) by FINSEQ_2:72;
then A30: ( dom H ) = ( dom G ) by A27,FINSEQ_3:29;
A31: ( dom p ) = ( dom G ) by A27,FINSEQ_3:29;
A32: ( len ( Line (( M1 @ ),j) ) ) = ( width ( M1 @ ) ) by MATRIX_1:def 7
.= ( len ( ( M1 @ ) @ ) ) by MATRIX_1:def 6
.= ( len G ) by A1,A2,A4,A17,A16,A27,MATRIX_2:13;
then A33: ( dom ( Line (( M1 @ ),j) ) ) = ( Seg ( len G ) ) by FINSEQ_1:def 3;
A34: ( dom G ) = ( Seg ( len p ) ) by A27,FINSEQ_1:def 3;
A35:now
let i being Nat;
A36: ( dom M ) = ( Seg ( len M ) ) by FINSEQ_1:def 3;
assume A37: i in ( dom ( Line (( M1 @ ),j) ) );
then A38: i in ( Seg ( len ( (the multF of K) .: (p,( Col (M,j) )) ) ) ) by A27,A28,A33,FINSEQ_2:72;
then A39: i in ( dom H ) by FINSEQ_1:def 3;
A40: i in ( dom ( (the multF of K) .: (p,( Col (M,j) )) ) ) by A38,FINSEQ_1:def 3;
A41: ( Seg ( len G ) ) = ( dom G ) by FINSEQ_1:def 3;
then A42: ( ( p /. i ) * ( M * (i,j) ) ) = ( (the multF of K) . (( p . i ),( M * (i,j) )) ) by A31,A33,A37,PARTFUN1:def 6
.= ( (the multF of K) . (( p . i ),( ( Col (M,j) ) . i )) ) by A4,A3,A27,A33,A37,A36,MATRIX_1:def 8
.= ( ( (the multF of K) .: (p,( Col (M,j) )) ) . i ) by A40,FUNCOP_1:22
.= ( H /. i ) by A39,PARTFUN1:def 6;
( dom M1 ) = ( dom G ) by A4,A17,A27,FINSEQ_3:29;
then [ i,j ] in [: ( dom M1 ),( Seg ( width M1 ) ) :] by A11,A15,A21,A33,A37,A41,ZFMISC_1:87;
then A43: [ i,j ] in ( Indices M1 ) by MATRIX_1:def 4;
i in ( Seg ( width ( M1 @ ) ) ) by A32,A33,A37,MATRIX_1:def 7;
hence ( ( Line (( M1 @ ),j) ) . i ) = ( ( M1 @ ) * (j,i) ) by MATRIX_1:def 7
.= ( M1 * (i,j) ) by A43,MATRIX_1:def 6
.= ( ( H /. i ) * ( b /. j ) ) by A10,A43,A42
.= ( G . i ) by A27,A34,A33,A37;
end;
thus ( ( lmlt (d,b) ) . j ) = ( (the lmult of V1) . (( d . j ),( b . j )) ) by A21,FUNCOP_1:22
.= ( ( d /. j ) * ( b /. j ) ) by A24,VECTSP_1:def 12
.= ( ( Sum H ) * ( b /. j ) ) by A6,A23
.= ( Sum G ) by A27,A29,A30,CKB17:1
.= ( Sum ( ( M1 @ ) /. j ) ) by A32,A35,A26,FINSEQ_2:9
.= ( ( Sum ( M1 @ ) ) /. j ) by A22,CKB21:def 1
.= ( ( Sum ( M1 @ ) ) . j ) by A15,A21,A20,PARTFUN1:def 6;
end;
A44: ( dom p ) = ( dom c ) by A4,A8,FINSEQ_3:29;
then A45: ( dom ( lmlt (p,c) ) ) = ( dom p ) by CKB20:1;
then A46: ( len ( lmlt (p,c) ) ) = ( len p ) by FINSEQ_3:29
.= ( len M1 ) by A4,MATRIX_1:def 2
.= ( len ( Sum M1 ) ) by CKB21:def 1;
now
let i being Nat;
assume that
A47: i in ( dom ( Sum M1 ) );
A48: i in ( dom c ) by A44,A45,A46,A47,FINSEQ_3:29;
then A49: (( c . i ) = ( c /. i ) & ( p . i ) = ( p /. i )) by A44,PARTFUN1:def 6;
i in ( Seg ( len ( Sum M1 ) ) ) by A47,FINSEQ_1:def 3;
then i in ( Seg ( len M1 ) ) by CKB21:def 1;
then A50: i in ( dom M1 ) by FINSEQ_1:def 3;
then A51: ( M1 /. i ) = ( M1 . i ) by PARTFUN1:def 6
.= ( Line (M1,i) ) by A50,MATRIX_2:16;
deffunc V(Nat) = ( ( p /. i ) * ( ( lmlt (( Line (M,i) ),b) ) /. $1 ) );
consider F being (FinSequence of V1) such that A52: (( len F ) = ( len b ) & (for j being Nat holds (j in ( dom F ) implies ( F . j ) = V(j)))) from FINSEQ_2:sch 1;
A53: ( len F ) = ( width M ) by A1,A7,A52,MATRIX_1:23;
A54: ( dom ( Line (M,i) ) ) = ( Seg ( len ( Line (M,i) ) ) ) by FINSEQ_1:def 3
.= ( Seg ( len F ) ) by A53,MATRIX_1:def 7
.= ( dom b ) by A52,FINSEQ_1:def 3;
then ( dom ( lmlt (( Line (M,i) ),b) ) ) = ( dom b ) by CKB20:1;
then A55: (( len F ) = ( len ( lmlt (( Line (M,i) ),b) ) ) & ( dom F ) = ( dom ( lmlt (( Line (M,i) ),b) ) )) by A52,FINSEQ_3:29;
A56: ( len F ) = ( width M1 ) by A1,A7,A52,MATRIX_1:23;
then A57: ( len ( Line (M1,i) ) ) = ( len F ) by MATRIX_1:def 7;
then A58: ( dom ( M1 /. i ) ) = ( Seg ( len F ) ) by A51,FINSEQ_1:def 3;
A59: ( dom F ) = ( Seg ( len b ) ) by A52,FINSEQ_1:def 3;
A60:now
let j being Nat;
assume A61: j in ( dom ( M1 /. i ) );
then A62: ( ( Line (M,i) ) . j ) = ( M * (i,j) ) by A53,A58,MATRIX_1:def 7;
[ i,j ] in [: ( dom M1 ),( Seg ( width M1 ) ) :] by A56,A50,A58,A61,ZFMISC_1:87;
then A63: [ i,j ] in ( Indices M1 ) by MATRIX_1:def 4;
A64: j in ( dom b ) by A52,A58,A61,FINSEQ_1:def 3;
then A65: ( b . j ) = ( b /. j ) by PARTFUN1:def 6;
A66: j in ( dom ( lmlt (( Line (M,i) ),b) ) ) by A54,A64,CKB20:1;
then A67: ( ( lmlt (( Line (M,i) ),b) ) /. j ) = ( ( lmlt (( Line (M,i) ),b) ) . j ) by PARTFUN1:def 6
.= ( (the lmult of V1) . (( ( Line (M,i) ) . j ),( b . j )) ) by A66,FUNCOP_1:22
.= ( ( M * (i,j) ) * ( b /. j ) ) by A65,A62,VECTSP_1:def 12;
thus ( ( M1 /. i ) . j ) = ( M1 * (i,j) ) by A56,A51,A58,A61,MATRIX_1:def 7
.= ( ( ( p /. i ) * ( M * (i,j) ) ) * ( b /. j ) ) by A10,A63
.= ( ( p /. i ) * ( ( lmlt (( Line (M,i) ),b) ) /. j ) ) by A67,VECTSP_1:def 16
.= ( F . j ) by A52,A59,A58,A61;
end;
A68: (for j being (Element of ( NAT )) holds (j in ( dom F ) implies ( F . j ) = ( ( p /. i ) * ( ( lmlt (( Line (M,i) ),b) ) /. j ) ))) by A52;
i in ( dom ( (the lmult of V1) .: (p,c) ) ) by A46,A47,FINSEQ_3:29;
hence ( ( lmlt (p,c) ) . i ) = ( (the lmult of V1) . (( p . i ),( c . i )) ) by FUNCOP_1:22
.= ( ( p /. i ) * ( c /. i ) ) by A49,VECTSP_1:def 12
.= ( ( p /. i ) * ( Sum ( lmlt (( Line (M,i) ),b) ) ) ) by A9,A48
.= ( Sum F ) by A55,A68,RLVECT_2:67
.= ( Sum ( M1 /. i ) ) by A57,A51,A60,FINSEQ_2:9
.= ( ( Sum M1 ) /. i ) by A47,CKB21:def 1
.= ( ( Sum M1 ) . i ) by A47,PARTFUN1:def 6;
end;
hence ( Sum ( lmlt (p,c) ) ) = ( Sum ( Sum M1 ) ) by A46,FINSEQ_2:9
.= ( Sum ( Sum ( M1 @ ) ) ) by CKB44:1
.= ( Sum ( lmlt (d,b) ) ) by A14,A19,FINSEQ_2:9;
end;
