environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,MATRIX_1,FINSEQ_3,RELAT_1,FINSEQ_1,TARSKI,ARYTM_3,XXREAL_0,CARD_1,TREES_1,FUNCT_1,INCSP_1,ORDINAL4,SUBSET_1,VECTSP_1,RLVECT_2,RLVECT_3,CARD_3,ARYTM_1,SUPINF_2,RLVECT_5,FINSET_1,STRUCT_0,RLSUB_1,ALGSTR_0,PARTFUN1,RLVECT_1,ZFMISC_1,QC_LANG1,FUNCT_2,VALUED_1,PRE_POLY,FINSEQ_2,RVSUM_1,FINSEQ_4,FVSUM_1,MATRLIN,MSSUBFAM,UNIALG_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,XCMPLX_0,NAT_1,MOD_2,FINSEQ_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,FUNCT_3,STRUCT_0,ALGSTR_0,MATRIX_1,MATRIX_3,FVSUM_1,RLVECT_1,VECTSP_1,VECTSP_4,VECTSP_6,VECTSP_7,FINSET_1,FINSEQ_3,FINSEQ_2,FINSEQOP,BINOP_1,XXREAL_0,PRE_POLY,GRCAT_1,CKB1,CKB6,CKB11,CKB13,CKB14,CKB15,CKB19,CKB21,CKB33,CKB34,CKB46;
definitions TARSKI,FVSUM_1,FUNCOP_1,ALGSTR_0,PRE_POLY,CKB11,CKB13,CKB14,CKB15,CKB19,CKB21,CKB46;
theorems TARSKI,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,VECTSP_1,VECTSP_4,VECTSP_6,VECTSP_7,RLVECT_1,FUNCT_1,FUNCT_2,FUNCT_3,MATRIX_1,MATRIX_2,MATRIX_3,MOD_2,ZFMISC_1,NAT_1,FVSUM_1,SUBSET_1,FINSEQOP,FUNCOP_1,RELAT_1,PARTFUN2,XBOOLE_0,XBOOLE_1,RLVECT_2,ORDINAL1,PARTFUN1,PRE_POLY,GRCAT_1,CKB2,CKB3,CKB4,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48;
schemes FINSEQ_1,FINSEQ_2,FUNCT_2,MATRIX_1,NAT_1,FINSEQ_4;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,STRUCT_0,VECTSP_1,MATRIX_1,CARD_1,VECTSP_7,MOD_2,GRCAT_1,PRE_POLY,RELAT_1,FUNCT_1,FINSEQ_4,CKB12,CKB32;
constructors PARTFUN1,BINOP_1,FUNCT_3,SQUARE_1,NAT_1,VECTSP_6,VECTSP_7,MOD_2,FVSUM_1,MATRIX_3,RELSET_1,PRE_POLY,GRCAT_1,CKB1,CKB6,CKB11,CKB13,CKB14,CKB15,CKB19,CKB21,CKB33,CKB34,CKB46;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve k for Nat;
reserve t for Nat;
reserve K for Field;
reserve V1 for  finite-dimensional (VectSp of K);
reserve b1 for (OrdBasis of V1);
reserve v for (Element of V1);
reserve KL for (Linear_Combination of V1);
theorem
Th40: v = ( Sum ( lmlt (( v |-- b1 ),b1) ) )
proof
consider KL being (Linear_Combination of V1) such that A1: (v = ( Sum KL ) & ( Carrier KL ) c= ( rng b1 )) and A2: (for k holds ((1 <= k & k <= ( len ( v |-- b1 ) )) implies ( ( v |-- b1 ) /. k ) = ( KL . ( b1 /. k ) ))) by CKB46:def 1;
( len ( v |-- b1 ) ) = ( len b1 ) by CKB46:def 1;
then A3: ( dom ( v |-- b1 ) ) = ( dom b1 ) by FINSEQ_3:29;
then A4: ( dom b1 ) = ( dom ( lmlt (( v |-- b1 ),b1) ) ) by CKB20:1;
( len ( KL (#) b1 ) ) = ( len b1 ) by VECTSP_6:def 5
.= ( len ( lmlt (( v |-- b1 ),b1) ) ) by A4,FINSEQ_3:29;
then A5: ( dom ( KL (#) b1 ) ) = ( dom ( lmlt (( v |-- b1 ),b1) ) ) by FINSEQ_3:29;
A6:now
let t being Nat;
assume A7: t in ( dom ( lmlt (( v |-- b1 ),b1) ) );
then A8: ( b1 /. t ) = ( b1 . t ) by A4,PARTFUN1:def 6;
t in ( dom ( v |-- b1 ) ) by A3,A7,CKB20:1;
then A9: t <= ( len ( v |-- b1 ) ) by FINSEQ_3:25;
A10: 1 <= t by A7,FINSEQ_3:25;
then A11: ( ( v |-- b1 ) /. t ) = ( ( v |-- b1 ) . t ) by A9,FINSEQ_4:15;
t in ( dom ( KL (#) b1 ) ) by A5,A7;
hence ( ( KL (#) b1 ) . t ) = ( ( KL . ( b1 /. t ) ) * ( b1 /. t ) ) by VECTSP_6:def 5
.= ( ( ( v |-- b1 ) /. t ) * ( b1 /. t ) ) by A2,A10,A9
.= ( (the lmult of V1) . (( ( v |-- b1 ) . t ),( b1 . t )) ) by A8,A11,VECTSP_1:def 12
.= ( ( lmlt (( v |-- b1 ),b1) ) . t ) by A7,FUNCOP_1:22;
end;
b1 is  one-to-one by CKB13:def 1;
hence v = ( Sum ( KL (#) b1 ) ) by A1,CKB29:1
.= ( Sum ( lmlt (( v |-- b1 ),b1) ) ) by A5,A6,FINSEQ_1:13;
end;
