environ
vocabularies NUMBERS,PRE_TOPC,EUCLID,FINSEQ_1,REAL_1,SUBSET_1,GOBOARD1,NAT_1,XBOOLE_0,CARD_1,ARYTM_3,XXREAL_0,TARSKI,ARYTM_1,RELAT_1,ORDINAL4,PARTFUN1,FUNCT_1,RLTOPSP1,TOPREAL1,MCART_1,MATRIX_1,INCSP_1,ZFMISC_1,TREES_1,ORDINAL2,COMPLEX1,STRUCT_0,GOBOARD2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,CARD_1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_1,PARTFUN1,FINSEQ_1,SEQ_1,VALUED_0,STRUCT_0,PRE_TOPC,SEQ_4,MATRIX_1,RLTOPSP1,EUCLID,TOPREAL1,GOBOARD1,XXREAL_0;
definitions TARSKI,TOPREAL1,GOBOARD1,XBOOLE_0;
theorems TARSKI,NAT_1,ZFMISC_1,FUNCT_1,FINSEQ_1,ABSVALUE,SEQ_4,FINSEQ_2,MATRIX_1,EUCLID,TOPREAL1,TOPREAL3,GOBOARD1,FINSEQ_4,FINSEQ_3,PARTFUN2,INT_1,XBOOLE_0,XBOOLE_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,PARTFUN1,SEQM_3,RLTOPSP1,CKB1,CKB2,CKB3,CKB4,CKB5;
schemes NAT_1,MATRIX_1,FINSEQ_4;
registrations RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,FINSEQ_1,STRUCT_0,EUCLID,GOBOARD1,VALUED_0,CARD_1,XXREAL_2,RELAT_1,FUNCT_1,SEQM_3,SEQ_4;
constructors PARTFUN1,SQUARE_1,NAT_1,COMPLEX1,SEQ_4,TOPREAL1,GOBOARD1,SEQ_1,XXREAL_2,SEQM_3,RELSET_1,DOMAIN_1,BINOP_2,RVSUM_1;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve f for (FinSequence of ( TOP-REAL 2 ));
reserve g for (FinSequence of ( TOP-REAL 2 ));
reserve n for (Element of ( NAT ));
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
reserve x for set;
theorem
Th11: ( L~ f ) c= ( L~ ( f ^ g ) )
proof
set f1 = ( f ^ g );
set lf = { ( LSeg (f,i) ): (1 <= i & ( i + 1 ) <= ( len f )) };
set l1 = { ( LSeg (f1,j) ): (1 <= j & ( j + 1 ) <= ( len f1 )) };
let x;
assume x in ( L~ f );
then consider X being set such that A1: x in X and A2: X in lf by TARSKI:def 4;
consider n such that A3: X = ( LSeg (f,n) ) and A4: 1 <= n and A5: ( n + 1 ) <= ( len f ) by A2;
n <= ( n + 1 ) by NAT_1:11;
then n <= ( len f ) by A5,XXREAL_0:2;
then A6: n in ( dom f ) by A4,FINSEQ_3:25;
( len f1 ) = ( ( len f ) + ( len g ) ) by FINSEQ_1:22;
then ( len f ) <= ( len f1 ) by XREAL_1:31;
then A7: ( n + 1 ) <= ( len f1 ) by A5,XXREAL_0:2;
1 <= ( n + 1 ) by XREAL_1:31;
then ( n + 1 ) in ( dom f ) by A5,FINSEQ_3:25;
then X = ( LSeg (f1,n) ) by A3,A6,TOPREAL3:18;
then X in l1 by A4,A7;
hence thesis by A1,TARSKI:def 4;
end;
