environ
vocabularies NUMBERS,XBOOLE_0,PROB_1,MEASURE1,PARTFUN1,REAL_1,XREAL_0,ORDINAL1,SUBSET_1,SEQFUNC,MEASURE6,RELAT_1,FUNCT_1,PBOOLE,TARSKI,SEQ_1,ORDINAL2,RINFSUP1,MESFUNC8,CARD_1,NAT_1,MESFUNC1,ARYTM_3,SEQ_2,XXREAL_0,XXREAL_2,SETFAM_1,COMSEQ_1,COMPLEX1,VALUED_1,SUPINF_2,POWER,ARYTM_1,MESFUNC5,INTEGRA5,MESFUNC2,FINSEQ_1,MESFUNC3,INT_1,ZFMISC_1,XCMPLX_0;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,COMPLEX1,XXREAL_0,XREAL_0,XXREAL_2,REAL_1,NAT_1,NAT_D,PROB_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FINSEQ_1,RFUNCT_3,VALUED_1,FUNCT_2,SETFAM_1,SUPINF_1,SUPINF_2,SEQ_1,SEQ_2,SEQFUNC,COMSEQ_1,COMSEQ_2,RINFSUP1,RINFSUP2,MEASURE1,MEASURE6,EXTREAL1,MESFUNC1,MESFUNC2,MESFUNC5,MESFUNC6,COMSEQ_3,MESFUN6C,MESFUNC8,SEQ_4,COMPLSP2,CKB1,CKB4,CKB6,CKB8,CKB10,CKB19,CKB21,CKB23;
definitions MESFUNC5,MEASURE6,COMPLEX1,RINFSUP2,TARSKI,XBOOLE_0,FINSEQ_1,COMPLSP2,XXREAL_3,CKB1,CKB4,CKB6,CKB8,CKB10,CKB19,CKB21,CKB23;
theorems MEASURE1,TARSKI,PARTFUN1,FUNCT_1,EXTREAL1,MESFUNC1,NAT_1,XBOOLE_0,XBOOLE_1,XCMPLX_0,XREAL_1,MESFUNC5,XXREAL_0,VALUED_1,MESFUNC6,COMPLEX1,RELAT_1,SQUARE_1,FINSEQ_1,MESFUN6C,ORDINAL1,FUNCT_2,SEQFUNC,SETFAM_1,RINFSUP1,MESFUNC7,MESFUNC8,COMSEQ_3,MESFUNC3,NUMBERS,RINFSUP2,XXREAL_2,COMPLSP2,NAT_D,FINSEQ_2,NAT_2,FINSEQ_3,RELSET_1,XXREAL_3,CKB1,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
schemes FUNCT_2,PARTFUN2,FINSEQ_1;
registrations NAT_1,MESFUNC8,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,VALUED_0,XCMPLX_0,PARTFUN1,FUNCT_2,RELAT_1,SEQ_2,COMSEQ_3,RELSET_1,FINSEQ_1,CKB3,CKB13;
constructors REAL_1,NAT_1,SQUARE_1,MEASURE6,EXTREAL1,MESFUNC2,MESFUNC3,MESFUNC5,SEQ_1,MESFUNC6,MESFUN6C,BINOP_2,RINFSUP1,MESFUNC8,COMSEQ_2,COMSEQ_3,SUPINF_1,RINFSUP2,SEQFUNC,SEQ_2,MESFUNC1,FINSEQ_1,COMPLSP2,MATRIX_5,NAT_D,RELSET_1,SEQ_4,CKB1,CKB4,CKB6,CKB8,CKB10,CKB19,CKB21,CKB23;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve X for non empty set;
reserve S for (SigmaField of X);
theorem
(for f being  with_the_same_dom (Functional_Sequence of X,( REAL )) holds (for F being (SetSequence of S) holds (for r being  real number holds ((for n being  natural number holds ( F . n ) = ( ( dom ( f . ( 0 ) ) ) /\ ( great_dom (( f . n ),r) ) )) implies ( union ( rng F ) ) = ( ( dom ( f . ( 0 ) ) ) /\ ( great_dom (( sup f ),r) ) )))))
proof
let f being  with_the_same_dom (Functional_Sequence of X,( REAL ));
let F being (SetSequence of S);
let r being  real number;
set E = ( dom ( f . ( 0 ) ) );
assume A1: (for n being  natural number holds ( F . n ) = ( E /\ ( great_dom (( f . n ),r) ) ));
now
let x being set;
assume A2: x in ( E /\ ( great_dom (( sup f ),r) ) );
then reconsider z = x as (Element of X);
A3: x in E by A2,XBOOLE_0:def 4;
x in ( great_dom (( sup f ),r) ) by A2,XBOOLE_0:def 4;
then A4: r < ( ( sup f ) . z ) by MESFUNC1:def 13;
(ex n being (Element of ( NAT )) st r < ( ( f # z ) . n ))
proof
assume A5: (for n being (Element of ( NAT )) holds ( ( f # z ) . n ) <= r);
(for p being  ext-real number holds (p in ( rng ( R_EAL ( f # z ) ) ) implies p <= r))
proof
let p being  ext-real number;
assume p in ( rng ( R_EAL ( f # z ) ) );
then (ex n being set st (n in ( NAT ) & ( ( R_EAL ( f # z ) ) . n ) = p)) by FUNCT_2:11;
hence thesis by A5;
end;
then r is (UpperBound of ( rng ( R_EAL ( f # z ) ) )) by XXREAL_2:def 1;
then A6: ( sup ( rng ( R_EAL ( f # z ) ) ) ) <= r by XXREAL_2:def 3;
x in ( dom ( sup f ) ) by A3,MESFUNC8:def 4;
hence contradiction by A4,A6,CKB7:1;
end;
then consider n being (Element of ( NAT )) such that A7: r < ( ( f # z ) . n );
A8: x in ( dom ( f . n ) ) by A3,MESFUNC8:def 2;
r < ( ( f . n ) . z ) by A7,SEQFUNC:def 10;
then A9: x in ( great_dom (( f . n ),r) ) by A8,MESFUNC1:def 13;
A10: ( F . n ) in ( rng F ) by FUNCT_2:4;
( F . n ) = ( E /\ ( great_dom (( f . n ),r) ) ) by A1;
then x in ( F . n ) by A3,A9,XBOOLE_0:def 4;
hence x in ( union ( rng F ) ) by A10,TARSKI:def 4;
end;
then A11: ( E /\ ( great_dom (( sup f ),r) ) ) c= ( union ( rng F ) ) by TARSKI:def 3;
now
let x being set;
assume x in ( union ( rng F ) );
then consider y being set such that A12: x in y and A13: y in ( rng (F qua (SetSequence of X)) ) by TARSKI:def 4;
reconsider z = x as (Element of X) by A12,A13;
consider n being set such that A14: n in ( dom F ) and A15: y = ( F . n ) by A13,FUNCT_1:def 3;
reconsider n as (Element of ( NAT )) by A14;
A16: ( F . n ) = ( E /\ ( great_dom (( f . n ),r) ) ) by A1;
then x in ( great_dom (( f . n ),r) ) by A12,A15,XBOOLE_0:def 4;
then A17: r < ( ( f . n ) . z ) by MESFUNC1:def 13;
( f # z ) = ( ( R_EAL f ) # z ) by CKB2:1;
then ( ( f . n ) . z ) = ( ( ( R_EAL f ) # z ) . n ) by SEQFUNC:def 10;
then A18: ( ( f . n ) . z ) <= ( sup ( rng ( ( R_EAL f ) # z ) ) ) by FUNCT_2:4,XXREAL_2:4;
A19: x in E by A12,A15,A16,XBOOLE_0:def 4;
then A20: x in ( dom ( sup f ) ) by MESFUNC8:def 4;
then ( ( sup f ) . z ) = ( sup ( ( R_EAL f ) # z ) ) by MESFUNC8:def 4;
then r < ( ( sup f ) . z ) by A17,A18,XXREAL_0:2;
then x in ( great_dom (( sup f ),r) ) by A20,MESFUNC1:def 13;
hence x in ( E /\ ( great_dom (( sup f ),r) ) ) by A19,XBOOLE_0:def 4;
end;
then ( union ( rng F ) ) c= ( E /\ ( great_dom (( sup f ),r) ) ) by TARSKI:def 3;
hence thesis by A11,XBOOLE_0:def 10;
end;
