environ
vocabularies XBOOLE_0,METRIC_1,SUBSET_1,FUNCT_1,ZFMISC_1,MCART_1,STRUCT_0,NUMBERS,ARYTM_3,CARD_1,XXREAL_0,REAL_1,METRIC_3,SQUARE_1,XREAL_0,ORDINAL1,RELAT_1,ARYTM_1,XCMPLX_0,COMPLEX1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,DOMAIN_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,FUNCT_2,BINOP_1,STRUCT_0,METRIC_1,MCART_1,XXREAL_0,SQUARE_1,CKB2,CKB6,CKB8,CKB10,CKB14,CKB15,CKB17,CKB21,CKB22,CKB23,CKB29,CKB30,CKB31;
definitions SQUARE_1,CKB2,CKB6,CKB8,CKB10,CKB14,CKB15,CKB17,CKB21,CKB22,CKB23,CKB29,CKB30,CKB31;
theorems BINOP_1,DOMAIN_1,ZFMISC_1,METRIC_1,MCART_1,XREAL_1,SQUARE_1,COMPLEX1,XXREAL_0,CKB2,CKB3,CKB4,CKB5,CKB6,CKB8,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34;
schemes BINOP_1,CKB1,CKB9,CKB16;
registrations XBOOLE_0,SUBSET_1,RELSET_1,NUMBERS,MEMBERED,STRUCT_0,METRIC_1,RELAT_1,XCMPLX_0,XREAL_0,SQUARE_1,CKB7;
constructors XXREAL_0,REAL_1,MEMBERED,METRIC_1,SQUARE_1,DOMAIN_1,COMPLEX1,CKB2,CKB6,CKB8,CKB10,CKB14,CKB15,CKB17,CKB21,CKB22,CKB23,CKB29,CKB30,CKB31;
requirements SUBSET,BOOLE,ARITHM,NUMERALS,REAL;
begin
theorem
Th17: (for a,b,c,d,e,f being  real number holds ( ( ( ( a * c ) + ( b * d ) ) + ( e * f ) ) ^2 ) <= ( ( ( ( a ^2 ) + ( b ^2 ) ) + ( e ^2 ) ) * ( ( ( c ^2 ) + ( d ^2 ) ) + ( f ^2 ) ) ))
proof
let a being  real number,b being  real number,c being  real number,d being  real number,e being  real number,f being  real number;
( ( ( ( 2 * ( a * d ) ) * ( c * b ) ) + ( ( 2 * ( a * f ) ) * ( e * c ) ) ) + ( ( 2 * ( b * f ) ) * ( e * d ) ) ) <= ( ( ( ( ( ( ( a * d ) ^2 ) + ( ( c * b ) ^2 ) ) + ( ( a * f ) ^2 ) ) + ( ( e * c ) ^2 ) ) + ( ( b * f ) ^2 ) ) + ( ( e * d ) ^2 ) ) by CKB34:1;
then ( ( ( e * f ) ^2 ) + ( ( ( ( 2 * ( a * b ) ) * ( c * d ) ) + ( ( 2 * ( a * c ) ) * ( e * f ) ) ) + ( ( 2 * ( b * d ) ) * ( e * f ) ) ) ) <= ( ( ( ( ( ( ( ( a * d ) ^2 ) + ( ( c * b ) ^2 ) ) + ( ( a * f ) ^2 ) ) + ( ( e * c ) ^2 ) ) + ( ( b * f ) ^2 ) ) + ( ( e * d ) ^2 ) ) + ( ( e * f ) ^2 ) ) by XREAL_1:6;
then ( ( ( b * d ) ^2 ) + ( ( ( e * f ) ^2 ) + ( ( ( ( 2 * ( a * b ) ) * ( c * d ) ) + ( ( 2 * ( a * c ) ) * ( e * f ) ) ) + ( ( 2 * ( b * d ) ) * ( e * f ) ) ) ) ) <= ( ( ( ( ( ( ( ( ( a * d ) ^2 ) + ( ( c * b ) ^2 ) ) + ( ( a * f ) ^2 ) ) + ( ( e * c ) ^2 ) ) + ( ( b * f ) ^2 ) ) + ( ( e * d ) ^2 ) ) + ( ( e * f ) ^2 ) ) + ( ( b * d ) ^2 ) ) by XREAL_1:6;
then ( ( ( a * c ) ^2 ) + ( ( ( b * d ) ^2 ) + ( ( ( e * f ) ^2 ) + ( ( ( ( 2 * ( a * b ) ) * ( c * d ) ) + ( ( 2 * ( a * c ) ) * ( e * f ) ) ) + ( ( 2 * ( b * d ) ) * ( e * f ) ) ) ) ) ) <= ( ( ( ( ( ( ( ( ( ( a * d ) ^2 ) + ( ( c * b ) ^2 ) ) + ( ( a * f ) ^2 ) ) + ( ( e * c ) ^2 ) ) + ( ( b * f ) ^2 ) ) + ( ( e * d ) ^2 ) ) + ( ( e * f ) ^2 ) ) + ( ( b * d ) ^2 ) ) + ( ( a * c ) ^2 ) ) by XREAL_1:6;
hence thesis;
end;
