environ
vocabularies NUMBERS,FUNCT_1,CARD_3,RELAT_1,XBOOLE_0,TARSKI,CARD_1,ZFMISC_1,SUBSET_1,PRE_TOPC,STRUCT_0,RELAT_2,FINSEQ_1,NAT_1,XXREAL_0,ARYTM_3,FINSET_1,SETFAM_1,PRALG_1,PBOOLE,FUNCOP_1,WAYBEL_3,FUNCT_4,RLVECT_2,INTEGRA1,ARYTM_1,ORDINAL4,PENCIL_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,XCMPLX_0,SETFAM_1,CARD_1,NUMBERS,NAT_1,FINSET_1,RELAT_1,DOMAIN_1,STRUCT_0,FUNCT_1,PBOOLE,FUNCT_7,WAYBEL_3,FINSEQ_1,CARD_3,PRE_TOPC,PZFMISC1,FUNCOP_1,PRALG_1,XXREAL_0,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB24,CKB25,CKB26,CKB30,CKB31,CKB32,CKB33,CKB35,CKB36,CKB37,CKB42,CKB43,CKB52;
definitions TARSKI,WAYBEL_3,PBOOLE,XBOOLE_0,PRALG_1,STRUCT_0,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB24,CKB26,CKB30,CKB31,CKB32,CKB33,CKB35,CKB37,CKB43,CKB52;
theorems TARSKI,FUNCT_1,FUNCOP_1,PBOOLE,CARD_3,PRALG_1,STRUCT_0,CARD_1,YELLOW11,ENUMSET1,FINSEQ_1,CARD_2,ZFMISC_1,NAT_1,FUNCT_7,YELLOW_6,YELLOW_8,PZFMISC1,PUA2MSS1,FINSEQ_3,RELAT_1,XBOOLE_0,XBOOLE_1,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,PARTFUN1,PRE_POLY,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB24,CKB26,CKB30,CKB31,CKB32,CKB33,CKB35,CKB37,CKB43,CKB45,CKB47,CKB48,CKB52,CKB53,CKB55;
schemes FINSEQ_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSET_1,XREAL_0,CARD_3,REALSET1,PZFMISC1,STRUCT_0,YELLOW_6,ORDINAL1,CARD_1,ZFMISC_1,PRE_POLY,FUNCOP_1,CKB21,CKB22,CKB23,CKB27,CKB28,CKB29,CKB34,CKB38,CKB39,CKB40,CKB41,CKB44,CKB46,CKB49,CKB50,CKB51,CKB54;
constructors XXREAL_0,PZFMISC1,REALSET2,PRALG_1,WAYBEL_3,POLYNOM1,PBOOLE,FUNCT_7,FUNCT_4,RELSET_1,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB26,CKB30,CKB32,CKB33,CKB36,CKB37,CKB42,CKB43,CKB52;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
registration
let I being non empty set;
let B being  Segre-like non trivial-yielding (ManySortedSet of I);
cluster ( product B ) -> non trivial;
coherence
proof
consider f being set such that A1: f in ( product B ) by XBOOLE_0:def 1;
A2: (ex g being Function st ((g = f & ( dom g ) = ( dom B )) & (for x being set holds (x in ( dom B ) implies ( g . x ) in ( B . x ))))) by A1,CARD_3:def 5;
( dom B ) = I by PARTFUN1:def 2;
then reconsider f as (ManySortedSet of I) by A2,PARTFUN1:def 2,RELAT_1:def 18;
( B . ( indx B ) ) is non trivial by CKB52:def 1;
then 2 c= ( card ( B . ( indx B ) ) ) by CKB4:1;
then consider y being set such that A3: y in ( B . ( indx B ) ) and A4: y <> ( f . ( indx B ) ) by CKB3:1;
set l = ( f +* (( indx B ),y) );
A5: (for x being set holds (x in ( dom B ) implies ( l . x ) in ( B . x )))
proof
let x being set;
assume A6: x in ( dom B );
then x in I by PARTFUN1:def 2;
then A7: x in ( dom f ) by PARTFUN1:def 2;
per cases ;
suppose x = ( indx B );

hence thesis by A3,A7,FUNCT_7:31;
end;
suppose x <> ( indx B );

then ( l . x ) = ( f . x ) by FUNCT_7:32;
hence thesis by A2,A6;
end;
end;
( dom f ) = I by PARTFUN1:def 2;
then A8: ( l . ( indx B ) ) = y by FUNCT_7:31;
( dom l ) = I by PARTFUN1:def 2
.= ( dom B ) by PARTFUN1:def 2;
then l in ( product B ) by A5,CARD_3:def 5;
then 2 c= ( card ( product B ) ) by A1,A4,A8,CKB2:1;
hence thesis by CKB4:1;
end;
end;
