environ
vocabularies DIRAF,SUBSET_1,ANALOAF,AFF_1,AFF_2,ANALMETR,CONMETR,CONAFFM,CONMETR1;
notations STRUCT_0,ANALOAF,DIRAF,AFF_1,ANALMETR,AFF_2,CONAFFM,CONMETR,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
definitions CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
theorems AFF_1,AFF_2,ANALMETR,CONAFFM,CONMETR,TRANSLAC,DIRAF,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16;
registrations STRUCT_0,ANALMETR;
constructors AFF_1,AFF_2,CONAFFM,CONMETR,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
requirements SUBSET;
begin
reserve X for AffinPlane;
theorem
(X is  satisfying_PPAP iff X is  satisfying_indirect_Scherungssatz)
proof
A1: (X is  satisfying_PPAP implies X is  satisfying_indirect_Scherungssatz)
proof
assume A2: X is  satisfying_PPAP;
then X is  satisfying_pap by AFF_2:10;
then A3: X is  satisfying_minor_indirect_Scherungssatz by CKB15:1;
X is  Pappian by A2,AFF_2:10;
then X is  satisfying_major_indirect_Scherungssatz by CKB16:1;
hence thesis by A3,CKB7:1;
end;
(X is  satisfying_indirect_Scherungssatz implies X is  satisfying_PPAP)
proof
assume A4: X is  satisfying_indirect_Scherungssatz;
then X is  satisfying_major_indirect_Scherungssatz by CKB7:1;
then A5: X is  Pappian by CKB16:1;
X is  satisfying_minor_indirect_Scherungssatz by A4,CKB7:1;
then X is  satisfying_pap by CKB15:1;
hence thesis by A5,AFF_2:10;
end;
hence thesis by A1;
end;
