environ
vocabularies NUMBERS,ORDINAL1,REAL_1,XBOOLE_0,METRIC_1,PROB_1,XXREAL_2,FUNCT_1,RELAT_1,STRUCT_0,PRE_TOPC,SUBSET_1,FUNCOP_1,XXREAL_0,MEASURE5,SEQ_1,CARD_1,ARYTM_1,ARYTM_3,VALUED_0,TARSKI,ORDINAL2,NAT_1,BHSP_3,COMPLEX1,RELAT_2,RCOMP_1,PCOMPS_1,ZFMISC_1,XREAL_0,REWRITE1,SETFAM_1,SEQ_2,METRIC_6,FRECHET,FINSET_1,VALUED_1,CARD_3,TOPGEN_1,WELLORD1,ORDERS_2,PARTFUN1,WELLFND1,TBSP_1,WAYBEL23,RLVECT_3,COMPL_SP;
notations METRIC_6,RELAT_2,BINOP_1,TOPMETR,CARD_1,FUNCOP_1,CANTOR_1,WELLORD1,COMPLEX1,FINSET_1,SEQ_2,TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,ZFMISC_1,XXREAL_0,XREAL_0,REAL_1,SETFAM_1,DOMAIN_1,TOPS_2,FUNCT_1,VALUED_1,NAT_1,VALUED_0,STRUCT_0,PRE_TOPC,COMPTS_1,RELAT_1,SEQ_1,TBSP_1,RELSET_1,PARTFUN1,FUNCT_2,METRIC_1,PCOMPS_1,CARD_3,PROB_1,FRECHET,KURATO_0,KURATO_2,WELLFND1,WAYBEL23,ORDERS_2,TOPGEN_1,CKB1,CKB3,CKB9,CKB10,CKB16,CKB17,CKB23,CKB24;
definitions TARSKI,TOPS_2,SUBSET_1,STRUCT_0,TBSP_1,PCOMPS_1,COMPTS_1,METRIC_1,CKB1,CKB3,CKB9,CKB10,CKB16,CKB17,CKB23,CKB24;
theorems KURATO_2,NAT_1,FUNCT_2,PCOMPS_1,PCOMPS_2,NAGATA_1,SUBSET_1,METRIC_6,FUNCT_1,METRIC_1,XREAL_0,XCMPLX_1,ABSVALUE,TOPMETR,XBOOLE_1,TARSKI,SETFAM_1,XBOOLE_0,TOPS_1,TOPS_2,PRE_TOPC,CARD_4,ZFMISC_1,BINOP_1,SEQ_2,SEQ_4,SEQ_1,SEQM_3,PARTFUN1,WELLORD1,WELLORD2,TBSP_1,RELAT_1,RELAT_2,YELLOW_9,XREAL_1,XXREAL_0,ORDINAL1,FRECHET2,FRECHET,COMPTS_1,STIRL2_1,CARD_1,HAUSDORF,TOPMETR3,CARD_3,TOPGEN_4,DICKSON,RELSET_2,TOPGEN_1,WELLFND1,WAYBEL23,UNIFORM1,CARD_2,TOPREAL6,FINSET_1,PROB_1,FUNCOP_1,KURATO_0,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB15,CKB16,CKB17,CKB18,CKB23,CKB24,CKB27,CKB28;
schemes FUNCT_1,WELLFND1,TREES_2,FUNCT_2,NAT_1,FRAENKEL,BINOP_1,SEQ_1;
registrations REALSET1,TOPMETR,PRE_TOPC,PCOMPS_1,NAT_1,TBSP_1,XREAL_0,RELSET_1,SUBSET_1,STRUCT_0,TOPS_1,METRIC_1,HAUSDORF,MEMBERED,XXREAL_0,YELLOW13,CARD_1,XBOOLE_0,VALUED_1,FUNCT_2,NUMBERS,FINSET_1,SEQ_4,WELLFND1,ZFMISC_1,KURATO_0,CKB2,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB22,CKB25,CKB26;
constructors REAL_1,NAT_1,TBSP_1,YELLOW_6,FRECHET,FRECHET2,KURATO_2,COMPLEX1,SEQ_2,TOPS_2,WELLORD1,CARD_3,CANTOR_1,URYSOHN3,METRIC_6,REALSET1,WELLFND1,TOPGEN_4,WAYBEL23,TOPGEN_1,SEQ_1,COMPTS_1,FINSUB_1,TOPS_1,BINOP_2,RVSUM_1,KURATO_0,CKB1,CKB3,CKB9,CKB10,CKB16,CKB17,CKB23,CKB24;
requirements REAL,SUBSET,BOOLE,NUMERALS,ARITHM;
begin
reserve i for  natural number;
reserve m for  natural number;
reserve x for set;
reserve y for set;
reserve r for Real;
theorem
Th9: (for M being non  empty MetrSpace holds (for C being (sequence of M) holds (ex S being  non-empty  closed (SetSequence of M) st ((S is  non-ascending & (C is  Cauchy implies (S is  bounded & ( lim ( diameter S ) ) = ( 0 )))) & (for i holds (ex U being (Subset of ( TopSpaceMetr M )) st (U = { ( C . j ) where j is (Element of ( NAT )): j >= i } & ( S . i ) = ( Cl U ))))))))
proof
let M being  Reflexive  symmetric  triangle non  empty MetrSpace;
set T = ( TopSpaceMetr M );
let C being (sequence of M);
defpred P[ set,set ]
 means
(for i holds (i = $1 implies (ex S being (Subset of T) st (S = { ( C . j ) where j is (Element of ( NAT )): j >= i } & $2 = ( Cl S )))));
A1: (for x holds (x in ( NAT ) implies (ex y st (y in ( bool (the carrier of M) ) & P[ x,y ]))))
proof
let x;
assume x in ( NAT );
then reconsider x9 = x as (Element of ( NAT ));
set S = { ( C . j ) where j is (Element of ( NAT )): j >= x9 };
S c= (the carrier of T)
proof
let y;
assume y in S;
then (ex j being (Element of ( NAT )) st (( C . j ) = y & j >= x9));
hence thesis;
end;
then reconsider S as (Subset of T);
take ( Cl S );
thus thesis;
end;
consider S being (SetSequence of M) such that A2: (for x holds (x in ( NAT ) implies P[ x,( S . x ) ])) from FUNCT_2:sch 1(A1);
A3:now
let x;
assume x in ( dom S );
then reconsider i = x as (Element of ( NAT ));
consider U being (Subset of T) such that A4: U = { ( C . j ) where j is (Element of ( NAT )): j >= i } and A5: ( S . i ) = ( Cl U ) by A2;
A6: U c= ( S . i ) by A5,PRE_TOPC:18;
( C . i ) in U by A4;
hence ( S . x ) is non  empty by A6;
end;
now
let i;
i in ( NAT ) by ORDINAL1:def 12;
then (ex U being (Subset of T) st (U = { ( C . j ) where j is (Element of ( NAT )): j >= i } & ( S . i ) = ( Cl U ))) by A2;
hence ( S . i ) is  closed by CKB15:1;
end;
then reconsider S as  non-empty  closed (SetSequence of M) by A3,CKB24:def 1,FUNCT_1:def 9;
take S;
now
let i being (Element of ( NAT ));
consider U being (Subset of T) such that A7: U = { ( C . j ) where j is (Element of ( NAT )): j >= i } and A8: ( S . i ) = ( Cl U ) by A2;
consider U1 being (Subset of T) such that A9: U1 = { ( C . j ) where j is (Element of ( NAT )): j >= ( i + 1 ) } and A10: ( S . ( i + 1 ) ) = ( Cl U1 ) by A2;
U1 c= U
proof
let x;
assume x in U1;
then consider j being (Element of ( NAT )) such that A11: x = ( C . j ) and A12: j >= ( i + 1 ) by A9;
j >= i by A12,NAT_1:13;
hence thesis by A7,A11;
end;
hence ( S . ( i + 1 ) ) c= ( S . i ) by A8,A10,PRE_TOPC:19;
end;
hence A13: S is  non-ascending by KURATO_0:def 3;
thus (C is  Cauchy implies (S is  bounded & ( lim ( diameter S ) ) = ( 0 )))
proof
assume A14: C is  Cauchy;
A15:now
let i;
i in ( NAT ) by ORDINAL1:def 12;
then consider U being (Subset of T) such that A16: U = { ( C . j ) where j is (Element of ( NAT )): j >= i } and A17: ( S . i ) = ( Cl U ) by A2;
reconsider U9 = U as (Subset of M);
U c= ( rng C )
proof
let x;
assume x in U;
then A18: (ex j being (Element of ( NAT )) st (x = ( C . j ) & j >= i)) by A16;
( dom C ) = ( NAT ) by FUNCT_2:def 1;
hence thesis by A18,FUNCT_1:def 3;
end;
then U9 is  bounded by A14,TBSP_1:14,TBSP_1:26;
hence ( S . i ) is  bounded by A17,CKB28:1;
end;
then reconsider S9 = S as  non-empty  bounded  closed (SetSequence of M) by CKB1:def 1;
set d = ( diameter S9 );
A19: (for r being  real number holds (( 0 ) < r implies (ex n being (Element of ( NAT )) st (for m being (Element of ( NAT )) holds (n <= m implies ( abs ( ( d . m ) - ( 0 ) ) ) < r)))))
proof
let r being  real number;
assume that
A20: ( 0 ) < r;
reconsider R = r as Real by XREAL_0:def 1;
set R2 = ( R / 2 );
R2 > ( 0 ) by A20,XREAL_1:139;
then consider p being (Element of ( NAT )) such that A21: (for n,m being (Element of ( NAT )) holds ((p <= n & p <= m) implies ( dist (( C . n ),( C . m )) ) < R2)) by A14,TBSP_1:def 4;
take p;
let m being (Element of ( NAT ));
assume that
A22: p <= m;
consider U being (Subset of T) such that A23: U = { ( C . j ) where j is (Element of ( NAT )): j >= m } and A24: ( S . m ) = ( Cl U ) by A2;
reconsider U9 = U as (Subset of M);
A25:now
let x being (Point of M);
let y being (Point of M);
assume that
A26: x in U9
and
A27: y in U9;
consider j being (Element of ( NAT )) such that A28: y = ( C . j ) and A29: j >= m by A23,A27;
A30: j >= p by A22,A29,XXREAL_0:2;
consider i being (Element of ( NAT )) such that A31: x = ( C . i ) and A32: i >= m by A23,A26;
i >= p by A22,A32,XXREAL_0:2;
hence ( dist (x,y) ) <= R2 by A21,A31,A28,A30;
end;
A33: U c= ( rng C )
proof
let x;
assume x in U;
then A34: (ex j being (Element of ( NAT )) st (x = ( C . j ) & j >= m)) by A23;
( dom C ) = ( NAT ) by FUNCT_2:def 1;
hence thesis by A34,FUNCT_1:def 3;
end;
then A35: U9 is  bounded by A14,TBSP_1:14,TBSP_1:26;
then A36: ( diameter U9 ) = ( diameter ( S . m ) ) by A24,CKB28:1;
( C . m ) in U by A23;
then A37: ( diameter U9 ) <= R2 by A35,A25,TBSP_1:def 8;
( rng C ) is  bounded by A14,TBSP_1:26;
then ( diameter ( S . m ) ) >= ( 0 ) by A33,A36,TBSP_1:14,TBSP_1:21;
then A38: ( abs ( diameter ( S . m ) ) ) <= R2 by A37,A36,ABSVALUE:def 1;
R2 < R by A20,XREAL_1:216;
then ( abs ( diameter ( S . m ) ) ) < R by A38,XXREAL_0:2;
hence thesis by CKB3:def 1;
end;
thus S is  bounded by A15,CKB1:def 1;
A39: d is  bounded_below by CKB4:1;
d is  non-increasing by A13,CKB5:1;
hence thesis by A39,A19,SEQ_2:def 7;
end;

let i;
i in ( NAT ) by ORDINAL1:def 12;
hence thesis by A2;
end;
