environ
vocabularies NUMBERS,ORDINAL1,REAL_1,XBOOLE_0,METRIC_1,PROB_1,XXREAL_2,FUNCT_1,RELAT_1,STRUCT_0,PRE_TOPC,SUBSET_1,FUNCOP_1,XXREAL_0,MEASURE5,SEQ_1,CARD_1,ARYTM_1,ARYTM_3,VALUED_0,TARSKI,ORDINAL2,NAT_1,BHSP_3,COMPLEX1,RELAT_2,RCOMP_1,PCOMPS_1,ZFMISC_1,XREAL_0,REWRITE1,SETFAM_1,SEQ_2,METRIC_6,FRECHET,FINSET_1,VALUED_1,CARD_3,TOPGEN_1,WELLORD1,ORDERS_2,PARTFUN1,WELLFND1,TBSP_1,WAYBEL23,RLVECT_3,COMPL_SP;
notations METRIC_6,RELAT_2,BINOP_1,TOPMETR,CARD_1,FUNCOP_1,CANTOR_1,WELLORD1,COMPLEX1,FINSET_1,SEQ_2,TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,ZFMISC_1,XXREAL_0,XREAL_0,REAL_1,SETFAM_1,DOMAIN_1,TOPS_2,FUNCT_1,VALUED_1,NAT_1,VALUED_0,STRUCT_0,PRE_TOPC,COMPTS_1,RELAT_1,SEQ_1,TBSP_1,RELSET_1,PARTFUN1,FUNCT_2,METRIC_1,PCOMPS_1,CARD_3,PROB_1,FRECHET,KURATO_0,KURATO_2,WELLFND1,WAYBEL23,ORDERS_2,TOPGEN_1,CKB1,CKB3,CKB9,CKB10,CKB16,CKB17,CKB23,CKB24,CKB40;
definitions TARSKI,TOPS_2,SUBSET_1,STRUCT_0,TBSP_1,PCOMPS_1,COMPTS_1,METRIC_1,CKB1,CKB3,CKB9,CKB10,CKB16,CKB17,CKB23,CKB24,CKB40;
theorems KURATO_2,NAT_1,FUNCT_2,PCOMPS_1,PCOMPS_2,NAGATA_1,SUBSET_1,METRIC_6,FUNCT_1,METRIC_1,XREAL_0,XCMPLX_1,ABSVALUE,TOPMETR,XBOOLE_1,TARSKI,SETFAM_1,XBOOLE_0,TOPS_1,TOPS_2,PRE_TOPC,CARD_4,ZFMISC_1,BINOP_1,SEQ_2,SEQ_4,SEQ_1,SEQM_3,PARTFUN1,WELLORD1,WELLORD2,TBSP_1,RELAT_1,RELAT_2,YELLOW_9,XREAL_1,XXREAL_0,ORDINAL1,FRECHET2,FRECHET,COMPTS_1,STIRL2_1,CARD_1,HAUSDORF,TOPMETR3,CARD_3,TOPGEN_4,DICKSON,RELSET_2,TOPGEN_1,WELLFND1,WAYBEL23,UNIFORM1,CARD_2,TOPREAL6,FINSET_1,PROB_1,FUNCOP_1,KURATO_0,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB15,CKB16,CKB17,CKB18,CKB23,CKB24,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB57,CKB58,CKB59,CKB60;
schemes FUNCT_1,WELLFND1,TREES_2,FUNCT_2,NAT_1,FRAENKEL,BINOP_1,SEQ_1,CKB56;
registrations REALSET1,TOPMETR,PRE_TOPC,PCOMPS_1,NAT_1,TBSP_1,XREAL_0,RELSET_1,SUBSET_1,STRUCT_0,TOPS_1,METRIC_1,HAUSDORF,MEMBERED,XXREAL_0,YELLOW13,CARD_1,XBOOLE_0,VALUED_1,FUNCT_2,NUMBERS,FINSET_1,SEQ_4,WELLFND1,ZFMISC_1,KURATO_0,CKB2,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB22,CKB25,CKB26;
constructors REAL_1,NAT_1,TBSP_1,YELLOW_6,FRECHET,FRECHET2,KURATO_2,COMPLEX1,SEQ_2,TOPS_2,WELLORD1,CARD_3,CANTOR_1,URYSOHN3,METRIC_6,REALSET1,WELLFND1,TOPGEN_4,WAYBEL23,TOPGEN_1,SEQ_1,COMPTS_1,FINSUB_1,TOPS_1,BINOP_2,RVSUM_1,KURATO_0,CKB1,CKB3,CKB9,CKB10,CKB16,CKB17,CKB23,CKB24,CKB40;
requirements REAL,SUBSET,BOOLE,NUMERALS,ARITHM;
begin
reserve i for  natural number;
reserve x for set;
reserve y for set;
theorem
Th33: (for M being non empty MetrSpace holds (M is  totally_bounded implies ( TopSpaceMetr M ) is  second-countable))
proof
let M being non empty MetrSpace;
assume that
A1: M is  totally_bounded;
set T = ( TopSpaceMetr M );
defpred F[ set,set ]
 means
(for i holds (i = $1 implies (for G being (Subset-Family of T) holds ($2 = G implies ((G is  finite & (the carrier of M) = ( union G )) & (for C being (Subset of M) holds (C in G implies (ex w being (Point of M) st C = ( Ball (w,( 1 / ( i + 1 ) )) )))))))));
A2: (for x holds (x in ( NAT ) implies (ex y st (y in ( bool ( bool (the carrier of T) ) ) & F[ x,y ]))))
proof
let x;
assume x in ( NAT );
then reconsider i = x as (Element of ( NAT ));
( 1 / ( i + 1 ) ) > ( 0 ) by XREAL_1:139;
then consider G being (Subset-Family of T) such that A3: G is  finite and A4: (the carrier of M) = ( union G ) and A5: (for C being (Subset of M) holds (C in G implies (ex w being (Point of M) st C = ( Ball (w,( 1 / ( i + 1 ) )) )))) by A1,TBSP_1:def 1;
take G;
thus thesis by A3,A4,A5;
end;
consider f being (Function of ( NAT ),( bool ( bool (the carrier of T) ) )) such that A6: (for x holds (x in ( NAT ) implies F[ x,( f . x ) ])) from FUNCT_2:sch 1(A2);
set U = ( Union f );
A7: ( dom f ) = ( NAT ) by FUNCT_2:def 1;
A8: (for A being (Subset of T) holds (A is  open implies (for p being (Point of T) holds (p in A implies (ex a being (Subset of T) st ((a in U & p in a) & a c= A))))))
proof
let A being (Subset of T);
assume that
A9: A is  open;
let p being (Point of T);
assume that
A10: p in A;
reconsider p9 = p as (Point of M);
consider r being  real number such that A11: r > ( 0 ) and A12: ( Ball (p9,r) ) c= A by A9,A10,TOPMETR:15;
reconsider r as Real by XREAL_0:def 1;
consider n being (Element of ( NAT )) such that A13: n > ( 0 ) and A14: ( 1 / n ) < ( r / 2 ) by A11,UNIFORM1:1,XREAL_1:215;
A15: ( ( 1 / n ) + ( 1 / n ) ) < ( ( r / 2 ) + ( r / 2 ) ) by A14,XREAL_1:8;
reconsider n1 = ( n - 1 ) as (Element of ( NAT )) by A13,NAT_1:20;
reconsider fn = ( f . n1 ) as (Subset-Family of T);
(the carrier of M) = ( union fn ) by A6;
then consider x being set such that A16: p in x and A17: x in fn by TARSKI:def 4;
reconsider x as (Subset of M) by A17;
consider w being (Point of M) such that A18: x = ( Ball (w,( 1 / ( n1 + 1 ) )) ) by A6,A17;
reconsider B = ( Ball (w,( 1 / n )) ) as (Subset of T);
take B;
( f . n1 ) in ( rng f ) by A7,FUNCT_1:def 3;
then B in ( union ( rng f ) ) by A17,A18,TARSKI:def 4;
hence (B in U & p in B) by A16,A18,CARD_3:def 4;
let q being set;
assume that
A19: q in B;
reconsider q9 = q as (Point of M) by A19;
A20: ( dist (q9,w) ) < ( 1 / n ) by A19,METRIC_1:11;
( dist (w,p9) ) < ( 1 / ( n1 + 1 ) ) by A16,A18,METRIC_1:11;
then A21: ( ( dist (q9,w) ) + ( dist (w,p9) ) ) < ( ( 1 / n ) + ( 1 / n ) ) by A20,XREAL_1:8;
( dist (q9,p9) ) <= ( ( dist (q9,w) ) + ( dist (w,p9) ) ) by METRIC_1:4;
then ( dist (q9,p9) ) < ( ( 1 / n ) + ( 1 / n ) ) by A21,XXREAL_0:2;
then ( dist (q9,p9) ) < ( ( r / 2 ) + ( r / 2 ) ) by A15,XXREAL_0:2;
then q in ( Ball (p9,r) ) by METRIC_1:11;
hence thesis by A12;
end;
set CB = { ( card B ) where B is (Basis of T): (not contradiction) };
U c= (the topology of T)
proof
let x;
assume x in U;
then x in ( union ( rng f ) ) by CARD_3:def 4;
then consider y such that A22: x in y and A23: y in ( rng f ) by TARSKI:def 4;
reconsider X = x as (Subset of T) by A22,A23;
consider z being set such that A24: z in ( dom f ) and A25: ( f . z ) = y by A23,FUNCT_1:def 3;
reconsider z as (Element of ( NAT )) by A24;
(ex w being (Point of M) st X = ( Ball (w,( 1 / ( z + 1 ) )) )) by A6,A22,A25;
hence thesis by PCOMPS_1:29;
end;
then U is (Basis of T) by A8,YELLOW_9:32;
then A26: ( card U ) in CB;
now
let x;
assume x in ( dom f );
then reconsider i = x as (Element of ( NAT ));
reconsider fx = ( f . i ) as (Subset-Family of T);
fx is  finite by A6;
hence ( f . x ) is  countable by CARD_4:1;
end;
then U is  countable by A7,CARD_4:2,CARD_4:11;
then A27: ( card U ) c= ( omega ) by CARD_3:def 14;
( weight T ) = ( meet CB ) by WAYBEL23:def 5;
then ( weight T ) c= ( card U ) by A26,SETFAM_1:3;
then ( weight T ) c= ( omega ) by A27,XBOOLE_1:1;
hence thesis by WAYBEL23:def 6;
end;
