environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,NAT_1,REAL_1,FINSEQ_1,RELAT_1,FUNCT_1,TARSKI,XREAL_0,ORDINAL1,FINSEQ_2,CARD_1,XXREAL_0,SEQ_1,ARYTM_3,CARD_3,FUNCOP_1,MATRIX_1,TREES_1,ZFMISC_1,INCSP_1,MATRIXC1,QC_LANG1,ORDINAL4,PRE_POLY,BINOP_2,FINSEQ_3,RVSUM_1,STRUCT_0,VECTSP_1,SUPINF_2,FVSUM_1,MATRIXR1,MATRPROB;
notations TARSKI,SUBSET_1,XBOOLE_0,XXREAL_0,XREAL_0,REAL_1,NAT_1,ORDINAL1,NUMBERS,RELAT_1,FUNCT_1,SEQ_1,ZFMISC_1,FUNCOP_1,BINOP_1,BINOP_2,FUNCT_2,RVSUM_1,FINSEQ_1,FINSEQ_2,FINSEQOP,NEWTON,STRUCT_0,MATRLIN,MATRIXR1,MATRIX_3,MATRIX_1,GROUP_1,FVSUM_1,RLVECT_1,VECTSP_1,CKB1,CKB2,CKB25,CKB26,CKB28,CKB31;
definitions TARSKI,FINSEQ_2,RVSUM_1,CKB25,CKB28,CKB31;
theorems FUNCT_1,SEQ_1,NAT_1,TARSKI,ZFMISC_1,MATRIX_3,MATRIX_2,XREAL_1,GOBOARD1,BINOP_2,FVSUM_1,VECTSP_1,RLVECT_1,MATRLIN,XBOOLE_0,FINSEQ_1,PROB_3,MATRIX_1,GOBRD13,FINSEQ_2,FUNCOP_1,RFINSEQ,FINSEQ_3,RVSUM_1,MATRIXR1,ORDINAL1,XREAL_0,MATRIXC1,XXREAL_0,STRUCT_0,RELAT_1,PRE_POLY,CARD_1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34;
schemes CLASSES1,FINSEQ_2,PARTFUN1,NAT_1,MATRIX_1;
registrations XBOOLE_0,ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,NAT_1,MEMBERED,FINSEQ_1,FINSEQ_2,STRUCT_0,VECTSP_1,MATRIX_1,MATRLIN,VALUED_0,CARD_1;
constructors XXREAL_0,REAL_1,NAT_1,BINOP_2,NEWTON,FVSUM_1,MATRIX_3,MATRLIN,MATRIXR1,SEQ_1,BINOP_1,RVSUM_1,RELSET_1,CKB1,CKB2,CKB25,CKB28,CKB31;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
theorem
Th26: (for M1,M2 being (Matrix of ( REAL )) holds ( ( Sum M1 ) + ( Sum M2 ) ) = ( Sum ( M1 ^^ M2 ) ))
proof
let M1 being (Matrix of ( REAL )),M2 being (Matrix of ( REAL ));
reconsider M = ( min (( len M1 ),( len M2 )) ) as (Element of ( NAT )) by FINSEQ_2:1;
A1: ( Seg M ) = ( ( Seg ( len M1 ) ) /\ ( Seg ( len M2 ) ) ) by FINSEQ_2:2
.= ( ( Seg ( len M1 ) ) /\ ( dom M2 ) ) by FINSEQ_1:def 3
.= ( ( dom M1 ) /\ ( dom M2 ) ) by FINSEQ_1:def 3
.= ( dom ( M1 ^^ M2 ) ) by PRE_POLY:def 4
.= ( Seg ( len ( M1 ^^ M2 ) ) ) by FINSEQ_1:def 3;
A2: ( len ( ( Sum M1 ) + ( Sum M2 ) ) ) = ( len ( ( addreal ) .: (( Sum M1 ),( Sum M2 )) ) )
.= ( min (( len ( Sum M1 ) ),( len ( Sum M2 ) )) ) by FINSEQ_2:71
.= ( min (( len M1 ),( len ( Sum M2 ) )) ) by CKB25:def 1
.= ( min (( len M1 ),( len M2 )) ) by CKB25:def 1
.= ( len ( M1 ^^ M2 ) ) by A1,FINSEQ_1:6
.= ( len ( Sum ( M1 ^^ M2 ) ) ) by CKB25:def 1;
A3: ( dom ( ( Sum M1 ) + ( Sum M2 ) ) ) = ( Seg ( len ( ( Sum M1 ) + ( Sum M2 ) ) ) ) by FINSEQ_1:def 3;
now
let i being Nat;
assume A4: i in ( dom ( ( Sum M1 ) + ( Sum M2 ) ) );
then A5: i in ( dom ( ( addreal ) .: (( Sum M1 ),( Sum M2 )) ) );
i in ( Seg ( len ( M1 ^^ M2 ) ) ) by A2,A3,A4,CKB25:def 1;
then A6: i in ( dom ( M1 ^^ M2 ) ) by FINSEQ_1:def 3;
then A7: i in ( ( dom M1 ) /\ ( dom M2 ) ) by PRE_POLY:def 4;
then i in ( dom M1 ) by XBOOLE_0:def 4;
then i in ( Seg ( len M1 ) ) by FINSEQ_1:def 3;
then i in ( Seg ( len ( Sum M1 ) ) ) by CKB25:def 1;
then A8: i in ( dom ( Sum M1 ) ) by FINSEQ_1:def 3;
i in ( dom M2 ) by A7,XBOOLE_0:def 4;
then i in ( Seg ( len M2 ) ) by FINSEQ_1:def 3;
then i in ( Seg ( len ( Sum M2 ) ) ) by CKB25:def 1;
then A9: i in ( dom ( Sum M2 ) ) by FINSEQ_1:def 3;
A10: i in ( dom ( Sum ( M1 ^^ M2 ) ) ) by A2,A3,A4,FINSEQ_1:def 3;
A11: ( ( M1 . i ) ^ ( M2 . i ) ) = ( ( M1 ^^ M2 ) . i ) by A6,PRE_POLY:def 4;
thus ( ( ( Sum M1 ) + ( Sum M2 ) ) . i ) = ( ( ( addreal ) .: (( Sum M1 ),( Sum M2 )) ) . i )
.= ( ( addreal ) . (( ( Sum M1 ) . i ),( ( Sum M2 ) . i )) ) by A5,FUNCOP_1:22
.= ( ( ( Sum M1 ) . i ) + ( ( Sum M2 ) . i ) ) by BINOP_2:def 9
.= ( ( Sum ( M1 . i ) ) + ( ( Sum M2 ) . i ) ) by A8,CKB25:def 1
.= ( ( Sum ( M1 . i ) ) + ( Sum ( M2 . i ) ) ) by A9,CKB25:def 1
.= ( Sum ( ( M1 ^^ M2 ) . i ) ) by A11,RVSUM_1:75
.= ( ( Sum ( M1 ^^ M2 ) ) . i ) by A10,CKB25:def 1;
end;
hence thesis by A2,FINSEQ_2:9;
end;
