environ
vocabularies CARD_1,ORDINAL1,FUNCT_1,CLASSES1,TARSKI,ZFMISC_1,XBOOLE_0,RELAT_1,CARD_3,FUNCT_2,SUBSET_1,SETFAM_1,FINSET_1,ORDINAL2,CLASSES2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,FINSET_1,SETFAM_1,RELAT_1,FUNCT_1,FUNCT_2,ORDINAL1,ORDINAL2,CLASSES1,CARD_3;
definitions TARSKI,ORDINAL1,CLASSES1,XBOOLE_0;
theorems TARSKI,ZFMISC_1,SETFAM_1,ORDINAL1,WELLORD2,ORDINAL2,ORDINAL3,FUNCT_1,FUNCT_2,CARD_1,CLASSES1,CARD_2,FRAENKEL,CARD_3,RELAT_1,XBOOLE_0,XBOOLE_1,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38;
schemes FUNCT_1,PARTFUN1,CARD_3,ORDINAL1,ORDINAL2,XBOOLE_0,CARD_2;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,ORDINAL1,CARD_1,CLASSES1,CKB2,CKB3;
constructors SETFAM_1,WELLORD2,ORDINAL2,CLASSES1,CARD_3,NUMBERS,FUNCT_2;
requirements SUBSET,BOOLE,NUMERALS;
begin
reserve A for Ordinal;
reserve B for Ordinal;
reserve x for set;
reserve y for set;
reserve X for set;
reserve Y for set;
reserve Z for set;
reserve W for set;
reserve f for Function;
reserve f for Function;
reserve g for Function;
deffunc f(set) = ( the_rank_of $1 );
deffunc g(set) = ( card ( bool $1 ) );
theorem
Th37: ((W is  Tarski & X c= ( Rank ( card W ) )) implies (X,( Rank ( card W ) ) are_equipotent  or X in ( Rank ( card W ) )))
proof
assume that
A1: W is  Tarski
and
A2: X c= ( Rank ( card W ) )
and
A3: (not X,( Rank ( card W ) ) are_equipotent );
defpred P[ set ]
 means
(ex Y st (Y in X & $1 = ( the_rank_of Y )));
consider LL being set such that A4: (x in LL iff (x in ( On W ) & P[ x ])) from XBOOLE_0:sch 1;
consider ff being Cardinal-Function such that A5: (( dom ff ) = LL & (for x holds (x in LL implies ( ff . x ) = g(x)))) from CARD_3:sch 1;
A6: LL c= ( On W )
proof
let x;
thus thesis by A4;
end;
A7: ( product ff ) c= ( Funcs (LL,W) )
proof
let x;
assume x in ( product ff );
then consider g such that A8: x = g and A9: ( dom g ) = ( dom ff ) and A10: (for x holds (x in ( dom ff ) implies ( g . x ) in ( ff . x ))) by CARD_3:def 5;
( rng g ) c= W
proof
let y;
assume y in ( rng g );
then consider x such that A11: x in ( dom g ) and A12: y = ( g . x ) by FUNCT_1:def 3;
A13: ( ff . x ) = ( card ( bool x ) ) by A5,A9,A11;
x in W by A6,A5,A9,A11,ORDINAL1:def 9;
then ( bool x ) in W by A1,CLASSES1:def 2;
then ( card ( bool x ) ) in W by A1,CKB14:1;
then A14: ( card ( bool x ) ) c= W by A1,CKB8:1;
y in ( ff . x ) by A9,A10,A11,A12;
hence thesis by A13,A14;
end;
hence thesis by A5,A8,A9,FUNCT_2:def 2;
end;
A15: ( card W ) = ( card ( Rank ( card W ) ) ) by A1,CKB37:1;
then A16: ( card X ) <> ( card W ) by A3,CARD_1:5;
( On W ) c= W by ORDINAL2:7;
then A17: LL c= W by A6,XBOOLE_1:1;
now
let Z;
assume Z in ( union LL );
then consider Y such that A18: Z in Y and A19: Y in LL by TARSKI:def 4;
Y in ( On W ) by A4,A19;
then reconsider Y as Ordinal by ORDINAL1:def 9;
A20: Y c= ( union LL ) by A19,ZFMISC_1:74;
A21: Z in Y by A18;
hence Z is Ordinal;
reconsider A = Z as Ordinal by A21;
A c= Y by A18,ORDINAL1:def 2;
hence Z c= ( union LL ) by A20,XBOOLE_1:1;
end;
then reconsider ULL = ( union LL ) as Ordinal by ORDINAL1:19;
A22: ( dom ( Card ( id LL ) ) ) = ( dom ( id LL ) ) by CARD_3:def 2;
A23: ( dom ( id LL ) ) = LL by RELAT_1:45;
now
let x;
assume A24: x in ( dom ( Card ( id LL ) ) );
then A25: ( ( Card ( id LL ) ) . x ) = ( card ( ( id LL ) . x ) ) by A22,CARD_3:def 2;
A26: ( ( id LL ) . x ) = x by A23,A22,A24,FUNCT_1:18;
( ff . x ) = ( card ( bool x ) ) by A5,A23,A22,A24;
hence ( ( Card ( id LL ) ) . x ) in ( ff . x ) by A26,A25,CARD_1:14;
end;
then A27: ( Sum ( Card ( id LL ) ) ) in ( Product ff ) by A5,A23,A22,CARD_3:41;
consider f such that A28: (( dom f ) = X & (for x holds (x in X implies ( f . x ) = f(x)))) from FUNCT_1:sch 3;
LL c= ( rng f )
proof
let x;
assume x in LL;
then consider Y such that A29: Y in X and A30: x = ( the_rank_of Y ) by A4;
( f . Y ) = x by A28,A29,A30;
hence thesis by A28,A29,FUNCT_1:def 3;
end;
then A31: ( card LL ) c= ( card X ) by A28,CARD_1:12;
A32: ( card ( product ff ) ) = ( Product ff ) by CARD_3:def 8;
( card X ) c= ( card W ) by A2,A15,CARD_1:11;
then ( card X ) in ( card W ) by A16,CARD_1:3;
then ( card LL ) <> ( card W ) by A31,ORDINAL1:12;
then (not LL,W are_equipotent ) by CARD_1:5;
then LL in W by A1,A17,CLASSES1:def 2;
then ( Funcs (LL,W) ) c= W by A1,A17,CKB25:1;
then ( product ff ) c= W by A7,XBOOLE_1:1;
then A33: ( Product ff ) c= ( card W ) by A32,CARD_1:11;
A34: ( card W ) is  limit_ordinal by A1,CKB22:1;
A35: ( card W ) = ( On W ) by A1,CKB12:1;
X c= ( Rank ( succ ULL ) )
proof
let x;
defpred P[ Ordinal ]
 means
($1 in ( card W ) & x c= ( Rank $1 ));
assume A36: x in X;
then A37: ( f . x ) = ( the_rank_of x ) by A28;
consider A such that A38: A in ( card W ) and A39: x in ( Rank A ) by A2,A34,A36,CLASSES1:29,CLASSES1:31;
P[ A ] by A38,A39,ORDINAL1:def 2;
then A40: (ex A st P[ A ]);
consider A such that A41: P[ A ] and A42: (for B holds (P[ B ] implies A c= B)) from ORDINAL1:sch 1(A40);
now
let B;
assume x c= ( Rank B );
then ((A c= ( card W ) & ( card W ) c= B) or A c= B) by A41,A42,ORDINAL1:16;
hence A c= B by XBOOLE_1:1;
end;
then A = ( the_rank_of x ) by A41,CLASSES1:def 8;
then ( f . x ) in LL by A4,A35,A36,A37,A41;
then ( the_rank_of x ) c= ULL by A37,ZFMISC_1:74;
then A43: ( Rank ( the_rank_of x ) ) c= ( Rank ULL ) by CLASSES1:37;
x c= ( Rank ( the_rank_of x ) ) by CLASSES1:def 8;
then x c= ( Rank ULL ) by A43,XBOOLE_1:1;
hence thesis by CLASSES1:32;
end;
then A44: X in ( Rank ( succ ( succ ULL ) ) ) by CLASSES1:32;
( Union ( id LL ) ) = ( union ( rng ( id LL ) ) ) by CARD_3:def 4
.= ULL by RELAT_1:45;
then ( card ULL ) in ( card W ) by A27,A33,CARD_3:39,ORDINAL1:12;
then A45: ULL <> ( On W ) by A35;
( union ( card W ) ) = ( card W ) by A34,ORDINAL1:def 6;
then ULL c= ( On W ) by A6,A35,ZFMISC_1:77;
then ULL c< ( On W ) by A45,XBOOLE_0:def 8;
then ULL in ( card W ) by A35,ORDINAL1:11;
then ( succ ULL ) in ( card W ) by A34,ORDINAL1:28;
then ( succ ( succ ULL ) ) in ( card W ) by A34,ORDINAL1:28;
hence thesis by A34,A44,CLASSES1:31;
end;
