environ
vocabularies CARD_1,ORDINAL1,FUNCT_1,CLASSES1,TARSKI,ZFMISC_1,XBOOLE_0,RELAT_1,CARD_3,FUNCT_2,SUBSET_1,SETFAM_1,FINSET_1,ORDINAL2,CLASSES2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,FINSET_1,SETFAM_1,RELAT_1,FUNCT_1,FUNCT_2,ORDINAL1,ORDINAL2,CLASSES1,CARD_3,CKB49,CKB53,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86;
definitions TARSKI,ORDINAL1,CLASSES1,XBOOLE_0,CKB49,CKB86;
theorems TARSKI,ZFMISC_1,SETFAM_1,ORDINAL1,WELLORD2,ORDINAL2,ORDINAL3,FUNCT_1,FUNCT_2,CARD_1,CLASSES1,CARD_2,FRAENKEL,CARD_3,RELAT_1,XBOOLE_0,XBOOLE_1,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB54,CKB55,CKB56,CKB59,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB86,CKB87;
schemes FUNCT_1,PARTFUN1,CARD_3,ORDINAL1,ORDINAL2,XBOOLE_0,CARD_2;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,ORDINAL1,CARD_1,CLASSES1,CKB2,CKB3,CKB50,CKB51,CKB52,CKB57,CKB58,CKB60,CKB73;
constructors SETFAM_1,WELLORD2,ORDINAL2,CLASSES1,CARD_3,NUMBERS,FUNCT_2,CKB49,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86;
requirements SUBSET,BOOLE,NUMERALS;
begin
reserve A for Ordinal;
reserve x for set;
reserve y for set;
reserve X for set;
reserve Y for set;
reserve L for T-Sequence;
theorem
Th69: ( card ( Rank ( omega ) ) ) = ( card ( omega ) )
proof
deffunc h(Ordinal) = ( Rank $1 );
consider L such that A1: (( dom L ) = ( omega ) & (for A holds (A in ( omega ) implies ( L . A ) = h(A)))) from ORDINAL2:sch 2;
now
let X;
let Y;
assume X in ( rng L );
then consider x such that A2: x in ( dom L ) and A3: X = ( L . x ) by FUNCT_1:def 3;
assume Y in ( rng L );
then consider y such that A4: y in ( dom L ) and A5: Y = ( L . y ) by FUNCT_1:def 3;
reconsider x,y as Ordinal by A2,A4;
A6: Y = ( Rank y ) by A1,A4,A5;
A7: (x c= y or y c= x);
X = ( Rank x ) by A1,A2,A3;
then (X c= Y or Y c= X) by A6,A7,CLASSES1:37;
hence X,Y are_c=-comparable  by XBOOLE_0:def 9;
end;
then A8: ( rng L ) is  c=-linear by ORDINAL1:def 8;
A9: ( card ( omega ) ) c= ( card ( Rank ( omega ) ) ) by CARD_1:11,CLASSES1:38;
A10:now
let X;
assume X in ( rng L );
then consider x such that A11: x in ( dom L ) and A12: X = ( L . x ) by FUNCT_1:def 3;
reconsider x as Ordinal by A11;
X = ( Rank x ) by A1,A11,A12;
hence ( card X ) in ( card ( omega ) ) by A1,A11,CARD_2:67,CARD_3:42;
end;
( Rank ( omega ) ) = ( Union L ) by A1,CKB87:1,CKB27:1
.= ( union ( rng L ) ) by CARD_3:def 4;
then ( card ( Rank ( omega ) ) ) c= ( card ( omega ) ) by A8,A10,CARD_3:46;
hence thesis by A9,XBOOLE_0:def 10;
end;
