environ
vocabularies NUMBERS,NAT_1,XXREAL_0,ARYTM_3,RADIX_1,RADIX_5,FINSEQ_1,CARD_1,FUNCT_1,NEWTON,RELAT_1,PARTFUN1,ARYTM_1,CARD_3,FINSEQ_2,SUBSET_1,INT_1,RADIX_6;
notations SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,INT_1,NAT_1,NAT_D,NEWTON,RADIX_1,FINSEQ_1,FINSEQ_2,FUNCT_1,RELSET_1,PARTFUN1,GR_CY_1,RADIX_5,CKB4,CKB5,CKB6,CKB7;
definitions CKB4,CKB5,CKB6,CKB7;
theorems RADIX_1,RADIX_2,RADIX_4,RADIX_5,INT_1,NAT_1,NAT_2,FINSEQ_1,FINSEQ_2,RVSUM_1,NEWTON,PREPOWER,FUNCT_1,FINSEQ_3,XREAL_1,XXREAL_0,NAT_D,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
schemes FINSEQ_2,NAT_1;
registrations RELSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,ORDINAL1,NEWTON,XBOOLE_0,FINSEQ_2,CARD_1;
constructors REAL_1,NAT_D,NEWTON,GR_CY_1,RADIX_5,SEQ_1,RELSET_1,CKB4,CKB5,CKB6,CKB7;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
definition
let i being Nat;
let m being Nat;
let k being Nat;
let r being (Tuple of ( m + 2 ),( k -SD ));
assume that
A1: k >= 2
and
A2: i in ( Seg ( m + 2 ) );
func MminDigit (r,i) -> (Element of ( k -SD ))
equals
:Def5: ( r . i ) if i >= m otherwise ( ( - ( Radix k ) ) + 1 );
coherence
proof
( len r ) = ( m + 2 ) by CARD_1:def 7;
then i in ( dom r ) by A2,FINSEQ_1:def 3;
then A3: ( r . i ) in ( rng r ) by FUNCT_1:def 3;
( Radix k ) > 2 by A1,RADIX_4:1;
then ( Radix k ) > 1 by XXREAL_0:2;
then ( ( Radix k ) + ( Radix k ) ) > ( 1 + 1 ) by XREAL_1:8;
then A4: ( ( Radix k ) - 1 ) > ( 1 - ( Radix k ) ) by XREAL_1:21;
A5: ( ( - ( Radix k ) ) + 1 ) is (Element of ( INT )) by INT_1:def 2;
( k -SD ) = { w where w is (Element of ( INT )): (w <= ( ( Radix k ) - 1 ) & w >= ( ( - ( Radix k ) ) + 1 )) } by RADIX_1:def 2;
then ( ( - ( Radix k ) ) + 1 ) in ( k -SD ) by A4,A5;
hence thesis by A3;
end;
consistency;
end;
