environ
vocabularies WAYBEL_0,WAYBEL11,WAYBEL_9,SUBSET_1,WAYBEL17,EQREL_1,ORDINAL2,FUNCT_1,STRUCT_0,TARSKI,YELLOW_1,XBOOLE_0,ORDERS_2,RELAT_2,SEQM_3,XXREAL_0,RELAT_1,FUNCOP_1,LATTICES,LATTICE3,NEWTON,REWRITE1,YELLOW_0,FUNCT_2,ZFMISC_1,BORSUK_1,FUNCT_5,MCART_1,PRE_TOPC,CAT_1,MONOID_0,WAYBEL_3,PBOOLE,CARD_3,FUNCT_4,WAYBEL24;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,BINOP_1,DOMAIN_1,FUNCT_5,MONOID_0,CARD_3,PBOOLE,FUNCOP_1,STRUCT_0,PRE_TOPC,ORDERS_2,LATTICE3,FUNCT_7,YELLOW_0,ORDERS_3,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_3,WAYBEL_9,WAYBEL11,WAYBEL17,YELLOW_3,CKB11,CKB13,CKB31;
definitions TARSKI,WAYBEL_0,LATTICE3,ORDERS_2,MONOID_0,XBOOLE_0,BINOP_1,STRUCT_0,CKB11,CKB13,CKB31;
theorems WAYBEL_0,TARSKI,FUNCT_1,FUNCT_2,YELLOW_0,YELLOW_2,WAYBEL_1,ZFMISC_1,LATTICE3,WAYBEL10,CAT_2,WAYBEL17,YELLOW_3,MCART_1,FUNCT_5,YELLOW_5,YELLOW10,WAYBEL_9,FUNCOP_1,YELLOW_1,ORDERS_2,WAYBEL_3,CARD_3,FUNCT_7,RELAT_1,WAYBEL15,RELSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB4,CKB5,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB34,CKB35,CKB40,CKB41,CKB42;
schemes XBOOLE_0,CKB6,CKB7;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FUNCT_2,STRUCT_0,LATTICE3,YELLOW_0,MONOID_0,WAYBEL_0,YELLOW_1,YELLOW_3,WAYBEL_3,WAYBEL10,WAYBEL11,WAYBEL17,PRE_TOPC,RELAT_1,CKB2,CKB3,CKB16,CKB19,CKB20,CKB21,CKB22,CKB32,CKB33,CKB36,CKB37,CKB38,CKB39;
constructors FUNCT_7,BORSUK_1,MONOID_0,ORDERS_3,WAYBEL_1,WAYBEL_3,WAYBEL17,YELLOW_3,CKB11,CKB13,CKB31;
requirements SUBSET,BOOLE;
begin
theorem
Th25: (for S being non  empty RelStr holds (for T being  complete LATTICE holds (for F being non  empty (Subset of ( T |^ (the carrier of S) )) holds (for i being (Element of S) holds ( ( sup F ) . i ) = ( "\/" ({ ( f . i ) where f is (Element of ( T |^ (the carrier of S) )): f in F },T) )))))
proof
let S being non  empty RelStr;
let T being  complete LATTICE;
let F being non  empty (Subset of ( T |^ (the carrier of S) ));
let i being (Element of S);
reconsider SYT = ( (the carrier of S) --> T ) as  non-Empty  RelStr-yielding (ManySortedSet of (the carrier of S));
reconsider SYT as  non-Empty  reflexive-yielding  RelStr-yielding (ManySortedSet of (the carrier of S));
reconsider X = F as (Subset of ( product SYT )) by YELLOW_1:def 5;
A1: ( pi (X,i) ) = { ( f . i ) where f is (Element of ( T |^ (the carrier of S) )): f in F }
proof
thus ( pi (X,i) ) c= { ( f . i ) where f is (Element of ( T |^ (the carrier of S) )): f in F }
proof
let a being set;
assume a in ( pi (X,i) );
then (ex g being Function st (g in X & a = ( g . i ))) by CARD_3:def 6;
hence thesis;
end;

thus { ( f . i ) where f is (Element of ( T |^ (the carrier of S) )): f in F } c= ( pi (X,i) )
proof
let a being set;
assume a in { ( f . i ) where f is (Element of ( T |^ (the carrier of S) )): f in F };
then (ex g being (Element of ( T |^ (the carrier of S) )) st (a = ( g . i ) & g in F));
hence thesis by CARD_3:def 6;
end;

end;
(( T |^ (the carrier of S) ) = ( product SYT ) & (for i being (Element of S) holds ( SYT . i ) is  complete  complete LATTICE)) by FUNCOP_1:7,YELLOW_1:def 5;
then ( ( sup F ) . i ) = ( "\/" (( pi (X,i) ),( SYT . i )) ) by WAYBEL_3:32
.= ( "\/" ({ ( f . i ) where f is (Element of ( T |^ (the carrier of S) )): f in F },T) ) by A1,FUNCOP_1:7;
hence thesis;
end;
