environ
vocabularies WAYBEL_0,WAYBEL11,WAYBEL_9,SUBSET_1,WAYBEL17,EQREL_1,ORDINAL2,FUNCT_1,STRUCT_0,TARSKI,YELLOW_1,XBOOLE_0,ORDERS_2,RELAT_2,SEQM_3,XXREAL_0,RELAT_1,FUNCOP_1,LATTICES,LATTICE3,NEWTON,REWRITE1,YELLOW_0,FUNCT_2,ZFMISC_1,BORSUK_1,FUNCT_5,MCART_1,PRE_TOPC,CAT_1,MONOID_0,WAYBEL_3,PBOOLE,CARD_3,FUNCT_4,WAYBEL24;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,BINOP_1,DOMAIN_1,FUNCT_5,MONOID_0,CARD_3,PBOOLE,FUNCOP_1,STRUCT_0,PRE_TOPC,ORDERS_2,LATTICE3,FUNCT_7,YELLOW_0,ORDERS_3,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_3,WAYBEL_9,WAYBEL11,WAYBEL17,YELLOW_3;
definitions TARSKI,WAYBEL_0,LATTICE3,ORDERS_2,MONOID_0,XBOOLE_0,BINOP_1,STRUCT_0;
theorems WAYBEL_0,TARSKI,FUNCT_1,FUNCT_2,YELLOW_0,YELLOW_2,WAYBEL_1,ZFMISC_1,LATTICE3,WAYBEL10,CAT_2,WAYBEL17,YELLOW_3,MCART_1,FUNCT_5,YELLOW_5,YELLOW10,WAYBEL_9,FUNCOP_1,YELLOW_1,ORDERS_2,WAYBEL_3,CARD_3,FUNCT_7,RELAT_1,WAYBEL15,RELSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB4,CKB5,CKB8;
schemes XBOOLE_0,CKB6,CKB7;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FUNCT_2,STRUCT_0,LATTICE3,YELLOW_0,MONOID_0,WAYBEL_0,YELLOW_1,YELLOW_3,WAYBEL_3,WAYBEL10,WAYBEL11,WAYBEL17,PRE_TOPC,RELAT_1,CKB2,CKB3;
constructors FUNCT_7,BORSUK_1,MONOID_0,ORDERS_3,WAYBEL_1,WAYBEL_3,WAYBEL17,YELLOW_3;
requirements SUBSET,BOOLE;
begin
theorem
(for S,T being  complete  lower-bounded LATTICE holds (for f being  monotone (Function of S,T) holds (for x being (Element of S) holds ( f . x ) = ( "\/" ({ ( f . w ) where w is (Element of S): w <= x },T) ))))
proof
let S being  complete  lower-bounded LATTICE,T being  complete  lower-bounded LATTICE;
let f being  monotone (Function of S,T);
let x being (Element of S);
deffunc A((Element of S)) = $1;
defpred P[ (Element of S) ]
 means
$1 <= x;
defpred R[ (Element of S) ]
 means
(ex y1 being (Element of S) st ($1 <= y1 & y1 in { x }));
A1: (the carrier of S) c= ( dom f ) by FUNCT_2:def 1;
A2: ( f .: { A(w) where w is (Element of S): P[ w ] } ) = { ( f . A(w) ) where w is (Element of S): P[ w ] } from CKB6:sch 1(A1);
A3: (for x2 being (Element of S) holds (P[ x2 ] iff R[ x2 ]))
proof
let x2 being (Element of S);
hereby
A4: x in { x } by TARSKI:def 1;
assume x2 <= x;
hence (ex y1 being (Element of S) st (x2 <= y1 & y1 in { x })) by A4;
end;
given y1 being (Element of S) such that
A5: (x2 <= y1 & y1 in { x });

thus thesis by A5,TARSKI:def 1;
end;
{ A(w) where w is (Element of S): P[ w ] } = { A(x1) where x1 is (Element of S): R[ x1 ] } from CKB7:sch 1(A3);
then A6: ( downarrow x ) = { w where w is (Element of S): w <= x } by WAYBEL_0:14;
( sup ( f .: ( downarrow x ) ) ) = ( f . x ) by CKB8:1
.= ( f . ( sup ( downarrow x ) ) ) by WAYBEL_0:34;
hence thesis by A2,A6,WAYBEL_0:34;
end;
