environ
vocabularies FUNCT_1,XBOOLE_0,SUBSET_1,ZFMISC_1,MULTOP_1;
notations XBOOLE_0,ZFMISC_1,SUBSET_1,FUNCT_1,FUNCT_2,MCART_1,DOMAIN_1,CKB1,CKB2,CKB6,CKB11,CKB12,CKB16;
definitions CKB1,CKB11;
theorems FUNCT_2,MCART_1,CKB1,CKB3,CKB4,CKB5,CKB11,CKB13,CKB14,CKB15;
schemes FUNCT_2,CKB7,CKB8,CKB9,CKB10,CKB17,CKB18;
registrations XBOOLE_0,SUBSET_1,RELSET_1;
constructors FUNCT_2,DOMAIN_1,RELSET_1,CKB1,CKB2,CKB11,CKB12;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve Z for set;
reserve S for set;
scheme Lambda4D { X,Y,Z,S,T() -> non  empty set,F((Element of X()),(Element of Y()),(Element of Z()),(Element of S())) -> (Element of T()) } : (ex f being (Function of [: X(),Y(),Z(),S() :],T()) st (for x being (Element of X()) holds (for y being (Element of Y()) holds (for z being (Element of Z()) holds (for s being (Element of S()) holds ( f . [ x,y,z,s ] ) = F(x,y,z,s))))))
proof
defpred P[ (Element of X()),(Element of Y()),(Element of Z()),(Element of S()),(Element of T()) ]
 means
$5 = F($1,$2,$3,$4);
A1: (for x being (Element of X()) holds (for y being (Element of Y()) holds (for z being (Element of Z()) holds (for s being (Element of S()) holds (ex t being (Element of T()) st P[ x,y,z,s,t ])))));
(ex f being (Function of [: X(),Y(),Z(),S() :],T()) st (for x being (Element of X()) holds (for y being (Element of Y()) holds (for z being (Element of Z()) holds (for s being (Element of S()) holds P[ x,y,z,s,( f . [ x,y,z,s ] ) ]))))) from CKB17:sch 1(A1);
hence thesis;
end;
