environ
vocabularies XBOOLE_0,SUBSET_1,PARTIT1,FUNCT_2,MARGREL1,EQREL_1,BVFUNC_1,BVFUNC_2,XBOOLEAN,FUNCT_1;
notations XBOOLE_0,SUBSET_1,XBOOLEAN,MARGREL1,FUNCT_2,EQREL_1,BVFUNC_1,BVFUNC_2;
definitions BVFUNC_1,XBOOLEAN;
theorems MARGREL1,BINARITH,BVFUNC_1,BVFUNC_2,XBOOLEAN,EQREL_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
registrations XBOOLE_0,MARGREL1;
constructors BVFUNC_1,BVFUNC_2,RELSET_1;
requirements BOOLE;
begin
reserve Y for non  empty set;
reserve G for (Subset of ( PARTITIONS Y ));
reserve a for (Element of ( Funcs (Y,( BOOLEAN )) ));
reserve b for (Element of ( Funcs (Y,( BOOLEAN )) ));
reserve PA for (a_partition of Y);
theorem
( ( All (a,PA,G) ) 'imp' ( All (b,PA,G) ) ) '<' ( ( All (a,PA,G) ) 'imp' ( Ex (b,PA,G) ) )
proof
let z being (Element of Y);
A1: (( 'not' ( ( All (a,PA,G) ) . z ) ) = ( TRUE ) or ( 'not' ( ( All (a,PA,G) ) . z ) ) = ( FALSE )) by XBOOLEAN:def 3;
A2: z in ( EqClass (z,( CompF (PA,G) )) ) by EQREL_1:def 6;
assume ( ( ( All (a,PA,G) ) 'imp' ( All (b,PA,G) ) ) . z ) = ( TRUE );
then A3: ( ( 'not' ( ( All (a,PA,G) ) . z ) ) 'or' ( ( All (b,PA,G) ) . z ) ) = ( TRUE ) by BVFUNC_1:def 8;
per cases  by A3,A1,BINARITH:3;
suppose ( 'not' ( ( All (a,PA,G) ) . z ) ) = ( TRUE );

hence ( ( ( All (a,PA,G) ) 'imp' ( Ex (b,PA,G) ) ) . z ) = ( ( TRUE ) 'or' ( ( Ex (b,PA,G) ) . z ) ) by BVFUNC_1:def 8
.= ( TRUE ) by BINARITH:10;
end;
suppose A4: ( ( All (b,PA,G) ) . z ) = ( TRUE );

now
assume (not (for x being (Element of Y) holds (x in ( EqClass (z,( CompF (PA,G) )) ) implies ( b . x ) = ( TRUE ))));
then ( ( B_INF (b,( CompF (PA,G) )) ) . z ) = ( FALSE ) by BVFUNC_1:def 16;
hence contradiction by A4,BVFUNC_2:def 9;
end;
then ( b . z ) = ( TRUE ) by A2;
then ( ( B_SUP (b,( CompF (PA,G) )) ) . z ) = ( TRUE ) by A2,BVFUNC_1:def 17;
then ( ( Ex (b,PA,G) ) . z ) = ( TRUE ) by BVFUNC_2:def 10;
hence ( ( ( All (a,PA,G) ) 'imp' ( Ex (b,PA,G) ) ) . z ) = ( ( 'not' ( ( All (a,PA,G) ) . z ) ) 'or' ( TRUE ) ) by BVFUNC_1:def 8
.= ( TRUE ) by BINARITH:10;
end;
end;
