environ
vocabularies ARYTM_1,XBOOLE_0,CARD_1,CLASSES1,COHSP_1,FINSET_1,FUNCT_1,GROUP_4,INT_1,MATROID0,ORDERS_1,PARTFUN1,PRE_TOPC,RELAT_1,RELAT_2,NUMBERS,SETFAM_1,SGRAPH1,SUBSET_1,TARSKI,TRIANG_1,WELLORD1,ZFMISC_1,SIMPLEX0,XXREAL_0,NAT_1,ORDINAL1,FUNCOP_1,ARYTM_3,RCOMP_1,STRUCT_0,GLIB_000,XREAL_0;
notations TARSKI,XBOOLE_0,SUBSET_1,ZFMISC_1,RELAT_1,RELAT_2,FUNCT_1,FUNCT_2,NUMBERS,WELLORD1,ORDINAL1,ORDERS_1,FINSET_1,CARD_1,XREAL_0,XXREAL_0,XXREAL_3,NAT_1,INT_1,SETFAM_1,DOMAIN_1,STRUCT_0,PRE_TOPC,TOPS_2,PENCIL_1,CLASSES1,MATROID0,RELSET_1,COHSP_1,FUNCOP_1,CKB1,CKB18,CKB20,CKB31,CKB37,CKB43,CKB44,CKB45,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB84,CKB90,CKB91,CKB95,CKB103,CKB115,CKB121,CKB122,CKB128,CKB134,CKB141,CKB146;
definitions CLASSES1,COHSP_1,FUNCOP_1,MATROID0,ORDINAL1,SETFAM_1,STRUCT_0,SUBSET_1,TARSKI,TOPS_2,VECTSP_1,XBOOLE_0,XXREAL_3,CKB18,CKB31,CKB48,CKB49,CKB51,CKB52,CKB53,CKB54,CKB57,CKB58,CKB84,CKB95,CKB103,CKB115,CKB121,CKB122,CKB128,CKB141,CKB146;
theorems CARD_1,CARD_2,CARD_3,CLASSES1,COHSP_1,COMBGRAS,COMPL_SP,FINSET_1,FUNCT_1,FUNCT_2,FUNCOP_1,INT_1,MATROID0,NAT_1,NUMBERS,ORDERS_1,ORDINAL1,PENCIL_1,PRE_TOPC,RELAT_1,RELAT_2,SETFAM_1,STIRL2_1,SUBSET_1,WELLORD1,WELLORD2,TARSKI,TOPS_2,XREAL_0,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,XXREAL_3,ZFMISC_1,CKB14,CKB17,CKB18,CKB19,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB38,CKB39,CKB40,CKB41,CKB42,CKB47,CKB48,CKB49,CKB51,CKB52,CKB53,CKB54,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB89,CKB95,CKB98,CKB99,CKB100,CKB101,CKB102,CKB103,CKB109,CKB110,CKB111,CKB112,CKB113,CKB114,CKB115,CKB116,CKB118,CKB119,CKB120,CKB121,CKB122,CKB123,CKB124,CKB125,CKB126,CKB128,CKB133,CKB135,CKB136,CKB137,CKB138,CKB139,CKB140,CKB141,CKB143,CKB144,CKB145,CKB146,CKB147;
schemes CLASSES1,FRAENKEL,FUNCT_2,NAT_1;
registrations BORSUK_3,CARD_1,COHSP_1,FIB_NUM2,FINSET_1,FUNCT_1,INT_1,MATROID0,NAT_1,ORDINAL1,PENCIL_1,REALSET1,RELAT_1,SETFAM_1,SUBSET_1,STRUCT_0,XBOOLE_0,XREAL_0,XXREAL_0,XXREAL_3,FUNCOP_1,DILWORTH,RELSET_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB15,CKB16,CKB21,CKB22,CKB23,CKB24,CKB32,CKB33,CKB34,CKB35,CKB36,CKB46,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB85,CKB86,CKB87,CKB88,CKB92,CKB93,CKB94,CKB96,CKB97,CKB104,CKB105,CKB106,CKB107,CKB108,CKB117,CKB127,CKB129,CKB130,CKB131,CKB132,CKB142;
constructors SETFAM_1,XXREAL_3,REAL_1,TOPS_2,BORSUK_1,WELLORD1,BINOP_2,CLASSES1,COH_SP,LEXBFS,MATROID0,COHSP_1,FUNCOP_1,CKB18,CKB20,CKB31,CKB48,CKB49,CKB51,CKB52,CKB53,CKB54,CKB57,CKB58,CKB84,CKB95,CKB103,CKB115,CKB121,CKB128,CKB134,CKB141,CKB146;
requirements REAL,SUBSET,NUMERALS,ARITHM,BOOLE;
begin
reserve x for set;
reserve X for set;
reserve KX for (SimplicialComplexStr of X);
reserve P for Function;
definition
let X;
let KX;
let P;
func subdivision (P,KX) ->  strict (SimplicialComplexStr of X) means 
:Def20: (( [#] it ) = ( [#] KX ) & (for A being (Subset of it) holds (A is  simplex-like iff (ex S being  c=-linear  finite  simplex-like (Subset-Family of KX) st A = ( P .: S )))));
existence
proof
defpred P[ set ]
 means
(ex S being  c=-linear  finite  simplex-like (Subset-Family of KX) st $1 = ( P .: S ));
set SS = { A where A is (Subset of KX): P[ A ] };
SS c= ( bool (the carrier of KX) )
proof
let x;
assume x in SS;
then (ex A being (Subset of KX) st (x = A & P[ A ]));
hence thesis;
end;
then reconsider SS as (Subset-Family of KX);
set PP = TopStruct (# (the carrier of KX),SS #);
(( [#] PP ) = ( [#] KX ) & ( [#] KX ) c= X) by CKB57:def 1;
then reconsider PP as  strict (SimplicialComplexStr of X) by CKB57:def 1;
take PP;
thus ( [#] PP ) = ( [#] KX );
let A being (Subset of PP);
hereby
assume A is  simplex-like;
then A in SS by PRE_TOPC:def 2;
then (ex B being (Subset of KX) st (B = A & P[ B ]));
hence P[ A ];
end;
assume P[ A ];
then A in SS;
hence thesis by PRE_TOPC:def 2;
end;
uniqueness
proof
let P1 being  strict (SimplicialComplexStr of X);
let P2 being  strict (SimplicialComplexStr of X);
assume that
A1: ( [#] P1 ) = ( [#] KX )
and
A2: (for A being (Subset of P1) holds (A is  simplex-like iff (ex S being  c=-linear  finite  simplex-like (Subset-Family of KX) st A = ( P .: S ))))
and
A3: ( [#] P2 ) = ( [#] KX )
and
A4: (for A being (Subset of P2) holds (A is  simplex-like iff (ex S being  c=-linear  finite  simplex-like (Subset-Family of KX) st A = ( P .: S ))));
now
let x;
hereby
assume A5: x in (the topology of P1);
then reconsider A = x as (Subset of P1);
reconsider B = A as (Subset of P2) by A1,A3;
A is  simplex-like by A5,PRE_TOPC:def 2;
then (ex S being  c=-linear  finite  simplex-like (Subset-Family of KX) st A = ( P .: S )) by A2;
then B is  simplex-like by A4;
hence x in (the topology of P2) by PRE_TOPC:def 2;
end;
assume A6: x in (the topology of P2);
then reconsider A = x as (Subset of P2);
reconsider B = A as (Subset of P1) by A1,A3;
A is  simplex-like by A6,PRE_TOPC:def 2;
then (ex S being  c=-linear  finite  simplex-like (Subset-Family of KX) st A = ( P .: S )) by A4;
then B is  simplex-like by A2;
hence x in (the topology of P1) by PRE_TOPC:def 2;
end;
hence thesis by A1,A3,TARSKI:1;
end;
end;
