environ
vocabularies OSALG_1,MSUALG_2,OSALG_2,MSUALG_1,TARSKI,STRUCT_0,RELAT_1,SEQM_3,PBOOLE,MSUALG_3,REALSET1,ZFMISC_1,XBOOLE_0,CARD_3,MSAFREE,SUBSET_1,FINSEQ_1,MARGREL1,FUNCT_1,XXREAL_0,PARTFUN1,LANG1,TDGROUP,DTCONSTR,TREES_3,TREES_4,NAT_1,TREES_2,OSALG_4,CARD_5,NATTRA_1,CARD_LAR,QC_LANG1,EQREL_1,RELAT_2,MSUALG_4,COH_SP,MCART_1,UNIALG_2,MEMBER_1,FUNCT_7,OSAFREE;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NAT_1,RELAT_1,RELSET_1,FUNCT_1,MCART_1,PARTFUN1,FUNCT_2,FINSEQ_1,FINSEQ_2,PBOOLE,RELAT_2,TREES_2,CARD_3,EQREL_1,STRUCT_0,LANG1,TREES_3,TREES_4,DTCONSTR,ORDERS_2,ORDERS_3,MSUALG_1,MSUALG_2,MSUALG_3,MSUALG_4,OSALG_1,OSALG_2,OSALG_3,OSALG_4,MSAFREE,FUNCT_7,CKB1,CKB3,CKB4,CKB5,CKB7,CKB12,CKB13,CKB15;
definitions TARSKI,XBOOLE_0,PBOOLE,MSUALG_3,OSALG_1,OSALG_3,OSALG_4,CKB1,CKB3,CKB4,CKB5,CKB7,CKB12,CKB13,CKB15;
theorems TARSKI,FUNCT_1,FUNCT_2,MCART_1,ZFMISC_1,PBOOLE,CARD_3,MSUALG_1,MSUALG_2,MSUALG_3,RELAT_1,LANG1,DTCONSTR,FINSEQ_1,TREES_4,TREES_1,DOMAIN_1,RELSET_1,XBOOLE_0,XBOOLE_1,OSALG_1,OSALG_2,OSALG_3,OSALG_4,MSAFREE,MSUALG_6,MSAFREE2,CARD_5,FINSEQ_2,FINSEQ_3,MSUALG_9,MSUALG_4,EQREL_1,FUNCT_5,ORDERS_2,RELAT_2,PARTFUN1,ORDERS_1,FUNCT_7,FUNCOP_1,TREES_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB9,CKB11,CKB12,CKB13,CKB15,CKB17,CKB18;
schemes CLASSES1,FUNCT_1,RELSET_1,DTCONSTR,XBOOLE_0,FUNCT_2,PBOOLE;
registrations XBOOLE_0,SUBSET_1,RELAT_1,ORDINAL1,PARTFUN1,FUNCOP_1,FUNCT_1,PBOOLE,TREES_2,TREES_3,STRUCT_0,DTCONSTR,MSUALG_1,MSUALG_3,MSAFREE,MSUALG_4,MSUALG_9,OSALG_1,OSALG_4,RELSET_1,FINSEQ_1,CKB8,CKB10,CKB14,CKB16;
constructors XXREAL_0,NAT_1,FINSEQOP,FUNCT_7,MSUALG_3,MSAFREE,ORDERS_3,OSALG_2,OSALG_3,OSALG_4,RELSET_1,CKB1,CKB3,CKB4,CKB5,CKB7,CKB12,CKB13,CKB15;
requirements BOOLE,SUBSET;
begin
reserve S for OrderSortedSign;
reserve X for (ManySortedSet of S);
reserve o for (OperSymbol of S);
reserve x for set;
theorem
Th7: (for S being OrderSortedSign holds (for X being  non-empty (ManySortedSet of S) holds (for o being (OperSymbol of S) holds (for p being (FinSequence of ( TS ( DTConOSA X ) )) holds (( OSSym (o,X) ) ==> ( roots p ) iff p in ( ( ( ( ParsedTerms X ) # ) * (the Arity of S) ) . o ))))))
proof
let S being OrderSortedSign;
let X being  non-empty (ManySortedSet of S);
let o being (OperSymbol of S);
let p being (FinSequence of ( TS ( DTConOSA X ) ));
set D = ( DTConOSA X );
set ar = ( the_arity_of o );
set r = ( roots p );
set OU = ( [: (the carrier' of S),{ (the carrier of S) } :] \/ ( Union ( coprod X ) ) );
A1: ( dom p ) = ( dom r ) by TREES_3:def 18;
thus (( OSSym (o,X) ) ==> ( roots p ) implies p in ( ( ( ( ParsedTerms X ) # ) * (the Arity of S) ) . o ))
proof
assume ( OSSym (o,X) ) ==> ( roots p );
then A2: [ [ o,(the carrier of S) ],( roots p ) ] in ( OSREL X ) by LANG1:def 1;
then reconsider r = ( roots p ) as (Element of ( ( [: (the carrier' of S),{ (the carrier of S) } :] \/ ( Union ( coprod X ) ) ) * )) by ZFMISC_1:87;
A3: ( dom p ) = ( dom r ) by TREES_3:def 18;
A4: (for n being Nat holds (n in ( dom p ) implies ( p . n ) in ( ParsedTerms (X,( ar /. n )) )))
proof
let n being Nat;
set s = ( ar /. n );
A5: ( rng r ) c= ( [: (the carrier' of S),{ (the carrier of S) } :] \/ ( Union ( coprod X ) ) ) by FINSEQ_1:def 4;
A6: ( rng p ) c= ( TS D ) by FINSEQ_1:def 4;
assume A7: n in ( dom p );
then consider T being DecoratedTree such that A8: T = ( p . n ) and A9: ( r . n ) = ( T . ( {} ) ) by TREES_3:def 18;
( p . n ) in ( rng p ) by A7,FUNCT_1:def 3;
then reconsider T as (Element of ( TS D )) by A8,A6;
A10: ( r . n ) in ( rng r ) by A3,A7,FUNCT_1:def 3;
per cases  by A5,A10,XBOOLE_0:def 3;
suppose A11: ( r . n ) in [: (the carrier' of S),{ (the carrier of S) } :];

then consider o1 being (Element of (the carrier' of S)),x2 being (Element of { (the carrier of S) }) such that A12: ( r . n ) = [ o1,x2 ] by DOMAIN_1:1;
A13: x2 = (the carrier of S) by TARSKI:def 1;
then ( the_result_sort_of o1 ) <= ( ar /. n ) by A2,A3,A7,A11,A12,CKB6:1;
then (ex o being (OperSymbol of S) st ([ o,(the carrier of S) ] = ( T . ( {} ) ) & ( the_result_sort_of o ) <= s)) by A9,A12,A13;
hence thesis by A8;
end;
suppose A14: ( r . n ) in ( Union ( coprod X ) );

then reconsider t = ( r . n ) as (Terminal of D) by CKB9:1;
A15: T = ( root-tree t ) by A9,DTCONSTR:9;
consider i being (Element of S) such that A16: i <= ( ar /. n ) and A17: ( r . n ) in ( coprod (i,X) ) by A2,A3,A7,A14,CKB6:1;
(ex a being set st (a in ( X . i ) & ( r . n ) = [ a,i ])) by A17,MSAFREE:def 2;
hence thesis by A8,A16,A15;
end;
end;
A18: ( Seg ( len ar ) ) = ( dom ar ) by FINSEQ_1:def 3;
A19: ( dom r ) = ( Seg ( len r ) ) by FINSEQ_1:def 3;
( len r ) = ( len ar ) by A2,CKB6:1;
hence thesis by A3,A19,A18,A4,CKB18:1;
end;

assume A20: p in ( ( ( ( ParsedTerms X ) # ) * (the Arity of S) ) . o );
A21: ( dom r ) = ( Seg ( len r ) ) by FINSEQ_1:def 3;
reconsider r as (FinSequence of OU);
reconsider r as (Element of ( OU * )) by FINSEQ_1:def 11;
A22: ( Union ( coprod X ) ) misses [: (the carrier' of S),{ (the carrier of S) } :] by MSAFREE:4;
A23: (for x being set holds (x in ( dom r ) implies ((( r . x ) in [: (the carrier' of S),{ (the carrier of S) } :] implies (for o1 being (OperSymbol of S) holds ([ o1,(the carrier of S) ] = ( r . x ) implies ( the_result_sort_of o1 ) <= ( ar /. x )))) & (( r . x ) in ( Union ( coprod X ) ) implies (ex i being (Element of S) st (i <= ( ar /. x ) & ( r . x ) in ( coprod (i,X) )))))))
proof
let x being set;
assume A24: x in ( dom r );
then reconsider n = x as Nat;
set s = ( ar /. n );
( p . n ) in ( ParsedTerms (X,s) ) by A20,A1,A24,CKB18:1;
then consider a being (Element of ( TS D )) such that A25: a = ( p . n ) and A26: ((ex s1 being (Element of S) st (ex x being set st ((s1 <= s & x in ( X . s1 )) & a = ( root-tree [ x,s1 ] )))) or (ex o being (OperSymbol of S) st ([ o,(the carrier of S) ] = ( a . ( {} ) ) & ( the_result_sort_of o ) <= s)));
A27: (ex T being DecoratedTree st (T = ( p . n ) & ( r . n ) = ( T . ( {} ) ))) by A1,A24,TREES_3:def 18;
thus (( r . x ) in [: (the carrier' of S),{ (the carrier of S) } :] implies (for o1 being (OperSymbol of S) holds ([ o1,(the carrier of S) ] = ( r . x ) implies ( the_result_sort_of o1 ) <= ( ar /. x ))))
proof
assume A28: ( r . x ) in [: (the carrier' of S),{ (the carrier of S) } :];
A29:now
given s1 being (Element of S),y being set such that
s1 <= s
and
A30: y in ( X . s1 )
and
A31: a = ( root-tree [ y,s1 ] );

A32: [ y,s1 ] in ( coprod (s1,X) ) by A30,MSAFREE:def 2;
( dom ( coprod X ) ) = (the carrier of S) by PARTFUN1:def 2;
then ( ( coprod X ) . s1 ) in ( rng ( coprod X ) ) by FUNCT_1:def 3;
then A33: ( coprod (s1,X) ) in ( rng ( coprod X ) ) by MSAFREE:def 3;
( r . x ) = [ y,s1 ] by A25,A27,A31,TREES_4:3;
then ( r . x ) in ( union ( rng ( coprod X ) ) ) by A32,A33,TARSKI:def 4;
then ( r . x ) in ( Union ( coprod X ) ) by CARD_3:def 4;
hence contradiction by A22,A28,XBOOLE_0:3;
end;
let o1 being (OperSymbol of S);
assume [ o1,(the carrier of S) ] = ( r . x );
hence thesis by A25,A26,A27,A29,ZFMISC_1:27;
end;

assume A34: ( r . x ) in ( Union ( coprod X ) );
now
given o1 being (OperSymbol of S) such that
A35: [ o1,(the carrier of S) ] = ( a . ( {} ) )
and
( the_result_sort_of o1 ) <= s;

(the carrier of S) in { (the carrier of S) } by TARSKI:def 1;
then [ o1,(the carrier of S) ] in [: (the carrier' of S),{ (the carrier of S) } :] by ZFMISC_1:87;
hence contradiction by A22,A25,A27,A34,A35,XBOOLE_0:3;
end;
then consider s1 being (Element of S),y being set such that A36: s1 <= s and A37: y in ( X . s1 ) and A38: a = ( root-tree [ y,s1 ] ) by A26;
take s1;
( r . x ) = [ y,s1 ] by A25,A27,A38,TREES_4:3;
hence thesis by A36,A37,MSAFREE:def 2;
end;
( dom p ) = ( dom ar ) by A20,CKB18:1;
then ( len r ) = ( len ar ) by A1,A21,FINSEQ_1:def 3;
then [ [ o,(the carrier of S) ],r ] in ( OSREL X ) by A23,CKB6:1;
hence thesis by LANG1:def 1;
end;
