environ
vocabularies OSALG_1,MSUALG_2,OSALG_2,MSUALG_1,TARSKI,STRUCT_0,RELAT_1,SEQM_3,PBOOLE,MSUALG_3,REALSET1,ZFMISC_1,XBOOLE_0,CARD_3,MSAFREE,SUBSET_1,FINSEQ_1,MARGREL1,FUNCT_1,XXREAL_0,PARTFUN1,LANG1,TDGROUP,DTCONSTR,TREES_3,TREES_4,NAT_1,TREES_2,OSALG_4,CARD_5,NATTRA_1,CARD_LAR,QC_LANG1,EQREL_1,RELAT_2,MSUALG_4,COH_SP,MCART_1,UNIALG_2,MEMBER_1,FUNCT_7,OSAFREE;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NAT_1,RELAT_1,RELSET_1,FUNCT_1,MCART_1,PARTFUN1,FUNCT_2,FINSEQ_1,FINSEQ_2,PBOOLE,RELAT_2,TREES_2,CARD_3,EQREL_1,STRUCT_0,LANG1,TREES_3,TREES_4,DTCONSTR,ORDERS_2,ORDERS_3,MSUALG_1,MSUALG_2,MSUALG_3,MSUALG_4,OSALG_1,OSALG_2,OSALG_3,OSALG_4,MSAFREE,FUNCT_7,CKB1,CKB3,CKB4,CKB5,CKB7,CKB12,CKB13,CKB15,CKB21,CKB22,CKB23,CKB25,CKB31,CKB32,CKB38,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46;
definitions TARSKI,XBOOLE_0,PBOOLE,MSUALG_3,OSALG_1,OSALG_3,OSALG_4,CKB1,CKB3,CKB4,CKB5,CKB7,CKB12,CKB13,CKB15,CKB21,CKB22,CKB23,CKB31,CKB38,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46;
theorems TARSKI,FUNCT_1,FUNCT_2,MCART_1,ZFMISC_1,PBOOLE,CARD_3,MSUALG_1,MSUALG_2,MSUALG_3,RELAT_1,LANG1,DTCONSTR,FINSEQ_1,TREES_4,TREES_1,DOMAIN_1,RELSET_1,XBOOLE_0,XBOOLE_1,OSALG_1,OSALG_2,OSALG_3,OSALG_4,MSAFREE,MSUALG_6,MSAFREE2,CARD_5,FINSEQ_2,FINSEQ_3,MSUALG_9,MSUALG_4,EQREL_1,FUNCT_5,ORDERS_2,RELAT_2,PARTFUN1,ORDERS_1,FUNCT_7,FUNCOP_1,TREES_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB9,CKB11,CKB12,CKB13,CKB15,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46;
schemes CLASSES1,FUNCT_1,RELSET_1,DTCONSTR,XBOOLE_0,FUNCT_2,PBOOLE;
registrations XBOOLE_0,SUBSET_1,RELAT_1,ORDINAL1,PARTFUN1,FUNCOP_1,FUNCT_1,PBOOLE,TREES_2,TREES_3,STRUCT_0,DTCONSTR,MSUALG_1,MSUALG_3,MSAFREE,MSUALG_4,MSUALG_9,OSALG_1,OSALG_4,RELSET_1,FINSEQ_1,CKB8,CKB10,CKB14,CKB16,CKB24,CKB37,CKB40;
constructors XXREAL_0,NAT_1,FINSEQOP,FUNCT_7,MSUALG_3,MSAFREE,ORDERS_3,OSALG_2,OSALG_3,OSALG_4,RELSET_1,CKB1,CKB3,CKB4,CKB5,CKB7,CKB12,CKB13,CKB15,CKB21,CKB22,CKB23,CKB25,CKB31,CKB38,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46;
requirements BOOLE,SUBSET;
begin
reserve S for OrderSortedSign;
reserve X for (ManySortedSet of S);
reserve o for (OperSymbol of S);
reserve x for set;
definition
let S being OrderSortedSign;
let X being  non-empty (ManySortedSet of S);
let nt being (Symbol of ( DTConOSA X ));
let x being (FinSequence of ( bool [: ( TS ( DTConOSA X ) ),(the carrier of S) :] ));
func @ (nt,x) -> (Subset of [: ( TS ( DTConOSA X ) ),(the carrier of S) :]) equals 
{ [ ( ( Den (o2,( ParsedTermsOSA X )) ) . x2 ),s3 ] where o2 is (OperSymbol of S),x2 is (Element of ( Args (o2,( ParsedTermsOSA X )) )),s3 is (Element of S): ((ex o1 being (OperSymbol of S) st ((((nt = [ o1,(the carrier of S) ] & o1 ~= o2) & ( len ( the_arity_of o1 ) ) = ( len ( the_arity_of o2 ) )) & ( the_result_sort_of o1 ) <= s3) & ( the_result_sort_of o2 ) <= s3)) & (ex w3 being (Element of ( (the carrier of S) * )) st (( dom w3 ) = ( dom x ) & (for y being Nat holds (y in ( dom x ) implies [ ( x2 . y ),( w3 /. y ) ] in ( x . y )))))) };
correctness
proof
set NT = { [ ( ( Den (o2,( ParsedTermsOSA X )) ) . x2 ),s3 ] where o2 is (OperSymbol of S),x2 is (Element of ( Args (o2,( ParsedTermsOSA X )) )),s3 is (Element of S): ((ex o1 being (OperSymbol of S) st ((((nt = [ o1,(the carrier of S) ] & o1 ~= o2) & ( len ( the_arity_of o1 ) ) = ( len ( the_arity_of o2 ) )) & ( the_result_sort_of o1 ) <= s3) & ( the_result_sort_of o2 ) <= s3)) & (ex w3 being (Element of ( (the carrier of S) * )) st (( dom w3 ) = ( dom x ) & (for y being Nat holds (y in ( dom x ) implies [ ( x2 . y ),( w3 /. y ) ] in ( x . y )))))) };
NT c= [: ( TS ( DTConOSA X ) ),(the carrier of S) :]
proof
let y being set;
assume y in NT;
then consider o2 being (OperSymbol of S),x2 being (Element of ( Args (o2,( ParsedTermsOSA X )) )),s3 being (Element of S) such that A1: y = [ ( ( Den (o2,( ParsedTermsOSA X )) ) . x2 ),s3 ] and (ex o1 being (OperSymbol of S) st ((((nt = [ o1,(the carrier of S) ] & o1 ~= o2) & ( len ( the_arity_of o1 ) ) = ( len ( the_arity_of o2 ) )) & ( the_result_sort_of o1 ) <= s3) & ( the_result_sort_of o2 ) <= s3)) and (ex w3 being (Element of ( (the carrier of S) * )) st (( dom w3 ) = ( dom x ) & (for y being Nat holds (y in ( dom x ) implies [ ( x2 . y ),( w3 /. y ) ] in ( x . y )))));
A2: ( OSSym (o2,X) ) ==> ( roots x2 ) by CKB30:1;
A3: x2 is (FinSequence of ( TS ( DTConOSA X ) )) by CKB30:1;
then A4: ( ( OSSym (o2,X) ) -tree x2 ) in ( TS ( DTConOSA X ) ) by A2,CKB29:1;
consider o being (OperSymbol of S) such that A5: ( OSSym (o2,X) ) = [ o,(the carrier of S) ] and x2 in ( Args (o,( ParsedTermsOSA X )) ) and A6: ( ( OSSym (o2,X) ) -tree x2 ) = ( ( Den (o,( ParsedTermsOSA X )) ) . x2 ) and (for s1 being (Element of S) holds (( ( OSSym (o2,X) ) -tree x2 ) in ( (the Sorts of ( ParsedTermsOSA X )) . s1 ) iff ( the_result_sort_of o ) <= s1)) by A3,A2,CKB29:1;
o2 = o by A5,ZFMISC_1:27;
hence thesis by A1,A4,A6,ZFMISC_1:def 2;
end;
hence thesis;
end;
end;
