environ
vocabularies XBOOLE_0,CAT_1,SUBSET_1,FUNCT_1,PARTFUN1,FUNCOP_1,STRUCT_0,FUNCT_6,RELAT_1,GRAPH_1,FUNCT_4,ARYTM_0,FVSUM_1,ALGSTR_0,WELLORD1,TARSKI,CARD_1,CAT_3;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCOP_1,FUNCT_4,NUMBERS,FUNCT_2,STRUCT_0,GRAPH_1,CAT_1,OPPCAT_1,CKB4;
definitions CAT_1,FUNCOP_1;
theorems TARSKI,FUNCT_2,FUNCOP_1,FUNCT_4,CAT_1,OPPCAT_1,RELSET_1,CKB2,CKB5;
schemes FUNCT_2,FUNCT_1,CKB1,CKB3;
registrations XBOOLE_0,RELSET_1,STRUCT_0;
constructors PARTFUN1,OPPCAT_1,FUNCOP_1,RELSET_1,CKB4;
requirements SUBSET,BOOLE;
begin
reserve x1 for set;
reserve x2 for set;
reserve A for non empty set;
theorem
Th7: (x1 <> x2 implies (for y1,y2 being (Element of A) holds (( ( (x1,x2) --> (y1,y2) ) /. x1 ) = y1 & ( ( (x1,x2) --> (y1,y2) ) /. x2 ) = y2)))
proof
assume A1: x1 <> x2;
let y1 being (Element of A),y2 being (Element of A);
set h = ( (x1,x2) --> (y1,y2) );
A2: (( h . x2 ) = y2 & x1 in { x1,x2 }) by FUNCT_4:63,TARSKI:def 2;
A3: x2 in { x1,x2 } by TARSKI:def 2;
( h . x1 ) = y1 by A1,FUNCT_4:63;
hence thesis by A2,A3,FUNCT_2:def 13;
end;
