environ
vocabularies RELAT_2,ALTCAT_1,XBOOLE_0,MSUALG_6,FUNCTOR0,FUNCT_2,FUNCT_1,RELAT_1,CAT_1,ENS_1,PARTFUN1,ZFMISC_1,STRUCT_0,YELLOW18,SETFAM_1,PBOOLE,ALTCAT_2,TARSKI,SUBSET_1,REALSET1,FUNCOP_1,FUNCT_3,MCART_1,MSUALG_3,WELLORD1,ARYTM_0,YELLOW20;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,RELSET_1,FUNCT_1,FUNCT_2,MCART_1,BINOP_1,REALSET1,MULTOP_1,PBOOLE,STRUCT_0,FUNCT_4,PARTFUN1,FUNCOP_1,MSUALG_3,FUNCT_3,ALTCAT_1,ALTCAT_2,FUNCTOR0,FUNCTOR3,YELLOW18,CKB10,CKB14,CKB21,CKB37,CKB38,CKB39;
definitions TARSKI,RELAT_1,PARTFUN1,PBOOLE,MSUALG_3,ALTCAT_1,ALTCAT_2,FUNCTOR0,FUNCT_2,XBOOLE_0,BINOP_1,REALSET1,CKB10,CKB14,CKB21;
theorems ZFMISC_1,RELAT_1,FUNCT_1,PBOOLE,MCART_1,FUNCT_2,FUNCT_3,FUNCT_4,ALTCAT_1,ALTCAT_2,FUNCTOR3,ALTCAT_4,FUNCTOR0,FUNCTOR1,FUNCTOR2,PARTFUN1,MULTOP_1,MSUALG_3,YELLOW18,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB30,CKB34,CKB40,CKB41,CKB42;
schemes FUNCT_1,YELLOW18,CKB29,CKB31,CKB32;
registrations SUBSET_1,RELAT_1,FUNCT_1,FUNCOP_1,PBOOLE,STRUCT_0,ALTCAT_2,FUNCTOR0,FUNCTOR2,ALTCAT_4,YELLOW18,RELSET_1,CKB33,CKB35,CKB36;
constructors REALSET1,MSUALG_3,FUNCTOR3,YELLOW18,RELSET_1,CKB10,CKB14,CKB21,CKB37,CKB38,CKB39;
requirements SUBSET,BOOLE;
begin
theorem
Th32: (for A,B being non  empty AltGraph holds (for F being BimapStr over A,B holds (F is  Covariant  one-to-one implies (for a,b being (object of A) holds (( F . a ) = ( F . b ) implies a = b)))))
proof
let A being non  empty AltGraph;
let B being non  empty AltGraph;
let F being BimapStr over A,B;
given f being (Function of (the carrier of A),(the carrier of B)) such that
A1: (the ObjectMap of F) = [: f,f :];

assume (the ObjectMap of F) is  one-to-one;
then A2: f is  one-to-one by A1,FUNCTOR0:7;
let a being (object of A);
let b being (object of A);
assume that
A3: ( F . a ) = ( F . b );
A4: (( [ ( f . a ),( f . a ) ] `1 ) = ( f . a ) & ( [ ( f . b ),( f . b ) ] `1 ) = ( f . b )) by MCART_1:7;
(( (the ObjectMap of F) . (a,a) ) = [ ( f . a ),( f . a ) ] & ( (the ObjectMap of F) . (b,b) ) = [ ( f . b ),( f . b ) ]) by A1,FUNCT_3:75;
hence thesis by A2,A3,A4,FUNCT_2:19;
end;
