environ
vocabularies XBOOLE_0,SUBSET_1,TARSKI,ZFMISC_1,RELAT_1,FUNCT_1,MCART_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1;
definitions TARSKI,XBOOLE_0,RELAT_1;
theorems TARSKI,XBOOLE_0,ZFMISC_1,ENUMSET1,ORDINAL1,XBOOLE_1,FUNCT_1,RELAT_1,CKB1;
schemes XBOOLE_0,FUNCT_1;
registrations XBOOLE_0,RELAT_1;
constructors TARSKI,ENUMSET1,SUBSET_1,FUNCT_1;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve Y1 for set;
reserve Z for set;
theorem
Th2: (X <> ( {} ) implies (ex Y st (Y in X & (for Y1 holds (Y1 in Y implies Y1 misses X)))))
proof
defpred P[ set ]
 means
$1 meets X;
consider Z such that A1: (for Y holds (Y in Z iff (Y in ( union X ) & P[ Y ]))) from XBOOLE_0:sch 1;
assume X <> ( {} );
then consider Y such that A2: Y in ( X \/ Z ) and A3: Y misses ( X \/ Z ) by CKB1:1;
assume A4: (not thesis);
now
assume A5: Y in X;
then consider Y1 such that A6: Y1 in Y and A7: (not Y1 misses X) by A4;
Y1 in ( union X ) by A5,A6,TARSKI:def 4;
then Y1 in Z by A1,A7;
then Y1 in ( X \/ Z ) by XBOOLE_0:def 3;
hence contradiction by A3,A6,XBOOLE_0:3;
end;
then Y in Z by A2,XBOOLE_0:def 3;
then Y meets X by A1;
hence contradiction by A3,XBOOLE_1:70;
end;
