environ
vocabularies XBOOLE_0,SUBSET_1,TARSKI,ZFMISC_1,RELAT_1,FUNCT_1,MCART_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1;
definitions TARSKI,XBOOLE_0,RELAT_1;
theorems TARSKI,XBOOLE_0,ZFMISC_1,ENUMSET1,ORDINAL1,XBOOLE_1,FUNCT_1,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5;
schemes XBOOLE_0,FUNCT_1;
registrations XBOOLE_0,RELAT_1;
constructors TARSKI,ENUMSET1,SUBSET_1,FUNCT_1;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve Y1 for set;
reserve Y2 for set;
reserve Y3 for set;
reserve Y4 for set;
reserve Y5 for set;
reserve Z1 for set;
reserve Z2 for set;
reserve Z3 for set;
reserve Z4 for set;
reserve Z5 for set;
theorem
Th6: (X <> ( {} ) implies (ex Y st (Y in X & (for Y1 holds (for Y2 holds (for Y3 holds (for Y4 holds (for Y5 holds (((((Y1 in Y2 & Y2 in Y3) & Y3 in Y4) & Y4 in Y5) & Y5 in Y) implies Y1 misses X)))))))))
proof
defpred P[ set ]
 means
(ex Y1 st (ex Y2 st (ex Y3 st (ex Y4 st ((((Y1 in Y2 & Y2 in Y3) & Y3 in Y4) & Y4 in $1) & Y1 meets X)))));
consider Z1 such that A1: (for Y holds (Y in Z1 iff (Y in ( union X ) & P[ Y ]))) from XBOOLE_0:sch 1;
defpred T[ set ]
 means
$1 meets X;
defpred S[ set ]
 means
(ex Y1 st (Y1 in $1 & Y1 meets X));
defpred R[ set ]
 means
(ex Y1 st (ex Y2 st ((Y1 in Y2 & Y2 in $1) & Y1 meets X)));
defpred Q[ set ]
 means
(ex Y1 st (ex Y2 st (ex Y3 st (((Y1 in Y2 & Y2 in Y3) & Y3 in $1) & Y1 meets X))));
consider Z2 such that A2: (for Y holds (Y in Z2 iff (Y in ( union ( union X ) ) & Q[ Y ]))) from XBOOLE_0:sch 1;
consider Z5 such that A3: (for Y holds (Y in Z5 iff (Y in ( union ( union ( union ( union ( union X ) ) ) ) ) & T[ Y ]))) from XBOOLE_0:sch 1;
consider Z3 such that A4: (for Y holds (Y in Z3 iff (Y in ( union ( union ( union X ) ) ) & R[ Y ]))) from XBOOLE_0:sch 1;
consider Z4 such that A5: (for Y holds (Y in Z4 iff (Y in ( union ( union ( union ( union X ) ) ) ) & S[ Y ]))) from XBOOLE_0:sch 1;
set V = ( ( ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) \/ Z4 ) \/ Z5 );
assume X <> ( {} );
then consider Y such that A6: Y in V and A7: Y misses V by CKB1:1;
A8: V = ( ( ( ( X \/ ( Z1 \/ Z2 ) ) \/ Z3 ) \/ Z4 ) \/ Z5 ) by XBOOLE_1:4
.= ( ( ( X \/ ( ( Z1 \/ Z2 ) \/ Z3 ) ) \/ Z4 ) \/ Z5 ) by XBOOLE_1:4
.= ( ( X \/ ( ( ( Z1 \/ Z2 ) \/ Z3 ) \/ Z4 ) ) \/ Z5 ) by XBOOLE_1:4
.= ( X \/ ( ( ( ( Z1 \/ Z2 ) \/ Z3 ) \/ Z4 ) \/ Z5 ) ) by XBOOLE_1:4;
A9:now
assume A10: Y in Z1;
then consider Y1,Y2,Y3,Y4 such that A11: ((Y1 in Y2 & Y2 in Y3) & Y3 in Y4) and A12: Y4 in Y and A13: Y1 meets X by A1;
Y in ( union X ) by A1,A10;
then Y4 in ( union ( union X ) ) by A12,TARSKI:def 4;
then Y4 in Z2 by A2,A11,A13;
then Y4 in ( ( X \/ Z1 ) \/ Z2 ) by XBOOLE_0:def 3;
then Y meets ( ( X \/ Z1 ) \/ Z2 ) by A12,XBOOLE_0:3;
then Y meets ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) by XBOOLE_1:70;
then Y meets ( ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) \/ Z4 ) by XBOOLE_1:70;
hence contradiction by A7,XBOOLE_1:70;
end;
A14:now
assume A15: Y in Z2;
then consider Y1,Y2,Y3 such that A16: (Y1 in Y2 & Y2 in Y3) and A17: Y3 in Y and A18: Y1 meets X by A2;
Y in ( union ( union X ) ) by A2,A15;
then Y3 in ( union ( union ( union X ) ) ) by A17,TARSKI:def 4;
then Y3 in Z3 by A4,A16,A18;
then Y3 in ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) by XBOOLE_0:def 3;
then Y3 in ( ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) \/ Z4 ) by XBOOLE_0:def 3;
then Y3 in V by XBOOLE_0:def 3;
hence contradiction by A7,A17,XBOOLE_0:3;
end;
A19:now
assume A20: Y in Z3;
then consider Y1,Y2 such that A21: Y1 in Y2 and A22: Y2 in Y and A23: Y1 meets X by A4;
Y in ( union ( union ( union X ) ) ) by A4,A20;
then Y2 in ( union ( union ( union ( union X ) ) ) ) by A22,TARSKI:def 4;
then Y2 in Z4 by A5,A21,A23;
then Y2 in ( ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) \/ Z4 ) by XBOOLE_0:def 3;
then Y2 in V by XBOOLE_0:def 3;
hence contradiction by A7,A22,XBOOLE_0:3;
end;
A24:now
assume A25: Y in Z4;
then consider Y1 such that A26: Y1 in Y and A27: Y1 meets X by A5;
Y in ( union ( union ( union ( union X ) ) ) ) by A5,A25;
then Y1 in ( union ( union ( union ( union ( union X ) ) ) ) ) by A26,TARSKI:def 4;
then Y1 in Z5 by A3,A27;
then Y1 in V by XBOOLE_0:def 3;
hence contradiction by A7,A26,XBOOLE_0:3;
end;
assume A28: (not thesis);
now
assume A29: Y in X;
then consider Y1,Y2,Y3,Y4,Y5 such that A30: (((Y1 in Y2 & Y2 in Y3) & Y3 in Y4) & Y4 in Y5) and A31: Y5 in Y and A32: (not Y1 misses X) by A28;
Y5 in ( union X ) by A29,A31,TARSKI:def 4;
then Y5 in Z1 by A1,A30,A32;
then Y5 in ( X \/ Z1 ) by XBOOLE_0:def 3;
then Y5 in ( ( X \/ Z1 ) \/ Z2 ) by XBOOLE_0:def 3;
then Y5 in ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) by XBOOLE_0:def 3;
then Y meets ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) by A31,XBOOLE_0:3;
then Y meets ( ( ( ( X \/ Z1 ) \/ Z2 ) \/ Z3 ) \/ Z4 ) by XBOOLE_1:70;
hence contradiction by A7,XBOOLE_1:70;
end;
then Y in ( ( ( ( Z1 \/ Z2 ) \/ Z3 ) \/ Z4 ) \/ Z5 ) by A8,A6,XBOOLE_0:def 3;
then Y in ( ( ( Z1 \/ ( Z2 \/ Z3 ) ) \/ Z4 ) \/ Z5 ) by XBOOLE_1:4;
then Y in ( ( Z1 \/ ( ( Z2 \/ Z3 ) \/ Z4 ) ) \/ Z5 ) by XBOOLE_1:4;
then Y in ( Z1 \/ ( ( ( Z2 \/ Z3 ) \/ Z4 ) \/ Z5 ) ) by XBOOLE_1:4;
then Y in ( ( ( Z2 \/ Z3 ) \/ Z4 ) \/ Z5 ) by A9,XBOOLE_0:def 3;
then Y in ( ( Z2 \/ ( Z3 \/ Z4 ) ) \/ Z5 ) by XBOOLE_1:4;
then Y in ( Z2 \/ ( ( Z3 \/ Z4 ) \/ Z5 ) ) by XBOOLE_1:4;
then Y in ( ( Z3 \/ Z4 ) \/ Z5 ) by A14,XBOOLE_0:def 3;
then Y in ( Z3 \/ ( Z4 \/ Z5 ) ) by XBOOLE_1:4;
then Y in ( Z4 \/ Z5 ) by A19,XBOOLE_0:def 3;
then Y in Z5 by A24,XBOOLE_0:def 3;
then Y meets X by A3;
hence contradiction by A8,A7,XBOOLE_1:70;
end;
