environ
vocabularies STRUCT_0,RELAT_1,TARSKI,ZFMISC_1,XBOOLE_0,SYSREL,E_SIEC;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,SYSREL,STRUCT_0,CKB1,CKB2,CKB4,CKB5,CKB8,CKB14,CKB15,CKB16,CKB19,CKB20,CKB24,CKB31,CKB32,CKB35;
definitions STRUCT_0,CKB2,CKB5,CKB14,CKB15,CKB16,CKB19,CKB20,CKB24,CKB31,CKB32,CKB35;
theorems ZFMISC_1,RELAT_1,SYSREL,RELSET_1,XBOOLE_0,XBOOLE_1,CKB2,CKB5,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35;
registrations XBOOLE_0,RELAT_1,CKB1,CKB3,CKB6,CKB7;
constructors SYSREL,STRUCT_0,CKB1,CKB2,CKB5,CKB14,CKB15,CKB16,CKB19,CKB20,CKB24,CKB31,CKB32,CKB35;
requirements SUBSET,BOOLE;
begin
reserve N for e_net;
theorem
( e_Flow N ) c= ( [: ( e_Places N ),( e_Transitions N ) :] \/ [: ( e_Transitions N ),( e_Places N ) :] )
proof
A1: ( ( (the entrance of N) ~ ) \ ( id N ) ) = ( ( (the entrance of N) ~ ) \ ( ( id (the carrier of N) ) ~ ) ) by RELAT_1:46
.= ( ( (the entrance of N) \ ( id (the carrier of N) ) ) ~ ) by RELAT_1:24;
A2: (( e_Flow N ) = ( ( ( (the entrance of N) ~ ) \ ( id (the carrier of N) ) ) \/ ( (the escape of N) \ ( id (the carrier of N) ) ) ) & ( (the escape of N) \ ( id (the carrier of N) ) ) c= [: ( e_Transitions N ),( e_Places N ) :]) by CKB34:1,XBOOLE_1:42;
( (the entrance of N) \ ( id (the carrier of N) ) ) c= [: ( e_Transitions N ),( e_Places N ) :] by CKB34:1;
then ( ( (the entrance of N) ~ ) \ ( id (the carrier of N) ) ) c= [: ( e_Places N ),( e_Transitions N ) :] by A1,SYSREL:4;
hence thesis by A2,XBOOLE_1:13;
end;
