environ
vocabularies NUMBERS,REAL_1,SUBSET_1,RCOMP_1,PARTFUN1,NAT_1,FUNCT_1,RELAT_1,XBOOLE_0,ARYTM_1,VALUED_1,TARSKI,XXREAL_0,PREPOWER,ORDINAL4,CARD_1,NEWTON,ARYTM_3,FDIFF_1,SIN_COS,ABIAN,SQUARE_1,REALSET1,TAYLOR_1,TAYLOR_2,XXREAL_1,COMPLEX1,FUNCOP_1;
notations SUBSET_1,PARTFUN1,RCOMP_1,XXREAL_0,NUMBERS,COMPLEX1,FUNCT_2,FUNCOP_1,REAL_1,NAT_1,NAT_D,VALUED_1,SEQ_1,TAYLOR_2,FDIFF_1,SEQFUNC,NEWTON,SIN_COS,TAYLOR_1,ABIAN,XBOOLE_0,TARSKI,PREPOWER,RFUNCT_1,SQUARE_1,RELSET_1;
definitions TAYLOR_1,VALUED_1,FDIFF_1,TARSKI,SQUARE_1,XBOOLE_0;
theorems RFUNCT_1,XBOOLE_0,NEWTON,XCMPLX_1,FUNCT_1,XBOOLE_1,ABSVALUE,PARTFUN1,RELAT_1,RCOMP_1,SIN_COS,NAT_1,FDIFF_1,FDIFF_2,TAYLOR_1,SIN_COS2,XREAL_1,ABIAN,XXREAL_0,TAYLOR_2,INT_1,WSIERP_1,FUNCT_2,TARSKI,XCMPLX_0,VALUED_1,PREPOWER,ZFMISC_1,FDIFF_7,FDIFF_8,FDIFF_4,FUNCOP_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37;
schemes NAT_1;
registrations RELSET_1,NUMBERS,XXREAL_0,NAT_1,MEMBERED,VALUED_0,RCOMP_1,FUNCT_1,INT_1,ORDINAL1,FUNCT_2;
constructors REAL_1,NAT_1,RCOMP_1,LIMFUNC1,TAYLOR_2,FDIFF_1,SIN_COS,ABIAN,TAYLOR_1,RFUNCT_1,SQUARE_1,PREPOWER,BINARITH,PARTFUN2,SEQ_1,VALUED_1,BINOP_2,NAT_D,SEQFUNC,RELSET_1,NEWTON;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve x for Real;
reserve m for (Element of ( NAT ));
reserve Z for  open (Subset of ( REAL ));
theorem
Th37: (x in Z implies ( ( ( diff (( #Z m ),Z) ) . m ) . x ) = ( m ! ))
proof
assume A1: x in Z;
per cases ;
suppose m > ( 0 );

then ( 0 ) < ( ( 0 ) + m );
then 1 <= m by NAT_1:19;
then reconsider n = ( m - 1 ) as (Element of ( NAT )) by INT_1:5;
A2: ( ( 0 ) + n ) < ( n + 1 ) by XREAL_1:6;
A3: ( n ! ) <> ( 0 ) by NEWTON:17;
A4: ( #Z 1 ) is_differentiable_on Z by CKB8:1,FDIFF_1:26;
then A5: ( ( ( n + 1 ) ! ) (#) ( #Z 1 ) ) is_differentiable_on Z by FDIFF_2:19;
Z c= ( dom ( #Z 1 ) ) by A4,FDIFF_1:def 6;
then A6: Z c= ( dom ( ( ( n + 1 ) ! ) (#) ( #Z 1 ) ) ) by VALUED_1:def 5;
( ( ( diff (( #Z m ),Z) ) . m ) . x ) = ( ( ( ( diff (( #Z ( n + 1 ) ),Z) ) . n ) `| Z ) . x ) by TAYLOR_1:def 5
.= ( ( ( ( ( ( ( n + 1 ) choose n ) * ( n ! ) ) (#) ( #Z ( ( n + 1 ) - n ) ) ) | Z ) `| Z ) . x ) by A2,CKB33:1
.= ( ( ( ( ( ( ( ( n + 1 ) ! ) / ( ( n ! ) * 1 ) ) * ( n ! ) ) (#) ( #Z ( ( n + 1 ) - n ) ) ) | Z ) `| Z ) . x ) by A2,NEWTON:13,NEWTON:def 3
.= ( ( ( ( ( ( ( n + 1 ) ! ) / 1 ) (#) ( #Z 1 ) ) | Z ) `| Z ) . x ) by A3,XCMPLX_1:92
.= ( ( ( ( ( n + 1 ) ! ) (#) ( #Z 1 ) ) `| Z ) . x ) by A5,FDIFF_2:16
.= ( ( ( n + 1 ) ! ) * ( diff (( #Z 1 ),x) ) ) by A1,A4,A6,FDIFF_1:20
.= ( ( ( n + 1 ) ! ) * ( 1 * ( x #Z ( 1 - 1 ) ) ) ) by TAYLOR_1:2
.= ( ( ( n + 1 ) ! ) * 1 ) by PREPOWER:34
.= ( m ! );
hence thesis;
end;
suppose A7: m = ( 0 );

then ( ( ( diff (( #Z m ),Z) ) . m ) . x ) = ( ( ( #Z ( 0 ) ) | Z ) . x ) by TAYLOR_1:def 5
.= ( ( #Z ( 0 ) ) . x ) by A1,FUNCT_1:49
.= ( x #Z ( 0 ) ) by TAYLOR_1:def 1
.= ( m ! ) by A7,NEWTON:12,PREPOWER:34;
hence thesis;
end;
end;
