environ
vocabularies NUMBERS,REAL_1,SUBSET_1,RCOMP_1,PARTFUN1,NAT_1,FUNCT_1,RELAT_1,XBOOLE_0,ARYTM_1,VALUED_1,TARSKI,XXREAL_0,PREPOWER,ORDINAL4,CARD_1,NEWTON,ARYTM_3,FDIFF_1,SIN_COS,ABIAN,SQUARE_1,REALSET1,TAYLOR_1,TAYLOR_2,XXREAL_1,COMPLEX1,FUNCOP_1;
notations SUBSET_1,PARTFUN1,RCOMP_1,XXREAL_0,NUMBERS,COMPLEX1,FUNCT_2,FUNCOP_1,REAL_1,NAT_1,NAT_D,VALUED_1,SEQ_1,TAYLOR_2,FDIFF_1,SEQFUNC,NEWTON,SIN_COS,TAYLOR_1,ABIAN,XBOOLE_0,TARSKI,PREPOWER,RFUNCT_1,SQUARE_1,RELSET_1;
definitions TAYLOR_1,VALUED_1,FDIFF_1,TARSKI,SQUARE_1,XBOOLE_0;
theorems RFUNCT_1,XBOOLE_0,NEWTON,XCMPLX_1,FUNCT_1,XBOOLE_1,ABSVALUE,PARTFUN1,RELAT_1,RCOMP_1,SIN_COS,NAT_1,FDIFF_1,FDIFF_2,TAYLOR_1,SIN_COS2,XREAL_1,ABIAN,XXREAL_0,TAYLOR_2,INT_1,WSIERP_1,FUNCT_2,TARSKI,XCMPLX_0,VALUED_1,PREPOWER,ZFMISC_1,FDIFF_7,FDIFF_8,FDIFF_4,FUNCOP_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63;
schemes NAT_1;
registrations RELSET_1,NUMBERS,XXREAL_0,NAT_1,MEMBERED,VALUED_0,RCOMP_1,FUNCT_1,INT_1,ORDINAL1,FUNCT_2;
constructors REAL_1,NAT_1,RCOMP_1,LIMFUNC1,TAYLOR_2,FDIFF_1,SIN_COS,ABIAN,TAYLOR_1,RFUNCT_1,SQUARE_1,PREPOWER,BINARITH,PARTFUN2,SEQ_1,VALUED_1,BINOP_2,NAT_D,SEQFUNC,RELSET_1,NEWTON;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve x for Real;
reserve Z for  open (Subset of ( REAL ));
theorem
( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . 2 ) = ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) )
proof
A1: (( sin ) is_differentiable_on 2,Z & ( exp_R ) is_differentiable_on 2,Z) by TAYLOR_2:10,TAYLOR_2:21;
A2: ( dom ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) = ( dom ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) by VALUED_1:def 5
.= ( ( dom ( ( exp_R ) (#) ( cos ) ) ) /\ Z ) by RELAT_1:61
.= ( ( ( REAL ) /\ ( REAL ) ) /\ Z ) by SIN_COS:24,SIN_COS:47,VALUED_1:def 4
.= Z by XBOOLE_1:28;
A3: ( exp_R ) is_differentiable_on Z by FDIFF_1:26,TAYLOR_1:16;
( cos ) is_differentiable_on Z by FDIFF_1:26,SIN_COS:67;
then ( ( cos ) | Z ) is_differentiable_on Z by FDIFF_2:16;
then A4: ( ( exp_R ) (#) ( ( cos ) | Z ) ) is_differentiable_on Z by A3,FDIFF_2:20;
A5: ( sin ) is_differentiable_on Z by FDIFF_1:26,SIN_COS:68;
then A6: ( ( exp_R ) (#) ( sin ) ) is_differentiable_on Z by A3,FDIFF_2:20;
( ( exp_R ) | Z ) is_differentiable_on Z by A3,FDIFF_2:16;
then ( ( ( exp_R ) | Z ) (#) ( sin ) ) is_differentiable_on Z by A5,FDIFF_2:20;
then A7: ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( ( exp_R ) (#) ( ( cos ) | Z ) ) ) is_differentiable_on Z by A4,FDIFF_2:17;
A8: ( dom ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . 2 ) ) = ( dom ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . ( 1 + 1 ) ) )
.= ( dom ( ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . ( 1 + ( 0 ) ) ) `| Z ) ) by TAYLOR_1:def 5
.= ( dom ( ( ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . ( 0 ) ) `| Z ) `| Z ) ) by TAYLOR_1:def 5
.= ( dom ( ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) `| Z ) `| Z ) ) by TAYLOR_1:def 5
.= ( dom ( ( ( ( exp_R ) (#) ( sin ) ) `| Z ) `| Z ) ) by A6,FDIFF_2:16
.= ( dom ( ( ( ( ( exp_R ) `| Z ) (#) ( sin ) ) + ( ( exp_R ) (#) ( ( sin ) `| Z ) ) ) `| Z ) ) by A3,A5,FDIFF_2:20
.= ( dom ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( ( exp_R ) (#) ( ( sin ) `| Z ) ) ) `| Z ) ) by TAYLOR_2:5
.= ( dom ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( ( exp_R ) (#) ( ( cos ) | Z ) ) ) `| Z ) ) by TAYLOR_2:17
.= Z by A7,FDIFF_1:def 7;
A9: ( dom ( ( 0 ) (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) ) = ( dom ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) by VALUED_1:def 5
.= ( ( dom ( ( exp_R ) (#) ( sin ) ) ) /\ Z ) by RELAT_1:61
.= ( ( ( REAL ) /\ ( REAL ) ) /\ Z ) by SIN_COS:24,SIN_COS:47,VALUED_1:def 4
.= Z by XBOOLE_1:28;
then A10: ( dom ( ( ( 0 ) (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) ) = ( Z /\ Z ) by A2,VALUED_1:def 1
.= Z;
(for x holds (x in ( dom ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . 2 ) ) implies ( ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . 2 ) . x ) = ( ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) . x )))
proof
let x;
assume A11: x in ( dom ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . 2 ) );
( ( ( diff (( ( exp_R ) (#) ( sin ) ),Z) ) . 2 ) . x ) = ( ( ( ( ( ( diff (( exp_R ),Z) ) . 2 ) (#) ( sin ) ) + ( 2 (#) ( ( ( exp_R ) `| Z ) (#) ( ( sin ) `| Z ) ) ) ) + ( ( exp_R ) (#) ( ( diff (( sin ),Z) ) . 2 ) ) ) . x ) by A1,CKB52:1
.= ( ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( 2 (#) ( ( ( exp_R ) `| Z ) (#) ( ( sin ) `| Z ) ) ) ) + ( ( exp_R ) (#) ( ( diff (( sin ),Z) ) . 2 ) ) ) . x ) by TAYLOR_2:6
.= ( ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( 2 (#) ( ( ( exp_R ) | Z ) (#) ( ( sin ) `| Z ) ) ) ) + ( ( exp_R ) (#) ( ( diff (( sin ),Z) ) . 2 ) ) ) . x ) by TAYLOR_2:5
.= ( ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( 2 (#) ( ( ( exp_R ) | Z ) (#) ( ( cos ) | Z ) ) ) ) + ( ( exp_R ) (#) ( ( diff (( sin ),Z) ) . ( 2 * 1 ) ) ) ) . x ) by TAYLOR_2:17
.= ( ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( 2 (#) ( ( ( exp_R ) | Z ) (#) ( ( cos ) | Z ) ) ) ) + ( ( exp_R ) (#) ( ( ( - 1 ) |^ 1 ) (#) ( ( sin ) | Z ) ) ) ) . x ) by TAYLOR_2:19
.= ( ( ( ( ( ( exp_R ) | Z ) (#) ( sin ) ) + ( 2 (#) ( ( ( exp_R ) | Z ) (#) ( ( cos ) | Z ) ) ) ) + ( ( exp_R ) (#) ( ( - 1 ) (#) ( ( sin ) | Z ) ) ) ) . x ) by NEWTON:5
.= ( ( ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) + ( 2 (#) ( ( ( exp_R ) | Z ) (#) ( ( cos ) | Z ) ) ) ) + ( ( exp_R ) (#) ( ( - 1 ) (#) ( ( sin ) | Z ) ) ) ) . x ) by RFUNCT_1:45
.= ( ( ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) + ( ( exp_R ) (#) ( ( - 1 ) (#) ( ( sin ) | Z ) ) ) ) . x ) by RFUNCT_1:45
.= ( ( ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) + ( ( exp_R ) (#) ( ( - 1 ) (#) ( ( sin ) | Z ) ) ) ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) . x ) by RFUNCT_1:8
.= ( ( ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) + ( ( - 1 ) (#) ( ( exp_R ) (#) ( ( sin ) | Z ) ) ) ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) . x ) by RFUNCT_1:13
.= ( ( ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) + ( ( - 1 ) (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) . x ) by RFUNCT_1:45
.= ( ( ( ( 1 (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) + ( ( - 1 ) (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) . x ) by RFUNCT_1:21
.= ( ( ( ( 1 + ( - 1 ) ) (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) + ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) ) . x ) by CKB5:1
.= ( ( ( ( 0 ) (#) ( ( ( exp_R ) (#) ( sin ) ) | Z ) ) . x ) + ( ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) . x ) ) by A10,A8,A11,VALUED_1:def 1
.= ( ( ( 0 ) * ( ( ( ( exp_R ) (#) ( sin ) ) | Z ) . x ) ) + ( ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) . x ) ) by A9,A8,A11,VALUED_1:def 5
.= ( ( 2 (#) ( ( ( exp_R ) (#) ( cos ) ) | Z ) ) . x );
hence thesis;
end;
hence thesis by A2,A8,PARTFUN1:5;
end;
