environ
vocabularies INCPROJ,INCSP_1,SUBSET_1,AFF_2,ZFMISC_1,VECTSP_1,ANALOAF,PARTFUN1,RELAT_1,TARSKI,FUNCT_1,PROJRED1;
notations TARSKI,ZFMISC_1,SUBSET_1,DOMAIN_1,RELAT_1,RELSET_1,INCSP_1,INCPROJ,PARTFUN1,FUNCT_1;
definitions TARSKI;
theorems TARSKI,PARTFUN1,INCPROJ,FUNCT_1,RELAT_1,RELSET_1,XBOOLE_0,ZFMISC_1,INCSP_1,CKB1,CKB2,CKB3,CKB4;
schemes PARTFUN1,XBOOLE_0;
registrations FUNCT_1,RELSET_1,INCPROJ;
constructors DOMAIN_1,INCPROJ,RELSET_1;
requirements SUBSET,BOOLE;
begin
reserve IPP for IncProjSp;
reserve a for (POINT of IPP);
reserve A for (LINE of IPP);
reserve B for (LINE of IPP);
reserve C for (LINE of IPP);
reserve Q for (LINE of IPP);
theorem
(ex A st (ex B st (ex C st (((((a on A & a on B) & a on C) & A <> B) & B <> C) & C <> A))))
proof
consider Q such that A1: (not a on Q) by CKB2:1;
consider b1 being (Element of (the Points of IPP)),b2 being (Element of (the Points of IPP)),b3 being (Element of (the Points of IPP)) such that A2: b1 <> b2 and A3: b2 <> b3 and A4: b3 <> b1 and A5: b1 on Q and A6: b2 on Q and A7: b3 on Q by INCPROJ:def 7;
consider B1 being (LINE of IPP) such that A8: (a on B1 & b1 on B1) by INCPROJ:def 5;
A9: (not b3 on B1) by A1,A4,A5,A7,A8,INCPROJ:def 4;
consider B2 being (LINE of IPP) such that A10: (a on B2 & b2 on B2) by INCPROJ:def 5;
consider B3 being (Element of (the Lines of IPP)) such that A11: (a on B3 & b3 on B3) by INCPROJ:def 5;
A12: (not b2 on B3) by A1,A3,A6,A7,A11,INCPROJ:def 4;
(not b1 on B2) by A1,A2,A5,A6,A10,INCPROJ:def 4;
hence thesis by A8,A10,A11,A12,A9;
end;
