environ
vocabularies NUMBERS,XBOOLE_0,PROB_1,MEASURE1,PARTFUN1,REAL_1,XREAL_0,ORDINAL1,SUBSET_1,SEQFUNC,MEASURE6,RELAT_1,FUNCT_1,PBOOLE,TARSKI,SEQ_1,ORDINAL2,RINFSUP1,MESFUNC8,CARD_1,NAT_1,MESFUNC1,ARYTM_3,SEQ_2,XXREAL_0,XXREAL_2,SETFAM_1,COMSEQ_1,COMPLEX1,VALUED_1,SUPINF_2,POWER,ARYTM_1,MESFUNC5,INTEGRA5,MESFUNC2,FINSEQ_1,MESFUNC3,INT_1,ZFMISC_1,XCMPLX_0;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,COMPLEX1,XXREAL_0,XREAL_0,XXREAL_2,REAL_1,NAT_1,NAT_D,PROB_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FINSEQ_1,RFUNCT_3,VALUED_1,FUNCT_2,SETFAM_1,SUPINF_1,SUPINF_2,SEQ_1,SEQ_2,SEQFUNC,COMSEQ_1,COMSEQ_2,RINFSUP1,RINFSUP2,MEASURE1,MEASURE6,EXTREAL1,MESFUNC1,MESFUNC2,MESFUNC5,MESFUNC6,COMSEQ_3,MESFUN6C,MESFUNC8,SEQ_4,COMPLSP2,CKB1,CKB4,CKB6,CKB8,CKB10,CKB19,CKB21,CKB23,CKB33,CKB34,CKB35,CKB37;
definitions MESFUNC5,MEASURE6,COMPLEX1,RINFSUP2,TARSKI,XBOOLE_0,FINSEQ_1,COMPLSP2,XXREAL_3,CKB1,CKB4,CKB6,CKB8,CKB10,CKB19,CKB21,CKB23,CKB33,CKB34,CKB35,CKB37;
theorems MEASURE1,TARSKI,PARTFUN1,FUNCT_1,EXTREAL1,MESFUNC1,NAT_1,XBOOLE_0,XBOOLE_1,XCMPLX_0,XREAL_1,MESFUNC5,XXREAL_0,VALUED_1,MESFUNC6,COMPLEX1,RELAT_1,SQUARE_1,FINSEQ_1,MESFUN6C,ORDINAL1,FUNCT_2,SEQFUNC,SETFAM_1,RINFSUP1,MESFUNC7,MESFUNC8,COMSEQ_3,MESFUNC3,NUMBERS,RINFSUP2,XXREAL_2,COMPLSP2,NAT_D,FINSEQ_2,NAT_2,FINSEQ_3,RELSET_1,XXREAL_3,CKB1,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB37,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52;
schemes FUNCT_2,PARTFUN2,FINSEQ_1;
registrations NAT_1,MESFUNC8,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,VALUED_0,XCMPLX_0,PARTFUN1,FUNCT_2,RELAT_1,SEQ_2,COMSEQ_3,RELSET_1,FINSEQ_1,CKB3,CKB13,CKB36,CKB38;
constructors REAL_1,NAT_1,SQUARE_1,MEASURE6,EXTREAL1,MESFUNC2,MESFUNC3,MESFUNC5,SEQ_1,MESFUNC6,MESFUN6C,BINOP_2,RINFSUP1,MESFUNC8,COMSEQ_2,COMSEQ_3,SUPINF_1,RINFSUP2,SEQFUNC,SEQ_2,MESFUNC1,FINSEQ_1,COMPLSP2,MATRIX_5,NAT_D,RELSET_1,SEQ_4,CKB1,CKB4,CKB6,CKB8,CKB10,CKB19,CKB21,CKB23,CKB33,CKB34,CKB35,CKB37;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve X for non  empty set;
reserve S for (SigmaField of X);
reserve M for (sigma_Measure of S);
reserve f for (PartFunc of X,( COMPLEX ));
reserve n for  natural number;
reserve E for (Element of S);
theorem
(f is_integrable_on M implies (ex F being (Function of ( NAT ),S) st (((for n being Nat holds ( F . n ) = ( ( dom f ) /\ ( great_eq_dom (|. f .|,( R_EAL ( 1 / ( n + 1 ) ) )) ) )) & ( ( dom f ) \ ( eq_dom (|. f .|,( 0 )) ) ) = ( union ( rng F ) )) & (for n being Nat holds (( F . n ) in S & ( M . ( F . n ) ) < ( +infty ))))))
proof
assume A1: f is_integrable_on M;
then consider E being (Element of S) such that A2: E = ( dom f ) and A3: f is_measurable_on E by CKB52:1;
defpred P[ (Element of ( NAT )),set ]
 means
$2 = ( E /\ ( great_eq_dom (|. f .|,( 1 / ( $1 + 1 ) )) ) );
A4: ( dom |. f .| ) = E by A2,VALUED_1:def 11;
now
let x being set;
reconsider y = ( |. f .| . x ) as Real;
assume A5: x in ( E \ ( eq_dom (|. f .|,( 0 )) ) );
then A6: x in E by XBOOLE_0:def 5;
then A7: x in ( dom |. f .| ) by A2,VALUED_1:def 11;
(not x in ( eq_dom (|. f .|,( 0 )) )) by A5,XBOOLE_0:def 5;
then (not y = ( 0 )) by A7,MESFUNC6:7;
then (not |. ( f . x ) .| = ( 0 )) by A7,VALUED_1:def 11;
then ( f . x ) <> ( 0 ) by COMPLEX1:5,SQUARE_1:17;
then ( 0 ) < |. ( f . x ) .| by COMPLEX1:47;
then ( 0 ) < ( |. f .| . x ) by A7,VALUED_1:def 11;
then x in ( great_dom (|. f .|,( 0 )) ) by A7,MESFUNC1:def 13;
hence x in ( E /\ ( great_dom (|. f .|,( 0 )) ) ) by A6,XBOOLE_0:def 4;
end;
then A8: ( E \ ( eq_dom (|. f .|,( 0 )) ) ) c= ( E /\ ( great_dom (|. f .|,( 0 )) ) ) by TARSKI:def 3;
now
let x being set;
assume A9: x in ( E /\ ( great_dom (|. f .|,( 0 )) ) );
then x in ( great_dom (|. f .|,( 0 )) ) by XBOOLE_0:def 4;
then ( 0 ) < ( |. f .| . x ) by MESFUNC1:def 13;
then A10: (not x in ( eq_dom (|. f .|,( 0 )) )) by MESFUNC1:def 15;
x in E by A9,XBOOLE_0:def 4;
hence x in ( E \ ( eq_dom (|. f .|,( 0 )) ) ) by A10,XBOOLE_0:def 5;
end;
then A11: ( E /\ ( great_dom (|. f .|,( 0 )) ) ) c= ( E \ ( eq_dom (|. f .|,( 0 )) ) ) by TARSKI:def 3;
A12: |. f .| is_measurable_on E by A2,A3,MESFUN6C:30;
A13: (for n being (Element of ( NAT )) holds (ex Z being (Element of S) st P[ n,Z ]))
proof
let n being (Element of ( NAT ));
take ( E /\ ( great_eq_dom (|. f .|,( 1 / ( n + 1 ) )) ) );
thus thesis by A12,A4,MESFUNC6:13;
end;
consider F being (Function of ( NAT ),S) such that A14: (for n being (Element of ( NAT )) holds P[ n,( F . n ) ]) from FUNCT_2:sch 10(A13);
A15: (for n being Nat holds (( F . n ) in S & ( M . ( F . n ) ) < ( +infty )))
proof
|. f .| is_integrable_on M by A1,CKB52:1;
then A16: ( Integral (M,|. f .|) ) < ( +infty ) by MESFUNC6:90;
let n being Nat;
reconsider n1 = n as (Element of ( NAT )) by ORDINAL1:def 12;
set z = ( R_EAL ( 1 / ( n + 1 ) ) );
A17: ( F . n1 ) = ( E /\ ( great_eq_dom (|. f .|,( 1 / ( n1 + 1 ) )) ) ) by A14;
then reconsider En = ( F . n ) as (Element of S);
set h = ( |. f .| | En );
consider nf being (PartFunc of X,( REAL )) such that A18: nf is_simple_func_in S and A19: ( dom nf ) = En and A20: (for x being set holds (x in En implies ( nf . x ) = ( 1 / ( n + 1 ) ))) by MESFUNC6:75;
A21: ( dom h ) = En by A4,A17,RELAT_1:62,XBOOLE_1:17;
A22: ( F . n ) c= ( great_eq_dom (|. f .|,( 1 / ( n + 1 ) )) ) by A17,XBOOLE_1:17;
A23: (for x being (Element of X) holds (x in ( dom nf ) implies ( nf . x ) <= ( h . x )))
proof
let x being (Element of X);
assume A24: x in ( dom nf );
then ( h . x ) = ( |. f .| . x ) by A19,FUNCT_1:49;
then ( 1 / ( n + 1 ) ) <= ( h . x ) by A22,A19,A24,MESFUNC1:def 14;
hence thesis by A19,A20,A24;
end;
( ( dom |. f .| ) /\ En ) = ( E /\ En ) by A2,VALUED_1:def 11;
then A25: ( ( dom |. f .| ) /\ En ) = En by A17,XBOOLE_1:17,XBOOLE_1:28;
|. f .| is_measurable_on En by A12,A17,MESFUNC6:16,XBOOLE_1:17;
then A26: h is_measurable_on En by A25,MESFUNC6:76;
A27: h is  nonnegative by CKB45:1,MESFUNC6:55;
(for x being set holds (x in ( dom nf ) implies ( nf . x ) >= ( 0 ))) by A19,A20;
then A28: nf is  nonnegative by MESFUNC6:52;
(|. f .| is  nonnegative & ( |. f .| | E ) = |. f .|) by A4,CKB45:1,RELAT_1:69;
then A29: ( Integral (M,h) ) <= ( Integral (M,|. f .|) ) by A12,A4,A17,MESFUNC6:87,XBOOLE_1:17;
nf is_measurable_on En by A18,MESFUNC6:50;
then ( Integral (M,nf) ) <= ( Integral (M,h) ) by A21,A26,A27,A19,A28,A23,CKB51:1;
then A30: ( Integral (M,nf) ) <= ( Integral (M,|. f .|) ) by A29,XXREAL_0:2;
A31: (( ( z * ( M . En ) ) / z ) = ( M . En ) & ( ( +infty ) / z ) = ( +infty )) by XXREAL_3:83,XXREAL_3:88;
( Integral (M,nf) ) = ( ( R_EAL ( 1 / ( n + 1 ) ) ) * ( M . En ) ) by A19,A20,MESFUNC6:97;
then ( ( R_EAL ( 1 / ( n + 1 ) ) ) * ( M . En ) ) < ( +infty ) by A16,A30,XXREAL_0:2;
hence thesis by A31,XXREAL_3:80;
end;
take F;
A32: (for n being Nat holds ( F . n ) = ( E /\ ( great_eq_dom (|. f .|,( 1 / ( n + 1 ) )) ) ))
proof
let n being Nat;
n in ( NAT ) by ORDINAL1:def 12;
hence thesis by A14;
end;
then (for n being Nat holds ( F . n ) = ( E /\ ( great_eq_dom (|. f .|,( ( 0 ) + ( 1 / ( n + 1 ) ) )) ) ));
then ( E /\ ( great_dom (|. f .|,( 0 )) ) ) = ( union ( rng F ) ) by MESFUNC6:11;
hence thesis by A2,A32,A11,A8,A15,XBOOLE_0:def 10;
end;
