environ
vocabularies NUMBERS,FINSEQ_1,SUBSET_1,RELAT_1,FUNCT_1,CARD_1,CARD_3,FINSEQ_2,ARYTM_3,ORDINAL4,TARSKI,NAT_1,XXREAL_0,REAL_1,ARYTM_1,XBOOLE_0,ORDINAL1,RLVECT_1,ALGSTR_0,SUPINF_2,PARTFUN1,FINSET_1,FUNCT_2,MCART_1,ZFMISC_1,PRE_POLY,FUNCT_4,FUNCOP_1,VALUED_0,PBOOLE,XREAL_0,SGRAPH1,FINSOP_1,BINOP_1,GROUP_1,STRUCT_0,POLYNOM1,POLYNOM3,AFINSQ_1,MESFUNC1,ALGSEQ_1,VECTSP_1,POLYNOM5,LATTICES,VECTSP_2,COMPLFLD,POLYNOM2,FVSUM_1,MEMBERED,CLASSES1,UPROOTS;
notations TARSKI,XBOOLE_0,XCMPLX_0,XXREAL_0,SUBSET_1,ORDINAL1,CARD_1,NUMBERS,XREAL_0,ZFMISC_1,REAL_1,VECTSP_2,BINOP_1,RELAT_1,FUNCT_1,PBOOLE,RELSET_1,PARTFUN1,FINSEQ_1,FINSEQ_2,DOMAIN_1,FUNCT_2,XXREAL_2,VALUED_0,NAT_1,NAT_D,STRUCT_0,ALGSTR_0,RLVECT_1,VFUNCT_1,VECTSP_1,FINSOP_1,NORMSP_1,GROUP_4,RVSUM_1,ALGSEQ_1,COMPLFLD,BHSP_1,POLYNOM3,POLYNOM4,POLYNOM5,FINSET_1,MCART_1,FUNCT_4,FUNCOP_1,CLASSES1,FVSUM_1,WSIERP_1,MEMBERED,GROUP_1,RECDEF_1,PRE_POLY;
definitions TARSKI,VECTSP_2,FUNCT_1,POLYNOM3,POLYNOM5,FINSEQ_2,RVSUM_1,GROUP_4,RLVECT_1,FUNCOP_1,RELAT_1,STRUCT_0;
theorems GROUP_1,CARD_1,FINSEQ_1,ZFMISC_1,NAT_1,FUNCT_1,FUNCT_2,RELAT_1,TARSKI,XBOOLE_0,XBOOLE_1,VECTSP_1,POLYNOM5,INT_1,AXIOMS,RVSUM_1,FVSUM_1,FINSEQ_3,FINSEQ_2,POLYNOM4,POLYNOM3,FUNCT_7,ALGSEQ_1,RLVECT_1,PBOOLE,FUNCOP_1,MATRIX_3,VECTSP_2,CARD_2,FINSEQ_5,GRAPH_5,BAGORDER,RFINSEQ,WELLORD2,CARD_3,ORDINAL1,FINSOP_1,MONOID_0,INTEGRA1,FUNCT_4,MCART_1,XREAL_1,GROUP_4,XXREAL_0,PARTFUN1,XXREAL_2,NAT_D,FINSEQ_4,CLASSES1,PRE_POLY,TREES_9;
schemes NAT_1,FUNCT_1,FUNCT_2,FRAENKEL,ALGSEQ_1,FINSEQ_1,RECDEF_1,CLASSES1,INT_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCOP_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,BINOP_2,CARD_1,MEMBERED,FINSEQ_1,STRUCT_0,VECTSP_1,COMPLFLD,ALGSTR_1,MONOID_0,PRE_POLY,POLYNOM3,POLYNOM4,POLYNOM5,FINSEQ_2,VALUED_0,XXREAL_2,FUNCT_2,RELSET_1,GROUP_1,VFUNCT_1;
constructors WELLORD2,SETWISEO,REAL_1,FINSEQOP,FINSOP_1,NAT_D,WSIERP_1,VECTSP_2,REALSET2,ALGSTR_1,GROUP_4,BHSP_1,MATRIX_2,MONOID_0,GOBOARD1,POLYNOM2,POLYNOM4,POLYNOM5,SEQ_1,RECDEF_1,BINOP_2,CLASSES1,XXREAL_2,RELSET_1,FUNCT_7,FVSUM_1,VFUNCT_1;
requirements NUMERALS,BOOLE,SUBSET,ARITHM,REAL;
begin
theorem
Th2: (for f being (FinSequence of ( NAT )) holds ((for i being (Element of ( NAT )) holds (i in ( dom f ) implies ( f . i ) <> ( 0 ))) implies (( Sum f ) = ( len f ) iff f = ( ( len f ) |-> 1 ))))
proof
defpred P[ (Element of ( NAT )) ]
 means
(for f being (FinSequence of ( NAT )) holds ((( len f ) = $1 & (for i being (Element of ( NAT )) holds (i in ( dom f ) implies ( f . i ) <> ( 0 )))) implies (( Sum f ) = ( len f ) iff f = ( ( len f ) |-> 1 ))));
let f being (FinSequence of ( NAT ));
A1: (for n being (Element of ( NAT )) holds (P[ n ] implies P[ ( n + 1 ) ]))
proof
let n being (Element of ( NAT ));
assume A2: P[ n ];
let f being (FinSequence of ( NAT ));
assume that
A3: ( len f ) = ( n + 1 )
and
A4: (for i being (Element of ( NAT )) holds (i in ( dom f ) implies ( f . i ) <> ( 0 )));
consider g being (FinSequence of ( NAT )),a being (Element of ( NAT )) such that A5: f = ( g ^ <* a *> ) by A3,FINSEQ_2:19;
A6:now
let i being (Element of ( NAT ));
A7: ( dom g ) c= ( dom f ) by A5,FINSEQ_1:26;
assume A8: i in ( dom g );
then ( f . i ) = ( g . i ) by A5,FINSEQ_1:def 7;
hence ( g . i ) <> ( 0 ) by A4,A8,A7;
end;
( n + 1 ) = ( ( len g ) + ( len <* a *> ) ) by A3,A5,FINSEQ_1:22;
then A9: ( n + 1 ) = ( ( len g ) + 1 ) by FINSEQ_1:40;
then (( dom f ) = ( Seg ( len f ) ) & ( f . ( len f ) ) = a) by A3,A5,FINSEQ_1:42,FINSEQ_1:def 3;
then a <> ( 0 ) by A3,A4,FINSEQ_1:4;
then A10: ( (( 0 ) qua Nat) + 1 ) <= a by NAT_1:13;
A11: g is (FinSequence of ( REAL )) by FINSEQ_2:24;
hereby
reconsider h = ( ( len g ) |-> (1 qua Real) ) as (FinSequence of ( REAL ));
reconsider h1 = h as (Element of ( ( len h ) -tuples_on ( REAL ) )) by FINSEQ_2:92;
reconsider g1 = g as (Element of ( ( len g ) -tuples_on ( REAL ) )) by A11,FINSEQ_2:92;
assume A12: ( Sum f ) = ( len f );
A13: ( Sum g ) = ( ( ( Sum g ) + a ) - a )
.= ( ( n + 1 ) - a ) by A3,A5,A12,RVSUM_1:74;
A14:now
let j being Nat;
reconsider a = j as (Element of ( NAT )) by ORDINAL1:def 12;
assume A15: j in ( Seg ( len g ) );
then j in ( dom g ) by FINSEQ_1:def 3;
then ( g . j ) <> ( 0 ) by A6;
then ( (( 0 ) qua Nat) + 1 ) <= ( g . a ) by NAT_1:13;
hence ( h1 . j ) <= ( g1 . j ) by A15,FUNCOP_1:7;
end;
( len h1 ) = ( len g1 ) by CARD_1:def 7;
then A16: ( Sum h1 ) <= ( Sum g1 ) by A14,RVSUM_1:82;
( Sum h ) = ( n * 1 ) by A9,RVSUM_1:80
.= n;
then ( n + a ) <= ( ( ( n + 1 ) - a ) + a ) by A16,A13,XREAL_1:6;
then a <= 1 by XREAL_1:6;
then A17: a = 1 by A10,XXREAL_0:1;
then g = ( ( len g ) |-> 1 ) by A2,A9,A6,A13;
hence f = ( ( len f ) |-> 1 ) by A3,A5,A9,A17,FINSEQ_2:60;
end;
assume f = ( ( len f ) |-> 1 );
then A18: f = ( ( n |-> 1 ) ^ ( 1 |-> 1 ) ) by A3,FINSEQ_2:123
.= ( ( n |-> 1 ) ^ <* 1 *> ) by FINSEQ_2:59;
then A19: a = 1 by A5,FINSEQ_2:17;
A20: ( Sum f ) = ( ( Sum g ) + a ) by A5,RVSUM_1:74;
g = ( ( len g ) |-> 1 ) by A5,A9,A18,FINSEQ_2:17;
hence thesis by A2,A3,A9,A6,A20,A19;
end;
A21: P[ ( 0 ) ]
proof
let f being (FinSequence of ( NAT ));
assume that
A22: ( len f ) = ( 0 )
and
(for i being (Element of ( NAT )) holds (i in ( dom f ) implies ( f . i ) <> ( 0 )));
hereby
assume ( Sum f ) = ( len f );
thus f = ( {} ) by A22
.= ( ( len f ) |-> 1 ) by A22;
end;
assume f = ( ( len f ) |-> 1 );
f = ( {} ) by A22;
hence thesis by RVSUM_1:72;
end;
(for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A21,A1);
hence thesis;
end;
