environ
vocabularies FINSET_1,SETFAM_1,TARSKI,SUBSET_1,XBOOLE_0,NAT_1,CARD_1,ARYTM_3,STRUCT_0,RELAT_2,LATTICE3,ORDERS_2,WAYBEL_0,LATTICES,XXREAL_0,EQREL_1,REWRITE1,ORDINAL2,WAYBEL_3,WAYBEL_6,RELAT_1,INT_2,ZFMISC_1,WAYBEL_8,RCOMP_1,PRE_TOPC,YELLOW_8,YELLOW_1,WAYBEL_9,RLVECT_3,WAYBEL11,PROB_1,YELLOW_6,FUNCT_1,WAYBEL_2,TMAP_1,CONNSP_2,TOPS_1,CARD_FIL,YELLOW_0,WAYBEL_5,ARYTM_0,WAYBEL14;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NAT_1,SETFAM_1,FINSET_1,DOMAIN_1,FUNCT_1,RELSET_1,BINOP_1,FUNCT_2,ORDERS_2,LATTICE3,CARD_1,STRUCT_0,PRE_TOPC,TOPS_1,TOPS_2,CONNSP_2,BORSUK_1,TMAP_1,CANTOR_1,COMPTS_1,YELLOW_0,YELLOW_1,YELLOW_3,YELLOW_4,YELLOW_6,YELLOW_7,YELLOW_8,WAYBEL_0,WAYBEL_1,WAYBEL_2,WAYBEL_3,WAYBEL_5,WAYBEL_6,WAYBEL_8,WAYBEL_9,WAYBEL11;
definitions TARSKI,WAYBEL_0,WAYBEL_6,TMAP_1,YELLOW_8,COMPTS_1,WAYBEL_3,WAYBEL_1,WAYBEL_8,TOPS_2,XBOOLE_0,SUBSET_1,BINOP_1,STRUCT_0,SETFAM_1;
theorems TARSKI,ZFMISC_1,SUBSET_1,RELAT_1,DOMAIN_1,FUNCT_1,FUNCT_2,SETFAM_1,LATTICE3,CARD_2,ORDERS_2,PRE_TOPC,TOPS_1,TOPS_2,BORSUK_1,TMAP_1,CONNSP_2,COMPTS_1,YELLOW_0,YELLOW_1,YELLOW_2,YELLOW_3,YELLOW_4,YELLOW_6,YELLOW_7,YELLOW_8,WAYBEL_0,WAYBEL_2,WAYBEL_3,WAYBEL_4,WAYBEL_6,WAYBEL_8,WAYBEL11,WAYBEL12,XBOOLE_0,XBOOLE_1,XCMPLX_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14;
schemes NAT_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSET_1,XCMPLX_0,STRUCT_0,PRE_TOPC,BORSUK_1,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_4,WAYBEL_3,YELLOW_6,WAYBEL_6,WAYBEL_8,YELLOW_8,WAYBEL11,ORDINAL1,CARD_1,TOPS_1;
constructors SETFAM_1,FINSUB_1,NAT_1,TOPS_1,TOPS_2,BORSUK_1,TMAP_1,T_0TOPSP,CANTOR_1,WAYBEL_1,YELLOW_4,WAYBEL_3,WAYBEL_5,WAYBEL_6,WAYBEL_8,YELLOW_8,WAYBEL11,COMPTS_1,BINOP_1,WAYBEL_2;
requirements NUMERALS,BOOLE,SUBSET;
begin
theorem
Th14: (for R being  with_suprema non empty Poset holds (for l being (Element of R) holds (l is  co-prime iff (for x,y being (Element of R) holds (l <= ( x "\/" y ) implies (l <= x or l <= y))))))
proof
let R being  with_suprema non empty Poset;
let l being (Element of R);
hereby
assume l is  co-prime;
then A1: ( l ~ ) is  prime by WAYBEL_6:def 8;
let x being (Element of R),y being (Element of R);
assume l <= ( x "\/" y );
then A2: ( ( x "\/" y ) ~ ) <= ( l ~ ) by LATTICE3:9;
( ( x "\/" y ) ~ ) = ( x "\/" y ) by LATTICE3:def 6
.= ( ( x ~ ) "/\" ( y ~ ) ) by YELLOW_7:23;
then (( x ~ ) <= ( l ~ ) or ( y ~ ) <= ( l ~ )) by A1,A2,WAYBEL_6:def 6;
hence (l <= x or l <= y) by LATTICE3:9;
end;
assume A3: (for x,y being (Element of R) holds (l <= ( x "\/" y ) implies (l <= x or l <= y)));
let x being (Element of ( R ~ )),y being (Element of ( R ~ ));
A4: ( ~ ( x "/\" y ) ) = ( x "/\" y ) by LATTICE3:def 7
.= ( ( ~ x ) "\/" ( ~ y ) ) by YELLOW_7:24;
assume ( x "/\" y ) <= ( l ~ );
then l <= ( ( ~ x ) "\/" ( ~ y ) ) by A4,YELLOW_7:2;
then (l <= ( ~ x ) or l <= ( ~ y )) by A3;
hence (x <= ( l ~ ) or y <= ( l ~ )) by YELLOW_7:2;
end;
