environ
vocabularies NUMBERS,FINSET_1,CARD_1,XBOOLE_0,ARYTM_3,ARYTM_1,SUBSET_1,XXREAL_0,NAT_1,RELAT_1,FINSEQ_1,ZFMISC_1,FUNCT_1,TARSKI,FUNCT_4,HALLMAR1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,FINSET_1,FINSEQ_1,FUNCT_2,FUNCT_7,CKB7;
definitions TARSKI,XBOOLE_0,CKB7;
theorems CARD_2,SPPOL_1,EULER_1,XBOOLE_1,ZFMISC_1,FUNCT_1,PARTFUN1,FINSET_1,PENCIL_1,CARD_1,TARSKI,NAT_1,XBOOLE_0,FINSEQ_1,FUNCT_7,FINSEQ_3,FINSEQ_5,TAXONOM1,RELAT_1,FUNCT_2,ENUMSET1,FINSEQ_2,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,CKB1,CKB5,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13;
schemes NAT_1,FUNCT_2,XBOOLE_0,CKB2,CKB3;
registrations SUBSET_1,RELAT_1,FUNCT_1,FINSET_1,XXREAL_0,XREAL_0,FINSEQ_1,CHAIN_1,ORDINAL1,CARD_1,RELSET_1,CKB4,CKB6,CKB10;
constructors XXREAL_0,REAL_1,NAT_1,FUNCT_7,RELSET_1,CKB7;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th8: (for J being set holds (for F being  finite set holds (for i being (Element of ( NAT )) holds (for A being (FinSequence of ( bool F )) holds ((i in J & i in ( dom A )) implies ( union (A,J) ) = ( ( union (A,( J \ { i } )) ) \/ ( A . i ) ))))))
proof
let J being set;
let F being  finite set;
let i being (Element of ( NAT ));
let A being (FinSequence of ( bool F ));
assume (i in J & i in ( dom A ));
then A1: ( A . i ) c= ( union (A,J) ) by CKB13:1;
thus ( union (A,J) ) c= ( ( union (A,( J \ { i } )) ) \/ ( A . i ) )
proof
let x being set;
assume x in ( union (A,J) );
then consider j being set such that A2: j in J and A3: j in ( dom A ) and A4: x in ( A . j ) by CKB7:def 1;
per cases ;
suppose i = j;

hence thesis by A4,XBOOLE_0:def 3;
end;
suppose i <> j;

then (not j in { i }) by TARSKI:def 1;
then j in ( J \ { i } ) by A2,XBOOLE_0:def 5;
then x in ( union (A,( J \ { i } )) ) by A3,A4,CKB7:def 1;
hence thesis by XBOOLE_0:def 3;
end;
end;

thus ( ( union (A,( J \ { i } )) ) \/ ( A . i ) ) c= ( union (A,J) )
proof
let x being set;
assume x in ( ( union (A,( J \ { i } )) ) \/ ( A . i ) );
then A5: (x in ( union (A,( J \ { i } )) ) or x in ( A . i )) by XBOOLE_0:def 3;
per cases  by A1,A5;
suppose x in ( union (A,( J \ { i } )) );

then (ex j being set st ((j in ( J \ { i } ) & j in ( dom A )) & x in ( A . j ))) by CKB7:def 1;
hence thesis by CKB7:def 1;
end;
suppose x in ( union (A,J) );

hence thesis;
end;
end;

end;
