environ
vocabularies NUMBERS,FINSET_1,CARD_1,XBOOLE_0,ARYTM_3,ARYTM_1,SUBSET_1,XXREAL_0,NAT_1,RELAT_1,FINSEQ_1,ZFMISC_1,FUNCT_1,TARSKI,FUNCT_4,HALLMAR1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,FINSET_1,FINSEQ_1,FUNCT_2,FUNCT_7,CKB7,CKB17;
definitions TARSKI,XBOOLE_0,CKB7,CKB17;
theorems CARD_2,SPPOL_1,EULER_1,XBOOLE_1,ZFMISC_1,FUNCT_1,PARTFUN1,FINSET_1,PENCIL_1,CARD_1,TARSKI,NAT_1,XBOOLE_0,FINSEQ_1,FUNCT_7,FINSEQ_3,FINSEQ_5,TAXONOM1,RELAT_1,FUNCT_2,ENUMSET1,FINSEQ_2,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,CKB1,CKB5,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19;
schemes NAT_1,FUNCT_2,XBOOLE_0,CKB2,CKB3;
registrations SUBSET_1,RELAT_1,FUNCT_1,FINSET_1,XXREAL_0,XREAL_0,FINSEQ_1,CHAIN_1,ORDINAL1,CARD_1,RELSET_1,CKB4,CKB6,CKB10;
constructors XXREAL_0,REAL_1,NAT_1,FUNCT_7,RELSET_1,CKB7,CKB17;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th13: (for F being  finite set holds (for A being (FinSequence of ( bool F )) holds (for i being (Element of ( NAT )) holds (for x,J being set holds ((not i in J) implies ( union (A,J) ) = ( union (( Cut (A,i,x) ),J) ))))))
proof
let F being  finite set;
let A being (FinSequence of ( bool F ));
let i being (Element of ( NAT ));
let x being set,J being set;
assume A1: (not i in J);
thus ( union (A,J) ) c= ( union (( Cut (A,i,x) ),J) )
proof
let z being set;
assume z in ( union (A,J) );
then consider j being set such that A2: j in J and A3: j in ( dom A ) and A4: z in ( A . j ) by CKB7:def 1;
A5: j in ( dom ( Cut (A,i,x) ) ) by A3,CKB17:def 1;
per cases ;
suppose i = j;

hence thesis by A1,A2;
end;
suppose i <> j;

then ( ( Cut (A,i,x) ) . j ) = ( A . j ) by A5,CKB17:def 1;
hence thesis by A2,A4,A5,CKB7:def 1;
end;
end;

let z being set;
assume z in ( union (( Cut (A,i,x) ),J) );
then consider j being set such that A6: j in J and A7: j in ( dom ( Cut (A,i,x) ) ) and A8: z in ( ( Cut (A,i,x) ) . j ) by CKB7:def 1;
A9: j in ( dom A ) by A7,CKB17:def 1;
per cases ;
suppose i = j;

hence thesis by A1,A6;
end;
suppose i <> j;

then ( ( Cut (A,i,x) ) . j ) = ( A . j ) by A7,CKB17:def 1;
hence thesis by A6,A8,A9,CKB7:def 1;
end;
end;
