environ
vocabularies NUMBERS,FINSET_1,CARD_1,XBOOLE_0,ARYTM_3,ARYTM_1,SUBSET_1,XXREAL_0,NAT_1,RELAT_1,FINSEQ_1,ZFMISC_1,FUNCT_1,TARSKI,FUNCT_4,HALLMAR1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,FINSET_1,FINSEQ_1,FUNCT_2,FUNCT_7,CKB7,CKB17,CKB22,CKB23,CKB31,CKB32,CKB33,CKB42;
definitions TARSKI,XBOOLE_0,CKB7,CKB17,CKB22,CKB23,CKB31,CKB32,CKB33,CKB42;
theorems CARD_2,SPPOL_1,EULER_1,XBOOLE_1,ZFMISC_1,FUNCT_1,PARTFUN1,FINSET_1,PENCIL_1,CARD_1,TARSKI,NAT_1,XBOOLE_0,FINSEQ_1,FUNCT_7,FINSEQ_3,FINSEQ_5,TAXONOM1,RELAT_1,FUNCT_2,ENUMSET1,FINSEQ_2,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,CKB1,CKB5,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB26,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB46,CKB47;
schemes NAT_1,FUNCT_2,XBOOLE_0,CKB2,CKB3;
registrations SUBSET_1,RELAT_1,FUNCT_1,FINSET_1,XXREAL_0,XREAL_0,FINSEQ_1,CHAIN_1,ORDINAL1,CARD_1,RELSET_1,CKB4,CKB6,CKB10,CKB24,CKB25,CKB27,CKB44,CKB45;
constructors XXREAL_0,REAL_1,NAT_1,FUNCT_7,RELSET_1,CKB7,CKB17,CKB22,CKB23,CKB31,CKB32,CKB33,CKB42;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th30: (for F being  finite set holds (for A being (FinSequence of ( bool F )) holds (for i being (Element of ( NAT )) holds ((i in ( dom A ) & A is  Hall) implies (ex G being (Singlification of A,i) st G is  Hall)))))
proof
let F being  finite set;
let A being (FinSequence of ( bool F ));
let i being (Element of ( NAT ));
assume that
A1: i in ( dom A )
and
A2: A is  Hall;
A3: ( A . i ) <> ( {} ) by A1,A2,CKB28:1,CARD_1:27;
set n = ( card ( A . i ) );
A4: n >= 1 by A1,A2,CKB28:1;
defpred P[ (Element of ( NAT )) ]
 means
(ex G being (Reduction of A) st (G is  Hall & ( card ( G . i ) ) = $1));
A5: A is (Reduction of A) by CKB41:1;
per cases  by A4,XXREAL_0:1;
suppose n = 1;

then A is (Singlification of A,i) by A1,A5,CKB33:def 1,CARD_1:27;
hence thesis by A2;
end;
suppose A6: n > 1;

A7: (for k being (Element of ( NAT )) holds ((k >= 1 & P[ ( k + 1 ) ]) implies P[ k ]))
proof
let k being (Element of ( NAT ));
assume that
A8: k >= 1
and
A9: P[ ( k + 1 ) ];
consider G being (Reduction of A) such that A10: G is  Hall and A11: ( card ( G . i ) ) = ( k + 1 ) by A9;
( 1 + 1 ) <= ( k + 1 ) by A8,XREAL_1:6;
then consider x being set such that A12: x in ( G . i ) and A13: ( Cut (G,i,x) ) is  Hall by A10,A11,CKB47:1;
set H = ( Cut (G,i,x) );
A14: ( dom G ) = ( dom A ) by CKB32:def 1;
then H is (Reduction of G) by A1,CKB36:1;
then A15: H is (Reduction of A) by CKB37:1;
( card ( H . i ) ) = ( ( k + 1 ) - 1 ) by A1,A11,A14,A12,CKB18:1
.= k;
hence thesis by A13,A15;
end;
A is (Reduction of A) by CKB41:1;
then A16: (ex n being (Element of ( NAT )) st (n > 1 & P[ n ])) by A2,A6;
P[ 1 ] from CKB3:sch 1(A16,A7);
then consider G being (Reduction of A) such that A17: G is  Hall and A18: ( card ( G . i ) ) = 1;
G is (Singlification of A,i) by A1,A3,A18,CKB33:def 1;
hence thesis by A17;
end;
end;
