environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,CARD_1,XXREAL_0,RELAT_1,ARYTM_3,NAT_1,NEWTON,INT_1,SUBSET_1,ARYTM_1,REALSET1,ABIAN,FINSEQ_1,FINSEQ_2,ORDINAL4,CARD_3,FUNCT_1,INT_2,NAT_3,XBOOLE_0,PRE_POLY,POWER,PEPIN,SQUARE_1,ZFMISC_1,TARSKI,BINOP_2,FINSET_1,MEMBERED,REAL_1,COMPLEX1,PREPOWER;
notations SUBSET_1,XXREAL_0,PREPOWER,TARSKI,XBOOLE_0,ORDINAL1,CARD_1,NUMBERS,XREAL_0,INT_1,ABIAN,SQUARE_1,NEWTON,FINSET_1,PEPIN,NAT_3,RELAT_1,FUNCT_1,FINSEQ_1,RVSUM_1,WSIERP_1,TREES_4,BINOP_2,XXREAL_2,POWER,MEMBERED,INT_2,FINSEQ_2,ZFMISC_1,RECDEF_1,PRE_POLY,REAL_1,NAT_1,NAT_D;
definitions TARSKI,MEMBERED,RVSUM_1,FINSEQ_2,NEWTON,SQUARE_1;
theorems TARSKI,NAT_1,NAT_2,INT_1,FINSEQ_1,CARD_1,XBOOLE_1,CARD_2,FINSET_1,SQUARE_1,EULER_1,EULER_2,PREPOWER,POWER,ABSVALUE,NEWTON,XCMPLX_1,ORDINAL1,XREAL_1,PEPIN,NAT_3,XBOOLE_0,INT_2,ABIAN,FINSEQ_3,RVSUM_1,FUNCT_1,FINSEQ_2,ZFMISC_1,FUNCT_2,FUNCOP_1,PROB_3,INTEGRA5,COMPTRIG,XXREAL_0,NAT_D,VALUED_1,XXREAL_2,PRE_POLY,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
schemes NAT_1,FINSEQ_1;
registrations XBOOLE_0,RELAT_1,FUNCT_1,ORDINAL1,FINSET_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,NAT_1,INT_1,MEMBERED,FINSEQ_1,FINSEQ_2,RVSUM_1,NEWTON,SEQM_3,NAT_3,VALUED_0,VALUED_1,XXREAL_2,CARD_1,PRE_POLY;
constructors REAL_1,NAT_D,PREPOWER,POWER,WSIERP_1,ABIAN,PEPIN,POLYNOM2,NAT_3,SEQ_1,RECDEF_1,BINOP_2,XXREAL_2,RELSET_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th25: (for n,f,d,n1,a,q being (Element of ( NAT )) holds ((((((( n - 1 ) = ( ( q |^ n1 ) * d ) & ( q |^ n1 ) > d) & d > ( 0 )) & q is  prime) & ( ( a |^ ( n -' 1 ) ) mod n ) = 1) & ( ( ( a |^ ( ( n -' 1 ) div q ) ) -' 1 ) gcd n ) = 1) implies n is  prime))
proof
let n being (Element of ( NAT )),f being (Element of ( NAT )),d being (Element of ( NAT )),n1 being (Element of ( NAT )),a being (Element of ( NAT )),q being (Element of ( NAT ));
assume that
A1: ((( n - 1 ) = ( ( q |^ n1 ) * d ) & ( q |^ n1 ) > d) & d > ( 0 ))
and
A2: q is  prime;
set f = ( q |^ n1 );
assume A3: ( ( a |^ ( n -' 1 ) ) mod n ) = 1;
assume A4: ( ( ( a |^ ( ( n -' 1 ) div q ) ) -' 1 ) gcd n ) = 1;
(for q1 being (Element of ( NAT )) holds ((q1 divides f & q1 is  prime) implies (ex a being (Element of ( NAT )) st (( ( a |^ ( n -' 1 ) ) mod n ) = 1 & ( ( ( a |^ ( ( n -' 1 ) div q1 ) ) -' 1 ) gcd n ) = 1))))
proof
let q1 being (Element of ( NAT ));
assume A5: q1 divides f;
assume A6: q1 is  prime;
consider a being (Element of ( NAT )) such that A7: (( ( a |^ ( n -' 1 ) ) mod n ) = 1 & ( ( ( a |^ ( ( n -' 1 ) div q ) ) -' 1 ) gcd n ) = 1) by A3,A4;
take a;
thus thesis by A2,A5,A6,A7,CKB19:1;
end;
hence thesis by A1,CKB25:1;
end;
