environ
vocabularies NUMBERS,SUBSET_1,FINSEQ_1,CARD_1,XXREAL_0,RELAT_1,REAL_1,FUNCT_1,ARYTM_3,FUNCOP_1,ARYTM_1,RFINSEQ,CLASSES1,FUNCT_2,XBOOLE_0,VALUED_0,ORDINAL4,NAT_1,RFINSEQ2;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,XXREAL_0,RELAT_1,FUNCT_1,FUNCT_2,FINSEQ_1,REAL_1,NAT_1,SEQ_1,RVSUM_1,FUNCOP_1,CLASSES1,RFINSEQ,INTEGRA2,CKB1,CKB2,CKB3,CKB4,CKB22;
definitions INTEGRA2,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB22;
theorems TARSKI,FINSEQ_1,FINSEQ_2,FINSEQ_3,NAT_1,FUNCT_1,FUNCT_2,RVSUM_1,RELAT_1,FUNCOP_1,RFINSEQ,INTEGRA2,XREAL_1,XXREAL_0,VALUED_1,CLASSES1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24;
schemes NAT_1;
registrations XBOOLE_0,FUNCT_1,RELSET_1,FUNCT_2,NUMBERS,XXREAL_0,NAT_1,MEMBERED,FINSEQ_1,RFINSEQ,INTEGRA2,VALUED_0,FINSET_1,CARD_1;
constructors FUNCOP_1,REAL_1,NAT_1,BINOP_2,SEQM_3,RFINSEQ,INTEGRA2,SEQ_1,RVSUM_1,CLASSES1,RELSET_1,CKB1,CKB2,CKB3,CKB4,CKB22;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve n for (Element of ( NAT ));
theorem
Lm3: (for f,g being  non-decreasing (FinSequence of ( REAL )) holds (for n holds (((( len f ) = ( n + 1 ) & ( len f ) = ( len g )) & f,g are_fiberwise_equipotent ) implies (( f . ( len f ) ) = ( g . ( len g ) ) & ( f | n ),( g | n ) are_fiberwise_equipotent ))))
proof
let f being  non-decreasing (FinSequence of ( REAL )),g being  non-decreasing (FinSequence of ( REAL ));
let n;
assume that
A1: ( len f ) = ( n + 1 )
and
A2: ( len f ) = ( len g )
and
A3: f,g are_fiberwise_equipotent ;
set r = ( f . ( n + 1 ) );
set s = ( g . ( n + 1 ) );
A4: ( ( 0 ) + 1 ) <= ( n + 1 ) by NAT_1:13;
then A5: ( n + 1 ) in ( dom f ) by A1,FINSEQ_3:25;
A6: f = ( ( f | n ) ^ <* r *> ) by A1,RFINSEQ:7;
A7: ( n + 1 ) in ( dom g ) by A1,A2,A4,FINSEQ_3:25;
A8:now
A9: ( rng f ) = ( rng g ) by A3,CLASSES1:75;
assume A10: r <> s;
now
per cases  by A10,XXREAL_0:1;
case A11: r < s;
s in ( rng f ) by A7,A9,FUNCT_1:def 3;
then consider m being Nat such that A12: m in ( dom f ) and A13: ( f . m ) = s by FINSEQ_2:10;
A14: m <= ( len f ) by A12,FINSEQ_3:25;
now
per cases ;
case m = ( len f );
hence contradiction by A1,A11,A13;
end;
case m <> ( len f );
then m < ( n + 1 ) by A1,A14,XXREAL_0:1;
hence contradiction by A5,A11,A12,A13,CKB24:1;
end;
end;
hence contradiction;
end;
case A15: r > s;
r in ( rng g ) by A5,A9,FUNCT_1:def 3;
then consider m being Nat such that A16: m in ( dom g ) and A17: ( g . m ) = r by FINSEQ_2:10;
A18: m <= ( len g ) by A16,FINSEQ_3:25;
now
per cases ;
case m = ( len g );
hence contradiction by A1,A2,A15,A17;
end;
case m <> ( len g );
then m < ( n + 1 ) by A1,A2,A18,XXREAL_0:1;
hence contradiction by A7,A15,A16,A17,CKB24:1;
end;
end;
hence contradiction;
end;
end;
hence contradiction;
end;
hence ( f . ( len f ) ) = ( g . ( len g ) ) by A1,A2;
A19: g = ( ( g | n ) ^ <* r *> ) by A1,A2,A8,RFINSEQ:7;
now
let x being set;
( ( card ( ( f | n ) " { x } ) ) + ( card ( <* r *> " { x } ) ) ) = ( card ( Coim (f,x) ) ) by A6,FINSEQ_3:57
.= ( card ( Coim (g,x) ) ) by A3,CLASSES1:def 9
.= ( ( card ( ( g | n ) " { x } ) ) + ( card ( <* r *> " { x } ) ) ) by A19,FINSEQ_3:57;
hence ( card ( Coim (( f | n ),x) ) ) = ( card ( Coim (( g | n ),x) ) );
end;
hence thesis by CLASSES1:def 9;
end;
