environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,RELAT_1,FUNCT_1,TARSKI,ZFMISC_1,RELAT_2,ANALOAF,STRUCT_0,DIRAF,PARSP_1,INCSP_1,AFF_1,TRANSGEO;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_2,FUNCT_1,RELSET_1,STRUCT_0,ANALOAF,DIRAF,PARTFUN1,FUNCT_2,AFF_1,CKB1,CKB4,CKB17,CKB22,CKB29,CKB31,CKB33,CKB40,CKB42,CKB49,CKB65,CKB86,CKB100;
definitions RELAT_2,CKB4,CKB17,CKB22,CKB29,CKB31,CKB40,CKB42,CKB49,CKB65,CKB86,CKB100;
theorems DOMAIN_1,FUNCT_1,FUNCT_2,ANALOAF,DIRAF,AFF_1,PASCH,TARSKI,ZFMISC_1,RELAT_1,XBOOLE_0,STRUCT_0,CKB2,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101,CKB102,CKB103;
schemes FUNCT_2,CKB5;
registrations XBOOLE_0,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,STRUCT_0,ANALOAF,DIRAF,CKB32;
constructors RELAT_2,PARTFUN1,DOMAIN_1,AFF_1,RELSET_1,CKB1,CKB4,CKB17,CKB22,CKB29,CKB31,CKB40,CKB42,CKB49,CKB65,CKB86,CKB100;
requirements SUBSET,BOOLE;
begin
reserve A for non  empty set;
reserve a for (Element of A);
reserve x for (Element of A);
reserve f for (Permutation of A);
reserve g for (Permutation of A);
reserve AFS for AffinSpace;
reserve a for (Element of AFS);
reserve p for (Element of AFS);
reserve x for (Element of AFS);
reserve f for (Permutation of (the carrier of AFS));
reserve g for (Permutation of (the carrier of AFS));
theorem
Th103: (((f is  translation & g is  translation) & ( f . a ) = ( g . a )) implies f = g)
proof
assume that
A1: f is  translation
and
A2: g is  translation
and
A3: ( f . a ) = ( g . a );
set b = ( f . a );
A4: f is  dilatation by A1,CKB100:def 1;
A5:now
assume A6: a <> b;
(for x holds ( f . x ) = ( g . x ))
proof
let x;
now
assume A7:  LIN a,b,x;
now
A8: f <> ( id (the carrier of AFS) ) by A6,FUNCT_1:18;
then A9: ( f . x ) <> x by A1,CKB100:def 1;
assume x <> a;
consider p such that A10: (not  LIN a,b,p) by A6,AFF_1:13;
A11: ( f . p ) <> p by A1,A8,CKB100:def 1;
A12: (not  LIN p,( f . p ),x)
proof
A13:  LIN a,b,( f . x ) by A4,A7,CKB93:1;
 LIN a,b,a by AFF_1:7;
then A14:  LIN x,( f . x ),a by A6,A7,A13,AFF_1:8;
A15:  LIN p,( f . p ),p by AFF_1:7;
 LIN a,b,b by AFF_1:7;
then A16:  LIN x,( f . x ),b by A6,A7,A13,AFF_1:8;
assume A17:  LIN p,( f . p ),x;
then  LIN p,( f . p ),( f . x ) by A4,CKB93:1;
then  LIN x,( f . x ),p by A11,A17,A15,AFF_1:8;
hence contradiction by A10,A9,A14,A16,AFF_1:8;
end;
( f . p ) = ( g . p ) by A1,A2,A3,A10,CKB103:1;
hence thesis by A1,A2,A12,CKB103:1;
end;
hence thesis by A3;
end;
hence thesis by A1,A2,A3,CKB103:1;
end;
hence thesis by FUNCT_2:63;
end;
now
assume A18: b = a;
then f = ( id (the carrier of AFS) ) by A1,CKB100:def 1;
hence thesis by A2,A3,A18,CKB100:def 1;
end;
hence thesis by A5;
end;
