environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,RELAT_1,FUNCT_1,TARSKI,ZFMISC_1,RELAT_2,ANALOAF,STRUCT_0,DIRAF,PARSP_1,INCSP_1,AFF_1,TRANSGEO;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_2,FUNCT_1,RELSET_1,STRUCT_0,ANALOAF,DIRAF,PARTFUN1,FUNCT_2,AFF_1,CKB1,CKB4,CKB17,CKB22,CKB29,CKB31,CKB33,CKB40,CKB42,CKB49;
definitions RELAT_2,CKB4,CKB17,CKB22,CKB29,CKB31,CKB40,CKB42,CKB49;
theorems DOMAIN_1,FUNCT_1,FUNCT_2,ANALOAF,DIRAF,AFF_1,PASCH,TARSKI,ZFMISC_1,RELAT_1,XBOOLE_0,STRUCT_0,CKB2,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56;
schemes FUNCT_2,CKB5;
registrations XBOOLE_0,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,STRUCT_0,ANALOAF,DIRAF,CKB32;
constructors RELAT_2,PARTFUN1,DOMAIN_1,AFF_1,RELSET_1,CKB1,CKB4,CKB17,CKB22,CKB29,CKB31,CKB40,CKB42,CKB49;
requirements SUBSET,BOOLE;
begin
reserve OAS for OAffinSpace;
reserve a for (Element of OAS);
reserve b for (Element of OAS);
reserve c for (Element of OAS);
reserve d for (Element of OAS);
reserve f for (Permutation of (the carrier of OAS));
theorem
Th58: (f is  dilatation implies (for a holds (for b holds (for c holds (for d holds (a,b '||' c,d iff ( f . a ),( f . b ) '||' ( f . c ),( f . d )))))))
proof
assume A1: f is  dilatation;
let a;
let b;
let c;
let d;
A2: c,d '||' ( f . c ),( f . d ) by A1,CKB50:1;
A3: a,b '||' ( f . a ),( f . b ) by A1,CKB50:1;
A4:now
A5:now
A6:now
assume ( f . c ) = ( f . d );
then c = d by FUNCT_2:58;
hence a,b '||' c,d by DIRAF:20;
end;
assume a,b '||' ( f . c ),( f . d );
hence a,b '||' c,d by A2,A6,DIRAF:23;
end;
A7:now
assume ( f . a ) = ( f . b );
then a = b by FUNCT_2:58;
hence a,b '||' c,d by DIRAF:20;
end;
assume ( f . a ),( f . b ) '||' ( f . c ),( f . d );
hence a,b '||' c,d by A3,A7,A5,DIRAF:23;
end;
now
A8:now
A9: (c = d implies ( f . a ),( f . b ) '||' ( f . c ),( f . d )) by DIRAF:20;
assume ( f . a ),( f . b ) '||' c,d;
hence ( f . a ),( f . b ) '||' ( f . c ),( f . d ) by A2,A9,DIRAF:23;
end;
assume a,b '||' c,d;
then (( f . a ),( f . b ) '||' c,d or a = b) by A3,DIRAF:23;
hence ( f . a ),( f . b ) '||' ( f . c ),( f . d ) by A8,DIRAF:20;
end;
hence thesis by A4;
end;
