environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,CARD_1,XXREAL_0,ARYTM_3,RELAT_1,ARYTM_1,XBOOLE_0,SUBSET_1,FUNCT_1,MCART_1,ZFMISC_1,NORMSP_1,PRE_TOPC,METRIC_1,SUPINF_2,TARSKI,REAL_1,COMPLEX1,LOPBAN_1,STRUCT_0,NORMSP_2,RCOMP_1,CONVEX1,XXREAL_2,XCMPLX_0,PREPOWER,SERIES_1,NEWTON,NAT_1,CARD_3,ORDINAL2,SEQ_2,RSSPACE3,FUNCT_2,PARTFUN1,FCONT_1,PROB_1;
notations TARSKI,XBOOLE_0,SUBSET_1,ZFMISC_1,FUNCT_1,RELSET_1,FUNCT_2,PARTFUN1,MCART_1,PRE_TOPC,DOMAIN_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,STRUCT_0,XXREAL_0,SEQ_2,NEWTON,PREPOWER,SERIES_1,RLVECT_1,CONVEX1,RUSUB_4,NORMSP_0,NORMSP_1,NORMSP_2,RSSPACE3,LOPBAN_1,NFCONT_1,LOPBAN_5,KURATO_2,T_0TOPSP;
definitions TARSKI,RLVECT_1,METRIC_1,PCOMPS_1,CONVEX1,RUSUB_4,T_0TOPSP,ALGSTR_0,NORMSP_2,XBOOLE_0,LOPBAN_1,LOPBAN_5,NFCONT_1,NORMSP_0;
theorems TARSKI,XBOOLE_1,SEQ_2,RLVECT_1,XREAL_0,RELAT_1,RUSUB_4,RLTOPSP1,SERIES_1,PREPOWER,ZFMISC_1,FUNCT_2,XBOOLE_0,XREAL_1,XCMPLX_1,NORMSP_1,PRE_TOPC,NFCONT_1,XXREAL_0,FUNCT_1,NEWTON,MESFUNC1,NORMSP_2,RINFSUP1,ABSVALUE,XCMPLX_0,LOPBAN_3,ORDINAL1,SUBSET_1,RSSPACE2,LOPBAN_1,NAT_1,PROB_1,LOPBAN_5,CONVEX1,MCART_1,GRCAT_1,NORMSP_0;
schemes FUNCT_2,RECDEF_1,NAT_1;
registrations REAL_1,XREAL_0,XXREAL_0,ORDINAL1,RELSET_1,STRUCT_0,TOPS_1,SUBSET_1,NAT_1,NORMSP_1,NORMSP_2,FUNCT_2,LOPBAN_1,NORMSP_0;
constructors XCMPLX_0,XXREAL_0,XREAL_0,ORDINAL2,TOPS_1,REAL_1,DOMAIN_1,SEQ_1,SEQ_2,PCOMPS_1,RUSUB_4,CONVEX1,RLTOPSP1,NFCONT_1,NAT_1,FUNCT_1,FUNCT_2,PSCOMP_1,PARTFUN1,NEWTON,PREPOWER,SERIES_1,NORMSP_2,RSSPACE3,LOPBAN_1,LOPBAN_5,T_0TOPSP,RELSET_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th1: (for x,y being  real number holds ((( 0 ) <= x & x < y) implies (ex s0 being  real number st ((( 0 ) < s0 & x < ( y / ( 1 + s0 ) )) & ( y / ( 1 + s0 ) ) < y))))
proof
let x being  real number,y being  real number;
assume that
A1: ( 0 ) <= x
and
A2: x < y;
(ex s0 being  real number st ((( 0 ) < s0 & x < ( y / ( 1 + s0 ) )) & ( y / ( 1 + s0 ) ) < y))
proof
consider s being  real number such that A3: x < s and A4: s < y by A2,XREAL_1:5;
now
per cases  by A1;
case A5: ( 0 ) = x;
set s0 = s;
y < ( y * ( 1 + s0 ) ) by A1,A3,A4,XREAL_1:29,XREAL_1:155;
hence ((( 0 ) < s0 & x < ( y / ( 1 + s0 ) )) & ( y / ( 1 + s0 ) ) < y) by A3,A4,A5,XREAL_1:83,XREAL_1:139;
end;
case A6: ( 0 ) < x;
set s0 = ( ( s / x ) - 1 );
A7: ( ( 1 + s0 ) " ) = ( 1 / ( 1 + s0 ) ) by XCMPLX_1:215;
then A8: ( s * ( ( 1 + s0 ) " ) ) = ( ( s * 1 ) / ( 1 + s0 ) ) by XCMPLX_1:74;
( ( 1 + s0 ) * x ) = ( ( x / x ) * s ) by XCMPLX_1:75;
then ( ( 1 + s0 ) * x ) = ( 1 * s ) by A6,XCMPLX_1:60;
then A9: ( ( ( ( 1 + s0 ) " ) * ( 1 + s0 ) ) * x ) = ( s * ( ( 1 + s0 ) " ) );
( 0 ) < ( 1 + s0 ) by A3,A6,XREAL_1:187;
then A10: ( ( ( 1 + s0 ) " ) * ( 1 + s0 ) ) = 1 by A7,XCMPLX_1:106;
A11: 1 < ( 1 + s0 ) by A3,A6,XREAL_1:187;
then y < ( y * ( 1 + s0 ) ) by A1,A2,XREAL_1:155;
hence ((( 0 ) < s0 & x < ( y / ( 1 + s0 ) )) & ( y / ( 1 + s0 ) ) < y) by A4,A11,A9,A10,A8,XREAL_1:50,XREAL_1:74,XREAL_1:83;
end;
end;
hence thesis;
end;
hence thesis;
end;
