environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,VECTSP_1,STRUCT_0,EUCLID,FINSEQ_1,FINSEQ_2,SUPINF_2,RELAT_1,ALGSTR_0,ARYTM_3,ARYTM_1,RVSUM_1,FUNCT_1,PARTFUN1,TARSKI,ZFMISC_1,NAT_1,XXREAL_0,GROUP_1,ORDINAL4,CARD_1,FVSUM_1,CARD_3,MATRIX_1,PRALG_1,MESFUNC1,MATRIX_6,TREES_1,MATRIXR2,AFINSQ_1,FUNCOP_1,QC_LANG1,FINSOP_1,INCSP_1,FUNCT_7,RFINSEQ,MATRIX_3,MATRIX14;
notations TARSKI,XBOOLE_0,SUBSET_1,XXREAL_0,RELAT_1,FUNCT_1,BINOP_1,ALGSTR_0,ZFMISC_1,MATRIX_1,FVSUM_1,PARTFUN1,FUNCT_3,NUMBERS,FINSEQ_7,FUNCT_2,FUNCOP_1,FINSEQ_1,STRUCT_0,GROUP_1,MATRIX_3,MATRIX_6,XCMPLX_0,NAT_1,NAT_D,VECTSP_1,FINSEQ_2,FINSOP_1,RFINSEQ,CKB1,CKB2,CKB10,CKB17,CKB27,CKB28;
definitions XBOOLE_0,MATRIX_1,ALGSTR_0,CKB1,CKB28;
theorems MATRIX_3,VECTSP_1,MATRIX_1,MATRIX_4,GROUP_1,FUNCT_1,FINSEQ_1,NAT_1,FINSEQ_7,FINSEQ_2,TARSKI,FINSOP_1,FVSUM_1,FUNCT_2,XBOOLE_0,ZFMISC_1,MATRIX_7,MATRIXR1,FINSEQ_3,XXREAL_0,ORDINAL1,FINSEQ_4,MATRIXR2,XREAL_1,FUNCOP_1,RLVECT_1,MATRIX_6,MATRIX12,POLYNOM1,PARTFUN1,NAT_D,CARD_1,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB28,CKB29,CKB30,CKB31;
schemes NAT_1,MATRIX_1;
registrations FINSEQ_2,XREAL_0,NAT_1,FUNCOP_1,STRUCT_0,VECTSP_1,ORDINAL1,XXREAL_0,RELAT_1,CARD_1,FINSEQ_1;
constructors FUNCT_3,FINSEQ_7,SETWISEO,FINSOP_1,JORDAN3,RFINSEQ,INTEGRA2,MATRIX_6,POLYNOM1,NAT_D,RELSET_1,FVSUM_1,CKB1,CKB2,CKB27,CKB28;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
reserve K for Field;
theorem
Th26: (for i,n being Nat holds ((1 <= i & i <= n) implies ( ( 1. (K,n) ) . i ) = ( Base_FinSeq (K,n,i) )))
proof
let i being Nat;
let n being Nat;
assume A1: (1 <= i & i <= n);
then 1 <= n by XXREAL_0:2;
then [ i,1 ] in ( Indices ( 1. (K,n) ) ) by A1,MATRIX_1:37;
then consider q being (FinSequence of K) such that A2: q = ( ( 1. (K,n) ) . i ) and ( ( 1. (K,n) ) * (i,1) ) = ( q . 1 ) by MATRIX_1:def 5;
( len ( 1. (K,n) ) ) = n by MATRIX_1:24;
then i in ( dom ( 1. (K,n) ) ) by A1,FINSEQ_3:25;
then q in ( rng ( 1. (K,n) ) ) by A2,FUNCT_1:def 3;
then A3: ( len q ) = n by MATRIX_1:def 2;
A4: (for j being Nat holds ((1 <= j & j <= n) implies ( q . j ) = ( ( Base_FinSeq (K,n,i) ) . j )))
proof
let j being Nat;
assume A5: (1 <= j & j <= n);
then A6: [ i,j ] in ( Indices ( 1. (K,n) ) ) by A1,MATRIX_1:37;
then A7: (ex q0 being (FinSequence of K) st (q0 = ( ( 1. (K,n) ) . i ) & ( ( 1. (K,n) ) * (i,j) ) = ( q0 . j ))) by MATRIX_1:def 5;
per cases ;
suppose A8: i = j;

then ( ( 1. (K,n) ) * (i,i) ) = ( 1_ K ) by A6,MATRIX_1:def 11;
hence thesis by A1,A2,A7,A8,CKB30:1;
end;
suppose A9: i <> j;

then ( q . j ) = ( 0. K ) by A2,A6,A7,MATRIX_1:def 11;
hence thesis by A5,A9,CKB31:1;
end;
end;
( len ( Base_FinSeq (K,n,i) ) ) = n by CKB29:1;
hence thesis by A2,A3,A4,FINSEQ_1:14;
end;
