environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,VECTSP_1,STRUCT_0,EUCLID,FINSEQ_1,FINSEQ_2,SUPINF_2,RELAT_1,ALGSTR_0,ARYTM_3,ARYTM_1,RVSUM_1,FUNCT_1,PARTFUN1,TARSKI,ZFMISC_1,NAT_1,XXREAL_0,GROUP_1,ORDINAL4,CARD_1,FVSUM_1,CARD_3,MATRIX_1,PRALG_1,MESFUNC1,MATRIX_6,TREES_1,MATRIXR2,AFINSQ_1,FUNCOP_1,QC_LANG1,FINSOP_1,INCSP_1,FUNCT_7,RFINSEQ,MATRIX_3,MATRIX14;
notations TARSKI,XBOOLE_0,SUBSET_1,XXREAL_0,RELAT_1,FUNCT_1,BINOP_1,ALGSTR_0,ZFMISC_1,MATRIX_1,FVSUM_1,PARTFUN1,FUNCT_3,NUMBERS,FINSEQ_7,FUNCT_2,FUNCOP_1,FINSEQ_1,STRUCT_0,GROUP_1,MATRIX_3,MATRIX_6,XCMPLX_0,NAT_1,NAT_D,VECTSP_1,FINSEQ_2,FINSOP_1,RFINSEQ,CKB1,CKB2,CKB10,CKB17,CKB27,CKB28,CKB49;
definitions XBOOLE_0,MATRIX_1,ALGSTR_0,CKB1,CKB28,CKB49;
theorems MATRIX_3,VECTSP_1,MATRIX_1,MATRIX_4,GROUP_1,FUNCT_1,FINSEQ_1,NAT_1,FINSEQ_7,FINSEQ_2,TARSKI,FINSOP_1,FVSUM_1,FUNCT_2,XBOOLE_0,ZFMISC_1,MATRIX_7,MATRIXR1,FINSEQ_3,XXREAL_0,ORDINAL1,FINSEQ_4,MATRIXR2,XREAL_1,FUNCOP_1,RLVECT_1,MATRIX_6,MATRIX12,POLYNOM1,PARTFUN1,NAT_D,CARD_1,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60;
schemes NAT_1,MATRIX_1;
registrations FINSEQ_2,XREAL_0,NAT_1,FUNCOP_1,STRUCT_0,VECTSP_1,ORDINAL1,XXREAL_0,RELAT_1,CARD_1,FINSEQ_1;
constructors FUNCT_3,FINSEQ_7,SETWISEO,FINSOP_1,JORDAN3,RFINSEQ,INTEGRA2,MATRIX_6,POLYNOM1,NAT_D,RELSET_1,FVSUM_1,CKB1,CKB2,CKB27,CKB28,CKB49;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
reserve K for Field;
theorem
Th54: (for A,B being (Matrix of n,K) holds (( B * A ) = ( 1. (K,n) ) implies (ex B2 being (Matrix of n,K) st ( A * B2 ) = ( 1. (K,n) ))))
proof
let A being (Matrix of n,K),B being (Matrix of n,K);
thus (( B * A ) = ( 1. (K,n) ) implies (ex B2 being (Matrix of n,K) st ( A * B2 ) = ( 1. (K,n) )))
proof
defpred P[ (Element of ( NAT )) ]
 means
(for D,B3 being (Matrix of $1,K) holds (( B3 * D ) = ( 1. (K,$1) ) implies (ex B4 being (Matrix of $1,K) st ( D * B4 ) = ( 1. (K,$1) ))));
assume A1: ( B * A ) = ( 1. (K,n) );
A2: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
let k being (Element of ( NAT ));
assume A3: P[ k ];
(for A2,B3 being (Matrix of ( k + 1 ),K) holds (( B3 * A2 ) = ( 1. (K,( k + 1 )) ) implies (ex B4 being (Matrix of ( k + 1 ),K) st ( A2 * B4 ) = ( 1. (K,( k + 1 )) ))))
proof
let A2 being (Matrix of ( k + 1 ),K),B2 being (Matrix of ( k + 1 ),K);
A4: ( Indices ( 1. (K,( k + 1 )) ) ) = [: ( Seg ( k + 1 ) ),( Seg ( k + 1 ) ) :] by MATRIX_1:24;
assume A5: ( B2 * A2 ) = ( 1. (K,( k + 1 )) );
then A6: ( ( Det B2 ) * ( Det A2 ) ) = ( Det ( 1. (K,( k + 1 )) ) ) by MATRIXR2:45;
now
assume A2 = ( 0. (K,( k + 1 )) );
then A2 = ( 0. (K,( k + 1 ),( k + 1 )) ) by MATRIX_3:def 1;
then ( Det A2 ) = ( 0. K ) by MATRIX_7:15,NAT_1:12;
then A7: ( ( Det B2 ) * ( Det A2 ) ) = ( 0. K ) by VECTSP_1:6;
(not ( 0. K ) = ( 1_ K ));
hence contradiction by A6,A7,MATRIX_7:16,NAT_1:12;
end;
then consider B being (Matrix of ( k + 1 ),K),C being (Matrix of ( k + 1 ),K) such that A8: B is  invertible and A9: C is  invertible and A10: ( ( ( B * A2 ) * C ) * (1,1) ) = ( 1. K ) and A11: (for i holds ((1 < i & i <= ( k + 1 )) implies ( ( ( B * A2 ) * C ) * (i,1) ) = ( 0. K ))) and A12: (for j holds ((1 < j & j <= ( k + 1 )) implies ( ( ( B * A2 ) * C ) * (1,j) ) = ( 0. K ))) by CKB60:1;
set A3 = ( ( B * A2 ) * C );
set B3 = ( ( ( C ~ ) * B2 ) * ( B ~ ) );
A13: ( width B3 ) = ( k + 1 ) by MATRIX_1:24;
A14: ( width A3 ) = ( k + 1 ) by MATRIX_1:24;
A15: (for j being Nat holds ((1 <= j & j <= ( len ( Line (A3,1) ) )) implies ( ( Line (A3,1) ) . j ) = ( ( Base_FinSeq (K,( k + 1 ),1) ) . j )))
proof
let j being Nat;
assume that
A16: 1 <= j
and
A17: j <= ( len ( Line (A3,1) ) );
A18: j <= ( k + 1 ) by A14,A17,MATRIX_1:def 7;
( len ( Line (A3,1) ) ) = ( width A3 ) by MATRIX_1:def 7;
then A19: j in ( Seg ( width A3 ) ) by A16,A17,FINSEQ_1:1;
per cases  by A16,XXREAL_0:1;
suppose A20: 1 = j;

then ( ( Line (A3,1) ) . j ) = ( 1. K ) by A10,A19,MATRIX_1:def 7;
hence thesis by A18,A20,CKB30:1;
end;
suppose A21: 1 < j;

A22: j in ( NAT ) by ORDINAL1:def 12;
( ( Line (A3,1) ) . j ) = ( A3 * (1,j) ) by A19,MATRIX_1:def 7
.= ( 0. K ) by A12,A18,A21,A22;
hence thesis by A18,A21,CKB31:1;
end;
end;
A23: ( len <* ( 0. K ) *> ) = 1 by FINSEQ_1:40;
deffunc f(Nat,Nat) = ( A3 * (( $1 + 1 ),( $2 + 1 )) );
A24: ( len ( A2 * C ) ) = ( k + 1 ) by MATRIX_1:24;
consider F being (Matrix of k,k,K) such that A25: (for i,j being Nat holds ([ i,j ] in ( Indices F ) implies ( F * (i,j) ) = f(i,j))) from MATRIX_1:sch 1;
A26: ( len F ) = k by MATRIX_1:24;
deffunc g(Nat,Nat) = ( B3 * (( $1 + 1 ),( $2 + 1 )) );
A27: ( len C ) = ( k + 1 ) by MATRIX_1:24;
consider G being (Matrix of k,k,K) such that A28: (for i,j being Nat holds ([ i,j ] in ( Indices G ) implies ( G * (i,j) ) = g(i,j))) from MATRIX_1:sch 1;
A29: ( len A3 ) = ( k + 1 ) by MATRIX_1:24;
A30: ( B3 * A3 ) = ( ( ( ( C ~ ) * B2 ) * ( B ~ ) ) * ( B * ( A2 * C ) ) ) by CKB21:1
.= ( ( ( ( ( Inv C ) * B2 ) * ( Inv B ) ) * B ) * ( A2 * C ) ) by CKB21:1
.= ( ( ( ( Inv C ) * B2 ) * ( ( Inv B ) * B ) ) * ( A2 * C ) ) by CKB21:1
.= ( ( ( ( Inv C ) * B2 ) * ( 1. (K,( k + 1 )) ) ) * ( A2 * C ) ) by A8,CKB22:1
.= ( ( ( Inv C ) * B2 ) * ( ( 1. (K,( k + 1 )) ) * ( A2 * C ) ) ) by CKB21:1
.= ( ( ( Inv C ) * B2 ) * ( A2 * C ) ) by A24,MATRIXR2:68
.= ( ( ( ( Inv C ) * B2 ) * A2 ) * C ) by CKB21:1
.= ( ( ( Inv C ) * ( 1. (K,( k + 1 )) ) ) * C ) by A5,CKB21:1
.= ( ( Inv C ) * ( ( 1. (K,( k + 1 )) ) * C ) ) by CKB21:1
.= ( ( Inv C ) * C ) by A27,MATRIXR2:68
.= ( 1. (K,( k + 1 )) ) by A9,CKB22:1;
A31: (for i being Nat holds ((1 < i & i <= ( k + 1 )) implies ( B3 * (i,1) ) = ( ( 1. (K,( k + 1 )) ) * (i,1) )))
proof
A32: ( len ( Base_FinSeq (K,( k + 1 ),1) ) ) = ( k + 1 ) by CKB29:1;
let i being Nat;
A33: ( len ( Col (A3,1) ) ) = ( len A3 ) by MATRIX_1:def 8
.= ( k + 1 ) by MATRIX_1:24;
A34: ( len A3 ) = ( k + 1 ) by MATRIX_1:24;
A35: (for k2 being Nat holds ((1 <= k2 & k2 <= ( len ( Col (A3,1) ) )) implies ( ( Col (A3,1) ) . k2 ) = ( ( Base_FinSeq (K,( k + 1 ),1) ) . k2 )))
proof
let k2 being Nat;
assume that
A36: 1 <= k2
and
A37: k2 <= ( len ( Col (A3,1) ) );
A38: k2 in ( NAT ) by ORDINAL1:def 12;
A39:now
per cases  by A36,XXREAL_0:1;
suppose k2 = 1;

hence ( A3 * (k2,1) ) = ( ( Base_FinSeq (K,( k + 1 ),1) ) . k2 ) by A10,A33,A37,CKB30:1;
end;
suppose A40: 1 < k2;

hence ( A3 * (k2,1) ) = ( 0. K ) by A11,A33,A38,A37
.= ( ( Base_FinSeq (K,( k + 1 ),1) ) . k2 ) by A33,A37,A40,CKB31:1;
end;
end;
k2 in ( Seg ( len A3 ) ) by A34,A33,A36,A37,FINSEQ_1:1;
then k2 in ( dom A3 ) by FINSEQ_1:def 3;
hence thesis by A39,MATRIX_1:def 8;
end;
A41: ( len ( Line (B3,i) ) ) = ( width B3 ) by MATRIX_1:def 7
.= ( k + 1 ) by MATRIX_1:24;
assume A42: (1 < i & i <= ( k + 1 ));
then A43: 1 <= ( k + 1 ) by XXREAL_0:2;
A44: ( width B3 ) = ( k + 1 ) by MATRIX_1:24;
then A45: 1 in ( Seg ( width B3 ) ) by A43,FINSEQ_1:1;
[ i,1 ] in ( Indices ( B3 * A3 ) ) by A42,A43,MATRIX_1:37;
then ( ( B3 * A3 ) * (i,1) ) = |( ( Line (B3,i) ),( Col (A3,1) ) )| by A44,A34,MATRIX_3:def 4
.= |( ( Line (B3,i) ),( Base_FinSeq (K,( k + 1 ),1) ) )| by A33,A32,A35,FINSEQ_1:14
.= ( ( Line (B3,i) ) . 1 ) by A43,A41,CKB41:1
.= ( B3 * (i,1) ) by A45,MATRIX_1:def 7;
hence thesis by A30;
end;
(for i,j being (Element of ( NAT )) holds ((((1 <= i & i <= k) & 1 <= j) & j <= k) implies ( ( G * F ) * (i,j) ) = ( IFEQ (i,j,( 1. K ),( 0. K )) )))
proof
let i being (Element of ( NAT )),j being (Element of ( NAT ));
assume that
A46: 1 <= i
and
A47: i <= k
and
A48: 1 <= j
and
A49: j <= k;
A50: [ i,j ] in ( Indices ( G * F ) ) by A46,A47,A48,A49,MATRIX_1:37;
A51: (for k2 being Nat holds (k2 in ( dom <* ( 0. K ) *> ) implies ( ( Col (A3,( j + 1 )) ) . k2 ) = ( <* ( 0. K ) *> . k2 )))
proof
(( j + 1 ) <= ( k + 1 ) & 1 < ( j + 1 )) by A48,A49,NAT_1:13,XREAL_1:7;
then A52: ( A3 * (1,( j + 1 )) ) = ( 0. K ) by A12;
let k2 being Nat;
assume k2 in ( dom <* ( 0. K ) *> );
then k2 in ( Seg ( len <* ( 0. K ) *> ) ) by FINSEQ_1:def 3;
then k2 in { 1 } by FINSEQ_1:2,FINSEQ_1:40;
then A53: k2 = 1 by TARSKI:def 1;
1 <= ( k + 1 ) by NAT_1:11;
then k2 in ( Seg ( len A3 ) ) by A29,A53,FINSEQ_1:1;
then k2 in ( dom A3 ) by FINSEQ_1:def 3;
then ( ( Col (A3,( j + 1 )) ) . k2 ) = ( 0. K ) by A53,A52,MATRIX_1:def 8;
hence thesis by A53,FINSEQ_1:40;
end;
A54: ( len ( Col (F,j) ) ) = ( len F ) by MATRIX_1:def 8
.= k by MATRIX_1:24;
A55: ( i + 1 ) <= ( k + 1 ) by A47,XREAL_1:7;
A56: (for k2 being Nat holds (k2 in ( dom <* ( 0. K ) *> ) implies ( ( Line (B3,( i + 1 )) ) . k2 ) = ( <* ( 0. K ) *> . k2 )))
proof
let k2 being Nat;
A57: 1 < ( i + 1 ) by A46,NAT_1:13;
1 <= ( 1 + k ) by NAT_1:11;
then A58: [ ( i + 1 ),1 ] in ( Indices ( 1. (K,( k + 1 )) ) ) by A55,A57,MATRIX_1:37;
A59: ( B3 * (( i + 1 ),1) ) = ( ( 1. (K,( k + 1 )) ) * (( i + 1 ),1) ) by A31,A55,A57
.= ( 0. K ) by A57,A58,MATRIX_1:def 11;
assume k2 in ( dom <* ( 0. K ) *> );
then k2 in ( Seg ( len <* ( 0. K ) *> ) ) by FINSEQ_1:def 3;
then k2 in { 1 } by FINSEQ_1:2,FINSEQ_1:40;
then A60: k2 = 1 by TARSKI:def 1;
1 <= ( k + 1 ) by NAT_1:11;
then k2 in ( Seg ( width B3 ) ) by A13,A60,FINSEQ_1:1;
then ( ( Line (B3,( i + 1 )) ) . k2 ) = ( 0. K ) by A60,A59,MATRIX_1:def 7;
hence thesis by A60,FINSEQ_1:40;
end;
A61: (for k2 being Nat holds (k2 in ( dom ( Col (F,j) ) ) implies ( ( Col (A3,( j + 1 )) ) . ( ( len <* ( 0. K ) *> ) + k2 ) ) = ( ( Col (F,j) ) . k2 )))
proof
reconsider j0 = ( j + 1 ) as (Element of ( NAT ));
let k2 being Nat;
A62: ( len ( Col (F,( j0 -' 1 )) ) ) = ( len F ) by MATRIX_1:def 8;
A63: ( j0 -' 1 ) = j by NAT_D:34;
assume A64: k2 in ( dom ( Col (F,j) ) );
then A65: k2 in ( Seg ( len ( Col (F,( j0 -' 1 )) ) ) ) by A63,FINSEQ_1:def 3;
then A66: k2 <= k by A26,A62,FINSEQ_1:1;
then (1 <= ( k2 + 1 ) & ( k2 + 1 ) <= ( k + 1 )) by NAT_1:11,XREAL_1:7;
then A67: ( k2 + 1 ) in ( dom A3 ) by A29,FINSEQ_3:25;
1 <= k2 by A65,FINSEQ_1:1;
then [ k2,j ] in ( Indices F ) by A48,A49,A66,MATRIX_1:37;
then [ k2,( j0 -' 1 ) ] in ( Indices F ) by NAT_D:34;
then A68: ( A3 * (( k2 + 1 ),( ( j0 -' 1 ) + 1 )) ) = ( F * (k2,( j0 -' 1 )) ) by A25;
k2 in ( Seg k ) by A26,A64,A62,A63,FINSEQ_1:def 3;
then k2 in ( dom F ) by A26,FINSEQ_1:def 3;
then ( A3 * (( k2 + 1 ),( ( j0 -' 1 ) + 1 )) ) = ( ( Col (F,( j0 -' 1 )) ) . k2 ) by A68,MATRIX_1:def 8;
hence thesis by A23,A63,A67,MATRIX_1:def 8;
end;
A69: ( len ( Line (G,i) ) ) = ( width G ) by MATRIX_1:def 7
.= k by MATRIX_1:24;
A70: ( k + 1 ) = ( ( len <* ( 0. K ) *> ) + k ) by FINSEQ_1:39;
A71: (for k2 being Nat holds (k2 in ( dom ( Line (G,i) ) ) implies ( ( Line (B3,( i + 1 )) ) . ( ( len <* ( 0. K ) *> ) + k2 ) ) = ( ( Line (G,i) ) . k2 )))
proof
let k2 being Nat;
A72: (( width B3 ) = ( k + 1 ) & 1 <= ( k2 + 1 )) by MATRIX_1:24,NAT_1:11;
assume A73: k2 in ( dom ( Line (G,i) ) );
then A74: k2 in ( Seg ( len ( Line (G,i) ) ) ) by FINSEQ_1:def 3;
A75: ( len ( Line (G,i) ) ) = ( width G ) by MATRIX_1:def 7
.= k by MATRIX_1:24;
then A76: k2 <= k by A74,FINSEQ_1:1;
1 <= k2 by A74,FINSEQ_1:1;
then [ i,k2 ] in ( Indices G ) by A46,A47,A76,MATRIX_1:37;
then A77: ( B3 * (( i + 1 ),( k2 + 1 )) ) = ( G * (i,k2) ) by A28;
k2 in ( Seg k ) by A73,A75,FINSEQ_1:def 3;
then k2 in ( Seg ( width G ) ) by MATRIX_1:24;
then A78: ( B3 * (( i + 1 ),( k2 + 1 )) ) = ( ( Line (G,i) ) . k2 ) by A77,MATRIX_1:def 7;
( k2 + 1 ) <= ( k + 1 ) by A76,XREAL_1:7;
then ( k2 + 1 ) in ( Seg ( width B3 ) ) by A72,FINSEQ_1:1;
then ( ( Line (B3,( i + 1 )) ) . ( k2 + 1 ) ) = ( ( Line (G,i) ) . k2 ) by A78,MATRIX_1:def 7;
hence thesis by FINSEQ_1:40;
end;
A79: ( width G ) = k by MATRIX_1:24;
(( len ( Line (B3,( i + 1 )) ) ) = ( width B3 ) & ( len ( Line (G,i) ) ) = ( width G )) by MATRIX_1:def 7;
then ( dom ( Line (B3,( i + 1 )) ) ) = ( Seg ( ( len <* ( 0. K ) *> ) + ( len ( Line (G,i) ) ) ) ) by A13,A79,A70,FINSEQ_1:def 3;
then A80: ( <* ( 0. K ) *> ^ ( Line (G,i) ) ) = ( Line (B3,( i + 1 )) ) by A56,A71,FINSEQ_1:def 7;
A81: (1 <= ( i + 1 ) & 1 <= ( j + 1 )) by NAT_1:11;
A82: ( j + 1 ) <= ( k + 1 ) by A49,XREAL_1:7;
A83:now
per cases ;
suppose A84: i = j;

[ ( i + 1 ),( j + 1 ) ] in ( Indices ( 1. (K,( k + 1 )) ) ) by A81,A55,A82,MATRIX_1:37;
then ( ( 1. (K,( k + 1 )) ) * (( i + 1 ),( j + 1 )) ) = ( 1. K ) by A84,MATRIX_1:def 11;
hence ( ( 1. (K,( k + 1 )) ) * (( i + 1 ),( j + 1 )) ) = ( IFEQ (i,j,( 1. K ),( 0. K )) ) by A84,FUNCOP_1:def 8;
end;
suppose A85: i <> j;

[ ( i + 1 ),( j + 1 ) ] in ( Indices ( 1. (K,( k + 1 )) ) ) by A81,A55,A82,MATRIX_1:37;
then (( i + 1 ) <> ( j + 1 ) implies ( ( 1. (K,( k + 1 )) ) * (( i + 1 ),( j + 1 )) ) = ( 0. K )) by MATRIX_1:def 11;
hence ( ( 1. (K,( k + 1 )) ) * (( i + 1 ),( j + 1 )) ) = ( IFEQ (i,j,( 1. K ),( 0. K )) ) by A85,FUNCOP_1:def 8;
end;
end;
(( len ( Col (A3,( j + 1 )) ) ) = ( len A3 ) & ( len ( Col (F,j) ) ) = ( len F )) by MATRIX_1:def 8;
then ( dom ( Col (A3,( j + 1 )) ) ) = ( Seg ( ( len <* ( 0. K ) *> ) + ( len ( Col (F,j) ) ) ) ) by A29,A26,A70,FINSEQ_1:def 3;
then A86: ( <* ( 0. K ) *> ^ ( Col (F,j) ) ) = ( Col (A3,( j + 1 )) ) by A51,A61,FINSEQ_1:def 7;
[ ( i + 1 ),( j + 1 ) ] in ( Indices ( B3 * A3 ) ) by A81,A55,A82,MATRIX_1:37;
then ( ( B3 * A3 ) * (( i + 1 ),( j + 1 )) ) = |( ( Line (B3,( i + 1 )) ),( Col (A3,( j + 1 )) ) )| by A13,A29,MATRIX_3:def 4
.= ( |( <* ( 0. K ) *>,<* ( 0. K ) *> )| + |( ( Line (G,i) ),( Col (F,j) ) )| ) by A23,A80,A86,A69,A54,CKB15:1
.= ( ( 0. K ) + |( ( Line (G,i) ),( Col (F,j) ) )| ) by CKB26:1
.= |( ( Line (G,i) ),( Col (F,j) ) )| by RLVECT_1:4;
hence thesis by A30,A26,A50,A79,A83,MATRIX_3:def 4;
end;
then ( G * F ) = ( 1. (K,k) ) by CKB35:1;
then consider G2 being (Matrix of k,K) such that A87: ( F * G2 ) = ( 1. (K,k) ) by A3;
deffunc h(Nat,Nat) = ( IFEQ ($1,1,( IFEQ ($2,1,( 1. K ),( 0. K )) ),( IFEQ ($2,1,( 0. K ),( G2 * (( $1 -' 1 ),( $2 -' 1 )) )) )) );
A88: ( len G2 ) = k by MATRIX_1:24;
consider B4 being (Matrix of ( k + 1 ),( k + 1 ),K) such that A89: (for i,j being Nat holds ([ i,j ] in ( Indices B4 ) implies ( B4 * (i,j) ) = h(i,j))) from MATRIX_1:sch 1;
A90: ( len B4 ) = ( k + 1 ) by MATRIX_1:24;
A91: ( width B4 ) = ( k + 1 ) by MATRIX_1:24;
A92: (for j being Nat holds ((1 <= j & j <= ( len ( Col (B4,1) ) )) implies ( ( Col (B4,1) ) . j ) = ( ( Base_FinSeq (K,( k + 1 ),1) ) . j )))
proof
let j being Nat;
assume that
A93: 1 <= j
and
A94: j <= ( len ( Col (B4,1) ) );
A95: j <= ( k + 1 ) by A90,A94,MATRIX_1:def 8;
then 1 <= ( k + 1 ) by A93,XXREAL_0:2;
then A96: [ j,1 ] in ( Indices B4 ) by A93,A95,MATRIX_1:37;
( len ( Col (B4,1) ) ) = ( len B4 ) by MATRIX_1:def 8;
then j in ( Seg ( width B4 ) ) by A90,A91,A93,A94,FINSEQ_1:1;
then A97: j in ( dom B4 ) by A90,A91,FINSEQ_1:def 3;
per cases  by A93,XXREAL_0:1;
suppose A98: 1 = j;

( ( Col (B4,1) ) . j ) = ( B4 * (j,1) ) by A97,MATRIX_1:def 8
.= ( IFEQ (j,1,( IFEQ (1,1,( 1. K ),( 0. K )) ),( IFEQ (1,1,( 0. K ),( G2 * (( j -' 1 ),( 1 -' 1 )) )) )) ) by A89,A96
.= ( IFEQ (1,1,( 1. K ),( 0. K )) ) by A98,FUNCOP_1:def 8
.= ( 1. K ) by FUNCOP_1:def 8;
hence thesis by A95,A98,CKB30:1;
end;
suppose A99: 1 < j;

( ( Col (B4,1) ) . j ) = ( B4 * (j,1) ) by A97,MATRIX_1:def 8
.= ( IFEQ (j,1,( IFEQ (1,1,( 1. K ),( 0. K )) ),( IFEQ (1,1,( 0. K ),( G2 * (( j -' 1 ),( 1 -' 1 )) )) )) ) by A89,A96
.= ( IFEQ (1,1,( 0. K ),( G2 * (( j -' 1 ),( 1 -' 1 )) )) ) by A99,FUNCOP_1:def 8
.= ( 0. K ) by FUNCOP_1:def 8;
hence thesis by A95,A99,CKB31:1;
end;
end;
A100: ( width ( A3 * B4 ) ) = ( k + 1 ) by MATRIX_1:24;
A101: ( Indices ( A3 * B4 ) ) = [: ( Seg ( k + 1 ) ),( Seg ( k + 1 ) ) :] by MATRIX_1:24;
( len ( Line (A3,1) ) ) = ( width A3 ) by MATRIX_1:def 7
.= ( k + 1 ) by MATRIX_1:24;
then A102: ( len ( Line (A3,1) ) ) = ( len ( Base_FinSeq (K,( k + 1 ),1) ) ) by CKB29:1;
then A103: ( Line (A3,1) ) = ( Base_FinSeq (K,( k + 1 ),1) ) by A15,FINSEQ_1:14;
A104: ( width F ) = k by MATRIX_1:24;
A105: 1 <= ( k + 1 ) by NAT_1:11;
( len ( Col (B4,1) ) ) = ( len B4 ) by MATRIX_1:def 8
.= ( k + 1 ) by MATRIX_1:24;
then A106: ( len ( Col (B4,1) ) ) = ( len ( Base_FinSeq (K,( k + 1 ),1) ) ) by CKB29:1;
then A107: ( Col (B4,1) ) = ( Base_FinSeq (K,( k + 1 ),1) ) by A92,FINSEQ_1:14;
(for i,j being Nat holds ([ i,j ] in ( Indices ( A3 * B4 ) ) implies ( ( A3 * B4 ) * (i,j) ) = ( ( 1. (K,( k + 1 )) ) * (i,j) )))
proof
let i being Nat,j being Nat;
reconsider i0 = i,j0 = j as (Element of ( NAT )) by ORDINAL1:def 12;
A108: ( len ( Line (F,( i -' 1 )) ) ) = ( width F ) by MATRIX_1:def 7
.= k by MATRIX_1:24;
A109: ( len ( Col (G2,( j -' 1 )) ) ) = ( len G2 ) by MATRIX_1:def 8
.= k by MATRIX_1:24;
A110: ( len ( Line (A3,i) ) ) = ( width A3 ) by MATRIX_1:def 7
.= ( k + 1 ) by MATRIX_1:24;
A111: ( len ( Col (B4,j) ) ) = ( len B4 ) by MATRIX_1:def 8
.= ( k + 1 ) by MATRIX_1:24;
assume A112: [ i,j ] in ( Indices ( A3 * B4 ) );
then A113: [ i,j ] in [: ( Seg ( k + 1 ) ),( Seg ( k + 1 ) ) :] by MATRIX_1:24;
then A114: [ i,j ] in ( Indices ( 1. (K,( k + 1 )) ) ) by MATRIX_1:24;
A115: i in ( Seg ( k + 1 ) ) by A101,A112,ZFMISC_1:87;
then A116: 1 <= i by FINSEQ_1:1;
A117: i <= ( k + 1 ) by A115,FINSEQ_1:1;
A118: j in ( Seg ( k + 1 ) ) by A100,A112,ZFMISC_1:87;
then A119: 1 <= j by FINSEQ_1:1;
A120: ( len B4 ) = ( k + 1 ) by MATRIX_1:24;
A121: ( width A3 ) = ( k + 1 ) by MATRIX_1:24;
A122: j <= ( k + 1 ) by A118,FINSEQ_1:1;
A123: [ i,j ] in ( Indices B4 ) by A101,A112,MATRIX_1:24;
now
per cases  by A116,XXREAL_0:1;
suppose A124: i = 1;

now
per cases  by A119,XXREAL_0:1;
suppose A125: j = 1;

( ( A3 * B4 ) * (i,j) ) = |( ( Line (A3,i0) ),( Col (B4,j0) ) )| by A112,A120,A121,MATRIX_3:def 4
.= ( 1. K ) by A103,A107,A105,A124,A125,CKB42:1;
hence thesis by A114,A124,A125,MATRIX_1:def 11;
end;
suppose A126: j > 1;

1 <= ( len B4 ) by A105,MATRIX_1:24;
then A127: 1 in ( dom B4 ) by FINSEQ_3:25;
( ( A3 * B4 ) * (i,j) ) = |( ( Line (A3,i0) ),( Col (B4,j0) ) )| by A112,A120,A121,MATRIX_3:def 4
.= |( ( Base_FinSeq (K,( k + 1 ),1) ),( Col (B4,j0) ) )| by A102,A15,A124,FINSEQ_1:14
.= |( ( Col (B4,j0) ),( Base_FinSeq (K,( k + 1 ),1) ) )| by FVSUM_1:90
.= ( ( Col (B4,j0) ) . 1 ) by A105,A111,CKB41:1
.= ( B4 * (1,j) ) by A127,MATRIX_1:def 8
.= ( IFEQ (i,1,( IFEQ (j,1,( 1. K ),( 0. K )) ),( IFEQ (j,1,( 0. K ),( G2 * (( i -' 1 ),( j -' 1 )) )) )) ) by A89,A123,A124
.= ( IFEQ (j,1,( 1. K ),( 0. K )) ) by A124,FUNCOP_1:def 8
.= ( 0. K ) by A126,FUNCOP_1:def 8;
hence thesis by A4,A113,A124,A126,MATRIX_1:def 11;
end;
end;
hence thesis;
end;
suppose A128: 1 < i;

then A129: ( 1 + 1 ) <= i by NAT_1:13;
now
per cases  by A119,XXREAL_0:1;
suppose A130: j = 1;

A131: 1 in ( Seg ( width A3 ) ) by A14,A105,FINSEQ_1:1;
A132: ( len ( Line (A3,i) ) ) = ( width A3 ) by MATRIX_1:def 7
.= ( k + 1 ) by MATRIX_1:24;
( ( A3 * B4 ) * (i,j) ) = |( ( Line (A3,i0) ),( Col (B4,j0) ) )| by A112,A120,A121,MATRIX_3:def 4
.= |( ( Line (A3,i) ),( Base_FinSeq (K,( k + 1 ),1) ) )| by A106,A92,A130,FINSEQ_1:14
.= ( ( Line (A3,i) ) . 1 ) by A105,A132,CKB41:1
.= ( ( ( B * A2 ) * C ) * (i0,1) ) by A131,MATRIX_1:def 7
.= ( 0. K ) by A11,A117,A128;
hence thesis by A114,A128,A130,MATRIX_1:def 11;
end;
suppose A133: j > 1;

then ( 1 + 1 ) <= j by NAT_1:13;
then A134: 1 <= ( j - 1 ) by XREAL_1:19;
A135: ( i -' 1 ) = ( i - 1 ) by A128,XREAL_1:233;
then A136: ( i -' 1 ) <= k by A117,XREAL_1:20;
A137: 1 <= ( i - 1 ) by A129,XREAL_1:19;
then A138: ( i -' 1 ) in ( Seg k ) by A135,A136,FINSEQ_1:1;
A139: ( len ( Line (F,( i -' 1 )) ) ) = ( width F ) by MATRIX_1:def 7
.= k by MATRIX_1:24;
A140: (for k2 being Nat holds (k2 in ( dom ( Line (F,( i -' 1 )) ) ) implies ( ( Line (A3,( ( i -' 1 ) + 1 )) ) . ( ( len <* ( 0. K ) *> ) + k2 ) ) = ( ( Line (F,( i -' 1 )) ) . k2 )))
proof
let k2 being Nat;
assume A141: k2 in ( dom ( Line (F,( i -' 1 )) ) );
then A142: k2 in ( Seg ( len ( Line (F,( i -' 1 )) ) ) ) by FINSEQ_1:def 3;
then A143: k2 <= k by A139,FINSEQ_1:1;
then (1 <= ( k2 + 1 ) & ( k2 + 1 ) <= ( k + 1 )) by NAT_1:11,XREAL_1:7;
then A144: ( k2 + 1 ) in ( Seg ( width A3 ) ) by A121,FINSEQ_1:1;
1 <= k2 by A142,FINSEQ_1:1;
then [ ( i -' 1 ),k2 ] in ( Indices F ) by A135,A137,A136,A143,MATRIX_1:37;
then A145: ( A3 * (( ( i -' 1 ) + 1 ),( k2 + 1 )) ) = ( F * (( i -' 1 ),k2) ) by A25;
k2 in ( Seg ( width F ) ) by A104,A139,A141,FINSEQ_1:def 3;
then ( A3 * (( ( i -' 1 ) + 1 ),( k2 + 1 )) ) = ( ( Line (F,( i -' 1 )) ) . k2 ) by A145,MATRIX_1:def 7;
then ( ( Line (A3,( ( i -' 1 ) + 1 )) ) . ( k2 + 1 ) ) = ( ( Line (F,( i -' 1 )) ) . k2 ) by A144,MATRIX_1:def 7;
hence thesis by FINSEQ_1:40;
end;
A146: (for k2 being Nat holds (k2 in ( dom <* ( 0. K ) *> ) implies ( ( Line (A3,( ( i -' 1 ) + 1 )) ) . k2 ) = ( <* ( 0. K ) *> . k2 )))
proof
let k2 being Nat;
assume k2 in ( dom <* ( 0. K ) *> );
then k2 in ( Seg ( len <* ( 0. K ) *> ) ) by FINSEQ_1:def 3;
then k2 in { 1 } by FINSEQ_1:2,FINSEQ_1:40;
then A147: k2 = 1 by TARSKI:def 1;
A148: ( A3 * (i0,1) ) = ( 0. K ) by A11,A117,A128;
1 <= ( k + 1 ) by NAT_1:11;
then k2 in ( Seg ( width A3 ) ) by A121,A147,FINSEQ_1:1;
then ( ( Line (A3,i) ) . k2 ) = ( 0. K ) by A147,A148,MATRIX_1:def 7;
hence thesis by A135,A147,FINSEQ_1:40;
end;
( dom ( Line (A3,( ( i -' 1 ) + 1 )) ) ) = ( Seg ( k + 1 ) ) by A110,A135,FINSEQ_1:def 3
.= ( Seg ( ( len <* ( 0. K ) *> ) + ( len ( Line (F,( i -' 1 )) ) ) ) ) by A139,FINSEQ_1:39;
then A149: ( <* ( 0. K ) *> ^ ( Line (F,( i -' 1 )) ) ) = ( Line (A3,( ( i -' 1 ) + 1 )) ) by A146,A140,FINSEQ_1:def 7;
A150: ( ( j -' 1 ) + 1 ) = ( ( j - 1 ) + 1 ) by A133,XREAL_1:233
.= j;
A151: ( j -' 1 ) = ( j - 1 ) by A133,XREAL_1:233;
then ( j -' 1 ) <= k by A122,XREAL_1:20;
then ( j -' 1 ) in ( Seg k ) by A151,A134,FINSEQ_1:1;
then A152: [ ( i -' 1 ),( j -' 1 ) ] in [: ( Seg k ),( Seg k ) :] by A138,ZFMISC_1:87;
then A153: [ ( i -' 1 ),( j -' 1 ) ] in ( Indices ( F * G2 ) ) by MATRIX_1:24;
A154: (for k2 being Nat holds (k2 in ( dom <* ( 0. K ) *> ) implies ( ( Col (B4,( ( j -' 1 ) + 1 )) ) . k2 ) = ( <* ( 0. K ) *> . k2 )))
proof
1 <= ( 1 + k ) by NAT_1:11;
then [ 1,j ] in ( Indices B4 ) by A119,A122,MATRIX_1:37;
then ( B4 * (1,j) ) = ( IFEQ (1,1,( IFEQ (j,1,( 1. K ),( 0. K )) ),( IFEQ (j,1,( 0. K ),( G2 * (( 1 -' 1 ),( j -' 1 )) )) )) ) by A89;
then A155: ( B4 * (1,j) ) = ( IFEQ (j,1,( 1. K ),( 0. K )) ) by FUNCOP_1:def 8
.= ( 0. K ) by A133,FUNCOP_1:def 8;
let k2 being Nat;
assume k2 in ( dom <* ( 0. K ) *> );
then k2 in ( Seg ( len <* ( 0. K ) *> ) ) by FINSEQ_1:def 3;
then k2 in { 1 } by FINSEQ_1:2,FINSEQ_1:40;
then A156: k2 = 1 by TARSKI:def 1;
1 <= ( k + 1 ) by NAT_1:11;
then k2 in ( Seg ( len B4 ) ) by A120,A156,FINSEQ_1:1;
then k2 in ( dom B4 ) by FINSEQ_1:def 3;
then ( ( Col (B4,j) ) . k2 ) = ( 0. K ) by A156,A155,MATRIX_1:def 8;
hence thesis by A151,A156,FINSEQ_1:40;
end;
A157: ( len ( Col (G2,( j -' 1 )) ) ) = ( len G2 ) by MATRIX_1:def 8
.= k by MATRIX_1:24;
A158: (for k2 being Nat holds (k2 in ( dom ( Col (G2,( j -' 1 )) ) ) implies ( ( Col (B4,( ( j -' 1 ) + 1 )) ) . ( ( len <* ( 0. K ) *> ) + k2 ) ) = ( ( Col (G2,( j -' 1 )) ) . k2 )))
proof
let k2 being Nat;
assume A159: k2 in ( dom ( Col (G2,( j -' 1 )) ) );
then 1 <= k2 by FINSEQ_3:25;
then A160: 1 < ( k2 + 1 ) by NAT_1:13;
k2 in ( Seg k ) by A157,A159,FINSEQ_1:def 3;
then A161: k2 in ( dom G2 ) by A88,FINSEQ_1:def 3;
k2 <= k by A157,A159,FINSEQ_3:25;
then A162: (1 <= ( k2 + 1 ) & ( k2 + 1 ) <= ( k + 1 )) by NAT_1:11,XREAL_1:7;
then [ ( k2 + 1 ),j ] in ( Indices B4 ) by A119,A122,MATRIX_1:37;
then ( B4 * (( k2 + 1 ),j) ) = ( IFEQ (( k2 + 1 ),1,( IFEQ (j,1,( 1. K ),( 0. K )) ),( IFEQ (j,1,( 0. K ),( G2 * (( ( k2 + 1 ) -' 1 ),( j -' 1 )) )) )) ) by A89;
then ( B4 * (( k2 + 1 ),j) ) = ( IFEQ (j,1,( 0. K ),( G2 * (( ( k2 + 1 ) -' 1 ),( j -' 1 )) )) ) by A160,FUNCOP_1:def 8
.= ( G2 * (( ( k2 + 1 ) -' 1 ),( j -' 1 )) ) by A133,FUNCOP_1:def 8
.= ( G2 * (k2,( j -' 1 )) ) by NAT_D:34;
then A163: ( B4 * (( k2 + 1 ),( ( j -' 1 ) + 1 )) ) = ( ( Col (G2,( j -' 1 )) ) . k2 ) by A151,A161,MATRIX_1:def 8;
( k2 + 1 ) in ( dom B4 ) by A120,A162,FINSEQ_3:25;
then ( ( Col (B4,( ( j -' 1 ) + 1 )) ) . ( k2 + 1 ) ) = ( ( Col (G2,( j -' 1 )) ) . k2 ) by A163,MATRIX_1:def 8;
hence thesis by FINSEQ_1:40;
end;
( dom ( Col (B4,( ( j -' 1 ) + 1 )) ) ) = ( Seg ( len ( Col (B4,( ( j -' 1 ) + 1 )) ) ) ) by FINSEQ_1:def 3
.= ( Seg ( ( len <* ( 0. K ) *> ) + ( len ( Col (G2,( j -' 1 )) ) ) ) ) by A111,A151,A157,FINSEQ_1:39;
then A164: ( <* ( 0. K ) *> ^ ( Col (G2,( j -' 1 )) ) ) = ( Col (B4,( ( j -' 1 ) + 1 )) ) by A154,A158,FINSEQ_1:def 7;
( ( i -' 1 ) + 1 ) = ( ( i - 1 ) + 1 ) by A128,XREAL_1:233
.= i;
then A165: ( ( A3 * B4 ) * (i,j) ) = |( ( Line (A3,( ( i -' 1 ) + 1 )) ),( Col (B4,( ( j -' 1 ) + 1 )) ) )| by A112,A120,A121,A150,MATRIX_3:def 4
.= ( |( <* ( 0. K ) *>,<* ( 0. K ) *> )| + |( ( Line (F,( i -' 1 )) ),( Col (G2,( j -' 1 )) ) )| ) by A23,A108,A109,A149,A164,CKB15:1
.= ( ( 0. K ) + |( ( Line (F,( i -' 1 )) ),( Col (G2,( j -' 1 )) ) )| ) by CKB26:1
.= ( ( 0. K ) + ( ( F * G2 ) * (( i -' 1 ),( j -' 1 )) ) ) by A104,A88,A153,MATRIX_3:def 4
.= ( ( 1. (K,k) ) * (( i -' 1 ),( j -' 1 )) ) by A87,RLVECT_1:4;
A166: [ ( i -' 1 ),( j -' 1 ) ] in ( Indices ( 1. (K,k) ) ) by A152,MATRIX_1:24;
now
per cases ;
suppose A167: i = j;

then ( ( 1. (K,( k + 1 )) ) * (i0,j0) ) = ( 1. K ) by A114,MATRIX_1:def 11;
hence thesis by A166,A165,A167,MATRIX_1:def 11;
end;
suppose A168: i <> j;

then ( i - 1 ) <> ( j - 1 );
then ( i0 -' 1 ) <> ( j0 -' 1 ) by A128,A151,XREAL_1:233;
then ( ( 1. (K,k) ) * (( i0 -' 1 ),( j0 -' 1 )) ) = ( 0. K ) by A166,MATRIX_1:def 11;
hence thesis by A114,A165,A168,MATRIX_1:def 11;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
then (( width ( Inv B ) ) = ( k + 1 ) & ( ( ( B * A2 ) * C ) * B4 ) = ( 1. (K,( k + 1 )) )) by MATRIX_1:24,MATRIX_1:27;
then ( ( Inv B ) * ( ( ( B * A2 ) * C ) * B4 ) ) = ( Inv B ) by MATRIXR2:67;
then ( ( ( Inv B ) * ( ( ( B * A2 ) * C ) * B4 ) ) * B ) = ( 1. (K,( k + 1 )) ) by A8,CKB22:1;
then ( ( ( Inv B ) * ( ( B * A2 ) * ( C * B4 ) ) ) * B ) = ( 1. (K,( k + 1 )) ) by CKB21:1;
then ( ( ( Inv B ) * ( B * ( A2 * ( C * B4 ) ) ) ) * B ) = ( 1. (K,( k + 1 )) ) by CKB21:1;
then ( ( ( ( Inv B ) * B ) * ( A2 * ( C * B4 ) ) ) * B ) = ( 1. (K,( k + 1 )) ) by CKB21:1;
then (( len ( A2 * ( C * B4 ) ) ) = ( k + 1 ) & ( ( ( 1. (K,( k + 1 )) ) * ( A2 * ( C * B4 ) ) ) * B ) = ( 1. (K,( k + 1 )) )) by A8,CKB22:1,MATRIX_1:24;
then ( ( A2 * ( C * B4 ) ) * B ) = ( 1. (K,( k + 1 )) ) by MATRIXR2:68;
then ( A2 * ( ( C * B4 ) * B ) ) = ( 1. (K,( k + 1 )) ) by CKB21:1;
hence thesis;
end;
hence thesis;
end;
(for D,B0 being (Matrix of ( 0 ),K) holds (( B0 * D ) = ( 1. (K,( 0 )) ) implies (ex B1 being (Matrix of ( 0 ),K) st ( D * B1 ) = ( 1. (K,( 0 )) ))))
proof
let D being (Matrix of ( 0 ),K),B0 being (Matrix of ( 0 ),K);
assume ( B0 * D ) = ( 1. (K,( 0 )) );
( D * ( 0. (K,( 0 )) ) ) = ( 1. (K,( 0 )) ) by CKB19:1;
hence thesis;
end;
then A169: P[ ( 0 ) ];
(for k being (Element of ( NAT )) holds P[ k ]) from NAT_1:sch 1(A169,A2);
hence thesis by A1;
end;

end;
