environ
vocabularies NUMBERS,TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,ZFMISC_1,PROB_1,FINSUB_1,FUNCT_1,SUPINF_2,XXREAL_0,MSSUBFAM,ARYTM_3,VALUED_0,FUNCOP_1,ARYTM_1,RELAT_1,CARD_3,CARD_1,NAT_1,EQREL_1,PROB_2,SUPINF_1,MEASURE1,FUNCT_7;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,NUMBERS,XXREAL_0,RELAT_1,FINSUB_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,NAT_1,SETFAM_1,FUNCOP_1,PROB_1,PROB_2,VALUED_0,FUNCT_7,SUPINF_1,SUPINF_2,CKB5,CKB8,CKB15,CKB16;
definitions SUPINF_2,TARSKI,FINSUB_1,PROB_2,PROB_1,XBOOLE_0,SUBSET_1,FUNCT_1,RELAT_1,XXREAL_3,CKB8,CKB15,CKB16;
theorems TARSKI,FUNCT_1,FUNCT_2,ENUMSET1,ZFMISC_1,NAT_1,SETFAM_1,SUPINF_2,RELAT_1,FUNCOP_1,FINSUB_1,PROB_2,PROB_1,SUBSET_1,XBOOLE_0,XBOOLE_1,XXREAL_0,CARD_3,ORDINAL1,VALUED_0,XXREAL_3,FUNCT_7,CKB1,CKB2,CKB3,CKB7,CKB8,CKB11,CKB13,CKB14,CKB15,CKB16;
schemes FUNCT_2,XBOOLE_0,CKB4;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FUNCT_2,NUMBERS,MEMBERED,PROB_1,VALUED_0,FINSUB_1,RELAT_1,FUNCT_1,CKB6,CKB9,CKB10,CKB12;
constructors ENUMSET1,PARTFUN1,FUNCOP_1,FINSUB_1,REAL_1,NAT_1,PROB_2,SUPINF_2,SUPINF_1,RELSET_1,FUNCT_7,CKB15,CKB16;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve X for set;
registration
let X being set;
let S being (Field_Subset of X);
cluster  nonnegative  additive  zeroed for (Function of S,( ExtREAL ));
existence
proof
reconsider M = ( S --> ( 0. ) ) as (Function of S,( ExtREAL ));
A1: (for A,B being (Element of S) holds (A misses B implies ( M . ( A \/ B ) ) = ( ( M . A ) + ( M . B ) )))
proof
let A being (Element of S);
let B being (Element of S);
assume A misses B;
A2: (( M . A ) = ( 0. ) & ( M . B ) = ( 0. )) by FUNCOP_1:7;
reconsider A,B as set;
reconsider A,B as (Element of S);
( 0. ) = ( ( M . A ) + ( M . B ) ) by A2,XXREAL_3:4;
hence thesis by FUNCOP_1:7;
end;
take M;
((for x being (Element of S) holds ( 0. ) <= ( M . x )) & ( M . ( {} ) ) = ( 0. )) by FUNCOP_1:7,PROB_1:4;
hence thesis by A1,CKB15:def 1,CKB16:def 1,VALUED_0:def 19;
end;
end;
