environ
vocabularies NUMBERS,PRE_TOPC,EUCLID,FINSEQ_1,XREAL_0,ORDINAL1,SUBSET_1,RELAT_1,ARYTM_3,MCART_1,ARYTM_1,FUNCT_1,SQUARE_1,BINOP_2,COMPLEX1,RVSUM_1,CARD_3,NAT_1,STRUCT_0,REAL_1,XXREAL_0,RLTOPSP1,TARSKI,CARD_1,XBOOLE_0,TOPREAL1,PARTFUN1,ORDINAL4,METRIC_1;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,SQUARE_1,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_1,PARTFUN1,FINSEQ_1,BINOP_1,PRE_TOPC,FINSEQ_2,STRUCT_0,METRIC_1,RVSUM_1,RLVECT_1,RLTOPSP1,EUCLID,TOPREAL1,XXREAL_0;
definitions TARSKI,TOPREAL1,FUNCT_1,XBOOLE_0,SQUARE_1,EUCLID,RVSUM_1,VALUED_1,ALGSTR_0,RLTOPSP1;
theorems TARSKI,NAT_1,ZFMISC_1,FUNCT_1,FINSEQ_1,ABSVALUE,SQUARE_1,FINSEQ_2,METRIC_1,RVSUM_1,EUCLID,TOPREAL1,FINSEQ_3,FINSEQ_4,PARTFUN2,TBSP_1,RELAT_1,INT_1,XBOOLE_0,XBOOLE_1,XCMPLX_1,XREAL_0,COMPLEX1,XREAL_1,BINOP_2,XXREAL_0,ORDINAL1,RLTOPSP1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
registrations XBOOLE_0,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,SQUARE_1,NAT_1,MEMBERED,FINSEQ_1,STRUCT_0,EUCLID,VALUED_0;
constructors PARTFUN1,REAL_1,SQUARE_1,NAT_1,BINOP_2,COMPLEX1,FINSEQOP,FINSEQ_4,TOPREAL1,SEQ_1,RVSUM_1,RELSET_1,DOMAIN_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve p1 for (Point of ( TOP-REAL 2 ));
reserve p2 for (Point of ( TOP-REAL 2 ));
reserve p3 for (Point of ( TOP-REAL 2 ));
reserve f for (FinSequence of ( TOP-REAL 2 ));
reserve i for (Element of ( NAT ));
reserve j for (Element of ( NAT ));
reserve x for set;
theorem
(f = <* p1,p2,p3 *> implies ( L~ f ) = ( ( LSeg (p1,p2) ) \/ ( LSeg (p2,p3) ) ))
proof
set M = { ( LSeg (f,i) ): (1 <= i & ( i + 1 ) <= ( len f )) };
assume A1: f = <* p1,p2,p3 *>;
then A2: ( len f ) = ( 2 + 1 ) by FINSEQ_1:45;
A3: ( f /. 3 ) = p3 by A1,FINSEQ_4:18;
A4: ( f /. 1 ) = p1 by A1,FINSEQ_4:18;
A5: ( f /. 2 ) = p2 by A1,FINSEQ_4:18;
A6: ( 1 + 1 ) in ( dom f ) by A1,CKB1:1;
M = { ( LSeg (p1,p2) ),( LSeg (p2,p3) ) }
proof
thus M c= { ( LSeg (p1,p2) ),( LSeg (p2,p3) ) }
proof
let x;
assume x in M;
then consider j such that A7: x = ( LSeg (f,j) ) and A8: 1 <= j and A9: ( j + 1 ) <= ( len f );
A10: j <= 2 by A2,A9,XREAL_1:6;
per cases  by A8,A10,NAT_1:26;
suppose j = 1;

then x = ( LSeg (p1,p2) ) by A4,A5,A7,A9,TOPREAL1:def 3;
hence thesis by TARSKI:def 2;
end;
suppose j = 2;

then x = ( LSeg (p2,p3) ) by A2,A5,A3,A7,TOPREAL1:def 3;
hence thesis by TARSKI:def 2;
end;
end;

let x;
assume that
A11: x in { ( LSeg (p1,p2) ),( LSeg (p2,p3) ) };
per cases  by A11,TARSKI:def 2;
suppose A12: x = ( LSeg (p1,p2) );

A13: ( 1 + 1 ) <= ( len f ) by A2;
x = ( LSeg (f,1) ) by A2,A4,A5,A6,A12,TOPREAL1:def 3;
hence thesis by A13;
end;
suppose x = ( LSeg (p2,p3) );

then x = ( LSeg (f,2) ) by A2,A5,A3,TOPREAL1:def 3;
hence thesis by A2;
end;
end;
hence thesis by ZFMISC_1:75;
end;
