environ
vocabularies NUMBERS,XBOOLE_0,PROB_1,MEASURE1,PARTFUN1,SUBSET_1,REAL_1,INTEGRA5,TARSKI,RELAT_1,FUNCT_1,ARYTM_3,XXREAL_0,MEASURE6,MESFUNC5,FUNCT_3,VALUED_1,MESFUNC1,ARYTM_1,SUPINF_2,MESFUNC2,FINSEQ_1,NAT_1,CARD_3,CARD_1,MESFUNC3,INTEGRA1,ZFMISC_1,XXREAL_2,VALUED_0,SEQ_1,RPR_1,FINSET_1,UPROOTS,RFUNCT_3,PROB_4,XREAL_0,ORDINAL1,COMPLEX1,EQREL_1,SEQ_2,ORDINAL2,POWER,RANDOM_1,BSPACE;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,FINSET_1,CARD_1,NUMBERS,XREAL_0,XXREAL_0,REAL_1,COMPLEX1,XXREAL_2,FUNCT_1,RELSET_1,PARTFUN1,VALUED_1,FINSEQ_1,RFUNCT_3,FUNCT_2,NAT_1,SUPINF_2,SEQ_1,SEQ_2,RPR_1,PROB_1,PROB_4,MEASURE1,EXTREAL1,MESFUNC1,MESFUNC3,MEASURE6,MESFUNC5,MESFUNC6,MESFUNC2,RVSUM_1,UPROOTS,MESFUN6C;
definitions TARSKI,RPR_1,SUBSET_1,FINSEQ_1,MESFUNC1,MEASURE6,MESFUNC5,MESFUNC6,XCMPLX_0,PROB_4,VALUED_1,XBOOLE_0,XXREAL_3;
theorems ABSVALUE,TARSKI,PARTFUN1,FUNCT_1,NUMBERS,SUPINF_2,EXTREAL1,RPR_1,MESFUNC1,FINSEQ_1,XBOOLE_0,SEQM_3,RVSUM_1,XBOOLE_1,XCMPLX_1,MESFUNC2,MESFUNC3,XREAL_1,COMPLEX1,XXREAL_0,RFUNCT_3,MESFUNC5,PROB_1,NAT_1,RELAT_1,FUNCT_3,ZFMISC_1,FUNCT_2,MEASURE1,INTEGRA5,MESFUNC4,MESFUNC6,ORDINAL1,SEQ_2,CARD_FIN,MESFUNC7,VALUED_0,VALUED_1,UPROOTS,ABCMIZ_1,RCOMP_1,MESFUN6C,FINSEQ_3,XXREAL_3,CKB1,CKB2;
schemes FINSEQ_1,FUNCT_2,FINSEQ_2;
registrations SUBSET_1,NAT_1,XREAL_0,XXREAL_0,TOPREAL6,MEMBERED,ORDINAL1,FINSEQ_1,MEASURE1,FUNCT_2,RELAT_1,SEQ_4,FINSET_1,NUMBERS,XCMPLX_0,VALUED_0,VALUED_1,UPROOTS,RELSET_1;
constructors REAL_1,RPR_1,NAT_3,EXTREAL1,SEQ_1,POWER,RVSUM_1,MESFUNC6,MESFUNC3,MESFUNC5,MEASURE6,MESFUNC2,BINOP_2,PARTFUN3,INTEGRA2,PROB_4,SUPINF_1,UPROOTS,MESFUN6C,MESFUNC1,DOMAIN_1,RELSET_1;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
theorem
Th3: (for X being non  empty set holds (for S being (SigmaField of X) holds (for M being (sigma_Measure of S) holds (for f being (PartFunc of X,( ExtREAL )) holds (for E being (Element of S) holds (for a being Real holds ((((f is_integrable_on M & E c= ( dom f )) & ( M . E ) < ( +infty )) & (for x being (Element of X) holds (x in E implies ( f . x ) <= a))) implies ( Integral (M,( f | E )) ) <= ( ( R_EAL a ) * ( M . E ) ))))))))
proof
let X being non  empty set;
let S being (SigmaField of X);
let M being (sigma_Measure of S);
let f being (PartFunc of X,( ExtREAL ));
let E being (Element of S);
let a being Real;
assume that
A1: f is_integrable_on M
and
A2: E c= ( dom f )
and
A3: ( M . E ) < ( +infty )
and
A4: (for x being (Element of X) holds (x in E implies ( f . x ) <= a));
set C = ( chi (E,X) );
A5: ( f | E ) is_integrable_on M by A1,MESFUNC5:97;
( dom ( a (#) ( C | E ) ) ) = ( dom ( C | E ) ) by MESFUNC1:def 6;
then ( dom ( a (#) ( C | E ) ) ) = ( ( dom C ) /\ E ) by RELAT_1:61;
then ( dom ( a (#) ( C | E ) ) ) = ( X /\ E ) by FUNCT_3:def 3;
then A6: ( dom ( a (#) ( C | E ) ) ) = E by XBOOLE_1:28;
( dom ( f | E ) ) = ( ( dom f ) /\ E ) by RELAT_1:61;
then A7: ( dom ( f | E ) ) = E by A2,XBOOLE_1:28;
(for x being (Element of X) holds (x in ( dom ( f | E ) ) implies ( ( f | E ) . x ) <= ( ( a (#) ( C | E ) ) . x )))
proof
let x being (Element of X);
assume A8: x in ( dom ( f | E ) );
then A9: x in ( dom ( C | E ) ) by A7,A6,MESFUNC1:def 6;
then x in ( ( dom C ) /\ E ) by RELAT_1:61;
then A10: x in E by XBOOLE_0:def 4;
then ( f . x ) <= a by A4;
then A11: ( ( f | E ) . x ) <= a by A10,FUNCT_1:49;
( ( a (#) ( C | E ) ) . x ) = ( ( R_EAL a ) * ( ( C | E ) . x ) ) by A7,A6,A8,MESFUNC1:def 6
.= ( ( R_EAL a ) * ( C . x ) ) by A9,FUNCT_1:47
.= ( ( R_EAL a ) * ( 1. ) ) by A10,FUNCT_3:def 3;
hence thesis by A11,XXREAL_3:81;
end;
then A12: ( ( a (#) ( C | E ) ) - ( f | E ) ) is  nonnegative by MESFUNC7:1;
( dom ( a (#) ( C | E ) ) ) = ( dom ( C | E ) ) by MESFUNC1:def 6;
then ( dom ( a (#) ( C | E ) ) ) = ( ( dom C ) /\ E ) by RELAT_1:61;
then ( dom ( a (#) ( C | E ) ) ) = ( X /\ E ) by FUNCT_3:def 3;
then A13: ( dom ( a (#) ( C | E ) ) ) = E by XBOOLE_1:28;
E = ( E /\ E );
then A14: ( Integral (M,( C | E )) ) = ( M . E ) by A3,MESFUNC7:25;
( chi (E,X) ) is_integrable_on M by A3,MESFUNC7:24;
then A15: ( C | E ) is_integrable_on M by MESFUNC5:97;
then ( a (#) ( C | E ) ) is_integrable_on M by MESFUNC5:110;
then consider E1 being (Element of S) such that A16: E1 = ( ( dom ( f | E ) ) /\ ( dom ( a (#) ( C | E ) ) ) ) and A17: ( Integral (M,( ( f | E ) | E1 )) ) <= ( Integral (M,( ( a (#) ( C | E ) ) | E1 )) ) by A5,A12,MESFUNC7:3;
( dom ( f | E ) ) = ( ( dom f ) /\ E ) by RELAT_1:61;
then ( dom ( f | E ) ) = E by A2,XBOOLE_1:28;
then (( ( a (#) ( C | E ) ) | E1 ) = ( a (#) ( C | E ) ) & ( ( f | E ) | E1 ) = ( f | E )) by A16,A13,RELAT_1:69;
hence thesis by A15,A17,A14,MESFUNC5:110;
end;
