environ
vocabularies PRE_TOPC,SUBSET_1,TARSKI,TOPS_1,XBOOLE_0,SETFAM_1,RCOMP_1,FUNCT_1,RELAT_1,ORDINAL2,DECOMP_1;
notations TARSKI,XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,PRE_TOPC,TOPS_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
definitions TARSKI,XBOOLE_0,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
theorems TOPS_1,PRE_TOPC,TOPS_2,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41;
schemes DOMAIN_1;
registrations SUBSET_1,PRE_TOPC,STRUCT_0,TOPS_1;
constructors TOPS_1,RELSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
requirements SUBSET;
begin
reserve T for TopSpace;
reserve B for (Subset of T);
theorem
Th17: ( ( PSO T ) /\ ( D(sp,ps) T ) ) = ( SPO T )
proof
thus ( ( PSO T ) /\ ( D(sp,ps) T ) ) c= ( SPO T )
proof
let x being set;
assume A1: x in ( ( PSO T ) /\ ( D(sp,ps) T ) );
then x in ( PSO T ) by XBOOLE_0:def 4;
then consider A being (Subset of T) such that A2: x = A and A3: A is  pre-semi-open;
x in ( D(sp,ps) T ) by A1,XBOOLE_0:def 4;
then consider Z being (Subset of T) such that A4: x = Z and A5: ( spInt Z ) = ( psInt Z );
A = ( psInt A ) by A3,CKB30:1;
then Z is  semi-pre-open by A2,A4,A5,CKB31:1;
hence thesis by A4;
end;

let x being set;
assume x in ( SPO T );
then consider K being (Subset of T) such that A6: x = K and A7: K is  semi-pre-open;
( Cl ( Int K ) ) c= ( Cl K ) by PRE_TOPC:19,TOPS_1:16;
then ( Int ( Cl ( Int K ) ) ) c= ( Int ( Cl K ) ) by TOPS_1:19;
then ( Cl ( Int ( Cl ( Int K ) ) ) ) c= ( Cl ( Int ( Cl K ) ) ) by PRE_TOPC:19;
then A8: ( Cl ( Int K ) ) c= ( Cl ( Int ( Cl K ) ) ) by TOPS_1:26;
( Int ( Cl K ) ) c= ( Cl ( Int ( Cl K ) ) ) by PRE_TOPC:18;
then A9: ( ( Cl ( Int K ) ) \/ ( Int ( Cl K ) ) ) c= ( Cl ( Int ( Cl K ) ) ) by A8,XBOOLE_1:8;
K c= ( ( Cl ( Int K ) ) \/ ( Int ( Cl K ) ) ) by A7,CKB5:def 1;
then K c= ( Cl ( Int ( Cl K ) ) ) by A9,XBOOLE_1:1;
then A10: K is  pre-semi-open by CKB4:def 1;
then K = ( psInt K ) by CKB30:1;
then ( spInt K ) = ( psInt K ) by A7,CKB31:1;
then A11: K in { B: ( spInt B ) = ( psInt B ) };
K in ( PSO T ) by A10;
hence thesis by A6,A11,XBOOLE_0:def 4;
end;
