environ
vocabularies PRE_TOPC,SUBSET_1,XBOOLE_0,STRUCT_0,TOPS_1,TARSKI,RCOMP_1,TOPS_3;
notations TARSKI,XBOOLE_0,SUBSET_1,STRUCT_0,PRE_TOPC,TOPS_1,BORSUK_1,TSEP_1,CKB9,CKB17,CKB24,CKB34,CKB35;
definitions PRE_TOPC,XBOOLE_0,SUBSET_1,STRUCT_0,CKB9,CKB17,CKB24,CKB34,CKB35;
theorems PRE_TOPC,TOPS_1,TOPS_2,TSEP_1,TDLAT_3,SUBSET_1,TARSKI,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72;
registrations STRUCT_0,PRE_TOPC,TOPS_1,BORSUK_1,TSEP_1;
constructors TOPS_1,BORSUK_1,TSEP_1,CKB34;
requirements BOOLE,SUBSET;
begin
reserve X for non empty TopSpace;
reserve X0 for non empty (SubSpace of X);
theorem
Th68: (for A being (Subset of X) holds (for B being (Subset of X0) holds (A c= B implies (B is  nowhere_dense implies A is  nowhere_dense))))
proof
let A being (Subset of X);
let B being (Subset of X0);
reconsider D = (the carrier of X0) as (Subset of X) by TSEP_1:1;
reconsider G = ( ( Int ( Cl A ) ) /\ ( [#] X0 ) ) as (Subset of X0);
assume A1: A c= B;
then reconsider C = A as (Subset of X0) by XBOOLE_1:1;
assume B is  nowhere_dense;
then C is  nowhere_dense by A1,CKB29:1;
then A2: (G is  open & ( Int ( Cl C ) ) = ( {} )) by CKB24:def 1,TOPS_2:24;
( ( Int ( Cl A ) ) /\ ( [#] X0 ) ) c= ( ( Cl A ) /\ ( [#] X0 ) ) by TOPS_1:16,XBOOLE_1:26;
then A3: ( ( Int ( Cl A ) ) /\ ( [#] X0 ) ) c= ( Cl C ) by PRE_TOPC:17;
now
assume ( Int ( Cl A ) ) <> ( {} );
then A meets ( Int ( Cl A ) ) by CKB7:1;
then A4: ( A /\ ( Int ( Cl A ) ) ) <> ( {} ) by XBOOLE_0:def 7;
C c= D;
then ( ( Int ( Cl A ) ) /\ D ) <> ( {} ) by A4,XBOOLE_1:3,XBOOLE_1:26;
hence contradiction by A3,A2,TOPS_1:24,XBOOLE_1:3;
end;
hence thesis by CKB24:def 1;
end;
