environ
vocabularies ANALMETR,SUBSET_1,SYMSP_1,ANALOAF,AFF_1,DIRAF,INCSP_1,AFF_2,CONAFFM,STRUCT_0,CONMETR;
notations SUBSET_1,STRUCT_0,ANALOAF,AFF_1,ANALMETR,AFF_2,CONAFFM;
definitions AFF_2;
theorems AFF_1,AFF_2,ANALMETR,TRANSLAC,CONAFFM,DIRAF;
registrations ANALMETR;
constructors AFF_1,AFF_2,CONAFFM;
requirements SUBSET;
begin
reserve X for OrtAfPl;
reserve o for (Element of X);
reserve a1 for (Element of X);
reserve a2 for (Element of X);
reserve a3 for (Element of X);
reserve b1 for (Element of X);
reserve b2 for (Element of X);
reserve b3 for (Element of X);
reserve M for (Subset of X);
reserve N for (Subset of X);
definition
let X;
attr X is  satisfying_OPAP
means
:Def1: (for o holds (for a1 holds (for a2 holds (for a3 holds (for b1 holds (for b2 holds (for b3 holds (for M holds (for N holds (((((((((((((((((((o in M & a1 in M) & a2 in M) & a3 in M) & o in N) & b1 in N) & b2 in N) & b3 in N) & (not b2 in M)) & (not a3 in N)) & M _|_ N) & o <> a1) & o <> a2) & o <> a3) & o <> b1) & o <> b2) & o <> b3) & a3,b2 // a2,b1) & a3,b3 // a1,b1) implies a1,b2 // a2,b3))))))))));
end;
