environ
vocabularies NUMBERS,PRE_TOPC,SUBSET_1,RELAT_1,SETFAM_1,RCOMP_1,NAT_1,INT_1,XBOOLE_0,TOPS_1,TARSKI,PROB_1,ZFMISC_1,STRUCT_0,FUNCT_1,CARD_1,ARYTM_3,PARTFUN1,FINSET_1,XXREAL_0,COMPTS_1,ARYTM_1,ORDINAL1,T_0TOPSP,TOPS_2,CARD_5,METRIZTS,RLVECT_3,CARD_3,MCART_1,PCOMPS_1,WAYBEL23,TOPDIM_1,FUNCT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,ORDINAL1,MCART_1,FUNCT_2,CARD_1,CARD_3,CANTOR_1,FINSET_1,NUMBERS,ZFMISC_1,XXREAL_0,REAL_1,SETFAM_1,DOMAIN_1,PRE_TOPC,TOPS_1,TOPS_2,NAT_1,STRUCT_0,COMPTS_1,PCOMPS_1,PROB_1,WAYBEL23,BORSUK_1,BORSUK_3,INT_1,METRIZTS,CKB3,CKB6,CKB7,CKB8,CKB9,CKB16,CKB17,CKB22,CKB30,CKB37;
definitions COMPTS_1,STRUCT_0,SUBSET_1,TOPS_1,TOPS_2,TARSKI,XBOOLE_0,CKB3,CKB6,CKB8,CKB16,CKB22,CKB30,CKB37;
theorems CARD_2,CARD_3,FUNCT_1,FUNCT_2,INT_1,KURATO_2,ORDINAL1,MCART_1,NAT_1,PRE_TOPC,PROB_1,RELAT_1,SETFAM_1,SETLIM_1,SUBSET_1,TARSKI,TOPGEN_1,TOPGRP_1,TOPS_1,TOPS_2,TOPS_3,TSEP_1,TSP_1,T_0TOPSP,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,YELLOW12,YELLOW_9,ZFMISC_1,METRIZTS,KURATO_0,CKB1,CKB2,CKB3,CKB5,CKB6,CKB8,CKB10,CKB11,CKB16,CKB19,CKB22,CKB23,CKB24,CKB25,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB36,CKB37,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71;
schemes CLASSES1,FRAENKEL,FUNCT_2,NAT_1,SUBSET_1;
registrations BORSUK_3,CARD_1,COMPTS_1,FINSET_1,FUNCT_2,INT_1,NAT_1,ORDINAL1,PRE_TOPC,RELAT_1,STRUCT_0,SUBSET_1,TOPREAL6,TOPS_1,XBOOLE_0,XCMPLX_0,XREAL_0,XXREAL_0,YELLOW13,METRIZTS,RELSET_1,KURATO_0,CKB4,CKB12,CKB13,CKB14,CKB15,CKB18,CKB20,CKB21,CKB26,CKB35,CKB38,CKB45,CKB46;
constructors SETFAM_1,TOPS_1,TOPS_2,BORSUK_1,REAL_1,KURATO_2,CANTOR_1,WELLFND1,WAYBEL23,COMPTS_1,BORSUK_3,TSP_1,METRIZTS,RELSET_1,ORDINAL2,PCOMPS_1,KURATO_0,EUCLID,CKB3,CKB6,CKB8,CKB16,CKB22,CKB30,CKB37;
requirements ARITHM,BOOLE,NUMERALS,REAL,SUBSET;
begin
reserve T for TopSpace;
reserve A for (Subset of T);
reserve B for (Subset of T);
reserve TM for  metrizable TopSpace;
theorem
(for Null,A being (Subset of TM) holds ((((( TM | Null ) is  second-countable & Null is  finite-ind) & A is  finite-ind) & ( ind Null ) <= ( 0 )) implies (( A \/ Null ) is  finite-ind & ( ind ( A \/ Null ) ) <= ( ( ind A ) + 1 ))))
proof
let Null being (Subset of TM);
let A being (Subset of TM);
assume that
A1: ( TM | Null ) is  second-countable
and
A2: Null is  finite-ind
and
A3: A is  finite-ind
and
A4: ( ind Null ) <= ( 0 );
set TAN = ( TM | ( A \/ Null ) );
A5: ( [#] TAN ) = ( A \/ Null ) by PRE_TOPC:def 5;
then reconsider N9 = Null,A9 = A as (Subset of TAN) by XBOOLE_1:7;
A6: ( ind N9 ) = ( ind Null ) by A2,CKB51:1;
(N9 is  finite-ind & ( TAN | N9 ) is  second-countable) by A1,A2,CKB51:1,METRIZTS:9;
then consider B being (Basis of TAN) such that A7: (for b being (Subset of TAN) holds (b in B implies N9 misses ( Fr b ))) by A4,A6,CKB71:1;
set i = ( ind A );
( - 1 ) <= i by A3,CKB23:1;
then ( ( - 1 ) + 1 ) <= ( i + 1 ) by XREAL_1:6;
then reconsider i1 = ( i + 1 ) as (Element of ( NAT )) by INT_1:3;
A8: (A9 is  finite-ind & ( ind A9 ) = ( ind A )) by A3,CKB51:1;
A9: (for b being (Subset of TAN) holds (b in B implies (( Fr b ) is  finite-ind & ( ind ( Fr b ) ) <= ( i1 - 1 ))))
proof
let b being (Subset of TAN);
assume b in B;
then N9 misses ( Fr b ) by A7;
then ( Fr b ) c= A9 by A5,XBOOLE_1:73;
hence thesis by A8,CKB49:1;
end;
then TAN is  finite-ind by CKB63:1;
then A10: ( A \/ Null ) is  finite-ind by CKB48:1;
( ind TAN ) <= i1 by A9,CKB63:1;
hence thesis by A10,CKB42:1;
end;
