environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,MARGREL1,XBOOLEAN,FUNCT_1,PARTIT1,BVFUNC_1;
notations XBOOLE_0,SUBSET_1,XBOOLEAN,MARGREL1,FUNCT_2,BVFUNC_1;
definitions BVFUNC_1,XBOOLEAN;
theorems MARGREL1,BVFUNC_1,BVFUNC_4,BVFUNC_5,BVFUNC_6,BVFUNC_7,XBOOLEAN,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12;
registrations XBOOLE_0,XBOOLEAN,MARGREL1;
constructors BINARITH,BVFUNC_1;
requirements ARITHM,BOOLE;
begin
reserve Y for non empty set;
theorem
(for a,b,c,d being (Element of ( Funcs (Y,( BOOLEAN )) )) holds ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) = ( ( ( a 'imp' ( ( b '&' c ) '&' d ) ) '&' ( b 'imp' ( c '&' d ) ) ) '&' ( c 'imp' d ) ))
proof
let a being (Element of ( Funcs (Y,( BOOLEAN )) )),b being (Element of ( Funcs (Y,( BOOLEAN )) )),c being (Element of ( Funcs (Y,( BOOLEAN )) )),d being (Element of ( Funcs (Y,( BOOLEAN )) ));
A1: ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) = ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( a 'imp' c ) ) '&' ( c 'imp' d ) ) by BVFUNC_7:12
.= ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( ( a 'imp' c ) '&' ( c 'imp' d ) ) ) by BVFUNC_1:4
.= ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( ( ( a 'imp' c ) '&' ( c 'imp' d ) ) '&' ( a 'imp' d ) ) ) by BVFUNC_7:12
.= ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( ( a 'imp' c ) '&' ( c 'imp' d ) ) ) '&' ( a 'imp' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) by BVFUNC_1:4
.= ( ( ( ( a 'imp' b ) '&' ( ( b 'imp' c ) '&' ( c 'imp' d ) ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) by BVFUNC_1:4
.= ( ( ( ( a 'imp' b ) '&' ( ( ( b 'imp' c ) '&' ( c 'imp' d ) ) '&' ( b 'imp' d ) ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) by BVFUNC_7:12
.= ( ( ( ( ( a 'imp' b ) '&' ( ( b 'imp' c ) '&' ( c 'imp' d ) ) ) '&' ( b 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( b 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( b 'imp' d ) ) '&' ( a 'imp' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) '&' ( b 'imp' d ) ) by BVFUNC_1:4;
( ( ( a 'imp' ( ( b '&' c ) '&' d ) ) '&' ( b 'imp' ( c '&' d ) ) ) '&' ( c 'imp' d ) ) = ( ( ( ( 'not' a ) 'or' ( ( b '&' c ) '&' d ) ) '&' ( b 'imp' ( c '&' d ) ) ) '&' ( c 'imp' d ) ) by BVFUNC_4:8
.= ( ( ( ( 'not' a ) 'or' ( ( b '&' c ) '&' d ) ) '&' ( ( 'not' b ) 'or' ( c '&' d ) ) ) '&' ( c 'imp' d ) ) by BVFUNC_4:8
.= ( ( ( ( 'not' a ) 'or' ( ( b '&' c ) '&' d ) ) '&' ( ( 'not' b ) 'or' ( c '&' d ) ) ) '&' ( ( 'not' c ) 'or' d ) ) by BVFUNC_4:8
.= ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' ( c '&' d ) ) ) '&' ( ( 'not' c ) 'or' d ) ) by BVFUNC_5:39
.= ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( ( 'not' b ) 'or' c ) '&' ( ( 'not' b ) 'or' d ) ) ) '&' ( ( 'not' c ) 'or' d ) ) by BVFUNC_1:11
.= ( ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' b ) 'or' d ) ) '&' ( ( 'not' c ) 'or' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) '&' ( ( 'not' c ) 'or' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) '&' ( ( 'not' c ) 'or' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' c ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' c ) 'or' d ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( ( 'not' a ) 'or' b ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' c ) 'or' d ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_1:4
.= ( ( ( ( ( ( a 'imp' b ) '&' ( ( 'not' b ) 'or' c ) ) '&' ( ( 'not' c ) 'or' d ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_4:8
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( ( 'not' c ) 'or' d ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_4:8
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( ( 'not' a ) 'or' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_4:8
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( ( 'not' a ) 'or' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_4:8
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) '&' ( ( 'not' b ) 'or' d ) ) by BVFUNC_4:8
.= ( ( ( ( ( ( a 'imp' b ) '&' ( b 'imp' c ) ) '&' ( c 'imp' d ) ) '&' ( a 'imp' c ) ) '&' ( a 'imp' d ) ) '&' ( b 'imp' d ) ) by BVFUNC_4:8;
hence thesis by A1;
end;
