environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,MARGREL1,XBOOLEAN,FUNCT_1,PARTIT1,BVFUNC_1;
notations XBOOLE_0,SUBSET_1,XBOOLEAN,MARGREL1,FUNCT_2,BVFUNC_1;
definitions BVFUNC_1,XBOOLEAN;
theorems MARGREL1,BVFUNC_1,BVFUNC_4,BVFUNC_5,BVFUNC_6,BVFUNC_7,XBOOLEAN,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11;
registrations XBOOLE_0,XBOOLEAN,MARGREL1;
constructors BINARITH,BVFUNC_1;
requirements ARITHM,BOOLE;
begin
reserve Y for non  empty set;
theorem
(for a1,a2,b1,b2,b3 being (Element of ( Funcs (Y,( BOOLEAN )) )) holds ( ( a1 '&' a2 ) 'or' ( ( b1 '&' b2 ) '&' b3 ) ) = ( ( ( ( ( ( a1 'or' b1 ) '&' ( a1 'or' b2 ) ) '&' ( a1 'or' b3 ) ) '&' ( a2 'or' b1 ) ) '&' ( a2 'or' b2 ) ) '&' ( a2 'or' b3 ) ))
proof
let a1 being (Element of ( Funcs (Y,( BOOLEAN )) ));
let a2 being (Element of ( Funcs (Y,( BOOLEAN )) ));
let b1 being (Element of ( Funcs (Y,( BOOLEAN )) ));
let b2 being (Element of ( Funcs (Y,( BOOLEAN )) ));
let b3 being (Element of ( Funcs (Y,( BOOLEAN )) ));
( ( ( ( ( ( a1 'or' b1 ) '&' ( a1 'or' b2 ) ) '&' ( a1 'or' b3 ) ) '&' ( a2 'or' b1 ) ) '&' ( a2 'or' b2 ) ) '&' ( a2 'or' b3 ) ) = ( ( ( ( ( a1 'or' ( b1 '&' b2 ) ) '&' ( a1 'or' b3 ) ) '&' ( a2 'or' b1 ) ) '&' ( a2 'or' b2 ) ) '&' ( a2 'or' b3 ) ) by BVFUNC_1:11
.= ( ( ( ( a1 'or' ( ( b1 '&' b2 ) '&' b3 ) ) '&' ( a2 'or' b1 ) ) '&' ( a2 'or' b2 ) ) '&' ( a2 'or' b3 ) ) by BVFUNC_1:11
.= ( ( ( a1 'or' ( ( b1 '&' b2 ) '&' b3 ) ) '&' ( ( a2 'or' b1 ) '&' ( a2 'or' b2 ) ) ) '&' ( a2 'or' b3 ) ) by BVFUNC_1:4
.= ( ( a1 'or' ( ( b1 '&' b2 ) '&' b3 ) ) '&' ( ( ( a2 'or' b1 ) '&' ( a2 'or' b2 ) ) '&' ( a2 'or' b3 ) ) ) by BVFUNC_1:4
.= ( ( a1 'or' ( ( b1 '&' b2 ) '&' b3 ) ) '&' ( ( a2 'or' ( b1 '&' b2 ) ) '&' ( a2 'or' b3 ) ) ) by BVFUNC_1:11
.= ( ( a1 'or' ( ( b1 '&' b2 ) '&' b3 ) ) '&' ( a2 'or' ( ( b1 '&' b2 ) '&' b3 ) ) ) by BVFUNC_1:11
.= ( ( a1 '&' a2 ) 'or' ( ( b1 '&' b2 ) '&' b3 ) ) by BVFUNC_1:11;
hence thesis;
end;
