environ
vocabularies NUMBERS,XBOOLE_0,PRE_TOPC,RCOMP_1,SUBSET_1,FUNCT_1,URYSOHN1,CARD_1,ZFMISC_1,STRUCT_0,TARSKI,ARYTM_3,PARTFUN1,SEQFUNC,RELAT_1,NEWTON,XXREAL_0,NAT_1,ARYTM_1,REAL_1,CARD_3,PROB_1,LIMFUNC1,SUPINF_1,TOPMETR,ORDINAL2,XXREAL_1,SUPINF_2,ORDINAL1,XXREAL_2,TMAP_1,METRIC_1,PCOMPS_1,XREAL_0,COMPLEX1,URYSOHN3;
notations TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,XXREAL_1,XXREAL_2,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,NEWTON,SUPINF_2,SEQ_1,TOPMETR,MEASURE6,PSCOMP_1,STRUCT_0,PRE_TOPC,COMPTS_1,TMAP_1,METRIC_1,PCOMPS_1,SEQFUNC,PROB_1,LIMFUNC1,SUPINF_1,URYSOHN1,CKB3,CKB6,CKB8,CKB9;
definitions PRE_TOPC,TARSKI,STRUCT_0,LIMFUNC1,PROB_1,CKB3,CKB8,CKB9;
theorems TARSKI,FUNCT_1,FUNCT_2,NAT_1,PCOMPS_1,PRE_TOPC,TOPS_1,TOPMETR,ABSVALUE,PARTFUN1,URYSOHN1,XREAL_0,RELSET_1,URYSOHN2,TMAP_1,METRIC_1,XBOOLE_0,XBOOLE_1,PREPOWER,XCMPLX_1,XREAL_1,PEPIN,NEWTON,XXREAL_0,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_1,XXREAL_2,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes NAT_1,FUNCT_2,RECDEF_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,PARTFUN1,NUMBERS,XXREAL_0,NAT_1,MEMBERED,STRUCT_0,PRE_TOPC,METRIC_1,URYSOHN1,TOPMETR,WAYBEL_3,BORSUK_4,BORSUK_6,VALUED_0,XREAL_0,FUNCT_1;
constructors REAL_1,NAT_1,PROB_1,LIMFUNC1,SEQFUNC,NEWTON,SUPINF_2,MEASURE5,MEASURE6,URYSOHN1,TMAP_1,WAYBEL_3,SEQ_1,BORSUK_4,PSCOMP_1,SUPINF_1,PCOMPS_1,BORSUK_6,WAYBEL_0,COMPTS_1,TOPREAL2,LATTICE3,MONOID_0,FUNCOP_1,CKB3,CKB6,CKB8,CKB9;
requirements NUMERALS,SUBSET,BOOLE,REAL,ARITHM;
begin
definition
let T being non empty TopSpace;
let A being (Subset of T);
let B being (Subset of T);
let R being (Rain of A,B);
assume A1: ((((T is  normal & A <> ( {} )) & A is  closed) & B is  closed) & A misses B);
func Tempest R -> (Function of ( DOM ),( bool (the carrier of T) ))
means
:Def4: (for x being Real holds (x in ( DOM ) implies (((x in ( halfline ( 0 ) ) implies ( it . x ) = ( {} )) & (x in ( right_open_halfline 1 ) implies ( it . x ) = (the carrier of T))) & (x in ( DYADIC ) implies (for n being (Element of ( NAT )) holds (x in ( dyadic n ) implies ( it . x ) = ( ( R . n ) . x )))))));
existence by A1,CKB15:1;
uniqueness
proof
let G1 being (Function of ( DOM ),( bool (the carrier of T) )),G2 being (Function of ( DOM ),( bool (the carrier of T) ));
assume that
A2: (for x being Real holds (x in ( DOM ) implies (((x in ( halfline ( 0 ) ) implies ( G1 . x ) = ( {} )) & (x in ( right_open_halfline 1 ) implies ( G1 . x ) = (the carrier of T))) & (x in ( DYADIC ) implies (for n being (Element of ( NAT )) holds (x in ( dyadic n ) implies ( G1 . x ) = ( ( R . n ) . x )))))))
and
A3: (for x being Real holds (x in ( DOM ) implies (((x in ( halfline ( 0 ) ) implies ( G2 . x ) = ( {} )) & (x in ( right_open_halfline 1 ) implies ( G2 . x ) = (the carrier of T))) & (x in ( DYADIC ) implies (for n being (Element of ( NAT )) holds (x in ( dyadic n ) implies ( G2 . x ) = ( ( R . n ) . x )))))));
(for x being set holds (x in ( DOM ) implies ( G1 . x ) = ( G2 . x )))
proof
let x being set;
assume A4: x in ( DOM );
then reconsider x as Real;
A5: (x in ( ( halfline ( 0 ) ) \/ ( DYADIC ) ) or x in ( right_open_halfline 1 )) by A4,URYSOHN1:def 3,XBOOLE_0:def 3;
per cases  by A5,XBOOLE_0:def 3;
suppose A6: x in ( halfline ( 0 ) );

then ( G1 . x ) = ( {} ) by A2,A4;
hence thesis by A3,A4,A6;
end;
suppose A7: x in ( right_open_halfline 1 );

then ( G1 . x ) = (the carrier of T) by A2,A4;
hence thesis by A3,A4,A7;
end;
suppose A8: x in ( DYADIC );

then consider n being (Element of ( NAT )) such that A9: x in ( dyadic n ) by URYSOHN1:def 2;
( G1 . x ) = ( ( R . n ) . x ) by A2,A4,A8,A9;
hence thesis by A3,A4,A8,A9;
end;
end;
hence thesis by FUNCT_2:12;
end;
end;
