environ
vocabularies NUMBERS,XBOOLE_0,PRE_TOPC,RCOMP_1,SUBSET_1,FUNCT_1,URYSOHN1,CARD_1,ZFMISC_1,STRUCT_0,TARSKI,ARYTM_3,PARTFUN1,SEQFUNC,RELAT_1,NEWTON,XXREAL_0,NAT_1,ARYTM_1,REAL_1,CARD_3,PROB_1,LIMFUNC1,SUPINF_1,TOPMETR,ORDINAL2,XXREAL_1,SUPINF_2,ORDINAL1,XXREAL_2,TMAP_1,METRIC_1,PCOMPS_1,XREAL_0,COMPLEX1,URYSOHN3;
notations TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,XXREAL_1,XXREAL_2,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,NEWTON,SUPINF_2,SEQ_1,TOPMETR,MEASURE6,PSCOMP_1,STRUCT_0,PRE_TOPC,COMPTS_1,TMAP_1,METRIC_1,PCOMPS_1,SEQFUNC,PROB_1,LIMFUNC1,SUPINF_1,URYSOHN1;
definitions PRE_TOPC,TARSKI,STRUCT_0,LIMFUNC1,PROB_1;
theorems TARSKI,FUNCT_1,FUNCT_2,NAT_1,PCOMPS_1,PRE_TOPC,TOPS_1,TOPMETR,ABSVALUE,PARTFUN1,URYSOHN1,XREAL_0,RELSET_1,URYSOHN2,TMAP_1,METRIC_1,XBOOLE_0,XBOOLE_1,PREPOWER,XCMPLX_1,XREAL_1,PEPIN,NEWTON,XXREAL_0,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_1,XXREAL_2,RELAT_1;
schemes NAT_1,FUNCT_2,RECDEF_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,PARTFUN1,NUMBERS,XXREAL_0,NAT_1,MEMBERED,STRUCT_0,PRE_TOPC,METRIC_1,URYSOHN1,TOPMETR,WAYBEL_3,BORSUK_4,BORSUK_6,VALUED_0,XREAL_0,FUNCT_1;
constructors REAL_1,NAT_1,PROB_1,LIMFUNC1,SEQFUNC,NEWTON,SUPINF_2,MEASURE5,MEASURE6,URYSOHN1,TMAP_1,WAYBEL_3,SEQ_1,BORSUK_4,PSCOMP_1,SUPINF_1,PCOMPS_1,BORSUK_6,WAYBEL_0,COMPTS_1,TOPREAL2,LATTICE3,MONOID_0,FUNCOP_1;
requirements NUMERALS,SUBSET,BOOLE,REAL,ARITHM;
begin
theorem
Lm1: (for T being non  empty  normal TopSpace holds (for A,B being  closed (Subset of T) holds ((A <> ( {} ) & A misses B) implies (ex G being (Function of ( dyadic ( 0 ) ),( bool (the carrier of T) )) st ((A c= ( G . ( 0 ) ) & B = ( ( [#] T ) \ ( G . 1 ) )) & (for r1,r2 being (Element of ( dyadic ( 0 ) )) holds (r1 < r2 implies ((( G . r1 ) is  open & ( G . r2 ) is  open) & ( Cl ( G . r1 ) ) c= ( G . r2 )))))))))
proof
let T being non  empty  normal TopSpace;
let A being  closed (Subset of T);
let B being  closed (Subset of T);
assume that
A1: A <> ( {} )
and
A2: A misses B;
reconsider G1 = ( ( [#] T ) \ B ) as (Subset of T);
A3: G1 = ( B ` ) by SUBSET_1:def 4;
then A4: G1 is  open by TOPS_1:3;
( A \ B ) c= G1 by XBOOLE_1:33;
then A c= G1 by A2,XBOOLE_1:83;
then consider G0 being (Subset of T) such that A5: G0 is  open and A6: A c= G0 and A7: ( Cl G0 ) c= G1 by A1,A4,URYSOHN1:23;
defpred P[ set,set ]
 means
(($1 = ( 0 ) implies $2 = G0) & ($1 = 1 implies $2 = G1));
A8: (for x being (Element of ( dyadic ( 0 ) )) holds (ex y being (Subset of T) st P[ x,y ]))
proof
let x being (Element of ( dyadic ( 0 ) ));
per cases  by TARSKI:def 2,URYSOHN1:2;
suppose A9: x = ( 0 );

take G0;
thus thesis by A9;
end;
suppose A10: x = 1;

take G1;
thus thesis by A10;
end;
end;
(ex F being (Function of ( dyadic ( 0 ) ),( bool (the carrier of T) )) st (for x being (Element of ( dyadic ( 0 ) )) holds P[ x,( F . x ) ])) from FUNCT_2:sch 3(A8);
then consider F being (Function of ( dyadic ( 0 ) ),( bool (the carrier of T) )) such that A11: (for x being (Element of ( dyadic ( 0 ) )) holds P[ x,( F . x ) ]);
A12: (for r1,r2 being (Element of ( dyadic ( 0 ) )) holds (r1 < r2 implies ((( F . r1 ) is  open & ( F . r2 ) is  open) & ( Cl ( F . r1 ) ) c= ( F . r2 ))))
proof
let r1 being (Element of ( dyadic ( 0 ) ));
let r2 being (Element of ( dyadic ( 0 ) ));
A13: (r1 = ( 0 ) or r1 = 1) by TARSKI:def 2,URYSOHN1:2;
A14: (r2 = ( 0 ) or r2 = 1) by TARSKI:def 2,URYSOHN1:2;
assume A15: r1 < r2;
then ( F . 1 ) = G1 by A11,A14,URYSOHN1:2;
hence thesis by A3,A5,A7,A11,A15,A13,A14,TOPS_1:3;
end;
take F;
1 in ( dyadic ( 0 ) ) by TARSKI:def 2,URYSOHN1:2;
then (( 0 ) in ( dyadic ( 0 ) ) & ( F . 1 ) = G1) by A11,TARSKI:def 2,URYSOHN1:2;
hence thesis by A6,A11,A12,PRE_TOPC:3;
end;
