environ
vocabularies NUMBERS,INTEGRA1,SUBSET_1,FUNCT_1,FINSEQ_1,NAT_1,RELAT_1,MEASURE7,XBOOLE_0,XXREAL_2,XXREAL_0,SEQ_4,CARD_1,REAL_1,ARYTM_3,XREAL_0,ORDINAL1,ARYTM_1,CARD_3,FINSEQ_2,INTEGRA2,SEQ_1,SEQ_2,ORDINAL2,COMPLEX1,XXREAL_1,FUNCT_3,REAL_NS1,STRUCT_0,PARTFUN1,VALUED_1,TARSKI,PRE_TOPC,INTEGRA5,REALSET1,INTEGR15,VALUED_2,MEASURE5;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XREAL_0,COMPLEX1,XXREAL_2,NAT_1,FUNCT_1,FUNCT_2,STRUCT_0,REAL_1,RCOMP_1,VALUED_1,RELSET_1,PARTFUN1,SEQ_1,SEQ_2,SEQ_4,FINSEQ_1,FINSEQ_2,FINSEQOP,VALUED_2,RVSUM_1,PRE_TOPC,XXREAL_0,EUCLID,PDIFF_1,MEASURE5,INTEGRA1,INTEGRA2,INTEGRA3,INTEGRA5,NORMSP_1,REAL_NS1,CKB1,CKB6,CKB11,CKB12,CKB13,CKB21;
definitions TARSKI,XBOOLE_0,EUCLID,INTEGRA1,INTEGRA5,CKB1,CKB6,CKB11,CKB13,CKB21;
theorems XBOOLE_0,XBOOLE_1,XREAL_0,INTEGRA1,INTEGRA2,INTEGRA4,XXREAL_2,XXREAL_0,EUCLID,RELAT_1,XCMPLX_1,PREPOWER,ORDINAL1,SUBSET_1,XREAL_1,RCOMP_1,SEQ_4,SEQ_2,FINSEQ_1,FINSEQ_2,RVSUM_1,FUNCT_1,FUNCT_2,PARTFUN1,REAL_NS1,INTEGRA5,PDIFF_1,INTEGRA6,VALUED_1,VALUED_2,RELSET_1,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21;
schemes SEQ_1,FUNCT_2,FINSEQ_1,PARTFUN2;
registrations NUMBERS,XREAL_0,FINSEQ_2,SEQ_2,INTEGRA1,FUNCT_2,NAT_1,MEMBERED,XXREAL_0,ORDINAL1,VALUED_0,VALUED_1,REAL_NS1,RELSET_1,EUCLID,VALUED_2,CARD_1,MEASURE5;
constructors REAL_1,FINSEQOP,MONOID_0,SEQ_4,PSCOMP_1,NAT_D,VFUNCT_1,PDIFF_1,BINOP_2,SEQ_1,INTEGRA2,INTEGRA5,RELSET_1,SEQ_2,INTEGRA3,VALUED_2,CKB1,CKB6,CKB11,CKB12,CKB13,CKB21;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
definition
let n being (Element of ( NAT ));
let A being non  empty  closed_interval (Subset of ( REAL ));
let f being (Function of A,( REAL n ));
let D being (Division of A);
let F being (middle_volume of f,D);
func middle_sum (f,F) -> (Element of ( REAL n )) means 
:Def6: (for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (ex Fi being (FinSequence of ( REAL )) st (Fi = ( ( proj (i,n) ) * F ) & ( it . i ) = ( Sum Fi )))));
existence
proof
defpred P[ Nat,(Element of ( REAL )) ]
 means
(ex i being (Element of ( NAT )) st (ex Fi being (FinSequence of ( REAL )) st (($1 = i & Fi = ( ( proj (i,n) ) * F )) & $2 = ( Sum Fi ))));
A1: (for i being Nat holds (i in ( Seg n ) implies (ex x being (Element of ( REAL )) st P[ i,x ])))
proof
let i being Nat;
assume i in ( Seg n );
then reconsider ii = i as (Element of ( NAT ));
reconsider Fi = ( ( proj (ii,n) ) * F ) as (FinSequence of ( REAL ));
reconsider x = ( Sum Fi ) as (Element of ( REAL ));
take x;
thus (ex ii being (Element of ( NAT )) st (ex Fi being (FinSequence of ( REAL )) st ((i = ii & Fi = ( ( proj (ii,n) ) * F )) & x = ( Sum Fi ))));
end;
consider p being (FinSequence of ( REAL )) such that A2: (( dom p ) = ( Seg n ) & (for i being Nat holds (i in ( Seg n ) implies P[ i,( p . i ) ]))) from FINSEQ_1:sch 5(A1);
take p;
A3: (for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (ex Fi being (FinSequence of ( REAL )) st (Fi = ( ( proj (i,n) ) * F ) & ( p . i ) = ( Sum Fi )))))
proof
let i being (Element of ( NAT ));
reconsider k = i as Nat;
assume i in ( Seg n );
then P[ k,( p . k ) ] by A2;
hence thesis;
end;
( len p ) = n by A2,FINSEQ_1:def 3;
hence thesis by A3,FINSEQ_2:92;
end;
uniqueness
proof
let x1 being (Element of ( REAL n ));
let x2 being (Element of ( REAL n ));
assume that
A4: ((for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (ex Fi1 being (FinSequence of ( REAL )) st (Fi1 = ( ( proj (i,n) ) * F ) & ( x1 . i ) = ( Sum Fi1 ))))) & (for i being (Element of ( NAT )) holds (i in ( Seg n ) implies (ex Fi2 being (FinSequence of ( REAL )) st (Fi2 = ( ( proj (i,n) ) * F ) & ( x2 . i ) = ( Sum Fi2 ))))));
A5: (for k0 being Nat holds (k0 in ( dom x1 ) implies ( x1 . k0 ) = ( x2 . k0 )))
proof
let k0 being Nat;
assume A6: k0 in ( dom x1 );
then reconsider k = k0 as (Element of ( NAT ));
( len x1 ) = n by CARD_1:def 7;
then k0 in ( Seg n ) by A6,FINSEQ_1:def 3;
then ((ex Fi1 being (FinSequence of ( REAL )) st (Fi1 = ( ( proj (k,n) ) * F ) & ( x1 . k ) = ( Sum Fi1 ))) & (ex Fi2 being (FinSequence of ( REAL )) st (Fi2 = ( ( proj (k,n) ) * F ) & ( x2 . k ) = ( Sum Fi2 )))) by A4;
hence thesis;
end;
A7: ( len x2 ) = n by CARD_1:def 7;
( len x1 ) = n by CARD_1:def 7;
then ( dom x1 ) = ( Seg n ) by FINSEQ_1:def 3
.= ( dom x2 ) by A7,FINSEQ_1:def 3;
hence thesis by A5,FINSEQ_1:13;
end;
end;
