environ
vocabularies NUMBERS,ORDINAL1,ORDINAL2,TARSKI,MATROID0,XBOOLE_0,CARD_1,FINSET_1,AFINSQ_1,ORDINAL4,RELAT_1,FUNCT_1,VALUED_0,CARD_3,SUBSET_1,ARYTM_3,NAT_1,XXREAL_0,NEWTON,ORDINAL3,FINSEQ_1,ORDINAL5;
notations XBOOLE_0,TARSKI,RELAT_1,FUNCT_1,SUBSET_1,FINSET_1,NUMBERS,MATROID0,ORDINAL1,NAT_1,XXREAL_0,NEWTON,ORDINAL2,AFINSQ_1,ORDINAL3,ORDINAL4,CARD_3,CKB10,CKB11,CKB12,CKB28,CKB54,CKB57,CKB66,CKB79;
definitions TARSKI,XBOOLE_0,ORDINAL2,CARD_3,CKB10,CKB11,CKB12,CKB28,CKB54,CKB57,CKB66,CKB79;
theorems TARSKI,FUNCT_1,FINSET_1,NAT_1,ORDERS_1,AFINSQ_1,RELAT_1,ORDINAL1,ORDINAL2,ORDINAL3,ORDINAL4,CARD_2,CARD_3,CARD_5,XBOOLE_0,XBOOLE_1,ZFMISC_1,NEWTON,XXREAL_0,NAT_4,PEPIN,CARD_1,CKB1,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB15,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB54,CKB55,CKB57,CKB58,CKB59,CKB60,CKB61,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB78,CKB79,CKB80,CKB81;
schemes NAT_1,ORDINAL1,ORDINAL2,AFINSQ_1,CKB52,CKB53;
registrations XBOOLE_0,RELAT_1,FUNCT_1,ORDINAL1,NAT_1,XXREAL_0,XREAL_0,ORDINAL2,ORDINAL4,CARD_1,CARD_5,CARD_LAR,NEWTON,AFINSQ_1,FINSET_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB13,CKB14,CKB16,CKB17,CKB18,CKB19,CKB20,CKB44,CKB45,CKB56,CKB62,CKB77;
constructors NEWTON,NAT_1,XXREAL_0,AFINSQ_1,ORDINAL3,CARD_3,ORDINAL4,CKB10,CKB11,CKB12,CKB28,CKB54,CKB57,CKB66,CKB79;
requirements SUBSET,BOOLE,NUMERALS,ARITHM,REAL;
begin
reserve a for  ordinal number;
reserve n for  natural number;
theorem
Th54: (for A being  finite Ordinal-Sequence holds ( Sum^ ( A ^ <% a %> ) ) = ( ( Sum^ A ) +^ a ))
proof
let A being  finite Ordinal-Sequence;
consider f being Ordinal-Sequence such that A1: (((( Sum^ ( A ^ <% a %> ) ) = ( last f ) & ( dom f ) = ( succ ( dom ( A ^ <% a %> ) ) )) & ( f . ( 0 ) ) = ( 0 )) & (for n being Nat holds (n in ( dom ( A ^ <% a %> ) ) implies ( f . ( n + 1 ) ) = ( ( f . n ) +^ ( ( A ^ <% a %> ) . n ) )))) by CKB79:def 1;
consider g being Ordinal-Sequence such that A2: (((( Sum^ A ) = ( last g ) & ( dom g ) = ( succ ( dom A ) )) & ( g . ( 0 ) ) = ( 0 )) & (for n being Nat holds (n in ( dom A ) implies ( g . ( n + 1 ) ) = ( ( g . n ) +^ ( A . n ) )))) by CKB79:def 1;
( dom <% a %> ) = 1 by AFINSQ_1:def 4;
then A3: (( dom ( A ^ <% a %> ) ) = ( ( dom A ) +^ 1 ) & ( ( dom A ) +^ 1 ) = ( succ ( dom A ) )) by ORDINAL2:31,ORDINAL4:def 1;
reconsider dA = ( dom A ) as (Element of ( NAT )) by ORDINAL1:def 12;
A4: ( dom A ) in ( succ ( dom A ) ) by ORDINAL1:6;
defpred P[ Nat ]
 means
($1 in ( succ ( dom A ) ) implies ( f . $1 ) = ( g . $1 ));
A5: P[ ( 0 ) ] by A1,A2;
A6: (P[ n ] implies P[ ( n + 1 ) ])
proof
assume that
A7: P[ n ]
and
A8: ( n + 1 ) in ( succ ( dom A ) );
( n + 1 ) = ( succ n ) by NAT_1:38;
then A9: n in ( dom A ) by A8,ORDINAL3:3;
then A10: n in ( succ ( dom A ) ) by A4,ORDINAL1:10;
then (( g . ( n + 1 ) ) = ( ( g . n ) +^ ( A . n ) ) & ( f . ( n + 1 ) ) = ( ( f . n ) +^ ( ( A ^ <% a %> ) . n ) )) by A1,A2,A3,A9;
hence thesis by A7,A9,A10,ORDINAL4:def 1;
end;
A11: P[ n ] from NAT_1:sch 2(A5,A6);
thus ( Sum^ ( A ^ <% a %> ) ) = ( f . ( ( dom A ) +^ 1 ) ) by A1,A3,ORDINAL2:6
.= ( f . ( dA + 1 ) ) by CARD_2:36
.= ( ( f . ( dom A ) ) +^ ( ( A ^ <% a %> ) . ( len A ) ) ) by A1,A3,A4
.= ( ( f . ( dom A ) ) +^ a ) by AFINSQ_1:36
.= ( ( g . ( dom A ) ) +^ a ) by A4,A11
.= ( ( Sum^ A ) +^ a ) by A2,ORDINAL2:6;
end;
