environ
vocabularies STRUCT_0,FUNCT_1,RELAT_1,XBOOLE_0,FUNCOP_1,SUBSET_1,MARGREL1,PBOOLE,CARD_1,NAT_1,UNIALG_1,FUNCT_2,PARTFUN1,FINSEQ_2,TARSKI,FINSEQ_1,NUMBERS,ZFMISC_1,CARD_3,MSUALG_1;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,NAT_1,RELAT_1,FUNCT_1,FUNCT_2,FINSEQ_1,STRUCT_0,PARTFUN1,FINSEQ_2,CARD_3,FUNCOP_1,PBOOLE,MARGREL1,UNIALG_1,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB16,CKB17,CKB18,CKB24,CKB27,CKB29,CKB30,CKB31,CKB33;
definitions TARSKI,FINSEQ_1,FUNCT_1,PBOOLE,STRUCT_0,XBOOLE_0,UNIALG_1,FUNCOP_1,MARGREL1,CKB6,CKB7,CKB10,CKB16,CKB17,CKB18,CKB24,CKB27,CKB29,CKB30,CKB31,CKB33;
theorems TARSKI,FUNCT_1,PARTFUN1,FINSEQ_1,FUNCOP_1,UNIALG_1,PBOOLE,FUNCT_2,CARD_3,FINSEQ_3,FINSEQ_2,RELAT_1,RELSET_1,STRUCT_0,ORDINAL1,MARGREL1,CARD_1,CKB6,CKB7,CKB10,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB27,CKB29,CKB30,CKB31,CKB33,CKB35,CKB36;
registrations XBOOLE_0,FUNCT_1,ORDINAL1,RELSET_1,FUNCOP_1,FINSEQ_2,RELAT_1,PBOOLE,STRUCT_0,UNIALG_1,FUNCT_2,CARD_1,ZFMISC_1,MARGREL1,CKB1,CKB2,CKB3,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB26,CKB28,CKB32,CKB34;
constructors CARD_3,PBOOLE,REALSET2,UNIALG_1,RELSET_1,MARGREL1,CKB1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB16,CKB17,CKB18,CKB24,CKB27,CKB29,CKB30,CKB31,CKB33;
requirements BOOLE,SUBSET,NUMERALS;
begin
reserve i for set;
reserve n for Nat;
theorem
Th14: (for MS being  segmental non  void 1 -element ManySortedSign holds (for A being  non-empty MSAlgebra over MS holds (the Charact of A) is (FinSequence of ( PFuncs (( ( the_sort_of A ) * ),( the_sort_of A )) ))))
proof
let MS being  segmental non  void 1 -element ManySortedSign;
let A being  non-empty MSAlgebra over MS;
A1: ( dom (the Charact of A) ) = (the carrier' of MS) by PARTFUN1:def 2;
(ex n being (Element of ( NAT )) st (the carrier' of MS) = ( Seg n ))
proof
consider n such that A2: (the carrier' of MS) = ( Seg n ) by CKB24:def 1;
n in ( NAT ) by ORDINAL1:def 12;
hence thesis by A2;
end;
then reconsider f = (the Charact of A) as FinSequence by A1,FINSEQ_1:def 2;
f is (FinSequence of ( PFuncs (( ( the_sort_of A ) * ),( the_sort_of A )) ))
proof
let x being set;
assume x in ( rng f );
then consider i such that A3: i in (the carrier' of MS) and A4: ( f . i ) = x by A1,FUNCT_1:def 3;
reconsider i as (OperSymbol of MS) by A3;
A5: ( (the Sorts of A) . ( (the ResultSort of MS) . i ) ) is (Component of (the Sorts of A)) by PBOOLE:139;
( dom (the ResultSort of MS) ) = (the carrier' of MS) by FUNCT_2:def 1;
then ( ( (the Sorts of A) * (the ResultSort of MS) ) . i ) = ( (the Sorts of A) . ( (the ResultSort of MS) . i ) ) by FUNCT_1:13
.= ( the_sort_of A ) by A5,CKB33:def 1;
then A6: x is (Function of ( Args (i,A) ),( the_sort_of A )) by A4,PBOOLE:def 15;
( Args (i,A) ) c= ( ( the_sort_of A ) * ) by CKB36:1;
then x is (PartFunc of ( ( the_sort_of A ) * ),( the_sort_of A )) by A6,RELSET_1:7;
hence thesis by PARTFUN1:45;
end;
hence thesis;
end;
