environ
vocabularies STRUCT_0,FUNCT_1,RELAT_1,XBOOLE_0,FUNCOP_1,SUBSET_1,MARGREL1,PBOOLE,CARD_1,NAT_1,UNIALG_1,FUNCT_2,PARTFUN1,FINSEQ_2,TARSKI,FINSEQ_1,NUMBERS,ZFMISC_1,CARD_3,MSUALG_1;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,NAT_1,RELAT_1,FUNCT_1,FUNCT_2,FINSEQ_1,STRUCT_0,PARTFUN1,FINSEQ_2,CARD_3,FUNCOP_1,PBOOLE,MARGREL1,UNIALG_1,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB16,CKB17,CKB18,CKB24,CKB27,CKB29;
definitions TARSKI,FINSEQ_1,FUNCT_1,PBOOLE,STRUCT_0,XBOOLE_0,UNIALG_1,FUNCOP_1,MARGREL1,CKB6,CKB7,CKB10,CKB16,CKB17,CKB18,CKB24,CKB27,CKB29;
theorems TARSKI,FUNCT_1,PARTFUN1,FINSEQ_1,FUNCOP_1,UNIALG_1,PBOOLE,FUNCT_2,CARD_3,FINSEQ_3,FINSEQ_2,RELAT_1,RELSET_1,STRUCT_0,ORDINAL1,MARGREL1,CARD_1,CKB6,CKB7,CKB10,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB27,CKB29;
registrations XBOOLE_0,FUNCT_1,ORDINAL1,RELSET_1,FUNCOP_1,FINSEQ_2,RELAT_1,PBOOLE,STRUCT_0,UNIALG_1,FUNCT_2,CARD_1,ZFMISC_1,MARGREL1,CKB1,CKB2,CKB3,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB26,CKB28;
constructors CARD_3,PBOOLE,REALSET2,UNIALG_1,RELSET_1,MARGREL1,CKB1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB16,CKB17,CKB18,CKB24,CKB27,CKB29;
requirements BOOLE,SUBSET,NUMERALS;
begin
reserve i for set;
definition
let A being Universal_Algebra;
func MSCharact A -> (ManySortedFunction of ( ( ( MSSorts A ) # ) * (the Arity of ( MSSign A )) ),( ( MSSorts A ) * (the ResultSort of ( MSSign A )) )) equals 
(the charact of A);
coherence
proof
A1: (the ResultSort of ( MSSign A )) = ( ( dom ( signature A ) ) --> ( 0 ) ) by CKB27:def 1;
reconsider OS = (the carrier' of ( MSSign A )) as non  empty set;
reconsider DO = ( ( ( MSSorts A ) # ) * (the Arity of ( MSSign A )) ),RO = ( ( MSSorts A ) * (the ResultSort of ( MSSign A )) ) as (ManySortedSet of OS);
A2: (the carrier' of ( MSSign A )) = ( dom ( signature A ) ) by CKB27:def 1;
( len ( signature A ) ) = ( len (the charact of A) ) by UNIALG_1:def 4;
then A3: ( dom (the charact of A) ) = OS by A2,FINSEQ_3:29;
then reconsider O = (the charact of A) as (ManySortedSet of OS) by PARTFUN1:def 2,RELAT_1:def 18;
A4: (the Arity of ( MSSign A )) = ( ( *--> ( 0 ) ) * ( signature A ) ) by CKB27:def 1;
reconsider O as (ManySortedFunction of OS);
A5: (the carrier of ( MSSign A )) = { ( 0 ) } by CKB27:def 1;
O is (ManySortedFunction of DO,RO)
proof
set D = (the carrier of A);
let i;
reconsider M = ( ( 0 ) .--> D ) as (ManySortedSet of { ( 0 ) });
A6: ( 0 ) in { ( 0 ) } by TARSKI:def 1;
assume A7: i in OS;
then reconsider n = i as Nat by A2;
reconsider h = ( O . n ) as  homogeneous  quasi_total non  empty (PartFunc of ( D * ),D) by A3,A7,MARGREL1:def 24,UNIALG_1:1;
n in ( dom ( ( dom ( signature A ) ) --> ( 0 ) ) ) by A2,A7,FUNCOP_1:13;
then ( RO . i ) = ( ( MSSorts A ) . ( ( ( dom ( signature A ) ) --> ( 0 ) ) . n ) ) by A1,FUNCT_1:13
.= ( ( { ( 0 ) } --> (the carrier of A) ) . ( 0 ) ) by A2,A7,FUNCOP_1:7
.= (the carrier of A) by A6,FUNCOP_1:7;
then A8: ( rng h ) c= ( RO . i ) by RELAT_1:def 19;
reconsider o = i as (Element of OS) by A7;
( DO . i ) = ( ( ( ( ( MSSorts A ) # ) * ( *--> ( 0 ) ) ) * ( signature A ) ) . n ) by A4,RELAT_1:36
.= ( ( ( M # ) * ( *--> ( 0 ) ) ) . ( ( signature A ) . n ) ) by A5,A2,A7,FUNCT_1:13
.= ( ( ( M # ) * ( *--> ( 0 ) ) ) . ( arity h ) ) by A2,A7,UNIALG_1:def 4
.= ( Funcs (( Seg ( arity h ) ),D) ) by FINSEQ_2:145
.= ( dom ( O . o ) ) by CKB22:1;
hence thesis by A8,FUNCT_2:def 1,RELSET_1:4;
end;
hence thesis;
end;
correctness;
end;
