environ
vocabularies CAT_1,FUNCT_1,ZFMISC_1,RELAT_1,MCART_1,STRUCT_0,ALGSTR_0,GRAPH_1,PZFMISC1,NATTRA_1,XBOOLE_0,WELLORD1,TARSKI,PARTFUN1,VALUED_1,REWRITE1,ISOCAT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,BINOP_1,FUNCT_3,STRUCT_0,GRAPH_1,CAT_1,CAT_2,NATTRA_1,CKB7,CKB11,CKB12;
definitions TARSKI,CAT_1,FUNCT_1,NATTRA_1,XBOOLE_0,CAT_2,BINOP_1,CKB7,CKB11,CKB12;
theorems FUNCT_2,CAT_1,ZFMISC_1,FUNCT_1,FUNCT_3,NATTRA_1,RELAT_1,TARSKI,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14;
registrations RELSET_1,FUNCT_2,STRUCT_0;
constructors PARTFUN1,NATTRA_1,FUNCOP_1,RELSET_1,CKB11;
requirements SUBSET,BOOLE;
begin
reserve A for Category;
reserve B for Category;
reserve F for (Functor of A,B);
theorem
(F is  isomorphic implies ( ( F " ) " ) = F)
proof
reconsider f = F as (Function of (the carrier' of A),(the carrier' of B));
reconsider g = ( F " ) as (Function of (the carrier' of B),(the carrier' of A));
assume A1: F is  isomorphic;
then A2: F is  one-to-one by CAT_1:def 19;
thus ( ( F " ) " ) = ( g " ) by A1,CKB11:def 1,CKB13:1
.= ( ( f " ) " ) by A1,CKB11:def 1
.= F by A2,FUNCT_1:43;
end;
