environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,SUBSET_1,FINSEQ_1,PARTFUN1,CARD_1,XXREAL_0,ARYTM_3,FUNCT_1,XREAL_0,ORDINAL1,INT_1,RELAT_1,ARYTM_1,POWER,ABIAN,ZFMISC_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,XCMPLX_0,XREAL_0,NUMBERS,INT_1,NAT_1,NAT_D,POWER,ABIAN,FUNCT_1,PARTFUN1,FINSEQ_1,XXREAL_0;
theorems AXIOMS,INT_1,NAT_1,ABIAN,POWER,FINSEQ_1,FINSEQ_4,XREAL_1,TARSKI,XCMPLX_1,ORDINAL1,NAT_D,XXREAL_0,XREAL_0,ZFMISC_1,CARD_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes NAT_1,RECDEF_1,CKB1;
registrations RELSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,MEMBERED,ABIAN,SERIES_1,XBOOLE_0,ZFMISC_1,FINSEQ_1;
constructors XXREAL_0,REAL_1,NAT_1,NAT_D,MEMBERED,SERIES_1,BINARITH,ABIAN;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve i for Nat;
reserve k for Nat;
reserve n for Nat;
theorem
((((k divides n & 1 <= n) & 1 <= i) & i <= k) implies ( ( n -' i ) div k ) = ( ( n div k ) - 1 ))
proof
assume that
A1: k divides n
and
A2: 1 <= n
and
A3: 1 <= i
and
A4: i <= k;
A5: ( k -' i ) < k by A3,A4,CKB10:1;
A6: k <= n by A1,A2,NAT_D:7;
then ( i + k ) <= ( k + n ) by A4,XREAL_1:7;
then A7: i <= n by XREAL_1:6;
( n div k ) > ( 0 )
proof
assume (not ( n div k ) > ( 0 ));
then ( n div k ) = ( 0 );
hence contradiction by A3,A4,A6,CKB13:1;
end;
then ( n div k ) >= ( ( 0 ) + 1 ) by NAT_1:13;
then A8: ( ( n div k ) -' 1 ) = ( ( n div k ) - 1 ) by XREAL_1:233;
n = ( k * ( n div k ) ) by A1,NAT_D:3;
then ( n -' i ) = ( ( ( ( k * ( n div k ) ) - ( k * 1 ) ) + k ) - i ) by A7,XREAL_1:233
.= ( ( k * ( ( n div k ) -' 1 ) ) + ( k - i ) ) by A8
.= ( ( k * ( ( n div k ) -' 1 ) ) + ( k -' i ) ) by A4,XREAL_1:233;
hence thesis by A8,A5,NAT_D:def 1;
end;
