environ
vocabularies NUMBERS,SUPINF_1,PROB_1,XBOOLE_0,SETFAM_1,FUNCT_1,SUBSET_1,TARSKI,RELAT_1,CARD_1,ARYTM_3,NAT_1,XXREAL_0,ZFMISC_1,MEASURE1,SUPINF_2,VALUED_0,FUNCOP_1,XREAL_0,ARYTM_1,REAL_1,MEASURE3,MEASURE4;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,NUMBERS,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,XXREAL_0,XREAL_0,VALUED_0,FUNCOP_1,REAL_1,NAT_1,SETFAM_1,PROB_1,SUPINF_1,SUPINF_2,MEASURE1,MEASURE3,CKB4,CKB5;
definitions TARSKI,MEASURE3,XBOOLE_0,CKB4,CKB5;
theorems TARSKI,ENUMSET1,FUNCT_1,FUNCT_2,ZFMISC_1,NAT_1,SUPINF_2,MEASURE1,MEASURE2,MEASURE3,XBOOLE_0,XBOOLE_1,XXREAL_0,PROB_1,ORDINAL1,VALUED_0,XXREAL_3,FUNCOP_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13;
schemes NAT_1,FUNCT_2,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FUNCT_2,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEASURE1,VALUED_0,MEMBERED;
constructors ENUMSET1,PARTFUN1,REAL_1,NAT_1,PROB_2,MEASURE3,SUPINF_1,FUNCOP_1,RELSET_1,CKB4,CKB5;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve B for set;
reserve X for set;
reserve C for (C_Measure of X);
theorem
Th21: ( sigma_Field C ) is (SigmaField of X)
proof
A1: C is  nonnegative by CKB4:def 1;
A2: (for M being (N_Sub_set_fam of X) holds (M c= ( sigma_Field C ) implies ( union M ) in ( sigma_Field C )))
proof
let M being (N_Sub_set_fam of X);
assume A3: M c= ( sigma_Field C );
(for W,Z being (Subset of X) holds ((W c= ( union M ) & Z c= ( X \ ( union M ) )) implies ( ( C . W ) + ( C . Z ) ) <= ( C . ( W \/ Z ) )))
proof
reconsider S = ( bool X ) as (SigmaField of X) by CKB3:1;
let W being (Subset of X);
let Z being (Subset of X);
assume that
A4: W c= ( union M )
and
A5: Z c= ( X \ ( union M ) );
consider F being (Function of ( NAT ),( bool X )) such that A6: ( rng F ) = M by SUPINF_2:def 8;
consider G being (Function of ( NAT ),S) such that A7: ( G . ( 0 ) ) = ( F . ( 0 ) ) and A8: (for n being (Element of ( NAT )) holds ( G . ( n + 1 ) ) = ( ( F . ( n + 1 ) ) \/ ( G . n ) )) by MEASURE2:4;
consider B being (Function of ( NAT ),S) such that A9: ( B . ( 0 ) ) = ( F . ( 0 ) ) and A10: (for n being (Element of ( NAT )) holds ( B . ( n + 1 ) ) = ( ( F . ( n + 1 ) ) \ ( G . n ) )) by MEASURE2:8;
A11: ( union ( rng F ) ) = ( union ( rng B ) ) by A7,A8,A9,A10,CKB2:1;
defpred P[ (Element of ( NAT )) ]
 means
( G . $1 ) in ( sigma_Field C );
A12: (for n being (Element of ( NAT )) holds ( F . n ) in ( sigma_Field C ))
proof
let n being (Element of ( NAT ));
( F . n ) in M by A6,FUNCT_2:4;
hence thesis by A3;
end;
A13: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
let k being (Element of ( NAT ));
assume A14: ( G . k ) in ( sigma_Field C );
A15: ( F . ( k + 1 ) ) in ( sigma_Field C ) by A12;
( G . ( k + 1 ) ) = ( ( F . ( k + 1 ) ) \/ ( G . k ) ) by A8;
hence thesis by A14,A15,CKB10:1;
end;
A16: P[ ( 0 ) ] by A12,A7;
A17: (for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A16,A13);
consider Q being (Function of ( NAT ),S) such that A18: (for n being (Element of ( NAT )) holds ( Q . n ) = ( W /\ ( B . n ) )) by CKB13:1;
A19: ( union ( rng Q ) ) = ( W /\ ( union ( rng B ) ) ) by A18,CKB1:1;
consider QQ being (Function of ( NAT ),S) such that A20: ( QQ . ( 0 ) ) = ( Q . ( 0 ) ) and A21: (for n being (Element of ( NAT )) holds ( QQ . ( n + 1 ) ) = ( ( Q . ( n + 1 ) ) \/ ( QQ . n ) )) by MEASURE2:4;
reconsider Q,QQ,F,G as (Function of ( NAT ),( bool X ));
A22: ( F . ( 0 ) ) in ( sigma_Field C ) by A12;
defpred P[ (Element of ( NAT )) ]
 means
( C . ( Z \/ ( QQ . $1 ) ) ) = ( ( C . Z ) + ( ( Ser ( C * Q ) ) . $1 ) );
A23: ( C * Q ) is  nonnegative by A1,MEASURE1:25;
A24: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
defpred P[ (Element of ( NAT )) ]
 means
( QQ . $1 ) c= ( G . $1 );
let k being (Element of ( NAT ));
A25: ( ( F . ( k + 1 ) ) \ ( G . k ) ) c= ( F . ( k + 1 ) ) by XBOOLE_1:36;
A26: ( QQ . ( k + 1 ) ) = ( ( QQ . k ) \/ ( Q . ( k + 1 ) ) ) by A21;
A27: ( G . k ) in ( sigma_Field C ) by A17;
( F . ( k + 1 ) ) in ( sigma_Field C ) by A12;
then A28: ( ( F . ( k + 1 ) ) \ ( G . k ) ) in ( sigma_Field C ) by A27,CKB12:1;
A29: ( 0. ) <= ( ( C * Q ) . ( k + 1 ) ) by A23,SUPINF_2:39;
A30: ( 0. ) <= ( ( Ser ( C * Q ) ) . k ) by A23,SUPINF_2:40;
( QQ . ( 0 ) ) = ( W /\ ( F . ( 0 ) ) ) by A9,A18,A20;
then A31: P[ ( 0 ) ] by A7,XBOOLE_1:17;
(for n being (Element of ( NAT )) holds ( QQ . n ) misses ( ( F . ( n + 1 ) ) \ ( G . n ) ))
proof
let n being (Element of ( NAT ));
A32: (for n being (Element of ( NAT )) holds (P[ n ] implies P[ ( n + 1 ) ]))
proof
let n being (Element of ( NAT ));
assume A33: ( QQ . n ) c= ( G . n );
A34: ( W /\ ( F . ( n + 1 ) ) ) c= ( F . ( n + 1 ) ) by XBOOLE_1:17;
( W /\ ( ( F . ( n + 1 ) ) \ ( G . n ) ) ) c= ( W /\ ( F . ( n + 1 ) ) ) by XBOOLE_1:26,XBOOLE_1:36;
then A35: ( W /\ ( ( F . ( n + 1 ) ) \ ( G . n ) ) ) c= ( F . ( n + 1 ) ) by A34,XBOOLE_1:1;
( QQ . ( n + 1 ) ) = ( ( Q . ( n + 1 ) ) \/ ( QQ . n ) ) by A21
.= ( ( W /\ ( B . ( n + 1 ) ) ) \/ ( QQ . n ) ) by A18
.= ( ( W /\ ( ( F . ( n + 1 ) ) \ ( G . n ) ) ) \/ ( QQ . n ) ) by A10;
then ( QQ . ( n + 1 ) ) c= ( ( F . ( n + 1 ) ) \/ ( G . n ) ) by A33,A35,XBOOLE_1:13;
hence thesis by A8;
end;
A36: (for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A31,A32);
( G . n ) misses ( ( F . ( n + 1 ) ) \ ( G . n ) ) by XBOOLE_1:79;
hence thesis by A36,XBOOLE_1:63;
end;
then ( QQ . k ) misses ( ( F . ( k + 1 ) ) \ ( G . k ) );
then A37: ( ( QQ . k ) /\ ( ( F . ( k + 1 ) ) \ ( G . k ) ) ) = ( {} ) by XBOOLE_0:def 7;
A38: ( QQ . k ) c= ( X \ ( ( F . ( k + 1 ) ) \ ( G . k ) ) )
proof
let z being set;
assume A39: z in ( QQ . k );
then (not z in ( ( F . ( k + 1 ) ) \ ( G . k ) )) by A37,XBOOLE_0:def 4;
hence thesis by A39,XBOOLE_0:def 5;
end;
( Q . ( k + 1 ) ) = ( W /\ ( B . ( k + 1 ) ) ) by A18
.= ( W /\ ( ( F . ( k + 1 ) ) \ ( G . k ) ) ) by A10;
then A40: ( Q . ( k + 1 ) ) c= ( ( F . ( k + 1 ) ) \ ( G . k ) ) by XBOOLE_1:17;
( F . ( k + 1 ) ) c= ( union ( rng F ) ) by FUNCT_2:4,ZFMISC_1:74;
then ( ( F . ( k + 1 ) ) \ ( G . k ) ) c= ( union ( rng F ) ) by A25,XBOOLE_1:1;
then ( X \ ( union ( rng F ) ) ) c= ( X \ ( ( F . ( k + 1 ) ) \ ( G . k ) ) ) by XBOOLE_1:34;
then Z c= ( X \ ( ( F . ( k + 1 ) ) \ ( G . k ) ) ) by A5,A6,XBOOLE_1:1;
then ( Z \/ ( QQ . k ) ) c= ( X \ ( ( F . ( k + 1 ) ) \ ( G . k ) ) ) by A38,XBOOLE_1:8;
then A41: ( ( C . ( Q . ( k + 1 ) ) ) + ( C . ( Z \/ ( QQ . k ) ) ) ) = ( C . ( ( Z \/ ( QQ . k ) ) \/ ( Q . ( k + 1 ) ) ) ) by A40,A28,CKB7:1
.= ( C . ( Z \/ ( QQ . ( k + 1 ) ) ) ) by A26,XBOOLE_1:4;
A42: ( 0. ) <= ( C . Z ) by A1,SUPINF_2:39;
assume ( C . ( Z \/ ( QQ . k ) ) ) = ( ( C . Z ) + ( ( Ser ( C * Q ) ) . k ) );
then ( C . ( Z \/ ( QQ . ( k + 1 ) ) ) ) = ( ( ( C . Z ) + ( ( Ser ( C * Q ) ) . k ) ) + ( ( C * Q ) . ( k + 1 ) ) ) by A41,FUNCT_2:15
.= ( ( C . Z ) + ( ( ( Ser ( C * Q ) ) . k ) + ( ( C * Q ) . ( k + 1 ) ) ) ) by A42,A30,A29,XXREAL_3:44
.= ( ( C . Z ) + ( ( Ser ( C * Q ) ) . ( k + 1 ) ) ) by SUPINF_2:44;
hence thesis;
end;
( QQ . ( 0 ) ) = ( W /\ ( F . ( 0 ) ) ) by A9,A18,A20;
then A43: ( QQ . ( 0 ) ) c= ( F . ( 0 ) ) by XBOOLE_1:17;
A44: ( ( Ser ( C * Q ) ) . ( 0 ) ) = ( ( C * Q ) . ( 0 ) ) by SUPINF_2:44
.= ( C . ( QQ . ( 0 ) ) ) by A20,FUNCT_2:15;
( F . ( 0 ) ) in ( rng F ) by FUNCT_2:4;
then ( X \ ( union ( rng F ) ) ) c= ( X \ ( F . ( 0 ) ) ) by XBOOLE_1:34,ZFMISC_1:74;
then Z c= ( X \ ( F . ( 0 ) ) ) by A5,A6,XBOOLE_1:1;
then A45: P[ ( 0 ) ] by A22,A43,A44,CKB7:1;
A46: (for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A45,A24);
defpred Q[ (Element of ( NAT )) ]
 means
( QQ . $1 ) c= W;
A47: (for n being (Element of ( NAT )) holds (Q[ n ] implies Q[ ( n + 1 ) ]))
proof
let n being (Element of ( NAT ));
assume A48: ( QQ . n ) c= W;
A49: ( W /\ ( B . ( n + 1 ) ) ) c= W by XBOOLE_1:17;
( QQ . ( n + 1 ) ) = ( ( Q . ( n + 1 ) ) \/ ( QQ . n ) ) by A21
.= ( ( W /\ ( B . ( n + 1 ) ) ) \/ ( QQ . n ) ) by A18;
then ( QQ . ( n + 1 ) ) c= ( W \/ W ) by A48,A49,XBOOLE_1:13;
hence thesis;
end;
( QQ . ( 0 ) ) = ( W /\ ( B . ( 0 ) ) ) by A18,A20;
then A50: Q[ ( 0 ) ] by XBOOLE_1:17;
A51: (for n being (Element of ( NAT )) holds Q[ n ]) from NAT_1:sch 1(A50,A47);
A52: ( union ( rng Q ) ) = W by A4,A6,A11,A19,XBOOLE_1:28;
A53: (( C . Z ) is  real implies ( ( C . W ) + ( C . Z ) ) <= ( C . ( W \/ Z ) ))
proof
defpred P[ set,set ]
 means
(($1 = ( 0 ) implies $2 = ( ( C . ( Z \/ W ) ) - ( C . Z ) )) & ($1 <> ( 0 ) implies $2 = ( 0. )));
A54: (for x being set holds (x in ( NAT ) implies (ex y being set st (y in ( ExtREAL ) & P[ x,y ]))))
proof
let x being set;
assume x in ( NAT );
then reconsider x as (Element of ( NAT ));
(x <> ( 0 ) implies (ex y being set st (y in ( ExtREAL ) & P[ x,y ])));
hence thesis;
end;
consider R being (Function of ( NAT ),( ExtREAL )) such that A55: (for x being set holds (x in ( NAT ) implies P[ x,( R . x ) ])) from FUNCT_2:sch 1(A54);
assume A56: ( C . Z ) is  real;
(for n being (Element of ( NAT )) holds ( 0. ) <= ( R . n ))
proof
let n being (Element of ( NAT ));
(( C . Z ) in ( REAL ) or ( C . Z ) in { ( -infty ),( +infty ) }) by XBOOLE_0:def 3,XXREAL_0:def 4;
then consider y being Real such that A57: y = ( C . Z ) by A56,TARSKI:def 2;
Z c= ( Z \/ W ) by XBOOLE_1:7;
then ( C . Z ) <= ( C . ( Z \/ W ) ) by CKB4:def 1;
then A58: ( ( C . Z ) - ( C . Z ) ) <= ( ( C . ( Z \/ W ) ) - ( C . Z ) ) by XXREAL_3:37;
( ( C . Z ) - ( C . Z ) ) = ( y - y ) by A57,SUPINF_2:3;
hence thesis by A55,A58;
end;
then A59: R is  nonnegative by SUPINF_2:39;
A60: (for n being (Element of ( NAT )) holds ( ( Ser ( C * Q ) ) . n ) <= ( ( C . ( Z \/ W ) ) - ( C . Z ) ))
proof
let n being (Element of ( NAT ));
A61: ( Z \/ ( QQ . n ) ) c= ( Z \/ W ) by A51,XBOOLE_1:9;
( ( ( Ser ( C * Q ) ) . n ) + ( C . Z ) ) = ( C . ( Z \/ ( QQ . n ) ) ) by A46;
then ( ( ( Ser ( C * Q ) ) . n ) + ( C . Z ) ) <= ( C . ( Z \/ W ) ) by A61,CKB4:def 1;
hence thesis by A56,XXREAL_3:45;
end;
A62: (for n being (Element of ( NAT )) holds ( ( Ser ( C * Q ) ) . n ) <= ( ( Ser R ) . n ))
proof
let n being (Element of ( NAT ));
defpred P[ (Element of ( NAT )) ]
 means
( ( Ser R ) . $1 ) = ( ( C . ( Z \/ W ) ) - ( C . Z ) );
A63: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
let k being (Element of ( NAT ));
assume A64: ( ( Ser R ) . k ) = ( ( C . ( Z \/ W ) ) - ( C . Z ) );
set y = ( ( Ser R ) . k );
thus ( ( Ser R ) . ( k + 1 ) ) = ( y + ( R . ( k + 1 ) ) ) by SUPINF_2:44
.= ( y + ( 0. ) ) by A55
.= ( ( C . ( Z \/ W ) ) - ( C . Z ) ) by A64,XXREAL_3:4;
end;
( ( Ser R ) . ( 0 ) ) = ( R . ( 0 ) ) by SUPINF_2:44;
then A65: P[ ( 0 ) ] by A55;
(for k being (Element of ( NAT )) holds P[ k ]) from NAT_1:sch 1(A65,A63);
then ( ( Ser R ) . n ) = ( ( C . ( Z \/ W ) ) - ( C . Z ) );
hence thesis by A60;
end;
set y = ( ( Ser R ) . ( 0 ) );
y = ( R . ( 0 ) ) by SUPINF_2:44;
then A66: y = ( ( C . ( Z \/ W ) ) - ( C . Z ) ) by A55;
A67: ( C . W ) <= ( SUM ( C * Q ) ) by A52,CKB4:def 1;
(for k being (Element of ( NAT )) holds (1 <= k implies ( R . k ) = ( 0. ))) by A55;
then A68: ( SUM R ) = ( ( Ser R ) . 1 ) by A59,SUPINF_2:48;
( ( Ser R ) . 1 ) = ( y + ( R . ( ( 0 ) + 1 ) ) ) by SUPINF_2:44
.= ( y + ( 0. ) ) by A55
.= ( ( C . ( Z \/ W ) ) - ( C . Z ) ) by A66,XXREAL_3:4;
then ( SUM ( C * Q ) ) <= ( ( C . ( Z \/ W ) ) - ( C . Z ) ) by A62,A68,MEASURE3:1;
then ( C . W ) <= ( ( C . ( Z \/ W ) ) - ( C . Z ) ) by A67,XXREAL_0:2;
hence thesis by A56,XXREAL_3:45;
end;
A69: (( C . Z ) = ( +infty ) implies ( ( C . W ) + ( C . Z ) ) <= ( C . ( W \/ Z ) ))
proof
A70: Z c= ( W \/ Z ) by XBOOLE_1:7;
assume A71: ( C . Z ) = ( +infty );
( 0. ) <= ( C . W ) by A1,MEASURE1:def 2;
then ( ( C . W ) + ( C . Z ) ) = ( +infty ) by A71,XXREAL_3:def 2;
hence thesis by A71,A70,CKB4:def 1;
end;
( 0 ) <= ( C . Z ) by A1,MEASURE1:def 2;
then (( C . Z ) is (Element of ( REAL )) or ( C . Z ) = ( +infty )) by XXREAL_0:14;
hence thesis by A69,A53;
end;
hence thesis by CKB5:def 1;
end;
(for A being set holds (A in ( sigma_Field C ) implies ( X \ A ) in ( sigma_Field C ))) by CKB9:1;
then reconsider Y = ( sigma_Field C ) as non  empty  compl-closed  sigma-additive (Subset-Family of X) by A2,MEASURE1:def 1,MEASURE1:def 5;
Y is (SigmaField of X);
hence thesis;
end;
