environ
vocabularies NUMBERS,REAL_1,SUBSET_1,SEQ_1,PARTFUN1,XREAL_0,ORDINAL1,CARD_1,ARYTM_3,XXREAL_0,ARYTM_1,RELAT_1,TARSKI,VALUED_1,XBOOLE_0,LIMFUNC1,FUNCT_1,COMPLEX1,SEQ_2,ORDINAL2,XXREAL_1,FUNCT_2,LIMFUNC2,NAT_1,VALUED_0,XXREAL_2,ORDINAL4,LIMFUNC3;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_2,VALUED_0,VALUED_1,SEQ_1,PARTFUN1,SEQ_2,RCOMP_1,RFUNCT_1,LIMFUNC1,LIMFUNC2,RECDEF_1,CKB13,CKB14,CKB15,CKB35;
definitions TARSKI,XBOOLE_0,VALUED_1,PROB_1,LIMFUNC1,CKB13,CKB14,CKB15,CKB35;
theorems TARSKI,NAT_1,FUNCT_1,FUNCT_2,ABSVALUE,SEQ_1,SEQ_2,SEQM_3,SEQ_4,RFUNCT_1,RCOMP_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,RELSET_1,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_0,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,XXREAL_1,VALUED_0,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44;
schemes NAT_1,RECDEF_1,FUNCT_2;
registrations ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,SEQ_4;
constructors REAL_1,NAT_1,COMPLEX1,SEQ_2,SEQM_3,PROB_1,RCOMP_1,PARTFUN1,RFUNCT_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,VALUED_1,SEQ_1,RECDEF_1,RELSET_1,CKB13,CKB14,CKB15,CKB35;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve r1 for Real;
reserve r2 for Real;
reserve g1 for Real;
reserve g2 for Real;
reserve x0 for Real;
reserve seq for Real_Sequence;
reserve f for (PartFunc of ( REAL ),( REAL ));
theorem
Th41: (((f is_convergent_in x0 & ( lim (f,x0) ) <> ( 0 )) & (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((((r1 < g1 & g1 < x0) & g1 in ( dom f )) & g2 < r2) & x0 < g2) & g2 in ( dom f )) & ( f . g1 ) <> ( 0 )) & ( f . g2 ) <> ( 0 )))))))) implies (( f ^ ) is_convergent_in x0 & ( lim (( f ^ ),x0) ) = ( ( lim (f,x0) ) " )))
proof
assume that
A1: f is_convergent_in x0
and
A2: ( lim (f,x0) ) <> ( 0 )
and
A3: (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((((r1 < g1 & g1 < x0) & g1 in ( dom f )) & g2 < r2) & x0 < g2) & g2 in ( dom f )) & ( f . g1 ) <> ( 0 )) & ( f . g2 ) <> ( 0 )))))));
A4: ( ( dom f ) \ ( f " { ( 0 ) } ) ) = ( dom ( f ^ ) ) by RFUNCT_1:def 2;
A5:now
let seq;
assume that
A6: seq is  convergent
and
A7: ( lim seq ) = x0
and
A8: ( rng seq ) c= ( ( dom ( f ^ ) ) \ { x0 } );
A9: ( f /* seq ) is  non-zero by A8,RFUNCT_2:11,XBOOLE_1:1;
( rng seq ) c= ( dom ( f ^ ) ) by A8,XBOOLE_1:1;
then A10: ( rng seq ) c= ( dom f ) by A4,XBOOLE_1:1;
now
let x being set;
assume A11: x in ( rng seq );
then (not x in { x0 }) by A8,XBOOLE_0:def 5;
hence x in ( ( dom f ) \ { x0 } ) by A10,A11,XBOOLE_0:def 5;
end;
then A12: ( rng seq ) c= ( ( dom f ) \ { x0 } ) by TARSKI:def 3;
then A13: ( lim ( f /* seq ) ) = ( lim (f,x0) ) by A1,A6,A7,CKB35:def 1;
A14: ( ( f /* seq ) " ) = ( ( f ^ ) /* seq ) by A8,RFUNCT_2:12,XBOOLE_1:1;
A15: ( f /* seq ) is  convergent by A1,A2,A6,A7,A12,CKB35:def 1;
hence ( ( f ^ ) /* seq ) is  convergent by A2,A13,A9,A14,SEQ_2:21;
thus ( lim ( ( f ^ ) /* seq ) ) = ( ( lim (f,x0) ) " ) by A2,A15,A13,A9,A14,SEQ_2:22;
end;
now
let r1;
let r2;
assume that
A16: r1 < x0
and
A17: x0 < r2;
consider g1,g2 such that A18: r1 < g1 and A19: g1 < x0 and A20: g1 in ( dom f ) and A21: g2 < r2 and A22: x0 < g2 and A23: g2 in ( dom f ) and A24: ( f . g1 ) <> ( 0 ) and A25: ( f . g2 ) <> ( 0 ) by A3,A16,A17;
take g1;
take g2;
(not ( f . g2 ) in { ( 0 ) }) by A25,TARSKI:def 1;
then A26: (not g2 in ( f " { ( 0 ) } )) by FUNCT_1:def 7;
(not ( f . g1 ) in { ( 0 ) }) by A24,TARSKI:def 1;
then (not g1 in ( f " { ( 0 ) } )) by FUNCT_1:def 7;
hence (((((r1 < g1 & g1 < x0) & g1 in ( dom ( f ^ ) )) & g2 < r2) & x0 < g2) & g2 in ( dom ( f ^ ) )) by A4,A18,A19,A20,A21,A22,A23,A26,XBOOLE_0:def 5;
end;
hence ( f ^ ) is_convergent_in x0 by A5,CKB13:def 1;
hence thesis by A5,CKB35:def 1;
end;
