environ
vocabularies NUMBERS,REAL_1,SUBSET_1,SEQ_1,PARTFUN1,XREAL_0,ORDINAL1,CARD_1,ARYTM_3,XXREAL_0,ARYTM_1,RELAT_1,TARSKI,VALUED_1,XBOOLE_0,LIMFUNC1,FUNCT_1,COMPLEX1,SEQ_2,ORDINAL2,XXREAL_1,FUNCT_2,LIMFUNC2,NAT_1,VALUED_0,XXREAL_2,ORDINAL4,LIMFUNC3;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_2,VALUED_0,VALUED_1,SEQ_1,PARTFUN1,SEQ_2,RCOMP_1,RFUNCT_1,LIMFUNC1,LIMFUNC2,RECDEF_1,CKB13,CKB14,CKB15,CKB35;
definitions TARSKI,XBOOLE_0,VALUED_1,PROB_1,LIMFUNC1,CKB13,CKB14,CKB15,CKB35;
theorems TARSKI,NAT_1,FUNCT_1,FUNCT_2,ABSVALUE,SEQ_1,SEQ_2,SEQM_3,SEQ_4,RFUNCT_1,RCOMP_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,RELSET_1,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_0,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,XXREAL_1,VALUED_0,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43;
schemes NAT_1,RECDEF_1,FUNCT_2;
registrations ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,SEQ_4;
constructors REAL_1,NAT_1,COMPLEX1,SEQ_2,SEQM_3,PROB_1,RCOMP_1,PARTFUN1,RFUNCT_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,VALUED_1,SEQ_1,RECDEF_1,RELSET_1,CKB13,CKB14,CKB15,CKB35;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve r1 for Real;
reserve r2 for Real;
reserve g1 for Real;
reserve g2 for Real;
reserve x0 for Real;
reserve seq for Real_Sequence;
reserve f for (PartFunc of ( REAL ),( REAL ));
theorem
(f is_convergent_in x0 implies (( abs f ) is_convergent_in x0 & ( lim (( abs f ),x0) ) = ( abs ( lim (f,x0) ) )))
proof
assume A1: f is_convergent_in x0;
A2:now
let seq;
assume that
A3: seq is  convergent
and
A4: ( lim seq ) = x0
and
A5: ( rng seq ) c= ( ( dom ( abs f ) ) \ { x0 } );
A6: ( rng seq ) c= ( ( dom f ) \ { x0 } ) by A5,VALUED_1:def 11;
then ( rng seq ) c= ( dom f ) by XBOOLE_1:1;
then A7: ( abs ( f /* seq ) ) = ( ( abs f ) /* seq ) by RFUNCT_2:10;
( lim (f,x0) ) = ( lim (f,x0) );
then A8: ( f /* seq ) is  convergent by A1,A3,A4,A6,CKB35:def 1;
hence ( ( abs f ) /* seq ) is  convergent by A7;
( lim ( f /* seq ) ) = ( lim (f,x0) ) by A1,A3,A4,A6,CKB35:def 1;
hence ( lim ( ( abs f ) /* seq ) ) = ( abs ( lim (f,x0) ) ) by A8,A7,SEQ_4:14;
end;
now
let r1;
let r2;
assume that
A9: r1 < x0
and
A10: x0 < r2;
consider g1,g2 such that A11: r1 < g1 and A12: g1 < x0 and A13: g1 in ( dom f ) and A14: g2 < r2 and A15: x0 < g2 and A16: g2 in ( dom f ) by A1,A9,A10,CKB13:def 1;
take g1;
take g2;
thus (((((r1 < g1 & g1 < x0) & g1 in ( dom ( abs f ) )) & g2 < r2) & x0 < g2) & g2 in ( dom ( abs f ) )) by A11,A12,A13,A14,A15,A16,VALUED_1:def 11;
end;
hence ( abs f ) is_convergent_in x0 by A2,CKB13:def 1;
hence thesis by A2,CKB35:def 1;
end;
