environ
vocabularies NUMBERS,REAL_1,SUBSET_1,SEQ_1,PARTFUN1,XREAL_0,ORDINAL1,CARD_1,ARYTM_3,XXREAL_0,ARYTM_1,RELAT_1,TARSKI,VALUED_1,XBOOLE_0,LIMFUNC1,FUNCT_1,COMPLEX1,SEQ_2,ORDINAL2,XXREAL_1,FUNCT_2,LIMFUNC2,NAT_1,VALUED_0,XXREAL_2,ORDINAL4,LIMFUNC3;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_2,VALUED_0,VALUED_1,SEQ_1,PARTFUN1,SEQ_2,RCOMP_1,RFUNCT_1,LIMFUNC1,LIMFUNC2,RECDEF_1,CKB13,CKB14,CKB15,CKB35;
definitions TARSKI,XBOOLE_0,VALUED_1,PROB_1,LIMFUNC1,CKB13,CKB14,CKB15,CKB35;
theorems TARSKI,NAT_1,FUNCT_1,FUNCT_2,ABSVALUE,SEQ_1,SEQ_2,SEQM_3,SEQ_4,RFUNCT_1,RCOMP_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,RELSET_1,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_0,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,XXREAL_1,VALUED_0,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52;
schemes NAT_1,RECDEF_1,FUNCT_2;
registrations ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,SEQ_4;
constructors REAL_1,NAT_1,COMPLEX1,SEQ_2,SEQM_3,PROB_1,RCOMP_1,PARTFUN1,RFUNCT_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,VALUED_1,SEQ_1,RECDEF_1,RELSET_1,CKB13,CKB14,CKB15,CKB35;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve r for Real;
reserve r1 for Real;
reserve r2 for Real;
reserve g for Real;
reserve g1 for Real;
reserve g2 for Real;
reserve x0 for Real;
reserve n for (Element of ( NAT ));
reserve k for (Element of ( NAT ));
reserve f for (PartFunc of ( REAL ),( REAL ));
theorem
((((f is_convergent_in x0 & ( lim (f,x0) ) = ( 0 )) & (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((((r1 < g1 & g1 < x0) & g1 in ( dom f )) & g2 < r2) & x0 < g2) & g2 in ( dom f )) & ( f . g1 ) <> ( 0 )) & ( f . g2 ) <> ( 0 )))))))) & (ex r st (( 0 ) < r & (for g holds (g in ( ( dom f ) /\ ( ]. ( x0 - r ),x0 .[ \/ ]. x0,( x0 + r ) .[ ) ) implies ( 0 ) <= ( f . g )))))) implies ( f ^ ) is_divergent_to+infty_in x0)
proof
assume that
A1: f is_convergent_in x0
and
A2: ( lim (f,x0) ) = ( 0 )
and
A3: (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((((r1 < g1 & g1 < x0) & g1 in ( dom f )) & g2 < r2) & x0 < g2) & g2 in ( dom f )) & ( f . g1 ) <> ( 0 )) & ( f . g2 ) <> ( 0 )))))));
given r such that
A4: ( 0 ) < r
and
A5: (for g holds (g in ( ( dom f ) /\ ( ]. ( x0 - r ),x0 .[ \/ ]. x0,( x0 + r ) .[ ) ) implies ( 0 ) <= ( f . g )));

thus (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((r1 < g1 & g1 < x0) & g1 in ( dom ( f ^ ) )) & g2 < r2) & x0 < g2) & g2 in ( dom ( f ^ ) )))))))
proof
let r1;
let r2;
assume that
A6: r1 < x0
and
A7: x0 < r2;
consider g1,g2 such that A8: r1 < g1 and A9: g1 < x0 and A10: g1 in ( dom f ) and A11: g2 < r2 and A12: x0 < g2 and A13: g2 in ( dom f ) and A14: ( f . g1 ) <> ( 0 ) and A15: ( f . g2 ) <> ( 0 ) by A3,A6,A7;
(not ( f . g2 ) in { ( 0 ) }) by A15,TARSKI:def 1;
then (not g2 in ( f " { ( 0 ) } )) by FUNCT_1:def 7;
then A16: g2 in ( ( dom f ) \ ( f " { ( 0 ) } ) ) by A13,XBOOLE_0:def 5;
take g1;
take g2;
(not ( f . g1 ) in { ( 0 ) }) by A14,TARSKI:def 1;
then (not g1 in ( f " { ( 0 ) } )) by FUNCT_1:def 7;
then g1 in ( ( dom f ) \ ( f " { ( 0 ) } ) ) by A10,XBOOLE_0:def 5;
hence thesis by A8,A9,A11,A12,A16,RFUNCT_1:def 2;
end;

let s being Real_Sequence;
assume that
A17: s is  convergent
and
A18: ( lim s ) = x0
and
A19: ( rng s ) c= ( ( dom ( f ^ ) ) \ { x0 } );
consider k such that A20: (for n holds (k <= n implies (( x0 - r ) < ( s . n ) & ( s . n ) < ( x0 + r )))) by A4,A17,A18,CKB11:1;
A21: ( rng s ) c= ( dom ( f ^ ) ) by A19,XBOOLE_1:1;
A22: ( dom ( f ^ ) ) = ( ( dom f ) \ ( f " { ( 0 ) } ) ) by RFUNCT_1:def 2;
then A23: ( ( f /* ( s ^\ k ) ) " ) = ( ( ( f /* s ) ^\ k ) " ) by A21,VALUED_0:27,XBOOLE_1:1
.= ( ( ( f /* s ) " ) ^\ k ) by SEQM_3:18
.= ( ( ( f ^ ) /* s ) ^\ k ) by A19,RFUNCT_2:12,XBOOLE_1:1;
A24: ( rng ( s ^\ k ) ) c= ( rng s ) by VALUED_0:21;
A25: ( rng s ) c= ( dom f ) by A21,A22,XBOOLE_1:1;
then A26: ( rng ( s ^\ k ) ) c= ( dom f ) by A24,XBOOLE_1:1;
A27: ( rng ( s ^\ k ) ) c= ( ( dom ( f ^ ) ) \ { x0 } ) by A19,A24,XBOOLE_1:1;
A28: ( rng ( s ^\ k ) ) c= ( ( dom f ) \ { x0 } )
proof
let x being set;
assume A29: x in ( rng ( s ^\ k ) );
then (not x in { x0 }) by A27,XBOOLE_0:def 5;
hence thesis by A26,A29,XBOOLE_0:def 5;
end;
A30: ( lim ( s ^\ k ) ) = x0 by A17,A18,SEQ_4:20;
then A31: ( lim ( f /* ( s ^\ k ) ) ) = ( 0 ) by A1,A2,A17,A28,CKB35:def 1;
A32: ( f /* ( s ^\ k ) ) is  non-zero by A21,A24,RFUNCT_2:11,XBOOLE_1:1;
now
let n;
A33: k <= ( n + k ) by NAT_1:12;
then ( s . ( n + k ) ) < ( x0 + r ) by A20;
then A34: ( ( s ^\ k ) . n ) < ( x0 + r ) by NAT_1:def 3;
( x0 - r ) < ( s . ( n + k ) ) by A20,A33;
then ( x0 - r ) < ( ( s ^\ k ) . n ) by NAT_1:def 3;
then ( ( s ^\ k ) . n ) in { g1: (( x0 - r ) < g1 & g1 < ( x0 + r )) } by A34;
then A35: ( ( s ^\ k ) . n ) in ]. ( x0 - r ),( x0 + r ) .[ by RCOMP_1:def 2;
A36: ( ( s ^\ k ) . n ) in ( rng ( s ^\ k ) ) by VALUED_0:28;
then (not ( ( s ^\ k ) . n ) in { x0 }) by A27,XBOOLE_0:def 5;
then ( ( s ^\ k ) . n ) in ( ]. ( x0 - r ),( x0 + r ) .[ \ { x0 } ) by A35,XBOOLE_0:def 5;
then ( ( s ^\ k ) . n ) in ( ]. ( x0 - r ),x0 .[ \/ ]. x0,( x0 + r ) .[ ) by A4,CKB8:1;
then ( ( s ^\ k ) . n ) in ( ( dom f ) /\ ( ]. ( x0 - r ),x0 .[ \/ ]. x0,( x0 + r ) .[ ) ) by A26,A36,XBOOLE_0:def 4;
then A37: ( 0 ) <= ( f . ( ( s ^\ k ) . n ) ) by A5;
( ( f /* ( s ^\ k ) ) . n ) <> ( 0 ) by A32,SEQ_1:5;
hence ( 0 ) < ( ( f /* ( s ^\ k ) ) . n ) by A25,A24,A37,FUNCT_2:108,XBOOLE_1:1;
end;
then A38: (for n holds (( 0 ) <= n implies ( 0 ) < ( ( f /* ( s ^\ k ) ) . n )));
( f /* ( s ^\ k ) ) is  convergent by A1,A2,A17,A30,A28,CKB35:def 1;
then ( ( f /* ( s ^\ k ) ) " ) is  divergent_to+infty by A31,A38,LIMFUNC1:35;
hence thesis by A23,LIMFUNC1:7;
end;
