environ
vocabularies NUMBERS,GRAPH_1,FINSEQ_1,STRUCT_0,TREES_2,SUBSET_1,REAL_1,GRAPH_4,XXREAL_0,ARYTM_3,FUNCT_1,XBOOLE_0,CARD_1,ZFMISC_1,MCART_1,ARYTM_1,NAT_1,RELAT_1,TARSKI,PARTFUN1,GLIB_000,FINSET_1,EUCLID,RLTOPSP1,TOPREAL1,GOBOARD5,PRE_TOPC,SUPINF_2,GOBOARD1,GOBOARD4,COMPLEX1,METRIC_1,SQUARE_1,RVSUM_1,CARD_3,PCOMPS_1,RCOMP_1,WEIERSTR,INT_1,BORSUK_1,TOPS_2,ORDINAL2,XXREAL_1,MEASURE5,PSCOMP_1,XXREAL_2,XREAL_0,ORDINAL1,JGRAPH_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,BINOP_1,FINSEQ_1,FINSET_1,NAT_1,NAT_D,SEQ_1,SEQM_3,GRAPH_1,STRUCT_0,GRAPH_2,GRAPH_4,TOPREAL1,GOBOARD5,PRE_TOPC,GOBOARD1,GOBOARD4,TOPMETR,PCOMPS_1,COMPTS_1,WEIERSTR,TOPS_2,METRIC_1,TBSP_1,RCOMP_1,SQUARE_1,PSCOMP_1,RVSUM_1,RLVECT_1,RLTOPSP1,EUCLID,FUNCT_3,CKB2,CKB4,CKB8,CKB11,CKB13,CKB18;
definitions TARSKI,XBOOLE_0,FUNCT_1,EUCLID,SQUARE_1,BINOP_1,VALUED_1,STRUCT_0,ALGSTR_0,RLTOPSP1,CKB2,CKB4,CKB13,CKB18;
theorems TARSKI,FUNCT_1,FINSEQ_1,NAT_1,ZFMISC_1,SPPOL_1,FINSEQ_4,GRAPH_1,FUNCT_3,RELAT_1,GRAPH_4,FINSEQ_3,TOPREAL1,GOBOARD1,GOBOARD5,GOBOARD4,TOPREAL3,SQUARE_1,EUCLID,JORDAN7,UNIFORM1,WEIERSTR,JORDAN5A,TOPS_2,PRE_TOPC,TBSP_1,HEINE,COMPTS_1,TOPMETR,PSCOMP_1,BORSUK_1,ABSVALUE,METRIC_1,RVSUM_1,FUNCT_2,JORDAN6,XBOOLE_0,XBOOLE_1,TOPRNS_1,XCMPLX_0,COMPLEX1,XREAL_1,XXREAL_0,ORDINAL1,NAT_D,PARTFUN1,XXREAL_1,XXREAL_2,SEQM_3,XREAL_0,VALUED_1,RLTOPSP1,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB6,CKB7,CKB9,CKB10,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21;
schemes FINSEQ_1;
registrations XBOOLE_0,RELAT_1,FUNCT_1,XXREAL_0,XREAL_0,NAT_1,MEMBERED,FINSEQ_1,STRUCT_0,PRE_TOPC,METRIC_1,BORSUK_1,MONOID_0,EUCLID,GRAPH_2,GRAPH_4,FINSET_1,VALUED_0,FUNCT_2,CARD_1,XXREAL_2,TOPREAL1,RELSET_1,CKB5;
constructors FUNCT_3,REAL_1,SQUARE_1,NAT_1,NAT_D,RCOMP_1,BINARITH,TOPS_2,COMPTS_1,TBSP_1,MONOID_0,GOBOARD1,GOBOARD4,GOBOARD5,PSCOMP_1,GRAPH_2,WEIERSTR,GRAPH_4,SEQ_1,SEQM_3,XXREAL_2,FUNCSDOM,CKB2,CKB4,CKB8,CKB11,CKB13,CKB18;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
theorem
Th19: (for f being (FinSequence of ( TOP-REAL 2 )) holds (((f is  nodic & ( PairF f ) is  Simple) & ( f . 1 ) <> ( f . ( len f ) )) implies f is  s.n.c.))
proof
let f being (FinSequence of ( TOP-REAL 2 ));
assume that
A1: f is  nodic
and
A2: ( PairF f ) is  Simple
and
A3: ( f . 1 ) <> ( f . ( len f ) );
reconsider f1 = f as (FinSequence of (the carrier of ( PGraph (the carrier of ( TOP-REAL 2 )) )));
A4: ( ( len f ) -' 1 ) <= ( len f ) by NAT_D:44;
per cases ;
suppose A5: ( ( len f ) -' 1 ) > 2;

then A6: ( ( len f ) -' 1 ) > 1 by XXREAL_0:2;
then A7: 1 < ( len f ) by NAT_D:44;
( len f ) >= 1 by A6,NAT_D:44;
then A8: f1 is_oriented_vertex_seq_of ( PairF f ) by CKB12:1;
A9: ( 1 + 1 ) < ( len f ) by A5,NAT_D:44;
A10: ( ( len f ) -' 1 ) = ( ( len f ) - 1 ) by A6,NAT_D:39;
then A11: ( ( ( len f ) -' 1 ) + 1 ) = ( len f );
now
assume A12: ( LSeg (f,1) ) meets ( LSeg (f,( ( len f ) -' 1 )) );
now
per cases  by A1,A12,CKB18:def 1;
case (( ( LSeg (f,1) ) /\ ( LSeg (f,( ( len f ) -' 1 )) ) ) = { ( f . 1 ) } & (( f . 1 ) = ( f . ( ( len f ) -' 1 ) ) or ( f . 1 ) = ( f . ( ( ( len f ) -' 1 ) + 1 ) )));
hence contradiction by A2,A3,A4,A6,A8,A10,CKB1:1;
end;
case A13: (( ( LSeg (f,1) ) /\ ( LSeg (f,( ( len f ) -' 1 )) ) ) = { ( f . ( 1 + 1 ) ) } & (( f . ( 1 + 1 ) ) = ( f . ( ( len f ) -' 1 ) ) or ( f . ( 1 + 1 ) ) = ( f . ( ( ( len f ) -' 1 ) + 1 ) )));
now
per cases  by A13;
case ( f . ( 1 + 1 ) ) = ( f . ( ( len f ) -' 1 ) );
hence contradiction by A2,A4,A5,A8,CKB1:1;
end;
case ( f . ( 1 + 1 ) ) = ( f . ( ( ( len f ) -' 1 ) + 1 ) );
hence contradiction by A2,A8,A9,A10,CKB1:1;
end;
end;
hence contradiction;
end;
case ( LSeg (f,1) ) = ( LSeg (f,( ( len f ) -' 1 )) );
then ( LSeg (( f /. 1 ),( f /. ( 1 + 1 ) )) ) = ( LSeg (f,( ( len f ) -' 1 )) ) by A9,TOPREAL1:def 3;
then A14: ( LSeg (( f /. 1 ),( f /. ( 1 + 1 ) )) ) = ( LSeg (( f /. ( ( len f ) -' 1 ) ),( f /. ( ( ( len f ) -' 1 ) + 1 ) )) ) by A6,A10,TOPREAL1:def 3;
A15: ( 1 + 1 ) < ( ( ( len f ) -' 1 ) + 1 ) by A6,XREAL_1:6;
( ( len f ) -' 1 ) < ( len f ) by A11,NAT_1:13;
then A16: ( f /. ( ( len f ) -' 1 ) ) = ( f . ( ( len f ) -' 1 ) ) by A6,FINSEQ_4:15;
1 < ( len f ) by A6,NAT_D:44;
then A17: ( f /. 1 ) = ( f . 1 ) by FINSEQ_4:15;
A18: (( f /. ( 1 + 1 ) ) = ( f . ( 1 + 1 ) ) & ( f /. ( ( ( len f ) -' 1 ) + 1 ) ) = ( f . ( ( ( len f ) -' 1 ) + 1 ) )) by A7,A9,A10,FINSEQ_4:15;
now
per cases  by A14,A17,A16,A18,SPPOL_1:8;
case (( f . 1 ) = ( f . ( ( len f ) -' 1 ) ) & ( f . ( 1 + 1 ) ) = ( f . ( ( ( len f ) -' 1 ) + 1 ) ));
hence contradiction by A2,A8,A10,A15,CKB1:1;
end;
case (( f . 1 ) = ( f . ( ( ( len f ) -' 1 ) + 1 ) ) & ( f . ( 1 + 1 ) ) = ( f . ( ( len f ) -' 1 ) ));
hence contradiction by A3,A10;
end;
end;
hence contradiction;
end;
end;
hence contradiction;
end;
hence thesis by A1,A2,CKB20:1,CKB21:1;
end;
suppose A19: ( ( len f ) -' 1 ) <= 2;

(for i,j being Nat holds (( i + 1 ) < j implies ( LSeg (f,i) ) misses ( LSeg (f,j) )))
proof
let i being Nat,j being Nat;
assume A20: ( i + 1 ) < j;
per cases ;
suppose A21: (1 <= i & ( j + 1 ) <= ( len f ));

then 1 < ( i + 1 ) by NAT_1:13;
then ( 1 + 1 ) < ( ( i + 1 ) + 1 ) by XREAL_1:8;
then A22: ( ( 1 + 1 ) + 1 ) <= ( ( i + 1 ) + 1 ) by NAT_1:13;
( ( i + 1 ) + 1 ) < ( j + 1 ) by A20,XREAL_1:6;
then ( ( i + 1 ) + 1 ) < ( len f ) by A21,XXREAL_0:2;
then ( ( 1 + 1 ) + 1 ) < ( len f ) by A22,XXREAL_0:2;
then A23: ( ( ( 1 + 1 ) + 1 ) - 1 ) < ( ( len f ) - 1 ) by XREAL_1:9;
then 1 < ( ( len f ) - 1 ) by XXREAL_0:2;
hence thesis by A19,A23,NAT_D:39;
end;
suppose A24: (1 > i or ( j + 1 ) > ( len f ));

now
per cases  by A24;
case 1 > i;
then ( LSeg (f,i) ) = ( {} ) by TOPREAL1:def 3;
hence ( ( LSeg (f,i) ) /\ ( LSeg (f,j) ) ) = ( {} );
end;
case ( j + 1 ) > ( len f );
then ( LSeg (f,j) ) = ( {} ) by TOPREAL1:def 3;
hence ( ( LSeg (f,i) ) /\ ( LSeg (f,j) ) ) = ( {} );
end;
end;
hence thesis by XBOOLE_0:def 7;
end;
end;
hence thesis by TOPREAL1:def 7;
end;
end;
