environ
vocabularies NUMBERS,FINSEQ_1,SUBSET_1,GRAPH_1,FUNCT_1,STRUCT_0,TREES_2,XBOOLE_0,ARYTM_3,XXREAL_0,PARTFUN1,GRAPH_2,RELAT_1,TARSKI,CARD_1,NAT_1,ARYTM_1,ORDINAL4,GLIB_000,FINSET_1,FINSEQ_2,GRAPH_4;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FINSEQ_1,FINSEQ_2,CARD_1,FINSET_1,NUMBERS,XCMPLX_0,NAT_1,NAT_D,STRUCT_0,GRAPH_1,GRAPH_2,XXREAL_0,CKB1,CKB3,CKB5,CKB6,CKB8;
definitions TARSKI,FINSEQ_2,CKB1,CKB3,CKB5,CKB6,CKB8;
theorems TARSKI,NAT_1,FINSEQ_1,FINSEQ_2,GRAPH_1,RELAT_1,FUNCT_1,GRFUNC_1,FUNCT_2,FINSET_1,FINSEQ_3,FINSEQ_4,GRAPH_2,XBOOLE_0,XBOOLE_1,XREAL_1,CARD_1,XXREAL_0,ORDINAL1,NAT_D,XREAL_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8;
schemes NAT_1,FINSEQ_1,FUNCT_1;
registrations XBOOLE_0,RELAT_1,FUNCT_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,GRAPH_2,ORDINAL1,CARD_1,STRUCT_0,GRAPH_1;
constructors PARTFUN1,XXREAL_0,XREAL_0,NAT_1,RECDEF_1,BINARITH,GRAPH_2,NAT_D,FINSEQ_2,RELSET_1,CKB1,CKB3,CKB5,CKB6,CKB8;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve G for Graph;
reserve vs for (FinSequence of (the carrier of G));
reserve c for  oriented (Chain of G);
theorem
Th5: (vs is_oriented_vertex_seq_of c implies vs is_vertex_seq_of c)
proof
assume A1: vs is_oriented_vertex_seq_of c;
then A2: ( len vs ) = ( ( len c ) + 1 ) by CKB8:def 1;
(for n holds ((1 <= n & n <= ( len c )) implies ( c . n ) joins ( vs /. n ),( vs /. ( n + 1 ) )))
proof
let n;
assume that
A3: 1 <= n
and
A4: n <= ( len c );
( c . n ) orientedly_joins ( vs /. n ),( vs /. ( n + 1 ) ) by A1,A3,A4,CKB8:def 1;
hence thesis by CKB2:1;
end;
hence thesis by A2,GRAPH_2:def 6;
end;
