environ
vocabularies WAYBEL_0,SUBSET_1,LATTICES,XBOOLE_0,EQREL_1,ORDERS_2,ORDERS_1,STRUCT_0,XXREAL_0,TARSKI,ARYTM_3,LATTICE3,ARYTM_0,RELAT_1,RELAT_2,CARD_FIL,REWRITE1,FUNCT_1,FUNCOP_1,YELLOW_0,SEQM_3,FINSET_1,ORDINAL2,YELLOW_1,SETFAM_1,WELLORD2,ZFMISC_1,WAYBEL_1,WAYBEL_6,YELLOW_8,WAYBEL_2,INT_2,WAYBEL_3,WAYBEL_8,RCOMP_1,WAYBEL16;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,FINSET_1,RELSET_1,FUNCT_2,FUNCOP_1,DOMAIN_1,STRUCT_0,ORDERS_2,LATTICE3,YELLOW_0,YELLOW_1,YELLOW_4,YELLOW_7,WAYBEL_0,WAYBEL_1,WAYBEL_2,WAYBEL_3,WAYBEL_4,WAYBEL_6,WAYBEL_8,CKB9,CKB10;
definitions TARSKI,XBOOLE_0,CKB9,CKB10;
theorems TARSKI,SUBSET_1,SETFAM_1,RELAT_1,ZFMISC_1,FUNCOP_1,ORDERS_2,LATTICE3,YELLOW_0,YELLOW_1,YELLOW_2,YELLOW_4,YELLOW_7,WAYBEL_0,WAYBEL_1,WAYBEL_2,WAYBEL_3,WAYBEL_4,WAYBEL_6,WAYBEL_7,WAYBEL_8,WAYBEL13,WAYBEL14,WAYBEL15,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB12;
schemes DOMAIN_1,SUBSET_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSET_1,STRUCT_0,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_2,WAYBEL_3,YELLOW_7,WAYBEL_6,WAYBEL_8,CKB11;
constructors SETFAM_1,DOMAIN_1,ORDERS_3,WAYBEL_1,YELLOW_4,WAYBEL_2,WAYBEL_3,WAYBEL_4,WAYBEL_6,WAYBEL_8,RELSET_1,CKB9,CKB10;
requirements BOOLE,SUBSET;
begin
theorem
(for X being set holds (for Y being non empty (Subset of ( InclPoset ( Filt ( BoolePoset X ) ) )) holds ( ex_inf_of Y,( InclPoset ( Filt ( BoolePoset X ) ) ) & ( "/\" (Y,( InclPoset ( Filt ( BoolePoset X ) ) )) ) = ( meet Y ))))
proof
let X being set;
set L = ( InclPoset ( Filt ( BoolePoset X ) ) );
let Y being non empty (Subset of L);
( meet Y ) is (Filter of ( BoolePoset X )) by CKB12:1;
then ( meet Y ) in { Z where Z is (Filter of ( BoolePoset X )): (not contradiction) };
then ( meet Y ) in (the carrier of RelStr (# ( Filt ( BoolePoset X ) ),( RelIncl ( Filt ( BoolePoset X ) ) ) #)) by WAYBEL_0:def 24;
then reconsider a = ( meet Y ) as (Element of L) by YELLOW_1:def 1;
A1: (for b being (Element of L) holds (b is_<=_than Y implies b <= a))
proof
let b being (Element of L);
assume A2: b is_<=_than Y;
now
let x being set;
assume A3: x in Y;
then reconsider x9 = x as (Element of L);
b <= x9 by A2,A3,LATTICE3:def 8;
hence b c= x by YELLOW_1:3;
end;
then b c= ( meet Y ) by SETFAM_1:5;
hence thesis by YELLOW_1:3;
end;
now
let b being (Element of L);
assume b in Y;
then ( meet Y ) c= b by SETFAM_1:3;
hence a <= b by YELLOW_1:3;
end;
then a is_<=_than Y by LATTICE3:def 8;
hence thesis by A1,YELLOW_0:31;
end;
