environ
vocabularies NUMBERS,SUBSET_1,FUNCT_1,NAT_1,TARSKI,FINSET_1,RELAT_1,AFINSQ_1,ARYTM_1,ARYTM_3,FINSEQ_1,XXREAL_0,CARD_1,XBOOLE_0,ORDINAL4,CARD_3,BINOP_1,FINSOP_1,FUNCOP_1,BINOP_2,FUNCT_2,INT_1,VALUED_1,NEWTON,REALSET1,ZFMISC_1,FUNCT_4,EQREL_1,SETFAM_1,STIRL2_1,CARD_FIN;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,RELAT_1,FUNCT_1,NAT_1,FINSET_1,ORDINAL1,XXREAL_0,NAT_D,AFINSQ_1,VALUED_1,RELSET_1,PARTFUN1,DOMAIN_1,FUNCT_2,FUNCT_4,FUNCOP_1,INT_1,ENUMSET1,BINOP_1,BINOP_2,RECDEF_1,AFINSQ_2,ZFMISC_1,NEWTON,STIRL2_1,YELLOW20;
definitions TARSKI,XBOOLE_0,FUNCT_1,FUNCOP_1,FINSET_1,RELAT_1;
theorems AFINSQ_1,TARSKI,FUNCT_1,XBOOLE_0,ZFMISC_1,RELAT_1,XBOOLE_1,NAT_1,FUNCT_2,FINSET_1,XCMPLX_1,CARD_2,INT_1,WELLORD2,SUBSET_1,ENUMSET1,CARD_1,BINOP_2,NEWTON,XREAL_1,FUNCOP_1,STIRL2_1,ALTCAT_1,FUNCT_5,IRRAT_1,FUNCT_4,YELLOW20,XXREAL_0,NAT_D,XREAL_0,PRE_POLY,AFINSQ_2,ORDINAL1,VALUED_1,VALUED_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8;
schemes FUNCT_2,NAT_1,XBOOLE_0,STIRL2_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FUNCOP_1,FUNCT_4,FINSET_1,FRAENKEL,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,BINOP_2,CARD_1,WSIERP_1,AFINSQ_1,RELSET_1,VALUED_1,VALUED_0,AFINSQ_2;
constructors PARTFUN3,BINOM,WELLORD2,DOMAIN_1,SETWISEO,REAL_1,NAT_D,YELLOW20,RECDEF_1,BINOP_2,RELSET_1,ORDINAL4,SEQ_1,AFINSQ_1,SEQ_4,AFINSQ_2,STIRL2_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve x for set;
reserve x1 for set;
reserve x2 for set;
reserve X for  finite set;
reserve k for Nat;
reserve f for Function;
definition
let X;
let k;
let x1;
let x2;
func Choose (X,k,x1,x2) -> (Subset of ( Funcs (X,{ x1,x2 }) ))
means
:Def1: (x in it iff (ex f being (Function of X,{ x1,x2 }) st (f = x & ( card ( f " { x1 } ) ) = k)));
existence
proof
defpred P[ set ]
 means
(ex f being (Function of X,{ x1,x2 }) st ($1 = f & ( card ( f " { x1 } ) ) = k));
consider F being set such that A1: (x in F iff (x in ( bool [: X,{ x1,x2 } :] ) & P[ x ])) from XBOOLE_0:sch 1;
F c= ( Funcs (X,{ x1,x2 }) )
proof
let x;
assume x in F;
then (ex f being (Function of X,{ x1,x2 }) st (x = f & ( card ( f " { x1 } ) ) = k)) by A1;
hence thesis by FUNCT_2:8;
end;
then reconsider F as (Subset of ( Funcs (X,{ x1,x2 }) ));
take F;
let x;
thus (x in F implies (ex f being (Function of X,{ x1,x2 }) st (x = f & ( card ( f " { x1 } ) ) = k))) by A1;
given f being (Function of X,{ x1,x2 }) such that
A2: (x = f & ( card ( f " { x1 } ) ) = k);

thus thesis by A1,A2;
end;
uniqueness
proof
let F1 being (Subset of ( Funcs (X,{ x1,x2 }) )),F2 being (Subset of ( Funcs (X,{ x1,x2 }) ));
assume that
A3: (x in F1 iff (ex f being (Function of X,{ x1,x2 }) st (x = f & ( card ( f " { x1 } ) ) = k)))
and
A4: (x in F2 iff (ex f being (Function of X,{ x1,x2 }) st (x = f & ( card ( f " { x1 } ) ) = k)));
(x in F1 iff x in F2)
proof
(x in F1 iff (ex f being (Function of X,{ x1,x2 }) st (x = f & ( card ( f " { x1 } ) ) = k))) by A3;
hence thesis by A4;
end;
hence thesis by TARSKI:1;
end;
end;
