environ
vocabularies CONLAT_1,STRUCT_0,QC_LANG1,SUBSET_1,LATTICES,XXREAL_2,PBOOLE,EQREL_1,XBOOLE_0,SETFAM_1,FUNCT_1,TARSKI,CAT_1,LATTICE3,ZFMISC_1,RELAT_1,FUNCT_3,LATTICE6,REWRITE1,GROUP_6,WELLORD1,FUNCT_2,MCART_1,FILTER_1,XXREAL_0,ORDERS_2,CONLAT_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,MCART_1,FUNCT_1,DOMAIN_1,RELSET_1,ORDERS_2,STRUCT_0,LATTICE2,LATTICE3,LATTICE6,PARTFUN1,FUNCT_2,LATTICES,LATTICE4,CONLAT_1,CKB1,CKB7,CKB8;
definitions TARSKI,LATTICE3,VECTSP_8,LATTICE6,FUNCT_1,XBOOLE_0,SUBSET_1,CKB1,CKB7,CKB8;
theorems TARSKI,RELAT_1,FUNCT_1,ZFMISC_1,LATTICE4,LATTICES,LATTICE3,LATTICE6,MCART_1,SETFAM_1,FUNCT_2,FILTER_1,LATTICE2,ORDERS_2,CONLAT_1,XBOOLE_0,CKB1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13;
schemes FUNCT_2;
registrations SUBSET_1,FUNCT_1,FUNCT_2,STRUCT_0,LATTICES,LATTICE2,LATTICE3,CONLAT_1,RELSET_1,CKB2;
constructors SETFAM_1,DOMAIN_1,LATTICE2,LATTICE4,CONLAT_1,LATTICE6,RELSET_1,CKB1,CKB7,CKB8;
requirements SUBSET,BOOLE;
begin
theorem
Th10: (for C being FormalContext holds (for CP being  strict (FormalConcept of C) holds ( "/\" ({ ConceptStr (# O,A #) where O is (Subset of (the carrier of C)),A is (Subset of (the carrier' of C)): (ex a being (Attribute of C) st ((a in (the Intent of CP) & O = ( ( AttributeDerivation C ) . { a } )) & A = ( ( ObjectDerivation C ) . ( ( AttributeDerivation C ) . { a } ) ))) },( ConceptLattice C )) ) = CP))
proof
let C being FormalContext;
let CP being  strict (FormalConcept of C);
set D = { ConceptStr (# O,A #) where O is (Subset of (the carrier of C)),A is (Subset of (the carrier' of C)): (ex a being (Attribute of C) st ((a in (the Intent of CP) & O = ( ( AttributeDerivation C ) . { a } )) & A = ( ( ObjectDerivation C ) . ( ( AttributeDerivation C ) . { a } ) ))) };
A1: (for CP9 being (Element of ( ConceptLattice C )) holds (CP9 is_less_than D implies CP9 [= ( @ CP )))
proof
let CP9 being (Element of ( ConceptLattice C ));
assume A2: CP9 is_less_than D;
A3: (the Intent of CP) c= (the Intent of ( CP9 @ ))
proof
let x being set;
assume A4: x in (the Intent of CP);
then reconsider x as (Element of (the carrier' of C));
set Ax = ( ( ObjectDerivation C ) . ( ( AttributeDerivation C ) . { x } ) );
set Ox = ( ( AttributeDerivation C ) . { x } );
reconsider Cx = ConceptStr (# Ox,Ax #) as  strict (FormalConcept of C) by CONLAT_1:21;
Cx in { ConceptStr (# O,A #) where O is (Subset of (the carrier of C)),A is (Subset of (the carrier' of C)): (ex a being (Attribute of C) st ((a in (the Intent of CP) & O = ( ( AttributeDerivation C ) . { a } )) & A = ( ( ObjectDerivation C ) . ( ( AttributeDerivation C ) . { a } ) ))) } by A4;
then CP9 [= ( @ Cx ) by A2,LATTICE3:def 16;
then A5: ( CP9 @ ) is-SubConcept-of ( ( @ Cx ) @ ) by CONLAT_1:43;
{ x } c= Ax by CONLAT_1:6;
then A6: x in (the Intent of Cx) by ZFMISC_1:31;
Cx = ( ( @ Cx ) @ ) by CONLAT_1:def 21;
then (the Intent of Cx) c= (the Intent of ( CP9 @ )) by A5,CONLAT_1:28;
hence thesis by A6;
end;
CP = ( ( @ CP ) @ ) by CONLAT_1:def 21;
then ( CP9 @ ) is-SubConcept-of ( ( @ CP ) @ ) by A3,CONLAT_1:28;
hence thesis by CONLAT_1:43;
end;
( @ CP ) is_less_than D
proof
let q being (Element of ( ConceptLattice C ));
assume q in D;
then consider O being (Subset of (the carrier of C)),A being (Subset of (the carrier' of C)) such that A7: q = ConceptStr (# O,A #) and A8: (ex a being (Attribute of C) st ((a in (the Intent of CP) & O = ( ( AttributeDerivation C ) . { a } )) & A = ( ( ObjectDerivation C ) . ( ( AttributeDerivation C ) . { a } ) )));
consider a being (Attribute of C) such that A9: a in (the Intent of CP) and A10: O = ( ( AttributeDerivation C ) . { a } ) and A = ( ( ObjectDerivation C ) . ( ( AttributeDerivation C ) . { a } ) ) by A8;
A11: { a } c= (the Intent of CP) by A9,ZFMISC_1:31;
(( ( AttributeDerivation C ) . (the Intent of CP) ) = (the Extent of CP) & (the Extent of ( q @ )) = ( ( AttributeDerivation C ) . { a } )) by A7,A10,CONLAT_1:def 10,CONLAT_1:def 21;
then (the Extent of CP) c= (the Extent of ( q @ )) by A11,CONLAT_1:4;
then A12: CP is-SubConcept-of ( q @ ) by CONLAT_1:def 16;
CP = ( ( @ CP ) @ ) by CONLAT_1:def 21;
hence thesis by A12,CONLAT_1:43;
end;
hence thesis by A1,LATTICE3:34;
end;
