environ
vocabularies FUNCT_1,NUMBERS,SUBSET_1,SUPINF_2,XXREAL_0,ORDINAL1,RELAT_1,SUPINF_1,ORDINAL2,PROB_1,MEASURE2,MEASURE1,TARSKI,SETFAM_1,CARD_1,XBOOLE_0,ARYTM_3,NAT_1,ARYTM_1,REAL_1,XXREAL_2,ZFMISC_1,MEASURE3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,REAL_1,NAT_1,SETFAM_1,PROB_1,XXREAL_2,SUPINF_1,SUPINF_2,MEASURE1,MEASURE2,CKB3,CKB4;
definitions TARSKI,XBOOLE_0,XXREAL_3;
theorems TARSKI,FUNCT_1,FUNCT_2,ZFMISC_1,NAT_1,SETFAM_1,SUPINF_2,MEASURE1,MEASURE2,PROB_2,XBOOLE_0,XBOOLE_1,XXREAL_0,PROB_1,FINSUB_1,ORDINAL1,XXREAL_2,VALUED_0,XXREAL_3,RELAT_1,CKB1,CKB2,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13;
schemes NAT_1,FUNCT_2,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,FUNCT_2,NUMBERS,XREAL_0,MEMBERED,MEASURE1,VALUED_0,XXREAL_3,RELSET_1;
constructors PARTFUN1,REAL_1,NAT_1,PROB_2,MEASURE1,MEASURE2,SUPINF_1,RELSET_1,CKB4;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve X for set;
theorem
(for S being (SigmaField of X) holds (for M being (sigma_Measure of S) holds (for F being (Function of ( NAT ),S) holds (((for n being (Element of ( NAT )) holds ( F . ( n + 1 ) ) c= ( F . n )) & ( M . ( F . ( 0 ) ) ) < ( +infty )) implies ( M . ( meet ( rng F ) ) ) = ( inf ( rng ( M * F ) ) )))))
proof
let S being (SigmaField of X);
let M being (sigma_Measure of S);
let F being (Function of ( NAT ),S);
assume that
A1: (for n being (Element of ( NAT )) holds ( F . ( n + 1 ) ) c= ( F . n ))
and
A2: ( M . ( F . ( 0 ) ) ) < ( +infty );
consider G being (Function of ( NAT ),S) such that A3: (( G . ( 0 ) ) = ( {} ) & (for n being (Element of ( NAT )) holds ( G . ( n + 1 ) ) = ( ( F . ( 0 ) ) \ ( F . n ) ))) by MEASURE2:9;
A4: ( union ( rng G ) ) = ( ( F . ( 0 ) ) \ ( meet ( rng F ) ) ) by A1,A3,CKB6:1;
A5: ( M . ( ( F . ( 0 ) ) \ ( union ( rng G ) ) ) ) = ( M . ( meet ( rng F ) ) ) by A1,A3,CKB7:1;
A6: (for A being (Element of S) holds (A = ( union ( rng G ) ) implies ( M . ( meet ( rng F ) ) ) = ( ( M . ( F . ( 0 ) ) ) - ( M . A ) )))
proof
let A being (Element of S);
assume A7: A = ( union ( rng G ) );
( M . ( ( F . ( 0 ) ) \ ( meet ( rng F ) ) ) ) <> ( +infty ) by A2,MEASURE1:31,XBOOLE_1:36;
then ( M . A ) < ( +infty ) by A4,A7,XXREAL_0:4;
hence thesis by A4,A5,A7,MEASURE1:32,XBOOLE_1:36;
end;
(for n being (Element of ( NAT )) holds ( G . n ) c= ( G . ( n + 1 ) )) by A1,A3,MEASURE2:13;
then ( M . ( union ( rng G ) ) ) = ( sup ( rng ( M * G ) ) ) by MEASURE2:23;
then ( M . ( meet ( rng F ) ) ) = ( ( M . ( F . ( 0 ) ) ) - ( sup ( rng ( M * G ) ) ) ) by A6;
hence thesis by A1,A2,A3,CKB13:1;
end;
