environ
vocabularies FUNCT_1,NUMBERS,SUBSET_1,SUPINF_2,XXREAL_0,ORDINAL1,RELAT_1,SUPINF_1,ORDINAL2,PROB_1,MEASURE2,MEASURE1,TARSKI,SETFAM_1,CARD_1,XBOOLE_0,ARYTM_3,NAT_1,ARYTM_1,REAL_1,XXREAL_2,ZFMISC_1,MEASURE3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,REAL_1,NAT_1,SETFAM_1,PROB_1,XXREAL_2,SUPINF_1,SUPINF_2,MEASURE1,MEASURE2;
definitions TARSKI,XBOOLE_0,XXREAL_3;
theorems TARSKI,FUNCT_1,FUNCT_2,ZFMISC_1,NAT_1,SETFAM_1,SUPINF_2,MEASURE1,MEASURE2,PROB_2,XBOOLE_0,XBOOLE_1,XXREAL_0,PROB_1,FINSUB_1,ORDINAL1,XXREAL_2,VALUED_0,XXREAL_3,RELAT_1;
schemes NAT_1,FUNCT_2,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,FUNCT_2,NUMBERS,XREAL_0,MEMBERED,MEASURE1,VALUED_0,XXREAL_3,RELSET_1;
constructors PARTFUN1,REAL_1,NAT_1,PROB_2,MEASURE1,MEASURE2,SUPINF_1,RELSET_1;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th3: (for F1,F2 being (Function of ( NAT ),( ExtREAL )) holds ((for n being (Element of ( NAT )) holds ( ( Ser F1 ) . n ) <= ( ( Ser F2 ) . n )) implies ( SUM F1 ) <= ( SUM F2 )))
proof
let F1 being (Function of ( NAT ),( ExtREAL ));
let F2 being (Function of ( NAT ),( ExtREAL ));
assume A1: (for n being (Element of ( NAT )) holds ( ( Ser F1 ) . n ) <= ( ( Ser F2 ) . n ));
A2: (for x being  ext-real number holds (x in ( rng ( Ser F1 ) ) implies (ex y being  ext-real number st (y in ( rng ( Ser F2 ) ) & x <= y))))
proof
let x being  ext-real number;
A3: ( dom ( Ser F1 ) ) = ( NAT ) by FUNCT_2:def 1;
assume x in ( rng ( Ser F1 ) );
then consider n being set such that A4: n in ( NAT ) and A5: x = ( ( Ser F1 ) . n ) by A3,FUNCT_1:def 3;
reconsider n as (Element of ( NAT )) by A4;
reconsider y = ( ( Ser F2 ) . n ) as R_eal;
take y;
( dom ( Ser F2 ) ) = ( NAT ) by FUNCT_2:def 1;
hence thesis by A1,A5,FUNCT_1:def 3;
end;
(( SUM F1 ) = ( sup ( rng ( Ser F1 ) ) ) & ( SUM F2 ) = ( sup ( rng ( Ser F2 ) ) )) by SUPINF_2:def 17;
hence thesis by A2,XXREAL_2:63;
end;
