environ
vocabularies NUMBERS,XBOOLE_0,MESFUNC8,SEQFUNC,MESFUNC5,SUBSET_1,SUPINF_1,NAT_1,FUNCT_1,XXREAL_0,ORDINAL2,RELAT_1,ORDINAL1,XXREAL_2,RINFSUP1,ARYTM_3,PBOOLE,PARTFUN1,PROB_1,MEASURE1,CARD_1,SUPINF_2,MESFUNC1,VALUED_0,SEQ_2,ARYTM_1,TARSKI,REAL_1,INTEGRA5,VALUED_1,COMPLEX1,MEASURE6,RFUNCT_3,XREAL_0,MESFUNC2,MESFUN10;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,REAL_1,XXREAL_0,XXREAL_2,RELAT_1,FUNCT_1,RELSET_1,DOMAIN_1,NAT_1,VALUED_0,FUNCT_2,PARTFUN1,PROB_1,SUPINF_1,SUPINF_2,MEASURE1,EXTREAL1,MESFUNC1,MEASURE6,MESFUNC2,SEQFUNC,MESFUNC5,MESFUNC8,RINFSUP2;
definitions MESFUNC1,MEASURE6,RINFSUP2,XXREAL_3,MEMBER_1;
theorems TARSKI,PARTFUN1,FUNCT_1,SUPINF_2,EXTREAL1,EXTREAL2,MESFUNC1,XREAL_0,XBOOLE_0,XBOOLE_1,MESFUNC2,XREAL_1,XXREAL_0,MESFUNC5,NAT_1,RELAT_1,FUNCT_2,SEQFUNC,ORDINAL1,MESFUNC8,RINFSUP2,MESFUNC7,MESFUNC9,NUMBERS,XXREAL_2,XXREAL_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
schemes FUNCT_2,SEQFUNC,FUNCT_1;
registrations NAT_1,XREAL_0,MEMBERED,ORDINAL1,PARTFUN1,RELAT_1,XBOOLE_0,SUPINF_2,NUMBERS,XXREAL_0,MESFUNC8,RINFSUP2,VALUED_0,MEMBER_1,RELSET_1,FUNCT_2;
constructors REAL_1,DOMAIN_1,EXTREAL1,MESFUNC1,MEASURE6,MESFUNC2,MESFUNC5,RINFSUP2,EXTREAL2,MESFUNC9,SUPINF_1,MESFUNC8,SEQFUNC,RELSET_1,BINOP_2;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve X for non empty set;
reserve F for  with_the_same_dom (Functional_Sequence of X,( ExtREAL ));
reserve n for Nat;
reserve S for (SigmaField of X);
reserve M for (sigma_Measure of S);
reserve E for (Element of S);
theorem
Th7: ((E = ( dom ( F . ( 0 ) ) ) & (for n holds (( F . n ) is  nonnegative & ( F . n ) is_measurable_on E))) implies (ex I being ExtREAL_sequence st ((for n holds ( I . n ) = ( Integral (M,( F . n )) )) & ( Integral (M,( lim_inf F )) ) <= ( lim_inf I ))))
proof
assume that
A1: E = ( dom ( F . ( 0 ) ) )
and
A2: (for n holds (( F . n ) is  nonnegative & ( F . n ) is_measurable_on E));
set H = ( inferior_realsequence F );
deffunc G((Element of ( NAT ))) = ( inf ( F ^\ $1 ) );
consider G being Function such that A3: (( dom G ) = ( NAT ) & (for n being (Element of ( NAT )) holds ( G . n ) = G(n))) from FUNCT_1:sch 4;
now
let n being (Element of ( NAT ));
( G . n ) = ( inf ( F ^\ n ) ) by A3;
hence ( G . n ) is (PartFunc of X,( ExtREAL ));
end;
then reconsider G as (Functional_Sequence of X,( ExtREAL )) by A3,SEQFUNC:1;
A4: (for n being (Element of ( NAT )) holds ( G . n ) = ( ( inferior_realsequence F ) . n ))
proof
let n being (Element of ( NAT ));
( ( inferior_realsequence F ) . n ) = ( inf ( F ^\ n ) ) by MESFUNC8:8;
hence thesis by A3;
end;
then A5: G = ( inferior_realsequence F ) by FUNCT_2:63;
reconsider G as  with_the_same_dom (Functional_Sequence of X,( ExtREAL )) by A4,FUNCT_2:63;
A6: ( dom ( H . ( 0 ) ) ) = ( dom ( G . ( 0 ) ) ) by A4;
A7: (for n,m being Nat holds (for x being (Element of X) holds ((n <= m & x in E) implies (( ( G . n ) . x ) <= ( ( G . m ) . x ) & ( ( G # x ) . n ) <= ( ( G # x ) . m )))))
proof
let n being Nat,m being Nat;
let x being (Element of X);
reconsider n1 = n,m1 = m as (Element of ( NAT )) by ORDINAL1:def 12;
assume that
A8: n <= m
and
A9: x in E;
( H # x ) = ( inferior_realsequence ( F # x ) ) by A1,A9,MESFUNC8:7;
then ( ( H # x ) . n1 ) <= ( ( H # x ) . m1 ) by A8,RINFSUP2:7;
then ( ( H . n ) . x ) <= ( ( H # x ) . m ) by MESFUNC5:def 13;
hence ( ( G . n ) . x ) <= ( ( G . m ) . x ) by A5,MESFUNC5:def 13;
then ( ( G # x ) . n ) <= ( ( G . m ) . x ) by MESFUNC5:def 13;
hence thesis by MESFUNC5:def 13;
end;
A10:now
let x being (Element of X);
assume x in E;
then (for n,m being (Element of ( NAT )) holds (m <= n implies ( ( G # x ) . m ) <= ( ( G # x ) . n ))) by A7;
then ( G # x ) is  non-decreasing by RINFSUP2:7;
hence ( G # x ) is  convergent by RINFSUP2:37;
end;
deffunc I((Element of ( NAT ))) = ( Integral (M,( F . $1 )) );
consider I being (Function of ( NAT ),( ExtREAL )) such that A11: (for n being (Element of ( NAT )) holds ( I . n ) = I(n)) from FUNCT_2:sch 4;
A12: (for n being Nat holds ( G . n ) is_measurable_on E) by A1,A2,A5,MESFUNC8:20;
A13: ( dom ( H . ( 0 ) ) ) = ( dom ( F . ( 0 ) ) ) by MESFUNC8:def 5;
then A14: ( dom ( lim G ) ) = E by A1,A6,MESFUNC8:def 9;
(for x being set holds (x in ( dom ( G . ( 0 ) ) ) implies ( 0 ) <= ( ( G . ( 0 ) ) . x )))
proof
let x being set;
assume A15: x in ( dom ( G . ( 0 ) ) );
then reconsider x as (Element of X);
A16:now
let n being Nat;
( F . n ) is  nonnegative by A2;
then ( 0 ) <= ( ( F . n ) . x ) by SUPINF_2:51;
then ( 0 ) <= ( ( F # x ) . ( ( 0 ) + n ) ) by MESFUNC5:def 13;
hence ( 0. ) <= ( ( ( F # x ) ^\ ( 0 ) ) . n ) by NAT_1:def 3;
end;
( ( F ^\ ( 0 ) ) . ( 0 ) ) = ( F . ( ( 0 ) + ( 0 ) ) ) by NAT_1:def 3;
then ( dom ( inf ( F ^\ ( 0 ) ) ) ) = ( dom ( F . ( 0 ) ) ) by MESFUNC8:def 3;
then ( ( inf ( F ^\ ( 0 ) ) ) . x ) = ( inf ( ( F # x ) ^\ ( 0 ) ) ) by A13,A6,A15,CKB6:1;
then ( ( G . ( 0 ) ) . x ) = ( inf ( ( F # x ) ^\ ( 0 ) ) ) by A3;
hence thesis by A16,CKB4:1;
end;
then A17: ( G . ( 0 ) ) is  nonnegative by SUPINF_2:52;
(for n,m being Nat holds (n <= m implies (for x being (Element of X) holds (x in E implies ( ( G . n ) . x ) <= ( ( G . m ) . x ))))) by A7;
then consider J being ExtREAL_sequence such that A18: (for n being Nat holds ( J . n ) = ( Integral (M,( G . n )) )) and A19: J is  convergent and A20: ( Integral (M,( lim G )) ) = ( lim J ) by A1,A13,A6,A17,A12,A10,MESFUNC9:52;
reconsider I as ExtREAL_sequence;
(for n being Nat holds ( J . n ) <= ( I . n ))
proof
let n being Nat;
A21: ( dom ( F . n ) ) = E by A1,MESFUNC8:def 2;
A22: ( F . n ) is  nonnegative by A2;
A23: n is (Element of ( NAT )) by ORDINAL1:def 12;
A24:now
let x being (Element of X);
assume A25: x in ( dom ( G . n ) );
( ( inferior_realsequence ( F # x ) ) . n ) <= ( ( F # x ) . n ) by A23,RINFSUP2:8;
then ( ( H . n ) . x ) <= ( ( F # x ) . n ) by A5,A25,MESFUNC8:def 5;
then ( ( H . n ) . x ) <= ( ( F . n ) . x ) by MESFUNC5:def 13;
hence ( ( G . n ) . x ) <= ( ( F . n ) . x ) by A4,A23;
end;
A26: ( F . n ) is_measurable_on E by A2;
A27: ( G . n ) is_measurable_on E by A1,A2,A5,MESFUNC8:20;
A28: ( dom ( G . n ) ) = E by A1,A13,A6,MESFUNC8:def 2;
A29:now
let x being set;
assume A30: x in ( dom ( G . n ) );
( 0 ) <= ( ( G . ( 0 ) ) . x ) by A17,SUPINF_2:51;
hence ( 0 ) <= ( ( G . n ) . x ) by A7,A28,A30;
end;
then ( G . n ) is  nonnegative by SUPINF_2:52;
then ( integral+ (M,( G . n )) ) <= ( integral+ (M,( F . n )) ) by A21,A28,A26,A27,A22,A24,MESFUNC5:85;
then ( Integral (M,( G . n )) ) <= ( integral+ (M,( F . n )) ) by A28,A27,A29,MESFUNC5:88,SUPINF_2:52;
then A31: ( Integral (M,( G . n )) ) <= ( Integral (M,( F . n )) ) by A21,A26,A22,MESFUNC5:88;
( I . n ) = ( Integral (M,( F . n )) ) by A11,A23;
hence thesis by A18,A31;
end;
then ( lim_inf J ) <= ( lim_inf I ) by CKB3:1;
then A32: ( lim J ) <= ( lim_inf I ) by A19,RINFSUP2:41;
A33: ( dom ( sup G ) ) = E by A1,A13,A6,MESFUNC8:def 4;
now
let x being (Element of X);
assume A34: x in ( dom ( lim G ) );
then (for n,m being (Element of ( NAT )) holds (m <= n implies ( ( G # x ) . m ) <= ( ( G # x ) . n ))) by A7,A14;
then ( G # x ) is  non-decreasing by RINFSUP2:7;
then A35: ( lim ( G # x ) ) = ( sup ( G # x ) ) by RINFSUP2:37;
( ( sup G ) . x ) = ( sup ( G # x ) ) by A14,A33,A34,MESFUNC8:def 4;
hence ( ( lim G ) . x ) = ( ( sup G ) . x ) by A34,A35,MESFUNC8:def 9;
end;
then A36: ( lim G ) = ( sup G ) by A14,A33,PARTFUN1:5;
take I;
(for n being Nat holds ( I . n ) = ( Integral (M,( F . n )) ))
proof
let n being Nat;
n is (Element of ( NAT )) by ORDINAL1:def 12;
hence thesis by A11;
end;
hence thesis by A5,A20,A36,A32,MESFUNC8:11;
end;
