environ
vocabularies STRUCT_0,XBOOLE_0,MSUALG_1,FUNCT_1,RELAT_1,PBOOLE,FUNCOP_1,EQREL_1,SUBSET_1,NAT_1,MARGREL1,PARTFUN1,FINSEQ_1,TARSKI,CARD_3,MSUALG_3,WELLORD1,MSUALG_4;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,EQREL_1,STRUCT_0,NAT_1,FUNCT_2,FINSEQ_1,FINSEQ_2,CARD_3,PBOOLE,FUNCOP_1,MSUALG_1,MSUALG_3,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17,CKB20,CKB21;
definitions TARSKI,MSUALG_3,XBOOLE_0,FUNCOP_1,CKB2,CKB5,CKB8,CKB11,CKB15,CKB16,CKB20,CKB21;
theorems FUNCT_1,FUNCT_2,PBOOLE,CARD_3,MSUALG_1,ZFMISC_1,RELAT_1,RELSET_1,EQREL_1,MSUALG_3,MSAFREE,TARSKI,XBOOLE_0,FUNCOP_1,ORDINAL1,PARTFUN1,FINSEQ_2,CKB2,CKB5,CKB8,CKB10,CKB11,CKB15,CKB16,CKB20,CKB21;
schemes FUNCT_1,CLASSES1,EQREL_1;
registrations RELAT_1,FUNCT_1,PARTFUN1,FUNCOP_1,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_3,CARD_3,RELSET_1,FINSEQ_2,FINSEQ_1,CKB1,CKB3,CKB9,CKB12,CKB18,CKB19;
constructors EQREL_1,PRALG_2,MSUALG_3,RELSET_1,CKB2,CKB5,CKB6,CKB8,CKB11,CKB14,CKB15,CKB16,CKB17,CKB20,CKB21;
requirements SUBSET,BOOLE;
begin
reserve S for non void non empty ManySortedSign;
reserve o for (OperSymbol of S);
definition
let S;
let o;
let A being  non-empty MSAlgebra over S;
let R being (MSCongruence of A);
func QuotArgs (R,o) -> (Function of ( ( ( (the Sorts of A) # ) * (the Arity of S) ) . o ),( ( ( ( Class R ) # ) * (the Arity of S) ) . o ))
means
(for x being (Element of ( Args (o,A) )) holds ( it . x ) = ( R # x ));
existence
proof
set ao = ( the_arity_of o );
set D = ( Args (o,A) );
deffunc F((Element of D)) = ( R # $1 );
consider f being Function such that A8: (( dom f ) = D & (for d being (Element of D) holds ( f . d ) = F(d))) from FUNCT_1:sch 4;
A9: o in (the carrier' of S);
then o in ( dom ( ( (the Sorts of A) # ) * (the Arity of S) ) ) by PARTFUN1:def 2;
then A10: ( ( ( (the Sorts of A) # ) * (the Arity of S) ) . o ) = ( ( (the Sorts of A) # ) . ( (the Arity of S) . o ) ) by FUNCT_1:12
.= ( ( (the Sorts of A) # ) . ( the_arity_of o ) ) by MSUALG_1:def 1;
A11: (for x being set holds (x in ( ( (the Sorts of A) # ) . ao ) implies ( f . x ) in ( ( ( Class R ) # ) . ao )))
proof
let x being set;
assume x in ( ( (the Sorts of A) # ) . ao );
then reconsider x1 = x as (Element of D) by A10,MSUALG_1:def 4;
(( f . x1 ) = ( R # x1 ) & ( ( ( Class R ) # ) . ao ) = ( product ( ( Class R ) * ao ) )) by A8,FINSEQ_2:def 5;
hence thesis;
end;
o in ( dom ( ( ( Class R ) # ) * (the Arity of S) ) ) by A9,PARTFUN1:def 2;
then ( ( ( ( Class R ) # ) * (the Arity of S) ) . o ) = ( ( ( Class R ) # ) . ( (the Arity of S) . o ) ) by FUNCT_1:12
.= ( ( ( Class R ) # ) . ao ) by MSUALG_1:def 1;
then reconsider f as (Function of ( ( ( (the Sorts of A) # ) * (the Arity of S) ) . o ),( ( ( ( Class R ) # ) * (the Arity of S) ) . o )) by A8,A10,A11,FUNCT_2:3,MSUALG_1:def 4;
take f;
thus thesis by A8;
end;
uniqueness
proof
set ao = ( the_arity_of o );
let f being (Function of ( ( ( (the Sorts of A) # ) * (the Arity of S) ) . o ),( ( ( ( Class R ) # ) * (the Arity of S) ) . o )),g being (Function of ( ( ( (the Sorts of A) # ) * (the Arity of S) ) . o ),( ( ( ( Class R ) # ) * (the Arity of S) ) . o ));
assume that
A12: (for x being (Element of ( Args (o,A) )) holds ( f . x ) = ( R # x ))
and
A13: (for x being (Element of ( Args (o,A) )) holds ( g . x ) = ( R # x ));
o in (the carrier' of S);
then o in ( dom ( ( (the Sorts of A) # ) * (the Arity of S) ) ) by PARTFUN1:def 2;
then A14: ( ( ( (the Sorts of A) # ) * (the Arity of S) ) . o ) = ( ( (the Sorts of A) # ) . ( (the Arity of S) . o ) ) by FUNCT_1:12
.= ( ( (the Sorts of A) # ) . ( the_arity_of o ) ) by MSUALG_1:def 1;
A15:now
let x being set;
assume x in ( ( (the Sorts of A) # ) . ao );
then reconsider x1 = x as (Element of ( Args (o,A) )) by A14,MSUALG_1:def 4;
( f . x1 ) = ( R # x1 ) by A12;
hence ( f . x ) = ( g . x ) by A13;
end;
(( dom f ) = ( ( (the Sorts of A) # ) . ao ) & ( dom g ) = ( ( (the Sorts of A) # ) . ao )) by A14,FUNCT_2:def 1;
hence thesis by A15,FUNCT_1:2;
end;
end;
