environ
vocabularies XBOOLE_0,PRE_TOPC,SUBSET_1,TOPS_1,TARSKI,RCOMP_1,RELAT_1,CONNSP_1,RELAT_2,SETFAM_1,CONNSP_2;
notations TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,DOMAIN_1,STRUCT_0,PRE_TOPC,TOPS_1,CONNSP_1,CKB1,CKB2,CKB16,CKB17,CKB18,CKB19;
definitions COMPTS_1,SUBSET_1,STRUCT_0,CKB1,CKB2,CKB16,CKB17,CKB18,CKB19;
theorems TARSKI,ZFMISC_1,SETFAM_1,PRE_TOPC,TOPS_1,CONNSP_1,COMPTS_1,XBOOLE_0,XBOOLE_1,SUBSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20;
schemes SUBSET_1;
registrations XBOOLE_0,SUBSET_1,STRUCT_0,PRE_TOPC,TOPS_1,CONNSP_1;
constructors SETFAM_1,DOMAIN_1,TOPS_1,CONNSP_1,COMPTS_1,CKB1,CKB2,CKB16,CKB17,CKB18,CKB19;
requirements SUBSET,BOOLE;
begin
reserve X for non empty TopSpace;
reserve x for (Point of X);
theorem
Th20: (for x holds (X is_locally_connected_in x iff (for U1 being non empty (Subset of X) holds ((U1 is  open & x in U1) implies (ex x1 being (Point of ( X | U1 )) st (x1 = x & x in ( Int ( Component_of x1 ) )))))))
proof
let x;
A1: (X is_locally_connected_in x implies (for U1 being non empty (Subset of X) holds ((U1 is  open & x in U1) implies (ex x1 being (Point of ( X | U1 )) st (x1 = x & x in ( Int ( Component_of x1 ) ))))))
proof
assume A2: X is_locally_connected_in x;
let U1 being non empty (Subset of X);
assume that
A3: U1 is  open
and
A4: x in U1;
x in ( [#] ( X | U1 ) ) by A4,PRE_TOPC:def 5;
then reconsider x1 = x as (Point of ( X | U1 ));
reconsider S1 = ( Component_of x1 ) as (Subset of ( X | U1 ));
take x1;
reconsider S = S1 as (Subset of X) by PRE_TOPC:11;
A5: x in S by CONNSP_1:38;
S1 is  a_component by CONNSP_1:40;
then A6: S is_a_component_of U1 by CONNSP_1:def 6;
U1 is (a_neighborhood of x) by A3,A4,CKB5:1;
then S is (a_neighborhood of x) by A2,A6,A5,CKB20:1;
then S1 is (a_neighborhood of x1) by CKB13:1;
hence thesis by CKB1:def 1;
end;
((for U1 being non empty (Subset of X) holds ((U1 is  open & x in U1) implies (ex x1 being (Point of ( X | U1 )) st (x1 = x & x in ( Int ( Component_of x1 ) ))))) implies X is_locally_connected_in x)
proof
assume A7: (for U1 being non empty (Subset of X) holds ((U1 is  open & x in U1) implies (ex x1 being (Point of ( X | U1 )) st (x1 = x & x in ( Int ( Component_of x1 ) )))));
(for U1 being (Subset of X) holds (U1 is (a_neighborhood of x) implies (ex V1 being (Subset of X) st ((V1 is (a_neighborhood of x) & V1 is  connected) & V1 c= U1))))
proof
let U1 being (Subset of X);
assume U1 is (a_neighborhood of x);
then consider V being non empty (Subset of X) such that A8: V is (a_neighborhood of x) and A9: V is  open and A10: V c= U1 by CKB7:1;
consider x1 being (Point of ( X | V )) such that A11: x1 = x and A12: x in ( Int ( Component_of x1 ) ) by A7,A8,A9,CKB6:1;
set S1 = ( Component_of x1 );
reconsider S = S1 as (Subset of X) by PRE_TOPC:11;
take S;
S1 c= ( [#] ( X | V ) );
then A13: (S1 is  connected & S c= V) by PRE_TOPC:def 5;
S1 is (a_neighborhood of x1) by A11,A12,CKB1:def 1;
hence thesis by A9,A10,A11,A13,CKB11:1,CONNSP_1:23,XBOOLE_1:1;
end;
hence thesis by CKB16:def 1;
end;
hence thesis by A1;
end;
