environ
vocabularies NUMBERS,ORDINAL1,SUBSET_1,XXREAL_0,ARYTM_3,XBOOLE_0,TARSKI,FINSET_1,CARD_1,MCART_1,ZFMISC_1,CQC_LANG,QC_LANG1,XBOOLEAN,BVFUNC_2,FUNCT_1,FINSEQ_1,NAT_1,RELAT_1,ORDINAL4,ARYTM_1,CQC_THE1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,XCMPLX_0,FUNCT_1,NUMBERS,NAT_1,FINSET_1,FINSEQ_1,MCART_1,QC_LANG1,CQC_LANG,XXREAL_0,CKB5,CKB7;
definitions TARSKI,XBOOLE_0,CKB5,CKB7;
theorems TARSKI,ZFMISC_1,FINSET_1,FINSEQ_1,MCART_1,FUNCT_1,NAT_1,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,ORDINAL1,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19;
schemes NAT_1,FRAENKEL,XBOOLE_0;
registrations SUBSET_1,RELSET_1,FINSET_1,XXREAL_0,XREAL_0,FINSEQ_1,CQC_LANG,ORDINAL1,CARD_1;
constructors XXREAL_0,XREAL_0,NAT_1,CQC_LANG,CKB5,CKB7;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve a for set;
reserve T for (Subset of ( CQC-WFF ));
reserve X for (Subset of ( CQC-WFF ));
reserve Y for (Subset of ( CQC-WFF ));
theorem
Th39: (X c= Y implies ( Cn X ) c= ( Cn Y ))
proof
assume A1: X c= Y;
thus ( Cn X ) c= ( Cn Y )
proof
let a;
assume A2: a in ( Cn X );
then reconsider t = a as (Element of ( CQC-WFF ));
(for T holds ((T is  being_a_theory & Y c= T) implies t in T))
proof
let T;
assume that
A3: T is  being_a_theory
and
A4: Y c= T;
X c= T by A1,A4,XBOOLE_1:1;
hence thesis by A2,A3,CKB7:def 1;
end;
hence thesis by CKB7:def 1;
end;

end;
