environ
vocabularies LATTICE2,FILTER_0,LATTICES,PRE_TOPC,SUBSET_1,XBOOLE_0,TOPS_1,TARSKI,RCOMP_1,SETFAM_1,BINOP_1,FUNCT_1,EQREL_1,STRUCT_0,PBOOLE,CARD_FIL,INT_2,RELAT_1,ZFMISC_1,ORDINAL1,GROUP_6,FUNCT_2,WELLORD1,XBOOLEAN,LATTICE4,OPENLATT;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,RELAT_1,FUNCT_1,FUNCT_2,BINOP_1,SETFAM_1,DOMAIN_1,STRUCT_0,PRE_TOPC,TOPS_1,LATTICES,LATTICE2,FILTER_0,LATTICE4,CKB5,CKB7,CKB8,CKB9,CKB10,CKB12;
definitions TARSKI,PRE_TOPC,FILTER_0,LATTICES,LATTICE4,FUNCT_1,STRUCT_0,XBOOLE_0,SUBSET_1,FUNCT_2,CKB5,CKB9,CKB10,CKB12;
theorems PRE_TOPC,LATTICES,TOPS_1,ZFMISC_1,FILTER_0,SETFAM_1,TARSKI,FUNCT_1,FUNCT_2,LATTICE4,RELAT_1,ORDINAL1,XBOOLE_0,XBOOLE_1,STRUCT_0,EQREL_1,CKB3,CKB4,CKB5,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16;
schemes BINOP_1,DOMAIN_1,FUNCT_1,BINOP_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,LATTICES,PRE_TOPC,FILTER_0,LATTICE2,TOPS_1,CKB1,CKB2,CKB6;
constructors SETFAM_1,BINOP_1,DOMAIN_1,NAT_D,TOPS_1,LATTICE2,FILTER_1,LATTICE4,RELSET_1,FILTER_0,CKB5,CKB7,CKB8,CKB9,CKB10,CKB12;
requirements BOOLE,SUBSET;
begin
reserve T for non empty TopSpace;
registration
let T;
cluster ( Open_setLatt T ) ->  implicative;
coherence
proof
set OL = ( Open_setLatt T );
let p being (Element of OL),q being (Element of OL);
reconsider p9 = p,q9 = q as (Element of ( Topology_of T ));
reconsider r9 = ( Int ( ( p9 ` ) \/ q9 ) ) as (Element of ( Topology_of T )) by PRE_TOPC:def 2;
reconsider r = r9 as (Element of OL);
take r;
A1: ( p "/\" r ) = ( p9 /\ r9 ) by CKB10:def 1;
( p9 /\ r ) c= q9 by CKB3:1;
hence ( p "/\" r ) [= q by A1,CKB16:1;
let r1 being (Element of OL);
reconsider r2 = r1 as (Element of ( Topology_of T ));
reconsider r19 = r2 as (Subset of T);
A2: r19 is  open by PRE_TOPC:def 2;
assume A3: ( p "/\" r1 ) [= q;
( p "/\" r1 ) = ( p9 /\ r19 ) by CKB10:def 1;
then ( p9 /\ r2 ) c= q9 by A3,CKB16:1;
then r19 c= r9 by A2,CKB4:1;
hence r1 [= r by CKB16:1;
end;
end;
