environ
vocabularies LATTICE2,FILTER_0,LATTICES,PRE_TOPC,SUBSET_1,XBOOLE_0,TOPS_1,TARSKI,RCOMP_1,SETFAM_1,BINOP_1,FUNCT_1,EQREL_1,STRUCT_0,PBOOLE,CARD_FIL,INT_2,RELAT_1,ZFMISC_1,ORDINAL1,GROUP_6,FUNCT_2,WELLORD1,XBOOLEAN,LATTICE4,OPENLATT;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,RELAT_1,FUNCT_1,FUNCT_2,BINOP_1,SETFAM_1,DOMAIN_1,STRUCT_0,PRE_TOPC,TOPS_1,LATTICES,LATTICE2,FILTER_0,LATTICE4,CKB5,CKB7,CKB8;
definitions TARSKI,PRE_TOPC,FILTER_0,LATTICES,LATTICE4,FUNCT_1,STRUCT_0,XBOOLE_0,SUBSET_1,FUNCT_2,CKB5;
theorems PRE_TOPC,LATTICES,TOPS_1,ZFMISC_1,FILTER_0,SETFAM_1,TARSKI,FUNCT_1,FUNCT_2,LATTICE4,RELAT_1,ORDINAL1,XBOOLE_0,XBOOLE_1,STRUCT_0,EQREL_1,CKB3,CKB4,CKB5;
schemes BINOP_1,DOMAIN_1,FUNCT_1,BINOP_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,LATTICES,PRE_TOPC,FILTER_0,LATTICE2,TOPS_1,CKB1,CKB2,CKB6;
constructors SETFAM_1,BINOP_1,DOMAIN_1,NAT_D,TOPS_1,LATTICE2,FILTER_1,LATTICE4,RELSET_1,FILTER_0,CKB5,CKB7,CKB8;
requirements BOOLE,SUBSET;
begin
reserve T for non empty TopSpace;
reserve P for (Element of ( Topology_of T ));
reserve Q for (Element of ( Topology_of T ));
definition
let T;
func Top_Union T -> (BinOp of ( Topology_of T ))
means
:Def2: ( it . (P,Q) ) = ( P \/ Q );
existence
proof
deffunc F((Element of ( Topology_of T )),(Element of ( Topology_of T ))) = ( $1 \/ $2 );
thus (ex F being (BinOp of ( Topology_of T )) st (for P,Q being (Element of ( Topology_of T )) holds ( F . (P,Q) ) = F(P,Q))) from BINOP_1:sch 4;
end;
uniqueness
proof
set A = ( Topology_of T );
deffunc O((Element of A),(Element of A)) = ( $1 \/ $2 );
thus (for o1,o2 being (BinOp of A) holds (((for a,b being (Element of A) holds ( o1 . (a,b) ) = O(a,b)) & (for a,b being (Element of A) holds ( o2 . (a,b) ) = O(a,b))) implies o1 = o2)) from BINOP_2:sch 2;
end;
end;
