environ
vocabularies ORDINAL6,CARD_1,RELAT_1,FUNCT_1,CLASSES2,NUMBERS,TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,ORDINAL2,WELLORD1,WELLORD2,ABIAN,CARD_3,MATROID0,ORDINAL4,NAT_1,ARYTM_3,CLASSES1,VALUED_0,AFINSQ_1,ORDINAL5,ZFMISC_1,FINSET_1,MESFUNC8,NAGATA_1,ORDINAL3,PRE_TOPC,AOFA_000;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,FINSET_1,ORDINAL1,ORDINAL2,NAT_1,ORDINAL3,ABIAN,WELLORD1,WELLORD2,CARD_1,ORDINAL4,CARD_3,NAGATA_1,AFINSQ_1,CLASSES1,CLASSES2,NUMBERS,MATROID0,ORDINAL5,AOFA_000,CKB1,CKB25,CKB26,CKB32,CKB33,CKB41,CKB55,CKB72,CKB74,CKB83,CKB84,CKB89,CKB91,CKB100;
definitions TARSKI,XBOOLE_0,FUNCT_1,WELLORD1,ABIAN,ORDINAL1,ORDINAL2,ORDINAL4,CARD_3,ORDINAL5,CKB1,CKB25,CKB26,CKB32,CKB33,CKB41,CKB55,CKB84,CKB89,CKB91,CKB100;
theorems XBOOLE_1,ZFMISC_1,RELAT_1,FUNCT_1,ORDINAL1,ORDINAL2,ORDINAL3,FUNCT_3,WELLORD1,WELLORD2,ORDERS_1,CARD_2,CARD_5,FUNCT_2,ORDINAL4,XBOOLE_0,TARSKI,ORDINAL5,NAT_1,CLASSES1,CLASSES2,CARD_1,AFINSQ_1,NAT_2,GRFUNC_1,ABIAN,CKB1,CKB4,CKB7,CKB8,CKB9,CKB10,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB25,CKB26,CKB31,CKB32,CKB33,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB70,CKB75,CKB76,CKB78,CKB80,CKB81,CKB82,CKB84,CKB89,CKB91,CKB100,CKB101,CKB102,CKB103,CKB104,CKB105,CKB106,CKB107,CKB108,CKB109;
schemes NAT_1,ORDINAL1,ORDINAL2,ORDINAL4,TREES_2,CKB77,CKB79;
registrations XBOOLE_0,RELAT_1,RELSET_1,FUNCT_1,FINSET_1,FUNCT_2,ORDINAL1,ORDINAL2,CARD_1,WELLORD2,ORDINAL3,CLASSES2,CARD_5,ORDINAL4,CARD_LAR,ORDINAL5,CLASSES1,AFINSQ_1,SUBSET_1,CKB2,CKB3,CKB5,CKB6,CKB11,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB27,CKB28,CKB29,CKB30,CKB34,CKB35,CKB36,CKB48,CKB49,CKB50,CKB59,CKB69,CKB71,CKB73,CKB85,CKB86,CKB87,CKB88,CKB90,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99;
constructors WELLORD1,WELLORD2,CLASSES1,ABIAN,CARD_3,AFINSQ_1,ORDINAL3,ORDINAL5,NAT_1,RELSET_1,CKB1,CKB25,CKB32,CKB41,CKB55,CKB74,CKB83,CKB84,CKB89,CKB91,CKB100;
requirements SUBSET,BOOLE,NUMERALS;
begin
reserve a for  ordinal number;
reserve x for set;
reserve y for set;
reserve z for set;
reserve f for Ordinal-Sequence;
theorem
ThAC: (for g1,g2 being  Ordinal-Sequence-valued T-Sequence holds (((( dom g1 ) = ( dom g2 ) & ( dom g1 ) <> ( {} )) & (for a holds (a in ( dom g1 ) implies ( g1 . a ) c= ( g2 . a )))) implies ( criticals g1 ) c= ( criticals g2 )))
proof
let g1 being  Ordinal-Sequence-valued T-Sequence,g2 being  Ordinal-Sequence-valued T-Sequence;
assume Z0: ( dom g1 ) = ( dom g2 );
assume Z1: ( dom g1 ) <> ( {} );
assume Z2: (for a holds (a in ( dom g1 ) implies ( g1 . a ) c= ( g2 . a )));
set f1 = ( g1 . ( 0 ) );
set f2 = ( g2 . ( 0 ) );
( 0 ) in ( dom g1 ) by Z1,ORDINAL3:8;
then ((f1 c= f2 & f1 in ( rng g1 )) & f2 in ( rng g2 )) by Z0,Z2,FUNCT_1:def 3;
then Z4: ( dom f1 ) c= ( dom f2 ) by GRFUNC_1:2;
set X = { a where a is (Element of ( dom f1 )): (a in ( dom f1 ) & (for f holds (f in ( rng g1 ) implies a is_a_fixpoint_of f))) };
set Z = { a where a is (Element of ( dom f2 )): (a in ( dom f2 ) & (for f holds (f in ( rng g2 ) implies a is_a_fixpoint_of f))) };
reconsider X,Z as  ordinal-membered set by CKB101:1;
set Y = ( Z \ X );
A1:now
let x;
let y;
assume x in X;
then consider a being (Element of ( dom f1 )) such that B1: ((x = a & a in ( dom f1 )) & (for f holds (f in ( rng g1 ) implies a is_a_fixpoint_of f)));
assume y in Y;
then B2: (y in Z & (not y in X)) by XBOOLE_0:def 5;
then consider b being (Element of ( dom f2 )) such that B3: ((y = b & b in ( dom f2 )) & (for f holds (f in ( rng g2 ) implies b is_a_fixpoint_of f)));
assume (not x in y);
then B4: b c= a by B1,B3,ORDINAL1:16;
then B5: b in ( dom f1 ) by B1,ORDINAL1:12;
now
let f;
assume B7: f in ( rng g1 );
then consider z such that B6: (z in ( dom g1 ) & f = ( g1 . z )) by FUNCT_1:def 3;
B8: f c= ( g2 . z ) by Z2,B6;
( g2 . z ) in ( rng g2 ) by Z0,B6,FUNCT_1:def 3;
then BB: b is_a_fixpoint_of ( g2 . z ) by B3;
a is_a_fixpoint_of f by B1,B7;
then a in ( dom f ) by ABIAN:def 3;
then B9: b in ( dom f ) by B4,ORDINAL1:12;
then ( f . b ) = ( ( g2 . z ) . b ) by B8,GRFUNC_1:2
.= b by BB,ABIAN:def 3;
hence b is_a_fixpoint_of f by B9,ABIAN:def 3;
end;
hence contradiction by B2,B3,B5;
end;
X c= Z
proof
let x;
assume x in X;
then consider a being (Element of ( dom f1 )) such that B1: ((x = a & a in ( dom f1 )) & (for f holds (f in ( rng g1 ) implies a is_a_fixpoint_of f)));
now
let f;
assume f in ( rng g2 );
then consider z such that B4: (z in ( dom g2 ) & f = ( g2 . z )) by FUNCT_1:def 3;
B5: ( g1 . z ) c= f by Z0,Z2,B4;
then B6: ( dom ( g1 . z ) ) c= ( dom f ) by GRFUNC_1:2;
( g1 . z ) in ( rng g1 ) by Z0,B4,FUNCT_1:def 3;
then a is_a_fixpoint_of ( g1 . z ) by B1;
then (a in ( dom ( g1 . z ) ) & a = ( ( g1 . z ) . a )) by ABIAN:def 3;
then (a in ( dom f ) & a = ( f . a )) by B5,B6,GRFUNC_1:2;
hence a is_a_fixpoint_of f by ABIAN:def 3;
end;
hence thesis by B1,Z4;
end;
then ( X \/ Y ) = Z by XBOOLE_1:45;
then ( criticals g2 ) = ( ( criticals g1 ) ^ ( numbering Y ) ) by A1,CKB52:1;
hence ( criticals g1 ) c= ( criticals g2 ) by CKB15:1;
end;
