environ
vocabularies NUMBERS,SUBSET_1,EUCLID,PRE_TOPC,TOPREAL2,RELAT_1,STRUCT_0,XREAL_0,ORDINAL1,ARYTM_1,SQUARE_1,XBOOLE_0,FUNCT_1,TOPS_2,RCOMP_1,ORDINAL2,TOPREAL1,XXREAL_2,MCART_1,XXREAL_0,CARD_1,ARYTM_3,PCOMPS_1,METRIC_1,TARSKI,COMPLEX1,JORDAN2C,RLTOPSP1,SPPOL_1,ZFMISC_1,JORDAN6,JORDAN3,JORDAN18,SEQ_4;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,FUNCT_1,RELSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,SQUARE_1,XXREAL_2,SEQ_4,STRUCT_0,PCOMPS_1,COMPLEX1,PRE_TOPC,TOPS_2,RCOMP_1,COMPTS_1,METRIC_1,SPPOL_1,RLTOPSP1,EUCLID,TOPREAL1,PSCOMP_1,TOPREAL2,JORDAN5C,JORDAN2C,TOPREAL6,JORDAN6,CKB27,CKB28,CKB37,CKB38;
definitions TARSKI,XBOOLE_0,ZFMISC_1,SEQ_4,SQUARE_1,EUCLID,PCOMPS_1,SUBSET_1,XXREAL_2,CKB27,CKB28,CKB37;
theorems JORDAN5B,TARSKI,TOPREAL1,XBOOLE_0,EUCLID,JORDAN6,TOPS_2,XBOOLE_1,SEQ_4,RELAT_1,PSCOMP_1,FUNCT_2,TOPREAL3,JORDAN1A,COMPTS_1,ZFMISC_1,JORDAN5C,TOPREAL2,JORDAN2C,SQUARE_1,RCOMP_1,TOPMETR,METRIC_1,JORDAN16,SPPOL_1,COMPLEX1,XREAL_1,TOPREAL6,XXREAL_0,JCT_MISC,XXREAL_2,PRE_TOPC,RLTOPSP1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB13,CKB14,CKB15,CKB16,CKB17,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47;
registrations XBOOLE_0,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,SQUARE_1,MEMBERED,COMPTS_1,EUCLID,TOPREAL1,STRUCT_0,TOPS_1,CKB9,CKB10,CKB11,CKB12,CKB18,CKB19,CKB20,CKB21;
constructors REAL_1,SQUARE_1,COMPLEX1,RCOMP_1,CONNSP_1,TOPS_2,COMPTS_1,TOPREAL1,SPPOL_1,PSCOMP_1,JORDAN5C,JORDAN6,JORDAN2C,TOPREAL6,SEQ_1,XXREAL_2,SEQ_4,RELSET_1,FUNCSDOM,BINOP_2,PCOMPS_1,RVSUM_1,CKB27,CKB28,CKB37;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve C for Simple_closed_curve;
reserve P for (Subset of ( TOP-REAL 2 ));
reserve p1 for (Point of ( TOP-REAL 2 ));
reserve p2 for (Point of ( TOP-REAL 2 ));
reserve q1 for (Point of ( TOP-REAL 2 ));
reserve q2 for (Point of ( TOP-REAL 2 ));
theorem
((((((((p1 in C & p2 in C) & q1 in C) & p1 <> p2) & q1 <> p1) & q1 <> p2) & q2 <> p1) & q2 <> p2) implies (p1,p2 are_neighbours_wrt q1,q2,C or p1,q1 are_neighbours_wrt p2,q2,C))
proof
assume that
A1: (p1 in C & p2 in C)
and
A2: q1 in C
and
A3: p1 <> p2
and
A4: q1 <> p1
and
A5: q1 <> p2
and
A6: (q2 <> p1 & q2 <> p2);
consider P,P1 being non  empty (Subset of ( TOP-REAL 2 )) such that A7: P is_an_arc_of p1,p2 and A8: P1 is_an_arc_of p1,p2 and A9: C = ( P \/ P1 ) and A10: ( P /\ P1 ) = { p1,p2 } by A1,A3,TOPREAL2:5;
A11: P c= C by A9,XBOOLE_1:7;
assume A12: (for A being (Subset of ( TOP-REAL 2 )) holds ((A is_an_arc_of p1,p2 & A c= C) implies A meets { q1,q2 }));
then A13: P meets { q1,q2 } by A7,A9,XBOOLE_1:7;
A14: P1 c= C by A9,XBOOLE_1:7;
per cases  by A13,ZFMISC_1:51;
suppose that A15: q1 in P
and
A16: (not q2 in P);
now
take A = ( Segment (P,p1,p2,p1,q1) );
A17:now
A18: A = { q where q is (Point of ( TOP-REAL 2 )): ( LE p1,q,P,p1,p2 &  LE q,q1,P,p1,p2) } by JORDAN6:26;
assume p2 in A;
then (ex q being (Point of ( TOP-REAL 2 )) st ((p2 = q &  LE p1,q,P,p1,p2) &  LE q,q1,P,p1,p2)) by A18;
hence contradiction by A5,A7,JORDAN6:55;
end;
 LE p1,q1,P,p1,p2 by A7,A15,JORDAN5C:10;
hence A is_an_arc_of p1,q1 by A4,A7,JORDAN16:21;
A19: A c= P by JORDAN16:2;
hence A c= C by A11,XBOOLE_1:1;
(not q2 in A) by A16,A19;
hence A misses { p2,q2 } by A17,ZFMISC_1:51;
end;
hence thesis by CKB37:def 1;
end;
suppose that A20: q2 in P
and
A21: (not q1 in P);
now
take A = ( Segment (P1,p1,p2,p1,q1) );
A22:now
A23: A = { q where q is (Point of ( TOP-REAL 2 )): ( LE p1,q,P1,p1,p2 &  LE q,q1,P1,p1,p2) } by JORDAN6:26;
assume p2 in A;
then (ex q being (Point of ( TOP-REAL 2 )) st ((p2 = q &  LE p1,q,P1,p1,p2) &  LE q,q1,P1,p1,p2)) by A23;
hence contradiction by A5,A8,JORDAN6:55;
end;
q1 in P1 by A2,A9,A21,XBOOLE_0:def 3;
then  LE p1,q1,P1,p1,p2 by A8,JORDAN5C:10;
hence A is_an_arc_of p1,q1 by A4,A8,JORDAN16:21;
A24: A c= P1 by JORDAN16:2;
hence A c= C by A14,XBOOLE_1:1;
now
assume q2 in A;
then q2 in { p1,p2 } by A10,A20,A24,XBOOLE_0:def 4;
hence contradiction by A6,TARSKI:def 2;
end;
hence A misses { p2,q2 } by A22,ZFMISC_1:51;
end;
hence thesis by CKB37:def 1;
end;
suppose that A25: (q1 in P & q2 in P);
P1 meets { q1,q2 } by A12,A8,A9,XBOOLE_1:7;
then (q1 in P1 or q2 in P1) by ZFMISC_1:51;
then (q1 in { p1,p2 } or q2 in { p1,p2 }) by A10,A25,XBOOLE_0:def 4;
hence thesis by A4,A5,A6,TARSKI:def 2;
end;
end;
