environ
vocabularies ZFMISC_1,XBOOLE_0,TARSKI,SUBSET_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,CKB10,CKB11;
definitions TARSKI,XBOOLE_0,ZFMISC_1,CKB10;
theorems XBOOLE_0,TARSKI,ENUMSET1,ZFMISC_1,XBOOLE_1,CKB10;
schemes XBOOLE_0;
registrations XBOOLE_0,ZFMISC_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB12,CKB13,CKB14;
constructors TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,CKB10;
requirements BOOLE;
begin
registration
let X1 being non  empty set;
let X2 being non  empty set;
let X3 being non  empty set;
let X4 being non  empty set;
cluster [: X1,X2,X3,X4 :] -> non  empty;
coherence;
end;
