environ
vocabularies NUMBERS,SUBSET_1,XREAL_0,ORDINAL1,POWER,CARD_1,NEWTON,XXREAL_0,SQUARE_1,RELAT_1,XBOOLE_0,ARYTM_1,ABIAN,NAT_1,ARYTM_3,PREPOWER,FIB_NUM,FUNCT_1,ZFMISC_1,MCART_1,PRE_FF,FIB_NUM3;
notations TARSKI,XBOOLE_0,SUBSET_1,SQUARE_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,ORDINAL1,NEWTON,NAT_1,MCART_1,DOMAIN_1,PREPOWER,POWER,FUNCT_2,NAT_D,PRE_FF,FIB_NUM,ABIAN,CKB13,CKB36,CKB37;
definitions SQUARE_1,CKB13,CKB37;
theorems NAT_1,MCART_1,POWER,PREPOWER,XCMPLX_1,PRE_FF,FIB_NUM,SQUARE_1,WSIERP_1,NAT_2,ABIAN,FIB_NUM2,XREAL_1,XXREAL_0,ORDINAL1,NAT_D,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45;
schemes FIB_NUM,FIB_NUM2,NAT_1;
registrations SUBSET_1,ORDINAL1,XXREAL_0,XREAL_0,SQUARE_1,NAT_1,MEMBERED,XBOOLE_0,XCMPLX_0,CKB9,CKB10,CKB22;
constructors DOMAIN_1,SQUARE_1,MEMBERED,NEWTON,PREPOWER,POWER,PRE_FF,NAT_D,ABIAN,FIB_NUM,CKB13,CKB36,CKB37;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve a for (Element of ( NAT ));
reserve b for (Element of ( NAT ));
reserve n for (Element of ( NAT ));
theorem
(for a,b,n being (Element of ( NAT )) holds ( ( GenFib (a,b,n) ) + ( GenFib (a,b,( n + 4 )) ) ) = ( 3 * ( GenFib (a,b,( n + 2 )) ) ))
proof
let a being (Element of ( NAT ));
let b being (Element of ( NAT ));
let n being (Element of ( NAT ));
( ( GenFib (a,b,n) ) + ( GenFib (a,b,( n + 4 )) ) ) = ( ( GenFib (a,b,n) ) + ( ( GenFib (a,b,( n + 2 )) ) + ( GenFib (a,b,( n + 3 )) ) ) ) by CKB42:1
.= ( ( ( GenFib (a,b,n) ) + ( GenFib (a,b,( n + 2 )) ) ) + ( GenFib (a,b,( n + 3 )) ) )
.= ( ( ( GenFib (a,b,n) ) + ( GenFib (a,b,( n + 2 )) ) ) + ( ( GenFib (a,b,( n + 1 )) ) + ( GenFib (a,b,( n + 2 )) ) ) ) by CKB41:1
.= ( ( ( ( GenFib (a,b,n) ) + ( GenFib (a,b,( n + 1 )) ) ) + ( GenFib (a,b,( n + 2 )) ) ) + ( GenFib (a,b,( n + 2 )) ) )
.= ( ( ( GenFib (a,b,( n + 2 )) ) + ( GenFib (a,b,( n + 2 )) ) ) + ( GenFib (a,b,( n + 2 )) ) ) by CKB40:1
.= ( 3 * ( GenFib (a,b,( n + 2 )) ) );
hence thesis;
end;
