environ
vocabularies XBOOLE_0,TARSKI,ZFMISC_1;
notations TARSKI,XBOOLE_0,ENUMSET1,CKB5,CKB6,CKB7,CKB8;
definitions TARSKI,XBOOLE_0,CKB5,CKB6,CKB7,CKB8;
theorems TARSKI,XBOOLE_0,ENUMSET1,XBOOLE_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40;
schemes XBOOLE_0;
registrations XBOOLE_0,CKB1;
constructors TARSKI,XBOOLE_0,ENUMSET1,CKB5,CKB6,CKB7,CKB8;
requirements BOOLE;
begin
reserve x1 for set;
reserve x2 for set;
reserve y1 for set;
reserve y2 for set;
theorem
({ x1,x2 } c= { y1,y2 } implies (x1 = y1 or x1 = y2))
proof
assume { x1,x2 } c= { y1,y2 };
then ((({ x1,x2 } = ( {} ) or { x1,x2 } = { y1 }) or { x1,x2 } = { y2 }) or { x1,x2 } = { y1,y2 }) by CKB40:1;
hence thesis by CKB12:1,CKB14:1;
end;
