environ
vocabularies XBOOLE_0,TARSKI,ZFMISC_1,SUBSET_1,RELAT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CKB1;
definitions TARSKI,XBOOLE_0,ZFMISC_1,CKB1;
theorems TARSKI,XBOOLE_0,ZFMISC_1,ENUMSET1,XBOOLE_1,CKB1;
schemes XBOOLE_0;
registrations XBOOLE_0,ZFMISC_1,CKB2;
constructors TARSKI,SUBSET_1,ZFMISC_1,CKB1;
requirements SUBSET,BOOLE;
begin
definition
mode Relation
 is  Relation-like set;
end;
