environ
vocabularies NUMBERS,SUBSET_1,AMI_1,SCMFSA_2,FSM_1,SCMFSA6A,TARSKI,CIRCUIT2,RELAT_1,FUNCT_1,CARD_1,FUNCOP_1,FUNCT_4,XBOOLE_0,SCMFSA6B,NAT_1,XXREAL_0,ARYTM_3,AMI_3,SF_MASTR,GRAPHSP,MSUALG_1,AMISTD_2,TURING_1,STRUCT_0,VALUED_1,SCMFSA6C,SCMFSA7B,UNIALG_2,SCMFSA8B,ARYTM_1,SCMFSA8C,SCMFSA8A,SCM_HALT,PARTFUN1,SCMNORM,RELOC,COMPOS_1;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,CARD_1,NUMBERS,XCMPLX_0,NAT_1,RELAT_1,FINSEQ_1,FUNCT_1,PARTFUN1,FUNCT_4,FUNCT_7,PBOOLE,VALUED_1,STRUCT_0,MEMSTR_0,COMPOS_1,EXTPRO_1,AMISTD_1,AMISTD_2,SCMFSA_2,FUNCOP_1,SCMFSA6B,SCMFSA6A,SF_MASTR,SCMFSA8A,SCMFSA8B,SFMASTR1,SCMFSA8C,SCMFSA7B,NAT_D,SCMFSA_3,SCMFSA6C,XXREAL_0,CKB1,CKB2,CKB3;
definitions FUNCOP_1,COMPOS_1,EXTPRO_1,XBOOLE_0,SCMFSA_2,SCMFSA8C,SCMFSA6A,AMISTD_2,SCMFSA7B,MEMSTR_0,CKB1,CKB2,CKB3;
theorems SF_MASTR,FUNCT_1,FUNCT_7,FUNCOP_1,RELAT_1,SCMFSA6A,FUNCT_4,ENUMSET1,AMI_3,NAT_1,TARSKI,INT_1,GRFUNC_1,SCMFSA_2,SCMFSA6B,SCMFSA7B,SCMFSA8B,SCMFSA8A,SCMFSA8C,SCMFSA_3,SCMFSA6C,CARD_1,XBOOLE_0,XBOOLE_1,XREAL_1,ORDINAL1,XXREAL_0,VALUED_1,XREAL_0,PBOOLE,PARTFUN1,AFINSQ_1,FINSEQ_4,COMPOS_1,SFMASTR1,EXTPRO_1,AMISTD_2,AMISTD_5,ZFMISC_1,MEMSTR_0,AMISTD_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB7,CKB13,CKB14,CKB16,CKB17,CKB18,CKB21;
schemes NAT_1;
registrations XBOOLE_0,SETFAM_1,FUNCT_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,SCMFSA_2,SCMFSA6A,SF_MASTR,SCMFSA6B,SCMFSA6C,SCMFSA7B,SCMFSA8A,SCMFSA8C,SCMFSA_9,ORDINAL1,RELAT_1,SCMFSA10,AMISTD_2,COMPOS_1,SFMASTR1,EXTPRO_1,SCMFSA_4,PBOOLE,FUNCT_4,FUNCT_7,PRE_POLY,STRUCT_0,FUNCOP_1,MEMSTR_0,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB15,CKB19,CKB20,CKB22;
constructors SFMASTR1,DOMAIN_1,XXREAL_0,REAL_1,SCM_1,SCMFSA_3,SCMFSA6A,SF_MASTR,SCMFSA6B,SCMFSA6C,SCMFSA8A,SCMFSA8B,SCMFSA8C,AMISTD_1,AMISTD_2,NAT_D,RELSET_1,VALUED_1,SCMFSA7B,SCMFSA_9,AMISTD_5,PBOOLE,PRE_POLY,MEMSTR_0,CKB1,CKB2,CKB3;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve m for (Element of ( NAT ));
reserve I for (Program of ( SCM+FSA ));
reserve s for (State of ( SCM+FSA ));
reserve p for (Instruction-Sequence of ( SCM+FSA ));
set iS = ( Initialize ( ( intloc ( 0 ) ) .--> 1 ) );
theorem
Th18: (for I being  InitClosed (Program of ( SCM+FSA )) holds (for J being (Program of ( SCM+FSA )) holds (((( Initialize ( ( intloc ( 0 ) ) .--> 1 ) ) c= s & I c= p) & p halts_on s) implies (for m holds (m <= ( LifeSpan (p,s) ) implies ( Comput (p,s,m) ) = ( Comput (( p +* ( I ';' J ) ),s,m) ))))))
proof
let I being  InitClosed (Program of ( SCM+FSA ));
let J being (Program of ( SCM+FSA ));
assume that
A1: iS c= s
and
A2: I c= p
and
A3: p halts_on s;
defpred X[ Nat ]
 means
($1 <= ( LifeSpan (p,s) ) implies ( Comput (p,s,$1) ) = ( Comput (( p +* ( I ';' J ) ),s,$1) ));
A4: (for m holds (X[ m ] implies X[ ( m + 1 ) ]))
proof
set px = ( p +* ( I ';' J ) );
let m;
A5: ( I ';' J ) c= px by FUNCT_4:25;
assume A6: (m <= ( LifeSpan (p,s) ) implies ( Comput (p,s,m) ) = ( Comput (( p +* ( I ';' J ) ),s,m) ));
( dom ( I ';' J ) ) = ( ( dom ( Directed I ) ) \/ ( dom ( Reloc (J,( card I )) ) ) ) by FUNCT_4:def 1
.= ( ( dom I ) \/ ( dom ( Reloc (J,( card I )) ) ) ) by FUNCT_4:99;
then A7: (( {} ) c= ( Comput (px,s,m) ) & ( dom I ) c= ( dom ( I ';' J ) )) by XBOOLE_1:2,XBOOLE_1:7;
A8: ( Comput (p,s,( m + 1 )) ) = ( Following (p,( Comput (p,s,m) )) ) by EXTPRO_1:3
.= ( Exec (( CurInstr (p,( Comput (p,s,m) )) ),( Comput (p,s,m) )) );
A9: ( Comput (px,s,( m + 1 )) ) = ( Following (px,( Comput (px,s,m) )) ) by EXTPRO_1:3
.= ( Exec (( CurInstr (px,( Comput (px,s,m) )) ),( Comput (px,s,m) )) );
A10: ( IC ( Comput (p,s,m) ) ) in ( dom I ) by A1,CKB1:def 1,A2;
A11: ( p /. ( IC ( Comput (p,s,m) ) ) ) = ( p . ( IC ( Comput (p,s,m) ) ) ) by PBOOLE:143;
A12: ( CurInstr (p,( Comput (p,s,m) )) ) = ( I . ( IC ( Comput (p,s,m) ) ) ) by A10,A11,A2,GRFUNC_1:2;
assume A13: ( m + 1 ) <= ( LifeSpan (p,s) );
A15: ( px /. ( IC ( Comput (px,s,m) ) ) ) = ( px . ( IC ( Comput (px,s,m) ) ) ) by PBOOLE:143;
m < ( LifeSpan (p,s) ) by A13,NAT_1:13;
then ( I . ( IC ( Comput (p,s,m) ) ) ) <> ( halt ( SCM+FSA ) ) by A3,A12,EXTPRO_1:def 15;
then ( CurInstr (p,( Comput (p,s,m) )) ) = ( ( I ';' J ) . ( IC ( Comput (p,s,m) ) ) ) by A10,A12,SCMFSA6A:15
.= ( CurInstr (px,( Comput (px,s,m) )) ) by A13,A10,A7,A15,A5,A6,GRFUNC_1:2,NAT_1:13;
hence thesis by A6,A13,A8,A9,NAT_1:13;
end;
(( Comput (p,s,( 0 )) ) = s & ( Comput (( p +* ( I ';' J ) ),s,( 0 )) ) = s) by EXTPRO_1:2;
then A16: X[ ( 0 ) ];
thus (for m holds X[ m ]) from NAT_1:sch 1(A16,A4);
end;
