environ
vocabularies FUNCT_1,TARSKI,RELAT_1,XBOOLE_0,SUBSET_1;
notations TARSKI,XBOOLE_0,SUBSET_1,ENUMSET1,RELAT_1,FUNCT_1;
definitions TARSKI,RELAT_1,XBOOLE_0,FUNCT_1;
theorems TARSKI,XBOOLE_0,ZFMISC_1,FUNCT_1,RELAT_1,XBOOLE_1,ENUMSET1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29;
registrations FUNCT_1,RELAT_1,CKB13;
constructors TARSKI,SUBSET_1,FUNCT_1,ENUMSET1;
requirements SUBSET,BOOLE;
begin
reserve Y for set;
reserve x for set;
reserve y for set;
reserve f for Function;
theorem
(x in ( f " Y ) iff ([ x,( f . x ) ] in f & ( f . x ) in Y))
proof
thus (x in ( f " Y ) implies ([ x,( f . x ) ] in f & ( f . x ) in Y))
proof
assume x in ( f " Y );
then (ex y st ([ x,y ] in f & y in Y)) by RELAT_1:def 14;
hence thesis by FUNCT_1:1;
end;

thus thesis by RELAT_1:def 14;
end;
