environ
vocabularies XBOOLE_0,ANALOAF,SUBSET_1,DIRAF,PARSP_2,FDIFF_1,SEMI_AF1;
notations STRUCT_0,ANALOAF,DIRAF,CKB1,CKB3;
definitions CKB1;
theorems PARDEPAP,DIRAF,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
registrations ANALOAF,STRUCT_0,CKB2;
constructors DIRAF,CKB1;
begin
reserve SAS for Semi_Affine_Space;
reserve a for (Element of SAS);
reserve b for (Element of SAS);
reserve c for (Element of SAS);
theorem
(((a = b or a = c) or b = c) implies a,b // a,c) by CKB1:def 1,CKB4:1,CKB6:1;
