environ
vocabularies XBOOLE_0,FUNCT_1,RELAT_1,PBOOLE,SUBSET_1,CARD_3,REALSET1,TARSKI,ZFMISC_1,PARTFUN1,STRUCT_0,MSUALG_1,MSUALG_2,PRELAMB,MSUALG_3,FINSEQ_1,MARGREL1,LANG1,TDGROUP,DTCONSTR,TREES_3,TREES_4,NAT_1,TREES_2,MCART_1,UNIALG_2,QC_LANG1,GROUP_6,MSAFREE;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NAT_1,RELAT_1,RELSET_1,STRUCT_0,FUNCT_1,PARTFUN1,MCART_1,FUNCT_2,FINSEQ_1,PBOOLE,TREES_2,FINSEQ_2,CARD_3,LANG1,TREES_4,DTCONSTR,MSUALG_1,MSUALG_2,MSUALG_3;
definitions TARSKI,XBOOLE_0,PBOOLE,MSUALG_3;
theorems TARSKI,FUNCT_1,FUNCT_2,MCART_1,ZFMISC_1,PBOOLE,CARD_3,MSUALG_1,MSUALG_2,MSUALG_3,RELAT_1,LANG1,DTCONSTR,FINSEQ_1,TREES_4,TREES_1,DOMAIN_1,RELSET_1,XBOOLE_0,XBOOLE_1,FUNCOP_1,TREES_3,PARTFUN1,FINSEQ_3,FINSEQ_2;
schemes CLASSES1,FUNCT_1,RELSET_1,DTCONSTR,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCOP_1,FINSEQ_1,PBOOLE,TREES_2,TREES_3,STRUCT_0,DTCONSTR,MSUALG_1,MSUALG_3,FUNCT_2,PARTFUN1,RELSET_1,PRE_POLY;
constructors XXREAL_0,NAT_1,NAT_D,CARD_3,FINSEQOP,DTCONSTR,MSUALG_3,RELSET_1,PBOOLE;
requirements NUMERALS,BOOLE,SUBSET;
begin
theorem
Th1: (for I being set holds (for J being non empty set holds (for f being (Function of I,( J * )) holds (for X being (ManySortedSet of J) holds (for p being (Element of ( J * )) holds (for x being set holds ((x in I & p = ( f . x )) implies ( ( ( X # ) * f ) . x ) = ( product ( X * p ) ))))))))
proof
let I being set;
let J being non empty set;
let f being (Function of I,( J * ));
let X being (ManySortedSet of J);
let p being (Element of ( J * ));
let x being set;
assume A1: (x in I & p = ( f . x ));
A2: ( dom f ) = I by FUNCT_2:def 1;
then ( dom ( ( X # ) * f ) ) = ( dom f ) by PARTFUN1:def 2;
hence ( ( ( X # ) * f ) . x ) = ( (( X # ) qua (ManySortedSet of ( J * ))) . p ) by A1,A2,FUNCT_1:12
.= ( product ( X * p ) ) by FINSEQ_2:def 5;
end;
