environ
vocabularies NUMBERS,FUNCT_1,FINSEQ_1,NAT_1,RELAT_1,FINSET_1,CARD_1,XBOOLE_0,TARSKI,XXREAL_0,SUBSET_1,PARTFUN1,ARYTM_1,ARYTM_3,ORDINAL4,FINSEQ_4,FUNCT_2,EQREL_1,CARD_3,SETFAM_1;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,RELAT_1,CARD_1,SETFAM_1,EQREL_1,NUMBERS,XCMPLX_0,FUNCT_1,PARTFUN1,FUNCT_2,FINSET_1,NAT_1,FINSEQ_1,FINSEQ_3,XXREAL_0,CKB1,CKB6,CKB12,CKB18,CKB19,CKB24,CKB39,CKB49;
definitions FUNCT_1,TARSKI,XBOOLE_0,FINSEQ_1,CKB1,CKB6,CKB12,CKB24,CKB39,CKB49;
theorems CARD_1,CARD_2,ENUMSET1,FINSEQ_1,FINSEQ_2,FINSEQ_3,FUNCT_1,FUNCT_2,INT_1,NAT_1,PARTFUN1,TARSKI,WELLORD2,ZFMISC_1,RELAT_1,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,ORDINAL1,GRFUNC_1,EQREL_1,RELSET_1,SETFAM_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58;
schemes FINSEQ_1,FINSET_1,NAT_1,FUNCT_1,FINSEQ_2,FUNCT_2;
registrations XBOOLE_0,RELAT_1,FUNCT_1,FINSET_1,XREAL_0,INT_1,FINSEQ_1,ORDINAL1,CARD_1,RELSET_1,SUBSET_1,EQREL_1,NAT_1,PARTFUN1,FUNCT_2,XXREAL_0,MEMBERED;
constructors ENUMSET1,WELLORD2,FUNCT_2,XXREAL_0,REAL_1,PARTFUN1,NAT_1,INT_1,FINSEQ_3,RELSET_1,EQREL_1,SETFAM_1,CKB1,CKB6,CKB12,CKB18,CKB19,CKB24,CKB39,CKB49;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve p for FinSequence;
reserve x for set;
theorem
Th66: (x in ( rng p ) implies p = ( ( ( p -| x ) ^ <* x *> ) ^ ( p |-- x ) ))
proof
set q1 = ( p -| x );
set q2 = ( p |-- x );
set r = ( q1 ^ <* x *> );
assume A1: x in ( rng p );
A2:now
let k being (Element of ( NAT ));
assume k in ( dom q2 );
then ( q2 . k ) = ( p . ( ( ( ( x .. p ) - 1 ) + 1 ) + k ) ) by A1,CKB49:def 1
.= ( p . ( ( ( len q1 ) + 1 ) + k ) ) by A1,CKB41:1
.= ( p . ( ( ( len q1 ) + ( len <* x *> ) ) + k ) ) by FINSEQ_1:40
.= ( p . ( ( len r ) + k ) ) by FINSEQ_1:22;
hence ( p . ( ( len r ) + k ) ) = ( q2 . k );
end;
A3:now
let k being (Element of ( NAT ));
assume A4: k in ( dom r );
now
per cases  by A4,FINSEQ_1:25;
suppose A5: k in ( dom q1 );

hence ( r . k ) = ( q1 . k ) by FINSEQ_1:def 7
.= ( p . k ) by A1,A5,CKB43:1;
end;
suppose (ex n being Nat st (n in ( dom <* x *> ) & k = ( ( len q1 ) + n )));

then consider n being Nat such that A6: n in ( dom <* x *> ) and A7: k = ( ( len q1 ) + n );
n in { 1 } by A6,FINSEQ_1:2,FINSEQ_1:def 8;
then A8: n = 1 by TARSKI:def 1;
hence ( r . k ) = ( <* x *> . 1 ) by A6,A7,FINSEQ_1:def 7
.= x by FINSEQ_1:def 8
.= ( p . ( ( ( x .. p ) - 1 ) + 1 ) ) by A1,CKB25:1
.= ( p . k ) by A1,A7,A8,CKB41:1;
end;
end;
hence ( p . k ) = ( r . k );
end;
( len p ) = ( ( ( len p ) - ( x .. p ) ) + ( x .. p ) )
.= ( ( ( ( x .. p ) - 1 ) + 1 ) + ( len q2 ) ) by A1,CKB49:def 1
.= ( ( ( len q1 ) + 1 ) + ( len q2 ) ) by A1,CKB41:1
.= ( ( ( len q1 ) + ( len <* x *> ) ) + ( len q2 ) ) by FINSEQ_1:40
.= ( ( len r ) + ( len q2 ) ) by FINSEQ_1:22;
hence thesis by A3,A2,FINSEQ_3:38;
end;
