environ
vocabularies GRAPH_1,STRUCT_0,FUNCT_1,PARTFUN1,ZFMISC_1,SUBSET_1,XBOOLE_0,CARD_1,FUNCOP_1,RELAT_1,TARSKI,ALGSTR_0,WELLORD1,CAT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,NUMBERS,BINOP_1,FUNCOP_1,STRUCT_0,GRAPH_1,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7;
definitions TARSKI,FUNCOP_1,BINOP_1,GRAPH_1,CKB5,CKB6,CKB7;
theorems TARSKI,FUNCT_1,FUNCT_2,PARTFUN1,FUNCOP_1,SUBSET_1,WELLORD2,RELAT_1,CKB5,CKB6,CKB7,CKB8,CKB9;
schemes FUNCT_2;
registrations XBOOLE_0,FUNCT_1,RELSET_1,FUNCT_2,STRUCT_0,RELAT_1,CKB1,CKB4;
constructors PARTFUN1,WELLORD2,BINOP_1,PBOOLE,GRAPH_1,RELSET_1,CKB1,CKB5,CKB6,CKB7;
requirements SUBSET,BOOLE;
begin
reserve C for non  void non  empty CatStr;
reserve a for (Object of C);
reserve b for (Object of C);
definition
let C;
let a;
let b;
assume A1: ( Hom (a,b) ) <> ( {} );
mode Morphism of a,b
 -> (Morphism of C)
means :Def7: it in ( Hom (a,b) );
existence by A1,SUBSET_1:4;
end;
