environ
vocabularies GRAPH_1,STRUCT_0,FUNCT_1,PARTFUN1,ZFMISC_1,SUBSET_1,XBOOLE_0,CARD_1,FUNCOP_1,RELAT_1,TARSKI,ALGSTR_0,WELLORD1,CAT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,NUMBERS,BINOP_1,FUNCOP_1,STRUCT_0,GRAPH_1,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB10,CKB18,CKB20,CKB22,CKB35,CKB36,CKB37,CKB40,CKB44,CKB60,CKB66,CKB67,CKB68,CKB82,CKB88,CKB93;
definitions TARSKI,FUNCOP_1,BINOP_1,GRAPH_1,CKB5,CKB6,CKB7,CKB10,CKB18,CKB22,CKB35,CKB36,CKB37,CKB40,CKB60,CKB66,CKB67,CKB68,CKB82,CKB88,CKB93;
theorems TARSKI,FUNCT_1,FUNCT_2,PARTFUN1,FUNCOP_1,SUBSET_1,WELLORD2,RELAT_1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96;
schemes FUNCT_2;
registrations XBOOLE_0,FUNCT_1,RELSET_1,FUNCT_2,STRUCT_0,RELAT_1,CKB1,CKB4,CKB19;
constructors PARTFUN1,WELLORD2,BINOP_1,PBOOLE,GRAPH_1,RELSET_1,CKB1,CKB5,CKB6,CKB7,CKB10,CKB18,CKB22,CKB35,CKB36,CKB37,CKB40,CKB44,CKB60,CKB66,CKB67,CKB68,CKB82,CKB88,CKB93;
requirements SUBSET,BOOLE;
begin
reserve B for Category;
reserve C for Category;
reserve D for Category;
reserve a for (Object of C);
reserve b for (Object of C);
reserve c for (Object of C);
reserve f for (Morphism of a,b);
reserve g for (Morphism of b,c);
theorem
Th110: (for T being (Functor of B,C) holds (for S being (Functor of C,D) holds ( S * T ) is (Functor of B,D)))
proof
let T being (Functor of B,C);
let S being (Functor of C,D);
reconsider FF = ( ( Obj S ) * ( Obj T ) ) as (Function of (the carrier of B),(the carrier of D));
reconsider TT = ( S * T ) as (Function of (the carrier' of B),(the carrier' of D));
now
thus (for b being (Object of B) holds ( TT . ( id b ) ) = ( id ( FF . b ) ))
proof
let b being (Object of B);
thus ( TT . ( id b ) ) = ( S . ( T . ( id b ) ) ) by FUNCT_2:15
.= ( S . ( id ( T . b ) ) ) by CKB91:1
.= ( id ( S . ( ( Obj T ) . b ) ) ) by CKB91:1
.= ( id ( FF . b ) ) by FUNCT_2:15;
end;

thus (for f being (Morphism of B) holds (( FF . ( dom f ) ) = ( dom ( TT . f ) ) & ( FF . ( cod f ) ) = ( cod ( TT . f ) )))
proof
let f being (Morphism of B);
thus ( FF . ( dom f ) ) = ( ( Obj S ) . ( ( Obj T ) . ( dom f ) ) ) by FUNCT_2:15
.= ( ( Obj S ) . ( dom ( T . f ) ) ) by CKB92:1
.= ( dom ( S . ( T . f ) ) ) by CKB92:1
.= ( dom ( TT . f ) ) by FUNCT_2:15;
thus ( FF . ( cod f ) ) = ( ( Obj S ) . ( ( Obj T ) . ( cod f ) ) ) by FUNCT_2:15
.= ( ( Obj S ) . ( cod ( T . f ) ) ) by CKB92:1
.= ( cod ( S . ( T . f ) ) ) by CKB92:1
.= ( cod ( TT . f ) ) by FUNCT_2:15;
end;

let f being (Morphism of B);
let g being (Morphism of B);
assume A1: ( dom g ) = ( cod f );
then A2: ( dom ( T . g ) ) = ( cod ( T . f ) ) by CKB86:1;
thus ( TT . ( g * f ) ) = ( S . ( T . ( g * f ) ) ) by FUNCT_2:15
.= ( S . ( ( T . g ) * ( T . f ) ) ) by A1,CKB86:1
.= ( ( S . ( T . g ) ) * ( S . ( T . f ) ) ) by A2,CKB86:1
.= ( ( TT . g ) * ( S . ( T . f ) ) ) by FUNCT_2:15
.= ( ( TT . g ) * ( TT . f ) ) by FUNCT_2:15;
end;
hence thesis by CKB87:1;
end;
