environ
vocabularies FUNCT_1,PBOOLE,RELAT_1,FUNCT_4,FUNCOP_1,XBOOLE_0,FINSET_1,TARSKI,ZFMISC_1,PZFMISC1;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,FUNCT_1,FUNCT_4,FINSET_1,FUNCOP_1,PBOOLE,MBOOLEAN;
definitions FINSET_1,PBOOLE,FUNCOP_1;
theorems FUNCOP_1,ENUMSET1,FUNCT_4,MBOOLEAN,PBOOLE,SETWISEO,TARSKI,ZFMISC_1,RELAT_1,XBOOLE_0,PARTFUN1,CKB1,CKB2;
schemes PBOOLE;
registrations XBOOLE_0,FUNCOP_1,FINSET_1;
constructors FUNCT_4,MBOOLEAN,PBOOLE,FINSET_1,RELSET_1;
requirements BOOLE;
begin
reserve i for set;
reserve I for set;
reserve X for (ManySortedSet of I);
theorem
(I is non empty implies (not (ex X st (X is  empty-yielding & X is  non-empty))))
proof
assume A1: I is non empty;
given X such that
A2: X is  empty-yielding
and
A3: X is  non-empty;

consider i such that A4: i in I by A1,XBOOLE_0:def 1;
( X . i ) is  empty by A2,A4,PBOOLE:def 12;
hence contradiction by A3,A4,PBOOLE:def 13;
end;
