environ
vocabularies NUMBERS,SUBSET_1,XREAL_0,ORDINAL1,NAT_1,ARYTM_3,XXREAL_0,ARYTM_1,FINSEQ_1,XBOOLE_0,RELAT_1,FINSET_1,TARSKI,COMPLEX1,REAL_1,PRE_TOPC,EUCLID,METRIC_1,FUNCT_1,RCOMP_1,RLTOPSP1,CARD_1,SEQ_4,XXREAL_2,PCOMPS_1,STRUCT_0,SUPINF_2,TEX_2,COMPTS_1,TOPREAL1,BORSUK_1,TOPS_2,ORDINAL2,MCART_1,ZFMISC_1,PARTFUN1,SETFAM_1,SPPOL_1;
notations TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,ORDINAL1,NUMBERS,XXREAL_0,XXREAL_2,XREAL_0,COMPLEX1,REAL_1,NAT_1,SQUARE_1,SEQ_4,FUNCT_1,PARTFUN1,PRE_TOPC,BORSUK_1,FINSET_1,FINSEQ_1,FINSEQ_4,DOMAIN_1,STRUCT_0,METRIC_1,PCOMPS_1,TOPS_2,ZFMISC_1,COMPTS_1,RLVECT_1,RLTOPSP1,EUCLID,TEX_2,TOPREAL1,CKB13,CKB20,CKB21,CKB42;
definitions TARSKI,TOPREAL1,SEQ_4,EUCLID,COMPTS_1,SUBSET_1,VALUED_1,STRUCT_0,ALGSTR_0,RLTOPSP1,XXREAL_2,CKB13,CKB20,CKB21,CKB42;
theorems TARSKI,NAT_1,INT_1,ABSVALUE,SUBSET_1,FINSET_1,FINSEQ_1,PRE_TOPC,METRIC_1,TOPS_1,TOPS_2,SEQ_4,EUCLID,TOPMETR,TOPREAL1,TOPREAL3,PCOMPS_1,COMPTS_1,TEX_2,FINSEQ_3,ZFMISC_1,HEINE,TDLAT_3,PARTFUN2,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,RLTOPSP1,CKB1,CKB2,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB25,CKB26,CKB27,CKB28,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51;
schemes FRAENKEL,CKB3,CKB4;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,INT_1,MEMBERED,FINSEQ_1,STRUCT_0,PRE_TOPC,TEX_2,EUCLID,TOPREAL1,FINSET_1,VALUED_0,RLTOPSP1,FUNCT_1,CKB11,CKB12,CKB23,CKB24,CKB29,CKB40;
constructors SETFAM_1,REAL_1,SQUARE_1,NAT_1,COMPLEX1,SEQ_4,FINSEQ_4,TOPS_2,COMPTS_1,REALSET2,TDLAT_3,TEX_2,MONOID_0,TOPMETR,TOPREAL1,PCOMPS_1,XXREAL_2,FUNCSDOM,CONVEX1,BINOP_2,CKB13,CKB20,CKB21,CKB42;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve i for (Element of ( NAT ));
reserve r for Real;
reserve s for Real;
reserve s1 for Real;
reserve f for (FinSequence of (the carrier of ( TOP-REAL 2 )));
reserve p for (Point of ( TOP-REAL 2 ));
reserve q for (Point of ( TOP-REAL 2 ));
theorem
Th58: (((((f is  special  alternating & 1 <= i) & ( i + 2 ) <= ( len f )) & ( f /. ( i + 1 ) ) in ( LSeg (p,q) )) & ( LSeg (p,q) ) c= ( ( LSeg (f,i) ) \/ ( LSeg (f,( i + 1 )) ) )) implies (( f /. ( i + 1 ) ) = p or ( f /. ( i + 1 ) ) = q))
proof
assume that
A1: (f is  special & f is  alternating)
and
A2: 1 <= i
and
A3: ( i + 2 ) <= ( len f );
( i + 1 ) <= ( i + 2 ) by XREAL_1:6;
then A4: ( i + 1 ) <= ( len f ) by A3,XXREAL_0:2;
set p1 = ( f /. i );
set p0 = ( f /. ( i + 1 ) );
set p2 = ( f /. ( i + 2 ) );
A5: (( i + ( 1 + 1 ) ) = ( ( i + 1 ) + 1 ) & 1 <= ( i + 1 )) by NAT_1:11;
assume that
A6: p0 in ( LSeg (p,q) )
and
A7: ( LSeg (p,q) ) c= ( ( LSeg (f,i) ) \/ ( LSeg (f,( i + 1 )) ) );
A8: (p in ( LSeg (p,q) ) & q in ( LSeg (p,q) )) by RLTOPSP1:68;
now
per cases  by A7,A8,XBOOLE_0:def 3;
case (p in ( LSeg (f,i) ) & q in ( LSeg (f,i) ));
then (p in ( LSeg (p1,p0) ) & q in ( LSeg (p1,p0) )) by A2,A4,TOPREAL1:def 3;
then A9: ( LSeg (p,q) ) c= ( LSeg (p1,p0) ) by TOPREAL1:6;
p0 is_extremal_in ( LSeg (p1,p0) ) by CKB16:1;
hence thesis by A6,A9,CKB13:def 1;
end;
case A10: (p in ( LSeg (f,i) ) & q in ( LSeg (f,( i + 1 )) ));
then p in ( LSeg (p1,p0) ) by A2,A4,TOPREAL1:def 3;
then consider s such that A11: p = ( ( ( 1 - s ) * p1 ) + ( s * p0 ) ) and ( 0 ) <= s and s <= 1;
A12: ( p `1 ) = ( ( ( ( 1 - s ) * p1 ) `1 ) + ( ( s * p0 ) `1 ) ) by A11,TOPREAL3:2
.= ( ( ( 1 - s ) * ( p1 `1 ) ) + ( ( s * p0 ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - s ) * ( p1 `1 ) ) + ( s * ( p0 `1 ) ) ) by TOPREAL3:4;
q in ( LSeg (p0,p2) ) by A3,A5,A10,TOPREAL1:def 3;
then consider s1 such that A13: q = ( ( ( 1 - s1 ) * p0 ) + ( s1 * p2 ) ) and ( 0 ) <= s1 and s1 <= 1;
A14: ( q `2 ) = ( ( ( ( 1 - s1 ) * p0 ) `2 ) + ( ( s1 * p2 ) `2 ) ) by A13,TOPREAL3:2
.= ( ( ( 1 - s1 ) * ( p0 `2 ) ) + ( ( s1 * p2 ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - s1 ) * ( p0 `2 ) ) + ( s1 * ( p2 `2 ) ) ) by TOPREAL3:4;
A15: ( p `2 ) = ( ( ( ( 1 - s ) * p1 ) `2 ) + ( ( s * p0 ) `2 ) ) by A11,TOPREAL3:2
.= ( ( ( 1 - s ) * ( p1 `2 ) ) + ( ( s * p0 ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - s ) * ( p1 `2 ) ) + ( s * ( p0 `2 ) ) ) by TOPREAL3:4;
A16: ( q `1 ) = ( ( ( ( 1 - s1 ) * p0 ) `1 ) + ( ( s1 * p2 ) `1 ) ) by A13,TOPREAL3:2
.= ( ( ( 1 - s1 ) * ( p0 `1 ) ) + ( ( s1 * p2 ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - s1 ) * ( p0 `1 ) ) + ( s1 * ( p2 `1 ) ) ) by TOPREAL3:4;
now
A17: (( f /. ( i + 2 ) ) = ( f /. ( i + 2 ) ) & ( f /. i ) = ( f /. i ));
per cases  by A1,A2,A3,A17,CKB45:1;
case A18: (( p1 `1 ) = ( p0 `1 ) & ( p2 `1 ) <> ( p0 `1 ));
consider r such that A19: p0 = ( ( ( 1 - r ) * p ) + ( r * q ) ) and ( 0 ) <= r and r <= 1 by A6;
( p0 `1 ) = ( ( ( ( 1 - r ) * p ) `1 ) + ( ( r * q ) `1 ) ) by A19,TOPREAL3:2
.= ( ( ( 1 - r ) * ( p `1 ) ) + ( ( r * q ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - r ) * ( p0 `1 ) ) + ( r * ( q `1 ) ) ) by A12,A18,TOPREAL3:4;
then ( r * ( ( p0 `1 ) - ( q `1 ) ) ) = ( 0 );
then A20: (r = ( 0 ) or ( ( p0 `1 ) - ( q `1 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A20;
case r = ( 0 );
then p0 = ( ( ( 1 - ( 0 ) ) * p ) + ( 0. ( TOP-REAL 2 ) ) ) by A19,EUCLID:29
.= ( 1 * p ) by EUCLID:27
.= p by EUCLID:29;
hence thesis;
end;
case ( p0 `1 ) = ( q `1 );
then ( s1 * ( ( p0 `1 ) - ( p2 `1 ) ) ) = ( 0 ) by A16;
then A21: (s1 = ( 0 ) or ( ( p0 `1 ) - ( p2 `1 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A21;
case s1 = ( 0 );
then q = ( ( ( 1 - ( 0 ) ) * p0 ) + ( 0. ( TOP-REAL 2 ) ) ) by A13,EUCLID:29
.= ( 1 * p0 ) by EUCLID:27
.= p0 by EUCLID:29;
hence thesis;
end;
case ( p0 `1 ) = ( p2 `1 );
hence contradiction by A18;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
case A22: (( p1 `2 ) = ( p0 `2 ) & ( p2 `2 ) <> ( p0 `2 ));
consider r such that A23: p0 = ( ( ( 1 - r ) * p ) + ( r * q ) ) and ( 0 ) <= r and r <= 1 by A6;
( p0 `2 ) = ( ( ( ( 1 - r ) * p ) `2 ) + ( ( r * q ) `2 ) ) by A23,TOPREAL3:2
.= ( ( ( 1 - r ) * ( p `2 ) ) + ( ( r * q ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - r ) * ( p0 `2 ) ) + ( r * ( q `2 ) ) ) by A15,A22,TOPREAL3:4;
then ( r * ( ( p0 `2 ) - ( q `2 ) ) ) = ( 0 );
then A24: (r = ( 0 ) or ( ( p0 `2 ) - ( q `2 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A24;
case r = ( 0 );
then p0 = ( ( ( 1 - ( 0 ) ) * p ) + ( 0. ( TOP-REAL 2 ) ) ) by A23,EUCLID:29
.= ( 1 * p ) by EUCLID:27
.= p by EUCLID:29;
hence thesis;
end;
case ( p0 `2 ) = ( q `2 );
then ( s1 * ( ( p0 `2 ) - ( p2 `2 ) ) ) = ( 0 ) by A14;
then A25: (s1 = ( 0 ) or ( ( p0 `2 ) - ( p2 `2 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A25;
case s1 = ( 0 );
then q = ( ( ( 1 - ( 0 ) ) * p0 ) + ( 0. ( TOP-REAL 2 ) ) ) by A13,EUCLID:29
.= ( 1 * p0 ) by EUCLID:27
.= p0 by EUCLID:29;
hence thesis;
end;
case ( p0 `2 ) = ( p2 `2 );
hence contradiction by A22;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
case A26: (p in ( LSeg (f,( i + 1 )) ) & q in ( LSeg (f,i) ));
then q in ( LSeg (p1,p0) ) by A2,A4,TOPREAL1:def 3;
then consider s such that A27: q = ( ( ( 1 - s ) * p1 ) + ( s * p0 ) ) and ( 0 ) <= s and s <= 1;
A28: ( q `1 ) = ( ( ( ( 1 - s ) * p1 ) `1 ) + ( ( s * p0 ) `1 ) ) by A27,TOPREAL3:2
.= ( ( ( 1 - s ) * ( p1 `1 ) ) + ( ( s * p0 ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - s ) * ( p1 `1 ) ) + ( s * ( p0 `1 ) ) ) by TOPREAL3:4;
p in ( LSeg (p0,p2) ) by A3,A5,A26,TOPREAL1:def 3;
then consider s1 such that A29: p = ( ( ( 1 - s1 ) * p0 ) + ( s1 * p2 ) ) and ( 0 ) <= s1 and s1 <= 1;
A30: ( p `2 ) = ( ( ( ( 1 - s1 ) * p0 ) `2 ) + ( ( s1 * p2 ) `2 ) ) by A29,TOPREAL3:2
.= ( ( ( 1 - s1 ) * ( p0 `2 ) ) + ( ( s1 * p2 ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - s1 ) * ( p0 `2 ) ) + ( s1 * ( p2 `2 ) ) ) by TOPREAL3:4;
A31: ( q `2 ) = ( ( ( ( 1 - s ) * p1 ) `2 ) + ( ( s * p0 ) `2 ) ) by A27,TOPREAL3:2
.= ( ( ( 1 - s ) * ( p1 `2 ) ) + ( ( s * p0 ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - s ) * ( p1 `2 ) ) + ( s * ( p0 `2 ) ) ) by TOPREAL3:4;
A32: ( p `1 ) = ( ( ( ( 1 - s1 ) * p0 ) `1 ) + ( ( s1 * p2 ) `1 ) ) by A29,TOPREAL3:2
.= ( ( ( 1 - s1 ) * ( p0 `1 ) ) + ( ( s1 * p2 ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - s1 ) * ( p0 `1 ) ) + ( s1 * ( p2 `1 ) ) ) by TOPREAL3:4;
now
A33: (( f /. ( i + 2 ) ) = ( f /. ( i + 2 ) ) & ( f /. i ) = ( f /. i ));
per cases  by A1,A2,A3,A33,CKB45:1;
case A34: (( p1 `1 ) = ( p0 `1 ) & ( p2 `1 ) <> ( p0 `1 ));
p0 in ( LSeg (q,p) ) by A6;
then consider r such that A35: p0 = ( ( ( 1 - r ) * q ) + ( r * p ) ) and ( 0 ) <= r and r <= 1;
( p0 `1 ) = ( ( ( ( 1 - r ) * q ) `1 ) + ( ( r * p ) `1 ) ) by A35,TOPREAL3:2
.= ( ( ( 1 - r ) * ( q `1 ) ) + ( ( r * p ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - r ) * ( p0 `1 ) ) + ( r * ( p `1 ) ) ) by A28,A34,TOPREAL3:4;
then ( r * ( ( p0 `1 ) - ( p `1 ) ) ) = ( 0 );
then A36: (r = ( 0 ) or ( ( p0 `1 ) - ( p `1 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A36;
case r = ( 0 );
then p0 = ( ( ( 1 - ( 0 ) ) * q ) + ( 0. ( TOP-REAL 2 ) ) ) by A35,EUCLID:29
.= ( 1 * q ) by EUCLID:27
.= q by EUCLID:29;
hence thesis;
end;
case ( p0 `1 ) = ( p `1 );
then ( s1 * ( ( p0 `1 ) - ( p2 `1 ) ) ) = ( 0 ) by A32;
then A37: (s1 = ( 0 ) or ( ( p0 `1 ) - ( p2 `1 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A37;
case s1 = ( 0 );
then p = ( ( ( 1 - ( 0 ) ) * p0 ) + ( 0. ( TOP-REAL 2 ) ) ) by A29,EUCLID:29
.= ( 1 * p0 ) by EUCLID:27
.= p0 by EUCLID:29;
hence thesis;
end;
case ( p0 `1 ) = ( p2 `1 );
hence contradiction by A34;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
case A38: (( p1 `2 ) = ( p0 `2 ) & ( p2 `2 ) <> ( p0 `2 ));
p0 in ( LSeg (q,p) ) by A6;
then consider r such that A39: p0 = ( ( ( 1 - r ) * q ) + ( r * p ) ) and ( 0 ) <= r and r <= 1;
( p0 `2 ) = ( ( ( ( 1 - r ) * q ) `2 ) + ( ( r * p ) `2 ) ) by A39,TOPREAL3:2
.= ( ( ( 1 - r ) * ( q `2 ) ) + ( ( r * p ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - r ) * ( p0 `2 ) ) + ( r * ( p `2 ) ) ) by A31,A38,TOPREAL3:4;
then ( r * ( ( p0 `2 ) - ( p `2 ) ) ) = ( 0 );
then A40: (r = ( 0 ) or ( ( p0 `2 ) - ( p `2 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A40;
case r = ( 0 );
then p0 = ( ( ( 1 - ( 0 ) ) * q ) + ( 0. ( TOP-REAL 2 ) ) ) by A39,EUCLID:29
.= ( 1 * q ) by EUCLID:27
.= q by EUCLID:29;
hence thesis;
end;
case ( p0 `2 ) = ( p `2 );
then ( s1 * ( ( p0 `2 ) - ( p2 `2 ) ) ) = ( 0 ) by A30;
then A41: (s1 = ( 0 ) or ( ( p0 `2 ) - ( p2 `2 ) ) = ( 0 )) by XCMPLX_1:6;
now
per cases  by A41;
case s1 = ( 0 );
then p = ( ( ( 1 - ( 0 ) ) * p0 ) + ( 0. ( TOP-REAL 2 ) ) ) by A29,EUCLID:29
.= ( 1 * p0 ) by EUCLID:27
.= p0 by EUCLID:29;
hence thesis;
end;
case ( p0 `2 ) = ( p2 `2 );
hence contradiction by A38;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
end;
hence thesis;
end;
case (p in ( LSeg (f,( i + 1 )) ) & q in ( LSeg (f,( i + 1 )) ));
then (p in ( LSeg (p0,p2) ) & q in ( LSeg (p0,p2) )) by A3,A5,TOPREAL1:def 3;
then A42: ( LSeg (p,q) ) c= ( LSeg (p0,p2) ) by TOPREAL1:6;
p0 is_extremal_in ( LSeg (p0,p2) ) by CKB16:1;
hence thesis by A6,A42,CKB13:def 1;
end;
end;
hence thesis;
end;
