environ
vocabularies NUMBERS,XBOOLE_0,RLVECT_1,SUBSET_1,REAL_1,RELAT_1,CARD_1,ARYTM_3,ARYTM_1,TARSKI,SUPINF_2,ALGSTR_0,RUSUB_4,RLSUB_1,STRUCT_0,XXREAL_0,SETFAM_1,BHSP_1,PROB_2,RLVECT_2,FINSEQ_1,FUNCT_1,CARD_3,NAT_1,PARTFUN1,VALUED_1,CONVEX1;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,SETFAM_1,DOMAIN_1,STRUCT_0,ALGSTR_0,CARD_1,NUMBERS,XCMPLX_0,FUNCT_1,NAT_1,REAL_1,PARTFUN1,FINSEQ_1,RLVECT_1,RLSUB_1,RLVECT_2,RVSUM_1,BHSP_1,RUSUB_4,RUSUB_5,XXREAL_0,CKB1,CKB2;
definitions TARSKI,XBOOLE_0,RLVECT_1,RVSUM_1,CKB1,CKB2;
theorems BHSP_1,SUBSET_1,RLVECT_1,RVSUM_1,FUNCT_1,FINSEQ_1,TARSKI,ZFMISC_1,XBOOLE_0,SETFAM_1,RLSUB_1,RUSUB_4,RUSUB_5,RLVECT_2,CARD_1,FINSEQ_3,FINSEQ_4,CARD_2,ENUMSET1,XCMPLX_1,XREAL_1,FINSOP_1,PARTFUN1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10;
schemes DOMAIN_1,SUBSET_1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,RLVECT_1,RUSUB_4,VALUED_0,FINSEQ_1,CARD_1;
constructors SETFAM_1,DOMAIN_1,XXREAL_0,REAL_1,PARTFUN1,BINOP_2,FINSEQ_4,FINSOP_1,RVSUM_1,RLVECT_2,RUSUB_5,RELSET_1,CKB1,CKB2;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
theorem
Lm3: (for V being  add-associative non empty addLoopStr holds (for M1,M2,M3 being (Subset of V) holds ( ( M1 + M2 ) + M3 ) = ( M1 + ( M2 + M3 ) )))
proof
let V being  add-associative non empty addLoopStr;
let M1 being (Subset of V),M2 being (Subset of V),M3 being (Subset of V);
(for x being (Element of V) holds (x in ( M1 + ( M2 + M3 ) ) implies x in ( ( M1 + M2 ) + M3 )))
proof
let x being (Element of V);
assume x in ( M1 + ( M2 + M3 ) );
then x in { ( u + v ) where u is (Element of V),v is (Element of V): (u in M1 & v in ( M2 + M3 )) } by RUSUB_4:def 9;
then consider x1 being (Element of V),x9 being (Element of V) such that A1: x = ( x1 + x9 ) and A2: x1 in M1 and A3: x9 in ( M2 + M3 );
x9 in { ( u + v ) where u is (Element of V),v is (Element of V): (u in M2 & v in M3) } by A3,RUSUB_4:def 9;
then consider x2 being (Element of V),x3 being (Element of V) such that A4: x9 = ( x2 + x3 ) and A5: x2 in M2 and A6: x3 in M3;
( x1 + x2 ) in { ( u + v ) where u is (Element of V),v is (Element of V): (u in M1 & v in M2) } by A2,A5;
then A7: ( x1 + x2 ) in ( M1 + M2 ) by RUSUB_4:def 9;
x = ( ( x1 + x2 ) + x3 ) by A1,A4,RLVECT_1:def 3;
then x in { ( u + v ) where u is (Element of V),v is (Element of V): (u in ( M1 + M2 ) & v in M3) } by A6,A7;
hence thesis by RUSUB_4:def 9;
end;
then A8: ( M1 + ( M2 + M3 ) ) c= ( ( M1 + M2 ) + M3 ) by SUBSET_1:2;
(for x being (Element of V) holds (x in ( ( M1 + M2 ) + M3 ) implies x in ( M1 + ( M2 + M3 ) )))
proof
let x being (Element of V);
assume x in ( ( M1 + M2 ) + M3 );
then x in { ( u + v ) where u is (Element of V),v is (Element of V): (u in ( M1 + M2 ) & v in M3) } by RUSUB_4:def 9;
then consider x9 being (Element of V),x3 being (Element of V) such that A9: x = ( x9 + x3 ) and A10: x9 in ( M1 + M2 ) and A11: x3 in M3;
x9 in { ( u + v ) where u is (Element of V),v is (Element of V): (u in M1 & v in M2) } by A10,RUSUB_4:def 9;
then consider x1 being (Element of V),x2 being (Element of V) such that A12: x9 = ( x1 + x2 ) and A13: x1 in M1 and A14: x2 in M2;
( x2 + x3 ) in { ( u + v ) where u is (Element of V),v is (Element of V): (u in M2 & v in M3) } by A11,A14;
then A15: ( x2 + x3 ) in ( M2 + M3 ) by RUSUB_4:def 9;
x = ( x1 + ( x2 + x3 ) ) by A9,A12,RLVECT_1:def 3;
then x in { ( u + v ) where u is (Element of V),v is (Element of V): (u in M1 & v in ( M2 + M3 )) } by A13,A15;
hence thesis by RUSUB_4:def 9;
end;
then ( ( M1 + M2 ) + M3 ) c= ( M1 + ( M2 + M3 ) ) by SUBSET_1:2;
hence thesis by A8,XBOOLE_0:def 10;
end;
