environ
vocabularies NUMBERS,SUBSET_1,XREAL_0,ORDINAL1,PRE_TOPC,EUCLID,ARYTM_1,ARYTM_3,SUPINF_2,XBOOLE_0,RELAT_1,CARD_1,VALUED_0,FINSEQ_1,COMPLEX1,SQUARE_1,CARD_3,RVSUM_1,XXREAL_0,NAT_1,TARSKI,STRUCT_0,REAL_1,FUNCT_1,UNIALG_1,MSSUBFAM,FUNCOP_1,FINSEQ_2,ALGSTR_0,FUNCT_2,FVSUM_1,INCSP_1,MATRIX_1,MATRIX_3,MATRIX13,MATRLIN,MATRLIN2,MESFUNC1,ORDINAL4,PARTFUN1,PRVECT_1,QC_LANG1,RLVECT_2,RLVECT_3,TREES_1,VALUED_1,VECTSP_1,MATRIXJ1,ZFMISC_1,BINOP_1,GROUP_1,ABIAN,MATRIX_2,XXREAL_1,SIN_COS,FINSOP_1,FUNCT_4,MATRIX_6,PRE_POLY,TOPS_2,RFINSEQ,MONOID_0,MATRIXR2,MATRTOP3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,NAT_D,FUNCOP_1,FINSEQ_1,PRE_POLY,RFINSEQ,FINSEQ_2,RVSUM_1,VALUED_0,SQUARE_1,STRUCT_0,PRE_TOPC,TOPS_2,RLVECT_1,EUCLID,GRCAT_1,TOPREAL9,CARD_1,VECTSP_1,MATRIX_1,MATRIX_2,MATRIX_3,MATRIX_6,GROUP_1,MATRIX11,MATRTOP1,SIN_COS,ALGSTR_0,MATRIX_7,BINOP_1,FVSUM_1,RCOMP_1,SEQ_1,MONOID_0,GROUP_4,PRVECT_1,RLVECT_2,RLVECT_3,FUNCT_7,MATRIX13,MATRIXR2,FINSOP_1,MATRLIN,MATRLIN2,MOD_2,MATRIXJ1,TMAP_1,CKB4,CKB15,CKB27,CKB45,CKB47,CKB57;
definitions TARSKI,SQUARE_1,EUCLID,XCMPLX_0,ALGSTR_0,STRUCT_0,GRCAT_1,TOPREAL9,FINSEQ_1,MATRTOP1,VECTSP_1,MATRIX_7,FVSUM_1,NAT_D,CKB4,CKB15,CKB27,CKB45,CKB47,CKB57;
theorems XREAL_0,TARSKI,FUNCT_2,EUCLID,XBOOLE_1,XBOOLE_0,JORDAN2C,SQUARE_1,XCMPLX_1,ABSVALUE,RVSUM_1,EUCLID_2,ENUMSET1,XREAL_1,XXREAL_0,RLVECT_1,ORDINAL1,GRCAT_1,CARD_1,CARD_2,FINSEQ_1,FINSEQ_2,FINSEQ_3,FUNCT_1,FVSUM_1,LAPLACE,MATRIX_1,MATRIX_2,MATRIX_6,MATRIX13,MATRIXR1,MATRLIN2,MATRTOP1,NAT_1,PARTFUN1,PRE_POLY,RELAT_1,RLSUB_1,RLVECT_2,RLVECT_3,STRUCT_0,TOPREAL7,ZFMISC_1,MATRIXJ1,STIRL2_1,TOPS_2,TOPREAL9,MATRIX_9,SIN_COS,MATRIX_7,MATRIXR2,MATRIX11,MATRIX_3,MATRIX15,RFINSEQ,FINSEQ_7,SIN_COS6,XXREAL_1,GROUP_4,MONOID_0,GROUP_1,FINSEQ_5,TMAP_1,RLVECT_4,FUNCT_7,TOPREALC,VALUED_1,INT_1,FINSOP_1,MOD_2,CKB1,CKB2,CKB3,CKB4,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB51,CKB52,CKB53,CKB57,CKB58;
schemes NAT_1,FINSEQ_4,MATRIX_1;
registrations XBOOLE_0,XXREAL_0,XREAL_0,SQUARE_1,NAT_1,MEMBERED,STRUCT_0,MONOID_0,EUCLID,VALUED_0,FINSEQ_1,FUNCT_1,RELAT_1,TOPREAL9,CARD_1,FINSEQ_2,FINSET_1,FUNCT_2,MATRIX13,MATRIX_2,MATRTOP1,NUMBERS,PRVECT_1,RELSET_1,RLVECT_2,VECTSP_1,XCMPLX_0,SIN_COS,MATRIX11,MATRIXJ1,GRCAT_1,BORSUK_3,FUNCOP_1,MATRIX_1,INT_1,FUNCT_7,PRE_POLY,SUBSET_1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB48,CKB49,CKB50,CKB54,CKB55,CKB56;
constructors REAL_1,SQUARE_1,BORSUK_1,MONOID_0,CONVEX1,TOPREAL9,BINARITH,FVSUM_1,LAPLACE,MATRIX_6,MATRIX11,TOPS_2,MATRIX13,MATRLIN2,MATRTOP1,REALSET1,RLVECT_3,SEQ_1,MATRIXJ1,RCOMP_1,ABIAN,SIN_COS,MATRIX_7,SETWISEO,GROUP_4,TMAP_1,FINSOP_1,MATRIXR2,SEQ_4,CKB4,CKB15,CKB27,CKB45,CKB47,CKB57;
requirements NUMERALS,BOOLE,SUBSET,ARITHM,REAL;
begin
reserve X for set;
reserve r for  real number;
reserve i for Nat;
reserve k for Nat;
reserve m for Nat;
reserve n for Nat;
reserve p for (Point of ( TOP-REAL n ));
reserve f for  homogeneous  additive (Function of ( TOP-REAL n ),( TOP-REAL n ));
theorem
Th29: ((k in X & k in ( Seg n )) implies (ex f st ((f is X -support-yielding  base_rotation & (( card ( X /\ ( Seg n ) ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 ))) & (for i holds ((i in ( X /\ ( Seg n ) ) & i <> k) implies ( ( f . p ) . i ) = ( 0 ))))))
proof
assume that
A1: k in X
and
A2: k in ( Seg n );
set TR = ( TOP-REAL n );
defpred P[ Nat ]
 means
($1 <= n implies (ex f being  base_rotation (Function of TR,TR) st ((f is ( ( X /\ ( Seg $1 ) ) \/ { k } ) -support-yielding & (( card ( ( X /\ ( Seg $1 ) ) \/ { k } ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 ))) & (for i holds ((i in ( X /\ ( Seg $1 ) ) & i <> k) implies ( ( f . p ) . i ) = ( 0 ))))));
A3: (for z being Nat holds (P[ z ] implies P[ ( z + 1 ) ]))
proof
let z being Nat;
set z1 = ( z + 1 );
assume A4: P[ z ];
A5: ( Seg z1 ) = ( ( Seg z ) \/ { z1 } ) by FINSEQ_1:9;
A6: ( Seg z1 ) = ( ( Seg z ) \/ { z1 } ) by FINSEQ_1:9;
A7: (z1 in X implies ( ( ( X /\ ( Seg z ) ) \/ { k } ) \/ { z1,k } ) = ( ( X /\ ( Seg z1 ) ) \/ { k } ))
proof
assume z1 in X;
then A8: ( X \/ { z1 } ) = X by ZFMISC_1:40;
{ z1,k } = ( { z1 } \/ { k } ) by ENUMSET1:1;
hence ( ( ( X /\ ( Seg z ) ) \/ { k } ) \/ { z1,k } ) = ( ( X /\ ( Seg z ) ) \/ ( { k } \/ ( { k } \/ { z1 } ) ) ) by XBOOLE_1:4
.= ( ( X /\ ( Seg z ) ) \/ ( ( { k } \/ { k } ) \/ { z1 } ) ) by XBOOLE_1:4
.= ( ( ( X /\ ( Seg z ) ) \/ { z1 } ) \/ { k } ) by XBOOLE_1:4
.= ( ( X /\ ( Seg z1 ) ) \/ { k } ) by A6,A8,XBOOLE_1:24;
end;
assume A9: z1 <= n;
then consider f being  base_rotation (Function of TR,TR) such that A10: f is ( ( X /\ ( Seg z ) ) \/ { k } ) -support-yielding and A11: (( card ( ( X /\ ( Seg z ) ) \/ { k } ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 )) and A12: (for m holds ((m in ( X /\ ( Seg z ) ) & m <> k) implies ( ( f . p ) . m ) = ( 0 ))) by A4,NAT_1:13;
set z1 = ( z + 1 );
per cases  by XXREAL_0:1;
suppose A13: z1 = k;

take f;
( ( Seg z1 ) \/ { z1 } ) = ( ( Seg z ) \/ ( { z1 } \/ { z1 } ) ) by A5,XBOOLE_1:4
.= ( ( Seg z ) \/ { z1 } );
then A14: ( ( X /\ ( Seg z1 ) ) \/ { k } ) = ( ( X \/ { k } ) /\ ( ( Seg z ) \/ { k } ) ) by A13,XBOOLE_1:24
.= ( ( X /\ ( Seg z ) ) \/ { k } ) by XBOOLE_1:24;
hence f is ( ( X /\ ( Seg z1 ) ) \/ { k } ) -support-yielding by A10;
thus (( card ( ( X /\ ( Seg z1 ) ) \/ { k } ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 )) by A11,A14;
let m;
assume that
A15: m in ( X /\ ( Seg z1 ) )
and
A16: m <> k;
A17: m in ( Seg z1 ) by A15,XBOOLE_0:def 4;
A18: m in X by A15,XBOOLE_0:def 4;
(not m in { z1 }) by A13,A16,TARSKI:def 1;
then m in ( Seg z ) by A5,A17,XBOOLE_0:def 3;
then m in ( X /\ ( Seg z ) ) by A18,XBOOLE_0:def 4;
hence ( ( f . p ) . m ) = ( 0 ) by A12,A16;
end;
suppose A19: (not z1 in X);

take f;
A20: { z1 } misses X by A19,ZFMISC_1:50;
A21: ( X /\ ( Seg z1 ) ) = ( ( X /\ ( Seg z ) ) \/ ( X /\ { z1 } ) ) by A5,XBOOLE_1:23
.= ( ( X /\ ( Seg z ) ) \/ ( {} ) ) by A20,XBOOLE_0:def 7
.= ( X /\ ( Seg z ) );
hence f is ( ( X /\ ( Seg z1 ) ) \/ { k } ) -support-yielding by A10;
thus (( card ( ( X /\ ( Seg z1 ) ) \/ { k } ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 )) by A11,A21;
let m;
assume that
A22: m in ( X /\ ( Seg z1 ) )
and
A23: m <> k;
A24: m in ( Seg z1 ) by A22,XBOOLE_0:def 4;
A25: m in X by A22,XBOOLE_0:def 4;
then (not m in { z1 }) by A19,TARSKI:def 1;
then m in ( Seg z ) by A5,A24,XBOOLE_0:def 3;
then m in ( X /\ ( Seg z ) ) by A25,XBOOLE_0:def 4;
hence ( ( f . p ) . m ) = ( 0 ) by A12,A23;
end;
suppose A26: (z1 < k & z1 in X);

set fp = ( f . p );
set S = ( ( ( fp . z1 ) ^2 ) + ( ( fp . k ) ^2 ) );
A27: (z1 >= 1 & k <= n) by A2,FINSEQ_1:1,NAT_1:11;
A28: (( ( fp . k ) ^2 ) >= ( 0 ) & ( ( fp . z1 ) ^2 ) >= ( 0 )) by XREAL_1:63;
then A29: ( ( sqrt S ) ^2 ) = S by SQUARE_1:def 2;
then consider r such that A30: ( ( ( Mx2Tran ( Rotation (z1,k,n,r) ) ) . fp ) . k ) = ( sqrt S ) by A26,A27,CKB43:1;
reconsider M = ( Mx2Tran ( Rotation (z1,k,n,r) ) ) as  base_rotation (Function of TR,TR) by A26,A27,CKB52:1;
take Mf = ( M * f );
A31: M is { z1,k } -support-yielding by A26,A27,CKB44:1;
hence Mf is ( ( X /\ ( Seg z1 ) ) \/ { k } ) -support-yielding by A7,A10,A26;
A32: ( dom Mf ) = (the carrier of TR) by FUNCT_2:52;
then A33: fp in ( dom M ) by FUNCT_1:11;
A34: ( Mf . p ) = ( M . fp ) by A32,FUNCT_1:12;
hence (( card ( ( X /\ ( Seg z1 ) ) \/ { k } ) ) > 1 implies ( ( Mf . p ) . k ) >= ( 0 )) by A28,A30,SQUARE_1:def 2;
let i;
assume that
A35: i in ( X /\ ( Seg z1 ) )
and
A36: i <> k;
A37: i in X by A35,XBOOLE_0:def 4;
i in ( Seg z1 ) by A35,XBOOLE_0:def 4;
then A38: (i in ( Seg z ) or i in { z1 }) by A5,XBOOLE_0:def 3;
per cases  by A38,TARSKI:def 1;
suppose A39: i in ( Seg z );

then A40: i in ( X /\ ( Seg z ) ) by A37,XBOOLE_0:def 4;
i <= z by A39,FINSEQ_1:1;
then i < z1 by NAT_1:13;
then (not i in { z1,k }) by A36,TARSKI:def 2;
hence ( ( Mf . p ) . i ) = ( fp . i ) by A31,A33,A34,CKB4:def 1
.= ( 0 ) by A12,A36,A40;
end;
suppose i = z1;

then A41: ( ( ( ( M . fp ) . i ) * ( ( M . fp ) . i ) ) + S ) = S by A26,A27,A29,A30,CKB42:1;
thus ( ( Mf . p ) . i ) = ( ( M . fp ) . i ) by A32,FUNCT_1:12
.= ( 0 ) by A41;
end;
end;
suppose A42: (z1 > k & z1 in X);

set fp = ( f . p );
set S = ( ( ( fp . z1 ) ^2 ) + ( ( fp . k ) ^2 ) );
A43: 1 <= k by A2,FINSEQ_1:1;
A44: (( ( fp . k ) ^2 ) >= ( 0 ) & ( ( fp . z1 ) ^2 ) >= ( 0 )) by XREAL_1:63;
then A45: ( ( sqrt S ) ^2 ) = S by SQUARE_1:def 2;
then consider r such that A46: ( ( ( Mx2Tran ( Rotation (k,z1,n,r) ) ) . fp ) . k ) = ( sqrt S ) by A9,A42,A43,CKB41:1;
reconsider M = ( Mx2Tran ( Rotation (k,z1,n,r) ) ) as  base_rotation (Function of TR,TR) by A9,A42,A43,CKB52:1;
take Mf = ( M * f );
A47: M is { k,z1 } -support-yielding by A9,A42,A43,CKB44:1;
hence Mf is ( ( X /\ ( Seg z1 ) ) \/ { k } ) -support-yielding by A7,A10,A42;
A48: ( dom Mf ) = (the carrier of TR) by FUNCT_2:52;
then A49: ( Mf . p ) = ( M . fp ) by FUNCT_1:12;
hence (( card ( ( X /\ ( Seg z1 ) ) \/ { k } ) ) > 1 implies ( ( Mf . p ) . k ) >= ( 0 )) by A44,A46,SQUARE_1:def 2;
let i;
assume that
A50: i in ( X /\ ( Seg z1 ) )
and
A51: i <> k;
A52: i in X by A50,XBOOLE_0:def 4;
i in ( Seg z1 ) by A50,XBOOLE_0:def 4;
then A53: (i in ( Seg z ) or i in { z1 }) by A5,XBOOLE_0:def 3;
per cases  by A53,TARSKI:def 1;
suppose A54: i in ( Seg z );

then i <= z by FINSEQ_1:1;
then i < z1 by NAT_1:13;
then A55: (not i in { z1,k }) by A51,TARSKI:def 2;
A56: i in ( X /\ ( Seg z ) ) by A52,A54,XBOOLE_0:def 4;
fp in ( dom M ) by A48,FUNCT_1:11;
hence ( ( Mf . p ) . i ) = ( fp . i ) by A47,A49,A55,CKB4:def 1
.= ( 0 ) by A12,A51,A56;
end;
suppose i = z1;

then A57: ( ( ( ( M . fp ) . i ) * ( ( M . fp ) . i ) ) + S ) = S by A9,A42,A43,A45,A46,CKB42:1;
thus ( ( Mf . p ) . i ) = ( ( M . fp ) . i ) by A48,FUNCT_1:12
.= ( 0 ) by A57;
end;
end;
end;
A58: P[ ( 0 ) ]
proof
assume ( 0 ) <= n;
take f = ( id TR );
A59: f is ( {} ) -support-yielding
proof
let F being Function;
let x being set;
assume that
A60: F in ( dom f )
and
A61: ( ( f . F ) . x ) <> ( F . x );
F in (the carrier of TR) by A60,FUNCT_1:17;
hence thesis by A61,FUNCT_1:17;
end;
( {} ) c= ( ( X /\ ( Seg ( 0 ) ) ) \/ { k } ) by XBOOLE_1:2;
hence f is ( ( X /\ ( Seg ( 0 ) ) ) \/ { k } ) -support-yielding by A59;
thus (( card ( ( X /\ ( Seg ( 0 ) ) ) \/ { k } ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 )) by CARD_2:42;
let m;
assume m in ( X /\ ( Seg ( 0 ) ) );
hence thesis;
end;
(for z being Nat holds P[ z ]) from NAT_1:sch 2(A58,A3);
then consider f being  base_rotation (Function of TR,TR) such that A62: ((f is ( ( X /\ ( Seg n ) ) \/ { k } ) -support-yielding & (( card ( ( X /\ ( Seg n ) ) \/ { k } ) ) > 1 implies ( ( f . p ) . k ) >= ( 0 ))) & (for i holds ((i in ( X /\ ( Seg n ) ) & i <> k) implies ( ( f . p ) . i ) = ( 0 ))));
take f;
A63: ( X /\ ( Seg n ) ) c= X by XBOOLE_1:17;
({ k } c= X & { k } c= ( Seg n )) by A1,A2,ZFMISC_1:31;
then ( ( X /\ ( Seg n ) ) \/ { k } ) = ( X /\ ( Seg n ) ) by XBOOLE_1:12,XBOOLE_1:19;
hence thesis by A62,A63;
end;
