environ
vocabularies XBOOLE_0,PROB_1,SUBSET_1,SETFAM_1,NUMBERS,RELAT_1,FUNCT_1,FINSET_1,ARYTM_3,ORDINAL1,CARD_1,FUNCT_7,CARD_3,TARSKI,ZFMISC_1,PROB_2,XXREAL_0,MSSUBFAM,NAT_1,EQREL_1,DYNKIN,FINSUB_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,FINSET_1,CARD_1,NUMBERS,SETFAM_1,RELAT_1,FUNCT_1,FUNCT_2,NAT_1,FUNCT_7,CARD_3,PROB_1,FINSUB_1,PROB_2,XXREAL_0,CKB5,CKB7,CKB8,CKB10,CKB11,CKB12;
definitions SUBSET_1,CARD_1,ORDINAL1,CARD_3,CKB7,CKB8,CKB11,CKB12;
theorems TARSKI,FUNCT_1,ZFMISC_1,FUNCT_2,SUBSET_1,NAT_1,RELAT_1,SETFAM_1,PROB_2,FINSUB_1,XBOOLE_0,XBOOLE_1,PROB_1,ORDINAL1,XXREAL_0,FUNCT_7,MEASURE1,CKB1,CKB2,CKB4,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17;
schemes FUNCT_2,NAT_1,FINSET_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,ORDINAL1,RELSET_1,FINSET_1,XREAL_0,FUNCT_7,CKB3;
constructors SETFAM_1,FINSUB_1,NAT_1,PROB_2,XREAL_0,FUNCT_7,ENUMSET1,RELSET_1,CKB5,CKB7,CKB8,CKB11,CKB12;
requirements NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve Omega for non  empty set;
reserve f for (SetSequence of Omega);
reserve X for (Subset of Omega);
reserve z for set;
reserve u for set;
reserve v for set;
theorem
Th13: (for f being (SetSequence of Omega) holds (for X being (Subset of Omega) holds ( X /\ ( Union f ) ) = ( Union ( seqIntersection (X,f) ) )))
proof
let f being (SetSequence of Omega);
let X being (Subset of Omega);
A1: ( dom f ) = ( NAT ) by FUNCT_2:def 1;
now
reconsider g = ( seqIntersection (X,f) ) as (SetSequence of Omega);
let z;
assume z in ( Union ( seqIntersection (X,f) ) );
then consider u such that A2: z in u and A3: u in ( rng g ) by TARSKI:def 4;
consider v such that A4: v in ( dom g ) and A5: u = ( g . v ) by A3,FUNCT_1:def 3;
reconsider n = v as (Element of ( NAT )) by A4,FUNCT_2:def 1;
A6: z in ( X /\ ( f . n ) ) by A2,A5,CKB7:def 1;
then A7: z in X by XBOOLE_0:def 4;
A8: ( f . n ) in ( rng f ) by A1,FUNCT_1:def 3;
z in ( f . n ) by A6,XBOOLE_0:def 4;
then z in ( Union f ) by A8,TARSKI:def 4;
hence z in ( X /\ ( Union f ) ) by A7,XBOOLE_0:def 4;
end;
then A9: ( Union ( seqIntersection (X,f) ) ) c= ( X /\ ( Union f ) ) by TARSKI:def 3;
A10: ( dom ( seqIntersection (X,f) ) ) = ( NAT ) by FUNCT_2:def 1;
now
let z;
assume A11: z in ( X /\ ( Union f ) );
then z in ( union ( rng f ) ) by XBOOLE_0:def 4;
then consider u such that A12: z in u and A13: u in ( rng f ) by TARSKI:def 4;
consider v such that A14: v in ( dom f ) and A15: u = ( f . v ) by A13,FUNCT_1:def 3;
reconsider n = v as (Element of ( NAT )) by A14,FUNCT_2:def 1;
( X /\ ( f . n ) ) = ( ( seqIntersection (X,f) ) . n ) by CKB7:def 1;
then A16: ( X /\ ( f . n ) ) in ( rng ( seqIntersection (X,f) ) ) by A10,FUNCT_1:def 3;
z in X by A11,XBOOLE_0:def 4;
then z in ( X /\ ( f . n ) ) by A12,A15,XBOOLE_0:def 4;
hence z in ( Union ( seqIntersection (X,f) ) ) by A16,TARSKI:def 4;
end;
then ( X /\ ( Union f ) ) c= ( Union ( seqIntersection (X,f) ) ) by TARSKI:def 3;
hence thesis by A9,XBOOLE_0:def 10;
end;
