environ
vocabularies ANALMETR,SUBSET_1,SYMSP_1,AFF_2,VECTSP_1,TRANSGEO,ANALOAF,DIRAF,STRUCT_0,AFF_1,INCSP_1,CONAFFM,CONMETR,RLVECT_1,ARYTM_1,ARYTM_3,REAL_1,RELAT_1,CARD_1,MCART_1,SUPINF_2,PARSP_1,EUCLMETR;
notations SUBSET_1,NUMBERS,STRUCT_0,REAL_1,RLVECT_1,ANALOAF,DIRAF,AFF_1,AFF_2,ANALMETR,GEOMTRAP,PAPDESAF,CONMETR,CONAFFM,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
definitions RLVECT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
theorems RLVECT_1,AFF_1,AFF_4,AFPROJ,ANALOAF,ANALMETR,GEOMTRAP,PAPDESAF,CONMETR,CONAFFM,AFF_2,RLSUB_2,XCMPLX_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36;
registrations ANALMETR,PAPDESAF,REAL_1,ORDINAL1,XREAL_0,STRUCT_0;
constructors REAL_1,AFF_1,AFF_2,TRANSLAC,GEOMTRAP,CONAFFM,CONMETR,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
requirements NUMERALS,SUBSET,ARITHM,BOOLE;
begin
reserve V for RealLinearSpace;
reserve w for (VECTOR of V);
reserve y for (VECTOR of V);
registration
cluster  Euclidean  Pappian  Desarguesian  Homogeneous  translation  Fanoian  Moufangian for OrtAfPl;
existence
proof
consider V such that A1: (ex w st (ex y st  Gen w,y)) by ANALMETR:3;
consider w,y such that A2:  Gen w,y by A1;
reconsider MS = ( AMSpace (V,w,y) ) as OrtAfPl by A2,ANALMETR:34;
A3: MS is  satisfying_3H by A2,CKB34:1,CONAFFM:6;
(for a,b being Real holds (( ( a * w ) + ( b * y ) ) = ( 0. V ) implies (a = ( 0 ) & b = ( 0 )))) by A2,ANALMETR:def 1;
then reconsider OAS = ( OASpace V ) as OAffinSpace by ANALOAF:26;
take MS;
A4: ( Af MS ) = ( Lambda OAS ) by ANALMETR:20;
then A5: (( Af MS ) is  Moufangian & ( Af MS ) is  translational) by PAPDESAF:16,PAPDESAF:17;
(( Af MS ) is  Pappian & ( Af MS ) is  Desarguesian) by A4,PAPDESAF:13,PAPDESAF:14;
hence thesis by A2,A3,A4,A5,CKB2:def 1,CKB3:def 1,CKB4:def 1,CKB5:def 1,CKB6:def 1,CKB15:1,CKB36:1;
end;
end;
