environ
vocabularies NUMBERS,SUBSET_1,REAL_1,FINSEQ_1,RELAT_1,ZFMISC_1,XBOOLE_0,ARYTM_3,CARD_1,ARYTM_1,ABIAN,EUCLID,XXREAL_0,PARTFUN1,FUNCT_1,TOPREAL1,GOBOARD5,NAT_1,RLTOPSP1,GRAPH_2,TARSKI,STRUCT_0,PRE_TOPC,SETFAM_1,FINSET_1,CONNSP_1,GOBOARD9,RELAT_2,GOBOARD1,MCART_1,CONVEX1,TREES_1,GOBOARD2,FINSEQ_5,SPPOL_1,MATRIX_1,TOPS_1,INT_1,JORDAN12;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,RELAT_1,CARD_1,NUMBERS,XCMPLX_0,REAL_1,NAT_1,NAT_D,ABIAN,INT_1,GRAPH_2,FINSET_1,FUNCT_1,PARTFUN1,FINSEQ_1,MATRIX_1,STRUCT_0,PRE_TOPC,TOPS_1,CONNSP_1,RLTOPSP1,EUCLID,TOPREAL1,SPPOL_1,GOBOARD1,GOBOARD2,GOBOARD5,GOBOARD9,GOBRD13,XXREAL_0,CKB9,CKB10;
definitions XBOOLE_0,TARSKI,GOBOARD5,TOPREAL1,JORDAN1,SUBSET_1,CKB9,CKB10;
theorems SPPOL_1,XBOOLE_0,TOPREAL1,JORDAN4,TARSKI,SPPOL_2,FUNCT_1,FINSEQ_4,FINSEQ_1,NAT_1,SETFAM_1,FINSET_1,CARD_2,RELAT_1,TOPREAL3,GOBOARD9,CARD_1,SUBSET_1,GOBRD14,JORDAN1H,GOBRD12,JORDAN9,XBOOLE_1,JORDAN1,GOBOARD5,JORDAN8,GOBRD13,GOBOARD6,EUCLID,GOBOARD7,TOPS_1,NAT_2,JORDAN1G,SPRECT_3,JORDAN1J,FINSEQ_5,GOBRD11,TOPREAL6,GOBOARD2,REALSET1,TOPREAL8,GRAPH_2,FINSEQ_3,JORDAN5B,XREAL_1,XXREAL_0,PARTFUN1,ORDINAL1,MATRIX_1,XREAL_0,NAT_D,ZFMISC_1,RLTOPSP1,SEQ_4,CKB1,CKB2,CKB3,CKB4,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21;
schemes FRAENKEL,NAT_1;
registrations SUBSET_1,RELSET_1,XREAL_0,INT_1,MEMBERED,ABIAN,GOBOARD2,SPPOL_2,GOBOARD5,GOBOARD9,JORDAN10,FUNCT_1,RELAT_1,ZFMISC_1,EUCLID,FINSET_1,FINSEQ_1,CKB6;
constructors SETFAM_1,XXREAL_0,NAT_1,NAT_D,ABIAN,TOPS_1,CONNSP_1,COMPTS_1,GOBOARD2,SPPOL_1,JORDAN1,GRAPH_2,GOBOARD9,GOBRD13,XXREAL_2,RELSET_1,CONVEX1,CKB9,CKB10;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve a for set;
reserve b for set;
reserve c for set;
reserve f for non  constant  standard special_circular_sequence;
theorem
Th18: (for f holds (for a holds (for b holds (for c holds (((((a in ( ( L~ f ) ` ) & b in ( ( L~ f ) ` )) & c in ( ( L~ f ) ` )) & (not (ex C being (Subset of ( TOP-REAL 2 )) st ((C is_a_component_of ( ( L~ f ) ` ) & a in C) & b in C)))) & (not (ex C being (Subset of ( TOP-REAL 2 )) st ((C is_a_component_of ( ( L~ f ) ` ) & b in C) & c in C)))) implies (ex C being (Subset of ( TOP-REAL 2 )) st ((C is_a_component_of ( ( L~ f ) ` ) & a in C) & c in C)))))))
proof
let f;
let a;
let b;
let c;
assume that
A1: a in ( ( L~ f ) ` )
and
A2: b in ( ( L~ f ) ` )
and
A3: c in ( ( L~ f ) ` )
and
A4: (not (ex C being (Subset of ( TOP-REAL 2 )) st ((C is_a_component_of ( ( L~ f ) ` ) & a in C) & b in C)))
and
A5: (not (ex C being (Subset of ( TOP-REAL 2 )) st ((C is_a_component_of ( ( L~ f ) ` ) & b in C) & c in C)));
A6: ( LeftComp f ) is_a_component_of ( ( L~ f ) ` ) by GOBOARD9:def 1;
A7: ( RightComp f ) is_a_component_of ( ( L~ f ) ` ) by GOBOARD9:def 2;
per cases  by A1,A2,A4,CKB20:1;
suppose A8: (a in ( LeftComp f ) & b in ( RightComp f ));

now
per cases  by A2,A3,A5,CKB20:1;
suppose (b in ( LeftComp f ) & c in ( RightComp f ));

then ( LeftComp f ) meets ( RightComp f ) by A8,XBOOLE_0:3;
hence thesis by GOBRD14:14;
end;
suppose (b in ( RightComp f ) & c in ( LeftComp f ));

hence thesis by A6,A8;
end;
end;
hence thesis;
end;
suppose A9: (a in ( RightComp f ) & b in ( LeftComp f ));

now
per cases  by A2,A3,A5,CKB20:1;
suppose (b in ( RightComp f ) & c in ( LeftComp f ));

then ( LeftComp f ) meets ( RightComp f ) by A9,XBOOLE_0:3;
hence thesis by GOBRD14:14;
end;
suppose (b in ( LeftComp f ) & c in ( RightComp f ));

hence thesis by A7,A9;
end;
end;
hence thesis;
end;
end;
