environ
vocabularies NUMBERS,ORDERS_2,XREAL_0,STRUCT_0,TARSKI,ORDINAL1,XXREAL_0,MEASURE5,XXREAL_1,XBOOLE_0,SUBSET_1,CARD_1,RELAT_2,LATTICE3,EQREL_1,LATTICES,XXREAL_2,YELLOW_0,REAL_1,INTEGRA1,SEQ_4,REWRITE1,TREES_2,LATTICE2,WAYBEL_0,RELAT_1,FUNCT_1,ORDINAL2,YELLOW_1,WAYBEL_3,PBOOLE,CARD_3,WAYBEL_1,NEWTON,FUNCOP_1,FUNCT_2,MONOID_0,FUZZY_1,PARTFUN1,QC_LANG1,FUZZY_2,VALUED_1,ZFMISC_1,LFUZZY_0;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,FUNCT_1,FUNCT_2,BINOP_1,DOMAIN_1,ORDINAL1,PARTFUN1,SUBSET_1,NUMBERS,XXREAL_2,XREAL_0,REAL_1,SEQ_4,RCOMP_1,RELSET_1,STRUCT_0,ORDERS_2,PBOOLE,MONOID_0,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_1,WAYBEL_1,WAYBEL_3,FUZZY_1,FUZZY_2,FUZZY_4,MEASURE5,INTEGRA1,FUNCOP_1,XXREAL_0,CKB1,CKB2,CKB9,CKB11,CKB12,CKB13,CKB14,CKB18,CKB19,CKB40,CKB46,CKB48,CKB49,CKB50,CKB51;
definitions TARSKI,XBOOLE_0,RELAT_1,STRUCT_0,LATTICE3,YELLOW_0,WAYBEL_0,WAYBEL_1,BINOP_1,CKB1,CKB2,CKB9,CKB40,CKB46,CKB48;
theorems ZFMISC_1,ORDERS_2,WAYBEL_1,FUNCT_1,XBOOLE_1,LATTICE3,YELLOW_0,INTEGRA1,XREAL_0,XBOOLE_0,TARSKI,SEQ_4,JORDAN5A,FUNCT_2,YELLOW_2,WAYBEL_3,YELLOW_3,CARD_3,YELLOW_1,FUNCOP_1,FUZZY_2,FUZZY_4,FUNCT_3,FUZZY_1,PARTFUN1,MONOID_0,WAYBEL_0,XXREAL_0,XXREAL_1,XXREAL_2,RELSET_1,RELAT_1,MEASURE5,CKB1,CKB2,CKB5,CKB7,CKB9,CKB15,CKB23,CKB24,CKB25,CKB26,CKB28,CKB34,CKB35,CKB36,CKB37,CKB38,CKB40,CKB41,CKB42,CKB44,CKB45,CKB46,CKB47,CKB48,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57;
schemes YELLOW_0,PBOOLE,YELLOW_3,FRAENKEL;
registrations SUBSET_1,RELSET_1,NUMBERS,XREAL_0,MEMBERED,STRUCT_0,LATTICE3,YELLOW_0,MONOID_0,YELLOW_1,WAYBEL_1,WAYBEL_2,WAYBEL_3,WAYBEL10,WAYBEL17,ORDERS_4,PRE_CIRC,ORDERS_2,FUNCOP_1,MEASURE5,CKB3,CKB4,CKB6,CKB8,CKB10,CKB16,CKB17,CKB20,CKB27,CKB29,CKB30,CKB31,CKB32,CKB33,CKB39,CKB43,CKB21,CKB22;
constructors DOMAIN_1,SQUARE_1,LATTICE3,MONOID_0,PSCOMP_1,ORDERS_3,WAYBEL_1,WAYBEL_3,INTEGRA1,FUZZY_4,SEQ_1,XXREAL_2,SEQ_4,RELSET_1,FUZZY_1,BINOP_2,RVSUM_1,CKB1,CKB2,CKB9,CKB18,CKB19,CKB40,CKB46,CKB48,CKB49,CKB50,CKB51;
requirements BOOLE,SUBSET,NUMERALS,REAL;
begin
reserve x for  real number;
reserve R for  real non  empty RelStr;
reserve a for (Element of R);
reserve b for (Element of R);
scheme SupDistributivity { L() ->  complete LATTICE,X,Y() -> non  empty set,F(set,set) -> (Element of L()),P,Q[set] } : ( "\/" ({ ( "\/" ({ F(x,y) where y is (Element of Y()): Q[ y ] },L()) ) where x is (Element of X()): P[ x ] },L()) ) = ( "\/" ({ F(x,y) where x is (Element of X()),y is (Element of Y()): (P[ x ] & Q[ y ]) },L()) )
proof
defpred R[ set ]
 means
(ex x being (Element of X()) st (P[ x ] & (for a being set holds (a in $1 iff (ex y being (Element of Y()) st (a = F(x,y) & Q[ y ]))))));
A1: ( "\/" ({ ( "\/" (A,L()) ) where A is (Subset of L()): R[ A ] },L()) ) = ( "\/" (( union { A where A is (Subset of L()): R[ A ] } ),L()) ) from YELLOW_3:sch 5;
A2: { F(x,y) where x is (Element of X()),y is (Element of Y()): (P[ x ] & Q[ y ]) } c= ( union { A where A is (Subset of L()): R[ A ] } )
proof
let a being set;
assume a in { F(x,y) where x is (Element of X()),y is (Element of Y()): (P[ x ] & Q[ y ]) };
then consider x being (Element of X()),y being (Element of Y()) such that A3: a = F(x,y) and A4: P[ x ] and A5: Q[ y ];
set A1 = { F(x,y9) where y9 is (Element of Y()): Q[ y9 ] };
A1 c= (the carrier of L())
proof
let b being set;
assume b in A1;
then (ex y9 being (Element of Y()) st (b = F(x,y9) & Q[ y9 ]));
hence thesis;
end;
then reconsider A1 as (Subset of L());
R[ A1 ]
proof
take x;
thus P[ x ] by A4;
let a being set;
thus thesis;
end;
then A6: A1 in { A where A is (Subset of L()): R[ A ] };
a in A1 by A3,A5;
hence thesis by A6,TARSKI:def 4;
end;
A7: { ( "\/" ({ F(x,y) where y is (Element of Y()): Q[ y ] },L()) ) where x is (Element of X()): P[ x ] } c= { ( "\/" (A,L()) ) where A is (Subset of L()): R[ A ] }
proof
let a being set;
assume a in { ( "\/" ({ F(x,y) where y is (Element of Y()): Q[ y ] },L()) ) where x is (Element of X()): P[ x ] };
then consider x being (Element of X()) such that A8: a = ( "\/" ({ F(x,y) where y is (Element of Y()): Q[ y ] },L()) ) and A9: P[ x ];
(ex A1 being (Subset of L()) st (a = ( "\/" (A1,L()) ) & R[ A1 ]))
proof
set A2 = { F(x,y) where y is (Element of Y()): Q[ y ] };
A2 c= (the carrier of L())
proof
let b being set;
assume b in A2;
then (ex y being (Element of Y()) st (b = F(x,y) & Q[ y ]));
hence thesis;
end;
then reconsider A1 = A2 as (Subset of L());
R[ A1 ]
proof
take x;
thus P[ x ] by A9;
thus thesis;
end;
hence thesis by A8;
end;
hence thesis;
end;
A10: { ( "\/" (A,L()) ) where A is (Subset of L()): R[ A ] } c= { ( "\/" ({ F(x,y) where y is (Element of Y()): Q[ y ] },L()) ) where x is (Element of X()): P[ x ] }
proof
let a being set;
assume a in { ( "\/" (A,L()) ) where A is (Subset of L()): R[ A ] };
then consider A1 being (Subset of L()) such that A11: a = ( "\/" (A1,L()) ) and A12: R[ A1 ];
consider x being (Element of X()) such that A13: P[ x ] and A14: (for a being set holds (a in A1 iff (ex y being (Element of Y()) st (a = F(x,y) & Q[ y ])))) by A12;
now
let a being set;
(a in { F(x,y) where y is (Element of Y()): Q[ y ] } iff (ex y being (Element of Y()) st (a = F(x,y) & Q[ y ])));
hence (a in A1 iff a in { F(x,y) where y is (Element of Y()): Q[ y ] }) by A14;
end;
then A1 = { F(x,y) where y is (Element of Y()): Q[ y ] } by TARSKI:1;
hence thesis by A11,A13;
end;
( union { A where A is (Subset of L()): R[ A ] } ) c= { F(x,y) where x is (Element of X()),y is (Element of Y()): (P[ x ] & Q[ y ]) }
proof
let a being set;
assume a in ( union { A where A is (Subset of L()): R[ A ] } );
then consider A1 being set such that A15: a in A1 and A16: A1 in { A where A is (Subset of L()): R[ A ] } by TARSKI:def 4;
consider A2 being (Subset of L()) such that A17: A1 = A2 and A18: R[ A2 ] by A16;
consider x being (Element of X()) such that A19: P[ x ] and A20: (for a being set holds (a in A2 iff (ex y being (Element of Y()) st (a = F(x,y) & Q[ y ])))) by A18;
(ex y being (Element of Y()) st (a = F(x,y) & Q[ y ])) by A15,A17,A20;
hence thesis by A19;
end;
then ( union { A where A is (Subset of L()): R[ A ] } ) = { F(x,y) where x is (Element of X()),y is (Element of Y()): (P[ x ] & Q[ y ]) } by A2,XBOOLE_0:def 10;
hence thesis by A1,A10,A7,XBOOLE_0:def 10;
end;
