environ
vocabularies BHSP_1,RLSUB_1,ARYTM_3,STRUCT_0,RLVECT_1,SUBSET_1,TARSKI,SUPINF_2,XBOOLE_0,ARYTM_1,RLSUB_2,ZFMISC_1,FUNCT_1,RELAT_1,REAL_1,CARD_1,FINSEQ_4,MCART_1,BINOP_1,LATTICES,EQREL_1,PBOOLE;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,STRUCT_0,FUNCT_1,NUMBERS,BINOP_1,LATTICES,RELSET_1,REAL_1,DOMAIN_1,RLVECT_1,RLSUB_1,BHSP_1,RUSUB_1,CKB1,CKB2,CKB46,CKB49,CKB53,CKB71,CKB79,CKB80;
definitions TARSKI,XBOOLE_0,RLVECT_1,CKB1,CKB2,CKB46,CKB49,CKB53,CKB71,CKB79,CKB80;
theorems RLVECT_1,FUNCT_1,TARSKI,ZFMISC_1,XBOOLE_0,RELAT_1,RLSUB_1,XBOOLE_1,RUSUB_1,RLSUB_2,MCART_1,BINOP_1,LATTICES,XCMPLX_0,ORDERS_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB83,CKB84,CKB85;
schemes XBOOLE_0,FUNCT_1,RELSET_1,ORDERS_1,BINOP_1,CLASSES1;
registrations SUBSET_1,RELSET_1,MEMBERED,STRUCT_0,LATTICES,BHSP_1,RUSUB_1,RELAT_1,CKB47,CKB54,CKB82;
constructors BINOP_1,REAL_1,MEMBERED,REALSET1,LATTICES,RLSUB_1,RUSUB_1,CKB1,CKB2,CKB46,CKB49,CKB53,CKB71,CKB79,CKB80;
requirements NUMERALS,SUBSET,BOOLE;
begin
theorem
Th58: (for V being RealUnitarySpace holds LattStr (# ( Subspaces V ),( SubJoin V ),( SubMeet V ) #) is  modular)
proof
let V being RealUnitarySpace;
set S = LattStr (# ( Subspaces V ),( SubJoin V ),( SubMeet V ) #);
(for A,B,C being (Element of S) holds (A [= C implies ( A "\/" ( B "/\" C ) ) = ( ( A "\/" B ) "/\" C )))
proof
let A being (Element of S),B being (Element of S),C being (Element of S);
reconsider W1 = A,W2 = B,W3 = C as  strict (Subspace of V) by CKB46:def 1;
assume A1: A [= C;
reconsider AB = ( W1 + W2 ) as (Element of S) by CKB46:def 1;
reconsider BC = ( W2 /\ W3 ) as (Element of S) by CKB46:def 1;
( W1 + W3 ) = ( ( SubJoin V ) . (A,C) ) by CKB79:def 1
.= ( A "\/" C ) by LATTICES:def 1
.= W3 by A1,LATTICES:def 3;
then A2: W1 is (Subspace of W3) by CKB13:1;
thus ( A "\/" ( B "/\" C ) ) = ( ( SubJoin V ) . (A,( B "/\" C )) ) by LATTICES:def 1
.= ( ( SubJoin V ) . (A,( ( SubMeet V ) . (B,C) )) ) by LATTICES:def 2
.= ( ( SubJoin V ) . (A,BC) ) by CKB80:def 1
.= ( W1 + ( W2 /\ W3 ) ) by CKB79:def 1
.= ( ( W1 + W2 ) /\ W3 ) by A2,CKB42:1
.= ( ( SubMeet V ) . (AB,C) ) by CKB80:def 1
.= ( ( SubMeet V ) . (( ( SubJoin V ) . (A,B) ),C) ) by CKB79:def 1
.= ( ( SubMeet V ) . (( A "\/" B ),C) ) by LATTICES:def 1
.= ( ( A "\/" B ) "/\" C ) by LATTICES:def 2;
end;
hence thesis by LATTICES:def 12;
end;
