environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,AFINSQ_1,NAT_1,FINSEQ_1,RELAT_1,ORDINAL4,FUNCT_1,ARYTM_3,XXREAL_0,CARD_1,ARYTM_1,REWRITE1,STRUCT_0,FSM_1,ZFMISC_1,FINSET_1,REWRITE2,PRELAMB,TARSKI,MCART_1,REWRITE3;
notations TARSKI,XBOOLE_0,ZFMISC_1,XCMPLX_0,NAT_1,FUNCT_1,RELSET_1,XXREAL_0,FINSET_1,RELAT_1,AFINSQ_1,SUBSET_1,REWRITE1,CATALAN2,FLANG_1,STRUCT_0,NUMBERS,MCART_1,FINSEQ_1,CKB14,CKB15,CKB18;
definitions TARSKI,STRUCT_0,CKB15,CKB18;
theorems AFINSQ_1,CALCUL_1,FLANG_1,FLANG_2,FUNCT_1,NAT_1,RELAT_1,RELSET_1,REWRITE1,STRUCT_0,TARSKI,XREAL_1,XXREAL_0,ZFMISC_1,FINSEQ_1,FINSEQ_2,FINSEQ_3,MCART_1,REWRITE2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB15,CKB16,CKB18;
schemes FINSEQ_1,NAT_1,RELSET_1;
registrations CARD_1,RELSET_1,NAT_1,XREAL_0,XBOOLE_0,MEMBERED,XXREAL_0,STRUCT_0,SUBSET_1,REWRITE1,AFINSQ_1,RELAT_1,FUNCT_1,FINSEQ_1,CATALAN2,CKB14,CKB17;
constructors XXREAL_0,NAT_1,FSM_1,MEMBERED,REWRITE1,FLANG_1,XREAL_0,RELSET_1,CKB14,CKB15,CKB18;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve x for set;
reserve y for set;
reserve z for set;
reserve X for set;
theorem
Th15: (for TS being transition-system over X holds (x,y -->. z,TS implies (((((x in TS & y in X) & z in TS) & x in ( dom ( dom (the Tran of TS) ) )) & y in ( rng ( dom (the Tran of TS) ) )) & z in ( rng (the Tran of TS) ))))
proof
let TS being transition-system over X;
assume x,y -->. z,TS;
then A1: [ [ x,y ],z ] in (the Tran of TS) by CKB18:def 1;
then [ x,y ] in [: (the carrier of TS),X :] by ZFMISC_1:87;
hence ((x in (the carrier of TS) & y in X) & z in (the carrier of TS)) by A1,ZFMISC_1:87;
[ x,y ] in ( dom (the Tran of TS) ) by A1,RELAT_1:6;
hence (x in ( dom ( dom (the Tran of TS) ) ) & y in ( rng ( dom (the Tran of TS) ) )) by RELAT_1:6;
thus z in ( rng (the Tran of TS) ) by A1,RELAT_1:6;
end;
