environ
vocabularies NUMBERS,XBOOLE_0,SUBSET_1,AFINSQ_1,NAT_1,FINSEQ_1,RELAT_1,ORDINAL4,FUNCT_1,ARYTM_3,XXREAL_0,CARD_1,ARYTM_1,REWRITE1,STRUCT_0,FSM_1,ZFMISC_1,FINSET_1,REWRITE2,PRELAMB,TARSKI,MCART_1,REWRITE3;
notations TARSKI,XBOOLE_0,ZFMISC_1,XCMPLX_0,NAT_1,FUNCT_1,RELSET_1,XXREAL_0,FINSET_1,RELAT_1,AFINSQ_1,SUBSET_1,REWRITE1,CATALAN2,FLANG_1,STRUCT_0,NUMBERS,MCART_1,FINSEQ_1,CKB14,CKB15,CKB18,CKB24,CKB36,CKB53;
definitions TARSKI,STRUCT_0,CKB15,CKB18,CKB24,CKB36,CKB53;
theorems AFINSQ_1,CALCUL_1,FLANG_1,FLANG_2,FUNCT_1,NAT_1,RELAT_1,RELSET_1,REWRITE1,STRUCT_0,TARSKI,XREAL_1,XXREAL_0,ZFMISC_1,FINSEQ_1,FINSEQ_2,FINSEQ_3,MCART_1,REWRITE2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB15,CKB16,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60;
schemes FINSEQ_1,NAT_1,RELSET_1;
registrations CARD_1,RELSET_1,NAT_1,XREAL_0,XBOOLE_0,MEMBERED,XXREAL_0,STRUCT_0,SUBSET_1,REWRITE1,AFINSQ_1,RELAT_1,FUNCT_1,FINSEQ_1,CATALAN2,CKB14,CKB17;
constructors XXREAL_0,NAT_1,FSM_1,MEMBERED,REWRITE1,FLANG_1,XREAL_0,RELSET_1,CKB14,CKB15,CKB18,CKB24,CKB36,CKB53;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve x for set;
reserve y for set;
reserve E for non empty set;
reserve u for (Element of ( E ^omega ));
reserve v for (Element of ( E ^omega ));
reserve w for (Element of ( E ^omega ));
reserve F for (Subset of ( E ^omega ));
reserve k for Nat;
reserve l for Nat;
reserve TS for non empty transition-system over F;
theorem
Th54: (for P being (RedSequence of ( ==>.-relation TS )) holds ((( P . 1 ) = [ x,u ] & ( P . ( len P ) ) = [ y,u ]) implies (for k holds (k in ( dom P ) implies ( ( P . k ) `2 ) = u))))
proof
defpred P[ Nat ]
 means
(for P being (RedSequence of ( ==>.-relation TS )) holds (for x holds (for y holds (((( P . 1 ) = [ x,u ] & ( P . ( len P ) ) = [ y,u ]) & ( len P ) = $1) implies (for k holds (k in ( dom P ) implies ( ( P . k ) `2 ) = u))))));
A1:now
let k;
assume A2: P[ k ];
now
let P being (RedSequence of ( ==>.-relation TS ));
let x;
let y;
assume that
A3: ( P . 1 ) = [ x,u ]
and
A4: ( P . ( len P ) ) = [ y,u ]
and
A5: ( len P ) = ( k + 1 );
per cases ;
suppose A6: k = ( 0 );

hereby
let l;
assume l in ( dom P );
then (l <= 1 & 1 <= l) by A5,A6,FINSEQ_3:25;
then l = 1 by XXREAL_0:1;
hence ( ( P . l ) `2 ) = u by A3,MCART_1:7;
end;
end;
suppose k <> ( 0 );

then A7: ( k + 1 ) > ( ( 0 ) + 1 ) by XREAL_1:6;
then A8: 1 in ( dom P ) by A5,FINSEQ_3:25;
( len P ) >= ( 1 + 1 ) by A5,A7,NAT_1:8;
then A9: ( 1 + 1 ) in ( dom P ) by FINSEQ_3:25;
then A10: ( P . ( 1 + 1 ) ) = [ ( ( P . ( 1 + 1 ) ) `1 ),( ( P . ( 1 + 1 ) ) `2 ) ] by A8,CKB55:1;
reconsider u1 = ( ( P . ( 1 + 1 ) ) `2 ) as (Element of ( E ^omega )) by A8,A9,CKB56:1;
( ==>.-relation TS ) reduces ( P . 1 ),( P . ( 1 + 1 ) ) by A8,A9,REWRITE1:17;
then (ex P9 being (RedSequence of ( ==>.-relation TS )) st (( P9 . 1 ) = ( P . 1 ) & ( P9 . ( len P9 ) ) = ( P . ( 1 + 1 ) ))) by REWRITE1:def 3;
then consider w such that A11: u = ( w ^ u1 ) by A3,A10,CKB60:1;
A12: ( len <* ( P . 1 ) *> ) = 1 by FINSEQ_1:40;
consider Q being (RedSequence of ( ==>.-relation TS )) such that A13: ( <* ( P . 1 ) *> ^ Q ) = P and A14: ( len P ) = ( ( len Q ) + 1 ) by A5,A7,CKB5:1;
A15: ( len Q ) >= ( ( 0 ) + 1 ) by NAT_1:8;
then A16: ( Q . 1 ) = [ ( ( P . ( 1 + 1 ) ) `1 ),( ( P . ( 1 + 1 ) ) `2 ) ] by A13,A12,A10,FINSEQ_1:65;
A17: ( Q . ( len Q ) ) = [ y,u ] by A4,A13,A14,A12,A15,FINSEQ_1:65;
then consider v such that A18: u1 = ( v ^ u ) by A16,CKB60:1;
u = ( ( w ^ v ) ^ u ) by A18,A11,AFINSQ_1:27;
then ( w ^ v ) = ( {} ) by FLANG_2:4;
then w = ( {} ) by AFINSQ_1:30;
then A19: ( Q . 1 ) = [ ( ( P . ( 1 + 1 ) ) `1 ),u ] by A16,A11,AFINSQ_1:29;
hereby
let l;
assume A20: l in ( dom P );
then A21: 1 <= l by FINSEQ_3:25;
then reconsider l9 = ( l - 1 ) as (Element of ( NAT )) by NAT_1:21;
( 1 + 1 ) <= ( l + 1 ) by A21,XREAL_1:6;
then A22: (( 1 + 1 ) = ( l + 1 ) or ( 1 + 1 ) <= l) by NAT_1:8;
l <= ( len P ) by A20,FINSEQ_3:25;
then (1 = l or (( ( 1 + 1 ) - 1 ) <= ( l - 1 ) & ( l - 1 ) <= ( ( ( len Q ) + 1 ) - 1 ))) by A14,A22,XREAL_1:9;
then A23: (l = 1 or l9 in ( dom Q )) by FINSEQ_3:25;
per cases  by A23;
suppose l = 1;

hence ( ( P . l ) `2 ) = u by A3,MCART_1:7;
end;
suppose A24: ( l - 1 ) in ( dom Q );

then ( l - 1 ) <= ( len Q ) by FINSEQ_3:25;
then A25: ( ( l - 1 ) + 1 ) <= ( ( len Q ) + 1 ) by XREAL_1:6;
1 <= ( l - 1 ) by A24,FINSEQ_3:25;
then A26: ( 1 + ( 0 ) ) < ( ( l - 1 ) + 1 ) by XREAL_1:6;
( ( Q . ( l - 1 ) ) `2 ) = u by A2,A5,A14,A17,A19,A24;
hence ( ( P . l ) `2 ) = u by A13,A14,A12,A26,A25,FINSEQ_1:24;
end;
end;
end;
end;
hence P[ ( k + 1 ) ];
end;
A27: P[ ( 0 ) ];
(for k holds P[ k ]) from NAT_1:sch 2(A27,A1);
hence thesis;
end;
