environ
vocabularies NUMBERS,SUBSET_1,REAL_1,XREAL_0,ORDINAL1,CFUNCT_1,COMSEQ_1,PARTFUN1,ORDINAL2,NAT_1,FDIFF_1,VALUED_0,SEQ_2,CARD_1,SEQ_1,FUNCT_1,COMPLEX1,RELAT_1,ARYTM_3,XXREAL_0,ARYTM_1,FUNCOP_1,VALUED_1,FUNCT_2,TARSKI,RCOMP_1,XBOOLE_0,FCONT_1,CFCONT_1,XXREAL_2,CFDIFF_1;
notations TARSKI,SUBSET_1,ORDINAL1,FUNCT_1,NUMBERS,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,PARTFUN1,FUNCT_2,FUNCOP_1,VALUED_0,VALUED_1,SEQ_1,RELSET_1,SEQ_2,CFUNCT_1,COMSEQ_1,COMSEQ_2,COMSEQ_3,CFCONT_1,XXREAL_0,CKB1,CKB3,CKB13,CKB15,CKB16,CKB18,CKB29,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39;
definitions XCMPLX_0,XBOOLE_0,TARSKI,RELAT_1,COMSEQ_2,SEQM_3,CFCONT_1,SUBSET_1,FINSEQ_4,VALUED_0,VALUED_1,SEQ_2,COMPLEX1,FUNCT_2,CKB1,CKB3,CKB13,CKB16,CKB29,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39;
theorems TARSKI,NAT_1,FUNCT_1,FUNCT_2,ZFMISC_1,COMPLEX1,SEQ_1,SEQ_2,SEQ_4,NUMBERS,COMSEQ_1,COMSEQ_2,COMSEQ_3,CFUNCT_1,CFCONT_1,RELAT_1,XBOOLE_0,XBOOLE_1,PARTFUN1,PARTFUN2,XCMPLX_0,XCMPLX_1,XREAL_1,XXREAL_0,ORDINAL1,ABSVALUE,XREAL_0,FUNCOP_1,SUBSET_1,VALUED_1,VALUED_0,CKB1,CKB2,CKB3,CKB4,CKB6,CKB11,CKB12,CKB13,CKB16,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44;
schemes SEQ_1,COMSEQ_1,FUNCT_2;
registrations FUNCT_1,RELSET_1,FUNCT_2,MEMBERED,NUMBERS,ORDINAL1,XREAL_0,XXREAL_0,COMSEQ_2,NAT_1,VALUED_0,SEQ_4,VALUED_1,FUNCOP_1,CKB5,CKB7,CKB8,CKB9,CKB10,CKB14,CKB17,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28;
constructors PARTFUN1,REAL_1,NAT_1,VALUED_0,VALUED_1,SEQ_1,SEQ_2,FINSEQ_4,SEQM_3,PARTFUN2,SQUARE_1,COMSEQ_2,COMSEQ_3,CFCONT_1,XXREAL_0,CFUNCT_1,RELSET_1,CKB1,CKB3,CKB13,CKB16,CKB29,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve X for set;
reserve r for  real number;
reserve z0 for Complex;
reserve s1 for Complex_Sequence;
theorem
(for X being (Subset of ( COMPLEX )) holds (for z0 being (Element of ( COMPLEX )) holds (for r being (Element of ( REAL )) holds (X = { y where y is Complex: |. ( y - z0 ) .| <= r } implies X is  closed))))
proof
let X being (Subset of ( COMPLEX ));
let z0 being (Element of ( COMPLEX ));
let r being (Element of ( REAL ));
reconsider X0 = X as (Subset of ( COMPLEX ));
assume A1: X = { y where y is Complex: |. ( y - z0 ) .| <= r };
(for s1 being Complex_Sequence holds ((( rng s1 ) c= X0 & s1 is  convergent) implies ( lim s1 ) in X0))
proof
reconsider s4 = ( ( NAT ) --> r ) as Real_Sequence;
reconsider s2 = ( ( NAT ) --> z0 ) as Complex_Sequence;
let s1 being Complex_Sequence;
assume that
A2: ( rng s1 ) c= X0
and
A3: s1 is  convergent;
set s3 = ( s1 - s2 );
A4: s2 is  convergent by CFCONT_1:26;
then A5: ( lim s3 ) = ( ( lim s1 ) - ( lim s2 ) ) by A3,COMSEQ_2:26;
A6: (for n being (Element of ( NAT )) holds ( |. s3 .| . n ) <= r)
proof
let n being (Element of ( NAT ));
now
let n being (Element of ( NAT ));
( s3 . n ) = ( ( s1 . n ) + ( ( - s2 ) . n ) ) by VALUED_1:1
.= ( ( s1 . n ) - ( s2 . n ) ) by VALUED_1:8;
hence ( s3 . n ) = ( ( s1 . n ) - z0 ) by FUNCOP_1:7;
end;
then A7: ( s3 . n ) = ( ( s1 . n ) - z0 );
( dom s1 ) = ( NAT ) by FUNCT_2:def 1;
then ( s1 . n ) in ( rng s1 ) by FUNCT_1:def 3;
then ( s1 . n ) in X0 by A2;
then (ex y being Complex st (y = ( s1 . n ) & |. ( y - z0 ) .| <= r)) by A1;
hence thesis by A7,VALUED_1:18;
end;
s3 is  convergent by A3,A4;
then A8: ( lim |. s3 .| ) = |. ( lim s3 ) .| by COMSEQ_2:11;
reconsider s3 = ( s1 - s2 ) as  convergent Complex_Sequence by A3,A4;
A9: (for n being (Element of ( NAT )) holds ( |. s3 .| . n ) <= ( s4 . n ))
proof
let n being (Element of ( NAT ));
( |. s3 .| . n ) <= r by A6;
hence thesis by FUNCOP_1:7;
end;
A10: (for n being (Element of ( NAT )) holds ( lim s2 ) = z0)
proof
let n being (Element of ( NAT ));
( lim s2 ) = ( s2 . n ) by CFCONT_1:28
.= z0 by FUNCOP_1:7;
hence thesis;
end;
( lim s4 ) = ( s4 . ( 0 ) ) by SEQ_4:26
.= r by FUNCOP_1:7;
then ( lim |. s3 .| ) <= r by A9,SEQ_2:18;
then |. ( ( lim s1 ) - z0 ) .| <= r by A10,A5,A8;
hence thesis by A1;
end;
hence thesis by CKB38:def 1;
end;
