environ
vocabularies NUMBERS,NAT_1,SUBSET_1,FINSEQ_2,MATRIX_1,ARYTM_3,FINSEQ_1,TREES_1,RELAT_1,CARD_1,XXREAL_0,ZFMISC_1,XCMPLX_0,ORDINAL1,COMPLFLD,MATRIX_5,ARYTM_1,COMPLEX1,QC_LANG1,FUNCT_1,RVSUM_1,BINOP_2,TARSKI,XBOOLE_0,CARD_3,INCSP_1,FUNCOP_1,SETWISEO,ORDINAL4,PARTFUN1,MATRIXC1;
notations TARSKI,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,ZFMISC_1,NAT_1,NAT_D,PARTFUN1,BINOP_1,FUNCOP_1,FINSEQ_1,FINSEQOP,SEQ_4,COMPLEX1,RVSUM_1,FINSEQ_2,BINOP_2,ORDINAL1,MATRIX_5,MATRIX_1,MATRIX_3,MATRIX_4,RLVECT_1,COMPLSP2,SETWOP_2,COMPLFLD,STRUCT_0,GROUP_1,SEQ_1,CKB1,CKB17,CKB18,CKB19,CKB20,CKB21,CKB24,CKB27,CKB39,CKB58;
definitions MATRIX_1,RVSUM_1,VALUED_1,CKB1,CKB17,CKB18,CKB19,CKB20,CKB21,CKB24,CKB39,CKB58;
theorems FINSEQ_1,FUNCT_1,NAT_1,MATRIX_1,FINSEQ_2,COMPLEX1,BINOP_2,FINSEQ_3,XCMPLX_0,ZFMISC_1,SEQ_4,MATRIX_2,FINSEQOP,COMPLSP2,FUNCOP_1,FUNCT_2,FINSOP_1,SETWOP_2,FINSEQ_5,XREAL_1,MATRIX_3,COMPLFLD,MATRIX_4,MATRIX_5,NUMBERS,XBOOLE_1,ORDINAL1,PARTFUN1,XXREAL_0,XREAL_0,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58;
schemes MATRIX_1,FINSEQ_2,FINSEQ_1,FUNCT_2,NAT_1;
registrations XBOOLE_0,FUNCT_1,FUNCT_2,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,BINOP_2,MEMBERED,FINSEQ_2,COMPLFLD,MATRIX_1,VALUED_0,RELSET_1,CARD_1,FINSEQ_1;
constructors PARTFUN1,SETWISEO,XXREAL_0,NAT_1,FINSOP_1,BINARITH,MATRIX_3,MATRIX_4,MATRIX_5,SEQ_4,SEQ_1,BINOP_2,BINOP_1,RVSUM_1,NAT_D,RELSET_1,COMPLSP2,CKB1,CKB17,CKB18,CKB19,CKB20,CKB21,CKB24,CKB27,CKB39,CKB58;
requirements NUMERALS,BOOLE,SUBSET,REAL,ARITHM;
begin
reserve j for Nat;
definition
let M being (Matrix of ( COMPLEX ));
func ColSum M -> (FinSequence of ( COMPLEX )) means 
:Def11: (( len it ) = ( width M ) & (for j being Nat holds (j in ( Seg ( width M ) ) implies ( it . j ) = ( Sum ( Col (M,j) ) ))));
existence
proof
deffunc F(Nat) = ( Sum ( Col (M,$1) ) );
consider f being (FinSequence of ( COMPLEX )) such that A1: ( len f ) = ( width M ) and A2: (for j being Nat holds (j in ( dom f ) implies ( f . j ) = F(j))) from FINSEQ_2:sch 1;
take f;
thus ( len f ) = ( width M ) by A1;
let j being Nat;
( dom f ) = ( Seg ( width M ) ) by A1,FINSEQ_1:def 3;
hence thesis by A2;
end;
uniqueness
proof
let p1 being (FinSequence of ( COMPLEX ));
let p2 being (FinSequence of ( COMPLEX ));
assume that
A3: ( len p1 ) = ( width M )
and
A4: (for j holds (j in ( Seg ( width M ) ) implies ( p1 . j ) = ( Sum ( Col (M,j) ) )))
and
A5: ( len p2 ) = ( width M )
and
A6: (for j holds (j in ( Seg ( width M ) ) implies ( p2 . j ) = ( Sum ( Col (M,j) ) )));
A7: ( dom p1 ) = ( Seg ( width M ) ) by A3,FINSEQ_1:def 3;
(for j being Nat holds (j in ( dom p1 ) implies ( p1 . j ) = ( p2 . j )))
proof
let j being Nat;
assume A8: j in ( dom p1 );
then ( p1 . j ) = ( Sum ( Col (M,j) ) ) by A4,A7;
hence thesis by A6,A7,A8;
end;
hence thesis by A3,A5,FINSEQ_2:9;
end;
end;
