environ
vocabularies XBOOLE_0,PRE_TOPC,SUBSET_1,STRUCT_0,CARD_3,CARD_1,TARSKI,ORDINAL1,FINSET_1,NATTRA_1,TOPS_1,SETFAM_1,RCOMP_1,RLVECT_3,GLIB_000,TOPMETR,NUMBERS,BORSUK_5,TOPGEN_1;
notations TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,CARD_1,ORDINAL1,NUMBERS,CARD_3,FINSET_1,DOMAIN_1,STRUCT_0,PRE_TOPC,TOPS_1,TDLAT_3,YELLOW_8,TOPMETR,BORSUK_5,ORDERS_4,CKB11,CKB23,CKB25;
definitions TARSKI,XBOOLE_0,SUBSET_1,STRUCT_0,CKB11,CKB23,CKB25;
theorems TARSKI,ZFMISC_1,PRE_TOPC,TOPS_1,XBOOLE_0,XBOOLE_1,SUBSET_1,TOPS_3,TDLAT_3,YELLOW_8,FRECHET,BORSUK_5,TOPMETR,NUMBERS,CARD_4,ORDERS_4,CARD_3,CKB1,CKB2,CKB3,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26;
schemes ORDINAL1,SUBSET_1;
registrations SUBSET_1,NUMBERS,CARD_1,STRUCT_0,TOPS_1,TEX_1,TEX_4,YELLOW13,BORSUK_3,TOPMETR,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
constructors SETFAM_1,CARD_3,TOPS_1,TDLAT_3,TOPMETR,YELLOW_8,BORSUK_5,ORDERS_4,TOPS_2,CKB11,CKB23,CKB25;
requirements BOOLE,SUBSET;
begin
theorem
Th19: (for T being non  empty TopSpace holds (for A being (Subset of T) holds (for x being (Point of T) holds (x in ( Der A ) iff (for U being  open (Subset of T) holds (x in U implies (ex y being (Point of T) st (y in ( A /\ U ) & x <> y))))))))
proof
let T being non  empty TopSpace;
let A being (Subset of T);
let x being (Point of T);
hereby
assume x in ( Der A );
then x is_an_accumulation_point_of A by CKB26:1;
then A1: x in ( Cl ( A \ { x } ) ) by CKB23:def 1;
let U being  open (Subset of T);
assume x in U;
then ( A \ { x } ) meets U by A1,PRE_TOPC:24;
then consider y being set such that A2: y in ( A \ { x } ) and A3: y in U by XBOOLE_0:3;
reconsider y as (Point of T) by A2;
take y;
y in A by A2,ZFMISC_1:56;
hence (y in ( A /\ U ) & x <> y) by A2,A3,XBOOLE_0:def 4,ZFMISC_1:56;
end;
assume A4: (for U being  open (Subset of T) holds (x in U implies (ex y being (Point of T) st (y in ( A /\ U ) & x <> y))));
(for G being (Subset of T) holds (G is  open implies (x in G implies ( A \ { x } ) meets G)))
proof
let G being (Subset of T);
assume A5: G is  open;
assume x in G;
then consider y being (Point of T) such that A6: y in ( A /\ G ) and A7: x <> y by A4,A5;
y in A by A6,XBOOLE_0:def 4;
then A8: y in ( A \ { x } ) by A7,ZFMISC_1:56;
y in G by A6,XBOOLE_0:def 4;
hence thesis by A8,XBOOLE_0:3;
end;
then x in ( Cl ( A \ { x } ) ) by PRE_TOPC:24;
then x is_an_accumulation_point_of A by CKB23:def 1;
hence thesis by CKB26:1;
end;
