environ
vocabularies NUMBERS,SUBSET_1,INT_1,XREAL_0,ORDINAL1,SEQ_1,FINSEQ_1,RAT_1,ORDINAL4,POWER,INT_2,SQUARE_1,XXREAL_0,CARD_1,ARYTM_3,RELAT_1,NAT_1,FUNCT_1,ARYTM_1,REALSET1,SEQ_2,ORDINAL2,COMPLEX1,VALUED_1,FUNCOP_1,SERIES_1,CARD_3,XBOOLE_0,RFINSEQ,PARTFUN1,FINSEQ_2,NEWTON,SIN_COS,IRRAT_1;
notations XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,INT_1,COMPLEX1,NAT_1,FUNCT_1,PARTFUN1,FUNCOP_1,VALUED_0,VALUED_1,SEQ_1,SEQ_2,POWER,FINSEQ_1,RVSUM_1,SERIES_1,FINSEQ_2,RFINSEQ,SIN_COS,RAT_1,SQUARE_1,LIMFUNC1,INT_2,PEPIN,NEWTON,CKB1,CKB2,CKB6,CKB7,CKB8,CKB10,CKB11,CKB39,CKB40;
definitions SEQ_2,SQUARE_1,XCMPLX_0,CKB6,CKB7,CKB8,CKB10,CKB11,CKB39,CKB40;
theorems SEQ_1,POWER,NEWTON,NAT_1,SEQ_2,SEQ_4,ABSVALUE,RVSUM_1,FINSEQ_2,SERIES_1,RFINSEQ,FINSEQ_3,FINSEQ_5,SIN_COS,SQUARE_1,INT_1,RAT_1,INT_2,FUNCT_2,XCMPLX_0,XCMPLX_1,FUNCOP_1,XREAL_1,COMPLEX1,XXREAL_0,NAT_D,PARTFUN1,CARD_1,VALUED_0,ORDINAL1,XREAL_0,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48;
schemes SEQ_1,NAT_1,CKB5;
registrations ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,MEMBERED,NEWTON,XBOOLE_0,VALUED_0,VALUED_1,FUNCT_2,POWER,SEQ_4,FINSEQ_1;
constructors ARYTM_0,REAL_1,NAT_1,NAT_D,SEQ_2,PARTFUN1,RVSUM_1,LIMFUNC1,COMSEQ_3,RFINSEQ,BINARITH,SIN_COS,PEPIN,SEQ_1,SERIES_1,POWER,RELSET_1,CKB6,CKB7,CKB8,CKB10,CKB11;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve k for (Element of ( NAT ));
reserve n for (Element of ( NAT ));
reserve x for  real number;
reserve seq for Real_Sequence;
theorem
Th40: ((n > ( 0 ) & x = ( 1 / ( n + 1 ) )) implies ( ( n ! ) * ( Sum ( ( eseq ) ^\ ( n + 1 ) ) ) ) <= ( x / ( 1 - x ) ))
proof
assume that
A1: n > ( 0 )
and
A2: x = ( 1 / ( n + 1 ) );
deffunc F((Element of ( NAT ))) = ( x ^ ( $1 + 1 ) );
consider seq being Real_Sequence such that A3: (for k holds ( seq . k ) = F(k)) from SEQ_1:sch 1;
A4:now
let k;
A5: ( ( ( n ! ) (#) ( ( eseq ) ^\ ( n + 1 ) ) ) . k ) = ( ( n ! ) * ( ( ( eseq ) ^\ ( n + 1 ) ) . k ) ) by SEQ_1:9
.= ( ( n ! ) * ( ( eseq ) . ( ( n + 1 ) + k ) ) ) by NAT_1:def 3
.= ( ( n ! ) * ( 1 / ( ( ( n + k ) + 1 ) ! ) ) ) by CKB11:def 1
.= ( ( n ! ) / ( ( ( n + k ) + 1 ) ! ) );
hence ( ( ( n ! ) (#) ( ( eseq ) ^\ ( n + 1 ) ) ) . k ) >= ( 0 );
( seq . k ) = ( x ^ ( k + 1 ) ) by A3;
hence ( ( ( n ! ) (#) ( ( eseq ) ^\ ( n + 1 ) ) ) . k ) <= ( seq . k ) by A2,A5,CKB48:1;
end;
A6: ( seq . ( 0 ) ) = ( x ^ ( ( 0 ) + 1 ) ) by A3
.= x by POWER:25;
A7: ( ( eseq ) ^\ ( n + 1 ) ) is  summable by CKB31:1,SERIES_1:12;
( n + 1 ) > ( ( 0 ) + 1 ) by A1,XREAL_1:6;
then A8: x < 1 by A2,XREAL_1:212;
A9:now
let k;
thus ( seq . ( k + 1 ) ) = ( x ^ ( ( k + 1 ) + 1 ) ) by A3
.= ( ( x ^ 1 ) * ( x ^ ( k + 1 ) ) ) by A2,POWER:27
.= ( x * ( x ^ ( k + 1 ) ) ) by POWER:25
.= ( x * ( seq . k ) ) by A3;
end;
( abs x ) = x by A2,ABSVALUE:def 1;
then seq is  summable by A8,A9,SERIES_1:25;
then A10: ( Sum ( ( n ! ) (#) ( ( eseq ) ^\ ( n + 1 ) ) ) ) <= ( Sum seq ) by A4,SERIES_1:20;
( abs x ) < 1 by A2,A8,ABSVALUE:def 1;
then ( Sum seq ) = ( x / ( 1 - x ) ) by A6,A9,SERIES_1:25;
hence thesis by A7,A10,SERIES_1:10;
end;
