environ
vocabularies XBOOLE_0,ORDERS_2,OSALG_1,PBOOLE,STRUCT_0,SUBSET_1,XXREAL_0,RELAT_1,FUNCT_1,TARSKI,FINSEQ_1,CARD_3,MEMBER_1,MSUALG_3,MSUALG_1,GROUP_6,MARGREL1,NAT_1,PARTFUN1,SEQM_3,OSALG_2,MSUALG_2,UNIALG_2,OSALG_3;
notations TARSKI,XBOOLE_0,SUBSET_1,NAT_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,FINSEQ_1,FINSEQ_2,CARD_3,ORDERS_2,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_2,OSALG_1,OSALG_2,MSUALG_3,CKB1,CKB10;
definitions TARSKI,OSALG_1,CKB1,CKB10;
theorems XBOOLE_1,FUNCT_1,FUNCT_2,FINSEQ_1,PBOOLE,CARD_3,MSUALG_1,ZFMISC_1,MSUALG_9,FINSEQ_3,MSUALG_2,TARSKI,RELAT_1,OSALG_1,OSALG_2,MSUALG_3,MSAFREE3,ORDINAL1,PARTFUN1,FINSEQ_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11;
registrations XBOOLE_0,FUNCT_1,RELSET_1,FUNCOP_1,FINSEQ_1,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_3,ORDERS_3,MSUALG_9,OSALG_1,CKB6;
constructors MSUALG_3,ORDERS_3,OSALG_2,CARD_3,RELSET_1,CKB1,CKB10;
requirements BOOLE,SUBSET;
begin
reserve S1 for OrderSortedSign;
theorem
Th10: (for U1,U2 being  non-empty (OSAlgebra of S1) holds (U1,U2 are_os_isomorphic  implies U2,U1 are_os_isomorphic ))
proof
let U1 being  non-empty (OSAlgebra of S1),U2 being  non-empty (OSAlgebra of S1);
A1: ((the Sorts of U1) is (OrderSortedSet of S1) & (the Sorts of U2) is (OrderSortedSet of S1)) by OSALG_1:17;
assume U1,U2 are_os_isomorphic ;
then consider F being (ManySortedFunction of U1,U2) such that A2: F is_isomorphism U1,U2 and A3: F is  order-sorted by CKB10:def 1;
reconsider G = ( F "" ) as (ManySortedFunction of U2,U1);
A4: G is_isomorphism U2,U1 by A2,MSUALG_3:14;
(F is  "onto" & F is  "1-1") by A2,MSUALG_3:13;
then ( F "" ) is  order-sorted by A3,A1,CKB8:1;
hence thesis by A4,CKB10:def 1;
end;
