environ
vocabularies DIRAF,SUBSET_1,ANALOAF,AFF_1,INCSP_1,STRUCT_0,XBOOLE_0,TARSKI,RELAT_1,PARSP_1,AFF_2,ARYTM_3,AFF_4;
notations TARSKI,XBOOLE_0,SUBSET_1,STRUCT_0,ANALOAF,DIRAF,AFF_1,AFF_2,CKB15,CKB16;
definitions CKB15,CKB16;
theorems AFF_1,DIRAF,TARSKI,AFF_2,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
registrations XBOOLE_0,STRUCT_0;
constructors AFF_1,AFF_2,CKB15,CKB16;
requirements SUBSET,BOOLE;
begin
reserve AS for AffinSpace;
reserve a for (Element of AS);
reserve b for (Element of AS);
reserve K for (Subset of AS);
reserve P for (Subset of AS);
reserve X for (Subset of AS);
theorem
Th19: ((((X is  being_plane & a in X) & b in X) & a <> b) implies ( Line (a,b) ) c= X)
proof
assume that
A1: X is  being_plane
and
A2: (a in X & b in X)
and
A3: a <> b;
set Q = ( Line (a,b) );
A4: (a in Q & b in Q) by AFF_1:15;
(Q is  being_line & (ex K st (ex P st (((K is  being_line & P is  being_line) & (not K // P)) & X = ( Plane (K,P) ))))) by A1,A3,CKB16:def 1,AFF_1:def 3;
hence thesis by A2,A3,A4,CKB25:1;
end;
