environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,FINSEQ_1,FUNCT_1,RELAT_1,TARSKI,SUBSET_1,MARGREL1,FINSET_1,FINSEQ_2,CARD_3,CARD_1,SETFAM_1,STRUCT_0,ZFMISC_1,FUNCOP_1,XBOOLEAN,EQREL_1,ORDERS_2,WAYBEL23,YELLOW_0,LATTICES,ORDINAL2,WAYBEL_0,WAYBEL_3,WAYBEL_8,RCOMP_1,PRE_TOPC,RLVECT_3,CANTOR_1,YELLOW15;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NAT_1,SETFAM_1,DOMAIN_1,CARD_1,NUMBERS,FINSET_1,STRUCT_0,MARGREL1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,FINSEQ_1,FINSEQ_2,FINSEQ_4,EQREL_1,FUNCOP_1,CARD_3,PRE_TOPC,TOPS_2,CANTOR_1,ORDERS_2,YELLOW_0,WAYBEL_0,WAYBEL_3,WAYBEL_8,WAYBEL23,CKB8,CKB22,CKB28;
definitions TARSKI,FUNCT_1,XBOOLE_0,FINSEQ_2,MARGREL1,XBOOLEAN,STRUCT_0,CKB8,CKB22,CKB28;
theorems TARSKI,SETFAM_1,ZFMISC_1,FINSET_1,RELAT_1,FUNCT_1,FUNCT_2,FUNCT_6,MSSUBFAM,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,EQREL_1,FUNCOP_1,CARD_1,CARD_4,T_0TOPSP,PRE_TOPC,TOPS_2,CANTOR_1,MSSCYC_1,YELLOW_0,YELLOW_8,YELLOW_9,WAYBEL_0,WAYBEL_3,WAYBEL_8,WAYBEL23,XBOOLE_0,XBOOLE_1,SUBSET_1,ORDINAL1,XBOOLEAN,CKB3,CKB4,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB22,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB35,CKB36;
schemes FUNCT_2,PRE_CIRC,FINSEQ_1,FRAENKEL,CKB1;
registrations SUBSET_1,FUNCT_1,RELSET_1,FINSET_1,FINSEQ_1,MARGREL1,FINSEQ_2,REALSET1,STRUCT_0,TOPS_1,LATTICE3,WAYBEL_0,WAYBEL_3,WAYBEL23,ORDINAL1,PRE_TOPC,ZFMISC_1,CARD_1,XBOOLE_0,RELAT_1,CKB2,CKB5,CKB6,CKB21,CKB23,CKB34;
constructors SETFAM_1,XXREAL_0,FINSEQ_4,REALSET1,VALUAT_1,TOPS_2,CANTOR_1,WAYBEL_8,WAYBEL23,RELSET_1,FINSEQ_2,CKB8,CKB22,CKB28;
requirements NUMERALS,REAL,SUBSET,BOOLE;
begin
theorem
(for L being  lower-bounded sup-Semilattice holds (for B being (Subset of L) holds (B is  infinite implies ( card B ) = ( card ( finsups B ) ))))
proof
let L being  lower-bounded sup-Semilattice;
let B being (Subset of L);
defpred P[ Function,set ]
 means
$2 = ( "\/" (( rng $1 ),L) );
assume A1: B is  infinite;
then reconsider B1 = B as non  empty (Subset of L);
A2: (for p being (Element of ( B1 * )) holds (ex u being (Element of ( finsups B1 )) st P[ p,u ]))
proof
let p being (Element of ( B1 * ));
A3: ( rng p ) c= (the carrier of L) by XBOOLE_1:1;
now
per cases ;
suppose ( rng p ) is  empty;

hence  ex_sup_of ( rng p ),L by YELLOW_0:42;
end;
suppose ( rng p ) is non  empty;

hence  ex_sup_of ( rng p ),L by A3,YELLOW_0:54;
end;
end;
then ( "\/" (( rng p ),L) ) in { ( "\/" (Y,L) ) where Y is  finite (Subset of B1):  ex_sup_of Y,L };
then reconsider u = ( "\/" (( rng p ),L) ) as (Element of ( finsups B1 )) by WAYBEL_0:def 27;
take u;
thus thesis;
end;
consider f being (Function of ( B1 * ),( finsups B1 )) such that A4: (for p being (Element of ( B1 * )) holds P[ p,( f . p ) ]) from FUNCT_2:sch 3(A2);
B c= ( finsups B )
proof
let z being set;
assume A5: z in B;
then reconsider z1 = z as (Element of L);
A6: { z1 } c= B
proof
let v being set;
assume v in { z1 };
hence thesis by A5,TARSKI:def 1;
end;
( ex_sup_of { z1 },L & z = ( sup { z1 } )) by YELLOW_0:38,YELLOW_0:39;
then z1 in { ( "\/" (Y,L) ) where Y is  finite (Subset of B):  ex_sup_of Y,L } by A6;
hence thesis by WAYBEL_0:def 27;
end;
then A7: ( card B ) c= ( card ( finsups B ) ) by CARD_1:11;
A8: ( dom f ) = ( B1 * ) by FUNCT_2:def 1;
( finsups B ) c= ( rng f )
proof
let z being set;
assume z in ( finsups B );
then z in { ( "\/" (Y,L) ) where Y is  finite (Subset of B):  ex_sup_of Y,L } by WAYBEL_0:def 27;
then consider Y being  finite (Subset of B) such that A9: z = ( "\/" (Y,L) ) and  ex_sup_of Y,L;
consider p being FinSequence such that A10: ( rng p ) = Y by FINSEQ_1:52;
reconsider p as (FinSequence of B1) by A10,FINSEQ_1:def 4;
reconsider p1 = p as (Element of ( B1 * )) by FINSEQ_1:def 11;
( f . p1 ) = ( "\/" (( rng p1 ),L) ) by A4;
hence thesis by A8,A9,A10,FUNCT_1:def 3;
end;
then ( card ( finsups B1 ) ) c= ( card ( B1 * ) ) by A8,CARD_1:12;
then ( card ( finsups B1 ) ) c= ( card B1 ) by A1,CARD_4:24;
hence thesis by A7,XBOOLE_0:def 10;
end;
