environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,FINSEQ_1,FUNCT_1,RELAT_1,TARSKI,SUBSET_1,MARGREL1,FINSET_1,FINSEQ_2,CARD_3,CARD_1,SETFAM_1,STRUCT_0,ZFMISC_1,FUNCOP_1,XBOOLEAN,EQREL_1,ORDERS_2,WAYBEL23,YELLOW_0,LATTICES,ORDINAL2,WAYBEL_0,WAYBEL_3,WAYBEL_8,RCOMP_1,PRE_TOPC,RLVECT_3,CANTOR_1,YELLOW15;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NAT_1,SETFAM_1,DOMAIN_1,CARD_1,NUMBERS,FINSET_1,STRUCT_0,MARGREL1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,FINSEQ_1,FINSEQ_2,FINSEQ_4,EQREL_1,FUNCOP_1,CARD_3,PRE_TOPC,TOPS_2,CANTOR_1,ORDERS_2,YELLOW_0,WAYBEL_0,WAYBEL_3,WAYBEL_8,WAYBEL23,CKB8,CKB22,CKB28;
definitions TARSKI,FUNCT_1,XBOOLE_0,FINSEQ_2,MARGREL1,XBOOLEAN,STRUCT_0,CKB8,CKB22,CKB28;
theorems TARSKI,SETFAM_1,ZFMISC_1,FINSET_1,RELAT_1,FUNCT_1,FUNCT_2,FUNCT_6,MSSUBFAM,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,EQREL_1,FUNCOP_1,CARD_1,CARD_4,T_0TOPSP,PRE_TOPC,TOPS_2,CANTOR_1,MSSCYC_1,YELLOW_0,YELLOW_8,YELLOW_9,WAYBEL_0,WAYBEL_3,WAYBEL_8,WAYBEL23,XBOOLE_0,XBOOLE_1,SUBSET_1,ORDINAL1,XBOOLEAN,CKB3,CKB4,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB22,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40;
schemes FUNCT_2,PRE_CIRC,FINSEQ_1,FRAENKEL,CKB1;
registrations SUBSET_1,FUNCT_1,RELSET_1,FINSET_1,FINSEQ_1,MARGREL1,FINSEQ_2,REALSET1,STRUCT_0,TOPS_1,LATTICE3,WAYBEL_0,WAYBEL_3,WAYBEL23,ORDINAL1,PRE_TOPC,ZFMISC_1,CARD_1,XBOOLE_0,RELAT_1,CKB2,CKB5,CKB6,CKB21,CKB23,CKB34;
constructors SETFAM_1,XXREAL_0,FINSEQ_4,REALSET1,VALUAT_1,TOPS_2,CANTOR_1,WAYBEL_8,WAYBEL23,RELSET_1,FINSEQ_2,CKB8,CKB22,CKB28;
requirements NUMERALS,REAL,SUBSET,BOOLE;
begin
theorem
(for T being non empty TopSpace holds (T is  finite implies (for B being (Basis of T) holds (for x being (Element of T) holds ( meet { A where A is (Element of (the topology of T)): x in A } ) in B))))
proof
deffunc F(set) = $1;
let T being non empty TopSpace;
assume T is  finite;
then reconsider tT = (the topology of T) as  finite non empty set;
let B being (Basis of T);
let x being (Element of T);
defpred P[ set ]
 means
x in $1;
{ A where A is (Element of (the topology of T)): x in A } c= ( bool (the carrier of T) )
proof
let z being set;
assume z in { A where A is (Element of (the topology of T)): x in A };
then (ex A being (Element of (the topology of T)) st (z = A & x in A));
hence thesis;
end;
then reconsider sfA = { A where A is (Element of (the topology of T)): x in A } as (Subset-Family of T);
reconsider sfA as (Subset-Family of T);
A1:now
let Y being set;
assume Y in sfA;
then (ex A being (Element of (the topology of T)) st (Y = A & x in A));
hence x in Y;
end;
(the carrier of T) is (Element of (the topology of T)) by PRE_TOPC:def 1;
then (the carrier of T) in sfA;
then A2: x in ( meet sfA ) by A1,SETFAM_1:def 1;
now
let P being (Subset of T);
assume P in sfA;
then (ex A being (Element of (the topology of T)) st (P = A & x in A));
hence P is  open by PRE_TOPC:def 2;
end;
then A3: sfA is  open by TOPS_2:def 1;
{ F(A) where A is (Element of tT): P[ A ] } is  finite from PRE_CIRC:sch 1;
then ( meet sfA ) is  open by A3,TOPS_2:20;
then consider a being (Subset of T) such that A4: a in B and A5: x in a and A6: a c= ( meet sfA ) by A2,YELLOW_9:31;
( meet sfA ) c= a
proof
let z being set;
B c= (the topology of T) by TOPS_2:64;
then a in sfA by A4,A5;
hence thesis by SETFAM_1:def 1;
end;
hence thesis by A4,A6,XBOOLE_0:def 10;
end;
