environ
vocabularies NUMBERS,REAL_1,ZFMISC_1,NORMSP_1,PRE_TOPC,PARTFUN1,FUNCT_1,FUNCT_4,NAT_1,FDIFF_1,SUBSET_1,SEQ_4,RELAT_1,GLIB_000,LOPBAN_1,ORDINAL4,RFINSEQ,RCOMP_1,TARSKI,SEQ_1,ARYTM_3,VALUED_1,FUNCT_2,ARYTM_1,SEQ_2,ORDINAL2,SUPINF_2,FCONT_1,COMPLEX1,STRUCT_0,CARD_1,VALUED_0,XXREAL_0,GROUP_2,FUNCOP_1,XREAL_0,ORDINAL1,MEMBERED,FINSEQ_5,XXREAL_2,XBOOLE_0,CARD_3,FINSEQ_1,FINSEQ_2,AFINSQ_1,RLVECT_1,SQUARE_1,RVSUM_1,XXREAL_1,PDIFF_1,PRVECT_1,PRVECT_2,ALGSTR_0,EUCLID,CFCONT_1,RFINSEQ2,NORMSP_0,NFCONT_1,MONOID_0,RLTOPSP1;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,FUNCT_4,CARD_1,NUMBERS,XXREAL_0,XREAL_0,REAL_1,SQUARE_1,NAT_1,MEMBERED,VALUED_0,COMPLEX1,NAT_D,BINOP_2,XXREAL_2,CARD_3,FINSEQ_1,VALUED_1,FINSEQ_2,SEQ_1,SEQ_2,RVSUM_1,RFINSEQ,SEQ_4,RCOMP_1,FCONT_1,FDIFF_1,FINSEQ_5,FINSEQ_7,RFINSEQ2,STRUCT_0,MONOID_0,ALGSTR_0,PRE_TOPC,RLVECT_1,NORMSP_0,NORMSP_1,VFUNCT_1,EUCLID,LOPBAN_1,PRVECT_1,NFCONT_1,NDIFF_1,PRVECT_2,NFCONT_3,NDIFF_3,RLTOPSP1,FUNCT_7,CKB11,CKB14,CKB22,CKB23,CKB31;
definitions TARSKI,FUNCT_2,RLVECT_1,LOPBAN_1,EUCLID,RFINSEQ2,FINSEQ_1,FINSEQ_2,STRUCT_0,MONOID_0,ALGSTR_0,NORMSP_0,RCOMP_1,XCMPLX_0,PRVECT_2,CKB14,CKB22,CKB31;
theorems TARSKI,ABSVALUE,XBOOLE_0,XBOOLE_1,RLVECT_1,XCMPLX_0,XCMPLX_1,ZFMISC_1,SEQ_1,SEQ_2,NAT_1,RELAT_1,FUNCT_1,VFUNCT_1,FUNCT_2,FUNCT_3,FINSEQ_4,RLVECT_2,FINSEQ_3,ORDINAL1,FINSEQ_1,CARD_3,FUNCT_4,SEQ_4,NORMSP_1,LOPBAN_1,PARTFUN1,PARTFUN2,NFCONT_1,FDIFF_1,NDIFF_1,FUNCOP_1,XREAL_1,COMPLEX1,XXREAL_0,VALUED_1,VALUED_0,GRCAT_1,NORMSP_0,XREAL_0,RCOMP_1,FINSEQ_2,FINSEQ_7,RVSUM_1,SQUARE_1,PRVECT_1,PRVECT_2,PDIFF_7,EUCLID,TOPREAL7,XXREAL_2,FINSEQ_5,NAT_D,RFINSEQ2,INTEGRA5,FCONT_1,NAT_2,NFCONT_3,NDIFF_2,NDIFF_3,CARD_1,ROLLE,XXREAL_1,RLTOPSP1,FUNCT_7,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB12,CKB13,CKB14,CKB18,CKB19,CKB20,CKB21,CKB22,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31;
schemes FUNCT_2,SEQ_1,FINSEQ_1,NAT_1,FINSEQ_2;
registrations RELSET_1,STRUCT_0,ORDINAL1,XREAL_0,MEMBERED,FUNCT_1,NDIFF_1,FUNCT_2,NUMBERS,XBOOLE_0,VALUED_0,PRVECT_2,FINSEQ_2,FINSEQ_1,CARD_3,NORMSP_0,NORMSP_1,RELAT_1,XXREAL_0,LOPBAN_1,LOPBAN_2,PRVECT_3,FUNCOP_1,NAT_1,FINSEQ_5,XXREAL_2,RCOMP_1,VALUED_1,FDIFF_1,NFCONT_3,FINSET_1,XCMPLX_0,PARTFUN1,CARD_1,MONOID_0,CKB10,CKB15,CKB16,CKB17;
constructors REAL_1,SQUARE_1,SEQ_2,FDIFF_1,NFCONT_1,RSSPACE,VFUNCT_1,NDIFF_1,SEQ_1,RELSET_1,FINSEQ_7,FINSEQ_5,RVSUM_1,BINOP_2,PRVECT_2,RLVECT_2,NAT_D,FINSEQOP,RFINSEQ,RFINSEQ2,SEQ_4,FCONT_1,NFCONT_3,NDIFF_3,MONOID_0,RLTOPSP1,FUNCT_7,CKB11,CKB14,CKB22,CKB31;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve r for Real;
reserve S for non  trivial RealNormSpace;
reserve T for non  trivial RealNormSpace;
reserve F for non  trivial RealNormSpace;
reserve g for (PartFunc of S,T);
reserve G for RealNormSpace-Sequence;
reserve i for (Element of ( dom G ));
reserve f for (PartFunc of ( product G ),F);
reserve x for (Element of ( product G ));
definition
let G being RealNormSpace-Sequence;
let i being (Element of ( dom G ));
let x being (Element of ( product G ));
func reproj (i,x) -> (Function of ( G . i ),( product G )) means 
:Def5: (for r being (Element of ( G . i )) holds ( it . r ) = ( x +* (i,r) ));
existence
proof
reconsider x1 = x as (Element of ( product ( carr G ) )) by CKB12:1;
defpred P[ (Element of ( G . i )),(Element of (the carrier of ( product G ))) ]
 means
$2 = ( x1 +* (i,$1) );
A1: (for r being (Element of ( G . i )) holds (ex y being (Element of (the carrier of ( product G ))) st P[ r,y ]))
proof
let r being (Element of ( G . i ));
( x1 +* (i,r) ) is (Element of (the carrier of ( product G ))) by CKB13:1;
hence thesis;
end;
(ex f being (Function of (the carrier of ( G . i )),(the carrier of ( product G ))) st (for r being (Element of ( G . i )) holds P[ r,( f . r ) ])) from FUNCT_2:sch 10(A1);
hence thesis;
end;
uniqueness
proof
let f being (Function of (the carrier of ( G . i )),(the carrier of ( product G )));
let g being (Function of (the carrier of ( G . i )),(the carrier of ( product G )));
assume that
A30: (for r being (Element of ( G . i )) holds ( f . r ) = ( x +* (i,r) ))
and
A40: (for r being (Element of ( G . i )) holds ( g . r ) = ( x +* (i,r) ));
let r being (Element of ( G . i ));
( f . r ) = ( x +* (i,r) ) by A30;
hence ( f . r ) = ( g . r ) by A40;
end;
end;
