environ
vocabularies NUMBERS,REAL_1,ZFMISC_1,NORMSP_1,PRE_TOPC,PARTFUN1,FUNCT_1,FUNCT_4,NAT_1,FDIFF_1,SUBSET_1,SEQ_4,RELAT_1,GLIB_000,LOPBAN_1,ORDINAL4,RFINSEQ,RCOMP_1,TARSKI,SEQ_1,ARYTM_3,VALUED_1,FUNCT_2,ARYTM_1,SEQ_2,ORDINAL2,SUPINF_2,FCONT_1,COMPLEX1,STRUCT_0,CARD_1,VALUED_0,XXREAL_0,GROUP_2,FUNCOP_1,XREAL_0,ORDINAL1,MEMBERED,FINSEQ_5,XXREAL_2,XBOOLE_0,CARD_3,FINSEQ_1,FINSEQ_2,AFINSQ_1,RLVECT_1,SQUARE_1,RVSUM_1,XXREAL_1,PDIFF_1,PRVECT_1,PRVECT_2,ALGSTR_0,EUCLID,CFCONT_1,RFINSEQ2,NORMSP_0,NFCONT_1,MONOID_0,RLTOPSP1;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,FUNCT_4,CARD_1,NUMBERS,XXREAL_0,XREAL_0,REAL_1,SQUARE_1,NAT_1,MEMBERED,VALUED_0,COMPLEX1,NAT_D,BINOP_2,XXREAL_2,CARD_3,FINSEQ_1,VALUED_1,FINSEQ_2,SEQ_1,SEQ_2,RVSUM_1,RFINSEQ,SEQ_4,RCOMP_1,FCONT_1,FDIFF_1,FINSEQ_5,FINSEQ_7,RFINSEQ2,STRUCT_0,MONOID_0,ALGSTR_0,PRE_TOPC,RLVECT_1,NORMSP_0,NORMSP_1,VFUNCT_1,EUCLID,LOPBAN_1,PRVECT_1,NFCONT_1,NDIFF_1,PRVECT_2,NFCONT_3,NDIFF_3,RLTOPSP1,FUNCT_7,CKB11,CKB14,CKB22,CKB23,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB42;
definitions TARSKI,FUNCT_2,RLVECT_1,LOPBAN_1,EUCLID,RFINSEQ2,FINSEQ_1,FINSEQ_2,STRUCT_0,MONOID_0,ALGSTR_0,NORMSP_0,RCOMP_1,XCMPLX_0,PRVECT_2,CKB14,CKB22,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB42;
theorems TARSKI,ABSVALUE,XBOOLE_0,XBOOLE_1,RLVECT_1,XCMPLX_0,XCMPLX_1,ZFMISC_1,SEQ_1,SEQ_2,NAT_1,RELAT_1,FUNCT_1,VFUNCT_1,FUNCT_2,FUNCT_3,FINSEQ_4,RLVECT_2,FINSEQ_3,ORDINAL1,FINSEQ_1,CARD_3,FUNCT_4,SEQ_4,NORMSP_1,LOPBAN_1,PARTFUN1,PARTFUN2,NFCONT_1,FDIFF_1,NDIFF_1,FUNCOP_1,XREAL_1,COMPLEX1,XXREAL_0,VALUED_1,VALUED_0,GRCAT_1,NORMSP_0,XREAL_0,RCOMP_1,FINSEQ_2,FINSEQ_7,RVSUM_1,SQUARE_1,PRVECT_1,PRVECT_2,PDIFF_7,EUCLID,TOPREAL7,XXREAL_2,FINSEQ_5,NAT_D,RFINSEQ2,INTEGRA5,FCONT_1,NAT_2,NFCONT_3,NDIFF_2,NDIFF_3,CARD_1,ROLLE,XXREAL_1,RLTOPSP1,FUNCT_7,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB12,CKB13,CKB14,CKB18,CKB19,CKB20,CKB21,CKB22,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70;
schemes FUNCT_2,SEQ_1,FINSEQ_1,NAT_1,FINSEQ_2;
registrations RELSET_1,STRUCT_0,ORDINAL1,XREAL_0,MEMBERED,FUNCT_1,NDIFF_1,FUNCT_2,NUMBERS,XBOOLE_0,VALUED_0,PRVECT_2,FINSEQ_2,FINSEQ_1,CARD_3,NORMSP_0,NORMSP_1,RELAT_1,XXREAL_0,LOPBAN_1,LOPBAN_2,PRVECT_3,FUNCOP_1,NAT_1,FINSEQ_5,XXREAL_2,RCOMP_1,VALUED_1,FDIFF_1,NFCONT_3,FINSET_1,XCMPLX_0,PARTFUN1,CARD_1,MONOID_0,CKB10,CKB15,CKB16,CKB17,CKB49;
constructors REAL_1,SQUARE_1,SEQ_2,FDIFF_1,NFCONT_1,RSSPACE,VFUNCT_1,NDIFF_1,SEQ_1,RELSET_1,FINSEQ_7,FINSEQ_5,RVSUM_1,BINOP_2,PRVECT_2,RLVECT_2,NAT_D,FINSEQOP,RFINSEQ,RFINSEQ2,SEQ_4,FCONT_1,NFCONT_3,NDIFF_3,MONOID_0,RLTOPSP1,FUNCT_7,CKB11,CKB14,CKB22,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB42;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve p for Real;
reserve r for Real;
reserve S for non  trivial RealNormSpace;
LmX:now
let S being RealLinearSpace;
let p being (Point of S);
let q being (Point of S);
let z1 being Real;
thus ( p + ( z1 * ( q - p ) ) ) = ( p + ( ( z1 * q ) + ( z1 * ( - p ) ) ) ) by RLVECT_1:def 5
.= ( p + ( ( z1 * q ) + ( - ( z1 * p ) ) ) ) by RLVECT_1:25
.= ( ( p + ( - ( z1 * p ) ) ) + ( z1 * q ) ) by RLVECT_1:def 3
.= ( ( ( 1 * p ) - ( z1 * p ) ) + ( z1 * q ) ) by RLVECT_1:def 8
.= ( ( ( 1 - z1 ) * p ) + ( z1 * q ) ) by RLVECT_1:35;
end;
reserve G for  non-trivial RealNormSpace-Sequence;
reserve i for (Element of ( dom G ));
reserve x for (Point of ( product G ));
theorem
XTh44: (for G being  non-trivial RealNormSpace-Sequence holds (for x,y,z,w being (Point of ( product G )) holds (for i being (Element of ( dom G )) holds (for d being Real holds (for p,q,r being (Point of ( G . i )) holds ((((((||. ( y - x ) .|| < d & ||. ( z - x ) .|| < d) & p = ( ( proj i ) . y )) & z = ( ( reproj (i,y) ) . q )) & r in [. p,q .]) & w = ( ( reproj (i,y) ) . r )) implies ||. ( w - x ) .|| < d))))))
proof
let G being  non-trivial RealNormSpace-Sequence;
let x being (Point of ( product G ));
let y being (Point of ( product G ));
let z being (Point of ( product G ));
let w being (Point of ( product G ));
let i being (Element of ( dom G ));
let d being Real;
let p being (Point of ( G . i ));
let q being (Point of ( G . i ));
let r being (Point of ( G . i ));
assume that
A2: (||. ( y - x ) .|| < d & ||. ( z - x ) .|| < d)
and
A3: (p = ( ( proj i ) . y ) & z = ( ( reproj (i,y) ) . q ))
and
A4: r in [. p,q .]
and
A5: w = ( ( reproj (i,y) ) . r );
set wx = ( w - x );
set yx = ( y - x );
set zx = ( z - x );
reconsider xi = ( ( proj i ) . x ) as (Point of ( G . i ));
r in { ( ( ( 1 - t ) * p ) + ( t * q ) ) where t is Real: (( 0 ) <= t & t <= 1) } by A4,RLTOPSP1:def 2;
then consider t being Real such that a6: ((r = ( ( ( 1 - t ) * p ) + ( t * q ) ) & ( 0 ) <= t) & t <= 1);
A6: ((r = ( p + ( t * ( q - p ) ) ) & ( 0 ) <= t) & t <= 1) by a6,LmX;
reconsider wx0 = wx,yx0 = yx,zx0 = zx as (Element of ( product ( carr G ) )) by CKB12:1;
reconsider Nwx = ( normsequence (G,wx0) ) as ( len G ) -element (FinSequence of ( REAL ));
reconsider Nyx = ( normsequence (G,yx0) ) as ( len G ) -element (FinSequence of ( REAL ));
reconsider Nzx = ( normsequence (G,zx0) ) as ( len G ) -element (FinSequence of ( REAL ));
set tyz = ( ( ( 1 - t ) * yx ) + ( t * zx ) );
reconsider tyz0 = tyz as (Element of ( product ( carr G ) )) by CKB12:1;
reconsider Ntyz = ( normsequence (G,tyz0) ) as ( len G ) -element (FinSequence of ( REAL ));
A7: 1 = ( ( 1 - t ) + t );
r = ( p + ( ( t * q ) - ( t * p ) ) ) by A6,RLVECT_1:34
.= ( ( p + ( - ( t * p ) ) ) + ( t * q ) ) by RLVECT_1:def 3
.= ( ( ( 1 * p ) - ( t * p ) ) + ( t * q ) ) by RLVECT_1:def 8
.= ( ( ( 1 - t ) * p ) + ( t * q ) ) by RLVECT_1:35;
then A8: ( r - xi ) = ( ( ( ( 1 - t ) * p ) + ( t * q ) ) - ( 1 * xi ) ) by RLVECT_1:def 8
.= ( ( ( ( 1 - t ) * p ) + ( t * q ) ) - ( ( ( 1 - t ) * xi ) + ( t * xi ) ) ) by A7,RLVECT_1:def 6
.= ( ( ( ( ( 1 - t ) * p ) + ( t * q ) ) - ( t * xi ) ) - ( ( 1 - t ) * xi ) ) by RLVECT_1:27
.= ( ( ( ( 1 - t ) * p ) + ( ( t * q ) - ( t * xi ) ) ) - ( ( 1 - t ) * xi ) ) by RLVECT_1:28
.= ( ( ( t * q ) - ( t * xi ) ) + ( ( ( 1 - t ) * p ) - ( ( 1 - t ) * xi ) ) ) by RLVECT_1:def 3
.= ( ( t * ( q - xi ) ) + ( ( ( 1 - t ) * p ) - ( ( 1 - t ) * xi ) ) ) by RLVECT_1:34
.= ( ( t * ( q - xi ) ) + ( ( 1 - t ) * ( p - xi ) ) ) by RLVECT_1:34;
reconsider Swx = wx as ( len G ) -element FinSequence;
reconsider Syz = ( ( ( 1 - t ) * yx ) + ( t * zx ) ) as ( len G ) -element FinSequence;
A9: (( dom Swx ) = ( Seg ( len G ) ) & ( dom Syz ) = ( Seg ( len G ) )) by FINSEQ_1:89;
Q2: (for k being Nat holds (k in ( dom Swx ) implies ( Swx . k ) = ( Syz . k )))
proof
let k being Nat;
assume k in ( dom Swx );
then reconsider k0 = k as (Element of ( dom G )) by A9,FINSEQ_1:def 3;
per cases ;
suppose B0: k = i;

then ( Swx . k ) = ( ( proj i ) . wx0 ) by CKB31:def 1;
then B2: ( Swx . k ) = ( ( ( proj i ) . w ) - ( ( proj i ) . x ) ) by CKB55:1;
B3: ( ( proj i ) . z ) = q by A3,CKB65:1;
( Syz . k ) = ( ( proj i ) . tyz0 ) by B0,CKB31:def 1;
then ( Syz . k ) = ( ( ( proj i ) . ( ( 1 - t ) * yx ) ) + ( ( proj i ) . ( t * zx ) ) ) by CKB53:1;
then ( Syz . k ) = ( ( ( 1 - t ) * ( ( proj i ) . yx ) ) + ( ( proj i ) . ( t * zx ) ) ) by CKB58:1;
then ( Syz . k ) = ( ( ( 1 - t ) * ( ( proj i ) . yx ) ) + ( t * ( ( proj i ) . zx ) ) ) by CKB58:1;
then ( Syz . k ) = ( ( ( 1 - t ) * ( ( ( proj i ) . y ) - ( ( proj i ) . x ) ) ) + ( t * ( ( proj i ) . zx ) ) ) by CKB55:1;
then ( Syz . k ) = ( ( ( 1 - t ) * ( p - xi ) ) + ( t * ( q - xi ) ) ) by A3,B3,CKB55:1;
hence ( Swx . k ) = ( Syz . k ) by B2,A8,A5,CKB65:1;
end;
suppose k <> i;

then B4: (( ( proj k0 ) . y ) = ( ( proj k0 ) . w ) & ( ( proj k0 ) . z ) = ( ( proj k0 ) . y )) by A3,A5,CKB68:1;
( Swx . k ) = ( ( proj k0 ) . wx0 ) by CKB31:def 1;
then B5: ( Swx . k ) = ( ( ( proj k0 ) . w ) - ( ( proj k0 ) . x ) ) by CKB55:1;
( Syz . k ) = ( ( proj k0 ) . tyz0 ) by CKB31:def 1
.= ( ( ( proj k0 ) . ( ( 1 - t ) * yx ) ) + ( ( proj k0 ) . ( t * zx ) ) ) by CKB53:1
.= ( ( ( 1 - t ) * ( ( proj k0 ) . yx ) ) + ( ( proj k0 ) . ( t * zx ) ) ) by CKB58:1
.= ( ( ( 1 - t ) * ( ( proj k0 ) . yx ) ) + ( t * ( ( proj k0 ) . zx ) ) ) by CKB58:1;
then ( Syz . k ) = ( ( ( 1 - t ) * ( ( ( proj k0 ) . y ) - ( ( proj k0 ) . x ) ) ) + ( t * ( ( proj k0 ) . zx ) ) ) by CKB55:1;
then ( Syz . k ) = ( ( ( 1 - t ) * ( ( ( proj k0 ) . y ) - ( ( proj k0 ) . x ) ) ) + ( t * ( ( ( proj k0 ) . y ) - ( ( proj k0 ) . x ) ) ) ) by B4,CKB55:1;
then ( Syz . k ) = ( ( ( ( 1 - t ) * ( ( proj k0 ) . y ) ) - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) + ( t * ( ( ( proj k0 ) . y ) - ( ( proj k0 ) . x ) ) ) ) by RLVECT_1:34;
then ( Syz . k ) = ( ( ( ( 1 - t ) * ( ( proj k0 ) . y ) ) - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) + ( ( t * ( ( proj k0 ) . y ) ) - ( t * ( ( proj k0 ) . x ) ) ) ) by RLVECT_1:34;
then ( Syz . k ) = ( ( ( ( ( 1 - t ) * ( ( proj k0 ) . y ) ) - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) + ( t * ( ( proj k0 ) . y ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) by RLVECT_1:def 3;
then ( Syz . k ) = ( ( ( ( 1 - t ) * ( ( proj k0 ) . y ) ) - ( ( ( 1 - t ) * ( ( proj k0 ) . x ) ) - ( t * ( ( proj k0 ) . y ) ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) by RLVECT_1:29;
then ( Syz . k ) = ( ( ( ( 1 - t ) * ( ( proj k0 ) . y ) ) + ( ( t * ( ( proj k0 ) . y ) ) + ( - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) by RLVECT_1:33;
then ( Syz . k ) = ( ( ( ( ( 1 - t ) * ( ( proj k0 ) . y ) ) + ( t * ( ( proj k0 ) . y ) ) ) + ( - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) by RLVECT_1:def 3;
then ( Syz . k ) = ( ( ( ( ( 1 - t ) + t ) * ( ( proj k0 ) . y ) ) + ( - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) by RLVECT_1:def 6;
then ( Syz . k ) = ( ( ( ( proj k0 ) . y ) + ( - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) by RLVECT_1:def 8;
then ( Syz . k ) = ( ( ( proj k0 ) . y ) + ( ( - ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) - ( t * ( ( proj k0 ) . x ) ) ) ) by RLVECT_1:28;
then ( Syz . k ) = ( ( ( proj k0 ) . y ) + ( - ( ( t * ( ( proj k0 ) . x ) ) + ( ( 1 - t ) * ( ( proj k0 ) . x ) ) ) ) ) by RLVECT_1:30;
then ( Syz . k ) = ( ( ( proj k0 ) . y ) + ( - ( ( t + ( 1 - t ) ) * ( ( proj k0 ) . x ) ) ) ) by RLVECT_1:def 6;
hence ( Swx . k ) = ( Syz . k ) by B5,B4,RLVECT_1:def 8;
end;
end;
P2: (( len Nwx ) = ( len G ) & ( len Ntyz ) = ( len G )) by CARD_1:def 7;
(for k being (Element of ( NAT )) holds (k in ( Seg ( len Nwx ) ) implies (( 0 ) <= ( Nwx . k ) & ( Nwx . k ) <= ( Ntyz . k ))))
proof
let k being (Element of ( NAT ));
assume Q3: k in ( Seg ( len Nwx ) );
then reconsider k1 = k as (Element of ( dom G )) by P2,FINSEQ_1:def 3;
reconsider wxk = ( wx0 . k1 ) as (Element of ( G . k1 ));
Q1: ( Nwx . k ) = ||. wxk .|| by PRVECT_2:def 11;
( wx0 . k1 ) = ( Syz . k ) by Q2,Q3,P2,A9;
hence thesis by Q1,PRVECT_2:def 11;
end;
then P3: |. Nwx .| <= |. Ntyz .| by P2,PRVECT_2:2;
P4: ||. ( w - x ) .|| = ( ( productnorm G ) . wx ) by PRVECT_2:def 13;
||. ( ( ( 1 - t ) * yx ) + ( t * zx ) ) .|| = ( ( productnorm G ) . tyz ) by PRVECT_2:def 13
.= |. ( normsequence (G,tyz0) ) .| by PRVECT_2:def 12;
then P5: ||. ( w - x ) .|| <= ||. ( ( ( 1 - t ) * yx ) + ( t * zx ) ) .|| by P3,P4,PRVECT_2:def 12;
P7: ||. ( ( ( 1 - t ) * yx ) + ( t * zx ) ) .|| <= ( ( ( abs ( 1 - t ) ) * ||. ( y - x ) .|| ) + ( ( abs t ) * ||. ( z - x ) .|| ) ) by NORMSP_1:5;
( 1 - t ) >= ( 0 ) by A6,XREAL_1:48;
then P8: (( abs ( 1 - t ) ) = ( 1 - t ) & ( abs t ) = t) by A6,ABSVALUE:def 1;
( ( ( abs ( 1 - t ) ) * ||. ( y - x ) .|| ) + ( ( abs t ) * ||. ( z - x ) .|| ) ) < d
proof
per cases ;
suppose (t = 1 or t = ( 0 ));

hence thesis by A2,P8;
end;
suppose (t <> 1 & t <> ( 0 ));

then (( 0 ) < t & t < 1) by A6,XXREAL_0:1;
then (( 0 ) < t & ( 1 - t ) > ( 0 )) by XREAL_1:50;
then (( ( abs ( 1 - t ) ) * ||. ( y - x ) .|| ) < ( ( 1 - t ) * d ) & ( ( abs t ) * ||. ( z - x ) .|| ) < ( t * d )) by A2,P8,XREAL_1:68;
then ( ( ( abs ( 1 - t ) ) * ||. ( y - x ) .|| ) + ( ( abs t ) * ||. ( z - x ) .|| ) ) < ( ( ( 1 - t ) * d ) + ( t * d ) ) by XREAL_1:8;
hence thesis;
end;
end;
then ||. ( ( ( 1 - t ) * yx ) + ( t * zx ) ) .|| < d by P7,XXREAL_0:2;
hence ||. ( w - x ) .|| < d by P5,XXREAL_0:2;
end;
