environ
vocabularies NUMBERS,INT_1,XXREAL_0,CARD_1,ARYTM_1,ARYTM_3,SUBSET_1,VECTSP_1,VECTSP_2,STRUCT_0,XBOOLE_0,ALGSTR_0,SUPINF_2,NEWTON,RELAT_1,GROUP_1,BINOP_1,RLVECT_1,MESFUNC1,LATTICES,ALGSTR_1,FINSEQ_1,PARTFUN1,CARD_3,NAT_1,FUNCT_1,ORDINAL4,FINSEQ_2,TARSKI,MATRIX_1,TREES_1,INCSP_1,FVSUM_1,RVSUM_1,ZFMISC_1,ALGSEQ_1,POLYNOM1,COMPLEX1,MCART_1,POLYNOM2,POLYNOM3,POLYNOM8;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,FUNCT_2,NUMBERS,XCMPLX_0,XXREAL_0,VECTSP_2,BINOP_1,BINOM,ALGSTR_1,PARTFUN1,FINSEQ_1,FINSEQ_2,INT_1,NAT_1,NAT_D,STRUCT_0,ALGSTR_0,RLVECT_1,GROUP_1,VECTSP_1,FVSUM_1,ALGSEQ_1,POLYNOM5,POLYNOM3,MATRIX_1,MATRIX_3,POLYNOM4,MCART_1,INT_2,CKB9,CKB15,CKB19;
definitions VECTSP_1,RLVECT_1,BINOM,FINSEQ_1,MATRIX_1,POLYNOM3,CKB9,CKB15,CKB19;
theorems FVSUM_1,GROUP_1,BINOM,VECTSP_1,ALGSEQ_1,NAT_1,FINSEQ_4,INT_1,FUNCT_2,XREAL_1,VECTSP_2,ALGSTR_1,MATRIX_1,FUNCT_1,MATRIX_3,FINSEQ_1,ZFMISC_1,COMPLEX1,RLVECT_1,POLYNOM4,TARSKI,MCART_1,FINSEQ_2,POLYNOM1,ABSVALUE,POLYNOM3,POLYNOM5,FINSEQ_3,ORDINAL1,XXREAL_0,FUNCOP_1,PARTFUN1,XREAL_0,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30;
schemes NAT_1,FUNCT_2,MATRIX_1,FINSEQ_1,INT_1;
registrations XBOOLE_0,ORDINAL1,RELSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,STRUCT_0,VECTSP_1,ALGSTR_1,GCD_1,POLYNOM3,CARD_1,FINSEQ_1,CKB4,CKB16;
constructors REAL_1,SQUARE_1,NAT_D,VECTSP_2,ALGSTR_2,TOPREAL1,MATRIX_3,POLYNOM1,POLYNOM4,POLYNOM5,BINOM,RELSET_1,FVSUM_1,CKB9,CKB15,CKB19;
requirements NUMERALS,SUBSET,REAL,BOOLE,ARITHM;
begin
theorem
Th19: (for L being Field holds (for j being Integer holds (for x being (Element of L) holds (x <> ( 0. L ) implies ( pow (x,( j + 1 )) ) = ( ( pow (x,j) ) * ( pow (x,1) ) )))))
proof
let L being Field;
let j being Integer;
let x being (Element of L);
A1: ( pow (x,( - 1 )) ) = ( ( x |^ ( abs ( - 1 ) ) ) " ) by CKB19:def 1;
assume A2: x <> ( 0. L );
then ( x |^ ( abs ( - 1 ) ) ) <> ( 0. L ) by CKB3:1;
then A3: ( pow (x,( - 1 )) ) <> ( 0. L ) by A1,VECTSP_1:25;
A4: ( pow (x,( - j )) ) <> ( 0. L )
proof
per cases ;
suppose ( 0 ) <= ( - j );

then reconsider k = ( - j ) as (Element of ( NAT )) by INT_1:3;
( pow (x,( - j )) ) = ( x |^ k ) by CKB19:def 1;
hence thesis by A2,CKB3:1;
end;
suppose A5: ( - j ) < ( 0 );

A6: ( x |^ ( abs ( - j ) ) ) <> ( 0. L ) by A2,CKB3:1;
( pow (x,( - j )) ) = ( ( x |^ ( abs ( - j ) ) ) " ) by A5,CKB19:def 1;
hence thesis by A6,VECTSP_1:25;
end;
end;
A7: ( pow (x,( j + 1 )) ) <> ( 0. L )
proof
per cases ;
suppose ( 0 ) <= ( j + 1 );

then reconsider k = ( j + 1 ) as (Element of ( NAT )) by INT_1:3;
( pow (x,( j + 1 )) ) = ( x |^ k ) by CKB19:def 1;
hence thesis by A2,CKB3:1;
end;
suppose A8: ( j + 1 ) < ( 0 );

A9: ( x |^ ( abs ( j + 1 ) ) ) <> ( 0. L ) by A2,CKB3:1;
( pow (x,( j + 1 )) ) = ( ( x |^ ( abs ( j + 1 ) ) ) " ) by A8,CKB19:def 1;
hence thesis by A9,VECTSP_1:25;
end;
end;
A10:now
per cases  by CKB1:1;
suppose A11: j >= ( 0 );

then reconsider n = j as (Element of ( NAT )) by INT_1:3;
A12: ( n + 1 ) = ( abs ( j + 1 ) ) by ABSVALUE:def 1;
( pow (x,( abs j )) ) = ( x |^ ( abs j ) ) by CKB19:def 1;
then A13: ( pow (x,( abs j )) ) <> ( 0. L ) by A2,CKB3:1;
( pow (x,( abs ( j + 1 ) )) ) = ( x |^ ( abs ( j + 1 ) ) ) by CKB19:def 1;
then A14: ( pow (x,( abs ( j + 1 ) )) ) <> ( 0. L ) by A2,CKB3:1;
( n + 1 ) >= ( 0 );
hence ( ( pow (x,( j + 1 )) ) * ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) ) = ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) ) by ABSVALUE:def 1
.= ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( x " ) * ( pow (x,( - j )) ) ) ) by CKB24:1
.= ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( x " ) * ( ( pow (x,j) ) " ) ) ) by A2,CKB30:1
.= ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( x " ) * ( ( pow (x,( abs j )) ) " ) ) ) by A11,ABSVALUE:def 1
.= ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( x * ( pow (x,( abs j )) ) ) " ) ) by A2,A13,CKB5:1
.= ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( pow (x,( ( abs j ) + 1 )) ) " ) ) by CKB27:1
.= ( ( pow (x,( abs ( j + 1 ) )) ) * ( ( pow (x,( abs ( j + 1 ) )) ) " ) ) by A12,ABSVALUE:def 1
.= ( 1. L ) by A14,VECTSP_1:def 10;
end;
suppose A15: j < ( - 1 );

A16: ( pow (x,( - j )) ) <> ( 0. L )
proof
reconsider k = ( - j ) as (Element of ( NAT )) by A15,INT_1:3;
( pow (x,( - j )) ) = ( x |^ k ) by CKB19:def 1;
hence thesis by A2,CKB3:1;
end;
( pow (x,( abs ( j + 1 ) )) ) = ( x |^ ( abs ( j + 1 ) ) ) by CKB19:def 1;
then A17: ( pow (x,( abs ( j + 1 ) )) ) <> ( 0. L ) by A2,CKB3:1;
A18: ( j + 1 ) < ( ( - 1 ) + 1 ) by A15,XREAL_1:6;
hence ( ( pow (x,( j + 1 )) ) * ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) ) = ( ( ( pow (x,( abs ( j + 1 ) )) ) " ) * ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) ) by CKB21:1
.= ( ( ( pow (x,( abs ( j + 1 ) )) ) " ) * ( ( x " ) * ( pow (x,( - j )) ) ) ) by CKB24:1
.= ( ( ( ( pow (x,( abs ( j + 1 ) )) ) " ) * ( x " ) ) * ( pow (x,( - j )) ) ) by GROUP_1:def 3
.= ( ( ( ( pow (x,( abs ( j + 1 ) )) ) * x ) " ) * ( pow (x,( - j )) ) ) by A2,A17,CKB5:1
.= ( ( ( pow (x,( ( abs ( j + 1 ) ) + 1 )) ) " ) * ( pow (x,( - j )) ) ) by CKB27:1
.= ( ( ( pow (x,( ( - ( j + 1 ) ) + 1 )) ) " ) * ( pow (x,( - j )) ) ) by A18,ABSVALUE:def 1
.= ( 1. L ) by A16,VECTSP_1:def 10;
end;
suppose A19: j = ( - 1 );

A20: ( x " ) <> ( 0. L ) by A2,VECTSP_1:25;
thus ( ( pow (x,( j + 1 )) ) * ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) ) = ( ( 1. L ) * ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) ) by A19,CKB20:1
.= ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) by VECTSP_1:def 8
.= ( ( x " ) * ( pow (x,( - j )) ) ) by CKB24:1
.= ( ( x " ) * ( ( pow (x,j) ) " ) ) by A2,CKB30:1
.= ( ( x " ) * ( ( x " ) " ) ) by A19,CKB24:1
.= ( 1. L ) by A20,VECTSP_1:def 10;
end;
end;
A21: ( pow (x,( j + 1 )) ) <> ( 0. L )
proof
per cases ;
suppose ( 0 ) <= ( j + 1 );

then reconsider k = ( j + 1 ) as (Element of ( NAT )) by INT_1:3;
( pow (x,( j + 1 )) ) = ( x |^ k ) by CKB19:def 1;
hence thesis by A2,CKB3:1;
end;
suppose A22: ( j + 1 ) < ( 0 );

A23: ( x |^ ( abs ( j + 1 ) ) ) <> ( 0. L ) by A2,CKB3:1;
( pow (x,( j + 1 )) ) = ( ( x |^ ( abs ( j + 1 ) ) ) " ) by A22,CKB19:def 1;
hence thesis by A23,VECTSP_1:25;
end;
end;
( ( pow (x,( j + 1 )) ) * ( pow (x,( - ( j + 1 ) )) ) ) = ( ( pow (x,( j + 1 )) ) * ( ( pow (x,( j + 1 )) ) " ) ) by A2,CKB30:1
.= ( 1. L ) by A7,VECTSP_1:def 10;
then A24: ( pow (x,( - ( j + 1 ) )) ) = ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) by A10,A21,VECTSP_1:5;
thus ( pow (x,( j + 1 )) ) = ( pow (x,( - ( - ( j + 1 ) ) )) )
.= ( ( ( pow (x,( - 1 )) ) * ( pow (x,( - j )) ) ) " ) by A2,A24,CKB30:1
.= ( ( ( pow (x,( - j )) ) " ) * ( ( pow (x,( - 1 )) ) " ) ) by A4,A3,CKB5:1
.= ( ( pow (x,( - ( - j ) )) ) * ( ( pow (x,( - 1 )) ) " ) ) by A2,CKB30:1
.= ( ( pow (x,j) ) * ( pow (x,( - ( - 1 ) )) ) ) by A2,CKB30:1
.= ( ( pow (x,j) ) * ( pow (x,1) ) );
end;
