environ
vocabularies XBOOLE_0,STRUCT_0,MSUALG_1,PBOOLE,FINSET_1,SUBSET_1,CLOSURE2,TARSKI,RELAT_1,FUNCT_1,FINSEQ_1,MARGREL1,NAT_1,PRALG_2,CARD_3,RLVECT_2,MSAFREE,PRELAMB,ZFMISC_1,PRALG_1,MCART_1,EQREL_1,FUNCOP_1,MSUALG_3,TREES_4,LANG1,NUMBERS,MSUALG_2,MEMBER_1,GROUP_6,WELLORD1,PARTFUN1,FUNCT_6,FINSEQ_4,PZFMISC1,CARD_1,MSUALG_4,MSUALG_5,SETFAM_1,FUNCT_4,RELAT_2,MSUALG_9;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,NAT_1,RELAT_1,RELAT_2,STRUCT_0,SETFAM_1,FUNCT_1,PBOOLE,EQREL_1,RELSET_1,PARTFUN1,FUNCT_2,FINSEQ_1,LANG1,MCART_1,FINSET_1,CARD_3,TREES_4,FUNCT_6,DTCONSTR,MSUALG_1,MSUALG_2,PRALG_1,PRALG_3,MSUALG_3,MSAFREE,PRALG_2,FUNCOP_1,MSAFREE2,MSUALG_4,PZFMISC1,MSSUBFAM,CLOSURE2,MSUALG_5;
definitions FINSEQ_1,FUNCT_1,MSAFREE2,FINSET_1,MSUALG_1,MSUALG_3,PZFMISC1,MSUALG_4,PBOOLE,TARSKI,XBOOLE_0;
theorems CARD_3,CLOSURE1,CLOSURE2,EXTENS_1,EQREL_1,FINSEQ_1,FUNCOP_1,FUNCT_1,FUNCT_2,MCART_1,MSAFREE,MSAFREE2,MSSUBFAM,MSUALG_1,MSUALG_2,MSUALG_3,MSUALG_4,MSUALG_5,MSUALG_6,MSUALG_7,PARTFUN1,PBOOLE,PRALG_1,PRALG_2,PZFMISC1,RELAT_2,SETFAM_1,TARSKI,RELSET_1,XBOOLE_0,XBOOLE_1,ORDERS_1,RELAT_1,FINSET_1,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19;
schemes MSSUBFAM,PBOOLE,MSUALG_8;
registrations XBOOLE_0,RELAT_1,ORDINAL1,FUNCT_2,FUNCOP_1,FINSET_1,EQREL_1,PRE_CIRC,PZFMISC1,MSSUBFAM,STRUCT_0,FUNCT_1,MSUALG_1,MSUALG_2,PRALG_2,MSUALG_3,MSAFREE,MSUALG_4,MSUALG_5,CLOSURE2,CARD_3,RELSET_1,PRALG_1,PBOOLE,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
constructors SETFAM_1,BINOP_1,PZFMISC1,MSUALG_3,MSAFREE2,MSUALG_5,CLOSURE1,CLOSURE2,PRALG_3,RELSET_1,CIRCUIT1,NAT_1,FUNCT_6,FUNCT_5;
requirements SUBSET,BOOLE;
begin
reserve S for non  empty non  void ManySortedSign;
theorem
(for S being non  empty ManySortedSign holds (for A being  non-empty MSAlgebra over S holds (for f,g being (Element of ( product (the Sorts of A) )) holds ((for i being set holds ( ( proj ((the Sorts of A),i) ) . f ) = ( ( proj ((the Sorts of A),i) ) . g )) implies f = g))))
proof
let S being non  empty ManySortedSign;
let A being  non-empty MSAlgebra over S;
let f being (Element of ( product (the Sorts of A) ));
let g being (Element of ( product (the Sorts of A) ));
assume that
A1: (for i being set holds ( ( proj ((the Sorts of A),i) ) . f ) = ( ( proj ((the Sorts of A),i) ) . g ));
set X = (the Sorts of A);
now
thus ( dom f ) = ( dom X ) by CARD_3:9
.= ( dom g ) by CARD_3:9;
let x being set;
assume that
x in ( dom f );
A2: ( dom ( proj (X,x) ) ) = ( product X ) by CARD_3:def 16;
hence ( f . x ) = ( ( proj (X,x) ) . f ) by CARD_3:def 16
.= ( ( proj (X,x) ) . g ) by A1
.= ( g . x ) by A2,CARD_3:def 16;
end;
hence thesis by FUNCT_1:2;
end;
