environ
vocabularies FUNCT_1,RELAT_1,XBOOLE_0,TARSKI,SUBSET_1,ZFMISC_1,RELAT_2,PARTFUN1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELAT_2,RELSET_1,FUNCT_1,CKB5,CKB11,CKB18,CKB29,CKB48,CKB56,CKB64;
definitions TARSKI,FUNCT_1,XBOOLE_0,RELAT_1,RELAT_2,CKB29,CKB48,CKB56,CKB64;
theorems TARSKI,FUNCT_1,GRFUNC_1,ZFMISC_1,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,RELAT_2,CKB1,CKB2,CKB6,CKB7,CKB8,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81;
schemes FUNCT_1,XBOOLE_0,CKB3,CKB9,CKB10;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,CKB4,CKB49,CKB50,CKB57;
constructors FUNCT_1,RELAT_2,RELSET_1,CKB11,CKB18,CKB29,CKB48,CKB56,CKB64;
requirements SUBSET,BOOLE;
begin
reserve x for set;
reserve y9 for set;
reserve y1 for set;
reserve y2 for set;
reserve z for set;
reserve X for set;
reserve Y for set;
theorem
Th162: (for f,g being (PartFunc of X,Y) holds (((Y = ( {} ) implies X = ( {} )) & f tolerates g) implies (ex h being (PartFunc of X,Y) st ((h is  total & f tolerates h) & g tolerates h))))
proof
let f being (PartFunc of X,Y);
let g being (PartFunc of X,Y);
assume that
A1: (Y = ( {} ) implies X = ( {} ))
and
A2: f tolerates g;
now
per cases ;
suppose A3: Y = ( {} );

then (f tolerates <: ( {} ),X,Y :> & g tolerates <: ( {} ),X,Y :>);
hence thesis by A1,A3;
end;
suppose A4: Y <> ( {} );

set y = the (Element of Y);
defpred P[ set,set ]
 means
((($1 in ( dom f ) implies $2 = ( f . $1 )) & ($1 in ( dom g ) implies $2 = ( g . $1 ))) & (((not $1 in ( dom f )) & (not $1 in ( dom g ))) implies $2 = y));
A5: (for x holds (x in X implies (ex y9 st P[ x,y9 ])))
proof
let x;
assume that
x in X;
now
per cases ;
suppose A6: (x in ( dom f ) & x in ( dom g ));

take y9 = ( f . x );
thus (x in ( dom f ) implies y9 = ( f . x ));
x in ( ( dom f ) /\ ( dom g ) ) by A6,XBOOLE_0:def 4;
hence (x in ( dom g ) implies y9 = ( g . x )) by A2,CKB64:def 1;
thus (((not x in ( dom f )) & (not x in ( dom g ))) implies y9 = y) by A6;
end;
suppose A7: (x in ( dom f ) & (not x in ( dom g )));

take y9 = ( f . x );
thus (((x in ( dom f ) implies y9 = ( f . x )) & (x in ( dom g ) implies y9 = ( g . x ))) & (((not x in ( dom f )) & (not x in ( dom g ))) implies y9 = y)) by A7;
end;
suppose A8: ((not x in ( dom f )) & x in ( dom g ));

take y9 = ( g . x );
thus (((x in ( dom f ) implies y9 = ( f . x )) & (x in ( dom g ) implies y9 = ( g . x ))) & (((not x in ( dom f )) & (not x in ( dom g ))) implies y9 = y)) by A8;
end;
suppose ((not x in ( dom f )) & (not x in ( dom g )));

hence thesis;
end;
end;
hence thesis;
end;
A9: (for x holds (for y1 holds (for y2 holds (((x in X & P[ x,y1 ]) & P[ x,y2 ]) implies y1 = y2))));
consider h being Function such that A10: ( dom h ) = X and A11: (for x holds (x in X implies P[ x,( h . x ) ])) from FUNCT_1:sch 2(A9,A5);
( rng h ) c= Y
proof
let z;
assume z in ( rng h );
then consider x such that A12: x in ( dom h ) and A13: z = ( h . x ) by FUNCT_1:def 3;
per cases ;
suppose A14: (x in ( dom f ) & x in ( dom g ));

then z = ( f . x ) by A11,A13;
hence thesis by A14,CKB7:1;
end;
suppose A15: (x in ( dom f ) & (not x in ( dom g )));

then z = ( f . x ) by A11,A13;
hence thesis by A15,CKB7:1;
end;
suppose A16: ((not x in ( dom f )) & x in ( dom g ));

then z = ( g . x ) by A11,A13;
hence thesis by A16,CKB7:1;
end;
suppose ((not x in ( dom f )) & (not x in ( dom g )));

then z = y by A10,A11,A12,A13;
hence thesis by A4;
end;
end;
then reconsider h9 = h as (PartFunc of X,Y) by A10,RELSET_1:4;
A17: f tolerates h
proof
let x;
assume x in ( ( dom f ) /\ ( dom h ) );
then x in ( dom f ) by XBOOLE_0:def 4;
hence thesis by A11;
end;
A18: g tolerates h
proof
let x;
assume x in ( ( dom g ) /\ ( dom h ) );
then x in ( dom g ) by XBOOLE_0:def 4;
hence thesis by A11;
end;
h9 is  total by A10,CKB48:def 1;
hence thesis by A17,A18;
end;
end;
hence thesis;
end;
