environ
vocabularies XBOOLE_0,RELAT_2,RELAT_1,EQREL_1,WELLORD1,ZFMISC_1,PARTFUN1,SUBSET_1,TARSKI,ORDINAL1,TOLER_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELSET_1,RELAT_2,PARTFUN1,ORDINAL1,WELLORD1,EQREL_1;
definitions TARSKI,RELAT_1,RELAT_2,WELLORD1;
theorems TARSKI,RELAT_1,RELSET_1,RELAT_2,ZFMISC_1,WELLORD1,ENUMSET1,ORDERS_1,EQREL_1,ORDINAL1,XBOOLE_0,XBOOLE_1,PARTFUN1;
schemes XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELAT_1,PARTFUN1,EQREL_1,RELSET_1;
constructors ORDINAL1,WELLORD1,EQREL_1,RELSET_1;
requirements SUBSET,BOOLE;
begin
reserve x for set;
reserve y for set;
reserve z for set;
registration
cluster  empty ->  reflexive  irreflexive  symmetric  antisymmetric  asymmetric  connected  strongly_connected  transitive for Relation;
coherence
proof
let R being Relation;
assume that
A1: R is  empty;
(x in ( {} ) implies [ x,x ] in ( {} ));
then ( {} ) is_reflexive_in ( field ( {} ) ) by RELAT_2:def 1;
hence R is  reflexive by A1,RELAT_2:def 9;
( {} ) is_irreflexive_in ( field ( {} ) )
proof
let x;
assume x in ( field ( {} ) );
thus thesis;
end;
hence R is  irreflexive by A1,RELAT_2:def 10;
thus R is  symmetric
proof
let x;
let y;
assume that
x in ( field R )
and
y in ( field R )
and
A2: [ x,y ] in R;
thus thesis by A1,A2;
end;

( {} ) is_antisymmetric_in ( field ( {} ) )
proof
let x;
let y;
assume that
A3: x in ( field ( {} ) )
and
y in ( field ( {} ) )
and
[ x,y ] in ( {} )
and
[ y,x ] in ( {} );
thus thesis by A3;
end;
hence R is  antisymmetric by A1,RELAT_2:def 12;
( {} ) is_asymmetric_in ( field ( {} ) )
proof
let x;
let y;
assume that
x in ( field ( {} ) )
and
y in ( field ( {} ) )
and
[ x,y ] in ( {} );
thus thesis;
end;
hence R is  asymmetric by A1,RELAT_2:def 13;
( {} ) is_connected_in ( field ( {} ) )
proof
let x;
let y;
assume that
A4: x in ( field ( {} ) )
and
y in ( field ( {} ) )
and
x <> y;
thus thesis by A4;
end;
hence R is  connected by A1,RELAT_2:def 14;
( {} ) is_strongly_connected_in ( field ( {} ) )
proof
let x;
let y;
assume that
A5: x in ( field ( {} ) )
and
y in ( field ( {} ) );
thus thesis by A5;
end;
hence R is  strongly_connected by A1,RELAT_2:def 15;
( {} ) is_transitive_in ( field ( {} ) )
proof
let x;
let y;
let z;
assume that
A6: x in ( field ( {} ) )
and
y in ( field ( {} ) )
and
z in ( field ( {} ) )
and
[ x,y ] in ( {} )
and
[ y,z ] in ( {} );
thus thesis by A6;
end;
hence R is  transitive by A1,RELAT_2:def 16;
end;
end;
