environ
vocabularies PRE_TOPC,SUBSET_1,XBOOLE_0,TARSKI,TOPS_1,RCOMP_1,SETFAM_1,ZFMISC_1,STRUCT_0,BINOP_1,FUNCT_1,MCART_1,LATTICES,EQREL_1,REALSET1,NAT_LAT,TDLAT_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,REALSET1,STRUCT_0,PRE_TOPC,LATTICES,BINOP_1,TOPS_1,FUNCT_1,DOMAIN_1,FUNCT_2,NAT_LAT,CKB30,CKB32,CKB33,CKB34,CKB35,CKB37,CKB38,CKB41,CKB42,CKB44,CKB45,CKB48,CKB49;
definitions TARSKI,LATTICES,NAT_LAT,XBOOLE_0,BINOP_1,REALSET1,SUBSET_1,STRUCT_0,CKB30,CKB32,CKB34,CKB37,CKB38,CKB41,CKB44,CKB48,CKB49;
theorems TOPS_1,PRE_TOPC,LATTICE2,BINOP_1,ZFMISC_1,FUNCT_2,SUBSET_1,MCART_1,FUNCT_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB34,CKB36,CKB37,CKB38,CKB40,CKB41,CKB43,CKB44,CKB46,CKB47,CKB48,CKB49,CKB51;
schemes FUNCT_2,BINOP_2;
registrations SUBSET_1,RELSET_1,REALSET1,LATTICES,TOPS_1,RELAT_1,PRE_TOPC,CKB31,CKB39,CKB50;
constructors PARTFUN1,BINOP_1,REALSET1,TOPS_1,NAT_LAT,CKB30,CKB32,CKB34,CKB37,CKB38,CKB41,CKB44,CKB48,CKB49;
requirements BOOLE,SUBSET;
begin
reserve T for TopSpace;
definition
let T being TopSpace;
func Open_Domains_Union T -> (BinOp of ( Open_Domains_of T )) means 
:Def10: (for A,B being (Element of ( Open_Domains_of T )) holds ( it . (A,B) ) = ( Int ( Cl ( A \/ B ) ) ));
existence
proof
defpred X[ set,set ]
 means
(for A,B being (Element of ( Open_Domains_of T )) holds ($1 = [ A,B ] implies $2 = ( Int ( Cl ( A \/ B ) ) )));
set D = [: ( Open_Domains_of T ),(( Open_Domains_of T ) qua non  empty set) :];
A1: (for a being (Element of D) holds (ex b being (Element of ( Open_Domains_of T )) st X[ a,b ]))
proof
let a being (Element of D);
reconsider G = ( a `1 ),F = ( a `2 ) as (Element of ( Open_Domains_of T ));
( Int ( Cl ( G \/ F ) ) ) is  open_condensed by CKB23:1;
then ( Int ( Cl ( G \/ F ) ) ) in { E where E is (Subset of T): E is  open_condensed };
then reconsider b = ( Int ( Cl ( G \/ F ) ) ) as (Element of ( Open_Domains_of T ));
take b;
let A being (Element of ( Open_Domains_of T ));
let B being (Element of ( Open_Domains_of T ));
assume a = [ A,B ];
then A2: [ A,B ] = [ G,F ] by MCART_1:21;
then A = G by ZFMISC_1:27;
hence thesis by A2,ZFMISC_1:27;
end;
consider h being (Function of D,( Open_Domains_of T )) such that A3: (for a being (Element of D) holds X[ a,( h . a ) ]) from FUNCT_2:sch 3(A1);
take h;
let A being (Element of ( Open_Domains_of T ));
let B being (Element of ( Open_Domains_of T ));
thus ( h . (A,B) ) = ( h . [ A,B ] )
.= ( Int ( Cl ( A \/ B ) ) ) by A3;
end;
uniqueness
proof
deffunc U((Element of ( Open_Domains_of T )),(Element of ( Open_Domains_of T ))) = ( Int ( Cl ( $1 \/ $2 ) ) );
thus (for o1,o2 being (BinOp of ( Open_Domains_of T )) holds (((for a,b being (Element of ( Open_Domains_of T )) holds ( o1 . (a,b) ) = U(a,b)) & (for a,b being (Element of ( Open_Domains_of T )) holds ( o2 . (a,b) ) = U(a,b))) implies o1 = o2)) from BINOP_2:sch 2;
end;
end;
