environ
vocabularies STRUCT_0,SUBSET_1,PRE_TOPC,XBOOLE_0,RCOMP_1,TARSKI,TOPS_1;
notations TARSKI,XBOOLE_0,SUBSET_1,STRUCT_0,PRE_TOPC;
definitions TARSKI,XBOOLE_0,PRE_TOPC,SUBSET_1,STRUCT_0;
theorems PRE_TOPC,TARSKI,SUBSET_1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB4,CKB6,CKB9,CKB10,CKB11,CKB14,CKB15,CKB18,CKB19,CKB20,CKB21,CKB22;
registrations XBOOLE_0,SUBSET_1,STRUCT_0,PRE_TOPC,CKB3,CKB5,CKB7,CKB8,CKB12,CKB13,CKB16,CKB17;
constructors SETFAM_1,PRE_TOPC;
requirements BOOLE,SUBSET;
begin
reserve GX for TopStruct;
reserve R for (Subset of GX);
definition
let GX being TopStruct;
let R being (Subset of GX);
func Int R -> (Subset of GX) equals 
( ( Cl ( R ` ) ) ` );
coherence;
projectivity;
end;
