environ
vocabularies NUMBERS,CARD_1,XBOOLE_0,TARSKI,RELAT_2,LATTICE3,ORDERS_2,SUBSET_1,LATTICES,EQREL_1,XXREAL_0,WAYBEL_0,YELLOW_1,STRUCT_0,CAT_1,LATTICE5,WELLORD1,FUNCT_1,SEQM_3,YELLOW_0,RELAT_1,ORDINAL2,MEASURE5,FINSET_1,ORDERS_1,REWRITE1,YELLOW11;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,FUNCT_1,RELSET_1,FUNCT_2,NUMBERS,ORDERS_1,DOMAIN_1,FINSET_1,STRUCT_0,ORDERS_2,LATTICE3,ORDERS_3,YELLOW_0,YELLOW_1,WAYBEL_1,LATTICE5,WAYBEL_0,CKB10,CKB13,CKB18;
definitions TARSKI,YELLOW_0,WAYBEL_1,FUNCT_1,WAYBEL_0,LATTICE3,XBOOLE_0,CKB10,CKB13,CKB18;
theorems WAYBEL_1,YELLOW_0,YELLOW_3,YELLOW_5,LATTICE3,TARSKI,FUNCT_2,WAYBEL_0,ZFMISC_1,FUNCT_1,ORDERS_2,YELLOW_1,ENUMSET1,CARD_1,FINSET_1,XBOOLE_0,XBOOLE_1,NAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB13,CKB16,CKB17,CKB18,CKB20;
schemes FUNCT_2,FINSET_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,ORDERS_2,LATTICE3,YELLOW_0,YELLOW_1,ORDINAL1,CKB11,CKB12,CKB14,CKB15,CKB19;
constructors DOMAIN_1,XXREAL_0,LATTICE3,ORDERS_3,WAYBEL_1,RELSET_1,CKB10,CKB13,CKB18;
requirements NUMERALS,REAL,SUBSET,BOOLE;
begin
theorem
(for L being LATTICE holds (L is  modular iff (not (ex K being  full (Sublattice of L) st ( N_5 ),K are_isomorphic ))))
proof
let L being LATTICE;
thus (L is  modular implies (not (ex K being  full (Sublattice of L) st ( N_5 ),K are_isomorphic )))
proof
assume L is  modular;
then (not (ex a,b,c,d,e being (Element of L) st ((((((((((((((((((a <> b & a <> c) & a <> d) & a <> e) & b <> c) & b <> d) & b <> e) & c <> d) & c <> e) & d <> e) & ( a "/\" b ) = a) & ( a "/\" c ) = a) & ( c "/\" e ) = c) & ( d "/\" e ) = d) & ( b "/\" c ) = a) & ( b "/\" d ) = b) & ( c "/\" d ) = a) & ( b "\/" c ) = e) & ( c "\/" d ) = e))) by CKB20:1;
hence thesis by CKB16:1;
end;

assume (not (ex K being  full (Sublattice of L) st ( N_5 ),K are_isomorphic ));
then (not (ex a,b,c,d,e being (Element of L) st ((((((((((((((((((a <> b & a <> c) & a <> d) & a <> e) & b <> c) & b <> d) & b <> e) & c <> d) & c <> e) & d <> e) & ( a "/\" b ) = a) & ( a "/\" c ) = a) & ( c "/\" e ) = c) & ( d "/\" e ) = d) & ( b "/\" c ) = a) & ( b "/\" d ) = b) & ( c "/\" d ) = a) & ( b "\/" c ) = e) & ( c "\/" d ) = e))) by CKB16:1;
hence thesis by CKB20:1;
end;
