environ
vocabularies RELAT_1,SUBSET_1,ZFMISC_1,TARSKI,XBOOLE_0;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,CKB1,CKB4,CKB5,CKB19,CKB20,CKB24,CKB25,CKB35,CKB36;
definitions TARSKI,XBOOLE_0,RELAT_1,CKB4,CKB5;
theorems TARSKI,ZFMISC_1,RELAT_1,XBOOLE_0,XBOOLE_1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB21,CKB22,CKB23,CKB26,CKB27,CKB30,CKB31,CKB32,CKB33,CKB34,CKB37,CKB38,CKB39;
schemes RELAT_1;
registrations XBOOLE_0,RELAT_1,SUBSET_1,CKB2,CKB3,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB28,CKB29;
constructors TARSKI,SUBSET_1,RELAT_1,CKB4,CKB5,CKB19,CKB20,CKB24,CKB25,CKB35,CKB36;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve Y1 for set;
reserve x for set;
reserve y for set;
reserve R for (Relation of X,Y);
theorem
(Y c= Y1 implies ( Y1 | R ) = R)
proof
assume A1: Y c= Y1;
now
let x;
let y;
now
assume A2: [ x,y ] in R;
then y in Y by ZFMISC_1:87;
hence [ x,y ] in ( Y1 | R ) by A1,A2,RELAT_1:def 12;
end;
hence ([ x,y ] in ( Y1 | R ) iff [ x,y ] in R) by RELAT_1:def 12;
end;
hence thesis by RELAT_1:def 2;
end;
