environ
vocabularies RELAT_1,FUNCT_1,XBOOLE_0,ZFMISC_1,SUBSET_1,WELLORD1,RELAT_2,TARSKI;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELAT_2,FUNCT_1,WELLORD1;
definitions TARSKI,WELLORD1;
theorems TARSKI,FUNCT_1,RELAT_1,RELAT_2,ZFMISC_1,WELLORD1,ENUMSET1,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB4,CKB5,CKB6;
schemes TARSKI,FUNCT_1,RELAT_1,XBOOLE_0,CKB3;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1;
constructors TARSKI,SUBSET_1,RELAT_2,WELLORD1;
requirements SUBSET,BOOLE;
begin
reserve x for set;
reserve y for set;
reserve z1 for set;
reserve z2 for set;
reserve M for set;
reserve X for set;
reserve Z for set;
theorem
Lm1: (X,M are_equipotent  iff (ex Z st (((for x holds (x in X implies (ex y st (y in M & [ x,y ] in Z)))) & (for y holds (y in M implies (ex x st (x in X & [ x,y ] in Z))))) & (for x holds (for z1 holds (for y holds (for z2 holds (([ x,z1 ] in Z & [ y,z2 ] in Z) implies (x = y iff z1 = z2)))))))))
proof
A1: ((ex Z st (((for x holds (x in X implies (ex y st (y in M & [ x,y ] in Z)))) & (for y holds (y in M implies (ex x st (x in X & [ x,y ] in Z))))) & (for x holds (for z1 holds (for y holds (for z2 holds (([ x,z1 ] in Z & [ y,z2 ] in Z) implies (x = y iff z1 = z2)))))))) implies X,M are_equipotent )
proof
assume (ex Z st (((for x holds (x in X implies (ex y st (y in M & [ x,y ] in Z)))) & (for y holds (y in M implies (ex x st (x in X & [ x,y ] in Z))))) & (for x holds (for z1 holds (for y holds (for z2 holds (([ x,z1 ] in Z & [ y,z2 ] in Z) implies (x = y iff z1 = z2))))))));
hence (ex Z st (((for x holds (x in X implies (ex y st (y in M & [ x,y ] in Z)))) & (for y holds (y in M implies (ex x st (x in X & [ x,y ] in Z))))) & (for x holds (for z1 holds (for y holds (for z2 holds (([ x,z1 ] in Z & [ y,z2 ] in Z) implies (x = y iff z1 = z2))))))));
end;
(X,M are_equipotent  implies (ex Z st (((for x holds (x in X implies (ex y st (y in M & [ x,y ] in Z)))) & (for y holds (y in M implies (ex x st (x in X & [ x,y ] in Z))))) & (for x holds (for z1 holds (for y holds (for z2 holds (([ x,z1 ] in Z & [ y,z2 ] in Z) implies (x = y iff z1 = z2)))))))))
proof
assume (ex Z st (((for x holds (x in X implies (ex y st (y in M & [ x,y ] in Z)))) & (for y holds (y in M implies (ex x st (x in X & [ x,y ] in Z))))) & (for x holds (for z1 holds (for y holds (for z2 holds (([ x,z1 ] in Z & [ y,z2 ] in Z) implies (x = y iff z1 = z2))))))));
hence thesis;
end;
hence thesis by A1;
end;
