environ
vocabularies NUMBERS,SUBSET_1,FUNCT_1,NAT_1,TARSKI,FINSET_1,RELAT_1,AFINSQ_1,ARYTM_1,ARYTM_3,FINSEQ_1,XXREAL_0,CARD_1,XBOOLE_0,ORDINAL4,CARD_3,BINOP_1,FINSOP_1,FUNCOP_1,BINOP_2,FUNCT_2,INT_1,VALUED_1,NEWTON,REALSET1,ZFMISC_1,FUNCT_4,EQREL_1,SETFAM_1,STIRL2_1,CARD_FIN;
notations TARSKI,XBOOLE_0,SUBSET_1,CARD_1,NUMBERS,RELAT_1,FUNCT_1,NAT_1,FINSET_1,ORDINAL1,XXREAL_0,NAT_D,AFINSQ_1,VALUED_1,RELSET_1,PARTFUN1,DOMAIN_1,FUNCT_2,FUNCT_4,FUNCOP_1,INT_1,ENUMSET1,BINOP_1,BINOP_2,RECDEF_1,AFINSQ_2,ZFMISC_1,NEWTON,STIRL2_1,YELLOW20;
definitions TARSKI,XBOOLE_0,FUNCT_1,FUNCOP_1,FINSET_1,RELAT_1;
theorems AFINSQ_1,TARSKI,FUNCT_1,XBOOLE_0,ZFMISC_1,RELAT_1,XBOOLE_1,NAT_1,FUNCT_2,FINSET_1,XCMPLX_1,CARD_2,INT_1,WELLORD2,SUBSET_1,ENUMSET1,CARD_1,BINOP_2,NEWTON,XREAL_1,FUNCOP_1,STIRL2_1,ALTCAT_1,FUNCT_5,IRRAT_1,FUNCT_4,YELLOW20,XXREAL_0,NAT_D,XREAL_0,PRE_POLY,AFINSQ_2,ORDINAL1,VALUED_1,VALUED_0,CKB1,CKB2;
schemes FUNCT_2,NAT_1,XBOOLE_0,STIRL2_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FUNCT_2,FUNCOP_1,FUNCT_4,FINSET_1,FRAENKEL,NUMBERS,XXREAL_0,XREAL_0,NAT_1,INT_1,BINOP_2,CARD_1,WSIERP_1,AFINSQ_1,RELSET_1,VALUED_1,VALUED_0,AFINSQ_2;
constructors PARTFUN3,BINOM,WELLORD2,DOMAIN_1,SETWISEO,REAL_1,NAT_D,YELLOW20,RECDEF_1,BINOP_2,RELSET_1,ORDINAL4,SEQ_1,AFINSQ_1,SEQ_4,AFINSQ_2,STIRL2_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve x for set;
reserve y for set;
reserve X for  finite set;
reserve Y for  finite set;
reserve f for Function;
theorem
Th3: (for X holds (for Y holds (for x holds (for y holds (((not x in X) & y in Y) implies ( card ( Funcs (X,Y) ) ) = ( card { F where F is (Function of ( X \/ { x } ),Y): ( F . x ) = y } ))))))
proof
let X;
let Y;
let x;
let y;
assume that
A1: (not x in X)
and
A2: y in Y;
set F2 = { F where F is (Function of ( X \/ { x } ),Y): ( F . x ) = y };
set F1 = { F where F is (Function of ( X \/ { x } ),( Y \/ { y } )): (( rng ( F | X ) ) c= Y & ( F . x ) = y) };
{ y } c= Y by A2,ZFMISC_1:31;
then A3: Y = ( Y \/ { y } ) by XBOOLE_1:12;
A4: F2 c= F1
proof
let f being set;
assume f in F2;
then consider F being (Function of ( X \/ { x } ),Y) such that A5: (f = F & ( F . x ) = y);
( rng ( F | X ) ) c= Y;
hence thesis by A3,A5;
end;
F1 c= F2
proof
let f being set;
assume f in F1;
then (ex F being (Function of ( X \/ { x } ),( Y \/ { y } )) st ((f = F & ( rng ( F | X ) ) c= Y) & ( F . x ) = y));
hence thesis by A3;
end;
then F1 = F2 by A4,XBOOLE_0:def 10;
hence thesis by A1,A2,CKB2:1;
end;
