environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,FINSEQ_1,MODELC_2,SUBSET_1,ZF_LANG,XREAL_0,ORDINAL1,FUNCT_1,RELAT_1,XXREAL_0,INT_1,ARYTM_3,ARYTM_1,CARD_1,STRUCT_0,TARSKI,XBOOLEAN,LATTICES,CAT_3,ORDINAL4,ZF_MODEL,MODELC_1,FINSET_1,SEQ_1,REAL_1,CARD_3,SERIES_1,ZFMISC_1,MSUALG_3,ORDERS_1,SUBSTUT1,FSM_1,FSM_2,VALUED_1,MODELC_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,FINSET_1,CARD_1,NUMBERS,XCMPLX_0,XREAL_0,REAL_1,XXREAL_0,NAT_1,RELAT_1,FUNCT_1,RELSET_1,FINSEQ_1,ORDERS_1,FUNCT_2,INT_1,SEQ_1,SERIES_1,PARTFUN1,STRUCT_0,MODELC_1,MODELC_2,RFINSEQ2,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB40,CKB54,CKB55,CKB56,CKB64,CKB76,CKB77,CKB82,CKB106,CKB108,CKB114,CKB115;
definitions TARSKI,MODELC_2,SERIES_1,CKB16,CKB17,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB40,CKB54,CKB55,CKB56,CKB64,CKB76,CKB77,CKB82,CKB106,CKB108,CKB114,CKB115;
theorems XBOOLE_0,ZFMISC_1,XBOOLE_1,TARSKI,FUNCT_1,FUNCT_2,FUNCT_7,WELLORD2,NAT_1,INT_1,ENUMSET1,XREAL_1,FINSEQ_1,ORDERS_1,XXREAL_0,MODELC_1,MODELC_2,ORDINAL1,SUBSET_1,FINSEQ_4,SERIES_1,CARD_1,CARD_2,SERIES_2,FINSET_1,RFINSEQ2,FINSEQ_3,SUBSET,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB16,CKB17,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101,CKB102,CKB103,CKB104,CKB105,CKB106,CKB108,CKB110,CKB111,CKB112,CKB113,CKB114,CKB115,CKB116,CKB117,CKB118;
schemes NAT_1,FUNCT_2,MODELC_2,TARSKI,FUNCT_1,FINSEQ_1,RECDEF_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,XXREAL_0,XREAL_0,NAT_1,INT_1,ORDERS_1,FINSET_1,MODELC_2,FINSEQ_1,NUMBERS,VALUED_0,MEMBERED,STRUCT_0,MODELC_1,CARD_1,RELSET_1,FUNCT_2,CKB19,CKB31,CKB53,CKB107,CKB109;
constructors KNASTER,MODELC_2,SERIES_1,REAL_1,NEWTON,RFINSEQ2,SEQ_1,RELSET_1,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB40,CKB54,CKB55,CKB56,CKB64,CKB76,CKB77,CKB82,CKB106,CKB108,CKB114,CKB115;
requirements REAL,NUMERALS,ARITHM,SUBSET,BOOLE;
begin
reserve k for Nat;
reserve n for Nat;
reserve m for Nat;
reserve i for Nat;
reserve x for set;
reserve y for set;
reserve L for FinSequence;
reserve v for LTL-formula;
reserve N for  strict LTLnode over v;
reserve M for  strict LTLnode over v;
reserve w for (Element of ( Inf_seq ( AtomicFamily ) ));
theorem
Th49: (for f being (Function of ( LTLNodes v ),( LTLNodes v )) holds (f is_succ_homomorphism v,w implies (for x holds (((x in ( LTLNodes v ) & ( CastNode (x,v) ) is non  elementary) & w |= ( * ( CastNode (x,v) ) )) implies (ex n st ((for i holds (i < n implies ( CastNode (( ( f |** i ) . x ),v) ) is non  elementary)) & ( CastNode (( ( f |** n ) . x ),v) ) is  elementary))))))
proof
set LN = ( LTLNodes v );
let f being (Function of LN,LN);
assume A1: f is_succ_homomorphism v,w;
(for x holds (((x in LN & ( CastNode (x,v) ) is non  elementary) & w |= ( * ( CastNode (x,v) ) )) implies (ex n st ((for i holds (i < n implies ( CastNode (( ( f |** i ) . x ),v) ) is non  elementary)) & ( CastNode (( ( f |** n ) . x ),v) ) is  elementary))))
proof
let x;
assume that
A2: x in LN
and
A3: ( CastNode (x,v) ) is non  elementary
and
A4: w |= ( * ( CastNode (x,v) ) );
deffunc F(set) = ( ( f |** ( CastNat $1 ) ) . x );
set len1 = ( ( len ( CastNode (( f . x ),v) ) ) + 1 );
( 0 ) < ( ( 0 ) + len1 );
then A5: 1 <= len1 by NAT_1:19;
reconsider len1 as Nat;
consider L such that A6: (( len L ) = len1 & (for k being Nat holds (k in ( dom L ) implies ( L . k ) = F(k)))) from FINSEQ_1:sch 2;
set X = { m where m is (Element of ( NAT )): ((1 <= m & m <= len1) & ( CastNode (( ( f |** m ) . x ),v) ) is  elementary) };
A7: ( Seg len1 ) = ( dom L ) by A6,FINSEQ_1:def 3;
A8: (for k holds ((1 <= k & k <= ( len L )) implies ( L . k ) = ( ( f |** k ) . x )))
proof
let k;
assume (1 <= k & k <= ( len L ));
then k in ( Seg len1 ) by A6,FINSEQ_1:1;
then ( L . k ) = ( ( f |** ( CastNat k ) ) . x ) by A6,A7;
hence thesis by MODELC_2:def 1;
end;
A9:now
assume A10: X = ( {} );
A11: (for k holds ((1 <= k & k <= ( len L )) implies ( CastNode (( ( f |** k ) . x ),v) ) is non  elementary))
proof
let k;
assume that
A12: (1 <= k & k <= ( len L ));
reconsider k as (Element of ( NAT )) by ORDINAL1:def 12;
(not k in X) by A10;
hence thesis by A6,A12;
end;
A13: (for k holds ((1 <= k & k < ( len L )) implies ( CastNode (( ( f |** ( k + 1 ) ) . x ),v) ) is_succ_of ( CastNode (( ( f |** k ) . x ),v) )))
proof
let k;
assume that
1 <= k
and
A14: k < ( len L );
(for i holds (i <= k implies ( CastNode (( ( f |** i ) . x ),v) ) is non  elementary))
proof
let i;
assume i <= k;
then A15: i < ( len L ) by A14,XXREAL_0:2;
now
per cases  by CKB6:1;
suppose 1 <= i;

hence thesis by A11,A15;
end;
suppose i = ( 0 );

then ( f |** i ) = ( id LN ) by FUNCT_7:84;
hence thesis by A2,A3,FUNCT_1:18;
end;
end;
hence thesis;
end;
hence thesis by A1,A2,A3,A4,CKB118:1;
end;
(for m holds ((1 <= m & m < ( len L )) implies (ex N st (ex M st ((N = ( L . m ) & M = ( L . ( m + 1 ) )) & M is_succ_of N)))))
proof
let m;
assume that
A16: (1 <= m & m < ( len L ));
set M = ( L . ( m + 1 ) );
(1 <= ( m + 1 ) & ( m + 1 ) <= ( len L )) by A16,NAT_1:13;
then A17: M = ( ( f |** ( m + 1 ) ) . x ) by A8;
then M in LN by A2,FUNCT_2:5;
then A18: (ex M1 being  strict LTLnode over v st M = M1) by CKB106:def 1;
set N = ( L . m );
A19: N = ( ( f |** m ) . x ) by A8,A16;
then N in LN by A2,FUNCT_2:5;
then A20: (ex N1 being  strict LTLnode over v st N = N1) by CKB106:def 1;
reconsider M as  strict LTLnode over v by A18;
reconsider N as  strict LTLnode over v by A20;
(( CastNode (N,v) ) = N & ( CastNode (M,v) ) = M) by CKB33:def 1;
hence thesis by A13,A16,A19,A17;
end;
then L is_Finseq_for v by CKB36:def 1;
then ( len ( CastNode (( L . len1 ),v) ) ) <= ( ( ( len ( CastNode (( L . 1 ),v) ) ) - len1 ) + 1 ) by A5,A6,CKB98:1;
then ( len ( CastNode (( L . len1 ),v) ) ) <= ( ( ( len ( CastNode (( ( f |** 1 ) . x ),v) ) ) - len1 ) + 1 ) by A5,A6,A8;
then ( len ( CastNode (( L . len1 ),v) ) ) <= ( ( ( len ( CastNode (( f . x ),v) ) ) - len1 ) + 1 ) by FUNCT_7:70;
then ( len ( CastNode (( ( f |** len1 ) . x ),v) ) ) <= ( 0 ) by A5,A6,A8;
then (the LTLnew of ( CastNode (( ( f |** len1 ) . x ),v) )) = ( {} v ) by CKB84:1;
then ( CastNode (( ( f |** len1 ) . x ),v) ) is  elementary by CKB27:def 1;
then len1 in X by A5;
hence contradiction by A10;
end;
X c= ( Seg len1 )
proof
let y;
assume y in X;
then (ex m being (Element of ( NAT )) st (((y = m & 1 <= m) & m <= len1) & ( CastNode (( ( f |** m ) . x ),v) ) is  elementary));
hence thesis by FINSEQ_1:1;
end;
then consider n such that 1 <= n and A21: n <= len1 and A22: n in X and A23: (for i holds ((1 <= i & i < n) implies (not i in X))) by A9,CKB113:1;
A24: (for i holds (i < n implies ( CastNode (( ( f |** i ) . x ),v) ) is non  elementary))
proof
let i;
assume that
A25: i < n;
now
per cases  by CKB6:1;
suppose i = ( 0 );

then ( f |** i ) = ( id LN ) by FUNCT_7:84;
hence thesis by A2,A3,FUNCT_1:18;
end;
suppose A26: 1 <= i;

then A27: (not i in X) by A23,A25;
now
assume A28: ( CastNode (( ( f |** i ) . x ),v) ) is  elementary;
reconsider i as (Element of ( NAT )) by ORDINAL1:def 12;
i < len1 by A21,A25,XXREAL_0:2;
hence contradiction by A26,A27,A28;
end;
hence thesis;
end;
end;
hence thesis;
end;
( CastNode (( ( f |** n ) . x ),v) ) is  elementary
proof
(ex m being (Element of ( NAT )) st (((n = m & 1 <= m) & m <= len1) & ( CastNode (( ( f |** m ) . x ),v) ) is  elementary)) by A22;
hence thesis;
end;
hence thesis by A24;
end;
hence thesis;
end;
