environ
vocabularies NUMBERS,NAT_1,XBOOLE_0,FINSEQ_1,MODELC_2,SUBSET_1,ZF_LANG,XREAL_0,ORDINAL1,FUNCT_1,RELAT_1,XXREAL_0,INT_1,ARYTM_3,ARYTM_1,CARD_1,STRUCT_0,TARSKI,XBOOLEAN,LATTICES,CAT_3,ORDINAL4,ZF_MODEL,MODELC_1,FINSET_1,SEQ_1,REAL_1,CARD_3,SERIES_1,ZFMISC_1,MSUALG_3,ORDERS_1,SUBSTUT1,FSM_1,FSM_2,VALUED_1,MODELC_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,FINSET_1,CARD_1,NUMBERS,XCMPLX_0,XREAL_0,REAL_1,XXREAL_0,NAT_1,RELAT_1,FUNCT_1,RELSET_1,FINSEQ_1,ORDERS_1,FUNCT_2,INT_1,SEQ_1,SERIES_1,PARTFUN1,STRUCT_0,MODELC_1,MODELC_2,RFINSEQ2,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB40,CKB54,CKB55,CKB56,CKB64,CKB76,CKB77,CKB82;
definitions TARSKI,MODELC_2,SERIES_1,CKB16,CKB17,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB40,CKB54,CKB55,CKB56,CKB64,CKB76,CKB77,CKB82;
theorems XBOOLE_0,ZFMISC_1,XBOOLE_1,TARSKI,FUNCT_1,FUNCT_2,FUNCT_7,WELLORD2,NAT_1,INT_1,ENUMSET1,XREAL_1,FINSEQ_1,ORDERS_1,XXREAL_0,MODELC_1,MODELC_2,ORDINAL1,SUBSET_1,FINSEQ_4,SERIES_1,CARD_1,CARD_2,SERIES_2,FINSET_1,RFINSEQ2,FINSEQ_3,SUBSET,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB16,CKB17,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101,CKB102;
schemes NAT_1,FUNCT_2,MODELC_2,TARSKI,FUNCT_1,FINSEQ_1,RECDEF_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,XXREAL_0,XREAL_0,NAT_1,INT_1,ORDERS_1,FINSET_1,MODELC_2,FINSEQ_1,NUMBERS,VALUED_0,MEMBERED,STRUCT_0,MODELC_1,CARD_1,RELSET_1,FUNCT_2,CKB19,CKB31,CKB53;
constructors KNASTER,MODELC_2,SERIES_1,REAL_1,NEWTON,RFINSEQ2,SEQ_1,RELSET_1,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB40,CKB54,CKB55,CKB56,CKB64,CKB76,CKB77,CKB82;
requirements REAL,NUMERALS,ARITHM,SUBSET,BOOLE;
begin
reserve m for Nat;
reserve L for FinSequence;
reserve H for LTL-formula;
reserve v for LTL-formula;
reserve N1 for  strict LTLnode over v;
reserve N2 for  strict LTLnode over v;
reserve s0 for  elementary  strict LTLnode over v;
reserve s1 for  elementary  strict LTLnode over v;
theorem
Th41: ((s1 is_next_of s0 & H in (the LTLold of s1)) implies ((((H is  conjunctive implies (( the_left_argument_of H ) in (the LTLold of s1) & ( the_right_argument_of H ) in (the LTLold of s1))) & ((H is  disjunctive or H is  Until) implies (( the_left_argument_of H ) in (the LTLold of s1) or ( the_right_argument_of H ) in (the LTLold of s1)))) & (H is  next implies ( the_argument_of H ) in (the LTLnext of s1))) & (H is  Release implies ( the_right_argument_of H ) in (the LTLold of s1))))
proof
assume that
A1: s1 is_next_of s0
and
A2: H in (the LTLold of s1);
consider L such that A3: 1 <= ( len L ) and A4: L is_Finseq_for v and A5: ( L . 1 ) = ( 'X' s0 ) and A6: ( L . ( len L ) ) = s1 by A1,CKB38:def 1;
A7: ( CastNode (( L . 1 ),v) ) = ( 'X' s0 ) by A5,CKB33:def 1;
set n = ( len L );
A8: ( CastNode (( L . n ),v) ) = s1 by A6,CKB33:def 1;
1 < n by A2,A3,A5,A6,XXREAL_0:1;
then consider m such that A9: (1 <= m & m < n) and A10: ((not H in (the LTLold of ( CastNode (( L . m ),v) ))) & H in (the LTLold of ( CastNode (( L . ( m + 1 ) ),v) ))) by A2,A4,A8,A7,CKB89:1;
consider N1,N2 such that A11: N1 = ( L . m ) and A12: N2 = ( L . ( m + 1 ) ) and A13: N2 is_succ_of N1 by A4,A9,CKB36:def 1;
A14: ( CastNode (( L . m ),v) ) = N1 by A11,CKB33:def 1;
then A15: (the LTLold of N1) c= (the LTLold of s1) by A4,A8,A9,CKB93:1;
set m1 = ( m + 1 );
A16: (m1 <= n & 1 <= m1) by A9,NAT_1:13;
A17: ( CastNode (( L . ( m + 1 ) ),v) ) = N2 by A12,CKB33:def 1;
then A18: N2 is_succ_of N1,H by A10,A13,A14,CKB90:1;
(the LTLnew of ( CastNode (( L . n ),v) )) = ( {} v ) by A8,CKB27:def 1;
then A19: (the LTLnew of N2) c= (the LTLold of s1) by A4,A8,A17,A16,CKB96:1;
A20: (H is  conjunctive implies (( the_left_argument_of H ) in (the LTLold of s1) & ( the_right_argument_of H ) in (the LTLold of s1)))
proof
set G = ( the_right_argument_of H );
set F = ( the_left_argument_of H );
assume A21: H is  conjunctive;
then A22: ( LTLNew1 H ) = { F,G } by CKB16:def 1;
now
per cases  by A18,CKB22:def 1;
suppose (H in (the LTLnew of N1) & N2 = ( SuccNode1 (H,N1) ));

then (the LTLnew of N2) = ( ( (the LTLnew of N1) \ { H } ) \/ ( ( LTLNew1 H ) \ (the LTLold of N1) ) ) by CKB20:def 1;
then A23: ( ( LTLNew1 H ) \ (the LTLold of N1) ) c= (the LTLnew of N2) by XBOOLE_1:7;
A24: G in (the LTLold of s1)
proof
now
per cases ;
suppose G in (the LTLold of N1);

hence thesis by A15;
end;
suppose A25: (not G in (the LTLold of N1));

G in ( LTLNew1 H ) by A22,TARSKI:def 2;
then G in ( ( LTLNew1 H ) \ (the LTLold of N1) ) by A25,XBOOLE_0:def 5;
then G in (the LTLnew of N2) by A23;
hence thesis by A19;
end;
end;
hence thesis;
end;
F in (the LTLold of s1)
proof
now
per cases ;
suppose F in (the LTLold of N1);

hence thesis by A15;
end;
suppose A26: (not F in (the LTLold of N1));

F in ( LTLNew1 H ) by A22,TARSKI:def 2;
then F in ( ( LTLNew1 H ) \ (the LTLold of N1) ) by A26,XBOOLE_0:def 5;
then F in (the LTLnew of N2) by A23;
hence thesis by A19;
end;
end;
hence thesis;
end;
hence thesis by A24;
end;
suppose ((H in (the LTLnew of N1) & ((H is  disjunctive or H is  Until) or H is  Release)) & N2 = ( SuccNode2 (H,N1) ));

hence thesis by A21,MODELC_2:78;
end;
end;
hence thesis;
end;
A27: (H is  Release implies ( the_right_argument_of H ) in (the LTLold of s1))
proof
set G = ( the_right_argument_of H );
set F = ( the_left_argument_of H );
assume A28: H is  Release;
then A29: ( LTLNew2 H ) = { F,G } by CKB17:def 1;
A30: ( LTLNew1 H ) = { G } by A28,CKB16:def 1;
now
per cases  by A18,CKB22:def 1;
suppose (H in (the LTLnew of N1) & N2 = ( SuccNode1 (H,N1) ));

then (the LTLnew of N2) = ( ( (the LTLnew of N1) \ { H } ) \/ ( ( LTLNew1 H ) \ (the LTLold of N1) ) ) by CKB20:def 1;
then A31: ( ( LTLNew1 H ) \ (the LTLold of N1) ) c= (the LTLnew of N2) by XBOOLE_1:7;
G in (the LTLold of s1)
proof
now
per cases ;
suppose G in (the LTLold of N1);

hence thesis by A15;
end;
suppose A32: (not G in (the LTLold of N1));

G in ( LTLNew1 H ) by A30,TARSKI:def 1;
then G in ( ( LTLNew1 H ) \ (the LTLold of N1) ) by A32,XBOOLE_0:def 5;
then G in (the LTLnew of N2) by A31;
hence thesis by A19;
end;
end;
hence thesis;
end;
hence thesis;
end;
suppose ((H in (the LTLnew of N1) & ((H is  disjunctive or H is  Until) or H is  Release)) & N2 = ( SuccNode2 (H,N1) ));

then (the LTLnew of N2) = ( ( (the LTLnew of N1) \ { H } ) \/ ( ( LTLNew2 H ) \ (the LTLold of N1) ) ) by CKB21:def 1;
then A33: ( ( LTLNew2 H ) \ (the LTLold of N1) ) c= (the LTLnew of N2) by XBOOLE_1:7;
G in (the LTLold of s1)
proof
now
per cases ;
suppose G in (the LTLold of N1);

hence thesis by A15;
end;
suppose A34: (not G in (the LTLold of N1));

G in ( LTLNew2 H ) by A29,TARSKI:def 2;
then G in ( ( LTLNew2 H ) \ (the LTLold of N1) ) by A34,XBOOLE_0:def 5;
then G in (the LTLnew of N2) by A33;
hence thesis by A19;
end;
end;
hence thesis;
end;
hence thesis;
end;
end;
hence thesis;
end;
A35: ((H is  disjunctive or H is  Until) implies (( the_left_argument_of H ) in (the LTLold of s1) or ( the_right_argument_of H ) in (the LTLold of s1)))
proof
set G = ( the_right_argument_of H );
set F = ( the_left_argument_of H );
assume A36: (H is  disjunctive or H is  Until);
then A37: ( LTLNew2 H ) = { G } by CKB17:def 1;
A38: ( LTLNew1 H ) = { F } by A36,CKB16:def 1;
now
per cases  by A18,CKB22:def 1;
suppose (H in (the LTLnew of N1) & N2 = ( SuccNode1 (H,N1) ));

then (the LTLnew of N2) = ( ( (the LTLnew of N1) \ { H } ) \/ ( ( LTLNew1 H ) \ (the LTLold of N1) ) ) by CKB20:def 1;
then A39: ( ( LTLNew1 H ) \ (the LTLold of N1) ) c= (the LTLnew of N2) by XBOOLE_1:7;
F in (the LTLold of s1)
proof
now
per cases ;
suppose F in (the LTLold of N1);

hence thesis by A15;
end;
suppose A40: (not F in (the LTLold of N1));

F in ( LTLNew1 H ) by A38,TARSKI:def 1;
then F in ( ( LTLNew1 H ) \ (the LTLold of N1) ) by A40,XBOOLE_0:def 5;
then F in (the LTLnew of N2) by A39;
hence thesis by A19;
end;
end;
hence thesis;
end;
hence thesis;
end;
suppose ((H in (the LTLnew of N1) & ((H is  disjunctive or H is  Until) or H is  Release)) & N2 = ( SuccNode2 (H,N1) ));

then (the LTLnew of N2) = ( ( (the LTLnew of N1) \ { H } ) \/ ( ( LTLNew2 H ) \ (the LTLold of N1) ) ) by CKB21:def 1;
then A41: ( ( LTLNew2 H ) \ (the LTLold of N1) ) c= (the LTLnew of N2) by XBOOLE_1:7;
G in (the LTLold of s1)
proof
now
per cases ;
suppose G in (the LTLold of N1);

hence thesis by A15;
end;
suppose A42: (not G in (the LTLold of N1));

G in ( LTLNew2 H ) by A37,TARSKI:def 1;
then G in ( ( LTLNew2 H ) \ (the LTLold of N1) ) by A42,XBOOLE_0:def 5;
then G in (the LTLnew of N2) by A41;
hence thesis by A19;
end;
end;
hence thesis;
end;
hence thesis;
end;
end;
hence thesis;
end;
A43: (the LTLnext of N2) c= (the LTLnext of s1) by A4,A8,A17,A16,CKB93:1;
(H is  next implies ( the_argument_of H ) in (the LTLnext of s1))
proof
set F = ( the_argument_of H );
assume A44: H is  next;
then A45: ( LTLNext H ) = { F } by CKB18:def 1;
now
per cases  by A18,CKB22:def 1;
suppose (H in (the LTLnew of N1) & N2 = ( SuccNode1 (H,N1) ));

then (the LTLnext of N2) = ( (the LTLnext of N1) \/ ( LTLNext H ) ) by CKB20:def 1;
then ( LTLNext H ) c= (the LTLnext of N2) by XBOOLE_1:7;
then A46: ( LTLNext H ) c= (the LTLnext of s1) by A43,XBOOLE_1:1;
F in ( LTLNext H ) by A45,TARSKI:def 1;
hence thesis by A46;
end;
suppose ((H in (the LTLnew of N1) & ((H is  disjunctive or H is  Until) or H is  Release)) & N2 = ( SuccNode2 (H,N1) ));

hence thesis by A44,MODELC_2:78;
end;
end;
hence thesis;
end;
hence thesis by A20,A35,A27;
end;
