environ
vocabularies NUMBERS,XBOOLE_0,METRIC_1,SUBSET_1,PARTFUN1,CARD_1,RELAT_2,TARSKI,STRUCT_0,XXREAL_0,ARYTM_3,ZFMISC_1,FUNCT_1,METRIC_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,XCMPLX_0,FUNCT_2,DOMAIN_1,STRUCT_0,METRIC_1,MCART_1,XXREAL_0,CKB1,CKB2,CKB3,CKB4;
definitions CKB1,CKB4;
theorems TARSKI,BINOP_1,METRIC_1,SUBSET_1,MCART_1,XBOOLE_0,XXREAL_0,CKB1,CKB4;
schemes FRAENKEL,BINOP_1;
registrations SUBSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,METRIC_1,XBOOLE_0;
constructors DOMAIN_1,XXREAL_0,REAL_1,MEMBERED,METRIC_1,CKB1,CKB2,CKB3,CKB4;
requirements REAL,SUBSET,BOOLE,ARITHM;
begin
definition
let M being non empty MetrStruct;
mode equivalence_class of M
 -> (Subset of M)
means :Def3: (ex x being (Element of M) st it = ( x -neighbour ));
existence
proof
set z = the (Element of M);
( z -neighbour ) is (Subset of M);
hence thesis;
end;
end;
