environ
vocabularies RLVECT_1,SUBSET_1,REAL_1,RELAT_1,ARYTM_3,SUPINF_2,CARD_1,XCMPLX_0,ANPROJ_1,ARYTM_1,XBOOLE_0,FUNCT_2,NUMBERS,FUNCT_1,FUNCSDOM,ZFMISC_1,INCSP_1,COLLSP,RELAT_2,PARSP_2,VECTSP_1,AFF_2,ANALOAF,ANPROJ_2;
notations XBOOLE_0,SUBSET_1,NUMBERS,FUNCT_1,FUNCT_2,DOMAIN_1,STRUCT_0,RLVECT_1,REAL_1,FUNCSDOM,COLLSP,ANPROJ_1,CKB13,CKB14,CKB15,CKB27,CKB28;
definitions COLLSP,ANPROJ_1,BINOP_1,FUNCSDOM,RLVECT_1,STRUCT_0,ALGSTR_0,CKB13,CKB14,CKB15,CKB27,CKB28;
theorems RLVECT_1,FUNCT_2,FUNCSDOM,COLLSP,ANPROJ_1,ENUMSET1,XCMPLX_0,XCMPLX_1,FUNCOP_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55;
schemes FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,NUMBERS,STRUCT_0,COLLSP,REAL_1,ANPROJ_1,XREAL_0,ORDINAL1;
constructors DOMAIN_1,REAL_1,FUNCSDOM,BINOP_2,ANPROJ_1,RELSET_1,CKB13,CKB14,CKB15,CKB27,CKB28;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve a for Real;
reserve b for Real;
reserve c for Real;
reserve d for Real;
reserve z for set;
reserve A for non empty set;
reserve f for (Element of ( Funcs (A,( REAL )) ));
reserve g for (Element of ( Funcs (A,( REAL )) ));
reserve h for (Element of ( Funcs (A,( REAL )) ));
reserve f1 for (Element of ( Funcs (A,( REAL )) ));
reserve x1 for (Element of A);
reserve x2 for (Element of A);
reserve x3 for (Element of A);
reserve x4 for (Element of A);
theorem
Th22: (((((((A = { x1,x2,x3,x4 } & x1 <> x2) & x1 <> x3) & x1 <> x4) & x2 <> x3) & x2 <> x4) & x3 <> x4) implies (ex f st (ex g st (ex h st (ex f1 st ((for a holds (for b holds (for c holds (for d holds (( ( RealFuncAdd A ) . (( ( RealFuncAdd A ) . (( ( RealFuncAdd A ) . (( ( RealFuncExtMult A ) . [ a,f ] ),( ( RealFuncExtMult A ) . [ b,g ] )) ),( ( RealFuncExtMult A ) . [ c,h ] )) ),( ( RealFuncExtMult A ) . [ d,f1 ] )) ) = ( RealFuncZero A ) implies (((a = ( 0 ) & b = ( 0 )) & c = ( 0 )) & d = ( 0 ))))))) & (for h9 being (Element of ( Funcs (A,( REAL )) )) holds (ex a st (ex b st (ex c st (ex d st h9 = ( ( RealFuncAdd A ) . (( ( RealFuncAdd A ) . (( ( RealFuncAdd A ) . (( ( RealFuncExtMult A ) . [ a,f ] ),( ( RealFuncExtMult A ) . [ b,g ] )) ),( ( RealFuncExtMult A ) . [ c,h ] )) ),( ( RealFuncExtMult A ) . [ d,f1 ] )) ))))))))))))
proof
assume A1: ((((((A = { x1,x2,x3,x4 } & x1 <> x2) & x1 <> x3) & x1 <> x4) & x2 <> x3) & x2 <> x4) & x3 <> x4);
consider f such that A2: (( f . x1 ) = 1 & (for z holds (z in A implies (z <> x1 implies ( f . z ) = ( 0 ))))) by CKB44:1;
consider f1 such that A3: (( f1 . x4 ) = 1 & (for z holds (z in A implies (z <> x4 implies ( f1 . z ) = ( 0 ))))) by CKB44:1;
consider h such that A4: (( h . x3 ) = 1 & (for z holds (z in A implies (z <> x3 implies ( h . z ) = ( 0 ))))) by CKB44:1;
consider g such that A5: (( g . x2 ) = 1 & (for z holds (z in A implies (z <> x2 implies ( g . z ) = ( 0 ))))) by CKB44:1;
take f;
take g;
take h;
take f1;
thus thesis by A1,A2,A5,A4,A3,CKB52:1,CKB54:1;
end;
