environ
vocabularies XBOOLE_0,BCIALG_1,BINOP_1,SUBSET_1,XXREAL_0,SUPINF_2,XXREAL_2,CARD_FIL,BCIALG_3;
notations XBOOLE_0,SUBSET_1,STRUCT_0,BCIALG_1,CKB1,CKB15;
definitions BCIALG_1,CKB1,CKB15;
theorems BCIALG_1,STRUCT_0,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
registrations STRUCT_0,BCIALG_1,CKB2,CKB3;
constructors BCIALG_1,CKB1,CKB15;
requirements SUBSET;
begin
definition
let X being BCI-algebra;
let a being (Element of X);
attr a is  being_positive
means
( ( 0. X ) \ a ) = ( 0. X );
end;
