environ
vocabularies XBOOLE_0,BCIALG_1,BINOP_1,SUBSET_1,XXREAL_0,SUPINF_2,XXREAL_2,CARD_FIL,BCIALG_3;
notations XBOOLE_0,SUBSET_1,STRUCT_0,BCIALG_1;
definitions BCIALG_1;
theorems BCIALG_1,STRUCT_0;
registrations STRUCT_0,BCIALG_1;
constructors BCIALG_1;
requirements SUBSET;
begin
definition
let IT being non  empty BCIStr_0;
attr IT is  commutative
means
:Def1: (for x,y being (Element of IT) holds ( x \ ( x \ y ) ) = ( y \ ( y \ x ) ));
end;
