environ
vocabularies XBOOLE_0,BCIALG_1,BINOP_1,SUBSET_1,XXREAL_0,SUPINF_2,XXREAL_2,CARD_FIL,BCIALG_3;
notations XBOOLE_0,SUBSET_1,STRUCT_0,BCIALG_1,CKB1,CKB15,CKB16,CKB17,CKB18;
definitions BCIALG_1,CKB1,CKB15,CKB16,CKB17,CKB18;
theorems BCIALG_1,STRUCT_0,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB21;
registrations STRUCT_0,BCIALG_1,CKB2,CKB3,CKB19,CKB20;
constructors BCIALG_1,CKB1,CKB15,CKB16,CKB17,CKB18;
requirements SUBSET;
begin
reserve X for BCK-algebra;
reserve x for (Element of X);
reserve y for (Element of X);
theorem
(for X being BCI-algebra holds (X is  p-Semisimple implies (X is  BCI-commutative & X is  BCI-weakly-commutative)))
proof
let X being BCI-algebra;
assume A1: X is  p-Semisimple;
A2: (for x,y being (Element of X) holds ( ( x \ ( x \ y ) ) \ ( ( 0. X ) \ ( x \ y ) ) ) = ( y \ ( y \ x ) ))
proof
let x being (Element of X);
let y being (Element of X);
( ( 0. X ) \ ( x \ y ) ) = ( ( ( 0. X ) \ ( 0. X ) ) \ ( x \ y ) ) by BCIALG_1:def 5
.= ( ( ( 0. X ) \ x ) \ ( ( 0. X ) \ y ) ) by A1,BCIALG_1:64
.= ( ( y \ x ) \ ( ( 0. X ) \ ( 0. X ) ) ) by A1,BCIALG_1:58
.= ( ( y \ x ) \ ( 0. X ) ) by BCIALG_1:def 5
.= ( y \ x ) by BCIALG_1:2;
hence thesis by A1,BCIALG_1:def 26;
end;
(for x,y being (Element of X) holds (( x \ y ) = ( 0. X ) implies x = ( y \ ( y \ x ) ))) by A1,BCIALG_1:def 26;
hence thesis by A2,CKB17:def 1,CKB18:def 1;
end;
