environ
vocabularies NUMBERS,BCIALG_1,SUBSET_1,INT_1,FUNCT_1,NAT_1,XBOOLE_0,ZFMISC_1,STRUCT_0,CARD_1,SUPINF_2,ARYTM_3,RELAT_1,NEWTON,COMPLEX1,XXREAL_0,WAYBEL15,ARYTM_1,GROUP_1,INT_2,UNIALG_2,CARD_FIL,RCOMP_1,BCIALG_2,REALSET1,MSSUBFAM,FUNCOP_1,MOD_4,GROUP_6,TARSKI,FUNCT_2,CHORD,WELLORD1,EQREL_1,ALG_1,CARD_3,BINOP_1,BCIALG_6;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,REALSET1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,BINOP_1,STRUCT_0,BCIALG_1,FUNCOP_1,NAT_1,NUMBERS,INT_2,XXREAL_0,BINOP_2,NAT_D,INT_1,BCIALG_2,EQREL_1,CKB1,CKB2,CKB3,CKB4,CKB32,CKB34,CKB44,CKB46,CKB47,CKB48,CKB49,CKB66,CKB68;
definitions TARSKI,REALSET1,BINOP_1,STRUCT_0,BCIALG_1,FUNCT_1,BCIALG_2,XBOOLE_0,CKB2,CKB3,CKB4,CKB32,CKB34,CKB44,CKB47,CKB49,CKB66,CKB68;
theorems TARSKI,FUNCT_1,FUNCT_2,FUNCOP_1,BINOP_1,ZFMISC_1,RELAT_1,XBOOLE_0,XBOOLE_1,BCIALG_1,GROUP_6,BCIALG_2,EQREL_1,RELSET_1,ABSVALUE,ORDINAL1,NAT_D,XREAL_1,INT_1,XCMPLX_1,INT_2,NAT_1,NEWTON,XXREAL_0,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB47,CKB49,CKB50,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74;
schemes BINOP_1,FUNCT_2,NAT_1,INT_1,CLASSES1;
registrations XBOOLE_0,RELSET_1,REALSET1,STRUCT_0,BCIALG_1,BCIALG_2,FUNCT_2,PARTFUN1,NAT_1,XREAL_0,ORDINAL1,XXREAL_0,INT_1,CKB45,CKB51,CKB58,CKB67;
constructors BINOP_1,REALSET1,BCIALG_2,REAL_1,BINOP_2,FINSEQOP,SUPINF_1,SEQ_1,NAT_D,RELSET_1,CKB1,CKB2,CKB3,CKB32,CKB34,CKB44,CKB47,CKB49,CKB66,CKB68;
requirements BOOLE,SUBSET,NUMERALS,ARITHM,REAL;
begin
reserve X for BCI-algebra;
reserve X9 for BCI-algebra;
reserve Y for BCI-algebra;
reserve I for (Ideal of X);
reserve x for (Element of X);
reserve y for (Element of X);
reserve RI for (I-congruence of X,I);
reserve f for (BCI-homomorphism of X,X9);
reserve h for (BCI-homomorphism of X9,Y);
theorem
Th55: ((I = ( Ker f ) & f is  onto) implies ( X ./. RI ),X9 are_isomorphic )
proof
assume that
A1: I = ( Ker f )
and
A2: f is  onto;
consider h being (BCI-homomorphism of ( X ./. RI ),X9) such that A3: f = ( h * ( nat_hom RI ) ) and A4: h is  one-to-one by A1,CKB70:1;
(for y being set holds (y in (the carrier of X9) implies (ex z being set st (z in (the carrier of ( X ./. RI )) & ( h . z ) = y))))
proof
let y being set;
assume y in (the carrier of X9);
then y in ( rng f ) by A2,FUNCT_2:def 3;
then consider x being set such that A5: x in ( dom f ) and A6: y = ( f . x ) by FUNCT_1:def 3;
take ( ( nat_hom RI ) . x );
A7: ( dom ( nat_hom RI ) ) = (the carrier of X) by FUNCT_2:def 1;
then ( ( nat_hom RI ) . x ) in ( rng ( nat_hom RI ) ) by A5,FUNCT_1:def 3;
hence thesis by A3,A5,A6,A7,FUNCT_1:13;
end;
then ( rng h ) = (the carrier of X9) by FUNCT_2:10;
then h is  onto by FUNCT_2:def 3;
hence thesis by A4,CKB66:def 1;
end;
