environ
vocabularies XBOOLE_0,RELAT_2,RELAT_1,EQREL_1,WELLORD1,ZFMISC_1,PARTFUN1,SUBSET_1,TARSKI,ORDINAL1,TOLER_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELSET_1,RELAT_2,PARTFUN1,ORDINAL1,WELLORD1,EQREL_1,CKB2,CKB3;
definitions TARSKI,RELAT_1,RELAT_2,WELLORD1;
theorems TARSKI,RELAT_1,RELSET_1,RELAT_2,ZFMISC_1,WELLORD1,ENUMSET1,ORDERS_1,EQREL_1,ORDINAL1,XBOOLE_0,XBOOLE_1,PARTFUN1;
schemes XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELAT_1,PARTFUN1,EQREL_1,RELSET_1,CKB1;
constructors ORDINAL1,WELLORD1,EQREL_1,RELSET_1,CKB3;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve x for set;
reserve y for set;
theorem
( rng ( Total X ) ) = X
proof
(for x holds (x in X iff (ex y st [ y,x ] in ( Total X ))))
proof
let x;
thus (x in X implies (ex y st [ y,x ] in ( Total X )))
proof
assume A1: x in X;
take x;
[ x,x ] in [: X,X :] by A1,ZFMISC_1:87;
hence thesis by EQREL_1:def 1;
end;

given y such that
A2: [ y,x ] in ( Total X );

thus thesis by A2,ZFMISC_1:87;
end;
hence thesis by RELAT_1:def 5;
end;
