environ
vocabularies NUMBERS,SUBSET_1,REAL_1,NORMSP_1,PARTFUN1,NAT_1,PRE_TOPC,TARSKI,RELAT_1,CARD_1,ARYTM_3,ARYTM_1,STRUCT_0,COMPLEX1,XBOOLE_0,XXREAL_0,VALUED_1,SUPINF_2,FUNCT_1,CFCONT_1,NFCONT_1,RCOMP_1,VALUED_0,SEQ_2,ORDINAL2,FCONT_1,FUNCT_2,SEQ_4,LOPBAN_1,ALI2,FUNCOP_1,XREAL_0,ORDINAL1,POWER,SEQ_1,RSSPACE3,FUNCT_7,NFCONT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,XCMPLX_0,XXREAL_0,XREAL_0,NUMBERS,COMPLEX1,REAL_1,NAT_1,RLVECT_1,SQUARE_1,STRUCT_0,PRE_TOPC,ORDINAL1,VALUED_1,SEQ_1,SEQ_2,VALUED_0,SEQ_4,ABIAN,POWER,VFUNCT_1,NORMSP_0,NORMSP_1,LOPBAN_1,RSSPACE3,NFCONT_1,RECDEF_1,CKB1,CKB2,CKB16;
definitions RLVECT_1,CKB1,CKB2,CKB16;
theorems TARSKI,ABSVALUE,XBOOLE_1,RLVECT_1,XCMPLX_1,FUNCOP_1,SEQ_1,SEQ_2,SERIES_1,NAT_1,POWER,RELAT_1,FUNCT_1,VFUNCT_1,LOPBAN_1,NORMSP_1,SEQ_4,FUNCT_2,RSSPACE3,FUNCT_7,LOPBAN_3,PARTFUN2,NFCONT_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,PARTFUN1,VALUED_0,NORMSP_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18;
schemes SEQ_1,NAT_1,FUNCT_2;
registrations XBOOLE_0,FUNCT_1,ORDINAL1,RELSET_1,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,VALUED_1,FUNCT_2,NUMBERS,VALUED_0;
constructors REAL_1,SQUARE_1,NAT_1,COMPLEX1,SEQ_2,SEQ_4,PARTFUN2,POWER,ABIAN,BHSP_3,VFUNCT_1,RSSPACE3,LOPBAN_3,NFCONT_1,SEQ_1,VALUED_1,RECDEF_1,NORMSP_1,RELSET_1,CKB1,CKB2,CKB16;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
reserve x for set;
reserve X for set;
reserve g for Real;
reserve S for RealNormSpace;
reserve T for RealNormSpace;
reserve f for (PartFunc of S,T);
theorem
Th14: (for X being RealBanachSpace holds (for f being (Function of X,X) holds (f is (contraction of X) implies (ex xp being (Point of X) st (( f . xp ) = xp & (for x being (Point of X) holds (( f . x ) = x implies xp = x)))))))
proof
let X being RealBanachSpace;
set x0 = the (Element of X);
let f being (Function of X,X);
assume f is (contraction of X);
then consider K being Real such that A1: ( 0 ) < K and A2: K < 1 and A3: (for x,y being (Point of X) holds ||. ( ( f . x ) - ( f . y ) ) .|| <= ( K * ||. ( x - y ) .|| )) by CKB16:def 1;
deffunc G(set,set) = ( f . $2 );
consider g being Function such that A4: ((( dom g ) = ( NAT ) & ( g . ( 0 ) ) = x0) & (for n being Nat holds ( g . ( n + 1 ) ) = G(n,( g . n )))) from NAT_1:sch 11;
defpred P[ (Element of ( NAT )) ]
 means
( g . $1 ) in (the carrier of X);
A5: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
let k being (Element of ( NAT ));
assume that
A6: P[ k ];
( g . ( k + 1 ) ) = ( f . ( g . k ) ) by A4;
hence thesis by A6,FUNCT_2:5;
end;
A7: P[ ( 0 ) ] by A4;
(for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A7,A5);
then (for n being set holds (n in ( NAT ) implies ( g . n ) in (the carrier of X)));
then reconsider g as (sequence of X) by A4,FUNCT_2:3;
A8:now
let n being (Element of ( NAT ));
||. ( ( ( g ^\ 1 ) . n ) - ( f . ( lim g ) ) ) .|| = ||. ( ( g . ( n + 1 ) ) - ( f . ( lim g ) ) ) .|| by NAT_1:def 3
.= ||. ( ( f . ( g . n ) ) - ( f . ( lim g ) ) ) .|| by A4;
hence ||. ( ( ( g ^\ 1 ) . n ) - ( f . ( lim g ) ) ) .|| <= ( K * ||. ( ( g . n ) - ( lim g ) ) .|| ) by A3;
end;
A9: (for n being (Element of ( NAT )) holds ||. ( ( g . ( n + 1 ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power n ) ))
proof
defpred P[ (Element of ( NAT )) ]
 means
||. ( ( g . ( $1 + 1 ) ) - ( g . $1 ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power $1 ) );
A10: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
let k being (Element of ( NAT ));
assume P[ k ];
then A11: ( K * ||. ( ( g . ( k + 1 ) ) - ( g . k ) ) .|| ) <= ( K * ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power k ) ) ) by A1,XREAL_1:64;
||. ( ( f . ( g . ( k + 1 ) ) ) - ( f . ( g . k ) ) ) .|| <= ( K * ||. ( ( g . ( k + 1 ) ) - ( g . k ) ) .|| ) by A3;
then ||. ( ( f . ( g . ( k + 1 ) ) ) - ( f . ( g . k ) ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K * ( K to_power k ) ) ) by A11,XXREAL_0:2;
then A12: ||. ( ( f . ( g . ( k + 1 ) ) ) - ( f . ( g . k ) ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power 1 ) * ( K to_power k ) ) ) by POWER:25;
( g . ( k + 1 ) ) = ( f . ( g . k ) ) by A4;
then ||. ( ( g . ( ( k + 1 ) + 1 ) ) - ( g . ( k + 1 ) ) ) .|| = ||. ( ( f . ( g . ( k + 1 ) ) ) - ( f . ( g . k ) ) ) .|| by A4;
hence thesis by A1,A12,POWER:27;
end;
||. ( ( g . ( ( 0 ) + 1 ) ) - ( g . ( 0 ) ) ) .|| = ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * 1 )
.= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power ( 0 ) ) ) by POWER:24;
then A13: P[ ( 0 ) ];
(for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A13,A10);
hence thesis;
end;
A14: (for k,n being (Element of ( NAT )) holds ||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ))
proof
defpred P[ (Element of ( NAT )) ]
 means
(for n being (Element of ( NAT )) holds ||. ( ( g . ( n + $1 ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + $1 ) ) ) / ( 1 - K ) ) ));
A15:now
let k being (Element of ( NAT ));
assume that
A16: P[ k ];
now
let n being (Element of ( NAT ));
( 1 - K ) <> ( 0 ) by A2;
then A17: ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) + ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power ( n + k ) ) ) ) = ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) + ( ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power ( n + k ) ) ) * ( 1 - K ) ) / ( 1 - K ) ) ) by XCMPLX_1:89
.= ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) + ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power ( n + k ) ) * ( 1 - K ) ) ) / ( 1 - K ) ) )
.= ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) + ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power ( n + k ) ) * ( 1 - K ) ) / ( 1 - K ) ) ) ) by XCMPLX_1:74
.= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) + ( ( ( K to_power ( n + k ) ) * ( 1 - K ) ) / ( 1 - K ) ) ) )
.= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) + ( ( K to_power ( n + k ) ) * ( 1 - K ) ) ) / ( 1 - K ) ) ) by XCMPLX_1:62
.= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K * ( K to_power ( n + k ) ) ) ) / ( 1 - K ) ) )
.= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( ( K to_power 1 ) * ( K to_power ( n + k ) ) ) ) / ( 1 - K ) ) ) by POWER:25
.= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( ( n + k ) + 1 ) ) ) / ( 1 - K ) ) ) by A1,POWER:27;
(||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) & ||. ( ( g . ( ( n + k ) + 1 ) ) - ( g . ( n + k ) ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power ( n + k ) ) )) by A9,A16;
then (||. ( ( g . ( n + ( k + 1 ) ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . ( n + ( k + 1 ) ) ) - ( g . ( n + k ) ) ) .|| + ||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| ) & ( ||. ( ( g . ( n + ( k + 1 ) ) ) - ( g . ( n + k ) ) ) .|| + ||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| ) <= ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( K to_power ( n + k ) ) ) + ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) )) by NORMSP_1:10,XREAL_1:7;
hence ||. ( ( g . ( n + ( k + 1 ) ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + ( k + 1 ) ) ) ) / ( 1 - K ) ) ) by A17,XXREAL_0:2;
end;
hence P[ ( k + 1 ) ];
end;
now
let n being (Element of ( NAT ));
||. ( ( g . ( n + ( 0 ) ) ) - ( g . n ) ) .|| = ||. ( 0. X ) .|| by RLVECT_1:15
.= ( 0 ) by NORMSP_1:1;
hence ||. ( ( g . ( n + ( 0 ) ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + ( 0 ) ) ) ) / ( 1 - K ) ) );
end;
then A18: P[ ( 0 ) ];
(for k being (Element of ( NAT )) holds P[ k ]) from NAT_1:sch 1(A18,A15);
hence thesis;
end;
A19: (for k,n being (Element of ( NAT )) holds ||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power n ) / ( 1 - K ) ) ))
proof
let k being (Element of ( NAT ));
now
let n being (Element of ( NAT ));
A20: ( 0 ) <= ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| by NORMSP_1:4;
( K to_power ( n + k ) ) > ( 0 ) by A1,POWER:34;
then A21: ( ( K to_power n ) - ( K to_power ( n + k ) ) ) <= ( ( K to_power n ) - ( 0 ) ) by XREAL_1:13;
( 1 - K ) > ( 1 - 1 ) by A2,XREAL_1:15;
then ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) <= ( ( K to_power n ) / ( 1 - K ) ) by A21,XREAL_1:72;
then A22: ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power n ) / ( 1 - K ) ) ) by A20,XREAL_1:64;
||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( ( K to_power n ) - ( K to_power ( n + k ) ) ) / ( 1 - K ) ) ) by A14;
hence ||. ( ( g . ( n + k ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power n ) / ( 1 - K ) ) ) by A22,XXREAL_0:2;
end;
hence thesis;
end;
now
let e being Real;
assume that
A23: e > ( 0 );
( e / 2 ) > ( 0 ) by A23,XREAL_1:215;
then consider n being (Element of ( NAT )) such that A24: ( abs ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| / ( 1 - K ) ) * ( K to_power n ) ) ) < ( e / 2 ) by A1,A2,CKB18:1;
take nn = ( n + 1 );
( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| / ( 1 - K ) ) * ( K to_power n ) ) <= ( abs ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| / ( 1 - K ) ) * ( K to_power n ) ) ) by ABSVALUE:4;
then ( ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| / ( 1 - K ) ) * ( K to_power n ) ) < ( e / 2 ) by A24,XXREAL_0:2;
then A25: ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power n ) / ( 1 - K ) ) ) < ( e / 2 ) by XCMPLX_1:75;
now
let m being (Element of ( NAT ));
let l being (Element of ( NAT ));
assume that
A26: nn <= m
and
A27: nn <= l;
n < m by A26,NAT_1:13;
then consider k1 being Nat such that A28: ( n + k1 ) = m by NAT_1:10;
n < l by A27,NAT_1:13;
then consider k2 being Nat such that A29: ( n + k2 ) = l by NAT_1:10;
reconsider k2 as (Element of ( NAT )) by ORDINAL1:def 12;
||. ( ( g . ( n + k2 ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power n ) / ( 1 - K ) ) ) by A19;
then A30: ||. ( ( g . l ) - ( g . n ) ) .|| < ( e / 2 ) by A25,A29,XXREAL_0:2;
reconsider k1 as (Element of ( NAT )) by ORDINAL1:def 12;
||. ( ( g . ( n + k1 ) ) - ( g . n ) ) .|| <= ( ||. ( ( g . 1 ) - ( g . ( 0 ) ) ) .|| * ( ( K to_power n ) / ( 1 - K ) ) ) by A19;
then ||. ( ( g . m ) - ( g . n ) ) .|| < ( e / 2 ) by A25,A28,XXREAL_0:2;
hence ||. ( ( g . l ) - ( g . m ) ) .|| < e by A23,A30,CKB17:1;
end;
hence (for n,m being (Element of ( NAT )) holds ((n >= nn & m >= nn) implies ||. ( ( g . n ) - ( g . m ) ) .|| < e));
end;
then g is  Cauchy_sequence_by_Norm by RSSPACE3:8;
then A31: g is  convergent by LOPBAN_1:def 15;
then A32: ( K (#) ||. ( g - ( lim g ) ) .|| ) is  convergent by NORMSP_1:24,SEQ_2:7;
A33: ( lim ( K (#) ||. ( g - ( lim g ) ) .|| ) ) = ( K * ( lim ||. ( g - ( lim g ) ) .|| ) ) by A31,NORMSP_1:24,SEQ_2:8
.= ( K * ( 0 ) ) by A31,NORMSP_1:24
.= ( 0 );
A34: (for e being Real holds (e > ( 0 ) implies (ex n being (Element of ( NAT )) st (for m being (Element of ( NAT )) holds (n <= m implies ||. ( ( ( g ^\ 1 ) . m ) - ( f . ( lim g ) ) ) .|| < e)))))
proof
let e being Real;
assume e > ( 0 );
then consider n being (Element of ( NAT )) such that A35: (for m being (Element of ( NAT )) holds (n <= m implies ( abs ( ( ( K (#) ||. ( g - ( lim g ) ) .|| ) . m ) - ( 0 ) ) ) < e)) by A32,A33,SEQ_2:def 7;
take n;
now
let m being (Element of ( NAT ));
assume n <= m;
then ( abs ( ( ( K (#) ||. ( g - ( lim g ) ) .|| ) . m ) - ( 0 ) ) ) < e by A35;
then ( abs ( K * ( ||. ( g - ( lim g ) ) .|| . m ) ) ) < e by SEQ_1:9;
then ( abs ( K * ||. ( ( g - ( lim g ) ) . m ) .|| ) ) < e by NORMSP_0:def 4;
then A36: ( abs ( K * ||. ( ( g . m ) - ( lim g ) ) .|| ) ) < e by NORMSP_1:def 4;
( K * ||. ( ( g . m ) - ( lim g ) ) .|| ) <= ( abs ( K * ||. ( ( g . m ) - ( lim g ) ) .|| ) ) by ABSVALUE:4;
then A37: ( K * ||. ( ( g . m ) - ( lim g ) ) .|| ) < e by A36,XXREAL_0:2;
||. ( ( ( g ^\ 1 ) . m ) - ( f . ( lim g ) ) ) .|| <= ( K * ||. ( ( g . m ) - ( lim g ) ) .|| ) by A8;
hence ||. ( ( ( g ^\ 1 ) . m ) - ( f . ( lim g ) ) ) .|| < e by A37,XXREAL_0:2;
end;
hence thesis;
end;
take xp = ( lim g );
A38: (( g ^\ 1 ) is  convergent & ( lim ( g ^\ 1 ) ) = ( lim g )) by A31,LOPBAN_3:9;
then A39: ( lim g ) = ( f . ( lim g ) ) by A34,NORMSP_1:def 7;
now
let x being (Point of X);
assume that
A40: ( f . x ) = x;
A41: (for k being (Element of ( NAT )) holds ||. ( x - xp ) .|| <= ( ||. ( x - xp ) .|| * ( K to_power k ) ))
proof
defpred P[ (Element of ( NAT )) ]
 means
||. ( x - xp ) .|| <= ( ||. ( x - xp ) .|| * ( K to_power $1 ) );
A42: (for k being (Element of ( NAT )) holds (P[ k ] implies P[ ( k + 1 ) ]))
proof
let k being (Element of ( NAT ));
assume P[ k ];
then A43: ( K * ||. ( x - xp ) .|| ) <= ( K * ( ||. ( x - xp ) .|| * ( K to_power k ) ) ) by A1,XREAL_1:64;
||. ( ( f . x ) - ( f . xp ) ) .|| <= ( K * ||. ( x - xp ) .|| ) by A3;
then ||. ( ( f . x ) - ( f . xp ) ) .|| <= ( ||. ( x - xp ) .|| * ( K * ( K to_power k ) ) ) by A43,XXREAL_0:2;
then ||. ( ( f . x ) - ( f . xp ) ) .|| <= ( ||. ( x - xp ) .|| * ( ( K to_power 1 ) * ( K to_power k ) ) ) by POWER:25;
hence thesis by A1,A39,A40,POWER:27;
end;
||. ( x - xp ) .|| = ( ||. ( x - xp ) .|| * 1 )
.= ( ||. ( x - xp ) .|| * ( K to_power ( 0 ) ) ) by POWER:24;
then A44: P[ ( 0 ) ];
(for n being (Element of ( NAT )) holds P[ n ]) from NAT_1:sch 1(A44,A42);
hence thesis;
end;
(for e being Real holds (( 0 ) < e implies ||. ( x - xp ) .|| < e))
proof
let e being Real;
assume ( 0 ) < e;
then consider n being (Element of ( NAT )) such that A45: ( abs ( ||. ( x - xp ) .|| * ( K to_power n ) ) ) < e by A1,A2,CKB18:1;
( ||. ( x - xp ) .|| * ( K to_power n ) ) <= ( abs ( ||. ( x - xp ) .|| * ( K to_power n ) ) ) by ABSVALUE:4;
then A46: ( ||. ( x - xp ) .|| * ( K to_power n ) ) < e by A45,XXREAL_0:2;
||. ( x - xp ) .|| <= ( ||. ( x - xp ) .|| * ( K to_power n ) ) by A41;
hence thesis by A46,XXREAL_0:2;
end;
hence x = xp by CKB17:1;
end;
hence thesis by A38,A34,NORMSP_1:def 7;
end;
