environ
vocabularies NUMBERS,QUATERNI,ORDINAL1,SUBSET_1,RELAT_1,ARYTM_1,ARYTM_3,ARYTM_0,REAL_1,CARD_1,XCMPLX_0,COMPLEX1,SQUARE_1,XXREAL_0,POLYEQ_3;
notations SUBSET_1,ORDINAL1,NUMBERS,COMPLEX1,ARYTM_0,QUATERNI,REAL_1,SQUARE_1,XXREAL_0,QUATERN2;
definitions SQUARE_1,XCMPLX_0,QUATERNI;
theorems ARYTM_0,SQUARE_1,XREAL_1,QUATERNI,QUATERN2,XCMPLX_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
registrations MEMBERED,QUATERNI;
constructors FUNCT_4,ARYTM_0,REAL_1,SQUARE_1,COMPLEX1,RFUNCT_1,QUATERN2;
requirements NUMERALS,SUBSET,BOOLE,REAL,ARITHM;
begin
reserve z1 for  quaternion number;
reserve z for  quaternion number;
theorem
(z is Real implies ( z * z1 ) = ( z1 * z ))
proof
assume A1: z is Real;
then A2: ( Im3 z ) = ( 0 ) by CKB2:1;
A3: (( Im1 z ) = ( 0 ) & ( Im2 z ) = ( 0 )) by A1,CKB2:1;
( z1 * z ) = ( ( ( ( ( ( ( ( Rea z1 ) * ( Rea z ) ) - ( ( Im1 z1 ) * ( Im1 z ) ) ) - ( ( Im2 z1 ) * ( Im2 z ) ) ) - ( ( Im3 z1 ) * ( Im3 z ) ) ) + ( ( ( ( ( ( Rea z1 ) * ( Im1 z ) ) + ( ( Im1 z1 ) * ( Rea z ) ) ) + ( ( Im2 z1 ) * ( Im3 z ) ) ) - ( ( Im3 z1 ) * ( Im2 z ) ) ) * ( <i> ) ) ) + ( ( ( ( ( ( Rea z1 ) * ( Im2 z ) ) + ( ( Im2 z1 ) * ( Rea z ) ) ) + ( ( Im3 z1 ) * ( Im1 z ) ) ) - ( ( Im1 z1 ) * ( Im3 z ) ) ) * ( <j> ) ) ) + ( ( ( ( ( ( Rea z1 ) * ( Im3 z ) ) + ( ( Im3 z1 ) * ( Rea z ) ) ) + ( ( Im1 z1 ) * ( Im2 z ) ) ) - ( ( Im2 z1 ) * ( Im1 z ) ) ) * ( <k> ) ) ) by QUATERNI:93;
hence thesis by A2,A3,QUATERNI:93;
end;
