environ
vocabularies NUMBERS,INT_1,SUBSET_1,XXREAL_0,FINSET_1,ARYTM_3,XBOOLE_0,ARYTM_1,NAT_1,FUNCT_1,RELAT_1,TARSKI,ORDINAL1,MEMBERED,ORDINAL2,FINSUB_1,SETWISEO,CARD_1,XREAL_0,RAT_1,XXREAL_1,XXREAL_2,MEASURE5;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,ORDINAL1,FINSET_1,FINSUB_1,SETWISEO,NUMBERS,MEMBERED,XXREAL_0,XCMPLX_0,XREAL_0,INT_1,NAT_1,RAT_1,XXREAL_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
definitions TARSKI,SETWISEO,XXREAL_0,MEMBERED,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
theorems XXREAL_0,MEMBERED,TARSKI,XBOOLE_0,XXREAL_1,XBOOLE_1,FINSUB_1,XREAL_0,XREAL_1,INT_1,NAT_1,FINSET_1,ZFMISC_1,FUNCT_1,SETFAM_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20;
schemes XXREAL_1,NAT_1,SETWISEO,CLASSES1,CKB1;
registrations XXREAL_0,MEMBERED,XXREAL_1,XBOOLE_0,FINSET_1,NUMBERS,SETWISEO,FINSUB_1,XREAL_0,INT_1,NAT_1,CARD_1,CKB12;
constructors XXREAL_0,MEMBERED,XREAL_0,INT_1,FINSET_1,RAT_1,XXREAL_1,SETWISEO,XCMPLX_0,REAL_1,NAT_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
requirements BOOLE,SUBSET,NUMERALS,ARITHM,REAL;
begin
reserve x for  ext-real number;
reserve B for  ext-real-membered set;
registration
cluster  finite ->  left_end  right_end for non  empty  ext-real-membered non  empty  ext-real-membered set;
coherence
proof
let X being non  empty  ext-real-membered set;
defpred P[ non  empty  ext-real-membered set ]
 means
$1 is  left_end  right_end;
assume A1: X is  finite;
X c= ( ExtREAL ) by MEMBERED:2;
then A2: X is non  empty non  empty (Element of ( Fin ( ExtREAL ) )) by A1,FINSUB_1:def 5;
A3: (for B1,B2 being non  empty (Element of ( Fin ( ExtREAL ) )) holds ((P[ B1 ] & P[ B2 ]) implies P[ ( B1 \/ B2 ) ]))
proof
let B1 being non  empty (Element of ( Fin ( ExtREAL ) ));
let B2 being non  empty (Element of ( Fin ( ExtREAL ) ));
assume A4: P[ B1 ];
( inf ( B1 \/ B2 ) ) = ( min (( inf B1 ),( inf B2 )) ) by CKB19:1;
then A5: (( inf ( B1 \/ B2 ) ) = ( inf B1 ) or ( inf ( B1 \/ B2 ) ) = ( inf B2 )) by XXREAL_0:15;
assume A6: P[ B2 ];
then A7: ( inf B2 ) in B2 by CKB6:def 1;
( inf B1 ) in B1 by A4,CKB6:def 1;
hence ( inf ( B1 \/ B2 ) ) in ( B1 \/ B2 ) by A7,A5,XBOOLE_0:def 3;
( sup ( B1 \/ B2 ) ) = ( max (( sup B1 ),( sup B2 )) ) by CKB20:1;
then A8: (( sup ( B1 \/ B2 ) ) = ( sup B1 ) or ( sup ( B1 \/ B2 ) ) = ( sup B2 )) by XXREAL_0:16;
A9: ( sup B2 ) in B2 by A6,CKB7:def 1;
( sup B1 ) in B1 by A4,CKB7:def 1;
hence ( sup ( B1 \/ B2 ) ) in ( B1 \/ B2 ) by A9,A8,XBOOLE_0:def 3;
end;
A10: (for x being (Element of ( ExtREAL )) holds P[ {. x .} ])
proof
let x being (Element of ( ExtREAL ));
( sup { x } ) = x by CKB10:1;
then A11: ( sup { x } ) in { x } by TARSKI:def 1;
( inf { x } ) = x by CKB11:1;
then ( inf { x } ) in { x } by TARSKI:def 1;
hence thesis by A11,CKB6:def 1,CKB7:def 1;
end;
(for B being non  empty (Element of ( Fin ( ExtREAL ) )) holds P[ B ]) from SETWISEO:sch 3(A10,A3);
hence thesis by A2;
end;
end;
