environ
vocabularies XBOOLE_0,TARSKI,SUBSET_1,ZFMISC_1,SETFAM_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,CKB1;
definitions TARSKI,XBOOLE_0,SUBSET_1,CKB1;
theorems TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ENUMSET1,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12;
schemes XBOOLE_0,SUBSET_1;
registrations XBOOLE_0,SUBSET_1;
constructors TARSKI,ENUMSET1,SUBSET_1,CKB1;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve SFX for set;
reserve SFY for set;
definition
let SFX;
let SFY;
pred SFX is_finer_than SFY
means
(for X holds (X in SFX implies (ex Y st (Y in SFY & X c= Y))))
;reflexivity;
end;
