environ
vocabularies SUBSET_1,NUMBERS,FUNCT_1,ORDINAL2,XCMPLX_0,RELAT_1,ARYTM_1,ARYTM_3,ORDINAL1,PARTFUN1,COMPLEX1,SIN_COS,CARD_1,SIN_COS2,COMSEQ_3,PREPOWER,SIN_COS3;
notations SUBSET_1,NUMBERS,ORDINAL1,XCMPLX_0,COMPLEX1,REAL_1,NAT_1,PARTFUN1,FUNCT_2,COMSEQ_3,SIN_COS,SIN_COS2,CKB1,CKB2,CKB3,CKB4;
definitions CKB1,CKB2,CKB3,CKB4;
theorems COMPLEX1,SIN_COS,SIN_COS2,COMSEQ_3,XCMPLX_0,NUMBERS,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32;
schemes NAT_1,BINOP_2,FUNCT_2;
registrations NUMBERS,XCMPLX_0,MEMBERED,FUNCT_2,RELSET_1;
constructors FUNCT_4,ARYTM_0,REAL_1,NAT_1,BINOP_2,SEQ_1,PARTFUN1,COMSEQ_3,SIN_COS,SIN_COS2,RVSUM_1,XXREAL_0,CKB1,CKB2,CKB3,CKB4;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve z for (Element of ( COMPLEX ));
theorem
( exp z ) = ( ( ( cosh_C ) /. z ) + ( ( sinh_C ) /. z ) )
proof
( ( ( cosh_C ) /. z ) + ( ( sinh_C ) /. z ) ) = ( ( ( ( exp z ) + ( exp ( - z ) ) ) / 2 ) + ( ( sinh_C ) /. z ) ) by CKB4:def 1
.= ( ( ( ( exp z ) + ( exp ( - z ) ) ) / 2 ) + ( ( ( exp z ) - ( exp ( - z ) ) ) / 2 ) ) by CKB3:def 1
.= ( ( ( exp z ) + ( ( ( exp ( - z ) ) + ( exp z ) ) - ( exp ( - z ) ) ) ) / 2 )
.= ( ( ( ( Re ( exp z ) ) + ( Re ( exp z ) ) ) + ( ( ( Im ( exp z ) ) + ( Im ( exp z ) ) ) * ( <i> ) ) ) / 2 ) by COMPLEX1:def 5
.= ( ( ( 2 * ( Re ( exp z ) ) ) + ( ( 2 * ( Im ( exp z ) ) ) * ( <i> ) ) ) / 2 )
.= ( ( ( Re ( 2 * ( exp z ) ) ) + ( ( 2 * ( Im ( exp z ) ) ) * ( <i> ) ) ) / 2 ) by COMSEQ_3:17
.= ( ( ( Re ( 2 * ( exp z ) ) ) + ( ( Im ( 2 * ( exp z ) ) ) * ( <i> ) ) ) / 2 ) by COMSEQ_3:17
.= ( ( 2 * ( exp z ) ) / 2 ) by COMPLEX1:13
.= ( ( exp z ) * 1 );
hence thesis;
end;
