environ
vocabularies XBOOLE_0,FUNCT_1,SUBSET_1,MCART_1,ZFMISC_1,TARSKI,PBOOLE,RELAT_1,FUNCT_2,FUNCOP_1,MEMBER_1,STRUCT_0,ALTCAT_1,RELAT_2,MSUALG_6,CAT_1,ALTCAT_2,FUNCT_3,MSUALG_3,ENS_1,WELLORD1,FUNCTOR0;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,MCART_1,FUNCT_1,PBOOLE,RELSET_1,PARTFUN1,FUNCT_2,BINOP_1,FUNCOP_1,FUNCT_3,FUNCT_4,STRUCT_0,MSUALG_3,ALTCAT_1,ALTCAT_2;
definitions TARSKI,ALTCAT_2,MSUALG_3,FUNCT_1,FUNCT_2,XBOOLE_0,PBOOLE,BINOP_1;
theorems ALTCAT_2,FUNCT_4,FUNCOP_1,ZFMISC_1,ALTCAT_1,FUNCT_2,FUNCT_1,PBOOLE,FUNCT_3,RELAT_1,MCART_1,DOMAIN_1,MSUALG_3,ISOCAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,PARTFUN1,CKB2,CKB3,CKB7,CKB8,CKB10,CKB11,CKB12;
schemes ALTCAT_2,CKB1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,FUNCT_2,FUNCOP_1,PBOOLE,STRUCT_0,ALTCAT_1,ALTCAT_2,PARTFUN1,RELSET_1,CKB4,CKB5,CKB6,CKB9;
constructors FUNCT_3,MSUALG_3,ALTCAT_2,RELSET_1,PBOOLE,REALSET1,CARD_3,PRALG_2;
requirements SUBSET,BOOLE;
begin
theorem
Th9: (for f being Function holds (f is  one-to-one implies ( ~ f ) is  one-to-one))
proof
let f being Function;
assume that
A1: f is  one-to-one;
let x1 being set;
let x2 being set;
consider X,Y being set such that A2: ( dom ( ~ f ) ) c= [: X,Y :] by FUNCT_4:44;
assume A3: x1 in ( dom ( ~ f ) );
then consider x11,x12 being set such that x11 in X and x12 in Y and A4: x1 = [ x11,x12 ] by A2,ZFMISC_1:84;
assume A5: x2 in ( dom ( ~ f ) );
then consider x21,x22 being set such that x21 in X and x22 in Y and A6: x2 = [ x21,x22 ] by A2,ZFMISC_1:84;
assume A7: ( ( ~ f ) . x1 ) = ( ( ~ f ) . x2 );
A8: [ x12,x11 ] in ( dom f ) by A3,A4,FUNCT_4:42;
A9: [ x22,x21 ] in ( dom f ) by A5,A6,FUNCT_4:42;
( f . (x12,x11) ) = ( ( ~ f ) . (x11,x12) ) by A3,A4,FUNCT_4:43
.= ( ( ~ f ) . (x21,x22) ) by A4,A6,A7
.= ( f . (x22,x21) ) by A5,A6,FUNCT_4:43;
then A10: [ x12,x11 ] = [ x22,x21 ] by A1,A8,A9,FUNCT_1:def 4;
then x12 = x22 by ZFMISC_1:27;
hence thesis by A4,A6,A10,ZFMISC_1:27;
end;
