environ
vocabularies XBOOLE_0,FUNCT_1,SUBSET_1,MCART_1,ZFMISC_1,TARSKI,PBOOLE,RELAT_1,FUNCT_2,FUNCOP_1,MEMBER_1,STRUCT_0,ALTCAT_1,RELAT_2,MSUALG_6,CAT_1,ALTCAT_2,FUNCT_3,MSUALG_3,ENS_1,WELLORD1,FUNCTOR0;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,MCART_1,FUNCT_1,PBOOLE,RELSET_1,PARTFUN1,FUNCT_2,BINOP_1,FUNCOP_1,FUNCT_3,FUNCT_4,STRUCT_0,MSUALG_3,ALTCAT_1,ALTCAT_2,CKB18,CKB21,CKB22,CKB23,CKB27,CKB28,CKB31,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB42,CKB43,CKB44,CKB45,CKB48,CKB50,CKB51,CKB52,CKB53,CKB54,CKB59,CKB61,CKB64,CKB71,CKB72,CKB73,CKB74,CKB78,CKB79,CKB80,CKB81,CKB82,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB100,CKB102,CKB112,CKB113;
definitions TARSKI,ALTCAT_2,MSUALG_3,FUNCT_1,FUNCT_2,XBOOLE_0,PBOOLE,BINOP_1,CKB22,CKB23,CKB27,CKB28,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB42,CKB44,CKB45,CKB48,CKB51,CKB53,CKB54,CKB59,CKB61,CKB64,CKB71,CKB72,CKB73,CKB74,CKB78,CKB79,CKB80,CKB81,CKB82,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB102,CKB112,CKB113;
theorems ALTCAT_2,FUNCT_4,FUNCOP_1,ZFMISC_1,ALTCAT_1,FUNCT_2,FUNCT_1,PBOOLE,FUNCT_3,RELAT_1,MCART_1,DOMAIN_1,MSUALG_3,ISOCAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,PARTFUN1,CKB2,CKB3,CKB7,CKB8,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB19,CKB20,CKB22,CKB23,CKB24,CKB26,CKB27,CKB28,CKB30,CKB32,CKB33,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB44,CKB45,CKB48,CKB51,CKB53,CKB54,CKB55,CKB58,CKB59,CKB60,CKB61,CKB64,CKB65,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB78,CKB79,CKB80,CKB81,CKB82,CKB84,CKB85,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB94,CKB95,CKB98,CKB102,CKB108,CKB109,CKB110,CKB112,CKB113,CKB114,CKB115,CKB116,CKB117,CKB118,CKB119;
schemes ALTCAT_2,CKB1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,FUNCT_2,FUNCOP_1,PBOOLE,STRUCT_0,ALTCAT_1,ALTCAT_2,PARTFUN1,RELSET_1,CKB4,CKB5,CKB6,CKB9,CKB25,CKB29,CKB34,CKB43,CKB46,CKB47,CKB49,CKB56,CKB57,CKB62,CKB63,CKB66,CKB67,CKB68,CKB69,CKB70,CKB77,CKB83,CKB86,CKB93,CKB96,CKB97,CKB99,CKB101,CKB103,CKB104,CKB105,CKB106,CKB107,CKB111;
constructors FUNCT_3,MSUALG_3,ALTCAT_2,RELSET_1,PBOOLE,REALSET1,CARD_3,PRALG_2,CKB18,CKB22,CKB23,CKB27,CKB31,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB42,CKB43,CKB44,CKB45,CKB48,CKB50,CKB51,CKB52,CKB53,CKB54,CKB64,CKB71,CKB72,CKB78,CKB79,CKB80,CKB81,CKB82,CKB87,CKB88,CKB90,CKB91,CKB92,CKB100,CKB102,CKB112,CKB113;
requirements SUBSET,BOOLE;
begin
theorem
Th42: (for A,B being  transitive  with_units non  empty AltCatStr holds (for F being  feasible  reflexive FunctorStr over A,B holds (F is  bijective  coreflexive  Contravariant implies (for o1,o2 being (object of B) holds (for m being (Morphism of o1,o2) holds (<^ o1,o2 ^> <> ( {} ) implies ( ( Morph-Map (F,( ( F " ) . o2 ),( ( F " ) . o1 )) ) . ( ( Morph-Map (( F " ),o1,o2) ) . m ) ) = m))))))
proof
let A being  transitive  with_units non  empty AltCatStr;
let B being  transitive  with_units non  empty AltCatStr;
let F being  feasible  reflexive FunctorStr over A,B;
assume that
A1: F is  bijective  coreflexive  Contravariant;
set G = ( F " );
A2: G is  Contravariant by A1,CKB118:1;
reconsider H = G as  feasible  reflexive FunctorStr over B,A by A1,CKB114:1,CKB115:1;
A3: (the ObjectMap of G) = ( (the ObjectMap of F) " ) by A1,CKB113:def 1;
consider f being (ManySortedFunction of (the Arrows of A),( (the Arrows of B) * (the ObjectMap of F) )) such that A4: f = (the MorphMap of F) and A5: (the MorphMap of G) = ( ( f "" ) * ( (the ObjectMap of F) " ) ) by A1,CKB113:def 1;
F is  injective by A1,CKB92:def 1;
then F is  faithful by CKB90:def 1;
then A6: (the MorphMap of F) is  "1-1" by CKB87:def 1;
F is  surjective by A1,CKB92:def 1;
then F is  full by CKB91:def 1;
then A7: (ex f being (ManySortedFunction of (the Arrows of A),( (the Arrows of B) * (the ObjectMap of F) )) st (f = (the MorphMap of F) & f is  "onto")) by CKB89:def 1;
let o1 being (object of B);
let o2 being (object of B);
let m being (Morphism of o1,o2);
assume that
A8: <^ o1,o2 ^> <> ( {} );
A9: [ ( G . o2 ),( G . o1 ) ] in [: (the carrier of A),(the carrier of A) :] by ZFMISC_1:87;
A10: [ o1,o2 ] in [: (the carrier of B),(the carrier of B) :] by ZFMISC_1:87;
then A11: [ o1,o2 ] in ( dom (the ObjectMap of G) ) by FUNCT_2:def 1;
( dom (the MorphMap of F) ) = [: (the carrier of A),(the carrier of A) :] by PARTFUN1:def 2;
then [ ( G . o2 ),( G . o1 ) ] in ( dom (the MorphMap of F) ) by ZFMISC_1:87;
then A12: ( Morph-Map (F,( G . o2 ),( G . o1 )) ) is  one-to-one by A6,MSUALG_3:def 2;
( ( (the Arrows of A) * (the ObjectMap of G) ) . [ o1,o2 ] ) = ( (the Arrows of A) . ( (the ObjectMap of H) . (o1,o2) ) ) by A11,FUNCT_1:13
.= ( (the Arrows of A) . (( H . o2 ),( H . o1 )) ) by A2,CKB60:1
.= <^ ( H . o2 ),( H . o1 ) ^> by ALTCAT_1:def 1;
then A13: ( ( (the Arrows of A) * (the ObjectMap of G) ) . [ o1,o2 ] ) <> ( {} ) by A2,A8,CKB61:def 1;
(the MorphMap of G) is (ManySortedFunction of (the Arrows of B),( (the Arrows of A) * (the ObjectMap of G) )) by CKB28:def 1;
then ( Morph-Map (G,o1,o2) ) is (Function of ( (the Arrows of B) . [ o1,o2 ] ),( ( (the Arrows of A) * (the ObjectMap of G) ) . [ o1,o2 ] )) by A10,PBOOLE:def 15;
then A14: ( dom ( Morph-Map (G,o1,o2) ) ) = ( (the Arrows of B) . (o1,o2) ) by A13,FUNCT_2:def 1
.= <^ o1,o2 ^> by ALTCAT_1:def 1;
A15: ( Morph-Map (G,o1,o2) ) = ( ( f "" ) . ( (the ObjectMap of G) . (o1,o2) ) ) by A3,A5,A11,FUNCT_1:13
.= ( ( f "" ) . [ ( H . o2 ),( H . o1 ) ] ) by A2,CKB60:1
.= ( ( Morph-Map (F,( G . o2 ),( G . o1 )) ) " ) by A4,A6,A7,A9,MSUALG_3:def 4;
thus ( ( Morph-Map (F,( ( F " ) . o2 ),( ( F " ) . o1 )) ) . ( ( Morph-Map (( F " ),o1,o2) ) . m ) ) = ( ( ( Morph-Map (F,( G . o2 ),( G . o1 )) ) * ( Morph-Map (G,o1,o2) ) ) . m ) by A8,A14,FUNCT_1:13
.= ( ( id ( rng ( Morph-Map (F,( G . o2 ),( G . o1 )) ) ) ) . m ) by A12,A15,FUNCT_1:39
.= ( ( id ( dom ( Morph-Map (G,o1,o2) ) ) ) . m ) by A12,A15,FUNCT_1:33
.= m by A8,A14,FUNCT_1:18;
end;
