environ
vocabularies UNIALG_1,UNIALG_2,XBOOLE_0,SUBSET_1,BINOP_1,GROUP_2,STRUCT_0,ORDERS_3,FUNCT_1,ZFMISC_1,CARD_1,FINSEQ_1,TARSKI,PARTFUN1,RELAT_1,FINSEQ_2,NUMBERS,CQC_SIM1,SETFAM_1,PBOOLE,EQREL_1,XXREAL_2,LATTICES,REWRITE1,LATTICE3,VECTSP_8,UNIALG_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,SETFAM_1,RELAT_1,FUNCT_1,STRUCT_0,RELSET_1,FUNCT_2,FINSEQ_1,FINSEQ_2,BINOP_1,MARGREL1,LATTICES,LATTICE3,UNIALG_1,UNIALG_2,CKB1,CKB3,CKB4,CKB5,CKB6;
definitions LATTICE3,VECTSP_8,LATTICES,UNIALG_2,TARSKI,XBOOLE_0,SUBSET_1,MARGREL1,CKB1,CKB5,CKB6;
theorems TARSKI,UNIALG_2,SETFAM_1,FUNCT_1,FUNCT_2,LATTICE3,RELAT_1,LATTICES,SUBSET_1,FINSEQ_2,UNIALG_1,FINSEQ_1,FINSEQ_3,XBOOLE_0,XBOOLE_1,STRUCT_0,MARGREL1,CKB1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11;
schemes FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,LATTICES,UNIALG_2,ORDINAL1,FINSEQ_1,CARD_1,MARGREL1,CKB2;
constructors SETFAM_1,BINOP_1,DOMAIN_1,LATTICE3,UNIALG_2,RELSET_1,CKB1,CKB3,CKB4,CKB5,CKB6;
requirements BOOLE,SUBSET;
begin
theorem
Th6: (for U0 being  with_const_op Universal_Algebra holds (for U1 being (SubAlgebra of U0) holds ( Constants U0 ) = ( Constants U1 )))
proof
let U0 being  with_const_op Universal_Algebra;
let U1 being (SubAlgebra of U0);
thus ( Constants U0 ) c= ( Constants U1 )
proof
reconsider A = (the carrier of U1) as non empty (Subset of U0) by UNIALG_2:def 7;
let a being set;
A1: ( Constants U0 ) is (Subset of U1) by UNIALG_2:15;
assume A2: a in ( Constants U0 );
then consider u being (Element of U0) such that A3: u = a and A4: (ex o being (operation of U0) st (( arity o ) = ( 0 ) & u in ( rng o )));
consider o1 being (operation of U0) such that A5: ( arity o1 ) = ( 0 ) and A6: u in ( rng o1 ) by A4;
A7: ( dom o1 ) = ( ( 0 ) -tuples_on (the carrier of U0) ) by A5,MARGREL1:22
.= { ( <*> (the carrier of U0) ) } by FINSEQ_2:94
.= { ( <*> A ) }
.= ( ( 0 ) -tuples_on A ) by FINSEQ_2:94;
consider x being set such that A8: x in ( dom (the charact of U0) ) and A9: o1 = ( (the charact of U0) . x ) by FUNCT_1:def 3;
reconsider x as (Element of ( NAT )) by A8;
x in ( dom (the charact of U1) ) by A8,UNIALG_2:7;
then reconsider o = ( (the charact of U1) . x ) as (operation of U1) by FUNCT_1:def 3;
A is  opers_closed by UNIALG_2:def 7;
then A10: A is_closed_on o1 by UNIALG_2:def 4;
x in ( dom ( Opers (U0,A) ) ) by A8,UNIALG_2:def 6;
then ( ( Opers (U0,A) ) . x ) = ( o1 /. A ) by A9,UNIALG_2:def 6;
then o = ( o1 /. A ) by UNIALG_2:def 7
.= ( o1 | ( ( 0 ) -tuples_on A ) ) by A5,A10,UNIALG_2:def 5
.= o1 by A7,RELAT_1:69;
hence thesis by A2,A3,A5,A6,A1;
end;

thus ( Constants U1 ) c= ( Constants U0 )
proof
reconsider A = (the carrier of U1) as non empty (Subset of U0) by UNIALG_2:def 7;
let a being set;
assume a in ( Constants U1 );
then consider u being (Element of U1) such that A11: u = a and A12: (ex o being (operation of U1) st (( arity o ) = ( 0 ) & u in ( rng o )));
consider o being (operation of U1) such that A13: ( arity o ) = ( 0 ) and A14: u in ( rng o ) by A12;
consider x being set such that A15: x in ( dom (the charact of U1) ) and A16: o = ( (the charact of U1) . x ) by FUNCT_1:def 3;
reconsider x as (Element of ( NAT )) by A15;
A17: x in ( dom (the charact of U0) ) by A15,UNIALG_2:7;
then reconsider o1 = ( (the charact of U0) . x ) as (operation of U0) by FUNCT_1:def 3;
( len ( signature U1 ) ) = ( len (the charact of U1) ) by UNIALG_1:def 4;
then A18: x in ( dom ( signature U1 ) ) by A15,FINSEQ_3:29;
U1,U0 are_similar  by UNIALG_2:13;
then ( signature U0 ) = ( signature U1 ) by UNIALG_2:def 1;
then A19: ( arity o1 ) = ( ( signature U1 ) . x ) by A18,UNIALG_1:def 4
.= ( 0 ) by A13,A16,A18,UNIALG_1:def 4;
then A20: ( dom o1 ) = ( ( 0 ) -tuples_on (the carrier of U0) ) by MARGREL1:22
.= { ( <*> (the carrier of U0) ) } by FINSEQ_2:94
.= { ( <*> A ) }
.= ( ( 0 ) -tuples_on A ) by FINSEQ_2:94;
A is  opers_closed by UNIALG_2:def 7;
then A21: A is_closed_on o1 by UNIALG_2:def 4;
(the carrier of U1) is (Subset of U0) by UNIALG_2:def 7;
then A22: u in (the carrier of U0) by TARSKI:def 3;
x in ( dom ( Opers (U0,A) ) ) by A17,UNIALG_2:def 6;
then ( ( Opers (U0,A) ) . x ) = ( o1 /. A ) by UNIALG_2:def 6;
then o = ( o1 /. A ) by A16,UNIALG_2:def 7
.= ( o1 | ( ( 0 ) -tuples_on A ) ) by A21,A19,UNIALG_2:def 5
.= o1 by A20,RELAT_1:69;
hence thesis by A11,A13,A14,A22;
end;

end;
