environ
vocabularies NUMBERS,STRUCT_0,RSSPACE,RLVECT_1,SEQ_1,VALUED_1,SERIES_1,SUPINF_2,ARYTM_3,REAL_1,RELAT_1,ARYTM_1,PROB_2,CARD_3,COMPLEX1,SUBSET_1,CARD_1,XXREAL_0,FUNCT_1,SQUARE_1,BHSP_1,ALGSTR_0,ZFMISC_1,REALSET1,PRE_TOPC,VALUED_0,XXREAL_2,ORDINAL2,SEQ_2,FUNCOP_1,NAT_1,BHSP_3,XREAL_0,ORDINAL1,NORMSP_1,REWRITE1,RSSPACE2;
notations TARSKI,SUBSET_1,ZFMISC_1,ORDINAL1,BINOP_1,REALSET1,NUMBERS,XCMPLX_0,XXREAL_0,COMPLEX1,REAL_1,NAT_1,STRUCT_0,ALGSTR_0,XREAL_0,RELAT_1,PARTFUN1,FUNCT_1,FUNCT_2,FUNCOP_1,PRE_TOPC,RLVECT_1,BHSP_1,BHSP_2,BHSP_3,SQUARE_1,VALUED_1,SEQ_1,SEQ_2,SERIES_1,RSSPACE;
definitions SQUARE_1,BINOP_1,REALSET1,RLVECT_1,STRUCT_0,ALGSTR_0,BHSP_3;
theorems RELAT_1,SQUARE_1,ZFMISC_1,SEQ_1,SEQ_2,SEQM_3,SERIES_1,INT_1,FUNCT_1,NAT_1,FUNCT_2,RLVECT_1,RLSUB_1,BHSP_1,BHSP_2,BHSP_3,SEQ_4,RSSPACE,XREAL_0,XCMPLX_1,COMPLEX1,FUNCOP_1,XREAL_1,XXREAL_0,CKB1,CKB2,CKB4;
schemes NAT_1,SEQ_1,FUNCT_2;
registrations XBOOLE_0,ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,REALSET1,STRUCT_0,RSSPACE,VALUED_1,FUNCT_2,VALUED_0,FUNCOP_1,NAT_1,SEQ_4,CKB3;
constructors PARTFUN1,BINOP_1,FUNCOP_1,REAL_1,SQUARE_1,NAT_1,NAT_D,SEQ_2,SERIES_1,REALSET1,RLSUB_1,BHSP_2,BHSP_3,RSSPACE,SEQ_1,VALUED_1,RELSET_1,BINOP_2,RVSUM_1;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
theorem
Lm2: ((for x,y being Real holds ( ( x + y ) * ( x + y ) ) <= ( ( ( 2 * x ) * x ) + ( ( 2 * y ) * y ) )) & (for x,y being Real holds ( x * x ) <= ( ( ( 2 * ( x - y ) ) * ( x - y ) ) + ( ( 2 * y ) * y ) )))
proof
A1:now
let x being Real,y being Real;
( 0 ) <= ( ( x - y ) ^2 ) by XREAL_1:63;
then ( ( 0 ) + ( ( x + y ) * ( x + y ) ) ) <= ( ( ( ( ( 2 * x ) * x ) + ( ( 2 * y ) * y ) ) - ( ( x + y ) * ( x + y ) ) ) + ( ( x + y ) * ( x + y ) ) ) by XREAL_1:7;
hence ( ( x + y ) * ( x + y ) ) <= ( ( ( 2 * x ) * x ) + ( ( 2 * y ) * y ) );
end;
now
let x being Real,y being Real;
( ( x - y ) + y ) = x;
hence ( x * x ) <= ( ( ( 2 * ( x - y ) ) * ( x - y ) ) + ( ( 2 * y ) * y ) ) by A1;
end;
hence thesis by A1;
end;
