environ
vocabularies SUBSET_1,CQC_LANG,QC_LANG1,FINSEQ_1,ZFMISC_1,CQC_THE1,NUMBERS,XBOOLEAN,BVFUNC_2,XBOOLE_0,FUNCT_1,TARSKI,RCOMP_1,MCART_1,NAT_1,XXREAL_0,ARYTM_3,CARD_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,NAT_1,FINSEQ_1,FUNCT_1,MCART_1,DOMAIN_1,QC_LANG1,QC_LANG2,CQC_LANG,CQC_THE1,XXREAL_0;
definitions CQC_THE1;
theorems TARSKI,ZFMISC_1,LUKASI_1,CQC_LANG,CQC_THE1,ENUMSET1,QC_LANG1,QC_LANG2,QC_LANG3,PROCAL_1,XBOOLE_0,XBOOLE_1,XXREAL_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26;
schemes NAT_1;
registrations XBOOLE_0,RELSET_1,XREAL_0,CQC_LANG,ORDINAL1,LUKASI_1;
constructors DOMAIN_1,XXREAL_0,XREAL_0,CQC_THE1;
requirements NUMERALS,SUBSET,BOOLE;
begin
reserve s for QC-formula;
reserve x for bound_QC-variable;
reserve y for bound_QC-variable;
theorem
((not x in ( still_not-bound_in ( Ex (x,y,s) ) )) & (not y in ( still_not-bound_in ( Ex (x,y,s) ) )))
proof
(not y in ( still_not-bound_in ( Ex (y,s) ) )) by CKB22:1;
then A1: (not y in ( still_not-bound_in ( Ex (x,( Ex (y,s) )) ) )) by CKB22:1;
(not x in ( still_not-bound_in ( Ex (x,( Ex (y,s) )) ) )) by CKB22:1;
hence thesis by A1,QC_LANG2:14;
end;
