environ
vocabularies ARYTM_1,ARYTM_3,XBOOLE_0,CARD_1,CONVEX1,CONVEX2,CONVEX3,FINSEQ_1,FINSEQ_2,FINSEQ_4,FINSET_1,FUNCOP_1,FUNCT_1,FUNCT_2,FUNCT_4,MEMBERED,ORDERS_1,RELAT_1,RLVECT_1,RLVECT_2,RUSUB_4,SEMI_AF1,SETFAM_1,TARSKI,TOPS_1,RLAFFIN1,RLAFFIN2,ZFMISC_1,REAL_1,CARD_3,XXREAL_0,NAT_1,SUBSET_1,NUMBERS,ORDINAL1,STRUCT_0,SUPINF_2,ORDINAL4,VALUED_1,XREAL_0,PARTFUN1;
notations TARSKI,XBOOLE_0,SUBSET_1,ZFMISC_1,ORDINAL1,NUMBERS,NAT_1,XCMPLX_0,XXREAL_0,ORDERS_1,CARD_1,XREAL_0,REAL_1,FINSET_1,SETFAM_1,DOMAIN_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,RELSET_1,FINSEQ_1,STRUCT_0,FINSEQ_2,SEQ_1,FINSEQOP,RVSUM_1,RLVECT_1,RLVECT_2,RUSUB_4,CONVEX1,CONVEX2,CONVEX3,RLAFFIN1,FUNCT_4,FUNCOP_1,MEMBERED,XXREAL_2,CKB6,CKB19;
definitions ORDERS_1,RLVECT_2,TARSKI,XBOOLE_0,CKB6,CKB19;
theorems BORSUK_4,CARD_1,CARD_2,CARD_FIN,CONVEX1,CONVEX3,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,FUNCOP_1,FUNCT_1,FUNCT_2,FUNCT_4,NAT_1,MEMBERED,PARTFUN1,RELAT_1,RLAFFIN1,RLTOPSP1,RUSUB_4,RLVECT_2,RLVECT_3,RLVECT_4,RVSUM_1,STIRL2_1,SIMPLEX0,TARSKI,WELLORD2,XBOOLE_0,XBOOLE_1,XCMPLX_1,XREAL_0,XREAL_1,XXREAL_0,XXREAL_2,ZFMISC_1,RLVECT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34;
schemes FRAENKEL,FUNCT_2,NAT_1,RLVECT_4;
registrations CARD_1,FINSET_1,FINSEQ_2,FUNCT_2,MEMBERED,NAT_1,NUMBERS,RELAT_1,RLVECT_1,RLVECT_3,STRUCT_0,SUBSET_1,VALUED_0,XCMPLX_0,XREAL_0,XXREAL_0,XBOOLE_0,RLAFFIN1,SIMPLEX0,FUNCOP_1,XXREAL_3,REALSET1,SETFAM_1,XXREAL_2,ABIAN,PARTFUN1,RVSUM_1,FINSEQ_1,RELSET_1,DILWORTH,RLVECT_2,CKB8;
constructors BINOP_2,CONVEX1,CONVEX3,DOMAIN_1,FINSEQOP,REAL_1,RLVECT_3,RVSUM_1,RUSUB_5,SEQ_1,SETFAM_1,RLAFFIN1,SIMPLEX0,XXREAL_2,FUNCT_4,RELSET_1,PARTFUN1,CKB6,CKB19;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve x for set;
reserve y for set;
reserve V for RealLinearSpace;
theorem
Th29: (for F being  c=-linear (Subset-Family of V) holds (( union F ) is  finite  affinely-independent implies ( ( center_of_mass V ) .: F ) is  affinely-independent  affinely-independent (Subset of V)))
proof
set B = ( center_of_mass V );
defpred P[ Nat ]
 means
(for k being Nat holds (k <= $1 implies (for S being  c=-linear (Subset-Family of V) holds ((( card ( union S ) ) = k & ( union S ) is  finite  affinely-independent) implies ( B .: S ) is  affinely-independent  affinely-independent (Subset of V)))));
let S being  c=-linear (Subset-Family of V);
A1: ( dom B ) = ( BOOL (the carrier of V) ) by FUNCT_2:def 1;
A2: (for n being Nat holds (P[ n ] implies P[ ( n + 1 ) ]))
proof
let n being Nat;
assume that
A3: P[ n ];
let k being Nat;
assume that
A4: k <= ( n + 1 );
per cases  by A4,NAT_1:8;
suppose k <= n;

hence thesis by A3;
end;
suppose A5: k = ( n + 1 );

let S being  c=-linear (Subset-Family of V);
assume that
A6: ( card ( union S ) ) = k
and
A7: ( union S ) is  finite  affinely-independent;
set U = ( union S );
A8: S c= ( bool U ) by ZFMISC_1:82;
set SU = ( S \ { U } );
A9: ( union SU ) c= U by XBOOLE_1:36,ZFMISC_1:77;
then reconsider Usu = ( union SU ) as  finite set by A7;
A10: SU c= S by XBOOLE_1:36;
A11: ( union SU ) <> U
proof
assume A12: ( union SU ) = U;
then SU is non empty by A5,A6,ZFMISC_1:2;
then ( union SU ) in SU by A7,A10,A8,SIMPLEX0:9;
hence contradiction by A12,ZFMISC_1:56;
end;
then ( union SU ) c< U by A9,XBOOLE_0:def 8;
then consider v being set such that A13: v in U and A14: (not v in ( union SU )) by XBOOLE_0:6;
reconsider v as (Element of V) by A13;
A15: ( ( U \ { v } ) \/ { ( B . U ) } ) is  affinely-independent  affinely-independent (Subset of V) by A7,A13,CKB34:1;
U is non empty by A5,A6;
then A16: U in ( dom B ) by A1,ZFMISC_1:56;
( B . U ) in { ( B . U ) } by TARSKI:def 1;
then ( B . U ) in ( ( U \ { v } ) \/ { ( B . U ) } ) by XBOOLE_0:def 3;
then reconsider BU = ( B . U ) as (Element of V) by A15;
S is non empty by A5,A6,ZFMISC_1:2;
then ( SU \/ { U } ) = S by A7,A8,SIMPLEX0:9,ZFMISC_1:116;
then A17: ( B .: S ) = ( ( B .: SU ) \/ ( B .: { U } ) ) by RELAT_1:120
.= ( ( B .: SU ) \/ ( Im (B,U) ) ) by RELAT_1:def 16
.= ( ( B .: SU ) \/ { BU } ) by A16,FUNCT_1:59;
A18: { v } c= U by A13,ZFMISC_1:31;
A19: ( card { v } ) = 1 by CARD_1:30;
per cases ;
suppose n = ( 0 );

then A20: U = { v } by A5,A6,A7,A18,A19,CARD_FIN:1;
( SU /\ ( dom B ) ) = ( {} )
proof
assume ( SU /\ ( dom B ) ) <> ( {} );
then consider x such that A21: x in ( SU /\ ( dom B ) ) by XBOOLE_0:def 1;
x in SU by A21,XBOOLE_0:def 4;
then A22: x c= ( union SU ) by ZFMISC_1:74;
then x c= U by A9,XBOOLE_1:1;
then A23: (x = U or x = ( {} )) by A20,ZFMISC_1:33;
(not v in x) by A14,A22;
hence thesis by A20,A21,A23,TARSKI:def 1,ZFMISC_1:56;
end;
then ( B .: SU ) = ( B .: ( {} ) ) by RELAT_1:112
.= ( {} ) by RELAT_1:116;
hence thesis by A17;
end;
suppose A24: n > ( 0 );

reconsider u = U as  finite set by A7;
A25: Usu c= u by XBOOLE_1:36,ZFMISC_1:77;
then ( card Usu ) <= ( n + 1 ) by A5,A6,NAT_1:43;
then ( card Usu ) < ( n + 1 ) by A5,A6,A11,A25,CARD_FIN:1,XXREAL_0:1;
then A26: ( card Usu ) <= n by NAT_1:13;
(( union SU ) c= ( U \ { v } ) & ( U \ { v } ) c= ( ( U \ { v } ) \/ { ( B . U ) } )) by A9,A14,XBOOLE_1:7,ZFMISC_1:34;
then ( union SU ) is  affinely-independent by A15,RLAFFIN1:43,XBOOLE_1:1;
then reconsider BSU = ( B .: SU ) as  affinely-independent (Subset of V) by A3,A10,A26;
BSU c= ( Affin ( U \ { v } ) )
proof
let y;
assume y in BSU;
then consider x such that A27: x in ( dom B ) and A28: x in SU and A29: ( B . x ) = y by FUNCT_1:def 6;
reconsider x as non empty (Subset of V) by A27,ZFMISC_1:56;
x in S by A28,XBOOLE_0:def 5;
then A30: x c= U by ZFMISC_1:74;
x c= ( union SU ) by A28,ZFMISC_1:74;
then (not v in x) by A14;
then x c= ( U \ { v } ) by A30,ZFMISC_1:34;
then A31: ( conv x ) c= ( conv ( U \ { v } ) ) by RLTOPSP1:20;
y in ( conv x ) by A7,A29,A30,CKB21:1;
then A32: y in ( conv ( U \ { v } ) ) by A31;
( conv ( U \ { v } ) ) c= ( Affin ( U \ { v } ) ) by RLAFFIN1:65;
hence thesis by A32;
end;
then A33: ( Affin BSU ) c= ( Affin ( U \ { v } ) ) by RLAFFIN1:51;
( card U ) <> 1 by A5,A6,A24;
then (not BU in U) by A7,CKB24:1;
then (not BU in ( U \ { v } )) by XBOOLE_0:def 5;
then (not BU in ( Affin BSU )) by A15,A33,CKB33:1;
hence thesis by A17,CKB33:1;
end;
end;
end;
A34: P[ (( 0 ) qua Nat) ]
proof
let k being Nat;
assume A35: k <= ( 0 );
let S being  c=-linear (Subset-Family of V);
assume that
A36: ( card ( union S ) ) = k
and
( union S ) is  finite  affinely-independent;
A37: ( union S ) = ( {} ) by A35,A36;
( S /\ ( dom B ) ) = ( {} )
proof
assume ( S /\ ( dom B ) ) <> ( {} );
then consider x such that A38: x in ( S /\ ( dom B ) ) by XBOOLE_0:def 1;
x in S by A38,XBOOLE_0:def 4;
then A39: x c= ( {} ) by A37,ZFMISC_1:74;
x <> ( {} ) by A38,ZFMISC_1:56;
hence contradiction by A39;
end;
then ( B .: S ) = ( B .: ( {} ) ) by RELAT_1:112
.= ( {} ) by RELAT_1:116;
hence thesis;
end;
A40: (for n being Nat holds P[ n ]) from NAT_1:sch 2(A34,A2);
assume A41: ( union S ) is  finite  affinely-independent;
then ( card ( union S ) ) is Nat;
hence thesis by A40,A41;
end;
