environ
vocabularies ARYTM_1,ARYTM_3,XBOOLE_0,CARD_1,CONVEX1,CONVEX2,CONVEX3,FINSEQ_1,FINSEQ_2,FINSEQ_4,FINSET_1,FUNCOP_1,FUNCT_1,FUNCT_2,FUNCT_4,MEMBERED,ORDERS_1,RELAT_1,RLVECT_1,RLVECT_2,RUSUB_4,SEMI_AF1,SETFAM_1,TARSKI,TOPS_1,RLAFFIN1,RLAFFIN2,ZFMISC_1,REAL_1,CARD_3,XXREAL_0,NAT_1,SUBSET_1,NUMBERS,ORDINAL1,STRUCT_0,SUPINF_2,ORDINAL4,VALUED_1,XREAL_0,PARTFUN1;
notations TARSKI,XBOOLE_0,SUBSET_1,ZFMISC_1,ORDINAL1,NUMBERS,NAT_1,XCMPLX_0,XXREAL_0,ORDERS_1,CARD_1,XREAL_0,REAL_1,FINSET_1,SETFAM_1,DOMAIN_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,RELSET_1,FINSEQ_1,STRUCT_0,FINSEQ_2,SEQ_1,FINSEQOP,RVSUM_1,RLVECT_1,RLVECT_2,RUSUB_4,CONVEX1,CONVEX2,CONVEX3,RLAFFIN1,FUNCT_4,FUNCOP_1,MEMBERED,XXREAL_2;
definitions ORDERS_1,RLVECT_2,TARSKI,XBOOLE_0;
theorems BORSUK_4,CARD_1,CARD_2,CARD_FIN,CONVEX1,CONVEX3,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,FUNCOP_1,FUNCT_1,FUNCT_2,FUNCT_4,NAT_1,MEMBERED,PARTFUN1,RELAT_1,RLAFFIN1,RLTOPSP1,RUSUB_4,RLVECT_2,RLVECT_3,RLVECT_4,RVSUM_1,STIRL2_1,SIMPLEX0,TARSKI,WELLORD2,XBOOLE_0,XBOOLE_1,XCMPLX_1,XREAL_0,XREAL_1,XXREAL_0,XXREAL_2,ZFMISC_1,RLVECT_1,CKB1,CKB2,CKB3,CKB4,CKB5;
schemes FRAENKEL,FUNCT_2,NAT_1,RLVECT_4;
registrations CARD_1,FINSET_1,FINSEQ_2,FUNCT_2,MEMBERED,NAT_1,NUMBERS,RELAT_1,RLVECT_1,RLVECT_3,STRUCT_0,SUBSET_1,VALUED_0,XCMPLX_0,XREAL_0,XXREAL_0,XBOOLE_0,RLAFFIN1,SIMPLEX0,FUNCOP_1,XXREAL_3,REALSET1,SETFAM_1,XXREAL_2,ABIAN,PARTFUN1,RVSUM_1,FINSEQ_1,RELSET_1,DILWORTH,RLVECT_2;
constructors BINOP_2,CONVEX1,CONVEX3,DOMAIN_1,FINSEQOP,REAL_1,RLVECT_3,RVSUM_1,RUSUB_5,SEQ_1,SETFAM_1,RLAFFIN1,SIMPLEX0,XXREAL_2,FUNCT_4,RELSET_1,PARTFUN1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve x for set;
definition
let V being non empty RLSStruct;
let A being (Subset of V);
func Int A -> (Subset of V)
means
:Def1: (x in it iff (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B ))))));
existence
proof
set I = { x where x is (Element of V): (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B ))))) };
now
let x;
assume x in I;
then (ex y being (Element of V) st ((x = y & y in ( conv A )) & (not (ex B being (Subset of V) st (B c< A & y in ( conv B ))))));
hence x in (the carrier of V);
end;
then reconsider I as (Subset of V) by TARSKI:def 3;
take I;
let x;
hereby
assume x in I;
then (ex y being (Element of V) st ((x = y & y in ( conv A )) & (not (ex B being (Subset of V) st (B c< A & y in ( conv B ))))));
hence (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B )))));
end;
assume (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B )))));
hence thesis;
end;
uniqueness
proof
let I1 being (Subset of V),I2 being (Subset of V);
assume that
A1: (x in I1 iff (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B ))))))
and
A2: (x in I2 iff (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B ))))));
now
let x;
(x in I1 iff (x in ( conv A ) & (not (ex B being (Subset of V) st (B c< A & x in ( conv B )))))) by A1;
hence (x in I1 iff x in I2) by A2;
end;
hence thesis by TARSKI:1;
end;
end;
