environ
vocabularies XBOOLE_0,FUNCT_1,SUBSET_1,TARSKI,COH_SP,FINSET_1,RELAT_1,CLASSES1,ZFMISC_1,FINSUB_1,NUMBERS,CARD_1,ARYTM_3,ARYTM_1,MSSUBFAM,FUNCOP_1,PBOOLE,MCART_1,CARD_3,XBOOLEAN,FINSEQ_1,LATTICES,EQREL_1,COHSP_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,REAL_1,NAT_1,MCART_1,RELAT_1,FUNCT_1,FINSEQ_1,FINSET_1,FINSUB_1,CLASSES1,COH_SP,PBOOLE,CARD_3,PARTFUN1,FUNCT_2,FUNCOP_1,CKB2,CKB4;
definitions XBOOLE_0,TARSKI,RELAT_1,COH_SP,CLASSES1,FINSUB_1,CKB2,CKB4;
theorems TARSKI,ENUMSET1,ZFMISC_1,RELAT_1,COH_SP,FUNCT_1,FUNCT_2,FINSEQ_1,FINSET_1,FINSUB_1,FUNCOP_1,MCART_1,CARD_1,CLASSES1,CARD_2,CARD_3,FUNCT_5,CARD_5,RELSET_1,XBOOLE_0,XBOOLE_1,XCMPLX_1,PARTFUN1,CKB1,CKB2,CKB4;
schemes NAT_1,SUBSET_1,FUNCT_1,FINSET_1,CARD_3,XBOOLE_0,CARD_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,PARTFUN1,FINSET_1,FINSUB_1,XREAL_0,NAT_1,FINSEQ_1,ORDINAL1,CARD_1,RELAT_1,CKB3;
constructors FINSUB_1,REAL_1,NAT_1,CARD_3,PBOOLE,BORSUK_1,COH_SP,CKB4;
requirements NUMERALS,BOOLE,SUBSET;
begin
definition
let X being set;
func Sub_of_Fin X -> (Subset of X) means 
:Def3: (for x being set holds (x in it iff (x in X & x is  finite)));
existence
proof
defpred P[ set ]
 means
$1 is  finite;
thus (ex W being (Subset of X) st (for x being set holds (x in W iff (x in X & P[ x ])))) from SUBSET_1:sch 1;
end;
correctness
proof
let X1 being (Subset of X);
let X2 being (Subset of X);
assume A1: (not thesis);
then consider x being set such that A2: (not (x in X1 iff x in X2)) by TARSKI:1;
(x in X2 iff (not (x in X & x is  finite))) by A1,A2;
hence thesis by A1;
end;
end;
