environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,MARGREL1,FUNCT_1,XBOOLEAN,RELAT_1,TARSKI,BVFUNC_1;
notations TARSKI,XBOOLE_0,SUBSET_1,XBOOLEAN,MARGREL1,RELAT_1,FUNCT_1,FUNCT_2,BVFUNC_1,CKB1,CKB2,CKB5,CKB6,CKB7,CKB8;
definitions TARSKI,MARGREL1,CKB1,CKB2,CKB5,CKB6;
theorems FUNCT_1,FUNCT_2,MARGREL1,BVFUNC_1,BVFUNC_4,BVFUNC_8,BVFUNC25,XBOOLEAN,CKB1,CKB2,CKB5,CKB6,CKB9,CKB10,CKB11;
schemes FUNCT_1;
registrations FUNCT_1,FUNCT_2,XBOOLEAN,MARGREL1,XBOOLE_0,CKB3,CKB4;
constructors BVFUNC_1,RELSET_1,CKB1,CKB2,CKB5,CKB6,CKB7,CKB8;
requirements SUBSET,BOOLE;
begin
reserve Y for non empty set;
reserve a for (Element of ( Funcs (Y,( BOOLEAN )) ));
theorem
Th4: ( ( O_el Y ) 'nand' a ) = ( I_el Y )
proof
(( ( O_el Y ) 'nand' a ) = ( 'not' ( ( O_el Y ) '&' a ) ) & ( ( O_el Y ) '&' a ) = ( O_el Y )) by CKB9:1,BVFUNC_1:5;
hence thesis by BVFUNC_1:2;
end;
