environ
vocabularies NUMBERS,STRUCT_0,RELAT_1,XBOOLE_0,SUBSET_1,FINSEQ_1,TDGROUP,TARSKI,ORDINAL4,ARYTM_3,CARD_1,FUNCT_1,XXREAL_0,NAT_1,ZFMISC_1,ORDINAL1,FINSET_1,LANG1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,NAT_1,DOMAIN_1,RELAT_1,STRUCT_0,FUNCT_1,FINSEQ_1,FINSET_1,RELSET_1,PARTFUN1,FUNCT_2,FINSEQ_2,XXREAL_0,PRE_POLY,CKB1,CKB3,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB16,CKB20,CKB22,CKB23,CKB24,CKB25,CKB26,CKB30;
definitions XBOOLE_0,TARSKI,RELAT_1,STRUCT_0,ORDINAL1,CKB7,CKB8,CKB9,CKB11,CKB16,CKB20,CKB24,CKB25,CKB26,CKB30;
theorems TARSKI,ZFMISC_1,RELAT_1,FINSEQ_1,NAT_1,RELSET_1,TREES_2,FUNCT_2,FINSEQ_3,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,ORDINAL1,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB24,CKB25,CKB26,CKB30,CKB32;
schemes NAT_1,FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,FINSEQ_1,STRUCT_0,ORDINAL1,CARD_1,RELSET_1,CKB1,CKB2,CKB3,CKB4,CKB27,CKB28,CKB29,CKB31;
constructors PARTFUN1,DOMAIN_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_2,STRUCT_0,RELSET_1,PRE_POLY,CKB1,CKB3,CKB7,CKB8,CKB9,CKB11,CKB16,CKB20,CKB22,CKB23,CKB24,CKB25,CKB26,CKB30;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve a for set;
reserve b for set;
theorem
Th11: ( Lang ( EmptyGrammar a ) ) = { ( {} ) }
proof
set E = ( EmptyGrammar a );
A1: ( Terminals E ) = ( {} ) by CKB32:1;
thus ( Lang E ) c= { ( {} ) }
proof
let b;
assume b in ( Lang E );
then (ex p being (String of E) st ((b = p & ( rng p ) c= ( Terminals E )) & p is_derivable_from <* (the InitialSym of E) *>));
then b = ( {} ) by A1;
hence thesis by TARSKI:def 1;
end;

let b;
assume b in { ( {} ) };
then A2: b = ( {} ) by TARSKI:def 1;
(the Rules of E) = { [ a,( {} ) ] } by CKB24:def 1;
then A3: [ a,( {} ) ] in (the Rules of E) by TARSKI:def 1;
(the carrier of E) = { a } by CKB24:def 1;
then a = (the InitialSym of E) by TARSKI:def 1;
then (the InitialSym of E) ==> ( <*> (the carrier of E) ) by A3,CKB7:def 1;
then A4: ( <*> (the carrier of E) ) is_derivable_from <* (the InitialSym of E) *> by CKB13:1,CKB18:1;
( rng ( {} ) ) = ( {} );
hence thesis by A1,A2,A4;
end;
