environ
vocabularies RELAT_1,FUNCT_1,TOPS_1,ARYTM_1,CONNSP_2,EUCLID,PRE_TOPC,ORDINAL2,METRIC_1,TOPMETR,RCOMP_1,PCOMPS_1,TARSKI,XBOOLE_0,NUMBERS,NAT_1,SUBSET_1,XXREAL_0,ARYTM_3,ORDINAL1,XREAL_0,CARD_1,XXREAL_1;
notations TARSKI,SUBSET_1,FUNCT_1,RELSET_1,FUNCT_2,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,XXREAL_0,MEMBERED,NAT_1,RCOMP_1,STRUCT_0,PRE_TOPC,TOPS_1,CONNSP_2,METRIC_1,PCOMPS_1,TOPMETR,T_0TOPSP,EUCLID,TOPREAL9,TOPREALB;
definitions TARSKI,T_0TOPSP,METRIC_1,PCOMPS_1,TOPMETR,BORSUK_4,TOPREALB;
theorems FUNCT_2,TOPMETR,TOPREAL9,EUCLID,JGRAPH_2,GOBOARD6,TOPS_1,METRIC_1,XBOOLE_1,T_0TOPSP,XREAL_0,FRECHET,TOPREAL6,RELAT_1,UNIFORM1,CONNSP_2,TOPGRP_1,ORDINAL1,TOPS_3,YELLOW12,TOPGEN_5,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16;
registrations XBOOLE_0,RELAT_1,MEMBERED,XREAL_0,PRE_TOPC,STRUCT_0,EUCLID,TOPREALB,XXREAL_0,METRIC_1,BORSUK_6,TOPMETR,TOPREAL9,PCOMPS_1,RCOMP_1,TOPGRP_1,EUCLID_9;
constructors TOPREAL9,TOPREALB,TOPS_1,BORSUK_4,T_0TOPSP,FUNCSDOM,PCOMPS_1;
requirements SUBSET,REAL;
begin
reserve M1 for non empty MetrSpace;
reserve M2 for non empty MetrSpace;
theorem
Th17: (for f being (Function of ( TopSpaceMetr M1 ),( TopSpaceMetr M2 )) holds (f is  continuous iff (for p being (Point of M1) holds (for q being (Point of M2) holds (for r being  positive  real number holds (q = ( f . p ) implies (ex s being  positive  real number st ( f .: ( Ball (p,s) ) ) c= ( Ball (q,r) ))))))))
proof
let f being (Function of ( TopSpaceMetr M1 ),( TopSpaceMetr M2 ));
hereby
assume A1: f is  continuous;
let p being (Point of M1);
let q being (Point of M2);
let r being  positive  real number;
assume that
A2: q = ( f . p );
r in ( REAL ) by XREAL_0:def 1;
then consider s being (Element of ( REAL )) such that A3: s > ( 0 ) and A4: (for w being (Element of M1) holds (for w1 being (Element of M2) holds ((w1 = ( f . w ) & ( dist (p,w) ) < s) implies ( dist (q,w1) ) < r))) by A1,A2,UNIFORM1:4;
reconsider s as  positive  real number by A3;
take s;
thus ( f .: ( Ball (p,s) ) ) c= ( Ball (q,r) )
proof
let y being set;
assume y in ( f .: ( Ball (p,s) ) );
then consider x being (Point of ( TopSpaceMetr M1 )) such that A5: x in ( Ball (p,s) ) and A6: ( f . x ) = y by FUNCT_2:65;
reconsider x1 = x as (Point of M1);
reconsider y1 = y as (Point of M2) by A6;
( dist (p,x1) ) < s by A5,METRIC_1:11;
then ( dist (q,y1) ) < r by A6,A4;
hence y in ( Ball (q,r) ) by METRIC_1:11;
end;

end;
assume A7: (for p being (Point of M1) holds (for q being (Point of M2) holds (for r being  positive  real number holds (q = ( f . p ) implies (ex s being  positive  real number st ( f .: ( Ball (p,s) ) ) c= ( Ball (q,r) ))))));
(for r being  real number holds (for u being (Element of M1) holds (for u1 being (Element of M2) holds ((r > ( 0 ) & u1 = ( f . u )) implies (ex s being  real number st (s > ( 0 ) & (for w being (Element of M1) holds (for w1 being (Element of M2) holds ((w1 = ( f . w ) & ( dist (u,w) ) < s) implies ( dist (u1,w1) ) < r)))))))))
proof
let r being  real number;
let u being (Element of M1);
let u1 being (Element of M2);
assume (r > ( 0 ) & u1 = ( f . u ));
then consider s being  positive  real number such that A8: ( f .: ( Ball (u,s) ) ) c= ( Ball (u1,r) ) by A7;
take s;
thus s > ( 0 );
let w being (Element of M1);
let w1 being (Element of M2);
assume that
A9: w1 = ( f . w );
assume ( dist (u,w) ) < s;
then w in ( Ball (u,s) ) by METRIC_1:11;
then ( f . w ) in ( f .: ( Ball (u,s) ) ) by FUNCT_2:35;
hence thesis by A8,A9,METRIC_1:11;
end;
hence thesis by UNIFORM1:3;
end;
