environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,XBOOLE_0,PARTFUN1,SUBSET_1,FUNCT_1,RELAT_1,XXREAL_2,COMPLEX1,ARYTM_1,XXREAL_0,SEQ_4,ARYTM_3,REAL_1,FDIFF_1,RCOMP_1,TARSKI,VALUED_1,CARD_1,ORDINAL4,INTEGRA5,INTEGRA1,XXREAL_1,SQUARE_1,ORDINAL2,FUNCOP_1,FCONT_1,REALSET1,SIN_COS,PREPOWER,SEQFUNC,SEQ_1,SEQ_2,INTEGRA2,FUNCT_3,FINSEQ_1,FINSEQ_2,CARD_3,MEASURE7,NAT_1,INTEGRA7;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,XXREAL_0,XXREAL_2,COMPLEX1,REAL_1,NAT_1,FUNCOP_1,RELSET_1,FUNCT_2,RCOMP_1,PARTFUN1,PARTFUN2,FINSEQ_1,VALUED_1,SEQ_1,RFUNCT_1,SEQ_2,SEQ_4,SQUARE_1,PREPOWER,FCONT_1,FDIFF_1,FINSEQ_2,RVSUM_1,INTEGRA1,INTEGRA2,SEQFUNC,SIN_COS,TAYLOR_1,INTEGRA3,INTEGRA5,CKB11,CKB12;
definitions XCMPLX_0,SUBSET_1,INTEGRA1,INTEGRA5,VALUED_1,FDIFF_1,SQUARE_1,CKB11,CKB12;
theorems TARSKI,PARTFUN1,RVSUM_1,ZFMISC_1,PREPOWER,INTEGRA1,INTEGRA2,RFUNCT_1,FUNCT_1,SEQ_1,SEQ_2,FDIFF_1,SEQFUNC,ABSVALUE,XCMPLX_1,FINSEQ_1,FINSEQ_2,RCOMP_1,FCONT_1,FDIFF_2,RELAT_1,XREAL_0,XXREAL_0,PARTFUN2,FUNCT_2,XBOOLE_0,XBOOLE_1,SEQ_4,XREAL_1,COMPLEX1,INTEGRA4,INTEGRA5,SIN_COS,INTEGRA6,TAYLOR_1,VALUED_1,XXREAL_1,XXREAL_2,FUNCOP_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16;
schemes FUNCT_2,XBOOLE_0;
registrations XREAL_0,RELSET_1,FINSEQ_2,INTEGRA1,RCOMP_1,INT_1,ORDINAL1,MEMBERED,PREPOWER,XBOOLE_0,NUMBERS,VALUED_0,VALUED_1,FUNCT_2,XXREAL_2,SEQ_2,FCONT_3,MEASURE5;
constructors REAL_1,FDIFF_1,PARTFUN1,PARTFUN2,RFUNCT_1,INTEGRA2,LIMFUNC1,FCONT_1,PSCOMP_1,NAT_1,BINOP_2,INTEGRA5,SIN_COS,PREPOWER,TAYLOR_1,SQUARE_1,SEQ_1,XXREAL_2,RFUNCT_2,SEQFUNC,RVSUM_1,SEQ_4,RELSET_1,SEQ_2,COMPLEX1,INTEGRA3,CKB11,CKB12;
requirements NUMERALS,BOOLE,SUBSET,REAL,ARITHM;
begin
reserve X for set;
reserve f for (PartFunc of ( REAL ),( REAL ));
reserve g for (PartFunc of ( REAL ),( REAL ));
reserve F for (PartFunc of ( REAL ),( REAL ));
reserve G for (PartFunc of ( REAL ),( REAL ));
theorem
((F is_integral_of f,X & G is_integral_of g,X) implies ( F (#) G ) is_integral_of ( ( f (#) G ) + ( F (#) g ) ),X)
proof
assume that
A1: F is_integral_of f,X
and
A2: G is_integral_of g,X;
A3: G is_differentiable_on X by A2,CKB13:1;
A4: X c= ( dom F ) by A1,CKB14:1;
A5: ( G `| X ) = ( g | X ) by A2,CKB13:1;
then ( dom ( g | X ) ) = X by A3,FDIFF_1:def 7;
then ( ( dom g ) /\ X ) = X by RELAT_1:61;
then X c= ( dom g ) by XBOOLE_1:18;
then X c= ( ( dom F ) /\ ( dom g ) ) by A4,XBOOLE_1:19;
then A6: X c= ( dom ( F (#) g ) ) by VALUED_1:def 4;
A7: X c= ( dom G ) by A2,CKB14:1;
A8: F is_differentiable_on X by A1,CKB13:1;
then A9: ( F (#) G ) is_differentiable_on X by A3,CKB6:1;
A10: ( F `| X ) = ( f | X ) by A1,CKB13:1;
then ( dom ( f | X ) ) = X by A8,FDIFF_1:def 7;
then ( ( dom f ) /\ X ) = X by RELAT_1:61;
then X c= ( dom f ) by XBOOLE_1:18;
then X c= ( ( dom f ) /\ ( dom G ) ) by A7,XBOOLE_1:19;
then X c= ( dom ( f (#) G ) ) by VALUED_1:def 4;
then X c= ( ( dom ( f (#) G ) ) /\ ( dom ( F (#) g ) ) ) by A6,XBOOLE_1:19;
then A11: X c= ( dom ( ( f (#) G ) + ( F (#) g ) ) ) by VALUED_1:def 1;
A12:now
let x being (Element of ( REAL ));
assume x in ( dom ( ( F (#) G ) `| X ) );
then A13: x in X by A9,FDIFF_1:def 7;
then ( F | X ) is_differentiable_in x by A8,FDIFF_1:def 6;
then A14: F is_differentiable_in x by A13,CKB4:1;
( ( G `| X ) . x ) = ( diff (G,x) ) by A3,A13,FDIFF_1:def 7;
then ( g . x ) = ( diff (G,x) ) by A5,A13,FUNCT_1:49;
then A15: ( ( F (#) g ) . x ) = ( ( F . x ) * ( diff (G,x) ) ) by VALUED_1:5;
( ( F `| X ) . x ) = ( diff (F,x) ) by A8,A13,FDIFF_1:def 7;
then ( f . x ) = ( diff (F,x) ) by A10,A13,FUNCT_1:49;
then A16: ( ( f (#) G ) . x ) = ( ( G . x ) * ( diff (F,x) ) ) by VALUED_1:5;
( G | X ) is_differentiable_in x by A3,A13,FDIFF_1:def 6;
then A17: G is_differentiable_in x by A13,CKB4:1;
( ( ( F (#) G ) `| X ) . x ) = ( diff (( F (#) G ),x) ) by A9,A13,FDIFF_1:def 7;
then ( ( ( F (#) G ) `| X ) . x ) = ( ( ( G . x ) * ( diff (F,x) ) ) + ( ( F . x ) * ( diff (G,x) ) ) ) by A14,A17,FDIFF_1:16;
then ( ( ( F (#) G ) `| X ) . x ) = ( ( ( F (#) g ) + ( f (#) G ) ) . x ) by A11,A13,A15,A16,VALUED_1:def 1;
hence ( ( ( F (#) G ) `| X ) . x ) = ( ( ( ( F (#) g ) + ( f (#) G ) ) | X ) . x ) by A13,FUNCT_1:49;
end;
X = ( dom ( ( ( f (#) G ) + ( F (#) g ) ) | X ) ) by A11,RELAT_1:62;
then ( dom ( ( F (#) G ) `| X ) ) = ( dom ( ( ( f (#) G ) + ( F (#) g ) ) | X ) ) by A9,FDIFF_1:def 7;
then ( ( F (#) G ) `| X ) = ( ( ( F (#) g ) + ( f (#) G ) ) | X ) by A12,PARTFUN1:5;
hence thesis by A9,CKB13:1;
end;
