environ
vocabularies NUMBERS,XBOOLE_0,STRUCT_0,GROUP_9,SUBSET_1,ORDINAL4,FUNCT_1,RELAT_1,TARSKI,GROUP_1,ALGSTR_0,ZFMISC_1,FUNCT_2,BINOP_1,SETFAM_1,CARD_1,FINSET_1,ORDINAL1,CARD_FIN,GROUP_2,EQREL_1,INT_2,NEWTON,INT_1,XXREAL_0,ARYTM_3,FINSEQ_1,NAT_1,PARTFUN1,CQC_SIM1,CARD_3,FUNCOP_1,FINSEQ_2,NAT_3,GR_CY_1,BINOP_2,XREAL_0,XCMPLX_0,ARYTM_1,RLSUB_1,GROUP_4,GRAPH_1,GROUP_3,REALSET1,GROUP_10;
notations TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,CARD_1,NUMBERS,XCMPLX_0,ZFMISC_1,XXREAL_0,XREAL_0,INT_2,NAT_1,NAT_D,FINSET_1,RELAT_1,REALSET1,FUNCT_1,RELSET_1,FUNCT_2,FINSEQ_1,RVSUM_1,STRUCT_0,ALGSTR_0,GROUP_1,GROUP_2,GROUP_3,EQREL_1,FUNCOP_1,WSIERP_1,NEWTON,DOMAIN_1,GR_CY_1,ORDINAL1,GROUP_4,CARD_FIN,PARTFUN1,NAT_3,TOPGRP_1,CKB1,CKB2,CKB3,CKB5,CKB8,CKB9,CKB10,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB28,CKB33,CKB34,CKB39;
definitions CARD_1,GROUP_2,TARSKI,REALSET1,RELAT_1,WELLORD2,STRUCT_0,FUNCT_2,CKB3,CKB9,CKB10,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB28,CKB33,CKB34,CKB39;
theorems FINSEQ_1,GROUP_2,GROUP_3,TARSKI,GROUP_6,FINSEQ_2,FUNCT_1,FUNCT_2,RELAT_1,XBOOLE_0,XBOOLE_1,NAT_1,GROUP_1,XREAL_1,RELSET_1,PARTFUN1,FINSEQ_3,INT_1,ZFMISC_1,CARD_1,CARD_2,FINSET_1,XCMPLX_1,ORDINAL1,FINSEQ_4,XXREAL_0,STRUCT_0,NAT_D,GR_CY_1,NEWTON,CARD_FIN,WEDDWITT,WELLORD2,EQREL_1,FUNCOP_1,RVSUM_1,PEPIN,NAT_4,GROUP_8,NAT_3,GROUP_9,GR_CY_2,TOPGRP_1,VALUED_1,XREAL_0,CKB3,CKB9,CKB10,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48;
schemes FUNCT_1,FINSEQ_1,NAT_1,FUNCT_2,SUBSET_1,CLASSES1,CKB6;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,ORDINAL1,RELSET_1,FINSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,CARD_1,FINSEQ_1,NEWTON,STRUCT_0,GROUP_2,GROUP_1,GROUP_3,GR_CY_1,FUNCT_2,NAT_3,REALSET1,VALUED_0,DYNKIN,CKB4,CKB7,CKB11,CKB29,CKB36,CKB37;
constructors SETFAM_1,WELLORD2,NAT_D,EQREL_1,BINARITH,WSIERP_1,REALSET2,GR_CY_1,GROUP_4,CARD_FIN,NAT_3,TOPGRP_1,SEQ_1,DYNKIN,RELSET_1,CKB2,CKB3,CKB9,CKB10,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB28,CKB33,CKB34,CKB39;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
theorem
Th14: (for G being  finite Group holds (for p being  prime  natural number holds ((for H being (Subgroup of G) holds (H is p -group implies (ex P being (Subgroup of G) st (P is_Sylow_p-subgroup_of_prime p & H is (Subgroup of P))))) & (for P1,P2 being (Subgroup of G) holds ((P1 is_Sylow_p-subgroup_of_prime p & P2 is_Sylow_p-subgroup_of_prime p) implies P1,P2 are_conjugated )))))
proof
let G being  finite Group;
let p being  prime  natural number;
reconsider p9 = p as  prime (Element of ( NAT )) by ORDINAL1:def 12;
A1: (for H,P being (Subgroup of G) holds ((H is p -group & P is_Sylow_p-subgroup_of_prime p) implies (ex g being (Element of G) st ( carr H ) c= ( carr ( P |^ g ) ))))
proof
let H being (Subgroup of G),P being (Subgroup of G);
set H9 = H;
set E = ( Left_Cosets P );
set T = ( the_left_operation_of (H9,P) );
reconsider E as non empty  finite set by GROUP_2:135;
reconsider T as (LeftOperation of H9,E);
assume H is p -group;
then A2: ( ( card ( the_fixed_points_of T ) ) mod p ) = ( ( card E ) mod p ) by CKB38:1;
assume P is_Sylow_p-subgroup_of_prime p;
then A3: (not p divides ( index P )) by CKB39:def 1;
now
assume ( ( card E ) mod p ) = ( 0 );
then ((ex t being Nat st (( card E ) = ( ( p * t ) + ( 0 ) ) & ( 0 ) < p)) or (( 0 ) = ( 0 ) & p = ( 0 ))) by NAT_D:def 2;
then p9 divides ( card E ) by NAT_D:def 3;
hence contradiction by A3,GROUP_2:def 18;
end;
then ( card ( the_fixed_points_of T ) ) <> ( 0 ) by A2,NAT_D:26;
then consider x being set such that A4: x in ( the_fixed_points_of T ) by CARD_1:27,XBOOLE_0:def 1;
x in { x9 where x9 is (Element of E): x9 is_fixed_under T } by A4,CKB23:def 1;
then consider x9 being (Element of E) such that x = x9 and A5: x9 is_fixed_under T;
x9 in ( Left_Cosets P );
then consider g9 being (Element of G) such that A6: x9 = ( g9 * P ) by GROUP_2:def 15;
set g = ( g9 " );
take g;
now
reconsider P1 = x9 as (Element of ( Left_Cosets P ));
let y being set;
assume y in ( carr H );
then reconsider h = y as (Element of H9);
reconsider h9 = h as (Element of H);
consider P2 being (Element of ( Left_Cosets P )),A1 being (Subset of G),A2 being (Subset of G),g99 being (Element of G) such that A7: (((P2 = ( ( the_left_translation_of (h9,P) ) . P1 ) & A2 = ( g99 * A1 )) & A1 = P1) & A2 = P2) and A8: g99 = h9 by CKB18:def 1;
( ( the_left_operation_of (H,P) ) . h9 ) = ( the_left_translation_of (h9,P) ) by CKB19:def 1;
then A9: ( ( g9 * P ) * ( g9 " ) ) = ( ( g99 * ( g9 * P ) ) * ( g9 " ) ) by A5,A6,A7,CKB22:def 1
.= ( g99 * ( ( g9 * P ) * ( g9 " ) ) ) by GROUP_2:33;
g99 in ( ( g9 * P ) * ( g9 " ) )
proof
( 1_ G ) in P by GROUP_2:46;
then A10: ( 1_ G ) in ( carr P ) by STRUCT_0:def 5;
g9 = ( g9 * ( 1_ G ) ) by GROUP_1:def 4;
then (( g9 * ( g9 " ) ) = ( 1_ G ) & g9 in ( g9 * P )) by A10,GROUP_1:def 5,GROUP_2:27;
then A11: (g99 = ( g99 * ( 1_ G ) ) & ( 1_ G ) in ( ( g9 * P ) * ( g9 " ) )) by GROUP_1:def 4,GROUP_2:28;
assume (not g99 in ( ( g9 * P ) * ( g9 " ) ));
hence contradiction by A9,A11,GROUP_2:27;
end;
hence y in ( ( g9 * P ) * ( g9 " ) ) by A8;
end;
then ( carr H ) c= ( ( ( g " ) * P ) * g ) by TARSKI:def 3;
hence thesis by GROUP_3:59;
end;
thus (for H being (Subgroup of G) holds (H is p -group implies (ex P being (Subgroup of G) st (P is_Sylow_p-subgroup_of_prime p & H is (Subgroup of P)))))
proof
let H being (Subgroup of G);
consider P9 being  strict (Subgroup of G) such that A12: P9 is_Sylow_p-subgroup_of_prime p by CKB46:1;
assume H is p -group;
then consider g being (Element of G) such that A13: ( carr H ) c= ( carr ( P9 |^ g ) ) by A1,A12;
set P = ( P9 |^ g );
take P;
set H2 = P;
reconsider H2 as  finite Group;
A14: ( card P9 ) = ( card P ) by GROUP_3:66;
P9 is p -group by A12,CKB39:def 1;
then consider H1 being  finite Group such that A15: P9 = H1 and A16: H1 is p -group;
(ex r being  natural number st ( card H1 ) = ( p |^ r )) by A16,CKB34:def 1;
then A17: H2 is p -group by A15,A14,CKB34:def 1;
A18: (not p divides ( index P9 )) by A12,CKB39:def 1;
( ( card P ) * ( index P ) ) = ( card G ) by GROUP_2:147
.= ( ( card P ) * ( index P9 ) ) by A14,GROUP_2:147;
then (not p divides ( index P )) by A18,XCMPLX_1:5;
hence P is_Sylow_p-subgroup_of_prime p by A17,CKB39:def 1;
thus thesis by A13,GROUP_2:57;
end;

let P1 being (Subgroup of G),P2 being (Subgroup of G);
assume A19: P1 is_Sylow_p-subgroup_of_prime p;
then A20: P1 is p -group by CKB39:def 1;
then consider H1 being  finite Group such that A21: P1 = H1 and A22: H1 is p -group;
A23: (not p divides ( index P1 )) by A19,CKB39:def 1;
consider r1 being  natural number such that A24: ( card H1 ) = ( p |^ r1 ) by A22,CKB34:def 1;
assume A25: P2 is_Sylow_p-subgroup_of_prime p;
then A26: (not p divides ( index P2 )) by CKB39:def 1;
P2 is p -group by A25,CKB39:def 1;
then consider H2 being  finite Group such that A27: P2 = H2 and A28: H2 is p -group;
consider r2 being  natural number such that A29: ( card H2 ) = ( p |^ r2 ) by A28,CKB34:def 1;
A30: ( card G ) = ( ( card P2 ) * ( index P2 ) ) by GROUP_2:147;
then A31: ( ( p |^ r1 ) * ( index P1 ) ) = ( ( p |^ r2 ) * ( index P2 ) ) by A21,A24,A27,A29,GROUP_2:147;
now
assume A32: r1 <> r2;
per cases  by A32,XXREAL_0:1;
suppose A33: r1 > r2;

set r = ( r1 -' r2 );
A34: ( r1 - r2 ) > ( r2 - r2 ) by A33,XREAL_1:9;
then A35: r = ( r1 - r2 ) by XREAL_0:def 2;
then consider k being Nat such that A36: r = ( k + 1 ) by A34,NAT_1:6;
r1 = ( r2 + r ) by A35;
then ( p9 |^ r1 ) = ( ( p9 |^ r2 ) * ( p9 |^ r ) ) by NEWTON:8;
then ( ( p9 |^ r2 ) * ( ( p9 |^ r ) * ( index P1 ) ) ) = ( ( p9 |^ r2 ) * ( index P2 ) ) by A31;
then ( ( p9 |^ r ) * ( index P1 ) ) = ( index P2 ) by XCMPLX_1:5;
then ( ( ( p |^ k ) * p ) * ( index P1 ) ) = ( index P2 ) by A36,NEWTON:6;
then ( p * ( ( p |^ k ) * ( index P1 ) ) ) = ( index P2 );
hence contradiction by A26,NAT_D:def 3;
end;
suppose A37: r1 < r2;

set r = ( r2 -' r1 );
A38: ( r2 - r1 ) > ( r1 - r1 ) by A37,XREAL_1:9;
then A39: r = ( r2 - r1 ) by XREAL_0:def 2;
then consider k being Nat such that A40: r = ( k + 1 ) by A38,NAT_1:6;
r2 = ( r1 + r ) by A39;
then ( p9 |^ r2 ) = ( ( p9 |^ r1 ) * ( p9 |^ r ) ) by NEWTON:8;
then ( ( p9 |^ r1 ) * ( ( p9 |^ r ) * ( index P2 ) ) ) = ( ( p9 |^ r1 ) * ( index P1 ) ) by A21,A24,A27,A29,A30,GROUP_2:147;
then ( ( p9 |^ r ) * ( index P2 ) ) = ( index P1 ) by XCMPLX_1:5;
then ( ( ( p |^ k ) * p ) * ( index P2 ) ) = ( index P1 ) by A40,NEWTON:6;
then ( p * ( ( p |^ k ) * ( index P2 ) ) ) = ( index P1 );
hence contradiction by A23,NAT_D:def 3;
end;
end;
then A41: ( card ( carr P1 ) ) = ( card ( carr P2 ) ) by A21,A24,A27,A29;
consider g being (Element of G) such that A42: ( carr P1 ) c= ( carr ( P2 |^ g ) ) by A1,A20,A25;
( card ( carr P2 ) ) = ( card P2 )
.= ( card ( P2 |^ g ) ) by GROUP_3:66
.= ( card ( carr ( P2 |^ g ) ) );
then ( the multMagma of P1 ) = ( the multMagma of ( P2 |^ g ) ) by A42,A41,CARD_FIN:1,GROUP_2:59;
hence thesis by GROUP_3:def 11;
end;
