environ
vocabularies RELAT_1,VALUED_1,TARSKI,XBOOLE_0,ORDERS_2,YELLOW_0,FUNCT_1,STRUCT_0,XXREAL_0,SUBSET_1,CAT_1,RELAT_2,WAYBEL_0,SEQM_3,FUNCOP_1,ORDINAL2,BINOP_1,GROUP_6,EQREL_1,FUNCT_3,BORSUK_1,WAYBEL_1,WELLORD1,REWRITE1,YELLOW_1,WAYBEL_3,NEWTON,CARD_3,PBOOLE,LATTICE3,FUNCT_4,RLVECT_2,ZFMISC_1,LATTICES,PRE_TOPC,RCOMP_1,WAYBEL18,CARD_1,YELLOW_9,T_0TOPSP,TOPS_2,YELLOW16,FUNCT_2;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,PBOOLE,RELSET_1,PARTFUN1,FUNCT_2,FUNCT_3,NUMBERS,FUNCT_7,FUNCOP_1,STRUCT_0,CARD_3,ZF_FUND1,PRALG_1,FUNCT_4,WELLORD1,ORDERS_2,LATTICE3,PRE_TOPC,TOPS_2,T_0TOPSP,BORSUK_1,QUANTAL1,YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_1,YELLOW_9,WAYBEL_3,WAYBEL18,CKB10,CKB11,CKB12,CKB13,CKB35,CKB37,CKB41,CKB53,CKB54;
definitions TARSKI,RELAT_1,LATTICE3,YELLOW_0,BORSUK_1,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_1,WAYBEL_3,T_0TOPSP,WAYBEL25,XBOOLE_0,STRUCT_0,CKB10,CKB11,CKB12,CKB13,CKB35,CKB53,CKB54;
theorems YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_1,PRE_TOPC,BORSUK_1,ORDERS_2,YELLOW12,ZF_FUND1,RELAT_1,FUNCT_2,FUNCT_1,ENUMSET1,WAYBEL_3,FUNCOP_1,LATTICE3,CARD_3,TARSKI,ZFMISC_1,WELLORD1,QUANTAL1,FUNCT_4,YELLOW_9,WAYBEL20,FUNCT_7,TOPS_2,FUNCT_3,WAYBEL10,T_0TOPSP,WAYBEL15,YELLOW_6,PRALG_1,WAYBEL18,WAYBEL13,WAYBEL21,XBOOLE_0,XBOOLE_1,PARTFUN1,CKB1,CKB2,CKB3,CKB5,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB62,CKB64,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71;
schemes PBOOLE,CKB57,CKB58,CKB59,CKB60;
registrations XBOOLE_0,FUNCT_1,RELSET_1,FUNCT_2,FUNCOP_1,STRUCT_0,PRE_TOPC,TOPS_1,BORSUK_1,LATTICE3,YELLOW_0,MONOID_0,BORSUK_2,WAYBEL_0,YELLOW_1,YELLOW_2,WAYBEL_1,WAYBEL_3,WAYBEL10,WAYBEL17,WAYBEL18,CKB4,CKB6,CKB36,CKB38,CKB39,CKB40,CKB61,CKB63,CKB65;
constructors TOLER_1,FUNCT_7,ZF_FUND1,TOPS_2,BORSUK_1,T_0TOPSP,MONOID_0,QUANTAL1,ORDERS_3,YELLOW_9,WAYBEL18,WAYBEL20,CKB10,CKB11,CKB12,CKB13,CKB35,CKB37,CKB41,CKB53,CKB54;
requirements SUBSET,BOOLE;
begin
theorem
(for L being non  empty RelStr holds (for X being non  empty set holds (for R being  full non  empty (SubRelStr of ( L |^ X )) holds ((for a being set holds (a is (Element of R) iff (ex x being (Element of L) st a = ( X --> x )))) implies L,R are_isomorphic ))))
proof
let L being non  empty RelStr;
let X being non  empty set;
deffunc F(set) = ( X --> $1 );
consider f being (ManySortedSet of (the carrier of L)) such that A1: (for i being (Element of L) holds ( f . i ) = F(i)) from PBOOLE:sch 5;
let R being  full non  empty (SubRelStr of ( L |^ X ));
assume that
A2: (for a being set holds (a is (Element of R) iff (ex x being (Element of L) st a = ( X --> x ))));
A3: ( rng f ) c= (the carrier of R)
proof
let y being set;
assume y in ( rng f );
then consider x being set such that A4: x in ( dom f ) and A5: y = ( f . x ) by FUNCT_1:def 3;
reconsider x as (Element of L) by A4,PARTFUN1:def 2;
y = ( X --> x ) by A1,A5;
then y is (Element of R) by A2;
hence thesis;
end;
A6: ( dom f ) = (the carrier of L) by PARTFUN1:def 2;
then reconsider f as (Function of L,R) by A3,FUNCT_2:2;
A7: f is  one-to-one
proof
let x being (Element of L);
let y being (Element of L);
( f . y ) = ( X --> y ) by A1;
then A8: ( f . y ) = [: X,{ y } :] by FUNCOP_1:def 2;
( f . x ) = ( X --> x ) by A1;
then ( f . x ) = [: X,{ x } :] by FUNCOP_1:def 2;
then (( f . x ) = ( f . y ) implies { x } = { y }) by A8,ZFMISC_1:110;
hence thesis by ZFMISC_1:3;
end;
A9:now
set i = the (Element of X);
let x being (Element of L);
let y being (Element of L);
reconsider a = ( f . x ),b = ( f . y ) as (Element of ( L |^ X )) by YELLOW_0:58;
reconsider Xx = ( X --> x ),Xy = ( X --> y ) as (Function of X,L);
reconsider a9 = a,b9 = b as (Element of ( product ( X --> L ) ));
A10: ( ( X --> L ) . i ) = L by FUNCOP_1:7;
A11: ( f . y ) = ( X --> y ) by A1;
A12: ( f . x ) = ( X --> x ) by A1;
hereby
assume A13: x <= y;
Xx <= Xy
proof
let i being set;
assume A14: i in X;
then A15: ( ( X --> y ) . i ) = y by FUNCOP_1:7;
( ( X --> x ) . i ) = x by A14,FUNCOP_1:7;
hence thesis by A13,A15;
end;
then a <= b by A12,A11,WAYBEL10:11;
hence ( f . x ) <= ( f . y ) by YELLOW_0:60;
end;
assume ( f . x ) <= ( f . y );
then a <= b by YELLOW_0:59;
then ( a9 . i ) <= ( b9 . i ) by WAYBEL_3:28;
then x <= ( Xy . i ) by A12,A11,A10,FUNCOP_1:7;
hence x <= y by FUNCOP_1:7;
end;
take f;
( rng f ) = (the carrier of R)
proof
thus ( rng f ) c= (the carrier of R);
let x being set;
assume x in (the carrier of R);
then reconsider a = x as (Element of R);
consider i being (Element of L) such that A16: a = ( X --> i ) by A2;
a = ( f . i ) by A1,A16;
hence thesis by A6,FUNCT_1:def 3;
end;
hence thesis by A7,A9,WAYBEL_0:66;
end;
