environ
vocabularies NUMBERS,XBOOLE_0,FINSEQ_1,ORDINAL4,RELAT_1,CARD_1,SUBSET_1,XXREAL_0,RFINSEQ,ARYTM_1,ARYTM_3,JORDAN3,FUNCT_1,FINSEQ_5,NAT_1,PARTFUN1,FINSEQ_8,FILEREC1;
notations XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,NAT_D,RELAT_1,RFINSEQ,FUNCT_1,PARTFUN1,FUNCT_2,FINSEQ_1,FINSEQ_4,FINSEQ_6,FINSEQ_5,FINSEQ_8,CKB21,CKB22;
definitions CKB22;
theorems NAT_1,NAT_2,REVROT_1,JORDAN4,FINSEQ_1,FINSEQ_2,FINSEQ_5,FINSEQ_6,RFINSEQ,FUNCT_2,FINSEQ_8,GENEALG1,TOPREAL3,CALCUL_1,FINSEQ_3,XREAL_1,CARD_1,XXREAL_0,PARTFUN1,XREAL_0,NAT_D,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38;
registrations XBOOLE_0,RELAT_1,FUNCT_1,XXREAL_0,XREAL_0,FINSEQ_1,FINSEQ_5,ORDINAL1,CARD_1;
constructors XXREAL_0,NAT_1,PARTFUN1,RFINSEQ,NAT_D,FINSEQ_4,FINSEQ_5,CQC_LANG,FINSEQ_6,FINSEQ_8,REAL_1,RELSET_1,CKB22;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
theorem
Th38: (for D being non empty set holds (for f,g being (File of D) holds (for n being (Element of ( NAT )) holds ((( 0 ) < n & g = ( {} )) implies ( instr (n,f,g) ) = n))))
proof
let D being non empty set;
let f being (File of D),g being (File of D);
let n being (Element of ( NAT ));
assume that
A1: ( 0 ) < n
and
A2: g = ( {} );
A3: ( len g ) = ( 0 ) by A2;
( instr (n,f,g) ) <> ( 0 )
proof
assume ( instr (n,f,g) ) = ( 0 );
then (not g is_substring_of f,n) by FINSEQ_8:def 10;
hence contradiction by A3,FINSEQ_8:def 7;
end;
then A4: n <= ( instr (n,f,g) ) by FINSEQ_8:def 10;
g is_preposition_of ( f /^ ( n -' 1 ) ) by A3,FINSEQ_8:def 8;
then n >= ( instr (n,f,g) ) by A1,FINSEQ_8:def 10;
hence thesis by A4,XXREAL_0:1;
end;
