:: Homomorphisms of algebras. Quotient Universal Algebra
::  by Ma{\l}gorzata Korolkiewicz
::
:: Received October 12, 1993
:: Copyright (c) 1993-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies UNIALG_1, SUBSET_1, NUMBERS, UNIALG_2, XBOOLE_0, FINSEQ_1,
      FUNCT_1, RELAT_1, NAT_1, TARSKI, STRUCT_0, PARTFUN1, MSUALG_3, CQC_SIM1,
      WELLORD1, FINSEQ_2, GROUP_6, EQREL_1, FUNCT_2, CARD_3, RELAT_2, ALG_1;
 notations TARSKI, XBOOLE_0, SUBSET_1, NUMBERS, ORDINAL1, NAT_1, RELAT_1,
      RELAT_2, FUNCT_1, RELSET_1, FINSEQ_1, PARTFUN1, EQREL_1, FINSEQ_2,
      FUNCT_2, STRUCT_0, MARGREL1, UNIALG_1, FINSEQOP, FINSEQ_3, UNIALG_2;
 constructors EQREL_1, FINSEQOP, UNIALG_2, RELSET_1, CARD_3, FINSEQ_3, CARD_1,
      NAT_1;
 registrations RELAT_1, FUNCT_1, PARTFUN1, FUNCT_2, EQREL_1, FINSEQ_2,
      STRUCT_0, UNIALG_1, UNIALG_2, ORDINAL1, FINSEQ_1, CARD_1, RELSET_1,
      MARGREL1, XBOOLE_0;
 requirements BOOLE, SUBSET;
 definitions UNIALG_2, RELAT_2, TARSKI, FUNCT_1, XBOOLE_0, FUNCT_2, MARGREL1,
      FINSEQ_3;
 theorems FINSEQ_1, FINSEQ_2, FUNCT_1, FUNCT_2, PARTFUN1, UNIALG_1, UNIALG_2,
      RELAT_1, RELSET_1, EQREL_1, ZFMISC_1, FINSEQ_3, XBOOLE_0, RELAT_2,
      ORDERS_1, MARGREL1;
 schemes FINSEQ_1, RELSET_1, FUNCT_2, FUNCT_1;

begin
theorem
L1: (for R1 being Universal_Algebra holds (for B1 being non  empty (Subset of R1) holds (B1 = (the carrier of R1) implies ( Opers (R1 , B1) ) = (the charact of R1))))
proof
let R1 being Universal_Algebra;
let C1 being non  empty (Subset of R1);
L2: ( dom ( Opers (R1 , C1) ) ) = ( dom (the charact of R1) ) by UNIALG_2:def 6;
assume L3: C1 = (the carrier of R1);
L4:
now
let C2 being Nat;
assume L5: C2 in ( dom (the charact of R1) );
reconsider D1 = ( (the charact of R1) . C2 ) as (operation of R1) by L5 , FUNCT_1:def 3;
thus L6: ( ( Opers (R1 , C1) ) . C2 ) = ( D1 /. C1 ) by L2 , L5 , UNIALG_2:def 6
.= ( (the charact of R1) . C2 ) by L3 , UNIALG_2:4;
end;
thus L7: thesis by L4 , L2 , FINSEQ_1:13;
end;
theorem
L8: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R12 being (Function of R1 , R2) holds ( R12 * ( <*> (the carrier of R1) ) ) = ( <*> (the carrier of R2) ))));
theorem
L9: (for R1 being Universal_Algebra holds (for R11 being (FinSequence of R1) holds ( ( id (the carrier of R1) ) * R11 ) = R11))
proof
let R1 being Universal_Algebra;
let R11 being (FinSequence of R1);
set D2 = ( id (the carrier of R1) );
L10: ( dom ( D2 * R11 ) ) = ( dom R11 ) by FINSEQ_3:120;
L11:
now
let C3 being Nat;
assume L12: C3 in ( dom ( D2 * R11 ) );
reconsider D3 = ( R11 . C3 ) as (Element of R1) by L12 , L10 , FINSEQ_2:11;
L13: ( D2 . D3 ) = D3 by FUNCT_1:18;
thus L14: ( ( D2 * R11 ) . C3 ) = ( R11 . C3 ) by L13 , L12 , FINSEQ_3:120;
end;
L15: ( len ( D2 * R11 ) ) = ( len R11 ) by FINSEQ_3:120;
thus L16: thesis by L15 , L11 , FINSEQ_2:9;
end;
theorem
L17: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R3 being Universal_Algebra holds (for B2 being (Function of R1 , R2) holds (for B3 being (Function of R2 , R3) holds (for B4 being (FinSequence of R1) holds ( B3 * ( B2 * B4 ) ) = ( ( B3 * B2 ) * B4 )))))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R3 being Universal_Algebra;
let C4 being (Function of R1 , R2);
let C5 being (Function of R2 , R3);
let C6 being (FinSequence of R1);
L18: ( dom C6 ) = ( Seg ( len C6 ) ) by FINSEQ_1:def 3;
L19: ( dom ( C5 * ( C4 * C6 ) ) ) = ( dom ( C4 * C6 ) ) by FINSEQ_3:120;
L20: ( dom ( C4 * C6 ) ) = ( dom C6 ) by FINSEQ_3:120;
L21: ( dom ( C5 * ( C4 * C6 ) ) ) = ( Seg ( len C6 ) ) by L20 , L19 , FINSEQ_1:def 3;
L22: ( len C6 ) = ( len ( (( C5 * C4 ) qua (Function of (the carrier of R1) , (the carrier of R3))) * (C6 qua (FinSequence of (the carrier of R1))) ) ) by FINSEQ_3:120;
L23: ( dom ( ( C5 * C4 ) * C6 ) ) = ( Seg ( len C6 ) ) by L22 , FINSEQ_1:def 3;
L24:
now
let C7 being Nat;
assume L25: C7 in ( dom ( C5 * ( C4 * C6 ) ) );
thus L26: ( ( C5 * ( C4 * C6 ) ) . C7 ) = ( C5 . ( ( C4 * C6 ) . C7 ) ) by L25 , FINSEQ_3:120
.= ( C5 . ( C4 . ( C6 . C7 ) ) ) by L19 , L25 , FINSEQ_3:120
.= ( ( C5 * C4 ) . ( C6 . C7 ) ) by L18 , L21 , L25 , FINSEQ_2:11 , FUNCT_2:15
.= ( ( ( C5 * C4 ) * C6 ) . C7 ) by L21 , L23 , L25 , FINSEQ_3:120;
end;
L27: (( len ( C5 * ( C4 * C6 ) ) ) = ( len ( C4 * C6 ) ) & ( len ( C4 * C6 ) ) = ( len C6 )) by FINSEQ_3:120;
thus L28: thesis by L27 , L22 , L24 , FINSEQ_2:9;
end;
definition
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
pred R12 is_homomorphism R1 , R2
means
:L29: (R1 , R2 are_similar  & (for R4 being (Element of ( NAT )) holds (R4 in ( dom (the charact of R1) ) implies (for R6 being (operation of R1) holds (for R7 being (operation of R2) holds ((R6 = ( (the charact of R1) . R4 ) & R7 = ( (the charact of R2) . R4 )) implies (for B5 being (FinSequence of R1) holds (B5 in ( dom R6 ) implies ( R12 . ( R6 . B5 ) ) = ( R7 . ( R12 * B5 ) )))))))))
;end;
definition
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
pred R12 is_monomorphism R1 , R2
means
:L31: (R12 is_homomorphism R1 , R2 & R12 is  one-to-one)
;pred R12 is_epimorphism R1 , R2
means
:L32: (R12 is_homomorphism R1 , R2 & ( rng R12 ) = (the carrier of R2))
;end;
definition
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
pred R12 is_isomorphism R1 , R2
means
:L34: (R12 is_monomorphism R1 , R2 & R12 is_epimorphism R1 , R2)
;end;
definition
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
pred R1 , R2 are_isomorphic 
means
:L36: (ex R12 being (Function of R1 , R2) st R12 is_isomorphism R1 , R2)
;end;
theorem
L38: (for R1 being Universal_Algebra holds ( id (the carrier of R1) ) is_homomorphism R1 , R1)
proof
let R1 being Universal_Algebra;
thus L39: R1 , R1 are_similar ;
let R4 being (Element of ( NAT ));
assume L40: R4 in ( dom (the charact of R1) );
let C8 , C9 being (operation of R1);
assume L41: (C8 = ( (the charact of R1) . R4 ) & C9 = ( (the charact of R1) . R4 ));
set D4 = ( id (the carrier of R1) );
let C10 being (FinSequence of R1);
assume L42: C10 in ( dom C8 );
L43: ( C8 . C10 ) in ( rng C8 ) by L42 , FUNCT_1:def 3;
reconsider D5 = ( C8 . C10 ) as (Element of R1) by L43;
L44: ( D4 . D5 ) = D5 by FUNCT_1:18;
thus L45: thesis by L44 , L41 , L9;
end;
theorem
L46: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R3 being Universal_Algebra holds (for B6 being (Function of R1 , R2) holds (for B7 being (Function of R2 , R3) holds ((B6 is_homomorphism R1 , R2 & B7 is_homomorphism R2 , R3) implies ( B7 * B6 ) is_homomorphism R1 , R3))))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R3 being Universal_Algebra;
let C11 being (Function of R1 , R2);
let C12 being (Function of R2 , R3);
set D6 = ( signature R1 );
set D7 = ( signature R2 );
set D8 = ( signature R3 );
assume that
L47: C11 is_homomorphism R1 , R2
and
L48: C12 is_homomorphism R2 , R3;
L49: R1 , R2 are_similar  by L47 , L29;
L50: D6 = D7 by L49 , UNIALG_2:def 1;
L51: R2 , R3 are_similar  by L48 , L29;
thus L52: D6 = D8 by L51 , L50 , UNIALG_2:def 1;
let R4 being (Element of ( NAT ));
assume L53: R4 in ( dom (the charact of R1) );
let R6 being (operation of R1);
let R8 being (operation of R3);
assume that
L54: R6 = ( (the charact of R1) . R4 )
and
L55: R8 = ( (the charact of R3) . R4 );
let R11 being (FinSequence of R1);
reconsider D9 = ( C11 * R11 ) as (Element of ( (the carrier of R2) * )) by FINSEQ_1:def 11;
assume L56: R11 in ( dom R6 );
L57: ( R6 . R11 ) in ( rng R6 ) by L56 , FUNCT_1:def 3;
L58: ( dom R6 ) = ( ( arity R6 ) -tuples_on (the carrier of R1) ) by MARGREL1:22;
L59: R11 in { B8 where B8 is (Element of ( (the carrier of R1) * )) : ( len B8 ) = ( arity R6 ) } by L58 , L56 , FINSEQ_2:def 4;
L60: (ex B9 being (Element of ( (the carrier of R1) * )) st (B9 = R11 & ( len B9 ) = ( arity R6 ))) by L59;
L61: (( len D6 ) = ( len (the charact of R1) ) & ( dom (the charact of R1) ) = ( Seg ( len (the charact of R1) ) )) by FINSEQ_1:def 3 , UNIALG_1:def 4;
L62: (( len D7 ) = ( len (the charact of R2) ) & ( dom (the charact of R2) ) = ( Seg ( len (the charact of R2) ) )) by FINSEQ_1:def 3 , UNIALG_1:def 4;
reconsider D10 = ( (the charact of R2) . R4 ) as (operation of R2) by L62 , L50 , L61 , L53 , FUNCT_1:def 3;
L63: ( dom D6 ) = ( Seg ( len D6 ) ) by FINSEQ_1:def 3;
L64: ( D7 . R4 ) = ( arity D10 ) by L63 , L50 , L61 , L53 , UNIALG_1:def 4;
L65: ( D6 . R4 ) = ( arity R6 ) by L61 , L63 , L53 , L54 , UNIALG_1:def 4;
L66: ( len ( C11 * R11 ) ) = ( arity D10 ) by L65 , L50 , L64 , L60 , FINSEQ_3:120;
L67: (( dom D10 ) = ( ( arity D10 ) -tuples_on (the carrier of R2) ) & D9 in { B10 where B10 is (Element of ( (the carrier of R2) * )) : ( len B10 ) = ( arity D10 ) }) by L66 , MARGREL1:22;
L68: ( C11 * R11 ) in ( dom D10 ) by L67 , FINSEQ_2:def 4;
L69: ( C12 . ( D10 . ( C11 * R11 ) ) ) = ( R8 . ( C12 * ( C11 * R11 ) ) ) by L68 , L48 , L50 , L61 , L62 , L53 , L55 , L29;
L70: ( C11 . ( R6 . R11 ) ) = ( D10 . ( C11 * R11 ) ) by L47 , L53 , L54 , L56 , L29;
thus L71: ( ( C12 * C11 ) . ( R6 . R11 ) ) = ( R8 . ( C12 * ( C11 * R11 ) ) ) by L70 , L57 , L69 , FUNCT_2:15
.= ( R8 . ( ( C12 * C11 ) * R11 ) ) by L17;
end;
theorem
L72: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R12 being (Function of R1 , R2) holds (R12 is_isomorphism R1 , R2 iff (R12 is_homomorphism R1 , R2 & ( rng R12 ) = (the carrier of R2) & R12 is  one-to-one)))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
thus L73: (R12 is_isomorphism R1 , R2 implies (R12 is_homomorphism R1 , R2 & ( rng R12 ) = (the carrier of R2) & R12 is  one-to-one))
proof
assume L74: R12 is_isomorphism R1 , R2;
L75: (R12 is_monomorphism R1 , R2 & R12 is_epimorphism R1 , R2) by L74 , L34;
thus L76: thesis by L75 , L31 , L32;
end;

assume L77: (R12 is_homomorphism R1 , R2 & ( rng R12 ) = (the carrier of R2) & R12 is  one-to-one);
L78: (R12 is_monomorphism R1 , R2 & R12 is_epimorphism R1 , R2) by L77 , L31 , L32;
thus L79: thesis by L78 , L34;
end;
theorem
L80: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R12 being (Function of R1 , R2) holds (R12 is_isomorphism R1 , R2 implies (( dom R12 ) = (the carrier of R1) & ( rng R12 ) = (the carrier of R2))))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
assume L81: R12 is_isomorphism R1 , R2;
L82: R12 is_epimorphism R1 , R2 by L81 , L34;
thus L83: thesis by L82 , L32 , FUNCT_2:def 1;
end;
theorem
L84: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for B11 being (Function of R1 , R2) holds (for B12 being (Function of R2 , R1) holds ((B11 is_isomorphism R1 , R2 & B12 = ( B11 " )) implies B12 is_homomorphism R2 , R1)))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let C13 being (Function of R1 , R2);
let C14 being (Function of R2 , R1);
assume that
L85: C13 is_isomorphism R1 , R2
and
L86: C14 = ( C13 " );
L87: C13 is  one-to-one by L85 , L72;
L88: C13 is_homomorphism R1 , R2 by L85 , L72;
L89: R1 , R2 are_similar  by L88 , L29;
L90: ( signature R1 ) = ( signature R2 ) by L89 , UNIALG_2:def 1;
L91: (( len ( signature R1 ) ) = ( len (the charact of R1) ) & ( dom (the charact of R1) ) = ( Seg ( len (the charact of R1) ) )) by FINSEQ_1:def 3 , UNIALG_1:def 4;
L92: ( dom ( signature R2 ) ) = ( Seg ( len ( signature R2 ) ) ) by FINSEQ_1:def 3;
L93: (( len ( signature R2 ) ) = ( len (the charact of R2) ) & ( dom (the charact of R2) ) = ( Seg ( len (the charact of R2) ) )) by FINSEQ_1:def 3 , UNIALG_1:def 4;
L94: ( rng C13 ) = (the carrier of R2) by L85 , L72;
L95:
now
let R4 being (Element of ( NAT ));
assume L96: R4 in ( dom (the charact of R2) );
let R7 being (operation of R2);
let R6 being (operation of R1);
assume L97: (R7 = ( (the charact of R2) . R4 ) & R6 = ( (the charact of R1) . R4 ));
let C15 being (FinSequence of R2);
defpred S1[ set , set ] means ( C13 . $2 ) = ( C15 . $1 );
L98: ( dom C15 ) = ( Seg ( len C15 ) ) by FINSEQ_1:def 3;
L99: (for B13 being Nat holds (B13 in ( Seg ( len C15 ) ) implies (ex B14 being (Element of R1) st S1[ B13 , B14 ])))
proof
let C16 being Nat;
assume L100: C16 in ( Seg ( len C15 ) );
L101: C16 in ( dom C15 ) by L100 , FINSEQ_1:def 3;
L102: ( C15 . C16 ) in (the carrier of R2) by L101 , FINSEQ_2:11;
consider C17 being set such that L103: C17 in ( dom C13 ) and L104: ( C13 . C17 ) = ( C15 . C16 ) by L102 , L94 , FUNCT_1:def 3;
reconsider D11 = C17 as (Element of R1) by L103;
take D11;
thus L105: thesis by L104;
end;
consider C18 being (FinSequence of R1) such that L106: (( dom C18 ) = ( Seg ( len C15 ) ) & (for B15 being Nat holds (B15 in ( Seg ( len C15 ) ) implies S1[ B15 , ( C18 . B15 ) ]))) from FINSEQ_1:sch 5(L99);
L107: ( dom ( C13 * C18 ) ) = ( dom C18 ) by FINSEQ_3:120;
L108:
now
let C19 being Nat;
assume L109: C19 in ( dom C15 );
thus L110: ( C15 . C19 ) = ( C13 . ( C18 . C19 ) ) by L109 , L106 , L98
.= ( ( C13 * C18 ) . C19 ) by L106 , L98 , L107 , L109 , FINSEQ_3:120;
end;
L111: C15 = ( C13 * C18 ) by L108 , L106 , L98 , L107 , FINSEQ_1:13;
L112: ( len C18 ) = ( len C15 ) by L106 , FINSEQ_1:def 3;
assume L113: C15 in ( dom R7 );
L114: C15 in ( ( arity R7 ) -tuples_on (the carrier of R2) ) by L113 , MARGREL1:22;
L115: C15 in { B16 where B16 is (Element of ( (the carrier of R2) * )) : ( len B16 ) = ( arity R7 ) } by L114 , FINSEQ_2:def 4;
L116: (ex B17 being (Element of ( (the carrier of R2) * )) st (C15 = B17 & ( len B17 ) = ( arity R7 ))) by L115;
L117: ( C14 * C13 ) = ( id ( dom C13 ) ) by L86 , L87 , FUNCT_1:39
.= ( id (the carrier of R1) ) by FUNCT_2:def 1;
L118: ( C14 * C15 ) = ( ( id (the carrier of R1) ) * C18 ) by L117 , L111 , L17
.= C18 by L9;
reconsider D12 = C18 as (Element of ( (the carrier of R1) * )) by FINSEQ_1:def 11;
L119: (( ( signature R1 ) . R4 ) = ( arity R6 ) & ( ( signature R2 ) . R4 ) = ( arity R7 )) by L90 , L92 , L93 , L96 , L97 , UNIALG_1:def 4;
L120: D12 in { B18 where B18 is (Element of ( (the carrier of R1) * )) : ( len B18 ) = ( arity R6 ) } by L119 , L90 , L116 , L112;
L121: D12 in ( ( arity R6 ) -tuples_on (the carrier of R1) ) by L120 , FINSEQ_2:def 4;
L122: D12 in ( dom R6 ) by L121 , MARGREL1:22;
L123: ( C14 . ( R7 . C15 ) ) = ( C14 . ( C13 . ( R6 . D12 ) ) ) by L122 , L88 , L90 , L91 , L93 , L96 , L97 , L111 , L29;
L124: ( R6 . D12 ) in (the carrier of R1) by L122 , PARTFUN1:4;
L125: ( R6 . D12 ) in ( dom C13 ) by L124 , FUNCT_2:def 1;
thus L126: ( C14 . ( R7 . C15 ) ) = ( ( id (the carrier of R1) ) . ( R6 . D12 ) ) by L125 , L117 , L123 , FUNCT_1:13
.= ( R6 . ( C14 * C15 ) ) by L118 , L124 , FUNCT_1:17;
end;
thus L127: thesis by L95 , L89 , L29;
end;
theorem
L128: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for B19 being (Function of R1 , R2) holds (for B20 being (Function of R2 , R1) holds ((B19 is_isomorphism R1 , R2 & B20 = ( B19 " )) implies B20 is_isomorphism R2 , R1)))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let C20 being (Function of R1 , R2);
let C21 being (Function of R2 , R1);
assume that
L129: C20 is_isomorphism R1 , R2
and
L130: C21 = ( C20 " );
L131: C21 is_homomorphism R2 , R1 by L129 , L130 , L84;
L132: C20 is  one-to-one by L129 , L72;
L133: ( rng C21 ) = ( dom C20 ) by L132 , L130 , FUNCT_1:33
.= (the carrier of R1) by FUNCT_2:def 1;
thus L134: thesis by L133 , L130 , L132 , L131 , L72;
end;
theorem
L135: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R3 being Universal_Algebra holds (for B21 being (Function of R1 , R2) holds (for B22 being (Function of R2 , R3) holds ((B21 is_isomorphism R1 , R2 & B22 is_isomorphism R2 , R3) implies ( B22 * B21 ) is_isomorphism R1 , R3))))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R3 being Universal_Algebra;
let C22 being (Function of R1 , R2);
let C23 being (Function of R2 , R3);
assume that
L136: C22 is_isomorphism R1 , R2
and
L137: C23 is_isomorphism R2 , R3;
L138: (( dom C23 ) = (the carrier of R2) & ( rng C22 ) = (the carrier of R2)) by L136 , L80 , FUNCT_2:def 1;
L139: ( rng ( C23 * C22 ) ) = ( rng C23 ) by L138 , RELAT_1:28
.= (the carrier of R3) by L137 , L80;
L140: (C22 is_homomorphism R1 , R2 & C23 is_homomorphism R2 , R3) by L136 , L137 , L72;
L141: ( C23 * C22 ) is_homomorphism R1 , R3 by L140 , L46;
L142: (C22 is  one-to-one & C23 is  one-to-one) by L136 , L137 , L72;
thus L143: thesis by L142 , L139 , L141 , L72;
end;
theorem
L144: (for R1 being Universal_Algebra holds R1 , R1 are_isomorphic )
proof
let R1 being Universal_Algebra;
set D13 = ( id (the carrier of R1) );
L145: (D13 is_homomorphism R1 , R1 & ( rng D13 ) = (the carrier of R1)) by L38;
L146: D13 is_isomorphism R1 , R1 by L145 , L72;
thus L147: thesis by L146 , L36;
end;
theorem
L148: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (R1 , R2 are_isomorphic  implies R2 , R1 are_isomorphic )))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
assume L149: R1 , R2 are_isomorphic ;
consider R12 being (Function of R1 , R2) such that L150: R12 is_isomorphism R1 , R2 by L149 , L36;
L151: R12 is_monomorphism R1 , R2 by L150 , L34;
L152: R12 is  one-to-one by L151 , L31;
L153: ( rng ( R12 " ) ) = ( dom R12 ) by L152 , FUNCT_1:33
.= (the carrier of R1) by FUNCT_2:def 1;
L154: R12 is_epimorphism R1 , R2 by L150 , L34;
L155: ( dom ( R12 " ) ) = ( rng R12 ) by L152 , FUNCT_1:33
.= (the carrier of R2) by L154 , L32;
reconsider D14 = ( R12 " ) as (Function of R2 , R1) by L155 , L153 , FUNCT_2:def 1 , RELSET_1:4;
take D14;
thus L156: thesis by L150 , L128;
end;
theorem
L157: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R3 being Universal_Algebra holds ((R1 , R2 are_isomorphic  & R2 , R3 are_isomorphic ) implies R1 , R3 are_isomorphic ))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R3 being Universal_Algebra;
assume L158: R1 , R2 are_isomorphic ;
consider R12 being (Function of R1 , R2) such that L159: R12 is_isomorphism R1 , R2 by L158 , L36;
assume L160: R2 , R3 are_isomorphic ;
consider C24 being (Function of R2 , R3) such that L161: C24 is_isomorphism R2 , R3 by L160 , L36;
L162: ( C24 * R12 ) is_isomorphism R1 , R3 by L159 , L161 , L135;
thus L163: thesis by L162 , L36;
end;
definition
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
assume L164: R12 is_homomorphism R1 , R2;
func Image R12 ->  strict (SubAlgebra of R2) means 
:L165: (the carrier of it) = ( R12 .: (the carrier of R1) );
existence
proof
L166: ( dom R12 ) = (the carrier of R1) by FUNCT_2:def 1;
reconsider D15 = ( R12 .: (the carrier of R1) ) as non  empty (Subset of R2) by L166;
take D16 = ( UniAlgSetClosed D15 );
L167: D15 is  opers_closed
proof
let C25 being (operation of R2);
consider C26 being Nat such that L168: C26 in ( dom (the charact of R2) ) and L169: ( (the charact of R2) . C26 ) = C25 by FINSEQ_2:10;
let C27 being (FinSequence of D15);
assume L170: ( len C27 ) = ( arity C25 );
defpred S2[ set , set ] means ( R12 . $2 ) = ( C27 . $1 );
L171: (for R9 being set holds (R9 in ( dom C27 ) implies (ex R10 being set st (R10 in (the carrier of R1) & S2[ R9 , R10 ]))))
proof
let R9 being set;
assume L172: R9 in ( dom C27 );
reconsider D17 = R9 as (Element of ( NAT )) by L172;
L173: ( C27 . D17 ) in D15 by L172 , FINSEQ_2:11;
consider R10 being set such that L174: R10 in ( dom R12 ) and L175: R10 in (the carrier of R1) and L176: ( R12 . R10 ) = ( C27 . D17 ) by L173 , FUNCT_1:def 6;
take R10;
thus L177: thesis by L174 , L176;
end;
consider C28 being Function such that L178: (( dom C28 ) = ( dom C27 ) & ( rng C28 ) c= (the carrier of R1) & (for R9 being set holds (R9 in ( dom C27 ) implies S2[ R9 , ( C28 . R9 ) ]))) from FUNCT_1:sch 5(L171);
L179: ( dom C28 ) = ( Seg ( len C27 ) ) by L178 , FINSEQ_1:def 3;
reconsider D18 = C28 as FinSequence by L179 , FINSEQ_1:def 2;
reconsider D19 = D18 as (FinSequence of R1) by L178 , FINSEQ_1:def 4;
reconsider D20 = D19 as (Element of ( (the carrier of R1) * )) by FINSEQ_1:def 11;
L180: ( len D20 ) = ( len C27 ) by L178 , FINSEQ_3:29;
L181: ( dom ( signature R2 ) ) = ( Seg ( len ( signature R2 ) ) ) by FINSEQ_1:def 3;
L182: R1 , R2 are_similar  by L164 , L29;
L183: ( signature R1 ) = ( signature R2 ) by L182 , UNIALG_2:def 1;
L184: ( dom ( signature R1 ) ) = ( dom ( signature R2 ) ) by L182 , UNIALG_2:def 1;
L185: (( len ( signature R2 ) ) = ( len (the charact of R2) ) & ( dom (the charact of R2) ) = ( Seg ( len (the charact of R2) ) )) by FINSEQ_1:def 3 , UNIALG_1:def 4;
L186: ( ( signature R2 ) . C26 ) = ( arity C25 ) by L185 , L168 , L169 , L181 , UNIALG_1:def 4;
L187: ( len ( R12 * D20 ) ) = ( len D20 ) by FINSEQ_3:120;
L188: (( dom ( R12 * D20 ) ) = ( Seg ( len ( R12 * D20 ) ) ) & ( dom C27 ) = ( Seg ( len D20 ) )) by L178 , FINSEQ_1:def 3;
L189:
now
let C29 being Nat;
assume L190: C29 in ( dom C27 );
L191: ( R12 . ( D20 . C29 ) ) = ( C27 . C29 ) by L190 , L178;
thus L192: ( ( R12 * D20 ) . C29 ) = ( C27 . C29 ) by L191 , L187 , L188 , L190 , FINSEQ_3:120;
end;
L193: C27 = ( R12 * D20 ) by L189 , L180 , L187 , FINSEQ_2:9;
L194: ( dom ( signature R1 ) ) = ( Seg ( len ( signature R1 ) ) ) by FINSEQ_1:def 3;
L195: (( len ( signature R1 ) ) = ( len (the charact of R1) ) & ( dom (the charact of R1) ) = ( Seg ( len (the charact of R1) ) )) by FINSEQ_1:def 3 , UNIALG_1:def 4;
reconsider D21 = ( (the charact of R1) . C26 ) as (operation of R1) by L195 , L168 , L185 , L194 , L184 , L181 , FUNCT_1:def 3;
L196: ( ( signature R1 ) . C26 ) = ( arity D21 ) by L168 , L185 , L184 , L181 , UNIALG_1:def 4;
L197: D20 in { B23 where B23 is (Element of ( (the carrier of R1) * )) : ( len B23 ) = ( arity D21 ) } by L196 , L183 , L170 , L186 , L180;
L198: D20 in ( ( arity D21 ) -tuples_on (the carrier of R1) ) by L197 , FINSEQ_2:def 4;
L199: D20 in ( dom D21 ) by L198 , MARGREL1:22;
L200: ( D21 . D20 ) in ( rng D21 ) by L199 , FUNCT_1:def 3;
L201: ( R12 . ( D21 . D20 ) ) = ( C25 . ( R12 * D20 ) ) by L164 , L168 , L169 , L195 , L185 , L194 , L184 , L181 , L199 , L29;
thus L202: thesis by L201 , L166 , L193 , L200 , FUNCT_1:def 6;
end;
L203: D16 = UAStr (# D15 , ( Opers (R2 , D15) ) #) by L167 , UNIALG_2:def 8;
thus L204: thesis by L203;
end;
uniqueness
proof
let C30 , C31 being  strict (SubAlgebra of R2);
reconsider D22 = (the carrier of C30) as non  empty (Subset of R2) by UNIALG_2:def 7;
L205: (the charact of C30) = ( Opers (R2 , D22) ) by UNIALG_2:def 7;
thus L206: thesis by L205 , UNIALG_2:def 7;
end;
end;
theorem
L208: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for B24 being (Function of R1 , R2) holds (B24 is_homomorphism R1 , R2 implies ( rng B24 ) = (the carrier of ( Image B24 ))))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let C32 being (Function of R1 , R2);
L209: ( dom C32 ) = (the carrier of R1) by FUNCT_2:def 1;
L210: ( rng C32 ) = ( C32 .: (the carrier of R1) ) by L209 , RELAT_1:113;
assume L211: C32 is_homomorphism R1 , R2;
thus L212: thesis by L211 , L210 , L165;
end;
theorem
L213: (for R1 being Universal_Algebra holds (for B25 being  strict Universal_Algebra holds (for B26 being (Function of R1 , B25) holds (B26 is_homomorphism R1 , B25 implies (B26 is_epimorphism R1 , B25 iff ( Image B26 ) = B25)))))
proof
let R1 being Universal_Algebra;
let C33 being  strict Universal_Algebra;
let C34 being (Function of R1 , C33);
assume L214: C34 is_homomorphism R1 , C33;
thus L215: (C34 is_epimorphism R1 , C33 implies ( Image C34 ) = C33)
proof
reconsider D23 = (the carrier of ( Image C34 )) as non  empty (Subset of C33) by UNIALG_2:def 7;
assume L216: C34 is_epimorphism R1 , C33;
L217: (the carrier of C33) = ( rng C34 ) by L216 , L32
.= ( C34 .: ( dom C34 ) ) by RELAT_1:113
.= ( C34 .: (the carrier of R1) ) by FUNCT_2:def 1
.= (the carrier of ( Image C34 )) by L214 , L165;
L218: (the charact of ( Image C34 )) = ( Opers (C33 , D23) ) by UNIALG_2:def 7;
thus L219: thesis by L218 , L217 , L1;
end;

assume L220: ( Image C34 ) = C33;
L221: (the carrier of C33) = ( C34 .: (the carrier of R1) ) by L220 , L214 , L165
.= ( C34 .: ( dom C34 ) ) by FUNCT_2:def 1
.= ( rng C34 ) by RELAT_1:113;
thus L222: thesis by L221 , L214 , L32;
end;
begin
definition
let C35 being 1-sorted;
mode Relation of C35
 is (Relation of (the carrier of C35));
mode Equivalence_Relation of C35
 is (Equivalence_Relation of (the carrier of C35));
end;
definition
let R1 being Universal_Algebra;
mode Congruence of R1
 -> (Equivalence_Relation of R1)
means :L224: (for R4 being (Element of ( NAT )) holds (for R6 being (operation of R1) holds ((R4 in ( dom (the charact of R1) ) & R6 = ( (the charact of R1) . R4 )) implies (for B27 , B28 being (FinSequence of R1) holds ((B27 in ( dom R6 ) & B28 in ( dom R6 ) & [ B27 , B28 ] in ( ExtendRel it )) implies [ ( R6 . B27 ) , ( R6 . B28 ) ] in it)))));
existence
proof
reconsider D24 = ( id (the carrier of R1) ) as (Equivalence_Relation of R1);
take D24;
let R4 being (Element of ( NAT ));
let R6 being (operation of R1);
assume that
L225: R4 in ( dom (the charact of R1) )
and
L226: R6 = ( (the charact of R1) . R4 );
let C36 , C37 being (FinSequence of R1);
assume that
L227: C36 in ( dom R6 )
and
L228: C37 in ( dom R6 )
and
L229: [ C36 , C37 ] in ( ExtendRel D24 );
L230: [ C36 , C37 ] in ( id ( (the carrier of R1) * ) ) by L229 , FINSEQ_3:121;
L231: C36 = C37 by L230 , RELAT_1:def 10;
L232: ( R6 . C36 ) in ( rng R6 ) by L227 , FUNCT_1:def 3;
thus L233: thesis by L232 , L231 , RELAT_1:def 10;
end;
end;
definition
let C38 being Universal_Algebra;
let C39 being (Congruence of C38);
let C40 being (operation of C38);
func QuotOp (C40 , C39) ->  homogeneous  quasi_total non  empty (PartFunc of ( ( Class C39 ) * ) , ( Class C39 )) means 
:L235: (( dom it ) = ( ( arity C40 ) -tuples_on ( Class C39 ) ) & (for B29 being (FinSequence of ( Class C39 )) holds (B29 in ( dom it ) implies (for B30 being (FinSequence of (the carrier of C38)) holds (B30 is_representatives_FS B29 implies ( it . B29 ) = ( Class (C39 , ( C40 . B30 )) ))))));
existence
proof
defpred S3[ set , set ] means (for B31 being (FinSequence of ( Class C39 )) holds (B31 = $1 implies (for B32 being (FinSequence of (the carrier of C38)) holds (B32 is_representatives_FS B31 implies $2 = ( Class (C39 , ( C40 . B32 )) )))));
set D25 = ( ( arity C40 ) -tuples_on ( Class C39 ) );
L236: (for B33 being set holds (B33 in D25 implies (ex B34 being set st (B34 in ( Class C39 ) & S3[ B33 , B34 ]))))
proof
let C41 being set;
L237: ( dom C40 ) = ( ( arity C40 ) -tuples_on (the carrier of C38) ) by MARGREL1:22
.= { B35 where B35 is (Element of ( (the carrier of C38) * )) : ( len B35 ) = ( arity C40 ) } by FINSEQ_2:def 4;
assume L238: C41 in D25;
L239: C41 in { B36 where B36 is (Element of ( ( Class C39 ) * )) : ( len B36 ) = ( arity C40 ) } by L238 , FINSEQ_2:def 4;
consider C42 being (Element of ( ( Class C39 ) * )) such that L240: C42 = C41 and L241: ( len C42 ) = ( arity C40 ) by L239;
consider C43 being (FinSequence of (the carrier of C38)) such that L242: C43 is_representatives_FS C42 by FINSEQ_3:122;
take D26 = ( Class (C39 , ( C40 . C43 )) );
L243: ( len C43 ) = ( arity C40 ) by L241 , L242 , FINSEQ_3:def 4;
L244: C43 is (Element of ( (the carrier of C38) * )) by FINSEQ_1:def 11;
L245: C43 in ( dom C40 ) by L244 , L237 , L243;
L246: ( C40 . C43 ) in ( rng C40 ) by L245 , FUNCT_1:def 3;
thus L247: D26 in ( Class C39 ) by L246 , EQREL_1:def 3;
let C44 being (FinSequence of ( Class C39 ));
assume L248: C44 = C41;
let C45 being (FinSequence of (the carrier of C38));
assume L249: C45 is_representatives_FS C44;
L250: ( len C45 ) = ( arity C40 ) by L249 , L240 , L241 , L248 , FINSEQ_3:def 4;
L251: (for R5 being (Element of ( NAT )) holds (R5 in ( dom C43 ) implies [ ( C43 . R5 ) , ( C45 . R5 ) ] in C39))
proof
let R5 being (Element of ( NAT ));
assume L252: R5 in ( dom C43 );
L253: (( Class (C39 , ( C43 . R5 )) ) = ( C42 . R5 ) & ( C43 . R5 ) in ( rng C43 )) by L252 , L242 , FINSEQ_3:def 4 , FUNCT_1:def 3;
L254: ( dom C43 ) = ( Seg ( arity C40 ) ) by L243 , FINSEQ_1:def 3
.= ( dom C45 ) by L250 , FINSEQ_1:def 3;
L255: ( Class (C39 , ( C45 . R5 )) ) = ( C42 . R5 ) by L254 , L240 , L248 , L249 , L252 , FINSEQ_3:def 4;
thus L256: thesis by L255 , L253 , EQREL_1:35;
end;
L257: [ C43 , C45 ] in ( ExtendRel C39 ) by L251 , L243 , L250 , FINSEQ_3:def 3;
L258: C45 is (Element of ( (the carrier of C38) * )) by FINSEQ_1:def 11;
L259: ((ex B37 being Nat st (B37 in ( dom (the charact of C38) ) & ( (the charact of C38) . B37 ) = C40)) & C45 in ( dom C40 )) by L258 , L237 , L250 , FINSEQ_2:10;
L260: [ ( C40 . C43 ) , ( C40 . C45 ) ] in C39 by L259 , L245 , L257 , L224;
thus L261: thesis by L260 , L246 , EQREL_1:35;
end;
consider C46 being Function such that L262: (( dom C46 ) = D25 & ( rng C46 ) c= ( Class C39 ) & (for B38 being set holds (B38 in D25 implies S3[ B38 , ( C46 . B38 ) ]))) from FUNCT_1:sch 5(L236);
L263: D25 in { ( R5 -tuples_on ( Class C39 ) ) where R5 is (Element of ( NAT )) : (not contradiction) };
L264: D25 c= ( union { ( R5 -tuples_on ( Class C39 ) ) where R5 is (Element of ( NAT )) : (not contradiction) } ) by L263 , ZFMISC_1:74;
L265: D25 c= ( ( Class C39 ) * ) by L264 , FINSEQ_2:108;
reconsider D27 = C46 as (PartFunc of ( ( Class C39 ) * ) , ( Class C39 )) by L265 , L262 , RELSET_1:4;
L266: ( dom D27 ) = { B39 where B39 is (Element of ( ( Class C39 ) * )) : ( len B39 ) = ( arity C40 ) } by L262 , FINSEQ_2:def 4;
L267: (for B40 , B41 being (FinSequence of ( Class C39 )) holds ((( len B40 ) = ( len B41 ) & B40 in ( dom D27 )) implies B41 in ( dom D27 )))
proof
let C47 , C48 being (FinSequence of ( Class C39 ));
assume that
L268: ( len C47 ) = ( len C48 )
and
L269: C47 in ( dom D27 );
L270: C48 is (Element of ( ( Class C39 ) * )) by FINSEQ_1:def 11;
L271: (ex B42 being (Element of ( ( Class C39 ) * )) st (C47 = B42 & ( len B42 ) = ( arity C40 ))) by L266 , L269;
thus L272: thesis by L271 , L266 , L268 , L270;
end;
L273: (ex B43 being FinSequence st B43 in ( dom D27 ))
proof
set D28 = the (Element of D25);
L274: D28 in D25;
thus L275: (ex B44 being FinSequence st B44 in ( dom D27 )) by L274 , L262;
end;
L276: ( dom D27 ) is  with_common_domain
proof
let C49 , C50 being FinSequence;
assume L277: (C49 in ( dom D27 ) & C50 in ( dom D27 ));
L278: ((ex B45 being (Element of ( ( Class C39 ) * )) st (C49 = B45 & ( len B45 ) = ( arity C40 ))) & (ex B46 being (Element of ( ( Class C39 ) * )) st (C50 = B46 & ( len B46 ) = ( arity C40 )))) by L277 , L266;
thus L279: thesis by L278;
end;
reconsider D29 = D27 as  homogeneous  quasi_total non  empty (PartFunc of ( ( Class C39 ) * ) , ( Class C39 )) by L276 , L267 , L273 , MARGREL1:def 21 , MARGREL1:def 22;
take D29;
thus L280: ( dom D29 ) = ( ( arity C40 ) -tuples_on ( Class C39 ) ) by L262;
let C51 being (FinSequence of ( Class C39 ));
assume L281: C51 in ( dom D29 );
let C52 being (FinSequence of (the carrier of C38));
assume L282: C52 is_representatives_FS C51;
thus L283: thesis by L282 , L262 , L281;
end;
uniqueness
proof
let C53 , C54 being  homogeneous  quasi_total non  empty (PartFunc of ( ( Class C39 ) * ) , ( Class C39 ));
assume that
L284: ( dom C53 ) = ( ( arity C40 ) -tuples_on ( Class C39 ) )
and
L285: (for B47 being (FinSequence of ( Class C39 )) holds (B47 in ( dom C53 ) implies (for B48 being (FinSequence of (the carrier of C38)) holds (B48 is_representatives_FS B47 implies ( C53 . B47 ) = ( Class (C39 , ( C40 . B48 )) )))))
and
L286: ( dom C54 ) = ( ( arity C40 ) -tuples_on ( Class C39 ) )
and
L287: (for B49 being (FinSequence of ( Class C39 )) holds (B49 in ( dom C54 ) implies (for B50 being (FinSequence of (the carrier of C38)) holds (B50 is_representatives_FS B49 implies ( C54 . B49 ) = ( Class (C39 , ( C40 . B50 )) )))));
L288: (for B51 being set holds (B51 in ( dom C53 ) implies ( C53 . B51 ) = ( C54 . B51 )))
proof
let C55 being set;
assume L289: C55 in ( dom C53 );
reconsider D30 = C55 as (FinSequence of ( Class C39 )) by L289 , FINSEQ_1:def 11;
consider C56 being (FinSequence of (the carrier of C38)) such that L290: C56 is_representatives_FS D30 by FINSEQ_3:122;
L291: ( C53 . D30 ) = ( Class (C39 , ( C40 . C56 )) ) by L285 , L289 , L290;
thus L292: thesis by L291 , L284 , L286 , L287 , L289 , L290;
end;
thus L293: thesis by L288 , L284 , L286 , FUNCT_1:2;
end;
end;
definition
let R1 being Universal_Algebra;
let R13 being (Congruence of R1);
func QuotOpSeq (R1 , R13) -> (PFuncFinSequence of ( Class R13 )) means 
:L295: (( len it ) = ( len (the charact of R1) ) & (for R4 being (Element of ( NAT )) holds (R4 in ( dom it ) implies (for R6 being (operation of R1) holds (( (the charact of R1) . R4 ) = R6 implies ( it . R4 ) = ( QuotOp (R6 , R13) ))))));
existence
proof
defpred S4[ set , set ] means (for B52 being (Element of ( Operations R1 )) holds (B52 = ( (the charact of R1) . $1 ) implies $2 = ( QuotOp (B52 , R13) )));
L296: (for B53 being Nat holds (B53 in ( Seg ( len (the charact of R1) ) ) implies (ex B54 being (Element of ( PFuncs (( ( Class R13 ) * ) , ( Class R13 )) )) st S4[ B53 , B54 ])))
proof
let C57 being Nat;
assume L297: C57 in ( Seg ( len (the charact of R1) ) );
L298: C57 in ( dom (the charact of R1) ) by L297 , FINSEQ_1:def 3;
reconsider D31 = ( (the charact of R1) . C57 ) as (operation of R1) by L298 , FUNCT_1:def 3;
reconsider D32 = ( QuotOp (D31 , R13) ) as (Element of ( PFuncs (( ( Class R13 ) * ) , ( Class R13 )) )) by PARTFUN1:45;
take D32;
thus L299: thesis;
end;
consider C58 being (FinSequence of ( PFuncs (( ( Class R13 ) * ) , ( Class R13 )) )) such that L300: (( dom C58 ) = ( Seg ( len (the charact of R1) ) ) & (for B55 being Nat holds (B55 in ( Seg ( len (the charact of R1) ) ) implies S4[ B55 , ( C58 . B55 ) ]))) from FINSEQ_1:sch 5(L296);
reconsider D33 = C58 as (PFuncFinSequence of ( Class R13 ));
take D33;
thus L301: ( len D33 ) = ( len (the charact of R1) ) by L300 , FINSEQ_1:def 3;
let R4 being (Element of ( NAT ));
assume L302: R4 in ( dom D33 );
thus L303: thesis by L302 , L300;
end;
uniqueness
proof
let C59 , C60 being (PFuncFinSequence of ( Class R13 ));
assume that
L304: ( len C59 ) = ( len (the charact of R1) )
and
L305: (for R4 being (Element of ( NAT )) holds (R4 in ( dom C59 ) implies (for R6 being (operation of R1) holds (( (the charact of R1) . R4 ) = R6 implies ( C59 . R4 ) = ( QuotOp (R6 , R13) )))))
and
L306: ( len C60 ) = ( len (the charact of R1) )
and
L307: (for R4 being (Element of ( NAT )) holds (R4 in ( dom C60 ) implies (for R6 being (operation of R1) holds (( (the charact of R1) . R4 ) = R6 implies ( C60 . R4 ) = ( QuotOp (R6 , R13) )))));
L308:
now
let C61 being Nat;
assume L309: C61 in ( dom C59 );
L310: ( dom C59 ) = ( Seg ( len (the charact of R1) ) ) by L304 , FINSEQ_1:def 3;
L311: C61 in ( dom (the charact of R1) ) by L310 , L309 , FINSEQ_1:def 3;
reconsider D34 = ( (the charact of R1) . C61 ) as (operation of R1) by L311 , FUNCT_1:def 3;
L312: (( dom C59 ) = ( dom (the charact of R1) ) & ( dom C60 ) = ( dom (the charact of R1) )) by L304 , L306 , FINSEQ_3:29;
L313: ( C59 . C61 ) = ( QuotOp (D34 , R13) ) by L305 , L309;
thus L314: ( C59 . C61 ) = ( C60 . C61 ) by L313 , L307 , L312 , L309;
end;
thus L315: thesis by L308 , L304 , L306 , FINSEQ_2:9;
end;
end;
definition
let R1 being Universal_Algebra;
let R13 being (Congruence of R1);
func QuotUnivAlg (R1 , R13) ->  strict Universal_Algebra equals 
UAStr (# ( Class R13 ) , ( QuotOpSeq (R1 , R13) ) #);
coherence
proof
set D35 = UAStr (# ( Class R13 ) , ( QuotOpSeq (R1 , R13) ) #);
L317: (for B56 being Nat holds (for B57 being (PartFunc of ( ( Class R13 ) * ) , ( Class R13 )) holds ((B56 in ( dom ( QuotOpSeq (R1 , R13) ) ) & B57 = ( ( QuotOpSeq (R1 , R13) ) . B56 )) implies B57 is  homogeneous)))
proof
let C62 being Nat;
let C63 being (PartFunc of ( ( Class R13 ) * ) , ( Class R13 ));
assume that
L318: C62 in ( dom ( QuotOpSeq (R1 , R13) ) )
and
L319: C63 = ( ( QuotOpSeq (R1 , R13) ) . C62 );
L320: C62 in ( Seg ( len ( QuotOpSeq (R1 , R13) ) ) ) by L318 , FINSEQ_1:def 3;
L321: C62 in ( Seg ( len (the charact of R1) ) ) by L320 , L295;
L322: C62 in ( dom (the charact of R1) ) by L321 , FINSEQ_1:def 3;
reconsider D36 = ( (the charact of R1) . C62 ) as (operation of R1) by L322 , FUNCT_1:def 3;
L323: ( ( QuotOpSeq (R1 , R13) ) . C62 ) = ( QuotOp (D36 , R13) ) by L318 , L295;
thus L324: thesis by L323 , L319;
end;
L325: (the charact of D35) is  homogeneous by L317 , MARGREL1:def 23;
L326: (for B58 being Nat holds (for B59 being (PartFunc of ( ( Class R13 ) * ) , ( Class R13 )) holds ((B58 in ( dom ( QuotOpSeq (R1 , R13) ) ) & B59 = ( ( QuotOpSeq (R1 , R13) ) . B58 )) implies B59 is  quasi_total)))
proof
let C64 being Nat;
let C65 being (PartFunc of ( ( Class R13 ) * ) , ( Class R13 ));
assume that
L327: C64 in ( dom ( QuotOpSeq (R1 , R13) ) )
and
L328: C65 = ( ( QuotOpSeq (R1 , R13) ) . C64 );
L329: C64 in ( Seg ( len ( QuotOpSeq (R1 , R13) ) ) ) by L327 , FINSEQ_1:def 3;
L330: C64 in ( Seg ( len (the charact of R1) ) ) by L329 , L295;
L331: C64 in ( dom (the charact of R1) ) by L330 , FINSEQ_1:def 3;
reconsider D37 = ( (the charact of R1) . C64 ) as (operation of R1) by L331 , FUNCT_1:def 3;
L332: ( ( QuotOpSeq (R1 , R13) ) . C64 ) = ( QuotOp (D37 , R13) ) by L327 , L295;
thus L333: thesis by L332 , L328;
end;
L334: (the charact of D35) is  quasi_total by L326 , MARGREL1:def 24;
L335: (for B60 being set holds (B60 in ( dom ( QuotOpSeq (R1 , R13) ) ) implies ( ( QuotOpSeq (R1 , R13) ) . B60 ) is non  empty))
proof
let C66 being set;
assume L336: C66 in ( dom ( QuotOpSeq (R1 , R13) ) );
L337: C66 in ( Seg ( len ( QuotOpSeq (R1 , R13) ) ) ) by L336 , FINSEQ_1:def 3;
L338: C66 in ( Seg ( len (the charact of R1) ) ) by L337 , L295;
L339: C66 in ( dom (the charact of R1) ) by L338 , FINSEQ_1:def 3;
reconsider D38 = C66 as (Element of ( NAT )) by L336;
reconsider D39 = ( (the charact of R1) . D38 ) as (operation of R1) by L339 , FUNCT_1:def 3;
L340: ( ( QuotOpSeq (R1 , R13) ) . D38 ) = ( QuotOp (D39 , R13) ) by L336 , L295;
thus L341: thesis by L340;
end;
L342: (the charact of D35) is  non-empty by L335 , FUNCT_1:def 9;
L343: (the charact of D35) <> ( {} )
proof
assume L344: (the charact of D35) = ( {} );
L345: ( len (the charact of D35) ) = ( len (the charact of R1) ) by L295;
thus L346: contradiction by L345 , L344;
end;
thus L347: thesis by L343 , L325 , L334 , L342 , UNIALG_1:def 1 , UNIALG_1:def 2 , UNIALG_1:def 3;
end;
end;
definition
let R1 being Universal_Algebra;
let R13 being (Congruence of R1);
func Nat_Hom (R1 , R13) -> (Function of R1 , ( QuotUnivAlg (R1 , R13) )) means 
:L349: (for B61 being (Element of R1) holds ( it . B61 ) = ( Class (R13 , B61) ));
existence
proof
defpred S5[ (Element of R1) , set ] means $2 = ( Class (R13 , $1) );
L350: (for B62 being (Element of R1) holds (ex B63 being (Element of ( QuotUnivAlg (R1 , R13) )) st S5[ B62 , B63 ]))
proof
let C67 being (Element of R1);
reconsider D40 = ( Class (R13 , C67) ) as (Element of ( QuotUnivAlg (R1 , R13) )) by EQREL_1:def 3;
take D40;
thus L351: thesis;
end;
consider C68 being (Function of R1 , ( QuotUnivAlg (R1 , R13) )) such that L352: (for B64 being (Element of R1) holds S5[ B64 , ( C68 . B64 ) ]) from FUNCT_2:sch 3(L350);
take C68;
thus L353: thesis by L352;
end;
uniqueness
proof
let C69 , C70 being (Function of R1 , ( QuotUnivAlg (R1 , R13) ));
assume that
L354: (for B65 being (Element of R1) holds ( C69 . B65 ) = ( Class (R13 , B65) ))
and
L355: (for B66 being (Element of R1) holds ( C70 . B66 ) = ( Class (R13 , B66) ));
L356:
now
let C71 being (Element of R1);
L357: ( C69 . C71 ) = ( Class (R13 , C71) ) by L354;
thus L358: ( C69 . C71 ) = ( C70 . C71 ) by L357 , L355;
end;
thus L359: thesis by L356 , FUNCT_2:63;
end;
end;
theorem
L361: (for R1 being Universal_Algebra holds (for R13 being (Congruence of R1) holds ( Nat_Hom (R1 , R13) ) is_homomorphism R1 , ( QuotUnivAlg (R1 , R13) )))
proof
let R1 being Universal_Algebra;
let R13 being (Congruence of R1);
set D41 = ( Nat_Hom (R1 , R13) );
set D42 = (the carrier of R1);
set D43 = (the carrier of ( QuotUnivAlg (R1 , R13) ));
L362: ( len ( signature R1 ) ) = ( len (the charact of R1) ) by UNIALG_1:def 4;
L363: ( dom ( signature R1 ) ) = ( Seg ( len ( signature R1 ) ) ) by FINSEQ_1:def 3;
L364: ( len ( QuotOpSeq (R1 , R13) ) ) = ( len (the charact of R1) ) by L295;
L365: ( len ( signature ( QuotUnivAlg (R1 , R13) ) ) ) = ( len (the charact of ( QuotUnivAlg (R1 , R13) )) ) by UNIALG_1:def 4;
L366:
now
let C72 being Nat;
assume L367: C72 in ( dom ( signature R1 ) );
L368: C72 in ( dom (the charact of R1) ) by L367 , L362 , L363 , FINSEQ_1:def 3;
reconsider D44 = ( (the charact of R1) . C72 ) as (operation of R1) by L368 , FUNCT_1:def 3;
L369: C72 in ( dom ( QuotOpSeq (R1 , R13) ) ) by L364 , L362 , L363 , L367 , FINSEQ_1:def 3;
L370: ( ( QuotOpSeq (R1 , R13) ) . C72 ) = ( QuotOp (D44 , R13) ) by L369 , L295;
reconsider D45 = ( QuotOp (D44 , R13) ) as  homogeneous  quasi_total non  empty (PartFunc of ( D43 * ) , D43);
consider C73 being set such that L371: C73 in ( dom D45 ) by XBOOLE_0:def 1;
reconsider D46 = C73 as (Element of ( D43 * )) by L371;
L372: ( dom ( QuotOp (D44 , R13) ) ) = ( ( arity D44 ) -tuples_on ( Class R13 ) ) by L235;
L373: D46 in { B67 where B67 is (Element of ( ( Class R13 ) * )) : ( len B67 ) = ( arity D44 ) } by L372 , L371 , FINSEQ_2:def 4;
L374: (ex B68 being (Element of ( ( Class R13 ) * )) st (B68 = D46 & ( len B68 ) = ( arity D44 ))) by L373;
L375: ( arity D45 ) = ( arity D44 ) by L374 , L371 , MARGREL1:def 25;
L376: (C72 in ( dom ( signature ( QuotUnivAlg (R1 , R13) ) ) ) & ( ( signature R1 ) . C72 ) = ( arity D44 )) by L364 , L365 , L363 , L367 , FINSEQ_1:def 3 , UNIALG_1:def 4;
thus L377: ( ( signature R1 ) . C72 ) = ( ( signature ( QuotUnivAlg (R1 , R13) ) ) . C72 ) by L376 , L370 , L375 , UNIALG_1:def 4;
end;
thus L378: ( signature R1 ) = ( signature ( QuotUnivAlg (R1 , R13) ) ) by L366 , L364 , L365 , L362 , FINSEQ_2:9;
let R4 being (Element of ( NAT ));
assume L379: R4 in ( dom (the charact of R1) );
L380: R4 in ( Seg ( len (the charact of R1) ) ) by L379 , FINSEQ_1:def 3;
L381: R4 in ( dom ( QuotOpSeq (R1 , R13) ) ) by L380 , L364 , FINSEQ_1:def 3;
let C74 being (operation of R1);
let C75 being (operation of ( QuotUnivAlg (R1 , R13) ));
assume L382: (( (the charact of R1) . R4 ) = C74 & C75 = ( (the charact of ( QuotUnivAlg (R1 , R13) )) . R4 ));
L383: C75 = ( QuotOp (C74 , R13) ) by L382 , L381 , L295;
let C76 being (FinSequence of R1);
reconsider D47 = C76 as (Element of ( D42 * )) by FINSEQ_1:def 11;
reconsider D48 = ( D41 * C76 ) as (FinSequence of ( Class R13 ));
reconsider D49 = D48 as (Element of ( ( Class R13 ) * )) by FINSEQ_1:def 11;
L384: ( len ( D41 * C76 ) ) = ( len C76 ) by FINSEQ_3:120;
L385:
now
let R5 being (Element of ( NAT ));
assume L386: R5 in ( dom C76 );
L387: R5 in ( dom ( D41 * C76 ) ) by L386 , FINSEQ_3:120;
L388: ( C76 . R5 ) in ( rng C76 ) by L386 , FUNCT_1:def 3;
reconsider D50 = ( C76 . R5 ) as (Element of D42) by L388;
thus L389: ( Class (R13 , ( C76 . R5 )) ) = ( D41 . D50 ) by L349
.= ( D49 . R5 ) by L387 , FINSEQ_3:120;
end;
L390: C76 is_representatives_FS D49 by L385 , L384 , FINSEQ_3:def 4;
assume L391: C76 in ( dom C74 );
L392: ( C74 . C76 ) in ( rng C74 ) by L391 , FUNCT_1:def 3;
reconsider D51 = ( C74 . C76 ) as (Element of D42) by L392;
L393: ( dom C74 ) = ( ( arity C74 ) -tuples_on D42 ) by MARGREL1:22
.= { B69 where B69 is (Element of ( D42 * )) : ( len B69 ) = ( arity C74 ) } by FINSEQ_2:def 4;
L394: (ex B70 being (Element of ( D42 * )) st (B70 = D47 & ( len B70 ) = ( arity C74 ))) by L393 , L391;
L395: ( D41 . ( C74 . C76 ) ) = ( Class (R13 , D51) ) by L349
.= ( Class (R13 , ( C74 . C76 )) );
L396: ( dom ( QuotOp (C74 , R13) ) ) = ( ( arity C74 ) -tuples_on ( Class R13 ) ) by L235
.= { B71 where B71 is (Element of ( ( Class R13 ) * )) : ( len B71 ) = ( arity C74 ) } by FINSEQ_2:def 4;
L397: D49 in ( dom ( QuotOp (C74 , R13) ) ) by L396 , L394 , L384;
thus L398: thesis by L397 , L395 , L383 , L390 , L235;
end;
theorem
L399: (for R1 being Universal_Algebra holds (for R13 being (Congruence of R1) holds ( Nat_Hom (R1 , R13) ) is_epimorphism R1 , ( QuotUnivAlg (R1 , R13) )))
proof
let R1 being Universal_Algebra;
let R13 being (Congruence of R1);
set D52 = ( Nat_Hom (R1 , R13) );
set D53 = ( QuotUnivAlg (R1 , R13) );
set D54 = (the carrier of D53);
set D55 = (the carrier of R1);
thus L400: D52 is_homomorphism R1 , D53 by L361;
thus L401: ( rng D52 ) c= D54;
let R9 being set;
assume L402: R9 in D54;
reconsider D56 = R9 as (Subset of D55) by L402;
consider R10 being set such that L403: R10 in D55 and L404: D56 = ( Class (R13 , R10) ) by L402 , EQREL_1:def 3;
reconsider D57 = R10 as (Element of D55) by L403;
L405: ( dom D52 ) = D55 by FUNCT_2:def 1;
L406: ( D52 . D57 ) in ( rng D52 ) by L405 , FUNCT_1:def 3;
thus L407: thesis by L406 , L404 , L349;
end;
definition
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let C77 being (Function of R1 , R2);
assume L408: C77 is_homomorphism R1 , R2;
func Cng C77 -> (Congruence of R1) means 
:L409: (for B72 , B73 being (Element of R1) holds ([ B72 , B73 ] in it iff ( C77 . B72 ) = ( C77 . B73 )));
existence
proof
defpred S6[ set , set ] means ( C77 . $1 ) = ( C77 . $2 );
set D58 = (the carrier of R1);
consider C78 being (Relation of D58 , D58) such that L410: (for B74 , B75 being (Element of D58) holds ([ B74 , B75 ] in C78 iff S6[ B74 , B75 ])) from RELSET_1:sch 2;
L411: C78 is_reflexive_in D58
proof
let R9 being set;
assume L412: R9 in D58;
reconsider D59 = R9 as (Element of D58) by L412;
L413: ( C77 . D59 ) = ( C77 . D59 );
thus L414: thesis by L413 , L410;
end;
L415: (( dom C78 ) = D58 & ( field C78 ) = D58) by L411 , ORDERS_1:13;
L416: C78 is_transitive_in D58
proof
let C79 , C80 , C81 being set;
assume that
L417: (C79 in D58 & C80 in D58 & C81 in D58)
and
L418: ([ C79 , C80 ] in C78 & [ C80 , C81 ] in C78);
reconsider D60 = C79 , D61 = C80 , D62 = C81 as (Element of D58) by L417;
L419: (( C77 . D60 ) = ( C77 . D61 ) & ( C77 . D61 ) = ( C77 . D62 )) by L410 , L418;
thus L420: thesis by L419 , L410;
end;
L421: C78 is_symmetric_in D58
proof
let R9 being set;
let R10 being set;
assume that
L422: (R9 in D58 & R10 in D58)
and
L423: [ R9 , R10 ] in C78;
reconsider D63 = R9 , D64 = R10 as (Element of D58) by L422;
L424: ( C77 . D63 ) = ( C77 . D64 ) by L410 , L423;
thus L425: thesis by L424 , L410;
end;
reconsider D65 = C78 as (Equivalence_Relation of R1) by L421 , L415 , L416 , PARTFUN1:def 2 , RELAT_2:def 11 , RELAT_2:def 16;
L426:
now
L427: R1 , R2 are_similar  by L408 , L29;
L428: ( signature R1 ) = ( signature R2 ) by L427 , UNIALG_2:def 1;
let C82 being (Element of ( NAT ));
let C83 being (operation of R1);
assume that
L429: C82 in ( dom (the charact of R1) )
and
L430: C83 = ( (the charact of R1) . C82 );
L431: (( len ( signature R1 ) ) = ( len (the charact of R1) ) & ( len ( signature R2 ) ) = ( len (the charact of R2) )) by UNIALG_1:def 4;
L432: ( dom (the charact of R2) ) = ( dom (the charact of R1) ) by L431 , L428 , FINSEQ_3:29;
reconsider D66 = ( (the charact of R2) . C82 ) as (operation of R2) by L432 , L429 , FUNCT_1:def 3;
let C84 , C85 being (FinSequence of R1);
assume that
L433: (C84 in ( dom C83 ) & C85 in ( dom C83 ))
and
L434: [ C84 , C85 ] in ( ExtendRel D65 );
L435: (( C83 . C84 ) in ( rng C83 ) & ( C83 . C85 ) in ( rng C83 )) by L433 , FUNCT_1:def 3;
reconsider D67 = ( C83 . C84 ) , D68 = ( C83 . C85 ) as (Element of D58) by L435;
L436: ( len C84 ) = ( len C85 ) by L434 , FINSEQ_3:def 3;
L437: ( len ( C77 * C85 ) ) = ( len C85 ) by FINSEQ_3:120;
L438: ( dom ( C77 * C85 ) ) = ( Seg ( len C84 ) ) by L437 , L436 , FINSEQ_1:def 3;
L439: ( len ( C77 * C84 ) ) = ( len C84 ) by FINSEQ_3:120;
L440:
now
let C86 being Nat;
assume L441: C86 in ( dom ( C77 * C85 ) );
L442: C86 in ( dom C85 ) by L441 , L436 , L438 , FINSEQ_1:def 3;
L443: ( C85 . C86 ) in ( rng C85 ) by L442 , FUNCT_1:def 3;
L444: C86 in ( dom C84 ) by L438 , L441 , FINSEQ_1:def 3;
L445: ( C84 . C86 ) in ( rng C84 ) by L444 , FUNCT_1:def 3;
reconsider D69 = ( C84 . C86 ) , D70 = ( C85 . C86 ) as (Element of D58) by L445 , L443;
L446: [ ( C84 . C86 ) , ( C85 . C86 ) ] in D65 by L434 , L444 , FINSEQ_3:def 3;
L447: ( C77 . D69 ) = ( C77 . D70 ) by L446 , L410
.= ( ( C77 * C85 ) . C86 ) by L441 , FINSEQ_3:120;
L448: C86 in ( dom ( C77 * C84 ) ) by L439 , L438 , L441 , FINSEQ_1:def 3;
thus L449: ( ( C77 * C85 ) . C86 ) = ( ( C77 * C84 ) . C86 ) by L448 , L447 , FINSEQ_3:120;
end;
L450: (( C77 . ( C83 . C84 ) ) = ( D66 . ( C77 * C84 ) ) & ( C77 . ( C83 . C85 ) ) = ( D66 . ( C77 * C85 ) )) by L408 , L429 , L430 , L433 , L29;
L451: ( C77 . D67 ) = ( C77 . D68 ) by L450 , L436 , L439 , L437 , L440 , FINSEQ_2:9;
thus L452: [ ( C83 . C84 ) , ( C83 . C85 ) ] in D65 by L451 , L410;
end;
reconsider D71 = D65 as (Congruence of R1) by L426 , L224;
take D71;
let C87 , C88 being (Element of D58);
thus L453: ([ C87 , C88 ] in D71 implies ( C77 . C87 ) = ( C77 . C88 )) by L410;
assume L454: ( C77 . C87 ) = ( C77 . C88 );
thus L455: thesis by L454 , L410;
end;
uniqueness
proof
set D72 = (the carrier of R1);
let C89 , C90 being (Congruence of R1);
assume that
L456: (for B76 , B77 being (Element of R1) holds ([ B76 , B77 ] in C89 iff ( C77 . B76 ) = ( C77 . B77 )))
and
L457: (for B78 , B79 being (Element of R1) holds ([ B78 , B79 ] in C90 iff ( C77 . B78 ) = ( C77 . B79 )));
L458: (for B80 , B81 being set holds ([ B80 , B81 ] in C89 iff [ B80 , B81 ] in C90))
proof
let R9 being set;
let R10 being set;
thus L459: ([ R9 , R10 ] in C89 implies [ R9 , R10 ] in C90)
proof
assume L460: [ R9 , R10 ] in C89;
reconsider D73 = R9 , D74 = R10 as (Element of D72) by L460 , ZFMISC_1:87;
L461: ( C77 . D73 ) = ( C77 . D74 ) by L456 , L460;
thus L462: thesis by L461 , L457;
end;

assume L463: [ R9 , R10 ] in C90;
reconsider D75 = R9 , D76 = R10 as (Element of D72) by L463 , ZFMISC_1:87;
L464: ( C77 . D75 ) = ( C77 . D76 ) by L457 , L463;
thus L465: thesis by L464 , L456;
end;
thus L466: thesis by L458 , RELAT_1:def 2;
end;
end;
definition
let C91 , C92 being Universal_Algebra;
let C93 being (Function of C91 , C92);
assume L468: C93 is_homomorphism C91 , C92;
func HomQuot C93 -> (Function of ( QuotUnivAlg (C91 , ( Cng C93 )) ) , C92) means 
:L469: (for B82 being (Element of C91) holds ( it . ( Class (( Cng C93 ) , B82) ) ) = ( C93 . B82 ));
existence
proof
set D77 = ( QuotUnivAlg (C91 , ( Cng C93 )) );
set D78 = (the carrier of D77);
set D79 = (the carrier of C91);
set D80 = (the carrier of C92);
defpred S7[ set , set ] means (for B83 being (Element of D79) holds ($1 = ( Class (( Cng C93 ) , B83) ) implies $2 = ( C93 . B83 )));
L470: (for R9 being set holds (R9 in D78 implies (ex R10 being set st (R10 in D80 & S7[ R9 , R10 ]))))
proof
let R9 being set;
assume L471: R9 in D78;
reconsider D81 = R9 as (Subset of D79) by L471;
consider C94 being set such that L472: C94 in D79 and L473: D81 = ( Class (( Cng C93 ) , C94) ) by L471 , EQREL_1:def 3;
reconsider D82 = C94 as (Element of D79) by L472;
take D83 = ( C93 . D82 );
thus L474: D83 in D80;
let C95 being (Element of D79);
assume L475: R9 = ( Class (( Cng C93 ) , C95) );
L476: C95 in ( Class (( Cng C93 ) , D82) ) by L475 , L473 , EQREL_1:23;
L477: [ C95 , D82 ] in ( Cng C93 ) by L476 , EQREL_1:19;
thus L478: thesis by L477 , L468 , L409;
end;
consider C96 being Function such that L479: (( dom C96 ) = D78 & ( rng C96 ) c= D80 & (for R9 being set holds (R9 in D78 implies S7[ R9 , ( C96 . R9 ) ]))) from FUNCT_1:sch 5(L470);
reconsider D84 = C96 as (Function of D77 , C92) by L479 , FUNCT_2:def 1 , RELSET_1:4;
take D84;
let C97 being (Element of D79);
L480: ( Class (( Cng C93 ) , C97) ) in ( Class ( Cng C93 ) ) by EQREL_1:def 3;
thus L481: thesis by L480 , L479;
end;
uniqueness
proof
set D85 = ( QuotUnivAlg (C91 , ( Cng C93 )) );
set D86 = (the carrier of D85);
set D87 = (the carrier of C91);
let C98 , C99 being (Function of D85 , C92);
assume that
L482: (for B84 being (Element of D87) holds ( C98 . ( Class (( Cng C93 ) , B84) ) ) = ( C93 . B84 ))
and
L483: (for B85 being (Element of D87) holds ( C99 . ( Class (( Cng C93 ) , B85) ) ) = ( C93 . B85 ));
let C100 being (Element of D86);
L484: C100 in D86;
reconsider D88 = C100 as (Subset of D87) by L484;
consider C101 being set such that L485: (C101 in D87 & D88 = ( Class (( Cng C93 ) , C101) )) by EQREL_1:def 3;
thus L486: ( C98 . C100 ) = ( C93 . C101 ) by L482 , L485
.= ( C99 . C100 ) by L483 , L485;
end;
end;
theorem
L488: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R12 being (Function of R1 , R2) holds (R12 is_homomorphism R1 , R2 implies (( HomQuot R12 ) is_homomorphism ( QuotUnivAlg (R1 , ( Cng R12 )) ) , R2 & ( HomQuot R12 ) is_monomorphism ( QuotUnivAlg (R1 , ( Cng R12 )) ) , R2)))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
set D89 = ( QuotUnivAlg (R1 , ( Cng R12 )) );
set D90 = (the carrier of D89);
set D91 = (the carrier of R1);
set D92 = ( HomQuot R12 );
assume L489: R12 is_homomorphism R1 , R2;
thus L490: D92 is_homomorphism D89 , R2
proof
L491: ( Nat_Hom (R1 , ( Cng R12 )) ) is_homomorphism R1 , D89 by L361;
L492: R1 , D89 are_similar  by L491 , L29;
L493: ( signature R1 ) = ( signature D89 ) by L492 , UNIALG_2:def 1;
L494: R1 , R2 are_similar  by L489 , L29;
L495: ( signature R2 ) = ( signature D89 ) by L494 , L493 , UNIALG_2:def 1;
thus L496: D89 , R2 are_similar  by L495 , UNIALG_2:def 1;
let R4 being (Element of ( NAT ));
assume L497: R4 in ( dom (the charact of D89) );
L498: (( len ( signature R1 ) ) = ( len (the charact of R1) ) & ( len ( signature D89 ) ) = ( len (the charact of D89) )) by UNIALG_1:def 4;
L499: (( dom (the charact of D89) ) = ( Seg ( len (the charact of D89) ) ) & ( dom (the charact of R1) ) = ( Seg ( len (the charact of R1) ) )) by FINSEQ_1:def 3;
reconsider D93 = ( (the charact of R1) . R4 ) as (operation of R1) by L499 , L493 , L497 , L498 , FUNCT_1:def 3;
L500: ( dom D93 ) = ( ( arity D93 ) -tuples_on D91 ) by MARGREL1:22
.= { B86 where B86 is (Element of ( D91 * )) : ( len B86 ) = ( arity D93 ) } by FINSEQ_2:def 4;
let C102 being (operation of D89);
let C103 being (operation of R2);
assume that
L501: C102 = ( (the charact of D89) . R4 )
and
L502: C103 = ( (the charact of R2) . R4 );
let C104 being (FinSequence of D89);
assume L503: C104 in ( dom C102 );
reconsider D94 = C104 as (FinSequence of ( Class ( Cng R12 ) ));
reconsider D95 = D94 as (Element of ( ( Class ( Cng R12 ) ) * )) by FINSEQ_1:def 11;
consider C105 being (FinSequence of R1) such that L504: C105 is_representatives_FS D95 by FINSEQ_3:122;
reconsider D96 = C105 as (Element of ( D91 * )) by FINSEQ_1:def 11;
L505: ( len D95 ) = ( len D96 ) by L504 , FINSEQ_3:def 4;
L506: ( len ( D92 * C104 ) ) = ( len D96 ) by L505 , FINSEQ_3:120;
L507: ( len D96 ) = ( len ( R12 * D96 ) ) by FINSEQ_3:120;
L508:
now
let C106 being Nat;
assume L509: C106 in ( Seg ( len D96 ) );
L510: C106 in ( dom ( D92 * C104 ) ) by L509 , L506 , FINSEQ_1:def 3;
L511: C106 in ( dom ( R12 * D96 ) ) by L507 , L509 , FINSEQ_1:def 3;
L512: C106 in ( dom D96 ) by L509 , FINSEQ_1:def 3;
reconsider D97 = ( D96 . C106 ) as (Element of D91) by L512 , FINSEQ_2:11;
L513: ( D95 . C106 ) = ( Class (( Cng R12 ) , ( D96 . C106 )) ) by L504 , L512 , FINSEQ_3:def 4;
thus L514: ( ( D92 * C104 ) . C106 ) = ( D92 . ( Class (( Cng R12 ) , D97) ) ) by L513 , L510 , FINSEQ_3:120
.= ( R12 . ( D96 . C106 ) ) by L489 , L469
.= ( ( R12 * D96 ) . C106 ) by L511 , FINSEQ_3:120;
end;
L515: ( dom ( D92 * C104 ) ) = ( Seg ( len D96 ) ) by L506 , FINSEQ_1:def 3;
L516: ( C103 . ( D92 * C104 ) ) = ( C103 . ( R12 * D96 ) ) by L515 , L506 , L507 , L508 , FINSEQ_2:9;
L517: C102 = ( QuotOp (D93 , ( Cng R12 )) ) by L497 , L501 , L295;
L518: ( dom C102 ) = ( ( arity D93 ) -tuples_on ( Class ( Cng R12 ) ) ) by L517 , L235
.= { B87 where B87 is (Element of ( ( Class ( Cng R12 ) ) * )) : ( len B87 ) = ( arity D93 ) } by FINSEQ_2:def 4;
L519: (ex B88 being (Element of ( ( Class ( Cng R12 ) ) * )) st (B88 = D95 & ( len B88 ) = ( arity D93 ))) by L518 , L503;
L520: D96 in ( dom D93 ) by L519 , L505 , L500;
L521: ( D93 . D96 ) in ( rng D93 ) by L520 , FUNCT_1:def 3;
reconsider D98 = ( D93 . D96 ) as (Element of D91) by L521;
L522: ( D92 . ( C102 . C104 ) ) = ( D92 . ( Class (( Cng R12 ) , D98) ) ) by L503 , L504 , L517 , L235
.= ( R12 . ( D93 . D96 ) ) by L489 , L469;
thus L523: thesis by L522 , L489 , L493 , L497 , L502 , L499 , L498 , L520 , L516 , L29;
end;

L524: ( dom D92 ) = D90 by FUNCT_2:def 1;
L525: D92 is  one-to-one
proof
let R9 being set;
let R10 being set;
assume that
L526: R9 in ( dom D92 )
and
L527: R10 in ( dom D92 )
and
L528: ( D92 . R9 ) = ( D92 . R10 );
reconsider D99 = R9 , D100 = R10 as (Subset of D91) by L524 , L526 , L527;
consider C107 being set such that L529: C107 in D91 and L530: D99 = ( Class (( Cng R12 ) , C107) ) by L526 , EQREL_1:def 3;
reconsider D101 = C107 as (Element of D91) by L529;
consider C108 being set such that L531: C108 in D91 and L532: D100 = ( Class (( Cng R12 ) , C108) ) by L527 , EQREL_1:def 3;
reconsider D102 = C108 as (Element of D91) by L531;
L533: ( D92 . D100 ) = ( R12 . D102 ) by L489 , L532 , L469;
L534: ( D92 . D99 ) = ( R12 . D101 ) by L489 , L530 , L469;
L535: [ D101 , D102 ] in ( Cng R12 ) by L534 , L489 , L528 , L533 , L409;
thus L536: thesis by L535 , L530 , L532 , EQREL_1:35;
end;
thus L537: thesis by L525 , L490 , L31;
end;
::$N First isomorphism theorem for universal algebras
theorem
L538: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R12 being (Function of R1 , R2) holds (R12 is_epimorphism R1 , R2 implies ( HomQuot R12 ) is_isomorphism ( QuotUnivAlg (R1 , ( Cng R12 )) ) , R2))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
set D103 = ( QuotUnivAlg (R1 , ( Cng R12 )) );
set D104 = (the carrier of R1);
set D105 = (the carrier of R2);
set D106 = ( HomQuot R12 );
assume L539: R12 is_epimorphism R1 , R2;
L540: R12 is_homomorphism R1 , R2 by L539 , L32;
L541: D106 is_monomorphism D103 , R2 by L540 , L488;
L542: D106 is  one-to-one by L541 , L31;
L543: ( rng R12 ) = D105 by L539 , L32;
L544: ( rng D106 ) = D105
proof
thus L545: ( rng D106 ) c= D105;
let R9 being set;
assume L546: R9 in D105;
consider R10 being set such that L547: R10 in ( dom R12 ) and L548: ( R12 . R10 ) = R9 by L546 , L543 , FUNCT_1:def 3;
reconsider D107 = R10 as (Element of D104) by L547;
set D108 = ( Class (( Cng R12 ) , D107) );
L549: (( dom D106 ) = (the carrier of D103) & D108 in ( Class ( Cng R12 ) )) by EQREL_1:def 3 , FUNCT_2:def 1;
L550: ( D106 . D108 ) = R9 by L540 , L548 , L469;
thus L551: thesis by L550 , L549 , FUNCT_1:def 3;
end;
L552: D106 is_homomorphism D103 , R2 by L540 , L488;
thus L553: thesis by L552 , L542 , L544 , L72;
end;
theorem
L554: (for R1 being Universal_Algebra holds (for R2 being Universal_Algebra holds (for R12 being (Function of R1 , R2) holds (R12 is_epimorphism R1 , R2 implies ( QuotUnivAlg (R1 , ( Cng R12 )) ) , R2 are_isomorphic ))))
proof
let R1 being Universal_Algebra;
let R2 being Universal_Algebra;
let R12 being (Function of R1 , R2);
assume L555: R12 is_epimorphism R1 , R2;
take ( HomQuot R12 );
thus L556: thesis by L555 , L538;
end;
