:: Banach Algebra of Bounded Functionals
::  by Yasunari Shidama , Hikofumi Suzuki and Noboru Endou
::
:: Received March 3, 2008
:: Copyright (c) 2008-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, XBOOLE_0, ALGSTR_0, SUBSET_1, ARYTM_1, IDEAL_1, ARYTM_3,
      FUNCSDOM, STRUCT_0, TARSKI, REALSET1, MESFUNC1, SUPINF_2, BINOP_1,
      FUNCT_1, ZFMISC_1, RELAT_1, RLVECT_1, VECTSP_1, LATTICES, RSSPACE,
      GROUP_1, REAL_1, POLYALG1, CARD_1, XREAL_0, ORDINAL1, RSSPACE4, XXREAL_2,
      FUNCOP_1, FUNCT_2, VALUED_1, LOPBAN_1, COMPLEX1, XXREAL_0, SEQ_4,
      ORDINAL2, LOPBAN_2, PRE_TOPC, NORMSP_1, NAT_1, RSSPACE3, SEQ_2, SEQ_1,
      REWRITE1, C0SP1, METRIC_1, RELAT_2;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, ORDINAL1, NUMBERS, RELAT_1,
      XCMPLX_0, XREAL_0, COMPLEX1, XXREAL_0, XXREAL_2, STRUCT_0, ALGSTR_0,
      REAL_1, REALSET1, FUNCT_1, FUNCT_2, BINOP_1, DOMAIN_1, RELSET_1,
      PRE_TOPC, RLVECT_1, GROUP_1, VECTSP_1, FUNCSDOM, PARTFUN1, IDEAL_1,
      RSSPACE3, VALUED_1, SEQ_1, SEQ_2, SEQ_4, FUNCOP_1, NORMSP_0, NORMSP_1,
      LOPBAN_1, LOPBAN_2;
 constructors REAL_1, REALSET1, RSSPACE3, COMPLEX1, BINOP_2, LOPBAN_2, SEQ_1,
      SEQ_2, IDEAL_1, SEQ_4, RELSET_1, COMSEQ_2;
 registrations XBOOLE_0, SUBSET_1, STRUCT_0, XREAL_0, REALSET1, ALGSTR_0,
      NUMBERS, ORDINAL1, MEMBERED, FUNCSDOM, XXREAL_0, RLVECT_1, VECTSP_1,
      VECTSP_2, FUNCT_2, VALUED_0, VALUED_1, LOPBAN_2, FUNCOP_1, SEQ_4,
      RFUNCT_1, RELSET_1;
 requirements NUMERALS, BOOLE, SUBSET, REAL, ARITHM;
 definitions REALSET1, ALGSTR_0, TARSKI, XCMPLX_0, FUNCSDOM, RLVECT_1,
      VECTSP_1, STRUCT_0, GROUP_1, BINOP_1, VALUED_1, NORMSP_0, XXREAL_2;
 theorems SEQ_4, RFUNCT_1, FUNCT_1, SEQ_1, SEQ_2, ABSVALUE, ALGSTR_0, COMPLEX1,
      ZFMISC_1, TARSKI, RSSPACE3, RELAT_1, XREAL_0, XXREAL_0, FUNCSDOM,
      NORMSP_1, LOPBAN_1, FUNCT_2, XBOOLE_0, XREAL_1, XCMPLX_0, RLVECT_1,
      FUNCOP_1, VECTSP_1, GROUP_1, LOPBAN_2, VALUED_1, RSSPACE2, IDEAL_1,
      RELSET_1, NORMSP_0;
 schemes SEQ_1, FUNCT_2;

begin
definition
let C1 being non  empty addLoopStr;
let C2 being (Subset of C1);
attr C2 is  having-inverse
means
:L1: (for B1 being (Element of C1) holds (B1 in C2 implies ( - B1 ) in C2));
end;
definition
let C3 being non  empty addLoopStr;
let C4 being (Subset of C3);
attr C4 is  additively-closed
means
:L3: C4 is  add-closed  having-inverse;
end;
L5: (for B2 being non  empty addLoopStr holds ( [#] B2 ) is  add-closed)
proof
let C5 being non  empty addLoopStr;
L6: (for B3 , B4 being (Element of C5) holds ((B3 in ( [#] C5 ) & B4 in ( [#] C5 )) implies ( B3 + B4 ) in ( [#] C5 )));
thus L7: thesis by L6 , IDEAL_1:def 1;
end;
L8: (for B5 being non  empty addLoopStr holds ( [#] B5 ) is  having-inverse)
proof
let C6 being non  empty addLoopStr;
L9: (for B6 being (Element of C6) holds (B6 in ( [#] C6 ) implies ( - B6 ) in ( [#] C6 )));
thus L10: thesis by L9 , L1;
end;
registration
let C7 being non  empty addLoopStr;
cluster ( [#] C7 ) ->  add-closed  having-inverse;
correctness by L5 , L8;
end;
registration
let C8 being non  empty doubleLoopStr;
cluster  additively-closed ->  add-closed  having-inverse for (Subset of C8);
coherence by L3;
cluster  add-closed  having-inverse ->  additively-closed for (Subset of C8);
coherence by L3;
end;
registration
let C9 being non  empty addLoopStr;
cluster  add-closed  having-inverse non  empty for (Subset of C9);
correctness
proof
take ( [#] C9 );
thus L13: thesis;
end;
end;
definition
let C10 being Ring;
mode Subring of C10
 -> Ring
means :L15: ((the carrier of it) c= (the carrier of C10) & (the addF of it) = ( (the addF of C10) || (the carrier of it) ) & (the multF of it) = ( (the multF of C10) || (the carrier of it) ) & ( 1. it ) = ( 1. C10 ) & ( 0. it ) = ( 0. C10 ));
existence
proof
take C10;
thus L16: thesis by RELSET_1:19;
end;
end;
theorem
L18: (for R1 being non  empty set holds (for R3 being (Element of R1) holds (for R4 being (Element of R1) holds (for R5 being (BinOp of R1) holds (for R6 being (Function of [: R1 , R1 :] , R1) holds (for R7 being Ring holds (for R8 being (Subset of R7) holds ((R8 = R1 & R5 = ( (the addF of R7) || R8 ) & R6 = ( (the multF of R7) || R8 ) & R3 = ( 1. R7 ) & R4 = ( 0. R7 ) & R8 is  having-inverse) implies doubleLoopStr (# R1 , R5 , R6 , R3 , R4 #) is (Subring of R7)))))))))
proof
let R1 being non  empty set;
let R3 being (Element of R1);
let R4 being (Element of R1);
let R5 being (BinOp of R1);
let R6 being (Function of [: R1 , R1 :] , R1);
let R7 being Ring;
let R8 being (Subset of R7);
assume that
L19: R8 = R1
and
L20: R5 = ( (the addF of R7) || R8 )
and
L21: R6 = ( (the multF of R7) || R8 )
and
L22: R3 = ( 1. R7 )
and
L23: R4 = ( 0. R7 )
and
L24: (for B7 being (Element of R7) holds (B7 in R8 implies ( - B7 ) in R8));
reconsider D1 = doubleLoopStr (# R1 , R5 , R6 , R3 , R4 #) as non  empty doubleLoopStr;
L25:
now
let C11 , C12 being (Element of D1);
L26: ( C11 * C12 ) = ( (the multF of R7) . [ C11 , C12 ] ) by L19 , L21 , FUNCT_1:49;
thus L27: ( C11 * C12 ) = ( (the multF of R7) . (C11 , C12) ) by L26;
end;
L28:
now
let C13 , C14 being (Element of D1);
L29: ( C13 + C14 ) = ( (the addF of R7) . [ C13 , C14 ] ) by L19 , L20 , FUNCT_1:49;
thus L30: ( C13 + C14 ) = ( (the addF of R7) . (C13 , C14) ) by L29;
end;
L31: D1 is  Abelian  add-associative  right_zeroed  right_complementable  associative  well-unital  distributive
proof
set D2 = (the multF of R7);
set D3 = (the addF of R7);
thus L32:now
let C15 , C16 being (Element of D1);
reconsider D4 = C15 , D5 = C16 as (Element of R7) by L19 , TARSKI:def 3;
L33: (( C15 + C16 ) = ( D4 + D5 ) & ( C16 + C15 ) = ( D5 + D4 )) by L28;
thus L34: ( C15 + C16 ) = ( C16 + C15 ) by L33;
end;
thus L35:now
let C17 , C18 , C19 being (Element of D1);
reconsider D6 = C17 , D7 = C18 , D8 = C19 as (Element of R7) by L19 , TARSKI:def 3;
L36: ( C17 + ( C18 + C19 ) ) = ( D3 . (D6 , ( C18 + C19 )) ) by L28;
L37: ( C17 + ( C18 + C19 ) ) = ( D6 + ( D7 + D8 ) ) by L36 , L28;
L38: ( ( C17 + C18 ) + C19 ) = ( D3 . (( C17 + C18 ) , D8) ) by L28;
L39: ( ( C17 + C18 ) + C19 ) = ( ( D6 + D7 ) + D8 ) by L38 , L28;
thus L40: ( ( C17 + C18 ) + C19 ) = ( C17 + ( C18 + C19 ) ) by L39 , L37 , RLVECT_1:def 3;
end;
thus L41:now
let C20 being (Element of D1);
reconsider D9 = C20 as (Element of R7) by L19 , TARSKI:def 3;
L42: ( C20 + ( 0. D1 ) ) = ( D9 + ( 0. R7 ) ) by L23 , L28;
thus L43: ( C20 + ( 0. D1 ) ) = C20 by L42 , RLVECT_1:4;
end;
thus L44: D1 is  right_complementable
proof
let C21 being (Element of D1);
reconsider D10 = C21 as (Element of R7) by L19 , TARSKI:def 3;
consider C22 being (Element of R7) such that L45: ( D10 + C22 ) = ( 0. R7 ) by ALGSTR_0:def 11;
L46: C22 = ( - D10 ) by L45 , VECTSP_1:16;
reconsider D11 = C22 as (Element of D1) by L46 , L19 , L24;
take D11;
thus L47: thesis by L23 , L28 , L45;
end;

thus L48:now
let C23 , C24 , C25 being (Element of D1);
reconsider D12 = C25 , D13 = C23 , D14 = C24 as (Element of R7) by L19 , TARSKI:def 3;
L49: ( C23 * ( C24 * C25 ) ) = ( D2 . (C23 , ( C24 * C25 )) ) by L25;
L50: ( C23 * ( C24 * C25 ) ) = ( D13 * ( D14 * D12 ) ) by L49 , L25;
L51: ( C23 * C24 ) = ( D13 * D14 ) by L25;
L52: ( ( C23 * C24 ) * C25 ) = ( ( D13 * D14 ) * D12 ) by L51 , L25;
thus L53: ( ( C23 * C24 ) * C25 ) = ( C23 * ( C24 * C25 ) ) by L52 , L50 , GROUP_1:def 3;
end;
thus L54:now
let C26 being (Element of D1);
reconsider D15 = C26 as (Element of R7) by L19 , TARSKI:def 3;
L55: (( C26 * ( 1. D1 ) ) = ( D15 * ( 1. R7 ) ) & ( ( 1. D1 ) * C26 ) = ( ( 1. R7 ) * D15 )) by L22 , L25;
thus L56: (( C26 * ( 1. D1 ) ) = C26 & ( ( 1. D1 ) * C26 ) = C26) by L55 , VECTSP_1:def 6;
end;
thus L57:now
let C27 , C28 , C29 being (Element of D1);
reconsider D16 = C28 , D17 = C29 , D18 = C27 as (Element of R7) by L19 , TARSKI:def 3;
L58: ( ( C28 + C29 ) * C27 ) = ( D2 . (( C28 + C29 ) , C27) ) by L25;
L59: ( ( C28 + C29 ) * C27 ) = ( ( D16 + D17 ) * D18 ) by L58 , L28;
L60: ( ( C28 + C29 ) * C27 ) = ( ( D16 * D18 ) + ( D17 * D18 ) ) by L59 , VECTSP_1:def 7;
L61: ( ( C28 + C29 ) * C27 ) = ( D3 . (( D2 . (D16 , D18) ) , ( C29 * C27 )) ) by L60 , L25;
L62: ( ( C28 + C29 ) * C27 ) = ( D3 . (( C28 * C27 ) , ( C29 * C27 )) ) by L61 , L25;
L63: ( C27 * ( C28 + C29 ) ) = ( D2 . (C27 , ( C28 + C29 )) ) by L25;
L64: ( C27 * ( C28 + C29 ) ) = ( D18 * ( D16 + D17 ) ) by L63 , L28;
L65: ( C27 * ( C28 + C29 ) ) = ( ( D18 * D16 ) + ( D18 * D17 ) ) by L64 , VECTSP_1:def 7;
L66: ( C27 * ( C28 + C29 ) ) = ( D3 . (( D2 . (C27 , D16) ) , ( C27 * C29 )) ) by L65 , L25;
L67: ( C27 * ( C28 + C29 ) ) = ( D3 . (( C27 * C28 ) , ( C27 * C29 )) ) by L66 , L25;
thus L68: (( C27 * ( C28 + C29 ) ) = ( ( C27 * C28 ) + ( C27 * C29 ) ) & ( ( C28 + C29 ) * C27 ) = ( ( C28 * C27 ) + ( C29 * C27 ) )) by L67 , L28 , L62;
end;
end;
L58: (( 0. D1 ) = ( 0. R7 ) & ( 1. D1 ) = ( 1. R7 )) by L22 , L23;
thus L59: thesis by L58 , L19 , L20 , L21 , L31 , L15;
end;
registration
let C30 being Ring;
cluster  strict for (Subring of C30);
existence
proof
set D19 = ( [#] C30 );
L60: ((the addF of C30) = ( (the addF of C30) || D19 ) & (the multF of C30) = ( (the multF of C30) || D19 )) by RELSET_1:19;
L61: doubleLoopStr (# (the carrier of C30) , (the addF of C30) , (the multF of C30) , ( 1. C30 ) , ( 0. C30 ) #) is (Subring of C30) by L60 , L18;
thus L62: thesis by L61;
end;
end;
definition
let C31 being non  empty multLoopStr_0;
let C32 being (Subset of C31);
attr C32 is  multiplicatively-closed
means
:L64: (( 1. C31 ) in C32 & (for B8 , B9 being (Element of C31) holds ((B8 in C32 & B9 in C32) implies ( B8 * B9 ) in C32)));
end;
definition
let C33 being non  empty addLoopStr;
let C34 being (Subset of C33);
assume that
L66: C34 is  add-closed non  empty;
func Add_ (C34 , C33) -> (BinOp of C34) equals 
:L67: ( (the addF of C33) || C34 );
correctness
proof
L68: ( dom (the addF of C33) ) = [: (the carrier of C33) , (the carrier of C33) :] by FUNCT_2:def 1;
L69: (for B10 being set holds (B10 in [: C34 , C34 :] implies ( ( (the addF of C33) || C34 ) . B10 ) in C34))
proof
let C35 being set;
assume L70: C35 in [: C34 , C34 :];
consider C36 , C37 being set such that L71: (C36 in C34 & C37 in C34) and L72: C35 = [ C36 , C37 ] by L70 , ZFMISC_1:def 2;
reconsider D20 = C37 , D21 = C36 as (Element of C33) by L71;
L73: [ C36 , C37 ] in ( dom ( (the addF of C33) || C34 ) ) by L68 , L70 , L72 , RELAT_1:62 , ZFMISC_1:96;
L74: ( ( (the addF of C33) || C34 ) . C35 ) = ( D21 + D20 ) by L73 , L72 , FUNCT_1:47;
thus L75: thesis by L74 , L66 , L71 , IDEAL_1:def 1;
end;
L76: ( dom ( (the addF of C33) || C34 ) ) = [: C34 , C34 :] by L68 , RELAT_1:62 , ZFMISC_1:96;
thus L77: thesis by L76 , L69 , FUNCT_2:3;
end;
end;
definition
let C38 being non  empty multLoopStr_0;
let C39 being (Subset of C38);
assume that
L79: C39 is  multiplicatively-closed non  empty;
func mult_ (C39 , C38) -> (BinOp of C39) equals 
:L80: ( (the multF of C38) || C39 );
correctness
proof
L81: ( dom (the multF of C38) ) = [: (the carrier of C38) , (the carrier of C38) :] by FUNCT_2:def 1;
L82: (for B11 being set holds (B11 in [: C39 , C39 :] implies ( ( (the multF of C38) || C39 ) . B11 ) in C39))
proof
let C40 being set;
assume L83: C40 in [: C39 , C39 :];
consider C41 , C42 being set such that L84: (C41 in C39 & C42 in C39) and L85: C40 = [ C41 , C42 ] by L83 , ZFMISC_1:def 2;
reconsider D22 = C42 , D23 = C41 as (Element of C38) by L84;
L86: [ C41 , C42 ] in ( dom ( (the multF of C38) || C39 ) ) by L81 , L83 , L85 , RELAT_1:62 , ZFMISC_1:96;
L87: ( ( (the multF of C38) || C39 ) . C40 ) = ( D23 * D22 ) by L86 , L85 , FUNCT_1:47;
thus L88: thesis by L87 , L79 , L84 , L64;
end;
L89: ( dom ( (the multF of C38) || C39 ) ) = [: C39 , C39 :] by L81 , RELAT_1:62 , ZFMISC_1:96;
thus L90: thesis by L89 , L82 , FUNCT_2:3;
end;
end;
definition
let C43 being  add-associative  right_zeroed  right_complementable non  empty doubleLoopStr;
let C44 being (Subset of C43);
assume that
L92: C44 is  add-closed  having-inverse non  empty;
func Zero_ (C44 , C43) -> (Element of C44) equals 
:L93: ( 0. C43 );
correctness
proof
set D24 = the (Element of C44);
reconsider D25 = D24 as (Element of C43) by L92 , TARSKI:def 3;
L94: (( - D25 ) in C44 & ( D25 + ( - D25 ) ) = ( 0. C43 )) by L92 , L1 , RLVECT_1:def 10;
thus L95: thesis by L94 , L92 , IDEAL_1:def 1;
end;
end;
definition
let C45 being non  empty multLoopStr_0;
let C46 being (Subset of C45);
assume that
L97: C46 is  multiplicatively-closed non  empty;
func One_ (C46 , C45) -> (Element of C46) equals 
:L98: ( 1. C45 );
correctness by L97 , L64;
end;
theorem
L100: (for R7 being Ring holds (for R8 being (Subset of R7) holds (R8 is  additively-closed  multiplicatively-closed non  empty implies doubleLoopStr (# R8 , ( Add_ (R8 , R7) ) , ( mult_ (R8 , R7) ) , ( One_ (R8 , R7) ) , ( Zero_ (R8 , R7) ) #) is Ring)))
proof
let R7 being Ring;
let R8 being (Subset of R7);
assume L101: R8 is  additively-closed  multiplicatively-closed non  empty;
L102: (( One_ (R8 , R7) ) = ( 1_ R7 ) & ( mult_ (R8 , R7) ) = ( (the multF of R7) || R8 )) by L101 , L80 , L98;
L103: (( Zero_ (R8 , R7) ) = ( 0. R7 ) & ( Add_ (R8 , R7) ) = ( (the addF of R7) || R8 )) by L101 , L67 , L93;
thus L104: thesis by L103 , L101 , L102 , L18;
end;
begin
definition
let C47 being Algebra;
mode Subalgebra of C47
 -> Algebra
means :L105: ((the carrier of it) c= (the carrier of C47) & (the addF of it) = ( (the addF of C47) || (the carrier of it) ) & (the multF of it) = ( (the multF of C47) || (the carrier of it) ) & (the Mult of it) = ( (the Mult of C47) | [: ( REAL ) , (the carrier of it) :] ) & ( 1. it ) = ( 1. C47 ) & ( 0. it ) = ( 0. C47 ));
existence
proof
take C47;
thus L106: ((the carrier of C47) c= (the carrier of C47) & (the addF of C47) = ( (the addF of C47) || (the carrier of C47) ) & (the multF of C47) = ( (the multF of C47) || (the carrier of C47) ) & (the Mult of C47) = ( (the Mult of C47) | [: ( REAL ) , (the carrier of C47) :] ) & ( 1. C47 ) = ( 1. C47 ) & ( 0. C47 ) = ( 0. C47 )) by RELSET_1:19;
end;
end;
theorem
L108: (for R1 being non  empty set holds (for R3 being (Element of R1) holds (for R4 being (Element of R1) holds (for R5 being (BinOp of R1) holds (for R6 being (Function of [: R1 , R1 :] , R1) holds (for R9 being Algebra holds (for R10 being (Subset of R9) holds (for R11 being (Function of [: ( REAL ) , R1 :] , R1) holds ((R10 = R1 & R3 = ( 0. R9 ) & R4 = ( 1. R9 ) & R5 = ( (the addF of R9) || R10 ) & R6 = ( (the multF of R9) || R10 ) & R11 = ( (the Mult of R9) | [: ( REAL ) , R10 :] ) & R10 is  having-inverse) implies AlgebraStr (# R1 , R6 , R5 , R11 , R4 , R3 #) is (Subalgebra of R9))))))))))
proof
let R1 being non  empty set;
let R3 being (Element of R1);
let R4 being (Element of R1);
let R5 being (BinOp of R1);
let R6 being (Function of [: R1 , R1 :] , R1);
let R9 being Algebra;
let R10 being (Subset of R9);
let R11 being (Function of [: ( REAL ) , R1 :] , R1);
assume that
L109: R10 = R1
and
L110: R3 = ( 0. R9 )
and
L111: R4 = ( 1. R9 )
and
L112: R5 = ( (the addF of R9) || R10 )
and
L113: R6 = ( (the multF of R9) || R10 )
and
L114: R11 = ( (the Mult of R9) | [: ( REAL ) , R10 :] )
and
L115: (for B12 being (Element of R9) holds (B12 in R10 implies ( - B12 ) in R10));
reconsider D26 = AlgebraStr (# R1 , R6 , R5 , R11 , R4 , R3 #) as non  empty AlgebraStr;
L116:
now
let C48 , C49 being (Element of D26);
L117: ( C48 + C49 ) = ( (the addF of R9) . [ C48 , C49 ] ) by L109 , L112 , FUNCT_1:49;
thus L118: ( C48 + C49 ) = ( (the addF of R9) . (C48 , C49) ) by L117;
end;
L119:
now
let C50 , C51 being (VECTOR of D26);
L120: ( C50 * C51 ) = ( (the multF of R9) . [ C50 , C51 ] ) by L109 , L113 , FUNCT_1:49;
thus L121: ( C50 * C51 ) = ( (the multF of R9) . (C50 , C51) ) by L120;
end;
L122:
now
let R12 being Real;
let C52 being (VECTOR of D26);
L123: ( R12 * C52 ) = ( (the Mult of R9) . [ R12 , C52 ] ) by L109 , L114 , FUNCT_1:49;
thus L124: ( R12 * C52 ) = ( (the Mult of R9) . (R12 , C52) ) by L123;
end;
L125: D26 is  Abelian  add-associative  right_zeroed  right_complementable  commutative  associative  right_unital  right-distributive  vector-distributive  scalar-distributive  scalar-associative  vector-associative
proof
set D27 = (the multF of R9);
set D28 = (the addF of R9);
thus L126:now
let C53 , C54 being (VECTOR of D26);
reconsider D29 = C53 , D30 = C54 as (VECTOR of R9) by L109 , TARSKI:def 3;
L127: (( C53 + C54 ) = ( D29 + D30 ) & ( C54 + C53 ) = ( D30 + D29 )) by L116;
thus L128: ( C53 + C54 ) = ( C54 + C53 ) by L127;
end;
thus L129:now
let C55 , C56 , C57 being (VECTOR of D26);
reconsider D31 = C55 , D32 = C56 , D33 = C57 as (VECTOR of R9) by L109 , TARSKI:def 3;
L130: ( C55 + ( C56 + C57 ) ) = ( D28 . (D31 , ( C56 + C57 )) ) by L116;
L131: ( C55 + ( C56 + C57 ) ) = ( D31 + ( D32 + D33 ) ) by L130 , L116;
L132: ( ( C55 + C56 ) + C57 ) = ( D28 . (( C55 + C56 ) , D33) ) by L116;
L133: ( ( C55 + C56 ) + C57 ) = ( ( D31 + D32 ) + D33 ) by L132 , L116;
thus L134: ( ( C55 + C56 ) + C57 ) = ( C55 + ( C56 + C57 ) ) by L133 , L131 , RLVECT_1:def 3;
end;
thus L135:now
let C58 being (VECTOR of D26);
reconsider D34 = C58 as (VECTOR of R9) by L109 , TARSKI:def 3;
thus L136: ( C58 + ( 0. D26 ) ) = ( D34 + ( 0. R9 ) ) by L110 , L116
.= C58 by RLVECT_1:4;
end;
thus L137: D26 is  right_complementable
proof
let C59 being (Element of D26);
reconsider D35 = C59 as (Element of R9) by L109 , TARSKI:def 3;
consider C60 being (Element of R9) such that L138: ( D35 + C60 ) = ( 0. R9 ) by ALGSTR_0:def 11;
L139: C60 = ( - D35 ) by L138 , VECTSP_1:16;
reconsider D36 = C60 as (Element of D26) by L139 , L109 , L115;
take D36;
thus L140: thesis by L110 , L116 , L138;
end;

thus L141:now
let C61 , C62 being (Element of D26);
reconsider D37 = C61 , D38 = C62 as (Element of R9) by L109 , TARSKI:def 3;
L142: (( C61 * C62 ) = ( D37 * D38 ) & ( C62 * C61 ) = ( D38 * D37 )) by L119;
thus L143: ( C61 * C62 ) = ( C62 * C61 ) by L142;
end;
thus L144:now
let C63 , C64 , C65 being (Element of D26);
reconsider D39 = C65 , D40 = C63 , D41 = C64 as (Element of R9) by L109 , TARSKI:def 3;
L145: ( C63 * ( C64 * C65 ) ) = ( D27 . (C63 , ( C64 * C65 )) ) by L119;
L146: ( C63 * ( C64 * C65 ) ) = ( D40 * ( D41 * D39 ) ) by L145 , L119;
L147: ( C63 * C64 ) = ( D40 * D41 ) by L119;
L148: ( ( C63 * C64 ) * C65 ) = ( ( D40 * D41 ) * D39 ) by L147 , L119;
thus L149: ( ( C63 * C64 ) * C65 ) = ( C63 * ( C64 * C65 ) ) by L148 , L146 , GROUP_1:def 3;
end;
thus L150:now
let C66 being (Element of D26);
reconsider D42 = C66 as (Element of R9) by L109 , TARSKI:def 3;
L151: ( C66 * ( 1. D26 ) ) = ( D42 * ( 1. R9 ) ) by L111 , L119;
thus L152: ( C66 * ( 1. D26 ) ) = C66 by L151 , VECTSP_1:def 4;
end;
thus L153:now
let C67 , C68 , C69 being (Element of D26);
reconsider D43 = C67 , D44 = C68 , D45 = C69 as (Element of R9) by L109 , TARSKI:def 3;
L154: ( C68 + C69 ) = ( D44 + D45 ) by L116;
L155: ( C67 * ( C68 + C69 ) ) = ( D43 * ( D44 + D45 ) ) by L154 , L119;
L156: ( C67 * ( C68 + C69 ) ) = ( ( D43 * D44 ) + ( D43 * D45 ) ) by L155 , VECTSP_1:def 2;
L157: (( C67 * C68 ) = ( D43 * D44 ) & ( C67 * C69 ) = ( D43 * D45 )) by L119;
thus L158: ( C67 * ( C68 + C69 ) ) = ( ( C67 * C68 ) + ( C67 * C69 ) ) by L157 , L116 , L156;
end;
thus L159: D26 is  vector-distributive
proof
let C70 being  real number;
let C71 , C72 being (Element of D26);
reconsider D46 = C71 , D47 = C72 as (Element of R9) by L109 , TARSKI:def 3;
reconsider D48 = C70 as Real by XREAL_0:def 1;
L160: ( D48 * C71 ) = ( D48 * D46 ) by L122;
L161: ( C71 + C72 ) = ( D46 + D47 ) by L116;
L162: ( D48 * ( C71 + C72 ) ) = ( D48 * ( D46 + D47 ) ) by L161 , L122;
L163: ( C70 * ( C71 + C72 ) ) = ( ( C70 * D46 ) + ( C70 * D47 ) ) by L162 , RLVECT_1:def 5;
L164: ( D48 * C72 ) = ( D48 * D47 ) by L122;
thus L165: ( C70 * ( C71 + C72 ) ) = ( ( C70 * C71 ) + ( C70 * C72 ) ) by L164 , L116 , L160 , L163;
end;

thus L166: D26 is  scalar-distributive
proof
let C73 , C74 being  real number;
reconsider D49 = C73 , D50 = C74 as Real by XREAL_0:def 1;
let C75 being (Element of D26);
reconsider D51 = C75 as (Element of R9) by L109 , TARSKI:def 3;
L167: ( D49 * C75 ) = ( D49 * D51 ) by L122;
L168: ( D50 * C75 ) = ( D50 * D51 ) by L122;
L169: ( ( D49 + D50 ) * C75 ) = ( ( C73 + C74 ) * D51 ) by L122;
L170: ( ( C73 + C74 ) * C75 ) = ( ( C73 * D51 ) + ( C74 * D51 ) ) by L169 , RLVECT_1:def 6;
thus L171: ( ( C73 + C74 ) * C75 ) = ( ( C73 * C75 ) + ( C74 * C75 ) ) by L170 , L116 , L167 , L168;
end;

thus L172: D26 is  scalar-associative
proof
let C76 , C77 being  real number;
let C78 being (Element of D26);
reconsider D52 = C78 as (Element of R9) by L109 , TARSKI:def 3;
reconsider D53 = C76 , D54 = C77 as Real by XREAL_0:def 1;
L173: ( D54 * C78 ) = ( D54 * D52 ) by L122;
L174: ( ( D53 * D54 ) * C78 ) = ( ( C76 * C77 ) * D52 ) by L122;
L175: ( ( D53 * D54 ) * C78 ) = ( C76 * ( D54 * D52 ) ) by L174 , RLVECT_1:def 7;
thus L176: ( ( C76 * C77 ) * C78 ) = ( C76 * ( C77 * C78 ) ) by L175 , L122 , L173;
end;

thus L177: D26 is  vector-associative
proof
let C79 , C80 being (Element of D26);
reconsider D55 = C79 , D56 = C80 as (Element of R9) by L109 , TARSKI:def 3;
let C81 being Real;
L178: ( C81 * C79 ) = ( C81 * D55 ) by L122;
L179: ( C79 * C80 ) = ( D55 * D56 ) by L119;
L180: ( C81 * ( C79 * C80 ) ) = ( C81 * ( D55 * D56 ) ) by L179 , L122;
L181: ( C81 * ( C79 * C80 ) ) = ( ( C81 * D55 ) * D56 ) by L180 , FUNCSDOM:def 9;
thus L182: ( C81 * ( C79 * C80 ) ) = ( ( C81 * C79 ) * C80 ) by L181 , L119 , L178;
end;

end;
L178: (( 0. D26 ) = ( 0. R9 ) & ( 1. D26 ) = ( 1. R9 )) by L110 , L111;
thus L179: thesis by L178 , L109 , L112 , L113 , L114 , L125 , L105;
end;
registration
let C82 being Algebra;
cluster  strict for (Subalgebra of C82);
existence
proof
set D57 = ( [#] C82 );
L180: (the Mult of C82) = ( (the Mult of C82) | [: ( REAL ) , D57 :] ) by RELSET_1:19;
L181: ((the addF of C82) = ( (the addF of C82) || D57 ) & (the multF of C82) = ( (the multF of C82) || D57 )) by RELSET_1:19;
L182: AlgebraStr (# (the carrier of C82) , (the multF of C82) , (the addF of C82) , (the Mult of C82) , ( 1. C82 ) , ( 0. C82 ) #) is (Subalgebra of C82) by L181 , L180 , L108;
thus L183: thesis by L182;
end;
end;
definition
let C83 being Algebra;
let C84 being (Subset of C83);
attr C84 is  additively-linearly-closed
means
:L185: (C84 is  add-closed  having-inverse & (for B13 being Real holds (for B14 being (Element of C83) holds (B14 in C84 implies ( B13 * B14 ) in C84))));
end;
registration
let C85 being Algebra;
cluster  additively-linearly-closed ->  additively-closed for (Subset of C85);
coherence
proof
L187:
now
let C86 being (Subset of C85);
assume L188: C86 is  additively-linearly-closed;
L189: C86 is  add-closed  having-inverse by L188 , L185;
thus L190: C86 is  additively-closed by L189;
end;
thus L191: thesis by L187;
end;
end;
definition
let C87 being Algebra;
let C88 being (Subset of C87);
assume that
L193: C88 is  additively-linearly-closed non  empty;
func Mult_ (C88 , C87) -> (Function of [: ( REAL ) , C88 :] , C88) equals 
:L194: ( (the Mult of C87) | [: ( REAL ) , C88 :] );
correctness
proof
L195: ([: ( REAL ) , C88 :] c= [: ( REAL ) , (the carrier of C87) :] & ( dom (the Mult of C87) ) = [: ( REAL ) , (the carrier of C87) :]) by FUNCT_2:def 1 , ZFMISC_1:95;
L196: (for B15 being set holds (B15 in [: ( REAL ) , C88 :] implies ( ( (the Mult of C87) | [: ( REAL ) , C88 :] ) . B15 ) in C88))
proof
let C89 being set;
assume that
L197: C89 in [: ( REAL ) , C88 :];
consider C90 , C91 being set such that L198: C90 in ( REAL ) and L199: C91 in C88 and L200: C89 = [ C90 , C91 ] by L197 , ZFMISC_1:def 2;
reconsider D58 = C90 as Real by L198;
reconsider D59 = C91 as (VECTOR of C87) by L199;
L201: [ D58 , C91 ] in ( dom ( (the Mult of C87) | [: ( REAL ) , C88 :] ) ) by L195 , L197 , L200 , RELAT_1:62;
L202: ( ( (the Mult of C87) | [: ( REAL ) , C88 :] ) . C89 ) = ( D58 * D59 ) by L201 , L200 , FUNCT_1:47;
thus L203: thesis by L202 , L193 , L199 , L185;
end;
L204: ( dom ( (the Mult of C87) | [: ( REAL ) , C88 :] ) ) = [: ( REAL ) , C88 :] by L195 , RELAT_1:62;
thus L205: thesis by L204 , L196 , FUNCT_2:3;
end;
end;
definition
let C92 being non  empty RLSStruct;
attr C92 is  scalar-mult-cancelable
means
:L207: (for B16 being Real holds (for B17 being (Element of C92) holds (( B16 * B17 ) = ( 0. C92 ) implies (B16 = ( 0 ) or B17 = ( 0. C92 )))));
end;
theorem
L209: (for B18 being  add-associative  right_zeroed  right_complementable  vector-distributive  scalar-distributive  scalar-associative  vector-associative non  empty AlgebraStr holds (for B19 being Real holds ( B19 * ( 0. B18 ) ) = ( 0. B18 )))
proof
let C93 being  add-associative  right_zeroed  right_complementable  vector-distributive  scalar-distributive  scalar-associative  vector-associative non  empty AlgebraStr;
let C94 being Real;
L210: ( ( C94 * ( 0. C93 ) ) + ( C94 * ( 0. C93 ) ) ) = ( C94 * ( ( 0. C93 ) + ( 0. C93 ) ) ) by RLVECT_1:def 5;
L211: ( ( C94 * ( 0. C93 ) ) + ( C94 * ( 0. C93 ) ) ) = ( C94 * ( 0. C93 ) ) by L210 , RLVECT_1:4;
L212: ( ( C94 * ( 0. C93 ) ) + ( C94 * ( 0. C93 ) ) ) = ( ( C94 * ( 0. C93 ) ) + ( 0. C93 ) ) by L211 , RLVECT_1:4;
thus L213: thesis by L212 , RLVECT_1:8;
end;
theorem
L214: (for B20 being  Abelian  add-associative  right_zeroed  right_complementable  vector-distributive  scalar-distributive  scalar-associative  vector-associative non  empty AlgebraStr holds (B20 is  scalar-mult-cancelable implies B20 is RealLinearSpace))
proof
let C95 being  Abelian  add-associative  right_zeroed  right_complementable  vector-distributive  scalar-distributive  scalar-associative  vector-associative non  empty AlgebraStr;
assume L215: C95 is  scalar-mult-cancelable;
L216: (for B21 being (VECTOR of C95) holds ( 1 * B21 ) = B21)
proof
let C96 being (VECTOR of C95);
L217: ( ( 1 * C96 ) + ( 1 * ( - C96 ) ) ) = ( 1 * ( C96 + ( - C96 ) ) ) by RLVECT_1:def 5;
L218: (( ( 1 * C96 ) - ( 1 * C96 ) ) = ( 0. C95 ) & ( ( 1 * C96 ) + ( 1 * ( - C96 ) ) ) = ( 1 * ( 0. C95 ) )) by L217 , RLVECT_1:5;
L219: ( - ( 1 * C96 ) ) = ( 1 * ( - C96 ) ) by L218 , L209 , RLVECT_1:8;
L220: ( 1 * C96 ) = ( ( 1 * 1 ) * C96 )
.= ( 1 * ( 1 * C96 ) ) by RLVECT_1:def 7;
L221: ( ( 1 * ( 1 * C96 ) ) - ( 1 * C96 ) ) = ( 0. C95 ) by L220 , RLVECT_1:15;
L222: ( 1 * ( ( 1 * C96 ) - C96 ) ) = ( 0. C95 ) by L221 , L219 , RLVECT_1:def 5;
L223: ( ( 1 * C96 ) - C96 ) = ( 0. C95 ) by L222 , L215 , L207;
thus L224: thesis by L223 , RLVECT_1:21;
end;
thus L225: thesis by L216 , RLVECT_1:def 8;
end;
L226: (for B22 being  Abelian  add-associative  right_zeroed  right_complementable  vector-distributive  scalar-distributive  scalar-associative  vector-associative non  empty AlgebraStr holds ((for B23 being (VECTOR of B22) holds ( 1 * B23 ) = B23) implies B22 is RealLinearSpace)) by RLVECT_1:def 8;
theorem
L227: (for R9 being Algebra holds (for R10 being (Subset of R9) holds (R10 is  additively-linearly-closed  multiplicatively-closed non  empty implies AlgebraStr (# R10 , ( mult_ (R10 , R9) ) , ( Add_ (R10 , R9) ) , ( Mult_ (R10 , R9) ) , ( One_ (R10 , R9) ) , ( Zero_ (R10 , R9) ) #) is (Subalgebra of R9))))
proof
let R9 being Algebra;
let R10 being (Subset of R9);
assume L228: R10 is  additively-linearly-closed  multiplicatively-closed non  empty;
L229: ( Mult_ (R10 , R9) ) = ( (the Mult of R9) | [: ( REAL ) , R10 :] ) by L228 , L194;
L230: (( One_ (R10 , R9) ) = ( 1_ R9 ) & ( mult_ (R10 , R9) ) = ( (the multF of R9) || R10 )) by L228 , L80 , L98;
L231: (( Zero_ (R10 , R9) ) = ( 0. R9 ) & ( Add_ (R10 , R9) ) = ( (the addF of R9) || R10 )) by L228 , L67 , L93;
thus L232: thesis by L231 , L228 , L230 , L229 , L108;
end;
registration
let C97 being non  empty set;
cluster ( RAlgebra C97 ) ->  Abelian  add-associative  right_zeroed  right_complementable  commutative  associative  right_unital  right-distributive  vector-distributive  scalar-distributive  scalar-associative  vector-associative;
correctness;
end;
theorem
L234: (for R1 being non  empty set holds ( RAlgebra R1 ) is RealLinearSpace)
proof
let R1 being non  empty set;
L235: (for B24 being (VECTOR of ( RAlgebra R1 )) holds ( 1 * B24 ) = B24) by FUNCSDOM:12;
thus L236: thesis by L235 , L226;
end;
theorem
L237: (for B25 being Algebra holds (for B26 being (Subalgebra of B25) holds ((for B27 , B28 being (Element of B26) holds (for B29 , B30 being (Element of B25) holds ((B27 = B29 & B28 = B30) implies ( B27 + B28 ) = ( B29 + B30 )))) & (for B31 , B32 being (Element of B26) holds (for B33 , B34 being (Element of B25) holds ((B31 = B33 & B32 = B34) implies ( B31 * B32 ) = ( B33 * B34 )))) & (for B35 being (Element of B26) holds (for B36 being (Element of B25) holds (for B37 being Real holds (B35 = B36 implies ( B37 * B35 ) = ( B37 * B36 ))))) & ( 1_ B26 ) = ( 1_ B25 ) & ( 0. B26 ) = ( 0. B25 ))))
proof
let C98 being Algebra;
let C99 being (Subalgebra of C98);
thus L238:now
let C100 , C101 being (Element of C99);
let C102 , C103 being (Element of C98);
assume L239: (C100 = C102 & C101 = C103);
L240: ( C100 + C101 ) = ( ( (the addF of C98) || (the carrier of C99) ) . [ C100 , C101 ] ) by L105;
thus L241: ( C100 + C101 ) = ( C102 + C103 ) by L240 , L239 , FUNCT_1:49;
end;
thus L242:now
let C104 , C105 being (Element of C99);
let C106 , C107 being (Element of C98);
assume L243: (C104 = C106 & C105 = C107);
L244: ( C104 * C105 ) = ( ( (the multF of C98) || (the carrier of C99) ) . [ C104 , C105 ] ) by L105;
thus L245: ( C104 * C105 ) = ( C106 * C107 ) by L244 , L243 , FUNCT_1:49;
end;
thus L246:now
let C108 being (Element of C99);
let C109 being (Element of C98);
let C110 being Real;
assume L247: C108 = C109;
L248: ( C110 * C108 ) = ( ( (the Mult of C98) | [: ( REAL ) , (the carrier of C99) :] ) . [ C110 , C108 ] ) by L105;
thus L249: ( C110 * C108 ) = ( C110 * C109 ) by L248 , L247 , FUNCT_1:49;
end;
thus L250: thesis by L105;
end;
begin
definition
let C111 being non  empty set;
func BoundedFunctions C111 -> non  empty (Subset of ( RAlgebra C111 )) equals 
{ B38 where B38 is (Function of C111 , ( REAL )) : ( B38 | C111 ) is  bounded };
correctness
proof
L251: { B39 where B39 is (Function of C111 , ( REAL )) : ( B39 | C111 ) is  bounded } is non  empty
proof
reconsider D60 = ( C111 --> ( 0 ) ) as (Function of C111 , ( REAL )) by FUNCOP_1:46;
L252: ( D60 | C111 ) is  bounded;
L253: D60 in { B40 where B40 is (Function of C111 , ( REAL )) : ( B40 | C111 ) is  bounded } by L252;
thus L254: thesis by L253;
end;
L255: { B41 where B41 is (Function of C111 , ( REAL )) : ( B41 | C111 ) is  bounded } c= ( Funcs (C111 , ( REAL )) )
proof
let C112 being set;
assume L256: C112 in { B42 where B42 is (Function of C111 , ( REAL )) : ( B42 | C111 ) is  bounded };
L257: (ex B43 being (Function of C111 , ( REAL )) st (C112 = B43 & ( B43 | C111 ) is  bounded)) by L256;
thus L258: thesis by L257 , FUNCT_2:8;
end;
thus L259: thesis by L255 , L251;
end;
end;
theorem
L261: (for R1 being non  empty set holds ( BoundedFunctions R1 ) is  additively-linearly-closed  multiplicatively-closed)
proof
let R1 being non  empty set;
set D61 = ( BoundedFunctions R1 );
set D62 = ( RAlgebra R1 );
L262: (for B44 , B45 being (Element of D62) holds ((B44 in D61 & B45 in D61) implies ( B44 * B45 ) in D61))
proof
let C113 , C114 being (Element of D62);
assume that
L263: C113 in D61
and
L264: C114 in D61;
consider C115 being (Function of R1 , ( REAL )) such that L265: C115 = C114 and L266: ( C115 | R1 ) is  bounded by L264;
reconsider D63 = ( C113 * C114 ) as (Element of ( Funcs (R1 , ( REAL )) ));
consider C116 being (Function of R1 , ( REAL )) such that L267: C116 = C113 and L268: ( C116 | R1 ) is  bounded by L263;
L269: ( dom ( C116 (#) C115 ) ) = ( R1 /\ R1 ) by FUNCT_2:def 1;
L270: ( ( C116 (#) C115 ) | R1 ) is  bounded by L269 , L268 , L266 , RFUNCT_1:84;
L271: ( ( dom C116 ) /\ ( dom C115 ) ) = ( R1 /\ ( dom C115 ) ) by FUNCT_2:def 1;
L272: ((ex B46 being Function st (D63 = B46 & ( dom B46 ) = R1 & ( rng B46 ) c= ( REAL ))) & ( ( dom C116 ) /\ ( dom C115 ) ) = ( R1 /\ R1 )) by L271 , FUNCT_2:def 1 , FUNCT_2:def 2;
L273: (for B47 being set holds (B47 in ( dom D63 ) implies ( D63 . B47 ) = ( ( C116 . B47 ) * ( C115 . B47 ) ))) by L267 , L265 , FUNCSDOM:2;
L274: ( C113 * C114 ) = ( C116 (#) C115 ) by L273 , L272 , VALUED_1:def 4;
thus L275: thesis by L274 , L270;
end;
reconsider D64 = ( RealFuncUnit R1 ) as (Function of R1 , ( REAL ));
L276: (for B48 , B49 being (Element of D62) holds ((B48 in D61 & B49 in D61) implies ( B48 + B49 ) in D61))
proof
let C117 , C118 being (Element of D62);
assume that
L277: C117 in D61
and
L278: C118 in D61;
consider C119 being (Function of R1 , ( REAL )) such that L279: C119 = C118 and L280: ( C119 | R1 ) is  bounded by L278;
reconsider D65 = ( C117 + C118 ) as (Element of ( Funcs (R1 , ( REAL )) ));
consider C120 being (Function of R1 , ( REAL )) such that L281: C120 = C117 and L282: ( C120 | R1 ) is  bounded by L277;
L283: ( dom ( C120 + C119 ) ) = ( R1 /\ R1 ) by FUNCT_2:def 1;
L284: ( ( C120 + C119 ) | R1 ) is  bounded by L283 , L282 , L280 , RFUNCT_1:83;
L285: ( ( dom C120 ) /\ ( dom C119 ) ) = ( R1 /\ ( dom C119 ) ) by FUNCT_2:def 1;
L286: ((ex B50 being Function st (D65 = B50 & ( dom B50 ) = R1 & ( rng B50 ) c= ( REAL ))) & ( ( dom C120 ) /\ ( dom C119 ) ) = ( R1 /\ R1 )) by L285 , FUNCT_2:def 1 , FUNCT_2:def 2;
L287: (for B51 being set holds (B51 in ( dom D65 ) implies ( D65 . B51 ) = ( ( C120 . B51 ) + ( C119 . B51 ) ))) by L281 , L279 , FUNCSDOM:1;
L288: ( C117 + C118 ) = ( C120 + C119 ) by L287 , L286 , VALUED_1:def 1;
thus L289: thesis by L288 , L284;
end;
L290: D61 is  add-closed by L276 , IDEAL_1:def 1;
L291: ( RAlgebra R1 ) is RealLinearSpace by L234;
L292: (for B52 being (Element of D62) holds (B52 in D61 implies ( - B52 ) in D61))
proof
let C121 being (Element of D62);
assume L293: C121 in D61;
consider C122 being (Function of R1 , ( REAL )) such that L294: C122 = C121 and L295: ( C122 | R1 ) is  bounded by L293;
L296: ( ( - C122 ) | R1 ) is  bounded by L295 , RFUNCT_1:82;
reconsider D66 = ( - C121 ) , D67 = C121 as (Element of ( Funcs (R1 , ( REAL )) ));
L297: D66 = ( ( - 1 ) * C121 ) by L291 , RLVECT_1:16;
L298:
now
let C123 being set;
assume L299: C123 in ( dom D66 );
reconsider D68 = C123 as (Element of R1) by L299;
L300: ( D66 . C123 ) = ( ( - 1 ) * ( D67 . D68 ) ) by L297 , FUNCSDOM:4;
thus L301: ( D66 . C123 ) = ( - ( C122 . C123 ) ) by L300 , L294;
end;
L302: ((ex B53 being Function st (D66 = B53 & ( dom B53 ) = R1 & ( rng B53 ) c= ( REAL ))) & ( dom C122 ) = R1) by FUNCT_2:def 1 , FUNCT_2:def 2;
L303: ( - C121 ) = ( - C122 ) by L302 , L298 , VALUED_1:9;
thus L304: thesis by L303 , L296;
end;
L305: D61 is  having-inverse by L292 , L1;
L306: (for B54 being Real holds (for B55 being (Element of D62) holds (B55 in D61 implies ( B54 * B55 ) in D61)))
proof
let C124 being Real;
let C125 being (Element of D62);
assume L307: C125 in D61;
consider C126 being (Function of R1 , ( REAL )) such that L308: C126 = C125 and L309: ( C126 | R1 ) is  bounded by L307;
L310: ( ( C124 (#) C126 ) | R1 ) is  bounded by L309 , RFUNCT_1:80;
reconsider D69 = ( C124 * C125 ) as (Element of ( Funcs (R1 , ( REAL )) ));
L311: ((ex B56 being Function st (D69 = B56 & ( dom B56 ) = R1 & ( rng B56 ) c= ( REAL ))) & ( dom C126 ) = R1) by FUNCT_2:def 1 , FUNCT_2:def 2;
L312: (for B57 being set holds (B57 in ( dom D69 ) implies ( D69 . B57 ) = ( C124 * ( C126 . B57 ) ))) by L308 , FUNCSDOM:4;
L313: ( C124 * C125 ) = ( C124 (#) C126 ) by L312 , L311 , VALUED_1:def 5;
thus L314: thesis by L313 , L310;
end;
thus L315: ( BoundedFunctions R1 ) is  additively-linearly-closed by L306 , L290 , L305 , L185;
L316: ( D64 | R1 ) is  bounded;
L317: ( 1. D62 ) in D61 by L316;
thus L318: thesis by L317 , L262 , L64;
end;
registration
let R1 being non  empty set;
cluster ( BoundedFunctions R1 ) ->  additively-linearly-closed  multiplicatively-closed;
coherence by L261;
end;
definition
let C127 being non  empty set;
func R_Algebra_of_BoundedFunctions C127 -> Algebra equals 
AlgebraStr (# ( BoundedFunctions C127 ) , ( mult_ (( BoundedFunctions C127 ) , ( RAlgebra C127 )) ) , ( Add_ (( BoundedFunctions C127 ) , ( RAlgebra C127 )) ) , ( Mult_ (( BoundedFunctions C127 ) , ( RAlgebra C127 )) ) , ( One_ (( BoundedFunctions C127 ) , ( RAlgebra C127 )) ) , ( Zero_ (( BoundedFunctions C127 ) , ( RAlgebra C127 )) ) #);
coherence by L227;
end;
theorem
L321: (for R1 being non  empty set holds ( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 ))) by L227;
theorem
L322: (for R1 being non  empty set holds ( R_Algebra_of_BoundedFunctions R1 ) is RealLinearSpace)
proof
let R1 being non  empty set;
L323:
now
let C128 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
reconsider D70 = C128 as (VECTOR of ( RAlgebra R1 )) by TARSKI:def 3;
L324: ( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 )) by L227;
L325: ( 1 * C128 ) = ( 1 * D70 ) by L324 , L237;
thus L326: ( 1 * C128 ) = C128 by L325 , FUNCSDOM:12;
end;
thus L327: thesis by L323 , L226;
end;
theorem
L328: (for R1 being non  empty set holds (for R13 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R14 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R15 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds (for R18 being (Function of R1 , ( REAL )) holds ((R16 = R13 & R17 = R14 & R18 = R15) implies (R15 = ( R13 + R14 ) iff (for B58 being (Element of R1) holds ( R18 . B58 ) = ( ( R16 . B58 ) + ( R17 . B58 ) )))))))))))
proof
let R1 being non  empty set;
let R13 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R14 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R15 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
let R18 being (Function of R1 , ( REAL ));
assume L329: (R16 = R13 & R17 = R14 & R18 = R15);
reconsider D71 = R13 , D72 = R14 , D73 = R15 as (VECTOR of ( RAlgebra R1 )) by TARSKI:def 3;
L330: ( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 )) by L227;
thus L331:now
assume L332: R15 = ( R13 + R14 );
let C129 being (Element of R1);
L333: D73 = ( D71 + D72 ) by L330 , L332 , L237;
thus L334: ( R18 . C129 ) = ( ( R16 . C129 ) + ( R17 . C129 ) ) by L333 , L329 , FUNCSDOM:1;
end;
assume L335: (for B59 being (Element of R1) holds ( R18 . B59 ) = ( ( R16 . B59 ) + ( R17 . B59 ) ));
L336: D73 = ( D71 + D72 ) by L335 , L329 , FUNCSDOM:1;
thus L337: thesis by L336 , L330 , L237;
end;
theorem
L338: (for R1 being non  empty set holds (for R12 being Real holds (for R13 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R14 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds ((R16 = R13 & R17 = R14) implies (R14 = ( R12 * R13 ) iff (for B60 being (Element of R1) holds ( R17 . B60 ) = ( R12 * ( R16 . B60 ) ))))))))))
proof
let R1 being non  empty set;
let R12 being Real;
let R13 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R14 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
assume L339: (R16 = R13 & R17 = R14);
reconsider D74 = R13 , D75 = R14 as (VECTOR of ( RAlgebra R1 )) by TARSKI:def 3;
L340: ( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 )) by L227;
thus L341:now
assume L342: R14 = ( R12 * R13 );
let C130 being (Element of R1);
L343: D75 = ( R12 * D74 ) by L340 , L342 , L237;
thus L344: ( R17 . C130 ) = ( R12 * ( R16 . C130 ) ) by L343 , L339 , FUNCSDOM:4;
end;
assume L345: (for B61 being (Element of R1) holds ( R17 . B61 ) = ( R12 * ( R16 . B61 ) ));
L346: D75 = ( R12 * D74 ) by L345 , L339 , FUNCSDOM:4;
thus L347: thesis by L346 , L340 , L237;
end;
theorem
L348: (for R1 being non  empty set holds (for R13 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R14 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R15 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 )) holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds (for R18 being (Function of R1 , ( REAL )) holds ((R16 = R13 & R17 = R14 & R18 = R15) implies (R15 = ( R13 * R14 ) iff (for B62 being (Element of R1) holds ( R18 . B62 ) = ( ( R16 . B62 ) * ( R17 . B62 ) )))))))))))
proof
let R1 being non  empty set;
let R13 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R14 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R15 being (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
let R18 being (Function of R1 , ( REAL ));
assume L349: (R16 = R13 & R17 = R14 & R18 = R15);
reconsider D76 = R13 , D77 = R14 , D78 = R15 as (VECTOR of ( RAlgebra R1 )) by TARSKI:def 3;
L350: ( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 )) by L227;
thus L351:now
assume L352: R15 = ( R13 * R14 );
let C131 being (Element of R1);
L353: D78 = ( D76 * D77 ) by L350 , L352 , L237;
thus L354: ( R18 . C131 ) = ( ( R16 . C131 ) * ( R17 . C131 ) ) by L353 , L349 , FUNCSDOM:2;
end;
assume L355: (for B63 being (Element of R1) holds ( R18 . B63 ) = ( ( R16 . B63 ) * ( R17 . B63 ) ));
L356: D78 = ( D76 * D77 ) by L355 , L349 , FUNCSDOM:2;
thus L357: thesis by L356 , L350 , L237;
end;
theorem
L358: (for R1 being non  empty set holds ( 0. ( R_Algebra_of_BoundedFunctions R1 ) ) = ( R1 --> ( 0 ) ))
proof
let R1 being non  empty set;
L359: (( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 )) & ( 0. ( RAlgebra R1 ) ) = ( R1 --> ( 0 ) )) by L227;
thus L360: thesis by L359 , L237;
end;
theorem
L361: (for R1 being non  empty set holds ( 1_ ( R_Algebra_of_BoundedFunctions R1 ) ) = ( R1 --> 1 ))
proof
let R1 being non  empty set;
L362: (( R_Algebra_of_BoundedFunctions R1 ) is (Subalgebra of ( RAlgebra R1 )) & ( 1_ ( RAlgebra R1 ) ) = ( R1 --> 1 )) by L227;
thus L363: thesis by L362 , L237;
end;
definition
let C132 being non  empty set;
let C133 being set;
assume that
L364: C133 in ( BoundedFunctions C132 );
func modetrans (C133 , C132) -> (Function of C132 , ( REAL )) means 
:L365: (it = C133 & ( it | C132 ) is  bounded);
correctness by L364;
end;
definition
let C134 being non  empty set;
let C135 being (Function of C134 , ( REAL ));
func PreNorms C135 -> non  empty (Subset of ( REAL )) equals 
{ ( abs ( C135 . B64 ) ) where B64 is (Element of C134) : (not contradiction) };
coherence
proof
set D79 = the (Element of C134);
L367:
now
let C136 being set;
L368:
now
assume L369: C136 in { ( abs ( C135 . B65 ) ) where B65 is (Element of C134) : (not contradiction) };
L370: (ex B66 being (Element of C134) st C136 = ( abs ( C135 . B66 ) )) by L369;
thus L371: C136 in ( REAL ) by L370;
end;
thus L372: (C136 in { ( abs ( C135 . B67 ) ) where B67 is (Element of C134) : (not contradiction) } implies C136 in ( REAL )) by L368;
end;
L373: ( abs ( C135 . D79 ) ) in { ( abs ( C135 . B68 ) ) where B68 is (Element of C134) : (not contradiction) };
thus L374: thesis by L373 , L367 , TARSKI:def 3;
end;
end;
theorem
L376: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (( R16 | R1 ) is  bounded implies ( PreNorms R16 ) is  bounded_above)))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
assume L377: ( R16 | R1 ) is  bounded;
consider C137 being  real number such that L378: (for B69 being set holds (B69 in ( R1 /\ ( dom R16 ) ) implies ( abs ( R16 . B69 ) ) <= C137)) by L377 , RFUNCT_1:73;
L379: ( R1 /\ ( dom R16 ) ) = ( R1 /\ R1 ) by FUNCT_2:def 1;
take C137;
let C138 being  ext-real number;
assume L380: C138 in ( PreNorms R16 );
L381: (ex B70 being (Element of R1) st C138 = ( abs ( R16 . B70 ) )) by L380;
thus L382: C138 <= C137 by L381 , L378 , L379;
end;
theorem
L383: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (( R16 | R1 ) is  bounded iff ( PreNorms R16 ) is  bounded_above)))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
L384:
now
reconsider D80 = ( upper_bound ( PreNorms R16 ) ) as Real;
assume L385: ( PreNorms R16 ) is  bounded_above;
take D81 = D80;
L386:
now
let C139 being set;
assume L387: C139 in ( R1 /\ ( dom R16 ) );
L388: ( abs ( R16 . C139 ) ) in ( PreNorms R16 ) by L387;
thus L389: ( abs ( R16 . C139 ) ) <= D81 by L388 , L385 , SEQ_4:def 1;
end;
thus L390: ( R16 | R1 ) is  bounded by L386 , RFUNCT_1:73;
end;
thus L391: thesis by L384 , L376;
end;
definition
let C140 being non  empty set;
func BoundedFunctionsNorm C140 -> (Function of ( BoundedFunctions C140 ) , ( REAL )) means 
:L392: (for B71 being set holds (B71 in ( BoundedFunctions C140 ) implies ( it . B71 ) = ( upper_bound ( PreNorms ( modetrans (B71 , C140) ) ) )));
existence
proof
deffunc H1(set) = ( upper_bound ( PreNorms ( modetrans ($1 , C140) ) ) );
L393: (for B72 being set holds (B72 in ( BoundedFunctions C140 ) implies H1(B72) in ( REAL )));
L394: (ex B73 being (Function of ( BoundedFunctions C140 ) , ( REAL )) st (for B74 being set holds (B74 in ( BoundedFunctions C140 ) implies ( B73 . B74 ) = H1(B74)))) from FUNCT_2:sch 2(L393);
thus L395: thesis by L394;
end;
uniqueness
proof
let C141 , C142 being (Function of ( BoundedFunctions C140 ) , ( REAL ));
assume that
L396: (for B75 being set holds (B75 in ( BoundedFunctions C140 ) implies ( C141 . B75 ) = ( upper_bound ( PreNorms ( modetrans (B75 , C140) ) ) )))
and
L397: (for B76 being set holds (B76 in ( BoundedFunctions C140 ) implies ( C142 . B76 ) = ( upper_bound ( PreNorms ( modetrans (B76 , C140) ) ) )));
L398: (for B77 being set holds (B77 in ( BoundedFunctions C140 ) implies ( C141 . B77 ) = ( C142 . B77 )))
proof
let C143 being set;
assume that
L399: C143 in ( BoundedFunctions C140 );
L400: ( C141 . C143 ) = ( upper_bound ( PreNorms ( modetrans (C143 , C140) ) ) ) by L396 , L399;
thus L401: thesis by L400 , L397 , L399;
end;
L402: (( dom C141 ) = ( BoundedFunctions C140 ) & ( dom C142 ) = ( BoundedFunctions C140 )) by FUNCT_2:def 1;
thus L403: thesis by L402 , L398 , FUNCT_1:2;
end;
end;
theorem
L405: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (( R16 | R1 ) is  bounded implies ( modetrans (R16 , R1) ) = R16)))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
assume L406: ( R16 | R1 ) is  bounded;
L407: R16 in ( BoundedFunctions R1 ) by L406;
thus L408: thesis by L407 , L365;
end;
theorem
L409: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (( R16 | R1 ) is  bounded implies ( ( BoundedFunctionsNorm R1 ) . R16 ) = ( upper_bound ( PreNorms R16 ) ))))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
reconsider D82 = R16 as set;
assume L410: ( R16 | R1 ) is  bounded;
L411: R16 in ( BoundedFunctions R1 ) by L410;
L412: ( ( BoundedFunctionsNorm R1 ) . R16 ) = ( upper_bound ( PreNorms ( modetrans (D82 , R1) ) ) ) by L411 , L392;
thus L413: thesis by L412 , L410 , L405;
end;
definition
let C144 being non  empty set;
func R_Normed_Algebra_of_BoundedFunctions C144 -> Normed_AlgebraStr equals 
Normed_AlgebraStr (# ( BoundedFunctions C144 ) , ( mult_ (( BoundedFunctions C144 ) , ( RAlgebra C144 )) ) , ( Add_ (( BoundedFunctions C144 ) , ( RAlgebra C144 )) ) , ( Mult_ (( BoundedFunctions C144 ) , ( RAlgebra C144 )) ) , ( One_ (( BoundedFunctions C144 ) , ( RAlgebra C144 )) ) , ( Zero_ (( BoundedFunctions C144 ) , ( RAlgebra C144 )) ) , ( BoundedFunctionsNorm C144 ) #);
correctness;
end;
registration
let C145 being non  empty set;
cluster ( R_Normed_Algebra_of_BoundedFunctions C145 ) -> non  empty;
correctness;
end;
L416:
now
let C146 being non  empty set;
set D83 = ( R_Normed_Algebra_of_BoundedFunctions C146 );
let C147 , C148 being (Element of D83);
set D84 = ( BoundedFunctions C146 );
reconsider D85 = C147 as (Element of D84);
assume L417: C148 = ( One_ (( BoundedFunctions C146 ) , ( RAlgebra C146 )) );
L418: ( C147 * C148 ) = ( ( mult_ (D84 , ( RAlgebra C146 )) ) . (D85 , ( 1_ ( RAlgebra C146 ) )) ) by L417 , L98;
L419: ( C147 * C148 ) = ( ( (the multF of ( RAlgebra C146 )) || D84 ) . (D85 , ( 1_ ( RAlgebra C146 ) )) ) by L418 , L80;
L420: ( C148 * C147 ) = ( ( mult_ (D84 , ( RAlgebra C146 )) ) . (( 1_ ( RAlgebra C146 ) ) , D85) ) by L417 , L98;
L421: ( C148 * C147 ) = ( ( (the multF of ( RAlgebra C146 )) || D84 ) . (( 1_ ( RAlgebra C146 ) ) , D85) ) by L420 , L80;
L422: ( 1_ ( RAlgebra C146 ) ) = ( 1_ ( R_Algebra_of_BoundedFunctions C146 ) ) by L361;
L423: [ D85 , ( 1_ ( RAlgebra C146 ) ) ] in [: D84 , D84 :] by L422 , ZFMISC_1:87;
L424: ( C147 * C148 ) = ( D85 * ( 1_ ( RAlgebra C146 ) ) ) by L423 , L419 , FUNCT_1:49;
thus L425: ( C147 * C148 ) = C147 by L424 , VECTSP_1:def 4;
L426: [ ( 1_ ( RAlgebra C146 ) ) , D85 ] in [: D84 , D84 :] by L422 , ZFMISC_1:87;
L427: ( C148 * C147 ) = ( ( 1_ ( RAlgebra C146 ) ) * D85 ) by L426 , L421 , FUNCT_1:49;
thus L428: ( C148 * C147 ) = C147 by L427 , VECTSP_1:def 4;
end;
registration
let C149 being non  empty set;
cluster ( R_Normed_Algebra_of_BoundedFunctions C149 ) ->  unital;
correctness
proof
reconsider D86 = ( One_ (( BoundedFunctions C149 ) , ( RAlgebra C149 )) ) as (Element of ( R_Normed_Algebra_of_BoundedFunctions C149 ));
take D86;
thus L429: thesis by L416;
end;
end;
theorem
L431: (for B78 being Normed_AlgebraStr holds (for B79 being Algebra holds (( the AlgebraStr of B78 ) = B79 implies B78 is Algebra)))
proof
let C150 being Normed_AlgebraStr;
let C151 being Algebra;
assume that
L432: ( the AlgebraStr of C150 ) = C151;
reconsider D87 = C150 as non  empty AlgebraStr by L432;
L433: D87 is  right_unital
proof
let C152 being (Element of D87);
reconsider D88 = C152 as (Element of C151) by L432;
L434: ( C152 * ( 1. D87 ) ) = ( D88 * ( 1. C151 ) ) by L432;
thus L435: thesis by L434 , VECTSP_1:def 4;
end;
L436: D87 is  right-distributive
proof
let C153 , C154 , C155 being (Element of D87);
reconsider D89 = C153 , D90 = C154 , D91 = C155 as (Element of C151) by L432;
L437: ( C153 * ( C154 + C155 ) ) = ( D89 * ( D90 + D91 ) ) by L432;
L438: ( C153 * ( C154 + C155 ) ) = ( ( D89 * D90 ) + ( D89 * D91 ) ) by L437 , VECTSP_1:def 2;
thus L439: thesis by L438 , L432;
end;
L440: (for B80 being (Element of D87) holds B80 is  right_complementable)
proof
let C156 being (Element of D87);
reconsider D92 = C156 as (Element of C151) by L432;
consider C157 being (Element of C151) such that L441: ( D92 + C157 ) = ( 0. C151 ) by ALGSTR_0:def 11;
reconsider D93 = C157 as (Element of D87) by L432;
L442: ( C156 + D93 ) = ( 0. D87 ) by L432 , L441;
thus L443: thesis by L442 , ALGSTR_0:def 11;
end;
L444: (for B81 , B82 , B83 being (Element of D87) holds ( ( B81 * B82 ) * B83 ) = ( B81 * ( B82 * B83 ) ))
proof
let C158 , C159 , C160 being (Element of D87);
reconsider D94 = C160 , D95 = C158 , D96 = C159 as (Element of C151) by L432;
L445: ( ( C158 * C159 ) * C160 ) = ( ( D95 * D96 ) * D94 ) by L432;
L446: ( ( C158 * C159 ) * C160 ) = ( D95 * ( D96 * D94 ) ) by L445 , GROUP_1:def 3;
thus L447: thesis by L446 , L432;
end;
L448: (for B84 , B85 being (Element of D87) holds ( B84 * B85 ) = ( B85 * B84 ))
proof
let C161 , C162 being (Element of D87);
reconsider D97 = C161 , D98 = C162 as (Element of C151) by L432;
L449: ( C161 * C162 ) = ( D97 * D98 ) by L432;
L450: ( C161 * C162 ) = ( D98 * D97 ) by L449;
thus L451: thesis by L450 , L432;
end;
L452: (for B86 , B87 , B88 being (VECTOR of D87) holds ( ( B86 + B87 ) + B88 ) = ( B86 + ( B87 + B88 ) ))
proof
let C163 , C164 , C165 being (VECTOR of D87);
reconsider D99 = C163 , D100 = C164 , D101 = C165 as (VECTOR of C151) by L432;
L453: ( ( C163 + C164 ) + C165 ) = ( ( D99 + D100 ) + D101 ) by L432;
L454: ( ( C163 + C164 ) + C165 ) = ( D99 + ( D100 + D101 ) ) by L453 , RLVECT_1:def 3;
thus L455: thesis by L454 , L432;
end;
L456: (for B89 , B90 being (VECTOR of D87) holds ( B89 + B90 ) = ( B90 + B89 ))
proof
let C166 , C167 being (VECTOR of D87);
reconsider D102 = C166 , D103 = C167 as (VECTOR of C151) by L432;
L457: ( C166 + C167 ) = ( D102 + D103 ) by L432;
L458: ( C166 + C167 ) = ( D103 + D102 ) by L457;
thus L459: thesis by L458 , L432;
end;
L460: D87 is  vector-distributive
proof
let C168 being  real number;
let C169 , C170 being (Element of D87);
reconsider D104 = C169 , D105 = C170 as (Element of C151) by L432;
L461: ( C168 * ( C169 + C170 ) ) = ( C168 * ( D104 + D105 ) ) by L432;
L462: ( C168 * ( C169 + C170 ) ) = ( ( C168 * D104 ) + ( C168 * D105 ) ) by L461 , RLVECT_1:def 5;
thus L463: ( C168 * ( C169 + C170 ) ) = ( ( C168 * C169 ) + ( C168 * C170 ) ) by L462 , L432;
end;
L464: D87 is  scalar-distributive
proof
let C171 , C172 being  real number;
let C173 being (Element of D87);
reconsider D106 = C173 as (Element of C151) by L432;
L465: ( ( C171 + C172 ) * C173 ) = ( ( C171 + C172 ) * D106 ) by L432;
L466: ( ( C171 + C172 ) * C173 ) = ( ( C171 * D106 ) + ( C172 * D106 ) ) by L465 , RLVECT_1:def 6;
thus L467: ( ( C171 + C172 ) * C173 ) = ( ( C171 * C173 ) + ( C172 * C173 ) ) by L466 , L432;
thus L468: thesis;
end;
L469: D87 is  scalar-associative
proof
let C174 , C175 being  real number;
let C176 being (Element of D87);
reconsider D107 = C176 as (Element of C151) by L432;
L470: ( ( C174 * C175 ) * C176 ) = ( ( C174 * C175 ) * D107 ) by L432;
L471: ( ( C174 * C175 ) * C176 ) = ( C174 * ( C175 * D107 ) ) by L470 , RLVECT_1:def 7;
thus L472: thesis by L471 , L432;
end;
L473: D87 is  vector-associative
proof
let C177 , C178 being (Element of D87);
reconsider D108 = C177 , D109 = C178 as (Element of C151) by L432;
let C179 being Real;
L474: ( C179 * ( C177 * C178 ) ) = ( C179 * ( D108 * D109 ) ) by L432;
L475: ( C179 * ( C177 * C178 ) ) = ( ( C179 * D108 ) * D109 ) by L474 , FUNCSDOM:def 9;
thus L476: ( C179 * ( C177 * C178 ) ) = ( ( C179 * C177 ) * C178 ) by L475 , L432;
end;
L477: (for B91 being (VECTOR of D87) holds ( B91 + ( 0. D87 ) ) = B91)
proof
let C180 being (VECTOR of D87);
reconsider D110 = C180 as (VECTOR of C151) by L432;
L478: ( C180 + ( 0. D87 ) ) = ( D110 + ( 0. C151 ) ) by L432;
thus L479: thesis by L478 , RLVECT_1:4;
end;
thus L480: thesis by L477 , L456 , L452 , L440 , L448 , L444 , L433 , L436 , L460 , L464 , L469 , L473 , ALGSTR_0:def 16 , GROUP_1:def 3 , GROUP_1:def 12 , RLVECT_1:def 2 , RLVECT_1:def 3 , RLVECT_1:def 4;
end;
theorem
L481: (for R1 being non  empty set holds ( R_Normed_Algebra_of_BoundedFunctions R1 ) is Algebra)
proof
let R1 being non  empty set;
L482: ( 1. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) = ( 1_ ( R_Algebra_of_BoundedFunctions R1 ) );
thus L483: thesis by L482 , L431;
end;
theorem
L484: (for R1 being non  empty set holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ( ( Mult_ (( BoundedFunctions R1 ) , ( RAlgebra R1 )) ) . (1 , R19) ) = R19))
proof
let R1 being non  empty set;
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
set D111 = ( BoundedFunctions R1 );
reconsider D112 = R19 as (Element of D111);
L485: [ 1 , D112 ] in [: ( REAL ) , D111 :] by ZFMISC_1:87;
thus L486: ( ( Mult_ (( BoundedFunctions R1 ) , ( RAlgebra R1 )) ) . (1 , R19) ) = ( ( (the Mult of ( RAlgebra R1 )) | [: ( REAL ) , D111 :] ) . (1 , D112) ) by L194
.= ( (the Mult of ( RAlgebra R1 )) . (1 , D112) ) by L485 , FUNCT_1:49
.= R19 by FUNCSDOM:12;
end;
theorem
L487: (for R1 being non  empty set holds ( R_Normed_Algebra_of_BoundedFunctions R1 ) is RealLinearSpace)
proof
let R1 being non  empty set;
L488: ((for B92 being (VECTOR of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ( 1 * B92 ) = B92) & ( R_Normed_Algebra_of_BoundedFunctions R1 ) is Algebra) by L481 , L484;
thus L489: thesis by L488 , L226;
end;
theorem
L490: (for R1 being non  empty set holds ( R1 --> ( 0 ) ) = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ))
proof
let R1 being non  empty set;
L491: ( R1 --> ( 0 ) ) = ( 0. ( R_Algebra_of_BoundedFunctions R1 ) ) by L358;
thus L492: thesis by L491;
end;
theorem
L493: (for R1 being non  empty set holds (for R2 being (Element of R1) holds (for R16 being (Function of R1 , ( REAL )) holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ((R16 = R19 & ( R16 | R1 ) is  bounded) implies ( abs ( R16 . R2 ) ) <= ||. R19 .||)))))
proof
let R1 being non  empty set;
let R2 being (Element of R1);
let R16 being (Function of R1 , ( REAL ));
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
assume that
L494: R16 = R19
and
L495: ( R16 | R1 ) is  bounded;
L496: ( abs ( R16 . R2 ) ) in ( PreNorms R16 );
L497: ( PreNorms R16 ) is non  empty  bounded_above by L495 , L376;
L498: ( abs ( R16 . R2 ) ) <= ( upper_bound ( PreNorms R16 ) ) by L497 , L496 , SEQ_4:def 1;
thus L499: thesis by L498 , L494 , L495 , L409;
end;
theorem
L500: (for R1 being non  empty set holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ( 0 ) <= ||. R19 .||))
proof
let R1 being non  empty set;
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
L501: R19 in ( BoundedFunctions R1 );
consider C181 being (Function of R1 , ( REAL )) such that L502: R19 = C181 and L503: ( C181 | R1 ) is  bounded by L501;
L504: ( PreNorms C181 ) is non  empty  bounded_above by L503 , L376;
consider C182 being set such that L505: C182 in ( PreNorms C181 ) by XBOOLE_0:def 1;
reconsider D113 = C182 as Real by L505;
L506:
now
let C183 being Real;
assume L507: C183 in ( PreNorms C181 );
L508: (ex B93 being (Element of R1) st C183 = ( abs ( C181 . B93 ) )) by L507;
thus L509: ( 0 ) <= C183 by L508 , COMPLEX1:46;
end;
L510: ( 0 ) <= D113 by L506 , L505;
L511: ( 0 ) <= ( upper_bound ( PreNorms C181 ) ) by L510 , L504 , L505 , SEQ_4:def 1;
thus L512: thesis by L511 , L502 , L503 , L409;
end;
theorem
L513: (for R1 being non  empty set holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (R19 = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) implies ( 0 ) = ||. R19 .||)))
proof
let R1 being non  empty set;
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
set D114 = ( R1 --> ( 0 ) );
reconsider D115 = D114 as (Function of R1 , ( REAL )) by FUNCOP_1:46;
L514: R19 in ( BoundedFunctions R1 );
consider C184 being (Function of R1 , ( REAL )) such that L515: C184 = R19 and L516: ( C184 | R1 ) is  bounded by L514;
L517: ( PreNorms C184 ) is non  empty  bounded_above by L516 , L376;
consider C185 being set such that L518: C185 in ( PreNorms C184 ) by XBOOLE_0:def 1;
reconsider D116 = C185 as Real by L518;
L519: ((for B94 being  real number holds (B94 in ( PreNorms C184 ) implies B94 <= ( 0 ))) implies ( upper_bound ( PreNorms C184 ) ) <= ( 0 )) by SEQ_4:45;
assume L520: R19 = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) );
L521:
now
let C186 being Real;
assume L522: C186 in ( PreNorms C184 );
consider C187 being (Element of R1) such that L523: C186 = ( abs ( C184 . C187 ) ) by L522;
L524: D115 = C184 by L520 , L515 , L490;
L525: ( abs ( C184 . C187 ) ) = ( abs ( 0 ) ) by L524 , FUNCOP_1:7;
thus L526: (( 0 ) <= C186 & C186 <= ( 0 )) by L525 , L523 , ABSVALUE:2;
end;
L527: ( 0 ) <= D116 by L521 , L518;
L528: ( upper_bound ( PreNorms C184 ) ) = ( 0 ) by L527 , L521 , L517 , L518 , L519 , SEQ_4:def 1;
thus L529: thesis by L528 , L515 , L516 , L409;
end;
theorem
L530: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds (for R18 being (Function of R1 , ( REAL )) holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R21 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ((R16 = R19 & R17 = R20 & R18 = R21) implies (R21 = ( R19 + R20 ) iff (for B95 being (Element of R1) holds ( R18 . B95 ) = ( ( R16 . B95 ) + ( R17 . B95 ) )))))))))))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
let R18 being (Function of R1 , ( REAL ));
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R21 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
reconsider D117 = R19 , D118 = R20 , D119 = R21 as (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
L531: (R21 = ( R19 + R20 ) iff D119 = ( D117 + D118 ));
assume L532: (R16 = R19 & R17 = R20 & R18 = R21);
thus L533: thesis by L532 , L531 , L328;
end;
theorem
L534: (for R1 being non  empty set holds (for R12 being Real holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ((R16 = R19 & R17 = R20) implies (R20 = ( R12 * R19 ) iff (for B96 being (Element of R1) holds ( R17 . B96 ) = ( R12 * ( R16 . B96 ) ))))))))))
proof
let R1 being non  empty set;
let R12 being Real;
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
reconsider D120 = R19 , D121 = R20 as (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
L535: (R20 = ( R12 * R19 ) iff D121 = ( R12 * D120 ));
assume L536: (R16 = R19 & R17 = R20);
thus L537: thesis by L536 , L535 , L338;
end;
theorem
L538: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds (for R18 being (Function of R1 , ( REAL )) holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R21 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ((R16 = R19 & R17 = R20 & R18 = R21) implies (R21 = ( R19 * R20 ) iff (for B97 being (Element of R1) holds ( R18 . B97 ) = ( ( R16 . B97 ) * ( R17 . B97 ) )))))))))))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
let R18 being (Function of R1 , ( REAL ));
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R21 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
reconsider D122 = R19 , D123 = R20 , D124 = R21 as (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
L539: (R21 = ( R19 * R20 ) iff D124 = ( D122 * D123 ));
assume L540: (R16 = R19 & R17 = R20 & R18 = R21);
thus L541: thesis by L540 , L539 , L348;
end;
theorem
L542: (for R1 being non  empty set holds (for R12 being Real holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ((||. R19 .|| = ( 0 ) iff R19 = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) )) & ||. ( R12 * R19 ) .|| = ( ( abs R12 ) * ||. R19 .|| ) & ||. ( R19 + R20 ) .|| <= ( ||. R19 .|| + ||. R20 .|| ))))))
proof
let R1 being non  empty set;
let R12 being Real;
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
L543:
now
set D125 = ( R1 --> ( 0 ) );
reconsider D126 = D125 as (Function of R1 , ( REAL )) by FUNCOP_1:46;
L544: R19 in ( BoundedFunctions R1 );
consider C188 being (Function of R1 , ( REAL )) such that L545: R19 = C188 and L546: ( C188 | R1 ) is  bounded by L544;
L547: ( PreNorms C188 ) is non  empty  bounded_above by L546 , L376;
consider C189 being set such that L548: C189 in ( PreNorms C188 ) by XBOOLE_0:def 1;
reconsider D127 = C189 as Real by L548;
L549: ((for B98 being  real number holds (B98 in ( PreNorms C188 ) implies B98 <= ( 0 ))) implies ( upper_bound ( PreNorms C188 ) ) <= ( 0 )) by SEQ_4:45;
assume L550: R19 = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) );
L551: D126 = C188 by L550 , L545 , L490;
L552:
now
let C190 being Real;
assume L553: C190 in ( PreNorms C188 );
consider C191 being (Element of R1) such that L554: C190 = ( abs ( C188 . C191 ) ) by L553;
L555: ( abs ( C188 . C191 ) ) = ( abs ( 0 ) ) by L551 , FUNCOP_1:7
.= ( 0 ) by ABSVALUE:2;
thus L556: (( 0 ) <= C190 & C190 <= ( 0 )) by L555 , L554;
end;
L557: ( 0 ) <= D127 by L552 , L548;
L558: ( upper_bound ( PreNorms C188 ) ) = ( 0 ) by L557 , L552 , L547 , L548 , L549 , SEQ_4:def 1;
thus L559: ||. R19 .|| = ( 0 ) by L558 , L545 , L546 , L409;
end;
L560: ||. ( R19 + R20 ) .|| <= ( ||. R19 .|| + ||. R20 .|| )
proof
L561: ( R19 + R20 ) in ( BoundedFunctions R1 );
consider C192 being (Function of R1 , ( REAL )) such that L562: C192 = ( R19 + R20 ) and L563: ( C192 | R1 ) is  bounded by L561;
L564: R20 in ( BoundedFunctions R1 );
consider C193 being (Function of R1 , ( REAL )) such that L565: C193 = R20 and L566: ( C193 | R1 ) is  bounded by L564;
L567: R19 in ( BoundedFunctions R1 );
consider C194 being (Function of R1 , ( REAL )) such that L568: C194 = R19 and L569: ( C194 | R1 ) is  bounded by L567;
L570:
now
let C195 being (Element of R1);
L571: (( abs ( C194 . C195 ) ) <= ||. R19 .|| & ( abs ( C193 . C195 ) ) <= ||. R20 .||) by L568 , L569 , L565 , L566 , L493;
L572: ( ( abs ( C194 . C195 ) ) + ( abs ( C193 . C195 ) ) ) <= ( ||. R19 .|| + ||. R20 .|| ) by L571 , XREAL_1:7;
L573: (( abs ( C192 . C195 ) ) = ( abs ( ( C194 . C195 ) + ( C193 . C195 ) ) ) & ( abs ( ( C194 . C195 ) + ( C193 . C195 ) ) ) <= ( ( abs ( C194 . C195 ) ) + ( abs ( C193 . C195 ) ) )) by L568 , L565 , L562 , L530 , COMPLEX1:56;
thus L574: ( abs ( C192 . C195 ) ) <= ( ||. R19 .|| + ||. R20 .|| ) by L573 , L572 , XXREAL_0:2;
end;
L575:
now
let C196 being Real;
assume L576: C196 in ( PreNorms C192 );
L577: (ex B99 being (Element of R1) st C196 = ( abs ( C192 . B99 ) )) by L576;
thus L578: C196 <= ( ||. R19 .|| + ||. R20 .|| ) by L577 , L570;
end;
L579: ((for B100 being  real number holds (B100 in ( PreNorms C192 ) implies B100 <= ( ||. R19 .|| + ||. R20 .|| ))) implies ( upper_bound ( PreNorms C192 ) ) <= ( ||. R19 .|| + ||. R20 .|| )) by SEQ_4:45;
thus L580: thesis by L579 , L562 , L563 , L575 , L409;
end;
L581: ||. ( R12 * R19 ) .|| = ( ( abs R12 ) * ||. R19 .|| )
proof
L582: R19 in ( BoundedFunctions R1 );
consider C197 being (Function of R1 , ( REAL )) such that L583: C197 = R19 and L584: ( C197 | R1 ) is  bounded by L582;
L585: ( R12 * R19 ) in ( BoundedFunctions R1 );
consider C198 being (Function of R1 , ( REAL )) such that L586: C198 = ( R12 * R19 ) and L587: ( C198 | R1 ) is  bounded by L585;
L588:
now
let C199 being (Element of R1);
L589: ( abs ( C198 . C199 ) ) = ( abs ( R12 * ( C197 . C199 ) ) ) by L583 , L586 , L534;
L590: ( abs ( C198 . C199 ) ) = ( ( abs R12 ) * ( abs ( C197 . C199 ) ) ) by L589 , COMPLEX1:65;
L591: ( 0 ) <= ( abs R12 ) by COMPLEX1:46;
thus L592: ( abs ( C198 . C199 ) ) <= ( ( abs R12 ) * ||. R19 .|| ) by L591 , L583 , L584 , L590 , L493 , XREAL_1:64;
end;
L593:
now
let C200 being Real;
assume L594: C200 in ( PreNorms C198 );
L595: (ex B101 being (Element of R1) st C200 = ( abs ( C198 . B101 ) )) by L594;
thus L596: C200 <= ( ( abs R12 ) * ||. R19 .|| ) by L595 , L588;
end;
L597: ((for B102 being  real number holds (B102 in ( PreNorms C198 ) implies B102 <= ( ( abs R12 ) * ||. R19 .|| ))) implies ( upper_bound ( PreNorms C198 ) ) <= ( ( abs R12 ) * ||. R19 .|| )) by SEQ_4:45;
L598: ||. ( R12 * R19 ) .|| <= ( ( abs R12 ) * ||. R19 .|| ) by L597 , L586 , L587 , L593 , L409;
per cases ;
suppose L599: R12 <> ( 0 );

L600:
now
let C201 being (Element of R1);
L601: ( abs ( R12 " ) ) = ( abs ( 1 / R12 ) );
L602: ( abs ( R12 " ) ) = ( 1 / ( abs R12 ) ) by L601 , ABSVALUE:7;
L603: ( C198 . C201 ) = ( R12 * ( C197 . C201 ) ) by L583 , L586 , L534;
L604: ( ( R12 " ) * ( C198 . C201 ) ) = ( ( ( R12 " ) * R12 ) * ( C197 . C201 ) ) by L603;
L605: ( ( R12 " ) * ( C198 . C201 ) ) = ( 1 * ( C197 . C201 ) ) by L604 , L599 , XCMPLX_0:def 7;
L606: (( abs ( ( R12 " ) * ( C198 . C201 ) ) ) = ( ( abs ( R12 " ) ) * ( abs ( C198 . C201 ) ) ) & ( 0 ) <= ( abs ( R12 " ) )) by COMPLEX1:46 , COMPLEX1:65;
thus L607: ( abs ( C197 . C201 ) ) <= ( ( ( abs R12 ) " ) * ||. ( R12 * R19 ) .|| ) by L606 , L586 , L587 , L605 , L602 , L493 , XREAL_1:64;
end;
L608:
now
let C202 being Real;
assume L609: C202 in ( PreNorms C197 );
L610: (ex B103 being (Element of R1) st C202 = ( abs ( C197 . B103 ) )) by L609;
thus L611: C202 <= ( ( ( abs R12 ) " ) * ||. ( R12 * R19 ) .|| ) by L610 , L600;
end;
L612: ( 0 ) <= ( abs R12 ) by COMPLEX1:46;
L613: ((for B104 being  real number holds (B104 in ( PreNorms C197 ) implies B104 <= ( ( ( abs R12 ) " ) * ||. ( R12 * R19 ) .|| ))) implies ( upper_bound ( PreNorms C197 ) ) <= ( ( ( abs R12 ) " ) * ||. ( R12 * R19 ) .|| )) by SEQ_4:45;
L614: ||. R19 .|| <= ( ( ( abs R12 ) " ) * ||. ( R12 * R19 ) .|| ) by L613 , L583 , L584 , L608 , L409;
L615: ( ( abs R12 ) * ||. R19 .|| ) <= ( ( abs R12 ) * ( ( ( abs R12 ) " ) * ||. ( R12 * R19 ) .|| ) ) by L614 , L612 , XREAL_1:64;
L616: ( ( abs R12 ) * ||. R19 .|| ) <= ( ( ( abs R12 ) * ( ( abs R12 ) " ) ) * ||. ( R12 * R19 ) .|| ) by L615;
L617: ( abs R12 ) <> ( 0 ) by L599 , COMPLEX1:47;
L618: ( ( abs R12 ) * ||. R19 .|| ) <= ( 1 * ||. ( R12 * R19 ) .|| ) by L617 , L616 , XCMPLX_0:def 7;
thus L619: thesis by L618 , L598 , XXREAL_0:1;
end;
suppose L620: R12 = ( 0 );

reconsider D128 = R19 as (VECTOR of ( R_Algebra_of_BoundedFunctions R1 ));
L621: ( R12 * D128 ) = ( ( R12 + R12 ) * D128 ) by L620
.= ( ( R12 * D128 ) + ( R12 * D128 ) ) by RLVECT_1:def 6;
L622: ( 0. ( R_Algebra_of_BoundedFunctions R1 ) ) = ( ( - ( R12 * D128 ) ) + ( ( R12 * D128 ) + ( R12 * D128 ) ) ) by L621 , VECTSP_1:16;
L623: ( 0. ( R_Algebra_of_BoundedFunctions R1 ) ) = ( ( ( - ( R12 * D128 ) ) + ( R12 * D128 ) ) + ( R12 * D128 ) ) by L622 , RLVECT_1:def 3;
L624: ( 0. ( R_Algebra_of_BoundedFunctions R1 ) ) = ( ( 0. ( R_Algebra_of_BoundedFunctions R1 ) ) + ( R12 * D128 ) ) by L623 , VECTSP_1:16;
L625: ( R12 * R19 ) = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) by L624 , RLVECT_1:4;
L626: ( ( abs R12 ) * ||. R19 .|| ) = ( ( 0 ) * ||. R19 .|| ) by L620 , ABSVALUE:2;
thus L627: thesis by L626 , L625 , L513;
end;
end;
L629:
now
set D129 = ( R1 --> ( 0 ) );
reconsider D130 = D129 as (Function of R1 , ( REAL )) by FUNCOP_1:46;
L630: R19 in ( BoundedFunctions R1 );
consider C203 being (Function of R1 , ( REAL )) such that L631: R19 = C203 and L632: ( C203 | R1 ) is  bounded by L630;
assume L633: ||. R19 .|| = ( 0 );
L634:
now
let C204 being (Element of R1);
L635: ( abs ( C203 . C204 ) ) <= ||. R19 .|| by L631 , L632 , L493;
L636: ( abs ( C203 . C204 ) ) = ( 0 ) by L635 , L633 , COMPLEX1:46;
thus L637: ( C203 . C204 ) = ( 0 ) by L636 , ABSVALUE:2
.= ( D130 . C204 ) by FUNCOP_1:7;
end;
L638: C203 = D130 by L634 , FUNCT_2:63;
thus L639: R19 = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) by L638 , L631 , L490;
end;
thus L640: thesis by L629 , L543 , L581 , L560;
end;
theorem
L641: (for R1 being non  empty set holds ( R_Normed_Algebra_of_BoundedFunctions R1 ) is  reflexive  discerning  RealNormSpace-like)
proof
let R1 being non  empty set;
thus L642: ||. ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) .|| = ( 0 ) by L542;
L643: (for B105 , B106 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for B107 being Real holds ((||. B105 .|| = ( 0 ) iff B105 = ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) )) & ||. ( B107 * B105 ) .|| = ( ( abs B107 ) * ||. B105 .|| ) & ||. ( B105 + B106 ) .|| <= ( ||. B105 .|| + ||. B106 .|| )))) by L542;
thus L644: thesis by L643 , NORMSP_0:def 5 , NORMSP_1:def 1;
end;
registration
let C205 being non  empty set;
cluster ( R_Normed_Algebra_of_BoundedFunctions C205 ) ->  reflexive  discerning  RealNormSpace-like  vector-distributive  scalar-distributive  scalar-associative  scalar-unital  Abelian  add-associative  right_zeroed  right_complementable;
coherence by L487 , L641;
end;
theorem
L646: (for R1 being non  empty set holds (for R16 being (Function of R1 , ( REAL )) holds (for R17 being (Function of R1 , ( REAL )) holds (for R18 being (Function of R1 , ( REAL )) holds (for R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (for R21 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds ((R16 = R19 & R17 = R20 & R18 = R21) implies (R21 = ( R19 - R20 ) iff (for B108 being (Element of R1) holds ( R18 . B108 ) = ( ( R16 . B108 ) - ( R17 . B108 ) )))))))))))
proof
let R1 being non  empty set;
let R16 being (Function of R1 , ( REAL ));
let R17 being (Function of R1 , ( REAL ));
let R18 being (Function of R1 , ( REAL ));
let R19 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R20 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
let R21 being (Point of ( R_Normed_Algebra_of_BoundedFunctions R1 ));
assume L647: (R16 = R19 & R17 = R20 & R18 = R21);
L648:
now
assume L649: (for B109 being (Element of R1) holds ( R18 . B109 ) = ( ( R16 . B109 ) - ( R17 . B109 ) ));
L650:
now
let C206 being (Element of R1);
L651: ( R18 . C206 ) = ( ( R16 . C206 ) - ( R17 . C206 ) ) by L649;
thus L652: ( ( R18 . C206 ) + ( R17 . C206 ) ) = ( R16 . C206 ) by L651;
end;
L653: R19 = ( R21 + R20 ) by L650 , L647 , L530;
L654: ( R19 - R20 ) = ( R21 + ( R20 - R20 ) ) by L653 , RLVECT_1:def 3;
L655: ( R19 - R20 ) = ( R21 + ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) ) by L654 , RLVECT_1:15;
thus L656: ( R19 - R20 ) = R21 by L655 , RLVECT_1:4;
end;
L657:
now
assume L658: R21 = ( R19 - R20 );
L659: ( R21 + R20 ) = ( R19 - ( R20 - R20 ) ) by L658 , RLVECT_1:29;
L660: ( R21 + R20 ) = ( R19 - ( 0. ( R_Normed_Algebra_of_BoundedFunctions R1 ) ) ) by L659 , RLVECT_1:15;
L661: ( R21 + R20 ) = R19 by L660 , RLVECT_1:13;
L662:
now
let C207 being (Element of R1);
L663: ( R16 . C207 ) = ( ( R18 . C207 ) + ( R17 . C207 ) ) by L647 , L661 , L530;
thus L664: ( ( R16 . C207 ) - ( R17 . C207 ) ) = ( R18 . C207 ) by L663;
end;
thus L665: (for B110 being (Element of R1) holds ( R18 . B110 ) = ( ( R16 . B110 ) - ( R17 . B110 ) )) by L662;
end;
thus L666: thesis by L657 , L648;
end;
theorem
L667: (for B111 being non  empty set holds (for B112 being (sequence of ( R_Normed_Algebra_of_BoundedFunctions B111 )) holds (B112 is  Cauchy_sequence_by_Norm implies B112 is  convergent)))
proof
let C208 being non  empty set;
let C209 being (sequence of ( R_Normed_Algebra_of_BoundedFunctions C208 ));
defpred S1[ set , set ] means (ex B113 being Real_Sequence st ((for B114 being (Element of ( NAT )) holds ( B113 . B114 ) = ( ( modetrans (( C209 . B114 ) , C208) ) . $1 )) & B113 is  convergent & $2 = ( lim B113 )));
assume L668: C209 is  Cauchy_sequence_by_Norm;
L669: (for B115 being (Element of C208) holds (ex B116 being (Element of ( REAL )) st S1[ B115 , B116 ]))
proof
let C210 being (Element of C208);
deffunc H2((Element of ( NAT ))) = ( ( modetrans (( C209 . $1 ) , C208) ) . C210 );
consider C211 being Real_Sequence such that L670: (for B117 being (Element of ( NAT )) holds ( C211 . B117 ) = H2(B117)) from FUNCT_2:sch 4;
take ( lim C211 );
L671: (for B118 , B119 being (Element of ( NAT )) holds ( abs ( ( C211 . B118 ) - ( C211 . B119 ) ) ) <= ||. ( ( C209 . B118 ) - ( C209 . B119 ) ) .||)
proof
let C212 , C213 being (Element of ( NAT ));
L672: ( ( C209 . C212 ) - ( C209 . C213 ) ) in ( BoundedFunctions C208 );
consider C214 being (Function of C208 , ( REAL )) such that L673: C214 = ( ( C209 . C212 ) - ( C209 . C213 ) ) and L674: ( C214 | C208 ) is  bounded by L672;
L675: ( C209 . C212 ) in ( BoundedFunctions C208 );
L676: (ex B120 being (Function of C208 , ( REAL )) st (( C209 . C212 ) = B120 & ( B120 | C208 ) is  bounded)) by L675;
L677: ( modetrans (( C209 . C212 ) , C208) ) = ( C209 . C212 ) by L676 , L405;
L678: ( C209 . C213 ) in ( BoundedFunctions C208 );
L679: (ex B121 being (Function of C208 , ( REAL )) st (( C209 . C213 ) = B121 & ( B121 | C208 ) is  bounded)) by L678;
L680: ( modetrans (( C209 . C213 ) , C208) ) = ( C209 . C213 ) by L679 , L405;
L681: (( C211 . C212 ) = ( ( modetrans (( C209 . C212 ) , C208) ) . C210 ) & ( C211 . C213 ) = ( ( modetrans (( C209 . C213 ) , C208) ) . C210 )) by L670;
L682: ( ( C211 . C212 ) - ( C211 . C213 ) ) = ( C214 . C210 ) by L681 , L677 , L680 , L673 , L646;
thus L683: thesis by L682 , L673 , L674 , L493;
end;
L684:
now
let C215 being  real number;
assume that
L685: C215 > ( 0 );
L686: C215 is Real by XREAL_0:def 1;
consider C216 being (Element of ( NAT )) such that L687: (for B122 , B123 being (Element of ( NAT )) holds ((B122 >= C216 & B123 >= C216) implies ||. ( ( C209 . B122 ) - ( C209 . B123 ) ) .|| < C215)) by L686 , L668 , L685 , RSSPACE3:8;
take D131 = C216;
thus L688:now
let C217 being (Element of ( NAT ));
assume L689: C217 >= D131;
L690: ||. ( ( C209 . C217 ) - ( C209 . D131 ) ) .|| < C215 by L689 , L687;
L691: ( abs ( ( C211 . C217 ) - ( C211 . D131 ) ) ) <= ||. ( ( C209 . C217 ) - ( C209 . D131 ) ) .|| by L671;
thus L692: ( abs ( ( C211 . C217 ) - ( C211 . D131 ) ) ) < C215 by L691 , L690 , XXREAL_0:2;
end;
end;
L689: C211 is  convergent by L684 , SEQ_4:41;
thus L690: thesis by L689 , L670;
end;
consider C218 being (Function of C208 , ( REAL )) such that L691: (for B124 being (Element of C208) holds S1[ B124 , ( C218 . B124 ) ]) from FUNCT_2:sch 3(L669);
L692:
now
let C219 being  real number;
assume that
L693: C219 > ( 0 );
reconsider D132 = C219 as Real by XREAL_0:def 1;
consider C220 being (Element of ( NAT )) such that L694: (for B125 , B126 being (Element of ( NAT )) holds ((B125 >= C220 & B126 >= C220) implies ||. ( ( C209 . B125 ) - ( C209 . B126 ) ) .|| < D132)) by L668 , L693 , RSSPACE3:8;
take D133 = C220;
L695:
now
let C221 being (Element of ( NAT ));
L696: ||. ( C209 . C221 ) .|| = ( ||. C209 .|| . C221 ) by NORMSP_0:def 4;
assume L697: C221 >= D133;
L698: ||. ( ( C209 . C221 ) - ( C209 . D133 ) ) .|| < D132 by L697 , L694;
L699: (( abs ( ||. ( C209 . C221 ) .|| - ||. ( C209 . D133 ) .|| ) ) <= ||. ( ( C209 . C221 ) - ( C209 . D133 ) ) .|| & ||. ( C209 . D133 ) .|| = ( ||. C209 .|| . D133 )) by NORMSP_0:def 4 , NORMSP_1:9;
thus L700: ( abs ( ( ||. C209 .|| . C221 ) - ( ||. C209 .|| . D133 ) ) ) < C219 by L699 , L698 , L696 , XXREAL_0:2;
end;
thus L701: (for B127 being (Element of ( NAT )) holds (B127 >= D133 implies ( abs ( ( ||. C209 .|| . B127 ) - ( ||. C209 .|| . D133 ) ) ) < C219)) by L695;
end;
L702: ||. C209 .|| is  convergent by L692 , SEQ_4:41;
L703:
now
let C222 being set;
assume L704: C222 in ( C208 /\ ( dom C218 ) );
consider C223 being Real_Sequence such that L705: (for B128 being (Element of ( NAT )) holds ( C223 . B128 ) = ( ( modetrans (( C209 . B128 ) , C208) ) . C222 )) and L706: (C223 is  convergent & ( C218 . C222 ) = ( lim C223 )) by L704 , L691;
L707: (for B129 being (Element of ( NAT )) holds ( ( abs C223 ) . B129 ) <= ( ||. C209 .|| . B129 ))
proof
let C224 being (Element of ( NAT ));
L708: ( C223 . C224 ) = ( ( modetrans (( C209 . C224 ) , C208) ) . C222 ) by L705;
L709: ( C209 . C224 ) in ( BoundedFunctions C208 );
L710: (ex B130 being (Function of C208 , ( REAL )) st (( C209 . C224 ) = B130 & ( B130 | C208 ) is  bounded)) by L709;
L711: ( modetrans (( C209 . C224 ) , C208) ) = ( C209 . C224 ) by L710 , L405;
L712: ( abs ( C223 . C224 ) ) <= ||. ( C209 . C224 ) .|| by L711 , L704 , L710 , L708 , L493;
L713: ( ( abs C223 ) . C224 ) <= ||. ( C209 . C224 ) .|| by L712 , VALUED_1:18;
thus L714: thesis by L713 , NORMSP_0:def 4;
end;
L715: (( abs C223 ) is  convergent & ( abs ( C218 . C222 ) ) = ( lim ( abs C223 ) )) by L706 , SEQ_4:14;
thus L716: ( abs ( C218 . C222 ) ) <= ( lim ||. C209 .|| ) by L715 , L702 , L707 , SEQ_2:18;
end;
L717: ( C218 | C208 ) is  bounded by L703 , RFUNCT_1:73;
L718: C218 in ( BoundedFunctions C208 ) by L717;
reconsider D134 = C218 as (Point of ( R_Normed_Algebra_of_BoundedFunctions C208 )) by L718;
L719: (for B131 being Real holds (B131 > ( 0 ) implies (ex B132 being (Element of ( NAT )) st (for B133 being (Element of ( NAT )) holds (B133 >= B132 implies (for B134 being (Element of C208) holds ( abs ( ( ( modetrans (( C209 . B133 ) , C208) ) . B134 ) - ( C218 . B134 ) ) ) <= B131))))))
proof
let C225 being Real;
assume L720: C225 > ( 0 );
consider C226 being (Element of ( NAT )) such that L721: (for B135 , B136 being (Element of ( NAT )) holds ((B135 >= C226 & B136 >= C226) implies ||. ( ( C209 . B135 ) - ( C209 . B136 ) ) .|| < C225)) by L720 , L668 , RSSPACE3:8;
take C226;
L722:
now
let C227 being (Element of ( NAT ));
assume that
L723: C227 >= C226;
L724:
now
let C228 being (Element of C208);
consider C229 being Real_Sequence such that L725: (for B137 being (Element of ( NAT )) holds ( C229 . B137 ) = ( ( modetrans (( C209 . B137 ) , C208) ) . C228 )) and L726: C229 is  convergent and L727: ( C218 . C228 ) = ( lim C229 ) by L691;
reconsider D135 = ( ( NAT ) --> ( C229 . C227 ) ) as Real_Sequence;
set D136 = ( C229 - D135 );
deffunc H3((Element of ( NAT ))) = ( abs ( ( C229 . $1 ) - ( C229 . C227 ) ) );
consider C230 being Real_Sequence such that L728: (for B138 being (Element of ( NAT )) holds ( C230 . B138 ) = H3(B138)) from SEQ_1:sch 1;
L729: (for B139 , B140 being (Element of ( NAT )) holds ( abs ( ( C229 . B139 ) - ( C229 . B140 ) ) ) <= ||. ( ( C209 . B139 ) - ( C209 . B140 ) ) .||)
proof
let C231 , C232 being (Element of ( NAT ));
L730: ( ( C209 . C231 ) - ( C209 . C232 ) ) in ( BoundedFunctions C208 );
consider C233 being (Function of C208 , ( REAL )) such that L731: C233 = ( ( C209 . C231 ) - ( C209 . C232 ) ) and L732: ( C233 | C208 ) is  bounded by L730;
L733: ( C209 . C231 ) in ( BoundedFunctions C208 );
L734: (ex B141 being (Function of C208 , ( REAL )) st (( C209 . C231 ) = B141 & ( B141 | C208 ) is  bounded)) by L733;
L735: ( modetrans (( C209 . C231 ) , C208) ) = ( C209 . C231 ) by L734 , L405;
L736: ( C209 . C232 ) in ( BoundedFunctions C208 );
L737: (ex B142 being (Function of C208 , ( REAL )) st (( C209 . C232 ) = B142 & ( B142 | C208 ) is  bounded)) by L736;
L738: ( modetrans (( C209 . C232 ) , C208) ) = ( C209 . C232 ) by L737 , L405;
L739: (( C229 . C231 ) = ( ( modetrans (( C209 . C231 ) , C208) ) . C228 ) & ( C229 . C232 ) = ( ( modetrans (( C209 . C232 ) , C208) ) . C228 )) by L725;
L740: ( ( C229 . C231 ) - ( C229 . C232 ) ) = ( C233 . C228 ) by L739 , L735 , L738 , L731 , L646;
thus L741: thesis by L740 , L731 , L732 , L493;
end;
L742: (for B143 being (Element of ( NAT )) holds (B143 >= C226 implies ( C230 . B143 ) <= C225))
proof
let C234 being (Element of ( NAT ));
assume L743: C234 >= C226;
L744: ||. ( ( C209 . C227 ) - ( C209 . C234 ) ) .|| < C225 by L743 , L721 , L723;
L745: ( C230 . C234 ) = ( abs ( ( C229 . C234 ) - ( C229 . C227 ) ) ) by L728;
L746: ( C230 . C234 ) = ( abs ( ( C229 . C227 ) - ( C229 . C234 ) ) ) by L745 , COMPLEX1:60;
L747: ( C230 . C234 ) <= ||. ( ( C209 . C227 ) - ( C209 . C234 ) ) .|| by L746 , L729;
thus L748: thesis by L747 , L744 , XXREAL_0:2;
end;
L749:
now
let C235 being (Element of ( NAT ));
L750: ( D136 . C235 ) = ( ( C229 . C235 ) + ( ( - D135 ) . C235 ) ) by SEQ_1:7;
L751: ( D136 . C235 ) = ( ( C229 . C235 ) + ( - ( D135 . C235 ) ) ) by L750 , SEQ_1:10;
thus L752: ( D136 . C235 ) = ( ( C229 . C235 ) - ( C229 . C227 ) ) by L751 , FUNCOP_1:7;
end;
L753:
now
let C236 being set;
assume L754: C236 in ( NAT );
reconsider D137 = C236 as (Element of ( NAT )) by L754;
L755: ( C230 . C236 ) = ( abs ( ( C229 . D137 ) - ( C229 . C227 ) ) ) by L728;
L756: ( C230 . C236 ) = ( abs ( D136 . D137 ) ) by L755 , L749;
thus L757: ( C230 . C236 ) = ( ( abs D136 ) . C236 ) by L756 , VALUED_1:18;
end;
L758: C230 = ( abs D136 ) by L753 , FUNCT_2:12;
L759: D136 is  convergent by L726 , SEQ_2:11;
L760: C230 is  convergent by L759 , L758;
L761: ( lim C230 ) <= C225 by L760 , L742 , RSSPACE2:5;
L762: ( lim D135 ) = ( D135 . ( 0 ) ) by SEQ_4:26;
L763: ( lim D135 ) = ( C229 . C227 ) by L762 , FUNCOP_1:7;
L764: ( lim D136 ) = ( ( C218 . C228 ) - ( C229 . C227 ) ) by L763 , L726 , L727 , SEQ_2:12;
L765: ( lim C230 ) = ( abs ( ( C218 . C228 ) - ( C229 . C227 ) ) ) by L764 , L759 , L758 , SEQ_4:14;
L766: ( abs ( ( C229 . C227 ) - ( C218 . C228 ) ) ) <= C225 by L765 , L761 , COMPLEX1:60;
thus L767: ( abs ( ( ( modetrans (( C209 . C227 ) , C208) ) . C228 ) - ( C218 . C228 ) ) ) <= C225 by L766 , L725;
end;
thus L768: (for B144 being (Element of C208) holds ( abs ( ( ( modetrans (( C209 . C227 ) , C208) ) . B144 ) - ( C218 . B144 ) ) ) <= C225) by L724;
end;
thus L769: thesis by L722;
end;
L770: (for B145 being Real holds (B145 > ( 0 ) implies (ex B146 being (Element of ( NAT )) st (for B147 being (Element of ( NAT )) holds (B147 >= B146 implies ||. ( ( C209 . B147 ) - D134 ) .|| <= B145)))))
proof
let C237 being Real;
assume L771: C237 > ( 0 );
consider C238 being (Element of ( NAT )) such that L772: (for B148 being (Element of ( NAT )) holds (B148 >= C238 implies (for B149 being (Element of C208) holds ( abs ( ( ( modetrans (( C209 . B148 ) , C208) ) . B149 ) - ( C218 . B149 ) ) ) <= C237))) by L771 , L719;
take C238;
thus L773:now
let C239 being (Element of ( NAT ));
assume that
L774: C239 >= C238;
L775: ( C209 . C239 ) in ( BoundedFunctions C208 );
consider C240 being (Function of C208 , ( REAL )) such that L776: C240 = ( C209 . C239 ) and L777: ( C240 | C208 ) is  bounded by L775;
L778: ( ( C209 . C239 ) - D134 ) in ( BoundedFunctions C208 );
consider C241 being (Function of C208 , ( REAL )) such that L779: C241 = ( ( C209 . C239 ) - D134 ) and L780: ( C241 | C208 ) is  bounded by L778;
L781:
now
let C242 being (Element of C208);
L782: (( modetrans (( C209 . C239 ) , C208) ) = C240 & ( C241 . C242 ) = ( ( C240 . C242 ) - ( C218 . C242 ) )) by L776 , L779 , L365 , L646;
thus L783: ( abs ( C241 . C242 ) ) <= C237 by L782 , L772 , L774;
end;
L784:
now
let C243 being Real;
assume L785: C243 in ( PreNorms C241 );
L786: (ex B150 being (Element of C208) st C243 = ( abs ( C241 . B150 ) )) by L785;
thus L787: C243 <= C237 by L786 , L781;
end;
L788: ((for B151 being  real number holds (B151 in ( PreNorms C241 ) implies B151 <= C237)) implies ( upper_bound ( PreNorms C241 ) ) <= C237) by SEQ_4:45;
thus L789: ||. ( ( C209 . C239 ) - D134 ) .|| <= C237 by L788 , L779 , L780 , L784 , L409;
end;
end;
L774: (for B152 being Real holds (B152 > ( 0 ) implies (ex B153 being (Element of ( NAT )) st (for B154 being (Element of ( NAT )) holds (B154 >= B153 implies ||. ( ( C209 . B154 ) - D134 ) .|| < B152)))))
proof
let C244 being Real;
assume that
L775: C244 > ( 0 );
consider C245 being (Element of ( NAT )) such that L776: (for B155 being (Element of ( NAT )) holds (B155 >= C245 implies ||. ( ( C209 . B155 ) - D134 ) .|| <= ( C244 / 2 ))) by L770 , L775 , XREAL_1:215;
take C245;
L777: ( C244 / 2 ) < C244 by L775 , XREAL_1:216;
thus L778:now
let C246 being (Element of ( NAT ));
assume L779: C246 >= C245;
L780: ||. ( ( C209 . C246 ) - D134 ) .|| <= ( C244 / 2 ) by L779 , L776;
thus L781: ||. ( ( C209 . C246 ) - D134 ) .|| < C244 by L780 , L777 , XXREAL_0:2;
end;
end;
thus L779: thesis by L774 , NORMSP_1:def 6;
end;
theorem
L780: (for R1 being non  empty set holds ( R_Normed_Algebra_of_BoundedFunctions R1 ) is RealBanachSpace)
proof
let R1 being non  empty set;
L781: (for B156 being (sequence of ( R_Normed_Algebra_of_BoundedFunctions R1 )) holds (B156 is  Cauchy_sequence_by_Norm implies B156 is  convergent)) by L667;
thus L782: thesis by L781 , LOPBAN_1:def 15;
end;
registration
let C247 being non  empty set;
cluster ( R_Normed_Algebra_of_BoundedFunctions C247 ) ->  complete;
coherence by L780;
end;
theorem
L784: (for R1 being non  empty set holds ( R_Normed_Algebra_of_BoundedFunctions R1 ) is Banach_Algebra)
proof
let R1 being non  empty set;
set D138 = ( R_Normed_Algebra_of_BoundedFunctions R1 );
reconsider D139 = D138 as non  empty Normed_Algebra by L481;
L785: ( 1. D139 ) in ( BoundedFunctions R1 );
consider C248 being (Function of R1 , ( REAL )) such that L786: C248 = ( 1. D139 ) and L787: ( C248 | R1 ) is  bounded by L785;
L788: ( 1. D139 ) = ( 1_ ( R_Algebra_of_BoundedFunctions R1 ) );
L789: ( 1. D139 ) = ( R1 --> 1 ) by L788 , L361;
L790: (for B157 being set holds (B157 in ( PreNorms C248 ) iff B157 = 1))
proof
set D140 = the (Element of R1);
let C249 being set;
L791: ( ( R1 --> 1 ) . D140 ) = 1 by FUNCOP_1:7;
thus L792:now
assume L793: C249 in ( PreNorms C248 );
consider C250 being (Element of R1) such that L794: C249 = ( abs ( ( R1 --> 1 ) . C250 ) ) by L793 , L786 , L789;
L795: ( ( R1 --> 1 ) . C250 ) = 1 by FUNCOP_1:7;
thus L796: C249 = 1 by L795 , L794 , COMPLEX1:48;
end;
assume L797: C249 = 1;
L798: C249 = ( abs ( ( R1 --> 1 ) . D140 ) ) by L797 , L791 , COMPLEX1:48;
thus L799: thesis by L798 , L786 , L789;
end;
L800: ( PreNorms C248 ) = { 1 } by L790 , TARSKI:def 1;
L801: ( upper_bound ( PreNorms C248 ) ) = 1 by L800 , SEQ_4:9;
L802: ||. ( 1. D139 ) .|| = 1 by L801 , L786 , L787 , L409;
L803:
now
let C251 being Real;
let C252 , C253 being (Element of D139);
L804: C252 in ( BoundedFunctions R1 );
consider C254 being (Function of R1 , ( REAL )) such that L805: C254 = C252 and L806: ( C254 | R1 ) is  bounded by L804;
L807: C253 in ( BoundedFunctions R1 );
consider C255 being (Function of R1 , ( REAL )) such that L808: C255 = C253 and L809: ( C255 | R1 ) is  bounded by L807;
L810: ( C251 * ( C252 * C253 ) ) in ( BoundedFunctions R1 );
consider C256 being (Function of R1 , ( REAL )) such that L811: C256 = ( C251 * ( C252 * C253 ) ) and L812: ( C256 | R1 ) is  bounded by L810;
L813: ( C252 * C253 ) in ( BoundedFunctions R1 );
consider C257 being (Function of R1 , ( REAL )) such that L814: C257 = ( C252 * C253 ) and L815: ( C257 | R1 ) is  bounded by L813;
L816: ( C251 * C253 ) in ( BoundedFunctions R1 );
consider C258 being (Function of R1 , ( REAL )) such that L817: C258 = ( C251 * C253 ) and L818: ( C258 | R1 ) is  bounded by L816;
L819:
now
let C259 being (Element of R1);
L820: ( C256 . C259 ) = ( C251 * ( C257 . C259 ) ) by L814 , L811 , L534;
L821: ( C256 . C259 ) = ( C251 * ( ( C254 . C259 ) * ( C255 . C259 ) ) ) by L820 , L805 , L808 , L814 , L538;
L822: ( C256 . C259 ) = ( ( C254 . C259 ) * ( C251 * ( C255 . C259 ) ) ) by L821;
thus L823: ( C256 . C259 ) = ( ( C254 . C259 ) * ( C258 . C259 ) ) by L822 , L808 , L817 , L534;
end;
thus L824: ( C251 * ( C252 * C253 ) ) = ( C252 * ( C251 * C253 ) ) by L819 , L805 , L817 , L811 , L538;
end;
L825:
now
let C260 , C261 being (Element of D139);
L826: C260 in ( BoundedFunctions R1 );
consider C262 being (Function of R1 , ( REAL )) such that L827: C262 = C260 and L828: ( C262 | R1 ) is  bounded by L826;
L829: C261 in ( BoundedFunctions R1 );
consider C263 being (Function of R1 , ( REAL )) such that L830: C263 = C261 and L831: ( C263 | R1 ) is  bounded by L829;
L832: ( PreNorms C263 ) is non  empty  bounded_above by L831 , L376;
L833: ( C260 * C261 ) in ( BoundedFunctions R1 );
consider C264 being (Function of R1 , ( REAL )) such that L834: C264 = ( C260 * C261 ) and L835: ( C264 | R1 ) is  bounded by L833;
L836: ( PreNorms C262 ) is non  empty  bounded_above by L828 , L376;
L837:
now
let C265 being  real number;
assume L838: C265 in ( PreNorms C264 );
consider C266 being (Element of R1) such that L839: C265 = ( abs ( C264 . C266 ) ) by L838;
L840: ( abs ( C263 . C266 ) ) in ( PreNorms C263 );
L841: ( abs ( C263 . C266 ) ) <= ( upper_bound ( PreNorms C263 ) ) by L840 , L832 , SEQ_4:def 1;
L842: ( abs ( C262 . C266 ) ) in ( PreNorms C262 );
L843: ( abs ( C262 . C266 ) ) <= ( upper_bound ( PreNorms C262 ) ) by L842 , L836 , SEQ_4:def 1;
L844: ( 0 ) <= ( upper_bound ( PreNorms C262 ) ) by L843 , COMPLEX1:46;
L845: ( ( upper_bound ( PreNorms C262 ) ) * ( abs ( C263 . C266 ) ) ) <= ( ( upper_bound ( PreNorms C262 ) ) * ( upper_bound ( PreNorms C263 ) ) ) by L844 , L841 , XREAL_1:64;
L846: ( 0 ) <= ( abs ( C263 . C266 ) ) by COMPLEX1:46;
L847: ( ( abs ( C262 . C266 ) ) * ( abs ( C263 . C266 ) ) ) <= ( ( upper_bound ( PreNorms C262 ) ) * ( abs ( C263 . C266 ) ) ) by L846 , L843 , XREAL_1:64;
L848: ( abs ( C264 . C266 ) ) = ( abs ( ( C262 . C266 ) * ( C263 . C266 ) ) ) by L827 , L830 , L834 , L538;
L849: ( abs ( C264 . C266 ) ) = ( ( abs ( C262 . C266 ) ) * ( abs ( C263 . C266 ) ) ) by L848 , COMPLEX1:65;
thus L850: C265 <= ( ( upper_bound ( PreNorms C262 ) ) * ( upper_bound ( PreNorms C263 ) ) ) by L849 , L839 , L847 , L845 , XXREAL_0:2;
end;
L851: ( upper_bound ( PreNorms C264 ) ) <= ( ( upper_bound ( PreNorms C262 ) ) * ( upper_bound ( PreNorms C263 ) ) ) by L837 , SEQ_4:45;
L852: ||. C261 .|| = ( upper_bound ( PreNorms C263 ) ) by L830 , L831 , L409;
L853: ||. C260 .|| = ( upper_bound ( PreNorms C262 ) ) by L827 , L828 , L409;
thus L854: ||. ( C260 * C261 ) .|| <= ( ||. C260 .|| * ||. C261 .|| ) by L853 , L834 , L835 , L852 , L851 , L409;
end;
L855:
now
let C267 , C268 , C269 being (Element of D139);
L856: C267 in ( BoundedFunctions R1 );
consider C270 being (Function of R1 , ( REAL )) such that L857: C270 = C267 and L858: ( C270 | R1 ) is  bounded by L856;
L859: C269 in ( BoundedFunctions R1 );
consider C271 being (Function of R1 , ( REAL )) such that L860: C271 = C269 and L861: ( C271 | R1 ) is  bounded by L859;
L862: C268 in ( BoundedFunctions R1 );
consider C272 being (Function of R1 , ( REAL )) such that L863: C272 = C268 and L864: ( C272 | R1 ) is  bounded by L862;
L865: ( ( C268 + C269 ) * C267 ) in ( BoundedFunctions R1 );
consider C273 being (Function of R1 , ( REAL )) such that L866: C273 = ( ( C268 + C269 ) * C267 ) and L867: ( C273 | R1 ) is  bounded by L865;
L868: ( C269 * C267 ) in ( BoundedFunctions R1 );
consider C274 being (Function of R1 , ( REAL )) such that L869: C274 = ( C269 * C267 ) and L870: ( C274 | R1 ) is  bounded by L868;
L871: ( C268 * C267 ) in ( BoundedFunctions R1 );
consider C275 being (Function of R1 , ( REAL )) such that L872: C275 = ( C268 * C267 ) and L873: ( C275 | R1 ) is  bounded by L871;
L874: ( C268 + C269 ) in ( BoundedFunctions R1 );
consider C276 being (Function of R1 , ( REAL )) such that L875: C276 = ( C268 + C269 ) and L876: ( C276 | R1 ) is  bounded by L874;
L877:
now
let C277 being (Element of R1);
L878: ( C273 . C277 ) = ( ( C276 . C277 ) * ( C270 . C277 ) ) by L857 , L875 , L866 , L538;
L879: ( C273 . C277 ) = ( ( ( C272 . C277 ) + ( C271 . C277 ) ) * ( C270 . C277 ) ) by L878 , L863 , L860 , L875 , L530;
L880: ( C273 . C277 ) = ( ( ( C272 . C277 ) * ( C270 . C277 ) ) + ( ( C271 . C277 ) * ( C270 . C277 ) ) ) by L879;
L881: ( C273 . C277 ) = ( ( C275 . C277 ) + ( ( C271 . C277 ) * ( C270 . C277 ) ) ) by L880 , L857 , L863 , L872 , L538;
thus L882: ( C273 . C277 ) = ( ( C275 . C277 ) + ( C274 . C277 ) ) by L881 , L857 , L860 , L869 , L538;
end;
thus L883: ( ( C268 + C269 ) * C267 ) = ( ( C268 * C267 ) + ( C269 * C267 ) ) by L877 , L872 , L869 , L866 , L530;
end;
L884: (for B158 being (Element of D139) holds ( ( 1. D139 ) * B158 ) = B158) by L416;
L885: D139 is  Banach_Algebra-like_1  Banach_Algebra-like_2  Banach_Algebra-like_3  left-distributive  left_unital  complete  Banach_Algebra-like_1  Banach_Algebra-like_2  Banach_Algebra-like_3  left-distributive  left_unital  complete  Banach_Algebra-like_1  Banach_Algebra-like_2  Banach_Algebra-like_3  left-distributive  left_unital  complete  Banach_Algebra-like_1  Banach_Algebra-like_2  Banach_Algebra-like_3  left-distributive  left_unital  complete Normed_Algebra by L884 , L825 , L802 , L803 , L855 , LOPBAN_2:def 9 , LOPBAN_2:def 10 , LOPBAN_2:def 11 , VECTSP_1:def 3 , VECTSP_1:def 8;
thus L886: thesis by L885;
end;
