:: The Collinearity Structure
::  by Wojciech Skaba
::
:: Received May 9, 1990
:: Copyright (c) 1990-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies TARSKI, ZFMISC_1, XBOOLE_0, SUBSET_1, STRUCT_0, PRE_TOPC,
      PARSP_2, RELAT_2, INCSP_1, NUMBERS, COLLSP;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, NUMBERS, DOMAIN_1, STRUCT_0,
      PRE_TOPC;
 constructors DOMAIN_1, NUMBERS, STRUCT_0;
 registrations XBOOLE_0, ORDINAL1, STRUCT_0;
 requirements NUMERALS, SUBSET, BOOLE;
 definitions TARSKI, STRUCT_0;
 theorems TARSKI, MCART_1, ENUMSET1, XBOOLE_0, XTUPLE_0;

begin
definition
let R1 being set;
mode Relation3 of R1
 -> set
means :L1: it c= [: R1 , R1 , R1 :];
existence;
end;
theorem
L3: (for R1 being set holds (R1 = ( {} ) or (ex B1 being set st ({ B1 } = R1 or (ex B2 , B3 being set st (B2 <> B3 & B2 in R1 & B3 in R1))))))
proof
let R1 being set;
L4:
now
set D1 = the (Element of R1);
assume L5: (R1 <> ( {} ) & (not (ex B4 , B5 being set st (B4 <> B5 & B4 in R1 & B5 in R1))));
L6: (for B6 being set holds (B6 in R1 iff B6 = D1)) by L5;
L7: R1 = { D1 } by L6 , TARSKI:def 1;
thus L8: (ex B7 being set st { B7 } = R1) by L7;
end;
thus L9: thesis by L4;
end;
definition
struct (1-sorted) CollStr(# carrier -> set , Collinearity -> (Relation3 of the carrier) #);
end;
registration
cluster non  empty  strict for CollStr;
existence
proof
set D2 = the non  empty set;
set D3 = the (Relation3 of D2);
take CollStr (# D2 , D3 #);
thus L11: (the carrier of CollStr (# D2 , D3 #)) is non  empty;
thus L12: thesis;
end;
end;
definition
let R2 being non  empty CollStr;
let R3 being (Point of R2);
let R4 being (Point of R2);
let R5 being (Point of R2);
pred R3 , R4 , R5 is_collinear 
means
:L14: [ R3 , R4 , R5 ] in (the Collinearity of R2)
;end;
set D4 = { 1 };
L16: 1 in D4 by TARSKI:def 1;
L17: { [ 1 , 1 , 1 ] } c= [: { 1 } , { 1 } , { 1 } :]
proof
L18:
now
let C1 being set;
assume L19: C1 in { [ 1 , 1 , 1 ] };
L20: C1 = [ 1 , 1 , 1 ] by L19 , TARSKI:def 1;
thus L21: C1 in [: { 1 } , { 1 } , { 1 } :] by L20 , L16 , MCART_1:69;
end;
thus L22: thesis by L18 , TARSKI:def 3;
end;
reconsider D5 = D4 as non  empty set;
reconsider D6 = { [ 1 , 1 , 1 ] } as (Relation3 of D5) by L1 , L17;
reconsider D7 = CollStr (# D5 , D6 #) as non  empty CollStr;
L23:
now
let C2 , C3 , C4 , C5 , C6 , C7 being (Point of D7);
L24: (for B8 , B9 , B10 being (Point of D7) holds [ B8 , B9 , B10 ] in (the Collinearity of D7))
proof
let C8 , C9 , C10 being (Point of D7);
L25: C10 = 1 by TARSKI:def 1;
L26: (C8 = 1 & C9 = 1) by TARSKI:def 1;
thus L27: thesis by L26 , L25 , TARSKI:def 1;
end;
thus L28: ((C2 = C3 or C2 = C4 or C3 = C4) implies [ C2 , C3 , C4 ] in (the Collinearity of D7)) by L24;
thus L29: ((C2 <> C3 & [ C2 , C3 , C5 ] in (the Collinearity of D7) & [ C2 , C3 , C6 ] in (the Collinearity of D7) & [ C2 , C3 , C7 ] in (the Collinearity of D7)) implies [ C5 , C6 , C7 ] in (the Collinearity of D7)) by L24;
end;
definition
let C11 being non  empty CollStr;
attr C11 is  reflexive
means
:L30: (for B11 , B12 , B13 being (Point of C11) holds ((B11 = B12 or B11 = B13 or B12 = B13) implies [ B11 , B12 , B13 ] in (the Collinearity of C11)));
end;
definition
let C12 being non  empty CollStr;
attr C12 is  transitive
means
:L32: (for B14 , B15 , B16 , B17 , B18 being (Point of C12) holds ((B14 <> B15 & [ B14 , B15 , B16 ] in (the Collinearity of C12) & [ B14 , B15 , B17 ] in (the Collinearity of C12) & [ B14 , B15 , B18 ] in (the Collinearity of C12)) implies [ B16 , B17 , B18 ] in (the Collinearity of C12)));
end;
registration
cluster  strict  reflexive  transitive for non  empty non  empty non  empty non  empty CollStr;
existence
proof
take D7;
thus L34: thesis by L30 , L32 , L23;
end;
end;
definition
mode CollSp
 is  reflexive  transitive non  empty CollStr;
end;
theorem
L37: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R9 being (Point of R6) holds ((R7 = R8 or R7 = R9 or R8 = R9) implies R7 , R8 , R9 is_collinear )))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R9 being (Point of R6);
assume L38: (R7 = R8 or R7 = R9 or R8 = R9);
L39: [ R7 , R8 , R9 ] in (the Collinearity of R6) by L38 , L30;
thus L40: thesis by L39 , L14;
end;
theorem
L41: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R11 being (Point of R6) holds (for R12 being (Point of R6) holds (for R13 being (Point of R6) holds ((R7 <> R8 & R7 , R8 , R11 is_collinear  & R7 , R8 , R12 is_collinear  & R7 , R8 , R13 is_collinear ) implies R11 , R12 , R13 is_collinear )))))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R11 being (Point of R6);
let R12 being (Point of R6);
let R13 being (Point of R6);
assume that
L42: R7 <> R8
and
L43: (R7 , R8 , R11 is_collinear  & R7 , R8 , R12 is_collinear )
and
L44: R7 , R8 , R13 is_collinear ;
L45: [ R7 , R8 , R13 ] in (the Collinearity of R6) by L44 , L14;
L46: ([ R7 , R8 , R11 ] in (the Collinearity of R6) & [ R7 , R8 , R12 ] in (the Collinearity of R6)) by L43 , L14;
L47: [ R11 , R12 , R13 ] in (the Collinearity of R6) by L46 , L42 , L45 , L32;
thus L48: thesis by L47 , L14;
end;
theorem
L49: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R9 being (Point of R6) holds (R7 , R8 , R9 is_collinear  implies (R8 , R7 , R9 is_collinear  & R7 , R9 , R8 is_collinear ))))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R9 being (Point of R6);
assume L50: R7 , R8 , R9 is_collinear ;
L51: (R7 = R8 or (R7 <> R8 & R7 , R8 , R8 is_collinear  & R7 , R8 , R7 is_collinear  & R7 , R8 , R9 is_collinear )) by L50 , L37;
thus L52: R8 , R7 , R9 is_collinear  by L51 , L37 , L41;
L53: (R7 = R8 or (R7 <> R8 & R7 , R8 , R7 is_collinear  & R7 , R8 , R9 is_collinear  & R7 , R8 , R8 is_collinear )) by L50 , L37;
thus L54: R7 , R9 , R8 is_collinear  by L53 , L37 , L41;
end;
theorem
L55: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds R7 , R8 , R7 is_collinear ))) by L37;
theorem
L56: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R9 being (Point of R6) holds (for R10 being (Point of R6) holds ((R7 <> R8 & R7 , R8 , R9 is_collinear  & R7 , R8 , R10 is_collinear ) implies R7 , R9 , R10 is_collinear ))))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R9 being (Point of R6);
let R10 being (Point of R6);
assume L57: (R7 <> R8 & R7 , R8 , R9 is_collinear  & R7 , R8 , R10 is_collinear );
L58: R7 , R8 , R7 is_collinear  by L37;
thus L59: thesis by L58 , L57 , L41;
end;
theorem
L60: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R9 being (Point of R6) holds (R7 , R8 , R9 is_collinear  implies R8 , R7 , R9 is_collinear ))))) by L49;
theorem
L61: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R9 being (Point of R6) holds (R7 , R8 , R9 is_collinear  implies R8 , R9 , R7 is_collinear )))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R9 being (Point of R6);
assume L62: R7 , R8 , R9 is_collinear ;
L63: R8 , R7 , R9 is_collinear  by L62 , L49;
thus L64: thesis by L63 , L49;
end;
theorem
L65: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R11 being (Point of R6) holds (for R12 being (Point of R6) holds (for R13 being (Point of R6) holds ((R11 <> R12 & R7 , R8 , R11 is_collinear  & R7 , R8 , R12 is_collinear  & R11 , R12 , R13 is_collinear ) implies R7 , R8 , R13 is_collinear )))))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R11 being (Point of R6);
let R12 being (Point of R6);
let R13 being (Point of R6);
assume that
L66: R11 <> R12
and
L67: (R7 , R8 , R11 is_collinear  & R7 , R8 , R12 is_collinear )
and
L68: R11 , R12 , R13 is_collinear ;
L69:
now
assume L70: R7 <> R8;
L71: R7 , R11 , R12 is_collinear  by L70 , L67 , L56;
L72: R11 , R12 , R7 is_collinear  by L71 , L61;
L73: R7 , R8 , R8 is_collinear  by L37;
L74: R11 , R12 , R8 is_collinear  by L73 , L67 , L70 , L41;
thus L75: thesis by L74 , L66 , L68 , L72 , L41;
end;
thus L76: thesis by L69 , L37;
end;
definition
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
func Line (R7 , R8) -> set equals 
{ R11 where R11 is (Point of R6) : R7 , R8 , R11 is_collinear  };
correctness;
end;
theorem
L78: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (R7 in ( Line (R7 , R8) ) & R8 in ( Line (R7 , R8) )))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
L79: R7 , R8 , R7 is_collinear  by L37;
thus L80: R7 in ( Line (R7 , R8) ) by L79;
L81: R7 , R8 , R8 is_collinear  by L37;
thus L82: R8 in ( Line (R7 , R8) ) by L81;
end;
theorem
L83: (for R6 being CollSp holds (for R7 being (Point of R6) holds (for R8 being (Point of R6) holds (for R13 being (Point of R6) holds (R7 , R8 , R13 is_collinear  iff R13 in ( Line (R7 , R8) ))))))
proof
let R6 being CollSp;
let R7 being (Point of R6);
let R8 being (Point of R6);
let R13 being (Point of R6);
thus L84: (R7 , R8 , R13 is_collinear  implies R13 in ( Line (R7 , R8) ));
thus L85: (R13 in ( Line (R7 , R8) ) implies R7 , R8 , R13 is_collinear )
proof
assume L86: R13 in ( Line (R7 , R8) );
L87: (ex R11 being (Point of R6) st (R13 = R11 & R7 , R8 , R11 is_collinear )) by L86;
thus L88: thesis by L87;
end;

end;
set D8 = { 1 , 2 , 3 };
set D9 = { [ R14 , R15 , R16 ] where R14 is (Element of ( NAT )) , R15 is (Element of ( NAT )) , R16 is (Element of ( NAT )) : ((R14 = R15 or R15 = R16 or R16 = R14) & R14 in D8 & R15 in D8 & R16 in D8) };
L86: D9 c= [: D8 , D8 , D8 :]
proof
L87:
now
let C13 being set;
assume L88: C13 in D9;
L89: (ex R14 being (Element of ( NAT )) st (ex R15 being (Element of ( NAT )) st (ex R16 being (Element of ( NAT )) st (C13 = [ R14 , R15 , R16 ] & (R14 = R15 or R15 = R16 or R16 = R14) & R14 in D8 & R15 in D8 & R16 in D8)))) by L88;
thus L90: C13 in [: D8 , D8 , D8 :] by L89 , MCART_1:69;
end;
thus L91: thesis by L87 , TARSKI:def 3;
end;
reconsider D10 = D8 as non  empty set by ENUMSET1:def 1;
reconsider D11 = D9 as (Relation3 of D10) by L1 , L86;
reconsider D12 = CollStr (# D10 , D11 #) as non  empty CollStr;
L92: (for B19 , B20 , B21 being (Point of D12) holds ([ B19 , B20 , B21 ] in D11 iff ((B19 = B20 or B20 = B21 or B21 = B19) & B19 in D10 & B20 in D10 & B21 in D10)))
proof
let C14 , C15 , C16 being (Point of D12);
thus L93: ([ C14 , C15 , C16 ] in D11 implies ((C14 = C15 or C15 = C16 or C16 = C14) & C14 in D10 & C15 in D10 & C16 in D10))
proof
assume L94: [ C14 , C15 , C16 ] in D11;
consider R14 being (Element of ( NAT )), R15 being (Element of ( NAT )), R16 being (Element of ( NAT )) such that L95: [ C14 , C15 , C16 ] = [ R14 , R15 , R16 ] and L96: (R14 = R15 or R15 = R16 or R16 = R14) and L97: R14 in D10 and L98: R15 in D10 and L99: R16 in D10 by L94;
L100: (C14 = R14 & C15 = R15) by L95 , XTUPLE_0:3;
thus L101: thesis by L100 , L95 , L96 , XTUPLE_0:3;
end;

thus L102: thesis;
end;
L103: (for B22 , B23 , B24 , B25 , B26 , B27 being (Point of D12) holds ((B22 <> B23 & [ B22 , B23 , B25 ] in (the Collinearity of D12) & [ B22 , B23 , B26 ] in (the Collinearity of D12) & [ B22 , B23 , B27 ] in (the Collinearity of D12)) implies [ B25 , B26 , B27 ] in (the Collinearity of D12)))
proof
let C17 , C18 , C19 , C20 , C21 , C22 being (Point of D12);
assume that
L104: C17 <> C18
and
L105: [ C17 , C18 , C20 ] in (the Collinearity of D12)
and
L106: [ C17 , C18 , C21 ] in (the Collinearity of D12)
and
L107: [ C17 , C18 , C22 ] in (the Collinearity of D12);
L108: (C17 = C21 or C18 = C21) by L104 , L106 , L92;
L109: (C17 = C22 or C18 = C22) by L104 , L107 , L92;
L110: (C20 in D10 & C21 in D10);
L111: C22 in D10;
L112: (C17 = C20 or C18 = C20) by L104 , L105 , L92;
thus L113: [ C20 , C21 , C22 ] in (the Collinearity of D12) by L112 , L108 , L109 , L110 , L111;
end;
L114: (ex B28 , B29 , B30 being (Point of D12) st (not B28 , B29 , B30 is_collinear ))
proof
reconsider D13 = 1 , D14 = 2 , D15 = 3 as (Point of D12) by ENUMSET1:def 1;
take D13;
take D14;
take D15;
L115: (not [ D13 , D14 , D15 ] in (the Collinearity of D12)) by L92;
thus L116: thesis by L115 , L14;
end;
L117: D12 is CollSp
proof
L118: (for B31 , B32 , B33 , B34 , B35 , B36 being (Point of D12) holds (((B31 = B32 or B31 = B33 or B32 = B33) implies [ B31 , B32 , B33 ] in (the Collinearity of D12)) & ((B31 <> B32 & [ B31 , B32 , B34 ] in (the Collinearity of D12) & [ B31 , B32 , B35 ] in (the Collinearity of D12) & [ B31 , B32 , B36 ] in (the Collinearity of D12)) implies [ B34 , B35 , B36 ] in (the Collinearity of D12)))) by L92 , L103;
thus L119: thesis by L118 , L30 , L32;
end;
definition
let C23 being non  empty CollStr;
attr C23 is  proper
means
:L120: (ex B37 , B38 , B39 being (Point of C23) st (not B37 , B38 , B39 is_collinear ));
end;
registration
cluster  strict  proper for CollSp;
existence
proof
reconsider D16 = D12 as CollSp by L117;
L122: D16 is  proper by L120 , L114;
thus L123: thesis by L122;
end;
end;
theorem
L125: (for R17 being  proper CollSp holds (for R21 being (Point of R17) holds (for R22 being (Point of R17) holds (R21 <> R22 implies (ex R23 being (Point of R17) st (not R21 , R22 , R23 is_collinear ))))))
proof
let R17 being  proper CollSp;
let R21 being (Point of R17);
let R22 being (Point of R17);
consider R18 being (Point of R17), R19 being (Point of R17), R20 being (Point of R17) such that L126: (not R18 , R19 , R20 is_collinear ) by L120;
assume L127: R21 <> R22;
L128: ((not R21 , R22 , R18 is_collinear ) or (not R21 , R22 , R19 is_collinear ) or (not R21 , R22 , R20 is_collinear )) by L127 , L126 , L41;
thus L129: thesis by L128;
end;
definition
let R17 being  proper CollSp;
mode LINE of R17
 -> set
means :L130: (ex R18 being (Point of R17) st (ex R19 being (Point of R17) st (R18 <> R19 & it = ( Line (R18 , R19) ))));
existence
proof
consider R18 being (Point of R17), R19 being (Point of R17), R20 being (Point of R17) such that L131: (not R18 , R19 , R20 is_collinear ) by L120;
take ( Line (R18 , R19) );
L132: R18 <> R19 by L131 , L37;
thus L133: thesis by L132;
end;
end;
theorem
L135: (for R17 being  proper CollSp holds (for R18 being (Point of R17) holds (for R19 being (Point of R17) holds (R18 = R19 implies ( Line (R18 , R19) ) = (the carrier of R17)))))
proof
let R17 being  proper CollSp;
let R18 being (Point of R17);
let R19 being (Point of R17);
assume L136: R18 = R19;
L137: (for B40 being set holds (B40 in ( Line (R18 , R19) ) iff B40 in (the carrier of R17)))
proof
let C24 being set;
thus L138: (C24 in ( Line (R18 , R19) ) implies C24 in (the carrier of R17))
proof
assume L139: C24 in ( Line (R18 , R19) );
L140: (ex R21 being (Point of R17) st (C24 = R21 & R18 , R19 , R21 is_collinear )) by L139;
reconsider D17 = C24 as (Point of R17) by L140;
L141: D17 is (Element of R17);
thus L142: thesis by L141;
end;

thus L143: (C24 in (the carrier of R17) implies C24 in ( Line (R18 , R19) ))
proof
assume L144: C24 in (the carrier of R17);
reconsider D18 = C24 as (Point of R17) by L144;
L145: R18 , R19 , D18 is_collinear  by L136 , L37;
thus L146: thesis by L145;
end;

end;
thus L144: thesis by L137 , TARSKI:1;
end;
theorem
L145: (for R17 being  proper CollSp holds (for R24 being (LINE of R17) holds (ex R18 being (Point of R17) st (ex R19 being (Point of R17) st (R18 <> R19 & R18 in R24 & R19 in R24)))))
proof
let R17 being  proper CollSp;
let R24 being (LINE of R17);
consider R18 being (Point of R17), R19 being (Point of R17) such that L146: (R18 <> R19 & R24 = ( Line (R18 , R19) )) by L130;
take R18;
take R19;
thus L147: thesis by L146 , L78;
end;
theorem
L148: (for R17 being  proper CollSp holds (for R18 being (Point of R17) holds (for R19 being (Point of R17) holds (R18 <> R19 implies (ex R24 being (LINE of R17) st (R18 in R24 & R19 in R24))))))
proof
let R17 being  proper CollSp;
let R18 being (Point of R17);
let R19 being (Point of R17);
assume L149: R18 <> R19;
reconsider D19 = ( Line (R18 , R19) ) as (LINE of R17) by L149 , L130;
take D19;
thus L150: thesis by L78;
end;
theorem
L151: (for R17 being  proper CollSp holds (for R21 being (Point of R17) holds (for R22 being (Point of R17) holds (for R23 being (Point of R17) holds (for R24 being (LINE of R17) holds ((R21 in R24 & R22 in R24 & R23 in R24) implies R21 , R22 , R23 is_collinear ))))))
proof
let R17 being  proper CollSp;
let R21 being (Point of R17);
let R22 being (Point of R17);
let R23 being (Point of R17);
let R24 being (LINE of R17);
assume that
L152: (R21 in R24 & R22 in R24)
and
L153: R23 in R24;
consider R18 being (Point of R17), R19 being (Point of R17) such that L154: R18 <> R19 and L155: R24 = ( Line (R18 , R19) ) by L130;
L156: (ex B41 being (Point of R17) st (B41 = R23 & R18 , R19 , B41 is_collinear )) by L153 , L155;
L157: ((ex B42 being (Point of R17) st (B42 = R21 & R18 , R19 , B42 is_collinear )) & (ex B43 being (Point of R17) st (B43 = R22 & R18 , R19 , B43 is_collinear ))) by L152 , L155;
thus L158: thesis by L157 , L154 , L156 , L41;
end;
L159: (for R17 being  proper CollSp holds (for R24 being (LINE of R17) holds (for B44 being set holds (B44 in R24 implies B44 is (Point of R17)))))
proof
let R17 being  proper CollSp;
let R24 being (LINE of R17);
let C25 being set;
consider R18 being (Point of R17), R19 being (Point of R17) such that L160: R18 <> R19 and L161: R24 = ( Line (R18 , R19) ) by L130;
assume L162: C25 in R24;
L163: (ex B45 being (Point of R17) st (B45 = C25 & R18 , R19 , B45 is_collinear )) by L162 , L161;
thus L164: thesis by L163;
end;
theorem
L165: (for R17 being  proper CollSp holds (for R24 being (LINE of R17) holds (for R25 being (LINE of R17) holds (R24 c= R25 implies R24 = R25))))
proof
let R17 being  proper CollSp;
let R24 being (LINE of R17);
let R25 being (LINE of R17);
assume L166: R24 c= R25;
L167: R25 c= R24
proof
let C26 being set;
consider R21 being (Point of R17), R22 being (Point of R17) such that L168: R21 <> R22 and L169: R24 = ( Line (R21 , R22) ) by L130;
assume L170: C26 in R25;
reconsider D20 = C26 as (Point of R17) by L170 , L159;
L171: (R21 in R24 & R22 in R24) by L169 , L78;
L172: R21 , R22 , D20 is_collinear  by L171 , L166 , L170 , L151;
thus L173: thesis by L172 , L169;
end;
thus L174: thesis by L167 , L166 , XBOOLE_0:def 10;
end;
theorem
L175: (for R17 being  proper CollSp holds (for R21 being (Point of R17) holds (for R22 being (Point of R17) holds (for R24 being (LINE of R17) holds ((R21 <> R22 & R21 in R24 & R22 in R24) implies ( Line (R21 , R22) ) c= R24)))))
proof
let R17 being  proper CollSp;
let R21 being (Point of R17);
let R22 being (Point of R17);
let R24 being (LINE of R17);
assume that
L176: R21 <> R22
and
L177: (R21 in R24 & R22 in R24);
let C27 being set;
consider R18 being (Point of R17), R19 being (Point of R17) such that L178: R18 <> R19 and L179: R24 = ( Line (R18 , R19) ) by L130;
assume L180: C27 in ( Line (R21 , R22) );
consider C28 being (Point of R17) such that L181: C28 = C27 and L182: R21 , R22 , C28 is_collinear  by L180;
L183: (R18 , R19 , R21 is_collinear  & R18 , R19 , R22 is_collinear ) by L177 , L179 , L83;
L184: R18 , R19 , C28 is_collinear  by L183 , L176 , L182 , L65;
thus L185: thesis by L184 , L179 , L181;
end;
theorem
L186: (for R17 being  proper CollSp holds (for R21 being (Point of R17) holds (for R22 being (Point of R17) holds (for R24 being (LINE of R17) holds ((R21 <> R22 & R21 in R24 & R22 in R24) implies ( Line (R21 , R22) ) = R24)))))
proof
let R17 being  proper CollSp;
let R21 being (Point of R17);
let R22 being (Point of R17);
let R24 being (LINE of R17);
assume that
L187: R21 <> R22
and
L188: (R21 in R24 & R22 in R24);
reconsider D21 = ( Line (R21 , R22) ) as (LINE of R17) by L187 , L130;
L189: D21 c= R24 by L187 , L188 , L175;
thus L190: thesis by L189 , L165;
end;
theorem
L191: (for R17 being  proper CollSp holds (for R21 being (Point of R17) holds (for R22 being (Point of R17) holds (for R24 being (LINE of R17) holds (for R25 being (LINE of R17) holds ((R21 <> R22 & R21 in R24 & R22 in R24 & R21 in R25 & R22 in R25) implies R24 = R25))))))
proof
let R17 being  proper CollSp;
let R21 being (Point of R17);
let R22 being (Point of R17);
let R24 being (LINE of R17);
let R25 being (LINE of R17);
assume that
L192: R21 <> R22
and
L193: (R21 in R24 & R22 in R24)
and
L194: (R21 in R25 & R22 in R25);
L195: ( Line (R21 , R22) ) = R24 by L192 , L193 , L186;
thus L196: thesis by L195 , L192 , L194 , L186;
end;
theorem
L197: (for R17 being  proper CollSp holds (for R24 being (LINE of R17) holds (for R25 being (LINE of R17) holds (R24 = R25 or R24 misses R25 or (ex R21 being (Point of R17) st ( R24 /\ R25 ) = { R21 })))))
proof
let R17 being  proper CollSp;
let R24 being (LINE of R17);
let R25 being (LINE of R17);
L198: ((ex B46 being set st { B46 } = ( R24 /\ R25 )) implies (ex R21 being (Point of R17) st ( R24 /\ R25 ) = { R21 }))
proof
given C29 being set such that
L199: { C29 } = ( R24 /\ R25 );

L200: C29 in ( R24 /\ R25 ) by L199 , TARSKI:def 1;
L201: C29 in R24 by L200 , XBOOLE_0:def 4;
reconsider D22 = C29 as (Point of R17) by L201 , L159;
L202: ( R24 /\ R25 ) = { D22 } by L199;
thus L203: thesis by L202;
end;
L204: ((ex B47 , B48 being set st (B47 <> B48 & B47 in ( R24 /\ R25 ) & B48 in ( R24 /\ R25 ))) implies R24 = R25)
proof
given C30 , C31 being set such that
L205: C30 <> C31
and
L206: (C30 in ( R24 /\ R25 ) & C31 in ( R24 /\ R25 ));

L207: (C30 in R24 & C31 in R24) by L206 , XBOOLE_0:def 4;
reconsider D23 = C30 , D24 = C31 as (Point of R17) by L207 , L159;
L208: (D23 in R25 & D24 in R25) by L206 , XBOOLE_0:def 4;
L209: (D23 in R24 & D24 in R24) by L206 , XBOOLE_0:def 4;
thus L210: thesis by L209 , L205 , L208 , L191;
end;
L211: (( R24 /\ R25 ) = ( {} ) or (ex B49 being set st ({ B49 } = ( R24 /\ R25 ) or (ex B50 , B51 being set st (B50 <> B51 & B50 in ( R24 /\ R25 ) & B51 in ( R24 /\ R25 )))))) by L3;
thus L212: thesis by L211 , L198 , L204 , XBOOLE_0:def 7;
end;
theorem
L213: (for R17 being  proper CollSp holds (for R18 being (Point of R17) holds (for R19 being (Point of R17) holds (R18 <> R19 implies ( Line (R18 , R19) ) <> (the carrier of R17)))))
proof
let R17 being  proper CollSp;
let R18 being (Point of R17);
let R19 being (Point of R17);
assume L214: R18 <> R19;
L215: (ex R23 being (Point of R17) st (not R18 , R19 , R23 is_collinear )) by L214 , L125;
thus L216: thesis by L215 , L83;
end;
