:: The Inner Product and Conjugate of Finite Sequences of Complex Numbers
::  by Wenpai Chang , Hiroshi Yamazaki and Yatsuka Nakamura
::
:: Received April 25, 2005
:: Copyright (c) 2005-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies SUBSET_1, NUMBERS, FINSEQ_1, FINSEQ_2, ARYTM_3, NAT_1, XXREAL_0,
      FUNCT_1, RELAT_1, TARSKI, BINOP_2, FUNCOP_1, ARYTM_1, XCMPLX_0, ORDINAL1,
      CARD_1, COMPLEX1, RVSUM_1, REAL_1, ZFMISC_1, VALUED_0;
 notations TARSKI, SUBSET_1, NUMBERS, XCMPLX_0, REAL_1, ORDINAL1, RELAT_1,
      FUNCT_1, FUNCT_2, ZFMISC_1, PARTFUN1, BINOP_1, FUNCOP_1, FINSEQ_1,
      FINSEQOP, VALUED_0, VALUED_1, SEQ_4, COMPLEX1, RVSUM_1, FINSEQ_2,
      BINOP_2, MATRIX_5, XXREAL_0, SEQ_1;
 constructors SETWISEO, REAL_1, BINOP_2, FINSEQOP, SEQ_4, MATRIX_5, SEQ_1,
      BINOP_1, RVSUM_1, RELSET_1;
 registrations XBOOLE_0, FUNCT_1, RELSET_1, FUNCT_2, NUMBERS, XCMPLX_0,
      BINOP_2, MEMBERED, FINSEQ_2, XXREAL_0, VALUED_0, FINSEQ_1, VALUED_1;
 requirements NUMERALS, BOOLE, SUBSET, ARITHM;
 definitions TARSKI, VALUED_1;
 theorems FUNCT_1, FUNCT_2, FINSEQ_1, FUNCOP_1, FINSEQ_2, FINSEQOP, RELAT_1,
      BINOP_2, COMPLEX1, XCMPLX_0, FINSEQ_3, RVSUM_1, ORDINAL1, VALUED_0,
      VALUED_1, SEQ_4, CARD_1;
 schemes FINSEQ_1;

begin
definition
let C1 being (FinSequence of ( COMPLEX ));
func C1 *' -> (FinSequence of ( COMPLEX )) means 
:L1: (( len it ) = ( len C1 ) & (for B1 being Nat holds ((1 <= B1 & B1 <= ( len C1 )) implies ( it . B1 ) = ( ( C1 . B1 ) *' ))));
existence
proof
deffunc H1(Nat) = ( ( C1 . $1 ) *' );
consider C2 being FinSequence such that L2: (( len C2 ) = ( len C1 ) & (for B2 being Nat holds (B2 in ( dom C2 ) implies ( C2 . B2 ) = H1(B2)))) from FINSEQ_1:sch 2;
L3: ( rng C2 ) c= ( COMPLEX )
proof
let C3 being set;
assume L4: C3 in ( rng C2 );
consider C4 being set such that L5: C4 in ( dom C2 ) and L6: C3 = ( C2 . C4 ) by L4 , FUNCT_1:def 3;
reconsider D1 = C4 as (Element of ( NAT )) by L5;
L7: ( C2 . D1 ) = ( ( C1 . D1 ) *' ) by L2 , L5;
thus L8: thesis by L7 , L6;
end;
L9: C2 is (FinSequence of ( COMPLEX )) by L3 , FINSEQ_1:def 4;
L10: (for B3 being Nat holds ((1 <= B3 & B3 <= ( len C1 )) implies ( ( C1 . B3 ) *' ) = ( C2 . B3 )))
proof
let C5 being Nat;
assume L11: (1 <= C5 & C5 <= ( len C1 ));
L12: C5 in ( dom C2 ) by L11 , L2 , FINSEQ_3:25;
thus L13: thesis by L12 , L2;
end;
thus L14: thesis by L10 , L2 , L9;
end;
uniqueness
proof
let C6 , C7 being (FinSequence of ( COMPLEX ));
assume that
L15: ( len C6 ) = ( len C1 )
and
L16: (for B4 being Nat holds ((1 <= B4 & B4 <= ( len C1 )) implies ( ( C1 . B4 ) *' ) = ( C6 . B4 )))
and
L17: ( len C7 ) = ( len C1 )
and
L18: (for B5 being Nat holds ((1 <= B5 & B5 <= ( len C1 )) implies ( ( C1 . B5 ) *' ) = ( C7 . B5 )));
L19: (for B6 being Nat holds ((1 <= B6 & B6 <= ( len C6 )) implies ( C6 . B6 ) = ( C7 . B6 )))
proof
let C8 being Nat;
assume L20: (1 <= C8 & C8 <= ( len C6 ));
L21: ( ( C1 . C8 ) *' ) = ( C6 . C8 ) by L20 , L15 , L16;
thus L22: thesis by L21 , L15 , L18 , L20;
end;
thus L23: thesis by L19 , L15 , L17 , FINSEQ_1:14;
end;
end;
L25: (for R3 being (FinSequence of ( COMPLEX )) holds (for R6 being (Element of ( COMPLEX )) holds ( R6 * R3 ) = ( ( ( multcomplex ) [;] (R6 , ( id ( COMPLEX ) )) ) * R3 )))
proof
let R3 being (FinSequence of ( COMPLEX ));
let R6 being (Element of ( COMPLEX ));
L26: ( R6 multcomplex ) = ( ( multcomplex ) [;] (R6 , ( id ( COMPLEX ) )) ) by SEQ_4:def 4;
thus L27: thesis by L26 , SEQ_4:def 9;
end;
theorem
L28: (for R1 being (Element of ( NAT )) holds (for R3 being (FinSequence of ( COMPLEX )) holds (for R4 being (FinSequence of ( COMPLEX )) holds (R1 in ( dom ( R3 + R4 ) ) implies ( ( R3 + R4 ) . R1 ) = ( ( R3 . R1 ) + ( R4 . R1 ) ))))) by VALUED_1:def 1;
theorem
L29: (for R1 being (Element of ( NAT )) holds (for R3 being (FinSequence of ( COMPLEX )) holds (for R4 being (FinSequence of ( COMPLEX )) holds (R1 in ( dom ( R3 - R4 ) ) implies ( ( R3 - R4 ) . R1 ) = ( ( R3 . R1 ) - ( R4 . R1 ) ))))) by VALUED_1:13;
definition
let R1 being (Element of ( NAT ));
let R8 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
let R9 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
redefine func R8 - R9 -> (Element of ( R1 -tuples_on ( COMPLEX ) ));

coherence
proof
L30: ( R8 - R9 ) = ( ( diffcomplex ) .: (R8 , R9) ) by SEQ_4:def 7;
thus L31: thesis by L30 , FINSEQ_2:120;
end;
end;
definition
let R1 being (Element of ( NAT ));
let R8 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
let R9 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
redefine func R8 + R9 -> (Element of ( R1 -tuples_on ( COMPLEX ) ));

coherence
proof
L33: ( R8 + R9 ) = ( ( addcomplex ) .: (R8 , R9) ) by SEQ_4:def 6;
thus L34: thesis by L33 , FINSEQ_2:120;
end;
end;
definition
let R1 being (Element of ( NAT ));
let R7 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
let C9 being  complex number;
redefine func C9 * R7 -> (Element of ( R1 -tuples_on ( COMPLEX ) ));

coherence
proof
reconsider D2 = C9 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L36: ( D2 * R7 ) = ( ( ( multcomplex ) [;] (D2 , ( id ( COMPLEX ) )) ) * R7 ) by L25;
thus L37: thesis by L36 , FINSEQ_2:113;
end;
end;
theorem
L39: (for B7 being  complex number holds (for B8 being (FinSequence of ( COMPLEX )) holds ( len ( B7 * B8 ) ) = ( len B8 )))
proof
let C10 being  complex number;
let C11 being (FinSequence of ( COMPLEX ));
set D3 = ( len C11 );
reconsider D4 = C11 as (Element of ( D3 -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D5 = C10 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L40: ( len ( D5 * D4 ) ) = D3 by CARD_1:def 7;
thus L41: thesis by L40;
end;
theorem
L42: (for B9 being  complex-yielding FinSequence holds ( dom B9 ) = ( dom ( - B9 ) )) by VALUED_1:8;
theorem
L43: (for B10 being  complex-valued FinSequence holds ( len ( - B10 ) ) = ( len B10 ))
proof
let C12 being  complex-valued FinSequence;
L44: ( dom ( - C12 ) ) = ( dom C12 ) by VALUED_1:8;
thus L45: thesis by L44 , FINSEQ_3:29;
end;
L46: (for B11 being  complex-valued FinSequence holds B11 is (FinSequence of ( COMPLEX )))
proof
let C13 being  complex-valued FinSequence;
L47: ( rng C13 ) c= ( COMPLEX ) by VALUED_0:def 1;
thus L48: thesis by L47 , FINSEQ_1:def 4;
end;
theorem
L49: (for B12 , B13 being  complex-valued FinSequence holds (( len B12 ) = ( len B13 ) implies ( len ( B12 + B13 ) ) = ( len B12 )))
proof
let C14 , C15 being  complex-valued FinSequence;
set D6 = ( len C14 );
L50: C15 is (FinSequence of ( COMPLEX )) by L46;
L51: C14 is (FinSequence of ( COMPLEX )) by L46;
reconsider D7 = C14 as (Element of ( ( len C14 ) -tuples_on ( COMPLEX ) )) by L51 , FINSEQ_2:92;
assume L52: ( len C14 ) = ( len C15 );
reconsider D8 = C15 as (Element of ( D6 -tuples_on ( COMPLEX ) )) by L52 , L50 , FINSEQ_2:92;
L53: ( dom ( D7 + D8 ) ) = ( Seg D6 ) by FINSEQ_2:124;
thus L54: thesis by L53 , FINSEQ_1:def 3;
end;
theorem
L55: (for B14 , B15 being  complex-valued FinSequence holds (( len B14 ) = ( len B15 ) implies ( len ( B14 - B15 ) ) = ( len B14 )))
proof
let C16 , C17 being  complex-valued FinSequence;
set D9 = ( len C16 );
L56: C17 is (FinSequence of ( COMPLEX )) by L46;
L57: C16 is (FinSequence of ( COMPLEX )) by L46;
reconsider D10 = C16 as (Element of ( ( len C16 ) -tuples_on ( COMPLEX ) )) by L57 , FINSEQ_2:92;
assume L58: ( len C16 ) = ( len C17 );
reconsider D11 = C17 as (Element of ( D9 -tuples_on ( COMPLEX ) )) by L58 , L56 , FINSEQ_2:92;
L59: ( dom ( D10 - D11 ) ) = ( Seg D9 ) by FINSEQ_2:124;
thus L60: thesis by L59 , FINSEQ_1:def 3;
end;
theorem
L61: (for B16 being  complex-valued FinSequence holds B16 is (Element of ( COMPLEX ( len B16 ) )))
proof
let C18 being  complex-valued FinSequence;
L62: C18 is (FinSequence of ( COMPLEX )) by L46;
L63: C18 is (Element of ( ( COMPLEX ) * )) by L62 , FINSEQ_1:def 11;
L64: C18 in { B17 where B17 is (Element of ( ( COMPLEX ) * )) : ( len B17 ) = ( len C18 ) } by L63;
L65: C18 in ( ( len C18 ) -tuples_on ( COMPLEX ) ) by L64 , FINSEQ_2:def 4;
thus L66: thesis by L65 , SEQ_4:def 11;
end;
theorem
L67: (for R1 being (Element of ( NAT )) holds (for R8 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds (for R9 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds ( R8 - R9 ) = ( R8 + ( - R9 ) ))));
theorem
L68: (for B18 , B19 being  complex-valued FinSequence holds (( len B18 ) = ( len B19 ) implies ( B18 - B19 ) = ( B18 + ( - B19 ) )));
theorem
L69: (for R1 being (Element of ( NAT )) holds (for R7 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds ( ( - 1 ) * R7 ) = ( - R7 )));
theorem
L70: (for B20 being (FinSequence of ( COMPLEX )) holds ( ( - 1 ) * B20 ) = ( - B20 ));
theorem
L71: (for R1 being (Element of ( NAT )) holds (for B21 being (FinSequence of ( COMPLEX )) holds ( ( - B21 ) . R1 ) = ( - ( B21 . R1 ) )))
proof
let R1 being (Element of ( NAT ));
let C19 being (FinSequence of ( COMPLEX ));
per cases ;
suppose L72: (not R1 in ( dom ( - C19 ) ));

L73: (not R1 in ( dom C19 )) by L72 , VALUED_1:8;
thus L74: ( ( - C19 ) . R1 ) = ( - ( 0 ) ) by L72 , FUNCT_1:def 2
.= ( - ( C19 . R1 ) ) by L73 , FUNCT_1:def 2;
end;
suppose L75: R1 in ( dom ( - C19 ) );

set D12 = ( C19 . R1 );
L76: ( - C19 ) = ( ( compcomplex ) * C19 ) by SEQ_4:def 8;
L77: ( ( - C19 ) . R1 ) = ( ( compcomplex ) . D12 ) by L76 , L75 , FUNCT_1:12;
thus L78: thesis by L77 , BINOP_2:def 1;
end;
end;
definition
let R1 being (Element of ( NAT ));
let R7 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
redefine func - R7 -> (Element of ( R1 -tuples_on ( COMPLEX ) ));

coherence
proof
L80: ( - R7 ) = ( ( compcomplex ) * R7 ) by SEQ_4:def 8;
thus L81: thesis by L80 , FINSEQ_2:113;
end;
end;
theorem
L83: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for R6 being (Element of ( COMPLEX )) holds (for R7 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds (R6 = ( R7 . R2 ) implies ( ( - R7 ) . R2 ) = ( - R6 )))))) by L71;
theorem
L84: (for R3 being (FinSequence of ( COMPLEX )) holds (for B22 being  complex number holds ( dom ( B22 * R3 ) ) = ( dom R3 )))
proof
let R3 being (FinSequence of ( COMPLEX ));
let C20 being  complex number;
L85: ( dom ( C20 multcomplex ) ) = ( COMPLEX ) by FUNCT_2:def 1;
L86: ( rng R3 ) c= ( dom ( C20 multcomplex ) ) by L85 , FINSEQ_1:def 4;
thus L87: ( dom R3 ) = ( dom ( ( C20 multcomplex ) * R3 ) ) by L86 , RELAT_1:27
.= ( dom ( C20 * R3 ) ) by SEQ_4:def 9;
end;
theorem
L88: (for R3 being (FinSequence of ( COMPLEX )) holds (for B23 being Nat holds (for B24 being  complex number holds ( ( B24 * R3 ) . B23 ) = ( B24 * ( R3 . B23 ) ))))
proof
let R3 being (FinSequence of ( COMPLEX ));
let C21 being Nat;
let C22 being  complex number;
reconsider D13 = C22 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
per cases ;
suppose L89: (not C21 in ( dom ( C22 * R3 ) ));

L90: (not C21 in ( dom R3 )) by L89 , L84;
thus L91: ( ( C22 * R3 ) . C21 ) = ( C22 * ( 0 ) ) by L89 , FUNCT_1:def 2
.= ( C22 * ( R3 . C21 ) ) by L90 , FUNCT_1:def 2;
end;
suppose L92: C21 in ( dom ( C22 * R3 ) );

set D14 = ( R3 . C21 );
L93: ( C22 * R3 ) = ( ( ( multcomplex ) [;] (D13 , ( id ( COMPLEX ) )) ) * R3 ) by L25;
L94: D14 in ( dom ( ( multcomplex ) [;] (D13 , ( id ( COMPLEX ) )) ) ) by L93 , L92 , FUNCT_1:11;
thus L95: ( ( C22 * R3 ) . C21 ) = ( ( ( multcomplex ) [;] (D13 , ( id ( COMPLEX ) )) ) . D14 ) by L92 , L93 , FUNCT_1:12
.= ( ( multcomplex ) . (C22 , ( ( id ( COMPLEX ) ) . D14 )) ) by L94 , FUNCOP_1:32
.= ( ( multcomplex ) . (D13 , D14) ) by FUNCT_1:18
.= ( C22 * ( R3 . C21 ) ) by BINOP_2:def 5;
end;
end;
theorem
L97: (for R3 being (FinSequence of ( COMPLEX )) holds (for B25 being  complex number holds ( ( B25 * R3 ) *' ) = ( ( B25 *' ) * ( R3 *' ) )))
proof
let R3 being (FinSequence of ( COMPLEX ));
let C23 being  complex number;
reconsider D15 = C23 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L98: ( len ( ( C23 *' ) * ( R3 *' ) ) ) = ( len ( R3 *' ) ) by L39;
L99: ( len ( ( C23 *' ) * ( R3 *' ) ) ) = ( len R3 ) by L98 , L1;
L100: ( len ( C23 * R3 ) ) = ( len R3 ) by L39;
L101:
now
let C24 being Nat;
assume that
L102: 1 <= C24
and
L103: C24 <= ( len ( ( C23 * R3 ) *' ) );
L104: C24 <= ( len ( C23 * R3 ) ) by L103 , L1;
thus L105: ( ( ( C23 * R3 ) *' ) . C24 ) = ( ( ( C23 * R3 ) . C24 ) *' ) by L104 , L102 , L1
.= ( ( D15 * ( R3 . C24 ) ) *' ) by L88
.= ( ( D15 *' ) * ( ( R3 . C24 ) *' ) ) by COMPLEX1:35
.= ( ( C23 *' ) * ( ( R3 *' ) . C24 ) ) by L100 , L102 , L104 , L1
.= ( ( ( C23 *' ) * ( R3 *' ) ) . C24 ) by L88;
end;
L106: ( len ( ( C23 * R3 ) *' ) ) = ( len ( C23 * R3 ) ) by L1;
thus L107: thesis by L106 , L99 , L101 , L39 , FINSEQ_1:14;
end;
theorem
L108: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for R8 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds (for R9 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds ( ( R8 + R9 ) . R2 ) = ( ( R8 . R2 ) + ( R9 . R2 ) )))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let R8 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
let R9 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
per cases ;
suppose L109: (not R2 in ( Seg R1 ));

L110: (not R2 in ( dom R9 )) by L109 , FINSEQ_2:124;
L111: (not R2 in ( dom R8 )) by L109 , FINSEQ_2:124;
L112: (not R2 in ( dom ( R8 + R9 ) )) by L109 , FINSEQ_2:124;
thus L113: ( ( R8 + R9 ) . R2 ) = ( ( 0 ) + ( 0 ) ) by L112 , FUNCT_1:def 2
.= ( ( R8 . R2 ) + ( 0 ) ) by L111 , FUNCT_1:def 2
.= ( ( R8 . R2 ) + ( R9 . R2 ) ) by L110 , FUNCT_1:def 2;
end;
suppose L114: R2 in ( Seg R1 );

L115: R2 in ( dom ( R8 + R9 ) ) by L114 , FINSEQ_2:124;
thus L116: thesis by L115 , VALUED_1:def 1;
end;
end;
theorem
L118: (for B26 , B27 being (FinSequence of ( COMPLEX )) holds (( len B26 ) = ( len B27 ) implies ( ( B26 + B27 ) *' ) = ( ( B26 *' ) + ( B27 *' ) )))
proof
let C25 , C26 being (FinSequence of ( COMPLEX ));
reconsider D16 = C25 as (Element of ( ( len C25 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D17 = C26 as (Element of ( ( len C26 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D18 = ( C25 *' ) as (Element of ( ( len ( C25 *' ) ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D19 = ( C26 *' ) as (Element of ( ( len ( C26 *' ) ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
assume L119: ( len C25 ) = ( len C26 );
L120: ( len ( C25 + C26 ) ) = ( len C25 ) by L119 , L49;
L121: (( len C25 ) = ( len ( C25 *' ) ) & ( len C26 ) = ( len ( C26 *' ) )) by L1;
L122:
now
let C27 being Nat;
L123: C27 in ( NAT ) by ORDINAL1:def 12;
assume that
L124: 1 <= C27
and
L125: C27 <= ( len ( ( C25 + C26 ) *' ) );
L126: C27 <= ( len ( C25 + C26 ) ) by L125 , L1;
thus L127: ( ( ( C25 + C26 ) *' ) . C27 ) = ( ( ( C25 + C26 ) . C27 ) *' ) by L126 , L124 , L1
.= ( ( ( D16 . C27 ) + ( D17 . C27 ) ) *' ) by L119 , L123 , L108
.= ( ( ( C25 . C27 ) *' ) + ( ( C26 . C27 ) *' ) ) by COMPLEX1:32
.= ( ( ( C25 *' ) . C27 ) + ( ( C26 . C27 ) *' ) ) by L120 , L124 , L126 , L1
.= ( ( ( C25 *' ) . C27 ) + ( ( C26 *' ) . C27 ) ) by L119 , L120 , L124 , L126 , L1
.= ( ( D18 + D19 ) . C27 ) by L119 , L121 , L123 , L108;
end;
L128: ( len ( ( C25 *' ) + ( C26 *' ) ) ) = ( len C25 ) by L119 , L121 , L49;
L129: ( len ( ( C25 + C26 ) *' ) ) = ( len ( ( C25 *' ) + ( C26 *' ) ) ) by L128 , L120 , L1;
thus L130: thesis by L129 , L122 , FINSEQ_1:14;
end;
theorem
L131: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for R8 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds (for R9 being (Element of ( R1 -tuples_on ( COMPLEX ) )) holds ( ( R8 - R9 ) . R2 ) = ( ( R8 . R2 ) - ( R9 . R2 ) )))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let R8 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
let R9 being (Element of ( R1 -tuples_on ( COMPLEX ) ));
per cases ;
suppose L132: (not R2 in ( Seg R1 ));

L133: (not R2 in ( dom R9 )) by L132 , FINSEQ_2:124;
L134: (not R2 in ( dom R8 )) by L132 , FINSEQ_2:124;
L135: (not R2 in ( dom ( R8 - R9 ) )) by L132 , FINSEQ_2:124;
thus L136: ( ( R8 - R9 ) . R2 ) = ( ( 0 ) - ( 0 ) ) by L135 , FUNCT_1:def 2
.= ( ( R8 . R2 ) - ( 0 ) ) by L134 , FUNCT_1:def 2
.= ( ( R8 . R2 ) - ( R9 . R2 ) ) by L133 , FUNCT_1:def 2;
end;
suppose L137: R2 in ( Seg R1 );

L138: R2 in ( dom ( R8 - R9 ) ) by L137 , FINSEQ_2:124;
thus L139: thesis by L138 , VALUED_1:13;
end;
end;
theorem
L141: (for B28 , B29 being (FinSequence of ( COMPLEX )) holds (( len B28 ) = ( len B29 ) implies ( ( B28 - B29 ) *' ) = ( ( B28 *' ) - ( B29 *' ) )))
proof
let C28 , C29 being (FinSequence of ( COMPLEX ));
reconsider D20 = C28 as (Element of ( ( len C28 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D21 = C29 as (Element of ( ( len C29 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D22 = ( C28 *' ) as (Element of ( ( len ( C28 *' ) ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D23 = ( C29 *' ) as (Element of ( ( len ( C29 *' ) ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
assume L142: ( len C28 ) = ( len C29 );
L143: ( len ( C28 - C29 ) ) = ( len C28 ) by L142 , L55;
L144: (( len C28 ) = ( len ( C28 *' ) ) & ( len C29 ) = ( len ( C29 *' ) )) by L1;
L145:
now
let C30 being Nat;
L146: C30 in ( NAT ) by ORDINAL1:def 12;
assume that
L147: 1 <= C30
and
L148: C30 <= ( len ( ( C28 - C29 ) *' ) );
L149: C30 <= ( len ( C28 - C29 ) ) by L148 , L1;
thus L150: ( ( ( C28 - C29 ) *' ) . C30 ) = ( ( ( C28 - C29 ) . C30 ) *' ) by L149 , L147 , L1
.= ( ( ( D20 . C30 ) - ( D21 . C30 ) ) *' ) by L142 , L146 , L131
.= ( ( ( C28 . C30 ) *' ) - ( ( C29 . C30 ) *' ) ) by COMPLEX1:34
.= ( ( ( C28 *' ) . C30 ) - ( ( C29 . C30 ) *' ) ) by L143 , L147 , L149 , L1
.= ( ( ( C28 *' ) . C30 ) - ( ( C29 *' ) . C30 ) ) by L142 , L143 , L147 , L149 , L1
.= ( ( D22 - D23 ) . C30 ) by L142 , L144 , L146 , L131;
end;
L151: ( len ( ( C28 *' ) - ( C29 *' ) ) ) = ( len C28 ) by L142 , L144 , L55;
L152: ( len ( ( C28 - C29 ) *' ) ) = ( len ( ( C28 *' ) - ( C29 *' ) ) ) by L151 , L143 , L1;
thus L153: thesis by L152 , L145 , FINSEQ_1:14;
end;
theorem
L154: (for B30 being (FinSequence of ( COMPLEX )) holds ( ( B30 *' ) *' ) = B30)
proof
let C31 being (FinSequence of ( COMPLEX ));
L155: ( len ( C31 *' ) ) = ( len C31 ) by L1;
L156:
now
let C32 being Nat;
assume that
L157: 1 <= C32
and
L158: C32 <= ( len ( ( C31 *' ) *' ) );
L159: C32 <= ( len ( C31 *' ) ) by L158 , L1;
L160: ( ( C31 *' ) . C32 ) = ( ( C31 . C32 ) *' ) by L159 , L155 , L157 , L1;
thus L161: ( ( ( C31 *' ) *' ) . C32 ) = ( ( ( C31 . C32 ) *' ) *' ) by L160 , L157 , L159 , L1
.= ( C31 . C32 );
end;
L162: ( len ( ( C31 *' ) *' ) ) = ( len ( C31 *' ) ) by L1;
thus L163: thesis by L162 , L155 , L156 , FINSEQ_1:14;
end;
theorem
L164: (for B31 being (FinSequence of ( COMPLEX )) holds ( ( - B31 ) *' ) = ( - ( B31 *' ) ))
proof
let C33 being (FinSequence of ( COMPLEX ));
L165: ( ( - C33 ) *' ) = ( ( ( - ( 1r ) ) *' ) * ( C33 *' ) ) by L97 , COMPLEX1:def 4
.= ( - ( C33 *' ) ) by COMPLEX1:30 , COMPLEX1:33 , COMPLEX1:def 4;
thus L166: thesis by L165;
end;
theorem
L167: (for B32 being  complex number holds ( B32 + ( B32 *' ) ) = ( 2 * ( Re B32 ) ))
proof
let C34 being  complex number;
L168: C34 is (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L169: ( C34 + ( C34 *' ) ) = ( ( ( Re C34 ) + ( Re ( C34 *' ) ) ) + ( ( ( Im C34 ) + ( Im ( C34 *' ) ) ) * ( <i> ) ) ) by L168 , COMPLEX1:def 5
.= ( ( ( Re C34 ) + ( Re ( C34 *' ) ) ) + ( ( ( Im C34 ) + ( - ( Im C34 ) ) ) * ( <i> ) ) ) by COMPLEX1:27
.= ( ( Re C34 ) + ( Re C34 ) ) by COMPLEX1:27
.= ( 2 * ( Re C34 ) );
thus L170: thesis by L169;
end;
theorem
L171: (for R1 being (Element of ( NAT )) holds (for B33 , B34 being  complex-valued FinSequence holds (( len B33 ) = ( len B34 ) implies ( ( B33 - B34 ) . R1 ) = ( ( B33 . R1 ) - ( B34 . R1 ) ))))
proof
let R1 being (Element of ( NAT ));
let C35 , C36 being  complex-valued FinSequence;
L172: (C35 is (FinSequence of ( COMPLEX )) & C36 is (FinSequence of ( COMPLEX ))) by L46;
reconsider D24 = C35 as (Element of ( ( len C35 ) -tuples_on ( COMPLEX ) )) by L172 , FINSEQ_2:92;
reconsider D25 = C36 as (Element of ( ( len C36 ) -tuples_on ( COMPLEX ) )) by L172 , FINSEQ_2:92;
reconsider D26 = ( D24 - D25 ) as (Element of ( ( len ( D24 - D25 ) ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
assume L173: ( len C35 ) = ( len C36 );
L174: ( len ( C35 - C36 ) ) = ( len C35 ) by L173 , L55;
per cases ;
suppose L175: (not R1 in ( Seg ( len C35 ) ));

L176: (not R1 in ( dom D24 )) by L175 , FINSEQ_2:124;
L177: (not R1 in ( dom D25 )) by L173 , L175 , FINSEQ_2:124;
L178: (not R1 in ( dom D26 )) by L174 , L175 , FINSEQ_2:124;
L179: ( ( D24 - D25 ) . R1 ) = ( ( 0 ) - ( 0 ) ) by L178 , FUNCT_1:def 2
.= ( ( D24 . R1 ) - ( 0 ) ) by L176 , FUNCT_1:def 2
.= ( ( D24 . R1 ) - ( D25 . R1 ) ) by L177 , FUNCT_1:def 2;
thus L180: thesis by L179;
end;
suppose L181: R1 in ( Seg ( len C35 ) );

L182: R1 in ( dom D26 ) by L181 , L174 , FINSEQ_2:124;
thus L183: thesis by L182 , VALUED_1:13;
end;
end;
theorem
L185: (for R1 being (Element of ( NAT )) holds (for B35 , B36 being  complex-valued FinSequence holds (( len B35 ) = ( len B36 ) implies ( ( B35 + B36 ) . R1 ) = ( ( B35 . R1 ) + ( B36 . R1 ) ))))
proof
let R1 being (Element of ( NAT ));
let C37 , C38 being  complex-valued FinSequence;
L186: (C37 is (FinSequence of ( COMPLEX )) & C38 is (FinSequence of ( COMPLEX ))) by L46;
reconsider D27 = C37 as (Element of ( ( len C37 ) -tuples_on ( COMPLEX ) )) by L186 , FINSEQ_2:92;
reconsider D28 = C38 as (Element of ( ( len C38 ) -tuples_on ( COMPLEX ) )) by L186 , FINSEQ_2:92;
reconsider D29 = ( D27 + D28 ) as (Element of ( ( len ( D27 + D28 ) ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
assume L187: ( len C37 ) = ( len C38 );
L188: ( len ( C37 + C38 ) ) = ( len C37 ) by L187 , L49;
per cases ;
suppose L189: (not R1 in ( Seg ( len C37 ) ));

L190: (not R1 in ( dom D27 )) by L189 , FINSEQ_2:124;
L191: (not R1 in ( dom D28 )) by L187 , L189 , FINSEQ_2:124;
L192: (not R1 in ( dom D29 )) by L188 , L189 , FINSEQ_2:124;
L193: ( ( D27 + D28 ) . R1 ) = ( ( 0 ) + ( 0 ) ) by L192 , FUNCT_1:def 2
.= ( ( D27 . R1 ) + ( 0 ) ) by L190 , FUNCT_1:def 2
.= ( ( D27 . R1 ) + ( D28 . R1 ) ) by L191 , FUNCT_1:def 2;
thus L194: thesis by L193;
end;
suppose L195: R1 in ( Seg ( len C37 ) );

L196: R1 in ( dom D29 ) by L195 , L188 , FINSEQ_2:124;
thus L197: thesis by L196 , VALUED_1:def 1;
end;
end;
definition
let C39 being (FinSequence of ( COMPLEX ));
func Re C39 -> (FinSequence of ( REAL )) equals 
( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) );
coherence
proof
L199: ( len C39 ) = ( len ( C39 *' ) ) by L1;
L200: ( len ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) ) = ( len ( C39 + ( C39 *' ) ) ) by L39
.= ( len C39 ) by L199 , L49;
L201: ( rng ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) ) c= ( REAL )
proof
let C40 being set;
assume L202: C40 in ( rng ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) );
consider C41 being set such that L203: C41 in ( dom ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) ) and L204: C40 = ( ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) . C41 ) by L202 , FUNCT_1:def 3;
reconsider D30 = C41 as (Element of ( NAT )) by L203;
L205: C41 in ( Seg ( len ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) ) ) by L203 , FINSEQ_1:def 3;
L206: (1 <= D30 & D30 <= ( len C39 )) by L205 , L200 , FINSEQ_1:1;
L207: ( ( ( 1 / 2 ) * ( C39 + ( C39 *' ) ) ) . D30 ) = ( ( 1 / 2 ) * ( ( C39 + ( C39 *' ) ) . D30 ) ) by L88
.= ( ( 1 / 2 ) * ( ( C39 . D30 ) + ( ( C39 *' ) . D30 ) ) ) by L199 , L185
.= ( ( 1 / 2 ) * ( ( C39 . D30 ) + ( ( C39 . D30 ) *' ) ) ) by L206 , L1
.= ( ( 1 / 2 ) * ( 2 * ( Re ( C39 . D30 ) ) ) ) by L167;
thus L208: thesis by L207 , L204;
end;
thus L209: thesis by L201 , FINSEQ_1:def 4;
end;
end;
theorem
L211: (for B37 being  complex number holds ( B37 - ( B37 *' ) ) = ( ( 2 * ( Im B37 ) ) * ( <i> ) ))
proof
let C42 being  complex number;
L212: C42 is (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L213: ( C42 - ( C42 *' ) ) = ( ( ( Re C42 ) - ( Re ( C42 *' ) ) ) + ( ( ( Im C42 ) - ( Im ( C42 *' ) ) ) * ( <i> ) ) ) by L212 , COMPLEX1:def 8
.= ( ( ( Re C42 ) - ( Re ( C42 *' ) ) ) + ( ( ( Im C42 ) - ( - ( Im C42 ) ) ) * ( <i> ) ) ) by COMPLEX1:27
.= ( ( ( Re C42 ) - ( Re C42 ) ) + ( ( ( Im C42 ) - ( - ( Im C42 ) ) ) * ( <i> ) ) ) by COMPLEX1:27
.= ( ( 2 * ( Im C42 ) ) * ( <i> ) );
thus L214: thesis by L213;
end;
definition
let C43 being (FinSequence of ( COMPLEX ));
func Im C43 -> (FinSequence of ( REAL )) equals 
( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) );
coherence
proof
L215: ( len C43 ) = ( len ( C43 *' ) ) by L1;
L216: ( len ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) ) = ( len ( C43 - ( C43 *' ) ) ) by L39
.= ( len C43 ) by L215 , L55;
L217: ( rng ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) ) c= ( REAL )
proof
let C44 being set;
assume L218: C44 in ( rng ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) );
consider C45 being set such that L219: C45 in ( dom ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) ) and L220: C44 = ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) . C45 ) by L218 , FUNCT_1:def 3;
reconsider D31 = C45 as (Element of ( NAT )) by L219;
L221: C45 in ( Seg ( len ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) ) ) by L219 , FINSEQ_1:def 3;
L222: (1 <= D31 & D31 <= ( len C43 )) by L221 , L216 , FINSEQ_1:1;
L223: ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C43 - ( C43 *' ) ) ) . D31 ) = ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C43 - ( C43 *' ) ) . D31 ) ) by L88
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C43 . D31 ) - ( ( C43 *' ) . D31 ) ) ) by L215 , L171
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C43 . D31 ) - ( ( C43 . D31 ) *' ) ) ) by L222 , L1
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( 2 * ( Im ( C43 . D31 ) ) ) * ( <i> ) ) ) by L211;
thus L224: thesis by L223 , L220;
end;
thus L225: thesis by L217 , FINSEQ_1:def 4;
end;
end;
definition
let C46 , C47 being (FinSequence of ( COMPLEX ));
func |(C46 , C47 )| -> (Element of ( COMPLEX )) equals 
( ( ( |( ( Re C46 ) , ( Re C47 ) )| - ( ( <i> ) * |( ( Re C46 ) , ( Im C47 ) )| ) ) + ( ( <i> ) * |( ( Im C46 ) , ( Re C47 ) )| ) ) + |( ( Im C46 ) , ( Im C47 ) )| );
coherence;
end;
theorem
L228: (for B38 , B39 , B40 being  complex-valued FinSequence holds ((( len B38 ) = ( len B39 ) & ( len B39 ) = ( len B40 )) implies ( B38 + ( B39 + B40 ) ) = ( ( B38 + B39 ) + B40 )))
proof
let C48 , C49 , C50 being  complex-valued FinSequence;
reconsider D32 = C48 , D33 = C49 , D34 = C50 as (FinSequence of ( COMPLEX )) by L46;
assume L229: (( len C48 ) = ( len C49 ) & ( len C49 ) = ( len C50 ));
reconsider D35 = D34 as (Element of ( ( len C50 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D36 = D33 as (Element of ( ( len C49 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D37 = D32 as (Element of ( ( len C48 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
L230: ( C48 + ( C49 + C50 ) ) = ( ( addcomplex ) .: (D32 , ( D33 + D34 )) ) by SEQ_4:def 6
.= ( ( addcomplex ) .: (D32 , ( ( addcomplex ) .: (D33 , D34) )) ) by SEQ_4:def 6
.= ( ( addcomplex ) .: (( ( addcomplex ) .: (D37 , D36) ) , D35) ) by L229 , FINSEQOP:28
.= ( ( addcomplex ) .: (( D32 + D33 ) , D34) ) by SEQ_4:def 6
.= ( ( C48 + C49 ) + C50 ) by SEQ_4:def 6;
thus L231: thesis by L230;
end;
theorem
L232: (for B41 , B42 being  complex-valued FinSequence holds (( len B41 ) = ( len B42 ) implies ( B41 + B42 ) = ( B42 + B41 )));
theorem
L233: (for B43 being  complex number holds (for B44 , B45 being (FinSequence of ( COMPLEX )) holds (( len B44 ) = ( len B45 ) implies ( B43 * ( B44 + B45 ) ) = ( ( B43 * B44 ) + ( B43 * B45 ) ))))
proof
let C51 being  complex number;
let C52 , C53 being (FinSequence of ( COMPLEX ));
assume L234: ( len C52 ) = ( len C53 );
set D38 = ( C51 multcomplex );
reconsider D39 = C53 as (Element of ( ( len C53 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D40 = C52 as (Element of ( ( len C52 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
L235: C51 is (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L236: ( C51 * ( C52 + C53 ) ) = ( D38 * ( C52 + C53 ) ) by SEQ_4:def 9
.= ( D38 * ( ( addcomplex ) .: (C52 , C53) ) ) by SEQ_4:def 6
.= ( ( addcomplex ) .: (( D38 * D40 ) , ( D38 * D39 )) ) by L234 , L235 , FINSEQOP:51 , SEQ_4:56
.= ( ( D38 * C52 ) + ( D38 * C53 ) ) by SEQ_4:def 6
.= ( ( C51 * C52 ) + ( D38 * C53 ) ) by SEQ_4:def 9
.= ( ( C51 * C52 ) + ( C51 * C53 ) ) by SEQ_4:def 9;
thus L237: thesis by L236;
end;
theorem
L238: (for B46 , B47 being  complex-valued FinSequence holds (( len B46 ) = ( len B47 ) implies ( B46 - B47 ) = ( B46 + ( - B47 ) )));
theorem
L239: (for B48 , B49 being  complex-valued FinSequence holds ((( len B48 ) = ( len B49 ) & ( B48 + B49 ) = ( 0c ( len B48 ) )) implies (B48 = ( - B49 ) & B49 = ( - B48 ))))
proof
let C54 , C55 being  complex-valued FinSequence;
assume that
L240: ( len C54 ) = ( len C55 )
and
L241: ( C54 + C55 ) = ( 0c ( len C54 ) );
reconsider D41 = C54 , D42 = C55 as (FinSequence of ( COMPLEX )) by L46;
reconsider D43 = D41 as (Element of ( ( len C54 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D44 = D42 as (Element of ( ( len C55 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
L242: (( C54 + C55 ) = ( ( addcomplex ) .: (D41 , D42) ) & ( - C55 ) = ( ( compcomplex ) * D42 )) by SEQ_4:def 6 , SEQ_4:def 8;
L243: ( C54 + C55 ) = ( ( len C54 ) |-> ( 0c ) ) by L241 , SEQ_4:def 12;
L244: D43 = ( - D44 ) by L243 , L240 , L242 , BINOP_2:1 , FINSEQOP:74 , SEQ_4:51 , SEQ_4:52;
thus L245: thesis by L244;
end;
theorem
L246: (for B50 being  complex-valued FinSequence holds ( B50 + ( 0c ( len B50 ) ) ) = B50)
proof
let C56 being  complex-valued FinSequence;
L247: C56 is (FinSequence of ( COMPLEX )) by L46;
reconsider D45 = C56 as (Element of ( ( len C56 ) -tuples_on ( COMPLEX ) )) by L247 , FINSEQ_2:92;
L248: ( C56 + ( 0c ( len C56 ) ) ) = ( C56 + ( ( len C56 ) |-> ( 0c ) ) ) by SEQ_4:def 12
.= ( ( addcomplex ) .: (C56 , ( ( len C56 ) |-> ( 0c ) )) ) by L247 , SEQ_4:def 6
.= D45 by BINOP_2:1 , FINSEQOP:56;
thus L249: thesis by L248;
end;
theorem
L250: (for B51 being  complex-valued FinSequence holds ( B51 + ( - B51 ) ) = ( 0c ( len B51 ) ))
proof
let C57 being  complex-valued FinSequence;
L251: (C57 is (FinSequence of ( COMPLEX )) & ( - C57 ) is (FinSequence of ( COMPLEX ))) by L46;
reconsider D46 = C57 as (Element of ( ( len C57 ) -tuples_on ( COMPLEX ) )) by L251 , FINSEQ_2:92;
L252: ( C57 + ( - C57 ) ) = ( ( addcomplex ) .: (C57 , ( - C57 )) ) by L251 , SEQ_4:def 6
.= ( ( addcomplex ) .: (C57 , ( ( compcomplex ) * C57 )) ) by L251 , SEQ_4:def 8
.= ( ( len D46 ) |-> ( 0c ) ) by BINOP_2:1 , FINSEQOP:73 , SEQ_4:51 , SEQ_4:52
.= ( 0c ( len D46 ) ) by SEQ_4:def 12;
thus L253: thesis by L252;
end;
theorem
L254: (for B52 , B53 being  complex-valued FinSequence holds (( len B52 ) = ( len B53 ) implies ( - ( B52 + B53 ) ) = ( ( - B52 ) + ( - B53 ) )))
proof
let C58 , C59 being  complex-valued FinSequence;
assume L255: ( len C58 ) = ( len C59 );
L256: ( len ( - C59 ) ) = ( len C59 ) by L43;
L257: ( len ( ( - C58 ) + ( - C59 ) ) ) = ( len ( - C58 ) ) by L256 , L255 , L43 , L49;
L258: ( len ( - C58 ) ) = ( len C58 ) by L43;
L259: ( len ( C58 + C59 ) ) = ( len C58 ) by L255 , L49;
L260: ( ( C58 + C59 ) + ( ( - C58 ) + ( - C59 ) ) ) = ( ( ( C59 + C58 ) + ( - C58 ) ) + ( - C59 ) ) by L259 , L255 , L256 , L258 , L228
.= ( ( C59 + ( C58 + ( - C58 ) ) ) + ( - C59 ) ) by L255 , L258 , L228
.= ( ( C59 + ( 0c ( len C58 ) ) ) + ( - C59 ) ) by L250
.= ( C59 + ( - C59 ) ) by L255 , L246
.= ( 0c ( len C59 ) ) by L250;
thus L261: thesis by L260 , L255 , L258 , L259 , L257 , L239;
end;
theorem
L262: (for B54 , B55 , B56 being  complex-valued FinSequence holds ((( len B54 ) = ( len B55 ) & ( len B55 ) = ( len B56 )) implies ( ( B54 - B55 ) - B56 ) = ( B54 - ( B55 + B56 ) )))
proof
let C60 , C61 , C62 being  complex-valued FinSequence;
assume that
L263: ( len C60 ) = ( len C61 )
and
L264: ( len C61 ) = ( len C62 );
L265: (( len ( - C61 ) ) = ( len C61 ) & ( len ( - C62 ) ) = ( len C62 )) by L43;
L266: ( ( C60 - C61 ) - C62 ) = ( C60 + ( ( - C61 ) + ( - C62 ) ) ) by L265 , L263 , L264 , L228
.= ( C60 - ( C61 + C62 ) ) by L264 , L254;
thus L267: thesis by L266;
end;
theorem
L268: (for B57 , B58 , B59 being  complex-valued FinSequence holds ((( len B57 ) = ( len B58 ) & ( len B58 ) = ( len B59 )) implies ( B57 + ( B58 - B59 ) ) = ( ( B57 + B58 ) - B59 )))
proof
let C63 , C64 , C65 being  complex-valued FinSequence;
assume L269: (( len C63 ) = ( len C64 ) & ( len C64 ) = ( len C65 ));
L270: ( len ( - C65 ) ) = ( len C65 ) by L43;
thus L271: thesis by L270 , L269 , L228;
end;
canceled 1;
theorem
L272: (for B60 , B61 being  complex-valued FinSequence holds (( len B60 ) = ( len B61 ) implies ( - ( B60 - B61 ) ) = ( ( - B60 ) + B61 )))
proof
let C66 , C67 being  complex-valued FinSequence;
assume L273: ( len C66 ) = ( len C67 );
L274: ( len ( - C67 ) ) = ( len C67 ) by L43;
L275: ( - ( C66 - C67 ) ) = ( ( - C66 ) + ( - ( - C67 ) ) ) by L274 , L273 , L254
.= ( ( - C66 ) + C67 );
thus L276: thesis by L275;
end;
theorem
L277: (for B62 , B63 , B64 being  complex-valued FinSequence holds ((( len B62 ) = ( len B63 ) & ( len B63 ) = ( len B64 )) implies ( B62 - ( B63 - B64 ) ) = ( ( B62 - B63 ) + B64 )))
proof
let C68 , C69 , C70 being  complex-valued FinSequence;
assume that
L278: ( len C68 ) = ( len C69 )
and
L279: ( len C69 ) = ( len C70 );
L280: ( len ( - C69 ) ) = ( len C69 ) by L43;
L281: ( C68 - ( C69 - C70 ) ) = ( C68 + ( ( - C69 ) + C70 ) ) by L279 , L272
.= ( ( C68 - C69 ) + C70 ) by L278 , L279 , L280 , L228;
thus L282: thesis by L281;
end;
theorem
L283: (for R3 being (FinSequence of ( COMPLEX )) holds (for B65 being  complex number holds ( B65 * ( 0c ( len R3 ) ) ) = ( 0c ( len R3 ) )))
proof
let R3 being (FinSequence of ( COMPLEX ));
let C71 being  complex number;
reconsider D47 = C71 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L284: ( rng ( 0c ( len R3 ) ) ) c= ( COMPLEX ) by FINSEQ_1:def 4;
L285: ( C71 * ( 0c ( len R3 ) ) ) = ( ( ( multcomplex ) [;] (D47 , ( id ( COMPLEX ) )) ) * ( 0c ( len R3 ) ) ) by L25
.= ( ( multcomplex ) [;] (D47 , ( ( id ( COMPLEX ) ) * ( 0c ( len R3 ) ) )) ) by FUNCOP_1:34
.= ( ( multcomplex ) [;] (D47 , ( 0c ( len R3 ) )) ) by L284 , RELAT_1:53
.= ( ( multcomplex ) [;] (D47 , ( ( len R3 ) |-> ( 0c ) )) ) by SEQ_4:def 12
.= ( ( len R3 ) |-> ( ( multcomplex ) . (D47 , ( 0c )) ) ) by FINSEQOP:18
.= ( ( len R3 ) |-> ( D47 * ( 0c ) ) ) by BINOP_2:def 5
.= ( 0c ( len R3 ) ) by SEQ_4:def 12;
thus L286: thesis by L285;
end;
theorem
L287: (for R3 being (FinSequence of ( COMPLEX )) holds (for B66 being  complex number holds ( - ( B66 * R3 ) ) = ( B66 * ( - R3 ) )))
proof
let R3 being (FinSequence of ( COMPLEX ));
let C72 being  complex number;
L288: (( len ( C72 * ( - R3 ) ) ) = ( len ( - R3 ) ) & ( len ( C72 * R3 ) ) = ( len R3 )) by L39;
L289: ( len R3 ) = ( len ( - R3 ) ) by L43;
L290: ( ( C72 * ( - R3 ) ) + ( C72 * R3 ) ) = ( C72 * ( R3 + ( - R3 ) ) ) by L289 , L233
.= ( C72 * ( 0c ( len R3 ) ) ) by L250
.= ( 0c ( len R3 ) ) by L283;
thus L291: thesis by L290 , L289 , L288 , L239;
end;
theorem
L292: (for B67 being  complex number holds (for B68 , B69 being (FinSequence of ( COMPLEX )) holds (( len B68 ) = ( len B69 ) implies ( B67 * ( B68 - B69 ) ) = ( ( B67 * B68 ) - ( B67 * B69 ) ))))
proof
let C73 being  complex number;
let C74 , C75 being (FinSequence of ( COMPLEX ));
assume L293: ( len C74 ) = ( len C75 );
reconsider D48 = C73 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
reconsider D49 = C75 as (Element of ( ( len C75 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
reconsider D50 = C74 as (Element of ( ( len C74 ) -tuples_on ( COMPLEX ) )) by FINSEQ_2:92;
set D51 = ( D48 multcomplex );
L294: ( C73 * ( C74 - C75 ) ) = ( D51 * ( C74 + ( - C75 ) ) ) by SEQ_4:def 9
.= ( D51 * ( ( addcomplex ) .: (C74 , ( - C75 )) ) ) by SEQ_4:def 6
.= ( ( addcomplex ) .: (( D51 * D50 ) , ( D51 * ( - D49 ) )) ) by L293 , FINSEQOP:51 , SEQ_4:56
.= ( ( D51 * C74 ) + ( D51 * ( - C75 ) ) ) by SEQ_4:def 6
.= ( ( C73 * C74 ) + ( D51 * ( - C75 ) ) ) by SEQ_4:def 9
.= ( ( C73 * C74 ) + ( C73 * ( - C75 ) ) ) by SEQ_4:def 9
.= ( ( C73 * C74 ) - ( C73 * C75 ) ) by L287;
thus L295: thesis by L294;
end;
theorem
L296: (for B70 , B71 being (Element of ( COMPLEX )) holds (for B72 , B73 being Real holds ((B70 = B72 & B71 = B73) implies ( ( addcomplex ) . (B70 , B71) ) = ( ( addreal ) . (B72 , B73) ))))
proof
let C76 , C77 being (Element of ( COMPLEX ));
let C78 , C79 being Real;
L297: ( ( addcomplex ) . (C76 , C77) ) = ( C76 + C77 ) by BINOP_2:def 3;
assume L298: (C76 = C78 & C77 = C79);
thus L299: thesis by L298 , L297 , BINOP_2:def 9;
end;
theorem
L300: (for R10 being (Function of [: ( COMPLEX ) , ( COMPLEX ) :] , ( COMPLEX )) holds (for R11 being (Function of [: ( REAL ) , ( REAL ) :] , ( REAL )) holds (for B74 , B75 being (FinSequence of ( COMPLEX )) holds (for B76 , B77 being (FinSequence of ( REAL )) holds ((B74 = B76 & B75 = B77 & ( len B74 ) = ( len B77 ) & (for R1 being (Element of ( NAT )) holds (R1 in ( dom B74 ) implies ( R10 . (( B74 . R1 ) , ( B75 . R1 )) ) = ( R11 . (( B76 . R1 ) , ( B77 . R1 )) )))) implies ( R10 .: (B74 , B75) ) = ( R11 .: (B76 , B77) ))))))
proof
let R10 being (Function of [: ( COMPLEX ) , ( COMPLEX ) :] , ( COMPLEX ));
let R11 being (Function of [: ( REAL ) , ( REAL ) :] , ( REAL ));
let C80 , C81 being (FinSequence of ( COMPLEX ));
let C82 , C83 being (FinSequence of ( REAL ));
assume that
L301: C80 = C82
and
L302: C81 = C83
and
L303: ( len C80 ) = ( len C83 )
and
L304: (for R1 being (Element of ( NAT )) holds (R1 in ( dom C80 ) implies ( R10 . (( C80 . R1 ) , ( C81 . R1 )) ) = ( R11 . (( C82 . R1 ) , ( C83 . R1 )) )));
L305: ( len ( R11 .: (C82 , C83) ) ) = ( len C80 ) by L301 , L303 , FINSEQ_2:72;
L306:
now
let C84 being Nat;
assume that
L307: 1 <= C84
and
L308: C84 <= ( len ( R10 .: (C80 , C81) ) );
L309: C84 <= ( len C80 ) by L302 , L303 , L308 , FINSEQ_2:72;
L310: C84 in ( dom C80 ) by L309 , L307 , FINSEQ_3:25;
L311: C84 in ( dom ( R11 .: (C82 , C83) ) ) by L305 , L307 , L309 , FINSEQ_3:25;
L312: C84 in ( dom ( R10 .: (C80 , C81) ) ) by L307 , L308 , FINSEQ_3:25;
thus L313: ( ( R10 .: (C80 , C81) ) . C84 ) = ( R10 . (( C80 . C84 ) , ( C81 . C84 )) ) by L312 , FUNCOP_1:22
.= ( R11 . (( C82 . C84 ) , ( C83 . C84 )) ) by L304 , L310
.= ( ( R11 .: (C82 , C83) ) . C84 ) by L311 , FUNCOP_1:22;
end;
L314: ( len ( R10 .: (C80 , C81) ) ) = ( len C80 ) by L302 , L303 , FINSEQ_2:72;
thus L315: thesis by L314 , L305 , L306 , FINSEQ_1:14;
end;
theorem
L316: (for B78 , B79 being (FinSequence of ( COMPLEX )) holds (for B80 , B81 being (FinSequence of ( REAL )) holds ((B78 = B80 & B79 = B81 & ( len B78 ) = ( len B81 )) implies ( ( addcomplex ) .: (B78 , B79) ) = ( ( addreal ) .: (B80 , B81) ))))
proof
let C85 , C86 being (FinSequence of ( COMPLEX ));
let C87 , C88 being (FinSequence of ( REAL ));
assume that
L317: (C85 = C87 & C86 = C88)
and
L318: ( len C85 ) = ( len C88 );
L319: (for R1 being (Element of ( NAT )) holds (R1 in ( dom C85 ) implies ( ( addcomplex ) . (( C85 . R1 ) , ( C86 . R1 )) ) = ( ( addreal ) . (( C87 . R1 ) , ( C88 . R1 )) )))
proof
let R1 being (Element of ( NAT ));
L320: ( ( C85 . R1 ) + ( C86 . R1 ) ) = ( ( addcomplex ) . (( C85 . R1 ) , ( C86 . R1 )) ) by BINOP_2:def 3;
thus L321: thesis by L320 , L317 , BINOP_2:def 9;
end;
thus L322: thesis by L319 , L317 , L318 , L300;
end;
theorem
L323: (for B82 , B83 being (FinSequence of ( COMPLEX )) holds (for B84 , B85 being (FinSequence of ( REAL )) holds ((B82 = B84 & B83 = B85 & ( len B82 ) = ( len B85 )) implies ( B82 + B83 ) = ( B84 + B85 ))));
theorem
L324: (for B86 being (FinSequence of ( COMPLEX )) holds (( len ( Re B86 ) ) = ( len B86 ) & ( len ( Im B86 ) ) = ( len B86 )))
proof
let C89 being (FinSequence of ( COMPLEX ));
L325: ( len C89 ) = ( len ( C89 *' ) ) by L1;
L326: ( len ( Im C89 ) ) = ( len ( C89 - ( C89 *' ) ) ) by L39
.= ( len C89 ) by L325 , L55;
L327: ( len ( Re C89 ) ) = ( len ( C89 + ( C89 *' ) ) ) by L39
.= ( len C89 ) by L325 , L49;
thus L328: thesis by L327 , L326;
end;
theorem
L329: (for B87 , B88 being (FinSequence of ( COMPLEX )) holds (( len B87 ) = ( len B88 ) implies (( Re ( B87 + B88 ) ) = ( ( Re B87 ) + ( Re B88 ) ) & ( Im ( B87 + B88 ) ) = ( ( Im B87 ) + ( Im B88 ) ))))
proof
let C90 , C91 being (FinSequence of ( COMPLEX ));
L330: ( len ( - ( C90 *' ) ) ) = ( len ( C90 *' ) ) by L43;
assume L331: ( len C90 ) = ( len C91 );
L332: ( len ( C90 + C91 ) ) = ( len C90 ) by L331 , L49;
L333: ( len C91 ) = ( len ( C91 *' ) ) by L1;
L334: ( len ( C91 + ( C91 *' ) ) ) = ( len C91 ) by L333 , L49;
L335: ( len C90 ) = ( len ( C90 *' ) ) by L1;
L336: ( len ( C90 + ( C90 *' ) ) ) = ( len C90 ) by L335 , L49;
L337: ( len ( C90 - ( C90 *' ) ) ) = ( len C90 ) by L335 , L55;
L338: ( len ( C91 - ( C91 *' ) ) ) = ( len C91 ) by L333 , L55;
thus L339: ( Re ( C90 + C91 ) ) = ( ( 1 / 2 ) * ( ( C90 + C91 ) + ( ( C90 *' ) + ( C91 *' ) ) ) ) by L331 , L118
.= ( ( 1 / 2 ) * ( ( ( C90 + C91 ) + ( C90 *' ) ) + ( C91 *' ) ) ) by L331 , L333 , L335 , L332 , L228
.= ( ( 1 / 2 ) * ( ( ( C90 + ( C90 *' ) ) + C91 ) + ( C91 *' ) ) ) by L331 , L335 , L228
.= ( ( 1 / 2 ) * ( ( C90 + ( C90 *' ) ) + ( C91 + ( C91 *' ) ) ) ) by L331 , L333 , L336 , L228
.= ( ( Re C90 ) + ( Re C91 ) ) by L331 , L336 , L334 , L233;
thus L340: ( Im ( C90 + C91 ) ) = ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C90 + C91 ) - ( ( C90 *' ) + ( C91 *' ) ) ) ) by L331 , L118
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( C90 + C91 ) - ( C90 *' ) ) - ( C91 *' ) ) ) by L331 , L333 , L335 , L332 , L262
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( C90 + ( - ( C90 *' ) ) ) + C91 ) - ( C91 *' ) ) ) by L331 , L335 , L330 , L228
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C90 - ( C90 *' ) ) + ( C91 - ( C91 *' ) ) ) ) by L331 , L333 , L337 , L268
.= ( ( Im C90 ) + ( Im C91 ) ) by L331 , L337 , L338 , L233;
end;
theorem
L341: (for B89 , B90 being (FinSequence of ( COMPLEX )) holds (for B91 , B92 being (FinSequence of ( REAL )) holds ((B89 = B91 & B90 = B92 & ( len B89 ) = ( len B92 )) implies ( ( diffcomplex ) .: (B89 , B90) ) = ( ( diffreal ) .: (B91 , B92) ))))
proof
let C92 , C93 being (FinSequence of ( COMPLEX ));
let C94 , C95 being (FinSequence of ( REAL ));
assume that
L342: (C92 = C94 & C93 = C95)
and
L343: ( len C92 ) = ( len C95 );
L344: (for R1 being (Element of ( NAT )) holds (R1 in ( dom C92 ) implies ( ( diffcomplex ) . (( C92 . R1 ) , ( C93 . R1 )) ) = ( ( diffreal ) . (( C94 . R1 ) , ( C95 . R1 )) )))
proof
let R1 being (Element of ( NAT ));
L345: ( ( C92 . R1 ) - ( C93 . R1 ) ) = ( ( diffcomplex ) . (( C92 . R1 ) , ( C93 . R1 )) ) by BINOP_2:def 4;
thus L346: thesis by L345 , L342 , BINOP_2:def 10;
end;
thus L347: thesis by L344 , L342 , L343 , L300;
end;
theorem
L348: (for B93 , B94 being (FinSequence of ( COMPLEX )) holds (for B95 , B96 being (FinSequence of ( REAL )) holds ((B93 = B95 & B94 = B96 & ( len B93 ) = ( len B96 )) implies ( B93 - B94 ) = ( B95 - B96 ))));
theorem
L349: (for B97 , B98 being (FinSequence of ( COMPLEX )) holds (( len B97 ) = ( len B98 ) implies (( Re ( B97 - B98 ) ) = ( ( Re B97 ) - ( Re B98 ) ) & ( Im ( B97 - B98 ) ) = ( ( Im B97 ) - ( Im B98 ) ))))
proof
let C96 , C97 being (FinSequence of ( COMPLEX ));
assume L350: ( len C96 ) = ( len C97 );
L351: ( len ( C96 - C97 ) ) = ( len C96 ) by L350 , L55;
L352: ( len C96 ) = ( len ( C96 *' ) ) by L1;
L353: ( len ( C96 + ( C96 *' ) ) ) = ( len C96 ) by L352 , L49;
L354: ( len C97 ) = ( len ( C97 *' ) ) by L1;
L355: ( len ( C97 + ( C97 *' ) ) ) = ( len C97 ) by L354 , L49;
thus L356: ( Re ( C96 - C97 ) ) = ( ( 1 / 2 ) * ( ( C96 - C97 ) + ( ( C96 *' ) - ( C97 *' ) ) ) ) by L350 , L141
.= ( ( 1 / 2 ) * ( ( ( C96 *' ) + ( C96 - C97 ) ) - ( C97 *' ) ) ) by L350 , L354 , L352 , L351 , L268
.= ( ( 1 / 2 ) * ( ( C96 *' ) + ( ( C96 - C97 ) - ( C97 *' ) ) ) ) by L350 , L354 , L352 , L351 , L268
.= ( ( 1 / 2 ) * ( ( C96 *' ) + ( C96 - ( C97 + ( C97 *' ) ) ) ) ) by L350 , L354 , L262
.= ( ( 1 / 2 ) * ( ( C96 + ( C96 *' ) ) - ( C97 + ( C97 *' ) ) ) ) by L350 , L352 , L355 , L268
.= ( ( Re C96 ) - ( Re C97 ) ) by L350 , L353 , L355 , L292;
L357: ( len ( C96 - ( C96 *' ) ) ) = ( len C96 ) by L352 , L55;
L358: ( len ( C97 - ( C97 *' ) ) ) = ( len C97 ) by L354 , L55;
thus L359: ( Im ( C96 - C97 ) ) = ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C96 - C97 ) - ( ( C96 *' ) - ( C97 *' ) ) ) ) by L350 , L141
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( C96 - C97 ) - ( C96 *' ) ) + ( C97 *' ) ) ) by L350 , L354 , L352 , L351 , L277
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C96 - ( ( C96 *' ) + C97 ) ) + ( C97 *' ) ) ) by L350 , L352 , L262
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( C96 - ( C96 *' ) ) - C97 ) + ( C97 *' ) ) ) by L350 , L352 , L262
.= ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( C96 - ( C96 *' ) ) - ( C97 - ( C97 *' ) ) ) ) by L350 , L354 , L357 , L277
.= ( ( Im C96 ) - ( Im C97 ) ) by L350 , L357 , L358 , L292;
end;
theorem
L360: (for R5 being (FinSequence of ( COMPLEX )) holds (for B99 , B100 being  complex number holds ( B99 * ( B100 * R5 ) ) = ( ( B99 * B100 ) * R5 )))
proof
let R5 being (FinSequence of ( COMPLEX ));
let C98 , C99 being  complex number;
reconsider D52 = C98 , D53 = C99 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
thus L361: ( ( C98 * C99 ) * R5 ) = ( ( ( multcomplex ) [;] (( D52 * D53 ) , ( id ( COMPLEX ) )) ) * R5 ) by L25
.= ( ( ( multcomplex ) [;] (( ( multcomplex ) . (D52 , D53) ) , ( id ( COMPLEX ) )) ) * R5 ) by BINOP_2:def 5
.= ( ( ( multcomplex ) [;] (D52 , ( ( multcomplex ) [;] (D53 , ( id ( COMPLEX ) )) )) ) * R5 ) by FUNCOP_1:62
.= ( ( ( ( multcomplex ) [;] (D52 , ( id ( COMPLEX ) )) ) * ( ( multcomplex ) [;] (D53 , ( id ( COMPLEX ) )) ) ) * R5 ) by FUNCOP_1:55
.= ( ( ( multcomplex ) [;] (D52 , ( id ( COMPLEX ) )) ) * ( ( ( multcomplex ) [;] (D53 , ( id ( COMPLEX ) )) ) * R5 ) ) by RELAT_1:36
.= ( ( ( multcomplex ) [;] (D52 , ( id ( COMPLEX ) )) ) * ( C99 * R5 ) ) by L25
.= ( C98 * ( C99 * R5 ) ) by L25;
end;
L362: (for R3 being (FinSequence of ( COMPLEX )) holds ( - ( 0c ( len R3 ) ) ) = ( 0c ( len R3 ) ))
proof
let R3 being (FinSequence of ( COMPLEX ));
L363: ( - ( 0c ( len R3 ) ) ) = ( - ( ( len R3 ) |-> ( 0c ) ) ) by SEQ_4:def 12
.= ( ( compcomplex ) * ( ( len R3 ) |-> ( 0c ) ) ) by SEQ_4:def 8
.= ( ( len R3 ) |-> ( ( compcomplex ) . ( 0c ) ) ) by FINSEQOP:16
.= ( ( len R3 ) |-> ( - ( 0c ) ) ) by BINOP_2:def 1
.= ( 0c ( len R3 ) ) by SEQ_4:def 12;
thus L364: thesis by L363;
end;
theorem
L365: (for R3 being (FinSequence of ( COMPLEX )) holds (for B101 being  complex number holds ( ( - B101 ) * R3 ) = ( - ( B101 * R3 ) )))
proof
let R3 being (FinSequence of ( COMPLEX ));
let C100 being  complex number;
L366: ( len ( ( - C100 ) * R3 ) ) = ( len R3 ) by L39;
L367: ( len ( C100 * R3 ) ) = ( len R3 ) by L39;
L368: ( ( ( - C100 ) * R3 ) + ( C100 * R3 ) ) = ( ( ( ( - 1 ) * C100 ) * R3 ) + ( C100 * R3 ) )
.= ( ( - ( C100 * R3 ) ) + ( C100 * R3 ) ) by L360
.= ( - ( ( C100 * R3 ) - ( C100 * R3 ) ) ) by L367 , L272
.= ( - ( 0c ( len R3 ) ) ) by L367 , L250
.= ( 0c ( len R3 ) ) by L362;
thus L369: thesis by L368 , L366 , L367 , L239;
end;
theorem
L370: (for R12 being (Function of ( COMPLEX ) , ( COMPLEX )) holds (for R13 being (Function of ( REAL ) , ( REAL )) holds (for B102 being (FinSequence of ( COMPLEX )) holds (for B103 being (FinSequence of ( REAL )) holds ((( len B102 ) = ( len B103 ) & (for R1 being (Element of ( NAT )) holds (R1 in ( dom B102 ) implies ( R12 . ( B102 . R1 ) ) = ( R13 . ( B103 . R1 ) )))) implies ( R12 * B102 ) = ( R13 * B103 ))))))
proof
let R12 being (Function of ( COMPLEX ) , ( COMPLEX ));
let R13 being (Function of ( REAL ) , ( REAL ));
let C101 being (FinSequence of ( COMPLEX ));
let C102 being (FinSequence of ( REAL ));
assume that
L371: ( len C101 ) = ( len C102 )
and
L372: (for R1 being (Element of ( NAT )) holds (R1 in ( dom C101 ) implies ( R12 . ( C101 . R1 ) ) = ( R13 . ( C102 . R1 ) )));
L373: ( len ( R13 * C102 ) ) = ( len C101 ) by L371 , FINSEQ_2:33;
L374:
now
let C103 being Nat;
assume that
L375: 1 <= C103
and
L376: C103 <= ( len ( R12 * C101 ) );
L377: C103 <= ( len C101 ) by L376 , FINSEQ_2:33;
L378: C103 in ( dom C101 ) by L377 , L375 , FINSEQ_3:25;
L379: C103 in ( dom ( R13 * C102 ) ) by L373 , L375 , L377 , FINSEQ_3:25;
L380: C103 in ( dom ( R12 * C101 ) ) by L375 , L376 , FINSEQ_3:25;
thus L381: ( ( R12 * C101 ) . C103 ) = ( R12 . ( C101 . C103 ) ) by L380 , FUNCT_1:12
.= ( R13 . ( C102 . C103 ) ) by L372 , L378
.= ( ( R13 * C102 ) . C103 ) by L379 , FUNCT_1:12;
end;
L382: ( len ( R12 * C101 ) ) = ( len C101 ) by FINSEQ_2:33;
thus L383: thesis by L382 , L373 , L374 , FINSEQ_1:14;
end;
theorem
L384: (for B104 being (FinSequence of ( COMPLEX )) holds (for B105 being (FinSequence of ( REAL )) holds ((B104 = B105 & ( len B104 ) = ( len B105 )) implies ( ( compcomplex ) * B104 ) = ( ( compreal ) * B105 ))))
proof
let C104 being (FinSequence of ( COMPLEX ));
let C105 being (FinSequence of ( REAL ));
assume that
L385: C104 = C105
and
L386: ( len C104 ) = ( len C105 );
L387: (for R1 being (Element of ( NAT )) holds (R1 in ( dom C104 ) implies ( ( compcomplex ) . ( C104 . R1 ) ) = ( ( compreal ) . ( C105 . R1 ) )))
proof
let R1 being (Element of ( NAT ));
assume L388: R1 in ( dom C104 );
L389: ( - ( C104 . R1 ) ) = ( ( compcomplex ) . ( C104 . R1 ) ) by BINOP_2:def 1;
thus L390: thesis by L389 , L385 , BINOP_2:def 7;
end;
thus L391: thesis by L387 , L386 , L370;
end;
theorem
L392: (for B106 being (FinSequence of ( COMPLEX )) holds (for B107 being (FinSequence of ( REAL )) holds ((B106 = B107 & ( len B106 ) = ( len B107 )) implies ( - B106 ) = ( - B107 ))));
theorem
L393: (for B108 being (FinSequence of ( COMPLEX )) holds (( Re ( ( <i> ) * B108 ) ) = ( - ( Im B108 ) ) & ( Im ( ( <i> ) * B108 ) ) = ( Re B108 )))
proof
let C106 being (FinSequence of ( COMPLEX ));
L394: ( len ( C106 *' ) ) = ( len C106 ) by L1;
L395: ( Im ( ( <i> ) * C106 ) ) = ( ( ( - ( 1 / 2 ) ) * ( <i> ) ) * ( ( ( <i> ) * C106 ) - ( ( - ( <i> ) ) * ( C106 *' ) ) ) ) by L97 , COMPLEX1:31
.= ( ( ( - ( 1 / 2 ) ) * ( <i> ) ) * ( ( ( <i> ) * C106 ) + ( - ( - ( ( <i> ) * ( C106 *' ) ) ) ) ) ) by L365
.= ( ( ( - ( 1 / 2 ) ) * ( <i> ) ) * ( ( <i> ) * ( C106 + ( C106 *' ) ) ) ) by L394 , L233
.= ( ( ( ( - ( 1 / 2 ) ) * ( <i> ) ) * ( <i> ) ) * ( C106 + ( C106 *' ) ) ) by L360
.= ( Re C106 );
L396: ( Re ( ( <i> ) * C106 ) ) = ( ( 1 / 2 ) * ( ( ( <i> ) * C106 ) + ( ( - ( <i> ) ) * ( C106 *' ) ) ) ) by L97 , COMPLEX1:31
.= ( ( 1 / 2 ) * ( ( ( <i> ) * C106 ) - ( ( <i> ) * ( C106 *' ) ) ) ) by L365
.= ( ( 1 / 2 ) * ( ( <i> ) * ( C106 - ( C106 *' ) ) ) ) by L394 , L292
.= ( ( ( 1 / 2 ) * ( <i> ) ) * ( C106 - ( C106 *' ) ) ) by L360
.= ( ( ( - 1 ) * ( ( - ( 1 / 2 ) ) * ( <i> ) ) ) * ( C106 - ( C106 *' ) ) )
.= ( - ( Im C106 ) ) by L360;
thus L397: thesis by L396 , L395;
end;
theorem
L398: (for B109 , B110 being (FinSequence of ( COMPLEX )) holds (( len B109 ) = ( len B110 ) implies |( ( ( <i> ) * B109 ) , B110 )| = ( ( <i> ) * |( B109 , B110 )| )))
proof
let C107 , C108 being (FinSequence of ( COMPLEX ));
assume L399: ( len C107 ) = ( len C108 );
L400: ( len ( Im C108 ) ) = ( len C108 ) by L324;
L401: ( len ( Re C108 ) ) = ( len C108 ) by L324;
L402: ( len ( Im C107 ) ) = ( len C107 ) by L324;
L403: |( ( ( <i> ) * C107 ) , C108 )| = ( ( ( |( ( - ( Im C107 ) ) , ( Re C108 ) )| - ( ( <i> ) * |( ( Re ( ( <i> ) * C107 ) ) , ( Im C108 ) )| ) ) + ( ( <i> ) * |( ( Im ( ( <i> ) * C107 ) ) , ( Re C108 ) )| ) ) + |( ( Im ( ( <i> ) * C107 ) ) , ( Im C108 ) )| ) by L393
.= ( ( ( |( ( - ( Im C107 ) ) , ( Re C108 ) )| - ( ( <i> ) * |( ( - ( Im C107 ) ) , ( Im C108 ) )| ) ) + ( ( <i> ) * |( ( Im ( ( <i> ) * C107 ) ) , ( Re C108 ) )| ) ) + |( ( Im ( ( <i> ) * C107 ) ) , ( Im C108 ) )| ) by L393
.= ( ( ( |( ( - ( Im C107 ) ) , ( Re C108 ) )| - ( ( <i> ) * |( ( - ( Im C107 ) ) , ( Im C108 ) )| ) ) + ( ( <i> ) * |( ( Re C107 ) , ( Re C108 ) )| ) ) + |( ( Im ( ( <i> ) * C107 ) ) , ( Im C108 ) )| ) by L393
.= ( ( ( |( ( - ( Im C107 ) ) , ( Re C108 ) )| - ( ( <i> ) * |( ( - ( Im C107 ) ) , ( Im C108 ) )| ) ) + ( ( <i> ) * |( ( Re C107 ) , ( Re C108 ) )| ) ) + |( ( Re C107 ) , ( Im C108 ) )| ) by L393
.= ( ( ( ( - |( ( Im C107 ) , ( Re C108 ) )| ) - ( ( <i> ) * |( ( - ( Im C107 ) ) , ( Im C108 ) )| ) ) + ( ( <i> ) * |( ( Re C107 ) , ( Re C108 ) )| ) ) + |( ( Re C107 ) , ( Im C108 ) )| ) by L399 , L401 , L402 , RVSUM_1:122
.= ( ( ( ( - |( ( Im C107 ) , ( Re C108 ) )| ) - ( ( <i> ) * ( - |( ( Im C107 ) , ( Im C108 ) )| ) ) ) + ( ( <i> ) * |( ( Re C107 ) , ( Re C108 ) )| ) ) + |( ( Re C107 ) , ( Im C108 ) )| ) by L399 , L402 , L400 , RVSUM_1:122
.= ( ( <i> ) * |( C107 , C108 )| );
thus L404: thesis by L403;
end;
theorem
L405: (for B111 , B112 being (FinSequence of ( COMPLEX )) holds (( len B111 ) = ( len B112 ) implies |( B111 , ( ( <i> ) * B112 ) )| = ( - ( ( <i> ) * |( B111 , B112 )| ) )))
proof
let C109 , C110 being (FinSequence of ( COMPLEX ));
assume L406: ( len C109 ) = ( len C110 );
L407: ( len ( Im C109 ) ) = ( len C109 ) by L324;
L408: ( len ( Re C109 ) ) = ( len C109 ) by L324;
L409: ( len ( Im C110 ) ) = ( len C110 ) by L324;
L410: |( C109 , ( ( <i> ) * C110 ) )| = ( ( ( |( ( Re C109 ) , ( - ( Im C110 ) ) )| - ( ( <i> ) * |( ( Re C109 ) , ( Im ( ( <i> ) * C110 ) ) )| ) ) + ( ( <i> ) * |( ( Im C109 ) , ( Re ( ( <i> ) * C110 ) ) )| ) ) + |( ( Im C109 ) , ( Im ( ( <i> ) * C110 ) ) )| ) by L393
.= ( ( ( |( ( Re C109 ) , ( - ( Im C110 ) ) )| - ( ( <i> ) * |( ( Re C109 ) , ( Re C110 ) )| ) ) + ( ( <i> ) * |( ( Im C109 ) , ( Re ( ( <i> ) * C110 ) ) )| ) ) + |( ( Im C109 ) , ( Im ( ( <i> ) * C110 ) ) )| ) by L393
.= ( ( ( |( ( Re C109 ) , ( - ( Im C110 ) ) )| - ( ( <i> ) * |( ( Re C109 ) , ( Re C110 ) )| ) ) + ( ( <i> ) * |( ( Im C109 ) , ( - ( Im C110 ) ) )| ) ) + |( ( Im C109 ) , ( Im ( ( <i> ) * C110 ) ) )| ) by L393
.= ( ( ( |( ( Re C109 ) , ( - ( Im C110 ) ) )| - ( ( <i> ) * |( ( Re C109 ) , ( Re C110 ) )| ) ) + ( ( <i> ) * |( ( Im C109 ) , ( - ( Im C110 ) ) )| ) ) + |( ( Im C109 ) , ( Re C110 ) )| ) by L393
.= ( ( ( ( - |( ( Re C109 ) , ( Im C110 ) )| ) - ( ( <i> ) * |( ( Re C109 ) , ( Re C110 ) )| ) ) + ( ( <i> ) * |( ( Im C109 ) , ( - ( Im C110 ) ) )| ) ) + |( ( Im C109 ) , ( Re C110 ) )| ) by L406 , L408 , L409 , RVSUM_1:122
.= ( ( ( ( - |( ( Re C109 ) , ( Im C110 ) )| ) - ( ( <i> ) * |( ( Re C109 ) , ( Re C110 ) )| ) ) + ( ( <i> ) * ( - |( ( Im C109 ) , ( Im C110 ) )| ) ) ) + |( ( Im C109 ) , ( Re C110 ) )| ) by L406 , L407 , L409 , RVSUM_1:122
.= ( - ( ( <i> ) * |( C109 , C110 )| ) );
thus L411: thesis by L410;
end;
theorem
L412: (for B113 being (Element of ( COMPLEX )) holds (for B114 being (FinSequence of ( COMPLEX )) holds (for B115 being (Element of ( REAL )) holds (for B116 being (FinSequence of ( REAL )) holds ((B113 = B115 & B114 = B116 & ( len B114 ) = ( len B116 )) implies ( ( B113 multcomplex ) * B114 ) = ( ( B115 multreal ) * B116 ))))))
proof
let C111 being (Element of ( COMPLEX ));
let C112 being (FinSequence of ( COMPLEX ));
let C113 being (Element of ( REAL ));
let C114 being (FinSequence of ( REAL ));
assume that
L413: (C111 = C113 & C112 = C114)
and
L414: ( len C112 ) = ( len C114 );
L415: (for R1 being (Element of ( NAT )) holds (R1 in ( dom C112 ) implies ( ( C111 multcomplex ) . ( C112 . R1 ) ) = ( ( C113 multreal ) . ( C114 . R1 ) )))
proof
let R1 being (Element of ( NAT ));
assume L416: R1 in ( dom C112 );
L417: ( ( C113 * C114 ) . R1 ) = ( C113 * ( C114 . R1 ) ) by RVSUM_1:44
.= ( ( multreal ) . (C113 , ( C114 . R1 )) ) by BINOP_2:def 11
.= ( ( multreal ) . (C113 , ( ( id ( REAL ) ) . ( C114 . R1 ) )) ) by FUNCT_1:18
.= ( ( ( multreal ) [;] (C113 , ( id ( REAL ) )) ) . ( C114 . R1 ) ) by FUNCOP_1:53
.= ( ( C113 multreal ) . ( C114 . R1 ) ) by RVSUM_1:def 3;
L418: ( ( C111 * C112 ) . R1 ) = ( C111 * ( C112 . R1 ) ) by L88
.= ( ( multcomplex ) . (C111 , ( C112 . R1 )) ) by BINOP_2:def 5
.= ( ( multcomplex ) . (C111 , ( ( id ( COMPLEX ) ) . ( C112 . R1 ) )) ) by FUNCT_1:18
.= ( ( ( multcomplex ) [;] (C111 , ( id ( COMPLEX ) )) ) . ( C112 . R1 ) ) by FUNCOP_1:53
.= ( ( C111 multcomplex ) . ( C112 . R1 ) ) by SEQ_4:def 4;
thus L419: thesis by L418 , L413 , L417;
end;
thus L420: thesis by L415 , L414 , L370;
end;
theorem
L421: (for B117 being  complex number holds (for B118 being (FinSequence of ( COMPLEX )) holds (for B119 being (Element of ( REAL )) holds (for B120 being (FinSequence of ( REAL )) holds ((B117 = B119 & B118 = B120 & ( len B118 ) = ( len B120 )) implies ( B117 * B118 ) = ( B119 * B120 ))))));
theorem
L422: (for R5 being (FinSequence of ( COMPLEX )) holds (for B121 , B122 being  complex number holds ( ( B121 + B122 ) * R5 ) = ( ( B121 * R5 ) + ( B122 * R5 ) )))
proof
let R5 being (FinSequence of ( COMPLEX ));
let C115 , C116 being  complex number;
reconsider D54 = C115 , D55 = C116 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
set D56 = ( ( multcomplex ) [;] (D54 , ( id ( COMPLEX ) )) );
set D57 = ( ( multcomplex ) [;] (D55 , ( id ( COMPLEX ) )) );
thus L423: ( ( C115 + C116 ) * R5 ) = ( ( ( multcomplex ) [;] (( D54 + D55 ) , ( id ( COMPLEX ) )) ) * R5 ) by L25
.= ( ( ( multcomplex ) [;] (( ( addcomplex ) . (D54 , D55) ) , ( id ( COMPLEX ) )) ) * R5 ) by BINOP_2:def 3
.= ( ( ( addcomplex ) .: (D56 , D57) ) * R5 ) by FINSEQOP:35 , SEQ_4:54
.= ( ( addcomplex ) .: (( D56 * R5 ) , ( D57 * R5 )) ) by FUNCOP_1:25
.= ( ( D56 * R5 ) + ( D57 * R5 ) ) by SEQ_4:def 6
.= ( ( C115 * R5 ) + ( D57 * R5 ) ) by L25
.= ( ( C115 * R5 ) + ( C116 * R5 ) ) by L25;
end;
theorem
L424: (for R5 being (FinSequence of ( COMPLEX )) holds (for B123 , B124 being  complex number holds ( ( B123 - B124 ) * R5 ) = ( ( B123 * R5 ) - ( B124 * R5 ) )))
proof
let R5 being (FinSequence of ( COMPLEX ));
let C117 , C118 being  complex number;
reconsider D58 = C117 , D59 = C118 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L425: ( ( C117 - C118 ) * R5 ) = ( ( C117 + ( - C118 ) ) * R5 )
.= ( ( D58 * R5 ) + ( ( - D59 ) * R5 ) ) by L422
.= ( ( C117 * R5 ) - ( C118 * R5 ) ) by L365;
thus L426: thesis by L425;
end;
theorem
L427: (for B125 being (Element of ( COMPLEX )) holds (for B126 being (FinSequence of ( COMPLEX )) holds (( Re ( B125 * B126 ) ) = ( ( ( Re B125 ) * ( Re B126 ) ) - ( ( Im B125 ) * ( Im B126 ) ) ) & ( Im ( B125 * B126 ) ) = ( ( ( Im B125 ) * ( Re B126 ) ) + ( ( Re B125 ) * ( Im B126 ) ) ))))
proof
let C119 being (Element of ( COMPLEX ));
let C120 being (FinSequence of ( COMPLEX ));
reconsider D60 = ( Re C119 ) , D61 = ( Im C119 ) as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L428: ( len ( C120 *' ) ) = ( len C120 ) by L1;
L429: ( len ( ( ( 1 / 2 ) * D60 ) * C120 ) ) = ( len C120 ) by L39;
L430: ( len ( ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) + ( ( ( 1 / 2 ) * D60 ) * C120 ) ) ) = ( len ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) ) by L429 , L39 , L49;
L431: ( len ( ( ( 1 / 2 ) * D60 ) * C120 ) ) = ( len C120 ) by L39;
L432: (( len ( D60 * C120 ) ) = ( len C120 ) & ( len ( ( ( <i> ) * D61 ) * C120 ) ) = ( len C120 )) by L39;
L433: ( ( Re C119 ) * ( Re C120 ) ) = ( ( D60 * ( 1 / 2 ) ) * ( C120 + ( C120 *' ) ) ) by L360
.= ( ( ( ( D60 * 1 ) / 2 ) * C120 ) + ( ( ( D60 * 1 ) / 2 ) * ( C120 *' ) ) ) by L428 , L233;
L434: (( len ( Re C120 ) ) = ( len C120 ) & ( len ( ( Re C119 ) * ( Re C120 ) ) ) = ( len ( Re C120 ) )) by L324 , RVSUM_1:117;
L435: (( len ( ( D60 - ( D61 * ( <i> ) ) ) * ( C120 *' ) ) ) = ( len ( C120 *' ) ) & ( len ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) = ( len C120 )) by L39;
L436: ( len ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) = ( len ( C120 *' ) ) by L39;
L437: ( ( Im C119 ) * ( Im C120 ) ) = ( ( D61 * ( - ( ( 1 / 2 ) * ( <i> ) ) ) ) * ( C120 - ( C120 *' ) ) ) by L360
.= ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * C120 ) - ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) by L428 , L292;
L438: ( len ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * C120 ) ) = ( len C120 ) by L39;
L439: (( len ( D60 * ( C120 *' ) ) ) = ( len ( C120 *' ) ) & ( len ( ( D61 * ( <i> ) ) * ( C120 *' ) ) ) = ( len ( C120 *' ) )) by L39;
L440: (( len ( ( ( 1 / 2 ) * D60 ) * ( C120 *' ) ) ) = ( len ( C120 *' ) ) & ( len ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) ) = ( len C120 )) by L39;
L441: ( Re ( C119 * C120 ) ) = ( ( 1 / 2 ) * ( ( ( C119 *' ) * ( C120 *' ) ) + ( C119 * C120 ) ) ) by L97
.= ( ( 1 / 2 ) * ( ( ( C119 *' ) * ( C120 *' ) ) + ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by COMPLEX1:13
.= ( ( 1 / 2 ) * ( ( ( D60 - ( D61 * ( <i> ) ) ) * ( C120 *' ) ) + ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by COMPLEX1:def 11
.= ( ( ( 1 / 2 ) * ( ( D60 - ( D61 * ( <i> ) ) ) * ( C120 *' ) ) ) + ( ( 1 / 2 ) * ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by L428 , L435 , L233
.= ( ( ( 1 / 2 ) * ( ( D60 - ( D61 * ( <i> ) ) ) * ( C120 *' ) ) ) + ( ( 1 / 2 ) * ( ( D60 * C120 ) + ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L422
.= ( ( ( 1 / 2 ) * ( ( D60 * ( C120 *' ) ) - ( ( D61 * ( <i> ) ) * ( C120 *' ) ) ) ) + ( ( 1 / 2 ) * ( ( D60 * C120 ) + ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L424
.= ( ( ( 1 / 2 ) * ( ( D60 * ( C120 *' ) ) - ( ( D61 * ( <i> ) ) * ( C120 *' ) ) ) ) + ( ( ( 1 / 2 ) * ( D60 * C120 ) ) + ( ( 1 / 2 ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L432 , L233
.= ( ( ( ( 1 / 2 ) * ( D60 * ( C120 *' ) ) ) - ( ( 1 / 2 ) * ( ( D61 * ( <i> ) ) * ( C120 *' ) ) ) ) + ( ( ( 1 / 2 ) * ( D60 * C120 ) ) + ( ( 1 / 2 ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L439 , L292
.= ( ( ( ( 1 / 2 ) * ( D60 * ( C120 *' ) ) ) - ( ( 1 / 2 ) * ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) ) + ( ( ( 1 / 2 ) * ( D60 * C120 ) ) + ( ( ( 1 / 2 ) * ( ( <i> ) * D61 ) ) * C120 ) ) ) by L360
.= ( ( ( ( 1 / 2 ) * ( D60 * ( C120 *' ) ) ) + ( - ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * ( C120 *' ) ) ) ) + ( ( ( 1 / 2 ) * ( D60 * C120 ) ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) ) ) by L360
.= ( ( ( ( 1 / 2 ) * ( D60 * ( C120 *' ) ) ) + ( ( - ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) ) * ( C120 *' ) ) ) + ( ( ( 1 / 2 ) * ( D60 * C120 ) ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) ) ) by L365
.= ( ( ( ( ( 1 / 2 ) * D60 ) * ( C120 *' ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) + ( ( ( 1 / 2 ) * ( D60 * C120 ) ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) ) ) by L360
.= ( ( ( ( ( 1 / 2 ) * D60 ) * C120 ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) ) + ( ( ( ( 1 / 2 ) * D60 ) * ( C120 *' ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) ) by L360
.= ( ( ( ( ( ( ( 1 / 2 ) * ( <i> ) ) * D61 ) * C120 ) + ( ( ( 1 / 2 ) * D60 ) * C120 ) ) + ( ( ( 1 / 2 ) * D60 ) * ( C120 *' ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) by L428 , L436 , L440 , L430 , L228
.= ( ( ( ( ( ( 1 / 2 ) * D60 ) * C120 ) + ( ( ( 1 / 2 ) * D60 ) * ( C120 *' ) ) ) + ( ( - ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) ) * C120 ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) by L428 , L431 , L440 , L228
.= ( ( ( ( ( ( 1 / 2 ) * D60 ) * C120 ) + ( ( ( 1 / 2 ) * D60 ) * ( C120 *' ) ) ) - ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * C120 ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D61 ) * ( C120 *' ) ) ) by L365
.= ( ( ( Re C119 ) * ( Re C120 ) ) - ( ( Im C119 ) * ( Im C120 ) ) ) by L428 , L433 , L437 , L434 , L438 , L436 , L277;
L442: ( len ( ( ( ( 1 / 2 ) * ( <i> ) ) * D60 ) * ( C120 *' ) ) ) = ( len ( C120 *' ) ) by L39;
L443: ( ( Im C119 ) * ( Re C120 ) ) = ( ( D61 * ( 1 / 2 ) ) * ( C120 + ( C120 *' ) ) ) by L360
.= ( ( ( ( 1 / 2 ) * D61 ) * C120 ) + ( ( ( 1 / 2 ) * D61 ) * ( C120 *' ) ) ) by L428 , L233;
L444: (( len ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) = ( len ( C120 *' ) ) & ( len ( ( - D60 ) * ( C120 *' ) ) ) = ( len ( C120 *' ) )) by L39;
L445: ( len ( ( 1 / 2 ) * ( D61 * C120 ) ) ) = ( len ( D61 * C120 ) ) by L39;
L446: (( len ( D61 * ( C120 *' ) ) ) = ( len ( C120 *' ) ) & ( len ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) ) = ( len ( D61 * ( C120 *' ) ) )) by L39;
L447: ( len ( ( ( 1 / 2 ) * ( D61 * C120 ) ) + ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) ) ) = ( len ( ( 1 / 2 ) * ( D61 * C120 ) ) ) by L446 , L428 , L445 , L39 , L49;
L448: ( len ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) ) = ( len C120 ) by L39;
L449: ( len ( ( ( 1 / 2 ) * ( D61 * C120 ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) ) ) = ( len ( ( 1 / 2 ) * ( D61 * C120 ) ) ) by L448 , L445 , L39 , L49;
L450: ( ( Re C119 ) * ( Im C120 ) ) = ( ( D60 * ( - ( ( 1 / 2 ) * ( <i> ) ) ) ) * ( C120 - ( C120 *' ) ) ) by L360
.= ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) - ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * ( C120 *' ) ) ) by L428 , L292;
L451: ( len ( D61 * C120 ) ) = ( len C120 ) by L39;
L452: (( len ( ( C119 * C120 ) *' ) ) = ( len ( C119 * C120 ) ) & ( len ( - ( ( C119 * C120 ) *' ) ) ) = ( len ( ( C119 * C120 ) *' ) )) by L1 , L43;
L453: ( Im ( C119 * C120 ) ) = ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - ( ( C119 * C120 ) *' ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C119 * C120 ) ) ) by L452 , L233
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - ( ( C119 *' ) * ( C120 *' ) ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( C119 * C120 ) ) ) by L97
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - ( ( C119 *' ) * ( C120 *' ) ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by COMPLEX1:13
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - ( ( D60 - ( D61 * ( <i> ) ) ) * ( C120 *' ) ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by COMPLEX1:def 11
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( - ( D60 - ( D61 * ( <i> ) ) ) ) * ( C120 *' ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by L365
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( - D60 ) + ( D61 * ( <i> ) ) ) * ( C120 *' ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) )
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( - D60 ) * ( C120 *' ) ) + ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( D60 + ( ( <i> ) * D61 ) ) * C120 ) ) ) by L422
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( - D60 ) * ( C120 *' ) ) + ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( D60 * C120 ) + ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L422
.= ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( - D60 ) * ( C120 *' ) ) + ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( D60 * C120 ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L432 , L233
.= ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( - D60 ) * ( C120 *' ) ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( D60 * C120 ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L444 , L233
.= ( ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - D60 ) ) * ( C120 *' ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * ( C120 *' ) ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( D60 * C120 ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L360
.= ( ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - D60 ) ) * ( C120 *' ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( <i> ) * ( D61 * ( C120 *' ) ) ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( D60 * C120 ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L360
.= ( ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - D60 ) ) * ( C120 *' ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( <i> ) ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( D60 * C120 ) ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L360
.= ( ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - D60 ) ) * ( C120 *' ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( <i> ) ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( ( <i> ) * D61 ) * C120 ) ) ) ) by L360
.= ( ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( - D60 ) ) * ( C120 *' ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( <i> ) ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) + ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * ( ( <i> ) * ( D61 * C120 ) ) ) ) ) by L360
.= ( ( ( ( 1 / 2 ) * ( D61 * C120 ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) ) + ( ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D60 ) * ( C120 *' ) ) ) ) by L360
.= ( ( ( ( ( 1 / 2 ) * ( D61 * C120 ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) ) + ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D60 ) * ( C120 *' ) ) ) by L428 , L451 , L445 , L446 , L442 , L449 , L228
.= ( ( ( ( ( 1 / 2 ) * ( D61 * C120 ) ) + ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D60 ) * ( C120 *' ) ) ) by L428 , L451 , L445 , L448 , L446 , L228
.= ( ( ( ( 1 / 2 ) * ( D61 * C120 ) ) + ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D60 ) * ( C120 *' ) ) ) ) by L428 , L451 , L445 , L448 , L442 , L447 , L228
.= ( ( ( ( ( 1 / 2 ) * D61 ) * C120 ) + ( ( 1 / 2 ) * ( D61 * ( C120 *' ) ) ) ) + ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) + ( ( ( ( 1 / 2 ) * ( <i> ) ) * D60 ) * ( C120 *' ) ) ) ) by L360
.= ( ( ( ( ( 1 / 2 ) * D61 ) * C120 ) + ( ( ( 1 / 2 ) * D61 ) * ( C120 *' ) ) ) + ( ( ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) * C120 ) + ( ( - ( ( - ( ( 1 / 2 ) * ( <i> ) ) ) * D60 ) ) * ( C120 *' ) ) ) ) by L360
.= ( ( ( Im C119 ) * ( Re C120 ) ) + ( ( Re C119 ) * ( Im C120 ) ) ) by L443 , L450 , L365;
thus L454: thesis by L453 , L441;
end;
begin
theorem
L455: (for B127 , B128 , B129 being (FinSequence of ( COMPLEX )) holds ((( len B127 ) = ( len B128 ) & ( len B128 ) = ( len B129 )) implies |( ( B127 + B128 ) , B129 )| = ( |( B127 , B129 )| + |( B128 , B129 )| )))
proof
let C121 , C122 , C123 being (FinSequence of ( COMPLEX ));
assume that
L456: ( len C121 ) = ( len C122 )
and
L457: ( len C122 ) = ( len C123 );
L458: (( len ( Re C121 ) ) = ( len C121 ) & ( len ( Re C122 ) ) = ( len C122 )) by L324;
L459: ( len ( Im C123 ) ) = ( len C123 ) by L324;
L460: (( len ( Im C121 ) ) = ( len C121 ) & ( len ( Im C122 ) ) = ( len C122 )) by L324;
L461: ( len ( Re C123 ) ) = ( len C123 ) by L324;
L462: |( ( C121 + C122 ) , C123 )| = ( ( ( |( ( ( Re C121 ) + ( Re C122 ) ) , ( Re C123 ) )| - ( ( <i> ) * |( ( Re ( C121 + C122 ) ) , ( Im C123 ) )| ) ) + ( ( <i> ) * |( ( Im ( C121 + C122 ) ) , ( Re C123 ) )| ) ) + |( ( Im ( C121 + C122 ) ) , ( Im C123 ) )| ) by L456 , L329
.= ( ( ( |( ( ( Re C121 ) + ( Re C122 ) ) , ( Re C123 ) )| - ( ( <i> ) * |( ( ( Re C121 ) + ( Re C122 ) ) , ( Im C123 ) )| ) ) + ( ( <i> ) * |( ( Im ( C121 + C122 ) ) , ( Re C123 ) )| ) ) + |( ( Im ( C121 + C122 ) ) , ( Im C123 ) )| ) by L456 , L329
.= ( ( ( |( ( ( Re C121 ) + ( Re C122 ) ) , ( Re C123 ) )| - ( ( <i> ) * |( ( ( Re C121 ) + ( Re C122 ) ) , ( Im C123 ) )| ) ) + ( ( <i> ) * |( ( ( Im C121 ) + ( Im C122 ) ) , ( Re C123 ) )| ) ) + |( ( Im ( C121 + C122 ) ) , ( Im C123 ) )| ) by L456 , L329
.= ( ( ( |( ( ( Re C121 ) + ( Re C122 ) ) , ( Re C123 ) )| - ( ( <i> ) * |( ( ( Re C121 ) + ( Re C122 ) ) , ( Im C123 ) )| ) ) + ( ( <i> ) * |( ( ( Im C121 ) + ( Im C122 ) ) , ( Re C123 ) )| ) ) + |( ( ( Im C121 ) + ( Im C122 ) ) , ( Im C123 ) )| ) by L456 , L329
.= ( ( ( ( |( ( Re C121 ) , ( Re C123 ) )| + |( ( Re C122 ) , ( Re C123 ) )| ) - ( ( <i> ) * |( ( ( Re C121 ) + ( Re C122 ) ) , ( Im C123 ) )| ) ) + ( ( <i> ) * |( ( ( Im C121 ) + ( Im C122 ) ) , ( Re C123 ) )| ) ) + |( ( ( Im C121 ) + ( Im C122 ) ) , ( Im C123 ) )| ) by L456 , L457 , L458 , L461 , RVSUM_1:120
.= ( ( ( ( |( ( Re C121 ) , ( Re C123 ) )| + |( ( Re C122 ) , ( Re C123 ) )| ) - ( ( <i> ) * ( |( ( Re C121 ) , ( Im C123 ) )| + |( ( Re C122 ) , ( Im C123 ) )| ) ) ) + ( ( <i> ) * |( ( ( Im C121 ) + ( Im C122 ) ) , ( Re C123 ) )| ) ) + |( ( ( Im C121 ) + ( Im C122 ) ) , ( Im C123 ) )| ) by L456 , L457 , L458 , L459 , RVSUM_1:120
.= ( ( ( ( |( ( Re C121 ) , ( Re C123 ) )| + |( ( Re C122 ) , ( Re C123 ) )| ) - ( ( <i> ) * ( |( ( Re C121 ) , ( Im C123 ) )| + |( ( Re C122 ) , ( Im C123 ) )| ) ) ) + ( ( <i> ) * ( |( ( Im C121 ) , ( Re C123 ) )| + |( ( Im C122 ) , ( Re C123 ) )| ) ) ) + |( ( ( Im C121 ) + ( Im C122 ) ) , ( Im C123 ) )| ) by L456 , L457 , L461 , L460 , RVSUM_1:120
.= ( ( ( ( |( ( Re C121 ) , ( Re C123 ) )| + |( ( Re C122 ) , ( Re C123 ) )| ) - ( ( <i> ) * ( |( ( Re C121 ) , ( Im C123 ) )| + |( ( Re C122 ) , ( Im C123 ) )| ) ) ) + ( ( <i> ) * ( |( ( Im C121 ) , ( Re C123 ) )| + |( ( Im C122 ) , ( Re C123 ) )| ) ) ) + ( |( ( Im C121 ) , ( Im C123 ) )| + |( ( Im C122 ) , ( Im C123 ) )| ) ) by L456 , L457 , L460 , L459 , RVSUM_1:120
.= ( |( C121 , C123 )| + |( C122 , C123 )| );
thus L463: thesis by L462;
end;
theorem
L464: (for B130 , B131 being (FinSequence of ( COMPLEX )) holds (( len B130 ) = ( len B131 ) implies |( ( - B130 ) , B131 )| = ( - |( B130 , B131 )| )))
proof
let C124 , C125 being (FinSequence of ( COMPLEX ));
assume L465: ( len C124 ) = ( len C125 );
L466: ( len ( ( <i> ) * C124 ) ) = ( len C124 ) by L39;
L467: |( ( - C124 ) , C125 )| = |( ( ( ( <i> ) * ( <i> ) ) * C124 ) , C125 )|
.= |( ( ( <i> ) * ( ( <i> ) * C124 ) ) , C125 )| by L360
.= ( ( <i> ) * |( ( ( <i> ) * C124 ) , C125 )| ) by L465 , L466 , L398
.= ( ( <i> ) * ( ( <i> ) * |( C124 , C125 )| ) ) by L465 , L398
.= ( ( - 1 ) * |( C124 , C125 )| );
thus L468: thesis by L467;
end;
theorem
L469: (for B132 , B133 being (FinSequence of ( COMPLEX )) holds (( len B132 ) = ( len B133 ) implies |( B132 , ( - B133 ) )| = ( - |( B132 , B133 )| )))
proof
let C126 , C127 being (FinSequence of ( COMPLEX ));
assume L470: ( len C126 ) = ( len C127 );
L471: ( len ( ( <i> ) * C127 ) ) = ( len C127 ) by L39;
L472: |( C126 , ( - C127 ) )| = |( C126 , ( ( ( <i> ) * ( <i> ) ) * C127 ) )|
.= |( C126 , ( ( <i> ) * ( ( <i> ) * C127 ) ) )| by L360
.= ( - ( ( <i> ) * |( C126 , ( ( <i> ) * C127 ) )| ) ) by L470 , L471 , L405
.= ( - ( ( <i> ) * ( - ( ( <i> ) * |( C126 , C127 )| ) ) ) ) by L470 , L405
.= ( - |( C126 , C127 )| );
thus L473: thesis by L472;
end;
theorem
L474: (for B134 , B135 being (FinSequence of ( COMPLEX )) holds (( len B134 ) = ( len B135 ) implies |( ( - B134 ) , ( - B135 ) )| = |( B134 , B135 )|))
proof
let C128 , C129 being (FinSequence of ( COMPLEX ));
assume L475: ( len C128 ) = ( len C129 );
L476: ( len ( - C129 ) ) = ( len C128 ) by L475 , L43;
L477: |( ( - C128 ) , ( - C129 ) )| = ( - |( C128 , ( - C129 ) )| ) by L476 , L464
.= ( - ( - |( C128 , C129 )| ) ) by L475 , L469;
thus L478: thesis by L477;
end;
theorem
L479: (for B136 , B137 , B138 being (FinSequence of ( COMPLEX )) holds ((( len B136 ) = ( len B137 ) & ( len B137 ) = ( len B138 )) implies |( ( B136 - B137 ) , B138 )| = ( |( B136 , B138 )| - |( B137 , B138 )| )))
proof
let C130 , C131 , C132 being (FinSequence of ( COMPLEX ));
assume that
L480: ( len C130 ) = ( len C131 )
and
L481: ( len C131 ) = ( len C132 );
L482: ( len ( - C131 ) ) = ( len C131 ) by L43;
L483: |( ( C130 - C131 ) , C132 )| = ( |( C130 , C132 )| + |( ( - C131 ) , C132 )| ) by L482 , L480 , L481 , L455
.= ( |( C130 , C132 )| + ( - |( C131 , C132 )| ) ) by L481 , L464;
thus L484: thesis by L483;
end;
theorem
L485: (for B139 , B140 , B141 being (FinSequence of ( COMPLEX )) holds ((( len B139 ) = ( len B140 ) & ( len B140 ) = ( len B141 )) implies |( B139 , ( B140 + B141 ) )| = ( |( B139 , B140 )| + |( B139 , B141 )| )))
proof
let C133 , C134 , C135 being (FinSequence of ( COMPLEX ));
assume that
L486: ( len C133 ) = ( len C134 )
and
L487: ( len C134 ) = ( len C135 );
L488: (( len ( Re C134 ) ) = ( len C134 ) & ( len ( Re C135 ) ) = ( len C135 )) by L324;
L489: ( len ( Im C133 ) ) = ( len C133 ) by L324;
L490: (( len ( Im C134 ) ) = ( len C134 ) & ( len ( Im C135 ) ) = ( len C135 )) by L324;
L491: ( len ( Re C133 ) ) = ( len C133 ) by L324;
L492: |( C133 , ( C134 + C135 ) )| = ( ( ( |( ( Re C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| - ( ( <i> ) * |( ( Re C133 ) , ( Im ( C134 + C135 ) ) )| ) ) + ( ( <i> ) * |( ( Im C133 ) , ( Re ( C134 + C135 ) ) )| ) ) + |( ( Im C133 ) , ( Im ( C134 + C135 ) ) )| ) by L487 , L329
.= ( ( ( |( ( Re C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| - ( ( <i> ) * |( ( Re C133 ) , ( Im ( C134 + C135 ) ) )| ) ) + ( ( <i> ) * |( ( Im C133 ) , ( Re ( C134 + C135 ) ) )| ) ) + |( ( Im C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) by L487 , L329
.= ( ( ( |( ( Re C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| - ( ( <i> ) * |( ( Re C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) ) + ( ( <i> ) * |( ( Im C133 ) , ( Re ( C134 + C135 ) ) )| ) ) + |( ( Im C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) by L487 , L329
.= ( ( ( |( ( Re C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| - ( ( <i> ) * |( ( Re C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) ) + ( ( <i> ) * |( ( Im C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| ) ) + |( ( Im C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) by L487 , L329
.= ( ( ( ( |( ( Re C133 ) , ( Re C134 ) )| + |( ( Re C133 ) , ( Re C135 ) )| ) - ( ( <i> ) * |( ( Re C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) ) + ( ( <i> ) * |( ( Im C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| ) ) + |( ( Im C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) by L486 , L487 , L488 , L491 , RVSUM_1:120
.= ( ( ( ( |( ( Re C133 ) , ( Re C134 ) )| + |( ( Re C133 ) , ( Re C135 ) )| ) - ( ( <i> ) * |( ( Re C133 ) , ( ( Im C134 ) + ( Im C135 ) ) )| ) ) + ( ( <i> ) * |( ( Im C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| ) ) + ( |( ( Im C133 ) , ( Im C134 ) )| + |( ( Im C133 ) , ( Im C135 ) )| ) ) by L486 , L487 , L490 , L489 , RVSUM_1:120
.= ( ( ( ( |( ( Re C133 ) , ( Re C134 ) )| + |( ( Re C133 ) , ( Re C135 ) )| ) - ( ( <i> ) * ( |( ( Re C133 ) , ( Im C134 ) )| + |( ( Re C133 ) , ( Im C135 ) )| ) ) ) + ( ( <i> ) * |( ( Im C133 ) , ( ( Re C134 ) + ( Re C135 ) ) )| ) ) + ( |( ( Im C133 ) , ( Im C134 ) )| + |( ( Im C133 ) , ( Im C135 ) )| ) ) by L486 , L487 , L491 , L490 , RVSUM_1:120
.= ( ( ( ( |( ( Re C133 ) , ( Re C134 ) )| + |( ( Re C133 ) , ( Re C135 ) )| ) - ( ( <i> ) * ( |( ( Re C133 ) , ( Im C134 ) )| + |( ( Re C133 ) , ( Im C135 ) )| ) ) ) + ( ( <i> ) * ( |( ( Im C133 ) , ( Re C134 ) )| + |( ( Im C133 ) , ( Re C135 ) )| ) ) ) + ( |( ( Im C133 ) , ( Im C134 ) )| + |( ( Im C133 ) , ( Im C135 ) )| ) ) by L486 , L487 , L488 , L489 , RVSUM_1:120
.= ( |( C133 , C134 )| + |( C133 , C135 )| );
thus L493: thesis by L492;
end;
theorem
L494: (for B142 , B143 , B144 being (FinSequence of ( COMPLEX )) holds ((( len B142 ) = ( len B143 ) & ( len B143 ) = ( len B144 )) implies |( B142 , ( B143 - B144 ) )| = ( |( B142 , B143 )| - |( B142 , B144 )| )))
proof
let C136 , C137 , C138 being (FinSequence of ( COMPLEX ));
assume that
L495: ( len C136 ) = ( len C137 )
and
L496: ( len C137 ) = ( len C138 );
L497: (( len ( Re C137 ) ) = ( len C137 ) & ( len ( Re C138 ) ) = ( len C138 )) by L324;
L498: ( len ( Im C136 ) ) = ( len C136 ) by L324;
L499: (( len ( Im C137 ) ) = ( len C137 ) & ( len ( Im C138 ) ) = ( len C138 )) by L324;
L500: ( len ( Re C136 ) ) = ( len C136 ) by L324;
L501: |( C136 , ( C137 - C138 ) )| = ( ( ( |( ( Re C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| - ( ( <i> ) * |( ( Re C136 ) , ( Im ( C137 - C138 ) ) )| ) ) + ( ( <i> ) * |( ( Im C136 ) , ( Re ( C137 - C138 ) ) )| ) ) + |( ( Im C136 ) , ( Im ( C137 - C138 ) ) )| ) by L496 , L349
.= ( ( ( |( ( Re C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| - ( ( <i> ) * |( ( Re C136 ) , ( Im ( C137 - C138 ) ) )| ) ) + ( ( <i> ) * |( ( Im C136 ) , ( Re ( C137 - C138 ) ) )| ) ) + |( ( Im C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) by L496 , L349
.= ( ( ( |( ( Re C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| - ( ( <i> ) * |( ( Re C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) ) + ( ( <i> ) * |( ( Im C136 ) , ( Re ( C137 - C138 ) ) )| ) ) + |( ( Im C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) by L496 , L349
.= ( ( ( |( ( Re C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| - ( ( <i> ) * |( ( Re C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) ) + ( ( <i> ) * |( ( Im C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| ) ) + |( ( Im C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) by L496 , L349
.= ( ( ( ( |( ( Re C136 ) , ( Re C137 ) )| - |( ( Re C136 ) , ( Re C138 ) )| ) - ( ( <i> ) * |( ( Re C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) ) + ( ( <i> ) * |( ( Im C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| ) ) + |( ( Im C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) by L495 , L496 , L497 , L500 , RVSUM_1:124
.= ( ( ( ( |( ( Re C136 ) , ( Re C137 ) )| - |( ( Re C136 ) , ( Re C138 ) )| ) - ( ( <i> ) * |( ( Re C136 ) , ( ( Im C137 ) - ( Im C138 ) ) )| ) ) + ( ( <i> ) * |( ( Im C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| ) ) + ( |( ( Im C136 ) , ( Im C137 ) )| - |( ( Im C136 ) , ( Im C138 ) )| ) ) by L495 , L496 , L499 , L498 , RVSUM_1:124
.= ( ( ( ( |( ( Re C136 ) , ( Re C137 ) )| - |( ( Re C136 ) , ( Re C138 ) )| ) - ( ( <i> ) * ( |( ( Re C136 ) , ( Im C137 ) )| - |( ( Re C136 ) , ( Im C138 ) )| ) ) ) + ( ( <i> ) * |( ( Im C136 ) , ( ( Re C137 ) - ( Re C138 ) ) )| ) ) + ( |( ( Im C136 ) , ( Im C137 ) )| - |( ( Im C136 ) , ( Im C138 ) )| ) ) by L495 , L496 , L500 , L499 , RVSUM_1:124
.= ( ( ( ( |( ( Re C136 ) , ( Re C137 ) )| - |( ( Re C136 ) , ( Re C138 ) )| ) - ( ( <i> ) * ( |( ( Re C136 ) , ( Im C137 ) )| - |( ( Re C136 ) , ( Im C138 ) )| ) ) ) + ( ( <i> ) * ( |( ( Im C136 ) , ( Re C137 ) )| - |( ( Im C136 ) , ( Re C138 ) )| ) ) ) + ( |( ( Im C136 ) , ( Im C137 ) )| - |( ( Im C136 ) , ( Im C138 ) )| ) ) by L495 , L496 , L497 , L498 , RVSUM_1:124
.= ( |( C136 , C137 )| - |( C136 , C138 )| );
thus L502: thesis by L501;
end;
theorem
L503: (for B145 , B146 , B147 , B148 being (FinSequence of ( COMPLEX )) holds ((( len B145 ) = ( len B146 ) & ( len B146 ) = ( len B147 ) & ( len B147 ) = ( len B148 )) implies |( ( B145 + B146 ) , ( B147 + B148 ) )| = ( ( ( |( B145 , B147 )| + |( B145 , B148 )| ) + |( B146 , B147 )| ) + |( B146 , B148 )| )))
proof
let C139 , C140 , C141 , C142 being (FinSequence of ( COMPLEX ));
assume that
L504: ( len C139 ) = ( len C140 )
and
L505: ( len C140 ) = ( len C141 )
and
L506: ( len C141 ) = ( len C142 );
L507: |( ( C139 + C140 ) , C142 )| = ( |( C139 , C142 )| + |( C140 , C142 )| ) by L504 , L505 , L506 , L455;
L508: ( |( ( C139 + C140 ) , C141 )| + |( ( C139 + C140 ) , C142 )| ) = ( ( |( C139 , C141 )| + |( C140 , C141 )| ) + ( |( C139 , C142 )| + |( C140 , C142 )| ) ) by L507 , L504 , L505 , L455;
L509: ( len ( C139 + C140 ) ) = ( len C139 ) by L504 , L49;
thus L510: thesis by L509 , L504 , L505 , L506 , L508 , L485;
end;
theorem
L511: (for B149 , B150 , B151 , B152 being (FinSequence of ( COMPLEX )) holds ((( len B149 ) = ( len B150 ) & ( len B150 ) = ( len B151 ) & ( len B151 ) = ( len B152 )) implies |( ( B149 - B150 ) , ( B151 - B152 ) )| = ( ( ( |( B149 , B151 )| - |( B149 , B152 )| ) - |( B150 , B151 )| ) + |( B150 , B152 )| )))
proof
let C143 , C144 , C145 , C146 being (FinSequence of ( COMPLEX ));
assume that
L512: ( len C143 ) = ( len C144 )
and
L513: ( len C144 ) = ( len C145 )
and
L514: ( len C145 ) = ( len C146 );
L515: |( C143 , ( C145 - C146 ) )| = ( |( C143 , C145 )| - |( C143 , C146 )| ) by L512 , L513 , L514 , L494;
L516: ( |( C143 , ( C145 - C146 ) )| - |( C144 , ( C145 - C146 ) )| ) = ( ( |( C143 , C145 )| - |( C143 , C146 )| ) - ( |( C144 , C145 )| - |( C144 , C146 )| ) ) by L515 , L513 , L514 , L494;
L517: ( len ( C145 - C146 ) ) = ( len C145 ) by L514 , L55;
thus L518: thesis by L517 , L512 , L513 , L516 , L479;
end;
theorem
L519: (for B153 , B154 being (FinSequence of ( COMPLEX )) holds |( B153 , B154 )| = ( |( B154 , B153 )| *' ))
proof
let C147 , C148 being (FinSequence of ( COMPLEX ));
set D62 = |( ( Re C148 ) , ( Re C147 ) )|;
set D63 = |( ( Re C148 ) , ( Im C147 ) )|;
set D64 = |( ( Im C148 ) , ( Re C147 ) )|;
set D65 = |( ( Im C148 ) , ( Im C147 ) )|;
reconsider D66 = D62 , D67 = D63 , D68 = D64 , D69 = D65 as (Element of ( REAL ));
L520: ( Im D66 ) = ( 0 ) by COMPLEX1:def 2;
L521: ( Im D67 ) = ( 0 ) by COMPLEX1:def 2;
L522: ( Im D69 ) = ( 0 ) by COMPLEX1:def 2;
L523: ( Im D68 ) = ( 0 ) by COMPLEX1:def 2;
reconsider D70 = D62 , D71 = D63 , D72 = D64 , D73 = D65 as (Element of ( COMPLEX )) by XCMPLX_0:def 2;
L524: ( |( C148 , C147 )| *' ) = ( ( ( D70 + D73 ) + ( ( <i> ) * ( D72 - D71 ) ) ) *' )
.= ( ( ( D70 + D73 ) *' ) + ( ( ( <i> ) * ( D72 - D71 ) ) *' ) ) by COMPLEX1:32
.= ( ( ( D70 *' ) + ( D73 *' ) ) + ( ( ( <i> ) * ( D72 - D71 ) ) *' ) ) by COMPLEX1:32
.= ( ( D70 + ( D73 *' ) ) + ( ( ( <i> ) * ( D72 - D71 ) ) *' ) ) by L520 , COMPLEX1:38
.= ( ( D70 + D73 ) + ( ( ( <i> ) * ( D72 - D71 ) ) *' ) ) by L522 , COMPLEX1:38
.= ( ( D70 + D73 ) + ( ( - ( <i> ) ) * ( ( D72 - D71 ) *' ) ) ) by COMPLEX1:31 , COMPLEX1:35
.= ( ( D70 + D73 ) + ( ( - ( <i> ) ) * ( ( D72 *' ) - ( D71 *' ) ) ) ) by COMPLEX1:34
.= ( ( D70 + D73 ) + ( ( - ( <i> ) ) * ( D72 - ( D71 *' ) ) ) ) by L523 , COMPLEX1:38
.= ( ( D70 + D73 ) + ( ( - ( <i> ) ) * ( D72 - D71 ) ) ) by L521 , COMPLEX1:38
.= |( C147 , C148 )|;
thus L525: thesis by L524;
end;
theorem
L526: (for B155 , B156 being (FinSequence of ( COMPLEX )) holds (( len B155 ) = ( len B156 ) implies |( ( B155 + B156 ) , ( B155 + B156 ) )| = ( ( |( B155 , B155 )| + ( 2 * ( Re |( B155 , B156 )| ) ) ) + |( B156 , B156 )| )))
proof
let C149 , C150 being (FinSequence of ( COMPLEX ));
set D74 = |( C149 , C150 )|;
assume L527: ( len C149 ) = ( len C150 );
L528: |( ( C149 + C150 ) , ( C149 + C150 ) )| = ( ( ( |( C149 , C149 )| + |( C149 , C150 )| ) + |( C150 , C149 )| ) + |( C150 , C150 )| ) by L527 , L503
.= ( ( ( |( C149 , C149 )| + |( C149 , C150 )| ) + ( |( C149 , C150 )| *' ) ) + |( C150 , C150 )| ) by L519
.= ( ( |( C149 , C149 )| + ( D74 + ( D74 *' ) ) ) + |( C150 , C150 )| )
.= ( ( |( C149 , C149 )| + ( 2 * ( Re |( C149 , C150 )| ) ) ) + |( C150 , C150 )| ) by L167;
thus L529: thesis by L528;
end;
theorem
L530: (for B157 , B158 being (FinSequence of ( COMPLEX )) holds (( len B157 ) = ( len B158 ) implies |( ( B157 - B158 ) , ( B157 - B158 ) )| = ( ( |( B157 , B157 )| - ( 2 * ( Re |( B157 , B158 )| ) ) ) + |( B158 , B158 )| )))
proof
let C151 , C152 being (FinSequence of ( COMPLEX ));
set D75 = |( C151 , C152 )|;
assume L531: ( len C151 ) = ( len C152 );
L532: |( ( C151 - C152 ) , ( C151 - C152 ) )| = ( ( ( |( C151 , C151 )| - |( C151 , C152 )| ) - |( C152 , C151 )| ) + |( C152 , C152 )| ) by L531 , L511
.= ( ( ( |( C151 , C151 )| - |( C151 , C152 )| ) - ( |( C151 , C152 )| *' ) ) + |( C152 , C152 )| ) by L519
.= ( ( |( C151 , C151 )| - ( D75 + ( D75 *' ) ) ) + |( C152 , C152 )| )
.= ( ( |( C151 , C151 )| - ( 2 * ( Re |( C151 , C152 )| ) ) ) + |( C152 , C152 )| ) by L167;
thus L533: thesis by L532;
end;
theorem
L534: (for B159 being (Element of ( COMPLEX )) holds (for B160 , B161 being (FinSequence of ( COMPLEX )) holds (( len B160 ) = ( len B161 ) implies |( ( B159 * B160 ) , B161 )| = ( B159 * |( B160 , B161 )| ))))
proof
let C153 being (Element of ( COMPLEX ));
let C154 , C155 being (FinSequence of ( COMPLEX ));
assume L535: ( len C154 ) = ( len C155 );
L536: (( len ( ( Re C153 ) * ( Im C154 ) ) ) = ( len ( Im C154 ) ) & ( len ( ( Im C153 ) * ( Re C154 ) ) ) = ( len ( Re C154 ) )) by RVSUM_1:117;
L537: (( len ( ( Re C153 ) * ( Re C154 ) ) ) = ( len ( Re C154 ) ) & ( len ( ( Im C153 ) * ( Im C154 ) ) ) = ( len ( Im C154 ) )) by RVSUM_1:117;
L538: ( len ( Re C154 ) ) = ( len C154 ) by L324;
L539: ( len ( Im C155 ) ) = ( len C155 ) by L324;
L540: ( len ( Re C155 ) ) = ( len C155 ) by L324;
L541: ( len ( Im C154 ) ) = ( len C154 ) by L324;
L542: |( ( C153 * C154 ) , C155 )| = ( ( ( |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| - ( ( <i> ) * |( ( Re ( C153 * C154 ) ) , ( Im C155 ) )| ) ) + ( ( <i> ) * |( ( Im ( C153 * C154 ) ) , ( Re C155 ) )| ) ) + |( ( Im ( C153 * C154 ) ) , ( Im C155 ) )| ) by L427
.= ( ( ( |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| - ( ( <i> ) * |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) ) + ( ( <i> ) * |( ( Im ( C153 * C154 ) ) , ( Re C155 ) )| ) ) + |( ( Im ( C153 * C154 ) ) , ( Im C155 ) )| ) by L427
.= ( ( ( |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| - ( ( <i> ) * |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) ) + ( ( <i> ) * |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| ) ) + |( ( Im ( C153 * C154 ) ) , ( Im C155 ) )| ) by L427
.= ( ( ( |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| - ( ( <i> ) * |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) ) + ( ( <i> ) * |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| ) ) + |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) by L427
.= ( ( ( ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Re C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * |( ( ( ( Re C153 ) * ( Re C154 ) ) - ( ( Im C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) ) + ( ( <i> ) * |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| ) ) + |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) by L535 , L538 , L540 , L541 , L537 , RVSUM_1:124
.= ( ( ( ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Re C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Im C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) ) + ( ( <i> ) * |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Re C155 ) )| ) ) + |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) by L535 , L538 , L541 , L539 , L537 , RVSUM_1:124
.= ( ( ( ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Re C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Im C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) ) + ( ( <i> ) * ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Re C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + |( ( ( ( Im C153 ) * ( Re C154 ) ) + ( ( Re C153 ) * ( Im C154 ) ) ) , ( Im C155 ) )| ) by L535 , L538 , L540 , L541 , L536 , RVSUM_1:120
.= ( ( ( ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Re C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Im C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) ) + ( ( <i> ) * ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Re C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L538 , L541 , L539 , L536 , RVSUM_1:120
.= ( ( ( ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Re C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) ) + ( ( <i> ) * ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Re C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L538 , L539 , RVSUM_1:121
.= ( ( ( ( |( ( ( Re C153 ) * ( Re C154 ) ) , ( Re C155 ) )| - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Re C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L541 , L539 , RVSUM_1:121
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) - |( ( ( Im C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Re C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L538 , L540 , RVSUM_1:121
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Re C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L540 , L541 , RVSUM_1:121
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( ( ( Im C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Re C155 ) )| ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L538 , L540 , RVSUM_1:121
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( ( ( Im C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + ( ( Re C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) ) + ( |( ( ( Im C153 ) * ( Re C154 ) ) , ( Im C155 ) )| + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L540 , L541 , RVSUM_1:121
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( ( ( Im C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + ( ( Re C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) ) + ( ( ( Im C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) + |( ( ( Re C153 ) * ( Im C154 ) ) , ( Im C155 ) )| ) ) by L535 , L538 , L539 , RVSUM_1:121
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) - ( ( <i> ) * ( ( ( Re C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) ) + ( ( <i> ) * ( ( ( Im C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + ( ( Re C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) ) + ( ( ( Im C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) + ( ( Re C153 ) * |( ( Im C154 ) , ( Im C155 ) )| ) ) ) by L535 , L541 , L539 , RVSUM_1:121
.= ( ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + ( ( ( <i> ) * ( Im C153 ) ) * |( ( Re C154 ) , ( Re C155 ) )| ) ) - ( ( ( Re C153 ) * ( <i> ) ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) + ( ( Im C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) + ( ( ( Re C153 ) * ( ( <i> ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) - ( ( Im C153 ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) + ( ( ( Re C153 ) + ( ( <i> ) * ( Im C153 ) ) ) * |( ( Im C154 ) , ( Im C155 ) )| ) )
.= ( ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + ( ( ( <i> ) * ( Im C153 ) ) * |( ( Re C154 ) , ( Re C155 ) )| ) ) - ( ( ( Re C153 ) * ( <i> ) ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) + ( ( Im C153 ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) + ( ( ( Re C153 ) + ( ( <i> ) * ( Im C153 ) ) ) * ( ( <i> ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) + ( C153 * |( ( Im C154 ) , ( Im C155 ) )| ) ) by COMPLEX1:13
.= ( ( ( ( ( ( Re C153 ) * |( ( Re C154 ) , ( Re C155 ) )| ) + ( ( ( <i> ) * ( Im C153 ) ) * |( ( Re C154 ) , ( Re C155 ) )| ) ) - ( ( ( Re C153 ) + ( ( <i> ) * ( Im C153 ) ) ) * ( ( <i> ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) ) + ( C153 * ( ( <i> ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) + ( C153 * |( ( Im C154 ) , ( Im C155 ) )| ) ) by COMPLEX1:13
.= ( ( ( ( ( ( Re C153 ) + ( ( <i> ) * ( Im C153 ) ) ) * |( ( Re C154 ) , ( Re C155 ) )| ) - ( C153 * ( ( <i> ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) ) + ( C153 * ( ( <i> ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) + ( C153 * |( ( Im C154 ) , ( Im C155 ) )| ) ) by COMPLEX1:13
.= ( ( ( ( C153 * |( ( Re C154 ) , ( Re C155 ) )| ) - ( C153 * ( ( <i> ) * |( ( Re C154 ) , ( Im C155 ) )| ) ) ) + ( C153 * ( ( <i> ) * |( ( Im C154 ) , ( Re C155 ) )| ) ) ) + ( C153 * |( ( Im C154 ) , ( Im C155 ) )| ) ) by COMPLEX1:13
.= ( C153 * |( C154 , C155 )| );
thus L543: thesis by L542;
end;
theorem
L544: (for B162 being (Element of ( COMPLEX )) holds (for B163 , B164 being (FinSequence of ( COMPLEX )) holds (( len B163 ) = ( len B164 ) implies |( B163 , ( B162 * B164 ) )| = ( ( B162 *' ) * |( B163 , B164 )| ))))
proof
let C156 being (Element of ( COMPLEX ));
let C157 , C158 being (FinSequence of ( COMPLEX ));
assume L545: ( len C157 ) = ( len C158 );
L546: |( C157 , ( C156 * C158 ) )| = ( |( ( C156 * C158 ) , C157 )| *' ) by L519
.= ( ( C156 * |( C158 , C157 )| ) *' ) by L545 , L534
.= ( ( C156 *' ) * ( |( C158 , C157 )| *' ) ) by COMPLEX1:35
.= ( ( C156 *' ) * |( C157 , C158 )| ) by L519;
thus L547: thesis by L546;
end;
theorem
L548: (for B165 , B166 being (Element of ( COMPLEX )) holds (for B167 , B168 , B169 being (FinSequence of ( COMPLEX )) holds ((( len B167 ) = ( len B168 ) & ( len B168 ) = ( len B169 )) implies |( ( ( B165 * B167 ) + ( B166 * B168 ) ) , B169 )| = ( ( B165 * |( B167 , B169 )| ) + ( B166 * |( B168 , B169 )| ) ))))
proof
let C159 , C160 being (Element of ( COMPLEX ));
let C161 , C162 , C163 being (FinSequence of ( COMPLEX ));
assume that
L549: ( len C161 ) = ( len C162 )
and
L550: ( len C162 ) = ( len C163 );
L551: (( len ( C159 * C161 ) ) = ( len C161 ) & ( len ( C160 * C162 ) ) = ( len C162 )) by L39;
L552: |( ( ( C159 * C161 ) + ( C160 * C162 ) ) , C163 )| = ( |( ( C159 * C161 ) , C163 )| + |( ( C160 * C162 ) , C163 )| ) by L551 , L549 , L550 , L455
.= ( ( C159 * |( C161 , C163 )| ) + |( ( C160 * C162 ) , C163 )| ) by L549 , L550 , L534
.= ( ( C159 * |( C161 , C163 )| ) + ( C160 * |( C162 , C163 )| ) ) by L550 , L534;
thus L553: thesis by L552;
end;
theorem
L554: (for B170 , B171 being (Element of ( COMPLEX )) holds (for B172 , B173 , B174 being (FinSequence of ( COMPLEX )) holds ((( len B172 ) = ( len B173 ) & ( len B173 ) = ( len B174 )) implies |( B172 , ( ( B170 * B173 ) + ( B171 * B174 ) ) )| = ( ( ( B170 *' ) * |( B172 , B173 )| ) + ( ( B171 *' ) * |( B172 , B174 )| ) ))))
proof
let C164 , C165 being (Element of ( COMPLEX ));
let C166 , C167 , C168 being (FinSequence of ( COMPLEX ));
assume that
L555: ( len C166 ) = ( len C167 )
and
L556: ( len C167 ) = ( len C168 );
L557: (( len ( C164 * C167 ) ) = ( len C167 ) & ( len ( C165 * C168 ) ) = ( len C168 )) by L39;
L558: |( C166 , ( ( C164 * C167 ) + ( C165 * C168 ) ) )| = ( |( C166 , ( C164 * C167 ) )| + |( C166 , ( C165 * C168 ) )| ) by L557 , L555 , L556 , L485
.= ( ( ( C164 *' ) * |( C166 , C167 )| ) + |( C166 , ( C165 * C168 ) )| ) by L555 , L544
.= ( ( ( C164 *' ) * |( C166 , C167 )| ) + ( ( C165 *' ) * |( C166 , C168 )| ) ) by L555 , L556 , L544;
thus L559: thesis by L558;
end;
