:: Two Programs for {\bf SCM}. Part II - Proofs
::  by Grzegorz Bancerek and Piotr Rudnicki
::
:: Received October 8, 1993
:: Copyright (c) 1993-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, CARD_1, INT_1, POWER, SUBSET_1, XXREAL_0, RELAT_1,
      ARYTM_3, ARYTM_1, NAT_1, AMI_3, AFINSQ_1, AMI_1, ORDINAL4, GRAPHSP,
      SCM_1, FINSEQ_1, MSUALG_1, FUNCT_1, PRE_FF, FSM_1, NEWTON, FIB_FUSC,
      EXTPRO_1, PARTFUN1, TARSKI;
 notations ENUMSET1, XCMPLX_0, SUBSET_1, NUMBERS, INT_1, ORDINAL1, NAT_1,
      NEWTON, POWER, RELAT_1, FUNCT_1, PARTFUN1, AFINSQ_1, FINSEQ_1, MEMSTR_0,
      COMPOS_1, EXTPRO_1, SCM_1, AMI_3, PRE_FF, XXREAL_0;
 constructors REAL_1, NEWTON, POWER, PRE_FF, SCM_1, ENUMSET1, PRE_POLY;
 registrations XREAL_0, INT_1, AMI_3, ORDINAL1, AFINSQ_1, SCM_1, PBOOLE,
      COMPOS_0;
 requirements REAL, NUMERALS, SUBSET, ARITHM, BOOLE;
 theorems NAT_1, INT_1, POWER, NEWTON, SCM_1, PRE_FF, AMI_3, XREAL_1, XXREAL_0,
      ORDINAL1, EXTPRO_1, AFINSQ_1, GRFUNC_1, CARD_1, ENUMSET1, MEMSTR_0;
 schemes NAT_1;

begin
L1: ( 0 ) = [\ ( log (2 , 1) ) /]
proof
thus L2: ( 0 ) = [\ ( 0 ) /] by INT_1:25
.= [\ ( log (2 , 1) ) /] by POWER:51;
end;
L3: (for B1 being (Element of ( NAT )) holds (B1 > ( 0 ) implies ([\ ( log (2 , B1) ) /] is (Element of ( NAT )) & ( ( 6 * ( [\ ( log (2 , B1) ) /] + 1 ) ) + 1 ) > ( 0 ))))
proof
let C1 being (Element of ( NAT ));
assume L4: C1 > ( 0 );
L5: C1 >= ( ( 0 ) + 1 ) by L4 , NAT_1:13;
L6: ( log (2 , 1) ) = ( 0 ) by POWER:51;
L7: ( log (2 , C1) ) >= ( 0 ) by L6 , L5 , PRE_FF:10;
L8: [\ ( log (2 , C1) ) /] >= [\ ( 0 ) /] by L7 , PRE_FF:9;
L9: [\ ( log (2 , C1) ) /] >= ( 0 ) by L8 , INT_1:25;
reconsider D1 = [\ ( log (2 , C1) ) /] as (Element of ( NAT )) by L9 , INT_1:3;
L10: D1 is (Element of ( NAT ));
thus L11: [\ ( log (2 , C1) ) /] is (Element of ( NAT )) by L10;
L12: ( ( 6 * D1 ) + ( 6 * 1 ) ) >= ( 0 ) by NAT_1:12;
thus L13: thesis by L12 , NAT_1:13;
end;
L14: (for B2 , B3 being (Element of ( NAT )) holds ((B2 = ( ( 2 * B3 ) + 1 ) & B3 > ( 0 )) implies ( 6 + ( ( 6 * ( [\ ( log (2 , B3) ) /] + 1 ) ) + 1 ) ) = ( ( 6 * ( [\ ( log (2 , B2) ) /] + 1 ) ) + 1 )))
proof
let C2 , C3 being (Element of ( NAT ));
assume that
L15: (C2 = ( ( 2 * C3 ) + 1 ) & C3 > ( 0 ));
set D2 = [\ ( log (2 , C3) ) /];
thus L16: ( 6 + ( ( 6 * ( D2 + 1 ) ) + 1 ) ) = ( ( 6 * ( 1 + ( D2 + 1 ) ) ) + 1 )
.= ( ( 6 * ( [\ ( log (2 , C2) ) /] + 1 ) ) + 1 ) by L15 , PRE_FF:14;
end;
L17: (for B4 being (Element of ( NAT )) holds (B4 > ( 0 ) implies (( log (2 , ( 2 * B4 )) ) = ( 1 + ( log (2 , B4) ) ) & ( log (2 , ( 2 * B4 )) ) = ( ( log (2 , B4) ) + 1 ))))
proof
let C4 being (Element of ( NAT ));
assume L18: C4 > ( 0 );
thus L19: ( log (2 , ( 2 * C4 )) ) = ( ( log (2 , 2) ) + ( log (2 , C4) ) ) by L18 , POWER:53
.= ( 1 + ( log (2 , C4) ) ) by POWER:52;
thus L20: thesis by L19;
end;
L21: (for B5 , B6 being (Element of ( NAT )) holds ((B5 = ( 2 * B6 ) & B6 > ( 0 )) implies ( 6 + ( ( 6 * ( [\ ( log (2 , B6) ) /] + 1 ) ) + 1 ) ) = ( ( 6 * ( [\ ( log (2 , B5) ) /] + 1 ) ) + 1 )))
proof
let C5 , C6 being (Element of ( NAT ));
assume that
L22: (C5 = ( 2 * C6 ) & C6 > ( 0 ));
set D3 = [\ ( log (2 , C6) ) /];
thus L23: ( 6 + ( ( 6 * ( D3 + 1 ) ) + 1 ) ) = ( ( 6 * ( 1 + ( D3 + 1 ) ) ) + 1 )
.= ( ( 6 * ( 1 + [\ ( ( log (2 , C6) ) + 1 ) /] ) ) + 1 ) by INT_1:28
.= ( ( 6 * ( [\ ( log (2 , C5) ) /] + 1 ) ) + 1 ) by L22 , L17;
end;
L24: (for B7 being (Element of ( NAT )) holds (B7 <> ( 0 ) implies ( ( 6 * B7 ) - 4 ) > ( 0 )))
proof
let C7 being (Element of ( NAT ));
assume L25: C7 <> ( 0 );
consider C8 being Nat such that L26: C7 = ( C8 + 1 ) by L25 , NAT_1:6;
reconsider D4 = C8 as (Element of ( NAT )) by ORDINAL1:def 12;
L27: ( ( 6 * D4 ) + 2 ) <> ( 0 ) by NAT_1:7;
thus L28: thesis by L27 , L26 , NAT_1:3;
end;
L29: ( dl. ( 0 ) ) <> ( dl. 1 ) by AMI_3:10;
L30: ( dl. ( 0 ) ) <> ( dl. 2 ) by AMI_3:10;
L31: ( dl. ( 0 ) ) <> ( dl. 3 ) by AMI_3:10;
L32: ( dl. 1 ) <> ( dl. 2 ) by AMI_3:10;
L33: ( dl. 1 ) <> ( dl. 3 ) by AMI_3:10;
L34: ( dl. 2 ) <> ( dl. 3 ) by AMI_3:10;
L35: ( dl. ( 0 ) ) <> ( dl. 4 ) by AMI_3:10;
L36: ( dl. 1 ) <> ( dl. 4 ) by AMI_3:10;
L37: ( dl. 2 ) <> ( dl. 4 ) by AMI_3:10;
L38: ( dl. 3 ) <> ( dl. 4 ) by AMI_3:10;
definition
func Fib_Program -> (XFinSequence of (the InstructionsF of ( SCM ))) equals 
( ( ( ( ( ( ( ( <% ( ( dl. 1 ) >0_goto 2 ) %> ^ <% ( halt ( SCM ) ) %> ) ^ <% ( ( dl. 3 ) := ( dl. ( 0 ) ) ) %> ) ^ <% ( SubFrom (( dl. 1 ) , ( dl. ( 0 ) )) ) %> ) ^ <% ( ( dl. 1 ) =0_goto 1 ) %> ) ^ <% ( ( dl. 4 ) := ( dl. 2 ) ) %> ) ^ <% ( ( dl. 2 ) := ( dl. 3 ) ) %> ) ^ <% ( AddTo (( dl. 3 ) , ( dl. 4 )) ) %> ) ^ <% ( SCM-goto 3 ) %> );
coherence;
end;
L40: (for R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function holds (for B8 , B9 , B10 , B11 , B12 , B13 , B14 , B15 , B16 being (Instruction of ( SCM )) holds (( ( ( ( ( ( ( ( <% B8 %> ^ <% B9 %> ) ^ <% B10 %> ) ^ <% B11 %> ) ^ <% B12 %> ) ^ <% B13 %> ) ^ <% B14 %> ) ^ <% B15 %> ) ^ <% B16 %> ) c= R1 implies (( R1 . ( 0 ) ) = B8 & ( R1 . 1 ) = B9 & ( R1 . 2 ) = B10 & ( R1 . 3 ) = B11 & ( R1 . 4 ) = B12 & ( R1 . 5 ) = B13 & ( R1 . 6 ) = B14 & ( R1 . 7 ) = B15 & ( R1 . 8 ) = B16))))
proof
let R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function;
let C9 , C10 , C11 , C12 , C13 , C14 , C15 , C16 , C17 being (Instruction of ( SCM ));
assume that
L41: ( ( ( ( ( ( ( ( <% C9 %> ^ <% C10 %> ) ^ <% C11 %> ) ^ <% C12 %> ) ^ <% C13 %> ) ^ <% C14 %> ) ^ <% C15 %> ) ^ <% C16 %> ) ^ <% C17 %> ) c= R1;
set D5 = ( ( ( ( ( ( ( ( <% C9 %> ^ <% C10 %> ) ^ <% C11 %> ) ^ <% C12 %> ) ^ <% C13 %> ) ^ <% C14 %> ) ^ <% C15 %> ) ^ <% C16 %> ) ^ <% C17 %> );
L42: (( D5 . 2 ) = C11 & ( D5 . 3 ) = C12) by AFINSQ_1:50;
L43: (( D5 . 6 ) = C15 & ( D5 . 7 ) = C16) by AFINSQ_1:50;
L44: (( D5 . 4 ) = C13 & ( D5 . 5 ) = C14) by AFINSQ_1:50;
L45: (( D5 . 8 ) = C17 & ( len D5 ) = 9) by AFINSQ_1:50;
L46: ( len D5 ) = 9 by AFINSQ_1:50;
L47: (( 0 ) in ( dom D5 ) & 1 in ( dom D5 ) & 2 in ( dom D5 ) & 3 in ( dom D5 ) & 4 in ( dom D5 ) & 5 in ( dom D5 ) & 6 in ( dom D5 ) & 7 in ( dom D5 ) & 8 in ( dom D5 )) by L46 , ENUMSET1:def 7 , CARD_1:57;
L48: (( D5 . ( 0 ) ) = C9 & ( D5 . 1 ) = C10) by AFINSQ_1:50;
thus L49: (( R1 . ( 0 ) ) = C9 & ( R1 . 1 ) = C10 & ( R1 . 2 ) = C11 & ( R1 . 3 ) = C12 & ( R1 . 4 ) = C13 & ( R1 . 5 ) = C14 & ( R1 . 6 ) = C15 & ( R1 . 7 ) = C16 & ( R1 . 8 ) = C17) by L48 , L42 , L44 , L43 , L45 , L47 , L41 , GRFUNC_1:2;
end;
theorem
L50: (for R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function holds (( Fib_Program ) c= R1 implies (for B17 being (Element of ( NAT )) holds (for B18 being ( 0 ) -started (State-consisting of <% 1 , B17 , ( 0 ) , ( 0 ) %>) holds (R1 halts_on B18 & (B17 = ( 0 ) implies ( LifeSpan (R1 , B18) ) = 1) & (B17 > ( 0 ) implies ( LifeSpan (R1 , B18) ) = ( ( 6 * B17 ) - 2 )) & ( ( Result (R1 , B18) ) . ( dl. 3 ) ) = ( Fib B17 ))))))
proof
let R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function;
assume L51: ( Fib_Program ) c= R1;
let C18 being (Element of ( NAT ));
let C19 being ( 0 ) -started (State-consisting of <% 1 , C18 , ( 0 ) , ( 0 ) %>);
set D6 = ( dl. ( 0 ) );
set D7 = ( dl. 1 );
set D8 = ( dl. 2 );
set D9 = ( dl. 3 );
set D10 = ( dl. 4 );
set D11 = 6;
set D12 = 7;
set D13 = 8;
set D14 = ( 0 );
set D15 = 1;
set D16 = 2;
set D17 = 3;
set D18 = 4;
set D19 = 5;
L52: (( IC C19 ) = D14 & ( R1 . D14 ) = ( D7 >0_goto D16 )) by L51 , L40 , MEMSTR_0:def 12;
set D20 = ( Comput (R1 , C19 , ( ( 0 ) + 1 )) );
set D21 = ( Comput (R1 , C19 , ( 0 )) );
L53: C19 = D21 by EXTPRO_1:2;
L54: ( C19 . D6 ) = 1 by SCM_1:1;
L55: ( D20 . D6 ) = 1 by L54 , L52 , L53 , SCM_1:11;
L56: ( R1 . D17 ) = ( SubFrom (D7 , D6) ) by L51 , L40;
L57: ( C19 . D8 ) = ( 0 ) by SCM_1:1;
L58: ( D20 . D8 ) = ( 0 ) by L57 , L52 , L53 , SCM_1:11;
L59: ( R1 . D18 ) = ( D7 =0_goto D15 ) by L51 , L40;
L60: ( C19 . D9 ) = ( 0 ) by SCM_1:1;
L61: ( D20 . D9 ) = ( 0 ) by L60 , L52 , L53 , SCM_1:11;
L62: ( R1 . D11 ) = ( D8 := D9 ) by L51 , L40;
defpred S1[ (Element of ( NAT )) ] means ($1 < C18 implies (for B19 being (State of ( SCM )) holds (B19 = ( Comput (R1 , C19 , ( ( 6 * $1 ) + 3 )) ) implies (( B19 . D6 ) = 1 & ( B19 . D7 ) = ( ( C18 - 1 ) - $1 ) & ( B19 . D8 ) = ( Fib $1 ) & ( B19 . D9 ) = ( Fib ( $1 + 1 ) ) & ( IC B19 ) = D18))));
L63: ( R1 . D16 ) = ( D9 := D6 ) by L51 , L40;
L64: ( R1 . D12 ) = ( AddTo (D9 , D10) ) by L51 , L40;
L65: ( R1 . D13 ) = ( SCM-goto D17 ) by L51 , L40;
L66: ( R1 . D19 ) = ( D10 := D8 ) by L51 , L40;
L67: (for B20 being (Element of ( NAT )) holds (S1[ B20 ] implies S1[ ( B20 + 1 ) ]))
proof
let C20 being (Element of ( NAT ));
assume that
L68: (C20 < C18 implies (for B21 being (State of ( SCM )) holds (B21 = ( Comput (R1 , C19 , ( ( 6 * C20 ) + 3 )) ) implies (( B21 . D6 ) = 1 & ( B21 . D7 ) = ( ( C18 - 1 ) - C20 ) & ( B21 . D8 ) = ( Fib C20 ) & ( B21 . D9 ) = ( Fib ( C20 + 1 ) ) & ( IC B21 ) = D18))))
and
L69: ( C20 + 1 ) < C18;
set D22 = ( ( 6 * C20 ) + 3 );
set D23 = ( Comput (R1 , C19 , ( D22 + 1 )) );
set D24 = ( Comput (R1 , C19 , ( ( D22 + 1 ) + 1 )) );
set D25 = ( Comput (R1 , C19 , ( ( ( D22 + 1 ) + 1 ) + 1 )) );
set D26 = ( Comput (R1 , C19 , ( ( ( ( D22 + 1 ) + 1 ) + 1 ) + 1 )) );
set D27 = ( Comput (R1 , C19 , ( ( ( ( ( D22 + 1 ) + 1 ) + 1 ) + 1 ) + 1 )) );
set D28 = ( Comput (R1 , C19 , ( ( ( ( ( ( D22 + 1 ) + 1 ) + 1 ) + 1 ) + 1 ) + 1 )) );
set D29 = ( Comput (R1 , C19 , ( ( 6 * C20 ) + 3 )) );
L70: ( IC D29 ) = D18 by L68 , L69 , NAT_1:13;
let C21 being (State of ( SCM ));
assume L71: C21 = ( Comput (R1 , C19 , ( ( 6 * ( C20 + 1 ) ) + 3 )) );
L72: ( D29 . D7 ) = ( ( C18 - 1 ) - C20 ) by L68 , L69 , NAT_1:13;
L73: ( D29 . D7 ) <> ( 0 ) by L72 , L69;
L74: ( IC D23 ) = ( 4 + 1 ) by L73 , L59 , L70 , SCM_1:10;
L75: ( IC D24 ) = ( 5 + 1 ) by L74 , L66 , SCM_1:4;
L76: ( IC D25 ) = ( 6 + 1 ) by L75 , L62 , SCM_1:4;
L77: ( IC D26 ) = ( 7 + 1 ) by L76 , L64 , SCM_1:5;
L78: ( IC D27 ) = D17 by L77 , L65 , SCM_1:9;
L79: ( IC D28 ) = ( 3 + 1 ) by L78 , L56 , SCM_1:6;
L80: ( D29 . D6 ) = 1 by L68 , L69 , NAT_1:13;
L81: ( D23 . D6 ) = 1 by L80 , L59 , L70 , SCM_1:10;
L82: ( D24 . D6 ) = 1 by L81 , L66 , L74 , L35 , SCM_1:4;
L83: ( D25 . D6 ) = 1 by L82 , L62 , L75 , L30 , SCM_1:4;
L84: ( D26 . D6 ) = 1 by L83 , L64 , L76 , L31 , SCM_1:5;
L85: ( D27 . D6 ) = 1 by L84 , L65 , L77 , SCM_1:9;
L86: ( D29 . D9 ) = ( Fib ( C20 + 1 ) ) by L68 , L69 , NAT_1:13;
L87: ( D23 . D9 ) = ( Fib ( C20 + 1 ) ) by L86 , L59 , L70 , SCM_1:10;
L88: ( D24 . D9 ) = ( Fib ( C20 + 1 ) ) by L87 , L66 , L74 , L38 , SCM_1:4;
L89: ( D25 . D9 ) = ( Fib ( C20 + 1 ) ) by L88 , L62 , L75 , L34 , SCM_1:4;
L90: ( D29 . D8 ) = ( Fib C20 ) by L68 , L69 , NAT_1:13;
L91: ( D23 . D8 ) = ( Fib C20 ) by L90 , L59 , L70 , SCM_1:10;
L92: ( D24 . D10 ) = ( Fib C20 ) by L91 , L66 , L74 , SCM_1:4;
L93: ( D25 . D10 ) = ( Fib C20 ) by L92 , L62 , L75 , L37 , SCM_1:4;
L94: ( D26 . D9 ) = ( ( D25 . D10 ) + ( D25 . D9 ) ) by L64 , L76 , SCM_1:5
.= ( Fib ( ( C20 + 1 ) + 1 ) ) by L89 , L93 , PRE_FF:1;
L95: ( D27 . D9 ) = ( Fib ( ( C20 + 1 ) + 1 ) ) by L94 , L65 , L77 , SCM_1:9;
L96: ( D25 . D8 ) = ( Fib ( C20 + 1 ) ) by L62 , L75 , L88 , SCM_1:4;
L97: ( D26 . D8 ) = ( Fib ( C20 + 1 ) ) by L96 , L64 , L76 , L34 , SCM_1:5;
L98: ( D27 . D8 ) = ( Fib ( C20 + 1 ) ) by L97 , L65 , L77 , SCM_1:9;
L99: ( D23 . D7 ) = ( ( C18 - 1 ) - C20 ) by L59 , L72 , L70 , SCM_1:10;
L100: ( D24 . D7 ) = ( ( C18 - 1 ) - C20 ) by L99 , L66 , L74 , L36 , SCM_1:4;
L101: ( D25 . D7 ) = ( ( C18 - 1 ) - C20 ) by L100 , L62 , L75 , L32 , SCM_1:4;
L102: ( D26 . D7 ) = ( ( C18 - 1 ) - C20 ) by L101 , L64 , L76 , L33 , SCM_1:5;
L103: ( D27 . D7 ) = ( ( C18 - 1 ) - C20 ) by L102 , L65 , L77 , SCM_1:9;
L104: ( D28 . D7 ) = ( ( ( C18 - 1 ) - C20 ) - 1 ) by L103 , L56 , L78 , L85 , SCM_1:6;
thus L105: thesis by L104 , L56 , L71 , L78 , L85 , L98 , L95 , L79 , L29 , L32 , L33 , SCM_1:6;
end;
L106: ( R1 . D15 ) = ( halt ( SCM ) ) by L51 , L40;
L107: ( C19 . D7 ) = C18 by SCM_1:1;
L108: ( D20 . D7 ) = C18 by L107 , L52 , L53 , SCM_1:11;
L109: S1[ ( 0 ) ]
proof
set D30 = ( Comput (R1 , C19 , ( 2 + 1 )) );
set D31 = ( Comput (R1 , C19 , ( 1 + 1 )) );
assume L110: ( 0 ) < C18;
L111: ( IC D20 ) = D16 by L110 , L52 , L107 , L53 , SCM_1:11;
L112: (( D31 . D9 ) = 1 & ( D31 . D6 ) = 1) by L111 , L63 , L55 , L61 , SCM_1:4;
let C22 being (State of ( SCM ));
assume L113: C22 = ( Comput (R1 , C19 , ( ( 6 * ( 0 ) ) + 3 )) );
L114: (( D31 . D7 ) = C18 & ( D31 . D8 ) = ( 0 )) by L63 , L108 , L58 , L111 , L33 , L34 , SCM_1:4;
L115: ( IC D31 ) = ( 2 + 1 ) by L63 , L111 , SCM_1:4;
L116: ( IC D30 ) = ( 3 + 1 ) by L115 , L56 , SCM_1:6;
thus L117: thesis by L116 , L56 , L113 , L112 , L114 , L115 , L29 , L32 , L33 , PRE_FF:1 , SCM_1:6;
end;
L118: (for B22 being (Element of ( NAT )) holds S1[ B22 ]) from NAT_1:sch 1(L109 , L67);
per cases  by NAT_1:6;
suppose L119: C18 = ( 0 );

L120: ( R1 . ( IC D20 ) ) = ( halt ( SCM ) ) by L119 , L52 , L106 , L107 , L53 , SCM_1:11;
thus L121: R1 halts_on C19 by L120 , EXTPRO_1:30;
thus L122:now
assume L123: C18 = ( 0 );
L124: ( halt ( SCM ) ) <> ( D7 >0_goto D16 ) by SCM_1:12;
thus L125: ( LifeSpan (R1 , C19) ) = 1 by L124 , L52 , L53 , L120 , EXTPRO_1:33;
end;
thus L126: (C18 > ( 0 ) implies ( LifeSpan (R1 , C19) ) = ( ( 6 * C18 ) - 2 )) by L119;
thus L127: thesis by L61 , L119 , L120 , EXTPRO_1:31 , PRE_FF:1;
end;
suppose L128: (ex B23 being Nat st C18 = ( B23 + 1 ));

consider C23 being Nat such that L129: C18 = ( C23 + 1 ) by L128;
reconsider D32 = C23 as (Element of ( NAT )) by ORDINAL1:def 12;
set D33 = ( Comput (R1 , C19 , ( ( 6 * D32 ) + 3 )) );
L130: D32 < C18 by L129 , NAT_1:13;
L131: ( IC D33 ) = D18 by L130 , L118;
L132: ( D33 . D9 ) = ( Fib ( D32 + 1 ) ) by L118 , L130;
set D34 = ( Comput (R1 , C19 , ( ( ( 6 * D32 ) + 3 ) + 1 )) );
L133: ( D33 . D7 ) = ( ( D32 + ( 1 - 1 ) ) - D32 ) by L118 , L129 , L130
.= ( 0 );
L134: ( IC D34 ) = D15 by L133 , L59 , L131 , SCM_1:10;
thus L135: R1 halts_on C19 by L134 , L106 , EXTPRO_1:30;
thus L136: (C18 = ( 0 ) implies ( LifeSpan (R1 , C19) ) = 1) by L129 , NAT_1:5;
thus L137: (C18 > ( 0 ) implies ( LifeSpan (R1 , C19) ) = ( ( 6 * C18 ) - 2 )) by L106 , L129 , L131 , L134 , EXTPRO_1:33;
thus L138: ( ( Result (R1 , C19) ) . D9 ) = ( D34 . D9 ) by L106 , L134 , EXTPRO_1:31
.= ( Fib C18 ) by L59 , L129 , L132 , L131 , SCM_1:10;
end;
end;
definition
let C24 being Integer;
func Fusc' C24 -> (Element of ( NAT )) means 
:L140: ((ex B24 being (Element of ( NAT )) st (C24 = B24 & it = ( Fusc B24 ))) or ((not C24 is (Element of ( NAT ))) & it = ( 0 )));
existence
proof
per cases ;
suppose L141: C24 is (Element of ( NAT ));

reconsider D35 = C24 as (Element of ( NAT )) by L141;
take ( Fusc D35 );
thus L142: thesis;
end;
suppose L143: (not C24 is (Element of ( NAT )));

thus L144: thesis by L143;
end;
end;
uniqueness;
end;
definition
func Fusc_Program -> (XFinSequence of (the InstructionsF of ( SCM ))) equals 
( ( ( ( ( ( ( ( <% ( ( dl. 1 ) =0_goto 8 ) %> ^ <% ( ( dl. 4 ) := ( dl. ( 0 ) ) ) %> ) ^ <% ( Divide (( dl. 1 ) , ( dl. 4 )) ) %> ) ^ <% ( ( dl. 4 ) =0_goto 6 ) %> ) ^ <% ( AddTo (( dl. 3 ) , ( dl. 2 )) ) %> ) ^ <% ( SCM-goto ( 0 ) ) %> ) ^ <% ( AddTo (( dl. 2 ) , ( dl. 3 )) ) %> ) ^ <% ( SCM-goto ( 0 ) ) %> ) ^ <% ( halt ( SCM ) ) %> );
coherence;
end;
theorem
L148: (for R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function holds (( Fusc_Program ) c= R1 implies (for B25 being (Element of ( NAT )) holds (B25 > ( 0 ) implies (for B26 being ( 0 ) -started (State-consisting of <% 2 , B25 , 1 , ( 0 ) %>) holds (R1 halts_on B26 & ( ( Result (R1 , B26) ) . ( dl. 3 ) ) = ( Fusc B25 ) & ( LifeSpan (R1 , B26) ) = ( ( 6 * ( [\ ( log (2 , B25) ) /] + 1 ) ) + 1 )))))))
proof
let R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function;
set D36 = ( dl. ( 0 ) );
set D37 = ( dl. 1 );
set D38 = ( dl. 2 );
set D39 = ( dl. 3 );
set D40 = ( dl. 4 );
set D41 = 6;
set D42 = 7;
set D43 = 8;
set D44 = ( 0 );
set D45 = 1;
set D46 = 2;
set D47 = 3;
set D48 = 4;
set D49 = 5;
assume L149: ( Fusc_Program ) c= R1;
let C25 being (Element of ( NAT ));
assume that
L150: C25 > ( 0 );
set D50 = [\ ( log (2 , C25) ) /];
L151: ( ( log (2 , C25) ) - 1 ) < D50 by INT_1:def 6;
L152: ( log (2 , C25) ) < ( D50 + 1 ) by L151 , XREAL_1:19;
L153: C25 >= ( ( 0 ) + 1 ) by L150 , NAT_1:13;
L154: ( log (2 , C25) ) >= ( log (2 , 1) ) by L153 , PRE_FF:10;
L155: ( log (2 , C25) ) >= ( 0 ) by L154 , POWER:51;
L156: ( D50 + 1 ) > ( 0 ) by L155 , L152 , XXREAL_0:2;
reconsider D51 = D50 as (Element of ( NAT )) by L156 , INT_1:3 , INT_1:7;
L157: ( 2 to_power ( D51 + 1 ) ) > ( 2 to_power ( log (2 , C25) ) ) by L152 , POWER:39;
L158: ( 2 to_power ( D51 + 1 ) ) > C25 by L157 , L150 , POWER:def 3;
L159: ( 2 |^ ( D51 + 1 ) ) > C25 by L158 , POWER:41;
let C26 being ( 0 ) -started (State-consisting of <% 2 , C25 , 1 , ( 0 ) %>);
consider C27 being (State of ( SCM )) such that L160: C27 = C26;
defpred S2[ (Element of ( NAT )) ] means ($1 <= ( ( log (2 , C25) ) + 1 ) implies (for B27 being (State of ( SCM )) holds (B27 = ( Comput (R1 , C27 , ( 6 * $1 )) ) implies (( IC B27 ) = D44 & ( B27 . D36 ) = 2 & ( B27 . D37 ) = ( (C25 qua Integer) div ( 2 |^ $1 ) ) & ( B27 . D37 ) is (Element of ( NAT )) & ( Fusc C25 ) = ( ( ( B27 . D38 ) * ( Fusc' ( B27 . D37 ) ) ) + ( ( B27 . D39 ) * ( Fusc' ( ( B27 . D37 ) + 1 ) ) ) )))));
L161: ( R1 . D44 ) = ( D37 =0_goto D43 ) by L149 , L40;
L162: ( R1 . D42 ) = ( SCM-goto D44 ) by L149 , L40;
L163: ( R1 . D45 ) = ( D40 := D36 ) by L149 , L40;
L164: ( R1 . D48 ) = ( AddTo (D39 , D38) ) by L149 , L40;
L165: ( R1 . D46 ) = ( Divide (D37 , D40) ) by L149 , L40;
L166: ( R1 . D41 ) = ( AddTo (D38 , D39) ) by L149 , L40;
L167: ( R1 . D47 ) = ( D40 =0_goto D41 ) by L149 , L40;
L168: ( R1 . D49 ) = ( SCM-goto D44 ) by L149 , L40;
L169: (for B28 being (Element of ( NAT )) holds (S2[ B28 ] implies S2[ ( B28 + 1 ) ]))
proof
let C28 being (Element of ( NAT ));
assume L170: (C28 <= ( ( log (2 , C25) ) + 1 ) implies (for B29 being (State of ( SCM )) holds (B29 = ( Comput (R1 , C27 , ( 6 * C28 )) ) implies (( IC B29 ) = D44 & ( B29 . D36 ) = 2 & ( B29 . D37 ) = ( (C25 qua Integer) div ( 2 |^ C28 ) ) & ( B29 . D37 ) is (Element of ( NAT )) & ( Fusc C25 ) = ( ( ( B29 . D38 ) * ( Fusc' ( B29 . D37 ) ) ) + ( ( B29 . D39 ) * ( Fusc' ( ( B29 . D37 ) + 1 ) ) ) )))));
set D52 = ( 6 * C28 );
set D53 = ( Comput (R1 , C27 , D52) );
assume L171: ( C28 + 1 ) <= ( ( log (2 , C25) ) + 1 );
L172: C28 <= ( log (2 , C25) ) by L171 , XREAL_1:6;
L173: ( 2 to_power C28 ) <= ( 2 to_power ( log (2 , C25) ) ) by L172 , PRE_FF:8;
L174: ( 2 to_power C28 ) <= C25 by L173 , L150 , POWER:def 3;
L175: ( 2 |^ C28 ) <= C25 by L174 , POWER:41;
L176: C28 <= ( C28 + 1 ) by NAT_1:11;
L177: ( D53 . D37 ) is (Element of ( NAT )) by L176 , L170 , L171 , XXREAL_0:2;
L178: ( D53 . D37 ) = ( (C25 qua Integer) div ( 2 |^ C28 ) ) by L170 , L171 , L176 , XXREAL_0:2;
L179: ( IC D53 ) = D44 by L170 , L171 , L176 , XXREAL_0:2;
set D54 = ( Comput (R1 , C27 , ( D52 + 3 )) );
set D55 = ( Comput (R1 , C27 , ( D52 + 2 )) );
set D56 = ( Comput (R1 , C27 , ( D52 + 1 )) );
L180: ( ( D52 + 1 ) + 1 ) = ( D52 + 2 );
L181: ( 2 |^ C28 ) > ( 0 ) by NEWTON:83;
L182: ( D53 . D37 ) <> ( 0 ) by L181 , L178 , L175 , PRE_FF:3;
L183: ( IC D56 ) = ( ( 0 ) + 1 ) by L182 , L161 , L179 , SCM_1:10;
L184: ( IC D55 ) = ( 1 + 1 ) by L183 , L163 , L180 , SCM_1:4;
L185: ( ( D52 + 2 ) + 1 ) = ( D52 + 3 );
L186: ( IC D54 ) = ( 2 + 1 ) by L185 , L165 , L184 , L36 , SCM_1:8;
L187: ( D56 . D37 ) = ( D53 . D37 ) by L161 , L179 , SCM_1:10;
L188: ( D55 . D37 ) = ( D53 . D37 ) by L187 , L163 , L183 , L180 , L36 , SCM_1:4;
L189: ( ( D53 . D37 ) mod 2 ) = ( ( D53 . D37 ) - ( ( ( D53 . D37 ) div 2 ) * 2 ) ) by INT_1:def 10;
let C29 being (State of ( SCM ));
assume L190: C29 = ( Comput (R1 , C27 , ( 6 * ( C28 + 1 ) )) );
L191: ( D53 . D36 ) = 2 by L170 , L171 , L176 , XXREAL_0:2;
L192: ( D56 . D36 ) = 2 by L191 , L161 , L179 , SCM_1:10;
L193: ( D55 . D36 ) = 2 by L192 , L163 , L183 , L180 , L35 , SCM_1:4;
L194: ( D54 . D36 ) = 2 by L193 , L165 , L184 , L185 , L29 , L35 , L36 , SCM_1:8;
L195: ( D55 . D40 ) = 2 by L163 , L183 , L192 , L180 , SCM_1:4;
L196: ( D54 . D37 ) = ( ( D53 . D37 ) div 2 ) by L195 , L165 , L184 , L188 , L185 , L36 , SCM_1:8;
L197: ( D54 . D37 ) = ( (C25 qua Integer) div ( ( 2 |^ C28 ) * 2 ) ) by L196 , L178 , PRE_FF:5
.= ( (C25 qua Integer) div ( 2 |^ ( C28 + 1 ) ) ) by NEWTON:6;
L198: ( D54 . D40 ) = ( ( D53 . D37 ) mod 2 ) by L165 , L184 , L195 , L188 , L185 , L36 , SCM_1:8;
set D57 = ( Comput (R1 , C27 , ( D52 + 6 )) );
set D58 = ( Comput (R1 , C27 , ( D52 + 5 )) );
set D59 = ( Comput (R1 , C27 , ( D52 + 4 )) );
L199: ( ( D52 + 3 ) + 1 ) = ( D52 + 4 );
L200: ( D56 . D39 ) = ( D53 . D39 ) by L161 , L179 , SCM_1:10;
L201: ( D55 . D39 ) = ( D53 . D39 ) by L200 , L163 , L183 , L180 , L38 , SCM_1:4;
L202: ( D54 . D39 ) = ( D53 . D39 ) by L201 , L165 , L184 , L185 , L33 , L36 , L38 , SCM_1:8;
L203: ( ( D52 + 5 ) + 1 ) = ( D52 + 6 );
L204: ( D56 . D38 ) = ( D53 . D38 ) by L161 , L179 , SCM_1:10;
L205: ( D55 . D38 ) = ( D53 . D38 ) by L204 , L163 , L183 , L180 , L37 , SCM_1:4;
L206: ( D54 . D38 ) = ( D53 . D38 ) by L205 , L165 , L184 , L185 , L32 , L36 , L37 , SCM_1:8;
L207: ( ( D52 + 4 ) + 1 ) = ( D52 + 5 );
per cases ;
suppose L208: ( D54 . D40 ) <> ( 0 );

reconsider D60 = ( D53 . D38 ) , D61 = ( D53 . D39 ) as Integer;
L209: ( D59 . D38 ) = ( D53 . D38 ) by L167 , L186 , L206 , L199 , SCM_1:10;
L210: ( IC D59 ) = ( 3 + 1 ) by L167 , L186 , L199 , L208 , SCM_1:10;
L211: ( IC D58 ) = ( 4 + 1 ) by L210 , L164 , L207 , SCM_1:5;
L212: ( D59 . D37 ) = ( D54 . D37 ) by L167 , L186 , L199 , SCM_1:10;
L213: ( D58 . D37 ) = ( D54 . D37 ) by L212 , L164 , L207 , L210 , L33 , SCM_1:5;
L214: ( D57 . D37 ) = ( D54 . D37 ) by L213 , L168 , L203 , L211 , SCM_1:9;
reconsider D62 = ( C29 . D37 ) , D63 = ( D53 . D37 ) as (Element of ( NAT )) by L214 , L190 , L177 , L196 , PRE_FF:7;
L215: D63 = ( ( ( ( D53 . D37 ) div 2 ) * 2 ) + ( ( D53 . D37 ) mod 2 ) ) by L189
.= ( ( 2 * D62 ) + 1 ) by L190 , L196 , L198 , L208 , L214 , PRE_FF:6;
L216: ( D63 + 1 ) = ( 2 * ( D62 + 1 ) ) by L215;
L217: ( D59 . D36 ) = 2 by L167 , L186 , L194 , L199 , SCM_1:10;
L218: ( D58 . D36 ) = 2 by L217 , L164 , L207 , L210 , L31 , SCM_1:5;
thus L219: (( IC C29 ) = D44 & ( C29 . D36 ) = 2 & ( C29 . D37 ) = ( (C25 qua Integer) div ( 2 |^ ( C28 + 1 ) ) )) by L218 , L168 , L190 , L197 , L203 , L211 , L213 , SCM_1:9;
thus L220: ( C29 . D37 ) is (Element of ( NAT )) by L190 , L177 , L196 , L214 , PRE_FF:7;
L221: ( Fusc' ( ( D53 . D37 ) + 1 ) ) = ( Fusc ( D63 + 1 ) ) by L140
.= ( Fusc ( D62 + 1 ) ) by L216 , PRE_FF:15
.= ( Fusc' ( ( C29 . D37 ) + 1 ) ) by L140;
L222: ( D59 . D39 ) = ( D53 . D39 ) by L167 , L186 , L202 , L199 , SCM_1:10;
L223: ( D58 . D39 ) = ( ( D53 . D39 ) + ( D53 . D38 ) ) by L222 , L164 , L207 , L210 , L209 , SCM_1:5;
L224: ( D57 . D39 ) = ( ( D53 . D39 ) + ( D53 . D38 ) ) by L223 , L168 , L203 , L211 , SCM_1:9;
L225: ( Fusc' ( D53 . D37 ) ) = ( Fusc D63 ) by L140
.= ( ( Fusc D62 ) + ( Fusc ( D62 + 1 ) ) ) by L215 , PRE_FF:15
.= ( ( Fusc' ( C29 . D37 ) ) + ( Fusc ( D62 + 1 ) ) ) by L140
.= ( ( Fusc' ( C29 . D37 ) ) + ( Fusc' ( ( C29 . D37 ) + 1 ) ) ) by L140;
reconsider D64 = ( C29 . D37 ) , D65 = ( D53 . D37 ) as Integer;
L226: ( D58 . D38 ) = ( D53 . D38 ) by L164 , L207 , L210 , L209 , L34 , SCM_1:5;
L227: ( D57 . D38 ) = ( D53 . D38 ) by L226 , L168 , L203 , L211 , SCM_1:9;
L228: ( ( D60 * ( Fusc' D65 ) ) + ( D61 * ( Fusc' ( D65 + 1 ) ) ) ) = ( ( ( C29 . D38 ) * ( Fusc' D64 ) ) + ( ( C29 . D39 ) * ( Fusc' ( D64 + 1 ) ) ) ) by L227 , L190 , L224 , L225 , L221;
thus L229: thesis by L228 , L170 , L171 , L176 , XXREAL_0:2;
end;
suppose L230: ( D54 . D40 ) = ( 0 );

L231: ( IC D59 ) = 6 by L230 , L167 , L186 , L199 , SCM_1:10;
L232: ( IC D58 ) = ( 6 + 1 ) by L231 , L166 , L207 , SCM_1:5;
L233: ( D59 . D37 ) = ( D54 . D37 ) by L167 , L186 , L199 , SCM_1:10;
L234: ( D58 . D37 ) = ( D54 . D37 ) by L233 , L166 , L207 , L231 , L32 , SCM_1:5;
L235: ( D57 . D37 ) = ( D54 . D37 ) by L234 , L162 , L203 , L232 , SCM_1:9;
reconsider D66 = ( C29 . D37 ) , D67 = ( D53 . D37 ) as (Element of ( NAT )) by L235 , L190 , L177 , L196 , PRE_FF:7;
L236: ( Fusc' ( ( D53 . D37 ) + 1 ) ) = ( Fusc ( D67 + 1 ) ) by L140
.= ( ( Fusc D66 ) + ( Fusc ( D66 + 1 ) ) ) by L190 , L196 , L198 , L189 , L230 , L235 , PRE_FF:15
.= ( ( Fusc D66 ) + ( Fusc' ( ( C29 . D37 ) + 1 ) ) ) by L140
.= ( ( Fusc' ( C29 . D37 ) ) + ( Fusc' ( ( C29 . D37 ) + 1 ) ) ) by L140;
L237: ( D59 . D39 ) = ( D53 . D39 ) by L167 , L186 , L202 , L199 , SCM_1:10;
L238: ( D58 . D39 ) = ( D53 . D39 ) by L237 , L166 , L207 , L231 , L34 , SCM_1:5;
L239: ( D57 . D39 ) = ( D53 . D39 ) by L238 , L162 , L203 , L232 , SCM_1:9;
L240: ( D59 . D36 ) = 2 by L167 , L186 , L194 , L199 , SCM_1:10;
L241: ( D58 . D36 ) = 2 by L240 , L166 , L207 , L231 , L30 , SCM_1:5;
thus L242: (( IC C29 ) = D44 & ( C29 . D36 ) = 2 & ( C29 . D37 ) = ( (C25 qua Integer) div ( 2 |^ ( C28 + 1 ) ) ) & ( C29 . D37 ) is (Element of ( NAT ))) by L241 , L162 , L190 , L177 , L196 , L197 , L203 , L232 , L235 , PRE_FF:7 , SCM_1:9;
L243: ( Fusc' ( D53 . D37 ) ) = ( Fusc D67 ) by L140
.= ( Fusc D66 ) by L190 , L196 , L198 , L189 , L230 , L235 , PRE_FF:15
.= ( Fusc' ( C29 . D37 ) ) by L140;
L244: ( D59 . D38 ) = ( D53 . D38 ) by L167 , L186 , L206 , L199 , SCM_1:10;
L245: ( D58 . D38 ) = ( ( D53 . D38 ) + ( D53 . D39 ) ) by L244 , L166 , L207 , L231 , L237 , SCM_1:5;
L246: ( D57 . D38 ) = ( ( D53 . D38 ) + ( D53 . D39 ) ) by L245 , L162 , L203 , L232 , SCM_1:9;
reconsider D68 = ( C29 . D37 ) , D69 = ( D53 . D37 ) , D70 = ( D53 . D38 ) , D71 = ( D53 . D39 ) as Integer;
L247: ( ( D70 * ( Fusc' D69 ) ) + ( D71 * ( Fusc' ( D69 + 1 ) ) ) ) = ( ( ( D70 + D71 ) * ( Fusc' D68 ) ) + ( D71 * ( Fusc' ( D68 + 1 ) ) ) ) by L243 , L236;
thus L248: thesis by L247 , L170 , L171 , L190 , L176 , L246 , L239 , XXREAL_0:2;
end;
end;
set D72 = ( Comput (R1 , C27 , ( ( 6 * ( D51 + 1 ) ) + 1 )) );
set D73 = ( Comput (R1 , C27 , ( 6 * ( D51 + 1 ) )) );
L250: ( C27 . D37 ) = C25 by L160 , SCM_1:1;
L251: (( C27 . D38 ) = 1 & ( C27 . D39 ) = ( 0 )) by L160 , SCM_1:1;
L252: S2[ ( 0 ) ]
proof
assume L253: ( 0 ) <= ( ( log (2 , C25) ) + 1 );
let C30 being (State of ( SCM ));
assume L254: C30 = ( Comput (R1 , C27 , ( 6 * ( 0 ) )) );
L255: C30 = C27 by L254 , EXTPRO_1:2;
thus L256: (( IC C30 ) = D44 & ( C30 . D36 ) = 2) by L255 , L160 , MEMSTR_0:def 12 , SCM_1:1;
thus L257: ( C30 . D37 ) = ( (C25 qua Integer) div 1 ) by L250 , L255 , PRE_FF:2
.= ( (C25 qua Integer) div ( 2 |^ ( 0 ) ) ) by NEWTON:4;
thus L258: ( C30 . D37 ) is (Element of ( NAT )) by L160 , L255 , SCM_1:1;
thus L259: thesis by L250 , L251 , L255 , L140;
end;
L260: (for B30 being (Element of ( NAT )) holds S2[ B30 ]) from NAT_1:sch 1(L252 , L169);
L261: [\ ( log (2 , C25) ) /] <= ( log (2 , C25) ) by INT_1:def 6;
L262: ( D51 + 1 ) <= ( ( log (2 , C25) ) + 1 ) by L261 , XREAL_1:6;
L263: ( Fusc C25 ) = ( ( ( D73 . D38 ) * ( Fusc' ( D73 . D37 ) ) ) + ( ( D73 . D39 ) * ( Fusc' ( ( D73 . D37 ) + 1 ) ) ) ) by L262 , L260;
L264: ( IC D73 ) = D44 by L260 , L262;
L265: ( D72 . D39 ) = ( D73 . D39 ) by L264 , L161 , SCM_1:10;
L266: ( D73 . D37 ) = ( (C25 qua Integer) div ( 2 |^ ( D51 + 1 ) ) ) by L260 , L262;
L267: ( D73 . D37 ) = ( 0 ) by L266 , L159 , NAT_1:2 , PRE_FF:4;
L268: ( IC D72 ) = D43 by L267 , L161 , L264 , SCM_1:10;
L269: ( R1 . ( IC D73 ) ) <> ( halt ( SCM ) ) by L161 , L264 , SCM_1:12;
L270: ( R1 . D43 ) = ( halt ( SCM ) ) by L149 , L40;
thus L271: R1 halts_on C26 by L270 , L160 , L268 , EXTPRO_1:30;
L272: ( ( ( D73 . D38 ) * ( Fusc' ( D73 . D37 ) ) ) + ( ( D73 . D39 ) * ( Fusc' ( ( D73 . D37 ) + 1 ) ) ) ) = ( ( ( D73 . D38 ) * ( 0 ) ) + ( ( D73 . D39 ) * ( Fusc' ( ( D73 . D37 ) + 1 ) ) ) ) by L267 , L140 , PRE_FF:15
.= ( ( D73 . D39 ) * ( Fusc ( ( 0 ) + 1 ) ) ) by L267 , L140
.= ( D73 . D39 ) by PRE_FF:15;
thus L273: ( ( Result (R1 , C26) ) . ( dl. 3 ) ) = ( Fusc C25 ) by L272 , L160 , L270 , L263 , L268 , L265 , EXTPRO_1:31;
L274: ( R1 . ( IC D72 ) ) = ( halt ( SCM ) ) by L268 , L149 , L40;
thus L275: thesis by L274 , L160 , L269 , EXTPRO_1:33;
end;
theorem
L276: (for R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function holds (( Fib_Program ) c= R1 implies (for B31 being (Element of ( NAT )) holds (for B32 , B33 , B34 being (Element of ( NAT )) holds (for B35 being 3 -started (State-consisting of <% 1 , B31 , B33 , B34 %>) holds ((B31 > ( 0 ) & B33 = ( Fib B32 ) & B34 = ( Fib ( B32 + 1 ) )) implies (R1 halts_on B35 & ( LifeSpan (R1 , B35) ) = ( ( 6 * B31 ) - 4 ) & (ex B36 being (Element of ( NAT )) st (B36 = ( ( B32 + B31 ) - 1 ) & ( ( Result (R1 , B35) ) . ( dl. 2 ) ) = ( Fib B36 ) & ( ( Result (R1 , B35) ) . ( dl. 3 ) ) = ( Fib ( B36 + 1 ) ))))))))))
proof
let R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function;
assume L277: ( Fib_Program ) c= R1;
defpred S3[ (Element of ( NAT )) ] means (for B37 , B38 , B39 being (Element of ( NAT )) holds (for B40 being 3 -started (State-consisting of <% 1 , $1 , B38 , B39 %>) holds (($1 > ( 0 ) & B38 = ( Fib B37 ) & B39 = ( Fib ( B37 + 1 ) )) implies (R1 halts_on B40 & ( LifeSpan (R1 , B40) ) = ( ( 6 * $1 ) - 4 ) & (ex B41 being (Element of ( NAT )) st (B41 = ( ( B37 + $1 ) - 1 ) & ( ( Result (R1 , B40) ) . ( dl. 2 ) ) = ( Fib B41 ) & ( ( Result (R1 , B40) ) . ( dl. 3 ) ) = ( Fib ( B41 + 1 ) )))))));
L278: (for B42 being (Element of ( NAT )) holds (S3[ B42 ] implies S3[ ( B42 + 1 ) ]))
proof
set D74 = ( dl. ( 0 ) );
set D75 = ( dl. 1 );
set D76 = ( dl. 2 );
set D77 = ( dl. 3 );
set D78 = ( dl. 4 );
let C31 being (Element of ( NAT ));
assume L279: S3[ C31 ];
L280: C31 >= ( 0 ) by NAT_1:2;
let C32 , C33 , C34 being (Element of ( NAT ));
let C35 being 3 -started (State-consisting of <% 1 , ( C31 + 1 ) , C33 , C34 %>);
assume that
L281: ( C31 + 1 ) > ( 0 )
and
L282: C33 = ( Fib C32 )
and
L283: C34 = ( Fib ( C32 + 1 ) );
L284: ( R1 . 3 ) = ( SubFrom (D75 , D74) ) by L277 , L40;
set D79 = ( Comput (R1 , C35 , ( 0 )) );
set D80 = ( Comput (R1 , C35 , ( ( 0 ) + 1 )) );
L285: ( R1 . 1 ) = ( halt ( SCM ) ) by L277 , L40;
L286: (( IC C35 ) = 3 & C35 = D79) by EXTPRO_1:2 , MEMSTR_0:def 12;
L287: ( IC D80 ) = ( 3 + 1 ) by L286 , L284 , SCM_1:6
.= 4;
set D81 = ( Comput (R1 , C35 , ( 1 + 1 )) );
L288: ( R1 . 4 ) = ( D75 =0_goto 1 ) by L277 , L40;
L289: ( C35 . D77 ) = C34 by SCM_1:1;
L290: ( D80 . D77 ) = C34 by L289 , L284 , L286 , L33 , SCM_1:6;
L291: ( D81 . D77 ) = C34 by L290 , L288 , L287 , SCM_1:10;
L292: ( R1 . 7 ) = ( AddTo (D77 , D78) ) by L277 , L40;
L293: ( C35 . D76 ) = C33 by SCM_1:1;
L294: ( D80 . D76 ) = C33 by L293 , L284 , L286 , L32 , SCM_1:6;
L295: ( D81 . D76 ) = C33 by L294 , L288 , L287 , SCM_1:10;
L296: ( R1 . 6 ) = ( D76 := D77 ) by L277 , L40;
L297: ( C35 . D74 ) = 1 by SCM_1:1;
L298: ( D80 . D74 ) = 1 by L297 , L284 , L286 , L29 , SCM_1:6;
L299: ( D81 . D74 ) = 1 by L298 , L288 , L287 , SCM_1:10;
L300: ( C35 . D75 ) = ( C31 + 1 ) by SCM_1:1;
L301: ( D80 . D75 ) = ( ( C31 + 1 ) - 1 ) by L300 , L284 , L297 , L286 , SCM_1:6
.= C31;
L302: ( D81 . D75 ) = C31 by L301 , L288 , L287 , SCM_1:10;
L303: ( R1 . 5 ) = ( D78 := D76 ) by L277 , L40;
L304: ( R1 . 8 ) = ( SCM-goto 3 ) by L277 , L40;
per cases  by L280 , XXREAL_0:1;
suppose L305: C31 = ( 0 );

L306: ( R1 . ( IC D81 ) ) = ( halt ( SCM ) ) by L305 , L285 , L288 , L301 , L287 , SCM_1:10;
thus L307: R1 halts_on C35 by L306 , EXTPRO_1:30;
L308: ( R1 . ( IC D80 ) ) <> ( halt ( SCM ) ) by L288 , L287 , SCM_1:12;
thus L309: ( LifeSpan (R1 , C35) ) = ( ( 6 * ( C31 + 1 ) ) - 4 ) by L308 , L305 , L306 , EXTPRO_1:32;
take D82 = C32;
thus L310: D82 = ( ( C32 + ( C31 + 1 ) ) - 1 ) by L305;
thus L311: thesis by L282 , L283 , L295 , L291 , L306 , EXTPRO_1:31;
end;
suppose L312: C31 > ( 0 );

L313: ( ( 6 * C31 ) - 4 ) > ( 0 ) by L312 , L24;
set D83 = ( Fib ( ( C32 + 1 ) + 1 ) );
set D84 = ( Comput (R1 , C35 , ( 5 + 1 )) );
set D85 = ( Comput (R1 , C35 , ( 4 + 1 )) );
set D86 = ( Comput (R1 , C35 , ( 3 + 1 )) );
set D87 = ( Comput (R1 , C35 , ( 2 + 1 )) );
L314: ( IC D81 ) = ( 4 + 1 ) by L288 , L301 , L287 , L312 , SCM_1:10;
L315: ( IC D87 ) = ( 5 + 1 ) by L314 , L303 , SCM_1:4;
L316: ( IC D86 ) = ( 6 + 1 ) by L315 , L296 , SCM_1:4;
L317: ( IC D85 ) = ( 7 + 1 ) by L316 , L292 , SCM_1:5;
L318: ( D87 . D77 ) = ( Fib ( C32 + 1 ) ) by L283 , L303 , L291 , L314 , L38 , SCM_1:4;
L319: ( D86 . D77 ) = ( Fib ( C32 + 1 ) ) by L318 , L296 , L315 , L34 , SCM_1:4;
L320: ( D86 . D76 ) = ( Fib ( C32 + 1 ) ) by L296 , L315 , L318 , SCM_1:4;
L321: ( D85 . D76 ) = ( Fib ( C32 + 1 ) ) by L320 , L292 , L316 , L34 , SCM_1:5;
L322: ( D84 . D76 ) = ( Fib ( C32 + 1 ) ) by L321 , L304 , L317 , SCM_1:9;
L323: ( D87 . D74 ) = 1 by L303 , L299 , L314 , L35 , SCM_1:4;
L324: ( D86 . D74 ) = 1 by L323 , L296 , L315 , L30 , SCM_1:4;
L325: ( D85 . D74 ) = 1 by L324 , L292 , L316 , L31 , SCM_1:5;
L326: ( D84 . D74 ) = 1 by L325 , L304 , L317 , SCM_1:9;
L327: ( D87 . D78 ) = ( Fib C32 ) by L282 , L303 , L295 , L314 , SCM_1:4;
L328: ( D86 . D78 ) = ( Fib C32 ) by L327 , L296 , L315 , L37 , SCM_1:4;
L329: ( D85 . D77 ) = ( ( D86 . D78 ) + ( D86 . D77 ) ) by L292 , L316 , SCM_1:5
.= ( Fib ( ( C32 + 1 ) + 1 ) ) by L319 , L328 , PRE_FF:1;
L330: ( D84 . D77 ) = ( Fib ( ( C32 + 1 ) + 1 ) ) by L329 , L304 , L317 , SCM_1:9;
L331: ( D87 . D75 ) = C31 by L303 , L302 , L314 , L36 , SCM_1:4;
L332: ( D86 . D75 ) = C31 by L331 , L296 , L315 , L32 , SCM_1:4;
L333: ( D85 . D75 ) = C31 by L332 , L292 , L316 , L33 , SCM_1:5;
L334: ( D84 . D75 ) = C31 by L333 , L304 , L317 , SCM_1:9;
L335: ( IC D84 ) = 3 by L304 , L317 , SCM_1:9;
L336: D84 is 3 -started 3 -started 3 -started 3 -started (State-consisting of <% 1 , C31 , C34 , D83 %>) by L335 , L283 , L326 , L334 , L322 , L330 , MEMSTR_0:def 12 , SCM_1:13;
consider C36 being (Element of ( NAT )) such that L337: C36 = ( ( ( C32 + 1 ) + C31 ) - 1 ) and L338: ( ( Result (R1 , D84) ) . ( dl. 2 ) ) = ( Fib C36 ) and L339: ( ( Result (R1 , D84) ) . ( dl. 3 ) ) = ( Fib ( C36 + 1 ) ) by L336 , L279 , L283 , L312;
L340: R1 halts_on D84 by L279 , L283 , L312 , L336;
thus L341: R1 halts_on C35 by L340 , EXTPRO_1:22;
L342: ( LifeSpan (R1 , D84) ) = ( ( 6 * C31 ) - 4 ) by L279 , L283 , L312 , L336;
thus L343: ( LifeSpan (R1 , C35) ) = ( 6 + ( ( 6 * C31 ) - 4 ) ) by L342 , L279 , L283 , L312 , L336 , L313 , EXTPRO_1:34
.= ( ( 6 * ( C31 + 1 ) ) - 4 );
take C36;
thus L344: C36 = ( ( C32 + ( C31 + 1 ) ) - 1 ) by L337;
L345: (ex B43 being (Element of ( NAT )) st (B43 = ( ( ( C32 + 1 ) + C31 ) - 1 ) & ( ( Result (R1 , D84) ) . ( dl. 2 ) ) = ( Fib B43 ) & ( ( Result (R1 , D84) ) . ( dl. 3 ) ) = ( Fib ( B43 + 1 ) ))) by L279 , L283 , L312 , L336;
thus L346: thesis by L345 , L337 , L279 , L283 , L312 , L336 , EXTPRO_1:35;
end;
end;
L348: S3[ ( 0 ) ];
thus L349: (for B44 being (Element of ( NAT )) holds S3[ B44 ]) from NAT_1:sch 1(L348 , L278);
end;
theorem
L350: (for R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function holds (( Fusc_Program ) c= R1 implies (for B45 being (Element of ( NAT )) holds (for B46 , B47 , B48 being (Element of ( NAT )) holds (for B49 being ( 0 ) -started (State-consisting of <% 2 , B45 , B47 , B48 %>) holds ((B46 > ( 0 ) & ( Fusc B46 ) = ( ( B47 * ( Fusc B45 ) ) + ( B48 * ( Fusc ( B45 + 1 ) ) ) )) implies (R1 halts_on B49 & ( ( Result (R1 , B49) ) . ( dl. 3 ) ) = ( Fusc B46 ) & (B45 = ( 0 ) implies ( LifeSpan (R1 , B49) ) = 1) & (B45 > ( 0 ) implies ( LifeSpan (R1 , B49) ) = ( ( 6 * ( [\ ( log (2 , B45) ) /] + 1 ) ) + 1 )))))))))
proof
let R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function;
assume L351: ( Fusc_Program ) c= R1;
defpred S4[ Nat ] means (for B50 , B51 , B52 being (Element of ( NAT )) holds (for B53 being ( 0 ) -started (State-consisting of <% 2 , $1 , B51 , B52 %>) holds ((B50 > ( 0 ) & ( Fusc B50 ) = ( ( B51 * ( Fusc $1 ) ) + ( B52 * ( Fusc ( $1 + 1 ) ) ) )) implies (R1 halts_on B53 & ( ( Result (R1 , B53) ) . ( dl. 3 ) ) = ( Fusc B50 ) & ($1 = ( 0 ) implies ( LifeSpan (R1 , B53) ) = 1) & ($1 > ( 0 ) implies ( LifeSpan (R1 , B53) ) = ( ( 6 * ( [\ ( log (2 , $1) ) /] + 1 ) ) + 1 ))))));
L352: (for B54 being Nat holds ((for B55 being Nat holds (B55 < B54 implies S4[ B55 ])) implies S4[ B54 ]))
proof
set D88 = ( dl. ( 0 ) );
set D89 = ( dl. 1 );
set D90 = ( dl. 2 );
set D91 = ( dl. 3 );
set D92 = ( dl. 4 );
let C37 being Nat;
assume L353: (for B56 being Nat holds (B56 < C37 implies (for B57 , B58 , B59 being (Element of ( NAT )) holds (for B60 being ( 0 ) -started (State-consisting of <% 2 , B56 , B58 , B59 %>) holds ((B57 > ( 0 ) & ( Fusc B57 ) = ( ( B58 * ( Fusc B56 ) ) + ( B59 * ( Fusc ( B56 + 1 ) ) ) )) implies (R1 halts_on B60 & ( ( Result (R1 , B60) ) . ( dl. 3 ) ) = ( Fusc B57 ) & (B56 = ( 0 ) implies ( LifeSpan (R1 , B60) ) = 1) & (B56 > ( 0 ) implies ( LifeSpan (R1 , B60) ) = ( ( 6 * ( [\ ( log (2 , B56) ) /] + 1 ) ) + 1 ))))))));
reconsider D93 = C37 as (Element of ( NAT )) by ORDINAL1:def 12;
let C38 , C39 , C40 being (Element of ( NAT ));
let C41 being ( 0 ) -started (State-consisting of <% 2 , C37 , C39 , C40 %>);
assume that
L354: C38 > ( 0 )
and
L355: ( Fusc C38 ) = ( ( C39 * ( Fusc C37 ) ) + ( C40 * ( Fusc ( C37 + 1 ) ) ) );
L356: ( C41 . D89 ) = C37 by SCM_1:1;
set D94 = ( Comput (R1 , C41 , ( 0 )) );
L357: ( R1 . ( 0 ) ) = ( D89 =0_goto 8 ) by L351 , L40;
set D95 = ( Comput (R1 , C41 , ( ( 0 ) + 1 )) );
L358: ( R1 . 8 ) = ( halt ( SCM ) ) by L351 , L40;
L359: ( R1 . 3 ) = ( D92 =0_goto 6 ) by L351 , L40;
L360: (( IC C41 ) = ( 0 ) & C41 = D94) by EXTPRO_1:2 , MEMSTR_0:def 12;
L361: ( C41 . D90 ) = C39 by SCM_1:1;
L362: ( D95 . D90 ) = C39 by L361 , L357 , L360 , SCM_1:10;
L363: ( C41 . D88 ) = 2 by SCM_1:1;
L364: ( D95 . D88 ) = 2 by L363 , L357 , L360 , SCM_1:10;
L365: ( R1 . 2 ) = ( Divide (D89 , D92) ) by L351 , L40;
L366: ( C41 . D91 ) = C40 by SCM_1:1;
L367: ( D95 . D91 ) = C40 by L366 , L357 , L360 , SCM_1:10;
L368:
now
assume L369: C37 = ( 0 );
L370: ( R1 . ( IC D95 ) ) = ( halt ( SCM ) ) by L369 , L357 , L358 , L356 , L360 , SCM_1:10;
thus L371: R1 halts_on C41 by L370 , EXTPRO_1:30;
thus L372: ( ( Result (R1 , C41) ) . D91 ) = ( D95 . D91 ) by L370 , EXTPRO_1:31
.= ( Fusc C38 ) by L355 , L367 , L369 , PRE_FF:18;
thus L373:now
assume L374: C37 = ( 0 );
L375: ( halt ( SCM ) ) <> ( D89 =0_goto 8 ) by SCM_1:12;
thus L376: ( LifeSpan (R1 , C41) ) = 1 by L375 , L357 , L360 , L370 , EXTPRO_1:33;
end;
thus L377: (C37 > ( 0 ) implies ( LifeSpan (R1 , C41) ) = ( ( 6 * ( [\ ( log (2 , C37) ) /] + 1 ) ) + 1 )) by L369;
end;
L378: ( R1 . 1 ) = ( D92 := D88 ) by L351 , L40;
L379: ( R1 . 5 ) = ( SCM-goto ( 0 ) ) by L351 , L40;
L380: ( R1 . 4 ) = ( AddTo (D91 , D90) ) by L351 , L40;
L381: ( R1 . 7 ) = ( SCM-goto ( 0 ) ) by L351 , L40;
L382: ( R1 . 6 ) = ( AddTo (D90 , D91) ) by L351 , L40;
L383: ( D95 . D89 ) = C37 by L357 , L356 , L360 , SCM_1:10;
L384:
now
set D96 = ( Comput (R1 , C41 , ( 5 + 1 )) );
set D97 = ( Comput (R1 , C41 , ( 4 + 1 )) );
set D98 = ( Comput (R1 , C41 , ( 3 + 1 )) );
set D99 = ( Comput (R1 , C41 , ( 2 + 1 )) );
set D100 = ( Comput (R1 , C41 , ( 1 + 1 )) );
L385: ( C37 mod 2 ) = ( C37 - ( ( C37 div 2 ) * 2 ) ) by INT_1:def 10;
assume L386: C37 > ( 0 );
L387: ( IC D95 ) = ( ( 0 ) + 1 ) by L386 , L357 , L356 , L360 , SCM_1:10;
L388: ( IC D100 ) = ( 1 + 1 ) by L387 , L378 , SCM_1:4;
L389: ( IC D99 ) = ( 2 + 1 ) by L388 , L365 , L36 , SCM_1:8;
L390: ( D100 . D90 ) = C39 by L378 , L362 , L387 , L37 , SCM_1:4;
L391: ( D99 . D90 ) = C39 by L390 , L365 , L388 , L32 , L36 , L37 , SCM_1:8;
L392: ( D100 . D88 ) = 2 by L378 , L364 , L387 , L35 , SCM_1:4;
L393: ( D99 . D88 ) = 2 by L392 , L365 , L388 , L29 , L35 , L36 , SCM_1:8;
L394: ( D100 . D91 ) = C40 by L378 , L367 , L387 , L38 , SCM_1:4;
L395: ( D99 . D91 ) = C40 by L394 , L365 , L388 , L33 , L36 , L38 , SCM_1:8;
L396: (( D100 . D92 ) = 2 & ( D100 . D89 ) = C37) by L378 , L364 , L383 , L387 , L36 , SCM_1:4;
L397: ( D99 . D89 ) = ( D93 div 2 ) by L396 , L365 , L388 , L36 , SCM_1:8;
reconsider D101 = ( D99 . D89 ) as (Element of ( NAT )) by L397 , PRE_FF:7;
L398: ( D99 . D92 ) = ( C37 mod 2 ) by L365 , L388 , L396 , L36 , SCM_1:8;
per cases ;
suppose L399: ( D99 . D92 ) <> ( 0 );

L400: ( IC D98 ) = ( 3 + 1 ) by L399 , L359 , L389 , SCM_1:10;
L401: ( IC D97 ) = ( 4 + 1 ) by L400 , L380 , SCM_1:5;
L402: ( D98 . D90 ) = C39 by L359 , L389 , L391 , SCM_1:10;
L403: ( D97 . D90 ) = C39 by L402 , L380 , L400 , L34 , SCM_1:5;
L404: ( D96 . D90 ) = C39 by L403 , L379 , L401 , SCM_1:9;
L405: ( D98 . D91 ) = C40 by L359 , L389 , L395 , SCM_1:10;
L406: ( D97 . D91 ) = ( C40 + C39 ) by L405 , L380 , L400 , L402 , SCM_1:5;
L407: ( D99 . D92 ) = 1 by L398 , L399 , PRE_FF:6;
L408: ( D98 . D89 ) = ( D99 . D89 ) by L359 , L389 , SCM_1:10;
L409: ( D97 . D89 ) = ( D99 . D89 ) by L408 , L380 , L400 , L33 , SCM_1:5;
L410: ( D96 . D89 ) = ( D99 . D89 ) by L409 , L379 , L401 , SCM_1:9;
L411: ( D98 . D88 ) = 2 by L359 , L389 , L393 , SCM_1:10;
L412: ( D97 . D88 ) = 2 by L411 , L380 , L400 , L31 , SCM_1:5;
L413: ( D96 . D88 ) = 2 by L412 , L379 , L401 , SCM_1:9;
L414: (( IC D96 ) = ( 0 ) & ( D96 . D91 ) = ( D97 . D91 )) by L379 , L401 , SCM_1:9;
L415: D96 is ( 0 ) -started ( 0 ) -started ( 0 ) -started ( 0 ) -started (State-consisting of <% 2 , D101 , C39 , ( C40 + C39 ) %>) by L414 , L406 , L413 , L410 , L404 , MEMSTR_0:def 12 , SCM_1:13;
L416: ( ( C37 mod 2 ) + ( ( C37 div 2 ) * 2 ) ) = C37 by L385;
L417: D101 < C37 by L416 , L397 , L398 , L407 , PRE_FF:17;
L418: ( Fusc C38 ) = ( ( C39 * ( Fusc D101 ) ) + ( ( C40 + C39 ) * ( Fusc ( D101 + 1 ) ) ) ) by L355 , L397 , L398 , L407 , L416 , PRE_FF:19;
L419: (D101 > ( 0 ) implies ( LifeSpan (R1 , D96) ) = ( ( 6 * ( [\ ( log (2 , D101) ) /] + 1 ) ) + 1 )) by L418 , L353 , L354 , L415 , L417;
L420: R1 halts_on D96 by L353 , L354 , L415 , L417 , L418;
thus L421: R1 halts_on C41 by L420 , EXTPRO_1:22;
L422: ( ( Result (R1 , D96) ) . ( dl. 3 ) ) = ( Fusc C38 ) by L353 , L354 , L415 , L417 , L418;
thus L423: ( ( Result (R1 , C41) ) . ( dl. 3 ) ) = ( Fusc C38 ) by L422 , L420 , EXTPRO_1:35;
thus L424: (C37 = ( 0 ) implies ( LifeSpan (R1 , C41) ) = 1) by L386;
L425: (D101 = ( 0 ) implies ( LifeSpan (R1 , D96) ) = 1) by L353 , L354 , L397 , L398 , L385 , L407 , L415 , L418;
thus L426: (C37 > ( 0 ) implies ( LifeSpan (R1 , C41) ) = ( ( 6 * ( [\ ( log (2 , C37) ) /] + 1 ) ) + 1 ))
proof
assume L427: C37 > ( 0 );
per cases ;
suppose L428: D101 = ( 0 );

thus L429: thesis by L428 , L397 , L398 , L385 , L407 , L420 , L425 , L1 , EXTPRO_1:34;
end;
suppose L430: D101 <> ( 0 );

L431: D101 > ( 0 ) by L430 , NAT_1:3;
reconsider D102 = [\ ( log (2 , D101) ) /] as (Element of ( NAT )) by L431 , L3;
L432: ( ( 6 * ( D102 + 1 ) ) + 1 ) > ( 0 ) by L431 , L3;
thus L433: ( LifeSpan (R1 , C41) ) = ( 6 + ( ( 6 * ( D102 + 1 ) ) + 1 ) ) by L432 , L420 , L419 , L430 , EXTPRO_1:34 , NAT_1:3
.= ( ( 6 * ( [\ ( log (2 , C37) ) /] + 1 ) ) + 1 ) by L397 , L398 , L407 , L416 , L431 , L14;
end;
end;

end;
suppose L427: ( D99 . D92 ) = ( 0 );

L428: ( IC D98 ) = 6 by L427 , L359 , L389 , SCM_1:10;
L429: ( IC D97 ) = ( 6 + 1 ) by L428 , L382 , SCM_1:5;
L430: ( D98 . D88 ) = 2 by L359 , L389 , L393 , SCM_1:10;
L431: ( D97 . D88 ) = 2 by L430 , L382 , L428 , L30 , SCM_1:5;
L432: ( D96 . D88 ) = 2 by L431 , L381 , L429 , SCM_1:9;
L433: ( D98 . D91 ) = C40 by L359 , L389 , L395 , SCM_1:10;
L434: ( D97 . D91 ) = C40 by L433 , L382 , L428 , L34 , SCM_1:5;
L435: ( D96 . D91 ) = C40 by L434 , L381 , L429 , SCM_1:9;
L436: ( D98 . D89 ) = ( D99 . D89 ) by L359 , L389 , SCM_1:10;
L437: ( D97 . D89 ) = ( D99 . D89 ) by L436 , L382 , L428 , L32 , SCM_1:5;
L438: ( D96 . D89 ) = ( D99 . D89 ) by L437 , L381 , L429 , SCM_1:9;
L439: ( D98 . D90 ) = C39 by L359 , L389 , L391 , SCM_1:10;
L440: ( D97 . D90 ) = ( C39 + C40 ) by L439 , L382 , L428 , L433 , SCM_1:5;
reconsider D103 = ( D99 . D89 ) as (Element of ( NAT )) by L397 , PRE_FF:7;
L441: (( IC D96 ) = ( 0 ) & ( D96 . D90 ) = ( D97 . D90 )) by L381 , L429 , SCM_1:9;
L442: D96 is ( 0 ) -started ( 0 ) -started ( 0 ) -started ( 0 ) -started (State-consisting of <% 2 , D103 , ( C39 + C40 ) , C40 %>) by L441 , L440 , L432 , L438 , L435 , MEMSTR_0:def 12 , SCM_1:13;
L443: (D103 < C37 & ( Fusc C38 ) = ( ( ( C39 + C40 ) * ( Fusc D103 ) ) + ( C40 * ( Fusc ( D103 + 1 ) ) ) )) by L355 , L386 , L397 , L398 , L385 , L427 , PRE_FF:16 , PRE_FF:20;
L444: R1 halts_on D96 by L443 , L353 , L354 , L442;
thus L445: R1 halts_on C41 by L444 , EXTPRO_1:22;
L446: ( ( Result (R1 , D96) ) . ( dl. 3 ) ) = ( Fusc C38 ) by L353 , L354 , L442 , L443;
thus L447: ( ( Result (R1 , C41) ) . ( dl. 3 ) ) = ( Fusc C38 ) by L446 , L444 , EXTPRO_1:35;
thus L448: (C37 = ( 0 ) implies ( LifeSpan (R1 , C41) ) = 1) by L386;
L449: (D103 > ( 0 ) implies ( LifeSpan (R1 , D96) ) = ( ( 6 * ( [\ ( log (2 , D103) ) /] + 1 ) ) + 1 )) by L353 , L354 , L442 , L443;
thus L450: (C37 > ( 0 ) implies ( LifeSpan (R1 , C41) ) = ( ( 6 * ( [\ ( log (2 , C37) ) /] + 1 ) ) + 1 ))
proof
assume L451: C37 > ( 0 );
per cases ;
suppose L452: D103 = ( 0 );

thus L453: thesis by L452 , L365 , L386 , L388 , L396 , L397 , L385 , L427 , L36 , SCM_1:8;
end;
suppose L454: D103 <> ( 0 );

L455: D103 > ( 0 ) by L454 , NAT_1:3;
reconsider D104 = [\ ( log (2 , D103) ) /] as (Element of ( NAT )) by L455 , L3;
L456: ( ( 6 * ( D104 + 1 ) ) + 1 ) > ( 0 ) by L455 , L3;
thus L457: ( LifeSpan (R1 , C41) ) = ( 6 + ( ( 6 * ( D104 + 1 ) ) + 1 ) ) by L456 , L444 , L449 , L454 , EXTPRO_1:34 , NAT_1:3
.= ( ( 6 * ( [\ ( log (2 , C37) ) /] + 1 ) ) + 1 ) by L397 , L398 , L385 , L427 , L455 , L21;
end;
end;

end;
end;
L452: C37 >= ( 0 ) by NAT_1:2;
thus L453: thesis by L452 , L368 , L384 , XXREAL_0:1;
end;
L454: (for B61 being Nat holds S4[ B61 ]) from NAT_1:sch 4(L352);
thus L455: thesis by L454;
end;
theorem
L456: (for R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function holds (( Fusc_Program ) c= R1 implies (for B62 being (Element of ( NAT )) holds (B62 > ( 0 ) implies (for B63 being ( 0 ) -started (State-consisting of <% 2 , B62 , 1 , ( 0 ) %>) holds (R1 halts_on B63 & ( ( Result (R1 , B63) ) . ( dl. 3 ) ) = ( Fusc B62 ) & (B62 = ( 0 ) implies ( LifeSpan (R1 , B63) ) = 1) & (B62 > ( 0 ) implies ( LifeSpan (R1 , B63) ) = ( ( 6 * ( [\ ( log (2 , B62) ) /] + 1 ) ) + 1 ))))))))
proof
let R1 being  total ( NAT ) -defined (the InstructionsF of ( SCM )) -valued Function;
assume L457: ( Fusc_Program ) c= R1;
let C42 being (Element of ( NAT ));
L458: ( Fusc C42 ) = ( ( 1 * ( Fusc C42 ) ) + ( ( 0 ) * ( Fusc ( C42 + 1 ) ) ) );
thus L459: thesis by L458 , L457 , L350;
end;
