:: Classes of Conjugation. Normal Subgroups
::  by Wojciech A. Trybulec
::
:: Received August 10, 1990
:: Copyright (c) 1990-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies GROUP_1, SUBSET_1, GROUP_2, NAT_1, INT_1, RELAT_1, BINOP_1,
      ALGSTR_0, FUNCT_1, STRUCT_0, TARSKI, ZFMISC_1, XBOOLE_0, FINSET_1,
      CARD_1, NEWTON, ARYTM_3, XXREAL_0, COMPLEX1, RLSUB_1, CQC_SIM1, SETFAM_1,
      PRE_TOPC, GROUP_3;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, ORDINAL1, NAT_1, BINOP_1,
      RELAT_1, FUNCT_1, FUNCT_2, FINSET_1, CARD_1, STRUCT_0, ALGSTR_0, GROUP_1,
      GROUP_2, DOMAIN_1, XXREAL_0, INT_1, INT_2;
 constructors SETFAM_1, WELLORD2, BINOP_1, XXREAL_0, NAT_1, INT_2, REALSET1,
      REAL_1, GROUP_2, RELSET_1, BINOP_2;
 registrations XBOOLE_0, SUBSET_1, FUNCT_1, RELSET_1, FINSET_1, XREAL_0, INT_1,
      STRUCT_0, GROUP_1, GROUP_2, ORDINAL1;
 requirements NUMERALS, SUBSET, BOOLE;
 definitions XBOOLE_0, BINOP_1, FUNCT_1, GROUP_2, TARSKI, GROUP_1, ALGSTR_0,
      STRUCT_0;
 theorems ABSVALUE, BINOP_1, CARD_1, CARD_2, ENUMSET1, FINSET_1, FUNCT_1,
      FUNCT_2, GROUP_1, GROUP_2, TARSKI, WELLORD2, ZFMISC_1, RELAT_1, XBOOLE_0,
      XBOOLE_1, STRUCT_0, XTUPLE_0;
 schemes FUNCT_1, FUNCT_2, NAT_1, SUBSET_1, XBOOLE_0, CLASSES1;

begin
theorem
L1: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (( ( R6 * R7 ) * ( R7 " ) ) = R6 & ( ( R6 * ( R7 " ) ) * R7 ) = R6 & ( ( ( R7 " ) * R7 ) * R6 ) = R6 & ( ( R7 * ( R7 " ) ) * R6 ) = R6 & ( R6 * ( R7 * ( R7 " ) ) ) = R6 & ( R6 * ( ( R7 " ) * R7 ) ) = R6 & ( ( R7 " ) * ( R7 * R6 ) ) = R6 & ( R7 * ( ( R7 " ) * R6 ) ) = R6))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L2: ( ( R6 * R7 ) * ( R7 " ) ) = ( R6 * ( R7 * ( R7 " ) ) ) by GROUP_1:def 3
.= ( R6 * ( 1_ R5 ) ) by GROUP_1:def 5
.= R6 by GROUP_1:def 4;
thus L3: ( ( R6 * ( R7 " ) ) * R7 ) = ( R6 * ( ( R7 " ) * R7 ) ) by GROUP_1:def 3
.= ( R6 * ( 1_ R5 ) ) by GROUP_1:def 5
.= R6 by GROUP_1:def 4;
thus L4: ( ( ( R7 " ) * R7 ) * R6 ) = ( ( 1_ R5 ) * R6 ) by GROUP_1:def 5
.= R6 by GROUP_1:def 4;
thus L5: ( ( R7 * ( R7 " ) ) * R6 ) = ( ( 1_ R5 ) * R6 ) by GROUP_1:def 5
.= R6 by GROUP_1:def 4;
thus L6: thesis by L5 , L2 , L3 , L4 , GROUP_1:def 3;
end;
L7: (for B1 being  commutative Group holds (for B2 , B3 being (Element of B1) holds ( B2 * B3 ) = ( B3 * B2 )));
theorem
L8: (for R5 being Group holds (R5 is  commutative  commutative  commutative  commutative Group iff (the multF of R5) is  commutative))
proof
let R5 being Group;
thus L9: (R5 is  commutative  commutative  commutative  commutative Group implies (the multF of R5) is  commutative)
proof
assume L10: R5 is  commutative  commutative  commutative  commutative Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L11: ( (the multF of R5) . (R6 , R7) ) = ( R6 * R7 )
.= ( R7 * R6 ) by L10 , L7
.= ( (the multF of R5) . (R7 , R6) );
end;

assume L12: (the multF of R5) is  commutative;
L13: R5 is  commutative
proof
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L14: thesis by L12 , BINOP_1:def 2;
end;
thus L15: thesis by L13;
end;
theorem
L16: (for R5 being Group holds ( (1). R5 ) is  commutative)
proof
let R5 being Group;
let C1 , C2 being (Element of ( (1). R5 ));
L17: C1 in (the carrier of ( (1). R5 ));
L18: C1 in { ( 1_ R5 ) } by L17 , GROUP_2:def 7;
L19: C1 = ( 1_ R5 ) by L18 , TARSKI:def 1;
L20: C2 in (the carrier of ( (1). R5 ));
L21: C2 in { ( 1_ R5 ) } by L20 , GROUP_2:def 7;
thus L22: thesis by L21 , L19 , TARSKI:def 1;
end;
theorem
L23: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (for R14 being (Subset of R5) holds (for R15 being (Subset of R5) holds ((R12 c= R13 & R14 c= R15) implies ( R12 * R14 ) c= ( R13 * R15 )))))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
let R14 being (Subset of R5);
let R15 being (Subset of R5);
assume L24: (R12 c= R13 & R14 c= R15);
let R1 being set;
assume L25: R1 in ( R12 * R14 );
L26: (ex R6 being (Element of R5) st (ex R8 being (Element of R5) st (R1 = ( R6 * R8 ) & R6 in R12 & R8 in R14))) by L25;
thus L27: thesis by L26 , L24;
end;
theorem
L28: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R12 c= R13 implies (( R6 * R12 ) c= ( R6 * R13 ) & ( R12 * R6 ) c= ( R13 * R6 ))))))) by L23;
theorem
L29: (for R5 being Group holds (for R6 being (Element of R5) holds (for R17 being (Subgroup of R5) holds (for R18 being (Subgroup of R5) holds (R17 is (Subgroup of R18) implies (( R6 * R17 ) c= ( R6 * R18 ) & ( R17 * R6 ) c= ( R18 * R6 )))))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R17 being (Subgroup of R5);
let R18 being (Subgroup of R5);
assume L30: R17 is (Subgroup of R18);
L31: (the carrier of R17) c= (the carrier of R18) by L30 , GROUP_2:def 5;
thus L32: thesis by L31 , L23;
end;
theorem
L33: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds ( R6 * R16 ) = ( { R6 } * R16 ))));
theorem
L34: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds ( R16 * R6 ) = ( R16 * { R6 } ))));
theorem
L35: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R16 being (Subgroup of R5) holds ( ( R12 * R6 ) * R16 ) = ( R12 * ( R6 * R16 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R12 being (Subset of R5);
let R16 being (Subgroup of R5);
thus L36: ( ( R12 * R6 ) * R16 ) = ( R12 * ( { R6 } * R16 ) ) by GROUP_2:96
.= ( R12 * ( R6 * R16 ) );
end;
theorem
L37: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R16 being (Subgroup of R5) holds ( ( R6 * R16 ) * R12 ) = ( R6 * ( R16 * R12 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R12 being (Subset of R5);
let R16 being (Subgroup of R5);
thus L38: ( ( R6 * R16 ) * R12 ) = ( ( { R6 } * R16 ) * R12 )
.= ( R6 * ( R16 * R12 ) ) by GROUP_2:97;
end;
theorem
L39: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R16 being (Subgroup of R5) holds ( ( R12 * R16 ) * R6 ) = ( R12 * ( R16 * R6 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R12 being (Subset of R5);
let R16 being (Subgroup of R5);
thus L40: ( ( R12 * R16 ) * R6 ) = ( R12 * ( R16 * { R6 } ) ) by GROUP_2:97
.= ( R12 * ( R16 * R6 ) );
end;
theorem
L41: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R16 being (Subgroup of R5) holds ( ( R16 * R6 ) * R12 ) = ( R16 * ( R6 * R12 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R12 being (Subset of R5);
let R16 being (Subgroup of R5);
thus L42: ( ( R16 * R6 ) * R12 ) = ( ( R16 * { R6 } ) * R12 )
.= ( R16 * ( R6 * R12 ) ) by GROUP_2:98;
end;
theorem
L43: (for R5 being Group holds (for R6 being (Element of R5) holds (for R17 being (Subgroup of R5) holds (for R18 being (Subgroup of R5) holds ( ( R17 * R6 ) * R18 ) = ( R17 * ( R6 * R18 ) ))))) by L35;
definition
let R5 being Group;
func Subgroups R5 -> set means 
:L44: (for R1 being set holds (R1 in it iff R1 is  strict  strict  strict  strict (Subgroup of R5)));
existence
proof
defpred S1[ set , set ] means (ex B4 being  strict (Subgroup of R5) st ($2 = B4 & $1 = (the carrier of B4)));
defpred S2[ set ] means (ex B5 being  strict (Subgroup of R5) st $1 = (the carrier of B5));
consider C3 being set such that L45: (for R1 being set holds (R1 in C3 iff (R1 in ( bool (the carrier of R5) ) & S2[ R1 ]))) from XBOOLE_0:sch 1;
L46: (for R1 being set holds (for R3 being set holds (for R4 being set holds ((S1[ R1 , R3 ] & S1[ R1 , R4 ]) implies R3 = R4)))) by GROUP_2:59;
consider C4 being Function such that L47: (for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in C4 iff (R1 in C3 & S1[ R1 , R2 ])))) from FUNCT_1:sch 1(L46);
L48: (for R1 being set holds (R1 in C3 iff (ex R2 being set st [ R1 , R2 ] in C4)))
proof
let R1 being set;
thus L49: (R1 in C3 implies (ex R2 being set st [ R1 , R2 ] in C4))
proof
assume L50: R1 in C3;
consider C5 being  strict (Subgroup of R5) such that L51: R1 = (the carrier of C5) by L50 , L45;
reconsider D1 = C5 as set;
take D1;
thus L52: thesis by L47 , L50 , L51;
end;

given R2 being set such that
L53: [ R1 , R2 ] in C4;

thus L54: thesis by L47 , L53;
end;
L55: C3 = ( dom C4 ) by L48 , XTUPLE_0:def 12;
L56: (for R2 being set holds (R2 in ( rng C4 ) iff R2 is  strict  strict  strict  strict (Subgroup of R5)))
proof
let R2 being set;
thus L57: (R2 in ( rng C4 ) implies R2 is  strict  strict  strict  strict (Subgroup of R5))
proof
assume L58: R2 in ( rng C4 );
consider R1 being set such that L59: (R1 in ( dom C4 ) & R2 = ( C4 . R1 )) by L58 , FUNCT_1:def 3;
L60: [ R1 , R2 ] in C4 by L59 , FUNCT_1:def 2;
L61: (ex B6 being  strict (Subgroup of R5) st (R2 = B6 & R1 = (the carrier of B6))) by L60 , L47;
thus L62: thesis by L61;
end;

assume L63: R2 is  strict  strict  strict  strict (Subgroup of R5);
reconsider D2 = R2 as  strict (Subgroup of R5) by L63;
reconsider D3 = (the carrier of D2) as set;
L64: (the carrier of D2) c= (the carrier of R5) by GROUP_2:def 5;
L65: D3 in ( dom C4 ) by L64 , L45 , L55;
L66: [ D3 , R2 ] in C4 by L65 , L47 , L55;
L67: R2 = ( C4 . D3 ) by L66 , L65 , FUNCT_1:def 2;
thus L68: thesis by L67 , L65 , FUNCT_1:def 3;
end;
thus L69: thesis by L56;
end;
uniqueness
proof
defpred S3[ set ] means $1 is  strict  strict  strict  strict (Subgroup of R5);
let C6 , C7 being set;
assume L70: (for R1 being set holds (R1 in C6 iff S3[ R1 ]));
assume L71: (for R1 being set holds (R1 in C7 iff S3[ R1 ]));
thus L72: thesis from XBOOLE_0:sch 2(L70 , L71);
end;
end;
registration
let R5 being Group;
cluster ( Subgroups R5 ) -> non  empty;
coherence
proof
set D4 = the  strict (Subgroup of R5);
L74: D4 in ( Subgroups R5 ) by L44;
thus L75: thesis by L74;
end;
end;
theorem
L77: (for B7 being  strict Group holds B7 in ( Subgroups B7 ))
proof
let C8 being  strict Group;
L78: C8 is (Subgroup of C8) by GROUP_2:54;
thus L79: thesis by L78 , L44;
end;
theorem
L80: (for R5 being Group holds (R5 is  finite implies ( Subgroups R5 ) is  finite))
proof
let R5 being Group;
defpred S4[ set , set ] means (ex B8 being  strict (Subgroup of R5) st ($1 = B8 & $2 = (the carrier of B8)));
assume L81: R5 is  finite;
L82: (for R1 being set holds (R1 in ( Subgroups R5 ) implies (ex R2 being set st S4[ R1 , R2 ])))
proof
let R1 being set;
assume L83: R1 in ( Subgroups R5 );
reconsider D5 = R1 as  strict (Subgroup of R5) by L83 , L44;
reconsider D6 = (the carrier of D5) as set;
take D6;
take D5;
thus L84: thesis;
end;
consider C9 being Function such that L85: ( dom C9 ) = ( Subgroups R5 ) and L86: (for R1 being set holds (R1 in ( Subgroups R5 ) implies S4[ R1 , ( C9 . R1 ) ])) from CLASSES1:sch 1(L82);
L87: ( rng C9 ) c= ( bool (the carrier of R5) )
proof
let R1 being set;
assume L88: R1 in ( rng C9 );
consider R2 being set such that L89: (R2 in ( dom C9 ) & ( C9 . R2 ) = R1) by L88 , FUNCT_1:def 3;
consider C10 being  strict (Subgroup of R5) such that L90: R2 = C10 and L91: R1 = (the carrier of C10) by L85 , L86 , L89;
L92: (the carrier of C10) c= (the carrier of R5) by GROUP_2:def 5;
thus L93: thesis by L92 , L91;
end;
L94: C9 is  one-to-one
proof
let R1 being set;
let R2 being set;
assume that
L95: (R1 in ( dom C9 ) & R2 in ( dom C9 ))
and
L96: ( C9 . R1 ) = ( C9 . R2 );
L97: ((ex B9 being  strict (Subgroup of R5) st (R1 = B9 & ( C9 . R1 ) = (the carrier of B9))) & (ex B10 being  strict (Subgroup of R5) st (R2 = B10 & ( C9 . R2 ) = (the carrier of B10)))) by L85 , L86 , L95;
thus L98: thesis by L97 , L96 , GROUP_2:59;
end;
L99: ( card ( Subgroups R5 ) ) c= ( card ( bool (the carrier of R5) ) ) by L94 , L85 , L87 , CARD_1:10;
thus L100: thesis by L99 , L81 , CARD_2:49;
end;
definition
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
func R6 |^ R7 -> (Element of R5) equals 
( ( ( R7 " ) * R6 ) * R7 );
correctness;
end;
theorem
L102: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R10 being (Element of R5) holds (( R6 |^ R10 ) = ( R7 |^ R10 ) implies R6 = R7)))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R10 being (Element of R5);
assume L103: ( R6 |^ R10 ) = ( R7 |^ R10 );
L104: ( ( R10 " ) * R6 ) = ( ( R10 " ) * R7 ) by L103 , GROUP_1:6;
thus L105: thesis by L104 , GROUP_1:6;
end;
theorem
L106: (for R5 being Group holds (for R6 being (Element of R5) holds ( ( 1_ R5 ) |^ R6 ) = ( 1_ R5 )))
proof
let R5 being Group;
let R6 being (Element of R5);
thus L107: ( ( 1_ R5 ) |^ R6 ) = ( ( R6 " ) * R6 ) by GROUP_1:def 4
.= ( 1_ R5 ) by GROUP_1:def 5;
end;
theorem
L108: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (( R6 |^ R7 ) = ( 1_ R5 ) implies R6 = ( 1_ R5 )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
assume L109: ( R6 |^ R7 ) = ( 1_ R5 );
L110: ( R7 " ) = ( ( R7 " ) * R6 ) by L109 , GROUP_1:12;
thus L111: thesis by L110 , GROUP_1:7;
end;
theorem
L112: (for R5 being Group holds (for R6 being (Element of R5) holds ( R6 |^ ( 1_ R5 ) ) = R6))
proof
let R5 being Group;
let R6 being (Element of R5);
thus L113: ( R6 |^ ( 1_ R5 ) ) = ( ( ( 1_ R5 ) " ) * R6 ) by GROUP_1:def 4
.= ( ( 1_ R5 ) * R6 ) by GROUP_1:8
.= R6 by GROUP_1:def 4;
end;
theorem
L114: (for R5 being Group holds (for R6 being (Element of R5) holds ( R6 |^ R6 ) = R6))
proof
let R5 being Group;
let R6 being (Element of R5);
thus L115: ( R6 |^ R6 ) = ( ( 1_ R5 ) * R6 ) by GROUP_1:def 5
.= R6 by GROUP_1:def 4;
end;
theorem
L116: (for R5 being Group holds (for R6 being (Element of R5) holds (( R6 |^ ( R6 " ) ) = R6 & ( ( R6 " ) |^ R6 ) = ( R6 " )))) by L1;
theorem
L117: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (( R6 |^ R7 ) = R6 iff ( R6 * R7 ) = ( R7 * R6 )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L118: (( R6 |^ R7 ) = R6 implies ( R6 * R7 ) = ( R7 * R6 ))
proof
assume L119: ( R6 |^ R7 ) = R6;
L120: R6 = ( ( R7 " ) * ( R6 * R7 ) ) by L119 , GROUP_1:def 3;
thus L121: thesis by L120 , GROUP_1:13;
end;

assume L122: ( R6 * R7 ) = ( R7 * R6 );
L123: R6 = ( ( R7 " ) * ( R6 * R7 ) ) by L122 , GROUP_1:13;
thus L124: thesis by L123 , GROUP_1:def 3;
end;
theorem
L125: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R10 being (Element of R5) holds ( ( R6 * R7 ) |^ R10 ) = ( ( R6 |^ R10 ) * ( R7 |^ R10 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R10 being (Element of R5);
thus L126: ( ( R6 * R7 ) |^ R10 ) = ( ( ( R10 " ) * ( ( R6 * ( 1_ R5 ) ) * R7 ) ) * R10 ) by GROUP_1:def 4
.= ( ( ( R10 " ) * ( ( R6 * ( R10 * ( R10 " ) ) ) * R7 ) ) * R10 ) by GROUP_1:def 5
.= ( ( ( R10 " ) * ( ( ( R6 * R10 ) * ( R10 " ) ) * R7 ) ) * R10 ) by GROUP_1:def 3
.= ( ( ( R10 " ) * ( ( R6 * R10 ) * ( ( R10 " ) * R7 ) ) ) * R10 ) by GROUP_1:def 3
.= ( ( ( ( R10 " ) * ( R6 * R10 ) ) * ( ( R10 " ) * R7 ) ) * R10 ) by GROUP_1:def 3
.= ( ( ( R6 |^ R10 ) * ( ( R10 " ) * R7 ) ) * R10 ) by GROUP_1:def 3
.= ( ( R6 |^ R10 ) * ( R7 |^ R10 ) ) by GROUP_1:def 3;
end;
theorem
L127: (for R5 being Group holds (for R6 being (Element of R5) holds (for R10 being (Element of R5) holds (for R11 being (Element of R5) holds ( ( R6 |^ R10 ) |^ R11 ) = ( R6 |^ ( R10 * R11 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R10 being (Element of R5);
let R11 being (Element of R5);
thus L128: ( ( R6 |^ R10 ) |^ R11 ) = ( ( ( ( R11 " ) * ( ( R10 " ) * R6 ) ) * R10 ) * R11 ) by GROUP_1:def 3
.= ( ( ( ( ( R11 " ) * ( R10 " ) ) * R6 ) * R10 ) * R11 ) by GROUP_1:def 3
.= ( ( ( ( ( R10 * R11 ) " ) * R6 ) * R10 ) * R11 ) by GROUP_1:17
.= ( R6 |^ ( R10 * R11 ) ) by GROUP_1:def 3;
end;
theorem
L129: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (( ( R6 |^ R7 ) |^ ( R7 " ) ) = R6 & ( ( R6 |^ ( R7 " ) ) |^ R7 ) = R6))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L130: ( ( R6 |^ R7 ) |^ ( R7 " ) ) = ( R6 |^ ( R7 * ( R7 " ) ) ) by L127
.= ( R6 |^ ( 1_ R5 ) ) by GROUP_1:def 5
.= R6 by L112;
thus L131: ( ( R6 |^ ( R7 " ) ) |^ R7 ) = ( R6 |^ ( ( R7 " ) * R7 ) ) by L127
.= ( R6 |^ ( 1_ R5 ) ) by GROUP_1:def 5
.= R6 by L112;
end;
theorem
L132: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( ( R6 " ) |^ R7 ) = ( ( R6 |^ R7 ) " ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L133: ( ( R6 " ) |^ R7 ) = ( ( ( R6 * R7 ) " ) * R7 ) by GROUP_1:17
.= ( ( ( R6 * R7 ) " ) * ( ( R7 " ) " ) )
.= ( ( ( R7 " ) * ( R6 * R7 ) ) " ) by GROUP_1:17
.= ( ( R6 |^ R7 ) " ) by GROUP_1:def 3;
end;
L134:
now
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L135: ( ( R6 |^ ( 0 ) ) |^ R7 ) = ( ( 1_ R5 ) |^ R7 ) by GROUP_1:25
.= ( 1_ R5 ) by L106
.= ( ( R6 |^ R7 ) |^ ( 0 ) ) by GROUP_1:25;
end;
L136:
now
let R20 being Nat;
assume L137: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( ( R6 |^ R20 ) |^ R7 ) = ( ( R6 |^ R7 ) |^ R20 ))));
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L138: ( ( R6 |^ ( R20 + 1 ) ) |^ R7 ) = ( ( ( R6 |^ R20 ) * R6 ) |^ R7 ) by GROUP_1:34
.= ( ( ( R6 |^ R20 ) |^ R7 ) * ( R6 |^ R7 ) ) by L125
.= ( ( ( R6 |^ R7 ) |^ R20 ) * ( R6 |^ R7 ) ) by L137
.= ( ( R6 |^ R7 ) |^ ( R20 + 1 ) ) by GROUP_1:34;
end;
L139: (for R20 being Nat holds (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( ( R6 |^ R20 ) |^ R7 ) = ( ( R6 |^ R7 ) |^ R20 )))))
proof
defpred S5[ Nat ] means (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( ( R6 |^ $1 ) |^ R7 ) = ( ( R6 |^ R7 ) |^ $1 ))));
L140: (for B11 being Nat holds (S5[ B11 ] implies S5[ ( B11 + 1 ) ])) by L136;
L141: S5[ ( 0 ) ] by L134;
L142: (for B12 being Nat holds S5[ B12 ]) from NAT_1:sch 2(L141 , L140);
thus L143: thesis by L142;
end;
theorem
L144: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R20 being Nat holds ( ( R6 |^ R20 ) |^ R7 ) = ( ( R6 |^ R7 ) |^ R20 ))))) by L139;
theorem
L145: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R21 being Integer holds ( ( R6 |^ R21 ) |^ R7 ) = ( ( R6 |^ R7 ) |^ R21 )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R21 being Integer;
per cases ;
suppose L146: R21 >= ( 0 );

L147: R21 = ( abs R21 ) by L146 , ABSVALUE:def 1;
thus L148: thesis by L147 , L139;
end;
suppose L149: R21 < ( 0 );

thus L150: ( ( R6 |^ R21 ) |^ R7 ) = ( ( ( R6 |^ ( abs R21 ) ) " ) |^ R7 ) by L149 , GROUP_1:30
.= ( ( ( R6 |^ ( abs R21 ) ) |^ R7 ) " ) by L132
.= ( ( ( R6 |^ R7 ) |^ ( abs R21 ) ) " ) by L139
.= ( ( R6 |^ R7 ) |^ R21 ) by L149 , GROUP_1:30;
end;
end;
theorem
L152: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (R5 is  commutative  commutative  commutative  commutative Group implies ( R6 |^ R7 ) = R6))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
assume L153: R5 is  commutative  commutative  commutative  commutative Group;
thus L154: ( R6 |^ R7 ) = ( ( R6 * ( R7 " ) ) * R7 ) by L153 , L7
.= R6 by L1;
end;
theorem
L155: (for R5 being Group holds ((for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( R6 |^ R7 ) = R6)) implies R5 is  commutative))
proof
let R5 being Group;
assume L156: (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( R6 |^ R7 ) = R6));
let R6 being (Element of R5);
let R7 being (Element of R5);
L157: ( R6 |^ R7 ) = R6 by L156;
thus L158: thesis by L157 , L117;
end;
definition
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
func R12 |^ R13 -> (Subset of R5) equals 
{ ( R10 |^ R11 ) where R10 is (Element of R5) , R11 is (Element of R5) : (R10 in R12 & R11 in R13) };
coherence
proof
set D7 = { ( R10 |^ R11 ) where R10 is (Element of R5) , R11 is (Element of R5) : (R10 in R12 & R11 in R13) };
L159: D7 c= (the carrier of R5)
proof
let R1 being set;
assume L160: R1 in D7;
L161: (ex R10 being (Element of R5) st (ex R11 being (Element of R5) st (R1 = ( R10 |^ R11 ) & R10 in R12 & R11 in R13))) by L160;
thus L162: thesis by L161;
end;
thus L163: thesis by L159;
end;
end;
theorem
L165: (for R1 being set holds (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R1 in ( R12 |^ R13 ) iff (ex R10 being (Element of R5) st (ex R11 being (Element of R5) st (R1 = ( R10 |^ R11 ) & R10 in R12 & R11 in R13))))))));
theorem
L166: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (( R12 |^ R13 ) <> ( {} ) iff (R12 <> ( {} ) & R13 <> ( {} ))))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
set D8 = the (Element of R12);
set D9 = the (Element of R13);
thus L167: (( R12 |^ R13 ) <> ( {} ) implies (R12 <> ( {} ) & R13 <> ( {} )))
proof
set D10 = the (Element of ( R12 |^ R13 ));
assume L168: ( R12 |^ R13 ) <> ( {} );
L169: (ex R6 being (Element of R5) st (ex R7 being (Element of R5) st (D10 = ( R6 |^ R7 ) & R6 in R12 & R7 in R13))) by L168 , L165;
thus L170: thesis by L169;
end;

assume L171: R12 <> ( {} );
assume L172: R13 <> ( {} );
reconsider D11 = D8 , D12 = D9 as (Element of R5) by L172 , L171 , TARSKI:def 3;
L173: ( D11 |^ D12 ) in ( R12 |^ R13 ) by L171 , L172;
thus L174: thesis by L173;
end;
theorem
L175: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds ( R12 |^ R13 ) c= ( ( ( R13 " ) * R12 ) * R13 ))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
let R1 being set;
assume L176: R1 in ( R12 |^ R13 );
consider R6 being (Element of R5), R7 being (Element of R5) such that L177: R1 = ( R6 |^ R7 ) and L178: R6 in R12 and L179: R7 in R13 by L176;
L180: ( R7 " ) in ( R13 " ) by L179;
L181: ( ( R7 " ) * R6 ) in ( ( R13 " ) * R12 ) by L180 , L178;
thus L182: thesis by L181 , L177 , L179;
end;
theorem
L183: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (for R14 being (Subset of R5) holds ( ( R12 * R13 ) |^ R14 ) c= ( ( R12 |^ R14 ) * ( R13 |^ R14 ) )))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
let R14 being (Subset of R5);
let R1 being set;
assume L184: R1 in ( ( R12 * R13 ) |^ R14 );
consider R6 being (Element of R5), R7 being (Element of R5) such that L185: R1 = ( R6 |^ R7 ) and L186: R6 in ( R12 * R13 ) and L187: R7 in R14 by L184;
consider R10 being (Element of R5), R11 being (Element of R5) such that L188: (R6 = ( R10 * R11 ) & R10 in R12) and L189: R11 in R13 by L186;
L190: ( R11 |^ R7 ) in ( R13 |^ R14 ) by L187 , L189;
L191: (R1 = ( ( R10 |^ R7 ) * ( R11 |^ R7 ) ) & ( R10 |^ R7 ) in ( R12 |^ R14 )) by L185 , L187 , L188 , L125;
thus L192: thesis by L191 , L190;
end;
theorem
L193: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (for R14 being (Subset of R5) holds ( ( R12 |^ R13 ) |^ R14 ) = ( R12 |^ ( R13 * R14 ) )))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
let R14 being (Subset of R5);
thus L194: ( ( R12 |^ R13 ) |^ R14 ) c= ( R12 |^ ( R13 * R14 ) )
proof
let R1 being set;
assume L195: R1 in ( ( R12 |^ R13 ) |^ R14 );
consider R6 being (Element of R5), R8 being (Element of R5) such that L196: R1 = ( R6 |^ R8 ) and L197: R6 in ( R12 |^ R13 ) and L198: R8 in R14 by L195;
consider R10 being (Element of R5), R11 being (Element of R5) such that L199: R6 = ( R10 |^ R11 ) and L200: R10 in R12 and L201: R11 in R13 by L197;
L202: (R1 = ( R10 |^ ( R11 * R8 ) ) & ( R11 * R8 ) in ( R13 * R14 )) by L196 , L198 , L199 , L201 , L127;
thus L203: thesis by L202 , L200;
end;

let R1 being set;
assume L204: R1 in ( R12 |^ ( R13 * R14 ) );
consider R6 being (Element of R5), R7 being (Element of R5) such that L205: (R1 = ( R6 |^ R7 ) & R6 in R12) and L206: R7 in ( R13 * R14 ) by L204;
consider R10 being (Element of R5), R11 being (Element of R5) such that L207: (R7 = ( R10 * R11 ) & R10 in R13) and L208: R11 in R14 by L206;
L209: (( R6 |^ R10 ) in ( R12 |^ R13 ) & R1 = ( ( R6 |^ R10 ) |^ R11 )) by L205 , L207 , L127;
thus L210: thesis by L209 , L208;
end;
theorem
L211: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds ( ( R12 " ) |^ R13 ) = ( ( R12 |^ R13 ) " ))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
thus L212: ( ( R12 " ) |^ R13 ) c= ( ( R12 |^ R13 ) " )
proof
let R1 being set;
assume L213: R1 in ( ( R12 " ) |^ R13 );
consider R6 being (Element of R5), R7 being (Element of R5) such that L214: R1 = ( R6 |^ R7 ) and L215: R6 in ( R12 " ) and L216: R7 in R13 by L213;
consider R8 being (Element of R5) such that L217: (R6 = ( R8 " ) & R8 in R12) by L215;
L218: (R1 = ( ( R8 |^ R7 ) " ) & ( R8 |^ R7 ) in ( R12 |^ R13 )) by L214 , L216 , L217 , L132;
thus L219: thesis by L218;
end;

let R1 being set;
assume L220: R1 in ( ( R12 |^ R13 ) " );
consider R6 being (Element of R5) such that L221: R1 = ( R6 " ) and L222: R6 in ( R12 |^ R13 ) by L220;
consider R7 being (Element of R5), R8 being (Element of R5) such that L223: R6 = ( R7 |^ R8 ) and L224: R7 in R12 and L225: R8 in R13 by L222;
L226: ( R7 " ) in ( R12 " ) by L224;
L227: R1 = ( ( R7 " ) |^ R8 ) by L221 , L223 , L132;
thus L228: thesis by L227 , L225 , L226;
end;
theorem
L229: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ( { R6 } |^ { R7 } ) = { ( R6 |^ R7 ) })))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
L230: ( ( ( { R7 } " ) * { R6 } ) * { R7 } ) = ( ( { ( R7 " ) } * { R6 } ) * { R7 } ) by GROUP_2:3
.= ( { ( ( R7 " ) * R6 ) } * { R7 } ) by GROUP_2:18
.= { ( R6 |^ R7 ) } by GROUP_2:18;
L231: (( { R6 } |^ { R7 } ) c= ( ( ( { R7 } " ) * { R6 } ) * { R7 } ) & ( { R6 } |^ { R7 } ) <> ( {} )) by L166 , L175;
thus L232: thesis by L231 , L230 , ZFMISC_1:33;
end;
theorem
L233: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R8 being (Element of R5) holds ( { R6 } |^ { R7 , R8 } ) = { ( R6 |^ R7 ) , ( R6 |^ R8 ) }))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R8 being (Element of R5);
thus L234: ( { R6 } |^ { R7 , R8 } ) c= { ( R6 |^ R7 ) , ( R6 |^ R8 ) }
proof
let R1 being set;
assume L235: R1 in ( { R6 } |^ { R7 , R8 } );
consider R10 being (Element of R5), R11 being (Element of R5) such that L236: R1 = ( R10 |^ R11 ) and L237: R10 in { R6 } and L238: R11 in { R7 , R8 } by L235;
L239: (R11 = R7 or R11 = R8) by L238 , TARSKI:def 2;
L240: R10 = R6 by L237 , TARSKI:def 1;
thus L241: thesis by L240 , L236 , L239 , TARSKI:def 2;
end;

let R1 being set;
L242: R8 in { R7 , R8 } by TARSKI:def 2;
assume L243: R1 in { ( R6 |^ R7 ) , ( R6 |^ R8 ) };
L244: (R1 = ( R6 |^ R7 ) or R1 = ( R6 |^ R8 )) by L243 , TARSKI:def 2;
L245: (R6 in { R6 } & R7 in { R7 , R8 }) by TARSKI:def 1 , TARSKI:def 2;
thus L246: thesis by L245 , L244 , L242;
end;
theorem
L247: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R8 being (Element of R5) holds ( { R6 , R7 } |^ { R8 } ) = { ( R6 |^ R8 ) , ( R7 |^ R8 ) }))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R8 being (Element of R5);
thus L248: ( { R6 , R7 } |^ { R8 } ) c= { ( R6 |^ R8 ) , ( R7 |^ R8 ) }
proof
let R1 being set;
assume L249: R1 in ( { R6 , R7 } |^ { R8 } );
consider R10 being (Element of R5), R11 being (Element of R5) such that L250: R1 = ( R10 |^ R11 ) and L251: R10 in { R6 , R7 } and L252: R11 in { R8 } by L249;
L253: (R10 = R7 or R10 = R6) by L251 , TARSKI:def 2;
L254: R11 = R8 by L252 , TARSKI:def 1;
thus L255: thesis by L254 , L250 , L253 , TARSKI:def 2;
end;

let R1 being set;
L256: R8 in { R8 } by TARSKI:def 1;
assume L257: R1 in { ( R6 |^ R8 ) , ( R7 |^ R8 ) };
L258: (R1 = ( R6 |^ R8 ) or R1 = ( R7 |^ R8 )) by L257 , TARSKI:def 2;
L259: (R6 in { R6 , R7 } & R7 in { R6 , R7 }) by TARSKI:def 2;
thus L260: thesis by L259 , L258 , L256;
end;
theorem
L261: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R8 being (Element of R5) holds (for R9 being (Element of R5) holds ( { R6 , R7 } |^ { R8 , R9 } ) = { ( R6 |^ R8 ) , ( R6 |^ R9 ) , ( R7 |^ R8 ) , ( R7 |^ R9 ) })))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R8 being (Element of R5);
let R9 being (Element of R5);
thus L262: ( { R6 , R7 } |^ { R8 , R9 } ) c= { ( R6 |^ R8 ) , ( R6 |^ R9 ) , ( R7 |^ R8 ) , ( R7 |^ R9 ) }
proof
let R1 being set;
assume L263: R1 in ( { R6 , R7 } |^ { R8 , R9 } );
consider R10 being (Element of R5), R11 being (Element of R5) such that L264: R1 = ( R10 |^ R11 ) and L265: R10 in { R6 , R7 } and L266: R11 in { R8 , R9 } by L263;
L267: (R11 = R8 or R11 = R9) by L266 , TARSKI:def 2;
L268: (R10 = R6 or R10 = R7) by L265 , TARSKI:def 2;
thus L269: thesis by L268 , L264 , L267 , ENUMSET1:def 2;
end;

let R1 being set;
L270: (R8 in { R8 , R9 } & R9 in { R8 , R9 }) by TARSKI:def 2;
assume L271: R1 in { ( R6 |^ R8 ) , ( R6 |^ R9 ) , ( R7 |^ R8 ) , ( R7 |^ R9 ) };
L272: (R1 = ( R6 |^ R8 ) or R1 = ( R6 |^ R9 ) or R1 = ( R7 |^ R8 ) or R1 = ( R7 |^ R9 )) by L271 , ENUMSET1:def 2;
L273: (R6 in { R6 , R7 } & R7 in { R6 , R7 }) by TARSKI:def 2;
thus L274: thesis by L273 , L272 , L270;
end;
definition
let R5 being Group;
let R12 being (Subset of R5);
let R10 being (Element of R5);
func R12 |^ R10 -> (Subset of R5) equals 
( R12 |^ { R10 } );
correctness;
func R10 |^ R12 -> (Subset of R5) equals 
( { R10 } |^ R12 );
correctness;
end;
theorem
L276: (for R1 being set holds (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds (R1 in ( R12 |^ R10 ) iff (ex R11 being (Element of R5) st (R1 = ( R11 |^ R10 ) & R11 in R12)))))))
proof
let R1 being set;
let R5 being Group;
let R10 being (Element of R5);
let R12 being (Subset of R5);
thus L277: (R1 in ( R12 |^ R10 ) implies (ex R11 being (Element of R5) st (R1 = ( R11 |^ R10 ) & R11 in R12)))
proof
assume L278: R1 in ( R12 |^ R10 );
consider R6 being (Element of R5), R7 being (Element of R5) such that L279: (R1 = ( R6 |^ R7 ) & R6 in R12) and L280: R7 in { R10 } by L278;
L281: R7 = R10 by L280 , TARSKI:def 1;
thus L282: thesis by L281 , L279;
end;

given R11 being (Element of R5) such that
L283: (R1 = ( R11 |^ R10 ) & R11 in R12);

L284: R10 in { R10 } by TARSKI:def 1;
thus L285: thesis by L284 , L283;
end;
theorem
L286: (for R1 being set holds (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds (R1 in ( R10 |^ R12 ) iff (ex R11 being (Element of R5) st (R1 = ( R10 |^ R11 ) & R11 in R12)))))))
proof
let R1 being set;
let R5 being Group;
let R10 being (Element of R5);
let R12 being (Subset of R5);
thus L287: (R1 in ( R10 |^ R12 ) implies (ex R11 being (Element of R5) st (R1 = ( R10 |^ R11 ) & R11 in R12)))
proof
assume L288: R1 in ( R10 |^ R12 );
consider R6 being (Element of R5), R7 being (Element of R5) such that L289: R1 = ( R6 |^ R7 ) and L290: R6 in { R10 } and L291: R7 in R12 by L288;
L292: R6 = R10 by L290 , TARSKI:def 1;
thus L293: thesis by L292 , L289 , L291;
end;

given R11 being (Element of R5) such that
L294: (R1 = ( R10 |^ R11 ) & R11 in R12);

L295: R10 in { R10 } by TARSKI:def 1;
thus L296: thesis by L295 , L294;
end;
theorem
L297: (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds ( R10 |^ R12 ) c= ( ( ( R12 " ) * R10 ) * R12 ))))
proof
let R5 being Group;
let R10 being (Element of R5);
let R12 being (Subset of R5);
let R1 being set;
assume L298: R1 in ( R10 |^ R12 );
consider R6 being (Element of R5) such that L299: R1 = ( R10 |^ R6 ) and L300: R6 in R12 by L298 , L286;
L301: ( R6 " ) in ( R12 " ) by L300;
L302: ( ( R6 " ) * R10 ) in ( ( R12 " ) * R10 ) by L301 , GROUP_2:28;
thus L303: thesis by L302 , L299 , L300;
end;
theorem
L304: (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds ( ( R12 |^ R13 ) |^ R10 ) = ( R12 |^ ( R13 * R10 ) ))))) by L193;
theorem
L305: (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds ( ( R12 |^ R10 ) |^ R13 ) = ( R12 |^ ( R10 * R13 ) ))))) by L193;
theorem
L306: (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds ( ( R10 |^ R12 ) |^ R13 ) = ( R10 |^ ( R12 * R13 ) ))))) by L193;
theorem
L307: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R12 being (Subset of R5) holds ( ( R12 |^ R6 ) |^ R7 ) = ( R12 |^ ( R6 * R7 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R12 being (Subset of R5);
thus L308: ( ( R12 |^ R6 ) |^ R7 ) = ( R12 |^ ( R6 * { R7 } ) ) by L193
.= ( R12 |^ ( R6 * R7 ) ) by GROUP_2:18;
end;
theorem
L309: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R12 being (Subset of R5) holds ( ( R6 |^ R12 ) |^ R7 ) = ( R6 |^ ( R12 * R7 ) ))))) by L193;
theorem
L310: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R12 being (Subset of R5) holds ( ( R6 |^ R7 ) |^ R12 ) = ( R6 |^ ( R7 * R12 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R12 being (Subset of R5);
thus L311: ( ( R6 |^ R7 ) |^ R12 ) = ( ( { R6 } |^ { R7 } ) |^ R12 ) by L229
.= ( R6 |^ ( R7 * R12 ) ) by L193;
end;
theorem
L312: (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds ( R12 |^ R10 ) = ( ( ( R10 " ) * R12 ) * R10 ))))
proof
let R5 being Group;
let R10 being (Element of R5);
let R12 being (Subset of R5);
L313: ( R12 |^ R10 ) c= ( ( ( { R10 } " ) * R12 ) * { R10 } ) by L175;
thus L314: ( R12 |^ R10 ) c= ( ( ( R10 " ) * R12 ) * R10 ) by L313 , GROUP_2:3;
let R1 being set;
assume L315: R1 in ( ( ( R10 " ) * R12 ) * R10 );
consider R6 being (Element of R5) such that L316: R1 = ( R6 * R10 ) and L317: R6 in ( ( R10 " ) * R12 ) by L315 , GROUP_2:28;
consider R7 being (Element of R5) such that L318: R6 = ( ( R10 " ) * R7 ) and L319: R7 in R12 by L317 , GROUP_2:27;
L320: R1 = ( R7 |^ R10 ) by L316 , L318;
thus L321: thesis by L320 , L319 , L276;
end;
theorem
L322: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds ( ( R12 * R13 ) |^ R6 ) c= ( ( R12 |^ R6 ) * ( R13 |^ R6 ) ))))) by L183;
theorem
L323: (for R5 being Group holds (for R12 being (Subset of R5) holds ( R12 |^ ( 1_ R5 ) ) = R12))
proof
let R5 being Group;
let R12 being (Subset of R5);
thus L324: ( R12 |^ ( 1_ R5 ) ) = ( ( ( ( 1_ R5 ) " ) * R12 ) * ( 1_ R5 ) ) by L312
.= ( ( ( 1_ R5 ) " ) * R12 ) by GROUP_2:37
.= ( ( 1_ R5 ) * R12 ) by GROUP_1:8
.= R12 by GROUP_2:37;
end;
theorem
L325: (for R5 being Group holds (for R12 being (Subset of R5) holds (R12 <> ( {} ) implies ( ( 1_ R5 ) |^ R12 ) = { ( 1_ R5 ) })))
proof
let R5 being Group;
let R12 being (Subset of R5);
set D13 = the (Element of R12);
assume L326: R12 <> ( {} );
reconsider D14 = D13 as (Element of R5) by L326 , TARSKI:def 3;
thus L327: ( ( 1_ R5 ) |^ R12 ) c= { ( 1_ R5 ) }
proof
let R1 being set;
assume L328: R1 in ( ( 1_ R5 ) |^ R12 );
L329: (ex R6 being (Element of R5) st (R1 = ( ( 1_ R5 ) |^ R6 ) & R6 in R12)) by L328 , L286;
L330: R1 = ( 1_ R5 ) by L329 , L106;
thus L331: thesis by L330 , TARSKI:def 1;
end;

let R1 being set;
assume L332: R1 in { ( 1_ R5 ) };
L333: R1 = ( 1_ R5 ) by L332 , TARSKI:def 1;
L334: ( ( 1_ R5 ) |^ D14 ) = R1 by L333 , L106;
thus L335: thesis by L334 , L326 , L286;
end;
theorem
L336: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds (( ( R12 |^ R6 ) |^ ( R6 " ) ) = R12 & ( ( R12 |^ ( R6 " ) ) |^ R6 ) = R12))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R12 being (Subset of R5);
thus L337: ( ( R12 |^ R6 ) |^ ( R6 " ) ) = ( R12 |^ ( R6 * ( R6 " ) ) ) by L307
.= ( R12 |^ ( 1_ R5 ) ) by GROUP_1:def 5
.= R12 by L323;
thus L338: ( ( R12 |^ ( R6 " ) ) |^ R6 ) = ( R12 |^ ( ( R6 " ) * R6 ) ) by L307
.= ( R12 |^ ( 1_ R5 ) ) by GROUP_1:def 5
.= R12 by L323;
end;
theorem
L339: (for R5 being Group holds (R5 is  commutative  commutative  commutative  commutative Group iff (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R13 <> ( {} ) implies ( R12 |^ R13 ) = R12)))))
proof
let R5 being Group;
thus L340: (R5 is  commutative  commutative  commutative  commutative Group implies (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R13 <> ( {} ) implies ( R12 |^ R13 ) = R12))))
proof
assume L341: R5 is  commutative  commutative  commutative  commutative Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
set D15 = the (Element of R13);
assume L342: R13 <> ( {} );
reconsider D16 = D15 as (Element of R5) by L342 , TARSKI:def 3;
thus L343: ( R12 |^ R13 ) c= R12
proof
let R1 being set;
assume L344: R1 in ( R12 |^ R13 );
L345: (ex R6 being (Element of R5) st (ex R7 being (Element of R5) st (R1 = ( R6 |^ R7 ) & R6 in R12 & R7 in R13))) by L344;
thus L346: thesis by L345 , L341 , L152;
end;

let R1 being set;
assume L347: R1 in R12;
reconsider D17 = R1 as (Element of R5) by L347;
L348: ( D17 |^ D16 ) = R1 by L341 , L152;
thus L349: thesis by L348 , L342 , L347;
end;

assume L350: (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R13 <> ( {} ) implies ( R12 |^ R13 ) = R12)));
L351:
now
let R6 being (Element of R5);
let R7 being (Element of R5);
L352: { R6 } = ( { R6 } |^ { R7 } ) by L350
.= { ( R6 |^ R7 ) } by L229;
thus L353: R6 = ( R6 |^ R7 ) by L352 , ZFMISC_1:3;
end;
thus L354: thesis by L351 , L155;
end;
theorem
L355: (for R5 being Group holds (R5 is  commutative  commutative  commutative  commutative Group iff (for R12 being (Subset of R5) holds (for R10 being (Element of R5) holds ( R12 |^ R10 ) = R12))))
proof
let R5 being Group;
thus L356: (R5 is  commutative  commutative  commutative  commutative Group implies (for R12 being (Subset of R5) holds (for R10 being (Element of R5) holds ( R12 |^ R10 ) = R12))) by L339;
assume L357: (for R12 being (Subset of R5) holds (for R10 being (Element of R5) holds ( R12 |^ R10 ) = R12));
L358:
now
let R6 being (Element of R5);
let R7 being (Element of R5);
L359: { R6 } = ( { R6 } |^ R7 ) by L357
.= { ( R6 |^ R7 ) } by L229;
thus L360: R6 = ( R6 |^ R7 ) by L359 , ZFMISC_1:3;
end;
thus L361: thesis by L358 , L155;
end;
theorem
L362: (for R5 being Group holds (R5 is  commutative  commutative  commutative  commutative Group iff (for R12 being (Subset of R5) holds (for R10 being (Element of R5) holds (R12 <> ( {} ) implies ( R10 |^ R12 ) = { R10 })))))
proof
let R5 being Group;
thus L363: (R5 is  commutative  commutative  commutative  commutative Group implies (for R12 being (Subset of R5) holds (for R10 being (Element of R5) holds (R12 <> ( {} ) implies ( R10 |^ R12 ) = { R10 })))) by L339;
assume L364: (for R12 being (Subset of R5) holds (for R10 being (Element of R5) holds (R12 <> ( {} ) implies ( R10 |^ R12 ) = { R10 })));
L365:
now
let R6 being (Element of R5);
let R7 being (Element of R5);
L366: { R6 } = ( R6 |^ { R7 } ) by L364
.= { ( R6 |^ R7 ) } by L229;
thus L367: R6 = ( R6 |^ R7 ) by L366 , ZFMISC_1:3;
end;
thus L368: thesis by L365 , L155;
end;
definition
let R5 being Group;
let R16 being (Subgroup of R5);
let R6 being (Element of R5);
func R16 |^ R6 ->  strict (Subgroup of R5) means 
:L369: (the carrier of it) = ( ( carr R16 ) |^ R6 );
existence
proof
consider C11 being  strict (Subgroup of R5) such that L370: (the carrier of C11) = ( ( ( R6 " ) * R16 ) * ( ( R6 " ) " ) ) by GROUP_2:127;
L371: (the carrier of C11) = ( ( ( R6 " ) * ( carr R16 ) ) * R6 ) by L370
.= ( ( carr R16 ) |^ R6 ) by L312;
thus L372: thesis by L371;
end;
correctness by GROUP_2:59;
end;
theorem
L374: (for R1 being set holds (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds (R1 in ( R16 |^ R6 ) iff (ex R10 being (Element of R5) st (R1 = ( R10 |^ R6 ) & R10 in R16)))))))
proof
let R1 being set;
let R5 being Group;
let R6 being (Element of R5);
let R16 being (Subgroup of R5);
thus L375: (R1 in ( R16 |^ R6 ) implies (ex R10 being (Element of R5) st (R1 = ( R10 |^ R6 ) & R10 in R16)))
proof
assume L376: R1 in ( R16 |^ R6 );
L377: R1 in (the carrier of ( R16 |^ R6 )) by L376 , STRUCT_0:def 5;
L378: R1 in ( ( carr R16 ) |^ R6 ) by L377 , L369;
consider R7 being (Element of R5) such that L379: (R1 = ( R7 |^ R6 ) & R7 in ( carr R16 )) by L378 , L276;
take R7;
thus L380: thesis by L379 , STRUCT_0:def 5;
end;

given R10 being (Element of R5) such that
L381: R1 = ( R10 |^ R6 )
and
L382: R10 in R16;

L383: R10 in ( carr R16 ) by L382 , STRUCT_0:def 5;
L384: R1 in ( ( carr R16 ) |^ R6 ) by L383 , L381 , L276;
L385: R1 in (the carrier of ( R16 |^ R6 )) by L384 , L369;
thus L386: thesis by L385 , STRUCT_0:def 5;
end;
theorem
L387: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds (the carrier of ( R16 |^ R6 )) = ( ( ( R6 " ) * R16 ) * R6 ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R16 being (Subgroup of R5);
thus L388: (the carrier of ( R16 |^ R6 )) = ( ( carr R16 ) |^ R6 ) by L369
.= ( ( ( R6 " ) * R16 ) * R6 ) by L312;
end;
theorem
L389: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R16 being (Subgroup of R5) holds ( ( R16 |^ R6 ) |^ R7 ) = ( R16 |^ ( R6 * R7 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R16 being (Subgroup of R5);
L390: (the carrier of ( ( R16 |^ R6 ) |^ R7 )) = ( ( carr ( R16 |^ R6 ) ) |^ R7 ) by L369
.= ( ( ( carr R16 ) |^ R6 ) |^ R7 ) by L369
.= ( ( carr R16 ) |^ ( R6 * R7 ) ) by L307
.= (the carrier of ( R16 |^ ( R6 * R7 ) )) by L369;
thus L391: thesis by L390 , GROUP_2:59;
end;
theorem
L392: (for R5 being Group holds (for B13 being  strict (Subgroup of R5) holds ( B13 |^ ( 1_ R5 ) ) = B13))
proof
let R5 being Group;
let C12 being  strict (Subgroup of R5);
L393: (the carrier of ( C12 |^ ( 1_ R5 ) )) = ( ( carr C12 ) |^ ( 1_ R5 ) ) by L369
.= (the carrier of C12) by L323;
thus L394: thesis by L393 , GROUP_2:59;
end;
theorem
L395: (for R5 being Group holds (for R6 being (Element of R5) holds (for B14 being  strict (Subgroup of R5) holds (( ( B14 |^ R6 ) |^ ( R6 " ) ) = B14 & ( ( B14 |^ ( R6 " ) ) |^ R6 ) = B14))))
proof
let R5 being Group;
let R6 being (Element of R5);
let C13 being  strict (Subgroup of R5);
thus L396: ( ( C13 |^ R6 ) |^ ( R6 " ) ) = ( C13 |^ ( R6 * ( R6 " ) ) ) by L389
.= ( C13 |^ ( 1_ R5 ) ) by GROUP_1:def 5
.= C13 by L392;
thus L397: ( ( C13 |^ ( R6 " ) ) |^ R6 ) = ( C13 |^ ( ( R6 " ) * R6 ) ) by L389
.= ( C13 |^ ( 1_ R5 ) ) by GROUP_1:def 5
.= C13 by L392;
end;
theorem
L398: (for R5 being Group holds (for R6 being (Element of R5) holds (for R17 being (Subgroup of R5) holds (for R18 being (Subgroup of R5) holds ( ( R17 /\ R18 ) |^ R6 ) = ( ( R17 |^ R6 ) /\ ( R18 |^ R6 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R17 being (Subgroup of R5);
let R18 being (Subgroup of R5);
let R10 being (Element of R5);
thus L399: (R10 in ( ( R17 /\ R18 ) |^ R6 ) implies R10 in ( ( R17 |^ R6 ) /\ ( R18 |^ R6 ) ))
proof
assume L400: R10 in ( ( R17 /\ R18 ) |^ R6 );
consider R11 being (Element of R5) such that L401: R10 = ( R11 |^ R6 ) and L402: R11 in ( R17 /\ R18 ) by L400 , L374;
L403: R11 in R18 by L402 , GROUP_2:82;
L404: R10 in ( R18 |^ R6 ) by L403 , L401 , L374;
L405: R11 in R17 by L402 , GROUP_2:82;
L406: R10 in ( R17 |^ R6 ) by L405 , L401 , L374;
thus L407: thesis by L406 , L404 , GROUP_2:82;
end;

assume L408: R10 in ( ( R17 |^ R6 ) /\ ( R18 |^ R6 ) );
L409: R10 in ( R17 |^ R6 ) by L408 , GROUP_2:82;
consider R7 being (Element of R5) such that L410: R10 = ( R7 |^ R6 ) and L411: R7 in R17 by L409 , L374;
L412: R10 in ( R18 |^ R6 ) by L408 , GROUP_2:82;
consider R8 being (Element of R5) such that L413: R10 = ( R8 |^ R6 ) and L414: R8 in R18 by L412 , L374;
L415: R7 = R8 by L410 , L413 , L102;
L416: R7 in ( R17 /\ R18 ) by L415 , L411 , L414 , GROUP_2:82;
thus L417: thesis by L416 , L410 , L374;
end;
theorem
L418: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds ( card R16 ) = ( card ( R16 |^ R6 ) ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R16 being (Subgroup of R5);
deffunc H1((Element of R5)) = ( $1 |^ R6 );
consider C14 being (Function of (the carrier of R5) , (the carrier of R5)) such that L419: (for R10 being (Element of R5) holds ( C14 . R10 ) = H1(R10)) from FUNCT_2:sch 4;
set D18 = ( C14 | (the carrier of R16) );
L420: (( dom C14 ) = (the carrier of R5) & (the carrier of R16) c= (the carrier of R5)) by FUNCT_2:def 1 , GROUP_2:def 5;
L421: ( dom D18 ) = (the carrier of R16) by L420 , RELAT_1:62;
L422: ( rng D18 ) = (the carrier of ( R16 |^ R6 ))
proof
thus L423: ( rng D18 ) c= (the carrier of ( R16 |^ R6 ))
proof
let R1 being set;
assume L424: R1 in ( rng D18 );
consider R2 being set such that L425: R2 in ( dom D18 ) and L426: ( D18 . R2 ) = R1 by L424 , FUNCT_1:def 3;
reconsider D19 = R2 as (Element of R16) by L420 , L425 , RELAT_1:62;
reconsider D20 = D19 as (Element of R5) by GROUP_2:42;
L427: ( C14 . D20 ) = ( D18 . D20 ) by L425 , FUNCT_1:47;
L428: ( C14 . D20 ) = ( D20 |^ R6 ) by L419;
L429: R1 in ( ( carr R16 ) |^ R6 ) by L428 , L426 , L427 , L276;
thus L430: thesis by L429 , L369;
end;

let R1 being set;
assume L431: R1 in (the carrier of ( R16 |^ R6 ));
L432: R1 in ( ( carr R16 ) |^ R6 ) by L431 , L369;
consider R7 being (Element of R5) such that L433: R1 = ( R7 |^ R6 ) and L434: R7 in ( carr R16 ) by L432 , L276;
L435: ( C14 . R7 ) = ( R7 |^ R6 ) by L419;
L436: ( D18 . R7 ) = ( C14 . R7 ) by L421 , L434 , FUNCT_1:47;
thus L437: thesis by L436 , L421 , L433 , L434 , L435 , FUNCT_1:def 3;
end;
L438: D18 is  one-to-one
proof
let R1 being set;
let R2 being set;
assume that
L439: R1 in ( dom D18 )
and
L440: R2 in ( dom D18 )
and
L441: ( D18 . R1 ) = ( D18 . R2 );
reconsider D21 = R1 , D22 = R2 as (Element of R16) by L420 , L439 , L440 , RELAT_1:62;
reconsider D23 = D21 , D24 = D22 as (Element of R5) by GROUP_2:42;
L442: (( C14 . R1 ) = ( D23 |^ R6 ) & ( C14 . R2 ) = ( D24 |^ R6 )) by L419;
L443: ( C14 . R1 ) = ( D18 . R1 ) by L439 , FUNCT_1:47;
thus L444: thesis by L443 , L440 , L441 , L442 , L102 , FUNCT_1:47;
end;
L445: (the carrier of R16) , (the carrier of ( R16 |^ R6 )) are_equipotent  by L438 , L421 , L422 , WELLORD2:def 4;
thus L446: thesis by L445 , CARD_1:5;
end;
theorem
L447: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds (R16 is  finite iff ( R16 |^ R6 ) is  finite))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R16 being (Subgroup of R5);
L448: ( card R16 ) = ( card ( R16 |^ R6 ) ) by L418;
L449: (the carrier of R16) , (the carrier of ( R16 |^ R6 )) are_equipotent  by L448 , CARD_1:5;
thus L450: thesis by L449 , CARD_1:38;
end;
registration
let R5 being Group;
let R6 being (Element of R5);
let C15 being  finite (Subgroup of R5);
cluster ( C15 |^ R6 ) ->  finite;
coherence by L447;
end;
theorem
L452: (for R5 being Group holds (for R6 being (Element of R5) holds (for B15 being  finite (Subgroup of R5) holds ( card B15 ) = ( card ( B15 |^ R6 ) )))) by L418;
theorem
L453: (for R5 being Group holds (for R6 being (Element of R5) holds ( ( (1). R5 ) |^ R6 ) = ( (1). R5 )))
proof
let R5 being Group;
let R6 being (Element of R5);
L454: (the carrier of ( (1). R5 )) = { ( 1_ R5 ) } by GROUP_2:def 7;
L455: (the carrier of ( ( (1). R5 ) |^ R6 )) = ( ( carr ( (1). R5 ) ) |^ R6 ) by L369
.= { ( ( 1_ R5 ) |^ R6 ) } by L454 , L229
.= { ( 1_ R5 ) } by L106;
thus L456: thesis by L455 , GROUP_2:def 7;
end;
theorem
L457: (for R5 being Group holds (for R6 being (Element of R5) holds (for B16 being  strict (Subgroup of R5) holds (( B16 |^ R6 ) = ( (1). R5 ) implies B16 = ( (1). R5 )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let C16 being  strict (Subgroup of R5);
assume L458: ( C16 |^ R6 ) = ( (1). R5 );
reconsider D25 = C16 as  finite (Subgroup of R5) by L458 , L447;
L459: ( card ( (1). R5 ) ) = 1 by GROUP_2:69;
L460: ( card D25 ) = 1 by L459 , L458 , L418;
thus L461: thesis by L460 , GROUP_2:70;
end;
theorem
L462: (for B17 being Group holds (for B18 being (Element of B17) holds ( ( (Omega). B17 ) |^ B18 ) = ( (Omega). B17 )))
proof
let C17 being Group;
let C18 being (Element of C17);
let C19 being (Element of C17);
L463: ( ( C19 |^ ( C18 " ) ) |^ C18 ) = ( C19 |^ ( ( C18 " ) * C18 ) ) by L127
.= ( C19 |^ ( 1_ C17 ) ) by GROUP_1:def 5
.= C19 by L112;
thus L464: thesis by L463 , L374 , STRUCT_0:def 5;
end;
theorem
L465: (for R5 being Group holds (for R6 being (Element of R5) holds (for B19 being  strict (Subgroup of R5) holds (( B19 |^ R6 ) = R5 implies B19 = R5))))
proof
let R5 being Group;
let R6 being (Element of R5);
let C20 being  strict (Subgroup of R5);
assume L466: ( C20 |^ R6 ) = R5;
L467:
now
let R10 being (Element of R5);
assume L468: (not R10 in C20);
L469:
now
assume L470: ( R10 |^ R6 ) in ( C20 |^ R6 );
L471: (ex R11 being (Element of R5) st (( R10 |^ R6 ) = ( R11 |^ R6 ) & R11 in C20)) by L470 , L374;
thus L472: contradiction by L471 , L468 , L102;
end;
thus L473: contradiction by L469 , L466 , STRUCT_0:def 5;
end;
thus L474: thesis by L467 , L466 , GROUP_2:62;
end;
theorem
L475: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds ( Index R16 ) = ( Index ( R16 |^ R6 ) ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R16 being (Subgroup of R5);
defpred S6[ set , set ] means (ex R7 being (Element of R5) st ($1 = ( R7 * R16 ) & $2 = ( ( R7 |^ R6 ) * ( R16 |^ R6 ) )));
L476: (for R1 being set holds (R1 in ( Left_Cosets R16 ) implies (ex R2 being set st S6[ R1 , R2 ])))
proof
let R1 being set;
assume L477: R1 in ( Left_Cosets R16 );
consider R7 being (Element of R5) such that L478: R1 = ( R7 * R16 ) by L477 , GROUP_2:def 15;
reconsider D26 = ( ( R7 |^ R6 ) * ( R16 |^ R6 ) ) as set;
take D26;
take R7;
thus L479: thesis by L478;
end;
consider C21 being Function such that L480: ( dom C21 ) = ( Left_Cosets R16 ) and L481: (for R1 being set holds (R1 in ( Left_Cosets R16 ) implies S6[ R1 , ( C21 . R1 ) ])) from CLASSES1:sch 1(L476);
L482: (for R1 being set holds (for R3 being set holds (for R4 being set holds ((R1 in ( Left_Cosets R16 ) & S6[ R1 , R3 ] & S6[ R1 , R4 ]) implies R3 = R4))))
proof
set D27 = ( carr R16 );
let R1 being set;
let R3 being set;
let R4 being set;
assume L483: R1 in ( Left_Cosets R16 );
given R7 being (Element of R5) such that
L484: R1 = ( R7 * R16 )
and
L485: R3 = ( ( R7 |^ R6 ) * ( R16 |^ R6 ) );

given R8 being (Element of R5) such that
L486: R1 = ( R8 * R16 )
and
L487: R4 = ( ( R8 |^ R6 ) * ( R16 |^ R6 ) );

thus L488: R3 = ( ( ( ( R6 " ) * R7 ) * R6 ) * ( ( ( R6 " ) * R16 ) * R6 ) ) by L485 , L387
.= ( ( ( ( ( R6 " ) * R7 ) * R6 ) * ( ( R6 " ) * D27 ) ) * R6 ) by GROUP_2:33
.= ( ( ( ( R6 " ) * R7 ) * ( R6 * ( ( R6 " ) * D27 ) ) ) * R6 ) by GROUP_2:32
.= ( ( ( ( R6 " ) * R7 ) * ( ( R6 * ( R6 " ) ) * D27 ) ) * R6 ) by GROUP_2:32
.= ( ( ( ( R6 " ) * R7 ) * ( ( 1_ R5 ) * D27 ) ) * R6 ) by GROUP_1:def 5
.= ( ( ( ( R6 " ) * R7 ) * D27 ) * R6 ) by GROUP_2:37
.= ( ( ( R6 " ) * ( R8 * R16 ) ) * R6 ) by L484 , L486 , GROUP_2:32
.= ( ( ( ( R6 " ) * R8 ) * D27 ) * R6 ) by GROUP_2:32
.= ( ( ( ( R6 " ) * R8 ) * ( ( 1_ R5 ) * D27 ) ) * R6 ) by GROUP_2:37
.= ( ( ( ( R6 " ) * R8 ) * ( ( R6 * ( R6 " ) ) * D27 ) ) * R6 ) by GROUP_1:def 5
.= ( ( ( ( R6 " ) * R8 ) * ( R6 * ( ( R6 " ) * D27 ) ) ) * R6 ) by GROUP_2:32
.= ( ( ( ( ( R6 " ) * R8 ) * R6 ) * ( ( R6 " ) * D27 ) ) * R6 ) by GROUP_2:32
.= ( ( ( ( R6 " ) * R8 ) * R6 ) * ( ( ( R6 " ) * R16 ) * R6 ) ) by GROUP_2:33
.= R4 by L487 , L387;
end;
L489: ( rng C21 ) = ( Left_Cosets ( R16 |^ R6 ) )
proof
thus L490: ( rng C21 ) c= ( Left_Cosets ( R16 |^ R6 ) )
proof
let R1 being set;
assume L491: R1 in ( rng C21 );
consider R2 being set such that L492: (R2 in ( dom C21 ) & ( C21 . R2 ) = R1) by L491 , FUNCT_1:def 3;
L493: (ex R7 being (Element of R5) st (R2 = ( R7 * R16 ) & R1 = ( ( R7 |^ R6 ) * ( R16 |^ R6 ) ))) by L480 , L481 , L492;
thus L494: thesis by L493 , GROUP_2:def 15;
end;

let R1 being set;
assume L495: R1 in ( Left_Cosets ( R16 |^ R6 ) );
consider R7 being (Element of R5) such that L496: R1 = ( R7 * ( R16 |^ R6 ) ) by L495 , GROUP_2:def 15;
set D28 = ( R7 |^ ( R6 " ) );
L497: R1 = ( ( D28 |^ R6 ) * ( R16 |^ R6 ) ) by L496 , L129;
L498: ( D28 * R16 ) in ( Left_Cosets R16 ) by GROUP_2:def 15;
consider R9 being (Element of R5) such that L499: ( D28 * R16 ) = ( R9 * R16 ) and L500: ( C21 . ( D28 * R16 ) ) = ( ( R9 |^ R6 ) * ( R16 |^ R6 ) ) by L498 , L481;
L501: ( ( D28 |^ R6 ) * ( R16 |^ R6 ) ) = ( ( R9 |^ R6 ) * ( R16 |^ R6 ) ) by L482 , L498 , L499;
thus L502: thesis by L501 , L480 , L497 , L498 , L500 , FUNCT_1:def 3;
end;
L503: C21 is  one-to-one
proof
let R1 being set;
let R2 being set;
assume that
L504: R1 in ( dom C21 )
and
L505: R2 in ( dom C21 )
and
L506: ( C21 . R1 ) = ( C21 . R2 );
consider R8 being (Element of R5) such that L507: R2 = ( R8 * R16 ) and L508: ( C21 . R2 ) = ( ( R8 |^ R6 ) * ( R16 |^ R6 ) ) by L480 , L481 , L505;
consider R7 being (Element of R5) such that L509: R1 = ( R7 * R16 ) and L510: ( C21 . R1 ) = ( ( R7 |^ R6 ) * ( R16 |^ R6 ) ) by L480 , L481 , L504;
L511: ( ( ( R8 |^ R6 ) " ) * ( R7 |^ R6 ) ) = ( ( ( R8 " ) |^ R6 ) * ( R7 |^ R6 ) ) by L132
.= ( ( ( R8 " ) * R7 ) |^ R6 ) by L125;
L512: ( ( ( R8 |^ R6 ) " ) * ( R7 |^ R6 ) ) in ( R16 |^ R6 ) by L506 , L510 , L508 , GROUP_2:114;
consider R9 being (Element of R5) such that L513: ( ( ( R8 " ) * R7 ) |^ R6 ) = ( R9 |^ R6 ) and L514: R9 in R16 by L512 , L511 , L374;
L515: ( ( R8 " ) * R7 ) = R9 by L513 , L102;
thus L516: thesis by L515 , L509 , L507 , L514 , GROUP_2:114;
end;
L517: ( Left_Cosets R16 ) , ( Left_Cosets ( R16 |^ R6 ) ) are_equipotent  by L503 , L480 , L489 , WELLORD2:def 4;
thus L518: thesis by L517 , CARD_1:5;
end;
theorem
L519: (for R5 being Group holds (for R6 being (Element of R5) holds (for R16 being (Subgroup of R5) holds (( Left_Cosets R16 ) is  finite implies ( index R16 ) = ( index ( R16 |^ R6 ) )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R16 being (Subgroup of R5);
assume L520: ( Left_Cosets R16 ) is  finite;
L521: (ex B20 being  finite set st (B20 = ( Left_Cosets R16 ) & ( index R16 ) = ( card B20 ))) by L520 , GROUP_2:def 18;
L522: ( Index R16 ) = ( Index ( R16 |^ R6 ) ) by L475;
L523: ( Left_Cosets R16 ) , ( Left_Cosets ( R16 |^ R6 ) ) are_equipotent  by L522 , CARD_1:5;
L524: ( Left_Cosets ( R16 |^ R6 ) ) is  finite by L523 , L520 , CARD_1:38;
thus L525: thesis by L524 , L521 , L522 , GROUP_2:def 18;
end;
theorem
L526: (for R5 being Group holds (R5 is  commutative  commutative  commutative  commutative Group implies (for B21 being  strict (Subgroup of R5) holds (for R6 being (Element of R5) holds ( B21 |^ R6 ) = B21))))
proof
let R5 being Group;
assume L527: R5 is  commutative  commutative  commutative  commutative Group;
let C22 being  strict (Subgroup of R5);
let R6 being (Element of R5);
L528: (the carrier of ( C22 |^ R6 )) = ( ( ( R6 " ) * C22 ) * R6 ) by L387
.= ( ( C22 * ( R6 " ) ) * R6 ) by L527 , GROUP_2:112
.= ( C22 * ( ( R6 " ) * R6 ) ) by GROUP_2:107
.= ( C22 * ( 1_ R5 ) ) by GROUP_1:def 5
.= (the carrier of C22) by GROUP_2:109;
thus L529: thesis by L528 , GROUP_2:59;
end;
definition
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
pred R6 , R7 are_conjugated 
means
:L530: (ex R10 being (Element of R5) st R6 = ( R7 |^ R10 ))
;end;
notation
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
antonym R6 , R7 are_not_conjugated  for R6 , R7 are_conjugated ;
end;
theorem
L533: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (R6 , R7 are_conjugated  iff (ex R10 being (Element of R5) st R7 = ( R6 |^ R10 ))))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L534: (R6 , R7 are_conjugated  implies (ex R10 being (Element of R5) st R7 = ( R6 |^ R10 )))
proof
given R10 being (Element of R5) such that
L535: R6 = ( R7 |^ R10 );

L536: ( R6 |^ ( R10 " ) ) = R7 by L535 , L129;
thus L537: thesis by L536;
end;

given R10 being (Element of R5) such that
L538: R7 = ( R6 |^ R10 );

L539: R6 = ( R7 |^ ( R10 " ) ) by L538 , L129;
thus L540: thesis by L539 , L530;
end;
theorem
L541: (for R5 being Group holds (for R6 being (Element of R5) holds R6 , R6 are_conjugated ))
proof
let R5 being Group;
let R6 being (Element of R5);
take ( 1_ R5 );
thus L542: thesis by L112;
end;
theorem
L543: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (R6 , R7 are_conjugated  implies R7 , R6 are_conjugated ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
given R10 being (Element of R5) such that
L544: R6 = ( R7 |^ R10 );

L545: R7 = ( R6 |^ ( R10 " ) ) by L544 , L129;
thus L546: thesis by L545 , L530;
end;
definition
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
redefine pred R6 , R7 are_conjugated 
;
reflexivity
 by L541;
symmetry
 by L543;
end;
theorem
L548: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (for R8 being (Element of R5) holds ((R6 , R7 are_conjugated  & R7 , R8 are_conjugated ) implies R6 , R8 are_conjugated )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
let R8 being (Element of R5);
given R10 being (Element of R5) such that
L549: R6 = ( R7 |^ R10 );

given R11 being (Element of R5) such that
L550: R7 = ( R8 |^ R11 );

L551: R6 = ( R8 |^ ( R11 * R10 ) ) by L549 , L550 , L127;
thus L552: thesis by L551 , L530;
end;
theorem
L553: (for R5 being Group holds (for R6 being (Element of R5) holds ((R6 , ( 1_ R5 ) are_conjugated  or ( 1_ R5 ) , R6 are_conjugated ) implies R6 = ( 1_ R5 ))))
proof
let R5 being Group;
let R6 being (Element of R5);
assume L554: (R6 , ( 1_ R5 ) are_conjugated  or ( 1_ R5 ) , R6 are_conjugated );
L555:
now
per cases  by L554;
suppose L556: R6 , ( 1_ R5 ) are_conjugated ;

L557: (ex R10 being (Element of R5) st ( 1_ R5 ) = ( R6 |^ R10 )) by L556 , L533;
thus L558: thesis by L557 , L108;
end;
suppose L559: ( 1_ R5 ) , R6 are_conjugated ;

L560: (ex R10 being (Element of R5) st ( 1_ R5 ) = ( R6 |^ R10 )) by L559 , L530;
thus L561: thesis by L560 , L108;
end;
end;
thus L563: thesis by L555;
end;
theorem
L564: (for R5 being Group holds (for R6 being (Element of R5) holds ( R6 |^ ( carr ( (Omega). R5 ) ) ) = { R7 where R7 is (Element of R5) : R6 , R7 are_conjugated  }))
proof
let R5 being Group;
let R6 being (Element of R5);
set D29 = ( R6 |^ ( carr ( (Omega). R5 ) ) );
set D30 = { R7 where R7 is (Element of R5) : R6 , R7 are_conjugated  };
thus L565: D29 c= D30
proof
let R1 being set;
assume L566: R1 in D29;
reconsider D31 = R1 as (Element of R5) by L566;
L567: (ex R10 being (Element of R5) st (R1 = ( R6 |^ R10 ) & R10 in ( carr ( (Omega). R5 ) ))) by L566 , L286;
L568: D31 , R6 are_conjugated  by L567 , L530;
thus L569: thesis by L568;
end;

let R1 being set;
assume L570: R1 in D30;
consider R7 being (Element of R5) such that L571: R1 = R7 and L572: R6 , R7 are_conjugated  by L570;
L573: (ex R10 being (Element of R5) st R7 = ( R6 |^ R10 )) by L572 , L530;
thus L574: thesis by L573 , L571 , L286;
end;
definition
let R5 being Group;
let R6 being (Element of R5);
func con_class R6 -> (Subset of R5) equals 
( R6 |^ ( carr ( (Omega). R5 ) ) );
correctness;
end;
theorem
L576: (for R1 being set holds (for R5 being Group holds (for R6 being (Element of R5) holds (R1 in ( con_class R6 ) iff (ex R7 being (Element of R5) st (R7 = R1 & R6 , R7 are_conjugated ))))))
proof
let R1 being set;
let R5 being Group;
let R6 being (Element of R5);
thus L577: (R1 in ( con_class R6 ) implies (ex R7 being (Element of R5) st (R7 = R1 & R6 , R7 are_conjugated )))
proof
assume L578: R1 in ( con_class R6 );
L579: R1 in { R7 where R7 is (Element of R5) : R6 , R7 are_conjugated  } by L578 , L564;
thus L580: thesis by L579;
end;

given R7 being (Element of R5) such that
L581: (R7 = R1 & R6 , R7 are_conjugated );

L582: R1 in { R8 where R8 is (Element of R5) : R6 , R8 are_conjugated  } by L581;
thus L583: thesis by L582 , L564;
end;
theorem
L584: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (R6 in ( con_class R7 ) iff R6 , R7 are_conjugated ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L585: (R6 in ( con_class R7 ) implies R6 , R7 are_conjugated )
proof
assume L586: R6 in ( con_class R7 );
L587: (ex R8 being (Element of R5) st (R6 = R8 & R7 , R8 are_conjugated )) by L586 , L576;
thus L588: thesis by L587;
end;

assume L589: R6 , R7 are_conjugated ;
thus L590: thesis by L589 , L576;
end;
theorem
L591: (for R5 being Group holds (for R6 being (Element of R5) holds (for R10 being (Element of R5) holds ( R6 |^ R10 ) in ( con_class R6 ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R10 being (Element of R5);
L592: R6 , ( R6 |^ R10 ) are_conjugated  by L533;
thus L593: thesis by L592 , L576;
end;
theorem
L594: (for R5 being Group holds (for R6 being (Element of R5) holds R6 in ( con_class R6 ))) by L584;
theorem
L595: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (R6 in ( con_class R7 ) implies R7 in ( con_class R6 )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
assume L596: R6 in ( con_class R7 );
L597: R6 , R7 are_conjugated  by L596 , L584;
thus L598: thesis by L597 , L584;
end;
theorem
L599: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds (( con_class R6 ) = ( con_class R7 ) iff ( con_class R6 ) meets ( con_class R7 )))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L600: (( con_class R6 ) = ( con_class R7 ) implies ( con_class R6 ) meets ( con_class R7 ))
proof
assume L601: ( con_class R6 ) = ( con_class R7 );
L602: R6 in ( con_class R6 ) by L584;
thus L603: thesis by L602 , L601 , XBOOLE_0:3;
end;

assume L604: ( con_class R6 ) meets ( con_class R7 );
consider R1 being set such that L605: R1 in ( con_class R6 ) and L606: R1 in ( con_class R7 ) by L604 , XBOOLE_0:3;
reconsider D32 = R1 as (Element of R5) by L605;
L607: R6 , D32 are_conjugated  by L605 , L584;
thus L608: ( con_class R6 ) c= ( con_class R7 )
proof
let R2 being set;
assume L609: R2 in ( con_class R6 );
consider R10 being (Element of R5) such that L610: R10 = R2 and L611: R6 , R10 are_conjugated  by L609 , L576;
L612: R7 , D32 are_conjugated  by L606 , L584;
L613: D32 , R6 are_conjugated  by L605 , L584;
L614: D32 , R10 are_conjugated  by L613 , L611 , L548;
L615: R7 , R10 are_conjugated  by L614 , L612 , L548;
thus L616: thesis by L615 , L610 , L576;
end;

let R2 being set;
assume L617: R2 in ( con_class R7 );
consider R10 being (Element of R5) such that L618: R10 = R2 and L619: R7 , R10 are_conjugated  by L617 , L576;
L620: D32 , R7 are_conjugated  by L606 , L584;
L621: D32 , R10 are_conjugated  by L620 , L619 , L548;
L622: R6 , R10 are_conjugated  by L621 , L607 , L548;
thus L623: thesis by L622 , L618 , L576;
end;
theorem
L624: (for R5 being Group holds (for R6 being (Element of R5) holds (( con_class R6 ) = { ( 1_ R5 ) } iff R6 = ( 1_ R5 ))))
proof
let R5 being Group;
let R6 being (Element of R5);
thus L625: (( con_class R6 ) = { ( 1_ R5 ) } implies R6 = ( 1_ R5 ))
proof
assume L626: ( con_class R6 ) = { ( 1_ R5 ) };
L627: R6 in ( con_class R6 ) by L584;
thus L628: thesis by L627 , L626 , TARSKI:def 1;
end;

assume L629: R6 = ( 1_ R5 );
thus L630: ( con_class R6 ) c= { ( 1_ R5 ) }
proof
let R1 being set;
assume L631: R1 in ( con_class R6 );
consider R7 being (Element of R5) such that L632: R7 = R1 and L633: R6 , R7 are_conjugated  by L631 , L576;
L634: R7 = ( 1_ R5 ) by L629 , L633 , L553;
thus L635: thesis by L634 , L632 , TARSKI:def 1;
end;

L636: ( 1_ R5 ) in ( con_class R6 ) by L629 , L584;
thus L637: thesis by L636 , ZFMISC_1:31;
end;
theorem
L638: (for R5 being Group holds (for R6 being (Element of R5) holds (for R12 being (Subset of R5) holds ( ( con_class R6 ) * R12 ) = ( R12 * ( con_class R6 ) ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R12 being (Subset of R5);
thus L639: ( ( con_class R6 ) * R12 ) c= ( R12 * ( con_class R6 ) )
proof
let R1 being set;
assume L640: R1 in ( ( con_class R6 ) * R12 );
consider R7 being (Element of R5), R8 being (Element of R5) such that L641: R1 = ( R7 * R8 ) and L642: R7 in ( con_class R6 ) and L643: R8 in R12 by L640;
reconsider D33 = R1 as (Element of R5) by L641;
L644: R7 , R6 are_conjugated  by L642 , L584;
consider R10 being (Element of R5) such that L645: R7 = ( R6 |^ R10 ) by L644 , L530;
L646: ( D33 |^ ( R8 " ) ) = ( ( R8 * ( ( R6 |^ R10 ) * R8 ) ) * ( R8 " ) ) by L641 , L645
.= ( R8 * ( ( ( R6 |^ R10 ) * R8 ) * ( R8 " ) ) ) by GROUP_1:def 3
.= ( R8 * ( R6 |^ R10 ) ) by L1;
L647: R1 = ( ( R8 * ( R6 |^ R10 ) ) |^ R8 ) by L646 , L129
.= ( ( R8 |^ R8 ) * ( ( R6 |^ R10 ) |^ R8 ) ) by L125
.= ( R8 * ( ( R6 |^ R10 ) |^ R8 ) ) by L114
.= ( R8 * ( R6 |^ ( R10 * R8 ) ) ) by L127;
L648: ( R6 |^ ( R10 * R8 ) ) in ( con_class R6 ) by L591;
thus L649: thesis by L648 , L643 , L647;
end;

let R1 being set;
assume L650: R1 in ( R12 * ( con_class R6 ) );
consider R7 being (Element of R5), R8 being (Element of R5) such that L651: R1 = ( R7 * R8 ) and L652: R7 in R12 and L653: R8 in ( con_class R6 ) by L650;
reconsider D34 = R1 as (Element of R5) by L651;
L654: R8 , R6 are_conjugated  by L653 , L584;
consider R10 being (Element of R5) such that L655: R8 = ( R6 |^ R10 ) by L654 , L530;
L656: ( D34 |^ R7 ) = ( ( R6 |^ R10 ) * R7 ) by L651 , L655 , L1;
L657: R1 = ( ( ( R6 |^ R10 ) * R7 ) |^ ( R7 " ) ) by L656 , L129
.= ( ( ( R6 |^ R10 ) |^ ( R7 " ) ) * ( R7 |^ ( R7 " ) ) ) by L125
.= ( ( R6 |^ ( R10 * ( R7 " ) ) ) * ( R7 |^ ( R7 " ) ) ) by L127
.= ( ( R6 |^ ( R10 * ( R7 " ) ) ) * R7 ) by L1;
L658: ( R6 |^ ( R10 * ( R7 " ) ) ) in ( con_class R6 ) by L591;
thus L659: thesis by L658 , L652 , L657;
end;
definition
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
pred R12 , R13 are_conjugated 
means
:L660: (ex R10 being (Element of R5) st R12 = ( R13 |^ R10 ))
;end;
notation
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
antonym R12 , R13 are_not_conjugated  for R12 , R13 are_conjugated ;
end;
theorem
L663: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R12 , R13 are_conjugated  iff (ex R10 being (Element of R5) st R13 = ( R12 |^ R10 ))))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
thus L664: (R12 , R13 are_conjugated  implies (ex R10 being (Element of R5) st R13 = ( R12 |^ R10 )))
proof
given R10 being (Element of R5) such that
L665: R12 = ( R13 |^ R10 );

L666: ( R12 |^ ( R10 " ) ) = R13 by L665 , L336;
thus L667: thesis by L666;
end;

given R10 being (Element of R5) such that
L668: R13 = ( R12 |^ R10 );

L669: R12 = ( R13 |^ ( R10 " ) ) by L668 , L336;
thus L670: thesis by L669 , L660;
end;
theorem
L671: (for R5 being Group holds (for R12 being (Subset of R5) holds R12 , R12 are_conjugated ))
proof
let R5 being Group;
let R12 being (Subset of R5);
take ( 1_ R5 );
thus L672: thesis by L323;
end;
theorem
L673: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R12 , R13 are_conjugated  implies R13 , R12 are_conjugated ))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
given R10 being (Element of R5) such that
L674: R12 = ( R13 |^ R10 );

L675: R13 = ( R12 |^ ( R10 " ) ) by L674 , L336;
thus L676: thesis by L675 , L660;
end;
definition
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
redefine pred R12 , R13 are_conjugated 
;
reflexivity
 by L671;
symmetry
 by L673;
end;
theorem
L678: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (for R14 being (Subset of R5) holds ((R12 , R13 are_conjugated  & R13 , R14 are_conjugated ) implies R12 , R14 are_conjugated )))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
let R14 being (Subset of R5);
given R10 being (Element of R5) such that
L679: R12 = ( R13 |^ R10 );

given R11 being (Element of R5) such that
L680: R13 = ( R14 |^ R11 );

L681: R12 = ( R14 |^ ( R11 * R10 ) ) by L679 , L680 , L307;
thus L682: thesis by L681 , L660;
end;
theorem
L683: (for R5 being Group holds (for R6 being (Element of R5) holds (for R7 being (Element of R5) holds ({ R6 } , { R7 } are_conjugated  iff R6 , R7 are_conjugated ))))
proof
let R5 being Group;
let R6 being (Element of R5);
let R7 being (Element of R5);
thus L684: ({ R6 } , { R7 } are_conjugated  implies R6 , R7 are_conjugated )
proof
assume L685: { R6 } , { R7 } are_conjugated ;
consider R10 being (Element of R5) such that L686: ( { R6 } |^ R10 ) = { R7 } by L685 , L663;
L687: { R7 } = { ( R6 |^ R10 ) } by L686 , L229;
L688: R7 = ( R6 |^ R10 ) by L687 , ZFMISC_1:3;
thus L689: thesis by L688 , L533;
end;

assume L690: R6 , R7 are_conjugated ;
consider R10 being (Element of R5) such that L691: ( R6 |^ R10 ) = R7 by L690 , L533;
L692: { R7 } = ( { R6 } |^ R10 ) by L691 , L229;
thus L693: thesis by L692 , L663;
end;
theorem
L694: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R17 being (Subgroup of R5) holds (R12 , ( carr R17 ) are_conjugated  implies (ex B22 being  strict (Subgroup of R5) st (the carrier of B22) = R12)))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R17 being (Subgroup of R5);
assume L695: R12 , ( carr R17 ) are_conjugated ;
consider R10 being (Element of R5) such that L696: R12 = ( ( carr R17 ) |^ R10 ) by L695 , L660;
L697: R12 = (the carrier of ( R17 |^ R10 )) by L696 , L369;
thus L698: thesis by L697;
end;
definition
let R5 being Group;
let R12 being (Subset of R5);
func con_class R12 -> (Subset-Family of R5) equals 
{ R13 where R13 is (Subset of R5) : R12 , R13 are_conjugated  };
coherence
proof
set D35 = { R13 where R13 is (Subset of R5) : R12 , R13 are_conjugated  };
L699: D35 c= ( bool (the carrier of R5) )
proof
let R1 being set;
assume L700: R1 in D35;
L701: (ex R13 being (Subset of R5) st (R1 = R13 & R12 , R13 are_conjugated )) by L700;
thus L702: thesis by L701;
end;
thus L703: thesis by L699;
end;
end;
theorem
L705: (for R1 being set holds (for R5 being Group holds (for R12 being (Subset of R5) holds (R1 in ( con_class R12 ) iff (ex R13 being (Subset of R5) st (R1 = R13 & R12 , R13 are_conjugated ))))));
theorem
L706: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R12 in ( con_class R13 ) iff R12 , R13 are_conjugated ))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
thus L707: (R12 in ( con_class R13 ) implies R12 , R13 are_conjugated )
proof
assume L708: R12 in ( con_class R13 );
L709: (ex R14 being (Subset of R5) st (R12 = R14 & R13 , R14 are_conjugated )) by L708;
thus L710: thesis by L709;
end;

assume L711: R12 , R13 are_conjugated ;
thus L712: thesis by L711;
end;
theorem
L713: (for R5 being Group holds (for R10 being (Element of R5) holds (for R12 being (Subset of R5) holds ( R12 |^ R10 ) in ( con_class R12 ))))
proof
let R5 being Group;
let R10 being (Element of R5);
let R12 being (Subset of R5);
L714: R12 , ( R12 |^ R10 ) are_conjugated  by L663;
thus L715: thesis by L714;
end;
theorem
L716: (for R5 being Group holds (for R12 being (Subset of R5) holds R12 in ( con_class R12 )));
theorem
L717: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (R12 in ( con_class R13 ) implies R13 in ( con_class R12 )))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
assume L718: R12 in ( con_class R13 );
L719: R12 , R13 are_conjugated  by L718 , L706;
thus L720: thesis by L719;
end;
theorem
L721: (for R5 being Group holds (for R12 being (Subset of R5) holds (for R13 being (Subset of R5) holds (( con_class R12 ) = ( con_class R13 ) iff ( con_class R12 ) meets ( con_class R13 )))))
proof
let R5 being Group;
let R12 being (Subset of R5);
let R13 being (Subset of R5);
thus L722: (( con_class R12 ) = ( con_class R13 ) implies ( con_class R12 ) meets ( con_class R13 ))
proof
L723: R12 in ( con_class R12 );
assume L724: ( con_class R12 ) = ( con_class R13 );
thus L725: thesis by L724 , L723 , XBOOLE_0:3;
end;

assume L726: ( con_class R12 ) meets ( con_class R13 );
consider R1 being set such that L727: R1 in ( con_class R12 ) and L728: R1 in ( con_class R13 ) by L726 , XBOOLE_0:3;
reconsider D36 = R1 as (Subset of R5) by L727;
L729: R12 , D36 are_conjugated  by L727 , L706;
thus L730: ( con_class R12 ) c= ( con_class R13 )
proof
let R2 being set;
assume L731: R2 in ( con_class R12 );
consider R14 being (Subset of R5) such that L732: R14 = R2 and L733: R12 , R14 are_conjugated  by L731;
L734: R13 , D36 are_conjugated  by L728 , L706;
L735: D36 , R12 are_conjugated  by L727 , L706;
L736: D36 , R14 are_conjugated  by L735 , L733 , L678;
L737: R13 , R14 are_conjugated  by L736 , L734 , L678;
thus L738: thesis by L737 , L732;
end;

let R2 being set;
assume L739: R2 in ( con_class R13 );
consider R14 being (Subset of R5) such that L740: R14 = R2 and L741: R13 , R14 are_conjugated  by L739;
L742: D36 , R13 are_conjugated  by L728 , L706;
L743: D36 , R14 are_conjugated  by L742 , L741 , L678;
L744: R12 , R14 are_conjugated  by L743 , L729 , L678;
thus L745: thesis by L744 , L740;
end;
theorem
L746: (for R5 being Group holds (for R6 being (Element of R5) holds ( con_class { R6 } ) = { { R7 } where R7 is (Element of R5) : R7 in ( con_class R6 ) }))
proof
let R5 being Group;
let R6 being (Element of R5);
set D37 = { { R7 } where R7 is (Element of R5) : R7 in ( con_class R6 ) };
thus L747: ( con_class { R6 } ) c= D37
proof
let R1 being set;
assume L748: R1 in ( con_class { R6 } );
consider R13 being (Subset of R5) such that L749: R1 = R13 and L750: { R6 } , R13 are_conjugated  by L748;
consider R7 being (Element of R5) such that L751: ( { R6 } |^ R7 ) = R13 by L750 , L663;
L752: R6 , ( R6 |^ R7 ) are_conjugated  by L533;
L753: ( R6 |^ R7 ) in ( con_class R6 ) by L752 , L584;
L754: R13 = { ( R6 |^ R7 ) } by L751 , L229;
thus L755: thesis by L754 , L749 , L753;
end;

let R1 being set;
assume L756: R1 in D37;
consider R7 being (Element of R5) such that L757: R1 = { R7 } and L758: R7 in ( con_class R6 ) by L756;
L759: R7 , R6 are_conjugated  by L758 , L584;
L760: { R7 } , { R6 } are_conjugated  by L759 , L683;
thus L761: thesis by L760 , L757;
end;
theorem
L762: (for R5 being Group holds (for R12 being (Subset of R5) holds (R5 is  finite implies ( con_class R12 ) is  finite)));
definition
let R5 being Group;
let R17 being (Subgroup of R5);
let R18 being (Subgroup of R5);
pred R17 , R18 are_conjugated 
means
:L763: (ex R10 being (Element of R5) st ( the multMagma of R17 ) = ( R18 |^ R10 ))
;end;
notation
let R5 being Group;
let R17 being (Subgroup of R5);
let R18 being (Subgroup of R5);
antonym R17 , R18 are_not_conjugated  for R17 , R18 are_conjugated ;
end;
theorem
L766: (for R5 being Group holds (for B23 , B24 being  strict (Subgroup of R5) holds (B23 , B24 are_conjugated  iff (ex R10 being (Element of R5) st B24 = ( B23 |^ R10 )))))
proof
let R5 being Group;
let C23 , C24 being  strict (Subgroup of R5);
thus L767: (C23 , C24 are_conjugated  implies (ex R10 being (Element of R5) st C24 = ( C23 |^ R10 )))
proof
given R10 being (Element of R5) such that
L768: ( the multMagma of C23 ) = ( C24 |^ R10 );

L769: ( C23 |^ ( R10 " ) ) = C24 by L768 , L395;
thus L770: thesis by L769;
end;

given R10 being (Element of R5) such that
L771: C24 = ( C23 |^ R10 );

L772: C23 = ( C24 |^ ( R10 " ) ) by L771 , L395;
thus L773: thesis by L772 , L763;
end;
theorem
L774: (for R5 being Group holds (for B25 being  strict (Subgroup of R5) holds B25 , B25 are_conjugated ))
proof
let R5 being Group;
let C25 being  strict (Subgroup of R5);
take ( 1_ R5 );
thus L775: thesis by L392;
end;
theorem
L776: (for R5 being Group holds (for B26 , B27 being  strict (Subgroup of R5) holds (B26 , B27 are_conjugated  implies B27 , B26 are_conjugated )))
proof
let R5 being Group;
let C26 , C27 being  strict (Subgroup of R5);
given R10 being (Element of R5) such that
L777: ( the multMagma of C26 ) = ( C27 |^ R10 );

L778: C27 = ( C26 |^ ( R10 " ) ) by L777 , L395;
thus L779: thesis by L778 , L763;
end;
definition
let R5 being Group;
let C28 , C29 being  strict (Subgroup of R5);
redefine pred C28 , C29 are_conjugated 
;
reflexivity
 by L774;
symmetry
 by L776;
end;
theorem
L781: (for R5 being Group holds (for R19 being (Subgroup of R5) holds (for B28 , B29 being  strict (Subgroup of R5) holds ((B28 , B29 are_conjugated  & B29 , R19 are_conjugated ) implies B28 , R19 are_conjugated ))))
proof
let R5 being Group;
let R19 being (Subgroup of R5);
let C30 , C31 being  strict (Subgroup of R5);
given R10 being (Element of R5) such that
L782: ( the multMagma of C30 ) = ( C31 |^ R10 );

given R11 being (Element of R5) such that
L783: ( the multMagma of C31 ) = ( R19 |^ R11 );

L784: C30 = ( R19 |^ ( R11 * R10 ) ) by L782 , L783 , L389;
thus L785: thesis by L784 , L763;
end;
definition
let R5 being Group;
let R16 being (Subgroup of R5);
func con_class R16 -> (Subset of ( Subgroups R5 )) means 
:L786: (for R1 being set holds (R1 in it iff (ex B30 being  strict (Subgroup of R5) st (R1 = B30 & R16 , B30 are_conjugated ))));
existence
proof
defpred S7[ set ] means (ex B31 being  strict (Subgroup of R5) st ($1 = B31 & R16 , B31 are_conjugated ));
consider R22 being (Subset of ( Subgroups R5 )) such that L787: (for R1 being set holds (R1 in R22 iff (R1 in ( Subgroups R5 ) & S7[ R1 ]))) from SUBSET_1:sch 1;
take R22;
let R1 being set;
thus L788: (R1 in R22 implies (ex B32 being  strict (Subgroup of R5) st (R1 = B32 & R16 , B32 are_conjugated ))) by L787;
given C32 being  strict (Subgroup of R5) such that
L789: R1 = C32
and
L790: R16 , C32 are_conjugated ;

L791: R1 in ( Subgroups R5 ) by L789 , L44;
thus L792: thesis by L791 , L787 , L789 , L790;
end;
uniqueness
proof
defpred S8[ set ] means (ex B33 being  strict (Subgroup of R5) st ($1 = B33 & R16 , B33 are_conjugated ));
let C33 , C34 being (Subset of ( Subgroups R5 ));
assume L793: (for R1 being set holds (R1 in C33 iff S8[ R1 ]));
assume L794: (for R1 being set holds (R1 in C34 iff S8[ R1 ]));
thus L795: thesis from XBOOLE_0:sch 2(L793 , L794);
end;
end;
theorem
L797: (for R1 being set holds (for R5 being Group holds (for R16 being (Subgroup of R5) holds (R1 in ( con_class R16 ) implies R1 is  strict  strict  strict  strict (Subgroup of R5)))))
proof
let R1 being set;
let R5 being Group;
let R16 being (Subgroup of R5);
assume L798: R1 in ( con_class R16 );
L799: (ex B34 being  strict (Subgroup of R5) st (R1 = B34 & R16 , B34 are_conjugated )) by L798 , L786;
thus L800: thesis by L799;
end;
theorem
L801: (for R5 being Group holds (for B35 , B36 being  strict (Subgroup of R5) holds (B35 in ( con_class B36 ) iff B35 , B36 are_conjugated )))
proof
let R5 being Group;
let C35 , C36 being  strict (Subgroup of R5);
thus L802: (C35 in ( con_class C36 ) implies C35 , C36 are_conjugated )
proof
assume L803: C35 in ( con_class C36 );
L804: (ex B37 being  strict (Subgroup of R5) st (C35 = B37 & C36 , B37 are_conjugated )) by L803 , L786;
thus L805: thesis by L804;
end;

assume L806: C35 , C36 are_conjugated ;
thus L807: thesis by L806 , L786;
end;
theorem
L808: (for R5 being Group holds (for R10 being (Element of R5) holds (for B38 being  strict (Subgroup of R5) holds ( B38 |^ R10 ) in ( con_class B38 ))))
proof
let R5 being Group;
let R10 being (Element of R5);
let C37 being  strict (Subgroup of R5);
L809: C37 , ( C37 |^ R10 ) are_conjugated  by L766;
thus L810: thesis by L809 , L786;
end;
theorem
L811: (for R5 being Group holds (for B39 being  strict (Subgroup of R5) holds B39 in ( con_class B39 )))
proof
let R5 being Group;
let C38 being  strict (Subgroup of R5);
L812: C38 , C38 are_conjugated ;
thus L813: thesis by L812 , L786;
end;
theorem
L814: (for R5 being Group holds (for B40 , B41 being  strict (Subgroup of R5) holds (B40 in ( con_class B41 ) implies B41 in ( con_class B40 ))))
proof
let R5 being Group;
let C39 , C40 being  strict (Subgroup of R5);
assume L815: C39 in ( con_class C40 );
L816: C39 , C40 are_conjugated  by L815 , L801;
thus L817: thesis by L816 , L801;
end;
theorem
L818: (for R5 being Group holds (for B42 , B43 being  strict (Subgroup of R5) holds (( con_class B42 ) = ( con_class B43 ) iff ( con_class B42 ) meets ( con_class B43 ))))
proof
let R5 being Group;
let C41 , C42 being  strict (Subgroup of R5);
thus L819: (( con_class C41 ) = ( con_class C42 ) implies ( con_class C41 ) meets ( con_class C42 ))
proof
assume L820: ( con_class C41 ) = ( con_class C42 );
L821: C41 in ( con_class C41 ) by L811;
thus L822: thesis by L821 , L820 , XBOOLE_0:3;
end;

assume L823: ( con_class C41 ) meets ( con_class C42 );
consider R1 being set such that L824: R1 in ( con_class C41 ) and L825: R1 in ( con_class C42 ) by L823 , XBOOLE_0:3;
reconsider D38 = R1 as  strict (Subgroup of R5) by L824 , L797;
L826: C41 , D38 are_conjugated  by L824 , L801;
thus L827: ( con_class C41 ) c= ( con_class C42 )
proof
let R2 being set;
assume L828: R2 in ( con_class C41 );
consider C43 being  strict (Subgroup of R5) such that L829: C43 = R2 and L830: C41 , C43 are_conjugated  by L828 , L786;
L831: C42 , D38 are_conjugated  by L825 , L801;
L832: D38 , C41 are_conjugated  by L824 , L801;
L833: D38 , C43 are_conjugated  by L832 , L830 , L781;
L834: C42 , C43 are_conjugated  by L833 , L831 , L781;
thus L835: thesis by L834 , L829 , L786;
end;

let R2 being set;
assume L836: R2 in ( con_class C42 );
consider C44 being  strict (Subgroup of R5) such that L837: C44 = R2 and L838: C42 , C44 are_conjugated  by L836 , L786;
L839: D38 , C42 are_conjugated  by L825 , L801;
L840: D38 , C44 are_conjugated  by L839 , L838 , L781;
L841: C41 , C44 are_conjugated  by L840 , L826 , L781;
thus L842: thesis by L841 , L837 , L786;
end;
theorem
L843: (for R5 being Group holds (for R16 being (Subgroup of R5) holds (R5 is  finite implies ( con_class R16 ) is  finite))) by L80 , FINSET_1:1;
theorem
L844: (for R5 being Group holds (for R18 being (Subgroup of R5) holds (for B44 being  strict (Subgroup of R5) holds (B44 , R18 are_conjugated  iff ( carr B44 ) , ( carr R18 ) are_conjugated ))))
proof
let R5 being Group;
let R18 being (Subgroup of R5);
let C45 being  strict (Subgroup of R5);
thus L845: (C45 , R18 are_conjugated  implies ( carr C45 ) , ( carr R18 ) are_conjugated )
proof
given R6 being (Element of R5) such that
L846: ( the multMagma of C45 ) = ( R18 |^ R6 );

L847: ( carr C45 ) = ( ( carr R18 ) |^ R6 ) by L846 , L369;
thus L848: thesis by L847 , L660;
end;

given R6 being (Element of R5) such that
L849: ( carr C45 ) = ( ( carr R18 ) |^ R6 );

L850: C45 = ( R18 |^ R6 ) by L849 , L369;
thus L851: thesis by L850 , L763;
end;
definition
let R5 being Group;
let C46 being (Subgroup of R5);
attr C46 is  normal
means
:L852: (for R6 being (Element of R5) holds ( C46 |^ R6 ) = ( the multMagma of C46 ));
end;
registration
let R5 being Group;
cluster  strict  normal for (Subgroup of R5);
existence
proof
L854: (for R6 being (Element of R5) holds ( ( (1). R5 ) |^ R6 ) = ( (1). R5 )) by L453;
L855: ( (1). R5 ) is  normal by L854 , L852;
thus L856: thesis by L855;
end;
end;
theorem
L858: (for R5 being Group holds (( (1). R5 ) is  normal & ( (Omega). R5 ) is  normal))
proof
let R5 being Group;
thus L859: (for B45 being (Element of R5) holds ( ( (1). R5 ) |^ B45 ) = ( the multMagma of ( (1). R5 ) )) by L453;
thus L860: (for B46 being (Element of R5) holds ( ( (Omega). R5 ) |^ B46 ) = ( the multMagma of ( (Omega). R5 ) )) by L462;
end;
theorem
L861: (for R5 being Group holds (for B47 , B48 being  strict  normal (Subgroup of R5) holds ( B47 /\ B48 ) is  normal))
proof
let R5 being Group;
let C47 , C48 being  strict  normal (Subgroup of R5);
let R6 being (Element of R5);
thus L862: ( ( C47 /\ C48 ) |^ R6 ) = ( ( C47 |^ R6 ) /\ ( C48 |^ R6 ) ) by L398
.= ( C47 /\ ( C48 |^ R6 ) ) by L852
.= ( the multMagma of ( C47 /\ C48 ) ) by L852;
end;
theorem
L863: (for R5 being Group holds (for B49 being  strict (Subgroup of R5) holds (R5 is  commutative  commutative  commutative  commutative Group implies B49 is  normal)))
proof
let R5 being Group;
let C49 being  strict (Subgroup of R5);
assume L864: R5 is  commutative  commutative  commutative  commutative Group;
thus L865: (for R6 being (Element of R5) holds ( C49 |^ R6 ) = ( the multMagma of C49 )) by L864 , L526;
end;
theorem
L866: (for R5 being Group holds (for R16 being (Subgroup of R5) holds (R16 is  normal  normal  normal  normal (Subgroup of R5) iff (for R6 being (Element of R5) holds ( R6 * R16 ) = ( R16 * R6 )))))
proof
let R5 being Group;
let R16 being (Subgroup of R5);
thus L867: (R16 is  normal  normal  normal  normal (Subgroup of R5) implies (for R6 being (Element of R5) holds ( R6 * R16 ) = ( R16 * R6 )))
proof
assume L868: R16 is  normal  normal  normal  normal (Subgroup of R5);
let R6 being (Element of R5);
L869: ( carr ( R16 |^ R6 ) ) = ( ( ( R6 " ) * R16 ) * R6 ) by L387;
L870: ( carr ( R16 |^ R6 ) ) = (the carrier of ( the multMagma of R16 )) by L868 , L852
.= ( carr R16 );
thus L871: ( R6 * R16 ) = ( ( R6 * ( ( R6 " ) * R16 ) ) * R6 ) by L870 , L869 , GROUP_2:33
.= ( ( ( R6 * ( R6 " ) ) * R16 ) * R6 ) by GROUP_2:105
.= ( ( ( 1_ R5 ) * R16 ) * R6 ) by GROUP_1:def 5
.= ( R16 * R6 ) by GROUP_2:37;
end;

assume L872: (for R6 being (Element of R5) holds ( R6 * R16 ) = ( R16 * R6 ));
L873: R16 is  normal
proof
let R6 being (Element of R5);
L874: (the carrier of ( R16 |^ R6 )) = ( ( ( R6 " ) * R16 ) * R6 ) by L387
.= ( ( R16 * ( R6 " ) ) * R6 ) by L872
.= ( R16 * ( ( R6 " ) * R6 ) ) by GROUP_2:107
.= ( R16 * ( 1_ R5 ) ) by GROUP_1:def 5
.= (the carrier of R16) by GROUP_2:109;
thus L875: thesis by L874 , GROUP_2:59;
end;
thus L876: thesis by L873;
end;
theorem
L877: (for R5 being Group holds (for B50 being (Subgroup of R5) holds (B50 is  normal  normal  normal  normal (Subgroup of R5) iff (for R6 being (Element of R5) holds ( R6 * B50 ) c= ( B50 * R6 )))))
proof
let R5 being Group;
let C50 being (Subgroup of R5);
thus L878: (C50 is  normal  normal  normal  normal (Subgroup of R5) implies (for R6 being (Element of R5) holds ( R6 * C50 ) c= ( C50 * R6 ))) by L866;
assume L879: (for R6 being (Element of R5) holds ( R6 * C50 ) c= ( C50 * R6 ));
L880:
now
let R6 being (Element of R5);
L881: ( ( R6 " ) * C50 ) c= ( C50 * ( R6 " ) ) by L879;
L882: ( R6 * ( ( R6 " ) * C50 ) ) c= ( R6 * ( C50 * ( R6 " ) ) ) by L881 , L23;
L883: ( ( R6 * ( R6 " ) ) * C50 ) c= ( R6 * ( C50 * ( R6 " ) ) ) by L882 , GROUP_2:105;
L884: ( ( 1_ R5 ) * C50 ) c= ( R6 * ( C50 * ( R6 " ) ) ) by L883 , GROUP_1:def 5;
L885: ( carr C50 ) c= ( R6 * ( C50 * ( R6 " ) ) ) by L884 , GROUP_2:109;
L886: ( carr C50 ) c= ( ( R6 * C50 ) * ( R6 " ) ) by L885 , GROUP_2:106;
L887: ( ( carr C50 ) * R6 ) c= ( ( ( R6 * C50 ) * ( R6 " ) ) * R6 ) by L886 , L23;
L888: ( C50 * R6 ) c= ( ( R6 * C50 ) * ( ( R6 " ) * R6 ) ) by L887 , GROUP_2:34;
L889: ( C50 * R6 ) c= ( ( R6 * C50 ) * ( 1_ R5 ) ) by L888 , GROUP_1:def 5;
thus L890: ( C50 * R6 ) c= ( R6 * C50 ) by L889 , GROUP_2:37;
end;
L891:
now
let R6 being (Element of R5);
L892: (( R6 * C50 ) c= ( C50 * R6 ) & ( C50 * R6 ) c= ( R6 * C50 )) by L879 , L880;
thus L893: ( R6 * C50 ) = ( C50 * R6 ) by L892 , XBOOLE_0:def 10;
end;
thus L894: thesis by L891 , L866;
end;
theorem
L895: (for R5 being Group holds (for B51 being (Subgroup of R5) holds (B51 is  normal  normal  normal  normal (Subgroup of R5) iff (for R6 being (Element of R5) holds ( B51 * R6 ) c= ( R6 * B51 )))))
proof
let R5 being Group;
let C51 being (Subgroup of R5);
thus L896: (C51 is  normal  normal  normal  normal (Subgroup of R5) implies (for R6 being (Element of R5) holds ( C51 * R6 ) c= ( R6 * C51 ))) by L866;
assume L897: (for R6 being (Element of R5) holds ( C51 * R6 ) c= ( R6 * C51 ));
L898:
now
let R6 being (Element of R5);
L899: ( C51 * ( R6 " ) ) c= ( ( R6 " ) * C51 ) by L897;
L900: ( R6 * ( C51 * ( R6 " ) ) ) c= ( R6 * ( ( R6 " ) * C51 ) ) by L899 , L23;
L901: ( R6 * ( C51 * ( R6 " ) ) ) c= ( ( R6 * ( R6 " ) ) * C51 ) by L900 , GROUP_2:105;
L902: ( R6 * ( C51 * ( R6 " ) ) ) c= ( ( 1_ R5 ) * C51 ) by L901 , GROUP_1:def 5;
L903: ( R6 * ( C51 * ( R6 " ) ) ) c= ( carr C51 ) by L902 , GROUP_2:109;
L904: ( ( R6 * C51 ) * ( R6 " ) ) c= ( carr C51 ) by L903 , GROUP_2:106;
L905: ( ( ( R6 * C51 ) * ( R6 " ) ) * R6 ) c= ( ( carr C51 ) * R6 ) by L904 , L23;
L906: ( ( R6 * C51 ) * ( ( R6 " ) * R6 ) ) c= ( C51 * R6 ) by L905 , GROUP_2:34;
L907: ( ( R6 * C51 ) * ( 1_ R5 ) ) c= ( C51 * R6 ) by L906 , GROUP_1:def 5;
thus L908: ( R6 * C51 ) c= ( C51 * R6 ) by L907 , GROUP_2:37;
end;
L909:
now
let R6 being (Element of R5);
L910: (( R6 * C51 ) c= ( C51 * R6 ) & ( C51 * R6 ) c= ( R6 * C51 )) by L897 , L898;
thus L911: ( R6 * C51 ) = ( C51 * R6 ) by L910 , XBOOLE_0:def 10;
end;
thus L912: thesis by L909 , L866;
end;
theorem
L913: (for R5 being Group holds (for B52 being (Subgroup of R5) holds (B52 is  normal  normal  normal  normal (Subgroup of R5) iff (for R12 being (Subset of R5) holds ( R12 * B52 ) = ( B52 * R12 )))))
proof
let R5 being Group;
let C52 being (Subgroup of R5);
thus L914: (C52 is  normal  normal  normal  normal (Subgroup of R5) implies (for R12 being (Subset of R5) holds ( R12 * C52 ) = ( C52 * R12 )))
proof
assume L915: C52 is  normal  normal  normal  normal (Subgroup of R5);
let R12 being (Subset of R5);
thus L916: ( R12 * C52 ) c= ( C52 * R12 )
proof
let R1 being set;
assume L917: R1 in ( R12 * C52 );
consider R6 being (Element of R5), R11 being (Element of R5) such that L918: R1 = ( R6 * R11 ) and L919: R6 in R12 and L920: R11 in C52 by L917 , GROUP_2:94;
L921: R1 in ( R6 * C52 ) by L918 , L920 , GROUP_2:103;
L922: R1 in ( C52 * R6 ) by L921 , L915 , L866;
L923: (ex R10 being (Element of R5) st (R1 = ( R10 * R6 ) & R10 in C52)) by L922 , GROUP_2:104;
thus L924: thesis by L923 , L919 , GROUP_2:95;
end;

let R1 being set;
assume L925: R1 in ( C52 * R12 );
consider R11 being (Element of R5), R6 being (Element of R5) such that L926: (R1 = ( R11 * R6 ) & R11 in C52) and L927: R6 in R12 by L925 , GROUP_2:95;
L928: R1 in ( C52 * R6 ) by L926 , GROUP_2:104;
L929: R1 in ( R6 * C52 ) by L928 , L915 , L866;
L930: (ex R10 being (Element of R5) st (R1 = ( R6 * R10 ) & R10 in C52)) by L929 , GROUP_2:103;
thus L931: thesis by L930 , L927 , GROUP_2:94;
end;

assume L932: (for R12 being (Subset of R5) holds ( R12 * C52 ) = ( C52 * R12 ));
L933:
now
let R6 being (Element of R5);
thus L934: ( R6 * C52 ) = ( { R6 } * C52 )
.= ( C52 * { R6 } ) by L932
.= ( C52 * R6 );
end;
thus L935: thesis by L933 , L866;
end;
theorem
L936: (for R5 being Group holds (for B53 being  strict (Subgroup of R5) holds (B53 is  normal  normal  normal  normal (Subgroup of R5) iff (for R6 being (Element of R5) holds B53 is (Subgroup of ( B53 |^ R6 ))))))
proof
let R5 being Group;
let C53 being  strict (Subgroup of R5);
thus L937: (C53 is  normal  normal  normal  normal (Subgroup of R5) implies (for R6 being (Element of R5) holds C53 is (Subgroup of ( C53 |^ R6 ))))
proof
assume L938: C53 is  normal  normal  normal  normal (Subgroup of R5);
let R6 being (Element of R5);
L939: ( C53 |^ R6 ) = ( the multMagma of C53 ) by L938 , L852;
thus L940: thesis by L939 , GROUP_2:54;
end;

assume L941: (for R6 being (Element of R5) holds C53 is (Subgroup of ( C53 |^ R6 )));
L942:
now
let R6 being (Element of R5);
L943: ( ( C53 |^ ( R6 " ) ) * R6 ) = ( ( ( ( ( R6 " ) " ) * C53 ) * ( R6 " ) ) * R6 ) by L387
.= ( ( ( ( R6 " ) " ) * C53 ) * ( ( R6 " ) * R6 ) ) by GROUP_2:34
.= ( ( ( ( R6 " ) " ) * C53 ) * ( 1_ R5 ) ) by GROUP_1:def 5
.= ( ( ( R6 " ) " ) * C53 ) by GROUP_2:37
.= ( R6 * C53 );
L944: C53 is (Subgroup of ( C53 |^ ( R6 " ) )) by L941;
thus L945: ( C53 * R6 ) c= ( R6 * C53 ) by L944 , L943 , L29;
end;
thus L946: thesis by L942 , L895;
end;
theorem
L947: (for R5 being Group holds (for B54 being  strict (Subgroup of R5) holds (B54 is  normal  normal  normal  normal (Subgroup of R5) iff (for R6 being (Element of R5) holds ( B54 |^ R6 ) is (Subgroup of B54)))))
proof
let R5 being Group;
let C54 being  strict (Subgroup of R5);
thus L948: (C54 is  normal  normal  normal  normal (Subgroup of R5) implies (for R6 being (Element of R5) holds ( C54 |^ R6 ) is (Subgroup of C54)))
proof
assume L949: C54 is  normal  normal  normal  normal (Subgroup of R5);
let R6 being (Element of R5);
L950: ( C54 |^ R6 ) = ( the multMagma of C54 ) by L949 , L852;
thus L951: thesis by L950 , GROUP_2:54;
end;

assume L952: (for R6 being (Element of R5) holds ( C54 |^ R6 ) is (Subgroup of C54));
L953:
now
let R6 being (Element of R5);
L954: ( ( C54 |^ ( R6 " ) ) * R6 ) = ( ( ( ( ( R6 " ) " ) * C54 ) * ( R6 " ) ) * R6 ) by L387
.= ( ( ( ( R6 " ) " ) * C54 ) * ( ( R6 " ) * R6 ) ) by GROUP_2:34
.= ( ( ( ( R6 " ) " ) * C54 ) * ( 1_ R5 ) ) by GROUP_1:def 5
.= ( ( ( R6 " ) " ) * C54 ) by GROUP_2:37
.= ( R6 * C54 );
L955: ( C54 |^ ( R6 " ) ) is (Subgroup of C54) by L952;
thus L956: ( R6 * C54 ) c= ( C54 * R6 ) by L955 , L954 , L29;
end;
thus L957: thesis by L953 , L877;
end;
theorem
L958: (for R5 being Group holds (for B55 being  strict (Subgroup of R5) holds (B55 is  normal  normal  normal  normal (Subgroup of R5) iff ( con_class B55 ) = { B55 })))
proof
let R5 being Group;
let C55 being  strict (Subgroup of R5);
thus L959: (C55 is  normal  normal  normal  normal (Subgroup of R5) implies ( con_class C55 ) = { C55 })
proof
assume L960: C55 is  normal  normal  normal  normal (Subgroup of R5);
thus L961: ( con_class C55 ) c= { C55 }
proof
let R1 being set;
assume L962: R1 in ( con_class C55 );
consider C56 being  strict (Subgroup of R5) such that L963: R1 = C56 and L964: C55 , C56 are_conjugated  by L962 , L786;
L965: (ex R10 being (Element of R5) st C56 = ( C55 |^ R10 )) by L964 , L766;
L966: R1 = C55 by L965 , L960 , L963 , L852;
thus L967: thesis by L966 , TARSKI:def 1;
end;

L968: C55 in ( con_class C55 ) by L811;
thus L969: thesis by L968 , ZFMISC_1:31;
end;

assume L970: ( con_class C55 ) = { C55 };
L971: C55 is  normal
proof
let R6 being (Element of R5);
L972: ( C55 |^ R6 ) in ( con_class C55 ) by L808;
thus L973: thesis by L972 , L970 , TARSKI:def 1;
end;
thus L974: thesis by L971;
end;
theorem
L975: (for R5 being Group holds (for B56 being  strict (Subgroup of R5) holds (B56 is  normal  normal  normal  normal (Subgroup of R5) iff (for R6 being (Element of R5) holds (R6 in B56 implies ( con_class R6 ) c= ( carr B56 ))))))
proof
let R5 being Group;
let C57 being  strict (Subgroup of R5);
thus L976: (C57 is  normal  normal  normal  normal (Subgroup of R5) implies (for R6 being (Element of R5) holds (R6 in C57 implies ( con_class R6 ) c= ( carr C57 ))))
proof
assume L977: C57 is  normal  normal  normal  normal (Subgroup of R5);
let R6 being (Element of R5);
assume L978: R6 in C57;
let R1 being set;
assume L979: R1 in ( con_class R6 );
consider R7 being (Element of R5) such that L980: R1 = R7 and L981: R6 , R7 are_conjugated  by L979 , L576;
consider R8 being (Element of R5) such that L982: R7 = ( R6 |^ R8 ) by L981 , L533;
L983: R1 in ( C57 |^ R8 ) by L978 , L980 , L982 , L374;
L984: R1 in C57 by L983 , L977 , L852;
thus L985: thesis by L984 , STRUCT_0:def 5;
end;

assume L986: (for R6 being (Element of R5) holds (R6 in C57 implies ( con_class R6 ) c= ( carr C57 )));
L987: C57 is  normal
proof
let R6 being (Element of R5);
L988: ( C57 |^ R6 ) = C57
proof
let R7 being (Element of R5);
thus L989: (R7 in ( C57 |^ R6 ) implies R7 in C57)
proof
assume L990: R7 in ( C57 |^ R6 );
consider R8 being (Element of R5) such that L991: (R7 = ( R8 |^ R6 ) & R8 in C57) by L990 , L374;
L992: (R7 in ( con_class R8 ) & ( con_class R8 ) c= ( carr C57 )) by L986 , L991 , L591;
thus L993: thesis by L992 , STRUCT_0:def 5;
end;

assume L994: R7 in C57;
L995: ( con_class R7 ) c= ( carr C57 ) by L994 , L986;
L996: ( R7 |^ ( R6 " ) ) in ( con_class R7 ) by L591;
L997: ( R7 |^ ( R6 " ) ) in C57 by L996 , L995 , STRUCT_0:def 5;
L998: ( ( R7 |^ ( R6 " ) ) |^ R6 ) in ( C57 |^ R6 ) by L997 , L374;
thus L999: thesis by L998 , L129;
end;
thus L1000: thesis by L988;
end;
thus L1001: thesis by L987;
end;
L1002: (for R5 being Group holds (for R23 being  normal (Subgroup of R5) holds (for B57 being  strict  normal (Subgroup of R5) holds ( ( carr B57 ) * ( carr R23 ) ) c= ( ( carr R23 ) * ( carr B57 ) ))))
proof
let R5 being Group;
let R23 being  normal (Subgroup of R5);
let C58 being  strict  normal (Subgroup of R5);
let R1 being set;
assume L1003: R1 in ( ( carr C58 ) * ( carr R23 ) );
consider R6 being (Element of R5), R7 being (Element of R5) such that L1004: R1 = ( R6 * R7 ) and L1005: R6 in ( carr C58 ) and L1006: R7 in ( carr R23 ) by L1003;
L1007: R6 in C58 by L1005 , STRUCT_0:def 5;
L1008: ( R6 |^ R7 ) in ( C58 |^ R7 ) by L1007 , L374;
L1009: ( R6 |^ R7 ) in ( the multMagma of C58 ) by L1008 , L852;
L1010: ( R6 |^ R7 ) in ( carr C58 ) by L1009 , STRUCT_0:def 5;
L1011: ( R7 * ( R6 |^ R7 ) ) = ( R7 * ( ( R7 " ) * ( R6 * R7 ) ) ) by GROUP_1:def 3
.= ( R6 * R7 ) by L1;
thus L1012: thesis by L1011 , L1004 , L1006 , L1010;
end;
theorem
L1013: (for R5 being Group holds (for B58 , B59 being  strict  normal (Subgroup of R5) holds ( ( carr B58 ) * ( carr B59 ) ) = ( ( carr B59 ) * ( carr B58 ) )))
proof
let R5 being Group;
let C59 , C60 being  strict  normal (Subgroup of R5);
L1014: (( ( carr C59 ) * ( carr C60 ) ) c= ( ( carr C60 ) * ( carr C59 ) ) & ( ( carr C60 ) * ( carr C59 ) ) c= ( ( carr C59 ) * ( carr C60 ) )) by L1002;
thus L1015: thesis by L1014 , XBOOLE_0:def 10;
end;
theorem
L1016: (for R5 being Group holds (for B60 , B61 being  strict  normal (Subgroup of R5) holds (ex B62 being  strict  normal (Subgroup of R5) st (the carrier of B62) = ( ( carr B60 ) * ( carr B61 ) ))))
proof
let R5 being Group;
let C61 , C62 being  strict  normal (Subgroup of R5);
set D39 = ( ( carr C61 ) * ( carr C62 ) );
set D40 = ( carr C61 );
set D41 = ( carr C62 );
L1017: ( ( carr C61 ) * ( carr C62 ) ) = ( ( carr C62 ) * ( carr C61 ) ) by L1013;
consider C63 being  strict (Subgroup of R5) such that L1018: (the carrier of C63) = D39 by L1017 , GROUP_2:78;
L1019:
now
let R6 being (Element of R5);
thus L1020: ( R6 * C63 ) = ( ( R6 * C61 ) * D41 ) by L1018 , GROUP_2:29
.= ( ( C61 * R6 ) * D41 ) by L866
.= ( D40 * ( R6 * C62 ) ) by GROUP_2:30
.= ( D40 * ( C62 * R6 ) ) by L866
.= ( C63 * R6 ) by L1018 , GROUP_2:31;
end;
L1021: C63 is  normal  normal  normal  normal (Subgroup of R5) by L1019 , L866;
thus L1022: thesis by L1021 , L1018;
end;
theorem
L1023: (for R5 being Group holds (for B63 being  normal (Subgroup of R5) holds ( Left_Cosets B63 ) = ( Right_Cosets B63 )))
proof
let R5 being Group;
let C64 being  normal (Subgroup of R5);
thus L1024: ( Left_Cosets C64 ) c= ( Right_Cosets C64 )
proof
let R1 being set;
assume L1025: R1 in ( Left_Cosets C64 );
consider R6 being (Element of R5) such that L1026: R1 = ( R6 * C64 ) by L1025 , GROUP_2:def 15;
L1027: R1 = ( C64 * R6 ) by L1026 , L866;
thus L1028: thesis by L1027 , GROUP_2:def 16;
end;

let R1 being set;
assume L1029: R1 in ( Right_Cosets C64 );
consider R6 being (Element of R5) such that L1030: R1 = ( C64 * R6 ) by L1029 , GROUP_2:def 16;
L1031: R1 = ( R6 * C64 ) by L1030 , L866;
thus L1032: thesis by L1031 , GROUP_2:def 15;
end;
theorem
L1033: (for R5 being Group holds (for B64 being (Subgroup of R5) holds ((( Left_Cosets B64 ) is  finite & ( index B64 ) = 2) implies B64 is  normal  normal  normal  normal (Subgroup of R5))))
proof
let R5 being Group;
let C65 being (Subgroup of R5);
assume that
L1034: ( Left_Cosets C65 ) is  finite
and
L1035: ( index C65 ) = 2;
L1036: (ex B65 being  finite set st (B65 = ( Left_Cosets C65 ) & ( index C65 ) = ( card B65 ))) by L1034 , GROUP_2:146;
consider R1 being set, R2 being set such that L1037: R1 <> R2 and L1038: ( Left_Cosets C65 ) = { R1 , R2 } by L1036 , L1035 , CARD_2:60;
L1039: ( carr C65 ) in ( Left_Cosets C65 ) by GROUP_2:135;
L1040: ({ R1 , R2 } = { R1 , ( carr C65 ) } or { R1 , R2 } = { ( carr C65 ) , R2 }) by L1039 , L1038 , TARSKI:def 2;
consider C66 being set such that L1041: { R1 , R2 } = { ( carr C65 ) , C66 } by L1040;
L1042: ( carr C65 ) misses C66
proof
L1043: C66 in ( Left_Cosets C65 ) by L1038 , L1041 , TARSKI:def 2;
L1044: (ex R6 being (Element of R5) st C66 = ( R6 * C65 )) by L1043 , GROUP_2:def 15;
L1045: ( carr C65 ) = ( ( 1_ R5 ) * C65 ) by GROUP_2:109;
assume L1046: (not thesis);
L1047: ( carr C65 ) = C66 by L1046 , L1044 , L1045 , GROUP_2:115;
L1048: { R1 , R2 } = { ( carr C65 ) } by L1047 , L1041 , ENUMSET1:29;
L1049: R1 = ( carr C65 ) by L1048 , ZFMISC_1:4;
thus L1050: thesis by L1049 , L1037 , L1048 , ZFMISC_1:4;
end;
L1051: (( union ( Left_Cosets C65 ) ) = (the carrier of R5) & ( union ( Left_Cosets C65 ) ) = ( ( carr C65 ) \/ C66 )) by L1038 , L1041 , GROUP_2:137 , ZFMISC_1:75;
L1052: (( union ( Right_Cosets C65 ) ) = (the carrier of R5) & C66 = ( (the carrier of R5) \ ( carr C65 ) )) by L1051 , L1042 , GROUP_2:137 , XBOOLE_1:88;
L1053: (ex B66 being  finite set st (B66 = ( Right_Cosets C65 ) & ( index C65 ) = ( card B66 ))) by L1034 , GROUP_2:146;
consider C67 , C68 being set such that L1054: C67 <> C68 and L1055: ( Right_Cosets C65 ) = { C67 , C68 } by L1053 , L1035 , CARD_2:60;
L1056: ( carr C65 ) in ( Right_Cosets C65 ) by GROUP_2:135;
L1057: ({ C67 , C68 } = { C67 , ( carr C65 ) } or { C67 , C68 } = { ( carr C65 ) , C68 }) by L1056 , L1055 , TARSKI:def 2;
consider C69 being set such that L1058: { C67 , C68 } = { ( carr C65 ) , C69 } by L1057;
L1059: ( carr C65 ) misses C69
proof
L1060: C69 in ( Right_Cosets C65 ) by L1055 , L1058 , TARSKI:def 2;
L1061: (ex R6 being (Element of R5) st C69 = ( C65 * R6 )) by L1060 , GROUP_2:def 16;
L1062: ( carr C65 ) = ( C65 * ( 1_ R5 ) ) by GROUP_2:109;
assume L1063: (not thesis);
L1064: ( carr C65 ) = C69 by L1063 , L1061 , L1062 , GROUP_2:121;
L1065: { C67 , C68 } = { ( carr C65 ) } by L1064 , L1058 , ENUMSET1:29;
L1066: C67 = ( carr C65 ) by L1065 , ZFMISC_1:4;
thus L1067: thesis by L1066 , L1054 , L1065 , ZFMISC_1:4;
end;
L1068: ( union ( Right_Cosets C65 ) ) = ( ( carr C65 ) \/ C69 ) by L1055 , L1058 , ZFMISC_1:75;
L1069:
now
let R8 being (Element of R5);
L1070:
now
per cases ;
suppose L1071: ( R8 * C65 ) = ( carr C65 );

L1072: R8 in C65 by L1071 , GROUP_2:113;
thus L1073: ( R8 * C65 ) = ( C65 * R8 ) by L1072 , L1071 , GROUP_2:119;
end;
suppose L1074: ( R8 * C65 ) <> ( carr C65 );

L1075: (not R8 in C65) by L1074 , GROUP_2:113;
L1076: ( C65 * R8 ) <> ( carr C65 ) by L1075 , GROUP_2:119;
L1077: ( R8 * C65 ) in ( Left_Cosets C65 ) by GROUP_2:def 15;
L1078: ( R8 * C65 ) = C66 by L1077 , L1038 , L1041 , L1074 , TARSKI:def 2;
L1079: ( C65 * R8 ) in ( Right_Cosets C65 ) by GROUP_2:def 16;
L1080: ( C65 * R8 ) = C69 by L1079 , L1055 , L1058 , L1076 , TARSKI:def 2;
thus L1081: ( R8 * C65 ) = ( C65 * R8 ) by L1080 , L1052 , L1068 , L1059 , L1078 , XBOOLE_1:88;
end;
end;
thus L1083: ( R8 * C65 ) = ( C65 * R8 ) by L1070;
end;
thus L1084: thesis by L1069 , L866;
end;
definition
let R5 being Group;
let R12 being (Subset of R5);
func Normalizer R12 ->  strict (Subgroup of R5) means 
:L1085: (the carrier of it) = { R11 where R11 is (Element of R5) : ( R12 |^ R11 ) = R12 };
existence
proof
set D42 = { R11 where R11 is (Element of R5) : ( R12 |^ R11 ) = R12 };
L1086: D42 c= (the carrier of R5)
proof
let R1 being set;
assume L1087: R1 in D42;
L1088: (ex R11 being (Element of R5) st (R1 = R11 & ( R12 |^ R11 ) = R12)) by L1087;
thus L1089: thesis by L1088;
end;
reconsider D43 = D42 as (Subset of R5) by L1086;
L1090:
now
let R6 being (Element of R5);
let R7 being (Element of R5);
assume L1091: (R6 in D43 & R7 in D43);
L1092: ((ex R10 being (Element of R5) st (R6 = R10 & ( R12 |^ R10 ) = R12)) & (ex R11 being (Element of R5) st (R7 = R11 & ( R12 |^ R11 ) = R12))) by L1091;
L1093: ( R12 |^ ( R6 * R7 ) ) = R12 by L1092 , L307;
thus L1094: ( R6 * R7 ) in D43 by L1093;
end;
L1095:
now
let R6 being (Element of R5);
assume L1096: R6 in D43;
L1097: (ex R7 being (Element of R5) st (R6 = R7 & ( R12 |^ R7 ) = R12)) by L1096;
L1098: R12 = ( R12 |^ ( R6 " ) ) by L1097 , L336;
thus L1099: ( R6 " ) in D43 by L1098;
end;
L1100: ( R12 |^ ( 1_ R5 ) ) = R12 by L323;
L1101: ( 1_ R5 ) in D43 by L1100;
thus L1102: thesis by L1101 , L1090 , L1095 , GROUP_2:52;
end;
uniqueness by GROUP_2:59;
end;
theorem
L1104: (for R1 being set holds (for R5 being Group holds (for R12 being (Subset of R5) holds (R1 in ( Normalizer R12 ) iff (ex R11 being (Element of R5) st (R1 = R11 & ( R12 |^ R11 ) = R12))))))
proof
let R1 being set;
let R5 being Group;
let R12 being (Subset of R5);
thus L1105: (R1 in ( Normalizer R12 ) implies (ex R11 being (Element of R5) st (R1 = R11 & ( R12 |^ R11 ) = R12)))
proof
assume L1106: R1 in ( Normalizer R12 );
L1107: R1 in (the carrier of ( Normalizer R12 )) by L1106 , STRUCT_0:def 5;
L1108: R1 in { R11 where R11 is (Element of R5) : ( R12 |^ R11 ) = R12 } by L1107 , L1085;
thus L1109: thesis by L1108;
end;

given R11 being (Element of R5) such that
L1110: (R1 = R11 & ( R12 |^ R11 ) = R12);

L1111: R1 in { R7 where R7 is (Element of R5) : ( R12 |^ R7 ) = R12 } by L1110;
L1112: R1 in (the carrier of ( Normalizer R12 )) by L1111 , L1085;
thus L1113: thesis by L1112 , STRUCT_0:def 5;
end;
theorem
L1114: (for R5 being Group holds (for R12 being (Subset of R5) holds ( card ( con_class R12 ) ) = ( Index ( Normalizer R12 ) )))
proof
let R5 being Group;
let R12 being (Subset of R5);
defpred S9[ set , set ] means (ex R6 being (Element of R5) st ($1 = ( R12 |^ R6 ) & $2 = ( ( Normalizer R12 ) * R6 )));
L1115: (for R1 being set holds (R1 in ( con_class R12 ) implies (ex R2 being set st S9[ R1 , R2 ])))
proof
let R1 being set;
assume L1116: R1 in ( con_class R12 );
consider R13 being (Subset of R5) such that L1117: R1 = R13 and L1118: R12 , R13 are_conjugated  by L1116;
consider R10 being (Element of R5) such that L1119: R13 = ( R12 |^ R10 ) by L1118 , L663;
reconsider D44 = ( ( Normalizer R12 ) * R10 ) as set;
take D44;
take R10;
thus L1120: thesis by L1117 , L1119;
end;
consider C70 being Function such that L1121: ( dom C70 ) = ( con_class R12 ) and L1122: (for R1 being set holds (R1 in ( con_class R12 ) implies S9[ R1 , ( C70 . R1 ) ])) from CLASSES1:sch 1(L1115);
L1123: (for R1 being set holds (for R3 being set holds (for R4 being set holds ((R1 in ( con_class R12 ) & S9[ R1 , R3 ] & S9[ R1 , R4 ]) implies R3 = R4))))
proof
let R1 being set;
let R3 being set;
let R4 being set;
assume L1124: R1 in ( con_class R12 );
given R6 being (Element of R5) such that
L1125: R1 = ( R12 |^ R6 )
and
L1126: R3 = ( ( Normalizer R12 ) * R6 );

given R7 being (Element of R5) such that
L1127: R1 = ( R12 |^ R7 )
and
L1128: R4 = ( ( Normalizer R12 ) * R7 );

L1129: R12 = ( ( R12 |^ R7 ) |^ ( R6 " ) ) by L1125 , L1127 , L336
.= ( R12 |^ ( R7 * ( R6 " ) ) ) by L307;
L1130: ( R7 * ( R6 " ) ) in ( Normalizer R12 ) by L1129 , L1104;
thus L1131: thesis by L1130 , L1126 , L1128 , GROUP_2:120;
end;
L1132: ( rng C70 ) = ( Right_Cosets ( Normalizer R12 ) )
proof
thus L1133: ( rng C70 ) c= ( Right_Cosets ( Normalizer R12 ) )
proof
let R1 being set;
assume L1134: R1 in ( rng C70 );
consider R2 being set such that L1135: (R2 in ( dom C70 ) & ( C70 . R2 ) = R1) by L1134 , FUNCT_1:def 3;
L1136: (ex R6 being (Element of R5) st (R2 = ( R12 |^ R6 ) & R1 = ( ( Normalizer R12 ) * R6 ))) by L1121 , L1122 , L1135;
thus L1137: thesis by L1136 , GROUP_2:def 16;
end;

let R1 being set;
assume L1138: R1 in ( Right_Cosets ( Normalizer R12 ) );
consider R6 being (Element of R5) such that L1139: R1 = ( ( Normalizer R12 ) * R6 ) by L1138 , GROUP_2:def 16;
set D45 = ( R12 |^ R6 );
L1140: R12 , ( R12 |^ R6 ) are_conjugated  by L663;
L1141: D45 in ( con_class R12 ) by L1140;
L1142: (ex R7 being (Element of R5) st (D45 = ( R12 |^ R7 ) & ( C70 . D45 ) = ( ( Normalizer R12 ) * R7 ))) by L1141 , L1122;
L1143: R1 = ( C70 . D45 ) by L1142 , L1123 , L1139 , L1141;
thus L1144: thesis by L1143 , L1121 , L1141 , FUNCT_1:def 3;
end;
L1145: C70 is  one-to-one
proof
let R1 being set;
let R2 being set;
assume that
L1146: R1 in ( dom C70 )
and
L1147: R2 in ( dom C70 )
and
L1148: ( C70 . R1 ) = ( C70 . R2 );
consider R7 being (Element of R5) such that L1149: R2 = ( R12 |^ R7 ) and L1150: ( C70 . R2 ) = ( ( Normalizer R12 ) * R7 ) by L1121 , L1122 , L1147;
consider R6 being (Element of R5) such that L1151: R1 = ( R12 |^ R6 ) and L1152: ( C70 . R1 ) = ( ( Normalizer R12 ) * R6 ) by L1121 , L1122 , L1146;
L1153: ( R7 * ( R6 " ) ) in ( Normalizer R12 ) by L1148 , L1152 , L1150 , GROUP_2:120;
L1154: (ex R11 being (Element of R5) st (( R7 * ( R6 " ) ) = R11 & ( R12 |^ R11 ) = R12)) by L1153 , L1104;
L1155: R12 = ( ( R12 |^ R7 ) |^ ( R6 " ) ) by L1154 , L307;
thus L1156: thesis by L1155 , L1151 , L1149 , L336;
end;
L1157: ( con_class R12 ) , ( Right_Cosets ( Normalizer R12 ) ) are_equipotent  by L1145 , L1121 , L1132 , WELLORD2:def 4;
thus L1158: ( card ( con_class R12 ) ) = ( card ( Right_Cosets ( Normalizer R12 ) ) ) by L1157 , CARD_1:5
.= ( Index ( Normalizer R12 ) ) by GROUP_2:145;
end;
theorem
L1159: (for R5 being Group holds (for R12 being (Subset of R5) holds ((( con_class R12 ) is  finite or ( Left_Cosets ( Normalizer R12 ) ) is  finite) implies (ex B67 being  finite set st (B67 = ( con_class R12 ) & ( card B67 ) = ( index ( Normalizer R12 ) ))))))
proof
let R5 being Group;
let R12 being (Subset of R5);
L1160: ( card ( con_class R12 ) ) = ( Index ( Normalizer R12 ) ) by L1114
.= ( card ( Left_Cosets ( Normalizer R12 ) ) );
L1161: ( con_class R12 ) , ( Left_Cosets ( Normalizer R12 ) ) are_equipotent  by L1160 , CARD_1:5;
assume L1162: (( con_class R12 ) is  finite or ( Left_Cosets ( Normalizer R12 ) ) is  finite);
reconsider D46 = ( con_class R12 ) as  finite set by L1162 , L1161 , CARD_1:38;
take D46;
thus L1163: D46 = ( con_class R12 );
L1164: ( Left_Cosets ( Normalizer R12 ) ) is  finite by L1162 , L1161 , CARD_1:38;
thus L1165: thesis by L1164 , L1160 , GROUP_2:def 18;
end;
theorem
L1166: (for R5 being Group holds (for R6 being (Element of R5) holds ( card ( con_class R6 ) ) = ( Index ( Normalizer { R6 } ) )))
proof
let R5 being Group;
let R6 being (Element of R5);
deffunc H2(set) = { $1 };
consider C71 being Function such that L1167: ( dom C71 ) = ( con_class R6 ) and L1168: (for R1 being set holds (R1 in ( con_class R6 ) implies ( C71 . R1 ) = H2(R1))) from FUNCT_1:sch 3;
L1169: ( rng C71 ) = ( con_class { R6 } )
proof
thus L1170: ( rng C71 ) c= ( con_class { R6 } )
proof
let R1 being set;
assume L1171: R1 in ( rng C71 );
consider R2 being set such that L1172: R2 in ( dom C71 ) and L1173: ( C71 . R2 ) = R1 by L1171 , FUNCT_1:def 3;
reconsider D47 = R2 as (Element of R5) by L1167 , L1172;
L1174: ( C71 . D47 ) = { D47 } by L1167 , L1168 , L1172;
L1175: R1 in { { R9 } where R9 is (Element of R5) : R9 in ( con_class R6 ) } by L1174 , L1167 , L1172 , L1173;
thus L1176: thesis by L1175 , L746;
end;

let R1 being set;
assume L1177: R1 in ( con_class { R6 } );
L1178: R1 in { { R7 } where R7 is (Element of R5) : R7 in ( con_class R6 ) } by L1177 , L746;
consider R7 being (Element of R5) such that L1179: R1 = { R7 } and L1180: R7 in ( con_class R6 ) by L1178;
L1181: ( C71 . R7 ) = { R7 } by L1168 , L1180;
thus L1182: thesis by L1181 , L1167 , L1179 , L1180 , FUNCT_1:def 3;
end;
L1183: C71 is  one-to-one
proof
let R1 being set;
let R2 being set;
assume that
L1184: (R1 in ( dom C71 ) & R2 in ( dom C71 ))
and
L1185: ( C71 . R1 ) = ( C71 . R2 );
L1186: (( C71 . R1 ) = { R1 } & ( C71 . R2 ) = { R2 }) by L1167 , L1168 , L1184;
thus L1187: thesis by L1186 , L1185 , ZFMISC_1:3;
end;
L1188: ( con_class R6 ) , ( con_class { R6 } ) are_equipotent  by L1183 , L1167 , L1169 , WELLORD2:def 4;
thus L1189: ( card ( con_class R6 ) ) = ( card ( con_class { R6 } ) ) by L1188 , CARD_1:5
.= ( Index ( Normalizer { R6 } ) ) by L1114;
end;
theorem
L1190: (for R5 being Group holds (for R6 being (Element of R5) holds ((( con_class R6 ) is  finite or ( Left_Cosets ( Normalizer { R6 } ) ) is  finite) implies (ex B68 being  finite set st (B68 = ( con_class R6 ) & ( card B68 ) = ( index ( Normalizer { R6 } ) ))))))
proof
let R5 being Group;
let R6 being (Element of R5);
L1191: ( card ( con_class R6 ) ) = ( Index ( Normalizer { R6 } ) ) by L1166
.= ( card ( Left_Cosets ( Normalizer { R6 } ) ) );
L1192: ( con_class R6 ) , ( Left_Cosets ( Normalizer { R6 } ) ) are_equipotent  by L1191 , CARD_1:5;
assume L1193: (( con_class R6 ) is  finite or ( Left_Cosets ( Normalizer { R6 } ) ) is  finite);
reconsider D48 = ( con_class R6 ) as  finite set by L1193 , L1192 , CARD_1:38;
take D48;
thus L1194: D48 = ( con_class R6 );
L1195: ( Left_Cosets ( Normalizer { R6 } ) ) is  finite by L1193 , L1192 , CARD_1:38;
thus L1196: thesis by L1195 , L1191 , GROUP_2:def 18;
end;
definition
let R5 being Group;
let R16 being (Subgroup of R5);
func Normalizer R16 ->  strict (Subgroup of R5) equals 
( Normalizer ( carr R16 ) );
correctness;
end;
theorem
L1198: (for R1 being set holds (for R5 being Group holds (for B69 being  strict (Subgroup of R5) holds (R1 in ( Normalizer B69 ) iff (ex R11 being (Element of R5) st (R1 = R11 & ( B69 |^ R11 ) = B69))))))
proof
let R1 being set;
let R5 being Group;
let C72 being  strict (Subgroup of R5);
thus L1199: (R1 in ( Normalizer C72 ) implies (ex R11 being (Element of R5) st (R1 = R11 & ( C72 |^ R11 ) = C72)))
proof
assume L1200: R1 in ( Normalizer C72 );
consider R6 being (Element of R5) such that L1201: R1 = R6 and L1202: ( ( carr C72 ) |^ R6 ) = ( carr C72 ) by L1200 , L1104;
L1203: ( C72 |^ R6 ) = C72 by L1202 , L369;
thus L1204: thesis by L1203 , L1201;
end;

given R11 being (Element of R5) such that
L1205: R1 = R11
and
L1206: ( C72 |^ R11 ) = C72;

L1207: ( ( carr C72 ) |^ R11 ) = ( carr C72 ) by L1206 , L369;
thus L1208: thesis by L1207 , L1205 , L1104;
end;
theorem
L1209: (for R5 being Group holds (for B70 being  strict (Subgroup of R5) holds ( card ( con_class B70 ) ) = ( Index ( Normalizer B70 ) )))
proof
let R5 being Group;
let C73 being  strict (Subgroup of R5);
defpred S10[ set , set ] means (ex B71 being  strict (Subgroup of R5) st ($1 = B71 & $2 = ( carr B71 )));
L1210: (for R1 being set holds (R1 in ( con_class C73 ) implies (ex R2 being set st S10[ R1 , R2 ])))
proof
let R1 being set;
assume L1211: R1 in ( con_class C73 );
reconsider D49 = R1 as  strict (Subgroup of R5) by L1211 , L44;
reconsider D50 = ( carr D49 ) as set;
take D50;
take D49;
thus L1212: thesis;
end;
consider C74 being Function such that L1213: ( dom C74 ) = ( con_class C73 ) and L1214: (for R1 being set holds (R1 in ( con_class C73 ) implies S10[ R1 , ( C74 . R1 ) ])) from CLASSES1:sch 1(L1210);
L1215: ( rng C74 ) = ( con_class ( carr C73 ) )
proof
thus L1216: ( rng C74 ) c= ( con_class ( carr C73 ) )
proof
let R1 being set;
assume L1217: R1 in ( rng C74 );
consider R2 being set such that L1218: R2 in ( dom C74 ) and L1219: ( C74 . R2 ) = R1 by L1217 , FUNCT_1:def 3;
consider C75 being  strict (Subgroup of R5) such that L1220: R2 = C75 and L1221: R1 = ( carr C75 ) by L1213 , L1214 , L1218 , L1219;
L1222: C75 , C73 are_conjugated  by L1213 , L1218 , L1220 , L801;
L1223: ( carr C75 ) , ( carr C73 ) are_conjugated  by L1222 , L844;
thus L1224: thesis by L1223 , L1221;
end;

let R1 being set;
assume L1225: R1 in ( con_class ( carr C73 ) );
consider R13 being (Subset of R5) such that L1226: R13 = R1 and L1227: ( carr C73 ) , R13 are_conjugated  by L1225;
consider C76 being  strict (Subgroup of R5) such that L1228: (the carrier of C76) = R13 by L1227 , L694;
L1229: R13 = ( carr C76 ) by L1228;
L1230: C76 , C73 are_conjugated  by L1229 , L1227 , L844;
L1231: C76 in ( con_class C73 ) by L1230 , L801;
L1232: (ex B72 being  strict (Subgroup of R5) st (C76 = B72 & ( C74 . C76 ) = ( carr B72 ))) by L1231 , L1214;
thus L1233: thesis by L1232 , L1213 , L1226 , L1228 , L1231 , FUNCT_1:def 3;
end;
L1234: C74 is  one-to-one
proof
let R1 being set;
let R2 being set;
assume that
L1235: (R1 in ( dom C74 ) & R2 in ( dom C74 ))
and
L1236: ( C74 . R1 ) = ( C74 . R2 );
L1237: ((ex B73 being  strict (Subgroup of R5) st (R1 = B73 & ( C74 . R1 ) = ( carr B73 ))) & (ex B74 being  strict (Subgroup of R5) st (R2 = B74 & ( C74 . R2 ) = ( carr B74 )))) by L1213 , L1214 , L1235;
thus L1238: thesis by L1237 , L1236 , GROUP_2:59;
end;
L1239: ( con_class C73 ) , ( con_class ( carr C73 ) ) are_equipotent  by L1234 , L1213 , L1215 , WELLORD2:def 4;
thus L1240: ( card ( con_class C73 ) ) = ( card ( con_class ( carr C73 ) ) ) by L1239 , CARD_1:5
.= ( Index ( Normalizer C73 ) ) by L1114;
end;
theorem
L1241: (for R5 being Group holds (for B75 being  strict (Subgroup of R5) holds ((( con_class B75 ) is  finite or ( Left_Cosets ( Normalizer B75 ) ) is  finite) implies (ex B76 being  finite set st (B76 = ( con_class B75 ) & ( card B76 ) = ( index ( Normalizer B75 ) ))))))
proof
let R5 being Group;
let C77 being  strict (Subgroup of R5);
L1242: ( card ( con_class C77 ) ) = ( Index ( Normalizer C77 ) ) by L1209
.= ( card ( Left_Cosets ( Normalizer C77 ) ) );
L1243: ( con_class C77 ) , ( Left_Cosets ( Normalizer C77 ) ) are_equipotent  by L1242 , CARD_1:5;
assume L1244: (( con_class C77 ) is  finite or ( Left_Cosets ( Normalizer C77 ) ) is  finite);
reconsider D51 = ( con_class C77 ) as  finite set by L1244 , L1243 , CARD_1:38;
take D51;
thus L1245: D51 = ( con_class C77 );
L1246: ( Left_Cosets ( Normalizer C77 ) ) is  finite by L1244 , L1243 , CARD_1:38;
thus L1247: thesis by L1246 , L1242 , GROUP_2:def 18;
end;
theorem
L1248: (for B77 being  strict Group holds (for B78 being  strict (Subgroup of B77) holds (B78 is  normal  normal  normal  normal (Subgroup of B77) iff ( Normalizer B78 ) = B77)))
proof
let C78 being  strict Group;
let C79 being  strict (Subgroup of C78);
thus L1249: (C79 is  normal  normal  normal  normal (Subgroup of C78) implies ( Normalizer C79 ) = C78)
proof
assume L1250: C79 is  normal  normal  normal  normal (Subgroup of C78);
L1251:
now
let C80 being (Element of C78);
L1252: ( C79 |^ C80 ) = C79 by L1250 , L852;
thus L1253: C80 in ( Normalizer C79 ) by L1252 , L1198;
end;
thus L1254: thesis by L1251 , GROUP_2:62;
end;

assume L1255: ( Normalizer C79 ) = C78;
L1256: C79 is  normal
proof
let C81 being (Element of C78);
L1257: C81 in ( Normalizer C79 ) by L1255 , STRUCT_0:def 5;
L1258: (ex B79 being (Element of C78) st (B79 = C81 & ( C79 |^ B79 ) = C79)) by L1257 , L1198;
thus L1259: thesis by L1258;
end;
thus L1260: thesis by L1256;
end;
theorem
L1261: (for B80 being  strict Group holds ( Normalizer ( (1). B80 ) ) = B80)
proof
let C82 being  strict Group;
L1262: ( (1). C82 ) is  normal  normal  normal  normal (Subgroup of C82) by L858;
thus L1263: thesis by L1262 , L1248;
end;
theorem
L1264: (for B81 being  strict Group holds ( Normalizer ( (Omega). B81 ) ) = B81)
proof
let C83 being  strict Group;
L1265: ( (Omega). C83 ) is  normal  normal  normal  normal (Subgroup of C83) by L858;
thus L1266: thesis by L1265 , L1248;
end;
