:: On Rough Subgroup of a Group
::  by Xiquan Liang and Dailu Li
::
:: Received August 7, 2009
:: Copyright (c) 2009-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies GROUP_1, XBOOLE_0, SUBSET_1, GROUP_2, PRE_TOPC, RELAT_1, TARSKI,
      STRUCT_0;
 notations TARSKI, XBOOLE_0, SUBSET_1, STRUCT_0, ALGSTR_0, GROUP_1, GROUP_2,
      GROUP_3, GROUP_4;
 constructors REALSET2, GROUP_4;
 registrations XBOOLE_0, STRUCT_0, GROUP_1, GROUP_2, GROUP_3;
 requirements SUBSET, BOOLE;
 definitions XBOOLE_0, GROUP_2, TARSKI, GROUP_4;
 theorems GROUP_1, GROUP_8, GROUP_2, GROUP_3, XBOOLE_0, XBOOLE_1, GROUP_4,
      STRUCT_0;

begin
theorem
L1: (for R1 being Group holds (for B1 being  normal (Subgroup of R1) holds (for B2 , B3 being (Element of R1) holds ( ( B2 * B1 ) * ( B3 * B1 ) ) = ( ( B2 * B3 ) * B1 ))))
proof
let R1 being Group;
let C1 being  normal (Subgroup of R1);
let C2 , C3 being (Element of R1);
L2: ( ( C2 * C1 ) * ( C3 * C1 ) ) = ( ( ( C2 * C1 ) * C3 ) * C1 ) by GROUP_2:10
.= ( ( C2 * ( C1 * C3 ) ) * C1 ) by GROUP_2:29
.= ( ( C2 * ( C3 * C1 ) ) * C1 ) by GROUP_3:117
.= ( ( ( C2 * C3 ) * C1 ) * C1 ) by GROUP_2:105
.= ( ( C2 * C3 ) * ( C1 * C1 ) ) by GROUP_2:29;
thus L3: thesis by L2 , GROUP_2:76;
end;
theorem
L4: (for B4 being Group holds (for B5 being (Subgroup of B4) holds (for B6 , B7 being (Element of B4) holds (B7 in ( B6 * B5 ) implies ( B6 * B5 ) = ( B7 * B5 )))))
proof
let C4 being Group;
let C5 being (Subgroup of C4);
let C6 , C7 being (Element of C4);
assume L5: C7 in ( C6 * C5 );
L6: C7 in ( C7 * C5 ) by GROUP_2:108;
L7: ( C6 * C5 ) meets ( C7 * C5 ) by L6 , L5 , XBOOLE_0:3;
thus L8: thesis by L7 , GROUP_2:115;
end;
theorem
L9: (for R1 being Group holds (for B8 being (Subgroup of R1) holds (for B9 being (Subgroup of R1) holds (for B10 being (Element of R1) holds (( B10 * B8 ) meets ( carr B9 ) implies (ex B11 being (Element of R1) st (B11 in ( B10 * B8 ) & B11 in B9)))))))
proof
let R1 being Group;
let C8 being (Subgroup of R1);
let C9 being (Subgroup of R1);
let C10 being (Element of R1);
assume L10: ( C10 * C8 ) meets ( carr C9 );
consider C11 being set such that L11: (C11 in ( C10 * C8 ) & C11 in ( carr C9 )) by L10 , XBOOLE_0:3;
reconsider D1 = C11 as (Element of R1) by L11;
L12: D1 in C9 by L11 , STRUCT_0:def 5;
thus L13: thesis by L12 , L11;
end;
theorem
L14: (for R1 being Group holds (for B12 , B13 being (Element of R1) holds (for B14 being  normal (Subgroup of R1) holds (B13 in B14 implies ( ( B12 * B13 ) * ( B12 " ) ) in B14))))
proof
let R1 being Group;
let C12 , C13 being (Element of R1);
let C14 being  normal (Subgroup of R1);
assume L15: C13 in C14;
L16: ( C12 * C13 ) in ( C12 * C14 ) by L15 , GROUP_2:103;
L17: ( C12 * C13 ) in ( C14 * C12 ) by L16 , GROUP_3:117;
consider C15 being (Element of R1) such that L18: (( C12 * C13 ) = ( C15 * C12 ) & C15 in C14) by L17 , GROUP_2:104;
L19: ( ( C12 * C13 ) * ( C12 " ) ) = ( C15 * ( C12 * ( C12 " ) ) ) by L18 , GROUP_1:def 3
.= ( C15 * ( 1_ R1 ) ) by GROUP_1:def 5
.= C15 by GROUP_1:def 4;
thus L20: thesis by L19 , L18;
end;
theorem
L21: (for R1 being Group holds (for B15 being (Subgroup of R1) holds ((for B16 , B17 being (Element of R1) holds (B17 in B15 implies ( ( B16 * B17 ) * ( B16 " ) ) in B15)) implies B15 is  normal)))
proof
let R1 being Group;
let C16 being (Subgroup of R1);
assume that
L22: (for B18 , B19 being (Element of R1) holds (B19 in C16 implies ( ( B18 * B19 ) * ( B18 " ) ) in C16));
L23: (for B20 being (Element of R1) holds ( B20 * C16 ) c= ( C16 * B20 ))
proof
let C17 being (Element of R1);
let C18 being set;
assume L24: C18 in ( C17 * C16 );
reconsider D2 = C18 as (Element of R1) by L24;
consider C19 being (Element of R1) such that L25: (D2 = ( C17 * C19 ) & C19 in C16) by L24 , GROUP_2:103;
L26: ( ( C17 * C19 ) * ( C17 " ) ) in C16 by L22 , L25;
L27: ( ( ( C17 * C19 ) * ( C17 " ) ) * C17 ) = D2 by L25 , GROUP_3:1;
thus L28: thesis by L27 , L26 , GROUP_2:104;
end;
thus L29: thesis by L23 , GROUP_3:118;
end;
theorem
L30: (for R1 being Group holds (for R6 being (Subgroup of R1) holds (for R7 being (Subgroup of R1) holds (for R8 being (Element of R1) holds (R8 in ( R6 * R7 ) iff (ex R9 being (Element of R1) st (ex R10 being (Element of R1) st (R8 = ( R9 * R10 ) & R9 in R6 & R10 in R7))))))))
proof
let R1 being Group;
let R6 being (Subgroup of R1);
let R7 being (Subgroup of R1);
let R8 being (Element of R1);
thus L31: (R8 in ( R6 * R7 ) implies (ex R9 being (Element of R1) st (ex R10 being (Element of R1) st (R8 = ( R9 * R10 ) & R9 in R6 & R10 in R7))))
proof
assume L32: R8 in ( R6 * R7 );
consider R9 being (Element of R1), R10 being (Element of R1) such that L33: (R8 = ( R9 * R10 ) & R9 in ( carr R6 ) & R10 in ( carr R7 )) by L32;
L34: (R9 in R6 & R10 in R7) by L33 , STRUCT_0:def 5;
thus L35: thesis by L34 , L33;
end;

given R9 being (Element of R1) , R10 being (Element of R1) such that
L36: (R8 = ( R9 * R10 ) & R9 in R6 & R10 in R7);

L37: (R9 in ( carr R6 ) & R10 in ( carr R7 )) by L36 , STRUCT_0:def 5;
thus L38: thesis by L37 , L36;
end;
theorem
L39: (for B21 being Group holds (for B22 , B23 being  strict  normal (Subgroup of B21) holds (ex B24 being  strict (Subgroup of B21) st (the carrier of B24) = ( B22 * B23 ))))
proof
let C20 being Group;
let C21 , C22 being  strict  normal (Subgroup of C20);
L40: ( 1_ C20 ) in ( C21 * C22 )
proof
L41: (( 1_ C20 ) in C21 & ( 1_ C20 ) in C22) by GROUP_2:46;
L42: ( ( 1_ C20 ) * ( 1_ C20 ) ) = ( 1_ C20 ) by GROUP_1:def 4;
thus L43: thesis by L42 , L41 , L30;
end;
L44: (for B25 , B26 being (Element of C20) holds ((B25 in ( C21 * C22 ) & B26 in ( C21 * C22 )) implies ( B25 * B26 ) in ( C21 * C22 )))
proof
let C23 , C24 being (Element of C20);
assume that
L45: C23 in ( C21 * C22 )
and
L46: C24 in ( C21 * C22 );
consider C25 , C26 being (Element of C20) such that L47: (C23 = ( C25 * C26 ) & C25 in C21 & C26 in C22) by L45 , L30;
consider C27 , C28 being (Element of C20) such that L48: (C24 = ( C27 * C28 ) & C27 in C21 & C28 in C22) by L46 , L30;
L49: ( C23 * C24 ) = ( ( ( C25 * C26 ) * C27 ) * C28 ) by L47 , L48 , GROUP_1:def 3
.= ( ( C25 * ( C26 * C27 ) ) * C28 ) by GROUP_1:def 3;
L50: ( C26 * C27 ) in ( C22 * C21 ) by L47 , L48 , L30;
L51: ( C26 * C27 ) in ( C21 * C22 ) by L50 , GROUP_3:125;
consider C29 , C30 being (Element of C20) such that L52: (( C26 * C27 ) = ( C29 * C30 ) & C29 in C21 & C30 in C22) by L51 , L30;
L53: ( C23 * C24 ) = ( ( ( C25 * C29 ) * C30 ) * C28 ) by L49 , L52 , GROUP_1:def 3
.= ( ( C25 * C29 ) * ( C30 * C28 ) ) by GROUP_1:def 3;
L54: ( C25 * C29 ) in C21 by L47 , L52 , GROUP_2:50;
L55: ( C30 * C28 ) in C22 by L48 , L52 , GROUP_2:50;
thus L56: thesis by L55 , L53 , L54 , L30;
end;
L57: (for B27 being (Element of C20) holds (B27 in ( C21 * C22 ) implies ( B27 " ) in ( C21 * C22 )))
proof
let C31 being (Element of C20);
assume L58: C31 in ( C21 * C22 );
consider C32 , C33 being (Element of C20) such that L59: (C31 = ( C32 * C33 ) & C32 in C21 & C33 in C22) by L58 , L30;
L60: ( C31 " ) = ( ( C33 " ) * ( C32 " ) ) by L59 , GROUP_1:17;
L61: (( C33 " ) in C22 & ( C32 " ) in C21) by L59 , GROUP_2:51;
L62: ( C31 " ) in ( C22 * C21 ) by L61 , L60 , L30;
thus L63: thesis by L62 , GROUP_3:125;
end;
thus L64: thesis by L57 , L40 , L44 , GROUP_2:52;
end;
theorem
L65: (for B28 being Group holds (for B29 , B30 being  strict  normal (Subgroup of B28) holds (ex B31 being  strict  normal (Subgroup of B28) st (the carrier of B31) = ( B29 * B30 ))))
proof
let C34 being Group;
let C35 , C36 being  strict  normal (Subgroup of C34);
consider C37 being  strict (Subgroup of C34) such that L66: (the carrier of C37) = ( C35 * C36 ) by L39;
L67: (for B32 , B33 being (Element of C34) holds (B33 in C37 implies ( ( B32 * B33 ) * ( B32 " ) ) in C37))
proof
let C38 , C39 being (Element of C34);
assume L68: C39 in C37;
L69: C39 in (the carrier of C37) by L68 , STRUCT_0:def 5;
consider C40 , C41 being (Element of C34) such that L70: (C39 = ( C40 * C41 ) & C40 in C35 & C41 in C36) by L69 , L66 , L30;
L71: ( ( C38 * C39 ) * ( C38 " ) ) = ( ( ( C38 * C40 ) * C41 ) * ( C38 " ) ) by L70 , GROUP_1:def 3
.= ( ( C38 * C40 ) * ( C41 * ( C38 " ) ) ) by GROUP_1:def 3
.= ( ( ( C38 * C40 ) * ( 1_ C34 ) ) * ( C41 * ( C38 " ) ) ) by GROUP_1:def 4
.= ( ( ( C38 * C40 ) * ( ( C38 " ) * C38 ) ) * ( C41 * ( C38 " ) ) ) by GROUP_1:def 5
.= ( ( ( ( C38 * C40 ) * ( C38 " ) ) * C38 ) * ( C41 * ( C38 " ) ) ) by GROUP_1:def 3
.= ( ( ( C38 * C40 ) * ( C38 " ) ) * ( C38 * ( C41 * ( C38 " ) ) ) ) by GROUP_1:def 3
.= ( ( ( C38 * C40 ) * ( C38 " ) ) * ( ( C38 * C41 ) * ( C38 " ) ) ) by GROUP_1:def 3;
L72: (( ( C38 * C40 ) * ( C38 " ) ) in C35 & ( ( C38 * C41 ) * ( C38 " ) ) in C36) by L70 , L14;
L73: ( ( C38 * C39 ) * ( C38 " ) ) in ( C35 * C36 ) by L72 , L71 , L30;
thus L74: thesis by L73 , L66 , STRUCT_0:def 5;
end;
L75: C37 is  normal  normal  normal  normal (Subgroup of C34) by L67 , L21;
thus L76: thesis by L75 , L66;
end;
theorem
L77: (for B34 being Group holds (for B35 , B36 , B37 being (Subgroup of B34) holds ((the carrier of B35) = ( B36 * B37 ) implies (B36 is (Subgroup of B35) & B37 is (Subgroup of B35)))))
proof
let C42 being Group;
let C43 , C44 , C45 being (Subgroup of C42);
assume L78: (the carrier of C43) = ( C44 * C45 );
L79: (for B38 being (Element of C42) holds (B38 in C44 implies B38 in C43))
proof
let C46 being (Element of C42);
assume L80: C46 in C44;
L81: ( 1_ C42 ) in C45 by GROUP_2:46;
L82: C46 = ( C46 * ( 1_ C42 ) ) by GROUP_1:def 4;
L83: C46 in ( C44 * C45 ) by L82 , L80 , L81 , L30;
thus L84: thesis by L83 , L78 , STRUCT_0:def 5;
end;
thus L85: C44 is (Subgroup of C43) by L79 , GROUP_2:58;
L86: (for B39 being (Element of C42) holds (B39 in C45 implies B39 in C43))
proof
let C47 being (Element of C42);
assume L87: C47 in C45;
L88: ( 1_ C42 ) in C44 by GROUP_2:46;
L89: C47 = ( ( 1_ C42 ) * C47 ) by GROUP_1:def 4;
L90: C47 in ( C44 * C45 ) by L89 , L87 , L88 , L30;
thus L91: thesis by L90 , L78 , STRUCT_0:def 5;
end;
thus L92: C45 is (Subgroup of C43) by L86 , GROUP_2:58;
end;
theorem
L93: (for R1 being Group holds (for B40 , B41 , B42 being  normal (Subgroup of R1) holds (for B43 , B44 being (Element of R1) holds ((the carrier of B40) = ( B41 * B42 ) implies ( ( B43 * B41 ) * ( B44 * B42 ) ) = ( ( B43 * B44 ) * B40 )))))
proof
let R1 being Group;
let C48 , C49 , C50 being  normal (Subgroup of R1);
let C51 , C52 being (Element of R1);
assume L94: (the carrier of C48) = ( C49 * C50 );
L95: ( ( C51 * C49 ) * ( C52 * C50 ) ) = ( ( ( C51 * C49 ) * C52 ) * C50 ) by GROUP_2:10
.= ( ( C51 * ( C49 * C52 ) ) * C50 ) by GROUP_2:29
.= ( ( C51 * ( C52 * C49 ) ) * C50 ) by GROUP_3:117
.= ( ( ( C51 * C52 ) * C49 ) * C50 ) by GROUP_2:105
.= ( ( C51 * C52 ) * ( C49 * C50 ) ) by GROUP_4:45;
thus L96: thesis by L95 , L94;
end;
theorem
L97: (for R1 being Group holds (for B45 being  normal (Subgroup of R1) holds (for R8 being (Element of R1) holds ( ( R8 * B45 ) * ( R8 " ) ) c= ( carr B45 ))))
proof
let R1 being Group;
let C53 being  normal (Subgroup of R1);
let R8 being (Element of R1);
L98: ( R8 * C53 ) c= ( C53 * R8 ) by GROUP_3:118;
L99: ( ( R8 * C53 ) * ( R8 " ) ) c= ( ( C53 * R8 ) * ( R8 " ) ) by L98 , GROUP_3:5;
L100: ( ( C53 * R8 ) * ( R8 " ) ) = ( C53 * ( R8 * ( R8 " ) ) ) by GROUP_2:107
.= ( C53 * ( 1_ R1 ) ) by GROUP_1:def 5;
thus L101: thesis by L100 , L99 , GROUP_2:109;
end;
definition
let C54 being Group;
let C55 being (Subset of C54);
let C56 being (Subgroup of C54);
func C56 ` C55 -> (Subset of C54) equals 
{ B46 where B46 is (Element of C54) : ( B46 * C56 ) c= C55 };
correctness
proof
L102: { B47 where B47 is (Element of C54) : ( B47 * C56 ) c= C55 } c= (the carrier of C54)
proof
let C57 being set;
assume L103: C57 in { B48 where B48 is (Element of C54) : ( B48 * C56 ) c= C55 };
L104: (ex B49 being (Element of C54) st (C57 = B49 & ( B49 * C56 ) c= C55)) by L103;
thus L105: thesis by L104;
end;
thus L106: thesis by L102;
end;
func C56 ~ C55 -> (Subset of C54) equals 
{ B50 where B50 is (Element of C54) : ( B50 * C56 ) meets C55 };
correctness
proof
L107: { B51 where B51 is (Element of C54) : ( B51 * C56 ) meets C55 } c= (the carrier of C54)
proof
let C58 being set;
assume L108: C58 in { B52 where B52 is (Element of C54) : ( B52 * C56 ) meets C55 };
L109: (ex B53 being (Element of C54) st (C58 = B53 & ( B53 * C56 ) meets C55)) by L108;
thus L110: thesis by L109;
end;
thus L111: thesis by L107;
end;
end;
theorem
L113: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B54 being (Element of R1) holds (B54 in ( R4 ` R2 ) implies ( B54 * R4 ) c= R2)))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C59 being (Element of R1);
assume L114: C59 in ( R4 ` R2 );
L115: (ex B55 being (Element of R1) st (B55 = C59 & ( B55 * R4 ) c= R2)) by L114;
thus L116: thesis by L115;
end;
theorem
L117: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B56 being (Element of R1) holds (( B56 * R4 ) c= R2 implies B56 in ( R4 ` R2 ))))));
theorem
L118: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B57 being (Element of R1) holds (B57 in ( R4 ~ R2 ) implies ( B57 * R4 ) meets R2)))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C60 being (Element of R1);
assume L119: C60 in ( R4 ~ R2 );
L120: (ex B58 being (Element of R1) st (C60 = B58 & ( B58 * R4 ) meets R2)) by L119;
thus L121: thesis by L120;
end;
theorem
L122: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B59 being (Element of R1) holds (( B59 * R4 ) meets R2 implies B59 in ( R4 ~ R2 ))))));
theorem
L123: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` R2 ) c= R2)))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C61 being set;
assume L124: C61 in ( R4 ` R2 );
consider C62 being (Element of R1) such that L125: (C62 = C61 & ( C62 * R4 ) c= R2) by L124;
L126: C62 in ( C62 * R4 ) by GROUP_2:108;
thus L127: thesis by L126 , L125;
end;
theorem
L128: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds R2 c= ( R4 ~ R2 ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C63 being set;
assume L129: C63 in R2;
reconsider D3 = C63 as (Element of R1) by L129;
L130: D3 in ( D3 * R4 ) by GROUP_2:108;
L131: ( D3 * R4 ) meets R2 by L130 , L129 , XBOOLE_0:3;
thus L132: thesis by L131;
end;
theorem
L133: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` R2 ) c= ( R4 ~ R2 ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
L134: ( R4 ` R2 ) c= R2 by L123;
L135: R2 c= ( R4 ~ R2 ) by L128;
thus L136: thesis by L135 , L134 , XBOOLE_1:1;
end;
theorem
L137: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ~ ( R2 \/ R3 ) ) = ( ( R4 ~ R2 ) \/ ( R4 ~ R3 ) )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L138: ( R4 ~ ( R2 \/ R3 ) ) c= ( ( R4 ~ R2 ) \/ ( R4 ~ R3 ) )
proof
let C64 being set;
assume L139: C64 in ( R4 ~ ( R2 \/ R3 ) );
reconsider D4 = C64 as (Element of R1) by L139;
L140: ( D4 * R4 ) meets ( R2 \/ R3 ) by L139 , L118;
L141: (( D4 * R4 ) meets R2 or ( D4 * R4 ) meets R3) by L140 , XBOOLE_1:70;
L142: (D4 in ( R4 ~ R2 ) or D4 in ( R4 ~ R3 )) by L141;
thus L143: thesis by L142 , XBOOLE_0:def 3;
end;

let C65 being set;
assume L144: C65 in ( ( R4 ~ R2 ) \/ ( R4 ~ R3 ) );
reconsider D5 = C65 as (Element of R1) by L144;
L145: (D5 in ( R4 ~ R2 ) or D5 in ( R4 ~ R3 )) by L144 , XBOOLE_0:def 3;
L146: (( D5 * R4 ) meets R2 or ( D5 * R4 ) meets R3) by L145 , L118;
L147: ( D5 * R4 ) meets ( R2 \/ R3 ) by L146 , XBOOLE_1:70;
thus L148: thesis by L147;
end;
theorem
L149: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` ( R2 /\ R3 ) ) = ( ( R4 ` R2 ) /\ ( R4 ` R3 ) )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L150: ( R4 ` ( R2 /\ R3 ) ) c= ( ( R4 ` R2 ) /\ ( R4 ` R3 ) )
proof
let C66 being set;
assume L151: C66 in ( R4 ` ( R2 /\ R3 ) );
reconsider D6 = C66 as (Element of R1) by L151;
consider C67 being (Element of R1) such that L152: (C67 = D6 & ( C67 * R4 ) c= ( R2 /\ R3 )) by L151;
L153: (( D6 * R4 ) c= R2 & ( D6 * R4 ) c= R3) by L152 , XBOOLE_1:18;
L154: (D6 in ( R4 ` R2 ) & D6 in ( R4 ` R3 )) by L153;
thus L155: thesis by L154 , XBOOLE_0:def 4;
end;

let C68 being set;
assume L156: C68 in ( ( R4 ` R2 ) /\ ( R4 ` R3 ) );
reconsider D7 = C68 as (Element of R1) by L156;
L157: (D7 in ( R4 ` R2 ) & D7 in ( R4 ` R3 )) by L156 , XBOOLE_0:def 4;
L158: (( D7 * R4 ) c= R2 & ( D7 * R4 ) c= R3) by L157 , L113;
L159: ( D7 * R4 ) c= ( R2 /\ R3 ) by L158 , XBOOLE_1:19;
thus L160: thesis by L159;
end;
theorem
L161: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (R2 c= R3 implies ( R4 ` R2 ) c= ( R4 ` R3 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
assume L162: R2 c= R3;
let C69 being set;
assume L163: C69 in ( R4 ` R2 );
reconsider D8 = C69 as (Element of R1) by L163;
L164: ( D8 * R4 ) c= R2 by L163 , L113;
L165: ( D8 * R4 ) c= R3 by L164 , L162 , XBOOLE_1:1;
thus L166: thesis by L165;
end;
theorem
L167: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (R2 c= R3 implies ( R4 ~ R2 ) c= ( R4 ~ R3 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
assume L168: R2 c= R3;
let C70 being set;
assume L169: C70 in ( R4 ~ R2 );
reconsider D9 = C70 as (Element of R1) by L169;
L170: ( D9 * R4 ) meets R2 by L169 , L118;
L171: ( D9 * R4 ) meets R3 by L170 , L168 , XBOOLE_1:63;
thus L172: thesis by L171;
end;
theorem
L173: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( ( R4 ` R2 ) \/ ( R4 ` R3 ) ) c= ( R4 ` ( R2 \/ R3 ) )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C71 being set;
assume L174: C71 in ( ( R4 ` R2 ) \/ ( R4 ` R3 ) );
reconsider D10 = C71 as (Element of R1) by L174;
per cases  by L174 , XBOOLE_0:def 3;
suppose L175: D10 in ( R4 ` R2 );

L176: ( D10 * R4 ) c= ( R2 \/ R3 ) by L175 , L113 , XBOOLE_1:10;
thus L177: thesis by L176;
end;
suppose L178: D10 in ( R4 ` R3 );

L179: ( D10 * R4 ) c= ( R2 \/ R3 ) by L178 , L113 , XBOOLE_1:10;
thus L180: thesis by L179;
end;
end;
theorem
L182: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ~ ( R2 \/ R3 ) ) = ( ( R4 ~ R2 ) \/ ( R4 ~ R3 ) )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L183: ( R4 ~ ( R2 \/ R3 ) ) c= ( ( R4 ~ R2 ) \/ ( R4 ~ R3 ) )
proof
let C72 being set;
assume L184: C72 in ( R4 ~ ( R2 \/ R3 ) );
reconsider D11 = C72 as (Element of R1) by L184;
L185: ( D11 * R4 ) meets ( R2 \/ R3 ) by L184 , L118;
L186: (( D11 * R4 ) meets R2 or ( D11 * R4 ) meets R3) by L185 , XBOOLE_1:70;
L187: (D11 in ( R4 ~ R2 ) or D11 in ( R4 ~ R3 )) by L186;
thus L188: thesis by L187 , XBOOLE_0:def 3;
end;

let C73 being set;
assume L189: C73 in ( ( R4 ~ R2 ) \/ ( R4 ~ R3 ) );
reconsider D12 = C73 as (Element of R1) by L189;
L190: (D12 in ( R4 ~ R2 ) or D12 in ( R4 ~ R3 )) by L189 , XBOOLE_0:def 3;
L191: (( D12 * R4 ) meets R2 or ( D12 * R4 ) meets R3) by L190 , L118;
L192: ( D12 * R4 ) meets ( R2 \/ R3 ) by L191 , XBOOLE_1:70;
thus L193: thesis by L192;
end;
theorem
L194: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds (R4 is (Subgroup of R5) implies ( R5 ` R2 ) c= ( R4 ` R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
assume L195: R4 is (Subgroup of R5);
let C74 being set;
assume L196: C74 in ( R5 ` R2 );
reconsider D13 = C74 as (Element of R1) by L196;
L197: ( D13 * R4 ) c= ( D13 * R5 ) by L195 , GROUP_3:6;
L198: ( D13 * R5 ) c= R2 by L196 , L113;
L199: ( D13 * R4 ) c= R2 by L198 , L197 , XBOOLE_1:1;
thus L200: thesis by L199;
end;
theorem
L201: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds (R4 is (Subgroup of R5) implies ( R4 ~ R2 ) c= ( R5 ~ R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
assume L202: R4 is (Subgroup of R5);
let C75 being set;
assume L203: C75 in ( R4 ~ R2 );
reconsider D14 = C75 as (Element of R1) by L203;
L204: ( D14 * R4 ) meets R2 by L203 , L118;
L205: ( D14 * R5 ) meets R2 by L204 , L202 , GROUP_3:6 , XBOOLE_1:63;
thus L206: thesis by L205;
end;
theorem
L207: (for B60 being Group holds (for B61 , B62 being non  empty (Subset of B60) holds (for B63 being  normal (Subgroup of B60) holds ( ( B63 ` B61 ) * ( B63 ` B62 ) ) c= ( B63 ` ( B61 * B62 ) ))))
proof
let C76 being Group;
let C77 , C78 being non  empty (Subset of C76);
let C79 being  normal (Subgroup of C76);
let C80 being set;
assume L208: C80 in ( ( C79 ` C77 ) * ( C79 ` C78 ) );
reconsider D15 = C80 as (Element of C76) by L208;
consider C81 , C82 being (Element of C76) such that L209: (D15 = ( C81 * C82 ) & C81 in ( C79 ` C77 ) & C82 in ( C79 ` C78 )) by L208;
L210: (( C81 * C79 ) c= C77 & ( C82 * C79 ) c= C78) by L209 , L113;
L211: ( ( C81 * C79 ) * ( C82 * C79 ) ) c= ( C77 * C78 ) by L210 , GROUP_3:4;
L212: ( ( C81 * C82 ) * C79 ) c= ( C77 * C78 ) by L211 , L1;
thus L213: thesis by L212 , L209;
end;
theorem
L214: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R3 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B64 being (Element of R1) holds (B64 in ( R4 ~ ( R2 * R3 ) ) implies ( B64 * R4 ) meets ( R2 * R3 )))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R3 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C83 being (Element of R1);
assume L215: C83 in ( R4 ~ ( R2 * R3 ) );
consider C84 being (Element of R1) such that L216: (C83 = C84 & ( C84 * R4 ) meets ( R2 * R3 )) by L215;
thus L217: thesis by L216;
end;
theorem
L218: (for B65 being Group holds (for B66 , B67 being non  empty (Subset of B65) holds (for B68 being  normal (Subgroup of B65) holds ( ( B68 ~ B66 ) * ( B68 ~ B67 ) ) = ( B68 ~ ( B66 * B67 ) ))))
proof
let C85 being Group;
let C86 , C87 being non  empty (Subset of C85);
let C88 being  normal (Subgroup of C85);
thus L219: ( ( C88 ~ C86 ) * ( C88 ~ C87 ) ) c= ( C88 ~ ( C86 * C87 ) )
proof
let C89 being set;
assume L220: C89 in ( ( C88 ~ C86 ) * ( C88 ~ C87 ) );
reconsider D16 = C89 as (Element of C85) by L220;
consider C90 , C91 being (Element of C85) such that L221: (D16 = ( C90 * C91 ) & C90 in ( C88 ~ C86 ) & C91 in ( C88 ~ C87 )) by L220;
L222: ( C90 * C88 ) meets C86 by L221 , L118;
L223: ( C91 * C88 ) meets C87 by L221 , L118;
consider C92 being set such that L224: (C92 in ( C90 * C88 ) & C92 in C86) by L222 , XBOOLE_0:3;
consider C93 being set such that L225: (C93 in ( C91 * C88 ) & C93 in C87) by L223 , XBOOLE_0:3;
reconsider D17 = C92 as (Element of C85) by L224;
reconsider D18 = C93 as (Element of C85) by L225;
L226: ( D17 * D18 ) in ( C86 * C87 ) by L224 , L225;
L227: ( D17 * D18 ) in ( ( C90 * C88 ) * ( C91 * C88 ) ) by L224 , L225;
L228: ( ( C90 * C88 ) * ( C91 * C88 ) ) meets ( C86 * C87 ) by L227 , L226 , XBOOLE_0:3;
L229: ( ( C90 * C91 ) * C88 ) meets ( C86 * C87 ) by L228 , L1;
thus L230: thesis by L229 , L221;
end;

let C94 being set;
assume L231: C94 in ( C88 ~ ( C86 * C87 ) );
reconsider D19 = C94 as (Element of C85) by L231;
L232: ( D19 * C88 ) meets ( C86 * C87 ) by L231 , L214;
consider C95 being set such that L233: (C95 in ( D19 * C88 ) & C95 in ( C86 * C87 )) by L232 , XBOOLE_0:3;
reconsider D20 = C95 as (Element of C85) by L233;
consider C96 , C97 being (Element of C85) such that L234: (D20 = ( C96 * C97 ) & C96 in C86 & C97 in C87) by L233;
L235: ( D19 * C88 ) = ( ( C96 * C97 ) * C88 ) by L233 , L234 , L4
.= ( ( C96 * C88 ) * ( C97 * C88 ) ) by L1;
L236: D19 in ( ( C96 * C88 ) * ( C97 * C88 ) ) by L235 , GROUP_2:108;
consider C98 , C99 being (Element of C85) such that L237: (D19 = ( C98 * C99 ) & C98 in ( C96 * C88 ) & C99 in ( C97 * C88 )) by L236;
L238: (( C96 * C88 ) = ( C98 * C88 ) & ( C97 * C88 ) = ( C99 * C88 )) by L237 , L4;
L239: (C96 in ( C98 * C88 ) & C97 in ( C99 * C88 )) by L238 , GROUP_2:108;
L240: (( C98 * C88 ) meets C86 & ( C99 * C88 ) meets C87) by L239 , L234 , XBOOLE_0:3;
L241: (C98 in ( C88 ~ C86 ) & C99 in ( C88 ~ C87 )) by L240;
thus L242: thesis by L241 , L237;
end;
theorem
L243: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B69 being (Element of R1) holds (B69 in ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) ) implies ( B69 * R4 ) meets ( R4 ` ( R4 ~ R2 ) ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C100 being (Element of R1);
assume L244: C100 in ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) );
L245: (ex B70 being (Element of R1) st (C100 = B70 & ( B70 * R4 ) meets ( R4 ` ( R4 ~ R2 ) ))) by L244;
thus L246: thesis by L245;
end;
theorem
L247: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B71 being (Element of R1) holds (B71 in ( R4 ` ( R4 ~ R2 ) ) implies ( B71 * R4 ) c= ( R4 ~ R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C101 being (Element of R1);
assume L248: C101 in ( R4 ` ( R4 ~ R2 ) );
L249: (ex B72 being (Element of R1) st (B72 = C101 & ( B72 * R4 ) c= ( R4 ~ R2 ))) by L248;
thus L250: thesis by L249;
end;
theorem
L251: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B73 being (Element of R1) holds (B73 in ( R4 ~ ( R4 ~ R2 ) ) implies ( B73 * R4 ) meets ( R4 ~ R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C102 being (Element of R1);
assume L252: C102 in ( R4 ~ ( R4 ~ R2 ) );
L253: (ex B74 being (Element of R1) st (C102 = B74 & ( B74 * R4 ) meets ( R4 ~ R2 ))) by L252;
thus L254: thesis by L253;
end;
theorem
L255: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B75 being (Element of R1) holds (B75 in ( R4 ~ ( R4 ` R2 ) ) implies ( B75 * R4 ) meets ( R4 ` R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C103 being (Element of R1);
assume L256: C103 in ( R4 ~ ( R4 ` R2 ) );
L257: (ex B76 being (Element of R1) st (C103 = B76 & ( B76 * R4 ) meets ( R4 ` R2 ))) by L256;
thus L258: thesis by L257;
end;
theorem
L259: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` ( R4 ` R2 ) ) = ( R4 ` R2 ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L260: ( R4 ` ( R4 ` R2 ) ) c= ( R4 ` R2 )
proof
let C104 being set;
assume L261: C104 in ( R4 ` ( R4 ` R2 ) );
consider C105 being (Element of R1) such that L262: (C105 = C104 & ( C105 * R4 ) c= ( R4 ` R2 )) by L261;
L263: C105 in ( C105 * R4 ) by GROUP_2:108;
thus L264: thesis by L263 , L262;
end;

let C106 being set;
assume L265: C106 in ( R4 ` R2 );
reconsider D21 = C106 as (Element of R1) by L265;
L266: ( D21 * R4 ) c= R2 by L265 , L113;
L267: ( D21 * R4 ) c= ( R4 ` R2 )
proof
let C107 being set;
assume L268: C107 in ( D21 * R4 );
reconsider D22 = C107 as (Element of R1) by L268;
L269: ( D21 * R4 ) = ( D22 * R4 ) by L268 , L4;
thus L270: thesis by L269 , L266;
end;
thus L271: thesis by L267;
end;
theorem
L272: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ~ R2 ) = ( R4 ~ ( R4 ~ R2 ) ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L273: ( R4 ~ R2 ) c= ( R4 ~ ( R4 ~ R2 ) )
proof
let C108 being set;
assume L274: C108 in ( R4 ~ R2 );
reconsider D23 = C108 as (Element of R1) by L274;
L275: D23 in ( D23 * R4 ) by GROUP_2:108;
L276: ( D23 * R4 ) meets ( R4 ~ R2 ) by L275 , L274 , XBOOLE_0:3;
thus L277: thesis by L276;
end;

let C109 being set;
assume L278: C109 in ( R4 ~ ( R4 ~ R2 ) );
reconsider D24 = C109 as (Element of R1) by L278;
L279: ( D24 * R4 ) meets ( R4 ~ R2 ) by L278 , L251;
consider C110 being set such that L280: (C110 in ( D24 * R4 ) & C110 in ( R4 ~ R2 )) by L279 , XBOOLE_0:3;
reconsider D25 = C110 as (Element of R1) by L280;
L281: ( D25 * R4 ) meets R2 by L280 , L118;
L282: ( D25 * R4 ) = ( D24 * R4 ) by L280 , L4;
thus L283: thesis by L282 , L281;
end;
theorem
L284: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` ( R4 ` R2 ) ) c= ( R4 ~ ( R4 ~ R2 ) ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
L285: ( R4 ` R2 ) c= ( R4 ~ R2 ) by L133;
L286: ( R4 ` ( R4 ` R2 ) ) c= ( R4 ~ R2 ) by L285 , L259;
thus L287: thesis by L286 , L272;
end;
theorem
L288: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ~ ( R4 ` R2 ) ) c= R2)))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C111 being set;
assume L289: C111 in ( R4 ~ ( R4 ` R2 ) );
reconsider D26 = C111 as (Element of R1) by L289;
L290: ( D26 * R4 ) meets ( R4 ` R2 ) by L289 , L255;
consider C112 being set such that L291: (C112 in ( D26 * R4 ) & C112 in ( R4 ` R2 )) by L290 , XBOOLE_0:3;
reconsider D27 = C112 as (Element of R1) by L291;
L292: ( D27 * R4 ) c= R2 by L291 , L113;
L293: ( D26 * R4 ) c= R2 by L292 , L291 , L4;
L294: D26 in ( D26 * R4 ) by GROUP_2:108;
thus L295: thesis by L294 , L293;
end;
theorem
L296: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` ( R4 ~ ( R4 ` R2 ) ) ) = ( R4 ` R2 ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L297: ( R4 ` ( R4 ~ ( R4 ` R2 ) ) ) c= ( R4 ` R2 )
proof
let C113 being set;
assume L298: C113 in ( R4 ` ( R4 ~ ( R4 ` R2 ) ) );
consider C114 being (Element of R1) such that L299: (C114 = C113 & ( C114 * R4 ) c= ( R4 ~ ( R4 ` R2 ) )) by L298;
L300: C114 in ( C114 * R4 ) by GROUP_2:108;
L301: ( C114 * R4 ) meets ( R4 ` R2 ) by L300 , L299 , L255;
consider C115 being set such that L302: (C115 in ( C114 * R4 ) & C115 in ( R4 ` R2 )) by L301 , XBOOLE_0:3;
reconsider D28 = C115 as (Element of R1) by L302;
L303: ( D28 * R4 ) c= R2 by L302 , L113;
L304: ( C114 * R4 ) c= R2 by L303 , L302 , L4;
thus L305: thesis by L304 , L299;
end;

let C116 being set;
assume L306: C116 in ( R4 ` R2 );
reconsider D29 = C116 as (Element of R1) by L306;
L307: ( D29 * R4 ) c= ( R4 ~ ( R4 ` R2 ) )
proof
let C117 being set;
assume L308: C117 in ( D29 * R4 );
reconsider D30 = C117 as (Element of R1) by L308;
L309: ( D30 * R4 ) = ( D29 * R4 ) by L308 , L4;
L310: D29 in ( D30 * R4 ) by L309 , GROUP_2:108;
L311: ( D30 * R4 ) meets ( R4 ` R2 ) by L310 , L306 , XBOOLE_0:3;
thus L312: thesis by L311;
end;
thus L313: thesis by L307;
end;
theorem
L314: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (R2 c= ( R4 ` ( R4 ~ R2 ) ) implies ( R4 ~ R2 ) c= ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
assume L315: R2 c= ( R4 ` ( R4 ~ R2 ) );
let C118 being set;
assume L316: C118 in ( R4 ~ R2 );
reconsider D31 = C118 as (Element of R1) by L316;
L317: ( D31 * R4 ) meets R2 by L316 , L118;
L318: ( D31 * R4 ) meets ( R4 ` ( R4 ~ R2 ) ) by L317 , L315 , XBOOLE_1:63;
thus L319: thesis by L318;
end;
theorem
L320: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) ) = ( R4 ~ R2 ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L321: ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) ) c= ( R4 ~ R2 )
proof
let C119 being set;
assume L322: C119 in ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) );
reconsider D32 = C119 as (Element of R1) by L322;
L323: ( D32 * R4 ) meets ( R4 ` ( R4 ~ R2 ) ) by L322 , L243;
consider C120 being set such that L324: (C120 in ( D32 * R4 ) & C120 in ( R4 ` ( R4 ~ R2 ) )) by L323 , XBOOLE_0:3;
reconsider D33 = C120 as (Element of R1) by L324;
L325: ( D33 * R4 ) c= ( R4 ~ R2 ) by L324 , L247;
L326: ( D32 * R4 ) c= ( R4 ~ R2 ) by L325 , L324 , L4;
L327: D32 in ( D32 * R4 ) by GROUP_2:108;
thus L328: thesis by L327 , L326;
end;

thus L329: ( R4 ~ R2 ) c= ( R4 ~ ( R4 ` ( R4 ~ R2 ) ) )
proof
L330: R2 c= ( R4 ` ( R4 ~ R2 ) )
proof
let C121 being set;
assume L331: C121 in R2;
reconsider D34 = C121 as (Element of R1) by L331;
L332: ( D34 * R4 ) c= ( R4 ~ R2 )
proof
let C122 being set;
assume L333: C122 in ( D34 * R4 );
reconsider D35 = C122 as (Element of R1) by L333;
L334: ( D35 * R4 ) = ( D34 * R4 ) by L333 , L4;
L335: D34 in ( D35 * R4 ) by L334 , GROUP_2:108;
L336: ( D35 * R4 ) meets R2 by L335 , L331 , XBOOLE_0:3;
thus L337: thesis by L336;
end;
thus L338: thesis by L332;
end;
thus L339: thesis by L330 , L314;
end;

end;
theorem
L330: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds (for B77 being (Element of R1) holds (B77 in ( R4 ` ( R4 ` R2 ) ) implies ( B77 * R4 ) c= ( R4 ` R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
let C123 being (Element of R1);
assume L331: C123 in ( R4 ` ( R4 ` R2 ) );
L332: (ex B78 being (Element of R1) st (B78 = C123 & ( B78 * R4 ) c= ( R4 ` R2 ))) by L331;
thus L333: thesis by L332;
end;
theorem
L334: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ` ( R4 ` R2 ) ) = ( R4 ~ ( R4 ` R2 ) ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L335: ( R4 ` ( R4 ` R2 ) ) c= ( R4 ~ ( R4 ` R2 ) )
proof
let C124 being set;
assume L336: C124 in ( R4 ` ( R4 ` R2 ) );
reconsider D36 = C124 as (Element of R1) by L336;
L337: ( D36 * R4 ) c= ( R4 ` R2 ) by L336 , L330;
L338: D36 in ( D36 * R4 ) by GROUP_2:108;
L339: ( D36 * R4 ) meets ( R4 ` R2 ) by L338 , L337 , XBOOLE_0:3;
thus L340: thesis by L339;
end;

let C125 being set;
assume L341: C125 in ( R4 ~ ( R4 ` R2 ) );
reconsider D37 = C125 as (Element of R1) by L341;
L342: ( D37 * R4 ) meets ( R4 ` R2 ) by L341 , L255;
consider C126 being set such that L343: (C126 in ( D37 * R4 ) & C126 in ( R4 ` R2 )) by L342 , XBOOLE_0:3;
reconsider D38 = C126 as (Element of R1) by L343;
L344: ( D38 * R4 ) c= R2 by L343 , L113;
L345: ( D37 * R4 ) c= R2 by L344 , L343 , L4;
L346: ( D37 * R4 ) c= ( R4 ` R2 )
proof
let C127 being set;
assume L347: C127 in ( D37 * R4 );
reconsider D39 = C127 as (Element of R1) by L347;
L348: ( D37 * R4 ) = ( D39 * R4 ) by L347 , L4;
thus L349: thesis by L348 , L345;
end;
thus L350: thesis by L346;
end;
theorem
L351: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for R4 being (Subgroup of R1) holds ( R4 ~ ( R4 ~ R2 ) ) = ( R4 ` ( R4 ~ R2 ) ))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let R4 being (Subgroup of R1);
thus L352: ( R4 ~ ( R4 ~ R2 ) ) c= ( R4 ` ( R4 ~ R2 ) )
proof
let C128 being set;
assume L353: C128 in ( R4 ~ ( R4 ~ R2 ) );
reconsider D40 = C128 as (Element of R1) by L353;
L354: ( D40 * R4 ) meets ( R4 ~ R2 ) by L353 , L251;
consider C129 being set such that L355: (C129 in ( D40 * R4 ) & C129 in ( R4 ~ R2 )) by L354 , XBOOLE_0:3;
reconsider D41 = C129 as (Element of R1) by L355;
L356: ( D41 * R4 ) meets R2 by L355 , L118;
L357: ( D40 * R4 ) meets R2 by L356 , L355 , L4;
L358: ( D40 * R4 ) c= ( R4 ~ R2 )
proof
let C130 being set;
assume L359: C130 in ( D40 * R4 );
reconsider D42 = C130 as (Element of R1) by L359;
L360: ( D40 * R4 ) = ( D42 * R4 ) by L359 , L4;
thus L361: thesis by L360 , L357;
end;
thus L362: thesis by L358;
end;

let C131 being set;
assume L363: C131 in ( R4 ` ( R4 ~ R2 ) );
reconsider D43 = C131 as (Element of R1) by L363;
L364: ( D43 * R4 ) c= ( R4 ~ R2 ) by L363 , L247;
L365: D43 in ( D43 * R4 ) by GROUP_2:108;
L366: ( D43 * R4 ) meets ( R4 ~ R2 ) by L365 , L364 , XBOOLE_0:3;
thus L367: thesis by L366;
end;
theorem
L368: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for B79 , B80 , B81 being (Subgroup of R1) holds (B79 = ( B80 /\ B81 ) implies ( B79 ~ R2 ) c= ( ( B80 ~ R2 ) /\ ( B81 ~ R2 ) )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let C132 , C133 , C134 being (Subgroup of R1);
assume L369: C132 = ( C133 /\ C134 );
L370: (C132 is (Subgroup of C133) & C132 is (Subgroup of C134)) by L369 , GROUP_2:88;
let C135 being set;
assume L371: C135 in ( C132 ~ R2 );
L372: (( C132 ~ R2 ) c= ( C133 ~ R2 ) & ( C132 ~ R2 ) c= ( C134 ~ R2 )) by L370 , L201;
thus L373: thesis by L372 , L371 , XBOOLE_0:def 4;
end;
theorem
L374: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for B82 , B83 , B84 being (Subgroup of R1) holds (B82 = ( B83 /\ B84 ) implies ( ( B83 ` R2 ) /\ ( B84 ` R2 ) ) c= ( B82 ` R2 )))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let C136 , C137 , C138 being (Subgroup of R1);
assume L375: C136 = ( C137 /\ C138 );
L376: (C136 is (Subgroup of C137) & C136 is (Subgroup of C138)) by L375 , GROUP_2:88;
let C139 being set;
assume L377: C139 in ( ( C137 ` R2 ) /\ ( C138 ` R2 ) );
L378: (C139 in ( C137 ` R2 ) & C139 in ( C138 ` R2 )) by L377 , XBOOLE_0:def 4;
L379: (( C137 ` R2 ) c= ( C136 ` R2 ) & ( C138 ` R2 ) c= ( C136 ` R2 )) by L376 , L194;
thus L380: thesis by L379 , L378;
end;
theorem
L381: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for B85 , B86 being  strict  normal (Subgroup of R1) holds (ex B87 being  strict  normal (Subgroup of R1) st ((the carrier of B87) = ( B85 * B86 ) & ( B87 ` R2 ) c= ( ( B85 ` R2 ) /\ ( B86 ` R2 ) ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let C140 , C141 being  strict  normal (Subgroup of R1);
consider C142 being  strict  normal (Subgroup of R1) such that L382: (the carrier of C142) = ( C140 * C141 ) by L65;
L383: (C140 is (Subgroup of C142) & C141 is (Subgroup of C142)) by L382 , L77;
L384: (( C142 ` R2 ) c= ( C140 ` R2 ) & ( C142 ` R2 ) c= ( C141 ` R2 )) by L383 , L194;
L385: ( C142 ` R2 ) c= ( ( C140 ` R2 ) /\ ( C141 ` R2 ) )
proof
let C143 being set;
assume L386: C143 in ( C142 ` R2 );
thus L387: thesis by L386 , L384 , XBOOLE_0:def 4;
end;
thus L388: thesis by L385 , L382;
end;
theorem
L389: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for B88 , B89 being  strict  normal (Subgroup of R1) holds (ex B90 being  strict  normal (Subgroup of R1) st ((the carrier of B90) = ( B88 * B89 ) & ( ( B88 ~ R2 ) \/ ( B89 ~ R2 ) ) c= ( B90 ~ R2 ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let C144 , C145 being  strict  normal (Subgroup of R1);
consider C146 being  strict  normal (Subgroup of R1) such that L390: (the carrier of C146) = ( C144 * C145 ) by L65;
L391: (C144 is (Subgroup of C146) & C145 is (Subgroup of C146)) by L390 , L77;
L392: (( C144 ~ R2 ) c= ( C146 ~ R2 ) & ( C145 ~ R2 ) c= ( C146 ~ R2 )) by L391 , L201;
L393: ( ( C144 ~ R2 ) \/ ( C145 ~ R2 ) ) c= ( C146 ~ R2 )
proof
let C147 being set;
assume L394: C147 in ( ( C144 ~ R2 ) \/ ( C145 ~ R2 ) );
L395: (C147 in ( C144 ~ R2 ) or C147 in ( C145 ~ R2 )) by L394 , XBOOLE_0:def 3;
thus L396: thesis by L395 , L392;
end;
thus L397: thesis by L393 , L390;
end;
theorem
L398: (for R1 being Group holds (for R2 being non  empty (Subset of R1) holds (for B91 , B92 being  strict  normal (Subgroup of R1) holds (ex B93 being  strict  normal (Subgroup of R1) st ((the carrier of B93) = ( B91 * B92 ) & ( B93 ~ R2 ) c= ( ( ( B91 ~ R2 ) * B92 ) /\ ( ( B92 ~ R2 ) * B91 ) ))))))
proof
let R1 being Group;
let R2 being non  empty (Subset of R1);
let C148 , C149 being  strict  normal (Subgroup of R1);
consider C150 being  strict  normal (Subgroup of R1) such that L399: (the carrier of C150) = ( C148 * C149 ) by L65;
L400: ( C150 ~ R2 ) c= ( ( ( C148 ~ R2 ) * C149 ) /\ ( ( C149 ~ R2 ) * C148 ) )
proof
let C151 being set;
assume L401: C151 in ( C150 ~ R2 );
reconsider D44 = C151 as (Element of R1) by L401;
L402: ( D44 * C150 ) meets R2 by L401 , L118;
consider C152 being set such that L403: (C152 in ( D44 * C150 ) & C152 in R2) by L402 , XBOOLE_0:3;
reconsider D45 = C152 as (Element of R1) by L403;
consider C153 being (Element of R1) such that L404: (D45 = ( D44 * C153 ) & C153 in C150) by L403 , GROUP_2:103;
L405: C153 in ( C148 * C149 ) by L399 , L404 , STRUCT_0:def 5;
consider C154 , C155 being (Element of R1) such that L406: (C153 = ( C154 * C155 ) & C154 in C148 & C155 in C149) by L405 , L30;
L407: D45 = ( ( D44 * C154 ) * C155 ) by L404 , L406 , GROUP_1:def 3;
L408: C154 in ( carr C148 ) by L406 , STRUCT_0:def 5;
L409: ( ( D44 * C154 ) * C155 ) in ( ( D44 * C148 ) * C155 ) by L408 , GROUP_8:15;
L410: ( ( D44 * C148 ) * C155 ) = ( D44 * ( C148 * C155 ) ) by GROUP_2:106
.= ( D44 * ( C155 * C148 ) ) by GROUP_3:117
.= ( ( D44 * C155 ) * C148 ) by GROUP_2:105;
L411: ( ( D44 * C155 ) * C148 ) meets R2 by L410 , L403 , L407 , L409 , XBOOLE_0:3;
L412: ( D44 * C155 ) in ( C148 ~ R2 ) by L411;
L413: ( ( D44 * C155 ) * ( C155 " ) ) = ( D44 * ( C155 * ( C155 " ) ) ) by GROUP_1:def 3
.= ( D44 * ( 1_ R1 ) ) by GROUP_1:def 5
.= D44 by GROUP_1:def 4;
L414: ( C155 " ) in C149 by L406 , GROUP_2:51;
L415: D44 in ( ( C148 ~ R2 ) * C149 ) by L414 , L412 , L413 , GROUP_2:94;
L416: C153 in ( C149 * C148 ) by L405 , GROUP_3:125;
consider C156 , C157 being (Element of R1) such that L417: (C153 = ( C156 * C157 ) & C156 in C149 & C157 in C148) by L416 , L30;
L418: D45 = ( ( D44 * C156 ) * C157 ) by L404 , L417 , GROUP_1:def 3;
L419: C156 in ( carr C149 ) by L417 , STRUCT_0:def 5;
L420: ( ( D44 * C156 ) * C157 ) in ( ( D44 * C149 ) * C157 ) by L419 , GROUP_8:15;
L421: ( ( D44 * C149 ) * C157 ) = ( D44 * ( C149 * C157 ) ) by GROUP_2:106
.= ( D44 * ( C157 * C149 ) ) by GROUP_3:117
.= ( ( D44 * C157 ) * C149 ) by GROUP_2:105;
L422: ( ( D44 * C157 ) * C149 ) meets R2 by L421 , L403 , L418 , L420 , XBOOLE_0:3;
L423: ( D44 * C157 ) in ( C149 ~ R2 ) by L422;
L424: ( ( D44 * C157 ) * ( C157 " ) ) = ( D44 * ( C157 * ( C157 " ) ) ) by GROUP_1:def 3
.= ( D44 * ( 1_ R1 ) ) by GROUP_1:def 5
.= D44 by GROUP_1:def 4;
L425: ( C157 " ) in C148 by L417 , GROUP_2:51;
L426: D44 in ( ( C149 ~ R2 ) * C148 ) by L425 , L423 , L424 , GROUP_2:94;
thus L427: thesis by L426 , L415 , XBOOLE_0:def 4;
end;
thus L428: thesis by L400 , L399;
end;
definition
let C158 being Group;
let C159 , C160 being (Subgroup of C158);
func C160 ` C159 -> (Subset of C158) equals 
{ B94 where B94 is (Element of C158) : ( B94 * C160 ) c= ( carr C159 ) };
coherence
proof
L429: { B95 where B95 is (Element of C158) : ( B95 * C160 ) c= ( carr C159 ) } c= (the carrier of C158)
proof
let C161 being set;
assume L430: C161 in { B96 where B96 is (Element of C158) : ( B96 * C160 ) c= ( carr C159 ) };
L431: (ex B97 being (Element of C158) st (C161 = B97 & ( B97 * C160 ) c= ( carr C159 ))) by L430;
thus L432: thesis by L431;
end;
thus L433: thesis by L429;
end;
func C160 ~ C159 -> (Subset of C158) equals 
{ B98 where B98 is (Element of C158) : ( B98 * C160 ) meets ( carr C159 ) };
coherence
proof
L434: { B99 where B99 is (Element of C158) : ( B99 * C160 ) meets ( carr C159 ) } c= (the carrier of C158)
proof
let C162 being set;
assume L435: C162 in { B100 where B100 is (Element of C158) : ( B100 * C160 ) meets ( carr C159 ) };
L436: (ex B101 being (Element of C158) st (C162 = B101 & ( B101 * C160 ) meets ( carr C159 ))) by L435;
thus L437: thesis by L436;
end;
thus L438: thesis by L434;
end;
end;
theorem
L440: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds (for B102 being (Element of R1) holds (B102 in ( R4 ` R5 ) implies ( B102 * R4 ) c= ( carr R5 ))))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
let C163 being (Element of R1);
assume L441: C163 in ( R4 ` R5 );
L442: (ex B103 being (Element of R1) st (B103 = C163 & ( B103 * R4 ) c= ( carr R5 ))) by L441;
thus L443: thesis by L442;
end;
theorem
L444: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds (for B104 being (Element of R1) holds (( B104 * R4 ) c= ( carr R5 ) implies B104 in ( R4 ` R5 ))))));
theorem
L445: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds (for B105 being (Element of R1) holds (B105 in ( R4 ~ R5 ) implies ( B105 * R4 ) meets ( carr R5 ))))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
let C164 being (Element of R1);
assume L446: C164 in ( R4 ~ R5 );
L447: (ex B106 being (Element of R1) st (C164 = B106 & ( B106 * R4 ) meets ( carr R5 ))) by L446;
thus L448: thesis by L447;
end;
theorem
L449: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds (for B107 being (Element of R1) holds (( B107 * R4 ) meets ( carr R5 ) implies B107 in ( R4 ~ R5 ))))));
theorem
L450: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds ( R4 ` R5 ) c= ( carr R5 ))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
let C165 being set;
assume L451: C165 in ( R4 ` R5 );
consider C166 being (Element of R1) such that L452: (C166 = C165 & ( C166 * R4 ) c= ( carr R5 )) by L451;
L453: C166 in ( C166 * R4 ) by GROUP_2:108;
thus L454: thesis by L453 , L452;
end;
theorem
L455: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds ( carr R5 ) c= ( R4 ~ R5 ))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
let C167 being set;
assume L456: C167 in ( carr R5 );
reconsider D46 = C167 as (Element of R5) by L456;
reconsider D47 = D46 as (Element of R1) by GROUP_2:42;
L457: D47 in ( D47 * R4 ) by GROUP_2:108;
L458: ( D47 * R4 ) meets ( carr R5 ) by L457 , XBOOLE_0:3;
thus L459: thesis by L458;
end;
theorem
L460: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R5 being (Subgroup of R1) holds ( R4 ` R5 ) c= ( R4 ~ R5 ))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R5 being (Subgroup of R1);
L461: ( R4 ` R5 ) c= ( carr R5 ) by L450;
L462: ( carr R5 ) c= ( R4 ~ R5 ) by L455;
thus L463: thesis by L462 , L461 , XBOOLE_1:1;
end;
theorem
L464: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R6 being (Subgroup of R1) holds (for R7 being (Subgroup of R1) holds (R6 is (Subgroup of R7) implies ( R4 ~ R6 ) c= ( R4 ~ R7 ))))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R6 being (Subgroup of R1);
let R7 being (Subgroup of R1);
assume L465: R6 is (Subgroup of R7);
L466: ( carr R6 ) c= ( carr R7 ) by L465 , GROUP_2:def 5;
let C168 being set;
assume L467: C168 in ( R4 ~ R6 );
reconsider D48 = C168 as (Element of R1) by L467;
L468: ( D48 * R4 ) meets ( carr R6 ) by L467 , L445;
L469: ( D48 * R4 ) meets ( carr R7 ) by L468 , L466 , XBOOLE_1:63;
thus L470: thesis by L469;
end;
theorem
L471: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for R11 being (Subgroup of R1) holds (for R12 being (Subgroup of R1) holds (R11 is (Subgroup of R12) implies ( R11 ~ R5 ) c= ( R12 ~ R5 ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let R11 being (Subgroup of R1);
let R12 being (Subgroup of R1);
assume L472: R11 is (Subgroup of R12);
let C169 being set;
assume L473: C169 in ( R11 ~ R5 );
reconsider D49 = C169 as (Element of R1) by L473;
L474: ( D49 * R11 ) meets ( carr R5 ) by L473 , L445;
L475: ( D49 * R12 ) meets ( carr R5 ) by L474 , L472 , GROUP_3:6 , XBOOLE_1:63;
thus L476: thesis by L475;
end;
theorem
L477: (for R1 being Group holds (for R11 being (Subgroup of R1) holds (for R12 being (Subgroup of R1) holds (R11 is (Subgroup of R12) implies ( R11 ~ R11 ) c= ( R12 ~ R12 )))))
proof
let R1 being Group;
let R11 being (Subgroup of R1);
let R12 being (Subgroup of R1);
assume L478: R11 is (Subgroup of R12);
L479: ( R12 ~ R11 ) c= ( R12 ~ R12 ) by L478 , L464;
L480: ( R11 ~ R11 ) c= ( R12 ~ R11 ) by L478 , L471;
thus L481: thesis by L480 , L479 , XBOOLE_1:1;
end;
theorem
L482: (for R1 being Group holds (for R4 being (Subgroup of R1) holds (for R6 being (Subgroup of R1) holds (for R7 being (Subgroup of R1) holds (R6 is (Subgroup of R7) implies ( R4 ` R6 ) c= ( R4 ` R7 ))))))
proof
let R1 being Group;
let R4 being (Subgroup of R1);
let R6 being (Subgroup of R1);
let R7 being (Subgroup of R1);
assume L483: R6 is (Subgroup of R7);
L484: ( carr R6 ) c= ( carr R7 ) by L483 , GROUP_2:def 5;
let C170 being set;
assume L485: C170 in ( R4 ` R6 );
reconsider D50 = C170 as (Element of R1) by L485;
L486: ( D50 * R4 ) c= ( carr R6 ) by L485 , L440;
L487: ( D50 * R4 ) c= ( carr R7 ) by L486 , L484 , XBOOLE_1:1;
thus L488: thesis by L487;
end;
theorem
L489: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for R11 being (Subgroup of R1) holds (for R12 being (Subgroup of R1) holds (R11 is (Subgroup of R12) implies ( R12 ` R5 ) c= ( R11 ` R5 ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let R11 being (Subgroup of R1);
let R12 being (Subgroup of R1);
assume L490: R11 is (Subgroup of R12);
let C171 being set;
assume L491: C171 in ( R12 ` R5 );
reconsider D51 = C171 as (Element of R1) by L491;
L492: ( D51 * R11 ) c= ( D51 * R12 ) by L490 , GROUP_3:6;
L493: ( D51 * R12 ) c= ( carr R5 ) by L491 , L440;
L494: ( D51 * R11 ) c= ( carr R5 ) by L493 , L492 , XBOOLE_1:1;
thus L495: thesis by L494;
end;
theorem
L496: (for R1 being Group holds (for R11 being (Subgroup of R1) holds (for R12 being (Subgroup of R1) holds (R11 is (Subgroup of R12) implies ( R12 ` R11 ) c= ( R11 ` R12 )))))
proof
let R1 being Group;
let R11 being (Subgroup of R1);
let R12 being (Subgroup of R1);
assume L497: R11 is (Subgroup of R12);
L498: ( R12 ` R11 ) c= ( R12 ` R12 ) by L497 , L482;
L499: ( R12 ` R12 ) c= ( R11 ` R12 ) by L497 , L489;
thus L500: thesis by L499 , L498 , XBOOLE_1:1;
end;
theorem
L501: (for R1 being Group holds (for R6 being (Subgroup of R1) holds (for R7 being (Subgroup of R1) holds (for B108 being  normal (Subgroup of R1) holds ( ( B108 ` R6 ) * ( B108 ` R7 ) ) c= ( B108 ` ( R6 * R7 ) )))))
proof
let R1 being Group;
let R6 being (Subgroup of R1);
let R7 being (Subgroup of R1);
let C172 being  normal (Subgroup of R1);
let C173 being set;
assume L502: C173 in ( ( C172 ` R6 ) * ( C172 ` R7 ) );
reconsider D52 = C173 as (Element of R1) by L502;
consider C174 , C175 being (Element of R1) such that L503: (D52 = ( C174 * C175 ) & C174 in ( C172 ` R6 ) & C175 in ( C172 ` R7 )) by L502;
L504: (( C174 * C172 ) c= ( carr R6 ) & ( C175 * C172 ) c= ( carr R7 )) by L503 , L440;
L505: ( ( C174 * C172 ) * ( C175 * C172 ) ) c= ( ( carr R6 ) * ( carr R7 ) ) by L504 , GROUP_3:4;
L506: ( ( C174 * C175 ) * C172 ) c= ( ( carr R6 ) * ( carr R7 ) ) by L505 , L1;
thus L507: thesis by L506 , L503;
end;
theorem
L508: (for R1 being Group holds (for R6 being (Subgroup of R1) holds (for R7 being (Subgroup of R1) holds (for B109 being  normal (Subgroup of R1) holds ( ( B109 ~ R6 ) * ( B109 ~ R7 ) ) = ( B109 ~ ( R6 * R7 ) )))))
proof
let R1 being Group;
let R6 being (Subgroup of R1);
let R7 being (Subgroup of R1);
let C176 being  normal (Subgroup of R1);
thus L509: ( ( C176 ~ R6 ) * ( C176 ~ R7 ) ) c= ( C176 ~ ( R6 * R7 ) )
proof
let C177 being set;
assume L510: C177 in ( ( C176 ~ R6 ) * ( C176 ~ R7 ) );
reconsider D53 = C177 as (Element of R1) by L510;
consider C178 , C179 being (Element of R1) such that L511: (D53 = ( C178 * C179 ) & C178 in ( C176 ~ R6 ) & C179 in ( C176 ~ R7 )) by L510;
L512: ( C178 * C176 ) meets ( carr R6 ) by L511 , L445;
L513: ( C179 * C176 ) meets ( carr R7 ) by L511 , L445;
consider C180 being set such that L514: (C180 in ( C178 * C176 ) & C180 in ( carr R6 )) by L512 , XBOOLE_0:3;
consider C181 being set such that L515: (C181 in ( C179 * C176 ) & C181 in ( carr R7 )) by L513 , XBOOLE_0:3;
reconsider D54 = C180 as (Element of R1) by L514;
reconsider D55 = C181 as (Element of R1) by L515;
L516: ( D54 * D55 ) in ( ( carr R6 ) * ( carr R7 ) ) by L514 , L515;
L517: ( D54 * D55 ) in ( ( C178 * C176 ) * ( C179 * C176 ) ) by L514 , L515;
L518: ( ( C178 * C176 ) * ( C179 * C176 ) ) meets ( ( carr R6 ) * ( carr R7 ) ) by L517 , L516 , XBOOLE_0:3;
L519: ( ( C178 * C179 ) * C176 ) meets ( ( carr R6 ) * ( carr R7 ) ) by L518 , L1;
thus L520: thesis by L519 , L511;
end;

let C182 being set;
assume L521: C182 in ( C176 ~ ( R6 * R7 ) );
reconsider D56 = C182 as (Element of R1) by L521;
L522: ( D56 * C176 ) meets ( ( carr R6 ) * ( carr R7 ) ) by L521 , L214;
consider C183 being set such that L523: (C183 in ( D56 * C176 ) & C183 in ( ( carr R6 ) * ( carr R7 ) )) by L522 , XBOOLE_0:3;
reconsider D57 = C183 as (Element of R1) by L523;
consider C184 , C185 being (Element of R1) such that L524: (D57 = ( C184 * C185 ) & C184 in ( carr R6 ) & C185 in ( carr R7 )) by L523;
L525: ( D56 * C176 ) = ( ( C184 * C185 ) * C176 ) by L523 , L524 , L4
.= ( ( C184 * C176 ) * ( C185 * C176 ) ) by L1;
L526: D56 in ( ( C184 * C176 ) * ( C185 * C176 ) ) by L525 , GROUP_2:108;
consider C186 , C187 being (Element of R1) such that L527: (D56 = ( C186 * C187 ) & C186 in ( C184 * C176 ) & C187 in ( C185 * C176 )) by L526;
L528: (( C184 * C176 ) = ( C186 * C176 ) & ( C185 * C176 ) = ( C187 * C176 )) by L527 , L4;
L529: (C184 in ( C186 * C176 ) & C185 in ( C187 * C176 )) by L528 , GROUP_2:108;
L530: (( C186 * C176 ) meets ( carr R6 ) & ( C187 * C176 ) meets ( carr R7 )) by L529 , L524 , XBOOLE_0:3;
L531: (C186 in ( C176 ~ R6 ) & C187 in ( C176 ~ R7 )) by L530;
thus L532: thesis by L531 , L527;
end;
theorem
L533: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B110 , B111 , B112 being (Subgroup of R1) holds (B110 = ( B111 /\ B112 ) implies ( B110 ~ R5 ) c= ( ( B111 ~ R5 ) /\ ( B112 ~ R5 ) )))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C188 , C189 , C190 being (Subgroup of R1);
assume L534: C188 = ( C189 /\ C190 );
L535: (C188 is (Subgroup of C189) & C188 is (Subgroup of C190)) by L534 , GROUP_2:88;
let C191 being set;
assume L536: C191 in ( C188 ~ R5 );
L537: (( C188 ~ R5 ) c= ( C189 ~ R5 ) & ( C188 ~ R5 ) c= ( C190 ~ R5 )) by L535 , L471;
thus L538: thesis by L537 , L536 , XBOOLE_0:def 4;
end;
theorem
L539: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B113 , B114 , B115 being (Subgroup of R1) holds (B113 = ( B114 /\ B115 ) implies ( ( B114 ` R5 ) /\ ( B115 ` R5 ) ) c= ( B113 ` R5 )))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C192 , C193 , C194 being (Subgroup of R1);
assume L540: C192 = ( C193 /\ C194 );
L541: (C192 is (Subgroup of C193) & C192 is (Subgroup of C194)) by L540 , GROUP_2:88;
let C195 being set;
assume L542: C195 in ( ( C193 ` R5 ) /\ ( C194 ` R5 ) );
L543: (C195 in ( C193 ` R5 ) & C195 in ( C194 ` R5 )) by L542 , XBOOLE_0:def 4;
L544: (( C193 ` R5 ) c= ( C192 ` R5 ) & ( C194 ` R5 ) c= ( C192 ` R5 )) by L541 , L489;
thus L545: thesis by L544 , L543;
end;
theorem
L546: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B116 , B117 being  strict  normal (Subgroup of R1) holds (ex B118 being  strict  normal (Subgroup of R1) st ((the carrier of B118) = ( B116 * B117 ) & ( B118 ` R5 ) c= ( ( B116 ` R5 ) /\ ( B117 ` R5 ) ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C196 , C197 being  strict  normal (Subgroup of R1);
consider C198 being  strict  normal (Subgroup of R1) such that L547: (the carrier of C198) = ( C196 * C197 ) by L65;
L548: (C196 is (Subgroup of C198) & C197 is (Subgroup of C198)) by L547 , L77;
L549: (( C198 ` R5 ) c= ( C196 ` R5 ) & ( C198 ` R5 ) c= ( C197 ` R5 )) by L548 , L489;
L550: ( C198 ` R5 ) c= ( ( C196 ` R5 ) /\ ( C197 ` R5 ) )
proof
let C199 being set;
assume L551: C199 in ( C198 ` R5 );
thus L552: thesis by L551 , L549 , XBOOLE_0:def 4;
end;
thus L553: thesis by L550 , L547;
end;
theorem
L554: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B119 , B120 being  strict  normal (Subgroup of R1) holds (ex B121 being  strict  normal (Subgroup of R1) st ((the carrier of B121) = ( B119 * B120 ) & ( ( B119 ~ R5 ) \/ ( B120 ~ R5 ) ) c= ( B121 ~ R5 ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C200 , C201 being  strict  normal (Subgroup of R1);
consider C202 being  strict  normal (Subgroup of R1) such that L555: (the carrier of C202) = ( C200 * C201 ) by L65;
L556: (C200 is (Subgroup of C202) & C201 is (Subgroup of C202)) by L555 , L77;
L557: (( C200 ~ R5 ) c= ( C202 ~ R5 ) & ( C201 ~ R5 ) c= ( C202 ~ R5 )) by L556 , L471;
L558: ( ( C200 ~ R5 ) \/ ( C201 ~ R5 ) ) c= ( C202 ~ R5 )
proof
let C203 being set;
assume L559: C203 in ( ( C200 ~ R5 ) \/ ( C201 ~ R5 ) );
L560: (C203 in ( C200 ~ R5 ) or C203 in ( C201 ~ R5 )) by L559 , XBOOLE_0:def 3;
thus L561: thesis by L560 , L557;
end;
thus L562: thesis by L558 , L555;
end;
theorem
L563: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B122 , B123 being  strict  normal (Subgroup of R1) holds (ex B124 being  strict  normal (Subgroup of R1) st ((the carrier of B124) = ( B122 * B123 ) & ( ( B122 ` R5 ) * ( B123 ` R5 ) ) c= ( B124 ` R5 ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C204 , C205 being  strict  normal (Subgroup of R1);
consider C206 being  strict  normal (Subgroup of R1) such that L564: (the carrier of C206) = ( C204 * C205 ) by L65;
L565: ( ( C204 ` R5 ) * ( C205 ` R5 ) ) c= ( C206 ` R5 )
proof
let C207 being set;
assume L566: C207 in ( ( C204 ` R5 ) * ( C205 ` R5 ) );
reconsider D58 = C207 as (Element of R1) by L566;
consider C208 , C209 being (Element of R1) such that L567: (D58 = ( C208 * C209 ) & C208 in ( C204 ` R5 ) & C209 in ( C205 ` R5 )) by L566;
L568: (( C208 * C204 ) c= ( carr R5 ) & ( C209 * C205 ) c= ( carr R5 )) by L567 , L440;
L569: ( ( C208 * C204 ) * ( C209 * C205 ) ) c= ( ( carr R5 ) * ( carr R5 ) ) by L568 , GROUP_3:4;
L570: ( ( C208 * C204 ) * ( C209 * C205 ) ) c= ( carr R5 ) by L569 , GROUP_2:76;
L571: ( ( C208 * C204 ) * ( C209 * C205 ) ) = ( ( C208 * C209 ) * C206 ) by L564 , L93;
thus L572: thesis by L571 , L567 , L570;
end;
thus L573: thesis by L565 , L564;
end;
theorem
L574: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B125 , B126 being  strict  normal (Subgroup of R1) holds (ex B127 being  strict  normal (Subgroup of R1) st ((the carrier of B127) = ( B125 * B126 ) & ( ( B125 ~ R5 ) * ( B126 ~ R5 ) ) c= ( B127 ~ R5 ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C210 , C211 being  strict  normal (Subgroup of R1);
consider C212 being  strict  normal (Subgroup of R1) such that L575: (the carrier of C212) = ( C210 * C211 ) by L65;
L576: ( ( C210 ~ R5 ) * ( C211 ~ R5 ) ) c= ( C212 ~ R5 )
proof
let C213 being set;
assume L577: C213 in ( ( C210 ~ R5 ) * ( C211 ~ R5 ) );
reconsider D59 = C213 as (Element of R1) by L577;
consider C214 , C215 being (Element of R1) such that L578: (D59 = ( C214 * C215 ) & C214 in ( C210 ~ R5 ) & C215 in ( C211 ~ R5 )) by L577;
L579: ( C214 * C210 ) meets ( carr R5 ) by L578 , L445;
L580: ( C215 * C211 ) meets ( carr R5 ) by L578 , L445;
consider C216 being set such that L581: (C216 in ( C214 * C210 ) & C216 in ( carr R5 )) by L579 , XBOOLE_0:3;
consider C217 being set such that L582: (C217 in ( C215 * C211 ) & C217 in ( carr R5 )) by L580 , XBOOLE_0:3;
reconsider D60 = C216 as (Element of R1) by L581;
reconsider D61 = C217 as (Element of R1) by L582;
L583: ( D60 * D61 ) in ( ( carr R5 ) * ( carr R5 ) ) by L581 , L582;
L584: ( D60 * D61 ) in ( ( C214 * C210 ) * ( C215 * C211 ) ) by L581 , L582;
L585: ( ( carr R5 ) * ( carr R5 ) ) = ( carr R5 ) by GROUP_2:76;
L586: ( ( C214 * C210 ) * ( C215 * C211 ) ) meets ( carr R5 ) by L585 , L583 , L584 , XBOOLE_0:3;
L587: ( ( C214 * C210 ) * ( C215 * C211 ) ) = ( ( C214 * C215 ) * C212 ) by L575 , L93;
thus L588: thesis by L587 , L578 , L586;
end;
thus L589: thesis by L576 , L575;
end;
theorem
L590: (for R1 being Group holds (for R5 being (Subgroup of R1) holds (for B128 , B129 being  strict  normal (Subgroup of R1) holds (ex B130 being  strict  normal (Subgroup of R1) st ((the carrier of B130) = ( B128 * B129 ) & ( B130 ~ R5 ) c= ( ( ( B128 ~ R5 ) * B129 ) /\ ( ( B129 ~ R5 ) * B128 ) ))))))
proof
let R1 being Group;
let R5 being (Subgroup of R1);
let C218 , C219 being  strict  normal (Subgroup of R1);
consider C220 being  strict  normal (Subgroup of R1) such that L591: (the carrier of C220) = ( C218 * C219 ) by L65;
L592: ( C220 ~ R5 ) c= ( ( ( C218 ~ R5 ) * C219 ) /\ ( ( C219 ~ R5 ) * C218 ) )
proof
let C221 being set;
assume L593: C221 in ( C220 ~ R5 );
reconsider D62 = C221 as (Element of R1) by L593;
L594: ( D62 * C220 ) meets ( carr R5 ) by L593 , L445;
consider C222 being set such that L595: (C222 in ( D62 * C220 ) & C222 in ( carr R5 )) by L594 , XBOOLE_0:3;
reconsider D63 = C222 as (Element of R1) by L595;
consider C223 being (Element of R1) such that L596: (D63 = ( D62 * C223 ) & C223 in C220) by L595 , GROUP_2:103;
L597: C223 in ( C218 * C219 ) by L591 , L596 , STRUCT_0:def 5;
consider C224 , C225 being (Element of R1) such that L598: (C223 = ( C224 * C225 ) & C224 in C218 & C225 in C219) by L597 , L30;
L599: D63 = ( ( D62 * C224 ) * C225 ) by L596 , L598 , GROUP_1:def 3;
L600: C224 in ( carr C218 ) by L598 , STRUCT_0:def 5;
L601: ( ( D62 * C224 ) * C225 ) in ( ( D62 * C218 ) * C225 ) by L600 , GROUP_8:15;
L602: ( ( D62 * C218 ) * C225 ) = ( D62 * ( C218 * C225 ) ) by GROUP_2:106
.= ( D62 * ( C225 * C218 ) ) by GROUP_3:117
.= ( ( D62 * C225 ) * C218 ) by GROUP_2:105;
L603: ( ( D62 * C225 ) * C218 ) meets ( carr R5 ) by L602 , L595 , L599 , L601 , XBOOLE_0:3;
L604: ( D62 * C225 ) in ( C218 ~ R5 ) by L603;
L605: ( ( D62 * C225 ) * ( C225 " ) ) = ( D62 * ( C225 * ( C225 " ) ) ) by GROUP_1:def 3
.= ( D62 * ( 1_ R1 ) ) by GROUP_1:def 5
.= D62 by GROUP_1:def 4;
L606: ( C225 " ) in C219 by L598 , GROUP_2:51;
L607: D62 in ( ( C218 ~ R5 ) * C219 ) by L606 , L604 , L605 , GROUP_2:94;
L608: C223 in ( C219 * C218 ) by L597 , GROUP_3:125;
consider C226 , C227 being (Element of R1) such that L609: (C223 = ( C226 * C227 ) & C226 in C219 & C227 in C218) by L608 , L30;
L610: D63 = ( ( D62 * C226 ) * C227 ) by L596 , L609 , GROUP_1:def 3;
L611: C226 in ( carr C219 ) by L609 , STRUCT_0:def 5;
L612: ( ( D62 * C226 ) * C227 ) in ( ( D62 * C219 ) * C227 ) by L611 , GROUP_8:15;
L613: ( ( D62 * C219 ) * C227 ) = ( D62 * ( C219 * C227 ) ) by GROUP_2:106
.= ( D62 * ( C227 * C219 ) ) by GROUP_3:117
.= ( ( D62 * C227 ) * C219 ) by GROUP_2:105;
L614: ( ( D62 * C227 ) * C219 ) meets ( carr R5 ) by L613 , L595 , L610 , L612 , XBOOLE_0:3;
L615: ( D62 * C227 ) in ( C219 ~ R5 ) by L614;
L616: ( ( D62 * C227 ) * ( C227 " ) ) = ( D62 * ( C227 * ( C227 " ) ) ) by GROUP_1:def 3
.= ( D62 * ( 1_ R1 ) ) by GROUP_1:def 5
.= D62 by GROUP_1:def 4;
L617: ( C227 " ) in C218 by L609 , GROUP_2:51;
L618: D62 in ( ( C219 ~ R5 ) * C218 ) by L617 , L615 , L616 , GROUP_2:94;
thus L619: thesis by L618 , L607 , XBOOLE_0:def 4;
end;
thus L620: thesis by L592 , L591;
end;
theorem
L621: (for R1 being Group holds (for B131 being (Subgroup of R1) holds (for B132 being  normal (Subgroup of R1) holds (ex B133 being  strict (Subgroup of R1) st (the carrier of B133) = ( B132 ~ B131 )))))
proof
let R1 being Group;
let C228 being (Subgroup of R1);
let C229 being  normal (Subgroup of R1);
L622: ( 1_ R1 ) in ( C229 ~ C228 )
proof
L623: ( 1_ R1 ) in C228 by GROUP_2:46;
L624: ( 1_ R1 ) in ( carr C228 ) by L623 , STRUCT_0:def 5;
L625: ( 1_ R1 ) in ( ( 1_ R1 ) * C229 ) by GROUP_2:108;
L626: ( ( 1_ R1 ) * C229 ) meets ( carr C228 ) by L625 , L624 , XBOOLE_0:3;
thus L627: thesis by L626;
end;
L628: (for B134 , B135 being (Element of R1) holds ((B134 in ( C229 ~ C228 ) & B135 in ( C229 ~ C228 )) implies ( B134 * B135 ) in ( C229 ~ C228 )))
proof
let C230 , C231 being (Element of R1);
assume that
L629: C230 in ( C229 ~ C228 )
and
L630: C231 in ( C229 ~ C228 );
consider C232 being (Element of R1) such that L631: (C232 in ( C230 * C229 ) & C232 in C228) by L629 , L445 , L9;
consider C233 being (Element of R1) such that L632: (C233 in ( C231 * C229 ) & C233 in C228) by L630 , L445 , L9;
L633: (( ( C230 * C229 ) * ( C231 * C229 ) ) = ( ( C230 * C231 ) * C229 ) & ( ( C232 * C229 ) * ( C233 * C229 ) ) = ( ( C232 * C233 ) * C229 )) by L1;
L634: ( C232 * C233 ) in ( ( C230 * C231 ) * C229 ) by L633 , L631 , L632;
L635: ( C232 * C233 ) in C228 by L631 , L632 , GROUP_2:50;
L636: ( C232 * C233 ) in ( carr C228 ) by L635 , STRUCT_0:def 5;
L637: ( ( C230 * C231 ) * C229 ) meets ( carr C228 ) by L636 , L634 , XBOOLE_0:3;
thus L638: thesis by L637;
end;
L639: (for B136 being (Element of R1) holds (B136 in ( C229 ~ C228 ) implies ( B136 " ) in ( C229 ~ C228 )))
proof
let C234 being (Element of R1);
assume L640: C234 in ( C229 ~ C228 );
consider C235 being (Element of R1) such that L641: (C235 in ( C234 * C229 ) & C235 in C228) by L640 , L9 , L445;
consider C236 being (Element of R1) such that L642: (C235 = ( C234 * C236 ) & C236 in C229) by L641 , GROUP_2:103;
L643: ( C236 " ) in C229 by L642 , GROUP_2:51;
L644: ( C235 " ) = ( ( C236 " ) * ( C234 " ) ) by L642 , GROUP_1:17;
L645: ( C235 " ) in ( C229 * ( C234 " ) ) by L644 , L643 , GROUP_2:104;
L646: ( C235 " ) in ( ( C234 " ) * C229 ) by L645 , GROUP_3:117;
L647: ( C235 " ) in C228 by L641 , GROUP_2:51;
L648: ( C235 " ) in ( carr C228 ) by L647 , STRUCT_0:def 5;
L649: ( ( C234 " ) * C229 ) meets ( carr C228 ) by L648 , L646 , XBOOLE_0:3;
thus L650: thesis by L649;
end;
thus L651: thesis by L639 , L622 , L628 , GROUP_2:52;
end;
theorem
L652: (for R1 being Group holds (for B137 being (Subgroup of R1) holds (for B138 being  normal (Subgroup of R1) holds (B138 is (Subgroup of B137) implies (ex B139 being  strict (Subgroup of R1) st (the carrier of B139) = ( B138 ` B137 ))))))
proof
let R1 being Group;
let C237 being (Subgroup of R1);
let C238 being  normal (Subgroup of R1);
assume L653: C238 is (Subgroup of C237);
L654: ( 1_ R1 ) in ( C238 ` C237 )
proof
L655: ( 1_ R1 ) in C238 by GROUP_2:46;
L656: ( ( 1_ R1 ) * C238 ) = ( carr C238 ) by L655 , GROUP_2:113;
L657: ( carr C238 ) c= ( carr C237 ) by L653 , GROUP_2:def 5;
thus L658: thesis by L657 , L656;
end;
L659: (for B140 , B141 being (Element of R1) holds ((B140 in ( C238 ` C237 ) & B141 in ( C238 ` C237 )) implies ( B140 * B141 ) in ( C238 ` C237 )))
proof
let C239 , C240 being (Element of R1);
assume L660: (C239 in ( C238 ` C237 ) & C240 in ( C238 ` C237 ));
L661: (( C239 * C238 ) c= ( carr C237 ) & ( C240 * C238 ) c= ( carr C237 )) by L660 , L440;
L662: ( ( C239 * C238 ) * ( C240 * C238 ) ) c= ( ( carr C237 ) * ( carr C237 ) ) by L661 , GROUP_3:4;
L663: ( ( C239 * C238 ) * ( C240 * C238 ) ) = ( ( C239 * C240 ) * C238 ) by L1;
L664: ( ( carr C237 ) * ( carr C237 ) ) = ( carr C237 ) by GROUP_2:76;
thus L665: thesis by L664 , L662 , L663;
end;
L666: (for B142 being (Element of R1) holds (B142 in ( C238 ` C237 ) implies ( B142 " ) in ( C238 ` C237 )))
proof
let C241 being (Element of R1);
assume L667: C241 in ( C238 ` C237 );
L668: ( C241 * C238 ) c= ( carr C237 ) by L667 , L440;
L669: C241 in ( C241 * C238 ) by GROUP_2:108;
L670: C241 in C237 by L669 , L668 , STRUCT_0:def 5;
L671: ( C241 " ) in C237 by L670 , GROUP_2:51;
L672: ( ( C241 " ) * C237 ) = ( carr C237 ) by L671 , GROUP_2:113;
L673: ( ( C241 " ) * C238 ) c= ( ( C241 " ) * C237 ) by L653 , GROUP_3:6;
thus L674: thesis by L673 , L672;
end;
thus L675: thesis by L666 , L654 , L659 , GROUP_2:52;
end;
theorem
L676: (for R1 being Group holds (for B143 , B144 being  normal (Subgroup of R1) holds (ex B145 being  strict  normal (Subgroup of R1) st (the carrier of B145) = ( B144 ~ B143 ))))
proof
let R1 being Group;
let C242 , C243 being  normal (Subgroup of R1);
consider C244 being  strict (Subgroup of R1) such that L677: (the carrier of C244) = ( C243 ~ C242 ) by L621;
L678: (for B146 being (Element of R1) holds ( B146 * C244 ) c= ( C244 * B146 ))
proof
let C245 being (Element of R1);
let C246 being set;
assume L679: C246 in ( C245 * C244 );
reconsider D64 = C246 as (Element of R1) by L679;
consider C247 being (Element of R1) such that L680: (D64 = ( C245 * C247 ) & C247 in C244) by L679 , GROUP_2:103;
L681: C247 in (the carrier of C244) by L680 , STRUCT_0:def 5;
consider C248 being (Element of R1) such that L682: (C248 in ( C247 * C243 ) & C248 in C242) by L681 , L9 , L677 , L445;
L683: ( ( C245 * C248 ) * ( C245 " ) ) in C242 by L682 , L14;
L684: ( ( C245 * C248 ) * ( C245 " ) ) in ( carr C242 ) by L683 , STRUCT_0:def 5;
L685: ( ( C245 * C248 ) * ( C245 " ) ) in ( ( C245 * ( C247 * C243 ) ) * ( C245 " ) ) by L682 , GROUP_8:15;
L686: ( ( C245 * ( C247 * C243 ) ) * ( C245 " ) ) = ( C245 * ( ( C247 * C243 ) * ( C245 " ) ) ) by GROUP_2:33
.= ( C245 * ( C247 * ( C243 * ( C245 " ) ) ) ) by GROUP_2:33
.= ( C245 * ( C247 * ( ( C245 " ) * C243 ) ) ) by GROUP_3:117
.= ( C245 * ( ( C247 * ( C245 " ) ) * C243 ) ) by GROUP_2:32
.= ( ( C245 * ( C247 * ( C245 " ) ) ) * C243 ) by GROUP_2:32
.= ( ( ( C245 * C247 ) * ( C245 " ) ) * C243 ) by GROUP_1:def 3;
L687: ( ( ( C245 * C247 ) * ( C245 " ) ) * C243 ) meets ( carr C242 ) by L686 , L684 , L685 , XBOOLE_0:3;
L688: ( ( C245 * C247 ) * ( C245 " ) ) in ( C243 ~ C242 ) by L687;
L689: ( ( C245 * C247 ) * ( C245 " ) ) in C244 by L688 , L677 , STRUCT_0:def 5;
L690: ( ( ( C245 * C247 ) * ( C245 " ) ) * C245 ) = D64 by L680 , GROUP_3:1;
thus L691: thesis by L690 , L689 , GROUP_2:104;
end;
L692: C244 is  normal  normal  normal  normal (Subgroup of R1) by L678 , GROUP_3:118;
thus L693: thesis by L692 , L677;
end;
theorem
L694: (for R1 being Group holds (for B147 , B148 being  normal (Subgroup of R1) holds (B148 is (Subgroup of B147) implies (ex B149 being  strict  normal (Subgroup of R1) st (the carrier of B149) = ( B148 ` B147 )))))
proof
let R1 being Group;
let C249 , C250 being  normal (Subgroup of R1);
assume L695: C250 is (Subgroup of C249);
consider C251 being  strict (Subgroup of R1) such that L696: (the carrier of C251) = ( C250 ` C249 ) by L695 , L652;
L697: (for B150 being (Element of R1) holds ( B150 * C251 ) c= ( C251 * B150 ))
proof
let C252 being (Element of R1);
let C253 being set;
assume L698: C253 in ( C252 * C251 );
reconsider D65 = C253 as (Element of R1) by L698;
consider C254 being (Element of R1) such that L699: (D65 = ( C252 * C254 ) & C254 in C251) by L698 , GROUP_2:103;
L700: C254 in (the carrier of C251) by L699 , STRUCT_0:def 5;
L701: ( C254 * C250 ) c= ( carr C249 ) by L700 , L696 , L440;
L702: C254 in ( C254 * C250 ) by GROUP_2:108;
L703: C254 in C249 by L702 , L701 , STRUCT_0:def 5;
L704: ( ( C252 * C254 ) * ( C252 " ) ) in C249 by L703 , L14;
L705: ( ( ( C252 * C254 ) * ( C252 " ) ) * C249 ) = ( carr C249 ) by L704 , GROUP_2:113;
L706: ( ( ( C252 * C254 ) * ( C252 " ) ) * C250 ) c= ( ( ( C252 * C254 ) * ( C252 " ) ) * C249 ) by L695 , GROUP_3:6;
L707: ( ( C252 * C254 ) * ( C252 " ) ) in ( C250 ` C249 ) by L706 , L705;
L708: ( ( C252 * C254 ) * ( C252 " ) ) in C251 by L707 , L696 , STRUCT_0:def 5;
L709: ( ( ( C252 * C254 ) * ( C252 " ) ) * C252 ) = D65 by L699 , GROUP_3:1;
thus L710: thesis by L709 , L708 , GROUP_2:104;
end;
L711: C251 is  normal  normal  normal  normal (Subgroup of R1) by L697 , GROUP_3:118;
thus L712: thesis by L711 , L696;
end;
theorem
L713: (for R1 being Group holds (for B151 , B152 being  normal (Subgroup of R1) holds (B152 is (Subgroup of B151) implies (ex B153 , B154 being  strict  normal (Subgroup of R1) st ((the carrier of B153) = ( B152 ~ B151 ) & (the carrier of B154) = ( B152 ` B151 ) & ( B153 ` B151 ) c= ( B154 ` B151 ))))))
proof
let R1 being Group;
let C255 , C256 being  normal (Subgroup of R1);
assume L714: C256 is (Subgroup of C255);
consider C257 being  strict  normal (Subgroup of R1) such that L715: (the carrier of C257) = ( C256 ~ C255 ) by L676;
consider C258 being  strict  normal (Subgroup of R1) such that L716: (the carrier of C258) = ( C256 ` C255 ) by L714 , L694;
L717: C258 is (Subgroup of C257) by L715 , L716 , L460 , GROUP_2:57;
L718: ( C257 ` C255 ) c= ( C258 ` C255 ) by L717 , L489;
thus L719: thesis by L718 , L715 , L716;
end;
theorem
L720: (for R1 being Group holds (for B155 , B156 being  normal (Subgroup of R1) holds (B156 is (Subgroup of B155) implies (ex B157 , B158 being  strict  normal (Subgroup of R1) st ((the carrier of B157) = ( B156 ~ B155 ) & (the carrier of B158) = ( B156 ` B155 ) & ( B158 ~ B155 ) c= ( B157 ~ B155 ))))))
proof
let R1 being Group;
let C259 , C260 being  normal (Subgroup of R1);
assume L721: C260 is (Subgroup of C259);
consider C261 being  strict  normal (Subgroup of R1) such that L722: (the carrier of C261) = ( C260 ~ C259 ) by L676;
consider C262 being  strict  normal (Subgroup of R1) such that L723: (the carrier of C262) = ( C260 ` C259 ) by L721 , L694;
L724: C262 is (Subgroup of C261) by L722 , L723 , L460 , GROUP_2:57;
L725: ( C262 ~ C259 ) c= ( C261 ~ C259 ) by L724 , L471;
thus L726: thesis by L725 , L722 , L723;
end;
theorem
L727: (for R1 being Group holds (for B159 , B160 being  normal (Subgroup of R1) holds (B160 is (Subgroup of B159) implies (ex B161 , B162 being  strict  normal (Subgroup of R1) st ((the carrier of B161) = ( B160 ~ B159 ) & (the carrier of B162) = ( B160 ` B159 ) & ( B161 ` B159 ) c= ( B162 ~ B159 ))))))
proof
let R1 being Group;
let C263 , C264 being  normal (Subgroup of R1);
assume L728: C264 is (Subgroup of C263);
consider C265 , C266 being  strict  normal (Subgroup of R1) such that L729: (the carrier of C265) = ( C264 ~ C263 ) and L730: (the carrier of C266) = ( C264 ` C263 ) and L731: ( C265 ` C263 ) c= ( C266 ` C263 ) by L728 , L713;
L732: ( C266 ` C263 ) c= ( C266 ~ C263 ) by L460;
thus L733: thesis by L732 , L729 , L730 , L731 , XBOOLE_1:1;
end;
theorem
L734: (for R1 being Group holds (for B163 , B164 being  normal (Subgroup of R1) holds (B164 is (Subgroup of B163) implies (ex B165 , B166 being  strict  normal (Subgroup of R1) st ((the carrier of B165) = ( B164 ~ B163 ) & (the carrier of B166) = ( B164 ` B163 ) & ( B166 ` B163 ) c= ( B165 ~ B163 ))))))
proof
let R1 being Group;
let C267 , C268 being  normal (Subgroup of R1);
assume L735: C268 is (Subgroup of C267);
consider C269 , C270 being  strict  normal (Subgroup of R1) such that L736: (the carrier of C269) = ( C268 ~ C267 ) and L737: (the carrier of C270) = ( C268 ` C267 ) and L738: ( C270 ~ C267 ) c= ( C269 ~ C267 ) by L735 , L720;
L739: ( C270 ` C267 ) c= ( C270 ~ C267 ) by L460;
thus L740: thesis by L739 , L736 , L737 , L738 , XBOOLE_1:1;
end;
theorem
L741: (for R1 being Group holds (for B167 , B168 , B169 being  normal (Subgroup of R1) holds (B168 is (Subgroup of B169) implies (ex B170 , B171 being  strict  normal (Subgroup of R1) st ((the carrier of B170) = ( B167 ~ B168 ) & (the carrier of B171) = ( B167 ~ B169 ) & ( B170 ~ B168 ) c= ( B171 ~ B168 ))))))
proof
let R1 being Group;
let C271 , C272 , C273 being  normal (Subgroup of R1);
assume L742: C272 is (Subgroup of C273);
consider C274 being  strict  normal (Subgroup of R1) such that L743: (the carrier of C274) = ( C271 ~ C272 ) by L676;
consider C275 being  strict  normal (Subgroup of R1) such that L744: (the carrier of C275) = ( C271 ~ C273 ) by L676;
L745: C274 is (Subgroup of C275) by L742 , L743 , L744 , L464 , GROUP_2:57;
L746: ( C274 ~ C272 ) c= ( C275 ~ C272 ) by L745 , L471;
thus L747: thesis by L746 , L743 , L744;
end;
theorem
L748: (for R1 being Group holds (for B172 , B173 being  normal (Subgroup of R1) holds (ex B174 being  strict  normal (Subgroup of R1) st ((the carrier of B174) = ( B172 ` B172 ) & ( B172 ` B173 ) c= ( B174 ` B173 )))))
proof
let R1 being Group;
let C276 , C277 being  normal (Subgroup of R1);
L749: C276 is (Subgroup of C276) by GROUP_2:54;
consider C278 being  strict  normal (Subgroup of R1) such that L750: (the carrier of C278) = ( C276 ` C276 ) by L749 , L694;
L751: C278 is (Subgroup of C276) by L750 , L450 , GROUP_2:57;
L752: ( C276 ` C277 ) c= ( C278 ` C277 ) by L751 , L489;
thus L753: thesis by L752 , L750;
end;
theorem
L754: (for R1 being Group holds (for B175 , B176 being  normal (Subgroup of R1) holds (ex B177 being  strict  normal (Subgroup of R1) st ((the carrier of B177) = ( B175 ~ B175 ) & ( B175 ~ B176 ) c= ( B177 ~ B176 )))))
proof
let R1 being Group;
let C279 , C280 being  normal (Subgroup of R1);
consider C281 being  strict  normal (Subgroup of R1) such that L755: (the carrier of C281) = ( C279 ~ C279 ) by L676;
L756: C279 is (Subgroup of C281) by L755 , L455 , GROUP_2:57;
L757: ( C279 ~ C280 ) c= ( C281 ~ C280 ) by L756 , L471;
thus L758: thesis by L757 , L755;
end;
