:: Hilbert Basis Theorem
::  by Jonathan Backer and Piotr Rudnicki
::
:: Received November 27, 2000
:: Copyright (c) 2000-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, FINSEQ_1, FUNCT_1, RELAT_1, XBOOLE_0, TARSKI, ORDINAL4,
      NAT_1, XXREAL_0, ARYTM_3, PRE_POLY, CARD_1, FUNCOP_1, PARTFUN1, SUBSET_1,
      ARYTM_1, FUNCT_4, ORDINAL1, PBOOLE, FINSET_1, ORDERS_1, VECTSP_1,
      ZFMISC_1, ALGSTR_0, POLYNOM2, GROUP_1, POLYNOM1, SUPINF_2, RLVECT_1,
      ALGSEQ_1, LATTICES, POLYNOM3, STRUCT_0, CARD_3, CARD_FIL, QUOFIELD,
      MSSUBFAM, IDEAL_1, PRELAMB, MCART_1, BINOP_1, FUNCT_2, HILBASIS,
      RECDEF_2;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, PBOOLE, RELAT_1, FINSET_1,
      FUNCT_1, PARTFUN1, CARD_1, NUMBERS, XCMPLX_0, XXREAL_0, ORDINAL1, NAT_1,
      RELSET_1, FUNCT_2, FUNCOP_1, FINSEQ_1, FUNCT_4, BINOP_1, XXREAL_2,
      MCART_1, FINSEQOP, FINSEQ_2, FUNCT_7, PRE_POLY, DOMAIN_1, STRUCT_0,
      ALGSTR_0, RLVECT_1, VFUNCT_1, GROUP_1, VECTSP_1, NORMSP_1, POLYNOM1,
      POLYNOM2, POLYNOM3, ALGSEQ_1, NAT_D, IDEAL_1, TOPS_2, GRCAT_1, WSIERP_1,
      ORDERS_1, GROUP_6, QUOFIELD, RECDEF_1, MATRLIN;
 constructors FINSEQOP, NAT_D, REAL_1, WSIERP_1, TOPS_2, ALGSEQ_1, GRCAT_1,
      GROUP_6, MATRIX_2, TRIANG_1, QUOFIELD, POLYNOM2, POLYNOM3, IDEAL_1,
      RECDEF_1, XXREAL_2, DOMAIN_1, BINARITH, RELSET_1, FUNCT_7, MATRLIN,
      VFUNCT_1;
 registrations XBOOLE_0, SUBSET_1, RELAT_1, FUNCT_1, FUNCOP_1, FINSET_1,
      XXREAL_0, XREAL_0, NAT_1, INT_1, CARD_1, MEMBERED, FINSEQ_1, CARD_5,
      PRE_CIRC, STRUCT_0, VECTSP_1, ALGSTR_1, GR_CY_1, WAYBEL_2, GCD_1,
      PRE_POLY, POLYNOM1, POLYNOM2, POLYNOM3, IDEAL_1, VALUED_0, ALGSTR_0,
      XXREAL_2, VFUNCT_1, FUNCT_2, RELSET_1;
 requirements NUMERALS, REAL, SUBSET, BOOLE, ARITHM;
 definitions TARSKI, IDEAL_1, VECTSP_1, GROUP_6, FUNCOP_1, POLYNOM3, CARD_1,
      STRUCT_0;
 theorems TARSKI, ZFMISC_1, RLVECT_1, FUNCT_1, FUNCT_2, POLYNOM1, NAT_1,
      AXIOMS, FVSUM_1, FINSEQ_1, FINSEQ_2, FINSEQ_3, POLYNOM3, FUNCOP_1,
      ALGSEQ_1, INT_1, FUNCT_7, IDEAL_1, POLYNOM4, GRCAT_1, QUOFIELD, FUNCT_4,
      RELAT_1, CARD_1, MATRLIN, CARD_3, ORDINAL1, WAYBEL_1, ORDERS_1, FINSET_1,
      FINSEQOP, POLYNOM2, TOPS_2, FINSEQ_5, GROUP_1, XBOOLE_0, XBOOLE_1,
      RLVECT_2, VECTSP_1, XREAL_1, GROUP_6, XXREAL_0, NORMSP_1, PARTFUN1,
      XXREAL_2, NAT_D, XREAL_0, PRE_POLY;
 schemes NAT_1, RECDEF_1, FUNCT_1, FUNCT_2, FINSEQ_2, FUNCT_7;

begin
theorem
L1: (for B1 , B2 being FinSequence holds (for B3 being Function holds (( ( rng B1 ) \/ ( rng B2 ) ) c= ( dom B3 ) implies (ex B4 , B5 being FinSequence st (B4 = ( B3 * B1 ) & B5 = ( B3 * B2 ) & ( B3 * ( B1 ^ B2 ) ) = ( B4 ^ B5 ))))))
proof
let C1 , C2 being FinSequence;
let C3 being Function;
assume L2: ( ( rng C1 ) \/ ( rng C2 ) ) c= ( dom C3 );
L3: ( rng ( C1 ^ C2 ) ) c= ( dom C3 ) by L2 , FINSEQ_1:31;
reconsider D1 = ( C3 * ( C1 ^ C2 ) ) as FinSequence by L3 , FINSEQ_1:16;
L4: ( rng C2 ) c= ( ( rng C1 ) \/ ( rng C2 ) ) by XBOOLE_1:7;
reconsider D2 = ( C3 * C2 ) as FinSequence by L4 , L2 , FINSEQ_1:16 , XBOOLE_1:1;
L5: ( dom ( C3 * C2 ) ) = ( dom C2 ) by L2 , L4 , RELAT_1:27 , XBOOLE_1:1;
L6: ( len D2 ) = ( len C2 ) by L5 , FINSEQ_3:29;
L7: ( rng C1 ) c= ( ( rng C1 ) \/ ( rng C2 ) ) by XBOOLE_1:7;
reconsider D3 = ( C3 * C1 ) as FinSequence by L7 , L2 , FINSEQ_1:16 , XBOOLE_1:1;
take D3;
take D2;
L8: ( dom ( C3 * ( C1 ^ C2 ) ) ) = ( dom ( C1 ^ C2 ) ) by L3 , RELAT_1:27;
L9: ( dom ( C3 * C1 ) ) = ( dom C1 ) by L2 , L7 , RELAT_1:27 , XBOOLE_1:1;
L10: ( len D3 ) = ( len C1 ) by L9 , FINSEQ_3:29;
L11:
now
let C4 being Nat;
assume L12: (1 <= C4 & C4 <= ( len D1 ));
L13: C4 in ( dom D1 ) by L12 , FINSEQ_3:25;
per cases ;
suppose L14: C4 in ( dom D3 );

thus L15: ( ( D3 ^ D2 ) . C4 ) = ( D3 . C4 ) by L14 , FINSEQ_1:def 7
.= ( C3 . ( C1 . C4 ) ) by L14 , FUNCT_1:12
.= ( C3 . ( ( C1 ^ C2 ) . C4 ) ) by L9 , L14 , FINSEQ_1:def 7
.= ( D1 . C4 ) by L13 , FUNCT_1:12;
end;
suppose L16: (not C4 in ( dom D3 ));

consider C5 being Nat such that L17: C5 in ( dom C2 ) and L18: C4 = ( ( len C1 ) + C5 ) by L16 , L9 , L8 , L13 , FINSEQ_1:25;
thus L19: ( D1 . C4 ) = ( C3 . ( ( C1 ^ C2 ) . C4 ) ) by L13 , FUNCT_1:12
.= ( C3 . ( C2 . C5 ) ) by L17 , L18 , FINSEQ_1:def 7
.= ( D2 . C5 ) by L5 , L17 , FUNCT_1:12
.= ( ( D3 ^ D2 ) . C4 ) by L10 , L5 , L17 , L18 , FINSEQ_1:def 7;
end;
end;
L21: ( len D1 ) = ( len ( C1 ^ C2 ) ) by L8 , FINSEQ_3:29
.= ( ( len D3 ) + ( len D2 ) ) by L10 , L6 , FINSEQ_1:22
.= ( len ( D3 ^ D2 ) ) by FINSEQ_1:22;
thus L22: thesis by L21 , L11 , FINSEQ_1:14;
end;
theorem
L23: (for B6 being (bag of ( 0 )) holds ( decomp B6 ) = <* <* ( {} ) , ( {} ) *> *>)
proof
let C6 being (bag of ( 0 ));
L24: ( EmptyBag ( {} ) ) = ( ( {} ) --> ( 0 ) );
L25: ( divisors C6 ) = <* ( {} ) *> by L24 , PRE_POLY:67;
L26: ( len ( divisors C6 ) ) = 1 by L25 , FINSEQ_1:39;
L27: ( dom ( divisors C6 ) ) = ( dom ( decomp C6 ) ) by PRE_POLY:def 17;
L28: 1 in ( dom ( decomp C6 ) ) by L27 , L26 , FINSEQ_3:25;
L29: ( ( decomp C6 ) . 1 ) = ( ( decomp C6 ) /. 1 ) by L28 , PARTFUN1:def 6
.= <* ( {} ) , ( {} ) *> by L24 , PRE_POLY:71;
L30: ( len ( decomp C6 ) ) = 1 by L26 , L27 , FINSEQ_3:29;
thus L31: thesis by L30 , L29 , FINSEQ_1:40;
end;
theorem
L32: (for B7 , B8 being (Element of ( NAT )) holds (for B9 being (bag of B8) holds (B7 <= B8 implies ( B9 | B7 ) is (Element of ( Bags B7 )))))
proof
let C7 , C8 being (Element of ( NAT ));
let C9 being (bag of C8);
assume L33: C7 <= C8;
L34: C7 c= C8
proof
let C10 being set;
assume L35: C10 in C7;
L36: C10 in { B10 where B10 is (Element of ( NAT )) : B10 < C7 } by L35 , AXIOMS:4;
consider C11 being (Element of ( NAT )) such that L37: C11 = C10 and L38: C11 < C7 by L36;
L39: C11 < C8 by L33 , L38 , XXREAL_0:2;
L40: C11 in { B11 where B11 is (Element of ( NAT )) : B11 < C8 } by L39;
thus L41: thesis by L40 , L37 , AXIOMS:4;
end;
thus L42: thesis by L34 , PRE_POLY:def 12;
end;
theorem
L43: (for B12 , B13 being set holds (for B14 , B15 being (bag of B13) holds (for B16 , B17 being (bag of B12) holds ((B16 = ( B14 | B12 ) & B17 = ( B15 | B12 ) & B14 divides B15) implies B16 divides B17))))
proof
let C12 , C13 being set;
let C14 , C15 being (bag of C13);
let C16 , C17 being (bag of C12);
assume that
L44: (C16 = ( C14 | C12 ) & C17 = ( C15 | C12 ))
and
L45: C14 divides C15;
L46:
now
let C18 being set;
L47: ( dom C16 ) = C12 by PARTFUN1:def 2
.= ( dom C17 ) by PARTFUN1:def 2;
per cases ;
suppose L48: (not C18 in ( dom C16 ));

L49: ( C16 . C18 ) = ( {} ) by L48 , FUNCT_1:def 2
.= ( C17 . C18 ) by L47 , L48 , FUNCT_1:def 2;
thus L50: ( C16 . C18 ) <= ( C17 . C18 ) by L49;
end;
suppose L51: C18 in ( dom C16 );

L52: (( C16 . C18 ) = ( C14 . C18 ) & ( C17 . C18 ) = ( C15 . C18 )) by L51 , L44 , L47 , FUNCT_1:47;
thus L53: ( C16 . C18 ) <= ( C17 . C18 ) by L52 , L45 , PRE_POLY:def 11;
end;
end;
thus L55: thesis by L46 , PRE_POLY:def 11;
end;
theorem
L56: (for B18 , B19 being set holds (for B20 , B21 being (bag of B19) holds (for B22 , B23 being (bag of B18) holds ((B22 = ( B20 | B18 ) & B23 = ( B21 | B18 )) implies (( ( B20 -' B21 ) | B18 ) = ( B22 -' B23 ) & ( ( B20 + B21 ) | B18 ) = ( B22 + B23 ))))))
proof
let C19 , C20 being set;
let C21 , C22 being (bag of C20);
let C23 , C24 being (bag of C19);
assume that
L57: C23 = ( C21 | C19 )
and
L58: C24 = ( C22 | C19 );
L59: ( dom C21 ) = C20 by PARTFUN1:def 2;
L60: ( dom ( C21 | C19 ) ) = ( C20 /\ C19 ) by L59 , RELAT_1:61;
L61: ( dom C22 ) = C20 by PARTFUN1:def 2;
L62: ( dom ( C22 | C19 ) ) = ( C20 /\ C19 ) by L61 , RELAT_1:61;
L63: ( dom ( C21 + C22 ) ) = C20 by PARTFUN1:def 2;
L64: ( dom ( ( C21 + C22 ) | C19 ) ) = ( C20 /\ C19 ) by L63 , RELAT_1:61;
L65:
now
let C25 being set;
assume L66: C25 in ( C20 /\ C19 );
thus L67: ( ( ( C21 + C22 ) | C19 ) . C25 ) = ( ( C21 + C22 ) . C25 ) by L66 , L64 , FUNCT_1:47
.= ( ( C21 . C25 ) + ( C22 . C25 ) ) by PRE_POLY:def 5
.= ( ( C23 . C25 ) + ( C22 . C25 ) ) by L57 , L60 , L66 , FUNCT_1:47
.= ( ( C23 . C25 ) + ( C24 . C25 ) ) by L58 , L62 , L66 , FUNCT_1:47
.= ( ( C23 + C24 ) . C25 ) by PRE_POLY:def 5;
end;
L68: ( dom ( C21 -' C22 ) ) = C20 by PARTFUN1:def 2;
L69: ( dom ( ( C21 -' C22 ) | C19 ) ) = ( C20 /\ C19 ) by L68 , RELAT_1:61;
L70:
now
let C26 being set;
assume L71: C26 in ( C20 /\ C19 );
thus L72: ( ( ( C21 -' C22 ) | C19 ) . C26 ) = ( ( C21 -' C22 ) . C26 ) by L71 , L69 , FUNCT_1:47
.= ( ( C21 . C26 ) -' ( C22 . C26 ) ) by PRE_POLY:def 6
.= ( ( C23 . C26 ) -' ( C22 . C26 ) ) by L57 , L60 , L71 , FUNCT_1:47
.= ( ( C23 . C26 ) -' ( C24 . C26 ) ) by L58 , L62 , L71 , FUNCT_1:47
.= ( ( C23 -' C24 ) . C26 ) by PRE_POLY:def 6;
end;
L73: ( dom ( C23 -' C24 ) ) = C19 by PARTFUN1:def 2
.= ( C20 /\ C19 ) by L57 , L60 , PARTFUN1:def 2;
thus L74: ( ( C21 -' C22 ) | C19 ) = ( C23 -' C24 ) by L73 , L69 , L70 , FUNCT_1:2;
L75: ( dom ( C23 + C24 ) ) = C19 by PARTFUN1:def 2
.= ( C20 /\ C19 ) by L57 , L60 , PARTFUN1:def 2;
thus L76: thesis by L75 , L64 , L65 , FUNCT_1:2;
end;
definition
let C27 , C28 being Nat;
let C29 being (bag of C27);
func C29 bag_extend C28 -> (Element of ( Bags ( C27 + 1 ) )) means 
:L77: (( it | C27 ) = C29 & ( it . C27 ) = C28);
existence
proof
set D4 = ( C29 +* ( C27 .--> C28 ) );
L78: ( dom C29 ) = C27 by PARTFUN1:def 2;
L79: ( dom D4 ) = ( ( dom C29 ) \/ ( dom ( C27 .--> C28 ) ) ) by FUNCT_4:def 1
.= ( ( dom C29 ) \/ { C27 } ) by FUNCOP_1:13
.= ( C27 \/ { C27 } ) by PARTFUN1:def 2
.= ( succ C27 ) by ORDINAL1:def 1
.= ( C27 + 1 ) by NAT_1:38;
L80: D4 is (ManySortedSet of ( C27 + 1 )) by L79 , PARTFUN1:def 2 , RELAT_1:def 18;
reconsider D5 = D4 as (Element of ( Bags ( C27 + 1 ) )) by L80 , PRE_POLY:def 12;
take D5;
L81: ( dom ( D5 | C27 ) ) = ( ( C27 + 1 ) /\ C27 ) by L79 , RELAT_1:61
.= ( ( succ C27 ) /\ C27 ) by NAT_1:38
.= ( ( C27 \/ { C27 } ) /\ C27 ) by ORDINAL1:def 1
.= C27 by XBOOLE_1:21;
L82:
now
let C30 being set;
assume L83: C30 in C27;
L84: C30 in ( ( dom C29 ) \/ ( dom ( C27 .--> C28 ) ) ) by L83 , L78 , XBOOLE_0:def 3;
L85:
now
assume L86: C30 in ( dom ( C27 .--> C28 ) );
L87: C30 in { C27 } by L86;
L88: C30 = C27 by L87 , TARSKI:def 1;
thus L89: contradiction by L88 , L83;
end;
thus L90: ( ( D5 | C27 ) . C30 ) = ( D5 . C30 ) by L81 , L83 , FUNCT_1:47
.= ( C29 . C30 ) by L84 , L85 , FUNCT_4:def 1;
end;
thus L91: ( D5 | C27 ) = C29 by L82 , L81 , L78 , FUNCT_1:2;
L92: C27 in { C27 } by TARSKI:def 1;
L93: C27 in ( dom ( C27 .--> C28 ) ) by L92 , FUNCOP_1:13;
L94: C27 in ( ( dom C29 ) \/ ( dom ( C27 .--> C28 ) ) ) by L93 , XBOOLE_0:def 3;
thus L95: ( D5 . C27 ) = ( ( C27 .--> C28 ) . C27 ) by L94 , L93 , FUNCT_4:def 1
.= C28 by FUNCOP_1:72;
end;
uniqueness
proof
let C31 , C32 being (Element of ( Bags ( C27 + 1 ) ));
assume that
L96: ( C31 | C27 ) = C29
and
L97: ( C31 . C27 ) = C28
and
L98: ( C32 | C27 ) = C29
and
L99: ( C32 . C27 ) = C28;
L100: ( dom C31 ) = ( C27 + 1 ) by PARTFUN1:def 2;
L101:
now
let C33 being set;
assume L102: C33 in ( C27 + 1 );
L103: C33 in ( succ C27 ) by L102 , NAT_1:38;
L104: C33 in ( C27 \/ { C27 } ) by L103 , ORDINAL1:def 1;
per cases ;
suppose L105: C33 in { C27 };

L106: C33 = C27 by L105 , TARSKI:def 1;
thus L107: ( C31 . C33 ) = ( C32 . C33 ) by L106 , L97 , L99;
end;
suppose L108: (not C33 in { C27 });

L109: C33 in C27 by L108 , L104 , XBOOLE_0:def 3;
L110: C33 in ( ( C27 + 1 ) /\ C27 ) by L109 , L102 , XBOOLE_0:def 4;
L111: C33 in ( dom C29 ) by L110 , L96 , L100 , RELAT_1:61;
thus L112: ( C31 . C33 ) = ( C29 . C33 ) by L111 , L96 , FUNCT_1:47
.= ( C32 . C33 ) by L98 , L111 , FUNCT_1:47;
end;
end;
L114: ( dom C32 ) = ( C27 + 1 ) by PARTFUN1:def 2;
thus L115: thesis by L114 , L100 , L101 , FUNCT_1:2;
end;
end;
theorem
L117: (for B24 being (Element of ( NAT )) holds ( EmptyBag ( B24 + 1 ) ) = ( ( EmptyBag B24 ) bag_extend ( 0 ) ))
proof
let C34 being (Element of ( NAT ));
L118:
now
let C35 being set;
assume L119: C35 in ( C34 + 1 );
L120: C35 in ( succ C34 ) by L119 , NAT_1:38;
L121: C35 in ( C34 \/ { C34 } ) by L120 , ORDINAL1:def 1;
per cases  by L121 , XBOOLE_0:def 3;
suppose L122: C35 in C34;

thus L123: ( ( EmptyBag ( C34 + 1 ) ) . C35 ) = ( 0 ) by PRE_POLY:52
.= ( ( EmptyBag C34 ) . C35 ) by PRE_POLY:52
.= ( ( ( ( EmptyBag C34 ) bag_extend ( 0 ) ) | C34 ) . C35 ) by L77
.= ( ( ( EmptyBag C34 ) bag_extend ( 0 ) ) . C35 ) by L122 , FUNCT_1:49;
end;
suppose L124: C35 in { C34 };

thus L125: ( ( EmptyBag ( C34 + 1 ) ) . C35 ) = ( 0 ) by PRE_POLY:52
.= ( ( ( EmptyBag C34 ) bag_extend ( 0 ) ) . C34 ) by L77
.= ( ( ( EmptyBag C34 ) bag_extend ( 0 ) ) . C35 ) by L124 , TARSKI:def 1;
end;
end;
L127: (( dom ( EmptyBag ( C34 + 1 ) ) ) = ( C34 + 1 ) & ( dom ( ( EmptyBag C34 ) bag_extend ( 0 ) ) ) = ( C34 + 1 )) by PARTFUN1:def 2;
thus L128: thesis by L127 , L118 , FUNCT_1:2;
end;
theorem
L129: (for B25 being Ordinal holds (for B26 , B27 being (bag of B25) holds (B27 in ( rng ( divisors B26 ) ) iff B27 divides B26)))
proof
let C36 being Ordinal;
let C37 , C38 being (bag of C36);
consider C39 being non  empty  finite (Subset of ( Bags C36 )) such that L130: ( divisors C37 ) = ( SgmX (( BagOrder C36 ) , C39) ) and L131: (for B28 being (bag of C36) holds (B28 in C39 iff B28 divides C37)) by PRE_POLY:def 16;
L132: ( field ( BagOrder C36 ) ) = ( Bags C36 ) by ORDERS_1:15;
L133: ( BagOrder C36 ) linearly_orders C39 by L132 , ORDERS_1:37 , ORDERS_1:38;
thus L134:now
assume L135: C38 in ( rng ( divisors C37 ) );
L136: C38 in C39 by L135 , L130 , L133 , PRE_POLY:def 2;
thus L137: C38 divides C37 by L136 , L131;
end;
assume L138: C38 divides C37;
L139: C38 in C39 by L138 , L131;
thus L140: thesis by L139 , L130 , L133 , PRE_POLY:def 2;
end;
definition
let C40 being set;
let C41 being (Element of C40);
func UnitBag C41 -> (Element of ( Bags C40 )) equals 
( ( EmptyBag C40 ) +* (C41 , 1) );
coherence by PRE_POLY:def 12;
end;
theorem
L142: (for B29 being non  empty set holds (for B30 being (Element of B29) holds ( support ( UnitBag B30 ) ) = { B30 }))
proof
let C42 being non  empty set;
let C43 being (Element of C42);
L143:
now
let C44 being set;
thus L144:now
assume L145: C44 in ( support ( UnitBag C43 ) );
L146:
now
assume L147: C44 <> C43;
L148: ( ( ( EmptyBag C42 ) +* (C43 , 1) ) . C44 ) = ( ( EmptyBag C42 ) . C44 ) by L147 , FUNCT_7:32
.= ( 0 ) by PRE_POLY:52;
thus L149: contradiction by L148 , L145 , PRE_POLY:def 7;
end;
thus L150: C44 in { C43 } by L146 , TARSKI:def 1;
end;
L151: ( EmptyBag C42 ) = ( C42 --> ( 0 ) ) by PRE_POLY:def 13;
L152: ( dom ( EmptyBag C42 ) ) = C42 by L151 , FUNCOP_1:13;
assume L153: C44 in { C43 };
L154: C44 = C43 by L153 , TARSKI:def 1;
L155: ( ( UnitBag C43 ) . C44 ) = 1 by L154 , L152 , FUNCT_7:31;
thus L156: C44 in ( support ( UnitBag C43 ) ) by L155 , PRE_POLY:def 7;
end;
thus L157: thesis by L143 , TARSKI:1;
end;
theorem
L158: (for B31 being non  empty set holds (for B32 being (Element of B31) holds (( ( UnitBag B32 ) . B32 ) = 1 & (for B33 being (Element of B31) holds (B32 <> B33 implies ( ( UnitBag B32 ) . B33 ) = ( 0 ))))))
proof
let C45 being non  empty set;
let C46 being (Element of C45);
L159: ( dom ( C45 --> ( 0 ) ) ) = C45 by FUNCOP_1:13;
thus L160: ( ( UnitBag C46 ) . C46 ) = ( ( ( C45 --> ( 0 ) ) +* (C46 , 1) ) . C46 ) by PRE_POLY:def 13
.= 1 by L159 , FUNCT_7:31;
let C47 being (Element of C45);
assume L161: C46 <> C47;
thus L162: ( ( UnitBag C46 ) . C47 ) = ( ( EmptyBag C45 ) . C47 ) by L161 , FUNCT_7:32
.= ( 0 ) by PRE_POLY:52;
end;
theorem
L163: (for B34 being non  empty set holds (for B35 , B36 being (Element of B34) holds (( UnitBag B35 ) = ( UnitBag B36 ) implies B35 = B36)))
proof
let C48 being non  empty set;
let C49 , C50 being (Element of C48);
assume that
L164: ( UnitBag C49 ) = ( UnitBag C50 )
and
L165: C49 <> C50;
L166: 1 = ( ( UnitBag C50 ) . C49 ) by L164 , L158
.= ( 0 ) by L165 , L158;
thus L167: contradiction by L166;
end;
theorem
L168: (for B37 being non  empty Ordinal holds (for B38 being (Element of B37) holds (for B39 being  well-unital non  trivial doubleLoopStr holds (for B40 being (Function of B37 , B39) holds ( eval (( UnitBag B38 ) , B40) ) = ( B40 . B38 )))))
proof
let C51 being non  empty Ordinal;
let C52 being (Element of C51);
let C53 being  well-unital non  trivial doubleLoopStr;
let C54 being (Function of C51 , C53);
reconsider D6 = ( C54 . C52 ) as (Element of C53);
L169: ( support ( UnitBag C52 ) ) = { C52 } by L142;
thus L170: ( eval (( UnitBag C52 ) , C54) ) = ( ( power C53 ) . (( C54 . C52 ) , ( ( UnitBag C52 ) . C52 )) ) by L169 , POLYNOM2:15
.= ( ( power C53 ) . (( C54 . C52 ) , ( ( 0 ) + 1 )) ) by L158
.= ( ( ( power C53 ) . (D6 , ( 0 )) ) * D6 ) by GROUP_1:def 7
.= ( ( 1_ C53 ) * D6 ) by GROUP_1:def 7
.= ( C54 . C52 ) by GROUP_1:def 4;
end;
definition
let C55 being set;
let C56 being (Element of C55);
let C57 being  unital non  empty multLoopStr_0;
func 1_1 (C56 , C57) -> (Series of C55 , C57) equals 
( ( 0_ (C55 , C57) ) +* (( UnitBag C56 ) , ( 1_ C57 )) );
coherence;
end;
theorem
L172: (for B41 being set holds (for B42 being  unital non  trivial doubleLoopStr holds (for B43 being (Element of B41) holds (( ( 1_1 (B43 , B42) ) . ( UnitBag B43 ) ) = ( 1_ B42 ) & (for B44 being (bag of B41) holds (B44 <> ( UnitBag B43 ) implies ( ( 1_1 (B43 , B42) ) . B44 ) = ( 0. B42 )))))))
proof
let C58 being set;
let C59 being  unital non  trivial doubleLoopStr;
let C60 being (Element of C58);
L173: ( dom ( 0_ (C58 , C59) ) ) = ( dom ( ( Bags C58 ) --> ( 0. C59 ) ) ) by POLYNOM1:def 7
.= ( Bags C58 ) by FUNCOP_1:13;
thus L174: ( ( 1_1 (C60 , C59) ) . ( UnitBag C60 ) ) = ( 1_ C59 ) by L173 , FUNCT_7:31;
let C61 being (bag of C58);
assume L175: C61 <> ( UnitBag C60 );
thus L176: ( ( 1_1 (C60 , C59) ) . C61 ) = ( ( 0_ (C58 , C59) ) . C61 ) by L175 , FUNCT_7:32
.= ( 0. C59 ) by POLYNOM1:22;
end;
theorem
L177: (for B45 being set holds (for B46 being (Element of B45) holds (for B47 being  add-associative  right_zeroed  right_complementable  well-unital  right-distributive non  trivial doubleLoopStr holds ( Support ( 1_1 (B46 , B47) ) ) = { ( UnitBag B46 ) })))
proof
let C62 being set;
let C63 being (Element of C62);
let C64 being  add-associative  right_zeroed  right_complementable  well-unital  right-distributive non  trivial doubleLoopStr;
L178:
now
let C65 being set;
thus L179:now
assume L180: C65 in ( Support ( 1_1 (C63 , C64) ) );
reconsider D7 = C65 as (Element of ( Bags C62 )) by L180;
L181:
now
assume L182: C65 <> ( UnitBag C63 );
L183: ( ( 1_1 (C63 , C64) ) . D7 ) = ( ( 0_ (C62 , C64) ) . D7 ) by L182 , FUNCT_7:32
.= ( 0. C64 ) by POLYNOM1:22;
thus L184: contradiction by L183 , L180 , POLYNOM1:def 3;
end;
thus L185: C65 in { ( UnitBag C63 ) } by L181 , TARSKI:def 1;
end;
assume L186: C65 in { ( UnitBag C63 ) };
L187: C65 = ( UnitBag C63 ) by L186 , TARSKI:def 1;
L188: ( ( 1_1 (C63 , C64) ) . C65 ) <> ( 0. C64 ) by L187 , L172;
thus L189: C65 in ( Support ( 1_1 (C63 , C64) ) ) by L188 , L186 , POLYNOM1:def 3;
end;
thus L190: thesis by L178 , TARSKI:1;
end;
registration
let C66 being Ordinal;
let C67 being (Element of C66);
let C68 being  add-associative  right_zeroed  right_complementable  well-unital  right-distributive non  trivial doubleLoopStr;
cluster ( 1_1 (C67 , C68) ) ->  finite-Support;
coherence
proof
L191: ( Support ( 1_1 (C67 , C68) ) ) = { ( UnitBag C67 ) } by L177;
thus L192: thesis by L191 , POLYNOM1:def 4;
end;
end;
theorem
L194: (for B48 being  add-associative  right_zeroed  right_complementable  well-unital  right-distributive non  trivial doubleLoopStr holds (for B49 being non  empty set holds (for B50 , B51 being (Element of B49) holds (( 1_1 (B50 , B48) ) = ( 1_1 (B51 , B48) ) implies B50 = B51))))
proof
let C69 being  add-associative  right_zeroed  right_complementable  well-unital  right-distributive non  trivial doubleLoopStr;
let C70 being non  empty set;
let C71 , C72 being (Element of C70);
assume that
L195: ( 1_1 (C71 , C69) ) = ( 1_1 (C72 , C69) )
and
L196: C71 <> C72;
L197: ( 1_ C69 ) = ( ( 1_1 (C72 , C69) ) . ( UnitBag C71 ) ) by L195 , L172
.= ( 0. C69 ) by L196 , L163 , L172;
thus L198: contradiction by L197;
end;
theorem
L199: (for B52 being  add-associative  right_zeroed  right_complementable  distributive non  empty doubleLoopStr holds (for B53 being (Element of ( Polynom-Ring B52 )) holds (for B54 being (sequence of B52) holds (B53 = B54 implies ( - B53 ) = ( - B54 )))))
proof
let C73 being  add-associative  right_zeroed  right_complementable  distributive non  empty doubleLoopStr;
let C74 being (Element of ( Polynom-Ring C73 ));
let C75 being (sequence of C73);
assume L200: C74 = C75;
reconsider D8 = C74 as (Polynomial of C73) by POLYNOM3:def 10;
L201:
now
let C76 being set;
assume L202: C76 in ( NAT );
reconsider D9 = C76 as (Element of ( NAT )) by L202;
thus L203: ( ( C75 - C75 ) . C76 ) = ( ( C75 . D9 ) - ( C75 . D9 ) ) by POLYNOM3:27
.= ( 0. C73 ) by RLVECT_1:15
.= ( ( 0_. C73 ) . C76 ) by L202 , FUNCOP_1:7;
end;
reconsider D10 = ( - D8 ) as (Element of ( Polynom-Ring C73 )) by POLYNOM3:def 10;
L204: (( dom ( 0_. C73 ) ) = ( NAT ) & ( dom ( C75 - C75 ) ) = ( NAT )) by FUNCT_2:def 1;
L205: ( C75 - C75 ) = ( 0_. C73 ) by L204 , L201 , FUNCT_1:2;
L206: ( C74 + D10 ) = ( D8 + ( - D8 ) ) by POLYNOM3:def 10
.= ( 0. ( Polynom-Ring C73 ) ) by L200 , L205 , POLYNOM3:def 10;
L207: C74 = ( - D10 ) by L206 , RLVECT_1:6;
thus L208: thesis by L207 , L200 , RLVECT_1:17;
end;
theorem
L209: (for B55 being  add-associative  right_zeroed  right_complementable  distributive non  empty doubleLoopStr holds (for B56 , B57 being (Element of ( Polynom-Ring B55 )) holds (for B58 , B59 being (sequence of B55) holds ((B56 = B58 & B57 = B59) implies ( B56 - B57 ) = ( B58 - B59 )))))
proof
let C77 being  add-associative  right_zeroed  right_complementable  distributive non  empty doubleLoopStr;
let C78 , C79 being (Element of ( Polynom-Ring C77 ));
let C80 , C81 being (sequence of C77);
assume that
L210: C78 = C80
and
L211: C79 = C81;
L212: ( - C79 ) = ( - C81 ) by L211 , L199;
thus L213: ( C78 - C79 ) = ( C78 + ( - C79 ) ) by RLVECT_1:def 11
.= ( C80 - C81 ) by L210 , L212 , POLYNOM3:def 10;
end;
definition
let C82 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C83 being non  empty (Subset of ( Polynom-Ring C82 ));
func minlen C83 -> non  empty (Subset of C83) equals 
{ B60 where B60 is (Element of C83) : (for B61 , B62 being (Polynomial of C82) holds ((B61 = B60 & B62 in C83) implies ( len B61 ) <= ( len B62 ))) };
coherence
proof
L214: C83 c= C83;
reconsider D11 = C83 as non  empty (Subset of C83) by L214;
defpred S1[ (Element of C83) , (Element of ( NAT )) ] means (for B63 being (Polynomial of C82) holds ($1 = B63 implies $2 = ( len B63 )));
set D12 = { B64 where B64 is (Element of C83) : (for B65 , B66 being (Polynomial of C82) holds ((B65 = B64 & B66 in C83) implies ( len B65 ) <= ( len B66 ))) };
L215:
now
let C84 being (Element of C83);
reconsider D13 = C84 as (Polynomial of C82) by POLYNOM3:def 10;
L216: (for B67 being (Polynomial of C82) holds (C84 = B67 implies ( len D13 ) = ( len B67 )));
thus L217: (ex B68 being (Element of ( NAT )) st S1[ C84 , B68 ]) by L216;
end;
consider C85 being (Function of C83 , ( NAT )) such that L218: (for B69 being (Element of C83) holds S1[ B69 , ( C85 . B69 ) ]) from FUNCT_2:sch 3(L215);
L219: ( min ( C85 .: D11 ) ) in ( C85 .: C83 ) by XXREAL_2:def 7;
consider C86 being set such that L220: C86 in ( dom C85 ) and L221: C86 in C83 and L222: ( min ( C85 .: D11 ) ) = ( C85 . C86 ) by L219 , FUNCT_1:def 6;
reconsider D14 = C86 as (Element of C83) by L220;
L223:
now
let C87 , C88 being (Polynomial of C82);
assume that
L224: C87 = D14
and
L225: C88 in C83;
L226: ( dom C85 ) = C83 by FUNCT_2:def 1;
L227: ( C85 . C88 ) in ( C85 .: C83 ) by L226 , L225 , FUNCT_1:def 6;
L228: ( C85 . D14 ) <= ( C85 . C88 ) by L227 , L222 , XXREAL_2:def 7;
L229: ( len C87 ) <= ( C85 . C88 ) by L228 , L218 , L224;
thus L230: ( len C87 ) <= ( len C88 ) by L229 , L218 , L225;
end;
L231: D14 in D12 by L223;
L232: D12 c= C83
proof
let C89 being set;
assume L233: C89 in D12;
L234: (ex B70 being (Element of C83) st (B70 = C89 & (for B71 , B72 being (Polynomial of C82) holds ((B71 = B70 & B72 in C83) implies ( len B71 ) <= ( len B72 ))))) by L233;
thus L235: thesis by L234;
end;
thus L236: thesis by L232 , L231;
end;
end;
theorem
L238: (for B73 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr holds (for B74 being non  empty (Subset of ( Polynom-Ring B73 )) holds (for B75 , B76 being (Polynomial of B73) holds ((B75 in ( minlen B74 ) & B76 in B74) implies (B75 in B74 & ( len B75 ) <= ( len B76 ))))))
proof
let C90 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C91 being non  empty (Subset of ( Polynom-Ring C90 ));
let C92 , C93 being (Polynomial of C90);
assume that
L239: C92 in ( minlen C91 )
and
L240: C93 in C91;
L241: (ex B77 being (Element of C91) st (B77 = C92 & (for B78 , B79 being (Polynomial of C90) holds ((B78 = B77 & B79 in C91) implies ( len B78 ) <= ( len B79 ))))) by L239;
thus L242: thesis by L241 , L240;
end;
definition
let C94 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C95 being Nat;
let C96 being (Element of C94);
func monomial (C96 , C95) -> (Polynomial of C94) means 
:L243: (for B80 being Nat holds ((B80 = C95 implies ( it . B80 ) = C96) & (B80 <> C95 implies ( it . B80 ) = ( 0. C94 ))));
existence
proof
reconsider D15 = ( ( 0_. C94 ) +* (C95 , C96) ) as (sequence of C94);
L244:
now
let C97 being Nat;
L245: C97 in ( NAT ) by ORDINAL1:def 12;
assume L246: C97 >= ( C95 + 1 );
L247: C97 > C95 by L246 , NAT_1:13;
thus L248: ( D15 . C97 ) = ( ( ( NAT ) --> ( 0. C94 ) ) . C97 ) by L247 , FUNCT_7:32
.= ( 0. C94 ) by L245 , FUNCOP_1:7;
end;
reconsider D16 = D15 as (Polynomial of C94) by L244 , ALGSEQ_1:def 1;
L249:
now
let C98 being Nat;
L250: C98 in ( NAT ) by ORDINAL1:def 12;
thus L251: (C98 = C95 implies ( D16 . C98 ) = C96)
proof
L252: ( dom ( 0_. C94 ) ) = ( NAT ) by FUNCT_2:def 1;
assume L253: C98 = C95;
thus L254: thesis by L253 , L250 , L252 , FUNCT_7:31;
end;

thus L255: (C98 <> C95 implies ( D16 . C98 ) = ( 0. C94 ))
proof
assume L256: C98 <> C95;
thus L257: ( D16 . C98 ) = ( ( ( NAT ) --> ( 0. C94 ) ) . C98 ) by L256 , FUNCT_7:32
.= ( 0. C94 ) by L250 , FUNCOP_1:7;
end;

end;
thus L256: thesis by L249;
end;
uniqueness
proof
let C99 , C100 being (Polynomial of C94);
assume that
L257: (for B81 being Nat holds ((B81 = C95 implies ( C99 . B81 ) = C96) & (B81 <> C95 implies ( C99 . B81 ) = ( 0. C94 ))))
and
L258: (for B82 being Nat holds ((B82 = C95 implies ( C100 . B82 ) = C96) & (B82 <> C95 implies ( C100 . B82 ) = ( 0. C94 ))));
L259:
now
let C101 being set;
assume L260: C101 in ( NAT );
per cases ;
suppose L261: C101 = C95;

thus L262: ( C99 . C101 ) = C96 by L261 , L257
.= ( C100 . C101 ) by L258 , L261;
end;
suppose L263: C101 <> C95;

thus L264: ( C99 . C101 ) = ( 0. C94 ) by L263 , L257 , L260
.= ( C100 . C101 ) by L258 , L260 , L263;
end;
end;
L266: (( dom C99 ) = ( NAT ) & ( dom C100 ) = ( NAT )) by FUNCT_2:def 1;
thus L267: C99 = C100 by L266 , L259 , FUNCT_1:2;
end;
end;
theorem
L269: (for B83 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr holds (for B84 being (Element of ( NAT )) holds (for B85 being (Element of B83) holds ((B85 <> ( 0. B83 ) implies ( len ( monomial (B85 , B84) ) ) = ( B84 + 1 )) & (B85 = ( 0. B83 ) implies ( len ( monomial (B85 , B84) ) ) = ( 0 )) & ( len ( monomial (B85 , B84) ) ) <= ( B84 + 1 )))))
proof
let C102 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C103 being (Element of ( NAT ));
let C104 being (Element of C102);
L270:
now
assume L271: C104 = ( 0. C102 );
L272:
now
let C105 being Nat;
assume L273: C105 >= ( 0 );
per cases ;
suppose L274: C105 = C103;

thus L275: ( ( monomial (C104 , C103) ) . C105 ) = ( 0. C102 ) by L271 , L243;
end;
suppose L276: C105 <> C103;

thus L277: ( ( monomial (C104 , C103) ) . C105 ) = ( 0. C102 ) by L276 , L243;
end;
end;
L279: ( 0 ) is_at_least_length_of ( monomial (C104 , C103) ) by L272 , ALGSEQ_1:def 2;
thus L280: ( len ( monomial (C104 , C103) ) ) = ( 0 ) by L279 , ALGSEQ_1:def 3;
end;
L281:
now
L282:
now
let C106 being Nat;
assume L283: C106 >= ( C103 + 1 );
L284: C106 > C103 by L283 , NAT_1:13;
thus L285: ( ( monomial (C104 , C103) ) . C106 ) = ( 0. C102 ) by L284 , L243;
end;
L286: ( C103 + 1 ) is_at_least_length_of ( monomial (C104 , C103) ) by L282 , ALGSEQ_1:def 2;
L287: ( len ( monomial (C104 , C103) ) ) <= ( C103 + 1 ) by L286 , ALGSEQ_1:def 3;
assume L288: C104 <> ( 0. C102 );
L289: ( ( monomial (C104 , C103) ) . C103 ) <> ( 0. C102 ) by L288 , L243;
L290: ( len ( monomial (C104 , C103) ) ) > C103 by L289 , ALGSEQ_1:8;
L291: ( len ( monomial (C104 , C103) ) ) >= ( C103 + 1 ) by L290 , NAT_1:13;
thus L292: ( len ( monomial (C104 , C103) ) ) = ( C103 + 1 ) by L291 , L287 , XXREAL_0:1;
end;
thus L293: thesis by L281 , L270;
end;
theorem
L294: (for B86 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr holds (for B87 , B88 being (Element of ( NAT )) holds (for B89 being (Element of B86) holds (for B90 being (Polynomial of B86) holds ( ( ( monomial (B89 , B87) ) *' B90 ) . ( B88 + B87 ) ) = ( B89 * ( B90 . B88 ) )))))
proof
let C107 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C108 , C109 being (Element of ( NAT ));
let C110 being (Element of C107);
let C111 being (Polynomial of C107);
consider C112 being (FinSequence of (the carrier of C107)) such that L295: ( len C112 ) = ( ( C109 + C108 ) + 1 ) and L296: ( ( ( monomial (C110 , C108) ) *' C111 ) . ( C109 + C108 ) ) = ( Sum C112 ) and L297: (for B91 being (Element of ( NAT )) holds (B91 in ( dom C112 ) implies ( C112 . B91 ) = ( ( ( monomial (C110 , C108) ) . ( B91 -' 1 ) ) * ( C111 . ( ( ( C109 + C108 ) + 1 ) -' B91 ) ) ))) by POLYNOM3:def 9;
L298: ( len C112 ) = ( C108 + ( 1 + C109 ) ) by L295;
consider C113 , C114 being (FinSequence of (the carrier of C107)) such that L299: ( len C113 ) = C108 and L300: ( len C114 ) = ( 1 + C109 ) and L301: C112 = ( C113 ^ C114 ) by L298 , FINSEQ_2:23;
consider C115 , C116 being (FinSequence of (the carrier of C107)) such that L302: ( len C115 ) = 1 and L303: ( len C116 ) = C109 and L304: C114 = ( C115 ^ C116 ) by L300 , FINSEQ_2:23;
L305: ( dom C115 ) c= ( dom C114 ) by L304 , FINSEQ_1:26;
L306:
now
L307: ( dom C113 ) c= ( dom C112 ) by L301 , FINSEQ_1:26;
let C117 being (Element of ( NAT ));
L308: ( C117 - 1 ) < C117 by XREAL_1:146;
assume L309: C117 in ( dom C113 );
L310: C117 <= C108 by L309 , L299 , FINSEQ_3:25;
L311: 1 <= C117 by L309 , FINSEQ_3:25;
L312: ( C117 -' 1 ) = ( C117 - 1 ) by L311 , XREAL_1:233;
thus L313: ( C113 . C117 ) = ( C112 . C117 ) by L301 , L309 , FINSEQ_1:def 7
.= ( ( ( monomial (C110 , C108) ) . ( C117 -' 1 ) ) * ( C111 . ( ( ( C109 + C108 ) + 1 ) -' C117 ) ) ) by L297 , L309 , L307
.= ( ( 0. C107 ) * ( C111 . ( ( ( C109 + C108 ) + 1 ) -' C117 ) ) ) by L310 , L312 , L308 , L243
.= ( 0. C107 ) by VECTSP_1:7;
end;
L314: ( Sum C113 ) = ( 0. C107 ) by L306 , POLYNOM3:1;
L315:
now
let C118 being (Element of ( NAT ));
L316: ( ( C108 + ( 1 + C118 ) ) -' 1 ) = ( ( ( C108 + C118 ) + 1 ) -' 1 )
.= ( C108 + C118 ) by NAT_D:34;
assume L317: C118 in ( dom C116 );
L318: ( 1 + C118 ) in ( dom C114 ) by L317 , L302 , L304 , FINSEQ_1:28;
L319: C118 >= 1 by L317 , FINSEQ_3:25;
L320: ( C108 + C118 ) >= ( C108 + 1 ) by L319 , XREAL_1:6;
L321: ( C108 + C118 ) > C108 by L320 , NAT_1:13;
thus L322: ( C116 . C118 ) = ( C114 . ( 1 + C118 ) ) by L302 , L304 , L317 , FINSEQ_1:def 7
.= ( C112 . ( C108 + ( 1 + C118 ) ) ) by L299 , L301 , L318 , FINSEQ_1:def 7
.= ( ( ( monomial (C110 , C108) ) . ( ( C108 + ( 1 + C118 ) ) -' 1 ) ) * ( C111 . ( ( ( C109 + C108 ) + 1 ) -' ( C108 + ( 1 + C118 ) ) ) ) ) by L297 , L299 , L301 , L318 , FINSEQ_1:28
.= ( ( 0. C107 ) * ( C111 . ( ( ( C109 + C108 ) + 1 ) -' ( C108 + ( 1 + C118 ) ) ) ) ) by L321 , L316 , L243
.= ( 0. C107 ) by VECTSP_1:7;
end;
L323: ( Sum C116 ) = ( 0. C107 ) by L315 , POLYNOM3:1;
L324: 1 in ( dom C115 ) by L302 , FINSEQ_3:25;
L325: ( C115 . 1 ) = ( C114 . 1 ) by L324 , L304 , FINSEQ_1:def 7
.= ( C112 . ( C108 + 1 ) ) by L299 , L301 , L324 , L305 , FINSEQ_1:def 7
.= ( ( ( monomial (C110 , C108) ) . ( ( C108 + 1 ) -' 1 ) ) * ( C111 . ( ( ( C109 + C108 ) + 1 ) -' ( C108 + 1 ) ) ) ) by L297 , L299 , L301 , L324 , L305 , FINSEQ_1:28
.= ( ( ( monomial (C110 , C108) ) . C108 ) * ( C111 . ( ( C109 + ( C108 + 1 ) ) -' ( C108 + 1 ) ) ) ) by NAT_D:34
.= ( ( ( monomial (C110 , C108) ) . C108 ) * ( C111 . C109 ) ) by NAT_D:34
.= ( C110 * ( C111 . C109 ) ) by L243;
L326: C115 = <* ( C110 * ( C111 . C109 ) ) *> by L325 , L302 , FINSEQ_1:40;
L327: ( Sum C115 ) = ( C110 * ( C111 . C109 ) ) by L326 , RLVECT_1:44;
L328: ( Sum C114 ) = ( ( C110 * ( C111 . C109 ) ) + ( 0. C107 ) ) by L327 , L304 , L323 , RLVECT_1:41
.= ( C110 * ( C111 . C109 ) ) by RLVECT_1:4;
thus L329: ( ( ( monomial (C110 , C108) ) *' C111 ) . ( C109 + C108 ) ) = ( ( 0. C107 ) + ( C110 * ( C111 . C109 ) ) ) by L328 , L296 , L301 , L314 , RLVECT_1:41
.= ( C110 * ( C111 . C109 ) ) by RLVECT_1:4;
end;
theorem
L330: (for B92 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr holds (for B93 , B94 being (Element of ( NAT )) holds (for B95 being (Element of B92) holds (for B96 being (Polynomial of B92) holds ( ( B96 *' ( monomial (B95 , B93) ) ) . ( B94 + B93 ) ) = ( ( B96 . B94 ) * B95 )))))
proof
let C119 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C120 , C121 being (Element of ( NAT ));
let C122 being (Element of C119);
let C123 being (Polynomial of C119);
consider C124 being (FinSequence of (the carrier of C119)) such that L331: ( len C124 ) = ( ( C121 + C120 ) + 1 ) and L332: ( ( C123 *' ( monomial (C122 , C120) ) ) . ( C121 + C120 ) ) = ( Sum C124 ) and L333: (for B97 being (Element of ( NAT )) holds (B97 in ( dom C124 ) implies ( C124 . B97 ) = ( ( C123 . ( B97 -' 1 ) ) * ( ( monomial (C122 , C120) ) . ( ( ( C121 + C120 ) + 1 ) -' B97 ) ) ))) by POLYNOM3:def 9;
L334: ( len C124 ) = ( C121 + ( C120 + 1 ) ) by L331;
consider C125 , C126 being (FinSequence of (the carrier of C119)) such that L335: ( len C125 ) = C121 and L336: ( len C126 ) = ( C120 + 1 ) and L337: C124 = ( C125 ^ C126 ) by L334 , FINSEQ_2:23;
consider C127 , C128 being (FinSequence of (the carrier of C119)) such that L338: ( len C127 ) = 1 and L339: ( len C128 ) = C120 and L340: C126 = ( C127 ^ C128 ) by L336 , FINSEQ_2:23;
L341: ( dom C127 ) c= ( dom C126 ) by L340 , FINSEQ_1:26;
L342:
now
let C129 being (Element of ( NAT ));
L343: C120 > ( C120 - 1 ) by XREAL_1:146;
assume L344: C129 in ( dom C128 );
L345: ( 1 + C129 ) in ( dom C126 ) by L344 , L338 , L340 , FINSEQ_1:28;
L346: C129 <= C120 by L339 , L344 , FINSEQ_3:25;
L347: ( C121 + C129 ) <= ( C121 + C120 ) by L346 , XREAL_1:6;
L348: ( ( C121 + C129 ) + 1 ) <= ( ( C121 + C120 ) + 1 ) by L347 , XREAL_1:6;
L349: ( ( ( C121 + C120 ) + 1 ) -' ( C121 + ( 1 + C129 ) ) ) = ( ( ( C121 + C120 ) + 1 ) - ( C121 + ( 1 + C129 ) ) ) by L348 , XREAL_1:233;
L350: 1 <= C129 by L344 , FINSEQ_3:25;
L351: ( C120 - C129 ) <= ( C120 - 1 ) by L350 , XREAL_1:13;
thus L352: ( C128 . C129 ) = ( C126 . ( 1 + C129 ) ) by L338 , L340 , L344 , FINSEQ_1:def 7
.= ( C124 . ( C121 + ( 1 + C129 ) ) ) by L335 , L337 , L345 , FINSEQ_1:def 7
.= ( ( C123 . ( ( C121 + ( 1 + C129 ) ) -' 1 ) ) * ( ( monomial (C122 , C120) ) . ( ( ( C121 + C120 ) + 1 ) -' ( C121 + ( 1 + C129 ) ) ) ) ) by L333 , L335 , L337 , L345 , FINSEQ_1:28
.= ( ( C123 . ( ( C121 + ( 1 + C129 ) ) -' 1 ) ) * ( 0. C119 ) ) by L349 , L351 , L343 , L243
.= ( 0. C119 ) by VECTSP_1:6;
end;
L353: ( Sum C128 ) = ( 0. C119 ) by L342 , POLYNOM3:1;
L354:
now
let C130 being (Element of ( NAT ));
L355: ( dom C125 ) c= ( dom C124 ) by L337 , FINSEQ_1:26;
assume L356: C130 in ( dom C125 );
L357: C130 <= C121 by L356 , L335 , FINSEQ_3:25;
L358: ( C130 + C120 ) <= ( C121 + C120 ) by L357 , XREAL_1:6;
L359: ( C130 + C120 ) < ( ( C121 + C120 ) + 1 ) by L358 , NAT_1:13;
L360: C120 < ( ( ( C121 + C120 ) + 1 ) - C130 ) by L359 , XREAL_1:20;
L361: ( ( ( C121 + C120 ) + 1 ) - C130 ) = ( ( ( C121 + C120 ) + 1 ) -' C130 ) by L360 , XREAL_0:def 2;
thus L362: ( C125 . C130 ) = ( C124 . C130 ) by L337 , L356 , FINSEQ_1:def 7
.= ( ( C123 . ( C130 -' 1 ) ) * ( ( monomial (C122 , C120) ) . ( ( ( C121 + C120 ) + 1 ) -' C130 ) ) ) by L333 , L356 , L355
.= ( ( C123 . ( C130 -' 1 ) ) * ( 0. C119 ) ) by L360 , L361 , L243
.= ( 0. C119 ) by VECTSP_1:6;
end;
L363: ( Sum C125 ) = ( 0. C119 ) by L354 , POLYNOM3:1;
L364: 1 in ( dom C127 ) by L338 , FINSEQ_3:25;
L365: ( C127 . 1 ) = ( C126 . 1 ) by L364 , L340 , FINSEQ_1:def 7
.= ( C124 . ( C121 + 1 ) ) by L335 , L337 , L364 , L341 , FINSEQ_1:def 7
.= ( ( C123 . ( ( C121 + 1 ) -' 1 ) ) * ( ( monomial (C122 , C120) ) . ( ( ( C121 + C120 ) + 1 ) -' ( C121 + 1 ) ) ) ) by L333 , L335 , L337 , L364 , L341 , FINSEQ_1:28
.= ( ( C123 . C121 ) * ( ( monomial (C122 , C120) ) . ( ( C120 + ( C121 + 1 ) ) -' ( C121 + 1 ) ) ) ) by NAT_D:34
.= ( ( C123 . C121 ) * ( ( monomial (C122 , C120) ) . C120 ) ) by NAT_D:34
.= ( ( C123 . C121 ) * C122 ) by L243;
L366: C127 = <* ( ( C123 . C121 ) * C122 ) *> by L365 , L338 , FINSEQ_1:40;
L367: ( Sum C127 ) = ( ( C123 . C121 ) * C122 ) by L366 , RLVECT_1:44;
L368: ( Sum C126 ) = ( ( ( C123 . C121 ) * C122 ) + ( 0. C119 ) ) by L367 , L340 , L353 , RLVECT_1:41
.= ( ( C123 . C121 ) * C122 ) by RLVECT_1:4;
thus L369: ( ( C123 *' ( monomial (C122 , C120) ) ) . ( C121 + C120 ) ) = ( ( 0. C119 ) + ( ( C123 . C121 ) * C122 ) ) by L368 , L332 , L337 , L363 , RLVECT_1:41
.= ( ( C123 . C121 ) * C122 ) by RLVECT_1:4;
end;
theorem
L370: (for B98 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr holds (for B99 , B100 being (Polynomial of B98) holds ( len ( B99 *' B100 ) ) <= ( ( ( len B99 ) + ( len B100 ) ) -' 1 )))
proof
let C131 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  empty doubleLoopStr;
let C132 , C133 being (Polynomial of C131);
L371:
now
let C134 being Nat;
L372: ( ( ( len C132 ) + ( len C133 ) ) -' 1 ) >= ( ( ( len C132 ) + ( len C133 ) ) - 1 ) by XREAL_0:def 2;
L373: C134 in ( NAT ) by ORDINAL1:def 12;
consider C135 being (FinSequence of (the carrier of C131)) such that L374: ( len C135 ) = ( C134 + 1 ) and L375: ( ( C132 *' C133 ) . C134 ) = ( Sum C135 ) and L376: (for B101 being (Element of ( NAT )) holds (B101 in ( dom C135 ) implies ( C135 . B101 ) = ( ( C132 . ( B101 -' 1 ) ) * ( C133 . ( ( C134 + 1 ) -' B101 ) ) ))) by L373 , POLYNOM3:def 9;
assume L377: C134 >= ( ( ( len C132 ) + ( len C133 ) ) -' 1 );
L378: C134 >= ( ( len C132 ) + ( ( len C133 ) - 1 ) ) by L377 , L372 , XXREAL_0:2;
L379: ( len C132 ) <= ( C134 - ( ( len C133 ) - 1 ) ) by L378 , XREAL_1:19;
L380: ( - ( len C132 ) ) >= ( - ( ( C134 - ( len C133 ) ) + 1 ) ) by L379 , XREAL_1:24;
L381:
now
let C136 being (Element of ( NAT ));
assume L382: C136 in ( dom C135 );
L383: ( C135 . C136 ) = ( ( C132 . ( C136 -' 1 ) ) * ( C133 . ( ( C134 + 1 ) -' C136 ) ) ) by L382 , L376;
L384: C136 in ( Seg ( len C135 ) ) by L382 , FINSEQ_1:def 3;
L385: C136 <= ( C134 + 1 ) by L384 , L374 , FINSEQ_1:1;
L386: ( ( C134 + 1 ) - C136 ) >= ( 0 ) by L385 , XREAL_1:48;
per cases ;
suppose L387: ( C136 -' 1 ) < ( len C132 );

L388: ( C136 - 1 ) < ( len C132 ) by L387 , XREAL_0:def 2;
L389: ( - ( C136 - 1 ) ) > ( - ( len C132 ) ) by L388 , XREAL_1:24;
L390: ( 1 - C136 ) > ( ( ( len C133 ) - 1 ) - C134 ) by L389 , L380 , XXREAL_0:2;
L391: ( C134 + ( 1 - C136 ) ) > ( ( len C133 ) - 1 ) by L390 , XREAL_1:19;
L392: ( ( C134 + 1 ) -' C136 ) > ( ( len C133 ) - 1 ) by L391 , L386 , XREAL_0:def 2;
L393: ( ( C134 + 1 ) -' C136 ) >= ( ( ( len C133 ) - 1 ) + 1 ) by L392 , INT_1:7;
L394: ( C133 . ( ( C134 + 1 ) -' C136 ) ) = ( 0. C131 ) by L393 , ALGSEQ_1:8;
thus L395: ( C135 . C136 ) = ( 0. C131 ) by L394 , L383 , VECTSP_1:6;
end;
suppose L396: ( C136 -' 1 ) >= ( len C132 );

L397: ( C132 . ( C136 -' 1 ) ) = ( 0. C131 ) by L396 , ALGSEQ_1:8;
thus L398: ( C135 . C136 ) = ( 0. C131 ) by L397 , L383 , VECTSP_1:7;
end;
end;
thus L400: ( ( C132 *' C133 ) . C134 ) = ( 0. C131 ) by L381 , L375 , POLYNOM3:1;
end;
L401: ( ( ( len C132 ) + ( len C133 ) ) -' 1 ) is_at_least_length_of ( C132 *' C133 ) by L371 , ALGSEQ_1:def 2;
thus L402: thesis by L401 , ALGSEQ_1:def 3;
end;
begin
theorem
L403: (for B102 , B103 being non  empty doubleLoopStr holds (for B104 being (Ideal of B102) holds (for B105 being (Function of B102 , B103) holds (B105 is  RingIsomorphism implies ( B105 .: B104 ) is (Ideal of B103)))))
proof
let C137 , C138 being non  empty doubleLoopStr;
let C139 being (Ideal of C137);
let C140 being (Function of C137 , C138);
set D17 = ( C140 .: C139 );
assume L404: C140 is  RingIsomorphism;
L405:
now
let C141 , C142 being (Element of C138);
assume L406: C142 in D17;
consider C143 being set such that L407: C143 in (the carrier of C137) and L408: C143 in C139 and L409: C142 = ( C140 . C143 ) by L406 , FUNCT_2:64;
reconsider D18 = C143 as (Element of C137) by L407;
L410: C140 is  RingMonomorphism  RingEpimorphism by L404 , QUOFIELD:def 21;
L411: ( rng C140 ) = (the carrier of C138) by L410 , QUOFIELD:def 19;
consider C144 being set such that L412: C144 in ( dom C140 ) and L413: C141 = ( C140 . C144 ) by L411 , FUNCT_1:def 3;
reconsider D19 = C144 as (Element of C137) by L412;
L414: ( D19 * D18 ) in C139 by L408 , IDEAL_1:def 2;
L415: C140 is  RingHomomorphism by L410 , QUOFIELD:def 19;
L416: C140 is  multiplicative by L415 , QUOFIELD:def 18;
L417: ( C141 * C142 ) = ( C140 . ( D19 * D18 ) ) by L416 , L409 , L413 , GROUP_6:def 6;
thus L418: ( C141 * C142 ) in D17 by L417 , L414 , FUNCT_2:35;
end;
L419:
now
let C145 , C146 being (Element of C138);
assume L420: C146 in D17;
consider C147 being set such that L421: C147 in (the carrier of C137) and L422: C147 in C139 and L423: C146 = ( C140 . C147 ) by L420 , FUNCT_2:64;
reconsider D20 = C147 as (Element of C137) by L421;
L424: C140 is  RingMonomorphism  RingEpimorphism by L404 , QUOFIELD:def 21;
L425: ( rng C140 ) = (the carrier of C138) by L424 , QUOFIELD:def 19;
consider C148 being set such that L426: C148 in ( dom C140 ) and L427: C145 = ( C140 . C148 ) by L425 , FUNCT_1:def 3;
reconsider D21 = C148 as (Element of C137) by L426;
L428: ( D20 * D21 ) in C139 by L422 , IDEAL_1:def 3;
L429: C140 is  RingHomomorphism by L424 , QUOFIELD:def 19;
L430: C140 is  multiplicative by L429 , QUOFIELD:def 18;
L431: ( C146 * C145 ) = ( C140 . ( D20 * D21 ) ) by L430 , L423 , L427 , GROUP_6:def 6;
thus L432: ( C146 * C145 ) in D17 by L431 , L428 , FUNCT_2:35;
end;
L433:
now
let C149 , C150 being (Element of C138);
assume that
L434: C149 in D17
and
L435: C150 in D17;
consider C151 being set such that L436: C151 in (the carrier of C137) and L437: C151 in C139 and L438: C149 = ( C140 . C151 ) by L434 , FUNCT_2:64;
consider C152 being set such that L439: C152 in (the carrier of C137) and L440: C152 in C139 and L441: C150 = ( C140 . C152 ) by L435 , FUNCT_2:64;
reconsider D22 = C151 , D23 = C152 as (Element of C137) by L436 , L439;
L442: ( D22 + D23 ) in C139 by L437 , L440 , IDEAL_1:def 1;
L443: C140 is  RingMonomorphism  RingEpimorphism by L404 , QUOFIELD:def 21;
L444: C140 is  RingHomomorphism by L443 , QUOFIELD:def 19;
L445: C140 is  additive by L444 , QUOFIELD:def 18;
L446: ( C149 + C150 ) = ( C140 . ( D22 + D23 ) ) by L445 , L438 , L441 , VECTSP_1:def 20;
thus L447: ( C149 + C150 ) in D17 by L446 , L442 , FUNCT_2:35;
end;
thus L448: thesis by L433 , L405 , L419 , IDEAL_1:def 1 , IDEAL_1:def 2 , IDEAL_1:def 3;
end;
theorem
L449: (for B106 , B107 being  add-associative  right_zeroed  right_complementable non  empty doubleLoopStr holds (for B108 being (Function of B106 , B107) holds (B108 is  RingHomomorphism implies ( B108 . ( 0. B106 ) ) = ( 0. B107 ))))
proof
let C153 , C154 being  add-associative  right_zeroed  right_complementable non  empty doubleLoopStr;
let C155 being (Function of C153 , C154);
assume L450: C155 is  RingHomomorphism;
L451: C155 is  additive by L450 , QUOFIELD:def 18;
L452: ( C155 . ( 0. C153 ) ) = ( C155 . ( ( 0. C153 ) + ( 0. C153 ) ) ) by RLVECT_1:4
.= ( ( C155 . ( 0. C153 ) ) + ( C155 . ( 0. C153 ) ) ) by L451 , VECTSP_1:def 20;
L453: ( 0. C154 ) = ( ( ( C155 . ( 0. C153 ) ) + ( C155 . ( 0. C153 ) ) ) + ( - ( C155 . ( 0. C153 ) ) ) ) by L452 , RLVECT_1:def 10
.= ( ( C155 . ( 0. C153 ) ) + ( ( C155 . ( 0. C153 ) ) + ( - ( C155 . ( 0. C153 ) ) ) ) ) by RLVECT_1:def 3
.= ( ( C155 . ( 0. C153 ) ) + ( 0. C154 ) ) by RLVECT_1:def 10
.= ( C155 . ( 0. C153 ) ) by RLVECT_1:4;
thus L454: thesis by L453;
end;
theorem
L455: (for B109 , B110 being  add-associative  right_zeroed  right_complementable non  empty doubleLoopStr holds (for B111 being non  empty (Subset of B109) holds (for B112 being non  empty (Subset of B110) holds (for B113 being (Function of B109 , B110) holds (for B114 being (LinearCombination of B111) holds (for B115 being (LinearCombination of B112) holds (for B116 being (FinSequence of [: (the carrier of B109) , (the carrier of B109) , (the carrier of B109) :]) holds ((B113 is  RingHomomorphism & ( len B114 ) = ( len B115 ) & B116 represents B114 & (for B117 being set holds (B117 in ( dom B115 ) implies ( B115 . B117 ) = ( ( ( B113 . ( ( B116 /. B117 ) `1_3 ) ) * ( B113 . ( ( B116 /. B117 ) `2_3 ) ) ) * ( B113 . ( ( B116 /. B117 ) `3_3 ) ) )))) implies ( B113 . ( Sum B114 ) ) = ( Sum B115 )))))))))
proof
let C156 , C157 being  add-associative  right_zeroed  right_complementable non  empty doubleLoopStr;
let C158 being non  empty (Subset of C156);
let C159 being non  empty (Subset of C157);
let C160 being (Function of C156 , C157);
let C161 being (LinearCombination of C158);
let C162 being (LinearCombination of C159);
let C163 being (FinSequence of [: (the carrier of C156) , (the carrier of C156) , (the carrier of C156) :]);
assume that
L456: C160 is  RingHomomorphism
and
L457: ( len C161 ) = ( len C162 )
and
L458: C163 represents C161
and
L459: (for B118 being set holds (B118 in ( dom C162 ) implies ( C162 . B118 ) = ( ( ( C160 . ( ( C163 /. B118 ) `1_3 ) ) * ( C160 . ( ( C163 /. B118 ) `2_3 ) ) ) * ( C160 . ( ( C163 /. B118 ) `3_3 ) ) )));
defpred S2[ (Element of ( NAT )) ] means (for B119 being (LinearCombination of C158) holds (for B120 being (LinearCombination of C159) holds ((B119 = ( C161 | ( Seg $1 ) ) & B120 = ( C162 | ( Seg $1 ) )) implies ( C160 . ( Sum B119 ) ) = ( Sum B120 ))));
L460: C160 is  additive  multiplicative by L456 , QUOFIELD:def 18;
L461: ( dom C161 ) = ( dom C162 ) by L457 , FINSEQ_3:29;
L462: (for B121 being (Element of ( NAT )) holds (S2[ B121 ] implies S2[ ( B121 + 1 ) ]))
proof
let C164 being (Element of ( NAT ));
assume L463: S2[ C164 ];
thus L464: S2[ ( C164 + 1 ) ]
proof
let C165 being (LinearCombination of C158);
let C166 being (LinearCombination of C159);
assume that
L465: C165 = ( C161 | ( Seg ( C164 + 1 ) ) )
and
L466: C166 = ( C162 | ( Seg ( C164 + 1 ) ) );
per cases ;
suppose L467: ( len C161 ) < ( C164 + 1 );

L468: ( len C161 ) <= C164 by L467 , NAT_1:13;
L469: C165 = C161 by L465 , L467 , FINSEQ_3:49
.= ( C161 | ( Seg C164 ) ) by L468 , FINSEQ_3:49;
L470: C166 = C162 by L457 , L466 , L467 , FINSEQ_3:49
.= ( C162 | ( Seg C164 ) ) by L457 , L468 , FINSEQ_3:49;
thus L471: thesis by L470 , L463 , L469;
end;
suppose L472: ( len C161 ) >= ( C164 + 1 );

set D24 = ( C164 + 1 );
reconsider D25 = ( C162 | ( Seg C164 ) ) as (LinearCombination of C159) by IDEAL_1:41;
reconsider D26 = ( C161 | ( Seg C164 ) ) as (LinearCombination of C158) by IDEAL_1:41;
L473: 1 <= ( C164 + 1 ) by NAT_1:11;
L474: ( C164 + 1 ) in ( dom C161 ) by L473 , L472 , FINSEQ_3:25;
L475: ( C161 . ( C164 + 1 ) ) = ( C161 /. ( C164 + 1 ) ) by L474 , PARTFUN1:def 6;
L476: ( C162 . ( C164 + 1 ) ) = ( C162 /. ( C164 + 1 ) ) by L461 , L474 , PARTFUN1:def 6;
L477: ( C161 | ( Seg ( C164 + 1 ) ) ) = ( D26 ^ <* ( C161 . ( C164 + 1 ) ) *> ) by L474 , FINSEQ_5:10;
thus L478: ( C160 . ( Sum C165 ) ) = ( C160 . ( ( Sum D26 ) + ( C161 /. ( C164 + 1 ) ) ) ) by L477 , L465 , L475 , FVSUM_1:71
.= ( ( C160 . ( Sum D26 ) ) + ( C160 . ( C161 /. ( C164 + 1 ) ) ) ) by L460 , VECTSP_1:def 20
.= ( ( Sum D25 ) + ( C160 . ( C161 /. ( C164 + 1 ) ) ) ) by L463
.= ( ( Sum D25 ) + ( C160 . ( ( ( ( C163 /. D24 ) `1_3 ) * ( ( C163 /. D24 ) `2_3 ) ) * ( ( C163 /. D24 ) `3_3 ) ) ) ) by L458 , L474 , L475 , IDEAL_1:def 11
.= ( ( Sum D25 ) + ( ( C160 . ( ( ( C163 /. D24 ) `1_3 ) * ( ( C163 /. D24 ) `2_3 ) ) ) * ( C160 . ( ( C163 /. D24 ) `3_3 ) ) ) ) by L460 , GROUP_6:def 6
.= ( ( Sum D25 ) + ( ( ( C160 . ( ( C163 /. D24 ) `1_3 ) ) * ( C160 . ( ( C163 /. D24 ) `2_3 ) ) ) * ( C160 . ( ( C163 /. D24 ) `3_3 ) ) ) ) by L460 , GROUP_6:def 6
.= ( ( Sum D25 ) + ( C162 /. ( C164 + 1 ) ) ) by L459 , L461 , L474 , L476
.= ( Sum ( D25 ^ <* ( C162 /. ( C164 + 1 ) ) *> ) ) by FVSUM_1:71
.= ( Sum C166 ) by L461 , L466 , L474 , L476 , FINSEQ_5:10;
end;
end;

end;
L465: (C161 = ( C161 | ( Seg ( len C161 ) ) ) & C162 = ( C162 | ( Seg ( len C162 ) ) )) by FINSEQ_3:49;
L466: S2[ ( 0 ) ]
proof
let C167 being (LinearCombination of C158);
let C168 being (LinearCombination of C159);
assume that
L467: C167 = ( C161 | (( Seg ( 0 ) ) qua set) )
and
L468: C168 = ( C162 | (( Seg ( 0 ) ) qua set) );
thus L469: ( C160 . ( Sum C167 ) ) = ( C160 . ( Sum ( <*> (the carrier of C156) ) ) ) by L467
.= ( C160 . ( 0. C156 ) ) by RLVECT_1:43
.= ( 0. C157 ) by L456 , L449
.= ( Sum ( <*> (the carrier of C157) ) ) by RLVECT_1:43
.= ( Sum C168 ) by L468;
end;
L470: (for B122 being (Element of ( NAT )) holds S2[ B122 ]) from NAT_1:sch 1(L466 , L462);
thus L471: thesis by L470 , L457 , L465;
end;
theorem
L472: (for B123 , B124 being non  empty doubleLoopStr holds (for B125 being (Function of B123 , B124) holds (B125 is  RingIsomorphism implies ( B125 " ) is  RingIsomorphism)))
proof
let C169 , C170 being non  empty doubleLoopStr;
let C171 being (Function of C169 , C170);
assume L473: C171 is  RingIsomorphism;
L474: C171 is  RingEpimorphism by L473 , QUOFIELD:def 21;
L475: ( rng C171 ) = (the carrier of C170) by L474 , QUOFIELD:def 19;
L476: C171 is  RingMonomorphism by L473 , QUOFIELD:def 21;
L477: C171 is  one-to-one by L476 , QUOFIELD:def 20;
L478: C171 is  RingHomomorphism by L474 , QUOFIELD:def 19;
L479: C171 is  additive  multiplicative  unity-preserving by L478 , QUOFIELD:def 18;
L480: (for B126 , B127 being (Element of C170) holds (( ( C171 " ) . ( B126 + B127 ) ) = ( ( ( C171 " ) . B126 ) + ( ( C171 " ) . B127 ) ) & ( ( C171 " ) . ( B126 * B127 ) ) = ( ( ( C171 " ) . B126 ) * ( ( C171 " ) . B127 ) ) & ( ( C171 " ) . ( 1_ C170 ) ) = ( 1_ C169 )))
proof
L481: C171 is  onto by L475 , FUNCT_2:def 3;
L482: ( ( C171 " ) . ( 1_ C170 ) ) = ( ( C171 " ) . ( C171 . ( 1_ C169 ) ) ) by L479 , GROUP_1:def 13
.= ( ( (C171 qua Function) " ) . ( C171 . ( 1_ C169 ) ) ) by L477 , L481 , TOPS_2:def 4
.= ( 1_ C169 ) by L477 , FUNCT_2:26;
let C172 , C173 being (Element of C170);
consider C174 being set such that L483: C174 in (the carrier of C169) and L484: ( C171 . C174 ) = C172 by L475 , FUNCT_2:11;
reconsider D27 = C174 as (Element of C169) by L483;
L485: D27 = ( ( (C171 qua Function) " ) . ( C171 . D27 ) ) by L477 , FUNCT_2:26
.= ( ( C171 " ) . C172 ) by L477 , L484 , L481 , TOPS_2:def 4;
consider C175 being set such that L486: C175 in (the carrier of C169) and L487: ( C171 . C175 ) = C173 by L475 , FUNCT_2:11;
reconsider D28 = C175 as (Element of C169) by L486;
L488: D28 = ( ( (C171 qua Function) " ) . ( C171 . D28 ) ) by L477 , FUNCT_2:26
.= ( ( C171 " ) . C173 ) by L481 , L477 , L487 , TOPS_2:def 4;
L489: ( ( C171 " ) . ( C172 * C173 ) ) = ( ( C171 " ) . ( C171 . ( D27 * D28 ) ) ) by L479 , L484 , L487 , GROUP_6:def 6
.= ( ( (C171 qua Function) " ) . ( C171 . ( D27 * D28 ) ) ) by L477 , L481 , TOPS_2:def 4
.= ( ( ( C171 " ) . C172 ) * ( ( C171 " ) . C173 ) ) by L477 , L485 , L488 , FUNCT_2:26;
L490: ( ( C171 " ) . ( C172 + C173 ) ) = ( ( C171 " ) . ( C171 . ( D27 + D28 ) ) ) by L479 , L484 , L487 , VECTSP_1:def 20
.= ( ( (C171 qua Function) " ) . ( C171 . ( D27 + D28 ) ) ) by L477 , L481 , TOPS_2:def 4
.= ( ( ( C171 " ) . C172 ) + ( ( C171 " ) . C173 ) ) by L477 , L485 , L488 , FUNCT_2:26;
thus L491: thesis by L490 , L489 , L482;
end;
L492: ( C171 " ) is  additive  multiplicative  unity-preserving by L480 , VECTSP_1:def 20 , GROUP_1:def 13 , GROUP_6:def 6;
L493: ( C171 " ) is  RingHomomorphism by L492 , QUOFIELD:def 18;
L494: ( rng C171 ) = ( [#] C170 ) by L474 , QUOFIELD:def 19;
L495: ( rng ( C171 " ) ) = ( [#] C169 ) by L494 , L477 , TOPS_2:49
.= (the carrier of C169);
L496: ( C171 " ) is  RingEpimorphism by L495 , L493 , QUOFIELD:def 19;
L497: ( C171 " ) is  one-to-one by L477 , L494 , TOPS_2:50;
L498: ( C171 " ) is  RingMonomorphism by L497 , L493 , QUOFIELD:def 20;
thus L499: thesis by L498 , L496 , QUOFIELD:def 21;
end;
theorem
L500: (for B128 , B129 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital non  empty doubleLoopStr holds (for B130 being non  empty (Subset of B128) holds (for B131 being (Function of B128 , B129) holds (B131 is  RingIsomorphism implies ( B131 .: ( B130 -Ideal ) ) = ( ( B131 .: B130 ) -Ideal )))))
proof
let C176 , C177 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital non  empty doubleLoopStr;
let C178 being non  empty (Subset of C176);
let C179 being (Function of C176 , C177);
assume L501: C179 is  RingIsomorphism;
L502:
now
let C180 being set;
L503: ( dom C179 ) = (the carrier of C176) by FUNCT_2:def 1;
assume L504: C180 in ( ( C179 .: C178 ) -Ideal );
consider C181 being (LinearCombination of ( C179 .: C178 )) such that L505: C180 = ( Sum C181 ) by L504 , IDEAL_1:60;
consider C182 being (FinSequence of [: (the carrier of C177) , (the carrier of C177) , (the carrier of C177) :]) such that L506: C182 represents C181 by IDEAL_1:35;
L507: C179 is  RingMonomorphism by L501 , QUOFIELD:def 21;
L508: C179 is  one-to-one by L507 , QUOFIELD:def 20;
L509: C179 is  RingEpimorphism by L501 , QUOFIELD:def 21;
L510: ( rng C179 ) = (the carrier of C177) by L509 , QUOFIELD:def 19;
L511: C179 is  onto by L510 , FUNCT_2:def 3;
L512: ( (C179 qua Function) " ) = ( C179 " ) by L511 , L508 , TOPS_2:def 4;
L513: ( ( (C179 qua Function) " ) .: ( C179 .: C178 ) ) = ( (C179 qua Function) " ( C179 .: C178 ) ) by L508 , FUNCT_1:85;
consider C183 being (LinearCombination of C178) such that L514: (( len C181 ) = ( len C183 ) & (for B132 being set holds (B132 in ( dom C183 ) implies ( C183 . B132 ) = ( ( ( ( C179 " ) . ( ( C182 /. B132 ) `1_3 ) ) * ( ( C179 " ) . ( ( C182 /. B132 ) `2_3 ) ) ) * ( ( C179 " ) . ( ( C182 /. B132 ) `3_3 ) ) )))) by L513 , L508 , L512 , L506 , FUNCT_1:82 , IDEAL_1:36;
L515: ( C179 " ) is  RingIsomorphism by L501 , L472;
L516: ( C179 " ) is  RingMonomorphism by L515 , QUOFIELD:def 21;
L517: ( C179 " ) is  RingHomomorphism by L516 , QUOFIELD:def 20;
L518: ( ( C179 " ) . C180 ) = ( Sum C183 ) by L517 , L505 , L506 , L514 , L455;
L519: ( ( C179 " ) . C180 ) in ( C178 -Ideal ) by L518 , IDEAL_1:60;
L520: ( C179 . ( ( C179 " ) . C180 ) ) in ( C179 .: ( C178 -Ideal ) ) by L519 , L503 , FUNCT_1:def 6;
thus L521: C180 in ( C179 .: ( C178 -Ideal ) ) by L520 , L504 , L508 , L510 , L512 , FUNCT_1:35;
end;
L522: ( ( C179 .: C178 ) -Ideal ) c= ( C179 .: ( C178 -Ideal ) ) by L502 , TARSKI:def 3;
L523:
now
let C184 being set;
assume L524: C184 in ( C179 .: ( C178 -Ideal ) );
consider C185 being set such that L525: C185 in (the carrier of C176) and L526: C185 in ( C178 -Ideal ) and L527: C184 = ( C179 . C185 ) by L524 , FUNCT_2:64;
consider C186 being (LinearCombination of C178) such that L528: C185 = ( Sum C186 ) by L526 , IDEAL_1:60;
consider C187 being (FinSequence of [: (the carrier of C176) , (the carrier of C176) , (the carrier of C176) :]) such that L529: C187 represents C186 by IDEAL_1:35;
consider C188 being (LinearCombination of ( C179 .: C178 )) such that L530: (( len C186 ) = ( len C188 ) & (for B133 being set holds (B133 in ( dom C188 ) implies ( C188 . B133 ) = ( ( ( C179 . ( ( C187 /. B133 ) `1_3 ) ) * ( C179 . ( ( C187 /. B133 ) `2_3 ) ) ) * ( C179 . ( ( C187 /. B133 ) `3_3 ) ) )))) by L529 , IDEAL_1:36;
L531: C179 is  RingMonomorphism by L501 , QUOFIELD:def 21;
L532: C179 is  RingHomomorphism by L531 , QUOFIELD:def 20;
L533: C184 = ( Sum C188 ) by L532 , L527 , L528 , L529 , L530 , L455;
thus L534: C184 in ( ( C179 .: C178 ) -Ideal ) by L533 , IDEAL_1:60;
end;
L535: ( C179 .: ( C178 -Ideal ) ) c= ( ( C179 .: C178 ) -Ideal ) by L523 , TARSKI:def 3;
thus L536: thesis by L535 , L522 , XBOOLE_0:def 10;
end;
theorem
L537: (for B134 , B135 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital non  empty doubleLoopStr holds (for B136 being (Function of B134 , B135) holds ((B136 is  RingIsomorphism & B134 is  Noetherian) implies B135 is  Noetherian)))
proof
let C189 , C190 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital non  empty doubleLoopStr;
let C191 being (Function of C189 , C190);
assume that
L538: C191 is  RingIsomorphism
and
L539: C189 is  Noetherian;
L540:
now
L541: C191 is  RingEpimorphism by L538 , QUOFIELD:def 21;
L542: ( rng C191 ) = (the carrier of C190) by L541 , QUOFIELD:def 19;
let C192 being (Ideal of C190);
L543: C191 is  RingMonomorphism by L538 , QUOFIELD:def 21;
L544: C191 is  one-to-one by L543 , QUOFIELD:def 20;
reconsider D29 = ( ( C191 " ) .: C192 ) as (Ideal of C189) by L538 , L403 , L472;
L545: D29 is  finitely_generated by L539 , IDEAL_1:def 26;
consider C193 being non  empty  finite (Subset of C189) such that L546: ( ( C191 " ) .: C192 ) = ( C193 -Ideal ) by L545 , IDEAL_1:def 25;
L547: C191 is  onto by L542 , FUNCT_2:def 3;
L548: ( C191 " ) = ( (C191 qua Function) " ) by L547 , L544 , TOPS_2:def 4;
L549: ( C191 .: ( ( C191 " ) .: C192 ) ) = ( C191 .: ( C191 " C192 ) ) by L548 , L544 , FUNCT_1:85;
L550: ( C191 .: ( ( C191 " ) .: C192 ) ) = C192 by L549 , L542 , FUNCT_1:77;
L551: C192 = ( ( C191 .: C193 ) -Ideal ) by L550 , L538 , L546 , L500;
thus L552: C192 is  finitely_generated by L551;
end;
thus L553: thesis by L540 , IDEAL_1:def 26;
end;
theorem
L554: (for B137 being  add-associative  right_zeroed  right_complementable  associative  Abelian  distributive  well-unital non  trivial doubleLoopStr holds (ex B138 being (Function of B137 , ( Polynom-Ring (( 0 ) , B137) )) st B138 is  RingIsomorphism))
proof
deffunc H1(set) = ( ( Bags ( {} ) ) --> $1 );
let C194 being  add-associative  right_zeroed  right_complementable  associative  Abelian  distributive  well-unital non  trivial doubleLoopStr;
consider C195 being Function such that L555: ( dom C195 ) = (the carrier of C194) and L556: (for B139 being set holds (B139 in (the carrier of C194) implies ( C195 . B139 ) = H1(B139))) from FUNCT_1:sch 3;
L557:
now
let C196 being set;
thus L558:now
assume L559: C196 in ( rng C195 );
consider C197 being set such that L560: C197 in (the carrier of C194) and L561: C196 = ( C195 . C197 ) by L559 , L555 , FUNCT_1:def 3;
reconsider D30 = C197 as (Element of C194) by L560;
reconsider D31 = ( ( Bags ( {} ) ) --> D30 ) as (Function of ( Bags ( {} ) ) , C194);
L562: ( Support D31 ) is  finite by PRE_POLY:51;
L563: D31 is  finite-Support  finite-Support  finite-Support  finite-Support (Series of ( 0 ) , C194) by L562 , POLYNOM1:def 4;
L564: D31 in (the carrier of ( Polynom-Ring (( 0 ) , C194) )) by L563 , POLYNOM1:def 10;
thus L565: C196 in (the carrier of ( Polynom-Ring (( 0 ) , C194) )) by L564 , L556 , L561;
end;
assume L566: C196 in (the carrier of ( Polynom-Ring (( 0 ) , C194) ));
reconsider D32 = C196 as (Function of ( Bags ( {} ) ) , C194) by L566 , POLYNOM1:def 10;
L567: ( dom D32 ) = ( Bags ( {} ) ) by FUNCT_2:def 1;
L568: ( rng D32 ) = { ( D32 . ( {} ) ) } by L567 , FUNCT_1:4 , PRE_POLY:51;
L569: ( D32 . ( {} ) ) in ( rng D32 ) by L568 , TARSKI:def 1;
reconsider D33 = ( D32 . ( {} ) ) as (Element of C194) by L569;
L570: D32 = ( ( Bags ( {} ) ) --> ( D32 . ( {} ) ) ) by L567 , L568 , FUNCOP_1:9;
L571: C196 = ( C195 . D33 ) by L570 , L556;
thus L572: C196 in ( rng C195 ) by L571 , L555 , FUNCT_1:def 3;
end;
L573: ( rng C195 ) = (the carrier of ( Polynom-Ring (( 0 ) , C194) )) by L557 , TARSKI:1;
reconsider D34 = C195 as (Function of C194 , ( Polynom-Ring (( 0 ) , C194) )) by L573 , L555 , FUNCT_2:1;
L574: ( EmptyBag ( {} ) ) = ( ( {} ) --> ( 0 ) );
L575:
now
let C198 , C199 being (Element of C194);
reconsider D35 = ( D34 . C198 ) , D36 = ( D34 . C199 ) , D37 = ( D34 . ( C198 + C199 ) ) as (Polynomial of ( 0 ) , C194) by POLYNOM1:def 10;
L576:
now
let C200 being (bag of ( 0 ));
L577: C200 in ( Bags ( {} ) ) by PRE_POLY:def 12;
L578: ( D36 . C200 ) = ( ( ( Bags ( {} ) ) --> C199 ) . C200 ) by L556
.= C199 by L577 , FUNCOP_1:7;
L579: ( D35 . C200 ) = ( ( ( Bags ( {} ) ) --> C198 ) . C200 ) by L556
.= C198 by L577 , FUNCOP_1:7;
L580: ( D37 . C200 ) = ( ( ( Bags ( {} ) ) --> ( C198 + C199 ) ) . C200 ) by L556
.= ( C198 + C199 ) by L577 , FUNCOP_1:7;
thus L581: ( D37 . C200 ) = ( ( D35 . C200 ) + ( D36 . C200 ) ) by L580 , L579 , L578;
end;
L582: D37 = ( D35 + D36 ) by L576 , POLYNOM1:16;
thus L583: ( ( D34 . C198 ) + ( D34 . C199 ) ) = ( D34 . ( C198 + C199 ) ) by L582 , POLYNOM1:def 10;
end;
L584: D34 is  additive by L575 , VECTSP_1:def 20;
L585:
now
let C201 , C202 being (Element of C194);
reconsider D38 = ( D34 . C201 ) , D39 = ( D34 . C202 ) , D40 = ( D34 . ( C201 * C202 ) ) as (Polynomial of ( 0 ) , C194) by POLYNOM1:def 10;
L586:
now
reconsider D41 = <* ( C201 * C202 ) *> as (FinSequence of (the carrier of C194));
let C203 being (bag of ( 0 ));
take D42 = D41;
L587: C203 in ( Bags ( {} ) ) by PRE_POLY:def 12;
thus L588: ( D40 . C203 ) = ( ( ( Bags ( {} ) ) --> ( C201 * C202 ) ) . C203 ) by L556
.= ( C201 * C202 ) by L587 , FUNCOP_1:7
.= ( Sum D42 ) by RLVECT_1:44;
L589: ( decomp C203 ) = <* <* ( {} ) , ( {} ) *> *> by L23;
L590: ( len D42 ) = 1 by FINSEQ_1:39;
thus L591: ( len D42 ) = ( len ( decomp C203 ) ) by L590 , L589 , FINSEQ_1:39;
L592: ( len ( decomp C203 ) ) = 1 by L589 , FINSEQ_1:39;
L593:
now
set D43 = ( {} );
set D44 = ( {} );
let C204 being (Element of ( NAT ));
L594: D43 in ( Bags ( {} ) ) by PRE_POLY:51 , TARSKI:def 1;
reconsider D45 = D43 , D46 = D44 as (bag of ( 0 )) by L594;
L595: ( D38 . D45 ) = ( ( ( Bags ( {} ) ) --> C201 ) . D45 ) by L556
.= C201 by L594 , FUNCOP_1:7;
L596: ( D39 . D46 ) = ( ( ( Bags ( {} ) ) --> C202 ) . D46 ) by L556
.= C202 by L594 , FUNCOP_1:7;
assume L597: C204 in ( dom D42 );
L598: (1 <= C204 & C204 <= 1) by L597 , L590 , FINSEQ_3:25;
L599: C204 = 1 by L598 , XXREAL_0:1;
take D47 = D45;
take D48 = D46;
L600: C204 in ( dom ( decomp C203 ) ) by L592 , L598 , FINSEQ_3:25;
thus L601: ( ( decomp C203 ) /. C204 ) = ( ( decomp C203 ) . 1 ) by L600 , L599 , PARTFUN1:def 6
.= <* D47 , D48 *> by L589 , FINSEQ_1:40;
thus L602: ( D42 /. C204 ) = ( D42 . 1 ) by L597 , L599 , PARTFUN1:def 6
.= ( ( D38 . D47 ) * ( D39 . D48 ) ) by L595 , L596 , FINSEQ_1:40;
end;
thus L603: (for B140 being (Element of ( NAT )) holds (B140 in ( dom D42 ) implies (ex B141 , B142 being (bag of ( 0 )) st (( ( decomp C203 ) /. B140 ) = <* B141 , B142 *> & ( D42 /. B140 ) = ( ( D38 . B141 ) * ( D39 . B142 ) ))))) by L593;
end;
L604: D40 = ( D38 *' D39 ) by L586 , POLYNOM1:def 9;
thus L605: ( ( D34 . C201 ) * ( D34 . C202 ) ) = ( D34 . ( C201 * C202 ) ) by L604 , POLYNOM1:def 10;
end;
L606: D34 is  multiplicative by L585 , GROUP_6:def 6;
take D34;
reconsider D49 = ( { ( {} ) } --> ( 0. C194 ) ) , D50 = ( { ( {} ) } --> ( 1_ C194 ) ) as (Function of { ( {} ) } , (the carrier of C194));
L607: ( dom D50 ) = { ( {} ) } by FUNCT_2:def 1;
L608: ( dom D49 ) = { ( {} ) } by FUNCT_2:def 1;
L609: ( {} ) in ( dom ( { ( {} ) } --> ( 0. C194 ) ) ) by L608 , TARSKI:def 1;
L610: ( 1_ ( Polynom-Ring (( 0 ) , C194) ) ) = ( 1_ (( 0 ) , C194) ) by POLYNOM1:31
.= ( ( 0_ (( 0 ) , C194) ) +* (( {} ) , ( 1_ C194 )) ) by L574 , POLYNOM1:def 8
.= ( ( { ( {} ) } --> ( 0. C194 ) ) +* (( {} ) , ( 1_ C194 )) ) by POLYNOM1:def 7 , PRE_POLY:51
.= ( ( { ( {} ) } --> ( 0. C194 ) ) +* ( ( {} ) .--> ( 1_ C194 ) ) ) by L609 , FUNCT_7:def 3
.= ( { ( {} ) } --> ( 1_ C194 ) ) by L608 , L607 , FUNCT_4:19
.= ( D34 . ( 1_ C194 ) ) by L556 , PRE_POLY:51;
L611: D34 is  unity-preserving by L610 , GROUP_1:def 13;
L612: D34 is  RingHomomorphism by L611 , L584 , L606 , QUOFIELD:def 18;
L613: D34 is  RingEpimorphism by L612 , L573 , QUOFIELD:def 19;
L614:
now
let C205 , C206 being set;
assume that
L615: C205 in ( dom D34 )
and
L616: C206 in ( dom D34 );
assume L617: ( D34 . C205 ) = ( D34 . C206 );
L618: ( ( Bags ( {} ) ) --> C205 ) = ( D34 . C206 ) by L617 , L556 , L615;
L619: ( ( Bags ( {} ) ) --> C205 ) = ( ( Bags ( {} ) ) --> C206 ) by L618 , L556 , L616;
thus L620: C205 = C206 by L619 , FUNCT_4:6;
end;
L621: D34 is  one-to-one by L614 , FUNCT_1:def 4;
L622: D34 is  RingMonomorphism by L621 , L612 , QUOFIELD:def 20;
thus L623: thesis by L622 , L613 , QUOFIELD:def 21;
end;
theorem
L624: (for B143 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  trivial doubleLoopStr holds (for B144 being (Element of ( NAT )) holds (for B145 being (bag of B144) holds (for B146 being (Polynomial of B144 , B143) holds (for B147 being (FinSequence of (the carrier of ( Polynom-Ring (B144 , B143) ))) holds (B146 = ( Sum B147 ) implies (ex B148 being (Function of (the carrier of ( Polynom-Ring (B144 , B143) )) , (the carrier of B143)) st ((for B149 being (Polynomial of B144 , B143) holds ( B148 . B149 ) = ( B149 . B145 )) & ( B146 . B145 ) = ( Sum ( B148 * B147 ) )))))))))
proof
let C207 being  right_zeroed  add-associative  right_complementable  well-unital  distributive non  trivial doubleLoopStr;
let C208 being (Element of ( NAT ));
let C209 being (bag of C208);
let C210 being (Polynomial of C208 , C207);
let C211 being (FinSequence of (the carrier of ( Polynom-Ring (C208 , C207) )));
assume L625: C210 = ( Sum C211 );
set D51 = (the carrier of C207);
set D52 = ( Polynom-Ring (C208 , C207) );
set D53 = (the carrier of D52);
defpred S3[ (Element of D53) , (Element of D51) ] means (for B150 being (Polynomial of C208 , C207) holds (B150 = $1 implies $2 = ( B150 . C209 )));
L626:
now
let C212 being (Element of D53);
reconsider D54 = C212 as (Polynomial of C208 , C207) by POLYNOM1:def 10;
L627: S3[ C212 , ( D54 . C209 ) ];
thus L628: (ex B151 being (Element of D51) st S3[ C212 , B151 ]) by L627;
end;
consider C213 being (Function of D53 , D51) such that L629: (for B152 being (Element of D53) holds S3[ B152 , ( C213 . B152 ) ]) from FUNCT_2:sch 3(L626);
take C213;
L630:
now
let C214 being (Polynomial of C208 , C207);
reconsider D55 = C214 as (Element of D53) by POLYNOM1:def 10;
L631: S3[ D55 , ( C213 . D55 ) ] by L629;
thus L632: ( C213 . C214 ) = ( C214 . C209 ) by L631;
end;
thus L633: (for B153 being (Polynomial of C208 , C207) holds ( C213 . B153 ) = ( B153 . C209 )) by L630;
defpred S4[ Nat ] means (for B154 being (FinSequence of D53) holds (for B155 being (Polynomial of C208 , C207) holds ((( len B154 ) <= $1 & B155 = ( Sum B154 )) implies ( B155 . C209 ) = ( Sum ( C213 * B154 ) ))));
L634: (for B156 being (Element of ( NAT )) holds (S4[ B156 ] implies S4[ ( B156 + 1 ) ]))
proof
let C215 being (Element of ( NAT ));
assume L635: S4[ C215 ];
L636:
now
let C216 being (FinSequence of D53);
let C217 being (Polynomial of C208 , C207);
assume that
L637: ( len C216 ) <= ( C215 + 1 )
and
L638: C217 = ( Sum C216 );
per cases ;
suppose L639: ( len C216 ) < ( C215 + 1 );

L640: ( len C216 ) <= C215 by L639 , NAT_1:13;
thus L641: ( C217 . C209 ) = ( Sum ( C213 * C216 ) ) by L640 , L635 , L638;
end;
suppose L642: ( len C216 ) >= ( C215 + 1 );

L643: ( len C216 ) = ( C215 + 1 ) by L642 , L637 , XXREAL_0:1;
consider C218 , C219 being FinSequence such that L644: ( len C218 ) = C215 and L645: ( len C219 ) = 1 and L646: C216 = ( C218 ^ C219 ) by L643 , FINSEQ_2:22;
L647: ( rng C219 ) c= ( rng C216 ) by L646 , FINSEQ_1:30;
L648: ( rng C219 ) c= D53 by L647 , XBOOLE_1:1;
reconsider D56 = C219 as (FinSequence of D53) by L648 , FINSEQ_1:def 4;
L649: ( rng C218 ) c= ( rng C216 ) by L646 , FINSEQ_1:29;
L650: ( rng C218 ) c= D53 by L649 , XBOOLE_1:1;
reconsider D57 = C218 as (FinSequence of D53) by L650 , FINSEQ_1:def 4;
L651: ( Sum C216 ) = ( ( Sum D57 ) + ( Sum D56 ) ) by L646 , RLVECT_1:41;
reconsider D58 = ( Sum D57 ) as (Polynomial of C208 , C207) by POLYNOM1:def 10;
L652: ( C213 * C216 ) = ( ( C213 * D57 ) ^ ( C213 * D56 ) ) by L646 , FINSEQOP:9;
L653: 1 in ( dom D56 ) by L645 , FINSEQ_3:25;
L654: ( D56 . 1 ) in ( rng D56 ) by L653 , FUNCT_1:def 3;
reconsider D59 = ( D56 . 1 ) as (Element of D53) by L654;
reconsider D60 = D59 as (Polynomial of C208 , C207) by POLYNOM1:def 10;
L655: D56 = <* D59 *> by L645 , FINSEQ_1:40;
L656: ( C213 * D56 ) = <* ( C213 . D59 ) *> by L655 , FINSEQ_2:35
.= <* ( D60 . C209 ) *> by L629;
L657: ( Sum ( C213 * D56 ) ) = ( D60 . C209 ) by L656 , RLVECT_1:44;
L658: D59 = ( Sum D56 ) by L655 , RLVECT_1:44;
L659: C217 = ( D58 + D60 ) by L658 , L638 , L651 , POLYNOM1:def 10;
L660: ( D58 . C209 ) = ( Sum ( C213 * D57 ) ) by L635 , L644;
thus L661: ( C217 . C209 ) = ( ( Sum ( C213 * D57 ) ) + ( Sum ( C213 * D56 ) ) ) by L660 , L657 , L659 , POLYNOM1:15
.= ( Sum ( C213 * C216 ) ) by L652 , RLVECT_1:41;
end;
end;
thus L663: thesis by L636;
end;
L664: S4[ ( 0 ) ]
proof
let C220 being (FinSequence of D53);
let C221 being (Polynomial of C208 , C207);
assume that
L665: ( len C220 ) <= ( 0 )
and
L666: C221 = ( Sum C220 );
L667: C220 = ( <*> D53 ) by L665;
L668: ( C213 * C220 ) = ( <*> D51 ) by L667;
L669: ( Sum ( C213 * C220 ) ) = ( 0. C207 ) by L668 , RLVECT_1:43;
L670: C221 = ( 0. D52 ) by L666 , L667 , RLVECT_1:43
.= ( 0_ (C208 , C207) ) by POLYNOM1:def 10;
thus L671: thesis by L670 , L669 , POLYNOM1:22;
end;
L672: (for B157 being (Element of ( NAT )) holds S4[ B157 ]) from NAT_1:sch 1(L664 , L634);
L673: S4[ ( len C211 ) ] by L672;
thus L674: thesis by L673 , L625;
end;
definition
let C222 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr;
let C223 being (Element of ( NAT ));
func upm (C223 , C222) -> (Function of ( Polynom-Ring ( Polynom-Ring (C223 , C222) ) ) , ( Polynom-Ring (( C223 + 1 ) , C222) )) means 
:L675: (for B158 being (Polynomial of ( Polynom-Ring (C223 , C222) )) holds (for B159 being (Polynomial of C223 , C222) holds (for B160 being (Polynomial of ( C223 + 1 ) , C222) holds (for B161 being (bag of ( C223 + 1 )) holds ((B160 = ( it . B158 ) & B159 = ( B158 . ( B161 . C223 ) )) implies ( B160 . B161 ) = ( B159 . ( B161 | C223 ) ))))));
existence
proof
set D61 = (the carrier of C222);
set D62 = ( Polynom-Ring (C223 , C222) );
set D63 = ( Polynom-Ring (( C223 + 1 ) , C222) );
set D64 = ( Polynom-Ring ( Polynom-Ring (C223 , C222) ) );
set D65 = (the carrier of D64);
set D66 = (the carrier of D63);
defpred S5[ (Element of D65) , (Element of D66) ] means (for B162 being (Polynomial of D62) holds (for B163 being (Polynomial of C223 , C222) holds (for B164 being (Polynomial of ( C223 + 1 ) , C222) holds (for B165 being (bag of ( C223 + 1 )) holds ((B162 = $1 & B164 = $2 & B163 = ( B162 . ( B165 . C223 ) )) implies ( B164 . B165 ) = ( B163 . ( B165 | C223 ) ))))));
L676:
now
let C224 being (Element of D65);
reconsider D67 = C224 as (Polynomial of D62) by POLYNOM3:def 10;
defpred S6[ (Element of ( Bags ( C223 + 1 ) )) , (Element of D61) ] means (for B166 being (Polynomial of C223 , C222) holds (B166 = ( D67 . ( $1 . C223 ) ) implies $2 = ( B166 . ( $1 | C223 ) )));
deffunc H2(set) = { B167 where B167 is (Element of ( Bags ( C223 + 1 ) )) : (( B167 . C223 ) = $1 & (for B168 being (Polynomial of C223 , C222) holds (B168 = ( D67 . $1 ) implies ( B167 | C223 ) in ( Support B168 )))) };
L677:
now
let C225 being set;
assume L678: C225 in ( NAT );
set D68 = H2(C225);
L679: D68 c= ( Bags ( C223 + 1 ) )
proof
let C226 being set;
assume L680: C226 in D68;
L681: (ex B169 being (Element of ( Bags ( C223 + 1 ) )) st (B169 = C226 & ( B169 . C223 ) = C225 & (for B170 being (Polynomial of C223 , C222) holds (B170 = ( D67 . C225 ) implies ( B169 | C223 ) in ( Support B170 ))))) by L680;
thus L682: thesis by L681;
end;
thus L683: D68 in ( bool ( Bags ( C223 + 1 ) ) ) by L679;
end;
consider C227 being (Function of ( NAT ) , ( bool ( Bags ( C223 + 1 ) ) )) such that L684: (for B171 being set holds (B171 in ( NAT ) implies ( C227 . B171 ) = H2(B171))) from FUNCT_2:sch 2(L677);
L685:
now
let C228 being set;
assume L686: C228 in ( C227 .: ( len D67 ) );
consider C229 being (Element of ( NAT )) such that L687: C229 in ( len D67 ) and L688: C228 = ( C227 . C229 ) by L686 , FUNCT_2:65;
reconsider D69 = ( D67 . C229 ) as (Polynomial of C223 , C222) by POLYNOM1:def 10;
L689: ( C227 . C229 ) = { B172 where B172 is (Element of ( Bags ( C223 + 1 ) )) : (( B172 . C223 ) = C229 & (for B173 being (Polynomial of C223 , C222) holds (B173 = ( D67 . C229 ) implies ( B172 | C223 ) in ( Support B173 )))) } by L684;
per cases ;
suppose L690: ( Support D69 ) = ( {} );

L691:
now
assume L692: ( C227 . C229 ) <> ( {} );
consider C230 being set such that L693: C230 in ( C227 . C229 ) by L692 , XBOOLE_0:def 1;
L694: (ex B174 being (Element of ( Bags ( C223 + 1 ) )) st (B174 = C230 & ( B174 . C223 ) = C229 & (for B175 being (Polynomial of C223 , C222) holds (B175 = ( D67 . C229 ) implies ( B174 | C223 ) in ( Support B175 ))))) by L689 , L693;
thus L695: contradiction by L694 , L690;
end;
thus L696: C228 is  finite by L691 , L688;
end;
suppose L697: ( Support D69 ) <> ( {} );

consider C231 being set such that L698: C231 in ( Support D69 ) by L697 , XBOOLE_0:def 1;
reconsider D70 = C231 as (Element of ( Bags C223 )) by L698;
L699: ( ( D70 bag_extend C229 ) . C223 ) = C229 by L77;
L700: (for B176 being (Polynomial of C223 , C222) holds (B176 = ( D67 . C229 ) implies ( ( D70 bag_extend C229 ) | C223 ) in ( Support B176 ))) by L698 , L77;
L701: ( D70 bag_extend C229 ) in ( C227 . C229 ) by L700 , L689 , L699;
reconsider D71 = ( C227 . C229 ) as non  empty set by L701;
reconsider D72 = ( Support D69 ) as non  empty set by L697;
defpred S7[ (Element of D71) , (Element of D72) ] means (for B177 being (Element of ( Bags ( C223 + 1 ) )) holds ($1 = B177 implies $2 = ( B177 | C223 )));
L702:
now
let C232 being (Element of D71);
L703: C232 in ( C227 . C229 );
consider C233 being (Element of ( Bags ( C223 + 1 ) )) such that L704: C233 = C232 and L705: ( C233 . C223 ) = C229 and L706: (for B178 being (Polynomial of C223 , C222) holds (B178 = ( D67 . C229 ) implies ( C233 | C223 ) in ( Support B178 ))) by L703 , L689;
reconsider D73 = ( C233 | C223 ) as (Element of D72) by L706;
L707: S7[ C232 , D73 ] by L704;
thus L708: (ex B179 being (Element of D72) st S7[ C232 , B179 ]) by L707;
end;
consider C234 being (Function of D71 , D72) such that L709: (for B180 being (Element of D71) holds S7[ B180 , ( C234 . B180 ) ]) from FUNCT_2:sch 3(L702);
L710: ( dom C234 ) = D71 by FUNCT_2:def 1;
L711:
now
let C235 , C236 being set;
assume that
L712: C235 in ( dom C234 )
and
L713: C236 in ( dom C234 )
and
L714: ( C234 . C235 ) = ( C234 . C236 );
L715: ( C234 . C235 ) in D72 by L712 , FUNCT_2:5;
reconsider D74 = ( C234 . C235 ) as (Element of ( Bags C223 )) by L715;
consider C237 being (Element of ( Bags ( C223 + 1 ) )) such that L716: C237 = C235 and L717: ( C237 . C223 ) = C229 and L718: (for B181 being (Polynomial of C223 , C222) holds (B181 = ( D67 . C229 ) implies ( C237 | C223 ) in ( Support B181 ))) by L689 , L710 , L712;
L719: ( C237 | C223 ) = ( C234 . C235 ) by L709 , L712 , L716;
L720: C237 = ( D74 bag_extend C229 ) by L719 , L717 , L77;
consider C238 being (Element of ( Bags ( C223 + 1 ) )) such that L721: C238 = C236 and L722: ( C238 . C223 ) = C229 and L723: (for B182 being (Polynomial of C223 , C222) holds (B182 = ( D67 . C229 ) implies ( C238 | C223 ) in ( Support B182 ))) by L689 , L710 , L713;
L724: ( C238 | C223 ) = ( C234 . C235 ) by L709 , L713 , L714 , L721;
thus L725: C235 = C236 by L724 , L716 , L720 , L721 , L722 , L77;
end;
L726: C234 is  one-to-one by L711 , FUNCT_1:def 4;
L727: ( rng C234 ) c= D72;
L728: ( card D71 ) c= ( card D72 ) by L727 , L710 , L726 , CARD_1:10;
thus L729: C228 is  finite by L728 , L688;
end;
end;
L731: ( union ( C227 .: ( len D67 ) ) ) is  finite by L685 , FINSET_1:7;
L732:
now
let C239 being (Element of ( Bags ( C223 + 1 ) ));
reconsider D75 = ( D67 . ( C239 . C223 ) ) as (Polynomial of C223 , C222) by POLYNOM1:def 10;
L733: C223 < ( C223 + 1 ) by XREAL_1:29;
reconsider D76 = ( C239 | C223 ) as (bag of C223) by L733 , L32;
L734: S6[ C239 , ( D75 . D76 ) ];
thus L735: (ex B183 being (Element of D61) st S6[ C239 , B183 ]) by L734;
end;
consider C240 being (Function of ( Bags ( C223 + 1 ) ) , D61) such that L736: (for B184 being (Element of ( Bags ( C223 + 1 ) )) holds S6[ B184 , ( C240 . B184 ) ]) from FUNCT_2:sch 3(L732);
reconsider D77 = C240 as (Function of ( Bags ( C223 + 1 ) ) , C222);
reconsider D78 = D77 as (Series of ( C223 + 1 ) , C222);
L737: ( Support D78 ) c= ( union ( C227 .: ( len D67 ) ) )
proof
let C241 being set;
L738: ( dom C227 ) = ( NAT ) by FUNCT_2:def 1;
assume L739: C241 in ( Support D78 );
reconsider D79 = C241 as (Element of ( Bags ( C223 + 1 ) )) by L739;
reconsider D80 = ( D67 . ( D79 . C223 ) ) as (Polynomial of C223 , C222) by POLYNOM1:def 10;
L740: C223 < ( C223 + 1 ) by XREAL_1:29;
reconsider D81 = ( D79 | C223 ) as (Element of ( Bags C223 )) by L740 , L32;
L741: ( D78 . D79 ) <> ( 0. C222 ) by L739 , POLYNOM1:def 3;
L742: ( D80 . D81 ) <> ( 0. C222 ) by L741 , L736;
L743: D80 <> ( 0_ (C223 , C222) ) by L742 , POLYNOM1:22;
L744: D80 <> ( 0. D62 ) by L743 , POLYNOM1:def 10;
L745: ( D79 . C223 ) < ( len D67 ) by L744 , ALGSEQ_1:8;
L746: ( len D67 ) = { B185 where B185 is (Element of ( NAT )) : B185 < ( len D67 ) } by AXIOMS:4;
L747: ( D79 . C223 ) in ( len D67 ) by L746 , L745;
L748: ( C227 . ( D79 . C223 ) ) in ( C227 .: ( len D67 ) ) by L747 , L738 , FUNCT_1:def 6;
L749: ( C227 . ( D79 . C223 ) ) = { B186 where B186 is (Element of ( Bags ( C223 + 1 ) )) : (( B186 . C223 ) = ( D79 . C223 ) & (for B187 being (Polynomial of C223 , C222) holds (B187 = ( D67 . ( D79 . C223 ) ) implies ( B186 | C223 ) in ( Support B187 )))) } by L684;
L750: (for B188 being (Polynomial of C223 , C222) holds (B188 = ( D67 . ( D79 . C223 ) ) implies D81 in ( Support B188 ))) by L742 , POLYNOM1:def 3;
L751: C241 in ( C227 . ( D79 . C223 ) ) by L750 , L749;
thus L752: thesis by L751 , L748 , TARSKI:def 4;
end;
L753: D78 is  finite-Support by L737 , L731 , POLYNOM1:def 4;
reconsider D82 = D78 as (Element of D66) by L753 , POLYNOM1:def 10;
L754:
now
let C242 being (Polynomial of D62);
let C243 being (Polynomial of C223 , C222);
let C244 being (Polynomial of ( C223 + 1 ) , C222);
let C245 being (bag of ( C223 + 1 ));
L755: C245 is (Element of ( Bags ( C223 + 1 ) )) by PRE_POLY:def 12;
assume L756: (C242 = C224 & C244 = D82 & C243 = ( C242 . ( C245 . C223 ) ));
thus L757: ( C244 . C245 ) = ( C243 . ( C245 | C223 ) ) by L756 , L736 , L755;
end;
thus L758: (ex B189 being (Element of D66) st S5[ C224 , B189 ]) by L754;
end;
consider C246 being (Function of D65 , D66) such that L759: (for B190 being (Element of D65) holds S5[ B190 , ( C246 . B190 ) ]) from FUNCT_2:sch 3(L676);
reconsider D83 = C246 as (Function of D64 , D63);
take D83;
L760:
now
let C247 being (Polynomial of ( Polynom-Ring (C223 , C222) ));
let C248 being (Polynomial of C223 , C222);
let C249 being (Polynomial of ( C223 + 1 ) , C222);
let C250 being (bag of ( C223 + 1 ));
L761: C247 in D65 by POLYNOM3:def 10;
assume L762: (C249 = ( D83 . C247 ) & C248 = ( C247 . ( C250 . C223 ) ));
thus L763: ( C249 . C250 ) = ( C248 . ( C250 | C223 ) ) by L762 , L759 , L761;
end;
thus L764: thesis by L760;
end;
uniqueness
proof
let C251 , C252 being (Function of ( Polynom-Ring ( Polynom-Ring (C223 , C222) ) ) , ( Polynom-Ring (( C223 + 1 ) , C222) ));
set D84 = (the carrier of ( Polynom-Ring (( C223 + 1 ) , C222) ));
set D85 = (the carrier of ( Polynom-Ring ( Polynom-Ring (C223 , C222) ) ));
set D86 = ( Polynom-Ring (C223 , C222) );
assume L765: (for B191 being (Polynomial of ( Polynom-Ring (C223 , C222) )) holds (for B192 being (Polynomial of C223 , C222) holds (for B193 being (Polynomial of ( C223 + 1 ) , C222) holds (for B194 being (bag of ( C223 + 1 )) holds ((B193 = ( C251 . B191 ) & B192 = ( B191 . ( B194 . C223 ) )) implies ( B193 . B194 ) = ( B192 . ( B194 | C223 ) ))))));
assume L766: (for B195 being (Polynomial of ( Polynom-Ring (C223 , C222) )) holds (for B196 being (Polynomial of C223 , C222) holds (for B197 being (Polynomial of ( C223 + 1 ) , C222) holds (for B198 being (bag of ( C223 + 1 )) holds ((B197 = ( C252 . B195 ) & B196 = ( B195 . ( B198 . C223 ) )) implies ( B197 . B198 ) = ( B196 . ( B198 | C223 ) ))))));
L767:
now
let C253 being set;
assume L768: C253 in D85;
reconsider D87 = C253 as (Polynomial of D86) by L768 , POLYNOM3:def 10;
L769: (( C251 . C253 ) in D84 & ( C252 . C253 ) in D84) by L768 , FUNCT_2:5;
reconsider D88 = ( C251 . C253 ) , D89 = ( C252 . C253 ) as (Polynomial of ( C223 + 1 ) , C222) by L769 , POLYNOM1:def 10;
L770:
now
let C254 being set;
assume L771: C254 in ( Bags ( C223 + 1 ) );
reconsider D90 = C254 as (Element of ( Bags ( C223 + 1 ) )) by L771;
reconsider D91 = ( D87 . ( D90 . C223 ) ) as (Polynomial of C223 , C222) by POLYNOM1:def 10;
L772: C223 < ( C223 + 1 ) by NAT_1:13;
reconsider D92 = ( D90 | C223 ) as (Element of ( Bags C223 )) by L772 , L32;
thus L773: ( D88 . C254 ) = ( D91 . D92 ) by L765
.= ( D89 . C254 ) by L766;
end;
thus L774: ( C251 . C253 ) = ( C252 . C253 ) by L770 , FUNCT_2:12;
end;
thus L775: C251 = C252 by L767 , FUNCT_2:12;
end;
end;
registration
let C255 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr;
let C256 being (Element of ( NAT ));
cluster ( upm (C256 , C255) ) ->  additive;
coherence
proof
set D93 = ( upm (C256 , C255) );
set D94 = ( Polynom-Ring (C256 , C255) );
thus L777: D93 is  additive
proof
let C257 , C258 being (Element of ( Polynom-Ring ( Polynom-Ring (C256 , C255) ) ));
reconsider D95 = C257 , D96 = C258 , D97 = ( C257 + C258 ) as (Polynomial of D94) by POLYNOM3:def 10;
reconsider D98 = ( D93 . ( C257 + C258 ) ) , D99 = ( D93 . C257 ) , D100 = ( D93 . C258 ) as (Polynomial of ( C256 + 1 ) , C255) by POLYNOM1:def 10;
L778: D97 = ( D95 + D96 ) by POLYNOM3:def 10;
L779:
now
let C259 being set;
assume L780: C259 in ( Bags ( C256 + 1 ) );
reconsider D101 = C259 as (bag of ( C256 + 1 )) by L780;
reconsider D102 = ( ( D95 + D96 ) . ( D101 . C256 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
reconsider D103 = ( D95 . ( D101 . C256 ) ) , D104 = ( D96 . ( D101 . C256 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L781: C256 < ( C256 + 1 ) by XREAL_1:29;
reconsider D105 = ( D101 | C256 ) as (bag of C256) by L781 , L32;
L782: (( D103 . D105 ) = ( D99 . D101 ) & ( D104 . D105 ) = ( D100 . D101 )) by L675;
L783: ( ( D95 + D96 ) . ( D101 . C256 ) ) = ( ( D95 . ( D101 . C256 ) ) + ( D96 . ( D101 . C256 ) ) ) by NORMSP_1:def 2;
L784: D102 = ( D103 + D104 ) by L783 , POLYNOM1:def 10;
thus L785: ( D98 . C259 ) = ( ( D103 + D104 ) . D105 ) by L784 , L778 , L675
.= ( ( D99 . D101 ) + ( D100 . D101 ) ) by L782 , POLYNOM1:15
.= ( ( D99 + D100 ) . C259 ) by POLYNOM1:15;
end;
thus L786: ( D93 . ( C257 + C258 ) ) = ( D99 + D100 ) by L779 , FUNCT_2:12
.= ( ( D93 . C257 ) + ( D93 . C258 ) ) by POLYNOM1:def 10;
end;

end;
cluster ( upm (C256 , C255) ) ->  multiplicative;
coherence
proof
set D106 = ( upm (C256 , C255) );
set D107 = (the carrier of C255);
set D108 = ( Polynom-Ring (C256 , C255) );
set D109 = (the carrier of D108);
thus L778: D106 is  multiplicative
proof
let C260 , C261 being (Element of (the carrier of ( Polynom-Ring ( Polynom-Ring (C256 , C255) ) )));
reconsider D110 = C260 , D111 = C261 , D112 = ( C260 * C261 ) as (Polynomial of D108) by POLYNOM3:def 10;
reconsider D113 = ( D106 . ( C260 * C261 ) ) , D114 = ( ( D106 . C260 ) * ( D106 . C261 ) ) , D115 = ( D106 . C260 ) , D116 = ( D106 . C261 ) as (Polynomial of ( C256 + 1 ) , C255) by POLYNOM1:def 10;
L779: D112 = ( D110 *' D111 ) by POLYNOM3:def 10;
L780: D114 = ( D115 *' D116 ) by POLYNOM1:def 10;
L781:
now
let C262 being set;
assume L782: C262 in ( Bags ( C256 + 1 ) );
reconsider D117 = C262 as (Element of ( Bags ( C256 + 1 ) )) by L782;
consider C263 being (FinSequence of D109) such that L783: ( len C263 ) = ( ( D117 . C256 ) + 1 ) and L784: ( D112 . ( D117 . C256 ) ) = ( Sum C263 ) and L785: (for B199 being (Element of ( NAT )) holds (B199 in ( dom C263 ) implies ( C263 . B199 ) = ( ( D110 . ( B199 -' 1 ) ) * ( D111 . ( ( ( D117 . C256 ) + 1 ) -' B199 ) ) ))) by L779 , POLYNOM3:def 9;
L786: C256 < ( C256 + 1 ) by NAT_1:13;
reconsider D118 = ( D117 | C256 ) as (Element of ( Bags C256 )) by L786 , L32;
defpred S8[ set , set ] means (for B200 , B201 being (Polynomial of C256 , C255) holds (for B202 being (FinSequence of D107) holds (for B203 being (Element of ( NAT )) holds ((B203 = $1 & B200 = ( D110 . ( B203 -' 1 ) ) & B201 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' B203 ) ) & B202 = $2) implies (( ( B200 *' B201 ) . D118 ) = ( Sum B202 ) & ( len B202 ) = ( len ( decomp D118 ) ) & (for B204 being (Element of ( NAT )) holds (B204 in ( dom B202 ) implies (ex B205 , B206 being (bag of C256) st (( ( decomp D118 ) /. B204 ) = <* B205 , B206 *> & ( B202 /. B204 ) = ( ( B200 . B205 ) * ( B201 . B206 ) ))))))))));
reconsider D119 = ( D112 . ( D117 . C256 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
consider C264 being (FinSequence of D107) such that L787: ( D114 . D117 ) = ( Sum C264 ) and L788: ( len C264 ) = ( len ( decomp D117 ) ) and L789: (for B207 being (Element of ( NAT )) holds (B207 in ( dom C264 ) implies (ex B208 , B209 being (bag of ( C256 + 1 )) st (( ( decomp D117 ) /. B207 ) = <* B208 , B209 *> & ( C264 /. B207 ) = ( ( D115 . B208 ) * ( D116 . B209 ) ))))) by L780 , POLYNOM1:def 9;
L790:
now
let C265 being set;
assume L791: C265 in ( dom C263 );
reconsider D120 = C265 as (Element of ( NAT )) by L791;
reconsider D121 = ( D110 . ( D120 -' 1 ) ) , D122 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' D120 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
consider C266 being (FinSequence of D107) such that L792: (( ( D121 *' D122 ) . D118 ) = ( Sum C266 ) & ( len C266 ) = ( len ( decomp D118 ) ) & (for B210 being (Element of ( NAT )) holds (B210 in ( dom C266 ) implies (ex B211 , B212 being (bag of C256) st (( ( decomp D118 ) /. B210 ) = <* B211 , B212 *> & ( C266 /. B210 ) = ( ( D121 . B211 ) * ( D122 . B212 ) )))))) by POLYNOM1:def 9;
L793: C266 in ( D107 * ) by FINSEQ_1:def 11;
L794: S8[ D120 , C266 ] by L792;
thus L795: (ex B213 being set st (B213 in ( D107 * ) & S8[ C265 , B213 ])) by L794 , L793;
end;
consider C267 being (Function of ( dom C263 ) , ( D107 * )) such that L796: (for B214 being set holds (B214 in ( dom C263 ) implies S8[ B214 , ( C267 . B214 ) ])) from FUNCT_2:sch 1(L790);
L797: ( rng C267 ) c= ( D107 * );
L798: ( dom C267 ) = ( dom C263 ) by FUNCT_2:def 1;
L799: (ex B215 being Nat st ( dom C267 ) = ( Seg B215 )) by L798 , FINSEQ_1:def 2;
L800: C267 is  FinSequence-like by L799 , FINSEQ_1:def 2;
reconsider D123 = C267 as (FinSequence of ( D107 * )) by L800 , L797 , FINSEQ_1:def 4;
consider C268 being (Function of D109 , D107) such that L801: (for B216 being (Polynomial of C256 , C255) holds ( C268 . B216 ) = ( B216 . D118 )) and L802: ( D119 . D118 ) = ( Sum ( C268 * C263 ) ) by L784 , L624;
L803: ( Sum ( C268 * C263 ) ) = ( D113 . D117 ) by L802 , L675;
L804: ( ( 0 ) + 1 ) <= ( len C263 ) by L783 , XREAL_1:6;
L805: 1 in ( dom D123 ) by L804 , L798 , FINSEQ_3:25;
L806:
now
reconsider D124 = ( D110 . ( 1 -' 1 ) ) , D125 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' 1 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L807: ( D123 /. 1 ) is (FinSequence of D107);
L808: ( D123 . 1 ) is (FinSequence of D107) by L807 , L805 , PARTFUN1:def 6;
L809: (D124 = ( D110 . ( 1 -' 1 ) ) & D125 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' 1 ) ));
thus L810: ( len ( D123 . 1 ) ) <> ( 0 ) by L809 , L796 , L798 , L805 , L808;
end;
defpred S9[ set , set ] means (for B217 , B218 being (Element of ( NAT )) holds (for B219 being (bag of ( C256 + 1 )) holds ((B218 = $1 & B219 = ( ( divisors D117 ) . B218 ) & B217 in ( dom ( divisors D118 ) ) & ( ( divisors D118 ) . B217 ) = ( B219 | C256 )) implies (( ( B219 . C256 ) + 1 ) in ( dom D123 ) & B217 in ( dom ( D123 . ( ( B219 . C256 ) + 1 ) ) ) & $2 = ( ( Sum ( Card ( D123 | ( ( ( B219 . C256 ) + 1 ) -' 1 ) ) ) ) + B217 )))));
set D126 = ( FlattenSeq D123 );
L811:
now
let C269 being set;
assume L812: C269 in ( dom C264 );
reconsider D127 = C269 as (Element of ( NAT )) by L812;
L813: ( dom C264 ) = ( dom ( decomp D117 ) ) by L788 , FINSEQ_3:29
.= ( dom ( divisors D117 ) ) by PRE_POLY:def 17;
L814: ( ( divisors D117 ) . D127 ) in ( rng ( divisors D117 ) ) by L813 , L812 , FUNCT_1:def 3;
reconsider D128 = ( ( divisors D117 ) . D127 ) as (bag of ( C256 + 1 )) by L814;
L815: D128 divides D117 by L814 , L129;
L816: ( D128 . C256 ) <= ( D117 . C256 ) by L815 , PRE_POLY:def 11;
L817: ( ( D128 . C256 ) + 1 ) <= ( ( D117 . C256 ) + 1 ) by L816 , XREAL_1:6;
L818: C256 < ( C256 + 1 ) by NAT_1:13;
reconsider D129 = ( D128 | C256 ) as (Element of ( Bags C256 )) by L818 , L32;
reconsider D130 = ( D110 . ( ( ( D128 . C256 ) + 1 ) -' 1 ) ) , D131 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' ( ( D128 . C256 ) + 1 ) ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L819: (D130 = ( D110 . ( ( ( D128 . C256 ) + 1 ) -' 1 ) ) & D131 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' ( ( D128 . C256 ) + 1 ) ) ));
L820: D129 divides D118 by L815 , L43;
L821: D129 in ( rng ( divisors D118 ) ) by L820 , L129;
consider C270 being set such that L822: C270 in ( dom ( divisors D118 ) ) and L823: D129 = ( ( divisors D118 ) . C270 ) by L821 , FUNCT_1:def 3;
reconsider D132 = C270 as (Element of ( NAT )) by L822;
set D133 = ( ( Sum ( Card ( D123 | ( ( ( D128 . C256 ) + 1 ) -' 1 ) ) ) ) + D132 );
L824: ( ( D128 . C256 ) + 1 ) >= ( 1 + ( 0 ) ) by XREAL_1:6;
L825: ( ( D128 . C256 ) + 1 ) in ( dom D123 ) by L824 , L783 , L798 , L817 , FINSEQ_3:25;
L826: ( D123 . ( ( D128 . C256 ) + 1 ) ) is (Element of ( D107 * )) by L825 , L798 , FUNCT_2:5;
L827: ( len ( D123 . ( ( D128 . C256 ) + 1 ) ) ) = ( len ( decomp D118 ) ) by L826 , L796 , L798 , L825 , L819;
L828: ( dom ( D123 . ( ( D128 . C256 ) + 1 ) ) ) = ( dom ( decomp D118 ) ) by L827 , FINSEQ_3:29
.= ( dom ( divisors D118 ) ) by PRE_POLY:def 17;
L829: D133 in ( dom D126 ) by L828 , L822 , L825 , PRE_POLY:30;
L830: (for B220 , B221 being (Element of ( NAT )) holds (for B222 being (bag of ( C256 + 1 )) holds ((B221 = D127 & B222 = ( ( divisors D117 ) . B221 ) & B220 in ( dom ( divisors D118 ) ) & ( ( divisors D118 ) . B220 ) = ( B222 | C256 )) implies (( ( B222 . C256 ) + 1 ) in ( dom D123 ) & B220 in ( dom ( D123 . ( ( B222 . C256 ) + 1 ) ) ) & D133 = ( ( Sum ( Card ( D123 | ( ( ( B222 . C256 ) + 1 ) -' 1 ) ) ) ) + B220 ))))) by L783 , L798 , L822 , L823 , L817 , L824 , L828 , FINSEQ_3:25 , FUNCT_1:def 4;
thus L831: (ex B223 being set st (B223 in ( dom D126 ) & S9[ C269 , B223 ])) by L830 , L829;
end;
consider C271 being (Function of ( dom C264 ) , ( dom D126 )) such that L832: (for B224 being set holds (B224 in ( dom C264 ) implies S9[ B224 , ( C271 . B224 ) ])) from FUNCT_2:sch 1(L811);
L833: 1 in ( dom ( Card D123 ) ) by L805 , CARD_3:def 2;
L834: ( Sum ( Card D123 ) ) >= ( ( Card D123 ) . 1 ) by L833 , POLYNOM3:4;
L835: ( Sum ( Card D123 ) ) > ( 0 ) by L834 , L805 , L806 , CARD_3:def 2;
L836: ( len D126 ) > ( 0 ) by L835 , PRE_POLY:27;
L837: D126 <> ( {} ) by L836;
L838: ( dom C271 ) = ( dom C264 ) by L837 , FUNCT_2:def 1;
L839:
now
let C272 , C273 being set;
assume that
L840: C272 in ( dom C271 )
and
L841: C273 in ( dom C271 )
and
L842: ( C271 . C272 ) = ( C271 . C273 );
L843: ( dom C271 ) = ( dom C264 ) by L837 , FUNCT_2:def 1;
reconsider D134 = C272 , D135 = C273 as (Element of ( NAT )) by L843 , L840 , L841;
L844: ( dom C264 ) = ( dom ( decomp D117 ) ) by L788 , FINSEQ_3:29
.= ( dom ( divisors D117 ) ) by PRE_POLY:def 17;
L845: ( ( divisors D117 ) . D134 ) in ( rng ( divisors D117 ) ) by L844 , L840 , FUNCT_1:def 3;
reconsider D136 = ( ( divisors D117 ) . D134 ) as (bag of ( C256 + 1 )) by L845;
L846: ( ( divisors D117 ) . D135 ) in ( rng ( divisors D117 ) ) by L841 , L844 , FUNCT_1:def 3;
reconsider D137 = ( ( divisors D117 ) . D135 ) as (bag of ( C256 + 1 )) by L846;
L847: C256 < ( C256 + 1 ) by NAT_1:13;
reconsider D138 = ( D136 | C256 ) , D139 = ( D137 | C256 ) as (Element of ( Bags C256 )) by L847 , L32;
L848: (( ( Card D123 ) | ( ( ( D136 . C256 ) + 1 ) -' 1 ) ) = ( Card ( D123 | ( ( ( D136 . C256 ) + 1 ) -' 1 ) ) ) & ( ( Card D123 ) | ( ( ( D137 . C256 ) + 1 ) -' 1 ) ) = ( Card ( D123 | ( ( ( D137 . C256 ) + 1 ) -' 1 ) ) )) by POLYNOM3:16;
L849: D137 divides D117 by L846 , L129;
L850: D139 divides D118 by L849 , L43;
L851: D139 in ( rng ( divisors D118 ) ) by L850 , L129;
consider C274 being set such that L852: C274 in ( dom ( divisors D118 ) ) and L853: D139 = ( ( divisors D118 ) . C274 ) by L851 , FUNCT_1:def 3;
reconsider D140 = C274 as (Element of ( NAT )) by L852;
L854: (( ( D137 . C256 ) + 1 ) in ( dom D123 ) & D140 in ( dom ( D123 . ( ( D137 . C256 ) + 1 ) ) )) by L832 , L841 , L852 , L853;
L855: D136 divides D117 by L845 , L129;
L856: D138 divides D118 by L855 , L43;
L857: D138 in ( rng ( divisors D118 ) ) by L856 , L129;
consider C275 being set such that L858: C275 in ( dom ( divisors D118 ) ) and L859: D138 = ( ( divisors D118 ) . C275 ) by L857 , FUNCT_1:def 3;
reconsider D141 = C275 as (Element of ( NAT )) by L858;
L860: ( C271 . D134 ) = ( ( Sum ( Card ( D123 | ( ( ( D136 . C256 ) + 1 ) -' 1 ) ) ) ) + D141 ) by L832 , L840 , L858 , L859;
L861: ( C271 . D135 ) = ( ( Sum ( Card ( D123 | ( ( ( D137 . C256 ) + 1 ) -' 1 ) ) ) ) + D140 ) by L832 , L841 , L852 , L853;
L862: D137 is (Element of ( Bags ( C256 + 1 ) )) by PRE_POLY:def 12;
L863: (( ( D136 . C256 ) + 1 ) in ( dom D123 ) & D141 in ( dom ( D123 . ( ( D136 . C256 ) + 1 ) ) )) by L832 , L840 , L858 , L859;
L864: (( ( D136 . C256 ) + 1 ) = ( ( D137 . C256 ) + 1 ) & D141 = D140) by L863 , L842 , L860 , L854 , L861 , L848 , POLYNOM3:22;
L865: D136 is (Element of ( Bags ( C256 + 1 ) )) by PRE_POLY:def 12;
L866: D136 = ( D138 bag_extend ( D136 . C256 ) ) by L865 , L77
.= D137 by L859 , L853 , L864 , L862 , L77;
thus L867: C272 = C273 by L866 , L840 , L841 , L844 , FUNCT_1:def 4;
end;
L868: C271 is  one-to-one by L839 , FUNCT_1:def 4;
L869: ( dom D126 ) c= ( rng C271 )
proof
let C276 being set;
assume L870: C276 in ( dom D126 );
reconsider D142 = C276 as (Element of ( NAT )) by L870;
consider C277 , C278 being (Element of ( NAT )) such that L871: C277 in ( dom D123 ) and L872: C278 in ( dom ( D123 . C277 ) ) and L873: D142 = ( ( Sum ( Card ( D123 | ( C277 -' 1 ) ) ) ) + C278 ) and L874: ( ( D123 . C277 ) . C278 ) = ( D126 . D142 ) by L870 , PRE_POLY:29;
L875: ( D123 . C277 ) in ( D107 * ) by L798 , L871 , FUNCT_2:5;
L876: ( D123 . C277 ) is (FinSequence of D107) by L875 , FINSEQ_1:def 11;
reconsider D143 = ( ( divisors D118 ) /. C278 ) as (bag of C256);
set D144 = ( D143 bag_extend ( C277 -' 1 ) );
reconsider D145 = ( D110 . ( C277 -' 1 ) ) , D146 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' C277 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L877: ( D144 . C256 ) = ( C277 -' 1 ) by L77;
L878: 1 <= C277 by L871 , FINSEQ_3:25;
L879: ( ( D144 . C256 ) + 1 ) = C277 by L878 , L877 , XREAL_1:235;
L880: ( dom C264 ) = ( dom ( decomp D117 ) ) by L788 , FINSEQ_3:29
.= ( dom ( divisors D117 ) ) by PRE_POLY:def 17;
L881: (D145 = ( D110 . ( C277 -' 1 ) ) & D146 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' C277 ) ));
L882: ( len ( D123 . C277 ) ) = ( len ( decomp D118 ) ) by L881 , L796 , L798 , L871 , L876;
L883: ( dom ( D123 . C277 ) ) = ( dom ( decomp D118 ) ) by L882 , FINSEQ_3:29
.= ( dom ( divisors D118 ) ) by PRE_POLY:def 17;
L884: D143 = ( ( divisors D118 ) . C278 ) by L883 , L872 , PARTFUN1:def 6;
L885: D143 in ( rng ( divisors D118 ) ) by L884 , L872 , L883 , FUNCT_1:def 3;
L886: D143 divides D118 by L885 , L129;
L887:
now
let C279 being set;
per cases ;
suppose L888: C279 in ( C256 + 1 );

L889:
now
per cases ;
suppose L890: C279 in C256;

L891: ( D117 . C279 ) = ( D118 . C279 ) by L890 , FUNCT_1:49;
L892: ( D144 . C279 ) = ( ( D144 | C256 ) . C279 ) by L890 , FUNCT_1:49
.= ( D143 . C279 ) by L77;
thus L893: ( D144 . C279 ) <= ( D117 . C279 ) by L892 , L886 , L891 , PRE_POLY:def 11;
end;
suppose L894: (not C279 in C256);

L895: 1 <= C277 by L871 , FINSEQ_3:25;
L896: C277 <= ( ( D117 . C256 ) + 1 ) by L783 , L798 , L871 , FINSEQ_3:25;
L897: ( C277 - 1 ) <= ( ( ( D117 . C256 ) + 1 ) - 1 ) by L896 , XREAL_1:9;
L898: ( C256 + 1 ) = ( succ C256 ) by NAT_1:38
.= ( C256 \/ { C256 } ) by ORDINAL1:def 1;
L899: C279 in { C256 } by L898 , L888 , L894 , XBOOLE_0:def 3;
L900: C279 = C256 by L899 , TARSKI:def 1;
L901: ( D144 . C279 ) = ( C277 -' 1 ) by L900 , L77;
thus L902: ( D144 . C279 ) <= ( D117 . C279 ) by L901 , L900 , L895 , L897 , XREAL_1:233;
end;
end;
thus L904: ( D144 . C279 ) <= ( D117 . C279 ) by L889;
end;
suppose L905: (not C279 in ( C256 + 1 ));

L906: ( dom D144 ) = ( C256 + 1 ) by PARTFUN1:def 2;
thus L907: ( D144 . C279 ) <= ( D117 . C279 ) by L906 , L905 , FUNCT_1:def 2;
end;
end;
L909: D144 divides D117 by L887 , PRE_POLY:def 11;
L910: D144 in ( rng ( divisors D117 ) ) by L909 , L129;
consider C280 being set such that L911: C280 in ( dom ( divisors D117 ) ) and L912: D144 = ( ( divisors D117 ) . C280 ) by L910 , FUNCT_1:def 3;
L913: ( dom C271 ) = ( dom C264 ) by L837 , FUNCT_2:def 1;
L914: ( ( divisors D118 ) . C278 ) = ( D144 | C256 ) by L884 , L77;
L915: ( C271 . C280 ) = ( ( Sum ( Card ( D123 | ( ( ( D144 . C256 ) + 1 ) -' 1 ) ) ) ) + C278 ) by L914 , L832 , L872 , L883 , L911 , L912 , L880;
thus L916: thesis by L915 , L873 , L911 , L913 , L880 , L879 , FUNCT_1:def 3;
end;
L917: ( rng C271 ) = ( dom D126 ) by L869 , XBOOLE_0:def 10;
L918: ( len ( Sum D123 ) ) = ( len D123 ) by MATRLIN:def 6;
L919: ( dom ( Sum D123 ) ) = ( dom C263 ) by L918 , L798 , FINSEQ_3:29;
L920:
now
let C281 being Nat;
reconsider D147 = ( D110 . ( C281 -' 1 ) ) , D148 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' C281 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
reconsider D149 = ( D147 *' D148 ) as (Element of D109) by POLYNOM1:def 10;
assume L921: C281 in ( dom C263 );
reconsider D150 = ( D123 . C281 ) as (Element of ( D107 * )) by L921 , FUNCT_2:5;
reconsider D151 = D150 as (FinSequence of D107);
L922: ( C263 . C281 ) = ( ( D110 . ( C281 -' 1 ) ) * ( D111 . ( ( ( D117 . C256 ) + 1 ) -' C281 ) ) ) by L785 , L921
.= D149 by POLYNOM1:def 10;
L923: (( ( Sum D123 ) /. C281 ) = ( ( Sum D123 ) . C281 ) & ( D123 /. C281 ) = ( D123 . C281 )) by L798 , L919 , L921 , PARTFUN1:def 6;
thus L924: ( ( Sum D123 ) . C281 ) = ( Sum D151 ) by L923 , L919 , L921 , MATRLIN:def 6
.= ( ( D147 *' D148 ) . D118 ) by L796 , L921
.= ( C268 . ( C263 . C281 ) ) by L801 , L922
.= ( ( C268 * C263 ) . C281 ) by L921 , FUNCT_1:13;
end;
L925:
now
let C282 being (Element of ( NAT ));
reconsider D152 = ( ( divisors D117 ) /. C282 ) as (bag of ( C256 + 1 ));
assume L926: C282 in ( dom C264 );
consider C283 , C284 being (bag of ( C256 + 1 )) such that L927: ( ( decomp D117 ) /. C282 ) = <* C283 , C284 *> and L928: ( C264 /. C282 ) = ( ( D115 . C283 ) * ( D116 . C284 ) ) by L926 , L789;
L929: ( dom C264 ) = ( dom ( decomp D117 ) ) by L788 , FINSEQ_3:29;
L930: <* C283 , C284 *> = <* D152 , ( D117 -' D152 ) *> by L929 , L926 , L927 , PRE_POLY:def 17;
L931: C283 = D152 by L930 , FINSEQ_1:77;
reconsider D153 = ( D110 . ( C283 . C256 ) ) , D154 = ( D111 . ( C284 . C256 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L932: C256 < ( C256 + 1 ) by NAT_1:13;
reconsider D155 = ( C283 | C256 ) , D156 = ( C284 | C256 ) as (Element of ( Bags C256 )) by L932 , L32;
L933: ( C264 . C282 ) = ( ( D115 . C283 ) * ( D116 . C284 ) ) by L926 , L928 , PARTFUN1:def 6
.= ( ( D153 . D155 ) * ( D116 . C284 ) ) by L675
.= ( ( D153 . D155 ) * ( D154 . D156 ) ) by L675;
L934: C284 = ( D117 -' D152 ) by L930 , FINSEQ_1:77;
L935: C282 in ( dom ( divisors D117 ) ) by L926 , L929 , PRE_POLY:def 17;
L936: C283 = ( ( divisors D117 ) . C282 ) by L935 , L931 , PARTFUN1:def 6;
L937: C283 in ( rng ( divisors D117 ) ) by L936 , L935 , FUNCT_1:def 3;
L938: C283 divides D117 by L937 , L129;
L939: D155 divides D118 by L938 , L43;
L940: D155 in ( rng ( divisors D118 ) ) by L939 , L129;
consider C285 being set such that L941: C285 in ( dom ( divisors D118 ) ) and L942: D155 = ( ( divisors D118 ) . C285 ) by L940 , FUNCT_1:def 3;
reconsider D157 = C285 as (Element of ( NAT )) by L941;
L943: ( C283 . C256 ) <= ( D117 . C256 ) by L938 , PRE_POLY:def 11;
L944: ( ( C283 . C256 ) + 1 ) <= ( ( D117 . C256 ) + 1 ) by L943 , XREAL_1:6;
L945: ( ( ( D117 . C256 ) + 1 ) -' ( ( C283 . C256 ) + 1 ) ) = ( ( ( D117 . C256 ) + 1 ) - ( ( C283 . C256 ) + 1 ) ) by L944 , XREAL_1:233
.= ( ( ( ( D117 . C256 ) - ( C283 . C256 ) ) + 1 ) - 1 )
.= ( ( D117 . C256 ) -' ( C283 . C256 ) ) by L943 , XREAL_1:233
.= ( C284 . C256 ) by L931 , L934 , PRE_POLY:def 6;
L946: ( ( ( C283 . C256 ) + 1 ) -' 1 ) = ( ( ( C283 . C256 ) + 1 ) - 1 ) by NAT_D:37
.= ( C283 . C256 );
L947: D153 = ( D110 . ( ( ( C283 . C256 ) + 1 ) -' 1 ) ) by L946;
L948: ( ( C283 . C256 ) + 1 ) in ( dom D123 ) by L832 , L926 , L936 , L941 , L942;
L949: ( D123 . ( ( C283 . C256 ) + 1 ) ) is (Element of ( D107 * )) by L948 , L798 , FUNCT_2:5;
reconsider D158 = ( D123 . ( ( C283 . C256 ) + 1 ) ) as (FinSequence of D107) by L949;
L950: D157 in ( dom ( D123 . ( ( C283 . C256 ) + 1 ) ) ) by L832 , L926 , L936 , L941 , L942;
consider C286 , C287 being (bag of C256) such that L951: ( ( decomp D118 ) /. D157 ) = <* C286 , C287 *> and L952: ( D158 /. D157 ) = ( ( D153 . C286 ) * ( D154 . C287 ) ) by L950 , L796 , L798 , L948 , L946 , L945;
L953: ( C271 . C282 ) = ( ( Sum ( Card ( D123 | ( ( ( C283 . C256 ) + 1 ) -' 1 ) ) ) ) + D157 ) by L832 , L926 , L936 , L941 , L942;
L954: ( D126 . ( C271 . C282 ) ) = ( ( D123 . ( ( C283 . C256 ) + 1 ) ) . D157 ) by L953 , L948 , L950 , PRE_POLY:30;
reconsider D159 = ( ( divisors D118 ) /. D157 ) as (bag of C256);
L955: ( dom ( divisors D118 ) ) = ( dom ( decomp D118 ) ) by PRE_POLY:def 17;
L956: <* C286 , C287 *> = <* D159 , ( D118 -' D159 ) *> by L955 , L941 , L951 , PRE_POLY:def 17;
L957: C286 = D159 by L956 , FINSEQ_1:77;
L958: C286 = D155 by L957 , L941 , L942 , PARTFUN1:def 6;
L959: D154 = ( D111 . ( ( ( D117 . C256 ) + 1 ) -' ( ( C283 . C256 ) + 1 ) ) ) by L945;
L960: ( len D158 ) = ( len ( decomp D118 ) ) by L959 , L796 , L798 , L948 , L947;
L961: ( dom D158 ) = ( dom ( divisors D118 ) ) by L960 , L955 , FINSEQ_3:29;
L962: C287 = ( D118 -' D159 ) by L956 , FINSEQ_1:77;
L963: C287 = D156 by L962 , L931 , L934 , L957 , L958 , L56;
thus L964: ( C264 . C282 ) = ( D126 . ( C271 . C282 ) ) by L963 , L933 , L941 , L954 , L952 , L958 , L961 , PARTFUN1:def 6;
end;
L965: ( dom C263 ) = ( dom ( C268 * C263 ) ) by FINSEQ_3:120;
L966: ( Sum D123 ) = ( C268 * C263 ) by L965 , L919 , L920 , FINSEQ_1:13;
L967: ( Sum D126 ) = ( D113 . D117 ) by L966 , L803 , POLYNOM1:14;
L968: ( len C264 ) = ( card ( dom C264 ) ) by CARD_1:62
.= ( card (C271 qua set) ) by L838 , CARD_1:62
.= ( card ( dom D126 ) ) by L868 , L917 , PRE_POLY:19
.= ( len D126 ) by CARD_1:62;
L969: ( dom C264 ) = ( dom D126 ) by L968 , FINSEQ_3:29;
L970: C271 is (Permutation of ( dom C264 )) by L969 , L868 , L917 , FUNCT_2:57;
thus L971: ( D113 . C262 ) = ( D114 . C262 ) by L970 , L967 , L787 , L925 , L968 , L969 , RLVECT_2:6;
end;
thus L972: ( D106 . ( C260 * C261 ) ) = ( ( D106 . C260 ) * ( D106 . C261 ) ) by L781 , FUNCT_2:12;
end;

end;
cluster ( upm (C256 , C255) ) ->  unity-preserving;
coherence
proof
set D160 = ( upm (C256 , C255) );
set D161 = ( Polynom-Ring (C256 , C255) );
set D162 = ( Polynom-Ring (( C256 + 1 ) , C255) );
set D163 = ( Polynom-Ring ( Polynom-Ring (C256 , C255) ) );
set D164 = (the carrier of D162);
reconsider D165 = ( 1_ D163 ) as (Polynomial of D161) by POLYNOM3:def 10;
reconsider D166 = ( 1_ D162 ) as (Polynomial of ( C256 + 1 ) , C255) by POLYNOM1:def 10;
L779: ( D160 . ( 1_ D163 ) ) in D164;
reconsider D167 = ( D160 . D165 ) as (Polynomial of ( C256 + 1 ) , C255) by L779 , POLYNOM1:def 10;
L780:
now
let C288 being set;
assume L781: C288 in ( Bags ( C256 + 1 ) );
reconsider D168 = C288 as (Element of ( Bags ( C256 + 1 ) )) by L781;
reconsider D169 = ( D165 . ( D168 . C256 ) ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L782: ( D167 . D168 ) = ( D169 . ( D168 | C256 ) ) by L675;
L783:
now
per cases ;
suppose L784: (( D168 | C256 ) = ( EmptyBag C256 ) & ( D168 . C256 ) = ( 0 ));

L785: D168 = ( ( EmptyBag C256 ) bag_extend ( 0 ) ) by L784 , L77
.= ( EmptyBag ( C256 + 1 ) ) by L117;
L786: D169 = ( ( 1_. D161 ) . ( 0 ) ) by L784 , POLYNOM3:def 10
.= ( 1_ D161 ) by POLYNOM3:30
.= ( 1_ (C256 , C255) ) by POLYNOM1:31;
thus L787: ( D167 . D168 ) = ( 1_ C255 ) by L786 , L782 , L784 , POLYNOM1:25
.= ( ( 1_ (( C256 + 1 ) , C255) ) . D168 ) by L785 , POLYNOM1:25
.= ( D166 . D168 ) by POLYNOM1:31;
end;
suppose L788: (( D168 | C256 ) <> ( EmptyBag C256 ) or ( D168 . C256 ) <> ( 0 ));

L789:
now
L790: C256 < ( C256 + 1 ) by NAT_1:13;
L791: ( D168 | C256 ) is (bag of C256) by L790 , L32;
L792: D169 = ( ( 1_. D161 ) . ( D168 . C256 ) ) by POLYNOM3:def 10;
per cases ;
suppose L793: ( D168 . C256 ) = ( 0 );

L794: D169 = ( 1_ D161 ) by L793 , L792 , POLYNOM3:30
.= ( 1_ (C256 , C255) ) by POLYNOM1:31;
thus L795: ( D167 . D168 ) = ( 0. C255 ) by L794 , L782 , L788 , L791 , L793 , POLYNOM1:25;
end;
suppose L796: ( D168 . C256 ) <> ( 0 );

L797: D169 = ( 0. D161 ) by L796 , L792 , POLYNOM3:30
.= ( 0_ (C256 , C255) ) by POLYNOM1:def 10;
thus L798: ( D167 . D168 ) = ( 0. C255 ) by L797 , L782 , L791 , POLYNOM1:22;
end;
end;
L800: D168 <> ( ( EmptyBag C256 ) bag_extend ( 0 ) ) by L788 , L77;
L801: D168 <> ( EmptyBag ( C256 + 1 ) ) by L800 , L117;
thus L802: ( D167 . D168 ) = ( ( 1_ (( C256 + 1 ) , C255) ) . D168 ) by L801 , L789 , POLYNOM1:25
.= ( D166 . D168 ) by POLYNOM1:31;
end;
end;
thus L804: ( D167 . C288 ) = ( D166 . C288 ) by L783;
end;
L805: D166 = D167 by L780 , FUNCT_2:12;
thus L806: thesis by L805 , GROUP_1:def 13;
end;
cluster ( upm (C256 , C255) ) ->  one-to-one;
coherence
proof
set D170 = ( upm (C256 , C255) );
set D171 = ( Polynom-Ring (C256 , C255) );
set D172 = ( Polynom-Ring ( Polynom-Ring (C256 , C255) ) );
L807:
now
let C289 , C290 being (Element of D172);
reconsider D173 = C289 , D174 = C290 as (Polynomial of D171) by POLYNOM3:def 10;
reconsider D175 = ( D170 . C290 ) as (Polynomial of ( C256 + 1 ) , C255) by POLYNOM1:def 10;
assume L808: ( D170 . C289 ) = ( D170 . C290 );
L809:
now
let C291 being set;
assume L810: C291 in ( NAT );
reconsider D176 = C291 as (Element of ( NAT )) by L810;
reconsider D177 = ( D173 . D176 ) , D178 = ( D174 . D176 ) as (Polynomial of C256 , C255) by POLYNOM1:def 10;
L811:
now
let C292 being set;
assume L812: C292 in ( Bags C256 );
reconsider D179 = C292 as (bag of C256) by L812;
set D180 = ( D179 bag_extend D176 );
L813: (( D180 | C256 ) = D179 & ( D180 . C256 ) = D176) by L77;
L814: ( D177 . D179 ) = ( D175 . D180 ) by L813 , L808 , L675
.= ( D178 . D179 ) by L813 , L675;
thus L815: ( D177 . C292 ) = ( D178 . C292 ) by L814;
end;
thus L816: ( D173 . C291 ) = ( D174 . C291 ) by L811 , FUNCT_2:12;
end;
thus L817: C289 = C290 by L809 , FUNCT_2:12;
end;
thus L818: thesis by L807 , WAYBEL_1:def 1;
end;
end;
definition
let C293 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr;
let C294 being (Element of ( NAT ));
func mpu (C294 , C293) -> (Function of ( Polynom-Ring (( C294 + 1 ) , C293) ) , ( Polynom-Ring ( Polynom-Ring (C294 , C293) ) )) means 
:L820: (for B225 being (Polynomial of ( C294 + 1 ) , C293) holds (for B226 being (Polynomial of C294 , C293) holds (for B227 being (Polynomial of ( Polynom-Ring (C294 , C293) )) holds (for B228 being (Element of ( NAT )) holds (for B229 being (bag of C294) holds ((B227 = ( it . B225 ) & B226 = ( B227 . B228 )) implies ( B226 . B229 ) = ( B225 . ( B229 bag_extend B228 ) )))))));
existence
proof
set D181 = (the carrier of C293);
set D182 = ( Polynom-Ring (C294 , C293) );
set D183 = ( Polynom-Ring (( C294 + 1 ) , C293) );
set D184 = ( Polynom-Ring ( Polynom-Ring (C294 , C293) ) );
set D185 = (the carrier of D184);
set D186 = (the carrier of D183);
set D187 = (the carrier of D182);
defpred S10[ (Element of D186) , (Element of D185) ] means (for B230 being (Polynomial of ( C294 + 1 ) , C293) holds (for B231 being (Polynomial of C294 , C293) holds (for B232 being (Polynomial of ( Polynom-Ring (C294 , C293) )) holds (for B233 being (Element of ( NAT )) holds (for B234 being (bag of C294) holds ((B230 = $1 & B232 = $2 & B231 = ( B232 . B233 )) implies ( B231 . B234 ) = ( B230 . ( B234 bag_extend B233 ) )))))));
L821:
now
let C295 being (Element of D186);
reconsider D188 = C295 as (Polynomial of ( C294 + 1 ) , C293) by POLYNOM1:def 10;
defpred S11[ (Element of ( NAT )) , (Element of D187) ] means (for B235 being (Polynomial of C294 , C293) holds (for B236 being (bag of C294) holds (B235 = $2 implies ( B235 . B236 ) = ( D188 . ( B236 bag_extend $1 ) ))));
L822:
now
let C296 being (Element of ( NAT ));
deffunc H3((Element of ( Bags C294 ))) = ( D188 . ( $1 bag_extend C296 ) );
consider C297 being (Function of ( Bags C294 ) , D181) such that L823: (for B237 being (Element of ( Bags C294 )) holds ( C297 . B237 ) = H3(B237)) from FUNCT_2:sch 4;
reconsider D189 = C297 as (Function of ( Bags C294 ) , C293);
reconsider D190 = D189 as (Series of C294 , C293);
L824:
now
per cases ;
suppose L825: ( Support D188 ) = ( {} );

L826:
now
assume L827: ( Support D190 ) <> ( {} );
consider C298 being set such that L828: C298 in ( Support D190 ) by L827 , XBOOLE_0:def 1;
reconsider D191 = C298 as (Element of ( Bags C294 )) by L828;
L829: ( D190 . D191 ) <> ( 0. C293 ) by L828 , POLYNOM1:def 3;
L830: ( D188 . ( D191 bag_extend C296 ) ) <> ( 0. C293 ) by L829 , L823;
thus L831: ( Support D188 ) <> ( {} ) by L830 , POLYNOM1:def 3;
end;
thus L832: ( Support D190 ) is  finite by L826 , L825;
end;
suppose L833: ( Support D190 ) = ( {} );

thus L834: ( Support D190 ) is  finite by L833;
end;
suppose L835: (( Support D188 ) <> ( {} ) & ( Support D190 ) <> ( {} ));

reconsider D192 = ( Support D190 ) as non  empty (Subset of ( Bags C294 )) by L835;
reconsider D193 = ( Support D188 ) as non  empty (Subset of ( Bags ( C294 + 1 ) )) by L835;
defpred S12[ (Element of D192) , set ] means $2 = ( $1 bag_extend C296 );
L836:
now
let C299 being (Element of D192);
L837: (C299 is (Element of ( Bags C294 )) & ( D190 . C299 ) <> ( 0. C293 )) by POLYNOM1:def 3;
L838: ( D188 . ( C299 bag_extend C296 ) ) <> ( 0. C293 ) by L837 , L823;
L839: ( C299 bag_extend C296 ) in ( Support D188 ) by L838 , POLYNOM1:def 3;
thus L840: (ex B238 being (Element of D193) st S12[ C299 , B238 ]) by L839;
end;
consider C300 being (Function of D192 , D193) such that L841: (for B239 being (Element of D192) holds S12[ B239 , ( C300 . B239 ) ]) from FUNCT_2:sch 3(L836);
L842: ( dom C300 ) = D192 by FUNCT_2:def 1;
L843:
now
let C301 , C302 being set;
assume that
L844: C301 in ( dom C300 )
and
L845: C302 in ( dom C300 )
and
L846: ( C300 . C301 ) = ( C300 . C302 );
reconsider D194 = C301 , D195 = C302 as (Element of ( Bags C294 )) by L842 , L844 , L845;
L847: ( D194 bag_extend C296 ) = ( C300 . C301 ) by L841 , L844
.= ( D195 bag_extend C296 ) by L841 , L845 , L846;
L848: D194 = ( ( D194 bag_extend C296 ) | C294 ) by L77
.= D195 by L847 , L77;
thus L849: C301 = C302 by L848;
end;
L850: C300 is  one-to-one by L843 , FUNCT_1:def 4;
L851: ( rng C300 ) c= D193;
L852: ( card D192 ) c= ( card D193 ) by L851 , L842 , L850 , CARD_1:10;
thus L853: ( Support D190 ) is  finite by L852;
end;
end;
L855: D190 is  finite-Support by L824 , POLYNOM1:def 4;
reconsider D196 = D190 as (Element of D187) by L855 , POLYNOM1:def 10;
take D197 = D196;
L856:
now
let C303 being (Polynomial of C294 , C293);
let C304 being (bag of C294);
L857: C304 is (Element of ( Bags C294 )) by PRE_POLY:def 12;
assume L858: C303 = D197;
thus L859: ( C303 . C304 ) = ( D188 . ( C304 bag_extend C296 ) ) by L858 , L823 , L857;
end;
thus L860: S11[ C296 , D197 ] by L856;
end;
consider C305 being (Function of ( NAT ) , D187) such that L861: (for B240 being (Element of ( NAT )) holds S11[ B240 , ( C305 . B240 ) ]) from FUNCT_2:sch 3(L822);
reconsider D198 = C305 as (sequence of D182);
L862:
now
per cases ;
suppose L863: ( Support D188 ) = ( {} );

L864:
now
let C306 being Nat;
assume L865: C306 >= ( 0 );
reconsider D199 = C306 as (Element of ( NAT )) by ORDINAL1:def 12;
reconsider D200 = ( D198 . D199 ) as (Polynomial of C294 , C293) by POLYNOM1:def 10;
L866:
now
let C307 being set;
assume L867: C307 in ( Bags C294 );
reconsider D201 = C307 as (Element of ( Bags C294 )) by L867;
L868: ( D188 . ( D201 bag_extend C306 ) ) = ( 0. C293 ) by L863 , POLYNOM1:def 3;
L869: ( D200 . D201 ) = ( 0. C293 ) by L868 , L861;
thus L870: ( D200 . C307 ) = ( ( ( Bags C294 ) --> ( 0. C293 ) ) . C307 ) by L869 , FUNCOP_1:7;
end;
L871: (( dom ( ( Bags C294 ) --> ( 0. C293 ) ) ) = ( Bags C294 ) & ( dom D200 ) = ( Bags C294 )) by FUNCT_2:def 1;
L872: D200 = ( ( Bags C294 ) --> ( 0. C293 ) ) by L871 , L866 , FUNCT_1:2;
thus L873: ( D198 . C306 ) = ( 0_ (C294 , C293) ) by L872 , POLYNOM1:def 7
.= ( 0. D182 ) by POLYNOM1:def 10;
end;
thus L874: D198 is  finite-Support by L864 , ALGSEQ_1:def 1;
end;
suppose L875: ( Support D188 ) <> ( {} );

reconsider D202 = ( Support D188 ) as  finite non  empty (Subset of ( Bags ( C294 + 1 ) )) by L875;
deffunc H4((Element of ( Bags ( C294 + 1 ) ))) = ( $1 . C294 );
consider C308 being (Function of ( Bags ( C294 + 1 ) ) , ( NAT )) such that L876: (for B241 being (Element of ( Bags ( C294 + 1 ) )) holds ( C308 . B241 ) = H4(B241)) from FUNCT_2:sch 4;
reconsider D203 = ( max ( C308 .: D202 ) ) as (Element of ( NAT )) by ORDINAL1:def 12;
L877:
now
let C309 being Nat;
reconsider D204 = C309 as (Element of ( NAT )) by ORDINAL1:def 12;
reconsider D205 = ( D198 . D204 ) as (Polynomial of C294 , C293) by POLYNOM1:def 10;
assume L878: C309 >= ( D203 + 1 );
L879:
now
let C310 being set;
assume L880: C310 in ( Bags C294 );
reconsider D206 = C310 as (Element of ( Bags C294 )) by L880;
L881: C309 > D203 by L878 , NAT_1:13;
L882: (not C309 in ( C308 .: D202 )) by L881 , XXREAL_2:def 8;
L883: ( C308 . ( D206 bag_extend C309 ) ) = ( ( D206 bag_extend C309 ) . C294 ) by L876
.= C309 by L77;
L884: (not ( D206 bag_extend C309 ) in D202) by L883 , L882 , FUNCT_2:35;
L885: ( D188 . ( D206 bag_extend C309 ) ) = ( 0. C293 ) by L884 , POLYNOM1:def 3;
L886: ( D205 . D206 ) = ( 0. C293 ) by L885 , L861;
thus L887: ( D205 . C310 ) = ( ( ( Bags C294 ) --> ( 0. C293 ) ) . C310 ) by L886 , FUNCOP_1:7;
end;
L888: (( dom ( ( Bags C294 ) --> ( 0. C293 ) ) ) = ( Bags C294 ) & ( dom D205 ) = ( Bags C294 )) by FUNCT_2:def 1;
L889: D205 = ( ( Bags C294 ) --> ( 0. C293 ) ) by L888 , L879 , FUNCT_1:2;
thus L890: ( D198 . C309 ) = ( 0_ (C294 , C293) ) by L889 , POLYNOM1:def 7
.= ( 0. D182 ) by POLYNOM1:def 10;
end;
thus L891: D198 is  finite-Support by L877 , ALGSEQ_1:def 1;
end;
end;
reconsider D207 = D198 as (Element of D185) by L862 , POLYNOM3:def 10;
take D208 = D207;
thus L893: S10[ C295 , D208 ] by L861;
end;
consider C311 being (Function of D186 , D185) such that L894: (for B242 being (Element of D186) holds S10[ B242 , ( C311 . B242 ) ]) from FUNCT_2:sch 3(L821);
reconsider D209 = C311 as (Function of D183 , D184);
take D209;
L895:
now
let C312 being (Polynomial of ( C294 + 1 ) , C293);
let C313 being (Polynomial of C294 , C293);
let C314 being (Polynomial of ( Polynom-Ring (C294 , C293) ));
let C315 being (Element of ( NAT ));
let C316 being (bag of C294);
L896: C312 in D186 by POLYNOM1:def 10;
assume L897: (C314 = ( D209 . C312 ) & C313 = ( C314 . C315 ));
thus L898: ( C313 . C316 ) = ( C312 . ( C316 bag_extend C315 ) ) by L897 , L894 , L896;
end;
thus L899: thesis by L895;
end;
uniqueness
proof
set D210 = ( Polynom-Ring (C294 , C293) );
set D211 = ( Polynom-Ring (( C294 + 1 ) , C293) );
set D212 = ( Polynom-Ring ( Polynom-Ring (C294 , C293) ) );
set D213 = (the carrier of D211);
let C317 , C318 being (Function of D211 , D212);
assume L900: (for B243 being (Polynomial of ( C294 + 1 ) , C293) holds (for B244 being (Polynomial of C294 , C293) holds (for B245 being (Polynomial of ( Polynom-Ring (C294 , C293) )) holds (for B246 being (Element of ( NAT )) holds (for B247 being (bag of C294) holds ((B245 = ( C317 . B243 ) & B244 = ( B245 . B246 )) implies ( B244 . B247 ) = ( B243 . ( B247 bag_extend B246 ) )))))));
assume L901: (for B248 being (Polynomial of ( C294 + 1 ) , C293) holds (for B249 being (Polynomial of C294 , C293) holds (for B250 being (Polynomial of ( Polynom-Ring (C294 , C293) )) holds (for B251 being (Element of ( NAT )) holds (for B252 being (bag of C294) holds ((B250 = ( C318 . B248 ) & B249 = ( B250 . B251 )) implies ( B249 . B252 ) = ( B248 . ( B252 bag_extend B251 ) )))))));
L902:
now
let C319 being set;
assume L903: C319 in D213;
reconsider D214 = C319 as (Element of D213) by L903;
reconsider D215 = C319 as (Polynomial of ( C294 + 1 ) , C293) by L903 , POLYNOM1:def 10;
reconsider D216 = ( C317 . D214 ) , D217 = ( C318 . D214 ) as (Polynomial of D210) by POLYNOM3:def 10;
L904:
now
let C320 being set;
assume L905: C320 in ( NAT );
reconsider D218 = C320 as (Element of ( NAT )) by L905;
reconsider D219 = ( D216 . D218 ) , D220 = ( D217 . D218 ) as (Polynomial of C294 , C293) by POLYNOM1:def 10;
L906:
now
let C321 being set;
assume L907: C321 in ( Bags C294 );
reconsider D221 = C321 as (bag of C294) by L907;
thus L908: ( D219 . C321 ) = ( D215 . ( D221 bag_extend D218 ) ) by L900
.= ( D220 . C321 ) by L901;
end;
thus L909: ( D216 . C320 ) = ( D217 . C320 ) by L906 , FUNCT_2:12;
end;
thus L910: ( C317 . C319 ) = ( C318 . C319 ) by L904 , FUNCT_2:12;
end;
thus L911: C317 = C318 by L902 , FUNCT_2:12;
end;
end;
theorem
L913: (for B253 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial non  empty doubleLoopStr holds (for B254 being (Element of ( NAT )) holds (for B255 being (Element of ( Polynom-Ring (( B254 + 1 ) , B253) )) holds ( ( upm (B254 , B253) ) . ( ( mpu (B254 , B253) ) . B255 ) ) = B255)))
proof
let C322 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr;
let C323 being (Element of ( NAT ));
let C324 being (Element of ( Polynom-Ring (( C323 + 1 ) , C322) ));
set D222 = ( Polynom-Ring (C323 , C322) );
reconsider D223 = C324 as (Polynomial of ( C323 + 1 ) , C322) by POLYNOM1:def 10;
reconsider D224 = ( ( upm (C323 , C322) ) . ( ( mpu (C323 , C322) ) . C324 ) ) as (Polynomial of ( C323 + 1 ) , C322) by POLYNOM1:def 10;
reconsider D225 = ( ( mpu (C323 , C322) ) . C324 ) as (Polynomial of D222) by POLYNOM3:def 10;
L914:
now
let C325 being set;
assume L915: C325 in ( Bags ( C323 + 1 ) );
reconsider D226 = C325 as (Element of ( Bags ( C323 + 1 ) )) by L915;
reconsider D227 = ( D225 . ( D226 . C323 ) ) as (Polynomial of C323 , C322) by POLYNOM1:def 10;
L916: C323 < ( C323 + 1 ) by NAT_1:13;
reconsider D228 = ( D226 | C323 ) as (bag of C323) by L916 , L32;
L917: D226 = ( D228 bag_extend ( D226 . C323 ) ) by L77;
thus L918: ( D224 . C325 ) = ( D227 . D228 ) by L675
.= ( D223 . C325 ) by L917 , L820;
end;
thus L919: thesis by L914 , FUNCT_2:12;
end;
theorem
L920: (for B256 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial non  empty doubleLoopStr holds (for B257 being (Element of ( NAT )) holds (ex B258 being (Function of ( Polynom-Ring ( Polynom-Ring (B257 , B256) ) ) , ( Polynom-Ring (( B257 + 1 ) , B256) )) st B258 is  RingIsomorphism)))
proof
let C326 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr;
let C327 being (Element of ( NAT ));
set D229 = ( Polynom-Ring (( C327 + 1 ) , C326) );
set D230 = (the carrier of ( Polynom-Ring ( Polynom-Ring (C327 , C326) ) ));
set D231 = (the carrier of D229);
set D232 = ( upm (C327 , C326) );
L921: D232 is  RingHomomorphism by QUOFIELD:def 18;
L922: D232 is  RingMonomorphism by L921 , QUOFIELD:def 20;
L923:
now
let C328 being set;
assume L924: C328 in D231;
reconsider D233 = C328 as (Element of D231) by L924;
L925: (( dom D232 ) = D230 & ( D232 . ( ( mpu (C327 , C326) ) . D233 ) ) = D233) by L913 , FUNCT_2:def 1;
thus L926: C328 in ( rng D232 ) by L925 , FUNCT_1:def 3;
end;
L927: D231 c= ( rng D232 ) by L923 , TARSKI:def 3;
L928: ( rng D232 ) = D231 by L927 , XBOOLE_0:def 10;
L929: D232 is  RingEpimorphism by L928 , L921 , QUOFIELD:def 19;
L930: D232 is  RingIsomorphism by L929 , L922 , QUOFIELD:def 21;
thus L931: thesis by L930;
end;
begin
registration
let C329 being  Noetherian  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  empty doubleLoopStr;
::$N Hilbert Basis Theorem
cluster ( Polynom-Ring C329 ) ->  Noetherian;
coherence
proof
set D234 = (the carrier of C329);
set D235 = ( Polynom-Ring C329 );
set D236 = (the carrier of D235);
L932:
now
assume L933: D235 is non  Noetherian;
consider C330 being (Ideal of D235) such that L934: C330 is non  finitely_generated by L933 , IDEAL_1:def 26;
defpred S13[ set , set , set ] means ($2 is non  empty  finite non  empty  finite non  empty  finite non  empty  finite (Subset of C330) implies (ex B259 , B260 being non  empty (Subset of D236) st (B259 = $2 & B260 = ( C330 \ ( B259 -Ideal ) ) & (ex B261 being (Element of D236) st (B261 in ( minlen B260 ) & $3 = ( $2 \/ { B261 } ))))));
L935:
now
let C331 being (Element of ( NAT ));
let C332 being (Subset of D236);
per cases ;
suppose L936: (not C332 is non  empty  finite non  empty  finite non  empty  finite non  empty  finite (Subset of C330));

thus L937: (ex B262 being (Subset of D236) st S13[ C331 , C332 , B262 ]) by L936;
end;
suppose L938: C332 is non  empty  finite non  empty  finite non  empty  finite non  empty  finite (Subset of C330);

reconsider D237 = C332 as non  empty (Subset of D236) by L938;
set D238 = ( C330 \ ( D237 -Ideal ) );
L939:
now
assume L940: D238 = ( {} );
L941: C330 c= ( D237 -Ideal ) by L940 , XBOOLE_1:37;
L942: ( D237 -Ideal ) c= ( C330 -Ideal ) by L938 , IDEAL_1:57;
L943: ( D237 -Ideal ) c= C330 by L942 , IDEAL_1:44;
thus L944: contradiction by L943 , L934 , L938 , L941 , XBOOLE_0:def 10;
end;
reconsider D239 = D238 as non  empty (Subset of D236) by L939;
consider C333 being set such that L945: C333 in ( minlen D239 ) by XBOOLE_0:def 1;
L946: ( minlen D239 ) c= D236 by XBOOLE_1:1;
reconsider D240 = C333 as (Element of D236) by L946 , L945;
L947: S13[ C331 , C332 , ( D237 \/ { D240 } ) ] by L945;
thus L948: (ex B263 being (Subset of D236) st S13[ C331 , C332 , B263 ]) by L947;
end;
end;
consider C334 being (Function of ( NAT ) , ( bool D236 )) such that L950: (( C334 . ( 0 ) ) = { ( 0. D235 ) } & (for B264 being (Element of ( NAT )) holds S13[ B264 , ( C334 . B264 ) , ( C334 . ( B264 + 1 ) ) ])) from RECDEF_1:sch 2(L935);
defpred S14[ set , set ] means (ex B265 being (Element of ( NAT )) st (ex B266 , B267 being non  empty (Subset of D236) st (B266 = ( C334 . B265 ) & B267 = ( C330 \ ( B266 -Ideal ) ) & B265 = $1 & ( C334 . ( B265 + 1 ) ) = ( ( C334 . B265 ) \/ { $2 } ) & $2 in ( minlen B267 ))));
defpred S15[ (Element of ( NAT )) ] means ( C334 . $1 ) is non  empty  finite non  empty  finite non  empty  finite non  empty  finite (Subset of C330);
L951:
now
let C335 being (Element of ( NAT ));
assume L952: S15[ C335 ];
reconsider D241 = ( C334 . C335 ) as non  empty  finite (Subset of C330) by L952;
consider C336 , C337 being non  empty (Subset of D236) such that L953: C336 = D241 and L954: C337 = ( C330 \ ( C336 -Ideal ) ) and L955: (ex B268 being (Element of D236) st (B268 in ( minlen C337 ) & ( C334 . ( C335 + 1 ) ) = ( D241 \/ { B268 } ))) by L950;
consider C338 being (Element of D236) such that L956: C338 in ( minlen C337 ) and L957: ( C334 . ( C335 + 1 ) ) = ( D241 \/ { C338 } ) by L955;
L958: C338 in C330 by L954 , L956 , XBOOLE_0:def 5;
L959: { C338 } c= C330 by L958 , ZFMISC_1:31;
thus L960: S15[ ( C335 + 1 ) ] by L959 , L957 , XBOOLE_1:8;
end;
L961: ( C334 . ( 0 ) ) c= C330
proof
let C339 being set;
assume L962: C339 in ( C334 . ( 0 ) );
L963: C339 = ( 0. D235 ) by L962 , L950 , TARSKI:def 1;
thus L964: thesis by L963 , IDEAL_1:2;
end;
L965: S15[ ( 0 ) ] by L961 , L950;
L966: (for B269 being (Element of ( NAT )) holds S15[ B269 ]) from NAT_1:sch 1(L965 , L951);
L967:
now
let C340 being (Element of ( NAT ));
L968: (ex B270 , B271 being non  empty (Subset of D236) st (B270 = ( C334 . C340 ) & B271 = ( C330 \ ( B270 -Ideal ) ) & (ex B272 being (Element of D236) st (B272 in ( minlen B271 ) & ( C334 . ( C340 + 1 ) ) = ( ( C334 . C340 ) \/ { B272 } ))))) by L950 , L966;
thus L969: (ex B273 being (Element of D236) st S14[ C340 , B273 ]) by L968;
end;
consider C341 being (Function of ( NAT ) , D236) such that L970: (for B274 being (Element of ( NAT )) holds S14[ B274 , ( C341 . B274 ) ]) from FUNCT_2:sch 3(L967);
L971: (for B275 , B276 being (Element of ( NAT )) holds (B275 <= B276 implies ( C334 . B275 ) c= ( C334 . B276 )))
proof
let C342 , C343 being (Element of ( NAT ));
defpred S16[ (Element of ( NAT )) ] means ( C334 . C342 ) c= ( C334 . ( C342 + $1 ) );
assume L972: C342 <= C343;
consider C344 being Nat such that L973: C343 = ( C342 + C344 ) by L972 , NAT_1:10;
L974: (for B277 being (Element of ( NAT )) holds (S16[ B277 ] implies S16[ ( B277 + 1 ) ]))
proof
let C345 being (Element of ( NAT ));
L975: (ex B278 , B279 being non  empty (Subset of D236) st (B278 = ( C334 . ( C342 + C345 ) ) & B279 = ( C330 \ ( B278 -Ideal ) ) & (ex B280 being (Element of D236) st (B280 in ( minlen B279 ) & ( C334 . ( ( C342 + C345 ) + 1 ) ) = ( ( C334 . ( C342 + C345 ) ) \/ { B280 } ))))) by L950 , L966;
L976: ( C334 . ( C342 + C345 ) ) c= ( C334 . ( ( C342 + C345 ) + 1 ) ) by L975 , XBOOLE_1:7;
assume L977: ( C334 . C342 ) c= ( C334 . ( C342 + C345 ) );
thus L978: thesis by L977 , L976 , XBOOLE_1:1;
end;
L979: S16[ ( 0 ) ];
L980: (for B281 being (Element of ( NAT )) holds S16[ B281 ]) from NAT_1:sch 1(L979 , L974);
L981: C344 in ( NAT ) by ORDINAL1:def 12;
thus L982: thesis by L981 , L973 , L980;
end;
L983: (for B282 being (Element of ( NAT )) holds ( C341 . B282 ) <> ( 0. D235 ))
proof
let C346 being (Element of ( NAT ));
consider C347 being (Element of ( NAT )), C348 , C349 being non  empty (Subset of D236) such that L984: C348 = ( C334 . C347 ) and L985: C349 = ( C330 \ ( C348 -Ideal ) ) and L986: C347 = C346 and L987: ( C334 . ( C347 + 1 ) ) = ( ( C334 . C347 ) \/ { ( C341 . C346 ) } ) and L988: ( C341 . C346 ) in ( minlen C349 ) by L970;
L989: ( C334 . C347 ) c= ( C348 -Ideal ) by L984 , IDEAL_1:def 14;
L990: (not ( C341 . C346 ) in ( C334 . C347 )) by L989 , L985 , L988 , XBOOLE_0:def 5;
L991: (( C334 . ( 0 ) ) c= ( C334 . C347 ) & ( 0. D235 ) in ( C334 . ( 0 ) )) by L950 , L971 , TARSKI:def 1;
thus L992: thesis by L991 , L990;
end;
L993:
now
let C350 being (Element of ( NAT ));
let C351 being (Polynomial of C329);
assume L994: C351 = ( C341 . C350 );
L995: C351 <> ( 0. D235 ) by L994 , L983;
L996: C351 <> ( 0_. C329 ) by L995 , POLYNOM3:def 10;
L997: ( len C351 ) <> ( 0 ) by L996 , POLYNOM4:5;
L998: ( len C351 ) >= ( ( 0 ) + 1 ) by L997 , NAT_1:13;
thus L999: ( ( len C351 ) - 1 ) >= ( 0 ) by L998 , XREAL_1:19;
end;
defpred S17[ set , set ] means (ex B283 being (Element of ( NAT )) st (ex B284 being (Polynomial of C329) st (B283 = $1 & B284 = ( C341 . B283 ) & $2 = ( B284 . ( ( len B284 ) -' 1 ) ))));
L1000:
now
let C352 being (Element of ( NAT ));
reconsider D242 = ( C341 . C352 ) as (Polynomial of C329) by POLYNOM3:def 10;
L1001: ( D242 . ( ( len D242 ) -' 1 ) ) is (Element of D234);
thus L1002: (ex B285 being (Element of D234) st S17[ C352 , B285 ]) by L1001;
end;
consider C353 being (Function of ( NAT ) , D234) such that L1003: (for B286 being (Element of ( NAT )) holds S17[ B286 , ( C353 . B286 ) ]) from FUNCT_2:sch 3(L1000);
reconsider D243 = C353 as (sequence of C329);
L1004: (for B287 being non  empty (Subset of D234) holds (ex B288 being non  empty  finite (Subset of D234) st (B288 c= B287 & ( B288 -Ideal ) = ( B287 -Ideal )))) by IDEAL_1:96;
consider C354 being (Element of ( NAT )) such that L1005: ( D243 . ( C354 + 1 ) ) in ( ( rng ( D243 | ( C354 + 1 ) ) ) -Ideal ) by L1004 , IDEAL_1:97;
reconsider D244 = ( C341 . ( C354 + 1 ) ) as (Polynomial of C329) by POLYNOM3:def 10;
defpred S18[ set , set ] means ((ex B289 , B290 , B291 being (Element of D234) st ($1 = ( ( B289 * B290 ) * B291 ) & B290 in ( rng ( D243 | ( Segm ( C354 + 1 ) ) ) ))) implies (ex B292 , B293 , B294 being (Element of D236) st (ex B295 being (Polynomial of C329) st ($2 = B295 & B295 = ( ( B292 * B293 ) * B294 ) & $1 = ( B295 . ( ( len D244 ) -' 1 ) ) & ( len B295 ) <= ( len D244 ) & B293 in ( C334 . ( C354 + 1 ) )))));
L1006: (ex B296 being (Element of ( NAT )) st (ex B297 , B298 being non  empty (Subset of D236) st (B297 = ( C334 . B296 ) & B298 = ( C330 \ ( B297 -Ideal ) ) & B296 = ( C354 + 1 ) & ( C334 . ( B296 + 1 ) ) = ( ( C334 . B296 ) \/ { ( C341 . ( C354 + 1 ) ) } ) & ( C341 . ( C354 + 1 ) ) in ( minlen B298 )))) by L970;
L1007: (for B299 , B300 being (Element of ( NAT )) holds (for B301 , B302 being (Polynomial of C329) holds ((B299 <= B300 & B301 = ( C341 . B299 ) & B302 = ( C341 . B300 )) implies ( len B301 ) <= ( len B302 ))))
proof
let C355 , C356 being (Element of ( NAT ));
let C357 , C358 being (Polynomial of C329);
assume that
L1008: C355 <= C356
and
L1009: C357 = ( C341 . C355 )
and
L1010: C358 = ( C341 . C356 );
consider C359 being Nat such that L1011: C356 = ( C355 + C359 ) by L1008 , NAT_1:10;
defpred S19[ (Element of ( NAT )) ] means (for B303 being (Polynomial of C329) holds (B303 = ( C341 . ( C355 + $1 ) ) implies ( len C357 ) <= ( len B303 )));
L1012:
now
let C360 being (Element of ( NAT ));
assume L1013: S19[ C360 ];
L1014:
now
reconsider D245 = ( C341 . ( C355 + C360 ) ) as (Polynomial of C329) by POLYNOM3:def 10;
let C361 being (Polynomial of C329);
L1015: ( len C357 ) <= ( len D245 ) by L1013;
consider C362 being (Element of ( NAT )), C363 , C364 being non  empty (Subset of D236) such that L1016: C363 = ( C334 . C362 ) and L1017: C364 = ( C330 \ ( C363 -Ideal ) ) and L1018: C362 = ( C355 + C360 ) and L1019: ( C334 . ( C362 + 1 ) ) = ( ( C334 . C362 ) \/ { ( C341 . ( C355 + C360 ) ) } ) and L1020: ( C341 . ( C355 + C360 ) ) in ( minlen C364 ) by L970;
consider C365 being (Element of ( NAT )), C366 , C367 being non  empty (Subset of D236) such that L1021: C366 = ( C334 . C365 ) and L1022: C367 = ( C330 \ ( C366 -Ideal ) ) and L1023: C365 = ( C355 + ( C360 + 1 ) ) and L1024: ( C334 . ( C365 + 1 ) ) = ( ( C334 . C365 ) \/ { ( C341 . ( C355 + ( C360 + 1 ) ) ) } ) and L1025: ( C341 . ( C355 + ( C360 + 1 ) ) ) in ( minlen C367 ) by L970;
L1026: ( C341 . ( C355 + ( C360 + 1 ) ) ) in C330 by L1022 , L1025 , XBOOLE_0:def 5;
L1027: ( C355 + ( C360 + 1 ) ) = ( ( C355 + C360 ) + 1 );
L1028: ( C355 + C360 ) < ( C355 + ( C360 + 1 ) ) by L1027 , NAT_1:13;
L1029: ( C363 -Ideal ) c= ( C366 -Ideal ) by L1028 , L971 , L1016 , L1018 , L1021 , L1023 , IDEAL_1:57;
L1030: (not ( C341 . ( C355 + ( C360 + 1 ) ) ) in ( C363 -Ideal )) by L1029 , L1022 , L1025 , XBOOLE_0:def 5;
L1031: ( C341 . ( C355 + ( C360 + 1 ) ) ) in C364 by L1030 , L1017 , L1026 , XBOOLE_0:def 5;
assume L1032: C361 = ( C341 . ( C355 + ( C360 + 1 ) ) );
L1033: ( len D245 ) <= ( len C361 ) by L1032 , L1020 , L1031 , L238;
thus L1034: ( len C357 ) <= ( len C361 ) by L1033 , L1015 , XXREAL_0:2;
end;
thus L1035: S19[ ( C360 + 1 ) ] by L1014;
end;
L1036: S19[ ( 0 ) ] by L1009;
L1037: (for B304 being (Element of ( NAT )) holds S19[ B304 ]) from NAT_1:sch 1(L1036 , L1012);
L1038: C359 in ( NAT ) by ORDINAL1:def 12;
thus L1039: thesis by L1038 , L1010 , L1011 , L1037;
end;
L1040: (for B305 being set holds (B305 in D234 implies (ex B306 being set st (B306 in D236 & S18[ B305 , B306 ]))))
proof
let C368 being set;
assume L1041: C368 in D234;
per cases ;
suppose L1042: (ex B307 , B308 , B309 being (Element of D234) st (C368 = ( ( B307 * B308 ) * B309 ) & B308 in ( rng ( D243 | ( Segm ( C354 + 1 ) ) ) )));

consider C369 , C370 , C371 being (Element of D234) such that L1043: C368 = ( ( C369 * C370 ) * C371 ) and L1044: C370 in ( rng ( D243 | ( Segm ( C354 + 1 ) ) ) ) by L1042;
consider C372 being set such that L1045: C372 in ( dom ( D243 | ( Segm ( C354 + 1 ) ) ) ) and L1046: C370 = ( ( D243 | ( Segm ( C354 + 1 ) ) ) . C372 ) by L1044 , FUNCT_1:def 3;
set D246 = C371;
set D247 = C369;
set D248 = ( monomial (D246 , ( 0 )) );
L1047: ( ( len D244 ) -' 1 ) = ( ( ( len D244 ) -' 1 ) + ( 0 ) );
reconsider D249 = C372 as (Element of ( NAT )) by L1045;
set D250 = ( C341 . D249 );
reconsider D251 = D250 as (Polynomial of C329) by POLYNOM3:def 10;
set D252 = ( monomial (D247 , ( ( len D244 ) -' ( len D251 ) )) );
L1048: ( dom ( D243 | ( Segm ( C354 + 1 ) ) ) ) = ( ( dom D243 ) /\ ( Segm ( C354 + 1 ) ) ) by RELAT_1:61
.= ( ( NAT ) /\ ( Segm ( C354 + 1 ) ) ) by FUNCT_2:def 1
.= ( Segm ( C354 + 1 ) ) by XBOOLE_1:28;
L1049: D249 < ( C354 + 1 ) by L1048 , L1045 , NAT_1:44;
L1050: ( len D251 ) <= ( len D244 ) by L1049 , L1007;
L1051: ( ( len D251 ) - ( len D251 ) ) <= ( ( len D244 ) - ( len D251 ) ) by L1050 , XREAL_1:9;
L1052: ( ( len D244 ) -' ( len D251 ) ) = ( ( len D244 ) - ( len D251 ) ) by L1051 , XREAL_0:def 2;
L1053: ( len D252 ) <= ( ( ( len D244 ) - ( len D251 ) ) + 1 ) by L1052 , L269;
L1054: ( ( len D252 ) + ( ( len D251 ) - 1 ) ) <= ( ( ( len D244 ) - ( ( len D251 ) - 1 ) ) + ( ( len D251 ) - 1 ) ) by L1053 , XREAL_1:6;
L1055: ( len ( D252 *' D251 ) ) <= ( ( ( len D252 ) + ( len D251 ) ) -' 1 ) by L370;
L1056: ( ( len D251 ) - 1 ) >= ( 0 ) by L993;
L1057: ( ( 0 ) + ( 0 ) ) <= ( ( ( len D251 ) - 1 ) + ( len D252 ) ) by L1056;
L1058: ( len ( D252 *' D251 ) ) <= ( ( ( len D252 ) + ( len D251 ) ) - 1 ) by L1057 , L1055 , XREAL_0:def 2;
L1059: ( len ( D252 *' D251 ) ) <= ( len D244 ) by L1058 , L1054 , XXREAL_0:2;
L1060: ( ( len D244 ) - 1 ) >= ( 0 ) by L993;
L1061: ( ( len D244 ) -' 1 ) = ( ( ( len D244 ) - ( len D251 ) ) + ( ( len D251 ) - 1 ) ) by L1060 , XREAL_0:def 2
.= ( ( ( len D251 ) -' 1 ) + ( ( len D244 ) -' ( len D251 ) ) ) by L1052 , L1056 , XREAL_0:def 2;
reconsider D253 = D252 , D254 = D248 as (Element of D236) by POLYNOM3:def 10;
set D255 = ( ( D253 * D250 ) * D254 );
L1062: ( D253 * D250 ) = ( D252 *' D251 ) by POLYNOM3:def 10;
L1063: D255 = ( ( D252 *' D251 ) *' D248 ) by L1062 , POLYNOM3:def 10;
reconsider D256 = D255 as (Polynomial of C329) by POLYNOM3:def 10;
L1064: (ex B310 being (Element of ( NAT )) st (ex B311 being (Polynomial of C329) st (B310 = D249 & B311 = ( C341 . B310 ) & ( D243 . D249 ) = ( B311 . ( ( len B311 ) -' 1 ) )))) by L1003;
L1065: C370 = ( D243 . D249 ) by L1045 , L1046 , FUNCT_1:47;
L1066: ( ( D252 *' D251 ) . ( ( len D244 ) -' 1 ) ) = ( D247 * C370 ) by L1065 , L1064 , L1061 , L294;
L1067: ( ( D247 * C370 ) * D246 ) = ( D256 . ( ( len D244 ) -' 1 ) ) by L1066 , L1063 , L1047 , L330;
L1068: (ex B312 being (Element of ( NAT )) st (ex B313 , B314 being non  empty (Subset of D236) st (B313 = ( C334 . B312 ) & B314 = ( C330 \ ( B313 -Ideal ) ) & B312 = D249 & ( C334 . ( B312 + 1 ) ) = ( ( C334 . B312 ) \/ { ( C341 . D249 ) } ) & ( C341 . D249 ) in ( minlen B314 )))) by L970;
L1069: { D250 } c= ( C334 . ( D249 + 1 ) ) by L1068 , XBOOLE_1:7;
L1070: D250 in ( C334 . ( D249 + 1 ) ) by L1069 , ZFMISC_1:31;
L1071: ( len D248 ) <= ( ( 0 ) + 1 ) by L269;
L1072: ( ( len ( D252 *' D251 ) ) + ( len D248 ) ) <= ( ( len D244 ) + 1 ) by L1071 , L1059 , XREAL_1:7;
L1073: ( ( ( len ( D252 *' D251 ) ) + ( len D248 ) ) -' 1 ) <= ( ( ( len D244 ) + 1 ) -' 1 ) by L1072 , NAT_D:42;
L1074: ( len ( ( D252 *' D251 ) *' D248 ) ) <= ( ( ( len ( D252 *' D251 ) ) + ( len D248 ) ) -' 1 ) by L370;
L1075: ( len ( ( D252 *' D251 ) *' D248 ) ) <= ( ( ( len D244 ) + 1 ) -' 1 ) by L1074 , L1073 , XXREAL_0:2;
L1076: ( len ( ( D252 *' D251 ) *' D248 ) ) <= ( ( ( len D244 ) + 1 ) - 1 ) by L1075 , XREAL_0:def 2;
L1077: ( len D256 ) <= ( ( len D244 ) + ( 0 ) ) by L1076 , L1062 , POLYNOM3:def 10;
L1078: ( D249 + 1 ) <= ( C354 + 1 ) by L1049 , NAT_1:13;
L1079: ( C334 . ( D249 + 1 ) ) c= ( C334 . ( C354 + 1 ) ) by L1078 , L971;
thus L1080: thesis by L1079 , L1043 , L1067 , L1077 , L1070;
end;
suppose L1081: (not (ex B315 , B316 , B317 being (Element of D234) st (C368 = ( ( B315 * B316 ) * B317 ) & B316 in ( rng ( D243 | ( Segm ( C354 + 1 ) ) ) ))));

thus L1082: thesis by L1081;
end;
end;
consider C373 being (Function of D234 , D236) such that L1084: (for B318 being set holds (B318 in D234 implies S18[ B318 , ( C373 . B318 ) ])) from FUNCT_2:sch 1(L1040);
reconsider D257 = ( C334 . ( C354 + 1 ) ) as non  empty (Subset of D236) by L966;
set D258 = ( rng ( D243 | ( Segm ( C354 + 1 ) ) ) );
consider C374 being (LinearCombination of ( rng ( D243 | ( Segm ( C354 + 1 ) ) ) )) such that L1085: ( D243 . ( C354 + 1 ) ) = ( Sum C374 ) by L1005 , IDEAL_1:60;
L1086: (for B319 being (LinearCombination of D258) holds (ex B320 being (LinearCombination of D257) st (B320 = ( C373 * B319 ) & ( len B319 ) = ( len B320 ))))
proof
let C375 being (LinearCombination of D258);
set D259 = ( C373 * C375 );
L1087: ( dom C373 ) = D234 by FUNCT_2:def 1;
L1088: ( rng C375 ) c= ( dom C373 ) by L1087;
L1089: ( dom C375 ) = ( dom ( C373 * C375 ) ) by L1088 , RELAT_1:27;
L1090: ( len C375 ) = ( len D259 ) by L1089 , FINSEQ_3:29;
L1091: D259 is (LinearCombination of D257)
proof
let C376 being set;
assume that
L1092: C376 in ( dom D259 );
consider C377 , C378 being (Element of C329), C379 being (Element of D258) such that L1093: ( C375 /. C376 ) = ( ( C377 * C379 ) * C378 ) by L1089 , L1092 , IDEAL_1:def 8;
L1094: ( C375 /. C376 ) = ( C375 . C376 ) by L1089 , L1092 , PARTFUN1:def 6;
consider C380 , C381 , C382 being (Element of D236), C383 being (Polynomial of C329) such that L1095: (( C373 . ( C375 /. C376 ) ) = C383 & C383 = ( ( C380 * C381 ) * C382 )) and L1096: ( ( C377 * C379 ) * C378 ) = ( C383 . ( ( len D244 ) -' 1 ) ) and L1097: ( len C383 ) <= ( len D244 ) and L1098: C381 in ( C334 . ( C354 + 1 ) ) by L1084 , L1093;
reconsider D260 = C381 as (Element of D257) by L1098;
reconsider D261 = C380 , D262 = C382 as (Element of D235);
L1099: ( D259 /. C376 ) = ( ( C373 * C375 ) . C376 ) by L1092 , PARTFUN1:def 6
.= ( ( D261 * D260 ) * D262 ) by L1089 , L1092 , L1094 , L1095 , FUNCT_1:13;
thus L1100: (ex B321 , B322 being (Element of D235) st (ex B323 being (Element of D257) st ( D259 /. C376 ) = ( ( B321 * B323 ) * B322 ))) by L1099;
end;
reconsider D263 = D259 as (LinearCombination of D257) by L1091;
L1101: D263 = D263;
thus L1102: thesis by L1101 , L1090;
end;
L1103: (for B324 being (LinearCombination of D258) holds (ex B325 being (LinearCombination of D257) st (ex B326 being (Polynomial of C329) st (B325 = ( C373 * B324 ) & B326 = ( Sum B325 ) & ( B326 . ( ( len D244 ) -' 1 ) ) = ( Sum B324 ) & ( len B326 ) <= ( len D244 )))))
proof
let C384 being (LinearCombination of D258);
defpred S20[ (Element of ( NAT )) ] means (for B327 being (LinearCombination of D258) holds (( len B327 ) <= $1 implies (ex B328 being (LinearCombination of D257) st (ex B329 being (Polynomial of C329) st (B328 = ( C373 * B327 ) & B329 = ( Sum B328 ) & ( B329 . ( ( len D244 ) -' 1 ) ) = ( Sum B327 ) & ( len B329 ) <= ( len D244 ))))));
L1104: (ex B330 being (Element of ( NAT )) st B330 = ( len C384 ));
L1105: (for B331 being (Element of ( NAT )) holds (S20[ B331 ] implies S20[ ( B331 + 1 ) ]))
proof
let C385 being (Element of ( NAT ));
assume L1106: S20[ C385 ];
thus L1107: S20[ ( C385 + 1 ) ]
proof
let C386 being (LinearCombination of D258);
assume L1108: ( len C386 ) <= ( C385 + 1 );
per cases ;
suppose L1109: ( len C386 ) <= C385;

thus L1110: thesis by L1109 , L1106;
end;
suppose L1111: ( len C386 ) > C385;

L1112: ( len C386 ) >= ( C385 + 1 ) by L1111 , NAT_1:13;
L1113: ( len C386 ) = ( C385 + 1 ) by L1112 , L1108 , XXREAL_0:1;
thus L1114: thesis
proof
per cases ;
suppose L1115: C385 = ( 0 );

L1116: ( dom C386 ) = { 1 } by L1115 , L1113 , FINSEQ_1:2 , FINSEQ_1:def 3;
L1117: 1 in ( dom C386 ) by L1116 , TARSKI:def 1;
consider C387 , C388 being (Element of C329), C389 being (Element of D258) such that L1118: ( C386 /. 1 ) = ( ( C387 * C389 ) * C388 ) by L1117 , IDEAL_1:def 8;
L1119: ( C386 . 1 ) = ( C386 /. 1 ) by L1117 , PARTFUN1:def 6;
consider C390 , C391 , C392 being (Element of D236), C393 being (Polynomial of C329) such that L1120: ( C373 . ( C386 . 1 ) ) = C393 and L1121: C393 = ( ( C390 * C391 ) * C392 ) and L1122: ( ( C387 * C389 ) * C388 ) = ( C393 . ( ( len D244 ) -' 1 ) ) and L1123: ( len C393 ) <= ( len D244 ) and L1124: C391 in ( C334 . ( C354 + 1 ) ) by L1119 , L1084 , L1118;
L1125: C386 = <* ( C386 . 1 ) *> by L1113 , L1115 , FINSEQ_1:40;
L1126: ( Sum C386 ) = ( C393 . ( ( len D244 ) -' 1 ) ) by L1125 , L1118 , L1119 , L1122 , RLVECT_1:44;
consider C394 being (LinearCombination of D257) such that L1127: C394 = ( C373 * C386 ) and L1128: ( len C394 ) = ( len C386 ) by L1086;
L1129: C394 = <* ( C373 . ( ( C387 * C389 ) * C388 ) ) *> by L1125 , L1118 , L1119 , L1127 , FINSEQ_2:35;
L1130: ( Sum C394 ) = C393 by L1129 , L1118 , L1119 , L1120 , RLVECT_1:44;
thus L1131: thesis by L1130 , L1123 , L1127 , L1126;
end;
suppose L1132: C385 > ( 0 );

consider C395 being (LinearCombination of D257) such that L1133: C395 = ( C373 * C386 ) and L1134: ( len C395 ) = ( len C386 ) by L1086;
L1135: C386 is non  empty by L1111;
consider C396 being (LinearCombination of D258), C397 being (Element of D234) such that L1136: C386 = ( C396 ^ <* C397 *> ) and L1137: <* C397 *> is (LinearCombination of D258) by L1135 , IDEAL_1:32;
L1138: ( len <* C397 *> ) = ( ( 0 ) + 1 ) by FINSEQ_1:39;
L1139: ( len <* C397 *> ) <= C385 by L1138 , L1132 , NAT_1:13;
consider C398 being (LinearCombination of D257), C399 being (Polynomial of C329) such that L1140: C398 = ( C373 * <* C397 *> ) and L1141: C399 = ( Sum C398 ) and L1142: ( C399 . ( ( len D244 ) -' 1 ) ) = ( Sum <* C397 *> ) and L1143: ( len C399 ) <= ( len D244 ) by L1139 , L1106 , L1137;
L1144: ( len C386 ) = ( ( len C396 ) + ( len <* C397 *> ) ) by L1136 , FINSEQ_1:22
.= ( ( len C396 ) + 1 ) by FINSEQ_1:39;
consider C400 being (LinearCombination of D257), C401 being (Polynomial of C329) such that L1145: C400 = ( C373 * C396 ) and L1146: C401 = ( Sum C400 ) and L1147: ( C401 . ( ( len D244 ) -' 1 ) ) = ( Sum C396 ) and L1148: ( len C401 ) <= ( len D244 ) by L1144 , L1106 , L1113;
set D264 = ( C401 + C399 );
L1149: ( Sum C386 ) = ( ( Sum C396 ) + C397 ) by L1136 , FVSUM_1:71
.= ( ( C401 . ( ( len D244 ) -' 1 ) ) + ( C399 . ( ( len D244 ) -' 1 ) ) ) by L1147 , L1142 , RLVECT_1:44
.= ( D264 . ( ( len D244 ) -' 1 ) ) by NORMSP_1:def 2;
L1150:
now
per cases ;
suppose L1151: ( len C401 ) < ( len C399 );

L1152: ( len D264 ) <= ( len C399 ) by L1151 , POLYNOM4:6;
thus L1153: ( len D264 ) <= ( len D244 ) by L1152 , L1143 , XXREAL_0:2;
end;
suppose L1154: ( len C401 ) >= ( len C399 );

L1155: ( len D264 ) <= ( len C401 ) by L1154 , POLYNOM4:6;
thus L1156: ( len D264 ) <= ( len D244 ) by L1155 , L1148 , XXREAL_0:2;
end;
end;
L1158: ( dom C373 ) = D234 by FUNCT_2:def 1;
L1159: ( ( rng C396 ) \/ ( rng <* C397 *> ) ) c= ( dom C373 ) by L1158;
L1160: (ex B332 , B333 being FinSequence st (B332 = ( C373 * C396 ) & B333 = ( C373 * <* C397 *> ) & ( C373 * ( C396 ^ <* C397 *> ) ) = ( B332 ^ B333 ))) by L1159 , L1;
L1161: ( Sum C395 ) = ( ( Sum C400 ) + ( Sum C398 ) ) by L1160 , L1136 , L1145 , L1140 , L1133 , RLVECT_1:41
.= D264 by L1146 , L1141 , POLYNOM3:def 10;
thus L1162: thesis by L1161 , L1133 , L1149 , L1150;
end;
end;

end;
end;

end;
L1108: S20[ ( 0 ) ]
proof
let C402 being (LinearCombination of D258);
assume L1109: ( len C402 ) <= ( 0 );
L1110: C402 = ( <*> D234 ) by L1109;
consider C403 being (LinearCombination of D257) such that L1111: C403 = ( C373 * C402 ) and L1112: ( len C402 ) = ( len C403 ) by L1086;
take C403;
take D265 = ( 0_. C329 );
thus L1113: C403 = ( C373 * C402 ) by L1111;
L1114: C403 = ( <*> D236 ) by L1109 , L1112;
L1115: ( Sum C403 ) = ( 0. D235 ) by L1114 , RLVECT_1:43
.= D265 by POLYNOM3:def 10;
thus L1116: D265 = ( Sum C403 ) by L1115;
thus L1117: ( D265 . ( ( len D244 ) -' 1 ) ) = ( 0. C329 ) by FUNCOP_1:7
.= ( Sum C402 ) by L1110 , RLVECT_1:43;
thus L1118: thesis by POLYNOM4:3;
end;
L1119: (for B334 being (Element of ( NAT )) holds S20[ B334 ]) from NAT_1:sch 1(L1108 , L1105);
thus L1120: thesis by L1119 , L1104;
end;
consider C404 being (LinearCombination of D257), C405 being (Polynomial of C329) such that L1121: C404 = ( C373 * C374 ) and L1122: C405 = ( Sum C404 ) and L1123: ( C405 . ( ( len D244 ) -' 1 ) ) = ( Sum C374 ) and L1124: ( len C405 ) <= ( len D244 ) by L1103;
L1125: C405 in ( D257 -Ideal ) by L1122 , IDEAL_1:60;
set D266 = ( D244 - C405 );
L1126:
now
L1127: (ex B335 being (Element of ( NAT )) st (ex B336 being (Polynomial of C329) st (B335 = ( C354 + 1 ) & B336 = ( C341 . B335 ) & ( D243 . ( C354 + 1 ) ) = ( B336 . ( ( len B336 ) -' 1 ) )))) by L1003;
L1128: ( D266 . ( ( len D244 ) -' 1 ) ) = ( ( D244 . ( ( len D244 ) -' 1 ) ) - ( D244 . ( ( len D244 ) -' 1 ) ) ) by L1127 , L1085 , L1123 , POLYNOM3:27
.= ( 0. C329 ) by RLVECT_1:15;
L1129: ( ( len D244 ) - 1 ) >= ( 0 ) by L993;
L1130: ( ( ( len D244 ) -' 1 ) + 1 ) = ( ( ( len D244 ) - 1 ) + 1 ) by L1129 , XREAL_0:def 2
.= ( len D244 );
assume L1131: ( len D266 ) = ( len D244 );
thus L1132: contradiction by L1131 , L1130 , L1128 , ALGSEQ_1:10;
end;
L1133: ( D266 + C405 ) = ( D244 + ( C405 + ( - C405 ) ) ) by POLYNOM3:26
.= ( D244 + ( C405 - C405 ) )
.= ( D244 + ( 0_. C329 ) ) by POLYNOM3:29
.= D244 by POLYNOM3:28;
L1134:
now
reconsider D267 = C405 as (Element of D236) by POLYNOM3:def 10;
assume L1135: D266 in ( D257 -Ideal );
reconsider D268 = D266 as (Element of D236) by POLYNOM3:def 10;
L1136: ( C341 . ( C354 + 1 ) ) = ( D268 + D267 ) by L1133 , POLYNOM3:def 10;
L1137: D244 in ( D257 -Ideal ) by L1136 , L1125 , L1135 , IDEAL_1:def 1;
thus L1138: contradiction by L1137 , L1006 , XBOOLE_0:def 5;
end;
L1139: ( len ( - C405 ) ) <= ( len D244 ) by L1124 , POLYNOM4:8;
L1140: ( len D266 ) <= ( len D244 ) by L1139 , POLYNOM4:6;
L1141: ( len D266 ) < ( len D244 ) by L1140 , L1126 , XXREAL_0:1;
L1142: D266 in C330
proof
reconsider D269 = D266 as (Element of D236) by POLYNOM3:def 10;
reconsider D270 = C405 as (Element of D236) by POLYNOM3:def 10;
L1143: D257 is (Subset of C330) by L966;
L1144: ( D257 -Ideal ) c= ( C330 -Ideal ) by L1143 , IDEAL_1:57;
L1145: ( D257 -Ideal ) c= C330 by L1144 , IDEAL_1:44;
L1146: (( C341 . ( C354 + 1 ) ) in C330 & D269 = ( ( C341 . ( C354 + 1 ) ) - D270 )) by L1006 , L209 , XBOOLE_0:def 5;
thus L1147: thesis by L1146 , L1125 , L1145 , IDEAL_1:15;
end;
L1148: D266 in ( C330 \ ( D257 -Ideal ) ) by L1142 , L1134 , XBOOLE_0:def 5;
thus L1149: contradiction by L1148 , L1141 , L1006 , L238;
end;
thus L1150: thesis by L932;
end;
end;
theorem
L1152: (for B337 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr holds (B337 is  Noetherian implies (for B338 being (Element of ( NAT )) holds ( Polynom-Ring (B338 , B337) ) is  Noetherian)))
proof
let C406 being  Abelian  add-associative  right_zeroed  right_complementable  associative  distributive  well-unital  commutative non  trivial doubleLoopStr;
assume L1153: C406 is  Noetherian;
defpred S21[ (Element of ( NAT )) ] means ( Polynom-Ring ($1 , C406) ) is  Noetherian;
L1154:
now
let C407 being (Element of ( NAT ));
assume that
L1155: S21[ C407 ];
L1156: (ex B339 being (Function of ( Polynom-Ring ( Polynom-Ring (C407 , C406) ) ) , ( Polynom-Ring (( C407 + 1 ) , C406) )) st B339 is  RingIsomorphism) by L920;
thus L1157: S21[ ( C407 + 1 ) ] by L1156 , L1155 , L537;
end;
L1158: (ex B340 being (Function of C406 , ( Polynom-Ring (( 0 ) , C406) )) st B340 is  RingIsomorphism) by L554;
L1159: S21[ ( 0 ) ] by L1158 , L1153 , L537;
thus L1160: (for B341 being (Element of ( NAT )) holds S21[ B341 ]) from NAT_1:sch 1(L1159 , L1154);
end;
theorem
L1161: (for B342 being Field holds B342 is  Noetherian)
proof
let C408 being Field;
let C409 being (Ideal of C408);
per cases  by IDEAL_1:22;
suppose L1162: C409 = { ( 0. C408 ) };

reconsider D271 = { ( 0. C408 ) } as  finite non  empty (Subset of C408);
L1163: { ( 0. C408 ) } = ( D271 -Ideal ) by IDEAL_1:47;
thus L1164: thesis by L1163 , L1162;
end;
suppose L1165: C409 = (the carrier of C408);

reconsider D272 = { ( 1_ C408 ) } as  finite non  empty (Subset of C408);
L1166: (the carrier of C408) = ( D272 -Ideal ) by IDEAL_1:51;
thus L1167: thesis by L1166 , L1165;
end;
end;
theorem
L1169: (for B343 being Field holds (for B344 being (Element of ( NAT )) holds ( Polynom-Ring (B344 , B343) ) is  Noetherian))
proof
let C410 being Field;
let C411 being (Element of ( NAT ));
L1170: C410 is  Noetherian by L1161;
thus L1171: thesis by L1170 , L1152;
end;
theorem
L1172: (for B345 being  Abelian  right_zeroed  add-associative  right_complementable  well-unital  distributive  associative  commutative non  trivial doubleLoopStr holds (for B346 being  infinite Ordinal holds ( Polynom-Ring (B346 , B345) ) is non  Noetherian))
proof
deffunc H5(set) = $1;
let C412 being  Abelian  right_zeroed  add-associative  right_complementable  well-unital  distributive  associative  commutative non  trivial doubleLoopStr;
let C413 being  infinite Ordinal;
assume that
L1173: ( Polynom-Ring (C413 , C412) ) is  Noetherian;
reconsider D273 = ( C413 --> ( 0. C412 ) ) as (Function of C413 , (the carrier of C412));
deffunc H6((Element of C413)) = ( 1_1 ($1 , C412) );
set D274 = (the carrier of C412);
L1174: (for B347 , B348 being (Element of C413) holds (H6(B347) = H6(B348) implies B347 = B348)) by L194;
L1175: D274 c= D274;
reconsider D275 = (the carrier of C412) as non  empty (Subset of D274) by L1175;
set D276 = { ( 1_1 (B349 , C412) ) where B349 is (Element of C413) : B349 in ( NAT ) };
set D277 = (the carrier of ( Polynom-Ring (C413 , C412) ));
L1176: ( NAT ) c= C413 by CARD_3:85;
L1177: ( 0 ) in ( NAT );
reconsider D278 = ( 0 ) as (Element of C413) by L1177 , L1176;
L1178: D276 c= D277
proof
let C414 being set;
assume L1179: C414 in D276;
L1180: (ex B350 being (Element of C413) st (C414 = ( 1_1 (B350 , C412) ) & B350 in ( NAT ))) by L1179;
thus L1181: thesis by L1180 , POLYNOM1:def 10;
end;
L1182: ( 1_1 (D278 , C412) ) in D276;
reconsider D279 = D276 as non  empty (Subset of D277) by L1182 , L1178;
consider C415 being non  empty  finite (Subset of D277) such that L1183: C415 c= D279 and L1184: ( C415 -Ideal ) = ( D279 -Ideal ) by L1173 , IDEAL_1:96;
set D280 = { H5(B351) where B351 is (Element of C413) : H6(B351) in C415 };
L1185: C415 is  finite;
L1186: D280 is  finite from FUNCT_7:sch 2(L1185 , L1174);
L1187: D280 c= ( NAT )
proof
let C416 being set;
assume L1188: C416 in D280;
consider C417 being (Element of C413) such that L1189: C416 = C417 and L1190: ( 1_1 (C417 , C412) ) in C415 by L1188;
L1191: ( 1_1 (C417 , C412) ) in D279 by L1183 , L1190;
L1192: (ex B352 being (Element of C413) st (( 1_1 (C417 , C412) ) = ( 1_1 (B352 , C412) ) & B352 in ( NAT ))) by L1191;
thus L1193: thesis by L1192 , L1189 , L194;
end;
set D281 = the (Element of C415);
L1194: D281 in C415;
L1195: D281 in D279 by L1194 , L1183;
consider C418 being (Element of C413) such that L1196: D281 = ( 1_1 (C418 , C412) ) and L1197: C418 in ( NAT ) by L1195;
reconsider D282 = C418 as (Element of ( NAT )) by L1197;
L1198: D282 in D280 by L1196;
reconsider D283 = D280 as non  empty  finite (Subset of ( NAT )) by L1198 , L1186 , L1187;
reconsider D284 = ( max D283 ) as (Element of ( NAT )) by ORDINAL1:def 12;
reconsider D285 = ( D284 + 1 ) as (Element of ( NAT ));
L1199: D285 in ( NAT );
reconsider D286 = D285 as (Element of C413) by L1199 , L1176;
L1200: (( 1_1 (D286 , C412) ) in D279 & D279 c= ( D279 -Ideal )) by IDEAL_1:def 14;
consider C419 being (LinearCombination of C415) such that L1201: ( 1_1 (D286 , C412) ) = ( Sum C419 ) by L1200 , L1184 , IDEAL_1:60;
reconsider D287 = ( D273 +* (D286 , ( 1_ C412 )) ) as (Function of C413 , C412);
consider C420 being (FinSequence of [: D277 , D277 , D277 :]) such that L1202: C420 represents C419 by IDEAL_1:35;
set D288 = ( Polynom-Evaluation (C413 , C412 , D287) );
deffunc H7(Nat) = ( ( ( D288 . ( ( C420 /. $1 ) `1_3 ) ) * ( D288 . ( ( C420 /. $1 ) `2_3 ) ) ) * ( D288 . ( ( C420 /. $1 ) `3_3 ) ) );
consider C421 being (FinSequence of (the carrier of C412)) such that L1203: ( len C421 ) = ( len C419 ) and L1204: (for B353 being Nat holds (B353 in ( dom C421 ) implies ( C421 . B353 ) = H7(B353))) from FINSEQ_2:sch 1;
L1205:
now
let C422 being set;
assume L1206: C422 in ( dom C421 );
reconsider D289 = C422 as (Element of ( NAT )) by L1206;
reconsider D290 = ( D288 . ( ( C420 /. D289 ) `2_3 ) ) as (Element of D275);
reconsider D291 = ( D288 . ( ( C420 /. D289 ) `1_3 ) ) , D292 = ( D288 . ( ( C420 /. D289 ) `3_3 ) ) as (Element of C412);
take D293 = D291;
take D294 = D292;
take D295 = D290;
thus L1207: ( C421 /. C422 ) = ( C421 . D289 ) by L1206 , PARTFUN1:def 6
.= ( ( D293 * D295 ) * D294 ) by L1204 , L1206;
end;
reconsider D296 = C421 as (LinearCombination of D275) by L1205 , IDEAL_1:def 8;
L1208:
now
let C423 being (Element of ( NAT ));
L1209:
now
assume L1210: D286 in D283;
L1211: ( ( max D283 ) + 1 ) <= ( max D283 ) by L1210 , XXREAL_2:def 8;
thus L1212: contradiction by L1211 , XREAL_1:29;
end;
assume L1213: C423 in ( dom D296 );
L1214: C423 in ( dom C419 ) by L1213 , L1203 , FINSEQ_3:29;
reconsider D297 = ( ( C420 /. C423 ) `2_3 ) as (Element of C415) by L1214 , L1202 , IDEAL_1:def 11;
L1215: D297 in C415;
L1216: D297 in D279 by L1215 , L1183;
consider C424 being (Element of C413) such that L1217: D297 = ( 1_1 (C424 , C412) ) and L1218: C424 in ( NAT ) by L1216;
L1219: C424 in D283 by L1217;
L1220: ( D287 . C424 ) = ( ( C413 --> ( 0. C412 ) ) . C424 ) by L1219 , L1209 , FUNCT_7:32
.= ( 0. C412 ) by FUNCOP_1:7;
L1221: ( Support ( 1_1 (C424 , C412) ) ) = { ( UnitBag C424 ) } by L177;
L1222: ( D288 . ( 1_1 (C424 , C412) ) ) = ( eval (( 1_1 (C424 , C412) ) , D287) ) by POLYNOM2:def 5
.= ( ( ( 1_1 (C424 , C412) ) . ( UnitBag C424 ) ) * ( eval (( UnitBag C424 ) , D287) ) ) by L1221 , POLYNOM2:19
.= ( ( 1_ C412 ) * ( eval (( UnitBag C424 ) , D287) ) ) by L172
.= ( ( 1_ C412 ) * ( D287 . C424 ) ) by L168
.= ( 0. C412 ) by L1220 , VECTSP_1:6;
thus L1223: ( D296 . C423 ) = ( ( ( D288 . ( ( C420 /. C423 ) `1_3 ) ) * ( D288 . ( ( C420 /. C423 ) `2_3 ) ) ) * ( D288 . ( ( C420 /. C423 ) `3_3 ) ) ) by L1204 , L1213
.= ( ( 0. C412 ) * ( D288 . ( ( C420 /. C423 ) `3_3 ) ) ) by L1217 , L1222 , VECTSP_1:6
.= ( 0. C412 ) by VECTSP_1:6;
end;
L1224: ( dom ( C413 --> ( 0. C412 ) ) ) = C413 by FUNCOP_1:13;
L1225: ( D287 . D286 ) = ( 1_ C412 ) by L1224 , FUNCT_7:31;
L1226: ( Support ( 1_1 (D286 , C412) ) ) = { ( UnitBag D286 ) } by L177;
L1227: ( ( Polynom-Evaluation (C413 , C412 , D287) ) . ( 1_1 (D286 , C412) ) ) = ( eval (( 1_1 (D286 , C412) ) , D287) ) by POLYNOM2:def 5
.= ( ( ( 1_1 (D286 , C412) ) . ( UnitBag D286 ) ) * ( eval (( UnitBag D286 ) , D287) ) ) by L1226 , POLYNOM2:19
.= ( ( 1_ C412 ) * ( eval (( UnitBag D286 ) , D287) ) ) by L172
.= ( ( 1_ C412 ) * ( D287 . D286 ) ) by L168
.= ( 1_ C412 ) by L1225 , GROUP_1:def 4;
L1228: (for B354 being set holds (B354 in ( dom D296 ) implies ( D296 . B354 ) = ( ( ( D288 . ( ( C420 /. B354 ) `1_3 ) ) * ( D288 . ( ( C420 /. B354 ) `2_3 ) ) ) * ( D288 . ( ( C420 /. B354 ) `3_3 ) ) ))) by L1204;
L1229: ( D288 . ( Sum C419 ) ) = ( Sum D296 ) by L1228 , L1202 , L1203 , L455
.= ( 0. C412 ) by L1208 , POLYNOM3:1;
thus L1230: contradiction by L1229 , L1201 , L1227;
end;
