:: Integrability Formulas -- Part {III}
::  by Bo Li and Na Ma
::
:: Received February 4, 2010
:: Copyright (c) 2010-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies RELAT_1, FUNCT_1, ARYTM_1, SIN_COS, VALUED_1, NAT_1, INTEGRA1,
      FDIFF_1, SQUARE_1, ARYTM_3, ORDINAL2, PREPOWER, REAL_1, PARTFUN1,
      TAYLOR_1, CARD_1, ORDINAL4, RCOMP_1, INTEGRA5, XXREAL_0, SIN_COS4,
      SUBSET_1, XBOOLE_0, TARSKI, NUMBERS, XXREAL_2, SEQ_4, MEASURE5;
 notations TARSKI, XBOOLE_0, SEQ_1, SIN_COS, SUBSET_1, NUMBERS, VALUED_1,
      ORDINAL1, XXREAL_0, REAL_1, RELSET_1, PARTFUN1, PARTFUN2, RCOMP_1,
      RFUNCT_1, MEASURE5, FCONT_1, SQUARE_1, INTEGRA5, PREPOWER, TAYLOR_1,
      FDIFF_1, SEQ_2, FDIFF_9, SIN_COS4, SEQ_4;
 constructors SIN_COS, TAYLOR_1, SEQ_1, REAL_1, FDIFF_1, FCONT_1, SQUARE_1,
      PREPOWER, INTEGRA5, SEQ_4, PARTFUN2, RFUNCT_1, FDIFF_9, SIN_COS4,
      RELSET_1, INTEGRA1, COMSEQ_2;
 registrations NUMBERS, MEMBERED, VALUED_0, INT_1, RELAT_1, RCOMP_1, RELSET_1,
      XXREAL_0, MEASURE5;
 requirements NUMERALS, SUBSET, ARITHM;
 definitions SIN_COS, VALUED_1, SIN_COS4, TARSKI, FDIFF_9, XBOOLE_0, XCMPLX_0;
 theorems PARTFUN1, RFUNCT_1, FUNCT_1, FDIFF_1, TARSKI, XBOOLE_0, INTEGRA5,
      SIN_COS, VALUED_1, XBOOLE_1, FDIFF_7, FDIFF_8, FDIFF_9, FDIFF_10,
      SIN_COS9, XREAL_0, RELAT_1, FDIFF_2;

begin
L1: (for R7 being  open (Subset of ( REAL )) holds (( 0 ) in R7 implies ( ( id R7 ) " { ( 0 ) } ) = { ( 0 ) }))
proof
let R7 being  open (Subset of ( REAL ));
assume L2: ( 0 ) in R7;
thus L3: ( ( id R7 ) " { ( 0 ) } ) c= { ( 0 ) }
proof
let C1 being set;
assume L4: C1 in ( ( id R7 ) " { ( 0 ) } );
L5: C1 in ( dom ( id R7 ) ) by L4 , FUNCT_1:def 7;
L6: C1 in R7 by L5;
L7: ( ( id R7 ) . C1 ) in { ( 0 ) } by L4 , FUNCT_1:def 7;
thus L8: thesis by L7 , L6 , FUNCT_1:18;
end;

let C2 being set;
assume L9: C2 in { ( 0 ) };
L10: C2 = ( 0 ) by L9 , TARSKI:def 1;
L11: ( ( id R7 ) . C2 ) = ( 0 ) by L10 , L2 , FUNCT_1:18;
L12: ( ( id R7 ) . C2 ) in { ( 0 ) } by L11 , TARSKI:def 1;
L13: C2 in ( dom ( id R7 ) ) by L2 , L10;
thus L14: thesis by L13 , L12 , FUNCT_1:def 7;
end;
theorem
L15: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( sec ) * ( ( id R7 ) ^ ) ) ) implies (( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L16: R7 c= ( dom ( ( sec ) * ( ( id R7 ) ^ ) ) );
L17: R7 c= ( dom ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) ) by L16 , VALUED_1:def 5;
L18: R7 c= ( dom ( ( id R7 ) ^ ) ) by L16 , FUNCT_1:101;
L19: (not ( 0 ) in R7)
proof
assume L20: ( 0 ) in R7;
L21: ( dom ( ( id R7 ) ^ ) ) = ( ( dom ( id R7 ) ) \ ( ( id R7 ) " { ( 0 ) } ) ) by RFUNCT_1:def 2
.= ( ( dom ( id R7 ) ) \ { ( 0 ) } ) by L1 , L20;
L22: (not ( 0 ) in { ( 0 ) }) by L21 , L20 , L18 , XBOOLE_0:def 5;
thus L23: thesis by L22 , TARSKI:def 1;
end;
L24: ( ( sec ) * ( ( id R7 ) ^ ) ) is_differentiable_on R7 by L19 , L16 , FDIFF_9:8;
L25: ( ( - 1 ) (#) ( ( sec ) * ( ( id R7 ) ^ ) ) ) is_differentiable_on R7 by L24 , L17 , FDIFF_1:20;
L26: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) )))
proof
let R2 being Real;
assume L27: R2 in R7;
L28: ( ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( sec ) * ( ( id R7 ) ^ ) ) `| R7 ) ) . R2 ) by L24 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( sec ) * ( ( id R7 ) ^ ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) ) ) ) by L16 , L19 , L27 , FDIFF_9:8
.= ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) );
thus L29: thesis by L28;
end;
thus L30: thesis by L26 , L25;
end;
theorem
L31: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cosec ) * ( exp_R ) ) ) implies (( - ( ( cosec ) * ( exp_R ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L32: R7 c= ( dom ( ( cosec ) * ( exp_R ) ) );
L33: R7 c= ( dom ( - ( ( cosec ) * ( exp_R ) ) ) ) by L32 , VALUED_1:8;
L34: ( ( cosec ) * ( exp_R ) ) is_differentiable_on R7 by L32 , FDIFF_9:13;
L35: ( ( - 1 ) (#) ( ( cosec ) * ( exp_R ) ) ) is_differentiable_on R7 by L34 , L33 , FDIFF_1:20;
L36: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) )))
proof
let R2 being Real;
assume L37: R2 in R7;
L38: ( ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cosec ) * ( exp_R ) ) `| R7 ) ) . R2 ) by L34 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cosec ) * ( exp_R ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) ) ) ) by L32 , L37 , FDIFF_9:13
.= ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) );
thus L39: thesis by L38;
end;
thus L40: thesis by L36 , L35;
end;
theorem
L41: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cosec ) * ( ln ) ) ) implies (( - ( ( cosec ) * ( ln ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L42: R7 c= ( dom ( ( cosec ) * ( ln ) ) );
L43: R7 c= ( dom ( - ( ( cosec ) * ( ln ) ) ) ) by L42 , VALUED_1:8;
L44: ( ( cosec ) * ( ln ) ) is_differentiable_on R7 by L42 , FDIFF_9:15;
L45: ( ( - 1 ) (#) ( ( cosec ) * ( ln ) ) ) is_differentiable_on R7 by L44 , L43 , FDIFF_1:20;
L46: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) )))
proof
let R2 being Real;
assume L47: R2 in R7;
L48: ( ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cosec ) * ( ln ) ) `| R7 ) ) . R2 ) by L44 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cosec ) * ( ln ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) ) ) ) by L42 , L47 , FDIFF_9:15
.= ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) );
thus L49: thesis by L48;
end;
thus L50: thesis by L46 , L45;
end;
theorem
L51: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( exp_R ) * ( cosec ) ) ) implies (( - ( ( exp_R ) * ( cosec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L52: R7 c= ( dom ( ( exp_R ) * ( cosec ) ) );
L53: R7 c= ( dom ( - ( ( exp_R ) * ( cosec ) ) ) ) by L52 , VALUED_1:8;
L54: ( ( exp_R ) * ( cosec ) ) is_differentiable_on R7 by L52 , FDIFF_9:17;
L55: ( ( - 1 ) (#) ( ( exp_R ) * ( cosec ) ) ) is_differentiable_on R7 by L54 , L53 , FDIFF_1:20;
L56: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) )))
proof
let R2 being Real;
assume L57: R2 in R7;
L58: ( ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( exp_R ) * ( cosec ) ) `| R7 ) ) . R2 ) by L54 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( exp_R ) * ( cosec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ) ) by L52 , L57 , FDIFF_9:17
.= ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) );
thus L59: thesis by L58;
end;
thus L60: thesis by L56 , L55;
end;
theorem
L61: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( ln ) * ( cosec ) ) ) implies (( - ( ( ln ) * ( cosec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( cot ) . R2 ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L62: R7 c= ( dom ( ( ln ) * ( cosec ) ) );
L63: R7 c= ( dom ( - ( ( ln ) * ( cosec ) ) ) ) by L62 , VALUED_1:8;
L64: ( ( ln ) * ( cosec ) ) is_differentiable_on R7 by L62 , FDIFF_9:19;
L65: ( ( - 1 ) (#) ( ( ln ) * ( cosec ) ) ) is_differentiable_on R7 by L64 , L63 , FDIFF_1:20;
L66: (for R2 being Real holds (R2 in R7 implies ( ( sin ) . R2 ) <> ( 0 )))
proof
let R2 being Real;
assume L67: R2 in R7;
L68: R2 in ( dom ( cosec ) ) by L67 , L62 , FUNCT_1:11;
thus L69: thesis by L68 , RFUNCT_1:3;
end;
L70: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( cot ) . R2 )))
proof
let R2 being Real;
assume L71: R2 in R7;
L72: ( ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( ln ) * ( cosec ) ) `| R7 ) ) . R2 ) by L64 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( ln ) * ( cosec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( cos ) . R2 ) / ( ( sin ) . R2 ) ) ) ) by L62 , L71 , FDIFF_9:19
.= ( cot R2 )
.= ( ( cot ) . R2 ) by L66 , L71 , SIN_COS9:16;
thus L73: thesis by L72;
end;
thus L74: thesis by L70 , L65;
end;
theorem
L75: (for R3 being Nat holds (for R7 being  open (Subset of ( REAL )) holds ((R7 c= ( dom ( ( #Z R3 ) * ( cosec ) ) ) & 1 <= R3) implies (( - ( ( #Z R3 ) * ( cosec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) )))))))
proof
let R3 being Nat;
let R7 being  open (Subset of ( REAL ));
assume L76: (R7 c= ( dom ( ( #Z R3 ) * ( cosec ) ) ) & 1 <= R3);
L77: (R7 c= ( dom ( - ( ( #Z R3 ) * ( cosec ) ) ) ) & 1 <= R3) by L76 , VALUED_1:8;
L78: ( ( #Z R3 ) * ( cosec ) ) is_differentiable_on R7 by L76 , FDIFF_9:21;
L79: ( ( - 1 ) (#) ( ( #Z R3 ) * ( cosec ) ) ) is_differentiable_on R7 by L78 , L77 , FDIFF_1:20;
L80: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) )))
proof
let R2 being Real;
assume L81: R2 in R7;
L82: ( ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( #Z R3 ) * ( cosec ) ) `| R7 ) ) . R2 ) by L78 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( #Z R3 ) * ( cosec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) ) ) ) by L76 , L81 , FDIFF_9:21
.= ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) );
thus L83: thesis by L82;
end;
thus L84: thesis by L80 , L79;
end;
theorem
L85: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) implies (( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) - ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L86: R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( sec ) ) );
L87: R7 c= ( dom ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) ) by L86 , VALUED_1:8;
L88: R7 c= ( ( dom ( ( id R7 ) ^ ) ) /\ ( dom ( sec ) ) ) by L86 , VALUED_1:def 4;
L89: R7 c= ( dom ( ( id R7 ) ^ ) ) by L88 , XBOOLE_1:18;
L90: (not ( 0 ) in R7)
proof
assume L91: ( 0 ) in R7;
L92: ( dom ( ( id R7 ) ^ ) ) = ( ( dom ( id R7 ) ) \ ( ( id R7 ) " { ( 0 ) } ) ) by RFUNCT_1:def 2
.= ( ( dom ( id R7 ) ) \ { ( 0 ) } ) by L1 , L91;
L93: (not ( 0 ) in { ( 0 ) }) by L92 , L91 , L89 , XBOOLE_0:def 5;
thus L94: thesis by L93 , TARSKI:def 1;
end;
L95: ( ( ( id R7 ) ^ ) (#) ( sec ) ) is_differentiable_on R7 by L90 , L86 , FDIFF_9:32;
L96: ( ( - 1 ) (#) ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) is_differentiable_on R7 by L95 , L87 , FDIFF_1:20;
L97: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) - ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L98: R2 in R7;
L99: ( ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( ( id R7 ) ^ ) (#) ( sec ) ) `| R7 ) ) . R2 ) by L95 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( ( id R7 ) ^ ) (#) ( sec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( - ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) ) + ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ) ) by L86 , L90 , L98 , FDIFF_9:32
.= ( ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) - ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) );
thus L100: thesis by L99;
end;
thus L101: thesis by L97 , L96;
end;
theorem
L102: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) implies (( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) + ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L103: R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( cosec ) ) );
L104: R7 c= ( dom ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) ) by L103 , VALUED_1:8;
L105: R7 c= ( ( dom ( ( id R7 ) ^ ) ) /\ ( dom ( cosec ) ) ) by L103 , VALUED_1:def 4;
L106: R7 c= ( dom ( ( id R7 ) ^ ) ) by L105 , XBOOLE_1:18;
L107: (not ( 0 ) in R7)
proof
assume L108: ( 0 ) in R7;
L109: ( dom ( ( id R7 ) ^ ) ) = ( ( dom ( id R7 ) ) \ ( ( id R7 ) " { ( 0 ) } ) ) by RFUNCT_1:def 2
.= ( ( dom ( id R7 ) ) \ { ( 0 ) } ) by L1 , L108;
L110: (not ( 0 ) in { ( 0 ) }) by L109 , L108 , L106 , XBOOLE_0:def 5;
thus L111: thesis by L110 , TARSKI:def 1;
end;
L112: ( ( ( id R7 ) ^ ) (#) ( cosec ) ) is_differentiable_on R7 by L107 , L103 , FDIFF_9:33;
L113: ( ( - 1 ) (#) ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) is_differentiable_on R7 by L112 , L104 , FDIFF_1:20;
L114: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) + ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L115: R2 in R7;
L116: ( ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( ( id R7 ) ^ ) (#) ( cosec ) ) `| R7 ) ) . R2 ) by L112 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( ( id R7 ) ^ ) (#) ( cosec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( - ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) ) - ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ) ) by L103 , L107 , L115 , FDIFF_9:33
.= ( ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) + ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) );
thus L117: thesis by L116;
end;
thus L118: thesis by L114 , L113;
end;
theorem
L119: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cosec ) * ( sin ) ) ) implies (( - ( ( cosec ) * ( sin ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L120: R7 c= ( dom ( ( cosec ) * ( sin ) ) );
L121: R7 c= ( dom ( - ( ( cosec ) * ( sin ) ) ) ) by L120 , VALUED_1:8;
L122: ( ( cosec ) * ( sin ) ) is_differentiable_on R7 by L120 , FDIFF_9:36;
L123: ( ( - 1 ) (#) ( ( cosec ) * ( sin ) ) ) is_differentiable_on R7 by L122 , L121 , FDIFF_1:20;
L124: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) )))
proof
let R2 being Real;
assume L125: R2 in R7;
L126: ( ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cosec ) * ( sin ) ) `| R7 ) ) . R2 ) by L122 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cosec ) * ( sin ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) ) ) ) by L120 , L125 , FDIFF_9:36
.= ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) );
thus L127: thesis by L126;
end;
thus L128: thesis by L124 , L123;
end;
theorem
L129: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( sec ) * ( cot ) ) ) implies (( - ( ( sec ) * ( cot ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L130: R7 c= ( dom ( ( sec ) * ( cot ) ) );
L131: R7 c= ( dom ( - ( ( sec ) * ( cot ) ) ) ) by L130 , VALUED_1:8;
L132: ( ( sec ) * ( cot ) ) is_differentiable_on R7 by L130 , FDIFF_9:39;
L133: ( ( - 1 ) (#) ( ( sec ) * ( cot ) ) ) is_differentiable_on R7 by L132 , L131 , FDIFF_1:20;
L134: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) )))
proof
let R2 being Real;
assume L135: R2 in R7;
L136: ( ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( sec ) * ( cot ) ) `| R7 ) ) . R2 ) by L132 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( sec ) * ( cot ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) ) ) by L130 , L135 , FDIFF_9:39
.= ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) );
thus L137: thesis by L136;
end;
thus L138: thesis by L134 , L133;
end;
theorem
L139: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cosec ) * ( tan ) ) ) implies (( - ( ( cosec ) * ( tan ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L140: R7 c= ( dom ( ( cosec ) * ( tan ) ) );
L141: R7 c= ( dom ( - ( ( cosec ) * ( tan ) ) ) ) by L140 , VALUED_1:8;
L142: ( ( cosec ) * ( tan ) ) is_differentiable_on R7 by L140 , FDIFF_9:40;
L143: ( dom ( ( cosec ) * ( tan ) ) ) c= ( dom ( tan ) ) by RELAT_1:25;
L144: R7 c= ( dom ( tan ) ) by L143 , L140 , XBOOLE_1:1;
L145: ( ( - 1 ) (#) ( ( cosec ) * ( tan ) ) ) is_differentiable_on R7 by L141 , L142 , FDIFF_1:20;
L146: (for R2 being Real holds (R2 in R7 implies ( ( sin ) . ( ( tan ) . R2 ) ) <> ( 0 )))
proof
let R2 being Real;
assume L147: R2 in R7;
L148: ( ( tan ) . R2 ) in ( dom ( cosec ) ) by L147 , L140 , FUNCT_1:11;
thus L149: thesis by L148 , RFUNCT_1:3;
end;
L150: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) )))
proof
let R2 being Real;
assume L151: R2 in R7;
L152: ( ( cos ) . R2 ) <> ( 0 ) by L151 , L144 , FDIFF_8:1;
L153: ( tan ) is_differentiable_in R2 by L152 , FDIFF_7:46;
L154: ( ( sin ) . ( ( tan ) . R2 ) ) <> ( 0 ) by L146 , L151;
L155: ( cosec ) is_differentiable_in ( ( tan ) . R2 ) by L154 , FDIFF_9:2;
L156: ( ( cosec ) * ( tan ) ) is_differentiable_in R2 by L142 , L151 , FDIFF_1:9;
L157: ( ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) . R2 ) = ( diff (( - ( ( cosec ) * ( tan ) ) ) , R2) ) by L145 , L151 , FDIFF_1:def 7
.= ( ( - 1 ) * ( diff (( ( cosec ) * ( tan ) ) , R2) ) ) by L156 , FDIFF_1:15
.= ( ( - 1 ) * ( ( diff (( cosec ) , ( ( tan ) . R2 )) ) * ( diff (( tan ) , R2) ) ) ) by L153 , L155 , FDIFF_2:13
.= ( ( - 1 ) * ( ( - ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) ) * ( diff (( tan ) , R2) ) ) ) by L154 , FDIFF_9:2
.= ( ( - 1 ) * ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) * ( - ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) ) ) ) by L152 , FDIFF_7:46
.= ( ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) );
thus L158: thesis by L157;
end;
thus L159: thesis by L150 , L145;
end;
theorem
L160: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cot ) (#) ( sec ) ) ) implies (( - ( ( cot ) (#) ( sec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) - ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L161: R7 c= ( dom ( ( cot ) (#) ( sec ) ) );
L162: R7 c= ( dom ( - ( ( cot ) (#) ( sec ) ) ) ) by L161 , VALUED_1:8;
L163: ( ( cot ) (#) ( sec ) ) is_differentiable_on R7 by L161 , FDIFF_9:43;
L164: ( ( - 1 ) (#) ( ( cot ) (#) ( sec ) ) ) is_differentiable_on R7 by L163 , L162 , FDIFF_1:20;
L165: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) - ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L166: R2 in R7;
L167: ( ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cot ) (#) ( sec ) ) `| R7 ) ) . R2 ) by L163 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cot ) (#) ( sec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( - ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) ) + ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ) ) by L161 , L166 , FDIFF_9:43
.= ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) - ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) );
thus L168: thesis by L167;
end;
thus L169: thesis by L165 , L164;
end;
theorem
L170: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cot ) (#) ( cosec ) ) ) implies (( - ( ( cot ) (#) ( cosec ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) + ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L171: R7 c= ( dom ( ( cot ) (#) ( cosec ) ) );
L172: R7 c= ( dom ( - ( ( cot ) (#) ( cosec ) ) ) ) by L171 , VALUED_1:8;
L173: ( ( cot ) (#) ( cosec ) ) is_differentiable_on R7 by L171 , FDIFF_9:45;
L174: ( ( - 1 ) (#) ( ( cot ) (#) ( cosec ) ) ) is_differentiable_on R7 by L173 , L172 , FDIFF_1:20;
L175: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) + ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L176: R2 in R7;
L177: ( ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cot ) (#) ( cosec ) ) `| R7 ) ) . R2 ) by L173 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cot ) (#) ( cosec ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( - ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) ) - ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ) ) by L171 , L176 , FDIFF_9:45
.= ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) + ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) );
thus L178: thesis by L177;
end;
thus L179: thesis by L175 , L174;
end;
theorem
L180: (for R7 being  open (Subset of ( REAL )) holds (R7 c= ( dom ( ( cos ) (#) ( cot ) ) ) implies (( - ( ( cos ) (#) ( cot ) ) ) is_differentiable_on R7 & (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . R2 ) + ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ))))))
proof
let R7 being  open (Subset of ( REAL ));
assume L181: R7 c= ( dom ( ( cos ) (#) ( cot ) ) );
L182: R7 c= ( dom ( - ( ( cos ) (#) ( cot ) ) ) ) by L181 , VALUED_1:8;
L183: ( ( cos ) (#) ( cot ) ) is_differentiable_on R7 by L181 , FDIFF_10:11;
L184: ( ( - 1 ) (#) ( ( cos ) (#) ( cot ) ) ) is_differentiable_on R7 by L183 , L182 , FDIFF_1:20;
L185: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . R2 ) + ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L186: R2 in R7;
L187: ( ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cos ) (#) ( cot ) ) `| R7 ) ) . R2 ) by L183 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cos ) (#) ( cot ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( - ( ( cos ) . R2 ) ) - ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ) ) by L181 , L186 , FDIFF_10:11
.= ( ( ( cos ) . R2 ) + ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) );
thus L188: thesis by L187;
end;
thus L189: thesis by L185 , L184;
end;
begin
theorem
L190: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( sec ) * ( ( id R7 ) ^ ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L191: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( sec ) * ( ( id R7 ) ^ ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L192: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L191 , INTEGRA5:10 , INTEGRA5:11;
L193: ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) is_differentiable_on R7 by L191 , L15;
L194: (for R2 being Real holds (R2 in ( dom ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) ) implies ( ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L195: R2 in ( dom ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) );
L196: R2 in R7 by L195 , L193 , FDIFF_1:def 7;
L197: ( ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( cos ) . ( 1 / R2 ) ) ^2 ) ) ) by L196 , L191 , L15
.= ( R5 . R2 ) by L191 , L196;
thus L198: thesis by L197;
end;
L199: ( dom ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) ) = ( dom R5 ) by L191 , L193 , FDIFF_1:def 7;
L200: ( ( - ( ( sec ) * ( ( id R7 ) ^ ) ) ) `| R7 ) = R5 by L199 , L194 , PARTFUN1:5;
thus L201: thesis by L200 , L191 , L192 , L193 , INTEGRA5:13;
end;
theorem
L202: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( sin ) . ( 1 / R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( cosec ) * ( ( id R7 ) ^ ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( cosec ) * ( ( id R7 ) ^ ) ) . ( upper_bound R4 ) ) - ( ( ( cosec ) * ( ( id R7 ) ^ ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L203: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( sin ) . ( 1 / R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( cosec ) * ( ( id R7 ) ^ ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L204: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L203 , INTEGRA5:10 , INTEGRA5:11;
L205: R7 c= ( dom ( ( id R7 ) ^ ) ) by L203 , FUNCT_1:101;
L206: (not ( 0 ) in R7)
proof
assume L207: ( 0 ) in R7;
L208: ( dom ( ( id R7 ) ^ ) ) = ( ( dom ( id R7 ) ) \ ( ( id R7 ) " { ( 0 ) } ) ) by RFUNCT_1:def 2
.= ( ( dom ( id R7 ) ) \ { ( 0 ) } ) by L1 , L207;
L209: (not ( 0 ) in { ( 0 ) }) by L208 , L207 , L205 , XBOOLE_0:def 5;
thus L210: thesis by L209 , TARSKI:def 1;
end;
L211: ( ( cosec ) * ( ( id R7 ) ^ ) ) is_differentiable_on R7 by L206 , L203 , FDIFF_9:9;
L212: (for R2 being Real holds (R2 in ( dom ( ( ( cosec ) * ( ( id R7 ) ^ ) ) `| R7 ) ) implies ( ( ( ( cosec ) * ( ( id R7 ) ^ ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L213: R2 in ( dom ( ( ( cosec ) * ( ( id R7 ) ^ ) ) `| R7 ) );
L214: R2 in R7 by L213 , L211 , FDIFF_1:def 7;
L215: ( ( ( ( cosec ) * ( ( id R7 ) ^ ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( 1 / R2 ) ) / ( ( R2 ^2 ) * ( ( ( sin ) . ( 1 / R2 ) ) ^2 ) ) ) by L214 , L203 , L206 , FDIFF_9:9
.= ( R5 . R2 ) by L203 , L214;
thus L216: thesis by L215;
end;
L217: ( dom ( ( ( cosec ) * ( ( id R7 ) ^ ) ) `| R7 ) ) = ( dom R5 ) by L203 , L211 , FDIFF_1:def 7;
L218: ( ( ( cosec ) * ( ( id R7 ) ^ ) ) `| R7 ) = R5 by L217 , L212 , PARTFUN1:5;
thus L219: thesis by L218 , L203 , L204 , L211 , INTEGRA5:13;
end;
theorem
L220: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( sin ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( cos ) . ( ( exp_R ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( exp_R ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( sec ) * ( exp_R ) ) . ( upper_bound R4 ) ) - ( ( ( sec ) * ( exp_R ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L221: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( sin ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( cos ) . ( ( exp_R ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( exp_R ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L222: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L221 , INTEGRA5:10 , INTEGRA5:11;
L223: ( ( sec ) * ( exp_R ) ) is_differentiable_on R7 by L221 , FDIFF_9:12;
L224: (for R2 being Real holds (R2 in ( dom ( ( ( sec ) * ( exp_R ) ) `| R7 ) ) implies ( ( ( ( sec ) * ( exp_R ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L225: R2 in ( dom ( ( ( sec ) * ( exp_R ) ) `| R7 ) );
L226: R2 in R7 by L225 , L223 , FDIFF_1:def 7;
L227: ( ( ( ( sec ) * ( exp_R ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( sin ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( cos ) . ( ( exp_R ) . R2 ) ) ^2 ) ) by L226 , L221 , FDIFF_9:12
.= ( R5 . R2 ) by L221 , L226;
thus L228: thesis by L227;
end;
L229: ( dom ( ( ( sec ) * ( exp_R ) ) `| R7 ) ) = ( dom R5 ) by L221 , L223 , FDIFF_1:def 7;
L230: ( ( ( sec ) * ( exp_R ) ) `| R7 ) = R5 by L229 , L224 , PARTFUN1:5;
thus L231: thesis by L230 , L221 , L222 , L223 , INTEGRA5:13;
end;
theorem
L232: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( exp_R ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cosec ) * ( exp_R ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cosec ) * ( exp_R ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L233: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( exp_R ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L234: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L233 , INTEGRA5:10 , INTEGRA5:11;
L235: ( - ( ( cosec ) * ( exp_R ) ) ) is_differentiable_on R7 by L233 , L31;
L236: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) ) implies ( ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L237: R2 in ( dom ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) );
L238: R2 in R7 by L237 , L235 , FDIFF_1:def 7;
L239: ( ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . ( ( exp_R ) . R2 ) ) ) / ( ( ( sin ) . ( ( exp_R ) . R2 ) ) ^2 ) ) by L238 , L233 , L31
.= ( R5 . R2 ) by L233 , L238;
thus L240: thesis by L239;
end;
L241: ( dom ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) ) = ( dom R5 ) by L233 , L235 , FDIFF_1:def 7;
L242: ( ( - ( ( cosec ) * ( exp_R ) ) ) `| R7 ) = R5 by L241 , L236 , PARTFUN1:5;
thus L243: thesis by L242 , L233 , L234 , L235 , INTEGRA5:13;
end;
theorem
L244: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( cos ) . ( ( ln ) . R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( sec ) * ( ln ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( sec ) * ( ln ) ) . ( upper_bound R4 ) ) - ( ( ( sec ) * ( ln ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L245: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( cos ) . ( ( ln ) . R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( sec ) * ( ln ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L246: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L245 , INTEGRA5:10 , INTEGRA5:11;
L247: ( ( sec ) * ( ln ) ) is_differentiable_on R7 by L245 , FDIFF_9:14;
L248: (for R2 being Real holds (R2 in ( dom ( ( ( sec ) * ( ln ) ) `| R7 ) ) implies ( ( ( ( sec ) * ( ln ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L249: R2 in ( dom ( ( ( sec ) * ( ln ) ) `| R7 ) );
L250: R2 in R7 by L249 , L247 , FDIFF_1:def 7;
L251: ( ( ( ( sec ) * ( ln ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( cos ) . ( ( ln ) . R2 ) ) ^2 ) ) ) by L250 , L245 , FDIFF_9:14
.= ( R5 . R2 ) by L245 , L250;
thus L252: thesis by L251;
end;
L253: ( dom ( ( ( sec ) * ( ln ) ) `| R7 ) ) = ( dom R5 ) by L245 , L247 , FDIFF_1:def 7;
L254: ( ( ( sec ) * ( ln ) ) `| R7 ) = R5 by L253 , L248 , PARTFUN1:5;
thus L255: thesis by L254 , L245 , L246 , L247 , INTEGRA5:13;
end;
theorem
L256: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( cosec ) * ( ln ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cosec ) * ( ln ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cosec ) * ( ln ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L257: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) ))) & R7 c= ( dom ( ( cosec ) * ( ln ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L258: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L257 , INTEGRA5:10 , INTEGRA5:11;
L259: ( - ( ( cosec ) * ( ln ) ) ) is_differentiable_on R7 by L257 , L41;
L260: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) ) implies ( ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L261: R2 in ( dom ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) );
L262: R2 in R7 by L261 , L259 , FDIFF_1:def 7;
L263: ( ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( ( ln ) . R2 ) ) / ( R2 * ( ( ( sin ) . ( ( ln ) . R2 ) ) ^2 ) ) ) by L262 , L257 , L41
.= ( R5 . R2 ) by L257 , L262;
thus L264: thesis by L263;
end;
L265: ( dom ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) ) = ( dom R5 ) by L257 , L259 , FDIFF_1:def 7;
L266: ( ( - ( ( cosec ) * ( ln ) ) ) `| R7 ) = R5 by L265 , L260 , PARTFUN1:5;
thus L267: thesis by L266 , L257 , L258 , L259 , INTEGRA5:13;
end;
theorem
L268: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & R5 = ( ( ( exp_R ) * ( sec ) ) (#) ( ( sin ) / ( ( cos ) ^2 ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( exp_R ) * ( sec ) ) . ( upper_bound R4 ) ) - ( ( ( exp_R ) * ( sec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L269: (R4 c= R7 & R5 = ( ( ( exp_R ) * ( sec ) ) (#) ( ( sin ) / ( ( cos ) ^2 ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L270: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L269 , INTEGRA5:10 , INTEGRA5:11;
L271: R7 = ( ( dom ( ( exp_R ) * ( sec ) ) ) /\ ( dom ( ( sin ) / ( ( cos ) ^2 ) ) ) ) by L269 , VALUED_1:def 4;
L272: (R7 c= ( dom ( ( exp_R ) * ( sec ) ) ) & R7 c= ( dom ( ( sin ) / ( ( cos ) ^2 ) ) )) by L271 , XBOOLE_1:18;
L273: ( ( exp_R ) * ( sec ) ) is_differentiable_on R7 by L272 , FDIFF_9:16;
L274: (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . ( ( sec ) . R2 ) ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) )))
proof
let R2 being Real;
assume L275: R2 in R7;
L276: ( ( ( ( exp_R ) * ( sec ) ) (#) ( ( sin ) / ( ( cos ) ^2 ) ) ) . R2 ) = ( ( ( ( exp_R ) * ( sec ) ) . R2 ) * ( ( ( sin ) / ( ( cos ) ^2 ) ) . R2 ) ) by VALUED_1:5
.= ( ( ( exp_R ) . ( ( sec ) . R2 ) ) * ( ( ( sin ) / ( ( cos ) ^2 ) ) . R2 ) ) by L275 , L272 , FUNCT_1:12
.= ( ( ( exp_R ) . ( ( sec ) . R2 ) ) * ( ( ( sin ) . R2 ) / ( ( ( cos ) ^2 ) . R2 ) ) ) by L272 , L275 , RFUNCT_1:def 1
.= ( ( ( exp_R ) . ( ( sec ) . R2 ) ) * ( ( ( sin ) . R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by VALUED_1:11
.= ( ( ( ( exp_R ) . ( ( sec ) . R2 ) ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) );
thus L277: thesis by L276 , L269;
end;
L278: (for R2 being Real holds (R2 in ( dom ( ( ( exp_R ) * ( sec ) ) `| R7 ) ) implies ( ( ( ( exp_R ) * ( sec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L279: R2 in ( dom ( ( ( exp_R ) * ( sec ) ) `| R7 ) );
L280: R2 in R7 by L279 , L273 , FDIFF_1:def 7;
L281: ( ( ( ( exp_R ) * ( sec ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . ( ( sec ) . R2 ) ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) by L280 , L272 , FDIFF_9:16
.= ( R5 . R2 ) by L274 , L280;
thus L282: thesis by L281;
end;
L283: ( dom ( ( ( exp_R ) * ( sec ) ) `| R7 ) ) = ( dom R5 ) by L269 , L273 , FDIFF_1:def 7;
L284: ( ( ( exp_R ) * ( sec ) ) `| R7 ) = R5 by L283 , L278 , PARTFUN1:5;
thus L285: thesis by L284 , L269 , L270 , L273 , INTEGRA5:13;
end;
theorem
L286: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & R5 = ( ( ( exp_R ) * ( cosec ) ) (#) ( ( cos ) / ( ( sin ) ^2 ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( exp_R ) * ( cosec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( exp_R ) * ( cosec ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L287: (R4 c= R7 & R5 = ( ( ( exp_R ) * ( cosec ) ) (#) ( ( cos ) / ( ( sin ) ^2 ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L288: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L287 , INTEGRA5:10 , INTEGRA5:11;
L289: R7 = ( ( dom ( ( exp_R ) * ( cosec ) ) ) /\ ( dom ( ( cos ) / ( ( sin ) ^2 ) ) ) ) by L287 , VALUED_1:def 4;
L290: (R7 c= ( dom ( ( exp_R ) * ( cosec ) ) ) & R7 c= ( dom ( ( cos ) / ( ( sin ) ^2 ) ) )) by L289 , XBOOLE_1:18;
L291: ( - ( ( exp_R ) * ( cosec ) ) ) is_differentiable_on R7 by L290 , L51;
L292: (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) )))
proof
let R2 being Real;
assume L293: R2 in R7;
L294: ( ( ( ( exp_R ) * ( cosec ) ) (#) ( ( cos ) / ( ( sin ) ^2 ) ) ) . R2 ) = ( ( ( ( exp_R ) * ( cosec ) ) . R2 ) * ( ( ( cos ) / ( ( sin ) ^2 ) ) . R2 ) ) by VALUED_1:5
.= ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( ( cos ) / ( ( sin ) ^2 ) ) . R2 ) ) by L293 , L290 , FUNCT_1:12
.= ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( ( cos ) . R2 ) / ( ( ( sin ) ^2 ) . R2 ) ) ) by L290 , L293 , RFUNCT_1:def 1
.= ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by VALUED_1:11
.= ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) );
thus L295: thesis by L294 , L287;
end;
L296: (for R2 being Real holds (R2 in ( dom ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) ) implies ( ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L297: R2 in ( dom ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) );
L298: R2 in R7 by L297 , L291 , FDIFF_1:def 7;
L299: ( ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . ( ( cosec ) . R2 ) ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) by L298 , L290 , L51
.= ( R5 . R2 ) by L292 , L298;
thus L300: thesis by L299;
end;
L301: ( dom ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) ) = ( dom R5 ) by L287 , L291 , FDIFF_1:def 7;
L302: ( ( - ( ( exp_R ) * ( cosec ) ) ) `| R7 ) = R5 by L301 , L296 , PARTFUN1:5;
thus L303: thesis by L302 , L287 , L288 , L291 , INTEGRA5:13;
end;
theorem
L304: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & R7 c= ( dom ( ( ln ) * ( sec ) ) ) & R7 = ( dom ( tan ) ) & ( ( tan ) | R4 ) is  continuous) implies ( integral (( tan ) , R4) ) = ( ( ( ( ln ) * ( sec ) ) . ( upper_bound R4 ) ) - ( ( ( ln ) * ( sec ) ) . ( lower_bound R4 ) ) ))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L305: (R4 c= R7 & R7 c= ( dom ( ( ln ) * ( sec ) ) ) & R7 = ( dom ( tan ) ) & ( ( tan ) | R4 ) is  continuous);
L306: (( tan ) is_integrable_on R4 & ( ( tan ) | R4 ) is  bounded) by L305 , INTEGRA5:10 , INTEGRA5:11;
L307: ( ( ln ) * ( sec ) ) is_differentiable_on R7 by L305 , FDIFF_9:18;
L308: (for R2 being Real holds (R2 in R7 implies ( ( cos ) . R2 ) <> ( 0 )))
proof
let R2 being Real;
assume L309: R2 in R7;
L310: R2 in ( dom ( sec ) ) by L309 , L305 , FUNCT_1:11;
thus L311: thesis by L310 , RFUNCT_1:3;
end;
L312: (for R2 being Real holds (R2 in ( dom ( ( ( ln ) * ( sec ) ) `| R7 ) ) implies ( ( ( ( ln ) * ( sec ) ) `| R7 ) . R2 ) = ( ( tan ) . R2 )))
proof
let R2 being Real;
assume L313: R2 in ( dom ( ( ( ln ) * ( sec ) ) `| R7 ) );
L314: R2 in R7 by L313 , L307 , FDIFF_1:def 7;
L315: ( ( cos ) . R2 ) <> ( 0 ) by L314 , L308;
L316: ( ( ( ( ln ) * ( sec ) ) `| R7 ) . R2 ) = ( tan R2 ) by L305 , L314 , FDIFF_9:18
.= ( ( tan ) . R2 ) by L315 , SIN_COS9:15;
thus L317: thesis by L316;
end;
L318: ( dom ( ( ( ln ) * ( sec ) ) `| R7 ) ) = ( dom ( tan ) ) by L305 , L307 , FDIFF_1:def 7;
L319: ( ( ( ln ) * ( sec ) ) `| R7 ) = ( tan ) by L318 , L312 , PARTFUN1:5;
thus L320: thesis by L319 , L305 , L306 , L307 , INTEGRA5:13;
end;
theorem
L321: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & R7 c= ( dom ( ( ln ) * ( cosec ) ) ) & R7 = ( dom ( cot ) ) & ( ( - ( cot ) ) | R4 ) is  continuous) implies ( integral (( - ( cot ) ) , R4) ) = ( ( ( ( ln ) * ( cosec ) ) . ( upper_bound R4 ) ) - ( ( ( ln ) * ( cosec ) ) . ( lower_bound R4 ) ) ))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L322: (R4 c= R7 & R7 c= ( dom ( ( ln ) * ( cosec ) ) ) & R7 = ( dom ( cot ) ) & ( ( - ( cot ) ) | R4 ) is  continuous);
L323: R7 = ( dom ( - ( cot ) ) ) by L322 , VALUED_1:8;
L324: (( - ( cot ) ) is_integrable_on R4 & ( ( - ( cot ) ) | R4 ) is  bounded) by L323 , L322 , INTEGRA5:10 , INTEGRA5:11;
L325: ( ( ln ) * ( cosec ) ) is_differentiable_on R7 by L322 , FDIFF_9:19;
L326: (for R2 being Real holds (R2 in R7 implies ( ( sin ) . R2 ) <> ( 0 )))
proof
let R2 being Real;
assume L327: R2 in R7;
L328: R2 in ( dom ( cosec ) ) by L327 , L322 , FUNCT_1:11;
thus L329: thesis by L328 , RFUNCT_1:3;
end;
L330: (for R2 being Real holds (R2 in ( dom ( ( ( ln ) * ( cosec ) ) `| R7 ) ) implies ( ( ( ( ln ) * ( cosec ) ) `| R7 ) . R2 ) = ( ( - ( cot ) ) . R2 )))
proof
let R2 being Real;
assume L331: R2 in ( dom ( ( ( ln ) * ( cosec ) ) `| R7 ) );
L332: R2 in R7 by L331 , L325 , FDIFF_1:def 7;
L333: ( ( sin ) . R2 ) <> ( 0 ) by L332 , L326;
L334: ( ( ( ( ln ) * ( cosec ) ) `| R7 ) . R2 ) = ( - ( cot R2 ) ) by L322 , L332 , FDIFF_9:19
.= ( - ( ( cot ) . R2 ) ) by L333 , SIN_COS9:16
.= ( ( - ( cot ) ) . R2 ) by VALUED_1:8;
thus L335: thesis by L334;
end;
L336: ( dom ( ( ( ln ) * ( cosec ) ) `| R7 ) ) = ( dom ( - ( cot ) ) ) by L323 , L325 , FDIFF_1:def 7;
L337: ( ( ( ln ) * ( cosec ) ) `| R7 ) = ( - ( cot ) ) by L336 , L330 , PARTFUN1:5;
thus L338: thesis by L337 , L322 , L324 , L325 , INTEGRA5:13;
end;
theorem
L339: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & R7 c= ( dom ( ( ln ) * ( cosec ) ) ) & R7 = ( dom ( cot ) ) & ( ( cot ) | R4 ) is  continuous) implies ( integral (( cot ) , R4) ) = ( ( ( - ( ( ln ) * ( cosec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( ln ) * ( cosec ) ) ) . ( lower_bound R4 ) ) ))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L340: (R4 c= R7 & R7 c= ( dom ( ( ln ) * ( cosec ) ) ) & R7 = ( dom ( cot ) ) & ( ( cot ) | R4 ) is  continuous);
L341: (( cot ) is_integrable_on R4 & ( ( cot ) | R4 ) is  bounded) by L340 , INTEGRA5:10 , INTEGRA5:11;
L342: ( - ( ( ln ) * ( cosec ) ) ) is_differentiable_on R7 by L340 , L61;
L343: (for R2 being Real holds (R2 in ( dom ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) ) implies ( ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( cot ) . R2 )))
proof
let R2 being Real;
assume L344: R2 in ( dom ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) );
L345: R2 in R7 by L344 , L342 , FDIFF_1:def 7;
L346: ( ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( cot ) . R2 ) by L345 , L340 , L61;
thus L347: thesis by L346;
end;
L348: ( dom ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) ) = ( dom ( cot ) ) by L340 , L342 , FDIFF_1:def 7;
L349: ( ( - ( ( ln ) * ( cosec ) ) ) `| R7 ) = ( cot ) by L348 , L343 , PARTFUN1:5;
thus L350: thesis by L349 , L340 , L341 , L342 , INTEGRA5:13;
end;
theorem
L351: (for R3 being Nat holds (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( R3 * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) #Z ( R3 + 1 ) ) ))) & R7 c= ( dom ( ( #Z R3 ) * ( sec ) ) ) & 1 <= R3 & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( #Z R3 ) * ( sec ) ) . ( upper_bound R4 ) ) - ( ( ( #Z R3 ) * ( sec ) ) . ( lower_bound R4 ) ) ))))))
proof
let R3 being Nat;
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L352: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( R3 * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) #Z ( R3 + 1 ) ) ))) & R7 c= ( dom ( ( #Z R3 ) * ( sec ) ) ) & 1 <= R3 & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L353: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L352 , INTEGRA5:10 , INTEGRA5:11;
L354: ( ( #Z R3 ) * ( sec ) ) is_differentiable_on R7 by L352 , FDIFF_9:20;
L355: (for R2 being Real holds (R2 in ( dom ( ( ( #Z R3 ) * ( sec ) ) `| R7 ) ) implies ( ( ( ( #Z R3 ) * ( sec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L356: R2 in ( dom ( ( ( #Z R3 ) * ( sec ) ) `| R7 ) );
L357: R2 in R7 by L356 , L354 , FDIFF_1:def 7;
L358: ( ( ( ( #Z R3 ) * ( sec ) ) `| R7 ) . R2 ) = ( ( R3 * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) #Z ( R3 + 1 ) ) ) by L357 , L352 , FDIFF_9:20
.= ( R5 . R2 ) by L352 , L357;
thus L359: thesis by L358;
end;
L360: ( dom ( ( ( #Z R3 ) * ( sec ) ) `| R7 ) ) = ( dom R5 ) by L352 , L354 , FDIFF_1:def 7;
L361: ( ( ( #Z R3 ) * ( sec ) ) `| R7 ) = R5 by L360 , L355 , PARTFUN1:5;
thus L362: thesis by L361 , L352 , L353 , L354 , INTEGRA5:13;
end;
theorem
L363: (for R3 being Nat holds (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) ))) & R7 c= ( dom ( ( #Z R3 ) * ( cosec ) ) ) & 1 <= R3 & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( #Z R3 ) * ( cosec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( #Z R3 ) * ( cosec ) ) ) . ( lower_bound R4 ) ) ))))))
proof
let R3 being Nat;
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L364: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) ))) & R7 c= ( dom ( ( #Z R3 ) * ( cosec ) ) ) & 1 <= R3 & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L365: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L364 , INTEGRA5:10 , INTEGRA5:11;
L366: ( - ( ( #Z R3 ) * ( cosec ) ) ) is_differentiable_on R7 by L364 , L75;
L367: (for R2 being Real holds (R2 in ( dom ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) ) implies ( ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L368: R2 in ( dom ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) );
L369: R2 in R7 by L368 , L366 , FDIFF_1:def 7;
L370: ( ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) . R2 ) = ( ( R3 * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) #Z ( R3 + 1 ) ) ) by L369 , L364 , L75
.= ( R5 . R2 ) by L364 , L369;
thus L371: thesis by L370;
end;
L372: ( dom ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) ) = ( dom R5 ) by L364 , L366 , FDIFF_1:def 7;
L373: ( ( - ( ( #Z R3 ) * ( cosec ) ) ) `| R7 ) = R5 by L372 , L367 , PARTFUN1:5;
thus L374: thesis by L373 , L364 , L365 , L366 , INTEGRA5:13;
end;
theorem
L375: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) / ( ( cos ) . R2 ) ) + ( ( ( ( exp_R ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( exp_R ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( exp_R ) (#) ( sec ) ) . ( upper_bound R4 ) ) - ( ( ( exp_R ) (#) ( sec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L376: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) / ( ( cos ) . R2 ) ) + ( ( ( ( exp_R ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( exp_R ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L377: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L376 , INTEGRA5:10 , INTEGRA5:11;
L378: ( ( exp_R ) (#) ( sec ) ) is_differentiable_on R7 by L376 , FDIFF_9:24;
L379: (for R2 being Real holds (R2 in ( dom ( ( ( exp_R ) (#) ( sec ) ) `| R7 ) ) implies ( ( ( ( exp_R ) (#) ( sec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L380: R2 in ( dom ( ( ( exp_R ) (#) ( sec ) ) `| R7 ) );
L381: R2 in R7 by L380 , L378 , FDIFF_1:def 7;
L382: ( ( ( ( exp_R ) (#) ( sec ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . R2 ) / ( ( cos ) . R2 ) ) + ( ( ( ( exp_R ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by L381 , L376 , FDIFF_9:24
.= ( R5 . R2 ) by L376 , L381;
thus L383: thesis by L382;
end;
L384: ( dom ( ( ( exp_R ) (#) ( sec ) ) `| R7 ) ) = ( dom R5 ) by L376 , L378 , FDIFF_1:def 7;
L385: ( ( ( exp_R ) (#) ( sec ) ) `| R7 ) = R5 by L384 , L379 , PARTFUN1:5;
thus L386: thesis by L385 , L376 , L377 , L378 , INTEGRA5:13;
end;
theorem
L387: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) / ( ( sin ) . R2 ) ) - ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( exp_R ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( exp_R ) (#) ( cosec ) ) . ( upper_bound R4 ) ) - ( ( ( exp_R ) (#) ( cosec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L388: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( exp_R ) . R2 ) / ( ( sin ) . R2 ) ) - ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( exp_R ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L389: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L388 , INTEGRA5:10 , INTEGRA5:11;
L390: ( ( exp_R ) (#) ( cosec ) ) is_differentiable_on R7 by L388 , FDIFF_9:25;
L391: (for R2 being Real holds (R2 in ( dom ( ( ( exp_R ) (#) ( cosec ) ) `| R7 ) ) implies ( ( ( ( exp_R ) (#) ( cosec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L392: R2 in ( dom ( ( ( exp_R ) (#) ( cosec ) ) `| R7 ) );
L393: R2 in R7 by L392 , L390 , FDIFF_1:def 7;
L394: ( ( ( ( exp_R ) (#) ( cosec ) ) `| R7 ) . R2 ) = ( ( ( ( exp_R ) . R2 ) / ( ( sin ) . R2 ) ) - ( ( ( ( exp_R ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by L393 , L388 , FDIFF_9:25
.= ( R5 . R2 ) by L388 , L393;
thus L395: thesis by L394;
end;
L396: ( dom ( ( ( exp_R ) (#) ( cosec ) ) `| R7 ) ) = ( dom R5 ) by L388 , L390 , FDIFF_1:def 7;
L397: ( ( ( exp_R ) (#) ( cosec ) ) `| R7 ) = R5 by L396 , L391 , PARTFUN1:5;
thus L398: thesis by L397 , L388 , L389 , L390 , INTEGRA5:13;
end;
theorem
L399: (for R1 being Real holds (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R6 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . ( R1 * R2 ) ) - ( ( ( cos ) . ( R1 * R2 ) ) ^2 ) ) / ( ( ( cos ) . ( R1 * R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) ) & (for R2 being Real holds (R2 in R7 implies (( R6 . R2 ) = ( R1 * R2 ) & R1 <> ( 0 )))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) . ( upper_bound R4 ) ) - ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) . ( lower_bound R4 ) ) )))))))
proof
let R1 being Real;
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R6 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L400: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . ( R1 * R2 ) ) - ( ( ( cos ) . ( R1 * R2 ) ) ^2 ) ) / ( ( ( cos ) . ( R1 * R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) ) & (for R2 being Real holds (R2 in R7 implies (( R6 . R2 ) = ( R1 * R2 ) & R1 <> ( 0 )))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L401: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L400 , INTEGRA5:10 , INTEGRA5:11;
L402: ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) is_differentiable_on R7 by L400 , FDIFF_9:26;
L403: (for R2 being Real holds (R2 in ( dom ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) `| R7 ) ) implies ( ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L404: R2 in ( dom ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) `| R7 ) );
L405: R2 in R7 by L404 , L402 , FDIFF_1:def 7;
L406: ( ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . ( R1 * R2 ) ) - ( ( ( cos ) . ( R1 * R2 ) ) ^2 ) ) / ( ( ( cos ) . ( R1 * R2 ) ) ^2 ) ) by L405 , L400 , FDIFF_9:26
.= ( R5 . R2 ) by L400 , L405;
thus L407: thesis by L406;
end;
L408: ( dom ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) `| R7 ) ) = ( dom R5 ) by L400 , L402 , FDIFF_1:def 7;
L409: ( ( ( ( 1 / R1 ) (#) ( ( sec ) * R6 ) ) - ( id R7 ) ) `| R7 ) = R5 by L408 , L403 , PARTFUN1:5;
thus L410: thesis by L409 , L400 , L401 , L402 , INTEGRA5:13;
end;
theorem
L411: (for R1 being Real holds (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R6 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . ( R1 * R2 ) ) - ( ( ( sin ) . ( R1 * R2 ) ) ^2 ) ) / ( ( ( sin ) . ( R1 * R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) ) & (for R2 being Real holds (R2 in R7 implies (( R6 . R2 ) = ( R1 * R2 ) & R1 <> ( 0 )))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) . ( upper_bound R4 ) ) - ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) . ( lower_bound R4 ) ) )))))))
proof
let R1 being Real;
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R6 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L412: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . ( R1 * R2 ) ) - ( ( ( sin ) . ( R1 * R2 ) ) ^2 ) ) / ( ( ( sin ) . ( R1 * R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) ) & (for R2 being Real holds (R2 in R7 implies (( R6 . R2 ) = ( R1 * R2 ) & R1 <> ( 0 )))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L413: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L412 , INTEGRA5:10 , INTEGRA5:11;
L414: ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) is_differentiable_on R7 by L412 , FDIFF_9:27;
L415: (for R2 being Real holds (R2 in ( dom ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) `| R7 ) ) implies ( ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L416: R2 in ( dom ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) `| R7 ) );
L417: R2 in R7 by L416 , L414 , FDIFF_1:def 7;
L418: ( ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . ( R1 * R2 ) ) - ( ( ( sin ) . ( R1 * R2 ) ) ^2 ) ) / ( ( ( sin ) . ( R1 * R2 ) ) ^2 ) ) by L417 , L412 , FDIFF_9:27
.= ( R5 . R2 ) by L412 , L417;
thus L419: thesis by L418;
end;
L420: ( dom ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) `| R7 ) ) = ( dom R5 ) by L412 , L414 , FDIFF_1:def 7;
L421: ( ( ( ( - ( 1 / R1 ) ) (#) ( ( cosec ) * R6 ) ) - ( id R7 ) ) `| R7 ) = R5 by L420 , L415 , PARTFUN1:5;
thus L422: thesis by L421 , L412 , L413 , L414 , INTEGRA5:13;
end;
theorem
L423: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / R2 ) + ( ( ( ( ln ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ln ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( ln ) (#) ( sec ) ) . ( upper_bound R4 ) ) - ( ( ( ln ) (#) ( sec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L424: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / R2 ) + ( ( ( ( ln ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ln ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L425: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L424 , INTEGRA5:10 , INTEGRA5:11;
L426: ( ( ln ) (#) ( sec ) ) is_differentiable_on R7 by L424 , FDIFF_9:30;
L427: (for R2 being Real holds (R2 in ( dom ( ( ( ln ) (#) ( sec ) ) `| R7 ) ) implies ( ( ( ( ln ) (#) ( sec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L428: R2 in ( dom ( ( ( ln ) (#) ( sec ) ) `| R7 ) );
L429: R2 in R7 by L428 , L426 , FDIFF_1:def 7;
L430: ( ( ( ( ln ) (#) ( sec ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / R2 ) + ( ( ( ( ln ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by L429 , L424 , FDIFF_9:30
.= ( R5 . R2 ) by L424 , L429;
thus L431: thesis by L430;
end;
L432: ( dom ( ( ( ln ) (#) ( sec ) ) `| R7 ) ) = ( dom R5 ) by L424 , L426 , FDIFF_1:def 7;
L433: ( ( ( ln ) (#) ( sec ) ) `| R7 ) = R5 by L432 , L427 , PARTFUN1:5;
thus L434: thesis by L433 , L424 , L425 , L426 , INTEGRA5:13;
end;
theorem
L435: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / R2 ) - ( ( ( ( ln ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ln ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( ln ) (#) ( cosec ) ) . ( upper_bound R4 ) ) - ( ( ( ln ) (#) ( cosec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L436: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / R2 ) - ( ( ( ( ln ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ln ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L437: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L436 , INTEGRA5:10 , INTEGRA5:11;
L438: ( ( ln ) (#) ( cosec ) ) is_differentiable_on R7 by L436 , FDIFF_9:31;
L439: (for R2 being Real holds (R2 in ( dom ( ( ( ln ) (#) ( cosec ) ) `| R7 ) ) implies ( ( ( ( ln ) (#) ( cosec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L440: R2 in ( dom ( ( ( ln ) (#) ( cosec ) ) `| R7 ) );
L441: R2 in R7 by L440 , L438 , FDIFF_1:def 7;
L442: ( ( ( ( ln ) (#) ( cosec ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / R2 ) - ( ( ( ( ln ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by L441 , L436 , FDIFF_9:31
.= ( R5 . R2 ) by L436 , L441;
thus L443: thesis by L442;
end;
L444: ( dom ( ( ( ln ) (#) ( cosec ) ) `| R7 ) ) = ( dom R5 ) by L436 , L438 , FDIFF_1:def 7;
L445: ( ( ( ln ) (#) ( cosec ) ) `| R7 ) = R5 by L444 , L439 , PARTFUN1:5;
thus L446: thesis by L445 , L436 , L437 , L438 , INTEGRA5:13;
end;
theorem
L447: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) - ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L448: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) - ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L449: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L448 , INTEGRA5:10 , INTEGRA5:11;
L450: ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) is_differentiable_on R7 by L448 , L85;
L451: (for R2 being Real holds (R2 in ( dom ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) ) implies ( ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L452: R2 in ( dom ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) );
L453: R2 in R7 by L452 , L450 , FDIFF_1:def 7;
L454: ( ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( cos ) . R2 ) ) / ( R2 ^2 ) ) - ( ( ( ( sin ) . R2 ) / R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by L453 , L448 , L85
.= ( R5 . R2 ) by L448 , L453;
thus L455: thesis by L454;
end;
L456: ( dom ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) ) = ( dom R5 ) by L448 , L450 , FDIFF_1:def 7;
L457: ( ( - ( ( ( id R7 ) ^ ) (#) ( sec ) ) ) `| R7 ) = R5 by L456 , L451 , PARTFUN1:5;
thus L458: thesis by L457 , L448 , L449 , L450 , INTEGRA5:13;
end;
theorem
L459: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) + ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L460: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) + ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L461: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L460 , INTEGRA5:10 , INTEGRA5:11;
L462: ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) is_differentiable_on R7 by L460 , L102;
L463: (for R2 being Real holds (R2 in ( dom ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) ) implies ( ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L464: R2 in ( dom ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) );
L465: R2 in R7 by L464 , L462 , FDIFF_1:def 7;
L466: ( ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( sin ) . R2 ) ) / ( R2 ^2 ) ) + ( ( ( ( cos ) . R2 ) / R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by L465 , L460 , L102
.= ( R5 . R2 ) by L460 , L465;
thus L467: thesis by L466;
end;
L468: ( dom ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) ) = ( dom R5 ) by L460 , L462 , FDIFF_1:def 7;
L469: ( ( - ( ( ( id R7 ) ^ ) (#) ( cosec ) ) ) `| R7 ) = R5 by L468 , L463 , PARTFUN1:5;
thus L470: thesis by L469 , L460 , L461 , L462 , INTEGRA5:13;
end;
theorem
L471: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( sin ) . ( ( sin ) . R2 ) ) ) / ( ( ( cos ) . ( ( sin ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( sin ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( sec ) * ( sin ) ) . ( upper_bound R4 ) ) - ( ( ( sec ) * ( sin ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L472: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( sin ) . ( ( sin ) . R2 ) ) ) / ( ( ( cos ) . ( ( sin ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( sin ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L473: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L472 , INTEGRA5:10 , INTEGRA5:11;
L474: ( ( sec ) * ( sin ) ) is_differentiable_on R7 by L472 , FDIFF_9:34;
L475: (for R2 being Real holds (R2 in ( dom ( ( ( sec ) * ( sin ) ) `| R7 ) ) implies ( ( ( ( sec ) * ( sin ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L476: R2 in ( dom ( ( ( sec ) * ( sin ) ) `| R7 ) );
L477: R2 in R7 by L476 , L474 , FDIFF_1:def 7;
L478: ( ( ( ( sec ) * ( sin ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( sin ) . ( ( sin ) . R2 ) ) ) / ( ( ( cos ) . ( ( sin ) . R2 ) ) ^2 ) ) by L477 , L472 , FDIFF_9:34
.= ( R5 . R2 ) by L472 , L477;
thus L479: thesis by L478;
end;
L480: ( dom ( ( ( sec ) * ( sin ) ) `| R7 ) ) = ( dom R5 ) by L472 , L474 , FDIFF_1:def 7;
L481: ( ( ( sec ) * ( sin ) ) `| R7 ) = R5 by L480 , L475 , PARTFUN1:5;
thus L482: thesis by L481 , L472 , L473 , L474 , INTEGRA5:13;
end;
theorem
L483: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( sin ) . ( ( cos ) . R2 ) ) ) / ( ( ( cos ) . ( ( cos ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( cos ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( sec ) * ( cos ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( sec ) * ( cos ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L484: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( sin ) . ( ( cos ) . R2 ) ) ) / ( ( ( cos ) . ( ( cos ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( cos ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L485: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L484 , INTEGRA5:10 , INTEGRA5:11;
L486: R7 c= ( dom ( - ( ( sec ) * ( cos ) ) ) ) by L484 , VALUED_1:8;
L487: ( ( sec ) * ( cos ) ) is_differentiable_on R7 by L484 , FDIFF_9:35;
L488: ( ( - 1 ) (#) ( ( sec ) * ( cos ) ) ) is_differentiable_on R7 by L487 , L486 , FDIFF_1:20;
L489: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( sin ) . ( ( cos ) . R2 ) ) ) / ( ( ( cos ) . ( ( cos ) . R2 ) ) ^2 ) )))
proof
let R2 being Real;
assume L490: R2 in R7;
L491: ( ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( sec ) * ( cos ) ) `| R7 ) ) . R2 ) by L487 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( sec ) * ( cos ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( ( sin ) . R2 ) * ( ( sin ) . ( ( cos ) . R2 ) ) ) / ( ( ( cos ) . ( ( cos ) . R2 ) ) ^2 ) ) ) ) by L484 , L490 , FDIFF_9:35
.= ( ( ( ( sin ) . R2 ) * ( ( sin ) . ( ( cos ) . R2 ) ) ) / ( ( ( cos ) . ( ( cos ) . R2 ) ) ^2 ) );
thus L492: thesis by L491;
end;
L493: (for R2 being Real holds (R2 in ( dom ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) ) implies ( ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L494: R2 in ( dom ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) );
L495: R2 in R7 by L494 , L488 , FDIFF_1:def 7;
L496: ( ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( sin ) . ( ( cos ) . R2 ) ) ) / ( ( ( cos ) . ( ( cos ) . R2 ) ) ^2 ) ) by L495 , L489
.= ( R5 . R2 ) by L484 , L495;
thus L497: thesis by L496;
end;
L498: ( dom ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) ) = ( dom R5 ) by L484 , L488 , FDIFF_1:def 7;
L499: ( ( - ( ( sec ) * ( cos ) ) ) `| R7 ) = R5 by L498 , L493 , PARTFUN1:5;
thus L500: thesis by L499 , L484 , L485 , L488 , INTEGRA5:13;
end;
theorem
L501: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( sin ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cosec ) * ( sin ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cosec ) * ( sin ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L502: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( sin ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L503: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L502 , INTEGRA5:10 , INTEGRA5:11;
L504: ( - ( ( cosec ) * ( sin ) ) ) is_differentiable_on R7 by L502 , L119;
L505: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) ) implies ( ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L506: R2 in ( dom ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) );
L507: R2 in R7 by L506 , L504 , FDIFF_1:def 7;
L508: ( ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . R2 ) * ( ( cos ) . ( ( sin ) . R2 ) ) ) / ( ( ( sin ) . ( ( sin ) . R2 ) ) ^2 ) ) by L507 , L502 , L119
.= ( R5 . R2 ) by L502 , L507;
thus L509: thesis by L508;
end;
L510: ( dom ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) ) = ( dom R5 ) by L502 , L504 , FDIFF_1:def 7;
L511: ( ( - ( ( cosec ) * ( sin ) ) ) `| R7 ) = R5 by L510 , L505 , PARTFUN1:5;
thus L512: thesis by L511 , L502 , L503 , L504 , INTEGRA5:13;
end;
theorem
L513: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( cos ) . ( ( cos ) . R2 ) ) ) / ( ( ( sin ) . ( ( cos ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( cos ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( cosec ) * ( cos ) ) . ( upper_bound R4 ) ) - ( ( ( cosec ) * ( cos ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L514: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( cos ) . ( ( cos ) . R2 ) ) ) / ( ( ( sin ) . ( ( cos ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( cos ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L515: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L514 , INTEGRA5:10 , INTEGRA5:11;
L516: ( ( cosec ) * ( cos ) ) is_differentiable_on R7 by L514 , FDIFF_9:37;
L517: (for R2 being Real holds (R2 in ( dom ( ( ( cosec ) * ( cos ) ) `| R7 ) ) implies ( ( ( ( cosec ) * ( cos ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L518: R2 in ( dom ( ( ( cosec ) * ( cos ) ) `| R7 ) );
L519: R2 in R7 by L518 , L516 , FDIFF_1:def 7;
L520: ( ( ( ( cosec ) * ( cos ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . R2 ) * ( ( cos ) . ( ( cos ) . R2 ) ) ) / ( ( ( sin ) . ( ( cos ) . R2 ) ) ^2 ) ) by L519 , L514 , FDIFF_9:37
.= ( R5 . R2 ) by L514 , L519;
thus L521: thesis by L520;
end;
L522: ( dom ( ( ( cosec ) * ( cos ) ) `| R7 ) ) = ( dom R5 ) by L514 , L516 , FDIFF_1:def 7;
L523: ( ( ( cosec ) * ( cos ) ) `| R7 ) = R5 by L522 , L517 , PARTFUN1:5;
thus L524: thesis by L523 , L514 , L515 , L516 , INTEGRA5:13;
end;
theorem
L525: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( tan ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( sec ) * ( tan ) ) . ( upper_bound R4 ) ) - ( ( ( sec ) * ( tan ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L526: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( tan ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L527: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L526 , INTEGRA5:10 , INTEGRA5:11;
L528: ( ( sec ) * ( tan ) ) is_differentiable_on R7 by L526 , FDIFF_9:38;
L529: (for R2 being Real holds (R2 in ( dom ( ( ( sec ) * ( tan ) ) `| R7 ) ) implies ( ( ( ( sec ) * ( tan ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L530: R2 in ( dom ( ( ( sec ) * ( tan ) ) `| R7 ) );
L531: R2 in R7 by L530 , L528 , FDIFF_1:def 7;
L532: ( ( ( ( sec ) * ( tan ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( tan ) . R2 ) ) ^2 ) ) by L531 , L526 , FDIFF_9:38
.= ( R5 . R2 ) by L526 , L531;
thus L533: thesis by L532;
end;
L534: ( dom ( ( ( sec ) * ( tan ) ) `| R7 ) ) = ( dom R5 ) by L526 , L528 , FDIFF_1:def 7;
L535: ( ( ( sec ) * ( tan ) ) `| R7 ) = R5 by L534 , L529 , PARTFUN1:5;
thus L536: thesis by L535 , L526 , L527 , L528 , INTEGRA5:13;
end;
theorem
L537: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( sec ) * ( cot ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( sec ) * ( cot ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L538: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( sec ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L539: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L538 , INTEGRA5:10 , INTEGRA5:11;
L540: ( - ( ( sec ) * ( cot ) ) ) is_differentiable_on R7 by L538 , L129;
L541: (for R2 being Real holds (R2 in ( dom ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) ) implies ( ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L542: R2 in ( dom ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) );
L543: R2 in R7 by L542 , L540 , FDIFF_1:def 7;
L544: ( ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( ( sin ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) by L543 , L538 , L129
.= ( R5 . R2 ) by L538 , L543;
thus L545: thesis by L544;
end;
L546: ( dom ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) ) = ( dom R5 ) by L538 , L540 , FDIFF_1:def 7;
L547: ( ( - ( ( sec ) * ( cot ) ) ) `| R7 ) = R5 by L546 , L541 , PARTFUN1:5;
thus L548: thesis by L547 , L538 , L539 , L540 , INTEGRA5:13;
end;
theorem
L549: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cosec ) * ( tan ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cosec ) * ( tan ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L550: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L551: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L550 , INTEGRA5:10 , INTEGRA5:11;
L552: ( - ( ( cosec ) * ( tan ) ) ) is_differentiable_on R7 by L550 , L139;
L553: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) ) implies ( ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L554: R2 in ( dom ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) );
L555: R2 in R7 by L554 , L552 , FDIFF_1:def 7;
L556: ( ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . ( ( tan ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) by L555 , L550 , L139
.= ( R5 . R2 ) by L550 , L555;
thus L557: thesis by L556;
end;
L558: ( dom ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) ) = ( dom R5 ) by L550 , L552 , FDIFF_1:def 7;
L559: ( ( - ( ( cosec ) * ( tan ) ) ) `| R7 ) = R5 by L558 , L553 , PARTFUN1:5;
thus L560: thesis by L559 , L550 , L551 , L552 , INTEGRA5:13;
end;
theorem
L561: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( cot ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( cosec ) * ( cot ) ) . ( upper_bound R4 ) ) - ( ( ( cosec ) * ( cot ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L562: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( ( cos ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( cot ) . R2 ) ) ^2 ) ))) & R7 c= ( dom ( ( cosec ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L563: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L562 , INTEGRA5:10 , INTEGRA5:11;
L564: ( ( cosec ) * ( cot ) ) is_differentiable_on R7 by L562 , FDIFF_9:41;
L565: (for R2 being Real holds (R2 in ( dom ( ( ( cosec ) * ( cot ) ) `| R7 ) ) implies ( ( ( ( cosec ) * ( cot ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L566: R2 in ( dom ( ( ( cosec ) * ( cot ) ) `| R7 ) );
L567: R2 in R7 by L566 , L564 , FDIFF_1:def 7;
L568: ( ( ( ( cosec ) * ( cot ) ) `| R7 ) . R2 ) = ( ( ( ( cos ) . ( ( cot ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( ( sin ) . ( ( cot ) . R2 ) ) ^2 ) ) by L567 , L562 , FDIFF_9:41
.= ( R5 . R2 ) by L562 , L567;
thus L569: thesis by L568;
end;
L570: ( dom ( ( ( cosec ) * ( cot ) ) `| R7 ) ) = ( dom R5 ) by L562 , L564 , FDIFF_1:def 7;
L571: ( ( ( cosec ) * ( cot ) ) `| R7 ) = R5 by L570 , L565 , PARTFUN1:5;
thus L572: thesis by L571 , L562 , L563 , L564 , INTEGRA5:13;
end;
theorem
L573: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) + ( ( ( ( tan ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( tan ) (#) ( sec ) ) . ( upper_bound R4 ) ) - ( ( ( tan ) (#) ( sec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L574: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) + ( ( ( ( tan ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L575: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L574 , INTEGRA5:10 , INTEGRA5:11;
L576: ( ( tan ) (#) ( sec ) ) is_differentiable_on R7 by L574 , FDIFF_9:42;
L577: (for R2 being Real holds (R2 in ( dom ( ( ( tan ) (#) ( sec ) ) `| R7 ) ) implies ( ( ( ( tan ) (#) ( sec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L578: R2 in ( dom ( ( ( tan ) (#) ( sec ) ) `| R7 ) );
L579: R2 in R7 by L578 , L576 , FDIFF_1:def 7;
L580: ( ( ( ( tan ) (#) ( sec ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) + ( ( ( ( tan ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by L579 , L574 , FDIFF_9:42
.= ( R5 . R2 ) by L574 , L579;
thus L581: thesis by L580;
end;
L582: ( dom ( ( ( tan ) (#) ( sec ) ) `| R7 ) ) = ( dom R5 ) by L574 , L576 , FDIFF_1:def 7;
L583: ( ( ( tan ) (#) ( sec ) ) `| R7 ) = R5 by L582 , L577 , PARTFUN1:5;
thus L584: thesis by L583 , L574 , L575 , L576 , INTEGRA5:13;
end;
theorem
L585: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) - ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cot ) (#) ( sec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cot ) (#) ( sec ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L586: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) - ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) (#) ( sec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L587: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L586 , INTEGRA5:10 , INTEGRA5:11;
L588: ( - ( ( cot ) (#) ( sec ) ) ) is_differentiable_on R7 by L586 , L160;
L589: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) ) implies ( ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L590: R2 in ( dom ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) );
L591: R2 in R7 by L590 , L588 , FDIFF_1:def 7;
L592: ( ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( cos ) . R2 ) ) - ( ( ( ( cot ) . R2 ) * ( ( sin ) . R2 ) ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by L591 , L586 , L160
.= ( R5 . R2 ) by L586 , L591;
thus L593: thesis by L592;
end;
L594: ( dom ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) ) = ( dom R5 ) by L586 , L588 , FDIFF_1:def 7;
L595: ( ( - ( ( cot ) (#) ( sec ) ) ) `| R7 ) = R5 by L594 , L589 , PARTFUN1:5;
thus L596: thesis by L595 , L586 , L587 , L588 , INTEGRA5:13;
end;
theorem
L597: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) - ( ( ( ( tan ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( tan ) (#) ( cosec ) ) . ( upper_bound R4 ) ) - ( ( ( tan ) (#) ( cosec ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L598: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) - ( ( ( ( tan ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L599: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L598 , INTEGRA5:10 , INTEGRA5:11;
L600: ( ( tan ) (#) ( cosec ) ) is_differentiable_on R7 by L598 , FDIFF_9:44;
L601: (for R2 being Real holds (R2 in ( dom ( ( ( tan ) (#) ( cosec ) ) `| R7 ) ) implies ( ( ( ( tan ) (#) ( cosec ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L602: R2 in ( dom ( ( ( tan ) (#) ( cosec ) ) `| R7 ) );
L603: R2 in R7 by L602 , L600 , FDIFF_1:def 7;
L604: ( ( ( ( tan ) (#) ( cosec ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) - ( ( ( ( tan ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by L603 , L598 , FDIFF_9:44
.= ( R5 . R2 ) by L598 , L603;
thus L605: thesis by L604;
end;
L606: ( dom ( ( ( tan ) (#) ( cosec ) ) `| R7 ) ) = ( dom R5 ) by L598 , L600 , FDIFF_1:def 7;
L607: ( ( ( tan ) (#) ( cosec ) ) `| R7 ) = R5 by L606 , L601 , PARTFUN1:5;
thus L608: thesis by L607 , L598 , L599 , L600 , INTEGRA5:13;
end;
theorem
L609: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) + ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cot ) (#) ( cosec ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cot ) (#) ( cosec ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L610: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) + ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) (#) ( cosec ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L611: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L610 , INTEGRA5:10 , INTEGRA5:11;
L612: ( - ( ( cot ) (#) ( cosec ) ) ) is_differentiable_on R7 by L610 , L170;
L613: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) ) implies ( ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L614: R2 in ( dom ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) );
L615: R2 in R7 by L614 , L612 , FDIFF_1:def 7;
L616: ( ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) . R2 ) = ( ( ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) / ( ( sin ) . R2 ) ) + ( ( ( ( cot ) . R2 ) * ( ( cos ) . R2 ) ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by L615 , L610 , L170
.= ( R5 . R2 ) by L610 , L615;
thus L617: thesis by L616;
end;
L618: ( dom ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) ) = ( dom R5 ) by L610 , L612 , FDIFF_1:def 7;
L619: ( ( - ( ( cot ) (#) ( cosec ) ) ) `| R7 ) = R5 by L618 , L613 , PARTFUN1:5;
thus L620: thesis by L619 , L610 , L611 , L612 , INTEGRA5:13;
end;
theorem
L621: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( tan ) * ( cot ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( tan ) * ( cot ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L622: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L623: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L622 , INTEGRA5:10 , INTEGRA5:11;
L624: R7 c= ( dom ( - ( ( tan ) * ( cot ) ) ) ) by L622 , VALUED_1:8;
L625: ( ( tan ) * ( cot ) ) is_differentiable_on R7 by L622 , FDIFF_10:1;
L626: ( ( - 1 ) (#) ( ( tan ) * ( cot ) ) ) is_differentiable_on R7 by L625 , L624 , FDIFF_1:20;
L627: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L628: R2 in R7;
L629: ( ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( tan ) * ( cot ) ) `| R7 ) ) . R2 ) by L625 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( tan ) * ( cot ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( 1 / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( - ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ) ) ) by L622 , L628 , FDIFF_10:1
.= ( ( 1 / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) );
thus L630: thesis by L629;
end;
L631: (for R2 being Real holds (R2 in ( dom ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) ) implies ( ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L632: R2 in ( dom ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) );
L633: R2 in R7 by L632 , L626 , FDIFF_1:def 7;
L634: ( ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ) by L633 , L627
.= ( R5 . R2 ) by L622 , L633;
thus L635: thesis by L634;
end;
L636: ( dom ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) ) = ( dom R5 ) by L622 , L626 , FDIFF_1:def 7;
L637: ( ( - ( ( tan ) * ( cot ) ) ) `| R7 ) = R5 by L636 , L631 , PARTFUN1:5;
thus L638: thesis by L637 , L622 , L623 , L626 , INTEGRA5:13;
end;
theorem
L639: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( tan ) * ( tan ) ) . ( upper_bound R4 ) ) - ( ( ( tan ) * ( tan ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L640: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L641: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L640 , INTEGRA5:10 , INTEGRA5:11;
L642: ( ( tan ) * ( tan ) ) is_differentiable_on R7 by L640 , FDIFF_10:2;
L643: (for R2 being Real holds (R2 in ( dom ( ( ( tan ) * ( tan ) ) `| R7 ) ) implies ( ( ( ( tan ) * ( tan ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L644: R2 in ( dom ( ( ( tan ) * ( tan ) ) `| R7 ) );
L645: R2 in R7 by L644 , L642 , FDIFF_1:def 7;
L646: ( ( ( ( tan ) * ( tan ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( cos ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ) by L645 , L640 , FDIFF_10:2
.= ( R5 . R2 ) by L640 , L645;
thus L647: thesis by L646;
end;
L648: ( dom ( ( ( tan ) * ( tan ) ) `| R7 ) ) = ( dom R5 ) by L640 , L642 , FDIFF_1:def 7;
L649: ( ( ( tan ) * ( tan ) ) `| R7 ) = R5 by L648 , L643 , PARTFUN1:5;
thus L650: thesis by L649 , L640 , L641 , L642 , INTEGRA5:13;
end;
theorem
L651: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( cot ) * ( cot ) ) . ( upper_bound R4 ) ) - ( ( ( cot ) * ( cot ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L652: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) * ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L653: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L652 , INTEGRA5:10 , INTEGRA5:11;
L654: ( ( cot ) * ( cot ) ) is_differentiable_on R7 by L652 , FDIFF_10:3;
L655: (for R2 being Real holds (R2 in ( dom ( ( ( cot ) * ( cot ) ) `| R7 ) ) implies ( ( ( ( cot ) * ( cot ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L656: R2 in ( dom ( ( ( cot ) * ( cot ) ) `| R7 ) );
L657: R2 in R7 by L656 , L654 , FDIFF_1:def 7;
L658: ( ( ( ( cot ) * ( cot ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( cot ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ) by L657 , L652 , FDIFF_10:3
.= ( R5 . R2 ) by L652 , L657;
thus L659: thesis by L658;
end;
L660: ( dom ( ( ( cot ) * ( cot ) ) `| R7 ) ) = ( dom R5 ) by L652 , L654 , FDIFF_1:def 7;
L661: ( ( ( cot ) * ( cot ) ) `| R7 ) = R5 by L660 , L655 , PARTFUN1:5;
thus L662: thesis by L661 , L652 , L653 , L654 , INTEGRA5:13;
end;
theorem
L663: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cot ) * ( tan ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cot ) * ( tan ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L664: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cot ) * ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L665: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L664 , INTEGRA5:10 , INTEGRA5:11;
L666: R7 c= ( dom ( - ( ( cot ) * ( tan ) ) ) ) by L664 , VALUED_1:8;
L667: ( ( cot ) * ( tan ) ) is_differentiable_on R7 by L664 , FDIFF_10:4;
L668: ( ( - 1 ) (#) ( ( cot ) * ( tan ) ) ) is_differentiable_on R7 by L667 , L666 , FDIFF_1:20;
L669: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) )))
proof
let R2 being Real;
assume L670: R2 in R7;
L671: ( ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cot ) * ( tan ) ) `| R7 ) ) . R2 ) by L667 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cot ) * ( tan ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( ( - ( 1 / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ) ) by L664 , L670 , FDIFF_10:4
.= ( ( 1 / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) );
thus L672: thesis by L671;
end;
L673: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) ) implies ( ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L674: R2 in ( dom ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) );
L675: R2 in R7 by L674 , L668 , FDIFF_1:def 7;
L676: ( ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( sin ) . ( ( tan ) . R2 ) ) ^2 ) ) * ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) ) by L675 , L669
.= ( R5 . R2 ) by L664 , L675;
thus L677: thesis by L676;
end;
L678: ( dom ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) ) = ( dom R5 ) by L664 , L668 , FDIFF_1:def 7;
L679: ( ( - ( ( cot ) * ( tan ) ) ) `| R7 ) = R5 by L678 , L673 , PARTFUN1:5;
thus L680: thesis by L679 , L664 , L665 , L668 , INTEGRA5:13;
end;
theorem
L681: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) + ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) - ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( tan ) - ( cot ) ) . ( upper_bound R4 ) ) - ( ( ( tan ) - ( cot ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L682: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) + ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) - ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L683: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L682 , INTEGRA5:10 , INTEGRA5:11;
L684: ( ( tan ) - ( cot ) ) is_differentiable_on R7 by L682 , FDIFF_10:5;
L685: (for R2 being Real holds (R2 in ( dom ( ( ( tan ) - ( cot ) ) `| R7 ) ) implies ( ( ( ( tan ) - ( cot ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L686: R2 in ( dom ( ( ( tan ) - ( cot ) ) `| R7 ) );
L687: R2 in R7 by L686 , L684 , FDIFF_1:def 7;
L688: ( ( ( ( tan ) - ( cot ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) + ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ) by L687 , L682 , FDIFF_10:5
.= ( R5 . R2 ) by L682 , L687;
thus L689: thesis by L688;
end;
L690: ( dom ( ( ( tan ) - ( cot ) ) `| R7 ) ) = ( dom R5 ) by L682 , L684 , FDIFF_1:def 7;
L691: ( ( ( tan ) - ( cot ) ) `| R7 ) = R5 by L690 , L685 , PARTFUN1:5;
thus L692: thesis by L691 , L682 , L683 , L684 , INTEGRA5:13;
end;
theorem
L693: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) - ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) + ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( tan ) + ( cot ) ) . ( upper_bound R4 ) ) - ( ( ( tan ) + ( cot ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L694: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) - ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( tan ) + ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L695: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L694 , INTEGRA5:10 , INTEGRA5:11;
L696: ( ( tan ) + ( cot ) ) is_differentiable_on R7 by L694 , FDIFF_10:6;
L697: (for R2 being Real holds (R2 in ( dom ( ( ( tan ) + ( cot ) ) `| R7 ) ) implies ( ( ( ( tan ) + ( cot ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L698: R2 in ( dom ( ( ( tan ) + ( cot ) ) `| R7 ) );
L699: R2 in R7 by L698 , L696 , FDIFF_1:def 7;
L700: ( ( ( ( tan ) + ( cot ) ) `| R7 ) . R2 ) = ( ( 1 / ( ( ( cos ) . R2 ) ^2 ) ) - ( 1 / ( ( ( sin ) . R2 ) ^2 ) ) ) by L699 , L694 , FDIFF_10:6
.= ( R5 . R2 ) by L694 , L699;
thus L701: thesis by L700;
end;
L702: ( dom ( ( ( tan ) + ( cot ) ) `| R7 ) ) = ( dom R5 ) by L694 , L696 , FDIFF_1:def 7;
L703: ( ( ( tan ) + ( cot ) ) `| R7 ) = R5 by L702 , L697 , PARTFUN1:5;
thus L704: thesis by L703 , L694 , L695 , L696 , INTEGRA5:13;
end;
theorem
L705: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( sin ) * ( sin ) ) . ( upper_bound R4 ) ) - ( ( ( sin ) * ( sin ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L706: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L707: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L706 , INTEGRA5:10 , INTEGRA5:11;
L708: ( ( sin ) * ( sin ) ) is_differentiable_on R7 by FDIFF_10:7;
L709: (for R2 being Real holds (R2 in ( dom ( ( ( sin ) * ( sin ) ) `| R7 ) ) implies ( ( ( ( sin ) * ( sin ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L710: R2 in ( dom ( ( ( sin ) * ( sin ) ) `| R7 ) );
L711: R2 in R7 by L710 , L708 , FDIFF_1:def 7;
L712: ( ( ( ( sin ) * ( sin ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ) by L711 , FDIFF_10:7
.= ( R5 . R2 ) by L706 , L711;
thus L713: thesis by L712;
end;
L714: ( dom ( ( ( sin ) * ( sin ) ) `| R7 ) ) = ( dom R5 ) by L706 , L708 , FDIFF_1:def 7;
L715: ( ( ( sin ) * ( sin ) ) `| R7 ) = R5 by L714 , L709 , PARTFUN1:5;
thus L716: thesis by L715 , L706 , L707 , L708 , INTEGRA5:13;
end;
theorem
L717: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( sin ) * ( cos ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( sin ) * ( cos ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L718: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L719: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L718 , INTEGRA5:10 , INTEGRA5:11;
L720: (( dom ( cos ) ) = ( REAL ) & ( rng ( cos ) ) c= ( dom ( cos ) ) & ( dom ( sin ) ) = ( dom ( cos ) )) by SIN_COS:24;
L721: ( dom ( ( sin ) * ( cos ) ) ) = ( REAL ) by L720 , RELAT_1:27;
L722: ( dom ( - ( ( sin ) * ( cos ) ) ) ) = ( REAL ) by L721 , VALUED_1:8;
L723: ( ( sin ) * ( cos ) ) is_differentiable_on R7 by FDIFF_10:8;
L724: ( ( - 1 ) (#) ( ( sin ) * ( cos ) ) ) is_differentiable_on R7 by L723 , L722 , FDIFF_1:20;
L725: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) )))
proof
let R2 being Real;
assume L726: R2 in R7;
L727: ( ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( sin ) * ( cos ) ) `| R7 ) ) . R2 ) by L723 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( sin ) * ( cos ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( cos ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ) ) ) by L726 , FDIFF_10:8
.= ( ( ( cos ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) );
thus L728: thesis by L727;
end;
L729: (for R2 being Real holds (R2 in ( dom ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) ) implies ( ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L730: R2 in ( dom ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) );
L731: R2 in R7 by L730 , L724 , FDIFF_1:def 7;
L732: ( ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ) by L731 , L725
.= ( R5 . R2 ) by L718 , L731;
thus L733: thesis by L732;
end;
L734: ( dom ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) ) = ( dom R5 ) by L718 , L724 , FDIFF_1:def 7;
L735: ( ( - ( ( sin ) * ( cos ) ) ) `| R7 ) = R5 by L734 , L729 , PARTFUN1:5;
thus L736: thesis by L735 , L718 , L719 , L724 , INTEGRA5:13;
end;
theorem
L737: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cos ) * ( sin ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cos ) * ( sin ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L738: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L739: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L738 , INTEGRA5:10 , INTEGRA5:11;
L740: ( dom ( sin ) ) = ( REAL ) by SIN_COS:24;
L741: (( rng ( sin ) ) c= ( dom ( sin ) ) & ( dom ( sin ) ) = ( dom ( cos ) )) by SIN_COS:24;
L742: ( dom ( ( cos ) * ( sin ) ) ) = ( REAL ) by L741 , L740 , RELAT_1:27;
L743: ( dom ( - ( ( cos ) * ( sin ) ) ) ) = ( REAL ) by L742 , VALUED_1:8;
L744: ( ( cos ) * ( sin ) ) is_differentiable_on R7 by FDIFF_10:9;
L745: ( ( - 1 ) (#) ( ( cos ) * ( sin ) ) ) is_differentiable_on R7 by L744 , L743 , FDIFF_1:20;
L746: (for R2 being Real holds (R2 in R7 implies ( ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) )))
proof
let R2 being Real;
assume L747: R2 in R7;
L748: ( ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( - 1 ) (#) ( ( ( cos ) * ( sin ) ) `| R7 ) ) . R2 ) by L744 , FDIFF_2:19
.= ( ( - 1 ) * ( ( ( ( cos ) * ( sin ) ) `| R7 ) . R2 ) ) by VALUED_1:6
.= ( ( - 1 ) * ( - ( ( ( sin ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ) ) ) by L747 , FDIFF_10:9
.= ( ( ( sin ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) );
thus L749: thesis by L748;
end;
L750: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) ) implies ( ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L751: R2 in ( dom ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) );
L752: R2 in R7 by L751 , L745 , FDIFF_1:def 7;
L753: ( ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( ( sin ) . R2 ) ) * ( ( cos ) . R2 ) ) by L752 , L746
.= ( R5 . R2 ) by L738 , L752;
thus L754: thesis by L753;
end;
L755: ( dom ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) ) = ( dom R5 ) by L738 , L745 , FDIFF_1:def 7;
L756: ( ( - ( ( cos ) * ( sin ) ) ) `| R7 ) = R5 by L755 , L750 , PARTFUN1:5;
thus L757: thesis by L756 , L738 , L739 , L745 , INTEGRA5:13;
end;
theorem
L758: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( cos ) * ( cos ) ) . ( upper_bound R4 ) ) - ( ( ( cos ) * ( cos ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L759: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ))) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L760: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L759 , INTEGRA5:10 , INTEGRA5:11;
L761: ( ( cos ) * ( cos ) ) is_differentiable_on R7 by FDIFF_10:10;
L762: (for R2 being Real holds (R2 in ( dom ( ( ( cos ) * ( cos ) ) `| R7 ) ) implies ( ( ( ( cos ) * ( cos ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L763: R2 in ( dom ( ( ( cos ) * ( cos ) ) `| R7 ) );
L764: R2 in R7 by L763 , L761 , FDIFF_1:def 7;
L765: ( ( ( ( cos ) * ( cos ) ) `| R7 ) . R2 ) = ( ( ( sin ) . ( ( cos ) . R2 ) ) * ( ( sin ) . R2 ) ) by L764 , FDIFF_10:10
.= ( R5 . R2 ) by L759 , L764;
thus L766: thesis by L765;
end;
L767: ( dom ( ( ( cos ) * ( cos ) ) `| R7 ) ) = ( dom R5 ) by L759 , L761 , FDIFF_1:def 7;
L768: ( ( ( cos ) * ( cos ) ) `| R7 ) = R5 by L767 , L762 , PARTFUN1:5;
thus L769: thesis by L768 , L759 , L760 , L761 , INTEGRA5:13;
end;
theorem
L770: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . R2 ) + ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cos ) (#) ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( - ( ( cos ) (#) ( cot ) ) ) . ( upper_bound R4 ) ) - ( ( - ( ( cos ) (#) ( cot ) ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L771: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( cos ) . R2 ) + ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( cos ) (#) ( cot ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L772: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L771 , INTEGRA5:10 , INTEGRA5:11;
L773: ( - ( ( cos ) (#) ( cot ) ) ) is_differentiable_on R7 by L771 , L180;
L774: (for R2 being Real holds (R2 in ( dom ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) ) implies ( ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L775: R2 in ( dom ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) );
L776: R2 in R7 by L775 , L773 , FDIFF_1:def 7;
L777: ( ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) . R2 ) = ( ( ( cos ) . R2 ) + ( ( ( cos ) . R2 ) / ( ( ( sin ) . R2 ) ^2 ) ) ) by L776 , L771 , L180
.= ( R5 . R2 ) by L771 , L776;
thus L778: thesis by L777;
end;
L779: ( dom ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) ) = ( dom R5 ) by L771 , L773 , FDIFF_1:def 7;
L780: ( ( - ( ( cos ) (#) ( cot ) ) ) `| R7 ) = R5 by L779 , L774 , PARTFUN1:5;
thus L781: thesis by L780 , L771 , L772 , L773 , INTEGRA5:13;
end;
theorem
L782: (for R4 being non  empty  closed_interval (Subset of ( REAL )) holds (for R5 being (PartFunc of ( REAL ) , ( REAL )) holds (for R7 being  open (Subset of ( REAL )) holds ((R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . R2 ) + ( ( ( sin ) . R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( sin ) (#) ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous) implies ( integral (R5 , R4) ) = ( ( ( ( sin ) (#) ( tan ) ) . ( upper_bound R4 ) ) - ( ( ( sin ) (#) ( tan ) ) . ( lower_bound R4 ) ) )))))
proof
let R4 being non  empty  closed_interval (Subset of ( REAL ));
let R5 being (PartFunc of ( REAL ) , ( REAL ));
let R7 being  open (Subset of ( REAL ));
assume L783: (R4 c= R7 & (for R2 being Real holds (R2 in R7 implies ( R5 . R2 ) = ( ( ( sin ) . R2 ) + ( ( ( sin ) . R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ))) & R7 c= ( dom ( ( sin ) (#) ( tan ) ) ) & R7 = ( dom R5 ) & ( R5 | R4 ) is  continuous);
L784: (R5 is_integrable_on R4 & ( R5 | R4 ) is  bounded) by L783 , INTEGRA5:10 , INTEGRA5:11;
L785: ( ( sin ) (#) ( tan ) ) is_differentiable_on R7 by L783 , FDIFF_10:12;
L786: (for R2 being Real holds (R2 in ( dom ( ( ( sin ) (#) ( tan ) ) `| R7 ) ) implies ( ( ( ( sin ) (#) ( tan ) ) `| R7 ) . R2 ) = ( R5 . R2 )))
proof
let R2 being Real;
assume L787: R2 in ( dom ( ( ( sin ) (#) ( tan ) ) `| R7 ) );
L788: R2 in R7 by L787 , L785 , FDIFF_1:def 7;
L789: ( ( ( ( sin ) (#) ( tan ) ) `| R7 ) . R2 ) = ( ( ( sin ) . R2 ) + ( ( ( sin ) . R2 ) / ( ( ( cos ) . R2 ) ^2 ) ) ) by L788 , L783 , FDIFF_10:12
.= ( R5 . R2 ) by L783 , L788;
thus L790: thesis by L789;
end;
L791: ( dom ( ( ( sin ) (#) ( tan ) ) `| R7 ) ) = ( dom R5 ) by L783 , L785 , FDIFF_1:def 7;
L792: ( ( ( sin ) (#) ( tan ) ) `| R7 ) = R5 by L791 , L786 , PARTFUN1:5;
thus L793: thesis by L792 , L783 , L784 , L785 , INTEGRA5:13;
end;
