:: The Axiomatization of Propositional Linear Time Temporal Logic
::  by Mariusz Giero
::
:: Received November 20, 2010
:: Copyright (c) 2010-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies FINSEQ_1, CARD_1, ORDINAL4, SUBSET_1, NUMBERS, ARYTM_3, TARSKI,
      RELAT_1, XBOOLE_0, FUNCT_1, QC_LANG1, XBOOLEAN, HILBERT1, MODELC_2,
      CQC_THE1, NAT_1, XXREAL_0, LTLAXIO1, ORDINAL1, ARYTM_1, ZF_LANG,
      PARTFUN1, MARGREL1, FUNCT_2, HILBERT2, ZFMISC_1, FUNCOP_1, ZF_MODEL,
      PBOOLE, GLIB_000;
 notations TARSKI, XBOOLE_0, ZFMISC_1, DOMAIN_1, SUBSET_1, RELAT_1, PARTFUN1,
      NUMBERS, XCMPLX_0, ORDINAL1, NAT_1, XXREAL_0, NAT_D, FUNCT_1, FUNCT_2,
      BINOP_1, FINSEQ_1, HILBERT1, HILBERT2, PBOOLE, XBOOLEAN, MARGREL1,
      AOFA_I00;
 constructors NAT_D, RELSET_1, AOFA_I00, HILBERT2, DOMAIN_1;
 registrations SUBSET_1, ORDINAL1, FUNCT_1, XXREAL_0, NAT_1, XBOOLEAN,
      RELSET_1, MARGREL1, XBOOLE_0, XREAL_0, FUNCT_2, HILBERT1;
 requirements NUMERALS, BOOLE, SUBSET, ARITHM, REAL;
 definitions XBOOLEAN, TARSKI, MARGREL1;
 theorems TARSKI, NAT_1, XBOOLE_0, XXREAL_0, FINSEQ_1, NAT_D, XBOOLEAN,
      FUNCT_2, PARTFUN1, XREAL_1, ZFMISC_1, ORDINAL1, FUNCOP_1, HILBERT2,
      BINOP_1, XREAL_0;
 schemes NAT_1, XBOOLE_0, FUNCT_2, FINSEQ_1, BINOP_1, HILBERT2;

begin
L1: (for B1 being set holds (for B2 being (FinSequence of B1) holds (for B3 being Nat holds ((1 <= B3 & B3 <= ( len B2 )) implies ( B2 . B3 ) = ( B2 /. B3 )))))
proof
let C1 being set;
let C2 being (FinSequence of C1);
let C3 being Nat;
assume L2: (1 <= C3 & C3 <= ( len C2 ));
L3: C3 in ( Seg ( len C2 ) ) by L2 , FINSEQ_1:1;
L4: C3 in ( dom C2 ) by L3 , FINSEQ_1:def 3;
thus L5: thesis by L4 , PARTFUN1:def 6;
end;
theorem
L6: (for R1 being  boolean number holds (for R2 being  boolean number holds (for R3 being  boolean number holds ( ( R1 => ( R2 '&' R3 ) ) => ( R1 => R2 ) ) = 1)))
proof
let R1 being  boolean number;
let R2 being  boolean number;
let R3 being  boolean number;
L7: (R2 = ( 0 ) or R2 = 1) by XBOOLEAN:def 3;
L8: (R1 = ( 0 ) or R1 = 1) by XBOOLEAN:def 3;
thus L9: ( ( R1 => ( R2 '&' R3 ) ) => ( R1 => R2 ) ) = 1 by L8 , L7;
end;
theorem
L10: (for R1 being  boolean number holds (for R2 being  boolean number holds (for R3 being  boolean number holds ( ( R1 => ( R2 => R3 ) ) => ( ( R1 '&' R2 ) => R3 ) ) = 1)))
proof
let R1 being  boolean number;
let R2 being  boolean number;
let R3 being  boolean number;
L11: (R1 = ( 0 ) or R1 = 1) by XBOOLEAN:def 3;
L12: (R2 = ( 0 ) or R2 = 1) by XBOOLEAN:def 3;
L13: (R3 = ( 0 ) or R3 = 1) by XBOOLEAN:def 3;
thus L14: thesis by L13 , L11 , L12;
end;
theorem
L15: (for R1 being  boolean number holds (for R2 being  boolean number holds (for R3 being  boolean number holds ( ( ( R1 '&' R2 ) => R3 ) => ( R1 => ( R2 => R3 ) ) ) = 1)))
proof
let R1 being  boolean number;
let R2 being  boolean number;
let R3 being  boolean number;
L16: (R1 = ( 0 ) or R1 = 1) by XBOOLEAN:def 3;
L17: (R2 = ( 0 ) or R2 = 1) by XBOOLEAN:def 3;
L18: (R3 = ( 0 ) or R3 = 1) by XBOOLEAN:def 3;
thus L19: thesis by L18 , L16 , L17;
end;
begin
notation
synonym LTLB_WFF for HP-WFF;
end;
notation
synonym TFALSUM for VERUM;
end;
notation
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
synonym R4 'Us' R5 for R4 '&' R5;
end;
theorem
L23: (for R8 being (Element of ( LTLB_WFF )) holds (R8 = ( TFALSUM ) or (ex R18 being (Element of ( NAT )) st (R8 = ( prop R18 ) or (ex R4 being (Element of ( LTLB_WFF )) st (ex R5 being (Element of ( LTLB_WFF )) st (R8 = ( R4 => R5 ) or (ex R4 being (Element of ( LTLB_WFF )) st (ex R5 being (Element of ( LTLB_WFF )) st R8 = ( R4 'Us' R5 ))))))))))
proof
let R8 being (Element of ( LTLB_WFF ));
L24: (R8 = ( VERUM ) or R8 is  simple or R8 is  conjunctive or R8 is  conditional) by HILBERT2:9;
thus L25: thesis by L24 , HILBERT2:def 6 , HILBERT2:def 7 , HILBERT2:def 8;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
func 'not' R4 -> (Element of ( LTLB_WFF )) equals 
( R4 => ( TFALSUM ) );
correctness;
func 'X' R4 -> (Element of ( LTLB_WFF )) equals 
( ( TFALSUM ) 'Us' R4 );
correctness;
end;
definition
func TVERUM -> (Element of ( LTLB_WFF )) equals 
( 'not' ( TFALSUM ) );
correctness;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
func R4 '&&' R5 -> (Element of ( LTLB_WFF )) equals 
( ( R4 => ( R5 => ( TFALSUM ) ) ) => ( TFALSUM ) );
correctness;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
func R4 'or' R5 -> (Element of ( LTLB_WFF )) equals 
( 'not' ( ( 'not' R4 ) '&&' ( 'not' R5 ) ) );
correctness;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
func 'G' R4 -> (Element of ( LTLB_WFF )) equals 
( 'not' ( ( 'not' R4 ) 'or' ( ( TVERUM ) '&&' ( ( TVERUM ) 'Us' ( 'not' R4 ) ) ) ) );
correctness;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
func 'F' R4 -> (Element of ( LTLB_WFF )) equals 
( 'not' ( 'G' ( 'not' R4 ) ) );
correctness;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
func R4 'U' R5 -> (Element of ( LTLB_WFF )) equals 
( R5 'or' ( R4 '&&' ( R4 'Us' R5 ) ) );
correctness;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
func R4 'R' R5 -> (Element of ( LTLB_WFF )) equals 
( 'not' ( ( 'not' R4 ) 'U' ( 'not' R5 ) ) );
correctness;
end;
begin
definition
func props -> (Subset of ( LTLB_WFF )) means 
(for B4 being set holds (B4 in it iff (ex B5 being (Element of ( NAT )) st B4 = ( prop B5 ))));
existence
proof
defpred S1[ set ] means (ex B6 being (Element of ( NAT )) st $1 = ( prop B6 ));
consider C4 being set such that L34: (for B7 being set holds (B7 in C4 iff (B7 in ( LTLB_WFF ) & S1[ B7 ]))) from XBOOLE_0:sch 1;
L35: C4 c= ( LTLB_WFF )
proof
let C5 being set;
assume L36: C5 in C4;
thus L37: thesis by L36 , L34;
end;
reconsider D1 = C4 as (Subset of ( LTLB_WFF )) by L35;
take D1;
thus L38: (for B8 being set holds (B8 in D1 iff (ex B9 being (Element of ( NAT )) st B8 = ( prop B9 )))) by L34;
end;
uniqueness
proof
let C6 , C7 being (Subset of ( LTLB_WFF ));
assume that
L39: (for B10 being set holds (B10 in C6 iff (ex B11 being (Element of ( NAT )) st B10 = ( prop B11 ))))
and
L40: (for B12 being set holds (B12 in C7 iff (ex B13 being (Element of ( NAT )) st B12 = ( prop B13 ))));
L41: C7 c= C6
proof
let C8 being set;
assume L42: C8 in C7;
consider C9 being (Element of ( NAT )) such that L43: C8 = ( prop C9 ) by L42 , L40;
thus L44: C8 in C6 by L39 , L43;
end;
L45: C6 c= C7
proof
let C10 being set;
assume L46: C10 in C6;
consider C11 being (Element of ( NAT )) such that L47: C10 = ( prop C11 ) by L46 , L39;
thus L48: C10 in C7 by L40 , L47;
end;
thus L49: C6 = C7 by L45 , L41 , XBOOLE_0:def 10;
end;
end;
definition
mode LTLModel
 is (sequence of ( bool ( props ) ));
end;
definition
let C12 being LTLModel;
func SAT C12 -> (Function of [: ( NAT ) , ( LTLB_WFF ) :] , ( BOOLEAN )) means 
:L52: (for R18 being (Element of ( NAT )) holds (( it . [ R18 , ( TFALSUM ) ] ) = ( 0 ) & (for R17 being (Element of ( NAT )) holds (( it . [ R18 , ( prop R17 ) ] ) = 1 iff ( prop R17 ) in ( C12 . R18 ))) & (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (( it . [ R18 , ( R4 => R5 ) ] ) = ( ( it . [ R18 , R4 ] ) => ( it . [ R18 , R5 ] ) ) & (( it . [ R18 , ( R4 'Us' R5 ) ] ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( it . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( it . [ ( R18 + R16 ) , R4 ] ) = 1))))))))));
existence
proof
set D2 = ( Funcs (( NAT ) , ( BOOLEAN )) );
defpred S2[ (Element of ( LTLB_WFF )) , (Element of ( LTLB_WFF )) , set , set , set ] means ((($3 is (sequence of ( BOOLEAN )) & $4 is (sequence of ( BOOLEAN ))) implies (ex B14 , B15 , B16 being (sequence of ( BOOLEAN )) st (B14 = $3 & B15 = $4 & B16 = $5 & (for R18 being (Element of ( NAT )) holds ( B16 . R18 ) = ( ( B14 . R18 ) => ( B15 . R18 ) ))))) & ((not ($3 is (sequence of ( BOOLEAN )) & $4 is (sequence of ( BOOLEAN )))) implies $5 = ( ( NAT ) --> ( FALSE ) )));
defpred S3[ (Element of ( LTLB_WFF )) , (Element of ( LTLB_WFF )) , set , set , set ] means ((($3 is (sequence of ( BOOLEAN )) & $4 is (sequence of ( BOOLEAN ))) implies (ex B17 , B18 , B19 being (sequence of ( BOOLEAN )) st (B17 = $3 & B18 = $4 & B19 = $5 & (for R18 being (Element of ( NAT )) holds (( B19 . R18 ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( B18 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( B17 . ( R18 + R16 ) ) = 1))))))))) & ((not ($3 is (sequence of ( BOOLEAN )) & $4 is (sequence of ( BOOLEAN )))) implies $5 = ( ( NAT ) --> ( FALSE ) )));
defpred S4[ (Element of ( NAT )) , Function ] means (for R18 being (Element of ( NAT )) holds (( $2 . R18 ) = 1 iff ( prop $1 ) in ( C12 . R18 )));
L53: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for B20 , B21 being set holds (ex B22 being set st S3[ R4 , R5 , B20 , B21 , B22 ]))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let C13 , C14 being set;
per cases ;
suppose L54: (C13 is (sequence of ( BOOLEAN )) & C14 is (sequence of ( BOOLEAN )));

reconsider D3 = C13 , D4 = C14 as (sequence of ( BOOLEAN )) by L54;
defpred S5[ (Element of ( NAT )) , (Element of ( BOOLEAN )) ] means ($2 = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( D4 . ( $1 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D3 . ( $1 + R16 ) ) = 1)))));
L55:
now
let R18 being (Element of ( NAT ));
per cases ;
suppose L56: (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( D4 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D3 . ( R18 + R16 ) ) = 1))));

thus L57: (ex B23 being (Element of ( BOOLEAN )) st S5[ R18 , B23 ]) by L56;
end;
suppose L58: (not (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( D4 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D3 . ( R18 + R16 ) ) = 1)))));

L59: S5[ R18 , ( FALSE ) ] by L58;
thus L60: (ex B24 being (Element of ( BOOLEAN )) st S5[ R18 , B24 ]) by L59;
end;
end;
consider C15 being (Function of ( NAT ) , ( BOOLEAN )) such that L62: (for R18 being (Element of ( NAT )) holds S5[ R18 , ( C15 . R18 ) ]) from FUNCT_2:sch 3(L55);
thus L63: thesis by L62;
end;
suppose L64: (not (C13 is (sequence of ( BOOLEAN )) & C14 is (sequence of ( BOOLEAN ))));

thus L65: thesis by L64;
end;
end;
L67: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for B25 , B26 , B27 , B28 being set holds ((S3[ R4 , R5 , B25 , B26 , B27 ] & S3[ R4 , R5 , B25 , B26 , B28 ]) implies B27 = B28))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let C16 , C17 , C18 , C19 being set;
assume that
L68: S3[ R4 , R5 , C16 , C17 , C18 ]
and
L69: S3[ R4 , R5 , C16 , C17 , C19 ];
per cases ;
suppose L70: (C16 is (sequence of ( BOOLEAN )) & C17 is (sequence of ( BOOLEAN )));

consider C20 , C21 , C22 being (sequence of ( BOOLEAN )) such that L71: (C20 = C16 & C21 = C17) and L72: C22 = C19 and L73: (for R18 being (Element of ( NAT )) holds (( C22 . R18 ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C21 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C20 . ( R18 + R16 ) ) = 1)))))) by L70 , L69;
consider C23 , C24 , C25 being (sequence of ( BOOLEAN )) such that L74: (C23 = C16 & C24 = C17) and L75: C25 = C18 and L76: (for R18 being (Element of ( NAT )) holds (( C25 . R18 ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C24 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C23 . ( R18 + R16 ) ) = 1)))))) by L68 , L70;
L77:
now
let C26 being set;
assume L78: C26 in ( NAT );
reconsider D5 = C26 as (Element of ( NAT )) by L78;
per cases  by XBOOLEAN:def 3;
suppose L79: ( C25 . D5 ) = 1;

L80: (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C21 . ( D5 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C20 . ( D5 + R16 ) ) = 1)))) by L79 , L74 , L76 , L71;
thus L81: ( C25 . C26 ) = ( C22 . C26 ) by L80 , L73 , L79;
end;
suppose L82: ( C25 . D5 ) = ( 0 );

L83: (not (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C21 . ( D5 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C20 . ( D5 + R16 ) ) = 1))))) by L82 , L74 , L76 , L71;
L84: (not ( C22 . D5 ) = 1) by L83 , L73;
thus L85: ( C25 . C26 ) = ( C22 . C26 ) by L84 , L82 , XBOOLEAN:def 3;
end;
end;
thus L87: C18 = C19 by L77 , L75 , L72 , FUNCT_2:12;
end;
suppose L88: (not (C16 is (sequence of ( BOOLEAN )) & C17 is (sequence of ( BOOLEAN ))));

thus L89: C18 = C19 by L88 , L68 , L69;
end;
end;
L91: (for B29 being (Element of ( NAT )) holds (ex B30 being (Element of ( Funcs (( NAT ) , ( BOOLEAN )) )) st S4[ B29 , B30 ]))
proof
let C27 being (Element of ( NAT ));
defpred S6[ (Element of ( NAT )) , (Element of ( BOOLEAN )) ] means ($2 = 1 iff ( prop C27 ) in ( C12 . $1 ));
L92:
now
let C28 being (Element of ( NAT ));
per cases ;
suppose L93: ( prop C27 ) in ( C12 . C28 );

L94: S6[ C28 , ( TRUE ) ] by L93;
thus L95: (ex B31 being (Element of ( BOOLEAN )) st S6[ C28 , B31 ]) by L94;
end;
suppose L96: (not ( prop C27 ) in ( C12 . C28 ));

L97: S6[ C28 , ( FALSE ) ] by L96;
thus L98: (ex B32 being (Element of ( BOOLEAN )) st S6[ C28 , B32 ]) by L97;
end;
end;
consider C29 being (Function of ( NAT ) , ( BOOLEAN )) such that L100: (for R18 being (Element of ( NAT )) holds S6[ R18 , ( C29 . R18 ) ]) from FUNCT_2:sch 3(L92);
reconsider D6 = C29 as (Element of ( Funcs (( NAT ) , ( BOOLEAN )) )) by FUNCT_2:8;
L101: S4[ C27 , D6 ] by L100;
thus L102: (ex B33 being (Element of ( Funcs (( NAT ) , ( BOOLEAN )) )) st S4[ C27 , B33 ]) by L101;
end;
consider C30 being (Function of ( NAT ) , ( Funcs (( NAT ) , ( BOOLEAN )) )) such that L103: (for R17 being (Element of ( NAT )) holds S4[ R17 , ( C30 . R17 ) ]) from FUNCT_2:sch 3(L91);
L104: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for B34 , B35 , B36 , B37 being set holds ((S2[ R4 , R5 , B34 , B35 , B36 ] & S2[ R4 , R5 , B34 , B35 , B37 ]) implies B36 = B37))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let C31 , C32 , C33 , C34 being set;
assume that
L105: S2[ R4 , R5 , C31 , C32 , C33 ]
and
L106: S2[ R4 , R5 , C31 , C32 , C34 ];
per cases ;
suppose L107: (C31 is (sequence of ( BOOLEAN )) & C32 is (sequence of ( BOOLEAN )));

consider C35 , C36 , C37 being (sequence of ( BOOLEAN )) such that L108: C35 = C31 and L109: C36 = C32 and L110: C37 = C34 and L111: (for R18 being (Element of ( NAT )) holds ( C37 . R18 ) = ( ( C35 . R18 ) => ( C36 . R18 ) )) by L107 , L106;
consider C38 , C39 , C40 being (sequence of ( BOOLEAN )) such that L112: C38 = C31 and L113: C39 = C32 and L114: C40 = C33 and L115: (for R18 being (Element of ( NAT )) holds ( C40 . R18 ) = ( ( C38 . R18 ) => ( C39 . R18 ) )) by L105 , L107;
L116:
now
let C41 being set;
assume L117: C41 in ( NAT );
reconsider D7 = C41 as (Element of ( NAT )) by L117;
thus L118: ( C40 . C41 ) = ( ( C35 . D7 ) => ( C39 . D7 ) ) by L112 , L115 , L108
.= ( C37 . C41 ) by L113 , L109 , L111;
end;
thus L119: C33 = C34 by L116 , L114 , L110 , FUNCT_2:12;
end;
suppose L120: (not (C31 is (sequence of ( BOOLEAN )) & C32 is (sequence of ( BOOLEAN ))));

thus L121: C33 = C34 by L120 , L105 , L106;
end;
end;
deffunc H1((Element of ( NAT ))) = ( C30 . $1 );
L123: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for B38 , B39 being set holds (ex B40 being set st S2[ R4 , R5 , B38 , B39 , B40 ]))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let C42 , C43 being set;
per cases ;
suppose L124: (C42 is (sequence of ( BOOLEAN )) & C43 is (sequence of ( BOOLEAN )));

reconsider D8 = C42 , D9 = C43 as (sequence of ( BOOLEAN )) by L124;
deffunc H2((Element of ( NAT ))) = ( 'not' ( ( D8 . $1 ) '&' ( 'not' ( D9 . $1 ) ) ) );
consider C44 being (Function of ( NAT ) , ( BOOLEAN )) such that L125: (for R18 being (Element of ( NAT )) holds ( C44 . R18 ) = H2(R18)) from FUNCT_2:sch 4;
L126: (for R18 being (Element of ( NAT )) holds ( C44 . R18 ) = ( ( D8 . R18 ) => ( D9 . R18 ) )) by L125;
thus L127: thesis by L126;
end;
suppose L128: (not (C42 is (sequence of ( BOOLEAN )) & C43 is (sequence of ( BOOLEAN ))));

thus L129: thesis by L128;
end;
end;
consider C45 being (ManySortedSet of ( LTLB_WFF )) such that L131: (( C45 . ( TFALSUM ) ) = ( ( NAT ) --> ( FALSE ) ) & (for R18 being (Element of ( NAT )) holds ( C45 . ( prop R18 ) ) = H1(R18)) & (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (S3[ R4 , R5 , ( C45 . R4 ) , ( C45 . R5 ) , ( C45 . ( R4 'Us' R5 ) ) ] & S2[ R4 , R5 , ( C45 . R4 ) , ( C45 . R5 ) , ( C45 . ( R4 => R5 ) ) ])))) from HILBERT2:sch 3(L53 , L123 , L67 , L104);
L132:
now
L133:
now
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
L134: S2[ R8 , R9 , ( C45 . R8 ) , ( C45 . R9 ) , ( C45 . ( R8 => R9 ) ) ] by L131;
per cases ;
suppose L135: (( C45 . R8 ) is (sequence of ( BOOLEAN )) & ( C45 . R9 ) is (sequence of ( BOOLEAN )));

consider C46 , C47 , C48 being (sequence of ( BOOLEAN )) such that L136: C46 = ( C45 . R8 ) and L137: C47 = ( C45 . R9 ) and L138: C48 = ( C45 . ( R8 => R9 ) ) and L139: (for R18 being (Element of ( NAT )) holds ( C48 . R18 ) = ( ( C46 . R18 ) => ( C47 . R18 ) )) by L135 , L131;
thus L140: ( C45 . ( R8 => R9 ) ) in D2 by L138 , FUNCT_2:8;
end;
suppose L141: (not (( C45 . R8 ) is (sequence of ( BOOLEAN )) & ( C45 . R9 ) is (sequence of ( BOOLEAN ))));

thus L142: ( C45 . ( R8 => R9 ) ) in D2 by L134 , FUNCT_2:8;
end;
end;
L144:
now
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
L145: S3[ R8 , R9 , ( C45 . R8 ) , ( C45 . R9 ) , ( C45 . ( R8 'Us' R9 ) ) ] by L131;
per cases ;
suppose L146: (( C45 . R8 ) is (sequence of ( BOOLEAN )) & ( C45 . R9 ) is (sequence of ( BOOLEAN )));

consider C49 , C50 , C51 being (sequence of ( BOOLEAN )) such that L147: C49 = ( C45 . R8 ) and L148: C50 = ( C45 . R9 ) and L149: C51 = ( C45 . ( R8 'Us' R9 ) ) and L150: (for R18 being (Element of ( NAT )) holds (( C51 . R18 ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C50 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C49 . ( R18 + R16 ) ) = 1)))))) by L146 , L131;
thus L151: ( C45 . ( R8 'Us' R9 ) ) in D2 by L149 , FUNCT_2:8;
end;
suppose L152: (not (( C45 . R8 ) is (sequence of ( BOOLEAN )) & ( C45 . R9 ) is (sequence of ( BOOLEAN ))));

thus L153: ( C45 . ( R8 'Us' R9 ) ) in D2 by L145 , FUNCT_2:8;
end;
end;
let C52 being set;
assume L155: C52 in ( LTLB_WFF );
reconsider D10 = C52 as (Element of ( LTLB_WFF )) by L155;
L156:
now
let R18 being (Element of ( NAT ));
L157: ( C45 . ( prop R18 ) ) = ( C30 . R18 ) by L131;
thus L158: ( C45 . ( prop R18 ) ) in D2 by L157;
end;
per cases  by L23;
suppose L159: D10 = ( TFALSUM );

thus L160: ( C45 . C52 ) in D2 by L159 , L131 , FUNCT_2:8;
end;
suppose L161: (ex B41 being (Element of ( NAT )) st D10 = ( prop B41 ));

thus L162: ( C45 . C52 ) in D2 by L161 , L156;
end;
suppose L163: (ex B42 , B43 being (Element of ( LTLB_WFF )) st D10 = ( B42 'Us' B43 ));

thus L164: ( C45 . C52 ) in D2 by L163 , L144;
end;
suppose L165: (ex B44 , B45 being (Element of ( LTLB_WFF )) st D10 = ( B44 => B45 ));

thus L166: ( C45 . C52 ) in D2 by L165 , L133;
end;
end;
L168: ( dom C45 ) = ( LTLB_WFF ) by PARTFUN1:def 2;
reconsider D11 = C45 as (Function of ( LTLB_WFF ) , ( Funcs (( NAT ) , ( BOOLEAN )) )) by L168 , L132 , FUNCT_2:3;
deffunc H3((Element of ( NAT )) , (Element of ( LTLB_WFF ))) = ( ( D11 . $2 ) . $1 );
consider C53 being (Function of [: ( NAT ) , ( LTLB_WFF ) :] , ( BOOLEAN )) such that L169: (for R18 being (Element of ( NAT )) holds (for R8 being (Element of ( LTLB_WFF )) holds ( C53 . (R18 , R8) ) = H3(R18 , R8))) from BINOP_1:sch 4;
L170:
now
let R8 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
thus L171: ( C53 . [ R18 , R8 ] ) = ( C53 . (R18 , R8) ) by BINOP_1:def 1
.= ( ( D11 . R8 ) . R18 ) by L169;
end;
L172:
now
let R17 being (Element of ( NAT ));
let R18 being (Element of ( NAT ));
L173: ( C53 . [ R18 , ( prop R17 ) ] ) = ( ( D11 . ( prop R17 ) ) . R18 ) by L170
.= ( ( C30 . R17 ) . R18 ) by L131;
thus L174: (( C53 . [ R18 , ( prop R17 ) ] ) = 1 iff ( prop R17 ) in ( C12 . R18 )) by L173 , L103;
end;
L175:
now
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
reconsider D12 = ( D11 . R4 ) , D13 = ( D11 . R5 ) as (sequence of ( BOOLEAN )) by FUNCT_2:66;
consider C54 , C55 , C56 being (sequence of ( BOOLEAN )) such that L176: C54 = D12 and L177: C55 = D13 and L178: C56 = ( D11 . ( R4 'Us' R5 ) ) and L179: (for R18 being (Element of ( NAT )) holds (( C56 . R18 ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C55 . ( R18 + R15 ) ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C54 . ( R18 + R16 ) ) = 1)))))) by L131;
consider C57 , C58 , C59 being (sequence of ( BOOLEAN )) such that L180: C57 = D12 and L181: C58 = D13 and L182: (C59 = ( D11 . ( R4 => R5 ) ) & (for R18 being (Element of ( NAT )) holds ( C59 . R18 ) = ( ( C57 . R18 ) => ( C58 . R18 ) ))) by L131;
thus L183: ( C53 . [ R18 , ( R4 => R5 ) ] ) = ( ( D11 . ( R4 => R5 ) ) . R18 ) by L170
.= ( ( ( D11 . R4 ) . R18 ) => ( C58 . R18 ) ) by L180 , L182
.= ( ( C53 . [ R18 , R4 ] ) => ( ( D11 . R5 ) . R18 ) ) by L170 , L181
.= ( ( C53 . [ R18 , R4 ] ) => ( C53 . [ R18 , R5 ] ) ) by L170;
thus L184: (( C53 . [ R18 , ( R4 'Us' R5 ) ] ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C53 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C53 . [ ( R18 + R16 ) , R4 ] ) = 1)))))
proof
thus L185:now
assume L186: ( C53 . [ R18 , ( R4 'Us' R5 ) ] ) = 1;
L187: ( C56 . R18 ) = 1 by L186 , L170 , L178;
consider R15 being (Element of ( NAT )) such that L188: ( 0 ) < R15 and L189: ( C55 . ( R18 + R15 ) ) = 1 and L190: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C54 . ( R18 + R16 ) ) = 1)) by L187 , L179;
L191:
now
let R16 being (Element of ( NAT ));
assume L192: (1 <= R16 & R16 < R15);
thus L193: ( C53 . [ ( R18 + R16 ) , R4 ] ) = ( ( D11 . R4 ) . ( R18 + R16 ) ) by L170
.= 1 by L176 , L190 , L192;
end;
L194: ( C53 . [ ( R18 + R15 ) , R5 ] ) = 1 by L170 , L177 , L189;
thus L195: (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C53 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C53 . [ ( R18 + R16 ) , R4 ] ) = 1)))) by L194 , L188 , L191;
end;
assume L196: (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C53 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C53 . [ ( R18 + R16 ) , R4 ] ) = 1))));
consider R15 being (Element of ( NAT )) such that L197: ( 0 ) < R15 and L198: ( C53 . [ ( R18 + R15 ) , R5 ] ) = 1 and L199: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C53 . [ ( R18 + R16 ) , R4 ] ) = 1)) by L196;
L200: ( C55 . ( R18 + R15 ) ) = 1 by L170 , L177 , L198;
L201: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C54 . ( R18 + R16 ) ) = 1))
proof
let R16 being (Element of ( NAT ));
assume L202: (1 <= R16 & R16 < R15);
thus L203: ( C54 . ( R18 + R16 ) ) = ( C53 . [ ( R18 + R16 ) , R4 ] ) by L170 , L176
.= 1 by L199 , L202;
end;
thus L204: ( C53 . [ R18 , ( R4 'Us' R5 ) ] ) = ( C56 . R18 ) by L170 , L178
.= 1 by L179 , L197 , L200 , L201;
end;

end;
take C53;
L185:
now
let R18 being (Element of ( NAT ));
thus L186: ( C53 . [ R18 , ( TFALSUM ) ] ) = ( ( D11 . ( TFALSUM ) ) . R18 ) by L170
.= ( 0 ) by L131 , FUNCOP_1:7;
end;
thus L187: thesis by L185 , L172 , L175;
end;
uniqueness
proof
let C60 , C61 being (Function of [: ( NAT ) , ( LTLB_WFF ) :] , ( BOOLEAN ));
assume L188: (for B46 being (Element of ( NAT )) holds (( C60 . [ B46 , ( TFALSUM ) ] ) = ( 0 ) & (for R17 being (Element of ( NAT )) holds (( C60 . [ B46 , ( prop R17 ) ] ) = 1 iff ( prop R17 ) in ( C12 . B46 ))) & (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (( C60 . [ B46 , ( R4 => R5 ) ] ) = ( ( C60 . [ B46 , R4 ] ) => ( C60 . [ B46 , R5 ] ) ) & (( C60 . [ B46 , ( R4 'Us' R5 ) ] ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C60 . [ ( B46 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C60 . [ ( B46 + R16 ) , R4 ] ) = 1))))))))));
assume L189: (for B47 being (Element of ( NAT )) holds (( C61 . [ B47 , ( TFALSUM ) ] ) = ( 0 ) & (for R17 being (Element of ( NAT )) holds (( C61 . [ B47 , ( prop R17 ) ] ) = 1 iff ( prop R17 ) in ( C12 . B47 ))) & (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (( C61 . [ B47 , ( R4 => R5 ) ] ) = ( ( C61 . [ B47 , R4 ] ) => ( C61 . [ B47 , R5 ] ) ) & (( C61 . [ B47 , ( R4 'Us' R5 ) ] ) = 1 iff (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C61 . [ ( B47 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C61 . [ ( B47 + R16 ) , R4 ] ) = 1))))))))));
thus L190: C60 = C61
proof
defpred S7[ (Element of ( LTLB_WFF )) ] means (for B48 being (Element of ( NAT )) holds ( C60 . [ B48 , $1 ] ) = ( C61 . [ B48 , $1 ] ));
L191: (for B49 being (Element of ( NAT )) holds S7[ ( prop B49 ) ])
proof
let C62 being (Element of ( NAT ));
L192:
now
let C63 being (Element of ( NAT ));
per cases ;
suppose L193: ( prop C62 ) in ( C12 . C63 );

thus L194: ( C60 . [ C63 , ( prop C62 ) ] ) = 1 by L193 , L188
.= ( C61 . [ C63 , ( prop C62 ) ] ) by L189 , L193;
end;
suppose L195: (not ( prop C62 ) in ( C12 . C63 ));

L196: (not ( C60 . [ C63 , ( prop C62 ) ] ) = 1) by L195 , L188;
L197: ( C60 . [ C63 , ( prop C62 ) ] ) = ( 0 ) by L196 , XBOOLEAN:def 3;
L198: (not ( C61 . [ C63 , ( prop C62 ) ] ) = 1) by L189 , L195;
thus L199: ( C60 . [ C63 , ( prop C62 ) ] ) = ( C61 . [ C63 , ( prop C62 ) ] ) by L198 , L197 , XBOOLEAN:def 3;
end;
end;
thus L201: S7[ ( prop C62 ) ] by L192;
end;
L202: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds ((S7[ R4 ] & S7[ R5 ]) implies (S7[ ( R4 'Us' R5 ) ] & S7[ ( R4 => R5 ) ]))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
assume that
L203: S7[ R4 ]
and
L204: S7[ R5 ];
thus L205: S7[ ( R4 'Us' R5 ) ]
proof
let R18 being (Element of ( NAT ));
per cases ;
suppose L206: (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C60 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C60 . [ ( R18 + R16 ) , R4 ] ) = 1))));

consider R15 being (Element of ( NAT )) such that L207: ( 0 ) < R15 and L208: ( C60 . [ ( R18 + R15 ) , R5 ] ) = 1 and L209: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C60 . [ ( R18 + R16 ) , R4 ] ) = 1)) by L206;
L210: ( C61 . [ ( R18 + R15 ) , R5 ] ) = 1 by L204 , L208;
L211:
now
let R16 being (Element of ( NAT ));
assume L212: (1 <= R16 & R16 < R15);
L213: ( C60 . [ ( R18 + R16 ) , R4 ] ) = 1 by L212 , L209;
thus L214: ( C61 . [ ( R18 + R16 ) , R4 ] ) = 1 by L213 , L203;
end;
thus L215: ( C60 . [ R18 , ( R4 'Us' R5 ) ] ) = 1 by L188 , L206
.= ( C61 . [ R18 , ( R4 'Us' R5 ) ] ) by L189 , L207 , L210 , L211;
end;
suppose L216: (not (ex R15 being (Element of ( NAT )) st (( 0 ) < R15 & ( C60 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C60 . [ ( R18 + R16 ) , R4 ] ) = 1)))));

L217:
now
let R15 being (Element of ( NAT ));
per cases  by L216;
suppose L218: (not ( 0 ) < R15);

thus L219: (not (( 0 ) < R15 & ( C61 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C61 . [ ( R18 + R16 ) , R4 ] ) = 1)))) by L218;
end;
suppose L220: (not ( C60 . [ ( R18 + R15 ) , R5 ] ) = 1);

thus L221: (not (( 0 ) < R15 & ( C61 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C61 . [ ( R18 + R16 ) , R4 ] ) = 1)))) by L220 , L204;
end;
suppose L222: (not (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C60 . [ ( R18 + R16 ) , R4 ] ) = 1)));

consider R16 being (Element of ( NAT )) such that L223: (1 <= R16 & R16 < R15) and L224: (not ( C60 . [ ( R18 + R16 ) , R4 ] ) = 1) by L222;
L225: (not ( C61 . [ ( R18 + R16 ) , R4 ] ) = 1) by L203 , L224;
thus L226: (not (( 0 ) < R15 & ( C61 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( C61 . [ ( R18 + R16 ) , R4 ] ) = 1)))) by L225 , L223;
end;
end;
L228: (not ( C61 . [ R18 , ( R4 'Us' R5 ) ] ) = 1) by L217 , L189;
L229: (not ( C60 . [ R18 , ( R4 'Us' R5 ) ] ) = 1) by L188 , L216;
L230: ( C60 . [ R18 , ( R4 'Us' R5 ) ] ) = ( 0 ) by L229 , XBOOLEAN:def 3;
thus L231: ( C60 . [ R18 , ( R4 'Us' R5 ) ] ) = ( C61 . [ R18 , ( R4 'Us' R5 ) ] ) by L230 , L228 , XBOOLEAN:def 3;
end;
end;

thus L233: S7[ ( R4 => R5 ) ]
proof
let C64 being (Element of ( NAT ));
thus L234: ( C60 . [ C64 , ( R4 => R5 ) ] ) = ( ( C60 . [ C64 , R4 ] ) => ( C60 . [ C64 , R5 ] ) ) by L188
.= ( ( C61 . [ C64 , R4 ] ) => ( C60 . [ C64 , R5 ] ) ) by L203
.= ( ( C61 . [ C64 , R4 ] ) => ( C61 . [ C64 , R5 ] ) ) by L204
.= ( C61 . [ C64 , ( R4 => R5 ) ] ) by L189;
end;

end;
L234:
now
let C65 being (Element of ( NAT ));
thus L235: ( C60 . [ C65 , ( TFALSUM ) ] ) = ( 0 ) by L188
.= ( C61 . [ C65 , ( TFALSUM ) ] ) by L189;
end;
L236: S7[ ( TFALSUM ) ] by L234;
L237: (for R8 being (Element of ( LTLB_WFF )) holds S7[ R8 ]) from HILBERT2:sch 2(L236 , L191 , L202);
L238: (for B50 being (Element of [: ( NAT ) , ( LTLB_WFF ) :]) holds (B50 in ( dom C60 ) implies ( C60 . B50 ) = ( C61 . B50 )))
proof
let C66 being (Element of [: ( NAT ) , ( LTLB_WFF ) :]);
consider C67 , C68 being set such that L239: C67 in ( NAT ) and L240: C68 in ( LTLB_WFF ) and L241: C66 = [ C67 , C68 ] by ZFMISC_1:def 2;
reconsider D14 = C67 as (Element of ( NAT )) by L239;
assume L242: C66 in ( dom C60 );
thus L243: ( C60 . C66 ) = ( C61 . C66 ) by L237 , L239 , L240 , L241;
reconsider D15 = C68 as (Element of ( LTLB_WFF )) by L240;
end;
L245: ( dom C60 ) = [: ( NAT ) , ( LTLB_WFF ) :] by FUNCT_2:def 1
.= ( dom C61 ) by FUNCT_2:def 1;
thus L246: thesis by L245 , L238 , PARTFUN1:5;
end;

end;
end;
theorem
L192: (for R8 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( 'not' R8 ) ] ) = 1 iff ( ( SAT R23 ) . [ R18 , R8 ] ) = ( 0 )))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
thus L193:now
assume L194: ( ( SAT R23 ) . [ R18 , ( 'not' R8 ) ] ) = 1;
L195: ( ( ( SAT R23 ) . [ R18 , R8 ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) = 1 by L194 , L52;
L196: (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 or ( ( SAT R23 ) . [ R18 , R8 ] ) = ( 0 )) by XBOOLEAN:def 3;
thus L197: ( ( SAT R23 ) . [ R18 , R8 ] ) = ( 0 ) by L196 , L195 , L52;
end;
assume L198: ( ( SAT R23 ) . [ R18 , R8 ] ) = ( 0 );
thus L199: ( ( SAT R23 ) . [ R18 , ( 'not' R8 ) ] ) = ( ( ( SAT R23 ) . [ R18 , R8 ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) by L52
.= 1 by L198;
end;
theorem
L200: (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( TVERUM ) ] ) = 1))
proof
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
assume L201: (not ( ( SAT R23 ) . [ R18 , ( TVERUM ) ] ) = 1);
L202: (not ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) = ( 0 )) by L201 , L192;
thus L203: contradiction by L202 , L52;
end;
theorem
L204: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( R8 '&&' R9 ) ] ) = 1 iff (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 & ( ( SAT R23 ) . [ R18 , R9 ] ) = 1))))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
thus L205:now
assume L206: ( ( SAT R23 ) . [ R18 , ( R8 '&&' R9 ) ] ) = 1;
L207: ( ( ( SAT R23 ) . [ R18 , ( R8 => ( R9 => ( TFALSUM ) ) ) ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) = 1 by L206 , L52;
L208: ( ( ( SAT R23 ) . [ R18 , ( R8 => ( R9 => ( TFALSUM ) ) ) ] ) => ( FALSE ) ) = 1 by L207 , L52;
L209: ( ( ( SAT R23 ) . [ R18 , R8 ] ) => ( ( SAT R23 ) . [ R18 , ( R9 => ( TFALSUM ) ) ] ) ) = ( 0 ) by L208 , L52;
L210: ( ( ( SAT R23 ) . [ R18 , R8 ] ) => ( ( ( SAT R23 ) . [ R18 , R9 ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) ) = ( 0 ) by L209 , L52;
L211: ( ( ( SAT R23 ) . [ R18 , R8 ] ) => ( ( ( SAT R23 ) . [ R18 , R9 ] ) => ( FALSE ) ) ) = ( 0 ) by L210 , L52;
L212: (( ( SAT R23 ) . [ R18 , R8 ] ) = ( 0 ) or ( ( SAT R23 ) . [ R18 , R8 ] ) = 1) by XBOOLEAN:def 3;
thus L213: (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 & ( ( SAT R23 ) . [ R18 , R9 ] ) = 1) by L212 , L211;
end;
assume that
L214: ( ( SAT R23 ) . [ R18 , R8 ] ) = 1
and
L215: ( ( SAT R23 ) . [ R18 , R9 ] ) = 1;
L216: ( ( ( SAT R23 ) . [ R18 , R9 ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) = ( 0 ) by L215 , L52;
L217: ( ( ( SAT R23 ) . [ R18 , R8 ] ) => ( ( SAT R23 ) . [ R18 , ( R9 => ( TFALSUM ) ) ] ) ) = ( 0 ) by L216 , L214 , L52;
L218: ( ( SAT R23 ) . [ R18 , ( R8 => ( R9 => ( TFALSUM ) ) ) ] ) = ( 0 ) by L217 , L52;
L219: ( ( ( SAT R23 ) . [ R18 , ( R8 => ( R9 => ( TFALSUM ) ) ) ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) = 1 by L218;
thus L220: ( ( SAT R23 ) . [ R18 , ( R8 '&&' R9 ) ] ) = 1 by L219 , L52;
end;
theorem
L221: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( R8 'or' R9 ) ] ) = 1 iff (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 or ( ( SAT R23 ) . [ R18 , R9 ] ) = 1))))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
thus L222:now
assume L223: ( ( SAT R23 ) . [ R18 , ( R8 'or' R9 ) ] ) = 1;
L224: ( ( SAT R23 ) . [ R18 , ( ( 'not' R8 ) '&&' ( 'not' R9 ) ) ] ) = ( 0 ) by L223 , L192;
per cases  by L224 , L204;
suppose L225: (not ( ( SAT R23 ) . [ R18 , ( 'not' R8 ) ] ) = 1);

L226: (not ( ( SAT R23 ) . [ R18 , R8 ] ) = ( 0 )) by L225 , L192;
thus L227: (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 or ( ( SAT R23 ) . [ R18 , R9 ] ) = 1) by L226 , XBOOLEAN:def 3;
end;
suppose L228: (not ( ( SAT R23 ) . [ R18 , ( 'not' R9 ) ] ) = 1);

L229: (not ( ( SAT R23 ) . [ R18 , R9 ] ) = ( 0 )) by L228 , L192;
thus L230: (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 or ( ( SAT R23 ) . [ R18 , R9 ] ) = 1) by L229 , XBOOLEAN:def 3;
end;
end;
assume L232: (( ( SAT R23 ) . [ R18 , R8 ] ) = 1 or ( ( SAT R23 ) . [ R18 , R9 ] ) = 1);
per cases  by L232;
suppose L233: ( ( SAT R23 ) . [ R18 , R8 ] ) = 1;

L234: (not ( ( SAT R23 ) . [ R18 , ( 'not' R8 ) ] ) = 1) by L233 , L192;
L235: (not ( ( SAT R23 ) . [ R18 , ( ( 'not' R8 ) '&&' ( 'not' R9 ) ) ] ) = 1) by L234 , L204;
L236: ( ( SAT R23 ) . [ R18 , ( ( 'not' R8 ) '&&' ( 'not' R9 ) ) ] ) = ( 0 ) by L235 , XBOOLEAN:def 3;
thus L237: thesis by L236 , L192;
end;
suppose L238: ( ( SAT R23 ) . [ R18 , R9 ] ) = 1;

L239: (not ( ( SAT R23 ) . [ R18 , ( 'not' R9 ) ] ) = 1) by L238 , L192;
L240: (not ( ( SAT R23 ) . [ R18 , ( ( 'not' R8 ) '&&' ( 'not' R9 ) ) ] ) = 1) by L239 , L204;
L241: ( ( SAT R23 ) . [ R18 , ( ( 'not' R8 ) '&&' ( 'not' R9 ) ) ] ) = ( 0 ) by L240 , XBOOLEAN:def 3;
thus L242: thesis by L241 , L192;
end;
end;
theorem
L244: (for R8 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( 'X' R8 ) ] ) = ( ( SAT R23 ) . [ ( R18 + 1 ) , R8 ] ))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D16 = ( TFALSUM );
set D17 = ( SAT R23 );
per cases  by XBOOLEAN:def 3;
suppose L245: ( ( SAT R23 ) . [ R18 , ( D16 'Us' R8 ) ] ) = 1;

consider R15 being (Element of ( NAT )) such that L246: (( 0 ) < R15 & ( D17 . [ ( R18 + R15 ) , R8 ] ) = 1) and L247: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D17 . [ ( R18 + R16 ) , D16 ] ) = 1)) by L245 , L52;
L248:
now
assume L249: 1 < R15;
L250: (not ( D17 . [ ( R18 + 1 ) , D16 ] ) = 1) by L52;
thus L251: contradiction by L250 , L247 , L249;
end;
thus L252: thesis by L248 , L245 , L246 , NAT_1:25;
end;
suppose L253: ( ( SAT R23 ) . [ R18 , ( D16 'Us' R8 ) ] ) = ( 0 );

L254:
now
assume L255: ( D17 . [ ( R18 + 1 ) , R8 ] ) = 1;
L256: ((not ( 0 ) < 1) or (not ( D17 . [ ( R18 + 1 ) , R8 ] ) = 1) or (not (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < 1) implies ( D17 . [ ( R18 + R16 ) , D16 ] ) = 1)))) by L253 , L52;
thus L257: contradiction by L256 , L255;
end;
thus L258: thesis by L254 , L253 , XBOOLEAN:def 3;
end;
end;
theorem
L260: (for R8 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( 'G' R8 ) ] ) = 1 iff (for R15 being (Element of ( NAT )) holds ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = 1)))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D18 = ( TFALSUM );
set D19 = ( TVERUM );
set D20 = ( SAT R23 );
thus L261:now
assume L262: ( D20 . [ R18 , ( 'G' R8 ) ] ) = 1;
L263: ( D20 . [ R18 , ( ( 'not' R8 ) 'or' ( D19 '&&' ( D19 'Us' ( 'not' R8 ) ) ) ) ] ) = ( 0 ) by L262 , L192;
L264: (not ( D20 . [ R18 , ( 'not' R8 ) ] ) = 1) by L263 , L221;
L265: (not ( D20 . [ R18 , R8 ] ) = ( 0 )) by L264 , L192;
let R15 being (Element of ( NAT ));
L266: (not ( D20 . [ R18 , ( D19 '&&' ( D19 'Us' ( 'not' R8 ) ) ) ] ) = 1) by L263 , L221;
L267: ((not ( D20 . [ R18 , D19 ] ) = 1) or (not ( D20 . [ R18 , ( D19 'Us' ( 'not' R8 ) ) ] ) = 1)) by L266 , L204;
per cases ;
suppose L268: R15 = ( 0 );

thus L269: ( D20 . [ ( R18 + R15 ) , R8 ] ) = 1 by L268 , L265 , XBOOLEAN:def 3;
end;
suppose L270: ( 0 ) < R15;

L271: ((not ( D20 . [ ( R18 + R15 ) , ( 'not' R8 ) ] ) = 1) or (ex R16 being (Element of ( NAT )) st (1 <= R16 & R16 < R15 & (not ( D20 . [ ( R18 + R16 ) , D19 ] ) = 1)))) by L270 , L267 , L52 , L200;
L272: (not ( D20 . [ ( R18 + R15 ) , R8 ] ) = ( 0 )) by L271 , L192 , L200;
thus L273: ( D20 . [ ( R18 + R15 ) , R8 ] ) = 1 by L272 , XBOOLEAN:def 3;
end;
end;
assume L275: (for R15 being (Element of ( NAT )) holds ( D20 . [ ( R18 + R15 ) , R8 ] ) = 1);
L276:
now
assume L277: ( D20 . [ R18 , ( 'G' R8 ) ] ) = ( 0 );
L278: (not ( D20 . [ R18 , ( ( 'not' R8 ) 'or' ( D19 '&&' ( D19 'Us' ( 'not' R8 ) ) ) ) ] ) = ( 0 )) by L277 , L192;
L279: ( D20 . [ R18 , ( ( 'not' R8 ) 'or' ( D19 '&&' ( D19 'Us' ( 'not' R8 ) ) ) ) ] ) = 1 by L278 , XBOOLEAN:def 3;
per cases  by L279 , L221;
suppose L280: ( D20 . [ R18 , ( 'not' R8 ) ] ) = 1;

L281: ( D20 . [ ( R18 + ( 0 ) ) , R8 ] ) = ( 0 ) by L280 , L192;
thus L282: contradiction by L281 , L275;
end;
suppose L283: ( D20 . [ R18 , ( D19 '&&' ( D19 'Us' ( 'not' R8 ) ) ) ] ) = 1;

L284: ( D20 . [ R18 , ( D19 'Us' ( 'not' R8 ) ) ] ) = 1 by L283 , L204;
consider R15 being (Element of ( NAT )) such that L285: ( 0 ) < R15 and L286: ( D20 . [ ( R18 + R15 ) , ( 'not' R8 ) ] ) = 1 and L287: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D20 . [ ( R18 + R16 ) , D19 ] ) = 1)) by L284 , L52;
L288: ( D20 . [ ( R18 + R15 ) , R8 ] ) = ( 0 ) by L286 , L192;
thus L289: contradiction by L288 , L275;
end;
end;
thus L291: ( D20 . [ R18 , ( 'G' R8 ) ] ) = 1 by L276 , XBOOLEAN:def 3;
end;
theorem
L292: (for R8 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( 'F' R8 ) ] ) = 1 iff (ex R15 being (Element of ( NAT )) st ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = 1)))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
thus L293:now
assume L294: ( ( SAT R23 ) . [ R18 , ( 'F' R8 ) ] ) = 1;
L295: ( ( SAT R23 ) . [ R18 , ( 'G' ( 'not' R8 ) ) ] ) = ( 0 ) by L294 , L192;
consider R15 being (Element of ( NAT )) such that L296: (not ( ( SAT R23 ) . [ ( R18 + R15 ) , ( 'not' R8 ) ] ) = 1) by L295 , L260;
L297: (not ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = ( 0 )) by L296 , L192;
L298: ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = 1 by L297 , XBOOLEAN:def 3;
thus L299: (ex R15 being (Element of ( NAT )) st ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = 1) by L298;
end;
assume L300: (ex R15 being (Element of ( NAT )) st ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = 1);
consider R15 being (Element of ( NAT )) such that L301: ( ( SAT R23 ) . [ ( R18 + R15 ) , R8 ] ) = 1 by L300;
L302: (not ( ( SAT R23 ) . [ ( R18 + R15 ) , ( 'not' R8 ) ] ) = 1) by L301 , L192;
L303: (not ( ( SAT R23 ) . [ R18 , ( 'G' ( 'not' R8 ) ) ] ) = 1) by L302 , L260;
L304: ( ( SAT R23 ) . [ R18 , ( 'G' ( 'not' R8 ) ) ] ) = ( 0 ) by L303 , XBOOLEAN:def 3;
thus L305: ( ( SAT R23 ) . [ R18 , ( 'F' R8 ) ] ) = 1 by L304 , L192;
end;
theorem
L306: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( R4 'U' R5 ) ] ) = 1 iff (ex R15 being (Element of ( NAT )) st (( ( SAT R23 ) . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 < R15 implies ( ( SAT R23 ) . [ ( R18 + R16 ) , R4 ] ) = 1)))))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D21 = ( SAT R23 );
thus L307:now
assume L308: ( D21 . [ R18 , ( R4 'U' R5 ) ] ) = 1;
per cases  by L308 , L221;
suppose L309: ( D21 . [ R18 , R5 ] ) = 1;

L310: (for R16 being (Element of ( NAT )) holds (R16 < ( 0 ) implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1));
L311: ( D21 . [ ( R18 + ( 0 ) ) , R5 ] ) = 1 by L309;
thus L312: (ex R15 being (Element of ( NAT )) st (( D21 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 < R15 implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1)))) by L311 , L310;
end;
suppose L313: ( D21 . [ R18 , ( R4 '&&' ( R4 'Us' R5 ) ) ] ) = 1;

L314: ( D21 . [ R18 , ( R4 'Us' R5 ) ] ) = 1 by L313 , L204;
consider R15 being (Element of ( NAT )) such that L315: ( 0 ) < R15 and L316: ( D21 . [ ( R18 + R15 ) , R5 ] ) = 1 and L317: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1)) by L314 , L52;
L318:
now
let R16 being (Element of ( NAT ));
assume L319: R16 < R15;
per cases ;
suppose L320: R16 = ( 0 );

thus L321: ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1 by L320 , L313 , L204;
end;
suppose L322: (not R16 = ( 0 ));

L323: 1 <= R16 by L322 , NAT_1:25;
thus L324: ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1 by L323 , L317 , L319;
end;
end;
thus L326: (ex R15 being (Element of ( NAT )) st (( D21 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 < R15 implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1)))) by L318 , L316;
end;
end;
assume L328: (ex R15 being (Element of ( NAT )) st (( D21 . [ ( R18 + R15 ) , R5 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 < R15 implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1))));
consider R15 being (Element of ( NAT )) such that L329: ( D21 . [ ( R18 + R15 ) , R5 ] ) = 1 and L330: (for R16 being (Element of ( NAT )) holds (R16 < R15 implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1)) by L328;
per cases ;
suppose L331: R15 = ( 0 );

thus L332: ( D21 . [ R18 , ( R4 'U' R5 ) ] ) = 1 by L331 , L329 , L221;
end;
suppose L333: (not R15 = ( 0 ));

L334: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D21 . [ ( R18 + R16 ) , R4 ] ) = 1)) by L330;
L335: ( D21 . [ R18 , ( R4 'Us' R5 ) ] ) = 1 by L334 , L329 , L333 , L52;
L336: ( D21 . [ ( R18 + ( 0 ) ) , R4 ] ) = 1 by L330 , L333;
L337: ( D21 . [ R18 , ( R4 '&&' ( R4 'Us' R5 ) ) ] ) = 1 by L336 , L335 , L204;
thus L338: ( D21 . [ R18 , ( R4 'U' R5 ) ] ) = 1 by L337 , L221;
end;
end;
theorem
L340: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (( ( SAT R23 ) . [ R18 , ( R4 'R' R5 ) ] ) = 1 iff ((ex R15 being (Element of ( NAT )) st (( ( SAT R23 ) . [ ( R18 + R15 ) , R4 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( ( SAT R23 ) . [ ( R18 + R16 ) , R5 ] ) = 1)))) or (for R15 being (Element of ( NAT )) holds ( ( SAT R23 ) . [ ( R18 + R15 ) , R5 ] ) = 1)))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D22 = ( SAT R23 );
set D23 = ( 'not' R4 );
set D24 = ( 'not' R5 );
thus L341: (( D22 . [ R18 , ( R4 'R' R5 ) ] ) = 1 implies ((ex R15 being (Element of ( NAT )) st (( D22 . [ ( R18 + R15 ) , R4 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1)))) or (for R15 being (Element of ( NAT )) holds ( D22 . [ ( R18 + R15 ) , R5 ] ) = 1)))
proof
defpred S8[ Nat ] means (( D22 . [ ( R18 + $1 ) , R5 ] ) = 1 & ( D22 . [ ( R18 + $1 ) , R4 ] ) = ( 0 ));
assume L342: ( D22 . [ R18 , ( R4 'R' R5 ) ] ) = 1;
L343: ( D22 . [ R18 , ( ( 'not' R4 ) 'U' ( 'not' R5 ) ) ] ) = ( 0 ) by L342 , L192;
L344:
now
let C69 being Nat;
reconsider D25 = C69 as (Element of ( NAT )) by ORDINAL1:def 12;
per cases  by L343 , L306;
suppose L345: (not ( D22 . [ ( R18 + D25 ) , ( 'not' R5 ) ] ) = 1);

thus L346: ((not ( D22 . [ ( R18 + C69 ) , ( 'not' R5 ) ] ) = 1) or (ex B51 being Nat st (B51 < C69 & (not ( D22 . [ ( R18 + B51 ) , ( 'not' R4 ) ] ) = 1)))) by L345;
end;
suppose L347: (ex R16 being (Element of ( NAT )) st (R16 < C69 & (not ( D22 . [ ( R18 + R16 ) , ( 'not' R4 ) ] ) = 1)));

thus L348: ((not ( D22 . [ ( R18 + C69 ) , ( 'not' R5 ) ] ) = 1) or (ex B52 being Nat st (B52 < C69 & (not ( D22 . [ ( R18 + B52 ) , ( 'not' R4 ) ] ) = 1)))) by L347;
end;
end;
assume that
L350: (not (ex R15 being (Element of ( NAT )) st (( D22 . [ ( R18 + R15 ) , R4 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1)))))
and
L351: (not (for R15 being (Element of ( NAT )) holds ( D22 . [ ( R18 + R15 ) , R5 ] ) = 1));
L352:
now
let C70 being Nat;
reconsider D26 = C70 as (Element of ( NAT )) by ORDINAL1:def 12;
L353: ((not ( D22 . [ ( R18 + D26 ) , R4 ] ) = 1) or (ex R16 being (Element of ( NAT )) st (R16 <= D26 & (not ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1)))) by L350;
thus L354: ((not ( D22 . [ ( R18 + C70 ) , R4 ] ) = 1) or (ex B53 being Nat st (B53 <= C70 & (not ( D22 . [ ( R18 + B53 ) , R5 ] ) = 1)))) by L353;
end;
L355: (for B54 being Nat holds ((for B55 being Nat holds (B55 < B54 implies S8[ B55 ])) implies S8[ B54 ]))
proof
let C71 being Nat;
assume L356: (for B56 being Nat holds (B56 < C71 implies S8[ B56 ]));
L357:
now
assume L358: (ex B57 being Nat st (B57 < C71 & (not ( D22 . [ ( R18 + B57 ) , ( 'not' R4 ) ] ) = 1)));
consider C72 being Nat such that L359: C72 < C71 and L360: (not ( D22 . [ ( R18 + C72 ) , ( 'not' R4 ) ] ) = 1) by L358;
L361: (not ( D22 . [ ( R18 + C72 ) , R4 ] ) = ( 0 )) by L360 , L192;
thus L362: contradiction by L361 , L356 , L359;
end;
L363: (not ( D22 . [ ( R18 + C71 ) , ( 'not' R5 ) ] ) = 1) by L357 , L344;
L364: (not ( D22 . [ ( R18 + C71 ) , R5 ] ) = ( 0 )) by L363 , L192;
L365: ( D22 . [ ( R18 + C71 ) , R5 ] ) = 1 by L364 , XBOOLEAN:def 3;
L366:
now
assume L367: (ex B58 being Nat st (B58 <= C71 & (not ( D22 . [ ( R18 + B58 ) , R5 ] ) = 1)));
consider C73 being Nat such that L368: C73 <= C71 and L369: (not ( D22 . [ ( R18 + C73 ) , R5 ] ) = 1) by L367;
per cases ;
suppose L370: C73 < C71;

thus L371: contradiction by L370 , L356 , L369;
end;
suppose L372: (not C73 < C71);

thus L373: contradiction by L372 , L365 , L368 , L369 , XXREAL_0:1;
end;
end;
L375: (not ( D22 . [ ( R18 + C71 ) , R4 ] ) = 1) by L366 , L352;
thus L376: S8[ C71 ] by L375 , L364 , XBOOLEAN:def 3;
end;
L377: (for B59 being Nat holds S8[ B59 ]) from NAT_1:sch 4(L355);
thus L378: contradiction by L377 , L351;
end;

thus L379: (((ex R15 being (Element of ( NAT )) st (( D22 . [ ( R18 + R15 ) , R4 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1)))) or (for R15 being (Element of ( NAT )) holds ( D22 . [ ( R18 + R15 ) , R5 ] ) = 1)) implies ( D22 . [ R18 , ( R4 'R' R5 ) ] ) = 1)
proof
assume L380: ((ex R15 being (Element of ( NAT )) st (( D22 . [ ( R18 + R15 ) , R4 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1)))) or (for R15 being (Element of ( NAT )) holds ( D22 . [ ( R18 + R15 ) , R5 ] ) = 1));
assume L381: (not ( D22 . [ R18 , ( R4 'R' R5 ) ] ) = 1);
L382: (not ( D22 . [ R18 , ( D23 'U' D24 ) ] ) = ( 0 )) by L381 , L192;
L383: ( D22 . [ R18 , ( D23 'U' D24 ) ] ) = 1 by L382 , XBOOLEAN:def 3;
per cases  by L380;
suppose L384: (ex R15 being (Element of ( NAT )) st (( D22 . [ ( R18 + R15 ) , R4 ] ) = 1 & (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1))));

consider R15 being (Element of ( NAT )) such that L385: ( D22 . [ ( R18 + R15 ) , R4 ] ) = 1 and L386: (for R16 being (Element of ( NAT )) holds (R16 <= R15 implies ( D22 . [ ( R18 + R16 ) , R5 ] ) = 1)) by L384;
consider R17 being (Element of ( NAT )) such that L387: ( D22 . [ ( R18 + R17 ) , D24 ] ) = 1 and L388: (for R16 being (Element of ( NAT )) holds (R16 < R17 implies ( D22 . [ ( R18 + R16 ) , D23 ] ) = 1)) by L383 , L306;
per cases ;
suppose L389: R17 <= R15;

L390: ( D22 . [ ( R18 + R17 ) , R5 ] ) = 1 by L389 , L386;
thus L391: contradiction by L390 , L387 , L192;
end;
suppose L392: (not R17 <= R15);

L393: ( D22 . [ ( R18 + R15 ) , D23 ] ) = 1 by L392 , L388;
thus L394: contradiction by L393 , L385 , L192;
end;
end;
suppose L396: (for R15 being (Element of ( NAT )) holds ( D22 . [ ( R18 + R15 ) , R5 ] ) = 1);

consider R15 being (Element of ( NAT )) such that L397: ( D22 . [ ( R18 + R15 ) , D24 ] ) = 1 and L398: (for R16 being (Element of ( NAT )) holds (R16 < R15 implies ( D22 . [ ( R18 + R16 ) , D23 ] ) = 1)) by L383 , L306;
L399: ( D22 . [ ( R18 + R15 ) , R5 ] ) = ( 0 ) by L397 , L192;
thus L400: contradiction by L399 , L396;
end;
end;

end;
theorem
L380: (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) = ( ( SAT R23 ) . [ R18 , ( 'X' ( 'not' R9 ) ) ] ))))
proof
let R9 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
thus L381: ( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'X' R9 ) ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) by L52
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) => ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) ) by L244
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) => ( FALSE ) ) by L52
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) => ( ( SAT R23 ) . [ ( R18 + 1 ) , ( TFALSUM ) ] ) ) by L52
.= ( ( SAT R23 ) . [ ( R18 + 1 ) , ( R9 => ( TFALSUM ) ) ] ) by L52
.= ( ( SAT R23 ) . [ R18 , ( 'X' ( 'not' R9 ) ) ] ) by L244;
end;
theorem
L382: (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( 'not' ( 'X' R9 ) ) => ( 'X' ( 'not' R9 ) ) ) ] ) = 1)))
proof
let R9 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
L383: (( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) = ( 0 ) or ( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) = 1) by XBOOLEAN:def 3;
thus L384: ( ( SAT R23 ) . [ R18 , ( ( 'not' ( 'X' R9 ) ) => ( 'X' ( 'not' R9 ) ) ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) => ( ( SAT R23 ) . [ R18 , ( 'X' ( 'not' R9 ) ) ] ) ) by L52
.= 1 by L383 , L380;
end;
theorem
L385: (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( 'X' ( 'not' R9 ) ) => ( 'not' ( 'X' R9 ) ) ) ] ) = 1)))
proof
let R9 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
L386: (( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) = ( 0 ) or ( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) = 1) by XBOOLEAN:def 3;
thus L387: ( ( SAT R23 ) . [ R18 , ( ( 'X' ( 'not' R9 ) ) => ( 'not' ( 'X' R9 ) ) ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'X' ( 'not' R9 ) ) ] ) => ( ( SAT R23 ) . [ R18 , ( 'not' ( 'X' R9 ) ) ] ) ) by L52
.= 1 by L386 , L380;
end;
theorem
L388: (for R9 being (Element of ( LTLB_WFF )) holds (for R10 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( 'X' ( R9 => R10 ) ) => ( ( 'X' R9 ) => ( 'X' R10 ) ) ) ] ) = 1))))
proof
let R9 being (Element of ( LTLB_WFF ));
let R10 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
L389: (( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) = ( 0 ) or ( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) = 1) by XBOOLEAN:def 3;
L390: (( ( SAT R23 ) . [ ( R18 + 1 ) , R10 ] ) = ( 0 ) or ( ( SAT R23 ) . [ ( R18 + 1 ) , R10 ] ) = 1) by XBOOLEAN:def 3;
thus L391: ( ( SAT R23 ) . [ R18 , ( ( 'X' ( R9 => R10 ) ) => ( ( 'X' R9 ) => ( 'X' R10 ) ) ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'X' ( R9 => R10 ) ) ] ) => ( ( SAT R23 ) . [ R18 , ( ( 'X' R9 ) => ( 'X' R10 ) ) ] ) ) by L52
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , ( R9 => R10 ) ] ) => ( ( SAT R23 ) . [ R18 , ( ( 'X' R9 ) => ( 'X' R10 ) ) ] ) ) by L244
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , ( R9 => R10 ) ] ) => ( ( ( SAT R23 ) . [ R18 , ( 'X' R9 ) ] ) => ( ( SAT R23 ) . [ R18 , ( 'X' R10 ) ] ) ) ) by L52
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , ( R9 => R10 ) ] ) => ( ( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) => ( ( SAT R23 ) . [ R18 , ( 'X' R10 ) ] ) ) ) by L244
.= ( ( ( SAT R23 ) . [ ( R18 + 1 ) , ( R9 => R10 ) ] ) => ( ( ( SAT R23 ) . [ ( R18 + 1 ) , R9 ] ) => ( ( SAT R23 ) . [ ( R18 + 1 ) , R10 ] ) ) ) by L244
.= 1 by L389 , L390 , L52;
end;
theorem
L392: (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( 'G' R9 ) => ( R9 '&&' ( 'X' ( 'G' R9 ) ) ) ) ] ) = 1)))
proof
let R9 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
L393: ( ( SAT R23 ) . [ R18 , ( ( 'G' R9 ) => ( R9 '&&' ( 'X' ( 'G' R9 ) ) ) ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'G' R9 ) ] ) => ( ( SAT R23 ) . [ R18 , ( R9 '&&' ( 'X' ( 'G' R9 ) ) ) ] ) ) by L52;
per cases  by XBOOLEAN:def 3;
suppose L394: ( ( SAT R23 ) . [ R18 , ( 'G' R9 ) ] ) = ( 0 );

thus L395: thesis by L394 , L393;
end;
suppose L396: ( ( SAT R23 ) . [ R18 , ( 'G' R9 ) ] ) = 1;

L397:
now
let C74 being (Element of ( NAT ));
L398: ( ( SAT R23 ) . [ ( R18 + ( C74 + 1 ) ) , R9 ] ) = 1 by L396 , L260;
thus L399: ( ( SAT R23 ) . [ ( ( R18 + 1 ) + C74 ) , R9 ] ) = 1 by L398;
end;
L400: ( ( SAT R23 ) . [ ( R18 + 1 ) , ( 'G' R9 ) ] ) = 1 by L397 , L260;
L401: ( ( SAT R23 ) . [ R18 , ( 'X' ( 'G' R9 ) ) ] ) = 1 by L400 , L244;
L402: ( ( SAT R23 ) . [ ( R18 + ( 0 ) ) , R9 ] ) = 1 by L396 , L260;
L403: ( ( SAT R23 ) . [ R18 , ( R9 '&&' ( 'X' ( 'G' R9 ) ) ) ] ) = 1 by L402 , L401 , L204;
thus L404: thesis by L403 , L393;
end;
end;
theorem
L406: (for R9 being (Element of ( LTLB_WFF )) holds (for R10 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( R9 'Us' R10 ) => ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ) ] ) = 1))))
proof
let R9 being (Element of ( LTLB_WFF ));
let R10 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D27 = ( SAT R23 );
L407:
now
assume that
L408: ( D27 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) = ( 0 )
and
L409: ( D27 . [ R18 , ( R9 'Us' R10 ) ] ) = 1;
consider R15 being (Element of ( NAT )) such that L410: ( 0 ) < R15 and L411: ( D27 . [ ( R18 + R15 ) , R10 ] ) = 1 and L412: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D27 . [ ( R18 + R16 ) , R9 ] ) = 1)) by L409 , L52;
L413: (not ( D27 . [ R18 , ( 'X' R10 ) ] ) = 1) by L408 , L221;
L414: (not ( D27 . [ R18 , ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ] ) = 1) by L408 , L221;
L415: ( D27 . [ R18 , ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ] ) = ( 0 ) by L414 , XBOOLEAN:def 3;
L416: ( D27 . [ ( R18 + 1 ) , ( R9 '&&' ( R9 'Us' R10 ) ) ] ) = ( 0 ) by L415 , L244;
per cases  by L410 , NAT_1:25;
suppose L417: R15 = 1;

thus L418: contradiction by L417 , L411 , L413 , L244;
end;
suppose L419: R15 > 1;

L420:
now
let R16 being (Element of ( NAT ));
assume that
L421: 1 <= R16
and
L422: R16 < ( R15 -' 1 );
L423: ( R16 + 1 ) < ( ( R15 -' 1 ) + 1 ) by L422 , XREAL_1:8;
L424: ( R16 + 1 ) < ( ( R15 - 1 ) + 1 ) by L423 , L422 , XREAL_0:def 2;
L425: 1 <= ( R16 + 1 ) by L421 , NAT_1:19;
L426: ( D27 . [ ( R18 + ( R16 + 1 ) ) , R9 ] ) = 1 by L425 , L412 , L424;
thus L427: ( D27 . [ ( ( R18 + 1 ) + R16 ) , R9 ] ) = 1 by L426;
end;
L428: ((not ( D27 . [ ( R18 + 1 ) , R9 ] ) = 1) or (not ( D27 . [ ( R18 + 1 ) , ( R9 'Us' R10 ) ] ) = 1)) by L416 , L204;
L429: ( R15 + ( - 1 ) ) > ( 1 + ( - 1 ) ) by L419 , XREAL_1:8;
L430: ( R18 + R15 ) = ( ( R18 + 1 ) + ( R15 - 1 ) )
.= ( ( R18 + 1 ) + ( R15 -' 1 ) ) by L429 , XREAL_0:def 2;
thus L431: contradiction by L430 , L411 , L412 , L419 , L429 , L420 , L428 , L52;
end;
end;
L433: (( D27 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) = ( 0 ) or ( D27 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) = 1) by XBOOLEAN:def 3;
L434: ( ( D27 . [ R18 , ( R9 'Us' R10 ) ] ) => ( D27 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) ) = 1 by L433 , L407 , XBOOLEAN:def 3;
thus L435: thesis by L434 , L52;
end;
theorem
L436: (for R9 being (Element of ( LTLB_WFF )) holds (for R10 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) => ( R9 'Us' R10 ) ) ] ) = 1))))
proof
let R9 being (Element of ( LTLB_WFF ));
let R10 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D28 = ( SAT R23 );
L437:
now
assume that
L438: ( D28 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) = 1
and
L439: ( D28 . [ R18 , ( R9 'Us' R10 ) ] ) = ( 0 );
per cases  by L438 , L221;
suppose L440: ( D28 . [ R18 , ( 'X' R10 ) ] ) = 1;

L441: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < 1) implies ( D28 . [ ( R18 + R16 ) , R9 ] ) = 1));
L442: ( D28 . [ ( R18 + 1 ) , R10 ] ) = 1 by L440 , L244;
thus L443: contradiction by L442 , L439 , L441 , L52;
end;
suppose L444: ( D28 . [ R18 , ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ] ) = 1;

L445: ( D28 . [ ( R18 + 1 ) , ( R9 '&&' ( R9 'Us' R10 ) ) ] ) = 1 by L444 , L244;
L446: ( D28 . [ ( R18 + 1 ) , ( R9 'Us' R10 ) ] ) = 1 by L445 , L204;
consider R15 being (Element of ( NAT )) such that L447: R15 > ( 0 ) and L448: ( D28 . [ ( ( R18 + 1 ) + R15 ) , R10 ] ) = 1 and L449: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D28 . [ ( ( R18 + 1 ) + R16 ) , R9 ] ) = 1)) by L446 , L52;
L450:
now
let R16 being (Element of ( NAT ));
assume L451: (1 <= R16 & R16 < ( 1 + R15 ));
per cases  by L451 , NAT_1:25;
suppose L452: 1 = R16;

thus L453: ( D28 . [ ( R18 + R16 ) , R9 ] ) = 1 by L452 , L445 , L204;
end;
suppose L454: (1 < R16 & R16 < ( R15 + 1 ));

L455: ( 1 + ( - 1 ) ) < ( R16 + ( - 1 ) ) by L454 , XREAL_1:8;
L456: ( R16 - 1 ) > ( 0 ) by L455;
L457: ( R16 -' 1 ) > ( 0 ) by L456 , XREAL_0:def 2;
L458: 1 <= ( R16 -' 1 ) by L457 , NAT_1:25;
L459: ( ( ( R18 + R16 ) + 1 ) - 1 ) = ( ( R18 + 1 ) + ( R16 - 1 ) )
.= ( ( R18 + 1 ) + ( R16 -' 1 ) ) by L455 , XREAL_0:def 2;
L460: ( R16 + ( - 1 ) ) < ( ( R15 + 1 ) + ( - 1 ) ) by L454 , XREAL_1:8;
thus L461: ( D28 . [ ( R18 + R16 ) , R9 ] ) = 1 by L460 , L449 , L459 , L458;
end;
end;
L463: ( D28 . [ ( R18 + ( 1 + R15 ) ) , R10 ] ) = 1 by L448;
thus L464: contradiction by L463 , L439 , L450 , L52;
end;
end;
L466: (( D28 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) = ( 0 ) or ( D28 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) = 1) by XBOOLEAN:def 3;
L467: ( ( D28 . [ R18 , ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ] ) => ( D28 . [ R18 , ( R9 'Us' R10 ) ] ) ) = 1 by L466 , L437 , XBOOLEAN:def 3;
thus L468: thesis by L467 , L52;
end;
theorem
L469: (for R9 being (Element of ( LTLB_WFF )) holds (for R10 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT R23 ) . [ R18 , ( ( R9 'Us' R10 ) => ( 'X' ( 'F' R10 ) ) ) ] ) = 1))))
proof
let R9 being (Element of ( LTLB_WFF ));
let R10 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
set D29 = ( SAT R23 );
L470:
now
assume that
L471: ( D29 . [ R18 , ( R9 'Us' R10 ) ] ) = 1
and
L472: ( D29 . [ R18 , ( 'X' ( 'F' R10 ) ) ] ) = ( 0 );
consider R15 being (Element of ( NAT )) such that L473: ( 0 ) < R15 and L474: ( D29 . [ ( R18 + R15 ) , R10 ] ) = 1 and L475: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < R15) implies ( D29 . [ ( R18 + R16 ) , R9 ] ) = 1)) by L471 , L52;
L476: R15 >= 1 by L473 , NAT_1:25;
L477: ( R15 + ( - 1 ) ) >= ( 1 + ( - 1 ) ) by L476 , XREAL_1:6;
L478: ( ( R18 + 1 ) + ( R15 -' 1 ) ) = ( ( R18 + 1 ) + ( R15 - 1 ) ) by L477 , XREAL_0:def 2
.= ( R18 + R15 );
L479: ( D29 . [ ( R18 + 1 ) , ( 'F' R10 ) ] ) = ( 0 ) by L472 , L244;
thus L480: contradiction by L479 , L474 , L478 , L292;
end;
L481: (( D29 . [ R18 , ( R9 'Us' R10 ) ] ) = ( 0 ) or ( D29 . [ R18 , ( R9 'Us' R10 ) ] ) = 1) by XBOOLEAN:def 3;
L482: ( ( D29 . [ R18 , ( R9 'Us' R10 ) ] ) => ( D29 . [ R18 , ( 'X' ( 'F' R10 ) ) ] ) ) = 1 by L481 , L470 , XBOOLEAN:def 3;
thus L483: thesis by L482 , L52;
end;
begin
definition
let R23 being LTLModel;
let R4 being (Element of ( LTLB_WFF ));
pred R23 |= R4
means
:L484: (for B60 being (Element of ( NAT )) holds ( ( SAT R23 ) . [ B60 , R4 ] ) = 1)
;end;
definition
let R23 being LTLModel;
let R11 being (Subset of ( LTLB_WFF ));
pred R23 |= R11
means
:L486: (for R4 being (Element of ( LTLB_WFF )) holds (R4 in R11 implies R23 |= R4))
;end;
definition
let R11 being (Subset of ( LTLB_WFF ));
let R4 being (Element of ( LTLB_WFF ));
pred R11 |= R4
means
:L488: (for R23 being LTLModel holds (R23 |= R11 implies R23 |= R4))
;end;
theorem
L490: (for R11 being (Subset of ( LTLB_WFF )) holds (for R12 being (Subset of ( LTLB_WFF )) holds (for R23 being LTLModel holds ((R23 |= R11 & R23 |= R12) iff R23 |= ( R11 \/ R12 )))))
proof
let R11 being (Subset of ( LTLB_WFF ));
let R12 being (Subset of ( LTLB_WFF ));
let R23 being LTLModel;
thus L491:now
assume L492: (R23 |= R11 & R23 |= R12);
thus L493: R23 |= ( R11 \/ R12 )
proof
let R4 being (Element of ( LTLB_WFF ));
assume L494: R4 in ( R11 \/ R12 );
L495: (R4 in R11 or R4 in R12) by L494 , XBOOLE_0:def 3;
thus L496: R23 |= R4 by L495 , L492 , L486;
end;

end;
assume L494: R23 |= ( R11 \/ R12 );
thus L495: R23 |= R11
proof
let R4 being (Element of ( LTLB_WFF ));
assume L496: R4 in R11;
L497: R4 in ( R11 \/ R12 ) by L496 , XBOOLE_0:def 3;
thus L498: R23 |= R4 by L497 , L494 , L486;
end;

thus L499: R23 |= R12
proof
let R4 being (Element of ( LTLB_WFF ));
assume L500: R4 in R12;
L501: R4 in ( R11 \/ R12 ) by L500 , XBOOLE_0:def 3;
thus L502: R23 |= R4 by L501 , L494 , L486;
end;

end;
theorem
L500: (for R8 being (Element of ( LTLB_WFF )) holds (for R23 being LTLModel holds (R23 |= R8 iff R23 |= { R8 })))
proof
let R8 being (Element of ( LTLB_WFF ));
let R23 being LTLModel;
thus L501:now
assume L502: R23 |= R8;
thus L503: R23 |= { R8 }
proof
let R4 being (Element of ( LTLB_WFF ));
assume L504: R4 in { R8 };
thus L505: R23 |= R4 by L504 , L502 , TARSKI:def 1;
end;

end;
L504: R8 in { R8 } by TARSKI:def 1;
assume L505: R23 |= { R8 };
thus L506: R23 |= R8 by L505 , L504 , L486;
end;
theorem
L507: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds ((R11 |= R8 & R11 |= ( R8 => R9 )) implies R11 |= R9))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume that
L508: R11 |= R8
and
L509: R11 |= ( R8 => R9 );
let R23 being LTLModel;
assume L510: R23 |= R11;
let C75 being (Element of ( NAT ));
L511: R23 |= ( R8 => R9 ) by L509 , L510 , L488;
L512: ( ( SAT R23 ) . [ C75 , ( R8 => R9 ) ] ) = 1 by L511 , L484;
L513: ( ( ( SAT R23 ) . [ C75 , R8 ] ) => ( ( SAT R23 ) . [ C75 , R9 ] ) ) = 1 by L512 , L52;
L514: R23 |= R8 by L508 , L510 , L488;
L515: ( ( SAT R23 ) . [ C75 , R8 ] ) = 1 by L514 , L484;
thus L516: ( ( SAT R23 ) . [ C75 , R9 ] ) = 1 by L515 , L513;
end;
theorem
L517: (for R8 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |= R8 implies R11 |= ( 'X' R8 ))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L518: R11 |= R8;
let R23 being LTLModel;
assume L519: R23 |= R11;
L520: R23 |= R8 by L519 , L518 , L488;
let C76 being (Element of ( NAT ));
thus L521: ( ( SAT R23 ) . [ C76 , ( 'X' R8 ) ] ) = ( ( SAT R23 ) . [ ( C76 + 1 ) , R8 ] ) by L244
.= 1 by L520 , L484;
end;
theorem
L522: (for R8 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |= R8 implies R11 |= ( 'G' R8 ))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L523: R11 |= R8;
let R23 being LTLModel;
assume L524: R23 |= R11;
let C77 being (Element of ( NAT ));
L525: R23 |= R8 by L523 , L524 , L488;
L526: (for B61 being (Element of ( NAT )) holds ( ( SAT R23 ) . [ ( C77 + B61 ) , R8 ] ) = 1) by L525 , L484;
thus L527: ( ( SAT R23 ) . [ C77 , ( 'G' R8 ) ] ) = 1 by L526 , L260;
end;
theorem
L528: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds ((R11 |= ( R8 => R9 ) & R11 |= ( R8 => ( 'X' R8 ) )) implies R11 |= ( R8 => ( 'G' R9 ) )))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume that
L529: R11 |= ( R8 => R9 )
and
L530: R11 |= ( R8 => ( 'X' R8 ) );
let R23 being LTLModel;
assume L531: R23 |= R11;
L532: R23 |= ( R8 => R9 ) by L531 , L529 , L488;
L533: R23 |= ( R8 => ( 'X' R8 ) ) by L530 , L531 , L488;
let C78 being (Element of ( NAT ));
defpred S9[ Nat ] means ( ( SAT R23 ) . [ ( C78 + $1 ) , R8 ] ) = 1;
per cases  by XBOOLEAN:def 3;
suppose L534: ( ( SAT R23 ) . [ C78 , R8 ] ) = 1;

L535: (for B62 being (Element of ( NAT )) holds (S9[ B62 ] implies S9[ ( B62 + 1 ) ]))
proof
let C79 being (Element of ( NAT ));
assume that
L536: S9[ C79 ];
L537: ( ( SAT R23 ) . [ ( C78 + C79 ) , ( R8 => ( 'X' R8 ) ) ] ) = 1 by L533 , L484;
L538: ( ( ( SAT R23 ) . [ ( C78 + C79 ) , R8 ] ) => ( ( SAT R23 ) . [ ( C78 + C79 ) , ( 'X' R8 ) ] ) ) = 1 by L537 , L52;
L539: ( ( SAT R23 ) . [ ( ( C78 + C79 ) + 1 ) , R8 ] ) = 1 by L538 , L536 , L244;
thus L540: S9[ ( C79 + 1 ) ] by L539;
end;
L541: S9[ ( 0 ) ] by L534;
L542: (for B63 being (Element of ( NAT )) holds S9[ B63 ]) from NAT_1:sch 1(L541 , L535);
L543:
now
let C80 being (Element of ( NAT ));
L544: ( ( SAT R23 ) . [ ( C78 + C80 ) , ( R8 => R9 ) ] ) = 1 by L532 , L484;
L545: ( ( ( SAT R23 ) . [ ( C78 + C80 ) , R8 ] ) => ( ( SAT R23 ) . [ ( C78 + C80 ) , R9 ] ) ) = 1 by L544 , L52;
L546: ( ( SAT R23 ) . [ ( C78 + C80 ) , R8 ] ) = 1 by L542;
thus L547: ( ( SAT R23 ) . [ ( C78 + C80 ) , R9 ] ) = 1 by L546 , L545;
end;
L548: ( ( SAT R23 ) . [ C78 , ( 'G' R9 ) ] ) = 1 by L543 , L260;
L549: ( ( ( SAT R23 ) . [ C78 , R8 ] ) => ( ( SAT R23 ) . [ C78 , ( 'G' R9 ) ] ) ) = 1 by L548;
thus L550: ( ( SAT R23 ) . [ C78 , ( R8 => ( 'G' R9 ) ) ] ) = 1 by L549 , L52;
end;
suppose L551: ( ( SAT R23 ) . [ C78 , R8 ] ) = ( 0 );

L552: ( ( ( SAT R23 ) . [ C78 , R8 ] ) => ( ( SAT R23 ) . [ C78 , ( 'G' R9 ) ] ) ) = 1 by L551;
thus L553: ( ( SAT R23 ) . [ C78 , ( R8 => ( 'G' R9 ) ) ] ) = 1 by L552 , L52;
end;
end;
theorem
L555: (for R8 being (Element of ( LTLB_WFF )) holds (for R15 being (Element of ( NAT )) holds (for R16 being (Element of ( NAT )) holds (for R23 being LTLModel holds ( ( SAT ( R23 ^\ R15 ) ) . [ R16 , R8 ] ) = ( ( SAT R23 ) . [ ( R15 + R16 ) , R8 ] )))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R15 being (Element of ( NAT ));
let R16 being (Element of ( NAT ));
let R23 being LTLModel;
defpred S10[ (Element of ( LTLB_WFF )) ] means (for R17 being (Element of ( NAT )) holds ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , $1 ] ) = ( ( SAT R23 ) . [ ( R15 + R17 ) , $1 ] ));
L556: (for B64 being (Element of ( NAT )) holds S10[ ( prop B64 ) ])
proof
let R18 being (Element of ( NAT ));
let R17 being (Element of ( NAT ));
per cases ;
suppose L557: ( prop R18 ) in ( ( R23 ^\ R15 ) . R17 );

L558: ( prop R18 ) in ( R23 . ( R15 + R17 ) ) by L557 , NAT_1:def 3;
thus L559: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( prop R18 ) ] ) = 1 by L557 , L52
.= ( ( SAT R23 ) . [ ( R15 + R17 ) , ( prop R18 ) ] ) by L558 , L52;
end;
suppose L560: (not ( prop R18 ) in ( ( R23 ^\ R15 ) . R17 ));

L561: (not ( prop R18 ) in ( R23 . ( R15 + R17 ) )) by L560 , NAT_1:def 3;
L562: (not ( ( SAT R23 ) . [ ( R15 + R17 ) , ( prop R18 ) ] ) = 1) by L561 , L52;
L563: (not ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( prop R18 ) ] ) = 1) by L560 , L52;
thus L564: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( prop R18 ) ] ) = ( 0 ) by L563 , XBOOLEAN:def 3
.= ( ( SAT R23 ) . [ ( R15 + R17 ) , ( prop R18 ) ] ) by L562 , XBOOLEAN:def 3;
end;
end;
L566: (for R6 being (Element of ( LTLB_WFF )) holds (for R7 being (Element of ( LTLB_WFF )) holds ((S10[ R6 ] & S10[ R7 ]) implies (S10[ ( R6 'Us' R7 ) ] & S10[ ( R6 => R7 ) ]))))
proof
let C81 , C82 being (Element of ( LTLB_WFF ));
assume that
L567: S10[ C81 ]
and
L568: S10[ C82 ];
thus L569: S10[ ( C81 'Us' C82 ) ]
proof
let R17 being (Element of ( NAT ));
L570: (( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( C81 'Us' C82 ) ] ) = 1 iff ( ( SAT R23 ) . [ ( R15 + R17 ) , ( C81 'Us' C82 ) ] ) = 1)
proof
thus L571:now
assume L572: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( C81 'Us' C82 ) ] ) = 1;
consider C83 being (Element of ( NAT )) such that L573: ( 0 ) < C83 and L574: ( ( SAT ( R23 ^\ R15 ) ) . [ ( R17 + C83 ) , C82 ] ) = 1 and L575: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < C83) implies ( ( SAT ( R23 ^\ R15 ) ) . [ ( R17 + R16 ) , C81 ] ) = 1)) by L572 , L52;
L576:
now
let R16 being (Element of ( NAT ));
assume L577: (1 <= R16 & R16 < C83);
L578: ( ( SAT ( R23 ^\ R15 ) ) . [ ( R17 + R16 ) , C81 ] ) = 1 by L577 , L575;
L579: ( ( SAT R23 ) . [ ( R15 + ( R17 + R16 ) ) , C81 ] ) = 1 by L578 , L567;
thus L580: ( ( SAT R23 ) . [ ( ( R15 + R17 ) + R16 ) , C81 ] ) = 1 by L579;
end;
L581: ( ( SAT R23 ) . [ ( R15 + ( R17 + C83 ) ) , C82 ] ) = 1 by L568 , L574;
L582: ( ( SAT R23 ) . [ ( ( R15 + R17 ) + C83 ) , C82 ] ) = 1 by L581;
thus L583: ( ( SAT R23 ) . [ ( R15 + R17 ) , ( C81 'Us' C82 ) ] ) = 1 by L582 , L573 , L576 , L52;
end;
assume L584: ( ( SAT R23 ) . [ ( R15 + R17 ) , ( C81 'Us' C82 ) ] ) = 1;
consider C84 being (Element of ( NAT )) such that L585: ( 0 ) < C84 and L586: ( ( SAT R23 ) . [ ( ( R15 + R17 ) + C84 ) , C82 ] ) = 1 and L587: (for R16 being (Element of ( NAT )) holds ((1 <= R16 & R16 < C84) implies ( ( SAT R23 ) . [ ( ( R15 + R17 ) + R16 ) , C81 ] ) = 1)) by L584 , L52;
L588:
now
let R16 being (Element of ( NAT ));
assume L589: (1 <= R16 & R16 < C84);
L590: ( ( SAT R23 ) . [ ( ( R15 + R17 ) + R16 ) , C81 ] ) = 1 by L589 , L587;
L591: ( ( SAT R23 ) . [ ( R15 + ( R17 + R16 ) ) , C81 ] ) = 1 by L590;
thus L592: ( ( SAT ( R23 ^\ R15 ) ) . [ ( R17 + R16 ) , C81 ] ) = 1 by L591 , L567;
end;
L593: ( ( SAT R23 ) . [ ( R15 + ( R17 + C84 ) ) , C82 ] ) = 1 by L586;
L594: ( ( SAT ( R23 ^\ R15 ) ) . [ ( R17 + C84 ) , C82 ] ) = 1 by L593 , L568;
thus L595: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( C81 'Us' C82 ) ] ) = 1 by L594 , L585 , L588 , L52;
end;
per cases ;
suppose L596: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( C81 'Us' C82 ) ] ) = 1;

thus L597: thesis by L596 , L570;
end;
suppose L598: (not ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( C81 'Us' C82 ) ] ) = 1);

L599: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( C81 'Us' C82 ) ] ) = ( 0 ) by L598 , XBOOLEAN:def 3;
thus L600: thesis by L599 , L570 , XBOOLEAN:def 3;
end;
end;

thus L602: S10[ ( C81 => C82 ) ]
proof
let C85 being (Element of ( NAT ));
thus L603: ( ( SAT ( R23 ^\ R15 ) ) . [ C85 , ( C81 => C82 ) ] ) = ( ( ( SAT ( R23 ^\ R15 ) ) . [ C85 , C81 ] ) => ( ( SAT ( R23 ^\ R15 ) ) . [ C85 , C82 ] ) ) by L52
.= ( ( ( SAT R23 ) . [ ( R15 + C85 ) , C81 ] ) => ( ( SAT ( R23 ^\ R15 ) ) . [ C85 , C82 ] ) ) by L567
.= ( ( ( SAT R23 ) . [ ( R15 + C85 ) , C81 ] ) => ( ( SAT R23 ) . [ ( R15 + C85 ) , C82 ] ) ) by L568
.= ( ( SAT R23 ) . [ ( R15 + C85 ) , ( C81 => C82 ) ] ) by L52;
end;

end;
L603:
now
let R17 being (Element of ( NAT ));
thus L604: ( ( SAT ( R23 ^\ R15 ) ) . [ R17 , ( TFALSUM ) ] ) = ( 0 ) by L52
.= ( ( SAT R23 ) . [ ( R15 + R17 ) , ( TFALSUM ) ] ) by L52;
end;
L605: S10[ ( TFALSUM ) ] by L603;
L606: (for B65 being (Element of ( LTLB_WFF )) holds S10[ B65 ]) from HILBERT2:sch 2(L605 , L556 , L566);
thus L607: ( ( SAT ( R23 ^\ R15 ) ) . [ R16 , R8 ] ) = ( ( SAT R23 ) . [ ( R15 + R16 ) , R8 ] ) by L606;
end;
theorem
L608: (for R11 being (Subset of ( LTLB_WFF )) holds (for R15 being (Element of ( NAT )) holds (for R23 being LTLModel holds (R23 |= R11 implies ( R23 ^\ R15 ) |= R11))))
proof
let R11 being (Subset of ( LTLB_WFF ));
let R15 being (Element of ( NAT ));
let R23 being LTLModel;
assume L609: R23 |= R11;
thus L610: ( R23 ^\ R15 ) |= R11
proof
let R4 being (Element of ( LTLB_WFF ));
assume L611: R4 in R11;
L612: R23 |= R4 by L611 , L609 , L486;
thus L613: ( R23 ^\ R15 ) |= R4
proof
let R18 being (Element of ( NAT ));
L614: ( ( SAT R23 ) . [ ( R15 + R18 ) , R4 ] ) = 1 by L612 , L484;
thus L615: ( ( SAT ( R23 ^\ R15 ) ) . [ R18 , R4 ] ) = 1 by L614 , L555;
end;

end;

end;
theorem
L611: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (( R11 \/ { R8 } ) |= R9 iff R11 |= ( ( 'G' R8 ) => R9 )))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
thus L612:now
assume L613: ( R11 \/ { R8 } ) |= R9;
thus L614: R11 |= ( ( 'G' R8 ) => R9 )
proof
let R23 being LTLModel;
assume L615: R23 |= R11;
thus L616: R23 |= ( ( 'G' R8 ) => R9 )
proof
let R18 being (Element of ( NAT ));
per cases  by XBOOLEAN:def 3;
suppose L617: ( ( SAT R23 ) . [ R18 , ( 'G' R8 ) ] ) = ( 0 );

thus L618: ( ( SAT R23 ) . [ R18 , ( ( 'G' R8 ) => R9 ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'G' R8 ) ] ) => ( ( SAT R23 ) . [ R18 , R9 ] ) ) by L52
.= 1 by L617;
end;
suppose L619: ( ( SAT R23 ) . [ R18 , ( 'G' R8 ) ] ) = 1;

L620:
now
let R16 being (Element of ( NAT ));
L621: ( ( SAT R23 ) . [ ( R18 + R16 ) , R8 ] ) = 1 by L619 , L260;
thus L622: ( ( SAT ( R23 ^\ R18 ) ) . [ R16 , R8 ] ) = 1 by L621 , L555;
end;
L623: ( R23 ^\ R18 ) |= R8 by L620 , L484;
L624: ( R23 ^\ R18 ) |= { R8 } by L623 , L500;
L625: ( R23 ^\ R18 ) |= R11 by L615 , L608;
L626: ( R23 ^\ R18 ) |= ( R11 \/ { R8 } ) by L625 , L624 , L490;
L627: ( R23 ^\ R18 ) |= R9 by L626 , L613 , L488;
L628: ( ( SAT ( R23 ^\ R18 ) ) . [ ( 0 ) , R9 ] ) = 1 by L627 , L484;
L629: ( ( SAT R23 ) . [ ( R18 + ( 0 ) ) , R9 ] ) = 1 by L628 , L555;
thus L630: ( ( SAT R23 ) . [ R18 , ( ( 'G' R8 ) => R9 ) ] ) = ( ( ( SAT R23 ) . [ R18 , ( 'G' R8 ) ] ) => ( ( SAT R23 ) . [ R18 , R9 ] ) ) by L52
.= 1 by L629;
end;
end;

end;

end;
assume L615: R11 |= ( ( 'G' R8 ) => R9 );
let R23 being LTLModel;
assume L616: R23 |= ( R11 \/ { R8 } );
let R15 being (Element of ( NAT ));
L617: R23 |= { R8 } by L616 , L490;
L618: R23 |= R8 by L617 , L500;
L619: (for R16 being (Element of ( NAT )) holds ( ( SAT R23 ) . [ ( R15 + R16 ) , R8 ] ) = 1) by L618 , L484;
L620: ( ( SAT R23 ) . [ R15 , ( 'G' R8 ) ] ) = 1 by L619 , L260;
L621: R23 |= R11 by L616 , L490;
L622: R23 |= ( ( 'G' R8 ) => R9 ) by L621 , L615 , L488;
L623: ( ( SAT R23 ) . [ R15 , ( ( 'G' R8 ) => R9 ) ] ) = 1 by L622 , L484;
L624: ( ( ( SAT R23 ) . [ R15 , ( 'G' R8 ) ] ) => ( ( SAT R23 ) . [ R15 , R9 ] ) ) = 1 by L623 , L52;
thus L625: ( ( SAT R23 ) . [ R15 , R9 ] ) = 1 by L624 , L620;
end;
definition
let C86 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
func VAL C86 -> (Function of ( LTLB_WFF ) , ( BOOLEAN )) means 
:L626: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (( it . ( TFALSUM ) ) = ( 0 ) & ( it . ( prop R18 ) ) = ( C86 . ( prop R18 ) ) & ( it . ( R8 => R9 ) ) = ( ( it . R8 ) => ( it . R9 ) ) & ( it . ( R8 'Us' R9 ) ) = ( C86 . ( R8 'Us' R9 ) )))));
existence
proof
defpred S11[ (Element of ( LTLB_WFF )) , (Element of ( LTLB_WFF )) , set , set , set ] means ((($3 is (Element of ( BOOLEAN )) & $4 is (Element of ( BOOLEAN ))) implies (ex B66 , B67 , B68 being (Element of ( BOOLEAN )) st (B66 = $3 & B67 = $4 & B68 = $5 & B68 = ( B66 => B67 )))) & (((not $3 is (Element of ( BOOLEAN ))) or (not $4 is (Element of ( BOOLEAN )))) implies $5 = ( {} )));
defpred S12[ (Element of ( LTLB_WFF )) , (Element of ( LTLB_WFF )) , set , set , set ] means $5 = ( C86 . ( $1 'Us' $2 ) );
deffunc H4((Element of ( NAT ))) = ( C86 . ( prop $1 ) );
L627: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for B69 , B70 being set holds (ex B71 being set st S11[ R8 , R9 , B69 , B70 , B71 ]))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
let C87 , C88 being set;
per cases ;
suppose that L628: C87 is (Element of ( BOOLEAN ))
and
L629: C88 is (Element of ( BOOLEAN ));
reconsider D30 = C88 as (Element of ( BOOLEAN )) by L629;
reconsider D31 = C87 as (Element of ( BOOLEAN )) by L628;
per cases  by XBOOLEAN:def 3;
suppose L630: D31 = ( 0 );

set D32 = ( TRUE );
L631: D32 = ( D31 => D30 ) by L630;
thus L632: thesis by L631;
end;
suppose L633: D31 = 1;

per cases  by XBOOLEAN:def 3;
suppose L634: D30 = ( 0 );

set D33 = ( FALSE );
L635: D33 = ( D31 => D30 ) by L633 , L634;
thus L636: thesis by L635;
end;
suppose L637: D30 = 1;

set D34 = ( TRUE );
L638: D34 = ( D31 => D30 ) by L637;
thus L639: thesis by L638;
end;
end;
end;
suppose L642: ((not C87 is (Element of ( BOOLEAN ))) or (not C88 is (Element of ( BOOLEAN ))));

thus L643: thesis by L642;
end;
end;
L645: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for B72 , B73 , B74 , B75 being set holds ((S12[ R4 , R5 , B72 , B73 , B74 ] & S12[ R4 , R5 , B72 , B73 , B75 ]) implies B74 = B75))));
L646: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for B76 , B77 , B78 , B79 being set holds ((S11[ R4 , R5 , B76 , B77 , B78 ] & S11[ R4 , R5 , B76 , B77 , B79 ]) implies B78 = B79))));
L647: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for B80 , B81 being set holds (ex B82 being set st S12[ R8 , R9 , B80 , B81 , B82 ]))));
consider C89 being (ManySortedSet of ( LTLB_WFF )) such that L648: (( C89 . ( TFALSUM ) ) = ( 0 ) & (for R18 being (Element of ( NAT )) holds ( C89 . ( prop R18 ) ) = H4(R18)) & (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (S12[ R4 , R5 , ( C89 . R4 ) , ( C89 . R5 ) , ( C89 . ( R4 'Us' R5 ) ) ] & S11[ R4 , R5 , ( C89 . R4 ) , ( C89 . R5 ) , ( C89 . ( R4 => R5 ) ) ])))) from HILBERT2:sch 3(L647 , L627 , L645 , L646);
L649:
now
L650:
now
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
per cases ;
suppose L651: (( C89 . R8 ) is (Element of ( BOOLEAN )) & ( C89 . R9 ) is (Element of ( BOOLEAN )));

consider C90 , C91 , C92 being (Element of ( BOOLEAN )) such that L652: C90 = ( C89 . R8 ) and L653: C91 = ( C89 . R9 ) and L654: C92 = ( C89 . ( R8 => R9 ) ) and L655: C92 = ( C90 => C91 ) by L651 , L648;
thus L656: ( C89 . ( R8 => R9 ) ) in ( BOOLEAN ) by L654;
end;
suppose L657: (not (( C89 . R8 ) is (Element of ( BOOLEAN )) & ( C89 . R9 ) is (Element of ( BOOLEAN ))));

L658: ( C89 . ( R8 => R9 ) ) = ( FALSE ) by L657 , L648;
thus L659: ( C89 . ( R8 => R9 ) ) in ( BOOLEAN ) by L658;
end;
end;
let C93 being set;
assume L661: C93 in ( LTLB_WFF );
reconsider D35 = C93 as (Element of ( LTLB_WFF )) by L661;
L662:
now
let R18 being (Element of ( NAT ));
L663: ( C89 . ( prop R18 ) ) = ( C86 . ( prop R18 ) ) by L648;
thus L664: ( C89 . ( prop R18 ) ) in ( BOOLEAN ) by L663;
end;
L665:
now
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
L666: ( C89 . ( R8 'Us' R9 ) ) = ( C86 . ( R8 'Us' R9 ) ) by L648;
thus L667: ( C89 . ( R8 'Us' R9 ) ) in ( BOOLEAN ) by L666;
end;
per cases  by L23;
suppose L668: D35 = ( TFALSUM );

thus L669: ( C89 . C93 ) in ( BOOLEAN ) by L668 , L648 , TARSKI:def 2;
end;
suppose L670: (ex B83 being (Element of ( NAT )) st D35 = ( prop B83 ));

thus L671: ( C89 . C93 ) in ( BOOLEAN ) by L670 , L662;
end;
suppose L672: (ex R4 being (Element of ( LTLB_WFF )) st (ex R5 being (Element of ( LTLB_WFF )) st D35 = ( R4 'Us' R5 )));

thus L673: ( C89 . C93 ) in ( BOOLEAN ) by L672 , L665;
end;
suppose L674: (ex R4 being (Element of ( LTLB_WFF )) st (ex R5 being (Element of ( LTLB_WFF )) st D35 = ( R4 => R5 )));

thus L675: ( C89 . C93 ) in ( BOOLEAN ) by L674 , L650;
end;
end;
L677: ( dom C89 ) = ( LTLB_WFF ) by PARTFUN1:def 2;
reconsider D36 = C89 as (Function of ( LTLB_WFF ) , ( BOOLEAN )) by L677 , L649 , FUNCT_2:3;
take D36;
L678:
now
let R8 being (Element of ( LTLB_WFF ));
let R9 being (Element of ( LTLB_WFF ));
L679: S11[ R8 , R9 , ( D36 . R8 ) , ( D36 . R9 ) , ( D36 . ( R8 => R9 ) ) ] by L648;
thus L680: ( D36 . ( R8 => R9 ) ) = ( ( D36 . R8 ) => ( D36 . R9 ) ) by L679;
end;
thus L681: thesis by L678 , L648;
end;
uniqueness
proof
let C94 , C95 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
assume L682: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (( C94 . ( TFALSUM ) ) = ( 0 ) & ( C94 . ( prop R18 ) ) = ( C86 . ( prop R18 ) ) & ( C94 . ( R8 => R9 ) ) = ( ( C94 . R8 ) => ( C94 . R9 ) ) & ( C94 . ( R8 'Us' R9 ) ) = ( C86 . ( R8 'Us' R9 ) )))));
assume L683: (for R8 being (Element of ( LTLB_WFF )) holds (for R9 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (( C95 . ( TFALSUM ) ) = ( 0 ) & ( C95 . ( prop R18 ) ) = ( C86 . ( prop R18 ) ) & ( C95 . ( R8 => R9 ) ) = ( ( C95 . R8 ) => ( C95 . R9 ) ) & ( C95 . ( R8 'Us' R9 ) ) = ( C86 . ( R8 'Us' R9 ) )))));
thus L684: C94 = C95
proof
defpred S13[ (Element of ( LTLB_WFF )) ] means ( C94 . $1 ) = ( C95 . $1 );
L685: (for R18 being (Element of ( NAT )) holds S13[ ( prop R18 ) ])
proof
let R18 being (Element of ( NAT ));
L686: ( C94 . ( prop R18 ) ) = ( C86 . ( prop R18 ) ) by L682
.= ( C95 . ( prop R18 ) ) by L683;
thus L687: S13[ ( prop R18 ) ] by L686;
end;
L688: (for R6 being (Element of ( LTLB_WFF )) holds (for R7 being (Element of ( LTLB_WFF )) holds ((S13[ R6 ] & S13[ R7 ]) implies (S13[ ( R6 'Us' R7 ) ] & S13[ ( R6 => R7 ) ]))))
proof
let R6 being (Element of ( LTLB_WFF ));
let R7 being (Element of ( LTLB_WFF ));
assume L689: (S13[ R6 ] & S13[ R7 ]);
L690: ( C94 . ( R6 'Us' R7 ) ) = ( C86 . ( R6 'Us' R7 ) ) by L682
.= ( C95 . ( R6 'Us' R7 ) ) by L683;
L691: ( C94 . ( R6 => R7 ) ) = ( ( C94 . R6 ) => ( C94 . R7 ) ) by L682
.= ( C95 . ( R6 => R7 ) ) by L683 , L689;
thus L692: thesis by L691 , L690;
end;
L693: S13[ ( TFALSUM ) ] by L682 , L683;
L694: (for B84 being (Element of ( LTLB_WFF )) holds S13[ B84 ]) from HILBERT2:sch 2(L693 , L685 , L688);
L695: (for B85 being (Element of ( LTLB_WFF )) holds (B85 in ( dom C94 ) implies S13[ B85 ])) by L694;
L696: ( dom C94 ) = ( LTLB_WFF ) by FUNCT_2:def 1
.= ( dom C95 ) by FUNCT_2:def 1;
thus L697: thesis by L696 , L695 , PARTFUN1:5;
end;

end;
end;
theorem
L686: (for B86 being (Function of ( LTLB_WFF ) , ( BOOLEAN )) holds (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds ( ( VAL B86 ) . ( R4 '&&' R5 ) ) = ( ( ( VAL B86 ) . R4 ) '&' ( ( VAL B86 ) . R5 ) ))))
proof
let C96 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
L687: (( ( VAL C96 ) . R4 ) = ( 0 ) or ( ( VAL C96 ) . R4 ) = 1) by XBOOLEAN:def 3;
L688: (( ( VAL C96 ) . R5 ) = ( 0 ) or ( ( VAL C96 ) . R5 ) = 1) by XBOOLEAN:def 3;
thus L689: ( ( VAL C96 ) . ( R4 '&&' R5 ) ) = ( ( ( VAL C96 ) . ( R4 => ( R5 => ( TFALSUM ) ) ) ) => ( ( VAL C96 ) . ( TFALSUM ) ) ) by L626
.= ( ( ( ( VAL C96 ) . R4 ) => ( ( VAL C96 ) . ( R5 => ( TFALSUM ) ) ) ) => ( ( VAL C96 ) . ( TFALSUM ) ) ) by L626
.= ( ( ( ( VAL C96 ) . R4 ) => ( ( ( VAL C96 ) . R5 ) => ( ( VAL C96 ) . ( TFALSUM ) ) ) ) => ( ( VAL C96 ) . ( TFALSUM ) ) ) by L626
.= ( ( ( ( VAL C96 ) /. R4 ) => ( ( ( VAL C96 ) . R5 ) => ( FALSE ) ) ) => ( ( VAL C96 ) . ( TFALSUM ) ) ) by L626
.= ( ( ( VAL C96 ) . R4 ) '&' ( ( VAL C96 ) . R5 ) ) by L687 , L688 , L626;
end;
theorem
L690: (for R8 being (Element of ( LTLB_WFF )) holds (for R18 being (Element of ( NAT )) holds (for R23 being LTLModel holds (for B87 being (Function of ( LTLB_WFF ) , ( BOOLEAN )) holds ((for B88 being set holds (B88 in ( LTLB_WFF ) implies ( B87 . B88 ) = ( ( SAT R23 ) . [ R18 , B88 ] ))) implies ( ( VAL B87 ) . R8 ) = ( ( SAT R23 ) . [ R18 , R8 ] ))))))
proof
let R8 being (Element of ( LTLB_WFF ));
let R18 being (Element of ( NAT ));
let R23 being LTLModel;
let C97 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
defpred S14[ (Element of ( LTLB_WFF )) ] means ( ( VAL C97 ) . $1 ) = ( ( SAT R23 ) . [ R18 , $1 ] );
assume L691: (for B89 being set holds (B89 in ( LTLB_WFF ) implies ( C97 . B89 ) = ( ( SAT R23 ) . [ R18 , B89 ] )));
L692: (for R17 being (Element of ( NAT )) holds S14[ ( prop R17 ) ])
proof
let R17 being (Element of ( NAT ));
L693: ( ( SAT R23 ) . [ R18 , ( prop R17 ) ] ) = ( C97 . ( prop R17 ) ) by L691
.= ( ( VAL C97 ) . ( prop R17 ) ) by L626;
thus L694: thesis by L693;
end;
L695: (for R6 being (Element of ( LTLB_WFF )) holds (for R7 being (Element of ( LTLB_WFF )) holds ((S14[ R6 ] & S14[ R7 ]) implies (S14[ ( R6 'Us' R7 ) ] & S14[ ( R6 => R7 ) ]))))
proof
let R6 being (Element of ( LTLB_WFF ));
let R7 being (Element of ( LTLB_WFF ));
assume L696: (S14[ R6 ] & S14[ R7 ]);
L697: ( ( VAL C97 ) . ( R6 'Us' R7 ) ) = ( C97 . ( R6 'Us' R7 ) ) by L626
.= ( ( SAT R23 ) . [ R18 , ( R6 'Us' R7 ) ] ) by L691;
thus L698: S14[ ( R6 'Us' R7 ) ] by L697;
L699: ( ( SAT R23 ) . [ R18 , ( R6 => R7 ) ] ) = ( ( ( SAT R23 ) . [ R18 , R6 ] ) => ( ( SAT R23 ) . [ R18 , R7 ] ) ) by L52
.= ( ( VAL C97 ) . ( R6 => R7 ) ) by L696 , L626;
thus L700: S14[ ( R6 => R7 ) ] by L699;
end;
L701: ( ( SAT R23 ) . [ R18 , ( TFALSUM ) ] ) = ( 0 ) by L52
.= ( ( VAL C97 ) . ( TFALSUM ) ) by L626;
L702: S14[ ( TFALSUM ) ] by L701;
L703: (for R6 being (Element of ( LTLB_WFF )) holds S14[ R6 ]) from HILBERT2:sch 2(L702 , L692 , L695);
thus L704: ( ( VAL C97 ) . R8 ) = ( ( SAT R23 ) . [ R18 , R8 ] ) by L703;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
attr R4 is  LTL_TAUT_OF_PL
means
:L705: (for B90 being (Function of ( LTLB_WFF ) , ( BOOLEAN )) holds ( ( VAL B90 ) . R4 ) = 1);
end;
theorem
L707: (for R8 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R8 is  LTL_TAUT_OF_PL implies R11 |= R8)))
proof
let R8 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L708: R8 is  LTL_TAUT_OF_PL;
let C98 being LTLModel;
assume L709: C98 |= R11;
let R18 being (Element of ( NAT ));
defpred S15[ set , set ] means $2 = ( ( SAT C98 ) . [ R18 , $1 ] );
L710: (for B91 being set holds (B91 in ( LTLB_WFF ) implies (ex B92 being set st (B92 in ( BOOLEAN ) & S15[ B91 , B92 ]))))
proof
let C99 being set;
set D37 = ( ( SAT C98 ) . [ R18 , C99 ] );
assume L711: C99 in ( LTLB_WFF );
reconsider D38 = C99 as (Element of ( LTLB_WFF )) by L711;
take D37;
L712: ( ( SAT C98 ) . [ R18 , D38 ] ) in ( BOOLEAN );
thus L713: (D37 in ( BOOLEAN ) & S15[ C99 , D37 ]) by L712;
end;
consider C100 being (Function of ( LTLB_WFF ) , ( BOOLEAN )) such that L714: (for B93 being set holds (B93 in ( LTLB_WFF ) implies S15[ B93 , ( C100 . B93 ) ])) from FUNCT_2:sch 1(L710);
thus L715: ( ( SAT C98 ) . [ R18 , R8 ] ) = ( ( VAL C100 ) . R8 ) by L714 , L690
.= 1 by L708 , L705;
end;
begin
definition
let C101 being set;
attr C101 is  with_LTL_axioms
means
:L716: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds ((R4 is  LTL_TAUT_OF_PL implies R4 in C101) & ( ( 'not' ( 'X' R4 ) ) => ( 'X' ( 'not' R4 ) ) ) in C101 & ( ( 'X' ( 'not' R4 ) ) => ( 'not' ( 'X' R4 ) ) ) in C101 & ( ( 'X' ( R4 => R5 ) ) => ( ( 'X' R4 ) => ( 'X' R5 ) ) ) in C101 & ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) in C101 & ( ( R4 'Us' R5 ) => ( ( 'X' R5 ) 'or' ( 'X' ( R4 '&&' ( R4 'Us' R5 ) ) ) ) ) in C101 & ( ( ( 'X' R5 ) 'or' ( 'X' ( R4 '&&' ( R4 'Us' R5 ) ) ) ) => ( R4 'Us' R5 ) ) in C101 & ( ( R4 'Us' R5 ) => ( 'X' ( 'F' R5 ) ) ) in C101)));
end;
definition
func LTL_axioms -> (Subset of ( LTLB_WFF )) means 
:L718: (it is  with_LTL_axioms & (for B94 being (Subset of ( LTLB_WFF )) holds (B94 is  with_LTL_axioms implies it c= B94)));
existence
proof
defpred S16[ set ] means (for B95 being set holds (B95 is  with_LTL_axioms implies $1 in B95));
consider C102 being set such that L719: (for B96 being set holds (B96 in C102 iff (B96 in ( LTLB_WFF ) & S16[ B96 ]))) from XBOOLE_0:sch 1;
L720: C102 c= ( LTLB_WFF )
proof
let C103 being set;
assume L721: C103 in C102;
thus L722: thesis by L721 , L719;
end;
reconsider D39 = C102 as (Subset of ( LTLB_WFF )) by L720;
take D39;
thus L723: D39 is  with_LTL_axioms
proof
let C104 , C105 being (Element of ( LTLB_WFF ));
thus L724: (C104 is  LTL_TAUT_OF_PL implies C104 in D39)
proof
assume L725: C104 is  LTL_TAUT_OF_PL;
L726: (for B97 being set holds (B97 is  with_LTL_axioms implies C104 in B97)) by L725 , L716;
thus L727: thesis by L726 , L719;
end;

L728: (for B98 being set holds (B98 is  with_LTL_axioms implies ( ( 'not' ( 'X' C104 ) ) => ( 'X' ( 'not' C104 ) ) ) in B98)) by L716;
thus L729: ( ( 'not' ( 'X' C104 ) ) => ( 'X' ( 'not' C104 ) ) ) in D39 by L728 , L719;
L730: (for B99 being set holds (B99 is  with_LTL_axioms implies ( ( 'X' ( 'not' C104 ) ) => ( 'not' ( 'X' C104 ) ) ) in B99)) by L716;
thus L731: ( ( 'X' ( 'not' C104 ) ) => ( 'not' ( 'X' C104 ) ) ) in D39 by L730 , L719;
L732: (for B100 being set holds (B100 is  with_LTL_axioms implies ( ( 'X' ( C104 => C105 ) ) => ( ( 'X' C104 ) => ( 'X' C105 ) ) ) in B100)) by L716;
thus L733: ( ( 'X' ( C104 => C105 ) ) => ( ( 'X' C104 ) => ( 'X' C105 ) ) ) in D39 by L732 , L719;
L734: (for B101 being set holds (B101 is  with_LTL_axioms implies ( ( 'G' C104 ) => ( C104 '&&' ( 'X' ( 'G' C104 ) ) ) ) in B101)) by L716;
thus L735: ( ( 'G' C104 ) => ( C104 '&&' ( 'X' ( 'G' C104 ) ) ) ) in D39 by L734 , L719;
L736: (for B102 being set holds (B102 is  with_LTL_axioms implies ( ( C104 'Us' C105 ) => ( ( 'X' C105 ) 'or' ( 'X' ( C104 '&&' ( C104 'Us' C105 ) ) ) ) ) in B102)) by L716;
thus L737: ( ( C104 'Us' C105 ) => ( ( 'X' C105 ) 'or' ( 'X' ( C104 '&&' ( C104 'Us' C105 ) ) ) ) ) in D39 by L736 , L719;
L738: (for B103 being set holds (B103 is  with_LTL_axioms implies ( ( ( 'X' C105 ) 'or' ( 'X' ( C104 '&&' ( C104 'Us' C105 ) ) ) ) => ( C104 'Us' C105 ) ) in B103)) by L716;
thus L739: ( ( ( 'X' C105 ) 'or' ( 'X' ( C104 '&&' ( C104 'Us' C105 ) ) ) ) => ( C104 'Us' C105 ) ) in D39 by L738 , L719;
L740: (for B104 being set holds (B104 is  with_LTL_axioms implies ( ( C104 'Us' C105 ) => ( 'X' ( 'F' C105 ) ) ) in B104)) by L716;
thus L741: ( ( C104 'Us' C105 ) => ( 'X' ( 'F' C105 ) ) ) in D39 by L740 , L719;
end;

let C106 being (Subset of ( LTLB_WFF ));
assume L742: C106 is  with_LTL_axioms;
let C107 being set;
assume L743: C107 in D39;
thus L744: C107 in C106 by L743 , L719 , L742;
end;
uniqueness
proof
let C108 , C109 being (Subset of ( LTLB_WFF ));
assume L745: (C108 is  with_LTL_axioms & (for B105 being (Subset of ( LTLB_WFF )) holds (B105 is  with_LTL_axioms implies C108 c= B105)) & C109 is  with_LTL_axioms & (for B106 being (Subset of ( LTLB_WFF )) holds (B106 is  with_LTL_axioms implies C109 c= B106)));
L746: (C108 c= C109 & C109 c= C108) by L745;
thus L747: C108 = C109 by L746 , XBOOLE_0:def 10;
end;
end;
registration
cluster ( LTL_axioms ) ->  with_LTL_axioms;
coherence by L718;
end;
theorem
L750: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds ( R4 => ( R5 => R4 ) ) in ( LTL_axioms )))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
L751: ( R4 => ( R5 => R4 ) ) is  LTL_TAUT_OF_PL
proof
let C110 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
L752: (( ( VAL C110 ) . R4 ) = ( 0 ) or ( ( VAL C110 ) . R4 ) = 1) by XBOOLEAN:def 3;
thus L753: ( ( VAL C110 ) . ( R4 => ( R5 => R4 ) ) ) = ( ( ( VAL C110 ) . R4 ) => ( ( VAL C110 ) . ( R5 => R4 ) ) ) by L626
.= ( ( ( VAL C110 ) . R4 ) => ( ( ( VAL C110 ) . R5 ) => ( ( VAL C110 ) . R4 ) ) ) by L626
.= 1 by L752;
end;
thus L754: ( R4 => ( R5 => R4 ) ) in ( LTL_axioms ) by L751 , L716;
end;
theorem
L755: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds ( ( R4 => ( R5 => R6 ) ) => ( ( R4 => R5 ) => ( R4 => R6 ) ) ) in ( LTL_axioms ))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
L756: ( ( R4 => ( R5 => R6 ) ) => ( ( R4 => R5 ) => ( R4 => R6 ) ) ) is  LTL_TAUT_OF_PL
proof
let C111 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
L757: (( ( VAL C111 ) . R4 ) = ( 0 ) or ( ( VAL C111 ) . R4 ) = 1) by XBOOLEAN:def 3;
L758: (( ( VAL C111 ) . R5 ) = ( 0 ) or ( ( VAL C111 ) . R5 ) = 1) by XBOOLEAN:def 3;
L759: (( ( VAL C111 ) . R6 ) = ( 0 ) or ( ( VAL C111 ) . R6 ) = 1) by XBOOLEAN:def 3;
thus L760: ( ( VAL C111 ) . ( ( R4 => ( R5 => R6 ) ) => ( ( R4 => R5 ) => ( R4 => R6 ) ) ) ) = ( ( ( VAL C111 ) . ( R4 => ( R5 => R6 ) ) ) => ( ( VAL C111 ) . ( ( R4 => R5 ) => ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C111 ) . R4 ) => ( ( VAL C111 ) . ( R5 => R6 ) ) ) => ( ( VAL C111 ) . ( ( R4 => R5 ) => ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C111 ) . R4 ) => ( ( ( VAL C111 ) . R5 ) => ( ( VAL C111 ) . R6 ) ) ) => ( ( VAL C111 ) . ( ( R4 => R5 ) => ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C111 ) . R4 ) => ( ( ( VAL C111 ) . R5 ) => ( ( VAL C111 ) . R6 ) ) ) => ( ( ( VAL C111 ) . ( R4 => R5 ) ) => ( ( VAL C111 ) . ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C111 ) . R4 ) => ( ( ( VAL C111 ) . R5 ) => ( ( VAL C111 ) . R6 ) ) ) => ( ( ( ( VAL C111 ) . R4 ) => ( ( VAL C111 ) . R5 ) ) => ( ( VAL C111 ) . ( R4 => R6 ) ) ) ) by L626
.= 1 by L757 , L758 , L759 , L626;
end;
thus L761: ( ( R4 => ( R5 => R6 ) ) => ( ( R4 => R5 ) => ( R4 => R6 ) ) ) in ( LTL_axioms ) by L756 , L716;
end;
definition
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
pred R4 NEX_rule R5
means
:L762: R5 = ( 'X' R4 )
;let R6 being (Element of ( LTLB_WFF ));
pred R4 , R5 MP_rule R6
means
:L763: R5 = ( R4 => R6 )
;pred R4 , R5 IND_rule R6
means
:L764: (ex R8 being (Element of ( LTLB_WFF )) st (ex R9 being (Element of ( LTLB_WFF )) st (R4 = ( R8 => R9 ) & R5 = ( R8 => ( 'X' R8 ) ) & R6 = ( R8 => ( 'G' R9 ) ))))
;end;
registration
cluster ( LTL_axioms ) -> non  empty;
coherence by L716;
end;
definition
let R8 being (Element of ( LTLB_WFF ));
attr R8 is  axltl1
means
:L767: (ex R9 being (Element of ( LTLB_WFF )) st R8 = ( ( 'not' ( 'X' R9 ) ) => ( 'X' ( 'not' R9 ) ) ));
attr R8 is  axltl1a
means
:L768: (ex R9 being (Element of ( LTLB_WFF )) st R8 = ( ( 'X' ( 'not' R9 ) ) => ( 'not' ( 'X' R9 ) ) ));
attr R8 is  axltl2
means
:L769: (ex R9 being (Element of ( LTLB_WFF )) st (ex R10 being (Element of ( LTLB_WFF )) st R8 = ( ( 'X' ( R9 => R10 ) ) => ( ( 'X' R9 ) => ( 'X' R10 ) ) )));
attr R8 is  axltl3
means
:L770: (ex R9 being (Element of ( LTLB_WFF )) st R8 = ( ( 'G' R9 ) => ( R9 '&&' ( 'X' ( 'G' R9 ) ) ) ));
attr R8 is  axltl4
means
:L771: (ex R9 being (Element of ( LTLB_WFF )) st (ex R10 being (Element of ( LTLB_WFF )) st R8 = ( ( R9 'Us' R10 ) => ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) )));
attr R8 is  axltl5
means
:L772: (ex R9 being (Element of ( LTLB_WFF )) st (ex R10 being (Element of ( LTLB_WFF )) st R8 = ( ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) => ( R9 'Us' R10 ) )));
attr R8 is  axltl6
means
:L773: (ex R9 being (Element of ( LTLB_WFF )) st (ex R10 being (Element of ( LTLB_WFF )) st R8 = ( ( R9 'Us' R10 ) => ( 'X' ( 'F' R10 ) ) )));
end;
theorem
L775: (for B107 being (Element of ( LTL_axioms )) holds (B107 is  LTL_TAUT_OF_PL or B107 is  axltl1 or B107 is  axltl1a or B107 is  axltl2 or B107 is  axltl3 or B107 is  axltl4 or B107 is  axltl5 or B107 is  axltl6))
proof
defpred S17[ (Element of ( LTL_axioms )) ] means ($1 is  LTL_TAUT_OF_PL or $1 is  axltl1 or $1 is  axltl1a or $1 is  axltl2 or $1 is  axltl3 or $1 is  axltl4 or $1 is  axltl5 or $1 is  axltl6);
set D40 = { B108 where B108 is (Element of ( LTL_axioms )) : S17[ B108 ] };
L776: D40 c= ( LTLB_WFF )
proof
let C112 being set;
assume L777: C112 in D40;
L778: (ex B109 being (Element of ( LTL_axioms )) st (C112 = B109 & S17[ B109 ])) by L777;
thus L779: C112 in ( LTLB_WFF ) by L778;
end;
reconsider D41 = D40 as (Subset of ( LTLB_WFF )) by L776;
let C113 being (Element of ( LTL_axioms ));
L780: D41 is  with_LTL_axioms
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
thus L781: (R4 is  LTL_TAUT_OF_PL implies R4 in D41)
proof
assume L782: R4 is  LTL_TAUT_OF_PL;
reconsider D42 = R4 as (Element of ( LTL_axioms )) by L782 , L716;
L783: S17[ D42 ] by L782;
thus L784: thesis by L783;
end;

thus L785: ( ( 'not' ( 'X' R4 ) ) => ( 'X' ( 'not' R4 ) ) ) in D41
proof
reconsider D43 = ( ( 'not' ( 'X' R4 ) ) => ( 'X' ( 'not' R4 ) ) ) as (Element of ( LTL_axioms )) by L716;
L786: S17[ D43 ] by L767;
thus L787: thesis by L786;
end;

thus L788: ( ( 'X' ( 'not' R4 ) ) => ( 'not' ( 'X' R4 ) ) ) in D41
proof
reconsider D44 = ( ( 'X' ( 'not' R4 ) ) => ( 'not' ( 'X' R4 ) ) ) as (Element of ( LTL_axioms )) by L716;
L789: S17[ D44 ] by L768;
thus L790: thesis by L789;
end;

thus L791: ( ( 'X' ( R4 => R5 ) ) => ( ( 'X' R4 ) => ( 'X' R5 ) ) ) in D41
proof
reconsider D45 = ( ( 'X' ( R4 => R5 ) ) => ( ( 'X' R4 ) => ( 'X' R5 ) ) ) as (Element of ( LTL_axioms )) by L716;
L792: S17[ D45 ] by L769;
thus L793: thesis by L792;
end;

thus L794: ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) in D41
proof
reconsider D46 = ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) as (Element of ( LTL_axioms )) by L716;
L795: S17[ D46 ] by L770;
thus L796: thesis by L795;
end;

thus L797: ( ( R4 'Us' R5 ) => ( ( 'X' R5 ) 'or' ( 'X' ( R4 '&&' ( R4 'Us' R5 ) ) ) ) ) in D41
proof
reconsider D47 = ( ( R4 'Us' R5 ) => ( ( 'X' R5 ) 'or' ( 'X' ( R4 '&&' ( R4 'Us' R5 ) ) ) ) ) as (Element of ( LTL_axioms )) by L716;
L798: S17[ D47 ] by L771;
thus L799: thesis by L798;
end;

thus L800: ( ( ( 'X' R5 ) 'or' ( 'X' ( R4 '&&' ( R4 'Us' R5 ) ) ) ) => ( R4 'Us' R5 ) ) in D41
proof
reconsider D48 = ( ( ( 'X' R5 ) 'or' ( 'X' ( R4 '&&' ( R4 'Us' R5 ) ) ) ) => ( R4 'Us' R5 ) ) as (Element of ( LTL_axioms )) by L716;
L801: S17[ D48 ] by L772;
thus L802: thesis by L801;
end;

thus L803: ( ( R4 'Us' R5 ) => ( 'X' ( 'F' R5 ) ) ) in D41
proof
reconsider D49 = ( ( R4 'Us' R5 ) => ( 'X' ( 'F' R5 ) ) ) as (Element of ( LTL_axioms )) by L716;
L804: S17[ D49 ] by L773;
thus L805: thesis by L804;
end;

end;
L804: (C113 in ( LTL_axioms ) & ( LTL_axioms ) c= D41) by L780 , L718;
L805: C113 in D41 by L804;
L806: (ex B110 being (Element of ( LTL_axioms )) st (C113 = B110 & S17[ B110 ])) by L805;
thus L807: S17[ C113 ] by L806;
end;
theorem
L808: (for R8 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds ((R8 is  axltl1 or R8 is  axltl1a or R8 is  axltl2 or R8 is  axltl3 or R8 is  axltl4 or R8 is  axltl5 or R8 is  axltl6) implies R11 |= R8)))
proof
let R8 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L809: (R8 is  axltl1 or R8 is  axltl1a or R8 is  axltl2 or R8 is  axltl3 or R8 is  axltl4 or R8 is  axltl5 or R8 is  axltl6);
let R23 being LTLModel;
assume L810: R23 |= R11;
let C114 being (Element of ( NAT ));
per cases  by L809;
suppose L811: R8 is  axltl1;

consider C115 being (Element of ( LTLB_WFF )) such that L812: R8 = ( ( 'not' ( 'X' C115 ) ) => ( 'X' ( 'not' C115 ) ) ) by L811 , L767;
thus L813: thesis by L812 , L382;
end;
suppose L814: R8 is  axltl1a;

consider C116 being (Element of ( LTLB_WFF )) such that L815: R8 = ( ( 'X' ( 'not' C116 ) ) => ( 'not' ( 'X' C116 ) ) ) by L814 , L768;
thus L816: thesis by L815 , L385;
end;
suppose L817: R8 is  axltl2;

consider C117 , C118 being (Element of ( LTLB_WFF )) such that L818: R8 = ( ( 'X' ( C117 => C118 ) ) => ( ( 'X' C117 ) => ( 'X' C118 ) ) ) by L817 , L769;
thus L819: thesis by L818 , L388;
end;
suppose L820: R8 is  axltl3;

consider C119 being (Element of ( LTLB_WFF )) such that L821: R8 = ( ( 'G' C119 ) => ( C119 '&&' ( 'X' ( 'G' C119 ) ) ) ) by L820 , L770;
thus L822: thesis by L821 , L392;
end;
suppose L823: R8 is  axltl4;

consider R9 being (Element of ( LTLB_WFF )), R10 being (Element of ( LTLB_WFF )) such that L824: R8 = ( ( R9 'Us' R10 ) => ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) ) by L823 , L771;
thus L825: thesis by L824 , L406;
end;
suppose L826: R8 is  axltl5;

consider R9 being (Element of ( LTLB_WFF )), R10 being (Element of ( LTLB_WFF )) such that L827: R8 = ( ( ( 'X' R10 ) 'or' ( 'X' ( R9 '&&' ( R9 'Us' R10 ) ) ) ) => ( R9 'Us' R10 ) ) by L826 , L772;
thus L828: thesis by L827 , L436;
end;
suppose L829: R8 is  axltl6;

consider R9 being (Element of ( LTLB_WFF )), R10 being (Element of ( LTLB_WFF )) such that L830: R8 = ( ( R9 'Us' R10 ) => ( 'X' ( 'F' R10 ) ) ) by L829 , L773;
thus L831: thesis by L830 , L469;
end;
end;
definition
let C120 being Nat;
let R19 being (FinSequence of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
pred  prc R19 , R13 , C120
means
:L833: (( R19 . C120 ) in ( LTL_axioms ) or ( R19 . C120 ) in R13 or (ex B111 , B112 being Nat st (1 <= B111 & B111 < C120 & 1 <= B112 & B112 < C120 & (( R19 /. B111 ) , ( R19 /. B112 ) MP_rule ( R19 /. C120 ) or ( R19 /. B111 ) , ( R19 /. B112 ) IND_rule ( R19 /. C120 )))) or (ex B113 being Nat st (1 <= B113 & B113 < C120 & ( R19 /. B113 ) NEX_rule ( R19 /. C120 ))))
;end;
definition
let R13 being (Subset of ( LTLB_WFF ));
let R4 being (Element of ( LTLB_WFF ));
pred R13 |- R4
means
:L835: (ex R19 being (FinSequence of ( LTLB_WFF )) st (( R19 . ( len R19 ) ) = R4 & 1 <= ( len R19 ) & (for B114 being Nat holds ((1 <= B114 & B114 <= ( len R19 )) implies  prc R19 , R13 , B114))))
;end;
theorem
L837: (for R13 being (Subset of ( LTLB_WFF )) holds (for R19 being (FinSequence of ( LTLB_WFF )) holds (for R21 being (FinSequence of ( LTLB_WFF )) holds (for B115 , B116 being Nat holds ((( B116 + ( len R19 ) ) <= ( len R21 ) & (for B117 being Nat holds ((1 <= B117 & B117 <= ( len R19 )) implies ( R19 . B117 ) = ( R21 . ( B117 + B116 ) ))) & 1 <= B115 & B115 <= ( len R19 )) implies ( prc R19 , R13 , B115 implies  prc R21 , R13 , ( B115 + B116 )))))))
proof
let R13 being (Subset of ( LTLB_WFF ));
let R19 being (FinSequence of ( LTLB_WFF ));
let R21 being (FinSequence of ( LTLB_WFF ));
let C121 , C122 being Nat;
assume that
L838: ( C122 + ( len R19 ) ) <= ( len R21 )
and
L839: (for B118 being Nat holds ((1 <= B118 & B118 <= ( len R19 )) implies ( R19 . B118 ) = ( R21 . ( B118 + C122 ) )))
and
L840: 1 <= C121
and
L841: C121 <= ( len R19 );
L842: ( C121 + C122 ) <= ( ( len R19 ) + C122 ) by L841 , XREAL_1:6;
L843: ( C121 + C122 ) <= ( len R21 ) by L842 , L838 , XXREAL_0:2;
L844: ( R19 /. C121 ) = ( R19 . C121 ) by L840 , L841 , L1
.= ( R21 . ( C121 + C122 ) ) by L839 , L840 , L841
.= ( R21 /. ( C121 + C122 ) ) by L840 , L843 , L1 , NAT_1:12;
assume L845:  prc R19 , R13 , C121;
per cases  by L845 , L833;
suppose L846: ( R19 . C121 ) in ( LTL_axioms );

L847: ( R21 . ( C121 + C122 ) ) in ( LTL_axioms ) by L846 , L839 , L840 , L841;
thus L848:  prc R21 , R13 , ( C121 + C122 ) by L847 , L833;
end;
suppose L849: ( R19 . C121 ) in R13;

L850: ( R21 . ( C121 + C122 ) ) in R13 by L849 , L839 , L840 , L841;
thus L851:  prc R21 , R13 , ( C121 + C122 ) by L850 , L833;
end;
suppose L852: (ex B119 , B120 being Nat st (1 <= B119 & B119 < C121 & 1 <= B120 & B120 < C121 & (( R19 /. B119 ) , ( R19 /. B120 ) MP_rule ( R19 /. C121 ) or ( R19 /. B119 ) , ( R19 /. B120 ) IND_rule ( R19 /. C121 ))));

consider C123 , C124 being Nat such that L853: 1 <= C123 and L854: C123 < C121 and L855: 1 <= C124 and L856: C124 < C121 and L857: (( R19 /. C123 ) , ( R19 /. C124 ) MP_rule ( R19 /. C121 ) or ( R19 /. C123 ) , ( R19 /. C124 ) IND_rule ( R19 /. C121 )) by L852;
L858: (1 <= ( C123 + C122 ) & ( C123 + C122 ) < ( C121 + C122 )) by L853 , L854 , NAT_1:12 , XREAL_1:8;
L859: C124 <= ( len R19 ) by L841 , L856 , XXREAL_0:2;
L860: ( C124 + C122 ) <= ( ( len R19 ) + C122 ) by L859 , XREAL_1:6;
L861: ( C124 + C122 ) <= ( len R21 ) by L860 , L838 , XXREAL_0:2;
L862: C123 <= ( len R19 ) by L841 , L854 , XXREAL_0:2;
L863: ( C123 + C122 ) <= ( ( len R19 ) + C122 ) by L862 , XREAL_1:6;
L864: ( C123 + C122 ) <= ( len R21 ) by L863 , L838 , XXREAL_0:2;
L865: ( R19 /. C124 ) = ( R19 . C124 ) by L855 , L859 , L1
.= ( R21 . ( C124 + C122 ) ) by L839 , L855 , L859
.= ( R21 /. ( C124 + C122 ) ) by L855 , L861 , L1 , NAT_1:12;
L866: (1 <= ( C124 + C122 ) & ( C124 + C122 ) < ( C121 + C122 )) by L855 , L856 , NAT_1:12 , XREAL_1:8;
L867: ( R19 /. C123 ) = ( R19 . C123 ) by L853 , L862 , L1
.= ( R21 . ( C123 + C122 ) ) by L839 , L853 , L862
.= ( R21 /. ( C123 + C122 ) ) by L853 , L864 , L1 , NAT_1:12;
thus L868:  prc R21 , R13 , ( C121 + C122 ) by L867 , L844 , L857 , L858 , L866 , L865 , L833;
end;
suppose L869: (ex B121 being Nat st (1 <= B121 & B121 < C121 & ( R19 /. B121 ) NEX_rule ( R19 /. C121 )));

consider C125 being Nat such that L870: 1 <= C125 and L871: C125 < C121 and L872: ( R19 /. C125 ) NEX_rule ( R19 /. C121 ) by L869;
L873: (1 <= ( C125 + C122 ) & ( C125 + C122 ) < ( C121 + C122 )) by L870 , L871 , NAT_1:12 , XREAL_1:8;
L874: C125 <= ( len R19 ) by L841 , L871 , XXREAL_0:2;
L875: ( C125 + C122 ) <= ( ( len R19 ) + C122 ) by L874 , XREAL_1:6;
L876: ( C125 + C122 ) <= ( len R21 ) by L875 , L838 , XXREAL_0:2;
L877: ( R19 /. C125 ) = ( R19 . C125 ) by L870 , L874 , L1
.= ( R21 . ( C125 + C122 ) ) by L839 , L870 , L874
.= ( R21 /. ( C125 + C122 ) ) by L870 , L876 , L1 , NAT_1:12;
thus L878:  prc R21 , R13 , ( C121 + C122 ) by L877 , L844 , L872 , L873 , L833;
end;
end;
theorem
L880: (for R13 being (Subset of ( LTLB_WFF )) holds (for R19 being (FinSequence of ( LTLB_WFF )) holds (for R20 being (FinSequence of ( LTLB_WFF )) holds (for R21 being (FinSequence of ( LTLB_WFF )) holds ((R21 = ( R19 ^ R20 ) & 1 <= ( len R19 ) & 1 <= ( len R20 ) & (for B122 being Nat holds ((1 <= B122 & B122 <= ( len R19 )) implies  prc R19 , R13 , B122)) & (for B123 being Nat holds ((1 <= B123 & B123 <= ( len R20 )) implies  prc R20 , R13 , B123))) implies (for B124 being Nat holds ((1 <= B124 & B124 <= ( len R21 )) implies  prc R21 , R13 , B124)))))))
proof
let R13 being (Subset of ( LTLB_WFF ));
let R19 being (FinSequence of ( LTLB_WFF ));
let R20 being (FinSequence of ( LTLB_WFF ));
let R21 being (FinSequence of ( LTLB_WFF ));
assume that
L881: R21 = ( R19 ^ R20 )
and
L882: 1 <= ( len R19 )
and
L883: 1 <= ( len R20 )
and
L884: (for B125 being Nat holds ((1 <= B125 & B125 <= ( len R19 )) implies  prc R19 , R13 , B125))
and
L885: (for B126 being Nat holds ((1 <= B126 & B126 <= ( len R20 )) implies  prc R20 , R13 , B126));
L886: ( len R21 ) = ( ( len R19 ) + ( len R20 ) ) by L881 , FINSEQ_1:22;
L887: (for B127 being Nat holds ((1 <= B127 & B127 <= ( len R20 )) implies ( R20 . B127 ) = ( R21 . ( B127 + ( len R19 ) ) ))) by L881 , FINSEQ_1:65;
let C126 being Nat;
assume that
L888: 1 <= C126
and
L889: C126 <= ( len R21 );
per cases  by NAT_1:13;
suppose L890: C126 <= ( len R19 );

L891: ( R19 /. C126 ) = ( R19 . C126 ) by L890 , L888 , L1
.= ( R21 . C126 ) by L881 , L888 , L890 , FINSEQ_1:64
.= ( R21 /. C126 ) by L888 , L889 , L1;
L892:  prc R19 , R13 , C126 by L884 , L888 , L890;
per cases  by L892 , L833;
suppose L893: ( R19 . C126 ) in ( LTL_axioms );

L894: ( R21 . C126 ) in ( LTL_axioms ) by L893 , L881 , L888 , L890 , FINSEQ_1:64;
thus L895:  prc R21 , R13 , C126 by L894 , L833;
end;
suppose L896: ( R19 . C126 ) in R13;

L897: ( R21 . C126 ) in R13 by L896 , L881 , L888 , L890 , FINSEQ_1:64;
thus L898:  prc R21 , R13 , C126 by L897 , L833;
end;
suppose L899: (ex B128 , B129 being Nat st (1 <= B128 & B128 < C126 & 1 <= B129 & B129 < C126 & (( R19 /. B128 ) , ( R19 /. B129 ) MP_rule ( R19 /. C126 ) or ( R19 /. B128 ) , ( R19 /. B129 ) IND_rule ( R19 /. C126 ))));

consider C127 , C128 being Nat such that L900: 1 <= C127 and L901: C127 < C126 and L902: 1 <= C128 and L903: C128 < C126 and L904: (( R19 /. C127 ) , ( R19 /. C128 ) MP_rule ( R19 /. C126 ) or ( R19 /. C127 ) , ( R19 /. C128 ) IND_rule ( R19 /. C126 )) by L899;
L905: C128 <= ( len R19 ) by L890 , L903 , XXREAL_0:2;
L906: C128 <= ( len R21 ) by L905 , L886 , NAT_1:12;
L907: ( R19 /. C128 ) = ( R19 . C128 ) by L902 , L905 , L1
.= ( R21 . C128 ) by L881 , L902 , L905 , FINSEQ_1:64
.= ( R21 /. C128 ) by L902 , L906 , L1;
L908: C127 <= ( len R19 ) by L890 , L901 , XXREAL_0:2;
L909: C127 <= ( len R21 ) by L908 , L886 , NAT_1:12;
L910: ( R19 /. C127 ) = ( R19 . C127 ) by L900 , L908 , L1
.= ( R21 . C127 ) by L881 , L900 , L908 , FINSEQ_1:64
.= ( R21 /. C127 ) by L900 , L909 , L1;
thus L911:  prc R21 , R13 , C126 by L910 , L891 , L900 , L901 , L902 , L903 , L904 , L907 , L833;
end;
suppose L912: (ex B130 being Nat st (1 <= B130 & B130 < C126 & ( R19 /. B130 ) NEX_rule ( R19 /. C126 )));

consider C129 being Nat such that L913: 1 <= C129 and L914: C129 < C126 and L915: ( R19 /. C129 ) NEX_rule ( R19 /. C126 ) by L912;
L916: C129 <= ( len R19 ) by L890 , L914 , XXREAL_0:2;
L917: C129 <= ( len R21 ) by L916 , L886 , NAT_1:12;
L918: ( R19 /. C129 ) = ( R19 . C129 ) by L913 , L916 , L1
.= ( R21 . C129 ) by L881 , L913 , L916 , FINSEQ_1:64
.= ( R21 /. C129 ) by L913 , L917 , L1;
thus L919:  prc R21 , R13 , C126 by L918 , L891 , L913 , L914 , L915 , L833;
end;
end;
suppose L921: ( ( len R19 ) + 1 ) <= C126;

set D50 = ( C126 -' ( len R19 ) );
L922: C126 <= ( ( len R19 ) + ( len R20 ) ) by L881 , L889 , FINSEQ_1:22;
L923: ( C126 -' ( len R19 ) ) <= ( ( ( len R19 ) + ( len R20 ) ) -' ( len R19 ) ) by L922 , NAT_D:42;
L924: D50 <= ( len R20 ) by L923 , NAT_D:34;
L925: 1 <= D50 by L921 , NAT_D:55;
L926:  prc R21 , R13 , ( D50 + ( len R19 ) ) by L925 , L885 , L886 , L887 , L924 , L837;
thus L927:  prc R21 , R13 , C126 by L926 , L921 , NAT_D:43 , NAT_D:55;
end;
end;
theorem
L929: (for R4 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds (for R19 being (FinSequence of ( LTLB_WFF )) holds (for R20 being (FinSequence of ( LTLB_WFF )) holds ((R19 = ( R20 ^ <* R4 *> ) & 1 <= ( len R20 ) & (for B131 being Nat holds ((1 <= B131 & B131 <= ( len R20 )) implies  prc R20 , R13 , B131)) &  prc R19 , R13 , ( len R19 )) implies ((for B132 being Nat holds ((1 <= B132 & B132 <= ( len R19 )) implies  prc R19 , R13 , B132)) & R13 |- R4))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
let R19 being (FinSequence of ( LTLB_WFF ));
let R20 being (FinSequence of ( LTLB_WFF ));
assume that
L930: R19 = ( R20 ^ <* R4 *> )
and
L931: 1 <= ( len R20 )
and
L932: (for B133 being Nat holds ((1 <= B133 & B133 <= ( len R20 )) implies  prc R20 , R13 , B133));
L933: ( len R19 ) = ( ( len R20 ) + ( len <* R4 *> ) ) by L930 , FINSEQ_1:22
.= ( ( len R20 ) + 1 ) by FINSEQ_1:39;
L934: 1 <= ( len R19 ) by L933 , XREAL_1:31;
assume L935:  prc R19 , R13 , ( len R19 );
L936: ( ( 0 ) + ( len R20 ) ) <= ( len R19 ) by L933 , NAT_1:12;
L937:
now
let C130 being Nat;
assume that
L938: 1 <= C130
and
L939: C130 <= ( len R19 );
L940: (C130 < ( ( len R20 ) + 1 ) or C130 = ( ( len R20 ) + 1 )) by L933 , L939 , XXREAL_0:1;
L941: (for B134 being Nat holds ((1 <= B134 & B134 <= ( len R20 )) implies ( R20 . B134 ) = ( R19 . ( B134 + ( 0 ) ) ))) by L930 , FINSEQ_1:64;
per cases  by L933 , L940 , NAT_1:13;
suppose L942: C130 <= ( len R20 );

L943:  prc R19 , R13 , ( C130 + ( 0 ) ) by L942 , L932 , L936 , L938 , L941 , L837;
thus L944:  prc R19 , R13 , C130 by L943;
end;
suppose L945: C130 = ( len R19 );

thus L946:  prc R19 , R13 , C130 by L945 , L935;
end;
end;
thus L948: (for B135 being Nat holds ((1 <= B135 & B135 <= ( len R19 )) implies  prc R19 , R13 , B135)) by L937;
L949: ( R19 . ( len R19 ) ) = ( R19 . ( ( len R20 ) + ( len <* R4 *> ) ) ) by L930 , FINSEQ_1:22
.= ( R19 . ( ( len R20 ) + 1 ) ) by FINSEQ_1:39
.= R4 by L930 , FINSEQ_1:42;
thus L950: R13 |- R4 by L949 , L934 , L937 , L835;
end;
theorem
L951: (for R8 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |- R8 implies R11 |= R8)))
proof
let R8 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L952: R11 |- R8;
consider R19 being (FinSequence of ( LTLB_WFF )) such that L953: ( R19 . ( len R19 ) ) = R8 and L954: 1 <= ( len R19 ) and L955: (for B136 being Nat holds ((1 <= B136 & B136 <= ( len R19 )) implies  prc R19 , R11 , B136)) by L952 , L835;
defpred S18[ Nat ] means ((1 <= $1 & $1 <= ( len R19 )) implies R11 |= ( R19 /. $1 ));
L956: (for B137 being Nat holds ((for B138 being Nat holds (B138 < B137 implies S18[ B138 ])) implies S18[ B137 ]))
proof
let C131 being Nat;
assume L957: (for B139 being Nat holds (B139 < C131 implies S18[ B139 ]));
per cases  by NAT_1:14;
suppose L958: C131 = ( 0 );

thus L959: S18[ C131 ] by L958;
end;
suppose L960: (not C131 < 1);

assume that
L961: 1 <= C131
and
L962: C131 <= ( len R19 );
L963:  prc R19 , R11 , C131 by L955 , L961 , L962;
per cases  by L963 , L833;
suppose L964: ( R19 . C131 ) in ( LTL_axioms );

L965: ( R19 /. C131 ) in ( LTL_axioms ) by L964 , L961 , L962 , L1;
per cases  by L965 , L775;
suppose L966: ( R19 /. C131 ) is  LTL_TAUT_OF_PL;

thus L967: R11 |= ( R19 /. C131 ) by L966 , L707;
end;
suppose L968: (( R19 /. C131 ) is  axltl1 or ( R19 /. C131 ) is  axltl1a or ( R19 /. C131 ) is  axltl2 or ( R19 /. C131 ) is  axltl3 or ( R19 /. C131 ) is  axltl4 or ( R19 /. C131 ) is  axltl5 or ( R19 /. C131 ) is  axltl6);

thus L969: R11 |= ( R19 /. C131 ) by L968 , L808;
end;
end;
suppose L971: ( R19 . C131 ) in R11;

L972: ( R19 /. C131 ) in R11 by L971 , L961 , L962 , L1;
thus L973: R11 |= ( R19 /. C131 )
proof
let R23 being LTLModel;
assume L974: R23 |= R11;
thus L975: R23 |= ( R19 /. C131 ) by L974 , L972 , L486;
end;

end;
suppose L974: (ex B140 , B141 being Nat st (1 <= B140 & B140 < C131 & 1 <= B141 & B141 < C131 & (( R19 /. B140 ) , ( R19 /. B141 ) MP_rule ( R19 /. C131 ) or ( R19 /. B140 ) , ( R19 /. B141 ) IND_rule ( R19 /. C131 ))));

consider C132 , C133 being Nat such that L975: 1 <= C132 and L976: C132 < C131 and L977: 1 <= C133 and L978: C133 < C131 and L979: (( R19 /. C132 ) , ( R19 /. C133 ) MP_rule ( R19 /. C131 ) or ( R19 /. C132 ) , ( R19 /. C133 ) IND_rule ( R19 /. C131 )) by L974;
L980: C133 <= ( len R19 ) by L962 , L978 , XXREAL_0:2;
L981: R11 |= ( R19 /. C133 ) by L980 , L957 , L977 , L978;
L982: C132 <= ( len R19 ) by L962 , L976 , XXREAL_0:2;
per cases  by L979;
suppose L983: ( R19 /. C132 ) , ( R19 /. C133 ) MP_rule ( R19 /. C131 );

L984: R11 |= ( ( R19 /. C132 ) => ( R19 /. C131 ) ) by L983 , L981 , L763;
thus L985: R11 |= ( R19 /. C131 ) by L984 , L957 , L975 , L976 , L982 , L507;
end;
suppose L986: ( R19 /. C132 ) , ( R19 /. C133 ) IND_rule ( R19 /. C131 );

consider R8 being (Element of ( LTLB_WFF )), R9 being (Element of ( LTLB_WFF )) such that L987: ( R19 /. C132 ) = ( R8 => R9 ) and L988: (( R19 /. C133 ) = ( R8 => ( 'X' R8 ) ) & ( R19 /. C131 ) = ( R8 => ( 'G' R9 ) )) by L986 , L764;
L989: R11 |= ( R8 => R9 ) by L957 , L975 , L976 , L982 , L987;
thus L990: R11 |= ( R19 /. C131 ) by L989 , L981 , L988 , L528;
end;
end;
suppose L992: (ex B142 being Nat st (1 <= B142 & B142 < C131 & ( R19 /. B142 ) NEX_rule ( R19 /. C131 )));

consider C134 being Nat such that L993: 1 <= C134 and L994: C134 < C131 and L995: ( R19 /. C134 ) NEX_rule ( R19 /. C131 ) by L992;
L996: S18[ C134 ] by L957 , L994;
L997: R11 |= ( 'X' ( R19 /. C134 ) ) by L996 , L962 , L993 , L994 , L517 , XXREAL_0:2;
thus L998: R11 |= ( R19 /. C131 ) by L997 , L995 , L762;
end;
end;
end;
L1001: (for B143 being Nat holds S18[ B143 ]) from NAT_1:sch 4(L956);
L1002: ( R19 /. ( len R19 ) ) = R8 by L953 , L954 , L1;
thus L1003: R11 |= R8 by L1002 , L954 , L1001;
end;
begin
theorem
L1004: (for R4 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds ((R4 in ( LTL_axioms ) or R4 in R13) implies R13 |- R4)))
proof
let R4 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
defpred S19[ set , set ] means $2 = R4;
L1005: (for B144 being Nat holds (B144 in ( Seg 1 ) implies (ex B145 being (Element of ( LTLB_WFF )) st S19[ B144 , B145 ])));
consider R22 being (FinSequence of ( LTLB_WFF )) such that L1006: (( dom R22 ) = ( Seg 1 ) & (for B146 being Nat holds (B146 in ( Seg 1 ) implies S19[ B146 , ( R22 . B146 ) ]))) from FINSEQ_1:sch 5(L1005);
L1007: ( len R22 ) = 1 by L1006 , FINSEQ_1:def 3;
L1008: 1 in ( Seg 1 ) by FINSEQ_1:2 , TARSKI:def 1;
L1009: ( R22 . 1 ) = R4 by L1008 , L1006;
assume L1010: (R4 in ( LTL_axioms ) or R4 in R13);
L1011: (for B147 being Nat holds ((1 <= B147 & B147 <= ( len R22 )) implies  prc R22 , R13 , B147))
proof
let C135 being Nat;
assume L1012: (1 <= C135 & C135 <= ( len R22 ));
per cases  by L1010;
suppose L1013: R4 in ( LTL_axioms );

L1014: ( R22 . C135 ) in ( LTL_axioms ) by L1013 , L1007 , L1009 , L1012 , XXREAL_0:1;
thus L1015: thesis by L1014 , L833;
end;
suppose L1016: R4 in R13;

L1017: ( R22 . C135 ) in R13 by L1016 , L1007 , L1009 , L1012 , XXREAL_0:1;
thus L1018: thesis by L1017 , L833;
end;
end;
thus L1020: R13 |- R4 by L1011 , L1007 , L1009 , L835;
end;
theorem
L1021: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds ((R13 |- R4 & R13 |- ( R4 => R5 )) implies R13 |- R5))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume L1022: R13 |- R4;
consider R19 being (FinSequence of ( LTLB_WFF )) such that L1023: ( R19 . ( len R19 ) ) = R4 and L1024: 1 <= ( len R19 ) and L1025: (for B148 being Nat holds ((1 <= B148 & B148 <= ( len R19 )) implies  prc R19 , R13 , B148)) by L1022 , L835;
set D51 = ( len R19 );
assume L1026: R13 |- ( R4 => R5 );
consider R20 being (FinSequence of ( LTLB_WFF )) such that L1027: ( R20 . ( len R20 ) ) = ( R4 => R5 ) and L1028: 1 <= ( len R20 ) and L1029: (for B149 being Nat holds ((1 <= B149 & B149 <= ( len R20 )) implies  prc R20 , R13 , B149)) by L1026 , L835;
L1030: 1 <= ( ( len R19 ) + ( len R20 ) ) by L1024 , NAT_1:12;
set D52 = ( ( R19 ^ R20 ) ^ <* R5 *> );
L1031: D52 = ( R19 ^ ( R20 ^ <* R5 *> ) ) by FINSEQ_1:32;
L1032: (for B150 being Nat holds ((1 <= B150 & B150 <= ( len R20 )) implies ( D52 . ( ( len R19 ) + B150 ) ) = ( R20 . B150 )))
proof
let C136 being Nat;
assume that
L1033: 1 <= C136
and
L1034: C136 <= ( len R20 );
L1035: ( len ( R20 ^ <* R5 *> ) ) = ( ( len R20 ) + ( len <* R5 *> ) ) by FINSEQ_1:22
.= ( ( len R20 ) + 1 ) by FINSEQ_1:39;
L1036: C136 <= ( len ( R20 ^ <* R5 *> ) ) by L1035 , L1034 , NAT_1:12;
thus L1037: ( D52 . ( ( len R19 ) + C136 ) ) = ( ( R20 ^ <* R5 *> ) . C136 ) by L1036 , L1031 , L1033 , FINSEQ_1:65
.= ( R20 . C136 ) by L1033 , L1034 , FINSEQ_1:64;
end;
L1038: ( len D52 ) = ( ( len ( R19 ^ R20 ) ) + ( len <* R5 *> ) ) by FINSEQ_1:22
.= ( ( len ( R19 ^ R20 ) ) + 1 ) by FINSEQ_1:39;
L1039: ( len D52 ) = ( ( ( len R19 ) + ( len R20 ) ) + 1 ) by L1038 , FINSEQ_1:22;
L1040: ( len D52 ) = ( ( len R19 ) + ( ( len R20 ) + 1 ) ) by L1039;
L1041: D51 < ( len D52 ) by L1040 , NAT_1:16;
L1042: ( D52 /. D51 ) = ( D52 . D51 ) by L1041 , L1024 , L1
.= R4 by L1023 , L1024 , L1031 , FINSEQ_1:64;
set D53 = ( ( len R19 ) + ( len R20 ) );
L1043: 1 <= D53 by L1024 , NAT_1:12;
L1044: (( D52 . ( len D52 ) ) = R5 & 1 <= ( len D52 )) by L1038 , FINSEQ_1:42 , NAT_1:11;
L1045: ( D52 /. ( len D52 ) ) = R5 by L1044 , L1;
L1046: D53 < ( len D52 ) by L1039 , NAT_1:16;
L1047: ( D52 /. D53 ) = ( D52 . D53 ) by L1046 , L1024 , L1 , NAT_1:12
.= ( R4 => R5 ) by L1027 , L1028 , L1032;
L1048: ( D52 /. D51 ) , ( D52 /. D53 ) MP_rule ( D52 /. ( len D52 ) ) by L1047 , L1042 , L1045 , L763;
L1049: (( len ( R19 ^ R20 ) ) = ( ( len R19 ) + ( len R20 ) ) &  prc D52 , R13 , ( len D52 )) by L1048 , L1024 , L1041 , L1043 , L1046 , L833 , FINSEQ_1:22;
L1050: (for B151 being Nat holds ((1 <= B151 & B151 <= ( len ( R19 ^ R20 ) )) implies  prc ( R19 ^ R20 ) , R13 , B151)) by L1024 , L1025 , L1028 , L1029 , L880;
thus L1051: R13 |- R5 by L1050 , L1030 , L1049 , L929;
end;
theorem
L1052: (for R4 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds (R13 |- R4 implies R13 |- ( 'X' R4 ))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume L1053: R13 |- R4;
consider R19 being (FinSequence of ( LTLB_WFF )) such that L1054: ( R19 . ( len R19 ) ) = R4 and L1055: 1 <= ( len R19 ) and L1056: (for B152 being Nat holds ((1 <= B152 & B152 <= ( len R19 )) implies  prc R19 , R13 , B152)) by L1053 , L835;
set D54 = ( R19 ^ <* ( 'X' R4 ) *> );
L1057: ( len D54 ) = ( ( len R19 ) + ( len <* ( 'X' R4 ) *> ) ) by FINSEQ_1:22
.= ( ( len R19 ) + 1 ) by FINSEQ_1:39;
L1058: ( len R19 ) < ( len D54 ) by L1057 , NAT_1:16;
L1059: ( D54 /. ( len R19 ) ) = ( D54 . ( len R19 ) ) by L1058 , L1055 , L1
.= R4 by L1054 , L1055 , FINSEQ_1:64;
L1060: 1 <= ( len D54 ) by L1055 , L1057 , NAT_1:16;
L1061: ( D54 /. ( len D54 ) ) = ( D54 . ( len D54 ) ) by L1060 , L1
.= ( 'X' ( D54 /. ( len R19 ) ) ) by L1057 , L1059 , FINSEQ_1:42;
L1062: ( D54 /. ( len R19 ) ) NEX_rule ( D54 /. ( len D54 ) ) by L1061 , L762;
L1063:  prc D54 , R13 , ( len D54 ) by L1062 , L1055 , L1058 , L833;
thus L1064: R13 |- ( 'X' R4 ) by L1063 , L1055 , L1056 , L929;
end;
theorem
L1065: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds ((R13 |- ( R4 => R5 ) & R13 |- ( R4 => ( 'X' R4 ) )) implies R13 |- ( R4 => ( 'G' R5 ) )))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume that
L1066: R13 |- ( R4 => R5 )
and
L1067: R13 |- ( R4 => ( 'X' R4 ) );
consider R19 being (FinSequence of ( LTLB_WFF )) such that L1068: ( R19 . ( len R19 ) ) = ( R4 => R5 ) and L1069: 1 <= ( len R19 ) and L1070: (for B153 being Nat holds ((1 <= B153 & B153 <= ( len R19 )) implies  prc R19 , R13 , B153)) by L1066 , L835;
consider R22 being (FinSequence of ( LTLB_WFF )) such that L1071: ( R22 . ( len R22 ) ) = ( R4 => ( 'X' R4 ) ) and L1072: 1 <= ( len R22 ) and L1073: (for B154 being Nat holds ((1 <= B154 & B154 <= ( len R22 )) implies  prc R22 , R13 , B154)) by L1067 , L835;
L1074: (for B155 being Nat holds ((1 <= B155 & B155 <= ( len ( R19 ^ R22 ) )) implies  prc ( R19 ^ R22 ) , R13 , B155)) by L1069 , L1070 , L1072 , L1073 , L880;
set D55 = ( ( R19 ^ R22 ) ^ <* ( R4 => ( 'G' R5 ) ) *> );
L1075: D55 = ( R19 ^ ( R22 ^ <* ( R4 => ( 'G' R5 ) ) *> ) ) by FINSEQ_1:32;
L1076: ( len ( R19 ^ R22 ) ) = ( ( len R19 ) + ( len R22 ) ) by FINSEQ_1:22;
L1077: 1 <= ( len ( R19 ^ R22 ) ) by L1076 , L1069 , NAT_1:12;
L1078: ( len D55 ) = ( ( len ( R19 ^ R22 ) ) + ( len <* ( R4 => ( 'G' R5 ) ) *> ) ) by FINSEQ_1:22
.= ( ( len ( R19 ^ R22 ) ) + 1 ) by FINSEQ_1:39;
L1079: 1 <= ( len D55 ) by L1078 , L1069 , L1076 , NAT_1:16;
L1080: ( D55 /. ( len D55 ) ) = ( D55 . ( len D55 ) ) by L1079 , L1
.= ( R4 => ( 'G' R5 ) ) by L1078 , FINSEQ_1:42;
L1081: ( len D55 ) = ( ( len R19 ) + ( ( len R22 ) + 1 ) ) by L1076 , L1078;
L1082: ( len R19 ) < ( len D55 ) by L1081 , NAT_1:16;
L1083: ( D55 /. ( len R19 ) ) = ( D55 . ( len R19 ) ) by L1082 , L1069 , L1
.= ( R4 => R5 ) by L1068 , L1069 , L1075 , FINSEQ_1:64;
L1084: ( len ( R19 ^ R22 ) ) < ( len D55 ) by L1078 , NAT_1:16;
L1085: ( D55 /. ( len ( R19 ^ R22 ) ) ) = ( D55 . ( len ( R19 ^ R22 ) ) ) by L1084 , L1077 , L1
.= ( ( R19 ^ R22 ) . ( len ( R19 ^ R22 ) ) ) by L1077 , FINSEQ_1:64
.= ( ( R19 ^ R22 ) . ( ( len R19 ) + ( len R22 ) ) ) by FINSEQ_1:22
.= ( R4 => ( 'X' R4 ) ) by L1071 , L1072 , FINSEQ_1:65;
L1086: ( D55 /. ( len R19 ) ) , ( D55 /. ( len ( R19 ^ R22 ) ) ) IND_rule ( D55 /. ( len D55 ) ) by L1085 , L1083 , L1080 , L764;
L1087:  prc D55 , R13 , ( len D55 ) by L1086 , L1069 , L1077 , L1082 , L1084 , L833;
thus L1088: R13 |- ( R4 => ( 'G' R5 ) ) by L1087 , L1077 , L1074 , L929;
end;
theorem
L1089: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds (R13 |- ( R6 => ( R4 '&&' R5 ) ) implies (R13 |- ( R6 => R4 ) & R13 |- ( R6 => R5 )))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume L1090: R13 |- ( R6 => ( R4 '&&' R5 ) );
set D56 = ( ( R6 => ( R4 '&&' R5 ) ) => ( R6 => R4 ) );
L1091: D56 is  LTL_TAUT_OF_PL
proof
let C137 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
thus L1092: ( ( VAL C137 ) . D56 ) = ( ( ( VAL C137 ) . ( R6 => ( R4 '&&' R5 ) ) ) => ( ( VAL C137 ) . ( R6 => R4 ) ) ) by L626
.= ( ( ( ( VAL C137 ) . R6 ) => ( ( VAL C137 ) . ( R4 '&&' R5 ) ) ) => ( ( VAL C137 ) . ( R6 => R4 ) ) ) by L626
.= ( ( ( ( VAL C137 ) . R6 ) => ( ( ( VAL C137 ) . R4 ) '&' ( ( VAL C137 ) . R5 ) ) ) => ( ( VAL C137 ) . ( R6 => R4 ) ) ) by L686
.= ( ( ( ( VAL C137 ) . R6 ) => ( ( ( VAL C137 ) . R4 ) '&' ( ( VAL C137 ) . R5 ) ) ) => ( ( ( VAL C137 ) . R6 ) => ( ( VAL C137 ) . R4 ) ) ) by L626
.= 1 by L6;
end;
L1093: D56 in ( LTL_axioms ) by L1091 , L716;
L1094: R13 |- D56 by L1093 , L1004;
thus L1095: R13 |- ( R6 => R4 ) by L1094 , L1090 , L1021;
set D57 = ( ( R6 => ( R4 '&&' R5 ) ) => ( R6 => R5 ) );
L1096: D57 is  LTL_TAUT_OF_PL
proof
let C138 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
thus L1097: ( ( VAL C138 ) . D57 ) = ( ( ( VAL C138 ) . ( R6 => ( R4 '&&' R5 ) ) ) => ( ( VAL C138 ) . ( R6 => R5 ) ) ) by L626
.= ( ( ( ( VAL C138 ) . R6 ) => ( ( VAL C138 ) . ( R4 '&&' R5 ) ) ) => ( ( VAL C138 ) . ( R6 => R5 ) ) ) by L626
.= ( ( ( ( VAL C138 ) . R6 ) => ( ( ( VAL C138 ) . R4 ) '&' ( ( VAL C138 ) . R5 ) ) ) => ( ( VAL C138 ) . ( R6 => R5 ) ) ) by L686
.= ( ( ( ( VAL C138 ) . R6 ) => ( ( ( VAL C138 ) . R4 ) '&' ( ( VAL C138 ) . R5 ) ) ) => ( ( ( VAL C138 ) . R6 ) => ( ( VAL C138 ) . R5 ) ) ) by L626
.= 1 by L6;
end;
L1098: D57 in ( LTL_axioms ) by L1096 , L716;
L1099: R13 |- D57 by L1098 , L1004;
thus L1100: R13 |- ( R6 => R5 ) by L1099 , L1090 , L1021;
end;
theorem
L1101: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds ((R13 |- ( R4 => R5 ) & R13 |- ( R5 => R6 )) implies R13 |- ( R4 => R6 ))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume that
L1102: R13 |- ( R4 => R5 )
and
L1103: R13 |- ( R5 => R6 );
set D58 = ( ( R4 => R5 ) => ( ( R5 => R6 ) => ( R4 => R6 ) ) );
L1104:
now
let C139 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
thus L1105: ( ( VAL C139 ) . D58 ) = ( ( ( VAL C139 ) . ( R4 => R5 ) ) => ( ( VAL C139 ) . ( ( R5 => R6 ) => ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C139 ) . R4 ) => ( ( VAL C139 ) . R5 ) ) => ( ( VAL C139 ) . ( ( R5 => R6 ) => ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C139 ) . R4 ) => ( ( VAL C139 ) . R5 ) ) => ( ( ( VAL C139 ) . ( R5 => R6 ) ) => ( ( VAL C139 ) . ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C139 ) . R4 ) => ( ( VAL C139 ) . R5 ) ) => ( ( ( ( VAL C139 ) . R5 ) => ( ( VAL C139 ) . R6 ) ) => ( ( VAL C139 ) . ( R4 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C139 ) . R4 ) => ( ( VAL C139 ) . R5 ) ) => ( ( ( ( VAL C139 ) . R5 ) => ( ( VAL C139 ) . R6 ) ) => ( ( ( VAL C139 ) . R4 ) => ( ( VAL C139 ) . R6 ) ) ) ) by L626
.= 1 by XBOOLEAN:106;
end;
L1106: ( ( R4 => R5 ) => ( ( R5 => R6 ) => ( R4 => R6 ) ) ) is  LTL_TAUT_OF_PL by L1104 , L705;
L1107: ( ( R4 => R5 ) => ( ( R5 => R6 ) => ( R4 => R6 ) ) ) in ( LTL_axioms ) by L1106 , L716;
L1108: R13 |- ( ( R4 => R5 ) => ( ( R5 => R6 ) => ( R4 => R6 ) ) ) by L1107 , L1004;
L1109: R13 |- ( ( R5 => R6 ) => ( R4 => R6 ) ) by L1108 , L1102 , L1021;
thus L1110: R13 |- ( R4 => R6 ) by L1109 , L1103 , L1021;
end;
theorem
L1111: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds (R13 |- ( R4 => ( R5 => R6 ) ) implies R13 |- ( ( R4 '&&' R5 ) => R6 ))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
set D59 = ( ( R4 => ( R5 => R6 ) ) => ( ( R4 '&&' R5 ) => R6 ) );
L1112:
now
let C140 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
thus L1113: ( ( VAL C140 ) . D59 ) = ( ( ( VAL C140 ) . ( R4 => ( R5 => R6 ) ) ) => ( ( VAL C140 ) . ( ( R4 '&&' R5 ) => R6 ) ) ) by L626
.= ( ( ( ( VAL C140 ) . R4 ) => ( ( VAL C140 ) . ( R5 => R6 ) ) ) => ( ( VAL C140 ) . ( ( R4 '&&' R5 ) => R6 ) ) ) by L626
.= ( ( ( ( VAL C140 ) . R4 ) => ( ( ( VAL C140 ) . R5 ) => ( ( VAL C140 ) . R6 ) ) ) => ( ( VAL C140 ) . ( ( R4 '&&' R5 ) => R6 ) ) ) by L626
.= ( ( ( ( VAL C140 ) . R4 ) => ( ( ( VAL C140 ) . R5 ) => ( ( VAL C140 ) . R6 ) ) ) => ( ( ( VAL C140 ) . ( R4 '&&' R5 ) ) => ( ( VAL C140 ) . R6 ) ) ) by L626
.= ( ( ( ( VAL C140 ) . R4 ) => ( ( ( VAL C140 ) . R5 ) => ( ( VAL C140 ) . R6 ) ) ) => ( ( ( ( VAL C140 ) . R4 ) '&' ( ( VAL C140 ) . R5 ) ) => ( ( VAL C140 ) . R6 ) ) ) by L686
.= 1 by L10;
end;
L1114: D59 is  LTL_TAUT_OF_PL by L1112 , L705;
L1115: D59 in ( LTL_axioms ) by L1114 , L716;
L1116: R13 |- D59 by L1115 , L1004;
assume L1117: R13 |- ( R4 => ( R5 => R6 ) );
thus L1118: R13 |- ( ( R4 '&&' R5 ) => R6 ) by L1117 , L1116 , L1021;
end;
theorem
L1119: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds (R13 |- ( ( R4 '&&' R5 ) => R6 ) implies R13 |- ( R4 => ( R5 => R6 ) ))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
set D60 = ( ( ( R4 '&&' R5 ) => R6 ) => ( R4 => ( R5 => R6 ) ) );
L1120:
now
let C141 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
thus L1121: ( ( VAL C141 ) . D60 ) = ( ( ( VAL C141 ) . ( ( R4 '&&' R5 ) => R6 ) ) => ( ( VAL C141 ) . ( R4 => ( R5 => R6 ) ) ) ) by L626
.= ( ( ( ( VAL C141 ) . ( R4 '&&' R5 ) ) => ( ( VAL C141 ) . R6 ) ) => ( ( VAL C141 ) . ( R4 => ( R5 => R6 ) ) ) ) by L626
.= ( ( ( ( ( VAL C141 ) . R4 ) '&' ( ( VAL C141 ) . R5 ) ) => ( ( VAL C141 ) . R6 ) ) => ( ( VAL C141 ) . ( R4 => ( R5 => R6 ) ) ) ) by L686
.= ( ( ( ( ( VAL C141 ) . R4 ) '&' ( ( VAL C141 ) . R5 ) ) => ( ( VAL C141 ) . R6 ) ) => ( ( ( VAL C141 ) . R4 ) => ( ( VAL C141 ) . ( R5 => R6 ) ) ) ) by L626
.= ( ( ( ( ( VAL C141 ) . R4 ) '&' ( ( VAL C141 ) . R5 ) ) => ( ( VAL C141 ) . R6 ) ) => ( ( ( VAL C141 ) . R4 ) => ( ( ( VAL C141 ) . R5 ) => ( ( VAL C141 ) . R6 ) ) ) ) by L626
.= 1 by L15;
end;
L1122: D60 is  LTL_TAUT_OF_PL by L1120 , L705;
L1123: D60 in ( LTL_axioms ) by L1122 , L716;
L1124: R13 |- D60 by L1123 , L1004;
assume L1125: R13 |- ( ( R4 '&&' R5 ) => R6 );
thus L1126: R13 |- ( R4 => ( R5 => R6 ) ) by L1125 , L1124 , L1021;
end;
theorem
L1127: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds (for R7 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds ((R13 |- ( ( R4 '&&' R5 ) => R6 ) & R13 |- ( R4 => R7 )) implies R13 |- ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) )))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
let R7 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume that
L1128: R13 |- ( ( R4 '&&' R5 ) => R6 )
and
L1129: R13 |- ( R4 => R7 );
set D61 = ( ( ( R4 '&&' R5 ) => R6 ) => ( ( R4 => R7 ) => ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) );
L1130:
now
let C142 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
L1131: (( ( VAL C142 ) . R4 ) = ( 0 ) or ( ( VAL C142 ) . R4 ) = 1) by XBOOLEAN:def 3;
L1132: (( ( VAL C142 ) . R5 ) = ( 0 ) or ( ( VAL C142 ) . R5 ) = 1) by XBOOLEAN:def 3;
L1133: (( ( VAL C142 ) . R7 ) = ( 0 ) or ( ( VAL C142 ) . R7 ) = 1) by XBOOLEAN:def 3;
L1134: (( ( VAL C142 ) . R6 ) = ( 0 ) or ( ( VAL C142 ) . R6 ) = 1) by XBOOLEAN:def 3;
thus L1135: ( ( VAL C142 ) . D61 ) = ( ( ( VAL C142 ) . ( ( R4 '&&' R5 ) => R6 ) ) => ( ( VAL C142 ) . ( ( R4 => R7 ) => ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) ) ) by L626
.= ( ( ( ( VAL C142 ) . ( R4 '&&' R5 ) ) => ( ( VAL C142 ) . R6 ) ) => ( ( VAL C142 ) . ( ( R4 => R7 ) => ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) ) ) by L626
.= ( ( ( ( ( VAL C142 ) . R4 ) '&' ( ( VAL C142 ) . R5 ) ) => ( ( VAL C142 ) . R6 ) ) => ( ( VAL C142 ) . ( ( R4 => R7 ) => ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) ) ) by L686
.= ( ( ( ( ( VAL C142 ) . R4 ) '&' ( ( VAL C142 ) . R5 ) ) => ( ( VAL C142 ) . R6 ) ) => ( ( ( VAL C142 ) . ( R4 => R7 ) ) => ( ( VAL C142 ) . ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) ) ) by L626
.= ( ( ( ( ( VAL C142 ) . R4 ) '&' ( ( VAL C142 ) . R5 ) ) => ( ( VAL C142 ) . R6 ) ) => ( ( ( ( VAL C142 ) . R4 ) => ( ( VAL C142 ) . R7 ) ) => ( ( VAL C142 ) . ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) ) ) by L626
.= ( ( ( ( ( VAL C142 ) . R4 ) '&' ( ( VAL C142 ) . R5 ) ) => ( ( VAL C142 ) . R6 ) ) => ( ( ( ( VAL C142 ) . R4 ) => ( ( VAL C142 ) . R7 ) ) => ( ( ( VAL C142 ) . ( R4 '&&' R5 ) ) => ( ( VAL C142 ) . ( R7 '&&' R6 ) ) ) ) ) by L626
.= ( ( ( ( ( VAL C142 ) . R4 ) '&' ( ( VAL C142 ) . R5 ) ) => ( ( VAL C142 ) . R6 ) ) => ( ( ( ( VAL C142 ) . R4 ) => ( ( VAL C142 ) . R7 ) ) => ( ( ( ( VAL C142 ) . R4 ) '&' ( ( VAL C142 ) . R5 ) ) => ( ( VAL C142 ) . ( R7 '&&' R6 ) ) ) ) ) by L686
.= 1 by L1131 , L1132 , L1134 , L1133 , L686;
end;
L1136: D61 is  LTL_TAUT_OF_PL by L1130 , L705;
L1137: D61 in ( LTL_axioms ) by L1136 , L716;
L1138: R13 |- D61 by L1137 , L1004;
L1139: R13 |- ( ( R4 => R7 ) => ( ( R4 '&&' R5 ) => ( R7 '&&' R6 ) ) ) by L1138 , L1128 , L1021;
thus L1140: thesis by L1139 , L1129 , L1021;
end;
theorem
L1141: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R6 being (Element of ( LTLB_WFF )) holds (for R7 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds ((R13 |- ( R4 => ( R5 => R6 ) ) & R13 |- ( R6 => R7 )) implies R13 |- ( R4 => ( R5 => R7 ) )))))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R6 being (Element of ( LTLB_WFF ));
let R7 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
assume that
L1142: R13 |- ( R4 => ( R5 => R6 ) )
and
L1143: R13 |- ( R6 => R7 );
set D62 = ( ( R4 => ( R5 => R6 ) ) => ( ( R6 => R7 ) => ( R4 => ( R5 => R7 ) ) ) );
L1144:
now
let C143 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
L1145: (( ( VAL C143 ) . R4 ) = ( 0 ) or ( ( VAL C143 ) . R4 ) = 1) by XBOOLEAN:def 3;
L1146: (( ( VAL C143 ) . R6 ) = ( 0 ) or ( ( VAL C143 ) . R6 ) = 1) by XBOOLEAN:def 3;
set D63 = ( ( VAL C143 ) . ( R4 => ( R5 => R6 ) ) );
set D64 = ( ( VAL C143 ) . ( R6 => R7 ) );
set D65 = ( ( VAL C143 ) . ( R4 => ( R5 => R7 ) ) );
L1147: (( ( VAL C143 ) . R5 ) = ( 0 ) or ( ( VAL C143 ) . R5 ) = 1) by XBOOLEAN:def 3;
L1148: (( ( VAL C143 ) . R7 ) = ( 0 ) or ( ( VAL C143 ) . R7 ) = 1) by XBOOLEAN:def 3;
L1149: ( ( VAL C143 ) . ( R4 => ( R5 => R7 ) ) ) = ( ( ( VAL C143 ) . R4 ) => ( ( VAL C143 ) . ( R5 => R7 ) ) ) by L626
.= ( ( ( VAL C143 ) . R4 ) => ( ( ( VAL C143 ) . R5 ) => ( ( VAL C143 ) . R7 ) ) ) by L626;
L1150: ( ( VAL C143 ) . ( R4 => ( R5 => R6 ) ) ) = ( ( ( VAL C143 ) . R4 ) => ( ( VAL C143 ) . ( R5 => R6 ) ) ) by L626
.= ( ( ( VAL C143 ) . R4 ) => ( ( ( VAL C143 ) . R5 ) => ( ( VAL C143 ) . R6 ) ) ) by L626;
thus L1151: ( ( VAL C143 ) . D62 ) = ( D63 => ( ( VAL C143 ) . ( ( R6 => R7 ) => ( R4 => ( R5 => R7 ) ) ) ) ) by L626
.= ( D63 => ( D64 => D65 ) ) by L626
.= 1 by L1145 , L1147 , L1146 , L1148 , L1150 , L1149 , L626;
end;
L1152: D62 is  LTL_TAUT_OF_PL by L1144 , L705;
L1153: D62 in ( LTL_axioms ) by L1152 , L716;
L1154: R13 |- D62 by L1153 , L1004;
L1155: R13 |- ( ( R6 => R7 ) => ( R4 => ( R5 => R7 ) ) ) by L1154 , L1142 , L1021;
thus L1156: R13 |- ( R4 => ( R5 => R7 ) ) by L1155 , L1143 , L1021;
end;
theorem
L1157: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds (R13 |- ( R4 => R5 ) implies R13 |- ( ( 'not' R5 ) => ( 'not' R4 ) )))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
set D66 = ( ( R4 => R5 ) => ( ( 'not' R5 ) => ( 'not' R4 ) ) );
L1158:
now
let C144 being (Function of ( LTLB_WFF ) , ( BOOLEAN ));
L1159: (( ( VAL C144 ) . R4 ) = ( 0 ) or ( ( VAL C144 ) . R4 ) = 1) by XBOOLEAN:def 3;
L1160: (( ( VAL C144 ) . R5 ) = ( 0 ) or ( ( VAL C144 ) . R5 ) = 1) by XBOOLEAN:def 3;
thus L1161: ( ( VAL C144 ) . D66 ) = ( ( ( VAL C144 ) . ( R4 => R5 ) ) => ( ( VAL C144 ) . ( ( 'not' R5 ) => ( 'not' R4 ) ) ) ) by L626
.= ( ( ( ( VAL C144 ) . R4 ) => ( ( VAL C144 ) . R5 ) ) => ( ( VAL C144 ) . ( ( 'not' R5 ) => ( 'not' R4 ) ) ) ) by L626
.= ( ( ( ( VAL C144 ) . R4 ) => ( ( VAL C144 ) . R5 ) ) => ( ( ( VAL C144 ) . ( R5 => ( TFALSUM ) ) ) => ( ( VAL C144 ) . ( R4 => ( TFALSUM ) ) ) ) ) by L626
.= ( ( ( ( VAL C144 ) . R4 ) => ( ( VAL C144 ) . R5 ) ) => ( ( ( ( VAL C144 ) . R5 ) => ( ( VAL C144 ) . ( TFALSUM ) ) ) => ( ( VAL C144 ) . ( R4 => ( TFALSUM ) ) ) ) ) by L626
.= ( ( ( ( VAL C144 ) . R4 ) => ( ( VAL C144 ) . R5 ) ) => ( ( ( ( VAL C144 ) . R5 ) => ( FALSE ) ) => ( ( VAL C144 ) . ( R4 => ( TFALSUM ) ) ) ) ) by L626
.= ( ( ( ( VAL C144 ) . R4 ) => ( ( VAL C144 ) . R5 ) ) => ( ( ( ( VAL C144 ) . R5 ) => ( FALSE ) ) => ( ( ( VAL C144 ) . R4 ) => ( ( VAL C144 ) . ( TFALSUM ) ) ) ) ) by L626
.= 1 by L1159 , L1160;
end;
L1162: D66 is  LTL_TAUT_OF_PL by L1158 , L705;
L1163: D66 in ( LTL_axioms ) by L1162 , L716;
L1164: R13 |- D66 by L1163 , L1004;
assume L1165: R13 |- ( R4 => R5 );
thus L1166: thesis by L1165 , L1164 , L1021;
end;
theorem
L1167: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R13 being (Subset of ( LTLB_WFF )) holds R13 |- ( ( ( 'X' R4 ) '&&' ( 'X' R5 ) ) => ( 'X' ( R4 '&&' R5 ) ) ))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R13 being (Subset of ( LTLB_WFF ));
set D67 = ( 'X' R4 );
set D68 = ( 'not' R5 );
set D69 = ( 'not' ( 'X' R5 ) );
set D70 = ( 'X' ( 'not' R5 ) );
L1168: ( D70 => D69 ) in ( LTL_axioms ) by L716;
L1169: R13 |- ( D70 => D69 ) by L1168 , L1004;
L1170: ( ( 'not' ( 'X' ( R4 => D68 ) ) ) => ( 'X' ( 'not' ( R4 => D68 ) ) ) ) in ( LTL_axioms ) by L716;
L1171: R13 |- ( ( 'not' ( 'X' ( R4 => D68 ) ) ) => ( 'X' ( 'not' ( R4 => D68 ) ) ) ) by L1170 , L1004;
L1172: ( ( 'X' ( R4 => D68 ) ) => ( D67 => D70 ) ) in ( LTL_axioms ) by L716;
L1173: R13 |- ( ( 'X' ( R4 => D68 ) ) => ( D67 => D70 ) ) by L1172 , L1004;
L1174: R13 |- ( ( 'X' ( R4 => D68 ) ) => ( D67 => D69 ) ) by L1173 , L1169 , L1141;
L1175: R13 |- ( ( 'not' ( D67 => D69 ) ) => ( 'not' ( 'X' ( R4 => D68 ) ) ) ) by L1174 , L1157;
thus L1176: thesis by L1175 , L1171 , L1101;
end;
theorem
L1177: (for R4 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |- R4 implies R11 |- ( 'G' R4 ))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L1178: R11 |- R4;
L1179: ( R4 => ( R4 => R4 ) ) in ( LTL_axioms ) by L750;
L1180: R11 |- ( R4 => ( R4 => R4 ) ) by L1179 , L1004;
L1181: R11 |- ( R4 => R4 ) by L1180 , L1178 , L1021;
L1182: ( ( 'X' R4 ) => ( R4 => ( 'X' R4 ) ) ) in ( LTL_axioms ) by L750;
L1183: R11 |- ( ( 'X' R4 ) => ( R4 => ( 'X' R4 ) ) ) by L1182 , L1004;
L1184: R11 |- ( 'X' R4 ) by L1178 , L1052;
L1185: R11 |- ( R4 => ( 'X' R4 ) ) by L1184 , L1183 , L1021;
L1186: R11 |- ( R4 => ( 'G' R4 ) ) by L1185 , L1181 , L1065;
thus L1187: R11 |- ( 'G' R4 ) by L1186 , L1178 , L1021;
end;
theorem
L1188: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (( R4 => R5 ) in R11 implies ( R11 \/ { R4 } ) |- ( 'G' R5 )))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
L1189: R4 in { R4 } by TARSKI:def 1;
L1190: R4 in ( R11 \/ { R4 } ) by L1189 , XBOOLE_0:def 3;
L1191: ( R11 \/ { R4 } ) |- R4 by L1190 , L1004;
assume L1192: ( R4 => R5 ) in R11;
L1193: ( R4 => R5 ) in ( R11 \/ { R4 } ) by L1192 , XBOOLE_0:def 3;
L1194: ( R11 \/ { R4 } ) |- ( R4 => R5 ) by L1193 , L1004;
L1195: ( R11 \/ { R4 } ) |- R5 by L1194 , L1191 , L1021;
thus L1196: ( R11 \/ { R4 } ) |- ( 'G' R5 ) by L1195 , L1177;
end;
theorem
L1197: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |- R5 implies ( R11 \/ { R4 } ) |- R5))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
assume L1198: R11 |- R5;
consider R19 being (FinSequence of ( LTLB_WFF )) such that L1199: (( R19 . ( len R19 ) ) = R5 & 1 <= ( len R19 )) and L1200: (for B156 being Nat holds ((1 <= B156 & B156 <= ( len R19 )) implies  prc R19 , R11 , B156)) by L1198 , L835;
L1201:
now
let C145 being Nat;
assume L1202: (1 <= C145 & C145 <= ( len R19 ));
L1203:  prc R19 , R11 , C145 by L1202 , L1200;
L1204: (( R19 . C145 ) in ( LTL_axioms ) or ( R19 . C145 ) in R11 or (ex B157 , B158 being Nat st ((1 <= B157 & B157 < C145 & 1 <= B158 & B158 < C145 & (( R19 /. B157 ) , ( R19 /. B158 ) MP_rule ( R19 /. C145 ) or ( R19 /. B157 ) , ( R19 /. B158 ) IND_rule ( R19 /. C145 ))) or (ex B159 being Nat st (1 <= B159 & B159 < C145 & ( R19 /. B159 ) NEX_rule ( R19 /. C145 )))))) by L1203 , L833;
L1205: (( R19 . C145 ) in ( LTL_axioms ) or ( R19 . C145 ) in ( R11 \/ { R4 } ) or (ex B160 , B161 being Nat st ((1 <= B160 & B160 < C145 & 1 <= B161 & B161 < C145 & (( R19 /. B160 ) , ( R19 /. B161 ) MP_rule ( R19 /. C145 ) or ( R19 /. B160 ) , ( R19 /. B161 ) IND_rule ( R19 /. C145 ))) or (ex B162 being Nat st (1 <= B162 & B162 < C145 & ( R19 /. B162 ) NEX_rule ( R19 /. C145 )))))) by L1204 , XBOOLE_0:def 3;
thus L1206:  prc R19 , ( R11 \/ { R4 } ) , C145 by L1205 , L833;
end;
thus L1207: ( R11 \/ { R4 } ) |- R5 by L1201 , L1199 , L835;
end;
theorem
L1208: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (( R11 \/ { R4 } ) |- R5 implies R11 |- ( ( 'G' R4 ) => R5 )))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
set D71 = ( R11 \/ { R4 } );
assume L1209: D71 |- R5;
consider R19 being (FinSequence of ( LTLB_WFF )) such that L1210: ( R19 . ( len R19 ) ) = R5 and L1211: 1 <= ( len R19 ) and L1212: (for B163 being Nat holds ((1 <= B163 & B163 <= ( len R19 )) implies  prc R19 , D71 , B163)) by L1209 , L835;
defpred S20[ Nat ] means ((1 <= $1 & $1 <= ( len R19 )) implies R11 |- ( ( 'G' R4 ) => ( R19 /. $1 ) ));
L1213: (for B164 being Nat holds ((for B165 being Nat holds (B165 < B164 implies S20[ B165 ])) implies S20[ B164 ]))
proof
let C146 being Nat;
assume L1214: (for B166 being Nat holds (B166 < C146 implies S20[ B166 ]));
per cases  by NAT_1:14;
suppose L1215: C146 = ( 0 );

thus L1216: S20[ C146 ] by L1215;
end;
suppose L1217: (not C146 < 1);

assume that
L1218: 1 <= C146
and
L1219: C146 <= ( len R19 );
L1220:  prc R19 , D71 , C146 by L1212 , L1218 , L1219;
per cases  by L1220 , L833;
suppose L1221: ( R19 . C146 ) in ( LTL_axioms );

set D72 = ( R19 /. C146 );
L1222: ( D72 => ( ( 'G' R4 ) => D72 ) ) in ( LTL_axioms ) by L750;
L1223: R11 |- ( D72 => ( ( 'G' R4 ) => D72 ) ) by L1222 , L1004;
L1224: ( R19 /. C146 ) in ( LTL_axioms ) by L1218 , L1219 , L1221 , L1;
L1225: R11 |- D72 by L1224 , L1004;
thus L1226: thesis by L1225 , L1223 , L1021;
end;
suppose L1227: ( R19 . C146 ) in D71;

per cases  by L1227 , XBOOLE_0:def 3;
suppose L1228: ( R19 . C146 ) in R11;

set D73 = ( R19 /. C146 );
L1229: ( D73 => ( ( 'G' R4 ) => D73 ) ) in ( LTL_axioms ) by L750;
L1230: R11 |- ( D73 => ( ( 'G' R4 ) => D73 ) ) by L1229 , L1004;
L1231: ( R19 /. C146 ) in R11 by L1218 , L1219 , L1228 , L1;
L1232: R11 |- D73 by L1231 , L1004;
thus L1233: thesis by L1232 , L1230 , L1021;
end;
suppose L1234: ( R19 . C146 ) in { R4 };

L1235: ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) in ( LTL_axioms ) by L716;
L1236: R11 |- ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) by L1235 , L1004;
L1237: ( R19 . C146 ) = R4 by L1234 , TARSKI:def 1;
L1238: ( R19 /. C146 ) = R4 by L1237 , L1218 , L1219 , L1;
thus L1239: thesis by L1238 , L1236 , L1089;
end;
end;
suppose L1241: (ex B167 , B168 being Nat st (1 <= B167 & B167 < C146 & 1 <= B168 & B168 < C146 & (( R19 /. B167 ) , ( R19 /. B168 ) MP_rule ( R19 /. C146 ) or ( R19 /. B167 ) , ( R19 /. B168 ) IND_rule ( R19 /. C146 ))));

consider C147 , C148 being Nat such that L1242: 1 <= C147 and L1243: C147 < C146 and L1244: 1 <= C148 and L1245: C148 < C146 and L1246: (( R19 /. C147 ) , ( R19 /. C148 ) MP_rule ( R19 /. C146 ) or ( R19 /. C147 ) , ( R19 /. C148 ) IND_rule ( R19 /. C146 )) by L1241;
L1247: C147 <= ( len R19 ) by L1219 , L1243 , XXREAL_0:2;
L1248: R11 |- ( ( 'G' R4 ) => ( R19 /. C147 ) ) by L1247 , L1214 , L1242 , L1243;
L1249: C148 <= ( len R19 ) by L1219 , L1245 , XXREAL_0:2;
L1250: R11 |- ( ( 'G' R4 ) => ( R19 /. C148 ) ) by L1249 , L1214 , L1244 , L1245;
per cases  by L1246;
suppose L1251: ( R19 /. C147 ) , ( R19 /. C148 ) MP_rule ( R19 /. C146 );

set D74 = ( ( ( 'G' R4 ) => ( ( R19 /. C147 ) => ( R19 /. C146 ) ) ) => ( ( ( 'G' R4 ) => ( R19 /. C147 ) ) => ( ( 'G' R4 ) => ( R19 /. C146 ) ) ) );
L1252: D74 in ( LTL_axioms ) by L755;
L1253: R11 |- D74 by L1252 , L1004;
L1254: R11 |- ( ( 'G' R4 ) => ( ( R19 /. C147 ) => ( R19 /. C146 ) ) ) by L1250 , L1251 , L763;
L1255: R11 |- ( ( ( 'G' R4 ) => ( R19 /. C147 ) ) => ( ( 'G' R4 ) => ( R19 /. C146 ) ) ) by L1254 , L1253 , L1021;
thus L1256: R11 |- ( ( 'G' R4 ) => ( R19 /. C146 ) ) by L1255 , L1248 , L1021;
end;
suppose L1257: ( R19 /. C147 ) , ( R19 /. C148 ) IND_rule ( R19 /. C146 );

consider R8 being (Element of ( LTLB_WFF )), R9 being (Element of ( LTLB_WFF )) such that L1258: ( R19 /. C147 ) = ( R8 => R9 ) and L1259: ( R19 /. C148 ) = ( R8 => ( 'X' R8 ) ) and L1260: ( R19 /. C146 ) = ( R8 => ( 'G' R9 ) ) by L1257 , L764;
set D75 = ( 'G' R4 );
set D76 = ( 'X' ( 'G' R4 ) );
set D77 = ( 'X' R8 );
set D78 = ( 'X' R5 );
set D79 = ( 'G' R9 );
L1261: ( D75 => ( R4 '&&' D76 ) ) in ( LTL_axioms ) by L716;
L1262: R11 |- ( D75 => ( R4 '&&' D76 ) ) by L1261 , L1004;
L1263: R11 |- ( D75 => D76 ) by L1262 , L1089;
L1264: R11 |- ( ( D75 '&&' R8 ) => D77 ) by L1250 , L1259 , L1111;
L1265: R11 |- ( ( D75 '&&' R8 ) => ( D76 '&&' D77 ) ) by L1264 , L1263 , L1127;
L1266: R11 |- ( ( D76 '&&' D77 ) => ( 'X' ( D75 '&&' R8 ) ) ) by L1167;
L1267: R11 |- ( ( D75 '&&' R8 ) => ( 'X' ( D75 '&&' R8 ) ) ) by L1266 , L1265 , L1101;
L1268: R11 |- ( ( D75 '&&' R8 ) => R9 ) by L1248 , L1258 , L1111;
L1269: R11 |- ( ( D75 '&&' R8 ) => D79 ) by L1268 , L1267 , L1065;
thus L1270: thesis by L1269 , L1260 , L1119;
end;
end;
suppose L1272: (ex B169 being Nat st (1 <= B169 & B169 < C146 & ( R19 /. B169 ) NEX_rule ( R19 /. C146 )));

L1273: ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) in ( LTL_axioms ) by L716;
L1274: R11 |- ( ( 'G' R4 ) => ( R4 '&&' ( 'X' ( 'G' R4 ) ) ) ) by L1273 , L1004;
L1275: R11 |- ( ( 'G' R4 ) => ( 'X' ( 'G' R4 ) ) ) by L1274 , L1089;
consider C149 being Nat, R5 being (Element of ( LTLB_WFF )), R6 being (Element of ( LTLB_WFF )) such that L1276: 1 <= C149 and L1277: C149 < C146 and L1278: ( R19 /. C149 ) NEX_rule ( R19 /. C146 ) by L1272;
L1279: ( ( 'X' ( ( 'G' R4 ) => ( R19 /. C149 ) ) ) => ( ( 'X' ( 'G' R4 ) ) => ( 'X' ( R19 /. C149 ) ) ) ) in ( LTL_axioms ) by L716;
L1280: R11 |- ( ( 'X' ( ( 'G' R4 ) => ( R19 /. C149 ) ) ) => ( ( 'X' ( 'G' R4 ) ) => ( 'X' ( R19 /. C149 ) ) ) ) by L1279 , L1004;
L1281: C149 <= ( len R19 ) by L1219 , L1277 , XXREAL_0:2;
L1282: R11 |- ( 'X' ( ( 'G' R4 ) => ( R19 /. C149 ) ) ) by L1281 , L1214 , L1276 , L1277 , L1052;
L1283: R11 |- ( ( 'X' ( 'G' R4 ) ) => ( 'X' ( R19 /. C149 ) ) ) by L1282 , L1280 , L1021;
L1284: ( R19 /. C146 ) = ( 'X' ( R19 /. C149 ) ) by L1278 , L762;
thus L1285: thesis by L1284 , L1283 , L1275 , L1101;
end;
end;
end;
L1288: (for B170 being Nat holds S20[ B170 ]) from NAT_1:sch 4(L1213);
L1289: R5 = ( R19 /. ( len R19 ) ) by L1210 , L1211 , L1;
thus L1290: R11 |- ( ( 'G' R4 ) => R5 ) by L1289 , L1211 , L1288;
end;
theorem
L1291: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |- ( R4 => R5 ) implies ( R11 \/ { R4 } ) |- R5))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
L1292: R4 in { R4 } by TARSKI:def 1;
L1293: R4 in ( R11 \/ { R4 } ) by L1292 , XBOOLE_0:def 3;
L1294: ( R11 \/ { R4 } ) |- R4 by L1293 , L1004;
assume L1295: R11 |- ( R4 => R5 );
L1296: ( R11 \/ { R4 } ) |- ( R4 => R5 ) by L1295 , L1197;
thus L1297: ( R11 \/ { R4 } ) |- R5 by L1296 , L1294 , L1021;
end;
theorem
L1298: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds (R11 |- ( ( 'G' R4 ) => R5 ) implies ( R11 \/ { R4 } ) |- R5))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
L1299: R4 in { R4 } by TARSKI:def 1;
L1300: R4 in ( R11 \/ { R4 } ) by L1299 , XBOOLE_0:def 3;
L1301: ( R11 \/ { R4 } ) |- R4 by L1300 , L1004;
L1302: ( R11 \/ { R4 } ) |- ( 'G' R4 ) by L1301 , L1177;
assume L1303: R11 |- ( ( 'G' R4 ) => R5 );
L1304: ( R11 \/ { R4 } ) |- ( ( 'G' R4 ) => R5 ) by L1303 , L1197;
thus L1305: ( R11 \/ { R4 } ) |- R5 by L1304 , L1302 , L1021;
end;
theorem
L1306: (for R4 being (Element of ( LTLB_WFF )) holds (for R5 being (Element of ( LTLB_WFF )) holds (for R11 being (Subset of ( LTLB_WFF )) holds R11 |- ( ( 'G' ( R4 => R5 ) ) => ( ( 'G' R4 ) => ( 'G' R5 ) ) ))))
proof
let R4 being (Element of ( LTLB_WFF ));
let R5 being (Element of ( LTLB_WFF ));
let R11 being (Subset of ( LTLB_WFF ));
reconsider D80 = ( ( R11 \/ { ( R4 => R5 ) } ) \/ { R4 } ) as (Subset of ( LTLB_WFF ));
L1307: ( R4 => R5 ) in { ( R4 => R5 ) } by TARSKI:def 1;
L1308: ( R4 => R5 ) in ( R11 \/ { ( R4 => R5 ) } ) by L1307 , XBOOLE_0:def 3;
L1309: D80 |- ( 'G' R5 ) by L1308 , L1188;
L1310: ( R11 \/ { ( R4 => R5 ) } ) |- ( ( 'G' R4 ) => ( 'G' R5 ) ) by L1309 , L1208;
thus L1311: thesis by L1310 , L1208;
end;
