:: Linear Transformations of Euclidean Topological Spaces. Part {II}
::  by Karol P\kak
::
:: Received October 26, 2010
:: Copyright (c) 2010-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies ALGSTR_0, ARYTM_1, ARYTM_3, CARD_1, CARD_3, CLASSES1, ENTROPY1,
      EUCLID, FINSEQ_1, FINSEQ_2, FINSEQ_4, FINSET_1, FUNCT_1, FUNCT_2,
      FVSUM_1, INCSP_1, LMOD_7, MATRIX_1, MATRIX_3, MATRIX13, MATRLIN,
      MATRLIN2, MESFUNC1, NAT_1, NUMBERS, ORDINAL4, PARTFUN1, PBOOLE, PRE_TOPC,
      PRVECT_1, QC_LANG1, RANKNULL, RELAT_1, RLAFFIN1, RLSUB_1, RLVECT_1,
      RLVECT_2, RLVECT_3, RLVECT_5, RVSUM_1, SEMI_AF1, STRUCT_0, SUBSET_1,
      SUPINF_2, TARSKI, TREES_1, VALUED_0, VALUED_1, VECTSP_1, VECTSP10,
      XBOOLE_0, XXREAL_0;
 notations TARSKI, XBOOLE_0, SUBSET_1, RELAT_1, CARD_1, NUMBERS, XXREAL_0,
      ORDINAL1, FINSET_1, FUNCT_1, RELSET_1, PARTFUN1, VALUED_0, FUNCT_2,
      FINSEQ_1, FINSEQ_2, FINSEQ_3, STRUCT_0, RLVECT_1, RLVECT_2, RLVECT_3,
      VECTSP_1, MATRIX_1, MATRIX_3, VECTSP_4, VECTSP_6, VECTSP_7, MATRIX13,
      RVSUM_1, ALGSTR_0, FVSUM_1, RANKNULL, BINOP_2, PRE_TOPC, MATRIX_6,
      MATRLIN, MATRLIN2, NAT_D, EUCLID, GROUP_1, MATRIX11, FINSEQOP, ENTROPY1,
      RLSUB_1, RUSUB_4, PRVECT_1, RLAFFIN1, MATRTOP1;
 constructors BINARITH, ENTROPY1, FVSUM_1, LAPLACE, MATRIX_6, MATRIX11,
      MATRIX13, MATRLIN2, MATRTOP1, MONOID_0, RANKNULL, REALSET1, RELSET_1,
      RLAFFIN1, RLVECT_3, RUSUB_5, SEQ_1, VECTSP10, MATRIX15;
 registrations CARD_1, EUCLID, FINSEQ_1, FINSEQ_2, FINSET_1, FUNCT_1, FUNCT_2,
      MATRIX13, MATRLIN2, MATRTOP1, MEMBERED, MONOID_0, NAT_1, NUMBERS,
      PRVECT_1, RELAT_1, RELSET_1, RLAFFIN1, RLVECT_3, RVSUM_1, STRUCT_0,
      RLVECT_2, VALUED_0, VECTSP_1, VECTSP_9, XREAL_0, XXREAL_0, ZFMISC_1;
 requirements ARITHM, NUMERALS, REAL, BOOLE, SUBSET;
 definitions EUCLID, FINSEQ_1, MATRIX13, MATRTOP1, STRUCT_0, TARSKI, VECTSP_1,
      XBOOLE_0;
 theorems CARD_1, CARD_2, ENTROPY1, EUCLID, FINSEQ_1, FINSEQ_2, FINSEQ_3,
      FINSEQ_4, FINSEQ_6, FUNCT_1, FUNCT_2, FVSUM_1, LAPLACE, MATRIX_1,
      MATRIX_2, MATRIX_6, MATRIX13, MATRIXR1, MATRLIN, MATRLIN2, MATRPROB,
      MATRTOP1, NAT_1, ORDINAL1, PARTFUN1, PRE_POLY, RANKNULL, RELAT_1,
      RLAFFIN1, RLSUB_1, RLVECT_1, RLVECT_2, RLVECT_3, RLVECT_5, RVSUM_1,
      STRUCT_0, SUBSET_1, TARSKI, VECTSP_1, VECTSP_4, VECTSP_6, VECTSP_7,
      VECTSP_9, XBOOLE_0, XBOOLE_1, XREAL_0, XREAL_1, ZFMISC_1, TOPREAL3;
 schemes FINSEQ_1, FUNCT_2, NAT_1;

begin
L1: (for R2 being Nat holds (the carrier of ( R2 -VectSp_over ( F_Real ) )) = (the carrier of ( TOP-REAL R2 )))
proof
let R2 being Nat;
thus L2: (the carrier of ( R2 -VectSp_over ( F_Real ) )) = ( REAL R2 ) by MATRIX13:102
.= (the carrier of ( TOP-REAL R2 )) by EUCLID:22;
end;
L3: (for R2 being Nat holds ( 0. ( R2 -VectSp_over ( F_Real ) ) ) = ( 0. ( TOP-REAL R2 ) ))
proof
let R2 being Nat;
thus L4: ( 0. ( R2 -VectSp_over ( F_Real ) ) ) = ( R2 |-> ( 0. ( F_Real ) ) ) by MATRIX13:102
.= ( 0* R2 )
.= ( 0. ( TOP-REAL R2 ) ) by EUCLID:70;
end;
L5: (for R2 being Nat holds (for R6 being R2 -element  real-valued FinSequence holds R6 is (Point of ( TOP-REAL R2 ))))
proof
let R2 being Nat;
let R6 being R2 -element  real-valued FinSequence;
L6: (( len R6 ) = R2 & ( @ ( @ R6 ) ) = R6) by CARD_1:def 7;
thus L7: thesis by L6 , TOPREAL3:46;
end;
theorem
L8: (for R1 being set holds (for R2 being Nat holds (R1 is (Linear_Combination of ( R2 -VectSp_over ( F_Real ) )) iff R1 is (Linear_Combination of ( TOP-REAL R2 )))))
proof
let R1 being set;
let R2 being Nat;
set D1 = ( R2 -VectSp_over ( F_Real ) );
set D2 = ( TOP-REAL R2 );
thus L9:now
assume L10: R1 is (Linear_Combination of D1);
reconsider D3 = R1 as (Linear_Combination of D1) by L10;
consider C1 being  finite (Subset of D1) such that L11: (for B1 being (Element of D1) holds ((not B1 in C1) implies ( D3 . B1 ) = ( 0. ( F_Real ) ))) by VECTSP_6:def 1;
L12:
now
let C2 being (Element of D2);
assume L13: (not C2 in C1);
L14: C2 is (Element of D1) by L1;
thus L15: ( 0 ) = ( D3 . C2 ) by L14 , L11 , L13;
end;
L16: (D3 is (Element of ( Funcs ((the carrier of D2) , ( REAL )) )) & C1 is  finite  finite  finite  finite (Subset of D2)) by L1;
thus L17: R1 is (Linear_Combination of D2) by L16 , L12 , RLVECT_2:def 3;
end;
assume L18: R1 is (Linear_Combination of D2);
reconsider D4 = R1 as (Linear_Combination of D2) by L18;
consider C3 being  finite (Subset of D2) such that L19: (for B2 being (Element of D2) holds ((not B2 in C3) implies ( D4 . B2 ) = ( 0 ))) by RLVECT_2:def 3;
L20:
now
let C4 being (Element of D1);
assume L21: (not C4 in C3);
L22: C4 is (Element of D2) by L1;
thus L23: ( 0. ( F_Real ) ) = ( D4 . C4 ) by L22 , L19 , L21;
end;
L24: (D4 is (Element of ( Funcs ((the carrier of D1) , (the carrier of ( F_Real ))) )) & C3 is  finite  finite  finite  finite (Subset of D1)) by L1;
thus L25: thesis by L24 , L20 , VECTSP_6:def 1;
end;
theorem
L26: (for R2 being Nat holds (for B3 being (Linear_Combination of ( R2 -VectSp_over ( F_Real ) )) holds (for B4 being (Linear_Combination of ( TOP-REAL R2 )) holds (B4 = B3 implies ( Carrier B4 ) = ( Carrier B3 )))))
proof
let R2 being Nat;
set D5 = ( R2 -VectSp_over ( F_Real ) );
set D6 = ( TOP-REAL R2 );
let C5 being (Linear_Combination of D5);
let C6 being (Linear_Combination of D6);
assume that
L27: C6 = C5;
thus L28: ( Carrier C6 ) c= ( Carrier C5 )
proof
let C7 being set;
assume L29: C7 in ( Carrier C6 );
reconsider D7 = C7 as (Element of D6) by L29;
reconsider D8 = D7 as (Element of D5) by L1;
L30: ( C5 . D8 ) <> ( 0. ( F_Real ) ) by L27 , L29 , RLVECT_2:19;
thus L31: thesis by L30 , VECTSP_6:1;
end;

let C8 being set;
assume L32: C8 in ( Carrier C5 );
consider C9 being (Element of D5) such that L33: C8 = C9 and L34: ( C5 . C9 ) <> ( 0. ( F_Real ) ) by L32 , VECTSP_6:1;
reconsider D9 = C9 as (Element of D6) by L1;
L35: D9 in ( Carrier C6 ) by L27 , L34 , RLVECT_2:19;
thus L36: thesis by L35 , L33;
end;
theorem
L37: (for R2 being Nat holds (for B5 being (FinSequence of ( TOP-REAL R2 )) holds (for B6 being (Function of ( TOP-REAL R2 ) , ( REAL )) holds (for B7 being (FinSequence of ( R2 -VectSp_over ( F_Real ) )) holds (for B8 being (Function of ( R2 -VectSp_over ( F_Real ) ) , ( F_Real )) holds ((B6 = B8 & B5 = B7) implies ( B6 (#) B5 ) = ( B8 (#) B7 )))))))
proof
let R2 being Nat;
let C10 being (FinSequence of ( TOP-REAL R2 ));
let C11 being (Function of ( TOP-REAL R2 ) , ( REAL ));
let C12 being (FinSequence of ( R2 -VectSp_over ( F_Real ) ));
let C13 being (Function of ( R2 -VectSp_over ( F_Real ) ) , ( F_Real ));
assume that
L38: C11 = C13
and
L39: C10 = C12;
L40: ( len ( C13 (#) C12 ) ) = ( len C12 ) by VECTSP_6:def 5;
L41: ( len ( C11 (#) C10 ) ) = ( len C10 ) by RLVECT_2:def 7;
L42:
now
reconsider D10 = ( TOP-REAL R2 ) as RealLinearSpace;
let C14 being Nat;
reconsider D11 = ( C10 /. C14 ) as (FinSequence of ( REAL )) by EUCLID:24;
reconsider D12 = ( C12 /. C14 ) as (Element of ( R2 -tuples_on (the carrier of ( F_Real )) )) by MATRIX13:102;
reconsider D13 = ( C10 /. C14 ) as (Element of D10);
assume L43: (1 <= C14 & C14 <= ( len C10 ));
L44: C14 in ( dom ( C13 (#) C12 ) ) by L43 , L39 , L40 , FINSEQ_3:25;
L45: C14 in ( dom C10 ) by L43 , FINSEQ_3:25;
L46: ( C10 /. C14 ) = ( C10 . C14 ) by L45 , PARTFUN1:def 6;
L47: C14 in ( dom C12 ) by L39 , L43 , FINSEQ_3:25;
L48: ( C12 /. C14 ) = ( C12 . C14 ) by L47 , PARTFUN1:def 6;
L49: C14 in ( dom ( C11 (#) C10 ) ) by L41 , L43 , FINSEQ_3:25;
thus L50: ( ( C11 (#) C10 ) . C14 ) = ( ( C11 . D13 ) * D13 ) by L49 , RLVECT_2:def 7
.= ( ( C11 . D11 ) * D11 ) by EUCLID:65
.= ( ( C13 . ( C12 /. C14 ) ) * D12 ) by L38 , L39 , L46 , L48 , MATRIXR1:17
.= ( ( C13 . ( C12 /. C14 ) ) * ( C12 /. C14 ) ) by MATRIX13:102
.= ( ( C13 (#) C12 ) . C14 ) by L44 , VECTSP_6:def 5;
end;
thus L51: thesis by L42 , L39 , L41 , L40 , FINSEQ_1:14;
end;
theorem
L52: (for R2 being Nat holds (for B9 being (FinSequence of ( TOP-REAL R2 )) holds (for B10 being (FinSequence of ( R2 -VectSp_over ( F_Real ) )) holds (B10 = B9 implies ( Sum B9 ) = ( Sum B10 )))))
proof
let R2 being Nat;
set D14 = ( TOP-REAL R2 );
set D15 = ( R2 -VectSp_over ( F_Real ) );
let C15 being (FinSequence of D14);
let C16 being (FinSequence of D15);
assume that
L53: C16 = C15;
reconsider D16 = ( TOP-REAL R2 ) as RealLinearSpace;
consider C17 being (Function of ( NAT ) , (the carrier of D16)) such that L54: ( Sum C15 ) = ( C17 . ( len C15 ) ) and L55: ( C17 . ( 0 ) ) = ( 0. D16 ) and L56: (for B11 being (Element of ( NAT )) holds (for B12 being (Element of D16) holds ((B11 < ( len C15 ) & B12 = ( C15 . ( B11 + 1 ) )) implies ( C17 . ( B11 + 1 ) ) = ( ( C17 . B11 ) + B12 )))) by RLVECT_1:def 12;
consider C18 being (Function of ( NAT ) , (the carrier of D15)) such that L57: ( Sum C16 ) = ( C18 . ( len C16 ) ) and L58: ( C18 . ( 0 ) ) = ( 0. D15 ) and L59: (for B13 being (Element of ( NAT )) holds (for B14 being (Element of D15) holds ((B13 < ( len C16 ) & B14 = ( C16 . ( B13 + 1 ) )) implies ( C18 . ( B13 + 1 ) ) = ( ( C18 . B13 ) + B14 )))) by RLVECT_1:def 12;
defpred S1[ Nat ] means ($1 <= ( len C15 ) implies ( C17 . $1 ) = ( C18 . $1 ));
L60: (for B15 being (Element of ( NAT )) holds (S1[ B15 ] implies S1[ ( B15 + 1 ) ]))
proof
let C19 being (Element of ( NAT ));
assume that
L61: S1[ C19 ];
set D17 = ( C19 + 1 );
reconsider D18 = ( C16 /. D17 ) , D19 = ( C18 . C19 ) as (Element of ( R2 -tuples_on (the carrier of ( F_Real )) )) by MATRIX13:102;
L62: (( @ ( @ D18 ) ) = D18 & ( @ ( @ D19 ) ) = D19);
reconsider D20 = ( C15 /. D17 ) as (Element of D16);
assume L63: D17 <= ( len C15 );
L64: C19 < ( len C15 ) by L63 , NAT_1:13;
L65: 1 <= D17 by NAT_1:11;
L66: D17 in ( dom C15 ) by L65 , L63 , FINSEQ_3:25;
L67: ( C15 . D17 ) = ( C15 /. D17 ) by L66 , PARTFUN1:def 6;
L68: ( C17 . D17 ) = ( ( C17 . C19 ) + D20 ) by L67 , L56 , L64;
L69: ( C16 /. D17 ) = ( C16 . D17 ) by L53 , L66 , PARTFUN1:def 6;
L70: D18 = ( C15 /. D17 ) by L69 , L53 , L66 , PARTFUN1:def 6;
thus L71: ( C17 . D17 ) = ( ( @ D19 ) + ( @ D18 ) ) by L70 , L61 , L63 , L68 , EUCLID:64 , NAT_1:13
.= ( D19 + D18 ) by L62 , MATRTOP1:1
.= ( ( C18 . C19 ) + ( C16 /. D17 ) ) by MATRIX13:102
.= ( C18 . D17 ) by L53 , L59 , L64 , L69;
end;
L72: S1[ ( 0 ) ] by L55 , L58 , L3;
L73: (for B16 being (Element of ( NAT )) holds S1[ B16 ]) from NAT_1:sch 1(L72 , L60);
thus L74: thesis by L73 , L53 , L54 , L57;
end;
theorem
L75: (for R2 being Nat holds (for B17 being (Linear_Combination of ( R2 -VectSp_over ( F_Real ) )) holds (for B18 being (Linear_Combination of ( TOP-REAL R2 )) holds (B18 = B17 implies ( Sum B18 ) = ( Sum B17 )))))
proof
let R2 being Nat;
set D21 = ( R2 -VectSp_over ( F_Real ) );
set D22 = ( TOP-REAL R2 );
let C20 being (Linear_Combination of D21);
let C21 being (Linear_Combination of D22);
assume that
L76: C21 = C20;
consider C22 being (FinSequence of (the carrier of D22)) such that L77: (C22 is  one-to-one & ( rng C22 ) = ( Carrier C21 )) and L78: ( Sum C21 ) = ( Sum ( C21 (#) C22 ) ) by RLVECT_2:def 8;
reconsider D23 = C22 as (FinSequence of (the carrier of D21)) by L1;
L79: ( C21 (#) C22 ) = ( C20 (#) D23 ) by L76 , L37;
L80: ( Carrier C21 ) = ( Carrier C20 ) by L76 , L26;
thus L81: ( Sum C20 ) = ( Sum ( C20 (#) D23 ) ) by L80 , L77 , VECTSP_6:def 6
.= ( Sum C21 ) by L78 , L79 , L52;
end;
theorem
L82: (for R2 being Nat holds (for B19 being (Subset of ( R2 -VectSp_over ( F_Real ) )) holds (for B20 being (Subset of ( TOP-REAL R2 )) holds (B19 = B20 implies ( [#] ( Lin B20 ) ) = ( [#] ( Lin B19 ) )))))
proof
let R2 being Nat;
set D24 = ( R2 -VectSp_over ( F_Real ) );
set D25 = ( TOP-REAL R2 );
let C23 being (Subset of D24);
let C24 being (Subset of D25);
assume that
L83: C23 = C24;
thus L84:now
let C25 being set;
assume L85: C25 in ( [#] ( Lin C24 ) );
L86: C25 in ( Lin C24 ) by L85 , STRUCT_0:def 5;
consider C26 being (Linear_Combination of C24) such that L87: C25 = ( Sum C26 ) by L86 , RLVECT_3:14;
reconsider D26 = C26 as (Linear_Combination of D24) by L8;
L88: (( Carrier D26 ) = ( Carrier C26 ) & ( Carrier C26 ) c= C24) by L26 , RLVECT_2:def 6;
L89: D26 is (Linear_Combination of C23) by L88 , L83 , VECTSP_6:def 4;
L90: ( Sum D26 ) = ( Sum C26 ) by L75;
L91: C25 in ( Lin C23 ) by L90 , L87 , L89 , VECTSP_7:7;
thus L92: C25 in ( [#] ( Lin C23 ) ) by L91 , STRUCT_0:def 5;
end;
let C27 being set;
assume L93: C27 in ( [#] ( Lin C23 ) );
L94: C27 in ( Lin C23 ) by L93 , STRUCT_0:def 5;
consider C28 being (Linear_Combination of C23) such that L95: C27 = ( Sum C28 ) by L94 , VECTSP_7:7;
reconsider D27 = C28 as (Linear_Combination of D25) by L8;
L96: (( Carrier D27 ) = ( Carrier C28 ) & ( Carrier C28 ) c= C23) by L26 , VECTSP_6:def 4;
L97: D27 is (Linear_Combination of C24) by L96 , L83 , RLVECT_2:def 6;
L98: ( Sum D27 ) = ( Sum C28 ) by L75;
L99: C27 in ( Lin C24 ) by L98 , L95 , L97 , RLVECT_3:14;
thus L100: thesis by L99 , STRUCT_0:def 5;
end;
theorem
L101: (for R2 being Nat holds (for B21 being (Subset of ( R2 -VectSp_over ( F_Real ) )) holds (for B22 being (Subset of ( TOP-REAL R2 )) holds (B21 = B22 implies (B21 is  linearly-independent iff B22 is  linearly-independent)))))
proof
let R2 being Nat;
set D28 = ( R2 -VectSp_over ( F_Real ) );
let C29 being (Subset of D28);
set D29 = ( TOP-REAL R2 );
let C30 being (Subset of D29);
assume that
L102: C29 = C30;
thus L103:now
assume L104: C29 is  linearly-independent;
L105:
now
let C31 being (Linear_Combination of C30);
reconsider D30 = C31 as (Linear_Combination of D28) by L8;
L106: ( Carrier D30 ) = ( Carrier C31 ) by L26;
assume L107: ( Sum C31 ) = ( 0. D29 );
L108: ( 0. D28 ) = ( Sum C31 ) by L107 , L3
.= ( Sum D30 ) by L75;
L109: ( Carrier C31 ) c= C30 by RLVECT_2:def 6;
L110: D30 is (Linear_Combination of C29) by L109 , L102 , L106 , VECTSP_6:def 4;
thus L111: ( Carrier C31 ) = ( {} ) by L110 , L104 , L106 , L108 , VECTSP_7:def 1;
end;
thus L112: C30 is  linearly-independent by L105 , RLVECT_3:def 1;
end;
assume L113: C30 is  linearly-independent;
L114:
now
let C32 being (Linear_Combination of C29);
reconsider D31 = C32 as (Linear_Combination of D29) by L8;
L115: ( Carrier D31 ) = ( Carrier C32 ) by L26;
L116: ( Carrier C32 ) c= C29 by VECTSP_6:def 4;
reconsider D32 = D31 as (Linear_Combination of C30) by L116 , L102 , L115 , RLVECT_2:def 6;
assume L117: ( Sum C32 ) = ( 0. D28 );
L118: ( 0. D29 ) = ( Sum C32 ) by L117 , L3
.= ( Sum D32 ) by L75;
thus L119: ( Carrier C32 ) = ( {} ) by L118 , L113 , L115 , RLVECT_3:def 1;
end;
thus L120: thesis by L114 , VECTSP_7:def 1;
end;
theorem
L121: (for R5 being Field holds (for B23 being (VectSp of R5) holds (for B24 being (Subspace of B23) holds (for B25 being (Linear_Combination of B23) holds ( B25 | (the carrier of B24) ) is (Linear_Combination of B24)))))
proof
let R5 being Field;
let C33 being (VectSp of R5);
let C34 being (Subspace of C33);
let C35 being (Linear_Combination of C33);
set D33 = (the carrier of C34);
L122: D33 c= ( [#] C33 ) by VECTSP_4:def 2;
L123: ( C35 | D33 ) is (Function of D33 , (the carrier of R5)) by L122 , FUNCT_2:32;
reconsider D34 = ( C35 | D33 ) as (Element of ( Funcs (D33 , (the carrier of R5)) )) by L123 , FUNCT_2:8;
L124: (for B26 being (Element of C34) holds ((not B26 in ( ( Carrier C35 ) /\ D33 )) implies ( D34 . B26 ) = ( 0. R5 )))
proof
let C36 being (Element of C34);
reconsider D35 = C36 as (Element of C33) by VECTSP_4:10;
assume L125: (not C36 in ( ( Carrier C35 ) /\ D33 ));
L126: (not C36 in ( Carrier C35 )) by L125 , XBOOLE_0:def 4;
L127: ( C35 . D35 ) = ( D34 . C36 ) by FUNCT_1:49;
thus L128: thesis by L127 , L126 , VECTSP_6:2;
end;
L129: ( ( Carrier C35 ) /\ D33 ) c= D33 by XBOOLE_1:17;
thus L130: thesis by L129 , L124 , VECTSP_6:def 1;
end;
theorem
L131: (for R5 being Field holds (for B27 being (VectSp of R5) holds (for B28 being  linearly-independent (Subset of B27) holds (for B29 , B30 being (Linear_Combination of B27) holds ((( Carrier B29 ) c= B28 & ( Carrier B30 ) c= B28 & ( Sum B29 ) = ( Sum B30 )) implies B29 = B30)))))
proof
let R5 being Field;
let C37 being (VectSp of R5);
let C38 being  linearly-independent (Subset of C37);
let C39 , C40 being (Linear_Combination of C37);
assume that
L132: (( Carrier C39 ) c= C38 & ( Carrier C40 ) c= C38)
and
L133: ( Sum C39 ) = ( Sum C40 );
L134: (C39 is (Linear_Combination of C38) & C40 is (Linear_Combination of C38)) by L132 , VECTSP_6:def 4;
L135: ( C39 - C40 ) is (Linear_Combination of C38) by L134 , VECTSP_6:42;
L136: ( Sum ( C39 - C40 ) ) = ( ( Sum C39 ) - ( Sum C40 ) ) by VECTSP_6:47
.= ( 0. C37 ) by L133 , RLVECT_1:15;
L137: ( Carrier ( C39 - C40 ) ) = ( {} ) by L136 , L135 , VECTSP_7:def 1;
L138: ( ZeroLC C37 ) = ( C39 - C40 ) by L137 , VECTSP_6:def 3
.= ( C39 + ( - C40 ) ) by VECTSP_6:def 11
.= ( ( - C40 ) + C39 ) by VECTSP_6:25;
L139: C39 = ( - ( - C40 ) ) by L138 , VECTSP_6:37;
thus L140: thesis by L139;
end;
theorem
L141: (for B31 being RealLinearSpace holds (for B32 being (Subspace of B31) holds (for B33 being (Linear_Combination of B31) holds ( B33 | (the carrier of B32) ) is (Linear_Combination of B32))))
proof
let C41 being RealLinearSpace;
let C42 being (Subspace of C41);
let C43 being (Linear_Combination of C41);
set D36 = (the carrier of C42);
L142: D36 c= ( [#] C41 ) by RLSUB_1:def 2;
L143: ( C43 | D36 ) is (Function of D36 , ( REAL )) by L142 , FUNCT_2:32;
reconsider D37 = ( C43 | D36 ) as (Element of ( Funcs (D36 , ( REAL )) )) by L143 , FUNCT_2:8;
L144: (for B34 being (Element of C42) holds ((not B34 in ( ( Carrier C43 ) /\ D36 )) implies ( D37 . B34 ) = ( 0 )))
proof
let C44 being (Element of C42);
reconsider D38 = C44 as (Element of C41) by RLSUB_1:10;
assume L145: (not C44 in ( ( Carrier C43 ) /\ D36 ));
L146: (not C44 in ( Carrier C43 )) by L145 , XBOOLE_0:def 4;
L147: ( C43 . D38 ) = ( D37 . C44 ) by FUNCT_1:49;
thus L148: thesis by L147 , L146 , RLVECT_2:19;
end;
L149: ( ( Carrier C43 ) /\ D36 ) c= D36 by XBOOLE_1:17;
thus L150: thesis by L149 , L144 , RLVECT_2:def 3;
end;
theorem
L151: (for R1 being set holds (for R2 being Nat holds (for B35 being (Subspace of ( R2 -VectSp_over ( F_Real ) )) holds (for B36 being (Subspace of ( TOP-REAL R2 )) holds (( [#] B35 ) = ( [#] B36 ) implies (R1 is (Linear_Combination of B35) iff R1 is (Linear_Combination of B36)))))))
proof
let R1 being set;
let R2 being Nat;
set D39 = ( R2 -VectSp_over ( F_Real ) );
set D40 = ( TOP-REAL R2 );
let C45 being (Subspace of D39);
let C46 being (Subspace of D40);
assume that
L152: ( [#] C45 ) = ( [#] C46 );
thus L153:now
assume L154: R1 is (Linear_Combination of C45);
reconsider D41 = R1 as (Linear_Combination of C45) by L154;
L155: (ex B37 being  finite (Subset of C45) st (for B38 being (Element of C45) holds ((not B38 in B37) implies ( D41 . B38 ) = ( 0. ( F_Real ) )))) by VECTSP_6:def 1;
thus L156: R1 is (Linear_Combination of C46) by L155 , L152 , RLVECT_2:def 3;
end;
assume L157: R1 is (Linear_Combination of C46);
reconsider D42 = R1 as (Linear_Combination of C46) by L157;
consider C47 being  finite (Subset of C46) such that L158: (for B39 being (Element of C46) holds ((not B39 in C47) implies ( D42 . B39 ) = ( 0 ))) by RLVECT_2:def 3;
L159: (for B40 being (Element of C45) holds ((not B40 in C47) implies ( 0. ( F_Real ) ) = ( D42 . B40 ))) by L152 , L158;
thus L160: thesis by L159 , L152 , VECTSP_6:def 1;
end;
theorem
L161: (for R2 being Nat holds (for B41 being (Subspace of ( R2 -VectSp_over ( F_Real ) )) holds (for B42 being (Subspace of ( TOP-REAL R2 )) holds (for B43 being (Linear_Combination of B41) holds (for B44 being (Linear_Combination of B42) holds (B43 = B44 implies (( Carrier B43 ) = ( Carrier B44 ) & ( Sum B43 ) = ( Sum B44 ))))))))
proof
let R2 being Nat;
set D43 = ( R2 -VectSp_over ( F_Real ) );
set D44 = ( TOP-REAL R2 );
let C48 being (Subspace of D43);
let C49 being (Subspace of ( TOP-REAL R2 ));
let C50 being (Linear_Combination of C48);
let C51 being (Linear_Combination of C49);
assume that
L162: C50 = C51;
reconsider D45 = C51 as (Function of (the carrier of C49) , ( REAL ));
defpred S2[ set , set ] means (($1 in C49 & $2 = ( C51 . $1 )) or ((not $1 in C49) & $2 = ( 0 )));
L163: (( dom C50 ) = ( [#] C48 ) & ( dom C51 ) = ( [#] C49 )) by FUNCT_2:def 1;
L164: (for B45 being set holds (B45 in (the carrier of D44) implies (ex B46 being set st (B46 in ( REAL ) & S2[ B45 , B46 ]))))
proof
let C52 being set;
assume L165: C52 in (the carrier of D44);
reconsider D46 = C52 as (VECTOR of D44) by L165;
per cases ;
suppose L166: D46 in C49;

reconsider D47 = D46 as (VECTOR of C49) by L166 , STRUCT_0:def 5;
L167: S2[ D47 , ( C51 . D47 ) ] by L166;
thus L168: thesis by L167;
end;
suppose L169: (not D46 in C49);

thus L170: thesis by L169;
end;
end;
consider C53 being (Function of (the carrier of D44) , ( REAL )) such that L172: (for B47 being set holds (B47 in (the carrier of D44) implies S2[ B47 , ( C53 . B47 ) ])) from FUNCT_2:sch 1(L164);
L173: (the carrier of C49) c= (the carrier of D44) by RLSUB_1:def 2;
reconsider D48 = ( Carrier C51 ) as  finite (Subset of D44) by L173 , XBOOLE_1:1;
L174: C53 is (Element of ( Funcs ((the carrier of D44) , ( REAL )) )) by FUNCT_2:8;
L175:
now
let C54 being (VECTOR of D44);
assume L176: (not C54 in D48);
L177: ((S2[ C54 , ( C51 . C54 ) ] & (not C54 in D48) & C54 in (the carrier of C49)) or S2[ C54 , ( 0 ) ]) by L176 , STRUCT_0:def 5;
L178: ((S2[ C54 , ( C51 . C54 ) ] & ( C51 . C54 ) = ( 0 )) or S2[ C54 , ( 0 ) ]) by L177 , RLVECT_2:19;
thus L179: ( C53 . C54 ) = ( 0 ) by L178 , L172;
end;
reconsider D49 = C53 as (Linear_Combination of D44) by L175 , L174 , RLVECT_2:def 3;
reconsider D50 = ( D49 | (the carrier of C49) ) as (Function of (the carrier of C49) , ( REAL )) by L173 , FUNCT_2:32;
L180:
now
let C55 being set;
assume L181: C55 in (the carrier of C49);
L182: S2[ C55 , ( D49 . C55 ) ] by L181 , L173 , L172;
thus L183: ( D45 . C55 ) = ( D50 . C55 ) by L182 , L181 , FUNCT_1:49 , STRUCT_0:def 5;
end;
L184: C51 = D50 by L180 , FUNCT_2:12;
reconsider D51 = D49 as (Linear_Combination of D43) by L8;
L185:
now
let C56 being set;
assume that
L186: C56 in ( Carrier D49 )
and
L187: (not C56 in (the carrier of C49));
consider C57 being (VECTOR of D44) such that L188: C56 = C57 and L189: ( D49 . C57 ) <> ( 0 ) by L186 , RLVECT_5:3;
L190: S2[ C57 , ( 0 ) ] by L187 , L188 , STRUCT_0:def 5;
thus L191: contradiction by L190 , L172 , L189;
end;
L192: ( Carrier D49 ) c= (the carrier of C49) by L185 , TARSKI:def 3;
L193: (( Carrier D49 ) = ( Carrier C51 ) & ( Sum D49 ) = ( Sum C51 )) by L192 , L184 , RLVECT_5:10;
L194: ( Carrier D49 ) = ( Carrier D51 ) by L26;
L195: ( Sum D51 ) = ( Sum C50 ) by L194 , L162 , L163 , L192 , L184 , VECTSP_9:7;
thus L196: thesis by L195 , L162 , L163 , L184 , L193 , L194 , L75 , VECTSP_9:7;
end;
registration
let R3 being Nat;
let R5 being Field;
let C58 being (Subset of ( R3 -VectSp_over R5 ));
cluster ( Lin C58 ) ->  finite-dimensional;
coherence;
end;
L198: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds ( lines R7 ) c= ( [#] ( Lin ( lines R7 ) ) ))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
let C59 being set;
assume L199: C59 in ( lines R7 );
L200: C59 in ( Lin ( lines R7 ) ) by L199 , VECTSP_7:8;
thus L201: thesis by L200 , STRUCT_0:def 5;
end;
begin
theorem
L202: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (( the_rank_of R7 ) = R2 implies R7 is (OrdBasis of ( Lin ( lines R7 ) ))))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
L203: ( lines R7 ) c= ( [#] ( Lin ( lines R7 ) ) ) by L198;
reconsider D52 = ( lines R7 ) as (Subset of ( Lin ( lines R7 ) )) by L203;
reconsider D53 = R7 as (FinSequence of ( Lin ( lines R7 ) )) by L203 , FINSEQ_1:def 4;
assume that
L204: ( the_rank_of R7 ) = R2;
L205: R7 is  one-to-one by L204 , MATRIX13:121;
L206: ( lines R7 ) is  linearly-independent by L204 , MATRIX13:121;
L207: D52 is  linearly-independent by L206 , VECTSP_9:12;
L208: ( Lin D52 ) = ( Lin ( lines R7 ) ) by VECTSP_9:17;
L209: D52 is (Basis of ( Lin ( lines R7 ) )) by L208 , L207 , VECTSP_7:def 3;
L210: D53 is (OrdBasis of ( Lin ( lines R7 ) )) by L209 , L205 , MATRLIN:def 2;
thus L211: thesis by L210;
end;
theorem
L212: (for R5 being Field holds (for B48 , B49 being (VectSp of R5) holds (for B50 being (linear-transformation of B48 , B49) holds (for B51 being (Subset of B48) holds (for B52 being (Linear_Combination of B51) holds (( B50 | B51 ) is  one-to-one implies ( B50 . ( Sum B52 ) ) = ( Sum ( B50 @ B52 ) )))))))
proof
let R5 being Field;
let C60 , C61 being (VectSp of R5);
let C62 being (linear-transformation of C60 , C61);
let C63 being (Subset of C60);
let C64 being (Linear_Combination of C63);
consider C65 being (FinSequence of C60) such that L213: C65 is  one-to-one and L214: ( rng C65 ) = ( Carrier C64 ) and L215: ( Sum C64 ) = ( Sum ( C64 (#) C65 ) ) by VECTSP_6:def 6;
set D54 = ( C62 * C65 );
reconsider D55 = D54 as (FinSequence of C61);
L216: ( Carrier C64 ) c= C63 by VECTSP_6:def 4;
L217: ( ( C62 | C63 ) | ( Carrier C64 ) ) = ( C62 | ( Carrier C64 ) ) by L216 , RELAT_1:74;
assume L218: ( C62 | C63 ) is  one-to-one;
L219: ( C62 | ( Carrier C64 ) ) is  one-to-one by L218 , L217 , FUNCT_1:52;
L220: ( rng D55 ) = ( C62 .: ( Carrier C64 ) ) by L214 , RELAT_1:127
.= ( Carrier ( C62 @ C64 ) ) by L219 , RANKNULL:39;
L221: ( dom C62 ) = ( [#] C60 ) by FUNCT_2:def 1;
L222: D55 is  one-to-one by L221 , L218 , L217 , L213 , L214 , FUNCT_1:52 , RANKNULL:1;
L223: ( Sum ( C62 @ C64 ) ) = ( Sum ( ( C62 @ C64 ) (#) D55 ) ) by L222 , L220 , VECTSP_6:def 6;
L224: ( C62 * ( C64 (#) C65 ) ) = ( ( C62 @ C64 ) (#) D55 ) by L219 , L214 , RANKNULL:38;
thus L225: thesis by L224 , L215 , L223 , MATRLIN:16;
end;
L226: (for R2 being Nat holds (for R3 being Nat holds (for R6 being R2 -element  real-valued FinSequence holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (( card ( lines R7 ) ) = 1 implies (ex B53 being (Linear_Combination of ( lines R7 )) st (( Sum B53 ) = ( ( Mx2Tran R7 ) . R6 ) & (for R4 being Nat holds (R4 in ( Seg R2 ) implies (( B53 . ( Line (R7 , R4) ) ) = ( Sum R6 ) & ( R7 " { ( Line (R7 , R4) ) } ) = ( dom R6 )))))))))))
proof
let R2 being Nat;
let R3 being Nat;
let R6 being R2 -element  real-valued FinSequence;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
assume that
L227: ( card ( lines R7 ) ) = 1;
per cases ;
suppose L228: R2 <> ( 0 );

deffunc H1(set) = ( 0. ( F_Real ) );
L229: ( len R7 ) = R2 by L228 , MATRIX13:1;
reconsider D56 = ( Sum R6 ) as (Element of ( F_Real )) by XREAL_0:def 1;
set D57 = ( ( Mx2Tran R7 ) . R6 );
L230: ( len D57 ) = R3 by CARD_1:def 7;
L231: ( len R6 ) = R2 by CARD_1:def 7;
set D58 = ( R3 -VectSp_over ( F_Real ) );
consider C66 being set such that L232: ( lines R7 ) = { C66 } by L227 , CARD_2:42;
L233: C66 in ( lines R7 ) by L232 , TARSKI:def 1;
consider C67 being set such that L234: C67 in ( dom R7 ) and L235: ( R7 . C67 ) = C66 by L233 , FUNCT_1:def 3;
reconsider D59 = C67 as Nat by L234;
L236: ( width R7 ) = R3 by L228 , MATRIX13:1;
reconsider D60 = ( Line (R7 , D59) ) as (Element of D58) by L236 , MATRIX13:102;
consider C68 being (Function of (the carrier of D58) , (the carrier of ( F_Real ))) such that L237: ( C68 . D60 ) = ( 1. ( F_Real ) ) and L238: (for B54 being (Element of D58) holds (B54 <> D60 implies ( C68 . B54 ) = H1(B54))) from FUNCT_2:sch 6;
reconsider D61 = C68 as (Element of ( Funcs ((the carrier of D58) , (the carrier of ( F_Real ))) )) by FUNCT_2:8;
L239: C66 = ( Line (R7 , D59) ) by L234 , L235 , MATRIX_2:16;
L240:
now
let C69 being (Vector of D58);
assume that
L241: (not C69 in ( lines R7 ));
L242: C69 <> D60 by L232 , L239 , L241 , TARSKI:def 1;
thus L243: ( D61 . C69 ) = ( 0. ( F_Real ) ) by L242 , L238;
end;
L244: ( len ( D56 * ( Line (R7 , D59) ) ) ) = R3 by L236 , CARD_1:def 7;
L245:
now
L246: ( len ( @ R6 ) ) = R2 by CARD_1:def 7;
reconsider D62 = ( @ R6 ) as (Element of ( R2 -tuples_on (the carrier of ( F_Real )) )) by L246 , FINSEQ_2:92;
let C70 being Nat;
set D63 = ( R7 * (D59 , C70) );
L247: R2 in ( NAT ) by ORDINAL1:def 12;
assume L248: (1 <= C70 & C70 <= R3);
L249: C70 in ( dom ( D56 * ( Line (R7 , D59) ) ) ) by L248 , L244 , FINSEQ_3:25;
L250: C70 in ( Seg R3 ) by L248 , FINSEQ_1:1;
L251: ( ( Line (R7 , D59) ) . C70 ) = D63 by L250 , L236 , MATRIX_1:def 7;
L252:
now
let C71 being Nat;
assume L253: (1 <= C71 & C71 <= R2);
L254: C71 in ( Seg R2 ) by L253 , FINSEQ_1:1;
L255: ( Line (R7 , C71) ) in ( lines R7 ) by L254 , MATRIX13:103;
L256: C71 in ( dom R7 ) by L229 , L253 , FINSEQ_3:25;
thus L257: ( ( Col (R7 , C70) ) . C71 ) = ( R7 * (C71 , C70) ) by L256 , MATRIX_1:def 8
.= ( ( Line (R7 , C71) ) . C70 ) by L236 , L250 , MATRIX_1:def 7
.= D63 by L232 , L239 , L251 , L255 , TARSKI:def 1
.= ( ( R2 |-> D63 ) . C71 ) by L254 , FINSEQ_2:57;
end;
L258: (( len ( Col (R7 , C70) ) ) = R2 & ( len ( R2 |-> D63 ) ) = R2) by L229 , CARD_1:def 7;
L259: ( Col (R7 , C70) ) = ( R2 |-> D63 ) by L258 , L252 , FINSEQ_1:14;
thus L260: ( D57 . C70 ) = ( ( @ R6 ) "*" ( Col (R7 , C70) ) ) by L228 , L248 , MATRTOP1:18
.= ( Sum ( mlt (( @ R6 ) , ( Col (R7 , C70) )) ) ) by FVSUM_1:def 9
.= ( Sum ( D63 * D62 ) ) by L259 , L247 , FVSUM_1:66
.= ( D63 * ( Sum ( @ R6 ) ) ) by FVSUM_1:73
.= ( D63 * D56 ) by MATRPROB:36
.= ( ( D56 * ( Line (R7 , D59) ) ) . C70 ) by L249 , L251 , FVSUM_1:50;
end;
reconsider D64 = D61 as (Linear_Combination of D58) by L240 , VECTSP_6:def 1;
L261: ( Carrier D64 ) c= { D60 }
proof
let C72 being set;
assume that
L262: C72 in ( Carrier D64 );
L263: ( D64 . C72 ) <> ( 0. ( F_Real ) ) by L262 , VECTSP_6:2;
L264: C72 = D60 by L263 , L238 , L262;
thus L265: thesis by L264 , TARSKI:def 1;
end;
reconsider D65 = D64 as (Linear_Combination of ( lines R7 )) by L261 , L232 , L239 , VECTSP_6:def 4;
L266: ( Sum D65 ) = ( ( 1. ( F_Real ) ) * D60 ) by L232 , L239 , L237 , VECTSP_6:17
.= D60 by VECTSP_1:def 17;
reconsider D66 = ( D56 * D65 ) as (Linear_Combination of ( lines R7 )) by VECTSP_6:31;
take D66;
L267: ( Sum D66 ) = ( D56 * ( Sum D65 ) ) by VECTSP_6:45
.= ( D56 * ( Line (R7 , D59) ) ) by L236 , L266 , MATRIX13:102;
thus L268: ( Sum D66 ) = D57 by L267 , L244 , L230 , L245 , FINSEQ_1:14;
let C73 being Nat;
assume that
L269: C73 in ( Seg R2 );
L270: ( Line (R7 , C73) ) in ( lines R7 ) by L269 , MATRIX13:103;
L271: ( Line (R7 , C73) ) = D60 by L270 , L232 , L239 , TARSKI:def 1;
thus L272: ( Sum R6 ) = ( D56 * ( 1. ( F_Real ) ) )
.= ( D66 . ( Line (R7 , C73) ) ) by L237 , L271 , VECTSP_6:def 9;
thus L273: ( R7 " { ( Line (R7 , C73) ) } ) = ( dom R7 ) by L232 , L239 , L271 , RELAT_1:134
.= ( dom R6 ) by L229 , L231 , FINSEQ_3:29;
end;
suppose L274: R2 = ( 0 );

reconsider D67 = ( ZeroLC ( R3 -VectSp_over ( F_Real ) ) ) as (Linear_Combination of ( lines R7 )) by VECTSP_6:5;
take D67;
thus L275: ( Sum D67 ) = ( 0. ( R3 -VectSp_over ( F_Real ) ) ) by VECTSP_6:15
.= ( 0. ( TOP-REAL R3 ) ) by L3
.= ( ( Mx2Tran R7 ) . R6 ) by L274 , MATRTOP1:def 3;
thus L276: thesis by L274;
end;
end;
theorem
L278: (for R2 being Nat holds (for R3 being Nat holds (for R6 being R2 -element  real-valued FinSequence holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B55 being (Subset of ( Seg R2 )) holds ((( R7 | B55 ) is  one-to-one & ( rng ( R7 | B55 ) ) = ( lines R7 )) implies (ex B56 being (Linear_Combination of ( lines R7 )) st (( Sum B56 ) = ( ( Mx2Tran R7 ) . R6 ) & (for R4 being Nat holds (R4 in B55 implies ( B56 . ( Line (R7 , R4) ) ) = ( Sum ( Seq ( R6 | ( R7 " { ( Line (R7 , R4) ) } ) ) ) )))))))))))
proof
let R2 being Nat;
let R3 being Nat;
let R6 being R2 -element  real-valued FinSequence;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
defpred S3[ Nat ] means (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for R6 being R2 -element  real-valued FinSequence holds (for B57 being (Subset of ( Seg R2 )) holds (((R2 = ( 0 ) implies R3 = ( 0 )) & ( R7 | B57 ) is  one-to-one & ( rng ( R7 | B57 ) ) = ( lines R7 ) & ( card ( lines R7 ) ) = $1) implies (ex B58 being (Linear_Combination of ( lines R7 )) st (( Sum B58 ) = ( ( Mx2Tran R7 ) . R6 ) & (for B59 being Nat holds (B59 in B57 implies ( B58 . ( Line (R7 , B59) ) ) = ( Sum ( Seq ( R6 | ( R7 " { ( Line (R7 , B59) ) } ) ) ) )))))))))));
L279: (for B60 being Nat holds (S3[ B60 ] implies S3[ ( B60 + 1 ) ]))
proof
let C74 being Nat;
assume that
L280: S3[ C74 ];
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
let R6 being R2 -element  real-valued FinSequence;
let C75 being (Subset of ( Seg R2 ));
assume that
L281: (R2 = ( 0 ) implies R3 = ( 0 ))
and
L282: ( R7 | C75 ) is  one-to-one
and
L283: ( rng ( R7 | C75 ) ) = ( lines R7 )
and
L284: ( card ( lines R7 ) ) = ( C74 + 1 );
L285: ( len R7 ) = R2 by L281 , MATRIX13:1;
L286: ( width R7 ) = R3 by L281 , MATRIX13:1;
per cases ;
suppose L287: C74 = ( 0 );

consider C76 being (Linear_Combination of ( lines R7 )) such that L288: ( Sum C76 ) = ( ( Mx2Tran R7 ) . R6 ) and L289: (for B61 being Nat holds (B61 in ( Seg R2 ) implies (( C76 . ( Line (R7 , B61) ) ) = ( Sum R6 ) & ( R7 " { ( Line (R7 , B61) ) } ) = ( dom R6 )))) by L287 , L284 , L226;
take C76;
thus L290: ( Sum C76 ) = ( ( Mx2Tran R7 ) . R6 ) by L288;
let C77 being Nat;
assume that
L291: C77 in C75;
L292: ( R7 " { ( Line (R7 , C77) ) } ) = ( dom R6 ) by L289 , L291;
L293: ( R6 | ( R7 " { ( Line (R7 , C77) ) } ) ) = R6 by L292 , RELAT_1:69;
L294: ( C76 . ( Line (R7 , C77) ) ) = ( Sum R6 ) by L289 , L291;
thus L295: ( Sum ( Seq ( R6 | ( R7 " { ( Line (R7 , C77) ) } ) ) ) ) = ( C76 . ( Line (R7 , C77) ) ) by L294 , L293 , FINSEQ_3:116;
end;
suppose L296: C74 > ( 0 );

L297: ( lines R7 ) <> ( {} ) by L284;
consider C78 being set such that L298: C78 in ( lines R7 ) by L297 , XBOOLE_0:def 1;
reconsider D68 = { C78 } as (Subset of ( lines R7 )) by L298 , ZFMISC_1:31;
set D69 = ( R2 -' ( card ( R7 " D68 ) ) );
reconsider D70 = ( R7 - D68 ) as (Matrix of D69 , R3 , ( F_Real )) by MATRTOP1:14;
L299: ( D68 ` ) = ( ( lines R7 ) \ D68 ) by SUBSET_1:def 4;
L300: D68 misses ( D68 ` ) by L299 , XBOOLE_1:79;
L301: ( D68 \/ ( D68 ` ) ) = ( [#] ( lines R7 ) ) by SUBSET_1:10
.= ( lines R7 ) by SUBSET_1:def 3;
L302: ( ( R7 " D68 ) \/ ( R7 " ( D68 ` ) ) ) = ( R7 " ( rng R7 ) ) by L301 , RELAT_1:140
.= ( dom R7 ) by RELAT_1:134;
L303: ( len D70 ) = ( ( len R7 ) - ( card ( R7 " D68 ) ) ) by FINSEQ_3:59;
L304: ( R2 - ( card ( R7 " D68 ) ) ) = D69 by L303 , L285 , XREAL_1:49 , XREAL_1:233;
L305: D68 misses ( D68 ` ) by L299 , XBOOLE_1:79;
L306: ( ( card ( R7 " D68 ) ) + ( card ( R7 " ( D68 ` ) ) ) ) = ( card ( dom R7 ) ) by L305 , L302 , CARD_2:40 , FUNCT_1:71
.= R2 by L285 , CARD_1:62;
L307: D69 <> ( 0 )
proof
assume L308: D69 = ( 0 );
L309: ( R7 " ( D68 ` ) ) = ( {} ) by L308 , L285 , L303 , L306 , XREAL_1:49 , XREAL_1:233;
L310: ( D68 ` ) misses ( rng R7 ) by L309 , RELAT_1:138;
L311: ( {} ) = ( ( lines R7 ) \ D68 ) by L310 , L299 , XBOOLE_1:67;
L312: ( lines R7 ) c= D68 by L311 , XBOOLE_1:37;
L313: ( lines R7 ) = D68 by L312 , XBOOLE_0:def 10;
L314: ( C74 + 1 ) = 1 by L313 , L284 , CARD_2:42;
thus L315: contradiction by L314 , L296;
end;
set D71 = ( R2 -' ( card ( R7 " ( D68 ` ) ) ) );
reconsider D72 = ( R7 - ( D68 ` ) ) as (Matrix of D71 , R3 , ( F_Real )) by MATRTOP1:14;
L316: ( rng D72 ) = ( ( rng R7 ) \ ( D68 ` ) ) by FINSEQ_3:65;
L317: ( rng D72 ) = ( ( D68 ` ) ` ) by L316 , SUBSET_1:def 4;
reconsider D73 = ( F_Real ) as Field;
set D74 = ( ( Mx2Tran R7 ) . R6 );
set D75 = ( R3 -VectSp_over ( F_Real ) );
L318: ( len R6 ) = R2 by CARD_1:def 7;
L319: ( dom R6 ) = ( Seg R2 ) by L318 , FINSEQ_1:def 3;
consider C79 being set such that L320: C79 in ( dom ( R7 | C75 ) ) and L321: ( ( R7 | C75 ) . C79 ) = C78 by L283 , L298 , FUNCT_1:def 3;
L322: C78 = ( R7 . C79 ) by L320 , L321 , FUNCT_1:47;
L323: C79 in ( dom R7 ) by L320 , RELAT_1:57;
L324: C79 in C75 by L320;
reconsider D76 = C79 as Nat by L320;
L325: C78 = ( Line (R7 , D76) ) by L323 , L322 , MATRIX_2:16;
L326: ( len D72 ) = ( ( len R7 ) - ( card ( R7 " ( D68 ` ) ) ) ) by FINSEQ_3:59;
L327: ( R2 - ( card ( R7 " ( D68 ` ) ) ) ) = D71 by L326 , L285 , XREAL_1:49 , XREAL_1:233;
L328: ( rng D70 ) = ( ( rng R7 ) \ D68 ) by FINSEQ_3:65;
L329: ( rng D70 ) = ( D68 ` ) by L328 , SUBSET_1:def 4;
reconsider D77 = ( Line (R7 , D76) ) as (Element of D75) by L286 , MATRIX13:102;
L330: ( card ( rng D70 ) ) = ( ( card ( rng R7 ) ) - ( card D68 ) ) by L328 , CARD_2:44
.= ( ( C74 + 1 ) - 1 ) by L284 , CARD_2:42;
L331: ( ( D68 ` ) ` ) = D68;
consider C80 being (Permutation of ( dom R7 )) such that L332: ( ( R7 - D68 ) ^ ( R7 - ( D68 ` ) ) ) = ( R7 * C80 ) by L331 , FINSEQ_3:115;
L333: ( dom R7 ) = ( Seg R2 ) by L285 , FINSEQ_1:def 3;
reconsider D78 = C80 as (Permutation of ( Seg R2 )) by L333;
L334: ( ( R7 | C75 ) * C80 ) = ( ( R7 | C75 ) * ( D78 | ( dom D78 ) ) )
.= ( ( R7 * D78 ) | ( ( dom D78 ) /\ ( D78 " C75 ) ) ) by FUNCT_1:100
.= ( ( R7 * D78 ) | ( D78 " C75 ) ) by RELAT_1:132 , XBOOLE_1:28;
reconsider D79 = C80 as  one-to-one Function;
L335: ( len ( R7 * D78 ) ) = R2 by MATRIX_1:def 2;
L336: ( dom ( R7 * D78 ) ) = ( Seg R2 ) by L335 , FINSEQ_1:def 3;
set D80 = ( ( D79 " ) . D76 );
L337: ( rng D78 ) = ( Seg R2 ) by FUNCT_2:def 3;
L338: (( D78 " C75 ) = ( ( D79 " ) .: C75 ) & ( dom ( D79 " ) ) = ( Seg R2 )) by L337 , FUNCT_1:33 , FUNCT_1:85;
L339: D80 in ( D78 " C75 ) by L338 , L324 , FUNCT_1:def 6;
L340: ( D78 . D80 ) = D76 by L324 , L337 , FUNCT_1:35;
L341: (not D80 in ( dom D70 ))
proof
assume L342: D80 in ( dom D70 );
L343: ( ( R7 * C80 ) . D80 ) = ( R7 . D76 ) by L339 , L340 , L336 , FUNCT_1:12;
L344: ( ( R7 * C80 ) . D80 ) = D77 by L343 , L323 , MATRIX_2:16;
L345: ( D70 . D80 ) = D77 by L344 , L332 , L342 , FINSEQ_1:def 7;
L346: ( D70 . D80 ) in D68 by L345 , L325 , TARSKI:def 1;
L347: ( D70 . D80 ) in ( D68 ` ) by L329 , L342 , FUNCT_1:def 3;
thus L348: contradiction by L347 , L300 , L346 , XBOOLE_0:3;
end;
set D81 = ( ( D78 " C75 ) \ { D80 } );
L349: ( dom R7 ) = ( Seg R2 ) by L285 , FINSEQ_1:def 3;
L350: ( dom ( R7 | C75 ) ) = C75 by L349 , RELAT_1:62;
L351: D81 c= ( dom D70 )
proof
let C81 being set;
assume L352: C81 in D81;
reconsider D82 = C81 as Nat by L352;
L353: ( ( R7 * D78 ) . C81 ) = ( R7 . ( D78 . C81 ) ) by L336 , L352 , FUNCT_1:12;
L354: (not C81 in { D80 }) by L352 , XBOOLE_0:def 5;
L355: C81 <> D80 by L354 , TARSKI:def 1;
L356: D80 in ( dom C80 ) by L339 , FUNCT_1:def 7;
L357: C81 in ( D78 " C75 ) by L352 , XBOOLE_0:def 5;
L358: ( D78 . C81 ) in ( dom ( R7 | C75 ) ) by L357 , L350 , FUNCT_1:def 7;
L359: C81 in ( dom C80 ) by L357 , FUNCT_1:def 7;
L360: ( D78 . C81 ) <> D76 by L359 , L340 , L355 , L356 , FUNCT_1:def 4;
L361: ( ( R7 | C75 ) . ( D78 . C81 ) ) <> ( ( R7 | C75 ) . D76 ) by L360 , L282 , L320 , L358 , FUNCT_1:def 4;
L362: ( ( R7 * D78 ) . C81 ) <> D77 by L361 , L321 , L325 , L353 , L358 , FUNCT_1:47;
L363: (not ( ( R7 * D78 ) . C81 ) in D68) by L362 , L325 , TARSKI:def 1;
assume L364: (not C81 in ( dom D70 ));
consider C82 being Nat such that L365: C82 in ( dom D72 ) and L366: D82 = ( ( len D70 ) + C82 ) by L364 , L332 , L336 , L352 , FINSEQ_1:25;
L367: ( ( R7 * D78 ) . D82 ) = ( D72 . C82 ) by L332 , L365 , L366 , FINSEQ_1:def 7;
thus L368: contradiction by L367 , L317 , L363 , L365 , FUNCT_1:def 3;
end;
L369: (( ( R7 * D78 ) | D81 ) = ( ( ( R7 * D78 ) | ( D78 " C75 ) ) | D81 ) & ( ( R7 * D78 ) | D81 ) = ( D70 | D81 )) by L351 , L332 , FINSEQ_6:11 , RELAT_1:74 , XBOOLE_1:36;
L370: ( D70 | D81 ) is  one-to-one by L369 , L282 , L334 , FUNCT_1:52;
L371: (( dom D78 ) = ( Seg R2 ) & ( D78 . D80 ) = D76) by L324 , L337 , FUNCT_1:35 , FUNCT_2:52;
L372: D80 in ( dom ( ( R7 | C75 ) * D78 ) ) by L371 , L320 , L339 , FUNCT_1:11;
L373: ( ( ( R7 | C75 ) * D78 ) . D80 ) = D77 by L372 , L321 , L325 , L340 , FUNCT_1:12;
L374: D68 = ( Im (( ( R7 | C75 ) * D78 ) , D80) ) by L373 , L325 , L372 , FUNCT_1:59
.= ( ( ( R7 * D78 ) | ( D78 " C75 ) ) .: { D80 } ) by L334 , RELAT_1:def 16;
L375: ( rng R7 ) = ( rng ( ( R7 * D78 ) | ( D78 " C75 ) ) ) by L283 , L334 , L337 , L350 , RELAT_1:28
.= ( ( R7 * D78 ) .: ( D78 " C75 ) ) by RELAT_1:115
.= ( ( ( R7 * D78 ) | ( D78 " C75 ) ) .: ( D78 " C75 ) ) by RELAT_1:129;
L376: ( rng D70 ) = ( ( ( R7 * D78 ) | ( D78 " C75 ) ) .: D81 ) by L375 , L282 , L334 , L328 , L374 , FUNCT_1:64
.= ( rng ( ( ( R7 * D78 ) | ( D78 " C75 ) ) | D81 ) ) by RELAT_1:115
.= ( rng ( ( R7 * D78 ) | D81 ) ) by RELAT_1:74 , XBOOLE_1:36
.= ( rng ( D70 | D81 ) ) by L332 , L351 , FINSEQ_6:11;
reconsider D83 = ( R6 * D78 ) as R2 -element (FinSequence of ( REAL )) by MATRTOP1:21;
L377: ( D69 + D71 ) = ( len ( D70 ^ D72 ) ) by MATRIX_1:def 2
.= ( len ( R7 * D78 ) ) by L332
.= R2 by MATRIX_1:def 2;
L378: ( len D83 ) = R2 by CARD_1:def 7;
consider C83 , C84 being (FinSequence of ( REAL )) such that L379: ( len C83 ) = D69 and L380: ( len C84 ) = D71 and L381: D83 = ( C83 ^ C84 ) by L378 , L377 , FINSEQ_2:23;
L382: C84 is D71 -element by L380 , CARD_1:def 7;
L383: ( len ( ( Mx2Tran D72 ) . C84 ) ) = R3 by L382 , CARD_1:def 7;
L384: ( card D68 ) = 1 by CARD_2:42;
consider C85 being (Linear_Combination of ( lines D72 )) such that L385: ( Sum C85 ) = ( ( Mx2Tran D72 ) . C84 ) and L386: (for B62 being Nat holds (B62 in ( Seg D71 ) implies (( C85 . ( Line (D72 , B62) ) ) = ( Sum C84 ) & ( D72 " { ( Line (D72 , B62) ) } ) = ( dom C84 )))) by L384 , L382 , L317 , L226;
L387: C83 is D69 -element by L379 , CARD_1:def 7;
L388: ( len ( ( Mx2Tran D70 ) . C83 ) ) = R3 by L387 , CARD_1:def 7;
reconsider D84 = ( @ ( ( Mx2Tran D70 ) . C83 ) ) , D85 = ( @ ( ( Mx2Tran D72 ) . C84 ) ) as (Element of ( R3 -tuples_on (the carrier of ( F_Real )) )) by L388 , L383 , FINSEQ_2:92;
L389: ( Carrier C85 ) c= ( lines D72 ) by VECTSP_6:def 4;
L390: ( len D70 ) = D69 by L285 , L303 , XREAL_1:49 , XREAL_1:233;
L391: D81 is (Subset of ( Seg D69 )) by L390 , L351 , FINSEQ_1:def 3;
consider C86 being (Linear_Combination of ( lines D70 )) such that L392: ( Sum C86 ) = ( ( Mx2Tran D70 ) . C83 ) and L393: (for B63 being Nat holds (B63 in D81 implies ( C86 . ( Line (D70 , B63) ) ) = ( Sum ( Seq ( C83 | ( D70 " { ( Line (D70 , B63) ) } ) ) ) ))) by L391 , L280 , L387 , L307 , L370 , L376 , L330;
L394: ( Carrier C86 ) c= ( lines D70 ) by VECTSP_6:def 4;
L395: ( ( rng D70 ) \/ ( rng D72 ) ) = ( [#] ( lines R7 ) ) by L317 , L329 , SUBSET_1:10
.= ( lines R7 ) by SUBSET_1:def 3;
L396: (C86 is (Linear_Combination of ( lines R7 )) & C85 is (Linear_Combination of ( lines R7 ))) by L395 , VECTSP_6:4 , XBOOLE_1:7;
reconsider D86 = ( C86 + C85 ) as (Linear_Combination of ( lines R7 )) by L396 , VECTSP_6:24;
take D86;
thus L397: ( ( Mx2Tran R7 ) . R6 ) = ( ( Mx2Tran ( D70 ^ D72 ) ) . ( C83 ^ C84 ) ) by L332 , L377 , L381 , MATRTOP1:21
.= ( ( ( Mx2Tran D70 ) . C83 ) + ( ( Mx2Tran D72 ) . C84 ) ) by L387 , L382 , MATRTOP1:36
.= ( D84 + D85 ) by MATRTOP1:1
.= ( ( Sum C86 ) + ( Sum C85 ) ) by L392 , L385 , MATRIX13:102
.= ( Sum D86 ) by VECTSP_6:44;
let C87 being Nat;
assume that
L398: C87 in C75;
L399: ( Line (R7 , C87) ) in ( lines R7 ) by L398 , MATRIX13:103;
reconsider D87 = ( Line (R7 , C87) ) as (Element of D75) by L399;
L400: ( D78 " ( R7 " { D87 } ) ) = ( ( R7 * D78 ) " { D87 } ) by RELAT_1:146;
L401: ( Sum ( Seq ( R6 | ( R7 " { D87 } ) ) ) ) = ( Sum ( Seq ( D83 | ( ( R7 * D78 ) " { D87 } ) ) ) ) by L400 , L319 , MATRTOP1:10
.= ( Sum ( ( Seq ( C83 | ( D70 " { D87 } ) ) ) ^ ( Seq ( C84 | ( D72 " { D87 } ) ) ) ) ) by L285 , L332 , L379 , L380 , L381 , L303 , L326 , L304 , L327 , MATRTOP1:13
.= ( ( Sum ( Seq ( C83 | ( D70 " { D87 } ) ) ) ) + ( Sum ( Seq ( C84 | ( D72 " { D87 } ) ) ) ) ) by RVSUM_1:75;
set D88 = ( ( D79 " ) . C87 );
L402: D88 in ( D78 " C75 ) by L338 , L398 , FUNCT_1:def 6;
L403: ( D78 . D88 ) = C87 by L337 , L398 , FUNCT_1:35;
L404: ( ( R7 * C80 ) . D88 ) = ( R7 . C87 ) by L403 , L336 , L402 , FUNCT_1:12;
reconsider D89 = D88 as Nat by L402;
L405: ( R7 . C87 ) = D87 by L398 , MATRIX_2:8;
reconsider D90 = ( C86 . D87 ) , D91 = ( C85 . D87 ) as (Element of D73);
L406: ( D86 . D87 ) = ( D90 + D91 ) by VECTSP_6:22;
per cases  by L332 , L336 , L402 , FINSEQ_1:25;
suppose L407: D89 in ( dom D70 );

L408: ( D70 . D89 ) = D87 by L407 , L332 , L404 , L405 , FINSEQ_1:def 7;
L409: D87 in ( rng D70 ) by L408 , L407 , FUNCT_1:def 3;
L410: (not D87 in ( Carrier C85 )) by L409 , L317 , L329 , L389 , L300 , XBOOLE_0:3;
L411: ( C85 . D87 ) = ( 0. ( F_Real ) ) by L410 , VECTSP_6:2;
L412: (not D87 in ( rng D72 )) by L317 , L329 , L300 , L409 , XBOOLE_0:3;
L413: { D87 } misses ( rng D72 ) by L412 , ZFMISC_1:50;
L414: ( D72 " { D87 } ) = ( {} ) by L413 , RELAT_1:138;
L415: ( Sum ( Seq ( C84 | ( D72 " { D87 } ) ) ) ) = ( 0 ) by L414 , RVSUM_1:72;
L416: (( Line (D70 , D89) ) = ( D70 . D89 ) & D89 in D81) by L402 , L341 , L407 , MATRIX_2:16 , ZFMISC_1:56;
L417: ( C86 . D87 ) = ( Sum ( Seq ( C83 | ( D70 " { D87 } ) ) ) ) by L416 , L393 , L408;
thus L418: thesis by L417 , L401 , L406 , L411 , L415 , RLVECT_1:def 4;
end;
suppose L419: (ex B64 being Nat st (B64 in ( dom D72 ) & D89 = ( ( len D70 ) + B64 )));

consider C88 being Nat such that L420: C88 in ( dom D72 ) and L421: D89 = ( ( len D70 ) + C88 ) by L419;
L422: ( D72 . C88 ) = D87 by L332 , L404 , L405 , L420 , L421 , FINSEQ_1:def 7;
L423: D87 in ( rng D72 ) by L422 , L420 , FUNCT_1:def 3;
L424: (not D87 in ( Carrier C86 )) by L423 , L317 , L329 , L394 , L300 , XBOOLE_0:3;
L425: ( C86 . D87 ) = ( 0. ( F_Real ) ) by L424 , VECTSP_6:2;
L426: (not D87 in ( D68 ` )) by L317 , L300 , L423 , XBOOLE_0:3;
L427: { D87 } misses ( rng D70 ) by L426 , L329 , ZFMISC_1:50;
L428: ( D70 " { D87 } ) = ( {} ) by L427 , RELAT_1:138;
L429: ( Seq ( C83 | ( D70 " { D87 } ) ) ) = ( <*> ( REAL ) ) by L428;
L430: ( D90 + D91 ) = ( D91 + D90 ) by RLVECT_1:def 2;
L431: ( D86 . D87 ) = ( C85 . D87 ) by L430 , L406 , L425 , RLVECT_1:def 4;
L432: ( dom D72 ) = ( Seg D71 ) by L285 , L326 , L327 , FINSEQ_1:def 3;
L433: ( D72 . C88 ) = ( Line (D72 , C88) ) by L420 , MATRIX_2:16;
L434: ( D72 " { D87 } ) = ( dom C84 ) by L433 , L386 , L420 , L422 , L432;
L435: ( C84 | ( D72 " { D87 } ) ) = C84 by L434 , RELAT_1:69;
L436: ( C85 . D87 ) = ( Sum C84 ) by L386 , L420 , L422 , L433 , L432;
thus L437: thesis by L436 , L401 , L431 , L429 , L435 , FINSEQ_3:116 , RVSUM_1:72;
end;
end;
end;
L440: S3[ ( 0 ) ]
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
let R6 being R2 -element  real-valued FinSequence;
let C89 being (Subset of ( Seg R2 ));
assume that
L441: (R2 = ( 0 ) implies R3 = ( 0 ))
and
L442: ( R7 | C89 ) is  one-to-one
and
L443: ( rng ( R7 | C89 ) ) = ( lines R7 )
and
L444: ( card ( lines R7 ) ) = ( 0 );
reconsider D92 = ( ZeroLC ( R3 -VectSp_over ( F_Real ) ) ) as (Linear_Combination of ( lines R7 )) by VECTSP_6:5;
take D92;
L445: ( Sum D92 ) = ( 0. ( R3 -VectSp_over ( F_Real ) ) ) by VECTSP_6:15
.= ( 0. ( TOP-REAL R3 ) ) by L3;
L446: (( len R7 ) = R2 & R7 = ( {} )) by L441 , L444 , MATRIX13:1;
L447: ( 0. ( TOP-REAL R3 ) ) = ( {} ) by L446 , L441;
thus L448: ( Sum D92 ) = ( ( Mx2Tran R7 ) . R6 ) by L447 , L441 , L446 , L445;
let C90 being Nat;
thus L449: thesis by L446;
end;
L450: (for B65 being Nat holds S3[ B65 ]) from NAT_1:sch 2(L440 , L279);
L451: S3[ ( card ( lines R7 ) ) ] by L450;
per cases ;
suppose L452: R2 <> ( 0 );

thus L453: thesis by L452 , L451;
end;
suppose L454: R2 = ( 0 );

let C91 being (Subset of ( Seg R2 ));
assume that
L455: (( R7 | C91 ) is  one-to-one & ( rng ( R7 | C91 ) ) = ( lines R7 ));
reconsider D93 = ( ZeroLC ( R3 -VectSp_over ( F_Real ) ) ) as (Linear_Combination of ( lines R7 )) by VECTSP_6:5;
take D93;
thus L456: ( Sum D93 ) = ( 0. ( R3 -VectSp_over ( F_Real ) ) ) by VECTSP_6:15
.= ( 0. ( TOP-REAL R3 ) ) by L3
.= ( ( Mx2Tran R7 ) . R6 ) by L454 , MATRTOP1:def 3;
thus L457: thesis by L454;
end;
end;
theorem
L459: (for R2 being Nat holds (for R3 being Nat holds (for R6 being R2 -element  real-valued FinSequence holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (R7 is  without_repeated_line implies (ex B66 being (Linear_Combination of ( lines R7 )) st (( Sum B66 ) = ( ( Mx2Tran R7 ) . R6 ) & (for R4 being Nat holds (R4 in ( dom R6 ) implies ( B66 . ( Line (R7 , R4) ) ) = ( R6 . R4 ))))))))))
proof
let R2 being Nat;
let R3 being Nat;
let R6 being R2 -element  real-valued FinSequence;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
assume that
L460: R7 is  without_repeated_line;
L461: ( len R7 ) = R2 by MATRIX_1:def 2;
L462: ( dom R7 ) c= ( Seg R2 ) by L461 , FINSEQ_1:def 3;
reconsider D94 = ( dom R7 ) as (Subset of ( Seg R2 )) by L462;
L463: ( len R6 ) = R2 by CARD_1:def 7;
L464: ( dom R6 ) = ( dom R7 ) by L463 , L461 , FINSEQ_3:29;
L465: ( R7 | ( dom R7 ) ) = R7;
consider C92 being (Linear_Combination of ( lines R7 )) such that L466: ( Sum C92 ) = ( ( Mx2Tran R7 ) . R6 ) and L467: (for B67 being Nat holds (B67 in D94 implies ( C92 . ( Line (R7 , B67) ) ) = ( Sum ( Seq ( R6 | ( R7 " { ( Line (R7 , B67) ) } ) ) ) ))) by L465 , L460 , L278;
take C92;
thus L468: ( Sum C92 ) = ( ( Mx2Tran R7 ) . R6 ) by L466;
let C93 being Nat;
assume that
L469: C93 in ( dom R6 );
L470: C93 >= 1 by L469 , FINSEQ_3:25;
L471: ( Sgm { C93 } ) = <* C93 *> by L470 , FINSEQ_3:44;
set D95 = ( Line (R7 , C93) );
L472: D95 in { D95 } by TARSKI:def 1;
L473: ( dom R7 ) = ( Seg R2 ) by L461 , FINSEQ_1:def 3;
L474: D95 in ( lines R7 ) by L473 , L464 , L469 , MATRIX13:103;
consider C94 being set such that L475: ( R7 " { D95 } ) = { C94 } by L474 , L460 , FUNCT_1:74;
L476: ( dom ( R6 | { C93 } ) ) = ( ( dom R6 ) /\ { C93 } ) by RELAT_1:61;
L477: { C93 } c= ( dom R6 ) by L469 , ZFMISC_1:31;
L478: ( dom ( R6 | { C93 } ) ) = { C93 } by L477 , L476 , XBOOLE_1:28;
L479: C93 in ( dom ( R6 | { C93 } ) ) by L478 , TARSKI:def 1;
L480: ( ( R6 | { C93 } ) . C93 ) = ( R6 . C93 ) by L479 , FUNCT_1:47;
L481: ( rng <* C93 *> ) = { C93 } by FINSEQ_1:38;
L482: <* C93 *> is (FinSequence of { C93 }) by L481 , FINSEQ_1:def 4;
L483: (( rng ( R6 | { C93 } ) ) <> ( {} ) & ( R6 | { C93 } ) is (Function of { C93 } , ( rng ( R6 | { C93 } ) ))) by L478 , FUNCT_2:1 , RELAT_1:42;
L484: ( Seq ( R6 | { C93 } ) ) = <* ( R6 . C93 ) *> by L483 , L478 , L471 , L482 , L480 , FINSEQ_2:35;
L485: ( Sum ( Seq ( R6 | { C93 } ) ) ) = ( R6 . C93 ) by L484 , RVSUM_1:73;
L486: ( R7 . C93 ) = D95 by L464 , L469 , MATRIX_2:16;
L487: C93 in ( R7 " { D95 } ) by L486 , L464 , L469 , L472 , FUNCT_1:def 7;
L488: ( R6 | ( R7 " { D95 } ) ) = ( R6 | { C93 } ) by L487 , L475 , TARSKI:def 1;
thus L489: thesis by L488 , L467 , L464 , L469 , L485;
end;
theorem
L490: (for R2 being Nat holds (for R3 being Nat holds (for R6 being R2 -element  real-valued FinSequence holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B68 being (OrdBasis of ( Lin ( lines R7 ) )) holds (B68 = R7 implies (for B69 being (Element of ( Lin ( lines R7 ) )) holds (B69 = ( ( Mx2Tran R7 ) . R6 ) implies ( B69 |-- B68 ) = R6))))))))
proof
let R2 being Nat;
let R3 being Nat;
let R6 being R2 -element  real-valued FinSequence;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
set D96 = ( lines R7 );
let C95 being (OrdBasis of ( Lin D96 ));
assume that
L491: C95 = R7;
L492: C95 is  one-to-one by MATRLIN:def 2;
let C96 being (Element of ( Lin D96 ));
assume that
L493: C96 = ( ( Mx2Tran R7 ) . R6 );
consider C97 being (Linear_Combination of D96) such that L494: ( Sum C97 ) = C96 and L495: (for B70 being Nat holds (B70 in ( dom R6 ) implies ( C97 . ( Line (R7 , B70) ) ) = ( R6 . B70 ))) by L491 , L493 , L492 , L459;
reconsider D97 = ( C97 | (the carrier of ( Lin D96 )) ) as (Linear_Combination of ( Lin D96 )) by L121;
L496: ( len R7 ) = R2 by MATRIX_1:def 2;
L497: ( len R6 ) = R2 by CARD_1:def 7;
L498: D96 c= ( [#] ( Lin D96 ) ) by L198;
L499:
now
let R4 being Nat;
assume L500: (1 <= R4 & R4 <= R2);
L501: R4 in ( Seg R2 ) by L500 , FINSEQ_1:1;
L502: ( R7 . R4 ) = ( Line (R7 , R4) ) by L501 , MATRIX_2:8;
L503: R4 in ( dom R7 ) by L496 , L500 , FINSEQ_3:25;
L504: ( C95 /. R4 ) = ( R7 . R4 ) by L503 , L491 , PARTFUN1:def 6;
L505: ( R7 . R4 ) in D96 by L503 , FUNCT_1:def 3;
L506: ( C97 . ( R7 . R4 ) ) = ( D97 . ( R7 . R4 ) ) by L505 , L498 , FUNCT_1:49;
L507: R4 in ( dom R6 ) by L497 , L500 , FINSEQ_3:25;
L508: ( R6 . R4 ) = ( ( @ R6 ) /. R4 ) by L507 , PARTFUN1:def 6;
thus L509: ( ( @ R6 ) /. R4 ) = ( D97 . ( C95 /. R4 ) ) by L508 , L495 , L507 , L504 , L502 , L506;
end;
L510: ( Carrier C97 ) c= D96 by VECTSP_6:def 4;
L511: ( Carrier C97 ) c= ( [#] ( Lin D96 ) ) by L510 , L498 , XBOOLE_1:1;
L512: (( Carrier C97 ) = ( Carrier D97 ) & ( Sum D97 ) = ( Sum C97 )) by L511 , VECTSP_9:7;
thus L513: thesis by L512 , L491 , L494 , L496 , L497 , L510 , L499 , MATRLIN:def 7;
end;
theorem
L514: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds ( rng ( Mx2Tran R7 ) ) = ( [#] ( Lin ( lines R7 ) ) ))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
consider C98 being set such that L515: C98 c= ( dom R7 ) and L516: ( lines R7 ) = ( rng ( R7 | C98 ) ) and L517: ( R7 | C98 ) is  one-to-one by MATRTOP1:6;
set D98 = ( R3 -VectSp_over ( F_Real ) );
set D99 = ( Mx2Tran R7 );
L518: ( len R7 ) = R2 by MATRIX_1:def 2;
reconsider D100 = C98 as (Subset of ( Seg R2 )) by L518 , L515 , FINSEQ_1:def 3;
thus L519:now
let C99 being set;
assume L520: C99 in ( rng D99 );
consider C100 being set such that L521: C100 in ( dom D99 ) and L522: ( D99 . C100 ) = C99 by L520 , FUNCT_1:def 3;
reconsider D101 = C100 as (Element of ( TOP-REAL R2 )) by L521;
consider C101 being (Linear_Combination of ( lines R7 )) such that L523: ( Sum C101 ) = C99 and L524: (for B71 being Nat holds (B71 in D100 implies ( C101 . ( Line (R7 , B71) ) ) = ( Sum ( Seq ( D101 | ( R7 " { ( Line (R7 , B71) ) } ) ) ) ))) by L516 , L517 , L522 , L278;
L525: ( Sum C101 ) in ( Lin ( lines R7 ) ) by VECTSP_7:7;
thus L526: C99 in ( [#] ( Lin ( lines R7 ) ) ) by L525 , L523 , STRUCT_0:def 5;
end;
let C102 being set;
assume L527: C102 in ( [#] ( Lin ( lines R7 ) ) );
L528: C102 in ( Lin ( lines R7 ) ) by L527 , STRUCT_0:def 5;
consider C103 being (Linear_Combination of ( lines R7 )) such that L529: C102 = ( Sum C103 ) by L528 , VECTSP_7:7;
defpred S4[ set , set ] means (($1 in D100 implies $2 = ( C103 . ( R7 . $1 ) )) & ((not $1 in D100) implies $2 = ( 0 )));
L530: (for B72 being Nat holds (B72 in ( Seg R2 ) implies (ex B73 being set st S4[ B72 , B73 ])))
proof
let C104 being Nat;
assume that
L531: C104 in ( Seg R2 );
L532: (C104 in D100 or (not C104 in D100));
thus L533: thesis by L532;
end;
consider C105 being FinSequence such that L534: (( dom C105 ) = ( Seg R2 ) & (for B74 being Nat holds (B74 in ( Seg R2 ) implies S4[ B74 , ( C105 . B74 ) ]))) from FINSEQ_1:sch 1(L530);
L535: ( dom R7 ) = ( Seg R2 ) by L518 , FINSEQ_1:def 3;
L536: ( rng C105 ) c= ( REAL )
proof
let C106 being set;
assume L537: C106 in ( rng C105 );
consider C107 being set such that L538: C107 in ( dom C105 ) and L539: ( C105 . C107 ) = C106 by L537 , FUNCT_1:def 3;
reconsider D102 = C107 as Nat by L538;
L540: S4[ D102 , ( C105 . D102 ) ] by L534 , L538;
L541: ( R7 . D102 ) = ( Line (R7 , D102) ) by L535 , L534 , L538 , MATRIX_2:16;
L542: ( R7 . D102 ) in ( lines R7 ) by L541 , L534 , L538 , MATRIX13:103;
reconsider D103 = ( R7 . D102 ) as (Element of D98) by L542;
per cases ;
suppose L543: (not D102 in D100);

L544: ( C105 . D102 ) = ( 0 ) by L543 , L534 , L538;
thus L545: thesis by L544 , L539;
end;
suppose L546: D102 in D100;

thus L547: thesis by L539 , L540 , XREAL_0:def 1;
end;
end;
reconsider D104 = C105 as (FinSequence of ( REAL )) by L536 , FINSEQ_1:def 4;
L549: ( len D104 ) = R2 by L518 , L534 , FINSEQ_1:def 3;
L550: D104 is R2 -element by L549 , CARD_1:def 7;
consider C108 being (Linear_Combination of ( lines R7 )) such that L551: ( Sum C108 ) = ( D99 . D104 ) and L552: (for B75 being Nat holds (B75 in D100 implies ( C108 . ( Line (R7 , B75) ) ) = ( Sum ( Seq ( D104 | ( R7 " { ( Line (R7 , B75) ) } ) ) ) ))) by L550 , L516 , L517 , L278;
L553:
now
let C109 being (Element of D98);
per cases ;
suppose L554: C109 in ( lines R7 );

consider C110 being set such that L555: C110 in ( dom ( R7 | D100 ) ) and L556: ( ( R7 | D100 ) . C110 ) = C109 by L554 , L516 , FUNCT_1:def 3;
L557: ( R7 . C110 ) = C109 by L555 , L556 , FUNCT_1:47;
set D105 = ( dom ( D104 | ( R7 " { C109 } ) ) );
L558: ( Seq ( D104 | ( R7 " { C109 } ) ) ) = ( @ ( @ ( Seq ( D104 | ( R7 " { C109 } ) ) ) ) );
reconsider D106 = ( Seq ( D104 | ( R7 " { C109 } ) ) ) as (FinSequence of ( REAL )) by L558;
L559: ( rng ( Sgm D105 ) ) = D105 by FINSEQ_1:50;
L560: ( dom D106 ) = ( dom ( Sgm D105 ) ) by L559 , RELAT_1:27;
L561: C110 in ( dom R7 ) by L555 , RELAT_1:57;
L562: C110 in D100 by L555;
reconsider D107 = C110 as Nat by L555;
L563: ( R7 . D107 ) = ( Line (R7 , D107) ) by L561 , MATRIX_2:16;
L564: ( C108 . C109 ) = ( Sum ( Seq ( D104 | ( R7 " { C109 } ) ) ) ) by L563 , L552 , L562 , L557;
L565: C109 in { C109 } by TARSKI:def 1;
L566: D107 in ( R7 " { C109 } ) by L565 , L561 , L557 , FUNCT_1:def 7;
L567: D107 in D105 by L566 , L534 , L562 , RELAT_1:57;
consider C111 being set such that L568: C111 in ( dom ( Sgm D105 ) ) and L569: ( ( Sgm D105 ) . C111 ) = D107 by L567 , L559 , FUNCT_1:def 3;
reconsider D108 = C111 as (Element of ( NAT )) by L568;
L570: (( D106 . D108 ) = ( ( D104 | ( R7 " { C109 } ) ) . D107 ) & D107 in D105) by L560 , L568 , L569 , FUNCT_1:11 , FUNCT_1:12;
L571: ( D106 . D108 ) = ( D104 . D107 ) by L570 , FUNCT_1:47;
L572: D105 c= ( dom D104 ) by RELAT_1:60;
L573: ( Sgm D105 ) is  one-to-one by L572 , L534 , FINSEQ_3:92;
L574:
now
let C112 being (Element of ( NAT ));
assume that
L575: C112 in ( dom D106 )
and
L576: C112 <> D108;
L577: ( ( Sgm D105 ) . C112 ) in D105 by L559 , L560 , L575 , FUNCT_1:def 3;
L578: ( ( Sgm D105 ) . C112 ) in ( R7 " { C109 } ) by L577 , RELAT_1:57;
L579: ( R7 . ( ( Sgm D105 ) . C112 ) ) in { C109 } by L578 , FUNCT_1:def 7;
L580: ( R7 . ( ( Sgm D105 ) . C112 ) ) = C109 by L579 , TARSKI:def 1;
L581: (not ( ( Sgm D105 ) . C112 ) in D100)
proof
assume L582: ( ( Sgm D105 ) . C112 ) in D100;
L583: ( ( Sgm D105 ) . C112 ) in ( dom ( R7 | D100 ) ) by L582 , L535 , RELAT_1:57;
L584: C109 = ( ( R7 | D100 ) . ( ( Sgm D105 ) . C112 ) ) by L583 , L580 , FUNCT_1:47;
L585: D107 = ( ( Sgm D105 ) . C112 ) by L584 , L517 , L555 , L556 , L583 , FUNCT_1:def 4;
thus L586: contradiction by L585 , L560 , L573 , L568 , L569 , L575 , L576 , FUNCT_1:def 4;
end;
L587: ( D106 . C112 ) = ( ( D104 | ( R7 " { C109 } ) ) . ( ( Sgm D105 ) . C112 ) ) by L575 , FUNCT_1:12;
L588: ( D106 . C112 ) = ( D104 . ( ( Sgm D105 ) . C112 ) ) by L587 , L577 , FUNCT_1:47;
L589: ( ( Sgm D105 ) . C112 ) in ( dom D104 ) by L577 , RELAT_1:57;
thus L590: ( D106 . C112 ) = ( 0 ) by L589 , L534 , L588 , L581;
end;
L591: D106 has_onlyone_value_in D108 by L574 , L560 , L568 , ENTROPY1:def 2;
L592: ( D104 . D107 ) = ( C103 . C109 ) by L534 , L562 , L557;
thus L593: ( C103 . C109 ) = ( C108 . C109 ) by L592 , L564 , L571 , L591 , ENTROPY1:13;
end;
suppose L594: (not C109 in ( lines R7 ));

L595: ( Carrier C103 ) c= ( lines R7 ) by VECTSP_6:def 4;
L596: (not C109 in ( Carrier C103 )) by L595 , L594;
L597: ( C103 . C109 ) = ( 0. ( F_Real ) ) by L596 , VECTSP_6:2;
L598: ( Carrier C108 ) c= ( lines R7 ) by VECTSP_6:def 4;
L599: (not C109 in ( Carrier C108 )) by L598 , L594;
thus L600: ( C103 . C109 ) = ( C108 . C109 ) by L599 , L597 , VECTSP_6:2;
end;
end;
L602: ( Sum C108 ) = ( Sum C103 ) by L553 , VECTSP_6:def 7;
L603: (( dom D99 ) = ( [#] ( TOP-REAL R2 ) ) & D104 is (Point of ( TOP-REAL R2 ))) by L550 , L5 , FUNCT_2:def 1;
thus L604: thesis by L603 , L529 , L551 , L602 , FUNCT_1:def 3;
end;
theorem
L605: (for R2 being Nat holds (for B76 being  one-to-one (FinSequence of ( TOP-REAL R2 )) holds (( rng B76 ) is  linearly-independent implies (ex B77 being (Matrix of R2 , ( F_Real )) st (B77 is  invertible & ( B77 | ( len B76 ) ) = B76)))))
proof
let R2 being Nat;
let C113 being  one-to-one (FinSequence of ( TOP-REAL R2 ));
assume that
L606: ( rng C113 ) is  linearly-independent;
reconsider D109 = C113 as (FinSequence of ( R2 -VectSp_over ( F_Real ) )) by L1;
set D110 = ( FinS2MX D109 );
L607: ( lines D110 ) is  linearly-independent by L606 , L101;
L608: ( the_rank_of D110 ) = ( len C113 ) by L607 , MATRIX13:121;
consider C114 being (Matrix of ( R2 -' ( len C113 ) ) , R2 , ( F_Real )) such that L609: ( the_rank_of ( D110 ^ C114 ) ) = R2 by L608 , MATRTOP1:16;
L610: ( len C113 ) <= ( width D110 ) by L608 , MATRIX13:74;
L611: ( len C113 ) <= R2 by L610 , MATRIX_1:23;
L612: ( R2 - ( len C113 ) ) = ( R2 -' ( len C113 ) ) by L611 , XREAL_1:233;
reconsider D111 = ( D110 ^ C114 ) as (Matrix of R2 , ( F_Real )) by L612;
take D111;
L613: ( Det D111 ) <> ( 0. ( F_Real ) ) by L609 , MATRIX13:83;
thus L614: D111 is  invertible by L613 , LAPLACE:34;
thus L615: C113 = ( D111 | ( dom C113 ) ) by FINSEQ_1:21
.= ( D111 | ( len C113 ) ) by FINSEQ_1:def 3;
end;
theorem
L616: (for R2 being Nat holds (for R4 being Nat holds (for R6 being R2 -element  real-valued FinSequence holds (for B78 being (OrdBasis of ( R2 -VectSp_over ( F_Real ) )) holds (B78 = ( MX2FinS ( 1. (( F_Real ) , R2) ) ) implies (R6 in ( Lin ( rng ( B78 | R4 ) ) ) iff R6 = ( ( R6 | R4 ) ^ ( ( R2 -' R4 ) |-> ( 0 ) ) )))))))
proof
let R2 being Nat;
let R4 being Nat;
let R6 being R2 -element  real-valued FinSequence;
set D112 = ( R2 -VectSp_over ( F_Real ) );
set D113 = ( ( R2 -' R4 ) |-> ( 0 ) );
let C115 being (OrdBasis of ( R2 -VectSp_over ( F_Real ) ));
assume that
L617: C115 = ( MX2FinS ( 1. (( F_Real ) , R2) ) );
L618: ( len C115 ) = R2 by L617 , MATRIX_1:def 2;
L619: R6 is (Point of ( TOP-REAL R2 )) by L5;
L620: R6 is (Point of D112) by L619 , L1;
L621: ( rng C115 ) is (Basis of D112) by MATRLIN:def 2;
L622: ( rng C115 ) is  linearly-independent by L621 , VECTSP_7:def 3;
L623: ( Lin ( rng C115 ) ) = ( the VectSpStr of D112 ) by L621 , VECTSP_7:def 3;
L624: R6 in ( Lin ( rng C115 ) ) by L623 , L620 , STRUCT_0:def 5;
L625: C115 is  one-to-one by MATRLIN:def 2;
reconsider D114 = R6 as (Point of D112) by L619 , L1;
L626: ( len R6 ) = R2 by CARD_1:def 7;
per cases ;
suppose L627: R4 >= R2;

L628: ( R2 - R4 ) <= ( 0 ) by L627 , XREAL_1:47;
L629: ( R2 -' R4 ) = ( 0 ) by L628 , XREAL_0:def 2;
L630: D113 = ( {} ) by L629;
L631: ( R6 | R4 ) = R6 by L626 , L627 , FINSEQ_1:58;
thus L632: thesis by L631 , L618 , L624 , L627 , L630 , FINSEQ_1:34 , FINSEQ_1:58;
end;
suppose L633: R4 < R2;

L634: ( len ( R6 | R4 ) ) = R4 by L633 , L626 , FINSEQ_1:59;
L635: ( len D113 ) = ( R2 -' R4 ) by CARD_1:def 7;
consider C116 being (Linear_Combination of D112) such that L636: D114 = ( Sum C116 ) and L637: ( Carrier C116 ) c= ( rng C115 ) and L638: (for R4 being Nat holds ((1 <= R4 & R4 <= ( len ( D114 |-- C115 ) )) implies ( ( D114 |-- C115 ) /. R4 ) = ( C116 . ( C115 /. R4 ) ))) by MATRLIN:def 7;
reconsider D115 = C116 as (Linear_Combination of ( rng C115 )) by L637 , VECTSP_6:def 4;
L639: ( D114 |-- C115 ) = D114 by L617 , L618 , MATRLIN2:46;
L640: ( R2 -' R4 ) = ( R2 - R4 ) by L633 , XREAL_1:233;
L641: ( len ( ( R6 | R4 ) ^ D113 ) ) = ( R4 + ( R2 - R4 ) ) by L640 , L634 , L635 , FINSEQ_1:22;
L642: ( dom ( ( R6 | R4 ) ^ D113 ) ) = ( dom R6 ) by L641 , L626 , FINSEQ_3:29;
thus L643:now
assume L644: R6 in ( Lin ( rng ( C115 | R4 ) ) );
consider C117 being (Linear_Combination of ( rng ( C115 | R4 ) )) such that L645: ( Sum C117 ) = R6 by L644 , VECTSP_7:7;
reconsider D116 = C117 as (Linear_Combination of ( rng C115 )) by RELAT_1:70 , VECTSP_6:4;
L646: ( D115 - D116 ) is (Linear_Combination of ( rng C115 )) by VECTSP_6:42;
L647: ( Sum ( D115 - D116 ) ) = ( ( Sum D115 ) - ( Sum D116 ) ) by VECTSP_6:47
.= ( 0. D112 ) by L636 , L645 , VECTSP_1:19;
L648: ( Carrier ( D115 - D116 ) ) = ( {} ) by L647 , L622 , L646 , VECTSP_7:def 1;
L649: ( ZeroLC D112 ) = ( D115 - D116 ) by L648 , VECTSP_6:def 3
.= ( D115 + ( - D116 ) ) by VECTSP_6:def 11
.= ( ( - D116 ) + D115 ) by VECTSP_6:25;
reconsider D117 = ( - ( 1. ( F_Real ) ) ) as (Element of ( F_Real ));
L650: ( Carrier C117 ) c= ( rng ( C115 | R4 ) ) by VECTSP_6:def 4;
L651: D116 = ( - ( - D116 ) );
L652: D115 = D116 by L651 , L649 , VECTSP_6:37;
L653:
now
let C118 being Nat;
assume L654: C118 in ( dom R6 );
per cases  by L634 , L642 , L654 , FINSEQ_1:25;
suppose L655: C118 in ( dom ( R6 | R4 ) );

L656: ( ( R6 | R4 ) . C118 ) = ( R6 . C118 ) by L655 , FUNCT_1:47;
thus L657: ( ( ( R6 | R4 ) ^ D113 ) . C118 ) = ( R6 . C118 ) by L656 , L655 , FINSEQ_1:def 7;
end;
suppose L658: (ex B79 being Nat st (B79 in ( dom D113 ) & C118 = ( R4 + B79 )));

L659: C118 in ( dom C115 ) by L626 , L618 , L654 , FINSEQ_3:29;
L660: ( C115 /. C118 ) = ( C115 . C118 ) by L659 , PARTFUN1:def 6;
consider C119 being Nat such that L661: C119 in ( dom D113 ) and L662: C118 = ( R4 + C119 ) by L658;
L663: 1 <= C119 by L661 , FINSEQ_3:25;
L664: (not ( C115 . C118 ) in ( rng ( C115 | R4 ) ))
proof
assume L665: ( C115 . C118 ) in ( rng ( C115 | R4 ) );
consider C120 being set such that L666: C120 in ( dom ( C115 | R4 ) ) and L667: ( ( C115 | R4 ) . C120 ) = ( C115 . C118 ) by L665 , FUNCT_1:def 3;
L668: (( C115 . C120 ) = ( C115 . C118 ) & C120 in ( dom C115 )) by L666 , L667 , FUNCT_1:47 , RELAT_1:57;
L669: C118 = C120 by L668 , L625 , L659 , FUNCT_1:def 4;
L670: C120 in ( Seg R4 ) by L666 , RELAT_1:57;
L671: C118 <= R4 by L670 , L669 , FINSEQ_1:1;
L672: C118 >= ( R4 + 1 ) by L662 , L663 , XREAL_1:6;
thus L673: contradiction by L672 , L671 , NAT_1:13;
end;
L674: (not ( C115 . C118 ) in ( Carrier C117 )) by L664 , L650;
L675: (1 <= C118 & C118 <= R2) by L626 , L654 , FINSEQ_3:25;
L676: ( ( D114 |-- C115 ) /. C118 ) = ( D115 . ( C115 /. C118 ) ) by L675 , L626 , L639 , L638;
L677: ( R6 . C118 ) = ( ( D114 |-- C115 ) /. C118 ) by L639 , L654 , PARTFUN1:def 6;
thus L678: ( R6 . C118 ) = ( 0. ( F_Real ) ) by L677 , L652 , L676 , L660 , L674 , VECTSP_6:2
.= ( D113 . C119 )
.= ( ( ( R6 | R4 ) ^ D113 ) . C118 ) by L634 , L661 , L662 , FINSEQ_1:def 7;
end;
end;
thus L680: ( ( R6 | R4 ) ^ ( ( R2 -' R4 ) |-> ( 0 ) ) ) = R6 by L653 , L642 , FINSEQ_1:13;
end;
assume L681: ( ( R6 | R4 ) ^ D113 ) = R6;
L682: ( Carrier D115 ) c= ( rng ( C115 | R4 ) )
proof
let C121 being set;
assume L683: C121 in ( Carrier D115 );
L684: ( Carrier D115 ) c= ( rng C115 ) by VECTSP_6:def 4;
consider C122 being set such that L685: C122 in ( dom C115 ) and L686: ( C115 . C122 ) = C121 by L684 , L683 , FUNCT_1:def 3;
reconsider D118 = C122 as (Element of ( NAT )) by L685;
L687: ( C115 /. D118 ) = ( C115 . D118 ) by L685 , PARTFUN1:def 6;
L688: ( dom C115 ) = ( dom R6 ) by L626 , L618 , FINSEQ_3:29;
assume L689: (not C121 in ( rng ( C115 | R4 ) ));
L690: (not D118 in ( Seg R4 ))
proof
assume L691: D118 in ( Seg R4 );
L692: D118 in ( dom ( C115 | R4 ) ) by L691 , L685 , RELAT_1:57;
L693: ( ( C115 | R4 ) . D118 ) = ( C115 . D118 ) by L692 , FUNCT_1:47;
thus L694: contradiction by L693 , L686 , L689 , L692 , FUNCT_1:def 3;
end;
L695: (not D118 in ( dom ( R6 | R4 ) )) by L690 , L634 , FINSEQ_1:def 3;
consider C123 being Nat such that L696: C123 in ( dom D113 ) and L697: D118 = ( R4 + C123 ) by L695 , L634 , L642 , L685 , L688 , FINSEQ_1:25;
L698: ( D113 . C123 ) = ( 0 );
L699: (1 <= D118 & D118 <= R2) by L618 , L685 , FINSEQ_3:25;
L700: ( ( D114 |-- C115 ) /. D118 ) = ( ( D114 |-- C115 ) . D118 ) by L639 , L685 , L688 , PARTFUN1:def 6;
L701: ( D115 . ( C115 /. D118 ) ) = ( R6 . D118 ) by L700 , L626 , L639 , L638 , L699
.= ( 0. ( F_Real ) ) by L634 , L681 , L696 , L697 , L698 , FINSEQ_1:def 7;
thus L702: contradiction by L701 , L683 , L686 , L687 , VECTSP_6:2;
end;
L703: D115 is (Linear_Combination of ( rng ( C115 | R4 ) )) by L682 , VECTSP_6:def 4;
thus L704: thesis by L703 , L636 , VECTSP_7:7;
end;
end;
theorem
L706: (for R2 being Nat holds (for B80 being  one-to-one (FinSequence of ( TOP-REAL R2 )) holds (( rng B80 ) is  linearly-independent implies (for B81 being (OrdBasis of ( R2 -VectSp_over ( F_Real ) )) holds (B81 = ( MX2FinS ( 1. (( F_Real ) , R2) ) ) implies (for B82 being (Matrix of R2 , ( F_Real )) holds ((B82 is  invertible & ( B82 | ( len B80 ) ) = B80) implies ( ( Mx2Tran B82 ) .: ( [#] ( Lin ( rng ( B81 | ( len B80 ) ) ) ) ) ) = ( [#] ( Lin ( rng B80 ) ) ))))))))
proof
let R2 being Nat;
let C124 being  one-to-one (FinSequence of ( TOP-REAL R2 ));
assume that
L707: ( rng C124 ) is  linearly-independent;
reconsider D119 = C124 as (FinSequence of ( R2 -VectSp_over ( F_Real ) )) by L1;
set D120 = ( FinS2MX D119 );
set D121 = ( R2 -' ( len C124 ) );
set D122 = ( len C124 );
L708: ( lines D120 ) is  linearly-independent by L707 , L101;
L709: ( the_rank_of D120 ) = ( len C124 ) by L708 , MATRIX13:121;
L710: D122 <= ( width D120 ) by L709 , MATRIX13:74;
L711: D122 <= R2 by L710 , MATRIX_1:23;
L712: ( R2 - D122 ) = D121 by L711 , XREAL_1:233;
set D123 = ( R2 -VectSp_over ( F_Real ) );
let C125 being (OrdBasis of ( R2 -VectSp_over ( F_Real ) ));
assume that
L713: C125 = ( MX2FinS ( 1. (( F_Real ) , R2) ) );
let C126 being (Matrix of R2 , ( F_Real ));
assume that
L714: C126 is  invertible
and
L715: ( C126 | ( len C124 ) ) = C124;
consider C127 being FinSequence such that L716: C126 = ( C124 ^ C127 ) by L715 , FINSEQ_1:80;
L717: C126 = ( MX2FinS C126 );
reconsider D124 = C127 as (FinSequence of ( R2 -VectSp_over ( F_Real ) )) by L717 , L716 , FINSEQ_1:36;
L718: ( len C126 ) = ( ( len C124 ) + ( len D124 ) ) by L716 , FINSEQ_1:22;
set D125 = ( FinS2MX D124 );
set D126 = ( Mx2Tran C126 );
L719: ( len C126 ) = R2 by MATRIX_1:def 2;
L720: ( dom D126 ) = ( [#] ( TOP-REAL R2 ) ) by FUNCT_2:52;
L721: ( dom ( Mx2Tran D120 ) ) = ( [#] ( TOP-REAL D122 ) ) by FUNCT_2:def 1;
L722: (the carrier of ( TOP-REAL R2 )) = ( REAL R2 ) by EUCLID:22
.= ( R2 -tuples_on ( REAL ) );
L723: ( rng ( Mx2Tran D120 ) ) = ( [#] ( Lin ( lines D120 ) ) ) by L514
.= ( [#] ( Lin ( rng C124 ) ) ) by L82;
L724: ( R2 |-> ( 0 ) ) = ( 0* R2 )
.= ( 0. ( TOP-REAL R2 ) ) by EUCLID:70;
L725: ( D121 |-> ( 0 ) ) = ( 0* D121 )
.= ( 0. ( TOP-REAL D121 ) ) by EUCLID:70;
L726: ( ( Mx2Tran D125 ) . ( D121 |-> ( 0 ) ) ) = ( 0. ( TOP-REAL R2 ) ) by L725 , L712 , L719 , L718 , MATRTOP1:29;
thus L727: ( D126 .: ( [#] ( Lin ( rng ( C125 | D122 ) ) ) ) ) c= ( [#] ( Lin ( rng C124 ) ) )
proof
let C128 being set;
assume L728: C128 in ( D126 .: ( [#] ( Lin ( rng ( C125 | D122 ) ) ) ) );
consider C129 being set such that L729: C129 in ( dom D126 ) and L730: C129 in ( [#] ( Lin ( rng ( C125 | D122 ) ) ) ) and L731: ( D126 . C129 ) = C128 by L728 , FUNCT_1:def 6;
reconsider D127 = C129 as (Element of ( TOP-REAL R2 )) by L729;
L732: ( len D127 ) = R2 by CARD_1:def 7;
L733: ( len ( D127 | D122 ) ) = D122 by L732 , L711 , FINSEQ_1:59;
L734: ( D127 | D122 ) is D122 -element by L733 , CARD_1:def 7;
L735: ( D127 | D122 ) is (Element of ( TOP-REAL D122 )) by L734 , L5;
L736: ( ( Mx2Tran D120 ) . ( D127 | D122 ) ) is (Element of ( R2 -tuples_on ( REAL ) )) by L722 , L734 , L5;
L737: D127 in ( Lin ( rng ( C125 | D122 ) ) ) by L730 , STRUCT_0:def 5;
L738: D127 = ( ( D127 | D122 ) ^ ( ( R2 -' D122 ) |-> ( 0 ) ) ) by L737 , L713 , L616;
L739: C128 = ( ( ( Mx2Tran D120 ) . ( D127 | D122 ) ) + ( ( Mx2Tran D125 ) . ( D121 |-> ( 0 ) ) ) ) by L738 , L712 , L719 , L716 , L718 , L731 , L734 , MATRTOP1:36
.= ( ( Mx2Tran D120 ) . ( D127 | D122 ) ) by L724 , L726 , L736 , RVSUM_1:16;
thus L740: thesis by L739 , L723 , L721 , L735 , FUNCT_1:def 3;
end;

let C130 being set;
assume L741: C130 in ( [#] ( Lin ( rng C124 ) ) );
consider C131 being set such that L742: C131 in ( dom ( Mx2Tran D120 ) ) and L743: ( ( Mx2Tran D120 ) . C131 ) = C130 by L741 , L723 , FUNCT_1:def 3;
reconsider D128 = C131 as (Element of ( TOP-REAL D122 )) by L742;
L744: ( ( Mx2Tran D120 ) . D128 ) is (Element of ( TOP-REAL R2 )) by L5;
L745: C130 = ( ( ( Mx2Tran D120 ) . D128 ) + ( 0. ( TOP-REAL R2 ) ) ) by L744 , L722 , L724 , L743 , RVSUM_1:16
.= ( ( ( Mx2Tran D120 ) . D128 ) + ( ( Mx2Tran D125 ) . ( D121 |-> ( 0 ) ) ) ) by L712 , L719 , L718 , L725 , MATRTOP1:29
.= ( D126 . ( D128 ^ ( D121 |-> ( 0 ) ) ) ) by L716 , L712 , L719 , L718 , MATRTOP1:36;
set D129 = ( D128 ^ ( D121 |-> ( 0 ) ) );
L746: ( len D128 ) = D122 by CARD_1:def 7;
L747: ( dom D128 ) = ( Seg D122 ) by L746 , FINSEQ_1:def 3;
L748: D129 = ( ( D129 | D122 ) ^ ( D121 |-> ( 0 ) ) ) by L747 , FINSEQ_1:21;
L749: D129 in ( Lin ( rng ( C125 | D122 ) ) ) by L748 , L713 , L712 , L616;
L750: D129 in ( [#] ( Lin ( rng ( C125 | D122 ) ) ) ) by L749 , STRUCT_0:def 5;
L751: D129 is (Element of ( TOP-REAL R2 )) by L712 , L5;
thus L752: thesis by L751 , L720 , L745 , L750 , FUNCT_1:def 6;
end;
theorem
L753: (for R2 being Nat holds (for B83 , B84 being  linearly-independent (Subset of ( TOP-REAL R2 )) holds (( card B83 ) = ( card B84 ) implies (ex B85 being (Matrix of R2 , ( F_Real )) st (B85 is  invertible & ( ( Mx2Tran B85 ) .: ( [#] ( Lin B83 ) ) ) = ( [#] ( Lin B84 ) ))))))
proof
let R2 being Nat;
set D130 = ( TOP-REAL R2 );
let C132 , C133 being  linearly-independent (Subset of D130);
assume that
L754: ( card C132 ) = ( card C133 );
reconsider D131 = ( MX2FinS ( 1. (( F_Real ) , R2) ) ) as (OrdBasis of ( R2 -VectSp_over ( F_Real ) )) by MATRLIN2:45;
set D132 = ( R2 -VectSp_over ( F_Real ) );
L755: C132 is  linearly-independent  linearly-independent  linearly-independent  linearly-independent (Subset of D132) by L1 , L101;
L756: C132 is  finite by L755 , VECTSP_9:21;
consider C134 being FinSequence such that L757: ( rng C134 ) = C132 and L758: C134 is  one-to-one by L756 , FINSEQ_4:58;
L759: ( len C134 ) = ( card C132 ) by L757 , L758 , PRE_POLY:19;
L760: C133 is  linearly-independent  linearly-independent  linearly-independent  linearly-independent (Subset of D132) by L1 , L101;
L761: C133 is  finite by L760 , VECTSP_9:21;
consider C135 being FinSequence such that L762: ( rng C135 ) = C133 and L763: C135 is  one-to-one by L761 , FINSEQ_4:58;
L764: ( len C135 ) = ( card C133 ) by L762 , L763 , PRE_POLY:19;
reconsider D133 = C134 , D134 = C135 as (FinSequence of D130) by L757 , L762 , FINSEQ_1:def 4;
consider C136 being (Matrix of R2 , ( F_Real )) such that L765: C136 is  invertible and L766: ( C136 | ( len D133 ) ) = D133 by L757 , L758 , L605;
L767: ( [#] ( Lin ( rng ( D131 | ( len D133 ) ) ) ) ) c= ( [#] D132 ) by VECTSP_4:def 2;
set D135 = ( Mx2Tran C136 );
L768: ( Det C136 ) <> ( 0. ( F_Real ) ) by L765 , LAPLACE:34;
L769: D135 is  one-to-one by L768 , MATRTOP1:40;
L770: ( rng ( D135 " ) ) = ( dom D135 ) by L769 , FUNCT_1:33;
L771: (( [#] ( TOP-REAL R2 ) ) = ( [#] D132 ) & ( dom D135 ) = ( [#] D130 )) by L1 , FUNCT_2:52;
L772: ( ( D135 " ) " ( [#] ( Lin ( rng ( D131 | ( len D133 ) ) ) ) ) ) = ( D135 .: ( [#] ( Lin ( rng ( D131 | ( len D133 ) ) ) ) ) ) by L769 , FUNCT_1:84
.= ( [#] ( Lin C132 ) ) by L757 , L758 , L765 , L766 , L706;
L773: ( ( D135 " ) .: ( [#] ( Lin C132 ) ) ) = ( [#] ( Lin ( rng ( D131 | ( len D134 ) ) ) ) ) by L772 , L754 , L759 , L764 , L771 , L770 , L767 , FUNCT_1:77;
consider C137 being (Matrix of R2 , ( F_Real )) such that L774: C137 is  invertible and L775: ( C137 | ( len D134 ) ) = D134 by L762 , L763 , L605;
set D136 = ( Mx2Tran C137 );
L776: (R2 = ( 0 ) implies R2 = ( 0 ));
reconsider D137 = C137 as (Matrix of ( width ( C136 ~ ) ) , R2 , ( F_Real )) by L776 , MATRIX13:1;
L777: ( width C137 ) = R2 by L776 , MATRIX13:1;
reconsider D138 = ( ( C136 ~ ) * D137 ) as (Matrix of R2 , ( F_Real )) by L777 , L776 , MATRIX13:1;
take D138;
L778: ( C136 ~ ) is  invertible by L765 , MATRIX_6:16;
thus L779: D138 is  invertible by L778 , L774 , MATRIX_6:45;
L780: ( D136 * ( D135 " ) ) = ( ( Mx2Tran D137 ) * ( D135 " ) ) by L776 , MATRIX13:1
.= ( ( Mx2Tran D137 ) * ( Mx2Tran ( C136 ~ ) ) ) by L768 , MATRTOP1:43
.= ( Mx2Tran ( ( C136 ~ ) * D137 ) ) by L776 , MATRTOP1:32
.= ( Mx2Tran D138 ) by L776 , L777 , MATRIX13:1;
thus L781: ( ( Mx2Tran D138 ) .: ( [#] ( Lin C132 ) ) ) = ( D136 .: ( [#] ( Lin ( rng ( D131 | ( len D134 ) ) ) ) ) ) by L780 , L773 , RELAT_1:126
.= ( [#] ( Lin C133 ) ) by L762 , L763 , L774 , L775 , L706;
end;
begin
theorem
L782: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B86 being  linearly-independent (Subset of ( TOP-REAL R2 )) holds (( the_rank_of R7 ) = R2 implies ( ( Mx2Tran R7 ) .: B86 ) is  linearly-independent)))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
let C138 being  linearly-independent (Subset of ( TOP-REAL R2 ));
assume that
L783: ( the_rank_of R7 ) = R2;
set D139 = ( R2 -VectSp_over ( F_Real ) );
set D140 = ( R3 -VectSp_over ( F_Real ) );
reconsider D141 = ( MX2FinS ( 1. (( F_Real ) , R2) ) ) as (OrdBasis of D139) by MATRLIN2:45;
reconsider D142 = ( MX2FinS ( 1. (( F_Real ) , R3) ) ) as (OrdBasis of D140) by MATRLIN2:45;
L784: ( len D141 ) = R2 by MATRTOP1:19;
reconsider D143 = R7 as (Matrix of ( len D141 ) , ( len D142 ) , ( F_Real )) by L784 , MATRTOP1:19;
set D144 = ( Mx2Tran (D143 , D141 , D142) );
L785: ( Mx2Tran R7 ) = D144 by MATRTOP1:20;
reconsider D145 = C138 as (Subset of D139) by L1;
L786: D145 is  linearly-independent by L101;
L787: ( D144 .: D145 ) is  linearly-independent
proof
assume L788: ( D144 .: D145 ) is non  linearly-independent;
consider C139 being (Linear_Combination of ( D144 .: D145 )) such that L789: ( Carrier C139 ) <> ( {} ) and L790: ( Sum C139 ) = ( 0. D140 ) by L788 , RANKNULL:41;
L791: D144 is  one-to-one by L783 , L785 , MATRTOP1:39;
L792: ( ker D144 ) = ( (0). D139 ) by L791 , RANKNULL:15;
L793: ( D144 | D145 ) is  one-to-one by L791 , FUNCT_1:52;
L794: ( D144 @ ( D144 # C139 ) ) = C139 by L793 , RANKNULL:43;
L795: ( D144 | ( Carrier ( D144 # C139 ) ) ) is  one-to-one by L791 , FUNCT_1:52;
L796: ( D144 .: ( Carrier ( D144 # C139 ) ) ) = ( Carrier C139 ) by L795 , L794 , RANKNULL:39;
L797: ( Carrier ( D144 # C139 ) ) <> ( {} ) by L796 , L789;
L798: ( D144 . ( Sum ( D144 # C139 ) ) ) = ( 0. D140 ) by L790 , L793 , L794 , L212;
L799: ( Sum ( D144 # C139 ) ) in ( ker D144 ) by L798 , RANKNULL:10;
L800: ( Sum ( D144 # C139 ) ) = ( 0. D139 ) by L799 , L792 , VECTSP_4:35;
thus L801: contradiction by L800 , L786 , L797 , VECTSP_7:def 1;
end;
thus L802: thesis by L787 , L785 , L101;
end;
theorem
L803: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B87 being  affinely-independent (Subset of ( TOP-REAL R2 )) holds (( the_rank_of R7 ) = R2 implies ( ( Mx2Tran R7 ) .: B87 ) is  affinely-independent)))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
set D146 = ( Mx2Tran R7 );
set D147 = ( TOP-REAL R2 );
set D148 = ( TOP-REAL R3 );
let C140 being  affinely-independent (Subset of D147);
assume that
L804: ( the_rank_of R7 ) = R2;
per cases ;
suppose L805: C140 is  empty;

L806: ( D146 .: C140 ) is  empty by L805;
thus L807: thesis by L806;
end;
suppose L808: C140 is non  empty;

consider C141 being (Element of D147) such that L809: C141 in C140 and L810: ( ( ( - C141 ) + C140 ) \ { ( 0. D147 ) } ) is  linearly-independent by L808 , RLAFFIN1:def 4;
L811: ( dom D146 ) = ( [#] D147 ) by FUNCT_2:def 1;
L812: ( D146 . C141 ) in ( D146 .: C140 ) by L811 , L809 , FUNCT_1:def 6;
L813: ( D146 . ( 0. D147 ) ) = ( 0. D148 ) by MATRTOP1:29;
L814: { ( 0. D148 ) } = ( Im (D146 , ( 0. D147 )) ) by L813 , L811 , FUNCT_1:59
.= ( D146 .: { ( 0. D147 ) } ) by RELAT_1:def 16;
L815: ( - C141 ) = ( ( 0. D147 ) - C141 ) by RLVECT_1:14;
L816: ( D146 . ( - C141 ) ) = ( ( D146 . ( 0. D147 ) ) - ( D146 . C141 ) ) by L815 , MATRTOP1:28
.= ( ( 0. D148 ) - ( D146 . C141 ) ) by MATRTOP1:29
.= ( - ( D146 . C141 ) ) by RLVECT_1:14;
L817: D146 is  one-to-one by L804 , MATRTOP1:39;
L818: ( D146 .: ( ( ( - C141 ) + C140 ) \ { ( 0. D147 ) } ) ) = ( ( D146 .: ( ( - C141 ) + C140 ) ) \ ( D146 .: { ( 0. D147 ) } ) ) by L817 , FUNCT_1:64
.= ( ( ( - ( D146 . C141 ) ) + ( D146 .: C140 ) ) \ { ( 0. D148 ) } ) by L814 , L816 , MATRTOP1:30;
L819: ( D146 .: ( ( ( - C141 ) + C140 ) \ { ( 0. D147 ) } ) ) is  linearly-independent by L804 , L810 , L782;
thus L820: thesis by L819 , L812 , L818 , RLAFFIN1:def 4;
end;
end;
theorem
L822: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B88 being  affinely-independent (Subset of ( TOP-REAL R2 )) holds (( the_rank_of R7 ) = R2 implies (for B89 being (Element of ( TOP-REAL R2 )) holds (B89 in ( Affin B88 ) implies (( ( Mx2Tran R7 ) . B89 ) in ( Affin ( ( Mx2Tran R7 ) .: B88 ) ) & (for R6 being R2 -element  real-valued FinSequence holds ( ( B89 |-- B88 ) . R6 ) = ( ( ( ( Mx2Tran R7 ) . B89 ) |-- ( ( Mx2Tran R7 ) .: B88 ) ) . ( ( Mx2Tran R7 ) . R6 ) ))))))))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
reconsider D149 = ( 0 ) as (Element of ( NAT ));
set D150 = ( TOP-REAL R2 );
set D151 = ( TOP-REAL R3 );
let C142 being  affinely-independent (Subset of D150);
assume that
L823: ( the_rank_of R7 ) = R2;
set D152 = ( Mx2Tran R7 );
let C143 being (Element of D150);
assume that
L824: C143 in ( Affin C142 );
set D153 = ( C143 |-- C142 );
set D154 = ( Carrier D153 );
defpred S5[ set , set ] means (((not $1 in ( rng D152 )) implies $2 = ( 0 )) & ($1 in ( rng D152 ) implies (for R6 being R2 -element  real-valued FinSequence holds (( D152 . R6 ) = $1 implies $2 = ( D153 . R6 )))));
consider C144 being (FinSequence of (the carrier of D150)) such that L825: C144 is  one-to-one and L826: ( rng C144 ) = D154 and L827: ( Sum ( D153 (#) C144 ) ) = ( Sum D153 ) by RLVECT_2:def 8;
L828: ( Sum D153 ) = C143 by L824 , RLAFFIN1:def 7;
reconsider D155 = ( D152 * C144 ) as (FinSequence of D151);
L829: ( dom D152 ) = ( [#] D150 ) by FUNCT_2:def 1;
L830: ( rng C144 ) c= ( dom D152 ) by L829;
L831: ( len D155 ) = ( len C144 ) by L830 , FINSEQ_2:29;
L832: D152 is  one-to-one by L823 , MATRTOP1:39;
L833: (for B90 being set holds (B90 in (the carrier of D151) implies (ex B91 being set st (B91 in ( REAL ) & S5[ B90 , B91 ]))))
proof
let C145 being set;
assume that
L834: C145 in (the carrier of D151);
per cases ;
suppose L835: C145 in ( rng D152 );

consider C146 being set such that L836: C146 in ( dom D152 ) and L837: ( D152 . C146 ) = C145 by L835 , FUNCT_1:def 3;
reconsider D156 = C146 as (Element of D150) by L836;
take ( D153 . D156 );
thus L838: (( D153 . D156 ) in ( REAL ) & ((not C145 in ( rng D152 )) implies ( D153 . D156 ) = ( 0 ))) by L835;
assume L839: C145 in ( rng D152 );
let R6 being R2 -element  real-valued FinSequence;
assume L840: ( D152 . R6 ) = C145;
L841: R6 is (Element of D150) by L5;
thus L842: thesis by L841 , L829 , L832 , L837 , L840 , FUNCT_1:def 4;
end;
suppose L843: (not C145 in ( rng D152 ));

take D157 = ( 0 );
thus L844: thesis by L843;
end;
end;
consider C147 being (Function of (the carrier of D151) , ( REAL )) such that L846: (for B92 being set holds (B92 in (the carrier of D151) implies S5[ B92 , ( C147 . B92 ) ])) from FUNCT_2:sch 1(L833);
reconsider D158 = C147 as (Element of ( Funcs ((the carrier of D151) , ( REAL )) )) by FUNCT_2:8;
L847:
now
let C148 being (Element of D151);
assume L848: (not C148 in ( D152 .: D154 ));
assume L849: ( D158 . C148 ) <> ( 0 );
L850: C148 in ( rng D152 ) by L849 , L846;
consider C149 being set such that L851: C149 in ( dom D152 ) and L852: ( D152 . C149 ) = C148 by L850 , FUNCT_1:def 3;
reconsider D159 = C149 as (Element of D150) by L851;
L853: ( D153 . D159 ) = ( D158 . C148 ) by L846 , L849 , L852;
L854: D159 in D154 by L853 , L849 , RLVECT_2:19;
thus L855: contradiction by L854 , L848 , L851 , L852 , FUNCT_1:def 6;
end;
reconsider D160 = D158 as (Linear_Combination of D151) by L847 , RLVECT_2:def 3;
L856: ( D152 .: D154 ) c= ( Carrier D160 )
proof
let C150 being set;
assume L857: C150 in ( D152 .: D154 );
consider C151 being set such that L858: C151 in ( dom D152 ) and L859: C151 in D154 and L860: ( D152 . C151 ) = C150 by L857 , FUNCT_1:def 6;
reconsider D161 = C151 as (Element of D150) by L858;
L861: ( D153 . D161 ) <> ( 0 ) by L859 , RLVECT_2:19;
reconsider D162 = C150 as (Element of D151) by L857;
L862: S5[ D162 , ( D160 . D162 ) ] by L846;
L863: ( D160 . D162 ) = ( D153 . D161 ) by L862 , L858 , L860 , FUNCT_1:def 3;
thus L864: thesis by L863 , L861 , RLVECT_2:19;
end;
L865: ( Carrier D160 ) c= ( D152 .: D154 )
proof
let C152 being set;
assume L866: C152 in ( Carrier D160 );
reconsider D163 = C152 as (Element of D151) by L866;
L867: ( D160 . D163 ) <> ( 0 ) by L866 , RLVECT_2:19;
thus L868: thesis by L867 , L847;
end;
L869: ( Carrier D160 ) = ( D152 .: D154 ) by L865 , L856 , XBOOLE_0:def 10;
L870: D154 c= C142 by RLVECT_2:def 6;
L871: ( D152 .: D154 ) c= ( D152 .: C142 ) by L870 , RELAT_1:123;
reconsider D164 = D160 as (Linear_Combination of ( D152 .: C142 )) by L871 , L869 , RLVECT_2:def 6;
set D165 = ( D164 (#) D155 );
consider C153 being (Function of ( NAT ) , D151) such that L872: ( Sum D165 ) = ( C153 . ( len D165 ) ) and L873: ( C153 . ( 0 ) ) = ( 0. D151 ) and L874: (for B93 being (Element of ( NAT )) holds (for B94 being (Element of D151) holds ((B93 < ( len D165 ) & B94 = ( D165 . ( B93 + 1 ) )) implies ( C153 . ( B93 + 1 ) ) = ( ( C153 . B93 ) + B94 )))) by RLVECT_1:def 12;
L875: ( rng D155 ) = ( D152 .: D154 ) by L826 , RELAT_1:127;
L876: ( dom D153 ) = ( [#] D150 ) by FUNCT_2:def 1;
L877: ( len ( D153 * C144 ) ) = ( len C144 ) by L876 , L826 , FINSEQ_2:29;
set D166 = ( D153 (#) C144 );
consider C154 being (Function of ( NAT ) , D150) such that L878: ( Sum D166 ) = ( C154 . ( len D166 ) ) and L879: ( C154 . ( 0 ) ) = ( 0. D150 ) and L880: (for B95 being (Element of ( NAT )) holds (for B96 being (Element of D150) holds ((B95 < ( len D166 ) & B96 = ( D166 . ( B95 + 1 ) )) implies ( C154 . ( B95 + 1 ) ) = ( ( C154 . B95 ) + B96 )))) by RLVECT_1:def 12;
L881: ( len D166 ) = ( len C144 ) by RLVECT_2:def 7;
defpred S6[ Nat ] means ($1 <= ( len D165 ) implies ( C153 . $1 ) = ( D152 . ( C154 . $1 ) ));
L882: ( len D165 ) = ( len D155 ) by RLVECT_2:def 7;
L883: ( D152 .: D154 ) c= ( rng D152 ) by RELAT_1:111;
L884: (for B97 being Nat holds (S6[ B97 ] implies S6[ ( B97 + 1 ) ]))
proof
reconsider D167 = D151 as RealLinearSpace;
reconsider D168 = D150 as RealLinearSpace;
let C155 being Nat;
reconsider D169 = C155 as (Element of ( NAT )) by ORDINAL1:def 12;
set D170 = ( D169 + 1 );
assume L885: S6[ C155 ];
reconsider D171 = ( D155 /. D170 ) as (Element of D167);
reconsider D172 = ( C144 /. D170 ) as R2 -element  real-valued FinSequence;
reconsider D173 = ( C144 /. D170 ) as (Element of D168);
assume L886: ( C155 + 1 ) <= ( len D165 );
L887: 1 <= D170 by NAT_1:11;
L888: D170 in ( dom D155 ) by L887 , L882 , L886 , FINSEQ_3:25;
L889: D171 = ( D155 . D170 ) by L888 , PARTFUN1:def 6;
L890: ( D155 . D170 ) in ( D152 .: D154 ) by L875 , L888 , FUNCT_1:def 3;
L891: D170 in ( dom C144 ) by L882 , L831 , L886 , L887 , FINSEQ_3:25;
L892: D173 = ( C144 . D170 ) by L891 , PARTFUN1:def 6;
L893: ( D155 . D170 ) = ( D152 . D173 ) by L892 , L888 , FUNCT_1:12;
L894: ( D164 . D171 ) = ( D153 . D173 ) by L893 , L846 , L883 , L889 , L890;
L895: D170 in ( dom D166 ) by L882 , L881 , L831 , L886 , L887 , FINSEQ_3:25;
L896: ( D166 . D170 ) in ( rng D166 ) by L895 , FUNCT_1:def 3;
reconsider D174 = ( D166 . D170 ) as (Element of D150) by L896;
L897: D170 in ( dom D165 ) by L886 , L887 , FINSEQ_3:25;
L898: ( D165 . D170 ) in ( rng D165 ) by L897 , FUNCT_1:def 3;
reconsider D175 = ( D165 . D170 ) as (Element of D151) by L898;
L899: ( D152 . D174 ) = ( D152 . ( ( D153 . D173 ) * D173 ) ) by L895 , RLVECT_2:def 7
.= ( D152 . ( ( D153 . D173 ) * D172 ) ) by EUCLID:65
.= ( ( D153 . D173 ) * ( D152 . D172 ) ) by MATRTOP1:23
.= ( ( D164 . D171 ) * D171 ) by L888 , L892 , L889 , L894 , EUCLID:65 , FUNCT_1:12
.= D175 by L897 , RLVECT_2:def 7;
L900: C155 < ( len D165 ) by L886 , NAT_1:13;
L901: ( C154 . D170 ) = ( ( C154 . D169 ) + D174 ) by L900 , L880 , L882 , L881 , L831;
thus L902: ( D152 . ( C154 . ( C155 + 1 ) ) ) = ( ( D152 . ( C154 . D169 ) ) + ( D152 . D174 ) ) by L901 , MATRTOP1:27
.= ( C153 . ( C155 + 1 ) ) by L874 , L899 , L900 , L885;
end;
L903: S6[ ( 0 ) ] by L879 , L873 , MATRTOP1:29;
L904: (for B98 being Nat holds S6[ B98 ]) from NAT_1:sch 2(L903 , L884);
L905: ( Sum D165 ) = ( D152 . ( Sum D166 ) ) by L904 , L878 , L872 , L882 , L881 , L831;
L906: ( Sum D164 ) = ( D152 . C143 ) by L905 , L832 , L869 , L825 , L827 , L828 , L875 , RLVECT_2:def 8;
L907:
now
let C156 being Nat;
assume L908: (1 <= C156 & C156 <= ( len C144 ));
L909: C156 in ( dom C144 ) by L908 , FINSEQ_3:25;
L910: ( ( D153 * C144 ) . C156 ) = ( D153 . ( C144 . C156 ) ) by L909 , FUNCT_1:13;
L911: ( C144 . C156 ) in ( rng C144 ) by L909 , FUNCT_1:def 3;
reconsider D176 = ( C144 . C156 ) as (Element of D150) by L911;
L912: ( D155 . C156 ) = ( D152 . ( C144 . C156 ) ) by L909 , FUNCT_1:13;
L913: C156 in ( dom D155 ) by L831 , L908 , FINSEQ_3:25;
L914: ( D155 . C156 ) in ( rng D155 ) by L913 , FUNCT_1:def 3;
L915: ( ( D164 * D155 ) . C156 ) = ( D164 . ( D155 . C156 ) ) by L913 , FUNCT_1:13;
L916: S5[ ( D152 . D176 ) , ( ( D164 * D155 ) . C156 ) ] by L915 , L846 , L912;
thus L917: ( ( D164 * D155 ) . C156 ) = ( ( D153 * C144 ) . C156 ) by L916 , L875 , L883 , L910 , L912 , L914;
end;
L918: ( dom D164 ) = ( [#] D151 ) by FUNCT_2:def 1;
L919: ( len ( D164 * D155 ) ) = ( len D155 ) by L918 , L875 , FINSEQ_2:29;
L920: ( D153 * C144 ) = ( D164 * D155 ) by L919 , L831 , L877 , L907 , FINSEQ_1:14;
L921: ( Sum ( D164 * D155 ) ) = ( sum D153 ) by L920 , L825 , L826 , RLAFFIN1:def 3
.= 1 by L824 , RLAFFIN1:def 7;
L922: ( sum D164 ) = 1 by L921 , L832 , L869 , L825 , L875 , RLAFFIN1:def 3;
L923: ( Sum D164 ) in { ( Sum B99 ) where B99 is (Linear_Combination of ( D152 .: C142 )) : ( sum B99 ) = 1 } by L922;
thus L924: ( D152 . C143 ) in ( Affin ( D152 .: C142 ) ) by L923 , L906 , RLAFFIN1:59;
let R6 being R2 -element  real-valued FinSequence;
L925: R6 is (Element of D150) by L5;
L926: ( D152 . R6 ) in ( rng D152 ) by L925 , L829 , FUNCT_1:def 3;
L927: ( D152 .: C142 ) is  affinely-independent by L823 , L803;
L928: D164 = ( ( D152 . C143 ) |-- ( D152 .: C142 ) ) by L927 , L906 , L922 , L924 , RLAFFIN1:def 7;
thus L929: thesis by L928 , L846 , L926;
end;
theorem
L930: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B100 being  linearly-independent (Subset of ( TOP-REAL R3 )) holds (( the_rank_of R7 ) = R2 implies ( ( Mx2Tran R7 ) " B100 ) is  linearly-independent)))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
let C157 being  linearly-independent (Subset of ( TOP-REAL R3 ));
assume that
L931: ( the_rank_of R7 ) = R2;
set D177 = ( R2 -VectSp_over ( F_Real ) );
set D178 = ( R3 -VectSp_over ( F_Real ) );
reconsider D179 = ( MX2FinS ( 1. (( F_Real ) , R3) ) ) as (OrdBasis of D178) by MATRLIN2:45;
reconsider D180 = C157 as (Subset of D178) by L1;
reconsider D181 = ( MX2FinS ( 1. (( F_Real ) , R2) ) ) as (OrdBasis of D177) by MATRLIN2:45;
L932: ( len D181 ) = R2 by MATRTOP1:19;
reconsider D182 = R7 as (Matrix of ( len D181 ) , ( len D179 ) , ( F_Real )) by L932 , MATRTOP1:19;
set D183 = ( Mx2Tran (D182 , D181 , D179) );
L933: ( Mx2Tran R7 ) = D183 by MATRTOP1:20;
L934: D183 is  one-to-one by L931 , L933 , MATRTOP1:39;
reconsider D184 = ( C157 /\ ( rng D183 ) ) as (Subset of D178);
L935: D184 c= C157 by XBOOLE_1:17;
L936: D180 is  linearly-independent by L101;
L937: (( dom D183 ) = ( [#] D177 ) & D184 is  linearly-independent) by L936 , L935 , FUNCT_2:def 1 , VECTSP_7:1;
L938: ( D183 " D184 ) is  linearly-independent
proof
assume L939: ( D183 " D184 ) is non  linearly-independent;
consider C158 being (Linear_Combination of ( D183 " D184 )) such that L940: ( Carrier C158 ) <> ( {} ) and L941: ( Sum C158 ) = ( 0. D177 ) by L939 , RANKNULL:41;
set D185 = ( Carrier C158 );
L942: D185 c= ( D183 " D184 ) by VECTSP_6:def 4;
L943: (( D183 .: ( D183 " D184 ) ) = D184 & ( D183 @ C158 ) is (Linear_Combination of ( D183 .: D185 ))) by FUNCT_1:77 , RANKNULL:29 , XBOOLE_1:17;
L944: ( D183 @ C158 ) is (Linear_Combination of D184) by L943 , L942 , RELAT_1:123 , VECTSP_6:4;
L945: ( D183 | D185 ) is  one-to-one by L934 , FUNCT_1:52;
L946: ( Carrier ( D183 @ C158 ) ) = ( D183 .: D185 ) by L945 , RANKNULL:39;
L947: ( D183 | ( D183 " D184 ) ) is  one-to-one by L934 , FUNCT_1:52;
L948: ( Sum ( D183 @ C158 ) ) = ( D183 . ( Sum C158 ) ) by L947 , L212
.= ( 0. D178 ) by L941 , RANKNULL:9;
thus L949: contradiction by L948 , L937 , L940 , L946 , L944 , VECTSP_7:def 1;
end;
L950: ( D183 " C157 ) is  linearly-independent by L938 , RELAT_1:133;
thus L951: thesis by L950 , L933 , L101;
end;
theorem
L952: (for R2 being Nat holds (for R3 being Nat holds (for R7 being (Matrix of R2 , R3 , ( F_Real )) holds (for B101 being  affinely-independent (Subset of ( TOP-REAL R3 )) holds (( the_rank_of R7 ) = R2 implies ( ( Mx2Tran R7 ) " B101 ) is  affinely-independent)))))
proof
let R2 being Nat;
let R3 being Nat;
let R7 being (Matrix of R2 , R3 , ( F_Real ));
set D186 = ( Mx2Tran R7 );
set D187 = ( TOP-REAL R2 );
set D188 = ( TOP-REAL R3 );
let C159 being  affinely-independent (Subset of D188);
assume that
L953: ( the_rank_of R7 ) = R2;
reconsider D189 = ( C159 /\ ( rng D186 ) ) as  affinely-independent (Subset of D188) by RLAFFIN1:43 , XBOOLE_1:17;
L954: ( D186 " C159 ) = ( D186 " ( C159 /\ ( rng D186 ) ) ) by RELAT_1:133;
per cases ;
suppose L955: D189 is  empty;

L956: ( D186 " C159 ) is  empty by L955 , L954;
thus L957: thesis by L956;
end;
suppose L958: D189 is non  empty;

consider C160 being (Element of D188) such that L959: C160 in D189 and L960: ( ( ( - C160 ) + D189 ) \ { ( 0. D188 ) } ) is  linearly-independent by L958 , RLAFFIN1:def 4;
L961: C160 in ( rng D186 ) by L959 , XBOOLE_0:def 4;
consider C161 being set such that L962: C161 in ( dom D186 ) and L963: ( D186 . C161 ) = C160 by L961 , FUNCT_1:def 3;
reconsider D190 = C161 as (Element of D187) by L962;
L964: ( - D190 ) = ( ( 0. D187 ) - D190 ) by RLVECT_1:14;
L965: ( D186 . ( - D190 ) ) = ( ( D186 . ( 0. D187 ) ) - ( D186 . D190 ) ) by L964 , MATRTOP1:28
.= ( ( 0. D188 ) - ( D186 . D190 ) ) by MATRTOP1:29
.= ( - C160 ) by L963 , RLVECT_1:14;
L966: ( dom D186 ) = ( [#] D187 ) by FUNCT_2:def 1;
L967: ( D186 . ( 0. D187 ) ) = ( 0. D188 ) by MATRTOP1:29;
L968: { ( 0. D188 ) } = ( Im (D186 , ( 0. D187 )) ) by L967 , L966 , FUNCT_1:59
.= ( D186 .: { ( 0. D187 ) } ) by RELAT_1:def 16;
L969: D186 is  one-to-one by L953 , MATRTOP1:39;
L970: ( D186 " { ( 0. D188 ) } ) c= { ( 0. D187 ) } by L969 , L968 , FUNCT_1:82;
L971: { ( 0. D187 ) } c= ( [#] D187 ) by ZFMISC_1:31;
L972: { ( 0. D187 ) } c= ( D186 " { ( 0. D188 ) } ) by L971 , L966 , L968 , FUNCT_1:76;
L973: ( D186 " { ( 0. D188 ) } ) = { ( 0. D187 ) } by L972 , L970 , XBOOLE_0:def 10;
L974: ( D186 " ( ( ( - C160 ) + D189 ) \ { ( 0. D188 ) } ) ) = ( ( D186 " ( ( - C160 ) + D189 ) ) \ { ( 0. D187 ) } ) by L973 , FUNCT_1:69
.= ( ( ( - D190 ) + ( D186 " D189 ) ) \ { ( 0. D187 ) } ) by L965 , MATRTOP1:31;
L975: ( ( ( - D190 ) + ( D186 " D189 ) ) \ { ( 0. D187 ) } ) is  linearly-independent by L974 , L953 , L960 , L930;
L976: D190 in ( D186 " D189 ) by L959 , L962 , L963 , FUNCT_1:def 7;
thus L977: thesis by L976 , L954 , L975 , RLAFFIN1:def 4;
end;
end;
