:: Determinant of Some Matrices of Field Elements
::  by Yatsuka Nakamura
::
:: Received January 4, 2006
:: Copyright (c) 2006-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, NAT_1, FUNCT_2, FINSEQ_1, RELAT_1, FUNCT_1, TARSKI,
      MATRIX_2, FINSEQ_2, XBOOLE_0, SUBSET_1, XXREAL_0, ARYTM_3, JORDAN3,
      ORDINAL4, ARYTM_1, CARD_1, STRUCT_0, INT_1, CARD_3, GROUP_1, VECTSP_1,
      MATRIX_1, MATRIX_3, ALGSTR_0, SETWISEO, FINSUB_1, BINOP_1, FINSOP_1,
      ABIAN, TREES_1, SUPINF_2, FUNCOP_1, MESFUNC1, ZFMISC_1, QC_LANG1,
      PARTFUN1, FINSEQ_5, CLASSES1, RFINSEQ, MATRIX_7;
 notations TARSKI, XBOOLE_0, SUBSET_1, XCMPLX_0, XXREAL_0, ORDINAL1, NAT_1,
      NAT_D, RELAT_1, FUNCT_1, BINOP_1, ZFMISC_1, CARD_1, NUMBERS, VECTSP_1,
      FUNCT_2, FUNCOP_1, SETWISEO, PARTFUN1, GROUP_4, FINSUB_1, NEWTON,
      FINSOP_1, SETWOP_2, FINSEQ_1,
      FINSEQ_2, STRUCT_0, ALGSTR_0, MATRIX_2, MATRIX_3,
      FINSEQ_6, MATRIX_1, CLASSES1, RFINSEQ, FINSEQ_5, GROUP_1;
 constructors SETWISEO, REAL_1, NAT_1, NAT_D, FINSOP_1, NEWTON, RFINSEQ,
      FINSEQ_5, ALGSTR_1, GROUP_4, MATRIX_3, FINSEQ_6, CLASSES1, RELSET_1,
      BINOP_1;
 registrations SUBSET_1, FUNCT_1, ORDINAL1, PARTFUN1, FUNCT_2, FINSUB_1,
      XXREAL_0, XREAL_0, NAT_1, FINSEQ_1, STRUCT_0, GROUP_1, VECTSP_1,
      MATRIX_2, FVSUM_1, FINSET_1, CARD_1, RELSET_1, FINSEQ_2;
 requirements NUMERALS, BOOLE, SUBSET, ARITHM, REAL;
 definitions TARSKI, XBOOLE_0, BINOP_1, FINSEQ_1, MATRIX_1, FINSEQ_2, GROUP_4,
      ALGSTR_0, RELAT_1;
 theorems BINOP_1, RLVECT_1, MATRIX_3, VECTSP_1, MATRIX_1, GROUP_1, FUNCT_1,
      FINSEQ_1, NAT_1, MATRIX_2, FINSEQ_2, TARSKI, FINSOP_1, FVSUM_1, SETWISEO,
      FUNCT_2, XBOOLE_0, GROUP_4, ENUMSET1, ZFMISC_1, FINSEQ_6, XREAL_1,
      FINSEQ_5, INTEGRA2, FUNCOP_1, FINSUB_1, XBOOLE_1, RELAT_1, SUBSET_1,
      RFINSEQ, FINSEQ_3, XXREAL_0, ORDINAL1, NAT_D, PARTFUN1, XREAL_0,
      CLASSES1, CARD_1;
 schemes NAT_1, FUNCT_2, FINSEQ_1;

begin
theorem
L1: (for B1 being (Permutation of ( Seg 2 )) holds (B1 = <* 1 , 2 *> or B1 = <* 2 , 1 *>))
proof
let C1 being (Permutation of ( Seg 2 ));
L2: ( rng C1 ) = ( Seg 2 ) by FUNCT_2:def 3;
L3: 2 in { 1 , 2 } by TARSKI:def 2;
L4: ( C1 . 2 ) in ( Seg 2 ) by L3 , L2 , FINSEQ_1:2 , FUNCT_2:4;
L5: ( dom C1 ) = ( Seg 2 ) by FUNCT_2:52;
reconsider D1 = C1 as FinSequence by L5 , FINSEQ_1:def 2;
L6: ( len D1 ) = 2 by L5 , FINSEQ_1:def 3;
L7: (1 in ( dom C1 ) & 2 in ( dom C1 )) by L5;
L8: 1 in { 1 , 2 } by TARSKI:def 2;
L9: ( C1 . 1 ) in ( Seg 2 ) by L8 , L2 , FINSEQ_1:2 , FUNCT_2:4;
L10:
now
per cases  by L9 , L4 , FINSEQ_1:2 , TARSKI:def 2;
case L11: (( C1 . 1 ) = 1 & ( C1 . 2 ) = 1);
thus L12: contradiction by L11 , L7 , FUNCT_1:def 4;
end;
case L13: (( C1 . 1 ) = 1 & ( C1 . 2 ) = 2);
thus L14: thesis by L13 , L6 , FINSEQ_1:44;
end;
case L15: (( C1 . 1 ) = 2 & ( C1 . 2 ) = 1);
thus L16: thesis by L15 , L6 , FINSEQ_1:44;
end;
case L17: (( C1 . 1 ) = 2 & ( C1 . 2 ) = 2);
thus L18: contradiction by L17 , L7 , FUNCT_1:def 4;
end;
end;
thus L20: thesis by L10;
end;
theorem
L21: (for B2 being FinSequence holds ((B2 = <* 1 , 2 *> or B2 = <* 2 , 1 *>) implies B2 is (Permutation of ( Seg 2 ))))
proof
let C2 being FinSequence;
assume L22: (C2 = <* 1 , 2 *> or C2 = <* 2 , 1 *>);
L23: (( len <* 1 , 2 *> ) = 2 & ( len <* 2 , 1 *> ) = 2) by FINSEQ_1:44;
L24: ( dom C2 ) = ( Seg 2 ) by L23 , L22 , FINSEQ_1:def 3;
L25: ( rng C2 ) c= ( Seg 2 )
proof
let C3 being set;
assume L26: C3 in ( rng C2 );
L27: (ex B3 being set st (B3 in ( dom C2 ) & C3 = ( C2 . B3 ))) by L26 , FUNCT_1:def 3;
L28: (C3 = ( C2 . 1 ) or C3 = ( C2 . 2 )) by L27 , L24 , FINSEQ_1:2 , TARSKI:def 2;
L29: (C3 = 1 or C3 = 2 or C3 = 2 or C3 = 1) by L28 , L22 , FINSEQ_1:44;
thus L30: thesis by L29;
end;
reconsider D2 = C2 as (Function of ( Seg 2 ) , ( Seg 2 )) by L25 , L24 , FUNCT_2:2;
L31:
now
per cases  by L22;
case L32: C2 = <* 1 , 2 *>;
L33: (for B4 , B5 being set holds ((B4 in ( dom C2 ) & B5 in ( dom C2 ) & ( C2 . B4 ) = ( C2 . B5 )) implies B4 = B5))
proof
let C4 , C5 being set;
assume that
L34: (C4 in ( dom C2 ) & C5 in ( dom C2 ))
and
L35: ( C2 . C4 ) = ( C2 . C5 );
L36:
now
per cases  by L24 , L34 , FINSEQ_1:2 , TARSKI:def 2;
case L37: (C4 = 1 & C5 = 1);
thus L38: thesis by L37;
end;
case L39: (C4 = 1 & C5 = 2);
L40: ( C2 . C4 ) = 1 by L39 , L32 , FINSEQ_1:44;
thus L41: contradiction by L40 , L32 , L35 , L39 , FINSEQ_1:44;
end;
case L42: (C4 = 2 & C5 = 1);
L43: ( C2 . C4 ) = 2 by L42 , L32 , FINSEQ_1:44;
thus L44: contradiction by L43 , L32 , L35 , L42 , FINSEQ_1:44;
end;
case L45: (C4 = 2 & C5 = 2);
thus L46: thesis by L45;
end;
end;
thus L48: thesis by L36;
end;
L49: C2 is  one-to-one by L33 , FUNCT_1:def 4;
L50:
now
let C6 being set;
assume L51: C6 in ( rng C2 );
consider C7 being set such that L52: C7 in ( dom C2 ) and L53: ( C2 . C7 ) = C6 by L51 , FUNCT_1:def 3;
L54: ( len C2 ) = 2 by L32 , FINSEQ_1:44;
L55: ( dom C2 ) = ( Seg 2 ) by L54 , FINSEQ_1:def 3;
L56: (C7 = 1 or C7 = 2) by L55 , L52 , FINSEQ_1:2 , TARSKI:def 2;
L57: (C6 = 1 or C6 = 2) by L56 , L32 , L53 , FINSEQ_1:44;
thus L58: C6 in ( Seg 2 ) by L57;
end;
L59: ( rng C2 ) c= ( Seg 2 ) by L50 , TARSKI:def 3;
L60: ( Seg 2 ) c= ( rng C2 )
proof
let C8 being set;
assume L61: C8 in ( Seg 2 );
L62: (C8 = 1 or C8 = 2) by L61 , FINSEQ_1:2 , TARSKI:def 2;
L63: (C8 = ( C2 . 1 ) or C8 = ( C2 . 2 )) by L62 , L32 , FINSEQ_1:44;
L64: (1 in ( dom C2 ) & 2 in ( dom C2 )) by L24;
thus L65: thesis by L64 , L63 , FUNCT_1:def 3;
end;
L66: ( rng C2 ) = ( Seg 2 ) by L60 , L59 , XBOOLE_0:def 10;
L67: D2 is  onto by L66 , FUNCT_2:def 3;
thus L68: thesis by L67 , L49;
end;
case L69: C2 = <* 2 , 1 *>;
L70: (for B6 , B7 being set holds ((B6 in ( dom C2 ) & B7 in ( dom C2 ) & ( C2 . B6 ) = ( C2 . B7 )) implies B6 = B7))
proof
let C9 , C10 being set;
assume that
L71: (C9 in ( dom C2 ) & C10 in ( dom C2 ))
and
L72: ( C2 . C9 ) = ( C2 . C10 );
L73:
now
per cases  by L24 , L71 , FINSEQ_1:2 , TARSKI:def 2;
case L74: (C9 = 1 & C10 = 1);
thus L75: thesis by L74;
end;
case L76: (C9 = 1 & C10 = 2);
L77: ( C2 . C9 ) = 2 by L76 , L69 , FINSEQ_1:44;
thus L78: contradiction by L77 , L69 , L72 , L76 , FINSEQ_1:44;
end;
case L79: (C9 = 2 & C10 = 1);
L80: ( C2 . C9 ) = 1 by L79 , L69 , FINSEQ_1:44;
thus L81: contradiction by L80 , L69 , L72 , L79 , FINSEQ_1:44;
end;
case L82: (C9 = 2 & C10 = 2);
thus L83: thesis by L82;
end;
end;
thus L85: thesis by L73;
end;
L86: C2 is  one-to-one by L70 , FUNCT_1:def 4;
L87:
now
let C11 being set;
assume L88: C11 in ( rng C2 );
consider C12 being set such that L89: C12 in ( dom C2 ) and L90: ( C2 . C12 ) = C11 by L88 , FUNCT_1:def 3;
L91: ( len C2 ) = 2 by L69 , FINSEQ_1:44;
L92: ( dom C2 ) = ( Seg 2 ) by L91 , FINSEQ_1:def 3;
L93: (C12 = 1 or C12 = 2) by L92 , L89 , FINSEQ_1:2 , TARSKI:def 2;
L94: (C11 = 2 or C11 = 1) by L93 , L69 , L90 , FINSEQ_1:44;
thus L95: C11 in ( Seg 2 ) by L94;
end;
L96: ( rng C2 ) c= ( Seg 2 ) by L87 , TARSKI:def 3;
L97: ( Seg 2 ) c= ( rng C2 )
proof
let C13 being set;
assume L98: C13 in ( Seg 2 );
L99: (C13 = 1 or C13 = 2) by L98 , FINSEQ_1:2 , TARSKI:def 2;
L100: (C13 = ( C2 . 2 ) or C13 = ( C2 . 1 )) by L99 , L69 , FINSEQ_1:44;
L101: (2 in ( dom C2 ) & 1 in ( dom C2 )) by L24;
thus L102: thesis by L101 , L100 , FUNCT_1:def 3;
end;
L103: ( rng C2 ) = ( Seg 2 ) by L97 , L96 , XBOOLE_0:def 10;
L104: D2 is  onto by L103 , FUNCT_2:def 3;
thus L105: thesis by L104 , L86;
end;
end;
thus L107: thesis by L31;
end;
theorem
L108: ( Permutations 2 ) = { <* 1 , 2 *> , <* 2 , 1 *> }
proof
L109:
now
let C14 being set;
assume L110: C14 in { ( idseq 2 ) , <* 2 , 1 *> };
L111:
now
per cases  by L110 , TARSKI:def 2;
case L112: C14 = ( idseq 2 );
thus L113: C14 in ( Permutations 2 ) by L112 , MATRIX_2:def 9;
end;
case L114: C14 = <* 2 , 1 *>;
L115: <* 2 , 1 *> is (Permutation of ( Seg 2 )) by L21;
thus L116: C14 in ( Permutations 2 ) by L115 , L114 , MATRIX_2:def 9;
end;
end;
thus L118: C14 in ( Permutations 2 ) by L111;
end;
L119: { ( idseq 2 ) , <* 2 , 1 *> } c= ( Permutations 2 ) by L109 , TARSKI:def 3;
L120:
now
let C15 being set;
assume L121: C15 in ( Permutations 2 );
reconsider D3 = C15 as (Permutation of ( Seg 2 )) by L121 , MATRIX_2:def 9;
L122: (D3 = <* 1 , 2 *> or D3 = <* 2 , 1 *>) by L1;
thus L123: C15 in { ( idseq 2 ) , <* 2 , 1 *> } by L122 , FINSEQ_2:52 , TARSKI:def 2;
end;
L124: ( Permutations 2 ) c= { ( idseq 2 ) , <* 2 , 1 *> } by L120 , TARSKI:def 3;
thus L125: thesis by L124 , L119 , FINSEQ_2:52 , XBOOLE_0:def 10;
end;
theorem
L126: (for B8 being (Permutation of ( Seg 2 )) holds (B8 is  being_transposition implies B8 = <* 2 , 1 *>))
proof
let C16 being (Permutation of ( Seg 2 ));
assume L127: C16 is  being_transposition;
L128:
now
set D4 = <* 1 , 2 *>;
assume L129: C16 = <* 1 , 2 *>;
consider C17 , C18 being Nat such that L130: C17 in ( dom C16 ) and L131: (C18 in ( dom C16 ) & C17 <> C18) and L132: ( C16 . C17 ) = C18 and L133: ( C16 . C18 ) = C17 and L134: (for B9 being Nat holds ((B9 <> C17 & B9 <> C18 & B9 in ( dom C16 )) implies ( C16 . B9 ) = B9)) by L127 , MATRIX_2:def 11;
L135: ( len D4 ) = 2 by FINSEQ_1:44;
L136: ( dom C16 ) = { 1 , 2 } by L135 , L129 , FINSEQ_1:2 , FINSEQ_1:def 3;
L137: (C17 = 1 or C17 = 2) by L136 , L130 , TARSKI:def 2;
L138:
now
per cases  by L131 , L136 , L137 , TARSKI:def 2;
case L139: (C17 = 1 & C18 = 2);
thus L140: contradiction by L139 , L129 , L132 , FINSEQ_1:44;
end;
case L141: (C17 = 2 & C18 = 1);
thus L142: contradiction by L141 , L129 , L132 , FINSEQ_1:44;
end;
end;
thus L144: contradiction by L138;
end;
thus L145: thesis by L128 , L1;
end;
theorem
L146: (for B10 being non  empty set holds (for B11 being (FinSequence of B10) holds (for B12 being (Element of ( NAT )) holds ((1 <= B12 & B12 < ( len B11 )) implies B11 = ( ( mid (B11 , 1 , B12) ) ^ ( mid (B11 , ( B12 + 1 ) , ( len B11 )) ) )))))
proof
let C19 being non  empty set;
let C20 being (FinSequence of C19);
let C21 being (Element of ( NAT ));
assume L147: (1 <= C21 & C21 < ( len C20 ));
L148: ( mid (C20 , 1 , ( len C20 )) ) = ( ( mid (C20 , 1 , C21) ) ^ ( mid (C20 , ( C21 + 1 ) , ( len C20 )) ) ) by L147 , INTEGRA2:4;
thus L149: thesis by L148 , L147 , FINSEQ_6:120 , XXREAL_0:2;
end;
theorem
L150: (for B13 being non  empty set holds (for B14 being (FinSequence of B13) holds (2 <= ( len B14 ) implies B14 = ( ( B14 | ( ( len B14 ) -' 2 ) ) ^ ( mid (B14 , ( ( len B14 ) -' 1 ) , ( len B14 )) ) ))))
proof
let C22 being non  empty set;
let C23 being (FinSequence of C22);
assume L151: 2 <= ( len C23 );
L152: ( ( len C23 ) -' 2 ) = ( ( len C23 ) - 2 ) by L151 , XREAL_1:233;
L153: ( ( ( len C23 ) -' 2 ) + 1 ) = ( ( ( ( len C23 ) - 1 ) - 1 ) + 1 ) by L152
.= ( ( len C23 ) -' 1 ) by L151 , XREAL_1:233 , XXREAL_0:2;
L154:
now
per cases ;
case L155: ( ( len C23 ) -' 2 ) > ( 0 );
L156: ( ( 0 ) + 1 ) <= ( ( len C23 ) -' 2 ) by L155 , NAT_1:13;
L157: ( len C23 ) < ( ( len C23 ) + 1 ) by NAT_1:13;
L158: ( len C23 ) < ( ( ( len C23 ) + 1 ) + 1 ) by L157 , NAT_1:13;
L159: ( ( len C23 ) - 2 ) < ( ( ( len C23 ) + 2 ) - 2 ) by L158 , XREAL_1:14;
L160: C23 = ( ( mid (C23 , 1 , ( ( len C23 ) -' 2 )) ) ^ ( mid (C23 , ( ( ( len C23 ) -' 2 ) + 1 ) , ( len C23 )) ) ) by L159 , L152 , L156 , L146;
thus L161: thesis by L160 , L153 , L156 , FINSEQ_6:116;
end;
case L162: ( ( len C23 ) -' 2 ) = ( 0 );
L163: ( mid (C23 , ( ( ( len C23 ) -' 2 ) + 1 ) , ( len C23 )) ) = C23 by L162 , L151 , FINSEQ_6:120 , XXREAL_0:2;
L164: ( C23 | ( 0 ) ) is  empty;
L165: ( ( ( len C23 ) -' 2 ) + 1 ) = ( ( ( len C23 ) - 2 ) + 1 ) by L151 , XREAL_1:233
.= ( ( len C23 ) - 1 )
.= ( ( len C23 ) -' 1 ) by L151 , XREAL_1:233 , XXREAL_0:2;
thus L166: thesis by L165 , L162 , L163 , L164 , FINSEQ_1:34;
end;
end;
thus L168: thesis by L154;
end;
theorem
L169: (for B15 being non  empty set holds (for B16 being (FinSequence of B15) holds (1 <= ( len B16 ) implies B16 = ( ( B16 | ( ( len B16 ) -' 1 ) ) ^ ( mid (B16 , ( len B16 ) , ( len B16 )) ) ))))
proof
let C24 being non  empty set;
let C25 being (FinSequence of C24);
assume L170: 1 <= ( len C25 );
L171: ( ( len C25 ) -' 1 ) = ( ( len C25 ) - 1 ) by L170 , XREAL_1:233;
L172:
now
per cases ;
case L173: ( ( len C25 ) -' 1 ) > ( 0 );
L174: ( ( 0 ) + 1 ) <= ( ( len C25 ) -' 1 ) by L173 , NAT_1:13;
L175: ( len C25 ) < ( ( len C25 ) + 1 ) by NAT_1:13;
L176: ( ( len C25 ) - 1 ) < ( ( ( len C25 ) + 1 ) - 1 ) by L175 , XREAL_1:14;
L177: C25 = ( ( mid (C25 , 1 , ( ( len C25 ) -' 1 )) ) ^ ( mid (C25 , ( ( ( len C25 ) -' 1 ) + 1 ) , ( len C25 )) ) ) by L176 , L171 , L174 , L146;
thus L178: thesis by L177 , L171 , L174 , FINSEQ_6:116;
end;
case L179: ( ( len C25 ) -' 1 ) = ( 0 );
L180: ( C25 | ( 0 ) ) is  empty;
L181: ( mid (C25 , ( ( ( len C25 ) -' 1 ) + 1 ) , ( len C25 )) ) = C25 by L170 , L179 , FINSEQ_6:120;
thus L182: thesis by L181 , L171 , L179 , L180 , FINSEQ_1:34;
end;
end;
thus L184: thesis by L172;
end;
L185: <* 1 , 2 *> <> <* 2 , 1 *> by FINSEQ_1:77;
theorem
L186: (for B17 being (Element of ( Group_of_Perm 2 )) holds ((ex B18 being (Element of ( Permutations 2 )) st (B18 = B17 & B18 is  being_transposition)) implies B17 = <* 2 , 1 *>))
proof
let C26 being (Element of ( Group_of_Perm 2 ));
given C27 being (Element of ( Permutations 2 )) such that
L187: C27 = C26
and
L188: C27 is  being_transposition;

L189: (the carrier of ( Group_of_Perm 2 )) = ( Permutations 2 ) by MATRIX_2:def 10;
reconsider D5 = C26 as (Permutation of ( Seg 2 )) by L189 , MATRIX_2:def 9;
L190: (ex B19 , B20 being Nat st (B19 in ( dom C27 ) & B20 in ( dom C27 ) & B19 <> B20 & ( C27 . B19 ) = B20 & ( C27 . B20 ) = B19 & (for B21 being Nat holds ((B21 <> B19 & B21 <> B20 & B21 in ( dom C27 )) implies ( C27 . B21 ) = B21)))) by L188 , MATRIX_2:def 11;
L191: D5 is  being_transposition by L190 , L187 , MATRIX_2:def 11;
thus L192: thesis by L191 , L126;
end;
theorem
L193: (for B22 being (Element of ( NAT )) holds (for B23 , B24 being (Element of ( Group_of_Perm B22 )) holds (for B25 , B26 being (Element of ( Permutations B22 )) holds ((B23 = B25 & B24 = B26) implies ( B23 * B24 ) = ( B26 * B25 ))))) by MATRIX_2:def 10;
theorem
L194: (for B27 , B28 being (Element of ( Group_of_Perm 2 )) holds (((ex B29 being (Element of ( Permutations 2 )) st (B29 = B27 & B29 is  being_transposition)) & (ex B30 being (Element of ( Permutations 2 )) st (B30 = B28 & B30 is  being_transposition))) implies ( B27 * B28 ) = <* 1 , 2 *>))
proof
let C28 , C29 being (Element of ( Group_of_Perm 2 ));
assume that
L195: (ex B31 being (Element of ( Permutations 2 )) st (B31 = C28 & B31 is  being_transposition))
and
L196: (ex B32 being (Element of ( Permutations 2 )) st (B32 = C29 & B32 is  being_transposition));
consider C30 being (Element of ( Permutations 2 )) such that L197: C30 = C28 and L198: C30 is  being_transposition by L195;
L199: (the carrier of ( Group_of_Perm 2 )) = ( Permutations 2 ) by MATRIX_2:def 10;
L200: (( C28 * C29 ) = <* 1 , 2 *> or ( C28 * C29 ) = <* 2 , 1 *>) by L199 , L108 , TARSKI:def 2;
reconsider D6 = C30 as FinSequence by L197 , L198 , L186;
L201: C28 = <* 2 , 1 *> by L195 , L186;
L202: ( len D6 ) = 2 by L201 , L197 , FINSEQ_1:44;
L203: 1 in ( Seg ( len D6 ) ) by L202;
L204: 1 in ( dom D6 ) by L203 , FINSEQ_1:def 3;
consider C31 being (Element of ( Permutations 2 )) such that L205: C31 = C29 and L206: C31 is  being_transposition by L196;
reconsider D7 = C31 as FinSequence by L205 , L206 , L186;
L207: C29 = <* 2 , 1 *> by L196 , L186;
L208: ( D7 . 2 ) = 1 by L207 , L205 , FINSEQ_1:44;
L209: ( C28 * C29 ) = ( C31 * C30 ) by L197 , L205 , MATRIX_2:def 10;
L210: ( D6 . 1 ) = 2 by L201 , L197 , FINSEQ_1:44;
L211: ( ( C31 * C30 ) . 1 ) = 1 by L210 , L208 , L204 , FUNCT_1:13;
thus L212: thesis by L211 , L200 , L209 , FINSEQ_1:44;
end;
theorem
L213: (for B33 being (FinSequence of ( Group_of_Perm 2 )) holds ((( ( len B33 ) mod 2 ) = ( 0 ) & (for R3 being Nat holds (R3 in ( dom B33 ) implies (ex B34 being (Element of ( Permutations 2 )) st (( B33 . R3 ) = B34 & B34 is  being_transposition))))) implies ( Product B33 ) = <* 1 , 2 *>))
proof
defpred S1[ (Element of ( NAT )) ] means (for B35 being (FinSequence of ( Group_of_Perm 2 )) holds ((( len B35 ) = ( 2 * $1 ) & (for R3 being Nat holds (R3 in ( dom B35 ) implies (ex B36 being (Element of ( Permutations 2 )) st (( B35 . R3 ) = B36 & B36 is  being_transposition))))) implies ( Product B35 ) = <* 1 , 2 *>));
let C32 being (FinSequence of ( Group_of_Perm 2 ));
assume that
L214: ( ( len C32 ) mod 2 ) = ( 0 )
and
L215: (for R3 being Nat holds (R3 in ( dom C32 ) implies (ex B37 being (Element of ( Permutations 2 )) st (( C32 . R3 ) = B37 & B37 is  being_transposition))));
L216: ((ex B38 being Nat st (( len C32 ) = ( ( 2 * B38 ) + ( 0 ) ) & ( 0 ) < 2)) or (( 0 ) = ( 0 ) & 2 = ( 0 ))) by L214 , NAT_D:def 2;
consider C33 being Nat such that L217: ( len C32 ) = ( 2 * C33 ) by L216;
L218: (for B39 being (Element of ( NAT )) holds (S1[ B39 ] implies S1[ ( B39 + 1 ) ]))
proof
let C34 being (Element of ( NAT ));
assume L219: S1[ C34 ];
L220: (for B40 being (FinSequence of ( Group_of_Perm 2 )) holds ((( len B40 ) = ( 2 * ( C34 + 1 ) ) & (for R3 being Nat holds (R3 in ( dom B40 ) implies (ex B41 being (Element of ( Permutations 2 )) st (( B40 . R3 ) = B41 & B41 is  being_transposition))))) implies ( Product B40 ) = <* 1 , 2 *>))
proof
let C35 being (FinSequence of ( Group_of_Perm 2 ));
assume that
L221: ( len C35 ) = ( 2 * ( C34 + 1 ) )
and
L222: (for R3 being Nat holds (R3 in ( dom C35 ) implies (ex B42 being (Element of ( Permutations 2 )) st (( C35 . R3 ) = B42 & B42 is  being_transposition))));
L223: ( len C35 ) = ( ( 2 * C34 ) + 2 ) by L221;
L224: 2 <= ( len C35 ) by L223 , NAT_1:11;
L225: ( ( len C35 ) -' 1 ) = ( ( len C35 ) - 1 ) by L224 , XREAL_1:233 , XXREAL_0:2;
L226: ( ( ( len C35 ) - ( ( len C35 ) -' 1 ) ) + 1 ) = ( ( ( len C35 ) - ( ( len C35 ) - 1 ) ) + 1 ) by L224 , XREAL_1:233 , XXREAL_0:2
.= 2;
set D8 = ( mid (C35 , ( ( len C35 ) -' 1 ) , ( len C35 )) );
L227: ( ( len C35 ) -' 1 ) <= ( len C35 ) by NAT_D:35;
L228: 1 <= ( len C35 ) by L224 , XXREAL_0:2;
L229: ( len C35 ) in ( Seg ( len C35 ) ) by L228;
L230: ( len C35 ) in ( dom C35 ) by L229 , FINSEQ_1:def 3;
L231: (ex B43 being (Element of ( Permutations 2 )) st (( C35 . ( len C35 ) ) = B43 & B43 is  being_transposition)) by L230 , L222;
reconsider D9 = ( Product ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) as (Element of ( Group_of_Perm 2 ));
reconsider D10 = ( Product ( D8 | ( ( len D8 ) -' 1 ) ) ) as (Element of ( Group_of_Perm 2 ));
L232: ( ( 1 + ( ( len C35 ) -' 1 ) ) -' 1 ) = ( ( 1 + ( ( len C35 ) -' 1 ) ) - 1 ) by NAT_1:11 , XREAL_1:233
.= ( ( len C35 ) -' 1 );
L233: ( ( 1 + 1 ) - 1 ) <= ( ( len C35 ) - 1 ) by L224 , XREAL_1:13;
L234: 1 <= ( ( len C35 ) -' 1 ) by L233 , L224 , XREAL_1:233 , XXREAL_0:2;
L235: ( len ( mid (C35 , ( ( len C35 ) -' 1 ) , ( len C35 )) ) ) = ( ( ( len C35 ) -' ( ( len C35 ) -' 1 ) ) + 1 ) by L234 , L228 , L227 , FINSEQ_6:118
.= ( ( ( len C35 ) - ( ( len C35 ) -' 1 ) ) + 1 ) by NAT_D:35 , XREAL_1:233
.= ( ( ( len C35 ) - ( ( len C35 ) - 1 ) ) + 1 ) by L224 , XREAL_1:233 , XXREAL_0:2
.= 2;
L236: ( ( len D8 ) -' 1 ) = ( ( len D8 ) - 1 ) by L235 , XREAL_1:233;
L237: ( ( D8 | ( ( len D8 ) -' 1 ) ) . 1 ) = ( D8 . 1 ) by L236 , L235 , FINSEQ_3:112
.= ( C35 . ( ( len C35 ) -' 1 ) ) by L233 , L227 , L226 , L232 , FINSEQ_6:122;
L238: (for R3 being Nat holds (R3 in ( dom ( C35 | ( ( len C35 ) -' 2 ) ) ) implies (ex B44 being (Element of ( Permutations 2 )) st (( ( C35 | ( ( len C35 ) -' 2 ) ) . R3 ) = B44 & B44 is  being_transposition))))
proof
let R3 being Nat;
assume L239: R3 in ( dom ( C35 | ( ( len C35 ) -' 2 ) ) );
L240: R3 in ( Seg ( len ( C35 | ( ( len C35 ) -' 2 ) ) ) ) by L239 , FINSEQ_1:def 3;
L241: 1 <= R3 by L240 , FINSEQ_1:1;
L242: R3 <= ( len ( C35 | ( ( len C35 ) -' 2 ) ) ) by L240 , FINSEQ_1:1;
L243: ( len ( C35 | ( ( len C35 ) -' 2 ) ) ) <= ( len C35 ) by FINSEQ_5:16;
L244: R3 <= ( len C35 ) by L243 , L242 , XXREAL_0:2;
L245: R3 in ( dom C35 ) by L244 , L241 , FINSEQ_3:25;
L246: (ex B45 being (Element of ( Permutations 2 )) st (( C35 . R3 ) = B45 & B45 is  being_transposition)) by L245 , L222;
L247: ( len ( C35 | ( ( len C35 ) -' 2 ) ) ) = ( ( len C35 ) -' 2 ) by FINSEQ_1:59 , NAT_D:35;
thus L248: thesis by L247 , L242 , L246 , FINSEQ_3:112;
end;
L249: ( len ( C35 | ( ( len C35 ) -' 2 ) ) ) = ( ( len C35 ) -' 2 ) by FINSEQ_1:59 , NAT_D:35
.= ( 2 * C34 ) by L223 , NAT_D:34;
L250: ( Product ( C35 | ( ( len C35 ) -' 2 ) ) ) = <* 1 , 2 *> by L249 , L219 , L238;
L251: ( 1_ ( Group_of_Perm 2 ) ) = ( Product ( C35 | ( ( len C35 ) -' 2 ) ) ) by L250 , FINSEQ_2:52 , MATRIX_2:24;
L252: C35 = ( ( C35 | ( ( len C35 ) -' 2 ) ) ^ ( mid (C35 , ( ( len C35 ) -' 1 ) , ( len C35 )) ) ) by L223 , L150 , NAT_1:11;
L253: ( Product C35 ) = ( ( Product ( C35 | ( ( len C35 ) -' 2 ) ) ) * ( Product ( mid (C35 , ( ( len C35 ) -' 1 ) , ( len C35 )) ) ) ) by L252 , GROUP_4:5
.= ( Product ( mid (C35 , ( ( len C35 ) -' 1 ) , ( len C35 )) ) ) by L251 , GROUP_1:def 4;
L254: 2 <= ( 2 + ( ( len C35 ) -' 1 ) ) by NAT_1:11;
L255: ( ( 2 + ( ( len C35 ) -' 1 ) ) -' 1 ) = ( ( 2 + ( ( len C35 ) -' 1 ) ) - 1 ) by L254 , XREAL_1:233 , XXREAL_0:2
.= ( len C35 ) by L225;
L256: ( ( ( len C35 ) - ( ( len C35 ) -' 1 ) ) + 1 ) = ( ( ( len C35 ) - ( ( len C35 ) - 1 ) ) + 1 ) by L224 , XREAL_1:233 , XXREAL_0:2
.= ( 1 + 1 );
L257: ( ( 1 + ( len D8 ) ) -' 1 ) = ( ( 1 + ( len D8 ) ) - 1 ) by NAT_1:11 , XREAL_1:233;
L258: ( len ( D8 | ( ( len D8 ) -' 1 ) ) ) = ( ( len D8 ) -' 1 ) by FINSEQ_1:59 , NAT_D:35
.= ( ( len D8 ) - 1 ) by L235 , XREAL_1:233
.= 1 by L235;
L259: 1 in ( Seg ( len ( D8 | ( ( len D8 ) -' 1 ) ) ) ) by L258;
L260: 1 in ( dom ( D8 | ( ( len D8 ) -' 1 ) ) ) by L259 , FINSEQ_1:def 3;
L261: (( rng ( D8 | ( ( len D8 ) -' 1 ) ) ) c= (the carrier of ( Group_of_Perm 2 )) & ( ( D8 | ( ( len D8 ) -' 1 ) ) . 1 ) in ( rng ( D8 | ( ( len D8 ) -' 1 ) ) )) by L260 , FINSEQ_1:def 4 , FUNCT_1:def 3;
reconsider D11 = ( ( D8 | ( ( len D8 ) -' 1 ) ) . 1 ) as (Element of ( Group_of_Perm 2 )) by L261;
L262: D10 = ( Product <* D11 *> ) by L258 , FINSEQ_1:40
.= ( C35 . ( ( len C35 ) -' 1 ) ) by L237 , FINSOP_1:11;
L263: 1 <= ( ( ( len D8 ) - ( len D8 ) ) + 1 );
L264: ( ( mid (D8 , ( len D8 ) , ( len D8 )) ) . 1 ) = ( D8 . ( ( 1 + ( len D8 ) ) -' 1 ) ) by L263 , L235 , FINSEQ_6:122
.= ( C35 . ( len C35 ) ) by L233 , L227 , L235 , L256 , L257 , L255 , FINSEQ_6:122;
L265: ( len ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) = ( ( ( len D8 ) -' ( len D8 ) ) + 1 ) by L235 , FINSEQ_6:118
.= ( ( 0 ) + 1 ) by XREAL_1:232
.= 1;
L266: 1 in ( Seg ( len ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) ) by L265;
L267: 1 in ( dom ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) by L266 , FINSEQ_1:def 3;
L268: (( rng ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) c= (the carrier of ( Group_of_Perm 2 )) & ( ( mid (D8 , ( len D8 ) , ( len D8 )) ) . 1 ) in ( rng ( mid (D8 , ( len D8 ) , ( len D8 )) ) )) by L267 , FINSEQ_1:def 4 , FUNCT_1:def 3;
reconsider D12 = ( ( mid (D8 , ( len D8 ) , ( len D8 )) ) . 1 ) as (Element of ( Group_of_Perm 2 )) by L268;
L269: D9 = ( Product <* D12 *> ) by L265 , FINSEQ_1:40
.= ( C35 . ( len C35 ) ) by L264 , FINSOP_1:11;
L270: ( ( len C35 ) -' 1 ) in ( Seg ( len C35 ) ) by L234 , L227;
L271: ( ( len C35 ) -' 1 ) in ( dom C35 ) by L270 , FINSEQ_1:def 3;
L272: (ex B46 being (Element of ( Permutations 2 )) st (( C35 . ( ( len C35 ) -' 1 ) ) = B46 & B46 is  being_transposition)) by L271 , L222;
L273: D8 = ( ( D8 | ( ( len D8 ) -' 1 ) ) ^ ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) by L235 , L169;
L274: ( Product D8 ) = ( ( Product ( D8 | ( ( len D8 ) -' 1 ) ) ) * ( Product ( mid (D8 , ( len D8 ) , ( len D8 )) ) ) ) by L273 , GROUP_4:5
.= <* 1 , 2 *> by L272 , L231 , L262 , L269 , L194;
thus L275: thesis by L274 , L253;
end;
thus L276: thesis by L220;
end;
L277: (for B47 being (FinSequence of ( Group_of_Perm 2 )) holds ((( len B47 ) = ( 2 * ( 0 ) ) & (for R3 being Nat holds (R3 in ( dom B47 ) implies (ex B48 being (Element of ( Permutations 2 )) st (( B47 . R3 ) = B48 & B48 is  being_transposition))))) implies ( Product B47 ) = <* 1 , 2 *>))
proof
set D13 = ( Group_of_Perm 2 );
let C36 being (FinSequence of ( Group_of_Perm 2 ));
assume that
L278: ( len C36 ) = ( 2 * ( 0 ) )
and
L279: (for R3 being Nat holds (R3 in ( dom C36 ) implies (ex B49 being (Element of ( Permutations 2 )) st (( C36 . R3 ) = B49 & B49 is  being_transposition))));
L280: ( 1_ D13 ) = <* 1 , 2 *> by FINSEQ_2:52 , MATRIX_2:24;
L281: C36 = ( <*> (the carrier of D13) ) by L278;
thus L282: thesis by L281 , L280 , GROUP_4:8;
end;
L283: S1[ ( 0 ) ] by L277;
L284: (for B50 being (Element of ( NAT )) holds S1[ B50 ]) from NAT_1:sch 1(L283 , L218);
reconsider D14 = C33 as (Element of ( NAT )) by ORDINAL1:def 12;
L285: ( len C32 ) = ( 2 * D14 ) by L217;
thus L286: thesis by L285 , L215 , L284;
end;
theorem
L287: (for B51 being Field holds (for B52 being (Matrix of 2 , B51) holds ( Det B52 ) = ( ( ( B52 * (1 , 1) ) * ( B52 * (2 , 2) ) ) - ( ( B52 * (1 , 2) ) * ( B52 * (2 , 1) ) ) )))
proof
reconsider D15 = <* 1 , 2 *> , D16 = <* 2 , 1 *> as (Permutation of ( Seg 2 )) by L21;
let C37 being Field;
let C38 being (Matrix of 2 , C37);
L288:
now
L289: ( D15 . 1 ) = 1 by FINSEQ_1:44;
assume L290: D15 = D16;
thus L291: contradiction by L290 , L289 , FINSEQ_1:44;
end;
set D17 = { D15 , D16 };
reconsider D18 = ( <*> D17 ) as (FinSequence of ( Group_of_Perm 2 )) by L108 , MATRIX_2:def 10;
set D19 = ( Permutations 2 );
reconsider D20 = D15 , D21 = D16 as (Element of ( Permutations 2 )) by MATRIX_2:def 9;
set D22 = (the carrier of C37);
set D23 = ( Path_product C38 );
set D24 = (the addF of C37);
set D25 = ( (the multF of C37) $$ ( Path_matrix (D20 , C38) ) );
set D26 = ( FinOmega ( Permutations 2 ) );
L292: D26 = ( Permutations 2 ) by MATRIX_2:26 , MATRIX_2:def 14;
L293: ( Det C38 ) = ( (the addF of C37) $$ (( FinOmega ( Permutations 2 ) ) , ( Path_product C38 )) ) by MATRIX_3:def 9;
consider C39 being (Function of ( Fin D19 ) , D22) such that L294: ( Det C38 ) = ( C39 . D26 ) and L295: (for B53 being (Element of D22) holds (B53 is_a_unity_wrt D24 implies ( C39 . ( {} ) ) = B53)) and L296: (for B54 being (Element of D19) holds ( C39 . { B54 } ) = ( D23 . B54 )) and L297: (for B55 being (Element of ( Fin D19 )) holds ((B55 c= D26 & B55 <> ( {} )) implies (for B56 being (Element of D19) holds (B56 in ( D26 \ B55 ) implies ( C39 . ( B55 \/ { B56 } ) ) = ( D24 . (( C39 . B55 ) , ( D23 . B56 )) ))))) by L293 , L292 , SETWISEO:def 3;
L298: ( C39 . { D20 } ) = ( D23 . D20 ) by L296;
L299: ( C39 . D26 ) = ( (the addF of C37) . (( D23 . D20 ) , ( D23 . D21 )) )
proof
reconsider D27 = {. D20 .} as (Element of ( Fin D19 ));
L300: D27 c= D26
proof
let C40 being set;
assume L301: C40 in D27;
L302: C40 = D20 by L301 , TARSKI:def 1;
thus L303: thesis by L302 , L292;
end;
L304: ( D26 \ D27 ) = { D16 } by L288 , L292 , L108 , ZFMISC_1:17;
L305: D16 in ( D26 \ D27 ) by L304 , TARSKI:def 1;
L306: ( C39 . ( D27 \/ { D21 } ) ) = ( D24 . (( C39 . D27 ) , ( D23 . D21 )) ) by L305 , L297 , L300;
thus L307: thesis by L306 , L292 , L298 , L108 , ENUMSET1:1;
end;
set D28 = ( (the multF of C37) $$ ( Path_matrix (D21 , C38) ) );
L308: ( D20 . 2 ) = 2 by FINSEQ_1:44;
L309: ( D21 . 2 ) = 1 by FINSEQ_1:44;
L310: ( len ( Path_matrix (D20 , C38) ) ) = 2 by MATRIX_3:def 7;
consider C41 being (Function of ( NAT ) , (the carrier of C37)) such that L311: ( C41 . 1 ) = ( ( Path_matrix (D20 , C38) ) . 1 ) and L312: (for B57 being (Element of ( NAT )) holds ((( 0 ) <> B57 & B57 < 2) implies ( C41 . ( B57 + 1 ) ) = ( (the multF of C37) . (( C41 . B57 ) , ( ( Path_matrix (D20 , C38) ) . ( B57 + 1 ) )) ))) and L313: D25 = ( C41 . 2 ) by L310 , FINSOP_1:def 1;
L314: 1 in ( Seg 2 );
L315: 1 in ( dom ( Path_matrix (D20 , C38) ) ) by L314 , L310 , FINSEQ_1:def 3;
L316: 2 in ( Seg 2 );
L317: 2 in ( dom ( Path_matrix (D20 , C38) ) ) by L316 , L310 , FINSEQ_1:def 3;
L318: (( D20 . 1 ) = 1 & ( ( Path_matrix (D20 , C38) ) . 2 ) = ( C38 * (2 , 2) )) by L317 , L308 , FINSEQ_1:44 , MATRIX_3:def 7;
L319: ( len ( Path_matrix (D21 , C38) ) ) = 2 by MATRIX_3:def 7;
consider C42 being (Function of ( NAT ) , (the carrier of C37)) such that L320: ( C42 . 1 ) = ( ( Path_matrix (D21 , C38) ) . 1 ) and L321: (for B58 being (Element of ( NAT )) holds ((( 0 ) <> B58 & B58 < 2) implies ( C42 . ( B58 + 1 ) ) = ( (the multF of C37) . (( C42 . B58 ) , ( ( Path_matrix (D21 , C38) ) . ( B58 + 1 ) )) ))) and L322: D28 = ( C42 . 2 ) by L319 , FINSOP_1:def 1;
L323: 1 in ( dom ( Path_matrix (D21 , C38) ) ) by L319 , L314 , FINSEQ_1:def 3;
L324: 2 in ( dom ( Path_matrix (D21 , C38) ) ) by L319 , L316 , FINSEQ_1:def 3;
L325: (( D21 . 1 ) = 2 & ( ( Path_matrix (D21 , C38) ) . 2 ) = ( C38 * (2 , 1) )) by L324 , L309 , FINSEQ_1:44 , MATRIX_3:def 7;
L326: ( C42 . ( 1 + 1 ) ) = ( (the multF of C37) . (( C42 . 1 ) , ( ( Path_matrix (D21 , C38) ) . ( 1 + 1 ) )) ) by L321
.= ( ( C38 * (1 , 2) ) * ( C38 * (2 , 1) ) ) by L323 , L325 , L320 , MATRIX_3:def 7;
L327: ( len ( Permutations 2 ) ) = 2 by MATRIX_2:18;
L328: (not (ex B59 being (FinSequence of ( Group_of_Perm 2 )) st (( ( len B59 ) mod 2 ) = ( 0 ) & D16 = ( Product B59 ) & (for R3 being Nat holds (R3 in ( dom B59 ) implies (ex B60 being (Element of ( Permutations 2 )) st (( B59 . R3 ) = B60 & B60 is  being_transposition))))))) by L185 , L213;
L329: (( D23 . D21 ) = ( - (( (the multF of C37) "**" ( Path_matrix (D21 , C38) ) ) , D21) ) & D21 is  odd) by L328 , L327 , MATRIX_2:def 12 , MATRIX_3:def 8;
L330: ( D23 . D21 ) = ( - D28 ) by L329 , MATRIX_2:def 13;
L331: ( Product D18 ) = ( Product ( <*> (the carrier of ( Group_of_Perm 2 )) ) )
.= ( 1_ ( Group_of_Perm 2 ) ) by GROUP_4:8
.= D20 by FINSEQ_2:52 , MATRIX_2:24;
L332: ( ( 0 ) mod 2 ) = ( 0 ) by NAT_D:26;
L333: (ex B61 being (FinSequence of ( Group_of_Perm 2 )) st (( ( len B61 ) mod 2 ) = ( 0 ) & D15 = ( Product B61 ) & (for R3 being Nat holds (R3 in ( dom B61 ) implies (ex B62 being (Element of ( Permutations 2 )) st (( B61 . R3 ) = B62 & B62 is  being_transposition))))))
proof
take D18;
thus L334: (( ( len D18 ) mod 2 ) = ( 0 ) & D15 = ( Product D18 )) by L332 , L331;
let R3 being Nat;
thus L335: thesis;
end;
L336: (( D23 . D20 ) = ( - (( (the multF of C37) "**" ( Path_matrix (D20 , C38) ) ) , D20) ) & D20 is  even) by L333 , L327 , MATRIX_2:def 12 , MATRIX_3:def 8;
L337: ( C41 . ( 1 + 1 ) ) = ( (the multF of C37) . (( C41 . 1 ) , ( ( Path_matrix (D20 , C38) ) . ( 1 + 1 ) )) ) by L312
.= ( ( C38 * (1 , 1) ) * ( C38 * (2 , 2) ) ) by L315 , L318 , L311 , MATRIX_3:def 7;
thus L338: thesis by L337 , L294 , L299 , L313 , L322 , L326 , L336 , L330 , MATRIX_2:def 13;
end;
definition
let C43 being Nat;
let C44 being Field;
let C45 being (Matrix of C43 , C44);
let C46 being (Element of C44);
redefine func C46 * C45 -> (Matrix of C43 , C44);

coherence
proof
L339: ( width ( C46 * C45 ) ) = ( width C45 ) by MATRIX_3:def 5;
L340: ( len C45 ) = C43 by MATRIX_1:def 2;
L341: ( len ( C46 * C45 ) ) = ( len C45 ) by MATRIX_3:def 5;
L342: ( len C45 ) = C43 by MATRIX_1:def 2;
L343:
now
per cases ;
case L344: ( len C45 ) > ( 0 );
L345: C43 = ( width C45 ) by L344 , L340 , MATRIX_1:20;
thus L346: thesis by L345 , L340 , L341 , L339 , L344 , MATRIX_1:20;
end;
case L347: ( len C45 ) <= ( 0 );
L348: ( len ( C46 * C45 ) ) = ( 0 ) by L347 , MATRIX_3:def 5;
L349: ( Seg ( len ( C46 * C45 ) ) ) = ( {} ) by L348;
L350: (for B63 being (FinSequence of C44) holds (B63 in ( rng ( C46 * C45 ) ) implies ( len B63 ) = ( 0 )))
proof
let C47 being (FinSequence of C44);
assume L351: C47 in ( rng ( C46 * C45 ) );
L352: (ex B64 being set st (B64 in ( dom ( C46 * C45 ) ) & C47 = ( ( C46 * C45 ) . B64 ))) by L351 , FUNCT_1:def 3;
thus L353: thesis by L352 , L349 , FINSEQ_1:def 3;
end;
thus L354: thesis by L350 , L342 , L341 , L348 , MATRIX_1:def 2;
end;
end;
thus L356: thesis by L343;
end;
end;
theorem
L358: (for B65 being Field holds (for B66 , B67 being (Element of ( NAT )) holds (( len ( 0. (B65 , B66 , B67) ) ) = B66 & ( dom ( 0. (B65 , B66 , B67) ) ) = ( Seg B66 ))))
proof
let C48 being Field;
let C49 , C50 being (Element of ( NAT ));
L359: ( len ( C49 |-> ( C50 |-> ( 0. C48 ) ) ) ) = C49 by CARD_1:def 7;
thus L360: ( len ( 0. (C48 , C49 , C50) ) ) = C49 by L359 , MATRIX_3:def 1;
thus L361: thesis by L360 , FINSEQ_1:def 3;
end;
theorem
L362: (for B68 being Field holds (for B69 being (Element of ( NAT )) holds (for B70 being (Element of ( Permutations B69 )) holds (for B71 being (Element of ( NAT )) holds (B71 in ( Seg B69 ) implies ( B70 . B71 ) in ( Seg B69 ))))))
proof
let C51 being Field;
let C52 being (Element of ( NAT ));
let C53 being (Element of ( Permutations C52 ));
let C54 being (Element of ( NAT ));
L363: C53 is (Permutation of ( Seg C52 )) by MATRIX_2:def 9;
assume L364: C54 in ( Seg C52 );
thus L365: thesis by L364 , L363 , FUNCT_2:5;
end;
theorem
L366: (for B72 being Field holds (for B73 being (Element of ( NAT )) holds (B73 >= 1 implies ( Det ( 0. (B72 , B73 , B73) ) ) = ( 0. B72 ))))
proof
let C55 being Field;
let C56 being (Element of ( NAT ));
set D29 = ( FinOmega ( Permutations C56 ) );
set D30 = ( Path_product ( 0. (C55 , C56 , C56) ) );
set D31 = (the addF of C55);
set D32 = (the carrier of C55);
set D33 = ( Permutations C56 );
reconsider D34 = ( ( Fin D33 ) --> ( 0. C55 ) ) as (Function of ( Fin D33 ) , D32);
L367: ( D34 . D29 ) = ( 0. C55 ) by FUNCOP_1:7;
L368: (for B74 being (Element of D32) holds (B74 is_a_unity_wrt D31 implies ( D34 . ( {} ) ) = B74))
proof
let C57 being (Element of D32);
L369: ( 0. C55 ) is_a_unity_wrt D31 by FVSUM_1:6;
L370: ( D31 . (( 0. C55 ) , C57) ) = C57 by L369 , BINOP_1:3;
assume L371: C57 is_a_unity_wrt D31;
L372: ( D31 . (( 0. C55 ) , C57) ) = ( 0. C55 ) by L371 , BINOP_1:3;
thus L373: thesis by L372 , L370 , FINSUB_1:7 , FUNCOP_1:7;
end;
assume L374: C56 >= 1;
L375: (for B75 being set holds (B75 in ( dom ( Path_product ( 0. (C55 , C56 , C56) ) ) ) implies ( ( Path_product ( 0. (C55 , C56 , C56) ) ) . B75 ) = ( ( ( Permutations C56 ) --> ( 0. C55 ) ) . B75 )))
proof
let C58 being set;
assume L376: C58 in ( dom ( Path_product ( 0. (C55 , C56 , C56) ) ) );
L377: (for B76 being (Element of ( Permutations C56 )) holds ( ( ( Permutations C56 ) --> ( 0. C55 ) ) . B76 ) = ( - (( (the multF of C55) $$ ( Path_matrix (B76 , ( 0. (C55 , C56 , C56) )) ) ) , B76) ))
proof
defpred S2[ (Element of ( NAT )) ] means ( (the multF of C55) $$ ( ( $1 + 1 ) |-> ( 0. C55 ) ) ) = ( 0. C55 );
let C59 being (Element of ( Permutations C56 ));
L378: (for B77 being (Element of ( NAT )) holds (S2[ B77 ] implies S2[ ( B77 + 1 ) ]))
proof
let C60 being (Element of ( NAT ));
L379: ( ( ( C60 + 1 ) + 1 ) |-> ( 0. C55 ) ) = ( ( ( C60 + 1 ) |-> ( 0. C55 ) ) ^ <* ( 0. C55 ) *> ) by FINSEQ_2:60;
assume L380: S2[ C60 ];
L381: ( (the multF of C55) $$ ( ( ( C60 + 1 ) + 1 ) |-> ( 0. C55 ) ) ) = ( ( 0. C55 ) * ( 0. C55 ) ) by L380 , L379 , FINSOP_1:4
.= ( 0. C55 ) by VECTSP_1:6;
thus L382: thesis by L381;
end;
L383: ( 1 |-> ( 0. C55 ) ) = <* ( 0. C55 ) *> by FINSEQ_2:59;
L384: S2[ ( 0 ) ] by L383 , FINSOP_1:11;
L385: (for B78 being (Element of ( NAT )) holds S2[ B78 ]) from NAT_1:sch 1(L384 , L378);
L386:
now
per cases ;
case L387: C59 is  even;
thus L388: ( - (( 0. C55 ) , C59) ) = ( 0. C55 ) by L387 , MATRIX_2:def 13;
end;
case L389: (not C59 is  even);
L390: ( - (( 0. C55 ) , C59) ) = ( - ( 0. C55 ) ) by L389 , MATRIX_2:def 13
.= ( 0. C55 ) by RLVECT_1:12;
thus L391: ( - (( 0. C55 ) , C59) ) = ( 0. C55 ) by L390;
end;
end;
L393: (for R3 being Nat holds (for R4 being Nat holds ((R3 in ( dom ( C56 |-> ( 0. C55 ) ) ) & R4 = ( C59 . R3 )) implies ( ( C56 |-> ( 0. C55 ) ) . R3 ) = ( ( 0. (C55 , C56 , C56) ) * (R3 , R4) ))))
proof
let R3 being Nat;
let R4 being Nat;
assume that
L394: R3 in ( dom ( C56 |-> ( 0. C55 ) ) )
and
L395: R4 = ( C59 . R3 );
L396: R3 in ( Seg C56 ) by L394 , FUNCOP_1:13;
L397: R4 in ( Seg C56 ) by L396 , L395 , L362;
L398: R4 in ( Seg ( width ( 0. (C55 , C56 , C56) ) ) ) by L397 , L374 , MATRIX_1:23;
L399: R3 in ( dom ( 0. (C55 , C56 , C56) ) ) by L396 , L358;
L400: [ R3 , R4 ] in ( Indices ( 0. (C55 , C56 , C56) ) ) by L399 , L398 , ZFMISC_1:def 2;
L401: ( ( C56 |-> ( 0. C55 ) ) . R3 ) = ( 0. C55 ) by L396 , FUNCOP_1:7;
thus L402: thesis by L401 , L400 , MATRIX_3:1;
end;
L403: ( len ( C56 |-> ( 0. C55 ) ) ) = C56 by CARD_1:def 7;
L404: ( Path_matrix (C59 , ( 0. (C55 , C56 , C56) )) ) = ( C56 |-> ( 0. C55 ) ) by L403 , L393 , MATRIX_3:def 7;
L405: ( C56 -' 1 ) = ( C56 - 1 ) by L374 , XREAL_1:233;
L406: ( ( C56 -' 1 ) + 1 ) = C56 by L405;
L407: ( ( ( Permutations C56 ) --> ( 0. C55 ) ) . C59 ) = ( 0. C55 ) by FUNCOP_1:7;
thus L408: thesis by L407 , L404 , L385 , L406 , L386;
end;
thus L409: thesis by L377 , MATRIX_3:def 8;
end;
L410: ( dom ( ( Permutations C56 ) --> ( 0. C55 ) ) ) = ( Permutations C56 ) by FUNCOP_1:13;
L411: ( dom ( Path_product ( 0. (C55 , C56 , C56) ) ) ) = ( dom ( ( Permutations C56 ) --> ( 0. C55 ) ) ) by L410 , FUNCT_2:def 1;
L412: ( Path_product ( 0. (C55 , C56 , C56) ) ) = ( ( Permutations C56 ) --> ( 0. C55 ) ) by L411 , L375 , FUNCT_1:2;
L413: (for B79 being (Element of D33) holds ( D34 . { B79 } ) = ( D30 . B79 ))
proof
let C61 being (Element of D33);
L414: ( D34 . {. C61 .} ) = ( 0. C55 ) by FUNCOP_1:7;
thus L415: thesis by L414 , L412 , FUNCOP_1:7;
end;
L416: (for B80 being (Element of ( Fin D33 )) holds ((B80 c= D29 & B80 <> ( {} )) implies (for B81 being (Element of D33) holds (B81 in ( D29 \ B80 ) implies ( D34 . ( B80 \/ { B81 } ) ) = ( D31 . (( D34 . B80 ) , ( D30 . B81 )) )))))
proof
let C62 being (Element of ( Fin D33 ));
assume that
L417: C62 c= D29
and
L418: C62 <> ( {} );
thus L419: (for B82 being (Element of D33) holds (B82 in ( D29 \ C62 ) implies ( D34 . ( C62 \/ { B82 } ) ) = ( D31 . (( D34 . C62 ) , ( D30 . B82 )) )))
proof
let C63 being (Element of D33);
assume L420: C63 in ( D29 \ C62 );
L421: (( D34 . ( C62 \/ {. C63 .} ) ) = ( 0. C55 ) & ( D34 . C62 ) = ( 0. C55 )) by FUNCOP_1:7;
L422: (( D30 . C63 ) = ( 0. C55 ) & ( 0. C55 ) is_a_unity_wrt D31) by L412 , FUNCOP_1:7 , FVSUM_1:6;
thus L423: thesis by L422 , L421 , BINOP_1:3;
end;

end;
L420: (D29 <> ( {} ) or D31 is  having_a_unity) by MATRIX_2:26 , MATRIX_2:def 14;
L421: ( (the addF of C55) $$ (( FinOmega ( Permutations C56 ) ) , ( Path_product ( 0. (C55 , C56 , C56) ) )) ) = ( 0. C55 ) by L420 , L367 , L368 , L413 , L416 , SETWISEO:def 3;
thus L422: thesis by L421 , MATRIX_3:def 9;
end;
definition
let C64 , C65 , C66 , C67 being set;
func IFIN (C64 , C65 , C66 , C67) equals 
:L423: C66 if C64 in C65 otherwise C67;
correctness;
end;
theorem
L425: (for B83 being Field holds (for B84 being (Element of ( NAT )) holds (B84 >= 1 implies ( Det ( 1. (B83 , B84) ) ) = ( 1_ B83 ))))
proof
let C68 being Field;
let C69 being (Element of ( NAT ));
assume L426: C69 >= 1;
deffunc H1(set) = ( IFEQ (( idseq C69 ) , $1 , ( 1_ C68 ) , ( 0. C68 )) );
set D35 = ( Permutations C69 );
set D36 = (the carrier of C68);
L427: (for B85 being set holds (B85 in D35 implies H1(B85) in D36));
L428: (ex B86 being (Function of D35 , D36) st (for B87 being set holds (B87 in D35 implies ( B86 . B87 ) = H1(B87)))) from FUNCT_2:sch 2(L427);
consider C70 being (Function of D35 , D36) such that L429: (for B88 being set holds (B88 in D35 implies ( C70 . B88 ) = H1(B88))) by L428;
L430: ( id ( Seg C69 ) ) is  even by MATRIX_2:25;
L431: (for B89 being set holds (B89 in ( dom ( Path_product ( 1. (C68 , C69) ) ) ) implies ( ( Path_product ( 1. (C68 , C69) ) ) . B89 ) = ( C70 . B89 )))
proof
let C71 being set;
assume L432: C71 in ( dom ( Path_product ( 1. (C68 , C69) ) ) );
L433: (for B90 being (Element of ( Permutations C69 )) holds ( C70 . B90 ) = ( - (( (the multF of C68) $$ ( Path_matrix (B90 , ( 1. (C68 , C69) )) ) ) , B90) ))
proof
defpred S3[ (Element of ( NAT )) ] means ( (the multF of C68) $$ ( ( $1 + 1 ) |-> ( 1_ C68 ) ) ) = ( 1_ C68 );
let C72 being (Element of ( Permutations C69 ));
L434: (for B91 being (Element of ( NAT )) holds (S3[ B91 ] implies S3[ ( B91 + 1 ) ]))
proof
let C73 being (Element of ( NAT ));
L435: ( ( ( C73 + 1 ) + 1 ) |-> ( 1_ C68 ) ) = ( ( ( C73 + 1 ) |-> ( 1_ C68 ) ) ^ <* ( 1_ C68 ) *> ) by FINSEQ_2:60;
assume L436: S3[ C73 ];
L437: ( (the multF of C68) $$ ( ( ( C73 + 1 ) + 1 ) |-> ( 1_ C68 ) ) ) = ( ( 1_ C68 ) * ( 1_ C68 ) ) by L436 , L435 , FINSOP_1:4
.= ( 1_ C68 ) by GROUP_1:def 4;
thus L438: thesis by L437;
end;
L439:
now
per cases ;
case L440: C72 is  even;
thus L441: ( - (( 0. C68 ) , C72) ) = ( 0. C68 ) by L440 , MATRIX_2:def 13;
end;
case L442: (not C72 is  even);
L443: ( - (( 0. C68 ) , C72) ) = ( - ( 0. C68 ) ) by L442 , MATRIX_2:def 13
.= ( 0. C68 ) by RLVECT_1:12;
thus L444: ( - (( 0. C68 ) , C72) ) = ( 0. C68 ) by L443;
end;
end;
L446: ( C69 -' 1 ) = ( C69 - 1 ) by L426 , XREAL_1:233;
L447: ( ( C69 -' 1 ) + 1 ) = C69 by L446;
L448: ( 1 |-> ( 1_ C68 ) ) = <* ( 1_ C68 ) *> by FINSEQ_2:59;
L449: S3[ ( 0 ) ] by L448 , FINSOP_1:11;
L450: (for B92 being (Element of ( NAT )) holds S3[ B92 ]) from NAT_1:sch 1(L449 , L434);
L451: (( len ( C69 |-> ( 1_ C68 ) ) ) = C69 & ( (the multF of C68) $$ ( C69 |-> ( 1_ C68 ) ) ) = ( 1_ C68 )) by L450 , L447 , CARD_1:def 7;
L452:
now
per cases ;
case L453: C72 = ( idseq C69 );
L454: (for R3 being Nat holds (for R4 being Nat holds ((R3 in ( dom ( C69 |-> ( 1_ C68 ) ) ) & R4 = ( C72 . R3 )) implies ( ( C69 |-> ( 1_ C68 ) ) . R3 ) = ( ( 1. (C68 , C69) ) * (R3 , R4) ))))
proof
L455: ( Indices ( 1. (C68 , C69) ) ) = [: ( Seg C69 ) , ( Seg C69 ) :] by L426 , MATRIX_1:23;
let R3 being Nat;
let R4 being Nat;
assume that
L456: R3 in ( dom ( C69 |-> ( 1_ C68 ) ) )
and
L457: R4 = ( C72 . R3 );
L458: R3 in ( Seg C69 ) by L456 , FUNCOP_1:13;
L459: R4 in ( Seg C69 ) by L458 , L457 , L362;
L460: [ R3 , R4 ] in ( Indices ( 1. (C68 , C69) ) ) by L459 , L458 , L455 , ZFMISC_1:def 2;
L461: (( ( C69 |-> ( 1_ C68 ) ) . R3 ) = ( 1_ C68 ) & ( C72 . R3 ) = R3) by L453 , L458 , FUNCOP_1:7 , FUNCT_1:17;
thus L462: thesis by L461 , L457 , L460 , MATRIX_1:def 11;
end;
L463: ( len ( Permutations C69 ) ) = C69 by MATRIX_2:18;
L464: ( - (( (the multF of C68) $$ ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) , C72) ) = ( (the multF of C68) $$ ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L463 , L430 , L453 , MATRIX_2:def 13;
L465: ( C70 . C72 ) = H1(C72) by L429
.= ( 1_ C68 ) by L453 , FUNCOP_1:def 8;
thus L466: thesis by L465 , L451 , L464 , L454 , MATRIX_3:def 7;
end;
case L467: C72 <> ( idseq C69 );
reconsider D37 = ( NAT ) as non  empty set;
defpred S4[ (Element of ( NAT )) ] means ($1 < C69 implies (ex B93 being (FinSequence of C68) st (( len B93 ) = ( $1 + 1 ) & ( B93 . 1 ) = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) & (for B94 being (Element of ( NAT )) holds ((( 0 ) <> B94 & B94 < ( $1 + 1 ) & B94 < C69) implies ( B93 . ( B94 + 1 ) ) = ( (the multF of C68) . (( B93 . B94 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( B94 + 1 ) )) ))))));
L468: ( rng ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) c= (the carrier of C68) by FINSEQ_1:def 4;
L469: ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) = C69 by MATRIX_3:def 7;
L470: 1 in ( Seg ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) ) by L469 , L426;
L471: 1 in ( dom ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L470 , FINSEQ_1:def 3;
L472: ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) in ( rng ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L471 , FUNCT_1:def 3;
reconsider D38 = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) as (Element of C68) by L472 , L468;
reconsider D39 = <* D38 *> as (FinSequence of C68);
L473: (for B95 being (Element of ( NAT )) holds ((( 0 ) <> B95 & B95 < ( ( 0 ) + 1 ) & B95 < C69) implies ( D39 . ( B95 + 1 ) ) = ( (the multF of C68) . (( D39 . B95 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( B95 + 1 ) )) ))) by NAT_1:13;
L474: ( dom C72 ) = ( Seg ( len ( Permutations C69 ) ) ) by FUNCT_2:52;
L475: ( dom C72 ) = ( Seg C69 ) by L474 , MATRIX_2:18;
L476: ( dom C72 ) = ( dom ( idseq C69 ) ) by L475 , RELAT_1:45;
consider C74 being set such that L477: C74 in ( dom C72 ) and L478: ( C72 . C74 ) <> ( ( idseq C69 ) . C74 ) by L476 , L467 , FUNCT_1:2;
reconsider D40 = C74 as (Element of ( NAT )) by L474 , L477;
L479: ( C72 . D40 ) <> D40 by L475 , L477 , L478 , FUNCT_1:18;
L480: (for B96 being (Element of ( NAT )) holds (S4[ B96 ] implies S4[ ( B96 + 1 ) ]))
proof
let C75 being (Element of ( NAT ));
assume L481: S4[ C75 ];
L482:
now
per cases ;
case L483: ( C75 + 1 ) < C69;
consider C76 being (FinSequence of C68) such that L484: ( len C76 ) = ( C75 + 1 ) and L485: ( C76 . 1 ) = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) and L486: (for B97 being (Element of ( NAT )) holds ((( 0 ) <> B97 & B97 < ( C75 + 1 ) & B97 < C69) implies ( C76 . ( B97 + 1 ) ) = ( (the multF of C68) . (( C76 . B97 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( B97 + 1 ) )) ))) by L483 , L481 , NAT_1:12;
defpred S5[ set , set ] means (($1 in ( Seg ( C75 + 1 ) ) implies $2 = ( C76 . $1 )) & ((not $1 in ( Seg ( C75 + 1 ) )) implies $2 = ( 0. C68 )));
L487: (for B98 being set holds (B98 in ( NAT ) implies (ex B99 being set st (B99 in (the carrier of C68) & S5[ B98 , B99 ]))))
proof
let C77 being set;
assume L488: C77 in ( NAT );
L489:
now
per cases ;
case L490: C77 in ( Seg ( C75 + 1 ) );
reconsider D41 = C77 as (Element of ( NAT )) by L490;
L491: D41 in ( dom C76 ) by L484 , L490 , FINSEQ_1:def 3;
L492: ( C76 . D41 ) in ( rng C76 ) by L491 , FUNCT_1:def 3;
L493: ( rng C76 ) c= (the carrier of C68) by FINSEQ_1:def 4;
reconsider D42 = ( C76 . D41 ) as (Element of C68) by L493 , L492;
L494: (C77 in ( Seg ( C75 + 1 ) ) implies D42 = ( C76 . C77 ));
thus L495: thesis by L494 , L490;
end;
case L496: (not C77 in ( Seg ( C75 + 1 ) ));
thus L497: thesis by L496;
end;
end;
thus L499: thesis by L489;
end;
L500: (ex B100 being (Function of ( NAT ) , (the carrier of C68)) st (for B101 being set holds (B101 in ( NAT ) implies S5[ B101 , ( B100 . B101 ) ]))) from FUNCT_2:sch 1(L487);
consider C78 being (Function of ( NAT ) , (the carrier of C68)) such that L501: (for B102 being set holds (B102 in ( NAT ) implies S5[ B102 , ( C78 . B102 ) ])) by L500;
L502: (1 <= ( ( C75 + 1 ) + 1 ) & ( ( C75 + 1 ) + 1 ) <= C69) by L483 , NAT_1:12 , NAT_1:13;
L503: ( ( C75 + 1 ) + 1 ) in ( Seg ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) ) by L502 , L469;
L504: ( ( C75 + 1 ) + 1 ) in ( dom ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L503 , FINSEQ_1:def 3;
L505: (( rng ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) c= (the carrier of C68) & ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( ( C75 + 1 ) + 1 ) ) in ( rng ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) )) by L504 , FINSEQ_1:def 4 , FUNCT_1:def 3;
L506: [ ( C78 . ( C75 + 1 ) ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( ( C75 + 1 ) + 1 ) ) ] in [: (the carrier of C68) , (the carrier of C68) :] by L505 , ZFMISC_1:def 2;
reconsider D43 = ( (the multF of C68) . (( C78 . ( C75 + 1 ) ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( ( C75 + 1 ) + 1 ) )) ) as (Element of C68) by L506 , FUNCT_2:5;
reconsider D44 = ( C76 ^ <* D43 *> ) as (FinSequence of C68);
L507: ( len D44 ) = ( ( len C76 ) + ( len <* D43 *> ) ) by FINSEQ_1:22
.= ( ( C75 + 1 ) + 1 ) by L484 , FINSEQ_1:40;
L508: (for B103 being (Element of ( NAT )) holds ((( 0 ) <> B103 & B103 < ( ( C75 + 1 ) + 1 ) & B103 < C69) implies ( D44 . ( B103 + 1 ) ) = ( (the multF of C68) . (( D44 . B103 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( B103 + 1 ) )) )))
proof
let C79 being (Element of ( NAT ));
assume that
L509: ( 0 ) <> C79
and
L510: C79 < ( ( C75 + 1 ) + 1 )
and
L511: C79 < C69;
L512:
now
per cases ;
case L513: C79 < ( C75 + 1 );
L514: (1 <= ( C79 + 1 ) & ( C79 + 1 ) <= ( C75 + 1 )) by L513 , NAT_1:12 , NAT_1:13;
L515: ( C79 + 1 ) in ( Seg ( len C76 ) ) by L514 , L484;
L516: ( C79 + 1 ) in ( dom C76 ) by L515 , FINSEQ_1:def 3;
L517: ( C76 . ( C79 + 1 ) ) = ( D44 . ( C79 + 1 ) ) by L516 , FINSEQ_1:def 7;
L518: ( ( 0 ) + 1 ) <= C79 by L509 , NAT_1:13;
L519: C79 in ( Seg ( len C76 ) ) by L518 , L484 , L513;
L520: C79 in ( dom C76 ) by L519 , FINSEQ_1:def 3;
L521: ( C76 . ( C79 + 1 ) ) = ( (the multF of C68) . (( C76 . C79 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( C79 + 1 ) )) ) by L486 , L509 , L511 , L513;
thus L522: thesis by L521 , L517 , L520 , FINSEQ_1:def 7;
end;
case L523: C79 >= ( C75 + 1 );
L524: ( C79 + 1 ) <= ( ( C75 + 1 ) + 1 ) by L510 , NAT_1:13;
L525: ( C79 + 1 ) > ( C75 + 1 ) by L523 , NAT_1:13;
L526: ( C79 + 1 ) >= ( ( C75 + 1 ) + 1 ) by L525 , NAT_1:13;
L527: ( C79 + 1 ) = ( ( C75 + 1 ) + 1 ) by L526 , L524 , XXREAL_0:1;
L528: 1 <= ( C75 + 1 ) by NAT_1:12;
L529: ( C75 + 1 ) in ( Seg ( C75 + 1 ) ) by L528;
L530: ( C75 + 1 ) in ( dom C76 ) by L529 , L484 , FINSEQ_1:def 3;
L531: ( D44 . ( C75 + 1 ) ) = ( C76 . ( C75 + 1 ) ) by L530 , FINSEQ_1:def 7;
L532: ( D44 . ( C79 + 1 ) ) = ( <* D43 *> . ( ( C79 + 1 ) - ( C75 + 1 ) ) ) by L484 , L507 , L525 , L524 , FINSEQ_1:24
.= D43 by L527 , FINSEQ_1:def 8;
thus L533: thesis by L532 , L501 , L527 , L529 , L531;
end;
end;
thus L535: thesis by L512;
end;
L536: 1 <= ( C75 + 1 ) by NAT_1:12;
L537: 1 in ( Seg ( len C76 ) ) by L536 , L484;
L538: 1 in ( dom C76 ) by L537 , FINSEQ_1:def 3;
L539: ( D44 . 1 ) = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) by L538 , L485 , FINSEQ_1:def 7;
thus L540: thesis by L539 , L507 , L508;
end;
case L541: ( C75 + 1 ) >= C69;
thus L542: thesis by L541;
end;
end;
thus L544: thesis by L482;
end;
L545: C69 < ( C69 + 1 ) by NAT_1:13;
L546: ( C69 - 1 ) < ( ( C69 + 1 ) - 1 ) by L545 , XREAL_1:14;
L547: ( C70 . C72 ) = H1(C72) by L429
.= ( 0. C68 ) by L467 , FUNCOP_1:def 8;
L548: ( C69 - 1 ) = ( C69 -' 1 ) by L426 , XREAL_1:233;
L549: (( len D39 ) = 1 & ( D39 . 1 ) = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 )) by FINSEQ_1:40;
L550: S4[ ( 0 ) ] by L549 , L473;
L551: (for B104 being (Element of ( NAT )) holds S4[ B104 ]) from NAT_1:sch 1(L550 , L480);
consider C80 being (FinSequence of C68) such that L552: ( len C80 ) = ( ( C69 -' 1 ) + 1 ) and L553: ( C80 . 1 ) = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) and L554: (for B105 being (Element of ( NAT )) holds ((( 0 ) <> B105 & B105 < ( ( C69 -' 1 ) + 1 ) & B105 < C69) implies ( C80 . ( B105 + 1 ) ) = ( (the multF of C68) . (( C80 . B105 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( B105 + 1 ) )) ))) by L551 , L548 , L546;
defpred S6[ set , set ] means (($1 in ( Seg C69 ) implies $2 = ( C80 . $1 )) & ((not $1 in ( Seg C69 )) implies $2 = ( 0. C68 )));
L555: (for B106 being (Element of D37) holds (ex B107 being (Element of C68) st S6[ B106 , B107 ]))
proof
let C81 being (Element of D37);
L556:
now
per cases ;
case L557: C81 in ( Seg C69 );
L558: C81 in ( dom C80 ) by L557 , L548 , L552 , FINSEQ_1:def 3;
L559: (( rng C80 ) c= (the carrier of C68) & ( C80 . C81 ) in ( rng C80 )) by L558 , FINSEQ_1:def 4 , FUNCT_1:def 3;
thus L560: thesis by L559 , L557;
end;
case L561: (not C81 in ( Seg C69 ));
thus L562: thesis by L561;
end;
end;
thus L564: thesis by L556;
end;
L565: (ex B108 being (Function of D37 , (the carrier of C68)) st (for B109 being (Element of D37) holds S6[ B109 , ( B108 . B109 ) ])) from FUNCT_2:sch 3(L555);
consider C82 being (Function of ( NAT ) , (the carrier of C68)) such that L566: (for B110 being (Element of ( NAT )) holds ((B110 in ( Seg C69 ) implies ( C82 . B110 ) = ( C80 . B110 )) & ((not B110 in ( Seg C69 )) implies ( C82 . B110 ) = ( 0. C68 )))) by L565;
L567: C72 is (Permutation of ( Seg C69 )) by MATRIX_2:def 9;
L568: ( C72 . D40 ) in ( Seg C69 ) by L567 , L475 , L477 , FUNCT_2:5;
reconsider D45 = ( C72 . D40 ) as (Element of ( NAT )) by L568;
L569: ( Indices ( 1. (C68 , C69) ) ) = [: ( Seg C69 ) , ( Seg C69 ) :] by L426 , MATRIX_1:23;
L570: [ D40 , D45 ] in ( Indices ( 1. (C68 , C69) ) ) by L569 , L475 , L477 , L568 , ZFMISC_1:def 2;
L571: D40 <= C69 by L475 , L477 , FINSEQ_1:1;
L572: ( C69 -' D40 ) = ( C69 - D40 ) by L571 , XREAL_1:233;
L573: D40 in ( dom ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L475 , L477 , L469 , FINSEQ_1:def 3;
L574: ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . D40 ) = ( ( 1. (C68 , C69) ) * (D40 , D45) ) by L573 , MATRIX_3:def 7;
defpred S7[ (Element of ( NAT )) ] means ( C82 . ( D40 + $1 ) ) = ( 0. C68 );
L575: ( 0 ) < D40 by L474 , L477 , FINSEQ_1:1;
L576: (for B111 being (Element of ( NAT )) holds (S7[ B111 ] implies S7[ ( B111 + 1 ) ]))
proof
let C83 being (Element of ( NAT ));
L577: 1 <= ( 1 + ( D40 + C83 ) ) by NAT_1:12;
assume L578: S7[ C83 ];
L579:
now
per cases ;
case L580: ( ( D40 + C83 ) + 1 ) <= C69;
L581: 1 <= ( 1 + ( D40 + C83 ) ) by NAT_1:12;
L582: ( ( D40 + C83 ) + 1 ) in ( Seg ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) ) by L581 , L469 , L580;
L583: ( ( D40 + C83 ) + 1 ) in ( dom ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L582 , FINSEQ_1:def 3;
L584: ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( ( D40 + C83 ) + 1 ) ) in ( rng ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L583 , FUNCT_1:def 3;
L585: ( rng ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) c= (the carrier of C68) by FINSEQ_1:def 4;
reconsider D46 = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( ( D40 + C83 ) + 1 ) ) as (Element of C68) by L585 , L584;
L586: ( D40 + C83 ) < C69 by L580 , NAT_1:13;
L587: ( ( 0 ) + 1 ) <= ( D40 + C83 ) by L575 , NAT_1:13;
L588: ( D40 + C83 ) in ( Seg C69 ) by L587 , L586;
L589: ( ( D40 + C83 ) + 1 ) in ( Seg C69 ) by L577 , L580;
L590: ( C82 . ( ( D40 + C83 ) + 1 ) ) = ( C80 . ( ( D40 + C83 ) + 1 ) ) by L589 , L566
.= ( (the multF of C68) . (( C80 . ( D40 + C83 ) ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( ( D40 + C83 ) + 1 ) )) ) by L548 , L554 , L575 , L586
.= ( ( 0. C68 ) * D46 ) by L566 , L578 , L588
.= ( 0. C68 ) by VECTSP_1:6;
thus L591: thesis by L590;
end;
case L592: ( ( D40 + C83 ) + 1 ) > C69;
L593: (not ( D40 + ( C83 + 1 ) ) in ( Seg C69 )) by L592 , FINSEQ_1:1;
thus L594: thesis by L593 , L566;
end;
end;
thus L596: thesis by L579;
end;
L597: 1 in ( Seg C69 ) by L426;
L598: ( C82 . 1 ) = ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . 1 ) by L597 , L553 , L566;
L599: (for B112 being (Element of ( NAT )) holds ((( 0 ) <> B112 & B112 < ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) )) implies ( C82 . ( B112 + 1 ) ) = ( (the multF of C68) . (( C82 . B112 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( B112 + 1 ) )) )))
proof
let C84 being (Element of ( NAT ));
assume that
L600: ( 0 ) <> C84
and
L601: C84 < ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) );
L602: ( C84 + 1 ) <= ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L601 , NAT_1:13;
L603: ( ( 0 ) + 1 ) <= C84 by L600 , NAT_1:13;
L604: C84 in ( Seg C69 ) by L603 , L469 , L601;
L605: 1 < ( C84 + 1 ) by L603 , NAT_1:13;
L606: ( C84 + 1 ) in ( Seg C69 ) by L605 , L469 , L602;
L607: ( C82 . ( C84 + 1 ) ) = ( C80 . ( C84 + 1 ) ) by L606 , L566;
L608: ( C80 . ( C84 + 1 ) ) = ( (the multF of C68) . (( C80 . C84 ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . ( C84 + 1 ) )) ) by L469 , L548 , L554 , L600 , L601;
thus L609: thesis by L608 , L566 , L607 , L604;
end;
L610: 1 <= D40 by L474 , L477 , FINSEQ_1:1;
L611:
now
per cases ;
case L612: D40 <= 1;
L613: D40 = 1 by L612 , L610 , XXREAL_0:1;
thus L614: S7[ ( 0 ) ] by L613 , L479 , L574 , L570 , L598 , MATRIX_1:def 11;
end;
case L615: D40 > 1;
reconsider D47 = ( C82 . ( D40 -' 1 ) ) as (Element of C68);
L616: D40 < ( D40 + 1 ) by NAT_1:13;
L617: ( D40 - 1 ) < ( ( D40 + 1 ) - 1 ) by L616 , XREAL_1:14;
L618: D40 <= C69 by L475 , L477 , FINSEQ_1:1;
L619: ( D40 - 1 ) < ( len ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) ) by L618 , L469 , L617 , XXREAL_0:2;
L620: ( D40 -' 1 ) = ( D40 - 1 ) by L615 , XREAL_1:233;
L621: ( ( D40 -' 1 ) + 1 ) = D40 by L620;
L622: ( D40 - 1 ) > ( 1 - 1 ) by L615 , XREAL_1:14;
L623: ( C82 . D40 ) = ( (the multF of C68) . (( C82 . ( D40 -' 1 ) ) , ( ( Path_matrix (C72 , ( 1. (C68 , C69) )) ) . D40 )) ) by L622 , L599 , L619 , L621
.= ( D47 * ( 0. C68 ) ) by L479 , L574 , L570 , MATRIX_1:def 11
.= ( 0. C68 ) by VECTSP_1:6;
thus L624: S7[ ( 0 ) ] by L623;
end;
end;
L626: S7[ ( 0 ) ] by L611;
L627: (for B113 being (Element of ( NAT )) holds S7[ B113 ]) from NAT_1:sch 1(L626 , L576);
L628: S7[ ( C69 -' D40 ) ] by L627;
thus L629: thesis by L628 , L426 , L439 , L547 , L469 , L598 , L599 , L572 , FINSOP_1:2;
end;
end;
thus L631: thesis by L452;
end;
thus L632: thesis by L433 , MATRIX_3:def 8;
end;
deffunc H2(set) = ( IFIN (( idseq C69 ) , $1 , ( 1_ C68 ) , ( 0. C68 )) );
set D48 = (the addF of C68);
set D49 = ( Path_product ( 1. (C68 , C69) ) );
set D50 = ( FinOmega ( Permutations C69 ) );
L633: (for B114 being set holds (B114 in ( Fin D35 ) implies H2(B114) in D36))
proof
let C85 being set;
assume L634: C85 in ( Fin D35 );
L635:
now
per cases ;
case L636: ( idseq C69 ) in C85;
L637: H2(C85) = ( 1_ C68 ) by L636 , L423;
thus L638: thesis by L637;
end;
case L639: (not ( idseq C69 ) in C85);
L640: H2(C85) = ( 0. C68 ) by L639 , L423;
thus L641: thesis by L640;
end;
end;
thus L643: thesis by L635;
end;
L644: (ex B115 being (Function of ( Fin D35 ) , D36) st (for B116 being set holds (B116 in ( Fin D35 ) implies ( B115 . B116 ) = H2(B116)))) from FUNCT_2:sch 2(L633);
consider C86 being (Function of ( Fin D35 ) , D36) such that L645: (for B117 being set holds (B117 in ( Fin D35 ) implies ( C86 . B117 ) = H2(B117))) by L644;
L646: ( dom C70 ) = ( Permutations C69 ) by FUNCT_2:def 1;
L647: ( dom ( Path_product ( 1. (C68 , C69) ) ) ) = ( dom C70 ) by L646 , FUNCT_2:def 1;
L648: ( Path_product ( 1. (C68 , C69) ) ) = C70 by L647 , L431 , FUNCT_1:2;
L649: (for B118 being (Element of ( Fin D35 )) holds ((B118 c= D50 & B118 <> ( {} )) implies (for B119 being (Element of D35) holds (B119 in ( D50 \ B118 ) implies ( C86 . ( B118 \/ { B119 } ) ) = ( D48 . (( C86 . B118 ) , ( D49 . B119 )) )))))
proof
let C87 being (Element of ( Fin D35 ));
assume that
L650: C87 c= D50
and
L651: C87 <> ( {} );
thus L652: (for B120 being (Element of D35) holds (B120 in ( D50 \ C87 ) implies ( C86 . ( C87 \/ { B120 } ) ) = ( D48 . (( C86 . C87 ) , ( D49 . B120 )) )))
proof
let C88 being (Element of D35);
assume L653: C88 in ( D50 \ C87 );
L654:
now
assume L655: (not ( idseq C69 ) in ( C87 \/ { C88 } ));
thus L656: ( C86 . ( C87 \/ { C88 } ) ) = ( IFIN (( idseq C69 ) , ( C87 \/ {. C88 .} ) , ( 1_ C68 ) , ( 0. C68 )) ) by L645
.= ( 0. C68 ) by L655 , L423;
end;
L657: ( 0. C68 ) is_a_unity_wrt D48 by FVSUM_1:6;
L658:
now
assume L659: (not ( idseq C69 ) in C87);
thus L660: ( C86 . C87 ) = ( IFIN (( idseq C69 ) , C87 , ( 1_ C68 ) , ( 0. C68 )) ) by L645
.= ( 0. C68 ) by L659 , L423;
end;
L661:
now
assume L662: (not ( idseq C69 ) in ( C87 \/ { C88 } ));
L663: (not ( idseq C69 ) in { C88 }) by L662 , XBOOLE_0:def 3;
L664: (not ( idseq C69 ) = C88) by L663 , TARSKI:def 1;
L665: ( D49 . C88 ) = H1(C88) by L429 , L648
.= ( 0. C68 ) by L664 , FUNCOP_1:def 8;
thus L666: ( D48 . (( C86 . C87 ) , ( D49 . C88 )) ) = ( 0. C68 ) by L665 , L658 , L657 , L662 , BINOP_1:3 , XBOOLE_0:def 3;
end;
L667:
now
assume L668: ( idseq C69 ) in C87;
thus L669: ( C86 . C87 ) = ( IFIN (( idseq C69 ) , C87 , ( 1_ C68 ) , ( 0. C68 )) ) by L645
.= ( 1_ C68 ) by L668 , L423;
end;
L670:
now
assume L671: ( idseq C69 ) in ( C87 \/ { C88 } );
L672: (( idseq C69 ) in C87 or ( idseq C69 ) in { C88 }) by L671 , XBOOLE_0:def 3;
L673:
now
per cases  by L672 , TARSKI:def 1;
case L674: ( idseq C69 ) in C87;
L675: (not C88 in C87) by L653 , XBOOLE_0:def 5;
L676: ( D49 . C88 ) = H1(C88) by L429 , L648
.= ( 0. C68 ) by L674 , L675 , FUNCOP_1:def 8;
thus L677: ( D48 . (( C86 . C87 ) , ( D49 . C88 )) ) = ( 1_ C68 ) by L676 , L667 , L657 , L674 , BINOP_1:3;
end;
case L678: ( idseq C69 ) = C88;
L679: ( D49 . C88 ) = H1(C88) by L429 , L648
.= ( 1_ C68 ) by L678 , FUNCOP_1:def 8;
thus L680: ( D48 . (( C86 . C87 ) , ( D49 . C88 )) ) = ( 1_ C68 ) by L679 , L653 , L658 , L657 , L678 , BINOP_1:3 , XBOOLE_0:def 5;
end;
end;
thus L682: ( D48 . (( C86 . C87 ) , ( D49 . C88 )) ) = ( 1_ C68 ) by L673;
end;
L683:
now
assume L684: ( idseq C69 ) in ( C87 \/ { C88 } );
thus L685: ( C86 . ( C87 \/ { C88 } ) ) = ( IFIN (( idseq C69 ) , ( C87 \/ {. C88 .} ) , ( 1_ C68 ) , ( 0. C68 )) ) by L645
.= ( 1_ C68 ) by L684 , L423;
end;
thus L686: thesis by L683 , L654 , L670 , L661;
end;

end;
L653: (for B121 being (Element of D35) holds ( C86 . { B121 } ) = ( D49 . B121 ))
proof
let C89 being (Element of D35);
L654:
now
per cases ;
case L655: C89 = ( idseq C69 );
L656: ( idseq C69 ) in { C89 } by L655 , TARSKI:def 1;
L657: ( IFIN (( idseq C69 ) , { C89 } , ( 1_ C68 ) , ( 0. C68 )) ) = ( 1_ C68 ) by L656 , L423;
L658: ( C70 . C89 ) = H1(C89) by L429
.= ( 1_ C68 ) by L655 , FUNCOP_1:def 8;
thus L659: ( C86 . {. C89 .} ) = ( C70 . C89 ) by L658 , L645 , L657;
end;
case L660: C89 <> ( idseq C69 );
L661: (not ( idseq C69 ) in { C89 }) by L660 , TARSKI:def 1;
L662: ( IFIN (( idseq C69 ) , { C89 } , ( 1_ C68 ) , ( 0. C68 )) ) = ( 0. C68 ) by L661 , L423;
L663: ( C70 . C89 ) = H1(C89) by L429
.= ( 0. C68 ) by L660 , FUNCOP_1:def 8;
thus L664: ( C86 . {. C89 .} ) = ( C70 . C89 ) by L663 , L645 , L662;
end;
end;
thus L666: thesis by L654 , L647 , L431 , FUNCT_1:2;
end;
L667: (for B122 being (Element of D36) holds (B122 is_a_unity_wrt D48 implies ( C86 . ( {} ) ) = B122))
proof
let C90 being (Element of D36);
assume L668: C90 is_a_unity_wrt D48;
L669: ( D48 . (( 0. C68 ) , C90) ) = ( 0. C68 ) by L668 , BINOP_1:3;
L670: ( 0. C68 ) is_a_unity_wrt D48 by FVSUM_1:6;
L671: ( D48 . (( 0. C68 ) , C90) ) = C90 by L670 , BINOP_1:3;
L672: ( IFIN (( idseq C69 ) , ( {} ) , ( 1_ C68 ) , ( 0. C68 )) ) = ( 0. C68 ) by L423;
thus L673: thesis by L672 , L645 , L669 , L671 , FINSUB_1:7;
end;
L674:
now
assume L675: ( idseq C69 ) in D50;
thus L676: ( C86 . D50 ) = ( IFIN (( idseq C69 ) , D50 , ( 1_ C68 ) , ( 0. C68 )) ) by L645
.= ( 1_ C68 ) by L675 , L423;
end;
L677: ( idseq C69 ) is (Element of ( Group_of_Perm C69 )) by MATRIX_2:20;
L678: (D50 = ( Permutations C69 ) & ( idseq C69 ) in (the carrier of ( Group_of_Perm C69 ))) by L677 , MATRIX_2:26 , MATRIX_2:def 14;
L679: ( (the addF of C68) $$ (( FinOmega ( Permutations C69 ) ) , ( Path_product ( 1. (C68 , C69) ) )) ) = ( 1_ C68 ) by L678 , L674 , L667 , L653 , L649 , MATRIX_2:def 10 , SETWISEO:def 3;
thus L680: thesis by L679 , MATRIX_3:def 9;
end;
definition
let C91 being Nat;
let C92 being Field;
let C93 being (Matrix of C91 , C92);
redefine attr C93 is  diagonal
means
:L681: (for B123 , B124 being (Element of ( NAT )) holds ((B123 in ( Seg C91 ) & B124 in ( Seg C91 ) & B123 <> B124) implies ( C93 * (B123 , B124) ) = ( 0. C92 )));
compatibility
proof
thus L682:now
assume L683: C93 is  diagonal;
let C94 , C95 being (Element of ( NAT ));
assume that
L684: (C94 in ( Seg C91 ) & C95 in ( Seg C91 ))
and
L685: C94 <> C95;
L686: [ C94 , C95 ] in [: ( Seg C91 ) , ( Seg C91 ) :] by L684 , ZFMISC_1:def 2;
L687: [ C94 , C95 ] in ( Indices C93 ) by L686 , MATRIX_1:24;
thus L688: ( C93 * (C94 , C95) ) = ( 0. C92 ) by L687 , L683 , L685 , MATRIX_1:def 14;
end;
assume L689: (for B125 , B126 being (Element of ( NAT )) holds ((B125 in ( Seg C91 ) & B126 in ( Seg C91 ) & B125 <> B126) implies ( C93 * (B125 , B126) ) = ( 0. C92 )));
let C96 , C97 being Nat;
assume that
L690: [ C96 , C97 ] in ( Indices C93 )
and
L691: ( C93 * (C96 , C97) ) <> ( 0. C92 );
L692: [ C96 , C97 ] in [: ( Seg C91 ) , ( Seg C91 ) :] by L690 , MATRIX_1:24;
L693: (C96 in ( Seg C91 ) & C97 in ( Seg C91 )) by L692 , ZFMISC_1:87;
thus L694: thesis by L693 , L689 , L691;
end;
end;
theorem
L696: (for B127 being Field holds (for B128 being (Element of ( NAT )) holds (for B129 being (Matrix of B128 , B127) holds ((B128 >= 1 & B129 is  diagonal) implies ( Det B129 ) = ( (the multF of B127) $$ ( diagonal_of_Matrix B129 ) )))))
proof
let C98 being Field;
let C99 being (Element of ( NAT ));
let C100 being (Matrix of C99 , C98);
assume that
L697: C99 >= 1
and
L698: C100 is  diagonal;
set D51 = ( (the multF of C98) $$ ( diagonal_of_Matrix C100 ) );
set D52 = ( Permutations C99 );
set D53 = (the carrier of C98);
reconsider D54 = ( idseq C99 ) as (Permutation of ( Seg C99 ));
L699: ( len ( diagonal_of_Matrix C100 ) ) = C99 by MATRIX_3:def 10;
deffunc H3(set) = ( IFEQ (( idseq C99 ) , $1 , D51 , ( 0. C98 )) );
L700: (for B130 being set holds (B130 in D52 implies H3(B130) in D53));
L701: (ex B131 being (Function of D52 , D53) st (for B132 being set holds (B132 in D52 implies ( B131 . B132 ) = H3(B132)))) from FUNCT_2:sch 2(L700);
consider C101 being (Function of D52 , D53) such that L702: (for B133 being set holds (B133 in D52 implies ( C101 . B133 ) = H3(B133))) by L701;
L703: D54 is  even by MATRIX_2:25;
L704: (for B134 being set holds (B134 in ( dom ( Path_product C100 ) ) implies ( ( Path_product C100 ) . B134 ) = ( C101 . B134 )))
proof
let C102 being set;
assume L705: C102 in ( dom ( Path_product C100 ) );
L706: (for B135 being (Element of ( Permutations C99 )) holds ( C101 . B135 ) = ( - (( (the multF of C98) $$ ( Path_matrix (B135 , C100) ) ) , B135) ))
proof
let C103 being (Element of ( Permutations C99 ));
L707:
now
per cases ;
suppose L708: C103 is  even;

thus L709: ( - (( 0. C98 ) , C103) ) = ( 0. C98 ) by L708 , MATRIX_2:def 13;
end;
suppose L710: C103 is  odd;

L711: ( - (( 0. C98 ) , C103) ) = ( - ( 0. C98 ) ) by L710 , MATRIX_2:def 13
.= ( 0. C98 ) by RLVECT_1:12;
thus L712: ( - (( 0. C98 ) , C103) ) = ( 0. C98 ) by L711;
end;
end;
L714:
now
per cases ;
case L715: C103 = ( idseq C99 );
L716: (for R3 being Nat holds (for R4 being Nat holds ((R3 in ( dom ( diagonal_of_Matrix C100 ) ) & R4 = ( C103 . R3 )) implies ( ( diagonal_of_Matrix C100 ) . R3 ) = ( C100 * (R3 , R4) ))))
proof
let R3 being Nat;
let R4 being Nat;
assume that
L717: R3 in ( dom ( diagonal_of_Matrix C100 ) )
and
L718: R4 = ( C103 . R3 );
L719: R3 in ( Seg C99 ) by L699 , L717 , FINSEQ_1:def 3;
L720: ( C103 . R3 ) = R3 by L719 , L715 , FUNCT_1:17;
thus L721: thesis by L720 , L718 , L719 , MATRIX_3:def 10;
end;
L722: ( len ( Permutations C99 ) ) = C99 by MATRIX_2:18;
L723: ( - (( (the multF of C98) $$ ( Path_matrix (C103 , C100) ) ) , C103) ) = ( (the multF of C98) $$ ( Path_matrix (C103 , C100) ) ) by L722 , L703 , L715 , MATRIX_2:def 13;
L724: ( C101 . C103 ) = H3(C103) by L702
.= D51 by L715 , FUNCOP_1:def 8;
thus L725: thesis by L724 , L699 , L723 , L716 , MATRIX_3:def 7;
end;
case L726: C103 <> ( idseq C99 );
reconsider D55 = ( NAT ) as non  empty set;
defpred S8[ (Element of ( NAT )) ] means ($1 < C99 implies (ex B136 being (FinSequence of C98) st (( len B136 ) = ( $1 + 1 ) & ( B136 . 1 ) = ( ( Path_matrix (C103 , C100) ) . 1 ) & (for B137 being (Element of ( NAT )) holds ((( 0 ) <> B137 & B137 < ( $1 + 1 ) & B137 < C99) implies ( B136 . ( B137 + 1 ) ) = ( (the multF of C98) . (( B136 . B137 ) , ( ( Path_matrix (C103 , C100) ) . ( B137 + 1 ) )) ))))));
L727: ( rng ( Path_matrix (C103 , C100) ) ) c= (the carrier of C98) by FINSEQ_1:def 4;
L728: ( len ( Path_matrix (C103 , C100) ) ) = C99 by MATRIX_3:def 7;
L729: 1 in ( Seg ( len ( Path_matrix (C103 , C100) ) ) ) by L728 , L697;
L730: 1 in ( dom ( Path_matrix (C103 , C100) ) ) by L729 , FINSEQ_1:def 3;
L731: ( ( Path_matrix (C103 , C100) ) . 1 ) in ( rng ( Path_matrix (C103 , C100) ) ) by L730 , FUNCT_1:def 3;
reconsider D56 = ( ( Path_matrix (C103 , C100) ) . 1 ) as (Element of C98) by L731 , L727;
reconsider D57 = <* D56 *> as (FinSequence of C98);
L732: (for B138 being (Element of ( NAT )) holds ((( 0 ) <> B138 & B138 < ( ( 0 ) + 1 ) & B138 < C99) implies ( D57 . ( B138 + 1 ) ) = ( (the multF of C98) . (( D57 . B138 ) , ( ( Path_matrix (C103 , C100) ) . ( B138 + 1 ) )) ))) by NAT_1:13;
L733: (for B139 being (Element of ( NAT )) holds (S8[ B139 ] implies S8[ ( B139 + 1 ) ]))
proof
let C104 being (Element of ( NAT ));
assume L734: S8[ C104 ];
L735:
now
per cases ;
case L736: ( C104 + 1 ) < C99;
consider C105 being (FinSequence of C98) such that L737: ( len C105 ) = ( C104 + 1 ) and L738: ( C105 . 1 ) = ( ( Path_matrix (C103 , C100) ) . 1 ) and L739: (for B140 being (Element of ( NAT )) holds ((( 0 ) <> B140 & B140 < ( C104 + 1 ) & B140 < C99) implies ( C105 . ( B140 + 1 ) ) = ( (the multF of C98) . (( C105 . B140 ) , ( ( Path_matrix (C103 , C100) ) . ( B140 + 1 ) )) ))) by L736 , L734 , NAT_1:12;
defpred S9[ set , set ] means (($1 in ( Seg ( C104 + 1 ) ) implies $2 = ( C105 . $1 )) & ((not $1 in ( Seg ( C104 + 1 ) )) implies $2 = ( 0. C98 )));
L740: (for B141 being set holds (B141 in ( NAT ) implies (ex B142 being set st (B142 in (the carrier of C98) & S9[ B141 , B142 ]))))
proof
let C106 being set;
assume L741: C106 in ( NAT );
L742:
now
per cases ;
case L743: C106 in ( Seg ( C104 + 1 ) );
reconsider D58 = C106 as (Element of ( NAT )) by L743;
L744: D58 in ( dom C105 ) by L737 , L743 , FINSEQ_1:def 3;
L745: ( C105 . D58 ) in ( rng C105 ) by L744 , FUNCT_1:def 3;
L746: ( rng C105 ) c= (the carrier of C98) by FINSEQ_1:def 4;
reconsider D59 = ( C105 . D58 ) as (Element of C98) by L746 , L745;
L747: (C106 in ( Seg ( C104 + 1 ) ) implies D59 = ( C105 . C106 ));
thus L748: thesis by L747 , L743;
end;
case L749: (not C106 in ( Seg ( C104 + 1 ) ));
thus L750: thesis by L749;
end;
end;
thus L752: thesis by L742;
end;
L753: (ex B143 being (Function of ( NAT ) , (the carrier of C98)) st (for B144 being set holds (B144 in ( NAT ) implies S9[ B144 , ( B143 . B144 ) ]))) from FUNCT_2:sch 1(L740);
consider C107 being (Function of ( NAT ) , (the carrier of C98)) such that L754: (for B145 being set holds (B145 in ( NAT ) implies S9[ B145 , ( C107 . B145 ) ])) by L753;
L755: (1 <= ( ( C104 + 1 ) + 1 ) & ( ( C104 + 1 ) + 1 ) <= C99) by L736 , NAT_1:12 , NAT_1:13;
L756: ( ( C104 + 1 ) + 1 ) in ( Seg ( len ( Path_matrix (C103 , C100) ) ) ) by L755 , L728;
L757: ( ( C104 + 1 ) + 1 ) in ( dom ( Path_matrix (C103 , C100) ) ) by L756 , FINSEQ_1:def 3;
L758: (( rng ( Path_matrix (C103 , C100) ) ) c= (the carrier of C98) & ( ( Path_matrix (C103 , C100) ) . ( ( C104 + 1 ) + 1 ) ) in ( rng ( Path_matrix (C103 , C100) ) )) by L757 , FINSEQ_1:def 4 , FUNCT_1:def 3;
L759: [ ( C107 . ( C104 + 1 ) ) , ( ( Path_matrix (C103 , C100) ) . ( ( C104 + 1 ) + 1 ) ) ] in [: (the carrier of C98) , (the carrier of C98) :] by L758 , ZFMISC_1:def 2;
reconsider D60 = ( (the multF of C98) . (( C107 . ( C104 + 1 ) ) , ( ( Path_matrix (C103 , C100) ) . ( ( C104 + 1 ) + 1 ) )) ) as (Element of C98) by L759 , FUNCT_2:5;
reconsider D61 = ( C105 ^ <* D60 *> ) as (FinSequence of C98);
L760: ( len D61 ) = ( ( len C105 ) + ( len <* D60 *> ) ) by FINSEQ_1:22
.= ( ( C104 + 1 ) + 1 ) by L737 , FINSEQ_1:40;
L761: (for B146 being (Element of ( NAT )) holds ((( 0 ) <> B146 & B146 < ( ( C104 + 1 ) + 1 ) & B146 < C99) implies ( D61 . ( B146 + 1 ) ) = ( (the multF of C98) . (( D61 . B146 ) , ( ( Path_matrix (C103 , C100) ) . ( B146 + 1 ) )) )))
proof
let C108 being (Element of ( NAT ));
assume that
L762: ( 0 ) <> C108
and
L763: C108 < ( ( C104 + 1 ) + 1 )
and
L764: C108 < C99;
L765:
now
per cases ;
case L766: C108 < ( C104 + 1 );
L767: (1 <= ( C108 + 1 ) & ( C108 + 1 ) <= ( C104 + 1 )) by L766 , NAT_1:12 , NAT_1:13;
L768: ( C108 + 1 ) in ( Seg ( len C105 ) ) by L767 , L737;
L769: ( C108 + 1 ) in ( dom C105 ) by L768 , FINSEQ_1:def 3;
L770: ( C105 . ( C108 + 1 ) ) = ( D61 . ( C108 + 1 ) ) by L769 , FINSEQ_1:def 7;
L771: ( ( 0 ) + 1 ) <= C108 by L762 , NAT_1:13;
L772: C108 in ( Seg ( len C105 ) ) by L771 , L737 , L766;
L773: C108 in ( dom C105 ) by L772 , FINSEQ_1:def 3;
L774: ( C105 . ( C108 + 1 ) ) = ( (the multF of C98) . (( C105 . C108 ) , ( ( Path_matrix (C103 , C100) ) . ( C108 + 1 ) )) ) by L739 , L762 , L764 , L766;
thus L775: thesis by L774 , L770 , L773 , FINSEQ_1:def 7;
end;
case L776: C108 >= ( C104 + 1 );
L777: ( C108 + 1 ) <= ( ( C104 + 1 ) + 1 ) by L763 , NAT_1:13;
L778: ( C108 + 1 ) > ( C104 + 1 ) by L776 , NAT_1:13;
L779: ( C108 + 1 ) >= ( ( C104 + 1 ) + 1 ) by L778 , NAT_1:13;
L780: ( C108 + 1 ) = ( ( C104 + 1 ) + 1 ) by L779 , L777 , XXREAL_0:1;
L781: 1 <= ( C104 + 1 ) by NAT_1:12;
L782: ( C104 + 1 ) in ( Seg ( C104 + 1 ) ) by L781;
L783: ( C104 + 1 ) in ( dom C105 ) by L782 , L737 , FINSEQ_1:def 3;
L784: ( D61 . ( C104 + 1 ) ) = ( C105 . ( C104 + 1 ) ) by L783 , FINSEQ_1:def 7;
L785: ( D61 . ( C108 + 1 ) ) = ( <* D60 *> . ( ( C108 + 1 ) - ( C104 + 1 ) ) ) by L737 , L760 , L778 , L777 , FINSEQ_1:24
.= D60 by L780 , FINSEQ_1:def 8;
thus L786: thesis by L785 , L754 , L780 , L782 , L784;
end;
end;
thus L788: thesis by L765;
end;
L789: 1 <= ( C104 + 1 ) by NAT_1:12;
L790: 1 in ( Seg ( len C105 ) ) by L789 , L737;
L791: 1 in ( dom C105 ) by L790 , FINSEQ_1:def 3;
L792: ( D61 . 1 ) = ( ( Path_matrix (C103 , C100) ) . 1 ) by L791 , L738 , FINSEQ_1:def 7;
thus L793: thesis by L792 , L760 , L761;
end;
case L794: ( C104 + 1 ) >= C99;
thus L795: thesis by L794;
end;
end;
thus L797: thesis by L735;
end;
L798: ( C101 . C103 ) = H3(C103) by L702
.= ( 0. C98 ) by L726 , FUNCOP_1:def 8;
L799: C99 < ( C99 + 1 ) by NAT_1:13;
L800: ( C99 - 1 ) < ( ( C99 + 1 ) - 1 ) by L799 , XREAL_1:14;
L801: ( dom C103 ) = ( Seg ( len ( Permutations C99 ) ) ) by FUNCT_2:52;
L802: ( dom C103 ) = ( Seg C99 ) by L801 , MATRIX_2:18;
L803: ( dom C103 ) = ( dom ( idseq C99 ) ) by L802 , RELAT_1:45;
consider C109 being set such that L804: C109 in ( dom C103 ) and L805: ( C103 . C109 ) <> ( ( idseq C99 ) . C109 ) by L803 , L726 , FUNCT_1:2;
L806: C109 in ( Seg C99 ) by L801 , L804 , MATRIX_2:18;
reconsider D62 = C109 as (Element of ( NAT )) by L801 , L804;
L807: ( C103 . D62 ) <> D62 by L802 , L804 , L805 , FUNCT_1:18;
L808: C103 is (Permutation of ( Seg C99 )) by MATRIX_2:def 9;
L809: ( C103 . D62 ) in ( Seg C99 ) by L808 , L802 , L804 , FUNCT_2:5;
reconsider D63 = ( C103 . D62 ) as (Element of ( NAT )) by L809;
L810: ( C99 - 1 ) = ( C99 -' 1 ) by L697 , XREAL_1:233;
L811: (( len D57 ) = 1 & ( D57 . 1 ) = ( ( Path_matrix (C103 , C100) ) . 1 )) by FINSEQ_1:40;
L812: S8[ ( 0 ) ] by L811 , L732;
L813: (for B147 being (Element of ( NAT )) holds S8[ B147 ]) from NAT_1:sch 1(L812 , L733);
consider C110 being (FinSequence of C98) such that L814: ( len C110 ) = ( ( C99 -' 1 ) + 1 ) and L815: ( C110 . 1 ) = ( ( Path_matrix (C103 , C100) ) . 1 ) and L816: (for B148 being (Element of ( NAT )) holds ((( 0 ) <> B148 & B148 < ( ( C99 -' 1 ) + 1 ) & B148 < C99) implies ( C110 . ( B148 + 1 ) ) = ( (the multF of C98) . (( C110 . B148 ) , ( ( Path_matrix (C103 , C100) ) . ( B148 + 1 ) )) ))) by L813 , L810 , L800;
defpred S10[ set , set ] means (($1 in ( Seg C99 ) implies $2 = ( C110 . $1 )) & ((not $1 in ( Seg C99 )) implies $2 = ( 0. C98 )));
L817: (for B149 being (Element of D55) holds (ex B150 being (Element of C98) st S10[ B149 , B150 ]))
proof
let C111 being (Element of D55);
L818:
now
per cases ;
case L819: C111 in ( Seg C99 );
L820: C111 in ( dom C110 ) by L819 , L810 , L814 , FINSEQ_1:def 3;
L821: (( rng C110 ) c= (the carrier of C98) & ( C110 . C111 ) in ( rng C110 )) by L820 , FINSEQ_1:def 4 , FUNCT_1:def 3;
thus L822: thesis by L821 , L819;
end;
case L823: (not C111 in ( Seg C99 ));
thus L824: thesis by L823;
end;
end;
thus L826: thesis by L818;
end;
L827: (ex B151 being (Function of D55 , (the carrier of C98)) st (for B152 being (Element of D55) holds S10[ B152 , ( B151 . B152 ) ])) from FUNCT_2:sch 3(L817);
consider C112 being (Function of ( NAT ) , (the carrier of C98)) such that L828: (for B153 being (Element of ( NAT )) holds ((B153 in ( Seg C99 ) implies ( C112 . B153 ) = ( C110 . B153 )) & ((not B153 in ( Seg C99 )) implies ( C112 . B153 ) = ( 0. C98 )))) by L827;
L829: (for B154 being (Element of ( NAT )) holds ((( 0 ) <> B154 & B154 < ( len ( Path_matrix (C103 , C100) ) )) implies ( C112 . ( B154 + 1 ) ) = ( (the multF of C98) . (( C112 . B154 ) , ( ( Path_matrix (C103 , C100) ) . ( B154 + 1 ) )) )))
proof
let C113 being (Element of ( NAT ));
assume that
L830: ( 0 ) <> C113
and
L831: C113 < ( len ( Path_matrix (C103 , C100) ) );
L832: ( C113 + 1 ) <= ( len ( Path_matrix (C103 , C100) ) ) by L831 , NAT_1:13;
L833: ( ( 0 ) + 1 ) <= C113 by L830 , NAT_1:13;
L834: C113 in ( Seg C99 ) by L833 , L728 , L831;
L835: 1 < ( C113 + 1 ) by L833 , NAT_1:13;
L836: ( C113 + 1 ) in ( Seg C99 ) by L835 , L728 , L832;
L837: ( C112 . ( C113 + 1 ) ) = ( C110 . ( C113 + 1 ) ) by L836 , L828;
L838: ( C110 . ( C113 + 1 ) ) = ( (the multF of C98) . (( C110 . C113 ) , ( ( Path_matrix (C103 , C100) ) . ( C113 + 1 ) )) ) by L728 , L810 , L816 , L830 , L831;
thus L839: thesis by L838 , L828 , L837 , L834;
end;
L840: D62 <= C99 by L802 , L804 , FINSEQ_1:1;
L841: ( C99 -' D62 ) = ( C99 - D62 ) by L840 , XREAL_1:233;
L842: D62 in ( dom ( Path_matrix (C103 , C100) ) ) by L806 , L728 , FINSEQ_1:def 3;
L843: ( ( Path_matrix (C103 , C100) ) . D62 ) = ( C100 * (D62 , D63) ) by L842 , MATRIX_3:def 7;
defpred S11[ (Element of ( NAT )) ] means ( C112 . ( D62 + $1 ) ) = ( 0. C98 );
L844: ( 0 ) < D62 by L801 , L804 , FINSEQ_1:1;
L845: (for B155 being (Element of ( NAT )) holds (S11[ B155 ] implies S11[ ( B155 + 1 ) ]))
proof
let C114 being (Element of ( NAT ));
L846: 1 <= ( 1 + ( D62 + C114 ) ) by NAT_1:12;
assume L847: S11[ C114 ];
L848:
now
per cases ;
case L849: ( ( D62 + C114 ) + 1 ) <= C99;
L850: 1 <= ( 1 + ( D62 + C114 ) ) by NAT_1:12;
L851: ( ( D62 + C114 ) + 1 ) in ( Seg ( len ( Path_matrix (C103 , C100) ) ) ) by L850 , L728 , L849;
L852: ( ( D62 + C114 ) + 1 ) in ( dom ( Path_matrix (C103 , C100) ) ) by L851 , FINSEQ_1:def 3;
L853: ( ( Path_matrix (C103 , C100) ) . ( ( D62 + C114 ) + 1 ) ) in ( rng ( Path_matrix (C103 , C100) ) ) by L852 , FUNCT_1:def 3;
L854: ( rng ( Path_matrix (C103 , C100) ) ) c= (the carrier of C98) by FINSEQ_1:def 4;
reconsider D64 = ( ( Path_matrix (C103 , C100) ) . ( ( D62 + C114 ) + 1 ) ) as (Element of C98) by L854 , L853;
L855: D62 <= ( D62 + C114 ) by NAT_1:12;
L856: ( 0 ) < ( D62 + C114 ) by L855 , L801 , L804 , FINSEQ_1:1;
L857: ( D62 + C114 ) < C99 by L849 , NAT_1:13;
L858: ( ( 0 ) + 1 ) <= ( D62 + C114 ) by L844 , NAT_1:13;
L859: ( D62 + C114 ) in ( Seg C99 ) by L858 , L857;
L860: ( ( D62 + C114 ) + 1 ) in ( Seg C99 ) by L846 , L849;
L861: ( C112 . ( ( D62 + C114 ) + 1 ) ) = ( C110 . ( ( D62 + C114 ) + 1 ) ) by L860 , L828
.= ( (the multF of C98) . (( C110 . ( D62 + C114 ) ) , ( ( Path_matrix (C103 , C100) ) . ( ( D62 + C114 ) + 1 ) )) ) by L810 , L816 , L857 , L856
.= ( ( 0. C98 ) * D64 ) by L828 , L847 , L859
.= ( 0. C98 ) by VECTSP_1:6;
thus L862: thesis by L861;
end;
case L863: ( ( D62 + C114 ) + 1 ) > C99;
L864: (not ( D62 + ( C114 + 1 ) ) in ( Seg C99 )) by L863 , FINSEQ_1:1;
thus L865: thesis by L864 , L828;
end;
end;
thus L867: thesis by L848;
end;
L868: 1 in ( Seg C99 ) by L697;
L869: ( C112 . 1 ) = ( ( Path_matrix (C103 , C100) ) . 1 ) by L868 , L815 , L828;
L870: 1 <= D62 by L801 , L804 , FINSEQ_1:1;
L871:
now
per cases ;
case L872: D62 <= 1;
L873: D62 = 1 by L872 , L870 , XXREAL_0:1;
thus L874: S11[ ( 0 ) ] by L873 , L698 , L806 , L807 , L809 , L843 , L869 , L681;
end;
case L875: D62 > 1;
reconsider D65 = ( C112 . ( D62 -' 1 ) ) as (Element of C98);
L876: D62 < ( D62 + 1 ) by NAT_1:13;
L877: ( D62 - 1 ) < ( ( D62 + 1 ) - 1 ) by L876 , XREAL_1:14;
L878: ( D62 - 1 ) < ( len ( Path_matrix (C103 , C100) ) ) by L877 , L840 , L728 , XXREAL_0:2;
L879: ( D62 -' 1 ) = ( D62 - 1 ) by L875 , XREAL_1:233;
L880: ( ( D62 -' 1 ) + 1 ) = D62 by L879;
L881: ( D62 - 1 ) > ( 1 - 1 ) by L875 , XREAL_1:14;
L882: ( C112 . D62 ) = ( (the multF of C98) . (( C112 . ( D62 -' 1 ) ) , ( ( Path_matrix (C103 , C100) ) . D62 )) ) by L881 , L829 , L878 , L880
.= ( D65 * ( 0. C98 ) ) by L698 , L806 , L807 , L809 , L843 , L681
.= ( 0. C98 ) by VECTSP_1:6;
thus L883: S11[ ( 0 ) ] by L882;
end;
end;
L885: S11[ ( 0 ) ] by L871;
L886: (for B156 being (Element of ( NAT )) holds S11[ B156 ]) from NAT_1:sch 1(L885 , L845);
L887: S11[ ( C99 -' D62 ) ] by L886;
thus L888: thesis by L887 , L697 , L707 , L798 , L728 , L869 , L829 , L841 , FINSOP_1:2;
end;
end;
thus L890: thesis by L714;
end;
thus L891: thesis by L706 , MATRIX_3:def 8;
end;
deffunc H4(set) = ( IFIN (( idseq C99 ) , $1 , D51 , ( 0. C98 )) );
set D66 = (the addF of C98);
set D67 = ( Path_product C100 );
set D68 = ( FinOmega ( Permutations C99 ) );
L892: (for B157 being set holds (B157 in ( Fin D52 ) implies H4(B157) in D53))
proof
let C115 being set;
assume L893: C115 in ( Fin D52 );
per cases ;
suppose L894: ( idseq C99 ) in C115;

L895: H4(C115) = D51 by L894 , L423;
thus L896: thesis by L895;
end;
suppose L897: (not ( idseq C99 ) in C115);

L898: H4(C115) = ( 0. C98 ) by L897 , L423;
thus L899: thesis by L898;
end;
end;
L901: (ex B158 being (Function of ( Fin D52 ) , D53) st (for B159 being set holds (B159 in ( Fin D52 ) implies ( B158 . B159 ) = H4(B159)))) from FUNCT_2:sch 2(L892);
consider C116 being (Function of ( Fin D52 ) , D53) such that L902: (for B160 being set holds (B160 in ( Fin D52 ) implies ( C116 . B160 ) = H4(B160))) by L901;
L903: ( dom C101 ) = ( Permutations C99 ) by FUNCT_2:def 1;
L904: ( dom ( Path_product C100 ) ) = ( dom C101 ) by L903 , FUNCT_2:def 1;
L905: ( Path_product C100 ) = C101 by L904 , L704 , FUNCT_1:2;
L906: (for B161 being (Element of ( Fin D52 )) holds ((B161 c= D68 & B161 <> ( {} )) implies (for B162 being (Element of D52) holds (B162 in ( D68 \ B161 ) implies ( C116 . ( B161 \/ { B162 } ) ) = ( D66 . (( C116 . B161 ) , ( D67 . B162 )) )))))
proof
let C117 being (Element of ( Fin D52 ));
assume that
L907: C117 c= D68
and
L908: C117 <> ( {} );
thus L909: (for B163 being (Element of D52) holds (B163 in ( D68 \ C117 ) implies ( C116 . ( C117 \/ { B163 } ) ) = ( D66 . (( C116 . C117 ) , ( D67 . B163 )) )))
proof
let C118 being (Element of D52);
assume L910: C118 in ( D68 \ C117 );
L911:
now
assume L912: (not ( idseq C99 ) in ( C117 \/ { C118 } ));
thus L913: ( C116 . ( C117 \/ { C118 } ) ) = ( IFIN (( idseq C99 ) , ( C117 \/ {. C118 .} ) , D51 , ( 0. C98 )) ) by L902
.= ( 0. C98 ) by L912 , L423;
end;
L914: ( 0. C98 ) is_a_unity_wrt D66 by FVSUM_1:6;
L915:
now
assume L916: (not ( idseq C99 ) in C117);
thus L917: ( C116 . C117 ) = ( IFIN (( idseq C99 ) , C117 , D51 , ( 0. C98 )) ) by L902
.= ( 0. C98 ) by L916 , L423;
end;
L918:
now
assume L919: (not ( idseq C99 ) in ( C117 \/ { C118 } ));
L920: (not ( idseq C99 ) in { C118 }) by L919 , XBOOLE_0:def 3;
L921: (not ( idseq C99 ) = C118) by L920 , TARSKI:def 1;
L922: ( D67 . C118 ) = H3(C118) by L702 , L905
.= ( 0. C98 ) by L921 , FUNCOP_1:def 8;
thus L923: ( D66 . (( C116 . C117 ) , ( D67 . C118 )) ) = ( 0. C98 ) by L922 , L915 , L914 , L919 , BINOP_1:3 , XBOOLE_0:def 3;
end;
L924:
now
assume L925: ( idseq C99 ) in C117;
thus L926: ( C116 . C117 ) = ( IFIN (( idseq C99 ) , C117 , D51 , ( 0. C98 )) ) by L902
.= D51 by L925 , L423;
end;
L927:
now
assume L928: ( idseq C99 ) in ( C117 \/ { C118 } );
L929: (( idseq C99 ) in C117 or ( idseq C99 ) in { C118 }) by L928 , XBOOLE_0:def 3;
L930:
now
per cases  by L929 , TARSKI:def 1;
case L931: ( idseq C99 ) in C117;
L932: (not C118 in C117) by L910 , XBOOLE_0:def 5;
L933: ( D67 . C118 ) = H3(C118) by L702 , L905
.= ( 0. C98 ) by L931 , L932 , FUNCOP_1:def 8;
thus L934: ( D66 . (( C116 . C117 ) , ( D67 . C118 )) ) = D51 by L933 , L924 , L914 , L931 , BINOP_1:3;
end;
case L935: ( idseq C99 ) = C118;
L936: ( D67 . C118 ) = H3(C118) by L702 , L905
.= D51 by L935 , FUNCOP_1:def 8;
thus L937: ( D66 . (( C116 . C117 ) , ( D67 . C118 )) ) = D51 by L936 , L910 , L915 , L914 , L935 , BINOP_1:3 , XBOOLE_0:def 5;
end;
end;
thus L939: ( D66 . (( C116 . C117 ) , ( D67 . C118 )) ) = D51 by L930;
end;
L940:
now
assume L941: ( idseq C99 ) in ( C117 \/ { C118 } );
thus L942: ( C116 . ( C117 \/ { C118 } ) ) = ( IFIN (( idseq C99 ) , ( C117 \/ {. C118 .} ) , D51 , ( 0. C98 )) ) by L902
.= D51 by L941 , L423;
end;
thus L943: thesis by L940 , L911 , L927 , L918;
end;

end;
L910: (for B164 being (Element of D52) holds ( C116 . { B164 } ) = ( D67 . B164 ))
proof
let C119 being (Element of D52);
L911:
now
per cases ;
case L912: C119 = ( idseq C99 );
L913: ( idseq C99 ) in { C119 } by L912 , TARSKI:def 1;
L914: ( IFIN (( idseq C99 ) , { C119 } , D51 , ( 0. C98 )) ) = D51 by L913 , L423;
L915: ( C101 . C119 ) = H3(C119) by L702
.= D51 by L912 , FUNCOP_1:def 8;
thus L916: ( C116 . {. C119 .} ) = ( C101 . C119 ) by L915 , L902 , L914;
end;
case L917: C119 <> ( idseq C99 );
L918: (not ( idseq C99 ) in { C119 }) by L917 , TARSKI:def 1;
L919: ( IFIN (( idseq C99 ) , { C119 } , D51 , ( 0. C98 )) ) = ( 0. C98 ) by L918 , L423;
L920: ( C101 . C119 ) = H3(C119) by L702
.= ( 0. C98 ) by L917 , FUNCOP_1:def 8;
thus L921: ( C116 . {. C119 .} ) = ( C101 . C119 ) by L920 , L902 , L919;
end;
end;
thus L923: thesis by L911 , L904 , L704 , FUNCT_1:2;
end;
L924: (for B165 being (Element of D53) holds (B165 is_a_unity_wrt D66 implies ( C116 . ( {} ) ) = B165))
proof
let C120 being (Element of D53);
assume L925: C120 is_a_unity_wrt D66;
L926: ( D66 . (( 0. C98 ) , C120) ) = ( 0. C98 ) by L925 , BINOP_1:3;
L927: ( 0. C98 ) is_a_unity_wrt D66 by FVSUM_1:6;
L928: ( D66 . (( 0. C98 ) , C120) ) = C120 by L927 , BINOP_1:3;
L929: ( IFIN (( idseq C99 ) , ( {} ) , D51 , ( 0. C98 )) ) = ( 0. C98 ) by L423;
thus L930: thesis by L929 , L902 , L926 , L928 , FINSUB_1:7;
end;
L931:
now
assume L932: ( idseq C99 ) in D68;
thus L933: ( C116 . D68 ) = ( IFIN (( idseq C99 ) , D68 , D51 , ( 0. C98 )) ) by L902
.= ( (the multF of C98) $$ ( diagonal_of_Matrix C100 ) ) by L932 , L423;
end;
L934: ( idseq C99 ) is (Element of ( Group_of_Perm C99 )) by MATRIX_2:20;
L935: (D68 = ( Permutations C99 ) & ( idseq C99 ) in (the carrier of ( Group_of_Perm C99 ))) by L934 , MATRIX_2:26 , MATRIX_2:def 14;
L936: ( (the addF of C98) $$ (( FinOmega ( Permutations C99 ) ) , ( Path_product C100 )) ) = ( (the multF of C98) $$ ( diagonal_of_Matrix C100 ) ) by L935 , L931 , L924 , L910 , L906 , MATRIX_2:def 10 , SETWISEO:def 3;
thus L937: thesis by L936 , MATRIX_3:def 9;
end;
theorem
L938: (for R2 being Nat holds (for B166 being (Element of ( Permutations R2 )) holds ( B166 " ) is (Element of ( Permutations R2 ))))
proof
let R2 being Nat;
let C121 being (Element of ( Permutations R2 ));
L939: ( C121 " ) is (Element of ( Group_of_Perm R2 )) by MATRIX_2:23;
thus L940: thesis by L939 , MATRIX_2:def 10;
end;
definition
let R2 being Nat;
let C122 being (Element of ( Permutations R2 ));
redefine func C122 " -> (Element of ( Permutations R2 ));

coherence by L938;
end;
theorem
L942: (for R2 being Nat holds (for B167 being Field holds (for B168 being (Matrix of R2 , B167) holds ( B168 @ ) is (Matrix of R2 , B167))));
theorem
L943: (for B169 being Group holds (for B170 , B171 being (FinSequence of B169) holds ( ( Product ( B170 ^ B171 ) ) " ) = ( ( ( Product B171 ) " ) * ( ( Product B170 ) " ) )))
proof
let C123 being Group;
let C124 , C125 being (FinSequence of C123);
thus L944: ( ( Product ( C124 ^ C125 ) ) " ) = ( ( ( Product C124 ) * ( Product C125 ) ) " ) by GROUP_4:5
.= ( ( ( Product C125 ) " ) * ( ( Product C124 ) " ) ) by GROUP_1:17;
end;
definition
let C126 being Group;
let C127 being (FinSequence of C126);
canceled 1;
func C127 " -> (FinSequence of C126) means 
:L945: (( len it ) = ( len C127 ) & (for B172 being (Element of ( NAT )) holds (B172 in ( dom C127 ) implies ( it /. B172 ) = ( ( C127 /. B172 ) " ))));
existence
proof
deffunc H5(Nat) = ( ( C127 /. $1 ) " );
L946: (ex B173 being FinSequence st (( len B173 ) = ( len C127 ) & (for B174 being Nat holds (B174 in ( dom B173 ) implies ( B173 . B174 ) = H5(B174))))) from FINSEQ_1:sch 2;
consider C128 being FinSequence such that L947: ( len C128 ) = ( len C127 ) and L948: (for B175 being Nat holds (B175 in ( dom C128 ) implies ( C128 . B175 ) = H5(B175))) by L946;
L949: ( rng C128 ) c= (the carrier of C126)
proof
let C129 being set;
assume L950: C129 in ( rng C128 );
consider C130 being set such that L951: C130 in ( dom C128 ) and L952: C129 = ( C128 . C130 ) by L950 , FUNCT_1:def 3;
reconsider D69 = C130 as (Element of ( NAT )) by L951;
L953: ( C128 . D69 ) = ( ( C127 /. D69 ) " ) by L948 , L951;
thus L954: thesis by L953 , L952;
end;
reconsider D70 = C128 as (FinSequence of C126) by L949 , FINSEQ_1:def 4;
L955: ( dom C128 ) = ( dom C127 ) by L947 , FINSEQ_3:29;
L956: (for B176 being (Element of ( NAT )) holds (B176 in ( dom C127 ) implies ( D70 /. B176 ) = ( ( C127 /. B176 ) " )))
proof
let C131 being (Element of ( NAT ));
assume L957: C131 in ( dom C127 );
thus L958: ( D70 /. C131 ) = ( C128 . C131 ) by L957 , L955 , PARTFUN1:def 6
.= ( ( C127 /. C131 ) " ) by L948 , L955 , L957;
end;
thus L959: thesis by L956 , L947;
end;
uniqueness
proof
thus L960: (for B177 , B178 being (FinSequence of C126) holds ((( len B177 ) = ( len C127 ) & (for B179 being (Element of ( NAT )) holds (B179 in ( dom C127 ) implies ( B177 /. B179 ) = ( ( C127 /. B179 ) " ))) & ( len B178 ) = ( len C127 ) & (for B180 being (Element of ( NAT )) holds (B180 in ( dom C127 ) implies ( B178 /. B180 ) = ( ( C127 /. B180 ) " )))) implies B177 = B178))
proof
let C132 , C133 being (FinSequence of C126);
assume that
L961: ( len C132 ) = ( len C127 )
and
L962: (for B181 being (Element of ( NAT )) holds (B181 in ( dom C127 ) implies ( C132 /. B181 ) = ( ( C127 /. B181 ) " )))
and
L963: ( len C133 ) = ( len C127 )
and
L964: (for B182 being (Element of ( NAT )) holds (B182 in ( dom C127 ) implies ( C133 /. B182 ) = ( ( C127 /. B182 ) " )));
L965: ( dom C132 ) = ( dom C127 ) by L961 , FINSEQ_3:29;
L966: (for B183 being Nat holds ((1 <= B183 & B183 <= ( len C132 )) implies ( C132 . B183 ) = ( C133 . B183 )))
proof
let C134 being Nat;
assume L967: (1 <= C134 & C134 <= ( len C132 ));
L968: C134 in ( NAT ) by ORDINAL1:def 12;
L969: C134 in ( Seg ( len C133 ) ) by L968 , L961 , L963 , L967;
L970: C134 in ( dom C133 ) by L969 , FINSEQ_1:def 3;
L971: ( C133 . C134 ) = ( C133 /. C134 ) by L970 , PARTFUN1:def 6;
L972: C134 in ( Seg ( len C132 ) ) by L968 , L967;
L973: C134 in ( dom C132 ) by L972 , FINSEQ_1:def 3;
L974: (( C132 . C134 ) = ( C132 /. C134 ) & ( C132 /. C134 ) = ( ( C127 /. C134 ) " )) by L973 , L962 , L965 , PARTFUN1:def 6;
thus L975: thesis by L974 , L964 , L965 , L973 , L971;
end;
thus L976: thesis by L966 , L961 , L963 , FINSEQ_1:14;
end;

end;
end;
theorem
L962: (for B184 being Group holds ( ( <*> (the carrier of B184) ) " ) = ( <*> (the carrier of B184) ))
proof
let C135 being Group;
L963: ( len ( <*> (the carrier of C135) ) ) = ( 0 );
L964: ( len (( ( <*> (the carrier of C135) ) " ) qua (FinSequence of C135)) ) = ( 0 ) by L963 , L945;
thus L965: thesis by L964;
end;
theorem
L966: (for B185 being Group holds (for B186 , B187 being (FinSequence of B185) holds ( ( B186 ^ B187 ) " ) = ( ( B186 " ) ^ ( B187 " ) )))
proof
let C136 being Group;
let C137 , C138 being (FinSequence of C136);
L967: ( len ( ( C137 ^ C138 ) " ) ) = ( len ( C137 ^ C138 ) ) by L945
.= ( ( len C137 ) + ( len C138 ) ) by FINSEQ_1:22;
L968: ( ( len C137 ) + ( len C138 ) ) = ( ( len ( C137 " ) ) + ( len C138 ) ) by L945
.= ( ( len ( C137 " ) ) + ( len ( C138 " ) ) ) by L945
.= ( len ( ( C137 " ) ^ ( C138 " ) ) ) by FINSEQ_1:22;
L969: ( len ( ( C137 ^ C138 ) " ) ) = ( len ( C137 ^ C138 ) ) by L945;
L970: (for B188 being Nat holds ((1 <= B188 & B188 <= ( len ( ( C137 ^ C138 ) " ) )) implies ( ( ( C137 ^ C138 ) " ) . B188 ) = ( ( ( C137 " ) ^ ( C138 " ) ) . B188 )))
proof
let C139 being Nat;
assume that
L971: 1 <= C139
and
L972: C139 <= ( len ( ( C137 ^ C138 ) " ) );
L973: C139 in ( NAT ) by ORDINAL1:def 12;
L974:
now
per cases ;
case L975: ( len C137 ) > ( 0 );
L976: ( len ( C137 " ) ) = ( len C137 ) by L945;
L977: ( len ( ( C137 ^ C138 ) " ) ) = ( len ( C137 ^ C138 ) ) by L945;
L978: ( dom ( ( C137 ^ C138 ) " ) ) = ( dom ( C137 ^ C138 ) ) by L977 , FINSEQ_3:29;
L979: C139 in ( Seg ( len ( ( C137 ^ C138 ) " ) ) ) by L971 , L972 , L973;
L980: C139 in ( dom ( ( C137 ^ C138 ) " ) ) by L979 , FINSEQ_1:def 3;
L981: ( ( ( C137 ^ C138 ) " ) . C139 ) = ( ( ( C137 ^ C138 ) " ) /. C139 ) by L980 , PARTFUN1:def 6
.= ( ( ( C137 ^ C138 ) /. C139 ) " ) by L978 , L980 , L945;
L982: ( len ( C138 " ) ) = ( len C138 ) by L945;
L983:
now
per cases ;
case L984: C139 <= ( len C137 );
L985: C139 in ( Seg ( len C137 ) ) by L984 , L971 , L973;
L986: C139 in ( dom C137 ) by L985 , FINSEQ_1:def 3;
L987: C139 in ( dom ( C137 " ) ) by L976 , L985 , FINSEQ_1:def 3;
L988: ( ( C137 ^ C138 ) /. C139 ) = ( ( C137 ^ C138 ) . C139 ) by L978 , L980 , PARTFUN1:def 6
.= ( C137 . C139 ) by L986 , FINSEQ_1:def 7
.= ( C137 /. C139 ) by L986 , PARTFUN1:def 6;
L989: ( ( ( C137 ^ C138 ) /. C139 ) " ) = ( ( C137 " ) /. C139 ) by L988 , L986 , L945
.= ( ( C137 " ) . C139 ) by L987 , PARTFUN1:def 6;
thus L990: thesis by L989 , L981 , L987 , FINSEQ_1:def 7;
end;
case L991: C139 > ( len C137 );
L992: ( 1 + ( len C137 ) ) <= C139 by L991 , NAT_1:13;
L993: ( ( 1 + ( len C137 ) ) - ( len C137 ) ) <= ( C139 - ( len C137 ) ) by L992 , XREAL_1:9;
L994: ( C139 -' ( len C137 ) ) = ( C139 - ( len C137 ) ) by L991 , XREAL_1:233;
L995: ( C139 - ( len C137 ) ) <= ( ( ( len C138 ) + ( len C137 ) ) - ( len C137 ) ) by L967 , L972 , XREAL_1:9;
L996: ( C139 -' ( len C137 ) ) in ( Seg ( len C138 ) ) by L995 , L994 , L993;
L997: ( C139 -' ( len C137 ) ) in ( dom C138 ) by L996 , FINSEQ_1:def 3;
L998: ( C139 -' ( len C137 ) ) in ( dom ( C138 " ) ) by L982 , L996 , FINSEQ_1:def 3;
L999: ( ( C137 ^ C138 ) /. C139 ) = ( ( C137 ^ C138 ) . C139 ) by L978 , L980 , PARTFUN1:def 6
.= ( C138 . ( C139 - ( len C137 ) ) ) by L969 , L972 , L991 , FINSEQ_1:24
.= ( C138 /. ( C139 -' ( len C137 ) ) ) by L994 , L997 , PARTFUN1:def 6;
L1000: ( ( ( C137 ^ C138 ) /. C139 ) " ) = ( ( C138 " ) /. ( C139 -' ( len C137 ) ) ) by L999 , L997 , L945
.= ( ( C138 " ) . ( C139 - ( len ( C137 " ) ) ) ) by L976 , L994 , L998 , PARTFUN1:def 6;
thus L1001: thesis by L1000 , L967 , L968 , L972 , L976 , L981 , L991 , FINSEQ_1:24;
end;
end;
thus L1003: thesis by L983;
end;
case L1004: ( len C137 ) <= ( 0 );
L1005: C137 = ( {} ) by L1004;
L1006: (( ( C137 ^ C138 ) " ) = ( C138 " ) & ( C137 " ) = ( <*> (the carrier of C136) )) by L1005 , L962 , FINSEQ_1:34;
thus L1007: thesis by L1006 , FINSEQ_1:34;
end;
end;
thus L1009: thesis by L974;
end;
thus L1010: thesis by L970 , L967 , L968 , FINSEQ_1:14;
end;
theorem
L1011: (for B189 being Group holds (for B190 being (Element of B189) holds ( <* B190 *> " ) = <* ( B190 " ) *>))
proof
let C140 being Group;
let C141 being (Element of C140);
L1012: ( len ( <* C141 *> " ) ) = ( len <* C141 *> ) by L945
.= 1 by FINSEQ_1:39
.= ( len <* ( C141 " ) *> ) by FINSEQ_1:39;
L1013: (for B191 being Nat holds ((1 <= B191 & B191 <= ( len <* ( C141 " ) *> )) implies ( ( <* C141 *> " ) . B191 ) = ( <* ( C141 " ) *> . B191 )))
proof
let C142 being Nat;
assume L1014: (1 <= C142 & C142 <= ( len <* ( C141 " ) *> ));
L1015: ( len <* ( C141 " ) *> ) = 1 by FINSEQ_1:39;
L1016: C142 = 1 by L1015 , L1014 , XXREAL_0:1;
L1017: C142 in ( NAT ) by ORDINAL1:def 12;
L1018: ( len <* C141 *> ) = 1 by FINSEQ_1:39;
L1019: C142 in ( Seg ( len <* C141 *> ) ) by L1018 , L1014 , L1017 , L1015;
L1020: C142 in ( dom <* C141 *> ) by L1019 , FINSEQ_1:def 3;
L1021: C142 in ( Seg ( len ( <* C141 *> " ) ) ) by L1012 , L1014 , L1017;
L1022: C142 in ( dom ( <* C141 *> " ) ) by L1021 , FINSEQ_1:def 3;
L1023: ( ( <* C141 *> " ) . C142 ) = ( ( <* C141 *> " ) /. C142 ) by L1022 , PARTFUN1:def 6
.= ( ( <* C141 *> /. C142 ) " ) by L1020 , L945;
L1024: ( <* C141 *> /. C142 ) = ( <* C141 *> . C142 ) by L1020 , PARTFUN1:def 6
.= C141 by L1016 , FINSEQ_1:40;
thus L1025: thesis by L1024 , L1016 , L1023 , FINSEQ_1:40;
end;
thus L1026: thesis by L1013 , L1012 , FINSEQ_1:14;
end;
theorem
L1027: (for B192 being Group holds (for B193 being (FinSequence of B192) holds ( Product ( B193 ^ ( ( Rev B193 ) " ) ) ) = ( 1_ B192 )))
proof
let C143 being Group;
let C144 being (FinSequence of C143);
defpred S12[ (Element of ( NAT )) ] means (for B194 being (FinSequence of C143) holds (( len B194 ) <= $1 implies ( Product ( B194 ^ ( ( Rev B194 ) " ) ) ) = ( 1_ C143 )));
L1028: (for B195 being (Element of ( NAT )) holds (S12[ B195 ] implies S12[ ( B195 + 1 ) ]))
proof
let C145 being (Element of ( NAT ));
assume L1029: S12[ C145 ];
L1030: (for B196 being (FinSequence of C143) holds (( len B196 ) <= ( C145 + 1 ) implies ( Product ( B196 ^ ( ( Rev B196 ) " ) ) ) = ( 1_ C143 )))
proof
let C146 being (FinSequence of C143);
assume L1031: ( len C146 ) <= ( C145 + 1 );
L1032:
now
per cases  by L1031 , XXREAL_0:1;
case L1033: ( len C146 ) < ( C145 + 1 );
L1034: ( len C146 ) <= C145 by L1033 , NAT_1:13;
thus L1035: thesis by L1034 , L1029;
end;
case L1036: ( len C146 ) = ( C145 + 1 );
reconsider D71 = ( C146 | C145 ) as (FinSequence of C143);
L1037: C145 < ( len C146 ) by L1036 , NAT_1:13;
L1038: ( len D71 ) = C145 by L1037 , FINSEQ_1:59;
L1039: ( Product ( <* ( C146 /. ( C145 + 1 ) ) *> ^ ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ) ) = ( ( Product <* ( C146 /. ( C145 + 1 ) ) *> ) * ( Product ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ) ) by GROUP_4:5
.= ( ( C146 /. ( C145 + 1 ) ) * ( Product ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ) ) by FINSOP_1:11
.= ( ( C146 /. ( C145 + 1 ) ) * ( Product <* ( ( C146 /. ( C145 + 1 ) ) " ) *> ) ) by L1011
.= ( ( C146 /. ( C145 + 1 ) ) * ( ( C146 /. ( C145 + 1 ) ) " ) ) by FINSOP_1:11
.= ( 1_ C143 ) by GROUP_1:def 5;
L1040: C146 = ( D71 ^ <* ( C146 /. ( C145 + 1 ) ) *> ) by L1036 , FINSEQ_5:21;
L1041: ( Rev C146 ) = ( <* ( C146 /. ( C145 + 1 ) ) *> ^ ( Rev D71 ) ) by L1040 , FINSEQ_5:63;
L1042: ( ( Rev C146 ) " ) = ( ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ^ ( ( Rev D71 ) " ) ) by L1041 , L966;
L1043: ( C146 ^ ( ( Rev C146 ) " ) ) = ( D71 ^ ( <* ( C146 /. ( C145 + 1 ) ) *> ^ ( ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ^ ( ( Rev D71 ) " ) ) ) ) by L1042 , L1040 , FINSEQ_1:32
.= ( D71 ^ ( ( <* ( C146 /. ( C145 + 1 ) ) *> ^ ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ) ^ ( ( Rev D71 ) " ) ) ) by FINSEQ_1:32;
L1044: ( Product ( C146 ^ ( ( Rev C146 ) " ) ) ) = ( ( Product D71 ) * ( Product ( ( <* ( C146 /. ( C145 + 1 ) ) *> ^ ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ) ^ ( ( Rev D71 ) " ) ) ) ) by L1043 , GROUP_4:5
.= ( ( Product D71 ) * ( ( Product ( <* ( C146 /. ( C145 + 1 ) ) *> ^ ( <* ( C146 /. ( C145 + 1 ) ) *> " ) ) ) * ( Product ( ( Rev D71 ) " ) ) ) ) by GROUP_4:5
.= ( ( Product D71 ) * ( Product ( ( Rev D71 ) " ) ) ) by L1039 , GROUP_1:def 4
.= ( Product ( D71 ^ ( ( Rev D71 ) " ) ) ) by GROUP_4:5;
thus L1045: thesis by L1044 , L1029 , L1038;
end;
end;
thus L1047: thesis by L1032;
end;
thus L1048: thesis by L1030;
end;
L1049: (for B197 being (FinSequence of C143) holds (( len B197 ) <= ( 0 ) implies ( Product ( B197 ^ ( ( Rev B197 ) " ) ) ) = ( 1_ C143 )))
proof
let C147 being (FinSequence of C143);
assume L1050: ( len C147 ) <= ( 0 );
L1051: C147 = ( <*> (the carrier of C143) ) by L1050;
L1052: ( Rev C147 ) = ( <*> (the carrier of C143) ) by L1051 , FINSEQ_5:79;
L1053: ( ( Rev C147 ) " ) = ( <*> (the carrier of C143) ) by L1052 , L962;
L1054: ( C147 ^ ( ( Rev C147 ) " ) ) = ( <*> (the carrier of C143) ) by L1053 , L1051 , FINSEQ_1:34;
thus L1055: thesis by L1054 , GROUP_4:8;
end;
L1056: S12[ ( 0 ) ] by L1049;
L1057: (for B198 being (Element of ( NAT )) holds S12[ B198 ]) from NAT_1:sch 1(L1056 , L1028);
L1058: S12[ ( len C144 ) ] by L1057;
thus L1059: thesis by L1058;
end;
theorem
L1060: (for B199 being Group holds (for B200 being (FinSequence of B199) holds ( Product ( ( ( Rev B200 ) " ) ^ B200 ) ) = ( 1_ B199 )))
proof
let C148 being Group;
let C149 being (FinSequence of C148);
L1061: ( len C149 ) = ( len ( Rev C149 ) ) by FINSEQ_5:def 3;
L1062: ( len ( Rev ( ( Rev C149 ) " ) ) ) = ( len ( ( Rev ( ( Rev C149 ) " ) ) " ) ) by L945;
L1063: ( dom ( Rev ( ( Rev C149 ) " ) ) ) = ( dom ( ( Rev ( ( Rev C149 ) " ) ) " ) ) by L1062 , FINSEQ_3:29;
L1064: ( len ( ( Rev C149 ) " ) ) = ( len ( Rev ( ( Rev C149 ) " ) ) ) by FINSEQ_5:def 3;
L1065: ( len ( Rev C149 ) ) = ( len ( ( Rev C149 ) " ) ) by L945;
L1066: ( dom ( Rev C149 ) ) = ( dom ( ( Rev C149 ) " ) ) by L1065 , FINSEQ_3:29;
L1067: (for B201 being Nat holds ((1 <= B201 & B201 <= ( len C149 )) implies ( C149 . B201 ) = ( ( ( Rev ( ( Rev C149 ) " ) ) " ) . B201 )))
proof
let C150 being Nat;
assume that
L1068: 1 <= C150
and
L1069: C150 <= ( len C149 );
L1070: ( ( ( len C149 ) - C150 ) + 1 ) = ( ( ( len C149 ) -' C150 ) + 1 ) by L1069 , XREAL_1:233;
reconsider D72 = ( ( ( len C149 ) - C150 ) + 1 ) as (Element of ( NAT )) by L1070;
L1071: ( C150 + D72 ) = ( ( len C149 ) + 1 );
L1072: C150 in ( NAT ) by ORDINAL1:def 12;
L1073: C150 in ( Seg ( len C149 ) ) by L1072 , L1068 , L1069;
L1074: C150 in ( dom ( ( Rev ( ( Rev C149 ) " ) ) " ) ) by L1073 , L1061 , L1065 , L1064 , L1062 , FINSEQ_1:def 3;
L1075: ( C150 - 1 ) >= ( 0 ) by L1068 , XREAL_1:48;
L1076: ( ( len C149 ) + ( 0 ) ) <= ( ( len C149 ) + ( C150 - 1 ) ) by L1075 , XREAL_1:7;
L1077: ( ( len C149 ) - ( C150 - 1 ) ) <= ( ( ( len C149 ) + ( C150 - 1 ) ) - ( C150 - 1 ) ) by L1076 , XREAL_1:13;
L1078: ( ( len C149 ) - C150 ) = ( ( len C149 ) -' C150 ) by L1069 , XREAL_1:233;
L1079: ( ( ( len C149 ) - C150 ) + 1 ) >= ( ( 0 ) + 1 ) by L1078 , XREAL_1:6;
L1080: D72 in ( Seg ( len C149 ) ) by L1079 , L1077;
L1081: D72 in ( dom ( ( Rev C149 ) " ) ) by L1080 , L1061 , L1065 , FINSEQ_1:def 3;
L1082: ( D72 + C150 ) = ( ( len C149 ) + 1 );
L1083: C150 in ( dom C149 ) by L1073 , FINSEQ_1:def 3;
L1084: ( C149 . C150 ) = ( C149 /. C150 ) by L1083 , PARTFUN1:def 6
.= ( ( Rev C149 ) /. D72 ) by L1083 , L1071 , FINSEQ_5:66
.= ( ( ( ( Rev C149 ) /. D72 ) " ) " )
.= ( ( ( ( Rev C149 ) " ) /. D72 ) " ) by L1066 , L1081 , L945
.= ( ( ( Rev ( ( Rev C149 ) " ) ) /. C150 ) " ) by L1061 , L1065 , L1081 , L1082 , FINSEQ_5:66
.= ( ( ( Rev ( ( Rev C149 ) " ) ) " ) /. C150 ) by L1063 , L1074 , L945
.= ( ( ( Rev ( ( Rev C149 ) " ) ) " ) . C150 ) by L1074 , PARTFUN1:def 6;
thus L1085: thesis by L1084;
end;
L1086: ( ( Rev ( ( Rev C149 ) " ) ) " ) = C149 by L1067 , L1061 , L1065 , L1064 , L1062 , FINSEQ_1:14;
thus L1087: thesis by L1086 , L1027;
end;
theorem
L1088: (for B202 being Group holds (for B203 being (FinSequence of B202) holds ( ( Product B203 ) " ) = ( Product ( ( Rev B203 ) " ) )))
proof
let C151 being Group;
let C152 being (FinSequence of C151);
L1089: ( Product ( C152 ^ ( ( Rev C152 ) " ) ) ) = ( 1_ C151 ) by L1027;
L1090: ( ( Product C152 ) * ( Product ( ( Rev C152 ) " ) ) ) = ( 1_ C151 ) by L1089 , GROUP_4:5;
L1091: ( Product ( ( ( Rev C152 ) " ) ^ C152 ) ) = ( 1_ C151 ) by L1060;
L1092: ( ( Product ( ( Rev C152 ) " ) ) * ( Product C152 ) ) = ( 1_ C151 ) by L1091 , GROUP_4:5;
thus L1093: thesis by L1092 , L1090 , GROUP_1:5;
end;
theorem
L1094: (for R2 being Nat holds (for B204 being (Element of ( Permutations R2 )) holds (for B205 being (Element of ( Group_of_Perm R2 )) holds ((B205 = B204 & R2 >= 1) implies ( B204 " ) = ( B205 " )))))
proof
let R2 being Nat;
let C153 being (Element of ( Permutations R2 ));
let C154 being (Element of ( Group_of_Perm R2 ));
assume that
L1095: C154 = C153
and
L1096: R2 >= 1;
reconsider D73 = C153 as (Function of ( Seg R2 ) , ( Seg R2 )) by MATRIX_2:def 9;
L1097: ( dom D73 ) = ( Seg R2 ) by L1096 , FUNCT_2:def 1;
L1098: ( ( C153 " ) * C153 ) = ( id ( Seg R2 ) ) by L1097 , FUNCT_1:39;
L1099: C153 is (Permutation of ( Seg R2 )) by MATRIX_2:def 9;
L1100: ( rng D73 ) = ( Seg R2 ) by L1099 , FUNCT_2:def 3;
L1101: ( C153 * ( C153 " ) ) = ( id ( Seg R2 ) ) by L1100 , FUNCT_1:39;
reconsider D74 = ( C153 " ) as (Element of ( Group_of_Perm R2 )) by MATRIX_2:def 10;
L1102: (( idseq R2 ) = ( 1_ ( Group_of_Perm R2 ) ) & ( C154 * D74 ) = ( (the multF of ( Group_of_Perm R2 )) . (C154 , D74) )) by MATRIX_2:24;
L1103: ( D74 * C154 ) = ( (the multF of ( Group_of_Perm R2 )) . (D74 , C154) );
L1104: (( (the multF of ( Group_of_Perm R2 )) . (C154 , D74) ) = ( ( C153 " ) * C153 ) & ( (the multF of ( Group_of_Perm R2 )) . (D74 , C154) ) = ( C153 * ( C153 " ) )) by L1095 , MATRIX_2:def 10;
thus L1105: thesis by L1104 , L1098 , L1101 , L1102 , L1103 , GROUP_1:def 5;
end;
L1106: (for B206 being (Element of ( NAT )) holds (for B207 being (Element of ( Permutations B206 )) holds ((B207 is  even & B206 >= 1) implies ( B207 " ) is  even)))
proof
let C155 being (Element of ( NAT ));
let C156 being (Element of ( Permutations C155 ));
assume that
L1107: C156 is  even
and
L1108: C155 >= 1;
reconsider D75 = C156 as (Element of ( Permutations C155 ));
reconsider D76 = D75 as (Element of ( Group_of_Perm C155 )) by MATRIX_2:def 10;
L1109: ( len ( Permutations C155 ) ) = C155 by MATRIX_2:18;
consider C157 being (FinSequence of ( Group_of_Perm C155 )) such that L1110: ( ( len C157 ) mod 2 ) = ( 0 ) and L1111: C156 = ( Product C157 ) and L1112: (for R3 being Nat holds (R3 in ( dom C157 ) implies (ex B208 being (Element of ( Permutations C155 )) st (( C157 . R3 ) = B208 & B208 is  being_transposition)))) by L1109 , L1107 , MATRIX_2:def 12;
set D77 = ( len C157 );
reconsider D78 = ( ( Rev C157 ) " ) as (FinSequence of ( Group_of_Perm C155 ));
L1113: ( len C157 ) = ( len ( Rev C157 ) ) by FINSEQ_5:def 3;
L1114: ( len C157 ) = ( len D78 ) by L1113 , L945;
L1115: (for R3 being Nat holds (R3 in ( dom D78 ) implies (ex B209 being (Element of ( Permutations C155 )) st (( D78 . R3 ) = B209 & B209 is  being_transposition))))
proof
let R3 being Nat;
reconsider D79 = R3 as (Element of ( NAT )) by ORDINAL1:def 12;
assume L1116: R3 in ( dom D78 );
L1117: R3 in ( dom ( Rev C157 ) ) by L1116 , L1113 , L1114 , FINSEQ_3:29;
L1118: R3 in ( Seg ( len D78 ) ) by L1116 , FINSEQ_1:def 3;
L1119: 1 <= R3 by L1118 , FINSEQ_1:1;
L1120: ( D77 + 1 ) <= ( D77 + R3 ) by L1119 , XREAL_1:7;
L1121: ( ( D77 + 1 ) - R3 ) <= ( ( D77 + R3 ) - R3 ) by L1120 , XREAL_1:9;
L1122: R3 <= D77 by L1114 , L1118 , FINSEQ_1:1;
L1123: ( D77 - R3 ) >= ( 0 ) by L1122 , XREAL_1:48;
L1124: ( ( D77 - R3 ) + 1 ) = ( ( D77 -' R3 ) + 1 ) by L1123 , XREAL_0:def 2;
reconsider D80 = ( ( ( len C157 ) - R3 ) + 1 ) as (Element of ( NAT )) by L1124;
L1125: ( ( D77 - R3 ) + 1 ) >= ( ( 0 ) + 1 ) by L1123 , XREAL_1:7;
L1126: D80 in ( Seg ( len C157 ) ) by L1125 , L1121;
L1127: D80 in ( dom C157 ) by L1126 , FINSEQ_1:def 3;
consider C158 being (Element of ( Permutations C155 )) such that L1128: ( C157 . D80 ) = C158 and L1129: C158 is  being_transposition by L1127 , L1112;
L1130: ( D78 . R3 ) = ( D78 /. R3 ) by L1116 , PARTFUN1:def 6;
reconsider D81 = ( D78 . R3 ) as (Element of ( Permutations C155 )) by L1130 , MATRIX_2:def 10;
reconsider D82 = D81 as (Function of ( Seg C155 ) , ( Seg C155 )) by MATRIX_2:def 9;
L1131: ( R3 + D80 ) = ( ( len C157 ) + 1 );
reconsider D83 = C158 as (Function of ( Seg C155 ) , ( Seg C155 )) by MATRIX_2:def 9;
consider C159 , C160 being Nat such that L1132: (C159 in ( dom C158 ) & C160 in ( dom C158 ) & C159 <> C160 & ( C158 . C159 ) = C160 & ( C158 . C160 ) = C159) and L1133: (for B210 being Nat holds ((B210 <> C159 & B210 <> C160 & B210 in ( dom C158 )) implies ( C158 . B210 ) = B210)) by L1129 , MATRIX_2:def 11;
L1134: (( dom D83 ) = ( Seg C155 ) & ( dom D82 ) = ( Seg C155 )) by L1108 , FUNCT_2:def 1;
L1135: D81 = ( ( ( Rev C157 ) " ) /. R3 ) by L1116 , PARTFUN1:def 6
.= ( ( ( Rev C157 ) /. D79 ) " ) by L1117 , L945
.= ( ( C157 /. D80 ) " ) by L1131 , L1127 , FINSEQ_5:66
.= ( C158 " ) by L1108 , L1127 , L1128 , L1094 , PARTFUN1:def 6;
L1136: (for B211 being (Element of ( NAT )) holds ((B211 <> C160 & B211 <> C159 & B211 in ( dom D81 )) implies ( D81 . B211 ) = B211))
proof
let C161 being (Element of ( NAT ));
assume that
L1137: (C161 <> C160 & C161 <> C159)
and
L1138: C161 in ( dom D81 );
L1139: ( C158 . C161 ) = C161 by L1133 , L1134 , L1137 , L1138;
thus L1140: thesis by L1139 , L1134 , L1135 , L1138 , FUNCT_1:32;
end;
L1141: D81 = ( ( ( Rev C157 ) " ) /. R3 ) by L1116 , PARTFUN1:def 6
.= ( ( ( Rev C157 ) /. D79 ) " ) by L1117 , L945
.= ( ( C157 /. D80 ) " ) by L1131 , L1127 , FINSEQ_5:66
.= ( C158 " ) by L1108 , L1127 , L1128 , L1094 , PARTFUN1:def 6;
L1142: (ex R3 being Nat st (ex R4 being Nat st (R3 in ( dom D81 ) & R4 in ( dom D81 ) & R3 <> R4 & ( D81 . R3 ) = R4 & ( D81 . R4 ) = R3 & (for R1 being Nat holds ((R1 <> R3 & R1 <> R4 & R1 in ( dom D81 )) implies ( D81 . R1 ) = R1)))))
proof
take D84 = C159;
take D85 = C160;
thus L1143: (D84 in ( dom D81 ) & D85 in ( dom D81 ) & D84 <> D85 & ( D81 . D84 ) = D85 & ( D81 . D85 ) = D84) by L1132 , L1134 , L1141 , FUNCT_1:32;
let R1 being Nat;
L1144: R1 in ( NAT ) by ORDINAL1:def 12;
thus L1145: thesis by L1144 , L1136;
end;
L1146: D81 is  being_transposition by L1142 , MATRIX_2:def 11;
thus L1147: thesis by L1146;
end;
L1148: ( D76 " ) = ( D75 " ) by L1108 , L1094;
L1149: ( C156 " ) = ( Product D78 ) by L1148 , L1111 , L1088;
thus L1150: thesis by L1149 , L1109 , L1110 , L1114 , L1115 , MATRIX_2:def 12;
end;
theorem
L1151: (for B212 being (Element of ( NAT )) holds (for B213 being (Element of ( Permutations B212 )) holds (B212 >= 1 implies (B213 is  even iff ( B213 " ) is  even))))
proof
let C162 being (Element of ( NAT ));
let C163 being (Element of ( Permutations C162 ));
assume L1152: C162 >= 1;
thus L1153: (C163 is  even implies ( C163 " ) is  even) by L1152 , L1106;
L1154:
now
assume L1155: ( C163 " ) is  even;
L1156: ( ( C163 " ) " ) is  even by L1155 , L1152 , L1106;
thus L1157: C163 is  even by L1156 , FUNCT_1:43;
end;
thus L1158: thesis by L1154;
end;
theorem
L1159: (for B214 being (Element of ( NAT )) holds (for B215 being Field holds (for B216 being (Element of ( Permutations B214 )) holds (for B217 being (Element of B215) holds (B214 >= 1 implies ( - (B217 , B216) ) = ( - (B217 , ( B216 " )) ))))))
proof
let C164 being (Element of ( NAT ));
let C165 being Field;
let C166 being (Element of ( Permutations C164 ));
let C167 being (Element of C165);
assume L1160: C164 >= 1;
reconsider D86 = C166 as (Permutation of ( Seg C164 )) by MATRIX_2:def 9;
L1161: ( len ( Permutations C164 ) ) = C164 by MATRIX_2:18;
per cases ;
suppose L1162: C166 is  even;

L1163: (( - (C167 , C166) ) = C167 & ( D86 " ) is  even) by L1162 , L1160 , L1161 , L1151 , MATRIX_2:def 13;
thus L1164: thesis by L1163 , L1161 , MATRIX_2:def 13;
end;
suppose L1165: (not C166 is  even);

L1166: (( - (C167 , C166) ) = ( - C167 ) & (not ( C166 " ) is  even)) by L1165 , L1160 , L1151 , MATRIX_2:def 13;
thus L1167: thesis by L1166 , MATRIX_2:def 13;
end;
end;
theorem
L1169: (for B218 being Field holds (for B219 , B220 being (FinSequence of B218) holds ( (the multF of B218) $$ ( B219 ^ B220 ) ) = ( ( (the multF of B218) $$ B219 ) * ( (the multF of B218) $$ B220 ) ))) by FINSOP_1:5;
theorem
L1170: (for B221 being Field holds (for B222 , B223 being (FinSequence of B221) holds (B222 , B223 are_fiberwise_equipotent  implies ( (the multF of B221) $$ B222 ) = ( (the multF of B221) $$ B223 ))))
proof
let C168 being Field;
defpred S13[ Nat ] means (for B224 , B225 being (FinSequence of C168) holds ((B224 , B225 are_fiberwise_equipotent  & ( len B224 ) = $1) implies ( (the multF of C168) $$ B224 ) = ( (the multF of C168) $$ B225 )));
let C169 , C170 being (FinSequence of C168);
assume L1171: C169 , C170 are_fiberwise_equipotent ;
L1172: ( len C169 ) = ( len C169 );
L1173: (for R2 being Nat holds (S13[ R2 ] implies S13[ ( R2 + 1 ) ]))
proof
let R2 being Nat;
assume L1174: S13[ R2 ];
reconsider D87 = R2 as (Element of ( NAT )) by ORDINAL1:def 12;
let C171 , C172 being (FinSequence of C168);
assume that
L1175: C171 , C172 are_fiberwise_equipotent 
and
L1176: ( len C171 ) = ( R2 + 1 );
L1177: ( rng C171 ) c= (the carrier of C168) by FINSEQ_1:def 4;
L1178: ( ( 0 ) + 1 ) <= ( R2 + 1 ) by NAT_1:13;
L1179: ( R2 + 1 ) in ( dom C171 ) by L1178 , L1176 , FINSEQ_3:25;
L1180: ( C171 . ( R2 + 1 ) ) in ( rng C171 ) by L1179 , FUNCT_1:def 3;
reconsider D88 = ( C171 . ( R2 + 1 ) ) as (Element of C168) by L1180 , L1177;
L1181: ( rng C171 ) = ( rng C172 ) by L1175 , CLASSES1:75;
L1182: D88 in ( rng C172 ) by L1181 , L1179 , FUNCT_1:def 3;
consider C173 being Nat such that L1183: C173 in ( dom C172 ) and L1184: ( C172 . C173 ) = D88 by L1182 , FINSEQ_2:10;
L1185: C172 = ( ( C172 | C173 ) ^ ( C172 /^ C173 ) ) by RFINSEQ:8;
set D89 = ( C172 /^ C173 );
set D90 = ( C172 | C173 );
L1186: 1 <= C173 by L1183 , FINSEQ_3:25;
L1187: ( max (( 0 ) , ( C173 - 1 )) ) = ( C173 - 1 ) by L1186 , FINSEQ_2:4;
reconsider D91 = ( C173 - 1 ) as (Element of ( NAT )) by L1187 , FINSEQ_2:5;
L1188: C173 in ( NAT ) by ORDINAL1:def 12;
L1189: C173 in ( Seg C173 ) by L1188 , L1186;
L1190: ( D90 . C173 ) = D88 by L1189 , L1183 , L1184 , RFINSEQ:6;
L1191: C173 = ( D91 + 1 );
L1192: D91 <= C173 by L1191 , NAT_1:11;
L1193: ( Seg D91 ) c= ( Seg C173 ) by L1192 , FINSEQ_1:5;
L1194: C173 <= ( len C172 ) by L1183 , FINSEQ_3:25;
L1195: ( len D90 ) = C173 by L1194 , FINSEQ_1:59;
L1196: D90 = ( ( D90 | D91 ) ^ <* D88 *> ) by L1195 , L1191 , L1190 , RFINSEQ:7;
set D92 = ( C171 | D87 );
L1197: C171 = ( D92 ^ <* D88 *> ) by L1176 , RFINSEQ:7;
L1198: ( D90 | D91 ) = ( C172 | ( ( Seg C173 ) /\ ( Seg D91 ) ) ) by RELAT_1:71
.= ( C172 | D91 ) by L1193 , XBOOLE_1:28;
L1199:
now
let C174 being set;
L1200: ( card ( Coim (C171 , C174) ) ) = ( card ( Coim (C172 , C174) ) ) by L1175 , CLASSES1:def 9;
L1201: ( ( card ( D92 " { C174 } ) ) + ( card ( <* D88 *> " { C174 } ) ) ) = ( card ( ( ( ( C172 | D91 ) ^ <* D88 *> ) ^ ( C172 /^ C173 ) ) " { C174 } ) ) by L1200 , L1185 , L1196 , L1198 , L1197 , FINSEQ_3:57
.= ( ( card ( ( ( C172 | D91 ) ^ <* D88 *> ) " { C174 } ) ) + ( card ( ( C172 /^ C173 ) " { C174 } ) ) ) by FINSEQ_3:57
.= ( ( ( card ( ( C172 | D91 ) " { C174 } ) ) + ( card ( <* D88 *> " { C174 } ) ) ) + ( card ( ( C172 /^ C173 ) " { C174 } ) ) ) by FINSEQ_3:57
.= ( ( ( card ( ( C172 | D91 ) " { C174 } ) ) + ( card ( ( C172 /^ C173 ) " { C174 } ) ) ) + ( card ( <* D88 *> " { C174 } ) ) )
.= ( ( card ( ( ( C172 | D91 ) ^ ( C172 /^ C173 ) ) " { C174 } ) ) + ( card ( <* D88 *> " { C174 } ) ) ) by FINSEQ_3:57;
thus L1202: ( card ( Coim (D92 , C174) ) ) = ( card ( Coim (( ( C172 | D91 ) ^ ( C172 /^ C173 ) ) , C174) ) ) by L1201;
end;
L1203: D92 , ( ( C172 | D91 ) ^ ( C172 /^ C173 ) ) are_fiberwise_equipotent  by L1199 , CLASSES1:def 9;
L1204: ( len D92 ) = R2 by L1176 , FINSEQ_1:59 , NAT_1:11;
L1205: ( (the multF of C168) $$ D92 ) = ( (the multF of C168) $$ ( ( C172 | D91 ) ^ D89 ) ) by L1204 , L1174 , L1203;
thus L1206: ( (the multF of C168) $$ C171 ) = ( ( (the multF of C168) $$ ( ( C172 | D91 ) ^ D89 ) ) * ( (the multF of C168) $$ <* D88 *> ) ) by L1205 , L1197 , FINSOP_1:5
.= ( ( ( (the multF of C168) $$ ( C172 | D91 ) ) * ( (the multF of C168) $$ D89 ) ) * ( (the multF of C168) $$ <* D88 *> ) ) by FINSOP_1:5
.= ( ( ( (the multF of C168) $$ ( C172 | D91 ) ) * ( (the multF of C168) $$ <* D88 *> ) ) * ( (the multF of C168) $$ D89 ) ) by GROUP_1:def 3
.= ( ( (the multF of C168) $$ D90 ) * ( (the multF of C168) $$ D89 ) ) by L1196 , L1198 , FINSOP_1:5
.= ( (the multF of C168) $$ C172 ) by L1185 , FINSOP_1:5;
end;
L1207: S13[ ( 0 ) ]
proof
let C175 , C176 being (FinSequence of C168);
assume L1208: (C175 , C176 are_fiberwise_equipotent  & ( len C175 ) = ( 0 ));
L1209: (( len C176 ) = ( 0 ) & C175 = ( <*> (the carrier of C168) )) by L1208 , RFINSEQ:3;
L1210: C176 = ( <*> (the carrier of C168) ) by L1209;
thus L1211: thesis by L1210 , L1209;
end;
L1212: (for R2 being Nat holds S13[ R2 ]) from NAT_1:sch 2(L1207 , L1173);
thus L1213: thesis by L1212 , L1171 , L1172;
end;
theorem
L1214: (for B226 being (Element of ( NAT )) holds (for B227 being Field holds (for B228 being (Element of ( Permutations B226 )) holds (for B229 , B230 being (FinSequence of B227) holds ((( len B229 ) = B226 & B230 = ( B229 * B228 )) implies B229 , B230 are_fiberwise_equipotent )))))
proof
let C177 being (Element of ( NAT ));
let C178 being Field;
let C179 being (Element of ( Permutations C177 ));
let C180 , C181 being (FinSequence of C178);
assume that
L1215: ( len C180 ) = C177
and
L1216: C181 = ( C180 * C179 );
reconsider D93 = C179 as (Function of ( Seg C177 ) , ( Seg C177 )) by MATRIX_2:def 9;
L1217: C179 is (Permutation of ( Seg C177 )) by MATRIX_2:def 9;
L1218: ( rng C179 ) = ( Seg C177 ) by L1217 , FUNCT_2:def 3;
L1219: ( rng D93 ) = ( Seg C177 ) by L1217 , FUNCT_2:def 3;
L1220: ( rng C179 ) c= ( dom C180 ) by L1219 , L1215 , FINSEQ_1:def 3;
L1221: ( dom ( C180 * C179 ) ) = ( dom D93 ) by L1220 , RELAT_1:27;
L1222: ( dom C180 ) = ( Seg C177 ) by L1215 , FINSEQ_1:def 3;
thus L1223: thesis by L1222 , L1216 , L1221 , L1218 , CLASSES1:77;
end;
theorem
L1224: (for B231 being (Element of ( NAT )) holds (for B232 being Field holds (for B233 being (Element of ( Permutations B231 )) holds (for B234 , B235 being (FinSequence of B232) holds ((B231 >= 1 & ( len B234 ) = B231 & B235 = ( B234 * B233 )) implies ( (the multF of B232) $$ B234 ) = ( (the multF of B232) $$ B235 )))))) by L1170 , L1214;
theorem
L1225: (for B236 being (Element of ( NAT )) holds (for B237 being Field holds (for B238 being (Element of ( Permutations B236 )) holds (for B239 being (FinSequence of B237) holds ((B236 >= 1 & ( len B239 ) = B236) implies ( B239 * B238 ) is (FinSequence of B237))))))
proof
let C182 being (Element of ( NAT ));
let C183 being Field;
let C184 being (Element of ( Permutations C182 ));
let C185 being (FinSequence of C183);
assume that
L1226: C182 >= 1
and
L1227: ( len C185 ) = C182;
reconsider D94 = C184 as (Function of ( Seg C182 ) , ( Seg C182 )) by MATRIX_2:def 9;
L1228: C184 is  bijective  bijective  bijective  bijective (Function of ( Seg C182 ) , ( Seg C182 )) by MATRIX_2:def 9;
L1229: ( rng D94 ) = ( Seg C182 ) by L1228 , FUNCT_2:def 3;
L1230: ( rng C184 ) c= ( dom C185 ) by L1229 , L1227 , FINSEQ_1:def 3;
L1231: ( dom ( C185 * C184 ) ) = ( dom D94 ) by L1230 , RELAT_1:27
.= ( Seg C182 ) by L1226 , FUNCT_2:def 1;
reconsider D95 = ( C185 * C184 ) as FinSequence by L1231 , FINSEQ_1:def 2;
L1232: (( rng D95 ) c= ( rng C185 ) & ( rng C185 ) c= (the carrier of C183)) by FINSEQ_1:def 4 , RELAT_1:26;
L1233: ( rng D95 ) c= (the carrier of C183) by L1232 , XBOOLE_1:1;
thus L1234: thesis by L1233 , FINSEQ_1:def 4;
end;
theorem
L1235: (for B240 being (Element of ( NAT )) holds (for B241 being Field holds (for B242 being (Element of ( Permutations B240 )) holds (for B243 being (Matrix of B240 , B241) holds (B240 >= 1 implies ( Path_matrix (( B242 " ) , ( B243 @ )) ) = ( ( Path_matrix (B242 , B243) ) * ( B242 " ) ))))))
proof
let C186 being (Element of ( NAT ));
let C187 being Field;
let C188 being (Element of ( Permutations C186 ));
let C189 being (Matrix of C186 , C187);
set D96 = ( Path_matrix (C188 , C189) );
reconsider D97 = ( C188 " ) as (Function of ( Seg C186 ) , ( Seg C186 )) by MATRIX_2:def 9;
reconsider D98 = C188 as (Function of ( Seg C186 ) , ( Seg C186 )) by MATRIX_2:def 9;
assume L1236: C186 >= 1;
L1237: ( dom D97 ) = ( Seg C186 ) by L1236 , FUNCT_2:def 1;
L1238: ( len ( Path_matrix (C188 , C189) ) ) = C186 by MATRIX_3:def 7;
reconsider D99 = ( ( Path_matrix (C188 , C189) ) * ( C188 " ) ) as (FinSequence of C187) by L1238 , L1236 , L1225;
L1239: ( C188 " ) is (Permutation of ( Seg C186 )) by MATRIX_2:def 9;
L1240: ( rng D97 ) = ( Seg C186 ) by L1239 , FUNCT_2:def 3;
L1241: ( rng ( C188 " ) ) c= ( dom D96 ) by L1240 , L1238 , FINSEQ_1:def 3;
L1242: ( dom ( D96 * ( C188 " ) ) ) = ( dom D97 ) by L1241 , RELAT_1:27;
L1243: C188 is (Permutation of ( Seg C186 )) by MATRIX_2:def 9;
L1244: (for R3 being Nat holds (for R4 being Nat holds ((R3 in ( dom D99 ) & R4 = ( ( C188 " ) . R3 )) implies ( D99 . R3 ) = ( ( C189 @ ) * (R3 , R4) ))))
proof
let R3 being Nat;
let R4 being Nat;
assume that
L1245: R3 in ( dom D99 )
and
L1246: R4 = ( ( C188 " ) . R3 );
L1247: R4 in ( Seg C186 ) by L1240 , L1242 , L1245 , L1246 , FUNCT_1:def 3;
L1248: R4 in ( dom D96 ) by L1247 , L1238 , FINSEQ_1:def 3;
L1249: ( rng D98 ) = ( Seg C186 ) by L1243 , FUNCT_2:def 3;
L1250: R3 = ( C188 . R4 ) by L1249 , L1242 , L1237 , L1245 , L1246 , FUNCT_1:32;
L1251: ( ( Path_matrix (C188 , C189) ) . R4 ) = ( C189 * (R4 , R3) ) by L1250 , L1248 , MATRIX_3:def 7;
L1252: ( dom C189 ) = ( Seg ( len C189 ) ) by FINSEQ_1:def 3
.= ( Seg C186 ) by MATRIX_1:def 2;
L1253: ( len C189 ) = C186 by MATRIX_1:def 2;
L1254: R3 in ( Seg ( width C189 ) ) by L1253 , L1236 , L1242 , L1237 , L1245 , MATRIX_1:20;
L1255: [ R4 , R3 ] in ( Indices C189 ) by L1254 , L1247 , L1252 , ZFMISC_1:def 2;
L1256: ( ( ( Path_matrix (C188 , C189) ) * ( C188 " ) ) . R3 ) = ( ( Path_matrix (C188 , C189) ) . ( ( C188 " ) . R3 ) ) by L1242 , L1245 , FUNCT_1:13;
thus L1257: thesis by L1256 , L1246 , L1251 , L1255 , MATRIX_1:def 6;
end;
L1258: ( len D99 ) = C186 by L1242 , L1237 , FINSEQ_1:def 3;
thus L1259: thesis by L1258 , L1244 , MATRIX_3:def 7;
end;
theorem
L1260: (for B244 being (Element of ( NAT )) holds (for B245 being Field holds (for B246 being (Element of ( Permutations B244 )) holds (for B247 being (Matrix of B244 , B245) holds (B244 >= 1 implies ( ( Path_product ( B247 @ ) ) . ( B246 " ) ) = ( ( Path_product B247 ) . B246 ))))))
proof
let C190 being (Element of ( NAT ));
let C191 being Field;
let C192 being (Element of ( Permutations C190 ));
let C193 being (Matrix of C190 , C191);
assume L1261: C190 >= 1;
L1262: ( len ( Path_matrix (C192 , C193) ) ) = C190 by MATRIX_3:def 7;
reconsider D100 = ( ( Path_matrix (C192 , C193) ) * ( C192 " ) ) as (FinSequence of C191) by L1262 , L1261 , L1225;
L1263: ( ( Path_product ( C193 @ ) ) . ( C192 " ) ) = ( - (( (the multF of C191) $$ ( Path_matrix (( C192 " ) , ( C193 @ )) ) ) , ( C192 " )) ) by MATRIX_3:def 8
.= ( - (( (the multF of C191) $$ D100 ) , ( C192 " )) ) by L1261 , L1235
.= ( - (( (the multF of C191) $$ D100 ) , C192) ) by L1261 , L1159
.= ( - (( (the multF of C191) $$ ( Path_matrix (C192 , C193) ) ) , C192) ) by L1262 , L1170 , L1214;
thus L1264: thesis by L1263 , MATRIX_3:def 8;
end;
theorem
L1265: (for B248 being (Element of ( NAT )) holds (for B249 being Field holds (for B250 being (Matrix of B248 , B249) holds (B248 >= 1 implies ( Det B250 ) = ( Det ( B250 @ ) )))))
proof
let C194 being (Element of ( NAT ));
let C195 being Field;
let C196 being (Matrix of C194 , C195);
set D101 = ( Path_product C196 );
set D102 = ( Path_product ( C196 @ ) );
set D103 = (the addF of C195);
set D104 = (the carrier of C195);
set D105 = ( Permutations C194 );
set D106 = ( FinOmega ( Permutations C194 ) );
set D107 = ( (the addF of C195) $$ (( FinOmega ( Permutations C194 ) ) , ( Path_product ( C196 @ ) )) );
L1266: ( Det C196 ) = ( (the addF of C195) $$ (( FinOmega ( Permutations C194 ) ) , ( Path_product C196 )) ) by MATRIX_3:def 9;
L1267: D106 = ( Permutations C194 ) by MATRIX_2:26 , MATRIX_2:def 14;
L1268: { ( B251 " ) where B251 is (Permutation of ( Seg C194 )) : B251 in D106 } c= D106
proof
let C197 being set;
assume L1269: C197 in { ( B252 " ) where B252 is (Permutation of ( Seg C194 )) : B252 in D106 };
L1270: (ex B253 being (Permutation of ( Seg C194 )) st (C197 = ( B253 " ) & B253 in D106)) by L1269;
thus L1271: thesis by L1270 , L1267 , MATRIX_2:def 9;
end;
L1272: D106 c= { ( B254 " ) where B254 is (Permutation of ( Seg C194 )) : B254 in D106 }
proof
let C198 being set;
assume L1273: C198 in D106;
reconsider D108 = C198 as (Permutation of ( Seg C194 )) by L1273 , L1267 , MATRIX_2:def 9;
set D109 = ( D108 " );
L1274: (( D109 " ) = D108 & D109 in D106) by L1267 , FUNCT_1:43 , MATRIX_2:def 9;
thus L1275: thesis by L1274;
end;
L1276: (D106 <> ( {} ) or D103 is  having_a_unity) by MATRIX_2:26 , MATRIX_2:def 14;
consider C199 being (Function of ( Fin D105 ) , D104) such that L1277: D107 = ( C199 . D106 ) and L1278: (for B255 being (Element of D104) holds (B255 is_a_unity_wrt D103 implies ( C199 . ( {} ) ) = B255)) and L1279: (for B256 being (Element of D105) holds ( C199 . { B256 } ) = ( D102 . B256 )) and L1280: (for B257 being (Element of ( Fin D105 )) holds ((B257 c= D106 & B257 <> ( {} )) implies (for B258 being (Element of D105) holds (B258 in ( D106 \ B257 ) implies ( C199 . ( B257 \/ { B258 } ) ) = ( D103 . (( C199 . B257 ) , ( D102 . B258 )) ))))) by L1276 , SETWISEO:def 3;
deffunc H6(set) = ( C199 . { ( B259 " ) where B259 is (Permutation of ( Seg C194 )) : B259 in $1 } );
L1281: (for B260 being set holds (B260 in ( Fin D105 ) implies H6(B260) in D104))
proof
let C200 being set;
assume L1282: C200 in ( Fin D105 );
L1283: { ( B261 " ) where B261 is (Permutation of ( Seg C194 )) : B261 in C200 } c= D105
proof
let C201 being set;
assume L1284: C201 in { ( B262 " ) where B262 is (Permutation of ( Seg C194 )) : B262 in C200 };
L1285: (ex B263 being (Permutation of ( Seg C194 )) st (C201 = ( B263 " ) & B263 in C200)) by L1284;
thus L1286: thesis by L1285 , MATRIX_2:def 9;
end;
L1287: { ( B264 " ) where B264 is (Permutation of ( Seg C194 )) : B264 in C200 } is (Finite_Subset of D105) by L1283 , FINSUB_1:18 , MATRIX_2:26;
thus L1288: thesis by L1287 , FUNCT_2:5;
end;
consider C202 being (Function of ( Fin D105 ) , D104) such that L1289: (for B265 being set holds (B265 in ( Fin D105 ) implies ( C202 . B265 ) = H6(B265))) from FUNCT_2:sch 2(L1281);
assume L1290: C194 >= 1;
L1291: (for B266 being (Element of D105) holds ( C202 . { B266 } ) = ( D101 . B266 ))
proof
let C203 being (Element of D105);
reconsider D110 = {. C203 .} as (Element of ( Fin D105 ));
reconsider D111 = C203 as (Permutation of ( Seg C194 )) by MATRIX_2:def 9;
L1292: ( D111 " ) is (Element of D105) by MATRIX_2:def 9;
L1293: { ( B267 " ) where B267 is (Permutation of ( Seg C194 )) : B267 in D110 } c= { ( D111 " ) }
proof
let C204 being set;
assume L1294: C204 in { ( B268 " ) where B268 is (Permutation of ( Seg C194 )) : B268 in D110 };
consider C205 being (Permutation of ( Seg C194 )) such that L1295: C204 = ( C205 " ) and L1296: C205 in D110 by L1294;
L1297: C205 = C203 by L1296 , TARSKI:def 1;
thus L1298: thesis by L1297 , L1295 , TARSKI:def 1;
end;
L1299: { ( D111 " ) } c= { ( B269 " ) where B269 is (Permutation of ( Seg C194 )) : B269 in D110 }
proof
let C206 being set;
assume L1300: C206 in { ( D111 " ) };
L1301: (D111 in D110 & C206 = ( D111 " )) by L1300 , TARSKI:def 1;
thus L1302: thesis by L1301;
end;
L1303: { ( B270 " ) where B270 is (Permutation of ( Seg C194 )) : B270 in D110 } = { ( D111 " ) } by L1299 , L1293 , XBOOLE_0:def 10;
L1304: ( C202 . D110 ) = ( C199 . { ( D111 " ) } ) by L1303 , L1289
.= ( D102 . ( D111 " ) ) by L1279 , L1292
.= ( ( Path_product C196 ) . D111 ) by L1290 , L1260;
thus L1305: thesis by L1304;
end;
L1306: (for B271 being (Element of ( Fin D105 )) holds ((B271 c= D106 & B271 <> ( {} )) implies (for B272 being (Element of D105) holds (B272 in ( D106 \ B271 ) implies ( C202 . ( B271 \/ { B272 } ) ) = ( D103 . (( C202 . B271 ) , ( D101 . B272 )) )))))
proof
let C207 being (Element of ( Fin D105 ));
assume that
L1307: C207 c= D106
and
L1308: C207 <> ( {} );
thus L1309: (for B273 being (Element of D105) holds (B273 in ( D106 \ C207 ) implies ( C202 . ( C207 \/ { B273 } ) ) = ( D103 . (( C202 . C207 ) , ( D101 . B273 )) )))
proof
L1310: { ( B274 " ) where B274 is (Permutation of ( Seg C194 )) : B274 in C207 } c= D105
proof
let C208 being set;
assume L1311: C208 in { ( B275 " ) where B275 is (Permutation of ( Seg C194 )) : B275 in C207 };
L1312: (ex B276 being (Permutation of ( Seg C194 )) st (( B276 " ) = C208 & B276 in C207)) by L1311;
thus L1313: thesis by L1312 , MATRIX_2:def 9;
end;
reconsider D112 = { ( B277 " ) where B277 is (Permutation of ( Seg C194 )) : B277 in C207 } as (Element of ( Fin D105 )) by L1310 , FINSUB_1:18 , MATRIX_2:26;
set D113 = the (Element of C207);
let C209 being (Element of D105);
reconsider D114 = C209 as (Permutation of ( Seg C194 )) by MATRIX_2:def 9;
reconsider D115 = ( D114 " ) as (Element of D105) by MATRIX_2:def 9;
L1314: ( D112 \/ { D115 } ) c= { ( B278 " ) where B278 is (Permutation of ( Seg C194 )) : B278 in ( C207 \/ { C209 } ) }
proof
let C210 being set;
assume L1315: C210 in ( D112 \/ { D115 } );
L1316: (C210 in D112 or C210 in { D115 }) by L1315 , XBOOLE_0:def 3;
L1317:
now
per cases  by L1316 , TARSKI:def 1;
case L1318: C210 in D112;
consider C211 being (Permutation of ( Seg C194 )) such that L1319: C210 = ( C211 " ) and L1320: C211 in C207 by L1318;
L1321: C211 in ( C207 \/ { C209 } ) by L1320 , XBOOLE_0:def 3;
thus L1322: thesis by L1321 , L1319;
end;
case L1323: C210 = D115;
L1324: D114 in { C209 } by TARSKI:def 1;
L1325: D114 in ( C207 \/ { C209 } ) by L1324 , XBOOLE_0:def 3;
thus L1326: thesis by L1325 , L1323;
end;
end;
thus L1328: thesis by L1317;
end;
L1329: D112 c= D106
proof
let C212 being set;
assume L1330: C212 in D112;
L1331: (ex B279 being (Permutation of ( Seg C194 )) st (( B279 " ) = C212 & B279 in C207)) by L1330;
thus L1332: thesis by L1331 , L1267 , MATRIX_2:def 9;
end;
assume L1333: C209 in ( D106 \ C207 );
L1334: (not C209 in C207) by L1333 , XBOOLE_0:def 5;
L1335:
now
assume L1336: D115 in D112;
consider C213 being (Permutation of ( Seg C194 )) such that L1337: D115 = ( C213 " ) and L1338: C213 in C207 by L1336;
L1339: D114 = ( ( C213 " ) " ) by L1337 , FUNCT_1:43;
thus L1340: contradiction by L1339 , L1334 , L1338 , FUNCT_1:43;
end;
L1341: D115 in ( D106 \ D112 ) by L1335 , L1267 , XBOOLE_0:def 5;
L1342: D113 in D106 by L1307 , L1308 , TARSKI:def 3;
reconsider D116 = D113 as (Permutation of ( Seg C194 )) by L1342 , L1267 , MATRIX_2:def 9;
L1343: ( D116 " ) in D112 by L1308;
L1344: (( C202 . ( C207 \/ {. C209 .} ) ) = ( C199 . { ( B280 " ) where B280 is (Permutation of ( Seg C194 )) : B280 in ( C207 \/ { C209 } ) } ) & ( C199 . D112 ) = ( C202 . C207 )) by L1289;
L1345: { ( B281 " ) where B281 is (Permutation of ( Seg C194 )) : B281 in ( C207 \/ { C209 } ) } c= ( D112 \/ { D115 } )
proof
let C214 being set;
assume L1346: C214 in { ( B282 " ) where B282 is (Permutation of ( Seg C194 )) : B282 in ( C207 \/ { C209 } ) };
consider C215 being (Permutation of ( Seg C194 )) such that L1347: C214 = ( C215 " ) and L1348: C215 in ( C207 \/ { C209 } ) by L1346;
L1349:
now
per cases  by L1348 , XBOOLE_0:def 3;
case L1350: C215 in C207;
thus L1351: (C214 in D112 or C214 in { D115 }) by L1350 , L1347;
end;
case L1352: C215 in { C209 };
L1353: C215 = C209 by L1352 , TARSKI:def 1;
thus L1354: (C214 in D112 or C214 in { D115 }) by L1353 , L1347 , TARSKI:def 1;
end;
end;
thus L1356: thesis by L1349 , XBOOLE_0:def 3;
end;
L1357: ( D112 \/ { D115 } ) = { ( B283 " ) where B283 is (Permutation of ( Seg C194 )) : B283 in ( C207 \/ { C209 } ) } by L1345 , L1314 , XBOOLE_0:def 10;
L1358: ( C199 . { ( B284 " ) where B284 is (Permutation of ( Seg C194 )) : B284 in ( C207 \/ { C209 } ) } ) = ( D103 . (( C199 . D112 ) , ( D102 . D115 )) ) by L1357 , L1280 , L1329 , L1343 , L1341;
thus L1359: thesis by L1358 , L1290 , L1344 , L1260;
end;

end;
L1310: (for B285 being (Element of D104) holds (B285 is_a_unity_wrt D103 implies ( C202 . ( {} ) ) = B285))
proof
L1311: ( {} ) is (Subset of D105) by SUBSET_1:1;
reconsider D117 = ( {} ) as (Element of ( Fin D105 )) by L1311 , FINSUB_1:18 , MATRIX_2:26;
let C216 being (Element of D104);
L1312: { ( B286 " ) where B286 is (Permutation of ( Seg C194 )) : B286 in D117 } c= ( {} )
proof
let C217 being set;
assume L1313: C217 in { ( B287 " ) where B287 is (Permutation of ( Seg C194 )) : B287 in D117 };
L1314: (ex B288 being (Permutation of ( Seg C194 )) st (C217 = ( B288 " ) & B288 in D117)) by L1313;
thus L1315: thesis by L1314;
end;
L1316: { ( B289 " ) where B289 is (Permutation of ( Seg C194 )) : B289 in D117 } = ( {} ) by L1312;
assume L1317: C216 is_a_unity_wrt D103;
L1318: ( C199 . { ( B290 " ) where B290 is (Permutation of ( Seg C194 )) : B290 in D117 } ) = C216 by L1317 , L1278 , L1316;
thus L1319: thesis by L1318 , L1289;
end;
L1320: ( C202 . D106 ) = ( C199 . { ( B291 " ) where B291 is (Permutation of ( Seg C194 )) : B291 in D106 } ) by L1289;
L1321: D107 = ( C202 . D106 ) by L1320 , L1277 , L1268 , L1272 , XBOOLE_0:def 10;
L1322: ( (the addF of C195) $$ (( FinOmega ( Permutations C194 ) ) , ( Path_product C196 )) ) = ( (the addF of C195) $$ (( FinOmega ( Permutations C194 ) ) , ( Path_product ( C196 @ ) )) ) by L1321 , L1276 , L1310 , L1291 , L1306 , SETWISEO:def 3;
thus L1323: thesis by L1322 , L1266 , MATRIX_3:def 9;
end;
