:: Properties of Caratheodory's Measure
::  by J\'ozef Bia{\l}as
::
:: Received June 25, 1992
:: Copyright (c) 1992-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, SUPINF_1, PROB_1, XBOOLE_0, SETFAM_1, FUNCT_1, SUBSET_1,
      TARSKI, RELAT_1, CARD_1, ARYTM_3, NAT_1, XXREAL_0, ZFMISC_1, MEASURE1,
      SUPINF_2, VALUED_0, FUNCOP_1, XREAL_0, ARYTM_1, REAL_1, MEASURE3,
      MEASURE4;
 notations TARSKI, XBOOLE_0, ENUMSET1, ZFMISC_1, SUBSET_1, NUMBERS, FUNCT_1,
      RELSET_1, PARTFUN1, FUNCT_2, XXREAL_0, XREAL_0, VALUED_0, FUNCOP_1,
      REAL_1, ORDINAL1, NAT_1, SETFAM_1, PROB_1, SUPINF_1, SUPINF_2, MEASURE1,
      MEASURE3;
 constructors ENUMSET1, PARTFUN1, REAL_1, NAT_1, PROB_2, MEASURE3, SUPINF_1,
      FUNCOP_1, RELSET_1;
 registrations XBOOLE_0, SUBSET_1, ORDINAL1, RELSET_1, FUNCT_2, NUMBERS,
      XXREAL_0, XREAL_0, NAT_1, MEASURE1, VALUED_0, MEMBERED;
 requirements REAL, NUMERALS, SUBSET, BOOLE, ARITHM;
 definitions TARSKI, MEASURE3, XBOOLE_0;
 theorems TARSKI, ENUMSET1, FUNCT_1, FUNCT_2, ZFMISC_1, NAT_1, SUPINF_2,
      MEASURE1, MEASURE2, MEASURE3, XBOOLE_0, XBOOLE_1, XXREAL_0, PROB_1,
      ORDINAL1, VALUED_0, XXREAL_3, FUNCOP_1;
 schemes NAT_1, FUNCT_2, XBOOLE_0;

begin
theorem
L1: (for R3 being set holds (for B1 being non  empty (Subset-Family of R3) holds (for B2 , B3 being (Function of ( NAT ) , B1) holds (for B4 being (Element of B1) holds ((for B5 being (Element of ( NAT )) holds ( B3 . B5 ) = ( B4 /\ ( B2 . B5 ) )) implies ( union ( rng B3 ) ) = ( B4 /\ ( union ( rng B2 ) ) ))))))
proof
let R3 being set;
let C1 being non  empty (Subset-Family of R3);
let C2 , C3 being (Function of ( NAT ) , C1);
let C4 being (Element of C1);
assume L2: (for B6 being (Element of ( NAT )) holds ( C3 . B6 ) = ( C4 /\ ( C2 . B6 ) ));
thus L3: ( union ( rng C3 ) ) c= ( C4 /\ ( union ( rng C2 ) ) )
proof
let C5 being set;
assume L4: C5 in ( union ( rng C3 ) );
consider C6 being set such that L5: C5 in C6 and L6: C6 in ( rng C3 ) by L4 , TARSKI:def 4;
consider C7 being set such that L7: C7 in ( dom C3 ) and L8: C6 = ( C3 . C7 ) by L6 , FUNCT_1:def 3;
reconsider D1 = C7 as (Element of ( NAT )) by L7;
L9: C5 in ( C4 /\ ( C2 . D1 ) ) by L2 , L5 , L8;
L10: C5 in C4 by L9 , XBOOLE_0:def 4;
L11: ( C2 . D1 ) in ( rng C2 ) by FUNCT_2:4;
L12: C5 in ( C2 . D1 ) by L9 , XBOOLE_0:def 4;
L13: C5 in ( union ( rng C2 ) ) by L12 , L11 , TARSKI:def 4;
thus L14: thesis by L13 , L10 , XBOOLE_0:def 4;
end;

let C8 being set;
assume L15: C8 in ( C4 /\ ( union ( rng C2 ) ) );
L16: C8 in C4 by L15 , XBOOLE_0:def 4;
L17: C8 in ( union ( rng C2 ) ) by L15 , XBOOLE_0:def 4;
consider C9 being set such that L18: C8 in C9 and L19: C9 in ( rng C2 ) by L17 , TARSKI:def 4;
consider C10 being set such that L20: C10 in ( dom C2 ) and L21: C9 = ( C2 . C10 ) by L19 , FUNCT_1:def 3;
reconsider D2 = C10 as (Element of ( NAT )) by L20;
L22: ( C3 . D2 ) in ( rng C3 ) by FUNCT_2:4;
L23: ( C4 /\ C9 ) = ( C3 . D2 ) by L2 , L21;
L24: C8 in ( C3 . D2 ) by L23 , L16 , L18 , XBOOLE_0:def 4;
thus L25: thesis by L24 , L22 , TARSKI:def 4;
end;
theorem
L26: (for R3 being set holds (for B7 being non  empty (Subset-Family of R3) holds (for B8 , B9 being (Function of ( NAT ) , B7) holds ((( B9 . ( 0 ) ) = ( B8 . ( 0 ) ) & (for B10 being (Element of ( NAT )) holds ( B9 . ( B10 + 1 ) ) = ( ( B8 . ( B10 + 1 ) ) \/ ( B9 . B10 ) ))) implies (for B11 being (Function of ( NAT ) , B7) holds ((( B11 . ( 0 ) ) = ( B8 . ( 0 ) ) & (for B12 being (Element of ( NAT )) holds ( B11 . ( B12 + 1 ) ) = ( ( B8 . ( B12 + 1 ) ) \ ( B9 . B12 ) ))) implies ( union ( rng B8 ) ) = ( union ( rng B11 ) )))))))
proof
let R3 being set;
let C11 being non  empty (Subset-Family of R3);
let C12 , C13 being (Function of ( NAT ) , C11);
assume that
L27: ( C13 . ( 0 ) ) = ( C12 . ( 0 ) )
and
L28: (for B13 being (Element of ( NAT )) holds ( C13 . ( B13 + 1 ) ) = ( ( C12 . ( B13 + 1 ) ) \/ ( C13 . B13 ) ));
let C14 being (Function of ( NAT ) , C11);
assume that
L29: ( C14 . ( 0 ) ) = ( C12 . ( 0 ) )
and
L30: (for B14 being (Element of ( NAT )) holds ( C14 . ( B14 + 1 ) ) = ( ( C12 . ( B14 + 1 ) ) \ ( C13 . B14 ) ));
thus L31: ( union ( rng C12 ) ) c= ( union ( rng C14 ) )
proof
let C15 being set;
assume L32: C15 in ( union ( rng C12 ) );
consider C16 being set such that L33: C15 in C16 and L34: C16 in ( rng C12 ) by L32 , TARSKI:def 4;
L35: (ex B15 being set st (B15 in ( dom C12 ) & C16 = ( C12 . B15 ))) by L34 , FUNCT_1:def 3;
L36: (ex B16 being (Element of ( NAT )) st C15 in ( C14 . B16 ))
proof
defpred S1[ Nat ] means C15 in ( C12 . $1 );
L37: (ex B17 being Nat st S1[ B17 ]) by L33 , L35;
L38: (ex B18 being Nat st (S1[ B18 ] & (for B19 being Nat holds (S1[ B19 ] implies B18 <= B19)))) from NAT_1:sch 5(L37);
consider C17 being Nat such that L39: C15 in ( C12 . C17 ) and L40: (for B20 being Nat holds (C15 in ( C12 . B20 ) implies C17 <= B20)) by L38;
L41: ((ex B21 being Nat st C17 = ( B21 + 1 )) implies (ex B22 being (Element of ( NAT )) st C15 in ( C14 . B22 )))
proof
given C18 being Nat such that
L42: C17 = ( C18 + 1 );

take C17;
reconsider D3 = C18 as (Element of ( NAT )) by ORDINAL1:def 12;
L43: (not C15 in ( C13 . D3 ))
proof
assume L44: C15 in ( C13 . D3 );
consider C19 being (Element of ( NAT )) such that L45: C19 <= D3 and L46: C15 in ( C12 . C19 ) by L44 , L27 , L28 , MEASURE2:5;
L47: C17 <= C19 by L40 , L46;
thus L48: thesis by L47 , L42 , L45 , NAT_1:13;
end;
L49: ( C14 . ( D3 + 1 ) ) = ( ( C12 . ( D3 + 1 ) ) \ ( C13 . D3 ) ) by L30;
thus L50: thesis by L49 , L39 , L42 , L43 , XBOOLE_0:def 5;
end;
L51: (C17 = ( 0 ) implies (ex B23 being (Element of ( NAT )) st C15 in ( C14 . B23 ))) by L29 , L39;
thus L52: thesis by L51 , L41 , NAT_1:6;
end;
consider C20 being (Element of ( NAT )) such that L53: C15 in ( C14 . C20 ) by L36;
L54: ( C14 . C20 ) in ( rng C14 ) by FUNCT_2:4;
thus L55: thesis by L54 , L53 , TARSKI:def 4;
end;

L56: (for B24 being (Element of ( NAT )) holds ( C14 . B24 ) c= ( C12 . B24 ))
proof
let C21 being (Element of ( NAT ));
L57: ((ex B25 being Nat st C21 = ( B25 + 1 )) implies ( C14 . C21 ) c= ( C12 . C21 ))
proof
given C22 being Nat such that
L58: C21 = ( C22 + 1 );

reconsider D4 = C22 as (Element of ( NAT )) by ORDINAL1:def 12;
L59: ( C14 . C21 ) = ( ( C12 . C21 ) \ ( C13 . D4 ) ) by L30 , L58;
thus L60: thesis by L59;
end;
L61: (C21 = ( 0 ) implies ( C14 . C21 ) c= ( C12 . C21 )) by L29;
thus L62: thesis by L61 , L57 , NAT_1:6;
end;
L63: ( union ( rng C14 ) ) c= ( union ( rng C12 ) )
proof
let C23 being set;
assume L64: C23 in ( union ( rng C14 ) );
consider C24 being set such that L65: C23 in C24 and L66: C24 in ( rng C14 ) by L64 , TARSKI:def 4;
consider C25 being set such that L67: C25 in ( dom C14 ) and L68: C24 = ( C14 . C25 ) by L66 , FUNCT_1:def 3;
reconsider D5 = C25 as (Element of ( NAT )) by L67;
L69: ( C12 . D5 ) in ( rng C12 ) by FUNCT_2:4;
L70: C24 c= ( C12 . D5 ) by L56 , L68;
thus L71: thesis by L70 , L65 , L69 , TARSKI:def 4;
end;
thus L72: thesis by L63;
end;
theorem
L73: (for R3 being set holds ( bool R3 ) is (SigmaField of R3))
proof
let R3 being set;
L74: (for B26 being (N_Sub_set_fam of R3) holds (B26 c= ( bool R3 ) implies ( union B26 ) in ( bool R3 )));
reconsider D6 = ( bool R3 ) as (Subset-Family of R3);
L75: (for B27 being set holds (B27 in ( bool R3 ) implies ( R3 \ B27 ) in ( bool R3 )));
reconsider D7 = D6 as non  empty  compl-closed  sigma-additive (Subset-Family of R3) by L75 , L74 , MEASURE1:def 1 , MEASURE1:def 5;
L76: D7 is (SigmaField of R3);
thus L77: thesis by L76;
end;
definition
let C26 being set;
mode C_Measure of C26
 -> (Function of ( bool C26 ) , ( ExtREAL ))
means :L78: (it is  nonnegative  zeroed & (for B28 , B29 being (Subset of C26) holds (B28 c= B29 implies (( it . B28 ) <= ( it . B29 ) & (for B30 being (Function of ( NAT ) , ( bool C26 )) holds ( it . ( union ( rng B30 ) ) ) <= ( SUM ( it * B30 ) ))))));
existence
proof
set D8 = ( ( bool C26 ) --> ( 0. ) );
take D8;
L79: (for B31 being (Subset of C26) holds ( 0. ) <= ( D8 . B31 ));
L80: D8 is  nonnegative by L79 , MEASURE1:def 2;
L81: (for B32 being (Function of ( NAT ) , ( bool C26 )) holds ( D8 . ( union ( rng B32 ) ) ) <= ( SUM ( D8 * B32 ) ))
proof
let C27 being (Function of ( NAT ) , ( bool C26 ));
L82: ( D8 . ( union ( rng C27 ) ) ) = ( 0. ) by FUNCOP_1:7;
L83: (for B33 being (Element of ( NAT )) holds (( 0 ) <= B33 implies ( ( D8 * C27 ) . B33 ) = ( 0. )))
proof
let C28 being (Element of ( NAT ));
L84: ( dom ( D8 * C27 ) ) = ( NAT ) by FUNCT_2:def 1;
L85: ( ( D8 * C27 ) . C28 ) = ( D8 . ( C27 . C28 ) ) by L84 , FUNCT_1:12;
thus L86: thesis by L85 , FUNCOP_1:7;
end;
L87: ( ( Ser ( D8 * C27 ) ) . ( 0 ) ) = ( ( D8 * C27 ) . ( 0 ) ) by SUPINF_2:44;
L88: ( D8 * C27 ) is  nonnegative by L80 , MEASURE1:25;
thus L89: thesis by L88 , L82 , L83 , L87 , SUPINF_2:48;
end;
L90: ( {} ) c= C26 by XBOOLE_1:2;
L91: ( D8 . ( {} ) ) = ( 0. ) by L90 , FUNCOP_1:7;
thus L92: thesis by L91 , L79 , L81 , FUNCOP_1:7 , MEASURE1:def 2 , VALUED_0:def 19;
end;
end;
definition
let C29 being set;
let C30 being (C_Measure of C29);
func sigma_Field C30 -> non  empty (Subset-Family of C29) means 
:L94: (for B34 being (Subset of C29) holds (B34 in it iff (for B35 , B36 being (Subset of C29) holds ((B35 c= B34 & B36 c= ( C29 \ B34 )) implies ( ( C30 . B35 ) + ( C30 . B36 ) ) <= ( C30 . ( B35 \/ B36 ) )))));
existence
proof
reconsider D9 = ( {} ) as (Subset of C29) by XBOOLE_1:2;
defpred S2[ set ] means (for B37 being set holds (B37 = $1 implies (for B38 , B39 being (Subset of C29) holds ((B38 c= B37 & B39 c= ( C29 \ B37 )) implies ( ( C30 . B38 ) + ( C30 . B39 ) ) <= ( C30 . ( B38 \/ B39 ) )))));
consider C31 being set such that L95: (for B40 being set holds (B40 in C31 iff (B40 in ( bool C29 ) & S2[ B40 ]))) from XBOOLE_0:sch 1;
L96: (for B41 being set holds (B41 in C31 iff (B41 in ( bool C29 ) & (for B42 , B43 being (Subset of C29) holds ((B42 c= B41 & B43 c= ( C29 \ B41 )) implies ( ( C30 . B42 ) + ( C30 . B43 ) ) <= ( C30 . ( B42 \/ B43 ) ))))))
proof
let C32 being set;
L97: (S2[ C32 ] iff (for B44 , B45 being (Subset of C29) holds ((B44 c= C32 & B45 c= ( C29 \ C32 )) implies ( ( C30 . B44 ) + ( C30 . B45 ) ) <= ( C30 . ( B44 \/ B45 ) ))));
thus L98: thesis by L97 , L95;
end;
L99: (for B46 being set holds (B46 in C31 implies B46 in ( bool C29 ))) by L96;
L100:
now
let C33 , C34 being (Subset of C29);
assume that
L101: C33 c= D9
and
L102: C34 c= ( C29 \ D9 );
L103: C33 = ( {} ) by L101;
L104: C30 is  zeroed by L78;
L105: ( C30 . C33 ) = ( 0 ) by L104 , L103 , VALUED_0:def 19;
thus L106: ( ( C30 . C33 ) + ( C30 . C34 ) ) <= ( C30 . ( C33 \/ C34 ) ) by L105 , L103 , XXREAL_3:4;
end;
reconsider D10 = C31 as non  empty (Subset-Family of C29) by L100 , L96 , L99 , TARSKI:def 3;
take D10;
thus L107: thesis by L96;
end;
uniqueness
proof
let C35 , C36 being non  empty (Subset-Family of C29);
assume that
L108: (for B47 being (Subset of C29) holds (B47 in C35 iff (for B48 , B49 being (Subset of C29) holds ((B48 c= B47 & B49 c= ( C29 \ B47 )) implies ( ( C30 . B48 ) + ( C30 . B49 ) ) <= ( C30 . ( B48 \/ B49 ) )))))
and
L109: (for B50 being (Subset of C29) holds (B50 in C36 iff (for B51 , B52 being (Subset of C29) holds ((B51 c= B50 & B52 c= ( C29 \ B50 )) implies ( ( C30 . B51 ) + ( C30 . B52 ) ) <= ( C30 . ( B51 \/ B52 ) )))));
L110: (for B53 being set holds (B53 in C35 iff B53 in C36))
proof
let C37 being set;
thus L111:now
assume L112: C37 in C35;
reconsider D11 = C37 as (Subset of C29) by L112;
L113: (for B54 , B55 being (Subset of C29) holds ((B54 c= C37 & B55 c= ( C29 \ D11 )) implies ( ( C30 . B54 ) + ( C30 . B55 ) ) <= ( C30 . ( B54 \/ B55 ) ))) by L108 , L112;
thus L114: C37 in C36 by L113 , L109;
end;
assume L115: C37 in C36;
reconsider D12 = C37 as (Subset of C29) by L115;
L116: (for B56 , B57 being (Subset of C29) holds ((B56 c= D12 & B57 c= ( C29 \ D12 )) implies ( ( C30 . B56 ) + ( C30 . B57 ) ) <= ( C30 . ( B56 \/ B57 ) ))) by L109 , L115;
thus L117: thesis by L116 , L108;
end;
thus L118: thesis by L110 , TARSKI:1;
end;
end;
theorem
L120: (for R3 being set holds (for R5 being (C_Measure of R3) holds (for B58 , B59 being (Subset of R3) holds ( R5 . ( B58 \/ B59 ) ) <= ( ( R5 . B58 ) + ( R5 . B59 ) ))))
proof
let R3 being set;
let R5 being (C_Measure of R3);
let C38 , C39 being (Subset of R3);
reconsider D13 = ( {} ) as (Subset of R3) by XBOOLE_1:2;
consider C40 being (Function of ( NAT ) , ( bool R3 )) such that L121: ( rng C40 ) = { C38 , C39 , D13 } and L122: ( C40 . ( 0 ) ) = C38 and L123: ( C40 . 1 ) = C39 and L124: (for B60 being (Element of ( NAT )) holds (1 < B60 implies ( C40 . B60 ) = D13)) by MEASURE1:17;
L125: ( ( R5 * C40 ) . 1 ) = ( R5 . C39 ) by L123 , FUNCT_2:15;
set D14 = ( R5 * C40 );
L126: ( union { C38 , C39 , D13 } ) = ( C38 \/ C39 )
proof
thus L127: ( union { C38 , C39 , D13 } ) c= ( C38 \/ C39 )
proof
let C41 being set;
assume L128: C41 in ( union { C38 , C39 , D13 } );
L129: (ex B61 being set st (C41 in B61 & B61 in { C38 , C39 , D13 })) by L128 , TARSKI:def 4;
L130: (C41 in C38 or C41 in C39 or C41 in D13) by L129 , ENUMSET1:def 1;
thus L131: thesis by L130 , XBOOLE_0:def 3;
end;

let C42 being set;
assume L132: C42 in ( C38 \/ C39 );
L133:
now
per cases  by L132 , XBOOLE_0:def 3;
suppose L134: C42 in C38;

take D15 = C38;
thus L135: (C42 in D15 & D15 in { C38 , C39 , D13 }) by L134 , ENUMSET1:def 1;
end;
suppose L136: C42 in C39;

take D16 = C39;
thus L137: (C42 in D16 & D16 in { C38 , C39 , D13 }) by L136 , ENUMSET1:def 1;
end;
end;
thus L139: thesis by L133 , TARSKI:def 4;
end;
L140: R5 is  zeroed by L78;
L141: (for B62 being (Element of ( NAT )) holds (2 <= B62 implies ( ( R5 * C40 ) . B62 ) = ( 0. )))
proof
let C43 being (Element of ( NAT ));
assume L142: 2 <= C43;
L143: ( 1 + 1 ) <= C43 by L142;
L144: 1 < C43 by L143 , NAT_1:13;
L145: ( C40 . C43 ) = ( {} ) by L144 , L124;
L146: R5 is  zeroed by L78;
L147: ( R5 . ( C40 . C43 ) ) = ( 0. ) by L146 , L145 , VALUED_0:def 19;
thus L148: thesis by L147 , FUNCT_2:15;
end;
L149: R5 is  nonnegative by L78;
L150: ( R5 * C40 ) is  nonnegative by L149 , MEASURE1:25;
L151: ( C40 . 2 ) = D13 by L124;
L152: ( ( R5 * C40 ) . 2 ) = ( R5 . D13 ) by L151 , FUNCT_2:15;
L153: ( ( R5 * C40 ) . ( 0 ) ) = ( R5 . C38 ) by L122 , FUNCT_2:15;
consider C44 , C45 being R_eal such that L154: C44 = ( ( Ser D14 ) . 1 ) and L155: C45 = ( ( Ser D14 ) . ( 0 ) );
L156: ( ( Ser D14 ) . 2 ) = ( C44 + ( D14 . ( 1 + 1 ) ) ) by L154 , SUPINF_2:44
.= ( ( ( Ser D14 ) . 1 ) + ( 0. ) ) by L152 , L154 , L140 , VALUED_0:def 19
.= ( ( Ser D14 ) . 1 ) by XXREAL_3:4
.= ( C45 + ( D14 . ( ( 0 ) + 1 ) ) ) by L155 , SUPINF_2:44
.= ( ( R5 . C38 ) + ( R5 . C39 ) ) by L125 , L153 , L155 , SUPINF_2:44;
L157: ( SUM ( R5 * C40 ) ) = ( ( R5 . C38 ) + ( R5 . C39 ) ) by L156 , L150 , L141 , SUPINF_2:48;
thus L158: thesis by L157 , L121 , L126 , L78;
end;
theorem
L159: (for R3 being set holds (for R5 being (C_Measure of R3) holds (for B63 being (Subset of R3) holds (B63 in ( sigma_Field R5 ) iff (for B64 , B65 being (Subset of R3) holds ((B64 c= B63 & B65 c= ( R3 \ B63 )) implies ( ( R5 . B64 ) + ( R5 . B65 ) ) = ( R5 . ( B64 \/ B65 ) )))))))
proof
let R3 being set;
let R5 being (C_Measure of R3);
let C46 being (Subset of R3);
thus L160:now
assume L161: C46 in ( sigma_Field R5 );
let C47 , C48 being (Subset of R3);
assume that
L162: C47 c= C46
and
L163: C48 c= ( R3 \ C46 );
L164: ( R5 . ( C47 \/ C48 ) ) <= ( ( R5 . C47 ) + ( R5 . C48 ) ) by L120;
L165: ( ( R5 . C47 ) + ( R5 . C48 ) ) <= ( R5 . ( C47 \/ C48 ) ) by L161 , L162 , L163 , L94;
thus L166: ( ( R5 . C47 ) + ( R5 . C48 ) ) = ( R5 . ( C47 \/ C48 ) ) by L165 , L164 , XXREAL_0:1;
end;
assume L167: (for B66 , B67 being (Subset of R3) holds ((B66 c= C46 & B67 c= ( R3 \ C46 )) implies ( ( R5 . B66 ) + ( R5 . B67 ) ) = ( R5 . ( B66 \/ B67 ) )));
L168: (for B68 , B69 being (Subset of R3) holds ((B68 c= C46 & B69 c= ( R3 \ C46 )) implies ( ( R5 . B68 ) + ( R5 . B69 ) ) <= ( R5 . ( B68 \/ B69 ) ))) by L167;
thus L169: thesis by L168 , L94;
end;
theorem
L170: (for R3 being set holds (for R5 being (C_Measure of R3) holds (for B70 , B71 being (Subset of R3) holds ((B70 in ( sigma_Field R5 ) & B71 misses B70) implies ( R5 . ( B70 \/ B71 ) ) = ( ( R5 . B70 ) + ( R5 . B71 ) )))))
proof
let R3 being set;
let R5 being (C_Measure of R3);
let C49 , C50 being (Subset of R3);
assume that
L171: C49 in ( sigma_Field R5 )
and
L172: C50 misses C49;
L173: ( C50 \ C49 ) c= ( R3 \ C49 ) by XBOOLE_1:33;
L174: C50 c= ( R3 \ C49 ) by L173 , L172 , XBOOLE_1:83;
thus L175: thesis by L174 , L171 , L159;
end;
theorem
L176: (for R1 being set holds (for R3 being set holds (for R5 being (C_Measure of R3) holds (R1 in ( sigma_Field R5 ) implies ( R3 \ R1 ) in ( sigma_Field R5 )))))
proof
let R1 being set;
let R3 being set;
let R5 being (C_Measure of R3);
assume L177: R1 in ( sigma_Field R5 );
L178: (for B72 , B73 being (Subset of R3) holds ((B72 c= ( R3 \ R1 ) & B73 c= ( R3 \ ( R3 \ R1 ) )) implies ( ( R5 . B72 ) + ( R5 . B73 ) ) <= ( R5 . ( B72 \/ B73 ) )))
proof
let C51 , C52 being (Subset of R3);
assume that
L179: C51 c= ( R3 \ R1 )
and
L180: C52 c= ( R3 \ ( R3 \ R1 ) );
L181: ( R3 \ ( R3 \ R1 ) ) = ( R3 /\ R1 ) by XBOOLE_1:48;
L182: C52 c= R1 by L181 , L177 , L180 , XBOOLE_1:28;
thus L183: thesis by L182 , L177 , L179 , L94;
end;
thus L184: thesis by L178 , L94;
end;
theorem
L185: (for R1 being set holds (for R2 being set holds (for R3 being set holds (for R5 being (C_Measure of R3) holds ((R1 in ( sigma_Field R5 ) & R2 in ( sigma_Field R5 )) implies ( R1 \/ R2 ) in ( sigma_Field R5 ))))))
proof
let R1 being set;
let R2 being set;
let R3 being set;
let R5 being (C_Measure of R3);
assume that
L186: R1 in ( sigma_Field R5 )
and
L187: R2 in ( sigma_Field R5 );
reconsider D17 = R1 , D18 = R2 as (Subset of R3) by L186 , L187;
set D19 = ( D17 \/ D18 );
L188: (for B74 , B75 being (Subset of R3) holds ((B74 c= D19 & B75 c= ( R3 \ D19 )) implies ( ( R5 . B74 ) + ( R5 . B75 ) ) = ( R5 . ( B74 \/ B75 ) )))
proof
let C53 , C54 being (Subset of R3);
assume that
L189: C53 c= D19
and
L190: C54 c= ( R3 \ D19 );
set D20 = ( C53 \ D17 );
set D21 = ( D20 \/ C54 );
L191: ( ( R3 \ D17 ) /\ ( R3 \ D18 ) ) c= ( R3 \ D18 ) by XBOOLE_1:17;
set D22 = ( C53 /\ D17 );
L192: D22 c= D17 by XBOOLE_1:17;
L193: ( ( R3 \ D17 ) /\ ( R3 \ D18 ) ) c= ( R3 \ D17 ) by XBOOLE_1:17;
L194: ( R3 \ ( D17 \/ D18 ) ) c= ( R3 \ D17 ) by L193 , XBOOLE_1:53;
L195: C54 c= ( ( R3 \ D17 ) /\ ( R3 \ D18 ) ) by L190 , XBOOLE_1:53;
L196: C54 c= ( R3 \ D18 ) by L195 , L191 , XBOOLE_1:1;
L197: C53 = ( D22 \/ D20 ) by XBOOLE_1:51;
L198: ( R5 . C53 ) <= ( ( R5 . D22 ) + ( R5 . D20 ) ) by L197 , L120;
L199: ( ( R5 . C53 ) + ( R5 . C54 ) ) <= ( ( ( R5 . D22 ) + ( R5 . D20 ) ) + ( R5 . C54 ) ) by L198 , XXREAL_3:36;
L200: ( C53 \ D17 ) c= ( ( D18 \/ D17 ) \ D17 ) by L189 , XBOOLE_1:33;
L201: ( C53 \ D17 ) c= ( D18 \ D17 ) by L200 , XBOOLE_1:40;
L202: ( D18 \ D17 ) c= D18 by XBOOLE_1:36;
L203: D20 c= D18 by L202 , L201 , XBOOLE_1:1;
L204: ( ( R5 . D20 ) + ( R5 . C54 ) ) <= ( R5 . D21 ) by L203 , L187 , L196 , L94;
L205: R5 is  nonnegative by L78;
L206: ( 0. ) <= ( R5 . D22 ) by L205 , MEASURE1:def 2;
L207: ( C53 \ D17 ) c= ( R3 \ D17 ) by XBOOLE_1:33;
L208: ( D20 \/ C54 ) c= ( ( R3 \ D17 ) \/ C54 ) by L207 , XBOOLE_1:9;
L209: D21 c= ( R3 \ D17 ) by L208 , L190 , L194 , XBOOLE_1:1 , XBOOLE_1:12;
L210: ( R5 . ( C53 \/ C54 ) ) = ( R5 . ( ( D22 \/ D20 ) \/ C54 ) ) by XBOOLE_1:51
.= ( R5 . ( D22 \/ D21 ) ) by XBOOLE_1:4
.= ( ( R5 . D22 ) + ( R5 . D21 ) ) by L186 , L192 , L209 , L159;
L211: ( ( R5 . D22 ) + ( ( R5 . D20 ) + ( R5 . C54 ) ) ) <= ( R5 . ( C53 \/ C54 ) ) by L210 , L204 , XXREAL_3:36;
L212: R5 is  nonnegative by L78;
L213: ( 0. ) <= ( R5 . C54 ) by L212 , MEASURE1:def 2;
L214: ( 0. ) <= ( R5 . D20 ) by L212 , MEASURE1:def 2;
L215: ( ( ( R5 . D22 ) + ( R5 . D20 ) ) + ( R5 . C54 ) ) <= ( R5 . ( C53 \/ C54 ) ) by L214 , L213 , L206 , L211 , XXREAL_3:44;
L216: ( ( R5 . C53 ) + ( R5 . C54 ) ) <= ( R5 . ( C53 \/ C54 ) ) by L215 , L199 , XXREAL_0:2;
L217: ( R5 . ( C53 \/ C54 ) ) <= ( ( R5 . C53 ) + ( R5 . C54 ) ) by L120;
thus L218: thesis by L217 , L216 , XXREAL_0:1;
end;
thus L219: thesis by L188 , L159;
end;
theorem
L220: (for R1 being set holds (for R2 being set holds (for R3 being set holds (for R5 being (C_Measure of R3) holds ((R1 in ( sigma_Field R5 ) & R2 in ( sigma_Field R5 )) implies ( R1 /\ R2 ) in ( sigma_Field R5 ))))))
proof
let R1 being set;
let R2 being set;
let R3 being set;
let R5 being (C_Measure of R3);
assume that
L221: R1 in ( sigma_Field R5 )
and
L222: R2 in ( sigma_Field R5 );
L223: ( R3 \ R2 ) in ( sigma_Field R5 ) by L222 , L176;
L224: ( R1 /\ R2 ) c= ( R3 /\ R3 ) by L221 , L222 , XBOOLE_1:27;
L225: ( R1 /\ R2 ) = ( R3 /\ ( R1 /\ R2 ) ) by L224 , XBOOLE_1:28
.= ( R3 \ ( R3 \ ( R1 /\ R2 ) ) ) by XBOOLE_1:48
.= ( R3 \ ( ( R3 \ R1 ) \/ ( R3 \ R2 ) ) ) by XBOOLE_1:54;
L226: ( R3 \ R1 ) in ( sigma_Field R5 ) by L221 , L176;
L227: ( ( R3 \ R1 ) \/ ( R3 \ R2 ) ) in ( sigma_Field R5 ) by L226 , L223 , L185;
thus L228: thesis by L227 , L225 , L176;
end;
theorem
L229: (for R1 being set holds (for R2 being set holds (for R3 being set holds (for R5 being (C_Measure of R3) holds ((R1 in ( sigma_Field R5 ) & R2 in ( sigma_Field R5 )) implies ( R1 \ R2 ) in ( sigma_Field R5 ))))))
proof
let R1 being set;
let R2 being set;
let R3 being set;
let R5 being (C_Measure of R3);
assume that
L230: R1 in ( sigma_Field R5 )
and
L231: R2 in ( sigma_Field R5 );
L232: (for B76 being set holds (B76 in ( R1 \ R2 ) iff B76 in ( R1 /\ ( R3 \ R2 ) )))
proof
let C55 being set;
thus L233:now
assume L234: C55 in ( R1 \ R2 );
L235: (not C55 in R2) by L234 , XBOOLE_0:def 5;
L236: C55 in R1 by L234;
L237: C55 in ( R3 \ R2 ) by L236 , L230 , L235 , XBOOLE_0:def 5;
thus L238: C55 in ( R1 /\ ( R3 \ R2 ) ) by L237 , L234 , XBOOLE_0:def 4;
end;
assume L239: C55 in ( R1 /\ ( R3 \ R2 ) );
L240: C55 in ( R3 \ R2 ) by L239 , XBOOLE_0:def 4;
L241: (not C55 in R2) by L240 , XBOOLE_0:def 5;
L242: C55 in R1 by L239 , XBOOLE_0:def 4;
thus L243: thesis by L242 , L241 , XBOOLE_0:def 5;
end;
L244: ( R1 \ R2 ) = ( R1 /\ ( R3 \ R2 ) ) by L232 , TARSKI:1;
L245: ( R3 \ R2 ) in ( sigma_Field R5 ) by L231 , L176;
thus L246: thesis by L245 , L230 , L244 , L220;
end;
theorem
L247: (for R3 being set holds (for R4 being (SigmaField of R3) holds (for B77 being (Function of ( NAT ) , R4) holds (for B78 being (Element of R4) holds (ex B79 being (Function of ( NAT ) , R4) st (for B80 being (Element of ( NAT )) holds ( B79 . B80 ) = ( B78 /\ ( B77 . B80 ) )))))))
proof
let R3 being set;
let R4 being (SigmaField of R3);
let C56 being (Function of ( NAT ) , R4);
let C57 being (Element of R4);
defpred S3[ set , set ] means ($1 in ( NAT ) implies $2 = ( C57 /\ ( C56 . $1 ) ));
L248: (for B81 being set holds (B81 in ( NAT ) implies (ex B82 being set st (B82 in R4 & S3[ B81 , B82 ]))))
proof
let C58 being set;
assume L249: C58 in ( NAT );
reconsider D23 = C58 as (Element of ( NAT )) by L249;
consider C59 being set such that L250: C59 = ( C57 /\ ( C56 . D23 ) );
take C59;
thus L251: thesis by L250;
end;
L252: (ex B83 being (Function of ( NAT ) , R4) st (for B84 being set holds (B84 in ( NAT ) implies S3[ B84 , ( B83 . B84 ) ]))) from FUNCT_2:sch 1(L248);
consider C60 being (Function of ( NAT ) , R4) such that L253: (for B85 being set holds (B85 in ( NAT ) implies S3[ B85 , ( C60 . B85 ) ])) by L252;
take C60;
thus L254: thesis by L253;
end;
theorem
L255: (for R3 being set holds (for R5 being (C_Measure of R3) holds ( sigma_Field R5 ) is (SigmaField of R3)))
proof
let R3 being set;
let R5 being (C_Measure of R3);
L256: R5 is  nonnegative by L78;
L257: (for B86 being (N_Sub_set_fam of R3) holds (B86 c= ( sigma_Field R5 ) implies ( union B86 ) in ( sigma_Field R5 )))
proof
let C61 being (N_Sub_set_fam of R3);
assume L258: C61 c= ( sigma_Field R5 );
L259: (for B87 , B88 being (Subset of R3) holds ((B87 c= ( union C61 ) & B88 c= ( R3 \ ( union C61 ) )) implies ( ( R5 . B87 ) + ( R5 . B88 ) ) <= ( R5 . ( B87 \/ B88 ) )))
proof
reconsider D24 = ( bool R3 ) as (SigmaField of R3) by L73;
let C62 , C63 being (Subset of R3);
assume that
L260: C62 c= ( union C61 )
and
L261: C63 c= ( R3 \ ( union C61 ) );
consider C64 being (Function of ( NAT ) , ( bool R3 )) such that L262: ( rng C64 ) = C61 by SUPINF_2:def 8;
consider C65 being (Function of ( NAT ) , D24) such that L263: ( C65 . ( 0 ) ) = ( C64 . ( 0 ) ) and L264: (for B89 being (Element of ( NAT )) holds ( C65 . ( B89 + 1 ) ) = ( ( C64 . ( B89 + 1 ) ) \/ ( C65 . B89 ) )) by MEASURE2:4;
consider C66 being (Function of ( NAT ) , D24) such that L265: ( C66 . ( 0 ) ) = ( C64 . ( 0 ) ) and L266: (for B90 being (Element of ( NAT )) holds ( C66 . ( B90 + 1 ) ) = ( ( C64 . ( B90 + 1 ) ) \ ( C65 . B90 ) )) by MEASURE2:8;
L267: ( union ( rng C64 ) ) = ( union ( rng C66 ) ) by L263 , L264 , L265 , L266 , L26;
defpred S4[ (Element of ( NAT )) ] means ( C65 . $1 ) in ( sigma_Field R5 );
L268: (for B91 being (Element of ( NAT )) holds ( C64 . B91 ) in ( sigma_Field R5 ))
proof
let C67 being (Element of ( NAT ));
L269: ( C64 . C67 ) in C61 by L262 , FUNCT_2:4;
thus L270: thesis by L269 , L258;
end;
L271: (for B92 being (Element of ( NAT )) holds (S4[ B92 ] implies S4[ ( B92 + 1 ) ]))
proof
let C68 being (Element of ( NAT ));
assume L272: ( C65 . C68 ) in ( sigma_Field R5 );
L273: ( C64 . ( C68 + 1 ) ) in ( sigma_Field R5 ) by L268;
L274: ( C65 . ( C68 + 1 ) ) = ( ( C64 . ( C68 + 1 ) ) \/ ( C65 . C68 ) ) by L264;
thus L275: thesis by L274 , L272 , L273 , L185;
end;
L276: S4[ ( 0 ) ] by L268 , L263;
L277: (for B93 being (Element of ( NAT )) holds S4[ B93 ]) from NAT_1:sch 1(L276 , L271);
consider C69 being (Function of ( NAT ) , D24) such that L278: (for B94 being (Element of ( NAT )) holds ( C69 . B94 ) = ( C62 /\ ( C66 . B94 ) )) by L247;
L279: ( union ( rng C69 ) ) = ( C62 /\ ( union ( rng C66 ) ) ) by L278 , L1;
consider C70 being (Function of ( NAT ) , D24) such that L280: ( C70 . ( 0 ) ) = ( C69 . ( 0 ) ) and L281: (for B95 being (Element of ( NAT )) holds ( C70 . ( B95 + 1 ) ) = ( ( C69 . ( B95 + 1 ) ) \/ ( C70 . B95 ) )) by MEASURE2:4;
reconsider D25 = C69 , D26 = C70 , D27 = C64 , D28 = C65 as (Function of ( NAT ) , ( bool R3 ));
L282: ( D27 . ( 0 ) ) in ( sigma_Field R5 ) by L268;
defpred S5[ (Element of ( NAT )) ] means ( R5 . ( C63 \/ ( D26 . $1 ) ) ) = ( ( R5 . C63 ) + ( ( Ser ( R5 * D25 ) ) . $1 ) );
L283: ( R5 * D25 ) is  nonnegative by L256 , MEASURE1:25;
L284: (for B96 being (Element of ( NAT )) holds (S5[ B96 ] implies S5[ ( B96 + 1 ) ]))
proof
defpred S6[ (Element of ( NAT )) ] means ( D26 . $1 ) c= ( D28 . $1 );
let C71 being (Element of ( NAT ));
L285: ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) c= ( D27 . ( C71 + 1 ) ) by XBOOLE_1:36;
L286: ( D26 . ( C71 + 1 ) ) = ( ( D26 . C71 ) \/ ( D25 . ( C71 + 1 ) ) ) by L281;
L287: ( D28 . C71 ) in ( sigma_Field R5 ) by L277;
L288: ( D27 . ( C71 + 1 ) ) in ( sigma_Field R5 ) by L268;
L289: ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) in ( sigma_Field R5 ) by L288 , L287 , L229;
L290: ( 0. ) <= ( ( R5 * D25 ) . ( C71 + 1 ) ) by L283 , SUPINF_2:39;
L291: ( 0. ) <= ( ( Ser ( R5 * D25 ) ) . C71 ) by L283 , SUPINF_2:40;
L292: ( D26 . ( 0 ) ) = ( C62 /\ ( D27 . ( 0 ) ) ) by L265 , L278 , L280;
L293: S6[ ( 0 ) ] by L292 , L263 , XBOOLE_1:17;
L294: (for B97 being (Element of ( NAT )) holds ( D26 . B97 ) misses ( ( D27 . ( B97 + 1 ) ) \ ( D28 . B97 ) ))
proof
let C72 being (Element of ( NAT ));
L295: (for B98 being (Element of ( NAT )) holds (S6[ B98 ] implies S6[ ( B98 + 1 ) ]))
proof
let C73 being (Element of ( NAT ));
assume L296: ( D26 . C73 ) c= ( D28 . C73 );
L297: ( C62 /\ ( D27 . ( C73 + 1 ) ) ) c= ( D27 . ( C73 + 1 ) ) by XBOOLE_1:17;
L298: ( C62 /\ ( ( D27 . ( C73 + 1 ) ) \ ( D28 . C73 ) ) ) c= ( C62 /\ ( D27 . ( C73 + 1 ) ) ) by XBOOLE_1:26 , XBOOLE_1:36;
L299: ( C62 /\ ( ( D27 . ( C73 + 1 ) ) \ ( D28 . C73 ) ) ) c= ( D27 . ( C73 + 1 ) ) by L298 , L297 , XBOOLE_1:1;
L300: ( D26 . ( C73 + 1 ) ) = ( ( D25 . ( C73 + 1 ) ) \/ ( D26 . C73 ) ) by L281
.= ( ( C62 /\ ( C66 . ( C73 + 1 ) ) ) \/ ( D26 . C73 ) ) by L278
.= ( ( C62 /\ ( ( D27 . ( C73 + 1 ) ) \ ( D28 . C73 ) ) ) \/ ( D26 . C73 ) ) by L266;
L301: ( D26 . ( C73 + 1 ) ) c= ( ( D27 . ( C73 + 1 ) ) \/ ( D28 . C73 ) ) by L300 , L296 , L299 , XBOOLE_1:13;
thus L302: thesis by L301 , L264;
end;
L303: (for B99 being (Element of ( NAT )) holds S6[ B99 ]) from NAT_1:sch 1(L293 , L295);
L304: ( D28 . C72 ) misses ( ( D27 . ( C72 + 1 ) ) \ ( D28 . C72 ) ) by XBOOLE_1:79;
thus L305: thesis by L304 , L303 , XBOOLE_1:63;
end;
L306: ( D26 . C71 ) misses ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) by L294;
L307: ( ( D26 . C71 ) /\ ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) ) = ( {} ) by L306 , XBOOLE_0:def 7;
L308: ( D26 . C71 ) c= ( R3 \ ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) )
proof
let C74 being set;
assume L309: C74 in ( D26 . C71 );
L310: (not C74 in ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) )) by L309 , L307 , XBOOLE_0:def 4;
thus L311: thesis by L310 , L309 , XBOOLE_0:def 5;
end;
L312: ( D25 . ( C71 + 1 ) ) = ( C62 /\ ( C66 . ( C71 + 1 ) ) ) by L278
.= ( C62 /\ ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) ) by L266;
L313: ( D25 . ( C71 + 1 ) ) c= ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) by L312 , XBOOLE_1:17;
L314: ( D27 . ( C71 + 1 ) ) c= ( union ( rng D27 ) ) by FUNCT_2:4 , ZFMISC_1:74;
L315: ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) c= ( union ( rng D27 ) ) by L314 , L285 , XBOOLE_1:1;
L316: ( R3 \ ( union ( rng D27 ) ) ) c= ( R3 \ ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) ) by L315 , XBOOLE_1:34;
L317: C63 c= ( R3 \ ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) ) by L316 , L261 , L262 , XBOOLE_1:1;
L318: ( C63 \/ ( D26 . C71 ) ) c= ( R3 \ ( ( D27 . ( C71 + 1 ) ) \ ( D28 . C71 ) ) ) by L317 , L308 , XBOOLE_1:8;
L319: ( ( R5 . ( D25 . ( C71 + 1 ) ) ) + ( R5 . ( C63 \/ ( D26 . C71 ) ) ) ) = ( R5 . ( ( C63 \/ ( D26 . C71 ) ) \/ ( D25 . ( C71 + 1 ) ) ) ) by L318 , L313 , L289 , L159
.= ( R5 . ( C63 \/ ( D26 . ( C71 + 1 ) ) ) ) by L286 , XBOOLE_1:4;
L320: ( 0. ) <= ( R5 . C63 ) by L256 , SUPINF_2:39;
assume L321: ( R5 . ( C63 \/ ( D26 . C71 ) ) ) = ( ( R5 . C63 ) + ( ( Ser ( R5 * D25 ) ) . C71 ) );
L322: ( R5 . ( C63 \/ ( D26 . ( C71 + 1 ) ) ) ) = ( ( ( R5 . C63 ) + ( ( Ser ( R5 * D25 ) ) . C71 ) ) + ( ( R5 * D25 ) . ( C71 + 1 ) ) ) by L321 , L319 , FUNCT_2:15
.= ( ( R5 . C63 ) + ( ( ( Ser ( R5 * D25 ) ) . C71 ) + ( ( R5 * D25 ) . ( C71 + 1 ) ) ) ) by L320 , L291 , L290 , XXREAL_3:44
.= ( ( R5 . C63 ) + ( ( Ser ( R5 * D25 ) ) . ( C71 + 1 ) ) ) by SUPINF_2:44;
thus L323: thesis by L322;
end;
L324: ( D26 . ( 0 ) ) = ( C62 /\ ( D27 . ( 0 ) ) ) by L265 , L278 , L280;
L325: ( D26 . ( 0 ) ) c= ( D27 . ( 0 ) ) by L324 , XBOOLE_1:17;
L326: ( ( Ser ( R5 * D25 ) ) . ( 0 ) ) = ( ( R5 * D25 ) . ( 0 ) ) by SUPINF_2:44
.= ( R5 . ( D26 . ( 0 ) ) ) by L280 , FUNCT_2:15;
L327: ( D27 . ( 0 ) ) in ( rng D27 ) by FUNCT_2:4;
L328: ( R3 \ ( union ( rng D27 ) ) ) c= ( R3 \ ( D27 . ( 0 ) ) ) by L327 , XBOOLE_1:34 , ZFMISC_1:74;
L329: C63 c= ( R3 \ ( D27 . ( 0 ) ) ) by L328 , L261 , L262 , XBOOLE_1:1;
L330: S5[ ( 0 ) ] by L329 , L282 , L325 , L326 , L159;
L331: (for B100 being (Element of ( NAT )) holds S5[ B100 ]) from NAT_1:sch 1(L330 , L284);
defpred S7[ (Element of ( NAT )) ] means ( D26 . $1 ) c= C62;
L332: (for B101 being (Element of ( NAT )) holds (S7[ B101 ] implies S7[ ( B101 + 1 ) ]))
proof
let C75 being (Element of ( NAT ));
assume L333: ( D26 . C75 ) c= C62;
L334: ( C62 /\ ( C66 . ( C75 + 1 ) ) ) c= C62 by XBOOLE_1:17;
L335: ( D26 . ( C75 + 1 ) ) = ( ( D25 . ( C75 + 1 ) ) \/ ( D26 . C75 ) ) by L281
.= ( ( C62 /\ ( C66 . ( C75 + 1 ) ) ) \/ ( D26 . C75 ) ) by L278;
L336: ( D26 . ( C75 + 1 ) ) c= ( C62 \/ C62 ) by L335 , L333 , L334 , XBOOLE_1:13;
thus L337: thesis by L336;
end;
L338: ( D26 . ( 0 ) ) = ( C62 /\ ( C66 . ( 0 ) ) ) by L278 , L280;
L339: S7[ ( 0 ) ] by L338 , XBOOLE_1:17;
L340: (for B102 being (Element of ( NAT )) holds S7[ B102 ]) from NAT_1:sch 1(L339 , L332);
L341: ( union ( rng D25 ) ) = C62 by L260 , L262 , L267 , L279 , XBOOLE_1:28;
L342: (( R5 . C63 ) is  real implies ( ( R5 . C62 ) + ( R5 . C63 ) ) <= ( R5 . ( C62 \/ C63 ) ))
proof
defpred S8[ set , set ] means (($1 = ( 0 ) implies $2 = ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) )) & ($1 <> ( 0 ) implies $2 = ( 0. )));
L343: (for B103 being set holds (B103 in ( NAT ) implies (ex B104 being set st (B104 in ( ExtREAL ) & S8[ B103 , B104 ]))))
proof
let C76 being set;
assume L344: C76 in ( NAT );
reconsider D29 = C76 as (Element of ( NAT )) by L344;
L345: (D29 <> ( 0 ) implies (ex B105 being set st (B105 in ( ExtREAL ) & S8[ D29 , B105 ])));
thus L346: thesis by L345;
end;
consider C77 being (Function of ( NAT ) , ( ExtREAL )) such that L347: (for B106 being set holds (B106 in ( NAT ) implies S8[ B106 , ( C77 . B106 ) ])) from FUNCT_2:sch 1(L343);
assume L348: ( R5 . C63 ) is  real;
L349: (for B107 being (Element of ( NAT )) holds ( 0. ) <= ( C77 . B107 ))
proof
let C78 being (Element of ( NAT ));
L350: (( R5 . C63 ) in ( REAL ) or ( R5 . C63 ) in { ( -infty ) , ( +infty ) }) by XBOOLE_0:def 3 , XXREAL_0:def 4;
consider C79 being Real such that L351: C79 = ( R5 . C63 ) by L350 , L348 , TARSKI:def 2;
L352: C63 c= ( C63 \/ C62 ) by XBOOLE_1:7;
L353: ( R5 . C63 ) <= ( R5 . ( C63 \/ C62 ) ) by L352 , L78;
L354: ( ( R5 . C63 ) - ( R5 . C63 ) ) <= ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L353 , XXREAL_3:37;
L355: ( ( R5 . C63 ) - ( R5 . C63 ) ) = ( C79 - C79 ) by L351 , SUPINF_2:3;
thus L356: thesis by L355 , L347 , L354;
end;
L357: C77 is  nonnegative by L349 , SUPINF_2:39;
L358: (for B108 being (Element of ( NAT )) holds ( ( Ser ( R5 * D25 ) ) . B108 ) <= ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ))
proof
let C80 being (Element of ( NAT ));
L359: ( C63 \/ ( D26 . C80 ) ) c= ( C63 \/ C62 ) by L340 , XBOOLE_1:9;
L360: ( ( ( Ser ( R5 * D25 ) ) . C80 ) + ( R5 . C63 ) ) = ( R5 . ( C63 \/ ( D26 . C80 ) ) ) by L331;
L361: ( ( ( Ser ( R5 * D25 ) ) . C80 ) + ( R5 . C63 ) ) <= ( R5 . ( C63 \/ C62 ) ) by L360 , L359 , L78;
thus L362: thesis by L361 , L348 , XXREAL_3:45;
end;
L363: (for B109 being (Element of ( NAT )) holds ( ( Ser ( R5 * D25 ) ) . B109 ) <= ( ( Ser C77 ) . B109 ))
proof
let C81 being (Element of ( NAT ));
defpred S9[ (Element of ( NAT )) ] means ( ( Ser C77 ) . $1 ) = ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) );
L364: (for B110 being (Element of ( NAT )) holds (S9[ B110 ] implies S9[ ( B110 + 1 ) ]))
proof
let C82 being (Element of ( NAT ));
assume L365: ( ( Ser C77 ) . C82 ) = ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) );
set D30 = ( ( Ser C77 ) . C82 );
thus L366: ( ( Ser C77 ) . ( C82 + 1 ) ) = ( D30 + ( C77 . ( C82 + 1 ) ) ) by SUPINF_2:44
.= ( D30 + ( 0. ) ) by L347
.= ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L365 , XXREAL_3:4;
end;
L367: ( ( Ser C77 ) . ( 0 ) ) = ( C77 . ( 0 ) ) by SUPINF_2:44;
L368: S9[ ( 0 ) ] by L367 , L347;
L369: (for B111 being (Element of ( NAT )) holds S9[ B111 ]) from NAT_1:sch 1(L368 , L364);
L370: ( ( Ser C77 ) . C81 ) = ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L369;
thus L371: thesis by L370 , L358;
end;
set D31 = ( ( Ser C77 ) . ( 0 ) );
L372: D31 = ( C77 . ( 0 ) ) by SUPINF_2:44;
L373: D31 = ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L372 , L347;
L374: ( R5 . C62 ) <= ( SUM ( R5 * D25 ) ) by L341 , L78;
L375: (for B112 being (Element of ( NAT )) holds (1 <= B112 implies ( C77 . B112 ) = ( 0. ))) by L347;
L376: ( SUM C77 ) = ( ( Ser C77 ) . 1 ) by L375 , L357 , SUPINF_2:48;
L377: ( ( Ser C77 ) . 1 ) = ( D31 + ( C77 . ( ( 0 ) + 1 ) ) ) by SUPINF_2:44
.= ( D31 + ( 0. ) ) by L347
.= ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L373 , XXREAL_3:4;
L378: ( SUM ( R5 * D25 ) ) <= ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L377 , L363 , L376 , MEASURE3:1;
L379: ( R5 . C62 ) <= ( ( R5 . ( C63 \/ C62 ) ) - ( R5 . C63 ) ) by L378 , L374 , XXREAL_0:2;
thus L380: thesis by L379 , L348 , XXREAL_3:45;
end;
L381: (( R5 . C63 ) = ( +infty ) implies ( ( R5 . C62 ) + ( R5 . C63 ) ) <= ( R5 . ( C62 \/ C63 ) ))
proof
L382: C63 c= ( C62 \/ C63 ) by XBOOLE_1:7;
assume L383: ( R5 . C63 ) = ( +infty );
L384: ( 0. ) <= ( R5 . C62 ) by L256 , MEASURE1:def 2;
L385: ( ( R5 . C62 ) + ( R5 . C63 ) ) = ( +infty ) by L384 , L383 , XXREAL_3:def 2;
thus L386: thesis by L385 , L383 , L382 , L78;
end;
L387: ( 0 ) <= ( R5 . C63 ) by L256 , MEASURE1:def 2;
L388: (( R5 . C63 ) is (Element of ( REAL )) or ( R5 . C63 ) = ( +infty )) by L387 , XXREAL_0:14;
thus L389: thesis by L388 , L381 , L342;
end;
thus L390: thesis by L259 , L94;
end;
L391: (for B113 being set holds (B113 in ( sigma_Field R5 ) implies ( R3 \ B113 ) in ( sigma_Field R5 ))) by L176;
reconsider D32 = ( sigma_Field R5 ) as non  empty  compl-closed  sigma-additive (Subset-Family of R3) by L391 , L257 , MEASURE1:def 1 , MEASURE1:def 5;
L392: D32 is (SigmaField of R3);
thus L393: thesis by L392;
end;
registration
let C83 being set;
let C84 being (C_Measure of C83);
cluster ( sigma_Field C84 ) ->  sigma-additive  compl-closed non  empty;
coherence by L255;
end;
definition
let C85 being set;
let C86 being (SigmaField of C85);
let C87 being (N_Sub_fam of C86);
redefine func union C87 -> (Element of C86);

coherence
proof
L395: C87 c= C86 by MEASURE2:def 1;
thus L396: thesis by L395 , MEASURE1:def 5;
end;
end;
definition
let C88 being set;
let C89 being (C_Measure of C88);
func sigma_Meas C89 -> (Function of ( sigma_Field C89 ) , ( ExtREAL )) means 
:L398: (for B114 being (Subset of C88) holds (B114 in ( sigma_Field C89 ) implies ( it . B114 ) = ( C89 . B114 )));
existence
proof
L399: (ex B115 being (Function of ( sigma_Field C89 ) , ( ExtREAL )) st (for B116 being (Subset of C88) holds (B116 in ( sigma_Field C89 ) implies ( B115 . B116 ) = ( C89 . B116 ))))
proof
deffunc H1(set) = ( C89 . $1 );
L400: (for B117 being set holds (B117 in ( sigma_Field C89 ) implies H1(B117) in ( ExtREAL )));
consider C90 being (Function of ( sigma_Field C89 ) , ( ExtREAL )) such that L401: (for B118 being set holds (B118 in ( sigma_Field C89 ) implies ( C90 . B118 ) = H1(B118))) from FUNCT_2:sch 2(L400);
take C90;
thus L402: thesis by L401;
end;
consider C91 being (Function of ( sigma_Field C89 ) , ( ExtREAL )) such that L403: (for B119 being (Subset of C88) holds (B119 in ( sigma_Field C89 ) implies ( C91 . B119 ) = ( C89 . B119 ))) by L399;
take C91;
thus L404: thesis by L403;
end;
uniqueness
proof
let C92 , C93 being (Function of ( sigma_Field C89 ) , ( ExtREAL ));
assume that
L405: (for B120 being (Subset of C88) holds (B120 in ( sigma_Field C89 ) implies ( C92 . B120 ) = ( C89 . B120 )))
and
L406: (for B121 being (Subset of C88) holds (B121 in ( sigma_Field C89 ) implies ( C93 . B121 ) = ( C89 . B121 )));
L407: (for B122 being set holds (B122 in ( sigma_Field C89 ) implies ( C92 . B122 ) = ( C93 . B122 )))
proof
let C94 being set;
assume L408: C94 in ( sigma_Field C89 );
reconsider D33 = C94 as (Subset of C88) by L408;
L409: ( C92 . D33 ) = ( C89 . D33 ) by L405 , L408
.= ( C93 . D33 ) by L406 , L408;
thus L410: thesis by L409;
end;
L411: ( sigma_Field C89 ) = ( dom C93 ) by FUNCT_2:def 1;
L412: ( sigma_Field C89 ) = ( dom C92 ) by FUNCT_2:def 1;
thus L413: thesis by L412 , L411 , L407 , FUNCT_1:2;
end;
end;
theorem
L415: (for R3 being set holds (for R5 being (C_Measure of R3) holds ( sigma_Meas R5 ) is (Measure of ( sigma_Field R5 ))))
proof
let R3 being set;
let R5 being (C_Measure of R3);
L416:
now
let C95 being (Element of ( sigma_Field R5 ));
reconsider D34 = C95 as (Subset of R3);
L417: R5 is  nonnegative by L78;
L418: ( ( sigma_Meas R5 ) . D34 ) = ( R5 . D34 ) by L398;
thus L419: ( 0. ) <= ( ( sigma_Meas R5 ) . C95 ) by L418 , L417 , MEASURE1:def 2;
end;
L420: ( {} ) in ( sigma_Field R5 ) by PROB_1:4;
L421: ( ( sigma_Meas R5 ) . ( {} ) ) = ( R5 . ( {} ) ) by L420 , L398;
L422:
now
let C96 , C97 being (Element of ( sigma_Field R5 ));
reconsider D35 = C96 , D36 = C97 as (Subset of R3);
L423: ( ( sigma_Meas R5 ) . D36 ) = ( R5 . D36 ) by L398;
assume L424: C96 misses C97;
L425: ( R5 . ( D35 \/ D36 ) ) = ( ( R5 . D35 ) + ( R5 . D36 ) ) by L424 , L170;
L426: ( ( sigma_Meas R5 ) . D35 ) = ( R5 . D35 ) by L398;
thus L427: ( ( sigma_Meas R5 ) . ( C96 \/ C97 ) ) = ( ( ( sigma_Meas R5 ) . C96 ) + ( ( sigma_Meas R5 ) . C97 ) ) by L426 , L423 , L425 , L398;
end;
L428: R5 is  zeroed by L78;
L429: ( ( sigma_Meas R5 ) . ( {} ) ) = ( 0. ) by L428 , L421 , VALUED_0:def 19;
thus L430: thesis by L429 , L416 , L422 , MEASURE1:def 2 , MEASURE1:def 3 , VALUED_0:def 19;
end;
::$N Caratheodory's Theorem
theorem
L431: (for R3 being set holds (for R5 being (C_Measure of R3) holds ( sigma_Meas R5 ) is (sigma_Measure of ( sigma_Field R5 ))))
proof
let R3 being set;
let R5 being (C_Measure of R3);
reconsider D37 = ( sigma_Meas R5 ) as (Measure of ( sigma_Field R5 )) by L415;
L432: (for B123 being (Sep_Sequence of ( sigma_Field R5 )) holds ( D37 . ( union ( rng B123 ) ) ) <= ( SUM ( D37 * B123 ) ))
proof
let C98 being (Sep_Sequence of ( sigma_Field R5 ));
consider C99 being (Subset of R3) such that L433: C99 = ( union ( rng C98 ) );
L434: (for B124 being set holds (B124 in ( NAT ) implies ( ( D37 * C98 ) . B124 ) = ( ( R5 * C98 ) . B124 )))
proof
let C100 being set;
assume L435: C100 in ( NAT );
L436: ( ( D37 * C98 ) . C100 ) = ( D37 . ( C98 . C100 ) ) by L435 , FUNCT_2:15;
L437: ( C98 . C100 ) in ( sigma_Field R5 ) by L435 , FUNCT_2:5;
reconsider D38 = C98 as (Function of ( NAT ) , ( bool R3 )) by FUNCT_2:7;
L438: ( ( R5 * D38 ) . C100 ) = ( R5 . ( D38 . C100 ) ) by L435 , FUNCT_2:15;
thus L439: thesis by L438 , L436 , L437 , L398;
end;
reconsider D39 = C98 as (Function of ( NAT ) , ( bool R3 )) by FUNCT_2:7;
consider C101 , C102 being R_eal such that L440: C101 = ( D37 . C99 ) and L441: C102 = ( R5 . C99 );
L442: ( R5 * D39 ) is (Function of ( NAT ) , ( ExtREAL ));
L443: ( D37 * C98 ) = ( R5 * C98 ) by L442 , L434 , FUNCT_2:12;
reconsider D40 = C98 as (Function of ( NAT ) , ( bool R3 )) by FUNCT_2:7;
L444: C102 <= ( SUM ( R5 * D40 ) ) by L433 , L441 , L78;
thus L445: thesis by L444 , L433 , L441 , L443 , L398;
end;
thus L446: thesis by L432 , MEASURE3:14;
end;
registration
let C103 being set;
let C104 being (C_Measure of C103);
cluster ( sigma_Meas C104 ) ->  nonnegative  sigma-additive  zeroed;
coherence by L431;
end;
theorem
L448: (for R3 being set holds (for R5 being (C_Measure of R3) holds (for B125 being (Subset of R3) holds (( R5 . B125 ) = ( 0. ) implies B125 in ( sigma_Field R5 )))))
proof
let R3 being set;
let R5 being (C_Measure of R3);
let C105 being (Subset of R3);
assume L449: ( R5 . C105 ) = ( 0. );
L450:
now
let C106 , C107 being (Subset of R3);
assume that
L451: C106 c= C105
and
L452: C107 c= ( R3 \ C105 );
L453: C107 c= ( C106 \/ C107 ) by XBOOLE_1:7;
L454: ( R5 . C107 ) <= ( R5 . ( C106 \/ C107 ) ) by L453 , L78;
L455: R5 is  nonnegative by L78;
L456: ( 0. ) <= ( R5 . C106 ) by L455 , MEASURE1:def 2;
L457: ( R5 . C106 ) = ( 0. ) by L456 , L449 , L451 , L78;
thus L458: ( ( R5 . C106 ) + ( R5 . C107 ) ) <= ( R5 . ( C106 \/ C107 ) ) by L457 , L454 , XXREAL_3:4;
end;
thus L459: thesis by L450 , L94;
end;
theorem
L460: (for R3 being set holds (for R5 being (C_Measure of R3) holds ( sigma_Meas R5 ) is_complete ( sigma_Field R5 )))
proof
let R3 being set;
let R5 being (C_Measure of R3);
let C108 being (Subset of R3);
let R2 being set;
assume that
L461: R2 in ( sigma_Field R5 )
and
L462: C108 c= R2
and
L463: ( ( sigma_Meas R5 ) . R2 ) = ( 0. );
reconsider D41 = R2 as (Subset of R3) by L461;
L464: R5 is  nonnegative by L78;
L465: ( 0. ) <= ( R5 . C108 ) by L464 , MEASURE1:def 2;
L466: ( R5 . D41 ) = ( 0. ) by L461 , L463 , L398;
L467: ( R5 . C108 ) = ( 0. ) by L466 , L462 , L465 , L78;
thus L468: thesis by L467 , L448;
end;
