:: Three-Argument Operations and Four-Argument Operations
::  by Michal Muzalewski and Wojciech Skaba
::
:: Received October 2, 1990
:: Copyright (c) 1990-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies FUNCT_1, XBOOLE_0, SUBSET_1, ZFMISC_1, MULTOP_1;
 notations XBOOLE_0, ZFMISC_1,
      XTUPLE_0, SUBSET_1, FUNCT_1, FUNCT_2, MCART_1, DOMAIN_1;
 constructors FUNCT_2, DOMAIN_1, RELSET_1, XTUPLE_0;
 registrations XBOOLE_0, SUBSET_1, RELSET_1, XTUPLE_0;
 definitions XTUPLE_0;
 requirements SUBSET, BOOLE;
 theorems FUNCT_2, MCART_1, XTUPLE_0;
 schemes FUNCT_2;

begin
definition
let C1 being Function;
let C2 , C3 , C4 being set;
func C1 . (C2 , C3 , C4) -> set equals 
( C1 . [ C2 , C3 , C4 ] );
correctness;
end;
definition
let R1 being non  empty set;
let R2 being non  empty set;
let R3 being non  empty set;
let R4 being non  empty set;
let C5 being (Function of [: R1 , R2 , R3 :] , R4);
let R6 being (Element of R1);
let R7 being (Element of R2);
let R8 being (Element of R3);
redefine func C5 . (R6 , R7 , R8) -> (Element of R4);

coherence
proof
L2: ( C5 . [ R6 , R7 , R8 ] ) is (Element of R4);
thus L3: thesis by L2;
end;
end;
theorem
L5: (for R4 being non  empty set holds (for R10 being set holds (for R11 being set holds (for R12 being set holds (for B1 , B2 being (Function of [: R10 , R11 , R12 :] , R4) holds ((for R14 being set holds (for R15 being set holds (for R16 being set holds ((R14 in R10 & R15 in R11 & R16 in R12) implies ( B1 . [ R14 , R15 , R16 ] ) = ( B2 . [ R14 , R15 , R16 ] ))))) implies B1 = B2))))))
proof
let R4 being non  empty set;
let R10 being set;
let R11 being set;
let R12 being set;
let C6 , C7 being (Function of [: R10 , R11 , R12 :] , R4);
assume that
L6: (for R14 being set holds (for R15 being set holds (for R16 being set holds ((R14 in R10 & R15 in R11 & R16 in R12) implies ( C6 . [ R14 , R15 , R16 ] ) = ( C7 . [ R14 , R15 , R16 ] )))));
L7: (for R18 being set holds (R18 in [: R10 , R11 , R12 :] implies ( C6 . R18 ) = ( C7 . R18 )))
proof
let R18 being set;
assume L8: R18 in [: R10 , R11 , R12 :];
L9: (ex R14 being set st (ex R15 being set st (ex R16 being set st (R14 in R10 & R15 in R11 & R16 in R12 & R18 = [ R14 , R15 , R16 ])))) by L8 , MCART_1:68;
thus L10: thesis by L9 , L6;
end;
thus L11: thesis by L7 , FUNCT_2:12;
end;
theorem
L12: (for R1 being non  empty set holds (for R2 being non  empty set holds (for R3 being non  empty set holds (for R4 being non  empty set holds (for B3 , B4 being (Function of [: R1 , R2 , R3 :] , R4) holds ((for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds ( B3 . [ R6 , R7 , R8 ] ) = ( B4 . [ R6 , R7 , R8 ] )))) implies B3 = B4))))))
proof
let R1 being non  empty set;
let R2 being non  empty set;
let R3 being non  empty set;
let R4 being non  empty set;
let C8 , C9 being (Function of [: R1 , R2 , R3 :] , R4);
assume L13: (for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds ( C8 . [ R6 , R7 , R8 ] ) = ( C9 . [ R6 , R7 , R8 ] ))));
L14: (for R14 being set holds (for R15 being set holds (for R16 being set holds ((R14 in R1 & R15 in R2 & R16 in R3) implies ( C8 . [ R14 , R15 , R16 ] ) = ( C9 . [ R14 , R15 , R16 ] ))))) by L13;
thus L15: thesis by L14 , L5;
end;
theorem
L16: (for R1 being non  empty set holds (for R2 being non  empty set holds (for R3 being non  empty set holds (for R4 being non  empty set holds (for B5 , B6 being (Function of [: R1 , R2 , R3 :] , R4) holds ((for B7 being (Element of R1) holds (for B8 being (Element of R2) holds (for B9 being (Element of R3) holds ( B5 . (B7 , B8 , B9) ) = ( B6 . (B7 , B8 , B9) )))) implies B5 = B6))))))
proof
let R1 being non  empty set;
let R2 being non  empty set;
let R3 being non  empty set;
let R4 being non  empty set;
let C10 , C11 being (Function of [: R1 , R2 , R3 :] , R4);
assume that
L17: (for B10 being (Element of R1) holds (for B11 being (Element of R2) holds (for B12 being (Element of R3) holds ( C10 . (B10 , B11 , B12) ) = ( C11 . (B10 , B11 , B12) ))));
L18: (for B13 being (Element of R1) holds (for B14 being (Element of R2) holds (for B15 being (Element of R3) holds ( C10 . [ B13 , B14 , B15 ] ) = ( C11 . [ B13 , B14 , B15 ] ))))
proof
let C12 being (Element of R1);
let C13 being (Element of R2);
let C14 being (Element of R3);
L19: (( C10 . (C12 , C13 , C14) ) = ( C10 . [ C12 , C13 , C14 ] ) & ( C11 . (C12 , C13 , C14) ) = ( C11 . [ C12 , C13 , C14 ] ));
thus L20: thesis by L19 , L17;
end;
thus L21: thesis by L18 , L12;
end;
definition
let C15 being set;
mode TriOp of C15
 is (Function of [: C15 , C15 , C15 :] , C15);
end;
scheme FuncEx3D { F1 , F2 , F3 , F4() -> non  empty set , P1[set , set , set , set] } : (ex B16 being (Function of [: F1() , F2() , F3() :] , F4()) st (for B17 being (Element of F1()) holds (for B18 being (Element of F2()) holds (for B19 being (Element of F3()) holds P1[ B17 , B18 , B19 , ( B16 . [ B17 , B18 , B19 ] ) ]))))
provided
L23: (for B20 being (Element of F1()) holds (for B21 being (Element of F2()) holds (for B22 being (Element of F3()) holds (ex B23 being (Element of F4()) st P1[ B20 , B21 , B22 , B23 ]))))
proof
defpred S1[ set , set ] means (for B24 being (Element of F1()) holds (for B25 being (Element of F2()) holds (for B26 being (Element of F3()) holds ($1 = [ B24 , B25 , B26 ] implies P1[ B24 , B25 , B26 , $2 ]))));
L24: (for B27 being (Element of [: F1() , F2() , F3() :]) holds (ex B28 being (Element of F4()) st S1[ B27 , B28 ]))
proof
let C16 being (Element of [: F1() , F2() , F3() :]);
consider C17 , C18 , C19 being set such that L25: C17 in F1() and L26: C18 in F2() and L27: C19 in F3() and L28: C16 = [ C17 , C18 , C19 ] by MCART_1:68;
reconsider D1 = C19 as (Element of F3()) by L27;
reconsider D2 = C18 as (Element of F2()) by L26;
reconsider D3 = C17 as (Element of F1()) by L25;
consider C20 being (Element of F4()) such that L29: P1[ D3 , D2 , D1 , C20 ] by L23;
take C20;
let C21 being (Element of F1());
let C22 being (Element of F2());
let C23 being (Element of F3());
assume L30: C16 = [ C21 , C22 , C23 ];
L31: (D3 = C21 & D2 = C22) by L30 , L28 , XTUPLE_0:3;
thus L32: thesis by L31 , L28 , L29 , L30 , XTUPLE_0:3;
end;
consider C24 being (Function of [: F1() , F2() , F3() :] , F4()) such that L33: (for B29 being (Element of [: F1() , F2() , F3() :]) holds S1[ B29 , ( C24 . B29 ) ]) from FUNCT_2:sch 3(L24);
take C24;
let C25 being (Element of F1());
let C26 being (Element of F2());
let C27 being (Element of F3());
thus L34: thesis by L33;
end;
scheme TriOpEx { F5() -> non  empty set , P2[(Element of F5()) , (Element of F5()) , (Element of F5()) , (Element of F5())] } : (ex B30 being (TriOp of F5()) st (for B31 , B32 , B33 being (Element of F5()) holds P2[ B31 , B32 , B33 , ( B30 . (B31 , B32 , B33) ) ]))
provided
L35: (for B34 , B35 , B36 being (Element of F5()) holds (ex B37 being (Element of F5()) st P2[ B34 , B35 , B36 , B37 ]))
proof
defpred S2[ (Element of F5()) , (Element of F5()) , (Element of F5()) , (Element of F5()) ] means (for B38 being (Element of F5()) holds (B38 = $4 implies P2[ $1 , $2 , $3 , B38 ]));
L36: (for B39 , B40 , B41 being (Element of F5()) holds (ex B42 being (Element of F5()) st S2[ B39 , B40 , B41 , B42 ]))
proof
let C28 , C29 , C30 being (Element of F5());
consider C31 being (Element of F5()) such that L37: P2[ C28 , C29 , C30 , C31 ] by L35;
take C31;
thus L38: thesis by L37;
end;
consider C32 being (Function of [: F5() , F5() , F5() :] , F5()) such that L39: (for B43 , B44 , B45 being (Element of F5()) holds S2[ B43 , B44 , B45 , ( C32 . [ B43 , B44 , B45 ] ) ]) from FuncEx3D(L36);
take C32;
let C33 , C34 , C35 being (Element of F5());
thus L40: thesis by L39;
end;
scheme Lambda3D { F6 , F7 , F8 , F9() -> non  empty set , F10((Element of F6()) , (Element of F7()) , (Element of F8())) -> (Element of F9()) } : (ex B46 being (Function of [: F6() , F7() , F8() :] , F9()) st (for B47 being (Element of F6()) holds (for B48 being (Element of F7()) holds (for B49 being (Element of F8()) holds ( B46 . [ B47 , B48 , B49 ] ) = F10(B47 , B48 , B49)))))
proof
defpred S3[ (Element of F6()) , (Element of F7()) , (Element of F8()) , (Element of F9()) ] means $4 = F10($1 , $2 , $3);
L41: (for B50 being (Element of F6()) holds (for B51 being (Element of F7()) holds (for B52 being (Element of F8()) holds (ex B53 being (Element of F9()) st S3[ B50 , B51 , B52 , B53 ]))));
L42: (ex B54 being (Function of [: F6() , F7() , F8() :] , F9()) st (for B55 being (Element of F6()) holds (for B56 being (Element of F7()) holds (for B57 being (Element of F8()) holds S3[ B55 , B56 , B57 , ( B54 . [ B55 , B56 , B57 ] ) ])))) from FuncEx3D(L41);
thus L43: thesis by L42;
end;
scheme TriOpLambda { F11 , F12 , F13 , F14() -> non  empty set , F15((Element of F11()) , (Element of F12()) , (Element of F13())) -> (Element of F14()) } : (ex B58 being (Function of [: F11() , F12() , F13() :] , F14()) st (for B59 being (Element of F11()) holds (for B60 being (Element of F12()) holds (for B61 being (Element of F13()) holds ( B58 . (B59 , B60 , B61) ) = F15(B59 , B60 , B61)))))
proof
consider C36 being (Function of [: F11() , F12() , F13() :] , F14()) such that L44: (for B62 being (Element of F11()) holds (for B63 being (Element of F12()) holds (for B64 being (Element of F13()) holds ( C36 . [ B62 , B63 , B64 ] ) = F15(B62 , B63 , B64)))) from Lambda3D;
take C36;
let C37 being (Element of F11());
let C38 being (Element of F12());
let C39 being (Element of F13());
thus L45: thesis by L44;
end;
definition
let C40 being Function;
let C41 , C42 , C43 , C44 being set;
func C40 . (C41 , C42 , C43 , C44) -> set equals 
( C40 . [ C41 , C42 , C43 , C44 ] );
correctness;
end;
definition
let R1 being non  empty set;
let R2 being non  empty set;
let R3 being non  empty set;
let R4 being non  empty set;
let R5 being non  empty set;
let C45 being (Function of [: R1 , R2 , R3 , R4 :] , R5);
let R6 being (Element of R1);
let R7 being (Element of R2);
let R8 being (Element of R3);
let R9 being (Element of R4);
redefine func C45 . (R6 , R7 , R8 , R9) -> (Element of R5);

coherence
proof
L47: ( C45 . [ R6 , R7 , R8 , R9 ] ) is (Element of R5);
thus L48: thesis by L47;
end;
end;
theorem
L50: (for R4 being non  empty set holds (for R10 being set holds (for R11 being set holds (for R12 being set holds (for R13 being set holds (for B65 , B66 being (Function of [: R10 , R11 , R12 , R13 :] , R4) holds ((for R14 being set holds (for R15 being set holds (for R16 being set holds (for R17 being set holds ((R14 in R10 & R15 in R11 & R16 in R12 & R17 in R13) implies ( B65 . [ R14 , R15 , R16 , R17 ] ) = ( B66 . [ R14 , R15 , R16 , R17 ] )))))) implies B65 = B66)))))))
proof
let R4 being non  empty set;
let R10 being set;
let R11 being set;
let R12 being set;
let R13 being set;
let C46 , C47 being (Function of [: R10 , R11 , R12 , R13 :] , R4);
assume that
L51: (for R14 being set holds (for R15 being set holds (for R16 being set holds (for R17 being set holds ((R14 in R10 & R15 in R11 & R16 in R12 & R17 in R13) implies ( C46 . [ R14 , R15 , R16 , R17 ] ) = ( C47 . [ R14 , R15 , R16 , R17 ] ))))));
L52: (for R18 being set holds (R18 in [: R10 , R11 , R12 , R13 :] implies ( C46 . R18 ) = ( C47 . R18 )))
proof
let R18 being set;
assume L53: R18 in [: R10 , R11 , R12 , R13 :];
L54: (ex R14 being set st (ex R15 being set st (ex R16 being set st (ex R17 being set st (R14 in R10 & R15 in R11 & R16 in R12 & R17 in R13 & R18 = [ R14 , R15 , R16 , R17 ]))))) by L53 , MCART_1:79;
thus L55: thesis by L54 , L51;
end;
thus L56: thesis by L52 , FUNCT_2:12;
end;
theorem
L57: (for R1 being non  empty set holds (for R2 being non  empty set holds (for R3 being non  empty set holds (for R4 being non  empty set holds (for R5 being non  empty set holds (for B67 , B68 being (Function of [: R1 , R2 , R3 , R4 :] , R5) holds ((for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds (for R9 being (Element of R4) holds ( B67 . [ R6 , R7 , R8 , R9 ] ) = ( B68 . [ R6 , R7 , R8 , R9 ] ))))) implies B67 = B68)))))))
proof
let R1 being non  empty set;
let R2 being non  empty set;
let R3 being non  empty set;
let R4 being non  empty set;
let R5 being non  empty set;
let C48 , C49 being (Function of [: R1 , R2 , R3 , R4 :] , R5);
assume L58: (for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds (for R9 being (Element of R4) holds ( C48 . [ R6 , R7 , R8 , R9 ] ) = ( C49 . [ R6 , R7 , R8 , R9 ] )))));
L59: (for R14 being set holds (for R15 being set holds (for R16 being set holds (for R17 being set holds ((R14 in R1 & R15 in R2 & R16 in R3 & R17 in R4) implies ( C48 . [ R14 , R15 , R16 , R17 ] ) = ( C49 . [ R14 , R15 , R16 , R17 ] )))))) by L58;
thus L60: thesis by L59 , L50;
end;
theorem
L61: (for R1 being non  empty set holds (for R2 being non  empty set holds (for R3 being non  empty set holds (for R4 being non  empty set holds (for R5 being non  empty set holds (for B69 , B70 being (Function of [: R1 , R2 , R3 , R4 :] , R5) holds ((for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds (for R9 being (Element of R4) holds ( B69 . (R6 , R7 , R8 , R9) ) = ( B70 . (R6 , R7 , R8 , R9) ))))) implies B69 = B70)))))))
proof
let R1 being non  empty set;
let R2 being non  empty set;
let R3 being non  empty set;
let R4 being non  empty set;
let R5 being non  empty set;
let C50 , C51 being (Function of [: R1 , R2 , R3 , R4 :] , R5);
assume that
L62: (for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds (for R9 being (Element of R4) holds ( C50 . (R6 , R7 , R8 , R9) ) = ( C51 . (R6 , R7 , R8 , R9) )))));
L63: (for R6 being (Element of R1) holds (for R7 being (Element of R2) holds (for R8 being (Element of R3) holds (for R9 being (Element of R4) holds ( C50 . [ R6 , R7 , R8 , R9 ] ) = ( C51 . [ R6 , R7 , R8 , R9 ] )))))
proof
let R6 being (Element of R1);
let R7 being (Element of R2);
let R8 being (Element of R3);
let R9 being (Element of R4);
L64: (( C50 . (R6 , R7 , R8 , R9) ) = ( C50 . [ R6 , R7 , R8 , R9 ] ) & ( C51 . (R6 , R7 , R8 , R9) ) = ( C51 . [ R6 , R7 , R8 , R9 ] ));
thus L65: thesis by L64 , L62;
end;
thus L66: thesis by L63 , L57;
end;
definition
let R1 being non  empty set;
mode QuaOp of R1
 is (Function of [: R1 , R1 , R1 , R1 :] , R1);
end;
scheme FuncEx4D { F16 , F17 , F18 , F19 , F20() -> non  empty set , P3[set , set , set , set , set] } : (ex B71 being (Function of [: F16() , F17() , F18() , F19() :] , F20()) st (for B72 being (Element of F16()) holds (for B73 being (Element of F17()) holds (for B74 being (Element of F18()) holds (for B75 being (Element of F19()) holds P3[ B72 , B73 , B74 , B75 , ( B71 . [ B72 , B73 , B74 , B75 ] ) ])))))
provided
L68: (for B76 being (Element of F16()) holds (for B77 being (Element of F17()) holds (for B78 being (Element of F18()) holds (for B79 being (Element of F19()) holds (ex B80 being (Element of F20()) st P3[ B76 , B77 , B78 , B79 , B80 ])))))
proof
defpred S4[ set , set ] means (for B81 being (Element of F16()) holds (for B82 being (Element of F17()) holds (for B83 being (Element of F18()) holds (for B84 being (Element of F19()) holds ($1 = [ B81 , B82 , B83 , B84 ] implies P3[ B81 , B82 , B83 , B84 , $2 ])))));
L69: (for B85 being (Element of [: F16() , F17() , F18() , F19() :]) holds (ex B86 being (Element of F20()) st S4[ B85 , B86 ]))
proof
let C52 being (Element of [: F16() , F17() , F18() , F19() :]);
consider C53 , C54 , C55 , C56 being set such that L70: C53 in F16() and L71: C54 in F17() and L72: C55 in F18() and L73: C56 in F19() and L74: C52 = [ C53 , C54 , C55 , C56 ] by MCART_1:79;
reconsider D4 = C56 as (Element of F19()) by L73;
reconsider D5 = C55 as (Element of F18()) by L72;
reconsider D6 = C54 as (Element of F17()) by L71;
reconsider D7 = C53 as (Element of F16()) by L70;
consider C57 being (Element of F20()) such that L75: P3[ D7 , D6 , D5 , D4 , C57 ] by L68;
take C57;
let C58 being (Element of F16());
let C59 being (Element of F17());
let C60 being (Element of F18());
let C61 being (Element of F19());
assume L76: C52 = [ C58 , C59 , C60 , C61 ];
L77: D5 = C60 by L76 , L74 , XTUPLE_0:5;
L78: (D7 = C58 & D6 = C59) by L74 , L76 , XTUPLE_0:5;
thus L79: thesis by L78 , L74 , L75 , L76 , L77 , XTUPLE_0:5;
end;
consider C62 being (Function of [: F16() , F17() , F18() , F19() :] , F20()) such that L80: (for B87 being (Element of [: F16() , F17() , F18() , F19() :]) holds S4[ B87 , ( C62 . B87 ) ]) from FUNCT_2:sch 3(L69);
take C62;
let C63 being (Element of F16());
let C64 being (Element of F17());
let C65 being (Element of F18());
let C66 being (Element of F19());
thus L81: thesis by L80;
end;
scheme QuaOpEx { F21() -> non  empty set , P4[(Element of F21()) , (Element of F21()) , (Element of F21()) , (Element of F21()) , (Element of F21())] } : (ex B88 being (QuaOp of F21()) st (for B89 , B90 , B91 , B92 being (Element of F21()) holds P4[ B89 , B90 , B91 , B92 , ( B88 . (B89 , B90 , B91 , B92) ) ]))
provided
L82: (for B93 , B94 , B95 , B96 being (Element of F21()) holds (ex B97 being (Element of F21()) st P4[ B93 , B94 , B95 , B96 , B97 ]))
proof
defpred S5[ (Element of F21()) , (Element of F21()) , (Element of F21()) , (Element of F21()) , (Element of F21()) ] means (for B98 being (Element of F21()) holds (B98 = $5 implies P4[ $1 , $2 , $3 , $4 , $5 ]));
L83: (for B99 , B100 , B101 , B102 being (Element of F21()) holds (ex B103 being (Element of F21()) st S5[ B99 , B100 , B101 , B102 , B103 ]))
proof
let C67 , C68 , C69 , C70 being (Element of F21());
consider C71 being (Element of F21()) such that L84: P4[ C67 , C68 , C69 , C70 , C71 ] by L82;
take C71;
thus L85: thesis by L84;
end;
consider C72 being (Function of [: F21() , F21() , F21() , F21() :] , F21()) such that L86: (for B104 , B105 , B106 , B107 being (Element of F21()) holds S5[ B104 , B105 , B106 , B107 , ( C72 . [ B104 , B105 , B106 , B107 ] ) ]) from FuncEx4D(L83);
take C72;
let C73 , C74 , C75 , C76 being (Element of F21());
thus L87: thesis by L86;
end;
scheme Lambda4D { F22 , F23 , F24 , F25 , F26() -> non  empty set , F27((Element of F22()) , (Element of F23()) , (Element of F24()) , (Element of F25())) -> (Element of F26()) } : (ex B108 being (Function of [: F22() , F23() , F24() , F25() :] , F26()) st (for B109 being (Element of F22()) holds (for B110 being (Element of F23()) holds (for B111 being (Element of F24()) holds (for B112 being (Element of F25()) holds ( B108 . [ B109 , B110 , B111 , B112 ] ) = F27(B109 , B110 , B111 , B112))))))
proof
defpred S6[ (Element of F22()) , (Element of F23()) , (Element of F24()) , (Element of F25()) , (Element of F26()) ] means $5 = F27($1 , $2 , $3 , $4);
L88: (for B113 being (Element of F22()) holds (for B114 being (Element of F23()) holds (for B115 being (Element of F24()) holds (for B116 being (Element of F25()) holds (ex B117 being (Element of F26()) st S6[ B113 , B114 , B115 , B116 , B117 ])))));
L89: (ex B118 being (Function of [: F22() , F23() , F24() , F25() :] , F26()) st (for B119 being (Element of F22()) holds (for B120 being (Element of F23()) holds (for B121 being (Element of F24()) holds (for B122 being (Element of F25()) holds S6[ B119 , B120 , B121 , B122 , ( B118 . [ B119 , B120 , B121 , B122 ] ) ]))))) from FuncEx4D(L88);
thus L90: thesis by L89;
end;
scheme QuaOpLambda { F28() -> non  empty set , F29((Element of F28()) , (Element of F28()) , (Element of F28()) , (Element of F28())) -> (Element of F28()) } : (ex B123 being (QuaOp of F28()) st (for B124 , B125 , B126 , B127 being (Element of F28()) holds ( B123 . (B124 , B125 , B126 , B127) ) = F29(B124 , B125 , B126 , B127)))
proof
deffunc H1((Element of F28()) , (Element of F28()) , (Element of F28()) , (Element of F28())) = F29($1 , $2 , $3 , $4);
consider C77 being (Function of [: F28() , F28() , F28() , F28() :] , F28()) such that L91: (for B128 , B129 , B130 , B131 being (Element of F28()) holds ( C77 . [ B128 , B129 , B130 , B131 ] ) = H1(B128 , B129 , B130 , B131)) from Lambda4D;
take C77;
let C78 , C79 , C80 , C81 being (Element of F28());
thus L92: thesis by L91;
end;
