:: The {N}agata-Smirnov Theorem. {P}art {I}
::  by Karol P\c{a}k
::
:: Received May 31, 2004
:: Copyright (c) 2004-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, XBOOLE_0, PRE_TOPC, METRIC_1, REAL_1, XXREAL_0, CARD_1,
      ARYTM_3, COMPLEX1, ARYTM_1, SETFAM_1, NATTRA_1, RCOMP_1, SUBSET_1,
      STRUCT_0, TARSKI, ZFMISC_1, PCOMPS_1, FINSET_1, FUNCT_1, CARD_3,
      FUNCOP_1, COMPTS_1, RELAT_1, ORDINAL1, RLVECT_3, XREAL_0, CARD_5, NEWTON,
      FINSEQ_1, PSCOMP_1, ORDINAL2, TOPMETR, TMAP_1, BINOP_1, FUNCT_2,
      SETWISEO, COH_SP, FINSOP_1, NAT_1, RELAT_2, NAGATA_1;
 notations BINOP_1, SETWISEO, TARSKI, XBOOLE_0, SUBSET_1, SETFAM_1, RELAT_1,
      FUNCT_1, ORDINAL1, COMPLEX1, RELSET_1, FUNCT_2, FINSEQ_1, ZFMISC_1,
      PCOMPS_1, PRE_TOPC, FINSET_1, CARD_1, XCMPLX_0, NUMBERS, XXREAL_0,
      XREAL_0, REAL_1, NAT_1, FINSOP_1, VALUED_1, STRUCT_0, TOPS_2, COMPTS_1,
      METRIC_1, NEWTON, CARD_3, PROB_1, FUNCOP_1, CANTOR_1, DOMAIN_1, TOPMETR,
      PSCOMP_1, BORSUK_1, TMAP_1;
 constructors SETWISEO, REAL_1, PROB_1, FUNCOP_1, FINSOP_1, NEWTON, CARD_5,
      TOPS_2, COMPTS_1, TMAP_1, CANTOR_1, PCOMPS_1, PSCOMP_1, URYSOHN3;
 registrations XBOOLE_0, SUBSET_1, RELSET_1, FINSET_1, NUMBERS, XXREAL_0,
      XREAL_0, NAT_1, MEMBERED, FINSEQ_1, CARD_LAR, STRUCT_0, TOPS_1, COMPTS_1,
      METRIC_1, BORSUK_1, TOPMETR, PSCOMP_1, VALUED_0, VALUED_1, FUNCT_2,
      CARD_3, FUNCT_1, PRE_TOPC, ZFMISC_1;
 requirements NUMERALS, REAL, BOOLE, SUBSET, ARITHM;
 definitions PCOMPS_1, TARSKI, BINOP_1, SUBSET_1, COMPTS_1, STRUCT_0;
 theorems FUNCT_1, FUNCT_2, METRIC_1, XREAL_0, XCMPLX_1, ABSVALUE, TOPMETR,
      TMAP_1, CARD_1, PCOMPS_1, PCOMPS_2, BORSUK_1, XBOOLE_1, TARSKI, SETFAM_1,
      XBOOLE_0, SUBSET_1, TOPS_1, TOPS_2, PRE_TOPC, COMPTS_1, CARD_3, URYSOHN1,
      NAT_1, YELLOW_9, FINSEQ_1, FINSOP_1, SETWISEO, NEWTON, ZFMISC_1, BINOP_1,
      SEQ_2, PROB_1, FUNCOP_1, XREAL_1, COMPLEX1, XXREAL_0, PREPOWER, ORDINAL1,
      VALUED_1, JORDAN5A;
 schemes FUNCT_1, FRAENKEL, FUNCT_2, NAT_1;

begin
L1: (for B1 , B2 , B3 being Real holds ((B1 >= ( 0 ) & B2 >= ( 0 ) & ( B1 + B2 ) < B3) implies (B1 < B3 & B2 < B3)))
proof
let C1 , C2 , C3 being Real;
assume that
L2: (C1 >= ( 0 ) & C2 >= ( 0 ))
and
L3: ( C1 + C2 ) < C3;
assume L4: (C1 >= C3 or C2 >= C3);
L5: (( C1 + C2 ) >= ( C3 + ( 0 ) ) or ( C2 + C1 ) >= ( C3 + ( 0 ) )) by L4 , L2 , XREAL_1:7;
thus L6: thesis by L5 , L3;
end;
L7: (for B4 , B5 , B6 , B7 being Real holds ( abs ( B4 - B7 ) ) <= ( ( ( abs ( B4 - B5 ) ) + ( abs ( B5 - B6 ) ) ) + ( abs ( B6 - B7 ) ) ))
proof
let C4 , C5 , C6 , C7 being Real;
L8: ( C5 - C7 ) = ( ( C5 - C6 ) + ( C6 - C7 ) );
L9: ( abs ( C5 - C7 ) ) <= ( ( abs ( C5 - C6 ) ) + ( abs ( C6 - C7 ) ) ) by L8 , COMPLEX1:56;
L10: ( ( abs ( C4 - C5 ) ) + ( abs ( C5 - C7 ) ) ) <= ( ( abs ( C4 - C5 ) ) + ( ( abs ( C5 - C6 ) ) + ( abs ( C6 - C7 ) ) ) ) by L9 , XREAL_1:7;
L11: ( C4 - C7 ) = ( ( C4 - C5 ) + ( C5 - C7 ) );
L12: ( abs ( C4 - C7 ) ) <= ( ( abs ( C4 - C5 ) ) + ( abs ( C5 - C7 ) ) ) by L11 , COMPLEX1:56;
thus L13: thesis by L12 , L10 , XXREAL_0:2;
end;
definition
let C8 being TopSpace;
let C9 being (Subset-Family of C8);
attr C9 is  discrete
means
:L14: (for B8 being (Point of C8) holds (ex B9 being  open (Subset of C8) st (B8 in B9 & (for B10 , B11 being (Subset of C8) holds ((B10 in C9 & B11 in C9) implies ((B9 meets B10 & B9 meets B11) implies B10 = B11))))));
end;
registration
let C10 being non  empty TopSpace;
cluster  discrete for (Subset-Family of C10);
existence
proof
set D1 = { ( {} ) , (the carrier of C10) };
L16: D1 c= ( bool (the carrier of C10) )
proof
let C11 being set;
assume L17: C11 in D1;
L18: (C11 = ( {} ) or C11 = (the carrier of C10)) by L17 , TARSKI:def 2;
L19: C11 c= (the carrier of C10) by L18 , XBOOLE_1:2;
thus L20: thesis by L19;
end;
reconsider D2 = D1 as (Subset-Family of C10) by L16;
take D2;
let C12 being (Point of C10);
take D3 = ( [#] C10 );
thus L21: C12 in D3;
L22:
now
let C13 , C14 being (Subset of C10);
assume that
L23: C13 in D2
and
L24: C14 in D2;
L25: (C14 = ( {} ) or C14 = (the carrier of C10)) by L24 , TARSKI:def 2;
assume L26: (D3 meets C13 & D3 meets C14);
L27: (( D3 /\ C13 ) <> ( {} ) & ( D3 /\ C14 ) <> ( {} )) by L26 , XBOOLE_0:def 7;
L28: (C13 = ( {} ) or C13 = (the carrier of C10)) by L23 , TARSKI:def 2;
thus L29: C13 = C14 by L28 , L25 , L27;
end;
thus L30: thesis by L22;
end;
end;
registration
let R1 being non  empty TopSpace;
cluster  empty  discrete for (Subset-Family of R1);
existence
proof
reconsider D4 = ( {} ) as (Subset-Family of R1) by XBOOLE_1:2;
take D4;
thus L32: D4 is  empty;
let C15 being (Point of R1);
take ( [#] R1 );
thus L33: thesis;
end;
end;
theorem
L35: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds ((ex R6 being (Subset of R1) st R3 = { R6 }) implies R3 is  discrete)))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
assume L36: (ex R6 being (Subset of R1) st R3 = { R6 });
consider R6 being (Subset of R1) such that L37: R3 = { R6 } by L36;
L38:
now
let R12 being (Point of R1);
take D5 = ( [#] R1 );
thus L39: R12 in D5;
L40:
now
let R7 being (Subset of R1);
let R8 being (Subset of R1);
assume that
L41: R7 in R3
and
L42: R8 in R3;
L43: { R7 } c= { R6 } by L37 , L41 , ZFMISC_1:31;
L44: R7 = R6 by L43 , ZFMISC_1:3;
L45: { R8 } c= { R6 } by L37 , L42 , ZFMISC_1:31;
thus L46: R7 = R8 by L45 , L44 , ZFMISC_1:3;
end;
thus L47: (for R7 being (Subset of R1) holds (for R8 being (Subset of R1) holds ((R7 in R3 & R8 in R3) implies ((D5 meets R7 & D5 meets R8) implies R7 = R8)))) by L40;
end;
thus L48: thesis by L38 , L14;
end;
theorem
L49: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (for R4 being (Subset-Family of R1) holds ((R3 c= R4 & R4 is  discrete) implies R3 is  discrete))))
proof
let R1 being non  empty TopSpace;
let C16 , C17 being (Subset-Family of R1);
assume that
L50: C16 c= C17
and
L51: C17 is  discrete;
L52:
now
let R12 being (Point of R1);
thus L53: (ex R10 being  open (Subset of R1) st (R12 in R10 & (for R8 being (Subset of R1) holds (for R9 being (Subset of R1) holds ((R8 in C16 & R9 in C16) implies ((R10 meets R8 & R10 meets R9) implies R8 = R9))))))
proof
consider R11 being  open (Subset of R1) such that L54: (R12 in R11 & (for R8 being (Subset of R1) holds (for R9 being (Subset of R1) holds ((R8 in C17 & R9 in C17) implies ((R11 meets R8 & R11 meets R9) implies R8 = R9))))) by L51 , L14;
take D6 = R11;
thus L55: thesis by L50 , L54;
end;

thus L56: (ex R10 being  open (Subset of R1) st (R12 in R10 & (for R8 being (Subset of R1) holds (for R9 being (Subset of R1) holds ((R8 in C16 & R9 in C16) implies ((R10 meets R8 & R10 meets R9) implies R8 = R9)))))) by L53;
end;
thus L57: thesis by L52 , L14;
end;
theorem
L58: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (for R4 being (Subset-Family of R1) holds (R3 is  discrete implies ( R3 /\ R4 ) is  discrete)))) by L49 , XBOOLE_1:17;
theorem
L59: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (for R4 being (Subset-Family of R1) holds (R3 is  discrete implies ( R3 \ R4 ) is  discrete)))) by L49 , XBOOLE_1:36;
theorem
L60: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (for R4 being (Subset-Family of R1) holds (for R5 being (Subset-Family of R1) holds ((R3 is  discrete & R4 is  discrete & ( INTERSECTION (R3 , R4) ) = R5) implies R5 is  discrete)))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
let R4 being (Subset-Family of R1);
let R5 being (Subset-Family of R1);
assume that
L61: R3 is  discrete
and
L62: R4 is  discrete
and
L63: ( INTERSECTION (R3 , R4) ) = R5;
L64:
now
let R12 being (Point of R1);
consider R10 being  open (Subset of R1) such that L65: R12 in R10 and L66: (for B12 , B13 being (Subset of R1) holds ((B12 in R3 & B13 in R3) implies ((R10 meets B12 & R10 meets B13) implies B12 = B13))) by L61 , L14;
consider R11 being  open (Subset of R1) such that L67: R12 in R11 and L68: (for B14 , B15 being (Subset of R1) holds ((B14 in R4 & B15 in R4) implies ((R11 meets B14 & R11 meets B15) implies B14 = B15))) by L62 , L14;
L69:
now
let R6 being (Subset of R1);
let R7 being (Subset of R1);
assume that
L70: R6 in ( INTERSECTION (R3 , R4) )
and
L71: R7 in ( INTERSECTION (R3 , R4) );
consider C18 , C19 being set such that L72: C18 in R3 and L73: C19 in R4 and L74: R6 = ( C18 /\ C19 ) by L70 , SETFAM_1:def 5;
assume that
L75: ( R10 /\ R11 ) meets R6
and
L76: ( R10 /\ R11 ) meets R7;
consider C20 , C21 being set such that L77: C20 in R3 and L78: C21 in R4 and L79: R7 = ( C20 /\ C21 ) by L71 , SETFAM_1:def 5;
L80: ( ( R10 /\ R11 ) /\ ( C20 /\ C21 ) ) <> ( {} ) by L79 , L76 , XBOOLE_0:def 7;
L81: ( ( ( R10 /\ R11 ) /\ C20 ) /\ C21 ) <> ( {} ) by L80 , XBOOLE_1:16;
L82: ( ( ( R10 /\ C20 ) /\ R11 ) /\ C21 ) <> ( {} ) by L81 , XBOOLE_1:16;
L83: ( R10 /\ C20 ) <> ( {} ) by L82;
L84: R10 meets C20 by L83 , XBOOLE_0:def 7;
L85: ( ( R10 /\ R11 ) /\ ( C18 /\ C19 ) ) <> ( {} ) by L74 , L75 , XBOOLE_0:def 7;
L86: ( ( ( R10 /\ R11 ) /\ C18 ) /\ C19 ) <> ( {} ) by L85 , XBOOLE_1:16;
L87: ( ( ( R10 /\ C18 ) /\ R11 ) /\ C19 ) <> ( {} ) by L86 , XBOOLE_1:16;
L88: ( ( R10 /\ C18 ) /\ ( R11 /\ C19 ) ) <> ( {} ) by L87 , XBOOLE_1:16;
L89: ( R11 /\ C19 ) <> ( {} ) by L88;
L90: R11 meets C19 by L89 , XBOOLE_0:def 7;
L91: ( ( R10 /\ C20 ) /\ ( R11 /\ C21 ) ) <> ( {} ) by L82 , XBOOLE_1:16;
L92: ( R11 /\ C21 ) <> ( {} ) by L91;
L93: R11 meets C21 by L92 , XBOOLE_0:def 7;
L94: ( R10 /\ C18 ) <> ( {} ) by L87;
L95: R10 meets C18 by L94 , XBOOLE_0:def 7;
L96: C18 = C20 by L95 , L66 , L72 , L77 , L84;
thus L97: R6 = R7 by L96 , L68 , L73 , L74 , L78 , L79 , L90 , L93;
end;
set D7 = ( R10 /\ R11 );
L98: R12 in D7 by L65 , L67 , XBOOLE_0:def 4;
thus L99: (ex B16 being  open (Subset of R1) st (R12 in B16 & (for B17 , B18 being (Subset of R1) holds ((B17 in R5 & B18 in R5) implies ((B16 meets B17 & B16 meets B18) implies B17 = B18))))) by L98 , L63 , L69;
end;
thus L100: thesis by L64 , L14;
end;
theorem
L101: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R3 is  discrete & R6 in R3 & R7 in R3) implies (R6 = R7 or R6 misses R7))))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
let R6 being (Subset of R1);
let R7 being (Subset of R1);
assume that
L102: R3 is  discrete
and
L103: (R6 in R3 & R7 in R3);
assume that
L104: R6 <> R7
and
L105: R6 meets R7;
L106: ( R6 /\ R7 ) <> ( {} R1 ) by L105 , XBOOLE_0:def 7;
consider R12 being (Point of R1) such that L107: R12 in ( R6 /\ R7 ) by L106 , PRE_TOPC:12;
consider R10 being  open (Subset of R1) such that L108: R12 in R10 and L109: (for R8 being (Subset of R1) holds (for R9 being (Subset of R1) holds ((R8 in R3 & R9 in R3) implies ((R10 meets R8 & R10 meets R9) implies R8 = R9)))) by L102 , L14;
L110: { R12 } c= R10 by L108 , ZFMISC_1:31;
L111: R12 in R7 by L107 , XBOOLE_0:def 4;
L112: { R12 } c= R7 by L111 , ZFMISC_1:31;
L113: { R12 } c= ( R10 /\ R7 ) by L112 , L110 , XBOOLE_1:19;
L114: R12 in ( R10 /\ R7 ) by L113 , ZFMISC_1:31;
L115: R12 in R6 by L107 , XBOOLE_0:def 4;
L116: { R12 } c= R6 by L115 , ZFMISC_1:31;
L117: { R12 } c= ( R10 /\ R6 ) by L116 , L110 , XBOOLE_1:19;
L118: R12 in ( R10 /\ R6 ) by L117 , ZFMISC_1:31;
L119: ((R10 meets R6 & R10 meets R7) implies R6 = R7) by L103 , L109;
thus L120: contradiction by L119 , L104 , L118 , L114 , XBOOLE_0:4;
end;
theorem
L121: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (R3 is  discrete implies (for R12 being (Point of R1) holds (ex R10 being  open (Subset of R1) st (R12 in R10 & ( ( INTERSECTION ({ R10 } , R3) ) \ { ( {} ) } ) is  trivial))))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
assume L122: R3 is  discrete;
let R12 being (Point of R1);
consider R10 being  open (Subset of R1) such that L123: R12 in R10 and L124: (for R8 being (Subset of R1) holds (for R9 being (Subset of R1) holds ((R8 in R3 & R9 in R3) implies ((R10 meets R8 & R10 meets R9) implies R8 = R9)))) by L122 , L14;
set D8 = ( INTERSECTION ({ R10 } , R3) );
L125: (for B19 , B20 being set holds ((B19 in D8 & B20 in D8) implies (B19 = B20 or B19 = ( {} ) or B20 = ( {} ))))
proof
let C22 , C23 being set;
assume that
L126: C22 in D8
and
L127: C23 in D8;
consider C24 , C25 being set such that L128: C24 in { R10 } and L129: C25 in R3 and L130: C22 = ( C24 /\ C25 ) by L126 , SETFAM_1:def 5;
consider C26 , C27 being set such that L131: C26 in { R10 } and L132: C27 in R3 and L133: C23 = ( C26 /\ C27 ) by L127 , SETFAM_1:def 5;
L134: { C26 } c= { R10 } by L131 , ZFMISC_1:31;
L135: C26 = R10 by L134 , ZFMISC_1:3;
L136: { C24 } c= { R10 } by L128 , ZFMISC_1:31;
L137: C24 = R10 by L136 , ZFMISC_1:3;
L138: ((R10 meets C25 & R10 meets C27) or C22 = ( {} ) or C23 = ( {} )) by L137 , L130 , L133 , L135 , XBOOLE_0:def 7;
thus L139: thesis by L138 , L124 , L129 , L130 , L132 , L133 , L137 , L135;
end;
L140: (for B21 being set holds ((B21 <> ( {} ) & B21 in D8) implies D8 c= { ( {} ) , B21 }))
proof
let C28 being set;
assume L141: (C28 <> ( {} ) & C28 in D8);
L142:
now
let C29 being set;
assume L143: C29 in D8;
L144: (C28 = C29 or C29 = ( {} )) by L143 , L125 , L141;
thus L145: C29 in { ( {} ) , C28 } by L144 , TARSKI:def 2;
end;
thus L146: thesis by L142 , TARSKI:def 3;
end;
L147:
now
per cases ;
suppose L148: ( D8 \ { ( {} ) } ) <> ( {} );

consider C30 being set such that L149: C30 in ( D8 \ { ( {} ) } ) by L148 , XBOOLE_0:def 1;
L150: C30 <> ( {} ) by L149 , ZFMISC_1:56;
L151: D8 c= { ( {} ) , C30 } by L150 , L140 , L149;
L152:
now
let C31 being set;
assume L153: C31 in D8;
L154: { C31 } c= { ( {} ) , C30 } by L153 , L151 , ZFMISC_1:31;
L155: (C31 = ( {} ) or C31 = C30) by L154 , ZFMISC_1:19;
L156: (C31 in { ( {} ) } or C31 in { C30 }) by L155 , ZFMISC_1:31;
thus L157: C31 in ( { ( {} ) } \/ { C30 } ) by L156 , XBOOLE_0:def 3;
end;
L158: D8 c= ( { ( {} ) } \/ { C30 } ) by L152 , TARSKI:def 3;
L159: ( D8 \ { ( {} ) } ) c= { C30 } by L158 , XBOOLE_1:43;
L160: (( D8 \ { ( {} ) } ) = ( {} ) or ( D8 \ { ( {} ) } ) = { C30 }) by L159 , ZFMISC_1:33;
thus L161: ( D8 \ { ( {} ) } ) is  trivial by L160;
end;
suppose L162: ( D8 \ { ( {} ) } ) = ( {} );

thus L163: ( D8 \ { ( {} ) } ) is  trivial by L162;
end;
end;
thus L165: thesis by L147 , L123;
end;
theorem
L166: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (R3 is  discrete iff ((for R12 being (Point of R1) holds (ex R10 being  open (Subset of R1) st (R12 in R10 & ( ( INTERSECTION ({ R10 } , R3) ) \ { ( {} ) } ) is  trivial))) & (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies (R6 = R7 or R6 misses R7))))))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
L167:
now
let R3 being (Subset-Family of R1);
L168: (((for R12 being (Point of R1) holds (ex R10 being  open (Subset of R1) st (R12 in R10 & ( ( INTERSECTION ({ R10 } , R3) ) \ { ( {} ) } ) is  trivial))) & (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies (R6 = R7 or R6 misses R7))))) implies R3 is  discrete)
proof
assume that
L169: (for R12 being (Point of R1) holds (ex R10 being  open (Subset of R1) st (R12 in R10 & ( ( INTERSECTION ({ R10 } , R3) ) \ { ( {} ) } ) is  trivial)))
and
L170: (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies (R6 = R7 or R6 misses R7))));
assume L171: (not R3 is  discrete);
consider R12 being (Point of R1) such that L172: (for R10 being  open (Subset of R1) holds ((not R12 in R10) or (not (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies ((R10 meets R6 & R10 meets R7) implies R6 = R7))))))) by L171 , L14;
consider R10 being  open (Subset of R1) such that L173: R12 in R10 and L174: ( ( INTERSECTION ({ R10 } , R3) ) \ { ( {} ) } ) is  trivial by L169;
consider R6 being (Subset of R1), R7 being (Subset of R1) such that L175: R6 in R3 and L176: R7 in R3 and L177: R10 meets R6 and L178: R10 meets R7 and L179: R6 <> R7 by L172 , L173;
L180: ( R10 /\ R7 ) <> ( {} ) by L178 , XBOOLE_0:def 7;
set D9 = ( INTERSECTION ({ R10 } , R3) );
consider C32 being set such that L181: (( D9 \ { ( {} ) } ) = ( {} ) or ( D9 \ { ( {} ) } ) = { C32 }) by L174 , ZFMISC_1:131;
L182: R10 in { R10 } by ZFMISC_1:31;
L183: ( R10 /\ R7 ) in D9 by L182 , L176 , SETFAM_1:def 5;
L184: ( R10 /\ R7 ) in ( D9 \ { ( {} ) } ) by L183 , L180 , ZFMISC_1:56;
L185: { ( R10 /\ R7 ) } c= { C32 } by L184 , L181 , ZFMISC_1:31;
L186: ( R10 /\ R7 ) = C32 by L185 , ZFMISC_1:3;
L187: ( R10 /\ R6 ) <> ( {} ) by L177 , XBOOLE_0:def 7;
consider C33 being set such that L188: C33 in ( R10 /\ R6 ) by L187 , XBOOLE_0:def 1;
L189: C33 in R6 by L188 , XBOOLE_0:def 4;
L190: ( R10 /\ R6 ) in D9 by L175 , L182 , SETFAM_1:def 5;
L191: ( R10 /\ R6 ) in ( D9 \ { ( {} ) } ) by L190 , L187 , ZFMISC_1:56;
L192: { ( R10 /\ R6 ) } c= { C32 } by L191 , L181 , ZFMISC_1:31;
L193: ( R10 /\ R6 ) = C32 by L192 , ZFMISC_1:3;
L194: C33 in R7 by L193 , L186 , L188 , XBOOLE_0:def 4;
L195: C33 in ( R6 /\ R7 ) by L194 , L189 , XBOOLE_0:def 4;
L196: R6 misses R7 by L170 , L175 , L176 , L179;
thus L197: thesis by L196 , L195 , XBOOLE_0:def 7;
end;
thus L198: (R3 is  discrete iff ((for R12 being (Point of R1) holds (ex R10 being  open (Subset of R1) st (R12 in R10 & ( ( INTERSECTION ({ R10 } , R3) ) \ { ( {} ) } ) is  trivial))) & (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies (R6 = R7 or R6 misses R7)))))) by L168 , L101 , L121;
end;
thus L199: thesis by L167;
end;
L200: (for R1 being non  empty TopSpace holds (for R10 being  open (Subset of R1) holds (for R6 being (Subset of R1) holds (R10 meets ( Cl R6 ) implies R10 meets R6))))
proof
let R1 being non  empty TopSpace;
let R10 being  open (Subset of R1);
let R6 being (Subset of R1);
L201: (R10 misses R6 implies R10 misses ( Cl R6 ))
proof
assume L202: R10 misses R6;
L203: R6 c= ( R10 ` ) by L202 , SUBSET_1:23;
L204: ( Cl R6 ) c= ( R10 ` ) by L203 , TOPS_1:5;
thus L205: thesis by L204 , SUBSET_1:23;
end;
thus L206: thesis by L201;
end;
registration
let R1 being non  empty TopSpace;
let C34 being  discrete (Subset-Family of R1);
cluster ( clf C34 ) ->  discrete;
coherence
proof
thus L207: ( clf C34 ) is  discrete
proof
let R12 being (Point of R1);
consider R10 being  open (Subset of R1) such that L208: R12 in R10 and L209: (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in C34 & R7 in C34) implies ((R10 meets R6 & R10 meets R7) implies R6 = R7)))) by L14;
L210:
now
let R6 being (Subset of R1);
let R7 being (Subset of R1);
assume that
L211: R6 in ( clf C34 )
and
L212: R7 in ( clf C34 );
consider R8 being (Subset of R1) such that L213: R6 = ( Cl R8 ) and L214: R8 in C34 by L211 , PCOMPS_1:def 2;
assume that
L215: R10 meets R6
and
L216: R10 meets R7;
consider R9 being (Subset of R1) such that L217: R7 = ( Cl R9 ) and L218: R9 in C34 by L212 , PCOMPS_1:def 2;
L219: R10 meets R9 by L217 , L216 , L200;
L220: R10 meets R8 by L213 , L215 , L200;
thus L221: R6 = R7 by L220 , L209 , L213 , L214 , L217 , L218 , L219;
end;
thus L222: thesis by L210 , L208;
end;

end;
end;
L209: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (for R6 being (Subset of R1) holds (R6 in R3 implies ( Cl R6 ) c= ( Cl ( union R3 ) )))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
let R6 being (Subset of R1);
assume L210: R6 in R3;
L211: (for B22 being set holds (B22 in R6 implies B22 in ( union R3 ))) by L210 , TARSKI:def 4;
L212: R6 c= ( union R3 ) by L211 , TARSKI:def 3;
thus L213: thesis by L212 , PRE_TOPC:19;
end;
theorem
L214: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (R3 is  discrete implies (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies ( Cl ( R6 /\ R7 ) ) = ( ( Cl R6 ) /\ ( Cl R7 ) )))))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
assume that
L215: R3 is  discrete;
let R6 being (Subset of R1);
let R7 being (Subset of R1);
assume that
L216: (R6 in R3 & R7 in R3);
L217:
now
per cases  by L215 , L216 , L101;
suppose L218: R6 misses R7;

L219: ( R6 /\ R7 ) = ( {} R1 ) by L218 , XBOOLE_0:def 7;
L220: ( ( Cl R6 ) /\ ( Cl R7 ) ) = ( {} )
proof
assume L221: ( ( Cl R6 ) /\ ( Cl R7 ) ) <> ( {} );
consider R14 being set such that L222: R14 in ( ( Cl R6 ) /\ ( Cl R7 ) ) by L221 , XBOOLE_0:def 1;
consider R10 being  open (Subset of R1) such that L223: R14 in R10 and L224: (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies ((R10 meets R6 & R10 meets R7) implies R6 = R7)))) by L215 , L222 , L14;
L225: R14 in ( Cl R6 ) by L222 , XBOOLE_0:def 4;
L226: R10 meets R6 by L225 , L223 , PRE_TOPC:def 7;
L227: R14 in ( Cl R7 ) by L222 , XBOOLE_0:def 4;
L228: R10 meets R7 by L227 , L223 , PRE_TOPC:def 7;
L229: R6 = R7 by L228 , L216 , L224 , L226;
thus L230: thesis by L229 , L219 , L226 , XBOOLE_1:65;
end;
thus L231: thesis by L220 , L219 , PRE_TOPC:22;
end;
suppose L232: R6 = R7;

thus L233: thesis by L232;
end;
end;
thus L235: thesis by L217;
end;
theorem
L236: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (R3 is  discrete implies ( Cl ( union R3 ) ) = ( union ( clf R3 ) ))))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
assume L237: R3 is  discrete;
L238: ( Cl ( union R3 ) ) c= ( union ( clf R3 ) )
proof
let R14 being set;
assume L239: R14 in ( Cl ( union R3 ) );
consider R10 being  open (Subset of R1) such that L240: R14 in R10 and L241: (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies ((R10 meets R6 & R10 meets R7) implies R6 = R7)))) by L239 , L237 , L14;
L242: (not R10 misses ( union R3 )) by L239 , L240 , PRE_TOPC:def 7;
consider C35 being set such that L243: C35 in R10 and L244: C35 in ( union R3 ) by L242 , XBOOLE_0:3;
consider C36 being set such that L245: C35 in C36 and L246: C36 in R3 by L244 , TARSKI:def 4;
reconsider D10 = C36 as (Subset of R1) by L246;
L247: R10 meets D10 by L243 , L245 , XBOOLE_0:3;
L248: (for R9 being (Subset of R1) holds ((R9 is  open & R14 in R9) implies (not R9 misses D10)))
proof
assume L249: (ex R9 being (Subset of R1) st (R9 is  open & R14 in R9 & R9 misses D10));
consider R9 being (Subset of R1) such that L250: R9 is  open and L251: R14 in R9 and L252: R9 misses D10 by L249;
L253: R14 in ( R9 /\ R10 ) by L240 , L251 , XBOOLE_0:def 4;
L254: ( R9 /\ R10 ) meets ( union R3 ) by L253 , L239 , L250 , PRE_TOPC:def 7;
consider R15 being set such that L255: R15 in ( R9 /\ R10 ) and L256: R15 in ( union R3 ) by L254 , XBOOLE_0:3;
consider C37 being set such that L257: R15 in C37 and L258: C37 in R3 by L256 , TARSKI:def 4;
L259: R15 in R9 by L255 , XBOOLE_0:def 4;
L260: R15 in ( R9 /\ C37 ) by L259 , L257 , XBOOLE_0:def 4;
L261: R9 meets C37 by L260 , XBOOLE_0:def 7;
L262: R15 in R10 by L255 , XBOOLE_0:def 4;
L263: R15 in ( R10 /\ C37 ) by L262 , L257 , XBOOLE_0:def 4;
L264: R10 meets C37 by L263 , XBOOLE_0:def 7;
thus L265: contradiction by L264 , L241 , L246 , L247 , L252 , L258 , L261;
end;
L266: R14 in ( Cl D10 ) by L248 , L239 , PRE_TOPC:def 7;
L267: ( Cl D10 ) in ( clf R3 ) by L246 , PCOMPS_1:def 2;
thus L268: thesis by L267 , L266 , TARSKI:def 4;
end;
L269: ( union ( clf R3 ) ) c= ( Cl ( union R3 ) )
proof
let C38 being set;
assume L270: C38 in ( union ( clf R3 ) );
consider C39 being set such that L271: C38 in C39 and L272: C39 in ( clf R3 ) by L270 , TARSKI:def 4;
reconsider D11 = C39 as (Subset of R1) by L272;
L273: (ex R6 being (Subset of R1) st (( Cl R6 ) = D11 & R6 in R3)) by L272 , PCOMPS_1:def 2;
L274: D11 c= ( Cl ( union R3 ) ) by L273 , L209;
thus L275: thesis by L274 , L271;
end;
thus L276: thesis by L269 , L238 , XBOOLE_0:def 10;
end;
theorem
L277: (for R1 being non  empty TopSpace holds (for R3 being (Subset-Family of R1) holds (R3 is  discrete implies R3 is  locally_finite)))
proof
let R1 being non  empty TopSpace;
let R3 being (Subset-Family of R1);
assume L278: R3 is  discrete;
L279: (for R12 being (Point of R1) holds (ex R6 being (Subset of R1) st (R12 in R6 & R6 is  open & { R9 where R9 is (Subset of R1) : (R9 in R3 & R9 meets R6) } is  finite)))
proof
let R12 being (Point of R1);
consider R11 being  open (Subset of R1) such that L280: R12 in R11 and L281: (for R6 being (Subset of R1) holds (for R7 being (Subset of R1) holds ((R6 in R3 & R7 in R3) implies ((R11 meets R6 & R11 meets R7) implies R6 = R7)))) by L278 , L14;
set D12 = { R9 where R9 is (Subset of R1) : (R9 in R3 & R9 meets R11) };
take D13 = R11;
L282: (D12 <> ( {} ) implies (ex R6 being (Subset of R1) st D12 = { R6 }))
proof
assume L283: D12 <> ( {} );
consider C40 being set such that L284: C40 in D12 by L283 , XBOOLE_0:def 1;
consider R9 being (Subset of R1) such that L285: C40 = R9 and L286: (R9 in R3 & R9 meets D13) by L284;
L287:
now
let C41 being set;
assume L288: C41 in D12;
L289: (ex R8 being (Subset of R1) st (C41 = R8 & R8 in R3 & R8 meets D13)) by L288;
L290: C41 = R9 by L289 , L281 , L286;
thus L291: C41 in { R9 } by L290 , TARSKI:def 1;
end;
L292: D12 c= { R9 } by L287 , TARSKI:def 3;
L293: { R9 } c= D12 by L284 , L285 , ZFMISC_1:31;
L294: D12 = { R9 } by L293 , L292 , XBOOLE_0:def 10;
thus L295: thesis by L294;
end;
thus L296: thesis by L282 , L280;
end;
thus L297: thesis by L279 , PCOMPS_1:def 1;
end;
definition
let C42 being TopSpace;
mode FamilySequence of C42
 is (Function of ( NAT ) , (( bool ( bool (the carrier of C42) ) ) qua non  empty set));
end;
definition
let R1 being non  empty TopSpace;
let R17 being (FamilySequence of R1);
let R21 being (Element of ( NAT ));
redefine func R17 . R21 -> (Subset-Family of R1);

coherence
proof
L299: ( R17 . R21 ) c= ( bool (the carrier of R1) );
thus L300: thesis by L299;
end;
end;
definition
let R1 being non  empty TopSpace;
let R17 being (FamilySequence of R1);
redefine func Union R17 -> (Subset-Family of R1);

coherence
proof
L302: ( Union R17 ) c= ( bool (the carrier of R1) );
thus L303: thesis by L302;
end;
end;
definition
let C43 being non  empty TopSpace;
let C44 being (FamilySequence of C43);
attr C44 is  sigma_discrete
means
:L305: (for B23 being (Element of ( NAT )) holds ( C44 . B23 ) is  discrete);
end;
L307: (for R1 being non  empty TopSpace holds (ex B24 being (FamilySequence of R1) st B24 is  sigma_discrete))
proof
let R1 being non  empty TopSpace;
set D14 = { (the carrier of R1) };
L308: (the carrier of R1) in ( bool (the carrier of R1) ) by ZFMISC_1:def 1;
L309: D14 c= ( bool (the carrier of R1) ) by L308 , ZFMISC_1:31;
reconsider D15 = ( ( NAT ) --> D14 ) as (Function of ( NAT ) , ( bool ( bool (the carrier of R1) ) )) by L309 , FUNCOP_1:45;
take D15;
L310:
now
let R21 being (Element of ( NAT ));
L311: (the carrier of R1) is (Subset of R1) by ZFMISC_1:def 1;
thus L312: ( D15 . R21 ) is  discrete by L311 , L35 , FUNCOP_1:7;
end;
thus L313: thesis by L310 , L305;
end;
registration
let C45 being non  empty TopSpace;
cluster  sigma_discrete for (FamilySequence of C45);
existence by L307;
end;
definition
let C46 being non  empty TopSpace;
let C47 being (FamilySequence of C46);
attr C47 is  sigma_locally_finite
means
:L315: (for B25 being (Element of ( NAT )) holds ( C47 . B25 ) is  locally_finite);
end;
definition
let R1 being non  empty TopSpace;
let C48 being (Subset-Family of R1);
attr C48 is  sigma_discrete
means
:L317: (ex B26 being  sigma_discrete (FamilySequence of R1) st C48 = ( Union B26 ));
end;
notation
let C49 being set;
antonym C49 is  uncountable for C49 is  countable;
end;
registration
cluster  uncountable -> non  empty for set;
coherence;
end;
registration
let C50 being non  empty TopSpace;
cluster  sigma_locally_finite for (FamilySequence of C50);
existence
proof
thus L321: (ex B27 being (FamilySequence of C50) st B27 is  sigma_locally_finite)
proof
consider C51 being (FamilySequence of C50) such that L322: C51 is  sigma_discrete by L307;
take C51;
L323:
now
let R21 being (Element of ( NAT ));
L324: ( C51 . R21 ) is  discrete by L322 , L305;
thus L325: ( C51 . R21 ) is  locally_finite by L324 , L277;
end;
thus L326: thesis by L323 , L315;
end;

end;
end;
theorem
L323: (for R1 being non  empty TopSpace holds (for R17 being (FamilySequence of R1) holds (R17 is  sigma_discrete implies R17 is  sigma_locally_finite)))
proof
let R1 being non  empty TopSpace;
let R17 being (FamilySequence of R1);
assume L324: R17 is  sigma_discrete;
let R21 being (Element of ( NAT ));
L325: ( R17 . R21 ) is  discrete by L324 , L305;
thus L326: thesis by L325 , L277;
end;
theorem
L327: (for B28 being  uncountable set holds (ex B29 being (Subset-Family of ( 1TopSp [: B28 , B28 :] )) st (B29 is  locally_finite & (not B29 is  sigma_discrete))))
proof
let C52 being  uncountable set;
set D16 = ( 1TopSp [: C52 , C52 :] );
set D17 = { ( [: { B30 } , C52 :] \/ [: C52 , { B30 } :] ) where B30 is (Element of C52) : B30 in C52 };
L328: D17 c= ( bool [: C52 , C52 :] )
proof
let C53 being set;
assume L329: C53 in D17;
consider C54 being (Element of C52) such that L330: C53 = ( [: { C54 } , C52 :] \/ [: C52 , { C54 } :] ) and L331: C54 in C52 by L329;
L332: ([: { C54 } , C52 :] c= [: C52 , C52 :] & [: C52 , { C54 } :] c= [: C52 , C52 :]) by ZFMISC_1:96;
L333: ( [: { C54 } , C52 :] \/ [: C52 , { C54 } :] ) c= [: C52 , C52 :] by L332 , XBOOLE_1:8;
thus L334: thesis by L333 , L330;
end;
reconsider D18 = D17 as (Subset-Family of D16) by L328;
take D18;
L335: (for B31 being (Point of D16) holds (ex B32 being (Subset of D16) st (B31 in B32 & B32 is  open & { B33 where B33 is (Subset of D16) : (B33 in D18 & B33 meets B32) } is  finite)))
proof
let C55 being (Point of D16);
set D19 = { C55 };
reconsider D20 = D19 as (Subset of D16);
consider R14 being set, R15 being set such that L336: R14 in C52 and L337: R15 in C52 and L338: C55 = [ R14 , R15 ] by ZFMISC_1:def 2;
set D21 = { ( [: { R15 } , C52 :] \/ [: C52 , { R15 } :] ) };
set D22 = { ( [: { R14 } , C52 :] \/ [: C52 , { R14 } :] ) };
set D23 = { B34 where B34 is (Subset of D16) : (B34 in D18 & B34 meets D20) };
L339: D23 c= ( D22 \/ D21 )
proof
let C56 being set;
assume L340: C56 in D23;
consider C57 being (Subset of D16) such that L341: C56 = C57 and L342: C57 in D18 and L343: C57 meets D20 by L340;
consider C58 being set such that L344: C58 in C57 and L345: C58 in D20 by L343 , XBOOLE_0:3;
consider C59 being (Element of C52) such that L346: C57 = ( [: { C59 } , C52 :] \/ [: C52 , { C59 } :] ) and L347: C59 in C52 by L342;
L348:
now
per cases  by L346 , L344 , XBOOLE_0:def 3;
suppose L349: C58 in [: { C59 } , C52 :];

L350: [ R14 , R15 ] in [: { C59 } , C52 :] by L349 , L338 , L345 , TARSKI:def 1;
L351: R14 in { C59 } by L350 , ZFMISC_1:87;
L352: R14 = C59 by L351 , TARSKI:def 1;
L353: C57 in D22 by L352 , L346 , TARSKI:def 1;
thus L354: C57 in ( D22 \/ D21 ) by L353 , XBOOLE_0:def 3;
end;
suppose L355: C58 in [: C52 , { C59 } :];

L356: [ R14 , R15 ] in [: C52 , { C59 } :] by L355 , L338 , L345 , TARSKI:def 1;
L357: R15 in { C59 } by L356 , ZFMISC_1:87;
L358: R15 = C59 by L357 , TARSKI:def 1;
L359: C57 in D21 by L358 , L346 , TARSKI:def 1;
thus L360: C57 in ( D22 \/ D21 ) by L359 , XBOOLE_0:def 3;
end;
end;
thus L362: thesis by L348 , L341;
end;
L363: (C55 in D20 & D20 is  open) by PRE_TOPC:def 2 , ZFMISC_1:31;
thus L364: thesis by L363 , L339;
end;
thus L365: D18 is  locally_finite by L335 , PCOMPS_1:def 1;
L366: (not D18 is  sigma_discrete)
proof
consider C60 being set such that L367: C60 in C52 by XBOOLE_0:def 1;
reconsider D24 = C60 as (Element of C52) by L367;
set D25 = ( [: { D24 } , C52 :] \/ [: C52 , { D24 } :] );
L368: ( card C52 ) c= ( card D18 )
proof
deffunc H1(set) = ( [: { $1 } , C52 :] \/ [: C52 , { $1 } :] );
consider C61 being Function such that L369: (( dom C61 ) = C52 & (for B35 being set holds (B35 in C52 implies ( C61 . B35 ) = H1(B35)))) from FUNCT_1:sch 3;
L370: (for B36 , B37 being set holds ((B36 in ( dom C61 ) & B37 in ( dom C61 ) & ( C61 . B36 ) = ( C61 . B37 )) implies B36 = B37))
proof
let C62 , C63 being set;
assume that
L371: C62 in ( dom C61 )
and
L372: C63 in ( dom C61 )
and
L373: ( C61 . C62 ) = ( C61 . C63 );
L374: C62 in { C62 } by ZFMISC_1:31;
L375: [ C62 , C62 ] in [: { C62 } , C52 :] by L374 , L369 , L371 , ZFMISC_1:87;
L376: (H1(C62) = ( C61 . C62 ) & H1(C63) = ( C61 . C63 )) by L369 , L371 , L372;
L377: [ C62 , C62 ] in ( [: { C63 } , C52 :] \/ [: C52 , { C63 } :] ) by L376 , L373 , L375 , XBOOLE_0:def 3;
L378: ([ C62 , C62 ] in [: { C63 } , C52 :] or [ C62 , C62 ] in [: C52 , { C63 } :]) by L377 , XBOOLE_0:def 3;
L379: C62 in { C63 } by L378 , ZFMISC_1:87;
assume L380: C62 <> C63;
thus L381: thesis by L380 , L379 , TARSKI:def 1;
end;
L382: C61 is  one-to-one by L370 , FUNCT_1:def 4;
L383: ( rng C61 ) c= D18
proof
let C64 being set;
assume L384: C64 in ( rng C61 );
consider C65 being set such that L385: C65 in ( dom C61 ) and L386: C64 = ( C61 . C65 ) by L384 , FUNCT_1:def 3;
reconsider D26 = C65 as (Element of C52) by L369 , L385;
L387: C64 = ( [: { D26 } , C52 :] \/ [: C52 , { D26 } :] ) by L369 , L386;
thus L388: thesis by L387;
end;
thus L389: thesis by L383 , L369 , L382 , CARD_1:10;
end;
assume L390: D18 is  sigma_discrete;
consider C66 being  sigma_discrete (FamilySequence of D16) such that L391: D18 = ( Union C66 ) by L390 , L317;
defpred S1[ set , set ] means (($2 in ( C66 . $1 ) & ( C66 . $1 ) is non  empty) or ($2 = D25 & ( C66 . $1 ) is  empty));
L392: (for B38 being set holds (B38 in ( NAT ) implies (ex B39 being set st (B39 in D18 & S1[ B38 , B39 ]))))
proof
let C67 being set;
assume L393: C67 in ( NAT );
reconsider D27 = C67 as (Element of ( NAT )) by L393;
L394:
now
per cases ;
suppose L395: ( C66 . D27 ) is  empty;

L396: D25 in D18;
thus L397: (ex B40 being set st (B40 in D18 & S1[ D27 , B40 ])) by L396 , L395;
end;
suppose L398: ( C66 . D27 ) is non  empty;

consider C68 being set such that L399: C68 in ( C66 . D27 ) by L398 , XBOOLE_0:def 1;
L400: C68 in D18 by L391 , L399 , PROB_1:12;
thus L401: (ex B41 being set st (B41 in D18 & S1[ D27 , B41 ])) by L400 , L399;
end;
end;
thus L403: thesis by L394;
end;
consider C69 being (Function of ( NAT ) , D18) such that L404: (for B42 being set holds (B42 in ( NAT ) implies S1[ B42 , ( C69 . B42 ) ])) from FUNCT_2:sch 1(L392);
L405: (for B43 being (Element of ( NAT )) holds (for B44 , B45 being (Element of D18) holds ((S1[ B43 , B44 ] & S1[ B43 , B45 ]) implies B44 = B45)))
proof
let C70 being (Element of ( NAT ));
let C71 , C72 being (Element of D18);
assume that
L406: S1[ C70 , C71 ]
and
L407: S1[ C70 , C72 ];
L408:
now
L409: ( C66 . C70 ) is  discrete by L305;
L410: C72 in D18 by L391 , L407 , PROB_1:12;
consider C73 being (Element of C52) such that L411: C72 = ( [: { C73 } , C52 :] \/ [: C52 , { C73 } :] ) and L412: C73 in C52 by L410;
L413: C71 in D18 by L391 , L406 , PROB_1:12;
consider C74 being (Element of C52) such that L414: C71 = ( [: { C74 } , C52 :] \/ [: C52 , { C74 } :] ) and L415: C74 in C52 by L413;
L416: C73 in { C73 } by TARSKI:def 1;
L417: [ C74 , C73 ] in [: C52 , { C73 } :] by L416 , ZFMISC_1:87;
L418: [ C74 , C73 ] in C72 by L417 , L411 , XBOOLE_0:def 3;
L419: C74 in { C74 } by TARSKI:def 1;
L420: [ C74 , C73 ] in [: { C74 } , C52 :] by L419 , ZFMISC_1:87;
L421: [ C74 , C73 ] in C71 by L420 , L414 , XBOOLE_0:def 3;
L422: C71 meets C72 by L421 , L418 , XBOOLE_0:3;
thus L423: thesis by L422 , L406 , L407 , L409 , L101;
end;
thus L424: thesis by L408;
end;
L425: D18 c= ( C69 .: ( NAT ) )
proof
let C75 being set;
assume L426: C75 in D18;
consider C76 being (Element of ( NAT )) such that L427: C75 in ( C66 . C76 ) by L426 , L391 , PROB_1:12;
L428: S1[ C76 , ( C69 . C76 ) ] by L404;
L429: C75 = ( C69 . C76 ) by L428 , L405 , L426 , L427;
L430: ( dom C69 ) = ( NAT ) by L426 , FUNCT_2:def 1;
thus L431: thesis by L430 , L429 , FUNCT_1:def 6;
end;
L432: (not ( card C52 ) c= ( omega )) by CARD_3:def 14;
L433: ( card ( NAT ) ) in ( card C52 ) by L432 , CARD_1:4 , CARD_1:47;
L434: ( card ( NAT ) ) c= ( card D18 ) by L433 , L368 , CARD_1:3;
L435: ( card ( NAT ) ) c< ( card D18 ) by L434 , L368 , L432 , CARD_1:47 , XBOOLE_0:def 8;
L436: ( card ( C69 .: ( NAT ) ) ) c< ( card D18 ) by L435 , CARD_1:67 , XBOOLE_1:59;
L437: ( card ( C69 .: ( NAT ) ) ) c= ( card D18 ) by L436 , XBOOLE_0:def 8;
L438: ( card ( C69 .: ( NAT ) ) ) in ( card D18 ) by L437 , L436 , CARD_1:3;
L439: ( D18 \ ( C69 .: ( NAT ) ) ) <> ( {} ) by L438 , CARD_1:68;
thus L440: contradiction by L439 , L425 , XBOOLE_1:37;
end;
thus L441: thesis by L366;
end;
definition
let C77 being non  empty TopSpace;
let C78 being (FamilySequence of C77);
attr C78 is  Basis_sigma_discrete
means
(C78 is  sigma_discrete & ( Union C78 ) is (Basis of C77));
end;
definition
let C79 being non  empty TopSpace;
let C80 being (FamilySequence of C79);
attr C80 is  Basis_sigma_locally_finite
means
:L443: (C80 is  sigma_locally_finite & ( Union C80 ) is (Basis of C79));
end;
theorem
L445: (for B46 being  real number holds (for B47 being non  empty MetrSpace holds (for B48 being (Element of B47) holds ( ( [#] B47 ) \ ( cl_Ball (B48 , B46) ) ) in ( Family_open_set B47 ))))
proof
let C81 being  real number;
reconsider D28 = C81 as Real by XREAL_0:def 1;
let C82 being non  empty MetrSpace;
let C83 being (Element of C82);
L446:
now
let C84 being (Element of C82);
set D29 = ( ( dist (C83 , C84) ) - D28 );
L447: ( Ball (C84 , D29) ) c= ( ( [#] C82 ) \ ( cl_Ball (C83 , C81) ) )
proof
assume L448: (not ( Ball (C84 , D29) ) c= ( ( [#] C82 ) \ ( cl_Ball (C83 , C81) ) ));
consider C85 being set such that L449: C85 in ( Ball (C84 , D29) ) and L450: (not C85 in ( ( [#] C82 ) \ ( cl_Ball (C83 , C81) ) )) by L448 , TARSKI:def 3;
reconsider D30 = C85 as (Element of C82) by L449;
L451: (not (D30 in ( [#] C82 ) & (not D30 in ( cl_Ball (C83 , C81) )))) by L450 , XBOOLE_0:def 5;
L452: ( dist (C83 , D30) ) <= D28 by L451 , METRIC_1:12;
L453: ( dist (C84 , D30) ) < D29 by L449 , METRIC_1:11;
L454: ( ( dist (C84 , D30) ) + ( dist (C83 , D30) ) ) < ( D29 + D28 ) by L453 , L452 , XREAL_1:8;
L455: ( ( dist (C83 , D30) ) + ( dist (D30 , C84) ) ) < ( D29 + D28 ) by L454;
thus L456: thesis by L455 , METRIC_1:4;
end;
assume L457: C84 in ( ( [#] C82 ) \ ( cl_Ball (C83 , C81) ) );
L458: (not C84 in ( cl_Ball (C83 , C81) )) by L457 , XBOOLE_0:def 5;
L459: ( D28 + ( 0 ) ) < ( D28 + D29 ) by L458 , METRIC_1:12;
L460: ( D28 - D28 ) < ( D29 - ( 0 ) ) by L459 , XREAL_1:21;
thus L461: (ex R20 being Real st (R20 > ( 0 ) & ( Ball (C84 , R20) ) c= ( ( [#] C82 ) \ ( cl_Ball (C83 , C81) ) ))) by L460 , L447;
end;
thus L462: thesis by L446 , PCOMPS_1:def 4;
end;
theorem
L463: (for R1 being non  empty TopSpace holds (R1 is  metrizable implies (R1 is  regular & R1 is  T_1)))
proof
let R1 being non  empty TopSpace;
assume L464: R1 is  metrizable;
consider C86 being (Function of [: (the carrier of R1) , (the carrier of R1) :] , ( REAL )) such that L465: C86 is_metric_of (the carrier of R1) and L466: ( Family_open_set ( SpaceMetr ((the carrier of R1) , C86) ) ) = (the topology of R1) by L464 , PCOMPS_1:def 8;
set D31 = ( SpaceMetr ((the carrier of R1) , C86) );
reconsider D32 = D31 as non  empty MetrSpace by L465 , PCOMPS_1:36;
set D33 = ( TopSpaceMetr D32 );
L467: (for B49 being (Element of R1) holds (for B50 being (Subset of R1) holds ((B50 <> ( {} ) & B50 is  closed & B49 in ( B50 ` )) implies (ex B51 , B52 being (Subset of R1) st (B51 is  open & B52 is  open & B49 in B51 & B50 c= B52 & B51 misses B52)))))
proof
let C87 being (Element of R1);
let C88 being (Subset of R1);
assume that
L468: C88 <> ( {} )
and
L469: C88 is  closed
and
L470: C87 in ( C88 ` );
L471: ( ( [#] R1 ) \ C88 ) in (the topology of R1) by L469 , L470 , PRE_TOPC:def 2;
reconsider D34 = C87 as (Element of D32) by L465 , PCOMPS_2:4;
L472: C88 misses ( C88 ` ) by XBOOLE_1:79;
reconsider D35 = C88 as (Subset of D33) by L465 , PCOMPS_2:4;
L473: ( ( [#] D33 ) \ D35 ) in ( Family_open_set D32 ) by L465 , L466 , L471 , PCOMPS_2:4;
L474: ( ( [#] D33 ) \ D35 ) is  open by L473 , PRE_TOPC:def 2;
L475: D35 is  closed by L474 , PRE_TOPC:def 3;
L476: (not D34 in D35) by L470 , L472 , XBOOLE_0:3;
L477: (ex R19 being Real st (R19 > ( 0 ) & ( Ball (D34 , R19) ) misses D35))
proof
assume L478: (for R19 being Real holds (R19 > ( 0 ) implies ( Ball (D34 , R19) ) meets D35));
L479:
now
let C89 being (Subset of D33);
assume that
L480: C89 is  open
and
L481: D34 in C89;
L482: C89 in ( Family_open_set D32 ) by L480 , PRE_TOPC:def 2;
consider R20 being Real such that L483: R20 > ( 0 ) and L484: ( Ball (D34 , R20) ) c= C89 by L482 , L481 , PCOMPS_1:def 4;
L485: ( Ball (D34 , R20) ) meets D35 by L478 , L483;
L486: (ex R14 being set st (R14 in ( Ball (D34 , R20) ) & R14 in D35)) by L485 , XBOOLE_0:3;
thus L487: C89 meets D35 by L486 , L484 , XBOOLE_0:3;
end;
L488: D34 in ( Cl D35 ) by L479 , PRE_TOPC:def 7;
thus L489: thesis by L488 , L475 , L476 , PRE_TOPC:22;
end;
consider R19 being Real such that L490: R19 > ( 0 ) and L491: ( Ball (D34 , R19) ) misses D35 by L477;
set D36 = ( R19 / 2 );
L492: D36 < ( D36 + D36 ) by L490 , XREAL_1:29;
L493: D35 c= ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) )
proof
assume L494: (not D35 c= ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) ));
consider R14 being set such that L495: R14 in D35 and L496: (not R14 in ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) )) by L494 , TARSKI:def 3;
reconsider D37 = R14 as (Element of D32) by L495;
L497: D37 in ( cl_Ball (D34 , D36) ) by L496 , XBOOLE_0:def 5;
L498: ( dist (D34 , D37) ) <= D36 by L497 , METRIC_1:12;
L499: ( dist (D34 , D37) ) < R19 by L498 , L492 , XXREAL_0:2;
L500: D37 in ( Ball (D34 , R19) ) by L499 , METRIC_1:11;
thus L501: thesis by L500 , L491 , L495 , XBOOLE_0:3;
end;
set D38 = ( D36 / 2 );
L502: D36 > ( 0 ) by L490 , XREAL_1:139;
L503: D38 < ( D38 + D38 ) by L502 , XREAL_1:29;
L504: ( Ball (D34 , D38) ) misses ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) )
proof
assume L505: ( Ball (D34 , D38) ) meets ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) );
consider R14 being set such that L506: R14 in ( Ball (D34 , D38) ) and L507: R14 in ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) ) by L505 , XBOOLE_0:3;
reconsider D39 = R14 as (Element of D32) by L506;
L508: (not D39 in ( cl_Ball (D34 , D36) )) by L507 , XBOOLE_0:def 5;
L509: ( dist (D34 , D39) ) > D36 by L508 , METRIC_1:12;
L510: ( dist (D34 , D39) ) < D38 by L506 , METRIC_1:11;
thus L511: thesis by L510 , L503 , L509 , XXREAL_0:2;
end;
set D40 = ( Ball (D34 , D38) );
set D41 = ( ( [#] D32 ) \ ( cl_Ball (D34 , D36) ) );
L512: (D41 in ( Family_open_set D32 ) & D40 in ( Family_open_set D32 )) by L445 , PCOMPS_1:29;
reconsider D42 = D40 , D43 = D41 as (Subset of R1) by L512 , L466;
take D42;
take D43;
L513: D38 > ( 0 ) by L502 , XREAL_1:139;
L514: ( dist (D34 , D34) ) < D38 by L513 , METRIC_1:1;
thus L515: thesis by L514 , L466 , L493 , L504 , L512 , METRIC_1:11 , PRE_TOPC:def 2;
end;
L516: (for B53 , B54 being (Point of R1) holds ((not B53 = B54) implies (ex B55 , B56 being (Subset of R1) st (B55 is  open & B56 is  open & B53 in B55 & (not B54 in B55) & B54 in B56 & (not B53 in B56)))))
proof
let C90 , C91 being (Point of R1);
assume L517: (not C90 = C91);
reconsider D44 = C90 , D45 = C91 as (Element of D33) by L465 , PCOMPS_2:4;
L518: D33 is  T_2 by PCOMPS_1:34;
consider C92 , C93 being (Subset of D33) such that L519: C92 is  open and L520: C93 is  open and L521: (D44 in C92 & D45 in C93) and L522: C92 misses C93 by L518 , L517 , PRE_TOPC:def 10;
reconsider D46 = C92 , D47 = C93 as (Subset of R1) by L465 , PCOMPS_2:4;
L523: D46 in (the topology of R1) by L466 , L519 , PRE_TOPC:def 2;
L524: D46 is  open by L523 , PRE_TOPC:def 2;
L525: D47 in (the topology of R1) by L466 , L520 , PRE_TOPC:def 2;
L526: D47 is  open by L525 , PRE_TOPC:def 2;
L527: ((not D45 in D46) & (not D44 in D47)) by L521 , L522 , XBOOLE_0:3;
thus L528: thesis by L527 , L521 , L524 , L526;
end;
thus L529: thesis by L516 , L467 , COMPTS_1:def 2 , URYSOHN1:def 7;
end;
theorem
L530: (for R1 being non  empty TopSpace holds (R1 is  metrizable implies (ex B57 being (FamilySequence of R1) st B57 is  Basis_sigma_locally_finite)))
proof
let R1 being non  empty TopSpace;
assume L531: R1 is  metrizable;
consider C94 being (Function of [: (the carrier of R1) , (the carrier of R1) :] , ( REAL )) such that L532: C94 is_metric_of (the carrier of R1) and L533: ( Family_open_set ( SpaceMetr ((the carrier of R1) , C94) ) ) = (the topology of R1) by L531 , PCOMPS_1:def 8;
set D48 = ( SpaceMetr ((the carrier of R1) , C94) );
reconsider D49 = D48 as non  empty MetrSpace by L532 , PCOMPS_1:36;
deffunc H2((Element of ( NAT ))) = { ( Ball (B58 , ( 1 / ( 2 |^ $1 ) )) ) where B58 is (Element of D49) : B58 is (Element of D49) };
defpred S2[ (Element of ( NAT )) , set ] means $2 = H2($1);
L534: (for B59 being (Element of ( NAT )) holds (ex B60 being (Subset-Family of R1) st S2[ B59 , B60 ]))
proof
let C95 being (Element of ( NAT ));
set D50 = H2(C95);
L535: D50 c= ( bool (the carrier of R1) )
proof
let C96 being set;
assume L536: C96 in D50;
L537: (ex B61 being (Element of D49) st (C96 = ( Ball (B61 , ( 1 / ( 2 |^ C95 ) )) ) & B61 is (Element of D49))) by L536;
L538: C96 in ( Family_open_set D49 ) by L537 , PCOMPS_1:29;
thus L539: thesis by L538 , L533;
end;
thus L540: thesis by L535;
end;
consider C97 being (Function of ( NAT ) , ( bool ( bool (the carrier of R1) ) )) such that L541: (for B62 being (Element of ( NAT )) holds S2[ B62 , ( C97 . B62 ) ]) from FUNCT_2:sch 3(L534);
defpred S3[ set , set ] means (ex B63 being (Subset-Family of R1) st (B63 = $2 & B63 is  open & B63 is (Cover of R1) & B63 is_finer_than ( C97 . $1 ) & B63 is  locally_finite));
set D51 = ( TopSpaceMetr D49 );
L542: ( [#] R1 ) = ( [#] D51 ) by L532 , PCOMPS_2:4;
L543: (for R21 being (Element of ( NAT )) holds (ex B64 being (Subset-Family of R1) st (B64 is_finer_than ( C97 . R21 ) & B64 is (Cover of R1) & B64 is  open & B64 is  locally_finite)))
proof
let R21 being (Element of ( NAT ));
L544: ( [#] D51 ) c= ( union ( C97 . R21 ) )
proof
let R14 being set;
assume L545: R14 in ( [#] D51 );
reconsider D52 = R14 as (Element of D49) by L545;
L546: (( dist (D52 , D52) ) = ( 0 ) & ( 2 |^ R21 ) > ( 0 )) by METRIC_1:1 , NEWTON:83;
L547: ( dist (D52 , D52) ) < ( 1 / ( 2 |^ R21 ) ) by L546 , XREAL_1:139;
L548: D52 in ( Ball (D52 , ( 1 / ( 2 |^ R21 ) )) ) by L547 , METRIC_1:11;
L549: ( Ball (D52 , ( 1 / ( 2 |^ R21 ) )) ) in H2(R21);
L550: ( Ball (D52 , ( 1 / ( 2 |^ R21 ) )) ) in ( C97 . R21 ) by L549 , L541;
thus L551: thesis by L550 , L548 , TARSKI:def 4;
end;
L552: ( C97 . R21 ) is (Cover of R1) by L544 , L542 , SETFAM_1:def 11;
L553: (for B65 being (Subset of R1) holds (B65 in ( C97 . R21 ) implies B65 is  open))
proof
let C98 being (Subset of R1);
assume L554: C98 in ( C97 . R21 );
L555: C98 in H2(R21) by L554 , L541;
L556: (ex B66 being (Element of D49) st (C98 = ( Ball (B66 , ( 1 / ( 2 |^ R21 ) )) ) & B66 is (Element of D49))) by L555;
L557: C98 in (the topology of R1) by L556 , L533 , PCOMPS_1:29;
thus L558: thesis by L557 , PRE_TOPC:def 2;
end;
L559: ( C97 . R21 ) is  open by L553 , TOPS_2:def 1;
L560: (ex B67 being (Subset-Family of R1) st (B67 is  open & B67 is (Cover of R1) & B67 is_finer_than ( C97 . R21 ) & B67 is  locally_finite)) by L559 , L531 , L552 , PCOMPS_2:6;
thus L561: thesis by L560;
end;
L562: (for B68 being set holds (B68 in ( NAT ) implies (ex R15 being set st (R15 in ( bool ( bool (the carrier of R1) ) ) & S3[ B68 , R15 ]))))
proof
let C99 being set;
assume L563: C99 in ( NAT );
reconsider D53 = C99 as (Element of ( NAT )) by L563;
L564: (ex B69 being (Subset-Family of R1) st (B69 is_finer_than ( C97 . D53 ) & B69 is (Cover of R1) & B69 is  open & B69 is  locally_finite)) by L543;
thus L565: thesis by L564;
end;
consider C100 being (FamilySequence of R1) such that L566: (for R14 being set holds (R14 in ( NAT ) implies S3[ R14 , ( C100 . R14 ) ])) from FUNCT_2:sch 1(L562);
L567: (for B70 being (Subset of R1) holds (B70 is  open implies (for B71 being (Point of R1) holds (B71 in B70 implies (ex B72 being (Subset of R1) st (B72 in ( Union C100 ) & B71 in B72 & B72 c= B70))))))
proof
let R6 being (Subset of R1);
assume L568: R6 is  open;
L569: R6 in ( Family_open_set D49 ) by L568 , L533 , PRE_TOPC:def 2;
let R12 being (Point of R1);
assume L570: R12 in R6;
reconsider D54 = R12 as (Element of D49) by L570 , L569;
consider R19 being Real such that L571: R19 > ( 0 ) and L572: ( Ball (D54 , R19) ) c= R6 by L570 , L569 , PCOMPS_1:def 4;
consider R21 being (Element of ( NAT )) such that L573: ( 1 / ( 2 |^ R21 ) ) <= R19 by L571 , PREPOWER:92;
L574: S3[ ( R21 + 1 ) , ( C100 . ( R21 + 1 ) ) ] by L566;
L575: ( union ( C100 . ( R21 + 1 ) ) ) = (the carrier of R1) by L574 , SETFAM_1:45;
consider C101 being set such that L576: D54 in C101 and L577: C101 in ( C100 . ( R21 + 1 ) ) by L575 , TARSKI:def 4;
reconsider D55 = C101 as (Subset of D49) by L532 , L577 , PCOMPS_2:4;
consider C102 being set such that L578: C102 in ( C97 . ( R21 + 1 ) ) and L579: D55 c= C102 by L574 , L577 , SETFAM_1:def 2;
L580: C102 in H2(( R21 + 1 )) by L541 , L578;
consider C103 being (Element of D49) such that L581: C102 = ( Ball (C103 , ( 1 / ( 2 |^ ( R21 + 1 ) ) )) ) and L582: C103 is (Element of D49) by L580;
L583: ( dist (C103 , D54) ) < ( 1 / ( 2 |^ ( R21 + 1 ) ) ) by L576 , L579 , L581 , METRIC_1:11;
L584:
now
let C104 being (Element of D49);
assume L585: C104 in D55;
L586: ( dist (C103 , C104) ) < ( 1 / ( 2 |^ ( R21 + 1 ) ) ) by L585 , L579 , L581 , METRIC_1:11;
L587: (( dist (D54 , C104) ) <= ( ( dist (C103 , D54) ) + ( dist (C103 , C104) ) ) & ( ( dist (C103 , D54) ) + ( dist (C103 , C104) ) ) < ( ( 1 / ( 2 |^ ( R21 + 1 ) ) ) + ( 1 / ( 2 |^ ( R21 + 1 ) ) ) )) by L586 , L583 , METRIC_1:4 , XREAL_1:8;
L588: ( dist (D54 , C104) ) < ( 2 * ( 1 / ( 2 |^ ( R21 + 1 ) ) ) ) by L587 , XXREAL_0:2;
L589: ( dist (D54 , C104) ) < ( ( 1 / ( ( 2 |^ R21 ) * 2 ) ) * 2 ) by L588 , NEWTON:6;
L590: ( dist (D54 , C104) ) < ( 1 / ( 2 |^ R21 ) ) by L589 , XCMPLX_1:92;
L591: ( dist (D54 , C104) ) < R19 by L590 , L573 , XXREAL_0:2;
thus L592: C104 in ( Ball (D54 , R19) ) by L591 , METRIC_1:11;
end;
L593: D55 c= ( Ball (D54 , R19) ) by L584 , SUBSET_1:2;
L594: D55 in ( Union C100 ) by L577 , PROB_1:12;
thus L595: thesis by L594 , L572 , L576 , L593 , XBOOLE_1:1;
end;
L596: (for R21 being (Element of ( NAT )) holds ( C100 . R21 ) is  locally_finite)
proof
let R21 being (Element of ( NAT ));
L597: S3[ R21 , ( C100 . R21 ) ] by L566;
thus L598: thesis by L597;
end;
L599: C100 is  sigma_locally_finite by L596 , L315;
L600: ( Union C100 ) c= (the topology of R1)
proof
let C105 being set;
assume L601: C105 in ( Union C100 );
consider C106 being (Element of ( NAT )) such that L602: C105 in ( C100 . C106 ) by L601 , PROB_1:12;
reconsider D56 = C105 as (Subset of R1) by L602;
L603: S3[ C106 , ( C100 . C106 ) ] by L566;
L604: D56 is  open by L603 , L602 , TOPS_2:def 1;
thus L605: thesis by L604 , PRE_TOPC:def 2;
end;
L606: ( Union C100 ) is (Basis of R1) by L600 , L567 , YELLOW_9:32;
L607: C100 is  Basis_sigma_locally_finite by L606 , L599 , L443;
thus L608: thesis by L607;
end;
L609: (for R1 being non  empty TopSpace holds (for R11 being  open (Subset of R1) holds (for R6 being (Subset of R1) holds (R6 is  closed implies ( R11 \ R6 ) is  open))))
proof
let R1 being non  empty TopSpace;
let R11 being  open (Subset of R1);
let R6 being (Subset of R1);
L610: ( R11 /\ ( ( [#] R1 ) \ R6 ) ) = ( R11 /\ ( R6 ` ) );
assume L611: R6 is  closed;
thus L612: thesis by L611 , L610 , SUBSET_1:13;
end;
theorem
L613: (for R1 being non  empty TopSpace holds (for B73 being (Function of ( NAT ) , ( bool (the carrier of R1) )) holds ((for R21 being (Element of ( NAT )) holds ( B73 . R21 ) is  open) implies ( Union B73 ) is  open)))
proof
let R1 being non  empty TopSpace;
let C107 being (Function of ( NAT ) , ( bool (the carrier of R1) ));
assume L614: (for R21 being (Element of ( NAT )) holds ( C107 . R21 ) is  open);
L615: ( rng C107 ) c= (the topology of R1)
proof
let C108 being set;
assume L616: C108 in ( rng C107 );
consider C109 being set such that L617: C109 in ( dom C107 ) and L618: C108 = ( C107 . C109 ) by L616 , FUNCT_1:def 3;
reconsider D57 = C109 as (Element of ( NAT )) by L617;
L619: ( C107 . D57 ) is  open by L614;
thus L620: thesis by L619 , L618 , PRE_TOPC:def 2;
end;
L621: ( union ( rng C107 ) ) in (the topology of R1) by L615 , PRE_TOPC:def 1;
L622: ( Union C107 ) in (the topology of R1) by L621 , CARD_3:def 4;
thus L623: thesis by L622 , PRE_TOPC:def 2;
end;
theorem
L624: (for R1 being non  empty TopSpace holds ((for R6 being (Subset of R1) holds (for R11 being  open (Subset of R1) holds ((R6 is  closed & R11 is  open & R6 c= R11) implies (ex B74 being (Function of ( NAT ) , ( bool (the carrier of R1) )) st (R6 c= ( Union B74 ) & ( Union B74 ) c= R11 & (for R21 being (Element of ( NAT )) holds (( Cl ( B74 . R21 ) ) c= R11 & ( B74 . R21 ) is  open))))))) implies R1 is  normal))
proof
let R1 being non  empty TopSpace;
assume L625: (for R6 being (Subset of R1) holds (for R11 being  open (Subset of R1) holds ((R6 is  closed & R11 is  open & R6 c= R11) implies (ex B75 being (Function of ( NAT ) , ( bool (the carrier of R1) )) st (R6 c= ( Union B75 ) & ( Union B75 ) c= R11 & (for R21 being (Element of ( NAT )) holds (( Cl ( B75 . R21 ) ) c= R11 & ( B75 . R21 ) is  open)))))));
L626: (for B76 , B77 being (Subset of R1) holds ((B76 <> ( {} ) & B77 <> ( {} ) & B76 is  closed & B77 is  closed & B76 misses B77) implies (ex B78 , B79 being (Subset of R1) st (B78 is  open & B79 is  open & B76 c= B78 & B77 c= B79 & B78 misses B79))))
proof
let C110 , C111 being (Subset of R1);
assume that
L627: C110 <> ( {} )
and
L628: C111 <> ( {} )
and
L629: (C110 is  closed & C111 is  closed)
and
L630: C110 misses C111;
set D58 = ( ( [#] R1 ) \ C111 );
L631: C110 c= ( C111 ` ) by L630 , SUBSET_1:23;
consider C112 being (Function of ( NAT ) , ( bool (the carrier of R1) )) such that L632: C110 c= ( Union C112 ) and L633: ( Union C112 ) c= D58 and L634: (for R21 being (Element of ( NAT )) holds (( Cl ( C112 . R21 ) ) c= D58 & ( C112 . R21 ) is  open)) by L631 , L625 , L629;
set D59 = ( ( [#] R1 ) \ C110 );
L635: C111 c= ( C110 ` ) by L630 , SUBSET_1:23;
consider C113 being (Function of ( NAT ) , ( bool (the carrier of R1) )) such that L636: C111 c= ( Union C113 ) and L637: ( Union C113 ) c= D59 and L638: (for R21 being (Element of ( NAT )) holds (( Cl ( C113 . R21 ) ) c= D59 & ( C113 . R21 ) is  open)) by L635 , L625 , L629;
deffunc H3((Element of ( NAT ))) = ( ( C113 . $1 ) \ ( union { ( Cl ( C112 . B80 ) ) where B80 is (Element of ( NAT )) : B80 in ( ( Seg $1 ) \/ { ( 0 ) } ) } ) );
defpred S4[ (Element of ( NAT )) , set ] means $2 = H3($1);
L639: (for B81 being (Element of ( NAT )) holds (ex B82 being (Subset of R1) st S4[ B81 , B82 ]));
consider C114 being (Function of ( NAT ) , ( bool (the carrier of R1) )) such that L640: (for B83 being (Element of ( NAT )) holds S4[ B83 , ( C114 . B83 ) ]) from FUNCT_2:sch 3(L639);
L641: (for R21 being (Element of ( NAT )) holds ( C114 . R21 ) is  open)
proof
let R21 being (Element of ( NAT ));
set D60 = { ( Cl ( C112 . B84 ) ) where B84 is (Element of ( NAT )) : B84 in ( ( Seg R21 ) \/ { ( 0 ) } ) };
L642:
now
let C115 being set;
assume L643: C115 in D60;
L644: (ex B85 being (Element of ( NAT )) st (C115 = ( Cl ( C112 . B85 ) ) & B85 in ( ( Seg R21 ) \/ { ( 0 ) } ))) by L643;
thus L645: C115 in ( bool (the carrier of R1) ) by L644;
end;
reconsider D61 = D60 as (Subset-Family of R1) by L642 , TARSKI:def 3;
deffunc H4((Element of ( NAT ))) = ( Cl ( C112 . $1 ) );
L646: ( ( Seg R21 ) \/ { ( 0 ) } ) is  finite;
L647: { H4(B86) where B86 is (Element of ( NAT )) : B86 in ( ( Seg R21 ) \/ { ( 0 ) } ) } is  finite from FRAENKEL:sch 21(L646);
L648:
now
let R6 being (Subset of R1);
assume L649: R6 in D61;
L650: (ex B87 being (Element of ( NAT )) st (R6 = ( Cl ( C112 . B87 ) ) & B87 in ( ( Seg R21 ) \/ { ( 0 ) } ))) by L649;
thus L651: R6 is  closed by L650;
end;
L652: D61 is  closed by L648 , TOPS_2:def 2;
L653: ( C113 . R21 ) is  open by L638;
L654: ( ( C113 . R21 ) \ ( union D61 ) ) is  open by L653 , L647 , L652 , L609 , TOPS_2:21;
thus L655: thesis by L654 , L640;
end;
L656: ( Union C114 ) is  open by L641 , L613;
L657: (for R21 being (Element of ( NAT )) holds C111 misses ( Cl ( C112 . R21 ) ))
proof
let R21 being (Element of ( NAT ));
L658: ( Cl ( C112 . R21 ) ) c= D58 by L634;
thus L659: thesis by L658 , XBOOLE_1:63 , XBOOLE_1:79;
end;
L660:
now
let C116 being set;
assume that
L661: C116 in C111
and
L662: (not C116 in ( Union C114 ));
consider C117 being (Element of ( NAT )) such that L663: C116 in ( C113 . C117 ) by L636 , L661 , PROB_1:12;
L664: (not C116 in ( union { ( Cl ( C112 . B88 ) ) where B88 is (Element of ( NAT )) : B88 in ( ( Seg C117 ) \/ { ( 0 ) } ) } ))
proof
assume L665: C116 in ( union { ( Cl ( C112 . B89 ) ) where B89 is (Element of ( NAT )) : B89 in ( ( Seg C117 ) \/ { ( 0 ) } ) } );
consider C118 being set such that L666: C116 in C118 and L667: C118 in { ( Cl ( C112 . B90 ) ) where B90 is (Element of ( NAT )) : B90 in ( ( Seg C117 ) \/ { ( 0 ) } ) } by L665 , TARSKI:def 4;
consider C119 being (Element of ( NAT )) such that L668: C118 = ( Cl ( C112 . C119 ) ) and L669: C119 in ( ( Seg C117 ) \/ { ( 0 ) } ) by L667;
L670: C111 meets ( Cl ( C112 . C119 ) ) by L661 , L666 , L668 , XBOOLE_0:3;
thus L671: contradiction by L670 , L657;
end;
L672: C116 in H3(C117) by L664 , L663 , XBOOLE_0:def 5;
L673: C116 in ( C114 . C117 ) by L672 , L640;
thus L674: contradiction by L673 , L662 , PROB_1:12;
end;
L675: C111 c= ( Union C114 ) by L660 , TARSKI:def 3;
deffunc H5((Element of ( NAT ))) = ( ( C112 . $1 ) \ ( union { ( Cl ( C113 . B91 ) ) where B91 is (Element of ( NAT )) : B91 in ( ( Seg $1 ) \/ { ( 0 ) } ) } ) );
defpred S5[ (Element of ( NAT )) , set ] means $2 = H5($1);
L676: (for B92 being (Element of ( NAT )) holds (ex B93 being (Subset of R1) st S5[ B92 , B93 ]));
consider C120 being (Function of ( NAT ) , ( bool (the carrier of R1) )) such that L677: (for B94 being (Element of ( NAT )) holds S5[ B94 , ( C120 . B94 ) ]) from FUNCT_2:sch 3(L676);
L678: ( Union C114 ) misses ( Union C120 )
proof
assume L679: ( Union C114 ) meets ( Union C120 );
consider C121 being set such that L680: C121 in ( Union C114 ) and L681: C121 in ( Union C120 ) by L679 , XBOOLE_0:3;
consider C122 being (Element of ( NAT )) such that L682: C121 in ( C114 . C122 ) by L680 , PROB_1:12;
consider C123 being (Element of ( NAT )) such that L683: C121 in ( C120 . C123 ) by L681 , PROB_1:12;
L684: (C122 >= C123 implies ( C114 . C122 ) misses ( C120 . C123 ))
proof
assume that
L685: C122 >= C123
and
L686: ( C114 . C122 ) meets ( C120 . C123 );
consider C124 being set such that L687: C124 in ( C114 . C122 ) and L688: C124 in ( C120 . C123 ) by L686 , XBOOLE_0:3;
L689: C124 in ( ( C112 . C123 ) \ ( union { ( Cl ( C113 . B95 ) ) where B95 is (Element of ( NAT )) : B95 in ( ( Seg C123 ) \/ { ( 0 ) } ) } ) ) by L677 , L688;
L690: C124 in ( C112 . C123 ) by L689 , XBOOLE_0:def 5;
L691: (C123 = ( 0 ) or C123 in ( Seg C123 )) by FINSEQ_1:3;
L692: (C123 in { ( 0 ) } or (C123 in ( Seg C123 ) & ( Seg C123 ) c= ( Seg C122 ))) by L691 , L685 , FINSEQ_1:5 , TARSKI:def 1;
L693: C123 in ( ( Seg C122 ) \/ { ( 0 ) } ) by L692 , XBOOLE_0:def 3;
L694: (( C112 . C123 ) c= ( Cl ( C112 . C123 ) ) & ( Cl ( C112 . C123 ) ) in { ( Cl ( C112 . B96 ) ) where B96 is (Element of ( NAT )) : B96 in ( ( Seg C122 ) \/ { ( 0 ) } ) }) by L693 , PRE_TOPC:18;
L695: C124 in ( ( C113 . C122 ) \ ( union { ( Cl ( C112 . B97 ) ) where B97 is (Element of ( NAT )) : B97 in ( ( Seg C122 ) \/ { ( 0 ) } ) } ) ) by L640 , L687;
L696: (not C124 in ( union { ( Cl ( C112 . B98 ) ) where B98 is (Element of ( NAT )) : B98 in ( ( Seg C122 ) \/ { ( 0 ) } ) } )) by L695 , XBOOLE_0:def 5;
thus L697: contradiction by L696 , L690 , L694 , TARSKI:def 4;
end;
L698: (C122 <= C123 implies ( C114 . C122 ) misses ( C120 . C123 ))
proof
assume that
L699: C122 <= C123
and
L700: ( C114 . C122 ) meets ( C120 . C123 );
consider C125 being set such that L701: C125 in ( C114 . C122 ) and L702: C125 in ( C120 . C123 ) by L700 , XBOOLE_0:3;
L703: C125 in ( ( C113 . C122 ) \ ( union { ( Cl ( C112 . B99 ) ) where B99 is (Element of ( NAT )) : B99 in ( ( Seg C122 ) \/ { ( 0 ) } ) } ) ) by L640 , L701;
L704: C125 in ( C113 . C122 ) by L703 , XBOOLE_0:def 5;
L705: (C122 = ( 0 ) or C122 in ( Seg C122 )) by FINSEQ_1:3;
L706: (C122 in { ( 0 ) } or (C122 in ( Seg C122 ) & ( Seg C122 ) c= ( Seg C123 ))) by L705 , L699 , FINSEQ_1:5 , TARSKI:def 1;
L707: C122 in ( ( Seg C123 ) \/ { ( 0 ) } ) by L706 , XBOOLE_0:def 3;
L708: (( C113 . C122 ) c= ( Cl ( C113 . C122 ) ) & ( Cl ( C113 . C122 ) ) in { ( Cl ( C113 . B100 ) ) where B100 is (Element of ( NAT )) : B100 in ( ( Seg C123 ) \/ { ( 0 ) } ) }) by L707 , PRE_TOPC:18;
L709: C125 in ( ( C112 . C123 ) \ ( union { ( Cl ( C113 . B101 ) ) where B101 is (Element of ( NAT )) : B101 in ( ( Seg C123 ) \/ { ( 0 ) } ) } ) ) by L677 , L702;
L710: (not C125 in ( union { ( Cl ( C113 . B102 ) ) where B102 is (Element of ( NAT )) : B102 in ( ( Seg C123 ) \/ { ( 0 ) } ) } )) by L709 , XBOOLE_0:def 5;
thus L711: contradiction by L710 , L704 , L708 , TARSKI:def 4;
end;
thus L712: contradiction by L698 , L682 , L683 , L684 , XBOOLE_0:3;
end;
L713: (for R21 being (Element of ( NAT )) holds ( C120 . R21 ) is  open)
proof
let R21 being (Element of ( NAT ));
set D62 = { ( Cl ( C113 . B103 ) ) where B103 is (Element of ( NAT )) : B103 in ( ( Seg R21 ) \/ { ( 0 ) } ) };
L714:
now
let C126 being set;
assume L715: C126 in D62;
L716: (ex B104 being (Element of ( NAT )) st (C126 = ( Cl ( C113 . B104 ) ) & B104 in ( ( Seg R21 ) \/ { ( 0 ) } ))) by L715;
thus L717: C126 in ( bool (the carrier of R1) ) by L716;
end;
reconsider D63 = D62 as (Subset-Family of R1) by L714 , TARSKI:def 3;
deffunc H6((Element of ( NAT ))) = ( Cl ( C113 . $1 ) );
L718: ( ( Seg R21 ) \/ { ( 0 ) } ) is  finite;
L719: { H6(B105) where B105 is (Element of ( NAT )) : B105 in ( ( Seg R21 ) \/ { ( 0 ) } ) } is  finite from FRAENKEL:sch 21(L718);
L720:
now
let R6 being (Subset of R1);
assume L721: R6 in D63;
L722: (ex B106 being (Element of ( NAT )) st (R6 = ( Cl ( C113 . B106 ) ) & B106 in ( ( Seg R21 ) \/ { ( 0 ) } ))) by L721;
thus L723: R6 is  closed by L722;
end;
L724: D63 is  closed by L720 , TOPS_2:def 2;
L725: ( C112 . R21 ) is  open by L634;
L726: ( ( C112 . R21 ) \ ( union D63 ) ) is  open by L725 , L719 , L724 , L609 , TOPS_2:21;
thus L727: thesis by L726 , L677;
end;
L728: ( Union C120 ) is  open by L713 , L613;
L729: (for R21 being (Element of ( NAT )) holds C110 misses ( Cl ( C113 . R21 ) ))
proof
let R21 being (Element of ( NAT ));
L730: ( Cl ( C113 . R21 ) ) c= D59 by L638;
thus L731: thesis by L730 , XBOOLE_1:63 , XBOOLE_1:79;
end;
L732:
now
let C127 being set;
assume that
L733: C127 in C110
and
L734: (not C127 in ( Union C120 ));
consider C128 being (Element of ( NAT )) such that L735: C127 in ( C112 . C128 ) by L632 , L733 , PROB_1:12;
L736: (not C127 in ( union { ( Cl ( C113 . B107 ) ) where B107 is (Element of ( NAT )) : B107 in ( ( Seg C128 ) \/ { ( 0 ) } ) } ))
proof
assume L737: C127 in ( union { ( Cl ( C113 . B108 ) ) where B108 is (Element of ( NAT )) : B108 in ( ( Seg C128 ) \/ { ( 0 ) } ) } );
consider C129 being set such that L738: C127 in C129 and L739: C129 in { ( Cl ( C113 . B109 ) ) where B109 is (Element of ( NAT )) : B109 in ( ( Seg C128 ) \/ { ( 0 ) } ) } by L737 , TARSKI:def 4;
consider C130 being (Element of ( NAT )) such that L740: C129 = ( Cl ( C113 . C130 ) ) and L741: C130 in ( ( Seg C128 ) \/ { ( 0 ) } ) by L739;
L742: C110 meets ( Cl ( C113 . C130 ) ) by L733 , L738 , L740 , XBOOLE_0:3;
thus L743: contradiction by L742 , L729;
end;
L744: C127 in H5(C128) by L736 , L735 , XBOOLE_0:def 5;
L745: C127 in ( C120 . C128 ) by L744 , L677;
thus L746: contradiction by L745 , L734 , PROB_1:12;
end;
L747: C110 c= ( Union C120 ) by L732 , TARSKI:def 3;
thus L748: thesis by L747 , L675 , L678 , L656 , L728;
end;
thus L749: thesis by L626 , COMPTS_1:def 3;
end;
theorem
L750: (for R1 being non  empty TopSpace holds (R1 is  regular implies (for B110 being (FamilySequence of R1) holds (( Union B110 ) is (Basis of R1) implies (for B111 being (Subset of R1) holds (for B112 being (Point of R1) holds ((B111 is  open & B112 in B111) implies (ex B113 being (Subset of R1) st (B112 in B113 & ( Cl B113 ) c= B111 & B113 in ( Union B110 ))))))))))
proof
let R1 being non  empty TopSpace;
assume L751: R1 is  regular;
let C131 being (FamilySequence of R1);
assume L752: ( Union C131 ) is (Basis of R1);
L753: (for R11 being  open (Subset of R1) holds (for R12 being (Point of R1) holds ((R11 is  open & R12 in R11) implies (ex B114 being (Subset of R1) st (R12 in B114 & ( Cl B114 ) c= R11 & B114 in ( Union C131 ))))))
proof
let R11 being  open (Subset of R1);
let R12 being (Point of R1);
assume that
L754: R11 is  open
and
L755: R12 in R11;
L756:
now
per cases ;
suppose L757: R11 = (the carrier of R1);

consider C132 being (Subset of R1) such that L758: (C132 in ( Union C131 ) & R12 in C132) and L759: C132 c= R11 by L752 , L755 , YELLOW_9:31;
take D64 = C132;
L760: ( Cl D64 ) c= R11 by L757;
thus L761: thesis by L760 , L758;
end;
suppose L762: R11 <> (the carrier of R1);

L763: R11 c< (the carrier of R1) by L762 , XBOOLE_0:def 8;
L764: ( R11 ` ) <> ( {} ) by L763 , XBOOLE_1:105;
L765: R12 in ( ( R11 ` ) ` ) by L755;
consider C133 , C134 being (Subset of R1) such that L766: C133 is  open and L767: C134 is  open and L768: R12 in C133 and L769: ( R11 ` ) c= C134 and L770: C133 misses C134 by L765 , L751 , L764 , COMPTS_1:def 2;
consider C135 being (Subset of R1) such that L771: (C135 in ( Union C131 ) & R12 in C135) and L772: C135 c= C133 by L752 , L766 , L768 , YELLOW_9:31;
L773: C133 c= ( C134 ` ) by L770 , SUBSET_1:23;
L774: C135 c= ( C134 ` ) by L773 , L772 , XBOOLE_1:1;
L775: ( Cl C135 ) c= ( Cl ( C134 ` ) ) by L774 , PRE_TOPC:19;
L776: ( Cl C135 ) c= ( C134 ` ) by L775 , L767 , PRE_TOPC:22;
take D65 = C135;
L777: ( C134 ` ) c= R11 by L769 , SUBSET_1:17;
thus L778: thesis by L777 , L771 , L776 , XBOOLE_1:1;
end;
end;
thus L780: thesis by L756;
end;
thus L781: thesis by L753;
end;
theorem
L782: (for R1 being non  empty TopSpace holds ((R1 is  regular & (ex B115 being (FamilySequence of R1) st B115 is  Basis_sigma_locally_finite)) implies R1 is  normal))
proof
let R1 being non  empty TopSpace;
assume that
L783: R1 is  regular
and
L784: (ex B116 being (FamilySequence of R1) st B116 is  Basis_sigma_locally_finite);
consider C136 being (FamilySequence of R1) such that L785: C136 is  Basis_sigma_locally_finite by L784;
L786: ( Union C136 ) is (Basis of R1) by L785 , L443;
L787: C136 is  sigma_locally_finite by L785 , L443;
L788: (for R6 being (Subset of R1) holds (for R11 being  open (Subset of R1) holds ((R6 is  closed & R11 is  open & R6 c= R11) implies (ex B117 being (Function of ( NAT ) , ( bool (the carrier of R1) )) st (R6 c= ( Union B117 ) & ( Union B117 ) c= R11 & (for R21 being (Element of ( NAT )) holds (( Cl ( B117 . R21 ) ) c= R11 & ( B117 . R21 ) is  open)))))))
proof
let R6 being (Subset of R1);
let R11 being  open (Subset of R1);
assume that
L789: R6 is  closed
and
L790: R11 is  open
and
L791: R6 c= R11;
deffunc H7(set) = ( union { B118 where B118 is (Subset of R1) : (B118 in ( C136 . $1 ) & ( Cl B118 ) c= R11) } );
L792: (for B119 being set holds (B119 in ( NAT ) implies H7(B119) in ( bool (the carrier of R1) )))
proof
let C137 being set;
assume L793: C137 in ( NAT );
reconsider D66 = C137 as (Element of ( NAT )) by L793;
L794:
now
let C138 being set;
assume L795: C138 in H7(D66);
consider C139 being set such that L796: C138 in C139 and L797: C139 in { B120 where B120 is (Subset of R1) : (B120 in ( C136 . D66 ) & ( Cl B120 ) c= R11) } by L795 , TARSKI:def 4;
L798: (ex B121 being (Subset of R1) st (C139 = B121 & B121 in ( C136 . D66 ) & ( Cl B121 ) c= R11)) by L797;
thus L799: C138 in (the carrier of R1) by L798 , L796;
end;
L800: H7(D66) c= (the carrier of R1) by L794 , TARSKI:def 3;
thus L801: thesis by L800;
end;
consider C140 being (Function of ( NAT ) , ( bool (the carrier of R1) )) such that L802: (for B122 being set holds (B122 in ( NAT ) implies ( C140 . B122 ) = H7(B122))) from FUNCT_2:sch 2(L792);
L803:
now
let R21 being (Element of ( NAT ));
set D67 = { B123 where B123 is (Subset of R1) : (B123 in ( C136 . R21 ) & ( Cl B123 ) c= R11) };
L804: D67 c= ( bool (the carrier of R1) )
proof
let C141 being set;
assume L805: C141 in D67;
L806: (ex B124 being (Subset of R1) st (C141 = B124 & B124 in ( C136 . R21 ) & ( Cl B124 ) c= R11)) by L805;
thus L807: thesis by L806;
end;
reconsider D68 = D67 as (Subset-Family of R1) by L804;
L808: D68 c= ( C136 . R21 )
proof
let C142 being set;
assume L809: C142 in D68;
L810: (ex B125 being (Subset of R1) st (C142 = B125 & B125 in ( C136 . R21 ) & ( Cl B125 ) c= R11)) by L809;
thus L811: thesis by L810;
end;
L812: ( C136 . R21 ) is  locally_finite by L787 , L315;
L813: ( Cl ( union D68 ) ) = ( union ( clf D68 ) ) by L812 , L808 , PCOMPS_1:9 , PCOMPS_1:20;
L814: ( Cl ( union D68 ) ) c= R11
proof
let C143 being set;
assume L815: C143 in ( Cl ( union D68 ) );
consider C144 being set such that L816: C143 in C144 and L817: C144 in ( clf D68 ) by L815 , L813 , TARSKI:def 4;
reconsider D69 = C144 as (Subset of R1) by L817;
consider C145 being (Subset of R1) such that L818: ( Cl C145 ) = D69 and L819: C145 in D68 by L817 , PCOMPS_1:def 2;
L820: (ex B126 being (Subset of R1) st (C145 = B126 & B126 in ( C136 . R21 ) & ( Cl B126 ) c= R11)) by L819;
thus L821: thesis by L820 , L816 , L818;
end;
L822: D68 c= (the topology of R1)
proof
let C146 being set;
assume L823: C146 in D68;
consider C147 being (Subset of R1) such that L824: C146 = C147 and L825: C147 in ( C136 . R21 ) and L826: ( Cl C147 ) c= R11 by L823;
L827: ( Union C136 ) c= (the topology of R1) by L786 , TOPS_2:64;
L828: C147 in ( Union C136 ) by L825 , PROB_1:12;
thus L829: thesis by L828 , L824 , L827;
end;
L830: ( union D68 ) in (the topology of R1) by L822 , PRE_TOPC:def 1;
L831: ( union D68 ) is  open by L830 , PRE_TOPC:def 2;
thus L832: (( C140 . R21 ) is  open & ( Cl ( C140 . R21 ) ) c= R11) by L831 , L802 , L814;
end;
L833: ( Union C140 ) c= R11
proof
let C148 being set;
assume L834: C148 in ( Union C140 );
consider C149 being (Element of ( NAT )) such that L835: C148 in ( C140 . C149 ) by L834 , PROB_1:12;
L836: C148 in ( union { B127 where B127 is (Subset of R1) : (B127 in ( C136 . C149 ) & ( Cl B127 ) c= R11) } ) by L802 , L835;
consider C150 being set such that L837: C148 in C150 and L838: C150 in { B128 where B128 is (Subset of R1) : (B128 in ( C136 . C149 ) & ( Cl B128 ) c= R11) } by L836 , TARSKI:def 4;
consider C151 being (Subset of R1) such that L839: C150 = C151 and L840: C151 in ( C136 . C149 ) and L841: ( Cl C151 ) c= R11 by L838;
L842: C151 c= ( Cl C151 ) by PRE_TOPC:18;
L843: C150 c= R11 by L842 , L839 , L841 , XBOOLE_1:1;
thus L844: thesis by L843 , L837;
end;
L845: (for B129 being set holds (B129 in R6 implies B129 in ( Union C140 )))
proof
let C152 being set;
assume L846: C152 in R6;
consider C153 being (Subset of R1) such that L847: C152 in C153 and L848: ( Cl C153 ) c= R11 and L849: C153 in ( Union C136 ) by L846 , L783 , L786 , L791 , L750;
consider C154 being (Element of ( NAT )) such that L850: C153 in ( C136 . C154 ) by L849 , PROB_1:12;
L851: C153 in { B130 where B130 is (Subset of R1) : (B130 in ( C136 . C154 ) & ( Cl B130 ) c= R11) } by L848 , L850;
L852: C152 in H7(C154) by L851 , L847 , TARSKI:def 4;
L853: C152 in ( C140 . C154 ) by L852 , L802;
thus L854: thesis by L853 , PROB_1:12;
end;
L855: R6 c= ( Union C140 ) by L845 , TARSKI:def 3;
thus L856: thesis by L855 , L833 , L803;
end;
thus L857: thesis by L788 , L624;
end;
L858: (for B131 being Real holds (for B132 being (Point of ( RealSpace )) holds (B131 > ( 0 ) implies B132 in ( Ball (B132 , B131) ))))
proof
let C155 being Real;
let C156 being (Point of ( RealSpace ));
reconsider D70 = C156 as Real by METRIC_1:def 13;
L859: ( abs ( D70 - D70 ) ) = ( 0 ) by ABSVALUE:2;
assume L860: C155 > ( 0 );
L861: ( dist (C156 , C156) ) < C155 by L860 , L859 , TOPMETR:11;
thus L862: thesis by L861 , METRIC_1:11;
end;
definition
let R1 being non  empty TopSpace;
let C157 , C158 being (RealMap of R1);
redefine func C157 + C158 -> (RealMap of R1) means 
:L863: (for B133 being (Element of R1) holds ( it . B133 ) = ( ( C157 . B133 ) + ( C158 . B133 ) ));
coherence
proof
L864: ( C157 + C158 ) is (Function of (the carrier of R1) , ( REAL ));
thus L865: thesis by L864;
end;
compatibility
proof
let C159 being (RealMap of R1);
thus L866: (C159 = ( C157 + C158 ) implies (for B134 being (Element of R1) holds ( C159 . B134 ) = ( ( C157 . B134 ) + ( C158 . B134 ) ))) by VALUED_1:1;
L867: ( dom ( C157 + C158 ) ) = ( ( dom C157 ) /\ ( dom C158 ) ) by VALUED_1:def 1
.= ( (the carrier of R1) /\ ( dom C158 ) ) by FUNCT_2:def 1
.= ( (the carrier of R1) /\ (the carrier of R1) ) by FUNCT_2:def 1;
assume L868: (for B135 being (Element of R1) holds ( C159 . B135 ) = ( ( C157 . B135 ) + ( C158 . B135 ) ));
L869:
now
let C160 being set;
assume L870: C160 in ( dom C159 );
thus L871: ( C159 . C160 ) = ( ( C157 . C160 ) + ( C158 . C160 ) ) by L870 , L868
.= ( ( C157 + C158 ) . C160 ) by L867 , L870 , VALUED_1:def 1;
end;
L872: ( dom C159 ) = (the carrier of R1) by FUNCT_2:def 1;
thus L873: thesis by L872 , L867 , L869 , FUNCT_1:2;
end;
end;
theorem
L875: (for R1 being non  empty TopSpace holds (for B136 being (RealMap of R1) holds (B136 is  continuous implies (for B137 being (RealMap of [: R1 , R1 :]) holds ((for B138 , B139 being (Element of R1) holds ( B137 . (B138 , B139) ) = ( abs ( ( B136 . B138 ) - ( B136 . B139 ) ) )) implies B137 is  continuous)))))
proof
let R1 being non  empty TopSpace;
let C161 being (RealMap of R1);
assume that
L876: C161 is  continuous;
set D71 = [: R1 , R1 :];
set D72 = (the carrier of R1);
reconsider D73 = C161 as (Function of R1 , ( R^1 )) by TOPMETR:17;
let C162 being (RealMap of [: R1 , R1 :]);
assume that
L877: (for B140 , B141 being (Element of R1) holds ( C162 . (B140 , B141) ) = ( abs ( ( C161 . B140 ) - ( C161 . B141 ) ) ));
reconsider D74 = C162 as (Function of [: R1 , R1 :] , ( R^1 )) by TOPMETR:17;
L878: D73 is  continuous by L876 , JORDAN5A:27;
L879:
now
let C163 being (Point of D71);
L880: C163 in (the carrier of D71);
L881: C163 in [: D72 , D72 :] by L880 , BORSUK_1:def 2;
consider C164 , C165 being set such that L882: (C164 in D72 & C165 in D72) and L883: [ C164 , C165 ] = C163 by L881 , ZFMISC_1:def 2;
reconsider D75 = C164 , D76 = C165 as (Point of R1) by L882;
L884: (for B142 being (Subset of ( R^1 )) holds ((B142 is  open & ( D74 . C163 ) in B142) implies (ex B143 being (Subset of D71) st (B143 is  open & C163 in B143 & ( D74 .: B143 ) c= B142))))
proof
reconsider D77 = ( C161 . D75 ) , D78 = ( C161 . D76 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
reconsider D79 = ( C162 . C163 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
let C166 being (Subset of ( R^1 ));
assume L885: (C166 is  open & ( D74 . C163 ) in C166);
consider C167 being  real number such that L886: C167 > ( 0 ) and L887: ( Ball (D79 , C167) ) c= C166 by L885 , TOPMETR:15 , TOPMETR:def 6;
reconsider D80 = C167 as Real by XREAL_0:def 1;
reconsider D81 = ( Ball (D77 , ( D80 / 2 )) ) , D82 = ( Ball (D78 , ( D80 / 2 )) ) as (Subset of ( R^1 )) by METRIC_1:def 13 , TOPMETR:17;
L888: (D81 is  open & D73 is_continuous_at D75) by L878 , TMAP_1:50 , TOPMETR:14 , TOPMETR:def 6;
L889: ( C161 . D75 ) in D81 by L886 , L858 , XREAL_1:139;
consider C168 being (Subset of R1) such that L890: C168 is  open and L891: D75 in C168 and L892: ( D73 .: C168 ) c= D81 by L889 , L888 , TMAP_1:43;
L893: (D82 is  open & D73 is_continuous_at D76) by L878 , TMAP_1:50 , TOPMETR:14 , TOPMETR:def 6;
L894: ( C161 . D76 ) in D82 by L886 , L858 , XREAL_1:139;
consider C169 being (Subset of R1) such that L895: C169 is  open and L896: D76 in C169 and L897: ( D73 .: C169 ) c= D82 by L894 , L893 , TMAP_1:43;
L898: ( C162 . C163 ) = ( C162 . (D75 , D76) ) by L883;
L899: ( abs ( ( D73 . D75 ) - ( D73 . D76 ) ) ) = ( C162 . C163 ) by L898 , L877;
L900: ( C162 .: [: C168 , C169 :] ) c= C166
proof
let C170 being set;
assume L901: C170 in ( C162 .: [: C168 , C169 :] );
consider C171 being set such that L902: C171 in ( dom C162 ) and L903: C171 in [: C168 , C169 :] and L904: C170 = ( C162 . C171 ) by L901 , FUNCT_1:def 6;
consider R14 being set, R15 being set such that L905: R14 in C168 and L906: R15 in C169 and L907: C171 = [ R14 , R15 ] by L903 , ZFMISC_1:def 2;
reconsider D83 = R14 , D84 = R15 as (Point of R1) by L905 , L906;
reconsider D85 = ( C161 . D83 ) , D86 = ( C161 . D84 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
L908: D84 in D72;
L909: D84 in ( dom C161 ) by L908 , FUNCT_2:def 1;
L910: ( C161 . D84 ) in ( C161 .: C169 ) by L909 , L906 , FUNCT_1:def 6;
L911: ( dist (D86 , D78) ) < ( D80 / 2 ) by L910 , L897 , METRIC_1:11;
reconsider D87 = ( C162 . [ D83 , D84 ] ) as (Point of ( RealSpace )) by METRIC_1:def 13;
L912: ( abs ( ( C161 . D83 ) - ( C161 . D84 ) ) ) = ( C162 . (D83 , D84) ) by L877;
L913: ( C162 . [ D83 , D84 ] ) <= ( ( ( abs ( ( C161 . D83 ) - ( C161 . D75 ) ) ) + ( C162 . C163 ) ) + ( abs ( ( C161 . D76 ) - ( C161 . D84 ) ) ) ) by L912 , L899 , L7;
L914: ( C162 . [ D83 , D84 ] ) <= ( ( ( abs ( ( C161 . D83 ) - ( C161 . D75 ) ) ) + ( C162 . C163 ) ) + ( dist (D78 , D86) ) ) by L913 , TOPMETR:11;
L915: ( ( C162 . [ D83 , D84 ] ) + ( 0 ) ) <= ( ( ( C162 . C163 ) + ( dist (D85 , D77) ) ) + ( dist (D78 , D86) ) ) by L914 , TOPMETR:11;
L916: ( C162 . C163 ) <= ( ( ( abs ( ( C161 . D75 ) - ( C161 . D83 ) ) ) + ( C162 . [ D83 , D84 ] ) ) + ( abs ( ( C161 . D84 ) - ( C161 . D76 ) ) ) ) by L899 , L912 , L7;
L917: ( C162 . C163 ) <= ( ( ( dist (D85 , D77) ) + ( C162 . [ D83 , D84 ] ) ) + ( abs ( ( C161 . D84 ) - ( C161 . D76 ) ) ) ) by L916 , TOPMETR:11;
L918: ( C162 . C163 ) <= ( ( ( C162 . [ D83 , D84 ] ) + ( dist (D85 , D77) ) ) + ( dist (D86 , D78) ) ) by L917 , TOPMETR:11;
L919: D83 in D72;
L920: D83 in ( dom C161 ) by L919 , FUNCT_2:def 1;
L921: ( C161 . D83 ) in ( C161 .: C168 ) by L920 , L905 , FUNCT_1:def 6;
L922: ( dist (D85 , D77) ) < ( D80 / 2 ) by L921 , L892 , METRIC_1:11;
L923: ( ( dist (D85 , D77) ) + ( dist (D86 , D78) ) ) < ( ( D80 / 2 ) + ( D80 / 2 ) ) by L922 , L911 , XREAL_1:8;
L924: ( ( C162 . [ D83 , D84 ] ) + ( ( dist (D85 , D77) ) + ( dist (D86 , D78) ) ) ) < ( ( C162 . [ D83 , D84 ] ) + D80 ) by L923 , XREAL_1:8;
L925: ( C162 . C163 ) < ( - ( ( - ( C162 . [ D83 , D84 ] ) ) - D80 ) ) by L924 , L918 , XXREAL_0:2;
L926: ( ( - ( C162 . C163 ) ) - ( 0 ) ) > ( ( - D80 ) - ( C162 . [ D83 , D84 ] ) ) by L925 , XREAL_1:26;
L927: ( ( - ( C162 . C163 ) ) + ( C162 . [ D83 , D84 ] ) ) > ( ( - D80 ) + ( 0 ) ) by L926 , XREAL_1:21;
L928: ( ( C162 . C163 ) + ( ( dist (D85 , D77) ) + ( dist (D78 , D86) ) ) ) < ( ( C162 . C163 ) + D80 ) by L923 , XREAL_1:8;
L929: ( ( C162 . [ D83 , D84 ] ) + ( 0 ) ) < ( ( C162 . C163 ) + D80 ) by L928 , L915 , XXREAL_0:2;
L930: ( ( C162 . [ D83 , D84 ] ) - ( C162 . C163 ) ) < ( D80 - ( 0 ) ) by L929 , XREAL_1:21;
L931: ( abs ( ( C162 . [ D83 , D84 ] ) - ( C162 . C163 ) ) ) < D80 by L930 , L927 , SEQ_2:1;
L932: ( dist (D79 , D87) ) < D80 by L931 , TOPMETR:11;
L933: D87 in ( Ball (D79 , C167) ) by L932 , METRIC_1:11;
thus L934: thesis by L933 , L887 , L904 , L907;
end;
L935: C163 in [: C168 , C169 :] by L883 , L891 , L896 , ZFMISC_1:def 2;
thus L936: thesis by L935 , L890 , L895 , L900 , BORSUK_1:6;
end;
thus L937: D74 is_continuous_at C163 by L884 , TMAP_1:43;
end;
L938: D74 is  continuous by L879 , TMAP_1:50;
thus L939: thesis by L938 , JORDAN5A:27;
end;
theorem
L940: (for R1 being non  empty TopSpace holds (for B144 , B145 being (RealMap of R1) holds ((B144 is  continuous & B145 is  continuous) implies ( B144 + B145 ) is  continuous)))
proof
let R1 being non  empty TopSpace;
let C172 , C173 being (RealMap of R1);
assume that
L941: C172 is  continuous
and
L942: C173 is  continuous;
reconsider D88 = C172 , D89 = C173 , D90 = ( C172 + C173 ) as (Function of R1 , ( R^1 )) by TOPMETR:17;
L943: D89 is  continuous by L942 , JORDAN5A:27;
L944: D88 is  continuous by L941 , JORDAN5A:27;
L945:
now
let C174 being (Point of R1);
L946: (for B146 being (Subset of ( R^1 )) holds ((B146 is  open & ( D90 . C174 ) in B146) implies (ex B147 being (Subset of R1) st (B147 is  open & C174 in B147 & ( D90 .: B147 ) c= B146))))
proof
reconsider D91 = ( C172 . C174 ) , D92 = ( C173 . C174 ) , D93 = ( ( C172 + C173 ) . C174 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
let C175 being (Subset of ( R^1 ));
assume L947: (C175 is  open & ( D90 . C174 ) in C175);
consider C176 being  real number such that L948: C176 > ( 0 ) and L949: ( Ball (D93 , C176) ) c= C175 by L947 , TOPMETR:15 , TOPMETR:def 6;
reconsider D94 = C176 as Real by XREAL_0:def 1;
reconsider D95 = ( Ball (D91 , ( D94 / 2 )) ) , D96 = ( Ball (D92 , ( D94 / 2 )) ) as (Subset of ( R^1 )) by METRIC_1:def 13 , TOPMETR:17;
L950: (D95 is  open & D88 is_continuous_at C174) by L944 , TMAP_1:50 , TOPMETR:14 , TOPMETR:def 6;
L951: ( D88 . C174 ) in D95 by L948 , L858 , XREAL_1:139;
consider C177 being (Subset of R1) such that L952: C177 is  open and L953: C174 in C177 and L954: ( D88 .: C177 ) c= D95 by L951 , L950 , TMAP_1:43;
L955: (D96 is  open & D89 is_continuous_at C174) by L943 , TMAP_1:50 , TOPMETR:14 , TOPMETR:def 6;
L956: ( C173 . C174 ) in D96 by L948 , L858 , XREAL_1:139;
consider C178 being (Subset of R1) such that L957: C178 is  open and L958: C174 in C178 and L959: ( D89 .: C178 ) c= D96 by L956 , L955 , TMAP_1:43;
L960: ( ( C172 + C173 ) .: ( C177 /\ C178 ) ) c= C175
proof
let C179 being set;
assume L961: C179 in ( ( C172 + C173 ) .: ( C177 /\ C178 ) );
consider R14 being set such that L962: R14 in ( dom ( C172 + C173 ) ) and L963: R14 in ( C177 /\ C178 ) and L964: C179 = ( ( C172 + C173 ) . R14 ) by L961 , FUNCT_1:def 6;
reconsider D97 = R14 as (Point of R1) by L962;
reconsider D98 = ( C172 . D97 ) , D99 = ( C173 . D97 ) , D100 = ( ( C172 + C173 ) . D97 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
L965: (( dom C173 ) = (the carrier of R1) & D97 in C178) by L963 , FUNCT_2:def 1 , XBOOLE_0:def 4;
L966: ( C173 . D97 ) in ( C173 .: C178 ) by L965 , FUNCT_1:def 6;
L967: ( dist (D99 , D92) ) < ( D94 / 2 ) by L966 , L959 , METRIC_1:11;
L968: ( abs ( ( C173 . D97 ) - ( C173 . C174 ) ) ) < ( D94 / 2 ) by L967 , TOPMETR:11;
L969: ( - ( D94 / 2 ) ) < ( ( C173 . D97 ) - ( C173 . C174 ) ) by L968 , SEQ_2:1;
L970: (( dom C172 ) = (the carrier of R1) & D97 in C177) by L963 , FUNCT_2:def 1 , XBOOLE_0:def 4;
L971: ( C172 . D97 ) in ( C172 .: C177 ) by L970 , FUNCT_1:def 6;
L972: ( dist (D98 , D91) ) < ( D94 / 2 ) by L971 , L954 , METRIC_1:11;
L973: ( abs ( ( C172 . D97 ) - ( C172 . C174 ) ) ) < ( D94 / 2 ) by L972 , TOPMETR:11;
L974: ( - ( D94 / 2 ) ) < ( ( C172 . D97 ) - ( C172 . C174 ) ) by L973 , SEQ_2:1;
L975: ( ( - ( D94 / 2 ) ) + ( - ( D94 / 2 ) ) ) < ( ( ( C172 . D97 ) - ( C172 . C174 ) ) + ( ( C173 . D97 ) - ( C173 . C174 ) ) ) by L974 , L969 , XREAL_1:8;
L976: ( - D94 ) < ( ( ( C172 . D97 ) + ( C173 . D97 ) ) - ( ( C172 . C174 ) + ( C173 . C174 ) ) ) by L975;
L977: ( ( C173 . D97 ) - ( C173 . C174 ) ) < ( D94 / 2 ) by L968 , SEQ_2:1;
L978: ( ( C172 . D97 ) - ( C172 . C174 ) ) < ( D94 / 2 ) by L973 , SEQ_2:1;
L979: ( ( ( C172 . D97 ) - ( C172 . C174 ) ) + ( ( C173 . D97 ) - ( C173 . C174 ) ) ) < ( ( D94 / 2 ) + ( D94 / 2 ) ) by L978 , L977 , XREAL_1:8;
L980: ( abs ( ( ( C172 . D97 ) + ( C173 . D97 ) ) - ( ( C172 . C174 ) + ( C173 . C174 ) ) ) ) < D94 by L979 , L976 , SEQ_2:1;
L981: ( abs ( ( ( C172 + C173 ) . D97 ) - ( ( C172 . C174 ) + ( C173 . C174 ) ) ) ) < D94 by L980 , L863;
L982: ( abs ( ( ( C172 + C173 ) . D97 ) - ( ( C172 + C173 ) . C174 ) ) ) < D94 by L981 , L863;
L983: ( dist (D93 , D100) ) < D94 by L982 , TOPMETR:11;
L984: D100 in ( Ball (D93 , C176) ) by L983 , METRIC_1:11;
thus L985: thesis by L984 , L949 , L964;
end;
L986: C174 in ( C177 /\ C178 ) by L953 , L958 , XBOOLE_0:def 4;
thus L987: thesis by L986 , L952 , L957 , L960;
end;
thus L988: D90 is_continuous_at C174 by L946 , TMAP_1:43;
end;
L989: D90 is  continuous by L945 , TMAP_1:50;
thus L990: thesis by L989 , JORDAN5A:27;
end;
theorem
L991: (for R1 being non  empty TopSpace holds (for B148 being (BinOp of ( Funcs ((the carrier of R1) , ( REAL )) )) holds ((for B149 , B150 being (RealMap of R1) holds ( B148 . (B149 , B150) ) = ( B149 + B150 )) implies (B148 is  having_a_unity & B148 is  commutative  associative))))
proof
let R1 being non  empty TopSpace;
set D101 = ( Funcs ((the carrier of R1) , ( REAL )) );
let C180 being (BinOp of ( Funcs ((the carrier of R1) , ( REAL )) ));
assume that
L992: (for B151 , B152 being (RealMap of R1) holds ( C180 . (B151 , B152) ) = ( B151 + B152 ));
L993: (ex B153 being (Element of D101) st B153 is_a_unity_wrt C180)
proof
reconsider D102 = ( (the carrier of R1) --> ( 0 ) ) as (RealMap of R1) by FUNCOP_1:45;
reconsider D103 = D102 as (Element of D101) by FUNCT_2:8;
take D103;
L994:
now
let C181 being (Element of D101);
L995:
now
let C182 being (Element of R1);
L996: ( ( C181 + D103 ) . C182 ) = ( ( C181 . C182 ) + ( D103 . C182 ) ) by L863;
L997: ( ( C181 + D103 ) . C182 ) = ( ( C181 . C182 ) + ( 0 ) ) by L996 , FUNCOP_1:7;
thus L998: ( ( C181 + D103 ) . C182 ) = ( C181 . C182 ) by L997;
end;
L999: ( C181 + D103 ) = C181 by L995 , FUNCT_2:63;
thus L1000: (( C180 . (D102 , C181) ) = C181 & ( C180 . (C181 , D102) ) = C181) by L999 , L992;
end;
thus L1001: thesis by L994 , BINOP_1:3;
end;
thus L1002: C180 is  having_a_unity by L993 , SETWISEO:def 2;
thus L1003: C180 is  commutative
proof
let C183 , C184 being (Element of D101);
L1004: ( C180 . (C183 , C184) ) = ( C183 + C184 ) by L992;
thus L1005: thesis by L1004 , L992;
end;

thus L1006: C180 is  associative
proof
let C185 , C186 , C187 being (Element of D101);
reconsider D104 = ( C180 . (C185 , C186) ) , D105 = ( C180 . (C186 , C187) ) as (RealMap of R1) by FUNCT_2:66;
L1007: ( D104 + C187 ) = ( C180 . (D104 , C187) ) by L992;
L1008:
now
let C188 being (Element of R1);
L1009: (( ( C185 + ( C186 + C187 ) ) . C188 ) = ( ( C185 . C188 ) + ( ( C186 + C187 ) . C188 ) ) & ( ( C186 + C187 ) . C188 ) = ( ( C186 . C188 ) + ( C187 . C188 ) )) by L863;
L1010: ( ( C185 + ( C186 + C187 ) ) . C188 ) = ( ( ( C185 . C188 ) + ( C186 . C188 ) ) + ( C187 . C188 ) ) by L1009;
L1011: ( ( C185 + ( C186 + C187 ) ) . C188 ) = ( ( ( C185 + C186 ) . C188 ) + ( C187 . C188 ) ) by L1010 , L863;
thus L1012: ( ( C185 + ( C186 + C187 ) ) . C188 ) = ( ( ( C185 + C186 ) + C187 ) . C188 ) by L1011 , L863;
end;
L1013: ( C185 + ( C186 + C187 ) ) = ( ( C185 + C186 ) + C187 ) by L1008 , FUNCT_2:63;
L1014: ( C185 + ( C186 + C187 ) ) = ( C185 + D105 ) by L992;
L1015: ( C185 + D105 ) = ( D104 + C187 ) by L1014 , L992 , L1013;
thus L1016: thesis by L1015 , L992 , L1007;
end;

end;
theorem
L1007: (for R1 being non  empty TopSpace holds (for B154 being (BinOp of ( Funcs ((the carrier of R1) , ( REAL )) )) holds ((for B155 , B156 being (RealMap of R1) holds ( B154 . (B155 , B156) ) = ( B155 + B156 )) implies (for B157 being (Element of ( Funcs ((the carrier of R1) , ( REAL )) )) holds (B157 is_a_unity_wrt B154 implies B157 is  continuous)))))
proof
let R1 being non  empty TopSpace;
let C189 being (BinOp of ( Funcs ((the carrier of R1) , ( REAL )) ));
assume that
L1008: (for B158 , B159 being (RealMap of R1) holds ( C189 . (B158 , B159) ) = ( B158 + B159 ));
set D106 = ( Funcs ((the carrier of R1) , ( REAL )) );
let C190 being (Element of D106);
assume that
L1009: C190 is_a_unity_wrt C189;
L1010: (for B160 being (Point of R1) holds ( C190 . B160 ) = ( 0 ))
proof
assume L1011: (ex B161 being (Point of R1) st ( C190 . B161 ) <> ( 0 ));
consider C191 being (Point of R1) such that L1012: ( C190 . C191 ) <> ( 0 ) by L1011;
L1013: ( C189 . (C190 , C190) ) = C190 by L1009 , BINOP_1:3;
L1014: ( C190 + C190 ) = C190 by L1013 , L1008;
L1015: ( ( C190 . C191 ) + ( C190 . C191 ) ) = ( C190 . C191 ) by L1014 , L863;
thus L1016: thesis by L1015 , L1012;
end;
reconsider D107 = C190 as (Function of R1 , ( R^1 )) by TOPMETR:17;
L1017: (for B162 being (Subset of R1) holds ( D107 .: ( Cl B162 ) ) c= ( Cl (( D107 .: B162 ) qua (Subset of ( R^1 ))) ))
proof
let C192 being (Subset of R1);
let C193 being set;
assume L1018: C193 in ( D107 .: ( Cl C192 ) );
L1019: (ex B163 being set st (B163 in ( dom C190 ) & B163 in ( Cl C192 ) & C193 = ( D107 . B163 ))) by L1018 , FUNCT_1:def 6;
L1020: C192 <> ( {} R1 ) by L1019 , PRE_TOPC:22;
consider C194 being set such that L1021: C194 in C192 by L1020 , XBOOLE_0:def 1;
reconsider D108 = C194 as (Element of R1) by L1021;
L1022: (( dom C190 ) = (the carrier of R1) & ( C190 . D108 ) = ( 0 )) by L1010 , FUNCT_2:def 1;
L1023: ( 0 ) in ( C190 .: C192 ) by L1022 , L1021 , FUNCT_1:def 6;
L1024: C193 in ( C190 .: C192 ) by L1023 , L1010 , L1019;
L1025: ( D107 .: C192 ) c= ( Cl ( D107 .: C192 ) ) by PRE_TOPC:18;
thus L1026: thesis by L1025 , L1024;
end;
L1027: D107 is  continuous by L1017 , TOPS_2:45;
thus L1028: thesis by L1027 , JORDAN5A:27;
end;
definition
let C195 , C196 being non  empty set;
let C197 being (Function of C195 , ( Funcs (C195 , C196) ));
func C197 Toler -> (Function of C195 , C196) means 
:L1029: (for B164 being (Element of C195) holds ( it . B164 ) = ( ( C197 . B164 ) . B164 ));
existence
proof
deffunc H8((Element of C195)) = ( ( C197 . $1 ) . $1 );
defpred S6[ (Element of C195) , set ] means $2 = H8($1);
L1030: (for B165 being (Element of C195) holds (ex B166 being (Element of C196) st S6[ B165 , B166 ]))
proof
let C198 being (Element of C195);
reconsider D109 = ( C197 . C198 ) as (Function of C195 , C196) by FUNCT_2:66;
L1031: ( D109 . C198 ) in C196;
thus L1032: thesis by L1031;
end;
consider C199 being (Function of C195 , C196) such that L1033: (for B167 being (Element of C195) holds S6[ B167 , ( C199 . B167 ) ]) from FUNCT_2:sch 3(L1030);
take C199;
thus L1034: thesis by L1033;
end;
uniqueness
proof
L1035:
now
let C200 , C201 being (Function of C195 , C196);
assume that
L1036: (for B168 being (Element of C195) holds (( C200 . B168 ) = ( ( C197 . B168 ) . B168 ) & (for B169 being (Element of C195) holds ( C201 . B169 ) = ( ( C197 . B169 ) . B169 ))));
L1037:
now
let C202 being (Element of C195);
L1038: ( C200 . C202 ) = ( ( C197 . C202 ) . C202 ) by L1036;
thus L1039: ( C200 . C202 ) = ( C201 . C202 ) by L1038 , L1036;
end;
thus L1040: C200 = C201 by L1037 , FUNCT_2:63;
end;
thus L1041: thesis by L1035;
end;
end;
theorem
L1043: (for R1 being non  empty TopSpace holds (for B170 being (BinOp of ( Funcs ((the carrier of R1) , ( REAL )) )) holds ((for B171 , B172 being (RealMap of R1) holds ( B170 . (B171 , B172) ) = ( B171 + B172 )) implies (for B173 being (FinSequence of ( Funcs ((the carrier of R1) , ( REAL )) )) holds ((for R21 being (Element of ( NAT )) holds ((( 0 ) <> R21 & R21 <= ( len B173 )) implies ( B173 . R21 ) is  continuous  continuous  continuous  continuous (RealMap of R1))) implies ( B170 "**" B173 ) is  continuous  continuous  continuous  continuous (RealMap of R1))))))
proof
let R1 being non  empty TopSpace;
let C203 being (BinOp of ( Funcs ((the carrier of R1) , ( REAL )) ));
assume that
L1044: (for B174 , B175 being (RealMap of R1) holds ( C203 . (B174 , B175) ) = ( B174 + B175 ));
set D110 = ( Funcs ((the carrier of R1) , ( REAL )) );
let C204 being (FinSequence of ( Funcs ((the carrier of R1) , ( REAL )) ));
assume that
L1045: (for R21 being (Element of ( NAT )) holds ((( 0 ) <> R21 & R21 <= ( len C204 )) implies ( C204 . R21 ) is  continuous  continuous  continuous  continuous (RealMap of R1)));
reconsider D111 = ( C203 "**" C204 ) as (RealMap of R1) by FUNCT_2:66;
L1046:
now
per cases ;
suppose L1047: ( len C204 ) = ( 0 );

L1048: C203 is  having_a_unity by L1044 , L991;
L1049: (ex B176 being (Element of D110) st B176 is_a_unity_wrt C203) by L1048 , SETWISEO:def 2;
L1050: ( the_unity_wrt C203 ) is_a_unity_wrt C203 by L1049 , BINOP_1:def 8;
L1051: D111 = ( the_unity_wrt C203 ) by L1047 , L1048 , FINSOP_1:def 1;
thus L1052: thesis by L1051 , L1044 , L1050 , L1007;
end;
suppose L1053: ( len C204 ) <> ( 0 );

L1054: ( len C204 ) >= 1
proof
assume L1055: ( len C204 ) < 1;
L1056: ( len C204 ) < ( 1 + ( 0 ) ) by L1055;
thus L1057: thesis by L1056 , L1053 , NAT_1:13;
end;
consider C205 being (Function of ( NAT ) , D110) such that L1058: ( C205 . 1 ) = ( C204 . 1 ) and L1059: (for R21 being (Element of ( NAT )) holds ((( 0 ) <> R21 & R21 < ( len C204 )) implies ( C205 . ( R21 + 1 ) ) = ( C203 . (( C205 . R21 ) , ( C204 . ( R21 + 1 ) )) ))) and L1060: ( C203 "**" C204 ) = ( C205 . ( len C204 ) ) by L1054 , FINSOP_1:1;
defpred S7[ Nat ] means ($1 <= ( len C204 ) implies ( C205 . $1 ) is  continuous  continuous  continuous  continuous (RealMap of R1));
L1061: (for B177 being Nat holds (B177 >= 1 implies (S7[ B177 ] implies S7[ ( B177 + 1 ) ])))
proof
let C206 being Nat;
assume that
L1062: C206 >= 1
and
L1063: S7[ C206 ];
assume L1064: ( C206 + 1 ) <= ( len C204 );
reconsider D112 = C206 as (Element of ( NAT )) by ORDINAL1:def 12;
L1065: ( D112 + ( 0 ) ) < ( D112 + 1 ) by XREAL_1:8;
L1066: D112 < ( len C204 ) by L1065 , L1064 , XXREAL_0:2;
L1067: ( C205 . ( D112 + 1 ) ) = ( C203 . (( C205 . D112 ) , ( C204 . ( D112 + 1 ) )) ) by L1066 , L1059 , L1062;
L1068: ( 1 + ( 0 ) ) <= ( D112 + 1 ) by L1062 , XREAL_1:8;
L1069: ( D112 + 1 ) in ( Seg ( len C204 ) ) by L1068 , L1064 , FINSEQ_1:1;
L1070: ( D112 + 1 ) in ( dom C204 ) by L1069 , FINSEQ_1:def 3;
L1071: ( C204 . ( D112 + 1 ) ) in ( rng C204 ) by L1070 , FUNCT_1:def 3;
reconsider D113 = ( C205 . D112 ) , D114 = ( C204 . ( D112 + 1 ) ) as (RealMap of R1) by L1071 , FUNCT_2:66;
L1072: D114 is  continuous by L1045 , L1064;
L1073: ( D113 + D114 ) is  continuous by L1072 , L1063 , L1064 , L1065 , L940 , XXREAL_0:2;
thus L1074: thesis by L1073 , L1044 , L1067;
end;
L1075: S7[ 1 ] by L1045 , L1058;
L1076: (for B178 being Nat holds (B178 >= 1 implies S7[ B178 ])) from NAT_1:sch 8(L1075 , L1061);
thus L1077: thesis by L1076 , L1054 , L1060;
end;
end;
thus L1079: thesis by L1046;
end;
theorem
L1080: (for R1 being non  empty TopSpace holds (for R2 being non  empty TopSpace holds (for B179 being (Function of (the carrier of R1) , ( Funcs ((the carrier of R1) , (the carrier of R2)) )) holds ((for B180 being (Point of R1) holds ( B179 . B180 ) is  continuous  continuous  continuous  continuous (Function of R1 , R2)) implies (for B181 being (Function of (the carrier of R1) , ( bool (the carrier of R1) )) holds ((for B182 being (Point of R1) holds (B182 in ( B181 . B182 ) & ( B181 . B182 ) is  open & (for B183 , B184 being (Point of R1) holds (B183 in ( B181 . B184 ) implies ( ( B179 . B183 ) . B183 ) = ( ( B179 . B184 ) . B183 ))))) implies ( B179 Toler ) is  continuous))))))
proof
let R1 being non  empty TopSpace;
let R2 being non  empty TopSpace;
let C207 being (Function of (the carrier of R1) , ( Funcs ((the carrier of R1) , (the carrier of R2)) ));
assume that
L1081: (for R12 being (Point of R1) holds ( C207 . R12 ) is  continuous  continuous  continuous  continuous (Function of R1 , R2));
let C208 being (Function of (the carrier of R1) , ( bool (the carrier of R1) ));
assume that
L1082: (for R12 being (Point of R1) holds (R12 in ( C208 . R12 ) & ( C208 . R12 ) is  open & (for R12 being (Point of R1) holds (for R13 being (Point of R1) holds (R12 in ( C208 . R13 ) implies ( ( C207 . R12 ) . R12 ) = ( ( C207 . R13 ) . R12 ))))));
L1083:
now
let C209 being (Point of R1);
L1084: (for B185 being (Subset of R2) holds ((B185 is  open & ( ( C207 Toler ) . C209 ) in B185) implies (ex B186 being (Subset of R1) st (B186 is  open & C209 in B186 & ( ( C207 Toler ) .: B186 ) c= B185))))
proof
reconsider D115 = ( C207 . C209 ) as (Function of R1 , R2) by L1081;
let C210 being (Subset of R2);
assume that
L1085: C210 is  open
and
L1086: ( ( C207 Toler ) . C209 ) in C210;
L1087: D115 is  continuous by L1081;
L1088: D115 is_continuous_at C209 by L1087 , TMAP_1:50;
L1089: ( D115 . C209 ) in C210 by L1086 , L1029;
consider C211 being (Subset of R1) such that L1090: (C211 is  open & C209 in C211) and L1091: ( D115 .: C211 ) c= C210 by L1089 , L1085 , L1088 , TMAP_1:43;
set D116 = ( C211 /\ ( C208 . C209 ) );
L1092: ( ( C207 Toler ) .: D116 ) c= C210
proof
let C212 being set;
assume L1093: C212 in ( ( C207 Toler ) .: D116 );
consider C213 being set such that L1094: C213 in ( dom ( C207 Toler ) ) and L1095: C213 in D116 and L1096: C212 = ( ( C207 Toler ) . C213 ) by L1093 , FUNCT_1:def 6;
reconsider D117 = C213 as (Point of R1) by L1094;
L1097: (D117 in ( C208 . C209 ) & C212 = ( ( C207 . D117 ) . D117 )) by L1095 , L1096 , L1029 , XBOOLE_0:def 4;
L1098: C212 = ( D115 . D117 ) by L1097 , L1082;
L1099: (the carrier of R1) = ( dom D115 ) by FUNCT_2:def 1;
L1100: D117 in C211 by L1095 , XBOOLE_0:def 4;
L1101: C212 in ( D115 .: C211 ) by L1100 , L1098 , L1099 , FUNCT_1:def 6;
thus L1102: thesis by L1101 , L1091;
end;
take D116;
L1103: (( C208 . C209 ) is  open & C209 in ( C208 . C209 )) by L1082;
thus L1104: thesis by L1103 , L1090 , L1092 , XBOOLE_0:def 4;
end;
thus L1105: ( C207 Toler ) is_continuous_at C209 by L1084 , TMAP_1:43;
end;
thus L1106: thesis by L1083 , TMAP_1:50;
end;
definition
let R16 being set;
let R18 being Real;
let C214 being (Function of R16 , ( REAL ));
deffunc H9((Element of R16)) = ( min (R18 , ( C214 . $1 )) );
func min (R18 , C214) -> (Function of R16 , ( REAL )) means 
:L1107: (for R14 being set holds (R14 in R16 implies ( it . R14 ) = ( min (R18 , ( C214 . R14 )) )));
existence
proof
defpred S8[ set , set ] means (ex B187 being (Element of R16) st (B187 = $1 & $2 = H9(B187)));
L1108: (for R14 being set holds (R14 in R16 implies (ex B188 being set st (B188 in ( REAL ) & S8[ R14 , B188 ]))))
proof
let C215 being set;
assume L1109: C215 in R16;
reconsider D118 = C215 as (Element of R16) by L1109;
L1110: ( min (R18 , ( C214 . D118 )) ) is (Element of ( REAL )) by XREAL_0:def 1;
thus L1111: thesis by L1110;
end;
consider C216 being (Function of R16 , ( REAL )) such that L1112: (for B189 being set holds (B189 in R16 implies S8[ B189 , ( C216 . B189 ) ])) from FUNCT_2:sch 1(L1108);
take C216;
let R14 being set;
assume L1113: R14 in R16;
L1114: S8[ R14 , ( C216 . R14 ) ] by L1113 , L1112;
thus L1115: thesis by L1114;
end;
uniqueness
proof
let C217 , C218 being (Function of R16 , ( REAL ));
assume that
L1116: (for R14 being set holds (R14 in R16 implies ( C217 . R14 ) = ( min (R18 , ( C214 . R14 )) )))
and
L1117: (for R14 being set holds (R14 in R16 implies ( C218 . R14 ) = ( min (R18 , ( C214 . R14 )) )));
L1118:
now
let R14 being set;
assume that
L1119: R14 in R16;
reconsider D119 = R14 as (Element of R16) by L1119;
L1120: ( C217 . R14 ) = H9(D119) by L1116 , L1119;
thus L1121: ( C217 . R14 ) = ( C218 . R14 ) by L1120 , L1117 , L1119;
end;
thus L1122: C217 = C218 by L1118 , FUNCT_2:12;
end;
end;
theorem
L1124: (for R1 being non  empty TopSpace holds (for B190 being Real holds (for B191 being (RealMap of R1) holds (B191 is  continuous implies ( min (B190 , B191) ) is  continuous))))
proof
let R1 being non  empty TopSpace;
let C219 being Real;
let C220 being (RealMap of R1);
assume that
L1125: C220 is  continuous;
reconsider D120 = C220 , D121 = ( min (C219 , C220) ) as (Function of R1 , ( R^1 )) by TOPMETR:17;
L1126: D120 is  continuous by L1125 , JORDAN5A:27;
L1127:
now
let C221 being (Point of R1);
L1128: (for B192 being (Subset of ( R^1 )) holds ((B192 is  open & ( D121 . C221 ) in B192) implies (ex B193 being (Subset of R1) st (B193 is  open & C221 in B193 & ( D121 .: B193 ) c= B192))))
proof
reconsider D122 = ( C220 . C221 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
let C222 being (Subset of ( R^1 ));
assume that
L1129: C222 is  open
and
L1130: ( D121 . C221 ) in C222;
L1131:
now
per cases ;
suppose L1132: ( C220 . C221 ) <= C219;

L1133: ( C220 . C221 ) = ( min (C219 , ( C220 . C221 )) ) by L1132 , XXREAL_0:def 9;
L1134: D122 in C222 by L1133 , L1130 , L1107;
consider C223 being  real number such that L1135: C223 > ( 0 ) and L1136: ( Ball (D122 , C223) ) c= C222 by L1134 , L1129 , TOPMETR:15 , TOPMETR:def 6;
reconsider D123 = C223 as Real by XREAL_0:def 1;
reconsider D124 = ( Ball (D122 , D123) ) as (Subset of ( R^1 )) by METRIC_1:def 13 , TOPMETR:17;
L1137: ( dist (D122 , D122) ) < D123 by L1135 , METRIC_1:1;
L1138: D122 in D124 by L1137 , METRIC_1:11;
L1139: (D124 is  open & D120 is_continuous_at C221) by L1126 , TMAP_1:50 , TOPMETR:14 , TOPMETR:def 6;
consider C224 being (Subset of R1) such that L1140: (C224 is  open & C221 in C224) and L1141: ( D120 .: C224 ) c= D124 by L1139 , L1138 , TMAP_1:43;
L1142: ( ( min (C219 , C220) ) .: C224 ) c= C222
proof
let C225 being set;
assume L1143: C225 in ( ( min (C219 , C220) ) .: C224 );
consider R14 being set such that L1144: R14 in ( dom ( min (C219 , C220) ) ) and L1145: R14 in C224 and L1146: C225 = ( ( min (C219 , C220) ) . R14 ) by L1143 , FUNCT_1:def 6;
reconsider D125 = R14 as (Point of R1) by L1144;
reconsider D126 = ( C220 . D125 ) , D127 = C219 as (Point of ( RealSpace )) by METRIC_1:def 13;
L1147: ( dom ( min (C219 , C220) ) ) = (the carrier of R1) by FUNCT_2:def 1;
L1148: D125 in ( dom C220 ) by L1147 , L1144 , FUNCT_2:def 1;
L1149: ( C220 . D125 ) in ( C220 .: C224 ) by L1148 , L1145 , FUNCT_1:def 6;
L1150: ( C220 . D125 ) in D124 by L1149 , L1141;
L1151:
now
per cases ;
suppose L1152: ( C220 . D125 ) <= C219;

L1153: ( min (C219 , ( C220 . D125 )) ) = ( C220 . D125 ) by L1152 , XXREAL_0:def 9;
L1154: C225 = ( C220 . D125 ) by L1153 , L1146 , L1107;
thus L1155: thesis by L1154 , L1136 , L1150;
end;
suppose L1156: ( C220 . D125 ) > C219;

L1157: ( dist (D126 , D122) ) < C223 by L1141 , L1149 , METRIC_1:11;
L1158: ( abs ( ( C220 . D125 ) - ( C220 . C221 ) ) ) < C223 by L1157 , TOPMETR:11;
L1159: ( C219 - ( C220 . C221 ) ) <= ( ( C220 . D125 ) - ( C220 . C221 ) ) by L1156 , XREAL_1:9;
L1160: ( C220 . D125 ) >= ( C220 . C221 ) by L1132 , L1156 , XXREAL_0:2;
L1161: ( ( C220 . D125 ) - ( C220 . C221 ) ) >= ( 0 ) by L1160 , XREAL_1:48;
L1162: ( ( C220 . D125 ) - ( C220 . C221 ) ) < C223 by L1161 , L1158 , ABSVALUE:def 1;
L1163: ( C219 - ( C220 . C221 ) ) < C223 by L1162 , L1159 , XXREAL_0:2;
L1164: ( C219 - ( C220 . C221 ) ) >= ( 0 ) by L1132 , XREAL_1:48;
L1165: ( abs ( C219 - ( C220 . C221 ) ) ) < C223 by L1164 , L1163 , ABSVALUE:def 1;
L1166: ( dist (D122 , D127) ) < C223 by L1165 , TOPMETR:11;
L1167: C219 in D124 by L1166 , METRIC_1:11;
L1168: ( min (C219 , ( C220 . D125 )) ) = C219 by L1156 , XXREAL_0:def 9;
L1169: C225 = C219 by L1168 , L1146 , L1107;
thus L1170: thesis by L1169 , L1136 , L1167;
end;
end;
thus L1172: thesis by L1151;
end;
thus L1173: (ex B194 being (Subset of R1) st (B194 is  open & C221 in B194 & ( ( min (C219 , C220) ) .: B194 ) c= C222)) by L1142 , L1140;
end;
suppose L1174: ( C220 . C221 ) > C219;

set D128 = ( ( C220 . C221 ) - C219 );
reconsider D129 = ( Ball (D122 , D128) ) as (Subset of ( R^1 )) by METRIC_1:def 13 , TOPMETR:17;
L1175: D128 > ( 0 ) by L1174 , XREAL_1:50;
L1176: ( dist (D122 , D122) ) < D128 by L1175 , METRIC_1:1;
L1177: D122 in D129 by L1176 , METRIC_1:11;
L1178: (D129 is  open & D120 is_continuous_at C221) by L1126 , TMAP_1:50 , TOPMETR:14 , TOPMETR:def 6;
consider C226 being (Subset of R1) such that L1179: (C226 is  open & C221 in C226) and L1180: ( D120 .: C226 ) c= D129 by L1178 , L1177 , TMAP_1:43;
L1181: ( ( min (C219 , C220) ) .: C226 ) c= C222
proof
let C227 being set;
assume L1182: C227 in ( ( min (C219 , C220) ) .: C226 );
consider R14 being set such that L1183: R14 in ( dom ( min (C219 , C220) ) ) and L1184: R14 in C226 and L1185: C227 = ( ( min (C219 , C220) ) . R14 ) by L1182 , FUNCT_1:def 6;
reconsider D130 = R14 as (Point of R1) by L1183;
reconsider D131 = ( C220 . D130 ) as (Point of ( RealSpace )) by METRIC_1:def 13;
L1186: ( dom ( min (C219 , C220) ) ) = (the carrier of R1) by FUNCT_2:def 1;
L1187: D130 in ( dom C220 ) by L1186 , L1183 , FUNCT_2:def 1;
L1188: ( C220 . D130 ) in ( C220 .: C226 ) by L1187 , L1184 , FUNCT_1:def 6;
L1189: ( dist (D122 , D131) ) < D128 by L1188 , L1180 , METRIC_1:11;
L1190: ( abs ( ( C220 . C221 ) - ( C220 . D130 ) ) ) < D128 by L1189 , TOPMETR:11;
L1191: ( ( C220 . C221 ) + ( - ( C220 . D130 ) ) ) <= ( ( C220 . C221 ) + ( - C219 ) ) by L1190 , ABSVALUE:5;
L1192: ( - ( C220 . D130 ) ) <= ( - C219 ) by L1191 , XREAL_1:6;
L1193: C219 <= ( C220 . D130 ) by L1192 , XREAL_1:24;
L1194: ( min (C219 , ( C220 . D130 )) ) = C219 by L1193 , XXREAL_0:def 9;
L1195: ( min (C219 , ( C220 . C221 )) ) = C219 by L1174 , XXREAL_0:def 9;
L1196: ( ( min (C219 , C220) ) . C221 ) = C219 by L1195 , L1107;
thus L1197: thesis by L1196 , L1130 , L1185 , L1194 , L1107;
end;
thus L1198: (ex B195 being (Subset of R1) st (B195 is  open & C221 in B195 & ( ( min (C219 , C220) ) .: B195 ) c= C222)) by L1181 , L1179;
end;
end;
thus L1200: thesis by L1131;
end;
thus L1201: D121 is_continuous_at C221 by L1128 , TMAP_1:43;
end;
L1202: D121 is  continuous by L1127 , TMAP_1:50;
thus L1203: thesis by L1202 , JORDAN5A:27;
end;
definition
let C228 being set;
let C229 being (Function of [: C228 , C228 :] , ( REAL ));
pred C229 is_a_pseudometric_of C228
means
:L1204: C229 is  Reflexive  symmetric  triangle
;end;
L1206: (for R16 being set holds (for B196 being (Function of [: R16 , R16 :] , ( REAL )) holds (B196 is_a_pseudometric_of R16 iff (for B197 , B198 , B199 being (Element of R16) holds (( B196 . (B197 , B197) ) = ( 0 ) & ( B196 . (B197 , B198) ) = ( B196 . (B198 , B197) ) & ( B196 . (B197 , B199) ) <= ( ( B196 . (B197 , B198) ) + ( B196 . (B198 , B199) ) ))))))
proof
let R16 being set;
let C230 being (Function of [: R16 , R16 :] , ( REAL ));
L1207: (C230 is_a_pseudometric_of R16 iff C230 is  Reflexive  symmetric  triangle) by L1204;
thus L1208: thesis by L1207 , METRIC_1:def 2 , METRIC_1:def 4 , METRIC_1:def 5;
end;
theorem
L1209: (for R16 being set holds (for B200 being (Function of [: R16 , R16 :] , ( REAL )) holds (B200 is_a_pseudometric_of R16 iff (for B201 , B202 , B203 being (Element of R16) holds (( B200 . (B201 , B201) ) = ( 0 ) & ( B200 . (B201 , B203) ) <= ( ( B200 . (B201 , B202) ) + ( B200 . (B203 , B202) ) ))))))
proof
let R16 being set;
let C231 being (Function of [: R16 , R16 :] , ( REAL ));
thus L1210: (C231 is_a_pseudometric_of R16 implies (for B204 , B205 , B206 being (Element of R16) holds (( C231 . (B204 , B204) ) = ( 0 ) & ( C231 . (B204 , B206) ) <= ( ( C231 . (B204 , B205) ) + ( C231 . (B206 , B205) ) ))))
proof
assume L1211: C231 is_a_pseudometric_of R16;
let C232 , C233 , C234 being (Element of R16);
L1212: ( C231 . (C232 , C234) ) <= ( ( C231 . (C232 , C233) ) + ( C231 . (C233 , C234) ) ) by L1211 , L1206;
thus L1213: thesis by L1212 , L1211 , L1206;
end;

thus L1214: ((for B207 , B208 , B209 being (Element of R16) holds (( C231 . (B207 , B207) ) = ( 0 ) & ( C231 . (B207 , B209) ) <= ( ( C231 . (B207 , B208) ) + ( C231 . (B209 , B208) ) ))) implies C231 is_a_pseudometric_of R16)
proof
assume L1215: (for B210 , B211 , B212 being (Element of R16) holds (( C231 . (B210 , B210) ) = ( 0 ) & ( C231 . (B210 , B212) ) <= ( ( C231 . (B210 , B211) ) + ( C231 . (B212 , B211) ) )));
L1216: (for B213 , B214 being (Element of R16) holds ( C231 . (B213 , B214) ) = ( C231 . (B214 , B213) ))
proof
let C235 , C236 being (Element of R16);
L1217: (( C231 . (C236 , C235) ) <= ( ( C231 . (C236 , C236) ) + ( C231 . (C235 , C236) ) ) & ( C231 . (C236 , C236) ) = ( 0 )) by L1215;
L1218: (( C231 . (C235 , C236) ) <= ( ( C231 . (C235 , C235) ) + ( C231 . (C236 , C235) ) ) & ( C231 . (C235 , C235) ) = ( 0 )) by L1215;
thus L1219: thesis by L1218 , L1217 , XXREAL_0:1;
end;
L1220: (for B215 , B216 , B217 being (Element of R16) holds ( C231 . (B215 , B217) ) <= ( ( C231 . (B215 , B216) ) + ( C231 . (B216 , B217) ) ))
proof
let C237 , C238 , C239 being (Element of R16);
L1221: ( C231 . (C237 , C239) ) <= ( ( C231 . (C237 , C238) ) + ( C231 . (C239 , C238) ) ) by L1215;
thus L1222: thesis by L1221 , L1216;
end;
L1223: C231 is  Reflexive  symmetric  triangle by L1220 , L1215 , L1216 , METRIC_1:def 2 , METRIC_1:def 4 , METRIC_1:def 5;
thus L1224: thesis by L1223 , L1204;
end;

end;
L1215: (for B218 being Real holds (for B219 being non  empty set holds (for B220 being (Function of [: B219 , B219 :] , ( REAL )) holds (for B221 , B222 being (Element of B219) holds ( ( min (B218 , B220) ) . (B221 , B222) ) = ( min (B218 , ( B220 . (B221 , B222) )) )))))
proof
let C240 being Real;
let C241 being non  empty set;
let C242 being (Function of [: C241 , C241 :] , ( REAL ));
let C243 , C244 being (Element of C241);
L1216: ( ( min (C240 , C242) ) . (C243 , C244) ) = ( min (C240 , ( C242 . [ C243 , C244 ] )) ) by L1107;
thus L1217: thesis by L1216;
end;
theorem
L1218: (for R16 being set holds (for B223 being (Function of [: R16 , R16 :] , ( REAL )) holds (B223 is_a_pseudometric_of R16 implies (for B224 , B225 being (Element of R16) holds ( B223 . (B224 , B225) ) >= ( 0 )))))
proof
let R16 being set;
let C245 being (Function of [: R16 , R16 :] , ( REAL ));
assume that
L1219: C245 is_a_pseudometric_of R16;
let C246 , C247 being (Element of R16);
L1220: (( C245 . (C246 , C246) ) <= ( ( C245 . (C246 , C247) ) + ( C245 . (C247 , C246) ) ) & ( C245 . (C246 , C246) ) = ( 0 )) by L1219 , L1206;
L1221: ( 0 ) <= ( ( ( C245 . (C246 , C247) ) + ( C245 . (C246 , C247) ) ) / 2 ) by L1220 , L1219 , L1206;
thus L1222: thesis by L1221;
end;
theorem
L1223: (for R1 being non  empty TopSpace holds (for R18 being Real holds (for R22 being (Function of [: (the carrier of R1) , (the carrier of R1) :] , ( REAL )) holds ((R18 > ( 0 ) & R22 is_a_pseudometric_of (the carrier of R1)) implies ( min (R18 , R22) ) is_a_pseudometric_of (the carrier of R1)))))
proof
let R1 being non  empty TopSpace;
let R18 being Real;
let R22 being (Function of [: (the carrier of R1) , (the carrier of R1) :] , ( REAL ));
assume that
L1224: R18 > ( 0 )
and
L1225: R22 is_a_pseudometric_of (the carrier of R1);
L1226:
now
let C248 , C249 , C250 being (Element of R1);
L1227: ( R22 . (C248 , C248) ) = ( 0 ) by L1225 , L1209;
L1228: ( min (R18 , ( R22 . (C248 , C248) )) ) = ( 0 ) by L1227 , L1224 , XXREAL_0:def 9;
thus L1229: ( ( min (R18 , R22) ) . (C248 , C248) ) = ( 0 ) by L1228 , L1215;
thus L1230: ( ( min (R18 , R22) ) . (C248 , C250) ) <= ( ( ( min (R18 , R22) ) . (C248 , C249) ) + ( ( min (R18 , R22) ) . (C250 , C249) ) )
proof
L1231:
now
per cases ;
suppose L1232: ( ( ( min (R18 , R22) ) . (C248 , C249) ) + ( ( min (R18 , R22) ) . (C250 , C249) ) ) >= R18;

L1233: ( min (R18 , ( R22 . (C248 , C250) )) ) <= R18 by XXREAL_0:17;
L1234: ( ( min (R18 , R22) ) . (C248 , C250) ) <= R18 by L1233 , L1215;
thus L1235: thesis by L1234 , L1232 , XXREAL_0:2;
end;
suppose L1236: ( ( ( min (R18 , R22) ) . (C248 , C249) ) + ( ( min (R18 , R22) ) . (C250 , C249) ) ) < R18;

L1237: ( R22 . (C250 , C249) ) >= ( 0 ) by L1225 , L1218;
L1238: ( 0 ) <= ( min (R18 , ( R22 . (C250 , C249) )) ) by L1237 , L1224 , XXREAL_0:20;
L1239: ( 0 ) <= ( ( min (R18 , R22) ) . (C250 , C249) ) by L1238 , L1215;
L1240: ( R22 . (C248 , C249) ) >= ( 0 ) by L1225 , L1218;
L1241: ( 0 ) <= ( min (R18 , ( R22 . (C248 , C249) )) ) by L1240 , L1224 , XXREAL_0:20;
L1242: ( 0 ) <= ( ( min (R18 , R22) ) . (C248 , C249) ) by L1241 , L1215;
L1243: ( ( min (R18 , R22) ) . (C248 , C249) ) < R18 by L1242 , L1236 , L1239 , L1;
L1244: ( min (R18 , ( R22 . (C248 , C249) )) ) < R18 by L1243 , L1215;
L1245: ( min (R18 , ( R22 . (C248 , C249) )) ) = ( R22 . (C248 , C249) ) by L1244 , XXREAL_0:def 9;
L1246: ( ( min (R18 , R22) ) . (C248 , C249) ) = ( R22 . (C248 , C249) ) by L1245 , L1215;
L1247: ( ( min (R18 , R22) ) . (C250 , C249) ) < R18 by L1236 , L1242 , L1239 , L1;
L1248: ( min (R18 , ( R22 . (C250 , C249) )) ) < R18 by L1247 , L1215;
L1249: ( min (R18 , ( R22 . (C250 , C249) )) ) = ( R22 . (C250 , C249) ) by L1248 , XXREAL_0:def 9;
L1250: ( ( min (R18 , R22) ) . (C250 , C249) ) = ( R22 . (C250 , C249) ) by L1249 , L1215;
L1251: (( min (R18 , ( R22 . (C248 , C250) )) ) <= ( R22 . (C248 , C250) ) & ( R22 . (C248 , C250) ) <= ( ( R22 . (C248 , C249) ) + ( R22 . (C250 , C249) ) )) by L1225 , L1209 , XXREAL_0:17;
L1252: ( min (R18 , ( R22 . (C248 , C250) )) ) <= ( ( R22 . (C248 , C249) ) + ( R22 . (C250 , C249) ) ) by L1251 , XXREAL_0:2;
thus L1253: thesis by L1252 , L1246 , L1250 , L1215;
end;
end;
thus L1255: thesis by L1231;
end;

end;
thus L1231: thesis by L1226 , L1209;
end;
theorem
L1232: (for R1 being non  empty TopSpace holds (for R18 being Real holds (for R22 being (Function of [: (the carrier of R1) , (the carrier of R1) :] , ( REAL )) holds ((R18 > ( 0 ) & R22 is_metric_of (the carrier of R1)) implies ( min (R18 , R22) ) is_metric_of (the carrier of R1)))))
proof
let R1 being non  empty TopSpace;
let R18 being Real;
let R22 being (Function of [: (the carrier of R1) , (the carrier of R1) :] , ( REAL ));
assume that
L1233: R18 > ( 0 )
and
L1234: R22 is_metric_of (the carrier of R1);
let C251 , C252 , C253 being (Element of R1);
L1235: (for B226 , B227 , B228 being (Element of R1) holds (( R22 . (B226 , B226) ) = ( 0 ) & ( R22 . (B226 , B227) ) = ( R22 . (B227 , B226) ) & ( R22 . (B226 , B228) ) <= ( ( R22 . (B226 , B227) ) + ( R22 . (B227 , B228) ) ))) by L1234 , PCOMPS_1:def 6;
L1236: R22 is_a_pseudometric_of (the carrier of R1) by L1235 , L1206;
L1237: ( min (R18 , R22) ) is_a_pseudometric_of (the carrier of R1) by L1236 , L1233 , L1223;
L1238: (( ( min (R18 , R22) ) . (C251 , C252) ) = ( 0 ) implies C251 = C252)
proof
assume L1239: ( ( min (R18 , R22) ) . (C251 , C252) ) = ( 0 );
L1240: ( min (R18 , ( R22 . (C251 , C252) )) ) = ( 0 ) by L1239 , L1215;
L1241: ( R22 . (C251 , C252) ) = ( 0 ) by L1240 , L1233 , XXREAL_0:def 9;
thus L1242: thesis by L1241 , L1234 , PCOMPS_1:def 6;
end;
thus L1243: (( ( min (R18 , R22) ) . (C251 , C252) ) = ( 0 ) iff C251 = C252) by L1238 , L1237 , L1206;
thus L1244: thesis by L1237 , L1206;
end;
