:: The Fundamental Logic Structure in Quantum Mechanics
::  by Pawe{\l} Sadowski, Andrzej Trybulec and Konrad Raczkowski
::
:: Received December 18, 1989
:: Copyright (c) 1990-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, SUBSET_1, XBOOLE_0, RPR_1, PROB_1, FUNCT_2, FUNCT_1,
      ZFMISC_1, CARD_1, XXREAL_0, TARSKI, ARYTM_3, RELAT_1, SEQ_2, ORDINAL2,
      EQREL_1, REAL_1, ARYTM_1, STRUCT_0, ORDERS_2, ROBBINS1, ORDERS_1,
      MCART_1, XBOOLEAN, CQC_THE1, ZFREFLE1, RELAT_2, QMAX_1;
 notations TARSKI, XBOOLE_0, ZFMISC_1,
      XTUPLE_0, SUBSET_1, NUMBERS, RELAT_1, RELSET_1,
      RELAT_2, FUNCT_1, REAL_1, FUNCT_2, ORDERS_1, DOMAIN_1, SEQ_2, PROB_1,
      MCART_1, EQREL_1, XXREAL_0, STRUCT_0, ORDERS_2, ROBBINS1;
 constructors DOMAIN_1, XXREAL_0, EQREL_1, SEQ_2, PROB_1, ORDERS_2, ROBBINS1,
      REAL_1, SEQ_1, VALUED_1, RELSET_1, FINSUB_1, COMSEQ_2, XTUPLE_0;
 registrations XBOOLE_0, SUBSET_1, ORDINAL1, RELSET_1, PARTFUN1, NUMBERS,
      MEMBERED, EQREL_1, PROB_1, RELAT_1, FUNCT_1, XTUPLE_0;
 requirements REAL, NUMERALS, SUBSET, BOOLE, ARITHM;
 definitions RELAT_2, ORDERS_1, SUBSET_1, XTUPLE_0;
 theorems ORDERS_1, TARSKI, FUNCT_1, ZFMISC_1, FUNCT_2, PROB_1, MCART_1,
      EQREL_1, RELAT_1, RELSET_1, XBOOLE_0, XREAL_1, XXREAL_0, NAT_1;
 schemes EQREL_1, RELSET_1, FUNCT_2, XBOOLE_0;

begin
definition
let R7 being non  empty set;
let C1 being (SigmaField of R7);
func Probabilities C1 -> set means 
:L1: (for R2 being set holds (R2 in it iff R2 is (Probability of C1)));
existence
proof
defpred S1[ set ] means $1 is (Probability of C1);
consider C2 being set such that L2: (for R2 being set holds (R2 in C2 iff (R2 in ( Funcs (C1 , ( REAL )) ) & S1[ R2 ]))) from XBOOLE_0:sch 1;
take C2;
let R2 being set;
L3: (R2 is (Probability of C1) implies R2 in ( Funcs (C1 , ( REAL )) )) by FUNCT_2:8;
thus L4: thesis by L3 , L2;
end;
uniqueness
proof
let C3 , C4 being set;
assume that
L5: (for R2 being set holds (R2 in C3 iff R2 is (Probability of C1)))
and
L6: (for R2 being set holds (R2 in C4 iff R2 is (Probability of C1)));
L7:
now
let R3 being set;
L8: (R3 in C3 iff R3 is (Probability of C1)) by L5;
thus L9: (R3 in C3 iff R3 in C4) by L8 , L6;
end;
thus L10: thesis by L7 , TARSKI:1;
end;
end;
registration
let R7 being non  empty set;
let C5 being (SigmaField of R7);
cluster ( Probabilities C5 ) -> non  empty;
coherence
proof
set D1 = the (Probability of C5);
L12: D1 in ( Probabilities C5 ) by L1;
thus L13: thesis by L12;
end;
end;
definition
struct QM_Str(# Observables , FStates -> non  empty set , Quantum_Probability -> (Function of [: the Observables , the FStates :] , ( Probabilities ( Borel_Sets ) )) #);
end;
definition
let R11 being QM_Str;
func Obs R11 -> set equals 
(the Observables of R11);
coherence;
func Sts R11 -> set equals 
(the FStates of R11);
coherence;
end;
registration
let R11 being QM_Str;
cluster ( Obs R11 ) -> non  empty;
coherence;
cluster ( Sts R11 ) -> non  empty;
coherence;
end;
definition
let R11 being QM_Str;
let R12 being (Element of ( Obs R11 ));
let R13 being (Element of ( Sts R11 ));
func Meas (R12 , R13) -> (Probability of ( Borel_Sets )) equals 
( (the Quantum_Probability of R11) . [ R12 , R13 ] );
coherence
proof
reconsider D2 = [ R12 , R13 ] as (Element of [: (the Observables of R11) , (the FStates of R11) :]);
L18: ( (the Quantum_Probability of R11) . D2 ) is (Element of ( Probabilities ( Borel_Sets ) ));
thus L19: thesis by L18 , L1;
end;
end;
set D3 = { ( 0 ) };
consider C6 being (Function of ( Borel_Sets ) , ( REAL )) such that L21: (for R10 being (Subset of ( REAL )) holds (R10 in ( Borel_Sets ) implies ((( 0 ) in R10 implies ( C6 . R10 ) = 1) & ((not ( 0 ) in R10) implies ( C6 . R10 ) = ( 0 ))))) by PROB_1:28;
L22: (for R8 being (Event of ( Borel_Sets )) holds ( 0 ) <= ( C6 . R8 ))
proof
let R8 being (Event of ( Borel_Sets ));
L23:
now
per cases ;
suppose L24: ( 0 ) in R8;

L25: ( C6 . R8 ) = 1 by L24 , L21;
thus L26: thesis by L25;
end;
suppose L27: (not ( 0 ) in R8);

thus L28: thesis by L27 , L21;
end;
end;
thus L30: thesis by L23;
end;
L31: ( C6 . ( REAL ) ) = 1
proof
L32: ( [#] ( REAL ) ) in ( Borel_Sets ) by PROB_1:5;
thus L33: thesis by L32 , L21;
end;
L34: (for R8 being (Event of ( Borel_Sets )) holds (for R9 being (Event of ( Borel_Sets )) holds (R8 misses R9 implies ( C6 . ( R8 \/ R9 ) ) = ( ( C6 . R8 ) + ( C6 . R9 ) ))))
proof
let R8 being (Event of ( Borel_Sets ));
let R9 being (Event of ( Borel_Sets ));
assume that
L35: R8 misses R9;
L36:
now
per cases  by L35 , XBOOLE_0:3;
suppose L37: (( 0 ) in R8 & (not ( 0 ) in R9));

L38: ( 0 ) in ( R8 \/ R9 ) by L37 , XBOOLE_0:def 3;
L39: (( C6 . R8 ) = 1 & ( C6 . R9 ) = ( 0 )) by L37 , L21;
thus L40: thesis by L39 , L38 , L21;
end;
suppose L41: ((not ( 0 ) in R8) & ( 0 ) in R9);

L42: ( 0 ) in ( R8 \/ R9 ) by L41 , XBOOLE_0:def 3;
L43: (( C6 . R8 ) = ( 0 ) & ( C6 . R9 ) = 1) by L41 , L21;
thus L44: thesis by L43 , L42 , L21;
end;
suppose L45: ((not ( 0 ) in R8) & (not ( 0 ) in R9));

L46: (not ( 0 ) in ( R8 \/ R9 )) by L45 , XBOOLE_0:def 3;
L47: (( C6 . R8 ) = ( 0 ) & ( C6 . R9 ) = ( 0 )) by L45 , L21;
thus L48: thesis by L47 , L46 , L21;
end;
end;
thus L50: thesis by L36;
end;
L51: (for R15 being (SetSequence of ( Borel_Sets )) holds (R15 is  non-ascending implies (( C6 * R15 ) is  convergent & ( lim ( C6 * R15 ) ) = ( C6 . ( Intersection R15 ) ))))
proof
let R15 being (SetSequence of ( Borel_Sets ));
L52:
now
let R5 being (Element of ( NAT ));
L53: ( dom ( C6 * R15 ) ) = ( NAT ) by FUNCT_2:def 1;
thus L54: ( ( C6 * R15 ) . R5 ) = ( C6 . ( R15 . R5 ) ) by L53 , FUNCT_1:12;
end;
assume L55: R15 is  non-ascending;
L56:
now
per cases ;
suppose L57: (for R5 being (Element of ( NAT )) holds ( 0 ) in ( R15 . R5 ));

reconsider D4 = 1 as Real;
L58: ( rng R15 ) c= ( Borel_Sets ) by RELAT_1:def 19;
L59: ( Intersection R15 ) in ( Borel_Sets ) by L58 , PROB_1:def 6;
L60: ( 0 ) in ( Intersection R15 ) by L57 , PROB_1:13;
L61:
now
let R5 being (Element of ( NAT ));
L62: (( rng R15 ) c= ( Borel_Sets ) & ( R15 . R5 ) in ( rng R15 )) by NAT_1:51 , RELAT_1:def 19;
L63: ( 0 ) in ( R15 . R5 ) by L57;
L64: ( C6 . ( R15 . R5 ) ) = 1 by L63 , L62 , L21;
thus L65: ( ( C6 * R15 ) . R5 ) = 1 by L64 , L52;
end;
L66: (ex R6 being (Element of ( NAT )) st (for R5 being (Element of ( NAT )) holds (R6 <= R5 implies ( ( C6 * R15 ) . R5 ) = D4)))
proof
take ( 0 );
thus L67: thesis by L61;
end;
L68: ( lim ( C6 * R15 ) ) = 1 by L66 , PROB_1:1;
thus L69: thesis by L68 , L66 , L60 , L59 , L21 , PROB_1:1;
end;
suppose L70: (not (for R5 being (Element of ( NAT )) holds ( 0 ) in ( R15 . R5 )));

L71: ( rng R15 ) c= ( Borel_Sets ) by RELAT_1:def 19;
L72: ( Intersection R15 ) in ( Borel_Sets ) by L71 , PROB_1:def 6;
L73: (not ( 0 ) in ( Intersection R15 )) by L70 , PROB_1:13;
L74: (ex R6 being (Element of ( NAT )) st (for R5 being (Element of ( NAT )) holds (R6 <= R5 implies ( ( C6 * R15 ) . R5 ) = ( 0 ))))
proof
consider R6 being (Element of ( NAT )) such that L75: (not ( 0 ) in ( R15 . R6 )) by L70;
take R6;
L76: (for R5 being (Element of ( NAT )) holds (R6 <= R5 implies ( ( C6 * R15 ) . R5 ) = ( 0 )))
proof
let R5 being (Element of ( NAT ));
assume L77: R6 <= R5;
L78: ( R15 . R5 ) c= ( R15 . R6 ) by L77 , L55 , PROB_1:def 4;
L79: (not ( 0 ) in ( R15 . R5 )) by L78 , L75;
L80: (( rng R15 ) c= ( Borel_Sets ) & ( R15 . R5 ) in ( rng R15 )) by NAT_1:51 , RELAT_1:def 19;
L81: ( C6 . ( R15 . R5 ) ) = ( 0 ) by L80 , L79 , L21;
thus L82: thesis by L81 , L52;
end;
thus L83: thesis by L76;
end;
L84: ( lim ( C6 * R15 ) ) = ( 0 ) by L74 , PROB_1:1;
thus L85: thesis by L84 , L74 , L73 , L72 , L21 , PROB_1:1;
end;
end;
thus L87: thesis by L56;
end;
reconsider D5 = C6 as (Probability of ( Borel_Sets )) by L51 , L22 , L31 , L34 , PROB_1:def 8;
set D6 = { [ [ ( 0 ) , ( 0 ) ] , D5 ] };
L88: ( dom D6 ) = { [ ( 0 ) , ( 0 ) ] } by RELAT_1:9;
L89: ( dom D6 ) = [: D3 , D3 :] by L88 , ZFMISC_1:29;
L90: (( rng D6 ) = { D5 } & D5 in ( Probabilities ( Borel_Sets ) )) by L1 , RELAT_1:9;
L91: ( rng D6 ) c= ( Probabilities ( Borel_Sets ) ) by L90 , ZFMISC_1:31;
reconsider D7 = D6 as (Function of [: D3 , D3 :] , ( Probabilities ( Borel_Sets ) )) by L91 , L89 , FUNCT_2:def 1 , RELSET_1:4;
L92:
now
thus L93: (for B1 , B2 being (Element of ( Obs QM_Str (# D3 , D3 , D7 #) )) holds ((for B3 being (Element of ( Sts QM_Str (# D3 , D3 , D7 #) )) holds ( Meas (B1 , B3) ) = ( Meas (B2 , B3) )) implies B1 = B2))
proof
let C7 , C8 being (Element of ( Obs QM_Str (# D3 , D3 , D7 #) ));
L94: C7 = ( 0 ) by TARSKI:def 1;
thus L95: thesis by L94 , TARSKI:def 1;
end;

thus L96: (for B4 , B5 being (Element of ( Sts QM_Str (# D3 , D3 , D7 #) )) holds ((for B6 being (Element of ( Obs QM_Str (# D3 , D3 , D7 #) )) holds ( Meas (B6 , B4) ) = ( Meas (B6 , B5) )) implies B4 = B5))
proof
let C9 , C10 being (Element of ( Sts QM_Str (# D3 , D3 , D7 #) ));
L97: C9 = ( 0 ) by TARSKI:def 1;
thus L98: thesis by L97 , TARSKI:def 1;
end;

thus L99: (for B7 , B8 being (Element of ( Sts QM_Str (# D3 , D3 , D7 #) )) holds (for B9 being Real holds ((( 0 ) <= B9 & B9 <= 1) implies (ex B10 being (Element of ( Sts QM_Str (# D3 , D3 , D7 #) )) st (for B11 being (Element of ( Obs QM_Str (# D3 , D3 , D7 #) )) holds (for R14 being (Event of ( Borel_Sets )) holds ( ( Meas (B11 , B10) ) . R14 ) = ( ( B9 * ( ( Meas (B11 , B7) ) . R14 ) ) + ( ( 1 - B9 ) * ( ( Meas (B11 , B8) ) . R14 ) ) )))))))
proof
let C11 , C12 being (Element of ( Sts QM_Str (# D3 , D3 , D7 #) ));
let C13 being Real;
assume L100: (( 0 ) <= C13 & C13 <= 1);
take C12;
let C14 being (Element of ( Obs QM_Str (# D3 , D3 , D7 #) ));
let R14 being (Event of ( Borel_Sets ));
L101: (C11 = ( 0 ) & C12 = ( 0 )) by TARSKI:def 1;
thus L102: thesis by L101;
end;

end;
definition
let C15 being QM_Str;
attr C15 is  Quantum_Mechanics-like
means
:L100: ((for B12 , B13 being (Element of ( Obs C15 )) holds ((for B14 being (Element of ( Sts C15 )) holds ( Meas (B12 , B14) ) = ( Meas (B13 , B14) )) implies B12 = B13)) & (for B15 , B16 being (Element of ( Sts C15 )) holds ((for B17 being (Element of ( Obs C15 )) holds ( Meas (B17 , B15) ) = ( Meas (B17 , B16) )) implies B15 = B16)) & (for B18 , B19 being (Element of ( Sts C15 )) holds (for B20 being Real holds ((( 0 ) <= B20 & B20 <= 1) implies (ex B21 being (Element of ( Sts C15 )) st (for B22 being (Element of ( Obs C15 )) holds (for R14 being (Event of ( Borel_Sets )) holds ( ( Meas (B22 , B21) ) . R14 ) = ( ( B20 * ( ( Meas (B22 , B18) ) . R14 ) ) + ( ( 1 - B20 ) * ( ( Meas (B22 , B19) ) . R14 ) ) ))))))));
end;
registration
cluster  strict  Quantum_Mechanics-like for QM_Str;
existence
proof
L102: QM_Str (# D3 , D3 , D7 #) is  Quantum_Mechanics-like by L100 , L92;
thus L103: thesis by L102;
end;
end;
definition
mode Quantum_Mechanics
 is  Quantum_Mechanics-like QM_Str;
end;
definition
struct (RelStr , ComplStr) OrthoRelStr(# carrier -> set , InternalRel -> (Relation of the carrier) , Compl -> (Function of the carrier , the carrier) #);
end;
definition
let R1 being set;
let R19 being (Function of R1 , R1);
pred R19 is_an_involution 
means
(for R18 being (Element of R1) holds ( R19 . ( R19 . R18 ) ) = R18)
;end;
definition
let C16 being OrthoRelStr;
pred C16 is_a_Quantum_Logic 
means
:L108: ((the InternalRel of C16) partially_orders (the carrier of C16) & (the Compl of C16) is_an_involution  & (for B23 , B24 being (Element of C16) holds ([ B23 , B24 ] in (the InternalRel of C16) implies [ ( (the Compl of C16) . B24 ) , ( (the Compl of C16) . B23 ) ] in (the InternalRel of C16))))
;end;
definition
let R16 being Quantum_Mechanics;
func Prop R16 -> set equals 
[: ( Obs R16 ) , ( Borel_Sets ) :];
coherence;
end;
registration
let R16 being Quantum_Mechanics;
cluster ( Prop R16 ) -> non  empty;
coherence;
end;
definition
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
redefine func R20 `1 -> (Element of ( Obs R16 ));

coherence by MCART_1:10;
redefine func R20 `2 -> (Event of ( Borel_Sets ));

coherence by MCART_1:10;
end;
theorem
L113: (for R16 being Quantum_Mechanics holds (for R17 being (Element of ( Sts R16 )) holds (for R20 being (Element of ( Prop R16 )) holds (for R14 being (Event of ( Borel_Sets )) holds (R14 = ( ( R20 `2 ) ` ) implies ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) = ( 1 - ( ( Meas (( R20 `1 ) , R17) ) . R14 ) ))))))
proof
let R16 being Quantum_Mechanics;
let R17 being (Element of ( Sts R16 ));
let R20 being (Element of ( Prop R16 ));
let R14 being (Event of ( Borel_Sets ));
assume that
L114: R14 = ( ( R20 `2 ) ` );
L115: (( [#] ( Borel_Sets ) ) = ( REAL ) & ( ( REAL ) \ R14 ) = ( R14 ` )) by PROB_1:def 7;
thus L116: thesis by L115 , L114 , PROB_1:32;
end;
definition
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
func 'not' R20 -> (Element of ( Prop R16 )) equals 
[ ( R20 `1 ) , ( ( R20 `2 ) ` ) ];
coherence
proof
reconsider D8 = ( ( R20 `2 ) ` ) as (Event of ( Borel_Sets )) by PROB_1:20;
L117: D8 in ( Borel_Sets );
thus L118: thesis by L117 , ZFMISC_1:87;
end;
involutiveness
proof
let C17 , C18 being (Element of ( Prop R16 ));
assume L119: C17 = [ ( C18 `1 ) , ( ( C18 `2 ) ` ) ];
thus L120: C18 = [ ( C18 `1 ) , ( ( ( C18 `2 ) ` ) ` ) ] by MCART_1:21
.= [ ( C17 `1 ) , ( ( ( C18 `2 ) ` ) ` ) ] by L119 , MCART_1:7
.= [ ( C17 `1 ) , ( ( C17 `2 ) ` ) ] by L119 , MCART_1:7;
end;
end;
definition
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
pred R20 |- R21
means
:L122: (for R17 being (Element of ( Sts R16 )) holds ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) <= ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ))
;reflexivity
;
end;
definition
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
pred R20 <==> R21
means
:L124: (R20 |- R21 & R21 |- R20)
;reflexivity
;
symmetry
;
end;
theorem
L126: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds (R20 <==> R21 iff (for R17 being (Element of ( Sts R16 )) holds ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) = ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ))))))
proof
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
thus L127: (R20 <==> R21 implies (for R17 being (Element of ( Sts R16 )) holds ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) = ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) )))
proof
assume L128: R20 <==> R21;
let R17 being (Element of ( Sts R16 ));
L129: R21 |- R20 by L128 , L124;
L130: ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ) <= ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) by L129 , L122;
L131: R20 |- R21 by L128 , L124;
L132: ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) <= ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ) by L131 , L122;
thus L133: thesis by L132 , L130 , XXREAL_0:1;
end;

assume L134: (for R17 being (Element of ( Sts R16 )) holds ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) = ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ));
thus L135: R20 |- R21
proof
let R17 being (Element of ( Sts R16 ));
thus L136: thesis by L134;
end;

let R17 being (Element of ( Sts R16 ));
thus L137: thesis by L134;
end;
theorem
L138: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds R20 |- R20));
theorem
L139: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds (for R22 being (Element of ( Prop R16 )) holds ((R20 |- R21 & R21 |- R22) implies R20 |- R22)))))
proof
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
let R22 being (Element of ( Prop R16 ));
assume L140: (R20 |- R21 & R21 |- R22);
let R17 being (Element of ( Sts R16 ));
L141: (( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) <= ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ) & ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ) <= ( ( Meas (( R22 `1 ) , R17) ) . ( R22 `2 ) )) by L140 , L122;
thus L142: thesis by L141 , XXREAL_0:2;
end;
theorem
L143: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds R20 <==> R20));
theorem
L144: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds (R20 <==> R21 implies R21 <==> R20))));
theorem
L145: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds (for R22 being (Element of ( Prop R16 )) holds ((R20 <==> R21 & R21 <==> R22) implies R20 <==> R22)))))
proof
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
let R22 being (Element of ( Prop R16 ));
assume L146: (R20 |- R21 & R21 |- R20 & R21 |- R22 & R22 |- R21);
thus L147: (R20 |- R22 & R22 |- R20) by L146 , L139;
end;
canceled 1;
theorem
L148: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds (R20 |- R21 implies ( 'not' R21 ) |- ( 'not' R20 )))))
proof
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
assume L149: R20 |- R21;
let R17 being (Element of ( Sts R16 ));
reconsider D9 = ( ( R21 `2 ) ` ) as (Event of ( Borel_Sets )) by PROB_1:20;
reconsider D10 = ( ( R20 `2 ) ` ) as (Event of ( Borel_Sets )) by PROB_1:20;
set D11 = ( ( Meas (( R20 `1 ) , R17) ) . D10 );
set D12 = ( ( Meas (( R21 `1 ) , R17) ) . D9 );
L150: (( - ( 1 - D11 ) ) = ( D11 - 1 ) & ( - ( 1 - D12 ) ) = ( D12 - 1 ));
L151: (( ( 'not' R20 ) `1 ) = ( R20 `1 ) & ( ( 'not' R20 ) `2 ) = ( ( R20 `2 ) ` )) by MCART_1:7;
L152: (( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ) = ( 1 - D12 ) & ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) = ( 1 - D11 )) by L113;
L153: (( ( 'not' R21 ) `1 ) = ( R21 `1 ) & ( ( 'not' R21 ) `2 ) = ( ( R21 `2 ) ` )) by MCART_1:7;
L154: ( ( Meas (( R20 `1 ) , R17) ) . ( R20 `2 ) ) <= ( ( Meas (( R21 `1 ) , R17) ) . ( R21 `2 ) ) by L149 , L122;
L155: ( D12 - 1 ) <= ( D11 - 1 ) by L154 , L152 , L150 , XREAL_1:24;
thus L156: thesis by L155 , L153 , L151 , XREAL_1:9;
end;
definition
let R16 being Quantum_Mechanics;
func PropRel R16 -> (Equivalence_Relation of ( Prop R16 )) means 
:L157: (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ([ R20 , R21 ] in it iff R20 <==> R21)));
existence
proof
defpred S2[ set , set ] means (ex R20 being (Element of ( Prop R16 )) st (ex R21 being (Element of ( Prop R16 )) st (R20 = $1 & R21 = $2 & R20 <==> R21)));
L158: (for R2 being set holds (for R3 being set holds (S2[ R2 , R3 ] implies S2[ R3 , R2 ])));
L159: (for R2 being set holds (for R3 being set holds (for R4 being set holds ((S2[ R2 , R3 ] & S2[ R3 , R4 ]) implies S2[ R2 , R4 ])))) by L145;
L160: (for R2 being set holds (R2 in ( Prop R16 ) implies S2[ R2 , R2 ]));
consider C19 being (Equivalence_Relation of ( Prop R16 )) such that L161: (for R2 being set holds (for R3 being set holds ([ R2 , R3 ] in C19 iff (R2 in ( Prop R16 ) & R3 in ( Prop R16 ) & S2[ R2 , R3 ])))) from EQREL_1:sch 1(L160 , L158 , L159);
take C19;
L162: (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ([ R20 , R21 ] in C19 iff R20 <==> R21)))
proof
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
thus L163: ([ R20 , R21 ] in C19 implies R20 <==> R21)
proof
assume L164: [ R20 , R21 ] in C19;
L165: (ex R23 being (Element of ( Prop R16 )) st (ex R24 being (Element of ( Prop R16 )) st (R23 = R20 & R24 = R21 & R23 <==> R24))) by L164 , L161;
thus L166: thesis by L165;
end;

assume L167: R20 <==> R21;
thus L168: thesis by L167 , L161;
end;
thus L169: thesis by L162;
end;
uniqueness
proof
let C20 , C21 being (Equivalence_Relation of ( Prop R16 ));
assume that
L170: (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ([ R20 , R21 ] in C20 iff R20 <==> R21)))
and
L171: (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ([ R20 , R21 ] in C21 iff R20 <==> R21)));
L172:
now
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
L173: ([ R20 , R21 ] in C20 iff R20 <==> R21) by L170;
thus L174: ([ R20 , R21 ] in C20 iff [ R20 , R21 ] in C21) by L173 , L171;
end;
L175: (for R2 being set holds (for R3 being set holds ([ R2 , R3 ] in C20 iff [ R2 , R3 ] in C21)))
proof
let R2 being set;
let R3 being set;
thus L176: ([ R2 , R3 ] in C20 implies [ R2 , R3 ] in C21)
proof
assume L177: [ R2 , R3 ] in C20;
L178: (R2 is (Element of ( Prop R16 )) & R3 is (Element of ( Prop R16 ))) by L177 , ZFMISC_1:87;
thus L179: thesis by L178 , L172 , L177;
end;

assume L180: [ R2 , R3 ] in C21;
L181: (R2 is (Element of ( Prop R16 )) & R3 is (Element of ( Prop R16 ))) by L180 , ZFMISC_1:87;
thus L182: thesis by L181 , L172 , L180;
end;
thus L183: thesis by L175 , RELAT_1:def 2;
end;
end;
theorem
L185: (for R16 being Quantum_Mechanics holds (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ((R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) )) implies (for B25 , B26 , B27 , B28 being (Element of ( Prop R16 )) holds ((B25 in R25 & B26 in R25 & B27 in R26 & B28 in R26 & B25 |- B27) implies B26 |- B28))))))
proof
let R16 being Quantum_Mechanics;
let R25 being (Subset of ( Prop R16 ));
let R26 being (Subset of ( Prop R16 ));
assume that
L186: R25 in ( Class ( PropRel R16 ) )
and
L187: R26 in ( Class ( PropRel R16 ) );
let C22 , C23 , C24 , C25 being (Element of ( Prop R16 ));
assume that
L188: (C22 in R25 & C23 in R25)
and
L189: (C24 in R26 & C25 in R26);
assume L190: C22 |- C24;
let R17 being (Element of ( Sts R16 ));
L191: (ex R3 being set st (R3 in ( Prop R16 ) & R26 = ( Class (( PropRel R16 ) , R3) ))) by L187 , EQREL_1:def 3;
L192: [ C24 , C25 ] in ( PropRel R16 ) by L191 , L189 , EQREL_1:22;
L193: C24 <==> C25 by L192 , L157;
L194: ( ( Meas (( C24 `1 ) , R17) ) . ( C24 `2 ) ) = ( ( Meas (( C25 `1 ) , R17) ) . ( C25 `2 ) ) by L193 , L126;
L195: (ex R2 being set st (R2 in ( Prop R16 ) & R25 = ( Class (( PropRel R16 ) , R2) ))) by L186 , EQREL_1:def 3;
L196: [ C22 , C23 ] in ( PropRel R16 ) by L195 , L188 , EQREL_1:22;
L197: C22 <==> C23 by L196 , L157;
L198: ( ( Meas (( C22 `1 ) , R17) ) . ( C22 `2 ) ) = ( ( Meas (( C23 `1 ) , R17) ) . ( C23 `2 ) ) by L197 , L126;
thus L199: thesis by L198 , L190 , L194 , L122;
end;
definition
let R16 being Quantum_Mechanics;
func OrdRel R16 -> (Relation of ( Class ( PropRel R16 ) )) means 
:L200: (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ([ R25 , R26 ] in it iff (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21)))))));
existence
proof
defpred S3[ set , set ] means (ex R25 being (Subset of ( Prop R16 )) st (ex R26 being (Subset of ( Prop R16 )) st ($1 = R25 & $2 = R26 & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21))))));
consider C26 being (Relation of ( Class ( PropRel R16 ) ) , ( Class ( PropRel R16 ) )) such that L201: (for R2 being set holds (for R3 being set holds ([ R2 , R3 ] in C26 iff (R2 in ( Class ( PropRel R16 ) ) & R3 in ( Class ( PropRel R16 ) ) & S3[ R2 , R3 ])))) from RELSET_1:sch 1;
L202: (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ([ R25 , R26 ] in C26 iff (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21)))))))
proof
let R25 being (Subset of ( Prop R16 ));
let R26 being (Subset of ( Prop R16 ));
thus L203: ([ R25 , R26 ] in C26 implies (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21)))))
proof
assume L204: [ R25 , R26 ] in C26;
L205: (ex B29 , B30 being (Subset of ( Prop R16 )) st (R25 = B29 & R26 = B30 & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in B29 & R21 in B30) implies R20 |- R21))))) by L204 , L201;
thus L206: thesis by L205 , L201 , L204;
end;

assume L207: (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21))));
thus L208: thesis by L207 , L201;
end;
thus L209: thesis by L202;
end;
uniqueness
proof
let C27 , C28 being (Relation of ( Class ( PropRel R16 ) ));
assume that
L210: (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ([ R25 , R26 ] in C27 iff (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21)))))))
and
L211: (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ([ R25 , R26 ] in C28 iff (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21)))))));
L212:
now
let R25 being (Subset of ( Prop R16 ));
let R26 being (Subset of ( Prop R16 ));
L213: ([ R25 , R26 ] in C27 iff (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ) & (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((R20 in R25 & R21 in R26) implies R20 |- R21))))) by L210;
thus L214: ([ R25 , R26 ] in C27 iff [ R25 , R26 ] in C28) by L213 , L211;
end;
L215: (for R2 being set holds (for R3 being set holds ([ R2 , R3 ] in C27 iff [ R2 , R3 ] in C28)))
proof
let R2 being set;
let R3 being set;
thus L216: ([ R2 , R3 ] in C27 implies [ R2 , R3 ] in C28)
proof
assume L217: [ R2 , R3 ] in C27;
L218: (R2 in ( Class ( PropRel R16 ) ) & R3 in ( Class ( PropRel R16 ) )) by L217 , ZFMISC_1:87;
thus L219: thesis by L218 , L212 , L217;
end;

assume L220: [ R2 , R3 ] in C28;
L221: (R2 in ( Class ( PropRel R16 ) ) & R3 in ( Class ( PropRel R16 ) )) by L220 , ZFMISC_1:87;
thus L222: thesis by L221 , L212 , L220;
end;
thus L223: thesis by L215 , RELAT_1:def 2;
end;
end;
theorem
L225: (for R16 being Quantum_Mechanics holds (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds (R20 |- R21 iff [ ( Class (( PropRel R16 ) , R20) ) , ( Class (( PropRel R16 ) , R21) ) ] in ( OrdRel R16 )))))
proof
let R16 being Quantum_Mechanics;
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
L226: [ R20 , R20 ] in ( PropRel R16 ) by L157;
L227: R20 in ( Class (( PropRel R16 ) , R20) ) by L226 , EQREL_1:19;
L228: [ R21 , R21 ] in ( PropRel R16 ) by L157;
L229: R21 in ( Class (( PropRel R16 ) , R21) ) by L228 , EQREL_1:19;
L230: (( Class (( PropRel R16 ) , R20) ) in ( Class ( PropRel R16 ) ) & ( Class (( PropRel R16 ) , R21) ) in ( Class ( PropRel R16 ) )) by EQREL_1:def 3;
thus L231: (R20 |- R21 implies [ ( Class (( PropRel R16 ) , R20) ) , ( Class (( PropRel R16 ) , R21) ) ] in ( OrdRel R16 ))
proof
assume L232: R20 |- R21;
L233: (for R23 being (Element of ( Prop R16 )) holds (for R24 being (Element of ( Prop R16 )) holds ((R23 in ( Class (( PropRel R16 ) , R20) ) & R24 in ( Class (( PropRel R16 ) , R21) )) implies R23 |- R24))) by L232 , L227 , L229 , L230 , L185;
thus L234: thesis by L233 , L230 , L200;
end;

thus L235: thesis by L227 , L229 , L200;
end;
theorem
L236: (for R16 being Quantum_Mechanics holds (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ((R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) )) implies (for R23 being (Element of ( Prop R16 )) holds (for R24 being (Element of ( Prop R16 )) holds ((R23 in R25 & R24 in R25 & ( 'not' R23 ) in R26) implies ( 'not' R24 ) in R26)))))))
proof
let R16 being Quantum_Mechanics;
let R25 being (Subset of ( Prop R16 ));
let R26 being (Subset of ( Prop R16 ));
assume that
L237: R25 in ( Class ( PropRel R16 ) )
and
L238: R26 in ( Class ( PropRel R16 ) );
consider R3 being set such that L239: R3 in ( Prop R16 ) and L240: R26 = ( Class (( PropRel R16 ) , R3) ) by L238 , EQREL_1:def 3;
let R23 being (Element of ( Prop R16 ));
let R24 being (Element of ( Prop R16 ));
assume that
L241: (R23 in R25 & R24 in R25)
and
L242: ( 'not' R23 ) in R26;
L243: (ex R2 being set st (R2 in ( Prop R16 ) & R25 = ( Class (( PropRel R16 ) , R2) ))) by L237 , EQREL_1:def 3;
L244: [ R23 , R24 ] in ( PropRel R16 ) by L243 , L241 , EQREL_1:22;
L245: R23 <==> R24 by L244 , L157;
L246:
now
reconsider D13 = ( ( R24 `2 ) ` ) , D14 = ( ( R23 `2 ) ` ) as (Event of ( Borel_Sets )) by PROB_1:20;
let R17 being (Element of ( Sts R16 ));
set D15 = ( ( Meas (( R23 `1 ) , R17) ) . D14 );
set D16 = ( ( Meas (( R24 `1 ) , R17) ) . D13 );
L247: (( ( 'not' R23 ) `1 ) = ( R23 `1 ) & ( ( 'not' R23 ) `2 ) = ( ( R23 `2 ) ` )) by MCART_1:7;
L248: ( ( 'not' R24 ) `1 ) = ( R24 `1 ) by MCART_1:7;
L249: ( 1 - D15 ) = ( ( Meas (( R23 `1 ) , R17) ) . ( R23 `2 ) ) by L113
.= ( ( Meas (( R24 `1 ) , R17) ) . ( R24 `2 ) ) by L245 , L126
.= ( 1 - D16 ) by L113;
thus L250: ( ( Meas (( ( 'not' R23 ) `1 ) , R17) ) . ( ( 'not' R23 ) `2 ) ) = ( ( Meas (( ( 'not' R24 ) `1 ) , R17) ) . ( ( 'not' R24 ) `2 ) ) by L249 , L247 , L248 , MCART_1:7;
end;
L251: ( 'not' R23 ) <==> ( 'not' R24 ) by L246 , L126;
reconsider D17 = R3 as (Element of ( Prop R16 )) by L239;
L252: [ ( 'not' R23 ) , D17 ] in ( PropRel R16 ) by L240 , L242 , EQREL_1:19;
L253: ( 'not' R23 ) <==> D17 by L252 , L157;
L254: D17 <==> ( 'not' R24 ) by L253 , L251 , L145;
L255: [ ( 'not' R24 ) , D17 ] in ( PropRel R16 ) by L254 , L157;
thus L256: thesis by L255 , L240 , EQREL_1:19;
end;
theorem
L257: (for R16 being Quantum_Mechanics holds (for R25 being (Subset of ( Prop R16 )) holds (for R26 being (Subset of ( Prop R16 )) holds ((R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) )) implies (for R20 being (Element of ( Prop R16 )) holds (for R21 being (Element of ( Prop R16 )) holds ((( 'not' R20 ) in R26 & ( 'not' R21 ) in R26 & R20 in R25) implies R21 in R25)))))))
proof
let R16 being Quantum_Mechanics;
let R25 being (Subset of ( Prop R16 ));
let R26 being (Subset of ( Prop R16 ));
assume that
L258: (R25 in ( Class ( PropRel R16 ) ) & R26 in ( Class ( PropRel R16 ) ));
let R20 being (Element of ( Prop R16 ));
let R21 being (Element of ( Prop R16 ));
L259: (( 'not' ( 'not' R20 ) ) = R20 & ( 'not' ( 'not' R21 ) ) = R21);
thus L260: thesis by L259 , L258 , L236;
end;
definition
let R16 being Quantum_Mechanics;
func InvRel R16 -> (Function of ( Class ( PropRel R16 ) ) , ( Class ( PropRel R16 ) )) means 
:L261: (for R20 being (Element of ( Prop R16 )) holds ( it . ( Class (( PropRel R16 ) , R20) ) ) = ( Class (( PropRel R16 ) , ( 'not' R20 )) ));
existence
proof
defpred S4[ set , set ] means (for R20 being (Element of ( Prop R16 )) holds ($1 = ( Class (( PropRel R16 ) , R20) ) implies $2 = ( Class (( PropRel R16 ) , ( 'not' R20 )) )));
L262: (for R2 being set holds (R2 in ( Class ( PropRel R16 ) ) implies (ex R3 being set st (R3 in ( Class ( PropRel R16 ) ) & S4[ R2 , R3 ]))))
proof
let R2 being set;
assume L263: R2 in ( Class ( PropRel R16 ) );
consider R21 being (Element of ( Prop R16 )) such that L264: R2 = ( Class (( PropRel R16 ) , R21) ) by L263 , EQREL_1:36;
reconsider D18 = ( Class (( PropRel R16 ) , ( 'not' R21 )) ) as set;
take D18;
thus L265: D18 in ( Class ( PropRel R16 ) ) by EQREL_1:def 3;
let R20 being (Element of ( Prop R16 ));
assume L266: R2 = ( Class (( PropRel R16 ) , R20) );
reconsider D19 = R2 as (Subset of ( Prop R16 )) by L266;
L267: R21 in D19 by L264 , EQREL_1:20;
reconsider D20 = D18 as (Subset of ( Prop R16 ));
L268: ( 'not' R21 ) in D20 by EQREL_1:20;
L269: R20 in D19 by L266 , EQREL_1:20;
L270: ( 'not' R20 ) in D20 by L269 , L263 , L265 , L267 , L268 , L236;
thus L271: thesis by L270 , EQREL_1:23;
end;
consider C29 being (Function of ( Class ( PropRel R16 ) ) , ( Class ( PropRel R16 ) )) such that L272: (for R2 being set holds (R2 in ( Class ( PropRel R16 ) ) implies S4[ R2 , ( C29 . R2 ) ])) from FUNCT_2:sch 1(L262);
take C29;
let R20 being (Element of ( Prop R16 ));
L273: ( Class (( PropRel R16 ) , R20) ) in ( Class ( PropRel R16 ) ) by EQREL_1:def 3;
thus L274: thesis by L273 , L272;
end;
uniqueness
proof
let C30 , C31 being (Function of ( Class ( PropRel R16 ) ) , ( Class ( PropRel R16 ) ));
assume that
L275: (for R20 being (Element of ( Prop R16 )) holds ( C30 . ( Class (( PropRel R16 ) , R20) ) ) = ( Class (( PropRel R16 ) , ( 'not' R20 )) ))
and
L276: (for R20 being (Element of ( Prop R16 )) holds ( C31 . ( Class (( PropRel R16 ) , R20) ) ) = ( Class (( PropRel R16 ) , ( 'not' R20 )) ));
L277:
now
let R2 being set;
assume L278: R2 in ( Class ( PropRel R16 ) );
consider R20 being (Element of ( Prop R16 )) such that L279: R2 = ( Class (( PropRel R16 ) , R20) ) by L278 , EQREL_1:36;
L280: ( C30 . R2 ) = ( Class (( PropRel R16 ) , ( 'not' R20 )) ) by L275 , L279;
thus L281: ( C30 . R2 ) = ( C31 . R2 ) by L280 , L276 , L279;
end;
thus L282: thesis by L277 , FUNCT_2:12;
end;
end;
theorem
L284: (for R16 being Quantum_Mechanics holds OrthoRelStr (# ( Class ( PropRel R16 ) ) , ( OrdRel R16 ) , ( InvRel R16 ) #) is_a_Quantum_Logic )
proof
let R16 being Quantum_Mechanics;
L285: ( OrdRel R16 ) is_transitive_in ( Class ( PropRel R16 ) )
proof
let R2 being set;
let R3 being set;
let R4 being set;
assume that
L286: R2 in ( Class ( PropRel R16 ) )
and
L287: R3 in ( Class ( PropRel R16 ) )
and
L288: R4 in ( Class ( PropRel R16 ) )
and
L289: ([ R2 , R3 ] in ( OrdRel R16 ) & [ R3 , R4 ] in ( OrdRel R16 ));
consider R20 being (Element of ( Prop R16 )) such that L290: R2 = ( Class (( PropRel R16 ) , R20) ) by L286 , EQREL_1:36;
consider R22 being (Element of ( Prop R16 )) such that L291: R4 = ( Class (( PropRel R16 ) , R22) ) by L288 , EQREL_1:36;
consider R21 being (Element of ( Prop R16 )) such that L292: R3 = ( Class (( PropRel R16 ) , R21) ) by L287 , EQREL_1:36;
L293: ((R20 |- R21 & R21 |- R22) implies R20 |- R22) by L139;
thus L294: thesis by L293 , L289 , L290 , L292 , L291 , L225;
end;
L295: ( OrdRel R16 ) is_antisymmetric_in ( Class ( PropRel R16 ) )
proof
let R2 being set;
let R3 being set;
assume that
L296: R2 in ( Class ( PropRel R16 ) )
and
L297: R3 in ( Class ( PropRel R16 ) )
and
L298: ([ R2 , R3 ] in ( OrdRel R16 ) & [ R3 , R2 ] in ( OrdRel R16 ));
consider R20 being (Element of ( Prop R16 )) such that L299: R2 = ( Class (( PropRel R16 ) , R20) ) by L296 , EQREL_1:36;
consider R21 being (Element of ( Prop R16 )) such that L300: R3 = ( Class (( PropRel R16 ) , R21) ) by L297 , EQREL_1:36;
L301: (R20 <==> R21 implies [ R20 , R21 ] in ( PropRel R16 )) by L157;
L302: ((R20 |- R21 & R21 |- R20) implies R20 <==> R21) by L124;
thus L303: thesis by L302 , L298 , L299 , L300 , L301 , L225 , EQREL_1:35;
end;
L304: (for B31 , B32 being (Element of ( Class ( PropRel R16 ) )) holds ([ B31 , B32 ] in ( OrdRel R16 ) implies [ ( ( InvRel R16 ) . B32 ) , ( ( InvRel R16 ) . B31 ) ] in ( OrdRel R16 )))
proof
let C32 , C33 being (Element of ( Class ( PropRel R16 ) ));
consider R20 being (Element of ( Prop R16 )) such that L305: C32 = ( Class (( PropRel R16 ) , R20) ) by EQREL_1:36;
consider R21 being (Element of ( Prop R16 )) such that L306: C33 = ( Class (( PropRel R16 ) , R21) ) by EQREL_1:36;
L307: (R20 |- R21 implies ( 'not' R21 ) |- ( 'not' R20 )) by L148;
L308: (( ( InvRel R16 ) . ( Class (( PropRel R16 ) , R20) ) ) = ( Class (( PropRel R16 ) , ( 'not' R20 )) ) & ( ( InvRel R16 ) . ( Class (( PropRel R16 ) , R21) ) ) = ( Class (( PropRel R16 ) , ( 'not' R21 )) )) by L261;
thus L309: thesis by L308 , L305 , L306 , L307 , L225;
end;
L310: ( InvRel R16 ) is_an_involution 
proof
let C34 being (Element of ( Class ( PropRel R16 ) ));
consider R20 being (Element of ( Prop R16 )) such that L311: C34 = ( Class (( PropRel R16 ) , R20) ) by EQREL_1:36;
L312: ( ( InvRel R16 ) . ( ( InvRel R16 ) . C34 ) ) = ( ( InvRel R16 ) . ( Class (( PropRel R16 ) , ( 'not' R20 )) ) ) by L311 , L261
.= ( Class (( PropRel R16 ) , ( 'not' ( 'not' R20 ) )) ) by L261;
thus L313: thesis by L312 , L311;
end;
L314: ( OrdRel R16 ) is_reflexive_in ( Class ( PropRel R16 ) )
proof
let R2 being set;
assume L315: R2 in ( Class ( PropRel R16 ) );
L316: (ex R20 being (Element of ( Prop R16 )) st R2 = ( Class (( PropRel R16 ) , R20) )) by L315 , EQREL_1:36;
thus L317: thesis by L316 , L225;
end;
L318: ( OrdRel R16 ) partially_orders ( Class ( PropRel R16 ) ) by L314 , L285 , L295 , ORDERS_1:def 7;
thus L319: thesis by L318 , L310 , L304 , L108;
end;
