:: Ramsey's Theorem
::  by Marco Riccardi
::
:: Received April 18, 2008
:: Copyright (c) 2008-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, ORDINAL1, FUNCT_1, SUBSET_1, EQREL_1, GROUP_10, TARSKI,
      FINSET_1, XBOOLE_0, CARD_1, RELAT_1, FUNCT_2, ARYTM_1, ARYTM_3, XXREAL_0,
      NAT_1, FINSEQ_1, CARD_3, RAMSEY_1;
 notations TARSKI, XBOOLE_0, SUBSET_1, XCMPLX_0, XXREAL_0, RELAT_1, RELSET_1,
      FUNCT_1, FINSEQ_1, CARD_1, ORDINAL1, NAT_1, NUMBERS, PARTFUN1, EQREL_1,
      FINSET_1, FUNCT_2, GROUP_10, NEWTON, NAT_D;
 constructors WELLORD2, GROUP_10, NEWTON, NAT_D, REAL_1, RVSUM_1, CARD_5,
      RELSET_1;
 registrations XBOOLE_0, SUBSET_1, XXREAL_0, XREAL_0, FINSEQ_1, RELAT_1,
      ORDINAL1, EQREL_1, CARD_3, NAT_1, CARD_1, MEMBERED, FINSET_1, FUNCT_1,
      FUNCT_2, RELSET_1;
 requirements REAL, NUMERALS, SUBSET, BOOLE, ARITHM;
 definitions CARD_1, GROUP_10;
 theorems TARSKI, XBOOLE_0, XBOOLE_1, EQREL_1, CARD_1, WELLORD2, FUNCT_1,
      FUNCT_2, RELAT_1, GROUP_10, ZFMISC_1, CARD_2, NAT_1, XREAL_1, ORDINAL1,
      XXREAL_0, STIRL2_1, WAYBEL12, CARD_FIL, FINSEQ_1, NEWTON, ENUMSET1,
      NAT_D, XREAL_0, CARD_3;
 schemes NAT_1, FUNCT_1, FUNCT_2, RECDEF_2;

begin
definition
let R4 being set;
let R5 being set;
let R8 being (Subset of R4);
let C1 being (a_partition of ( the_subsets_of_card (R5 , R4) ));
pred R8 is_homogeneous_for C1
means
:L1: (ex B1 being (Element of C1) st ( the_subsets_of_card (R5 , R8) ) c= B1)
;end;
registration
let R1 being Nat;
let C2 being  infinite set;
cluster ( the_subsets_of_card (R1 , C2) ) -> non  empty;
correctness
proof
L3: (not ( card C2 ) c= ( card R1 ));
thus L4: thesis by L3 , GROUP_10:1;
end;
end;
definition
let R1 being Nat;
let R4 being set;
let R5 being set;
let R7 being (Function of R4 , R5);
assume that
L6: R7 is  one-to-one
and
L7: (( card R1 ) c= ( card R4 ) & R4 is non  empty)
and
L8: R5 is non  empty;
func R7 ||^ R1 -> (Function of ( the_subsets_of_card (R1 , R4) ) , ( the_subsets_of_card (R1 , R5) )) means
:L9: (for B2 being (Element of ( the_subsets_of_card (R1 , R4) )) holds ( it . B2 ) = ( R7 .: B2 ));
existence
proof
set D1 = ( the_subsets_of_card (R1 , R4) );
reconsider D2 = D1 as non  empty set by L7 , GROUP_10:1;
deffunc H1(set) = ( R7 .: $1 );
consider C3 being Function such that L10: (( dom C3 ) = D2 & (for B3 being (Element of D2) holds ( C3 . B3 ) = H1(B3))) from FUNCT_1:sch 4;
L11: (for B4 being set holds (B4 in ( rng C3 ) implies B4 in ( the_subsets_of_card (R1 , R5) )))
proof
let C4 being set;
assume L12: C4 in ( rng C3 );
consider C5 being set such that L13: C5 in ( dom C3 ) and L14: C4 = ( C3 . C5 ) by L12 , FUNCT_1:def 3;
L15: (ex B5 being (Subset of R4) st (C5 = B5 & ( card B5 ) = R1)) by L10 , L13;
reconsider D3 = C5 as (Element of D2) by L10 , L13;
L16: C4 = ( R7 .: D3 ) by L10 , L14;
L17: R7 in ( Funcs (R4 , R5) ) by L8 , FUNCT_2:8;
L18: (ex B6 being Function st (R7 = B6 & ( dom B6 ) = R4 & ( rng B6 ) c= R5)) by L17 , FUNCT_2:def 2;
L19: ( R7 .: D3 ) c= ( rng R7 ) by RELAT_1:111;
reconsider D4 = C4 as (Subset of R5) by L19 , L16 , L18 , XBOOLE_1:1;
L20: D3 , ( R7 .: D3 ) are_equipotent  by L6 , L10 , L13 , L18 , CARD_1:33;
L21: ( card D4 ) = R1 by L20 , L15 , L16 , CARD_1:5;
thus L22: thesis by L21;
end;
L23: ( rng C3 ) c= ( the_subsets_of_card (R1 , R5) ) by L11 , TARSKI:def 3;
reconsider D5 = C3 as (Function of ( the_subsets_of_card (R1 , R4) ) , ( the_subsets_of_card (R1 , R5) )) by L23 , L10 , FUNCT_2:2;
take D5;
thus L24: thesis by L10;
end;
uniqueness
proof
let C6 , C7 being (Function of ( the_subsets_of_card (R1 , R4) ) , ( the_subsets_of_card (R1 , R5) ));
assume that
L25: (for B7 being (Element of ( the_subsets_of_card (R1 , R4) )) holds ( C6 . B7 ) = ( R7 .: B7 ))
and
L26: (for B8 being (Element of ( the_subsets_of_card (R1 , R4) )) holds ( C7 . B8 ) = ( R7 .: B8 ));
L27:
now
let C8 being set;
assume L28: C8 in ( the_subsets_of_card (R1 , R4) );
reconsider D6 = C8 as (Element of ( the_subsets_of_card (R1 , R4) )) by L28;
thus L29: ( C6 . C8 ) = ( R7 .: D6 ) by L25
.= ( C7 . C8 ) by L26;
end;
thus L30: thesis by L27 , FUNCT_2:12;
end;
end;
L32: (for R4 being set holds (for R5 being set holds (for R6 being set holds (R4 c= R5 implies ( the_subsets_of_card (R6 , R4) ) c= ( the_subsets_of_card (R6 , R5) )))))
proof
let R4 being set;
let R5 being set;
let R6 being set;
assume L33: R4 c= R5;
L34: (for B9 being set holds (B9 in ( the_subsets_of_card (R6 , R4) ) implies B9 in ( the_subsets_of_card (R6 , R5) )))
proof
let C9 being set;
assume L35: C9 in ( the_subsets_of_card (R6 , R4) );
consider C10 being (Subset of R4) such that L36: C10 = C9 and L37: ( card C10 ) = R6 by L35;
reconsider D7 = C10 as (Subset of R5) by L33 , XBOOLE_1:1;
L38: D7 = C9 by L36;
thus L39: thesis by L38 , L37;
end;
thus L40: thesis by L34 , TARSKI:def 3;
end;
theorem
L41: (for R1 being Nat holds (for R4 being set holds (for R5 being set holds (for R7 being (Function of R4 , R5) holds (for R8 being (Subset of R4) holds ((R7 is  one-to-one & ( card R1 ) c= ( card R4 ) & R4 is non  empty & R5 is non  empty) implies ( the_subsets_of_card (R1 , ( R7 .: R8 )) ) = ( ( R7 ||^ R1 ) .: ( the_subsets_of_card (R1 , R8) ) )))))))
proof
let R1 being Nat;
let R4 being set;
let R5 being set;
let R7 being (Function of R4 , R5);
let R8 being (Subset of R4);
assume that
L42: R7 is  one-to-one
and
L43: ( card R1 ) c= ( card R4 )
and
L44: R4 is non  empty
and
L45: R5 is non  empty;
consider C11 being Function such that L46: R1 c= ( C11 .: R4 ) by L43 , CARD_1:66;
L47: R7 in ( Funcs (R4 , R5) ) by L45 , FUNCT_2:8;
L48: (ex B10 being Function st (R7 = B10 & ( dom B10 ) = R4 & ( rng B10 ) c= R5)) by L47 , FUNCT_2:def 2;
L49: ( card R4 ) c= ( card R5 ) by L48 , L42 , CARD_1:10;
consider C12 being Function such that L50: R4 c= ( C12 .: R5 ) by L49 , CARD_1:66;
L51: ( C11 .: R4 ) c= ( C11 .: ( C12 .: R5 ) ) by L50 , RELAT_1:123;
L52: R1 c= ( C11 .: ( C12 .: R5 ) ) by L51 , L46 , XBOOLE_1:1;
L53: R1 c= ( ( C11 * C12 ) .: R5 ) by L52 , RELAT_1:126;
L54: ( card R1 ) c= ( card R5 ) by L53 , CARD_1:66;
L55: ( the_subsets_of_card (R1 , R5) ) is non  empty by L54 , L45 , GROUP_10:1;
L56: ( R7 ||^ R1 ) in ( Funcs (( the_subsets_of_card (R1 , R4) ) , ( the_subsets_of_card (R1 , R5) )) ) by L55 , FUNCT_2:8;
L57: (ex B11 being Function st (( R7 ||^ R1 ) = B11 & ( dom B11 ) = ( the_subsets_of_card (R1 , R4) ) & ( rng B11 ) c= ( the_subsets_of_card (R1 , R5) ))) by L56 , FUNCT_2:def 2;
L58: (for B12 being set holds (B12 in ( the_subsets_of_card (R1 , ( R7 .: R8 )) ) iff B12 in ( ( R7 ||^ R1 ) .: ( the_subsets_of_card (R1 , R8) ) )))
proof
let C13 being set;
thus L59:now
L60: ( R7 .: R8 ) c= ( rng R7 ) by RELAT_1:111;
assume L61: C13 in ( the_subsets_of_card (R1 , ( R7 .: R8 )) );
L62: (ex B13 being (Subset of ( R7 .: R8 )) st (C13 = B13 & ( card B13 ) = R1)) by L61;
L63: (ex B14 being set st (B14 in ( dom ( R7 ||^ R1 ) ) & B14 in ( the_subsets_of_card (R1 , R8) ) & C13 = ( ( R7 ||^ R1 ) . B14 )))
proof
set D8 = ( R7 " C13 );
take D8;
L64: D8 c= ( dom R7 ) by RELAT_1:132;
L65: ( R7 .: D8 ) = C13 by L61 , L60 , FUNCT_1:77 , XBOOLE_1:1;
reconsider D9 = D8 as (Subset of R8) by L65 , L42 , L61 , L64 , FUNCT_1:87;
L66: D8 , ( R7 .: D8 ) are_equipotent  by L42 , L64 , CARD_1:33;
L67: ( card D9 ) = R1 by L66 , L62 , L65 , CARD_1:5;
L68: D8 in ( the_subsets_of_card (R1 , R8) ) by L67;
L69: ( the_subsets_of_card (R1 , R8) ) c= ( the_subsets_of_card (R1 , R4) ) by L32;
thus L70: D8 in ( dom ( R7 ||^ R1 ) ) by L69 , L57 , L68;
thus L71: D8 in ( the_subsets_of_card (R1 , R8) ) by L67;
thus L72: C13 = ( R7 .: D8 ) by L61 , L60 , FUNCT_1:77 , XBOOLE_1:1
.= ( ( R7 ||^ R1 ) . D8 ) by L42 , L43 , L44 , L45 , L68 , L69 , L9;
end;
thus L73: C13 in ( ( R7 ||^ R1 ) .: ( the_subsets_of_card (R1 , R8) ) ) by L63 , FUNCT_1:def 6;
end;
assume L74: C13 in ( ( R7 ||^ R1 ) .: ( the_subsets_of_card (R1 , R8) ) );
consider C14 being set such that L75: C14 in ( dom ( R7 ||^ R1 ) ) and L76: C14 in ( the_subsets_of_card (R1 , R8) ) and L77: C13 = ( ( R7 ||^ R1 ) . C14 ) by L74 , FUNCT_1:def 6;
reconsider D10 = C14 as (Element of ( the_subsets_of_card (R1 , R4) )) by L75;
L78: C13 = ( R7 .: D10 ) by L42 , L43 , L44 , L45 , L77 , L9;
reconsider D11 = C13 as (Subset of ( R7 .: R8 )) by L78 , L76 , RELAT_1:123;
L79: ((ex B15 being (Subset of R8) st (B15 = D10 & ( card B15 ) = R1)) & D10 , ( R7 .: D10 ) are_equipotent ) by L42 , L48 , L76 , CARD_1:33 , XBOOLE_1:1;
L80: ( card D11 ) = R1 by L79 , L78 , CARD_1:5;
thus L81: thesis by L80;
end;
thus L82: thesis by L58 , TARSKI:1;
end;
L83: (for R4 being set holds ( the_subsets_of_card (( 0 ) , R4) ) = { ( 0 ) })
proof
let R4 being set;
L84: (for B16 being set holds (B16 in ( the_subsets_of_card (( 0 ) , R4) ) iff B16 = ( 0 )))
proof
let C15 being set;
thus L85:now
assume L86: C15 in ( the_subsets_of_card (( 0 ) , R4) );
L87: (ex B17 being (Subset of R4) st (B17 = C15 & ( card B17 ) = ( 0 ))) by L86;
thus L88: C15 = ( 0 ) by L87;
end;
assume L89: C15 = ( 0 );
reconsider D12 = C15 as (Subset of R4) by L89 , XBOOLE_1:2;
L90: ( card D12 ) = ( 0 ) by L89;
thus L91: thesis by L90;
end;
thus L92: thesis by L84 , TARSKI:def 1;
end;
L93: (for B18 , B19 being  finite set holds (( card B19 ) = B18 implies ( the_subsets_of_card (B18 , B19) ) = { B19 }))
proof
let C16 , C17 being  finite set;
assume L94: ( card C17 ) = C16;
L95: (for B20 being set holds (B20 in ( the_subsets_of_card (C16 , C17) ) iff B20 = C17))
proof
let C18 being set;
thus L96:now
assume L97: C18 in ( the_subsets_of_card (C16 , C17) );
consider C19 being (Subset of C17) such that L98: C19 = C18 and L99: ( card C19 ) = C16 by L97;
reconsider D13 = C19 as  finite (Subset of C17);
L100: ( card ( C17 \ D13 ) ) = ( ( card C17 ) - ( card D13 ) ) by CARD_2:44
.= ( 0 ) by L94 , L99;
L101: ( C17 \ D13 ) = ( {} ) by L100;
L102: C17 c= D13 by L101 , XBOOLE_1:37;
thus L103: C18 = C17 by L102 , L98 , XBOOLE_0:def 10;
end;
assume L104: C18 = C17;
L105: C18 c= C17 by L104;
reconsider D14 = C18 as (Subset of C17) by L105;
L106: D14 in ( the_subsets_of_card (C16 , C17) ) by L94 , L104;
thus L107: thesis by L106;
end;
thus L108: thesis by L95 , TARSKI:def 1;
end;
theorem
L109: (for R4 being set holds ((R4 is  infinite & R4 c= ( omega )) implies ( card R4 ) = ( omega )))
proof
let R4 being set;
assume L110: (R4 is  infinite & R4 c= ( omega ));
L111: ( NAT ) , R4 are_equipotent  by L110 , WAYBEL12:2;
thus L112: thesis by L111 , CARD_1:5 , CARD_1:47;
end;
theorem
L113: (for R4 being set holds (for R5 being set holds (R4 is  infinite implies ( R4 \/ R5 ) is  infinite)))
proof
let R4 being set;
let R5 being set;
assume L114: R4 is  infinite;
L115: ( card R4 ) c= ( card ( R4 \/ R5 ) ) by CARD_1:11 , XBOOLE_1:7;
assume L116: ( R4 \/ R5 ) is  finite;
thus L117: contradiction by L116 , L114 , L115;
end;
theorem
L118: (for R4 being set holds (for R5 being set holds ((R4 is  infinite & R5 is  finite) implies ( R4 \ R5 ) is  infinite)))
proof
let R4 being set;
let R5 being set;
assume L119: (R4 is  infinite & R5 is  finite);
L120: ( R4 \/ R5 ) = ( ( R4 \ R5 ) \/ R5 ) by XBOOLE_1:39;
assume L121: ( R4 \ R5 ) is  finite;
thus L122: contradiction by L121 , L119 , L120 , L113;
end;
registration
let C20 being  infinite set;
let C21 being set;
cluster ( C20 \/ C21 ) ->  infinite;
correctness by L113;
end;
registration
let C22 being  infinite set;
let C23 being  finite set;
cluster ( C22 \ C23 ) ->  infinite;
correctness by L118;
end;
L125: (for R1 being Nat holds (for R3 being Nat holds (for R4 being set holds (for B21 being (Function of ( the_subsets_of_card (R1 , R4) ) , R3) holds ((( card R4 ) = ( omega ) & R4 c= ( omega ) & R3 <> ( 0 )) implies (ex R8 being (Subset of R4) st (R8 is  infinite & ( B21 | ( the_subsets_of_card (R1 , R8) ) ) is  constant)))))))
proof
let R1 being Nat;
let R3 being Nat;
let R4 being set;
defpred S1[ Nat ] means (for B22 being Nat holds (for B23 being set holds (for B24 being (Function of ( the_subsets_of_card ($1 , B23) ) , B22) holds ((( card B23 ) = ( omega ) & B23 c= ( omega ) & B22 <> ( 0 )) implies (ex B25 being (Subset of B23) st (B25 is  infinite & ( B24 | ( the_subsets_of_card ($1 , B25) ) ) is  constant))))));
L126: (for B26 being Nat holds (S1[ B26 ] implies S1[ ( B26 + 1 ) ]))
proof
let C24 being Nat;
assume L127: S1[ C24 ];
L128:
now
let C25 being Nat;
let C26 being set;
let C27 being (Function of ( the_subsets_of_card (( C24 + 1 ) , C26) ) , C25);
assume L129: ( card C26 ) = ( omega );
L130: C26 c= C26;
L131: C26 in ( the_subsets_of_card (( omega ) , C26) ) by L130 , L129;
reconsider D15 = ( the_subsets_of_card (( omega ) , C26) ) as non  empty set by L131;
reconsider D16 = C26 as (Element of D15) by L131;
defpred S2[ set , set , set , set , set ] means (for B27 , B28 being (Element of D15) holds (for B29 , B30 being (Element of ( omega )) holds (($2 = B27 & $3 = B29 & $4 = B28 & $5 = B30) implies ((B29 in B27 implies (ex B31 being (Function of ( the_subsets_of_card (C24 , ( B27 \ { B29 } )) ) , C25) st (ex B32 being (Subset of ( B27 \ { B29 } )) st (B32 is  infinite & ( B31 | ( the_subsets_of_card (C24 , B32) ) ) is  constant & B28 = B32 & B30 in B32 & B29 < B30 & (for B33 being (Element of ( the_subsets_of_card (C24 , ( B27 \ { B29 } )) )) holds ( B31 . B33 ) = ( C27 . ( B33 \/ { B29 } ) )) & (for B34 being (Element of ( omega )) holds ((B34 > B29 & B34 in B32) implies B30 <= B34)))))) & ((not B29 in B27) implies (B28 = C26 & B30 = ( 0 )))))));
set D17 = ( min* C26 );
assume L132: C26 c= ( omega );
assume L133: C25 <> ( 0 );
L134: (for B35 being set holds (for B36 being (Element of B35) holds ((( card B35 ) = ( omega ) & B35 c= C26) implies (ex B37 being (Function of ( the_subsets_of_card (C24 , ( B35 \ { B36 } )) ) , C25) st (ex B38 being (Subset of ( B35 \ { B36 } )) st (B38 is  infinite & ( B37 | ( the_subsets_of_card (C24 , B38) ) ) is  constant & (for B39 being (Element of ( the_subsets_of_card (C24 , ( B35 \ { B36 } )) )) holds ( B37 . B39 ) = ( C27 . ( B39 \/ { B36 } ) ))))))))
proof
let C28 being set;
let C29 being (Element of C28);
set D18 = ( the_subsets_of_card (C24 , ( C28 \ { C29 } )) );
assume L135: ( card C28 ) = ( omega );
L136: C28 is  infinite by L135;
reconsider D19 = D18 as non  empty set by L136;
deffunc H2((Element of D19)) = ( C27 . ( $1 \/ { C29 } ) );
assume L137: C28 c= C26;
L138: C28 is non  empty by L135;
L139: { C29 } c= C28 by L138 , ZFMISC_1:31;
L140: (for B40 being (Element of D19) holds H2(B40) in C25)
proof
let C30 being (Element of D19);
L141: C30 in D19;
consider C31 being (Subset of ( C28 \ { C29 } )) such that L142: C30 = C31 and L143: ( card C31 ) = C24 by L141;
L144: ( C30 \/ { C29 } ) c= ( ( C28 \ { C29 } ) \/ { C29 } ) by L142 , XBOOLE_1:9;
L145: ( C30 \/ { C29 } ) c= ( C28 \/ { C29 } ) by L144 , XBOOLE_1:39;
reconsider D20 = ( C30 \/ { C29 } ) as (Subset of C28) by L145 , L139 , XBOOLE_1:12;
reconsider D21 = C31 as  finite set by L143;
L146: (not C29 in D21)
proof
assume L147: C29 in D21;
L148: (not C29 in { C29 }) by L147 , XBOOLE_0:def 5;
thus L149: contradiction by L148 , TARSKI:def 1;
end;
L150: ( card D20 ) = ( C24 + 1 ) by L146 , L142 , L143 , CARD_2:41;
L151: ( C30 \/ { C29 } ) in ( the_subsets_of_card (( C24 + 1 ) , C28) ) by L150;
L152: ( the_subsets_of_card (( C24 + 1 ) , C28) ) c= ( the_subsets_of_card (( C24 + 1 ) , C26) ) by L137 , L32;
thus L153: thesis by L152 , L133 , L151 , FUNCT_2:5;
end;
consider C32 being (Function of D19 , C25) such that L154: (for B41 being (Element of D19) holds ( C32 . B41 ) = H2(B41)) from FUNCT_2:sch 8(L140);
reconsider D22 = C32 as (Function of ( the_subsets_of_card (C24 , ( C28 \ { C29 } )) ) , C25);
L155: C28 c= ( omega ) by L132 , L137 , XBOOLE_1:1;
L156: ( card ( C28 \ { C29 } ) ) = ( omega ) by L155 , L136 , L109 , XBOOLE_1:1;
consider C33 being (Subset of ( C28 \ { C29 } )) such that L157: (C33 is  infinite & ( D22 | ( the_subsets_of_card (C24 , C33) ) ) is  constant) by L156 , L127 , L133 , L155 , XBOOLE_1:1;
take D22;
take C33;
thus L158: (C33 is  infinite & ( D22 | ( the_subsets_of_card (C24 , C33) ) ) is  constant) by L157;
let C34 being (Element of ( the_subsets_of_card (C24 , ( C28 \ { C29 } )) ));
thus L159: thesis by L154;
end;
L160: (for B42 being (Element of ( NAT )) holds (for B43 being (Element of D15) holds (for B44 being (Element of ( omega )) holds (ex B45 being (Element of D15) st (ex B46 being (Element of ( omega )) st S2[ B42 , B43 , B44 , B45 , B46 ])))))
proof
let C35 being (Element of ( NAT ));
let C36 being (Element of D15);
let C37 being (Element of ( omega ));
per cases ;
suppose L161: C37 in C36;

reconsider D23 = C37 as (Element of C36) by L161;
L162: C36 in D15;
L163: (ex B47 being (Subset of C26) st (B47 = C36 & ( card B47 ) = ( omega ))) by L162;
consider C38 being (Function of ( the_subsets_of_card (C24 , ( C36 \ { D23 } )) ) , C25), C39 being (Subset of ( C36 \ { D23 } )) such that L164: C39 is  infinite and L165: ( C38 | ( the_subsets_of_card (C24 , C39) ) ) is  constant and L166: (for B48 being (Element of ( the_subsets_of_card (C24 , ( C36 \ { D23 } )) )) holds ( C38 . B48 ) = ( C27 . ( B48 \/ { D23 } ) )) by L163 , L134;
L167: C39 c= C36 by XBOOLE_1:1;
L168: C39 c= C26 by L167 , L162 , XBOOLE_1:1;
L169: ( card C39 ) = ( omega ) by L168 , L132 , L164 , L109 , XBOOLE_1:1;
L170: C39 in D15 by L169 , L168;
reconsider D24 = C39 as (Element of D15) by L170;
set D25 = ( min* { B49 where B49 is (Element of ( omega )) : (B49 > C37 & B49 in C39) } );
take D24;
take D25;
L171: C39 c= ( omega ) by L132 , L168 , XBOOLE_1:1;
L172:
now
let C40 , C41 being (Element of D15);
let C42 , C43 being (Element of ( omega ));
assume that
L173: C36 = C40
and
L174: C37 = C42;
assume that
L175: D24 = C41
and
L176: D25 = C43;
thus L177: (C42 in C40 implies (ex B50 being (Function of ( the_subsets_of_card (C24 , ( C40 \ { C42 } )) ) , C25) st (ex B51 being (Subset of ( C40 \ { C42 } )) st (B51 is  infinite & ( B50 | ( the_subsets_of_card (C24 , B51) ) ) is  constant & C41 = B51 & C43 in B51 & C42 < C43 & (for B52 being (Element of ( the_subsets_of_card (C24 , ( C40 \ { C42 } )) )) holds ( B50 . B52 ) = ( C27 . ( B52 \/ { C42 } ) )) & (for B53 being (Element of ( omega )) holds ((B53 > C42 & B53 in B51) implies C43 <= B53))))))
proof
reconsider D26 = C39 as (Subset of ( C40 \ { C42 } )) by L173 , L174;
set D27 = { B54 where B54 is (Element of ( omega )) : (B54 > C37 & B54 in C39) };
reconsider D28 = C38 as (Function of ( the_subsets_of_card (C24 , ( C40 \ { C42 } )) ) , C25) by L173 , L174;
assume L178: C42 in C40;
take D28;
take D26;
L179: (for B55 being set holds (B55 in D27 implies B55 in ( NAT )))
proof
let C44 being set;
assume L180: C44 in D27;
L181: (ex B56 being (Element of ( omega )) st (B56 = C44 & B56 > C37 & B56 in C39)) by L180;
thus L182: thesis by L181;
end;
reconsider D29 = D27 as (Subset of ( NAT )) by L179 , TARSKI:def 3;
thus L183: D26 is  infinite by L164;
thus L184: ( D28 | ( the_subsets_of_card (C24 , D26) ) ) is  constant by L165;
thus L185: C41 = D26 by L175;
L186: D29 <> ( {} )
proof
set D30 = { B57 where B57 is (Element of ( omega )) : (B57 <= C37 & B57 in C39) };
L187:
now
let C45 being set;
assume L188: C45 in ( D29 \/ D30 );
per cases  by L188 , XBOOLE_0:def 3;
suppose L189: C45 in D29;

L190: (ex B58 being (Element of ( omega )) st (C45 = B58 & B58 > C37 & B58 in C39)) by L189;
thus L191: C45 in C39 by L190;
end;
suppose L192: C45 in D30;

L193: (ex B59 being (Element of ( omega )) st (C45 = B59 & B59 <= C37 & B59 in C39)) by L192;
thus L194: C45 in C39 by L193;
end;
end;
L196:
now
let C46 being set;
assume L197: C46 in D30;
consider C47 being (Element of ( omega )) such that L198: C46 = C47 and L199: C47 <= C37 and L200: C47 in C39 by L197;
L201: C47 < ( C37 + 1 ) by L199 , NAT_1:13;
thus L202: C46 in ( Segm ( C37 + 1 ) ) by L201 , L198 , NAT_1:44;
end;
L203: D30 c= ( Segm ( C37 + 1 ) ) by L196 , TARSKI:def 3;
L204:
now
let C48 being set;
assume L205: C48 in C39;
reconsider D31 = C48 as (Element of ( omega )) by L205 , L171;
per cases ;
suppose L206: D31 <= C37;

L207: C48 in D30 by L206 , L205;
thus L208: C48 in ( D29 \/ D30 ) by L207 , XBOOLE_0:def 3;
end;
suppose L209: D31 > C37;

L210: C48 in D29 by L209 , L205;
thus L211: C48 in ( D29 \/ D30 ) by L210 , XBOOLE_0:def 3;
end;
end;
assume L213: D29 = ( {} );
thus L214: contradiction by L213 , L164 , L203 , L187 , L204 , TARSKI:1;
end;
L215: D25 in D29 by L186 , NAT_1:def 1;
L216: (ex B60 being (Element of ( omega )) st (D25 = B60 & B60 > C37 & B60 in C39)) by L215;
thus L217: C43 in D26 by L216 , L176;
thus L218: C42 < C43 by L174 , L176 , L216;
thus L219: (for B61 being (Element of ( the_subsets_of_card (C24 , ( C40 \ { C42 } )) )) holds ( D28 . B61 ) = ( C27 . ( B61 \/ { C42 } ) )) by L166 , L173 , L174;
let C49 being (Element of ( omega ));
assume L220: C49 > C42;
assume L221: C49 in D26;
L222: C49 in D29 by L221 , L174 , L220;
thus L223: thesis by L222 , L176 , NAT_1:def 1;
end;

assume L224: (not C42 in C40);
thus L225: thesis by L224 , L161 , L173 , L174;
end;
thus L226: thesis by L172;
end;
suppose L227: (not C37 in C36);

reconsider D32 = ( 0 ) as (Element of ( omega ));
reconsider D33 = C26 as (Element of D15) by L131;
take D33;
take D32;
thus L228: thesis by L227;
end;
end;
consider C50 being (Function of ( NAT ) , D15), C51 being (Function of ( NAT ) , ( omega )) such that L230: (( C50 . ( 0 ) ) = D16 & ( C51 . ( 0 ) ) = D17 & (for B62 being (Element of ( NAT )) holds S2[ B62 , ( C50 . B62 ) , ( C51 . B62 ) , ( C50 . ( B62 + 1 ) ) , ( C51 . ( B62 + 1 ) ) ])) from RECDEF_2:sch 3(L160);
defpred S3[ Nat ] means (( C51 . $1 ) in ( C51 . ( $1 + 1 ) ) & ( C50 . ( $1 + 1 ) ) c= ( C50 . $1 ) & ( C51 . $1 ) in ( C50 . $1 ) & ( C51 . ( $1 + 1 ) ) in ( C50 . ( $1 + 1 ) ) & (not ( C51 . $1 ) in ( C50 . ( $1 + 1 ) )));
L231: S3[ ( 0 ) ]
proof
set D34 = ( 0 );
reconsider D35 = D34 as (Element of ( NAT ));
reconsider D36 = ( C50 . D35 ) as (Element of D15);
reconsider D37 = ( C50 . ( D35 + 1 ) ) as (Element of D15);
reconsider D38 = ( C51 . D35 ) as (Element of ( omega ));
reconsider D39 = ( C51 . ( D35 + 1 ) ) as (Element of ( omega ));
L232: (D38 in D36 implies (ex B63 being (Function of ( the_subsets_of_card (C24 , ( D36 \ { D38 } )) ) , C25) st (ex B64 being (Subset of ( D36 \ { D38 } )) st (B64 is  infinite & ( B63 | ( the_subsets_of_card (C24 , B64) ) ) is  constant & D37 = B64 & D39 in B64 & D38 < D39 & (for B65 being (Element of ( the_subsets_of_card (C24 , ( D36 \ { D38 } )) )) holds ( B63 . B65 ) = ( C27 . ( B65 \/ { D38 } ) )) & (for B66 being (Element of ( omega )) holds ((B66 > D38 & B66 in B64) implies D39 <= B66)))))) by L230;
thus L233: ( C51 . ( 0 ) ) in ( C51 . ( ( 0 ) + 1 ) ) by L232 , L129 , L132 , L230 , CARD_1:27 , NAT_1:44 , NAT_1:def 1;
thus L234: ( C50 . ( ( 0 ) + 1 ) ) c= ( C50 . ( 0 ) ) by L129 , L132 , L230 , L232 , CARD_1:27 , NAT_1:def 1 , XBOOLE_1:1;
thus L235: ( C51 . ( 0 ) ) in ( C50 . ( 0 ) ) by L129 , L132 , L230 , CARD_1:27 , NAT_1:def 1;
thus L236: ( C51 . ( ( 0 ) + 1 ) ) in ( C50 . ( ( 0 ) + 1 ) ) by L129 , L132 , L230 , L232 , CARD_1:27 , NAT_1:def 1;
L237: (not D38 in D37)
proof
assume L238: D38 in D37;
L239: (not D38 in { D38 }) by L238 , L129 , L132 , L230 , L232 , CARD_1:27 , NAT_1:def 1 , XBOOLE_0:def 5;
thus L240: contradiction by L239 , TARSKI:def 1;
end;
thus L241: thesis by L237;
end;
defpred S4[ set , set ] means (for B67 being set holds (for B68 being (Element of ( NAT )) holds (for B69 being (Function of ( the_subsets_of_card (C24 , ( ( C50 . B68 ) \ { ( C51 . B68 ) } )) ) , C25) holds ((B68 = $1 & B67 = { B70 where B70 is (Element of ( omega )) : (ex B71 being (Element of ( NAT )) st (( C51 . B71 ) = B70 & B71 > B68)) } & (for B72 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . B68 ) \ { ( C51 . B68 ) } )) )) holds ( B69 . B72 ) = ( C27 . ( B72 \/ { ( C51 . B68 ) } ) ))) implies (ex B73 being Nat st (B73 = $2 & B73 in C25 & ( rng ( B69 | ( the_subsets_of_card (C24 , B67) ) ) ) = { B73 }))))));
defpred S5[ Nat ] means (for B74 , B75 being Nat holds ((B74 >= B75 & B74 = ( $1 + B75 )) implies (( C50 . B74 ) c= ( C50 . B75 ) & (for B76 , B77 being Nat holds ((B74 <> B75 & B76 = ( C51 . B74 ) & B77 = ( C51 . B75 )) implies B76 > B77)))));
L242: (for B78 being Nat holds (S3[ B78 ] implies S3[ ( B78 + 1 ) ]))
proof
let C52 being Nat;
reconsider D40 = ( C52 + 1 ) as (Element of ( NAT ));
reconsider D41 = ( C50 . D40 ) as (Element of D15);
reconsider D42 = ( C50 . ( D40 + 1 ) ) as (Element of D15);
reconsider D43 = ( C51 . D40 ) as (Element of ( omega ));
reconsider D44 = ( C51 . ( D40 + 1 ) ) as (Element of ( omega ));
assume L243: S3[ C52 ];
L244: (ex B79 being (Function of ( the_subsets_of_card (C24 , ( D41 \ { D43 } )) ) , C25) st (ex B80 being (Subset of ( D41 \ { D43 } )) st (B80 is  infinite & ( B79 | ( the_subsets_of_card (C24 , B80) ) ) is  constant & D42 = B80 & D44 in B80 & D43 < D44 & (for B81 being (Element of ( the_subsets_of_card (C24 , ( D41 \ { D43 } )) )) holds ( B79 . B81 ) = ( C27 . ( B81 \/ { D43 } ) )) & (for B82 being (Element of ( omega )) holds ((B82 > D43 & B82 in B80) implies D44 <= B82))))) by L243 , L230;
L245: (not D43 in D42)
proof
assume L246: D43 in D42;
L247: (not D43 in { D43 }) by L246 , L244 , XBOOLE_0:def 5;
thus L248: contradiction by L247 , TARSKI:def 1;
end;
thus L249: S3[ ( C52 + 1 ) ] by L245 , L243 , L244 , NAT_1:44 , XBOOLE_1:1;
end;
L250: (for B83 being Nat holds S3[ B83 ]) from NAT_1:sch 2(L231 , L242);
L251: (for B84 being Nat holds (S5[ B84 ] implies S5[ ( B84 + 1 ) ]))
proof
let C53 being Nat;
assume L252: S5[ C53 ];
thus L253: S5[ ( C53 + 1 ) ]
proof
let C54 , C55 being Nat;
assume L254: C54 >= C55;
set D45 = ( C55 + 1 );
assume L255: C54 = ( ( C53 + 1 ) + C55 );
L256: C54 = ( C53 + D45 ) by L255;
L257: ( C50 . ( C55 + 1 ) ) c= ( C50 . C55 ) by L250;
L258: C54 <> C55
proof
assume L259: C54 = C55;
L260: ( 0 ) = ( C53 + 1 ) by L259 , L255;
thus L261: contradiction by L260;
end;
L262: C54 > C55 by L258 , L254 , XXREAL_0:1;
L263: C54 >= D45 by L262 , NAT_1:13;
L264: ( C50 . C54 ) c= ( C50 . ( C55 + 1 ) ) by L263 , L252 , L256;
thus L265: ( C50 . C54 ) c= ( C50 . C55 ) by L264 , L257 , XBOOLE_1:1;
L266: (for B85 , B86 being Nat holds ((C54 <> D45 & B85 = ( C51 . C54 ) & B86 = ( C51 . D45 )) implies B85 > B86)) by L252 , L263 , L256;
thus L267: (for B87 , B88 being Nat holds ((C54 <> C55 & B87 = ( C51 . C54 ) & B88 = ( C51 . C55 )) implies B87 > B88))
proof
let C56 , C57 being Nat;
assume L268: C54 <> C55;
assume that
L269: C56 = ( C51 . C54 )
and
L270: C57 = ( C51 . C55 );
reconsider D46 = ( C51 . D45 ) as Nat;
L271: C57 in D46 by L250 , L270;
L272: D46 > C57 by L271 , NAT_1:44;
thus L273: thesis by L272 , L266 , L269 , XXREAL_0:2;
end;

end;

end;
L254: S5[ ( 0 ) ];
L255: (for B89 being Nat holds S5[ B89 ]) from NAT_1:sch 2(L254 , L251);
L256: (for B90 , B91 being Nat holds (B90 >= B91 implies (( C50 . B90 ) c= ( C50 . B91 ) & (for B92 , B93 being Nat holds ((B90 <> B91 & B92 = ( C51 . B90 ) & B93 = ( C51 . B91 )) implies B92 > B93)))))
proof
let C58 , C59 being Nat;
assume L257: C58 >= C59;
L258: (ex B94 being Nat st C58 = ( C59 + B94 )) by L257 , NAT_1:10;
thus L259: ( C50 . C58 ) c= ( C50 . C59 ) by L258 , L255 , L257;
thus L260: thesis by L255 , L257 , L258;
end;
L261: (for B95 being (Element of ( NAT )) holds (for B96 being set holds (for B97 being (Function of ( the_subsets_of_card (C24 , ( ( C50 . B95 ) \ { ( C51 . B95 ) } )) ) , C25) holds ((B96 = { B98 where B98 is (Element of ( omega )) : (ex B99 being (Element of ( NAT )) st (( C51 . B99 ) = B98 & B99 > B95)) } & (for B100 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . B95 ) \ { ( C51 . B95 ) } )) )) holds ( B97 . B100 ) = ( C27 . ( B100 \/ { ( C51 . B95 ) } ) ))) implies (B96 c= ( C50 . ( B95 + 1 ) ) & ( B97 | ( the_subsets_of_card (C24 , B96) ) ) is  constant)))))
proof
let C60 being (Element of ( NAT ));
let C61 being set;
let C62 being (Function of ( the_subsets_of_card (C24 , ( ( C50 . C60 ) \ { ( C51 . C60 ) } )) ) , C25);
assume L262: C61 = { B101 where B101 is (Element of ( omega )) : (ex B102 being (Element of ( NAT )) st (( C51 . B102 ) = B101 & B102 > C60)) };
consider C63 being (Element of D15), C64 being (Element of ( omega )) such that L263: ( C50 . ( C60 + 1 ) ) = C63 and L264: ( C51 . ( C60 + 1 ) ) = C64;
consider C65 being (Element of D15), C66 being (Element of ( omega )) such that L265: (( C50 . C60 ) = C65 & ( C51 . C60 ) = C66);
L266: (C66 in C65 implies ((ex B103 being (Function of ( the_subsets_of_card (C24 , ( C65 \ { C66 } )) ) , C25) st (ex B104 being (Subset of ( C65 \ { C66 } )) st (B104 is  infinite & ( B103 | ( the_subsets_of_card (C24 , B104) ) ) is  constant & C63 = B104 & C64 in B104 & C66 < C64 & (for B105 being (Element of ( the_subsets_of_card (C24 , ( C65 \ { C66 } )) )) holds ( B103 . B105 ) = ( C27 . ( B105 \/ { C66 } ) )) & (for B106 being (Element of ( omega )) holds ((B106 > C66 & B106 in B104) implies C64 <= B106))))) & ((not C66 in C65) implies (C63 = C26 & C64 = ( 0 ))))) by L230 , L265 , L263 , L264;
consider C67 being (Function of ( the_subsets_of_card (C24 , ( C65 \ { C66 } )) ) , C25), C68 being (Subset of ( C65 \ { C66 } )) such that L267: C68 is  infinite and L268: (( C67 | ( the_subsets_of_card (C24 , C68) ) ) is  constant & C63 = C68) and L269: (for B107 being (Element of ( the_subsets_of_card (C24 , ( C65 \ { C66 } )) )) holds ( C67 . B107 ) = ( C27 . ( B107 \/ { C66 } ) )) and L270: (for B108 being (Element of ( omega )) holds ((B108 > C66 & B108 in C68) implies C64 <= B108)) by L266 , L250 , L265;
reconsider D47 = C67 as (Function of ( the_subsets_of_card (C24 , ( ( C50 . C60 ) \ { ( C51 . C60 ) } )) ) , C25) by L265;
assume L271: (for B109 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . C60 ) \ { ( C51 . C60 ) } )) )) holds ( C62 . B109 ) = ( C27 . ( B109 \/ { ( C51 . C60 ) } ) ));
L272: (for B110 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . C60 ) \ { ( C51 . C60 ) } )) )) holds ( D47 . B110 ) = ( C62 . B110 ))
proof
let C69 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . C60 ) \ { ( C51 . C60 ) } )) ));
thus L273: ( D47 . C69 ) = ( C27 . ( C69 \/ { ( C51 . C60 ) } ) ) by L265 , L269
.= ( C62 . C69 ) by L271;
end;
L274: ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) is  constant by L272 , L263 , L268 , FUNCT_2:63;
L275:
now
let C70 being set;
assume L276: C70 in C61;
L277: (ex B111 being (Element of ( omega )) st (C70 = B111 & (ex B112 being (Element of ( NAT )) st (( C51 . B112 ) = B111 & B112 > C60)))) by L276 , L262;
consider C71 being (Element of ( NAT )) such that L278: ( C51 . C71 ) = C70 and L279: C71 > C60 by L277;
L280: C71 >= ( C60 + 1 ) by L279 , NAT_1:13;
L281: ( C50 . C71 ) c= ( C50 . ( C60 + 1 ) ) by L280 , L256;
L282: ( C51 . C71 ) in ( C50 . C71 ) by L250;
thus L283: C70 in ( C50 . ( C60 + 1 ) ) by L282 , L278 , L281;
end;
thus L284: C61 c= ( C50 . ( C60 + 1 ) ) by L275 , TARSKI:def 3;
L285: ( the_subsets_of_card (C24 , C61) ) c= ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) by L284 , L32;
L286: (for B113 , B114 being set holds ((B113 in ( dom ( C62 | ( the_subsets_of_card (C24 , C61) ) ) ) & B114 in ( dom ( C62 | ( the_subsets_of_card (C24 , C61) ) ) )) implies ( ( C62 | ( the_subsets_of_card (C24 , C61) ) ) . B113 ) = ( ( C62 | ( the_subsets_of_card (C24 , C61) ) ) . B114 )))
proof
let C72 , C73 being set;
assume L287: C72 in ( dom ( C62 | ( the_subsets_of_card (C24 , C61) ) ) );
L288: C72 in ( the_subsets_of_card (C24 , C61) ) by L287;
L289: C72 in ( dom C62 ) by L287 , RELAT_1:57;
L290: C72 in ( dom ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) ) by L289 , L285 , L288 , RELAT_1:57;
assume L291: C73 in ( dom ( C62 | ( the_subsets_of_card (C24 , C61) ) ) );
L292: C73 in ( the_subsets_of_card (C24 , C61) ) by L291;
L293: C73 in ( dom C62 ) by L291 , RELAT_1:57;
L294: C73 in ( dom ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) ) by L293 , L285 , L292 , RELAT_1:57;
thus L295: ( ( C62 | ( the_subsets_of_card (C24 , C61) ) ) . C72 ) = ( ( ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) | ( the_subsets_of_card (C24 , C61) ) ) . C72 ) by L285 , FUNCT_1:51
.= ( ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) . C72 ) by L288 , FUNCT_1:49
.= ( ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) . C73 ) by L274 , L290 , L294 , FUNCT_1:def 10
.= ( ( ( C62 | ( the_subsets_of_card (C24 , ( C50 . ( C60 + 1 ) )) ) ) | ( the_subsets_of_card (C24 , C61) ) ) . C73 ) by L292 , FUNCT_1:49
.= ( ( C62 | ( the_subsets_of_card (C24 , C61) ) ) . C73 ) by L285 , FUNCT_1:51;
end;
thus L296: thesis by L286 , FUNCT_1:def 10;
end;
L297: (for B115 , B116 being set holds ((B115 in ( dom C51 ) & B116 in ( dom C51 ) & ( C51 . B115 ) = ( C51 . B116 )) implies B115 = B116))
proof
let C74 , C75 being set;
assume L298: C74 in ( dom C51 );
reconsider D48 = C74 as (Element of ( NAT )) by L298;
assume L299: C75 in ( dom C51 );
reconsider D49 = C75 as (Element of ( NAT )) by L299;
reconsider D50 = ( C51 . D49 ) as (Element of ( NAT ));
reconsider D51 = ( C51 . D48 ) as (Element of ( NAT ));
assume L300: ( C51 . C74 ) = ( C51 . C75 );
assume L301: C74 <> C75;
per cases  by L301 , XXREAL_0:1;
suppose L302: D48 < D49;

L303: D51 < D50 by L302 , L256;
thus L304: contradiction by L303 , L300;
end;
suppose L305: D48 > D49;

L306: D51 > D50 by L305 , L256;
thus L307: contradiction by L306 , L300;
end;
end;
L309: C51 is  one-to-one by L297 , FUNCT_1:def 4;
L310: ( NAT ) = ( dom C51 ) by FUNCT_2:def 1;
L311: (for B117 being (Element of ( NAT )) holds ( card { B118 where B118 is (Element of ( omega )) : (ex B119 being (Element of ( NAT )) st (( C51 . B119 ) = B118 & B119 > B117)) } ) = ( omega ))
proof
let C76 being (Element of ( NAT ));
set D52 = { B120 where B120 is (Element of ( omega )) : (ex B121 being (Element of ( NAT )) st (( C51 . B121 ) = B120 & B121 > C76)) };
L312:
now
let C77 being set;
assume L313: C77 in D52;
L314: (ex B122 being (Element of ( omega )) st (C77 = B122 & (ex B123 being (Element of ( NAT )) st (( C51 . B123 ) = B122 & B123 > C76)))) by L313;
thus L315: C77 in ( NAT ) by L314;
end;
L316: D52 c= ( NAT ) by L312 , TARSKI:def 3;
L317: ( dom ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) ) = ( ( dom C51 ) /\ ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) by RELAT_1:61
.= ( ( NAT ) /\ ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) by FUNCT_2:def 1
.= ( ( ( NAT ) /\ ( NAT ) ) \ ( Segm ( C76 + 1 ) ) ) by XBOOLE_1:49
.= ( ( NAT ) \ ( Segm ( C76 + 1 ) ) );
L318: (for B124 being set holds (B124 in D52 iff B124 in ( rng ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) )))
proof
let C78 being set;
thus L319:now
assume L320: C78 in D52;
L321: (ex B125 being (Element of ( omega )) st (C78 = B125 & (ex B126 being (Element of ( NAT )) st (( C51 . B126 ) = B125 & B126 > C76)))) by L320;
consider C79 being (Element of ( NAT )) such that L322: ( C51 . C79 ) = C78 and L323: C79 > C76 by L321;
L324: C79 >= ( C76 + 1 ) by L323 , NAT_1:13;
L325: (not C79 in ( C76 + 1 )) by L324 , NAT_1:44;
L326: C79 in ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) by L325 , XBOOLE_0:def 5;
thus L327: C78 in ( rng ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) ) by L326 , L310 , L322 , FUNCT_1:50;
end;
assume L328: C78 in ( rng ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) );
consider C80 being set such that L329: C80 in ( dom ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) ) and L330: C78 = ( ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) . C80 ) by L328 , FUNCT_1:def 3;
L331: C80 in ( dom C51 ) by L329 , RELAT_1:57;
reconsider D53 = C80 as (Element of ( NAT )) by L331;
L332: (not D53 in ( Segm ( C76 + 1 ) )) by L329 , XBOOLE_0:def 5;
L333: D53 >= ( C76 + 1 ) by L332 , NAT_1:44;
L334: D53 > C76 by L333 , NAT_1:13;
L335: ( C51 . D53 ) = C78 by L329 , L330 , FUNCT_1:47;
thus L336: thesis by L335 , L334;
end;
L337: D52 = ( rng ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) ) by L318 , TARSKI:1;
L338: ( C51 | ( ( NAT ) \ ( Segm ( C76 + 1 ) ) ) ) is  one-to-one by L309 , FUNCT_1:52;
thus L339: thesis by L338 , L317 , L337 , L316 , L109 , CARD_1:59;
end;
L340: (for B127 being set holds (B127 in ( NAT ) implies (ex B128 being set st (B128 in C25 & S4[ B127 , B128 ]))))
proof
let C81 being set;
assume L341: C81 in ( NAT );
reconsider D54 = C81 as (Element of ( NAT )) by L341;
set D55 = ( C50 . D54 );
L342: (not ( C51 . D54 ) in ( C50 . ( D54 + 1 ) )) by L250;
reconsider D56 = ( C51 . D54 ) as (Element of D55) by L250;
set D57 = { B129 where B129 is (Element of ( omega )) : (ex B130 being (Element of ( NAT )) st (( C51 . B130 ) = B129 & B130 > D54)) };
L343: ( C50 . ( D54 + 1 ) ) c= ( C50 . D54 ) by L250;
L344: D55 in D15;
L345: (ex B131 being (Subset of C26) st (B131 = D55 & ( card B131 ) = ( omega ))) by L344;
consider C82 being (Function of ( the_subsets_of_card (C24 , ( D55 \ { D56 } )) ) , C25), C83 being (Subset of ( D55 \ { D56 } )) such that L346: C83 is  infinite and L347: ( C82 | ( the_subsets_of_card (C24 , C83) ) ) is  constant and L348: (for B132 being (Element of ( the_subsets_of_card (C24 , ( D55 \ { D56 } )) )) holds ( C82 . B132 ) = ( C27 . ( B132 \/ { D56 } ) )) by L345 , L134;
L349: D57 c= ( C50 . ( D54 + 1 ) ) by L261 , L348;
L350:
now
let C84 being set;
assume L351: C84 in D57;
L352: C84 in ( C50 . ( D54 + 1 ) ) by L351 , L349;
L353: (not C84 in { ( C51 . D54 ) }) by L352 , L342 , TARSKI:def 1;
thus L354: C84 in ( ( C50 . D54 ) \ { ( C51 . D54 ) } ) by L353 , L343 , L352 , XBOOLE_0:def 5;
end;
L355: D57 c= ( ( C50 . D54 ) \ { ( C51 . D54 ) } ) by L350 , TARSKI:def 3;
L356: ( the_subsets_of_card (C24 , D57) ) c= ( the_subsets_of_card (C24 , ( D55 \ { D56 } )) ) by L355 , L32;
L357: ( C82 | ( the_subsets_of_card (C24 , D57) ) ) is (Function of ( the_subsets_of_card (C24 , D57) ) , C25) by L356 , L133 , FUNCT_2:32;
L358: (not ( card D57 ) c= ( card C24 )) by L311;
L359: D57 is non  empty by L358;
L360: ( the_subsets_of_card (C24 , D57) ) is non  empty by L359 , L358 , GROUP_10:1;
L361: ( C82 | ( the_subsets_of_card (C24 , D57) ) ) is  constant by L261 , L348;
consider C85 being (Element of C25) such that L362: ( rng ( C82 | ( the_subsets_of_card (C24 , D57) ) ) ) = { C85 } by L361 , L133 , L357 , L360 , FUNCT_2:111;
reconsider D58 = C85 as set;
take D58;
thus L363: D58 in C25 by L133;
L364: (for B133 being set holds (for B134 being (Element of ( NAT )) holds (for B135 being (Function of ( the_subsets_of_card (C24 , ( ( C50 . B134 ) \ { ( C51 . B134 ) } )) ) , C25) holds ((B134 = C81 & B133 = { B136 where B136 is (Element of ( omega )) : (ex B137 being (Element of ( NAT )) st (( C51 . B137 ) = B136 & B137 > B134)) } & (for B138 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . B134 ) \ { ( C51 . B134 ) } )) )) holds ( B135 . B138 ) = ( C27 . ( B138 \/ { ( C51 . B134 ) } ) ))) implies (ex B139 being Nat st (B139 = D58 & B139 in C25 & ( rng ( B135 | ( the_subsets_of_card (C24 , B133) ) ) ) = { B139 }))))))
proof
reconsider D59 = C25 as (Element of ( NAT )) by ORDINAL1:def 12;
let C86 being set;
let C87 being (Element of ( NAT ));
let C88 being (Function of ( the_subsets_of_card (C24 , ( ( C50 . C87 ) \ { ( C51 . C87 ) } )) ) , C25);
assume L365: C87 = C81;
L366: D59 is (Subset of ( NAT )) by STIRL2_1:8;
reconsider D60 = D58 as Nat by L366;
assume L367: C86 = { B140 where B140 is (Element of ( omega )) : (ex B141 being (Element of ( NAT )) st (( C51 . B141 ) = B140 & B141 > C87)) };
assume L368: (for B142 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . C87 ) \ { ( C51 . C87 ) } )) )) holds ( C88 . B142 ) = ( C27 . ( B142 \/ { ( C51 . C87 ) } ) ));
take D60;
thus L369: D60 = D58;
thus L370: D60 in C25 by L133;
L371: (for B143 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . C87 ) \ { ( C51 . C87 ) } )) )) holds ( C82 . B143 ) = ( C88 . B143 ))
proof
let C89 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . C87 ) \ { ( C51 . C87 ) } )) ));
thus L372: ( C82 . C89 ) = ( C27 . ( C89 \/ { ( C51 . C87 ) } ) ) by L348 , L365
.= ( C88 . C89 ) by L368;
end;
thus L373: thesis by L371 , L362 , L365 , L367 , FUNCT_2:63;
end;
thus L374: S4[ C81 , D58 ] by L364;
end;
consider C90 being (Function of ( NAT ) , C25) such that L375: (for B144 being set holds (B144 in ( NAT ) implies S4[ B144 , ( C90 . B144 ) ])) from FUNCT_2:sch 1(L340);
L376: C90 in ( Funcs (( NAT ) , C25) ) by L133 , FUNCT_2:8;
L377: (ex B145 being Function st (C90 = B145 & ( dom B145 ) = ( NAT ) & ( rng B145 ) c= C25)) by L376 , FUNCT_2:def 2;
consider C91 being set such that L378: C91 in ( rng C90 ) and L379: ( C90 " { C91 } ) is  infinite by L377 , CARD_2:101;
set D61 = ( C51 .: ( C90 " { C91 } ) );
L380: ( C90 " { C91 } ) c= ( dom C90 ) by RELAT_1:132;
L381: ( C90 " { C91 } ) , D61 are_equipotent  by L380 , L309 , L310 , CARD_1:33 , XBOOLE_1:1;
L382: ( card ( C90 " { C91 } ) ) = ( card D61 ) by L381 , CARD_1:5;
L383:
now
let C92 being set;
assume L384: C92 in D61;
consider C93 being set such that L385: [ C93 , C92 ] in C51 and L386: C93 in ( C90 " { C91 } ) by L384 , RELAT_1:def 13;
L387: C93 in ( dom C51 ) by L385 , FUNCT_1:1;
reconsider D62 = C93 as (Element of ( NAT )) by L387;
L388: C92 = ( C51 . C93 ) by L385 , FUNCT_1:1;
L389: C92 in ( C50 . D62 ) by L388 , L250;
L390: ( C50 . D62 ) in ( the_subsets_of_card (( omega ) , C26) );
thus L391: C92 in C26 by L390 , L389;
end;
reconsider D63 = D61 as (Subset of C26) by L383 , TARSKI:def 3;
take D64 = D63;
thus L392: D64 is  infinite by L379 , L382;
L393: (for B146 being set holds (B146 in ( dom ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) ) implies ( ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) . B146 ) = C91))
proof
let C94 being set;
assume L394: C94 in ( dom ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) );
L395: C94 in ( the_subsets_of_card (( C24 + 1 ) , D64) ) by L394 , RELAT_1:57;
consider C95 being (Subset of D64) such that L396: C94 = C95 and L397: ( card C95 ) = ( C24 + 1 ) by L395;
set D65 = ( min* C95 );
set D66 = ( C94 \ { D65 } );
L398: C95 c= C26 by XBOOLE_1:1;
L399: C95 c= ( NAT ) by L398 , L132 , XBOOLE_1:1;
L400: D65 in C95 by L399 , L397 , CARD_1:27 , NAT_1:def 1;
consider C96 being set such that L401: C96 in ( dom C51 ) and L402: C96 in ( C90 " { C91 } ) and L403: D65 = ( C51 . C96 ) by L400 , FUNCT_1:def 6;
consider C97 being set such that L404: C97 in ( rng C90 ) and L405: [ C96 , C97 ] in C90 and L406: C97 in { C91 } by L402 , RELAT_1:131;
L407: C96 in ( dom C90 ) by L405 , FUNCT_1:1;
L408: ( C90 . C96 ) = C97 by L405 , FUNCT_1:1;
reconsider D67 = C96 as (Element of ( NAT )) by L407;
set D68 = { B147 where B147 is (Element of ( omega )) : (ex B148 being (Element of ( NAT )) st (( C51 . B148 ) = B147 & B148 > D67)) };
L409: { D65 } c= C94 by L396 , L400 , ZFMISC_1:31;
L410: ( D66 \/ { ( C51 . D67 ) } ) = C94 by L409 , L403 , XBOOLE_1:45;
reconsider D69 = ( C51 . D67 ) as (Element of ( C50 . D67 )) by L250;
L411: ( C50 . D67 ) in ( the_subsets_of_card (( omega ) , C26) );
L412: (ex B149 being (Subset of C26) st (B149 = ( C50 . D67 ) & ( card B149 ) = ( omega ))) by L411;
consider C98 being (Function of ( the_subsets_of_card (C24 , ( ( C50 . D67 ) \ { D69 } )) ) , C25), C99 being (Subset of ( ( C50 . D67 ) \ { D69 } )) such that L413: C99 is  infinite and L414: ( C98 | ( the_subsets_of_card (C24 , C99) ) ) is  constant and L415: (for B150 being (Element of ( the_subsets_of_card (C24 , ( ( C50 . D67 ) \ { D69 } )) )) holds ( C98 . B150 ) = ( C27 . ( B150 \/ { D69 } ) )) by L412 , L134;
reconsider D70 = C94 as  finite set by L396 , L397;
L416: ( card D66 ) c= ( card D70 ) by CARD_1:11;
reconsider D71 = D66 as  finite set by L416;
L417: D68 c= ( C50 . ( D67 + 1 ) ) by L261 , L415;
L418:
now
let C100 being set;
assume L419: C100 in D66;
L420: C100 in C94 by L419;
consider C101 being set such that L421: C101 in ( dom C51 ) and L422: C101 in ( C90 " { C91 } ) and L423: C100 = ( C51 . C101 ) by L420 , L396 , FUNCT_1:def 6;
reconsider D72 = C100 as (Element of ( omega )) by L396 , L399 , L420;
L424: (not C100 in { D65 }) by L419 , XBOOLE_0:def 5;
L425: (ex B151 being (Element of ( NAT )) st (( C51 . B151 ) = D72 & B151 > D67))
proof
reconsider D73 = C101 as (Element of ( NAT )) by L421;
take D73;
thus L426: ( C51 . D73 ) = D72 by L423;
L427: D65 <= D72 by L396 , L399 , L419 , NAT_1:def 1;
thus L428: D73 > D67
proof
assume L429: D67 >= D73;
L430: D67 <> D73 by L403 , L424 , L423 , TARSKI:def 1;
thus L431: contradiction by L430 , L256 , L403 , L423 , L427 , L429;
end;

end;
thus L429: C100 in D68 by L425;
end;
L430: D66 is (Subset of D68) by L418 , TARSKI:def 3;
L431: D65 in { D65 } by TARSKI:def 1;
L432: (not ( C51 . D67 ) in D66) by L431 , L403 , XBOOLE_0:def 5;
L433: ( card D70 ) = ( ( card D71 ) + 1 ) by L432 , L410 , CARD_2:41;
L434: D66 in ( the_subsets_of_card (C24 , D68) ) by L433 , L396 , L397 , L430;
L435: (ex B152 being Nat st (B152 = ( C90 . D67 ) & B152 in C25 & ( rng ( C98 | ( the_subsets_of_card (C24 , D68) ) ) ) = { B152 })) by L375 , L415;
L436: ( rng ( C98 | ( the_subsets_of_card (C24 , D68) ) ) ) = { C91 } by L435 , L406 , L408 , TARSKI:def 1;
L437: ( C50 . ( D67 + 1 ) ) c= ( C50 . D67 ) by L250;
L438: D68 c= ( C50 . D67 ) by L437 , L417 , XBOOLE_1:1;
L439: ( D68 \ { ( C51 . D67 ) } ) c= ( ( C50 . D67 ) \ { ( C51 . D67 ) } ) by L438 , XBOOLE_1:33;
L440: (not ( C51 . D67 ) in D68) by L250 , L417;
L441: D68 c= ( ( C50 . D67 ) \ { ( C51 . D67 ) } ) by L440 , L439 , ZFMISC_1:57;
L442: ( the_subsets_of_card (C24 , D68) ) c= ( the_subsets_of_card (C24 , ( ( C50 . D67 ) \ { ( C51 . D67 ) } )) ) by L441 , L32;
L443: D66 in ( the_subsets_of_card (C24 , ( ( C50 . D67 ) \ { ( C51 . D67 ) } )) ) by L442 , L434;
reconsider D74 = D66 as (Element of ( the_subsets_of_card (C24 , ( ( C50 . D67 ) \ { ( C51 . D67 ) } )) )) by L442 , L434;
L444: D74 in ( dom C98 ) by L133 , L443 , FUNCT_2:def 1;
L445: D74 in ( dom ( C98 | ( the_subsets_of_card (C24 , D68) ) ) ) by L444 , L434 , RELAT_1:57;
L446: ( ( C98 | ( the_subsets_of_card (C24 , D68) ) ) . D74 ) in ( rng ( C98 | ( the_subsets_of_card (C24 , D68) ) ) ) by L445 , FUNCT_1:3;
L447: ( ( C98 | ( the_subsets_of_card (C24 , D68) ) ) . D74 ) = C91 by L446 , L436 , TARSKI:def 1;
L448: ( C98 . D74 ) = C91 by L447 , L434 , FUNCT_1:49;
L449: ( C98 . D74 ) = ( C27 . ( D74 \/ { ( C51 . D67 ) } ) ) by L415;
thus L450: thesis by L449 , L395 , L410 , L448 , FUNCT_1:49;
end;
L451: (for B153 , B154 being set holds ((B153 in ( dom ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) ) & B154 in ( dom ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) )) implies ( ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) . B153 ) = ( ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) . B154 )))
proof
let C102 , C103 being set;
assume L452: C102 in ( dom ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) );
L453: ( ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) . C102 ) = C91 by L452 , L393;
assume L454: C103 in ( dom ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) );
thus L455: thesis by L454 , L393 , L453;
end;
thus L456: ( C27 | ( the_subsets_of_card (( C24 + 1 ) , D64) ) ) is  constant by L451 , FUNCT_1:def 10;
end;
thus L457: thesis by L128;
end;
L458: S1[ ( 0 ) ]
proof
let C104 being Nat;
let C105 being set;
set D75 = C105;
L459: D75 c= C105;
reconsider D76 = D75 as (Subset of C105) by L459;
let C106 being (Function of ( the_subsets_of_card (( 0 ) , C105) ) , C104);
assume L460: ( card C105 ) = ( omega );
assume L461: C105 c= ( omega );
assume L462: C104 <> ( 0 );
take D76;
thus L463: D76 is  infinite by L460;
L464: (for B155 , B156 being set holds ((B155 in ( dom ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) ) & B156 in ( dom ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) )) implies ( ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) . B155 ) = ( ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) . B156 )))
proof
let C107 , C108 being set;
assume L465: C107 in ( dom ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) );
L466: ( dom ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) ) = ( dom ( C106 | { ( 0 ) } ) ) by L83
.= ( ( dom C106 ) /\ { ( 0 ) } ) by RELAT_1:61;
assume L467: C108 in ( dom ( C106 | ( the_subsets_of_card (( 0 ) , D76) ) ) );
L468: C108 in { ( 0 ) } by L467 , L466 , XBOOLE_0:def 4;
L469: C108 = ( 0 ) by L468 , TARSKI:def 1;
L470: C107 in { ( 0 ) } by L466 , L465 , XBOOLE_0:def 4;
thus L471: thesis by L470 , L469 , TARSKI:def 1;
end;
thus L472: thesis by L464 , FUNCT_1:def 10;
end;
L473: (for B157 being Nat holds S1[ B157 ]) from NAT_1:sch 2(L458 , L126);
thus L474: thesis by L473;
end;
theorem
L475: (for R4 being set holds ( the_subsets_of_card (( 0 ) , R4) ) = { ( 0 ) }) by L83;
theorem
L476: (for R1 being Nat holds (for B158 being  finite set holds (( card B158 ) < R1 implies ( the_subsets_of_card (R1 , B158) ) is  empty)))
proof
let R1 being Nat;
let C109 being  finite set;
assume L477: ( card C109 ) < R1;
L478: ( card ( Seg R1 ) ) = R1 by FINSEQ_1:57;
assume L479: (not ( the_subsets_of_card (R1 , C109) ) is  empty);
consider C110 being set such that L480: C110 in ( the_subsets_of_card (R1 , C109) ) by L479 , XBOOLE_0:def 1;
L481: (ex B159 being (Subset of C109) st (C110 = B159 & ( card B159 ) = R1)) by L480;
L482: ( card ( Seg R1 ) ) c= ( card C109 ) by L481 , L478 , CARD_1:11;
L483: ( card ( Seg R1 ) ) <= ( card C109 ) by L482 , NAT_1:39;
thus L484: contradiction by L483 , L477 , FINSEQ_1:57;
end;
theorem
L485: (for R4 being set holds (for R5 being set holds (for R6 being set holds (R4 c= R5 implies ( the_subsets_of_card (R6 , R4) ) c= ( the_subsets_of_card (R6 , R5) ))))) by L32;
theorem
L486: (for R4 being set holds (for R5 being set holds ((R4 is  finite & R5 is  finite & ( card R5 ) = R4) implies ( the_subsets_of_card (R4 , R5) ) = { R5 }))) by L93;
theorem
L487: (for R4 being set holds (for R5 being set holds (for R7 being (Function of R4 , R5) holds ((R4 is non  empty & R5 is non  empty) implies (R7 is  constant iff (ex B160 being (Element of R5) st ( rng R7 ) = { B160 })))))) by FUNCT_2:111;
theorem
L488: (for R3 being Nat holds (for B161 being  finite set holds (R3 <= ( card B161 ) implies (ex B162 being (Subset of B161) st ( card B162 ) = R3))))
proof
let R3 being Nat;
let C111 being  finite set;
assume L489: R3 <= ( card C111 );
L490: ( card R3 ) <= ( card C111 ) by L489 , CARD_1:def 2;
L491: ( card R3 ) c= ( card C111 ) by L490 , NAT_1:39;
consider C112 being set such that L492: C112 c= C111 and L493: ( card C112 ) = ( card R3 ) by L491 , CARD_FIL:36;
reconsider D77 = C112 as (Subset of C111) by L492;
take D77;
thus L494: thesis by L493 , CARD_1:def 2;
end;
theorem
L495: (for R1 being Nat holds (for R2 being Nat holds (R2 >= 1 implies ( R1 + 1 ) <= ( ( R1 + R2 ) choose R2 ))))
proof
let R1 being Nat;
let R2 being Nat;
defpred S6[ Nat ] means (for B163 being (Element of ( NAT )) holds ($1 >= 1 implies ( B163 + 1 ) <= ( ( B163 + $1 ) choose $1 )));
L496: (for B164 being (Element of ( NAT )) holds (S6[ B164 ] implies S6[ ( B164 + 1 ) ]))
proof
let C113 being (Element of ( NAT ));
set D78 = ( C113 + 1 );
reconsider D79 = D78 as (Element of ( NAT ));
assume L497: S6[ C113 ];
L498: (for B165 being (Element of ( NAT )) holds (D79 >= 1 implies ( B165 + 1 ) <= ( ( B165 + D79 ) choose D79 )))
proof
let C114 being (Element of ( NAT ));
assume L499: D79 >= 1;
per cases  by L499 , NAT_1:8;
suppose L500: ( C113 + 1 ) = 1;

L501: ( C114 + 1 ) >= ( ( 0 ) + 1 ) by XREAL_1:6;
thus L502: thesis by L501 , L500 , NEWTON:23;
end;
suppose L503: C113 >= 1;

L504: ( ( C114 + D79 ) choose D79 ) = ( ( ( C114 + C113 ) + 1 ) choose ( C113 + 1 ) )
.= ( ( ( C114 + C113 ) choose ( C113 + 1 ) ) + ( ( C114 + C113 ) choose C113 ) ) by NEWTON:22;
L505: ( C114 + 1 ) <= ( ( C114 + C113 ) choose C113 ) by L497 , L503;
L506: ( ( C114 + 1 ) + ( ( C114 + C113 ) choose ( C113 + 1 ) ) ) <= ( ( C114 + D79 ) choose D79 ) by L505 , L504 , XREAL_1:6;
L507: ( ( 0 ) + ( C114 + 1 ) ) <= ( ( ( C114 + C113 ) choose ( C113 + 1 ) ) + ( C114 + 1 ) ) by XREAL_1:6;
thus L508: thesis by L507 , L506 , XXREAL_0:2;
end;
end;
thus L510: thesis by L498;
end;
reconsider D80 = R1 as (Element of ( NAT )) by ORDINAL1:def 12;
reconsider D81 = R2 as (Element of ( NAT )) by ORDINAL1:def 12;
assume L511: R2 >= 1;
L512: S6[ ( 0 ) ];
L513: (for B166 being (Element of ( NAT )) holds S6[ B166 ]) from NAT_1:sch 1(L512 , L496);
L514: ( D80 + 1 ) <= ( ( D80 + D81 ) choose D81 ) by L513 , L511;
thus L515: thesis by L514;
end;
theorem
L516: (for R1 being Nat holds (for R2 being Nat holds ((R2 >= 1 & R1 >= 1) implies ( R2 + 1 ) <= ( ( R1 + R2 ) choose R2 ))))
proof
let R1 being Nat;
let R2 being Nat;
defpred S7[ Nat ] means (for B167 being (Element of ( NAT )) holds (($1 >= 1 & B167 >= 1) implies ( $1 + 1 ) <= ( ( B167 + $1 ) choose $1 )));
assume L517: (R2 >= 1 & R1 >= 1);
reconsider D82 = R1 as (Element of ( NAT )) by ORDINAL1:def 12;
reconsider D83 = R2 as (Element of ( NAT )) by ORDINAL1:def 12;
L518: (for B168 being (Element of ( NAT )) holds (S7[ B168 ] implies S7[ ( B168 + 1 ) ]))
proof
let C115 being (Element of ( NAT ));
set D84 = ( C115 + 1 );
reconsider D85 = D84 as (Element of ( NAT ));
assume L519: S7[ C115 ];
L520: (for B169 being (Element of ( NAT )) holds ((D85 >= 1 & B169 >= 1) implies ( D85 + 1 ) <= ( ( B169 + D85 ) choose D85 )))
proof
let C116 being (Element of ( NAT ));
assume L521: D85 >= 1;
assume L522: C116 >= 1;
per cases  by L521 , NAT_1:8;
suppose L523: ( C115 + 1 ) = 1;

L524: (( C116 + 1 ) >= ( ( 0 ) + 1 ) & ( C116 + 1 ) >= ( 1 + 1 )) by L522 , XREAL_1:6;
thus L525: thesis by L524 , L523 , NEWTON:23;
end;
suppose L526: C115 >= 1;

set D86 = ( C115 + 1 );
L527: ( ( C116 + D85 ) choose D85 ) = ( ( ( C116 + C115 ) + 1 ) choose ( C115 + 1 ) )
.= ( ( ( C116 + C115 ) choose ( C115 + 1 ) ) + ( ( C116 + C115 ) choose C115 ) ) by NEWTON:22;
L528: ( C115 + 1 ) >= ( ( 0 ) + 1 ) by XREAL_1:6;
L529: ( ( C116 -' 1 ) + 1 ) <= ( ( ( C116 -' 1 ) + D86 ) choose D86 ) by L528 , L495;
L530: ( C116 - 1 ) >= ( 1 - 1 ) by L522 , XREAL_1:9;
L531: ( C116 -' 1 ) = ( C116 - 1 ) by L530 , XREAL_0:def 2;
L532: 1 <= ( ( C116 + C115 ) choose ( C115 + 1 ) ) by L531 , L522 , L529 , XXREAL_0:2;
L533: ( 1 + ( C115 + 1 ) ) <= ( ( ( C116 + C115 ) choose ( C115 + 1 ) ) + ( C115 + 1 ) ) by L532 , XREAL_1:6;
L534: ( C115 + 1 ) <= ( ( C116 + C115 ) choose C115 ) by L519 , L522 , L526;
L535: ( ( C115 + 1 ) + ( ( C116 + C115 ) choose ( C115 + 1 ) ) ) <= ( ( C116 + D85 ) choose D85 ) by L534 , L527 , XREAL_1:6;
thus L536: thesis by L535 , L533 , XXREAL_0:2;
end;
end;
thus L538: thesis by L520;
end;
L539: S7[ ( 0 ) ];
L540: (for B170 being (Element of ( NAT )) holds S7[ B170 ]) from NAT_1:sch 1(L539 , L518);
L541: ( D83 + 1 ) <= ( ( D82 + D83 ) choose D83 ) by L540 , L517;
thus L542: thesis by L541;
end;
theorem
L543: (for B171 being non  empty set holds (for B172 , B173 being (Element of B171) holds (for B174 being (a_partition of B171) holds (for B175 being (Element of B174) holds ((B172 in B175 & ( ( proj B174 ) . B172 ) = ( ( proj B174 ) . B173 )) implies B173 in B175)))))
proof
let C117 being non  empty set;
let C118 , C119 being (Element of C117);
let C120 being (a_partition of C117);
let C121 being (Element of C120);
assume L544: C118 in C121;
assume L545: ( ( proj C120 ) . C118 ) = ( ( proj C120 ) . C119 );
L546: ( ( proj C120 ) . C119 ) = C121 by L545 , L544 , EQREL_1:65;
assume L547: (not C119 in C121);
L548: ( union C120 ) = C117 by EQREL_1:def 4;
consider C122 being set such that L549: C119 in C122 and L550: C122 in C120 by L548 , TARSKI:def 4;
reconsider D87 = C122 as (Element of C120) by L550;
L551: ( ( proj C120 ) . C119 ) = D87 by L549 , EQREL_1:65;
per cases  by EQREL_1:def 4;
suppose L552: C121 = D87;

thus L553: contradiction by L552 , L547 , L549;
end;
suppose L554: C121 misses D87;

L555: ( C121 /\ C121 ) = ( {} ) by L554 , L546 , L551 , XBOOLE_0:def 7;
thus L556: contradiction by L555 , EQREL_1:def 4;
end;
end;
begin
theorem
L558: (for R1 being Nat holds (for R3 being Nat holds (for R4 being set holds (for B176 being (Function of ( the_subsets_of_card (R1 , R4) ) , R3) holds ((R3 <> ( 0 ) & R4 is  infinite) implies (ex R8 being (Subset of R4) st (R8 is  infinite & ( B176 | ( the_subsets_of_card (R1 , R8) ) ) is  constant)))))))
proof
let R1 being Nat;
let R3 being Nat;
let R4 being set;
let C123 being (Function of ( the_subsets_of_card (R1 , R4) ) , R3);
assume that
L559: R3 <> ( 0 )
and
L560: R4 is  infinite;
L561: C123 in ( Funcs (( the_subsets_of_card (R1 , R4) ) , R3) ) by L559 , FUNCT_2:8;
L562: (ex B177 being Function st (C123 = B177 & ( dom B177 ) = ( the_subsets_of_card (R1 , R4) ) & ( rng B177 ) c= R3)) by L561 , FUNCT_2:def 2;
consider C124 being set such that L563: C124 c= R4 and L564: ( card C124 ) = ( omega ) by L560 , CARD_3:87;
reconsider D88 = C124 as non  empty set by L564;
L565: D88 , ( omega ) are_equipotent  by L564 , CARD_1:5 , CARD_1:47;
consider C125 being Function such that L566: C125 is  one-to-one and L567: ( dom C125 ) = ( omega ) and L568: ( rng C125 ) = D88 by L565 , WELLORD2:def 4;
reconsider D89 = C125 as (Function of ( omega ) , D88) by L567 , L568 , FUNCT_2:1;
L569: (not ( card D88 ) c= ( card R1 )) by L564;
L570: ( the_subsets_of_card (R1 , D88) ) is non  empty by L569 , GROUP_10:1;
L571: ( D89 ||^ R1 ) in ( Funcs (( the_subsets_of_card (R1 , ( omega )) ) , ( the_subsets_of_card (R1 , D88) )) ) by L570 , FUNCT_2:8;
L572: (ex B178 being Function st (( D89 ||^ R1 ) = B178 & ( dom B178 ) = ( the_subsets_of_card (R1 , ( omega )) ) & ( rng B178 ) c= ( the_subsets_of_card (R1 , D88) ))) by L571 , FUNCT_2:def 2;
set D90 = ( C123 * ( D89 ||^ R1 ) );
L573: ( the_subsets_of_card (R1 , D88) ) c= ( the_subsets_of_card (R1 , R4) ) by L563 , L32;
L574: ( dom D90 ) = ( the_subsets_of_card (R1 , ( omega )) ) by L573 , L562 , L572 , RELAT_1:27 , XBOOLE_1:1;
L575: ( rng D90 ) c= ( rng C123 ) by RELAT_1:26;
L576: ( rng D90 ) c= R3 by L575 , L562 , XBOOLE_1:1;
reconsider D91 = D90 as (Function of ( the_subsets_of_card (R1 , ( omega )) ) , R3) by L562 , L574 , L575 , FUNCT_2:2 , XBOOLE_1:1;
consider C126 being (Subset of ( omega )) such that L577: C126 is  infinite and L578: ( D91 | ( the_subsets_of_card (R1 , C126) ) ) is  constant by L559 , L125 , CARD_1:47;
L579: ( rng ( D91 | ( the_subsets_of_card (R1 , C126) ) ) ) c= ( rng D91 ) by RELAT_1:70;
set D92 = ( D89 .: C126 );
L580: ( D89 .: C126 ) c= ( rng D89 ) by RELAT_1:111;
reconsider D93 = D92 as (Subset of R4) by L580 , L563 , L568 , XBOOLE_1:1;
take D93;
L581: C126 , ( D89 .: C126 ) are_equipotent  by L566 , L567 , CARD_1:33;
thus L582: D93 is  infinite by L581 , L577 , CARD_1:38;
L583: ( dom ( D91 | ( the_subsets_of_card (R1 , C126) ) ) ) = ( the_subsets_of_card (R1 , C126) ) by L574 , L32 , RELAT_1:62;
L584: ( D91 | ( the_subsets_of_card (R1 , C126) ) ) is (Function of ( the_subsets_of_card (R1 , C126) ) , R3) by L583 , L576 , L579 , FUNCT_2:2 , XBOOLE_1:1;
consider C127 being (Element of R3) such that L585: ( rng ( D91 | ( the_subsets_of_card (R1 , C126) ) ) ) = { C127 } by L584 , L559 , L577 , L578 , FUNCT_2:111;
L586: (not ( card ( omega ) ) c= ( card R1 ));
L587: (ex B179 being (Element of R3) st ( rng ( C123 | ( the_subsets_of_card (R1 , D93) ) ) ) = { B179 })
proof
take C127;
thus L588: ( rng ( C123 | ( the_subsets_of_card (R1 , D93) ) ) ) = ( C123 .: ( the_subsets_of_card (R1 , D93) ) ) by RELAT_1:115
.= ( C123 .: ( ( D89 ||^ R1 ) .: ( the_subsets_of_card (R1 , C126) ) ) ) by L566 , L586 , L41
.= ( D91 .: ( the_subsets_of_card (R1 , C126) ) ) by RELAT_1:126
.= { C127 } by L585 , RELAT_1:115;
end;
thus L589: thesis by L587;
end;
::$N Ramsey's Theorem
theorem
L590: (for R1 being Nat holds (for R3 being Nat holds (for B180 being  infinite set holds (for B181 being (a_partition of ( the_subsets_of_card (R1 , B180) )) holds (( card B181 ) = R3 implies (ex B182 being (Subset of B180) st (B182 is  infinite & B182 is_homogeneous_for B181)))))))
proof
let R1 being Nat;
let R3 being Nat;
let C128 being  infinite set;
let C129 being (a_partition of ( the_subsets_of_card (R1 , C128) ));
assume L591: ( card C129 ) = R3;
L592: C129 , R3 are_equipotent  by L591 , CARD_1:def 2;
consider C130 being Function such that L593: C130 is  one-to-one and L594: ( dom C130 ) = C129 and L595: ( rng C130 ) = R3 by L592 , WELLORD2:def 4;
reconsider D94 = C130 as (Function of C129 , R3) by L594 , L595 , FUNCT_2:1;
set D95 = ( D94 * ( proj C129 ) );
reconsider D96 = D95 as (Function of ( the_subsets_of_card (R1 , C128) ) , R3);
consider C131 being (Subset of C128) such that L596: C131 is  infinite and L597: ( D96 | ( the_subsets_of_card (R1 , C131) ) ) is  constant by L591 , L558;
take C131;
thus L598: C131 is  infinite by L596;
set D97 = the (Element of ( the_subsets_of_card (R1 , C131) ));
L599: ( the_subsets_of_card (R1 , C131) ) is non  empty by L596;
L600: D97 in ( the_subsets_of_card (R1 , C131) ) by L599;
L601: ( the_subsets_of_card (R1 , C131) ) c= ( the_subsets_of_card (R1 , C128) ) by L32;
reconsider D98 = D97 as (Element of ( the_subsets_of_card (R1 , C128) )) by L601 , L600;
set D99 = ( EqClass (D98 , C129) );
reconsider D100 = D99 as (Element of C129) by EQREL_1:def 6;
L602: (for B183 being set holds (B183 in ( the_subsets_of_card (R1 , C131) ) implies B183 in D100))
proof
let C132 being set;
assume L603: C132 in ( the_subsets_of_card (R1 , C131) );
reconsider D101 = C132 as (Element of ( the_subsets_of_card (R1 , C128) )) by L603 , L601;
L604: ( dom D96 ) = ( the_subsets_of_card (R1 , C128) ) by L591 , FUNCT_2:def 1;
L605: D98 in ( ( dom D96 ) /\ ( the_subsets_of_card (R1 , C131) ) ) by L604 , L596 , XBOOLE_0:def 4;
L606: D98 in ( dom ( D96 | ( the_subsets_of_card (R1 , C131) ) ) ) by L605 , RELAT_1:61;
L607: D101 in ( ( dom D96 ) /\ ( the_subsets_of_card (R1 , C131) ) ) by L603 , L604 , XBOOLE_0:def 4;
L608: D101 in ( dom ( D96 | ( the_subsets_of_card (R1 , C131) ) ) ) by L607 , RELAT_1:61;
L609: ( D96 . D101 ) = ( ( D96 | ( the_subsets_of_card (R1 , C131) ) ) . D101 ) by L603 , FUNCT_1:49
.= ( ( D96 | ( the_subsets_of_card (R1 , C131) ) ) . D98 ) by L597 , L608 , L606 , FUNCT_1:def 10
.= ( D96 . D98 ) by L596 , FUNCT_1:49;
L610: ( D94 . ( ( proj C129 ) . D101 ) ) = ( ( D94 * ( proj C129 ) ) . D98 ) by L609 , L604 , FUNCT_1:12
.= ( D94 . ( ( proj C129 ) . D98 ) ) by L604 , FUNCT_1:12;
L611: (D98 in D100 & ( ( proj C129 ) . D98 ) = ( ( proj C129 ) . D101 )) by L610 , L593 , L594 , EQREL_1:def 6 , FUNCT_1:def 4;
thus L612: thesis by L611 , L543;
end;
L613: ( the_subsets_of_card (R1 , C131) ) c= D100 by L602 , TARSKI:def 3;
thus L614: thesis by L613 , L1;
end;
begin
scheme BinInd2 { P1[Nat , Nat] } : (for R2 being Nat holds (for R1 being Nat holds P1[ R2 , R1 ]))
provided
L615: (for R1 being Nat holds (P1[ ( 0 ) , R1 ] & P1[ R1 , ( 0 ) ]))
and
L616: (for R2 being Nat holds (for R1 being Nat holds ((P1[ ( R2 + 1 ) , R1 ] & P1[ R2 , ( R1 + 1 ) ]) implies P1[ ( R2 + 1 ) , ( R1 + 1 ) ])))
proof
defpred S8[ Nat ] means (for B184 , B185 being Nat holds (( B184 + B185 ) = $1 implies P1[ B184 , B185 ]));
L617: (for B186 being (Element of ( NAT )) holds (S8[ B186 ] implies S8[ ( B186 + 1 ) ]))
proof
let C133 being (Element of ( NAT ));
assume L618: S8[ C133 ];
L619: (for B187 , B188 being Nat holds (( B187 + B188 ) = ( C133 + 1 ) implies P1[ B187 , B188 ]))
proof
let C134 , C135 being Nat;
assume L620: ( C134 + C135 ) = ( C133 + 1 );
per cases ;
suppose L621: (C134 = ( 0 ) or C135 = ( 0 ));

thus L622: thesis by L621 , L615;
end;
suppose L623: (C134 <> ( 0 ) & C135 <> ( 0 ));

reconsider D102 = ( C134 - 1 ) as (Element of ( NAT )) by L623 , NAT_1:20;
reconsider D103 = ( C135 - 1 ) as (Element of ( NAT )) by L623 , NAT_1:20;
L624: ( D102 + C135 ) = C133 by L620;
L625: P1[ D102 , ( D103 + 1 ) ] by L624 , L618;
L626: ( C134 + D103 ) = C133 by L620;
L627: P1[ ( D102 + 1 ) , D103 ] by L626 , L618;
thus L628: thesis by L627 , L616 , L625;
end;
end;
thus L630: thesis by L619;
end;
let R2 being Nat;
let R1 being Nat;
set D104 = ( R2 + R1 );
reconsider D105 = D104 as (Element of ( NAT )) by ORDINAL1:def 12;
L631: S8[ ( 0 ) ]
proof
let C136 , C137 being Nat;
assume L632: ( C136 + C137 ) = ( 0 );
L633: C136 = ( 0 ) by L632;
thus L634: thesis by L633 , L615;
end;
L635: (for B189 being (Element of ( NAT )) holds S8[ B189 ]) from NAT_1:sch 1(L631 , L617);
L636: S8[ D105 ] by L635;
thus L637: thesis by L636;
end;
theorem
L638: (for R2 being Nat holds (for R1 being Nat holds ((R2 >= 2 & R1 >= 2) implies (ex B190 being Nat st (B190 <= ( ( ( R2 + R1 ) -' 2 ) choose ( R2 -' 1 ) ) & B190 >= 2 & (for B191 being  finite set holds (for B192 being (Function of ( the_subsets_of_card (2 , B191) ) , ( Seg 2 )) holds (( card B191 ) >= B190 implies (ex B193 being (Subset of B191) st ((( card B193 ) >= R2 & ( rng ( B192 | ( the_subsets_of_card (2 , B193) ) ) ) = { 1 }) or (( card B193 ) >= R1 & ( rng ( B192 | ( the_subsets_of_card (2 , B193) ) ) ) = { 2 })))))))))))
proof
let R2 being Nat;
let R1 being Nat;
defpred S9[ Nat , Nat ] means (($1 >= 2 & $2 >= 2) implies (ex B194 being Nat st (B194 <= ( ( ( $1 + $2 ) -' 2 ) choose ( $1 -' 1 ) ) & B194 >= 2 & (for B195 being  finite set holds (for B196 being (Function of ( the_subsets_of_card (2 , B195) ) , ( Seg 2 )) holds (( card B195 ) >= B194 implies (ex B197 being (Subset of B195) st ((( card B197 ) >= $1 & ( rng ( B196 | ( the_subsets_of_card (2 , B197) ) ) ) = { 1 }) or (( card B197 ) >= $2 & ( rng ( B196 | ( the_subsets_of_card (2 , B197) ) ) ) = { 2 })))))))));
L639: (for B198 , B199 being Nat holds ((S9[ ( B198 + 1 ) , B199 ] & S9[ B198 , ( B199 + 1 ) ]) implies S9[ ( B198 + 1 ) , ( B199 + 1 ) ]))
proof
let C138 , C139 being Nat;
assume L640: S9[ ( C138 + 1 ) , C139 ];
assume L641: S9[ C138 , ( C139 + 1 ) ];
assume that
L642: ( C138 + 1 ) >= 2
and
L643: ( C139 + 1 ) >= 2;
per cases  by XXREAL_0:1;
suppose L644: (( C138 + 1 ) < 2 or ( C139 + 1 ) < 2);

thus L645: thesis by L644 , L642 , L643;
end;
suppose L646: ( C138 + 1 ) = 2;

set D106 = ( C139 + 1 );
take D106;
L647: ( ( C138 + 1 ) + ( C139 + 1 ) ) >= ( 2 + 2 ) by L642 , L643 , XREAL_1:7;
L648: ( ( ( C138 + 1 ) + ( C139 + 1 ) ) - 2 ) >= ( 4 - 2 ) by L647 , XREAL_1:9;
L649: ( C138 + C139 ) = ( ( ( C138 + 1 ) + ( C139 + 1 ) ) -' 2 ) by L648 , XREAL_0:def 2;
L650: (( ( C138 + 1 ) -' 1 ) = C138 & ( ( C138 + 1 ) - 1 ) >= ( 2 - 1 )) by L642 , NAT_D:34 , XREAL_1:9;
thus L651: D106 <= ( ( ( ( C138 + 1 ) + ( C139 + 1 ) ) -' 2 ) choose ( ( C138 + 1 ) -' 1 ) ) by L650 , L649 , L495;
thus L652: D106 >= 2 by L643;
let C140 being  finite set;
let C141 being (Function of ( the_subsets_of_card (2 , C140) ) , ( Seg 2 ));
assume L653: ( card C140 ) >= D106;
L654: C141 in ( Funcs (( the_subsets_of_card (2 , C140) ) , ( Seg 2 )) ) by FUNCT_2:8;
L655: (ex B200 being Function st (C141 = B200 & ( dom B200 ) = ( the_subsets_of_card (2 , C140) ) & ( rng B200 ) c= ( Seg 2 ))) by L654 , FUNCT_2:def 2;
per cases ;
suppose L656: (not 1 in ( rng C141 ));

consider C142 being (Subset of C140) such that L657: ( card C142 ) = D106 by L653 , L488;
L658: ( card 2 ) <= ( card C142 ) by L643 , L657 , CARD_1:def 2;
L659: ( card 2 ) c= ( card C142 ) by L658 , NAT_1:39;
L660: ( the_subsets_of_card (2 , C142) ) is non  empty by L659 , L657 , CARD_1:27 , GROUP_10:1;
L661: (ex B201 being set st B201 in ( the_subsets_of_card (2 , C142) )) by L660 , XBOOLE_0:def 1;
take C142;
L662: ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ) c= ( rng C141 ) by RELAT_1:70;
L663: ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ) c= { 1 , 2 } by L662 , L655 , FINSEQ_1:2 , XBOOLE_1:1;
L664: ( the_subsets_of_card (2 , C142) ) c= ( the_subsets_of_card (2 , C140) ) by L32;
L665: ( C141 | ( the_subsets_of_card (2 , C142) ) ) <> ( {} ) by L664 , L655 , L661;
L666:
now
let C143 being set;
L667: (( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ) = ( {} ) or ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ) = { 1 } or ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ) = { 2 } or ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ) = { 1 , 2 }) by L663 , ZFMISC_1:36;
thus L668:now
assume L669: C143 in ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) );
L670: (C143 = 1 or C143 = 2) by L669 , L663 , TARSKI:def 2;
thus L671: C143 = 2 by L670 , L656 , L662 , L669;
end;
assume L672: C143 = 2;
L673: (not 1 in ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) )) by L656 , L662;
assume L674: (not C143 in ( rng ( C141 | ( the_subsets_of_card (2 , C142) ) ) ));
thus L675: contradiction by L674 , L665 , L672 , L673 , L667 , TARSKI:def 1 , TARSKI:def 2;
end;
thus L676: thesis by L666 , L657 , TARSKI:def 1;
end;
suppose L677: 1 in ( rng C141 );

consider C144 being set such that L678: C144 in ( dom C141 ) and L679: 1 = ( C141 . C144 ) by L677 , FUNCT_1:def 3;
L680: C144 in { B202 where B202 is (Subset of C140) : ( card B202 ) = 2 } by L678;
L681: (ex B203 being (Subset of C140) st (C144 = B203 & ( card B203 ) = 2)) by L680;
reconsider D107 = C144 as (Subset of C140) by L681;
L682: ( the_subsets_of_card (2 , D107) ) = { D107 } by L681 , L93;
L683: D107 in ( the_subsets_of_card (2 , D107) ) by L682 , TARSKI:def 1;
L684: ( ( C141 | ( the_subsets_of_card (2 , D107) ) ) . D107 ) = 1 by L683 , L679 , FUNCT_1:49;
take D107;
L685: { D107 } c= ( dom C141 ) by L678 , ZFMISC_1:31;
L686: ( dom ( C141 | ( the_subsets_of_card (2 , D107) ) ) ) = ( ( dom C141 ) /\ ( the_subsets_of_card (2 , D107) ) ) by RELAT_1:61
.= ( ( dom C141 ) /\ { D107 } ) by L681 , L93
.= { D107 } by L685 , XBOOLE_1:28;
thus L687: thesis by L686 , L646 , L681 , L684 , FUNCT_1:4;
end;
end;
suppose L689: ( C139 + 1 ) = 2;

set D108 = ( C138 + 1 );
take D108;
L690: ( ( C139 + 1 ) - 1 ) >= ( 2 - 1 ) by L643 , XREAL_1:9;
L691: ( ( C138 + 1 ) + ( C139 + 1 ) ) >= ( 2 + 2 ) by L642 , L643 , XREAL_1:7;
L692: ( ( ( C138 + 1 ) + ( C139 + 1 ) ) - 2 ) >= ( 4 - 2 ) by L691 , XREAL_1:9;
L693: ( C138 + C139 ) = ( ( ( C138 + 1 ) + ( C139 + 1 ) ) -' 2 ) by L692 , XREAL_0:def 2;
L694: (( ( C138 + 1 ) -' 1 ) = C138 & ( ( C138 + 1 ) - 1 ) >= ( 2 - 1 )) by L642 , NAT_D:34 , XREAL_1:9;
thus L695: D108 <= ( ( ( ( C138 + 1 ) + ( C139 + 1 ) ) -' 2 ) choose ( ( C138 + 1 ) -' 1 ) ) by L694 , L693 , L690 , L516;
thus L696: D108 >= 2 by L642;
let C145 being  finite set;
let C146 being (Function of ( the_subsets_of_card (2 , C145) ) , ( Seg 2 ));
assume L697: ( card C145 ) >= D108;
L698: C146 in ( Funcs (( the_subsets_of_card (2 , C145) ) , ( Seg 2 )) ) by FUNCT_2:8;
L699: (ex B204 being Function st (C146 = B204 & ( dom B204 ) = ( the_subsets_of_card (2 , C145) ) & ( rng B204 ) c= ( Seg 2 ))) by L698 , FUNCT_2:def 2;
per cases ;
suppose L700: (not 2 in ( rng C146 ));

consider C147 being (Subset of C145) such that L701: ( card C147 ) = D108 by L697 , L488;
L702: ( card 2 ) <= ( card C147 ) by L642 , L701 , CARD_1:def 2;
L703: ( card 2 ) c= ( card C147 ) by L702 , NAT_1:39;
L704: ( the_subsets_of_card (2 , C147) ) is non  empty by L703 , L701 , CARD_1:27 , GROUP_10:1;
L705: (ex B205 being set st B205 in ( the_subsets_of_card (2 , C147) )) by L704 , XBOOLE_0:def 1;
take C147;
L706: ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ) c= ( rng C146 ) by RELAT_1:70;
L707: ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ) c= { 1 , 2 } by L706 , L699 , FINSEQ_1:2 , XBOOLE_1:1;
L708: ( the_subsets_of_card (2 , C147) ) c= ( the_subsets_of_card (2 , C145) ) by L32;
L709: ( C146 | ( the_subsets_of_card (2 , C147) ) ) <> ( {} ) by L708 , L699 , L705;
L710:
now
let C148 being set;
L711: (( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ) = ( {} ) or ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ) = { 1 } or ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ) = { 2 } or ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ) = { 1 , 2 }) by L707 , ZFMISC_1:36;
thus L712:now
assume L713: C148 in ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) );
L714: (C148 = 1 or C148 = 2) by L713 , L707 , TARSKI:def 2;
thus L715: C148 = 1 by L714 , L700 , L706 , L713;
end;
assume L716: C148 = 1;
L717: (not 2 in ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) )) by L700 , L706;
assume L718: (not C148 in ( rng ( C146 | ( the_subsets_of_card (2 , C147) ) ) ));
thus L719: contradiction by L718 , L709 , L716 , L717 , L711 , TARSKI:def 1 , TARSKI:def 2;
end;
thus L720: thesis by L710 , L701 , TARSKI:def 1;
end;
suppose L721: 2 in ( rng C146 );

consider C149 being set such that L722: C149 in ( dom C146 ) and L723: 2 = ( C146 . C149 ) by L721 , FUNCT_1:def 3;
L724: C149 in { B206 where B206 is (Subset of C145) : ( card B206 ) = 2 } by L722;
L725: (ex B207 being (Subset of C145) st (C149 = B207 & ( card B207 ) = 2)) by L724;
reconsider D109 = C149 as (Subset of C145) by L725;
L726: ( the_subsets_of_card (2 , D109) ) = { D109 } by L725 , L93;
L727: D109 in ( the_subsets_of_card (2 , D109) ) by L726 , TARSKI:def 1;
L728: ( ( C146 | ( the_subsets_of_card (2 , D109) ) ) . D109 ) = 2 by L727 , L723 , FUNCT_1:49;
take D109;
L729: { D109 } c= ( dom C146 ) by L722 , ZFMISC_1:31;
L730: ( dom ( C146 | ( the_subsets_of_card (2 , D109) ) ) ) = ( ( dom C146 ) /\ ( the_subsets_of_card (2 , D109) ) ) by RELAT_1:61
.= ( ( dom C146 ) /\ { D109 } ) by L725 , L93
.= { D109 } by L729 , XBOOLE_1:28;
thus L731: thesis by L730 , L689 , L725 , L728 , FUNCT_1:4;
end;
end;
suppose L733: (( C138 + 1 ) > 2 & ( C139 + 1 ) > 2);

set D110 = ( ( C138 + C139 ) -' 1 );
set D111 = ( C138 -' 1 );
L734: ( ( C138 + 1 ) - 2 ) >= ( 2 - 2 ) by L642 , XREAL_1:9;
L735: ( C138 -' 1 ) = ( C138 - 1 ) by L734 , XREAL_0:def 2;
L736: ( ( C138 + 1 ) -' 1 ) = ( D111 + 1 ) by L735 , NAT_D:34;
L737: ( ( C138 + 1 ) + ( C139 + 1 ) ) >= ( 2 + 2 ) by L642 , L643 , XREAL_1:7;
L738: ( ( ( C138 + C139 ) + 2 ) - 3 ) >= ( 4 - 3 ) by L737 , XREAL_1:9;
L739: ( ( C138 + C139 ) -' 1 ) = ( ( C138 + C139 ) - 1 ) by L738 , XREAL_0:def 2;
L740: ( ( ( C138 + C139 ) + 1 ) -' 2 ) = ( ( ( C138 + C139 ) + 1 ) - 2 ) by L738 , XREAL_0:def 2;
L741: ( C138 + C139 ) >= ( 0 );
L742: ( ( ( C138 + 1 ) + ( C139 + 1 ) ) -' 2 ) = ( ( ( C138 + 1 ) + ( C139 + 1 ) ) - 2 ) by L741 , XREAL_0:def 2
.= ( D110 + 1 ) by L739;
consider C150 being Nat such that L743: C150 <= ( ( ( C138 + ( C139 + 1 ) ) -' 2 ) choose ( C138 -' 1 ) ) and L744: C150 >= 2 and L745: (for B208 being  finite set holds (for B209 being (Function of ( the_subsets_of_card (2 , B208) ) , ( Seg 2 )) holds (( card B208 ) >= C150 implies (ex B210 being (Subset of B208) st ((( card B210 ) >= C138 & ( rng ( B209 | ( the_subsets_of_card (2 , B210) ) ) ) = { 1 }) or (( card B210 ) >= ( C139 + 1 ) & ( rng ( B209 | ( the_subsets_of_card (2 , B210) ) ) ) = { 2 })))))) by L641 , L733 , NAT_1:13;
consider C151 being Nat such that L746: C151 <= ( ( ( ( C138 + 1 ) + C139 ) -' 2 ) choose ( ( C138 + 1 ) -' 1 ) ) and L747: C151 >= 2 and L748: (for B211 being  finite set holds (for B212 being (Function of ( the_subsets_of_card (2 , B211) ) , ( Seg 2 )) holds (( card B211 ) >= C151 implies (ex B213 being (Subset of B211) st ((( card B213 ) >= ( C138 + 1 ) & ( rng ( B212 | ( the_subsets_of_card (2 , B213) ) ) ) = { 1 }) or (( card B213 ) >= C139 & ( rng ( B212 | ( the_subsets_of_card (2 , B213) ) ) ) = { 2 })))))) by L640 , L733 , NAT_1:13;
set D112 = ( C151 + C150 );
take D112;
L749: ( C151 + C150 ) <= ( ( ( ( ( C138 + 1 ) + C139 ) -' 2 ) choose ( ( C138 + 1 ) -' 1 ) ) + ( ( ( C138 + ( C139 + 1 ) ) -' 2 ) choose ( C138 -' 1 ) ) ) by L746 , L743 , XREAL_1:7;
thus L750: D112 <= ( ( ( ( C138 + 1 ) + ( C139 + 1 ) ) -' 2 ) choose ( ( C138 + 1 ) -' 1 ) ) by L749 , L739 , L740 , L742 , L736 , NEWTON:22;
L751: ( C151 + C150 ) >= ( ( 0 ) + 2 ) by L747 , XREAL_1:7;
thus L752: D112 >= 2 by L751;
let C152 being  finite set;
let C153 being (Function of ( the_subsets_of_card (2 , C152) ) , ( Seg 2 ));
assume L753: ( card C152 ) >= D112;
consider C154 being (Subset of C152) such that L754: ( card C154 ) = D112 by L753 , L488;
consider C155 being set such that L755: C155 in C154 by L747 , L754 , CARD_1:27 , XBOOLE_0:def 1;
set D113 = { B214 where B214 is (Element of C154) : (( C153 . { C155 , B214 } ) = 2 & { C155 , B214 } in ( dom C153 )) };
set D114 = { B215 where B215 is (Element of C154) : (( C153 . { C155 , B215 } ) = 1 & { C155 , B215 } in ( dom C153 )) };
L756: C153 in ( Funcs (( the_subsets_of_card (2 , C152) ) , ( Seg 2 )) ) by FUNCT_2:8;
L757: (ex B216 being Function st (C153 = B216 & ( dom B216 ) = ( the_subsets_of_card (2 , C152) ) & ( rng B216 ) c= ( Seg 2 ))) by L756 , FUNCT_2:def 2;
L758: (for B217 being set holds (B217 in ( D114 \/ D113 ) iff B217 in ( C154 \ { C155 } )))
proof
let C156 being set;
thus L759:now
assume L760: C156 in ( D114 \/ D113 );
per cases  by L760 , XBOOLE_0:def 3;
suppose L761: C156 in D114;

consider C157 being (Element of C154) such that L762: C156 = C157 and L763: ( C153 . { C155 , C157 } ) = 1 and L764: { C155 , C157 } in ( dom C153 ) by L761;
L765:
now
assume L766: C156 in { C155 };
L767: C156 = C155 by L766 , TARSKI:def 1;
L768: { C155 , C157 } = ( { C155 } \/ { C157 } ) by ENUMSET1:1
.= { C155 } by L762 , L767;
L769: { C155 } in ( the_subsets_of_card (2 , C152) ) by L768 , L764;
L770: (ex B218 being (Subset of C152) st (B218 = { C155 } & ( card B218 ) = 2)) by L769;
thus L771: contradiction by L770 , CARD_1:30;
end;
thus L772: C156 in ( C154 \ { C155 } ) by L765 , L747 , L754 , L762 , CARD_1:27 , XBOOLE_0:def 5;
end;
suppose L773: C156 in D113;

consider C158 being (Element of C154) such that L774: C156 = C158 and L775: ( C153 . { C155 , C158 } ) = 2 and L776: { C155 , C158 } in ( dom C153 ) by L773;
L777:
now
assume L778: C156 in { C155 };
L779: C156 = C155 by L778 , TARSKI:def 1;
L780: { C155 , C158 } = ( { C155 } \/ { C158 } ) by ENUMSET1:1
.= { C155 } by L774 , L779;
L781: { C155 } in ( the_subsets_of_card (2 , C152) ) by L780 , L776;
L782: (ex B219 being (Subset of C152) st (B219 = { C155 } & ( card B219 ) = 2)) by L781;
thus L783: contradiction by L782 , CARD_1:30;
end;
thus L784: C156 in ( C154 \ { C155 } ) by L777 , L747 , L754 , L774 , CARD_1:27 , XBOOLE_0:def 5;
end;
end;
assume L786: C156 in ( C154 \ { C155 } );
reconsider D115 = C156 as (Element of C154) by L786 , XBOOLE_0:def 5;
L787: (not D115 in { C155 }) by L786 , XBOOLE_0:def 5;
L788: C155 <> D115 by L787 , TARSKI:def 1;
L789: ( card { C155 , D115 } ) = 2 by L788 , CARD_2:57;
L790: { C155 , D115 } c= C154 by L755 , ZFMISC_1:32;
L791: { C155 , D115 } is (Subset of C152) by L790 , XBOOLE_1:1;
L792: { C155 , D115 } in ( dom C153 ) by L791 , L757 , L789;
L793: ( C153 . { C155 , D115 } ) in ( rng C153 ) by L792 , FUNCT_1:3;
per cases  by L757 , L793 , FINSEQ_1:2 , TARSKI:def 2;
suppose L794: ( C153 . { C155 , D115 } ) = 1;

L795: C156 in D114 by L794 , L792;
thus L796: thesis by L795 , XBOOLE_0:def 3;
end;
suppose L797: ( C153 . { C155 , D115 } ) = 2;

L798: C156 in D113 by L797 , L792;
thus L799: thesis by L798 , XBOOLE_0:def 3;
end;
end;
L801:
now
assume L802: ( D114 /\ D113 ) <> ( {} );
consider C159 being set such that L803: C159 in ( D114 /\ D113 ) by L802 , XBOOLE_0:def 1;
L804: C159 in D113 by L803 , XBOOLE_0:def 4;
L805: (ex B220 being (Element of C154) st (C159 = B220 & ( C153 . { C155 , B220 } ) = 2 & { C155 , B220 } in ( dom C153 ))) by L804;
L806: C159 in D114 by L803 , XBOOLE_0:def 4;
L807: (ex B221 being (Element of C154) st (C159 = B221 & ( C153 . { C155 , B221 } ) = 1 & { C155 , B221 } in ( dom C153 ))) by L806;
thus L808: contradiction by L807 , L805;
end;
L809: ( C154 \ { C155 } ) c= C154 by XBOOLE_1:36;
L810: ( D114 \/ D113 ) c= C154 by L809 , L758 , TARSKI:1;
L811: { C155 } c= C154 by L755 , ZFMISC_1:31;
L812: ( card ( C154 \ { C155 } ) ) = ( ( card C154 ) - ( card { C155 } ) ) by L811 , CARD_2:44
.= ( ( C151 + C150 ) - 1 ) by L754 , CARD_1:30;
reconsider D116 = D113 as  finite (Subset of C154) by L810 , XBOOLE_1:11;
reconsider D117 = D114 as  finite (Subset of C154) by L810 , XBOOLE_1:11;
L813: ( card ( D117 \/ D116 ) ) = ( ( ( card D117 ) + ( card D116 ) ) - ( card ( {} ) ) ) by L801 , CARD_2:45
.= ( ( card D117 ) + ( card D116 ) );
L814: ( ( card D117 ) + ( card D116 ) ) = ( ( C151 + C150 ) - 1 ) by L813 , L758 , L812 , TARSKI:1;
L815: (( card D117 ) >= C150 or ( card D116 ) >= C151)
proof
assume L816: ( card D117 ) < C150;
L817: ( ( card D117 ) + 1 ) <= C150 by L816 , NAT_1:13;
assume L818: ( card D116 ) < C151;
L819: ( ( ( card D117 ) + 1 ) + ( card D116 ) ) < ( C150 + C151 ) by L818 , L817 , XREAL_1:8;
thus L820: contradiction by L819 , L814;
end;
per cases  by L815;
suppose L821: ( card D117 ) >= C150;

set D118 = ( C153 | ( the_subsets_of_card (2 , D117) ) );
L822: D117 c= C152 by XBOOLE_1:1;
L823: ( ( the_subsets_of_card (2 , C152) ) /\ ( the_subsets_of_card (2 , D117) ) ) = ( the_subsets_of_card (2 , D117) ) by L822 , L32 , XBOOLE_1:28;
L824: ( dom ( C153 | ( the_subsets_of_card (2 , D117) ) ) ) = ( the_subsets_of_card (2 , D117) ) by L823 , L757 , RELAT_1:61;
L825: ( rng ( C153 | ( the_subsets_of_card (2 , D117) ) ) ) c= ( rng C153 ) by RELAT_1:70;
reconsider D119 = D118 as (Function of ( the_subsets_of_card (2 , D117) ) , ( Seg 2 )) by L825 , L757 , L824 , FUNCT_2:2 , XBOOLE_1:1;
consider C160 being (Subset of D117) such that L826: ((( card C160 ) >= C138 & ( rng ( D119 | ( the_subsets_of_card (2 , C160) ) ) ) = { 1 }) or (( card C160 ) >= ( C139 + 1 ) & ( rng ( D119 | ( the_subsets_of_card (2 , C160) ) ) ) = { 2 })) by L745 , L821;
L827: ( D119 | ( the_subsets_of_card (2 , C160) ) ) = ( C153 | ( the_subsets_of_card (2 , C160) ) ) by L32 , RELAT_1:74;
L828: D117 c= C152 by XBOOLE_1:1;
reconsider D120 = C160 as (Subset of C152) by L828 , XBOOLE_1:1;
per cases  by L826;
suppose L829: (( card D120 ) >= ( C139 + 1 ) & ( rng ( D119 | ( the_subsets_of_card (2 , D120) ) ) ) = { 2 });

take D120;
thus L830: thesis by L829 , L32 , RELAT_1:74;
end;
suppose L831: (( card D120 ) >= C138 & ( rng ( D119 | ( the_subsets_of_card (2 , D120) ) ) ) = { 1 });

set D121 = ( D120 \/ { C155 } );
L832: { C155 } c= C152 by L755 , ZFMISC_1:31;
reconsider D122 = D121 as (Subset of C152) by L832 , XBOOLE_1:8;
L833: ( the_subsets_of_card (2 , D120) ) c= ( the_subsets_of_card (2 , D122) ) by L32 , XBOOLE_1:7;
L834: ( rng ( C153 | ( the_subsets_of_card (2 , D120) ) ) ) = { 1 } by L831 , L32 , RELAT_1:74;
L835: (for B222 being set holds (B222 in ( rng ( C153 | ( the_subsets_of_card (2 , D122) ) ) ) iff B222 = 1))
proof
let C161 being set;
L836: ( C153 | ( the_subsets_of_card (2 , D120) ) ) c= ( C153 | ( the_subsets_of_card (2 , D122) ) ) by L833 , RELAT_1:75;
L837: ( rng ( C153 | ( the_subsets_of_card (2 , D120) ) ) ) c= ( rng ( C153 | ( the_subsets_of_card (2 , D122) ) ) ) by L836 , RELAT_1:11;
thus L838:now
assume L839: C161 in ( rng ( C153 | ( the_subsets_of_card (2 , D122) ) ) );
consider C162 being set such that L840: C162 in ( dom ( C153 | ( the_subsets_of_card (2 , D122) ) ) ) and L841: C161 = ( ( C153 | ( the_subsets_of_card (2 , D122) ) ) . C162 ) by L839 , FUNCT_1:def 3;
L842: C162 in ( the_subsets_of_card (2 , D122) ) by L840 , RELAT_1:57;
L843: C162 in ( dom C153 ) by L840 , RELAT_1:57;
L844: C162 in { B223 where B223 is (Subset of D122) : ( card B223 ) = 2 } by L840 , RELAT_1:57;
consider C163 being (Subset of D122) such that L845: C162 = C163 and L846: ( card C163 ) = 2 by L844;
consider C164 , C165 being set such that L847: C164 <> C165 and L848: C163 = { C164 , C165 } by L846 , CARD_2:60;
L849: C164 in C163 by L848 , TARSKI:def 2;
L850: C165 in C163 by L848 , TARSKI:def 2;
per cases  by L849 , XBOOLE_0:def 3;
suppose L851: C164 in D120;

per cases  by L850 , XBOOLE_0:def 3;
suppose L852: C165 in D120;

reconsider D123 = C162 as (Subset of D120) by L852 , L845 , L848 , L851 , ZFMISC_1:32;
L853: D123 in ( the_subsets_of_card (2 , D120) ) by L845 , L846;
L854: D123 in ( dom ( C153 | ( the_subsets_of_card (2 , D120) ) ) ) by L853 , L843 , RELAT_1:57;
L855: D123 in ( dom ( ( C153 | ( the_subsets_of_card (2 , D122) ) ) | ( the_subsets_of_card (2 , D120) ) ) ) by L854 , L833 , RELAT_1:74;
L856: ( ( C153 | ( the_subsets_of_card (2 , D120) ) ) . D123 ) = ( ( ( C153 | ( the_subsets_of_card (2 , D122) ) ) | ( the_subsets_of_card (2 , D120) ) ) . D123 ) by L833 , RELAT_1:74
.= ( ( C153 | ( the_subsets_of_card (2 , D122) ) ) . D123 ) by L855 , FUNCT_1:47;
L857: C161 in ( rng ( C153 | ( the_subsets_of_card (2 , D120) ) ) ) by L856 , L841 , L854 , FUNCT_1:3;
thus L858: C161 = 1 by L857 , L827 , L831 , TARSKI:def 1;
end;
suppose L859: C165 in { C155 };

L860: C164 in D117 by L851;
L861: (ex B224 being (Element of C154) st (C164 = B224 & ( C153 . { C155 , B224 } ) = 1 & { C155 , B224 } in ( dom C153 ))) by L860;
L862: C162 = { C164 , C155 } by L845 , L848 , L859 , TARSKI:def 1;
thus L863: C161 = 1 by L862 , L841 , L842 , L861 , FUNCT_1:49;
end;
end;
suppose L865: C164 in { C155 };

L866: C155 <> C165 by L865 , L847 , TARSKI:def 1;
per cases  by L850 , XBOOLE_0:def 3;
suppose L867: C165 in D120;

L868: C165 in D117 by L867;
L869: (ex B225 being (Element of C154) st (C165 = B225 & ( C153 . { C155 , B225 } ) = 1 & { C155 , B225 } in ( dom C153 ))) by L868;
L870: ( C153 . C162 ) = 1 by L869 , L845 , L848 , L865 , TARSKI:def 1;
thus L871: C161 = 1 by L870 , L841 , L842 , FUNCT_1:49;
end;
suppose L872: C165 in { C155 };

thus L873: C161 = 1 by L872 , L866 , TARSKI:def 1;
end;
end;
end;
assume L876: C161 = 1;
L877: C161 in ( rng ( C153 | ( the_subsets_of_card (2 , D120) ) ) ) by L876 , L834 , TARSKI:def 1;
thus L878: thesis by L877 , L837;
end;
take D122;
L879: (not C155 in D120)
proof
assume L880: C155 in D120;
L881: C155 in D117 by L880;
L882: (ex B226 being (Element of C154) st (C155 = B226 & ( C153 . { C155 , B226 } ) = 1 & { C155 , B226 } in ( dom C153 ))) by L881;
L883: { C155 , C155 } = ( { C155 } \/ { C155 } ) by ENUMSET1:1
.= { C155 };
L884: { C155 } in ( the_subsets_of_card (2 , C152) ) by L883 , L882;
L885: (ex B227 being (Subset of C152) st (B227 = { C155 } & ( card B227 ) = 2)) by L884;
thus L886: contradiction by L885 , CARD_1:30;
end;
L887: ( ( card D120 ) + 1 ) >= ( C138 + 1 ) by L831 , XREAL_1:6;
thus L888: thesis by L887 , L835 , L879 , CARD_2:41 , TARSKI:def 1;
end;
end;
suppose L890: ( card D116 ) >= C151;

set D124 = ( C153 | ( the_subsets_of_card (2 , D116) ) );
L891: D116 c= C152 by XBOOLE_1:1;
L892: ( ( the_subsets_of_card (2 , C152) ) /\ ( the_subsets_of_card (2 , D116) ) ) = ( the_subsets_of_card (2 , D116) ) by L891 , L32 , XBOOLE_1:28;
L893: ( dom ( C153 | ( the_subsets_of_card (2 , D116) ) ) ) = ( the_subsets_of_card (2 , D116) ) by L892 , L757 , RELAT_1:61;
L894: ( rng ( C153 | ( the_subsets_of_card (2 , D116) ) ) ) c= ( rng C153 ) by RELAT_1:70;
reconsider D125 = D124 as (Function of ( the_subsets_of_card (2 , D116) ) , ( Seg 2 )) by L894 , L757 , L893 , FUNCT_2:2 , XBOOLE_1:1;
consider C166 being (Subset of D116) such that L895: ((( card C166 ) >= ( C138 + 1 ) & ( rng ( D125 | ( the_subsets_of_card (2 , C166) ) ) ) = { 1 }) or (( card C166 ) >= C139 & ( rng ( D125 | ( the_subsets_of_card (2 , C166) ) ) ) = { 2 })) by L748 , L890;
L896: ( D125 | ( the_subsets_of_card (2 , C166) ) ) = ( C153 | ( the_subsets_of_card (2 , C166) ) ) by L32 , RELAT_1:74;
L897: D116 c= C152 by XBOOLE_1:1;
reconsider D126 = C166 as (Subset of C152) by L897 , XBOOLE_1:1;
per cases  by L895;
suppose L898: (( card D126 ) >= ( C138 + 1 ) & ( rng ( D125 | ( the_subsets_of_card (2 , D126) ) ) ) = { 1 });

take D126;
thus L899: thesis by L898 , L32 , RELAT_1:74;
end;
suppose L900: (( card D126 ) >= C139 & ( rng ( D125 | ( the_subsets_of_card (2 , D126) ) ) ) = { 2 });

set D127 = ( D126 \/ { C155 } );
L901: { C155 } c= C152 by L755 , ZFMISC_1:31;
reconsider D128 = D127 as (Subset of C152) by L901 , XBOOLE_1:8;
L902: ( the_subsets_of_card (2 , D126) ) c= ( the_subsets_of_card (2 , D128) ) by L32 , XBOOLE_1:7;
L903: ( rng ( C153 | ( the_subsets_of_card (2 , D126) ) ) ) = { 2 } by L900 , L32 , RELAT_1:74;
L904: (for B228 being set holds (B228 in ( rng ( C153 | ( the_subsets_of_card (2 , D128) ) ) ) iff B228 = 2))
proof
let C167 being set;
L905: ( C153 | ( the_subsets_of_card (2 , D126) ) ) c= ( C153 | ( the_subsets_of_card (2 , D128) ) ) by L902 , RELAT_1:75;
L906: ( rng ( C153 | ( the_subsets_of_card (2 , D126) ) ) ) c= ( rng ( C153 | ( the_subsets_of_card (2 , D128) ) ) ) by L905 , RELAT_1:11;
thus L907:now
assume L908: C167 in ( rng ( C153 | ( the_subsets_of_card (2 , D128) ) ) );
consider C168 being set such that L909: C168 in ( dom ( C153 | ( the_subsets_of_card (2 , D128) ) ) ) and L910: C167 = ( ( C153 | ( the_subsets_of_card (2 , D128) ) ) . C168 ) by L908 , FUNCT_1:def 3;
L911: C168 in ( the_subsets_of_card (2 , D128) ) by L909 , RELAT_1:57;
L912: C168 in ( dom C153 ) by L909 , RELAT_1:57;
L913: C168 in { B229 where B229 is (Subset of D128) : ( card B229 ) = 2 } by L909 , RELAT_1:57;
consider C169 being (Subset of D128) such that L914: C168 = C169 and L915: ( card C169 ) = 2 by L913;
consider C170 , C171 being set such that L916: C170 <> C171 and L917: C169 = { C170 , C171 } by L915 , CARD_2:60;
L918: C170 in C169 by L917 , TARSKI:def 2;
L919: C171 in C169 by L917 , TARSKI:def 2;
per cases  by L918 , XBOOLE_0:def 3;
suppose L920: C170 in D126;

per cases  by L919 , XBOOLE_0:def 3;
suppose L921: C171 in D126;

reconsider D129 = C168 as (Subset of D126) by L921 , L914 , L917 , L920 , ZFMISC_1:32;
L922: D129 in ( the_subsets_of_card (2 , D126) ) by L914 , L915;
L923: D129 in ( dom ( C153 | ( the_subsets_of_card (2 , D126) ) ) ) by L922 , L912 , RELAT_1:57;
L924: D129 in ( dom ( ( C153 | ( the_subsets_of_card (2 , D128) ) ) | ( the_subsets_of_card (2 , D126) ) ) ) by L923 , L902 , RELAT_1:74;
L925: ( ( C153 | ( the_subsets_of_card (2 , D126) ) ) . D129 ) = ( ( ( C153 | ( the_subsets_of_card (2 , D128) ) ) | ( the_subsets_of_card (2 , D126) ) ) . D129 ) by L902 , RELAT_1:74
.= ( ( C153 | ( the_subsets_of_card (2 , D128) ) ) . D129 ) by L924 , FUNCT_1:47;
L926: C167 in ( rng ( C153 | ( the_subsets_of_card (2 , D126) ) ) ) by L925 , L910 , L923 , FUNCT_1:3;
thus L927: C167 = 2 by L926 , L896 , L900 , TARSKI:def 1;
end;
suppose L928: C171 in { C155 };

L929: C170 in D116 by L920;
L930: (ex B230 being (Element of C154) st (C170 = B230 & ( C153 . { C155 , B230 } ) = 2 & { C155 , B230 } in ( dom C153 ))) by L929;
L931: C168 = { C170 , C155 } by L914 , L917 , L928 , TARSKI:def 1;
thus L932: C167 = 2 by L931 , L910 , L911 , L930 , FUNCT_1:49;
end;
end;
suppose L934: C170 in { C155 };

L935: C155 <> C171 by L934 , L916 , TARSKI:def 1;
per cases  by L919 , XBOOLE_0:def 3;
suppose L936: C171 in D126;

L937: C171 in D116 by L936;
L938: (ex B231 being (Element of C154) st (C171 = B231 & ( C153 . { C155 , B231 } ) = 2 & { C155 , B231 } in ( dom C153 ))) by L937;
L939: ( C153 . C168 ) = 2 by L938 , L914 , L917 , L934 , TARSKI:def 1;
thus L940: C167 = 2 by L939 , L910 , L911 , FUNCT_1:49;
end;
suppose L941: C171 in { C155 };

thus L942: C167 = 2 by L941 , L935 , TARSKI:def 1;
end;
end;
end;
assume L945: C167 = 2;
L946: C167 in ( rng ( C153 | ( the_subsets_of_card (2 , D126) ) ) ) by L945 , L903 , TARSKI:def 1;
thus L947: thesis by L946 , L906;
end;
take D128;
L948: (not C155 in D126)
proof
assume L949: C155 in D126;
L950: C155 in D116 by L949;
L951: (ex B232 being (Element of C154) st (C155 = B232 & ( C153 . { C155 , B232 } ) = 2 & { C155 , B232 } in ( dom C153 ))) by L950;
L952: { C155 , C155 } = ( { C155 } \/ { C155 } ) by ENUMSET1:1
.= { C155 };
L953: { C155 } in ( the_subsets_of_card (2 , C152) ) by L952 , L951;
L954: (ex B233 being (Subset of C152) st (B233 = { C155 } & ( card B233 ) = 2)) by L953;
thus L955: contradiction by L954 , CARD_1:30;
end;
L956: ( ( card D126 ) + 1 ) >= ( C139 + 1 ) by L900 , XREAL_1:6;
thus L957: thesis by L956 , L904 , L948 , CARD_2:41 , TARSKI:def 1;
end;
end;
end;
end;
L961: (for B234 being Nat holds (S9[ ( 0 ) , B234 ] & S9[ B234 , ( 0 ) ]));
L962: (for B235 , B236 being Nat holds S9[ B235 , B236 ]) from BinInd2(L961 , L639);
thus L963: thesis by L962;
end;
::$N Ramsey's Theorem (finite case)
theorem
L964: (for B237 being Nat holds (ex B238 being Nat st (for B239 being  finite set holds (for B240 being (a_partition of ( the_subsets_of_card (2 , B239) )) holds ((( card B239 ) >= B238 & ( card B240 ) = 2) implies (ex B241 being (Subset of B239) st (( card B241 ) >= B237 & B241 is_homogeneous_for B240)))))))
proof
let C172 being Nat;
per cases ;
suppose L965: C172 < 2;

set D130 = 1;
take D130;
let C173 being  finite set;
let C174 being (a_partition of ( the_subsets_of_card (2 , C173) ));
assume L966: ( card C173 ) >= D130;
consider C175 being set such that L967: C175 in C173 by L966 , CARD_1:27 , XBOOLE_0:def 1;
reconsider D131 = { C175 } as (Subset of C173) by L967 , ZFMISC_1:31;
assume L968: ( card C174 ) = 2;
take D131;
L969: C172 < ( 1 + 1 ) by L965;
L970: C172 <= 1 by L969 , NAT_1:13;
thus L971: ( card D131 ) >= C172 by L970 , CARD_1:30;
L972: ( card D131 ) = 1 by CARD_1:30;
L973: (ex B242 being (Element of C174) st ( the_subsets_of_card (2 , D131) ) c= B242)
proof
set D132 = the (Element of C174);
take D132;
L974: ( the_subsets_of_card (2 , D131) ) = ( {} ) by L972 , L476;
thus L975: thesis by L974 , XBOOLE_1:2;
end;
thus L976: thesis by L973 , L1;
end;
suppose L977: C172 >= 2;

consider C176 being Nat such that L978: C176 <= ( ( ( C172 + C172 ) -' 2 ) choose ( C172 -' 1 ) ) and L979: C176 >= 2 and L980: (for B243 being  finite set holds (for B244 being (Function of ( the_subsets_of_card (2 , B243) ) , ( Seg 2 )) holds (( card B243 ) >= C176 implies (ex B245 being (Subset of B243) st ((( card B245 ) >= C172 & ( rng ( B244 | ( the_subsets_of_card (2 , B245) ) ) ) = { 1 }) or (( card B245 ) >= C172 & ( rng ( B244 | ( the_subsets_of_card (2 , B245) ) ) ) = { 2 })))))) by L977 , L638;
take C176;
let C177 being  finite set;
let C178 being (a_partition of ( the_subsets_of_card (2 , C177) ));
assume that
L981: ( card C177 ) >= C176
and
L982: ( card C178 ) = 2;
L983: 2 <= ( card C177 ) by L979 , L981 , XXREAL_0:2;
L984: ( card ( Seg 2 ) ) <= ( card C177 ) by L983 , FINSEQ_1:57;
L985: ( card ( Seg 2 ) ) c= ( card C177 ) by L984 , NAT_1:39;
L986: ( card 2 ) c= ( card C177 ) by L985 , FINSEQ_1:55;
reconsider D133 = ( the_subsets_of_card (2 , C177) ) as non  empty set by L986 , L979 , L981 , CARD_1:27 , GROUP_10:1;
reconsider D134 = C178 as (a_partition of D133);
L987: ( card D134 ) = ( card ( Seg 2 ) ) by L982 , FINSEQ_1:57;
L988: D134 , ( Seg 2 ) are_equipotent  by L987 , CARD_1:5;
consider C179 being Function such that L989: C179 is  one-to-one and L990: ( dom C179 ) = D134 and L991: ( rng C179 ) = ( Seg 2 ) by L988 , WELLORD2:def 4;
reconsider D135 = C179 as (Function of D134 , ( Seg 2 )) by L990 , L991 , FUNCT_2:1;
set D136 = ( D135 * ( proj D134 ) );
reconsider D137 = D136 as (Function of ( the_subsets_of_card (2 , C177) ) , ( Seg 2 ));
consider C180 being (Subset of C177) such that L992: ((( card C180 ) >= C172 & ( rng ( D137 | ( the_subsets_of_card (2 , C180) ) ) ) = { 1 }) or (( card C180 ) >= C172 & ( rng ( D137 | ( the_subsets_of_card (2 , C180) ) ) ) = { 2 })) by L980 , L981;
take C180;
thus L993: ( card C180 ) >= C172 by L992;
set D138 = the (Element of ( the_subsets_of_card (2 , C180) ));
L994: ( the_subsets_of_card (2 , C180) ) is non  empty by L992;
L995: D138 in ( the_subsets_of_card (2 , C180) ) by L994;
L996: ( the_subsets_of_card (2 , C180) ) c= ( the_subsets_of_card (2 , C177) ) by L32;
reconsider D139 = D138 as (Element of D133) by L996 , L995;
set D140 = ( EqClass (D139 , D134) );
reconsider D141 = D140 as (Element of C178) by EQREL_1:def 6;
L997: ( D137 | ( the_subsets_of_card (2 , C180) ) ) is  constant by L992;
L998: (for B246 being set holds (B246 in ( the_subsets_of_card (2 , C180) ) implies B246 in D141))
proof
let C181 being set;
assume L999: C181 in ( the_subsets_of_card (2 , C180) );
reconsider D142 = C181 as (Element of ( the_subsets_of_card (2 , C177) )) by L999 , L996;
reconsider D143 = C181 as (Element of D133) by L996 , L999;
L1000: ( dom D137 ) = ( the_subsets_of_card (2 , C177) ) by FUNCT_2:def 1;
L1001: D139 in ( ( dom D137 ) /\ ( the_subsets_of_card (2 , C180) ) ) by L1000 , L994 , XBOOLE_0:def 4;
L1002: D139 in ( dom ( D137 | ( the_subsets_of_card (2 , C180) ) ) ) by L1001 , RELAT_1:61;
L1003: D142 in ( ( dom D137 ) /\ ( the_subsets_of_card (2 , C180) ) ) by L999 , L1000 , XBOOLE_0:def 4;
L1004: D142 in ( dom ( D137 | ( the_subsets_of_card (2 , C180) ) ) ) by L1003 , RELAT_1:61;
L1005: ( D137 . D142 ) = ( ( D137 | ( the_subsets_of_card (2 , C180) ) ) . D142 ) by L999 , FUNCT_1:49
.= ( ( D137 | ( the_subsets_of_card (2 , C180) ) ) . D139 ) by L997 , L1004 , L1002 , FUNCT_1:def 10
.= ( D137 . D139 ) by L994 , FUNCT_1:49;
L1006: ( D135 . ( ( proj D134 ) . D142 ) ) = ( ( D135 * ( proj D134 ) ) . D139 ) by L1005 , L1000 , FUNCT_1:12
.= ( D135 . ( ( proj D134 ) . D139 ) ) by L1000 , FUNCT_1:12;
L1007: ( ( proj D134 ) . D143 ) in D134;
L1008: (D139 in D141 & ( ( proj D134 ) . D139 ) = ( ( proj D134 ) . D142 )) by L1007 , L989 , L990 , L1006 , EQREL_1:def 6 , FUNCT_1:def 4;
thus L1009: thesis by L1008 , L543;
end;
L1010: ( the_subsets_of_card (2 , C180) ) c= D141 by L998 , TARSKI:def 3;
thus L1011: thesis by L1010 , L1;
end;
end;
