:: Schemes of Existence of some Types of Functions
::  by Jaros{\l}aw Kotowicz
::
:: Received September 21, 1990
:: Copyright (c) 1990-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, SUBSET_1, REAL_1, RELAT_1, ARYTM_3, INT_1, CARD_1,
      XXREAL_0, SEQ_1, VALUED_0, FUNCT_1, NAT_1, TARSKI, ORDINAL2, ARYTM_1,
      XBOOLE_0, PARTFUN1, ZFMISC_1;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, NUMBERS, XCMPLX_0, REAL_1,
      ORDINAL1, NAT_1, NAT_D, RELAT_1, FUNCT_1, RELSET_1, PARTFUN1, FUNCT_2,
      VALUED_0, SEQ_1, XXREAL_0, RECDEF_1;
 constructors PARTFUN1, XXREAL_0, NAT_1, NAT_D, SEQ_1, SEQM_3, RECDEF_1,
      MEMBERED, RELSET_1;
 registrations ORDINAL1, RELSET_1, NUMBERS, XXREAL_0, XREAL_0, SEQM_3,
      VALUED_0;
 requirements NUMERALS, REAL, SUBSET, BOOLE, ARITHM;
 definitions TARSKI, XBOOLE_0;
 theorems ZFMISC_1, NAT_1, FUNCT_1, FUNCT_2, SEQM_3, PARTFUN1, RELSET_1,
      XBOOLE_1, NAT_D, ORDINAL1, XXREAL_0, XTUPLE_0;
 schemes NAT_1, FUNCT_2, RECDEF_1, SUBSET_1, CLASSES1, XBOOLE_0;

begin
theorem
L1: (for R4 being (Element of ( NAT )) holds (ex R5 being (Element of ( NAT )) st (R4 = ( 2 * R5 ) or R4 = ( ( 2 * R5 ) + 1 ))))
proof
let R4 being (Element of ( NAT ));
take ( R4 div 2 );
set D1 = ( R4 mod 2 );
L2: (D1 = ( 0 ) or D1 = 1)
proof
L3: D1 < ( 1 + 1 ) by NAT_D:1;
L4: D1 <= ( ( 0 ) + 1 ) by L3 , NAT_1:13;
L5:
now
per cases  by L4 , NAT_1:8;
suppose L6: D1 <= ( 0 );

thus L7: thesis by L6 , NAT_1:2;
end;
suppose L8: D1 = ( ( 0 ) + 1 );

thus L9: thesis by L8;
end;
end;
thus L11: thesis by L5;
end;
L12: R4 = ( ( 2 * ( R4 div 2 ) ) + ( R4 mod 2 ) ) by NAT_D:2;
thus L13: thesis by L12 , L2;
end;
theorem
L14: (for R4 being (Element of ( NAT )) holds (ex R5 being (Element of ( NAT )) st (R4 = ( 3 * R5 ) or R4 = ( ( 3 * R5 ) + 1 ) or R4 = ( ( 3 * R5 ) + 2 ))))
proof
let R4 being (Element of ( NAT ));
take ( R4 div 3 );
set D2 = ( R4 mod 3 );
L15: (D2 = ( 0 ) or D2 = 1 or D2 = 2)
proof
L16: D2 < ( 2 + 1 ) by NAT_D:1;
L17: D2 <= ( 1 + 1 ) by L16 , NAT_1:13;
L18:
now
per cases  by L17 , NAT_1:8;
suppose L19: D2 <= 1;

L20:
now
per cases  by L19 , NAT_1:8;
suppose L21: D2 <= ( 0 );

thus L22: thesis by L21 , NAT_1:2;
end;
suppose L23: D2 = ( ( 0 ) + 1 );

thus L24: thesis by L23;
end;
end;
thus L26: thesis by L20;
end;
suppose L27: D2 = ( 1 + 1 );

thus L28: thesis by L27;
end;
end;
thus L30: thesis by L18;
end;
L31: R4 = ( ( 3 * ( R4 div 3 ) ) + ( R4 mod 3 ) ) by NAT_D:2;
L32:
now
per cases  by L15;
suppose L33: D2 = ( 0 );

thus L34: thesis by L33 , L31;
end;
suppose L35: D2 = 1;

thus L36: thesis by L35 , NAT_D:2;
end;
suppose L37: D2 = 2;

thus L38: thesis by L37 , NAT_D:2;
end;
end;
thus L40: thesis by L32;
end;
theorem
L41: (for R4 being (Element of ( NAT )) holds (ex R5 being (Element of ( NAT )) st (R4 = ( 4 * R5 ) or R4 = ( ( 4 * R5 ) + 1 ) or R4 = ( ( 4 * R5 ) + 2 ) or R4 = ( ( 4 * R5 ) + 3 ))))
proof
let R4 being (Element of ( NAT ));
take ( R4 div 4 );
set D3 = ( R4 mod 4 );
L42: (D3 = ( 0 ) or D3 = 1 or D3 = 2 or D3 = 3)
proof
L43: D3 < ( 3 + 1 ) by NAT_D:1;
L44: D3 <= ( 2 + 1 ) by L43 , NAT_1:13;
L45:
now
per cases  by L44 , NAT_1:8;
suppose L46: D3 <= 2;

L47:
now
per cases  by L46 , NAT_1:8;
suppose L48: D3 <= 1;

L49:
now
per cases  by L48 , NAT_1:8;
suppose L50: D3 <= ( 0 );

thus L51: thesis by L50 , NAT_1:2;
end;
suppose L52: D3 = ( ( 0 ) + 1 );

thus L53: thesis by L52;
end;
end;
thus L55: thesis by L49;
end;
suppose L56: D3 = ( 1 + 1 );

thus L57: thesis by L56;
end;
end;
thus L59: thesis by L47;
end;
suppose L60: D3 = ( 2 + 1 );

thus L61: thesis by L60;
end;
end;
thus L63: thesis by L45;
end;
L64: R4 = ( ( 4 * ( R4 div 4 ) ) + ( R4 mod 4 ) ) by NAT_D:2;
thus L65: thesis by L64 , L42;
end;
theorem
L66: (for R4 being (Element of ( NAT )) holds (ex R5 being (Element of ( NAT )) st (R4 = ( 5 * R5 ) or R4 = ( ( 5 * R5 ) + 1 ) or R4 = ( ( 5 * R5 ) + 2 ) or R4 = ( ( 5 * R5 ) + 3 ) or R4 = ( ( 5 * R5 ) + 4 ))))
proof
let R4 being (Element of ( NAT ));
take ( R4 div 5 );
set D4 = ( R4 mod 5 );
L67: (D4 = ( 0 ) or D4 = 1 or D4 = 2 or D4 = 3 or D4 = 4)
proof
L68: D4 < ( 4 + 1 ) by NAT_D:1;
L69: D4 <= ( 3 + 1 ) by L68 , NAT_1:13;
L70:
now
per cases  by L69 , NAT_1:8;
suppose L71: D4 <= 3;

L72:
now
per cases  by L71 , NAT_1:8;
suppose L73: D4 <= 2;

L74:
now
per cases  by L73 , NAT_1:8;
suppose L75: D4 <= 1;

L76:
now
per cases  by L75 , NAT_1:8;
suppose L77: D4 <= ( 0 );

thus L78: thesis by L77 , NAT_1:2;
end;
suppose L79: D4 = ( ( 0 ) + 1 );

thus L80: thesis by L79;
end;
end;
thus L82: thesis by L76;
end;
suppose L83: D4 = ( 1 + 1 );

thus L84: thesis by L83;
end;
end;
thus L86: thesis by L74;
end;
suppose L87: D4 = ( 2 + 1 );

thus L88: thesis by L87;
end;
end;
thus L90: thesis by L72;
end;
suppose L91: D4 = ( 3 + 1 );

thus L92: thesis by L91;
end;
end;
thus L94: thesis by L70;
end;
L95: R4 = ( ( 5 * ( R4 div 5 ) ) + ( R4 mod 5 ) ) by NAT_D:2;
thus L96: thesis by L95 , L67;
end;
scheme ExRealSubseq { F1() -> Real_Sequence , P1[set] } : (ex B1 being Real_Sequence st (B1 is (subsequence of F1()) & (for R4 being (Element of ( NAT )) holds P1[ ( B1 . R4 ) ]) & (for R4 being (Element of ( NAT )) holds ((for R7 being Real holds (R7 = ( F1() . R4 ) implies P1[ R7 ])) implies (ex R5 being (Element of ( NAT )) st ( F1() . R4 ) = ( B1 . R5 ))))))
provided
L97: (for R4 being (Element of ( NAT )) holds (ex R5 being (Element of ( NAT )) st (R4 <= R5 & P1[ ( F1() . R5 ) ])))
proof
defpred S1[ set , set ] means (for R4 being (Element of ( NAT )) holds (for R5 being (Element of ( NAT )) holds (($1 = R4 & $2 = R5) implies (R4 < R5 & P1[ ( F1() . R5 ) ] & (for R6 being (Element of ( NAT )) holds ((R4 < R6 & P1[ ( F1() . R6 ) ]) implies R5 <= R6))))));
defpred S2[ set , set , set ] means S1[ $2 , $3 ];
defpred S3[ set ] means P1[ ( F1() . $1 ) ];
L98: (ex B2 being (Element of ( NAT )) st (( 0 ) <= B2 & P1[ ( F1() . B2 ) ])) by L97;
L99: (ex B3 being Nat st S3[ B3 ]) by L98;
consider C1 being Nat such that L100: (S3[ C1 ] & (for B4 being Nat holds (S3[ B4 ] implies C1 <= B4))) from NAT_1:sch 5(L99);
reconsider D5 = C1 as (Element of ( NAT )) by ORDINAL1:def 12;
L101:
now
let R4 being (Element of ( NAT ));
consider R5 being (Element of ( NAT )) such that L102: (( R4 + 1 ) <= R5 & P1[ ( F1() . R5 ) ]) by L97;
take D6 = R5;
thus L103: (R4 < D6 & P1[ ( F1() . D6 ) ]) by L102 , NAT_1:13;
end;
L104: (for R4 being (Element of ( NAT )) holds (for B5 being (Element of ( NAT )) holds (ex B6 being (Element of ( NAT )) st S2[ R4 , B5 , B6 ])))
proof
let R4 being (Element of ( NAT ));
let C2 being (Element of ( NAT ));
defpred S4[ Nat ] means (C2 < $1 & P1[ ( F1() . $1 ) ]);
L105: (ex B7 being (Element of ( NAT )) st S4[ B7 ]) by L101;
L106: (ex B8 being Nat st S4[ B8 ]) by L105;
consider C3 being Nat such that L107: (S4[ C3 ] & (for B9 being Nat holds (S4[ B9 ] implies C3 <= B9))) from NAT_1:sch 5(L106);
reconsider D7 = C3 as (Element of ( NAT )) by ORDINAL1:def 12;
take D7;
thus L108: thesis by L107;
end;
consider C4 being (Function of ( NAT ) , ( NAT )) such that L109: (( C4 . ( 0 ) ) = D5 & (for B10 being (Element of ( NAT )) holds S2[ B10 , ( C4 . B10 ) , ( C4 . ( B10 + 1 ) ) ])) from RECDEF_1:sch 2(L104);
L110: (( dom C4 ) = ( NAT ) & ( rng C4 ) c= ( REAL )) by FUNCT_2:def 1 , XBOOLE_1:1;
reconsider D8 = C4 as  natural-valued Real_Sequence by L110 , FUNCT_2:def 1 , RELSET_1:4;
L111: (for R4 being (Element of ( NAT )) holds ( D8 . R4 ) < ( D8 . ( R4 + 1 ) )) by L109;
reconsider D9 = D8 as  increasing (sequence of ( NAT )) by L111 , SEQM_3:def 6;
L112: (for R4 being (Element of ( NAT )) holds (P1[ ( F1() . R4 ) ] implies (ex R5 being (Element of ( NAT )) st ( D9 . R5 ) = R4)))
proof
defpred S5[ set ] means (P1[ ( F1() . $1 ) ] & (for R5 being (Element of ( NAT )) holds ( D9 . R5 ) <> $1));
assume L113: (ex R4 being (Element of ( NAT )) st S5[ R4 ]);
L114: (ex B11 being Nat st S5[ B11 ]) by L113;
consider C5 being Nat such that L115: (S5[ C5 ] & (for B12 being Nat holds (S5[ B12 ] implies C5 <= B12))) from NAT_1:sch 5(L114);
defpred S6[ Nat ] means ($1 < C5 & P1[ ( F1() . $1 ) ] & (ex R5 being (Element of ( NAT )) st ( D9 . R5 ) = $1));
L116: (ex B13 being Nat st S6[ B13 ])
proof
take C1;
L117: (C1 <= C5 & C1 <> C5) by L100 , L109 , L115;
thus L118: C1 < C5 by L117 , XXREAL_0:1;
thus L119: P1[ ( F1() . C1 ) ] by L100;
take ( 0 );
thus L120: thesis by L109;
end;
L121: (for B14 being Nat holds (S6[ B14 ] implies B14 <= C5));
consider C6 being Nat such that L122: (S6[ C6 ] & (for B15 being Nat holds (S6[ B15 ] implies B15 <= C6))) from NAT_1:sch 6(L121 , L116);
L123: (for R6 being (Element of ( NAT )) holds ((C6 < R6 & R6 < C5) implies (not P1[ ( F1() . R6 ) ])))
proof
given R6 being (Element of ( NAT )) such that
L124: C6 < R6
and
L125: (R6 < C5 & P1[ ( F1() . R6 ) ]);

L126:
now
per cases ;
suppose L127: (ex R5 being (Element of ( NAT )) st ( D9 . R5 ) = R6);

thus L128: contradiction by L127 , L122 , L124 , L125;
end;
suppose L129: (for R5 being (Element of ( NAT )) holds ( D9 . R5 ) <> R6);

thus L130: contradiction by L129 , L115 , L125;
end;
end;
thus L132: contradiction by L126;
end;
consider R5 being (Element of ( NAT )) such that L133: ( D9 . R5 ) = C6 by L122;
L134: (C6 < ( D9 . ( R5 + 1 ) ) & P1[ ( F1() . ( D9 . ( R5 + 1 ) ) ) ]) by L109 , L133;
L135: C5 in ( NAT ) by ORDINAL1:def 12;
L136: ( D9 . ( R5 + 1 ) ) <= C5 by L135 , L109 , L115 , L122 , L133;
L137:
now
assume L138: ( D9 . ( R5 + 1 ) ) <> C5;
L139: ( D9 . ( R5 + 1 ) ) < C5 by L138 , L136 , XXREAL_0:1;
thus L140: contradiction by L139 , L123 , L134;
end;
thus L141: contradiction by L137 , L115;
end;
take D10 = ( F1() * D9 );
defpred S7[ set ] means P1[ ( D10 . $1 ) ];
L142: (for R6 being (Element of ( NAT )) holds (S7[ R6 ] implies S7[ ( R6 + 1 ) ]))
proof
let R6 being (Element of ( NAT ));
assume that
L143: P1[ ( D10 . R6 ) ];
L144: S1[ ( D9 . R6 ) , ( D9 . ( R6 + 1 ) ) ] by L109;
L145: P1[ ( F1() . ( D9 . ( R6 + 1 ) ) ) ] by L144;
thus L146: thesis by L145 , FUNCT_2:15;
end;
thus L147: D10 is (subsequence of F1());
L148: S7[ ( 0 ) ] by L100 , L109 , FUNCT_2:15;
thus L149: (for R4 being (Element of ( NAT )) holds S7[ R4 ]) from NAT_1:sch 1(L148 , L142);
let R4 being (Element of ( NAT ));
assume L150: (for R7 being Real holds (R7 = ( F1() . R4 ) implies P1[ R7 ]));
consider R5 being (Element of ( NAT )) such that L151: ( D9 . R5 ) = R4 by L150 , L112;
take R5;
thus L152: thesis by L151 , FUNCT_2:15;
end;
scheme ExRealSeq2 { F2 , F3(set) -> Real } : (ex B16 being Real_Sequence st (for R4 being (Element of ( NAT )) holds (( B16 . ( 2 * R4 ) ) = F2(R4) & ( B16 . ( ( 2 * R4 ) + 1 ) ) = F3(R4))))
proof
defpred S8[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( 2 * R5 ));
consider C7 being (Subset of ( NAT )) such that L153: (for R4 being (Element of ( NAT )) holds (R4 in C7 iff S8[ R4 ])) from SUBSET_1:sch 3;
defpred S9[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 2 * R5 ) + 1 ));
consider C8 being (Subset of ( NAT )) such that L154: (for R4 being (Element of ( NAT )) holds (R4 in C8 iff S9[ R4 ])) from SUBSET_1:sch 3;
defpred S10[ (Element of ( NAT )) , set ] means (($1 in C7 implies $2 = F2(( $1 / 2 ))) & ($1 in C8 implies $2 = F3(( ( $1 - 1 ) / 2 ))));
L155: (for R4 being (Element of ( NAT )) holds (ex R7 being Real st S10[ R4 , R7 ]))
proof
let R4 being (Element of ( NAT ));
L156:
now
assume L157: R4 in C7;
take D11 = F2(( R4 / 2 ));
L158:
now
assume L159: R4 in C8;
L160: (ex R6 being (Element of ( NAT )) st R4 = ( ( 2 * R6 ) + 1 )) by L159 , L154;
consider R5 being (Element of ( NAT )) such that L161: R4 = ( 2 * R5 ) by L153 , L157;
L162: R4 = ( ( 2 * R5 ) + ( 0 ) ) by L161;
thus L163: contradiction by L162 , L160 , NAT_1:18;
end;
thus L164: thesis by L158;
end;
thus L165: thesis by L156;
end;
consider C9 being (Function of ( NAT ) , ( REAL )) such that L166: (for R4 being (Element of ( NAT )) holds S10[ R4 , ( C9 . R4 ) ]) from FUNCT_2:sch 3(L155);
reconsider D12 = C9 as Real_Sequence;
take D12;
let R4 being (Element of ( NAT ));
L167: ( 2 * R4 ) in C7 by L153;
thus L168: ( D12 . ( 2 * R4 ) ) = F2(( ( 2 * R4 ) / 2 )) by L167 , L166
.= F2(R4);
L169: ( ( 2 * R4 ) + 1 ) in C8 by L154;
thus L170: ( D12 . ( ( 2 * R4 ) + 1 ) ) = F3(( ( ( ( 2 * R4 ) + 1 ) - 1 ) / 2 )) by L169 , L166
.= F3(R4);
end;
scheme ExRealSeq3 { F4 , F5 , F6(set) -> Real } : (ex B17 being Real_Sequence st (for R4 being (Element of ( NAT )) holds (( B17 . ( 3 * R4 ) ) = F4(R4) & ( B17 . ( ( 3 * R4 ) + 1 ) ) = F5(R4) & ( B17 . ( ( 3 * R4 ) + 2 ) ) = F6(R4))))
proof
defpred S11[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( 3 * R5 ));
consider C10 being (Subset of ( NAT )) such that L171: (for R4 being (Element of ( NAT )) holds (R4 in C10 iff S11[ R4 ])) from SUBSET_1:sch 3;
defpred S12[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 3 * R5 ) + 1 ));
consider C11 being (Subset of ( NAT )) such that L172: (for R4 being (Element of ( NAT )) holds (R4 in C11 iff S12[ R4 ])) from SUBSET_1:sch 3;
defpred S13[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 3 * R5 ) + 2 ));
consider C12 being (Subset of ( NAT )) such that L173: (for R4 being (Element of ( NAT )) holds (R4 in C12 iff S13[ R4 ])) from SUBSET_1:sch 3;
defpred S14[ (Element of ( NAT )) , set ] means (($1 in C10 implies $2 = F4(( $1 / 3 ))) & ($1 in C11 implies $2 = F5(( ( $1 - 1 ) / 3 ))) & ($1 in C12 implies $2 = F6(( ( $1 - 2 ) / 3 ))));
L174: (for R4 being (Element of ( NAT )) holds (ex R7 being Real st S14[ R4 , R7 ]))
proof
let R4 being (Element of ( NAT ));
consider R5 being (Element of ( NAT )) such that L175: (R4 = ( 3 * R5 ) or R4 = ( ( 3 * R5 ) + 1 ) or R4 = ( ( 3 * R5 ) + 2 )) by L14;
L176:
now
per cases  by L175;
suppose L177: R4 = ( 3 * R5 );

take D13 = F4(( R4 / 3 ));
L178: R4 = ( ( 3 * R5 ) + ( 0 ) ) by L177;
L179:
now
assume L180: R4 in C12;
L181: (ex R6 being (Element of ( NAT )) st R4 = ( ( 3 * R6 ) + 2 )) by L180 , L173;
thus L182: contradiction by L181 , L178 , NAT_1:18;
end;
L183:
now
assume L184: R4 in C11;
L185: (ex R6 being (Element of ( NAT )) st R4 = ( ( 3 * R6 ) + 1 )) by L184 , L172;
thus L186: contradiction by L185 , L178 , NAT_1:18;
end;
thus L187: thesis by L183 , L179;
end;
suppose L188: R4 = ( ( 3 * R5 ) + 1 );

take D14 = F5(( ( R4 - 1 ) / 3 ));
L189:
now
assume L190: R4 in C10;
consider R6 being (Element of ( NAT )) such that L191: R4 = ( 3 * R6 ) by L190 , L171;
L192: R4 = ( ( 3 * R6 ) + ( 0 ) ) by L191;
thus L193: contradiction by L192 , L188 , NAT_1:18;
end;
L194:
now
assume L195: R4 in C12;
L196: (ex R6 being (Element of ( NAT )) st R4 = ( ( 3 * R6 ) + 2 )) by L195 , L173;
thus L197: contradiction by L196 , L188 , NAT_1:18;
end;
thus L198: thesis by L194 , L189;
end;
suppose L199: R4 = ( ( 3 * R5 ) + 2 );

take D15 = F6(( ( R4 - 2 ) / 3 ));
L200:
now
assume L201: R4 in C10;
consider R6 being (Element of ( NAT )) such that L202: R4 = ( 3 * R6 ) by L201 , L171;
L203: R4 = ( ( 3 * R6 ) + ( 0 ) ) by L202;
thus L204: contradiction by L203 , L199 , NAT_1:18;
end;
L205:
now
assume L206: R4 in C11;
L207: (ex R6 being (Element of ( NAT )) st R4 = ( ( 3 * R6 ) + 1 )) by L206 , L172;
thus L208: contradiction by L207 , L199 , NAT_1:18;
end;
thus L209: thesis by L205 , L200;
end;
end;
thus L211: thesis by L176;
end;
consider C13 being (Function of ( NAT ) , ( REAL )) such that L212: (for R4 being (Element of ( NAT )) holds S14[ R4 , ( C13 . R4 ) ]) from FUNCT_2:sch 3(L174);
reconsider D16 = C13 as Real_Sequence;
take D16;
let R4 being (Element of ( NAT ));
L213: ( 3 * R4 ) in C10 by L171;
thus L214: ( D16 . ( 3 * R4 ) ) = F4(( ( 3 * R4 ) / 3 )) by L213 , L212
.= F4(R4);
L215: ( ( 3 * R4 ) + 1 ) in C11 by L172;
thus L216: ( D16 . ( ( 3 * R4 ) + 1 ) ) = F5(( ( ( ( 3 * R4 ) + 1 ) - 1 ) / 3 )) by L215 , L212
.= F5(R4);
L217: ( ( 3 * R4 ) + 2 ) in C12 by L173;
thus L218: ( D16 . ( ( 3 * R4 ) + 2 ) ) = F6(( ( ( ( 3 * R4 ) + 2 ) - 2 ) / 3 )) by L217 , L212
.= F6(R4);
end;
scheme ExRealSeq4 { F7 , F8 , F9 , F10(set) -> Real } : (ex B18 being Real_Sequence st (for R4 being (Element of ( NAT )) holds (( B18 . ( 4 * R4 ) ) = F7(R4) & ( B18 . ( ( 4 * R4 ) + 1 ) ) = F8(R4) & ( B18 . ( ( 4 * R4 ) + 2 ) ) = F9(R4) & ( B18 . ( ( 4 * R4 ) + 3 ) ) = F10(R4))))
proof
defpred S15[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( 4 * R5 ));
consider C14 being (Subset of ( NAT )) such that L219: (for R4 being (Element of ( NAT )) holds (R4 in C14 iff S15[ R4 ])) from SUBSET_1:sch 3;
defpred S16[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 4 * R5 ) + 1 ));
consider C15 being (Subset of ( NAT )) such that L220: (for R4 being (Element of ( NAT )) holds (R4 in C15 iff S16[ R4 ])) from SUBSET_1:sch 3;
defpred S17[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 4 * R5 ) + 2 ));
consider C16 being (Subset of ( NAT )) such that L221: (for R4 being (Element of ( NAT )) holds (R4 in C16 iff S17[ R4 ])) from SUBSET_1:sch 3;
defpred S18[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 4 * R5 ) + 3 ));
consider C17 being (Subset of ( NAT )) such that L222: (for R4 being (Element of ( NAT )) holds (R4 in C17 iff S18[ R4 ])) from SUBSET_1:sch 3;
defpred S19[ (Element of ( NAT )) , set ] means (($1 in C14 implies $2 = F7(( $1 / 4 ))) & ($1 in C15 implies $2 = F8(( ( $1 - 1 ) / 4 ))) & ($1 in C16 implies $2 = F9(( ( $1 - 2 ) / 4 ))) & ($1 in C17 implies $2 = F10(( ( $1 - 3 ) / 4 ))));
L223: (for R4 being (Element of ( NAT )) holds (ex R7 being Real st S19[ R4 , R7 ]))
proof
let R4 being (Element of ( NAT ));
consider R5 being (Element of ( NAT )) such that L224: (R4 = ( 4 * R5 ) or R4 = ( ( 4 * R5 ) + 1 ) or R4 = ( ( 4 * R5 ) + 2 ) or R4 = ( ( 4 * R5 ) + 3 )) by L41;
L225:
now
per cases  by L224;
suppose L226: R4 = ( 4 * R5 );

take D17 = F7(( R4 / 4 ));
L227: R4 = ( ( 4 * R5 ) + ( 0 ) ) by L226;
L228:
now
assume L229: R4 in C16;
L230: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 2 )) by L229 , L221;
thus L231: contradiction by L230 , L227 , NAT_1:18;
end;
L232:
now
assume L233: R4 in C17;
L234: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 3 )) by L233 , L222;
thus L235: contradiction by L234 , L227 , NAT_1:18;
end;
L236:
now
assume L237: R4 in C15;
L238: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 1 )) by L237 , L220;
thus L239: contradiction by L238 , L227 , NAT_1:18;
end;
thus L240: thesis by L236 , L228 , L232;
end;
suppose L241: R4 = ( ( 4 * R5 ) + 1 );

take D18 = F8(( ( R4 - 1 ) / 4 ));
L242:
now
assume L243: R4 in C14;
consider R6 being (Element of ( NAT )) such that L244: R4 = ( 4 * R6 ) by L243 , L219;
L245: R4 = ( ( 4 * R6 ) + ( 0 ) ) by L244;
thus L246: contradiction by L245 , L241 , NAT_1:18;
end;
L247:
now
assume L248: R4 in C17;
L249: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 3 )) by L248 , L222;
thus L250: contradiction by L249 , L241 , NAT_1:18;
end;
L251:
now
assume L252: R4 in C16;
L253: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 2 )) by L252 , L221;
thus L254: contradiction by L253 , L241 , NAT_1:18;
end;
thus L255: thesis by L251 , L242 , L247;
end;
suppose L256: R4 = ( ( 4 * R5 ) + 2 );

take D19 = F9(( ( R4 - 2 ) / 4 ));
L257:
now
assume L258: R4 in C14;
consider R6 being (Element of ( NAT )) such that L259: R4 = ( 4 * R6 ) by L258 , L219;
L260: R4 = ( ( 4 * R6 ) + ( 0 ) ) by L259;
thus L261: contradiction by L260 , L256 , NAT_1:18;
end;
L262:
now
assume L263: R4 in C17;
L264: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 3 )) by L263 , L222;
thus L265: contradiction by L264 , L256 , NAT_1:18;
end;
L266:
now
assume L267: R4 in C15;
L268: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 1 )) by L267 , L220;
thus L269: contradiction by L268 , L256 , NAT_1:18;
end;
thus L270: thesis by L266 , L257 , L262;
end;
suppose L271: R4 = ( ( 4 * R5 ) + 3 );

take D20 = F10(( ( R4 - 3 ) / 4 ));
L272:
now
assume L273: R4 in C14;
consider R6 being (Element of ( NAT )) such that L274: R4 = ( 4 * R6 ) by L273 , L219;
L275: R4 = ( ( 4 * R6 ) + ( 0 ) ) by L274;
thus L276: contradiction by L275 , L271 , NAT_1:18;
end;
L277:
now
assume L278: R4 in C16;
L279: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 2 )) by L278 , L221;
thus L280: contradiction by L279 , L271 , NAT_1:18;
end;
L281:
now
assume L282: R4 in C15;
L283: (ex R6 being (Element of ( NAT )) st R4 = ( ( 4 * R6 ) + 1 )) by L282 , L220;
thus L284: contradiction by L283 , L271 , NAT_1:18;
end;
thus L285: thesis by L281 , L272 , L277;
end;
end;
thus L287: thesis by L225;
end;
consider C18 being (Function of ( NAT ) , ( REAL )) such that L288: (for R4 being (Element of ( NAT )) holds S19[ R4 , ( C18 . R4 ) ]) from FUNCT_2:sch 3(L223);
reconsider D21 = C18 as Real_Sequence;
take D21;
let R4 being (Element of ( NAT ));
L289: ( 4 * R4 ) in C14 by L219;
thus L290: ( D21 . ( 4 * R4 ) ) = F7(( ( 4 * R4 ) / 4 )) by L289 , L288
.= F7(R4);
L291: ( ( 4 * R4 ) + 1 ) in C15 by L220;
thus L292: ( D21 . ( ( 4 * R4 ) + 1 ) ) = F8(( ( ( ( 4 * R4 ) + 1 ) - 1 ) / 4 )) by L291 , L288
.= F8(R4);
L293: ( ( 4 * R4 ) + 2 ) in C16 by L221;
thus L294: ( D21 . ( ( 4 * R4 ) + 2 ) ) = F9(( ( ( ( 4 * R4 ) + 2 ) - 2 ) / 4 )) by L293 , L288
.= F9(R4);
L295: ( ( 4 * R4 ) + 3 ) in C17 by L222;
thus L296: ( D21 . ( ( 4 * R4 ) + 3 ) ) = F10(( ( ( ( 4 * R4 ) + 3 ) - 3 ) / 4 )) by L295 , L288
.= F10(R4);
end;
scheme ExRealSeq5 { F11 , F12 , F13 , F14 , F15(set) -> Real } : (ex B19 being Real_Sequence st (for R4 being (Element of ( NAT )) holds (( B19 . ( 5 * R4 ) ) = F11(R4) & ( B19 . ( ( 5 * R4 ) + 1 ) ) = F12(R4) & ( B19 . ( ( 5 * R4 ) + 2 ) ) = F13(R4) & ( B19 . ( ( 5 * R4 ) + 3 ) ) = F14(R4) & ( B19 . ( ( 5 * R4 ) + 4 ) ) = F15(R4))))
proof
defpred S20[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( 5 * R5 ));
consider C19 being (Subset of ( NAT )) such that L297: (for R4 being (Element of ( NAT )) holds (R4 in C19 iff S20[ R4 ])) from SUBSET_1:sch 3;
defpred S21[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 5 * R5 ) + 1 ));
consider C20 being (Subset of ( NAT )) such that L298: (for R4 being (Element of ( NAT )) holds (R4 in C20 iff S21[ R4 ])) from SUBSET_1:sch 3;
defpred S22[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 5 * R5 ) + 2 ));
consider C21 being (Subset of ( NAT )) such that L299: (for R4 being (Element of ( NAT )) holds (R4 in C21 iff S22[ R4 ])) from SUBSET_1:sch 3;
defpred S23[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 5 * R5 ) + 3 ));
consider C22 being (Subset of ( NAT )) such that L300: (for R4 being (Element of ( NAT )) holds (R4 in C22 iff S23[ R4 ])) from SUBSET_1:sch 3;
defpred S24[ set ] means (ex R5 being (Element of ( NAT )) st $1 = ( ( 5 * R5 ) + 4 ));
consider C23 being (Subset of ( NAT )) such that L301: (for R4 being (Element of ( NAT )) holds (R4 in C23 iff S24[ R4 ])) from SUBSET_1:sch 3;
defpred S25[ (Element of ( NAT )) , set ] means (($1 in C19 implies $2 = F11(( $1 / 5 ))) & ($1 in C20 implies $2 = F12(( ( $1 - 1 ) / 5 ))) & ($1 in C21 implies $2 = F13(( ( $1 - 2 ) / 5 ))) & ($1 in C22 implies $2 = F14(( ( $1 - 3 ) / 5 ))) & ($1 in C23 implies $2 = F15(( ( $1 - 4 ) / 5 ))));
L302: (for R4 being (Element of ( NAT )) holds (ex R7 being Real st S25[ R4 , R7 ]))
proof
let R4 being (Element of ( NAT ));
consider R5 being (Element of ( NAT )) such that L303: (R4 = ( 5 * R5 ) or R4 = ( ( 5 * R5 ) + 1 ) or R4 = ( ( 5 * R5 ) + 2 ) or R4 = ( ( 5 * R5 ) + 3 ) or R4 = ( ( 5 * R5 ) + 4 )) by L66;
L304:
now
per cases  by L303;
suppose L305: R4 = ( 5 * R5 );

take D22 = F11(( R4 / 5 ));
L306: R4 = ( ( 5 * R5 ) + ( 0 ) ) by L305;
L307:
now
assume L308: R4 in C21;
L309: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 2 )) by L308 , L299;
thus L310: contradiction by L309 , L306 , NAT_1:18;
end;
L311:
now
assume L312: R4 in C23;
L313: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 4 )) by L312 , L301;
thus L314: contradiction by L313 , L306 , NAT_1:18;
end;
L315:
now
assume L316: R4 in C22;
L317: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 3 )) by L316 , L300;
thus L318: contradiction by L317 , L306 , NAT_1:18;
end;
L319:
now
assume L320: R4 in C20;
L321: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 1 )) by L320 , L298;
thus L322: contradiction by L321 , L306 , NAT_1:18;
end;
thus L323: thesis by L319 , L307 , L315 , L311;
end;
suppose L324: R4 = ( ( 5 * R5 ) + 1 );

L325:
now
assume L326: R4 in C23;
L327: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 4 )) by L326 , L301;
thus L328: contradiction by L327 , L324 , NAT_1:18;
end;
L329:
now
assume L330: R4 in C22;
L331: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 3 )) by L330 , L300;
thus L332: contradiction by L331 , L324 , NAT_1:18;
end;
take D23 = F12(( ( R4 - 1 ) / 5 ));
L333:
now
assume L334: R4 in C19;
consider R6 being (Element of ( NAT )) such that L335: R4 = ( 5 * R6 ) by L334 , L297;
L336: R4 = ( ( 5 * R6 ) + ( 0 ) ) by L335;
thus L337: contradiction by L336 , L324 , NAT_1:18;
end;
L338:
now
assume L339: R4 in C21;
L340: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 2 )) by L339 , L299;
thus L341: contradiction by L340 , L324 , NAT_1:18;
end;
thus L342: thesis by L338 , L333 , L329 , L325;
end;
suppose L343: R4 = ( ( 5 * R5 ) + 2 );

L344:
now
assume L345: R4 in C23;
L346: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 4 )) by L345 , L301;
thus L347: contradiction by L346 , L343 , NAT_1:18;
end;
L348:
now
assume L349: R4 in C22;
L350: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 3 )) by L349 , L300;
thus L351: contradiction by L350 , L343 , NAT_1:18;
end;
take D24 = F13(( ( R4 - 2 ) / 5 ));
L352:
now
assume L353: R4 in C19;
consider R6 being (Element of ( NAT )) such that L354: R4 = ( 5 * R6 ) by L353 , L297;
L355: R4 = ( ( 5 * R6 ) + ( 0 ) ) by L354;
thus L356: contradiction by L355 , L343 , NAT_1:18;
end;
L357:
now
assume L358: R4 in C20;
L359: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 1 )) by L358 , L298;
thus L360: contradiction by L359 , L343 , NAT_1:18;
end;
thus L361: thesis by L357 , L352 , L348 , L344;
end;
suppose L362: R4 = ( ( 5 * R5 ) + 3 );

L363:
now
assume L364: R4 in C23;
L365: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 4 )) by L364 , L301;
thus L366: contradiction by L365 , L362 , NAT_1:18;
end;
L367:
now
assume L368: R4 in C21;
L369: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 2 )) by L368 , L299;
thus L370: contradiction by L369 , L362 , NAT_1:18;
end;
take D25 = F14(( ( R4 - 3 ) / 5 ));
L371:
now
assume L372: R4 in C19;
consider R6 being (Element of ( NAT )) such that L373: R4 = ( 5 * R6 ) by L372 , L297;
L374: R4 = ( ( 5 * R6 ) + ( 0 ) ) by L373;
thus L375: contradiction by L374 , L362 , NAT_1:18;
end;
L376:
now
assume L377: R4 in C20;
L378: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 1 )) by L377 , L298;
thus L379: contradiction by L378 , L362 , NAT_1:18;
end;
thus L380: thesis by L376 , L371 , L367 , L363;
end;
suppose L381: R4 = ( ( 5 * R5 ) + 4 );

L382:
now
assume L383: R4 in C22;
L384: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 3 )) by L383 , L300;
thus L385: contradiction by L384 , L381 , NAT_1:18;
end;
L386:
now
assume L387: R4 in C21;
L388: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 2 )) by L387 , L299;
thus L389: contradiction by L388 , L381 , NAT_1:18;
end;
take D26 = F15(( ( R4 - 4 ) / 5 ));
L390:
now
assume L391: R4 in C19;
consider R6 being (Element of ( NAT )) such that L392: R4 = ( 5 * R6 ) by L391 , L297;
L393: R4 = ( ( 5 * R6 ) + ( 0 ) ) by L392;
thus L394: contradiction by L393 , L381 , NAT_1:18;
end;
L395:
now
assume L396: R4 in C20;
L397: (ex R6 being (Element of ( NAT )) st R4 = ( ( 5 * R6 ) + 1 )) by L396 , L298;
thus L398: contradiction by L397 , L381 , NAT_1:18;
end;
thus L399: thesis by L395 , L390 , L386 , L382;
end;
end;
thus L401: thesis by L304;
end;
consider C24 being (Function of ( NAT ) , ( REAL )) such that L402: (for R4 being (Element of ( NAT )) holds S25[ R4 , ( C24 . R4 ) ]) from FUNCT_2:sch 3(L302);
reconsider D27 = C24 as Real_Sequence;
take D27;
let R4 being (Element of ( NAT ));
L403: ( 5 * R4 ) in C19 by L297;
thus L404: ( D27 . ( 5 * R4 ) ) = F11(( ( 5 * R4 ) / 5 )) by L403 , L402
.= F11(R4);
L405: ( ( 5 * R4 ) + 1 ) in C20 by L298;
thus L406: ( D27 . ( ( 5 * R4 ) + 1 ) ) = F12(( ( ( ( 5 * R4 ) + 1 ) - 1 ) / 5 )) by L405 , L402
.= F12(R4);
L407: ( ( 5 * R4 ) + 2 ) in C21 by L299;
thus L408: ( D27 . ( ( 5 * R4 ) + 2 ) ) = F13(( ( ( ( 5 * R4 ) + 2 ) - 2 ) / 5 )) by L407 , L402
.= F13(R4);
L409: ( ( 5 * R4 ) + 3 ) in C22 by L300;
thus L410: ( D27 . ( ( 5 * R4 ) + 3 ) ) = F14(( ( ( ( 5 * R4 ) + 3 ) - 3 ) / 5 )) by L409 , L402
.= F14(R4);
L411: ( ( 5 * R4 ) + 4 ) in C23 by L301;
thus L412: ( D27 . ( ( 5 * R4 ) + 4 ) ) = F15(( ( ( ( 5 * R4 ) + 4 ) - 4 ) / 5 )) by L411 , L402
.= F15(R4);
end;
scheme PartFuncExD2 { F16 , F17() -> non  empty set , P2 , P3[set] , F18 , F19(set) -> (Element of F17()) } : (ex B20 being (PartFunc of F16() , F17()) st ((for B21 being (Element of F16()) holds (B21 in ( dom B20 ) iff (P2[ B21 ] or P3[ B21 ]))) & (for B22 being (Element of F16()) holds (B22 in ( dom B20 ) implies ((P2[ B22 ] implies ( B20 . B22 ) = F18(B22)) & (P3[ B22 ] implies ( B20 . B22 ) = F19(B22)))))))
provided
L413: (for B23 being (Element of F16()) holds (P2[ B23 ] implies (not P3[ B23 ])))
proof
defpred S26[ set , set ] means ((P2[ $1 ] implies $2 = F18($1)) & (P3[ $1 ] implies $2 = F19($1)));
defpred S27[ set ] means (P2[ $1 ] or P3[ $1 ]);
consider C25 being set such that L414: (for R1 being set holds (R1 in C25 iff (R1 in F16() & S27[ R1 ]))) from XBOOLE_0:sch 1;
L415: (for R1 being set holds (R1 in C25 implies (ex R2 being set st S26[ R1 , R2 ])))
proof
let R1 being set;
assume L416: R1 in C25;
reconsider D28 = R1 as (Element of F16()) by L416 , L414;
L417:
now
per cases  by L414 , L416;
suppose L418: P2[ R1 ];

take D29 = F18(R1);
L419: (not P3[ D28 ]) by L413 , L418;
thus L420: thesis by L419;
end;
suppose L421: P3[ R1 ];

take D30 = F19(R1);
L422: (not P2[ D28 ]) by L413 , L421;
thus L423: thesis by L422;
end;
end;
thus L425: thesis by L417;
end;
consider C26 being Function such that L426: (( dom C26 ) = C25 & (for R1 being set holds (R1 in C25 implies S26[ R1 , ( C26 . R1 ) ]))) from CLASSES1:sch 1(L415);
L427: C25 c= F16()
proof
let R1 being set;
assume L428: R1 in C25;
thus L429: thesis by L428 , L414;
end;
L430: ( rng C26 ) c= F17()
proof
let R1 being set;
assume L431: R1 in ( rng C26 );
consider R2 being set such that L432: R2 in ( dom C26 ) and L433: R1 = ( C26 . R2 ) by L431 , FUNCT_1:def 3;
L434:
now
per cases  by L414 , L426 , L432;
suppose L435: P2[ R2 ];

L436: ( C26 . R2 ) = F18(R2) by L435 , L426 , L432;
thus L437: thesis by L436 , L433;
end;
suppose L438: P3[ R2 ];

L439: ( C26 . R2 ) = F19(R2) by L438 , L426 , L432;
thus L440: thesis by L439 , L433;
end;
end;
thus L442: thesis by L434;
end;
reconsider D31 = C26 as (PartFunc of F16() , F17()) by L430 , L427 , L426 , RELSET_1:4;
take D31;
thus L443: (for B24 being (Element of F16()) holds (B24 in ( dom D31 ) iff (P2[ B24 ] or P3[ B24 ]))) by L414 , L426;
let C27 being (Element of F16());
assume L444: C27 in ( dom D31 );
thus L445: thesis by L444 , L426;
end;
scheme PartFuncExD29 { F20 , F21() -> non  empty set , P4 , P5[set] , F22 , F23(set) -> (Element of F21()) } : (ex B25 being (PartFunc of F20() , F21()) st ((for B26 being (Element of F20()) holds (B26 in ( dom B25 ) iff (P4[ B26 ] or P5[ B26 ]))) & (for B27 being (Element of F20()) holds (B27 in ( dom B25 ) implies ((P4[ B27 ] implies ( B25 . B27 ) = F22(B27)) & (P5[ B27 ] implies ( B25 . B27 ) = F23(B27)))))))
provided
L446: (for B28 being (Element of F20()) holds ((P4[ B28 ] & P5[ B28 ]) implies F22(B28) = F23(B28)))
proof
defpred S28[ set , set ] means ((P4[ $1 ] implies $2 = F22($1)) & (P5[ $1 ] implies $2 = F23($1)));
defpred S29[ set ] means (P4[ $1 ] or P5[ $1 ]);
consider C28 being set such that L447: (for R1 being set holds (R1 in C28 iff (R1 in F20() & S29[ R1 ]))) from XBOOLE_0:sch 1;
L448: (for R1 being set holds (R1 in C28 implies (ex R2 being set st S28[ R1 , R2 ])))
proof
let R1 being set;
assume L449: R1 in C28;
reconsider D32 = R1 as (Element of F20()) by L449 , L447;
L450:
now
per cases  by L447 , L449;
suppose L451: P4[ D32 ];

take D33 = F22(D32);
L452:
now
per cases ;
suppose L453: P5[ D32 ];

L454: F22(D32) = F23(D32) by L453 , L446 , L451;
thus L455: thesis by L454;
end;
suppose L456: (not P5[ D32 ]);

thus L457: thesis by L456;
end;
end;
thus L459: thesis by L452;
end;
suppose L460: P5[ D32 ];

take D34 = F23(D32);
L461:
now
per cases ;
suppose L462: P4[ D32 ];

L463: F22(D32) = F23(D32) by L462 , L446 , L460;
thus L464: thesis by L463;
end;
suppose L465: (not P4[ D32 ]);

thus L466: thesis by L465;
end;
end;
thus L468: thesis by L461;
end;
end;
thus L470: thesis by L450;
end;
consider C29 being Function such that L471: (( dom C29 ) = C28 & (for R1 being set holds (R1 in C28 implies S28[ R1 , ( C29 . R1 ) ]))) from CLASSES1:sch 1(L448);
L472: C28 c= F20()
proof
let R1 being set;
assume L473: R1 in C28;
thus L474: thesis by L473 , L447;
end;
L475: ( rng C29 ) c= F21()
proof
let R1 being set;
assume L476: R1 in ( rng C29 );
consider R2 being set such that L477: R2 in ( dom C29 ) and L478: R1 = ( C29 . R2 ) by L476 , FUNCT_1:def 3;
L479:
now
per cases  by L447 , L471 , L477;
suppose L480: P4[ R2 ];

L481: ( C29 . R2 ) = F22(R2) by L480 , L471 , L477;
thus L482: thesis by L481 , L478;
end;
suppose L483: P5[ R2 ];

L484: ( C29 . R2 ) = F23(R2) by L483 , L471 , L477;
thus L485: thesis by L484 , L478;
end;
end;
thus L487: thesis by L479;
end;
reconsider D35 = C29 as (PartFunc of F20() , F21()) by L475 , L472 , L471 , RELSET_1:4;
take D35;
thus L488: (for B29 being (Element of F20()) holds (B29 in ( dom D35 ) iff (P4[ B29 ] or P5[ B29 ]))) by L447 , L471;
let C30 being (Element of F20());
assume L489: C30 in ( dom D35 );
thus L490: thesis by L489 , L471;
end;
scheme PartFuncExD299 { F24 , F25() -> non  empty set , P6[set] , F26 , F27(set) -> (Element of F25()) } : (ex B30 being (PartFunc of F24() , F25()) st (B30 is  total & (for B31 being (Element of F24()) holds (B31 in ( dom B30 ) implies ((P6[ B31 ] implies ( B30 . B31 ) = F26(B31)) & ((not P6[ B31 ]) implies ( B30 . B31 ) = F27(B31)))))))
proof
defpred S30[ set ] means (not P6[ $1 ]);
L491: (for B32 being (Element of F24()) holds (P6[ B32 ] implies (not S30[ B32 ])));
consider C31 being (PartFunc of F24() , F25()) such that L492: ((for B33 being (Element of F24()) holds (B33 in ( dom C31 ) iff (P6[ B33 ] or S30[ B33 ]))) & (for B34 being (Element of F24()) holds (B34 in ( dom C31 ) implies ((P6[ B34 ] implies ( C31 . B34 ) = F26(B34)) & (S30[ B34 ] implies ( C31 . B34 ) = F27(B34)))))) from PartFuncExD2(L491);
take C31;
L493: ( dom C31 ) = F24()
proof
thus L494: ( dom C31 ) c= F24();
let R1 being set;
assume L495: R1 in F24();
reconsider D36 = R1 as (Element of F24()) by L495;
L496: (P6[ D36 ] or (not P6[ D36 ]));
thus L497: thesis by L496 , L492;
end;
thus L498: C31 is  total by L493 , PARTFUN1:def 2;
thus L499: thesis by L492;
end;
scheme PartFuncExD3 { F28 , F29() -> non  empty set , P7 , P8 , P9[set] , F30 , F31 , F32(set) -> (Element of F29()) } : (ex B35 being (PartFunc of F28() , F29()) st ((for B36 being (Element of F28()) holds (B36 in ( dom B35 ) iff (P7[ B36 ] or P8[ B36 ] or P9[ B36 ]))) & (for B37 being (Element of F28()) holds (B37 in ( dom B35 ) implies ((P7[ B37 ] implies ( B35 . B37 ) = F30(B37)) & (P8[ B37 ] implies ( B35 . B37 ) = F31(B37)) & (P9[ B37 ] implies ( B35 . B37 ) = F32(B37)))))))
provided
L500: (for B38 being (Element of F28()) holds ((P7[ B38 ] implies (not P8[ B38 ])) & (P7[ B38 ] implies (not P9[ B38 ])) & (P8[ B38 ] implies (not P9[ B38 ]))))
proof
defpred S31[ set , set ] means ((P7[ $1 ] implies $2 = F30($1)) & (P8[ $1 ] implies $2 = F31($1)) & (P9[ $1 ] implies $2 = F32($1)));
defpred S32[ set ] means (P7[ $1 ] or P8[ $1 ] or P9[ $1 ]);
consider C32 being set such that L501: (for R1 being set holds (R1 in C32 iff (R1 in F28() & S32[ R1 ]))) from XBOOLE_0:sch 1;
L502: (for R1 being set holds (R1 in C32 implies (ex R2 being set st S31[ R1 , R2 ])))
proof
let R1 being set;
assume L503: R1 in C32;
reconsider D37 = R1 as (Element of F28()) by L503 , L501;
L504:
now
per cases  by L501 , L503;
suppose L505: P7[ R1 ];

take D38 = F30(R1);
L506: ((not P8[ D37 ]) & (not P9[ D37 ])) by L500 , L505;
thus L507: thesis by L506;
end;
suppose L508: P8[ R1 ];

take D39 = F31(R1);
L509: ((not P7[ D37 ]) & (not P9[ D37 ])) by L500 , L508;
thus L510: thesis by L509;
end;
suppose L511: P9[ R1 ];

take D40 = F32(R1);
L512: ((not P7[ D37 ]) & (not P8[ D37 ])) by L500 , L511;
thus L513: thesis by L512;
end;
end;
thus L515: thesis by L504;
end;
consider C33 being Function such that L516: (( dom C33 ) = C32 & (for R1 being set holds (R1 in C32 implies S31[ R1 , ( C33 . R1 ) ]))) from CLASSES1:sch 1(L502);
L517: ( rng C33 ) c= F29()
proof
let R1 being set;
assume L518: R1 in ( rng C33 );
consider R2 being set such that L519: R2 in ( dom C33 ) and L520: R1 = ( C33 . R2 ) by L518 , FUNCT_1:def 3;
L521:
now
per cases  by L501 , L516 , L519;
suppose L522: P7[ R2 ];

L523: ( C33 . R2 ) = F30(R2) by L522 , L516 , L519;
thus L524: thesis by L523 , L520;
end;
suppose L525: P8[ R2 ];

L526: ( C33 . R2 ) = F31(R2) by L525 , L516 , L519;
thus L527: thesis by L526 , L520;
end;
suppose L528: P9[ R2 ];

L529: ( C33 . R2 ) = F32(R2) by L528 , L516 , L519;
thus L530: thesis by L529 , L520;
end;
end;
thus L532: thesis by L521;
end;
L533: C32 c= F28()
proof
let R1 being set;
assume L534: R1 in C32;
thus L535: thesis by L534 , L501;
end;
reconsider D41 = C33 as (PartFunc of F28() , F29()) by L533 , L516 , L517 , RELSET_1:4;
take D41;
thus L536: (for B39 being (Element of F28()) holds (B39 in ( dom D41 ) iff (P7[ B39 ] or P8[ B39 ] or P9[ B39 ]))) by L501 , L516;
let C34 being (Element of F28());
assume L537: C34 in ( dom D41 );
thus L538: thesis by L537 , L516;
end;
scheme PartFuncExD39 { F33 , F34() -> non  empty set , P10 , P11 , P12[set] , F35 , F36 , F37(set) -> (Element of F34()) } : (ex B40 being (PartFunc of F33() , F34()) st ((for B41 being (Element of F33()) holds (B41 in ( dom B40 ) iff (P10[ B41 ] or P11[ B41 ] or P12[ B41 ]))) & (for B42 being (Element of F33()) holds (B42 in ( dom B40 ) implies ((P10[ B42 ] implies ( B40 . B42 ) = F35(B42)) & (P11[ B42 ] implies ( B40 . B42 ) = F36(B42)) & (P12[ B42 ] implies ( B40 . B42 ) = F37(B42)))))))
provided
L539: (for B43 being (Element of F33()) holds (((P10[ B43 ] & P11[ B43 ]) implies F35(B43) = F36(B43)) & ((P10[ B43 ] & P12[ B43 ]) implies F35(B43) = F37(B43)) & ((P11[ B43 ] & P12[ B43 ]) implies F36(B43) = F37(B43))))
proof
defpred S33[ set , set ] means ((P10[ $1 ] implies $2 = F35($1)) & (P11[ $1 ] implies $2 = F36($1)) & (P12[ $1 ] implies $2 = F37($1)));
defpred S34[ set ] means (P10[ $1 ] or P11[ $1 ] or P12[ $1 ]);
consider C35 being set such that L540: (for R1 being set holds (R1 in C35 iff (R1 in F33() & S34[ R1 ]))) from XBOOLE_0:sch 1;
L541: (for R1 being set holds (R1 in C35 implies (ex R2 being set st S33[ R1 , R2 ])))
proof
let R1 being set;
assume L542: R1 in C35;
reconsider D42 = R1 as (Element of F33()) by L542 , L540;
L543:
now
per cases  by L540 , L542;
suppose L544: P10[ D42 ];

take D43 = F35(D42);
L545:
now
per cases ;
suppose L546: P11[ D42 ];

L547: F35(D42) = F36(D42) by L546 , L539 , L544;
L548:
now
per cases ;
suppose L549: P12[ D42 ];

L550: F36(D42) = F37(D42) by L549 , L539 , L546;
thus L551: thesis by L550 , L547;
end;
suppose L552: (not P12[ D42 ]);

thus L553: thesis by L552 , L547;
end;
end;
thus L555: thesis by L548;
end;
suppose L556: (not P11[ D42 ]);

L557:
now
per cases ;
suppose L558: P12[ D42 ];

L559: F35(D42) = F37(D42) by L558 , L539 , L544;
thus L560: thesis by L559 , L556;
end;
suppose L561: (not P12[ D42 ]);

thus L562: thesis by L561 , L556;
end;
end;
thus L564: thesis by L557;
end;
end;
thus L566: thesis by L545;
end;
suppose L567: P11[ D42 ];

take D44 = F36(R1);
L568:
now
per cases ;
suppose L569: P10[ D42 ];

L570: F35(D42) = F36(D42) by L569 , L539 , L567;
L571:
now
per cases ;
suppose L572: P12[ D42 ];

L573: F36(D42) = F37(D42) by L572 , L539 , L567;
thus L574: thesis by L573 , L570;
end;
suppose L575: (not P12[ D42 ]);

thus L576: thesis by L575 , L570;
end;
end;
thus L578: thesis by L571;
end;
suppose L579: (not P10[ D42 ]);

L580:
now
per cases ;
suppose L581: P12[ D42 ];

L582: F36(D42) = F37(D42) by L581 , L539 , L567;
thus L583: thesis by L582 , L579;
end;
suppose L584: (not P12[ D42 ]);

thus L585: thesis by L584 , L579;
end;
end;
thus L587: thesis by L580;
end;
end;
thus L589: thesis by L568;
end;
suppose L590: P12[ D42 ];

take D45 = F37(R1);
L591:
now
per cases ;
suppose L592: P10[ D42 ];

L593: F35(D42) = F37(D42) by L592 , L539 , L590;
L594:
now
per cases ;
suppose L595: P11[ D42 ];

L596: F36(D42) = F37(D42) by L595 , L539 , L590;
thus L597: thesis by L596 , L593;
end;
suppose L598: (not P11[ D42 ]);

thus L599: thesis by L598 , L593;
end;
end;
thus L601: thesis by L594;
end;
suppose L602: (not P10[ D42 ]);

L603:
now
per cases ;
suppose L604: P11[ D42 ];

L605: F36(D42) = F37(D42) by L604 , L539 , L590;
thus L606: thesis by L605 , L602;
end;
suppose L607: (not P11[ D42 ]);

thus L608: thesis by L607 , L602;
end;
end;
thus L610: thesis by L603;
end;
end;
thus L612: thesis by L591;
end;
end;
thus L614: thesis by L543;
end;
consider C36 being Function such that L615: (( dom C36 ) = C35 & (for R1 being set holds (R1 in C35 implies S33[ R1 , ( C36 . R1 ) ]))) from CLASSES1:sch 1(L541);
L616: ( rng C36 ) c= F34()
proof
let R1 being set;
assume L617: R1 in ( rng C36 );
consider R2 being set such that L618: R2 in ( dom C36 ) and L619: R1 = ( C36 . R2 ) by L617 , FUNCT_1:def 3;
L620:
now
per cases  by L540 , L615 , L618;
suppose L621: P10[ R2 ];

L622: ( C36 . R2 ) = F35(R2) by L621 , L615 , L618;
thus L623: thesis by L622 , L619;
end;
suppose L624: P11[ R2 ];

L625: ( C36 . R2 ) = F36(R2) by L624 , L615 , L618;
thus L626: thesis by L625 , L619;
end;
suppose L627: P12[ R2 ];

L628: ( C36 . R2 ) = F37(R2) by L627 , L615 , L618;
thus L629: thesis by L628 , L619;
end;
end;
thus L631: thesis by L620;
end;
L632: C35 c= F33()
proof
let R1 being set;
assume L633: R1 in C35;
thus L634: thesis by L633 , L540;
end;
reconsider D46 = C36 as (PartFunc of F33() , F34()) by L632 , L615 , L616 , RELSET_1:4;
take D46;
thus L635: (for B44 being (Element of F33()) holds (B44 in ( dom D46 ) iff (P10[ B44 ] or P11[ B44 ] or P12[ B44 ]))) by L540 , L615;
let C37 being (Element of F33());
assume L636: C37 in ( dom D46 );
thus L637: thesis by L636 , L615;
end;
scheme PartFuncExD4 { F38 , F39() -> non  empty set , P13 , P14 , P15 , P16[set] , F40 , F41 , F42 , F43(set) -> (Element of F39()) } : (ex B45 being (PartFunc of F38() , F39()) st ((for B46 being (Element of F38()) holds (B46 in ( dom B45 ) iff (P13[ B46 ] or P14[ B46 ] or P15[ B46 ] or P16[ B46 ]))) & (for B47 being (Element of F38()) holds (B47 in ( dom B45 ) implies ((P13[ B47 ] implies ( B45 . B47 ) = F40(B47)) & (P14[ B47 ] implies ( B45 . B47 ) = F41(B47)) & (P15[ B47 ] implies ( B45 . B47 ) = F42(B47)) & (P16[ B47 ] implies ( B45 . B47 ) = F43(B47)))))))
provided
L638: (for B48 being (Element of F38()) holds ((P13[ B48 ] implies (not P14[ B48 ])) & (P13[ B48 ] implies (not P15[ B48 ])) & (P13[ B48 ] implies (not P16[ B48 ])) & (P14[ B48 ] implies (not P15[ B48 ])) & (P14[ B48 ] implies (not P16[ B48 ])) & (P15[ B48 ] implies (not P16[ B48 ]))))
proof
defpred S35[ set , set ] means ((P13[ $1 ] implies $2 = F40($1)) & (P14[ $1 ] implies $2 = F41($1)) & (P15[ $1 ] implies $2 = F42($1)) & (P16[ $1 ] implies $2 = F43($1)));
defpred S36[ set ] means (P13[ $1 ] or P14[ $1 ] or P15[ $1 ] or P16[ $1 ]);
consider C38 being set such that L639: (for R1 being set holds (R1 in C38 iff (R1 in F38() & S36[ R1 ]))) from XBOOLE_0:sch 1;
L640: (for R1 being set holds (R1 in C38 implies (ex R2 being set st S35[ R1 , R2 ])))
proof
let R1 being set;
assume L641: R1 in C38;
reconsider D47 = R1 as (Element of F38()) by L641 , L639;
L642:
now
per cases  by L639 , L641;
suppose L643: P13[ R1 ];

take D48 = F40(R1);
L644: (not P16[ D47 ]) by L638 , L643;
L645: ((not P14[ D47 ]) & (not P15[ D47 ])) by L638 , L643;
thus L646: thesis by L645 , L644;
end;
suppose L647: P14[ R1 ];

take D49 = F41(R1);
L648: (not P16[ D47 ]) by L638 , L647;
L649: ((not P13[ D47 ]) & (not P15[ D47 ])) by L638 , L647;
thus L650: thesis by L649 , L648;
end;
suppose L651: P15[ R1 ];

take D50 = F42(R1);
L652: (not P16[ D47 ]) by L638 , L651;
L653: ((not P13[ D47 ]) & (not P14[ D47 ])) by L638 , L651;
thus L654: thesis by L653 , L652;
end;
suppose L655: P16[ R1 ];

take D51 = F43(R1);
L656: (not P15[ D47 ]) by L638 , L655;
L657: ((not P13[ D47 ]) & (not P14[ D47 ])) by L638 , L655;
thus L658: thesis by L657 , L656;
end;
end;
thus L660: thesis by L642;
end;
consider C39 being Function such that L661: (( dom C39 ) = C38 & (for R2 being set holds (R2 in C38 implies S35[ R2 , ( C39 . R2 ) ]))) from CLASSES1:sch 1(L640);
L662: ( rng C39 ) c= F39()
proof
let R1 being set;
assume L663: R1 in ( rng C39 );
consider R2 being set such that L664: R2 in ( dom C39 ) and L665: R1 = ( C39 . R2 ) by L663 , FUNCT_1:def 3;
L666:
now
per cases  by L639 , L661 , L664;
suppose L667: P13[ R2 ];

L668: ( C39 . R2 ) = F40(R2) by L667 , L661 , L664;
thus L669: thesis by L668 , L665;
end;
suppose L670: P14[ R2 ];

L671: ( C39 . R2 ) = F41(R2) by L670 , L661 , L664;
thus L672: thesis by L671 , L665;
end;
suppose L673: P15[ R2 ];

L674: ( C39 . R2 ) = F42(R2) by L673 , L661 , L664;
thus L675: thesis by L674 , L665;
end;
suppose L676: P16[ R2 ];

L677: ( C39 . R2 ) = F43(R2) by L676 , L661 , L664;
thus L678: thesis by L677 , L665;
end;
end;
thus L680: thesis by L666;
end;
L681: C38 c= F38()
proof
let R1 being set;
assume L682: R1 in C38;
thus L683: thesis by L682 , L639;
end;
reconsider D52 = C39 as (PartFunc of F38() , F39()) by L681 , L661 , L662 , RELSET_1:4;
take D52;
thus L684: (for B49 being (Element of F38()) holds (B49 in ( dom D52 ) iff (P13[ B49 ] or P14[ B49 ] or P15[ B49 ] or P16[ B49 ]))) by L639 , L661;
let C40 being (Element of F38());
assume L685: C40 in ( dom D52 );
thus L686: thesis by L685 , L661;
end;
scheme PartFuncExS2 { F44 , F45() -> set , P17 , P18[set] , F46 , F47(set) -> set } : (ex B50 being (PartFunc of F44() , F45()) st ((for R1 being set holds (R1 in ( dom B50 ) iff (R1 in F44() & (P17[ R1 ] or P18[ R1 ])))) & (for R1 being set holds (R1 in ( dom B50 ) implies ((P17[ R1 ] implies ( B50 . R1 ) = F46(R1)) & (P18[ R1 ] implies ( B50 . R1 ) = F47(R1)))))))
provided
L687: (for R1 being set holds (R1 in F44() implies (P17[ R1 ] implies (not P18[ R1 ]))))
and
L688: (for R1 being set holds ((R1 in F44() & P17[ R1 ]) implies F46(R1) in F45()))
and
L689: (for R1 being set holds ((R1 in F44() & P18[ R1 ]) implies F47(R1) in F45()))
proof
defpred S37[ set , set ] means ((P17[ $1 ] implies $2 = F46($1)) & (P18[ $1 ] implies $2 = F47($1)));
defpred S38[ set ] means (P17[ $1 ] or P18[ $1 ]);
consider C41 being set such that L690: (for R1 being set holds (R1 in C41 iff (R1 in F44() & S38[ R1 ]))) from XBOOLE_0:sch 1;
L691: (for R1 being set holds (R1 in C41 implies (ex R2 being set st S37[ R1 , R2 ])))
proof
let R1 being set;
assume L692: R1 in C41;
L693: R1 in F44() by L692 , L690;
L694:
now
per cases  by L690 , L692;
suppose L695: P17[ R1 ];

take D53 = F46(R1);
L696: (not P18[ R1 ]) by L687 , L693 , L695;
thus L697: thesis by L696;
end;
suppose L698: P18[ R1 ];

take D54 = F47(R1);
L699: (not P17[ R1 ]) by L687 , L693 , L698;
thus L700: thesis by L699;
end;
end;
thus L702: thesis by L694;
end;
consider C42 being Function such that L703: (( dom C42 ) = C41 & (for R1 being set holds (R1 in C41 implies S37[ R1 , ( C42 . R1 ) ]))) from CLASSES1:sch 1(L691);
L704: C41 c= F44()
proof
let R1 being set;
assume L705: R1 in C41;
thus L706: thesis by L705 , L690;
end;
L707: ( rng C42 ) c= F45()
proof
let R1 being set;
assume L708: R1 in ( rng C42 );
consider R2 being set such that L709: R2 in ( dom C42 ) and L710: R1 = ( C42 . R2 ) by L708 , FUNCT_1:def 3;
L711:
now
per cases  by L690 , L703 , L709;
suppose L712: P17[ R2 ];

L713: ( C42 . R2 ) = F46(R2) by L712 , L703 , L709;
thus L714: thesis by L713 , L688 , L704 , L703 , L709 , L710 , L712;
end;
suppose L715: P18[ R2 ];

L716: ( C42 . R2 ) = F47(R2) by L715 , L703 , L709;
thus L717: thesis by L716 , L689 , L704 , L703 , L709 , L710 , L715;
end;
end;
thus L719: thesis by L711;
end;
reconsider D55 = C42 as (PartFunc of F44() , F45()) by L707 , L704 , L703 , RELSET_1:4;
take D55;
thus L720: (for R1 being set holds (R1 in ( dom D55 ) iff (R1 in F44() & (P17[ R1 ] or P18[ R1 ])))) by L690 , L703;
let R1 being set;
assume L721: R1 in ( dom D55 );
thus L722: thesis by L721 , L703;
end;
scheme PartFuncExS3 { F48 , F49() -> set , P19 , P20 , P21[set] , F50 , F51 , F52(set) -> set } : (ex B51 being (PartFunc of F48() , F49()) st ((for R1 being set holds (R1 in ( dom B51 ) iff (R1 in F48() & (P19[ R1 ] or P20[ R1 ] or P21[ R1 ])))) & (for R1 being set holds (R1 in ( dom B51 ) implies ((P19[ R1 ] implies ( B51 . R1 ) = F50(R1)) & (P20[ R1 ] implies ( B51 . R1 ) = F51(R1)) & (P21[ R1 ] implies ( B51 . R1 ) = F52(R1)))))))
provided
L723: (for R1 being set holds (R1 in F48() implies ((P19[ R1 ] implies (not P20[ R1 ])) & (P19[ R1 ] implies (not P21[ R1 ])) & (P20[ R1 ] implies (not P21[ R1 ])))))
and
L724: (for R1 being set holds ((R1 in F48() & P19[ R1 ]) implies F50(R1) in F49()))
and
L725: (for R1 being set holds ((R1 in F48() & P20[ R1 ]) implies F51(R1) in F49()))
and
L726: (for R1 being set holds ((R1 in F48() & P21[ R1 ]) implies F52(R1) in F49()))
proof
defpred S39[ set , set ] means ((P19[ $1 ] implies $2 = F50($1)) & (P20[ $1 ] implies $2 = F51($1)) & (P21[ $1 ] implies $2 = F52($1)));
defpred S40[ set ] means (P19[ $1 ] or P20[ $1 ] or P21[ $1 ]);
consider C43 being set such that L727: (for R1 being set holds (R1 in C43 iff (R1 in F48() & S40[ R1 ]))) from XBOOLE_0:sch 1;
L728: (for R1 being set holds (R1 in C43 implies (ex R2 being set st S39[ R1 , R2 ])))
proof
let R1 being set;
assume L729: R1 in C43;
L730: R1 in F48() by L729 , L727;
L731:
now
per cases  by L727 , L729;
suppose L732: P19[ R1 ];

take D56 = F50(R1);
L733: ((not P20[ R1 ]) & (not P21[ R1 ])) by L723 , L730 , L732;
thus L734: thesis by L733;
end;
suppose L735: P20[ R1 ];

take D57 = F51(R1);
L736: ((not P19[ R1 ]) & (not P21[ R1 ])) by L723 , L730 , L735;
thus L737: thesis by L736;
end;
suppose L738: P21[ R1 ];

take D58 = F52(R1);
L739: ((not P19[ R1 ]) & (not P20[ R1 ])) by L723 , L730 , L738;
thus L740: thesis by L739;
end;
end;
thus L742: thesis by L731;
end;
consider C44 being Function such that L743: (( dom C44 ) = C43 & (for R1 being set holds (R1 in C43 implies S39[ R1 , ( C44 . R1 ) ]))) from CLASSES1:sch 1(L728);
L744: C43 c= F48()
proof
let R1 being set;
assume L745: R1 in C43;
thus L746: thesis by L745 , L727;
end;
L747: ( rng C44 ) c= F49()
proof
let R1 being set;
assume L748: R1 in ( rng C44 );
consider R2 being set such that L749: R2 in ( dom C44 ) and L750: R1 = ( C44 . R2 ) by L748 , FUNCT_1:def 3;
L751:
now
per cases  by L727 , L743 , L749;
suppose L752: P19[ R2 ];

L753: ( C44 . R2 ) = F50(R2) by L752 , L743 , L749;
thus L754: thesis by L753 , L724 , L744 , L743 , L749 , L750 , L752;
end;
suppose L755: P20[ R2 ];

L756: ( C44 . R2 ) = F51(R2) by L755 , L743 , L749;
thus L757: thesis by L756 , L725 , L744 , L743 , L749 , L750 , L755;
end;
suppose L758: P21[ R2 ];

L759: ( C44 . R2 ) = F52(R2) by L758 , L743 , L749;
thus L760: thesis by L759 , L726 , L744 , L743 , L749 , L750 , L758;
end;
end;
thus L762: thesis by L751;
end;
reconsider D59 = C44 as (PartFunc of F48() , F49()) by L747 , L744 , L743 , RELSET_1:4;
take D59;
thus L763: (for R1 being set holds (R1 in ( dom D59 ) iff (R1 in F48() & (P19[ R1 ] or P20[ R1 ] or P21[ R1 ])))) by L727 , L743;
let R1 being set;
assume L764: R1 in ( dom D59 );
thus L765: thesis by L764 , L743;
end;
scheme PartFuncExS4 { F53 , F54() -> set , P22 , P23 , P24 , P25[set] , F55 , F56 , F57 , F58(set) -> set } : (ex B52 being (PartFunc of F53() , F54()) st ((for R1 being set holds (R1 in ( dom B52 ) iff (R1 in F53() & (P22[ R1 ] or P23[ R1 ] or P24[ R1 ] or P25[ R1 ])))) & (for R1 being set holds (R1 in ( dom B52 ) implies ((P22[ R1 ] implies ( B52 . R1 ) = F55(R1)) & (P23[ R1 ] implies ( B52 . R1 ) = F56(R1)) & (P24[ R1 ] implies ( B52 . R1 ) = F57(R1)) & (P25[ R1 ] implies ( B52 . R1 ) = F58(R1)))))))
provided
L766: (for R1 being set holds (R1 in F53() implies ((P22[ R1 ] implies (not P23[ R1 ])) & (P22[ R1 ] implies (not P24[ R1 ])) & (P22[ R1 ] implies (not P25[ R1 ])) & (P23[ R1 ] implies (not P24[ R1 ])) & (P23[ R1 ] implies (not P25[ R1 ])) & (P24[ R1 ] implies (not P25[ R1 ])))))
and
L767: (for R1 being set holds ((R1 in F53() & P22[ R1 ]) implies F55(R1) in F54()))
and
L768: (for R1 being set holds ((R1 in F53() & P23[ R1 ]) implies F56(R1) in F54()))
and
L769: (for R1 being set holds ((R1 in F53() & P24[ R1 ]) implies F57(R1) in F54()))
and
L770: (for R1 being set holds ((R1 in F53() & P25[ R1 ]) implies F58(R1) in F54()))
proof
defpred S41[ set , set ] means ((P22[ $1 ] implies $2 = F55($1)) & (P23[ $1 ] implies $2 = F56($1)) & (P24[ $1 ] implies $2 = F57($1)) & (P25[ $1 ] implies $2 = F58($1)));
defpred S42[ set ] means (P22[ $1 ] or P23[ $1 ] or P24[ $1 ] or P25[ $1 ]);
consider C45 being set such that L771: (for R1 being set holds (R1 in C45 iff (R1 in F53() & S42[ R1 ]))) from XBOOLE_0:sch 1;
L772: (for R1 being set holds (R1 in C45 implies (ex R2 being set st S41[ R1 , R2 ])))
proof
let R1 being set;
assume L773: R1 in C45;
L774: R1 in F53() by L773 , L771;
L775:
now
per cases  by L771 , L773;
suppose L776: P22[ R1 ];

take D60 = F55(R1);
L777: (not P25[ R1 ]) by L766 , L774 , L776;
L778: ((not P23[ R1 ]) & (not P24[ R1 ])) by L766 , L774 , L776;
thus L779: thesis by L778 , L777;
end;
suppose L780: P23[ R1 ];

take D61 = F56(R1);
L781: (not P25[ R1 ]) by L766 , L774 , L780;
L782: ((not P22[ R1 ]) & (not P24[ R1 ])) by L766 , L774 , L780;
thus L783: thesis by L782 , L781;
end;
suppose L784: P24[ R1 ];

take D62 = F57(R1);
L785: (not P25[ R1 ]) by L766 , L774 , L784;
L786: ((not P22[ R1 ]) & (not P23[ R1 ])) by L766 , L774 , L784;
thus L787: thesis by L786 , L785;
end;
suppose L788: P25[ R1 ];

take D63 = F58(R1);
L789: (not P24[ R1 ]) by L766 , L774 , L788;
L790: ((not P22[ R1 ]) & (not P23[ R1 ])) by L766 , L774 , L788;
thus L791: thesis by L790 , L789;
end;
end;
thus L793: thesis by L775;
end;
consider C46 being Function such that L794: (( dom C46 ) = C45 & (for R1 being set holds (R1 in C45 implies S41[ R1 , ( C46 . R1 ) ]))) from CLASSES1:sch 1(L772);
L795: C45 c= F53()
proof
let R1 being set;
assume L796: R1 in C45;
thus L797: thesis by L796 , L771;
end;
L798: ( rng C46 ) c= F54()
proof
let R1 being set;
assume L799: R1 in ( rng C46 );
consider R2 being set such that L800: R2 in ( dom C46 ) and L801: R1 = ( C46 . R2 ) by L799 , FUNCT_1:def 3;
L802:
now
per cases  by L771 , L794 , L800;
suppose L803: P22[ R2 ];

L804: ( C46 . R2 ) = F55(R2) by L803 , L794 , L800;
thus L805: thesis by L804 , L767 , L795 , L794 , L800 , L801 , L803;
end;
suppose L806: P23[ R2 ];

L807: ( C46 . R2 ) = F56(R2) by L806 , L794 , L800;
thus L808: thesis by L807 , L768 , L795 , L794 , L800 , L801 , L806;
end;
suppose L809: P24[ R2 ];

L810: ( C46 . R2 ) = F57(R2) by L809 , L794 , L800;
thus L811: thesis by L810 , L769 , L795 , L794 , L800 , L801 , L809;
end;
suppose L812: P25[ R2 ];

L813: ( C46 . R2 ) = F58(R2) by L812 , L794 , L800;
thus L814: thesis by L813 , L770 , L795 , L794 , L800 , L801 , L812;
end;
end;
thus L816: thesis by L802;
end;
reconsider D64 = C46 as (PartFunc of F53() , F54()) by L798 , L795 , L794 , RELSET_1:4;
take D64;
thus L817: (for R1 being set holds (R1 in ( dom D64 ) iff (R1 in F53() & (P22[ R1 ] or P23[ R1 ] or P24[ R1 ] or P25[ R1 ])))) by L771 , L794;
let R1 being set;
assume L818: R1 in ( dom D64 );
thus L819: thesis by L818 , L794;
end;
scheme PartFuncExCD2 { F59 , F60 , F61() -> non  empty set , P26 , P27[set , set] , F62 , F63(set , set) -> (Element of F61()) } : (ex B53 being (PartFunc of [: F59() , F60() :] , F61()) st ((for B54 being (Element of F59()) holds (for B55 being (Element of F60()) holds ([ B54 , B55 ] in ( dom B53 ) iff (P26[ B54 , B55 ] or P27[ B54 , B55 ])))) & (for B56 being (Element of F59()) holds (for B57 being (Element of F60()) holds ([ B56 , B57 ] in ( dom B53 ) implies ((P26[ B56 , B57 ] implies ( B53 . [ B56 , B57 ] ) = F62(B56 , B57)) & (P27[ B56 , B57 ] implies ( B53 . [ B56 , B57 ] ) = F63(B56 , B57))))))))
provided
L820: (for B58 being (Element of F59()) holds (for B59 being (Element of F60()) holds (P26[ B58 , B59 ] implies (not P27[ B58 , B59 ]))))
proof
defpred S43[ set , set ] means (for B60 being (Element of F59()) holds (for B61 being (Element of F60()) holds ($1 = [ B60 , B61 ] implies ((P26[ B60 , B61 ] implies $2 = F62(B60 , B61)) & (P27[ B60 , B61 ] implies $2 = F63(B60 , B61))))));
defpred S44[ set ] means (for B62 being (Element of F59()) holds (for B63 being (Element of F60()) holds ($1 = [ B62 , B63 ] implies (P26[ B62 , B63 ] or P27[ B62 , B63 ]))));
consider C47 being set such that L821: (for R3 being set holds (R3 in C47 iff (R3 in [: F59() , F60() :] & S44[ R3 ]))) from XBOOLE_0:sch 1;
L822: (for B64 being set holds (B64 in C47 implies (ex R3 being set st S43[ B64 , R3 ])))
proof
let C48 being set;
assume L823: C48 in C47;
L824: C48 in [: F59() , F60() :] by L823 , L821;
consider C49 , C50 being set such that L825: C49 in F59() and L826: C50 in F60() and L827: C48 = [ C49 , C50 ] by L824 , ZFMISC_1:def 2;
reconsider D65 = C50 as (Element of F60()) by L826;
reconsider D66 = C49 as (Element of F59()) by L825;
L828:
now
per cases  by L821 , L823 , L827;
suppose L829: P26[ D66 , D65 ];

take D67 = F62(D66 , D65);
let C51 being (Element of F59());
let C52 being (Element of F60());
assume L830: C48 = [ C51 , C52 ];
L831: (D66 = C51 & D65 = C52) by L830 , L827 , XTUPLE_0:1;
thus L832: ((P26[ C51 , C52 ] implies D67 = F62(C51 , C52)) & (P27[ C51 , C52 ] implies D67 = F63(C51 , C52))) by L831 , L820 , L829;
end;
suppose L833: P27[ D66 , D65 ];

take D68 = F63(D66 , D65);
let C53 being (Element of F59());
let C54 being (Element of F60());
assume L834: C48 = [ C53 , C54 ];
L835: (D66 = C53 & D65 = C54) by L834 , L827 , XTUPLE_0:1;
thus L836: ((P26[ C53 , C54 ] implies D68 = F62(C53 , C54)) & (P27[ C53 , C54 ] implies D68 = F63(C53 , C54))) by L835 , L820 , L833;
end;
end;
thus L838: thesis by L828;
end;
consider C55 being Function such that L839: (( dom C55 ) = C47 & (for R3 being set holds (R3 in C47 implies S43[ R3 , ( C55 . R3 ) ]))) from CLASSES1:sch 1(L822);
L840: ( rng C55 ) c= F61()
proof
let R3 being set;
assume L841: R3 in ( rng C55 );
consider C56 being set such that L842: C56 in ( dom C55 ) and L843: R3 = ( C55 . C56 ) by L841 , FUNCT_1:def 3;
L844: C56 in [: F59() , F60() :] by L821 , L839 , L842;
consider R1 being set, R2 being set such that L845: R1 in F59() and L846: R2 in F60() and L847: C56 = [ R1 , R2 ] by L844 , ZFMISC_1:def 2;
reconsider D69 = R2 as (Element of F60()) by L846;
reconsider D70 = R1 as (Element of F59()) by L845;
L848:
now
per cases  by L821 , L839 , L842 , L847;
suppose L849: P26[ D70 , D69 ];

L850: ( C55 . [ D70 , D69 ] ) = F62(D70 , D69) by L849 , L839 , L842 , L847;
thus L851: thesis by L850 , L843 , L847;
end;
suppose L852: P27[ D70 , D69 ];

L853: ( C55 . [ D70 , D69 ] ) = F63(D70 , D69) by L852 , L839 , L842 , L847;
thus L854: thesis by L853 , L843 , L847;
end;
end;
thus L856: thesis by L848;
end;
L857: C47 c= [: F59() , F60() :]
proof
let R3 being set;
assume L858: R3 in C47;
thus L859: thesis by L858 , L821;
end;
reconsider D71 = C55 as (PartFunc of [: F59() , F60() :] , F61()) by L857 , L839 , L840 , RELSET_1:4;
take D71;
thus L860: (for B65 being (Element of F59()) holds (for B66 being (Element of F60()) holds ([ B65 , B66 ] in ( dom D71 ) iff (P26[ B65 , B66 ] or P27[ B65 , B66 ]))))
proof
let C57 being (Element of F59());
let C58 being (Element of F60());
thus L861: ([ C57 , C58 ] in ( dom D71 ) implies (P26[ C57 , C58 ] or P27[ C57 , C58 ])) by L821 , L839;
assume L862: (P26[ C57 , C58 ] or P27[ C57 , C58 ]);
L863:
now
let C59 being (Element of F59());
let C60 being (Element of F60());
assume L864: [ C57 , C58 ] = [ C59 , C60 ];
L865: C57 = C59 by L864 , XTUPLE_0:1;
thus L866: (P26[ C59 , C60 ] or P27[ C59 , C60 ]) by L865 , L862 , L864 , XTUPLE_0:1;
end;
L867: [ C57 , C58 ] in [: F59() , F60() :] by ZFMISC_1:87;
thus L868: thesis by L867 , L821 , L839 , L863;
end;

let C61 being (Element of F59());
let C62 being (Element of F60());
assume L869: [ C61 , C62 ] in ( dom D71 );
thus L870: thesis by L869 , L839;
end;
scheme PartFuncExCD3 { F64 , F65 , F66() -> non  empty set , P28 , P29 , P30[set , set] , F67 , F68 , F69(set , set) -> (Element of F66()) } : (ex B67 being (PartFunc of [: F64() , F65() :] , F66()) st ((for B68 being (Element of F64()) holds (for B69 being (Element of F65()) holds ([ B68 , B69 ] in ( dom B67 ) iff (P28[ B68 , B69 ] or P29[ B68 , B69 ] or P30[ B68 , B69 ])))) & (for B70 being (Element of F64()) holds (for B71 being (Element of F65()) holds ([ B70 , B71 ] in ( dom B67 ) implies ((P28[ B70 , B71 ] implies ( B67 . [ B70 , B71 ] ) = F67(B70 , B71)) & (P29[ B70 , B71 ] implies ( B67 . [ B70 , B71 ] ) = F68(B70 , B71)) & (P30[ B70 , B71 ] implies ( B67 . [ B70 , B71 ] ) = F69(B70 , B71))))))))
provided
L871: (for B72 being (Element of F64()) holds (for B73 being (Element of F65()) holds ((P28[ B72 , B73 ] implies (not P29[ B72 , B73 ])) & (P28[ B72 , B73 ] implies (not P30[ B72 , B73 ])) & (P29[ B72 , B73 ] implies (not P30[ B72 , B73 ])))))
proof
defpred S45[ set , set ] means (for B74 being (Element of F64()) holds (for B75 being (Element of F65()) holds ($1 = [ B74 , B75 ] implies ((P28[ B74 , B75 ] implies $2 = F67(B74 , B75)) & (P29[ B74 , B75 ] implies $2 = F68(B74 , B75)) & (P30[ B74 , B75 ] implies $2 = F69(B74 , B75))))));
defpred S46[ set ] means (for B76 being (Element of F64()) holds (for B77 being (Element of F65()) holds ($1 = [ B76 , B77 ] implies (P28[ B76 , B77 ] or P29[ B76 , B77 ] or P30[ B76 , B77 ]))));
consider C63 being set such that L872: (for R3 being set holds (R3 in C63 iff (R3 in [: F64() , F65() :] & S46[ R3 ]))) from XBOOLE_0:sch 1;
L873: (for B78 being set holds (B78 in C63 implies (ex R3 being set st S45[ B78 , R3 ])))
proof
let C64 being set;
assume L874: C64 in C63;
L875: C64 in [: F64() , F65() :] by L874 , L872;
consider C65 , C66 being set such that L876: C65 in F64() and L877: C66 in F65() and L878: C64 = [ C65 , C66 ] by L875 , ZFMISC_1:def 2;
reconsider D72 = C66 as (Element of F65()) by L877;
reconsider D73 = C65 as (Element of F64()) by L876;
L879:
now
per cases  by L872 , L874 , L878;
suppose L880: P28[ D73 , D72 ];

take D74 = F67(D73 , D72);
let C67 being (Element of F64());
let C68 being (Element of F65());
assume L881: C64 = [ C67 , C68 ];
L882: (D73 = C67 & D72 = C68) by L881 , L878 , XTUPLE_0:1;
thus L883: ((P28[ C67 , C68 ] implies D74 = F67(C67 , C68)) & (P29[ C67 , C68 ] implies D74 = F68(C67 , C68)) & (P30[ C67 , C68 ] implies D74 = F69(C67 , C68))) by L882 , L871 , L880;
end;
suppose L884: P29[ D73 , D72 ];

take D75 = F68(D73 , D72);
let C69 being (Element of F64());
let C70 being (Element of F65());
assume L885: C64 = [ C69 , C70 ];
L886: (D73 = C69 & D72 = C70) by L885 , L878 , XTUPLE_0:1;
thus L887: ((P28[ C69 , C70 ] implies D75 = F67(C69 , C70)) & (P29[ C69 , C70 ] implies D75 = F68(C69 , C70)) & (P30[ C69 , C70 ] implies D75 = F69(C69 , C70))) by L886 , L871 , L884;
end;
suppose L888: P30[ D73 , D72 ];

take D76 = F69(D73 , D72);
let C71 being (Element of F64());
let C72 being (Element of F65());
assume L889: C64 = [ C71 , C72 ];
L890: (D73 = C71 & D72 = C72) by L889 , L878 , XTUPLE_0:1;
thus L891: ((P28[ C71 , C72 ] implies D76 = F67(C71 , C72)) & (P29[ C71 , C72 ] implies D76 = F68(C71 , C72)) & (P30[ C71 , C72 ] implies D76 = F69(C71 , C72))) by L890 , L871 , L888;
end;
end;
thus L893: thesis by L879;
end;
consider C73 being Function such that L894: (( dom C73 ) = C63 & (for R3 being set holds (R3 in C63 implies S45[ R3 , ( C73 . R3 ) ]))) from CLASSES1:sch 1(L873);
L895: ( rng C73 ) c= F66()
proof
let R3 being set;
assume L896: R3 in ( rng C73 );
consider C74 being set such that L897: C74 in ( dom C73 ) and L898: R3 = ( C73 . C74 ) by L896 , FUNCT_1:def 3;
L899: C74 in [: F64() , F65() :] by L872 , L894 , L897;
consider R1 being set, R2 being set such that L900: R1 in F64() and L901: R2 in F65() and L902: C74 = [ R1 , R2 ] by L899 , ZFMISC_1:def 2;
reconsider D77 = R2 as (Element of F65()) by L901;
reconsider D78 = R1 as (Element of F64()) by L900;
L903:
now
per cases  by L872 , L894 , L897 , L902;
suppose L904: P28[ D78 , D77 ];

L905: ( C73 . [ D78 , D77 ] ) = F67(D78 , D77) by L904 , L894 , L897 , L902;
thus L906: thesis by L905 , L898 , L902;
end;
suppose L907: P29[ D78 , D77 ];

L908: ( C73 . [ D78 , D77 ] ) = F68(D78 , D77) by L907 , L894 , L897 , L902;
thus L909: thesis by L908 , L898 , L902;
end;
suppose L910: P30[ D78 , D77 ];

L911: ( C73 . [ D78 , D77 ] ) = F69(D78 , D77) by L910 , L894 , L897 , L902;
thus L912: thesis by L911 , L898 , L902;
end;
end;
thus L914: thesis by L903;
end;
L915: C63 c= [: F64() , F65() :]
proof
let R3 being set;
assume L916: R3 in C63;
thus L917: thesis by L916 , L872;
end;
reconsider D79 = C73 as (PartFunc of [: F64() , F65() :] , F66()) by L915 , L894 , L895 , RELSET_1:4;
take D79;
thus L918: (for B79 being (Element of F64()) holds (for B80 being (Element of F65()) holds ([ B79 , B80 ] in ( dom D79 ) iff (P28[ B79 , B80 ] or P29[ B79 , B80 ] or P30[ B79 , B80 ]))))
proof
let C75 being (Element of F64());
let C76 being (Element of F65());
thus L919: ([ C75 , C76 ] in ( dom D79 ) implies (P28[ C75 , C76 ] or P29[ C75 , C76 ] or P30[ C75 , C76 ])) by L872 , L894;
assume L920: (P28[ C75 , C76 ] or P29[ C75 , C76 ] or P30[ C75 , C76 ]);
L921:
now
let C77 being (Element of F64());
let C78 being (Element of F65());
assume L922: [ C75 , C76 ] = [ C77 , C78 ];
L923: C75 = C77 by L922 , XTUPLE_0:1;
thus L924: (P28[ C77 , C78 ] or P29[ C77 , C78 ] or P30[ C77 , C78 ]) by L923 , L920 , L922 , XTUPLE_0:1;
end;
L925: [ C75 , C76 ] in [: F64() , F65() :] by ZFMISC_1:87;
thus L926: thesis by L925 , L872 , L894 , L921;
end;

let C79 being (Element of F64());
let C80 being (Element of F65());
assume L927: [ C79 , C80 ] in ( dom D79 );
thus L928: thesis by L927 , L894;
end;
scheme PartFuncExCS2 { F70 , F71 , F72() -> set , P31 , P32[set , set] , F73 , F74(set , set) -> set } : (ex B81 being (PartFunc of [: F70() , F71() :] , F72()) st ((for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in ( dom B81 ) iff (R1 in F70() & R2 in F71() & (P31[ R1 , R2 ] or P32[ R1 , R2 ]))))) & (for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in ( dom B81 ) implies ((P31[ R1 , R2 ] implies ( B81 . [ R1 , R2 ] ) = F73(R1 , R2)) & (P32[ R1 , R2 ] implies ( B81 . [ R1 , R2 ] ) = F74(R1 , R2))))))))
provided
L929: (for R1 being set holds (for R2 being set holds ((R1 in F70() & R2 in F71()) implies (P31[ R1 , R2 ] implies (not P32[ R1 , R2 ])))))
and
L930: (for R1 being set holds (for R2 being set holds ((R1 in F70() & R2 in F71() & P31[ R1 , R2 ]) implies F73(R1 , R2) in F72())))
and
L931: (for R1 being set holds (for R2 being set holds ((R1 in F70() & R2 in F71() & P32[ R1 , R2 ]) implies F74(R1 , R2) in F72())))
proof
defpred S47[ set , set ] means (for R1 being set holds (for R2 being set holds ($1 = [ R1 , R2 ] implies ((P31[ R1 , R2 ] implies $2 = F73(R1 , R2)) & (P32[ R1 , R2 ] implies $2 = F74(R1 , R2))))));
defpred S48[ set ] means (for R1 being set holds (for R2 being set holds ($1 = [ R1 , R2 ] implies (P31[ R1 , R2 ] or P32[ R1 , R2 ]))));
consider C81 being set such that L932: (for R3 being set holds (R3 in C81 iff (R3 in [: F70() , F71() :] & S48[ R3 ]))) from XBOOLE_0:sch 1;
L933: (for B82 being set holds (B82 in C81 implies (ex R3 being set st S47[ B82 , R3 ])))
proof
let C82 being set;
assume L934: C82 in C81;
L935: C82 in [: F70() , F71() :] by L934 , L932;
consider C83 , C84 being set such that L936: (C83 in F70() & C84 in F71()) and L937: C82 = [ C83 , C84 ] by L935 , ZFMISC_1:def 2;
L938:
now
per cases  by L932 , L934 , L937;
suppose L939: P31[ C83 , C84 ];

take D80 = F73(C83 , C84);
let R1 being set;
let R2 being set;
assume L940: C82 = [ R1 , R2 ];
L941: (C83 = R1 & C84 = R2) by L940 , L937 , XTUPLE_0:1;
thus L942: ((P31[ R1 , R2 ] implies D80 = F73(R1 , R2)) & (P32[ R1 , R2 ] implies D80 = F74(R1 , R2))) by L941 , L929 , L936 , L939;
end;
suppose L943: P32[ C83 , C84 ];

take D81 = F74(C83 , C84);
let R1 being set;
let R2 being set;
assume L944: C82 = [ R1 , R2 ];
L945: (C83 = R1 & C84 = R2) by L944 , L937 , XTUPLE_0:1;
thus L946: ((P31[ R1 , R2 ] implies D81 = F73(R1 , R2)) & (P32[ R1 , R2 ] implies D81 = F74(R1 , R2))) by L945 , L929 , L936 , L943;
end;
end;
thus L948: thesis by L938;
end;
consider C85 being Function such that L949: (( dom C85 ) = C81 & (for R3 being set holds (R3 in C81 implies S47[ R3 , ( C85 . R3 ) ]))) from CLASSES1:sch 1(L933);
L950: ( rng C85 ) c= F72()
proof
let R3 being set;
assume L951: R3 in ( rng C85 );
consider C86 being set such that L952: C86 in ( dom C85 ) and L953: R3 = ( C85 . C86 ) by L951 , FUNCT_1:def 3;
L954: C86 in [: F70() , F71() :] by L932 , L949 , L952;
consider R1 being set, R2 being set such that L955: (R1 in F70() & R2 in F71()) and L956: C86 = [ R1 , R2 ] by L954 , ZFMISC_1:def 2;
L957:
now
per cases  by L932 , L949 , L952 , L956;
suppose L958: P31[ R1 , R2 ];

L959: ( C85 . [ R1 , R2 ] ) = F73(R1 , R2) by L958 , L949 , L952 , L956;
thus L960: thesis by L959 , L930 , L953 , L955 , L956 , L958;
end;
suppose L961: P32[ R1 , R2 ];

L962: ( C85 . [ R1 , R2 ] ) = F74(R1 , R2) by L961 , L949 , L952 , L956;
thus L963: thesis by L962 , L931 , L953 , L955 , L956 , L961;
end;
end;
thus L965: thesis by L957;
end;
L966: C81 c= [: F70() , F71() :]
proof
let R3 being set;
assume L967: R3 in C81;
thus L968: thesis by L967 , L932;
end;
reconsider D82 = C85 as (PartFunc of [: F70() , F71() :] , F72()) by L966 , L949 , L950 , RELSET_1:4;
take D82;
thus L969: (for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in ( dom D82 ) iff (R1 in F70() & R2 in F71() & (P31[ R1 , R2 ] or P32[ R1 , R2 ])))))
proof
let R1 being set;
let R2 being set;
thus L970: ([ R1 , R2 ] in ( dom D82 ) implies (R1 in F70() & R2 in F71() & (P31[ R1 , R2 ] or P32[ R1 , R2 ]))) by L932 , L949 , ZFMISC_1:87;
assume that
L971: (R1 in F70() & R2 in F71())
and
L972: (P31[ R1 , R2 ] or P32[ R1 , R2 ]);
L973:
now
let C87 , C88 being set;
assume L974: [ R1 , R2 ] = [ C87 , C88 ];
L975: R1 = C87 by L974 , XTUPLE_0:1;
thus L976: (P31[ C87 , C88 ] or P32[ C87 , C88 ]) by L975 , L972 , L974 , XTUPLE_0:1;
end;
L977: [ R1 , R2 ] in [: F70() , F71() :] by L971 , ZFMISC_1:87;
thus L978: thesis by L977 , L932 , L949 , L973;
end;

let R1 being set;
let R2 being set;
assume L979: [ R1 , R2 ] in ( dom D82 );
thus L980: thesis by L979 , L949;
end;
scheme PartFuncExCS3 { F75 , F76 , F77() -> set , P33 , P34 , P35[set , set] , F78 , F79 , F80(set , set) -> set } : (ex B83 being (PartFunc of [: F75() , F76() :] , F77()) st ((for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in ( dom B83 ) iff (R1 in F75() & R2 in F76() & (P33[ R1 , R2 ] or P34[ R1 , R2 ] or P35[ R1 , R2 ]))))) & (for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in ( dom B83 ) implies ((P33[ R1 , R2 ] implies ( B83 . [ R1 , R2 ] ) = F78(R1 , R2)) & (P34[ R1 , R2 ] implies ( B83 . [ R1 , R2 ] ) = F79(R1 , R2)) & (P35[ R1 , R2 ] implies ( B83 . [ R1 , R2 ] ) = F80(R1 , R2))))))))
provided
L981: (for R1 being set holds (for R2 being set holds ((R1 in F75() & R2 in F76()) implies ((P33[ R1 , R2 ] implies (not P34[ R1 , R2 ])) & (P33[ R1 , R2 ] implies (not P35[ R1 , R2 ])) & (P34[ R1 , R2 ] implies (not P35[ R1 , R2 ]))))))
and
L982: (for R1 being set holds (for R2 being set holds ((R1 in F75() & R2 in F76()) implies (P33[ R1 , R2 ] implies F78(R1 , R2) in F77()))))
and
L983: (for R1 being set holds (for R2 being set holds ((R1 in F75() & R2 in F76()) implies (P34[ R1 , R2 ] implies F79(R1 , R2) in F77()))))
and
L984: (for R1 being set holds (for R2 being set holds ((R1 in F75() & R2 in F76()) implies (P35[ R1 , R2 ] implies F80(R1 , R2) in F77()))))
proof
defpred S49[ set , set ] means (for R1 being set holds (for R2 being set holds ($1 = [ R1 , R2 ] implies ((P33[ R1 , R2 ] implies $2 = F78(R1 , R2)) & (P34[ R1 , R2 ] implies $2 = F79(R1 , R2)) & (P35[ R1 , R2 ] implies $2 = F80(R1 , R2))))));
defpred S50[ set ] means (for R1 being set holds (for R2 being set holds ($1 = [ R1 , R2 ] implies (P33[ R1 , R2 ] or P34[ R1 , R2 ] or P35[ R1 , R2 ]))));
consider C89 being set such that L985: (for R3 being set holds (R3 in C89 iff (R3 in [: F75() , F76() :] & S50[ R3 ]))) from XBOOLE_0:sch 1;
L986: (for B84 being set holds (B84 in C89 implies (ex R3 being set st S49[ B84 , R3 ])))
proof
let C90 being set;
assume L987: C90 in C89;
L988: C90 in [: F75() , F76() :] by L987 , L985;
consider C91 , C92 being set such that L989: (C91 in F75() & C92 in F76()) and L990: C90 = [ C91 , C92 ] by L988 , ZFMISC_1:def 2;
L991:
now
per cases  by L985 , L987 , L990;
suppose L992: P33[ C91 , C92 ];

take D83 = F78(C91 , C92);
let R1 being set;
let R2 being set;
assume L993: C90 = [ R1 , R2 ];
L994: (C91 = R1 & C92 = R2) by L993 , L990 , XTUPLE_0:1;
thus L995: ((P33[ R1 , R2 ] implies D83 = F78(R1 , R2)) & (P34[ R1 , R2 ] implies D83 = F79(R1 , R2)) & (P35[ R1 , R2 ] implies D83 = F80(R1 , R2))) by L994 , L981 , L989 , L992;
end;
suppose L996: P34[ C91 , C92 ];

take D84 = F79(C91 , C92);
let R1 being set;
let R2 being set;
assume L997: C90 = [ R1 , R2 ];
L998: (C91 = R1 & C92 = R2) by L997 , L990 , XTUPLE_0:1;
thus L999: ((P33[ R1 , R2 ] implies D84 = F78(R1 , R2)) & (P34[ R1 , R2 ] implies D84 = F79(R1 , R2)) & (P35[ R1 , R2 ] implies D84 = F80(R1 , R2))) by L998 , L981 , L989 , L996;
end;
suppose L1000: P35[ C91 , C92 ];

take D85 = F80(C91 , C92);
let R1 being set;
let R2 being set;
assume L1001: C90 = [ R1 , R2 ];
L1002: (C91 = R1 & C92 = R2) by L1001 , L990 , XTUPLE_0:1;
thus L1003: ((P33[ R1 , R2 ] implies D85 = F78(R1 , R2)) & (P34[ R1 , R2 ] implies D85 = F79(R1 , R2)) & (P35[ R1 , R2 ] implies D85 = F80(R1 , R2))) by L1002 , L981 , L989 , L1000;
end;
end;
thus L1005: thesis by L991;
end;
consider C93 being Function such that L1006: (( dom C93 ) = C89 & (for R3 being set holds (R3 in C89 implies S49[ R3 , ( C93 . R3 ) ]))) from CLASSES1:sch 1(L986);
L1007: ( rng C93 ) c= F77()
proof
let R3 being set;
assume L1008: R3 in ( rng C93 );
consider C94 being set such that L1009: C94 in ( dom C93 ) and L1010: R3 = ( C93 . C94 ) by L1008 , FUNCT_1:def 3;
L1011: C94 in [: F75() , F76() :] by L985 , L1006 , L1009;
consider R1 being set, R2 being set such that L1012: (R1 in F75() & R2 in F76()) and L1013: C94 = [ R1 , R2 ] by L1011 , ZFMISC_1:def 2;
L1014:
now
per cases  by L985 , L1006 , L1009 , L1013;
suppose L1015: P33[ R1 , R2 ];

L1016: ( C93 . [ R1 , R2 ] ) = F78(R1 , R2) by L1015 , L1006 , L1009 , L1013;
thus L1017: thesis by L1016 , L982 , L1010 , L1012 , L1013 , L1015;
end;
suppose L1018: P34[ R1 , R2 ];

L1019: ( C93 . [ R1 , R2 ] ) = F79(R1 , R2) by L1018 , L1006 , L1009 , L1013;
thus L1020: thesis by L1019 , L983 , L1010 , L1012 , L1013 , L1018;
end;
suppose L1021: P35[ R1 , R2 ];

L1022: ( C93 . [ R1 , R2 ] ) = F80(R1 , R2) by L1021 , L1006 , L1009 , L1013;
thus L1023: thesis by L1022 , L984 , L1010 , L1012 , L1013 , L1021;
end;
end;
thus L1025: thesis by L1014;
end;
L1026: C89 c= [: F75() , F76() :]
proof
let R3 being set;
assume L1027: R3 in C89;
thus L1028: thesis by L1027 , L985;
end;
reconsider D86 = C93 as (PartFunc of [: F75() , F76() :] , F77()) by L1026 , L1006 , L1007 , RELSET_1:4;
take D86;
thus L1029: (for R1 being set holds (for R2 being set holds ([ R1 , R2 ] in ( dom D86 ) iff (R1 in F75() & R2 in F76() & (P33[ R1 , R2 ] or P34[ R1 , R2 ] or P35[ R1 , R2 ])))))
proof
let R1 being set;
let R2 being set;
thus L1030: ([ R1 , R2 ] in ( dom D86 ) implies (R1 in F75() & R2 in F76() & (P33[ R1 , R2 ] or P34[ R1 , R2 ] or P35[ R1 , R2 ]))) by L985 , L1006 , ZFMISC_1:87;
assume that
L1031: (R1 in F75() & R2 in F76())
and
L1032: (P33[ R1 , R2 ] or P34[ R1 , R2 ] or P35[ R1 , R2 ]);
L1033:
now
let C95 , C96 being set;
assume L1034: [ R1 , R2 ] = [ C95 , C96 ];
L1035: R1 = C95 by L1034 , XTUPLE_0:1;
thus L1036: (P33[ C95 , C96 ] or P34[ C95 , C96 ] or P35[ C95 , C96 ]) by L1035 , L1032 , L1034 , XTUPLE_0:1;
end;
L1037: [ R1 , R2 ] in [: F75() , F76() :] by L1031 , ZFMISC_1:87;
thus L1038: thesis by L1037 , L985 , L1006 , L1033;
end;

let R1 being set;
let R2 being set;
assume L1039: [ R1 , R2 ] in ( dom D86 );
thus L1040: thesis by L1039 , L1006;
end;
scheme ExFuncD3 { F81 , F82() -> non  empty set , P36 , P37 , P38[set] , F83 , F84 , F85(set) -> (Element of F82()) } : (ex B85 being (Function of F81() , F82()) st (for B86 being (Element of F81()) holds ((P36[ B86 ] implies ( B85 . B86 ) = F83(B86)) & (P37[ B86 ] implies ( B85 . B86 ) = F84(B86)) & (P38[ B86 ] implies ( B85 . B86 ) = F85(B86)))))
provided
L1041: (for B87 being (Element of F81()) holds ((P36[ B87 ] implies (not P37[ B87 ])) & (P36[ B87 ] implies (not P38[ B87 ])) & (P37[ B87 ] implies (not P38[ B87 ]))))
and
L1042: (for B88 being (Element of F81()) holds (P36[ B88 ] or P37[ B88 ] or P38[ B88 ]))
proof
L1043: (for B89 being (Element of F81()) holds ((P36[ B89 ] implies (not P37[ B89 ])) & (P36[ B89 ] implies (not P38[ B89 ])) & (P37[ B89 ] implies (not P38[ B89 ])))) by L1041;
consider C97 being (PartFunc of F81() , F82()) such that L1044: (for B90 being (Element of F81()) holds (B90 in ( dom C97 ) iff (P36[ B90 ] or P37[ B90 ] or P38[ B90 ]))) and L1045: (for B91 being (Element of F81()) holds (B91 in ( dom C97 ) implies ((P36[ B91 ] implies ( C97 . B91 ) = F83(B91)) & (P37[ B91 ] implies ( C97 . B91 ) = F84(B91)) & (P38[ B91 ] implies ( C97 . B91 ) = F85(B91))))) from PartFuncExD3(L1043);
set D87 = C97;
L1046: ( dom D87 ) = F81()
proof
thus L1047: ( dom D87 ) c= F81();
let R1 being set;
assume L1048: R1 in F81();
reconsider D88 = R1 as (Element of F81()) by L1048;
L1049: (P36[ D88 ] or P37[ D88 ] or P38[ D88 ]) by L1042;
thus L1050: thesis by L1049 , L1044;
end;
reconsider D89 = D87 as (Function of F81() , F82()) by L1046 , FUNCT_2:def 1;
take D89;
let C98 being (Element of F81());
thus L1051: thesis by L1045 , L1046;
end;
scheme ExFuncD4 { F86 , F87() -> non  empty set , P39 , P40 , P41 , P42[set] , F88 , F89 , F90 , F91(set) -> (Element of F87()) } : (ex B92 being (Function of F86() , F87()) st (for B93 being (Element of F86()) holds ((P39[ B93 ] implies ( B92 . B93 ) = F88(B93)) & (P40[ B93 ] implies ( B92 . B93 ) = F89(B93)) & (P41[ B93 ] implies ( B92 . B93 ) = F90(B93)) & (P42[ B93 ] implies ( B92 . B93 ) = F91(B93)))))
provided
L1052: (for B94 being (Element of F86()) holds ((P39[ B94 ] implies (not P40[ B94 ])) & (P39[ B94 ] implies (not P41[ B94 ])) & (P39[ B94 ] implies (not P42[ B94 ])) & (P40[ B94 ] implies (not P41[ B94 ])) & (P40[ B94 ] implies (not P42[ B94 ])) & (P41[ B94 ] implies (not P42[ B94 ]))))
and
L1053: (for B95 being (Element of F86()) holds (P39[ B95 ] or P40[ B95 ] or P41[ B95 ] or P42[ B95 ]))
proof
L1054: (for B96 being (Element of F86()) holds ((P39[ B96 ] implies (not P40[ B96 ])) & (P39[ B96 ] implies (not P41[ B96 ])) & (P39[ B96 ] implies (not P42[ B96 ])) & (P40[ B96 ] implies (not P41[ B96 ])) & (P40[ B96 ] implies (not P42[ B96 ])) & (P41[ B96 ] implies (not P42[ B96 ])))) by L1052;
consider C99 being (PartFunc of F86() , F87()) such that L1055: (for B97 being (Element of F86()) holds (B97 in ( dom C99 ) iff (P39[ B97 ] or P40[ B97 ] or P41[ B97 ] or P42[ B97 ]))) and L1056: (for B98 being (Element of F86()) holds (B98 in ( dom C99 ) implies ((P39[ B98 ] implies ( C99 . B98 ) = F88(B98)) & (P40[ B98 ] implies ( C99 . B98 ) = F89(B98)) & (P41[ B98 ] implies ( C99 . B98 ) = F90(B98)) & (P42[ B98 ] implies ( C99 . B98 ) = F91(B98))))) from PartFuncExD4(L1054);
set D90 = C99;
L1057: ( dom D90 ) = F86()
proof
thus L1058: ( dom D90 ) c= F86();
let R1 being set;
assume L1059: R1 in F86();
reconsider D91 = R1 as (Element of F86()) by L1059;
L1060: (P39[ D91 ] or P40[ D91 ] or P41[ D91 ] or P42[ D91 ]) by L1053;
thus L1061: thesis by L1060 , L1055;
end;
reconsider D92 = D90 as (Function of F86() , F87()) by L1057 , FUNCT_2:def 1;
take D92;
let C100 being (Element of F86());
thus L1062: thesis by L1056 , L1057;
end;
scheme FuncExCD2 { F92 , F93 , F94() -> non  empty set , P43[set , set] , F95 , F96(set , set) -> (Element of F94()) } : (ex B99 being (Function of [: F92() , F93() :] , F94()) st (for B100 being (Element of F92()) holds (for B101 being (Element of F93()) holds ([ B100 , B101 ] in ( dom B99 ) implies ((P43[ B100 , B101 ] implies ( B99 . [ B100 , B101 ] ) = F95(B100 , B101)) & ((not P43[ B100 , B101 ]) implies ( B99 . [ B100 , B101 ] ) = F96(B100 , B101)))))))
proof
defpred S51[ set , set ] means (not P43[ $1 , $2 ]);
L1063: (for B102 being (Element of F92()) holds (for B103 being (Element of F93()) holds (P43[ B102 , B103 ] implies (not S51[ B102 , B103 ]))));
consider C101 being (PartFunc of [: F92() , F93() :] , F94()) such that L1064: ((for B104 being (Element of F92()) holds (for B105 being (Element of F93()) holds ([ B104 , B105 ] in ( dom C101 ) iff (P43[ B104 , B105 ] or S51[ B104 , B105 ])))) & (for B106 being (Element of F92()) holds (for B107 being (Element of F93()) holds ([ B106 , B107 ] in ( dom C101 ) implies ((P43[ B106 , B107 ] implies ( C101 . [ B106 , B107 ] ) = F95(B106 , B107)) & (S51[ B106 , B107 ] implies ( C101 . [ B106 , B107 ] ) = F96(B106 , B107))))))) from PartFuncExCD2(L1063);
consider C102 being Function such that L1065: C102 = C101;
L1066: ( dom C101 ) = [: F92() , F93() :]
proof
thus L1067: ( dom C101 ) c= [: F92() , F93() :];
let R1 being set;
assume L1068: R1 in [: F92() , F93() :];
consider R2 being set, R3 being set such that L1069: R2 in F92() and L1070: R3 in F93() and L1071: R1 = [ R2 , R3 ] by L1068 , ZFMISC_1:def 2;
reconsider D93 = R3 as (Element of F93()) by L1070;
reconsider D94 = R2 as (Element of F92()) by L1069;
L1072: (P43[ D94 , D93 ] or (not P43[ D94 , D93 ]));
thus L1073: thesis by L1072 , L1064 , L1071;
end;
reconsider D95 = C102 as (Function of [: F92() , F93() :] , F94()) by L1066 , L1065 , FUNCT_2:def 1;
take D95;
thus L1074: thesis by L1064 , L1065;
end;
scheme FuncExCD3 { F97 , F98 , F99() -> non  empty set , P44 , P45 , P46[set , set] , F100 , F101 , F102(set , set) -> (Element of F99()) } : (ex B108 being (Function of [: F97() , F98() :] , F99()) st ((for B109 being (Element of F97()) holds (for B110 being (Element of F98()) holds ([ B109 , B110 ] in ( dom B108 ) iff (P44[ B109 , B110 ] or P45[ B109 , B110 ] or P46[ B109 , B110 ])))) & (for B111 being (Element of F97()) holds (for B112 being (Element of F98()) holds ([ B111 , B112 ] in ( dom B108 ) implies ((P44[ B111 , B112 ] implies ( B108 . [ B111 , B112 ] ) = F100(B111 , B112)) & (P45[ B111 , B112 ] implies ( B108 . [ B111 , B112 ] ) = F101(B111 , B112)) & (P46[ B111 , B112 ] implies ( B108 . [ B111 , B112 ] ) = F102(B111 , B112))))))))
provided
L1075: (for B113 being (Element of F97()) holds (for B114 being (Element of F98()) holds ((P44[ B113 , B114 ] implies (not P45[ B113 , B114 ])) & (P44[ B113 , B114 ] implies (not P46[ B113 , B114 ])) & (P45[ B113 , B114 ] implies (not P46[ B113 , B114 ])))))
and
L1076: (for B115 being (Element of F97()) holds (for B116 being (Element of F98()) holds (P44[ B115 , B116 ] or P45[ B115 , B116 ] or P46[ B115 , B116 ])))
proof
L1077: (for B117 being (Element of F97()) holds (for B118 being (Element of F98()) holds ((P44[ B117 , B118 ] implies (not P45[ B117 , B118 ])) & (P44[ B117 , B118 ] implies (not P46[ B117 , B118 ])) & (P45[ B117 , B118 ] implies (not P46[ B117 , B118 ]))))) by L1075;
consider C103 being (PartFunc of [: F97() , F98() :] , F99()) such that L1078: ((for B119 being (Element of F97()) holds (for B120 being (Element of F98()) holds ([ B119 , B120 ] in ( dom C103 ) iff (P44[ B119 , B120 ] or P45[ B119 , B120 ] or P46[ B119 , B120 ])))) & (for B121 being (Element of F97()) holds (for B122 being (Element of F98()) holds ([ B121 , B122 ] in ( dom C103 ) implies ((P44[ B121 , B122 ] implies ( C103 . [ B121 , B122 ] ) = F100(B121 , B122)) & (P45[ B121 , B122 ] implies ( C103 . [ B121 , B122 ] ) = F101(B121 , B122)) & (P46[ B121 , B122 ] implies ( C103 . [ B121 , B122 ] ) = F102(B121 , B122))))))) from PartFuncExCD3(L1077);
consider C104 being Function such that L1079: C104 = C103;
L1080: ( dom C103 ) = [: F97() , F98() :]
proof
thus L1081: ( dom C103 ) c= [: F97() , F98() :];
let R1 being set;
assume L1082: R1 in [: F97() , F98() :];
consider R2 being set, R3 being set such that L1083: R2 in F97() and L1084: R3 in F98() and L1085: R1 = [ R2 , R3 ] by L1082 , ZFMISC_1:def 2;
reconsider D96 = R3 as (Element of F98()) by L1084;
reconsider D97 = R2 as (Element of F97()) by L1083;
L1086: (P44[ D97 , D96 ] or P45[ D97 , D96 ] or P46[ D97 , D96 ]) by L1076;
thus L1087: thesis by L1086 , L1078 , L1085;
end;
reconsider D98 = C104 as (Function of [: F97() , F98() :] , F99()) by L1080 , L1079 , FUNCT_2:def 1;
take D98;
thus L1088: thesis by L1078 , L1079;
end;
