:: Inverse Trigonometric Functions Arcsin and Arccos
::  by Artur Korni{\l}owicz and Yasunari Shidama
::
:: Received September 25, 2004
:: Copyright (c) 2004-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, XREAL_0, ORDINAL1, INT_1, CARD_1, XXREAL_0, ARYTM_3,
      ARYTM_1, FUNCT_1, RELAT_1, TARSKI, XBOOLE_0, SIN_COS, XXREAL_1, SQUARE_1,
      REAL_1, ORDINAL2, SUBSET_1, VALUED_0, PARTFUN1, FDIFF_1, SIN_COS6;
 notations TARSKI, XBOOLE_0, SUBSET_1, ORDINAL1, NUMBERS, XCMPLX_0, XXREAL_0,
      XREAL_0, REAL_1, INT_1, SQUARE_1, RCOMP_1, RELAT_1, FUNCT_1, PARTFUN1,
      RELSET_1, SEQ_1, PARTFUN2, RFUNCT_2, FCONT_1, FDIFF_1, SIN_COS;
 constructors PARTFUN1, ARYTM_0, REAL_1, SQUARE_1, RCOMP_1, PARTFUN2, RFUNCT_2,
      FCONT_1, FDIFF_1, COMSEQ_3, SIN_COS, SEQ_1, RVSUM_1, RELSET_1;
 registrations FUNCT_1, RELSET_1, XCMPLX_0, XXREAL_0, XREAL_0, SQUARE_1, INT_1,
      MEMBERED, RCOMP_1, RFUNCT_2, SIN_COS, XBOOLE_0, VALUED_0;
 requirements BOOLE, SUBSET, NUMERALS, ARITHM, REAL;
 definitions TARSKI, XBOOLE_0, FUNCT_1, RFUNCT_2, XXREAL_0, SQUARE_1;
 theorems RELAT_1, SIN_COS, FUNCT_1, COMPTRIG, FDIFF_1, FDIFF_2, RFUNCT_2,
      XCMPLX_1, INT_1, XBOOLE_0, SQUARE_1, COMPLEX2, FCONT_3, FCONT_1, XREAL_1,
      XXREAL_0, XXREAL_1, XBOOLE_1;
 schemes INT_1;

begin
theorem
L1: (for R1 being  real number holds (for R2 being  real number holds ((( 0 ) <= R1 & R1 < R2) implies [\ ( R1 / R2 ) /] = ( 0 ))))
proof
let R1 being  real number;
let R2 being  real number;
assume L2: (( 0 ) <= R1 & R1 < R2);
L3: ( R1 / R2 ) < ( R2 / R2 ) by L2 , XREAL_1:74;
L4: ( ( R1 / R2 ) - 1 ) < ( ( R2 / R2 ) - 1 ) by L3 , XREAL_1:9;
L5: ( ( R1 / R2 ) - 1 ) < ( 1 - 1 ) by L4 , L2 , XCMPLX_1:60;
thus L6: thesis by L5 , L2 , INT_1:def 6;
end;
theorem
L7: (for B1 being Function holds (for B2 , B3 being set holds ((( B1 | B2 ) is  one-to-one & B3 c= B2) implies ( B1 | B3 ) is  one-to-one)))
proof
let C1 being Function;
let C2 , C3 being set;
assume that
L8: ( C1 | C2 ) is  one-to-one
and
L9: C3 c= C2;
let C4 , C5 being set;
L10: ( dom ( C1 | C3 ) ) = ( ( dom C1 ) /\ C3 ) by RELAT_1:61;
assume L11: C4 in ( dom ( C1 | C3 ) );
L12: C4 in C3 by L11 , L10 , XBOOLE_0:def 4;
L13: C4 in ( dom C1 ) by L10 , L11 , XBOOLE_0:def 4;
L14: C4 in ( ( dom C1 ) /\ C2 ) by L13 , L9 , L12 , XBOOLE_0:def 4;
L15: C4 in ( dom ( C1 | C2 ) ) by L14 , RELAT_1:61;
assume L16: C5 in ( dom ( C1 | C3 ) );
L17: C5 in C3 by L16 , L10 , XBOOLE_0:def 4;
L18: C5 in ( dom C1 ) by L10 , L16 , XBOOLE_0:def 4;
L19: C5 in ( ( dom C1 ) /\ C2 ) by L18 , L9 , L17 , XBOOLE_0:def 4;
L20: C5 in ( dom ( C1 | C2 ) ) by L19 , RELAT_1:61;
assume L21: ( ( C1 | C3 ) . C4 ) = ( ( C1 | C3 ) . C5 );
L22: ( ( C1 | C2 ) . C4 ) = ( C1 . C4 ) by L9 , L12 , FUNCT_1:49
.= ( ( C1 | C3 ) . C4 ) by L12 , FUNCT_1:49
.= ( C1 . C5 ) by L17 , L21 , FUNCT_1:49
.= ( ( C1 | C2 ) . C5 ) by L9 , L17 , FUNCT_1:49;
thus L23: thesis by L22 , L8 , L15 , L20 , FUNCT_1:def 4;
end;
begin
theorem
L24: (for R1 being  real number holds ( - 1 ) <= ( sin R1 ))
proof
let R1 being  real number;
L25: ( ( sin ) . R1 ) in [. ( - 1 ) , 1 .] by COMPTRIG:27;
L26: ( sin R1 ) in [. ( - 1 ) , 1 .] by L25 , SIN_COS:def 17;
thus L27: thesis by L26 , XXREAL_1:1;
end;
theorem
L28: (for R1 being  real number holds ( sin R1 ) <= 1)
proof
let R1 being  real number;
L29: ( ( sin ) . R1 ) in [. ( - 1 ) , 1 .] by COMPTRIG:27;
L30: ( sin R1 ) in [. ( - 1 ) , 1 .] by L29 , SIN_COS:def 17;
thus L31: thesis by L30 , XXREAL_1:1;
end;
theorem
L32: (for R1 being  real number holds ( - 1 ) <= ( cos R1 ))
proof
let R1 being  real number;
L33: ( ( cos ) . R1 ) in [. ( - 1 ) , 1 .] by COMPTRIG:27;
L34: ( cos R1 ) in [. ( - 1 ) , 1 .] by L33 , SIN_COS:def 19;
thus L35: thesis by L34 , XXREAL_1:1;
end;
theorem
L36: (for R1 being  real number holds ( cos R1 ) <= 1)
proof
let R1 being  real number;
L37: ( ( cos ) . R1 ) in [. ( - 1 ) , 1 .] by COMPTRIG:27;
L38: ( cos R1 ) in [. ( - 1 ) , 1 .] by L37 , SIN_COS:def 19;
thus L39: thesis by L38 , XXREAL_1:1;
end;
deffunc H1(Integer) = ( ( 2 * ( PI ) ) * $1 );
L40: [. ( ( - ( ( PI ) / 2 ) ) + H1(( 0 )) ) , ( ( ( PI ) / 2 ) + H1(( 0 )) ) .] = [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .];
L41: [. ( ( ( PI ) / 2 ) + H1(( 0 )) ) , ( ( ( 3 / 2 ) * ( PI ) ) + H1(( 0 )) ) .] = [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .];
L42: [. H1(( 0 )) , ( ( PI ) + H1(( 0 )) ) .] = [. ( 0 ) , ( PI ) .];
L43: [. ( ( PI ) + H1(( 0 )) ) , ( ( 2 * ( PI ) ) + H1(( 0 )) ) .] = [. ( PI ) , ( 2 * ( PI ) ) .];
L44: (for R1 being  real number holds (for R2 being  real number holds (( ( R1 ^2 ) + ( R2 ^2 ) ) = 1 implies (( - 1 ) <= R1 & R1 <= 1))))
proof
let R1 being  real number;
let R2 being  real number;
L45: ( R2 ^2 ) >= ( 0 ) by XREAL_1:63;
L46: ( - ( R2 ^2 ) ) <= ( - ( 0 ) ) by L45;
L47: ( ( R1 ^2 ) - ( ( R1 ^2 ) + ( R2 ^2 ) ) ) <= ( 0 ) by L46;
thus L48: thesis by L47 , SQUARE_1:43;
end;
registration
cluster ( PI ) ->  positive;
coherence
proof
L49: ( PI ) in ]. ( 0 ) , 4 .[ by SIN_COS:def 28;
thus L50: ( PI ) > ( 0 ) by L49 , XXREAL_1:4;
end;
end;
L52: ( ( PI ) / 2 ) < ( ( PI ) / 1 ) by XREAL_1:76;
L53: ( 1 * ( PI ) ) < ( ( 3 / 2 ) * ( PI ) ) by XREAL_1:68;
L54: ( ( 0 ) + H1(1) ) < ( ( ( PI ) / 2 ) + H1(1) ) by XREAL_1:6;
L55: ( ( 3 / 2 ) * ( PI ) ) < ( 2 * ( PI ) ) by XREAL_1:68;
L56: ( 1 * ( PI ) ) < ( 2 * ( PI ) ) by XREAL_1:68;
theorem
L57: (( sin ( - ( ( PI ) / 2 ) ) ) = ( - 1 ) & ( ( sin ) . ( - ( ( PI ) / 2 ) ) ) = ( - 1 ))
proof
L58: ( ( sin ) . ( - ( ( PI ) / 2 ) ) ) = ( ( sin ) . ( ( - ( ( PI ) / 2 ) ) + ( 2 * ( PI ) ) ) ) by SIN_COS:78
.= ( - 1 ) by SIN_COS:76;
thus L59: thesis by L58 , SIN_COS:def 17;
end;
theorem
L60: (for R1 being  real number holds (for R3 being  integer number holds ( ( sin ) . R1 ) = ( ( sin ) . ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) )))
proof
let R1 being  real number;
let R3 being  integer number;
thus L61: ( ( sin ) . R1 ) = ( sin R1 ) by SIN_COS:def 17
.= ( sin ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) ) by COMPLEX2:8
.= ( ( sin ) . ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) ) by SIN_COS:def 17;
end;
theorem
L62: (( cos ( - ( ( PI ) / 2 ) ) ) = ( 0 ) & ( ( cos ) . ( - ( ( PI ) / 2 ) ) ) = ( 0 ))
proof
L63: ( ( cos ) . ( - ( ( PI ) / 2 ) ) ) = ( ( cos ) . ( ( - ( ( PI ) / 2 ) ) + ( 2 * ( PI ) ) ) ) by SIN_COS:78
.= ( 0 ) by SIN_COS:76;
thus L64: thesis by L63 , SIN_COS:def 19;
end;
theorem
L65: (for R1 being  real number holds (for R3 being  integer number holds ( ( cos ) . R1 ) = ( ( cos ) . ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) )))
proof
let R1 being  real number;
let R3 being  integer number;
thus L66: ( ( cos ) . R1 ) = ( cos R1 ) by SIN_COS:def 19
.= ( cos ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) ) by COMPLEX2:9
.= ( ( cos ) . ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) ) by SIN_COS:def 19;
end;
theorem
L67: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) < R1 & R1 < ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) > ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L68: (H1(R3) < R1 & R1 < ( ( PI ) + H1(R3) ));
L69: (( H1(R3) - H1(R3) ) < ( R1 - H1(R3) ) & ( R1 - H1(R3) ) < ( ( ( PI ) + H1(R3) ) - H1(R3) )) by L68 , XREAL_1:9;
L70: ( R1 - H1(R3) ) in ]. ( 0 ) , ( PI ) .[ by L69 , XXREAL_1:4;
L71: ( ( sin ) . ( R1 + H1(( - R3 )) ) ) > ( 0 ) by L70 , COMPTRIG:7;
L72: ( ( sin ) . R1 ) > ( 0 ) by L71 , L60;
thus L73: thesis by L72 , SIN_COS:def 17;
end;
theorem
L74: (for R1 being  real number holds (for R3 being  integer number holds ((( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) < ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L75: (( ( PI ) + H1(R3) ) < R1 & R1 < ( ( 2 * ( PI ) ) + H1(R3) ));
L76: (( ( ( PI ) + H1(R3) ) - H1(R3) ) < ( R1 - H1(R3) ) & ( R1 - H1(R3) ) < ( ( ( 2 * ( PI ) ) + H1(R3) ) - H1(R3) )) by L75 , XREAL_1:9;
L77: ( R1 - H1(R3) ) in ]. ( PI ) , ( 2 * ( PI ) ) .[ by L76 , XXREAL_1:4;
L78: ( ( sin ) . ( R1 + H1(( - R3 )) ) ) < ( 0 ) by L77 , COMPTRIG:9;
L79: ( ( sin ) . R1 ) < ( 0 ) by L78 , L60;
thus L80: thesis by L79 , SIN_COS:def 17;
end;
theorem
L81: (for R1 being  real number holds (for R3 being  integer number holds ((( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) > ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L82: ( ( - ( ( PI ) / 2 ) ) + H1(R3) ) < R1
and
L83: R1 < ( ( ( PI ) / 2 ) + H1(R3) );
L84: ( R1 + ( ( PI ) / 2 ) ) < ( ( ( ( PI ) / 2 ) + H1(R3) ) + ( ( PI ) / 2 ) ) by L83 , XREAL_1:6;
L85: ( R1 + ( ( PI ) / 2 ) ) < ( ( PI ) + H1(R3) ) by L84;
L86: ( sin ( R1 + ( ( PI ) / 2 ) ) ) = ( cos R1 ) by SIN_COS:79;
L87: ( ( ( - ( ( PI ) / 2 ) ) + H1(R3) ) + ( ( PI ) / 2 ) ) < ( R1 + ( ( PI ) / 2 ) ) by L82 , XREAL_1:6;
thus L88: thesis by L87 , L85 , L86 , L67;
end;
theorem
L89: (for R1 being  real number holds (for R3 being  integer number holds ((( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) < ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L90: ( ( ( PI ) / 2 ) + H1(R3) ) < R1
and
L91: R1 < ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) );
L92: ( ( ( ( PI ) / 2 ) + H1(R3) ) + ( ( PI ) / 2 ) ) < ( R1 + ( ( PI ) / 2 ) ) by L90 , XREAL_1:6;
L93: ( ( PI ) + H1(R3) ) < ( R1 + ( ( PI ) / 2 ) ) by L92;
L94: ( R1 + ( ( PI ) / 2 ) ) < ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) + ( ( PI ) / 2 ) ) by L91 , XREAL_1:6;
L95: ( R1 + ( ( PI ) / 2 ) ) < ( ( 2 * ( PI ) ) + H1(R3) ) by L94;
L96: ( sin ( R1 + ( ( PI ) / 2 ) ) ) = ( cos R1 ) by SIN_COS:79;
thus L97: thesis by L96 , L93 , L95 , L74;
end;
theorem
L98: (for R1 being  real number holds (for R3 being  integer number holds ((( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) > ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L99: ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) < R1
and
L100: R1 < ( ( 2 * ( PI ) ) + H1(R3) );
L101: ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) - ( PI ) ) < ( R1 - ( PI ) ) by L99 , XREAL_1:9;
L102: ( ( ( PI ) / 2 ) + H1(R3) ) < ( R1 - ( PI ) ) by L101;
L103: (( ( PI ) + H1(R3) ) < ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) & ( R1 - ( PI ) ) < ( ( ( 2 * ( PI ) ) + H1(R3) ) - ( PI ) )) by L100 , COMPTRIG:5 , XREAL_1:6 , XREAL_1:9;
L104: ( R1 - ( PI ) ) < ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) by L103 , XXREAL_0:2;
L105: ( cos ( R1 - ( PI ) ) ) = ( cos ( - ( ( PI ) - R1 ) ) )
.= ( cos ( ( PI ) + ( - R1 ) ) ) by SIN_COS:31
.= ( - ( cos ( - R1 ) ) ) by SIN_COS:79
.= ( - ( cos R1 ) ) by SIN_COS:31;
thus L106: thesis by L105 , L102 , L104 , L89;
end;
theorem
L107: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 <= ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) >= ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L108: (( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 <= ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ));
per cases  by L108 , XXREAL_0:1;
suppose L109: (( ( 2 * ( PI ) ) * R3 ) < R1 & R1 < ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ));

thus L110: thesis by L109 , L67;
end;
suppose L111: ( ( 2 * ( PI ) ) * R3 ) = R1;

L112: ( sin ( ( 0 ) + ( ( 2 * ( PI ) ) * R3 ) ) ) = ( sin ( 0 ) ) by COMPLEX2:8;
thus L113: thesis by L112 , L111 , SIN_COS:31;
end;
suppose L114: R1 = ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) );

thus L115: thesis by L114 , COMPLEX2:8 , SIN_COS:77;
end;
end;
theorem
L117: (for R1 being  real number holds (for R3 being  integer number holds ((( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) <= ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L118: (( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ));
L119: ((( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) or ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) = R1 or R1 = ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) by L118 , XXREAL_0:1;
thus L120: thesis by L119 , L74 , COMPLEX2:8 , SIN_COS:77;
end;
theorem
L121: (for R1 being  real number holds (for R3 being  integer number holds ((( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) >= ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L122: (( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ));
L123: ((( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) )) or ( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) = R1 or R1 = ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) )) by L122 , XXREAL_0:1;
thus L124: thesis by L123 , L62 , L81 , COMPLEX2:9 , SIN_COS:77;
end;
theorem
L125: (for R1 being  real number holds (for R3 being  integer number holds ((( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) <= ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L126: (( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ));
L127: ((( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) or ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) = R1 or R1 = ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) by L126 , XXREAL_0:1;
thus L128: thesis by L127 , L89 , COMPLEX2:9 , SIN_COS:77;
end;
theorem
L129: (for R1 being  real number holds (for R3 being  integer number holds ((( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) >= ( 0 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L130: (( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) <= R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ));
per cases  by L130 , XXREAL_0:1;
suppose L131: (( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ));

thus L132: thesis by L131 , L98;
end;
suppose L133: ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) = R1;

thus L134: thesis by L133 , COMPLEX2:9 , SIN_COS:77;
end;
suppose L135: R1 = ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) );

thus L136: thesis by L135 , COMPLEX2:9 , SIN_COS:77;
end;
end;
theorem
L138: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) & ( sin R1 ) = ( 0 )) implies (R1 = ( ( 2 * ( PI ) ) * R3 ) or R1 = ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) )))))
proof
let R1 being  real number;
let R3 being  integer number;
assume L139: (H1(R3) <= R1 & R1 < ( ( 2 * ( PI ) ) + H1(R3) ));
assume L140: ( sin R1 ) = ( 0 );
L141: (R1 <= ( ( PI ) + H1(R3) ) or ( ( 2 * ( PI ) ) + H1(R3) ) <= R1) by L140 , L74;
L142: (R1 <= H1(R3) or R1 >= ( ( PI ) + H1(R3) )) by L140 , L67;
thus L143: thesis by L142 , L139 , L141 , XXREAL_0:1;
end;
theorem
L144: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) & ( cos R1 ) = ( 0 )) implies (R1 = ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) or R1 = ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L145: H1(R3) <= R1
and
L146: R1 < ( ( 2 * ( PI ) ) + H1(R3) );
L147: ( ( - ( ( PI ) / 2 ) ) + H1(R3) ) < ( ( 0 ) + H1(R3) ) by XREAL_1:6;
assume L148: ( cos R1 ) = ( 0 );
L149: (( ( ( PI ) / 2 ) + H1(R3) ) >= R1 or R1 >= ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) )) by L148 , L89;
L150: (( ( - ( ( PI ) / 2 ) ) + H1(R3) ) >= R1 or R1 >= ( ( ( PI ) / 2 ) + H1(R3) )) by L148 , L81;
L151: (R1 = ( ( ( PI ) / 2 ) + H1(R3) ) or R1 = ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) or R1 > ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) )) by L150 , L145 , L149 , L147 , XXREAL_0:1 , XXREAL_0:2;
thus L152: thesis by L151 , L146 , L148 , L98;
end;
theorem
L153: (for R1 being  real number holds (( sin R1 ) = ( - 1 ) implies R1 = ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] ) )))
proof
let R1 being  real number;
set D1 = [\ ( R1 / ( 2 * ( PI ) ) ) /];
consider C6 being  real number such that L154: C6 = ( ( ( 2 * ( PI ) ) * ( - D1 ) ) + R1 ) and L155: (( 0 ) <= C6 & C6 < ( 2 * ( PI ) )) by COMPLEX2:1;
assume L156: ( sin R1 ) = ( - 1 );
L157: ( ( ( cos R1 ) * ( cos R1 ) ) + ( ( - 1 ) * ( - 1 ) ) ) = 1 by L156 , SIN_COS:29;
L158: ( cos R1 ) = ( 0 ) by L157;
L159: (( ( 0 ) + H1(D1) ) <= ( C6 + H1(D1) ) & ( C6 + H1(D1) ) < ( ( 2 * ( PI ) ) + H1(D1) )) by L155 , XREAL_1:6;
L160: (R1 = ( ( ( PI ) / 2 ) + H1(D1) ) or R1 = ( ( ( 3 / 2 ) * ( PI ) ) + H1(D1) )) by L159 , L154 , L158 , L144;
thus L161: thesis by L160 , L156 , COMPLEX2:8 , SIN_COS:77;
end;
theorem
L162: (for R1 being  real number holds (( sin R1 ) = 1 implies R1 = ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] ) )))
proof
let R1 being  real number;
set D2 = [\ ( R1 / ( 2 * ( PI ) ) ) /];
consider C7 being  real number such that L163: C7 = ( ( ( 2 * ( PI ) ) * ( - D2 ) ) + R1 ) and L164: (( 0 ) <= C7 & C7 < ( 2 * ( PI ) )) by COMPLEX2:1;
assume L165: ( sin R1 ) = 1;
L166: ( ( ( cos R1 ) * ( cos R1 ) ) + ( 1 * 1 ) ) = 1 by L165 , SIN_COS:29;
L167: ( cos R1 ) = ( 0 ) by L166;
L168: (( ( 0 ) + H1(D2) ) <= ( C7 + H1(D2) ) & ( C7 + H1(D2) ) < ( ( 2 * ( PI ) ) + H1(D2) )) by L164 , XREAL_1:6;
L169: (R1 = ( ( ( PI ) / 2 ) + H1(D2) ) or R1 = ( ( ( 3 / 2 ) * ( PI ) ) + H1(D2) )) by L168 , L163 , L167 , L144;
thus L170: thesis by L169 , L165 , COMPLEX2:8 , SIN_COS:77;
end;
theorem
L171: (for R1 being  real number holds (( cos R1 ) = ( - 1 ) implies R1 = ( ( PI ) + ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] ) )))
proof
let R1 being  real number;
set D3 = [\ ( R1 / ( 2 * ( PI ) ) ) /];
consider C8 being  real number such that L172: C8 = ( ( ( 2 * ( PI ) ) * ( - D3 ) ) + R1 ) and L173: (( 0 ) <= C8 & C8 < ( 2 * ( PI ) )) by COMPLEX2:1;
assume L174: ( cos R1 ) = ( - 1 );
L175: ( ( ( sin R1 ) * ( sin R1 ) ) + ( ( - 1 ) * ( - 1 ) ) ) = 1 by L174 , SIN_COS:29;
L176: ( sin R1 ) = ( 0 ) by L175;
L177: (( ( 0 ) + H1(D3) ) <= ( C8 + H1(D3) ) & ( C8 + H1(D3) ) < ( ( 2 * ( PI ) ) + H1(D3) )) by L173 , XREAL_1:6;
L178: (R1 = ( ( 0 ) + H1(D3) ) or R1 = ( ( PI ) + H1(D3) )) by L177 , L172 , L176 , L138;
thus L179: thesis by L178 , L174 , COMPLEX2:9 , SIN_COS:31;
end;
theorem
L180: (for R1 being  real number holds (( cos R1 ) = 1 implies R1 = ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] )))
proof
let R1 being  real number;
set D4 = [\ ( R1 / ( 2 * ( PI ) ) ) /];
consider C9 being  real number such that L181: C9 = ( ( ( 2 * ( PI ) ) * ( - D4 ) ) + R1 ) and L182: (( 0 ) <= C9 & C9 < ( 2 * ( PI ) )) by COMPLEX2:1;
assume L183: ( cos R1 ) = 1;
L184: ( ( ( sin R1 ) * ( sin R1 ) ) + ( 1 * 1 ) ) = 1 by L183 , SIN_COS:29;
L185: ( sin R1 ) = ( 0 ) by L184;
L186: (( ( 0 ) + H1(D4) ) <= ( C9 + H1(D4) ) & ( C9 + H1(D4) ) < ( ( 2 * ( PI ) ) + H1(D4) )) by L182 , XREAL_1:6;
L187: (R1 = ( ( 0 ) + H1(D4) ) or R1 = ( ( PI ) + H1(D4) )) by L186 , L181 , L185 , L138;
thus L188: thesis by L187 , L183 , COMPLEX2:9 , SIN_COS:77;
end;
theorem
L189: (for R1 being  real number holds ((( 0 ) <= R1 & R1 <= ( 2 * ( PI ) ) & ( sin R1 ) = ( - 1 )) implies R1 = ( ( 3 / 2 ) * ( PI ) )))
proof
let R1 being  real number;
assume that
L190: ( 0 ) <= R1
and
L191: R1 <= ( 2 * ( PI ) )
and
L192: ( sin R1 ) = ( - 1 );
L193: (R1 = ( 2 * ( PI ) ) or R1 < ( 2 * ( PI ) )) by L191 , XXREAL_0:1;
thus L194: R1 = ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] ) ) by L192 , L153
.= ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * ( 0 ) ) ) by L190 , L192 , L193 , L1 , SIN_COS:77
.= ( ( 3 / 2 ) * ( PI ) );
end;
theorem
L195: (for R1 being  real number holds ((( 0 ) <= R1 & R1 <= ( 2 * ( PI ) ) & ( sin R1 ) = 1) implies R1 = ( ( PI ) / 2 )))
proof
let R1 being  real number;
assume that
L196: ( 0 ) <= R1
and
L197: R1 <= ( 2 * ( PI ) )
and
L198: ( sin R1 ) = 1;
L199: (R1 = ( 2 * ( PI ) ) or R1 < ( 2 * ( PI ) )) by L197 , XXREAL_0:1;
thus L200: R1 = ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] ) ) by L198 , L162
.= ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * ( 0 ) ) ) by L196 , L198 , L199 , L1 , SIN_COS:77
.= ( ( PI ) / 2 );
end;
theorem
L201: (for R1 being  real number holds ((( 0 ) <= R1 & R1 <= ( 2 * ( PI ) ) & ( cos R1 ) = ( - 1 )) implies R1 = ( PI )))
proof
let R1 being  real number;
assume that
L202: ( 0 ) <= R1
and
L203: R1 <= ( 2 * ( PI ) )
and
L204: ( cos R1 ) = ( - 1 );
L205: (R1 = ( 2 * ( PI ) ) or R1 < ( 2 * ( PI ) )) by L203 , XXREAL_0:1;
thus L206: R1 = ( ( PI ) + ( ( 2 * ( PI ) ) * [\ ( R1 / ( 2 * ( PI ) ) ) /] ) ) by L204 , L171
.= ( ( PI ) + ( ( 2 * ( PI ) ) * ( 0 ) ) ) by L202 , L204 , L205 , L1 , SIN_COS:77
.= ( PI );
end;
theorem
L207: (for R1 being  real number holds ((( 0 ) <= R1 & R1 < ( ( PI ) / 2 )) implies ( sin R1 ) < 1))
proof
let R1 being  real number;
assume that
L208: ( 0 ) <= R1
and
L209: R1 < ( ( PI ) / 2 )
and
L210: ( sin R1 ) >= 1;
L211: ( sin R1 ) <= 1 by L28;
L212: ( ( 1 / 2 ) * ( PI ) ) <= ( 2 * ( PI ) ) by XREAL_1:64;
L213: R1 < ( 2 * ( PI ) ) by L212 , L209 , XXREAL_0:2;
thus L214: thesis by L213 , L208 , L209 , L210 , L211 , L195 , XXREAL_0:1;
end;
theorem
L215: (for R1 being  real number holds ((( 0 ) <= R1 & R1 < ( ( 3 / 2 ) * ( PI ) )) implies ( sin R1 ) > ( - 1 )))
proof
let R1 being  real number;
assume that
L216: ( 0 ) <= R1
and
L217: R1 < ( ( 3 / 2 ) * ( PI ) )
and
L218: ( sin R1 ) <= ( - 1 );
L219: ( sin R1 ) >= ( - 1 ) by L24;
L220: R1 <= ( 2 * ( PI ) ) by L217 , L55 , XXREAL_0:2;
thus L221: thesis by L220 , L216 , L217 , L218 , L219 , L189 , XXREAL_0:1;
end;
theorem
L222: (for R1 being  real number holds ((( ( 3 / 2 ) * ( PI ) ) < R1 & R1 <= ( 2 * ( PI ) )) implies ( sin R1 ) > ( - 1 )))
proof
let R1 being  real number;
assume L223: (( ( 3 / 2 ) * ( PI ) ) < R1 & R1 <= ( 2 * ( PI ) ) & ( sin R1 ) <= ( - 1 ));
L224: ( sin R1 ) >= ( - 1 ) by L24;
thus L225: thesis by L224 , L223 , L189 , XXREAL_0:1;
end;
theorem
L226: (for R1 being  real number holds ((( ( PI ) / 2 ) < R1 & R1 <= ( 2 * ( PI ) )) implies ( sin R1 ) < 1))
proof
let R1 being  real number;
assume L227: (( ( PI ) / 2 ) < R1 & R1 <= ( 2 * ( PI ) ) & ( sin R1 ) >= 1);
L228: ( sin R1 ) <= 1 by L28;
thus L229: thesis by L228 , L227 , L195 , XXREAL_0:1;
end;
theorem
L230: (for R1 being  real number holds ((( 0 ) < R1 & R1 < ( 2 * ( PI ) )) implies ( cos R1 ) < 1))
proof
let R1 being  real number;
assume L231: (( 0 ) < R1 & R1 < ( 2 * ( PI ) ));
L232: ( cos R1 ) <> 1 by L231 , COMPTRIG:61;
L233: ( cos R1 ) <= 1 by L36;
thus L234: thesis by L233 , L232 , XXREAL_0:1;
end;
theorem
L235: (for R1 being  real number holds ((( 0 ) <= R1 & R1 < ( PI )) implies ( cos R1 ) > ( - 1 )))
proof
let R1 being  real number;
assume that
L236: ( 0 ) <= R1
and
L237: R1 < ( PI );
L238: ( cos R1 ) >= ( - 1 ) by L32;
L239: R1 <= ( 2 * ( PI ) ) by L237 , L56 , XXREAL_0:2;
thus L240: thesis by L239 , L236 , L237 , L238 , L201 , XXREAL_0:1;
end;
theorem
L241: (for R1 being  real number holds ((( PI ) < R1 & R1 <= ( 2 * ( PI ) )) implies ( cos R1 ) > ( - 1 )))
proof
let R1 being  real number;
assume L242: (( PI ) < R1 & R1 <= ( 2 * ( PI ) ));
L243: ( cos R1 ) >= ( - 1 ) by L32;
thus L244: thesis by L243 , L242 , L201 , XXREAL_0:1;
end;
theorem
L245: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 < ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) < 1)))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L246: (H1(R3) <= R1 & R1 < ( ( ( PI ) / 2 ) + H1(R3) ))
and
L247: ( sin R1 ) >= 1;
L248: (( H1(R3) - H1(R3) ) <= ( R1 - H1(R3) ) & ( R1 - H1(R3) ) < ( ( ( ( PI ) / 2 ) + H1(R3) ) - H1(R3) )) by L246 , XREAL_1:9;
L249: ( sin R1 ) <= 1 by L28;
L250: ( sin ( R1 - H1(R3) ) ) = ( sin ( R1 + H1(( - R3 )) ) )
.= ( sin R1 ) by COMPLEX2:8
.= 1 by L247 , L249 , XXREAL_0:1;
thus L251: thesis by L250 , L248 , L207;
end;
theorem
L252: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 < ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) > ( - 1 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L253: (H1(R3) <= R1 & R1 < ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ))
and
L254: ( sin R1 ) <= ( - 1 );
L255: (( H1(R3) - H1(R3) ) <= ( R1 - H1(R3) ) & ( R1 - H1(R3) ) < ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) - H1(R3) )) by L253 , XREAL_1:9;
L256: ( sin R1 ) >= ( - 1 ) by L24;
L257: ( sin ( R1 - H1(R3) ) ) = ( sin ( R1 + H1(( - R3 )) ) )
.= ( sin R1 ) by COMPLEX2:8
.= ( - 1 ) by L254 , L256 , XXREAL_0:1;
thus L258: thesis by L257 , L255 , L215;
end;
theorem
L259: (for R1 being  real number holds (for R3 being  integer number holds ((( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) > ( - 1 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L260: (( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) < R1 & R1 <= ( ( 2 * ( PI ) ) + H1(R3) ))
and
L261: ( sin R1 ) <= ( - 1 );
L262: (( ( ( ( 3 / 2 ) * ( PI ) ) + H1(R3) ) - H1(R3) ) < ( R1 - H1(R3) ) & ( R1 - H1(R3) ) <= ( ( ( 2 * ( PI ) ) + H1(R3) ) - H1(R3) )) by L260 , XREAL_1:9;
L263: ( sin R1 ) >= ( - 1 ) by L24;
L264: ( sin ( R1 - H1(R3) ) ) = ( sin ( R1 + H1(( - R3 )) ) )
.= ( sin R1 ) by COMPLEX2:8
.= ( - 1 ) by L261 , L263 , XXREAL_0:1;
thus L265: thesis by L264 , L262 , L222;
end;
theorem
L266: (for R1 being  real number holds (for R3 being  integer number holds ((( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( sin R1 ) < 1)))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L267: (( ( ( PI ) / 2 ) + H1(R3) ) < R1 & R1 <= ( ( 2 * ( PI ) ) + H1(R3) ))
and
L268: ( sin R1 ) >= 1;
L269: (( ( ( ( PI ) / 2 ) + H1(R3) ) - H1(R3) ) < ( R1 - H1(R3) ) & ( R1 - H1(R3) ) <= ( ( ( 2 * ( PI ) ) + H1(R3) ) - H1(R3) )) by L267 , XREAL_1:9;
L270: ( sin R1 ) <= 1 by L28;
L271: ( sin ( R1 - H1(R3) ) ) = ( sin ( R1 + H1(( - R3 )) ) )
.= ( sin R1 ) by COMPLEX2:8
.= 1 by L268 , L270 , XXREAL_0:1;
thus L272: thesis by L271 , L269 , L226;
end;
theorem
L273: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) < R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) < 1)))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L274: (H1(R3) < R1 & R1 < ( ( 2 * ( PI ) ) + H1(R3) ))
and
L275: ( cos R1 ) >= 1;
L276: (( H1(R3) - H1(R3) ) < ( R1 - H1(R3) ) & ( R1 - H1(R3) ) < ( ( ( 2 * ( PI ) ) + H1(R3) ) - H1(R3) )) by L274 , XREAL_1:9;
L277: ( cos R1 ) <= 1 by L36;
L278: ( cos ( R1 - H1(R3) ) ) = ( cos ( R1 + H1(( - R3 )) ) )
.= ( cos R1 ) by COMPLEX2:9
.= 1 by L275 , L277 , XXREAL_0:1;
thus L279: thesis by L278 , L276 , L230;
end;
theorem
L280: (for R1 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 < ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) > ( - 1 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L281: (H1(R3) <= R1 & R1 < ( ( PI ) + H1(R3) ))
and
L282: ( cos R1 ) <= ( - 1 );
L283: (( H1(R3) - H1(R3) ) <= ( R1 - H1(R3) ) & ( R1 - H1(R3) ) < ( ( ( PI ) + H1(R3) ) - H1(R3) )) by L281 , XREAL_1:9;
L284: ( cos R1 ) >= ( - 1 ) by L32;
L285: ( cos ( R1 - H1(R3) ) ) = ( cos ( R1 + H1(( - R3 )) ) )
.= ( cos R1 ) by COMPLEX2:9
.= ( - 1 ) by L282 , L284 , XXREAL_0:1;
thus L286: thesis by L285 , L283 , L235;
end;
theorem
L287: (for R1 being  real number holds (for R3 being  integer number holds ((( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) < R1 & R1 <= ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )) implies ( cos R1 ) > ( - 1 ))))
proof
let R1 being  real number;
let R3 being  integer number;
assume that
L288: (( ( PI ) + H1(R3) ) < R1 & R1 <= ( ( 2 * ( PI ) ) + H1(R3) ))
and
L289: ( cos R1 ) <= ( - 1 );
L290: (( ( ( PI ) + H1(R3) ) - H1(R3) ) < ( R1 - H1(R3) ) & ( R1 - H1(R3) ) <= ( ( ( 2 * ( PI ) ) + H1(R3) ) - H1(R3) )) by L288 , XREAL_1:9;
L291: ( cos R1 ) >= ( - 1 ) by L32;
L292: ( cos ( R1 - H1(R3) ) ) = ( cos ( R1 + H1(( - R3 )) ) )
.= ( cos R1 ) by COMPLEX2:9
.= ( - 1 ) by L289 , L291 , XXREAL_0:1;
thus L293: thesis by L292 , L290 , L241;
end;
theorem
L294: (for R1 being  real number holds (( cos ( ( 2 * ( PI ) ) * R1 ) ) = 1 implies R1 in ( INT )))
proof
let R1 being  real number;
reconsider D5 = 2 as  positive  real number;
assume L295: ( cos ( ( 2 * ( PI ) ) * R1 ) ) = 1;
assume L296: (not R1 in ( INT ));
L297: (not R1 is  integer) by L296 , INT_1:def 2;
reconsider D6 = ( frac R1 ) as  positive  real number by L297 , INT_1:46;
set D7 = [\ R1 /];
L298: (R1 = ( D7 + D6 ) & ( ( D5 * ( PI ) ) * D6 ) < ( ( D5 * ( PI ) ) * 1 )) by INT_1:42 , INT_1:43 , XREAL_1:68;
L299: ( cos ( ( 2 * ( PI ) ) * ( D7 + D6 ) ) ) = ( cos ( ( ( 2 * ( PI ) ) * D7 ) + ( ( 2 * ( PI ) ) * D6 ) ) )
.= ( cos ( ( 2 * ( PI ) ) * D6 ) ) by COMPLEX2:9;
thus L300: contradiction by L299 , L295 , L298 , L230;
end;
theorem
L301: ( ( sin ) .: [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) = [. ( - 1 ) , 1 .] by COMPTRIG:30 , RELAT_1:115;
theorem
L302: ( ( sin ) .: ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) = ]. ( - 1 ) , 1 .[
proof
L303: ( ( sin ) | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) c= ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) by RELAT_1:75 , XXREAL_1:25;
L304: ( rng ( ( sin ) | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) ) c= ( rng ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) by L303 , RELAT_1:11;
L305: ( rng ( ( sin ) | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) ) = ( ( sin ) .: ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) by RELAT_1:115;
thus L306: ( ( sin ) .: ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) c= ]. ( - 1 ) , 1 .[
proof
let C10 being set;
assume L307: C10 in ( ( sin ) .: ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ );
consider C11 being set such that L308: C11 in ( dom ( sin ) ) and L309: C11 in ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ and L310: ( ( sin ) . C11 ) = C10 by L307 , FUNCT_1:def 6;
reconsider D8 = C11 , D9 = C10 as Real by L308 , L310;
set D10 = [\ ( D8 / ( 2 * ( PI ) ) ) /];
L311: ( H1(D10) / ( ( 2 * ( PI ) ) * 1 ) ) = ( D10 / 1 ) by XCMPLX_1:91;
L312: ( ( sin ) . D8 ) = ( sin D8 ) by SIN_COS:def 17;
L313:
now
assume L314: D9 = 1;
L315: D8 = ( ( ( PI ) / 2 ) + H1(D10) ) by L314 , L310 , L312 , L162;
L316: ( ( ( PI ) / 2 ) + H1(D10) ) < ( ( PI ) / 2 ) by L315 , L309 , XXREAL_1:4;
L317: ( ( ( ( PI ) / 2 ) + H1(D10) ) - ( ( PI ) / 2 ) ) < ( ( ( PI ) / 2 ) - ( ( PI ) / 2 ) ) by L316 , XREAL_1:9;
L318: D10 < ( 0 ) by L317;
L319: D10 <= ( - 1 ) by L318 , INT_1:8;
L320: ( - ( ( PI ) / 2 ) ) < ( ( ( PI ) / 2 ) + H1(D10) ) by L309 , L315 , XXREAL_1:4;
L321: ( ( - ( ( PI ) / 2 ) ) - ( ( PI ) / 2 ) ) < ( ( ( ( PI ) / 2 ) + H1(D10) ) - ( ( PI ) / 2 ) ) by L320 , XREAL_1:9;
L322: ( ( ( - 1 ) * ( PI ) ) / ( 2 * ( PI ) ) ) < D10 by L321 , L311 , XREAL_1:74;
L323: ( ( - 1 ) / 2 ) < D10 by L322 , XCMPLX_1:91;
thus L324: contradiction by L323 , L319 , XXREAL_0:2;
end;
L325:
now
assume L326: D9 = ( - 1 );
L327: D8 = ( ( ( 3 / 2 ) * ( PI ) ) + H1(D10) ) by L326 , L310 , L312 , L153;
L328: ( - ( ( PI ) / 2 ) ) < ( ( ( 3 / 2 ) * ( PI ) ) + H1(D10) ) by L327 , L309 , XXREAL_1:4;
L329: ( ( - ( ( PI ) / 2 ) ) - ( ( 3 / 2 ) * ( PI ) ) ) < ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(D10) ) - ( ( 3 / 2 ) * ( PI ) ) ) by L328 , XREAL_1:9;
L330: ( ( - ( 2 * ( PI ) ) ) / ( 2 * ( PI ) ) ) < D10 by L329 , L311 , XREAL_1:74;
L331: ( - ( ( 2 * ( PI ) ) / ( 2 * ( PI ) ) ) ) < D10 by L330 , XCMPLX_1:187;
L332: ( - 1 ) < D10 by L331 , XCMPLX_1:60;
L333: ( ( - 1 ) + 1 ) <= D10 by L332 , INT_1:7;
L334: ( ( ( 3 / 2 ) * ( PI ) ) + H1(D10) ) < ( ( PI ) / 2 ) by L309 , L327 , XXREAL_1:4;
L335: ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(D10) ) - ( ( 3 / 2 ) * ( PI ) ) ) < ( ( ( PI ) / 2 ) - ( ( 3 / 2 ) * ( PI ) ) ) by L334 , XREAL_1:9;
L336: D10 < ( ( - ( PI ) ) / ( 2 * ( PI ) ) ) by L335 , L311 , XREAL_1:74;
thus L337: contradiction by L336 , L333 , XCMPLX_1:91;
end;
L338: D9 <= 1 by L304 , L305 , L307 , COMPTRIG:30 , XXREAL_1:1;
L339: D9 < 1 by L338 , L313 , XXREAL_0:1;
L340: ( - 1 ) <= D9 by L304 , L305 , L307 , COMPTRIG:30 , XXREAL_1:1;
L341: ( - 1 ) < D9 by L340 , L325 , XXREAL_0:1;
thus L342: thesis by L341 , L339 , XXREAL_1:4;
end;

let C12 being set;
assume L343: C12 in ]. ( - 1 ) , 1 .[;
reconsider D11 = C12 as Real by L343;
L344: (( - 1 ) < D11 & D11 < 1) by L343 , XXREAL_1:4;
L345: D11 in ( rng ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) by L344 , COMPTRIG:30 , XXREAL_1:1;
consider C13 being set such that L346: C13 in ( dom ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) and L347: ( ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) . C13 ) = D11 by L345 , FUNCT_1:def 3;
reconsider D12 = C13 as Real by L346;
L348: ( ( sin ) . D12 ) = D11 by L346 , L347 , FUNCT_1:47;
L349: ( dom ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) = [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by RELAT_1:62 , SIN_COS:24;
L350: (( - ( ( PI ) / 2 ) ) <= D12 & D12 <= ( ( PI ) / 2 )) by L349 , L346 , XXREAL_1:1;
L351: ((( - ( ( PI ) / 2 ) ) < D12 & D12 < ( ( PI ) / 2 )) or ( - ( ( PI ) / 2 ) ) = D12 or ( ( PI ) / 2 ) = D12) by L350 , XXREAL_0:1;
L352: D12 in ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ by L351 , L343 , L348 , L57 , SIN_COS:76 , XXREAL_1:4;
thus L353: thesis by L352 , L348 , FUNCT_1:def 6 , SIN_COS:24;
end;
theorem
L354: ( ( sin ) .: [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) = [. ( - 1 ) , 1 .] by COMPTRIG:31 , RELAT_1:115;
theorem
L355: ( ( sin ) .: ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) = ]. ( - 1 ) , 1 .[
proof
L356: ( ( sin ) | ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) c= ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) by RELAT_1:75 , XXREAL_1:25;
L357: ( rng ( ( sin ) | ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) ) c= ( rng ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ) by L356 , RELAT_1:11;
L358: ( rng ( ( sin ) | ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) ) = ( ( sin ) .: ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) by RELAT_1:115;
thus L359: ( ( sin ) .: ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) c= ]. ( - 1 ) , 1 .[
proof
let C14 being set;
assume L360: C14 in ( ( sin ) .: ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ );
consider C15 being set such that L361: C15 in ( dom ( sin ) ) and L362: C15 in ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ and L363: ( ( sin ) . C15 ) = C14 by L360 , FUNCT_1:def 6;
reconsider D13 = C15 , D14 = C14 as Real by L361 , L363;
set D15 = [\ ( D13 / ( 2 * ( PI ) ) ) /];
L364: ( H1(D15) / ( ( 2 * ( PI ) ) * 1 ) ) = ( D15 / 1 ) by XCMPLX_1:91;
L365: ( ( sin ) . D13 ) = ( sin D13 ) by SIN_COS:def 17;
L366:
now
assume L367: D14 = 1;
L368: D13 = ( ( ( PI ) / 2 ) + H1(D15) ) by L367 , L363 , L365 , L162;
L369: ( ( PI ) / 2 ) < ( ( ( PI ) / 2 ) + H1(D15) ) by L368 , L362 , XXREAL_1:4;
L370: ( ( ( PI ) / 2 ) - ( ( PI ) / 2 ) ) < ( ( ( ( PI ) / 2 ) + H1(D15) ) - ( ( PI ) / 2 ) ) by L369 , XREAL_1:9;
L371: ( 0 ) < D15 by L370;
L372: ( ( 0 ) + 1 ) <= D15 by L371 , INT_1:7;
L373: ( ( ( PI ) / 2 ) + H1(D15) ) < ( ( 3 / 2 ) * ( PI ) ) by L362 , L368 , XXREAL_1:4;
L374: ( ( ( ( PI ) / 2 ) + H1(D15) ) - ( ( PI ) / 2 ) ) < ( ( ( 3 / 2 ) * ( PI ) ) - ( ( PI ) / 2 ) ) by L373 , XREAL_1:9;
L375: D15 < ( ( 1 * ( PI ) ) / ( 2 * ( PI ) ) ) by L374 , L364 , XREAL_1:74;
L376: D15 < ( 1 / 2 ) by L375 , XCMPLX_1:91;
thus L377: contradiction by L376 , L372 , XXREAL_0:2;
end;
L378:
now
assume L379: D14 = ( - 1 );
L380: D13 = ( ( ( 3 / 2 ) * ( PI ) ) + H1(D15) ) by L379 , L363 , L365 , L153;
L381: ( ( ( 3 / 2 ) * ( PI ) ) + H1(D15) ) < ( ( 3 / 2 ) * ( PI ) ) by L380 , L362 , XXREAL_1:4;
L382: ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(D15) ) - ( ( 3 / 2 ) * ( PI ) ) ) < ( ( ( 3 / 2 ) * ( PI ) ) - ( ( 3 / 2 ) * ( PI ) ) ) by L381 , XREAL_1:9;
L383: D15 < ( 0 ) by L382;
L384: D15 <= ( - 1 ) by L383 , INT_1:8;
L385: ( ( PI ) / 2 ) < ( ( ( 3 / 2 ) * ( PI ) ) + H1(D15) ) by L362 , L380 , XXREAL_1:4;
L386: ( ( ( PI ) / 2 ) - ( ( 3 / 2 ) * ( PI ) ) ) < ( ( ( ( 3 / 2 ) * ( PI ) ) + H1(D15) ) - ( ( 3 / 2 ) * ( PI ) ) ) by L385 , XREAL_1:9;
L387: ( ( ( - 1 ) * ( PI ) ) / ( 2 * ( PI ) ) ) < D15 by L386 , L364 , XREAL_1:74;
L388: ( ( - 1 ) / 2 ) < D15 by L387 , XCMPLX_1:91;
thus L389: contradiction by L388 , L384 , XXREAL_0:2;
end;
L390: D14 <= 1 by L357 , L358 , L360 , COMPTRIG:31 , XXREAL_1:1;
L391: D14 < 1 by L390 , L366 , XXREAL_0:1;
L392: ( - 1 ) <= D14 by L357 , L358 , L360 , COMPTRIG:31 , XXREAL_1:1;
L393: ( - 1 ) < D14 by L392 , L378 , XXREAL_0:1;
thus L394: thesis by L393 , L391 , XXREAL_1:4;
end;

let C16 being set;
assume L395: C16 in ]. ( - 1 ) , 1 .[;
reconsider D16 = C16 as Real by L395;
L396: (( - 1 ) < D16 & D16 < 1) by L395 , XXREAL_1:4;
L397: D16 in ( rng ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ) by L396 , COMPTRIG:31 , XXREAL_1:1;
consider C17 being set such that L398: C17 in ( dom ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ) and L399: ( ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) . C17 ) = D16 by L397 , FUNCT_1:def 3;
reconsider D17 = C17 as Real by L398;
L400: ( ( sin ) . D17 ) = D16 by L398 , L399 , FUNCT_1:47;
L401: ( dom ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ) = [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] by RELAT_1:62 , SIN_COS:24;
L402: (( ( PI ) / 2 ) <= D17 & D17 <= ( ( 3 / 2 ) * ( PI ) )) by L401 , L398 , XXREAL_1:1;
L403: ((( ( PI ) / 2 ) < D17 & D17 < ( ( 3 / 2 ) * ( PI ) )) or ( ( PI ) / 2 ) = D17 or ( ( 3 / 2 ) * ( PI ) ) = D17) by L402 , XXREAL_0:1;
L404: D17 in ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ by L403 , L395 , L400 , SIN_COS:76 , XXREAL_1:4;
thus L405: thesis by L404 , L400 , FUNCT_1:def 6 , SIN_COS:24;
end;
theorem
L406: ( ( cos ) .: [. ( 0 ) , ( PI ) .] ) = [. ( - 1 ) , 1 .] by COMPTRIG:32 , RELAT_1:115;
theorem
L407: ( ( cos ) .: ]. ( 0 ) , ( PI ) .[ ) = ]. ( - 1 ) , 1 .[
proof
L408: ( ( cos ) | ]. ( 0 ) , ( PI ) .[ ) c= ( ( cos ) | [. ( 0 ) , ( PI ) .] ) by RELAT_1:75 , XXREAL_1:25;
L409: ( rng ( ( cos ) | ]. ( 0 ) , ( PI ) .[ ) ) c= ( rng ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) by L408 , RELAT_1:11;
L410: ( rng ( ( cos ) | ]. ( 0 ) , ( PI ) .[ ) ) = ( ( cos ) .: ]. ( 0 ) , ( PI ) .[ ) by RELAT_1:115;
thus L411: ( ( cos ) .: ]. ( 0 ) , ( PI ) .[ ) c= ]. ( - 1 ) , 1 .[
proof
let C18 being set;
assume L412: C18 in ( ( cos ) .: ]. ( 0 ) , ( PI ) .[ );
consider C19 being set such that L413: C19 in ( dom ( cos ) ) and L414: C19 in ]. ( 0 ) , ( PI ) .[ and L415: ( ( cos ) . C19 ) = C18 by L412 , FUNCT_1:def 6;
reconsider D18 = C19 , D19 = C18 as Real by L413 , L415;
set D20 = [\ ( D18 / ( 2 * ( PI ) ) ) /];
L416: ( H1(D20) / ( ( 2 * ( PI ) ) * 1 ) ) = ( D20 / 1 ) by XCMPLX_1:91;
L417: ( ( cos ) . D18 ) = ( cos D18 ) by SIN_COS:def 19;
L418:
now
assume L419: D19 = 1;
L420: D18 = H1(D20) by L419 , L415 , L417 , L180;
L421: H1(D20) < ( PI ) by L420 , L414 , XXREAL_1:4;
L422: D20 < ( ( 1 * ( PI ) ) / ( 2 * ( PI ) ) ) by L421 , L416 , XREAL_1:74;
L423: D20 < ( 1 / 2 ) by L422 , XCMPLX_1:91;
L424: ( 0 ) < D20 by L414 , L420 , XXREAL_1:4;
L425: ( ( 0 ) + 1 ) <= D20 by L424 , INT_1:7;
thus L426: contradiction by L425 , L423 , XXREAL_0:2;
end;
L427:
now
assume L428: D19 = ( - 1 );
L429: D18 = ( ( PI ) + H1(D20) ) by L428 , L415 , L417 , L171;
L430: ( 0 ) < ( ( PI ) + H1(D20) ) by L429 , L414 , XXREAL_1:4;
L431: ( ( 0 ) - ( PI ) ) < ( ( ( PI ) + H1(D20) ) - ( PI ) ) by L430 , XREAL_1:9;
L432: ( ( - ( PI ) ) / ( 2 * ( PI ) ) ) < ( H1(D20) / ( 2 * ( PI ) ) ) by L431 , XREAL_1:74;
L433: ( - ( ( 1 * ( PI ) ) / ( 2 * ( PI ) ) ) ) < D20 by L432 , L416 , XCMPLX_1:187;
L434: ( - ( 1 / 2 ) ) < D20 by L433 , XCMPLX_1:91;
L435: ( ( PI ) + H1(D20) ) < ( PI ) by L414 , L429 , XXREAL_1:4;
L436: ( ( ( PI ) + H1(D20) ) - ( PI ) ) < ( ( PI ) - ( PI ) ) by L435 , XREAL_1:9;
L437: D20 < ( 0 ) by L436;
L438: D20 <= ( - 1 ) by L437 , INT_1:8;
thus L439: contradiction by L438 , L434 , XXREAL_0:2;
end;
L440: D19 <= 1 by L409 , L410 , L412 , COMPTRIG:32 , XXREAL_1:1;
L441: D19 < 1 by L440 , L418 , XXREAL_0:1;
L442: ( - 1 ) <= D19 by L409 , L410 , L412 , COMPTRIG:32 , XXREAL_1:1;
L443: ( - 1 ) < D19 by L442 , L427 , XXREAL_0:1;
thus L444: thesis by L443 , L441 , XXREAL_1:4;
end;

let C20 being set;
assume L445: C20 in ]. ( - 1 ) , 1 .[;
reconsider D21 = C20 as Real by L445;
L446: (( - 1 ) < D21 & D21 < 1) by L445 , XXREAL_1:4;
L447: D21 in ( rng ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) by L446 , COMPTRIG:32 , XXREAL_1:1;
consider C21 being set such that L448: C21 in ( dom ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) and L449: ( ( ( cos ) | [. ( 0 ) , ( PI ) .] ) . C21 ) = D21 by L447 , FUNCT_1:def 3;
reconsider D22 = C21 as Real by L448;
L450: ( ( cos ) . D22 ) = D21 by L448 , L449 , FUNCT_1:47;
L451: ( dom ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) = [. ( 0 ) , ( PI ) .] by RELAT_1:62 , SIN_COS:24;
L452: D22 <= ( PI ) by L451 , L448 , XXREAL_1:1;
L453: ((( 0 ) < D22 & D22 < ( PI )) or ( 0 ) = D22 or ( PI ) = D22) by L452 , L448 , L451 , XXREAL_0:1 , XXREAL_1:1;
L454: D22 in ]. ( 0 ) , ( PI ) .[ by L453 , L445 , L450 , SIN_COS:30 , SIN_COS:76 , XXREAL_1:4;
thus L455: thesis by L454 , L450 , FUNCT_1:def 6 , SIN_COS:24;
end;
theorem
L456: ( ( cos ) .: [. ( PI ) , ( 2 * ( PI ) ) .] ) = [. ( - 1 ) , 1 .] by COMPTRIG:33 , RELAT_1:115;
theorem
L457: ( ( cos ) .: ]. ( PI ) , ( 2 * ( PI ) ) .[ ) = ]. ( - 1 ) , 1 .[
proof
L458: ( ( cos ) | ]. ( PI ) , ( 2 * ( PI ) ) .[ ) c= ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) by RELAT_1:75 , XXREAL_1:25;
L459: ( rng ( ( cos ) | ]. ( PI ) , ( 2 * ( PI ) ) .[ ) ) c= ( rng ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) ) by L458 , RELAT_1:11;
L460: ( rng ( ( cos ) | ]. ( PI ) , ( 2 * ( PI ) ) .[ ) ) = ( ( cos ) .: ]. ( PI ) , ( 2 * ( PI ) ) .[ ) by RELAT_1:115;
thus L461: ( ( cos ) .: ]. ( PI ) , ( 2 * ( PI ) ) .[ ) c= ]. ( - 1 ) , 1 .[
proof
let C22 being set;
assume L462: C22 in ( ( cos ) .: ]. ( PI ) , ( 2 * ( PI ) ) .[ );
consider C23 being set such that L463: C23 in ( dom ( cos ) ) and L464: C23 in ]. ( PI ) , ( 2 * ( PI ) ) .[ and L465: ( ( cos ) . C23 ) = C22 by L462 , FUNCT_1:def 6;
reconsider D23 = C23 , D24 = C22 as Real by L463 , L465;
set D25 = [\ ( D23 / ( 2 * ( PI ) ) ) /];
L466: ( H1(D25) / ( ( 2 * ( PI ) ) * 1 ) ) = ( D25 / 1 ) by XCMPLX_1:91;
L467: ( ( cos ) . D23 ) = ( cos D23 ) by SIN_COS:def 19;
L468:
now
assume L469: D24 = 1;
L470: D23 = H1(D25) by L469 , L465 , L467 , L180;
L471: H1(D25) < ( 2 * ( PI ) ) by L470 , L464 , XXREAL_1:4;
L472: D25 < ( ( 2 * ( PI ) ) / ( 2 * ( PI ) ) ) by L471 , L466 , XREAL_1:74;
L473: D25 < ( 1 + ( 0 ) ) by L472 , XCMPLX_1:60;
L474: ( PI ) < H1(D25) by L464 , L470 , XXREAL_1:4;
thus L475: contradiction by L474 , L466 , L473 , INT_1:7;
end;
L476:
now
assume L477: D24 = ( - 1 );
L478: D23 = ( ( PI ) + H1(D25) ) by L477 , L465 , L467 , L171;
L479: ( PI ) < ( ( PI ) + H1(D25) ) by L478 , L464 , XXREAL_1:4;
L480: ( ( PI ) - ( PI ) ) < ( ( ( PI ) + H1(D25) ) - ( PI ) ) by L479 , XREAL_1:9;
L481: ( ( 0 ) / ( 2 * ( PI ) ) ) < D25 by L480;
L482: ( ( 0 ) + 1 ) <= D25 by L481 , INT_1:7;
L483: ( ( PI ) + H1(D25) ) < ( 2 * ( PI ) ) by L464 , L478 , XXREAL_1:4;
L484: ( ( ( PI ) + H1(D25) ) - ( PI ) ) < ( ( 2 * ( PI ) ) - ( PI ) ) by L483 , XREAL_1:9;
L485: D25 < ( ( 1 * ( PI ) ) / ( 2 * ( PI ) ) ) by L484 , L466 , XREAL_1:74;
L486: D25 <= ( 1 / 2 ) by L485 , XCMPLX_1:91;
thus L487: contradiction by L486 , L482 , XXREAL_0:2;
end;
L488: D24 <= 1 by L459 , L460 , L462 , COMPTRIG:33 , XXREAL_1:1;
L489: D24 < 1 by L488 , L468 , XXREAL_0:1;
L490: ( - 1 ) <= D24 by L459 , L460 , L462 , COMPTRIG:33 , XXREAL_1:1;
L491: ( - 1 ) < D24 by L490 , L476 , XXREAL_0:1;
thus L492: thesis by L491 , L489 , XXREAL_1:4;
end;

let C24 being set;
assume L493: C24 in ]. ( - 1 ) , 1 .[;
reconsider D26 = C24 as Real by L493;
L494: (( - 1 ) < D26 & D26 < 1) by L493 , XXREAL_1:4;
L495: D26 in ( rng ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) ) by L494 , COMPTRIG:33 , XXREAL_1:1;
consider C25 being set such that L496: C25 in ( dom ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) ) and L497: ( ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) . C25 ) = D26 by L495 , FUNCT_1:def 3;
reconsider D27 = C25 as Real by L496;
L498: ( ( cos ) . D27 ) = D26 by L496 , L497 , FUNCT_1:47;
L499: ( dom ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) ) = [. ( PI ) , ( 2 * ( PI ) ) .] by RELAT_1:62 , SIN_COS:24;
L500: (( PI ) <= D27 & D27 <= ( 2 * ( PI ) )) by L499 , L496 , XXREAL_1:1;
L501: ((( PI ) < D27 & D27 < ( 2 * ( PI ) )) or ( PI ) = D27 or ( 2 * ( PI ) ) = D27) by L500 , XXREAL_0:1;
L502: D27 in ]. ( PI ) , ( 2 * ( PI ) ) .[ by L501 , L493 , L498 , SIN_COS:76 , XXREAL_1:4;
thus L503: thesis by L502 , L498 , FUNCT_1:def 6 , SIN_COS:24;
end;
L504:
now
let R3 being  integer number;
let R1 being  real number;
let C26 , C27 being  real number;
assume L505: R1 in [. ( C26 + H1(R3) ) , ( C27 + H1(R3) ) .];
L506: R1 <= ( C27 + H1(R3) ) by L505 , XXREAL_1:1;
L507: ( R1 + ( 2 * ( PI ) ) ) <= ( ( C27 + H1(R3) ) + ( 2 * ( PI ) ) ) by L506 , XREAL_1:6;
L508: ( C26 + H1(R3) ) <= R1 by L505 , XXREAL_1:1;
L509: ( ( C26 + H1(R3) ) + ( 2 * ( PI ) ) ) <= ( R1 + ( 2 * ( PI ) ) ) by L508 , XREAL_1:6;
thus L510: ( R1 + ( 2 * ( PI ) ) ) in [. ( C26 + H1(( R3 + 1 )) ) , ( C27 + H1(( R3 + 1 )) ) .] by L509 , L507 , XXREAL_1:1;
end;
L511:
now
let R3 being  integer number;
let R1 being  real number;
let C28 , C29 being  real number;
assume L512: R1 in ( [. ( C28 + H1(R3) ) , ( C29 + H1(R3) ) .] /\ ( REAL ) );
L513: R1 in [. ( C28 + H1(R3) ) , ( C29 + H1(R3) ) .] by L512 , XBOOLE_0:def 4;
L514: ( R1 + ( 2 * ( PI ) ) ) in [. ( C28 + H1(( R3 + 1 )) ) , ( C29 + H1(( R3 + 1 )) ) .] by L513 , L504;
thus L515: ( R1 + ( 2 * ( PI ) ) ) in ( [. ( C28 + H1(( R3 + 1 )) ) , ( C29 + H1(( R3 + 1 )) ) .] /\ ( REAL ) ) by L514 , XBOOLE_0:def 4;
end;
L516:
now
let R3 being  integer number;
let R1 being  real number;
let C30 , C31 being  real number;
assume L517: R1 in [. ( C30 + H1(R3) ) , ( C31 + H1(R3) ) .];
L518: R1 <= ( C31 + H1(R3) ) by L517 , XXREAL_1:1;
L519: ( R1 - ( 2 * ( PI ) ) ) <= ( ( C31 + H1(R3) ) - ( 2 * ( PI ) ) ) by L518 , XREAL_1:9;
L520: ( C30 + H1(R3) ) <= R1 by L517 , XXREAL_1:1;
L521: ( ( C30 + H1(R3) ) - ( 2 * ( PI ) ) ) <= ( R1 - ( 2 * ( PI ) ) ) by L520 , XREAL_1:9;
thus L522: ( R1 - ( 2 * ( PI ) ) ) in [. ( C30 + H1(( R3 - 1 )) ) , ( C31 + H1(( R3 - 1 )) ) .] by L521 , L519 , XXREAL_1:1;
end;
L523:
now
let R3 being  integer number;
let R1 being  real number;
let C32 , C33 being  real number;
assume L524: R1 in ( [. ( C32 + H1(R3) ) , ( C33 + H1(R3) ) .] /\ ( REAL ) );
L525: R1 in [. ( C32 + H1(R3) ) , ( C33 + H1(R3) ) .] by L524 , XBOOLE_0:def 4;
L526: ( R1 - ( 2 * ( PI ) ) ) in [. ( C32 + H1(( R3 - 1 )) ) , ( C33 + H1(( R3 - 1 )) ) .] by L525 , L516;
thus L527: ( R1 - ( 2 * ( PI ) ) ) in ( [. ( C32 + H1(( R3 - 1 )) ) , ( C33 + H1(( R3 - 1 )) ) .] /\ ( REAL ) ) by L526 , XBOOLE_0:def 4;
end;
theorem
L528: (for R3 being  integer number holds ( ( sin ) | [. ( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  increasing)
proof
let R3 being  integer number;
defpred S1[ Integer ] means ( ( sin ) | [. ( ( - ( ( PI ) / 2 ) ) + H1($1) ) , ( ( ( PI ) / 2 ) + H1($1) ) .] ) is  increasing;
L529: (for R3 being  integer number holds (S1[ R3 ] implies (S1[ ( R3 - 1 ) ] & S1[ ( R3 + 1 ) ])))
proof
let R3 being  integer number;
assume that
L530: S1[ R3 ];
set D28 = [. ( ( - ( ( PI ) / 2 ) ) + H1(( ( R3 - 1 ) + 1 )) ) , ( ( ( PI ) / 2 ) + H1(( ( R3 - 1 ) + 1 )) ) .];
thus L531: S1[ ( R3 - 1 ) ]
proof
set D29 = [. ( ( - ( ( PI ) / 2 ) ) + H1(( R3 - 1 )) ) , ( ( ( PI ) / 2 ) + H1(( R3 - 1 )) ) .];
L532:
now
let C34 , C35 being (Element of ( REAL ));
assume L533: (C34 in ( D29 /\ ( dom ( sin ) ) ) & C35 in ( D29 /\ ( dom ( sin ) ) ));
L534: (( C34 + ( 2 * ( PI ) ) ) in ( D28 /\ ( dom ( sin ) ) ) & ( C35 + ( 2 * ( PI ) ) ) in ( D28 /\ ( dom ( sin ) ) )) by L533 , L511 , SIN_COS:24;
assume L535: C34 < C35;
L536: ( C34 + ( 2 * ( PI ) ) ) < ( C35 + ( 2 * ( PI ) ) ) by L535 , XREAL_1:6;
L537: ( ( sin ) . ( C34 + ( 2 * ( PI ) ) ) ) < ( ( sin ) . ( C35 + ( ( 2 * ( PI ) ) * 1 ) ) ) by L536 , L530 , L534 , RFUNCT_2:20;
L538: ( ( sin ) . ( C34 + ( ( 2 * ( PI ) ) * 1 ) ) ) < ( ( sin ) . C35 ) by L537 , L60;
thus L539: ( ( sin ) . C34 ) < ( ( sin ) . C35 ) by L538 , L60;
end;
thus L540: thesis by L532 , RFUNCT_2:20;
end;

set D30 = [. ( ( - ( ( PI ) / 2 ) ) + H1(( R3 + 1 )) ) , ( ( ( PI ) / 2 ) + H1(( R3 + 1 )) ) .];
L541: D28 = [. ( ( - ( ( PI ) / 2 ) ) + H1(( ( R3 + 1 ) - 1 )) ) , ( ( ( PI ) / 2 ) + H1(( ( R3 + 1 ) - 1 )) ) .];
L542:
now
let C36 , C37 being (Element of ( REAL ));
assume L543: (C36 in ( D30 /\ ( dom ( sin ) ) ) & C37 in ( D30 /\ ( dom ( sin ) ) ));
L544: (( C36 - ( 2 * ( PI ) ) ) in ( D28 /\ ( dom ( sin ) ) ) & ( C37 - ( 2 * ( PI ) ) ) in ( D28 /\ ( dom ( sin ) ) )) by L543 , L541 , L523 , SIN_COS:24;
assume L545: C36 < C37;
L546: ( C36 - ( 2 * ( PI ) ) ) < ( C37 - ( 2 * ( PI ) ) ) by L545 , XREAL_1:9;
L547: ( ( sin ) . ( C36 - ( 2 * ( PI ) ) ) ) < ( ( sin ) . ( C37 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) by L546 , L530 , L544 , RFUNCT_2:20;
L548: ( ( sin ) . ( C36 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) < ( ( sin ) . C37 ) by L547 , L60;
thus L549: ( ( sin ) . C36 ) < ( ( sin ) . C37 ) by L548 , L60;
end;
thus L550: thesis by L542 , RFUNCT_2:20;
end;
L551: S1[ ( 0 ) ] by COMPTRIG:23;
L552: (for R3 being  integer number holds S1[ R3 ]) from INT_1:sch 4(L551 , L529);
thus L553: thesis by L552;
end;
theorem
L554: (for R3 being  integer number holds ( ( sin ) | [. ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  decreasing)
proof
let R3 being  integer number;
defpred S2[ Integer ] means ( ( sin ) | [. ( ( ( PI ) / 2 ) + H1($1) ) , ( ( ( 3 / 2 ) * ( PI ) ) + H1($1) ) .] ) is  decreasing;
L555: (for R3 being  integer number holds (S2[ R3 ] implies (S2[ ( R3 - 1 ) ] & S2[ ( R3 + 1 ) ])))
proof
let R3 being  integer number;
assume that
L556: S2[ R3 ];
set D31 = [. ( ( ( PI ) / 2 ) + H1(( ( R3 - 1 ) + 1 )) ) , ( ( ( 3 / 2 ) * ( PI ) ) + H1(( ( R3 - 1 ) + 1 )) ) .];
thus L557: S2[ ( R3 - 1 ) ]
proof
set D32 = [. ( ( ( PI ) / 2 ) + H1(( R3 - 1 )) ) , ( ( ( 3 / 2 ) * ( PI ) ) + H1(( R3 - 1 )) ) .];
L558:
now
let C38 , C39 being (Element of ( REAL ));
assume L559: (C38 in ( D32 /\ ( dom ( sin ) ) ) & C39 in ( D32 /\ ( dom ( sin ) ) ));
L560: (( C38 + ( 2 * ( PI ) ) ) in ( D31 /\ ( dom ( sin ) ) ) & ( C39 + ( 2 * ( PI ) ) ) in ( D31 /\ ( dom ( sin ) ) )) by L559 , L511 , SIN_COS:24;
assume L561: C38 < C39;
L562: ( C38 + ( 2 * ( PI ) ) ) < ( C39 + ( 2 * ( PI ) ) ) by L561 , XREAL_1:6;
L563: ( ( sin ) . ( C38 + ( 2 * ( PI ) ) ) ) > ( ( sin ) . ( C39 + ( ( 2 * ( PI ) ) * 1 ) ) ) by L562 , L556 , L560 , RFUNCT_2:21;
L564: ( ( sin ) . ( C38 + ( ( 2 * ( PI ) ) * 1 ) ) ) > ( ( sin ) . C39 ) by L563 , L60;
thus L565: ( ( sin ) . C38 ) > ( ( sin ) . C39 ) by L564 , L60;
end;
thus L566: thesis by L558 , RFUNCT_2:21;
end;

set D33 = [. ( ( ( PI ) / 2 ) + H1(( R3 + 1 )) ) , ( ( ( 3 / 2 ) * ( PI ) ) + H1(( R3 + 1 )) ) .];
L567: D31 = [. ( ( ( PI ) / 2 ) + H1(( ( R3 + 1 ) - 1 )) ) , ( ( ( 3 / 2 ) * ( PI ) ) + H1(( ( R3 + 1 ) - 1 )) ) .];
L568:
now
let C40 , C41 being (Element of ( REAL ));
assume L569: (C40 in ( D33 /\ ( dom ( sin ) ) ) & C41 in ( D33 /\ ( dom ( sin ) ) ));
L570: (( C40 - ( 2 * ( PI ) ) ) in ( D31 /\ ( dom ( sin ) ) ) & ( C41 - ( 2 * ( PI ) ) ) in ( D31 /\ ( dom ( sin ) ) )) by L569 , L567 , L523 , SIN_COS:24;
assume L571: C40 < C41;
L572: ( C40 - ( 2 * ( PI ) ) ) < ( C41 - ( 2 * ( PI ) ) ) by L571 , XREAL_1:9;
L573: ( ( sin ) . ( C40 - ( 2 * ( PI ) ) ) ) > ( ( sin ) . ( C41 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) by L572 , L556 , L570 , RFUNCT_2:21;
L574: ( ( sin ) . ( C40 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) > ( ( sin ) . C41 ) by L573 , L60;
thus L575: ( ( sin ) . C40 ) > ( ( sin ) . C41 ) by L574 , L60;
end;
thus L576: thesis by L568 , RFUNCT_2:21;
end;
L577: S2[ ( 0 ) ] by COMPTRIG:24;
L578: (for R3 being  integer number holds S2[ R3 ]) from INT_1:sch 4(L577 , L555);
thus L579: thesis by L578;
end;
theorem
L580: (for R3 being  integer number holds ( ( cos ) | [. ( ( 2 * ( PI ) ) * R3 ) , ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  decreasing)
proof
let R3 being  integer number;
defpred S3[ Integer ] means ( ( cos ) | [. H1($1) , ( ( PI ) + H1($1) ) .] ) is  decreasing;
L581: (for R3 being  integer number holds (S3[ R3 ] implies (S3[ ( R3 - 1 ) ] & S3[ ( R3 + 1 ) ])))
proof
let R3 being  integer number;
assume that
L582: S3[ R3 ];
set D34 = [. ( ( 0 ) + H1(( ( R3 - 1 ) + 1 )) ) , ( ( PI ) + H1(( ( R3 - 1 ) + 1 )) ) .];
thus L583: S3[ ( R3 - 1 ) ]
proof
set D35 = [. H1(( R3 - 1 )) , ( ( PI ) + H1(( R3 - 1 )) ) .];
L584: D35 = [. ( ( 0 ) + H1(( R3 - 1 )) ) , ( ( PI ) + H1(( R3 - 1 )) ) .];
L585:
now
let C42 , C43 being (Element of ( REAL ));
assume L586: (C42 in ( D35 /\ ( dom ( cos ) ) ) & C43 in ( D35 /\ ( dom ( cos ) ) ));
L587: (( C42 + ( 2 * ( PI ) ) ) in ( D34 /\ ( dom ( cos ) ) ) & ( C43 + ( 2 * ( PI ) ) ) in ( D34 /\ ( dom ( cos ) ) )) by L586 , L584 , L511 , SIN_COS:24;
assume L588: C42 < C43;
L589: ( C42 + ( 2 * ( PI ) ) ) < ( C43 + ( 2 * ( PI ) ) ) by L588 , XREAL_1:6;
L590: ( ( cos ) . ( C42 + ( 2 * ( PI ) ) ) ) > ( ( cos ) . ( C43 + ( ( 2 * ( PI ) ) * 1 ) ) ) by L589 , L582 , L587 , RFUNCT_2:21;
L591: ( ( cos ) . ( C42 + ( ( 2 * ( PI ) ) * 1 ) ) ) > ( ( cos ) . C43 ) by L590 , L65;
thus L592: ( ( cos ) . C42 ) > ( ( cos ) . C43 ) by L591 , L65;
end;
thus L593: thesis by L585 , RFUNCT_2:21;
end;

set D36 = [. H1(( R3 + 1 )) , ( ( PI ) + H1(( R3 + 1 )) ) .];
L594: (D36 = [. ( ( 0 ) + H1(( R3 + 1 )) ) , ( ( PI ) + H1(( R3 + 1 )) ) .] & D34 = [. H1(( ( R3 + 1 ) - 1 )) , ( ( PI ) + H1(( ( R3 + 1 ) - 1 )) ) .]);
L595:
now
let C44 , C45 being (Element of ( REAL ));
assume L596: (C44 in ( D36 /\ ( dom ( cos ) ) ) & C45 in ( D36 /\ ( dom ( cos ) ) ));
L597: (( C44 - ( 2 * ( PI ) ) ) in ( D34 /\ ( dom ( cos ) ) ) & ( C45 - ( 2 * ( PI ) ) ) in ( D34 /\ ( dom ( cos ) ) )) by L596 , L594 , L523 , SIN_COS:24;
assume L598: C44 < C45;
L599: ( C44 - ( 2 * ( PI ) ) ) < ( C45 - ( 2 * ( PI ) ) ) by L598 , XREAL_1:9;
L600: ( ( cos ) . ( C44 - ( 2 * ( PI ) ) ) ) > ( ( cos ) . ( C45 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) by L599 , L582 , L597 , RFUNCT_2:21;
L601: ( ( cos ) . ( C44 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) > ( ( cos ) . C45 ) by L600 , L65;
thus L602: ( ( cos ) . C44 ) > ( ( cos ) . C45 ) by L601 , L65;
end;
thus L603: thesis by L595 , RFUNCT_2:21;
end;
L604: S3[ ( 0 ) ] by COMPTRIG:25;
L605: (for R3 being  integer number holds S3[ R3 ]) from INT_1:sch 4(L604 , L581);
thus L606: thesis by L605;
end;
theorem
L607: (for R3 being  integer number holds ( ( cos ) | [. ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  increasing)
proof
let R3 being  integer number;
defpred S4[ Integer ] means ( ( cos ) | [. ( ( PI ) + H1($1) ) , ( ( 2 * ( PI ) ) + H1($1) ) .] ) is  increasing;
L608: (for R3 being  integer number holds (S4[ R3 ] implies (S4[ ( R3 - 1 ) ] & S4[ ( R3 + 1 ) ])))
proof
let R3 being  integer number;
assume that
L609: S4[ R3 ];
set D37 = [. ( ( PI ) + H1(( ( R3 - 1 ) + 1 )) ) , ( ( 2 * ( PI ) ) + H1(( ( R3 - 1 ) + 1 )) ) .];
thus L610: S4[ ( R3 - 1 ) ]
proof
set D38 = [. ( ( PI ) + H1(( R3 - 1 )) ) , ( ( 2 * ( PI ) ) + H1(( R3 - 1 )) ) .];
L611:
now
let C46 , C47 being (Element of ( REAL ));
assume L612: (C46 in ( D38 /\ ( dom ( cos ) ) ) & C47 in ( D38 /\ ( dom ( cos ) ) ));
L613: (( C46 + ( 2 * ( PI ) ) ) in ( D37 /\ ( dom ( cos ) ) ) & ( C47 + ( 2 * ( PI ) ) ) in ( D37 /\ ( dom ( cos ) ) )) by L612 , L511 , SIN_COS:24;
assume L614: C46 < C47;
L615: ( C46 + ( 2 * ( PI ) ) ) < ( C47 + ( 2 * ( PI ) ) ) by L614 , XREAL_1:6;
L616: ( ( cos ) . ( C46 + ( 2 * ( PI ) ) ) ) < ( ( cos ) . ( C47 + ( ( 2 * ( PI ) ) * 1 ) ) ) by L615 , L609 , L613 , RFUNCT_2:20;
L617: ( ( cos ) . ( C46 + ( ( 2 * ( PI ) ) * 1 ) ) ) < ( ( cos ) . C47 ) by L616 , L65;
thus L618: ( ( cos ) . C46 ) < ( ( cos ) . C47 ) by L617 , L65;
end;
thus L619: thesis by L611 , RFUNCT_2:20;
end;

set D39 = [. ( ( PI ) + H1(( R3 + 1 )) ) , ( ( 2 * ( PI ) ) + H1(( R3 + 1 )) ) .];
L620: D37 = [. ( ( PI ) + H1(( ( R3 + 1 ) - 1 )) ) , ( ( 2 * ( PI ) ) + H1(( ( R3 + 1 ) - 1 )) ) .];
L621:
now
let C48 , C49 being (Element of ( REAL ));
assume L622: (C48 in ( D39 /\ ( dom ( cos ) ) ) & C49 in ( D39 /\ ( dom ( cos ) ) ));
L623: (( C48 - ( 2 * ( PI ) ) ) in ( D37 /\ ( dom ( cos ) ) ) & ( C49 - ( 2 * ( PI ) ) ) in ( D37 /\ ( dom ( cos ) ) )) by L622 , L620 , L523 , SIN_COS:24;
assume L624: C48 < C49;
L625: ( C48 - ( 2 * ( PI ) ) ) < ( C49 - ( 2 * ( PI ) ) ) by L624 , XREAL_1:9;
L626: ( ( cos ) . ( C48 - ( 2 * ( PI ) ) ) ) < ( ( cos ) . ( C49 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) by L625 , L609 , L623 , RFUNCT_2:20;
L627: ( ( cos ) . ( C48 + ( ( 2 * ( PI ) ) * ( - 1 ) ) ) ) < ( ( cos ) . C49 ) by L626 , L65;
thus L628: ( ( cos ) . C48 ) < ( ( cos ) . C49 ) by L627 , L65;
end;
thus L629: thesis by L621 , RFUNCT_2:20;
end;
L630: S4[ ( 0 ) ] by COMPTRIG:26;
L631: (for R3 being  integer number holds S4[ R3 ]) from INT_1:sch 4(L630 , L608);
thus L632: thesis by L631;
end;
theorem
L633: (for R3 being  integer number holds ( ( sin ) | [. ( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  one-to-one)
proof
let R3 being  integer number;
set D40 = [. ( ( - ( ( PI ) / 2 ) ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) .];
L634: ( ( sin ) | D40 ) is  increasing by L528;
thus L635: thesis by L634 , FCONT_3:8;
end;
theorem
L636: (for R3 being  integer number holds ( ( sin ) | [. ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  one-to-one)
proof
let R3 being  integer number;
set D41 = [. ( ( ( PI ) / 2 ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( ( 3 / 2 ) * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) .];
L637: ( ( sin ) | D41 ) is  decreasing by L554;
thus L638: thesis by L637 , FCONT_3:8;
end;
registration
cluster ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ->  one-to-one;
coherence by L40 , L633;
cluster ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ->  one-to-one;
coherence by L41 , L636;
end;
registration
cluster ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( 0 ) .] ) ->  one-to-one;
coherence
proof
L640: ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) is  one-to-one;
thus L641: thesis by L640 , L7 , XXREAL_1:34;
end;
cluster ( ( sin ) | [. ( 0 ) , ( ( PI ) / 2 ) .] ) ->  one-to-one;
coherence
proof
L642: ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) is  one-to-one;
thus L643: thesis by L642 , L7 , XXREAL_1:34;
end;
cluster ( ( sin ) | [. ( ( PI ) / 2 ) , ( PI ) .] ) ->  one-to-one;
coherence
proof
L644: ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) is  one-to-one;
thus L645: thesis by L644 , L53 , L7 , XXREAL_1:34;
end;
cluster ( ( sin ) | [. ( PI ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ->  one-to-one;
coherence
proof
L646: ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) is  one-to-one;
thus L647: thesis by L646 , L52 , L7 , XXREAL_1:34;
end;
cluster ( ( sin ) | [. ( ( 3 / 2 ) * ( PI ) ) , ( 2 * ( PI ) ) .] ) ->  one-to-one;
coherence
proof
L648: ( ( sin ) | [. ( ( - ( ( PI ) / 2 ) ) + H1(1) ) , ( ( ( PI ) / 2 ) + H1(1) ) .] ) is  one-to-one by L633;
thus L649: thesis by L648 , L54 , L7 , XXREAL_1:34;
end;
end;
registration
cluster ( ( sin ) | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) ->  one-to-one;
coherence
proof
L651: ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) is  one-to-one;
thus L652: thesis by L651 , L7 , XXREAL_1:25;
end;
cluster ( ( sin ) | ]. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) ->  one-to-one;
coherence
proof
L653: ( ( sin ) | [. ( ( PI ) / 2 ) , ( ( 3 / 2 ) * ( PI ) ) .] ) is  one-to-one;
thus L654: thesis by L653 , L7 , XXREAL_1:25;
end;
cluster ( ( sin ) | ]. ( - ( ( PI ) / 2 ) ) , ( 0 ) .[ ) ->  one-to-one;
coherence
proof
L655: ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( 0 ) .] ) is  one-to-one;
thus L656: thesis by L655 , L7 , XXREAL_1:25;
end;
cluster ( ( sin ) | ]. ( 0 ) , ( ( PI ) / 2 ) .[ ) ->  one-to-one;
coherence
proof
L657: ( ( sin ) | [. ( 0 ) , ( ( PI ) / 2 ) .] ) is  one-to-one;
thus L658: thesis by L657 , L7 , XXREAL_1:25;
end;
cluster ( ( sin ) | ]. ( ( PI ) / 2 ) , ( PI ) .[ ) ->  one-to-one;
coherence
proof
L659: ( ( sin ) | [. ( ( PI ) / 2 ) , ( PI ) .] ) is  one-to-one;
thus L660: thesis by L659 , L7 , XXREAL_1:25;
end;
cluster ( ( sin ) | ]. ( PI ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) ->  one-to-one;
coherence
proof
L661: ( ( sin ) | [. ( PI ) , ( ( 3 / 2 ) * ( PI ) ) .] ) is  one-to-one;
thus L662: thesis by L661 , L7 , XXREAL_1:25;
end;
cluster ( ( sin ) | ]. ( ( 3 / 2 ) * ( PI ) ) , ( 2 * ( PI ) ) .[ ) ->  one-to-one;
coherence
proof
L663: ( ( sin ) | [. ( ( 3 / 2 ) * ( PI ) ) , ( 2 * ( PI ) ) .] ) is  one-to-one;
thus L664: thesis by L663 , L7 , XXREAL_1:25;
end;
end;
theorem
L666: (for R3 being  integer number holds ( ( cos ) | [. ( ( 2 * ( PI ) ) * R3 ) , ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  one-to-one)
proof
let R3 being  integer number;
set D42 = [. ( ( 2 * ( PI ) ) * R3 ) , ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) .];
L667: ( ( cos ) | D42 ) is  decreasing by L580;
thus L668: thesis by L667 , FCONT_3:8;
end;
theorem
L669: (for R3 being  integer number holds ( ( cos ) | [. ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) .] ) is  one-to-one)
proof
let R3 being  integer number;
set D43 = [. ( ( PI ) + ( ( 2 * ( PI ) ) * R3 ) ) , ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) .];
L670: ( ( cos ) | D43 ) is  increasing by L607;
thus L671: thesis by L670 , FCONT_3:8;
end;
registration
cluster ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ->  one-to-one;
coherence by L42 , L666;
cluster ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) ->  one-to-one;
coherence by L43 , L669;
end;
registration
cluster ( ( cos ) | [. ( 0 ) , ( ( PI ) / 2 ) .] ) ->  one-to-one;
coherence
proof
L673: ( ( cos ) | [. ( 0 ) , ( PI ) .] ) is  one-to-one;
thus L674: thesis by L673 , L52 , L7 , XXREAL_1:34;
end;
cluster ( ( cos ) | [. ( ( PI ) / 2 ) , ( PI ) .] ) ->  one-to-one;
coherence
proof
L675: ( ( cos ) | [. ( 0 ) , ( PI ) .] ) is  one-to-one;
thus L676: thesis by L675 , L7 , XXREAL_1:34;
end;
cluster ( ( cos ) | [. ( PI ) , ( ( 3 / 2 ) * ( PI ) ) .] ) ->  one-to-one;
coherence
proof
L677: ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) is  one-to-one;
thus L678: thesis by L677 , L55 , L7 , XXREAL_1:34;
end;
cluster ( ( cos ) | [. ( ( 3 / 2 ) * ( PI ) ) , ( 2 * ( PI ) ) .] ) ->  one-to-one;
coherence
proof
L679: ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) is  one-to-one;
thus L680: thesis by L679 , L53 , L7 , XXREAL_1:34;
end;
end;
registration
cluster ( ( cos ) | ]. ( 0 ) , ( PI ) .[ ) ->  one-to-one;
coherence
proof
L682: ( ( cos ) | [. ( 0 ) , ( PI ) .] ) is  one-to-one;
thus L683: thesis by L682 , L7 , XXREAL_1:25;
end;
cluster ( ( cos ) | ]. ( PI ) , ( 2 * ( PI ) ) .[ ) ->  one-to-one;
coherence
proof
L684: ( ( cos ) | [. ( PI ) , ( 2 * ( PI ) ) .] ) is  one-to-one;
thus L685: thesis by L684 , L7 , XXREAL_1:25;
end;
cluster ( ( cos ) | ]. ( 0 ) , ( ( PI ) / 2 ) .[ ) ->  one-to-one;
coherence
proof
L686: ( ( cos ) | [. ( 0 ) , ( ( PI ) / 2 ) .] ) is  one-to-one;
thus L687: thesis by L686 , L7 , XXREAL_1:25;
end;
cluster ( ( cos ) | ]. ( ( PI ) / 2 ) , ( PI ) .[ ) ->  one-to-one;
coherence
proof
L688: ( ( cos ) | [. ( ( PI ) / 2 ) , ( PI ) .] ) is  one-to-one;
thus L689: thesis by L688 , L7 , XXREAL_1:25;
end;
cluster ( ( cos ) | ]. ( PI ) , ( ( 3 / 2 ) * ( PI ) ) .[ ) ->  one-to-one;
coherence
proof
L690: ( ( cos ) | [. ( PI ) , ( ( 3 / 2 ) * ( PI ) ) .] ) is  one-to-one;
thus L691: thesis by L690 , L7 , XXREAL_1:25;
end;
cluster ( ( cos ) | ]. ( ( 3 / 2 ) * ( PI ) ) , ( 2 * ( PI ) ) .[ ) ->  one-to-one;
coherence
proof
L692: ( ( cos ) | [. ( ( 3 / 2 ) * ( PI ) ) , ( 2 * ( PI ) ) .] ) is  one-to-one;
thus L693: thesis by L692 , L7 , XXREAL_1:25;
end;
end;
theorem
L695: (for R1 being  real number holds (for R2 being  real number holds (for R3 being  integer number holds ((( ( 2 * ( PI ) ) * R3 ) <= R1 & R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) & ( ( 2 * ( PI ) ) * R3 ) <= R2 & R2 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) & ( sin R1 ) = ( sin R2 ) & ( cos R1 ) = ( cos R2 )) implies R1 = R2))))
proof
let R1 being  real number;
let R2 being  real number;
let R3 being  integer number;
assume that
L696: ( ( 2 * ( PI ) ) * R3 ) <= R1
and
L697: (R1 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) & ( ( 2 * ( PI ) ) * R3 ) <= R2)
and
L698: R2 < ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) )
and
L699: (( sin R1 ) = ( sin R2 ) & ( cos R1 ) = ( cos R2 ));
L700: ( cos ( R1 - R2 ) ) = ( ( ( cos R1 ) * ( cos R2 ) ) + ( ( sin R1 ) * ( sin R2 ) ) ) by COMPLEX2:3
.= 1 by L699 , SIN_COS:29;
L701: ( sin ( R1 - R2 ) ) = ( ( ( sin R1 ) * ( cos R2 ) ) - ( ( cos R1 ) * ( sin R2 ) ) ) by COMPLEX2:3
.= ( 0 ) by L699;
L702: ( cos ( R2 - R1 ) ) = ( ( ( cos R1 ) * ( cos R2 ) ) + ( ( sin R1 ) * ( sin R2 ) ) ) by COMPLEX2:3
.= 1 by L699 , SIN_COS:29;
L703: ( sin ( R2 - R1 ) ) = ( ( ( sin R2 ) * ( cos R1 ) ) - ( ( cos R2 ) * ( sin R1 ) ) ) by COMPLEX2:3
.= ( 0 ) by L699;
per cases  by XXREAL_0:1;
suppose L704: R1 > R2;

L705: ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) < ( ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) + R2 ) by L697 , XREAL_1:8;
L706: ( ( R1 + ( ( 2 * ( PI ) ) * R3 ) ) - ( ( 2 * ( PI ) ) * R3 ) ) < ( ( ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) + R2 ) - ( ( 2 * ( PI ) ) * R3 ) ) by L705 , XREAL_1:9;
L707: R1 < ( ( 2 * ( PI ) ) + R2 ) by L706;
L708: ( R1 - R2 ) < ( 2 * ( PI ) ) by L707 , XREAL_1:19;
L709: R1 > ( R2 + ( 0 ) ) by L704;
L710: ( 0 ) <= ( R1 - R2 ) by L709 , XREAL_1:20;
L711: (( R1 - R2 ) = ( 0 ) or ( R1 - R2 ) = ( PI )) by L710 , L701 , L708 , COMPTRIG:17;
thus L712: thesis by L711 , L700 , SIN_COS:77;
end;
suppose L713: R1 < R2;

L714: ( R2 + ( ( 2 * ( PI ) ) * R3 ) ) < ( ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) + R1 ) by L696 , L698 , XREAL_1:8;
L715: ( ( R2 + ( ( 2 * ( PI ) ) * R3 ) ) - ( ( 2 * ( PI ) ) * R3 ) ) < ( ( ( ( 2 * ( PI ) ) + ( ( 2 * ( PI ) ) * R3 ) ) + R1 ) - ( ( 2 * ( PI ) ) * R3 ) ) by L714 , XREAL_1:9;
L716: R2 < ( ( 2 * ( PI ) ) + R1 ) by L715;
L717: ( R2 - R1 ) < ( 2 * ( PI ) ) by L716 , XREAL_1:19;
L718: R2 > ( R1 + ( 0 ) ) by L713;
L719: ( 0 ) <= ( R2 - R1 ) by L718 , XREAL_1:20;
L720: (( R2 - R1 ) = ( 0 ) or ( R2 - R1 ) = ( PI )) by L719 , L703 , L717 , COMPTRIG:17;
thus L721: thesis by L720 , L702 , SIN_COS:77;
end;
suppose L722: R1 = R2;

thus L723: thesis by L722;
end;
end;
begin
definition
func arcsin -> (PartFunc of ( REAL ) , ( REAL )) equals 
( ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) " );
coherence;
end;
definition
let C50 being set;
func arcsin C50 equals 
( ( arcsin ) . C50 );
coherence;
end;
definition
let C51 being set;
redefine func arcsin C51 -> Real;

coherence;
end;
L728: ( (( arcsin ) qua Function) " ) = ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) by FUNCT_1:43;
theorem
L729: ( rng ( arcsin ) ) = [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .]
proof
L730: ( dom ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) = [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by RELAT_1:62 , SIN_COS:24;
thus L731: thesis by L730 , FUNCT_1:33;
end;
registration
cluster ( arcsin ) ->  one-to-one;
coherence;
end;
theorem
L733: ( dom ( arcsin ) ) = [. ( - 1 ) , 1 .] by COMPTRIG:30 , FUNCT_1:33;
theorem
L734: ( (( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) qua Function) * ( arcsin ) ) = ( id [. ( - 1 ) , 1 .] ) by COMPTRIG:30 , FUNCT_1:39;
theorem
L735: ( ( arcsin ) * ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) = ( id [. ( - 1 ) , 1 .] ) by COMPTRIG:30 , FUNCT_1:39;
theorem
L736: ( ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) * ( arcsin ) ) = ( id [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) by L728 , L729 , FUNCT_1:39;
theorem
L737: ( (( arcsin ) qua Function) * ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) = ( id [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) by L728 , L729 , FUNCT_1:39;
theorem
L738: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( sin ( arcsin R1 ) ) = R1))
proof
let R1 being  real number;
assume L739: (( - 1 ) <= R1 & R1 <= 1);
L740: R1 in [. ( - 1 ) , 1 .] by L739 , XXREAL_1:1;
L741: ( ( arcsin ) . R1 ) in [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by L740 , L729 , L733 , FUNCT_1:def 3;
thus L742: ( sin ( arcsin R1 ) ) = ( ( sin ) . ( ( arcsin ) . R1 ) ) by SIN_COS:def 17
.= ( (( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) qua Function) . ( ( arcsin ) . R1 ) ) by L741 , FUNCT_1:49
.= ( ( id [. ( - 1 ) , 1 .] ) . R1 ) by L740 , L733 , L734 , FUNCT_1:13
.= R1 by L740 , FUNCT_1:18;
end;
theorem
L743: (for R1 being  real number holds ((( - ( ( PI ) / 2 ) ) <= R1 & R1 <= ( ( PI ) / 2 )) implies ( arcsin ( sin R1 ) ) = R1))
proof
let R1 being  real number;
L744: ( dom ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) = [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by RELAT_1:62 , SIN_COS:24;
assume L745: (( - ( ( PI ) / 2 ) ) <= R1 & R1 <= ( ( PI ) / 2 ));
L746: R1 in [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by L745 , XXREAL_1:1;
thus L747: ( arcsin ( sin R1 ) ) = ( ( arcsin ) . ( ( sin ) . R1 ) ) by SIN_COS:def 17
.= ( ( arcsin ) . ( ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) . R1 ) ) by L746 , FUNCT_1:49
.= ( ( id [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) . R1 ) by L746 , L744 , L736 , FUNCT_1:13
.= R1 by L746 , FUNCT_1:18;
end;
theorem
L748: ( arcsin ( - 1 ) ) = ( - ( ( PI ) / 2 ) ) by L57 , L743;
theorem
L749: ( arcsin ( 0 ) ) = ( 0 ) by L743 , SIN_COS:31;
theorem
L750: ( arcsin 1 ) = ( ( PI ) / 2 ) by L743 , SIN_COS:77;
theorem
L751: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1 & ( arcsin R1 ) = ( - ( ( PI ) / 2 ) )) implies R1 = ( - 1 ))) by L57 , L738;
theorem
L752: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1 & ( arcsin R1 ) = ( 0 )) implies R1 = ( 0 ))) by L738 , SIN_COS:31;
theorem
L753: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1 & ( arcsin R1 ) = ( ( PI ) / 2 )) implies R1 = 1)) by L738 , SIN_COS:77;
theorem
L754: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies (( - ( ( PI ) / 2 ) ) <= ( arcsin R1 ) & ( arcsin R1 ) <= ( ( PI ) / 2 ))))
proof
let R1 being  real number;
assume L755: (( - 1 ) <= R1 & R1 <= 1);
L756: R1 in [. ( - 1 ) , 1 .] by L755 , XXREAL_1:1;
L757: ( ( arcsin ) . R1 ) in ( rng ( arcsin ) ) by L756 , L733 , FUNCT_1:def 3;
thus L758: thesis by L757 , L729 , XXREAL_1:1;
end;
theorem
L759: (for R1 being  real number holds ((( - 1 ) < R1 & R1 < 1) implies (( - ( ( PI ) / 2 ) ) < ( arcsin R1 ) & ( arcsin R1 ) < ( ( PI ) / 2 ))))
proof
let R1 being  real number;
assume L760: (( - 1 ) < R1 & R1 < 1);
L761: (( - ( ( PI ) / 2 ) ) <= ( arcsin R1 ) & ( arcsin R1 ) <= ( ( PI ) / 2 )) by L760 , L754;
L762: ((( - ( ( PI ) / 2 ) ) < ( arcsin R1 ) & ( arcsin R1 ) < ( ( PI ) / 2 )) or ( - ( ( PI ) / 2 ) ) = ( arcsin R1 ) or ( arcsin R1 ) = ( ( PI ) / 2 )) by L761 , XXREAL_0:1;
thus L763: thesis by L762 , L760 , L57 , L738 , SIN_COS:77;
end;
theorem
L764: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( arcsin R1 ) = ( - ( arcsin ( - R1 ) ) )))
proof
let R1 being  real number;
assume L765: (( - 1 ) <= R1 & R1 <= 1);
L766: (( - ( - 1 ) ) >= ( - R1 ) & ( - R1 ) >= ( - 1 )) by L765 , XREAL_1:24;
L767: ( arcsin ( - R1 ) ) <= ( ( PI ) / 2 ) by L766 , L754;
L768: ( - ( ( PI ) / 2 ) ) <= ( - ( arcsin ( - R1 ) ) ) by L767 , XREAL_1:24;
L769: ( - ( ( PI ) / 2 ) ) <= ( arcsin ( - R1 ) ) by L766 , L754;
L770: ( - ( arcsin ( - R1 ) ) ) <= ( - ( - ( ( PI ) / 2 ) ) ) by L769 , XREAL_1:24;
L771: R1 = ( ( 0 ) - ( 1 * ( - R1 ) ) )
.= ( ( ( sin ( 0 ) ) * ( cos ( arcsin ( - R1 ) ) ) ) - ( ( cos ( 0 ) ) * ( sin ( arcsin ( - R1 ) ) ) ) ) by L766 , L738 , SIN_COS:31
.= ( sin ( ( 0 ) - ( arcsin ( - R1 ) ) ) ) by COMPLEX2:3;
thus L772: thesis by L771 , L768 , L770 , L743;
end;
theorem
L773: (for R1 being  real number holds (for R2 being  real number holds ((( 0 ) <= R2 & ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1) implies ( cos ( arcsin R1 ) ) = R2)))
proof
let R1 being  real number;
let R2 being  real number;
set D44 = ( arcsin R1 );
assume that
L774: ( 0 ) <= R2
and
L775: ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1;
L776: (( - 1 ) <= R1 & R1 <= 1) by L775 , L44;
L777: (( - ( ( PI ) / 2 ) ) <= D44 & D44 <= ( ( PI ) / 2 )) by L776 , L754;
L778: D44 in [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by L777 , XXREAL_1:1;
L779: ( ( ( ( sin ) . D44 ) ^2 ) + ( ( ( cos ) . D44 ) ^2 ) ) = 1 by SIN_COS:28;
L780: ( ( ( cos ) . D44 ) ^2 ) = ( 1 - ( ( ( sin ) . D44 ) ^2 ) ) by L779
.= ( 1 - ( ( sin D44 ) ^2 ) ) by SIN_COS:def 17
.= ( 1 - ( R1 ^2 ) ) by L776 , L738;
L781: (( ( cos ) . D44 ) = R2 or ( ( cos ) . D44 ) = ( - R2 )) by L780 , L775 , SQUARE_1:40;
L782: (( - ( - ( - R2 ) ) ) < ( 0 ) or R2 = ( 0 )) by L774;
thus L783: thesis by L782 , L781 , L778 , COMPTRIG:12 , SIN_COS:def 19;
end;
theorem
L784: (for R1 being  real number holds (for R2 being  real number holds ((R2 <= ( 0 ) & ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1) implies ( cos ( arcsin R1 ) ) = ( - R2 ))))
proof
let R1 being  real number;
let R2 being  real number;
set D45 = ( arcsin R1 );
assume that
L785: R2 <= ( 0 )
and
L786: ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1;
L787: (( - 1 ) <= R1 & R1 <= 1) by L786 , L44;
L788: (( - ( ( PI ) / 2 ) ) <= D45 & D45 <= ( ( PI ) / 2 )) by L787 , L754;
L789: D45 in [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by L788 , XXREAL_1:1;
L790: ( ( ( ( sin ) . D45 ) ^2 ) + ( ( ( cos ) . D45 ) ^2 ) ) = 1 by SIN_COS:28;
L791: ( ( ( cos ) . D45 ) ^2 ) = ( 1 - ( ( ( sin ) . D45 ) ^2 ) ) by L790
.= ( 1 - ( ( sin D45 ) ^2 ) ) by SIN_COS:def 17
.= ( 1 - ( R1 ^2 ) ) by L787 , L738;
L792: (( ( cos ) . D45 ) = R2 or ( ( cos ) . D45 ) = ( - R2 )) by L791 , L786 , SQUARE_1:40;
L793: (( 0 ) > R2 or R2 = ( 0 )) by L785;
thus L794: thesis by L793 , L792 , L789 , COMPTRIG:12 , SIN_COS:def 19;
end;
theorem
L795: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( cos ( arcsin R1 ) ) = ( sqrt ( 1 - ( R1 ^2 ) ) )))
proof
let R1 being  real number;
set D46 = ( sqrt ( 1 - ( R1 ^2 ) ) );
assume L796: (( - 1 ) <= R1 & R1 <= 1);
L797: ( ( R1 ^2 ) + ( 0 ) ) <= ( 1 ^2 ) by L796 , SQUARE_1:49;
L798: ( 0 ) <= ( 1 - ( R1 ^2 ) ) by L797 , XREAL_1:19;
L799: (( 0 ) <= D46 & ( ( R1 ^2 ) + ( D46 ^2 ) ) = ( ( R1 ^2 ) + ( 1 - ( R1 ^2 ) ) )) by L798 , SQUARE_1:def 2;
thus L800: thesis by L799 , L773;
end;
theorem
L801: ( ( arcsin ) | [. ( - 1 ) , 1 .] ) is  increasing
proof
set D47 = ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] );
L802: (( D47 .: [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) = [. ( - 1 ) , 1 .] & ( ( ( D47 | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) " ) | ( D47 .: [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) is  increasing) by L301 , COMPTRIG:23 , FCONT_3:9 , RELAT_1:129;
thus L803: thesis by L802 , RELAT_1:72;
end;
theorem
L804: (for R1 being  real number holds (( arcsin ) is_differentiable_on ]. ( - 1 ) , 1 .[ & ((( - 1 ) < R1 & R1 < 1) implies ( diff (( arcsin ) , R1) ) = ( 1 / ( sqrt ( 1 - ( R1 ^2 ) ) ) ))))
proof
let R1 being  real number;
set D48 = ( ( arcsin ) | ]. ( - 1 ) , 1 .[ );
set D49 = ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] );
set D50 = ( ( sin ) | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ );
L805: ( dom D50 ) = ( ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ /\ ( REAL ) ) by RELAT_1:61 , SIN_COS:24
.= ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ by XBOOLE_1:28;
set D51 = ( ( arcsin ) . R1 );
set D52 = ( sqrt ( 1 - ( R1 ^2 ) ) );
L806: ]. ( - 1 ) , 1 .[ c= ( dom ( arcsin ) ) by L733 , XXREAL_1:25;
L807: ( sin ) is_differentiable_on ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ by FDIFF_1:26 , SIN_COS:68;
L808: D50 is_differentiable_on ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ by L807 , FDIFF_2:16;
L809:
now
let C52 being Real;
assume that
L810: C52 in ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[;
L811: ( diff (D50 , C52) ) = ( ( D50 `| ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) . C52 ) by L808 , L810 , FDIFF_1:def 7
.= ( ( ( sin ) `| ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) . C52 ) by L807 , FDIFF_2:16
.= ( diff (( sin ) , C52) ) by L807 , L810 , FDIFF_1:def 7
.= ( ( cos ) . C52 ) by SIN_COS:68;
thus L812: ( 0 ) < ( diff (D50 , C52) ) by L811 , L810 , COMPTRIG:11;
end;
L813: ( D50 " ) = ( ( D49 | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) " ) by RELAT_1:74 , XXREAL_1:25
.= ( ( D49 " ) | ( D49 .: ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) ) by RFUNCT_2:17
.= D48 by L302 , RELAT_1:129 , XXREAL_1:25;
L814: (( D50 | ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) = D50 & ( dom ( D50 " ) ) = ]. ( - 1 ) , 1 .[) by L813 , L733 , RELAT_1:62 , RELAT_1:72 , XXREAL_1:25;
L815: D48 is_differentiable_on ]. ( - 1 ) , 1 .[ by L814 , L813 , L808 , L805 , L809 , FDIFF_2:48;
L816: (for B4 being Real holds (B4 in ]. ( - 1 ) , 1 .[ implies D48 is_differentiable_in B4)) by L815 , FDIFF_1:9;
thus L817: ( arcsin ) is_differentiable_on ]. ( - 1 ) , 1 .[ by L816 , L806 , FDIFF_1:def 6;
assume L818: (( - 1 ) < R1 & R1 < 1);
L819: R1 in ]. ( - 1 ) , 1 .[ by L818 , XXREAL_1:4;
L820: ( D48 . R1 ) = D51 by L819 , FUNCT_1:49;
L821: D51 = ( arcsin R1 );
L822: (( - ( ( PI ) / 2 ) ) < D51 & D51 < ( ( PI ) / 2 )) by L821 , L818 , L759;
L823: D51 in ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ by L822 , XXREAL_1:4;
L824: ( diff (D50 , D51) ) = ( ( D50 `| ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) . D51 ) by L823 , L808 , FDIFF_1:def 7
.= ( ( ( sin ) `| ]. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .[ ) . D51 ) by L807 , FDIFF_2:16
.= ( diff (( sin ) , D51) ) by L807 , L823 , FDIFF_1:def 7
.= ( ( cos ) . D51 ) by SIN_COS:68
.= ( cos ( arcsin R1 ) ) by SIN_COS:def 19
.= D52 by L818 , L795;
thus L825: ( diff (( arcsin ) , R1) ) = ( ( ( arcsin ) `| ]. ( - 1 ) , 1 .[ ) . R1 ) by L817 , L819 , FDIFF_1:def 7
.= ( ( D48 `| ]. ( - 1 ) , 1 .[ ) . R1 ) by L817 , FDIFF_2:16
.= ( diff (D48 , R1) ) by L815 , L819 , FDIFF_1:def 7
.= ( 1 / D52 ) by L813 , L814 , L808 , L805 , L809 , L819 , L820 , L824 , FDIFF_2:48;
end;
theorem
L826: ( ( arcsin ) | [. ( - 1 ) , 1 .] ) is  continuous
proof
set D53 = ( ( sin ) | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] );
L827: ( dom D53 ) = [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] by RELAT_1:62 , SIN_COS:24;
L828: (( D53 | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) = D53 & ( ( ( D53 | [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) " ) | ( D53 .: [. ( - ( ( PI ) / 2 ) ) , ( ( PI ) / 2 ) .] ) ) is  continuous) by L827 , COMPTRIG:23 , FCONT_1:47 , RELAT_1:73;
thus L829: thesis by L828 , COMPTRIG:30 , RELAT_1:115;
end;
begin
definition
func arccos -> (PartFunc of ( REAL ) , ( REAL )) equals 
( ( ( cos ) | [. ( 0 ) , ( PI ) .] ) " );
coherence;
end;
definition
let C53 being set;
func arccos C53 equals 
( ( arccos ) . C53 );
coherence;
end;
definition
let C54 being set;
redefine func arccos C54 -> Real;

coherence;
end;
L833: ( (( arccos ) qua Function) " ) = ( ( cos ) | [. ( 0 ) , ( PI ) .] ) by FUNCT_1:43;
theorem
L834: ( rng ( arccos ) ) = [. ( 0 ) , ( PI ) .]
proof
L835: ( dom ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) = [. ( 0 ) , ( PI ) .] by RELAT_1:62 , SIN_COS:24;
thus L836: thesis by L835 , FUNCT_1:33;
end;
registration
cluster ( arccos ) ->  one-to-one;
coherence;
end;
theorem
L838: ( dom ( arccos ) ) = [. ( - 1 ) , 1 .] by COMPTRIG:32 , FUNCT_1:33;
theorem
L839: ( (( ( cos ) | [. ( 0 ) , ( PI ) .] ) qua Function) * ( arccos ) ) = ( id [. ( - 1 ) , 1 .] ) by COMPTRIG:32 , FUNCT_1:39;
theorem
L840: ( ( arccos ) * ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) = ( id [. ( - 1 ) , 1 .] ) by COMPTRIG:32 , FUNCT_1:39;
theorem
L841: ( ( ( cos ) | [. ( 0 ) , ( PI ) .] ) * ( arccos ) ) = ( id [. ( 0 ) , ( PI ) .] ) by L833 , L834 , FUNCT_1:39;
theorem
L842: ( (( arccos ) qua Function) * ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) = ( id [. ( 0 ) , ( PI ) .] ) by L833 , L834 , FUNCT_1:39;
theorem
L843: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( cos ( arccos R1 ) ) = R1))
proof
let R1 being  real number;
assume L844: (( - 1 ) <= R1 & R1 <= 1);
L845: R1 in [. ( - 1 ) , 1 .] by L844 , XXREAL_1:1;
L846: ( ( arccos ) . R1 ) in [. ( 0 ) , ( PI ) .] by L845 , L834 , L838 , FUNCT_1:def 3;
thus L847: ( cos ( arccos R1 ) ) = ( ( cos ) . ( ( arccos ) . R1 ) ) by SIN_COS:def 19
.= ( (( ( cos ) | [. ( 0 ) , ( PI ) .] ) qua Function) . ( ( arccos ) . R1 ) ) by L846 , FUNCT_1:49
.= ( ( id [. ( - 1 ) , 1 .] ) . R1 ) by L845 , L838 , L839 , FUNCT_1:13
.= R1 by L845 , FUNCT_1:18;
end;
theorem
L848: (for R1 being  real number holds ((( 0 ) <= R1 & R1 <= ( PI )) implies ( arccos ( cos R1 ) ) = R1))
proof
let R1 being  real number;
L849: ( dom ( ( cos ) | [. ( 0 ) , ( PI ) .] ) ) = [. ( 0 ) , ( PI ) .] by RELAT_1:62 , SIN_COS:24;
assume L850: (( 0 ) <= R1 & R1 <= ( PI ));
L851: R1 in [. ( 0 ) , ( PI ) .] by L850 , XXREAL_1:1;
thus L852: ( arccos ( cos R1 ) ) = ( ( arccos ) . ( ( cos ) . R1 ) ) by SIN_COS:def 19
.= ( ( arccos ) . ( ( ( cos ) | [. ( 0 ) , ( PI ) .] ) . R1 ) ) by L851 , FUNCT_1:49
.= ( ( id [. ( 0 ) , ( PI ) .] ) . R1 ) by L851 , L849 , L841 , FUNCT_1:13
.= R1 by L851 , FUNCT_1:18;
end;
theorem
L853: ( arccos ( - 1 ) ) = ( PI ) by L848 , SIN_COS:77;
theorem
L854: ( arccos ( 0 ) ) = ( ( PI ) / 2 ) by L52 , L848 , SIN_COS:77;
theorem
L855: ( arccos 1 ) = ( 0 ) by L848 , SIN_COS:31;
theorem
L856: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1 & ( arccos R1 ) = ( 0 )) implies R1 = 1)) by L843 , SIN_COS:31;
theorem
L857: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1 & ( arccos R1 ) = ( ( PI ) / 2 )) implies R1 = ( 0 ))) by L843 , SIN_COS:77;
theorem
L858: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1 & ( arccos R1 ) = ( PI )) implies R1 = ( - 1 ))) by L843 , SIN_COS:77;
theorem
L859: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies (( 0 ) <= ( arccos R1 ) & ( arccos R1 ) <= ( PI ))))
proof
let R1 being  real number;
assume L860: (( - 1 ) <= R1 & R1 <= 1);
L861: R1 in [. ( - 1 ) , 1 .] by L860 , XXREAL_1:1;
L862: ( ( arccos ) . R1 ) in ( rng ( arccos ) ) by L861 , L838 , FUNCT_1:def 3;
thus L863: thesis by L862 , L834 , XXREAL_1:1;
end;
theorem
L864: (for R1 being  real number holds ((( - 1 ) < R1 & R1 < 1) implies (( 0 ) < ( arccos R1 ) & ( arccos R1 ) < ( PI ))))
proof
let R1 being  real number;
assume L865: (( - 1 ) < R1 & R1 < 1);
L866: ( arccos R1 ) <= ( PI ) by L865 , L859;
L867: ((( 0 ) < ( arccos R1 ) & ( arccos R1 ) < ( PI )) or ( 0 ) = ( arccos R1 ) or ( arccos R1 ) = ( PI )) by L866 , L865 , L859 , XXREAL_0:1;
thus L868: thesis by L867 , L865 , L843 , SIN_COS:31 , SIN_COS:77;
end;
theorem
L869: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( arccos R1 ) = ( ( PI ) - ( arccos ( - R1 ) ) )))
proof
let R1 being  real number;
assume L870: (( - 1 ) <= R1 & R1 <= 1);
L871: (( - ( - 1 ) ) >= ( - R1 ) & ( - R1 ) >= ( - 1 )) by L870 , XREAL_1:24;
L872: ( ( 0 ) + ( arccos ( - R1 ) ) ) <= ( PI ) by L871 , L859;
L873: ( 0 ) <= ( ( PI ) - ( arccos ( - R1 ) ) ) by L872 , XREAL_1:19;
L874: ( 0 ) <= ( arccos ( - R1 ) ) by L871 , L859;
L875: ( ( PI ) + ( 0 ) ) <= ( ( PI ) + ( arccos ( - R1 ) ) ) by L874 , XREAL_1:6;
L876: ( ( PI ) - ( arccos ( - R1 ) ) ) <= ( PI ) by L875 , XREAL_1:20;
L877: R1 = ( ( - 1 ) * ( - R1 ) )
.= ( ( ( cos ( PI ) ) * ( cos ( arccos ( - R1 ) ) ) ) + ( ( sin ( PI ) ) * ( sin ( arccos ( - R1 ) ) ) ) ) by L871 , L843 , SIN_COS:77
.= ( cos ( ( PI ) - ( arccos ( - R1 ) ) ) ) by COMPLEX2:3;
thus L878: thesis by L877 , L873 , L876 , L848;
end;
theorem
L879: (for R1 being  real number holds (for R2 being  real number holds ((( 0 ) <= R2 & ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1) implies ( sin ( arccos R1 ) ) = R2)))
proof
let R1 being  real number;
let R2 being  real number;
set D54 = ( arccos R1 );
assume that
L880: ( 0 ) <= R2
and
L881: ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1;
L882: (( - 1 ) <= R1 & R1 <= 1) by L881 , L44;
L883: (( 0 ) <= D54 & D54 <= ( PI )) by L882 , L859;
L884: D54 in [. ( 0 ) , ( PI ) .] by L883 , XXREAL_1:1;
L885: ( ( ( ( sin ) . D54 ) ^2 ) + ( ( ( cos ) . D54 ) ^2 ) ) = 1 by SIN_COS:28;
L886: ( ( ( sin ) . D54 ) ^2 ) = ( 1 - ( ( ( cos ) . D54 ) ^2 ) ) by L885
.= ( 1 - ( ( cos D54 ) ^2 ) ) by SIN_COS:def 19
.= ( 1 - ( R1 ^2 ) ) by L882 , L843;
L887: (( ( sin ) . D54 ) = R2 or ( ( sin ) . D54 ) = ( - R2 )) by L886 , L881 , SQUARE_1:40;
L888: (( - ( - ( - R2 ) ) ) < ( 0 ) or R2 = ( 0 )) by L880;
thus L889: thesis by L888 , L887 , L884 , COMPTRIG:8 , SIN_COS:def 17;
end;
theorem
L890: (for R1 being  real number holds (for R2 being  real number holds ((R2 <= ( 0 ) & ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1) implies ( sin ( arccos R1 ) ) = ( - R2 ))))
proof
let R1 being  real number;
let R2 being  real number;
set D55 = ( arccos R1 );
assume that
L891: R2 <= ( 0 )
and
L892: ( ( R1 ^2 ) + ( R2 ^2 ) ) = 1;
L893: (( - 1 ) <= R1 & R1 <= 1) by L892 , L44;
L894: (( 0 ) <= D55 & D55 <= ( PI )) by L893 , L859;
L895: D55 in [. ( 0 ) , ( PI ) .] by L894 , XXREAL_1:1;
L896: ( ( ( ( sin ) . D55 ) ^2 ) + ( ( ( cos ) . D55 ) ^2 ) ) = 1 by SIN_COS:28;
L897: ( ( ( sin ) . D55 ) ^2 ) = ( 1 - ( ( ( cos ) . D55 ) ^2 ) ) by L896
.= ( 1 - ( ( cos D55 ) ^2 ) ) by SIN_COS:def 19
.= ( 1 - ( R1 ^2 ) ) by L893 , L843;
L898: (( ( sin ) . D55 ) = R2 or ( ( sin ) . D55 ) = ( - R2 )) by L897 , L892 , SQUARE_1:40;
L899: (( 0 ) > R2 or R2 = ( 0 )) by L891;
thus L900: thesis by L899 , L898 , L895 , COMPTRIG:8 , SIN_COS:def 17;
end;
theorem
L901: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( sin ( arccos R1 ) ) = ( sqrt ( 1 - ( R1 ^2 ) ) )))
proof
let R1 being  real number;
set D56 = ( sqrt ( 1 - ( R1 ^2 ) ) );
assume L902: (( - 1 ) <= R1 & R1 <= 1);
L903: ( ( R1 ^2 ) + ( 0 ) ) <= ( 1 ^2 ) by L902 , SQUARE_1:49;
L904: ( 0 ) <= ( 1 - ( R1 ^2 ) ) by L903 , XREAL_1:19;
L905: (( 0 ) <= D56 & ( ( R1 ^2 ) + ( D56 ^2 ) ) = ( ( R1 ^2 ) + ( 1 - ( R1 ^2 ) ) )) by L904 , SQUARE_1:def 2;
thus L906: thesis by L905 , L879;
end;
theorem
L907: ( ( arccos ) | [. ( - 1 ) , 1 .] ) is  decreasing
proof
set D57 = ( ( cos ) | [. ( 0 ) , ( PI ) .] );
L908: (( D57 .: [. ( 0 ) , ( PI ) .] ) = [. ( - 1 ) , 1 .] & ( ( ( D57 | [. ( 0 ) , ( PI ) .] ) " ) | ( D57 .: [. ( 0 ) , ( PI ) .] ) ) is  decreasing) by L406 , COMPTRIG:25 , FCONT_3:10 , RELAT_1:129;
thus L909: thesis by L908 , RELAT_1:72;
end;
theorem
L910: (for R1 being  real number holds (( arccos ) is_differentiable_on ]. ( - 1 ) , 1 .[ & ((( - 1 ) < R1 & R1 < 1) implies ( diff (( arccos ) , R1) ) = ( - ( 1 / ( sqrt ( 1 - ( R1 ^2 ) ) ) ) ))))
proof
let R1 being  real number;
set D58 = ( ( arccos ) | ]. ( - 1 ) , 1 .[ );
set D59 = ( ( cos ) | [. ( 0 ) , ( PI ) .] );
set D60 = ( ( cos ) | ]. ( 0 ) , ( PI ) .[ );
L911: ( dom D60 ) = ( ]. ( 0 ) , ( PI ) .[ /\ ( REAL ) ) by RELAT_1:61 , SIN_COS:24
.= ]. ( 0 ) , ( PI ) .[ by XBOOLE_1:28;
set D61 = ( ( arccos ) . R1 );
set D62 = ( sqrt ( 1 - ( R1 ^2 ) ) );
L912: ]. ( - 1 ) , 1 .[ c= ( dom ( arccos ) ) by L838 , XXREAL_1:25;
L913: ( cos ) is_differentiable_on ]. ( 0 ) , ( PI ) .[ by FDIFF_1:26 , SIN_COS:67;
L914: D60 is_differentiable_on ]. ( 0 ) , ( PI ) .[ by L913 , FDIFF_2:16;
L915:
now
let C55 being Real;
assume that
L916: C55 in ]. ( 0 ) , ( PI ) .[;
L917: ( - ( - ( ( sin ) . C55 ) ) ) > ( 0 ) by L916 , COMPTRIG:7;
L918: ( diff (D60 , C55) ) = ( ( D60 `| ]. ( 0 ) , ( PI ) .[ ) . C55 ) by L914 , L916 , FDIFF_1:def 7
.= ( ( ( cos ) `| ]. ( 0 ) , ( PI ) .[ ) . C55 ) by L913 , FDIFF_2:16
.= ( diff (( cos ) , C55) ) by L913 , L916 , FDIFF_1:def 7
.= ( - ( ( sin ) . C55 ) ) by SIN_COS:67;
thus L919: ( 0 ) > ( diff (D60 , C55) ) by L918 , L917;
end;
L920: ( D60 " ) = ( ( D59 | ]. ( 0 ) , ( PI ) .[ ) " ) by RELAT_1:74 , XXREAL_1:25
.= ( ( D59 " ) | ( D59 .: ]. ( 0 ) , ( PI ) .[ ) ) by RFUNCT_2:17
.= D58 by L407 , RELAT_1:129 , XXREAL_1:25;
L921: (( D60 | ]. ( 0 ) , ( PI ) .[ ) = D60 & ( dom ( D60 " ) ) = ]. ( - 1 ) , 1 .[) by L920 , L838 , RELAT_1:62 , RELAT_1:72 , XXREAL_1:25;
L922: D58 is_differentiable_on ]. ( - 1 ) , 1 .[ by L921 , L920 , L914 , L911 , L915 , FDIFF_2:48;
L923: (for B5 being Real holds (B5 in ]. ( - 1 ) , 1 .[ implies D58 is_differentiable_in B5)) by L922 , FDIFF_1:9;
thus L924: ( arccos ) is_differentiable_on ]. ( - 1 ) , 1 .[ by L923 , L912 , FDIFF_1:def 6;
assume L925: (( - 1 ) < R1 & R1 < 1);
L926: R1 in ]. ( - 1 ) , 1 .[ by L925 , XXREAL_1:4;
L927: ( D58 . R1 ) = D61 by L926 , FUNCT_1:49;
L928: D61 = ( arccos R1 );
L929: (( 0 ) < D61 & D61 < ( PI )) by L928 , L925 , L864;
L930: D61 in ]. ( 0 ) , ( PI ) .[ by L929 , XXREAL_1:4;
L931: ( diff (D60 , D61) ) = ( ( D60 `| ]. ( 0 ) , ( PI ) .[ ) . D61 ) by L930 , L914 , FDIFF_1:def 7
.= ( ( ( cos ) `| ]. ( 0 ) , ( PI ) .[ ) . D61 ) by L913 , FDIFF_2:16
.= ( diff (( cos ) , D61) ) by L913 , L930 , FDIFF_1:def 7
.= ( - ( ( sin ) . D61 ) ) by SIN_COS:67
.= ( - ( sin ( arccos R1 ) ) ) by SIN_COS:def 17
.= ( - D62 ) by L925 , L901;
thus L932: ( diff (( arccos ) , R1) ) = ( ( ( arccos ) `| ]. ( - 1 ) , 1 .[ ) . R1 ) by L924 , L926 , FDIFF_1:def 7
.= ( ( D58 `| ]. ( - 1 ) , 1 .[ ) . R1 ) by L924 , FDIFF_2:16
.= ( diff (D58 , R1) ) by L922 , L926 , FDIFF_1:def 7
.= ( 1 / ( - D62 ) ) by L920 , L921 , L914 , L911 , L915 , L926 , L927 , L931 , FDIFF_2:48
.= ( ( - 1 ) / D62 ) by XCMPLX_1:192
.= ( - ( 1 / D62 ) ) by XCMPLX_1:187;
end;
theorem
L933: ( ( arccos ) | [. ( - 1 ) , 1 .] ) is  continuous
proof
set D63 = ( ( cos ) | [. ( 0 ) , ( PI ) .] );
L934: ( dom D63 ) = [. ( 0 ) , ( PI ) .] by RELAT_1:62 , SIN_COS:24;
L935: (( D63 | [. ( 0 ) , ( PI ) .] ) = D63 & ( ( ( D63 | [. ( 0 ) , ( PI ) .] ) " ) | ( D63 .: [. ( 0 ) , ( PI ) .] ) ) is  continuous) by L934 , COMPTRIG:25 , FCONT_1:47 , RELAT_1:73;
thus L936: thesis by L935 , COMPTRIG:32 , RELAT_1:115;
end;
theorem
L937: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( ( arcsin R1 ) + ( arccos R1 ) ) = ( ( PI ) / 2 )))
proof
let R1 being  real number;
assume L938: (( - 1 ) <= R1 & R1 <= 1);
L939: ( ( - ( ( PI ) / 2 ) ) + ( ( PI ) / 2 ) ) <= ( arccos R1 ) by L938 , L859;
L940: ( - ( ( PI ) / 2 ) ) <= ( ( arccos R1 ) - ( ( PI ) / 2 ) ) by L939 , XREAL_1:19;
L941: ( - ( - ( ( PI ) / 2 ) ) ) >= ( - ( ( arccos R1 ) - ( ( PI ) / 2 ) ) ) by L940 , XREAL_1:24;
L942: ( arccos R1 ) <= ( ( ( PI ) / 2 ) + ( ( PI ) / 2 ) ) by L938 , L859;
L943: ( ( arccos R1 ) - ( ( PI ) / 2 ) ) <= ( ( PI ) / 2 ) by L942 , XREAL_1:20;
L944: ( - ( ( arccos R1 ) - ( ( PI ) / 2 ) ) ) >= ( - ( ( PI ) / 2 ) ) by L943 , XREAL_1:24;
L945: R1 = ( ( ( sin ( ( PI ) / 2 ) ) * ( cos ( arccos R1 ) ) ) - ( ( cos ( ( PI ) / 2 ) ) * ( sin ( arccos R1 ) ) ) ) by L938 , L843 , SIN_COS:77
.= ( sin ( ( ( PI ) / 2 ) - ( arccos R1 ) ) ) by COMPLEX2:3;
L946: ( arcsin R1 ) = ( ( ( PI ) / 2 ) - ( arccos R1 ) ) by L945 , L941 , L944 , L743;
thus L947: thesis by L946;
end;
theorem
L948: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( ( arccos ( - R1 ) ) - ( arcsin R1 ) ) = ( ( PI ) / 2 )))
proof
let R1 being  real number;
assume L949: (( - 1 ) <= R1 & R1 <= 1);
L950: ( ( arcsin R1 ) + ( arccos R1 ) ) = ( ( ( PI ) / 2 ) + ( 0 ) ) by L949 , L937;
L951: (( - ( - 1 ) ) >= ( - R1 ) & ( - R1 ) >= ( - 1 )) by L949 , XREAL_1:24;
L952: ( arccos ( - R1 ) ) = ( ( PI ) - ( arccos ( - ( - R1 ) ) ) ) by L951 , L869
.= ( ( arcsin R1 ) + ( ( PI ) / 2 ) ) by L950;
thus L953: thesis by L952;
end;
theorem
L954: (for R1 being  real number holds ((( - 1 ) <= R1 & R1 <= 1) implies ( ( arccos R1 ) - ( arcsin ( - R1 ) ) ) = ( ( PI ) / 2 )))
proof
let R1 being  real number;
assume L955: (( - 1 ) <= R1 & R1 <= 1);
L956: ( ( arcsin R1 ) + ( arccos R1 ) ) = ( ( ( PI ) / 2 ) + ( 0 ) ) by L955 , L937;
L957: (( - ( - 1 ) ) >= ( - R1 ) & ( - R1 ) >= ( - 1 )) by L955 , XREAL_1:24;
L958: ( arcsin ( - R1 ) ) = ( - ( arcsin ( - ( - R1 ) ) ) ) by L957 , L764
.= ( ( arccos R1 ) - ( ( PI ) / 2 ) ) by L956;
thus L959: thesis by L958;
end;
