:: Some properties of special polygonal curves
::  by Andrzej Trybulec and Yatsuka Nakamura
::
:: Received October 22, 1998
:: Copyright (c) 1998-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, NAT_1, XBOOLE_0, FINSEQ_1, ORDINAL4, PARTFUN1, XXREAL_0,
      ARYTM_3, MATRIX_1, MATRIX_2, ZFMISC_1, SUBSET_1, PRE_TOPC, EUCLID,
      REAL_1, CARD_1, ARYTM_1, RELAT_1, SUPINF_2, RLTOPSP1, METRIC_1, RELAT_2,
      CONVEX1, RCOMP_1, CONNSP_1, TARSKI, PCOMPS_1, XREAL_0, ORDINAL1, SPPOL_1,
      MCART_1, GOBOARD1, TREES_1, PSCOMP_1, TOPREAL1, SPRECT_1, SPPOL_2,
      JORDAN3, FUNCT_1, RFINSEQ, GROUP_2, GOBOARD5, GOBOARD9, TOPREAL4,
      JORDAN5D, GOBOARD2, SPRECT_2, COMPLEX1, ORDINAL2, TOPS_1, JORDAN5C,
      FINSEQ_5;
 notations TARSKI, XBOOLE_0, ENUMSET1, ZFMISC_1, SUBSET_1, ORDINAL1, NUMBERS,
      XCMPLX_0, XREAL_0, COMPLEX1, REAL_1, NAT_1, NAT_D, CARD_1, RFINSEQ,
      FUNCT_1, PARTFUN1, FINSEQ_1, FINSEQ_4, FINSEQ_5, MATRIX_1, MATRIX_2,
      SEQM_3, SEQ_4, FINSEQ_6, STRUCT_0, METRIC_1, PRE_TOPC, TOPS_1, COMPTS_1,
      CONNSP_1, PCOMPS_1, RLVECT_1, RLTOPSP1, EUCLID, TOPREAL1, TOPREAL4,
      PSCOMP_1, GOBOARD1, GOBOARD2, SPPOL_1, SPPOL_2, GOBOARD5, GOBOARD9,
      JORDAN3, JORDAN5C, JORDAN5D, SPRECT_1, SPRECT_2, XXREAL_0;
 constructors REAL_1, FINSEQ_4, RFINSEQ, NAT_D, TOPS_1, CONNSP_1, TOPS_2,
      COMPTS_1, MATRIX_2, TOPMETR, TOPREAL2, TOPREAL4, GOBOARD2, SPPOL_1,
      PSCOMP_1, GOBOARD9, JORDAN3, JORDAN5C, SPRECT_1, SPRECT_2, JORDAN5D,
      SEQ_1, GOBOARD1, PCOMPS_1, BINARITH, FUNCSDOM, CONVEX1, SEQ_4, RVSUM_1;
 registrations XBOOLE_0, RELSET_1, NUMBERS, XXREAL_0, XREAL_0, MEMBERED,
      FINSEQ_1, STRUCT_0, EUCLID, GOBOARD2, SPPOL_2, SPRECT_1, SPRECT_2,
      VALUED_0, CARD_1, FUNCT_1, SEQ_4, SPPOL_1, TOPS_1, ZFMISC_1, FINSET_1,
      JORDAN1;
 requirements REAL, NUMERALS, BOOLE, SUBSET, ARITHM;
 definitions TARSKI, RLTOPSP1, SPRECT_2, JORDAN1, TOPREAL4, XBOOLE_0, PSCOMP_1,
      SEQM_3;
 theorems FINSEQ_4, TARSKI, FINSEQ_3, FINSEQ_1, SPRECT_2, GOBOARD7, PSCOMP_1,
      SPRECT_1, TOPREAL3, SPPOL_2, NAT_1, SPPOL_1, EUCLID, ZFMISC_1, TOPREAL1,
      GOBOARD5, JORDAN5D, FINSEQ_5, FINSEQ_6, JORDAN4, JORDAN3, TOPREAL5,
      GOBRD11, GOBOARD9, TOPMETR, GOBOARD6, JORDAN1, CONNSP_1, SUBSET_1,
      GOBRD12, JORDAN5C, JORDAN6, MATRIX_2, GOBOARD1, ENUMSET1, CARD_2,
      GOBOARD2, NAT_2, ABSVALUE, GOBOARD8, PARTFUN2, FUNCT_1, XBOOLE_0,
      XBOOLE_1, XREAL_0, FINSEQ_2, XREAL_1, XXREAL_0, PARTFUN1, MATRIX_1,
      NAT_D, PRE_TOPC, RLTOPSP1, SEQM_3, SEQ_4, XTUPLE_0;
 schemes DOMAIN_1;

begin
theorem
L1: (for B1 being non  empty set holds (for B2 being non  empty (FinSequence of B1) holds (for B3 being (FinSequence of B1) holds ( ( B3 ^ B2 ) /. ( len ( B3 ^ B2 ) ) ) = ( B2 /. ( len B2 ) ))))
proof
let C1 being non  empty set;
let C2 being non  empty (FinSequence of C1);
let C3 being (FinSequence of C1);
L2: ( len C2 ) >= 1 by NAT_1:14;
L3: ( len ( C3 ^ C2 ) ) = ( ( len C3 ) + ( len C2 ) ) by FINSEQ_1:22;
thus L4: thesis by L3 , L2 , SEQ_4:136;
end;
theorem
L5: (for B4 , B5 , B6 , B7 being set holds ( Indices ( (B4 , B5) ][ (B6 , B7) ) ) = { [ 1 , 1 ] , [ 1 , 2 ] , [ 2 , 1 ] , [ 2 , 2 ] })
proof
let C4 , C5 , C6 , C7 being set;
thus L6: ( Indices ( (C4 , C5) ][ (C6 , C7) ) ) = [: ( Seg 2 ) , ( Seg 2 ) :] by MATRIX_2:3
.= ( [: { 1 } , ( Seg 2 ) :] \/ [: { 2 } , ( Seg 2 ) :] ) by FINSEQ_1:2 , ZFMISC_1:109
.= ( [: { 1 } , ( Seg 2 ) :] \/ { [ 2 , 1 ] , [ 2 , 2 ] } ) by FINSEQ_1:2 , ZFMISC_1:30
.= ( { [ 1 , 1 ] , [ 1 , 2 ] } \/ { [ 2 , 1 ] , [ 2 , 2 ] } ) by FINSEQ_1:2 , ZFMISC_1:30
.= { [ 1 , 1 ] , [ 1 , 2 ] , [ 2 , 1 ] , [ 2 , 2 ] } by ENUMSET1:5;
end;
begin
theorem
L7: (for R4 being (Element of ( NAT )) holds (for B8 , B9 being (Point of ( TOP-REAL R4 )) holds (for B10 being Real holds ((( 0 ) < B10 & B8 = ( ( ( 1 - B10 ) * B8 ) + ( B10 * B9 ) )) implies B8 = B9))))
proof
let R4 being (Element of ( NAT ));
let C8 , C9 being (Point of ( TOP-REAL R4 ));
let C10 being Real;
assume that
L8: ( 0 ) < C10
and
L9: C8 = ( ( ( 1 - C10 ) * C8 ) + ( C10 * C9 ) );
L10: ( ( ( 1 - C10 ) * C8 ) + ( C10 * C8 ) ) = ( ( ( 1 - C10 ) + C10 ) * C8 ) by EUCLID:33
.= C8 by EUCLID:29;
L11: ( C10 * C8 ) = ( ( C10 * C8 ) + ( 0. ( TOP-REAL R4 ) ) ) by EUCLID:27
.= ( ( C10 * C8 ) + ( ( ( 1 - C10 ) * C8 ) + ( - ( ( 1 - C10 ) * C8 ) ) ) ) by EUCLID:36
.= ( ( ( C10 * C9 ) + ( ( 1 - C10 ) * C8 ) ) + ( - ( ( 1 - C10 ) * C8 ) ) ) by L9 , L10 , EUCLID:26
.= ( ( C10 * C9 ) + ( ( ( 1 - C10 ) * C8 ) + ( - ( ( 1 - C10 ) * C8 ) ) ) ) by EUCLID:26
.= ( ( C10 * C9 ) + ( 0. ( TOP-REAL R4 ) ) ) by EUCLID:36
.= ( C10 * C9 ) by EUCLID:27;
thus L12: thesis by L11 , L8 , EUCLID:34;
end;
theorem
L13: (for R4 being (Element of ( NAT )) holds (for B11 , B12 being (Point of ( TOP-REAL R4 )) holds (for B13 being Real holds ((B13 < 1 & B11 = ( ( ( 1 - B13 ) * B12 ) + ( B13 * B11 ) )) implies B11 = B12))))
proof
let R4 being (Element of ( NAT ));
let C11 , C12 being (Point of ( TOP-REAL R4 ));
let C13 being Real;
assume that
L14: C13 < 1
and
L15: C11 = ( ( ( 1 - C13 ) * C12 ) + ( C13 * C11 ) );
set D1 = ( 1 - C13 );
L16: ( C13 + ( 0 ) ) < 1 by L14;
L17: ( 0 ) < ( 1 - C13 ) by L16 , XREAL_1:20;
L18: C11 = ( ( ( 1 - D1 ) * C11 ) + ( D1 * C12 ) ) by L15;
thus L19: thesis by L18 , L17 , L7;
end;
theorem
L20: (for R4 being (Element of ( NAT )) holds (for B14 , B15 being (Point of ( TOP-REAL R4 )) holds (B14 = ( ( 1 / 2 ) * ( B14 + B15 ) ) implies B14 = B15)))
proof
let R4 being (Element of ( NAT ));
let C14 , C15 being (Point of ( TOP-REAL R4 ));
assume L21: C14 = ( ( 1 / 2 ) * ( C14 + C15 ) );
L22: C14 = ( ( ( 1 - ( 1 / 2 ) ) * C14 ) + ( ( 1 / 2 ) * C15 ) ) by L21 , EUCLID:32;
thus L23: thesis by L22 , L7;
end;
theorem
L24: (for R4 being (Element of ( NAT )) holds (for B16 , B17 , B18 being (Point of ( TOP-REAL R4 )) holds ((B17 in ( LSeg (B16 , B18) ) & B18 in ( LSeg (B16 , B17) )) implies B17 = B18)))
proof
let R4 being (Element of ( NAT ));
let C16 , C17 , C18 being (Point of ( TOP-REAL R4 ));
assume L25: C17 in ( LSeg (C16 , C18) );
consider C19 being Real such that L26: C17 = ( ( ( 1 - C19 ) * C16 ) + ( C19 * C18 ) ) and L27: ( 0 ) <= C19 and L28: C19 <= 1 by L25;
assume L29: C18 in ( LSeg (C16 , C17) );
consider C20 being Real such that L30: C18 = ( ( ( 1 - C20 ) * C16 ) + ( C20 * C17 ) ) and L31: ( 0 ) <= C20 and L32: C20 <= 1 by L29;
L33: ( C19 * C20 ) <= 1 by L27 , L28 , L32 , XREAL_1:160;
L34: ( ( 1 - C20 ) + ( C20 * ( 1 - C19 ) ) ) = ( 1 - ( C20 * C19 ) );
L35: C18 = ( ( ( 1 - C20 ) * C16 ) + ( ( C20 * ( ( 1 - C19 ) * C16 ) ) + ( C20 * ( C19 * C18 ) ) ) ) by L26 , L30 , EUCLID:32
.= ( ( ( ( 1 - C20 ) * C16 ) + ( C20 * ( ( 1 - C19 ) * C16 ) ) ) + ( C20 * ( C19 * C18 ) ) ) by EUCLID:26
.= ( ( ( ( 1 - C20 ) * C16 ) + ( ( C20 * ( 1 - C19 ) ) * C16 ) ) + ( C20 * ( C19 * C18 ) ) ) by EUCLID:30
.= ( ( ( 1 - ( C20 * C19 ) ) * C16 ) + ( C20 * ( C19 * C18 ) ) ) by L34 , EUCLID:33
.= ( ( ( 1 - ( C20 * C19 ) ) * C16 ) + ( ( C20 * C19 ) * C18 ) ) by EUCLID:30;
L36: ( ( 1 - C19 ) + ( C19 * ( 1 - C20 ) ) ) = ( 1 - ( C19 * C20 ) );
L37: C17 = ( ( ( 1 - C19 ) * C16 ) + ( ( C19 * ( ( 1 - C20 ) * C16 ) ) + ( C19 * ( C20 * C17 ) ) ) ) by L26 , L30 , EUCLID:32
.= ( ( ( ( 1 - C19 ) * C16 ) + ( C19 * ( ( 1 - C20 ) * C16 ) ) ) + ( C19 * ( C20 * C17 ) ) ) by EUCLID:26
.= ( ( ( ( 1 - C19 ) * C16 ) + ( ( C19 * ( 1 - C20 ) ) * C16 ) ) + ( C19 * ( C20 * C17 ) ) ) by EUCLID:30
.= ( ( ( 1 - ( C19 * C20 ) ) * C16 ) + ( C19 * ( C20 * C17 ) ) ) by L36 , EUCLID:33
.= ( ( ( 1 - ( C19 * C20 ) ) * C16 ) + ( ( C19 * C20 ) * C17 ) ) by EUCLID:30;
per cases  by L33 , XXREAL_0:1;
suppose L38: ( C19 * C20 ) = 1;

L39: (1 <= C19 or 1 <= C20) by L38 , L27 , XREAL_1:162;
L40: (( 1 * C19 ) = 1 or ( 1 * C20 ) = 1) by L39 , L28 , L32 , XXREAL_0:1;
thus L41: C17 = ( ( ( 0 ) * C16 ) + C18 ) by L40 , L26 , L38 , EUCLID:29
.= ( ( 0. ( TOP-REAL R4 ) ) + C18 ) by EUCLID:29
.= C18 by EUCLID:27;
end;
suppose L42: ( C19 * C20 ) < 1;

thus L43: C17 = C16 by L42 , L37 , L13
.= C18 by L35 , L42 , L13;
end;
end;
begin
theorem
L45: (for B19 being non  empty (Subset of ( TOP-REAL 2 )) holds (for B20 being (Element of ( Euclid 2 )) holds (for B21 being Real holds (B19 = ( Ball (B20 , B21) ) implies B19 is  connected))))
proof
let C21 being non  empty (Subset of ( TOP-REAL 2 ));
let C22 being (Element of ( Euclid 2 ));
let C23 being Real;
assume that
L46: C21 = ( Ball (C22 , C23) );
L47: C21 is  convex
proof
let C24 , C25 being (Point of ( TOP-REAL 2 ));
assume that
L48: C24 in C21
and
L49: C25 in C21;
thus L50: thesis by L46 , L48 , L49 , TOPREAL3:21;
end;
thus L51: thesis by L47;
end;
theorem
L52: (for B22 , B23 being (Subset of ( TOP-REAL 2 )) holds ((B22 is  open & B23 is_a_component_of B22) implies B23 is  open))
proof
let C26 , C27 being (Subset of ( TOP-REAL 2 ));
assume that
L53: C26 is  open
and
L54: C27 is_a_component_of C26;
L55: C27 c= C26 by L54 , SPRECT_1:5;
L56: ( the TopStruct of ( TOP-REAL 2 ) ) = ( TopSpaceMetr ( Euclid 2 ) ) by EUCLID:def 8;
reconsider D2 = C27 , D3 = C26 as (Subset of ( TopSpaceMetr ( Euclid 2 ) )) by L56;
L57: D3 is  open by L53 , L56 , PRE_TOPC:30;
L58: (for B24 being (Point of ( Euclid 2 )) holds (B24 in D2 implies (ex B25 being  real number st (B25 > ( 0 ) & ( Ball (B24 , B25) ) c= D2))))
proof
let C28 being (Point of ( Euclid 2 ));
assume L59: C28 in D2;
consider C29 being  real number such that L60: C29 > ( 0 ) and L61: ( Ball (C28 , C29) ) c= D3 by L59 , L55 , L57 , TOPMETR:15;
reconsider D4 = C29 as Real by XREAL_0:def 1;
take D4;
thus L62: D4 > ( 0 ) by L60;
reconsider D5 = ( Ball (C28 , D4) ) as (Subset of ( TOP-REAL 2 )) by L56 , TOPMETR:12;
L63: C28 in D5 by L60 , GOBOARD6:1;
L64: D5 is  connected by L63 , L45;
L65: C27 meets D5 by L59 , L63 , XBOOLE_0:3;
thus L66: thesis by L65 , L54 , L61 , L64 , GOBOARD9:4;
end;
L67: D2 is  open by L58 , TOPMETR:15;
thus L68: C27 is  open by L67 , L56 , PRE_TOPC:30;
end;
theorem
L69: (for B26 , B27 , B28 , B29 being (Point of ( TOP-REAL 2 )) holds ((( LSeg (B26 , B27) ) is  horizontal & ( LSeg (B28 , B29) ) is  horizontal & ( LSeg (B26 , B27) ) meets ( LSeg (B28 , B29) )) implies ( B26 `2 ) = ( B28 `2 )))
proof
let C30 , C31 , C32 , C33 being (Point of ( TOP-REAL 2 ));
assume that
L70: ( LSeg (C30 , C31) ) is  horizontal
and
L71: ( LSeg (C32 , C33) ) is  horizontal;
assume L72: ( LSeg (C30 , C31) ) meets ( LSeg (C32 , C33) );
L73: ( ( LSeg (C30 , C31) ) /\ ( LSeg (C32 , C33) ) ) <> ( {} ) by L72 , XBOOLE_0:def 7;
consider C34 being (Point of ( TOP-REAL 2 )) such that L74: C34 in ( ( LSeg (C30 , C31) ) /\ ( LSeg (C32 , C33) ) ) by L73 , SUBSET_1:4;
L75: C34 in ( LSeg (C32 , C33) ) by L74 , XBOOLE_0:def 4;
L76: C34 in ( LSeg (C30 , C31) ) by L74 , XBOOLE_0:def 4;
thus L77: ( C30 `2 ) = ( C34 `2 ) by L76 , L70 , SPPOL_1:40
.= ( C32 `2 ) by L71 , L75 , SPPOL_1:40;
end;
theorem
L78: (for B30 , B31 , B32 being (Point of ( TOP-REAL 2 )) holds ((( LSeg (B30 , B31) ) is  vertical & ( LSeg (B31 , B32) ) is  horizontal) implies ( ( LSeg (B30 , B31) ) /\ ( LSeg (B31 , B32) ) ) = { B31 }))
proof
let C35 , C36 , C37 being (Point of ( TOP-REAL 2 ));
assume that
L79: ( LSeg (C35 , C36) ) is  vertical
and
L80: ( LSeg (C36 , C37) ) is  horizontal;
L81: (for B33 being set holds (B33 in ( ( LSeg (C35 , C36) ) /\ ( LSeg (C36 , C37) ) ) iff B33 = C36))
proof
let C38 being set;
thus L82: (C38 in ( ( LSeg (C35 , C36) ) /\ ( LSeg (C36 , C37) ) ) implies C38 = C36)
proof
assume L83: C38 in ( ( LSeg (C35 , C36) ) /\ ( LSeg (C36 , C37) ) );
reconsider D6 = C38 as (Point of ( TOP-REAL 2 )) by L83;
L84: D6 in ( LSeg (C36 , C37) ) by L83 , XBOOLE_0:def 4;
L85: ( D6 `2 ) = ( C36 `2 ) by L84 , L80 , SPPOL_1:40;
L86: D6 in ( LSeg (C35 , C36) ) by L83 , XBOOLE_0:def 4;
L87: ( D6 `1 ) = ( C36 `1 ) by L86 , L79 , SPPOL_1:41;
thus L88: thesis by L87 , L85 , TOPREAL3:6;
end;

assume L89: C38 = C36;
L90: C38 in ( LSeg (C36 , C37) ) by L89 , RLTOPSP1:68;
L91: C38 in ( LSeg (C35 , C36) ) by L89 , RLTOPSP1:68;
thus L92: thesis by L91 , L90 , XBOOLE_0:def 4;
end;
thus L93: thesis by L81 , TARSKI:def 1;
end;
theorem
L94: (for B34 , B35 , B36 , B37 being (Point of ( TOP-REAL 2 )) holds ((( LSeg (B34 , B35) ) is  horizontal & ( LSeg (B37 , B36) ) is  vertical & B36 in ( LSeg (B34 , B35) )) implies ( ( LSeg (B34 , B35) ) /\ ( LSeg (B37 , B36) ) ) = { B36 }))
proof
let C39 , C40 , C41 , C42 being (Point of ( TOP-REAL 2 ));
assume that
L95: ( LSeg (C39 , C40) ) is  horizontal
and
L96: ( LSeg (C42 , C41) ) is  vertical
and
L97: C41 in ( LSeg (C39 , C40) );
L98: (for B38 being set holds (B38 in ( ( LSeg (C39 , C40) ) /\ ( LSeg (C42 , C41) ) ) iff B38 = C41))
proof
let C43 being set;
thus L99: (C43 in ( ( LSeg (C39 , C40) ) /\ ( LSeg (C42 , C41) ) ) implies C43 = C41)
proof
assume L100: C43 in ( ( LSeg (C39 , C40) ) /\ ( LSeg (C42 , C41) ) );
reconsider D7 = C43 as (Point of ( TOP-REAL 2 )) by L100;
L101: D7 in ( LSeg (C39 , C40) ) by L100 , XBOOLE_0:def 4;
L102: ( D7 `2 ) = ( C39 `2 ) by L101 , L95 , SPPOL_1:40;
L103: D7 in ( LSeg (C42 , C41) ) by L100 , XBOOLE_0:def 4;
L104: ( D7 `1 ) = ( C41 `1 ) by L103 , L96 , SPPOL_1:41;
L105: ( C39 `2 ) = ( C41 `2 ) by L95 , L97 , SPPOL_1:40;
thus L106: thesis by L105 , L102 , L104 , TOPREAL3:6;
end;

assume L107: C43 = C41;
L108: C43 in ( LSeg (C42 , C41) ) by L107 , RLTOPSP1:68;
thus L109: thesis by L108 , L97 , L107 , XBOOLE_0:def 4;
end;
thus L110: thesis by L98 , TARSKI:def 1;
end;
begin
theorem
L111: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for R3 being (Element of ( NAT )) holds (for R8 being Go-board holds ((1 <= R2 & R2 <= R3 & R3 <= ( width R8 ) & 1 <= R1 & R1 <= ( len R8 )) implies ( ( R8 * (R1 , R2) ) `2 ) <= ( ( R8 * (R1 , R3) ) `2 ))))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let R3 being (Element of ( NAT ));
let R8 being Go-board;
assume that
L112: 1 <= R2
and
L113: R2 <= R3
and
L114: R3 <= ( width R8 )
and
L115: 1 <= R1
and
L116: R1 <= ( len R8 );
per cases  by L113 , XXREAL_0:1;
suppose L117: R2 < R3;

thus L118: thesis by L117 , L112 , L114 , L115 , L116 , GOBOARD5:4;
end;
suppose L119: R2 = R3;

thus L120: thesis by L119;
end;
end;
theorem
L122: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for R3 being (Element of ( NAT )) holds (for R8 being Go-board holds ((1 <= R2 & R2 <= ( width R8 ) & 1 <= R1 & R1 <= R3 & R3 <= ( len R8 )) implies ( ( R8 * (R1 , R2) ) `1 ) <= ( ( R8 * (R3 , R2) ) `1 ))))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let R3 being (Element of ( NAT ));
let R8 being Go-board;
assume that
L123: 1 <= R2
and
L124: R2 <= ( width R8 )
and
L125: 1 <= R1
and
L126: R1 <= R3
and
L127: R3 <= ( len R8 );
per cases  by L126 , XXREAL_0:1;
suppose L128: R1 < R3;

thus L129: thesis by L128 , L123 , L124 , L125 , L127 , GOBOARD5:3;
end;
suppose L130: R1 = R3;

thus L131: thesis by L130;
end;
end;
theorem
L133: (for R9 being (Subset of ( TOP-REAL 2 )) holds ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) c= ( L~ ( SpStSeq R9 ) ))
proof
let R9 being (Subset of ( TOP-REAL 2 ));
L134: ( ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) \/ ( LSeg (( NE-corner R9 ) , ( SE-corner R9 )) ) ) c= ( ( ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) \/ ( LSeg (( NE-corner R9 ) , ( SE-corner R9 )) ) ) \/ ( ( LSeg (( SE-corner R9 ) , ( SW-corner R9 )) ) \/ ( LSeg (( SW-corner R9 ) , ( NW-corner R9 )) ) ) ) by XBOOLE_1:7;
L135: ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) c= ( ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) \/ ( LSeg (( NE-corner R9 ) , ( SE-corner R9 )) ) ) by XBOOLE_1:7;
L136: ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) c= ( ( ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) \/ ( LSeg (( NE-corner R9 ) , ( SE-corner R9 )) ) ) \/ ( ( LSeg (( SE-corner R9 ) , ( SW-corner R9 )) ) \/ ( LSeg (( SW-corner R9 ) , ( NW-corner R9 )) ) ) ) by L135 , L134 , XBOOLE_1:1;
thus L137: thesis by L136 , SPRECT_1:41;
end;
theorem
L138: (for B39 being non  empty  compact (Subset of ( TOP-REAL 2 )) holds ( N-min B39 ) in ( LSeg (( NW-corner B39 ) , ( NE-corner B39 )) ))
proof
let C44 being non  empty  compact (Subset of ( TOP-REAL 2 ));
L139: ( N-most C44 ) c= ( LSeg (( NW-corner C44 ) , ( NE-corner C44 )) ) by XBOOLE_1:17;
L140: ( N-min C44 ) in ( N-most C44 ) by PSCOMP_1:42;
thus L141: thesis by L140 , L139;
end;
registration
let R9 being (Subset of ( TOP-REAL 2 ));
cluster ( LSeg (( NW-corner R9 ) , ( NE-corner R9 )) ) ->  horizontal;
coherence
proof
L142: ( ( NW-corner R9 ) `2 ) = ( N-bound R9 ) by EUCLID:52
.= ( ( NE-corner R9 ) `2 ) by EUCLID:52;
thus L143: thesis by L142 , SPPOL_1:15;
end;
end;
theorem
L145: (for B40 being (FinSequence of ( TOP-REAL 2 )) holds (for B41 being (Point of ( TOP-REAL 2 )) holds ((( B40 /. 1 ) <> B41 & (( ( B40 /. 1 ) `1 ) = ( B41 `1 ) or ( ( B40 /. 1 ) `2 ) = ( B41 `2 )) & B40 is  being_S-Seq & ( ( LSeg (B41 , ( B40 /. 1 )) ) /\ ( L~ B40 ) ) = { ( B40 /. 1 ) }) implies ( <* B41 *> ^ B40 ) is  being_S-Seq)))
proof
let C45 being (FinSequence of ( TOP-REAL 2 ));
let C46 being (Point of ( TOP-REAL 2 ));
assume that
L146: ( C45 /. 1 ) <> C46
and
L147: (( ( C45 /. 1 ) `1 ) = ( C46 `1 ) or ( ( C45 /. 1 ) `2 ) = ( C46 `2 ))
and
L148: C45 is  being_S-Seq
and
L149: ( ( LSeg (C46 , ( C45 /. 1 )) ) /\ ( L~ C45 ) ) = { ( C45 /. 1 ) };
set D8 = <* C46 , ( C45 /. 1 ) *>;
L150: D8 is  being_S-Seq by L146 , L147 , SPPOL_2:43;
reconsider D9 = C45 as S-Sequence_in_R2 by L148;
L151: 1 in ( dom D9 ) by FINSEQ_5:6;
L152: ( len D8 ) = ( 1 + 1 ) by FINSEQ_1:44;
L153: ( ( len D8 ) -' 1 ) = 1 by L152 , NAT_D:34;
L154: ( mid (D8 , 1 , ( ( len D8 ) -' 1 )) ) = <* ( D8 /. 1 ) *> by L153 , L152 , JORDAN4:15
.= <* C46 *> by FINSEQ_4:17;
L155: ( ( L~ D8 ) /\ ( L~ C45 ) ) = { ( C45 /. 1 ) } by L149 , SPPOL_2:21
.= { ( C45 . 1 ) } by L151 , PARTFUN1:def 6;
L156: ( D8 . ( len D8 ) ) = ( C45 /. 1 ) by L152 , FINSEQ_1:44
.= ( C45 . 1 ) by L151 , PARTFUN1:def 6;
thus L157: thesis by L156 , L148 , L150 , L155 , L154 , JORDAN3:45;
end;
theorem
L158: (for R2 being (Element of ( NAT )) holds (for B42 being S-Sequence_in_R2 holds (for B43 being (Point of ( TOP-REAL 2 )) holds ((1 < R2 & R2 <= ( len B42 ) & B43 in ( L~ ( mid (B42 , 1 , R2) ) )) implies  LE B43 , ( B42 /. R2 ) , ( L~ B42 ) , ( B42 /. 1 ) , ( B42 /. ( len B42 ) )))))
proof
let R2 being (Element of ( NAT ));
let C47 being S-Sequence_in_R2;
let C48 being (Point of ( TOP-REAL 2 ));
assume that
L159: 1 < R2
and
L160: R2 <= ( len C47 )
and
L161: C48 in ( L~ ( mid (C47 , 1 , R2) ) );
consider R1 being (Element of ( NAT )) such that L162: 1 <= R1 and L163: ( R1 + 1 ) <= ( len ( mid (C47 , 1 , R2) ) ) and L164: C48 in ( LSeg (( mid (C47 , 1 , R2) ) , R1) ) by L161 , SPPOL_2:13;
L165: ( ( R2 -' 1 ) + 1 ) = R2 by L159 , XREAL_1:235;
L166: ( R1 + 1 ) <= R2 by L165 , L159 , L160 , L163 , JORDAN4:8;
L167: R1 < ( ( R2 -' 1 ) + 1 ) by L166 , L165 , NAT_1:13;
L168: ( LSeg (( mid (C47 , 1 , R2) ) , R1) ) = ( LSeg (C47 , ( ( R1 + 1 ) -' 1 )) ) by L167 , L159 , L160 , L162 , JORDAN4:19;
L169: 1 <= ( R1 + 1 ) by NAT_1:11;
L170:  LE ( C47 /. ( R1 + 1 ) ) , ( C47 /. R2 ) , ( L~ C47 ) , ( C47 /. 1 ) , ( C47 /. ( len C47 ) ) by L169 , L160 , L166 , JORDAN5C:24;
L171: R1 = ( ( R1 + 1 ) -' 1 ) by NAT_D:34;
L172: ( R1 + 1 ) <= ( len C47 ) by L160 , L166 , XXREAL_0:2;
L173:  LE C48 , ( C47 /. ( R1 + 1 ) ) , ( L~ C47 ) , ( C47 /. 1 ) , ( C47 /. ( len C47 ) ) by L172 , L162 , L164 , L171 , L168 , JORDAN5C:26;
thus L174: thesis by L173 , L170 , JORDAN5C:13;
end;
theorem
L175: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for B44 being (FinSequence of ( TOP-REAL 2 )) holds ((R1 in ( dom B44 ) & R2 in ( dom B44 )) implies ( L~ ( mid (B44 , R1 , R2) ) ) c= ( L~ B44 )))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let C49 being (FinSequence of ( TOP-REAL 2 ));
assume that
L176: R1 in ( dom C49 )
and
L177: R2 in ( dom C49 );
L178: R1 <= ( len C49 ) by L176 , FINSEQ_3:25;
L179: R2 <= ( len C49 ) by L177 , FINSEQ_3:25;
L180: 1 <= R2 by L177 , FINSEQ_3:25;
L181: 1 <= R1 by L176 , FINSEQ_3:25;
thus L182: thesis by L181 , L178 , L180 , L179 , JORDAN4:35;
end;
theorem
L183: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds ((1 <= R1 & R1 < R2) implies (for B45 being (FinSequence of ( TOP-REAL 2 )) holds (R2 <= ( len B45 ) implies ( L~ ( mid (B45 , R1 , R2) ) ) = ( ( LSeg (B45 , R1) ) \/ ( L~ ( mid (B45 , ( R1 + 1 ) , R2) ) ) ))))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
assume that
L184: 1 <= R1
and
L185: R1 < R2;
let C50 being (FinSequence of ( TOP-REAL 2 ));
assume that
L186: R2 <= ( len C50 );
set D10 = { ( LSeg (C50 , R3) ) where R3 is (Element of ( NAT )) : (R1 <= R3 & R3 < R2) };
set D11 = { ( LSeg (C50 , R3) ) where R3 is (Element of ( NAT )) : (( R1 + 1 ) <= R3 & R3 < R2) };
L187: D10 = ( D11 \/ { ( LSeg (C50 , R1) ) } )
proof
thus L188: D10 c= ( D11 \/ { ( LSeg (C50 , R1) ) } )
proof
let C51 being set;
assume L189: C51 in D10;
consider R3 being (Element of ( NAT )) such that L190: C51 = ( LSeg (C50 , R3) ) and L191: R1 <= R3 and L192: R3 < R2 by L189;
L193: (R1 = R3 or R1 < R3) by L191 , XXREAL_0:1;
L194: (R1 = R3 or ( R1 + 1 ) <= R3) by L193 , NAT_1:13;
L195: (C51 in D11 or C51 in { ( LSeg (C50 , R1) ) }) by L194 , L190 , L192 , TARSKI:def 1;
thus L196: thesis by L195 , XBOOLE_0:def 3;
end;

let C52 being set;
assume L197: C52 in ( D11 \/ { ( LSeg (C50 , R1) ) } );
per cases  by L197 , XBOOLE_0:def 3;
suppose L198: C52 in D11;

consider R3 being (Element of ( NAT )) such that L199: C52 = ( LSeg (C50 , R3) ) and L200: ( R1 + 1 ) <= R3 and L201: R3 < R2 by L198;
L202: R1 < R3 by L200 , NAT_1:13;
thus L203: thesis by L202 , L199 , L201;
end;
suppose L204: C52 in { ( LSeg (C50 , R1) ) };

L205: C52 = ( LSeg (C50 , R1) ) by L204 , TARSKI:def 1;
thus L206: thesis by L205 , L185;
end;
end;
L208: 1 <= ( R1 + 1 ) by NAT_1:11;
L209: ( R1 + 1 ) <= R2 by L185 , NAT_1:13;
thus L210: ( L~ ( mid (C50 , R1 , R2) ) ) = ( union D10 ) by L184 , L185 , L186 , SPRECT_2:14
.= ( ( union D11 ) \/ ( union { ( LSeg (C50 , R1) ) } ) ) by L187 , ZFMISC_1:78
.= ( ( union D11 ) \/ ( LSeg (C50 , R1) ) ) by ZFMISC_1:25
.= ( ( LSeg (C50 , R1) ) \/ ( L~ ( mid (C50 , ( R1 + 1 ) , R2) ) ) ) by L186 , L208 , L209 , SPRECT_2:14;
end;
theorem
L211: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for B46 being (FinSequence of ( TOP-REAL 2 )) holds (1 <= R1 implies ((R1 < R2 & R2 <= ( len B46 )) implies ( L~ ( mid (B46 , R1 , R2) ) ) = ( ( L~ ( mid (B46 , R1 , ( R2 -' 1 )) ) ) \/ ( LSeg (B46 , ( R2 -' 1 )) ) ))))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let C53 being (FinSequence of ( TOP-REAL 2 ));
assume that
L212: 1 <= R1
and
L213: R1 < R2
and
L214: R2 <= ( len C53 );
L215: ( R2 -' 1 ) <= R2 by NAT_D:35;
L216: ( R2 -' 1 ) <= ( len C53 ) by L215 , L214 , XXREAL_0:2;
set D12 = { ( LSeg (C53 , R3) ) where R3 is (Element of ( NAT )) : (R1 <= R3 & R3 < R2) };
set D13 = { ( LSeg (C53 , R3) ) where R3 is (Element of ( NAT )) : (R1 <= R3 & R3 < ( R2 -' 1 )) };
L217: R1 <= ( R2 -' 1 ) by L213 , NAT_D:49;
L218: D12 = ( D13 \/ { ( LSeg (C53 , ( R2 -' 1 )) ) } )
proof
thus L219: D12 c= ( D13 \/ { ( LSeg (C53 , ( R2 -' 1 )) ) } )
proof
let C54 being set;
assume L220: C54 in D12;
consider R3 being (Element of ( NAT )) such that L221: C54 = ( LSeg (C53 , R3) ) and L222: R1 <= R3 and L223: R3 < R2 by L220;
L224: R3 <= ( R2 -' 1 ) by L223 , NAT_D:49;
L225: (( R2 -' 1 ) = R3 or R3 < ( R2 -' 1 )) by L224 , XXREAL_0:1;
L226: (C54 in D13 or C54 in { ( LSeg (C53 , ( R2 -' 1 )) ) }) by L225 , L221 , L222 , TARSKI:def 1;
thus L227: thesis by L226 , XBOOLE_0:def 3;
end;

let C55 being set;
L228: ( R2 -' 1 ) <= R2 by NAT_D:35;
assume L229: C55 in ( D13 \/ { ( LSeg (C53 , ( R2 -' 1 )) ) } );
per cases  by L229 , XBOOLE_0:def 3;
suppose L230: C55 in D13;

consider R3 being (Element of ( NAT )) such that L231: C55 = ( LSeg (C53 , R3) ) and L232: R1 <= R3 and L233: R3 < ( R2 -' 1 ) by L230;
L234: R3 < R2 by L228 , L233 , XXREAL_0:2;
thus L235: thesis by L234 , L231 , L232;
end;
suppose L236: C55 in { ( LSeg (C53 , ( R2 -' 1 )) ) };

L237: 1 <= ( R2 -' 1 ) by L212 , L217 , XXREAL_0:2;
L238: ( R2 -' 1 ) < R2 by L237 , NAT_D:51;
L239: C55 = ( LSeg (C53 , ( R2 -' 1 )) ) by L236 , TARSKI:def 1;
thus L240: thesis by L239 , L217 , L238;
end;
end;
thus L242: ( L~ ( mid (C53 , R1 , R2) ) ) = ( union D12 ) by L212 , L213 , L214 , SPRECT_2:14
.= ( ( union D13 ) \/ ( union { ( LSeg (C53 , ( R2 -' 1 )) ) } ) ) by L218 , ZFMISC_1:78
.= ( ( union D13 ) \/ ( LSeg (C53 , ( R2 -' 1 )) ) ) by ZFMISC_1:25
.= ( ( L~ ( mid (C53 , R1 , ( R2 -' 1 )) ) ) \/ ( LSeg (C53 , ( R2 -' 1 )) ) ) by L212 , L217 , L216 , SPRECT_2:14;
end;
theorem
L243: (for B47 , B48 being (FinSequence of ( TOP-REAL 2 )) holds ((B47 is  being_S-Seq & B48 is  being_S-Seq & (( ( B47 /. ( len B47 ) ) `1 ) = ( ( B48 /. 1 ) `1 ) or ( ( B47 /. ( len B47 ) ) `2 ) = ( ( B48 /. 1 ) `2 )) & ( L~ B47 ) misses ( L~ B48 ) & ( ( LSeg (( B47 /. ( len B47 ) ) , ( B48 /. 1 )) ) /\ ( L~ B47 ) ) = { ( B47 /. ( len B47 ) ) } & ( ( LSeg (( B47 /. ( len B47 ) ) , ( B48 /. 1 )) ) /\ ( L~ B48 ) ) = { ( B48 /. 1 ) }) implies ( B47 ^ B48 ) is  being_S-Seq))
proof
let C56 , C57 being (FinSequence of ( TOP-REAL 2 ));
assume that
L244: C56 is  being_S-Seq
and
L245: C57 is  being_S-Seq
and
L246: (( ( C56 /. ( len C56 ) ) `1 ) = ( ( C57 /. 1 ) `1 ) or ( ( C56 /. ( len C56 ) ) `2 ) = ( ( C57 /. 1 ) `2 ))
and
L247: ( L~ C56 ) misses ( L~ C57 )
and
L248: ( ( LSeg (( C56 /. ( len C56 ) ) , ( C57 /. 1 )) ) /\ ( L~ C56 ) ) = { ( C56 /. ( len C56 ) ) }
and
L249: ( ( LSeg (( C56 /. ( len C56 ) ) , ( C57 /. 1 )) ) /\ ( L~ C57 ) ) = { ( C57 /. 1 ) };
L250: ( len C57 ) >= 2 by L245 , TOPREAL1:def 8;
L251: ( len C57 ) >= 1 by L250 , XXREAL_0:2;
L252: 1 in ( dom C57 ) by L251 , FINSEQ_3:25;
L253: ( C57 /. 1 ) in ( L~ C57 ) by L252 , L250 , GOBOARD1:1;
set D14 = ( <* ( C56 /. ( len C56 ) ) *> ^ C57 );
L254: ( len C56 ) >= 2 by L244 , TOPREAL1:def 8;
L255: 1 <= ( len C56 ) by L254 , XXREAL_0:2;
L256: ( len C56 ) in ( dom C56 ) by L255 , FINSEQ_3:25;
L257: ( C56 . ( len C56 ) ) = ( C56 /. ( len C56 ) ) by L256 , PARTFUN1:def 6
.= ( D14 . 1 ) by FINSEQ_1:41;
L258: ( len D14 ) = ( ( len <* ( C56 /. ( len C56 ) ) *> ) + ( len C57 ) ) by FINSEQ_1:22
.= ( ( len C57 ) + 1 ) by FINSEQ_1:39;
L259: ( len D14 ) >= ( 1 + 1 ) by L258 , L251 , XREAL_1:6;
L260: ( mid (D14 , 2 , ( len D14 )) ) = ( ( D14 /^ ( ( 1 + 1 ) -' 1 ) ) | ( ( ( len D14 ) -' 2 ) + 1 ) ) by L259 , FINSEQ_6:def 3
.= ( ( D14 /^ 1 ) | ( ( ( len D14 ) -' 2 ) + 1 ) ) by NAT_D:34
.= ( C57 | ( ( ( len D14 ) -' 2 ) + 1 ) ) by FINSEQ_6:45
.= ( C57 | ( ( ( ( len D14 ) -' 1 ) -' 1 ) + 1 ) ) by NAT_D:45
.= ( C57 | ( ( ( len C57 ) -' 1 ) + 1 ) ) by L258 , NAT_D:34
.= ( C57 | ( len C57 ) ) by L250 , XREAL_1:235 , XXREAL_0:2
.= C57 by FINSEQ_1:58;
L261: ( C56 /. ( len C56 ) ) in ( L~ C56 ) by L254 , L256 , GOBOARD1:1;
L262: ( C56 /. ( len C56 ) ) <> ( C57 /. 1 ) by L261 , L247 , L253 , XBOOLE_0:3;
L263: D14 is  being_S-Seq by L262 , L245 , L246 , L249 , SPRECT_2:60;
L264: ( ( L~ C56 ) /\ ( L~ D14 ) ) = ( ( L~ C56 ) /\ ( ( LSeg (( C56 /. ( len C56 ) ) , ( C57 /. 1 )) ) \/ ( L~ C57 ) ) ) by L245 , SPPOL_2:20
.= ( ( ( L~ C56 ) /\ ( LSeg (( C56 /. ( len C56 ) ) , ( C57 /. 1 )) ) ) \/ ( ( L~ C56 ) /\ ( L~ C57 ) ) ) by XBOOLE_1:23
.= ( ( ( L~ C56 ) /\ ( LSeg (( C56 /. ( len C56 ) ) , ( C57 /. 1 )) ) ) \/ ( {} ) ) by L247 , XBOOLE_0:def 7
.= { ( D14 . 1 ) } by L248 , L256 , L257 , PARTFUN1:def 6;
thus L265: thesis by L264 , L244 , L257 , L263 , L260 , JORDAN3:38;
end;
theorem
L266: (for B49 being (FinSequence of ( TOP-REAL 2 )) holds (for B50 being (Point of ( TOP-REAL 2 )) holds (B50 in ( L~ B49 ) implies ( ( R_Cut (B49 , B50) ) /. 1 ) = ( B49 /. 1 ))))
proof
let C58 being (FinSequence of ( TOP-REAL 2 ));
let C59 being (Point of ( TOP-REAL 2 ));
set D15 = ( Index (C59 , C58) );
assume L267: C59 in ( L~ C58 );
L268: 1 <= D15 by L267 , JORDAN3:8;
L269: D15 <= ( len C58 ) by L267 , JORDAN3:8;
L270: C58 <> ( {} ) by L269 , L268;
L271: 1 in ( dom C58 ) by L270 , FINSEQ_5:6;
L272: (C59 = ( C58 . 1 ) or C59 <> ( C58 . 1 ));
L273: (( len ( R_Cut (C58 , C59) ) ) = ( Index (C59 , C58) ) or ( len ( R_Cut (C58 , C59) ) ) = ( ( Index (C59 , C58) ) + 1 )) by L272 , L267 , JORDAN3:25;
L274: 1 <= ( len ( R_Cut (C58 , C59) ) ) by L273 , L267 , JORDAN3:8 , NAT_1:11;
thus L275: ( ( R_Cut (C58 , C59) ) /. 1 ) = ( ( R_Cut (C58 , C59) ) . 1 ) by L274 , FINSEQ_4:15
.= ( C58 . 1 ) by L267 , L268 , JORDAN3:24
.= ( C58 /. 1 ) by L271 , PARTFUN1:def 6;
end;
theorem
L276: (for R2 being (Element of ( NAT )) holds (for B51 being S-Sequence_in_R2 holds (for B52 , B53 being (Point of ( TOP-REAL 2 )) holds ((1 <= R2 & R2 < ( len B51 ) & B52 in ( LSeg (B51 , R2) ) & B53 in ( LSeg (( B51 /. R2 ) , B52) )) implies  LE B53 , B52 , ( L~ B51 ) , ( B51 /. 1 ) , ( B51 /. ( len B51 ) )))))
proof
let R2 being (Element of ( NAT ));
let C60 being S-Sequence_in_R2;
let C61 , C62 being (Point of ( TOP-REAL 2 ));
assume that
L277: 1 <= R2
and
L278: R2 < ( len C60 )
and
L279: C61 in ( LSeg (C60 , R2) )
and
L280: C62 in ( LSeg (( C60 /. R2 ) , C61) );
L281: ( R2 + 1 ) <= ( len C60 ) by L278 , NAT_1:13;
L282: ( LSeg (C60 , R2) ) = ( LSeg (( C60 /. R2 ) , ( C60 /. ( R2 + 1 ) )) ) by L281 , L277 , TOPREAL1:def 3;
L283: ( C60 /. R2 ) in ( LSeg (C60 , R2) ) by L277 , L281 , TOPREAL1:21;
L284: ( LSeg (( C60 /. R2 ) , C61) ) c= ( LSeg (C60 , R2) ) by L283 , L279 , L282 , TOPREAL1:6;
L285: C62 in ( LSeg (C60 , R2) ) by L284 , L280;
L286: ( LSeg (C60 , R2) ) c= ( L~ C60 ) by TOPREAL3:19;
per cases ;
suppose L287: C61 = C62;

thus L288: thesis by L287 , L279 , L286 , JORDAN5C:9;
end;
suppose L289: C62 <> C61;

L290: (for B54 , B55 being (Element of ( NAT )) holds ((C62 in ( LSeg (C60 , B54) ) & C61 in ( LSeg (C60 , B55) ) & 1 <= B54 & ( B54 + 1 ) <= ( len C60 ) & 1 <= B55 & ( B55 + 1 ) <= ( len C60 )) implies (B54 <= B55 & (B54 = B55 implies  LE C62 , C61 , ( C60 /. B54 ) , ( C60 /. ( B54 + 1 ) )))))
proof
L291: 1 <= ( R2 + 1 ) by NAT_1:11;
L292: ( R2 + 1 ) in ( dom C60 ) by L291 , L281 , FINSEQ_3:25;
let C63 , C64 being (Element of ( NAT ));
assume that
L293: C62 in ( LSeg (C60 , C63) )
and
L294: C61 in ( LSeg (C60 , C64) )
and
L295: 1 <= C63
and
L296: ( C63 + 1 ) <= ( len C60 )
and
L297: 1 <= C64
and
L298: ( C64 + 1 ) <= ( len C60 );
L299: C61 in ( ( LSeg (C60 , C64) ) /\ ( LSeg (C60 , R2) ) ) by L279 , L294 , XBOOLE_0:def 4;
L300: ( LSeg (C60 , C64) ) meets ( LSeg (C60 , R2) ) by L299 , XBOOLE_0:4;
L301: ( R2 + 1 ) >= C64 by L300 , TOPREAL1:def 7;
L302: C62 in ( ( LSeg (C60 , C63) ) /\ ( LSeg (C60 , R2) ) ) by L280 , L284 , L293 , XBOOLE_0:def 4;
L303: ( LSeg (C60 , C63) ) meets ( LSeg (C60 , R2) ) by L302 , XBOOLE_0:4;
L304: ( C63 + 1 ) >= R2 by L303 , TOPREAL1:def 7;
L305:
now
assume L306: ( C64 + 1 ) = R2;
L307: ( C64 + ( 1 + 1 ) ) = ( ( C64 + 1 ) + 1 );
L308: ( C64 + 2 ) <= ( len C60 ) by L307 , L278 , L306 , NAT_1:13;
L309: C61 in { ( C60 /. R2 ) } by L308 , L297 , L299 , L306 , TOPREAL1:def 6;
L310: C61 = ( C60 /. R2 ) by L309 , TARSKI:def 1;
L311: C62 in { C61 } by L310 , L280 , RLTOPSP1:70;
thus L312: contradiction by L311 , L289 , TARSKI:def 1;
end;
L313:
now
assume that
L314: ( C64 + 1 ) > R2
and
L315: ( R2 + 1 ) > C64;
L316: R2 <= C64 by L314 , NAT_1:13;
L317: C64 <= R2 by L315 , NAT_1:13;
thus L318: C64 = R2 by L317 , L316 , XXREAL_0:1;
end;
L319: ( C64 + 1 ) >= R2 by L300 , TOPREAL1:def 7;
L320: (( C64 + 1 ) = R2 or C64 = R2 or ( R2 + 1 ) = C64) by L319 , L313 , L301 , XXREAL_0:1;
L321: C64 >= R2 by L320 , L305 , NAT_1:11;
L322:
now
assume that
L323: ( C63 + 1 ) > R2
and
L324: ( R2 + 1 ) > C63;
L325: R2 <= C63 by L323 , NAT_1:13;
L326: C63 <= R2 by L324 , NAT_1:13;
thus L327: C63 = R2 by L326 , L325 , XXREAL_0:1;
end;
L328: R2 in ( dom C60 ) by L277 , L278 , FINSEQ_3:25;
L329:
now
assume L330: ( C60 /. ( R2 + 1 ) ) = ( C60 /. R2 );
L331: R2 = ( R2 + 1 ) by L330 , L292 , L328 , PARTFUN2:10;
thus L332: contradiction by L331;
end;
L333:
now
L334: ( R2 + ( 1 + 1 ) ) = ( ( R2 + 1 ) + 1 );
assume L335: C63 = ( R2 + 1 );
L336: C62 in { ( C60 /. ( R2 + 1 ) ) } by L335 , L277 , L296 , L302 , L334 , TOPREAL1:def 6;
L337: C62 = ( C60 /. ( R2 + 1 ) ) by L336 , TARSKI:def 1;
thus L338: contradiction by L337 , L279 , L280 , L282 , L283 , L289 , L329 , SPPOL_1:7 , TOPREAL1:6;
end;
L339: ( R2 + 1 ) >= C63 by L303 , TOPREAL1:def 7;
L340: (( C63 + 1 ) = R2 or C63 = R2 or ( R2 + 1 ) = C63) by L339 , L322 , L304 , XXREAL_0:1;
L341: C63 <= R2 by L340 , L333 , NAT_1:11;
thus L342: C63 <= C64 by L341 , L321 , XXREAL_0:2;
assume L343: C63 = C64;
L344: (not C61 in ( LSeg (( C60 /. R2 ) , C62) )) by L280 , L289 , L24;
L345: (not  LE C61 , C62 , ( C60 /. R2 ) , ( C60 /. ( R2 + 1 ) )) by L344 , JORDAN3:30;
L346:  LT C62 , C61 , ( C60 /. R2 ) , ( C60 /. ( R2 + 1 ) ) by L345 , L279 , L282 , L293 , L305 , L322 , L304 , L339 , L329 , L333 , L343 , JORDAN3:28 , XXREAL_0:1;
thus L347: thesis by L346 , L305 , L322 , L304 , L339 , L333 , L343 , JORDAN3:def 6 , XXREAL_0:1;
end;
thus L348: thesis by L290 , L279 , L285 , L286 , L289 , JORDAN5C:30;
end;
end;
begin
theorem
L350: (for B56 being non  constant  standard special_circular_sequence holds (( LeftComp B56 ) is  open & ( RightComp B56 ) is  open))
proof
let C65 being non  constant  standard special_circular_sequence;
L351: ( LeftComp C65 ) is_a_component_of ( ( L~ C65 ) ` ) by GOBOARD9:def 1;
thus L352: ( LeftComp C65 ) is  open by L351 , L52;
L353: ( RightComp C65 ) is_a_component_of ( ( L~ C65 ) ` ) by GOBOARD9:def 2;
thus L354: thesis by L353 , L52;
end;
registration
let C66 being non  constant  standard special_circular_sequence;
cluster ( L~ C66 ) -> non  vertical non  horizontal;
coherence
proof
L355: ( W-bound ( L~ C66 ) ) <> ( E-bound ( L~ C66 ) ) by TOPREAL5:17;
thus L356: ( L~ C66 ) is non  vertical by L355 , SPRECT_1:15;
L357: ( S-bound ( L~ C66 ) ) <> ( N-bound ( L~ C66 ) ) by TOPREAL5:16;
thus L358: thesis by L357 , SPRECT_1:16;
end;
cluster ( LeftComp C66 ) ->  being_Region;
coherence
proof
thus L359: ( LeftComp C66 ) is  open by L350;
L360: ( LeftComp C66 ) is_a_component_of ( ( L~ C66 ) ` ) by GOBOARD9:def 1;
consider C67 being (Subset of ( ( TOP-REAL 2 ) | ( ( L~ C66 ) ` ) )) such that L361: C67 = ( LeftComp C66 ) and L362: C67 is  a_component by L360 , CONNSP_1:def 6;
L363: C67 is  connected by L362 , CONNSP_1:def 5;
thus L364: thesis by L363 , L361 , CONNSP_1:23;
end;
cluster ( RightComp C66 ) ->  being_Region;
coherence
proof
thus L365: ( RightComp C66 ) is  open by L350;
L366: ( RightComp C66 ) is_a_component_of ( ( L~ C66 ) ` ) by GOBOARD9:def 2;
consider C68 being (Subset of ( ( TOP-REAL 2 ) | ( ( L~ C66 ) ` ) )) such that L367: C68 = ( RightComp C66 ) and L368: C68 is  a_component by L366 , CONNSP_1:def 6;
L369: C68 is  connected by L368 , CONNSP_1:def 5;
thus L370: thesis by L369 , L367 , CONNSP_1:23;
end;
end;
theorem
L372: (for B57 being non  constant  standard special_circular_sequence holds ( RightComp B57 ) misses ( L~ B57 ))
proof
let C69 being non  constant  standard special_circular_sequence;
L373: ( ( L~ C69 ) ` ) = ( ( LeftComp C69 ) \/ ( RightComp C69 ) ) by GOBRD12:10;
L374: ( RightComp C69 ) c= ( ( L~ C69 ) ` ) by L373 , XBOOLE_1:7;
thus L375: thesis by L374 , SUBSET_1:23;
end;
theorem
L376: (for B58 being non  constant  standard special_circular_sequence holds ( LeftComp B58 ) misses ( L~ B58 ))
proof
let C70 being non  constant  standard special_circular_sequence;
L377: ( ( L~ C70 ) ` ) = ( ( LeftComp C70 ) \/ ( RightComp C70 ) ) by GOBRD12:10;
L378: ( LeftComp C70 ) c= ( ( L~ C70 ) ` ) by L377 , XBOOLE_1:7;
thus L379: thesis by L378 , SUBSET_1:23;
end;
theorem
L380: (for B59 being non  constant  standard special_circular_sequence holds ( i_w_n B59 ) < ( i_e_n B59 ))
proof
let C71 being non  constant  standard special_circular_sequence;
set D16 = ( GoB C71 );
L381: ( i_w_n C71 ) <= ( len D16 ) by JORDAN5D:45;
L382: ( D16 * (( i_w_n C71 ) , ( width D16 )) ) = ( N-min ( L~ C71 ) ) by JORDAN5D:def 7;
assume L383: ( i_w_n C71 ) >= ( i_e_n C71 );
L384: 1 <= ( i_e_n C71 ) by JORDAN5D:45;
L385: ( ( N-min ( L~ C71 ) ) `1 ) < ( ( N-max ( L~ C71 ) ) `1 ) by SPRECT_2:51;
L386: ( D16 * (( i_e_n C71 ) , ( width D16 )) ) = ( N-max ( L~ C71 ) ) by JORDAN5D:def 8;
L387: ( i_w_n C71 ) <> ( i_e_n C71 ) by L386 , L385 , JORDAN5D:def 7;
L388: ( i_w_n C71 ) > ( i_e_n C71 ) by L387 , L383 , XXREAL_0:1;
L389: ( width D16 ) > 1 by GOBOARD7:33;
thus L390: contradiction by L389 , L381 , L382 , L384 , L386 , L385 , L388 , GOBOARD5:3;
end;
theorem
L391: (for B60 being non  constant  standard special_circular_sequence holds (ex R1 being (Element of ( NAT )) st (1 <= R1 & R1 < ( len ( GoB B60 ) ) & ( N-min ( L~ B60 ) ) = ( ( GoB B60 ) * (R1 , ( width ( GoB B60 ) )) ))))
proof
let C72 being non  constant  standard special_circular_sequence;
take D17 = ( i_w_n C72 );
thus L392: 1 <= D17 by JORDAN5D:45;
L393: ( i_e_n C72 ) <= ( len ( GoB C72 ) ) by JORDAN5D:45;
thus L394: D17 < ( len ( GoB C72 ) ) by L393 , L380 , XXREAL_0:2;
thus L395: thesis by JORDAN5D:def 7;
end;
theorem
L396: (for R1 being (Element of ( NAT )) holds (for B61 being  clockwise_oriented non  constant  standard special_circular_sequence holds ((R1 in ( dom ( GoB B61 ) ) & ( B61 /. 1 ) = ( ( GoB B61 ) * (R1 , ( width ( GoB B61 ) )) ) & ( B61 /. 1 ) = ( N-min ( L~ B61 ) )) implies (( B61 /. 2 ) = ( ( GoB B61 ) * (( R1 + 1 ) , ( width ( GoB B61 ) )) ) & ( B61 /. ( ( len B61 ) -' 1 ) ) = ( ( GoB B61 ) * (R1 , ( ( width ( GoB B61 ) ) -' 1 )) )))))
proof
let R1 being (Element of ( NAT ));
let C73 being  clockwise_oriented non  constant  standard special_circular_sequence;
assume that
L397: R1 in ( dom ( GoB C73 ) )
and
L398: ( C73 /. 1 ) = ( ( GoB C73 ) * (R1 , ( width ( GoB C73 ) )) )
and
L399: ( C73 /. 1 ) = ( N-min ( L~ C73 ) );
L400: R1 <= ( len ( GoB C73 ) ) by L397 , FINSEQ_3:25;
L401: 4 < ( len C73 ) by GOBOARD7:34;
L402: ( ( ( len C73 ) -' 1 ) + 1 ) = ( len C73 ) by L401 , XREAL_1:235 , XXREAL_0:2;
L403: ( C73 /. ( len C73 ) ) = ( C73 /. 1 ) by FINSEQ_6:def 1;
L404: 1 <= ( len C73 ) by GOBOARD7:34 , XXREAL_0:2;
L405: 1 in ( dom C73 ) by L404 , FINSEQ_3:25;
L406: 1 <= ( width ( GoB C73 ) ) by GOBRD11:34;
L407: ( C73 /. 2 ) in ( N-most ( L~ C73 ) ) by L399 , SPRECT_2:30;
L408: ( 1 + 1 ) <= ( len C73 ) by GOBOARD7:34 , XXREAL_0:2;
L409: ( 1 + 1 ) in ( dom C73 ) by L408 , FINSEQ_3:25;
consider C74 , C75 being (Element of ( NAT )) such that L410: [ C74 , C75 ] in ( Indices ( GoB C73 ) ) and L411: ( C73 /. 2 ) = ( ( GoB C73 ) * (C74 , C75) ) by L409 , GOBOARD2:14;
L412: 1 <= C75 by L410 , MATRIX_1:38;
L413: C75 <= ( width ( GoB C73 ) ) by L410 , MATRIX_1:38;
L414: 1 <= C74 by L410 , MATRIX_1:38;
L415: C74 <= ( len ( GoB C73 ) ) by L410 , MATRIX_1:38;
L416:
now
L417: ( ( C73 /. 2 ) `2 ) = ( ( N-min ( L~ C73 ) ) `2 ) by L407 , PSCOMP_1:39
.= ( N-bound ( L~ C73 ) ) by EUCLID:52;
assume L418: C75 < ( width ( GoB C73 ) );
L419: ( ( ( GoB C73 ) * (C74 , ( width ( GoB C73 ) )) ) `2 ) = ( ( ( GoB C73 ) * (1 , ( width ( GoB C73 ) )) ) `2 ) by L406 , L414 , L415 , GOBOARD5:1
.= ( N-bound ( L~ C73 ) ) by JORDAN5D:40;
thus L420: contradiction by L419 , L411 , L412 , L414 , L415 , L418 , L417 , GOBOARD5:4;
end;
L421: C75 = ( width ( GoB C73 ) ) by L416 , L413 , XXREAL_0:1;
L422:
now
assume L423: R1 > C74;
L424: ( ( C73 /. 2 ) `1 ) < ( ( N-min ( L~ C73 ) ) `1 ) by L423 , L398 , L399 , L411 , L400 , L412 , L414 , L421 , GOBOARD5:3;
thus L425: contradiction by L424 , L407 , PSCOMP_1:39;
end;
L426: 1 <= R1 by L397 , FINSEQ_3:25;
L427: [ R1 , ( width ( GoB C73 ) ) ] in ( Indices ( GoB C73 ) ) by L426 , L406 , L400 , MATRIX_1:36;
L428: ( ( abs ( R1 - C74 ) ) + ( 0 ) ) = ( ( abs ( R1 - C74 ) ) + ( abs ( ( width ( GoB C73 ) ) - ( width ( GoB C73 ) ) ) ) ) by ABSVALUE:2
.= 1 by L398 , L409 , L410 , L411 , L405 , L427 , L421 , GOBOARD5:12;
thus L429: ( C73 /. 2 ) = ( ( GoB C73 ) * (( R1 + 1 ) , ( width ( GoB C73 ) )) ) by L428 , L411 , L421 , L422 , SEQM_3:41;
L430: ( ( len C73 ) -' 1 ) <= ( len C73 ) by NAT_D:44;
L431: 1 <= ( ( len C73 ) -' 1 ) by L408 , NAT_D:49;
L432: ( ( len C73 ) -' 1 ) in ( dom C73 ) by L431 , L430 , FINSEQ_3:25;
consider C76 , C77 being (Element of ( NAT )) such that L433: [ C76 , C77 ] in ( Indices ( GoB C73 ) ) and L434: ( C73 /. ( ( len C73 ) -' 1 ) ) = ( ( GoB C73 ) * (C76 , C77) ) by L432 , GOBOARD2:14;
L435: 1 <= C76 by L433 , MATRIX_1:38;
L436: C77 <= ( width ( GoB C73 ) ) by L433 , MATRIX_1:38;
L437: C76 <= ( len ( GoB C73 ) ) by L433 , MATRIX_1:38;
L438: ( len C73 ) in ( dom C73 ) by L404 , FINSEQ_3:25;
L439: ( ( abs ( C76 - R1 ) ) + ( abs ( C77 - ( width ( GoB C73 ) ) ) ) ) = 1 by L438 , L398 , L427 , L403 , L402 , L432 , L433 , L434 , GOBOARD5:12;
per cases  by L439 , SEQM_3:42;
suppose that L440: ( abs ( C76 - R1 ) ) = 1
and
L441: C77 = ( width ( GoB C73 ) );
L442: ( ( C73 /. ( ( len C73 ) -' 1 ) ) `2 ) = ( ( ( GoB C73 ) * (1 , ( width ( GoB C73 ) )) ) `2 ) by L406 , L434 , L435 , L437 , L441 , GOBOARD5:1
.= ( ( N-min ( L~ C73 ) ) `2 ) by L398 , L399 , L406 , L426 , L400 , GOBOARD5:1
.= ( N-bound ( L~ C73 ) ) by EUCLID:52;
L443: ( C73 /. ( ( len C73 ) -' 1 ) ) in ( N-most ( L~ C73 ) ) by L442 , L408 , L432 , GOBOARD1:1 , SPRECT_2:10;
L444:
now
per cases  by L440 , SEQM_3:41;
suppose L445: R1 > C76;

L446: ( ( C73 /. ( ( len C73 ) -' 1 ) ) `1 ) < ( ( N-min ( L~ C73 ) ) `1 ) by L445 , L398 , L399 , L406 , L400 , L434 , L435 , L441 , GOBOARD5:3;
thus L447: contradiction by L446 , L443 , PSCOMP_1:39;
end;
suppose L448: ( R1 + 1 ) = C76;

L449: 2 >= ( ( len C73 ) -' 1 ) by L448 , L429 , L430 , L434 , L441 , GOBOARD7:37;
L450: ( 2 + 1 ) >= ( len C73 ) by L449 , NAT_D:52;
thus L451: contradiction by L450 , GOBOARD7:34 , XXREAL_0:2;
end;
end;
thus L453: thesis by L444;
end;
suppose that L454: ( abs ( C77 - ( width ( GoB C73 ) ) ) ) = 1
and
L455: C76 = R1;
L456: ( width ( GoB C73 ) ) in ( NAT );
L457: ( width ( GoB C73 ) ) = ( C77 + 1 ) by L456 , L436 , L454 , SEQM_3:41;
thus L458: thesis by L457 , L434 , L455 , NAT_D:34;
end;
end;
theorem
L460: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for B62 being non  constant  standard special_circular_sequence holds ((1 <= R1 & R1 < R2 & R2 <= ( len B62 ) & ( B62 /. 1 ) in ( L~ ( mid (B62 , R1 , R2) ) )) implies (R1 = 1 or R2 = ( len B62 ))))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let C78 being non  constant  standard special_circular_sequence;
assume that
L461: 1 <= R1
and
L462: R1 < R2
and
L463: R2 <= ( len C78 );
L464: ( 1 + 1 ) <= ( len C78 ) by GOBOARD7:34 , XXREAL_0:2;
L465: ( C78 /. 1 ) in ( LSeg (C78 , 1) ) by L464 , TOPREAL1:21;
assume L466: ( C78 /. 1 ) in ( L~ ( mid (C78 , R1 , R2) ) );
consider R4 being (Element of ( NAT )) such that L467: 1 <= R4 and L468: ( R4 + 1 ) <= ( len ( mid (C78 , R1 , R2) ) ) and L469: ( C78 /. 1 ) in ( LSeg (( mid (C78 , R1 , R2) ) , R4) ) by L466 , SPPOL_2:13;
L470: R4 < ( len ( mid (C78 , R1 , R2) ) ) by L468 , NAT_1:13;
L471: R4 < ( ( R2 -' R1 ) + 1 ) by L470 , L461 , L462 , L463 , JORDAN4:8;
L472: ( LSeg (( mid (C78 , R1 , R2) ) , R4) ) = ( LSeg (C78 , ( ( R4 + R1 ) -' 1 )) ) by L471 , L461 , L462 , L463 , L467 , JORDAN4:19;
L473: ( C78 /. 1 ) in ( ( LSeg (C78 , 1) ) /\ ( LSeg (C78 , ( ( R4 + R1 ) -' 1 )) ) ) by L472 , L469 , L465 , XBOOLE_0:def 4;
L474: ( LSeg (C78 , 1) ) meets ( LSeg (C78 , ( ( R4 + R1 ) -' 1 )) ) by L473 , XBOOLE_0:4;
assume that
L475: R1 <> 1
and
L476: R2 <> ( len C78 );
per cases  by L474 , GOBOARD5:def 4;
suppose L477: ( 1 + 1 ) >= ( ( R4 + R1 ) -' 1 );

L478: ( R4 + R1 ) <= ( 2 + 1 ) by L477 , NAT_D:52;
L479: R1 > 1 by L461 , L475 , XXREAL_0:1;
L480: R1 >= ( 1 + 1 ) by L479 , NAT_1:13;
L481: ( R4 + R1 ) >= ( R1 + 1 ) by L467 , XREAL_1:6;
L482: ( R1 + 1 ) <= ( 2 + 1 ) by L481 , L478 , XXREAL_0:2;
L483: R1 <= 2 by L482 , XREAL_1:6;
L484: R1 = 2 by L483 , L480 , XXREAL_0:1;
L485: R4 <= 1 by L484 , L478 , XREAL_1:6;
L486: R4 = 1 by L485 , L467 , XXREAL_0:1;
L487: ( ( R4 + R1 ) -' 1 ) = 2 by L486 , L484 , NAT_D:34;
L488: 2 < ( len C78 ) by GOBOARD7:34 , XXREAL_0:2;
L489: ( 1 + 2 ) <= ( len C78 ) by GOBOARD7:34 , XXREAL_0:2;
L490: ( ( LSeg (C78 , 1) ) /\ ( LSeg (C78 , ( 1 + 1 )) ) ) = { ( C78 /. ( 1 + 1 ) ) } by L489 , TOPREAL1:def 6;
L491: ( C78 /. 1 ) = ( C78 /. 2 ) by L490 , L473 , L487 , TARSKI:def 1;
thus L492: contradiction by L491 , L488 , GOBOARD7:36;
end;
suppose L493: ( ( ( R4 + R1 ) -' 1 ) + 1 ) >= ( len C78 );

L494: R4 <= ( R4 + R1 ) by NAT_1:11;
L495: ( len C78 ) <= ( R4 + R1 ) by L494 , L467 , L493 , XREAL_1:235 , XXREAL_0:2;
L496: ( ( ( R2 -' R1 ) + 1 ) + R1 ) = ( ( ( R2 -' R1 ) + R1 ) + 1 )
.= ( R2 + 1 ) by L462 , XREAL_1:235;
L497: ( R4 + R1 ) < ( R2 + 1 ) by L496 , L471 , XREAL_1:6;
L498: ( R4 + R1 ) <= R2 by L497 , NAT_1:13;
L499: R2 < ( len C78 ) by L463 , L476 , XXREAL_0:1;
thus L500: contradiction by L499 , L495 , L498 , XXREAL_0:2;
end;
end;
theorem
L502: (for B63 being  clockwise_oriented non  constant  standard special_circular_sequence holds (( B63 /. 1 ) = ( N-min ( L~ B63 ) ) implies ( LSeg (( B63 /. 1 ) , ( B63 /. 2 )) ) c= ( L~ ( SpStSeq ( L~ B63 ) ) )))
proof
let C79 being  clockwise_oriented non  constant  standard special_circular_sequence;
L503: ( N-most ( L~ C79 ) ) c= ( LSeg (( NW-corner ( L~ C79 ) ) , ( NE-corner ( L~ C79 ) )) ) by XBOOLE_1:17;
assume L504: ( C79 /. 1 ) = ( N-min ( L~ C79 ) );
L505: ( C79 /. 2 ) in ( N-most ( L~ C79 ) ) by L504 , SPRECT_2:30;
L506: ( LSeg (( NW-corner ( L~ C79 ) ) , ( NE-corner ( L~ C79 ) )) ) c= ( L~ ( SpStSeq ( L~ C79 ) ) ) by L133;
L507: ( C79 /. 1 ) in ( LSeg (( NW-corner ( L~ C79 ) ) , ( NE-corner ( L~ C79 ) )) ) by L504 , L138;
L508: ( LSeg (( C79 /. 1 ) , ( C79 /. 2 )) ) c= ( LSeg (( NW-corner ( L~ C79 ) ) , ( NE-corner ( L~ C79 ) )) ) by L507 , L505 , L503 , TOPREAL1:6;
thus L509: thesis by L508 , L506 , XBOOLE_1:1;
end;
begin
theorem
L510: (for B64 being  rectangular (FinSequence of ( TOP-REAL 2 )) holds (for B65 being (Point of ( TOP-REAL 2 )) holds (B65 in ( L~ B64 ) implies (( B65 `1 ) = ( W-bound ( L~ B64 ) ) or ( B65 `1 ) = ( E-bound ( L~ B64 ) ) or ( B65 `2 ) = ( S-bound ( L~ B64 ) ) or ( B65 `2 ) = ( N-bound ( L~ B64 ) )))))
proof
let C80 being  rectangular (FinSequence of ( TOP-REAL 2 ));
let C81 being (Point of ( TOP-REAL 2 ));
assume that
L511: C81 in ( L~ C80 );
consider C82 being non  vertical non  horizontal non  empty  compact (Subset of ( TOP-REAL 2 )) such that L512: C80 = ( SpStSeq C82 ) by SPRECT_1:def 2;
L513: ( L~ C80 ) = ( ( ( LSeg (( NW-corner C82 ) , ( NE-corner C82 )) ) \/ ( LSeg (( NE-corner C82 ) , ( SE-corner C82 )) ) ) \/ ( ( LSeg (( SE-corner C82 ) , ( SW-corner C82 )) ) \/ ( LSeg (( SW-corner C82 ) , ( NW-corner C82 )) ) ) ) by L512 , SPRECT_1:41;
L514: (C81 in ( ( LSeg (( NW-corner C82 ) , ( NE-corner C82 )) ) \/ ( LSeg (( NE-corner C82 ) , ( SE-corner C82 )) ) ) or C81 in ( ( LSeg (( SE-corner C82 ) , ( SW-corner C82 )) ) \/ ( LSeg (( SW-corner C82 ) , ( NW-corner C82 )) ) )) by L513 , L511 , XBOOLE_0:def 3;
per cases  by L514 , XBOOLE_0:def 3;
suppose L515: C81 in ( LSeg (( NW-corner C82 ) , ( NE-corner C82 )) );

L516: ( N-bound ( L~ ( SpStSeq C82 ) ) ) = ( N-bound C82 ) by SPRECT_1:60;
L517: ( ( NE-corner C82 ) `2 ) = ( N-bound ( L~ C80 ) ) by L516 , L512 , EUCLID:52;
L518: ( ( NW-corner C82 ) `2 ) = ( N-bound ( L~ C80 ) ) by L512 , L516 , EUCLID:52;
thus L519: thesis by L518 , L515 , L517 , GOBOARD7:6;
end;
suppose L520: C81 in ( LSeg (( NE-corner C82 ) , ( SE-corner C82 )) );

L521: ( E-bound ( L~ ( SpStSeq C82 ) ) ) = ( E-bound C82 ) by SPRECT_1:61;
L522: ( ( SE-corner C82 ) `1 ) = ( E-bound ( L~ C80 ) ) by L521 , L512 , EUCLID:52;
L523: ( ( NE-corner C82 ) `1 ) = ( E-bound ( L~ C80 ) ) by L512 , L521 , EUCLID:52;
thus L524: thesis by L523 , L520 , L522 , GOBOARD7:5;
end;
suppose L525: C81 in ( LSeg (( SE-corner C82 ) , ( SW-corner C82 )) );

L526: ( S-bound ( L~ ( SpStSeq C82 ) ) ) = ( S-bound C82 ) by SPRECT_1:59;
L527: ( ( SW-corner C82 ) `2 ) = ( S-bound ( L~ C80 ) ) by L526 , L512 , EUCLID:52;
L528: ( ( SE-corner C82 ) `2 ) = ( S-bound ( L~ C80 ) ) by L512 , L526 , EUCLID:52;
thus L529: thesis by L528 , L525 , L527 , GOBOARD7:6;
end;
suppose L530: C81 in ( LSeg (( SW-corner C82 ) , ( NW-corner C82 )) );

L531: ( W-bound ( L~ ( SpStSeq C82 ) ) ) = ( W-bound C82 ) by SPRECT_1:58;
L532: ( ( NW-corner C82 ) `1 ) = ( W-bound ( L~ C80 ) ) by L531 , L512 , EUCLID:52;
L533: ( ( SW-corner C82 ) `1 ) = ( W-bound ( L~ C80 ) ) by L512 , L531 , EUCLID:52;
thus L534: thesis by L533 , L530 , L532 , GOBOARD7:5;
end;
end;
registration
cluster  rectangular for special_circular_sequence;
existence
proof
set D18 = the non  empty  compact non  vertical non  horizontal (Subset of ( TOP-REAL 2 ));
L536: ( SpStSeq D18 ) is special_circular_sequence;
thus L537: thesis by L536;
end;
end;
theorem
L539: (for B66 being  rectangular special_circular_sequence holds (for B67 being S-Sequence_in_R2 holds ((( B67 /. 1 ) in ( LeftComp B66 ) & ( B67 /. ( len B67 ) ) in ( RightComp B66 )) implies ( L~ B66 ) meets ( L~ B67 ))))
proof
let C83 being  rectangular special_circular_sequence;
let C84 being S-Sequence_in_R2;
assume that
L540: ( C84 /. 1 ) in ( LeftComp C83 )
and
L541: ( C84 /. ( len C84 ) ) in ( RightComp C83 );
L542: ( len C84 ) >= 2 by TOPREAL1:def 8;
L543: ( C84 /. 1 ) in ( L~ C84 ) by L542 , JORDAN3:1;
L544: ( C84 /. 1 ) in ( ( LeftComp C83 ) /\ ( L~ C84 ) ) by L543 , L540 , XBOOLE_0:def 4;
L545: ( LeftComp C83 ) meets ( L~ C84 ) by L544 , XBOOLE_0:4;
L546: ( C84 /. ( len C84 ) ) in ( L~ C84 ) by L542 , JORDAN3:1;
L547: ( C84 /. ( len C84 ) ) in ( ( RightComp C83 ) /\ ( L~ C84 ) ) by L546 , L541 , XBOOLE_0:def 4;
L548: ( RightComp C83 ) meets ( L~ C84 ) by L547 , XBOOLE_0:4;
L549: ( LeftComp C83 ) misses ( RightComp C83 ) by SPRECT_1:88;
assume L550: ( L~ C83 ) misses ( L~ C84 );
L551: ( L~ C84 ) c= ( ( L~ C83 ) ` ) by L550 , SUBSET_1:23;
L552: ( L~ C84 ) c= ( ( LeftComp C83 ) \/ ( RightComp C83 ) ) by L551 , GOBRD12:10;
L553: ( L~ C84 ) is_an_arc_of ( C84 /. 1 ) , ( C84 /. ( len C84 ) ) by TOPREAL1:25;
L554: ( RightComp C83 ) is  open by L350;
L555: ( LeftComp C83 ) is  open by L350;
thus L556: contradiction by L555 , L552 , L554 , L545 , L548 , L549 , L553 , JORDAN6:10 , TOPREAL5:1;
end;
theorem
L557: (for B68 being  rectangular special_circular_sequence holds ( SpStSeq ( L~ B68 ) ) = B68)
proof
let C85 being  rectangular special_circular_sequence;
set D19 = ( L~ C85 );
set D20 = ( SpStSeq D19 );
consider C86 being non  vertical non  horizontal non  empty  compact (Subset of ( TOP-REAL 2 )) such that L558: C85 = ( SpStSeq C86 ) by SPRECT_1:def 2;
L559: 5 = ( len C85 ) by SPRECT_1:82;
L560: ( SpStSeq ( L~ C85 ) ) = ( <* ( NW-corner ( L~ C85 ) ) , ( NE-corner ( L~ C85 ) ) , ( SE-corner ( L~ C85 ) ) *> ^ <* ( SW-corner ( L~ C85 ) ) , ( NW-corner ( L~ C85 ) ) *> ) by SPRECT_1:def 1;
L561: ( len D20 ) = ( ( len <* ( NW-corner ( L~ C85 ) ) , ( NE-corner ( L~ C85 ) ) , ( SE-corner ( L~ C85 ) ) *> ) + ( len <* ( SW-corner ( L~ C85 ) ) , ( NW-corner ( L~ C85 ) ) *> ) ) by L560 , FINSEQ_1:22
.= ( 3 + ( len <* ( SW-corner ( L~ C85 ) ) , ( NW-corner ( L~ C85 ) ) *> ) ) by FINSEQ_1:45
.= ( 3 + 2 ) by FINSEQ_1:44;
L562: (for B69 being Nat holds (B69 in ( dom C85 ) implies ( C85 /. B69 ) = ( D20 /. B69 )))
proof
let C87 being Nat;
assume L563: C87 in ( dom C85 );
L564: ( 0 ) <> C87 by L563 , FINSEQ_3:25;
L565: C87 <= ( len C85 ) by L563 , FINSEQ_3:25;
L566: ( C85 /. 1 ) = ( W-max D19 ) by SPRECT_1:83
.= ( NW-corner C86 ) by L558 , SPRECT_1:75
.= ( NW-corner D19 ) by L558 , SPRECT_1:62
.= ( D20 /. 1 ) by SPRECT_1:35;
per cases  by L559 , L564 , L565 , NAT_1:29;
suppose L567: C87 = 1;

thus L568: thesis by L567 , L566;
end;
suppose L569: C87 = 2;

thus L570: ( C85 /. C87 ) = ( E-max D19 ) by L569 , SPRECT_1:84
.= ( NE-corner C86 ) by L558 , SPRECT_1:79
.= ( NE-corner D19 ) by L558 , SPRECT_1:63
.= ( D20 /. C87 ) by L569 , SPRECT_1:36;
end;
suppose L571: C87 = 3;

thus L572: ( C85 /. C87 ) = ( E-min D19 ) by L571 , SPRECT_1:85
.= ( SE-corner C86 ) by L558 , SPRECT_1:78
.= ( SE-corner D19 ) by L558 , SPRECT_1:65
.= ( D20 /. C87 ) by L571 , SPRECT_1:37;
end;
suppose L573: C87 = 4;

thus L574: ( C85 /. C87 ) = ( W-min D19 ) by L573 , SPRECT_1:86
.= ( SW-corner C86 ) by L558 , SPRECT_1:74
.= ( SW-corner D19 ) by L558 , SPRECT_1:64
.= ( D20 /. C87 ) by L573 , SPRECT_1:38;
end;
suppose L575: C87 = 5;

thus L576: ( C85 /. C87 ) = ( C85 /. 1 ) by L575 , L559 , FINSEQ_6:def 1
.= ( D20 /. C87 ) by L561 , L566 , L575 , FINSEQ_6:def 1;
end;
end;
L578: ( dom C85 ) = ( dom D20 ) by L559 , L561 , FINSEQ_3:29;
thus L579: thesis by L578 , L562 , FINSEQ_5:12;
end;
theorem
L580: (for B70 being  rectangular special_circular_sequence holds ( L~ B70 ) = { B71 where B71 is (Point of ( TOP-REAL 2 )) : ((( B71 `1 ) = ( W-bound ( L~ B70 ) ) & ( B71 `2 ) <= ( N-bound ( L~ B70 ) ) & ( B71 `2 ) >= ( S-bound ( L~ B70 ) )) or (( B71 `1 ) <= ( E-bound ( L~ B70 ) ) & ( B71 `1 ) >= ( W-bound ( L~ B70 ) ) & ( B71 `2 ) = ( N-bound ( L~ B70 ) )) or (( B71 `1 ) <= ( E-bound ( L~ B70 ) ) & ( B71 `1 ) >= ( W-bound ( L~ B70 ) ) & ( B71 `2 ) = ( S-bound ( L~ B70 ) )) or (( B71 `1 ) = ( E-bound ( L~ B70 ) ) & ( B71 `2 ) <= ( N-bound ( L~ B70 ) ) & ( B71 `2 ) >= ( S-bound ( L~ B70 ) ))) })
proof
let C88 being  rectangular special_circular_sequence;
set D21 = ( L~ C88 );
set D22 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (( R6 `1 ) = ( E-bound D21 ) & ( R6 `2 ) <= ( N-bound D21 ) & ( R6 `2 ) >= ( S-bound D21 )) };
set D23 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (( R6 `1 ) <= ( E-bound D21 ) & ( R6 `1 ) >= ( W-bound D21 ) & ( R6 `2 ) = ( S-bound D21 )) };
set D24 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (( R6 `1 ) <= ( E-bound D21 ) & ( R6 `1 ) >= ( W-bound D21 ) & ( R6 `2 ) = ( N-bound D21 )) };
set D25 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (( R6 `1 ) = ( W-bound D21 ) & ( R6 `2 ) <= ( N-bound D21 ) & ( R6 `2 ) >= ( S-bound D21 )) };
L581: ( LSeg (( SE-corner D21 ) , ( NE-corner D21 )) ) = D22 by SPRECT_1:23;
L582: ( LSeg (( SW-corner D21 ) , ( SE-corner D21 )) ) = D23 by SPRECT_1:24;
L583: ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) ) = D25 by SPRECT_1:26;
L584: ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) = D24 by SPRECT_1:25;
L585: D21 = ( L~ ( SpStSeq D21 ) ) by L557;
thus L586: D21 c= { B72 where B72 is (Point of ( TOP-REAL 2 )) : ((( B72 `1 ) = ( W-bound D21 ) & ( B72 `2 ) <= ( N-bound D21 ) & ( B72 `2 ) >= ( S-bound D21 )) or (( B72 `1 ) <= ( E-bound D21 ) & ( B72 `1 ) >= ( W-bound D21 ) & ( B72 `2 ) = ( N-bound D21 )) or (( B72 `1 ) <= ( E-bound D21 ) & ( B72 `1 ) >= ( W-bound D21 ) & ( B72 `2 ) = ( S-bound D21 )) or (( B72 `1 ) = ( E-bound D21 ) & ( B72 `2 ) <= ( N-bound D21 ) & ( B72 `2 ) >= ( S-bound D21 ))) }
proof
let C89 being set;
assume L587: C89 in D21;
reconsider D26 = C89 as (Point of ( TOP-REAL 2 )) by L587;
L588: D26 in ( ( ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) \/ ( LSeg (( NE-corner D21 ) , ( SE-corner D21 )) ) ) \/ ( ( LSeg (( SE-corner D21 ) , ( SW-corner D21 )) ) \/ ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) ) ) ) by L585 , L587 , SPRECT_1:41;
L589: (D26 in ( ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) \/ ( LSeg (( NE-corner D21 ) , ( SE-corner D21 )) ) ) or D26 in ( ( LSeg (( SE-corner D21 ) , ( SW-corner D21 )) ) \/ ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) ) )) by L588 , XBOOLE_0:def 3;
L590: (D26 in ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) or D26 in ( LSeg (( NE-corner D21 ) , ( SE-corner D21 )) ) or D26 in ( LSeg (( SE-corner D21 ) , ( SW-corner D21 )) ) or D26 in ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) )) by L589 , XBOOLE_0:def 3;
L591: ((ex R6 being (Point of ( TOP-REAL 2 )) st (C89 = R6 & ( R6 `1 ) = ( E-bound D21 ) & ( R6 `2 ) <= ( N-bound D21 ) & ( R6 `2 ) >= ( S-bound D21 ))) or (ex R6 being (Point of ( TOP-REAL 2 )) st (C89 = R6 & ( R6 `1 ) <= ( E-bound D21 ) & ( R6 `1 ) >= ( W-bound D21 ) & ( R6 `2 ) = ( S-bound D21 ))) or (ex R6 being (Point of ( TOP-REAL 2 )) st (C89 = R6 & ( R6 `1 ) <= ( E-bound D21 ) & ( R6 `1 ) >= ( W-bound D21 ) & ( R6 `2 ) = ( N-bound D21 ))) or (ex R6 being (Point of ( TOP-REAL 2 )) st (C89 = R6 & ( R6 `1 ) = ( W-bound D21 ) & ( R6 `2 ) <= ( N-bound D21 ) & ( R6 `2 ) >= ( S-bound D21 )))) by L590 , L581 , L582 , L584 , L583;
thus L592: thesis by L591;
end;

let C90 being set;
assume L593: C90 in { B73 where B73 is (Point of ( TOP-REAL 2 )) : ((( B73 `1 ) = ( W-bound D21 ) & ( B73 `2 ) <= ( N-bound D21 ) & ( B73 `2 ) >= ( S-bound D21 )) or (( B73 `1 ) <= ( E-bound D21 ) & ( B73 `1 ) >= ( W-bound D21 ) & ( B73 `2 ) = ( N-bound D21 )) or (( B73 `1 ) <= ( E-bound D21 ) & ( B73 `1 ) >= ( W-bound D21 ) & ( B73 `2 ) = ( S-bound D21 )) or (( B73 `1 ) = ( E-bound D21 ) & ( B73 `2 ) <= ( N-bound D21 ) & ( B73 `2 ) >= ( S-bound D21 ))) };
L594: (ex R6 being (Point of ( TOP-REAL 2 )) st (C90 = R6 & ((( R6 `1 ) = ( W-bound D21 ) & ( R6 `2 ) <= ( N-bound D21 ) & ( R6 `2 ) >= ( S-bound D21 )) or (( R6 `1 ) <= ( E-bound D21 ) & ( R6 `1 ) >= ( W-bound D21 ) & ( R6 `2 ) = ( N-bound D21 )) or (( R6 `1 ) <= ( E-bound D21 ) & ( R6 `1 ) >= ( W-bound D21 ) & ( R6 `2 ) = ( S-bound D21 )) or (( R6 `1 ) = ( E-bound D21 ) & ( R6 `2 ) <= ( N-bound D21 ) & ( R6 `2 ) >= ( S-bound D21 ))))) by L593;
L595: (C90 in ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) or C90 in ( LSeg (( NE-corner D21 ) , ( SE-corner D21 )) ) or C90 in ( LSeg (( SE-corner D21 ) , ( SW-corner D21 )) ) or C90 in ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) )) by L594 , L581 , L582 , L584 , L583;
L596: (C90 in ( ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) \/ ( LSeg (( NE-corner D21 ) , ( SE-corner D21 )) ) ) or C90 in ( ( LSeg (( SE-corner D21 ) , ( SW-corner D21 )) ) \/ ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) ) )) by L595 , XBOOLE_0:def 3;
L597: C90 in ( ( ( LSeg (( NW-corner D21 ) , ( NE-corner D21 )) ) \/ ( LSeg (( NE-corner D21 ) , ( SE-corner D21 )) ) ) \/ ( ( LSeg (( SE-corner D21 ) , ( SW-corner D21 )) ) \/ ( LSeg (( SW-corner D21 ) , ( NW-corner D21 )) ) ) ) by L596 , XBOOLE_0:def 3;
thus L598: thesis by L597 , L585 , SPRECT_1:41;
end;
theorem
L599: (for B74 being  rectangular special_circular_sequence holds ( GoB B74 ) = ( (( B74 /. 4 ) , ( B74 /. 1 )) ][ (( B74 /. 3 ) , ( B74 /. 2 )) ))
proof
let C91 being  rectangular special_circular_sequence;
set D27 = ( (( C91 /. 4 ) , ( C91 /. 1 )) ][ (( C91 /. 3 ) , ( C91 /. 2 )) );
set D28 = ( Incr ( X_axis C91 ) );
set D29 = ( Incr ( Y_axis C91 ) );
L600: ( C91 /. 2 ) = ( N-max ( L~ C91 ) ) by SPRECT_1:84;
L601: ( C91 /. 1 ) = ( N-min ( L~ C91 ) ) by SPRECT_1:83;
L602: ( ( C91 /. 1 ) `1 ) < ( ( C91 /. 2 ) `1 ) by L601 , L600 , SPRECT_2:51;
L603: ( ( C91 /. 2 ) `2 ) = ( ( C91 /. 1 ) `2 ) by L601 , L600 , PSCOMP_1:37;
L604: ( C91 /. 4 ) = ( S-min ( L~ C91 ) ) by SPRECT_1:86;
L605: ( C91 /. 3 ) = ( S-max ( L~ C91 ) ) by SPRECT_1:85;
L606: ( ( C91 /. 3 ) `2 ) = ( ( C91 /. 4 ) `2 ) by L605 , L604 , PSCOMP_1:53;
L607: ( len <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> ) = 3 by FINSEQ_1:45;
L608: ( len C91 ) = 5 by SPRECT_1:82;
L609: ( C91 /. 1 ) = ( C91 /. 5 ) by L608 , FINSEQ_6:def 1;
set D30 = <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *>;
set D31 = ( <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> ^ <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> );
L610: ( C91 /. 3 ) = ( E-min ( L~ C91 ) ) by SPRECT_1:85;
L611: ( C91 /. 2 ) = ( E-max ( L~ C91 ) ) by SPRECT_1:84;
L612: ( ( C91 /. 3 ) `1 ) = ( ( C91 /. 2 ) `1 ) by L611 , L610 , PSCOMP_1:45;
L613: ( len D30 ) = 2 by FINSEQ_1:44;
L614: ( dom D30 ) = { 1 , 2 } by FINSEQ_1:2 , FINSEQ_1:89;
L615: D30 is  increasing
proof
L616: ( D30 . 2 ) = ( ( C91 /. 2 ) `1 ) by FINSEQ_1:44;
L617: ( D30 . 1 ) = ( ( C91 /. 1 ) `1 ) by FINSEQ_1:44;
let R4 being (Element of ( NAT ));
let R5 being (Element of ( NAT ));
assume that
L618: R4 in ( dom D30 )
and
L619: R5 in ( dom D30 )
and
L620: R4 < R5;
L621: (R5 = 1 or R5 = 2) by L614 , L619 , TARSKI:def 2;
L622: (R4 = 1 or R4 = 2) by L614 , L618 , TARSKI:def 2;
thus L623: ( D30 . R4 ) < ( D30 . R5 ) by L622 , L601 , L600 , L620 , L617 , L616 , L621 , SPRECT_2:51;
end;
L624: ( C91 /. 4 ) = ( W-min ( L~ C91 ) ) by SPRECT_1:86;
L625: ( len D31 ) = ( ( len <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> ) + ( len <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> ) ) by FINSEQ_1:22
.= ( ( len <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> ) + 3 ) by FINSEQ_1:45
.= ( 2 + 3 ) by FINSEQ_1:44
.= ( len C91 ) by SPRECT_1:82;
L626: (for R4 being (Element of ( NAT )) holds (R4 in ( dom D31 ) implies ( D31 . R4 ) = ( ( C91 /. R4 ) `1 )))
proof
let R4 being (Element of ( NAT ));
assume L627: R4 in ( dom D31 );
L628: 1 <= R4 by L627 , FINSEQ_3:25;
L629: R4 <= 5 by L608 , L625 , L627 , FINSEQ_3:25;
per cases  by L628 , L629 , NAT_1:29;
suppose L630: R4 = 1;

L631: R4 in ( dom D30 ) by L630 , L613 , FINSEQ_3:25;
thus L632: ( D31 . R4 ) = ( <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> . 1 ) by L631 , L630 , FINSEQ_1:def 7
.= ( ( C91 /. R4 ) `1 ) by L630 , FINSEQ_1:44;
end;
suppose L633: R4 = 2;

L634: R4 in ( dom D30 ) by L633 , L613 , FINSEQ_3:25;
thus L635: ( D31 . R4 ) = ( <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> . 2 ) by L634 , L633 , FINSEQ_1:def 7
.= ( ( C91 /. R4 ) `1 ) by L633 , FINSEQ_1:44;
end;
suppose L636: R4 = 3;

thus L637: ( D31 . R4 ) = ( D31 . ( 2 + 1 ) ) by L636
.= ( <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> . 1 ) by L613 , L607 , FINSEQ_1:65
.= ( ( C91 /. R4 ) `1 ) by L636 , FINSEQ_1:45;
end;
suppose L638: R4 = 4;

thus L639: ( D31 . R4 ) = ( D31 . ( 2 + 2 ) ) by L638
.= ( <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> . 2 ) by L613 , L607 , FINSEQ_1:65
.= ( ( C91 /. R4 ) `1 ) by L638 , FINSEQ_1:45;
end;
suppose L640: R4 = 5;

thus L641: ( D31 . R4 ) = ( D31 . ( 2 + 3 ) ) by L640
.= ( <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> . 3 ) by L613 , L607 , FINSEQ_1:65
.= ( ( C91 /. R4 ) `1 ) by L640 , FINSEQ_1:45;
end;
end;
L643: ( X_axis C91 ) = D31 by L626 , L625 , GOBOARD1:def 1;
L644: ( rng D30 ) = { ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) } by FINSEQ_2:127;
L645: ( C91 /. 1 ) = ( W-max ( L~ C91 ) ) by SPRECT_1:83;
L646: ( ( C91 /. 4 ) `2 ) < ( ( C91 /. 5 ) `2 ) by L645 , L624 , L609 , SPRECT_2:57;
L647: { ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) } c= { ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) }
proof
let C92 being set;
assume L648: C92 in { ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) };
per cases  by L648 , ENUMSET1:def 1;
suppose L649: C92 = ( ( C91 /. 3 ) `1 );

L650: C92 = ( ( C91 /. 2 ) `1 ) by L649 , L611 , L610 , PSCOMP_1:45;
thus L651: thesis by L650 , TARSKI:def 2;
end;
suppose L652: C92 = ( ( C91 /. 4 ) `1 );

L653: C92 = ( ( C91 /. 1 ) `1 ) by L652 , L645 , L624 , PSCOMP_1:29;
thus L654: thesis by L653 , TARSKI:def 2;
end;
suppose L655: C92 = ( ( C91 /. 5 ) `1 );

L656: C92 = ( ( C91 /. 1 ) `1 ) by L655 , L608 , FINSEQ_6:def 1;
thus L657: thesis by L656 , TARSKI:def 2;
end;
end;
L659: ( rng D30 ) = ( ( rng <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> ) \/ { ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) } ) by L647 , L644 , XBOOLE_1:12
.= ( ( rng <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> ) \/ ( rng <* ( ( C91 /. 3 ) `1 ) , ( ( C91 /. 4 ) `1 ) , ( ( C91 /. 5 ) `1 ) *> ) ) by FINSEQ_2:128
.= ( rng ( X_axis C91 ) ) by L643 , FINSEQ_1:31;
L660: ( len D30 ) = 2 by FINSEQ_1:44
.= ( card ( rng ( X_axis C91 ) ) ) by L644 , L659 , L602 , CARD_2:57;
L661: D28 = <* ( ( C91 /. 1 ) `1 ) , ( ( C91 /. 2 ) `1 ) *> by L660 , L659 , L615 , SEQ_4:def 21;
L662: ( D28 . 1 ) = ( ( C91 /. 1 ) `1 ) by L661 , FINSEQ_1:44;
set D32 = <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *>;
set D33 = ( <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ^ <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *> );
L663: ( len D33 ) = ( ( len <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) + ( len <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *> ) ) by FINSEQ_1:22
.= ( ( len <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *> ) + 3 ) by FINSEQ_1:45
.= ( 2 + 3 ) by FINSEQ_1:44
.= ( len C91 ) by SPRECT_1:82;
L664: ( len <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) = 3 by FINSEQ_1:45;
L665: ( dom D32 ) = { 1 , 2 } by FINSEQ_1:2 , FINSEQ_1:89;
L666: D32 is  increasing
proof
L667: ( D32 . 2 ) = ( ( C91 /. 5 ) `2 ) by FINSEQ_1:44;
L668: ( D32 . 1 ) = ( ( C91 /. 4 ) `2 ) by FINSEQ_1:44;
let R4 being (Element of ( NAT ));
let R5 being (Element of ( NAT ));
assume that
L669: R4 in ( dom D32 )
and
L670: R5 in ( dom D32 )
and
L671: R4 < R5;
L672: (R5 = 1 or R5 = 2) by L665 , L670 , TARSKI:def 2;
L673: (R4 = 1 or R4 = 2) by L665 , L669 , TARSKI:def 2;
thus L674: ( D32 . R4 ) < ( D32 . R5 ) by L673 , L645 , L624 , L609 , L671 , L668 , L667 , L672 , SPRECT_2:57;
end;
L675: ( D28 . 2 ) = ( ( C91 /. 2 ) `1 ) by L661 , FINSEQ_1:44;
L676: ( len D32 ) = 2 by FINSEQ_1:44;
L677: (for R4 being (Element of ( NAT )) holds (R4 in ( dom D33 ) implies ( D33 . R4 ) = ( ( C91 /. R4 ) `2 )))
proof
let R4 being (Element of ( NAT ));
assume L678: R4 in ( dom D33 );
L679: 1 <= R4 by L678 , FINSEQ_3:25;
L680: R4 <= 5 by L608 , L663 , L678 , FINSEQ_3:25;
per cases  by L679 , L680 , NAT_1:29;
suppose L681: R4 = 1;

L682: R4 in ( dom <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) by L681 , L664 , FINSEQ_3:25;
thus L683: ( D33 . R4 ) = ( <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> . 1 ) by L682 , L681 , FINSEQ_1:def 7
.= ( ( C91 /. R4 ) `2 ) by L681 , FINSEQ_1:45;
end;
suppose L684: R4 = 2;

L685: R4 in ( dom <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) by L684 , L664 , FINSEQ_3:25;
thus L686: ( D33 . R4 ) = ( <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> . 2 ) by L685 , L684 , FINSEQ_1:def 7
.= ( ( C91 /. R4 ) `2 ) by L684 , FINSEQ_1:45;
end;
suppose L687: R4 = 3;

L688: R4 in ( dom <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) by L687 , L664 , FINSEQ_3:25;
thus L689: ( D33 . R4 ) = ( <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> . 3 ) by L688 , L687 , FINSEQ_1:def 7
.= ( ( C91 /. R4 ) `2 ) by L687 , FINSEQ_1:45;
end;
suppose L690: R4 = 4;

thus L691: ( D33 . R4 ) = ( D33 . ( 3 + 1 ) ) by L690
.= ( <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *> . 1 ) by L676 , L664 , FINSEQ_1:65
.= ( ( C91 /. R4 ) `2 ) by L690 , FINSEQ_1:44;
end;
suppose L692: R4 = 5;

thus L693: ( D33 . R4 ) = ( D33 . ( 2 + 3 ) ) by L692
.= ( <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *> . 2 ) by L676 , L664 , FINSEQ_1:65
.= ( ( C91 /. R4 ) `2 ) by L692 , FINSEQ_1:44;
end;
end;
L695: ( Y_axis C91 ) = D33 by L677 , L663 , GOBOARD1:def 2;
L696: ( rng D32 ) = { ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) } by FINSEQ_2:127;
L697: { ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) } c= { ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) }
proof
let C93 being set;
assume L698: C93 in { ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) };
per cases  by L698 , ENUMSET1:def 1;
suppose L699: C93 = ( ( C91 /. 1 ) `2 );

thus L700: thesis by L699 , L609 , TARSKI:def 2;
end;
suppose L701: C93 = ( ( C91 /. 2 ) `2 );

L702: C93 = ( ( C91 /. 1 ) `2 ) by L701 , L601 , L600 , PSCOMP_1:37;
thus L703: thesis by L702 , L609 , TARSKI:def 2;
end;
suppose L704: C93 = ( ( C91 /. 3 ) `2 );

L705: C93 = ( ( C91 /. 4 ) `2 ) by L704 , L605 , L604 , PSCOMP_1:53;
thus L706: thesis by L705 , TARSKI:def 2;
end;
end;
L708: ( rng D32 ) = ( { ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) } \/ { ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) } ) by L697 , L696 , XBOOLE_1:12
.= ( ( rng <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) \/ { ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) } ) by FINSEQ_2:128
.= ( ( rng <* ( ( C91 /. 1 ) `2 ) , ( ( C91 /. 2 ) `2 ) , ( ( C91 /. 3 ) `2 ) *> ) \/ ( rng <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 5 ) `2 ) *> ) ) by FINSEQ_2:127
.= ( rng ( Y_axis C91 ) ) by L695 , FINSEQ_1:31;
L709: ( len D32 ) = 2 by FINSEQ_1:44
.= ( card ( rng ( Y_axis C91 ) ) ) by L696 , L708 , L646 , CARD_2:57;
L710: D29 = <* ( ( C91 /. 4 ) `2 ) , ( ( C91 /. 1 ) `2 ) *> by L709 , L609 , L708 , L666 , SEQ_4:def 21;
L711: ( D29 . 1 ) = ( ( C91 /. 4 ) `2 ) by L710 , FINSEQ_1:44;
L712: ( D29 . 2 ) = ( ( C91 /. 1 ) `2 ) by L710 , FINSEQ_1:44;
L713: ( ( C91 /. 1 ) `1 ) = ( ( C91 /. 4 ) `1 ) by L645 , L624 , PSCOMP_1:29;
L714: (for R4 being (Element of ( NAT )) holds (for R5 being (Element of ( NAT )) holds ([ R4 , R5 ] in ( Indices D27 ) implies ( D27 * (R4 , R5) ) = |[ ( D28 . R4 ) , ( D29 . R5 ) ]|)))
proof
let R4 being (Element of ( NAT ));
let R5 being (Element of ( NAT ));
assume L715: [ R4 , R5 ] in ( Indices D27 );
L716: [ R4 , R5 ] in { [ 1 , 1 ] , [ 1 , 2 ] , [ 2 , 1 ] , [ 2 , 2 ] } by L715 , L5;
per cases  by L716 , ENUMSET1:def 2;
suppose L717: [ R4 , R5 ] = [ 1 , 1 ];

L718: R5 = 1 by L717 , XTUPLE_0:1;
L719: R4 = 1 by L717 , XTUPLE_0:1;
thus L720: ( D27 * (R4 , R5) ) = ( C91 /. 4 ) by L719 , L718 , MATRIX_2:6
.= |[ ( D28 . R4 ) , ( D29 . R5 ) ]| by L662 , L711 , L713 , L719 , L718 , EUCLID:53;
end;
suppose L721: [ R4 , R5 ] = [ 1 , 2 ];

L722: R5 = 2 by L721 , XTUPLE_0:1;
L723: R4 = 1 by L721 , XTUPLE_0:1;
thus L724: ( D27 * (R4 , R5) ) = ( C91 /. 1 ) by L723 , L722 , MATRIX_2:6
.= |[ ( D28 . R4 ) , ( D29 . R5 ) ]| by L662 , L712 , L723 , L722 , EUCLID:53;
end;
suppose L725: [ R4 , R5 ] = [ 2 , 1 ];

L726: R5 = 1 by L725 , XTUPLE_0:1;
L727: R4 = 2 by L725 , XTUPLE_0:1;
thus L728: ( D27 * (R4 , R5) ) = ( C91 /. 3 ) by L727 , L726 , MATRIX_2:6
.= |[ ( D28 . R4 ) , ( D29 . R5 ) ]| by L675 , L711 , L612 , L606 , L727 , L726 , EUCLID:53;
end;
suppose L729: [ R4 , R5 ] = [ 2 , 2 ];

L730: R5 = 2 by L729 , XTUPLE_0:1;
L731: R4 = 2 by L729 , XTUPLE_0:1;
thus L732: ( D27 * (R4 , R5) ) = ( C91 /. 2 ) by L731 , L730 , MATRIX_2:6
.= |[ ( D28 . R4 ) , ( D29 . R5 ) ]| by L675 , L712 , L603 , L731 , L730 , EUCLID:53;
end;
end;
L734: ( width D27 ) = 2 by MATRIX_2:3
.= ( len D29 ) by L710 , FINSEQ_1:44;
L735: ( len D27 ) = 2 by MATRIX_2:3
.= ( len D28 ) by L661 , FINSEQ_1:44;
L736: ( GoB (D28 , D29) ) = D27 by L735 , L734 , L714 , GOBOARD2:def 1;
thus L737: thesis by L736 , GOBOARD2:def 2;
end;
theorem
L738: (for B75 being  rectangular special_circular_sequence holds (( LeftComp B75 ) = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (not (( W-bound ( L~ B75 ) ) <= ( R6 `1 ) & ( R6 `1 ) <= ( E-bound ( L~ B75 ) ) & ( S-bound ( L~ B75 ) ) <= ( R6 `2 ) & ( R6 `2 ) <= ( N-bound ( L~ B75 ) ))) } & ( RightComp B75 ) = { R7 where R7 is (Point of ( TOP-REAL 2 )) : (( W-bound ( L~ B75 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ B75 ) ) & ( S-bound ( L~ B75 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ B75 ) )) }))
proof
let C94 being  rectangular special_circular_sequence;
defpred S1[ (Element of ( TOP-REAL 2 )) ] means (not (( W-bound ( L~ C94 ) ) <= ( $1 `1 ) & ( $1 `1 ) <= ( E-bound ( L~ C94 ) ) & ( S-bound ( L~ C94 ) ) <= ( $1 `2 ) & ( $1 `2 ) <= ( N-bound ( L~ C94 ) )));
defpred S2[ (Element of ( TOP-REAL 2 )) ] means (( W-bound ( L~ C94 ) ) < ( $1 `1 ) & ( $1 `1 ) < ( E-bound ( L~ C94 ) ) & ( S-bound ( L~ C94 ) ) < ( $1 `2 ) & ( $1 `2 ) < ( N-bound ( L~ C94 ) ));
defpred S3[ (Element of ( TOP-REAL 2 )) ] means ((( $1 `1 ) = ( W-bound ( L~ C94 ) ) & ( $1 `2 ) <= ( N-bound ( L~ C94 ) ) & ( $1 `2 ) >= ( S-bound ( L~ C94 ) )) or (( $1 `1 ) <= ( E-bound ( L~ C94 ) ) & ( $1 `1 ) >= ( W-bound ( L~ C94 ) ) & ( $1 `2 ) = ( N-bound ( L~ C94 ) )) or (( $1 `1 ) <= ( E-bound ( L~ C94 ) ) & ( $1 `1 ) >= ( W-bound ( L~ C94 ) ) & ( $1 `2 ) = ( S-bound ( L~ C94 ) )) or (( $1 `1 ) = ( E-bound ( L~ C94 ) ) & ( $1 `2 ) <= ( N-bound ( L~ C94 ) ) & ( $1 `2 ) >= ( S-bound ( L~ C94 ) )));
set D34 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : S1[ R6 ] };
set D35 = { R7 where R7 is (Point of ( TOP-REAL 2 )) : S2[ R7 ] };
set D36 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : S3[ R6 ] };
L739: ( S-bound ( L~ C94 ) ) < ( N-bound ( L~ C94 ) ) by SPRECT_1:32;
L740: D36 is (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
L741: D35 is (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
L742: ( L~ C94 ) = D36 by L580;
L743: D34 is (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
reconsider D37 = D34 , D38 = D35 , D39 = D36 as (Subset of ( TOP-REAL 2 )) by L743 , L741 , L740;
reconsider D40 = D39 as (Subset of ( TOP-REAL 2 ));
reconsider D41 = D37 , D42 = D38 as (Subset of ( TOP-REAL 2 ));
L744: ( W-bound ( L~ C94 ) ) < ( E-bound ( L~ C94 ) ) by SPRECT_1:31;
reconsider D43 = D41 , D44 = D42 as (Subset of ( ( TOP-REAL 2 ) | ( D40 ` ) )) by L744 , L739 , JORDAN1:39 , JORDAN1:41;
reconsider D45 = D43 , D46 = D44 as (Subset of ( ( TOP-REAL 2 ) | ( D40 ` ) ));
L745: ( ( ( 1 / 2 ) * ( S-bound ( L~ C94 ) ) ) + ( ( 1 / 2 ) * ( S-bound ( L~ C94 ) ) ) ) = ( S-bound ( L~ C94 ) );
L746: D46 = D42;
L747: D45 is  a_component by L746 , L744 , L739 , JORDAN1:36;
L748: D41 is_a_component_of ( D40 ` ) by L747 , CONNSP_1:def 6;
set D47 = ( ( ( 1 / 2 ) * ( ( ( GoB C94 ) * (1 , ( width ( GoB C94 ) )) ) + ( ( GoB C94 ) * (( 1 + 1 ) , ( width ( GoB C94 ) )) ) ) ) + |[ ( 0 ) , 1 ]| );
set D48 = ( ( 1 / 2 ) * ( ( ( GoB C94 ) * (1 , ( width ( GoB C94 ) )) ) + ( ( GoB C94 ) * (( 1 + 1 ) , ( width ( GoB C94 ) )) ) ) );
L749: ( 1 + 1 ) <= ( len C94 ) by GOBOARD7:34 , XXREAL_0:2;
L750: ( D47 `2 ) = ( ( D48 `2 ) + ( |[ ( 0 ) , 1 ]| `2 ) ) by TOPREAL3:2
.= ( ( D48 `2 ) + 1 ) by EUCLID:52;
L751: ( GoB C94 ) = ( (( C94 /. 4 ) , ( C94 /. 1 )) ][ (( C94 /. 3 ) , ( C94 /. 2 )) ) by L599;
L752: ( 1 + 1 ) = ( width ( GoB C94 ) ) by L751 , MATRIX_2:3;
L753: ( D48 `2 ) = ( ( ( 1 / 2 ) * ( ( ( GoB C94 ) * (1 , ( width ( GoB C94 ) )) ) + ( C94 /. 2 ) ) ) `2 ) by L752 , L751 , MATRIX_2:6
.= ( ( ( 1 / 2 ) * ( ( C94 /. 1 ) + ( C94 /. 2 ) ) ) `2 ) by L751 , L752 , MATRIX_2:6
.= ( ( 1 / 2 ) * ( ( ( C94 /. 1 ) + ( C94 /. 2 ) ) `2 ) ) by TOPREAL3:4
.= ( ( 1 / 2 ) * ( ( ( C94 /. 1 ) `2 ) + ( ( C94 /. 2 ) `2 ) ) ) by TOPREAL3:2
.= ( ( 1 / 2 ) * ( ( ( N-min ( L~ C94 ) ) `2 ) + ( ( C94 /. 2 ) `2 ) ) ) by SPRECT_1:83
.= ( ( 1 / 2 ) * ( ( ( N-min ( L~ C94 ) ) `2 ) + ( ( N-max ( L~ C94 ) ) `2 ) ) ) by SPRECT_1:84
.= ( ( 1 / 2 ) * ( ( N-bound ( L~ C94 ) ) + ( ( N-max ( L~ C94 ) ) `2 ) ) ) by EUCLID:52
.= ( ( 1 / 2 ) * ( ( N-bound ( L~ C94 ) ) + ( N-bound ( L~ C94 ) ) ) ) by EUCLID:52
.= ( N-bound ( L~ C94 ) );
L754: ( D47 `2 ) > ( ( 0 ) + ( N-bound ( L~ C94 ) ) ) by L753 , L750 , XREAL_1:8;
L755: D47 in D34 by L754;
L756: ( 1 + 1 ) = ( len ( GoB C94 ) ) by L751 , MATRIX_2:3;
L757: D47 in ( Int ( cell (( GoB C94 ) , 1 , ( 1 + 1 )) ) ) by L756 , L752 , GOBOARD6:32;
L758: ( C94 /. ( 1 + 1 ) ) = ( ( GoB C94 ) * (( 1 + 1 ) , ( 1 + 1 )) ) by L751 , MATRIX_2:6;
L759: 1 < ( width ( GoB C94 ) ) by GOBOARD7:33;
L760: ( 1 + 1 ) <= ( width ( GoB C94 ) ) by L759 , NAT_1:13;
L761: [ ( 1 + 1 ) , ( 1 + 1 ) ] in ( Indices ( GoB C94 ) ) by L760 , L756 , MATRIX_1:36;
L762: 1 <= ( len ( GoB C94 ) ) by GOBOARD7:32;
L763: [ 1 , ( 1 + 1 ) ] in ( Indices ( GoB C94 ) ) by L762 , L760 , MATRIX_1:36;
L764: ( C94 /. 1 ) = ( ( GoB C94 ) * (1 , ( 1 + 1 )) ) by L751 , MATRIX_2:6;
L765: ( right_cell (C94 , 1) ) = ( cell (( GoB C94 ) , 1 , 1) ) by L764 , L749 , L763 , L761 , L758 , GOBOARD5:28;
L766: ( Int ( cell (( GoB C94 ) , 1 , 1) ) ) c= ( RightComp C94 ) by L765 , GOBOARD9:def 2;
L767: ( left_cell (C94 , 1) ) = ( cell (( GoB C94 ) , 1 , ( 1 + 1 )) ) by L749 , L763 , L764 , L761 , L758 , GOBOARD5:28;
L768: ( Int ( cell (( GoB C94 ) , 1 , ( 1 + 1 )) ) ) c= ( LeftComp C94 ) by L767 , GOBOARD9:def 1;
L769: D34 meets ( LeftComp C94 ) by L768 , L757 , L755 , XBOOLE_0:3;
L770: ( ( C94 /. 2 ) `1 ) = ( ( E-max ( L~ C94 ) ) `1 ) by SPRECT_1:84
.= ( E-bound ( L~ C94 ) ) by EUCLID:52;
set D49 = ( ( 1 / 2 ) * ( ( ( GoB C94 ) * (1 , 1) ) + ( ( GoB C94 ) * (2 , 2) ) ) );
L771: D49 in ( Int ( cell (( GoB C94 ) , 1 , 1) ) ) by L756 , L752 , GOBOARD6:31;
L772: D49 = ( ( 1 / 2 ) * ( ( ( GoB C94 ) * (1 , 1) ) + ( C94 /. 2 ) ) ) by L751 , MATRIX_2:6
.= ( ( 1 / 2 ) * ( ( C94 /. 4 ) + ( C94 /. 2 ) ) ) by L751 , MATRIX_2:6;
L773: ( D49 `1 ) = ( ( 1 / 2 ) * ( ( ( C94 /. 4 ) + ( C94 /. 2 ) ) `1 ) ) by L772 , TOPREAL3:4
.= ( ( 1 / 2 ) * ( ( ( C94 /. 4 ) `1 ) + ( ( C94 /. 2 ) `1 ) ) ) by TOPREAL3:2
.= ( ( ( 1 / 2 ) * ( ( C94 /. 4 ) `1 ) ) + ( ( 1 / 2 ) * ( ( C94 /. 2 ) `1 ) ) );
L774: ( LeftComp C94 ) is_a_component_of ( ( L~ C94 ) ` ) by GOBOARD9:def 1;
thus L775: ( LeftComp C94 ) = D34 by L774 , L742 , L748 , L769 , GOBOARD9:1;
L776: ( ( ( 1 / 2 ) * ( W-bound ( L~ C94 ) ) ) + ( ( 1 / 2 ) * ( W-bound ( L~ C94 ) ) ) ) = ( W-bound ( L~ C94 ) );
L777: ( ( ( 1 / 2 ) * ( E-bound ( L~ C94 ) ) ) + ( ( 1 / 2 ) * ( E-bound ( L~ C94 ) ) ) ) = ( E-bound ( L~ C94 ) );
L778: ( ( ( 1 / 2 ) * ( N-bound ( L~ C94 ) ) ) + ( ( 1 / 2 ) * ( N-bound ( L~ C94 ) ) ) ) = ( N-bound ( L~ C94 ) );
L779: ( ( C94 /. 4 ) `1 ) = ( ( W-min ( L~ C94 ) ) `1 ) by SPRECT_1:86
.= ( W-bound ( L~ C94 ) ) by EUCLID:52;
L780: ( ( 1 / 2 ) * ( ( C94 /. 4 ) `1 ) ) < ( ( 1 / 2 ) * ( E-bound ( L~ C94 ) ) ) by L779 , SPRECT_1:31 , XREAL_1:68;
L781: ( D49 `1 ) < ( E-bound ( L~ C94 ) ) by L780 , L777 , L773 , L770 , XREAL_1:6;
L782: ( D49 `2 ) = ( ( 1 / 2 ) * ( ( ( C94 /. 4 ) + ( C94 /. 2 ) ) `2 ) ) by L772 , TOPREAL3:4
.= ( ( 1 / 2 ) * ( ( ( C94 /. 4 ) `2 ) + ( ( C94 /. 2 ) `2 ) ) ) by TOPREAL3:2
.= ( ( ( 1 / 2 ) * ( ( C94 /. 4 ) `2 ) ) + ( ( 1 / 2 ) * ( ( C94 /. 2 ) `2 ) ) );
L783: D45 = D41;
L784: D46 is  a_component by L783 , L744 , L739 , JORDAN1:36;
L785: D42 is_a_component_of ( D40 ` ) by L784 , CONNSP_1:def 6;
L786: ( ( C94 /. 2 ) `2 ) = ( ( N-max ( L~ C94 ) ) `2 ) by SPRECT_1:84
.= ( N-bound ( L~ C94 ) ) by EUCLID:52;
L787: ( ( C94 /. 4 ) `2 ) = ( ( S-min ( L~ C94 ) ) `2 ) by SPRECT_1:86
.= ( S-bound ( L~ C94 ) ) by EUCLID:52;
L788: ( ( 1 / 2 ) * ( ( C94 /. 4 ) `2 ) ) < ( ( 1 / 2 ) * ( N-bound ( L~ C94 ) ) ) by L787 , SPRECT_1:32 , XREAL_1:68;
L789: ( D49 `2 ) < ( N-bound ( L~ C94 ) ) by L788 , L778 , L782 , L786 , XREAL_1:6;
L790: ( ( 1 / 2 ) * ( ( C94 /. 2 ) `2 ) ) > ( ( 1 / 2 ) * ( S-bound ( L~ C94 ) ) ) by L786 , SPRECT_1:32 , XREAL_1:68;
L791: ( S-bound ( L~ C94 ) ) < ( D49 `2 ) by L790 , L745 , L782 , L787 , XREAL_1:6;
L792: ( ( 1 / 2 ) * ( ( C94 /. 2 ) `1 ) ) > ( ( 1 / 2 ) * ( W-bound ( L~ C94 ) ) ) by L770 , SPRECT_1:31 , XREAL_1:68;
L793: ( W-bound ( L~ C94 ) ) < ( D49 `1 ) by L792 , L776 , L773 , L779 , XREAL_1:6;
L794: D49 in D35 by L793 , L781 , L791 , L789;
L795: D35 meets ( RightComp C94 ) by L794 , L771 , L766 , XBOOLE_0:3;
L796: ( RightComp C94 ) is_a_component_of ( ( L~ C94 ) ` ) by GOBOARD9:def 2;
thus L797: thesis by L796 , L742 , L785 , L795 , GOBOARD9:1;
end;
registration
cluster  clockwise_oriented for  rectangular  rectangular  rectangular  rectangular special_circular_sequence;
existence
proof
set D50 = the non  empty  compact non  vertical non  horizontal (Subset of ( TOP-REAL 2 ));
L798: ( SpStSeq D50 ) is  clockwise_oriented;
thus L799: thesis by L798;
end;
end;
registration
cluster  ->  clockwise_oriented for  rectangular  rectangular  rectangular  rectangular special_circular_sequence;
coherence
proof
let C95 being  rectangular special_circular_sequence;
L801: (ex B76 being non  vertical non  horizontal non  empty  compact (Subset of ( TOP-REAL 2 )) st C95 = ( SpStSeq B76 )) by SPRECT_1:def 2;
thus L802: thesis by L801;
end;
end;
theorem
L804: (for B77 being  rectangular special_circular_sequence holds (for B78 being S-Sequence_in_R2 holds ((( B78 /. 1 ) in ( LeftComp B77 ) & ( B78 /. ( len B78 ) ) in ( RightComp B77 )) implies ( Last_Point (( L~ B78 ) , ( B78 /. 1 ) , ( B78 /. ( len B78 ) ) , ( L~ B77 )) ) <> ( NW-corner ( L~ B77 ) ))))
proof
let C96 being  rectangular special_circular_sequence;
let C97 being S-Sequence_in_R2;
assume that
L805: ( C97 /. 1 ) in ( LeftComp C96 )
and
L806: ( C97 /. ( len C97 ) ) in ( RightComp C96 );
L807: ( L~ C96 ) meets ( L~ C97 ) by L805 , L806 , L539;
assume L808: ( Last_Point (( L~ C97 ) , ( C97 /. 1 ) , ( C97 /. ( len C97 ) ) , ( L~ C96 )) ) = ( NW-corner ( L~ C96 ) );
set D51 = ( NW-corner ( L~ C96 ) );
set D52 = ( Index (D51 , C97) );
L809: ( len C97 ) in ( dom C97 ) by FINSEQ_5:6;
L810: ( C97 . ( len C97 ) ) = ( C97 /. ( len C97 ) ) by L809 , PARTFUN1:def 6;
L811: 1 <= ( D52 + 1 ) by NAT_1:11;
L812: ( L~ C97 ) is_an_arc_of ( C97 /. 1 ) , ( C97 /. ( len C97 ) ) by TOPREAL1:25;
L813: D51 in ( ( L~ C97 ) /\ ( L~ C96 ) ) by L812 , L807 , L808 , JORDAN5C:def 2;
L814: D51 in ( L~ C97 ) by L813 , XBOOLE_0:def 4;
L815: 1 <= D52 by L814 , JORDAN3:8;
L816: D51 in ( LSeg (C97 , D52) ) by L814 , JORDAN3:9;
L817: D52 < ( len C97 ) by L814 , JORDAN3:8;
L818: ( D52 + 1 ) <= ( len C97 ) by L817 , NAT_1:13;
L819: ( D52 + 1 ) in ( dom C97 ) by L818 , L811 , FINSEQ_3:25;
L820: ( L~ C96 ) misses ( RightComp C96 ) by L372;
L821:
now
L822: ( len C97 ) >= 1 by L818 , L811 , XXREAL_0:2;
assume L823: D51 <> ( C97 . ( D52 + 1 ) );
L824: D51 <> ( C97 /. ( D52 + 1 ) ) by L823 , L819 , PARTFUN1:def 6;
per cases ;
suppose L825: ( C97 /. ( D52 + 1 ) ) in ( L~ C96 );

L826: ( D52 + 1 ) <> ( len C97 ) by L825 , L806 , L820 , XBOOLE_0:3;
L827: ( D52 + 1 ) < ( len C97 ) by L826 , L818 , XXREAL_0:1;
L828: ( ( D52 + 1 ) + 1 ) <= ( len C97 ) by L827 , NAT_1:13;
L829: ( C97 /. ( D52 + 1 ) ) in ( LSeg (C97 , ( D52 + 1 )) ) by L828 , L811 , TOPREAL1:21;
L830: D52 >= ( D52 + 1 ) by L829 , L807 , L808 , L815 , L818 , L816 , L811 , L824 , L825 , L828 , JORDAN5C:28;
thus L831: contradiction by L830 , XREAL_1:29;
end;
suppose L832: (not ( C97 /. ( D52 + 1 ) ) in ( L~ C96 ));

L833:
now
assume L834: ( C97 /. ( D52 + 1 ) ) in ( RightComp C96 );
L835: ( RightComp C96 ) = { R7 where R7 is (Point of ( TOP-REAL 2 )) : (( W-bound ( L~ C96 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C96 ) ) & ( S-bound ( L~ C96 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C96 ) )) } by L738;
L836: (ex R7 being (Point of ( TOP-REAL 2 )) st (( C97 /. ( D52 + 1 ) ) = R7 & ( W-bound ( L~ C96 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C96 ) ) & ( S-bound ( L~ C96 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C96 ) ))) by L835 , L834;
L837: (( LSeg (C97 , D52) ) is  vertical or ( LSeg (C97 , D52) ) is  horizontal) by SPPOL_1:19;
L838: ( LSeg (C97 , D52) ) = ( LSeg (( C97 /. D52 ) , ( C97 /. ( D52 + 1 ) )) ) by L815 , L818 , TOPREAL1:def 3;
L839: (( ( C97 /. ( D52 + 1 ) ) `1 ) = ( D51 `1 ) or ( ( C97 /. ( D52 + 1 ) ) `2 ) = ( D51 `2 )) by L838 , L816 , L837 , SPPOL_1:40 , SPPOL_1:41;
thus L840: contradiction by L839 , L836 , EUCLID:52;
end;
reconsider D53 = ( mid (C97 , ( D52 + 1 ) , ( len C97 )) ) as S-Sequence_in_R2 by L833 , L806 , L818 , L811 , L822 , JORDAN3:6;
L841: ( D52 + 1 ) < ( len C97 ) by L806 , L818 , L833 , XXREAL_0:1;
L842: ( C97 /. ( D52 + 1 ) ) in ( ( L~ C96 ) ` ) by L832 , SUBSET_1:29;
L843: ( C97 /. ( D52 + 1 ) ) in ( ( LeftComp C96 ) \/ ( RightComp C96 ) ) by L842 , GOBRD12:10;
L844: ( C97 /. ( D52 + 1 ) ) in ( LeftComp C96 ) by L843 , L833 , XBOOLE_0:def 3;
L845: ( D53 /. 1 ) in ( LeftComp C96 ) by L844 , L809 , L819 , SPRECT_2:8;
L846: ( D53 /. ( len D53 ) ) in ( RightComp C96 ) by L806 , L809 , L819 , SPRECT_2:9;
L847: ( L~ C96 ) meets ( L~ D53 ) by L846 , L845 , L539;
consider C98 being set such that L848: C98 in ( L~ C96 ) and L849: C98 in ( L~ D53 ) by L847 , XBOOLE_0:3;
reconsider D54 = C98 as (Point of ( TOP-REAL 2 )) by L849;
consider R1 being (Element of ( NAT )) such that L850: 1 <= R1 and L851: ( R1 + 1 ) <= ( len D53 ) and L852: D54 in ( LSeg (D53 , R1) ) by L849 , SPPOL_2:13;
set D55 = ( ( R1 + ( D52 + 1 ) ) -' 1 );
L853: D55 = ( ( ( R1 + D52 ) + 1 ) -' 1 )
.= ( R1 + D52 ) by NAT_D:34;
L854: ( len D53 ) = ( ( ( len C97 ) -' ( D52 + 1 ) ) + 1 ) by L818 , L811 , JORDAN4:8;
L855: ( len D53 ) = ( ( len C97 ) -' D52 ) by L854 , L814 , JORDAN3:8 , NAT_2:7;
L856: ( ( len D53 ) + D52 ) = ( len C97 ) by L855 , L817 , XREAL_1:235;
L857: ( ( R1 + 1 ) + D52 ) <= ( len C97 ) by L856 , L851 , XREAL_1:6;
L858: ( D55 + 1 ) <= ( len C97 ) by L857 , L853;
L859: R1 < ( len D53 ) by L851 , NAT_1:13;
L860: ( LSeg (D53 , R1) ) = ( LSeg (C97 , ( ( R1 + ( D52 + 1 ) ) -' 1 )) ) by L859 , L811 , L841 , L850 , L854 , JORDAN4:19;
L861: D55 >= ( D52 + 1 ) by L850 , L853 , XREAL_1:6;
L862:
now
assume L863: D51 = D54;
L864: D51 in ( ( LSeg (C97 , D52) ) /\ ( LSeg (C97 , D55) ) ) by L863 , L816 , L852 , L860 , XBOOLE_0:def 4;
L865: ( LSeg (C97 , D52) ) meets ( LSeg (C97 , D55) ) by L864 , XBOOLE_0:4;
per cases  by L861 , XXREAL_0:1;
suppose L866: ( D52 + 1 ) = D55;

L867: ( ( D52 + 1 ) + 1 ) <= ( len C97 ) by L841 , NAT_1:13;
L868: ( D52 + ( 1 + 1 ) ) <= ( len C97 ) by L867;
L869: ( ( LSeg (C97 , D52) ) /\ ( LSeg (C97 , ( D52 + 1 )) ) ) = { ( C97 /. ( D52 + 1 ) ) } by L868 , L815 , TOPREAL1:def 6;
thus L870: contradiction by L869 , L824 , L864 , L866 , TARSKI:def 1;
end;
suppose L871: ( D52 + 1 ) < D55;

thus L872: contradiction by L871 , L865 , TOPREAL1:def 7;
end;
end;
L874: D52 >= ( 0 ) by NAT_1:2;
L875: ( ( 0 ) + 1 ) <= D55 by L874 , L850 , L853 , XREAL_1:7;
L876: D52 >= D55 by L875 , L807 , L808 , L815 , L818 , L816 , L848 , L852 , L860 , L858 , L862 , JORDAN5C:28;
L877: D52 >= ( D52 + 1 ) by L876 , L861 , XXREAL_0:2;
thus L878: contradiction by L877 , XREAL_1:29;
end;
end;
L880: D51 in ( L~ C96 ) by L813 , XBOOLE_0:def 4;
L881: D51 <> ( C97 . ( len C97 ) ) by L880 , L806 , L820 , L810 , XBOOLE_0:3;
L882: ( D52 + 1 ) < ( len C97 ) by L881 , L818 , L821 , XXREAL_0:1;
L883: ( ( D52 + 1 ) + 1 ) <= ( len C97 ) by L882 , NAT_1:13;
L884: ( C97 /. ( D52 + 1 ) ) in ( LSeg (C97 , ( D52 + 1 )) ) by L883 , L811 , TOPREAL1:21;
L885: D51 in ( LSeg (C97 , ( D52 + 1 )) ) by L884 , L819 , L821 , PARTFUN1:def 6;
L886: 1 <= ( ( D52 + 1 ) + 1 ) by NAT_1:11;
L887: ( len C97 ) >= 1 by L886 , L883 , XXREAL_0:2;
L888: ( ( D52 + 1 ) + 1 ) in ( dom C97 ) by L883 , L886 , FINSEQ_3:25;
L889: ( D52 + 1 ) < ( ( D52 + 1 ) + 1 ) by NAT_1:13;
L890: D51 <> ( C97 . ( ( D52 + 1 ) + 1 ) ) by L889 , L819 , L821 , L888 , FUNCT_1:def 4;
L891: D51 <> ( C97 /. ( ( D52 + 1 ) + 1 ) ) by L890 , L888 , PARTFUN1:def 6;
per cases ;
suppose L892: ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( L~ C96 );

L893: D51 <> ( C97 /. ( ( D52 + 1 ) + 1 ) ) by L888 , L890 , PARTFUN1:def 6;
L894: ( ( D52 + 1 ) + 1 ) <> ( len C97 ) by L806 , L820 , L892 , XBOOLE_0:3;
L895: ( ( D52 + 1 ) + 1 ) < ( len C97 ) by L894 , L883 , XXREAL_0:1;
L896: ( ( ( D52 + 1 ) + 1 ) + 1 ) <= ( len C97 ) by L895 , NAT_1:13;
L897: ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( LSeg (C97 , ( ( D52 + 1 ) + 1 )) ) by L896 , L886 , TOPREAL1:21;
L898: ( D52 + 1 ) >= ( ( D52 + 1 ) + 1 ) by L897 , L807 , L808 , L811 , L883 , L886 , L885 , L892 , L896 , L893 , JORDAN5C:28;
thus L899: contradiction by L898 , XREAL_1:29;
end;
suppose L900: (not ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( L~ C96 ));

L901:
now
assume L902: ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( RightComp C96 );
L903: ( RightComp C96 ) = { R7 where R7 is (Point of ( TOP-REAL 2 )) : (( W-bound ( L~ C96 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C96 ) ) & ( S-bound ( L~ C96 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C96 ) )) } by L738;
L904: (ex R7 being (Point of ( TOP-REAL 2 )) st (( C97 /. ( ( D52 + 1 ) + 1 ) ) = R7 & ( W-bound ( L~ C96 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C96 ) ) & ( S-bound ( L~ C96 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C96 ) ))) by L903 , L902;
L905: (( LSeg (C97 , ( D52 + 1 )) ) is  vertical or ( LSeg (C97 , ( D52 + 1 )) ) is  horizontal) by SPPOL_1:19;
L906: ( LSeg (C97 , ( D52 + 1 )) ) = ( LSeg (( C97 /. ( D52 + 1 ) ) , ( C97 /. ( ( D52 + 1 ) + 1 ) )) ) by L811 , L883 , TOPREAL1:def 3;
L907: (( ( C97 /. ( ( D52 + 1 ) + 1 ) ) `1 ) = ( D51 `1 ) or ( ( C97 /. ( ( D52 + 1 ) + 1 ) ) `2 ) = ( D51 `2 )) by L906 , L885 , L905 , SPPOL_1:40 , SPPOL_1:41;
thus L908: contradiction by L907 , L904 , EUCLID:52;
end;
reconsider D56 = ( mid (C97 , ( ( D52 + 1 ) + 1 ) , ( len C97 )) ) as S-Sequence_in_R2 by L901 , L806 , L883 , L886 , L887 , JORDAN3:6;
L909: ( ( D52 + 1 ) + 1 ) < ( len C97 ) by L806 , L883 , L901 , XXREAL_0:1;
L910: ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( ( L~ C96 ) ` ) by L900 , SUBSET_1:29;
L911: ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( ( LeftComp C96 ) \/ ( RightComp C96 ) ) by L910 , GOBRD12:10;
L912: ( C97 /. ( ( D52 + 1 ) + 1 ) ) in ( LeftComp C96 ) by L911 , L901 , XBOOLE_0:def 3;
L913: ( D56 /. 1 ) in ( LeftComp C96 ) by L912 , L809 , L888 , SPRECT_2:8;
L914: ( D56 /. ( len D56 ) ) in ( RightComp C96 ) by L806 , L809 , L888 , SPRECT_2:9;
L915: ( L~ C96 ) meets ( L~ D56 ) by L914 , L913 , L539;
consider C99 being set such that L916: C99 in ( L~ C96 ) and L917: C99 in ( L~ D56 ) by L915 , XBOOLE_0:3;
reconsider D57 = C99 as (Point of ( TOP-REAL 2 )) by L917;
consider R1 being (Element of ( NAT )) such that L918: 1 <= R1 and L919: ( R1 + 1 ) <= ( len D56 ) and L920: D57 in ( LSeg (D56 , R1) ) by L917 , SPPOL_2:13;
set D58 = ( ( R1 + ( ( D52 + 1 ) + 1 ) ) -' 1 );
L921: ( len D56 ) = ( ( ( len C97 ) -' ( ( D52 + 1 ) + 1 ) ) + 1 ) by L883 , L886 , JORDAN4:8;
L922: ( len D56 ) = ( ( len C97 ) -' ( D52 + 1 ) ) by L921 , L882 , NAT_2:7;
L923: ( ( len D56 ) + ( D52 + 1 ) ) = ( len C97 ) by L922 , L818 , XREAL_1:235;
L924: ( ( R1 + 1 ) + ( D52 + 1 ) ) <= ( len C97 ) by L923 , L919 , XREAL_1:6;
L925: ( ( ( R1 + 1 ) + D52 ) + 1 ) <= ( len C97 ) by L924;
L926: R1 < ( len D56 ) by L919 , NAT_1:13;
L927: ( LSeg (D56 , R1) ) = ( LSeg (C97 , ( ( R1 + ( ( D52 + 1 ) + 1 ) ) -' 1 )) ) by L926 , L886 , L909 , L918 , L921 , JORDAN4:19;
L928: D58 = ( ( ( ( R1 + D52 ) + 1 ) + 1 ) -' 1 )
.= ( ( R1 + D52 ) + 1 ) by NAT_D:34;
L929: D58 = ( R1 + ( D52 + 1 ) ) by L928;
L930: D58 >= ( ( D52 + 1 ) + 1 ) by L929 , L918 , XREAL_1:6;
L931:
now
assume L932: D51 = D57;
L933: D51 in ( ( LSeg (C97 , ( D52 + 1 )) ) /\ ( LSeg (C97 , D58) ) ) by L932 , L885 , L920 , L927 , XBOOLE_0:def 4;
L934: ( LSeg (C97 , ( D52 + 1 )) ) meets ( LSeg (C97 , D58) ) by L933 , XBOOLE_0:4;
per cases  by L930 , XXREAL_0:1;
suppose L935: ( ( D52 + 1 ) + 1 ) = D58;

L936: ( ( ( D52 + 1 ) + 1 ) + 1 ) <= ( len C97 ) by L909 , NAT_1:13;
L937: ( ( D52 + 1 ) + ( 1 + 1 ) ) <= ( len C97 ) by L936;
L938: ( ( LSeg (C97 , ( D52 + 1 )) ) /\ ( LSeg (C97 , ( ( D52 + 1 ) + 1 )) ) ) = { ( C97 /. ( ( D52 + 1 ) + 1 ) ) } by L937 , L811 , TOPREAL1:def 6;
thus L939: contradiction by L938 , L891 , L933 , L935 , TARSKI:def 1;
end;
suppose L940: ( ( D52 + 1 ) + 1 ) < D58;

thus L941: contradiction by L940 , L934 , TOPREAL1:def 7;
end;
end;
L943: ( ( 0 ) + 1 ) <= D58 by L928 , NAT_1:11;
L944: ( D52 + 1 ) >= D58 by L943 , L807 , L808 , L811 , L883 , L885 , L916 , L920 , L927 , L928 , L925 , L931 , JORDAN5C:28;
L945: ( D52 + 1 ) >= ( ( D52 + 1 ) + 1 ) by L944 , L930 , XXREAL_0:2;
thus L946: contradiction by L945 , XREAL_1:29;
end;
end;
theorem
L948: (for B79 being  rectangular special_circular_sequence holds (for B80 being S-Sequence_in_R2 holds ((( B80 /. 1 ) in ( LeftComp B79 ) & ( B80 /. ( len B80 ) ) in ( RightComp B79 )) implies ( Last_Point (( L~ B80 ) , ( B80 /. 1 ) , ( B80 /. ( len B80 ) ) , ( L~ B79 )) ) <> ( SE-corner ( L~ B79 ) ))))
proof
let C100 being  rectangular special_circular_sequence;
let C101 being S-Sequence_in_R2;
assume that
L949: ( C101 /. 1 ) in ( LeftComp C100 )
and
L950: ( C101 /. ( len C101 ) ) in ( RightComp C100 );
L951: ( L~ C100 ) meets ( L~ C101 ) by L949 , L950 , L539;
assume L952: ( Last_Point (( L~ C101 ) , ( C101 /. 1 ) , ( C101 /. ( len C101 ) ) , ( L~ C100 )) ) = ( SE-corner ( L~ C100 ) );
set D59 = ( SE-corner ( L~ C100 ) );
set D60 = ( Index (D59 , C101) );
L953: ( len C101 ) in ( dom C101 ) by FINSEQ_5:6;
L954: ( C101 . ( len C101 ) ) = ( C101 /. ( len C101 ) ) by L953 , PARTFUN1:def 6;
L955: 1 <= ( D60 + 1 ) by NAT_1:11;
L956: ( L~ C101 ) is_an_arc_of ( C101 /. 1 ) , ( C101 /. ( len C101 ) ) by TOPREAL1:25;
L957: D59 in ( ( L~ C101 ) /\ ( L~ C100 ) ) by L956 , L951 , L952 , JORDAN5C:def 2;
L958: D59 in ( L~ C101 ) by L957 , XBOOLE_0:def 4;
L959: 1 <= D60 by L958 , JORDAN3:8;
L960: D59 in ( LSeg (C101 , D60) ) by L958 , JORDAN3:9;
L961: D60 < ( len C101 ) by L958 , JORDAN3:8;
L962: ( D60 + 1 ) <= ( len C101 ) by L961 , NAT_1:13;
L963: ( D60 + 1 ) in ( dom C101 ) by L962 , L955 , FINSEQ_3:25;
L964: ( L~ C100 ) misses ( RightComp C100 ) by L372;
L965:
now
L966: ( len C101 ) >= 1 by L962 , L955 , XXREAL_0:2;
assume L967: D59 <> ( C101 . ( D60 + 1 ) );
L968: D59 <> ( C101 /. ( D60 + 1 ) ) by L967 , L963 , PARTFUN1:def 6;
per cases ;
suppose L969: ( C101 /. ( D60 + 1 ) ) in ( L~ C100 );

L970: ( D60 + 1 ) <> ( len C101 ) by L969 , L950 , L964 , XBOOLE_0:3;
L971: ( D60 + 1 ) < ( len C101 ) by L970 , L962 , XXREAL_0:1;
L972: ( ( D60 + 1 ) + 1 ) <= ( len C101 ) by L971 , NAT_1:13;
L973: ( C101 /. ( D60 + 1 ) ) in ( LSeg (C101 , ( D60 + 1 )) ) by L972 , L955 , TOPREAL1:21;
L974: D60 >= ( D60 + 1 ) by L973 , L951 , L952 , L959 , L962 , L960 , L955 , L968 , L969 , L972 , JORDAN5C:28;
thus L975: contradiction by L974 , XREAL_1:29;
end;
suppose L976: (not ( C101 /. ( D60 + 1 ) ) in ( L~ C100 ));

L977:
now
assume L978: ( C101 /. ( D60 + 1 ) ) in ( RightComp C100 );
L979: ( RightComp C100 ) = { R7 where R7 is (Point of ( TOP-REAL 2 )) : (( W-bound ( L~ C100 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C100 ) ) & ( S-bound ( L~ C100 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C100 ) )) } by L738;
L980: (ex R7 being (Point of ( TOP-REAL 2 )) st (( C101 /. ( D60 + 1 ) ) = R7 & ( W-bound ( L~ C100 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C100 ) ) & ( S-bound ( L~ C100 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C100 ) ))) by L979 , L978;
L981: (( LSeg (C101 , D60) ) is  vertical or ( LSeg (C101 , D60) ) is  horizontal) by SPPOL_1:19;
L982: ( LSeg (C101 , D60) ) = ( LSeg (( C101 /. D60 ) , ( C101 /. ( D60 + 1 ) )) ) by L959 , L962 , TOPREAL1:def 3;
L983: (( ( C101 /. ( D60 + 1 ) ) `1 ) = ( D59 `1 ) or ( ( C101 /. ( D60 + 1 ) ) `2 ) = ( D59 `2 )) by L982 , L960 , L981 , SPPOL_1:40 , SPPOL_1:41;
thus L984: contradiction by L983 , L980 , EUCLID:52;
end;
reconsider D61 = ( mid (C101 , ( D60 + 1 ) , ( len C101 )) ) as S-Sequence_in_R2 by L977 , L950 , L962 , L955 , L966 , JORDAN3:6;
L985: ( D60 + 1 ) < ( len C101 ) by L950 , L962 , L977 , XXREAL_0:1;
L986: ( C101 /. ( D60 + 1 ) ) in ( ( L~ C100 ) ` ) by L976 , SUBSET_1:29;
L987: ( C101 /. ( D60 + 1 ) ) in ( ( LeftComp C100 ) \/ ( RightComp C100 ) ) by L986 , GOBRD12:10;
L988: ( C101 /. ( D60 + 1 ) ) in ( LeftComp C100 ) by L987 , L977 , XBOOLE_0:def 3;
L989: ( D61 /. 1 ) in ( LeftComp C100 ) by L988 , L953 , L963 , SPRECT_2:8;
L990: ( D61 /. ( len D61 ) ) in ( RightComp C100 ) by L950 , L953 , L963 , SPRECT_2:9;
L991: ( L~ C100 ) meets ( L~ D61 ) by L990 , L989 , L539;
consider C102 being set such that L992: C102 in ( L~ C100 ) and L993: C102 in ( L~ D61 ) by L991 , XBOOLE_0:3;
reconsider D62 = C102 as (Point of ( TOP-REAL 2 )) by L993;
consider R1 being (Element of ( NAT )) such that L994: 1 <= R1 and L995: ( R1 + 1 ) <= ( len D61 ) and L996: D62 in ( LSeg (D61 , R1) ) by L993 , SPPOL_2:13;
set D63 = ( ( R1 + ( D60 + 1 ) ) -' 1 );
L997: D63 = ( ( ( R1 + D60 ) + 1 ) -' 1 )
.= ( R1 + D60 ) by NAT_D:34;
L998: ( len D61 ) = ( ( ( len C101 ) -' ( D60 + 1 ) ) + 1 ) by L962 , L955 , JORDAN4:8;
L999: ( len D61 ) = ( ( len C101 ) -' D60 ) by L998 , L958 , JORDAN3:8 , NAT_2:7;
L1000: ( ( len D61 ) + D60 ) = ( len C101 ) by L999 , L961 , XREAL_1:235;
L1001: ( ( R1 + 1 ) + D60 ) <= ( len C101 ) by L1000 , L995 , XREAL_1:6;
L1002: ( D63 + 1 ) <= ( len C101 ) by L1001 , L997;
L1003: R1 < ( len D61 ) by L995 , NAT_1:13;
L1004: ( LSeg (D61 , R1) ) = ( LSeg (C101 , ( ( R1 + ( D60 + 1 ) ) -' 1 )) ) by L1003 , L955 , L985 , L994 , L998 , JORDAN4:19;
L1005: D63 >= ( D60 + 1 ) by L994 , L997 , XREAL_1:6;
L1006:
now
assume L1007: D59 = D62;
L1008: D59 in ( ( LSeg (C101 , D60) ) /\ ( LSeg (C101 , D63) ) ) by L1007 , L960 , L996 , L1004 , XBOOLE_0:def 4;
L1009: ( LSeg (C101 , D60) ) meets ( LSeg (C101 , D63) ) by L1008 , XBOOLE_0:4;
per cases  by L1005 , XXREAL_0:1;
suppose L1010: ( D60 + 1 ) = D63;

L1011: ( ( D60 + 1 ) + 1 ) <= ( len C101 ) by L985 , NAT_1:13;
L1012: ( D60 + ( 1 + 1 ) ) <= ( len C101 ) by L1011;
L1013: ( ( LSeg (C101 , D60) ) /\ ( LSeg (C101 , ( D60 + 1 )) ) ) = { ( C101 /. ( D60 + 1 ) ) } by L1012 , L959 , TOPREAL1:def 6;
thus L1014: contradiction by L1013 , L968 , L1008 , L1010 , TARSKI:def 1;
end;
suppose L1015: ( D60 + 1 ) < D63;

thus L1016: contradiction by L1015 , L1009 , TOPREAL1:def 7;
end;
end;
L1018: D60 >= ( 0 ) by NAT_1:2;
L1019: ( ( 0 ) + 1 ) <= D63 by L1018 , L994 , L997 , XREAL_1:7;
L1020: D60 >= D63 by L1019 , L951 , L952 , L959 , L962 , L960 , L992 , L996 , L1004 , L1002 , L1006 , JORDAN5C:28;
L1021: D60 >= ( D60 + 1 ) by L1020 , L1005 , XXREAL_0:2;
thus L1022: contradiction by L1021 , XREAL_1:29;
end;
end;
L1024: D59 in ( L~ C100 ) by L957 , XBOOLE_0:def 4;
L1025: D59 <> ( C101 . ( len C101 ) ) by L1024 , L950 , L964 , L954 , XBOOLE_0:3;
L1026: ( D60 + 1 ) < ( len C101 ) by L1025 , L962 , L965 , XXREAL_0:1;
L1027: ( ( D60 + 1 ) + 1 ) <= ( len C101 ) by L1026 , NAT_1:13;
L1028: ( C101 /. ( D60 + 1 ) ) in ( LSeg (C101 , ( D60 + 1 )) ) by L1027 , L955 , TOPREAL1:21;
L1029: D59 in ( LSeg (C101 , ( D60 + 1 )) ) by L1028 , L963 , L965 , PARTFUN1:def 6;
L1030: 1 <= ( ( D60 + 1 ) + 1 ) by NAT_1:11;
L1031: ( len C101 ) >= 1 by L1030 , L1027 , XXREAL_0:2;
L1032: ( ( D60 + 1 ) + 1 ) in ( dom C101 ) by L1027 , L1030 , FINSEQ_3:25;
L1033: ( D60 + 1 ) < ( ( D60 + 1 ) + 1 ) by NAT_1:13;
L1034: D59 <> ( C101 . ( ( D60 + 1 ) + 1 ) ) by L1033 , L963 , L965 , L1032 , FUNCT_1:def 4;
L1035: D59 <> ( C101 /. ( ( D60 + 1 ) + 1 ) ) by L1034 , L1032 , PARTFUN1:def 6;
per cases ;
suppose L1036: ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( L~ C100 );

L1037: D59 <> ( C101 /. ( ( D60 + 1 ) + 1 ) ) by L1032 , L1034 , PARTFUN1:def 6;
L1038: ( ( D60 + 1 ) + 1 ) <> ( len C101 ) by L950 , L964 , L1036 , XBOOLE_0:3;
L1039: ( ( D60 + 1 ) + 1 ) < ( len C101 ) by L1038 , L1027 , XXREAL_0:1;
L1040: ( ( ( D60 + 1 ) + 1 ) + 1 ) <= ( len C101 ) by L1039 , NAT_1:13;
L1041: ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( LSeg (C101 , ( ( D60 + 1 ) + 1 )) ) by L1040 , L1030 , TOPREAL1:21;
L1042: ( D60 + 1 ) >= ( ( D60 + 1 ) + 1 ) by L1041 , L951 , L952 , L955 , L1027 , L1030 , L1029 , L1036 , L1040 , L1037 , JORDAN5C:28;
thus L1043: contradiction by L1042 , XREAL_1:29;
end;
suppose L1044: (not ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( L~ C100 ));

L1045:
now
assume L1046: ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( RightComp C100 );
L1047: ( RightComp C100 ) = { R7 where R7 is (Point of ( TOP-REAL 2 )) : (( W-bound ( L~ C100 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C100 ) ) & ( S-bound ( L~ C100 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C100 ) )) } by L738;
L1048: (ex R7 being (Point of ( TOP-REAL 2 )) st (( C101 /. ( ( D60 + 1 ) + 1 ) ) = R7 & ( W-bound ( L~ C100 ) ) < ( R7 `1 ) & ( R7 `1 ) < ( E-bound ( L~ C100 ) ) & ( S-bound ( L~ C100 ) ) < ( R7 `2 ) & ( R7 `2 ) < ( N-bound ( L~ C100 ) ))) by L1047 , L1046;
L1049: (( LSeg (C101 , ( D60 + 1 )) ) is  vertical or ( LSeg (C101 , ( D60 + 1 )) ) is  horizontal) by SPPOL_1:19;
L1050: ( LSeg (C101 , ( D60 + 1 )) ) = ( LSeg (( C101 /. ( D60 + 1 ) ) , ( C101 /. ( ( D60 + 1 ) + 1 ) )) ) by L955 , L1027 , TOPREAL1:def 3;
L1051: (( ( C101 /. ( ( D60 + 1 ) + 1 ) ) `1 ) = ( D59 `1 ) or ( ( C101 /. ( ( D60 + 1 ) + 1 ) ) `2 ) = ( D59 `2 )) by L1050 , L1029 , L1049 , SPPOL_1:40 , SPPOL_1:41;
thus L1052: contradiction by L1051 , L1048 , EUCLID:52;
end;
reconsider D64 = ( mid (C101 , ( ( D60 + 1 ) + 1 ) , ( len C101 )) ) as S-Sequence_in_R2 by L1045 , L950 , L1027 , L1030 , L1031 , JORDAN3:6;
L1053: ( ( D60 + 1 ) + 1 ) < ( len C101 ) by L950 , L1027 , L1045 , XXREAL_0:1;
L1054: ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( ( L~ C100 ) ` ) by L1044 , SUBSET_1:29;
L1055: ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( ( LeftComp C100 ) \/ ( RightComp C100 ) ) by L1054 , GOBRD12:10;
L1056: ( C101 /. ( ( D60 + 1 ) + 1 ) ) in ( LeftComp C100 ) by L1055 , L1045 , XBOOLE_0:def 3;
L1057: ( D64 /. 1 ) in ( LeftComp C100 ) by L1056 , L953 , L1032 , SPRECT_2:8;
L1058: ( D64 /. ( len D64 ) ) in ( RightComp C100 ) by L950 , L953 , L1032 , SPRECT_2:9;
L1059: ( L~ C100 ) meets ( L~ D64 ) by L1058 , L1057 , L539;
consider C103 being set such that L1060: C103 in ( L~ C100 ) and L1061: C103 in ( L~ D64 ) by L1059 , XBOOLE_0:3;
reconsider D65 = C103 as (Point of ( TOP-REAL 2 )) by L1061;
consider R1 being (Element of ( NAT )) such that L1062: 1 <= R1 and L1063: ( R1 + 1 ) <= ( len D64 ) and L1064: D65 in ( LSeg (D64 , R1) ) by L1061 , SPPOL_2:13;
set D66 = ( ( R1 + ( ( D60 + 1 ) + 1 ) ) -' 1 );
L1065: ( len D64 ) = ( ( ( len C101 ) -' ( ( D60 + 1 ) + 1 ) ) + 1 ) by L1027 , L1030 , JORDAN4:8;
L1066: ( len D64 ) = ( ( len C101 ) -' ( D60 + 1 ) ) by L1065 , L1026 , NAT_2:7;
L1067: ( ( len D64 ) + ( D60 + 1 ) ) = ( len C101 ) by L1066 , L962 , XREAL_1:235;
L1068: ( ( R1 + 1 ) + ( D60 + 1 ) ) <= ( len C101 ) by L1067 , L1063 , XREAL_1:6;
L1069: ( ( ( R1 + 1 ) + D60 ) + 1 ) <= ( len C101 ) by L1068;
L1070: R1 < ( len D64 ) by L1063 , NAT_1:13;
L1071: ( LSeg (D64 , R1) ) = ( LSeg (C101 , ( ( R1 + ( ( D60 + 1 ) + 1 ) ) -' 1 )) ) by L1070 , L1030 , L1053 , L1062 , L1065 , JORDAN4:19;
L1072: D66 = ( ( ( ( R1 + D60 ) + 1 ) + 1 ) -' 1 )
.= ( ( R1 + D60 ) + 1 ) by NAT_D:34;
L1073: D66 = ( R1 + ( D60 + 1 ) ) by L1072;
L1074: D66 >= ( ( D60 + 1 ) + 1 ) by L1073 , L1062 , XREAL_1:6;
L1075:
now
assume L1076: D59 = D65;
L1077: D59 in ( ( LSeg (C101 , ( D60 + 1 )) ) /\ ( LSeg (C101 , D66) ) ) by L1076 , L1029 , L1064 , L1071 , XBOOLE_0:def 4;
L1078: ( LSeg (C101 , ( D60 + 1 )) ) meets ( LSeg (C101 , D66) ) by L1077 , XBOOLE_0:4;
per cases  by L1074 , XXREAL_0:1;
suppose L1079: ( ( D60 + 1 ) + 1 ) = D66;

L1080: ( ( ( D60 + 1 ) + 1 ) + 1 ) <= ( len C101 ) by L1053 , NAT_1:13;
L1081: ( ( D60 + 1 ) + ( 1 + 1 ) ) <= ( len C101 ) by L1080;
L1082: ( ( LSeg (C101 , ( D60 + 1 )) ) /\ ( LSeg (C101 , ( ( D60 + 1 ) + 1 )) ) ) = { ( C101 /. ( ( D60 + 1 ) + 1 ) ) } by L1081 , L955 , TOPREAL1:def 6;
thus L1083: contradiction by L1082 , L1035 , L1077 , L1079 , TARSKI:def 1;
end;
suppose L1084: ( ( D60 + 1 ) + 1 ) < D66;

thus L1085: contradiction by L1084 , L1078 , TOPREAL1:def 7;
end;
end;
L1087: ( ( 0 ) + 1 ) <= D66 by L1072 , NAT_1:11;
L1088: ( D60 + 1 ) >= D66 by L1087 , L951 , L952 , L955 , L1027 , L1029 , L1060 , L1064 , L1071 , L1072 , L1069 , L1075 , JORDAN5C:28;
L1089: ( D60 + 1 ) >= ( ( D60 + 1 ) + 1 ) by L1088 , L1074 , XXREAL_0:2;
thus L1090: contradiction by L1089 , XREAL_1:29;
end;
end;
theorem
L1092: (for B81 being  rectangular special_circular_sequence holds (for B82 being (Point of ( TOP-REAL 2 )) holds ((( W-bound ( L~ B81 ) ) > ( B82 `1 ) or ( B82 `1 ) > ( E-bound ( L~ B81 ) ) or ( S-bound ( L~ B81 ) ) > ( B82 `2 ) or ( B82 `2 ) > ( N-bound ( L~ B81 ) )) implies B82 in ( LeftComp B81 ))))
proof
let C104 being  rectangular special_circular_sequence;
let C105 being (Point of ( TOP-REAL 2 ));
L1093: ( LeftComp C104 ) = { R7 where R7 is (Point of ( TOP-REAL 2 )) : (not (( W-bound ( L~ C104 ) ) <= ( R7 `1 ) & ( R7 `1 ) <= ( E-bound ( L~ C104 ) ) & ( S-bound ( L~ C104 ) ) <= ( R7 `2 ) & ( R7 `2 ) <= ( N-bound ( L~ C104 ) ))) } by L738;
thus L1094: thesis by L1093;
end;
theorem
L1095: (for B83 being  clockwise_oriented non  constant  standard special_circular_sequence holds (( B83 /. 1 ) = ( N-min ( L~ B83 ) ) implies ( LeftComp ( SpStSeq ( L~ B83 ) ) ) c= ( LeftComp B83 )))
proof
let C106 being  clockwise_oriented non  constant  standard special_circular_sequence;
assume that
L1096: ( C106 /. 1 ) = ( N-min ( L~ C106 ) );
defpred S4[ (Element of ( TOP-REAL 2 )) ] means ( $1 `2 ) < ( S-bound ( L~ C106 ) );
reconsider D67 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : S4[ R6 ] } as (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
defpred S5[ (Element of ( TOP-REAL 2 )) ] means ( $1 `2 ) > ( N-bound ( L~ C106 ) );
reconsider D68 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : S5[ R6 ] } as (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
defpred S6[ (Element of ( TOP-REAL 2 )) ] means ( $1 `1 ) > ( E-bound ( L~ C106 ) );
reconsider D69 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : S6[ R6 ] } as (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
defpred S7[ (Element of ( TOP-REAL 2 )) ] means ( $1 `1 ) < ( W-bound ( L~ C106 ) );
reconsider D70 = { R6 where R6 is (Point of ( TOP-REAL 2 )) : S7[ R6 ] } as (Subset of ( TOP-REAL 2 )) from DOMAIN_1:sch 7;
L1097: ( W-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) = ( W-bound ( L~ C106 ) ) by SPRECT_1:58;
L1098: (for R6 being (Point of ( TOP-REAL 2 )) holds (R6 in D68 implies ( R6 `2 ) > ( ( ( GoB C106 ) * (1 , ( width ( GoB C106 ) )) ) `2 )))
proof
let R6 being (Point of ( TOP-REAL 2 ));
assume L1099: R6 in D68;
L1100: (ex R7 being (Point of ( TOP-REAL 2 )) st (R6 = R7 & ( R7 `2 ) > ( N-bound ( L~ C106 ) ))) by L1099;
thus L1101: thesis by L1100 , JORDAN5D:40;
end;
L1102: D68 misses ( L~ C106 ) by L1098 , GOBOARD8:24;
L1103: ( 1 + 1 ) <= ( len C106 ) by GOBOARD7:34 , XXREAL_0:2;
L1104: ( ( ( width ( GoB C106 ) ) -' 1 ) + 1 ) = ( width ( GoB C106 ) ) by GOBRD11:34 , XREAL_1:235;
consider R1 being (Element of ( NAT )) such that L1105: 1 <= R1 and L1106: R1 < ( len ( GoB C106 ) ) and L1107: ( N-min ( L~ C106 ) ) = ( ( GoB C106 ) * (R1 , ( width ( GoB C106 ) )) ) by L391;
L1108: ( R1 + 1 ) <= ( len ( GoB C106 ) ) by L1106 , NAT_1:13;
L1109: R1 in ( dom ( GoB C106 ) ) by L1105 , L1106 , FINSEQ_3:25;
L1110: ( C106 /. 2 ) = ( ( GoB C106 ) * (( R1 + 1 ) , ( width ( GoB C106 ) )) ) by L1109 , L1096 , L1107 , L396;
L1111: ( width ( GoB C106 ) ) >= 1 by GOBRD11:34;
L1112: [ R1 , ( width ( GoB C106 ) ) ] in ( Indices ( GoB C106 ) ) by L1111 , L1105 , L1106 , MATRIX_1:36;
L1113: 1 <= ( R1 + 1 ) by L1105 , NAT_1:13;
L1114: ( ( C106 /. 2 ) `2 ) = ( ( ( GoB C106 ) * (1 , ( width ( GoB C106 ) )) ) `2 ) by L1113 , L1110 , L1111 , L1108 , GOBOARD5:1
.= ( ( N-min ( L~ C106 ) ) `2 ) by L1105 , L1106 , L1107 , L1111 , GOBOARD5:1
.= ( N-bound ( L~ C106 ) ) by EUCLID:52;
set D71 = ( ( ( 1 / 2 ) * ( ( ( GoB C106 ) * (R1 , ( width ( GoB C106 ) )) ) + ( ( GoB C106 ) * (( R1 + 1 ) , ( width ( GoB C106 ) )) ) ) ) + |[ ( 0 ) , 1 ]| );
set D72 = ( ( 1 / 2 ) * ( ( ( GoB C106 ) * (R1 , ( width ( GoB C106 ) )) ) + ( ( GoB C106 ) * (( R1 + 1 ) , ( width ( GoB C106 ) )) ) ) );
L1115: ( D71 `2 ) = ( ( D72 `2 ) + ( |[ ( 0 ) , 1 ]| `2 ) ) by TOPREAL3:2
.= ( ( D72 `2 ) + 1 ) by EUCLID:52;
L1116: ( D72 `2 ) = ( ( ( 1 / 2 ) * ( ( ( GoB C106 ) * (R1 , ( width ( GoB C106 ) )) ) + ( C106 /. 2 ) ) ) `2 ) by L1096 , L1107 , L1109 , L396
.= ( ( 1 / 2 ) * ( ( ( C106 /. 1 ) + ( C106 /. 2 ) ) `2 ) ) by L1096 , L1107 , TOPREAL3:4
.= ( ( 1 / 2 ) * ( ( ( C106 /. 1 ) `2 ) + ( ( C106 /. 2 ) `2 ) ) ) by TOPREAL3:2
.= ( ( 1 / 2 ) * ( ( N-bound ( L~ C106 ) ) + ( N-bound ( L~ C106 ) ) ) ) by L1096 , L1114 , EUCLID:52
.= ( N-bound ( L~ C106 ) );
L1117: ( D71 `2 ) > ( ( 0 ) + ( N-bound ( L~ C106 ) ) ) by L1116 , L1115 , XREAL_1:8;
L1118: ( D71 `2 ) > ( N-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) by L1117 , SPRECT_1:60;
L1119: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (not (( W-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) <= ( R6 `1 ) & ( R6 `1 ) <= ( E-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) & ( S-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) <= ( R6 `2 ) & ( R6 `2 ) <= ( N-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ))) } by L738;
L1120: D71 in ( LeftComp ( SpStSeq ( L~ C106 ) ) ) by L1119 , L1118;
L1121: [ ( R1 + 1 ) , ( width ( GoB C106 ) ) ] in ( Indices ( GoB C106 ) ) by L1111 , L1113 , L1108 , MATRIX_1:36;
L1122: ( left_cell (C106 , 1) ) = ( cell (( GoB C106 ) , R1 , ( width ( GoB C106 ) )) ) by L1121 , L1096 , L1107 , L1110 , L1104 , L1103 , L1112 , GOBOARD5:28;
L1123: ( Int ( cell (( GoB C106 ) , R1 , ( width ( GoB C106 ) )) ) ) c= ( LeftComp C106 ) by L1122 , GOBOARD9:def 1;
L1124: D71 in ( Int ( cell (( GoB C106 ) , R1 , ( width ( GoB C106 ) )) ) ) by L1105 , L1108 , GOBOARD6:32;
L1125: ( LeftComp C106 ) meets ( LeftComp ( SpStSeq ( L~ C106 ) ) ) by L1124 , L1123 , L1120 , XBOOLE_0:3;
L1126: ( S-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) = ( S-bound ( L~ C106 ) ) by SPRECT_1:59;
L1127: (for R6 being (Point of ( TOP-REAL 2 )) holds (R6 in D70 implies ( R6 `1 ) < ( ( ( GoB C106 ) * (1 , 1) ) `1 )))
proof
let R6 being (Point of ( TOP-REAL 2 ));
assume L1128: R6 in D70;
L1129: (ex R7 being (Point of ( TOP-REAL 2 )) st (R6 = R7 & ( R7 `1 ) < ( W-bound ( L~ C106 ) ))) by L1128;
thus L1130: thesis by L1129 , JORDAN5D:37;
end;
L1131: D70 misses ( L~ C106 ) by L1127 , GOBOARD8:21;
L1132: (for R6 being (Point of ( TOP-REAL 2 )) holds (R6 in D69 implies ( R6 `1 ) > ( ( ( GoB C106 ) * (( len ( GoB C106 ) ) , 1) ) `1 )))
proof
let R6 being (Point of ( TOP-REAL 2 ));
assume L1133: R6 in D69;
L1134: (ex R7 being (Point of ( TOP-REAL 2 )) st (R6 = R7 & ( R7 `1 ) > ( E-bound ( L~ C106 ) ))) by L1133;
thus L1135: thesis by L1134 , JORDAN5D:39;
end;
L1136: D69 misses ( L~ C106 ) by L1132 , GOBOARD8:22;
L1137: ( D69 \/ D70 ) misses ( L~ C106 ) by L1136 , L1131 , XBOOLE_1:70;
L1138: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) is_a_component_of ( ( L~ ( SpStSeq ( L~ C106 ) ) ) ` ) by GOBOARD9:def 1;
consider C107 being (Subset of ( ( TOP-REAL 2 ) | ( ( L~ ( SpStSeq ( L~ C106 ) ) ) ` ) )) such that L1139: C107 = ( LeftComp ( SpStSeq ( L~ C106 ) ) ) and L1140: C107 is  a_component by L1138 , CONNSP_1:def 6;
L1141: C107 is  connected by L1140 , CONNSP_1:def 5;
L1142: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) is  connected by L1141 , L1139 , CONNSP_1:23;
L1143: ( E-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) = ( E-bound ( L~ C106 ) ) by SPRECT_1:61;
L1144: ( N-bound ( L~ ( SpStSeq ( L~ C106 ) ) ) ) = ( N-bound ( L~ C106 ) ) by SPRECT_1:60;
L1145: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) = ( ( D67 \/ D68 ) \/ ( D69 \/ D70 ) )
proof
thus L1146: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) c= ( ( D67 \/ D68 ) \/ ( D69 \/ D70 ) )
proof
let C108 being set;
assume L1147: C108 in ( LeftComp ( SpStSeq ( L~ C106 ) ) );
L1148: C108 in { R6 where R6 is (Point of ( TOP-REAL 2 )) : (not (( W-bound ( L~ C106 ) ) <= ( R6 `1 ) & ( R6 `1 ) <= ( E-bound ( L~ C106 ) ) & ( S-bound ( L~ C106 ) ) <= ( R6 `2 ) & ( R6 `2 ) <= ( N-bound ( L~ C106 ) ))) } by L1147 , L1144 , L1097 , L1126 , L1143 , L738;
L1149: (ex R6 being (Point of ( TOP-REAL 2 )) st (R6 = C108 & (not (( W-bound ( L~ C106 ) ) <= ( R6 `1 ) & ( R6 `1 ) <= ( E-bound ( L~ C106 ) ) & ( S-bound ( L~ C106 ) ) <= ( R6 `2 ) & ( R6 `2 ) <= ( N-bound ( L~ C106 ) ))))) by L1148;
L1150: (C108 in D67 or C108 in D68 or C108 in D69 or C108 in D70) by L1149;
L1151: (C108 in ( D67 \/ D68 ) or C108 in ( D69 \/ D70 )) by L1150 , XBOOLE_0:def 3;
thus L1152: thesis by L1151 , XBOOLE_0:def 3;
end;

let C109 being set;
assume L1153: C109 in ( ( D67 \/ D68 ) \/ ( D69 \/ D70 ) );
L1154: (C109 in ( D67 \/ D68 ) or C109 in ( D69 \/ D70 )) by L1153 , XBOOLE_0:def 3;
per cases  by L1154 , XBOOLE_0:def 3;
suppose L1155: C109 in D67;

L1156: (ex R6 being (Point of ( TOP-REAL 2 )) st (C109 = R6 & ( R6 `2 ) < ( S-bound ( L~ C106 ) ))) by L1155;
thus L1157: thesis by L1156 , L1126 , L1092;
end;
suppose L1158: C109 in D68;

L1159: (ex R6 being (Point of ( TOP-REAL 2 )) st (C109 = R6 & ( R6 `2 ) > ( N-bound ( L~ C106 ) ))) by L1158;
thus L1160: thesis by L1159 , L1144 , L1092;
end;
suppose L1161: C109 in D69;

L1162: (ex R6 being (Point of ( TOP-REAL 2 )) st (C109 = R6 & ( R6 `1 ) > ( E-bound ( L~ C106 ) ))) by L1161;
thus L1163: thesis by L1162 , L1143 , L1092;
end;
suppose L1164: C109 in D70;

L1165: (ex R6 being (Point of ( TOP-REAL 2 )) st (C109 = R6 & ( R6 `1 ) < ( W-bound ( L~ C106 ) ))) by L1164;
thus L1166: thesis by L1165 , L1097 , L1092;
end;
end;
L1168: (for R6 being (Point of ( TOP-REAL 2 )) holds (R6 in D67 implies ( R6 `2 ) < ( ( ( GoB C106 ) * (1 , 1) ) `2 )))
proof
let R6 being (Point of ( TOP-REAL 2 ));
assume L1169: R6 in D67;
L1170: (ex R7 being (Point of ( TOP-REAL 2 )) st (R6 = R7 & ( R7 `2 ) < ( S-bound ( L~ C106 ) ))) by L1169;
thus L1171: thesis by L1170 , JORDAN5D:38;
end;
L1172: D67 misses ( L~ C106 ) by L1168 , GOBOARD8:23;
L1173: ( D67 \/ D68 ) misses ( L~ C106 ) by L1172 , L1102 , XBOOLE_1:70;
L1174: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) misses ( L~ C106 ) by L1173 , L1145 , L1137 , XBOOLE_1:70;
L1175: ( LeftComp ( SpStSeq ( L~ C106 ) ) ) c= ( ( L~ C106 ) ` ) by L1174 , SUBSET_1:23;
L1176: ( LeftComp C106 ) is_a_component_of ( ( L~ C106 ) ` ) by GOBOARD9:def 1;
thus L1177: thesis by L1176 , L1142 , L1125 , L1175 , GOBOARD9:4;
end;
begin
theorem
L1178: (for B84 being (FinSequence of ( TOP-REAL 2 )) holds (for B85 , B86 being (Point of ( TOP-REAL 2 )) holds (<* B85 , B86 *> is_in_the_area_of B84 iff (<* B85 *> is_in_the_area_of B84 & <* B86 *> is_in_the_area_of B84))))
proof
let C110 being (FinSequence of ( TOP-REAL 2 ));
let C111 , C112 being (Point of ( TOP-REAL 2 ));
thus L1179: (<* C111 , C112 *> is_in_the_area_of C110 implies (<* C111 *> is_in_the_area_of C110 & <* C112 *> is_in_the_area_of C110))
proof
L1180: ( dom <* C111 , C112 *> ) = { 1 , 2 } by FINSEQ_1:2 , FINSEQ_1:89;
L1181: 1 in ( dom <* C111 , C112 *> ) by L1180 , TARSKI:def 2;
assume L1182: <* C111 , C112 *> is_in_the_area_of C110;
L1183: ( <* C111 , C112 *> /. 1 ) = C111 by FINSEQ_4:17;
L1184: ( C111 `1 ) <= ( E-bound ( L~ C110 ) ) by L1183 , L1182 , L1181 , SPRECT_2:def 1;
L1185: ( C111 `2 ) <= ( N-bound ( L~ C110 ) ) by L1182 , L1181 , L1183 , SPRECT_2:def 1;
L1186: ( S-bound ( L~ C110 ) ) <= ( C111 `2 ) by L1182 , L1181 , L1183 , SPRECT_2:def 1;
L1187: ( W-bound ( L~ C110 ) ) <= ( C111 `1 ) by L1182 , L1181 , L1183 , SPRECT_2:def 1;
thus L1188: <* C111 *> is_in_the_area_of C110
proof
let R1 being (Element of ( NAT ));
assume L1189: R1 in ( dom <* C111 *> );
L1190: R1 in { 1 } by L1189 , FINSEQ_1:2 , FINSEQ_1:38;
L1191: R1 = 1 by L1190 , TARSKI:def 1;
thus L1192: thesis by L1191 , L1187 , L1184 , L1186 , L1185 , FINSEQ_4:16;
end;

let R1 being (Element of ( NAT ));
assume L1193: R1 in ( dom <* C112 *> );
L1194: R1 in { 1 } by L1193 , FINSEQ_1:2 , FINSEQ_1:38;
L1195: R1 = 1 by L1194 , TARSKI:def 1;
L1196: ( <* C111 , C112 *> /. 2 ) = C112 by FINSEQ_4:17;
L1197: 2 in ( dom <* C111 , C112 *> ) by L1180 , TARSKI:def 2;
L1198: ( C112 `1 ) <= ( E-bound ( L~ C110 ) ) by L1197 , L1182 , L1196 , SPRECT_2:def 1;
L1199: ( C112 `2 ) <= ( N-bound ( L~ C110 ) ) by L1182 , L1197 , L1196 , SPRECT_2:def 1;
L1200: ( S-bound ( L~ C110 ) ) <= ( C112 `2 ) by L1182 , L1197 , L1196 , SPRECT_2:def 1;
L1201: ( W-bound ( L~ C110 ) ) <= ( C112 `1 ) by L1182 , L1197 , L1196 , SPRECT_2:def 1;
thus L1202: thesis by L1201 , L1198 , L1200 , L1199 , L1195 , FINSEQ_4:16;
end;

L1203: ( <* C111 *> /. 1 ) = C111 by FINSEQ_4:16;
L1204: ( dom <* C112 *> ) = { 1 } by FINSEQ_1:2 , FINSEQ_1:38;
L1205: 1 in ( dom <* C112 *> ) by L1204 , TARSKI:def 1;
L1206: ( dom <* C111 *> ) = { 1 } by FINSEQ_1:2 , FINSEQ_1:38;
L1207: 1 in ( dom <* C111 *> ) by L1206 , TARSKI:def 1;
assume L1208: <* C111 *> is_in_the_area_of C110;
L1209: ( C111 `1 ) <= ( E-bound ( L~ C110 ) ) by L1208 , L1207 , L1203 , SPRECT_2:def 1;
L1210: ( C111 `2 ) <= ( N-bound ( L~ C110 ) ) by L1208 , L1207 , L1203 , SPRECT_2:def 1;
L1211: ( S-bound ( L~ C110 ) ) <= ( C111 `2 ) by L1208 , L1207 , L1203 , SPRECT_2:def 1;
L1212: ( <* C112 *> /. 1 ) = C112 by FINSEQ_4:16;
assume L1213: <* C112 *> is_in_the_area_of C110;
L1214: ( W-bound ( L~ C110 ) ) <= ( C112 `1 ) by L1213 , L1205 , L1212 , SPRECT_2:def 1;
L1215: ( C112 `1 ) <= ( E-bound ( L~ C110 ) ) by L1213 , L1205 , L1212 , SPRECT_2:def 1;
let R1 being (Element of ( NAT ));
assume L1216: R1 in ( dom <* C111 , C112 *> );
L1217: R1 in { 1 , 2 } by L1216 , FINSEQ_1:2 , FINSEQ_1:89;
L1218: (R1 = 1 or R1 = 2) by L1217 , TARSKI:def 2;
L1219: ( C112 `2 ) <= ( N-bound ( L~ C110 ) ) by L1213 , L1205 , L1212 , SPRECT_2:def 1;
L1220: ( S-bound ( L~ C110 ) ) <= ( C112 `2 ) by L1213 , L1205 , L1212 , SPRECT_2:def 1;
L1221: ( W-bound ( L~ C110 ) ) <= ( C111 `1 ) by L1208 , L1207 , L1203 , SPRECT_2:def 1;
thus L1222: thesis by L1221 , L1209 , L1211 , L1210 , L1214 , L1215 , L1220 , L1219 , L1218 , FINSEQ_4:17;
end;
theorem
L1223: (for B87 being  rectangular (FinSequence of ( TOP-REAL 2 )) holds (for B88 being (Point of ( TOP-REAL 2 )) holds ((<* B88 *> is_in_the_area_of B87 & (( B88 `1 ) = ( W-bound ( L~ B87 ) ) or ( B88 `1 ) = ( E-bound ( L~ B87 ) ) or ( B88 `2 ) = ( S-bound ( L~ B87 ) ) or ( B88 `2 ) = ( N-bound ( L~ B87 ) ))) implies B88 in ( L~ B87 ))))
proof
let C113 being  rectangular (FinSequence of ( TOP-REAL 2 ));
let C114 being (Point of ( TOP-REAL 2 ));
L1224: ( <* C114 *> /. 1 ) = C114 by FINSEQ_4:16;
L1225: ( dom <* C114 *> ) = { 1 } by FINSEQ_1:2 , FINSEQ_1:38;
L1226: 1 in ( dom <* C114 *> ) by L1225 , TARSKI:def 1;
assume L1227: <* C114 *> is_in_the_area_of C113;
L1228: ( W-bound ( L~ C113 ) ) <= ( C114 `1 ) by L1227 , L1226 , L1224 , SPRECT_2:def 1;
L1229: ( C114 `2 ) <= ( N-bound ( L~ C113 ) ) by L1227 , L1226 , L1224 , SPRECT_2:def 1;
L1230: ( S-bound ( L~ C113 ) ) <= ( C114 `2 ) by L1227 , L1226 , L1224 , SPRECT_2:def 1;
L1231: ( C114 `1 ) <= ( E-bound ( L~ C113 ) ) by L1227 , L1226 , L1224 , SPRECT_2:def 1;
consider C115 being non  vertical non  horizontal non  empty  compact (Subset of ( TOP-REAL 2 )) such that L1232: C113 = ( SpStSeq C115 ) by SPRECT_1:def 2;
L1233: ( E-bound ( L~ ( SpStSeq C115 ) ) ) = ( E-bound C115 ) by SPRECT_1:61;
L1234: ( N-bound ( L~ ( SpStSeq C115 ) ) ) = ( N-bound C115 ) by SPRECT_1:60;
L1235: ( S-bound ( L~ ( SpStSeq C115 ) ) ) = ( S-bound C115 ) by SPRECT_1:59;
L1236: ( W-bound ( L~ ( SpStSeq C115 ) ) ) = ( W-bound C115 ) by SPRECT_1:58;
L1237: ( L~ C113 ) = ( ( ( LSeg (( NW-corner C115 ) , ( NE-corner C115 )) ) \/ ( LSeg (( NE-corner C115 ) , ( SE-corner C115 )) ) ) \/ ( ( LSeg (( SE-corner C115 ) , ( SW-corner C115 )) ) \/ ( LSeg (( SW-corner C115 ) , ( NW-corner C115 )) ) ) ) by L1232 , SPRECT_1:41;
assume L1238: (( C114 `1 ) = ( W-bound ( L~ C113 ) ) or ( C114 `1 ) = ( E-bound ( L~ C113 ) ) or ( C114 `2 ) = ( S-bound ( L~ C113 ) ) or ( C114 `2 ) = ( N-bound ( L~ C113 ) ));
per cases  by L1238;
suppose L1239: ( C114 `1 ) = ( W-bound ( L~ C113 ) );

L1240: ( ( NW-corner C115 ) `1 ) = ( W-bound C115 ) by EUCLID:52;
L1241: ( ( NW-corner C115 ) `2 ) = ( N-bound C115 ) by EUCLID:52;
L1242: ( ( SW-corner C115 ) `2 ) = ( S-bound C115 ) by EUCLID:52;
L1243: ( ( SW-corner C115 ) `1 ) = ( W-bound C115 ) by EUCLID:52;
L1244: C114 in ( LSeg (( SW-corner C115 ) , ( NW-corner C115 )) ) by L1243 , L1230 , L1229 , L1232 , L1236 , L1235 , L1234 , L1239 , L1240 , L1242 , L1241 , GOBOARD7:7;
L1245: C114 in ( ( LSeg (( SE-corner C115 ) , ( SW-corner C115 )) ) \/ ( LSeg (( SW-corner C115 ) , ( NW-corner C115 )) ) ) by L1244 , XBOOLE_0:def 3;
thus L1246: thesis by L1245 , L1237 , XBOOLE_0:def 3;
end;
suppose L1247: ( C114 `1 ) = ( E-bound ( L~ C113 ) );

L1248: ( ( SE-corner C115 ) `1 ) = ( E-bound C115 ) by EUCLID:52;
L1249: ( ( SE-corner C115 ) `2 ) = ( S-bound C115 ) by EUCLID:52;
L1250: ( ( NE-corner C115 ) `2 ) = ( N-bound C115 ) by EUCLID:52;
L1251: ( ( NE-corner C115 ) `1 ) = ( E-bound C115 ) by EUCLID:52;
L1252: C114 in ( LSeg (( NE-corner C115 ) , ( SE-corner C115 )) ) by L1251 , L1230 , L1229 , L1232 , L1235 , L1234 , L1233 , L1247 , L1248 , L1250 , L1249 , GOBOARD7:7;
L1253: C114 in ( ( LSeg (( NW-corner C115 ) , ( NE-corner C115 )) ) \/ ( LSeg (( NE-corner C115 ) , ( SE-corner C115 )) ) ) by L1252 , XBOOLE_0:def 3;
thus L1254: thesis by L1253 , L1237 , XBOOLE_0:def 3;
end;
suppose L1255: ( C114 `2 ) = ( S-bound ( L~ C113 ) );

L1256: ( ( SW-corner C115 ) `1 ) = ( W-bound C115 ) by EUCLID:52;
L1257: ( ( SW-corner C115 ) `2 ) = ( S-bound C115 ) by EUCLID:52;
L1258: ( ( SE-corner C115 ) `2 ) = ( S-bound C115 ) by EUCLID:52;
L1259: ( ( SE-corner C115 ) `1 ) = ( E-bound C115 ) by EUCLID:52;
L1260: C114 in ( LSeg (( SE-corner C115 ) , ( SW-corner C115 )) ) by L1259 , L1228 , L1231 , L1232 , L1236 , L1235 , L1233 , L1255 , L1256 , L1258 , L1257 , GOBOARD7:8;
L1261: C114 in ( ( LSeg (( SE-corner C115 ) , ( SW-corner C115 )) ) \/ ( LSeg (( SW-corner C115 ) , ( NW-corner C115 )) ) ) by L1260 , XBOOLE_0:def 3;
thus L1262: thesis by L1261 , L1237 , XBOOLE_0:def 3;
end;
suppose L1263: ( C114 `2 ) = ( N-bound ( L~ C113 ) );

L1264: ( ( NE-corner C115 ) `1 ) = ( E-bound C115 ) by EUCLID:52;
L1265: ( ( NE-corner C115 ) `2 ) = ( N-bound C115 ) by EUCLID:52;
L1266: ( ( NW-corner C115 ) `2 ) = ( N-bound C115 ) by EUCLID:52;
L1267: ( ( NW-corner C115 ) `1 ) = ( W-bound C115 ) by EUCLID:52;
L1268: C114 in ( LSeg (( NW-corner C115 ) , ( NE-corner C115 )) ) by L1267 , L1228 , L1231 , L1232 , L1236 , L1234 , L1233 , L1263 , L1264 , L1266 , L1265 , GOBOARD7:8;
L1269: C114 in ( ( LSeg (( NW-corner C115 ) , ( NE-corner C115 )) ) \/ ( LSeg (( NE-corner C115 ) , ( SE-corner C115 )) ) ) by L1268 , XBOOLE_0:def 3;
thus L1270: thesis by L1269 , L1237 , XBOOLE_0:def 3;
end;
end;
theorem
L1272: (for B89 being (FinSequence of ( TOP-REAL 2 )) holds (for B90 , B91 being (Point of ( TOP-REAL 2 )) holds (for B92 being Real holds ((( 0 ) <= B92 & B92 <= 1 & <* B90 , B91 *> is_in_the_area_of B89) implies <* ( ( ( 1 - B92 ) * B90 ) + ( B92 * B91 ) ) *> is_in_the_area_of B89))))
proof
let C116 being (FinSequence of ( TOP-REAL 2 ));
let C117 , C118 being (Point of ( TOP-REAL 2 ));
let C119 being Real;
assume that
L1273: ( 0 ) <= C119
and
L1274: C119 <= 1
and
L1275: <* C117 , C118 *> is_in_the_area_of C116;
L1276: ( dom <* C117 , C118 *> ) = { 1 , 2 } by FINSEQ_1:2 , FINSEQ_1:89;
L1277: 2 in ( dom <* C117 , C118 *> ) by L1276 , TARSKI:def 2;
L1278: ( <* C117 , C118 *> /. 2 ) = C118 by FINSEQ_4:17;
L1279: ( W-bound ( L~ C116 ) ) <= ( C118 `1 ) by L1278 , L1275 , L1277 , SPRECT_2:def 1;
L1280: ( C119 * ( W-bound ( L~ C116 ) ) ) <= ( C119 * ( C118 `1 ) ) by L1279 , L1273 , XREAL_1:64;
L1281: ( C118 `1 ) <= ( E-bound ( L~ C116 ) ) by L1275 , L1277 , L1278 , SPRECT_2:def 1;
L1282: ( C119 * ( C118 `1 ) ) <= ( C119 * ( E-bound ( L~ C116 ) ) ) by L1281 , L1273 , XREAL_1:64;
L1283: ( <* C117 , C118 *> /. 1 ) = C117 by FINSEQ_4:17;
L1284: ( 1 - C119 ) >= ( 0 ) by L1274 , XREAL_1:48;
L1285: 1 in ( dom <* C117 , C118 *> ) by L1276 , TARSKI:def 2;
L1286: ( W-bound ( L~ C116 ) ) <= ( C117 `1 ) by L1285 , L1275 , L1283 , SPRECT_2:def 1;
L1287: ( ( 1 - C119 ) * ( W-bound ( L~ C116 ) ) ) <= ( ( 1 - C119 ) * ( C117 `1 ) ) by L1286 , L1284 , XREAL_1:64;
L1288: ( C117 `1 ) <= ( E-bound ( L~ C116 ) ) by L1275 , L1285 , L1283 , SPRECT_2:def 1;
L1289: ( ( 1 - C119 ) * ( C117 `1 ) ) <= ( ( 1 - C119 ) * ( E-bound ( L~ C116 ) ) ) by L1288 , L1284 , XREAL_1:64;
L1290: ( S-bound ( L~ C116 ) ) <= ( C117 `2 ) by L1275 , L1285 , L1283 , SPRECT_2:def 1;
L1291: ( ( 1 - C119 ) * ( S-bound ( L~ C116 ) ) ) <= ( ( 1 - C119 ) * ( C117 `2 ) ) by L1290 , L1284 , XREAL_1:64;
L1292: ( ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) `1 ) = ( ( ( ( 1 - C119 ) * C117 ) `1 ) + ( ( C119 * C118 ) `1 ) ) by TOPREAL3:2
.= ( ( ( 1 - C119 ) * ( C117 `1 ) ) + ( ( C119 * C118 ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - C119 ) * ( C117 `1 ) ) + ( C119 * ( C118 `1 ) ) ) by TOPREAL3:4;
L1293: ( C117 `2 ) <= ( N-bound ( L~ C116 ) ) by L1275 , L1285 , L1283 , SPRECT_2:def 1;
L1294: ( ( 1 - C119 ) * ( C117 `2 ) ) <= ( ( 1 - C119 ) * ( N-bound ( L~ C116 ) ) ) by L1293 , L1284 , XREAL_1:64;
let R4 being (Element of ( NAT ));
L1295: ( dom <* ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) *> ) = { 1 } by FINSEQ_1:2 , FINSEQ_1:38;
assume L1296: R4 in ( dom <* ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) *> );
L1297: R4 = 1 by L1296 , L1295 , TARSKI:def 1;
L1298: ( ( ( 1 - C119 ) * ( W-bound ( L~ C116 ) ) ) + ( C119 * ( W-bound ( L~ C116 ) ) ) ) = ( 1 * ( W-bound ( L~ C116 ) ) );
L1299: ( W-bound ( L~ C116 ) ) <= ( ( ( 1 - C119 ) * ( C117 `1 ) ) + ( C119 * ( C118 `1 ) ) ) by L1298 , L1280 , L1287 , XREAL_1:7;
thus L1300: ( W-bound ( L~ C116 ) ) <= ( ( <* ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) *> /. R4 ) `1 ) by L1299 , L1297 , L1292 , FINSEQ_4:16;
L1301: ( ( ( 1 - C119 ) * ( E-bound ( L~ C116 ) ) ) + ( C119 * ( E-bound ( L~ C116 ) ) ) ) = ( 1 * ( E-bound ( L~ C116 ) ) );
L1302: ( ( ( 1 - C119 ) * ( C117 `1 ) ) + ( C119 * ( C118 `1 ) ) ) <= ( E-bound ( L~ C116 ) ) by L1301 , L1282 , L1289 , XREAL_1:7;
thus L1303: ( ( <* ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) *> /. R4 ) `1 ) <= ( E-bound ( L~ C116 ) ) by L1302 , L1297 , L1292 , FINSEQ_4:16;
L1304: ( ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) `2 ) = ( ( ( ( 1 - C119 ) * C117 ) `2 ) + ( ( C119 * C118 ) `2 ) ) by TOPREAL3:2
.= ( ( ( 1 - C119 ) * ( C117 `2 ) ) + ( ( C119 * C118 ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - C119 ) * ( C117 `2 ) ) + ( C119 * ( C118 `2 ) ) ) by TOPREAL3:4;
L1305: ( C118 `2 ) <= ( N-bound ( L~ C116 ) ) by L1275 , L1277 , L1278 , SPRECT_2:def 1;
L1306: ( C119 * ( C118 `2 ) ) <= ( C119 * ( N-bound ( L~ C116 ) ) ) by L1305 , L1273 , XREAL_1:64;
L1307: ( S-bound ( L~ C116 ) ) <= ( C118 `2 ) by L1275 , L1277 , L1278 , SPRECT_2:def 1;
L1308: ( C119 * ( S-bound ( L~ C116 ) ) ) <= ( C119 * ( C118 `2 ) ) by L1307 , L1273 , XREAL_1:64;
L1309: ( ( ( 1 - C119 ) * ( S-bound ( L~ C116 ) ) ) + ( C119 * ( S-bound ( L~ C116 ) ) ) ) = ( 1 * ( S-bound ( L~ C116 ) ) );
L1310: ( S-bound ( L~ C116 ) ) <= ( ( ( 1 - C119 ) * ( C117 `2 ) ) + ( C119 * ( C118 `2 ) ) ) by L1309 , L1308 , L1291 , XREAL_1:7;
thus L1311: ( S-bound ( L~ C116 ) ) <= ( ( <* ( ( ( 1 - C119 ) * C117 ) + ( C119 * C118 ) ) *> /. R4 ) `2 ) by L1310 , L1297 , L1304 , FINSEQ_4:16;
L1312: ( ( ( 1 - C119 ) * ( N-bound ( L~ C116 ) ) ) + ( C119 * ( N-bound ( L~ C116 ) ) ) ) = ( 1 * ( N-bound ( L~ C116 ) ) );
L1313: ( ( ( 1 - C119 ) * ( C117 `2 ) ) + ( C119 * ( C118 `2 ) ) ) <= ( N-bound ( L~ C116 ) ) by L1312 , L1306 , L1294 , XREAL_1:7;
thus L1314: thesis by L1313 , L1297 , L1304 , FINSEQ_4:16;
end;
theorem
L1315: (for R1 being (Element of ( NAT )) holds (for B93 , B94 being (FinSequence of ( TOP-REAL 2 )) holds ((B94 is_in_the_area_of B93 & R1 in ( dom B94 )) implies <* ( B94 /. R1 ) *> is_in_the_area_of B93)))
proof
let R1 being (Element of ( NAT ));
let C120 , C121 being (FinSequence of ( TOP-REAL 2 ));
assume that
L1316: C121 is_in_the_area_of C120
and
L1317: R1 in ( dom C121 );
let R4 being (Element of ( NAT ));
L1318: ( dom <* ( C121 /. R1 ) *> ) = { 1 } by FINSEQ_1:2 , FINSEQ_1:38;
assume L1319: R4 in ( dom <* ( C121 /. R1 ) *> );
L1320: R4 = 1 by L1319 , L1318 , TARSKI:def 1;
L1321: ( <* ( C121 /. R1 ) *> /. R4 ) = ( C121 /. R1 ) by L1320 , FINSEQ_4:16;
thus L1322: thesis by L1321 , L1316 , L1317 , SPRECT_2:def 1;
end;
theorem
L1323: (for B95 , B96 being (FinSequence of ( TOP-REAL 2 )) holds (for B97 being (Point of ( TOP-REAL 2 )) holds ((B96 is_in_the_area_of B95 & B97 in ( L~ B96 )) implies <* B97 *> is_in_the_area_of B95)))
proof
let C122 , C123 being (FinSequence of ( TOP-REAL 2 ));
let C124 being (Point of ( TOP-REAL 2 ));
assume that
L1324: C123 is_in_the_area_of C122;
assume L1325: C124 in ( L~ C123 );
consider R1 being (Element of ( NAT )) such that L1326: 1 <= R1 and L1327: ( R1 + 1 ) <= ( len C123 ) and L1328: C124 in ( LSeg (( C123 /. R1 ) , ( C123 /. ( R1 + 1 ) )) ) by L1325 , SPPOL_2:14;
L1329: (ex B98 being Real st (C124 = ( ( ( 1 - B98 ) * ( C123 /. R1 ) ) + ( B98 * ( C123 /. ( R1 + 1 ) ) ) ) & ( 0 ) <= B98 & B98 <= 1)) by L1328;
L1330: R1 <= ( R1 + 1 ) by NAT_1:11;
L1331: R1 <= ( len C123 ) by L1330 , L1327 , XXREAL_0:2;
L1332: R1 in ( dom C123 ) by L1331 , L1326 , FINSEQ_3:25;
L1333: <* ( C123 /. R1 ) *> is_in_the_area_of C122 by L1332 , L1324 , L1315;
L1334: 1 <= ( R1 + 1 ) by NAT_1:11;
L1335: ( R1 + 1 ) in ( dom C123 ) by L1334 , L1327 , FINSEQ_3:25;
L1336: <* ( C123 /. ( R1 + 1 ) ) *> is_in_the_area_of C122 by L1335 , L1324 , L1315;
L1337: <* ( C123 /. R1 ) , ( C123 /. ( R1 + 1 ) ) *> is_in_the_area_of C122 by L1336 , L1333 , L1178;
thus L1338: thesis by L1337 , L1329 , L1272;
end;
theorem
L1339: (for B99 being  rectangular (FinSequence of ( TOP-REAL 2 )) holds (for B100 , B101 being (Point of ( TOP-REAL 2 )) holds (((not B101 in ( L~ B99 )) & <* B100 , B101 *> is_in_the_area_of B99) implies ( ( LSeg (B100 , B101) ) /\ ( L~ B99 ) ) c= { B100 })))
proof
let C125 being  rectangular (FinSequence of ( TOP-REAL 2 ));
let C126 , C127 being (Point of ( TOP-REAL 2 ));
assume that
L1340: (not C127 in ( L~ C125 ));
assume L1341: <* C126 , C127 *> is_in_the_area_of C125;
L1342: ( dom <* C126 , C127 *> ) = { 1 , 2 } by FINSEQ_1:2 , FINSEQ_1:89;
L1343: 2 in ( dom <* C126 , C127 *> ) by L1342 , TARSKI:def 2;
L1344: ( <* C126 , C127 *> /. 2 ) = C127 by FINSEQ_4:17;
L1345: ( W-bound ( L~ C125 ) ) <= ( C127 `1 ) by L1344 , L1341 , L1343 , SPRECT_2:def 1;
L1346: <* C127 *> is_in_the_area_of C125 by L1341 , L1178;
L1347: ( C127 `1 ) <> ( W-bound ( L~ C125 ) ) by L1346 , L1340 , L1223;
L1348: ( W-bound ( L~ C125 ) ) < ( C127 `1 ) by L1347 , L1345 , XXREAL_0:1;
L1349: ( C127 `2 ) <= ( N-bound ( L~ C125 ) ) by L1341 , L1343 , L1344 , SPRECT_2:def 1;
L1350: ( C127 `2 ) <> ( N-bound ( L~ C125 ) ) by L1340 , L1346 , L1223;
L1351: ( C127 `2 ) < ( N-bound ( L~ C125 ) ) by L1350 , L1349 , XXREAL_0:1;
let C128 being set;
L1352: ( <* C126 , C127 *> /. 1 ) = C126 by FINSEQ_4:17;
L1353: ( C127 `1 ) <= ( E-bound ( L~ C125 ) ) by L1341 , L1343 , L1344 , SPRECT_2:def 1;
L1354: ( C127 `1 ) <> ( E-bound ( L~ C125 ) ) by L1340 , L1346 , L1223;
L1355: ( C127 `1 ) < ( E-bound ( L~ C125 ) ) by L1354 , L1353 , XXREAL_0:1;
assume L1356: C128 in ( ( LSeg (C126 , C127) ) /\ ( L~ C125 ) );
reconsider D73 = C128 as (Point of ( TOP-REAL 2 )) by L1356;
L1357: D73 in ( L~ C125 ) by L1356 , XBOOLE_0:def 4;
L1358: 1 in ( dom <* C126 , C127 *> ) by L1342 , TARSKI:def 2;
L1359: ( W-bound ( L~ C125 ) ) <= ( C126 `1 ) by L1358 , L1341 , L1352 , SPRECT_2:def 1;
L1360: ( C126 `2 ) <= ( N-bound ( L~ C125 ) ) by L1341 , L1358 , L1352 , SPRECT_2:def 1;
L1361: ( S-bound ( L~ C125 ) ) <= ( C126 `2 ) by L1341 , L1358 , L1352 , SPRECT_2:def 1;
L1362: ( C126 `1 ) <= ( E-bound ( L~ C125 ) ) by L1341 , L1358 , L1352 , SPRECT_2:def 1;
L1363: ( S-bound ( L~ C125 ) ) <= ( C127 `2 ) by L1341 , L1343 , L1344 , SPRECT_2:def 1;
L1364: ( C127 `2 ) <> ( S-bound ( L~ C125 ) ) by L1340 , L1346 , L1223;
L1365: ( S-bound ( L~ C125 ) ) < ( C127 `2 ) by L1364 , L1363 , XXREAL_0:1;
L1366: C128 in ( LSeg (C126 , C127) ) by L1356 , XBOOLE_0:def 4;
consider C129 being Real such that L1367: D73 = ( ( ( 1 - C129 ) * C126 ) + ( C129 * C127 ) ) and L1368: ( 0 ) <= C129 and L1369: C129 <= 1 by L1366;
L1370: ( D73 `1 ) = ( ( ( ( 1 - C129 ) * C126 ) `1 ) + ( ( C129 * C127 ) `1 ) ) by L1367 , TOPREAL3:2
.= ( ( ( 1 - C129 ) * ( C126 `1 ) ) + ( ( C129 * C127 ) `1 ) ) by TOPREAL3:4
.= ( ( ( 1 - C129 ) * ( C126 `1 ) ) + ( C129 * ( C127 `1 ) ) ) by TOPREAL3:4;
L1371: ( D73 `2 ) = ( ( ( ( 1 - C129 ) * C126 ) `2 ) + ( ( C129 * C127 ) `2 ) ) by L1367 , TOPREAL3:2
.= ( ( ( 1 - C129 ) * ( C126 `2 ) ) + ( ( C129 * C127 ) `2 ) ) by TOPREAL3:4
.= ( ( ( 1 - C129 ) * ( C126 `2 ) ) + ( C129 * ( C127 `2 ) ) ) by TOPREAL3:4;
per cases  by L1357 , L510;
suppose L1372: ( D73 `1 ) = ( W-bound ( L~ C125 ) );

L1373: C129 = ( 0 ) by L1372 , L1359 , L1348 , L1368 , L1369 , L1370 , XREAL_1:180;
L1374: D73 = ( ( 1 * C126 ) + ( 0. ( TOP-REAL 2 ) ) ) by L1373 , L1367 , EUCLID:29
.= ( 1 * C126 ) by EUCLID:27
.= C126 by EUCLID:29;
thus L1375: thesis by L1374 , ZFMISC_1:31;
end;
suppose L1376: ( D73 `1 ) = ( E-bound ( L~ C125 ) );

L1377: C129 = ( 0 ) by L1376 , L1362 , L1355 , L1368 , L1369 , L1370 , XREAL_1:179;
L1378: D73 = ( ( 1 * C126 ) + ( 0. ( TOP-REAL 2 ) ) ) by L1377 , L1367 , EUCLID:29
.= ( 1 * C126 ) by EUCLID:27
.= C126 by EUCLID:29;
thus L1379: thesis by L1378 , ZFMISC_1:31;
end;
suppose L1380: ( D73 `2 ) = ( S-bound ( L~ C125 ) );

L1381: C129 = ( 0 ) by L1380 , L1361 , L1365 , L1368 , L1369 , L1371 , XREAL_1:180;
L1382: D73 = ( ( 1 * C126 ) + ( 0. ( TOP-REAL 2 ) ) ) by L1381 , L1367 , EUCLID:29
.= ( 1 * C126 ) by EUCLID:27
.= C126 by EUCLID:29;
thus L1383: thesis by L1382 , ZFMISC_1:31;
end;
suppose L1384: ( D73 `2 ) = ( N-bound ( L~ C125 ) );

L1385: C129 = ( 0 ) by L1384 , L1360 , L1351 , L1368 , L1369 , L1371 , XREAL_1:179;
L1386: D73 = ( ( 1 * C126 ) + ( 0. ( TOP-REAL 2 ) ) ) by L1385 , L1367 , EUCLID:29
.= ( 1 * C126 ) by EUCLID:27
.= C126 by EUCLID:29;
thus L1387: thesis by L1386 , ZFMISC_1:31;
end;
end;
theorem
L1389: (for B102 being  rectangular (FinSequence of ( TOP-REAL 2 )) holds (for B103 , B104 being (Point of ( TOP-REAL 2 )) holds ((B103 in ( L~ B102 ) & (not B104 in ( L~ B102 )) & <* B104 *> is_in_the_area_of B102) implies ( ( LSeg (B103 , B104) ) /\ ( L~ B102 ) ) = { B103 })))
proof
let C130 being  rectangular (FinSequence of ( TOP-REAL 2 ));
let C131 , C132 being (Point of ( TOP-REAL 2 ));
assume that
L1390: C131 in ( L~ C130 )
and
L1391: (not C132 in ( L~ C130 ))
and
L1392: <* C132 *> is_in_the_area_of C130;
L1393: <* C131 , C132 *> = ( <* C131 *> ^ <* C132 *> ) by FINSEQ_1:def 9;
L1394: <* C131 *> is_in_the_area_of C130 by L1390 , L1323 , SPRECT_2:21;
thus L1395: ( ( LSeg (C131 , C132) ) /\ ( L~ C130 ) ) c= { C131 } by L1394 , L1391 , L1392 , L1393 , L1339 , SPRECT_2:24;
L1396: C131 in ( LSeg (C131 , C132) ) by RLTOPSP1:68;
L1397: C131 in ( ( LSeg (C131 , C132) ) /\ ( L~ C130 ) ) by L1396 , L1390 , XBOOLE_0:def 4;
thus L1398: thesis by L1397 , ZFMISC_1:31;
end;
theorem
L1399: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for B105 being non  constant  standard special_circular_sequence holds ((1 <= R1 & R1 <= ( len ( GoB B105 ) ) & 1 <= R2 & R2 <= ( width ( GoB B105 ) )) implies <* ( ( GoB B105 ) * (R1 , R2) ) *> is_in_the_area_of B105))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let C133 being non  constant  standard special_circular_sequence;
assume that
L1400: 1 <= R1
and
L1401: R1 <= ( len ( GoB C133 ) )
and
L1402: 1 <= R2
and
L1403: R2 <= ( width ( GoB C133 ) );
set D74 = ( GoB C133 );
L1404: 1 <= ( width D74 ) by L1402 , L1403 , XXREAL_0:2;
L1405: 1 <= ( len D74 ) by L1400 , L1401 , XXREAL_0:2;
L1406: ( N-bound ( L~ C133 ) ) = ( ( D74 * (1 , ( width D74 )) ) `2 ) by JORDAN5D:40
.= ( ( D74 * (R1 , ( width D74 )) ) `2 ) by L1400 , L1401 , L1404 , GOBOARD5:1;
L1407: (R2 = 1 or R2 > 1) by L1402 , XXREAL_0:1;
L1408: ( S-bound ( L~ C133 ) ) = ( ( D74 * (1 , 1) ) `2 ) by JORDAN5D:38
.= ( ( D74 * (R1 , 1) ) `2 ) by L1400 , L1401 , L1404 , GOBOARD5:1;
L1409: (R1 = 1 or R1 > 1) by L1400 , XXREAL_0:1;
L1410: ( E-bound ( L~ C133 ) ) = ( ( D74 * (( len D74 ) , 1) ) `1 ) by JORDAN5D:39
.= ( ( D74 * (( len D74 ) , R2) ) `1 ) by L1402 , L1403 , L1405 , GOBOARD5:2;
L1411: (R2 = ( width D74 ) or R2 < ( width D74 )) by L1403 , XXREAL_0:1;
L1412: (R1 = ( len D74 ) or R1 < ( len D74 )) by L1401 , XXREAL_0:1;
let R4 being (Element of ( NAT ));
set D75 = ( ( GoB C133 ) * (R1 , R2) );
assume L1413: R4 in ( dom <* ( ( GoB C133 ) * (R1 , R2) ) *> );
L1414: R4 in { 1 } by L1413 , FINSEQ_1:2 , FINSEQ_1:38;
L1415: R4 = 1 by L1414 , TARSKI:def 1;
L1416: ( <* D75 *> /. R4 ) = D75 by L1415 , FINSEQ_4:16;
L1417: ( W-bound ( L~ C133 ) ) = ( ( D74 * (1 , 1) ) `1 ) by JORDAN5D:37
.= ( ( D74 * (1 , R2) ) `1 ) by L1402 , L1403 , L1405 , GOBOARD5:2;
thus L1418: thesis by L1417 , L1416 , L1409 , L1408 , L1407 , L1410 , L1412 , L1406 , L1411 , GOBOARD5:3 , GOBOARD5:4;
end;
theorem
L1419: (for B106 being (FinSequence of ( TOP-REAL 2 )) holds (for B107 , B108 being (Point of ( TOP-REAL 2 )) holds (<* B107 , B108 *> is_in_the_area_of B106 implies <* ( ( 1 / 2 ) * ( B107 + B108 ) ) *> is_in_the_area_of B106)))
proof
let C134 being (FinSequence of ( TOP-REAL 2 ));
let C135 , C136 being (Point of ( TOP-REAL 2 ));
L1420: ( ( 1 / 2 ) * ( C135 + C136 ) ) = ( ( ( 1 - ( 1 / 2 ) ) * C135 ) + ( ( 1 / 2 ) * C136 ) ) by EUCLID:32;
thus L1421: thesis by L1420 , L1272;
end;
theorem
L1422: (for B109 , B110 being (FinSequence of ( TOP-REAL 2 )) holds (B110 is_in_the_area_of B109 implies ( Rev B110 ) is_in_the_area_of B109))
proof
let C137 , C138 being (FinSequence of ( TOP-REAL 2 ));
assume that
L1423: C138 is_in_the_area_of C137;
L1424: ( Rev ( Rev C138 ) ) = C138;
let R4 being (Element of ( NAT ));
assume that
L1425: R4 in ( dom ( Rev C138 ) );
L1426: R4 >= 1 by L1425 , FINSEQ_3:25;
L1427: ( R4 - 1 ) >= ( 0 ) by L1426 , XREAL_1:48;
set D76 = ( ( ( len C138 ) + 1 ) -' R4 );
L1428: ( len ( Rev C138 ) ) = ( len C138 ) by FINSEQ_5:def 3;
L1429: R4 <= ( len C138 ) by L1428 , L1425 , FINSEQ_3:25;
L1430: D76 = ( ( ( len C138 ) -' R4 ) + 1 ) by L1429 , NAT_D:38;
L1431: D76 = ( ( ( len C138 ) - R4 ) + 1 ) by L1430 , L1429 , XREAL_1:233
.= ( ( len C138 ) - ( R4 - 1 ) );
L1432: D76 <= ( ( len C138 ) - ( 0 ) ) by L1431 , L1427 , XREAL_1:13;
L1433: 1 <= D76 by L1430 , NAT_1:11;
L1434: D76 in ( dom C138 ) by L1433 , L1432 , FINSEQ_3:25;
L1435: ( len C138 ) <= ( ( len C138 ) + 1 ) by NAT_1:11;
L1436: ( R4 + D76 ) = ( ( len C138 ) + 1 ) by L1435 , L1429 , XREAL_1:235 , XXREAL_0:2;
L1437: ( ( Rev C138 ) /. R4 ) = ( C138 /. D76 ) by L1436 , L1424 , L1428 , L1425 , FINSEQ_5:66;
thus L1438: thesis by L1437 , L1423 , L1434 , SPRECT_2:def 1;
end;
theorem
L1439: (for B111 , B112 being (FinSequence of ( TOP-REAL 2 )) holds (for B113 being (Point of ( TOP-REAL 2 )) holds ((B112 is_in_the_area_of B111 & <* B113 *> is_in_the_area_of B111 & B112 is  being_S-Seq & B113 in ( L~ B112 )) implies ( R_Cut (B112 , B113) ) is_in_the_area_of B111)))
proof
let C139 , C140 being (FinSequence of ( TOP-REAL 2 ));
let C141 being (Point of ( TOP-REAL 2 ));
assume that
L1440: C140 is_in_the_area_of C139
and
L1441: <* C141 *> is_in_the_area_of C139
and
L1442: C140 is  being_S-Seq;
L1443: 2 <= ( len C140 ) by L1442 , TOPREAL1:def 8;
L1444: 1 <= ( len C140 ) by L1443 , XXREAL_0:2;
L1445: 1 in ( dom C140 ) by L1444 , FINSEQ_3:25;
assume L1446: C141 in ( L~ C140 );
L1447: ( Index (C141 , C140) ) < ( len C140 ) by L1446 , JORDAN3:8;
L1448: 1 <= ( Index (C141 , C140) ) by L1446 , JORDAN3:8;
L1449: ( Index (C141 , C140) ) in ( dom C140 ) by L1448 , L1447 , FINSEQ_3:25;
per cases ;
suppose L1450: C141 <> ( C140 . 1 );

L1451: ( R_Cut (C140 , C141) ) = ( ( mid (C140 , 1 , ( Index (C141 , C140) )) ) ^ <* C141 *> ) by L1450 , JORDAN3:def 4;
L1452: ( mid (C140 , 1 , ( Index (C141 , C140) )) ) is_in_the_area_of C139 by L1440 , L1445 , L1449 , SPRECT_2:22;
thus L1453: thesis by L1452 , L1441 , L1451 , SPRECT_2:24;
end;
suppose L1454: C141 = ( C140 . 1 );

L1455: ( R_Cut (C140 , C141) ) = <* ( C140 . 1 ) *> by L1454 , JORDAN3:def 4
.= <* ( C140 /. 1 ) *> by L1445 , PARTFUN1:def 6
.= ( mid (C140 , 1 , 1) ) by L1444 , JORDAN4:15;
thus L1456: thesis by L1455 , L1440 , L1445 , SPRECT_2:22;
end;
end;
theorem
L1458: (for B114 being non  constant  standard special_circular_sequence holds (for B115 being (FinSequence of ( TOP-REAL 2 )) holds (B115 is_in_the_area_of B114 iff B115 is_in_the_area_of ( SpStSeq ( L~ B114 ) ))))
proof
let C142 being non  constant  standard special_circular_sequence;
let C143 being (FinSequence of ( TOP-REAL 2 ));
L1459: ( S-bound ( L~ ( SpStSeq ( L~ C142 ) ) ) ) = ( S-bound ( L~ C142 ) ) by SPRECT_1:59;
L1460: ( N-bound ( L~ ( SpStSeq ( L~ C142 ) ) ) ) = ( N-bound ( L~ C142 ) ) by SPRECT_1:60;
L1461: ( E-bound ( L~ ( SpStSeq ( L~ C142 ) ) ) ) = ( E-bound ( L~ C142 ) ) by SPRECT_1:61;
L1462: ( W-bound ( L~ ( SpStSeq ( L~ C142 ) ) ) ) = ( W-bound ( L~ C142 ) ) by SPRECT_1:58;
thus L1463: (C143 is_in_the_area_of C142 implies C143 is_in_the_area_of ( SpStSeq ( L~ C142 ) ))
proof
assume L1464: C143 is_in_the_area_of C142;
let R4 being (Element of ( NAT ));
thus L1465: thesis by L1462 , L1459 , L1460 , L1461 , L1464 , SPRECT_2:def 1;
end;

assume L1466: C143 is_in_the_area_of ( SpStSeq ( L~ C142 ) );
let R4 being (Element of ( NAT ));
thus L1467: thesis by L1462 , L1459 , L1460 , L1461 , L1466 , SPRECT_2:def 1;
end;
theorem
L1468: (for B116 being  rectangular special_circular_sequence holds (for B117 being S-Sequence_in_R2 holds ((( B117 /. 1 ) in ( LeftComp B116 ) & ( B117 /. ( len B117 ) ) in ( RightComp B116 )) implies ( L_Cut (B117 , ( Last_Point (( L~ B117 ) , ( B117 /. 1 ) , ( B117 /. ( len B117 ) ) , ( L~ B116 )) )) ) is_in_the_area_of B116)))
proof
let C144 being  rectangular special_circular_sequence;
let C145 being S-Sequence_in_R2;
assume that
L1469: ( C145 /. 1 ) in ( LeftComp C144 )
and
L1470: ( C145 /. ( len C145 ) ) in ( RightComp C144 );
L1471: ( L~ C145 ) meets ( L~ C144 ) by L1469 , L1470 , L539;
L1472: 1 in ( dom C145 ) by FINSEQ_5:6;
L1473: ( len C145 ) >= 1 by L1472 , FINSEQ_3:25;
set D77 = ( Last_Point (( L~ C145 ) , ( C145 /. 1 ) , ( C145 /. ( len C145 ) ) , ( L~ C144 )) );
set D78 = ( Index (D77 , C145) );
set D79 = ( L_Cut (C145 , D77) );
L1474: ( L~ C145 ) is_an_arc_of ( C145 /. 1 ) , ( C145 /. ( len C145 ) ) by TOPREAL1:25;
L1475: D77 in ( ( L~ C145 ) /\ ( L~ C144 ) ) by L1474 , L1471 , JORDAN5C:def 2;
L1476: D77 in ( L~ C145 ) by L1475 , XBOOLE_0:def 4;
L1477: 1 <= D78 by L1476 , JORDAN3:8;
L1478: D77 in ( LSeg (C145 , D78) ) by L1476 , JORDAN3:9;
L1479: D78 < ( len C145 ) by L1476 , JORDAN3:8;
L1480: ( D78 + 1 ) <= ( len C145 ) by L1479 , NAT_1:13;
given R4 being (Element of ( NAT )) such that
L1481: R4 in ( dom D79 )
and
L1482: (( W-bound ( L~ C144 ) ) > ( ( D79 /. R4 ) `1 ) or ( ( D79 /. R4 ) `1 ) > ( E-bound ( L~ C144 ) ) or ( S-bound ( L~ C144 ) ) > ( ( D79 /. R4 ) `2 ) or ( ( D79 /. R4 ) `2 ) > ( N-bound ( L~ C144 ) ));

L1483: 1 <= R4 by L1481 , FINSEQ_3:25;
L1484: ( ( D78 + R4 ) -' 1 ) = ( D78 + ( R4 -' 1 ) ) by L1483 , NAT_D:38;
L1485: ( LeftComp C144 ) = { R6 where R6 is (Point of ( TOP-REAL 2 )) : (not (( W-bound ( L~ C144 ) ) <= ( R6 `1 ) & ( R6 `1 ) <= ( E-bound ( L~ C144 ) ) & ( S-bound ( L~ C144 ) ) <= ( R6 `2 ) & ( R6 `2 ) <= ( N-bound ( L~ C144 ) ))) } by L738;
L1486: ( D79 /. R4 ) in ( LeftComp C144 ) by L1485 , L1482;
L1487: 1 <= ( D78 + 1 ) by NAT_1:11;
L1488: ( D78 + 1 ) in ( dom C145 ) by L1487 , L1480 , FINSEQ_3:25;
L1489: ( LeftComp C144 ) misses ( RightComp C144 ) by SPRECT_1:88;
L1490: ( L~ C144 ) misses ( LeftComp C144 ) by L376;
L1491: ( len C145 ) in ( dom C145 ) by FINSEQ_5:6;
L1492: D77 in ( L~ C144 ) by L1475 , XBOOLE_0:def 4;
L1493:
now
assume L1494: R4 = 1;
per cases ;
suppose L1495: D77 <> ( C145 . ( D78 + 1 ) );

L1496: D79 = ( <* D77 *> ^ ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) by L1495 , JORDAN3:def 3;
L1497: ( D79 /. R4 ) = D77 by L1496 , L1494 , FINSEQ_5:15;
thus L1498: contradiction by L1497 , L1490 , L1492 , L1486 , XBOOLE_0:3;
end;
suppose L1499: D77 = ( C145 . ( D78 + 1 ) );

L1500: D79 = ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) by L1499 , JORDAN3:def 3;
L1501: ( D79 /. R4 ) = ( C145 /. ( ( 1 + ( D78 + 1 ) ) -' 1 ) ) by L1500 , L1491 , L1481 , L1480 , L1488 , L1494 , SPRECT_2:3
.= ( C145 /. ( D78 + 1 ) ) by NAT_D:34
.= D77 by L1488 , L1499 , PARTFUN1:def 6;
thus L1502: contradiction by L1501 , L1490 , L1492 , L1486 , XBOOLE_0:3;
end;
end;
L1504: R4 > 1 by L1493 , L1483 , XXREAL_0:1;
L1505: ( 1 + 1 ) < ( D78 + R4 ) by L1504 , L1477 , XREAL_1:8;
L1506: 1 <= ( ( D78 + R4 ) -' 1 ) by L1505 , NAT_D:49;
set D80 = ( mid (C145 , ( D78 + R4 ) , ( len C145 )) );
L1507: ( len <* D77 *> ) = 1 by FINSEQ_1:39;
L1508: R4 <= ( len D79 ) by L1481 , FINSEQ_3:25;
L1509: ( R4 + D78 ) <= ( ( len D79 ) + D78 ) by L1508 , XREAL_1:6;
L1510: R4 = ( ( R4 -' 1 ) + 1 ) by L1483 , XREAL_1:235;
L1511: 1 <= ( R4 -' 1 ) by L1510 , L1504 , NAT_1:13;
L1512: ( len ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) = ( ( ( len C145 ) -' ( D78 + 1 ) ) + 1 ) by L1480 , L1487 , JORDAN4:8
.= ( ( len C145 ) -' D78 ) by L1476 , JORDAN3:8 , NAT_2:7;
L1513: ( ( D78 + ( len ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) ) + 1 ) = ( ( len C145 ) + 1 ) by L1512 , L1479 , XREAL_1:235;
L1514:
now
L1515: ( D78 + 1 ) <= ( ( D78 + R4 ) -' 1 ) by L1484 , L1511 , XREAL_1:6;
assume L1516: D77 <> ( C145 . ( D78 + 1 ) );
L1517: D79 = ( <* D77 *> ^ ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) by L1516 , JORDAN3:def 3;
L1518: ( len D79 ) = ( 1 + ( len ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) ) by L1517 , L1507 , FINSEQ_1:22;
L1519: ( ( D78 + R4 ) -' 1 ) <= ( len C145 ) by L1518 , L1513 , L1509 , NAT_D:53;
L1520: ( ( len D79 ) -' 1 ) = ( len ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) by L1518 , NAT_D:34;
L1521: ( R4 -' 1 ) <= ( len ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) by L1520 , L1508 , NAT_D:42;
L1522: ( R4 -' 1 ) in ( dom ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) ) by L1521 , L1511 , FINSEQ_3:25;
L1523: ( D79 /. R4 ) = ( ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) /. ( R4 -' 1 ) ) by L1508 , L1510 , L1507 , L1511 , L1517 , L1520 , NAT_D:42 , SEQ_4:136;
L1524: ( D79 /. R4 ) = ( C145 /. ( ( ( R4 -' 1 ) + ( D78 + 1 ) ) -' 1 ) ) by L1523 , L1491 , L1480 , L1488 , L1522 , SPRECT_2:3
.= ( C145 /. ( ( R4 + D78 ) -' 1 ) ) by L1510;
L1525: ( ( D78 + R4 ) -' 1 ) <> ( len C145 ) by L1524 , L1470 , L1486 , L1489 , XBOOLE_0:3;
L1526: ( ( D78 + R4 ) -' 1 ) < ( len C145 ) by L1525 , L1519 , XXREAL_0:1;
reconsider D81 = ( mid (C145 , ( ( D78 + R4 ) -' 1 ) , ( len C145 )) ) as S-Sequence_in_R2 by L1473 , L1506 , L1519 , L1525 , JORDAN3:6;
L1527: ( ( D78 + R4 ) -' 1 ) in ( dom C145 ) by L1506 , L1519 , FINSEQ_3:25;
L1528: ( D81 /. ( len D81 ) ) in ( RightComp C144 ) by L1527 , L1470 , L1491 , SPRECT_2:9;
L1529: ( D81 /. 1 ) in ( LeftComp C144 ) by L1491 , L1486 , L1524 , L1527 , SPRECT_2:8;
L1530: ( L~ C144 ) meets ( L~ D81 ) by L1529 , L1528 , L539;
consider C146 being set such that L1531: C146 in ( L~ C144 ) and L1532: C146 in ( L~ D81 ) by L1530 , XBOOLE_0:3;
reconsider D82 = C146 as (Point of ( TOP-REAL 2 )) by L1532;
consider R1 being (Element of ( NAT )) such that L1533: 1 <= R1 and L1534: ( R1 + 1 ) <= ( len D81 ) and L1535: D82 in ( LSeg (D81 , R1) ) by L1532 , SPPOL_2:13;
L1536: ( len D81 ) = ( ( ( len C145 ) -' ( ( D78 + R4 ) -' 1 ) ) + 1 ) by L1506 , L1519 , JORDAN4:8;
L1537: R1 <= ( ( len C145 ) -' ( ( D78 + R4 ) -' 1 ) ) by L1536 , L1534 , XREAL_1:6;
L1538: ( R1 + ( ( D78 + R4 ) -' 1 ) ) <= ( len C145 ) by L1537 , L1519 , NAT_D:54;
L1539: R1 < ( len D81 ) by L1534 , NAT_1:13;
L1540: ( LSeg (D81 , R1) ) = ( LSeg (C145 , ( ( R1 + ( ( D78 + R4 ) -' 1 ) ) -' 1 )) ) by L1539 , L1506 , L1533 , L1536 , L1526 , JORDAN4:19;
set D83 = ( ( R1 + ( ( D78 + R4 ) -' 1 ) ) -' 1 );
L1541: R1 <= ( R1 + ( ( D78 + R4 ) -' 1 ) ) by NAT_1:11;
L1542: ( D83 + 1 ) <= ( len C145 ) by L1541 , L1533 , L1538 , XREAL_1:235 , XXREAL_0:2;
L1543: D83 = ( ( R1 -' 1 ) + ( ( D78 + R4 ) -' 1 ) ) by L1533 , NAT_D:38;
L1544: D83 >= ( ( D78 + R4 ) -' 1 ) by L1543 , NAT_1:11;
L1545: ( D78 + 1 ) <= D83 by L1544 , L1515 , XXREAL_0:2;
L1546: D77 <> ( C145 /. ( D78 + 1 ) ) by L1488 , L1516 , PARTFUN1:def 6;
L1547:
now
assume L1548: D77 = D82;
L1549: D77 in ( ( LSeg (C145 , D78) ) /\ ( LSeg (C145 , D83) ) ) by L1548 , L1478 , L1535 , L1540 , XBOOLE_0:def 4;
L1550: ( LSeg (C145 , D78) ) meets ( LSeg (C145 , D83) ) by L1549 , XBOOLE_0:4;
per cases  by L1545 , XXREAL_0:1;
suppose L1551: ( D78 + 1 ) = D83;

L1552: ( D78 + ( 1 + 1 ) ) <= ( len C145 ) by L1551 , L1542;
L1553: ( ( LSeg (C145 , D78) ) /\ ( LSeg (C145 , ( D78 + 1 )) ) ) = { ( C145 /. ( D78 + 1 ) ) } by L1552 , L1477 , TOPREAL1:def 6;
thus L1554: contradiction by L1553 , L1546 , L1549 , L1551 , TARSKI:def 1;
end;
suppose L1555: ( D78 + 1 ) < D83;

thus L1556: contradiction by L1555 , L1550 , TOPREAL1:def 7;
end;
end;
L1558: 1 <= D83 by L1487 , L1545 , XXREAL_0:2;
L1559: D78 >= D83 by L1558 , L1471 , L1478 , L1480 , L1477 , L1531 , L1535 , L1540 , L1542 , L1547 , JORDAN5C:28;
L1560: D78 >= ( D78 + 1 ) by L1559 , L1545 , XXREAL_0:2;
thus L1561: contradiction by L1560 , XREAL_1:29;
end;
L1562: D79 = ( mid (C145 , ( D78 + 1 ) , ( len C145 )) ) by L1514 , JORDAN3:def 3;
L1563: ( D78 + ( len D79 ) ) = ( len C145 ) by L1562 , L1479 , L1512 , XREAL_1:235;
L1564: D80 = ( C145 /^ ( ( D78 + R4 ) -' 1 ) ) by L1563 , L1509 , FINSEQ_6:117;
L1565: 1 <= ( D78 + R4 ) by L1505 , XXREAL_0:2;
L1566: ( ( ( D78 + R4 ) -' 1 ) + 1 ) = ( D78 + R4 ) by L1505 , XREAL_1:235 , XXREAL_0:2;
L1567: ( ( D78 + R4 ) -' 1 ) < ( len C145 ) by L1566 , L1509 , L1563 , NAT_1:13;
L1568: ( D80 /. ( len D80 ) ) in ( RightComp C144 ) by L1567 , L1470 , L1564 , JORDAN4:6;
L1569: ( D79 /. R4 ) = ( C145 /. ( ( R4 + ( D78 + 1 ) ) -' 1 ) ) by L1491 , L1481 , L1480 , L1488 , L1562 , SPRECT_2:3
.= ( C145 /. ( ( ( R4 + D78 ) + 1 ) -' 1 ) )
.= ( C145 /. ( D78 + R4 ) ) by NAT_D:34;
L1570: ( D78 + R4 ) <> ( len C145 ) by L1569 , L1470 , L1486 , L1489 , XBOOLE_0:3;
reconsider D84 = D80 as S-Sequence_in_R2 by L1570 , L1473 , L1509 , L1563 , L1565 , JORDAN3:6;
L1571: ( D78 + R4 ) in ( dom C145 ) by L1509 , L1563 , L1565 , FINSEQ_3:25;
L1572: ( D84 /. 1 ) in ( LeftComp C144 ) by L1571 , L1491 , L1486 , L1569 , SPRECT_2:8;
L1573: ( L~ C144 ) meets ( L~ D84 ) by L1572 , L1568 , L539;
consider C147 being set such that L1574: C147 in ( L~ C144 ) and L1575: C147 in ( L~ D84 ) by L1573 , XBOOLE_0:3;
reconsider D85 = C147 as (Point of ( TOP-REAL 2 )) by L1575;
consider R1 being (Element of ( NAT )) such that L1576: 1 <= R1 and L1577: ( R1 + 1 ) <= ( len D84 ) and L1578: D85 in ( LSeg (D84 , R1) ) by L1575 , SPPOL_2:13;
set D86 = ( ( R1 + ( D78 + R4 ) ) -' 1 );
L1579: D86 = ( ( R1 -' 1 ) + ( D78 + R4 ) ) by L1576 , NAT_D:38;
L1580: D86 >= ( D78 + R4 ) by L1579 , NAT_1:11;
L1581: ( len D84 ) = ( ( ( len C145 ) -' ( D78 + R4 ) ) + 1 ) by L1473 , L1509 , L1563 , L1565 , FINSEQ_6:118;
L1582: R1 < ( ( ( len C145 ) -' ( D78 + R4 ) ) + 1 ) by L1581 , L1577 , NAT_1:13;
L1583: ( R1 -' 1 ) < ( ( len C145 ) -' ( D78 + R4 ) ) by L1582 , L1576 , NAT_D:54;
L1584: ( ( R1 -' 1 ) + ( D78 + R4 ) ) < ( len C145 ) by L1583 , NAT_D:53;
L1585: ( D86 + 1 ) <= ( len C145 ) by L1584 , L1579 , NAT_1:13;
L1586: ( D78 + R4 ) < ( len C145 ) by L1509 , L1563 , L1570 , XXREAL_0:1;
L1587: ( LSeg (D84 , R1) ) = ( LSeg (C145 , ( ( R1 + ( D78 + R4 ) ) -' 1 )) ) by L1586 , L1565 , L1576 , L1582 , JORDAN4:19;
L1588: ( D78 + 1 ) < ( D78 + R4 ) by L1504 , XREAL_1:6;
L1589: D86 > ( D78 + 1 ) by L1588 , L1580 , XXREAL_0:2;
L1590:
now
assume L1591: D77 = D85;
L1592: D77 in ( ( LSeg (C145 , D78) ) /\ ( LSeg (C145 , D86) ) ) by L1591 , L1478 , L1578 , L1587 , XBOOLE_0:def 4;
L1593: ( LSeg (C145 , D78) ) meets ( LSeg (C145 , D86) ) by L1592 , XBOOLE_0:4;
thus L1594: contradiction by L1593 , L1589 , TOPREAL1:def 7;
end;
L1595: 1 <= D86 by L1565 , L1580 , XXREAL_0:2;
L1596: D78 >= D86 by L1595 , L1471 , L1478 , L1480 , L1477 , L1574 , L1578 , L1587 , L1590 , L1585 , JORDAN5C:28;
L1597: D78 >= ( D78 + 1 ) by L1596 , L1589 , XXREAL_0:2;
thus L1598: contradiction by L1597 , XREAL_1:29;
end;
theorem
L1599: (for R1 being (Element of ( NAT )) holds (for R2 being (Element of ( NAT )) holds (for B118 being non  constant  standard special_circular_sequence holds ((1 <= R1 & R1 < ( len ( GoB B118 ) ) & 1 <= R2 & R2 < ( width ( GoB B118 ) )) implies ( Int ( cell (( GoB B118 ) , R1 , R2) ) ) misses ( L~ ( SpStSeq ( L~ B118 ) ) )))))
proof
let R1 being (Element of ( NAT ));
let R2 being (Element of ( NAT ));
let C148 being non  constant  standard special_circular_sequence;
assume that
L1600: 1 <= R1
and
L1601: R1 < ( len ( GoB C148 ) )
and
L1602: 1 <= R2
and
L1603: R2 < ( width ( GoB C148 ) );
L1604: ( R1 + 1 ) <= ( len ( GoB C148 ) ) by L1601 , NAT_1:13;
set D87 = ( GoB C148 );
L1605: ( Int ( cell (D87 , R1 , R2) ) ) = { |[ B119 , B120 ]| where B119 , B120 is Real : (( ( D87 * (R1 , 1) ) `1 ) < B119 & B119 < ( ( D87 * (( R1 + 1 ) , 1) ) `1 ) & ( ( D87 * (1 , R2) ) `2 ) < B120 & B120 < ( ( D87 * (1 , ( R2 + 1 )) ) `2 )) } by L1600 , L1601 , L1602 , L1603 , GOBOARD6:26;
L1606: ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) = ( N-bound ( L~ C148 ) ) by SPRECT_1:60;
L1607: 1 <= ( width ( GoB C148 ) ) by GOBRD11:34;
L1608: <* ( ( GoB C148 ) * (R1 , 1) ) *> is_in_the_area_of C148 by L1607 , L1600 , L1601 , L1399;
L1609: 1 <= ( R1 + 1 ) by L1600 , NAT_1:13;
L1610: <* ( ( GoB C148 ) * (( R1 + 1 ) , 1) ) *> is_in_the_area_of C148 by L1609 , L1607 , L1604 , L1399;
assume L1611: ( Int ( cell (( GoB C148 ) , R1 , R2) ) ) meets ( L~ ( SpStSeq ( L~ C148 ) ) );
consider C149 being set such that L1612: C149 in ( Int ( cell (( GoB C148 ) , R1 , R2) ) ) and L1613: C149 in ( L~ ( SpStSeq ( L~ C148 ) ) ) by L1611 , XBOOLE_0:3;
L1614: ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) = ( W-bound ( L~ C148 ) ) by SPRECT_1:58;
L1615: 1 <= ( len ( GoB C148 ) ) by GOBRD11:34;
L1616: <* ( ( GoB C148 ) * (1 , R2) ) *> is_in_the_area_of C148 by L1615 , L1602 , L1603 , L1399;
L1617: ( R2 + 1 ) <= ( width ( GoB C148 ) ) by L1603 , NAT_1:13;
L1618: 1 <= ( R2 + 1 ) by L1602 , NAT_1:13;
L1619: <* ( ( GoB C148 ) * (1 , ( R2 + 1 )) ) *> is_in_the_area_of C148 by L1618 , L1615 , L1617 , L1399;
L1620: ( L~ ( SpStSeq ( L~ C148 ) ) ) = { R6 where R6 is (Point of ( TOP-REAL 2 )) : ((( R6 `1 ) = ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) <= ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) >= ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) )) or (( R6 `1 ) <= ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `1 ) >= ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) = ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) )) or (( R6 `1 ) <= ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `1 ) >= ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) = ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) )) or (( R6 `1 ) = ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) <= ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) >= ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ))) } by L580;
L1621: ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) = ( E-bound ( L~ C148 ) ) by SPRECT_1:61;
consider R6 being (Point of ( TOP-REAL 2 )) such that L1622: R6 = C149 and L1623: ((( R6 `1 ) = ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) <= ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) >= ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) )) or (( R6 `1 ) <= ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `1 ) >= ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) = ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) )) or (( R6 `1 ) <= ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `1 ) >= ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) = ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) )) or (( R6 `1 ) = ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) <= ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) & ( R6 `2 ) >= ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ))) by L1613 , L1620;
L1624: ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) ) = ( S-bound ( L~ C148 ) ) by SPRECT_1:59;
consider C150 , C151 being Real such that L1625: C149 = |[ C150 , C151 ]| and L1626: ( ( D87 * (R1 , 1) ) `1 ) < C150 and L1627: C150 < ( ( D87 * (( R1 + 1 ) , 1) ) `1 ) and L1628: ( ( D87 * (1 , R2) ) `2 ) < C151 and L1629: C151 < ( ( D87 * (1 , ( R2 + 1 )) ) `2 ) by L1605 , L1612;
L1630: ( R6 `1 ) = C150 by L1625 , L1622 , EUCLID:52;
L1631: ( R6 `2 ) = C151 by L1625 , L1622 , EUCLID:52;
per cases  by L1623;
suppose L1632: ( R6 `1 ) = ( W-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) );

L1633: 1 in ( dom <* ( D87 * (R1 , 1) ) *> ) by FINSEQ_5:6;
L1634: ( <* ( D87 * (R1 , 1) ) *> /. 1 ) = ( D87 * (R1 , 1) ) by FINSEQ_4:16;
thus L1635: contradiction by L1634 , L1626 , L1608 , L1630 , L1614 , L1632 , L1633 , SPRECT_2:def 1;
end;
suppose L1636: ( R6 `2 ) = ( N-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) );

L1637: 1 in ( dom <* ( D87 * (1 , ( R2 + 1 )) ) *> ) by FINSEQ_5:6;
L1638: ( <* ( D87 * (1 , ( R2 + 1 )) ) *> /. 1 ) = ( D87 * (1 , ( R2 + 1 )) ) by FINSEQ_4:16;
thus L1639: contradiction by L1638 , L1629 , L1619 , L1631 , L1606 , L1636 , L1637 , SPRECT_2:def 1;
end;
suppose that L1640: ( R6 `2 ) = ( S-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) );
L1641: 1 in ( dom <* ( D87 * (1 , R2) ) *> ) by FINSEQ_5:6;
L1642: ( <* ( D87 * (1 , R2) ) *> /. 1 ) = ( D87 * (1 , R2) ) by FINSEQ_4:16;
thus L1643: contradiction by L1642 , L1628 , L1616 , L1631 , L1624 , L1640 , L1641 , SPRECT_2:def 1;
end;
suppose that L1644: ( R6 `1 ) = ( E-bound ( L~ ( SpStSeq ( L~ C148 ) ) ) );
L1645: 1 in ( dom <* ( D87 * (( R1 + 1 ) , 1) ) *> ) by FINSEQ_5:6;
L1646: ( <* ( D87 * (( R1 + 1 ) , 1) ) *> /. 1 ) = ( D87 * (( R1 + 1 ) , 1) ) by FINSEQ_4:16;
thus L1647: contradiction by L1646 , L1627 , L1610 , L1630 , L1621 , L1644 , L1645 , SPRECT_2:def 1;
end;
end;
theorem
L1649: (for B121 , B122 being (FinSequence of ( TOP-REAL 2 )) holds (for B123 being (Point of ( TOP-REAL 2 )) holds ((B122 is_in_the_area_of B121 & <* B123 *> is_in_the_area_of B121 & B122 is  being_S-Seq & B123 in ( L~ B122 )) implies ( L_Cut (B122 , B123) ) is_in_the_area_of B121)))
proof
let C152 , C153 being (FinSequence of ( TOP-REAL 2 ));
let C154 being (Point of ( TOP-REAL 2 ));
assume that
L1650: C153 is_in_the_area_of C152
and
L1651: <* C154 *> is_in_the_area_of C152
and
L1652: C153 is  being_S-Seq;
L1653: 2 <= ( len C153 ) by L1652 , TOPREAL1:def 8;
L1654: 1 <= ( len C153 ) by L1653 , XXREAL_0:2;
L1655: ( len C153 ) in ( dom C153 ) by L1654 , FINSEQ_3:25;
assume L1656: C154 in ( L~ C153 );
L1657: ( Index (C154 , C153) ) < ( len C153 ) by L1656 , JORDAN3:8;
L1658: ( ( Index (C154 , C153) ) + 1 ) <= ( len C153 ) by L1657 , NAT_1:13;
L1659: 1 <= ( ( Index (C154 , C153) ) + 1 ) by NAT_1:11;
L1660: ( ( Index (C154 , C153) ) + 1 ) in ( dom C153 ) by L1659 , L1658 , FINSEQ_3:25;
per cases ;
suppose L1661: C154 <> ( C153 . ( ( Index (C154 , C153) ) + 1 ) );

L1662: ( L_Cut (C153 , C154) ) = ( <* C154 *> ^ ( mid (C153 , ( ( Index (C154 , C153) ) + 1 ) , ( len C153 )) ) ) by L1661 , JORDAN3:def 3;
L1663: ( mid (C153 , ( ( Index (C154 , C153) ) + 1 ) , ( len C153 )) ) is_in_the_area_of C152 by L1650 , L1655 , L1660 , SPRECT_2:22;
thus L1664: thesis by L1663 , L1651 , L1662 , SPRECT_2:24;
end;
suppose L1665: C154 = ( C153 . ( ( Index (C154 , C153) ) + 1 ) );

L1666: ( L_Cut (C153 , C154) ) = ( mid (C153 , ( ( Index (C154 , C153) ) + 1 ) , ( len C153 )) ) by L1665 , JORDAN3:def 3;
thus L1667: thesis by L1666 , L1650 , L1655 , L1660 , SPRECT_2:22;
end;
end;
