:: Miscellaneous Facts about Open Functions and Continuous Functions
::  by Artur Korni{\l}owicz
::
:: Received February 9, 2010
:: Copyright (c) 2010-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies RELAT_1, FUNCT_1, TOPS_1, ARYTM_1, CONNSP_2, EUCLID, PRE_TOPC,
      ORDINAL2, METRIC_1, TOPMETR, RCOMP_1, PCOMPS_1, TARSKI, XBOOLE_0,
      NUMBERS, NAT_1, SUBSET_1, XXREAL_0, ARYTM_3, ORDINAL1, XREAL_0, CARD_1,
      XXREAL_1;
 notations TARSKI, SUBSET_1, FUNCT_1, RELSET_1, FUNCT_2, ORDINAL1, NUMBERS,
      XCMPLX_0, XREAL_0, XXREAL_0, RCOMP_1, STRUCT_0, PRE_TOPC, TOPS_1,
      CONNSP_2, METRIC_1, PCOMPS_1, TOPMETR, T_0TOPSP, EUCLID, TOPREAL9,
      TOPREALB;
 constructors TOPREAL9, TOPREALB, TOPS_1, T_0TOPSP, FUNCSDOM, PCOMPS_1;
 registrations XBOOLE_0, RELAT_1, MEMBERED, XREAL_0, PRE_TOPC, STRUCT_0,
      EUCLID, TOPREALB, XXREAL_0, METRIC_1, TOPMETR, TOPREAL9, PCOMPS_1,
      RCOMP_1, TOPGRP_1, VALUED_0;
 requirements SUBSET, REAL;
 definitions TARSKI, T_0TOPSP, METRIC_1, PCOMPS_1, TOPMETR, TOPREALB;
 theorems FUNCT_2, TOPMETR, TOPREAL9, EUCLID, JGRAPH_2, GOBOARD6, TOPS_1,
      METRIC_1, XBOOLE_1, T_0TOPSP, XREAL_0, FRECHET, TOPREAL6, RELAT_1,
      UNIFORM1, CONNSP_2, TOPGRP_1, ORDINAL1, TOPS_3, YELLOW12, TOPGEN_5;

begin
theorem
L1: (for B1 , B2 , B3 , B4 being TopSpace holds (for B5 being (Function of B1 , B3) holds (for B6 being (Function of B2 , B4) holds ((( the TopStruct of B1 ) = ( the TopStruct of B2 ) & ( the TopStruct of B3 ) = ( the TopStruct of B4 ) & B5 = B6 & B5 is  open) implies B6 is  open))))
proof
let C1 , C2 , C3 , C4 being TopSpace;
let C5 being (Function of C1 , C3);
let C6 being (Function of C2 , C4);
assume that
L2: ( the TopStruct of C1 ) = ( the TopStruct of C2 )
and
L3: ( the TopStruct of C3 ) = ( the TopStruct of C4 )
and
L4: C5 = C6
and
L5: C5 is  open;
let C7 being (Subset of C2);
assume L6: C7 is  open;
reconsider D1 = C7 as (Subset of C1) by L2;
L7: D1 is  open by L2 , L6 , TOPS_3:76;
L8: ( C5 .: D1 ) is  open by L7 , L5 , T_0TOPSP:def 2;
thus L9: thesis by L8 , L3 , L4 , TOPS_3:76;
end;
theorem
L10: (for R2 being Nat holds (for B7 being (Subset of ( TOP-REAL R2 )) holds (B7 is  open iff (for B8 being (Point of ( TOP-REAL R2 )) holds (B8 in B7 implies (ex B9 being  positive  real number st ( Ball (B8 , B9) ) c= B7))))))
proof
let R2 being Nat;
let C8 being (Subset of ( TOP-REAL R2 ));
L11: ( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) by EUCLID:def 8;
reconsider D2 = C8 as (Subset of ( TopSpaceMetr ( Euclid R2 ) )) by L11;
L12: R2 in ( NAT ) by ORDINAL1:def 12;
thus L13:now
assume L14: C8 is  open;
let C9 being (Point of ( TOP-REAL R2 ));
assume L15: C9 in C8;
reconsider D3 = C9 as (Point of ( Euclid R2 )) by EUCLID:67;
L16: D2 is  open by L14 , L11 , TOPS_3:76;
consider C10 being  real number such that L17: C10 > ( 0 ) and L18: ( Ball (D3 , C10) ) c= D2 by L16 , L15 , TOPMETR:15;
reconsider D4 = C10 as  positive  real number by L17;
take D5 = D4;
thus L19: ( Ball (C9 , D5) ) c= C8 by L12 , L18 , TOPREAL9:13;
end;
assume L20: (for B10 being (Point of ( TOP-REAL R2 )) holds (B10 in C8 implies (ex B11 being  positive  real number st ( Ball (B10 , B11) ) c= C8)));
L21: (for B12 being (Point of ( Euclid R2 )) holds (B12 in D2 implies (ex B13 being  real number st (B13 > ( 0 ) & ( Ball (B12 , B13) ) c= D2))))
proof
let C11 being (Point of ( Euclid R2 ));
assume L22: C11 in D2;
reconsider D6 = C11 as (Point of ( TOP-REAL R2 )) by EUCLID:67;
consider C12 being  positive  real number such that L23: ( Ball (D6 , C12) ) c= D2 by L20 , L22;
take C12;
thus L24: thesis by L12 , L23 , TOPREAL9:13;
end;
L25: D2 is  open by L21 , TOPMETR:15;
thus L26: thesis by L25 , L11 , TOPS_3:76;
end;
theorem
L27: (for B14 , B15 being non  empty TopSpace holds (for B16 being (Function of B14 , B15) holds (B16 is  open iff (for B17 being (Point of B14) holds (for B18 being  open (Subset of B14) holds (B17 in B18 implies (ex B19 being  open (Subset of B15) st (( B16 . B17 ) in B19 & B19 c= ( B16 .: B18 )))))))))
proof
let C13 , C14 being non  empty TopSpace;
let C15 being (Function of C13 , C14);
thus L28: (C15 is  open implies (for B20 being (Point of C13) holds (for B21 being  open (Subset of C13) holds (B20 in B21 implies (ex B22 being  open (Subset of C14) st (( C15 . B20 ) in B22 & B22 c= ( C15 .: B21 )))))))
proof
assume L29: C15 is  open;
let C16 being (Point of C13);
let C17 being  open (Subset of C13);
assume that
L30: C16 in C17;
L31: C17 is (a_neighborhood of C16) by L30 , CONNSP_2:3;
consider C18 being  open (a_neighborhood of ( C15 . C16 )) such that L32: C18 c= ( C15 .: C17 ) by L31 , L29 , TOPGRP_1:22;
take C18;
thus L33: ( C15 . C16 ) in C18 by CONNSP_2:4;
thus L34: thesis by L32;
end;

assume L35: (for B23 being (Point of C13) holds (for B24 being  open (Subset of C13) holds (B23 in B24 implies (ex B25 being  open (Subset of C14) st (( C15 . B23 ) in B25 & B25 c= ( C15 .: B24 ))))));
L36: (for B26 being (Point of C13) holds (for B27 being  open (a_neighborhood of B26) holds (ex B28 being (a_neighborhood of ( C15 . B26 )) st B28 c= ( C15 .: B27 ))))
proof
let C19 being (Point of C13);
let C20 being  open (a_neighborhood of C19);
consider C21 being  open (Subset of C14) such that L37: ( C15 . C19 ) in C21 and L38: C21 c= ( C15 .: C20 ) by L35 , CONNSP_2:4;
L39: C21 is (a_neighborhood of ( C15 . C19 )) by L37 , CONNSP_2:3;
thus L40: thesis by L39 , L38;
end;
thus L41: thesis by L36 , TOPGRP_1:23;
end;
theorem
L42: (for R3 being non  empty TopSpace holds (for R4 being non  empty MetrSpace holds (for B29 being (Function of R3 , ( TopSpaceMetr R4 )) holds (B29 is  open iff (for B30 being (Point of R3) holds (for B31 being  open (Subset of R3) holds (for B32 being (Point of R4) holds ((B32 = ( B29 . B30 ) & B30 in B31) implies (ex B33 being  positive  real number st ( Ball (B32 , B33) ) c= ( B29 .: B31 ))))))))))
proof
let R3 being non  empty TopSpace;
let R4 being non  empty MetrSpace;
let C22 being (Function of R3 , ( TopSpaceMetr R4 ));
thus L43: (C22 is  open implies (for B34 being (Point of R3) holds (for B35 being  open (Subset of R3) holds (for B36 being (Point of R4) holds ((B36 = ( C22 . B34 ) & B34 in B35) implies (ex B37 being  positive  real number st ( Ball (B36 , B37) ) c= ( C22 .: B35 )))))))
proof
assume L44: C22 is  open;
let C23 being (Point of R3);
let C24 being  open (Subset of R3);
let C25 being (Point of R4);
assume that
L45: C25 = ( C22 . C23 );
assume L46: C23 in C24;
consider C26 being  open (Subset of ( TopSpaceMetr R4 )) such that L47: ( C22 . C23 ) in C26 and L48: C26 c= ( C22 .: C24 ) by L46 , L44 , L27;
L49: (ex B38 being  real number st (B38 > ( 0 ) & ( Ball (C25 , B38) ) c= C26)) by L45 , L47 , TOPMETR:15;
thus L50: thesis by L49 , L48 , XBOOLE_1:1;
end;

assume L51: (for B39 being (Point of R3) holds (for B40 being  open (Subset of R3) holds (for B41 being (Point of R4) holds ((B41 = ( C22 . B39 ) & B39 in B40) implies (ex B42 being  positive  real number st ( Ball (B41 , B42) ) c= ( C22 .: B40 ))))));
L52: (for B43 being (Point of R3) holds (for B44 being  open (Subset of R3) holds (B43 in B44 implies (ex B45 being  open (Subset of ( TopSpaceMetr R4 )) st (( C22 . B43 ) in B45 & B45 c= ( C22 .: B44 ))))))
proof
let C27 being (Point of R3);
let C28 being  open (Subset of R3);
reconsider D7 = ( C22 . C27 ) as (Point of R4);
assume L53: C27 in C28;
consider C29 being  positive  real number such that L54: ( Ball (D7 , C29) ) c= ( C22 .: C28 ) by L53 , L51;
reconsider D8 = ( Ball (D7 , C29) ) as  open (Subset of ( TopSpaceMetr R4 )) by TOPMETR:14;
take D8;
thus L55: ( C22 . C27 ) in D8 by GOBOARD6:1;
thus L56: D8 c= ( C22 .: C28 ) by L54;
end;
thus L57: thesis by L52 , L27;
end;
theorem
L58: (for R3 being non  empty TopSpace holds (for R4 being non  empty MetrSpace holds (for B46 being (Function of ( TopSpaceMetr R4 ) , R3) holds (B46 is  open iff (for B47 being (Point of R4) holds (for B48 being  positive  real number holds (ex B49 being  open (Subset of R3) st (( B46 . B47 ) in B49 & B49 c= ( B46 .: ( Ball (B47 , B48) ) )))))))))
proof
let R3 being non  empty TopSpace;
let R4 being non  empty MetrSpace;
let C30 being (Function of ( TopSpaceMetr R4 ) , R3);
thus L59:now
assume L60: C30 is  open;
let C31 being (Point of R4);
let C32 being  positive  real number;
L61: C31 in ( Ball (C31 , C32) ) by GOBOARD6:1;
reconsider D9 = ( Ball (C31 , C32) ) as (Subset of ( TopSpaceMetr R4 ));
L62: D9 is  open by TOPMETR:14;
consider C33 being  open (Subset of R3) such that L63: (( C30 . C31 ) in C33 & C33 c= ( C30 .: D9 )) by L62 , L60 , L61 , L27;
take D10 = C33;
thus L64: (( C30 . C31 ) in D10 & D10 c= ( C30 .: ( Ball (C31 , C32) ) )) by L63;
end;
assume L65: (for B50 being (Point of R4) holds (for B51 being  positive  real number holds (ex B52 being  open (Subset of R3) st (( C30 . B50 ) in B52 & B52 c= ( C30 .: ( Ball (B50 , B51) ) )))));
L66: (for B53 being (Point of ( TopSpaceMetr R4 )) holds (for B54 being  open (Subset of ( TopSpaceMetr R4 )) holds (B53 in B54 implies (ex B55 being  open (Subset of R3) st (( C30 . B53 ) in B55 & B55 c= ( C30 .: B54 ))))))
proof
let C34 being (Point of ( TopSpaceMetr R4 ));
let C35 being  open (Subset of ( TopSpaceMetr R4 ));
reconsider D11 = C34 as (Point of R4);
assume L67: C34 in C35;
consider C36 being  real number such that L68: C36 > ( 0 ) and L69: ( Ball (D11 , C36) ) c= C35 by L67 , TOPMETR:15;
consider C37 being  open (Subset of R3) such that L70: ( C30 . C34 ) in C37 and L71: C37 c= ( C30 .: ( Ball (D11 , C36) ) ) by L65 , L68;
take C37;
thus L72: ( C30 . C34 ) in C37 by L70;
L73: ( C30 .: ( Ball (D11 , C36) ) ) c= ( C30 .: C35 ) by L69 , RELAT_1:123;
thus L74: thesis by L73 , L71 , XBOOLE_1:1;
end;
thus L75: thesis by L66 , L27;
end;
theorem
L76: (for R5 being non  empty MetrSpace holds (for R6 being non  empty MetrSpace holds (for B56 being (Function of ( TopSpaceMetr R5 ) , ( TopSpaceMetr R6 )) holds (B56 is  open iff (for B57 being (Point of R5) holds (for B58 being (Point of R6) holds (for B59 being  positive  real number holds (B58 = ( B56 . B57 ) implies (ex B60 being  positive  real number st ( Ball (B58 , B60) ) c= ( B56 .: ( Ball (B57 , B59) ) ))))))))))
proof
let R5 being non  empty MetrSpace;
let R6 being non  empty MetrSpace;
let C38 being (Function of ( TopSpaceMetr R5 ) , ( TopSpaceMetr R6 ));
thus L77: (C38 is  open implies (for B61 being (Point of R5) holds (for B62 being (Point of R6) holds (for B63 being  positive  real number holds (B62 = ( C38 . B61 ) implies (ex B64 being  positive  real number st ( Ball (B62 , B64) ) c= ( C38 .: ( Ball (B61 , B63) ) )))))))
proof
assume L78: C38 is  open;
let C39 being (Point of R5);
let C40 being (Point of R6);
let C41 being  positive  real number;
assume that
L79: C40 = ( C38 . C39 );
reconsider D12 = ( Ball (C39 , C41) ) as (Subset of ( TopSpaceMetr R5 ));
L80: C39 in D12 by GOBOARD6:1;
L81: D12 is  open by TOPMETR:14;
thus L82: thesis by L81 , L78 , L79 , L80 , L42;
end;

assume L83: (for B65 being (Point of R5) holds (for B66 being (Point of R6) holds (for B67 being  positive  real number holds (B66 = ( C38 . B65 ) implies (ex B68 being  positive  real number st ( Ball (B66 , B68) ) c= ( C38 .: ( Ball (B65 , B67) ) ))))));
L84: (for B69 being (Point of ( TopSpaceMetr R5 )) holds (for B70 being  open (Subset of ( TopSpaceMetr R5 )) holds (for B71 being (Point of R6) holds ((B71 = ( C38 . B69 ) & B69 in B70) implies (ex B72 being  positive  real number st ( Ball (B71 , B72) ) c= ( C38 .: B70 ))))))
proof
let C42 being (Point of ( TopSpaceMetr R5 ));
let C43 being  open (Subset of ( TopSpaceMetr R5 ));
let C44 being (Point of R6);
assume that
L85: C44 = ( C38 . C42 );
reconsider D13 = C42 as (Point of R5);
assume L86: C42 in C43;
consider C45 being  real number such that L87: C45 > ( 0 ) and L88: ( Ball (D13 , C45) ) c= C43 by L86 , TOPMETR:15;
L89: ( C38 .: ( Ball (D13 , C45) ) ) c= ( C38 .: C43 ) by L88 , RELAT_1:123;
L90: (ex B73 being  positive  real number st ( Ball (C44 , B73) ) c= ( C38 .: ( Ball (D13 , C45) ) )) by L83 , L85 , L87;
thus L91: thesis by L90 , L89 , XBOOLE_1:1;
end;
thus L92: thesis by L84 , L42;
end;
theorem
L93: (for R2 being Nat holds (for R3 being non  empty TopSpace holds (for B74 being (Function of R3 , ( TOP-REAL R2 )) holds (B74 is  open iff (for B75 being (Point of R3) holds (for B76 being  open (Subset of R3) holds (B75 in B76 implies (ex B77 being  positive  real number st ( Ball (( B74 . B75 ) , B77) ) c= ( B74 .: B76 )))))))))
proof
let R2 being Nat;
let R3 being non  empty TopSpace;
let C46 being (Function of R3 , ( TOP-REAL R2 ));
L94: ( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) by EUCLID:def 8;
reconsider D14 = C46 as (Function of R3 , ( TopSpaceMetr ( Euclid R2 ) )) by L94;
L95: ( the TopStruct of R3 ) = ( the TopStruct of R3 );
L96: R2 in ( NAT ) by ORDINAL1:def 12;
thus L97: (C46 is  open implies (for B78 being (Point of R3) holds (for B79 being  open (Subset of R3) holds (B78 in B79 implies (ex B80 being  positive  real number st ( Ball (( C46 . B78 ) , B80) ) c= ( C46 .: B79 ))))))
proof
assume L98: C46 is  open;
let C47 being (Point of R3);
let C48 being  open (Subset of R3);
assume L99: C47 in C48;
reconsider D15 = ( C46 . C47 ) as (Point of ( Euclid R2 )) by EUCLID:67;
L100: D14 is  open by L98 , L94 , L95 , L1;
consider C49 being  positive  real number such that L101: ( Ball (D15 , C49) ) c= ( D14 .: C48 ) by L100 , L99 , L42;
L102: ( Ball (( C46 . C47 ) , C49) ) = ( Ball (D15 , C49) ) by L96 , TOPREAL9:13;
thus L103: thesis by L102 , L101;
end;

assume L104: (for B81 being (Point of R3) holds (for B82 being  open (Subset of R3) holds (B81 in B82 implies (ex B83 being  positive  real number st ( Ball (( C46 . B81 ) , B83) ) c= ( C46 .: B82 )))));
L105: (for B84 being (Point of R3) holds (for B85 being  open (Subset of R3) holds (for B86 being (Point of ( Euclid R2 )) holds ((B86 = ( D14 . B84 ) & B84 in B85) implies (ex B87 being  positive  real number st ( Ball (B86 , B87) ) c= ( D14 .: B85 ))))))
proof
let C50 being (Point of R3);
let C51 being  open (Subset of R3);
let C52 being (Point of ( Euclid R2 ));
assume that
L106: C52 = ( D14 . C50 );
assume L107: C50 in C51;
consider C53 being  positive  real number such that L108: ( Ball (( C46 . C50 ) , C53) ) c= ( C46 .: C51 ) by L107 , L104;
L109: ( Ball (( C46 . C50 ) , C53) ) = ( Ball (C52 , C53) ) by L96 , L106 , TOPREAL9:13;
thus L110: thesis by L109 , L108;
end;
L111: D14 is  open by L105 , L42;
thus L112: thesis by L111 , L94 , L95 , L1;
end;
theorem
L113: (for R2 being Nat holds (for R3 being non  empty TopSpace holds (for B88 being (Function of ( TOP-REAL R2 ) , R3) holds (B88 is  open iff (for B89 being (Point of ( TOP-REAL R2 )) holds (for B90 being  positive  real number holds (ex B91 being  open (Subset of R3) st (( B88 . B89 ) in B91 & B91 c= ( B88 .: ( Ball (B89 , B90) ) )))))))))
proof
let R2 being Nat;
let R3 being non  empty TopSpace;
let C54 being (Function of ( TOP-REAL R2 ) , R3);
L114: ( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) by EUCLID:def 8;
reconsider D16 = C54 as (Function of ( TopSpaceMetr ( Euclid R2 ) ) , R3) by L114;
L115: ( the TopStruct of R3 ) = ( the TopStruct of R3 );
L116: R2 in ( NAT ) by ORDINAL1:def 12;
thus L117: (C54 is  open implies (for B92 being (Point of ( TOP-REAL R2 )) holds (for B93 being  positive  real number holds (ex B94 being  open (Subset of R3) st (( C54 . B92 ) in B94 & B94 c= ( C54 .: ( Ball (B92 , B93) ) ))))))
proof
assume L118: C54 is  open;
let C55 being (Point of ( TOP-REAL R2 ));
let C56 being  positive  real number;
reconsider D17 = C55 as (Point of ( Euclid R2 )) by EUCLID:67;
L119: D16 is  open by L118 , L114 , L115 , L1;
consider C57 being  open (Subset of R3) such that L120: (( D16 . C55 ) in C57 & C57 c= ( D16 .: ( Ball (D17 , C56) ) )) by L119 , L58;
L121: ( Ball (C55 , C56) ) = ( Ball (D17 , C56) ) by L116 , TOPREAL9:13;
thus L122: thesis by L121 , L120;
end;

assume L123: (for B95 being (Point of ( TOP-REAL R2 )) holds (for B96 being  positive  real number holds (ex B97 being  open (Subset of R3) st (( C54 . B95 ) in B97 & B97 c= ( C54 .: ( Ball (B95 , B96) ) )))));
L124: (for B98 being (Point of ( Euclid R2 )) holds (for B99 being  positive  real number holds (ex B100 being  open (Subset of R3) st (( D16 . B98 ) in B100 & B100 c= ( D16 .: ( Ball (B98 , B99) ) )))))
proof
let C58 being (Point of ( Euclid R2 ));
let C59 being  positive  real number;
reconsider D18 = C58 as (Point of ( TOP-REAL R2 )) by EUCLID:67;
consider C60 being  open (Subset of R3) such that L125: (( C54 . D18 ) in C60 & C60 c= ( C54 .: ( Ball (D18 , C59) ) )) by L123;
L126: ( Ball (C58 , C59) ) = ( Ball (D18 , C59) ) by L116 , TOPREAL9:13;
thus L127: thesis by L126 , L125;
end;
L128: D16 is  open by L124 , L58;
thus L129: thesis by L128 , L114 , L115 , L1;
end;
theorem
L130: (for R1 being Nat holds (for R2 being Nat holds (for B101 being (Function of ( TOP-REAL R2 ) , ( TOP-REAL R1 )) holds (B101 is  open iff (for B102 being (Point of ( TOP-REAL R2 )) holds (for B103 being  positive  real number holds (ex B104 being  positive  real number st ( Ball (( B101 . B102 ) , B104) ) c= ( B101 .: ( Ball (B102 , B103) ) ))))))))
proof
let R1 being Nat;
let R2 being Nat;
let C61 being (Function of ( TOP-REAL R2 ) , ( TOP-REAL R1 ));
L131: (( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) & ( the TopStruct of ( TOP-REAL R1 ) ) = ( TopSpaceMetr ( Euclid R1 ) )) by EUCLID:def 8;
reconsider D19 = C61 as (Function of ( TopSpaceMetr ( Euclid R2 ) ) , ( TopSpaceMetr ( Euclid R1 ) )) by L131;
L132: (R2 in ( NAT ) & R1 in ( NAT )) by ORDINAL1:def 12;
thus L133: (C61 is  open implies (for B105 being (Point of ( TOP-REAL R2 )) holds (for B106 being  positive  real number holds (ex B107 being  positive  real number st ( Ball (( C61 . B105 ) , B107) ) c= ( C61 .: ( Ball (B105 , B106) ) )))))
proof
assume L134: C61 is  open;
let C62 being (Point of ( TOP-REAL R2 ));
let C63 being  positive  real number;
reconsider D20 = C62 as (Point of ( Euclid R2 )) by EUCLID:67;
reconsider D21 = ( C61 . C62 ) as (Point of ( Euclid R1 )) by EUCLID:67;
L135: D19 is  open by L131 , L134 , L1;
consider C64 being  positive  real number such that L136: ( Ball (D21 , C64) ) c= ( D19 .: ( Ball (D20 , C63) ) ) by L135 , L76;
L137: (( Ball (D20 , C63) ) = ( Ball (C62 , C63) ) & ( Ball (D21 , C64) ) = ( Ball (( C61 . C62 ) , C64) )) by L132 , TOPREAL9:13;
thus L138: thesis by L137 , L136;
end;

assume L139: (for B108 being (Point of ( TOP-REAL R2 )) holds (for B109 being  positive  real number holds (ex B110 being  positive  real number st ( Ball (( C61 . B108 ) , B110) ) c= ( C61 .: ( Ball (B108 , B109) ) ))));
L140: (for B111 being (Point of ( Euclid R2 )) holds (for B112 being (Point of ( Euclid R1 )) holds (for B113 being  positive  real number holds (B112 = ( D19 . B111 ) implies (ex B114 being  positive  real number st ( Ball (B112 , B114) ) c= ( D19 .: ( Ball (B111 , B113) ) ))))))
proof
let C65 being (Point of ( Euclid R2 ));
let C66 being (Point of ( Euclid R1 ));
let C67 being  positive  real number;
assume that
L141: C66 = ( D19 . C65 );
reconsider D22 = C65 as (Point of ( TOP-REAL R2 )) by EUCLID:67;
reconsider D23 = C66 as (Point of ( TOP-REAL R1 )) by EUCLID:67;
consider C68 being  positive  real number such that L142: ( Ball (D23 , C68) ) c= ( C61 .: ( Ball (D22 , C67) ) ) by L139 , L141;
L143: (( Ball (D22 , C67) ) = ( Ball (C65 , C67) ) & ( Ball (D23 , C68) ) = ( Ball (C66 , C68) )) by L132 , TOPREAL9:13;
thus L144: thesis by L143 , L142;
end;
L145: D19 is  open by L140 , L76;
thus L146: thesis by L145 , L131 , L1;
end;
theorem
L147: (for R3 being non  empty TopSpace holds (for B115 being (Function of R3 , ( R^1 )) holds (B115 is  open iff (for B116 being (Point of R3) holds (for B117 being  open (Subset of R3) holds (B116 in B117 implies (ex B118 being  positive  real number st ]. ( ( B115 . B116 ) - B118 ) , ( ( B115 . B116 ) + B118 ) .[ c= ( B115 .: B117 ))))))))
proof
let R3 being non  empty TopSpace;
let C69 being (Function of R3 , ( R^1 ));
thus L148: (C69 is  open implies (for B119 being (Point of R3) holds (for B120 being  open (Subset of R3) holds (B119 in B120 implies (ex B121 being  positive  real number st ]. ( ( C69 . B119 ) - B121 ) , ( ( C69 . B119 ) + B121 ) .[ c= ( C69 .: B120 ))))))
proof
assume L149: C69 is  open;
let C70 being (Point of R3);
let C71 being  open (Subset of R3);
assume L150: C70 in C71;
reconsider D24 = ( C69 . C70 ) as (Point of ( RealSpace ));
consider C72 being  positive  real number such that L151: ( Ball (D24 , C72) ) c= ( C69 .: C71 ) by L149 , L150 , L42;
L152: C72 in ( REAL ) by XREAL_0:def 1;
L153: ]. ( D24 - C72 ) , ( D24 + C72 ) .[ = ( Ball (D24 , C72) ) by L152 , FRECHET:7;
thus L154: thesis by L153 , L151;
end;

assume L155: (for B122 being (Point of R3) holds (for B123 being  open (Subset of R3) holds (B122 in B123 implies (ex B124 being  positive  real number st ]. ( ( C69 . B122 ) - B124 ) , ( ( C69 . B122 ) + B124 ) .[ c= ( C69 .: B123 )))));
L156: (for B125 being (Point of R3) holds (for B126 being  open (Subset of R3) holds (for B127 being (Point of ( RealSpace )) holds ((B127 = ( C69 . B125 ) & B125 in B126) implies (ex B128 being  positive  real number st ( Ball (B127 , B128) ) c= ( C69 .: B126 ))))))
proof
let C73 being (Point of R3);
let C74 being  open (Subset of R3);
let C75 being (Point of ( RealSpace ));
assume that
L157: C75 = ( C69 . C73 );
assume L158: C73 in C74;
consider C76 being  positive  real number such that L159: ]. ( ( C69 . C73 ) - C76 ) , ( ( C69 . C73 ) + C76 ) .[ c= ( C69 .: C74 ) by L158 , L155;
L160: C76 in ( REAL ) by XREAL_0:def 1;
L161: ]. ( C75 - C76 ) , ( C75 + C76 ) .[ = ( Ball (C75 , C76) ) by L160 , FRECHET:7;
thus L162: thesis by L161 , L157 , L159;
end;
thus L163: thesis by L156 , L42;
end;
theorem
L164: (for R3 being non  empty TopSpace holds (for B129 being (Function of ( R^1 ) , R3) holds (B129 is  open iff (for B130 being (Point of ( R^1 )) holds (for B131 being  positive  real number holds (ex B132 being  open (Subset of R3) st (( B129 . B130 ) in B132 & B132 c= ( B129 .: ]. ( B130 - B131 ) , ( B130 + B131 ) .[ ))))))))
proof
let R3 being non  empty TopSpace;
let C77 being (Function of ( R^1 ) , R3);
thus L165: (C77 is  open implies (for B133 being (Point of ( R^1 )) holds (for B134 being  positive  real number holds (ex B135 being  open (Subset of R3) st (( C77 . B133 ) in B135 & B135 c= ( C77 .: ]. ( B133 - B134 ) , ( B133 + B134 ) .[ ))))))
proof
assume L166: C77 is  open;
let C78 being (Point of ( R^1 ));
let C79 being  positive  real number;
reconsider D25 = C78 as (Point of ( RealSpace ));
consider C80 being  open (Subset of R3) such that L167: (( C77 . C78 ) in C80 & C80 c= ( C77 .: ( Ball (D25 , C79) ) )) by L166 , L58;
L168: C79 in ( REAL ) by XREAL_0:def 1;
L169: ]. ( D25 - C79 ) , ( D25 + C79 ) .[ = ( Ball (D25 , C79) ) by L168 , FRECHET:7;
thus L170: thesis by L169 , L167;
end;

assume L171: (for B136 being (Point of ( R^1 )) holds (for B137 being  positive  real number holds (ex B138 being  open (Subset of R3) st (( C77 . B136 ) in B138 & B138 c= ( C77 .: ]. ( B136 - B137 ) , ( B136 + B137 ) .[ )))));
L172: (for B139 being (Point of ( RealSpace )) holds (for B140 being  positive  real number holds (ex B141 being  open (Subset of R3) st (( C77 . B139 ) in B141 & B141 c= ( C77 .: ( Ball (B139 , B140) ) )))))
proof
let C81 being (Point of ( RealSpace ));
let C82 being  positive  real number;
reconsider D26 = C81 as (Point of ( R^1 ));
consider C83 being  open (Subset of R3) such that L173: (( C77 . D26 ) in C83 & C83 c= ( C77 .: ]. ( C81 - C82 ) , ( C81 + C82 ) .[ )) by L171;
L174: C82 in ( REAL ) by XREAL_0:def 1;
L175: ]. ( C81 - C82 ) , ( C81 + C82 ) .[ = ( Ball (C81 , C82) ) by L174 , FRECHET:7;
thus L176: thesis by L175 , L173;
end;
thus L177: thesis by L172 , L58;
end;
theorem
L178: (for B142 being (Function of ( R^1 ) , ( R^1 )) holds (B142 is  open iff (for B143 being (Point of ( R^1 )) holds (for B144 being  positive  real number holds (ex B145 being  positive  real number st ]. ( ( B142 . B143 ) - B145 ) , ( ( B142 . B143 ) + B145 ) .[ c= ( B142 .: ]. ( B143 - B144 ) , ( B143 + B144 ) .[ ))))))
proof
let C84 being (Function of ( R^1 ) , ( R^1 ));
thus L179: (C84 is  open implies (for B146 being (Point of ( R^1 )) holds (for B147 being  positive  real number holds (ex B148 being  positive  real number st ]. ( ( C84 . B146 ) - B148 ) , ( ( C84 . B146 ) + B148 ) .[ c= ( C84 .: ]. ( B146 - B147 ) , ( B146 + B147 ) .[ )))))
proof
assume L180: C84 is  open;
let C85 being (Point of ( R^1 ));
let C86 being  positive  real number;
reconsider D27 = C85 , D28 = ( C84 . C85 ) as (Point of ( RealSpace ));
consider C87 being  positive  real number such that L181: ( Ball (D28 , C87) ) c= ( C84 .: ( Ball (D27 , C86) ) ) by L180 , L76;
L182: (C86 in ( REAL ) & C87 in ( REAL )) by XREAL_0:def 1;
L183: (]. ( C85 - C86 ) , ( C85 + C86 ) .[ = ( Ball (D27 , C86) ) & ]. ( ( C84 . C85 ) - C87 ) , ( ( C84 . C85 ) + C87 ) .[ = ( Ball (D28 , C87) )) by L182 , FRECHET:7;
thus L184: thesis by L183 , L181;
end;

assume L185: (for B149 being (Point of ( R^1 )) holds (for B150 being  positive  real number holds (ex B151 being  positive  real number st ]. ( ( C84 . B149 ) - B151 ) , ( ( C84 . B149 ) + B151 ) .[ c= ( C84 .: ]. ( B149 - B150 ) , ( B149 + B150 ) .[ ))));
L186: (for B152 , B153 being (Point of ( RealSpace )) holds (for B154 being  positive  real number holds (B153 = ( C84 . B152 ) implies (ex B155 being  positive  real number st ( Ball (B153 , B155) ) c= ( C84 .: ( Ball (B152 , B154) ) )))))
proof
let C88 , C89 being (Point of ( RealSpace ));
let C90 being  positive  real number;
assume that
L187: C89 = ( C84 . C88 );
consider C91 being  positive  real number such that L188: ]. ( ( C84 . C88 ) - C91 ) , ( ( C84 . C88 ) + C91 ) .[ c= ( C84 .: ]. ( C88 - C90 ) , ( C88 + C90 ) .[ ) by L185;
L189: (C90 in ( REAL ) & C91 in ( REAL )) by XREAL_0:def 1;
L190: (]. ( C88 - C90 ) , ( C88 + C90 ) .[ = ( Ball (C88 , C90) ) & ]. ( ( C84 . C88 ) - C91 ) , ( ( C84 . C88 ) + C91 ) .[ = ( Ball (C89 , C91) )) by L189 , L187 , FRECHET:7;
thus L191: thesis by L190 , L188;
end;
thus L192: thesis by L186 , L76;
end;
theorem
L193: (for R2 being Nat holds (for B156 being (Function of ( TOP-REAL R2 ) , ( R^1 )) holds (B156 is  open iff (for B157 being (Point of ( TOP-REAL R2 )) holds (for B158 being  positive  real number holds (ex B159 being  positive  real number st ]. ( ( B156 . B157 ) - B159 ) , ( ( B156 . B157 ) + B159 ) .[ c= ( B156 .: ( Ball (B157 , B158) ) )))))))
proof
let R2 being Nat;
let C92 being (Function of ( TOP-REAL R2 ) , ( R^1 ));
L194: R2 in ( NAT ) by ORDINAL1:def 12;
thus L195:now
assume L196: C92 is  open;
let C93 being (Point of ( TOP-REAL R2 ));
let C94 being  positive  real number;
L197: C93 in ( Ball (C93 , C94) ) by L194 , TOPGEN_5:13;
L198: ( C92 . C93 ) in ( C92 .: ( Ball (C93 , C94) ) ) by L197 , FUNCT_2:35;
L199: ( C92 .: ( Ball (C93 , C94) ) ) is  open by L196 , T_0TOPSP:def 2;
consider C95 being (Element of ( REAL )) such that L200: C95 > ( 0 ) and L201: ]. ( ( C92 . C93 ) - C95 ) , ( ( C92 . C93 ) + C95 ) .[ c= ( C92 .: ( Ball (C93 , C94) ) ) by L199 , L198 , FRECHET:8;
reconsider D29 = C95 as  positive  real number by L200;
take D30 = D29;
thus L202: ]. ( ( C92 . C93 ) - D30 ) , ( ( C92 . C93 ) + D30 ) .[ c= ( C92 .: ( Ball (C93 , C94) ) ) by L201;
end;
assume L203: (for B160 being (Point of ( TOP-REAL R2 )) holds (for B161 being  positive  real number holds (ex B162 being  positive  real number st ]. ( ( C92 . B160 ) - B162 ) , ( ( C92 . B160 ) + B162 ) .[ c= ( C92 .: ( Ball (B160 , B161) ) ))));
let C96 being (Subset of ( TOP-REAL R2 ));
assume that
L204: C96 is  open;
L205: (for B163 being set holds (B163 in ( C92 .: C96 ) iff (ex B164 being (Subset of ( R^1 )) st (B164 is  open & B164 c= ( C92 .: C96 ) & B163 in B164))))
proof
let C97 being set;
thus L206:now
assume L207: C97 in ( C92 .: C96 );
consider C98 being (Point of ( TOP-REAL R2 )) such that L208: C98 in C96 and L209: C97 = ( C92 . C98 ) by L207 , FUNCT_2:65;
reconsider D31 = C98 as (Point of ( Euclid R2 )) by EUCLID:67;
L210: C96 = ( Int C96 ) by L204 , TOPS_1:23;
consider C99 being  real number such that L211: C99 > ( 0 ) and L212: ( Ball (D31 , C99) ) c= C96 by L210 , L208 , GOBOARD6:5;
L213: ( Ball (D31 , C99) ) = ( Ball (C98 , C99) ) by L194 , TOPREAL9:13;
consider C100 being  positive  real number such that L214: ]. ( ( C92 . C98 ) - C100 ) , ( ( C92 . C98 ) + C100 ) .[ c= ( C92 .: ( Ball (C98 , C99) ) ) by L203 , L211;
take D32 = ( R^1 ]. ( ( C92 . C98 ) - C100 ) , ( ( C92 . C98 ) + C100 ) .[ );
thus L215: D32 is  open;
L216: ( C92 .: ( Ball (C98 , C99) ) ) c= ( C92 .: C96 ) by L212 , L213 , RELAT_1:123;
thus L217: D32 c= ( C92 .: C96 ) by L216 , L214 , XBOOLE_1:1;
thus L218: C97 in D32 by L209 , TOPREAL6:15;
end;
thus L219: thesis;
end;
thus L220: ( C92 .: C96 ) is  open by L205 , TOPS_1:25;
end;
theorem
L221: (for R2 being Nat holds (for B165 being (Function of ( R^1 ) , ( TOP-REAL R2 )) holds (B165 is  open iff (for B166 being (Point of ( R^1 )) holds (for B167 being  positive  real number holds (ex B168 being  positive  real number st ( Ball (( B165 . B166 ) , B168) ) c= ( B165 .: ]. ( B166 - B167 ) , ( B166 + B167 ) .[ )))))))
proof
let R2 being Nat;
let C101 being (Function of ( R^1 ) , ( TOP-REAL R2 ));
L222: ( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) by EUCLID:def 8;
reconsider D33 = C101 as (Function of ( R^1 ) , ( TopSpaceMetr ( Euclid R2 ) )) by L222;
L223: R2 in ( NAT ) by ORDINAL1:def 12;
thus L224: (C101 is  open implies (for B169 being (Point of ( R^1 )) holds (for B170 being  positive  real number holds (ex B171 being  positive  real number st ( Ball (( C101 . B169 ) , B171) ) c= ( C101 .: ]. ( B169 - B170 ) , ( B169 + B170 ) .[ )))))
proof
assume L225: C101 is  open;
let C102 being (Point of ( R^1 ));
let C103 being  positive  real number;
reconsider D34 = C102 as (Point of ( RealSpace ));
reconsider D35 = ( C101 . C102 ) as (Point of ( Euclid R2 )) by EUCLID:67;
L226: D33 is  open by L222 , L225 , L1;
consider C104 being  positive  real number such that L227: ( Ball (D35 , C104) ) c= ( D33 .: ( Ball (D34 , C103) ) ) by L226 , L76;
L228: C103 in ( REAL ) by XREAL_0:def 1;
L229: (]. ( C102 - C103 ) , ( C102 + C103 ) .[ = ( Ball (D34 , C103) ) & ( Ball (( C101 . C102 ) , C104) ) = ( Ball (D35 , C104) )) by L228 , L223 , FRECHET:7 , TOPREAL9:13;
thus L230: thesis by L229 , L227;
end;

assume L231: (for B172 being (Point of ( R^1 )) holds (for B173 being  positive  real number holds (ex B174 being  positive  real number st ( Ball (( C101 . B172 ) , B174) ) c= ( C101 .: ]. ( B172 - B173 ) , ( B172 + B173 ) .[ ))));
L232: (for B175 being (Point of ( RealSpace )) holds (for B176 being (Point of ( Euclid R2 )) holds (for B177 being  positive  real number holds (B176 = ( D33 . B175 ) implies (ex B178 being  positive  real number st ( Ball (B176 , B178) ) c= ( D33 .: ( Ball (B175 , B177) ) ))))))
proof
let C105 being (Point of ( RealSpace ));
let C106 being (Point of ( Euclid R2 ));
let C107 being  positive  real number;
assume that
L233: C106 = ( D33 . C105 );
reconsider D36 = C105 as (Point of ( R^1 ));
consider C108 being  positive  real number such that L234: ( Ball (( C101 . D36 ) , C108) ) c= ( C101 .: ]. ( D36 - C107 ) , ( D36 + C107 ) .[ ) by L231;
L235: (C107 in ( REAL ) & C108 in ( REAL )) by XREAL_0:def 1;
L236: (]. ( D36 - C107 ) , ( D36 + C107 ) .[ = ( Ball (C105 , C107) ) & ( Ball (( C101 . D36 ) , C108) ) = ( Ball (C106 , C108) )) by L235 , L223 , L233 , FRECHET:7 , TOPREAL9:13;
thus L237: thesis by L236 , L234;
end;
L238: D33 is  open by L232 , L76;
thus L239: thesis by L238 , L222 , L1;
end;
begin
theorem
L240: (for R3 being non  empty TopSpace holds (for R4 being non  empty MetrSpace holds (for B179 being (Function of R3 , ( TopSpaceMetr R4 )) holds (B179 is  continuous iff (for B180 being (Point of R3) holds (for B181 being (Point of R4) holds (for B182 being  positive  real number holds (B181 = ( B179 . B180 ) implies (ex B183 being  open (Subset of R3) st (B180 in B183 & ( B179 .: B183 ) c= ( Ball (B181 , B182) )))))))))))
proof
let R3 being non  empty TopSpace;
let R4 being non  empty MetrSpace;
let C109 being (Function of R3 , ( TopSpaceMetr R4 ));
thus L241: (C109 is  continuous implies (for B184 being (Point of R3) holds (for B185 being (Point of R4) holds (for B186 being  positive  real number holds (B185 = ( C109 . B184 ) implies (ex B187 being  open (Subset of R3) st (B184 in B187 & ( C109 .: B187 ) c= ( Ball (B185 , B186) ))))))))
proof
assume L242: C109 is  continuous;
let C110 being (Point of R3);
let C111 being (Point of R4);
let C112 being  positive  real number;
assume L243: ( C109 . C110 ) = C111;
reconsider D37 = ( Ball (C111 , C112) ) as (Subset of ( TopSpaceMetr R4 ));
L244: C111 in ( Ball (C111 , C112) ) by GOBOARD6:1;
L245: D37 is  open by TOPMETR:14;
L246: (ex B188 being (Subset of R3) st (C110 in B188 & B188 is  open & ( C109 .: B188 ) c= D37)) by L245 , L242 , L243 , L244 , JGRAPH_2:10;
thus L247: thesis by L246;
end;

assume L248: (for B189 being (Point of R3) holds (for B190 being (Point of R4) holds (for B191 being  positive  real number holds (B190 = ( C109 . B189 ) implies (ex B192 being  open (Subset of R3) st (B189 in B192 & ( C109 .: B192 ) c= ( Ball (B190 , B191) )))))));
L249: (for B193 being (Point of R3) holds (for B194 being (Subset of ( TopSpaceMetr R4 )) holds ((( C109 . B193 ) in B194 & B194 is  open) implies (ex B195 being (Subset of R3) st (B193 in B195 & B195 is  open & ( C109 .: B195 ) c= B194)))))
proof
let C113 being (Point of R3);
let C114 being (Subset of ( TopSpaceMetr R4 ));
assume that
L250: ( C109 . C113 ) in C114;
reconsider D38 = ( C109 . C113 ) as (Point of R4);
assume L251: C114 is  open;
L252: ( Int C114 ) = C114 by L251 , TOPS_1:23;
consider C115 being  real number such that L253: (C115 > ( 0 ) & ( Ball (D38 , C115) ) c= C114) by L252 , L250 , GOBOARD6:4;
L254: (ex B196 being  open (Subset of R3) st (C113 in B196 & ( C109 .: B196 ) c= ( Ball (D38 , C115) ))) by L248 , L253;
thus L255: thesis by L254 , L253 , XBOOLE_1:1;
end;
thus L256: thesis by L249 , JGRAPH_2:10;
end;
theorem
L257: (for R3 being non  empty TopSpace holds (for R4 being non  empty MetrSpace holds (for B197 being (Function of ( TopSpaceMetr R4 ) , R3) holds (B197 is  continuous iff (for B198 being (Point of R4) holds (for B199 being  open (Subset of R3) holds (( B197 . B198 ) in B199 implies (ex B200 being  positive  real number st ( B197 .: ( Ball (B198 , B200) ) ) c= B199))))))))
proof
let R3 being non  empty TopSpace;
let R4 being non  empty MetrSpace;
let C116 being (Function of ( TopSpaceMetr R4 ) , R3);
thus L258:now
assume L259: C116 is  continuous;
let C117 being (Point of R4);
let C118 being  open (Subset of R3);
assume L260: ( C116 . C117 ) in C118;
consider C119 being (Subset of ( TopSpaceMetr R4 )) such that L261: C117 in C119 and L262: C119 is  open and L263: ( C116 .: C119 ) c= C118 by L260 , L259 , JGRAPH_2:10;
L264: ( Int C119 ) = C119 by L262 , TOPS_1:23;
consider C120 being  real number such that L265: C120 > ( 0 ) and L266: ( Ball (C117 , C120) ) c= C119 by L264 , L261 , GOBOARD6:4;
reconsider D39 = C120 as  positive  real number by L265;
take D40 = D39;
L267: ( C116 .: ( Ball (C117 , D40) ) ) c= ( C116 .: C119 ) by L266 , RELAT_1:123;
thus L268: ( C116 .: ( Ball (C117 , D40) ) ) c= C118 by L267 , L263 , XBOOLE_1:1;
end;
assume L269: (for B201 being (Point of R4) holds (for B202 being  open (Subset of R3) holds (( C116 . B201 ) in B202 implies (ex B203 being  positive  real number st ( C116 .: ( Ball (B201 , B203) ) ) c= B202))));
L270: (for B204 being (Point of ( TopSpaceMetr R4 )) holds (for B205 being (Subset of R3) holds ((( C116 . B204 ) in B205 & B205 is  open) implies (ex B206 being (Subset of ( TopSpaceMetr R4 )) st (B204 in B206 & B206 is  open & ( C116 .: B206 ) c= B205)))))
proof
let C121 being (Point of ( TopSpaceMetr R4 ));
let C122 being (Subset of R3);
assume that
L271: ( C116 . C121 ) in C122
and
L272: C122 is  open;
reconsider D41 = C121 as (Point of R4);
consider C123 being  positive  real number such that L273: ( C116 .: ( Ball (D41 , C123) ) ) c= C122 by L269 , L271 , L272;
reconsider D42 = ( Ball (D41 , C123) ) as (Subset of ( TopSpaceMetr R4 ));
take D42;
thus L274: C121 in D42 by GOBOARD6:1;
thus L275: D42 is  open by TOPMETR:14;
thus L276: thesis by L273;
end;
thus L277: thesis by L270 , JGRAPH_2:10;
end;
theorem
L278: (for R5 being non  empty MetrSpace holds (for R6 being non  empty MetrSpace holds (for B207 being (Function of ( TopSpaceMetr R5 ) , ( TopSpaceMetr R6 )) holds (B207 is  continuous iff (for B208 being (Point of R5) holds (for B209 being (Point of R6) holds (for B210 being  positive  real number holds (B209 = ( B207 . B208 ) implies (ex B211 being  positive  real number st ( B207 .: ( Ball (B208 , B211) ) ) c= ( Ball (B209 , B210) ))))))))))
proof
let R5 being non  empty MetrSpace;
let R6 being non  empty MetrSpace;
let C124 being (Function of ( TopSpaceMetr R5 ) , ( TopSpaceMetr R6 ));
thus L279:now
assume L280: C124 is  continuous;
let C125 being (Point of R5);
let C126 being (Point of R6);
let C127 being  positive  real number;
assume that
L281: C126 = ( C124 . C125 );
L282: C127 in ( REAL ) by XREAL_0:def 1;
consider C128 being (Element of ( REAL )) such that L283: C128 > ( 0 ) and L284: (for B212 being (Element of R5) holds (for B213 being (Element of R6) holds ((B213 = ( C124 . B212 ) & ( dist (C125 , B212) ) < C128) implies ( dist (C126 , B213) ) < C127))) by L282 , L280 , L281 , UNIFORM1:4;
reconsider D43 = C128 as  positive  real number by L283;
take D44 = D43;
thus L285: ( C124 .: ( Ball (C125 , D44) ) ) c= ( Ball (C126 , C127) )
proof
let C129 being set;
assume L286: C129 in ( C124 .: ( Ball (C125 , D44) ) );
consider C130 being (Point of ( TopSpaceMetr R5 )) such that L287: C130 in ( Ball (C125 , D44) ) and L288: ( C124 . C130 ) = C129 by L286 , FUNCT_2:65;
reconsider D45 = C130 as (Point of R5);
reconsider D46 = C129 as (Point of R6) by L288;
L289: ( dist (C125 , D45) ) < D44 by L287 , METRIC_1:11;
L290: ( dist (C126 , D46) ) < C127 by L289 , L288 , L284;
thus L291: C129 in ( Ball (C126 , C127) ) by L290 , METRIC_1:11;
end;

end;
assume L286: (for B214 being (Point of R5) holds (for B215 being (Point of R6) holds (for B216 being  positive  real number holds (B215 = ( C124 . B214 ) implies (ex B217 being  positive  real number st ( C124 .: ( Ball (B214 , B217) ) ) c= ( Ball (B215 , B216) ))))));
L287: (for B218 being  real number holds (for B219 being (Element of R5) holds (for B220 being (Element of R6) holds ((B218 > ( 0 ) & B220 = ( C124 . B219 )) implies (ex B221 being  real number st (B221 > ( 0 ) & (for B222 being (Element of R5) holds (for B223 being (Element of R6) holds ((B223 = ( C124 . B222 ) & ( dist (B219 , B222) ) < B221) implies ( dist (B220 , B223) ) < B218)))))))))
proof
let C131 being  real number;
let C132 being (Element of R5);
let C133 being (Element of R6);
assume L288: (C131 > ( 0 ) & C133 = ( C124 . C132 ));
consider C134 being  positive  real number such that L289: ( C124 .: ( Ball (C132 , C134) ) ) c= ( Ball (C133 , C131) ) by L288 , L286;
take C134;
thus L290: C134 > ( 0 );
let C135 being (Element of R5);
let C136 being (Element of R6);
assume that
L291: C136 = ( C124 . C135 );
assume L292: ( dist (C132 , C135) ) < C134;
L293: C135 in ( Ball (C132 , C134) ) by L292 , METRIC_1:11;
L294: ( C124 . C135 ) in ( C124 .: ( Ball (C132 , C134) ) ) by L293 , FUNCT_2:35;
thus L295: thesis by L294 , L289 , L291 , METRIC_1:11;
end;
thus L296: thesis by L287 , UNIFORM1:3;
end;
theorem
L297: (for R2 being Nat holds (for R3 being non  empty TopSpace holds (for B224 being (Function of R3 , ( TOP-REAL R2 )) holds (B224 is  continuous iff (for B225 being (Point of R3) holds (for B226 being  positive  real number holds (ex B227 being  open (Subset of R3) st (B225 in B227 & ( B224 .: B227 ) c= ( Ball (( B224 . B225 ) , B226) )))))))))
proof
let R2 being Nat;
let R3 being non  empty TopSpace;
let C137 being (Function of R3 , ( TOP-REAL R2 ));
L298: R2 in ( NAT ) by ORDINAL1:def 12;
thus L299: (C137 is  continuous implies (for B228 being (Point of R3) holds (for B229 being  positive  real number holds (ex B230 being  open (Subset of R3) st (B228 in B230 & ( C137 .: B230 ) c= ( Ball (( C137 . B228 ) , B229) ))))))
proof
assume L300: C137 is  continuous;
let C138 being (Point of R3);
let C139 being  positive  real number;
L301: ( C137 . C138 ) in ( Ball (( C137 . C138 ) , C139) ) by L298 , TOPGEN_5:13;
L302: (ex B231 being (Subset of R3) st (C138 in B231 & B231 is  open & ( C137 .: B231 ) c= ( Ball (( C137 . C138 ) , C139) ))) by L301 , L300 , JGRAPH_2:10;
thus L303: thesis by L302;
end;

assume L304: (for B232 being (Point of R3) holds (for B233 being  positive  real number holds (ex B234 being  open (Subset of R3) st (B232 in B234 & ( C137 .: B234 ) c= ( Ball (( C137 . B232 ) , B233) )))));
L305: (for B235 being (Point of R3) holds (for B236 being (Subset of ( TOP-REAL R2 )) holds ((( C137 . B235 ) in B236 & B236 is  open) implies (ex B237 being (Subset of R3) st (B235 in B237 & B237 is  open & ( C137 .: B237 ) c= B236)))))
proof
let C140 being (Point of R3);
let C141 being (Subset of ( TOP-REAL R2 ));
assume that
L306: ( C137 . C140 ) in C141;
reconsider D47 = ( C137 . C140 ) as (Point of ( Euclid R2 )) by EUCLID:67;
assume L307: C141 is  open;
L308: ( Int C141 ) = C141 by L307 , TOPS_1:23;
consider C142 being  real number such that L309: C142 > ( 0 ) and L310: ( Ball (D47 , C142) ) c= C141 by L308 , L306 , GOBOARD6:5;
L311: ( Ball (D47 , C142) ) = ( Ball (( C137 . C140 ) , C142) ) by L298 , TOPREAL9:13;
L312: (ex B238 being  open (Subset of R3) st (C140 in B238 & ( C137 .: B238 ) c= ( Ball (( C137 . C140 ) , C142) ))) by L304 , L309;
thus L313: thesis by L312 , L310 , L311 , XBOOLE_1:1;
end;
thus L314: thesis by L305 , JGRAPH_2:10;
end;
theorem
L315: (for R2 being Nat holds (for R3 being non  empty TopSpace holds (for B239 being (Function of ( TOP-REAL R2 ) , R3) holds (B239 is  continuous iff (for B240 being (Point of ( TOP-REAL R2 )) holds (for B241 being  open (Subset of R3) holds (( B239 . B240 ) in B241 implies (ex B242 being  positive  real number st ( B239 .: ( Ball (B240 , B242) ) ) c= B241))))))))
proof
let R2 being Nat;
let R3 being non  empty TopSpace;
let C143 being (Function of ( TOP-REAL R2 ) , R3);
L316: R2 in ( NAT ) by ORDINAL1:def 12;
thus L317:now
assume L318: C143 is  continuous;
let C144 being (Point of ( TOP-REAL R2 ));
let C145 being  open (Subset of R3);
assume L319: ( C143 . C144 ) in C145;
consider C146 being (Subset of ( TOP-REAL R2 )) such that L320: C144 in C146 and L321: C146 is  open and L322: ( C143 .: C146 ) c= C145 by L319 , L318 , JGRAPH_2:10;
reconsider D48 = C144 as (Point of ( Euclid R2 )) by EUCLID:67;
L323: ( Int C146 ) = C146 by L321 , TOPS_1:23;
consider C147 being  real number such that L324: C147 > ( 0 ) and L325: ( Ball (D48 , C147) ) c= C146 by L323 , L320 , GOBOARD6:5;
reconsider D49 = C147 as  positive  real number by L324;
take D50 = D49;
L326: ( Ball (D48 , D50) ) = ( Ball (C144 , D50) ) by L316 , TOPREAL9:13;
L327: ( C143 .: ( Ball (C144 , D50) ) ) c= ( C143 .: C146 ) by L326 , L325 , RELAT_1:123;
thus L328: ( C143 .: ( Ball (C144 , D50) ) ) c= C145 by L327 , L322 , XBOOLE_1:1;
end;
assume L329: (for B243 being (Point of ( TOP-REAL R2 )) holds (for B244 being  open (Subset of R3) holds (( C143 . B243 ) in B244 implies (ex B245 being  positive  real number st ( C143 .: ( Ball (B243 , B245) ) ) c= B244))));
L330: (for B246 being (Point of ( TOP-REAL R2 )) holds (for B247 being (Subset of R3) holds ((( C143 . B246 ) in B247 & B247 is  open) implies (ex B248 being (Subset of ( TOP-REAL R2 )) st (B246 in B248 & B248 is  open & ( C143 .: B248 ) c= B247)))))
proof
let C148 being (Point of ( TOP-REAL R2 ));
let C149 being (Subset of R3);
assume that
L331: ( C143 . C148 ) in C149
and
L332: C149 is  open;
consider C150 being  positive  real number such that L333: ( C143 .: ( Ball (C148 , C150) ) ) c= C149 by L329 , L331 , L332;
take D51 = ( Ball (C148 , C150) );
thus L334: C148 in D51 by L316 , TOPGEN_5:13;
thus L335: D51 is  open;
thus L336: thesis by L333;
end;
thus L337: thesis by L330 , JGRAPH_2:10;
end;
theorem
L338: (for R1 being Nat holds (for R2 being Nat holds (for B249 being (Function of ( TOP-REAL R2 ) , ( TOP-REAL R1 )) holds (B249 is  continuous iff (for B250 being (Point of ( TOP-REAL R2 )) holds (for B251 being  positive  real number holds (ex B252 being  positive  real number st ( B249 .: ( Ball (B250 , B252) ) ) c= ( Ball (( B249 . B250 ) , B251) ))))))))
proof
let R1 being Nat;
let R2 being Nat;
let C151 being (Function of ( TOP-REAL R2 ) , ( TOP-REAL R1 ));
L339: (( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) & ( the TopStruct of ( TOP-REAL R1 ) ) = ( TopSpaceMetr ( Euclid R1 ) )) by EUCLID:def 8;
reconsider D52 = C151 as (Function of ( TopSpaceMetr ( Euclid R2 ) ) , ( TopSpaceMetr ( Euclid R1 ) )) by L339;
L340: (R2 in ( NAT ) & R1 in ( NAT )) by ORDINAL1:def 12;
thus L341:now
assume L342: C151 is  continuous;
let C152 being (Point of ( TOP-REAL R2 ));
let C153 being  positive  real number;
reconsider D53 = C152 as (Point of ( Euclid R2 )) by EUCLID:67;
reconsider D54 = ( C151 . C152 ) as (Point of ( Euclid R1 )) by EUCLID:67;
L343: D52 is  continuous by L339 , L342 , YELLOW12:36;
consider C154 being  positive  real number such that L344: ( D52 .: ( Ball (D53 , C154) ) ) c= ( Ball (D54 , C153) ) by L343 , L278;
take D55 = C154;
L345: (( Ball (D53 , D55) ) = ( Ball (C152 , D55) ) & ( Ball (D54 , C153) ) = ( Ball (( C151 . C152 ) , C153) )) by L340 , TOPREAL9:13;
thus L346: ( C151 .: ( Ball (C152 , D55) ) ) c= ( Ball (( C151 . C152 ) , C153) ) by L345 , L344;
end;
assume L347: (for B253 being (Point of ( TOP-REAL R2 )) holds (for B254 being  positive  real number holds (ex B255 being  positive  real number st ( C151 .: ( Ball (B253 , B255) ) ) c= ( Ball (( C151 . B253 ) , B254) ))));
L348: (for B256 being (Point of ( Euclid R2 )) holds (for B257 being (Point of ( Euclid R1 )) holds (for B258 being  positive  real number holds (B257 = ( D52 . B256 ) implies (ex B259 being  positive  real number st ( D52 .: ( Ball (B256 , B259) ) ) c= ( Ball (B257 , B258) ))))))
proof
let C155 being (Point of ( Euclid R2 ));
let C156 being (Point of ( Euclid R1 ));
let C157 being  positive  real number;
assume that
L349: C156 = ( D52 . C155 );
reconsider D56 = C155 as (Point of ( TOP-REAL R2 )) by EUCLID:67;
consider C158 being  positive  real number such that L350: ( C151 .: ( Ball (D56 , C158) ) ) c= ( Ball (( C151 . D56 ) , C157) ) by L347;
take C158;
L351: (( Ball (D56 , C158) ) = ( Ball (C155 , C158) ) & ( Ball (( C151 . D56 ) , C157) ) = ( Ball (C156 , C157) )) by L340 , L349 , TOPREAL9:13;
thus L352: thesis by L351 , L350;
end;
L353: D52 is  continuous by L348 , L278;
thus L354: thesis by L353 , L339 , YELLOW12:36;
end;
theorem
L355: (for R3 being non  empty TopSpace holds (for B260 being (Function of R3 , ( R^1 )) holds (B260 is  continuous iff (for B261 being (Point of R3) holds (for B262 being  positive  real number holds (ex B263 being  open (Subset of R3) st (B261 in B263 & ( B260 .: B263 ) c= ]. ( ( B260 . B261 ) - B262 ) , ( ( B260 . B261 ) + B262 ) .[)))))))
proof
let R3 being non  empty TopSpace;
let C159 being (Function of R3 , ( R^1 ));
thus L356: (C159 is  continuous implies (for B264 being (Point of R3) holds (for B265 being  positive  real number holds (ex B266 being  open (Subset of R3) st (B264 in B266 & ( C159 .: B266 ) c= ]. ( ( C159 . B264 ) - B265 ) , ( ( C159 . B264 ) + B265 ) .[)))))
proof
assume L357: C159 is  continuous;
let C160 being (Point of R3);
let C161 being  positive  real number;
L358: ( C159 . C160 ) in ]. ( ( C159 . C160 ) - C161 ) , ( ( C159 . C160 ) + C161 ) .[ by TOPREAL6:15;
L359: ( R^1 ]. ( ( C159 . C160 ) - C161 ) , ( ( C159 . C160 ) + C161 ) .[ ) is  open;
L360: (ex B267 being (Subset of R3) st (C160 in B267 & B267 is  open & ( C159 .: B267 ) c= ]. ( ( C159 . C160 ) - C161 ) , ( ( C159 . C160 ) + C161 ) .[)) by L359 , L357 , L358 , JGRAPH_2:10;
thus L361: thesis by L360;
end;

assume L362: (for B268 being (Point of R3) holds (for B269 being  positive  real number holds (ex B270 being  open (Subset of R3) st (B268 in B270 & ( C159 .: B270 ) c= ]. ( ( C159 . B268 ) - B269 ) , ( ( C159 . B268 ) + B269 ) .[))));
L363: (for B271 being (Point of R3) holds (for B272 being (Subset of ( R^1 )) holds ((( C159 . B271 ) in B272 & B272 is  open) implies (ex B273 being (Subset of R3) st (B271 in B273 & B273 is  open & ( C159 .: B273 ) c= B272)))))
proof
let C162 being (Point of R3);
let C163 being (Subset of ( R^1 ));
assume that
L364: ( C159 . C162 ) in C163;
assume L365: C163 is  open;
consider C164 being (Element of ( REAL )) such that L366: C164 > ( 0 ) and L367: ]. ( ( C159 . C162 ) - C164 ) , ( ( C159 . C162 ) + C164 ) .[ c= C163 by L365 , L364 , FRECHET:8;
L368: (ex B274 being  open (Subset of R3) st (C162 in B274 & ( C159 .: B274 ) c= ]. ( ( C159 . C162 ) - C164 ) , ( ( C159 . C162 ) + C164 ) .[)) by L362 , L366;
thus L369: thesis by L368 , L367 , XBOOLE_1:1;
end;
thus L370: thesis by L363 , JGRAPH_2:10;
end;
theorem
L371: (for R3 being non  empty TopSpace holds (for B275 being (Function of ( R^1 ) , R3) holds (B275 is  continuous iff (for B276 being (Point of ( R^1 )) holds (for B277 being  open (Subset of R3) holds (( B275 . B276 ) in B277 implies (ex B278 being  positive  real number st ( B275 .: ]. ( B276 - B278 ) , ( B276 + B278 ) .[ ) c= B277)))))))
proof
let R3 being non  empty TopSpace;
let C165 being (Function of ( R^1 ) , R3);
thus L372:now
assume L373: C165 is  continuous;
let C166 being (Point of ( R^1 ));
let C167 being  open (Subset of R3);
assume L374: ( C165 . C166 ) in C167;
consider C168 being (Subset of ( R^1 )) such that L375: C166 in C168 and L376: C168 is  open and L377: ( C165 .: C168 ) c= C167 by L374 , L373 , JGRAPH_2:10;
consider C169 being (Element of ( REAL )) such that L378: C169 > ( 0 ) and L379: ]. ( C166 - C169 ) , ( C166 + C169 ) .[ c= C168 by L375 , L376 , FRECHET:8;
reconsider D57 = C169 as  positive  real number by L378;
take D58 = D57;
L380: ( C165 .: ]. ( C166 - D58 ) , ( C166 + D58 ) .[ ) c= ( C165 .: C168 ) by L379 , RELAT_1:123;
thus L381: ( C165 .: ]. ( C166 - D58 ) , ( C166 + D58 ) .[ ) c= C167 by L380 , L377 , XBOOLE_1:1;
end;
assume L382: (for B279 being (Point of ( R^1 )) holds (for B280 being  open (Subset of R3) holds (( C165 . B279 ) in B280 implies (ex B281 being  positive  real number st ( C165 .: ]. ( B279 - B281 ) , ( B279 + B281 ) .[ ) c= B280))));
L383: (for B282 being (Point of ( R^1 )) holds (for B283 being (Subset of R3) holds ((( C165 . B282 ) in B283 & B283 is  open) implies (ex B284 being (Subset of ( R^1 )) st (B282 in B284 & B284 is  open & ( C165 .: B284 ) c= B283)))))
proof
let C170 being (Point of ( R^1 ));
let C171 being (Subset of R3);
assume that
L384: ( C165 . C170 ) in C171
and
L385: C171 is  open;
consider C172 being  positive  real number such that L386: ( C165 .: ]. ( C170 - C172 ) , ( C170 + C172 ) .[ ) c= C171 by L382 , L384 , L385;
take D59 = ( R^1 ]. ( C170 - C172 ) , ( C170 + C172 ) .[ );
thus L387: C170 in D59 by TOPREAL6:15;
thus L388: D59 is  open;
thus L389: thesis by L386;
end;
thus L390: thesis by L383 , JGRAPH_2:10;
end;
theorem
L391: (for B285 being (Function of ( R^1 ) , ( R^1 )) holds (B285 is  continuous iff (for B286 being (Point of ( R^1 )) holds (for B287 being  positive  real number holds (ex B288 being  positive  real number st ( B285 .: ]. ( B286 - B288 ) , ( B286 + B288 ) .[ ) c= ]. ( ( B285 . B286 ) - B287 ) , ( ( B285 . B286 ) + B287 ) .[)))))
proof
let C173 being (Function of ( R^1 ) , ( R^1 ));
thus L392:now
assume L393: C173 is  continuous;
let C174 being (Point of ( R^1 ));
let C175 being  positive  real number;
reconsider D60 = C174 , D61 = ( C173 . C174 ) as (Point of ( RealSpace ));
consider C176 being  positive  real number such that L394: ( C173 .: ( Ball (D60 , C176) ) ) c= ( Ball (D61 , C175) ) by L393 , L278;
take D62 = C176;
L395: (D60 in ( REAL ) & D61 in ( REAL ) & C175 in ( REAL ) & D62 in ( REAL )) by XREAL_0:def 1;
L396: (( Ball (D60 , D62) ) = ]. ( D60 - D62 ) , ( D60 + D62 ) .[ & ( Ball (D61 , C175) ) = ]. ( D61 - C175 ) , ( D61 + C175 ) .[) by L395 , FRECHET:7;
thus L397: ( C173 .: ]. ( C174 - D62 ) , ( C174 + D62 ) .[ ) c= ]. ( ( C173 . C174 ) - C175 ) , ( ( C173 . C174 ) + C175 ) .[ by L396 , L394;
end;
assume L398: (for B289 being (Point of ( R^1 )) holds (for B290 being  positive  real number holds (ex B291 being  positive  real number st ( C173 .: ]. ( B289 - B291 ) , ( B289 + B291 ) .[ ) c= ]. ( ( C173 . B289 ) - B290 ) , ( ( C173 . B289 ) + B290 ) .[)));
L399: (for B292 , B293 being (Point of ( RealSpace )) holds (for B294 being  positive  real number holds (B293 = ( C173 . B292 ) implies (ex B295 being  positive  real number st ( C173 .: ( Ball (B292 , B295) ) ) c= ( Ball (B293 , B294) )))))
proof
let C177 , C178 being (Point of ( RealSpace ));
let C179 being  positive  real number;
assume that
L400: C178 = ( C173 . C177 );
consider C180 being  positive  real number such that L401: ( C173 .: ]. ( C177 - C180 ) , ( C177 + C180 ) .[ ) c= ]. ( ( C173 . C177 ) - C179 ) , ( ( C173 . C177 ) + C179 ) .[ by L398;
take C180;
L402: (C177 in ( REAL ) & C178 in ( REAL ) & C179 in ( REAL ) & C180 in ( REAL )) by XREAL_0:def 1;
L403: (( Ball (C177 , C180) ) = ]. ( C177 - C180 ) , ( C177 + C180 ) .[ & ( Ball (C178 , C179) ) = ]. ( C178 - C179 ) , ( C178 + C179 ) .[) by L402 , FRECHET:7;
thus L404: thesis by L403 , L401 , L400;
end;
thus L405: C173 is  continuous by L399 , L278;
end;
theorem
L406: (for R2 being Nat holds (for B296 being (Function of ( TOP-REAL R2 ) , ( R^1 )) holds (B296 is  continuous iff (for B297 being (Point of ( TOP-REAL R2 )) holds (for B298 being  positive  real number holds (ex B299 being  positive  real number st ( B296 .: ( Ball (B297 , B299) ) ) c= ]. ( ( B296 . B297 ) - B298 ) , ( ( B296 . B297 ) + B298 ) .[))))))
proof
let R2 being Nat;
let C181 being (Function of ( TOP-REAL R2 ) , ( R^1 ));
L407: ( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) by EUCLID:def 8;
reconsider D63 = C181 as (Function of ( TopSpaceMetr ( Euclid R2 ) ) , ( R^1 )) by L407;
L408: R2 in ( NAT ) by ORDINAL1:def 12;
thus L409:now
assume L410: C181 is  continuous;
let C182 being (Point of ( TOP-REAL R2 ));
let C183 being  positive  real number;
reconsider D64 = C182 as (Point of ( Euclid R2 )) by EUCLID:67;
reconsider D65 = ( C181 . C182 ) as (Point of ( RealSpace ));
L411: D63 is  continuous by L407 , L410 , YELLOW12:36;
consider C184 being  positive  real number such that L412: ( C181 .: ( Ball (D64 , C184) ) ) c= ( Ball (D65 , C183) ) by L411 , L407 , L278;
take D66 = C184;
L413: (D65 in ( REAL ) & C183 in ( REAL )) by XREAL_0:def 1;
L414: (( Ball (D64 , D66) ) = ( Ball (C182 , D66) ) & ( Ball (D65 , C183) ) = ]. ( ( C181 . C182 ) - C183 ) , ( ( C181 . C182 ) + C183 ) .[) by L413 , L408 , FRECHET:7 , TOPREAL9:13;
thus L415: ( C181 .: ( Ball (C182 , D66) ) ) c= ]. ( ( C181 . C182 ) - C183 ) , ( ( C181 . C182 ) + C183 ) .[ by L414 , L412;
end;
assume L416: (for B300 being (Point of ( TOP-REAL R2 )) holds (for B301 being  positive  real number holds (ex B302 being  positive  real number st ( C181 .: ( Ball (B300 , B302) ) ) c= ]. ( ( C181 . B300 ) - B301 ) , ( ( C181 . B300 ) + B301 ) .[)));
L417: (for B303 being (Point of ( Euclid R2 )) holds (for B304 being (Point of ( RealSpace )) holds (for B305 being  positive  real number holds (B304 = ( D63 . B303 ) implies (ex B306 being  positive  real number st ( D63 .: ( Ball (B303 , B306) ) ) c= ( Ball (B304 , B305) ))))))
proof
let C185 being (Point of ( Euclid R2 ));
let C186 being (Point of ( RealSpace ));
let C187 being  positive  real number;
assume that
L418: C186 = ( D63 . C185 );
reconsider D67 = C185 as (Point of ( TOP-REAL R2 )) by EUCLID:67;
consider C188 being  positive  real number such that L419: ( C181 .: ( Ball (D67 , C188) ) ) c= ]. ( ( C181 . C185 ) - C187 ) , ( ( C181 . C185 ) + C187 ) .[ by L416;
take C188;
L420: (C186 in ( REAL ) & C187 in ( REAL )) by XREAL_0:def 1;
L421: (( Ball (D67 , C188) ) = ( Ball (C185 , C188) ) & ]. ( ( C181 . C185 ) - C187 ) , ( ( C181 . C185 ) + C187 ) .[ = ( Ball (C186 , C187) )) by L420 , L408 , L418 , FRECHET:7 , TOPREAL9:13;
thus L422: thesis by L421 , L419;
end;
L423: D63 is  continuous by L417 , L278;
thus L424: thesis by L423 , L407 , YELLOW12:36;
end;
theorem
L425: (for R2 being Nat holds (for B307 being (Function of ( R^1 ) , ( TOP-REAL R2 )) holds (B307 is  continuous iff (for B308 being (Point of ( R^1 )) holds (for B309 being  positive  real number holds (ex B310 being  positive  real number st ( B307 .: ]. ( B308 - B310 ) , ( B308 + B310 ) .[ ) c= ( Ball (( B307 . B308 ) , B309) )))))))
proof
let R2 being Nat;
let C189 being (Function of ( R^1 ) , ( TOP-REAL R2 ));
L426: ( the TopStruct of ( TOP-REAL R2 ) ) = ( TopSpaceMetr ( Euclid R2 ) ) by EUCLID:def 8;
reconsider D68 = C189 as (Function of ( R^1 ) , ( TopSpaceMetr ( Euclid R2 ) )) by L426;
L427: R2 in ( NAT ) by ORDINAL1:def 12;
thus L428:now
assume L429: C189 is  continuous;
let C190 being (Point of ( R^1 ));
let C191 being  positive  real number;
reconsider D69 = C190 as (Point of ( RealSpace ));
reconsider D70 = ( C189 . C190 ) as (Point of ( Euclid R2 )) by EUCLID:67;
L430: D68 is  continuous by L426 , L429 , YELLOW12:36;
consider C192 being  positive  real number such that L431: ( D68 .: ( Ball (D69 , C192) ) ) c= ( Ball (D70 , C191) ) by L430 , L278;
take D71 = C192;
L432: (C190 in ( REAL ) & D71 in ( REAL )) by XREAL_0:def 1;
L433: (( Ball (D69 , D71) ) = ]. ( C190 - D71 ) , ( C190 + D71 ) .[ & ( Ball (D70 , C191) ) = ( Ball (( C189 . C190 ) , C191) )) by L432 , L427 , FRECHET:7 , TOPREAL9:13;
thus L434: ( C189 .: ]. ( C190 - D71 ) , ( C190 + D71 ) .[ ) c= ( Ball (( C189 . C190 ) , C191) ) by L433 , L431;
end;
assume L435: (for B311 being (Point of ( R^1 )) holds (for B312 being  positive  real number holds (ex B313 being  positive  real number st ( C189 .: ]. ( B311 - B313 ) , ( B311 + B313 ) .[ ) c= ( Ball (( C189 . B311 ) , B312) ))));
L436: (for B314 being (Point of ( RealSpace )) holds (for B315 being (Point of ( Euclid R2 )) holds (for B316 being  positive  real number holds (B315 = ( C189 . B314 ) implies (ex B317 being  positive  real number st ( C189 .: ( Ball (B314 , B317) ) ) c= ( Ball (B315 , B316) ))))))
proof
let C193 being (Point of ( RealSpace ));
let C194 being (Point of ( Euclid R2 ));
let C195 being  positive  real number;
assume that
L437: C194 = ( C189 . C193 );
reconsider D72 = C193 as (Point of ( R^1 ));
consider C196 being  positive  real number such that L438: ( C189 .: ]. ( C193 - C196 ) , ( C193 + C196 ) .[ ) c= ( Ball (( C189 . D72 ) , C195) ) by L435;
take C196;
L439: (C193 in ( REAL ) & C196 in ( REAL )) by XREAL_0:def 1;
L440: (]. ( C193 - C196 ) , ( C193 + C196 ) .[ = ( Ball (C193 , C196) ) & ( Ball (( C189 . D72 ) , C195) ) = ( Ball (C194 , C195) )) by L439 , L427 , L437 , FRECHET:7 , TOPREAL9:13;
thus L441: thesis by L440 , L438;
end;
L442: D68 is  continuous by L436 , L426 , L278;
thus L443: thesis by L442 , L426 , YELLOW12:36;
end;
