:: Meet-continuous Lattices
::  by Artur Korni{\l}owicz
::
:: Received October 10, 1996
:: Copyright (c) 1996-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies XBOOLE_0, FUNCT_1, SUBSET_1, RELAT_1, RELAT_2, LATTICE3,
      ORDERS_2, XXREAL_0, TREES_2, WAYBEL_0, YELLOW_0, LATTICES, EQREL_1,
      ORDINAL2, ZFMISC_1, TARSKI, STRUCT_0, MCART_1, SEQM_3, REWRITE1,
      FINSET_1, WELLORD1, CAT_1, YELLOW_2, FINSUB_1, WELLORD2, YELLOW_1,
      CARD_FIL, LATTICE2, WAYBEL_1, WAYBEL_2, CARD_1;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, FINSUB_1, RELAT_1, FUNCT_1,
      RELSET_1, TOLER_1, FINSET_1, PARTFUN1, BINOP_1, FUNCT_2, DOMAIN_1,
      STRUCT_0, ORDERS_2, ORDERS_3, LATTICE3, YELLOW_0, WAYBEL_0, YELLOW_1,
      YELLOW_2, WAYBEL_1, YELLOW_3, YELLOW_4;
 constructors DOMAIN_1, FINSUB_1, TOLER_1, ORDERS_3, WAYBEL_1, YELLOW_3,
      YELLOW_4, RELSET_1;
 registrations XBOOLE_0, SUBSET_1, RELAT_1, FUNCT_1, FUNCT_2, FINSET_1,
      FINSUB_1, STRUCT_0, LATTICE3, YELLOW_0, WAYBEL_0, YELLOW_1, YELLOW_2,
      WAYBEL_1, YELLOW_3, YELLOW_4, CARD_1, ORDINAL1, ORDERS_2, RELSET_1,
      XTUPLE_0;
 requirements SUBSET, BOOLE, NUMERALS;
 definitions WAYBEL_1, YELLOW_0, LATTICE3, ORDERS_3, TARSKI, WAYBEL_0,
      XBOOLE_0, WELLORD1, BINOP_1, RELAT_1, STRUCT_0;
 theorems FINSUB_1, FUNCT_1, FUNCT_2, LATTICE3, MCART_1, ORDERS_2, ORDERS_3,
      RELAT_1, STRUCT_0, TARSKI, WAYBEL_0, YELLOW_0, ZFMISC_1, YELLOW_1,
      YELLOW_2, WAYBEL_1, YELLOW_3, YELLOW_4, XBOOLE_1, RELSET_1, XTUPLE_0;
 schemes FINSET_1, YELLOW_3, FUNCT_2;

begin
registration
let C1 , C2 being non  empty set;
let C3 being (Function of C1 , C2);
let C4 being non  empty (Subset of C1);
cluster ( C3 .: C4 ) -> non  empty;
coherence
proof
set D1 = the (Element of C4);
L1: ( dom C3 ) = C1 by FUNCT_2:def 1;
thus L2: thesis by L1;
end;
end;
registration
cluster  reflexive  connected ->  with_infima  with_suprema for non  empty non  empty non  empty non  empty RelStr;
coherence
proof
let C5 being non  empty RelStr;
assume that
L4: C5 is  reflexive  connected;
thus L5: C5 is  with_infima
proof
let C6 , C7 being (Element of C5);
per cases  by L4 , WAYBEL_0:def 29;
suppose L6: C6 <= C7;

take D2 = C6;
thus L7: (D2 <= C6 & D2 <= C7) by L4 , L6 , YELLOW_0:def 1;
thus L8: thesis;
end;
suppose L9: C7 <= C6;

take D3 = C7;
thus L10: (D3 <= C6 & D3 <= C7) by L4 , L9 , YELLOW_0:def 1;
thus L11: thesis;
end;
end;

let C8 , C9 being (Element of C5);
per cases  by L4 , WAYBEL_0:def 29;
suppose L13: C8 <= C9;

take D4 = C9;
thus L14: (D4 >= C8 & D4 >= C9) by L4 , L13 , YELLOW_0:def 1;
thus L15: thesis;
end;
suppose L16: C9 <= C8;

take D5 = C8;
thus L17: (D5 >= C8 & D5 >= C9) by L4 , L16 , YELLOW_0:def 1;
thus L18: thesis;
end;
end;
end;
registration
let C10 being Chain;
cluster ( [#] C10 ) ->  directed;
coherence;
end;
theorem
L22: (for B1 being  up-complete Semilattice holds (for B2 being non  empty  directed (Subset of B1) holds (for B3 being (Element of B1) holds  ex_sup_of ( { B3 } "/\" B2 ) , B1)))
proof
let C11 being  up-complete Semilattice;
let C12 being non  empty  directed (Subset of C11);
let C13 being (Element of C11);
reconsider D6 = { C13 } as non  empty  directed (Subset of C11) by WAYBEL_0:5;
L23:  ex_sup_of ( D6 "/\" C12 ) , C11 by WAYBEL_0:75;
thus L24: thesis by L23;
end;
theorem
L25: (for B4 being  up-complete sup-Semilattice holds (for B5 being non  empty  directed (Subset of B4) holds (for B6 being (Element of B4) holds  ex_sup_of ( { B6 } "\/" B5 ) , B4)))
proof
let C14 being  up-complete sup-Semilattice;
let C15 being non  empty  directed (Subset of C14);
let C16 being (Element of C14);
reconsider D7 = { C16 } as non  empty  directed (Subset of C14) by WAYBEL_0:5;
L26:  ex_sup_of ( D7 "\/" C15 ) , C14 by WAYBEL_0:75;
thus L27: thesis by L26;
end;
theorem
L28: (for B7 being  up-complete sup-Semilattice holds (for B8 , B9 being non  empty  directed (Subset of B7) holds B8 is_<=_than ( sup ( B8 "\/" B9 ) )))
proof
let C17 being  up-complete sup-Semilattice;
let C18 , C19 being non  empty  directed (Subset of C17);
L29: ( C18 "\/" C19 ) = { ( B10 "\/" B11 ) where B10 , B11 is (Element of C17) : (B10 in C18 & B11 in C19) } by YELLOW_4:def 3;
set D8 = the (Element of C19);
let C20 being (Element of C17);
assume L30: C20 in C18;
L31: ( C20 "\/" D8 ) in ( C18 "\/" C19 ) by L30 , L29;
L32: (ex B12 being (Element of C17) st (C20 <= B12 & D8 <= B12 & (for B13 being (Element of C17) holds ((C20 <= B13 & D8 <= B13) implies B12 <= B13)))) by LATTICE3:def 10;
L33: C20 <= ( C20 "\/" D8 ) by L32 , LATTICE3:def 13;
L34:  ex_sup_of ( C18 "\/" C19 ) , C17 by WAYBEL_0:75;
L35: ( C18 "\/" C19 ) is_<=_than ( sup ( C18 "\/" C19 ) ) by L34 , YELLOW_0:def 9;
L36: ( C20 "\/" D8 ) <= ( sup ( C18 "\/" C19 ) ) by L35 , L31 , LATTICE3:def 9;
thus L37: C20 <= ( sup ( C18 "\/" C19 ) ) by L36 , L33 , YELLOW_0:def 2;
end;
theorem
L38: (for B14 being  up-complete sup-Semilattice holds (for B15 , B16 being non  empty  directed (Subset of B14) holds ( sup ( B15 "\/" B16 ) ) = ( ( sup B15 ) "\/" ( sup B16 ) )))
proof
let C21 being  up-complete sup-Semilattice;
let C22 , C23 being non  empty  directed (Subset of C21);
L39:  ex_sup_of C23 , C21 by WAYBEL_0:75;
L40: C23 is_<=_than ( sup C23 ) by L39 , YELLOW_0:30;
L41:  ex_sup_of C22 , C21 by WAYBEL_0:75;
L42: C22 is_<=_than ( sup C22 ) by L41 , YELLOW_0:30;
L43: ( ex_sup_of ( C22 "\/" C23 ) , C21 & ( C22 "\/" C23 ) is_<=_than ( ( sup C22 ) "\/" ( sup C23 ) )) by L42 , L40 , WAYBEL_0:75 , YELLOW_4:27;
L44: ( sup ( C22 "\/" C23 ) ) <= ( ( sup C22 ) "\/" ( sup C23 ) ) by L43 , YELLOW_0:def 9;
L45: C23 is_<=_than ( sup ( C22 "\/" C23 ) ) by L28;
L46: ( sup C23 ) <= ( sup ( C22 "\/" C23 ) ) by L45 , L39 , YELLOW_0:30;
L47: C22 is_<=_than ( sup ( C22 "\/" C23 ) ) by L28;
L48: ( sup C22 ) <= ( sup ( C22 "\/" C23 ) ) by L47 , L41 , YELLOW_0:30;
L49: ( ( sup C22 ) "\/" ( sup C23 ) ) <= ( ( sup ( C22 "\/" C23 ) ) "\/" ( sup ( C22 "\/" C23 ) ) ) by L48 , L46 , YELLOW_3:3;
L50: ( sup ( C22 "\/" C23 ) ) <= ( sup ( C22 "\/" C23 ) );
L51: ( ( sup ( C22 "\/" C23 ) ) "\/" ( sup ( C22 "\/" C23 ) ) ) = ( sup ( C22 "\/" C23 ) ) by L50 , YELLOW_0:24;
thus L52: thesis by L51 , L44 , L49 , ORDERS_2:2;
end;
theorem
L53: (for B17 being  up-complete Semilattice holds (for B18 being non  empty  directed (Subset of [: B17 , B17 :]) holds { ( sup ( { B19 } "/\" ( proj2 B18 ) ) ) where B19 is (Element of B17) : B19 in ( proj1 B18 ) } = { ( sup B20 ) where B20 is non  empty  directed (Subset of B17) : (ex B21 being (Element of B17) st (B20 = ( { B21 } "/\" ( proj2 B18 ) ) & B21 in ( proj1 B18 ))) }))
proof
let C24 being  up-complete Semilattice;
let C25 being non  empty  directed (Subset of [: C24 , C24 :]);
defpred S1[ set ] means (ex B22 being (Element of C24) st ($1 = ( { B22 } "/\" ( proj2 C25 ) ) & B22 in ( proj1 C25 )));
reconsider D9 = ( proj1 C25 ) , D10 = ( proj2 C25 ) as non  empty  directed (Subset of C24) by YELLOW_3:21 , YELLOW_3:22;
thus L54: { ( sup ( { B23 } "/\" ( proj2 C25 ) ) ) where B23 is (Element of C24) : B23 in ( proj1 C25 ) } c= { ( sup B24 ) where B24 is non  empty  directed (Subset of C24) : S1[ B24 ] }
proof
let C26 being set;
assume L55: C26 in { ( sup ( { B25 } "/\" ( proj2 C25 ) ) ) where B25 is (Element of C24) : B25 in ( proj1 C25 ) };
consider C27 being (Element of C24) such that L56: (C26 = ( sup ( { C27 } "/\" D10 ) ) & C27 in D9) by L55;
reconsider D11 = { C27 } as non  empty  directed (Subset of C24) by WAYBEL_0:5;
L57: ( D11 "/\" D10 ) is non  empty  directed;
thus L58: thesis by L57 , L56;
end;

let C28 being set;
assume L59: C28 in { ( sup B26 ) where B26 is non  empty  directed (Subset of C24) : S1[ B26 ] };
L60: (ex B27 being non  empty  directed (Subset of C24) st (C28 = ( sup B27 ) & S1[ B27 ])) by L59;
thus L61: thesis by L60;
end;
theorem
L62: (for B28 being Semilattice holds (for B29 being non  empty  directed (Subset of [: B28 , B28 :]) holds ( union { B30 where B30 is non  empty  directed (Subset of B28) : (ex B31 being (Element of B28) st (B30 = ( { B31 } "/\" ( proj2 B29 ) ) & B31 in ( proj1 B29 ))) } ) = ( ( proj1 B29 ) "/\" ( proj2 B29 ) )))
proof
let C29 being Semilattice;
let C30 being non  empty  directed (Subset of [: C29 , C29 :]);
set D12 = ( proj1 C30 );
set D13 = ( proj2 C30 );
defpred S2[ set ] means (ex B32 being (Element of C29) st ($1 = ( { B32 } "/\" ( proj2 C30 ) ) & B32 in ( proj1 C30 )));
reconsider D14 = D13 as non  empty  directed (Subset of C29) by YELLOW_3:21 , YELLOW_3:22;
L63: ( D12 "/\" D13 ) = { ( B33 "/\" B34 ) where B33 , B34 is (Element of C29) : (B33 in D12 & B34 in D13) } by YELLOW_4:def 4;
thus L64: ( union { B35 where B35 is non  empty  directed (Subset of C29) : S2[ B35 ] } ) c= ( D12 "/\" D13 )
proof
let C31 being set;
assume L65: C31 in ( union { B36 where B36 is non  empty  directed (Subset of C29) : S2[ B36 ] } );
consider C32 being set such that L66: C31 in C32 and L67: C32 in { B37 where B37 is non  empty  directed (Subset of C29) : S2[ B37 ] } by L65 , TARSKI:def 4;
consider C33 being non  empty  directed (Subset of C29) such that L68: C32 = C33 and L69: S2[ C33 ] by L67;
consider C34 being (Element of C29) such that L70: C33 = ( { C34 } "/\" D13 ) and L71: C34 in D12 by L69;
L72: ( { C34 } "/\" D13 ) = { ( C34 "/\" B38 ) where B38 is (Element of C29) : B38 in D13 } by YELLOW_4:42;
L73: (ex B39 being (Element of C29) st (C31 = ( C34 "/\" B39 ) & B39 in D13)) by L72 , L66 , L68 , L70;
thus L74: thesis by L73 , L63 , L71;
end;

let C35 being set;
assume L75: C35 in ( D12 "/\" D13 );
consider C36 , C37 being (Element of C29) such that L76: C35 = ( C36 "/\" C37 ) and L77: C36 in D12 and L78: C37 in D13 by L75 , L63;
reconsider D15 = { C36 } as non  empty  directed (Subset of C29) by WAYBEL_0:5;
L79: ( D15 "/\" D14 ) is non  empty  directed;
L80: ( { C36 } "/\" D13 ) in { B40 where B40 is non  empty  directed (Subset of C29) : S2[ B40 ] } by L79 , L77;
L81: ( { C36 } "/\" D13 ) = { ( C36 "/\" B41 ) where B41 is (Element of C29) : B41 in D13 } by YELLOW_4:42;
L82: C35 in ( { C36 } "/\" D13 ) by L81 , L76 , L78;
thus L83: thesis by L82 , L80 , TARSKI:def 4;
end;
theorem
L84: (for B42 being  up-complete Semilattice holds (for B43 being non  empty  directed (Subset of [: B42 , B42 :]) holds  ex_sup_of ( union { B44 where B44 is non  empty  directed (Subset of B42) : (ex B45 being (Element of B42) st (B44 = ( { B45 } "/\" ( proj2 B43 ) ) & B45 in ( proj1 B43 ))) } ) , B42))
proof
let C38 being  up-complete Semilattice;
let C39 being non  empty  directed (Subset of [: C38 , C38 :]);
reconsider D16 = ( proj1 C39 ) , D17 = ( proj2 C39 ) as non  empty  directed (Subset of C38) by YELLOW_3:21 , YELLOW_3:22;
set D18 = { B46 where B46 is non  empty  directed (Subset of C38) : (ex B47 being (Element of C38) st (B46 = ( { B47 } "/\" D17 ) & B47 in D16)) };
L85: ( union D18 ) c= (the carrier of C38)
proof
let C40 being set;
assume L86: C40 in ( union D18 );
consider C41 being set such that L87: C40 in C41 and L88: C41 in D18 by L86 , TARSKI:def 4;
L89: (ex B48 being non  empty  directed (Subset of C38) st (C41 = B48 & (ex B49 being (Element of C38) st (B48 = ( { B49 } "/\" D17 ) & B49 in D16)))) by L88;
thus L90: thesis by L89 , L87;
end;
reconsider D19 = ( union D18 ) as (Subset of C38) by L85;
L91: D19 = ( D16 "/\" D17 ) by L62;
thus L92: thesis by L91 , WAYBEL_0:75;
end;
theorem
L93: (for B50 being  up-complete Semilattice holds (for B51 being non  empty  directed (Subset of [: B50 , B50 :]) holds  ex_sup_of { ( sup B52 ) where B52 is non  empty  directed (Subset of B50) : (ex B53 being (Element of B50) st (B52 = ( { B53 } "/\" ( proj2 B51 ) ) & B53 in ( proj1 B51 ))) } , B50))
proof
let C42 being  up-complete Semilattice;
let C43 being non  empty  directed (Subset of [: C42 , C42 :]);
reconsider D20 = ( proj1 C43 ) , D21 = ( proj2 C43 ) as non  empty  directed (Subset of C42) by YELLOW_3:21 , YELLOW_3:22;
defpred S3[ set ] means (ex B54 being (Element of C42) st ($1 = ( { B54 } "/\" D21 ) & B54 in D20));
set D22 = { ( sup B55 ) where B55 is non  empty  directed (Subset of C42) : S3[ B55 ] };
L94: D22 c= (the carrier of C42)
proof
let C44 being set;
assume L95: C44 in D22;
L96: (ex B56 being non  empty  directed (Subset of C42) st (C44 = ( sup B56 ) & S3[ B56 ])) by L95;
thus L97: thesis by L96;
end;
reconsider D23 = D22 as (Subset of C42) by L94;
set D24 = { B57 where B57 is non  empty  directed (Subset of C42) : S3[ B57 ] };
L98: ( union D24 ) c= (the carrier of C42)
proof
let C45 being set;
assume L99: C45 in ( union D24 );
consider C46 being set such that L100: C45 in C46 and L101: C46 in D24 by L99 , TARSKI:def 4;
L102: (ex B58 being non  empty  directed (Subset of C42) st (C46 = B58 & (ex B59 being (Element of C42) st (B58 = ( { B59 } "/\" D21 ) & B59 in D20)))) by L101;
thus L103: thesis by L102 , L100;
end;
reconsider D25 = ( union D24 ) as (Subset of C42) by L98;
set D26 = ( sup D25 );
L104:  ex_sup_of D25 , C42 by L84;
L105: (for B60 being (Element of C42) holds (D23 is_<=_than B60 implies D26 <= B60))
proof
let C47 being (Element of C42);
assume that
L106: D23 is_<=_than C47;
L107: D25 is_<=_than C47
proof
let C48 being (Element of C42);
assume L108: C48 in D25;
consider C49 being set such that L109: C48 in C49 and L110: C49 in D24 by L108 , TARSKI:def 4;
consider C50 being non  empty  directed (Subset of C42) such that L111: C49 = C50 and L112: S3[ C50 ] by L110;
consider C51 being (Element of C42) such that L113: C50 = ( { C51 } "/\" D21 ) and L114: C51 in D20 by L112;
L115: ( { C51 } "/\" D21 ) = { ( C51 "/\" B61 ) where B61 is (Element of C42) : B61 in D21 } by YELLOW_4:42;
L116: ( sup C50 ) in D23 by L112;
L117: ( sup C50 ) <= C47 by L116 , L106 , LATTICE3:def 9;
consider C52 being (Element of C42) such that L118: C48 = ( C51 "/\" C52 ) and L119: C52 in D21 by L109 , L111 , L113 , L115;
L120: ( C51 "/\" C52 ) <= ( sup C50 ) by L109 , L111 , L113 , L118 , L22 , YELLOW_4:1;
thus L121: C48 <= C47 by L120 , L118 , L117 , YELLOW_0:def 2;
end;
thus L122: thesis by L107 , L104 , YELLOW_0:def 9;
end;
L123: D23 is_<=_than D26
proof
let C53 being (Element of C42);
assume L124: C53 in D23;
consider C54 being non  empty  directed (Subset of C42) such that L125: C53 = ( sup C54 ) and L126: S3[ C54 ] by L124;
L127: ( ex_sup_of C54 , C42 & C54 in D24) by L126 , WAYBEL_0:75;
thus L128: C53 <= D26 by L127 , L104 , L125 , YELLOW_0:34 , ZFMISC_1:74;
end;
thus L129: thesis by L123 , L105 , YELLOW_0:15;
end;
theorem
L130: (for B62 being  up-complete Semilattice holds (for B63 being non  empty  directed (Subset of [: B62 , B62 :]) holds ( "\/" ({ ( sup B64 ) where B64 is non  empty  directed (Subset of B62) : (ex B65 being (Element of B62) st (B64 = ( { B65 } "/\" ( proj2 B63 ) ) & B65 in ( proj1 B63 ))) } , B62) ) <= ( "\/" (( union { B66 where B66 is non  empty  directed (Subset of B62) : (ex B67 being (Element of B62) st (B66 = ( { B67 } "/\" ( proj2 B63 ) ) & B67 in ( proj1 B63 ))) } ) , B62) )))
proof
let C55 being  up-complete Semilattice;
let C56 being non  empty  directed (Subset of [: C55 , C55 :]);
defpred S4[ set ] means (ex B68 being (Element of C55) st ($1 = ( { B68 } "/\" ( proj2 C56 ) ) & B68 in ( proj1 C56 )));
L131: ( "\/" (( union { B69 where B69 is non  empty  directed (Subset of C55) : S4[ B69 ] } ) , C55) ) is_>=_than { ( sup B70 ) where B70 is non  empty  directed (Subset of C55) : S4[ B70 ] }
proof
let C57 being (Element of C55);
assume L132: C57 in { ( sup B71 ) where B71 is non  empty  directed (Subset of C55) : S4[ B71 ] };
consider C58 being non  empty  directed (Subset of C55) such that L133: C57 = ( sup C58 ) and L134: S4[ C58 ] by L132;
L135: C58 in { B72 where B72 is non  empty  directed (Subset of C55) : S4[ B72 ] } by L134;
L136: ( ex_sup_of C58 , C55 &  ex_sup_of ( union { B73 where B73 is non  empty  directed (Subset of C55) : S4[ B73 ] } ) , C55) by L84 , WAYBEL_0:75;
thus L137: C57 <= ( "\/" (( union { B74 where B74 is non  empty  directed (Subset of C55) : S4[ B74 ] } ) , C55) ) by L136 , L133 , L135 , YELLOW_0:34 , ZFMISC_1:74;
end;
L138:  ex_sup_of { ( sup B75 ) where B75 is non  empty  directed (Subset of C55) : S4[ B75 ] } , C55 by L93;
thus L139: thesis by L138 , L131 , YELLOW_0:def 9;
end;
theorem
L140: (for B76 being  up-complete Semilattice holds (for B77 being non  empty  directed (Subset of [: B76 , B76 :]) holds ( "\/" ({ ( sup B78 ) where B78 is non  empty  directed (Subset of B76) : (ex B79 being (Element of B76) st (B78 = ( { B79 } "/\" ( proj2 B77 ) ) & B79 in ( proj1 B77 ))) } , B76) ) = ( "\/" (( union { B80 where B80 is non  empty  directed (Subset of B76) : (ex B81 being (Element of B76) st (B80 = ( { B81 } "/\" ( proj2 B77 ) ) & B81 in ( proj1 B77 ))) } ) , B76) )))
proof
let C59 being  up-complete Semilattice;
let C60 being non  empty  directed (Subset of [: C59 , C59 :]);
defpred S5[ set ] means (ex B82 being (Element of C59) st ($1 = ( { B82 } "/\" ( proj2 C60 ) ) & B82 in ( proj1 C60 )));
L141: ( "\/" ({ ( sup B83 ) where B83 is non  empty  directed (Subset of C59) : S5[ B83 ] } , C59) ) <= ( "\/" (( union { B84 where B84 is non  empty  directed (Subset of C59) : S5[ B84 ] } ) , C59) ) by L130;
L142: ( union { B85 where B85 is non  empty  directed (Subset of C59) : S5[ B85 ] } ) is_<=_than ( "\/" ({ ( "\/" (B86 , C59) ) where B86 is non  empty  directed (Subset of C59) : S5[ B86 ] } , C59) )
proof
let C61 being (Element of C59);
assume L143: C61 in ( union { B87 where B87 is non  empty  directed (Subset of C59) : S5[ B87 ] } );
consider C62 being set such that L144: C61 in C62 and L145: C62 in { B88 where B88 is non  empty  directed (Subset of C59) : S5[ B88 ] } by L143 , TARSKI:def 4;
consider C63 being non  empty  directed (Subset of C59) such that L146: C62 = C63 and L147: S5[ C63 ] by L145;
L148: ( "\/" (C63 , C59) ) in { ( "\/" (B89 , C59) ) where B89 is non  empty  directed (Subset of C59) : S5[ B89 ] } by L147;
L149: ( "\/" (C63 , C59) ) <= ( "\/" ({ ( "\/" (B90 , C59) ) where B90 is non  empty  directed (Subset of C59) : S5[ B90 ] } , C59) ) by L148 , L93 , YELLOW_4:1;
L150:  ex_sup_of C63 , C59 by WAYBEL_0:75;
L151: C61 <= ( "\/" (C63 , C59) ) by L150 , L144 , L146 , YELLOW_4:1;
thus L152: C61 <= ( "\/" ({ ( "\/" (B91 , C59) ) where B91 is non  empty  directed (Subset of C59) : S5[ B91 ] } , C59) ) by L151 , L149 , YELLOW_0:def 2;
end;
L153:  ex_sup_of ( union { B92 where B92 is non  empty  directed (Subset of C59) : S5[ B92 ] } ) , C59 by L84;
L154: ( "\/" (( union { B93 where B93 is non  empty  directed (Subset of C59) : S5[ B93 ] } ) , C59) ) <= ( "\/" ({ ( "\/" (B94 , C59) ) where B94 is non  empty  directed (Subset of C59) : S5[ B94 ] } , C59) ) by L153 , L142 , YELLOW_0:def 9;
thus L155: thesis by L154 , L141 , ORDERS_2:2;
end;
registration
let C64 , C65 being  up-complete non  empty  reflexive RelStr;
cluster [: C64 , C65 :] ->  up-complete;
coherence
proof
let C66 being non  empty  directed (Subset of [: C64 , C65 :]);
reconsider D27 = ( proj1 C66 ) as non  empty  directed (Subset of C64) by YELLOW_3:21 , YELLOW_3:22;
reconsider D28 = ( proj2 C66 ) as non  empty  directed (Subset of C65) by YELLOW_3:21 , YELLOW_3:22;
consider C67 being (Element of C64) such that L156: C67 is_>=_than D27 and L157: (for B95 being (Element of C64) holds (B95 is_>=_than D27 implies C67 <= B95)) by WAYBEL_0:def 39;
consider C68 being (Element of C65) such that L158: C68 is_>=_than D28 and L159: (for B96 being (Element of C65) holds (B96 is_>=_than D28 implies C68 <= B96)) by WAYBEL_0:def 39;
take [ C67 , C68 ];
thus L160: [ C67 , C68 ] is_>=_than C66 by L156 , L158 , YELLOW_3:31;
let C69 being (Element of [: C64 , C65 :]);
assume that
L161: C69 is_>=_than C66;
L162: (the carrier of [: C64 , C65 :]) = [: (the carrier of C64) , (the carrier of C65) :] by YELLOW_3:def 2;
L163: C69 = [ ( C69 `1 ) , ( C69 `2 ) ] by L162 , MCART_1:21;
L164: ( C69 `2 ) is_>=_than D28 by L163 , L161 , YELLOW_3:31;
L165: C68 <= ( C69 `2 ) by L164 , L159;
L166: ( C69 `1 ) is_>=_than D27 by L161 , L163 , YELLOW_3:31;
L167: C67 <= ( C69 `1 ) by L166 , L157;
thus L168: thesis by L167 , L163 , L165 , YELLOW_3:11;
end;
end;
theorem
L170: (for B97 , B98 being non  empty  reflexive  antisymmetric RelStr holds ([: B97 , B98 :] is  up-complete implies (B97 is  up-complete & B98 is  up-complete)))
proof
let C70 , C71 being non  empty  reflexive  antisymmetric RelStr;
assume that
L171: [: C70 , C71 :] is  up-complete;
thus L172: C70 is  up-complete
proof
set D29 = the non  empty  directed (Subset of C71);
let C72 being non  empty  directed (Subset of C70);
consider C73 being (Element of [: C70 , C71 :]) such that L173: C73 is_>=_than [: C72 , D29 :] and L174: (for B99 being (Element of [: C70 , C71 :]) holds (B99 is_>=_than [: C72 , D29 :] implies C73 <= B99)) by L171 , WAYBEL_0:def 39;
take ( C73 `1 );
L175: (the carrier of [: C70 , C71 :]) = [: (the carrier of C70) , (the carrier of C71) :] by YELLOW_3:def 2;
L176: C73 = [ ( C73 `1 ) , ( C73 `2 ) ] by L175 , MCART_1:21;
thus L177: ( C73 `1 ) is_>=_than C72 by L176 , L173 , YELLOW_3:29;
L178:  ex_sup_of [: C72 , D29 :] , [: C70 , C71 :] by L171 , WAYBEL_0:75;
L179:  ex_sup_of D29 , C71 by L178 , YELLOW_3:39;
L180: ( sup D29 ) is_>=_than D29 by L179 , YELLOW_0:def 9;
let C74 being (Element of C70);
assume L181: C74 is_>=_than C72;
L182: C73 <= [ C74 , ( sup D29 ) ] by L181 , L174 , L180 , YELLOW_3:30;
thus L183: thesis by L182 , L176 , YELLOW_3:11;
end;

set D30 = the non  empty  directed (Subset of C70);
let C75 being non  empty  directed (Subset of C71);
consider C76 being (Element of [: C70 , C71 :]) such that L184: C76 is_>=_than [: D30 , C75 :] and L185: (for B100 being (Element of [: C70 , C71 :]) holds (B100 is_>=_than [: D30 , C75 :] implies C76 <= B100)) by L171 , WAYBEL_0:def 39;
L186:  ex_sup_of [: D30 , C75 :] , [: C70 , C71 :] by L171 , WAYBEL_0:75;
L187:  ex_sup_of D30 , C70 by L186 , YELLOW_3:39;
L188: ( sup D30 ) is_>=_than D30 by L187 , YELLOW_0:def 9;
take ( C76 `2 );
L189: (the carrier of [: C70 , C71 :]) = [: (the carrier of C70) , (the carrier of C71) :] by YELLOW_3:def 2;
L190: C76 = [ ( C76 `1 ) , ( C76 `2 ) ] by L189 , MCART_1:21;
thus L191: ( C76 `2 ) is_>=_than C75 by L190 , L184 , YELLOW_3:29;
let C77 being (Element of C71);
assume L192: C77 is_>=_than C75;
L193: C76 <= [ ( sup D30 ) , C77 ] by L192 , L185 , L188 , YELLOW_3:30;
thus L194: thesis by L193 , L190 , YELLOW_3:11;
end;
theorem
L195: (for B101 being  up-complete  antisymmetric non  empty  reflexive RelStr holds (for B102 being non  empty  directed (Subset of [: B101 , B101 :]) holds ( sup B102 ) = [ ( sup ( proj1 B102 ) ) , ( sup ( proj2 B102 ) ) ]))
proof
let C78 being  up-complete  antisymmetric non  empty  reflexive RelStr;
let C79 being non  empty  directed (Subset of [: C78 , C78 :]);
reconsider D31 = ( proj1 C79 ) , D32 = ( proj2 C79 ) as non  empty  directed (Subset of C78) by YELLOW_3:21 , YELLOW_3:22;
reconsider D33 = (the carrier of C78) as non  empty set;
reconsider D34 = C79 as non  empty (Subset of [: D33 , D33 :]) by YELLOW_3:def 2;
L196:  ex_sup_of D31 , C78 by WAYBEL_0:75;
L197: (the carrier of [: C78 , C78 :]) = [: D33 , D33 :] by YELLOW_3:def 2;
consider C80 , C81 being set such that L198: (C80 in D33 & C81 in D33) and L199: ( sup C79 ) = [ C80 , C81 ] by L197 , ZFMISC_1:def 2;
L200:  ex_sup_of D32 , C78 by WAYBEL_0:75;
reconsider D35 = C80 , D36 = C81 as (Element of C78) by L198;
L201:  ex_sup_of C79 , [: C78 , C78 :] by WAYBEL_0:75;
L202: D32 is_<=_than D36
proof
let C82 being (Element of C78);
assume L203: C82 in D32;
consider C83 being set such that L204: [ C83 , C82 ] in C79 by L203 , XTUPLE_0:def 13;
reconsider D37 = C83 as (Element of D31) by L204 , XTUPLE_0:def 12;
L205: C79 is_<=_than [ D35 , D36 ] by L201 , L199 , YELLOW_0:def 9;
L206: [ D37 , C82 ] <= [ D35 , D36 ] by L205 , L204 , LATTICE3:def 9;
thus L207: C82 <= D36 by L206 , YELLOW_3:11;
end;
L208: ( sup D32 ) <= D36 by L202 , L200 , YELLOW_0:def 9;
L209: D31 is_<=_than D35
proof
let C84 being (Element of C78);
assume L210: C84 in D31;
consider C85 being set such that L211: [ C84 , C85 ] in C79 by L210 , XTUPLE_0:def 12;
reconsider D38 = C85 as (Element of D32) by L211 , XTUPLE_0:def 13;
L212: C79 is_<=_than [ D35 , D36 ] by L201 , L199 , YELLOW_0:def 9;
L213: [ C84 , D38 ] <= [ D35 , D36 ] by L212 , L211 , LATTICE3:def 9;
thus L214: C84 <= D35 by L213 , YELLOW_3:11;
end;
L215: ( sup D31 ) <= D35 by L209 , L196 , YELLOW_0:def 9;
L216: [ ( sup D31 ) , ( sup D32 ) ] <= ( sup C79 ) by L215 , L199 , L208 , YELLOW_3:11;
L217:  ex_sup_of [: D31 , D32 :] , [: C78 , C78 :] by WAYBEL_0:75;
reconsider D39 = D31 , D40 = D32 as non  empty (Subset of C78);
L218: D34 c= [: D39 , D40 :] by YELLOW_3:1;
L219: ( sup C79 ) <= ( sup [: D39 , D40 :] ) by L218 , L201 , L217 , YELLOW_0:34;
L220: ( sup C79 ) <= [ ( sup ( proj1 C79 ) ) , ( sup ( proj2 C79 ) ) ] by L219 , L196 , L200 , YELLOW_3:43;
thus L221: thesis by L220 , L216 , ORDERS_2:2;
end;
theorem
L222: (for B103 , B104 being RelStr holds (for B105 being (Subset of B103) holds (for B106 being (Function of B103 , B104) holds (B106 is  monotone implies ( B106 .: ( downarrow B105 ) ) c= ( downarrow ( B106 .: B105 ) )))))
proof
let C86 , C87 being RelStr;
let C88 being (Subset of C86);
let C89 being (Function of C86 , C87);
assume that
L223: C89 is  monotone;
let C90 being set;
assume L224: C90 in ( C89 .: ( downarrow C88 ) );
consider C91 being set such that L225: C91 in ( dom C89 ) and L226: C91 in ( downarrow C88 ) and L227: C90 = ( C89 . C91 ) by L224 , FUNCT_1:def 6;
reconsider D41 = C86 , D42 = C87 as non  empty RelStr by L224;
reconsider D43 = C91 as (Element of D41) by L225;
consider C92 being (Element of D41) such that L228: D43 <= C92 and L229: C92 in C88 by L226 , WAYBEL_0:def 15;
reconsider D44 = C89 as (Function of D41 , D42);
L230: ( D44 . D43 ) is (Element of D42);
reconsider D45 = C90 , D46 = ( D44 . C92 ) as (Element of D42) by L230 , L227;
L231: (the carrier of D42) <> ( {} );
L232: ( dom C89 ) = (the carrier of D41) by L231 , FUNCT_2:def 1;
L233: ( C89 . C92 ) in ( C89 .: C88 ) by L232 , L229 , FUNCT_1:def 6;
L234: D45 <= D46 by L223 , L227 , L228 , ORDERS_3:def 5;
thus L235: thesis by L234 , L233 , WAYBEL_0:def 15;
end;
theorem
L236: (for B107 , B108 being RelStr holds (for B109 being (Subset of B107) holds (for B110 being (Function of B107 , B108) holds (B110 is  monotone implies ( B110 .: ( uparrow B109 ) ) c= ( uparrow ( B110 .: B109 ) )))))
proof
let C93 , C94 being RelStr;
let C95 being (Subset of C93);
let C96 being (Function of C93 , C94);
assume that
L237: C96 is  monotone;
let C97 being set;
assume L238: C97 in ( C96 .: ( uparrow C95 ) );
consider C98 being set such that L239: C98 in ( dom C96 ) and L240: C98 in ( uparrow C95 ) and L241: C97 = ( C96 . C98 ) by L238 , FUNCT_1:def 6;
reconsider D47 = C93 , D48 = C94 as non  empty RelStr by L238;
reconsider D49 = C98 as (Element of D47) by L239;
consider C99 being (Element of D47) such that L242: C99 <= D49 and L243: C99 in C95 by L240 , WAYBEL_0:def 16;
reconsider D50 = C96 as (Function of D47 , D48);
L244: ( D50 . D49 ) is (Element of D48);
reconsider D51 = C97 , D52 = ( D50 . C99 ) as (Element of D48) by L244 , L241;
L245: (the carrier of D48) <> ( {} );
L246: ( dom C96 ) = (the carrier of D47) by L245 , FUNCT_2:def 1;
L247: ( C96 . C99 ) in ( C96 .: C95 ) by L246 , L243 , FUNCT_1:def 6;
L248: D52 <= D51 by L237 , L241 , L242 , ORDERS_3:def 5;
thus L249: thesis by L248 , L247 , WAYBEL_0:def 16;
end;
registration
cluster  ->  distributive  complemented for 1 -element  reflexive 1 -element  reflexive 1 -element  reflexive 1 -element  reflexive RelStr;
coherence
proof
let C100 being 1 -element  reflexive RelStr;
thus L250: C100 is  distributive
proof
let C101 , C102 , C103 being (Element of C100);
thus L251: thesis by STRUCT_0:def 10;
end;

let C104 being (Element of C100);
take D53 = C104;
thus L252: ( C104 "\/" D53 ) = ( Top C100 ) by STRUCT_0:def 10;
thus L253: thesis by STRUCT_0:def 10;
end;
end;
registration
cluster  strict 1 -element for LATTICE;
existence
proof
set D54 = the  strict 1 -element  reflexive RelStr;
take D54;
thus L255: thesis;
end;
end;
theorem
L257: (for B111 being  distributive  complete LATTICE holds (for B112 being (Element of B111) holds (for B113 being  finite (Subset of B111) holds ( sup ( { B112 } "/\" B113 ) ) = ( B112 "/\" ( sup B113 ) ))))
proof
let C105 being  distributive  complete LATTICE;
let C106 being (Element of C105);
let C107 being  finite (Subset of C105);
defpred S6[ set ] means (ex B114 being (Subset of C105) st (B114 = $1 & ( C106 "/\" ( sup B114 ) ) = ( sup ( { C106 } "/\" B114 ) )));
L258: S6[ ( {} ) ]
proof
reconsider D55 = ( {} ) as (Subset of C105) by XBOOLE_1:2;
take D55;
thus L259: D55 = ( {} );
L260: (( Bottom C105 ) <= C106 & ( { C106 } "/\" ( {} C105 ) ) = ( {} )) by YELLOW_0:44 , YELLOW_4:36;
thus L261: thesis by L260 , YELLOW_0:25;
end;
L262: (for B115 , B116 being set holds ((B115 in C107 & B116 c= C107 & S6[ B116 ]) implies S6[ ( B116 \/ { B115 } ) ]))
proof
let C108 , C109 being set;
assume that
L263: C108 in C107
and
L264: C109 c= C107
and
L265: S6[ C109 ];
reconsider D56 = C108 as (Element of C105) by L263;
L266: { D56 } c= (the carrier of C105);
L267: C109 c= (the carrier of C105) by L264 , XBOOLE_1:1;
reconsider D57 = ( C109 \/ { C108 } ) as (Subset of C105) by L267 , L266 , XBOOLE_1:8;
take D57;
thus L268: D57 = ( C109 \/ { C108 } );
consider C110 being (Subset of C105) such that L269: C110 = C109 and L270: ( C106 "/\" ( sup C110 ) ) = ( sup ( { C106 } "/\" C110 ) ) by L265;
L271: ( { C106 } "/\" D57 ) = ( ( { C106 } "/\" C110 ) \/ ( { C106 } "/\" { D56 } ) ) by L269 , YELLOW_4:43
.= ( ( { C106 } "/\" C110 ) \/ { ( C106 "/\" D56 ) } ) by YELLOW_4:46;
L272: ( ex_sup_of ( { C106 } "/\" C110 ) , C105 &  ex_sup_of { ( C106 "/\" D56 ) } , C105) by YELLOW_0:17;
L273: ( ex_sup_of C109 , C105 &  ex_sup_of { C108 } , C105) by YELLOW_0:17;
thus L274: ( C106 "/\" ( sup D57 ) ) = ( C106 "/\" ( ( "\/" (C109 , C105) ) "\/" ( "\/" ({ C108 } , C105) ) ) ) by L273 , YELLOW_2:3
.= ( ( sup ( { C106 } "/\" C110 ) ) "\/" ( C106 "/\" ( "\/" ({ C108 } , C105) ) ) ) by L269 , L270 , WAYBEL_1:def 3
.= ( ( sup ( { C106 } "/\" C110 ) ) "\/" ( C106 "/\" D56 ) ) by YELLOW_0:39
.= ( ( sup ( { C106 } "/\" C110 ) ) "\/" ( sup { ( C106 "/\" D56 ) } ) ) by YELLOW_0:39
.= ( sup ( { C106 } "/\" D57 ) ) by L272 , L271 , YELLOW_2:3;
end;
L275: C107 is  finite;
L276: S6[ C107 ] from FINSET_1:sch 2(L275 , L258 , L262);
thus L277: thesis by L276;
end;
theorem
L278: (for B117 being  distributive  complete LATTICE holds (for B118 being (Element of B117) holds (for B119 being  finite (Subset of B117) holds ( inf ( { B118 } "\/" B119 ) ) = ( B118 "\/" ( inf B119 ) ))))
proof
let C111 being  distributive  complete LATTICE;
let C112 being (Element of C111);
let C113 being  finite (Subset of C111);
defpred S7[ set ] means (ex B120 being (Subset of C111) st (B120 = $1 & ( C112 "\/" ( inf B120 ) ) = ( inf ( { C112 } "\/" B120 ) )));
L279: S7[ ( {} ) ]
proof
reconsider D58 = ( {} ) as (Subset of C111) by XBOOLE_1:2;
take D58;
thus L280: D58 = ( {} );
L281: (C112 <= ( Top C111 ) & ( { C112 } "\/" ( {} C111 ) ) = ( {} )) by YELLOW_0:45 , YELLOW_4:9;
thus L282: thesis by L281 , YELLOW_0:24;
end;
L283: (for B121 , B122 being set holds ((B121 in C113 & B122 c= C113 & S7[ B122 ]) implies S7[ ( B122 \/ { B121 } ) ]))
proof
let C114 , C115 being set;
assume that
L284: C114 in C113
and
L285: C115 c= C113
and
L286: S7[ C115 ];
reconsider D59 = C114 as (Element of C111) by L284;
L287: { D59 } c= (the carrier of C111);
L288: C115 c= (the carrier of C111) by L285 , XBOOLE_1:1;
reconsider D60 = ( C115 \/ { C114 } ) as (Subset of C111) by L288 , L287 , XBOOLE_1:8;
take D60;
thus L289: D60 = ( C115 \/ { C114 } );
consider C116 being (Subset of C111) such that L290: C116 = C115 and L291: ( C112 "\/" ( inf C116 ) ) = ( inf ( { C112 } "\/" C116 ) ) by L286;
L292: ( { C112 } "\/" D60 ) = ( ( { C112 } "\/" C116 ) \/ ( { C112 } "\/" { D59 } ) ) by L290 , YELLOW_4:16
.= ( ( { C112 } "\/" C116 ) \/ { ( C112 "\/" D59 ) } ) by YELLOW_4:19;
L293: ( ex_inf_of ( { C112 } "\/" C116 ) , C111 &  ex_inf_of { ( C112 "\/" D59 ) } , C111) by YELLOW_0:17;
L294: ( ex_inf_of C115 , C111 &  ex_inf_of { C114 } , C111) by YELLOW_0:17;
thus L295: ( C112 "\/" ( inf D60 ) ) = ( C112 "\/" ( ( "/\" (C115 , C111) ) "/\" ( "/\" ({ C114 } , C111) ) ) ) by L294 , YELLOW_2:4
.= ( ( inf ( { C112 } "\/" C116 ) ) "/\" ( C112 "\/" ( "/\" ({ C114 } , C111) ) ) ) by L290 , L291 , WAYBEL_1:5
.= ( ( inf ( { C112 } "\/" C116 ) ) "/\" ( C112 "\/" D59 ) ) by YELLOW_0:39
.= ( ( inf ( { C112 } "\/" C116 ) ) "/\" ( inf { ( C112 "\/" D59 ) } ) ) by YELLOW_0:39
.= ( inf ( { C112 } "\/" D60 ) ) by L293 , L292 , YELLOW_2:4;
end;
L296: C113 is  finite;
L297: S7[ C113 ] from FINSET_1:sch 2(L296 , L279 , L283);
thus L298: thesis by L297;
end;
theorem
L299: (for B123 being  complete  distributive LATTICE holds (for B124 being (Element of B123) holds (for B125 being  finite (Subset of B123) holds ( B124 "/\" ) preserves_sup_of B125)))
proof
let C117 being  complete  distributive LATTICE;
let C118 being (Element of C117);
let C119 being  finite (Subset of C117);
assume L300:  ex_sup_of C119 , C117;
thus L301:  ex_sup_of ( ( C118 "/\" ) .: C119 ) , C117 by YELLOW_0:17;
thus L302: ( sup ( ( C118 "/\" ) .: C119 ) ) = ( "\/" ({ ( C118 "/\" B126 ) where B126 is (Element of C117) : B126 in C119 } , C117) ) by WAYBEL_1:61
.= ( sup ( { C118 } "/\" C119 ) ) by YELLOW_4:42
.= ( C118 "/\" ( sup C119 ) ) by L257
.= ( ( C118 "/\" ) . ( sup C119 ) ) by WAYBEL_1:def 18;
end;
begin
scheme ExNet { F1() -> non  empty RelStr , F2() -> (prenet of F1()) , F3(set) -> (Element of F1()) } : (ex B127 being (prenet of F1()) st (( the RelStr of B127 ) = ( the RelStr of F2() ) & (for B128 being (Element of B127) holds ( (the mapping of B127) . B128 ) = F3(( (the mapping of F2()) . B128 )))))
proof
deffunc H1((Element of F2())) = F3(( (the mapping of F2()) . $1 ));
L303: (for B129 being (Element of F2()) holds H1(B129) in (the carrier of F1()));
consider C120 being (Function of (the carrier of F2()) , (the carrier of F1())) such that L304: (for B130 being (Element of F2()) holds ( C120 . B130 ) = H1(B130)) from FUNCT_2:sch 8(L303);
set D61 = NetStr (# (the carrier of F2()) , (the InternalRel of F2()) , C120 #);
L305: (( the RelStr of D61 ) = ( the RelStr of F2() ) & ( [#] F2() ) is  directed) by WAYBEL_0:def 6;
L306: ( [#] D61 ) is  directed by L305 , WAYBEL_0:3;
reconsider D62 = D61 as (prenet of F1()) by L306 , WAYBEL_0:def 6;
take D62;
thus L307: thesis by L304;
end;
theorem
L308: (for B131 being non  empty RelStr holds (for B132 being (prenet of B131) holds (B132 is  eventually-directed implies ( rng ( netmap (B132 , B131) ) ) is  directed)))
proof
let C121 being non  empty RelStr;
let C122 being (prenet of C121);
assume that
L309: C122 is  eventually-directed;
set D63 = ( netmap (C122 , C121) );
let C123 , C124 being (Element of C121);
assume that
L310: C123 in ( rng D63 )
and
L311: C124 in ( rng D63 );
consider C125 being set such that L312: C125 in ( dom D63 ) and L313: ( D63 . C125 ) = C123 by L310 , FUNCT_1:def 3;
consider C126 being set such that L314: C126 in ( dom D63 ) and L315: ( D63 . C126 ) = C124 by L311 , FUNCT_1:def 3;
reconsider D64 = C125 , D65 = C126 as (Element of C122) by L312 , L314;
consider C127 being (Element of C122) such that L316: (for B133 being (Element of C122) holds (C127 <= B133 implies ( C122 . D64 ) <= ( C122 . B133 ))) by L309 , WAYBEL_0:11;
consider C128 being (Element of C122) such that L317: (for B134 being (Element of C122) holds (C128 <= B134 implies ( C122 . D65 ) <= ( C122 . B134 ))) by L309 , WAYBEL_0:11;
L318: ( [#] C122 ) is  directed by WAYBEL_0:def 6;
consider C129 being (Element of C122) such that L319: C129 in ( [#] C122 ) and L320: (C127 <= C129 & C128 <= C129) by L318 , WAYBEL_0:def 1;
take D66 = ( D63 . C129 );
L321: ( dom D63 ) = (the carrier of C122) by FUNCT_2:def 1;
thus L322: D66 in ( rng D63 ) by L321 , FUNCT_1:def 3;
L323: ( C122 . C129 ) = ( D63 . C129 );
thus L324: thesis by L323 , L313 , L315 , L316 , L317 , L320;
end;
theorem
L325: (for B135 being non  empty  reflexive RelStr holds (for B136 being non  empty  directed (Subset of B135) holds (for B137 being (Function of B136 , (the carrier of B135)) holds NetStr (# B136 , ( (the InternalRel of B135) |_2 B136 ) , B137 #) is (prenet of B135))))
proof
let C130 being non  empty  reflexive RelStr;
let C131 being non  empty  directed (Subset of C130);
let C132 being (Function of C131 , (the carrier of C130));
set D67 = NetStr (# C131 , ( (the InternalRel of C130) |_2 C131 ) , C132 #);
L326: D67 is  directed
proof
let C133 , C134 being (Element of D67);
assume that
L327: C133 in ( [#] D67 )
and
L328: C134 in ( [#] D67 );
reconsider D68 = C133 , D69 = C134 as (Element of C131);
consider C135 being (Element of C130) such that L329: C135 in C131 and L330: (D68 <= C135 & D69 <= C135) by WAYBEL_0:def 1;
reconsider D70 = C135 as (Element of D67) by L329;
take D70;
thus L331: D70 in ( [#] D67 );
L332: (the InternalRel of D67) c= (the InternalRel of C130) by XBOOLE_1:17;
reconsider D71 = D67 as (SubRelStr of C130) by L332 , YELLOW_0:def 13;
L333: D71 is  full by YELLOW_0:def 14;
thus L334: thesis by L333 , L330 , YELLOW_0:60;
end;
thus L335: thesis by L326;
end;
theorem
L336: (for B138 being non  empty  reflexive RelStr holds (for B139 being non  empty  directed (Subset of B138) holds (for B140 being (Function of B139 , (the carrier of B138)) holds (for B141 being (prenet of B138) holds ((B140 = ( id B139 ) & B141 = NetStr (# B139 , ( (the InternalRel of B138) |_2 B139 ) , B140 #)) implies B141 is  eventually-directed)))))
proof
let C136 being non  empty  reflexive RelStr;
let C137 being non  empty  directed (Subset of C136);
let C138 being (Function of C137 , (the carrier of C136));
let C139 being (prenet of C136);
assume that
L337: C138 = ( id C137 )
and
L338: C139 = NetStr (# C137 , ( (the InternalRel of C136) |_2 C137 ) , C138 #);
L339: (for B142 being (Element of C139) holds (ex B143 being (Element of C139) st (for B144 being (Element of C139) holds (B143 <= B144 implies ( C139 . B142 ) <= ( C139 . B144 )))))
proof
let C140 being (Element of C139);
take D72 = C140;
let C141 being (Element of C139);
assume that
L340: D72 <= C141;
L341: (the InternalRel of C139) c= (the InternalRel of C136) by L338 , XBOOLE_1:17;
L342: C139 is (SubRelStr of C136) by L341 , L338 , YELLOW_0:def 13;
reconsider D73 = ( C138 . D72 ) , D74 = ( C138 . C141 ) as (Element of C136) by L338 , FUNCT_2:5;
L343: (D73 = D72 & D74 = C141) by L337 , L338 , FUNCT_1:18;
thus L344: thesis by L343 , L338 , L340 , L342 , YELLOW_0:59;
end;
thus L345: thesis by L339 , WAYBEL_0:11;
end;
definition
let C142 being non  empty RelStr;
let C143 being NetStr over C142;
func sup C143 -> (Element of C142) equals 
( Sup (the mapping of C143) );
coherence;
end;
definition
let C144 being non  empty RelStr;
let C145 being set;
let C146 being (Function of C145 , (the carrier of C144));
func FinSups C146 -> (prenet of C144) means 
:L347: (ex B145 being (Function of ( Fin C145 ) , (the carrier of C144)) st (for B146 being (Element of ( Fin C145 )) holds (( B145 . B146 ) = ( sup ( C146 .: B146 ) ) & it = NetStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) , B145 #))));
existence
proof
deffunc H2((Element of ( Fin C145 ))) = ( sup ( C146 .: $1 ) );
L348: (for B147 being (Element of ( Fin C145 )) holds H2(B147) in (the carrier of C144));
consider C147 being (Function of ( Fin C145 ) , (the carrier of C144)) such that L349: (for B148 being (Element of ( Fin C145 )) holds ( C147 . B148 ) = H2(B148)) from FUNCT_2:sch 8(L348);
set D75 = NetStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) , C147 #);
L350: D75 is  directed
proof
let C148 , C149 being (Element of D75);
assume that
L351: C148 in ( [#] D75 )
and
L352: C149 in ( [#] D75 );
reconsider D76 = C148 , D77 = C149 as (Element of ( Fin C145 ));
reconsider D78 = ( D76 \/ D77 ) as (Element of D75);
take D78;
thus L353: D78 in ( [#] D75 );
L354: ( InclPoset ( Fin C145 ) ) = RelStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) #) by YELLOW_1:def 1;
reconsider D79 = C148 , D80 = C149 , D81 = D78 as (Element of ( InclPoset ( Fin C145 ) )) by L354;
L355: C149 c= D78 by XBOOLE_1:7;
L356: D80 <= D81 by L355 , YELLOW_1:3;
L357: C148 c= D78 by XBOOLE_1:7;
L358: D79 <= D81 by L357 , YELLOW_1:3;
thus L359: thesis by L358 , L354 , L356 , YELLOW_0:1;
end;
reconsider D82 = D75 as (prenet of C144) by L350;
take D82;
thus L360: thesis by L349;
end;
uniqueness
proof
let C150 , C151 being (prenet of C144);
assume that
L361: (ex B149 being (Function of ( Fin C145 ) , (the carrier of C144)) st (for B150 being (Element of ( Fin C145 )) holds (( B149 . B150 ) = ( sup ( C146 .: B150 ) ) & C150 = NetStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) , B149 #))))
and
L362: (ex B151 being (Function of ( Fin C145 ) , (the carrier of C144)) st (for B152 being (Element of ( Fin C145 )) holds (( B151 . B152 ) = ( sup ( C146 .: B152 ) ) & C151 = NetStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) , B151 #))));
consider C152 being (Function of ( Fin C145 ) , (the carrier of C144)) such that L363: (for B153 being (Element of ( Fin C145 )) holds (( C152 . B153 ) = ( sup ( C146 .: B153 ) ) & C150 = NetStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) , C152 #))) by L361;
consider C153 being (Function of ( Fin C145 ) , (the carrier of C144)) such that L364: (for B154 being (Element of ( Fin C145 )) holds (( C153 . B154 ) = ( sup ( C146 .: B154 ) ) & C151 = NetStr (# ( Fin C145 ) , ( RelIncl ( Fin C145 ) ) , C153 #))) by L362;
L365: (for B155 being set holds (B155 in ( Fin C145 ) implies ( C152 . B155 ) = ( C153 . B155 )))
proof
let C154 being set;
assume L366: C154 in ( Fin C145 );
thus L367: ( C152 . C154 ) = ( sup ( C146 .: C154 ) ) by L366 , L363
.= ( C153 . C154 ) by L364 , L366;
end;
thus L368: thesis by L365 , L363 , L364 , FUNCT_2:12;
end;
end;
theorem
L370: (for B156 being non  empty RelStr holds (for B157 , B158 being set holds (for B159 being (Function of B157 , (the carrier of B156)) holds (B158 is (Element of ( FinSups B159 )) iff B158 is (Element of ( Fin B157 ))))))
proof
let C155 being non  empty RelStr;
let C156 , C157 being set;
let C158 being (Function of C156 , (the carrier of C155));
L371: (ex B160 being (Function of ( Fin C156 ) , (the carrier of C155)) st (for B161 being (Element of ( Fin C156 )) holds (( B160 . B161 ) = ( sup ( C158 .: B161 ) ) & ( FinSups C158 ) = NetStr (# ( Fin C156 ) , ( RelIncl ( Fin C156 ) ) , B160 #)))) by L347;
thus L372: thesis by L371;
end;
registration
let C159 being  complete  antisymmetric non  empty  reflexive RelStr;
let C160 being set;
let C161 being (Function of C160 , (the carrier of C159));
cluster ( FinSups C161 ) ->  monotone;
coherence
proof
let C162 , C163 being (Element of ( FinSups C161 ));
assume that
L373: C162 <= C163;
consider C164 being (Function of ( Fin C160 ) , (the carrier of C159)) such that L374: (for B162 being (Element of ( Fin C160 )) holds (( C164 . B162 ) = ( sup ( C161 .: B162 ) ) & ( FinSups C161 ) = NetStr (# ( Fin C160 ) , ( RelIncl ( Fin C160 ) ) , C164 #))) by L347;
L375: ( C164 . C162 ) = ( sup ( C161 .: C162 ) ) by L374;
reconsider D83 = ( C164 . C162 ) as (Element of C159) by L375;
L376: ( InclPoset ( Fin C160 ) ) = RelStr (# ( Fin C160 ) , ( RelIncl ( Fin C160 ) ) #) by YELLOW_1:def 1;
reconsider D84 = C162 , D85 = C163 as (Element of ( InclPoset ( Fin C160 ) )) by L376 , L374;
L377: ( ex_sup_of ( C161 .: C162 ) , C159 &  ex_sup_of ( C161 .: C163 ) , C159) by YELLOW_0:17;
L378: D84 <= D85 by L373 , L374 , L376 , YELLOW_0:1;
L379: C162 c= C163 by L378 , YELLOW_1:3;
L380: ( sup ( C161 .: C162 ) ) <= ( sup ( C161 .: C163 ) ) by L379 , L377 , RELAT_1:123 , YELLOW_0:34;
L381: D83 <= ( sup ( C161 .: C163 ) ) by L380 , L374;
let C165 , C166 being (Element of C159);
assume L382: (C165 = ( ( netmap (( FinSups C161 ) , C159) ) . C162 ) & C166 = ( ( netmap (( FinSups C161 ) , C159) ) . C163 ));
thus L383: C165 <= C166 by L382 , L374 , L381;
end;
end;
definition
let C167 being non  empty RelStr;
let C168 being (Element of C167);
let C169 being non  empty NetStr over C167;
func C168 "/\" C169 ->  strict NetStr over C167 means 
:L385: (( the RelStr of it ) = ( the RelStr of C169 ) & (for B163 being (Element of it) holds (ex B164 being (Element of C167) st (B164 = ( (the mapping of C169) . B163 ) & ( (the mapping of it) . B163 ) = ( C168 "/\" B164 )))));
existence
proof
defpred S8[ set , set ] means (ex B165 being (Element of C167) st (B165 = ( (the mapping of C169) . $1 ) & $2 = ( C168 "/\" B165 )));
L386: (for B166 being (Element of C169) holds (ex B167 being (Element of C167) st S8[ B166 , B167 ]))
proof
let C170 being (Element of C169);
take ( C168 "/\" ( (the mapping of C169) . C170 ) );
take ( (the mapping of C169) . C170 );
thus L387: thesis;
end;
L388: (ex B168 being (Function of (the carrier of C169) , (the carrier of C167)) st (for B169 being (Element of C169) holds S8[ B169 , ( B168 . B169 ) ])) from FUNCT_2:sch 3(L386);
consider C171 being (Function of (the carrier of C169) , (the carrier of C167)) such that L389: (for B170 being (Element of C169) holds (ex B171 being (Element of C167) st (B171 = ( (the mapping of C169) . B170 ) & ( C171 . B170 ) = ( C168 "/\" B171 )))) by L388;
take NetStr (# (the carrier of C169) , (the InternalRel of C169) , C171 #);
thus L390: thesis by L389;
end;
uniqueness
proof
let C172 , C173 being  strict NetStr over C167;
assume that
L391: ( the RelStr of C172 ) = ( the RelStr of C169 )
and
L392: (for B172 being (Element of C172) holds (ex B173 being (Element of C167) st (B173 = ( (the mapping of C169) . B172 ) & ( (the mapping of C172) . B172 ) = ( C168 "/\" B173 ))))
and
L393: ( the RelStr of C173 ) = ( the RelStr of C169 )
and
L394: (for B174 being (Element of C173) holds (ex B175 being (Element of C167) st (B175 = ( (the mapping of C169) . B174 ) & ( (the mapping of C173) . B174 ) = ( C168 "/\" B175 ))));
reconsider D86 = (the carrier of C172) as non  empty set by L391;
reconsider D87 = (the mapping of C172) , D88 = (the mapping of C173) as (Function of D86 , (the carrier of C167)) by L391 , L393;
L395: (for B176 being (Element of D86) holds ( D87 . B176 ) = ( D88 . B176 ))
proof
let C174 being (Element of D86);
L396: ((ex B177 being (Element of C167) st (B177 = ( (the mapping of C169) . C174 ) & ( D87 . C174 ) = ( C168 "/\" B177 ))) & (ex B178 being (Element of C167) st (B178 = ( (the mapping of C169) . C174 ) & ( D88 . C174 ) = ( C168 "/\" B178 )))) by L391 , L392 , L393 , L394;
thus L397: thesis by L396;
end;
thus L398: thesis by L395 , L391 , L393 , FUNCT_2:63;
end;
end;
theorem
L400: (for B179 being non  empty RelStr holds (for B180 being non  empty NetStr over B179 holds (for B181 being (Element of B179) holds (for B182 being set holds (B182 is (Element of B180) iff B182 is (Element of ( B181 "/\" B180 )))))))
proof
let C175 being non  empty RelStr;
let C176 being non  empty NetStr over C175;
let C177 being (Element of C175);
let C178 being set;
L401: ( the RelStr of ( C177 "/\" C176 ) ) = ( the RelStr of C176 ) by L385;
thus L402: thesis by L401;
end;
registration
let C179 being non  empty RelStr;
let C180 being (Element of C179);
let C181 being non  empty NetStr over C179;
cluster ( C180 "/\" C181 ) -> non  empty;
coherence
proof
L403: ( the RelStr of ( C180 "/\" C181 ) ) = ( the RelStr of C181 ) by L385;
thus L404: thesis by L403;
end;
end;
registration
let C182 being non  empty RelStr;
let C183 being (Element of C182);
let C184 being (prenet of C182);
cluster ( C183 "/\" C184 ) ->  directed;
coherence
proof
L406: (( the RelStr of ( C183 "/\" C184 ) ) = ( the RelStr of C184 ) & ( [#] C184 ) is  directed) by L385 , WAYBEL_0:def 6;
thus L407: ( [#] ( C183 "/\" C184 ) ) is  directed by L406 , WAYBEL_0:3;
end;
end;
theorem
L409: (for B183 being non  empty RelStr holds (for B184 being (Element of B183) holds (for B185 being non  empty NetStr over B183 holds ( rng (the mapping of ( B184 "/\" B185 )) ) = ( { B184 } "/\" ( rng (the mapping of B185) ) ))))
proof
let C185 being non  empty RelStr;
let C186 being (Element of C185);
let C187 being non  empty NetStr over C185;
set D89 = (the mapping of C187);
set D90 = (the mapping of ( C186 "/\" C187 ));
set D91 = ( rng (the mapping of C187) );
L410: ( { C186 } "/\" D91 ) = { ( C186 "/\" B186 ) where B186 is (Element of C185) : B186 in D91 } by YELLOW_4:42;
L411: ( the RelStr of ( C186 "/\" C187 ) ) = ( the RelStr of C187 ) by L385;
L412: ( dom D90 ) = (the carrier of C187) by L411 , FUNCT_2:def 1;
L413: ( dom D89 ) = (the carrier of C187) by FUNCT_2:def 1;
thus L414: ( rng (the mapping of ( C186 "/\" C187 )) ) c= ( { C186 } "/\" D91 )
proof
let C188 being set;
assume L415: C188 in ( rng D90 );
consider C189 being set such that L416: C189 in ( dom D90 ) and L417: C188 = ( D90 . C189 ) by L415 , FUNCT_1:def 3;
reconsider D92 = C189 as (Element of ( C186 "/\" C187 )) by L416;
consider C190 being (Element of C185) such that L418: C190 = ( D89 . D92 ) and L419: ( D90 . D92 ) = ( C186 "/\" C190 ) by L385;
L420: C190 in D91 by L411 , L413 , L418 , FUNCT_1:def 3;
thus L421: thesis by L420 , L410 , L417 , L419;
end;

let C191 being set;
assume L422: C191 in ( { C186 } "/\" D91 );
consider C192 being (Element of C185) such that L423: C191 = ( C186 "/\" C192 ) and L424: C192 in D91 by L422 , L410;
consider C193 being set such that L425: C193 in ( dom D89 ) and L426: C192 = ( D89 . C193 ) by L424 , FUNCT_1:def 3;
reconsider D93 = C193 as (Element of ( C186 "/\" C187 )) by L411 , L425;
L427: (ex B187 being (Element of C185) st (B187 = ( D89 . D93 ) & ( D90 . D93 ) = ( C186 "/\" B187 ))) by L385;
thus L428: thesis by L427 , L412 , L423 , L425 , L426 , FUNCT_1:def 3;
end;
theorem
L429: (for B188 being non  empty RelStr holds (for B189 being set holds (for B190 being (Function of B189 , (the carrier of B188)) holds ((for B191 being set holds  ex_sup_of ( B190 .: B191 ) , B188) implies ( rng ( netmap (( FinSups B190 ) , B188) ) ) c= ( finsups ( rng B190 ) )))))
proof
let C194 being non  empty RelStr;
let C195 being set;
let C196 being (Function of C195 , (the carrier of C194));
assume that
L430: (for B192 being set holds  ex_sup_of ( C196 .: B192 ) , C194);
let C197 being set;
set D94 = ( netmap (( FinSups C196 ) , C194) );
assume L431: C197 in ( rng D94 );
consider C198 being set such that L432: C198 in ( dom D94 ) and L433: ( D94 . C198 ) = C197 by L431 , FUNCT_1:def 3;
L434: (ex B193 being (Function of ( Fin C195 ) , (the carrier of C194)) st (for B194 being (Element of ( Fin C195 )) holds (( B193 . B194 ) = ( sup ( C196 .: B194 ) ) & ( FinSups C196 ) = NetStr (# ( Fin C195 ) , ( RelIncl ( Fin C195 ) ) , B193 #)))) by L347;
reconsider D95 = C198 as (Element of ( Fin C195 )) by L434 , L432;
L435: (( C196 .: D95 ) is  finite  finite  finite  finite (Subset of ( rng C196 )) &  ex_sup_of ( C196 .: D95 ) , C194) by L430 , RELAT_1:111;
L436: ( D94 . D95 ) = ( sup ( C196 .: D95 ) ) by L434;
thus L437: thesis by L436 , L433 , L435;
end;
theorem
L438: (for B195 being non  empty  reflexive  antisymmetric RelStr holds (for B196 being set holds (for B197 being (Function of B196 , (the carrier of B195)) holds ( rng B197 ) c= ( rng ( netmap (( FinSups B197 ) , B195) ) ))))
proof
let C199 being non  empty  reflexive  antisymmetric RelStr;
let C200 being set;
let C201 being (Function of C200 , (the carrier of C199));
per cases ;
suppose L439: C200 is non  empty;

let C202 being set;
assume L440: C202 in ( rng C201 );
consider C203 being set such that L441: C203 in ( dom C201 ) and L442: C202 = ( C201 . C203 ) by L440 , FUNCT_1:def 3;
reconsider D96 = C203 as (Element of C200) by L441;
L443: ( C201 . D96 ) in ( rng C201 ) by L441 , FUNCT_1:def 3;
reconsider D97 = ( C201 . D96 ) as (Element of C199) by L443;
L444: ( Im (C201 , D96) ) = { D97 } by L441 , FUNCT_1:59;
L445: { D96 } c= C200 by L439 , ZFMISC_1:31;
reconsider D98 = { D96 } as (Element of ( Fin C200 )) by L445 , FINSUB_1:def 5;
consider C204 being (Function of ( Fin C200 ) , (the carrier of C199)) such that L446: (for B198 being (Element of ( Fin C200 )) holds (( C204 . B198 ) = ( sup ( C201 .: B198 ) ) & ( FinSups C201 ) = NetStr (# ( Fin C200 ) , ( RelIncl ( Fin C200 ) ) , C204 #))) by L347;
L447: ( dom C204 ) = ( Fin C200 ) by FUNCT_2:def 1;
L448: D98 in ( dom C204 ) by L447;
L449: ( C204 . { D96 } ) = ( sup ( C201 .: D98 ) ) by L446
.= C202 by L442 , L444 , YELLOW_0:39;
thus L450: thesis by L449 , L446 , L448 , FUNCT_1:def 3;
end;
suppose L451: C200 is  empty;

L452: ( rng C201 ) = ( {} ) by L451;
thus L453: thesis by L452 , XBOOLE_1:2;
end;
end;
theorem
L455: (for B199 being non  empty  reflexive  antisymmetric RelStr holds (for B200 being set holds (for B201 being (Function of B200 , (the carrier of B199)) holds (( ex_sup_of ( rng B201 ) , B199 &  ex_sup_of ( rng ( netmap (( FinSups B201 ) , B199) ) ) , B199 & (for B202 being (Element of ( Fin B200 )) holds  ex_sup_of ( B201 .: B202 ) , B199)) implies ( Sup B201 ) = ( sup ( FinSups B201 ) )))))
proof
let C205 being non  empty  reflexive  antisymmetric RelStr;
let C206 being set;
let C207 being (Function of C206 , (the carrier of C205));
assume that
L456:  ex_sup_of ( rng C207 ) , C205
and
L457:  ex_sup_of ( rng ( netmap (( FinSups C207 ) , C205) ) ) , C205
and
L458: (for B203 being (Element of ( Fin C206 )) holds  ex_sup_of ( C207 .: B203 ) , C205);
set D99 = ( netmap (( FinSups C207 ) , C205) );
L459: ( "\/" (( rng C207 ) , C205) ) <= ( sup ( rng D99 ) ) by L456 , L457 , L438 , YELLOW_0:34;
L460: ( rng D99 ) is_<=_than ( "\/" (( rng C207 ) , C205) )
proof
let C208 being (Element of C205);
assume L461: C208 in ( rng D99 );
consider C209 being set such that L462: C209 in ( dom D99 ) and L463: C208 = ( D99 . C209 ) by L461 , FUNCT_1:def 3;
L464: (ex B204 being (Function of ( Fin C206 ) , (the carrier of C205)) st (for B205 being (Element of ( Fin C206 )) holds (( B204 . B205 ) = ( sup ( C207 .: B205 ) ) & ( FinSups C207 ) = NetStr (# ( Fin C206 ) , ( RelIncl ( Fin C206 ) ) , B204 #)))) by L347;
reconsider D100 = C209 as (Element of ( Fin C206 )) by L464 , L462;
L465:  ex_sup_of ( C207 .: D100 ) , C205 by L458;
L466: ( sup ( C207 .: D100 ) ) <= ( "\/" (( rng C207 ) , C205) ) by L465 , L456 , RELAT_1:111 , YELLOW_0:34;
thus L467: C208 <= ( "\/" (( rng C207 ) , C205) ) by L466 , L463 , L464;
end;
L468: ( sup ( rng D99 ) ) <= ( "\/" (( rng C207 ) , C205) ) by L460 , L457 , YELLOW_0:def 9;
thus L469: ( Sup C207 ) = ( "\/" (( rng C207 ) , C205) ) by YELLOW_2:def 5
.= ( sup ( rng ( netmap (( FinSups C207 ) , C205) ) ) ) by L459 , L468 , ORDERS_2:2
.= ( sup ( FinSups C207 ) ) by YELLOW_2:def 5;
end;
theorem
L470: (for B206 being  with_infima  antisymmetric  transitive RelStr holds (for B207 being (prenet of B206) holds (for B208 being (Element of B206) holds (B207 is  eventually-directed implies ( B208 "/\" B207 ) is  eventually-directed))))
proof
let C210 being  with_infima  antisymmetric  transitive RelStr;
let C211 being (prenet of C210);
let C212 being (Element of C210);
assume that
L471: C211 is  eventually-directed;
L472: ( the RelStr of ( C212 "/\" C211 ) ) = ( the RelStr of C211 ) by L385;
L473: (for B209 being (Element of ( C212 "/\" C211 )) holds (ex B210 being (Element of ( C212 "/\" C211 )) st (for B211 being (Element of ( C212 "/\" C211 )) holds (B210 <= B211 implies ( ( C212 "/\" C211 ) . B209 ) <= ( ( C212 "/\" C211 ) . B211 )))))
proof
let C213 being (Element of ( C212 "/\" C211 ));
reconsider D101 = C213 as (Element of C211) by L400;
consider C214 being (Element of C211) such that L474: (for B212 being (Element of C211) holds (C214 <= B212 implies ( C211 . D101 ) <= ( C211 . B212 ))) by L471 , WAYBEL_0:11;
reconsider D102 = C214 as (Element of ( C212 "/\" C211 )) by L400;
take D102;
let C215 being (Element of ( C212 "/\" C211 ));
reconsider D103 = C215 as (Element of C211) by L400;
assume L475: D102 <= C215;
L476: C214 <= D103 by L475 , L472 , YELLOW_0:1;
L477: ( C211 . D101 ) <= ( C211 . D103 ) by L476 , L474;
L478: ((ex B213 being (Element of C210) st (B213 = ( (the mapping of C211) . C213 ) & ( (the mapping of ( C212 "/\" C211 )) . C213 ) = ( C212 "/\" B213 ))) & (ex B214 being (Element of C210) st (B214 = ( (the mapping of C211) . C215 ) & ( (the mapping of ( C212 "/\" C211 )) . C215 ) = ( C212 "/\" B214 )))) by L385;
thus L479: thesis by L478 , L477 , WAYBEL_1:1;
end;
thus L480: thesis by L473 , WAYBEL_0:11;
end;
theorem
L481: (for B215 being  up-complete Semilattice holds ((for B216 being (Element of B215) holds (for B217 being non  empty  directed (Subset of B215) holds (B216 <= ( sup B217 ) implies B216 <= ( sup ( { B216 } "/\" B217 ) )))) implies (for B218 being non  empty  directed (Subset of B215) holds (for B219 being (Element of B215) holds ( B219 "/\" ( sup B218 ) ) = ( sup ( { B219 } "/\" B218 ) )))))
proof
let C216 being  up-complete Semilattice;
assume that
L482: (for B220 being (Element of C216) holds (for B221 being non  empty  directed (Subset of C216) holds (B220 <= ( sup B221 ) implies B220 <= ( sup ( { B220 } "/\" B221 ) ))));
let C217 being non  empty  directed (Subset of C216);
let C218 being (Element of C216);
L483: (ex B222 being (Element of C216) st (C218 >= B222 & ( sup C217 ) >= B222 & (for B223 being (Element of C216) holds ((C218 >= B223 & ( sup C217 ) >= B223) implies B222 >= B223)))) by LATTICE3:def 11;
L484: ( C218 "/\" ( sup C217 ) ) <= ( sup C217 ) by L483 , LATTICE3:def 14;
L485: ( C218 "/\" ( sup C217 ) ) <= ( sup ( { ( C218 "/\" ( sup C217 ) ) } "/\" C217 ) ) by L484 , L482;
reconsider D104 = { ( C218 "/\" ( sup C217 ) ) } as non  empty  directed (Subset of C216) by WAYBEL_0:5;
L486:  ex_sup_of C217 , C216 by WAYBEL_0:75;
L487: ( sup C217 ) is_>=_than C217 by L486 , YELLOW_0:30;
L488: ( ex_sup_of ( D104 "/\" C217 ) , C216 & ( { ( C218 "/\" ( sup C217 ) ) } "/\" C217 ) is_<=_than ( C218 "/\" ( sup C217 ) )) by WAYBEL_0:75 , YELLOW_4:52;
L489: ( sup ( { ( C218 "/\" ( sup C217 ) ) } "/\" C217 ) ) <= ( C218 "/\" ( sup C217 ) ) by L488 , YELLOW_0:30;
thus L490: ( C218 "/\" ( sup C217 ) ) = ( sup ( { ( C218 "/\" ( sup C217 ) ) } "/\" C217 ) ) by L489 , L485 , ORDERS_2:2
.= ( sup ( ( { C218 } "/\" { ( sup C217 ) } ) "/\" C217 ) ) by YELLOW_4:46
.= ( sup ( { C218 } "/\" ( { ( sup C217 ) } "/\" C217 ) ) ) by YELLOW_4:41
.= ( sup ( { C218 } "/\" C217 ) ) by L487 , YELLOW_4:51;
end;
theorem
L491: (for B224 being  with_suprema Poset holds ((for B225 being  directed (Subset of B224) holds (for B226 being (Element of B224) holds ( B226 "/\" ( sup B225 ) ) = ( sup ( { B226 } "/\" B225 ) ))) implies (for B227 being (Subset of B224) holds (for B228 being (Element of B224) holds ( ex_sup_of B227 , B224 implies ( B228 "/\" ( sup B227 ) ) = ( sup ( { B228 } "/\" ( finsups B227 ) ) ))))))
proof
let C219 being  with_suprema Poset;
assume that
L492: (for B229 being  directed (Subset of C219) holds (for B230 being (Element of C219) holds ( B230 "/\" ( sup B229 ) ) = ( sup ( { B230 } "/\" B229 ) )));
let C220 being (Subset of C219);
let C221 being (Element of C219);
assume L493:  ex_sup_of C220 , C219;
thus L494: ( C221 "/\" ( sup C220 ) ) = ( C221 "/\" ( sup ( finsups C220 ) ) ) by L493 , WAYBEL_0:55
.= ( sup ( { C221 } "/\" ( finsups C220 ) ) ) by L492;
end;
theorem
L495: (for B231 being  up-complete LATTICE holds ((for B232 being (Subset of B231) holds (for B233 being (Element of B231) holds ( B233 "/\" ( sup B232 ) ) = ( sup ( { B233 } "/\" ( finsups B232 ) ) ))) implies (for B234 being non  empty  directed (Subset of B231) holds (for B235 being (Element of B231) holds ( B235 "/\" ( sup B234 ) ) = ( sup ( { B235 } "/\" B234 ) )))))
proof
let C222 being  up-complete LATTICE;
assume that
L496: (for B236 being (Subset of C222) holds (for B237 being (Element of C222) holds ( B237 "/\" ( sup B236 ) ) = ( sup ( { B237 } "/\" ( finsups B236 ) ) )));
let C223 being non  empty  directed (Subset of C222);
let C224 being (Element of C222);
reconsider D105 = { C224 } as non  empty  directed (Subset of C222) by WAYBEL_0:5;
L497:  ex_sup_of ( D105 "/\" C223 ) , C222 by WAYBEL_0:75;
L498: ( { C224 } "/\" ( finsups C223 ) ) = { ( C224 "/\" B238 ) where B238 is (Element of C222) : B238 in ( finsups C223 ) } by YELLOW_4:42;
L499: ( { C224 } "/\" ( finsups C223 ) ) is_<=_than ( sup ( { C224 } "/\" C223 ) )
proof
let C225 being (Element of C222);
L500: C224 <= C224;
assume L501: C225 in ( { C224 } "/\" ( finsups C223 ) );
consider C226 being (Element of C222) such that L502: C225 = ( C224 "/\" C226 ) and L503: C226 in ( finsups C223 ) by L501 , L498;
consider C227 being  finite (Subset of C223) such that L504: C226 = ( "\/" (C227 , C222) ) and L505:  ex_sup_of C227 , C222 by L503;
consider C228 being (Element of C222) such that L506: C228 in C223 and L507: C228 is_>=_than C227 by WAYBEL_0:1;
L508: ( "\/" (C227 , C222) ) <= C228 by L505 , L507 , YELLOW_0:30;
L509: ( C224 "/\" C226 ) <= ( C224 "/\" C228 ) by L508 , L504 , L500 , YELLOW_3:2;
L510: C224 in { C224 } by TARSKI:def 1;
L511: ( C224 "/\" C228 ) <= ( sup ( { C224 } "/\" C223 ) ) by L510 , L497 , L506 , YELLOW_4:1 , YELLOW_4:37;
thus L512: C225 <= ( sup ( { C224 } "/\" C223 ) ) by L511 , L502 , L509 , YELLOW_0:def 2;
end;
L513:  ex_sup_of ( D105 "/\" ( finsups C223 ) ) , C222 by WAYBEL_0:75;
L514: ( sup ( { C224 } "/\" ( finsups C223 ) ) ) <= ( sup ( { C224 } "/\" C223 ) ) by L513 , L499 , YELLOW_0:30;
L515: ( C224 "/\" ( sup C223 ) ) <= ( sup ( { C224 } "/\" C223 ) ) by L514 , L496;
L516:  ex_sup_of C223 , C222 by WAYBEL_0:75;
L517: ( sup ( { C224 } "/\" C223 ) ) <= ( C224 "/\" ( sup C223 ) ) by L516 , L497 , YELLOW_4:53;
thus L518: thesis by L517 , L515 , ORDERS_2:2;
end;
begin
definition
let C229 being non  empty RelStr;
func inf_op C229 -> (Function of [: C229 , C229 :] , C229) means 
:L519: (for B239 , B240 being (Element of C229) holds ( it . (B239 , B240) ) = ( B239 "/\" B240 ));
existence
proof
deffunc H3((Element of C229) , (Element of C229)) = ( $1 "/\" $2 );
L520: (for B241 , B242 being (Element of C229) holds H3(B241 , B242) is (Element of C229));
consider C230 being (Function of [: C229 , C229 :] , C229) such that L521: (for B243 , B244 being (Element of C229) holds ( C230 . (B243 , B244) ) = H3(B243 , B244)) from YELLOW_3:sch 6(L520);
take C230;
thus L522: thesis by L521;
end;
uniqueness
proof
let C231 , C232 being (Function of [: C229 , C229 :] , C229);
assume that
L523: (for B245 , B246 being (Element of C229) holds ( C231 . (B245 , B246) ) = ( B245 "/\" B246 ))
and
L524: (for B247 , B248 being (Element of C229) holds ( C232 . (B247 , B248) ) = ( B247 "/\" B248 ));
L525:
now
let C233 , C234 being (Element of C229);
thus L526: ( C231 . (C233 , C234) ) = ( C233 "/\" C234 ) by L523
.= ( C232 . (C233 , C234) ) by L524;
end;
thus L527: C231 = C232 by L525 , YELLOW_3:13;
end;
end;
theorem
L529: (for B249 being non  empty RelStr holds (for B250 being (Element of [: B249 , B249 :]) holds ( ( inf_op B249 ) . B250 ) = ( ( B250 `1 ) "/\" ( B250 `2 ) )))
proof
let C235 being non  empty RelStr;
let C236 being (Element of [: C235 , C235 :]);
L530: (the carrier of [: C235 , C235 :]) = [: (the carrier of C235) , (the carrier of C235) :] by YELLOW_3:def 2;
L531: (ex B251 , B252 being set st (B251 in (the carrier of C235) & B252 in (the carrier of C235) & C236 = [ B251 , B252 ])) by L530 , ZFMISC_1:def 2;
thus L532: ( ( inf_op C235 ) . C236 ) = ( ( inf_op C235 ) . (( C236 `1 ) , ( C236 `2 )) ) by L531 , MCART_1:8
.= ( ( C236 `1 ) "/\" ( C236 `2 ) ) by L519;
end;
registration
let C237 being  with_infima  transitive  antisymmetric RelStr;
cluster ( inf_op C237 ) ->  monotone;
coherence
proof
let C238 , C239 being (Element of [: C237 , C237 :]);
set D106 = ( inf_op C237 );
assume L533: C238 <= C239;
L534: (( C238 `1 ) <= ( C239 `1 ) & ( C238 `2 ) <= ( C239 `2 )) by L533 , YELLOW_3:12;
L535: (( D106 . C238 ) = ( ( C238 `1 ) "/\" ( C238 `2 ) ) & ( D106 . C239 ) = ( ( C239 `1 ) "/\" ( C239 `2 ) )) by L529;
let C240 , C241 being (Element of C237);
assume L536: (C240 = ( D106 . C238 ) & C241 = ( D106 . C239 ));
thus L537: thesis by L536 , L534 , L535 , YELLOW_3:2;
end;
end;
theorem
L539: (for B253 being non  empty RelStr holds (for B254 , B255 being (Subset of B253) holds ( ( inf_op B253 ) .: [: B254 , B255 :] ) = ( B254 "/\" B255 )))
proof
let C242 being non  empty RelStr;
let C243 , C244 being (Subset of C242);
set D107 = ( inf_op C242 );
reconsider D108 = [: C243 , C244 :] as set;
thus L540: ( D107 .: [: C243 , C244 :] ) c= ( C243 "/\" C244 )
proof
let C245 being set;
assume L541: C245 in ( D107 .: [: C243 , C244 :] );
reconsider D109 = C245 as (Element of C242) by L541;
consider C246 being (Element of [: C242 , C242 :]) such that L542: C246 in [: C243 , C244 :] and L543: D109 = ( D107 . C246 ) by L541 , FUNCT_2:65;
consider C247 , C248 being set such that L544: (C247 in C243 & C248 in C244) and L545: C246 = [ C247 , C248 ] by L542 , ZFMISC_1:def 2;
reconsider D110 = C247 , D111 = C248 as (Element of C242) by L544;
L546: C245 = ( D107 . (D110 , D111) ) by L543 , L545
.= ( D110 "/\" D111 ) by L519;
L547: C245 in { ( B256 "/\" B257 ) where B256 , B257 is (Element of C242) : (B256 in C243 & B257 in C244) } by L546 , L544;
thus L548: thesis by L547 , YELLOW_4:def 4;
end;

let C249 being set;
assume L549: C249 in ( C243 "/\" C244 );
L550: C249 in { ( B258 "/\" B259 ) where B258 , B259 is (Element of C242) : (B258 in C243 & B259 in C244) } by L549 , YELLOW_4:def 4;
consider C250 , C251 being (Element of C242) such that L551: (C249 = ( C250 "/\" C251 ) & C250 in C243 & C251 in C244) by L550;
L552: (C249 = ( D107 . (C250 , C251) ) & [ C250 , C251 ] in D108) by L551 , L519 , ZFMISC_1:87;
thus L553: thesis by L552 , FUNCT_2:35;
end;
theorem
L554: (for B260 being  up-complete Semilattice holds (for B261 being non  empty  directed (Subset of [: B260 , B260 :]) holds ( sup ( ( inf_op B260 ) .: B261 ) ) = ( sup ( ( proj1 B261 ) "/\" ( proj2 B261 ) ) )))
proof
let C252 being  up-complete Semilattice;
let C253 being non  empty  directed (Subset of [: C252 , C252 :]);
reconsider D112 = (the carrier of C252) as non  empty set;
reconsider D113 = C253 as non  empty (Subset of [: D112 , D112 :]) by YELLOW_3:def 2;
reconsider D114 = ( proj1 C253 ) , D115 = ( proj2 C253 ) as non  empty  directed (Subset of C252) by YELLOW_3:21 , YELLOW_3:22;
set D116 = ( inf_op C252 );
L555:  ex_sup_of ( D114 "/\" D115 ) , C252 by WAYBEL_0:75;
L556: ( D116 .: [: D114 , D115 :] ) = ( D114 "/\" D115 ) by L539;
L557: (( D116 .: [: D114 , D115 :] ) c= ( D116 .: ( downarrow C253 ) ) & ( D116 .: ( downarrow C253 ) ) c= ( downarrow ( D116 .: C253 ) )) by L222 , RELAT_1:123 , YELLOW_3:48;
L558: ( D116 .: C253 ) is  directed by YELLOW_2:15;
L559:  ex_sup_of ( D116 .: C253 ) , C252 by L558 , WAYBEL_0:75;
L560:  ex_sup_of ( downarrow ( D116 .: C253 ) ) , C252 by L558 , WAYBEL_0:75;
L561: ( sup ( D114 "/\" D115 ) ) <= ( sup ( downarrow ( D116 .: C253 ) ) ) by L560 , L555 , L557 , L556 , XBOOLE_1:1 , YELLOW_0:34;
L562: ( sup ( D114 "/\" D115 ) ) <= ( sup ( D116 .: C253 ) ) by L561 , L559 , WAYBEL_0:33;
L563: ( D116 .: D113 ) c= ( D116 .: [: D114 , D115 :] ) by RELAT_1:123 , YELLOW_3:1;
L564: ( D116 .: D113 ) c= ( D114 "/\" D115 ) by L563 , L539;
L565: ( sup ( D116 .: C253 ) ) <= ( sup ( D114 "/\" D115 ) ) by L564 , L559 , L555 , YELLOW_0:34;
thus L566: thesis by L565 , L562 , ORDERS_2:2;
end;
definition
let C254 being non  empty RelStr;
func sup_op C254 -> (Function of [: C254 , C254 :] , C254) means 
:L567: (for B262 , B263 being (Element of C254) holds ( it . (B262 , B263) ) = ( B262 "\/" B263 ));
existence
proof
deffunc H4((Element of C254) , (Element of C254)) = ( $1 "\/" $2 );
L568: (for B264 , B265 being (Element of C254) holds H4(B264 , B265) is (Element of C254));
consider C255 being (Function of [: C254 , C254 :] , C254) such that L569: (for B266 , B267 being (Element of C254) holds ( C255 . (B266 , B267) ) = H4(B266 , B267)) from YELLOW_3:sch 6(L568);
take C255;
thus L570: thesis by L569;
end;
uniqueness
proof
let C256 , C257 being (Function of [: C254 , C254 :] , C254);
assume that
L571: (for B268 , B269 being (Element of C254) holds ( C256 . (B268 , B269) ) = ( B268 "\/" B269 ))
and
L572: (for B270 , B271 being (Element of C254) holds ( C257 . (B270 , B271) ) = ( B270 "\/" B271 ));
L573:
now
let C258 , C259 being (Element of C254);
thus L574: ( C256 . (C258 , C259) ) = ( C258 "\/" C259 ) by L571
.= ( C257 . (C258 , C259) ) by L572;
end;
thus L575: C256 = C257 by L573 , YELLOW_3:13;
end;
end;
theorem
L577: (for B272 being non  empty RelStr holds (for B273 being (Element of [: B272 , B272 :]) holds ( ( sup_op B272 ) . B273 ) = ( ( B273 `1 ) "\/" ( B273 `2 ) )))
proof
let C260 being non  empty RelStr;
let C261 being (Element of [: C260 , C260 :]);
L578: (the carrier of [: C260 , C260 :]) = [: (the carrier of C260) , (the carrier of C260) :] by YELLOW_3:def 2;
L579: (ex B274 , B275 being set st (B274 in (the carrier of C260) & B275 in (the carrier of C260) & C261 = [ B274 , B275 ])) by L578 , ZFMISC_1:def 2;
thus L580: ( ( sup_op C260 ) . C261 ) = ( ( sup_op C260 ) . (( C261 `1 ) , ( C261 `2 )) ) by L579 , MCART_1:8
.= ( ( C261 `1 ) "\/" ( C261 `2 ) ) by L567;
end;
registration
let C262 being  with_suprema  transitive  antisymmetric RelStr;
cluster ( sup_op C262 ) ->  monotone;
coherence
proof
let C263 , C264 being (Element of [: C262 , C262 :]);
set D117 = ( sup_op C262 );
assume L581: C263 <= C264;
L582: (( C263 `1 ) <= ( C264 `1 ) & ( C263 `2 ) <= ( C264 `2 )) by L581 , YELLOW_3:12;
L583: (( D117 . C263 ) = ( ( C263 `1 ) "\/" ( C263 `2 ) ) & ( D117 . C264 ) = ( ( C264 `1 ) "\/" ( C264 `2 ) )) by L577;
let C265 , C266 being (Element of C262);
assume L584: (C265 = ( D117 . C263 ) & C266 = ( D117 . C264 ));
thus L585: thesis by L584 , L582 , L583 , YELLOW_3:3;
end;
end;
theorem
L587: (for B276 being non  empty RelStr holds (for B277 , B278 being (Subset of B276) holds ( ( sup_op B276 ) .: [: B277 , B278 :] ) = ( B277 "\/" B278 )))
proof
let C267 being non  empty RelStr;
let C268 , C269 being (Subset of C267);
set D118 = ( sup_op C267 );
reconsider D119 = [: C268 , C269 :] as set;
thus L588: ( D118 .: [: C268 , C269 :] ) c= ( C268 "\/" C269 )
proof
let C270 being set;
assume L589: C270 in ( D118 .: [: C268 , C269 :] );
reconsider D120 = C270 as (Element of C267) by L589;
consider C271 being (Element of [: C267 , C267 :]) such that L590: C271 in [: C268 , C269 :] and L591: D120 = ( D118 . C271 ) by L589 , FUNCT_2:65;
consider C272 , C273 being set such that L592: (C272 in C268 & C273 in C269) and L593: C271 = [ C272 , C273 ] by L590 , ZFMISC_1:def 2;
reconsider D121 = C272 , D122 = C273 as (Element of C267) by L592;
L594: C270 = ( D118 . (D121 , D122) ) by L591 , L593
.= ( D121 "\/" D122 ) by L567;
L595: C270 in { ( B279 "\/" B280 ) where B279 , B280 is (Element of C267) : (B279 in C268 & B280 in C269) } by L594 , L592;
thus L596: thesis by L595 , YELLOW_4:def 3;
end;

let C274 being set;
assume L597: C274 in ( C268 "\/" C269 );
L598: C274 in { ( B281 "\/" B282 ) where B281 , B282 is (Element of C267) : (B281 in C268 & B282 in C269) } by L597 , YELLOW_4:def 3;
consider C275 , C276 being (Element of C267) such that L599: (C274 = ( C275 "\/" C276 ) & C275 in C268 & C276 in C269) by L598;
L600: (C274 = ( D118 . (C275 , C276) ) & [ C275 , C276 ] in D119) by L599 , L567 , ZFMISC_1:87;
thus L601: thesis by L600 , FUNCT_2:35;
end;
theorem
L602: (for B283 being  complete non  empty Poset holds (for B284 being non  empty  filtered (Subset of [: B283 , B283 :]) holds ( inf ( ( sup_op B283 ) .: B284 ) ) = ( inf ( ( proj1 B284 ) "\/" ( proj2 B284 ) ) )))
proof
let C277 being  complete non  empty Poset;
let C278 being non  empty  filtered (Subset of [: C277 , C277 :]);
reconsider D123 = (the carrier of C277) as non  empty set;
reconsider D124 = C278 as non  empty (Subset of [: D123 , D123 :]) by YELLOW_3:def 2;
set D125 = ( proj1 C278 );
set D126 = ( proj2 C278 );
set D127 = ( sup_op C277 );
L603:  ex_inf_of ( D125 "\/" D126 ) , C277 by YELLOW_0:17;
L604: ( ex_inf_of ( uparrow ( D127 .: C278 ) ) , C277 & ( D127 .: [: D125 , D126 :] ) c= ( D127 .: ( uparrow C278 ) )) by RELAT_1:123 , YELLOW_0:17 , YELLOW_3:49;
L605: (( D127 .: ( uparrow C278 ) ) c= ( uparrow ( D127 .: C278 ) ) & ( D127 .: [: D125 , D126 :] ) = ( D125 "\/" D126 )) by L236 , L587;
L606: ( inf ( D125 "\/" D126 ) ) >= ( inf ( uparrow ( D127 .: C278 ) ) ) by L605 , L603 , L604 , XBOOLE_1:1 , YELLOW_0:35;
L607: ( inf ( D125 "\/" D126 ) ) >= ( inf ( D127 .: C278 ) ) by L606 , WAYBEL_0:38 , YELLOW_0:17;
L608: ( D127 .: D124 ) c= ( D127 .: [: D125 , D126 :] ) by RELAT_1:123 , YELLOW_3:1;
L609: ( ex_inf_of ( D127 .: D124 ) , C277 & ( D127 .: D124 ) c= ( D125 "\/" D126 )) by L608 , L587 , YELLOW_0:17;
L610: ( inf ( D127 .: C278 ) ) >= ( inf ( D125 "\/" D126 ) ) by L609 , L603 , YELLOW_0:35;
thus L611: thesis by L610 , L607 , ORDERS_2:2;
end;
begin
definition
let C279 being non  empty  reflexive RelStr;
attr C279 is  satisfying_MC
means
:L612: (for B285 being (Element of C279) holds (for B286 being non  empty  directed (Subset of C279) holds ( B285 "/\" ( sup B286 ) ) = ( sup ( { B285 } "/\" B286 ) )));
end;
definition
let C280 being non  empty  reflexive RelStr;
attr C280 is  meet-continuous
means
:L614: C280 is  up-complete  satisfying_MC;
end;
registration
cluster  ->  satisfying_MC for 1 -element  reflexive 1 -element  reflexive 1 -element  reflexive 1 -element  reflexive RelStr;
coherence
proof
let C281 being 1 -element  reflexive RelStr;
let C282 being (Element of C281);
let C283 being non  empty  directed (Subset of C281);
thus L616: thesis by STRUCT_0:def 10;
end;
end;
registration
cluster  meet-continuous ->  up-complete  satisfying_MC for non  empty  reflexive non  empty  reflexive non  empty  reflexive non  empty  reflexive RelStr;
coherence by L614;
cluster  up-complete  satisfying_MC ->  meet-continuous for non  empty  reflexive non  empty  reflexive non  empty  reflexive non  empty  reflexive RelStr;
coherence by L614;
end;
theorem
L619: (for B287 being non  empty  reflexive RelStr holds ((for B288 being (Subset of B287) holds (for B289 being (Element of B287) holds ( B289 "/\" ( sup B288 ) ) = ( "\/" ({ ( B289 "/\" B290 ) where B290 is (Element of B287) : B290 in B288 } , B287) ))) implies B287 is  satisfying_MC))
proof
let C284 being non  empty  reflexive RelStr;
assume that
L620: (for B291 being (Subset of C284) holds (for B292 being (Element of C284) holds ( B292 "/\" ( sup B291 ) ) = ( "\/" ({ ( B292 "/\" B293 ) where B293 is (Element of C284) : B293 in B291 } , C284) )));
let C285 being (Element of C284);
let C286 being non  empty  directed (Subset of C284);
thus L621: ( sup ( { C285 } "/\" C286 ) ) = ( "\/" ({ ( C285 "/\" B294 ) where B294 is (Element of C284) : B294 in C286 } , C284) ) by YELLOW_4:42
.= ( C285 "/\" ( sup C286 ) ) by L620;
end;
theorem
L622: (for B295 being  up-complete Semilattice holds (( SupMap B295 ) is  meet-preserving implies (for B296 , B297 being (Ideal of B295) holds ( ( sup B296 ) "/\" ( sup B297 ) ) = ( sup ( B296 "/\" B297 ) ))))
proof
let C287 being  up-complete Semilattice;
assume that
L623: ( SupMap C287 ) is  meet-preserving;
set D128 = ( SupMap C287 );
let C288 , C289 being (Ideal of C287);
reconsider D129 = C288 , D130 = C289 as (Element of ( InclPoset ( Ids C287 ) )) by YELLOW_2:41;
L624: D128 preserves_inf_of { D129 , D130 } by L623 , WAYBEL_0:def 34;
reconsider D131 = ( D128 . D129 ) as (Element of C287);
thus L625: ( ( sup C288 ) "/\" ( sup C289 ) ) = ( D131 "/\" ( sup C289 ) ) by YELLOW_2:def 3
.= ( ( D128 . D129 ) "/\" ( D128 . D130 ) ) by YELLOW_2:def 3
.= ( D128 . ( D129 "/\" D130 ) ) by L624 , YELLOW_3:8
.= ( D128 . ( C288 "/\" C289 ) ) by YELLOW_4:58
.= ( sup ( C288 "/\" C289 ) ) by YELLOW_2:def 3;
end;
registration
let C290 being  up-complete sup-Semilattice;
cluster ( SupMap C290 ) ->  join-preserving;
coherence
proof
let C291 , C292 being (Element of ( InclPoset ( Ids C290 ) ));
set D132 = ( SupMap C290 );
assume L626:  ex_sup_of { C291 , C292 } , ( InclPoset ( Ids C290 ) );
reconsider D133 = C291 , D134 = C292 as (Ideal of C290) by YELLOW_2:41;
L627:  ex_sup_of ( D133 "\/" D134 ) , C290 by WAYBEL_0:75;
L628: ( dom D132 ) = (the carrier of ( InclPoset ( Ids C290 ) )) by FUNCT_2:def 1;
L629: ( D132 .: { C291 , C292 } ) = { ( D132 . C291 ) , ( D132 . C292 ) } by L628 , FUNCT_1:60;
thus L630:  ex_sup_of ( D132 .: { C291 , C292 } ) , C290 by L629 , YELLOW_0:20;
thus L631: ( sup ( D132 .: { C291 , C292 } ) ) = ( sup { ( D132 . C291 ) , ( D132 . C292 ) } ) by L628 , FUNCT_1:60
.= ( ( D132 . C291 ) "\/" ( D132 . C292 ) ) by YELLOW_0:41
.= ( ( D132 . C291 ) "\/" ( sup D134 ) ) by YELLOW_2:def 3
.= ( ( sup D133 ) "\/" ( sup D134 ) ) by YELLOW_2:def 3
.= ( sup ( D133 "\/" D134 ) ) by L38
.= ( sup ( downarrow ( D133 "\/" D134 ) ) ) by L627 , WAYBEL_0:33
.= ( D132 . ( downarrow ( D133 "\/" D134 ) ) ) by YELLOW_2:def 3
.= ( D132 . ( C291 "\/" C292 ) ) by YELLOW_4:30
.= ( D132 . ( sup { C291 , C292 } ) ) by YELLOW_0:41;
end;
end;
theorem
L633: (for B298 being  up-complete Semilattice holds ((for B299 , B300 being (Ideal of B298) holds ( ( sup B299 ) "/\" ( sup B300 ) ) = ( sup ( B299 "/\" B300 ) )) implies ( SupMap B298 ) is  meet-preserving))
proof
let C293 being  up-complete Semilattice;
assume that
L634: (for B301 , B302 being (Ideal of C293) holds ( ( sup B301 ) "/\" ( sup B302 ) ) = ( sup ( B301 "/\" B302 ) ));
let C294 , C295 being (Element of ( InclPoset ( Ids C293 ) ));
set D135 = ( SupMap C293 );
assume L635:  ex_inf_of { C294 , C295 } , ( InclPoset ( Ids C293 ) );
reconsider D136 = C294 , D137 = C295 as (Ideal of C293) by YELLOW_2:41;
L636: ( dom D135 ) = (the carrier of ( InclPoset ( Ids C293 ) )) by FUNCT_2:def 1;
L637: ( D135 .: { C294 , C295 } ) = { ( D135 . C294 ) , ( D135 . C295 ) } by L636 , FUNCT_1:60;
thus L638:  ex_inf_of ( D135 .: { C294 , C295 } ) , C293 by L637 , YELLOW_0:21;
thus L639: ( inf ( D135 .: { C294 , C295 } ) ) = ( inf { ( D135 . C294 ) , ( D135 . C295 ) } ) by L636 , FUNCT_1:60
.= ( ( D135 . C294 ) "/\" ( D135 . C295 ) ) by YELLOW_0:40
.= ( ( D135 . C294 ) "/\" ( sup D137 ) ) by YELLOW_2:def 3
.= ( ( sup D136 ) "/\" ( sup D137 ) ) by YELLOW_2:def 3
.= ( sup ( D136 "/\" D137 ) ) by L634
.= ( D135 . ( D136 "/\" D137 ) ) by YELLOW_2:def 3
.= ( D135 . ( C294 "/\" C295 ) ) by YELLOW_4:58
.= ( D135 . ( inf { C294 , C295 } ) ) by YELLOW_0:40;
end;
theorem
L640: (for B303 being  up-complete Semilattice holds ((for B304 , B305 being (Ideal of B303) holds ( ( sup B304 ) "/\" ( sup B305 ) ) = ( sup ( B304 "/\" B305 ) )) implies (for B306 , B307 being  directed non  empty (Subset of B303) holds ( ( sup B306 ) "/\" ( sup B307 ) ) = ( sup ( B306 "/\" B307 ) ))))
proof
let C296 being  up-complete Semilattice;
assume that
L641: (for B308 , B309 being (Ideal of C296) holds ( ( sup B308 ) "/\" ( sup B309 ) ) = ( sup ( B308 "/\" B309 ) ));
let C297 , C298 being  directed non  empty (Subset of C296);
L642:  ex_sup_of C298 , C296 by WAYBEL_0:75;
L643:  ex_sup_of ( ( downarrow C297 ) "/\" ( downarrow C298 ) ) , C296 by WAYBEL_0:75;
L644:  ex_sup_of ( C297 "/\" C298 ) , C296 by WAYBEL_0:75;
L645:  ex_sup_of C297 , C296 by WAYBEL_0:75;
thus L646: ( ( sup C297 ) "/\" ( sup C298 ) ) = ( ( sup ( downarrow C297 ) ) "/\" ( sup C298 ) ) by L645 , WAYBEL_0:33
.= ( ( sup ( downarrow C297 ) ) "/\" ( sup ( downarrow C298 ) ) ) by L642 , WAYBEL_0:33
.= ( sup ( ( downarrow C297 ) "/\" ( downarrow C298 ) ) ) by L641
.= ( sup ( downarrow ( ( downarrow C297 ) "/\" ( downarrow C298 ) ) ) ) by L643 , WAYBEL_0:33
.= ( sup ( downarrow ( C297 "/\" C298 ) ) ) by YELLOW_4:62
.= ( sup ( C297 "/\" C298 ) ) by L644 , WAYBEL_0:33;
end;
theorem
L647: (for B310 being non  empty  reflexive RelStr holds (B310 is  satisfying_MC implies (for B311 being (Element of B310) holds (for B312 being non  empty (prenet of B310) holds (B312 is  eventually-directed implies ( B311 "/\" ( sup B312 ) ) = ( sup ( { B311 } "/\" ( rng ( netmap (B312 , B310) ) ) ) ))))))
proof
let C299 being non  empty  reflexive RelStr;
assume that
L648: C299 is  satisfying_MC;
let C300 being (Element of C299);
let C301 being non  empty (prenet of C299);
assume L649: C301 is  eventually-directed;
L650: ( rng ( netmap (C301 , C299) ) ) is  directed by L649 , L308;
thus L651: ( C300 "/\" ( sup C301 ) ) = ( C300 "/\" ( sup ( rng ( netmap (C301 , C299) ) ) ) ) by YELLOW_2:def 5
.= ( sup ( { C300 } "/\" ( rng ( netmap (C301 , C299) ) ) ) ) by L648 , L650 , L612;
end;
theorem
L652: (for B313 being non  empty  reflexive RelStr holds ((for B314 being (Element of B313) holds (for B315 being (prenet of B313) holds (B315 is  eventually-directed implies ( B314 "/\" ( sup B315 ) ) = ( sup ( { B314 } "/\" ( rng ( netmap (B315 , B313) ) ) ) )))) implies B313 is  satisfying_MC))
proof
let C302 being non  empty  reflexive RelStr;
assume that
L653: (for B316 being (Element of C302) holds (for B317 being (prenet of C302) holds (B317 is  eventually-directed implies ( B316 "/\" ( sup B317 ) ) = ( sup ( { B316 } "/\" ( rng ( netmap (B317 , C302) ) ) ) ))));
let C303 being (Element of C302);
let C304 being non  empty  directed (Subset of C302);
reconsider D138 = ( id C304 ) as (Function of C304 , (the carrier of C302)) by FUNCT_2:7;
reconsider D139 = NetStr (# C304 , ( (the InternalRel of C302) |_2 C304 ) , D138 #) as (prenet of C302) by L325;
L654: ( Sup ( netmap (D139 , C302) ) ) = ( sup D139 );
L655: C304 c= C304;
L656: C304 = ( D138 .: C304 ) by L655 , FUNCT_1:92
.= ( rng ( netmap (D139 , C302) ) ) by RELSET_1:22;
thus L657: ( C303 "/\" ( sup C304 ) ) = ( C303 "/\" ( Sup ( netmap (D139 , C302) ) ) ) by L656 , YELLOW_2:def 5
.= ( sup ( { C303 } "/\" C304 ) ) by L653 , L656 , L654 , L336;
end;
theorem
L658: (for B318 being  up-complete  antisymmetric non  empty  reflexive RelStr holds (( inf_op B318 ) is  directed-sups-preserving implies (for B319 , B320 being non  empty  directed (Subset of B318) holds ( ( sup B319 ) "/\" ( sup B320 ) ) = ( sup ( B319 "/\" B320 ) ))))
proof
let C305 being  up-complete  antisymmetric non  empty  reflexive RelStr;
assume that
L659: ( inf_op C305 ) is  directed-sups-preserving;
let C306 , C307 being non  empty  directed (Subset of C305);
set D140 = [: C306 , C307 :];
set D141 = ( inf_op C305 );
L660: D141 preserves_sup_of D140 by L659 , WAYBEL_0:def 37;
L661:  ex_sup_of D140 , [: C305 , C305 :] by WAYBEL_0:75;
L662: ( ex_sup_of C306 , C305 &  ex_sup_of C307 , C305) by WAYBEL_0:75;
thus L663: ( ( sup C306 ) "/\" ( sup C307 ) ) = ( D141 . (( sup C306 ) , ( sup C307 )) ) by L519
.= ( D141 . ( sup D140 ) ) by L662 , YELLOW_3:43
.= ( sup ( D141 .: D140 ) ) by L660 , L661 , WAYBEL_0:def 31
.= ( sup ( C306 "/\" C307 ) ) by L539;
end;
theorem
L664: (for B321 being non  empty  reflexive  antisymmetric RelStr holds ((for B322 , B323 being non  empty  directed (Subset of B321) holds ( ( sup B322 ) "/\" ( sup B323 ) ) = ( sup ( B322 "/\" B323 ) )) implies B321 is  satisfying_MC))
proof
let C308 being non  empty  reflexive  antisymmetric RelStr;
assume that
L665: (for B324 , B325 being non  empty  directed (Subset of C308) holds ( ( sup B324 ) "/\" ( sup B325 ) ) = ( sup ( B324 "/\" B325 ) ));
let C309 being (Element of C308);
let C310 being non  empty  directed (Subset of C308);
L666: { C309 } is  directed by WAYBEL_0:5;
thus L667: ( C309 "/\" ( sup C310 ) ) = ( ( sup { C309 } ) "/\" ( sup C310 ) ) by YELLOW_0:39
.= ( sup ( { C309 } "/\" C310 ) ) by L665 , L666;
end;
theorem
L668: (for B326 being  satisfying_MC  with_infima  antisymmetric non  empty  reflexive RelStr holds (for B327 being (Element of B326) holds (for B328 being non  empty  directed (Subset of B326) holds (B327 <= ( sup B328 ) implies B327 = ( sup ( { B327 } "/\" B328 ) )))))
proof
let C311 being  satisfying_MC  with_infima  antisymmetric non  empty  reflexive RelStr;
let C312 being (Element of C311);
let C313 being non  empty  directed (Subset of C311);
assume L669: C312 <= ( sup C313 );
thus L670: C312 = ( C312 "/\" ( sup C313 ) ) by L669 , YELLOW_0:25
.= ( sup ( { C312 } "/\" C313 ) ) by L612;
end;
theorem
L671: (for B329 being  up-complete Semilattice holds ((for B330 being (Element of B329) holds (for B331 being non  empty  directed (Subset of B329) holds (B330 <= ( sup B331 ) implies B330 <= ( sup ( { B330 } "/\" B331 ) )))) implies ( inf_op B329 ) is  directed-sups-preserving))
proof
let C314 being  up-complete Semilattice;
assume that
L672: (for B332 being (Element of C314) holds (for B333 being non  empty  directed (Subset of C314) holds (B332 <= ( sup B333 ) implies B332 <= ( sup ( { B332 } "/\" B333 ) ))));
let C315 being (Subset of [: C314 , C314 :]);
assume L673: C315 is non  empty  directed;
reconsider D142 = C315 as non  empty  directed (Subset of [: C314 , C314 :]) by L673;
thus L674: ( inf_op C314 ) preserves_sup_of C315
proof
reconsider D143 = ( proj1 D142 ) , D144 = ( proj2 D142 ) as non  empty  directed (Subset of C314) by YELLOW_3:21 , YELLOW_3:22;
reconsider D145 = (the carrier of C314) as non  empty set;
set D146 = ( inf_op C314 );
assume L675:  ex_sup_of C315 , [: C314 , C314 :];
set D147 = ( sup D144 );
defpred S9[ set ] means (ex B334 being (Element of C314) st ($1 = ( { B334 } "/\" D144 ) & B334 in D143));
L676: ( D146 .: D142 ) is  directed by YELLOW_2:15;
thus L677:  ex_sup_of ( D146 .: C315 ) , C314 by L676 , WAYBEL_0:75;
L678: { ( B335 "/\" B336 ) where B335 , B336 is (Element of C314) : (B335 in D143 & B336 in { D147 }) } c= D145
proof
let C316 being set;
assume L679: C316 in { ( B337 "/\" B338 ) where B337 , B338 is (Element of C314) : (B337 in D143 & B338 in { D147 }) };
L680: (ex B339 , B340 being (Element of C314) st (C316 = ( B339 "/\" B340 ) & B339 in D143 & B340 in { D147 })) by L679;
thus L681: thesis by L680;
end;
reconsider D148 = { ( B341 "/\" B342 ) where B341 , B342 is (Element of C314) : (B341 in D143 & B342 in { D147 }) } as (Subset of C314) by L678;
L682: ( "\/" ({ ( sup B343 ) where B343 is non  empty  directed (Subset of C314) : S9[ B343 ] } , C314) ) = ( "\/" (( union { B344 where B344 is non  empty  directed (Subset of C314) : S9[ B344 ] } ) , C314) ) by L140;
L683: D148 = { ( sup ( { B345 } "/\" D144 ) ) where B345 is (Element of C314) : B345 in D143 }
proof
thus L684: D148 c= { ( sup ( { B346 } "/\" D144 ) ) where B346 is (Element of C314) : B346 in D143 }
proof
let C317 being set;
assume L685: C317 in D148;
consider C318 , C319 being (Element of C314) such that L686: C317 = ( C318 "/\" C319 ) and L687: C318 in D143 and L688: C319 in { D147 } by L685;
L689: C317 = ( C318 "/\" D147 ) by L686 , L688 , TARSKI:def 1
.= ( sup ( { C318 } "/\" D144 ) ) by L672 , L481;
thus L690: thesis by L689 , L687;
end;

let C320 being set;
L691: D147 in { D147 } by TARSKI:def 1;
assume L692: C320 in { ( sup ( { B347 } "/\" D144 ) ) where B347 is (Element of C314) : B347 in D143 };
consider C321 being (Element of C314) such that L693: C320 = ( sup ( { C321 } "/\" D144 ) ) and L694: C321 in D143 by L692;
L695: C320 = ( C321 "/\" D147 ) by L672 , L693 , L481;
thus L696: thesis by L695 , L694 , L691;
end;
thus L697: ( sup ( D146 .: C315 ) ) = ( sup ( D143 "/\" D144 ) ) by L554
.= ( "\/" ({ ( "\/" (B348 , C314) ) where B348 is non  empty  directed (Subset of C314) : S9[ B348 ] } , C314) ) by L682 , L62
.= ( "\/" ({ ( sup ( { B349 } "/\" D144 ) ) where B349 is (Element of C314) : B349 in D143 } , C314) ) by L53
.= ( sup ( { D147 } "/\" D143 ) ) by L683 , YELLOW_4:def 4
.= ( ( sup D143 ) "/\" D147 ) by L672 , L481
.= ( D146 . (( sup D143 ) , ( sup D144 )) ) by L519
.= ( D146 . ( sup C315 ) ) by L195;
end;

end;
theorem
L675: (for B350 being  complete  antisymmetric non  empty  reflexive RelStr holds ((for B351 being (Element of B350) holds (for B352 being (prenet of B350) holds (B352 is  eventually-directed implies ( B351 "/\" ( sup B352 ) ) = ( sup ( { B351 } "/\" ( rng ( netmap (B352 , B350) ) ) ) )))) implies (for B353 being (Element of B350) holds (for B354 being set holds (for B355 being (Function of B354 , (the carrier of B350)) holds ( B353 "/\" ( Sup B355 ) ) = ( sup ( B353 "/\" ( FinSups B355 ) ) ))))))
proof
let C322 being  complete  antisymmetric non  empty  reflexive RelStr;
assume that
L676: (for B356 being (Element of C322) holds (for B357 being (prenet of C322) holds (B357 is  eventually-directed implies ( B356 "/\" ( sup B357 ) ) = ( sup ( { B356 } "/\" ( rng ( netmap (B357 , C322) ) ) ) ))));
let C323 being (Element of C322);
let C324 being set;
let C325 being (Function of C324 , (the carrier of C322));
set D149 = ( FinSups C325 );
L677: (for B358 being (Element of ( Fin C324 )) holds  ex_sup_of ( C325 .: B358 ) , C322) by YELLOW_0:17;
L678: ( ex_sup_of ( rng C325 ) , C322 &  ex_sup_of ( rng ( netmap (( FinSups C325 ) , C322) ) ) , C322) by YELLOW_0:17;
thus L679: ( C323 "/\" ( Sup C325 ) ) = ( C323 "/\" ( sup D149 ) ) by L678 , L677 , L455
.= ( sup ( { C323 } "/\" ( rng ( netmap (D149 , C322) ) ) ) ) by L676
.= ( "\/" (( rng (the mapping of ( C323 "/\" D149 )) ) , C322) ) by L409
.= ( sup ( C323 "/\" D149 ) ) by YELLOW_2:def 5;
end;
theorem
L680: (for B359 being  complete Semilattice holds ((for B360 being (Element of B359) holds (for B361 being set holds (for B362 being (Function of B361 , (the carrier of B359)) holds ( B360 "/\" ( Sup B362 ) ) = ( sup ( B360 "/\" ( FinSups B362 ) ) )))) implies (for B363 being (Element of B359) holds (for B364 being (prenet of B359) holds (B364 is  eventually-directed implies ( B363 "/\" ( sup B364 ) ) = ( sup ( { B363 } "/\" ( rng ( netmap (B364 , B359) ) ) ) ))))))
proof
let C326 being  complete Semilattice;
assume that
L681: (for B365 being (Element of C326) holds (for B366 being set holds (for B367 being (Function of B366 , (the carrier of C326)) holds ( B365 "/\" ( Sup B367 ) ) = ( sup ( B365 "/\" ( FinSups B367 ) ) ))));
let C327 being (Element of C326);
let C328 being (prenet of C326);
assume that
L682: C328 is  eventually-directed;
reconsider D150 = ( rng ( netmap (C328 , C326) ) ) as non  empty  directed (Subset of C326) by L682 , L308;
reconsider D151 = { C327 } as non  empty  directed (Subset of C326) by WAYBEL_0:5;
set D152 = (the mapping of C328);
set D153 = (the mapping of ( FinSups D152 ));
L683:  ex_sup_of ( D151 "/\" D150 ) , C326 by WAYBEL_0:75;
L684: ( rng (the mapping of ( C327 "/\" ( FinSups D152 ) )) ) is_<=_than ( sup ( { C327 } "/\" ( rng ( netmap (C328 , C326) ) ) ) )
proof
let C329 being (Element of C326);
L685: ( { C327 } "/\" ( rng D153 ) ) = { ( C327 "/\" B368 ) where B368 is (Element of C326) : B368 in ( rng D153 ) } by YELLOW_4:42;
assume L686: C329 in ( rng (the mapping of ( C327 "/\" ( FinSups D152 ) )) );
L687: C329 in ( { C327 } "/\" ( rng D153 ) ) by L686 , L409;
consider C330 being (Element of C326) such that L688: C329 = ( C327 "/\" C330 ) and L689: C330 in ( rng D153 ) by L687 , L685;
L690: (for B369 being set holds  ex_sup_of ( D152 .: B369 ) , C326) by YELLOW_0:17;
L691: ( rng ( netmap (( FinSups D152 ) , C326) ) ) c= ( finsups ( rng D152 ) ) by L690 , L429;
L692: C330 in ( finsups ( rng D152 ) ) by L691 , L689;
consider C331 being  finite (Subset of ( rng D152 )) such that L693: C330 = ( "\/" (C331 , C326) ) and L694:  ex_sup_of C331 , C326 by L692;
L695: ( rng ( netmap (C328 , C326) ) ) is  directed by L682 , L308;
consider C332 being (Element of C326) such that L696: C332 in ( rng D152 ) and L697: C332 is_>=_than C331 by L695 , WAYBEL_0:1;
L698: C327 <= C327;
L699: ( "\/" (C331 , C326) ) <= C332 by L694 , L697 , YELLOW_0:30;
L700: ( C327 "/\" C330 ) <= ( C327 "/\" C332 ) by L699 , L693 , L698 , YELLOW_3:2;
L701: C327 in { C327 } by TARSKI:def 1;
L702: ( C327 "/\" C332 ) <= ( sup ( D151 "/\" ( rng D152 ) ) ) by L701 , L683 , L696 , YELLOW_4:1 , YELLOW_4:37;
thus L703: C329 <= ( sup ( { C327 } "/\" ( rng ( netmap (C328 , C326) ) ) ) ) by L702 , L688 , L700 , YELLOW_0:def 2;
end;
L704: ( C327 "/\" ( FinSups D152 ) ) is  eventually-directed by L470;
L705: ( rng ( netmap (( C327 "/\" ( FinSups D152 ) ) , C326) ) ) is  directed by L704 , L308;
L706:  ex_sup_of ( rng (the mapping of ( C327 "/\" ( FinSups D152 ) )) ) , C326 by L705 , WAYBEL_0:75;
L707: (( sup ( C327 "/\" ( FinSups D152 ) ) ) = ( "\/" (( rng (the mapping of ( C327 "/\" ( FinSups D152 ) )) ) , C326) ) & ( "\/" (( rng (the mapping of ( C327 "/\" ( FinSups D152 ) )) ) , C326) ) <= ( sup ( { C327 } "/\" ( rng ( netmap (C328 , C326) ) ) ) )) by L706 , L684 , YELLOW_0:def 9 , YELLOW_2:def 5;
L708: ( C327 "/\" ( Sup ( netmap (C328 , C326) ) ) ) <= ( sup ( { C327 } "/\" ( rng ( netmap (C328 , C326) ) ) ) ) by L707 , L681;
L709: ( ex_sup_of D150 , C326 & ( Sup ( netmap (C328 , C326) ) ) = ( "\/" (( rng ( netmap (C328 , C326) ) ) , C326) )) by WAYBEL_0:75 , YELLOW_2:def 5;
L710: ( sup ( { C327 } "/\" ( rng ( netmap (C328 , C326) ) ) ) ) <= ( C327 "/\" ( Sup ( netmap (C328 , C326) ) ) ) by L709 , L683 , YELLOW_4:53;
thus L711: thesis by L710 , L708 , ORDERS_2:2;
end;
theorem
L712: (for B370 being  up-complete LATTICE holds (B370 is  meet-continuous iff ( SupMap B370 ) is  meet-preserving  join-preserving))
proof
let C333 being  up-complete LATTICE;
thus L713:now
assume L714: C333 is  meet-continuous;
L715: (for B371 , B372 being non  empty  directed (Subset of C333) holds ( ( sup B371 ) "/\" ( sup B372 ) ) = ( sup ( B371 "/\" B372 ) ))
proof
let C334 , C335 being non  empty  directed (Subset of C333);
L716: (for B373 being (Element of C333) holds (for B374 being non  empty  directed (Subset of C333) holds (B373 <= ( sup B374 ) implies B373 <= ( sup ( { B373 } "/\" B374 ) )))) by L714 , L668;
L717: ( inf_op C333 ) is  directed-sups-preserving by L716 , L671;
thus L718: thesis by L717 , L658;
end;
L719: (for B375 , B376 being (Ideal of C333) holds ( ( sup B375 ) "/\" ( sup B376 ) ) = ( sup ( B375 "/\" B376 ) )) by L715;
thus L720: ( SupMap C333 ) is  meet-preserving  join-preserving by L719 , L633;
end;
assume L721: ( SupMap C333 ) is  meet-preserving  join-preserving;
thus L722: C333 is  up-complete;
L723: (for B377 , B378 being (Ideal of C333) holds ( ( sup B377 ) "/\" ( sup B378 ) ) = ( sup ( B377 "/\" B378 ) )) by L721 , L622;
L724: (for B379 , B380 being non  empty  directed (Subset of C333) holds ( ( sup B379 ) "/\" ( sup B380 ) ) = ( sup ( B379 "/\" B380 ) )) by L723 , L640;
thus L725: thesis by L724 , L664;
end;
registration
let C336 being  meet-continuous LATTICE;
cluster ( SupMap C336 ) ->  meet-preserving  join-preserving;
coherence by L712;
end;
theorem
L727: (for B381 being  up-complete LATTICE holds (B381 is  meet-continuous iff (for B382 , B383 being (Ideal of B381) holds ( ( sup B382 ) "/\" ( sup B383 ) ) = ( sup ( B382 "/\" B383 ) ))))
proof
let C337 being  up-complete LATTICE;
thus L728:now
assume L729: C337 is  meet-continuous;
L730: ( SupMap C337 ) is  meet-preserving  join-preserving by L729;
thus L731: (for B384 , B385 being (Ideal of C337) holds ( ( sup B384 ) "/\" ( sup B385 ) ) = ( sup ( B384 "/\" B385 ) )) by L730 , L622;
end;
assume L732: (for B386 , B387 being (Ideal of C337) holds ( ( sup B386 ) "/\" ( sup B387 ) ) = ( sup ( B386 "/\" B387 ) ));
L733: (for B388 , B389 being  directed non  empty (Subset of C337) holds ( ( sup B388 ) "/\" ( sup B389 ) ) = ( sup ( B388 "/\" B389 ) )) by L732 , L640;
thus L734: (C337 is  up-complete & C337 is  satisfying_MC) by L733 , L664;
end;
theorem
L735: (for B390 being  up-complete LATTICE holds (B390 is  meet-continuous iff (for B391 , B392 being non  empty  directed (Subset of B390) holds ( ( sup B391 ) "/\" ( sup B392 ) ) = ( sup ( B391 "/\" B392 ) ))))
proof
let C338 being  up-complete LATTICE;
thus L736:now
assume L737: C338 is  meet-continuous;
L738: (for B393 , B394 being (Ideal of C338) holds ( ( sup B393 ) "/\" ( sup B394 ) ) = ( sup ( B393 "/\" B394 ) )) by L737 , L727;
thus L739: (for B395 , B396 being  directed non  empty (Subset of C338) holds ( ( sup B395 ) "/\" ( sup B396 ) ) = ( sup ( B395 "/\" B396 ) )) by L738 , L640;
end;
assume L740: (for B397 , B398 being non  empty  directed (Subset of C338) holds ( ( sup B397 ) "/\" ( sup B398 ) ) = ( sup ( B397 "/\" B398 ) ));
thus L741: (C338 is  up-complete & C338 is  satisfying_MC) by L740 , L664;
end;
theorem
L742: (for B399 being  up-complete LATTICE holds (B399 is  meet-continuous iff (for B400 being (Element of B399) holds (for B401 being non  empty  directed (Subset of B399) holds (B400 <= ( sup B401 ) implies B400 = ( sup ( { B400 } "/\" B401 ) ))))))
proof
let C339 being  up-complete LATTICE;
thus L743: (C339 is  meet-continuous implies (for B402 being (Element of C339) holds (for B403 being non  empty  directed (Subset of C339) holds (B402 <= ( sup B403 ) implies B402 = ( sup ( { B402 } "/\" B403 ) ))))) by L668;
assume L744: (for B404 being (Element of C339) holds (for B405 being non  empty  directed (Subset of C339) holds (B404 <= ( sup B405 ) implies B404 = ( sup ( { B404 } "/\" B405 ) ))));
L745: (for B406 being (Element of C339) holds (for B407 being non  empty  directed (Subset of C339) holds (B406 <= ( sup B407 ) implies B406 <= ( sup ( { B406 } "/\" B407 ) )))) by L744;
L746: ( inf_op C339 ) is  directed-sups-preserving by L745 , L671;
L747: (for B408 , B409 being non  empty  directed (Subset of C339) holds ( ( sup B408 ) "/\" ( sup B409 ) ) = ( sup ( B408 "/\" B409 ) )) by L746 , L658;
thus L748: thesis by L747 , L735;
end;
theorem
L749: (for B410 being  up-complete Semilattice holds (B410 is  meet-continuous iff ( inf_op B410 ) is  directed-sups-preserving))
proof
let C340 being  up-complete Semilattice;
thus L750:now
assume L751: C340 is  meet-continuous;
L752: (for B411 being (Element of C340) holds (for B412 being non  empty  directed (Subset of C340) holds (B411 <= ( sup B412 ) implies B411 <= ( sup ( { B411 } "/\" B412 ) )))) by L751 , L668;
thus L753: ( inf_op C340 ) is  directed-sups-preserving by L752 , L671;
end;
assume L754: ( inf_op C340 ) is  directed-sups-preserving;
L755: (for B413 , B414 being non  empty  directed (Subset of C340) holds ( ( sup B413 ) "/\" ( sup B414 ) ) = ( sup ( B413 "/\" B414 ) )) by L754 , L658;
thus L756: (C340 is  up-complete & C340 is  satisfying_MC) by L755 , L664;
end;
registration
let C341 being  meet-continuous Semilattice;
cluster ( inf_op C341 ) ->  directed-sups-preserving;
coherence by L749;
end;
theorem
L758: (for B415 being  up-complete Semilattice holds (B415 is  meet-continuous iff (for B416 being (Element of B415) holds (for B417 being non  empty (prenet of B415) holds (B417 is  eventually-directed implies ( B416 "/\" ( sup B417 ) ) = ( sup ( { B416 } "/\" ( rng ( netmap (B417 , B415) ) ) ) ))))))
proof
let C342 being  up-complete Semilattice;
thus L759: (C342 is  meet-continuous implies (for B418 being (Element of C342) holds (for B419 being non  empty (prenet of C342) holds (B419 is  eventually-directed implies ( B418 "/\" ( sup B419 ) ) = ( sup ( { B418 } "/\" ( rng ( netmap (B419 , C342) ) ) ) ))))) by L647;
assume L760: (for B420 being (Element of C342) holds (for B421 being non  empty (prenet of C342) holds (B421 is  eventually-directed implies ( B420 "/\" ( sup B421 ) ) = ( sup ( { B420 } "/\" ( rng ( netmap (B421 , C342) ) ) ) ))));
thus L761: (C342 is  up-complete & C342 is  satisfying_MC) by L760 , L652;
end;
theorem
L762: (for B422 being  complete Semilattice holds (B422 is  meet-continuous iff (for B423 being (Element of B422) holds (for B424 being set holds (for B425 being (Function of B424 , (the carrier of B422)) holds ( B423 "/\" ( Sup B425 ) ) = ( sup ( B423 "/\" ( FinSups B425 ) ) ))))))
proof
let C343 being  complete Semilattice;
thus L763:now
assume L764: C343 is  meet-continuous;
L765: (for B426 being (Element of C343) holds (for B427 being non  empty (prenet of C343) holds (B427 is  eventually-directed implies ( B426 "/\" ( sup B427 ) ) = ( sup ( { B426 } "/\" ( rng ( netmap (B427 , C343) ) ) ) )))) by L764 , L758;
thus L766: (for B428 being (Element of C343) holds (for B429 being set holds (for B430 being (Function of B429 , (the carrier of C343)) holds ( B428 "/\" ( Sup B430 ) ) = ( sup ( B428 "/\" ( FinSups B430 ) ) )))) by L765 , L675;
end;
assume L767: (for B431 being (Element of C343) holds (for B432 being set holds (for B433 being (Function of B432 , (the carrier of C343)) holds ( B431 "/\" ( Sup B433 ) ) = ( sup ( B431 "/\" ( FinSups B433 ) ) ))));
L768: (for B434 being (Element of C343) holds (for B435 being (prenet of C343) holds (B435 is  eventually-directed implies ( B434 "/\" ( sup B435 ) ) = ( sup ( { B434 } "/\" ( rng ( netmap (B435 , C343) ) ) ) )))) by L767 , L680;
thus L769: (C343 is  up-complete & C343 is  satisfying_MC) by L768 , L652;
end;
L770: (for B436 being  meet-continuous Semilattice holds (for B437 being (Element of B436) holds ( B437 "/\" ) is  directed-sups-preserving))
proof
let C344 being  meet-continuous Semilattice;
let C345 being (Element of C344);
let C346 being (Subset of C344);
assume that
L771: C346 is non  empty  directed;
reconsider D154 = C346 as non  empty (Subset of C344) by L771;
assume L772:  ex_sup_of C346 , C344;
L773: ( ( C345 "/\" ) .: D154 ) is non  empty;
L774: ( ( C345 "/\" ) .: C346 ) is  directed by L771 , YELLOW_2:15;
thus L775:  ex_sup_of ( ( C345 "/\" ) .: C346 ) , C344 by L774 , L773 , WAYBEL_0:75;
L776: (for B438 being (Element of C344) holds (for B439 being non  empty  directed (Subset of C344) holds (B438 <= ( sup B439 ) implies B438 <= ( sup ( { B438 } "/\" B439 ) )))) by L668;
thus L777: ( sup ( ( C345 "/\" ) .: C346 ) ) = ( "\/" ({ ( C345 "/\" B440 ) where B440 is (Element of C344) : B440 in C346 } , C344) ) by WAYBEL_1:61
.= ( sup ( { C345 } "/\" C346 ) ) by YELLOW_4:42
.= ( C345 "/\" ( sup C346 ) ) by L771 , L776 , L481
.= ( ( C345 "/\" ) . ( sup C346 ) ) by WAYBEL_1:def 18;
end;
registration
let C347 being  meet-continuous Semilattice;
let C348 being (Element of C347);
cluster ( C348 "/\" ) ->  directed-sups-preserving;
coherence by L770;
end;
theorem
L779: (for B441 being  complete non  empty Poset holds (B441 is  Heyting iff B441 is  meet-continuous  distributive))
proof
let C349 being  complete non  empty Poset;
thus L780:now
assume L781: C349 is  Heyting;
L782: (for B442 being (Element of C349) holds ( B442 "/\" ) is  lower_adjoint) by L781 , WAYBEL_1:def 19;
L783: (for B443 being (Subset of C349) holds (for B444 being (Element of C349) holds ( B444 "/\" ( sup B443 ) ) = ( "\/" ({ ( B444 "/\" B445 ) where B445 is (Element of C349) : B445 in B443 } , C349) ))) by L782 , WAYBEL_1:64;
L784: C349 is  up-complete  satisfying_MC by L783 , L619;
thus L785: C349 is  meet-continuous by L784;
thus L786: C349 is  distributive by L781;
end;
assume L787: C349 is  meet-continuous  distributive;
thus L788: C349 is LATTICE;
let C350 being (Element of C349);
L789: ((for B446 being  finite (Subset of C349) holds ( C350 "/\" ) preserves_sup_of B446) & (for B447 being non  empty  directed (Subset of C349) holds ( C350 "/\" ) preserves_sup_of B447)) by L787 , L299 , WAYBEL_0:def 37;
L790: ( C350 "/\" ) is  sups-preserving by L789 , WAYBEL_0:74;
thus L791: thesis by L790 , WAYBEL_1:17;
end;
registration
cluster  complete  Heyting ->  meet-continuous  distributive for non  empty non  empty non  empty non  empty Poset;
coherence by L779;
cluster  complete  meet-continuous  distributive ->  Heyting for non  empty non  empty non  empty non  empty Poset;
coherence by L779;
end;
