:: Basic Operations on Extended Real Numbers
::  by Andrzej Trybulec
::
:: Received September 23, 2008
:: Copyright (c) 2008-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies NUMBERS, XXREAL_0, ORDINAL1, XREAL_0, SUBSET_1, CARD_1, ARYTM_3,
      XCMPLX_0, ARYTM_1, RELAT_1;
 notations ORDINAL1, SUBSET_1, XCMPLX_0, XXREAL_0, XREAL_0, NUMBERS;
 constructors XBOOLE_0, ORDINAL1, XXREAL_0, XCMPLX_0, XREAL_0, NUMBERS,
      XXREAL_2;
 registrations XXREAL_0, XREAL_0, ORDINAL1, XBOOLE_0, XCMPLX_0, REAL_1;
 requirements BOOLE, SUBSET, NUMERALS, ARITHM, REAL;
 definitions XCMPLX_0, XXREAL_0;
 theorems XXREAL_0, XREAL_0, XCMPLX_1, XREAL_1;

begin
definition
let R1 being  ext-real number;
let R2 being  ext-real number;
redefine pred R1 <= R2
means
:L1: (ex B1 , B2 being (Element of ( REAL )) st (B1 = R1 & B2 = R2 & B1 <= B2)) if (R1 in ( REAL ) & R2 in ( REAL )) otherwise (R1 = ( -infty ) or R2 = ( +infty ))
;consistency;
compatibility
proof
thus L2: ((R1 in ( REAL ) & R2 in ( REAL )) implies (R1 <= R2 iff (ex B3 , B4 being (Element of ( REAL )) st (B3 = R1 & B4 = R2 & B3 <= B4))));
thus L3: ((not (R1 in ( REAL ) & R2 in ( REAL ))) implies (R1 <= R2 iff (R1 = ( -infty ) or R2 = ( +infty ))))
proof
assume L4: (not (R1 in ( REAL ) & R2 in ( REAL )));
per cases  by L4;
suppose L5: (not R1 in ( REAL ));

thus L6: (R1 <= R2 implies (R1 = ( -infty ) or R2 = ( +infty )))
proof
assume L7: R1 <= R2;
assume L8: R1 <> ( -infty );
L9: R1 = ( +infty ) by L8 , L5 , XXREAL_0:14;
thus L10: thesis by L9 , L7 , XXREAL_0:4;
end;

thus L11: thesis by XXREAL_0:3 , XXREAL_0:5;
end;
suppose L12: (not R2 in ( REAL ));

thus L13: (R1 <= R2 implies (R1 = ( -infty ) or R2 = ( +infty )))
proof
assume L14: R1 <= R2;
assume L15: R1 <> ( -infty );
assume L16: R2 <> ( +infty );
L17: R2 = ( -infty ) by L16 , L12 , XXREAL_0:14;
thus L18: thesis by L17 , L14 , L15 , XXREAL_0:6;
end;

thus L19: thesis by XXREAL_0:3 , XXREAL_0:5;
end;
end;

end;
end;
registration
cluster non  real  positive for  ext-real  ext-real  ext-real  ext-real number;
existence
proof
take ( +infty );
thus L5: thesis;
end;
cluster non  real  negative for  ext-real  ext-real  ext-real  ext-real number;
existence
proof
take ( -infty );
thus L6: thesis;
end;
end;
theorem
L8: (for B5 being non  real  positive  ext-real number holds B5 = ( +infty ))
proof
let C1 being non  real  positive  ext-real number;
L9: (not C1 in ( REAL ));
thus L10: thesis by L9 , XXREAL_0:14;
end;
theorem
L11: (for B6 being non  real  negative  ext-real number holds B6 = ( -infty ))
proof
let C2 being non  real  negative  ext-real number;
L12: (not C2 in ( REAL ));
thus L13: thesis by L12 , XXREAL_0:14;
end;
registration
cluster non  real non  negative ->  positive for  ext-real  ext-real  ext-real  ext-real number;
coherence;
cluster non  real non  positive ->  negative for  ext-real  ext-real  ext-real  ext-real number;
coherence;
end;
theorem
L15: (for R1 being  ext-real number holds (for R3 being  ext-real number holds (R1 < R3 implies (ex B7 being  real number st (R1 < B7 & B7 < R3)))))
proof
let R1 being  ext-real number;
let R3 being  ext-real number;
assume L16: R1 < R3;
per cases  by XXREAL_0:14;
suppose L17: (R1 in ( REAL ) & R3 in ( REAL ));

thus L18: thesis by L17 , L16 , XREAL_1:5;
end;
suppose L19: (R1 = ( +infty ) or R3 = ( -infty ));

thus L20: thesis by L19 , L16 , XXREAL_0:4 , XXREAL_0:6;
end;
suppose L21: R3 = ( +infty );

per cases  by L16 , L21 , XXREAL_0:14;
suppose L22: R1 = ( -infty );

thus L23: thesis by L22 , L21;
end;
suppose L24: R1 in ( REAL );

reconsider D1 = R1 as  real number by L24;
take ( D1 + 1 );
L25: ( D1 + 1 ) in ( REAL ) by XREAL_0:def 1;
L26: ( D1 + ( 0 ) ) < ( D1 + 1 ) by XREAL_1:8;
thus L27: thesis by L26 , L21 , L25 , XXREAL_0:9;
end;
end;
suppose L29: R1 = ( -infty );

per cases  by L16 , L29 , XXREAL_0:14;
suppose L30: R3 = ( +infty );

thus L31: thesis by L30 , L29;
end;
suppose L32: R3 in ( REAL );

reconsider D2 = R3 as  real number by L32;
take ( D2 - 1 );
L33: ( D2 - 1 ) in ( REAL ) by XREAL_0:def 1;
L34: ( D2 - 1 ) < ( D2 - ( 0 ) ) by XREAL_1:10;
thus L35: thesis by L34 , L29 , L33 , XXREAL_0:12;
end;
end;
end;
begin
definition
let R1 being  ext-real number;
let R2 being  ext-real number;
func R1 + R2 ->  ext-real number means 
:L38: (ex B8 , B9 being  complex number st (R1 = B8 & R2 = B9 & it = ( B8 + B9 ))) if (R1 is  real & R2 is  real) , it = ( +infty ) if ((R1 = ( +infty ) & R2 <> ( -infty )) or (R2 = ( +infty ) & R1 <> ( -infty ))) , it = ( -infty ) if ((R1 = ( -infty ) & R2 <> ( +infty )) or (R2 = ( -infty ) & R1 <> ( +infty ))) otherwise it = ( 0 );
existence
proof
thus L39: ((R1 is  real & R2 is  real) implies (ex B10 being  ext-real number st (ex B11 , B12 being  complex number st (R1 = B11 & R2 = B12 & B10 = ( B11 + B12 )))))
proof
assume L40: (R1 is  real & R2 is  real);
reconsider D3 = R1 , D4 = R2 as  real number by L40;
take ( D3 + D4 );
take D3;
take D4;
thus L41: thesis;
end;

thus L42: thesis;
end;
uniqueness;
consistency;
commutativity
;
end;
definition
let R1 being  ext-real number;
func - R1 ->  ext-real number means 
:L44: (ex B13 being  complex number st (R1 = B13 & it = ( - B13 ))) if R1 is  real , it = ( -infty ) if R1 = ( +infty ) otherwise it = ( +infty );
existence
proof
thus L45: (R1 is  real implies (ex B14 being  ext-real number st (ex B15 being  complex number st (R1 = B15 & B14 = ( - B15 )))))
proof
assume L46: R1 is  real;
reconsider D5 = R1 as  real number by L46;
take ( - D5 );
take D5;
thus L47: thesis;
end;

thus L48: thesis;
end;
uniqueness;
consistency;
involutiveness
proof
let C3 , C4 being  ext-real number;
assume that
L49: (C4 is  real implies (ex B16 being  complex number st (C4 = B16 & C3 = ( - B16 ))))
and
L50: (C4 = ( +infty ) implies C3 = ( -infty ))
and
L51: (((not C4 is  real) & C4 <> ( +infty )) implies C3 = ( +infty ));
thus L52: (C3 is  real implies (ex B17 being  complex number st (C3 = B17 & C4 = ( - B17 ))))
proof
assume L53: C3 is  real;
consider C5 being  complex number such that L54: (C4 = C5 & C3 = ( - C5 )) by L53 , L49 , L50 , L51;
take ( - C5 );
thus L55: thesis by L54;
end;

L56: (C4 in ( REAL ) implies C4 is  real);
thus L57: (C3 = ( +infty ) implies C4 = ( -infty )) by L56 , L49 , L50 , XXREAL_0:14;
thus L58: thesis by L49 , L51;
end;
end;
definition
let R1 being  ext-real number;
let R2 being  ext-real number;
func R1 - R2 ->  ext-real number equals 
( R1 + ( - R2 ) );
coherence;
end;
registration
let C6 , C7 being  real number;
let C8 , C9 being  complex number;
identify C6 + C7 with C8 + C9 when C6 = C8 , C7 = C9;
compatibility by L38;
end;
registration
let C10 being  real number;
let C11 being  complex number;
identify - C10 with - C11 when C10 = C11;
compatibility by L44;
end;
registration
let C12 being  real number;
cluster ( - C12 ) ->  real;
coherence;
end;
registration
let C13 , C14 being  real number;
cluster ( C13 + C14 ) ->  real;
coherence;
cluster ( C13 - C14 ) ->  real;
coherence;
end;
registration
let C15 being  real number;
let C16 being non  real  ext-real number;
cluster ( C15 + C16 ) -> non  real for number;
coherence
proof
L65: (not C16 in ( REAL ));
L66: (C16 = ( -infty ) or C16 = ( +infty )) by L65 , XXREAL_0:14;
let C17 being number;
assume L67: C17 = ( C15 + C16 );
thus L68: thesis by L67 , L66 , L38;
end;
end;
registration
let C18 , C19 being non  real  positive  ext-real number;
cluster ( C18 + C19 ) -> non  real;
coherence
proof
L70: C18 = ( +infty ) by L8;
thus L71: thesis by L70 , L38;
end;
end;
registration
let C20 , C21 being non  real  negative  ext-real number;
cluster ( C20 + C21 ) -> non  real;
coherence
proof
L73: C20 = ( -infty ) by L11;
thus L74: thesis by L73 , L38;
end;
end;
registration
let C22 being non  real  negative  ext-real number;
let C23 being non  real  positive  ext-real number;
cluster ( C22 + C23 ) ->  zero;
coherence
proof
L76: (C22 = ( -infty ) & C23 = ( +infty )) by L8 , L11;
thus L77: thesis by L76 , L38;
end;
end;
registration
let C24 , C25 being  real number;
let C26 , C27 being  complex number;
identify C24 - C25 with C26 - C27 when C24 = C26 , C25 = C27;
compatibility;
end;
theorem
L80: (for R1 being  ext-real number holds ( R1 + ( 0 ) ) = R1)
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L81: R1 in ( REAL );

reconsider D6 = R1 as  real number by L81;
L82: ( D6 + ( 0 ) ) = D6;
thus L83: thesis by L82;
end;
suppose L84: (R1 = ( -infty ) or R1 = ( +infty ));

thus L85: thesis by L84 , L38;
end;
end;
theorem
L87: ( - ( -infty ) ) = ( +infty ) by L44;
theorem
L88: ( - ( +infty ) ) = ( -infty ) by L44;
L89: ( ( +infty ) + ( +infty ) ) = ( +infty ) by L38;
L90: ( ( -infty ) + ( -infty ) ) = ( -infty ) by L38;
theorem
L91: (for R1 being  ext-real number holds ( R1 + ( - R1 ) ) = ( 0 ))
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L92: R1 = ( -infty );

thus L93: thesis by L92 , L87;
end;
suppose L94: R1 in ( REAL );

reconsider D7 = R1 as  real number by L94;
reconsider D8 = ( - D7 ) as  real number;
L95: ( D7 + D8 ) = ( 0 );
thus L96: thesis by L95;
end;
suppose L97: R1 = ( +infty );

thus L98: thesis by L97 , L88;
end;
end;
theorem
L100: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 + R2 ) = ( 0 ) implies R1 = ( - R2 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L101: ( R1 + R2 ) = ( 0 );
per cases  by XXREAL_0:14;
suppose L102: R1 in ( REAL );

reconsider D9 = R1 as  real number by L102;
L103: ( D9 + R2 ) is  real by L101;
reconsider D10 = R2 as  real number by L103;
L104: ( D9 + D10 ) = ( 0 ) by L101;
L105: D9 = ( - D10 ) by L104;
thus L106: thesis by L105;
end;
suppose L107: R1 = ( -infty );

L108: R2 = ( +infty ) by L107 , L101 , L38;
thus L109: thesis by L108 , L107 , L44;
end;
suppose L110: R1 = ( +infty );

L111: R2 = ( -infty ) by L110 , L101 , L38;
thus L112: thesis by L111 , L110 , L44;
end;
end;
L114: (for R1 being  ext-real number holds (( - R1 ) in ( REAL ) iff R1 in ( REAL )))
proof
let R1 being  ext-real number;
thus L115:now
assume L116: ( - R1 ) in ( REAL );
reconsider D11 = ( - R1 ) as  real number by L116;
L117: ( - D11 ) in ( REAL ) by XREAL_0:def 1;
thus L118: R1 in ( REAL ) by L117;
end;
assume L119: R1 in ( REAL );
reconsider D12 = R1 as  real number by L119;
L120: ( - D12 ) is  real;
thus L121: thesis by L120 , XREAL_0:def 1;
end;
L122: ( - ( ( +infty ) + ( -infty ) ) ) = ( ( +infty ) - ( +infty ) ) by L44
.= ( ( - ( -infty ) ) - ( +infty ) ) by L44;
L123: ( - ( +infty ) ) = ( -infty ) by L44;
L124: (for R1 being  ext-real number holds (R1 in ( REAL ) implies ( - ( R1 + ( +infty ) ) ) = ( ( - ( +infty ) ) + ( - R1 ) )))
proof
let R1 being  ext-real number;
assume L125: R1 in ( REAL );
L126: ( R1 + ( +infty ) ) = ( +infty ) by L125 , L38;
thus L127: thesis by L126 , L125 , L38 , L88;
end;
L128: (for R1 being  ext-real number holds (R1 in ( REAL ) implies ( - ( R1 + ( -infty ) ) ) = ( ( - ( -infty ) ) + ( - R1 ) )))
proof
let R1 being  ext-real number;
assume L129: R1 in ( REAL );
L130: ( R1 + ( -infty ) ) = ( -infty ) by L129 , L38;
thus L131: thesis by L130 , L129 , L38 , L87;
end;
theorem
L132: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ( - ( R1 + R2 ) ) = ( ( - R1 ) + ( - R2 ) )))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L133: (R1 = ( +infty ) & R2 = ( +infty ));

thus L134: ( - ( R1 + R2 ) ) = ( - ( +infty ) ) by L133 , L38
.= ( ( - R1 ) + ( - R2 ) ) by L133 , L38 , L123;
end;
suppose L135: (R1 = ( +infty ) & R2 = ( -infty ));

thus L136: thesis by L135 , L122;
end;
suppose L137: (R1 = ( +infty ) & R2 in ( REAL ));

thus L138: thesis by L137 , L124;
end;
suppose L139: (R1 = ( -infty ) & R2 = ( +infty ));

thus L140: thesis by L139 , L122;
end;
suppose L141: (R1 = ( -infty ) & R2 = ( -infty ));

thus L142: ( - ( R1 + R2 ) ) = ( - ( -infty ) ) by L141 , L38
.= ( ( - R1 ) + ( - R2 ) ) by L141 , L38 , L87;
end;
suppose L143: (R1 = ( -infty ) & R2 in ( REAL ));

thus L144: thesis by L143 , L128;
end;
suppose L145: (R1 in ( REAL ) & R2 = ( +infty ));

thus L146: thesis by L145 , L124;
end;
suppose L147: (R1 in ( REAL ) & R2 = ( -infty ));

thus L148: thesis by L147 , L128;
end;
suppose L149: (R1 in ( REAL ) & R2 in ( REAL ));

reconsider D13 = R1 , D14 = R2 as  real number by L149;
L150: ( - ( R1 + R2 ) ) = ( - ( D13 + D14 ) )
.= ( ( - D13 ) + ( - D14 ) );
thus L151: thesis by L150;
end;
end;
theorem
L153: (for R6 being  ext-real number holds (for R7 being  ext-real number holds (( - R6 ) = ( - R7 ) implies R6 = R7)))
proof
let R6 being  ext-real number;
let R7 being  ext-real number;
assume L154: ( - R6 ) = ( - R7 );
per cases  by XXREAL_0:14;
suppose L155: R6 in ( REAL );

L156:
now
assume L157: (not R7 in ( REAL ));
L158: (R7 = ( +infty ) or R7 = ( -infty )) by L157 , XXREAL_0:14;
thus L159: contradiction by L158 , L154 , L155 , L44;
end;
L160: (ex B18 being  complex number st (R7 = B18 & ( - R7 ) = ( - B18 ))) by L156 , L44;
L161: (ex B19 being  complex number st (R6 = B19 & ( - R6 ) = ( - B19 ))) by L155 , L44;
thus L162: thesis by L161 , L154 , L160;
end;
suppose L163: R6 = ( +infty );

thus L164: thesis by L163 , L154 , L87;
end;
suppose L165: R6 = ( -infty );

L166: ( - ( - R7 ) ) = ( -infty ) by L165 , L154;
thus L167: thesis by L166 , L154;
end;
end;
L169: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 + R2 ) = ( +infty ) implies (R1 = ( +infty ) or R2 = ( +infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L170: ( R1 + R2 ) = ( +infty );
assume L171: ((not R1 = ( +infty )) & (not R2 = ( +infty )));
L172: ((R1 in ( REAL ) & R2 in ( REAL )) or (R1 in ( REAL ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 in ( REAL )) or (R1 = ( -infty ) & R2 = ( -infty ))) by L171 , XXREAL_0:14;
thus L173: thesis by L172 , L170 , L38;
end;
L174: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 + R2 ) = ( -infty ) implies (R1 = ( -infty ) or R2 = ( -infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L175: ( R1 + R2 ) = ( -infty );
assume L176: ((not R1 = ( -infty )) & (not R2 = ( -infty )));
L177: ((R1 in ( REAL ) & R2 in ( REAL )) or (R1 in ( REAL ) & R2 = ( +infty )) or (R1 = ( +infty ) & R2 in ( REAL )) or (R1 = ( +infty ) & R2 = ( +infty ))) by L176 , XXREAL_0:14;
thus L178: thesis by L177 , L175 , L38;
end;
theorem
L179: (for R5 being  real number holds (for R6 being  ext-real number holds (for R7 being  ext-real number holds (( R5 + R6 ) = ( R5 + R7 ) implies R6 = R7))))
proof
let R5 being  real number;
let R6 being  ext-real number;
let R7 being  ext-real number;
assume L180: ( R5 + R6 ) = ( R5 + R7 );
per cases  by XXREAL_0:14;
suppose L181: R6 in ( REAL );

L182:
now
assume L183: (not R7 in ( REAL ));
L184: (R7 = ( +infty ) or R7 = ( -infty )) by L183 , XXREAL_0:14;
thus L185: contradiction by L184 , L180 , L181;
end;
L186: (ex B20 , B21 being  complex number st (R5 = B20 & R7 = B21 & ( R5 + R7 ) = ( B20 + B21 ))) by L182 , L38;
L187: (ex B22 , B23 being  complex number st (R5 = B22 & R6 = B23 & ( R5 + R6 ) = ( B22 + B23 ))) by L181 , L38;
thus L188: thesis by L187 , L180 , L186;
end;
suppose L189: R6 = ( +infty );

L190: ( R5 + R6 ) = ( +infty ) by L189 , L38;
thus L191: thesis by L190 , L180 , L189 , L169;
end;
suppose L192: R6 = ( -infty );

L193: ( R5 + R6 ) = ( -infty ) by L192 , L38;
thus L194: thesis by L193 , L180 , L192 , L174;
end;
end;
theorem
L196: (for R5 being  real number holds (for R6 being  ext-real number holds (for R7 being  ext-real number holds (( R5 - R6 ) = ( R5 - R7 ) implies R6 = R7))))
proof
let R5 being  real number;
let R6 being  ext-real number;
let R7 being  ext-real number;
assume L197: ( R5 - R6 ) = ( R5 - R7 );
L198: ( - R6 ) = ( - R7 ) by L197 , L179;
thus L199: thesis by L198 , L153;
end;
theorem
L200: (for R1 being  ext-real number holds (R1 <> ( +infty ) implies (( ( +infty ) - R1 ) = ( +infty ) & ( R1 - ( +infty ) ) = ( -infty ))))
proof
let R1 being  ext-real number;
assume L201: R1 <> ( +infty );
L202: ( - R1 ) <> ( -infty ) by L201 , L87;
thus L203: ( ( +infty ) - R1 ) = ( +infty ) by L202 , L38;
L204: ( - ( +infty ) ) = ( -infty ) by L44;
thus L205: thesis by L204 , L201 , L38;
end;
theorem
L206: (for R1 being  ext-real number holds (R1 <> ( -infty ) implies (( ( -infty ) - R1 ) = ( -infty ) & ( R1 - ( -infty ) ) = ( +infty ))))
proof
let R1 being  ext-real number;
assume L207: R1 <> ( -infty );
L208:
now
assume L209: ( - R1 ) = ( +infty );
L210: ( - ( - R1 ) ) = ( -infty ) by L209 , L44;
thus L211: contradiction by L210 , L207;
end;
thus L212: ( ( -infty ) - R1 ) = ( -infty ) by L208 , L38;
thus L213: thesis by L207 , L38 , L87;
end;
theorem
L214: (for R1 being  ext-real number holds ( R1 - ( 0 ) ) = R1)
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L215: R1 in ( REAL );

reconsider D15 = R1 as  real number by L215;
L216: ( R1 - ( 0 ) ) = ( D15 - ( 0 ) )
.= R1;
thus L217: thesis by L216;
end;
suppose L218: R1 = ( -infty );

thus L219: thesis by L218 , L206;
end;
suppose L220: R1 = ( +infty );

thus L221: thesis by L220 , L200;
end;
end;
theorem
L223: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 + R2 ) = ( +infty ) implies (R1 = ( +infty ) or R2 = ( +infty ))))) by L169;
theorem
L224: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 + R2 ) = ( -infty ) implies (R1 = ( -infty ) or R2 = ( -infty ))))) by L174;
theorem
L225: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 - R2 ) = ( +infty ) implies (R1 = ( +infty ) or R2 = ( -infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L226: ( R1 - R2 ) = ( +infty );
assume L227: ((not R1 = ( +infty )) & (not R2 = ( -infty )));
L228: ((R1 in ( REAL ) & R2 in ( REAL )) or (R1 in ( REAL ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 in ( REAL )) or (R1 = ( -infty ) & R2 = ( +infty ))) by L227 , XXREAL_0:14;
thus L229: thesis by L228 , L226 , L200 , L206;
end;
theorem
L230: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 - R2 ) = ( -infty ) implies (R1 = ( -infty ) or R2 = ( +infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L231: ( R1 - R2 ) = ( -infty );
assume L232: ((not R1 = ( -infty )) & (not R2 = ( +infty )));
L233: ((R1 in ( REAL ) & R2 in ( REAL )) or (R1 in ( REAL ) & R2 = ( -infty )) or (R1 = ( +infty ) & R2 in ( REAL )) or (R1 = ( +infty ) & R2 = ( -infty ))) by L232 , XXREAL_0:14;
thus L234: thesis by L233 , L231 , L200 , L206;
end;
theorem
L235: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (((not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty )))) & ( R1 + R2 ) in ( REAL )) implies (R1 in ( REAL ) & R2 in ( REAL )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L236: ((not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty )))) & ( R1 + R2 ) in ( REAL ));
L237: (R1 in ( REAL ) or R1 = ( -infty ) or R1 = ( +infty )) by XXREAL_0:14;
L238: (R2 in ( REAL ) or R2 = ( -infty ) or R2 = ( +infty )) by XXREAL_0:14;
assume L239: (not (R1 in ( REAL ) & R2 in ( REAL )));
thus L240: thesis by L239 , L236 , L237 , L238;
end;
theorem
L241: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (((not ((R1 = ( +infty ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 = ( -infty )))) & ( R1 - R2 ) in ( REAL )) implies (R1 in ( REAL ) & R2 in ( REAL )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L242: ((not ((R1 = ( +infty ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 = ( -infty )))) & ( R1 - R2 ) in ( REAL ));
L243: (R1 in ( REAL ) or R1 = ( -infty ) or R1 = ( +infty )) by XXREAL_0:14;
L244: (R2 in ( REAL ) or R2 = ( -infty ) or R2 = ( +infty )) by XXREAL_0:14;
assume L245: (not (R1 in ( REAL ) & R2 in ( REAL )));
thus L246: thesis by L245 , L242 , L243 , L244 , L200 , L206;
end;
theorem
L247: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (R1 is  real implies (( ( R2 - R1 ) + R1 ) = R2 & ( ( R2 + R1 ) - R1 ) = R2))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L248: R1 is  real;
per cases  by L248 , XXREAL_0:14;
suppose L249: (R1 in ( REAL ) & R2 in ( REAL ));

reconsider D16 = R1 , D17 = R2 as  real number by L249;
L250: ( ( R2 + R1 ) - R1 ) = ( ( D17 + D16 ) - D16 )
.= R2;
L251: ( ( R2 - R1 ) + R1 ) = ( ( D17 - D16 ) + D16 )
.= R2;
thus L252: thesis by L251 , L250;
end;
suppose L253: (R1 in ( REAL ) & R2 = ( -infty ));

L254: ( R2 - R1 ) = ( -infty ) by L253 , L38;
thus L255: thesis by L254 , L253 , L38;
end;
suppose L256: (R1 in ( REAL ) & R2 = ( +infty ));

L257: ( R2 - R1 ) = ( +infty ) by L256 , L38;
thus L258: thesis by L257 , L256 , L38;
end;
end;
theorem
L260: (for R1 being  ext-real number holds ((R1 = ( +infty ) iff ( - R1 ) = ( -infty )) & (R1 = ( -infty ) iff ( - R1 ) = ( +infty ))))
proof
let R1 being  ext-real number;
L261: (( - R1 ) = ( +infty ) implies R1 = ( -infty ))
proof
assume L262: ( - R1 ) = ( +infty );
L263: ( - ( - R1 ) ) = ( -infty ) by L262 , L44;
thus L264: thesis by L263;
end;
thus L265: thesis by L261 , L87;
end;
theorem
L266: (for R1 being  ext-real number holds (for R3 being  ext-real number holds (R3 is  real implies R1 = ( ( R1 + R3 ) - R3 ))))
proof
let R1 being  ext-real number;
let R3 being  ext-real number;
assume L267: R3 is  real;
per cases  by XXREAL_0:14;
suppose L268: R1 = ( +infty );

L269: ( R1 + R3 ) = ( +infty ) by L268 , L267 , L38;
thus L270: thesis by L269 , L267 , L268 , L200;
end;
suppose L271: R1 = ( -infty );

L272: ( R1 + R3 ) = ( -infty ) by L271 , L267 , L38;
thus L273: thesis by L272 , L267 , L271 , L206;
end;
suppose L274: R1 is (Element of ( REAL ));

reconsider D18 = R1 , D19 = R3 as  real number by L274 , L267;
L275: ( ( R1 + R3 ) - R3 ) = ( ( D18 + D19 ) - D19 );
thus L276: thesis by L275;
end;
end;
L278: ( - ( +infty ) ) = ( -infty ) by L44;
L279: (for R1 being  ext-real number holds (R1 in ( REAL ) implies ( - ( R1 + ( -infty ) ) ) = ( ( - ( -infty ) ) + ( - R1 ) )))
proof
let R1 being  ext-real number;
L280: ( - ( -infty ) ) = ( +infty ) by L260;
assume L281: R1 in ( REAL );
L282: ( R1 + ( -infty ) ) = ( -infty ) by L281 , L38;
thus L283: thesis by L282 , L281 , L280 , L38;
end;
theorem
L284: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ( - ( R1 + R2 ) ) = ( ( - R2 ) - R1 )))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L285: (R1 = ( +infty ) & R2 = ( +infty ));

thus L286: ( - ( R1 + R2 ) ) = ( - ( +infty ) ) by L285 , L38
.= ( ( - R2 ) - R1 ) by L285 , L38 , L278;
end;
suppose L287: (R1 = ( +infty ) & R2 = ( -infty ));

thus L288: thesis by L287 , L122;
end;
suppose L289: (R1 = ( +infty ) & R2 in ( REAL ));

thus L290: thesis by L289 , L124;
end;
suppose L291: (R1 = ( -infty ) & R2 = ( +infty ));

thus L292: thesis by L291 , L122;
end;
suppose L293: (R1 = ( -infty ) & R2 = ( -infty ));

thus L294: ( - ( R1 + R2 ) ) = ( - ( -infty ) ) by L293 , L38
.= ( ( - R2 ) - R1 ) by L293 , L38 , L87;
end;
suppose L295: (R1 = ( -infty ) & R2 in ( REAL ));

thus L296: thesis by L295 , L279;
end;
suppose L297: (R1 in ( REAL ) & R2 = ( +infty ));

thus L298: thesis by L297 , L124;
end;
suppose L299: (R1 in ( REAL ) & R2 = ( -infty ));

thus L300: thesis by L299 , L279;
end;
suppose L301: (R1 in ( REAL ) & R2 in ( REAL ));

reconsider D20 = R1 , D21 = R2 as  real number by L301;
L302: ( - ( R1 + R2 ) ) = ( - ( D20 + D21 ) )
.= ( ( - D20 ) + ( - D21 ) );
thus L303: thesis by L302;
end;
end;
theorem
L305: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( - ( R1 - R2 ) ) = ( ( - R1 ) + R2 ) & ( - ( R1 - R2 ) ) = ( R2 - R1 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
L306: ( - ( R1 - R2 ) ) = ( ( - ( - R2 ) ) - R1 ) by L284;
thus L307: thesis by L306;
end;
theorem
L308: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( - ( ( - R1 ) + R2 ) ) = ( R1 - R2 ) & ( - ( ( - R1 ) + R2 ) ) = ( R1 + ( - R2 ) ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
L309: ( - ( ( - R1 ) + R2 ) ) = ( ( - ( - R1 ) ) - R2 ) by L284
.= ( R1 - R2 );
thus L310: thesis by L309;
end;
theorem
L311: (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((( 0 ) <= R2 & R2 < ( +infty )) implies R3 = ( ( R3 + R2 ) - R2 ))))
proof
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L312: (( 0 ) <= R2 & R2 < ( +infty ));
L313: R2 in ( REAL ) by L312 , XXREAL_0:14;
thus L314: thesis by L313 , L247;
end;
theorem
L315: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not (R1 = ( +infty ) & R2 = ( -infty ))) & (not (R1 = ( -infty ) & R2 = ( +infty ))) & (not ((R2 = ( +infty ) & R3 = ( -infty )) or (R2 = ( -infty ) & R3 = ( +infty )))) & (not ((R1 = ( +infty ) & R3 = ( -infty )) or (R1 = ( -infty ) & R3 = ( +infty ))))) implies ( ( R1 + R2 ) + R3 ) = ( R1 + ( R2 + R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L316: ((not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty )))) & (not ((R2 = ( +infty ) & R3 = ( -infty )) or (R2 = ( -infty ) & R3 = ( +infty )))) & (not ((R1 = ( +infty ) & R3 = ( -infty )) or (R1 = ( -infty ) & R3 = ( +infty )))));
per cases  by L316 , XXREAL_0:14;
suppose L317: (R1 in ( REAL ) & R2 in ( REAL ) & R3 in ( REAL ));

reconsider D22 = R1 , D23 = R2 , D24 = R3 as  real number by L317;
L318: (( ( D22 + D23 ) + D24 ) = ( ( R1 + R2 ) + R3 ) & ( D22 + ( D23 + D24 ) ) = ( R1 + ( R2 + R3 ) ));
thus L319: thesis by L318;
end;
suppose L320: (R1 in ( REAL ) & R2 = ( +infty ) & R3 in ( REAL ));

L321: (( R1 + R2 ) = ( +infty ) & ( R2 + R3 ) = ( +infty )) by L320 , L38;
thus L322: thesis by L321 , L320;
end;
suppose L323: (R1 in ( REAL ) & R2 = ( -infty ) & R3 in ( REAL ));

L324: (( R1 + R2 ) = ( -infty ) & ( R2 + R3 ) = ( -infty )) by L323 , L38;
thus L325: thesis by L324 , L323;
end;
suppose L326: (R1 = ( -infty ) & R2 in ( REAL ) & R3 in ( REAL ));

L327: ( R1 + R2 ) = ( -infty ) by L326 , L38;
L328: ( ( R1 + R2 ) + R3 ) = ( -infty ) by L327 , L326 , L38;
thus L329: thesis by L328 , L326 , L38;
end;
suppose L330: (R1 = ( +infty ) & R2 in ( REAL ) & R3 in ( REAL ));

L331: ( R1 + R2 ) = ( +infty ) by L330 , L38;
L332: ( ( R1 + R2 ) + R3 ) = ( +infty ) by L331 , L330 , L38;
thus L333: thesis by L332 , L330 , L38;
end;
suppose L334: (R1 in ( REAL ) & R2 in ( REAL ) & R3 = ( +infty ));

L335: ( R2 + R3 ) = ( +infty ) by L334 , L38;
L336: ( R1 + ( R2 + R3 ) ) = ( +infty ) by L335 , L334 , L38;
thus L337: thesis by L336 , L334 , L38;
end;
suppose L338: (R1 in ( REAL ) & R2 in ( REAL ) & R3 = ( -infty ));

L339: ( R2 + R3 ) = ( -infty ) by L338 , L38;
L340: ( R1 + ( R2 + R3 ) ) = ( -infty ) by L339 , L338 , L38;
thus L341: thesis by L340 , L338 , L38;
end;
suppose L342: (R1 = ( +infty ) & R2 = ( +infty ) & R3 in ( REAL ));

L343: ( R1 + R2 ) = ( +infty ) by L342 , L38;
L344: ( ( R1 + R2 ) + R3 ) = ( +infty ) by L343 , L342 , L38;
L345: ( R2 + R3 ) <> ( -infty ) by L342 , L38;
thus L346: thesis by L345 , L342 , L344 , L38;
end;
suppose L347: (R1 in ( REAL ) & R2 = ( -infty ) & R3 = ( -infty ));

L348: ( R1 + R2 ) = ( -infty ) by L347 , L38;
L349: ( ( R1 + R2 ) + R3 ) = ( -infty ) by L348 , L347 , L38;
thus L350: thesis by L349 , L347 , L348;
end;
suppose L351: (R1 = ( -infty ) & R2 = ( -infty ) & R3 in ( REAL ));

L352: ( R1 + R2 ) = ( -infty ) by L351 , L38;
L353: ( ( R1 + R2 ) + R3 ) = ( -infty ) by L352 , L351 , L38;
thus L354: thesis by L353 , L351 , L352;
end;
suppose L355: ((R1 = ( -infty ) & R2 in ( REAL ) & R3 = ( -infty )) or (R1 = ( -infty ) & R2 = ( -infty ) & R3 = ( -infty )) or (R1 = ( +infty ) & R2 in ( REAL ) & R3 = ( +infty )) or (R1 = ( +infty ) & R2 = ( +infty ) & R3 = ( +infty )));

thus L356: thesis by L355;
end;
suppose L357: (R1 in ( REAL ) & R2 = ( +infty ) & R3 = ( +infty ));

L358: (( R1 + R2 ) = ( +infty ) & ( R2 + R3 ) = ( +infty )) by L357 , L38;
thus L359: thesis by L358 , L357;
end;
end;
theorem
L361: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not (R1 = ( +infty ) & R2 = ( -infty ))) & (not (R1 = ( -infty ) & R2 = ( +infty ))) & (not (R2 = ( +infty ) & R3 = ( +infty ))) & (not (R2 = ( -infty ) & R3 = ( -infty ))) & (not (R1 = ( +infty ) & R3 = ( +infty ))) & (not (R1 = ( -infty ) & R3 = ( -infty )))) implies ( ( R1 + R2 ) - R3 ) = ( R1 + ( R2 - R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L362: ((not (R1 = ( +infty ) & R2 = ( -infty ))) & (not (R1 = ( -infty ) & R2 = ( +infty ))))
and
L363: ((not (R2 = ( +infty ) & R3 = ( +infty ))) & (not (R2 = ( -infty ) & R3 = ( -infty ))))
and
L364: ((not (R1 = ( +infty ) & R3 = ( +infty ))) & (not (R1 = ( -infty ) & R3 = ( -infty ))));
L365: ((not (R1 = ( +infty ) & ( - R3 ) = ( -infty ))) & (not (R1 = ( -infty ) & ( - R3 ) = ( +infty )))) by L364 , L260;
L366: ((not (R2 = ( +infty ) & ( - R3 ) = ( -infty ))) & (not (R2 = ( -infty ) & ( - R3 ) = ( +infty )))) by L363 , L260;
thus L367: thesis by L366 , L362 , L365 , L315;
end;
theorem
L368: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not (R1 = ( +infty ) & R2 = ( +infty ))) & (not (R1 = ( -infty ) & R2 = ( -infty ))) & (not (R2 = ( +infty ) & R3 = ( -infty ))) & (not (R2 = ( -infty ) & R3 = ( +infty ))) & (not (R1 = ( +infty ) & R3 = ( +infty ))) & (not (R1 = ( -infty ) & R3 = ( -infty )))) implies ( ( R1 - R2 ) - R3 ) = ( R1 - ( R2 + R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L369: (not (R1 = ( +infty ) & R2 = ( +infty )))
and
L370: (not (R1 = ( -infty ) & R2 = ( -infty )))
and
L371: (not (R2 = ( +infty ) & R3 = ( -infty )))
and
L372: (not (R2 = ( -infty ) & R3 = ( +infty )))
and
L373: (not (R1 = ( +infty ) & R3 = ( +infty )))
and
L374: (not (R1 = ( -infty ) & R3 = ( -infty )));
per cases ;
suppose L375: R1 = ( +infty );

L376: ( R1 - R2 ) = ( +infty ) by L375 , L369 , L200;
L377: ( ( R1 - R2 ) - R3 ) = ( +infty ) by L376 , L373 , L375 , L200;
L378: ( R2 + R3 ) <> ( +infty ) by L369 , L373 , L375 , L169;
thus L379: thesis by L378 , L375 , L377 , L200;
end;
suppose L380: R1 = ( -infty );

L381: ( R1 - R2 ) = ( -infty ) by L380 , L370 , L206;
L382: ( ( R1 - R2 ) - R3 ) = ( -infty ) by L381 , L374 , L380 , L206;
L383: ( R2 + R3 ) <> ( -infty ) by L370 , L374 , L380 , L174;
thus L384: thesis by L383 , L380 , L382 , L206;
end;
suppose L385: (R1 <> ( +infty ) & R1 <> ( -infty ));

L386: R1 in ( REAL ) by L385 , XXREAL_0:14;
reconsider D25 = R1 as  real number by L386;
per cases ;
suppose L387: R2 = ( +infty );

L388: (( R1 - R2 ) = ( -infty ) & ( R2 + R3 ) = ( +infty )) by L387 , L371 , L385 , L38 , L200;
thus L389: thesis by L388 , L371 , L387 , L206;
end;
suppose L390: R2 = ( -infty );

L391: (( R1 - R2 ) = ( +infty ) & ( R2 + R3 ) = ( -infty )) by L390 , L372 , L385 , L38 , L206;
thus L392: thesis by L391 , L372 , L390 , L200;
end;
suppose L393: (R2 <> ( +infty ) & R2 <> ( -infty ));

L394: R2 in ( REAL ) by L393 , XXREAL_0:14;
reconsider D26 = R2 as  real number by L394;
L395: ( R1 - R2 ) = ( D25 - D26 );
per cases ;
suppose L396: R3 = ( +infty );

L397: (( ( R1 - R2 ) - R3 ) = ( -infty ) & ( R2 + R3 ) = ( +infty )) by L396 , L395 , L38 , L200;
thus L398: thesis by L397 , L385 , L200;
end;
suppose L399: R3 = ( -infty );

L400: (( ( R1 - R2 ) - R3 ) = ( +infty ) & ( R2 + R3 ) = ( -infty )) by L399 , L395 , L38 , L206;
thus L401: thesis by L400 , L385 , L206;
end;
suppose L402: (R3 <> ( +infty ) & R3 <> ( -infty ));

L403: R3 in ( REAL ) by L402 , XXREAL_0:14;
reconsider D27 = R3 as  real number by L403;
L404: (( ( R1 - R2 ) - R3 ) = ( ( D25 - D26 ) - D27 ) & ( R1 - ( R2 + R3 ) ) = ( D25 - ( D26 + D27 ) ));
thus L405: thesis by L404;
end;
end;
end;
end;
theorem
L409: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not (R1 = ( +infty ) & R2 = ( +infty ))) & (not (R1 = ( -infty ) & R2 = ( -infty ))) & (not (R2 = ( +infty ) & R3 = ( +infty ))) & (not (R2 = ( -infty ) & R3 = ( -infty ))) & (not (R1 = ( +infty ) & R3 = ( -infty ))) & (not (R1 = ( -infty ) & R3 = ( +infty )))) implies ( ( R1 - R2 ) + R3 ) = ( R1 - ( R2 - R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L410: (not (R1 = ( +infty ) & R2 = ( +infty )))
and
L411: (not (R1 = ( -infty ) & R2 = ( -infty )))
and
L412: (not (R2 = ( +infty ) & R3 = ( +infty )))
and
L413: (not (R2 = ( -infty ) & R3 = ( -infty )))
and
L414: (not (R1 = ( +infty ) & R3 = ( -infty )))
and
L415: (not (R1 = ( -infty ) & R3 = ( +infty )));
per cases ;
suppose L416: R1 = ( +infty );

L417: ( R1 - R2 ) = ( +infty ) by L416 , L410 , L200;
L418: ( ( R1 - R2 ) + R3 ) = ( +infty ) by L417 , L414 , L416 , L38;
L419: ( R2 - R3 ) <> ( +infty ) by L410 , L414 , L416 , L225;
thus L420: thesis by L419 , L416 , L418 , L200;
end;
suppose L421: R1 = ( -infty );

L422: ( R1 - R2 ) = ( -infty ) by L421 , L411 , L206;
L423: ( ( R1 - R2 ) + R3 ) = ( -infty ) by L422 , L415 , L421 , L38;
L424: ( R2 - R3 ) <> ( -infty ) by L411 , L415 , L421 , L230;
thus L425: thesis by L424 , L421 , L423 , L206;
end;
suppose L426: (R1 <> ( +infty ) & R1 <> ( -infty ));

L427: R1 in ( REAL ) by L426 , XXREAL_0:14;
reconsider D28 = R1 as  real number by L427;
per cases ;
suppose L428: R2 = ( +infty );

L429: (( R1 - R2 ) = ( -infty ) & ( R2 - R3 ) = ( +infty )) by L428 , L412 , L426 , L200;
thus L430: thesis by L429 , L412 , L428 , L38;
end;
suppose L431: R2 = ( -infty );

L432: (( R1 - R2 ) = ( +infty ) & ( R2 - R3 ) = ( -infty )) by L431 , L413 , L426 , L206;
thus L433: thesis by L432 , L413 , L431 , L38;
end;
suppose L434: (R2 <> ( +infty ) & R2 <> ( -infty ));

L435: R2 in ( REAL ) by L434 , XXREAL_0:14;
reconsider D29 = R2 as  real number by L435;
L436: ( R1 - R2 ) = ( D28 - D29 );
per cases ;
suppose L437: R3 = ( +infty );

L438: (( ( R1 - R2 ) + R3 ) = ( +infty ) & ( R2 - R3 ) = ( -infty )) by L437 , L436 , L38 , L200;
thus L439: thesis by L438 , L426 , L206;
end;
suppose L440: R3 = ( -infty );

L441: (( ( R1 - R2 ) + R3 ) = ( -infty ) & ( R2 - R3 ) = ( +infty )) by L440 , L436 , L38 , L206;
thus L442: thesis by L441 , L426 , L200;
end;
suppose L443: (R3 <> ( +infty ) & R3 <> ( -infty ));

L444: R3 in ( REAL ) by L443 , XXREAL_0:14;
reconsider D30 = R3 as  real number by L444;
L445: (( ( R1 - R2 ) + R3 ) = ( ( D28 - D29 ) + D30 ) & ( R1 - ( R2 - R3 ) ) = ( D28 - ( D29 - D30 ) ));
thus L446: thesis by L445;
end;
end;
end;
end;
theorem
L450: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R3 is  real implies ( ( R3 + R1 ) - ( R3 + R2 ) ) = ( R1 - R2 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L451: R3 is  real;
per cases  by L451 , XXREAL_0:14;
suppose L452: R1 = ( -infty );

per cases  by XXREAL_0:14;
suppose L453: R2 = ( -infty );

L454: ( ( R3 + ( -infty ) ) - ( R3 + ( -infty ) ) ) = ( ( -infty ) - ( R3 + ( -infty ) ) ) by L451 , L38
.= ( ( -infty ) - ( -infty ) ) by L451 , L38;
thus L455: thesis by L454 , L452 , L453;
end;
suppose L456: R2 = ( +infty );

L457: ( ( R3 + ( -infty ) ) - ( R3 + ( +infty ) ) ) = ( ( -infty ) - ( R3 + ( +infty ) ) ) by L451 , L38
.= ( ( -infty ) - ( +infty ) ) by L451 , L38;
thus L458: thesis by L457 , L452 , L456;
end;
suppose L459: R2 in ( REAL );

consider C28 , C29 being  complex number such that L460: (R3 = C28 & R2 = C29) and L461: ( R3 + R2 ) = ( C28 + C29 ) by L459 , L451 , L38;
reconsider D31 = C28 , D32 = C29 as  real number by L451 , L459 , L460;
L462: ( D31 + D32 ) in ( REAL ) by XREAL_0:def 1;
L463: ( ( R3 + ( -infty ) ) - ( R3 + R2 ) ) = ( ( -infty ) - ( R3 + R2 ) ) by L451 , L38
.= ( -infty ) by L460 , L462 , L38
.= ( ( -infty ) - R2 ) by L459 , L38;
thus L464: thesis by L463 , L452;
end;
end;
suppose L466: R2 = ( +infty );

per cases  by XXREAL_0:14;
suppose L467: R1 = ( -infty );

L468: ( ( R3 + ( -infty ) ) - ( R3 + ( +infty ) ) ) = ( ( R3 + ( -infty ) ) - ( +infty ) ) by L451 , L38
.= ( ( -infty ) - ( +infty ) ) by L451 , L38;
thus L469: thesis by L468 , L466 , L467;
end;
suppose L470: R1 = ( +infty );

L471: ( ( R3 + ( +infty ) ) - ( R3 + ( +infty ) ) ) = ( ( R3 + ( +infty ) ) - ( +infty ) ) by L451 , L38
.= ( ( +infty ) - ( +infty ) ) by L451 , L38;
thus L472: thesis by L471 , L466 , L470;
end;
suppose L473: R1 in ( REAL );

consider C30 , C31 being  complex number such that L474: (R3 = C30 & R1 = C31) and L475: ( R3 + R1 ) = ( C30 + C31 ) by L473 , L451 , L38;
reconsider D33 = C30 , D34 = C31 as  real number by L451 , L473 , L474;
L476: ( D33 + D34 ) in ( REAL ) by XREAL_0:def 1;
L477: ( - ( +infty ) ) = ( -infty ) by L44;
L478: ( ( R3 + R1 ) - ( R3 + ( +infty ) ) ) = ( ( R3 + R1 ) - ( +infty ) ) by L451 , L38
.= ( ( R3 + R1 ) + ( -infty ) ) by L44
.= ( -infty ) by L474 , L476 , L38
.= ( R1 + ( - ( +infty ) ) ) by L473 , L477 , L38;
thus L479: thesis by L478 , L466;
end;
end;
suppose L481: (R1 in ( REAL ) & R2 in ( REAL ) & R3 in ( REAL ));

reconsider D35 = R1 , D36 = R2 , D37 = R3 as  real number by L481;
L482: ( ( R3 + R1 ) - ( R3 + R2 ) ) = ( ( D35 + D37 ) - ( D37 + D36 ) )
.= ( D35 - D36 )
.= ( R1 - R2 );
thus L483: thesis by L482;
end;
suppose L484: (R1 = ( +infty ) & R2 in ( REAL ) & R3 in ( REAL ));

reconsider D38 = R3 , D39 = R2 as  real number by L484;
L485: ( R3 + R2 ) = ( D38 + D39 );
L486: (( R3 + R1 ) = ( +infty ) & ( R1 - R2 ) = ( +infty )) by L484 , L38;
thus L487: thesis by L486 , L485 , L200;
end;
suppose L488: (R1 in ( REAL ) & R2 = ( -infty ) & R3 in ( REAL ));

reconsider D40 = R3 , D41 = R1 as  real number by L488;
L489: (( R3 + R1 ) = ( D40 + D41 ) & ( R3 + R2 ) = ( -infty )) by L488 , L38;
L490: ( ( R3 + R1 ) - ( R3 + R2 ) ) = ( +infty ) by L489 , L206
.= ( R1 - R2 ) by L488 , L206;
thus L491: thesis by L490;
end;
suppose L492: (R1 = ( +infty ) & R2 = ( -infty ) & R3 in ( REAL ));

L493: (( R3 + R2 ) = ( -infty ) & (not ( R3 + R1 ) = ( -infty ))) by L492 , L38;
L494: ( ( R3 + R1 ) - ( R3 + R2 ) ) = ( +infty ) by L493 , L206
.= ( R1 - R2 ) by L492 , L206;
thus L495: thesis by L494;
end;
end;
theorem
L497: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R2 is  real implies ( ( R3 - R2 ) + ( R2 - R1 ) ) = ( R3 - R1 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L498: R2 is  real;
thus L499: ( ( R3 - R2 ) + ( R2 - R1 ) ) = ( ( R3 - R2 ) - ( R1 - R2 ) ) by L308
.= ( R3 - R1 ) by L498 , L450;
end;
begin
L500: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R1 <= R2 implies ( R1 + R3 ) <= ( R2 + R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L501: R1 <= R2;
per cases  by XXREAL_0:14;
suppose L502: (R1 in ( REAL ) & R2 in ( REAL ));

per cases  by XXREAL_0:14;
suppose L503: R3 = ( -infty );

L504: ( -infty ) <= ( R2 + R3 ) by XXREAL_0:5;
thus L505: thesis by L504 , L502 , L503 , L38;
end;
suppose L506: R3 in ( REAL );

reconsider D42 = R1 , D43 = R2 , D44 = R3 as  real number by L506 , L502;
L507: ( D42 + D44 ) <= ( D43 + D44 ) by L501 , XREAL_1:6;
thus L508: thesis by L507;
end;
suppose L509: R3 = ( +infty );

L510: ( R1 + R3 ) <= ( +infty ) by XXREAL_0:3;
thus L511: thesis by L510 , L502 , L509 , L38;
end;
end;
suppose L513: (R1 in ( REAL ) & R2 = ( +infty ));

per cases  by XXREAL_0:14;
suppose L514: R3 = ( -infty );

L515: ( -infty ) <= ( R2 + R3 ) by XXREAL_0:5;
thus L516: thesis by L515 , L513 , L514 , L38;
end;
suppose L517: R3 in ( REAL );

L518: ( R1 + R3 ) <= ( +infty ) by XXREAL_0:3;
thus L519: thesis by L518 , L513 , L517 , L38;
end;
suppose L520: R3 = ( +infty );

thus L521: thesis by L520 , L513 , L89 , XXREAL_0:3;
end;
end;
suppose L523: (R1 = ( -infty ) & R2 in ( REAL ));

per cases  by XXREAL_0:14;
suppose L524: R3 = ( -infty );

thus L525: thesis by L524 , L523 , L90 , XXREAL_0:5;
end;
suppose L526: R3 in ( REAL );

L527: ( -infty ) <= ( R2 + R3 ) by XXREAL_0:5;
thus L528: thesis by L527 , L523 , L526 , L38;
end;
suppose L529: R3 = ( +infty );

L530: ( R1 + R3 ) <= ( +infty ) by XXREAL_0:3;
thus L531: thesis by L530 , L523 , L529 , L38;
end;
end;
suppose L533: (R1 = ( -infty ) & R2 = ( +infty ));

per cases  by XXREAL_0:14;
suppose L534: R3 = ( -infty );

thus L535: thesis by L534 , L533 , L90;
end;
suppose L536: R3 in ( REAL );

L537: ( -infty ) <= ( R2 + R3 ) by XXREAL_0:5;
thus L538: thesis by L537 , L533 , L536 , L38;
end;
suppose L539: R3 = ( +infty );

thus L540: thesis by L539 , L533 , L89;
end;
end;
suppose L542: R1 = ( +infty );

thus L543: thesis by L542 , L501 , XXREAL_0:4;
end;
suppose L544: R2 = ( -infty );

thus L545: thesis by L544 , L501 , XXREAL_0:6;
end;
end;
L547: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((R1 >= ( 0 ) & R2 > ( 0 )) implies ( R1 + R2 ) > ( 0 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L548: R1 >= ( 0 );
L549: ( R1 + R2 ) >= ( ( 0 ) + R2 ) by L548 , L500;
thus L550: thesis by L549 , L80;
end;
L551: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((R1 <= ( 0 ) & R2 < ( 0 )) implies ( R1 + R2 ) < ( 0 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L552: R1 <= ( 0 );
L553: ( R1 + R2 ) <= ( ( 0 ) + R2 ) by L552 , L500;
thus L554: thesis by L553 , L80;
end;
registration
let C32 , C33 being non  negative  ext-real number;
cluster ( C32 + C33 ) -> non  negative;
coherence
proof
per cases ;
suppose L555: C32 = ( 0 );

thus L556: ( C32 + C33 ) >= ( 0 ) by L555 , L80;
end;
suppose L557: C32 > ( 0 );

thus L558: ( C32 + C33 ) >= ( 0 ) by L557 , L547;
end;
end;
end;
registration
let C34 , C35 being non  positive  ext-real number;
cluster ( C34 + C35 ) -> non  positive;
coherence
proof
per cases ;
suppose L561: C34 = ( 0 );

thus L562: ( C34 + C35 ) <= ( 0 ) by L561 , L80;
end;
suppose L563: C34 < ( 0 );

thus L564: ( C34 + C35 ) <= ( 0 ) by L563 , L551;
end;
end;
end;
registration
let C36 being  positive  ext-real number;
let C37 being non  negative  ext-real number;
cluster ( C36 + C37 ) ->  positive;
coherence by L547;
cluster ( C37 + C36 ) ->  positive;
coherence;
end;
registration
let C38 being  negative  ext-real number;
let C39 being non  positive  ext-real number;
cluster ( C38 + C39 ) ->  negative;
coherence by L551;
cluster ( C39 + C38 ) ->  negative;
coherence;
end;
registration
let C40 being non  positive  ext-real number;
cluster ( - C40 ) -> non  negative;
coherence
proof
assume L569: ( - C40 ) < ( 0 );
L570: ( ( - C40 ) - ( - C40 ) ) < ( 0 ) by L569;
thus L571: contradiction by L570 , L91;
end;
end;
registration
let C41 being non  negative  ext-real number;
cluster ( - C41 ) -> non  positive;
coherence
proof
assume L573: ( - C41 ) > ( 0 );
L574: ( ( - C41 ) - ( - C41 ) ) > ( 0 ) by L573;
thus L575: contradiction by L574 , L91;
end;
end;
registration
let C42 being  positive  ext-real number;
cluster ( - C42 ) ->  negative;
coherence
proof
assume L577: ( - C42 ) >= ( 0 );
L578: ( ( - C42 ) - ( - C42 ) ) > ( 0 ) by L577;
thus L579: contradiction by L578 , L91;
end;
end;
registration
let C43 being  negative  ext-real number;
cluster ( - C43 ) ->  positive;
coherence
proof
assume L581: ( - C43 ) <= ( 0 );
L582: ( ( - C43 ) - ( - C43 ) ) < ( 0 ) by L581;
thus L583: contradiction by L582 , L91;
end;
end;
registration
let C44 being non  negative  ext-real number;
let C45 being non  positive  ext-real number;
cluster ( C44 - C45 ) -> non  negative;
coherence;
cluster ( C45 - C44 ) -> non  positive;
coherence;
end;
registration
let C46 being  positive  ext-real number;
let C47 being non  positive  ext-real number;
cluster ( C46 - C47 ) ->  positive;
coherence;
cluster ( C47 - C46 ) ->  negative;
coherence;
end;
registration
let C48 being  negative  ext-real number;
let C49 being non  negative  ext-real number;
cluster ( C48 - C49 ) ->  negative;
coherence;
cluster ( C49 - C48 ) ->  positive;
coherence;
end;
L588: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (R1 <= R2 implies ( - R2 ) <= ( - R1 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L589: R1 <= R2;
per cases ;
case that L590: ( - R2 ) in ( REAL )
and
L591: ( - R1 ) in ( REAL );
L592: R1 in ( REAL ) by L591 , L114;
consider C50 being  complex number such that L593: R1 = C50 and L594: ( - R1 ) = ( - C50 ) by L592 , L44;
L595: R2 in ( REAL ) by L590 , L114;
consider C51 being  complex number such that L596: R2 = C51 and L597: ( - R2 ) = ( - C51 ) by L595 , L44;
L598: (R1 in ( REAL ) & R2 in ( REAL )) by L590 , L591 , L114;
reconsider D45 = C50 , D46 = C51 as  real number by L598 , L596 , L593;
reconsider D47 = ( - D46 ) , D48 = ( - D45 ) as (Element of ( REAL )) by XREAL_0:def 1;
take D47;
take D48;
thus L599: (D47 = ( - R2 ) & D48 = ( - R1 )) by L597 , L594;
thus L600: thesis by L589 , L596 , L593 , XREAL_1:24;
end;
case L601: (not (( - R2 ) in ( REAL ) & ( - R1 ) in ( REAL )));
L602: (not (R2 in ( REAL ) & R1 in ( REAL ))) by L601 , L114;
L603: (R1 = ( -infty ) or R2 = ( +infty )) by L602 , L589 , L1;
thus L604: thesis by L603 , L44;
end;
end;
theorem
L606: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R1 <= R2 implies ( R1 + R3 ) <= ( R2 + R3 ))))) by L500;
theorem
L607: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (for R4 being  ext-real number holds ((R1 <= R2 & R3 <= R4) implies ( R1 + R3 ) <= ( R2 + R4 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
let R4 being  ext-real number;
assume that
L608: R1 <= R2
and
L609: R3 <= R4;
per cases ;
suppose L610: (R1 = ( +infty ) & R3 = ( -infty ));

L611: (R4 <> ( -infty ) implies ( ( +infty ) + R4 ) = ( +infty )) by L38;
L612: R2 = ( +infty ) by L608 , L610 , XXREAL_0:4;
thus L613: thesis by L612 , L610 , L611;
end;
suppose L614: (R1 = ( -infty ) & R3 = ( +infty ));

L615: (R2 <> ( -infty ) implies ( ( +infty ) + R2 ) = ( +infty )) by L38;
L616: R4 = ( +infty ) by L609 , L614 , XXREAL_0:4;
thus L617: thesis by L616 , L614 , L615;
end;
suppose L618: (R2 = ( +infty ) & R4 = ( -infty ));

L619: (R1 <> ( +infty ) implies ( ( -infty ) + R1 ) = ( -infty )) by L38;
L620: R3 = ( -infty ) by L609 , L618 , XXREAL_0:6;
thus L621: thesis by L620 , L618 , L619;
end;
suppose L622: (R2 = ( -infty ) & R4 = ( +infty ));

L623: (R3 <> ( +infty ) implies ( ( -infty ) + R3 ) = ( -infty )) by L38;
L624: R1 = ( -infty ) by L608 , L622 , XXREAL_0:6;
thus L625: thesis by L624 , L622 , L623;
end;
suppose L626: ((not ((R1 = ( +infty ) & R3 = ( -infty )) or (R1 = ( -infty ) & R3 = ( +infty )))) & (not ((R2 = ( +infty ) & R4 = ( -infty )) or (R2 = ( -infty ) & R4 = ( +infty )))));

reconsider D49 = ( R1 + R3 ) , D50 = ( R2 + R4 ) as (Element of ( ExtREAL )) by XXREAL_0:def 1;
L627: (not (D49 = ( +infty ) & D50 = ( -infty )))
proof
assume that
L628: D49 = ( +infty )
and
L629: D50 = ( -infty );
L630: (R1 = ( +infty ) or R3 = ( +infty )) by L628 , L169;
thus L631: thesis by L630 , L608 , L609 , L626 , L629 , L174 , XXREAL_0:4;
end;
L632: ((D49 in ( REAL ) & D50 in ( REAL )) implies D49 <= D50)
proof
assume L633: (D49 in ( REAL ) & D50 in ( REAL ));
L634: (R3 in ( REAL ) & R4 in ( REAL )) by L633 , L626 , L235;
L635: (R1 in ( REAL ) & R2 in ( REAL )) by L626 , L633 , L235;
consider C52 , C53 , C54 , C55 being  real number such that L636: (C52 = R1 & C53 = R2 & C54 = R3 & C55 = R4) and L637: (C52 <= C53 & C54 <= C55) by L635 , L608 , L609 , L634;
L638: (( C52 + C54 ) <= ( C54 + C53 ) & ( C54 + C53 ) <= ( C55 + C53 )) by L637 , XREAL_1:6;
thus L639: thesis by L638 , L636 , XXREAL_0:2;
end;
L640: ((D49 = ( +infty ) & D50 in ( REAL )) implies D49 <= D50)
proof
assume that
L641: D49 = ( +infty )
and
L642: D50 in ( REAL );
L643: (R1 = ( +infty ) or R3 = ( +infty )) by L641 , L169;
L644: (R2 = ( +infty ) or R4 = ( +infty )) by L643 , L608 , L609 , XXREAL_0:4;
L645: D50 = ( +infty ) by L644 , L626 , L38;
thus L646: thesis by L645 , XXREAL_0:4;
end;
L647: ((D49 in ( REAL ) & D50 = ( -infty )) implies D49 <= D50)
proof
assume that
L648: D49 in ( REAL )
and
L649: D50 = ( -infty );
L650: (R2 = ( -infty ) or R4 = ( -infty )) by L649 , L174;
L651: (R1 = ( -infty ) or R3 = ( -infty )) by L650 , L608 , L609 , XXREAL_0:6;
L652: D49 = ( -infty ) by L651 , L626 , L38;
thus L653: thesis by L652 , XXREAL_0:5;
end;
L654: ((D49 in ( REAL ) & D50 in ( REAL )) or (D49 in ( REAL ) & D50 = ( +infty )) or (D49 in ( REAL ) & D50 = ( -infty )) or (D49 = ( +infty ) & D50 in ( REAL )) or (D49 = ( +infty ) & D50 = ( +infty )) or (D49 = ( +infty ) & D50 = ( -infty )) or (D49 = ( -infty ) & D50 in ( REAL )) or (D49 = ( -infty ) & D50 = ( +infty )) or (D49 = ( -infty ) & D50 = ( -infty ))) by XXREAL_0:14;
thus L655: thesis by L654 , L632 , L647 , L640 , L627 , XXREAL_0:4 , XXREAL_0:5;
end;
end;
theorem
L657: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (for R4 being  ext-real number holds ((R1 <= R2 & R3 <= R4) implies ( R1 - R4 ) <= ( R2 - R3 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
let R4 being  ext-real number;
assume that
L658: R1 <= R2
and
L659: R3 <= R4;
L660: ( - R4 ) <= ( - R3 ) by L659 , L588;
thus L661: thesis by L660 , L658 , L607;
end;
theorem
L662: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (R1 <= R2 iff ( - R2 ) <= ( - R1 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
thus L663: (R1 <= R2 implies ( - R2 ) <= ( - R1 )) by L588;
L664: (( - R2 ) <= ( - R1 ) implies ( - ( - R1 ) ) <= ( - ( - R2 ) )) by L588;
thus L665: thesis by L664;
end;
theorem
L666: (for R1 being  ext-real number holds (for R3 being  ext-real number holds (( 0 ) <= R3 implies R1 <= ( R1 + R3 ))))
proof
let R1 being  ext-real number;
let R3 being  ext-real number;
assume L667: ( 0 ) <= R3;
L668: ( R1 + ( 0 ) ) <= ( R1 + R3 ) by L667 , L607;
thus L669: thesis by L668 , L80;
end;
theorem
L670: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (R1 <= R2 implies ( R2 - R1 ) >= ( 0 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L671: R1 <= R2;
L672: ( - R2 ) <= ( - R1 ) by L671 , L588;
L673: ( ( - R2 ) + R2 ) <= ( R2 + ( - R1 ) ) by L672 , L607;
thus L674: thesis by L673 , L91;
end;
theorem
L675: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((((R3 = ( -infty ) & R2 = ( +infty )) implies R1 <= ( 0 )) & ((R3 = ( +infty ) & R2 = ( -infty )) implies R1 <= ( 0 ))) implies (( R1 - R2 ) <= R3 implies R1 <= ( R3 + R2 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L676: ((R3 = ( -infty ) & R2 = ( +infty )) implies R1 <= ( 0 ))
and
L677: ((R3 = ( +infty ) & R2 = ( -infty )) implies R1 <= ( 0 ))
and
L678: ( R1 - R2 ) <= R3;
per cases  by XXREAL_0:14;
suppose L679: R3 = ( -infty );

per cases  by L678 , L679 , L230 , XXREAL_0:6;
suppose L680: R1 = ( -infty );

thus L681: thesis by L680 , XXREAL_0:5;
end;
suppose L682: R2 = ( +infty );

thus L683: thesis by L682 , L676 , L679;
end;
end;
suppose L685: R3 = ( +infty );

per cases ;
suppose L686: R2 = ( -infty );

thus L687: thesis by L686 , L677 , L685;
end;
suppose L688: R2 <> ( -infty );

L689: ( R3 + R2 ) = ( +infty ) by L688 , L685 , L38;
thus L690: thesis by L689 , XXREAL_0:3;
end;
end;
suppose L692: R3 in ( REAL );

per cases  by L678 , L692 , XXREAL_0:13;
suppose L693: ( R1 - R2 ) in ( REAL );

per cases  by L693 , L241;
suppose L694: R2 = ( +infty );

L695: ( R3 + R2 ) = ( +infty ) by L694 , L692 , L38;
thus L696: thesis by L695 , XXREAL_0:3;
end;
suppose L697: R1 = ( -infty );

thus L698: thesis by L697 , XXREAL_0:5;
end;
suppose L699: (R1 in ( REAL ) & R2 in ( REAL ));

reconsider D51 = R1 , D52 = R2 , D53 = R3 as (Element of ( REAL )) by L699 , L692;
L700: ( D51 - D52 ) <= D53 by L678;
L701: D51 <= ( D52 + D53 ) by L700 , XREAL_1:20;
thus L702: thesis by L701;
end;
end;
suppose L704: ( R1 - R2 ) = ( -infty );

per cases  by L704 , L230;
suppose L705: R1 = ( -infty );

thus L706: thesis by L705 , XXREAL_0:5;
end;
suppose L707: R2 = ( +infty );

L708: ( R3 + R2 ) = ( +infty ) by L707 , L692 , L38;
thus L709: thesis by L708 , XXREAL_0:3;
end;
end;
end;
end;
theorem
L713: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((((R1 = ( +infty ) & R2 = ( +infty )) implies ( 0 ) <= R3) & ((R1 = ( -infty ) & R2 = ( -infty )) implies ( 0 ) <= R3)) implies (R1 <= ( R3 + R2 ) implies ( R1 - R2 ) <= R3)))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L714: ((R1 = ( +infty ) & R2 = ( +infty )) implies ( 0 ) <= R3)
and
L715: ((R1 = ( -infty ) & R2 = ( -infty )) implies ( 0 ) <= R3)
and
L716: R1 <= ( R3 + R2 );
per cases  by XXREAL_0:14;
suppose L717: R1 = ( +infty );

per cases  by L716 , L717 , L169 , XXREAL_0:4;
suppose L718: R3 = ( +infty );

thus L719: thesis by L718 , XXREAL_0:3;
end;
suppose L720: R2 = ( +infty );

thus L721: thesis by L720 , L714 , L717 , L91;
end;
end;
suppose L723: R1 = ( -infty );

per cases ;
suppose L724: R2 = ( -infty );

thus L725: thesis by L724 , L715 , L723 , L91;
end;
suppose L726: ( - ( - R2 ) ) <> ( -infty );

L727: ( - R2 ) <> ( +infty ) by L726 , L44;
L728: ( R1 - R2 ) = ( -infty ) by L727 , L723 , L38;
thus L729: thesis by L728 , XXREAL_0:5;
end;
end;
suppose L731: R1 in ( REAL );

per cases  by L716 , L731 , XXREAL_0:10;
suppose L732: ( R3 + R2 ) in ( REAL );

per cases  by L732 , L235;
suppose L733: R2 = ( +infty );

L734: ( R1 - R2 ) = ( -infty ) by L733 , L731 , L38 , L87;
thus L735: thesis by L734 , XXREAL_0:5;
end;
suppose L736: R3 = ( +infty );

thus L737: thesis by L736 , XXREAL_0:3;
end;
suppose L738: (R3 in ( REAL ) & R2 in ( REAL ));

reconsider D54 = R1 , D55 = R2 , D56 = R3 as (Element of ( REAL )) by L738 , L731;
L739: D54 <= ( D55 + D56 ) by L716;
L740: ( D54 - D55 ) <= D56 by L739 , XREAL_1:20;
thus L741: thesis by L740;
end;
end;
suppose L743: ( R3 + R2 ) = ( +infty );

per cases  by L743 , L169;
suppose L744: R3 = ( +infty );

thus L745: thesis by L744 , XXREAL_0:3;
end;
suppose L746: R2 = ( +infty );

L747: ( R1 - R2 ) = ( -infty ) by L746 , L731 , L38 , L87;
thus L748: thesis by L747 , XXREAL_0:5;
end;
end;
end;
end;
theorem
L752: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R3 in ( REAL ) & R1 < R2) implies (( R1 + R3 ) < ( R2 + R3 ) & ( R1 - R3 ) < ( R2 - R3 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L753: R3 in ( REAL )
and
L754: R1 < R2;
L755: ( R1 + R3 ) <> ( R2 + R3 )
proof
assume L756: ( R1 + R3 ) = ( R2 + R3 );
L757: R1 = ( ( R2 + R3 ) - R3 ) by L756 , L753 , L247
.= R2 by L753 , L247;
thus L758: thesis by L757 , L754;
end;
L759: ( R1 - R3 ) <> ( R2 - R3 )
proof
assume L760: ( R1 - R3 ) = ( R2 - R3 );
L761: R1 = ( ( R2 - R3 ) + R3 ) by L760 , L753 , L247
.= R2 by L753 , L247;
thus L762: thesis by L761 , L754;
end;
L763: (( R1 + R3 ) <= ( R2 + R3 ) & ( R1 - R3 ) <= ( R2 - R3 )) by L754 , L607;
thus L764: thesis by L763 , L755 , L759 , XXREAL_0:1;
end;
theorem
L765: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((( 0 ) <= R1 & ( 0 ) <= R2 & ( 0 ) <= R3) implies ( ( R1 + R2 ) + R3 ) = ( R1 + ( R2 + R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L766: ( 0 ) <= R1
and
L767: ( 0 ) <= R2
and
L768: ( 0 ) <= R3;
per cases  by L766 , L767 , L768 , XXREAL_0:14;
suppose L769: (R1 in ( REAL ) & R2 in ( REAL ) & R3 in ( REAL ));

consider C56 , C57 , C58 , C59 , C60 being  real number such that L770: (R1 = C56 & R2 = C57 & R3 = C58) and L771: ( R1 + R2 ) = C59 and L772: ( R2 + R3 ) = C60 by L769;
L773: ( ( R1 + R2 ) + R3 ) = ( ( C56 + C57 ) + C58 ) by L770
.= ( C56 + ( C57 + C58 ) )
.= ( R1 + ( R2 + R3 ) ) by L770;
thus L774: thesis by L773;
end;
suppose L775: R1 = ( +infty );

L776: ( ( R1 + R2 ) + R3 ) = ( ( +infty ) + R3 ) by L775 , L767 , L38
.= ( +infty ) by L768 , L38
.= ( ( +infty ) + ( R2 + R3 ) ) by L767 , L768 , L38;
thus L777: thesis by L776 , L775;
end;
suppose L778: R2 = ( +infty );

L779: ( ( R1 + R2 ) + R3 ) = ( ( +infty ) + R3 ) by L778 , L766 , L38
.= ( +infty ) by L768 , L38
.= ( R1 + ( +infty ) ) by L766 , L38
.= ( R1 + ( ( +infty ) + R3 ) ) by L768 , L38;
thus L780: thesis by L779 , L778;
end;
suppose L781: R3 = ( +infty );

L782: ( ( R1 + R2 ) + R3 ) = ( +infty ) by L781 , L766 , L767 , L38
.= ( R1 + ( +infty ) ) by L766 , L38
.= ( R1 + ( R2 + ( +infty ) ) ) by L767 , L38;
thus L783: thesis by L782 , L781;
end;
end;
theorem
L785: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R1 is  real implies (( R2 + R1 ) <= R3 iff R2 <= ( R3 - R1 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L786: R1 is  real;
L787: ( ( R3 - R1 ) + R1 ) = R3
proof
per cases  by XXREAL_0:14;
suppose L788: R3 in ( REAL );

reconsider D57 = R1 , D58 = R3 as  real number by L788 , L786;
thus L789: ( ( R3 - R1 ) + R1 ) = ( ( D58 - D57 ) + D57 )
.= R3;
end;
suppose L790: R3 = ( -infty );

thus L791: ( ( R3 - R1 ) + R1 ) = ( ( -infty ) + R1 ) by L790 , L786 , L206
.= R3 by L786 , L790 , L38;
end;
suppose L792: R3 = ( +infty );

thus L793: ( ( R3 - R1 ) + R1 ) = ( ( +infty ) + R1 ) by L792 , L786 , L200
.= R3 by L786 , L792 , L38;
end;
end;
thus L795:now
L796: ( ( R2 + R1 ) - R1 ) = R2
proof
per cases  by XXREAL_0:14;
suppose L797: R2 in ( REAL );

reconsider D59 = R1 , D60 = R2 as (Element of ( REAL )) by L797 , L786 , XXREAL_0:14;
L798: ( ( R2 + R1 ) - R1 ) = ( ( D60 + D59 ) - D59 )
.= R2;
thus L799: thesis by L798;
end;
suppose L800: (R2 = ( -infty ) or R2 = ( +infty ));

per cases  by L800;
suppose L801: R2 = ( -infty );

thus L802: ( ( R2 + R1 ) - R1 ) = ( ( -infty ) - R1 ) by L801 , L786 , L38
.= R2 by L786 , L801 , L206;
end;
suppose L803: R2 = ( +infty );

thus L804: ( ( R2 + R1 ) - R1 ) = ( ( +infty ) - R1 ) by L803 , L786 , L38
.= R2 by L786 , L803 , L200;
end;
end;
end;
assume L807: ( R2 + R1 ) <= R3;
thus L808: R2 <= ( R3 - R1 ) by L807 , L796 , L657;
end;
assume L809: R2 <= ( R3 - R1 );
thus L810: thesis by L809 , L787 , L607;
end;
theorem
L811: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((( 0 ) < R1 & R1 < R2) implies ( 0 ) < ( R2 - R1 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L812: ( 0 ) < R1
and
L813: R1 < R2;
L814: R1 in ( REAL ) by L812 , L813 , XXREAL_0:48;
L815: ( 0 ) <> ( R2 - R1 )
proof
assume L816: ( 0 ) = ( R2 - R1 );
L817: R1 = ( ( R2 - R1 ) + R1 ) by L816 , L80
.= R2 by L814 , L247;
thus L818: thesis by L817 , L813;
end;
L819: ( ( 0 ) + R1 ) < R2 by L813 , L80;
thus L820: thesis by L819 , L814 , L815 , L785;
end;
theorem
L821: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((( 0 ) <= R1 & ( 0 ) <= R3 & ( R3 + R1 ) < R2) implies R3 < ( R2 - R1 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L822: ( 0 ) <= R1
and
L823: ( 0 ) <= R3
and
L824: ( R3 + R1 ) < R2;
L825: R1 in ( REAL )
proof
L826: R1 <> ( +infty )
proof
assume L827: R1 = ( +infty );
L828: ( +infty ) < R2 by L827 , L823 , L824 , L38;
thus L829: thesis by L828 , XXREAL_0:4;
end;
assume L830: (not R1 in ( REAL ));
thus L831: thesis by L830 , L822 , L826 , XXREAL_0:10;
end;
L832: (R3 <= ( R2 - R1 ) & R3 <> ( R2 - R1 )) by L825 , L824 , L247 , L785;
thus L833: thesis by L832 , XXREAL_0:1;
end;
theorem
L834: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((( 0 ) <= R1 & ( 0 ) <= R3 & ( R3 + R1 ) < R2) implies R3 <= R2))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L835: ( 0 ) <= R1
and
L836: ( 0 ) <= R3
and
L837: ( R3 + R1 ) < R2;
L838: R1 in ( REAL )
proof
L839: R1 <> ( +infty )
proof
assume L840: R1 = ( +infty );
L841: ( +infty ) < R2 by L840 , L836 , L837 , L38;
thus L842: thesis by L841 , XXREAL_0:4;
end;
assume L843: (not R1 in ( REAL ));
thus L844: thesis by L843 , L835 , L839 , XXREAL_0:10;
end;
L845: ( ( R3 + R1 ) - R1 ) = R3 by L838 , L247;
L846: ( R2 - ( 0 ) ) = R2 by L214;
thus L847: thesis by L846 , L835 , L837 , L845 , L657;
end;
theorem
L848: (for R1 being  ext-real number holds (for R3 being  ext-real number holds ((( 0 ) <= R1 & R1 < R3) implies (ex B24 being  real number st (( 0 ) < B24 & ( R1 + B24 ) < R3)))))
proof
let R1 being  ext-real number;
let R3 being  ext-real number;
assume that
L849: ( 0 ) <= R1
and
L850: R1 < R3;
per cases  by L849;
suppose L851: ( 0 ) < R1;

L852: ( 0 ) < ( R3 - R1 ) by L851 , L850 , L811;
consider C61 being  real number such that L853: ( 0 ) < C61 and L854: C61 < ( R3 - R1 ) by L852 , L15;
take C61;
L855: ( R1 + C61 ) <= ( R1 + ( R3 - R1 ) ) by L854 , L607;
L856: R1 in ( REAL ) by L850 , L851 , XXREAL_0:48;
L857: ( R1 + ( R3 - R1 ) ) = R3 by L856 , L247;
L858: ( R1 + C61 ) <> R3 by L856 , L854 , L247;
thus L859: thesis by L858 , L853 , L855 , L857 , XXREAL_0:1;
end;
suppose L860: ( 0 ) = R1;

consider C62 being  real number such that L861: (( 0 ) < C62 & C62 < R3) by L849 , L850 , L15;
take C62;
thus L862: thesis by L860 , L861 , L80;
end;
end;
theorem
L864: (for R1 being  ext-real number holds (( 0 ) < R1 implies (ex B25 being  real number st (( 0 ) < B25 & ( B25 + B25 ) < R1))))
proof
let R1 being  ext-real number;
assume L865: ( 0 ) < R1;
consider C63 being  real number such that L866: ( 0 ) < C63 and L867: C63 < R1 by L865 , L15;
consider C64 being  real number such that L868: ( 0 ) < C64 and L869: ( C63 + C64 ) < R1 by L866 , L867 , L848;
take D61 = ( min (C63 , C64) );
per cases ;
suppose L870: C63 <= C64;

thus L871: ( 0 ) < D61 by L870 , L866 , XXREAL_0:def 9;
L872: D61 = C63 by L870 , XXREAL_0:def 9;
L873: ( D61 + D61 ) <= ( C63 + C64 ) by L872 , L870 , L607;
thus L874: thesis by L873 , L869 , XXREAL_0:2;
end;
suppose L875: C64 <= C63;

thus L876: ( 0 ) < D61 by L875 , L868 , XXREAL_0:def 9;
L877: D61 = C64 by L875 , XXREAL_0:def 9;
L878: ( D61 + D61 ) <= ( C63 + C64 ) by L877 , L875 , L607;
thus L879: thesis by L878 , L869 , XXREAL_0:2;
end;
end;
theorem
L881: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((R1 < R2 & R1 < ( +infty ) & ( -infty ) < R2) implies ( 0 ) < ( R2 - R1 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L882: R1 < R2
and
L883: R1 < ( +infty )
and
L884: ( -infty ) < R2;
per cases ;
suppose L885: R2 = ( +infty );

thus L886: thesis by L885 , L883 , L200;
end;
suppose L887: R2 <> ( +infty );

per cases ;
suppose L888: R1 = ( -infty );

thus L889: thesis by L888 , L884 , L206;
end;
suppose L890: R1 <> ( -infty );

L891: R2 in ( REAL ) by L884 , L887 , XXREAL_0:14;
L892: R1 in ( REAL ) by L883 , L890 , XXREAL_0:14;
reconsider D62 = R1 , D63 = R2 as  real number by L892 , L891;
L893: ( D63 - D62 ) > ( 0 ) by L882 , XREAL_1:50;
thus L894: thesis by L893;
end;
end;
end;
theorem
L897: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty )))) & ( R1 + R2 ) < R3) implies (R1 <> ( +infty ) & R2 <> ( +infty ) & R3 <> ( -infty ) & R1 < ( R3 - R2 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L898: (not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty ))))
and
L899: ( R1 + R2 ) < R3;
per cases ;
suppose L900: R3 = ( +infty );

L901: R1 <> ( +infty ) by L900 , L898 , L899 , L38;
L902: R1 < ( +infty ) by L901 , XXREAL_0:4;
L903: R2 <> ( +infty ) by L898 , L899 , L900 , L38;
thus L904: thesis by L903 , L900 , L902 , L200;
end;
suppose L905: R3 <> ( +infty );

L906: ( -infty ) <= ( R1 + R2 ) by XXREAL_0:5;
L907: R3 in ( REAL ) by L906 , L899 , L905 , XXREAL_0:14;
reconsider D64 = R3 as  real number by L907;
L908: ( R1 + R2 ) < ( +infty ) by L899 , XXREAL_0:2 , XXREAL_0:4;
L909: R1 <> ( +infty ) by L908 , L898 , L38;
L910: R2 <> ( +infty ) by L898 , L908 , L38;
per cases ;
suppose L911: R2 = ( -infty );

L912: R1 < ( +infty ) by L911 , L898 , XXREAL_0:4;
thus L913: thesis by L912 , L899 , L906 , L911 , L206;
end;
suppose L914: R2 <> ( -infty );

L915: R2 in ( REAL ) by L914 , L910 , XXREAL_0:14;
reconsider D65 = R2 as  real number by L915;
per cases ;
suppose L916: R1 = ( -infty );

thus L917: R1 <> ( +infty ) by L916;
L918: ( R3 - R2 ) = ( D64 - D65 );
thus L919: R2 <> ( +infty ) by L918;
thus L920: R3 <> ( -infty ) by L918;
L921: ( D64 - D65 ) in ( REAL ) by XREAL_0:def 1;
thus L922: thesis by L921 , L916 , XXREAL_0:12;
end;
suppose L923: R1 <> ( -infty );

L924: R1 in ( REAL ) by L923 , L909 , XXREAL_0:14;
reconsider D66 = R1 as  real number by L924;
L925: ( R1 + R2 ) = ( D66 + D65 );
L926: D66 < ( D64 - D65 ) by L925 , L899 , XREAL_1:20;
thus L927: thesis by L926;
end;
end;
end;
end;
theorem
L931: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not ((R3 = ( +infty ) & R2 = ( +infty )) or (R3 = ( -infty ) & R2 = ( -infty )))) & R1 < ( R3 - R2 )) implies (R1 <> ( +infty ) & R2 <> ( +infty ) & R3 <> ( -infty ) & ( R1 + R2 ) < R3)))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L932: (not ((R3 = ( +infty ) & R2 = ( +infty )) or (R3 = ( -infty ) & R2 = ( -infty ))))
and
L933: R1 < ( R3 - R2 );
per cases ;
suppose L934: R1 = ( -infty );

L935: ( -infty ) <= R3 by XXREAL_0:5;
L936: R3 <> ( -infty ) by L932 , L933 , L934 , L206;
L937: ( -infty ) < R3 by L936 , L935 , XXREAL_0:1;
L938: R2 <> ( +infty ) by L932 , L933 , L934 , L200;
thus L939: thesis by L938 , L934 , L937 , L38;
end;
suppose L940: R1 <> ( -infty );

L941: ( R3 - R2 ) <= ( +infty ) by XXREAL_0:4;
L942: R1 in ( REAL ) by L941 , L933 , L940 , XXREAL_0:14;
reconsider D67 = R1 as  real number by L942;
L943: ( -infty ) <= R1 by XXREAL_0:5;
L944: R3 <> ( -infty ) by L943 , L932 , L933 , L206;
L945: R2 <> ( +infty ) by L932 , L933 , L943 , L200;
per cases ;
suppose L946: R2 = ( -infty );

L947: ( -infty ) <= R3 by XXREAL_0:5;
L948: ( -infty ) < R3 by L947 , L932 , L946 , XXREAL_0:1;
thus L949: thesis by L948 , L933 , L941 , L946 , L38;
end;
suppose L950: R2 <> ( -infty );

L951: R2 in ( REAL ) by L950 , L945 , XXREAL_0:14;
reconsider D68 = R2 as  real number by L951;
per cases ;
suppose L952: R3 = ( +infty );

L953: ( D67 + D68 ) in ( REAL ) by XREAL_0:def 1;
thus L954: thesis by L953 , L952 , XXREAL_0:9;
end;
suppose L955: R3 <> ( +infty );

L956: R3 in ( REAL ) by L955 , L944 , XXREAL_0:14;
reconsider D69 = R3 as  real number by L956;
L957: ( R3 - R2 ) = ( D69 - D68 );
L958: ( D67 + D68 ) < D69 by L957 , L933 , XREAL_1:20;
thus L959: thesis by L958;
end;
end;
end;
end;
theorem
L963: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not ((R1 = ( +infty ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 = ( -infty )))) & ( R1 - R2 ) < R3) implies (R1 <> ( +infty ) & R2 <> ( -infty ) & R3 <> ( -infty ) & R1 < ( R3 + R2 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L964: (not ((R1 = ( +infty ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 = ( -infty ))))
and
L965: ( R1 - R2 ) < R3;
per cases ;
suppose L966: R3 = ( +infty );

L967: R1 <> ( +infty ) by L966 , L964 , L965 , L200;
L968: R1 < ( +infty ) by L967 , XXREAL_0:4;
L969: R2 <> ( -infty ) by L964 , L965 , L966 , L206;
thus L970: thesis by L969 , L966 , L968 , L38;
end;
suppose L971: R3 <> ( +infty );

L972: ( -infty ) <= ( R1 - R2 ) by XXREAL_0:5;
L973: R3 in ( REAL ) by L972 , L965 , L971 , XXREAL_0:14;
reconsider D70 = R3 as  real number by L973;
L974: ( R1 - R2 ) < ( +infty ) by L965 , XXREAL_0:2 , XXREAL_0:4;
L975: R1 <> ( +infty ) by L974 , L964 , L200;
L976: R2 <> ( -infty ) by L964 , L974 , L206;
per cases ;
suppose L977: R2 = ( +infty );

L978: R1 < ( +infty ) by L977 , L964 , XXREAL_0:4;
thus L979: thesis by L978 , L965 , L972 , L977 , L38;
end;
suppose L980: R2 <> ( +infty );

L981: R2 in ( REAL ) by L980 , L976 , XXREAL_0:14;
reconsider D71 = R2 as  real number by L981;
per cases ;
suppose L982: R1 = ( -infty );

L983: ( D70 + D71 ) in ( REAL ) by XREAL_0:def 1;
thus L984: thesis by L983 , L982 , XXREAL_0:12;
end;
suppose L985: R1 <> ( -infty );

L986: R1 in ( REAL ) by L985 , L975 , XXREAL_0:14;
reconsider D72 = R1 as  real number by L986;
L987: ( R1 - R2 ) = ( D72 - D71 );
L988: D72 < ( D70 + D71 ) by L987 , L965 , XREAL_1:19;
thus L989: thesis by L988;
end;
end;
end;
end;
theorem
L993: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not ((R3 = ( +infty ) & R2 = ( -infty )) or (R3 = ( -infty ) & R2 = ( +infty )))) & R1 < ( R3 + R2 )) implies (R1 <> ( +infty ) & R2 <> ( -infty ) & R3 <> ( -infty ) & ( R1 - R2 ) < R3)))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L994: (not ((R3 = ( +infty ) & R2 = ( -infty )) or (R3 = ( -infty ) & R2 = ( +infty ))))
and
L995: R1 < ( R3 + R2 );
per cases ;
suppose L996: R1 = ( -infty );

L997: ( -infty ) <= R3 by XXREAL_0:5;
L998: R3 <> ( -infty ) by L994 , L995 , L996 , L38;
L999: ( -infty ) < R3 by L998 , L997 , XXREAL_0:1;
L1000: R2 <> ( -infty ) by L994 , L995 , L996 , L38;
thus L1001: thesis by L1000 , L996 , L999 , L206;
end;
suppose L1002: R1 <> ( -infty );

L1003: ( R3 + R2 ) <= ( +infty ) by XXREAL_0:4;
L1004: R1 in ( REAL ) by L1003 , L995 , L1002 , XXREAL_0:14;
reconsider D73 = R1 as  real number by L1004;
L1005: ( -infty ) <= R1 by XXREAL_0:5;
L1006: R3 <> ( -infty ) by L1005 , L994 , L995 , L38;
L1007: R2 <> ( -infty ) by L994 , L995 , L1005 , L38;
per cases ;
suppose L1008: R2 = ( +infty );

L1009: ( -infty ) <= R3 by XXREAL_0:5;
L1010: ( -infty ) < R3 by L1009 , L994 , L1008 , XXREAL_0:1;
thus L1011: thesis by L1010 , L995 , L1003 , L1008 , L200;
end;
suppose L1012: R2 <> ( +infty );

L1013: R2 in ( REAL ) by L1012 , L1007 , XXREAL_0:14;
reconsider D74 = R2 as  real number by L1013;
per cases ;
suppose L1014: R3 = ( +infty );

L1015: ( D73 - D74 ) in ( REAL ) by XREAL_0:def 1;
thus L1016: thesis by L1015 , L1014 , XXREAL_0:9;
end;
suppose L1017: R3 <> ( +infty );

L1018: R3 in ( REAL ) by L1017 , L1006 , XXREAL_0:14;
reconsider D75 = R3 as  real number by L1018;
L1019: ( R3 + R2 ) = ( D75 + D74 );
L1020: ( D73 - D74 ) < D75 by L1019 , L995 , XREAL_1:19;
thus L1021: thesis by L1020;
end;
end;
end;
end;
theorem
L1025: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty )) or (R2 = ( +infty ) & R3 = ( +infty )) or (R2 = ( -infty ) & R3 = ( -infty )))) & ( R1 + R2 ) <= R3) implies (R2 <> ( +infty ) & R1 <= ( R3 - R2 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1026: (not ((R1 = ( +infty ) & R2 = ( -infty )) or (R1 = ( -infty ) & R2 = ( +infty )) or (R2 = ( +infty ) & R3 = ( +infty )) or (R2 = ( -infty ) & R3 = ( -infty ))))
and
L1027: ( R1 + R2 ) <= R3;
thus L1028: R2 <> ( +infty )
proof
assume L1029: R2 = ( +infty );
L1030: ( R1 + R2 ) = ( +infty ) by L1029 , L1026 , L38;
thus L1031: contradiction by L1030 , L1026 , L1027 , L1029 , XXREAL_0:4;
end;

per cases ;
suppose L1032: R3 = ( +infty );

L1033: ( R3 - R2 ) = ( +infty ) by L1032 , L1026 , L200;
thus L1034: thesis by L1033 , XXREAL_0:4;
end;
suppose L1035: R3 <> ( +infty );

L1036: ( R1 + R2 ) < ( +infty ) by L1035 , L1027 , XXREAL_0:2 , XXREAL_0:4;
L1037: R1 <> ( +infty ) by L1036 , L1026 , L38;
L1038: R2 <> ( +infty ) by L1026 , L1036 , L38;
per cases ;
suppose L1039: R1 = ( -infty );

thus L1040: thesis by L1039 , XXREAL_0:5;
end;
suppose L1041: R1 <> ( -infty );

L1042: R1 in ( REAL ) by L1041 , L1037 , XXREAL_0:14;
reconsider D76 = R1 as  real number by L1042;
per cases ;
suppose L1043: R2 = ( -infty );

L1044: ( R3 - R2 ) = ( +infty ) by L1043 , L1026 , L206;
thus L1045: thesis by L1044 , XXREAL_0:4;
end;
suppose L1046: R2 <> ( -infty );

L1047: R2 in ( REAL ) by L1046 , L1038 , XXREAL_0:14;
reconsider D77 = R2 as  real number by L1047;
L1048: ( D76 + D77 ) in ( REAL ) by XREAL_0:def 1;
L1049: R3 <> ( -infty ) by L1048 , L1027 , XXREAL_0:12;
L1050: R3 in ( REAL ) by L1049 , L1035 , XXREAL_0:14;
reconsider D78 = R3 as  real number by L1050;
L1051: ( R1 + R2 ) = ( D76 + D77 );
L1052: D76 <= ( D78 - D77 ) by L1051 , L1027 , XREAL_1:19;
thus L1053: thesis by L1052;
end;
end;
end;
end;
theorem
L1057: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not (R1 = ( +infty ) & R2 = ( -infty ))) & (not (R1 = ( -infty ) & R2 = ( +infty ))) & (not (R2 = ( +infty ) & R3 = ( +infty ))) & R1 <= ( R3 - R2 )) implies (R2 <> ( +infty ) & ( R1 + R2 ) <= R3)))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1058: (not (R1 = ( +infty ) & R2 = ( -infty )))
and
L1059: (not (R1 = ( -infty ) & R2 = ( +infty )))
and
L1060: (not (R2 = ( +infty ) & R3 = ( +infty )))
and
L1061: R1 <= ( R3 - R2 );
thus L1062: R2 <> ( +infty )
proof
assume L1063: R2 = ( +infty );
L1064: ( R3 - R2 ) = ( -infty ) by L1063 , L1060 , L200;
thus L1065: contradiction by L1064 , L1059 , L1061 , L1063 , XXREAL_0:6;
end;

per cases  by L1062;
suppose L1066: R2 = ( -infty );

L1067: ( R1 + R2 ) = ( -infty ) by L1066 , L1058 , L38;
thus L1068: thesis by L1067 , XXREAL_0:5;
end;
suppose L1069: (R2 <> ( +infty ) & R2 <> ( -infty ));

L1070: ( - ( -infty ) ) = ( +infty ) by L44;
L1071: ( - R2 ) <> ( -infty ) by L1070 , L1069;
L1072: ( - ( +infty ) ) = ( -infty ) by L44;
L1073: ( - R2 ) <> ( +infty ) by L1072 , L1069;
L1074: ( ( R3 - R2 ) + R2 ) = ( R3 + ( ( - R2 ) + R2 ) ) by L1073 , L1069 , L1071 , L315
.= ( R3 + ( 0 ) ) by L91
.= R3 by L80;
thus L1075: thesis by L1074 , L1061 , L607;
end;
end;
theorem
L1077: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not ((R1 = ( +infty ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 = ( -infty )) or (R2 = ( +infty ) & R3 = ( -infty )) or (R2 = ( -infty ) & R3 = ( +infty )))) & ( R1 - R2 ) <= R3) implies R2 <> ( -infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1078: (not ((R1 = ( +infty ) & R2 = ( +infty )) or (R1 = ( -infty ) & R2 = ( -infty )) or (R2 = ( +infty ) & R3 = ( -infty )) or (R2 = ( -infty ) & R3 = ( +infty ))))
and
L1079: ( R1 - R2 ) <= R3;
assume L1080: R2 = ( -infty );
L1081: ( R1 - R2 ) = ( +infty ) by L1080 , L1078 , L206;
thus L1082: contradiction by L1081 , L1078 , L1079 , L1080 , XXREAL_0:4;
end;
theorem
L1083: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (((not (R1 = ( -infty ) & R2 = ( -infty ))) & (not (R2 = ( -infty ) & R3 = ( +infty ))) & R1 <= ( R3 + R2 )) implies R2 <> ( -infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1084: (not (R1 = ( -infty ) & R2 = ( -infty )))
and
L1085: (not (R2 = ( -infty ) & R3 = ( +infty )))
and
L1086: R1 <= ( R3 + R2 );
assume L1087: R2 = ( -infty );
L1088: ( R3 + R2 ) = ( -infty ) by L1087 , L1085 , L38;
thus L1089: contradiction by L1088 , L1084 , L1086 , L1087 , XXREAL_0:6;
end;
theorem
L1090: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((R1 <= ( - R2 ) implies R2 <= ( - R1 )) & (( - R1 ) <= R2 implies ( - R2 ) <= R1))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
L1091: (R1 <= ( - R2 ) implies ( - ( - R2 ) ) <= ( - R1 )) by L662;
thus L1092: (R1 <= ( - R2 ) implies R2 <= ( - R1 )) by L1091;
L1093: (( - R1 ) <= R2 implies ( - R2 ) <= ( - ( - R1 ) )) by L662;
thus L1094: thesis by L1093;
end;
theorem
L1095: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((for B26 being  real number holds (( 0 ) < B26 implies R1 < ( R2 + B26 ))) implies R1 <= R2)))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L1096: (for B27 being  real number holds (( 0 ) < B27 implies R1 < ( R2 + B27 )));
per cases ;
suppose L1097: (R2 = ( +infty ) or R2 = ( -infty ));

per cases  by L1097;
suppose L1098: R2 = ( +infty );

thus L1099: thesis by L1098 , XXREAL_0:4;
end;
suppose L1100: R2 = ( -infty );

L1101: R1 < ( R2 + 1 ) by L1096;
thus L1102: thesis by L1101 , L1100 , L38;
end;
end;
suppose L1104: (R2 <> ( +infty ) & R2 <> ( -infty ));

per cases ;
suppose L1105: R1 = ( +infty );

L1106: R1 < ( R2 + 1 ) by L1096;
thus L1107: thesis by L1106 , L1105 , XXREAL_0:4;
end;
suppose L1108: R1 <> ( +infty );

L1109:
now
assume L1110: R1 <> ( -infty );
L1111: R1 in ( REAL ) by L1110 , L1108 , XXREAL_0:14;
reconsider D79 = R1 as  real number by L1111;
L1112: ( -infty ) <= R1 by XXREAL_0:5;
L1113: ( -infty ) < R1 by L1112 , L1110 , XXREAL_0:1;
L1114: R2 in ( REAL ) by L1104 , XXREAL_0:14;
reconsider D80 = R2 as  real number by L1114;
assume L1115: (not R1 <= R2);
L1116: R2 < ( +infty ) by L1104 , XXREAL_0:4;
L1117: ( 0 ) < ( R1 - R2 ) by L1116 , L1115 , L1113 , L881;
L1118: R1 < ( R2 + ( D79 - D80 ) ) by L1117 , L1096;
L1119: R1 < ( ( R2 + R1 ) - R2 ) by L1118 , L361;
L1120: R1 < ( R1 + ( R2 - R2 ) ) by L1119 , L1104 , L361;
L1121: R1 < ( R1 + ( 0 ) ) by L1120 , L91;
thus L1122: contradiction by L1121 , L80;
end;
thus L1123: thesis by L1109 , XXREAL_0:5;
end;
end;
end;
theorem
L1126: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R8 being  ext-real number holds ((R8 <> ( -infty ) & R8 <> ( +infty ) & R1 < R2) implies ( R1 + R8 ) < ( R2 + R8 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R8 being  ext-real number;
assume that
L1127: (R8 <> ( -infty ) & R8 <> ( +infty ))
and
L1128: R1 < R2;
L1129: ( R8 - R8 ) = ( 0 ) by L91;
L1130:
now
assume L1131: ( R1 + R8 ) = ( R2 + R8 );
L1132: ( R1 + ( R8 - R8 ) ) = ( ( R2 + R8 ) - R8 ) by L1131 , L1127 , L361;
L1133: ( R1 + ( 0 ) ) = ( R2 + ( R8 - R8 ) ) by L1132 , L1127 , L1129 , L361;
L1134: R1 = ( R2 + ( 0 ) ) by L1133 , L1129 , L80;
thus L1135: contradiction by L1134 , L1128 , L80;
end;
L1136: ( R1 + R8 ) <= ( R2 + R8 ) by L1128 , L607;
thus L1137: thesis by L1136 , L1130 , XXREAL_0:1;
end;
theorem
L1138: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R8 being  ext-real number holds ((R8 <> ( -infty ) & R8 <> ( +infty ) & R1 < R2) implies ( R1 - R8 ) < ( R2 - R8 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R8 being  ext-real number;
assume that
L1139: (R8 <> ( -infty ) & R8 <> ( +infty ))
and
L1140: R1 < R2;
L1141: ( R8 - R8 ) = ( 0 ) by L91;
L1142:
now
assume L1143: ( R1 - R8 ) = ( R2 - R8 );
L1144: ( R1 - ( R8 - R8 ) ) = ( ( R2 - R8 ) + R8 ) by L1143 , L1139 , L409;
L1145: ( R1 - ( 0 ) ) = ( R2 - ( R8 - R8 ) ) by L1144 , L1139 , L1141 , L409;
L1146: R1 = ( R2 + ( 0 ) ) by L1145 , L1141 , L80;
thus L1147: contradiction by L1146 , L1140 , L80;
end;
L1148: ( R1 - R8 ) <= ( R2 - R8 ) by L1140 , L657;
thus L1149: thesis by L1148 , L1142 , XXREAL_0:1;
end;
theorem
L1150: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (for R4 being  ext-real number holds ((R1 < R2 & R4 < R3) implies ( R1 + R4 ) < ( R2 + R3 ))))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
let R4 being  ext-real number;
assume that
L1151: R1 < R2
and
L1152: R4 < R3;
L1153: ( -infty ) <= R4 by XXREAL_0:5;
per cases  by L1153 , XXREAL_0:1;
suppose L1154: R4 = ( -infty );

L1155: (R2 <> ( -infty ) & R3 <> ( -infty )) by L1151 , L1152 , XXREAL_0:5;
L1156: R1 <> ( +infty ) by L1151 , XXREAL_0:3;
L1157: ( R1 + R4 ) = ( -infty ) by L1156 , L1154 , L38;
thus L1158: thesis by L1157 , L1155 , L174 , XXREAL_0:6;
end;
suppose L1159: ( -infty ) < R4;

per cases ;
suppose L1160: R2 = ( +infty );

L1161: R3 <= ( +infty ) by XXREAL_0:4;
L1162: ( R2 + R3 ) = ( +infty ) by L1159 , L1152 , L1160 , L38;
thus L1163: thesis by L1162 , L1151 , L1152 , L1160 , L1161 , L169 , XXREAL_0:4;
end;
suppose L1164: R2 <> ( +infty );

L1165: ( -infty ) <= R1 by XXREAL_0:5;
L1166: R2 in ( REAL ) by L1165 , L1151 , L1164 , XXREAL_0:14;
L1167: ( R2 + R4 ) < ( R2 + R3 ) by L1166 , L1152 , L752;
L1168: R3 <= ( +infty ) by XXREAL_0:4;
L1169: R4 in ( REAL ) by L1168 , L1159 , L1152 , XXREAL_0:14;
L1170: ( R1 + R4 ) < ( R2 + R4 ) by L1169 , L1151 , L752;
thus L1171: thesis by L1170 , L1167 , XXREAL_0:2;
end;
end;
end;
theorem
L1174: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((( 0 ) <= R1 & ( R3 + R1 ) <= R2) implies R3 <= R2))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1175: ( 0 ) <= R1;
L1176: R3 <= ( R3 + R1 ) by L1175 , L666;
thus L1177: thesis by L1176 , XXREAL_0:2;
end;
begin
definition
let C65 , C66 being  ext-real number;
func C65 * C66 ->  ext-real number means 
:L1178: (ex B28 , B29 being  complex number st (C65 = B28 & C66 = B29 & it = ( B28 * B29 ))) if (C65 is  real & C66 is  real) , it = ( +infty ) if (((not C65 is  real) or (not C66 is  real)) & ((C65 is  positive & C66 is  positive) or (C65 is  negative & C66 is  negative))) , it = ( -infty ) if (((not C65 is  real) or (not C66 is  real)) & ((C65 is  positive & C66 is  negative) or (C65 is  negative & C66 is  positive))) otherwise it = ( 0 );
existence
proof
thus L1179: ((C65 is  real & C66 is  real) implies (ex B30 being  ext-real number st (ex B31 , B32 being  complex number st (C65 = B31 & C66 = B32 & B30 = ( B31 * B32 )))))
proof
assume L1180: (C65 is  real & C66 is  real);
reconsider D81 = C65 , D82 = C66 as  real number by L1180;
take ( D81 * D82 );
take D81;
take D82;
thus L1181: thesis;
end;

thus L1182: thesis;
end;
uniqueness;
consistency;
commutativity
;
end;
registration
let C67 , C68 being  real number;
let C69 , C70 being  complex number;
identify C67 * C68 with C69 * C70 when C67 = C69 , C68 = C70;
compatibility by L1178;
end;
definition
let C71 being  ext-real number;
func C71 " ->  ext-real number means 
:L1185: (ex B33 being  complex number st (C71 = B33 & it = ( B33 " ))) if C71 is  real otherwise it = ( 0 );
existence
proof
thus L1186: (C71 is  real implies (ex B34 being  ext-real number st (ex B35 being  complex number st (C71 = B35 & B34 = ( B35 " )))))
proof
assume L1187: C71 is  real;
reconsider D83 = C71 as  real number by L1187;
take ( D83 " );
take D83;
thus L1188: thesis;
end;

thus L1189: thesis;
end;
uniqueness;
consistency;
end;
registration
let C72 being  real number;
let C73 being  complex number;
identify C72 " with C73 " when C72 = C73;
compatibility by L1185;
end;
definition
let C74 , C75 being  ext-real number;
func C74 / C75 ->  ext-real number equals 
( C74 * ( C75 " ) );
coherence;
end;
registration
let C76 , C77 being  real number;
let C78 , C79 being  complex number;
identify C76 / C77 with C78 / C79 when C76 = C78 , C77 = C79;
compatibility
proof
reconsider D84 = ( C77 " ) as  real number;
assume L1193: (C76 = C78 & C77 = C79);
thus L1194: ( C78 / C79 ) = ( C76 * D84 ) by L1193
.= ( C76 / C77 );
end;
end;
L1196: (for R1 being  ext-real number holds ( R1 * ( 0 ) ) = ( 0 ))
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L1197: R1 in ( REAL );

L1198: (ex B36 , B37 being  complex number st (R1 = B36 & ( 0 ) = B37 & ( R1 * ( 0 ) ) = ( B36 * B37 ))) by L1197 , L1178;
thus L1199: thesis by L1198;
end;
suppose L1200: R1 = ( +infty );

thus L1201: thesis by L1200 , L1178;
end;
suppose L1202: R1 = ( -infty );

thus L1203: thesis by L1202 , L1178;
end;
end;
registration
let C80 being  positive  ext-real number;
let C81 being  negative  ext-real number;
cluster ( C80 * C81 ) ->  negative;
coherence
proof
per cases ;
suppose L1205: (C80 in ( REAL ) & C81 in ( REAL ));

reconsider D85 = C80 , D86 = C81 as  real number by L1205;
L1206: ( D85 * D86 ) < ( 0 );
thus L1207: thesis by L1206;
end;
suppose L1208: ((not C80 in ( REAL )) or (not C81 in ( REAL )));

L1209: ((not C80 is  real) or (not C81 is  real)) by L1208 , XREAL_0:def 1;
thus L1210: thesis by L1209 , L1178;
end;
end;
end;
registration
let C82 , C83 being  negative  ext-real number;
cluster ( C82 * C83 ) ->  positive;
coherence
proof
per cases ;
suppose L1213: (C82 in ( REAL ) & C83 in ( REAL ));

reconsider D87 = C82 , D88 = C83 as  real number by L1213;
L1214: ( D87 * D88 ) > ( 0 );
thus L1215: thesis by L1214;
end;
suppose L1216: ((not C82 in ( REAL )) or (not C83 in ( REAL )));

L1217: ((not C82 is  real) or (not C83 is  real)) by L1216 , XREAL_0:def 1;
thus L1218: thesis by L1217 , L1178;
end;
end;
end;
registration
let C84 , C85 being  positive  ext-real number;
cluster ( C84 * C85 ) ->  positive;
coherence
proof
per cases ;
suppose L1221: (C84 in ( REAL ) & C85 in ( REAL ));

reconsider D89 = C84 , D90 = C85 as  real number by L1221;
L1222: ( D89 * D90 ) > ( 0 );
thus L1223: thesis by L1222;
end;
suppose L1224: ((not C84 in ( REAL )) or (not C85 in ( REAL )));

L1225: ((not C84 is  real) or (not C85 is  real)) by L1224 , XREAL_0:def 1;
thus L1226: thesis by L1225 , L1178;
end;
end;
end;
registration
let C86 being non  positive  ext-real number;
let C87 being non  negative  ext-real number;
cluster ( C86 * C87 ) -> non  positive;
coherence
proof
per cases ;
suppose L1229: (C86 = ( 0 ) or C87 = ( 0 ));

thus L1230: ( C86 * C87 ) <= ( 0 ) by L1229 , L1196;
end;
suppose L1231: (C86 < ( 0 ) & C87 > ( 0 ));

thus L1232: ( C86 * C87 ) <= ( 0 ) by L1231;
end;
end;
end;
registration
let C88 , C89 being non  positive  ext-real number;
cluster ( C88 * C89 ) -> non  negative;
coherence
proof
per cases ;
suppose L1235: (C88 = ( 0 ) or C89 = ( 0 ));

thus L1236: ( C88 * C89 ) >= ( 0 ) by L1235 , L1196;
end;
suppose L1237: (C88 < ( 0 ) & C89 < ( 0 ));

thus L1238: ( C88 * C89 ) >= ( 0 ) by L1237;
end;
end;
end;
registration
let C90 , C91 being non  negative  ext-real number;
cluster ( C90 * C91 ) -> non  negative;
coherence
proof
per cases ;
suppose L1241: (C90 = ( 0 ) or C91 = ( 0 ));

thus L1242: ( C90 * C91 ) >= ( 0 ) by L1241 , L1196;
end;
suppose L1243: (C90 > ( 0 ) & C91 > ( 0 ));

thus L1244: ( C90 * C91 ) >= ( 0 ) by L1243;
end;
end;
end;
registration
let C92 being non  positive  ext-real number;
cluster ( C92 " ) -> non  positive;
coherence
proof
per cases ;
suppose L1247: C92 is  real;

reconsider D91 = C92 as  real number by L1247;
L1248: ( D91 " ) is non  positive;
thus L1249: thesis by L1248;
end;
suppose L1250: (not C92 is  real);

thus L1251: thesis by L1250 , L1185;
end;
end;
end;
registration
let C93 being non  negative  ext-real number;
cluster ( C93 " ) -> non  negative;
coherence
proof
per cases ;
suppose L1254: C93 is  real;

reconsider D92 = C93 as  real number by L1254;
L1255: ( D92 " ) is non  negative;
thus L1256: thesis by L1255;
end;
suppose L1257: (not C93 is  real);

thus L1258: thesis by L1257 , L1185;
end;
end;
end;
registration
let C94 being non  negative  ext-real number;
let C95 being non  positive  ext-real number;
cluster ( C94 / C95 ) -> non  positive;
coherence;
cluster ( C95 / C94 ) -> non  positive;
coherence;
end;
registration
let C96 , C97 being non  negative  ext-real number;
cluster ( C96 / C97 ) -> non  negative;
coherence;
end;
registration
let C98 , C99 being non  positive  ext-real number;
cluster ( C98 / C99 ) -> non  negative;
coherence;
end;
L1264: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (((not R1 is  real) & ( R1 * R2 ) = ( 0 )) implies R2 = ( 0 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L1265: (not R1 is  real)
and
L1266: ( R1 * R2 ) = ( 0 );
L1267: (not ((R1 is  positive & R2 is  positive) or (R1 is  negative & R2 is  negative))) by L1266;
thus L1268: thesis by L1267 , L1265 , L1266;
end;
registration
let C100 , C101 being non  zero  ext-real number;
cluster ( C100 * C101 ) -> non  zero;
coherence
proof
per cases ;
suppose L1269: (C100 is  real & C101 is  real);

reconsider D93 = C100 , D94 = C101 as  real number by L1269;
assume L1270: ( C100 * C101 ) is  zero;
L1271: ( D93 * D94 ) = ( 0 ) by L1270;
thus L1272: contradiction by L1271;
end;
suppose L1273: ((not C100 is  real) or (not C101 is  real));

thus L1274: thesis by L1273 , L1264;
end;
end;
end;
registration
let C102 being  zero  ext-real number;
let C103 being  ext-real number;
cluster ( C102 * C103 ) ->  zero for  ext-real  ext-real  ext-real  ext-real number;
coherence by L1196;
end;
L1278: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R1 = ( 0 ) implies ( R1 * ( R2 * R3 ) ) = ( ( R1 * R2 ) * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1279: R1 = ( 0 );
thus L1280: ( R1 * ( R2 * R3 ) ) = ( 0 ) by L1279
.= ( ( R1 * R2 ) * R3 ) by L1279;
end;
L1281: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R2 = ( 0 ) implies ( R1 * ( R2 * R3 ) ) = ( ( R1 * R2 ) * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1282: R2 = ( 0 );
thus L1283: ( R1 * ( R2 * R3 ) ) = ( 0 ) by L1282
.= ( ( R1 * R2 ) * R3 ) by L1282;
end;
L1284: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((not R2 is  real) implies ( R1 * ( R2 * R3 ) ) = ( ( R1 * R2 ) * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1285: (not R2 is  real);
L1286: (not R2 in ( REAL )) by L1285;
assume L1287: (not thesis);
L1288: (R1 <> ( 0 ) & R3 <> ( 0 )) by L1287 , L1278;
per cases  by L1286 , XXREAL_0:14;
suppose L1289: R2 = ( -infty );

per cases  by L1288;
suppose L1290: (R1 is  positive & R3 is  positive);

L1291: ( R1 * ( ( -infty ) * R3 ) ) = ( R1 * ( -infty ) ) by L1290 , L1178
.= ( -infty ) by L1290 , L1178
.= ( ( -infty ) * R3 ) by L1290 , L1178
.= ( ( R1 * ( -infty ) ) * R3 ) by L1290 , L1178;
thus L1292: thesis by L1291 , L1287 , L1289;
end;
suppose L1293: (R1 is  positive & R3 is  negative);

L1294: ( R1 * ( ( -infty ) * R3 ) ) = ( R1 * ( +infty ) ) by L1293 , L1178
.= ( +infty ) by L1293 , L1178
.= ( ( -infty ) * R3 ) by L1293 , L1178
.= ( ( R1 * ( -infty ) ) * R3 ) by L1293 , L1178;
thus L1295: thesis by L1294 , L1287 , L1289;
end;
suppose L1296: (R1 is  negative & R3 is  positive);

L1297: ( R1 * ( ( -infty ) * R3 ) ) = ( R1 * ( -infty ) ) by L1296 , L1178
.= ( +infty ) by L1296 , L1178
.= ( ( +infty ) * R3 ) by L1296 , L1178
.= ( ( R1 * ( -infty ) ) * R3 ) by L1296 , L1178;
thus L1298: thesis by L1297 , L1287 , L1289;
end;
suppose L1299: (R1 is  negative & R3 is  negative);

L1300: ( R1 * ( ( -infty ) * R3 ) ) = ( R1 * ( +infty ) ) by L1299 , L1178
.= ( -infty ) by L1299 , L1178
.= ( ( +infty ) * R3 ) by L1299 , L1178
.= ( ( R1 * ( -infty ) ) * R3 ) by L1299 , L1178;
thus L1301: thesis by L1300 , L1287 , L1289;
end;
end;
suppose L1303: R2 = ( +infty );

per cases  by L1288;
suppose L1304: (R1 is  positive & R3 is  positive);

L1305: ( R1 * ( ( +infty ) * R3 ) ) = ( R1 * ( +infty ) ) by L1304 , L1178
.= ( +infty ) by L1304 , L1178
.= ( ( +infty ) * R3 ) by L1304 , L1178
.= ( ( R1 * ( +infty ) ) * R3 ) by L1304 , L1178;
thus L1306: thesis by L1305 , L1287 , L1303;
end;
suppose L1307: (R1 is  positive & R3 is  negative);

L1308: ( R1 * ( ( +infty ) * R3 ) ) = ( R1 * ( -infty ) ) by L1307 , L1178
.= ( -infty ) by L1307 , L1178
.= ( ( +infty ) * R3 ) by L1307 , L1178
.= ( ( R1 * ( +infty ) ) * R3 ) by L1307 , L1178;
thus L1309: thesis by L1308 , L1287 , L1303;
end;
suppose L1310: (R1 is  negative & R3 is  positive);

L1311: ( R1 * ( ( +infty ) * R3 ) ) = ( R1 * ( +infty ) ) by L1310 , L1178
.= ( -infty ) by L1310 , L1178
.= ( ( -infty ) * R3 ) by L1310 , L1178
.= ( ( R1 * ( +infty ) ) * R3 ) by L1310 , L1178;
thus L1312: thesis by L1311 , L1287 , L1303;
end;
suppose L1313: (R1 is  negative & R3 is  negative);

L1314: ( R1 * ( ( +infty ) * R3 ) ) = ( R1 * ( -infty ) ) by L1313 , L1178
.= ( +infty ) by L1313 , L1178
.= ( ( -infty ) * R3 ) by L1313 , L1178
.= ( ( R1 * ( +infty ) ) * R3 ) by L1313 , L1178;
thus L1315: thesis by L1314 , L1287 , L1303;
end;
end;
end;
L1318: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((not R1 is  real) implies ( R1 * ( R2 * R3 ) ) = ( ( R1 * R2 ) * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1319: (not R1 is  real);
L1320: (not R1 in ( REAL )) by L1319;
assume L1321: (not thesis);
L1322: (R2 <> ( 0 ) & R3 <> ( 0 )) by L1321 , L1278 , L1281;
per cases  by L1320 , XXREAL_0:14;
suppose L1323: R1 = ( -infty );

per cases  by L1322;
suppose L1324: (R2 is  positive & R3 is  positive);

L1325: ( ( -infty ) * ( R2 * R3 ) ) = ( -infty ) by L1324 , L1178
.= ( ( -infty ) * R3 ) by L1324 , L1178
.= ( ( ( -infty ) * R2 ) * R3 ) by L1324 , L1178;
thus L1326: thesis by L1325 , L1321 , L1323;
end;
suppose L1327: (R2 is  positive & R3 is  negative);

L1328: ( ( -infty ) * ( R2 * R3 ) ) = ( +infty ) by L1327 , L1178
.= ( ( -infty ) * R3 ) by L1327 , L1178
.= ( ( ( -infty ) * R2 ) * R3 ) by L1327 , L1178;
thus L1329: thesis by L1328 , L1321 , L1323;
end;
suppose L1330: (R2 is  negative & R3 is  positive);

L1331: ( ( -infty ) * ( R2 * R3 ) ) = ( +infty ) by L1330 , L1178
.= ( ( +infty ) * R3 ) by L1330 , L1178
.= ( ( ( -infty ) * R2 ) * R3 ) by L1330 , L1178;
thus L1332: thesis by L1331 , L1321 , L1323;
end;
suppose L1333: (R2 is  negative & R3 is  negative);

L1334: ( ( -infty ) * ( R2 * R3 ) ) = ( -infty ) by L1333 , L1178
.= ( ( +infty ) * R3 ) by L1333 , L1178
.= ( ( ( -infty ) * R2 ) * R3 ) by L1333 , L1178;
thus L1335: thesis by L1334 , L1321 , L1323;
end;
end;
suppose L1337: R1 = ( +infty );

per cases  by L1322;
suppose L1338: (R2 is  positive & R3 is  positive);

L1339: ( ( +infty ) * ( R2 * R3 ) ) = ( +infty ) by L1338 , L1178
.= ( ( +infty ) * R3 ) by L1338 , L1178
.= ( ( ( +infty ) * R2 ) * R3 ) by L1338 , L1178;
thus L1340: thesis by L1339 , L1321 , L1337;
end;
suppose L1341: (R2 is  positive & R3 is  negative);

L1342: ( ( +infty ) * ( R2 * R3 ) ) = ( -infty ) by L1341 , L1178
.= ( ( +infty ) * R3 ) by L1341 , L1178
.= ( ( ( +infty ) * R2 ) * R3 ) by L1341 , L1178;
thus L1343: thesis by L1342 , L1321 , L1337;
end;
suppose L1344: (R2 is  negative & R3 is  positive);

L1345: ( ( +infty ) * ( R2 * R3 ) ) = ( -infty ) by L1344 , L1178
.= ( ( -infty ) * R3 ) by L1344 , L1178
.= ( ( ( +infty ) * R2 ) * R3 ) by L1344 , L1178;
thus L1346: thesis by L1345 , L1321 , L1337;
end;
suppose L1347: (R2 is  negative & R3 is  negative);

L1348: ( ( +infty ) * ( R2 * R3 ) ) = ( +infty ) by L1347 , L1178
.= ( ( -infty ) * R3 ) by L1347 , L1178
.= ( ( ( +infty ) * R2 ) * R3 ) by L1347 , L1178;
thus L1349: thesis by L1348 , L1321 , L1337;
end;
end;
end;
theorem
L1352: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ( R1 * ( R2 * R3 ) ) = ( ( R1 * R2 ) * R3 ))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
per cases ;
suppose L1353: (R1 is  real & R2 is  real & R3 is  real);

reconsider D95 = R1 , D96 = R2 , D97 = R3 as  real number by L1353;
reconsider D98 = ( D95 * D96 ) , D99 = ( D96 * D97 ) as  real number;
thus L1354: ( R1 * ( R2 * R3 ) ) = ( D95 * D99 )
.= ( D98 * D97 )
.= ( ( R1 * R2 ) * R3 );
end;
suppose L1355: ((not R1 is  real) or (not R3 is  real));

thus L1356: thesis by L1355 , L1318;
end;
suppose L1357: (not R2 is  real);

thus L1358: thesis by L1357 , L1284;
end;
end;
registration
let C104 being  real number;
cluster ( C104 " ) ->  real;
coherence;
end;
registration
let C105 , C106 being  real number;
cluster ( C105 * C106 ) ->  real;
coherence;
cluster ( C105 / C106 ) ->  real;
coherence;
end;
registration
cluster ( ( -infty ) " ) ->  zero;
coherence by L1185;
cluster ( ( +infty ) " ) ->  zero;
coherence by L1185;
end;
theorem
L1363: (for R6 being  ext-real number holds (for R7 being  ext-real number holds ( ( R6 * R7 ) " ) = ( ( R6 " ) * ( R7 " ) )))
proof
let R6 being  ext-real number;
let R7 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L1364: (R6 in ( REAL ) & R7 in ( REAL ));

reconsider D100 = R6 , D101 = R7 as  real number by L1364;
L1365: ((ex B38 being  complex number st (D100 = B38 & ( R6 " ) = ( B38 " ))) & (ex B39 being  complex number st (D101 = B39 & ( R7 " ) = ( B39 " )))) by L1185;
L1366: (ex B40 , B41 being  complex number st (( R6 " ) = B40 & ( R7 " ) = B41 & ( ( R6 " ) * ( R7 " ) ) = ( B40 * B41 ))) by L1365 , L1178;
L1367: ( ( R6 " ) * ( R7 " ) ) = ( ( D100 * D101 ) " ) by L1366 , L1365 , XCMPLX_1:204;
thus L1368: thesis by L1367;
end;
suppose L1369: R6 = ( +infty );

L1370: (R7 is  positive or R7 is  negative or R7 = ( 0 ));
L1371: (( ( R6 * R7 ) " ) = ( ( +infty ) " ) or ( ( R6 * R7 ) " ) = ( ( -infty ) " ) or ( ( R6 * R7 ) " ) = ( ( 0 ) " )) by L1370 , L1369 , L1178;
thus L1372: thesis by L1371 , L1369;
end;
suppose L1373: R6 = ( -infty );

L1374: (R7 is  positive or R7 is  negative or R7 = ( 0 ));
L1375: (( ( R6 * R7 ) " ) = ( ( +infty ) " ) or ( ( R6 * R7 ) " ) = ( ( -infty ) " ) or ( ( R6 * R7 ) " ) = ( ( 0 ) " )) by L1374 , L1373 , L1178;
thus L1376: thesis by L1375 , L1373;
end;
suppose L1377: R7 = ( +infty );

L1378: (R6 is  positive or R6 is  negative or R6 = ( 0 ));
L1379: (( ( R6 * R7 ) " ) = ( ( +infty ) " ) or ( ( R6 * R7 ) " ) = ( ( -infty ) " ) or ( ( R6 * R7 ) " ) = ( ( 0 ) " )) by L1378 , L1377 , L1178;
thus L1380: thesis by L1379 , L1377;
end;
suppose L1381: R7 = ( -infty );

L1382: (R6 is  positive or R6 is  negative or R6 = ( 0 ));
L1383: (( ( R6 * R7 ) " ) = ( ( +infty ) " ) or ( ( R6 * R7 ) " ) = ( ( -infty ) " ) or ( ( R6 * R7 ) " ) = ( ( 0 ) " )) by L1382 , L1381 , L1178;
thus L1384: thesis by L1383 , L1381;
end;
end;
theorem
L1386: (for R5 being  real number holds (for R6 being  ext-real number holds (for R7 being  ext-real number holds ((R5 <> ( 0 ) & ( R5 * R6 ) = ( R5 * R7 )) implies R6 = R7))))
proof
let R5 being  real number;
let R6 being  ext-real number;
let R7 being  ext-real number;
assume that
L1387: R5 <> ( 0 )
and
L1388: ( R5 * R6 ) = ( R5 * R7 );
L1389: (R5 is  positive or R5 is  negative) by L1387;
per cases  by XXREAL_0:14;
suppose L1390: R6 in ( REAL );

L1391:
now
assume L1392: (not R7 in ( REAL ));
L1393: (R7 = ( +infty ) or R7 = ( -infty )) by L1392 , XXREAL_0:14;
thus L1394: contradiction by L1393 , L1388 , L1389 , L1390 , L1178;
end;
L1395: (ex B42 , B43 being  complex number st (R5 = B42 & R7 = B43 & ( R5 * R7 ) = ( B42 * B43 ))) by L1391 , L1178;
L1396: (ex B44 , B45 being  complex number st (R5 = B44 & R6 = B45 & ( R5 * R6 ) = ( B44 * B45 ))) by L1390 , L1178;
thus L1397: thesis by L1396 , L1387 , L1388 , L1395 , XCMPLX_1:5;
end;
suppose L1398: R6 = ( +infty );

assume L1399: R6 <> R7;
L1400: (R7 in ( REAL ) or R7 = ( -infty )) by L1399 , L1398 , XXREAL_0:14;
thus L1401: thesis by L1400 , L1388 , L1389 , L1398 , L1178;
end;
suppose L1402: R6 = ( -infty );

assume L1403: R6 <> R7;
L1404: (R7 in ( REAL ) or R7 = ( +infty )) by L1403 , L1402 , XXREAL_0:14;
thus L1405: thesis by L1404 , L1388 , L1389 , L1402 , L1178;
end;
end;
theorem
L1407: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((R1 <> ( +infty ) & R1 <> ( -infty ) & ( R1 * R2 ) = ( +infty )) implies (R2 = ( +infty ) or R2 = ( -infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L1408: (R1 <> ( +infty ) & R1 <> ( -infty ))
and
L1409: ( R1 * R2 ) = ( +infty );
assume L1410: (R2 <> ( +infty ) & R2 <> ( -infty ));
L1411: R2 in ( REAL ) by L1410 , XXREAL_0:14;
L1412: R1 in ( REAL ) by L1408 , XXREAL_0:14;
reconsider D102 = R1 , D103 = R2 as  real number by L1412 , L1411;
L1413: ( R1 * R2 ) = ( D102 * D103 );
thus L1414: contradiction by L1413 , L1409;
end;
theorem
L1415: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((R1 <> ( +infty ) & R1 <> ( -infty ) & ( R1 * R2 ) = ( -infty )) implies (R2 = ( +infty ) or R2 = ( -infty )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L1416: (R1 <> ( +infty ) & R1 <> ( -infty ))
and
L1417: ( R1 * R2 ) = ( -infty );
assume L1418: (R2 <> ( +infty ) & R2 <> ( -infty ));
L1419: R2 in ( REAL ) by L1418 , XXREAL_0:14;
L1420: R1 in ( REAL ) by L1416 , XXREAL_0:14;
reconsider D104 = R1 , D105 = R2 as  real number by L1420 , L1419;
L1421: ( R1 * R2 ) = ( D104 * D105 );
thus L1422: contradiction by L1421 , L1417;
end;
L1423: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 * R2 ) in ( REAL ) implies ((R1 in ( REAL ) & R2 in ( REAL )) or ( R1 * R2 ) = ( 0 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume L1424: ( R1 * R2 ) in ( REAL );
assume L1425: ((not R1 in ( REAL )) or (not R2 in ( REAL )));
L1426: ((not R1 is  real) or (not R2 is  real)) by L1425 , XREAL_0:def 1;
assume L1427: ( R1 * R2 ) <> ( 0 );
per cases  by L1427;
suppose L1428: ((R1 is  positive & R2 is  positive) or (R1 is  negative & R2 is  negative));

thus L1429: contradiction by L1428 , L1424 , L1426 , L1178;
end;
suppose L1430: ((R1 is  positive & R2 is  negative) or (R1 is  negative & R2 is  positive));

thus L1431: contradiction by L1430 , L1424 , L1426 , L1178;
end;
end;
theorem
L1433: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 <= R2 & ( 0 ) <= R3) implies ( R1 * R3 ) <= ( R2 * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1434: R1 <= R2
and
L1435: ( 0 ) <= R3;
per cases  by L1435;
suppose L1436: R3 = ( 0 );

thus L1437: thesis by L1436;
end;
suppose L1438: R3 > ( 0 );

per cases ;
suppose L1439: R1 = ( 0 );

L1440: ( R3 * R2 ) >= ( 0 ) by L1439 , L1434 , L1435;
thus L1441: thesis by L1440 , L1439;
end;
suppose L1442: R1 <> ( 0 );

per cases ;
case that L1443: (( R1 * R3 ) in ( REAL ) & ( R2 * R3 ) in ( REAL ));
L1444: (( R2 * R3 ) = ( 0 ) implies R2 = ( 0 )) by L1438;
reconsider D106 = R1 , D107 = R2 , D108 = R3 as (Element of ( REAL )) by L1444 , L1438 , L1442 , L1443 , L1423;
reconsider D109 = ( D106 * D108 ) , D110 = ( D107 * D108 ) as (Element of ( REAL )) by XREAL_0:def 1;
take D109;
take D110;
thus L1445: thesis by L1434 , L1435 , XREAL_1:64;
end;
case L1446: ((not ( R1 * R3 ) in ( REAL )) or (not ( R2 * R3 ) in ( REAL )));
per cases  by L1446;
suppose L1447: (not ( R1 * R3 ) in ( REAL ));

per cases  by L1447 , XXREAL_0:14;
suppose L1448: ( R1 * R3 ) = ( -infty );

thus L1449: thesis by L1448;
end;
suppose L1450: ( R1 * R3 ) = ( +infty );

L1451: R1 <> ( -infty ) by L1450 , L1438;
L1452: ((not R1 in ( REAL )) or (not R2 in ( REAL )) or (not R3 in ( REAL ))) by L1447 , XREAL_0:def 1;
per cases  by L1451 , L1452 , XXREAL_0:14;
suppose L1453: R2 = ( +infty );

thus L1454: thesis by L1453 , L1438 , L1178;
end;
suppose L1455: R1 = ( +infty );

L1456: R2 = ( +infty ) by L1455 , L1434 , XXREAL_0:4;
thus L1457: thesis by L1456 , L1438 , L1178;
end;
suppose L1458: R2 = ( -infty );

L1459: R1 = ( -infty ) by L1458 , L1434 , XXREAL_0:6;
thus L1460: thesis by L1459 , L1438 , L1178;
end;
suppose that L1461: (not R3 in ( REAL ))
and
L1462: (R1 in ( REAL ) & R2 in ( REAL ));
L1463: R3 = ( +infty ) by L1438 , L1461 , XXREAL_0:14;
per cases  by L1442;
suppose L1464: R1 < ( 0 );

thus L1465: thesis by L1464 , L1463 , L1178;
end;
suppose L1466: ( 0 ) < R1;

thus L1467: thesis by L1466 , L1434 , L1463 , L1178;
end;
end;
end;
end;
suppose L1471: (not ( R2 * R3 ) in ( REAL ));

L1472: ((not R1 in ( REAL )) or (not R2 in ( REAL )) or (not R3 in ( REAL ))) by L1471 , XREAL_0:def 1;
per cases  by L1472 , XXREAL_0:14;
suppose L1473: R1 = ( -infty );

thus L1474: thesis by L1473 , L1438 , L1178;
end;
suppose L1475: R2 = ( +infty );

thus L1476: thesis by L1475 , L1438 , L1178;
end;
suppose L1477: R1 = ( +infty );

L1478: R2 = ( +infty ) by L1477 , L1434 , XXREAL_0:4;
thus L1479: thesis by L1478 , L1438 , L1178;
end;
suppose L1480: R2 = ( -infty );

L1481: R1 = ( -infty ) by L1480 , L1434 , XXREAL_0:6;
thus L1482: thesis by L1481 , L1438 , L1178;
end;
suppose that L1483: (not R3 in ( REAL ))
and
L1484: (R1 in ( REAL ) & R2 in ( REAL ));
L1485: R3 = ( +infty ) by L1438 , L1483 , XXREAL_0:14;
per cases  by L1442;
suppose L1486: R1 < ( 0 );

thus L1487: thesis by L1486 , L1485 , L1178;
end;
suppose L1488: ( 0 ) < R1;

thus L1489: thesis by L1488 , L1434 , L1485 , L1178;
end;
end;
end;
end;
end;
end;
end;
theorem
L1496: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 < R2 & ( 0 ) < R3 & R3 <> ( +infty )) implies ( R1 * R3 ) < ( R2 * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1497: R1 < R2
and
L1498: ( 0 ) < R3
and
L1499: R3 <> ( +infty );
L1500:
now
L1501: (R1 <> ( +infty ) & R2 <> ( -infty )) by L1497 , XXREAL_0:3 , XXREAL_0:5;
assume L1502: ( R1 * R3 ) = ( R2 * R3 );
per cases  by L1501 , XXREAL_0:14;
suppose L1503: (R1 in ( REAL ) & R2 in ( REAL ));

L1504: R3 in ( REAL ) by L1498 , L1499 , XXREAL_0:14;
reconsider D111 = R1 , D112 = R2 , D113 = R3 as  real number by L1504 , L1503;
L1505: ( D111 * D113 ) < ( D112 * D113 ) by L1497 , L1498 , XREAL_1:68;
thus L1506: contradiction by L1505 , L1502;
end;
suppose L1507: R2 = ( +infty );

L1508: ( R2 * R3 ) = ( +infty ) by L1507 , L1498 , L1178;
L1509: (R1 = ( +infty ) or R1 = ( -infty )) by L1508 , L1498 , L1499 , L1502 , L1407;
thus L1510: contradiction by L1509 , L1497 , L1498 , L1502 , L1507;
end;
suppose L1511: R1 = ( -infty );

L1512: ( R1 * R3 ) = ( -infty ) by L1511 , L1498 , L1178;
L1513: (R2 = ( +infty ) or R2 = ( -infty )) by L1512 , L1498 , L1499 , L1502 , L1415;
thus L1514: contradiction by L1513 , L1497 , L1498 , L1502 , L1511;
end;
end;
L1516: ( R1 * R3 ) <= ( R2 * R3 ) by L1497 , L1498 , L1433;
thus L1517: thesis by L1516 , L1500 , XXREAL_0:1;
end;
theorem
L1518: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (( R1 * R2 ) in ( REAL ) implies ((R1 in ( REAL ) & R2 in ( REAL )) or ( R1 * R2 ) = ( 0 ))))) by L1423;
theorem
L1519: ( ( +infty ) " ) = ( 0 );
theorem
L1520: ( ( -infty ) " ) = ( 0 );
theorem
L1521: (for R1 being  ext-real number holds ( R1 / ( +infty ) ) = ( 0 ));
theorem
L1522: (for R1 being  ext-real number holds ( R1 / ( -infty ) ) = ( 0 ));
theorem
L1523: (for R1 being  ext-real number holds ((R1 <> ( -infty ) & R1 <> ( +infty ) & R1 <> ( 0 )) implies ( R1 / R1 ) = 1))
proof
let R1 being  ext-real number;
assume L1524: (R1 <> ( -infty ) & R1 <> ( +infty ));
L1525: R1 in ( REAL ) by L1524 , XXREAL_0:14;
reconsider D114 = R1 as  real number by L1525;
assume L1526: R1 <> ( 0 );
L1527: ( D114 / D114 ) = 1 by L1526 , XCMPLX_1:60;
thus L1528: thesis by L1527;
end;
theorem
L1529: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 <= R2 & ( 0 ) < R3) implies ( R1 / R3 ) <= ( R2 / R3 ))))) by L1433;
theorem
L1530: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 < R2 & ( 0 ) < R3 & R3 <> ( +infty )) implies ( R1 / R3 ) < ( R2 / R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1531: R1 < R2
and
L1532: ( 0 ) < R3
and
L1533: R3 <> ( +infty );
per cases  by L1533 , XXREAL_0:14;
suppose L1534: R3 = ( -infty );

thus L1535: thesis by L1534 , L1532;
end;
suppose L1536: R3 in ( REAL );

reconsider D115 = R3 as  real number by L1536;
L1537: ( D115 " ) > ( 0 ) by L1532;
thus L1538: thesis by L1537 , L1531 , L1496;
end;
end;
theorem
L1540: (for R1 being  ext-real number holds ( 1 * R1 ) = R1)
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L1541: R1 in ( REAL );

reconsider D116 = R1 , D117 = 1 as  real number by L1541;
L1542: ( D117 * D116 ) = D116;
thus L1543: thesis by L1542;
end;
suppose L1544: (R1 = ( -infty ) or R1 = ( +infty ));

thus L1545: thesis by L1544 , L1178;
end;
end;
theorem
L1547: (for R2 being  ext-real number holds (( R2 " ) = ( 0 ) implies (R2 = ( +infty ) or R2 = ( -infty ) or R2 = ( 0 ))))
proof
let R2 being  ext-real number;
assume L1548: ( R2 " ) = ( 0 );
assume L1549: (R2 <> ( +infty ) & R2 <> ( -infty ));
L1550: R2 in ( REAL ) by L1549 , XXREAL_0:14;
reconsider D118 = R2 as  real number by L1550;
L1551: ( ( D118 " ) " ) = ( 0 ) by L1548;
thus L1552: thesis by L1551;
end;
theorem
L1553: (for R2 being  ext-real number holds ((( 0 ) < R2 & R2 <> ( +infty )) implies ( ( +infty ) / R2 ) = ( +infty )))
proof
let R2 being  ext-real number;
assume that
L1554: ( 0 ) < R2
and
L1555: R2 <> ( +infty );
L1556: ( R2 " ) <> ( 0 ) by L1554 , L1555 , L1547;
thus L1557: thesis by L1556 , L1554 , L1178;
end;
theorem
L1558: (for R2 being  ext-real number holds ((R2 < ( 0 ) & ( -infty ) <> R2) implies ( ( -infty ) / R2 ) = ( +infty )))
proof
let R2 being  ext-real number;
assume that
L1559: R2 < ( 0 )
and
L1560: ( -infty ) <> R2;
L1561: ( R2 " ) <> ( 0 ) by L1559 , L1560 , L1547;
thus L1562: thesis by L1561 , L1559 , L1178;
end;
theorem
L1563: (for R2 being  ext-real number holds ((R2 < ( 0 ) & ( -infty ) <> R2) implies ( ( +infty ) / R2 ) = ( -infty )))
proof
let R2 being  ext-real number;
assume that
L1564: R2 < ( 0 )
and
L1565: ( -infty ) <> R2;
L1566: ( R2 " ) <> ( 0 ) by L1564 , L1565 , L1547;
thus L1567: thesis by L1566 , L1564 , L1178;
end;
theorem
L1568: (for R2 being  ext-real number holds ((( 0 ) < R2 & R2 <> ( +infty )) implies ( ( -infty ) / R2 ) = ( -infty )))
proof
let R2 being  ext-real number;
assume that
L1569: ( 0 ) < R2
and
L1570: R2 <> ( +infty );
L1571: ( R2 " ) <> ( 0 ) by L1569 , L1570 , L1547;
thus L1572: thesis by L1571 , L1569 , L1178;
end;
theorem
L1573: (for R1 being  ext-real number holds ((R1 <> ( +infty ) & R1 <> ( -infty ) & R1 <> ( 0 )) implies (( R1 * ( 1 / R1 ) ) = 1 & ( ( 1 / R1 ) * R1 ) = 1)))
proof
let R1 being  ext-real number;
assume that
L1574: (R1 <> ( +infty ) & R1 <> ( -infty ))
and
L1575: R1 <> ( 0 );
L1576: R1 in ( REAL ) by L1574 , XXREAL_0:14;
reconsider D119 = R1 as  real number by L1576;
L1577: ( R1 * ( 1 / R1 ) ) = ( D119 * ( 1 / D119 ) )
.= 1 by L1575 , XCMPLX_1:106;
thus L1578: thesis by L1577;
end;
theorem
L1579: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((( -infty ) <> R2 & R2 <> ( +infty ) & R2 <> ( 0 )) implies (( ( R1 * R2 ) / R2 ) = R1 & ( R1 * ( R2 / R2 ) ) = R1))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L1580: ( -infty ) <> R2
and
L1581: R2 <> ( +infty )
and
L1582: R2 <> ( 0 );
reconsider D120 = R2 as (Element of ( REAL )) by L1580 , L1581 , XXREAL_0:14;
L1583: ( ( R1 * R2 ) / R2 ) = R1
proof
per cases ;
suppose L1584: R1 = ( +infty );

per cases  by L1582;
suppose L1585: ( 0 ) < R2;

L1586: ( R1 * R2 ) = ( +infty ) by L1585 , L1584 , L1178;
thus L1587: thesis by L1586 , L1581 , L1584 , L1585 , L1553;
end;
suppose L1588: R2 < ( 0 );

L1589: ( R1 * R2 ) = ( -infty ) by L1588 , L1584 , L1178;
thus L1590: thesis by L1589 , L1580 , L1584 , L1588 , L1558;
end;
end;
suppose L1592: R1 = ( -infty );

per cases  by L1582;
suppose L1593: ( 0 ) < R2;

L1594: ( R1 * R2 ) = ( -infty ) by L1593 , L1592 , L1178;
thus L1595: thesis by L1594 , L1581 , L1592 , L1593 , L1568;
end;
suppose L1596: R2 < ( 0 );

L1597: ( R1 * R2 ) = ( +infty ) by L1596 , L1592 , L1178;
thus L1598: thesis by L1597 , L1580 , L1592 , L1596 , L1563;
end;
end;
suppose L1600: (R1 <> ( +infty ) & R1 <> ( -infty ));

L1601: R1 in ( REAL ) by L1600 , XXREAL_0:14;
reconsider D121 = R1 as  real number by L1601;
L1602: ( ( R1 * R2 ) / R2 ) = ( ( D121 * D120 ) / D120 )
.= D121 by L1582 , XCMPLX_1:89;
thus L1603: thesis by L1602;
end;
end;
L1605: ( R2 / R2 ) = 1 by L1580 , L1581 , L1582 , L1523;
thus L1606: thesis by L1605 , L1583 , L1540;
end;
theorem
L1607: (for R2 being  ext-real number holds (( ( +infty ) * R2 ) <> 1 & ( ( -infty ) * R2 ) <> 1))
proof
let R2 being  ext-real number;
L1608: (R2 = ( 0 ) or ( 0 ) < R2 or R2 < ( 0 ));
thus L1609: thesis by L1608 , L1178;
end;
theorem
L1610: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ((( R1 * R2 ) <> ( +infty ) & ( R1 * R2 ) <> ( -infty )) implies (R1 in ( REAL ) or R2 in ( REAL )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
assume that
L1611: ( R1 * R2 ) <> ( +infty )
and
L1612: ( R1 * R2 ) <> ( -infty );
assume L1613: ((not R1 in ( REAL )) & (not R2 in ( REAL )));
per cases  by L1613 , XXREAL_0:14;
suppose L1614: (R1 = ( +infty ) & R2 = ( +infty ));

thus L1615: contradiction by L1614 , L1611 , L1178;
end;
suppose L1616: (R1 = ( +infty ) & R2 = ( -infty ));

thus L1617: contradiction by L1616 , L1612 , L1178;
end;
suppose L1618: (R1 = ( -infty ) & R2 = ( +infty ));

thus L1619: contradiction by L1618 , L1612 , L1178;
end;
suppose L1620: (R1 = ( -infty ) & R2 = ( -infty ));

thus L1621: contradiction by L1620 , L1611 , L1178;
end;
end;
begin
theorem
L1623: (for R1 being  ext-real number holds ( ( - 1 ) * R1 ) = ( - R1 ))
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L1624: R1 in ( REAL );

reconsider D122 = R1 , D123 = ( - 1 ) as  real number by L1624;
L1625: ( D123 * D122 ) = ( - D122 );
thus L1626: thesis by L1625;
end;
suppose L1627: R1 = ( -infty );

thus L1628: ( ( - 1 ) * R1 ) = ( +infty ) by L1627 , L1178
.= ( - R1 ) by L1627 , L44;
end;
suppose L1629: R1 = ( +infty );

thus L1630: ( ( - 1 ) * R1 ) = ( -infty ) by L1629 , L1178
.= ( - R1 ) by L1629 , L44;
end;
end;
theorem
L1632: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ( - ( R1 * R2 ) ) = ( ( - R1 ) * R2 )))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
thus L1633: ( - ( R1 * R2 ) ) = ( ( - 1 ) * ( R1 * R2 ) ) by L1623
.= ( ( ( - 1 ) * R1 ) * R2 ) by L1352
.= ( ( - R1 ) * R2 ) by L1623;
end;
theorem
L1634: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R2 = ( - R3 ) implies ( R1 * ( R2 + R3 ) ) = ( ( R1 * R2 ) + ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1635: R2 = ( - R3 );
thus L1636: ( R1 * ( R2 + R3 ) ) = ( R1 * ( 0 ) ) by L1635 , L91
.= ( ( R1 * R2 ) - ( R1 * R2 ) ) by L91
.= ( ( R1 * R2 ) + ( R1 * ( - R2 ) ) ) by L1632
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1635;
end;
theorem
L1637: (for R1 being  ext-real number holds ( 2 * R1 ) = ( R1 + R1 ))
proof
let R1 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L1638: R1 in ( REAL );

reconsider D124 = R1 as  real number by L1638;
L1639: ( 2 * D124 ) = ( D124 + D124 );
thus L1640: thesis by L1639;
end;
suppose L1641: R1 = ( -infty );

thus L1642: ( 2 * R1 ) = ( -infty ) by L1641 , L1178
.= ( R1 + R1 ) by L1641 , L38;
end;
suppose L1643: R1 = ( +infty );

thus L1644: ( 2 * R1 ) = ( +infty ) by L1643 , L1178
.= ( R1 + R1 ) by L1643 , L38;
end;
end;
L1646: (for R1 being  ext-real number holds (for R2 being  ext-real number holds ( R1 * ( R2 + R2 ) ) = ( ( R1 * R2 ) + ( R1 * R2 ) )))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
thus L1647: ( R1 * ( R2 + R2 ) ) = ( R1 * ( 2 * R2 ) ) by L1637
.= ( 2 * ( R1 * R2 ) ) by L1352
.= ( ( R1 * R2 ) + ( R1 * R2 ) ) by L1637;
end;
L1648: (for R1 being  ext-real number holds (for R3 being  ext-real number holds ( R1 * ( ( 0 ) + R3 ) ) = ( ( R1 * ( 0 ) ) + ( R1 * R3 ) )))
proof
let R1 being  ext-real number;
let R3 being  ext-real number;
thus L1649: ( R1 * ( ( 0 ) + R3 ) ) = ( R1 * R3 ) by L80
.= ( ( R1 * ( 0 ) ) + ( R1 * R3 ) ) by L80;
end;
L1650: (for R2 being  ext-real number holds (for R3 being  ext-real number holds ( ( 0 ) * ( R2 + R3 ) ) = ( ( ( 0 ) * R2 ) + ( ( 0 ) * R3 ) )));
L1651: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 is  real & R2 is  real) implies ( R1 * ( R2 + R3 ) ) = ( ( R1 * R2 ) + ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1652: R1 is  real
and
L1653: R2 is  real;
reconsider D125 = R1 , D126 = R2 as  real number by L1652 , L1653;
L1654: ( R1 * R2 ) = ( D125 * D126 );
per cases  by XXREAL_0:14;
suppose L1655: R3 in ( REAL );

reconsider D127 = R3 as  real number by L1655;
reconsider D128 = ( D126 + D127 ) , D129 = ( D125 * D126 ) , D130 = ( D125 * D127 ) as  real number;
L1656: ( D125 * D128 ) = ( D129 + D130 );
thus L1657: thesis by L1656;
end;
suppose L1658: R3 = ( -infty );

L1659: ( R2 + R3 ) = ( -infty ) by L1658 , L1653 , L38;
per cases ;
suppose L1660: R1 is  zero;

thus L1661: thesis by L1660 , L1650;
end;
suppose L1662: R1 is  positive;

thus L1663: ( R1 * ( R2 + R3 ) ) = ( -infty ) by L1662 , L1659 , L1178
.= ( ( R1 * R2 ) + ( -infty ) ) by L1654 , L38
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1658 , L1662 , L1178;
end;
suppose L1664: R1 is  negative;

thus L1665: ( R1 * ( R2 + R3 ) ) = ( +infty ) by L1664 , L1659 , L1178
.= ( ( R1 * R2 ) + ( +infty ) ) by L1654 , L38
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1658 , L1664 , L1178;
end;
end;
suppose L1667: R3 = ( +infty );

L1668: ( R2 + R3 ) = ( +infty ) by L1667 , L1653 , L38;
per cases ;
suppose L1669: R1 is  zero;

thus L1670: thesis by L1669 , L1650;
end;
suppose L1671: R1 is  positive;

thus L1672: ( R1 * ( R2 + R3 ) ) = ( +infty ) by L1671 , L1668 , L1178
.= ( ( R1 * R2 ) + ( +infty ) ) by L1654 , L38
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1667 , L1671 , L1178;
end;
suppose L1673: R1 is  negative;

thus L1674: ( R1 * ( R2 + R3 ) ) = ( -infty ) by L1673 , L1668 , L1178
.= ( ( R1 * R2 ) + ( -infty ) ) by L1654 , L38
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1667 , L1673 , L1178;
end;
end;
end;
L1677: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 is  real & (not R2 is  real)) implies ( R1 * ( R2 + R3 ) ) = ( ( R1 * R2 ) + ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1678: R1 is  real
and
L1679: (not R2 is  real);
per cases ;
suppose L1680: R3 is  real;

thus L1681: thesis by L1680 , L1678 , L1651;
end;
suppose L1682: (not R3 is  real);

L1683: (not R3 in ( REAL )) by L1682;
L1684: (not R2 in ( REAL )) by L1679;
per cases  by L1684 , L1683 , XXREAL_0:14;
suppose L1685: (R2 = ( -infty ) & R3 = ( -infty ));

thus L1686: thesis by L1685 , L1646;
end;
suppose L1687: (R2 = ( -infty ) & R3 = ( +infty ));

thus L1688: thesis by L1687 , L87 , L1634;
end;
suppose L1689: (R2 = ( +infty ) & R3 = ( -infty ));

thus L1690: thesis by L1689 , L88 , L1634;
end;
suppose L1691: (R2 = ( +infty ) & R3 = ( +infty ));

thus L1692: thesis by L1691 , L1646;
end;
end;
end;
theorem
L1695: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R1 is  real implies ( R1 * ( R2 + R3 ) ) = ( ( R1 * R2 ) + ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1696: R1 is  real;
per cases ;
suppose L1697: (R2 is  real & R3 is  real);

thus L1698: thesis by L1697 , L1696 , L1651;
end;
suppose L1699: ((not R2 is  real) or (not R3 is  real));

thus L1700: thesis by L1699 , L1696 , L1677;
end;
end;
theorem
L1702: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R2 >= ( 0 ) & R3 >= ( 0 )) implies ( R1 * ( R2 + R3 ) ) = ( ( R1 * R2 ) + ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1703: (R2 >= ( 0 ) & R3 >= ( 0 ));
per cases  by L1703;
suppose L1704: (R2 = ( 0 ) or R3 = ( 0 ));

thus L1705: thesis by L1704 , L1648;
end;
suppose L1706: (R2 > ( 0 ) & R3 > ( 0 ));

per cases ;
suppose L1707: R1 is  real;

thus L1708: thesis by L1707 , L1695;
end;
suppose L1709: (not R1 is  real);

L1710: (not R1 in ( REAL )) by L1709;
per cases  by L1710 , XXREAL_0:14;
suppose L1711: R1 = ( -infty );

thus L1712: ( R1 * ( R2 + R3 ) ) = ( -infty ) by L1711 , L1706 , L1178
.= ( ( -infty ) + ( R1 * R3 ) ) by L1706 , L1711 , L38
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1706 , L1711 , L1178;
end;
suppose L1713: R1 = ( +infty );

thus L1714: ( R1 * ( R2 + R3 ) ) = ( +infty ) by L1713 , L1706 , L1178
.= ( ( +infty ) + ( R1 * R3 ) ) by L1706 , L1713 , L38
.= ( ( R1 * R2 ) + ( R1 * R3 ) ) by L1706 , L1713 , L1178;
end;
end;
end;
end;
theorem
L1718: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R2 <= ( 0 ) & R3 <= ( 0 )) implies ( R1 * ( R2 + R3 ) ) = ( ( R1 * R2 ) + ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1719: (R2 <= ( 0 ) & R3 <= ( 0 ));
thus L1720: ( R1 * ( R2 + R3 ) ) = ( - ( - ( R1 * ( R2 + R3 ) ) ) )
.= ( - ( R1 * ( - ( R2 + R3 ) ) ) ) by L1632
.= ( - ( R1 * ( ( - R2 ) + ( - R3 ) ) ) ) by L132
.= ( - ( ( R1 * ( - R2 ) ) + ( R1 * ( - R3 ) ) ) ) by L1719 , L1702
.= ( - ( ( - ( R1 * R2 ) ) + ( R1 * ( - R3 ) ) ) ) by L1632
.= ( - ( ( - ( R1 * R2 ) ) + ( - ( R1 * R3 ) ) ) ) by L1632
.= ( - ( - ( ( R1 * R2 ) + ( R1 * R3 ) ) ) ) by L132
.= ( ( R1 * R2 ) + ( R1 * R3 ) );
end;
theorem
L1721: (for R1 being  ext-real number holds (for R3 being  ext-real number holds ( R1 * ( ( 0 ) + R3 ) ) = ( ( R1 * ( 0 ) ) + ( R1 * R3 ) ))) by L1648;
theorem
L1722: (for R6 being  ext-real number holds ( ( - R6 ) " ) = ( - ( R6 " ) ))
proof
let R6 being  ext-real number;
per cases  by XXREAL_0:14;
suppose L1723: R6 in ( REAL );

reconsider D131 = R6 as  real number by L1723;
L1724: ( - R6 ) = ( - D131 );
consider C107 being  complex number such that L1725: R6 = C107 and L1726: ( R6 " ) = ( C107 " ) by L1723 , L1185;
L1727: ( ( - C107 ) " ) = ( - ( C107 " ) ) by XCMPLX_1:222;
L1728: (ex B46 being  complex number st (( - R6 ) = B46 & ( - ( R6 " ) ) = ( B46 " )))
proof
take ( - C107 );
thus L1729: ( - R6 ) = ( - C107 ) by L1725 , L1724;
thus L1730: thesis by L1726 , L1727 , L1724 , L44;
end;
thus L1731: thesis by L1728 , L1724 , L1185;
end;
suppose L1732: R6 = ( +infty );

thus L1733: ( ( - R6 ) " ) = ( ( -infty ) " ) by L1732 , L44
.= ( - ( R6 " ) ) by L1732;
end;
suppose L1734: R6 = ( -infty );

thus L1735: ( ( - R6 ) " ) = ( ( +infty ) " ) by L1734 , L44
.= ( - ( R6 " ) ) by L1734;
end;
end;
theorem
L1737: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds (R1 is  real implies ( R1 * ( R2 - R3 ) ) = ( ( R1 * R2 ) - ( R1 * R3 ) )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1738: R1 is  real;
L1739: ( R1 * ( R2 - R3 ) ) = ( ( R1 * R2 ) + ( R1 * ( - R3 ) ) ) by L1738 , L1695
.= ( ( R1 * R2 ) + ( - ( R1 * R3 ) ) ) by L1632;
thus L1740: thesis by L1739;
end;
theorem
L1741: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 <= R2 & R3 <= ( 0 )) implies ( R2 * R3 ) <= ( R1 * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1742: (R1 <= R2 & R3 <= ( 0 ));
L1743: ( R1 * ( - R3 ) ) <= ( R2 * ( - R3 ) ) by L1742 , L1433;
L1744: (( - ( R1 * R3 ) ) = ( R1 * ( - R3 ) ) & ( - ( R2 * R3 ) ) = ( R2 * ( - R3 ) )) by L1632;
thus L1745: thesis by L1744 , L1743 , L662;
end;
theorem
L1746: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 < R2 & R3 < ( 0 ) & R3 <> ( -infty )) implies ( R2 * R3 ) < ( R1 * R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume L1747: (R1 < R2 & R3 < ( 0 ) & R3 <> ( -infty ));
L1748: ( R1 * ( - R3 ) ) < ( R2 * ( - R3 ) ) by L1747 , L87 , L153 , L1496;
L1749: (( - ( R1 * R3 ) ) = ( R1 * ( - R3 ) ) & ( - ( R2 * R3 ) ) = ( R2 * ( - R3 ) )) by L1632;
thus L1750: thesis by L1749 , L1748 , L662;
end;
theorem
L1751: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 <= R2 & R3 < ( 0 )) implies ( R2 / R3 ) <= ( R1 / R3 ))))) by L1741;
theorem
L1752: (for R1 being  ext-real number holds (for R2 being  ext-real number holds (for R3 being  ext-real number holds ((R1 < R2 & R3 < ( 0 ) & R3 <> ( -infty )) implies ( R2 / R3 ) < ( R1 / R3 )))))
proof
let R1 being  ext-real number;
let R2 being  ext-real number;
let R3 being  ext-real number;
assume that
L1753: R1 < R2
and
L1754: ( 0 ) > R3
and
L1755: R3 <> ( -infty );
per cases  by L1755 , XXREAL_0:14;
suppose L1756: R3 = ( +infty );

thus L1757: thesis by L1756 , L1754;
end;
suppose L1758: R3 in ( REAL );

reconsider D132 = R3 as  real number by L1758;
L1759: ( D132 " ) < ( 0 ) by L1754;
thus L1760: thesis by L1759 , L1753 , L1746;
end;
end;
theorem
L1762: (for R1 being  ext-real number holds ( ( R1 / 2 ) + ( R1 / 2 ) ) = R1)
proof
let R1 being  ext-real number;
L1763: ( ( R1 / 2 ) + ( R1 / 2 ) ) = ( ( R1 + R1 ) / 2 ) by L1695
.= ( ( 2 * R1 ) / 2 ) by L1637
.= ( R1 * ( 2 / 2 ) ) by L1352
.= R1 by L1540;
thus L1764: thesis by L1763;
end;
