:: Boolean Posets, Posets under Inclusion and Products of Relational
:: Structures
::  by Adam Grabowski and Robert Milewski
::
:: Received September 20, 1996
:: Copyright (c) 1996-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies LATTICES, LATTICE3, SUBSET_1, STRUCT_0, EQREL_1, XBOOLE_0,
      PBOOLE, XXREAL_0, REWRITE1, WELLORD2, ORDERS_1, RELAT_1, ZFMISC_1,
      RELAT_2, ORDERS_2, TARSKI, SETFAM_1, CAT_1, YELLOW_0, WELLORD1, ORDINAL2,
      PRE_TOPC, RCOMP_1, PRALG_1, FUNCT_1, FUNCOP_1, CARD_3, RLVECT_2, NEWTON,
      FUNCT_2, SEQM_3, ORDERS_3, YELLOW_1, CARD_1;
 notations TARSKI, XBOOLE_0, ZFMISC_1, SUBSET_1, RELAT_1, RELAT_2, RELSET_1,
      SETFAM_1, FUNCT_1, ORDERS_1, CARD_3, PBOOLE, WELLORD2, TOLER_1, PARTFUN1,
      FUNCT_2, STRUCT_0, ORDERS_2, TOPS_2, LATTICES, ORDERS_3, LATTICE3,
      PRE_TOPC, FUNCOP_1, PRALG_1, YELLOW_0;
 constructors SETFAM_1, WELLORD2, TOLER_1, TOPS_2, LATTICE3, YELLOW_0, PRALG_1,
      ORDERS_3, CARD_3, RELSET_1;
 registrations XBOOLE_0, SUBSET_1, RELSET_1, PARTFUN1, FUNCOP_1, STRUCT_0,
      LATTICES, PRE_TOPC, ORDERS_2, LATTICE3, YELLOW_0, PRE_CIRC, CARD_1,
      ORDINAL1, WELLORD1, WELLORD2;
 requirements SUBSET, BOOLE, NUMERALS;
 definitions LATTICE3, XBOOLE_0, TOPS_2, TARSKI, RELAT_1, PRALG_1;
 theorems TARSKI, LATTICES, LATTICE3, YELLOW_0, STRUCT_0, RELAT_1, ORDERS_2,
      RELAT_2, RELSET_1, ZFMISC_1, WELLORD2, SETFAM_1, PRE_TOPC, TOPS_2,
      FUNCT_1, FUNCOP_1, PBOOLE, CARD_3, FUNCT_2, PRALG_1, ORDERS_3, XBOOLE_0,
      XBOOLE_1, PARTFUN1, ORDERS_1;
 schemes RELSET_1, FUNCT_2;

begin
registration
let C1 being Lattice;
cluster ( LattPOSet C1 ) ->  with_suprema  with_infima;
coherence by LATTICE3:11;
end;
registration
let C2 being  upper-bounded Lattice;
cluster ( LattPOSet C2 ) ->  upper-bounded;
coherence
proof
L2: (ex B1 being (Element of ( LattPOSet C2 )) st B1 is_>=_than (the carrier of ( LattPOSet C2 )))
proof
take D1 = ( Top ( LattPOSet C2 ) );
consider C3 being (Element of C2) such that L3: (for B2 being (Element of C2) holds (( C3 "\/" B2 ) = C3 & ( B2 "\/" C3 ) = C3)) by LATTICES:def 14;
reconsider D2 = C3 as (Element of ( LattPOSet C2 ));
L4: C3 = ( Top C2 ) by L3 , LATTICES:def 17;
L5:
now
let C4 being (Element of ( LattPOSet C2 ));
reconsider D3 = C4 as (Element of C2);
assume L6: C4 is_<=_than ( {} );
L7: (( D3 % ) = D3 & ( C3 % ) = C3);
L8: D3 [= C3 by L4 , LATTICES:19;
thus L9: D2 >= C4 by L8 , L7 , LATTICE3:7;
end;
L10: D2 is_<=_than ( {} ) by YELLOW_0:6;
L11: D2 = ( "/\" (( {} ) , ( LattPOSet C2 )) ) by L10 , L5 , YELLOW_0:31;
L12:
now
reconsider D4 = D1 as (Element of C2);
let C5 being (Element of ( LattPOSet C2 ));
assume L13: C5 in (the carrier of ( LattPOSet C2 ));
reconsider D5 = C5 as (Element of C2);
L14: ( Top ( LattPOSet C2 ) ) = ( Top C2 ) by L4 , L11 , YELLOW_0:def 12;
L15: D5 [= D4 by L14 , LATTICES:19;
L16: (( D5 % ) = D5 & ( D4 % ) = D4);
thus L17: C5 <= D1 by L16 , L15 , LATTICE3:7;
end;
thus L18: thesis by L12 , LATTICE3:def 9;
end;
thus L19: thesis by L2 , YELLOW_0:def 5;
end;
end;
registration
let C6 being  lower-bounded Lattice;
cluster ( LattPOSet C6 ) ->  lower-bounded;
coherence
proof
L21: (ex B3 being (Element of ( LattPOSet C6 )) st B3 is_<=_than (the carrier of ( LattPOSet C6 )))
proof
take D6 = ( Bottom ( LattPOSet C6 ) );
consider C7 being (Element of C6) such that L22: (for B4 being (Element of C6) holds (( C7 "/\" B4 ) = C7 & ( B4 "/\" C7 ) = C7)) by LATTICES:def 13;
reconsider D7 = C7 as (Element of ( LattPOSet C6 ));
L23: C7 = ( Bottom C6 ) by L22 , LATTICES:def 16;
L24:
now
let C8 being (Element of ( LattPOSet C6 ));
reconsider D8 = C8 as (Element of C6);
assume L25: C8 is_>=_than ( {} );
L26: (( D8 % ) = D8 & ( C7 % ) = C7);
L27: C7 [= D8 by L23 , LATTICES:16;
thus L28: D7 <= C8 by L27 , L26 , LATTICE3:7;
end;
L29: D7 is_>=_than ( {} ) by YELLOW_0:6;
L30: D7 = ( "\/" (( {} ) , ( LattPOSet C6 )) ) by L29 , L24 , YELLOW_0:30;
L31:
now
reconsider D9 = D6 as (Element of C6);
let C9 being (Element of ( LattPOSet C6 ));
assume L32: C9 in (the carrier of ( LattPOSet C6 ));
reconsider D10 = C9 as (Element of C6);
L33: ( Bottom ( LattPOSet C6 ) ) = ( Bottom C6 ) by L23 , L30 , YELLOW_0:def 11;
L34: D9 [= D10 by L33 , LATTICES:16;
L35: (( D10 % ) = D10 & ( D9 % ) = D9);
thus L36: D6 <= C9 by L35 , L34 , LATTICE3:7;
end;
thus L37: thesis by L31 , LATTICE3:def 8;
end;
thus L38: thesis by L21 , YELLOW_0:def 4;
end;
end;
registration
let C10 being  complete Lattice;
cluster ( LattPOSet C10 ) ->  complete;
coherence
proof
L40: (for B5 being set holds (ex B6 being (Element of ( LattPOSet C10 )) st (B5 is_<=_than B6 & (for B7 being (Element of ( LattPOSet C10 )) holds (B5 is_<=_than B7 implies B6 <= B7)))))
proof
let C11 being set;
take D11 = ( "\/" (C11 , ( LattPOSet C10 )) );
L41: C11 is_less_than ( "\/" (C11 , C10) ) by LATTICE3:def 21;
L42: C11 is_<=_than ( ( "\/" (C11 , C10) ) % ) by L41 , LATTICE3:30;
thus L43: C11 is_<=_than D11 by L42 , YELLOW_0:29;
let C12 being (Element of ( LattPOSet C10 ));
reconsider D12 = C12 as (Element of C10);
assume L44: C11 is_<=_than C12;
L45: C11 is_<=_than ( D12 % ) by L44;
L46: C11 is_less_than D12 by L45 , LATTICE3:30;
L47: ( "\/" (C11 , C10) ) [= D12 by L46 , LATTICE3:def 21;
L48: (( ( "\/" (C11 , C10) ) % ) = D11 & ( D12 % ) = C12) by YELLOW_0:29;
thus L49: thesis by L48 , L47 , LATTICE3:7;
end;
thus L50: thesis by L40 , LATTICE3:def 12;
end;
end;
definition
let C13 being set;
redefine func RelIncl C13 -> (Order of C13);

coherence
proof
L52:
now
let C14 being set;
assume L53: C14 in ( RelIncl C13 );
consider C15 , C16 being set such that L54: C14 = [ C15 , C16 ] by L53 , RELAT_1:def 1;
L55: C16 in ( field ( RelIncl C13 ) ) by L53 , L54 , RELAT_1:15;
L56: C16 in C13 by L55 , WELLORD2:def 1;
L57: C15 in ( field ( RelIncl C13 ) ) by L53 , L54 , RELAT_1:15;
L58: C15 in C13 by L57 , WELLORD2:def 1;
thus L59: C14 in [: C13 , C13 :] by L58 , L54 , L56 , ZFMISC_1:87;
end;
reconsider D13 = ( RelIncl C13 ) as (Relation of C13) by L52 , TARSKI:def 3;
L60: (( field D13 ) = C13 & D13 is  reflexive) by WELLORD2:def 1;
L61: D13 is_reflexive_in C13 by L60 , RELAT_2:def 9;
L62: ( dom D13 ) = C13 by L61 , ORDERS_1:13;
thus L63: thesis by L62 , PARTFUN1:def 2;
end;
end;
definition
let C17 being set;
func InclPoset C17 ->  strict RelStr equals 
RelStr (# C17 , ( RelIncl C17 ) #);
correctness;
end;
registration
let C18 being set;
cluster ( InclPoset C18 ) ->  reflexive  antisymmetric  transitive;
coherence;
end;
registration
let C19 being non  empty set;
cluster ( InclPoset C19 ) -> non  empty;
coherence;
end;
theorem
L68: (for R1 being set holds ((the carrier of ( InclPoset R1 )) = R1 & (the InternalRel of ( InclPoset R1 )) = ( RelIncl R1 )));
definition
let C20 being set;
func BoolePoset C20 ->  strict RelStr equals 
( LattPOSet ( BooleLatt C20 ) );
correctness;
end;
registration
let C21 being set;
cluster ( BoolePoset C21 ) -> non  empty  reflexive  antisymmetric  transitive;
coherence;
end;
registration
let C22 being set;
cluster ( BoolePoset C22 ) ->  complete;
coherence;
end;
theorem
L72: (for R1 being set holds (for B8 , B9 being (Element of ( BoolePoset R1 )) holds (B8 <= B9 iff B8 c= B9)))
proof
let R1 being set;
let C23 , C24 being (Element of ( BoolePoset R1 ));
reconsider D14 = C23 , D15 = C24 as (Element of ( BooleLatt R1 ));
thus L73: (C23 <= C24 implies C23 c= C24)
proof
assume L74: C23 <= C24;
L75: ( D14 % ) <= ( D15 % ) by L74;
L76: D14 [= D15 by L75 , LATTICE3:7;
thus L77: thesis by L76 , LATTICE3:2;
end;

assume L78: C23 c= C24;
L79: D14 [= D15 by L78 , LATTICE3:2;
L80: ( D14 % ) <= ( D15 % ) by L79 , LATTICE3:7;
thus L81: thesis by L80;
end;
theorem
L82: (for B10 being non  empty set holds (for B11 , B12 being (Element of ( InclPoset B10 )) holds (B11 <= B12 iff B11 c= B12)))
proof
let C25 being non  empty set;
let C26 , C27 being (Element of ( InclPoset C25 ));
thus L83: (C26 <= C27 implies C26 c= C27)
proof
assume L84: C26 <= C27;
L85: [ C26 , C27 ] in (the InternalRel of ( InclPoset C25 )) by L84 , ORDERS_2:def 5;
thus L86: thesis by L85 , WELLORD2:def 1;
end;

thus L87: (C26 c= C27 implies C26 <= C27)
proof
assume L88: C26 c= C27;
L89: [ C26 , C27 ] in ( RelIncl C25 ) by L88 , WELLORD2:def 1;
thus L90: thesis by L89 , ORDERS_2:def 5;
end;

end;
theorem
L88: (for R1 being set holds ( BoolePoset R1 ) = ( InclPoset ( bool R1 ) ))
proof
let R1 being set;
set D16 = ( BoolePoset R1 );
L89: (the carrier of D16) = ( bool R1 ) by LATTICE3:def 1;
reconsider D17 = (the InternalRel of D16) as (Relation of ( bool R1 )) by L89;
L90: (for B13 being set holds (B13 in ( bool R1 ) implies (ex B14 being set st [ B13 , B14 ] in D17)))
proof
let C28 being set;
assume L91: C28 in ( bool R1 );
reconsider D18 = C28 as (Element of D16) by L91 , LATTICE3:def 1;
take D19 = D18;
L92: D18 <= D19;
thus L93: thesis by L92 , ORDERS_2:def 5;
end;
L94: ( dom D17 ) = ( bool R1 ) by L90 , RELSET_1:9;
L95:
now
let C29 , C30 being set;
assume L96: (C29 in ( bool R1 ) & C30 in ( bool R1 ));
reconsider D20 = C29 , D21 = C30 as (Element of D16) by L96 , LATTICE3:def 1;
thus L97: ([ C29 , C30 ] in (the InternalRel of D16) implies C29 c= C30)
proof
assume L98: [ C29 , C30 ] in (the InternalRel of D16);
L99: D20 <= D21 by L98 , ORDERS_2:def 5;
thus L100: thesis by L99 , L72;
end;

thus L101: (C29 c= C30 implies [ C29 , C30 ] in (the InternalRel of D16))
proof
assume L102: C29 c= C30;
L103: D20 <= D21 by L102 , L72;
thus L104: thesis by L103 , ORDERS_2:def 5;
end;

end;
L102: (for B15 being set holds (B15 in ( bool R1 ) implies (ex B16 being set st [ B16 , B15 ] in D17)))
proof
let C31 being set;
assume L103: C31 in ( bool R1 );
reconsider D22 = C31 as (Element of D16) by L103 , LATTICE3:def 1;
take D23 = D22;
L104: D23 <= D22;
thus L105: thesis by L104 , ORDERS_2:def 5;
end;
L106: ( field (the InternalRel of D16) ) = ( ( bool R1 ) \/ ( bool R1 ) ) by L102 , L94 , RELSET_1:10;
L107: (the InternalRel of D16) = ( RelIncl ( bool R1 ) ) by L106 , L95 , WELLORD2:def 1;
thus L108: thesis by L107 , LATTICE3:def 1;
end;
theorem
L109: (for R1 being set holds (for B17 being (Subset-Family of R1) holds ( InclPoset B17 ) is  full  full  full  full (SubRelStr of ( BoolePoset R1 ))))
proof
let R1 being set;
set D24 = ( BoolePoset R1 );
let C32 being (Subset-Family of R1);
reconsider D25 = C32 as (Subset of D24) by LATTICE3:def 1;
L110: (the carrier of D24) = ( bool R1 ) by LATTICE3:def 1;
reconsider D26 = (the InternalRel of D24) as (Relation of ( bool R1 )) by L110;
L111: (for B18 being set holds (B18 in ( bool R1 ) implies (ex B19 being set st [ B18 , B19 ] in D26)))
proof
let C33 being set;
assume L112: C33 in ( bool R1 );
reconsider D27 = C33 as (Element of D24) by L112 , LATTICE3:def 1;
take D28 = D27;
L113: D27 <= D28;
thus L114: thesis by L113 , ORDERS_2:def 5;
end;
L115: ( dom D26 ) = ( bool R1 ) by L111 , RELSET_1:9;
L116:
now
let C34 , C35 being set;
assume L117: (C34 in ( bool R1 ) & C35 in ( bool R1 ));
reconsider D29 = C34 , D30 = C35 as (Element of D24) by L117 , LATTICE3:def 1;
thus L118: ([ C34 , C35 ] in (the InternalRel of D24) implies C34 c= C35)
proof
assume L119: [ C34 , C35 ] in (the InternalRel of D24);
L120: D29 <= D30 by L119 , ORDERS_2:def 5;
thus L121: thesis by L120 , L72;
end;

thus L122: (C34 c= C35 implies [ C34 , C35 ] in (the InternalRel of D24))
proof
assume L123: C34 c= C35;
L124: D29 <= D30 by L123 , L72;
thus L125: thesis by L124 , ORDERS_2:def 5;
end;

end;
L123: (for B20 being set holds (B20 in ( bool R1 ) implies (ex B21 being set st [ B21 , B20 ] in D26)))
proof
let C36 being set;
assume L124: C36 in ( bool R1 );
reconsider D31 = C36 as (Element of D24) by L124 , LATTICE3:def 1;
take D32 = D31;
L125: D32 <= D31;
thus L126: thesis by L125 , ORDERS_2:def 5;
end;
L127: ( field (the InternalRel of D24) ) = ( ( bool R1 ) \/ ( bool R1 ) ) by L123 , L115 , RELSET_1:10;
L128: (the InternalRel of D24) = ( RelIncl ( bool R1 ) ) by L127 , L116 , WELLORD2:def 1;
L129: RelStr (# D25 , ( (the InternalRel of D24) |_2 D25 ) #) is  full  full  full  full (SubRelStr of D24) by YELLOW_0:56;
thus L130: thesis by L129 , L128 , WELLORD2:7;
end;
theorem
L131: (for B22 being non  empty set holds (( InclPoset B22 ) is  with_suprema implies (for B23 , B24 being (Element of ( InclPoset B22 )) holds ( B23 \/ B24 ) c= ( B23 "\/" B24 ))))
proof
let C37 being non  empty set;
assume L132: ( InclPoset C37 ) is  with_suprema;
let C38 , C39 being (Element of ( InclPoset C37 ));
L133: C39 <= ( C38 "\/" C39 ) by L132 , YELLOW_0:22;
L134: C39 c= ( C38 "\/" C39 ) by L133 , L82;
L135: C38 <= ( C38 "\/" C39 ) by L132 , YELLOW_0:22;
L136: C38 c= ( C38 "\/" C39 ) by L135 , L82;
thus L137: thesis by L136 , L134 , XBOOLE_1:8;
end;
theorem
L138: (for B25 being non  empty set holds (( InclPoset B25 ) is  with_infima implies (for B26 , B27 being (Element of ( InclPoset B25 )) holds ( B26 "/\" B27 ) c= ( B26 /\ B27 ))))
proof
let C40 being non  empty set;
assume L139: ( InclPoset C40 ) is  with_infima;
let C41 , C42 being (Element of ( InclPoset C40 ));
L140: ( C41 "/\" C42 ) <= C42 by L139 , YELLOW_0:23;
L141: ( C41 "/\" C42 ) c= C42 by L140 , L82;
L142: ( C41 "/\" C42 ) <= C41 by L139 , YELLOW_0:23;
L143: ( C41 "/\" C42 ) c= C41 by L142 , L82;
thus L144: thesis by L143 , L141 , XBOOLE_1:19;
end;
theorem
L145: (for B28 being non  empty set holds (for B29 , B30 being (Element of ( InclPoset B28 )) holds (( B29 \/ B30 ) in B28 implies ( B29 "\/" B30 ) = ( B29 \/ B30 ))))
proof
let C43 being non  empty set;
let C44 , C45 being (Element of ( InclPoset C43 ));
assume L146: ( C44 \/ C45 ) in C43;
reconsider D33 = ( C44 \/ C45 ) as (Element of ( InclPoset C43 )) by L146;
L147: C45 c= D33 by XBOOLE_1:7;
L148: C45 <= D33 by L147 , L82;
L149:
now
let C46 being (Element of ( InclPoset C43 ));
assume L150: (C44 <= C46 & C45 <= C46);
L151: (C44 c= C46 & C45 c= C46) by L150 , L82;
L152: D33 c= C46 by L151 , XBOOLE_1:8;
thus L153: D33 <= C46 by L152 , L82;
end;
L154: C44 c= D33 by XBOOLE_1:7;
L155: C44 <= D33 by L154 , L82;
thus L156: thesis by L155 , L148 , L149 , LATTICE3:def 13;
end;
theorem
L157: (for B31 being non  empty set holds (for B32 , B33 being (Element of ( InclPoset B31 )) holds (( B32 /\ B33 ) in B31 implies ( B32 "/\" B33 ) = ( B32 /\ B33 ))))
proof
let C47 being non  empty set;
let C48 , C49 being (Element of ( InclPoset C47 ));
assume L158: ( C48 /\ C49 ) in C47;
reconsider D34 = ( C48 /\ C49 ) as (Element of ( InclPoset C47 )) by L158;
L159: D34 c= C49 by XBOOLE_1:17;
L160: D34 <= C49 by L159 , L82;
L161:
now
let C50 being (Element of ( InclPoset C47 ));
assume L162: (C50 <= C48 & C50 <= C49);
L163: (C50 c= C48 & C50 c= C49) by L162 , L82;
L164: C50 c= D34 by L163 , XBOOLE_1:19;
thus L165: C50 <= D34 by L164 , L82;
end;
L166: D34 c= C48 by XBOOLE_1:17;
L167: D34 <= C48 by L166 , L82;
thus L168: thesis by L167 , L160 , L161 , LATTICE3:def 14;
end;
theorem
L169: (for B34 being RelStr holds ((for B35 , B36 being (Element of B34) holds (B35 <= B36 iff B35 c= B36)) implies (the InternalRel of B34) = ( RelIncl (the carrier of B34) )))
proof
let C51 being RelStr;
assume L170: (for B37 , B38 being (Element of C51) holds (B37 <= B38 iff B37 c= B38));
L171:
now
let C52 , C53 being set;
assume L172: (C52 in (the carrier of C51) & C53 in (the carrier of C51));
reconsider D35 = C52 , D36 = C53 as (Element of C51) by L172;
thus L173: ([ C52 , C53 ] in (the InternalRel of C51) implies C52 c= C53)
proof
assume L174: [ C52 , C53 ] in (the InternalRel of C51);
L175: D35 <= D36 by L174 , ORDERS_2:def 5;
thus L176: thesis by L175 , L170;
end;

thus L177: (C52 c= C53 implies [ C52 , C53 ] in (the InternalRel of C51))
proof
assume L178: C52 c= C53;
L179: D35 <= D36 by L178 , L170;
thus L180: thesis by L179 , ORDERS_2:def 5;
end;

end;
L178: (for B39 being set holds (B39 in (the carrier of C51) implies (ex B40 being set st [ B39 , B40 ] in (the InternalRel of C51))))
proof
let C54 being set;
assume L179: C54 in (the carrier of C51);
reconsider D37 = C54 as (Element of C51) by L179;
take D38 = D37;
L180: D37 <= D38 by L170;
thus L181: thesis by L180 , ORDERS_2:def 5;
end;
L182: ( dom (the InternalRel of C51) ) = (the carrier of C51) by L178 , RELSET_1:9;
L183: (for B41 being set holds (B41 in (the carrier of C51) implies (ex B42 being set st [ B42 , B41 ] in (the InternalRel of C51))))
proof
let C55 being set;
assume L184: C55 in (the carrier of C51);
reconsider D39 = C55 as (Element of C51) by L184;
take D40 = D39;
L185: D40 <= D39 by L170;
thus L186: thesis by L185 , ORDERS_2:def 5;
end;
L187: ( field (the InternalRel of C51) ) = ( (the carrier of C51) \/ (the carrier of C51) ) by L183 , L182 , RELSET_1:10;
thus L188: thesis by L187 , L171 , WELLORD2:def 1;
end;
theorem
L189: (for B43 being non  empty set holds ((for B44 , B45 being set holds ((B44 in B43 & B45 in B43) implies ( B44 \/ B45 ) in B43)) implies ( InclPoset B43 ) is  with_suprema))
proof
let C56 being non  empty set;
set D41 = ( InclPoset C56 );
assume L190: (for B46 , B47 being set holds ((B46 in C56 & B47 in C56) implies ( B46 \/ B47 ) in C56));
L191:
now
let C57 , C58 being (Element of D41);
L192: (ex B48 being (Element of D41) st ({ C57 , C58 } is_<=_than B48 & (for B49 being (Element of D41) holds ({ C57 , C58 } is_<=_than B49 implies B48 <= B49))))
proof
take D42 = ( C57 "\/" C58 );
L193: ( C57 \/ C58 ) = D42 by L190 , L145;
L194: C58 c= D42 by L193 , XBOOLE_1:7;
L195: C58 <= D42 by L194 , L82;
L196: C57 c= D42 by L193 , XBOOLE_1:7;
L197: C57 <= D42 by L196 , L82;
thus L198: { C57 , C58 } is_<=_than D42 by L197 , L195 , YELLOW_0:8;
let C59 being (Element of D41);
assume L199: { C57 , C58 } is_<=_than C59;
L200: C58 in { C57 , C58 } by TARSKI:def 2;
L201: C58 <= C59 by L200 , L199 , LATTICE3:def 9;
L202: C58 c= C59 by L201 , L82;
L203: C57 in { C57 , C58 } by TARSKI:def 2;
L204: C57 <= C59 by L203 , L199 , LATTICE3:def 9;
L205: C57 c= C59 by L204 , L82;
L206: ( C57 \/ C58 ) c= C59 by L205 , L202 , XBOOLE_1:8;
L207: D42 c= C59 by L206 , L190 , L145;
thus L208: thesis by L207 , L82;
end;
thus L209:  ex_sup_of { C57 , C58 } , D41 by L192 , YELLOW_0:15;
end;
thus L210: thesis by L191 , YELLOW_0:20;
end;
theorem
L211: (for B50 being non  empty set holds ((for B51 , B52 being set holds ((B51 in B50 & B52 in B50) implies ( B51 /\ B52 ) in B50)) implies ( InclPoset B50 ) is  with_infima))
proof
let C60 being non  empty set;
set D43 = ( InclPoset C60 );
assume L212: (for B53 , B54 being set holds ((B53 in C60 & B54 in C60) implies ( B53 /\ B54 ) in C60));
L213:
now
let C61 , C62 being (Element of D43);
L214: (ex B55 being (Element of D43) st ({ C61 , C62 } is_>=_than B55 & (for B56 being (Element of D43) holds ({ C61 , C62 } is_>=_than B56 implies B55 >= B56))))
proof
take D44 = ( C61 "/\" C62 );
L215: ( C61 /\ C62 ) = D44 by L212 , L157;
L216: D44 c= C62 by L215 , XBOOLE_1:17;
L217: D44 <= C62 by L216 , L82;
L218: D44 c= C61 by L215 , XBOOLE_1:17;
L219: D44 <= C61 by L218 , L82;
thus L220: { C61 , C62 } is_>=_than D44 by L219 , L217 , YELLOW_0:8;
let C63 being (Element of D43);
assume L221: { C61 , C62 } is_>=_than C63;
L222: C62 in { C61 , C62 } by TARSKI:def 2;
L223: C63 <= C62 by L222 , L221 , LATTICE3:def 8;
L224: C63 c= C62 by L223 , L82;
L225: C61 in { C61 , C62 } by TARSKI:def 2;
L226: C63 <= C61 by L225 , L221 , LATTICE3:def 8;
L227: C63 c= C61 by L226 , L82;
L228: C63 c= ( C61 /\ C62 ) by L227 , L224 , XBOOLE_1:19;
L229: C63 c= D44 by L228 , L212 , L157;
thus L230: thesis by L229 , L82;
end;
thus L231:  ex_inf_of { C61 , C62 } , D43 by L214 , YELLOW_0:16;
end;
thus L232: thesis by L213 , YELLOW_0:21;
end;
theorem
L233: (for B57 being non  empty set holds (( {} ) in B57 implies ( Bottom ( InclPoset B57 ) ) = ( {} )))
proof
let C64 being non  empty set;
assume L234: ( {} ) in C64;
reconsider D45 = ( {} ) as (Element of ( InclPoset C64 )) by L234;
L235:
now
let C65 being (Element of ( InclPoset C64 ));
assume L236: C65 in C64;
L237: ( {} ) c= C65 by XBOOLE_1:2;
thus L238: D45 <= C65 by L237 , L82;
end;
L239: D45 is_<=_than C64 by L235 , LATTICE3:def 8;
L240: ( InclPoset C64 ) is  lower-bounded by L239 , YELLOW_0:def 4;
L241: (( {} ) is_<=_than D45 &  ex_sup_of ( {} ) , ( InclPoset C64 )) by L240 , YELLOW_0:6 , YELLOW_0:42;
L242: ( "\/" (( {} ) , ( InclPoset C64 )) ) <= D45 by L241 , YELLOW_0:def 9;
L243: ( "\/" (( {} ) , ( InclPoset C64 )) ) c= D45 by L242 , L82;
thus L244: ( Bottom ( InclPoset C64 ) ) = ( "\/" (( {} ) , ( InclPoset C64 )) ) by YELLOW_0:def 11
.= ( {} ) by L243;
end;
theorem
L245: (for B58 being non  empty set holds (( union B58 ) in B58 implies ( Top ( InclPoset B58 ) ) = ( union B58 )))
proof
let C66 being non  empty set;
assume L246: ( union C66 ) in C66;
reconsider D46 = ( union C66 ) as (Element of ( InclPoset C66 )) by L246;
L247:
now
let C67 being (Element of ( InclPoset C66 ));
assume L248: C67 in C66;
L249: C67 c= ( union C66 ) by ZFMISC_1:74;
thus L250: C67 <= D46 by L249 , L82;
end;
L251: D46 is_>=_than C66 by L247 , LATTICE3:def 9;
L252: ( InclPoset C66 ) is  upper-bounded by L251 , YELLOW_0:def 5;
L253: (( {} ) is_>=_than D46 &  ex_inf_of ( {} ) , ( InclPoset C66 )) by L252 , YELLOW_0:6 , YELLOW_0:43;
L254: D46 <= ( "/\" (( {} ) , ( InclPoset C66 )) ) by L253 , YELLOW_0:def 10;
L255: (( "/\" (( {} ) , ( InclPoset C66 )) ) c= D46 & D46 c= ( "/\" (( {} ) , ( InclPoset C66 )) )) by L254 , L82 , ZFMISC_1:74;
thus L256: ( Top ( InclPoset C66 ) ) = ( "/\" (( {} ) , ( InclPoset C66 )) ) by YELLOW_0:def 12
.= ( union C66 ) by L255 , XBOOLE_0:def 10;
end;
theorem
L257: (for B59 being non  empty set holds (( InclPoset B59 ) is  upper-bounded implies ( union B59 ) in B59))
proof
let C68 being non  empty set;
assume L258: ( InclPoset C68 ) is  upper-bounded;
consider C69 being (Element of ( InclPoset C68 )) such that L259: C69 is_>=_than (the carrier of ( InclPoset C68 )) by L258 , YELLOW_0:def 5;
L260:
now
let C70 being set;
assume L261: C70 in ( union C68 );
consider C71 being set such that L262: C70 in C71 and L263: C71 in C68 by L261 , TARSKI:def 4;
reconsider D47 = C71 as (Element of ( InclPoset C68 )) by L263;
L264: D47 <= C69 by L259 , LATTICE3:def 9;
L265: D47 c= C69 by L264 , L82;
thus L266: C70 in C69 by L265 , L262;
end;
L267: ( union C68 ) c= C69 by L260 , TARSKI:def 3;
L268: (C69 in C68 & C69 c= ( union C68 )) by ZFMISC_1:74;
thus L269: thesis by L268 , L267 , XBOOLE_0:def 10;
end;
theorem
L270: (for B60 being non  empty set holds (( InclPoset B60 ) is  lower-bounded implies ( meet B60 ) in B60))
proof
let C72 being non  empty set;
assume L271: ( InclPoset C72 ) is  lower-bounded;
consider C73 being (Element of ( InclPoset C72 )) such that L272: C73 is_<=_than (the carrier of ( InclPoset C72 )) by L271 , YELLOW_0:def 4;
L273:
now
let C74 being set;
assume L274: C74 in C73;
L275:
now
let C75 being set;
assume L276: C75 in C72;
reconsider D48 = C75 as (Element of ( InclPoset C72 )) by L276;
L277: C73 <= D48 by L272 , LATTICE3:def 8;
L278: C73 c= C75 by L277 , L82;
thus L279: C74 in C75 by L278 , L274;
end;
thus L280: C74 in ( meet C72 ) by L275 , SETFAM_1:def 1;
end;
L281: C73 c= ( meet C72 ) by L273 , TARSKI:def 3;
L282: (C73 in C72 & ( meet C72 ) c= C73) by SETFAM_1:3;
thus L283: thesis by L282 , L281 , XBOOLE_0:def 10;
end;
L284: (for R1 being set holds (for B61 , B62 being (Element of ( BoolePoset R1 )) holds (( B61 /\ B62 ) in ( bool R1 ) & ( B61 \/ B62 ) in ( bool R1 ))))
proof
let R1 being set;
let C76 , C77 being (Element of ( BoolePoset R1 ));
L285: C76 in (the carrier of ( BoolePoset R1 ));
L286: C76 in ( bool R1 ) by L285 , LATTICE3:def 1;
L287: ( C76 /\ C77 ) c= R1 by L286 , XBOOLE_1:108;
thus L288: ( C76 /\ C77 ) in ( bool R1 ) by L287;
L289: C77 in (the carrier of ( BoolePoset R1 ));
L290: C77 in ( bool R1 ) by L289 , LATTICE3:def 1;
L291: ( C76 \/ C77 ) c= R1 by L290 , L286 , XBOOLE_1:8;
thus L292: thesis by L291;
end;
theorem
L293: (for R1 being set holds (for B63 , B64 being (Element of ( BoolePoset R1 )) holds (( B63 "\/" B64 ) = ( B63 \/ B64 ) & ( B63 "/\" B64 ) = ( B63 /\ B64 ))))
proof
let R1 being set;
let C78 , C79 being (Element of ( BoolePoset R1 ));
reconsider D49 = C78 , D50 = C79 as (Element of ( InclPoset ( bool R1 ) )) by L88;
L294: (( D49 "/\" D50 ) = ( D49 /\ D50 ) & ( D49 "\/" D50 ) = ( D49 \/ D50 )) by L284 , L145 , L157;
thus L295: thesis by L294 , L88;
end;
theorem
L296: (for R1 being set holds ( Bottom ( BoolePoset R1 ) ) = ( {} ))
proof
let R1 being set;
thus L297: ( Bottom ( BoolePoset R1 ) ) = ( "\/" (( {} ) , ( LattPOSet ( BooleLatt R1 ) )) ) by YELLOW_0:def 11
.= ( "\/" (( {} ) , ( BooleLatt R1 )) ) by YELLOW_0:29
.= ( Bottom ( BooleLatt R1 ) ) by LATTICE3:49
.= ( {} ) by LATTICE3:3;
end;
theorem
L298: (for R1 being set holds ( Top ( BoolePoset R1 ) ) = R1)
proof
let R1 being set;
L299: ( Top ( InclPoset ( bool R1 ) ) ) = ( union ( bool R1 ) ) by L245;
L300: ( BoolePoset R1 ) = ( InclPoset ( bool R1 ) ) by L88;
thus L301: thesis by L300 , L299 , ZFMISC_1:81;
end;
theorem
L302: (for R1 being set holds (for B65 being non  empty (Subset of ( BoolePoset R1 )) holds ( inf B65 ) = ( meet B65 )))
proof
let R1 being set;
set D51 = ( BoolePoset R1 );
let C80 being non  empty (Subset of D51);
set D52 = the (Element of C80);
L303: (the carrier of D51) = ( bool R1 ) by LATTICE3:def 1;
L304: D52 c= R1 by L303;
reconsider D53 = ( meet C80 ) as (Element of D51) by L304 , L303 , SETFAM_1:7;
L305:
now
let C81 being (Element of D51);
assume L306: C81 is_<=_than C80;
L307:
now
let C82 being set;
assume L308: C82 in C80;
reconsider D54 = C82 as (Element of D51) by L308;
L309: C81 <= D54 by L306 , L308 , LATTICE3:def 8;
thus L310: C81 c= C82 by L309 , L72;
end;
L311: C81 c= D53 by L307 , SETFAM_1:5;
thus L312: D53 >= C81 by L311 , L72;
end;
L313:
now
let C83 being (Element of D51);
assume L314: C83 in C80;
L315: D53 c= C83 by L314 , SETFAM_1:3;
thus L316: D53 <= C83 by L315 , L72;
end;
L317: D53 is_<=_than C80 by L313 , LATTICE3:def 8;
thus L318: thesis by L317 , L305 , YELLOW_0:33;
end;
theorem
L319: (for R1 being set holds (for B66 being (Subset of ( BoolePoset R1 )) holds ( sup B66 ) = ( union B66 )))
proof
let R1 being set;
set D55 = ( BoolePoset R1 );
let C84 being (Subset of D55);
L320: (the carrier of D55) = ( bool R1 ) by LATTICE3:def 1;
L321: ( union C84 ) c= ( union ( bool R1 ) ) by L320 , ZFMISC_1:77;
reconsider D56 = ( union C84 ) as (Element of D55) by L321 , L320 , ZFMISC_1:81;
L322:
now
let C85 being (Element of D55);
assume L323: C85 is_>=_than C84;
L324:
now
let C86 being set;
assume L325: C86 in C84;
reconsider D57 = C86 as (Element of D55) by L325;
L326: D57 <= C85 by L323 , L325 , LATTICE3:def 9;
thus L327: C86 c= C85 by L326 , L72;
end;
L328: D56 c= C85 by L324 , ZFMISC_1:76;
thus L329: D56 <= C85 by L328 , L72;
end;
L330:
now
let C87 being (Element of D55);
assume L331: C87 in C84;
L332: C87 c= D56 by L331 , ZFMISC_1:74;
thus L333: C87 <= D56 by L332 , L72;
end;
L334: D56 is_>=_than C84 by L330 , LATTICE3:def 9;
thus L335: thesis by L334 , L322 , YELLOW_0:30;
end;
theorem
L336: (for B67 being non  empty TopSpace holds (for B68 being (Subset of ( InclPoset (the topology of B67) )) holds ( sup B68 ) = ( union B68 )))
proof
let C88 being non  empty TopSpace;
set D58 = ( InclPoset (the topology of C88) );
let C89 being (Subset of D58);
reconsider D59 = C89 as (Subset-Family of C88) by XBOOLE_1:1;
reconsider D60 = ( union D59 ) as (Element of D58) by PRE_TOPC:def 1;
L337:
now
let C90 being (Element of D58);
assume L338: C90 is_>=_than D59;
L339:
now
let C91 being set;
assume L340: C91 in D59;
reconsider D61 = C91 as (Element of D58) by L340;
L341: D61 <= C90 by L338 , L340 , LATTICE3:def 9;
thus L342: C91 c= C90 by L341 , L82;
end;
L343: D60 c= C90 by L339 , ZFMISC_1:76;
thus L344: D60 <= C90 by L343 , L82;
end;
L345:
now
let C92 being (Element of D58);
assume L346: C92 in D59;
L347: C92 c= D60 by L346 , ZFMISC_1:74;
thus L348: C92 <= D60 by L347 , L82;
end;
L349: D60 is_>=_than D59 by L345 , LATTICE3:def 9;
thus L350: thesis by L349 , L337 , YELLOW_0:30;
end;
theorem
L351: (for B69 being non  empty TopSpace holds ( Bottom ( InclPoset (the topology of B69) ) ) = ( {} )) by L233 , PRE_TOPC:1;
L352: (for B70 being non  empty TopSpace holds ( InclPoset (the topology of B70) ) is  lower-bounded)
proof
let C93 being non  empty TopSpace;
set D62 = ( InclPoset (the topology of C93) );
reconsider D63 = ( {} ) as (Element of D62) by PRE_TOPC:1;
L353:
now
take D64 = D63;
thus L354: D64 is_<=_than (the carrier of D62)
proof
let C94 being (Element of D62);
assume L355: C94 in (the carrier of D62);
L356: D64 c= C94 by XBOOLE_1:2;
thus L357: thesis by L356 , L82;
end;

end;
thus L355: thesis by L353 , YELLOW_0:def 4;
end;
theorem
L356: (for B71 being non  empty TopSpace holds ( Top ( InclPoset (the topology of B71) ) ) = (the carrier of B71))
proof
let C95 being non  empty TopSpace;
set D65 = ( InclPoset (the topology of C95) );
set D66 = (the carrier of C95);
L357: (the carrier of C95) = ( "/\" (( {} ) , D65) )
proof
reconsider D67 = D66 as (Element of D65) by PRE_TOPC:def 1;
L358: (for B72 being (Element of D65) holds (B72 is_<=_than ( {} ) implies D67 >= B72))
proof
let C96 being (Element of D65);
assume L359: C96 is_<=_than ( {} );
L360: C96 in (the topology of C95);
thus L361: thesis by L360 , L82;
end;
L362: D67 is_<=_than ( {} ) by YELLOW_0:6;
thus L363: thesis by L362 , L358 , YELLOW_0:31;
end;
thus L364: thesis by L357 , YELLOW_0:def 12;
end;
L365: (for B73 being non  empty TopSpace holds ( InclPoset (the topology of B73) ) is  complete)
proof
let C97 being non  empty TopSpace;
set D68 = (the topology of C97);
reconsider D69 = ( InclPoset D68 ) as  lower-bounded Poset by L352;
L366: (for B74 being (Subset of D69) holds  ex_sup_of B74 , ( InclPoset D68 ))
proof
let C98 being (Subset of D69);
set D70 = ( union C98 );
reconsider D71 = C98 as (Subset-Family of C97) by XBOOLE_1:1;
L367: D71 c= (the topology of C97);
reconsider D72 = D70 as (Element of ( InclPoset D68 )) by L367 , PRE_TOPC:def 1;
L368: (for B75 being (Element of ( InclPoset D68 )) holds (C98 is_<=_than B75 implies D72 <= B75))
proof
let C99 being (Element of ( InclPoset D68 ));
assume L369: C98 is_<=_than C99;
L370:
now
let C100 being set;
assume L371: C100 in C98;
reconsider D73 = C100 as (Element of ( InclPoset D68 )) by L371;
L372: D73 <= C99 by L369 , L371 , LATTICE3:def 9;
thus L373: C100 c= C99 by L372 , L82;
end;
L374: ( union C98 ) c= C99 by L370 , ZFMISC_1:76;
thus L375: thesis by L374 , L82;
end;
L376: C98 is_<=_than D72
proof
let C101 being (Element of ( InclPoset D68 ));
assume L377: C101 in C98;
L378: C101 c= D72 by L377 , ZFMISC_1:74;
thus L379: thesis by L378 , L82;
end;
thus L380: thesis by L376 , L368 , YELLOW_0:15;
end;
thus L381: thesis by L366 , YELLOW_0:53;
end;
L382: (for B76 being non  empty TopSpace holds ( InclPoset (the topology of B76) ) is non  trivial)
proof
let C102 being non  empty TopSpace;
set D74 = ( InclPoset (the topology of C102) );
reconsider D75 = ( {} ) , D76 = (the carrier of C102) as (Element of D74) by PRE_TOPC:1 , PRE_TOPC:def 1;
L383: D75 <> D76;
thus L384: thesis by L383 , STRUCT_0:def 10;
end;
registration
let C103 being non  empty TopSpace;
cluster ( InclPoset (the topology of C103) ) ->  complete non  trivial;
coherence by L365 , L382;
end;
theorem
L386: (for B77 being TopSpace holds (for B78 being (Subset-Family of B77) holds (B78 is  open iff B78 is (Subset of ( InclPoset (the topology of B77) )))))
proof
let C104 being TopSpace;
let C105 being (Subset-Family of C104);
thus L387:now
assume L388: C105 is  open;
L389: C105 c= (the topology of C104)
proof
let C106 being set;
assume L390: C106 in C105;
reconsider D77 = C106 as (Subset of C104) by L390;
L391: D77 is  open by L388 , L390 , TOPS_2:def 1;
thus L392: thesis by L391 , PRE_TOPC:def 2;
end;
thus L393: C105 is (Subset of ( InclPoset (the topology of C104) )) by L389;
end;
assume L394: C105 is (Subset of ( InclPoset (the topology of C104) ));
let C107 being (Subset of C104);
assume L395: C107 in C105;
thus L396: thesis by L395 , L394 , PRE_TOPC:def 2;
end;
begin
definition
let C108 being Relation;
attr C108 is  RelStr-yielding
means
:L397: (for B79 being set holds (B79 in ( rng C108 ) implies B79 is RelStr));
end;
registration
cluster  RelStr-yielding ->  1-sorted-yielding for Function;
coherence
proof
let C109 being Function;
assume that
L399: C109 is  RelStr-yielding;
let C110 being set;
assume L400: C110 in ( dom C109 );
L401: ( C109 . C110 ) in ( rng C109 ) by L400 , FUNCT_1:def 3;
thus L402: thesis by L401 , L399 , L397;
end;
end;
registration
let C111 being set;
cluster  RelStr-yielding for (ManySortedSet of C111);
existence
proof
set D78 = the RelStr;
take ( C111 --> D78 );
let C112 being set;
assume L404: C112 in ( rng ( C111 --> D78 ) );
L405: ( rng ( C111 --> D78 ) ) c= { D78 } by FUNCOP_1:13;
thus L406: thesis by L405 , L404 , TARSKI:def 1;
end;
end;
definition
let C113 being non  empty set;
let C114 being  RelStr-yielding (ManySortedSet of C113);
let C115 being (Element of C113);
redefine func C114 . C115 -> RelStr;

coherence
proof
L408: ( dom C114 ) = C113 by PARTFUN1:def 2;
L409: ( C114 . C115 ) in ( rng C114 ) by L408 , FUNCT_1:def 3;
thus L410: thesis by L409 , L397;
end;
end;
definition
let C116 being set;
let C117 being  RelStr-yielding (ManySortedSet of C116);
func product C117 ->  strict RelStr means 
:L412: ((the carrier of it) = ( product ( Carrier C117 ) ) & (for B80 , B81 being (Element of it) holds (B80 in ( product ( Carrier C117 ) ) implies (B80 <= B81 iff (ex B82 , B83 being Function st (B82 = B80 & B83 = B81 & (for B84 being set holds (B84 in C116 implies (ex B85 being RelStr st (ex B86 , B87 being (Element of B85) st (B85 = ( C117 . B84 ) & B86 = ( B82 . B84 ) & B87 = ( B83 . B84 ) & B86 <= B87)))))))))));
existence
proof
defpred S1[ set , set ] means (ex B88 , B89 being Function st (B88 = $1 & B89 = $2 & (for B90 being set holds (B90 in C116 implies (ex B91 being RelStr st (ex B92 , B93 being (Element of B91) st (B91 = ( C117 . B90 ) & B92 = ( B88 . B90 ) & B93 = ( B89 . B90 ) & B92 <= B93)))))));
consider C118 being (Relation of ( product ( Carrier C117 ) )) such that L413: (for B94 , B95 being set holds ([ B94 , B95 ] in C118 iff (B94 in ( product ( Carrier C117 ) ) & B95 in ( product ( Carrier C117 ) ) & S1[ B94 , B95 ]))) from RELSET_1:sch 1;
take D79 = RelStr (# ( product ( Carrier C117 ) ) , C118 #);
thus L414: (the carrier of D79) = ( product ( Carrier C117 ) );
let C119 , C120 being (Element of D79);
assume that
L415: C119 in ( product ( Carrier C117 ) );
thus L416:now
assume L417: C119 <= C120;
L418: [ C119 , C120 ] in (the InternalRel of D79) by L417 , ORDERS_2:def 5;
thus L419: (ex B96 , B97 being Function st (B96 = C119 & B97 = C120 & (for B98 being set holds (B98 in C116 implies (ex B99 being RelStr st (ex B100 , B101 being (Element of B99) st (B99 = ( C117 . B98 ) & B100 = ( B96 . B98 ) & B101 = ( B97 . B98 ) & B100 <= B101))))))) by L418 , L413;
end;
assume L420: (ex B102 , B103 being Function st (B102 = C119 & B103 = C120 & (for B104 being set holds (B104 in C116 implies (ex B105 being RelStr st (ex B106 , B107 being (Element of B105) st (B105 = ( C117 . B104 ) & B106 = ( B102 . B104 ) & B107 = ( B103 . B104 ) & B106 <= B107)))))));
L421: [ C119 , C120 ] in (the InternalRel of D79) by L420 , L413 , L415;
thus L422: thesis by L421 , ORDERS_2:def 5;
end;
uniqueness
proof
let C121 , C122 being  strict RelStr;
assume that
L423: (the carrier of C121) = ( product ( Carrier C117 ) )
and
L424: (for B108 , B109 being (Element of C121) holds (B108 in ( product ( Carrier C117 ) ) implies (B108 <= B109 iff (ex B110 , B111 being Function st (B110 = B108 & B111 = B109 & (for B112 being set holds (B112 in C116 implies (ex B113 being RelStr st (ex B114 , B115 being (Element of B113) st (B113 = ( C117 . B112 ) & B114 = ( B110 . B112 ) & B115 = ( B111 . B112 ) & B114 <= B115))))))))))
and
L425: (the carrier of C122) = ( product ( Carrier C117 ) )
and
L426: (for B116 , B117 being (Element of C122) holds (B116 in ( product ( Carrier C117 ) ) implies (B116 <= B117 iff (ex B118 , B119 being Function st (B118 = B116 & B119 = B117 & (for B120 being set holds (B120 in C116 implies (ex B121 being RelStr st (ex B122 , B123 being (Element of B121) st (B121 = ( C117 . B120 ) & B122 = ( B118 . B120 ) & B123 = ( B119 . B120 ) & B122 <= B123))))))))));
L427: (the InternalRel of C121) = (the InternalRel of C122)
proof
let C123 , C124 being set;
thus L428:now
assume L429: [ C123 , C124 ] in (the InternalRel of C121);
reconsider D80 = C123 , D81 = C124 as (Element of C121) by L429 , ZFMISC_1:87;
reconsider D82 = D80 , D83 = D81 as (Element of C122) by L423 , L425;
L430: C123 in (the carrier of C121) by L429 , ZFMISC_1:87;
L431: D80 <= D81 by L429 , ORDERS_2:def 5;
L432: (ex B124 , B125 being Function st (B124 = D80 & B125 = D81 & (for B126 being set holds (B126 in C116 implies (ex B127 being RelStr st (ex B128 , B129 being (Element of B127) st (B127 = ( C117 . B126 ) & B128 = ( B124 . B126 ) & B129 = ( B125 . B126 ) & B128 <= B129))))))) by L431 , L423 , L424 , L430;
L433: D82 <= D83 by L432 , L423 , L426 , L430;
thus L434: [ C123 , C124 ] in (the InternalRel of C122) by L433 , ORDERS_2:def 5;
end;
assume L435: [ C123 , C124 ] in (the InternalRel of C122);
reconsider D84 = C123 , D85 = C124 as (Element of C122) by L435 , ZFMISC_1:87;
reconsider D86 = D84 , D87 = D85 as (Element of C121) by L423 , L425;
L436: C123 in (the carrier of C122) by L435 , ZFMISC_1:87;
L437: D84 <= D85 by L435 , ORDERS_2:def 5;
L438: (ex B130 , B131 being Function st (B130 = D84 & B131 = D85 & (for B132 being set holds (B132 in C116 implies (ex B133 being RelStr st (ex B134 , B135 being (Element of B133) st (B133 = ( C117 . B132 ) & B134 = ( B130 . B132 ) & B135 = ( B131 . B132 ) & B134 <= B135))))))) by L437 , L425 , L426 , L436;
L439: D86 <= D87 by L438 , L424 , L425 , L436;
thus L440: thesis by L439 , ORDERS_2:def 5;
end;
thus L441: thesis by L427 , L423 , L425;
end;
end;
registration
let C125 being set;
let C126 being RelStr;
cluster ( C125 --> C126 ) ->  RelStr-yielding;
coherence
proof
let C127 being set;
assume L443: C127 in ( rng ( C125 --> C126 ) );
L444: ( rng ( C125 --> C126 ) ) c= { C126 } by FUNCOP_1:13;
thus L445: thesis by L444 , L443 , TARSKI:def 1;
end;
end;
definition
let C128 being set;
let C129 being RelStr;
func C129 |^ C128 ->  strict RelStr equals 
( product ( C128 --> C129 ) );
correctness;
end;
theorem
L448: (for B136 being  RelStr-yielding (ManySortedSet of ( {} )) holds ( product B136 ) = RelStr (# { ( {} ) } , ( id { ( {} ) } ) #))
proof
let C130 being  RelStr-yielding (ManySortedSet of ( {} ));
set D88 = ( product C130 );
L449: (the carrier of D88) = ( product ( Carrier C130 ) ) by L412
.= { ( {} ) } by CARD_3:10 , PBOOLE:122;
L450: ( product ( Carrier C130 ) ) = { ( {} ) } by CARD_3:10 , PBOOLE:122;
L451: (the InternalRel of ( product C130 )) = ( id { ( {} ) } )
proof
reconsider D89 = ( {} ) , D90 = ( {} ) as (Element of D88) by L449 , TARSKI:def 1;
let C131 , C132 being set;
L452: D89 = ( ( {} ) --> { ( {} ) } );
reconsider D91 = D89 , D92 = D90 as Function by L452;
thus L453:now
assume L454: [ C131 , C132 ] in (the InternalRel of D88);
L455: C132 in (the carrier of D88) by L454 , ZFMISC_1:87;
L456: C131 in (the carrier of D88) by L454 , ZFMISC_1:87;
L457: C131 = ( {} ) by L456 , L449 , TARSKI:def 1;
L458: C131 = C132 by L457 , L449 , L455 , TARSKI:def 1;
thus L459: [ C131 , C132 ] in ( id { ( {} ) } ) by L458 , L449 , L456 , RELAT_1:def 10;
end;
assume L460: [ C131 , C132 ] in ( id { ( {} ) } );
L461: C131 in { ( {} ) } by L460 , RELAT_1:def 10;
L462: C131 = ( {} ) by L461 , TARSKI:def 1;
L463: (for B137 being set holds (B137 in ( {} ) implies (ex B138 being RelStr st (ex B139 , B140 being (Element of B138) st (B138 = ( C130 . B137 ) & B139 = ( D91 . B137 ) & B140 = ( D92 . B137 ) & B139 <= B140)))));
L464: D89 <= D90 by L463 , L449 , L450 , L412;
L465: C131 = C132 by L460 , RELAT_1:def 10;
thus L466: thesis by L465 , L462 , L464 , ORDERS_2:def 5;
end;
thus L467: thesis by L451 , L449;
end;
theorem
L468: (for B141 being RelStr holds ( B141 |^ ( {} ) ) = RelStr (# { ( {} ) } , ( id { ( {} ) } ) #)) by L448;
theorem
L469: (for B142 being set holds (for B143 being RelStr holds ( Funcs (B142 , (the carrier of B143)) ) = (the carrier of ( B143 |^ B142 ))))
proof
let C133 being set;
let C134 being RelStr;
set D93 = (the carrier of C134);
set D94 = ( Carrier ( C133 --> C134 ) );
L470: ( dom D94 ) = C133 by PARTFUN1:def 2;
L471: (for B144 being set holds (B144 in C133 implies ( D94 . B144 ) = D93))
proof
let C135 being set;
assume L472: C135 in C133;
L473: (ex B145 being 1-sorted st (B145 = ( ( C133 --> C134 ) . C135 ) & ( D94 . C135 ) = (the carrier of B145))) by L472 , PRALG_1:def 13;
thus L474: thesis by L473 , L472 , FUNCOP_1:7;
end;
L475: ( Funcs (C133 , D93) ) = ( product D94 )
proof
thus L476: ( Funcs (C133 , D93) ) c= ( product D94 )
proof
let C136 being set;
assume L477: C136 in ( Funcs (C133 , D93) );
consider C137 being Function such that L478: C136 = C137 and L479: ( dom C137 ) = C133 and L480: ( rng C137 ) c= D93 by L477 , FUNCT_2:def 2;
L481:
now
let C138 being set;
assume L482: C138 in ( dom D94 );
L483: (( D94 . C138 ) = D93 & ( C137 . C138 ) in ( rng C137 )) by L482 , L471 , L479 , FUNCT_1:def 3;
thus L484: ( C137 . C138 ) in ( D94 . C138 ) by L483 , L480;
end;
thus L485: thesis by L481 , L470 , L478 , L479 , CARD_3:def 5;
end;

let R2 being set;
assume L486: R2 in ( product D94 );
consider C139 being Function such that L487: R2 = C139 and L488: ( dom C139 ) = ( dom D94 ) and L489: (for R2 being set holds (R2 in ( dom D94 ) implies ( C139 . R2 ) in ( D94 . R2 ))) by L486 , CARD_3:def 5;
L490: ( rng C139 ) c= D93
proof
let R3 being set;
assume L491: R3 in ( rng C139 );
consider R4 being set such that L492: R4 in ( dom C139 ) and L493: R3 = ( C139 . R4 ) by L491 , FUNCT_1:def 3;
L494: ( D94 . R4 ) = D93 by L471 , L488 , L492;
thus L495: thesis by L494 , L488 , L489 , L492 , L493;
end;
thus L496: thesis by L490 , L470 , L487 , L488 , FUNCT_2:def 2;
end;
thus L497: thesis by L475 , L412;
end;
registration
let C140 being set;
let C141 being non  empty RelStr;
cluster ( C141 |^ C140 ) -> non  empty;
coherence
proof
set D95 = the (Function of C140 , (the carrier of C141));
L498: D95 in ( Funcs (C140 , (the carrier of C141)) ) by FUNCT_2:8;
thus L499: thesis by L498 , L469;
end;
end;
L501: (for B146 being set holds (for B147 being non  empty RelStr holds (for B148 being (Element of ( B147 |^ B146 )) holds (B148 in (the carrier of ( product ( B146 --> B147 ) )) & B148 is (Function of B146 , (the carrier of B147))))))
proof
let C142 being set;
let C143 being non  empty RelStr;
let C144 being (Element of ( C143 |^ C142 ));
L502: C144 in (the carrier of ( C143 |^ C142 ));
L503: C144 in ( Funcs (C142 , (the carrier of C143)) ) by L502 , L469;
thus L504: thesis by L503 , FUNCT_2:66;
end;
registration
let C145 being set;
let C146 being  reflexive non  empty RelStr;
cluster ( C146 |^ C145 ) ->  reflexive;
coherence
proof
per cases ;
suppose L505: C145 is  empty;

thus L506: thesis by L505 , L448;
end;
suppose L507: C145 is non  empty;

reconsider D96 = C145 as non  empty set by L507;
L508: (for B149 being (Element of ( C146 |^ D96 )) holds B149 <= B149)
proof
let C147 being (Element of ( C146 |^ D96 ));
reconsider D97 = C147 as (Function of D96 , (the carrier of C146)) by L501;
reconsider D98 = C147 as (Element of ( product ( D96 --> C146 ) ));
L509: (ex B150 , B151 being Function st (B150 = D98 & B151 = D98 & (for B152 being set holds (B152 in D96 implies (ex B153 being RelStr st (ex B154 , B155 being (Element of B153) st (B153 = ( ( D96 --> C146 ) . B152 ) & B154 = ( B150 . B152 ) & B155 = ( B151 . B152 ) & B154 <= B155)))))))
proof
take D97;
take D97;
thus L510: (D97 = D98 & D97 = D98);
let C148 being set;
assume L511: C148 in D96;
reconsider D99 = C148 as (Element of D96) by L511;
take D100 = ( ( D96 --> C146 ) . D99 );
reconsider D101 = ( D97 . D99 ) , D102 = ( D97 . D99 ) as (Element of D100) by FUNCOP_1:7;
take D101;
take D102;
reconsider D103 = D101 , D104 = D101 as (Element of C146);
L512: D103 <= D104;
thus L513: thesis by L512 , FUNCOP_1:7;
end;
L514: C147 in (the carrier of ( product ( D96 --> C146 ) ));
L515: D98 in ( product ( Carrier ( D96 --> C146 ) ) ) by L514 , L412;
thus L516: thesis by L515 , L509 , L412;
end;
thus L517: thesis by L508 , YELLOW_0:def 1;
end;
end;
end;
registration
let C149 being non  empty RelStr;
cluster ( C149 |^ ( {} ) ) -> 1 -element;
coherence by L448;
end;
registration
let C150 being non  empty  reflexive RelStr;
cluster ( C150 |^ ( {} ) ) ->  with_infima  with_suprema  antisymmetric;
coherence;
end;
registration
let C151 being set;
let C152 being  transitive non  empty RelStr;
cluster ( C152 |^ C151 ) ->  transitive;
coherence
proof
set D105 = ( C152 |^ C151 );
L522:
now
let C153 , C154 , C155 being (Element of D105);
reconsider D106 = C153 , D107 = C154 , D108 = C155 as (Element of ( product ( C151 --> C152 ) ));
assume that
L523: C153 <= C154
and
L524: C154 <= C155;
L525: D107 in (the carrier of ( product ( C151 --> C152 ) ));
L526: D107 in ( product ( Carrier ( C151 --> C152 ) ) ) by L525 , L412;
consider C156 , C157 being Function such that L527: (C156 = D107 & C157 = D108) and L528: (for B156 being set holds (B156 in C151 implies (ex B157 being RelStr st (ex B158 , B159 being (Element of B157) st (B157 = ( ( C151 --> C152 ) . B156 ) & B158 = ( C156 . B156 ) & B159 = ( C157 . B156 ) & B158 <= B159))))) by L526 , L524 , L412;
L529: D106 in (the carrier of ( product ( C151 --> C152 ) ));
L530: D106 in ( product ( Carrier ( C151 --> C152 ) ) ) by L529 , L412;
consider C158 , C159 being Function such that L531: (C158 = D106 & C159 = D107) and L532: (for B160 being set holds (B160 in C151 implies (ex B161 being RelStr st (ex B162 , B163 being (Element of B161) st (B161 = ( ( C151 --> C152 ) . B160 ) & B162 = ( C158 . B160 ) & B163 = ( C159 . B160 ) & B162 <= B163))))) by L530 , L523 , L412;
L533: (ex B164 , B165 being Function st (B164 = D106 & B165 = D108 & (for B166 being set holds (B166 in C151 implies (ex B167 being RelStr st (ex B168 , B169 being (Element of B167) st (B167 = ( ( C151 --> C152 ) . B166 ) & B168 = ( B164 . B166 ) & B169 = ( B165 . B166 ) & B168 <= B169)))))))
proof
reconsider D109 = C153 , D110 = C155 as (Function of C151 , (the carrier of C152)) by L501;
take D109;
take D110;
thus L534: (D109 = D106 & D110 = D108);
let C160 being set;
assume L535: C160 in C151;
reconsider D111 = C151 as non  empty set by L535;
reconsider D112 = C160 as (Element of D111) by L535;
reconsider D113 = ( ( D111 --> C152 ) . D112 ) as RelStr;
L536: D113 = C152 by FUNCOP_1:7;
reconsider D114 = ( D109 . D112 ) , D115 = ( D110 . D112 ) as (Element of D113) by L536 , FUNCT_2:5;
take D113;
take D114;
take D115;
L537: ((ex B170 being RelStr st (ex B171 , B172 being (Element of B170) st (B170 = ( ( D111 --> C152 ) . D112 ) & B171 = ( C158 . D112 ) & B172 = ( C159 . D112 ) & B171 <= B172))) & (ex B173 being RelStr st (ex B174 , B175 being (Element of B173) st (B173 = ( ( D111 --> C152 ) . D112 ) & B174 = ( C156 . D112 ) & B175 = ( C157 . D112 ) & B174 <= B175)))) by L532 , L528;
thus L538: thesis by L537 , L531 , L527 , L536 , YELLOW_0:def 2;
end;
thus L539: C153 <= C155 by L533 , L530 , L412;
end;
thus L540: thesis by L522 , YELLOW_0:def 2;
end;
end;
registration
let C161 being set;
let C162 being  antisymmetric non  empty RelStr;
cluster ( C162 |^ C161 ) ->  antisymmetric;
coherence
proof
set D116 = ( C162 |^ C161 );
L542:
now
let C163 , C164 being (Element of D116);
reconsider D117 = C163 , D118 = C164 as (Function of C161 , (the carrier of C162)) by L501;
reconsider D119 = C163 , D120 = C164 as (Element of ( product ( C161 --> C162 ) ));
assume that
L543: C163 <= C164
and
L544: C164 <= C163;
L545: D120 in (the carrier of ( product ( C161 --> C162 ) ));
L546: D120 in ( product ( Carrier ( C161 --> C162 ) ) ) by L545 , L412;
consider C165 , C166 being Function such that L547: (C165 = D120 & C166 = D119) and L548: (for B176 being set holds (B176 in C161 implies (ex B177 being RelStr st (ex B178 , B179 being (Element of B177) st (B177 = ( ( C161 --> C162 ) . B176 ) & B178 = ( C165 . B176 ) & B179 = ( C166 . B176 ) & B178 <= B179))))) by L546 , L544 , L412;
L549: D119 in (the carrier of ( product ( C161 --> C162 ) ));
L550: D119 in ( product ( Carrier ( C161 --> C162 ) ) ) by L549 , L412;
consider C167 , C168 being Function such that L551: (C167 = D119 & C168 = D120) and L552: (for B180 being set holds (B180 in C161 implies (ex B181 being RelStr st (ex B182 , B183 being (Element of B181) st (B181 = ( ( C161 --> C162 ) . B180 ) & B182 = ( C167 . B180 ) & B183 = ( C168 . B180 ) & B182 <= B183))))) by L550 , L543 , L412;
L553:
now
let C169 being set;
assume L554: C169 in C161;
consider C170 being RelStr, C171 , C172 being (Element of C170) such that L555: C170 = ( ( C161 --> C162 ) . C169 ) and L556: (C171 = ( C165 . C169 ) & C172 = ( C166 . C169 ) & C171 <= C172) by L554 , L548;
L557: C162 = C170 by L554 , L555 , FUNCOP_1:7;
consider C173 being RelStr, C174 , C175 being (Element of C173) such that L558: C173 = ( ( C161 --> C162 ) . C169 ) and L559: (C174 = ( C167 . C169 ) & C175 = ( C168 . C169 ) & C174 <= C175) by L552 , L554;
L560: C162 = C173 by L554 , L558 , FUNCOP_1:7;
thus L561: ( D117 . C169 ) = ( D118 . C169 ) by L560 , L551 , L547 , L559 , L556 , L557 , ORDERS_2:2;
end;
L562: (( dom D117 ) = C161 & ( dom D118 ) = C161) by FUNCT_2:def 1;
thus L563: C163 = C164 by L562 , L553 , FUNCT_1:2;
end;
thus L564: thesis by L542 , YELLOW_0:def 3;
end;
end;
registration
let C176 being non  empty set;
let C177 being non  empty  with_infima  antisymmetric RelStr;
cluster ( C177 |^ C176 ) ->  with_infima;
coherence
proof
set D121 = ( C177 |^ C176 );
let C178 , C179 being (Element of D121);
reconsider D122 = C179 as (Function of C176 , (the carrier of C177)) by L501;
reconsider D123 = C178 as (Function of C176 , (the carrier of C177)) by L501;
defpred S2[ set , set ] means (ex B184 , B185 being (Element of C177) st (B184 = ( D123 . $1 ) & B185 = ( D122 . $1 ) & $2 = ( B184 "/\" B185 )));
L566: (for B186 being set holds (B186 in C176 implies (ex B187 being set st (B187 in (the carrier of C177) & S2[ B186 , B187 ]))))
proof
let C180 being set;
assume L567: C180 in C176;
reconsider D124 = ( D123 . C180 ) , D125 = ( D122 . C180 ) as (Element of C177) by L567 , FUNCT_2:5;
take D126 = ( D124 "/\" D125 );
thus L568: D126 in (the carrier of C177);
take D124;
take D125;
thus L569: thesis;
end;
consider C181 being (Function of C176 , (the carrier of C177)) such that L570: (for B188 being set holds (B188 in C176 implies S2[ B188 , ( C181 . B188 ) ])) from FUNCT_2:sch 1(L566);
L571: C181 in ( Funcs (C176 , (the carrier of C177)) ) by FUNCT_2:8;
reconsider D127 = C181 as (Element of D121) by L571 , L469;
take D127;
L572: D127 <= C179
proof
reconsider D128 = C179 , D129 = D127 as (Element of ( product ( C176 --> C177 ) ));
L573: (ex B189 , B190 being Function st (B189 = D129 & B190 = D128 & (for B191 being set holds (B191 in C176 implies (ex B192 being RelStr st (ex B193 , B194 being (Element of B192) st (B192 = ( ( C176 --> C177 ) . B191 ) & B193 = ( B189 . B191 ) & B194 = ( B190 . B191 ) & B193 <= B194)))))))
proof
take C181;
take D122;
thus L574: (C181 = D129 & D122 = D128);
let C182 being set;
assume L575: C182 in C176;
reconsider D130 = C182 as (Element of C176) by L575;
reconsider D131 = ( ( C176 --> C177 ) . D130 ) as RelStr;
reconsider D132 = ( C181 . D130 ) , D133 = ( D122 . D130 ) as (Element of D131) by FUNCOP_1:7;
take D131;
take D132;
take D133;
L576: (D131 = C177 & (ex B195 , B196 being (Element of C177) st (B195 = ( D123 . D130 ) & B196 = ( D122 . D130 ) & ( C181 . D130 ) = ( B195 "/\" B196 )))) by L570 , FUNCOP_1:7;
thus L577: thesis by L576 , YELLOW_0:23;
end;
L578: D129 in (the carrier of ( product ( C176 --> C177 ) ));
L579: D129 in ( product ( Carrier ( C176 --> C177 ) ) ) by L578 , L412;
thus L580: thesis by L579 , L573 , L412;
end;
L581: (for B197 being (Element of D121) holds ((B197 <= C178 & B197 <= C179) implies B197 <= D127))
proof
let C183 being (Element of D121);
assume that
L582: C183 <= C178
and
L583: C183 <= C179;
L584: C183 <= D127
proof
reconsider D134 = C183 , D135 = D127 , D136 = C179 , D137 = C178 as (Element of ( product ( C176 --> C177 ) ));
reconsider D138 = D134 , D139 = D135 as (Function of C176 , (the carrier of C177)) by L501;
L585: C183 in (the carrier of ( product ( C176 --> C177 ) ));
L586: D134 in ( product ( Carrier ( C176 --> C177 ) ) ) by L585 , L412;
consider C184 , C185 being Function such that L587: (C184 = D134 & C185 = D137) and L588: (for B198 being set holds (B198 in C176 implies (ex B199 being RelStr st (ex B200 , B201 being (Element of B199) st (B199 = ( ( C176 --> C177 ) . B198 ) & B200 = ( C184 . B198 ) & B201 = ( C185 . B198 ) & B200 <= B201))))) by L586 , L582 , L412;
consider C186 , C187 being Function such that L589: (C186 = D134 & C187 = D136) and L590: (for B202 being set holds (B202 in C176 implies (ex B203 being RelStr st (ex B204 , B205 being (Element of B203) st (B203 = ( ( C176 --> C177 ) . B202 ) & B204 = ( C186 . B202 ) & B205 = ( C187 . B202 ) & B204 <= B205))))) by L583 , L586 , L412;
L591: (ex B206 , B207 being Function st (B206 = D134 & B207 = D135 & (for B208 being set holds (B208 in C176 implies (ex B209 being RelStr st (ex B210 , B211 being (Element of B209) st (B209 = ( ( C176 --> C177 ) . B208 ) & B210 = ( B206 . B208 ) & B211 = ( B207 . B208 ) & B210 <= B211)))))))
proof
take D138;
take D139;
thus L592: (D138 = D134 & D139 = D135);
let C188 being set;
assume L593: C188 in C176;
reconsider D140 = C188 as (Element of C176) by L593;
reconsider D141 = ( ( C176 --> C177 ) . D140 ) as RelStr;
reconsider D142 = ( D138 . D140 ) , D143 = ( D139 . D140 ) as (Element of D141) by FUNCOP_1:7;
take D141;
take D142;
take D143;
L594: (D141 = C177 & (ex B212 , B213 being (Element of C177) st (B212 = ( D123 . D140 ) & B213 = ( D122 . D140 ) & ( C181 . D140 ) = ( B212 "/\" B213 )))) by L570 , FUNCOP_1:7;
L595: ((ex B214 being RelStr st (ex B215 , B216 being (Element of B214) st (B214 = ( ( C176 --> C177 ) . D140 ) & B215 = ( C184 . D140 ) & B216 = ( C185 . D140 ) & B215 <= B216))) & (ex B217 being RelStr st (ex B218 , B219 being (Element of B217) st (B217 = ( ( C176 --> C177 ) . D140 ) & B218 = ( C186 . D140 ) & B219 = ( C187 . D140 ) & B218 <= B219)))) by L588 , L590;
thus L596: thesis by L595 , L587 , L589 , L594 , YELLOW_0:23;
end;
thus L597: thesis by L591 , L586 , L412;
end;
thus L598: thesis by L584;
end;
L599: D127 <= C178
proof
reconsider D144 = C178 , D145 = D127 as (Element of ( product ( C176 --> C177 ) ));
L600: (ex B220 , B221 being Function st (B220 = D145 & B221 = D144 & (for B222 being set holds (B222 in C176 implies (ex B223 being RelStr st (ex B224 , B225 being (Element of B223) st (B223 = ( ( C176 --> C177 ) . B222 ) & B224 = ( B220 . B222 ) & B225 = ( B221 . B222 ) & B224 <= B225)))))))
proof
take C181;
take D123;
thus L601: (C181 = D145 & D123 = D144);
let C189 being set;
assume L602: C189 in C176;
reconsider D146 = C189 as (Element of C176) by L602;
reconsider D147 = ( ( C176 --> C177 ) . D146 ) as RelStr;
reconsider D148 = ( C181 . D146 ) , D149 = ( D123 . D146 ) as (Element of D147) by FUNCOP_1:7;
take D147;
take D148;
take D149;
L603: (D147 = C177 & (ex B226 , B227 being (Element of C177) st (B226 = ( D123 . D146 ) & B227 = ( D122 . D146 ) & ( C181 . D146 ) = ( B226 "/\" B227 )))) by L570 , FUNCOP_1:7;
thus L604: thesis by L603 , YELLOW_0:23;
end;
L605: D145 in (the carrier of ( product ( C176 --> C177 ) ));
L606: D145 in ( product ( Carrier ( C176 --> C177 ) ) ) by L605 , L412;
thus L607: thesis by L606 , L600 , L412;
end;
thus L608: thesis by L599 , L572 , L581;
end;
end;
registration
let C190 being non  empty set;
let C191 being non  empty  with_suprema  antisymmetric RelStr;
cluster ( C191 |^ C190 ) ->  with_suprema;
coherence
proof
set D150 = ( C191 |^ C190 );
let C192 , C193 being (Element of D150);
reconsider D151 = C193 as (Function of C190 , (the carrier of C191)) by L501;
reconsider D152 = C192 as (Function of C190 , (the carrier of C191)) by L501;
defpred S3[ set , set ] means (ex B228 , B229 being (Element of C191) st (B228 = ( D152 . $1 ) & B229 = ( D151 . $1 ) & $2 = ( B228 "\/" B229 )));
L610: (for B230 being set holds (B230 in C190 implies (ex B231 being set st (B231 in (the carrier of C191) & S3[ B230 , B231 ]))))
proof
let C194 being set;
assume L611: C194 in C190;
reconsider D153 = ( D152 . C194 ) , D154 = ( D151 . C194 ) as (Element of C191) by L611 , FUNCT_2:5;
take D155 = ( D153 "\/" D154 );
thus L612: D155 in (the carrier of C191);
take D153;
take D154;
thus L613: thesis;
end;
consider C195 being (Function of C190 , (the carrier of C191)) such that L614: (for B232 being set holds (B232 in C190 implies S3[ B232 , ( C195 . B232 ) ])) from FUNCT_2:sch 1(L610);
L615: C195 in ( Funcs (C190 , (the carrier of C191)) ) by FUNCT_2:8;
reconsider D156 = C195 as (Element of D150) by L615 , L469;
take D156;
L616: C193 <= D156
proof
reconsider D157 = C193 , D158 = D156 as (Element of ( product ( C190 --> C191 ) ));
L617: (ex B233 , B234 being Function st (B233 = D157 & B234 = D158 & (for B235 being set holds (B235 in C190 implies (ex B236 being RelStr st (ex B237 , B238 being (Element of B236) st (B236 = ( ( C190 --> C191 ) . B235 ) & B237 = ( B233 . B235 ) & B238 = ( B234 . B235 ) & B237 <= B238)))))))
proof
take D151;
take C195;
thus L618: (D151 = D157 & C195 = D158);
let C196 being set;
assume L619: C196 in C190;
reconsider D159 = C196 as (Element of C190) by L619;
reconsider D160 = ( ( C190 --> C191 ) . D159 ) as RelStr;
reconsider D161 = ( C195 . D159 ) , D162 = ( D151 . D159 ) as (Element of D160) by FUNCOP_1:7;
take D160;
take D162;
take D161;
L620: (D160 = C191 & (ex B239 , B240 being (Element of C191) st (B239 = ( D152 . D159 ) & B240 = ( D151 . D159 ) & ( C195 . D159 ) = ( B239 "\/" B240 )))) by L614 , FUNCOP_1:7;
thus L621: thesis by L620 , YELLOW_0:22;
end;
L622: D157 in (the carrier of ( product ( C190 --> C191 ) ));
L623: D157 in ( product ( Carrier ( C190 --> C191 ) ) ) by L622 , L412;
thus L624: thesis by L623 , L617 , L412;
end;
L625: (for B241 being (Element of D150) holds ((B241 >= C192 & B241 >= C193) implies B241 >= D156))
proof
let C197 being (Element of D150);
assume that
L626: C197 >= C192
and
L627: C197 >= C193;
L628: C197 >= D156
proof
reconsider D163 = C197 , D164 = D156 , D165 = C193 , D166 = C192 as (Element of ( product ( C190 --> C191 ) ));
L629: D165 in (the carrier of ( product ( C190 --> C191 ) ));
L630: D165 in ( product ( Carrier ( C190 --> C191 ) ) ) by L629 , L412;
consider C198 , C199 being Function such that L631: (C198 = D165 & C199 = D163) and L632: (for B242 being set holds (B242 in C190 implies (ex B243 being RelStr st (ex B244 , B245 being (Element of B243) st (B243 = ( ( C190 --> C191 ) . B242 ) & B244 = ( C198 . B242 ) & B245 = ( C199 . B242 ) & B244 <= B245))))) by L630 , L627 , L412;
reconsider D167 = D164 , D168 = D163 as (Function of C190 , (the carrier of C191)) by L501;
L633: D166 in (the carrier of ( product ( C190 --> C191 ) ));
L634: D166 in ( product ( Carrier ( C190 --> C191 ) ) ) by L633 , L412;
consider C200 , C201 being Function such that L635: (C200 = D166 & C201 = D163) and L636: (for B246 being set holds (B246 in C190 implies (ex B247 being RelStr st (ex B248 , B249 being (Element of B247) st (B247 = ( ( C190 --> C191 ) . B246 ) & B248 = ( C200 . B246 ) & B249 = ( C201 . B246 ) & B248 <= B249))))) by L634 , L626 , L412;
L637: (ex B250 , B251 being Function st (B250 = D164 & B251 = D163 & (for B252 being set holds (B252 in C190 implies (ex B253 being RelStr st (ex B254 , B255 being (Element of B253) st (B253 = ( ( C190 --> C191 ) . B252 ) & B254 = ( B250 . B252 ) & B255 = ( B251 . B252 ) & B254 <= B255)))))))
proof
take D167;
take D168;
thus L638: (D167 = D164 & D168 = D163);
let C202 being set;
assume L639: C202 in C190;
reconsider D169 = C202 as (Element of C190) by L639;
reconsider D170 = ( ( C190 --> C191 ) . D169 ) as RelStr;
reconsider D171 = ( D168 . D169 ) , D172 = ( D167 . D169 ) as (Element of D170) by FUNCOP_1:7;
take D170;
take D172;
take D171;
L640: (D170 = C191 & (ex B256 , B257 being (Element of C191) st (B256 = ( D152 . D169 ) & B257 = ( D151 . D169 ) & ( C195 . D169 ) = ( B256 "\/" B257 )))) by L614 , FUNCOP_1:7;
L641: ((ex B258 being RelStr st (ex B259 , B260 being (Element of B258) st (B258 = ( ( C190 --> C191 ) . D169 ) & B259 = ( C200 . D169 ) & B260 = ( C201 . D169 ) & B259 <= B260))) & (ex B261 being RelStr st (ex B262 , B263 being (Element of B261) st (B261 = ( ( C190 --> C191 ) . D169 ) & B262 = ( C198 . D169 ) & B263 = ( C199 . D169 ) & B262 <= B263)))) by L636 , L632;
thus L642: thesis by L641 , L635 , L631 , L640 , YELLOW_0:22;
end;
L643: D164 in (the carrier of ( product ( C190 --> C191 ) ));
L644: D164 in ( product ( Carrier ( C190 --> C191 ) ) ) by L643 , L412;
thus L645: thesis by L644 , L637 , L412;
end;
thus L646: thesis by L628;
end;
L647: C192 <= D156
proof
reconsider D173 = C192 , D174 = D156 as (Element of ( product ( C190 --> C191 ) ));
L648: (ex B264 , B265 being Function st (B264 = D173 & B265 = D174 & (for B266 being set holds (B266 in C190 implies (ex B267 being RelStr st (ex B268 , B269 being (Element of B267) st (B267 = ( ( C190 --> C191 ) . B266 ) & B268 = ( B264 . B266 ) & B269 = ( B265 . B266 ) & B268 <= B269)))))))
proof
take D152;
take C195;
thus L649: (D152 = D173 & C195 = D174);
let C203 being set;
assume L650: C203 in C190;
reconsider D175 = C203 as (Element of C190) by L650;
reconsider D176 = ( ( C190 --> C191 ) . D175 ) as RelStr;
reconsider D177 = ( C195 . D175 ) , D178 = ( D152 . D175 ) as (Element of D176) by FUNCOP_1:7;
take D176;
take D178;
take D177;
L651: (D176 = C191 & (ex B270 , B271 being (Element of C191) st (B270 = ( D152 . D175 ) & B271 = ( D151 . D175 ) & ( C195 . D175 ) = ( B270 "\/" B271 )))) by L614 , FUNCOP_1:7;
thus L652: thesis by L651 , YELLOW_0:22;
end;
L653: D173 in (the carrier of ( product ( C190 --> C191 ) ));
L654: D173 in ( product ( Carrier ( C190 --> C191 ) ) ) by L653 , L412;
thus L655: thesis by L654 , L648 , L412;
end;
thus L656: thesis by L647 , L616 , L625;
end;
end;
definition
let C204 , C205 being RelStr;
func MonMaps (C204 , C205) ->  strict  full (SubRelStr of ( C205 |^ (the carrier of C204) )) means 
(for B272 being (Function of C204 , C205) holds (B272 in (the carrier of it) iff (B272 in ( Funcs ((the carrier of C204) , (the carrier of C205)) ) & B272 is  monotone)));
existence
proof
set D179 = ( MonFuncs (C204 , C205) );
L658: D179 c= ( Funcs ((the carrier of C204) , (the carrier of C205)) ) by ORDERS_3:11;
reconsider D180 = D179 as (Subset of ( C205 |^ (the carrier of C204) )) by L658 , L469;
take D181 = ( subrelstr D180 );
let C206 being (Function of C204 , C205);
thus L659:now
assume L660: C206 in (the carrier of D181);
L661: C206 in D180 by L660 , YELLOW_0:def 15;
L662: (ex B273 being (Function of C204 , C205) st (B273 = C206 & B273 in ( Funcs ((the carrier of C204) , (the carrier of C205)) ) & B273 is  monotone)) by L661 , ORDERS_3:def 6;
thus L663: (C206 in ( Funcs ((the carrier of C204) , (the carrier of C205)) ) & C206 is  monotone) by L662;
end;
assume L664: (C206 in ( Funcs ((the carrier of C204) , (the carrier of C205)) ) & C206 is  monotone);
L665: C206 in D180 by L664 , ORDERS_3:def 6;
thus L666: thesis by L665 , YELLOW_0:def 15;
end;
uniqueness
proof
let C207 , C208 being  strict  full (SubRelStr of ( C205 |^ (the carrier of C204) ));
assume that
L667: (for B274 being (Function of C204 , C205) holds (B274 in (the carrier of C207) iff (B274 in ( Funcs ((the carrier of C204) , (the carrier of C205)) ) & B274 is  monotone)))
and
L668: (for B275 being (Function of C204 , C205) holds (B275 in (the carrier of C208) iff (B275 in ( Funcs ((the carrier of C204) , (the carrier of C205)) ) & B275 is  monotone)));
L669: (the carrier of C208) c= (the carrier of ( C205 |^ (the carrier of C204) )) by YELLOW_0:def 13;
L670: (the carrier of C208) c= ( Funcs ((the carrier of C204) , (the carrier of C205)) ) by L669 , L469;
L671: (the carrier of C208) c= (the carrier of C207)
proof
let C209 being set;
assume L672: C209 in (the carrier of C208);
reconsider D182 = C209 as (Function of C204 , C205) by L672 , L670 , FUNCT_2:66;
L673: D182 is  monotone by L668 , L672;
thus L674: thesis by L673 , L667 , L670 , L672;
end;
L675: (the carrier of C207) c= (the carrier of ( C205 |^ (the carrier of C204) )) by YELLOW_0:def 13;
L676: (the carrier of C207) c= ( Funcs ((the carrier of C204) , (the carrier of C205)) ) by L675 , L469;
L677: (the carrier of C207) c= (the carrier of C208)
proof
let C210 being set;
assume L678: C210 in (the carrier of C207);
reconsider D183 = C210 as (Function of C204 , C205) by L678 , L676 , FUNCT_2:66;
L679: D183 is  monotone by L667 , L678;
thus L680: thesis by L679 , L668 , L676 , L678;
end;
L681: (the carrier of C207) = (the carrier of C208) by L677 , L671 , XBOOLE_0:def 10;
thus L682: thesis by L681 , YELLOW_0:57;
end;
end;
