:: Yoneda Embedding
::  by Miros{\l}aw Wojciechowski
::
:: Received June 12, 1997
:: Copyright (c) 1997-2012 Association of Mizar Users
::           (Stowarzyszenie Uzytkownikow Mizara, Bialystok, Poland).
:: This code can be distributed under the GNU General Public Licence
:: version 3.0 or later, or the Creative Commons Attribution-ShareAlike
:: License version 3.0 or later, subject to the binding interpretation
:: detailed in file COPYING.interpretation.
:: See COPYING.GPL and COPYING.CC-BY-SA for the full text of these
:: licenses, or see http://www.gnu.org/licenses/gpl.html and
:: http://creativecommons.org/licenses/by-sa/3.0/.

environ

 vocabularies CAT_1, ENS_1, FUNCT_1, GRAPH_1, RELAT_1, SUBSET_1, MCART_1,
      NATTRA_1, STRUCT_0, XBOOLE_0, PZFMISC1, TARSKI, OPPCAT_1, CAT_2, FUNCT_2,
      YONEDA_1, MONOID_0, PARTFUN1;
 notations TARSKI, XBOOLE_0,
      XTUPLE_0, SUBSET_1, MCART_1, RELAT_1, FUNCT_1, BINOP_1,
      FUNCT_2, STRUCT_0, GRAPH_1, CAT_1, CAT_2, OPPCAT_1, ENS_1,
      CAT_3, NATTRA_1;
 constructors DOMAIN_1, NATTRA_1, ENS_1, RELSET_1, CAT_3, XTUPLE_0;
 registrations XBOOLE_0, FUNCT_1, RELSET_1, ENS_1, STRUCT_0, FUNCT_2,
      RELAT_1, CAT_1, XTUPLE_0;
 requirements SUBSET, BOOLE;
 definitions TARSKI, BINOP_1, GRAPH_1, CAT_1, XTUPLE_0;
 theorems ZFMISC_1, MCART_1, FUNCT_1, FUNCT_2, CAT_1, CAT_2, OPPCAT_1, ENS_1,
      NATTRA_1, ISOCAT_1, RELAT_1, CAT_3, XTUPLE_0;
 schemes FUNCT_2;

begin
definition
let R2 being Category;
func EnsHom R2 -> Category equals 
( Ens ( Hom R2 ) );
correctness;
end;
theorem
L2: (for R2 being Category holds (for B1 , B2 being Function holds (for B3 , B4 being (Morphism of ( EnsHom R2 )) holds ((( cod B3 ) = ( dom B4 ) & [ [ ( dom B3 ) , ( cod B3 ) ] , B1 ] = B3 & [ [ ( dom B4 ) , ( cod B4 ) ] , B2 ] = B4) implies [ [ ( dom B3 ) , ( cod B4 ) ] , ( B2 * B1 ) ] = ( B4 (*) B3 )))))
proof
let R2 being Category;
let C1 , C2 being Function;
let C3 , C4 being (Morphism of ( EnsHom R2 ));
assume that
L3: ( cod C3 ) = ( dom C4 )
and
L4: [ [ ( dom C3 ) , ( cod C3 ) ] , C1 ] = C3
and
L5: [ [ ( dom C4 ) , ( cod C4 ) ] , C2 ] = C4;
L6: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D1 = C3 as (Element of ( Maps ( Hom R2 ) )) by L6;
reconsider D2 = C4 as (Element of ( Maps ( Hom R2 ) )) by L6;
L7: ( cod D1 ) = ( ( C3 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( dom C3 ) , ( cod C3 ) ] `2 ) by L4 , MCART_1:7
.= ( dom C4 ) by L3
.= ( [ ( dom C4 ) , ( cod C4 ) ] `1 )
.= ( ( C4 `1 ) `1 ) by L5 , MCART_1:7
.= ( dom D2 ) by ENS_1:def 3;
L8: [ [ ( dom D1 ) , ( cod D1 ) ] , ( D1 `2 ) ] = C3 by ENS_1:8;
L9: ( D1 `2 ) = C1 by L8 , L4 , XTUPLE_0:1;
L10: [ [ ( dom D2 ) , ( cod D2 ) ] , ( D2 `2 ) ] = C4 by ENS_1:8;
L11: ( D2 `2 ) = C2 by L10 , L5 , XTUPLE_0:1;
L12: ( cod C4 ) = ( [ ( dom C4 ) , ( cod C4 ) ] `2 )
.= ( ( C4 `1 ) `2 ) by L5 , MCART_1:7
.= ( cod D2 ) by ENS_1:def 4;
L13: ( dom D1 ) = ( ( C3 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( dom C3 ) , ( cod C3 ) ] `1 ) by L4 , MCART_1:7
.= ( dom C3 );
L14: [ C4 , C3 ] in ( dom (the Comp of ( EnsHom R2 )) ) by L3 , CAT_1:15;
L15: ( C4 (*) C3 ) = ( ( fComp ( Hom R2 ) ) . (D2 , D1) ) by L14 , L6 , CAT_1:def 1
.= ( D2 * D1 ) by L7 , ENS_1:def 11
.= [ [ ( dom C3 ) , ( cod C4 ) ] , ( C2 * C1 ) ] by L7 , L13 , L12 , L11 , L9 , ENS_1:def 6;
thus L16: thesis by L15;
end;
definition
let R2 being Category;
let R3 being (Object of R2);
func <|R3 ,?> -> (Functor of R2 , ( EnsHom R2 )) equals 
( hom?- R3 );
coherence by ENS_1:49;
end;
theorem
L18: (for R2 being Category holds (for B5 being (Morphism of R2) holds <| ( cod B5 ) ,?> is_naturally_transformable_to <| ( dom B5 ) ,?>))
proof
let R2 being Category;
let R5 being (Morphism of R2);
set D3 = <| ( cod R5 ) ,?>;
set D4 = <| ( dom R5 ) ,?>;
set D5 = ( EnsHom R2 );
deffunc H1((Element of R2)) = [ [ ( Hom (( cod R5 ) , $1) ) , ( Hom (( dom R5 ) , $1) ) ] , ( hom (R5 , $1) ) ];
L19: (for B6 being (Object of R2) holds [ [ ( Hom (( cod R5 ) , B6) ) , ( Hom (( dom R5 ) , B6) ) ] , ( hom (R5 , B6) ) ] in ( Hom (( D3 . B6 ) , ( D4 . B6 )) ))
proof
let C5 being (Object of R2);
L20: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D6 = [ [ ( Hom (( cod R5 ) , C5) ) , ( Hom (( dom R5 ) , C5) ) ] , ( hom (R5 , C5) ) ] as (Morphism of ( EnsHom R2 )) by L20 , ENS_1:48;
reconsider D7 = D6 as (Element of ( Maps ( Hom R2 ) )) by ENS_1:48;
L21: ( cod D6 ) = ( ( fCod ( Hom R2 ) ) . D6 ) by L20
.= ( cod D7 ) by ENS_1:def 10
.= ( ( D6 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C5) ) , ( Hom (( dom R5 ) , C5) ) ] `2 ) by MCART_1:7
.= ( Hom (( dom R5 ) , C5) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( dom R5 )) ) ) . C5 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( dom R5 )) ) . C5 )
.= ( D4 . C5 ) by ENS_1:def 25;
L22: ( dom D6 ) = ( ( fDom ( Hom R2 ) ) . D6 ) by L20
.= ( dom D7 ) by ENS_1:def 9
.= ( ( D6 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C5) ) , ( Hom (( dom R5 ) , C5) ) ] `1 ) by MCART_1:7
.= ( Hom (( cod R5 ) , C5) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( cod R5 )) ) ) . C5 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( cod R5 )) ) . C5 )
.= ( D3 . C5 ) by ENS_1:def 25;
thus L23: thesis by L22 , L21;
end;
L24: (for B7 being (Element of R2) holds H1(B7) in (the carrier' of D5))
proof
let R3 being (Object of R2);
L25: [ [ ( Hom (( cod R5 ) , R3) ) , ( Hom (( dom R5 ) , R3) ) ] , ( hom (R5 , R3) ) ] in ( Hom (( D3 . R3 ) , ( D4 . R3 )) ) by L19;
thus L26: thesis by L25;
end;
consider C6 being (Function of (the carrier of R2) , (the carrier' of D5)) such that L27: (for B8 being (Element of R2) holds ( C6 . B8 ) = H1(B8)) from FUNCT_2:sch 8(L24);
L28: (for B9 being (Object of R2) holds ( C6 . B9 ) is (Morphism of ( D3 . B9 ) , ( D4 . B9 )))
proof
let R3 being (Object of R2);
L29: [ [ ( Hom (( cod R5 ) , R3) ) , ( Hom (( dom R5 ) , R3) ) ] , ( hom (R5 , R3) ) ] in ( Hom (( D3 . R3 ) , ( D4 . R3 )) ) by L19;
L30: [ [ ( Hom (( cod R5 ) , R3) ) , ( Hom (( dom R5 ) , R3) ) ] , ( hom (R5 , R3) ) ] is (Morphism of ( D3 . R3 ) , ( D4 . R3 )) by L29 , CAT_1:def 5;
thus L31: thesis by L30 , L27;
end;
L32: (for B10 being (Object of R2) holds ( Hom (( D3 . B10 ) , ( D4 . B10 )) ) <> ( {} )) by L19;
L33: D3 is_transformable_to D4 by L32 , NATTRA_1:def 2;
reconsider D8 = C6 as (transformation of D3 , D4) by L33 , L28 , NATTRA_1:def 3;
L34: (for B11 , B12 being (Object of R2) holds (( Hom (B11 , B12) ) <> ( {} ) implies (for B13 being (Morphism of B11 , B12) holds ( ( D8 . B12 ) * ( D3 /. B13 ) ) = ( ( D4 /. B13 ) * ( D8 . B11 ) ))))
proof
let C7 , C8 being (Object of R2);
assume that
L35: ( Hom (C7 , C8) ) <> ( {} );
L36: ( Hom (( D3 . C7 ) , ( D3 . C8 )) ) <> ( {} ) by L35 , CAT_1:84;
let C9 being (Morphism of C7 , C8);
L37: ( dom C9 ) = C7 by L35 , CAT_1:5;
L38: ( rng ( hom (( cod R5 ) , C9) ) ) c= ( dom ( hom (R5 , C8) ) )
proof
L39: ( cod C9 ) = C8 by L35 , CAT_1:5;
per cases ;
suppose L40: ( Hom (( dom R5 ) , C8) ) = ( {} );

L41: ( Hom (( cod R5 ) , C8) ) = ( {} ) by L40 , ENS_1:42;
thus L42: thesis by L41 , L39;
end;
suppose L43: ( Hom (( dom R5 ) , C8) ) <> ( {} );

L44: ( cod C9 ) = C8 by L35 , CAT_1:5;
L45: (( rng ( hom (( cod R5 ) , C9) ) ) c= ( Hom (( cod R5 ) , ( cod C9 )) ) & ( Hom (( cod R5 ) , ( cod C9 )) ) = ( dom ( hom (R5 , C8) ) )) by L44 , L43 , FUNCT_2:def 1 , RELAT_1:def 19;
let C10 being set;
assume L46: C10 in ( rng ( hom (( cod R5 ) , C9) ) );
thus L47: thesis by L46 , L45;
end;
end;
L49: ( rng ( hom (R5 , C7) ) ) c= ( dom ( hom (( dom R5 ) , C9) ) )
proof
L50: ( dom C9 ) = C7 by L35 , CAT_1:5;
per cases ;
suppose L51: ( Hom (( dom R5 ) , ( cod C9 )) ) = ( {} );

L52: ( Hom (( dom R5 ) , ( dom C9 )) ) = ( {} ) by L51 , ENS_1:42;
thus L53: thesis by L52 , L50;
end;
suppose L54: ( Hom (( dom R5 ) , ( cod C9 )) ) <> ( {} );

let C11 being set;
assume L55: C11 in ( rng ( hom (R5 , C7) ) );
L56: (( rng ( hom (R5 , C7) ) ) c= ( Hom (( dom R5 ) , C7) ) & ( Hom (( dom R5 ) , C7) ) = ( dom ( hom (( dom R5 ) , C9) ) )) by L50 , L54 , FUNCT_2:def 1 , RELAT_1:def 19;
thus L57: thesis by L56 , L55;
end;
end;
L59: ( dom ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) ) = ( dom ( ( hom (( dom R5 ) , C9) ) * ( hom (R5 , C7) ) ) )
proof
per cases ;
suppose L60: ( Hom (( cod R5 ) , ( dom C9 )) ) = ( {} );

L61: ( dom ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) ) = ( dom ( hom (( cod R5 ) , C9) ) ) by L38 , RELAT_1:27
.= ( Hom (( cod R5 ) , ( dom C9 )) ) by L60
.= ( dom ( hom (R5 , C7) ) ) by L37 , L60
.= ( dom ( ( hom (( dom R5 ) , C9) ) * ( hom (R5 , C7) ) ) ) by L49 , RELAT_1:27;
thus L62: thesis by L61;
end;
suppose L63: ( Hom (( cod R5 ) , ( dom C9 )) ) <> ( {} );

L64: ( Hom (( cod R5 ) , ( cod C9 )) ) <> ( {} ) by L63 , ENS_1:42;
L65: ( Hom (( dom R5 ) , C7) ) <> ( {} ) by L37 , L63 , ENS_1:42;
L66: ( dom ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) ) = ( dom ( hom (( cod R5 ) , C9) ) ) by L38 , RELAT_1:27
.= ( Hom (( cod R5 ) , ( dom C9 )) ) by L64 , FUNCT_2:def 1
.= ( Hom (( cod R5 ) , C7) ) by L35 , CAT_1:5
.= ( dom ( hom (R5 , C7) ) ) by L65 , FUNCT_2:def 1
.= ( dom ( ( hom (( dom R5 ) , C9) ) * ( hom (R5 , C7) ) ) ) by L49 , RELAT_1:27;
thus L67: thesis by L66;
end;
end;
L69: (for B14 being set holds (B14 in ( dom ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) ) implies ( ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) . B14 ) = ( ( ( hom (( dom R5 ) , C9) ) * ( hom (R5 , C7) ) ) . B14 )))
proof
let C12 being set;
assume that
L70: C12 in ( dom ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) );
per cases ;
suppose L71: ( Hom (( cod R5 ) , ( dom C9 )) ) <> ( {} );

L72: C12 in ( dom ( hom (( cod R5 ) , C9) ) ) by L70 , FUNCT_1:11;
L73: ( Hom (( cod R5 ) , ( cod C9 )) ) <> ( {} ) by L71 , ENS_1:42;
L74: C12 in ( Hom (( cod R5 ) , ( dom C9 )) ) by L73 , L72 , FUNCT_2:def 1;
reconsider D9 = C12 as (Morphism of R2) by L74;
L75: (( dom C9 ) = ( cod D9 ) & ( dom D9 ) = ( cod R5 )) by L74 , CAT_1:1;
L76: ( dom C9 ) = ( cod D9 ) by L74 , CAT_1:1;
L77: ( cod ( C9 (*) D9 ) ) = ( cod C9 ) by L76 , CAT_1:17
.= C8 by L35 , CAT_1:5;
L78: ( ( hom (R5 , C7) ) . D9 ) = ( D9 (*) R5 ) by L37 , L74 , ENS_1:def 20;
reconsider D10 = ( ( hom (R5 , C7) ) . D9 ) as (Morphism of R2) by L78;
L79: ( dom D9 ) = ( cod R5 ) by L74 , CAT_1:1;
L80: ( dom ( D9 (*) R5 ) ) = ( dom R5 ) by L79 , CAT_1:17;
L81: ( dom ( C9 (*) D9 ) ) = ( dom D9 ) by L76 , CAT_1:17
.= ( cod R5 ) by L74 , CAT_1:1;
L82: ( C9 (*) D9 ) in ( Hom (( cod R5 ) , C8) ) by L81 , L77;
L83: ( cod ( D9 (*) R5 ) ) = ( cod D9 ) by L79 , CAT_1:17
.= ( dom C9 ) by L74 , CAT_1:1;
L84: ( ( hom (R5 , C7) ) . D9 ) in ( Hom (( dom R5 ) , ( dom C9 )) ) by L83 , L78 , L80;
L85: ( ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) . D9 ) = ( ( hom (R5 , C8) ) . ( ( hom (( cod R5 ) , C9) ) . D9 ) ) by L70 , FUNCT_1:12
.= ( ( hom (R5 , C8) ) . ( C9 (*) D9 ) ) by L74 , ENS_1:def 19
.= ( ( C9 (*) D9 ) (*) R5 ) by L82 , ENS_1:def 20
.= ( C9 (*) ( D9 (*) R5 ) ) by L75 , CAT_1:18
.= ( C9 (*) D10 ) by L37 , L74 , ENS_1:def 20
.= ( ( hom (( dom R5 ) , C9) ) . ( ( hom (R5 , C7) ) . D9 ) ) by L84 , ENS_1:def 19
.= ( ( ( hom (( dom R5 ) , C9) ) * ( hom (R5 , C7) ) ) . D9 ) by L59 , L70 , FUNCT_1:12;
thus L86: thesis by L85;
end;
suppose L87: ( Hom (( cod R5 ) , ( dom C9 )) ) = ( {} );

L88: C12 in ( dom ( hom (( cod R5 ) , C9) ) ) by L70 , FUNCT_1:11;
thus L89: thesis by L88 , L87;
end;
end;
L91: ( Hom (( D4 . C7 ) , ( D4 . C8 )) ) <> ( {} ) by L35 , CAT_1:84;
L92: ( cod C9 ) = C8 by L35 , CAT_1:5;
reconsider D11 = ( D8 . C7 ) as (Morphism of ( EnsHom R2 ));
L93: ( D8 . C7 ) = ( (D8 qua (Function of (the carrier of R2) , (the carrier' of D5))) . C7 ) by L33 , NATTRA_1:def 5
.= [ [ ( Hom (( cod R5 ) , C7) ) , ( Hom (( dom R5 ) , C7) ) ] , ( hom (R5 , C7) ) ] by L27;
reconsider D12 = D11 as (Element of ( Maps ( Hom R2 ) )) by L93 , ENS_1:48;
L94: ( Hom (( D3 . C7 ) , ( D4 . C7 )) ) <> ( {} ) by L19;
reconsider D13 = ( D8 . C8 ) as (Morphism of ( EnsHom R2 ));
L95: ( D8 . C8 ) = ( (D8 qua (Function of (the carrier of R2) , (the carrier' of D5))) . C8 ) by L33 , NATTRA_1:def 5
.= [ [ ( Hom (( cod R5 ) , C8) ) , ( Hom (( dom R5 ) , C8) ) ] , ( hom (R5 , C8) ) ] by L27;
reconsider D14 = D13 as (Element of ( Maps ( Hom R2 ) )) by L95 , ENS_1:48;
L96: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
L97: ( cod D13 ) = ( ( fCod ( Hom R2 ) ) . D13 ) by L96
.= ( cod D14 ) by ENS_1:def 10
.= ( ( D13 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C8) ) , ( Hom (( dom R5 ) , C8) ) ] `2 ) by L95 , MCART_1:7
.= ( Hom (( dom R5 ) , C8) );
L98: ( dom D11 ) = ( ( fDom ( Hom R2 ) ) . D11 ) by L96
.= ( dom D12 ) by ENS_1:def 9
.= ( ( D11 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C7) ) , ( Hom (( dom R5 ) , C7) ) ] `1 ) by L93 , MCART_1:7
.= ( Hom (( cod R5 ) , C7) );
L99: ( cod D11 ) = ( ( fCod ( Hom R2 ) ) . D11 ) by L96
.= ( cod D12 ) by ENS_1:def 10
.= ( ( D11 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C7) ) , ( Hom (( dom R5 ) , C7) ) ] `2 ) by L93 , MCART_1:7
.= ( Hom (( dom R5 ) , C7) );
reconsider D15 = ( D3 /. C9 ) as (Morphism of ( EnsHom R2 ));
L100: D15 = ( ( hom?- ( cod R5 ) ) . C9 ) by L35 , CAT_3:def 10
.= [ [ ( Hom (( cod R5 ) , ( dom C9 )) ) , ( Hom (( cod R5 ) , ( cod C9 )) ) ] , ( hom (( cod R5 ) , C9) ) ] by ENS_1:def 21;
reconsider D16 = D15 as (Element of ( Maps ( Hom R2 ) )) by L100 , ENS_1:47;
L101: ( dom D15 ) = ( ( fDom ( Hom R2 ) ) . D15 ) by L96
.= ( dom D16 ) by ENS_1:def 9
.= ( ( D15 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , ( dom C9 )) ) , ( Hom (( cod R5 ) , ( cod C9 )) ) ] `1 ) by L100 , MCART_1:7
.= ( Hom (( cod R5 ) , ( dom C9 )) );
L102: ( cod D15 ) = ( ( fCod ( Hom R2 ) ) . D15 ) by L96
.= ( cod D16 ) by ENS_1:def 10
.= ( ( D15 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , ( dom C9 )) ) , ( Hom (( cod R5 ) , ( cod C9 )) ) ] `2 ) by L100 , MCART_1:7
.= ( Hom (( cod R5 ) , ( cod C9 )) );
L103: ( dom D13 ) = ( ( fDom ( Hom R2 ) ) . D13 ) by L96
.= ( dom D14 ) by ENS_1:def 9
.= ( ( D13 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C8) ) , ( Hom (( dom R5 ) , C8) ) ] `1 ) by L95 , MCART_1:7
.= ( Hom (( cod R5 ) , C8) );
L104: ( cod D15 ) = ( dom D13 ) by L103 , L35 , L102 , CAT_1:5;
reconsider D17 = ( D4 /. C9 ) as (Morphism of ( EnsHom R2 ));
L105: D17 = ( ( hom?- ( dom R5 ) ) . C9 ) by L35 , CAT_3:def 10
.= [ [ ( Hom (( dom R5 ) , ( dom C9 )) ) , ( Hom (( dom R5 ) , ( cod C9 )) ) ] , ( hom (( dom R5 ) , C9) ) ] by ENS_1:def 21;
reconsider D18 = D17 as (Element of ( Maps ( Hom R2 ) )) by L105 , ENS_1:47;
L106: ( cod D17 ) = ( ( fCod ( Hom R2 ) ) . D17 ) by L96
.= ( cod D18 ) by ENS_1:def 10
.= ( ( D17 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( dom R5 ) , ( dom C9 )) ) , ( Hom (( dom R5 ) , ( cod C9 )) ) ] `2 ) by L105 , MCART_1:7
.= ( Hom (( dom R5 ) , ( cod C9 )) );
L107: ( dom D17 ) = ( ( fDom ( Hom R2 ) ) . D17 ) by L96
.= ( dom D18 ) by ENS_1:def 9
.= ( ( D17 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( dom R5 ) , ( dom C9 )) ) , ( Hom (( dom R5 ) , ( cod C9 )) ) ] `1 ) by L105 , MCART_1:7
.= ( Hom (( dom R5 ) , ( dom C9 )) );
L108: ( cod D11 ) = ( dom D17 ) by L107 , L35 , L99 , CAT_1:5;
L109: ( Hom (( D3 . C8 ) , ( D4 . C8 )) ) <> ( {} ) by L19;
L110: ( ( D8 . C8 ) * ( D3 /. C9 ) ) = ( D13 (*) D15 ) by L109 , L36 , CAT_1:def 13
.= [ [ ( Hom (( cod R5 ) , ( dom C9 )) ) , ( Hom (( dom R5 ) , C8) ) ] , ( ( hom (R5 , C8) ) * ( hom (( cod R5 ) , C9) ) ) ] by L95 , L103 , L97 , L100 , L101 , L102 , L104 , L2
.= [ [ ( Hom (( cod R5 ) , C7) ) , ( Hom (( dom R5 ) , ( cod C9 )) ) ] , ( ( hom (( dom R5 ) , C9) ) * ( hom (R5 , C7) ) ) ] by L37 , L92 , L59 , L69 , FUNCT_1:2
.= ( D17 (*) D11 ) by L105 , L107 , L106 , L93 , L98 , L99 , L108 , L2
.= ( ( D4 /. C9 ) * ( D8 . C7 ) ) by L91 , L94 , CAT_1:def 13;
thus L111: thesis by L110;
end;
thus L112: thesis by L34 , L33 , NATTRA_1:def 7;
end;
definition
let R2 being Category;
let R5 being (Morphism of R2);
func <|R5 ,?> -> (natural_transformation of <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?>) means 
:L113: (for B15 being (Object of R2) holds ( it . B15 ) = [ [ ( Hom (( cod R5 ) , B15) ) , ( Hom (( dom R5 ) , B15) ) ] , ( hom (R5 , ( id B15 )) ) ]);
existence
proof
set D19 = ( EnsHom R2 );
deffunc H2((Element of R2)) = [ [ ( Hom (( cod R5 ) , $1) ) , ( Hom (( dom R5 ) , $1) ) ] , ( hom (R5 , ( id $1 )) ) ];
set D20 = <| ( cod R5 ) ,?>;
set D21 = <| ( dom R5 ) ,?>;
L114: (for B16 being (Object of R2) holds [ [ ( Hom (( cod R5 ) , B16) ) , ( Hom (( dom R5 ) , B16) ) ] , ( hom (R5 , ( id B16 )) ) ] in ( Hom (( D20 . B16 ) , ( D21 . B16 )) ))
proof
let C13 being (Object of R2);
L115: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
L116: ( hom (R5 , ( id C13 )) ) = ( hom (R5 , C13) ) by ENS_1:53;
reconsider D22 = [ [ ( Hom (( cod R5 ) , C13) ) , ( Hom (( dom R5 ) , C13) ) ] , ( hom (R5 , ( id C13 )) ) ] as (Morphism of ( EnsHom R2 )) by L116 , L115 , ENS_1:48;
reconsider D23 = D22 as (Element of ( Maps ( Hom R2 ) )) by L116 , ENS_1:48;
L117: ( cod D22 ) = ( ( fCod ( Hom R2 ) ) . D22 ) by L115
.= ( cod D23 ) by ENS_1:def 10
.= ( ( D22 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C13) ) , ( Hom (( dom R5 ) , C13) ) ] `2 ) by MCART_1:7
.= ( Hom (( dom R5 ) , C13) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( dom R5 )) ) ) . C13 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( dom R5 )) ) . C13 )
.= ( D21 . C13 ) by ENS_1:def 25;
L118: ( dom D22 ) = ( ( fDom ( Hom R2 ) ) . D22 ) by L115
.= ( dom D23 ) by ENS_1:def 9
.= ( ( D22 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C13) ) , ( Hom (( dom R5 ) , C13) ) ] `1 ) by MCART_1:7
.= ( Hom (( cod R5 ) , C13) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( cod R5 )) ) ) . C13 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( cod R5 )) ) . C13 )
.= ( D20 . C13 ) by ENS_1:def 25;
thus L119: thesis by L118 , L117;
end;
L120: (for B17 being (Element of R2) holds H2(B17) in (the carrier' of ( EnsHom R2 )))
proof
let R4 being (Object of R2);
L121: [ [ ( Hom (( cod R5 ) , R4) ) , ( Hom (( dom R5 ) , R4) ) ] , ( hom (R5 , ( id R4 )) ) ] in ( Hom (( D20 . R4 ) , ( D21 . R4 )) ) by L114;
thus L122: thesis by L121;
end;
consider C14 being (Function of (the carrier of R2) , (the carrier' of ( EnsHom R2 ))) such that L123: (for B18 being (Element of R2) holds ( C14 . B18 ) = H2(B18)) from FUNCT_2:sch 8(L120);
L124: (for B19 being (Object of R2) holds ( C14 . B19 ) is (Morphism of ( D20 . B19 ) , ( D21 . B19 )))
proof
let R4 being (Object of R2);
L125: [ [ ( Hom (( cod R5 ) , R4) ) , ( Hom (( dom R5 ) , R4) ) ] , ( hom (R5 , ( id R4 )) ) ] in ( Hom (( D20 . R4 ) , ( D21 . R4 )) ) by L114;
L126: [ [ ( Hom (( cod R5 ) , R4) ) , ( Hom (( dom R5 ) , R4) ) ] , ( hom (R5 , ( id R4 )) ) ] is (Morphism of ( D20 . R4 ) , ( D21 . R4 )) by L125 , CAT_1:def 5;
thus L127: thesis by L126 , L123;
end;
L128: (for B20 being (Object of R2) holds ( Hom (( D20 . B20 ) , ( D21 . B20 )) ) <> ( {} )) by L114;
L129: D20 is_transformable_to D21 by L128 , NATTRA_1:def 2;
reconsider D24 = C14 as (transformation of D20 , D21) by L129 , L124 , NATTRA_1:def 3;
L130: (for B21 , B22 being (Object of R2) holds (( Hom (B21 , B22) ) <> ( {} ) implies (for B23 being (Morphism of B21 , B22) holds ( ( D24 . B22 ) * ( D20 /. B23 ) ) = ( ( D21 /. B23 ) * ( D24 . B21 ) ))))
proof
let C15 , C16 being (Object of R2);
assume that
L131: ( Hom (C15 , C16) ) <> ( {} );
L132: ( Hom (( D20 . C15 ) , ( D20 . C16 )) ) <> ( {} ) by L131 , CAT_1:84;
let C17 being (Morphism of C15 , C16);
L133: ( dom C17 ) = C15 by L131 , CAT_1:5;
L134: ( rng ( hom (( cod R5 ) , C17) ) ) c= ( dom ( hom (R5 , C16) ) )
proof
L135: ( cod C17 ) = C16 by L131 , CAT_1:5;
per cases ;
suppose L136: ( Hom (( dom R5 ) , C16) ) = ( {} );

L137: ( Hom (( cod R5 ) , C16) ) = ( {} ) by L136 , ENS_1:42;
thus L138: thesis by L137 , L135;
end;
suppose L139: ( Hom (( dom R5 ) , C16) ) <> ( {} );

L140: ( cod C17 ) = C16 by L131 , CAT_1:5;
L141: (( rng ( hom (( cod R5 ) , C17) ) ) c= ( Hom (( cod R5 ) , ( cod C17 )) ) & ( Hom (( cod R5 ) , ( cod C17 )) ) = ( dom ( hom (R5 , C16) ) )) by L140 , L139 , FUNCT_2:def 1 , RELAT_1:def 19;
let C18 being set;
assume L142: C18 in ( rng ( hom (( cod R5 ) , C17) ) );
thus L143: thesis by L142 , L141;
end;
end;
L145: ( rng ( hom (R5 , C15) ) ) c= ( dom ( hom (( dom R5 ) , C17) ) )
proof
L146: ( dom C17 ) = C15 by L131 , CAT_1:5;
per cases ;
suppose L147: ( Hom (( dom R5 ) , ( cod C17 )) ) = ( {} );

L148: ( Hom (( dom R5 ) , ( dom C17 )) ) = ( {} ) by L147 , ENS_1:42;
thus L149: thesis by L148 , L146;
end;
suppose L150: ( Hom (( dom R5 ) , ( cod C17 )) ) <> ( {} );

let C19 being set;
assume L151: C19 in ( rng ( hom (R5 , C15) ) );
L152: (( rng ( hom (R5 , C15) ) ) c= ( Hom (( dom R5 ) , C15) ) & ( Hom (( dom R5 ) , C15) ) = ( dom ( hom (( dom R5 ) , C17) ) )) by L146 , L150 , FUNCT_2:def 1 , RELAT_1:def 19;
thus L153: thesis by L152 , L151;
end;
end;
L155: ( dom ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) ) = ( dom ( ( hom (( dom R5 ) , C17) ) * ( hom (R5 , C15) ) ) )
proof
per cases ;
suppose L156: ( Hom (( cod R5 ) , ( dom C17 )) ) = ( {} );

L157: ( dom ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) ) = ( dom ( hom (( cod R5 ) , C17) ) ) by L134 , RELAT_1:27
.= ( Hom (( cod R5 ) , C15) ) by L133 , L156
.= ( dom ( hom (R5 , C15) ) ) by L133 , L156
.= ( dom ( ( hom (( dom R5 ) , C17) ) * ( hom (R5 , C15) ) ) ) by L145 , RELAT_1:27;
thus L158: thesis by L157;
end;
suppose L159: ( Hom (( cod R5 ) , ( dom C17 )) ) <> ( {} );

L160: ( Hom (( cod R5 ) , ( cod C17 )) ) <> ( {} ) by L159 , ENS_1:42;
L161: ( Hom (( dom R5 ) , C15) ) <> ( {} ) by L133 , L159 , ENS_1:42;
L162: ( dom ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) ) = ( dom ( hom (( cod R5 ) , C17) ) ) by L134 , RELAT_1:27
.= ( Hom (( cod R5 ) , C15) ) by L133 , L160 , FUNCT_2:def 1
.= ( dom ( hom (R5 , C15) ) ) by L161 , FUNCT_2:def 1
.= ( dom ( ( hom (( dom R5 ) , C17) ) * ( hom (R5 , C15) ) ) ) by L145 , RELAT_1:27;
thus L163: thesis by L162;
end;
end;
L165: (for B24 being set holds (B24 in ( dom ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) ) implies ( ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) . B24 ) = ( ( ( hom (( dom R5 ) , C17) ) * ( hom (R5 , C15) ) ) . B24 )))
proof
let C20 being set;
assume that
L166: C20 in ( dom ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) );
per cases ;
suppose L167: ( Hom (( cod R5 ) , ( dom C17 )) ) <> ( {} );

L168: C20 in ( dom ( hom (( cod R5 ) , C17) ) ) by L166 , FUNCT_1:11;
L169: ( Hom (( cod R5 ) , ( cod C17 )) ) <> ( {} ) by L167 , ENS_1:42;
L170: C20 in ( Hom (( cod R5 ) , ( dom C17 )) ) by L169 , L168 , FUNCT_2:def 1;
reconsider D25 = C20 as (Morphism of R2) by L170;
L171: ( dom C17 ) = ( cod D25 ) by L170 , CAT_1:1;
L172: ( cod C17 ) = C16 by L131 , CAT_1:5;
L173: ( cod ( C17 (*) D25 ) ) = C16 by L172 , L171 , CAT_1:17;
L174: ( dom ( C17 (*) D25 ) ) = ( dom D25 ) by L171 , CAT_1:17
.= ( cod R5 ) by L170 , CAT_1:1;
L175: ( C17 (*) D25 ) in ( Hom (( cod R5 ) , C16) ) by L174 , L173;
L176: ( dom D25 ) = ( cod R5 ) by L170 , CAT_1:1;
L177: ( dom ( D25 (*) R5 ) ) = ( dom R5 ) by L176 , CAT_1:17;
L178: ( ( hom (R5 , C15) ) . D25 ) = ( D25 (*) R5 ) by L133 , L170 , ENS_1:def 20;
reconsider D26 = ( ( hom (R5 , C15) ) . D25 ) as (Morphism of R2) by L178;
L179: (( dom C17 ) = ( cod D25 ) & ( dom D25 ) = ( cod R5 )) by L170 , CAT_1:1;
L180: ( cod ( D25 (*) R5 ) ) = ( cod D25 ) by L176 , CAT_1:17
.= ( dom C17 ) by L170 , CAT_1:1;
L181: ( ( hom (R5 , C15) ) . D25 ) in ( Hom (( dom R5 ) , ( dom C17 )) ) by L180 , L178 , L177;
L182: ( ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) . D25 ) = ( ( hom (R5 , C16) ) . ( ( hom (( cod R5 ) , C17) ) . D25 ) ) by L166 , FUNCT_1:12
.= ( ( hom (R5 , C16) ) . ( C17 (*) D25 ) ) by L170 , ENS_1:def 19
.= ( ( C17 (*) D25 ) (*) R5 ) by L175 , ENS_1:def 20
.= ( C17 (*) ( D25 (*) R5 ) ) by L179 , CAT_1:18
.= ( C17 (*) D26 ) by L133 , L170 , ENS_1:def 20
.= ( ( hom (( dom R5 ) , C17) ) . ( ( hom (R5 , C15) ) . D25 ) ) by L181 , ENS_1:def 19
.= ( ( ( hom (( dom R5 ) , C17) ) * ( hom (R5 , C15) ) ) . D25 ) by L155 , L166 , FUNCT_1:12;
thus L183: thesis by L182;
end;
suppose L184: ( Hom (( cod R5 ) , ( dom C17 )) ) = ( {} );

L185: C20 in ( dom ( hom (( cod R5 ) , C17) ) ) by L166 , FUNCT_1:11;
thus L186: thesis by L185 , L184;
end;
end;
L188: ( Hom (( D21 . C15 ) , ( D21 . C16 )) ) <> ( {} ) by L131 , CAT_1:84;
L189: ( cod C17 ) = C16 by L131 , CAT_1:5;
reconsider D27 = ( D24 . C15 ) as (Morphism of ( EnsHom R2 ));
L190: ( D24 . C15 ) = ( (D24 qua (Function of (the carrier of R2) , (the carrier' of D19))) . C15 ) by L129 , NATTRA_1:def 5
.= [ [ ( Hom (( cod R5 ) , C15) ) , ( Hom (( dom R5 ) , C15) ) ] , ( hom (R5 , ( id C15 )) ) ] by L123
.= [ [ ( Hom (( cod R5 ) , C15) ) , ( Hom (( dom R5 ) , C15) ) ] , ( hom (R5 , C15) ) ] by ENS_1:53;
reconsider D28 = D27 as (Element of ( Maps ( Hom R2 ) )) by L190 , ENS_1:48;
L191: ( Hom (( D20 . C15 ) , ( D21 . C15 )) ) <> ( {} ) by L114;
reconsider D29 = ( D24 . C16 ) as (Morphism of ( EnsHom R2 ));
L192: ( D24 . C16 ) = ( (D24 qua (Function of (the carrier of R2) , (the carrier' of D19))) . C16 ) by L129 , NATTRA_1:def 5
.= [ [ ( Hom (( cod R5 ) , C16) ) , ( Hom (( dom R5 ) , C16) ) ] , ( hom (R5 , ( id C16 )) ) ] by L123
.= [ [ ( Hom (( cod R5 ) , C16) ) , ( Hom (( dom R5 ) , C16) ) ] , ( hom (R5 , C16) ) ] by ENS_1:53;
reconsider D30 = D29 as (Element of ( Maps ( Hom R2 ) )) by L192 , ENS_1:48;
L193: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
L194: ( cod D29 ) = ( ( fCod ( Hom R2 ) ) . D29 ) by L193
.= ( cod D30 ) by ENS_1:def 10
.= ( ( D29 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C16) ) , ( Hom (( dom R5 ) , C16) ) ] `2 ) by L192 , MCART_1:7
.= ( Hom (( dom R5 ) , C16) );
L195: ( dom D27 ) = ( ( fDom ( Hom R2 ) ) . D27 ) by L193
.= ( dom D28 ) by ENS_1:def 9
.= ( ( D27 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C15) ) , ( Hom (( dom R5 ) , C15) ) ] `1 ) by L190 , MCART_1:7
.= ( Hom (( cod R5 ) , C15) );
L196: ( cod D27 ) = ( ( fCod ( Hom R2 ) ) . D27 ) by L193
.= ( cod D28 ) by ENS_1:def 10
.= ( ( D27 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C15) ) , ( Hom (( dom R5 ) , C15) ) ] `2 ) by L190 , MCART_1:7
.= ( Hom (( dom R5 ) , C15) );
reconsider D31 = ( D20 /. C17 ) as (Morphism of ( EnsHom R2 ));
L197: D31 = ( ( hom?- ( cod R5 ) ) . C17 ) by L131 , CAT_3:def 10
.= [ [ ( Hom (( cod R5 ) , ( dom C17 )) ) , ( Hom (( cod R5 ) , ( cod C17 )) ) ] , ( hom (( cod R5 ) , C17) ) ] by ENS_1:def 21;
reconsider D32 = D31 as (Element of ( Maps ( Hom R2 ) )) by L197 , ENS_1:47;
L198: ( dom D31 ) = ( ( fDom ( Hom R2 ) ) . D31 ) by L193
.= ( dom D32 ) by ENS_1:def 9
.= ( ( D31 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , ( dom C17 )) ) , ( Hom (( cod R5 ) , ( cod C17 )) ) ] `1 ) by L197 , MCART_1:7
.= ( Hom (( cod R5 ) , ( dom C17 )) );
L199: ( cod D31 ) = ( ( fCod ( Hom R2 ) ) . D31 ) by L193
.= ( cod D32 ) by ENS_1:def 10
.= ( ( D31 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , ( dom C17 )) ) , ( Hom (( cod R5 ) , ( cod C17 )) ) ] `2 ) by L197 , MCART_1:7
.= ( Hom (( cod R5 ) , ( cod C17 )) );
L200: ( dom D29 ) = ( ( fDom ( Hom R2 ) ) . D29 ) by L193
.= ( dom D30 ) by ENS_1:def 9
.= ( ( D29 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C16) ) , ( Hom (( dom R5 ) , C16) ) ] `1 ) by L192 , MCART_1:7
.= ( Hom (( cod R5 ) , C16) );
L201: ( cod D31 ) = ( dom D29 ) by L200 , L131 , L199 , CAT_1:5;
reconsider D33 = ( D21 /. C17 ) as (Morphism of ( EnsHom R2 ));
L202: D33 = ( ( hom?- ( dom R5 ) ) . C17 ) by L131 , CAT_3:def 10
.= [ [ ( Hom (( dom R5 ) , ( dom C17 )) ) , ( Hom (( dom R5 ) , ( cod C17 )) ) ] , ( hom (( dom R5 ) , C17) ) ] by ENS_1:def 21;
reconsider D34 = D33 as (Element of ( Maps ( Hom R2 ) )) by L202 , ENS_1:47;
L203: ( cod D33 ) = ( ( fCod ( Hom R2 ) ) . D33 ) by L193
.= ( cod D34 ) by ENS_1:def 10
.= ( ( D33 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( dom R5 ) , ( dom C17 )) ) , ( Hom (( dom R5 ) , ( cod C17 )) ) ] `2 ) by L202 , MCART_1:7
.= ( Hom (( dom R5 ) , ( cod C17 )) );
L204: ( dom D33 ) = ( ( fDom ( Hom R2 ) ) . D33 ) by L193
.= ( dom D34 ) by ENS_1:def 9
.= ( ( D33 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( dom R5 ) , ( dom C17 )) ) , ( Hom (( dom R5 ) , ( cod C17 )) ) ] `1 ) by L202 , MCART_1:7
.= ( Hom (( dom R5 ) , ( dom C17 )) );
L205: ( cod D27 ) = ( dom D33 ) by L204 , L131 , L196 , CAT_1:5;
L206: ( Hom (( D20 . C16 ) , ( D21 . C16 )) ) <> ( {} ) by L114;
L207: ( ( D24 . C16 ) * ( D20 /. C17 ) ) = ( D29 (*) D31 ) by L206 , L132 , CAT_1:def 13
.= [ [ ( Hom (( cod R5 ) , ( dom C17 )) ) , ( Hom (( dom R5 ) , C16) ) ] , ( ( hom (R5 , C16) ) * ( hom (( cod R5 ) , C17) ) ) ] by L192 , L200 , L194 , L197 , L198 , L199 , L201 , L2
.= [ [ ( Hom (( cod R5 ) , C15) ) , ( Hom (( dom R5 ) , ( cod C17 )) ) ] , ( ( hom (( dom R5 ) , C17) ) * ( hom (R5 , C15) ) ) ] by L133 , L189 , L155 , L165 , FUNCT_1:2
.= ( D33 (*) D27 ) by L202 , L204 , L203 , L190 , L195 , L196 , L205 , L2
.= ( ( D21 /. C17 ) * ( D24 . C15 ) ) by L188 , L191 , CAT_1:def 13;
thus L208: thesis by L207;
end;
L209: D20 is_naturally_transformable_to D21 by L18;
reconsider D35 = D24 as (natural_transformation of D20 , D21) by L209 , L130 , NATTRA_1:def 8;
L210: (for B25 being (Element of R2) holds ( D35 . B25 ) = [ [ ( Hom (( cod R5 ) , B25) ) , ( Hom (( dom R5 ) , B25) ) ] , ( hom (R5 , ( id B25 )) ) ])
proof
let R4 being (Object of R2);
L211: ( D35 . R4 ) = ( (D35 qua Function) . R4 ) by L129 , NATTRA_1:def 5
.= [ [ ( Hom (( cod R5 ) , R4) ) , ( Hom (( dom R5 ) , R4) ) ] , ( hom (R5 , ( id R4 )) ) ] by L123;
thus L212: thesis by L211;
end;
thus L213: thesis by L210;
end;
uniqueness
proof
L214: (for B26 being (Object of R2) holds [ [ ( Hom (( cod R5 ) , B26) ) , ( Hom (( dom R5 ) , B26) ) ] , ( hom (R5 , B26) ) ] in ( Hom (( <| ( cod R5 ) ,?> . B26 ) , ( <| ( dom R5 ) ,?> . B26 )) ))
proof
let C21 being (Object of R2);
L215: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D36 = [ [ ( Hom (( cod R5 ) , C21) ) , ( Hom (( dom R5 ) , C21) ) ] , ( hom (R5 , C21) ) ] as (Morphism of ( EnsHom R2 )) by L215 , ENS_1:48;
reconsider D37 = D36 as (Element of ( Maps ( Hom R2 ) )) by ENS_1:48;
L216: ( cod D36 ) = ( ( fCod ( Hom R2 ) ) . D36 ) by L215
.= ( cod D37 ) by ENS_1:def 10
.= ( ( D36 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod R5 ) , C21) ) , ( Hom (( dom R5 ) , C21) ) ] `2 ) by MCART_1:7
.= ( Hom (( dom R5 ) , C21) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( dom R5 )) ) ) . C21 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( dom R5 )) ) . C21 )
.= ( <| ( dom R5 ) ,?> . C21 ) by ENS_1:def 25;
L217: ( dom D36 ) = ( ( fDom ( Hom R2 ) ) . D36 ) by L215
.= ( dom D37 ) by ENS_1:def 9
.= ( ( D36 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod R5 ) , C21) ) , ( Hom (( dom R5 ) , C21) ) ] `1 ) by MCART_1:7
.= ( Hom (( cod R5 ) , C21) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( cod R5 )) ) ) . C21 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( cod R5 )) ) . C21 )
.= ( <| ( cod R5 ) ,?> . C21 ) by ENS_1:def 25;
thus L218: thesis by L217 , L216;
end;
L219: (for B27 being (Object of R2) holds ( Hom (( <| ( cod R5 ) ,?> . B27 ) , ( <| ( dom R5 ) ,?> . B27 )) ) <> ( {} )) by L214;
L220: <| ( cod R5 ) ,?> is_transformable_to <| ( dom R5 ) ,?> by L219 , NATTRA_1:def 2;
let C22 , C23 being (natural_transformation of <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?>);
assume that
L221: (for B28 being (Object of R2) holds ( C22 . B28 ) = [ [ ( Hom (( cod R5 ) , B28) ) , ( Hom (( dom R5 ) , B28) ) ] , ( hom (R5 , ( id B28 )) ) ])
and
L222: (for B29 being (Object of R2) holds ( C23 . B29 ) = [ [ ( Hom (( cod R5 ) , B29) ) , ( Hom (( dom R5 ) , B29) ) ] , ( hom (R5 , ( id B29 )) ) ]);
L223:
now
let R4 being (Object of R2);
thus L224: ( C22 . R4 ) = [ [ ( Hom (( cod R5 ) , R4) ) , ( Hom (( dom R5 ) , R4) ) ] , ( hom (R5 , ( id R4 )) ) ] by L221
.= ( C23 . R4 ) by L222;
end;
thus L225: thesis by L223 , L220 , NATTRA_1:19;
end;
end;
theorem
L227: (for R2 being Category holds (for B30 being (Element of (the carrier' of R2)) holds [ [ <| ( cod B30 ) ,?> , <| ( dom B30 ) ,?> ] , <| B30 ,?> ] is (Element of (the carrier' of ( Functors (R2 , ( EnsHom R2 )) )))))
proof
let R2 being Category;
let C24 being (Element of (the carrier' of R2));
L228: <| ( cod C24 ) ,?> is_naturally_transformable_to <| ( dom C24 ) ,?> by L18;
L229: [ [ <| ( cod C24 ) ,?> , <| ( dom C24 ) ,?> ] , <| C24 ,?> ] in ( NatTrans (R2 , ( EnsHom R2 )) ) by L228 , NATTRA_1:def 16;
thus L230: thesis by L229 , NATTRA_1:def 17;
end;
definition
let R2 being Category;
func Yoneda R2 -> (Contravariant_Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) )) means 
:L231: (for B31 being (Morphism of R2) holds ( it . B31 ) = [ [ <| ( cod B31 ) ,?> , <| ( dom B31 ) ,?> ] , <| B31 ,?> ]);
existence
proof
deffunc H3((Element of (the carrier' of R2))) = [ [ <| ( cod $1 ) ,?> , <| ( dom $1 ) ,?> ] , <| $1 ,?> ];
L232: (for B32 being (Element of (the carrier' of R2)) holds H3(B32) in (the carrier' of ( Functors (R2 , ( EnsHom R2 )) )))
proof
let R5 being (Morphism of R2);
L233: [ [ <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?> ] , <| R5 ,?> ] is (Morphism of ( Functors (R2 , ( EnsHom R2 )) )) by L227;
thus L234: thesis by L233;
end;
consider C25 being (Function of (the carrier' of R2) , (the carrier' of ( Functors (R2 , ( EnsHom R2 )) ))) such that L235: (for B33 being (Element of (the carrier' of R2)) holds ( C25 . B33 ) = H3(B33)) from FUNCT_2:sch 8(L232);
L236: (for B34 , B35 being (Morphism of R2) holds (( dom B35 ) = ( cod B34 ) implies ( C25 . ( B35 (*) B34 ) ) = ( ( C25 . B34 ) (*) ( C25 . B35 ) )))
proof
let C26 , C27 being (Morphism of R2);
reconsider D38 = <| C27 ,?> as (natural_transformation of <| ( cod C27 ) ,?> , <| ( dom C27 ) ,?>);
assume L237: ( dom C27 ) = ( cod C26 );
reconsider D39 = <| C26 ,?> as (natural_transformation of <| ( dom C27 ) ,?> , <| ( dom C26 ) ,?>) by L237;
L238: ( C25 . C27 ) = [ [ <| ( cod C27 ) ,?> , <| ( dom C27 ) ,?> ] , D38 ] by L235;
L239: ( dom ( C27 (*) C26 ) ) = ( dom C26 ) by L237 , CAT_1:17;
reconsider D40 = ( D39 `*` D38 ) as (natural_transformation of <| ( cod ( C27 (*) C26 ) ) ,?> , <| ( dom ( C27 (*) C26 ) ) ,?>) by L239 , L237 , CAT_1:17;
L240: ( cod ( C27 (*) C26 ) ) = ( cod C27 ) by L237 , CAT_1:17;
L241: (for B36 being (Object of R2) holds ( <| ( C27 (*) C26 ) ,?> . B36 ) = ( D40 . B36 ))
proof
set D41 = <| ( cod C26 ) ,?>;
set D42 = <| ( dom C26 ) ,?>;
let C28 being (Object of R2);
reconsider D43 = ( D39 . C28 ) as (Morphism of ( EnsHom R2 ));
reconsider D44 = ( D38 . C28 ) as (Morphism of ( EnsHom R2 ));
L242: D44 = [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C27 ) , C28) ) ] , ( hom (C27 , ( id C28 )) ) ] by L113;
L243: (for B37 being (Object of R2) holds [ [ ( Hom (( cod C27 ) , B37) ) , ( Hom (( dom C27 ) , B37) ) ] , ( hom (C27 , B37) ) ] in ( Hom (( <| ( cod C27 ) ,?> . B37 ) , ( <| ( dom C27 ) ,?> . B37 )) ))
proof
let C29 being (Object of R2);
L244: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D45 = [ [ ( Hom (( cod C27 ) , C29) ) , ( Hom (( dom C27 ) , C29) ) ] , ( hom (C27 , C29) ) ] as (Morphism of ( EnsHom R2 )) by L244 , ENS_1:48;
reconsider D46 = D45 as (Element of ( Maps ( Hom R2 ) )) by ENS_1:48;
L245: ( cod D45 ) = ( ( fCod ( Hom R2 ) ) . D45 ) by L244
.= ( cod D46 ) by ENS_1:def 10
.= ( ( D45 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod C27 ) , C29) ) , ( Hom (( dom C27 ) , C29) ) ] `2 ) by MCART_1:7
.= ( Hom (( dom C27 ) , C29) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( dom C27 )) ) ) . C29 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( dom C27 )) ) . C29 )
.= ( <| ( dom C27 ) ,?> . C29 ) by ENS_1:def 25;
L246: ( dom D45 ) = ( ( fDom ( Hom R2 ) ) . D45 ) by L244
.= ( dom D46 ) by ENS_1:def 9
.= ( ( D45 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod C27 ) , C29) ) , ( Hom (( dom C27 ) , C29) ) ] `1 ) by MCART_1:7
.= ( Hom (( cod C27 ) , C29) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( cod C27 )) ) ) . C29 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( cod C27 )) ) . C29 )
.= ( <| ( cod C27 ) ,?> . C29 ) by ENS_1:def 25;
thus L247: thesis by L246 , L245;
end;
L248: ( Hom (( <| ( cod C27 ) ,?> . C28 ) , ( <| ( dom C27 ) ,?> . C28 )) ) <> ( {} ) by L243;
L249: (for B38 being (Object of R2) holds [ [ ( Hom (( cod C26 ) , B38) ) , ( Hom (( dom C26 ) , B38) ) ] , ( hom (C26 , B38) ) ] in ( Hom (( D41 . B38 ) , ( D42 . B38 )) ))
proof
let C30 being (Object of R2);
L250: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D47 = [ [ ( Hom (( cod C26 ) , C30) ) , ( Hom (( dom C26 ) , C30) ) ] , ( hom (C26 , C30) ) ] as (Morphism of ( EnsHom R2 )) by L250 , ENS_1:48;
reconsider D48 = D47 as (Element of ( Maps ( Hom R2 ) )) by ENS_1:48;
L251: ( cod D47 ) = ( ( fCod ( Hom R2 ) ) . D47 ) by L250
.= ( cod D48 ) by ENS_1:def 10
.= ( ( D47 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod C26 ) , C30) ) , ( Hom (( dom C26 ) , C30) ) ] `2 ) by MCART_1:7
.= ( Hom (( dom C26 ) , C30) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( dom C26 )) ) ) . C30 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( dom C26 )) ) . C30 )
.= ( D42 . C30 ) by ENS_1:def 25;
L252: ( dom D47 ) = ( ( fDom ( Hom R2 ) ) . D47 ) by L250
.= ( dom D48 ) by ENS_1:def 9
.= ( ( D47 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod C26 ) , C30) ) , ( Hom (( dom C26 ) , C30) ) ] `1 ) by MCART_1:7
.= ( Hom (( cod C26 ) , C30) )
.= ( ( Obj ( hom?- (( Hom R2 ) , ( cod C26 )) ) ) . C30 ) by ENS_1:60
.= ( ( hom?- (( Hom R2 ) , ( cod C26 )) ) . C30 )
.= ( D41 . C30 ) by ENS_1:def 25;
thus L253: thesis by L252 , L251;
end;
L254: ( Hom (( D41 . C28 ) , ( D42 . C28 )) ) <> ( {} ) by L249;
L255: ( <| ( C27 (*) C26 ) ,?> . C28 ) = [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom ( C27 (*) C26 ) ) , C28) ) ] , ( hom (( C27 (*) C26 ) , ( id C28 )) ) ] by L240 , L113
.= [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] , ( hom (( C27 (*) C26 ) , C28) ) ] by L239 , ENS_1:53;
L256: ( D39 . C28 ) = [ [ ( Hom (( cod C26 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] , ( hom (C26 , ( id C28 )) ) ] by L237 , L113;
L257: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D49 = D43 as (Element of ( Maps ( Hom R2 ) )) by L257;
reconsider D50 = D44 as (Element of ( Maps ( Hom R2 ) )) by L257;
L258: ( cod D44 ) = ( ( fCod ( Hom R2 ) ) . D44 ) by L257
.= ( cod D50 ) by ENS_1:def 10
.= ( ( D44 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C27 ) , C28) ) ] `2 ) by L242 , MCART_1:7
.= ( Hom (( dom C27 ) , C28) );
L259: ( cod D43 ) = ( ( fCod ( Hom R2 ) ) . D43 ) by L257
.= ( cod D49 ) by ENS_1:def 10
.= ( ( D43 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (( cod C26 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] `2 ) by L256 , MCART_1:7
.= ( Hom (( dom C26 ) , C28) );
L260: ( dom D43 ) = ( ( fDom ( Hom R2 ) ) . D43 ) by L257
.= ( dom D49 ) by ENS_1:def 9
.= ( ( D43 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod C26 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] `1 ) by L256 , MCART_1:7
.= ( Hom (( cod C26 ) , C28) );
L261: ( dom D44 ) = ( ( fDom ( Hom R2 ) ) . D44 ) by L257
.= ( dom D50 ) by ENS_1:def 9
.= ( ( D44 `1 ) `1 ) by ENS_1:def 3
.= ( [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C27 ) , C28) ) ] `1 ) by L242 , MCART_1:7
.= ( Hom (( cod C27 ) , C28) );
L262: (<| ( dom C27 ) ,?> is_naturally_transformable_to <| ( dom C26 ) ,?> & <| ( cod C27 ) ,?> is_naturally_transformable_to <| ( dom C27 ) ,?>) by L237 , L18;
L263: ( D40 . C28 ) = ( ( D39 . C28 ) * ( D38 . C28 ) ) by L262 , L239 , L240 , NATTRA_1:25
.= ( D43 (*) D44 ) by L237 , L254 , L248 , CAT_1:def 13
.= [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] , ( ( hom (C26 , ( id C28 )) ) * ( hom (C27 , ( id C28 )) ) ) ] by L237 , L256 , L242 , L260 , L258 , L261 , L259 , L2
.= [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] , ( ( hom (C26 , C28) ) * ( hom (C27 , ( id C28 )) ) ) ] by ENS_1:53
.= [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] , ( ( hom (C26 , C28) ) * ( hom (C27 , C28) ) ) ] by ENS_1:53
.= [ [ ( Hom (( cod C27 ) , C28) ) , ( Hom (( dom C26 ) , C28) ) ] , ( hom (( C27 (*) C26 ) , C28) ) ] by L237 , ENS_1:46;
thus L264: thesis by L263 , L255;
end;
L265: <| ( C27 (*) C26 ) ,?> = D40 by L241 , L18 , ISOCAT_1:26;
L266: ( C25 . C26 ) = [ [ <| ( dom C27 ) ,?> , <| ( dom C26 ) ,?> ] , D39 ] by L235 , L237;
L267: [ ( C25 . C26 ) , ( C25 . C27 ) ] in ( dom (the Comp of ( Functors (R2 , ( EnsHom R2 )) )) ) by L266 , L238 , NATTRA_1:35;
consider C31 , C32 , C33 being (Functor of R2 , ( EnsHom R2 )), C34 being (natural_transformation of C31 , C32), C35 being (natural_transformation of C32 , C33) such that L268: ( C25 . C27 ) = [ [ C31 , C32 ] , C34 ] and L269: ( C25 . C26 ) = [ [ C32 , C33 ] , C35 ] and L270: ( (the Comp of ( Functors (R2 , ( EnsHom R2 )) )) . (( C25 . C26 ) , ( C25 . C27 )) ) = [ [ C31 , C33 ] , ( C35 `*` C34 ) ] by L267 , NATTRA_1:def 17;
L271: <| C26 ,?> = C35 by L266 , L269 , XTUPLE_0:1;
L272: [ C32 , C33 ] = [ <| ( dom C27 ) ,?> , <| ( dom C26 ) ,?> ] by L266 , L269 , XTUPLE_0:1;
L273: <| ( dom C26 ) ,?> = C33 by L272 , XTUPLE_0:1;
L274: [ C31 , C32 ] = [ <| ( cod C27 ) ,?> , <| ( dom C27 ) ,?> ] by L238 , L268 , XTUPLE_0:1;
L275: (<| ( cod C27 ) ,?> = C31 & <| ( dom C27 ) ,?> = C32) by L274 , XTUPLE_0:1;
L276: <| C27 ,?> = C34 by L238 , L268 , XTUPLE_0:1;
L277: ( ( C25 . C26 ) (*) ( C25 . C27 ) ) = [ [ <| ( cod C27 ) ,?> , <| ( dom C26 ) ,?> ] , ( D39 `*` D38 ) ] by L276 , L267 , L270 , L271 , L275 , L273 , CAT_1:def 1;
thus L278: thesis by L277 , L235 , L239 , L240 , L265;
end;
L279: (for B39 being (Morphism of R2) holds (( C25 . ( id ( dom B39 ) ) ) = ( id ( cod ( C25 . B39 ) ) ) & ( C25 . ( id ( cod B39 ) ) ) = ( id ( dom ( C25 . B39 ) ) )))
proof
let R5 being (Morphism of R2);
set D51 = ( C25 . R5 );
set D52 = ( dom <| ( id ( dom R5 ) ) ,?> );
L280: ( dom <| ( id ( dom R5 ) ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| ( dom R5 ) ,?> ) ) by FUNCT_2:def 1;
L281: ( C25 . ( id ( dom R5 ) ) ) = [ [ <| ( cod ( id ( dom R5 ) ) ) ,?> , <| ( dom ( id ( dom R5 ) ) ) ,?> ] , <| ( id ( dom R5 ) ) ,?> ] by L235
.= [ [ <| ( dom R5 ) ,?> , <| ( dom ( id ( dom R5 ) ) ) ,?> ] , <| ( id ( dom R5 ) ) ,?> ] by CAT_1:58
.= [ [ <| ( dom R5 ) ,?> , <| ( dom R5 ) ,?> ] , <| ( id ( dom R5 ) ) ,?> ] by CAT_1:58;
L282: D51 = [ [ <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?> ] , <| R5 ,?> ] by L235;
L283: ( cod D51 ) = <| ( dom R5 ) ,?> by L282 , NATTRA_1:33;
L284: [ [ <| ( dom R5 ) ,?> , <| ( dom R5 ) ,?> ] , ( id <| ( dom R5 ) ,?> ) ] = ( id ( cod ( C25 . R5 ) ) ) by L283 , NATTRA_1:def 17;
L285: (for R1 being set holds (R1 in D52 implies ( <| ( id ( dom R5 ) ) ,?> . R1 ) = ( ( id <| ( dom R5 ) ,?> ) . R1 )))
proof
let R1 being set;
assume L286: R1 in D52;
reconsider D53 = R1 as (Object of R2) by L286 , FUNCT_2:def 1;
reconsider D54 = ( id D53 ) as (Morphism of D53 , D53);
L287: ( Hom (D53 , D53) ) <> ( {} );
L288: <| ( cod ( id ( dom R5 ) ) ) ,?> is_transformable_to <| ( dom ( id ( dom R5 ) ) ) ,?>;
L289: ( <| ( id ( dom R5 ) ) ,?> . D53 ) = [ [ ( Hom (( cod ( id ( dom R5 ) ) ) , D53) ) , ( Hom (( dom ( id ( dom R5 ) ) ) , D53) ) ] , ( hom (( id ( dom R5 ) ) , ( id D53 )) ) ] by L113
.= [ [ ( Hom (( dom R5 ) , D53) ) , ( Hom (( dom ( id ( dom R5 ) ) ) , D53) ) ] , ( hom (( id ( dom R5 ) ) , ( id D53 )) ) ]
.= [ [ ( Hom (( dom R5 ) , D53) ) , ( Hom (( dom R5 ) , D53) ) ] , ( hom (( id ( dom R5 ) ) , ( id D53 )) ) ]
.= [ [ ( Hom (( dom R5 ) , D53) ) , ( Hom (( dom R5 ) , D53) ) ] , ( hom (( dom R5 ) , ( id D53 )) ) ] by ENS_1:53
.= [ [ ( Hom (( dom R5 ) , D53) ) , ( Hom (( dom R5 ) , ( cod ( id D53 ) )) ) ] , ( hom (( dom R5 ) , ( id D53 )) ) ]
.= [ [ ( Hom (( dom R5 ) , ( dom ( id D53 ) )) ) , ( Hom (( dom R5 ) , ( cod ( id D53 ) )) ) ] , ( hom (( dom R5 ) , ( id D53 )) ) ]
.= ( (<| ( dom R5 ) ,?> qua Function) . ( id D53 ) ) by ENS_1:def 21
.= ( <| ( dom R5 ) ,?> /. D54 ) by L287 , CAT_3:def 10
.= ( id ( <| ( dom R5 ) ,?> . D53 ) ) by NATTRA_1:15
.= ( ( id <| ( dom R5 ) ,?> ) . D53 ) by NATTRA_1:20
.= ( (( id <| ( dom R5 ) ,?> ) qua Function) . D53 ) by NATTRA_1:def 5;
thus L290: thesis by L289 , L288 , NATTRA_1:def 5;
end;
set D55 = ( dom <| ( id ( cod R5 ) ) ,?> );
L291: (for R1 being set holds (R1 in D55 implies ( <| ( id ( cod R5 ) ) ,?> . R1 ) = ( ( id <| ( cod R5 ) ,?> ) . R1 )))
proof
let R1 being set;
assume L292: R1 in D55;
reconsider D56 = R1 as (Object of R2) by L292 , FUNCT_2:def 1;
L293: ( Hom (D56 , D56) ) <> ( {} );
L294: <| ( cod ( id ( cod R5 ) ) ) ,?> is_transformable_to <| ( dom ( id ( cod R5 ) ) ) ,?>;
L295: ( <| ( id ( cod R5 ) ) ,?> . D56 ) = [ [ ( Hom (( cod ( id ( cod R5 ) ) ) , D56) ) , ( Hom (( dom ( id ( cod R5 ) ) ) , D56) ) ] , ( hom (( id ( cod R5 ) ) , ( id D56 )) ) ] by L113
.= [ [ ( Hom (( cod R5 ) , D56) ) , ( Hom (( dom ( id ( cod R5 ) ) ) , D56) ) ] , ( hom (( id ( cod R5 ) ) , ( id D56 )) ) ]
.= [ [ ( Hom (( cod R5 ) , D56) ) , ( Hom (( cod R5 ) , D56) ) ] , ( hom (( id ( cod R5 ) ) , ( id D56 )) ) ]
.= [ [ ( Hom (( cod R5 ) , D56) ) , ( Hom (( cod R5 ) , D56) ) ] , ( hom (( cod R5 ) , ( id D56 )) ) ] by ENS_1:53
.= [ [ ( Hom (( cod R5 ) , D56) ) , ( Hom (( cod R5 ) , ( cod ( id D56 ) )) ) ] , ( hom (( cod R5 ) , ( id D56 )) ) ]
.= [ [ ( Hom (( cod R5 ) , ( dom ( id D56 ) )) ) , ( Hom (( cod R5 ) , ( cod ( id D56 ) )) ) ] , ( hom (( cod R5 ) , ( id D56 )) ) ]
.= ( (<| ( cod R5 ) ,?> qua Function) . ( id D56 ) ) by ENS_1:def 21
.= ( <| ( cod R5 ) ,?> /. ( id D56 ) ) by L293 , CAT_3:def 10
.= ( id ( <| ( cod R5 ) ,?> . D56 ) ) by NATTRA_1:15
.= ( ( id <| ( cod R5 ) ,?> ) . D56 ) by NATTRA_1:20
.= ( (( id <| ( cod R5 ) ,?> ) qua Function) . D56 ) by NATTRA_1:def 5;
thus L296: thesis by L295 , L294 , NATTRA_1:def 5;
end;
L297: ( dom <| ( id ( cod R5 ) ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| ( cod R5 ) ,?> ) ) by FUNCT_2:def 1;
L298: <| ( id ( cod R5 ) ) ,?> = ( id <| ( cod R5 ) ,?> ) by L297 , L291 , FUNCT_1:2;
L299: ( C25 . ( id ( cod R5 ) ) ) = [ [ <| ( cod ( id ( cod R5 ) ) ) ,?> , <| ( dom ( id ( cod R5 ) ) ) ,?> ] , <| ( id ( cod R5 ) ) ,?> ] by L235
.= [ [ <| ( cod R5 ) ,?> , <| ( dom ( id ( cod R5 ) ) ) ,?> ] , <| ( id ( cod R5 ) ) ,?> ] by CAT_1:58
.= [ [ <| ( cod R5 ) ,?> , <| ( cod R5 ) ,?> ] , <| ( id ( cod R5 ) ) ,?> ] by CAT_1:58;
L300: ( dom D51 ) = <| ( cod R5 ) ,?> by L282 , NATTRA_1:33;
thus L301: thesis by L300 , L281 , L284 , L280 , L285 , L299 , L298 , FUNCT_1:2 , NATTRA_1:def 17;
end;
L302: (for B40 being (Object of R2) holds (ex B41 being (Object of ( Functors (R2 , ( EnsHom R2 )) )) st ( C25 . ( id B40 ) ) = ( id B41 )))
proof
let C36 being (Object of R2);
set D57 = ( dom <| ( id C36 ) ,?> );
L303: <| C36 ,?> in ( Funct (R2 , ( EnsHom R2 )) ) by CAT_2:def 2;
reconsider D58 = <| C36 ,?> as (Object of ( Functors (R2 , ( EnsHom R2 )) )) by L303 , NATTRA_1:def 17;
take D58;
L304: (for R1 being set holds (R1 in D57 implies ( <| ( id C36 ) ,?> . R1 ) = ( ( id <| C36 ,?> ) . R1 )))
proof
let R1 being set;
assume L305: R1 in D57;
reconsider D59 = R1 as (Object of R2) by L305 , FUNCT_2:def 1;
reconsider D60 = ( id D59 ) as (Morphism of D59 , D59);
L306: ( Hom (D59 , D59) ) <> ( {} );
L307: <| ( cod ( id C36 ) ) ,?> is_transformable_to <| ( dom ( id C36 ) ) ,?>;
L308: ( <| ( id C36 ) ,?> . D59 ) = [ [ ( Hom (( cod ( id C36 ) ) , D59) ) , ( Hom (( dom ( id C36 ) ) , D59) ) ] , ( hom (( id C36 ) , ( id D59 )) ) ] by L113
.= [ [ ( Hom (C36 , D59) ) , ( Hom (( dom ( id C36 ) ) , D59) ) ] , ( hom (( id C36 ) , ( id D59 )) ) ]
.= [ [ ( Hom (C36 , D59) ) , ( Hom (C36 , D59) ) ] , ( hom (( id C36 ) , ( id D59 )) ) ]
.= [ [ ( Hom (C36 , D59) ) , ( Hom (C36 , D59) ) ] , ( hom (C36 , ( id D59 )) ) ] by ENS_1:53
.= [ [ ( Hom (C36 , D59) ) , ( Hom (C36 , ( cod ( id D59 ) )) ) ] , ( hom (C36 , ( id D59 )) ) ]
.= [ [ ( Hom (C36 , ( dom ( id D59 ) )) ) , ( Hom (C36 , ( cod ( id D59 ) )) ) ] , ( hom (C36 , ( id D59 )) ) ]
.= ( (<| C36 ,?> qua Function) . ( id D59 ) ) by ENS_1:def 21
.= ( <| C36 ,?> /. D60 ) by L306 , CAT_3:def 10
.= ( id ( <| C36 ,?> . D59 ) ) by NATTRA_1:15
.= ( ( id <| C36 ,?> ) . D59 ) by NATTRA_1:20
.= ( (( id <| C36 ,?> ) qua Function) . D59 ) by NATTRA_1:def 5;
thus L309: thesis by L308 , L307 , NATTRA_1:def 5;
end;
L310: ( dom <| ( id C36 ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| C36 ,?> ) ) by FUNCT_2:def 1;
L311: <| ( id C36 ) ,?> = ( id <| C36 ,?> ) by L310 , L304 , FUNCT_1:2;
L312: ( C25 . ( id C36 ) ) = [ [ <| ( cod ( id C36 ) ) ,?> , <| ( dom ( id C36 ) ) ,?> ] , <| ( id C36 ) ,?> ] by L235
.= [ [ <| C36 ,?> , <| ( dom ( id C36 ) ) ,?> ] , <| ( id C36 ) ,?> ] by CAT_1:58
.= [ [ <| C36 ,?> , <| C36 ,?> ] , ( id <| C36 ,?> ) ] by L311 , CAT_1:58
.= ( id D58 ) by NATTRA_1:def 17;
thus L313: thesis by L312;
end;
reconsider D61 = C25 as (Contravariant_Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) )) by L302 , L279 , L236 , OPPCAT_1:def 9;
L314: (for B42 being (Element of (the carrier' of R2)) holds ( D61 . B42 ) = [ [ <| ( cod B42 ) ,?> , <| ( dom B42 ) ,?> ] , <| B42 ,?> ]) by L235;
thus L315: thesis by L314;
end;
uniqueness
proof
let C37 , C38 being (Contravariant_Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) ));
assume that
L316: (for R5 being (Morphism of R2) holds ( C37 . R5 ) = [ [ <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?> ] , <| R5 ,?> ])
and
L317: (for R5 being (Morphism of R2) holds ( C38 . R5 ) = [ [ <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?> ] , <| R5 ,?> ]);
L318:
now
let R5 being (Morphism of R2);
thus L319: ( C37 . R5 ) = [ [ <| ( cod R5 ) ,?> , <| ( dom R5 ) ,?> ] , <| R5 ,?> ] by L316
.= ( C38 . R5 ) by L317;
end;
thus L320: thesis by L318 , FUNCT_2:63;
end;
end;
definition
let C39 , C40 being Category;
let C41 being (Contravariant_Functor of C39 , C40);
let C42 being (Object of C39);
func C41 . C42 -> (Object of C40) equals 
( ( Obj C41 ) . C42 );
correctness;
end;
theorem
L323: (for R2 being Category holds (for B43 being (Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) )) holds ((( Obj B43 ) is  one-to-one & B43 is  faithful) implies B43 is  one-to-one)))
proof
let R2 being Category;
let C43 being (Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) ));
assume L324: ( Obj C43 ) is  one-to-one;
assume L325: C43 is  faithful;
L326: (for B44 , B45 being set holds ((B44 in ( dom C43 ) & B45 in ( dom C43 ) & ( C43 . B44 ) = ( C43 . B45 )) implies B44 = B45))
proof
let C44 , C45 being set;
assume that
L327: (C44 in ( dom C43 ) & C45 in ( dom C43 ))
and
L328: ( C43 . C44 ) = ( C43 . C45 );
reconsider D62 = C44 , D63 = C45 as (Morphism of R2) by L327 , FUNCT_2:def 1;
set D64 = ( dom D62 );
set D65 = ( cod D62 );
set D66 = ( dom D63 );
set D67 = ( cod D63 );
reconsider D68 = D62 as (Morphism of D64 , D65) by CAT_1:4;
reconsider D69 = D63 as (Morphism of D66 , D67) by CAT_1:4;
L329: ( Hom (D64 , D65) ) <> ( {} ) by CAT_1:2;
L330: ( Hom (( C43 . D64 ) , ( C43 . D65 )) ) <> ( {} ) by L329 , CAT_1:84;
L331: ( Hom (D66 , D67) ) <> ( {} ) by CAT_1:2;
L332: ( Hom (( C43 . D66 ) , ( C43 . D67 )) ) <> ( {} ) by L331 , CAT_1:84;
L333: ( C43 /. D68 ) = ( C43 . D63 ) by L328 , L329 , CAT_3:def 10
.= ( C43 /. D69 ) by L331 , CAT_3:def 10;
L334: ( ( Obj C43 ) . D64 ) = ( C43 . D64 )
.= ( dom ( C43 /. D69 ) ) by L333 , L330 , CAT_1:5
.= ( ( Obj C43 ) . D66 ) by L332 , CAT_1:5;
L335: (D63 is (Morphism of ( dom D63 ) , ( cod D63 )) & D64 = D66) by L334 , L324 , CAT_1:4 , FUNCT_2:19;
L336: ( ( Obj C43 ) . D65 ) = ( C43 . D65 )
.= ( cod ( C43 /. D69 ) ) by L333 , L330 , CAT_1:5
.= ( ( Obj C43 ) . D67 ) by L332 , CAT_1:5;
L337: (D62 is (Morphism of ( dom D62 ) , ( cod D62 )) & D63 is (Morphism of D64 , D65)) by L336 , L324 , L335 , CAT_1:4 , FUNCT_2:19;
thus L338: thesis by L337 , L325 , L328 , L329 , CAT_1:def 27;
end;
thus L339: thesis by L326 , FUNCT_1:def 4;
end;
definition
let C46 , C47 being Category;
let C48 being (Contravariant_Functor of C46 , C47);
attr C48 is  faithful
means
:L340: (for B46 , B47 being (Object of C46) holds (( Hom (B46 , B47) ) <> ( {} ) implies (for B48 , B49 being (Morphism of B46 , B47) holds (( C48 . B48 ) = ( C48 . B49 ) implies B48 = B49))));
end;
theorem
L342: (for R2 being Category holds (for B50 being (Contravariant_Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) )) holds ((( Obj B50 ) is  one-to-one & B50 is  faithful) implies B50 is  one-to-one)))
proof
let R2 being Category;
let C49 being (Contravariant_Functor of R2 , ( Functors (R2 , ( EnsHom R2 )) ));
assume L343: ( Obj C49 ) is  one-to-one;
assume L344: C49 is  faithful;
L345: (for B51 , B52 being set holds ((B51 in ( dom C49 ) & B52 in ( dom C49 ) & ( C49 . B51 ) = ( C49 . B52 )) implies B51 = B52))
proof
let C50 , C51 being set;
assume that
L346: (C50 in ( dom C49 ) & C51 in ( dom C49 ))
and
L347: ( C49 . C50 ) = ( C49 . C51 );
reconsider D70 = C50 , D71 = C51 as (Morphism of R2) by L346 , FUNCT_2:def 1;
set D72 = ( dom D70 );
set D73 = ( cod D70 );
set D74 = ( dom D71 );
set D75 = ( cod D71 );
reconsider D76 = D71 as (Morphism of D74 , D75) by CAT_1:4;
L348: ( ( Obj C49 ) . D72 ) = ( cod ( C49 . D76 ) ) by L347 , OPPCAT_1:32
.= ( ( Obj C49 ) . D74 ) by OPPCAT_1:32;
L349: (D71 is (Morphism of ( dom D71 ) , ( cod D71 )) & D72 = D74) by L348 , L343 , CAT_1:4 , FUNCT_2:19;
L350: (D70 is (Morphism of ( dom D70 ) , ( cod D70 )) & ( Hom (D72 , D73) ) <> ( {} )) by CAT_1:2 , CAT_1:4;
L351: ( ( Obj C49 ) . D73 ) = ( dom ( C49 . D76 ) ) by L347 , OPPCAT_1:32
.= ( ( Obj C49 ) . D75 ) by OPPCAT_1:32;
L352: D71 is (Morphism of D72 , D73) by L351 , L343 , L349 , FUNCT_2:19;
thus L353: thesis by L352 , L344 , L347 , L350 , L340;
end;
thus L354: thesis by L345 , FUNCT_1:def 4;
end;
registration
let R2 being Category;
cluster ( Yoneda R2 ) ->  faithful;
coherence
proof
set D77 = ( Yoneda R2 );
L355: (for B53 , B54 being (Object of R2) holds (( Hom (B53 , B54) ) <> ( {} ) implies (for B55 , B56 being (Morphism of B53 , B54) holds (( D77 . B55 ) = ( D77 . B56 ) implies B55 = B56))))
proof
let C52 , C53 being (Object of R2);
assume L356: ( Hom (C52 , C53) ) <> ( {} );
let C54 , C55 being (Morphism of C52 , C53);
L357: C55 in ( Hom (C52 , C53) ) by L356 , CAT_1:def 5;
assume L358: ( D77 . C54 ) = ( D77 . C55 );
L359: [ [ <| ( cod C54 ) ,?> , <| ( dom C54 ) ,?> ] , <| C54 ,?> ] = ( D77 . C55 ) by L358 , L231;
L360: [ [ <| ( cod C54 ) ,?> , <| ( dom C54 ) ,?> ] , <| C54 ,?> ] = [ [ <| ( cod C55 ) ,?> , <| ( dom C55 ) ,?> ] , <| C55 ,?> ] by L359 , L231;
L361: [ <| ( cod C54 ) ,?> , <| ( dom C54 ) ,?> , <| C54 ,?> ] = [ [ <| ( cod C55 ) ,?> , <| ( dom C55 ) ,?> ] , <| C55 ,?> ] by L360;
L362: [ <| ( cod C54 ) ,?> , <| ( dom C54 ) ,?> , <| C54 ,?> ] = [ <| ( cod C55 ) ,?> , <| ( dom C55 ) ,?> , <| C55 ,?> ] by L361;
L363: <| C54 ,?> = <| C55 ,?> by L362 , XTUPLE_0:3;
L364: C54 in ( Hom (C52 , C53) ) by L356 , CAT_1:def 5;
L365: ( dom C54 ) = C52 by L364 , CAT_1:1
.= ( dom C55 ) by L357 , CAT_1:1;
L366: ( cod C54 ) = C53 by L364 , CAT_1:1
.= ( cod C55 ) by L357 , CAT_1:1;
L367: [ [ ( Hom (( cod C54 ) , C53) ) , ( Hom (( dom C54 ) , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = ( <| C55 ,?> . C53 ) by L366 , L365 , L363 , L113;
L368: [ [ ( Hom (( cod C54 ) , C53) ) , ( Hom (( dom C54 ) , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = [ [ ( Hom (( cod C55 ) , C53) ) , ( Hom (( dom C55 ) , C53) ) ] , ( hom (C55 , ( id C53 )) ) ] by L367 , L113;
L369: [ [ ( Hom (C53 , C53) ) , ( Hom (( dom C54 ) , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = [ [ ( Hom (( cod C55 ) , C53) ) , ( Hom (( dom C55 ) , C53) ) ] , ( hom (C55 , ( id C53 )) ) ] by L368 , L364 , CAT_1:1;
L370: [ [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = [ [ ( Hom (( cod C55 ) , C53) ) , ( Hom (( dom C55 ) , C53) ) ] , ( hom (C55 , ( id C53 )) ) ] by L369 , L364 , CAT_1:1;
L371: [ [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = [ [ ( Hom (C53 , C53) ) , ( Hom (( dom C55 ) , C53) ) ] , ( hom (C55 , ( id C53 )) ) ] by L370 , L357 , CAT_1:1;
L372: [ [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = [ [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) ] , ( hom (C55 , ( id C53 )) ) ] by L371 , L357 , CAT_1:1;
L373: [ [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) ] , ( hom (C54 , ( id C53 )) ) ] = [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) , ( hom (C55 , ( id C53 )) ) ] by L372;
L374: [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) , ( hom (C54 , ( id C53 )) ) ] = [ ( Hom (C53 , C53) ) , ( Hom (C52 , C53) ) , ( hom (C55 , ( id C53 )) ) ] by L373;
reconsider D78 = ( id C53 ) as (Morphism of R2);
L375: ( Hom (C53 , C53) ) <> ( {} );
L376: ( ( id C53 ) (*) D78 ) = ( ( id C53 ) * ( id C53 ) ) by L375 , CAT_1:def 13;
L377: ( id C53 ) in ( Hom (C53 , C53) ) by CAT_1:27;
L378: ( id C53 ) in ( Hom (( cod C55 ) , C53) ) by L377 , L357 , CAT_1:1;
L379: ( id C53 ) in ( Hom (( cod C55 ) , ( dom ( id C53 ) )) ) by L378;
L380: ( ( hom (C55 , ( id C53 )) ) . D78 ) = ( ( ( id C53 ) * ( id C53 ) ) (*) (C55 qua (Morphism of R2)) ) by L379 , L376 , ENS_1:def 23
.= ( ( id C53 ) (*) (C55 qua (Morphism of R2)) )
.= ( ( id C53 ) * C55 ) by L356 , L375 , CAT_1:def 13
.= C55 by L356 , CAT_1:28;
L381: ( id C53 ) in ( Hom (C53 , C53) ) by CAT_1:27;
L382: ( id C53 ) in ( Hom (( cod C54 ) , C53) ) by L381 , L364 , CAT_1:1;
L383: ( id C53 ) in ( Hom (( cod C54 ) , ( dom ( id C53 ) )) ) by L382;
L384: ( ( hom (C54 , ( id C53 )) ) . D78 ) = ( ( ( id C53 ) * ( id C53 ) ) (*) (C54 qua (Morphism of R2)) ) by L383 , L376 , ENS_1:def 23
.= ( ( id C53 ) (*) (C54 qua (Morphism of R2)) )
.= ( ( id C53 ) * C54 ) by L356 , L375 , CAT_1:def 13
.= C54 by L356 , CAT_1:28;
thus L385: thesis by L384 , L380 , L374 , XTUPLE_0:3;
end;
thus L386: thesis by L355 , L340;
end;
end;
registration
let R2 being Category;
cluster ( Yoneda R2 ) ->  one-to-one;
coherence
proof
set D79 = ( Yoneda R2 );
L388: (for B57 , B58 being set holds ((B57 in ( dom ( Obj D79 ) ) & B58 in ( dom ( Obj D79 ) ) & ( ( Obj D79 ) . B57 ) = ( ( Obj D79 ) . B58 )) implies B57 = B58))
proof
let C56 , C57 being set;
assume that
L389: (C56 in ( dom ( Obj D79 ) ) & C57 in ( dom ( Obj D79 ) ))
and
L390: ( ( Obj D79 ) . C56 ) = ( ( Obj D79 ) . C57 );
reconsider D80 = C56 , D81 = C57 as (Object of R2) by L389 , FUNCT_2:def 1;
reconsider D82 = ( id D81 ) as (Morphism of D81 , D81);
L391: ( Hom (D81 , D81) ) <> ( {} );
L392: <| D81 ,?> in ( Funct (R2 , ( EnsHom R2 )) ) by CAT_2:def 2;
reconsider D83 = <| D81 ,?> as (Object of ( Functors (R2 , ( EnsHom R2 )) )) by L392 , NATTRA_1:def 17;
L393: <| D80 ,?> in ( Funct (R2 , ( EnsHom R2 )) ) by CAT_2:def 2;
reconsider D84 = <| D80 ,?> as (Object of ( Functors (R2 , ( EnsHom R2 )) )) by L393 , NATTRA_1:def 17;
L394: ( D79 . ( id D81 ) ) = ( id D83 )
proof
set D85 = ( dom <| ( id D81 ) ,?> );
L395: (for R1 being set holds (R1 in D85 implies ( <| ( id D81 ) ,?> . R1 ) = ( ( id <| D81 ,?> ) . R1 )))
proof
let R1 being set;
assume L396: R1 in D85;
reconsider D86 = R1 as (Object of R2) by L396 , FUNCT_2:def 1;
reconsider D87 = ( id D86 ) as (Morphism of D86 , D86);
L397: ( Hom (D86 , D86) ) <> ( {} );
L398: <| ( cod ( id D81 ) ) ,?> is_transformable_to <| ( dom ( id D81 ) ) ,?>;
L399: ( <| ( id D81 ) ,?> . D86 ) = [ [ ( Hom (( cod ( id D81 ) ) , D86) ) , ( Hom (( dom ( id D81 ) ) , D86) ) ] , ( hom (( id D81 ) , ( id D86 )) ) ] by L113
.= [ [ ( Hom (D81 , D86) ) , ( Hom (( dom ( id D81 ) ) , D86) ) ] , ( hom (( id D81 ) , ( id D86 )) ) ]
.= [ [ ( Hom (D81 , D86) ) , ( Hom (D81 , D86) ) ] , ( hom (( id D81 ) , ( id D86 )) ) ]
.= [ [ ( Hom (D81 , D86) ) , ( Hom (D81 , D86) ) ] , ( hom (D81 , ( id D86 )) ) ] by ENS_1:53
.= [ [ ( Hom (D81 , D86) ) , ( Hom (D81 , ( cod ( id D86 ) )) ) ] , ( hom (D81 , ( id D86 )) ) ]
.= [ [ ( Hom (D81 , ( dom ( id D86 ) )) ) , ( Hom (D81 , ( cod ( id D86 ) )) ) ] , ( hom (D81 , ( id D86 )) ) ]
.= ( (<| D81 ,?> qua Function) . ( id D86 ) ) by ENS_1:def 21
.= ( <| D81 ,?> /. D87 ) by L397 , CAT_3:def 10
.= ( id ( <| D81 ,?> . D86 ) ) by NATTRA_1:15
.= ( ( id <| D81 ,?> ) . D86 ) by NATTRA_1:20
.= ( (( id <| D81 ,?> ) qua Function) . D86 ) by NATTRA_1:def 5;
thus L400: thesis by L399 , L398 , NATTRA_1:def 5;
end;
L401: ( dom <| ( id D81 ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| D81 ,?> ) ) by FUNCT_2:def 1;
L402: <| ( id D81 ) ,?> = ( id <| D81 ,?> ) by L401 , L395 , FUNCT_1:2;
L403: ( D79 . ( id D81 ) ) = [ [ <| ( cod ( id D81 ) ) ,?> , <| ( dom ( id D81 ) ) ,?> ] , <| ( id D81 ) ,?> ] by L231
.= [ [ <| D81 ,?> , <| ( dom ( id D81 ) ) ,?> ] , <| ( id D81 ) ,?> ] by CAT_1:58
.= [ [ <| D81 ,?> , <| D81 ,?> ] , ( id <| D81 ,?> ) ] by L402 , CAT_1:58
.= ( id D83 ) by NATTRA_1:def 17;
thus L404: thesis by L403;
end;
L405: ( ( Obj D79 ) . D81 ) = D83 by L394 , OPPCAT_1:30;
L406: ( D79 . ( id D80 ) ) = ( id D84 )
proof
set D88 = ( dom <| ( id D80 ) ,?> );
L407: (for R1 being set holds (R1 in D88 implies ( <| ( id D80 ) ,?> . R1 ) = ( ( id <| D80 ,?> ) . R1 )))
proof
let R1 being set;
assume L408: R1 in D88;
reconsider D89 = R1 as (Object of R2) by L408 , FUNCT_2:def 1;
reconsider D90 = ( id D89 ) as (Morphism of D89 , D89);
L409: ( Hom (D89 , D89) ) <> ( {} );
L410: <| ( cod ( id D80 ) ) ,?> is_transformable_to <| ( dom ( id D80 ) ) ,?>;
L411: ( <| ( id D80 ) ,?> . D89 ) = [ [ ( Hom (( cod ( id D80 ) ) , D89) ) , ( Hom (( dom ( id D80 ) ) , D89) ) ] , ( hom (( id D80 ) , ( id D89 )) ) ] by L113
.= [ [ ( Hom (D80 , D89) ) , ( Hom (( dom ( id D80 ) ) , D89) ) ] , ( hom (( id D80 ) , ( id D89 )) ) ]
.= [ [ ( Hom (D80 , D89) ) , ( Hom (D80 , D89) ) ] , ( hom (( id D80 ) , ( id D89 )) ) ]
.= [ [ ( Hom (D80 , D89) ) , ( Hom (D80 , D89) ) ] , ( hom (D80 , ( id D89 )) ) ] by ENS_1:53
.= [ [ ( Hom (D80 , D89) ) , ( Hom (D80 , ( cod ( id D89 ) )) ) ] , ( hom (D80 , ( id D89 )) ) ]
.= [ [ ( Hom (D80 , ( dom ( id D89 ) )) ) , ( Hom (D80 , ( cod ( id D89 ) )) ) ] , ( hom (D80 , ( id D89 )) ) ]
.= ( (<| D80 ,?> qua Function) . ( id D89 ) ) by ENS_1:def 21
.= ( <| D80 ,?> /. D90 ) by L409 , CAT_3:def 10
.= ( id ( <| D80 ,?> . D89 ) ) by NATTRA_1:15
.= ( ( id <| D80 ,?> ) . D89 ) by NATTRA_1:20
.= ( (( id <| D80 ,?> ) qua Function) . D89 ) by NATTRA_1:def 5;
thus L412: thesis by L411 , L410 , NATTRA_1:def 5;
end;
L413: ( dom <| ( id D80 ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| D80 ,?> ) ) by FUNCT_2:def 1;
L414: <| ( id D80 ) ,?> = ( id <| D80 ,?> ) by L413 , L407 , FUNCT_1:2;
L415: ( D79 . ( id D80 ) ) = [ [ <| ( cod ( id D80 ) ) ,?> , <| ( dom ( id D80 ) ) ,?> ] , <| ( id D80 ) ,?> ] by L231
.= [ [ <| D80 ,?> , <| ( dom ( id D80 ) ) ,?> ] , <| ( id D80 ) ,?> ] by CAT_1:58
.= [ [ <| D80 ,?> , <| D80 ,?> ] , ( id <| D80 ,?> ) ] by L414 , CAT_1:58
.= ( id D84 ) by NATTRA_1:def 17;
thus L416: thesis by L415;
end;
L417: ( ( Obj D79 ) . D80 ) = D84 by L406 , OPPCAT_1:30;
L418: [ [ ( Hom (D80 , ( dom D82 )) ) , ( Hom (D80 , ( cod D82 )) ) ] , ( hom (D80 , D82) ) ] = ( ( hom?- D81 ) . D82 ) by L417 , L390 , L405 , ENS_1:def 21;
L419: [ [ ( Hom (D80 , ( dom D82 )) ) , ( Hom (D80 , ( cod D82 )) ) ] , ( hom (D80 , D82) ) ] = [ [ ( Hom (D81 , ( dom D82 )) ) , ( Hom (D81 , ( cod D82 )) ) ] , ( hom (D81 , D82) ) ] by L418 , ENS_1:def 21;
L420: [ ( Hom (D80 , ( dom D82 )) ) , ( Hom (D80 , ( cod D82 )) ) , ( hom (D80 , D82) ) ] = [ [ ( Hom (D81 , ( dom D82 )) ) , ( Hom (D81 , ( cod D82 )) ) ] , ( hom (D81 , D82) ) ] by L419;
L421: [ ( Hom (D80 , ( dom D82 )) ) , ( Hom (D80 , ( cod D82 )) ) , ( hom (D80 , D82) ) ] = [ ( Hom (D81 , ( dom D82 )) ) , ( Hom (D81 , ( cod D82 )) ) , ( hom (D81 , D82) ) ] by L420;
L422: ( Hom (D80 , ( dom D82 )) ) = ( Hom (D81 , ( dom D82 )) ) by L421 , XTUPLE_0:3;
L423: ( Hom (D80 , ( dom D82 )) ) = ( Hom (D81 , D81) ) by L422 , CAT_1:5;
L424: ( Hom (D80 , D81) ) = ( Hom (D81 , D81) ) by L423 , CAT_1:5;
L425: ( id D81 ) in ( Hom (D81 , D81) ) by CAT_1:27;
reconsider D91 = ( id D81 ) as (Morphism of D80 , D81) by L425 , L424 , CAT_1:def 5;
L426: ( dom D91 ) = D80 by L424 , CAT_1:5;
thus L427: thesis by L426 , L391 , CAT_1:5;
end;
L428: ( Obj D79 ) is  one-to-one by L388 , FUNCT_1:def 4;
thus L429: thesis by L428 , L342;
end;
end;
definition
let C58 , C59 being Category;
let C60 being (Contravariant_Functor of C58 , C59);
attr C60 is  full
means
:L431: (for B59 , B60 being (Object of C58) holds (( Hom (( C60 . B60 ) , ( C60 . B59 )) ) <> ( {} ) implies (for B61 being (Morphism of ( C60 . B60 ) , ( C60 . B59 )) holds (( Hom (B59 , B60) ) <> ( {} ) & (ex B62 being (Morphism of B59 , B60) st B61 = ( C60 . B62 ))))));
end;
registration
let R2 being Category;
::$N Yoneda Lemma
cluster ( Yoneda R2 ) ->  full;
coherence
proof
set D92 = ( Yoneda R2 );
L433: (for B63 , B64 being (Object of R2) holds (( Hom (( D92 . B64 ) , ( D92 . B63 )) ) <> ( {} ) implies (for B65 being (Morphism of ( D92 . B64 ) , ( D92 . B63 )) holds (( Hom (B63 , B64) ) <> ( {} ) & (ex B66 being (Morphism of B63 , B64) st B65 = ( D92 . B66 ))))))
proof
let C61 , C62 being (Object of R2);
assume L434: ( Hom (( D92 . C62 ) , ( D92 . C61 )) ) <> ( {} );
L435: ( <| C62 ,?> . C62 ) = ( ( hom?- (( Hom R2 ) , C62) ) . C62 ) by ENS_1:def 25
.= ( ( Obj ( hom?- (( Hom R2 ) , C62) ) ) . C62 )
.= ( Hom (C62 , C62) ) by ENS_1:60;
let C63 being (Morphism of ( D92 . C62 ) , ( D92 . C61 ));
L436: C63 in (the carrier' of ( Functors (R2 , ( EnsHom R2 )) ));
L437: C63 in ( NatTrans (R2 , ( EnsHom R2 )) ) by L436 , NATTRA_1:def 17;
consider C64 , C65 being (Functor of R2 , ( EnsHom R2 )), C66 being (natural_transformation of C64 , C65) such that L438: C63 = [ [ C64 , C65 ] , C66 ] and L439: C64 is_naturally_transformable_to C65 by L437 , NATTRA_1:def 16;
L440: ( dom C63 ) = C64 by L438 , NATTRA_1:33;
L441: <| C62 ,?> in ( Funct (R2 , ( EnsHom R2 )) ) by CAT_2:def 2;
reconsider D93 = <| C62 ,?> as (Object of ( Functors (R2 , ( EnsHom R2 )) )) by L441 , NATTRA_1:def 17;
L442: <| C61 ,?> in ( Funct (R2 , ( EnsHom R2 )) ) by CAT_2:def 2;
reconsider D94 = <| C61 ,?> as (Object of ( Functors (R2 , ( EnsHom R2 )) )) by L442 , NATTRA_1:def 17;
L443: ( D92 . ( id C61 ) ) = ( id D94 )
proof
set D95 = ( dom <| ( id C61 ) ,?> );
L444: (for R1 being set holds (R1 in D95 implies ( <| ( id C61 ) ,?> . R1 ) = ( ( id <| C61 ,?> ) . R1 )))
proof
let R1 being set;
assume L445: R1 in D95;
reconsider D96 = R1 as (Object of R2) by L445 , FUNCT_2:def 1;
reconsider D97 = ( id D96 ) as (Morphism of D96 , D96);
L446: ( Hom (D96 , D96) ) <> ( {} );
L447: <| ( cod ( id C61 ) ) ,?> is_transformable_to <| ( dom ( id C61 ) ) ,?>;
L448: ( <| ( id C61 ) ,?> . D96 ) = [ [ ( Hom (( cod ( id C61 ) ) , D96) ) , ( Hom (( dom ( id C61 ) ) , D96) ) ] , ( hom (( id C61 ) , ( id D96 )) ) ] by L113
.= [ [ ( Hom (C61 , D96) ) , ( Hom (( dom ( id C61 ) ) , D96) ) ] , ( hom (( id C61 ) , ( id D96 )) ) ]
.= [ [ ( Hom (C61 , D96) ) , ( Hom (C61 , D96) ) ] , ( hom (( id C61 ) , ( id D96 )) ) ]
.= [ [ ( Hom (C61 , D96) ) , ( Hom (C61 , D96) ) ] , ( hom (C61 , ( id D96 )) ) ] by ENS_1:53
.= [ [ ( Hom (C61 , D96) ) , ( Hom (C61 , ( cod ( id D96 ) )) ) ] , ( hom (C61 , ( id D96 )) ) ]
.= [ [ ( Hom (C61 , ( dom ( id D96 ) )) ) , ( Hom (C61 , ( cod ( id D96 ) )) ) ] , ( hom (C61 , ( id D96 )) ) ]
.= ( (<| C61 ,?> qua Function) . ( id D96 ) ) by ENS_1:def 21
.= ( <| C61 ,?> /. D97 ) by L446 , CAT_3:def 10
.= ( id ( <| C61 ,?> . D96 ) ) by NATTRA_1:15
.= ( ( id <| C61 ,?> ) . D96 ) by NATTRA_1:20
.= ( (( id <| C61 ,?> ) qua Function) . D96 ) by NATTRA_1:def 5;
thus L449: thesis by L448 , L447 , NATTRA_1:def 5;
end;
L450: ( dom <| ( id C61 ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| C61 ,?> ) ) by FUNCT_2:def 1;
L451: <| ( id C61 ) ,?> = ( id <| C61 ,?> ) by L450 , L444 , FUNCT_1:2;
L452: ( D92 . ( id C61 ) ) = [ [ <| ( cod ( id C61 ) ) ,?> , <| ( dom ( id C61 ) ) ,?> ] , <| ( id C61 ) ,?> ] by L231
.= [ [ <| C61 ,?> , <| ( dom ( id C61 ) ) ,?> ] , <| ( id C61 ) ,?> ] by CAT_1:58
.= [ [ <| C61 ,?> , <| C61 ,?> ] , ( id <| C61 ,?> ) ] by L451 , CAT_1:58
.= ( id D94 ) by NATTRA_1:def 17;
thus L453: thesis by L452;
end;
L454: ( D92 . C61 ) = D94 by L443 , OPPCAT_1:30;
L455: ( D92 . ( id C62 ) ) = ( id D93 )
proof
set D98 = ( dom <| ( id C62 ) ,?> );
L456: (for R1 being set holds (R1 in D98 implies ( <| ( id C62 ) ,?> . R1 ) = ( ( id <| C62 ,?> ) . R1 )))
proof
let R1 being set;
assume L457: R1 in D98;
reconsider D99 = R1 as (Object of R2) by L457 , FUNCT_2:def 1;
reconsider D100 = ( id D99 ) as (Morphism of D99 , D99);
L458: ( Hom (D99 , D99) ) <> ( {} );
L459: <| ( cod ( id C62 ) ) ,?> is_transformable_to <| ( dom ( id C62 ) ) ,?>;
L460: ( <| ( id C62 ) ,?> . D99 ) = [ [ ( Hom (( cod ( id C62 ) ) , D99) ) , ( Hom (( dom ( id C62 ) ) , D99) ) ] , ( hom (( id C62 ) , ( id D99 )) ) ] by L113
.= [ [ ( Hom (C62 , D99) ) , ( Hom (( dom ( id C62 ) ) , D99) ) ] , ( hom (( id C62 ) , ( id D99 )) ) ]
.= [ [ ( Hom (C62 , D99) ) , ( Hom (C62 , D99) ) ] , ( hom (( id C62 ) , ( id D99 )) ) ]
.= [ [ ( Hom (C62 , D99) ) , ( Hom (C62 , D99) ) ] , ( hom (C62 , ( id D99 )) ) ] by ENS_1:53
.= [ [ ( Hom (C62 , D99) ) , ( Hom (C62 , ( cod ( id D99 ) )) ) ] , ( hom (C62 , ( id D99 )) ) ]
.= [ [ ( Hom (C62 , ( dom ( id D99 ) )) ) , ( Hom (C62 , ( cod ( id D99 ) )) ) ] , ( hom (C62 , ( id D99 )) ) ]
.= ( (<| C62 ,?> qua Function) . ( id D99 ) ) by ENS_1:def 21
.= ( <| C62 ,?> /. D100 ) by L458 , CAT_3:def 10
.= ( id ( <| C62 ,?> . D99 ) ) by NATTRA_1:15
.= ( ( id <| C62 ,?> ) . D99 ) by NATTRA_1:20
.= ( (( id <| C62 ,?> ) qua Function) . D99 ) by NATTRA_1:def 5;
thus L461: thesis by L460 , L459 , NATTRA_1:def 5;
end;
L462: ( dom <| ( id C62 ) ,?> ) = (the carrier of R2) by FUNCT_2:def 1
.= ( dom ( id <| C62 ,?> ) ) by FUNCT_2:def 1;
L463: <| ( id C62 ) ,?> = ( id <| C62 ,?> ) by L462 , L456 , FUNCT_1:2;
L464: ( D92 . ( id C62 ) ) = [ [ <| ( cod ( id C62 ) ) ,?> , <| ( dom ( id C62 ) ) ,?> ] , <| ( id C62 ) ,?> ] by L231
.= [ [ <| C62 ,?> , <| ( dom ( id C62 ) ) ,?> ] , <| ( id C62 ) ,?> ] by CAT_1:58
.= [ [ <| C62 ,?> , <| C62 ,?> ] , ( id <| C62 ,?> ) ] by L463 , CAT_1:58
.= ( id D93 ) by NATTRA_1:def 17;
thus L465: thesis by L464;
end;
L466: ( ( Obj D92 ) . C62 ) = D93 by L455 , OPPCAT_1:30;
L467: ( cod C63 ) = C65 by L438 , NATTRA_1:33;
L468: C65 = ( D92 . C61 ) by L467 , L434 , CAT_1:5;
L469: ( D92 . C62 ) = D93 by L455 , OPPCAT_1:30;
L470: ( <| C61 ,?> . C62 ) = ( ( hom?- (( Hom R2 ) , C61) ) . C62 ) by ENS_1:def 25
.= ( ( Obj ( hom?- (( Hom R2 ) , C61) ) ) . C62 )
.= ( Hom (C61 , C62) ) by ENS_1:60;
L471: (( dom C63 ) = ( D92 . C62 ) & ( cod C63 ) = ( D92 . C61 )) by L434 , CAT_1:5;
reconsider D101 = C66 as (natural_transformation of <| C62 ,?> , <| C61 ,?>) by L471 , L440 , L467 , L455 , L454 , OPPCAT_1:30;
L472: ( ( Obj D92 ) . C61 ) = D94 by L443 , OPPCAT_1:30;
L473: <| C62 ,?> is_transformable_to <| C61 ,?> by L472 , L439 , L440 , L467 , L471 , L469 , NATTRA_1:def 7;
L474: ( Hom (( <| C62 ,?> . C62 ) , ( <| C61 ,?> . C62 )) ) <> ( {} ) by L473 , NATTRA_1:def 2;
L475: ( D101 . C62 ) in ( Hom (( <| C62 ,?> . C62 ) , ( <| C61 ,?> . C62 )) ) by L474 , CAT_1:def 5;
L476: ( cod ( D101 . C62 ) ) = ( <| C61 ,?> . C62 ) by L475 , CAT_1:1;
L477: ( EnsHom R2 ) = CatStr (# ( Hom R2 ) , ( Maps ( Hom R2 ) ) , ( fDom ( Hom R2 ) ) , ( fCod ( Hom R2 ) ) , ( fComp ( Hom R2 ) ) #) by ENS_1:def 13;
reconsider D102 = ( D101 . C62 ) as (Element of ( Maps ( Hom R2 ) )) by L477;
L478: ( cod ( D101 . C62 ) ) = ( ( fCod ( Hom R2 ) ) . ( D101 . C62 ) ) by L477
.= ( cod D102 ) by ENS_1:def 10;
L479: D102 in ( Maps (( dom D102 ) , ( cod D102 )) ) by ENS_1:19;
L480: ( D102 `2 ) in ( Funcs (( dom D102 ) , ( cod D102 )) ) by L479 , ENS_1:20;
L481: ( dom ( D101 . C62 ) ) = ( <| C62 ,?> . C62 ) by L475 , CAT_1:1;
L482: ( (the Source of ( EnsHom R2 )) . ( D101 . C62 ) ) <> ( {} ) by L481 , L435;
L483: ( dom D102 ) <> ( {} ) by L482 , L477 , ENS_1:def 9;
L484: ( cod D102 ) <> ( {} ) by L483 , L480;
L485: ( cod ( D101 . C62 ) ) <> ( {} ) by L484 , L477 , ENS_1:def 10;
thus L486: ( Hom (C61 , C62) ) <> ( {} ) by L485 , L470 , L475 , CAT_1:1;
L487: ( dom ( D101 . C62 ) ) = ( ( fDom ( Hom R2 ) ) . ( D101 . C62 ) ) by L477
.= ( dom D102 ) by ENS_1:def 9;
L488: ( D102 `2 ) is (Function of ( <| C62 ,?> . C62 ) , ( <| C61 ,?> . C62 )) by L487 , L481 , L476 , L480 , L478 , FUNCT_2:66;
L489: ( dom ( D102 `2 ) ) = ( Hom (C62 , C62) ) by L488 , L435 , L476 , L485 , FUNCT_2:def 1;
L490: ( id C62 ) in ( dom ( D102 `2 ) ) by L489 , CAT_1:27;
L491: ( ( D102 `2 ) . ( id C62 ) ) in ( rng ( D102 `2 ) ) by L490 , FUNCT_1:def 3;
L492: ( rng ( D102 `2 ) ) c= ( Hom (C61 , C62) ) by L470 , L488 , RELAT_1:def 19;
L493: ( ( D102 `2 ) . ( id C62 ) ) in ( Hom (C61 , C62) ) by L492 , L491;
reconsider D103 = ( ( D102 `2 ) . ( id C62 ) ) as (Morphism of C61 , C62) by L493 , CAT_1:def 5;
L494: ( <| C61 ,?> . C62 ) <> ( {} ) by L476 , L477 , L484 , ENS_1:def 10;
L495: ( dom D103 ) = C61 by L494 , L470 , CAT_1:5;
take D103;
L496: ( cod D103 ) = C62 by L470 , L494 , CAT_1:5;
L497: C64 = ( D92 . C62 ) by L434 , L440 , CAT_1:5;
L498: <| C62 ,?> is_transformable_to <| C61 ,?> by L497 , L439 , L468 , L466 , L454 , NATTRA_1:def 7;
L499: (for B67 being (Object of R2) holds ( <| D103 ,?> . B67 ) = ( D101 . B67 ))
proof
let C67 being (Object of R2);
L500: ( <| C61 ,?> . C67 ) = ( ( hom?- (( Hom R2 ) , C61) ) . C67 ) by ENS_1:def 25
.= ( ( Obj ( hom?- (( Hom R2 ) , C61) ) ) . C67 )
.= ( Hom (C61 , C67) ) by ENS_1:60;
reconsider D104 = ( D101 . C67 ) as (Element of ( Maps ( Hom R2 ) )) by L477;
L501: ( <| C62 ,?> . C67 ) = ( ( hom?- (( Hom R2 ) , C62) ) . C67 ) by ENS_1:def 25
.= ( ( Obj ( hom?- (( Hom R2 ) , C62) ) ) . C67 )
.= ( Hom (C62 , C67) ) by ENS_1:60;
L502: D104 in ( Maps (( dom D104 ) , ( cod D104 )) ) by ENS_1:19;
L503: ( D104 `2 ) in ( Funcs (( dom D104 ) , ( cod D104 )) ) by L502 , ENS_1:20;
L504: ( D104 `2 ) is (Function of ( dom D104 ) , ( cod D104 )) by L503 , FUNCT_2:66;
set D105 = ( dom ( D104 `2 ) );
L505: ( dom ( D101 . C67 ) ) = ( ( fDom ( Hom R2 ) ) . ( D101 . C67 ) ) by L477
.= ( dom D104 ) by ENS_1:def 9;
L506: ( Hom (( <| C62 ,?> . C67 ) , ( <| C61 ,?> . C67 )) ) <> ( {} ) by L498 , NATTRA_1:def 2;
L507: ( dom ( D101 . C67 ) ) = ( <| C62 ,?> . C67 ) by L506 , CAT_1:5;
L508: ( cod ( D101 . C67 ) ) = ( <| C61 ,?> . C67 ) by L506 , CAT_1:5;
L509: ( cod ( D101 . C67 ) ) = ( ( fCod ( Hom R2 ) ) . ( D101 . C67 ) ) by L477
.= ( cod D104 ) by ENS_1:def 10;
L510: D104 = [ [ ( <| C62 ,?> . C67 ) , ( <| C61 ,?> . C67 ) ] , ( D104 `2 ) ] by L509 , L507 , L508 , L505 , ENS_1:8;
L511: ( D104 `2 ) is (Function of ( dom ( D101 . C67 ) ) , ( cod ( D101 . C67 ) )) by L505 , L509 , L503 , FUNCT_2:66;
L512: ( dom ( D104 `2 ) ) = ( Hom (C62 , C67) )
proof
per cases ;
suppose L513: ( Hom (C62 , C67) ) = ( {} );

thus L514: thesis by L513 , L507 , L505 , L501 , L504;
end;
suppose L515: ( Hom (C62 , C67) ) <> ( {} );

L516: ( Hom (( dom D103 ) , C67) ) <> ( {} ) by L515 , L496 , ENS_1:42;
thus L517: thesis by L516 , L495 , L507 , L508 , L501 , L500 , L511 , FUNCT_2:def 1;
end;
end;
L519: (for B68 being set holds (B68 in D105 implies ( ( hom (D103 , ( id C67 )) ) . B68 ) = ( ( D104 `2 ) . B68 )))
proof
reconsider D106 = ( D101 . C62 ) as (Element of ( Maps ( Hom R2 ) )) by L477;
let C68 being set;
L520: D103 in ( Hom (C61 , ( cod D103 )) ) by L495;
assume L521: C68 in D105;
reconsider D107 = C68 as (Morphism of ( cod D103 ) , C67) by L521 , L496 , L512 , CAT_1:def 5;
reconsider D108 = D107 as (Morphism of C62 , C67) by L470 , L476 , L485 , CAT_1:5;
L522: ( dom D108 ) = C62 by L512 , L521 , CAT_1:5;
reconsider D109 = ( <| C62 ,?> . D108 ) as (Element of ( Maps ( Hom R2 ) )) by L477;
L523: ( cod D108 ) = C67 by L512 , L521 , CAT_1:5;
reconsider D110 = ( <| C61 ,?> . D108 ) as (Element of ( Maps ( Hom R2 ) )) by L477;
L524: [ [ ( Hom (C61 , ( dom D108 )) ) , ( Hom (C61 , ( cod D108 )) ) ] , ( hom (C61 , D108) ) ] = ( (<| C61 ,?> qua Function) . D108 ) by ENS_1:def 21
.= ( <| C61 ,?> . D108 );
L525: [ [ ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) ) ] , ( hom (C62 , D108) ) ] = ( (<| C62 ,?> qua Function) . D108 ) by ENS_1:def 21
.= ( <| C62 ,?> . D108 );
L526: ( cod ( <| C62 ,?> . D108 ) ) = ( ( fCod ( Hom R2 ) ) . ( <| C62 ,?> . D108 ) ) by L477
.= ( cod D109 ) by ENS_1:def 10;
L527: ( cod ( <| C62 ,?> . D108 ) ) = ( ( D109 `1 ) `2 ) by L526 , ENS_1:def 4
.= ( [ ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) ) ] `2 ) by L525 , MCART_1:7
.= ( Hom (C62 , ( cod D108 )) );
L528: [ ( D101 . C67 ) , ( <| C62 ,?> . D108 ) ] in ( dom (the Comp of ( EnsHom R2 )) ) by L527 , L507 , L501 , L523 , CAT_1:15;
L529: D109 in ( Maps (( dom D109 ) , ( cod D109 )) ) by ENS_1:19;
L530: ( D109 `2 ) in ( Funcs (( dom D109 ) , ( cod D109 )) ) by L529 , ENS_1:20;
L531: ( dom ( <| C62 ,?> . D108 ) ) = ( ( fDom ( Hom R2 ) ) . ( <| C62 ,?> . D108 ) ) by L477
.= ( dom D109 ) by ENS_1:def 9;
L532: ( dom ( <| C62 ,?> . D108 ) ) = ( ( D109 `1 ) `1 ) by L531 , ENS_1:def 3
.= ( [ ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) ) ] `1 ) by L525 , MCART_1:7
.= ( Hom (C62 , ( dom D108 )) );
L533: ( D109 `2 ) is (Function of ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) )) by L532 , L531 , L526 , L527 , L530 , FUNCT_2:66;
L534: ( dom ( D109 `2 ) ) = ( Hom (C62 , C62) ) by L533 , L512 , L521 , L522 , L523 , FUNCT_2:def 1;
L535: ( dom D107 ) = ( cod D103 ) by L496 , L512 , L521 , CAT_1:5;
L536: D110 = [ [ ( dom D110 ) , ( cod D110 ) ] , ( D110 `2 ) ] by ENS_1:8;
L537: [ ( Hom (C61 , ( dom D108 )) ) , ( Hom (C61 , ( cod D108 )) ) , ( hom (C61 , D108) ) ] = [ [ ( dom D110 ) , ( cod D110 ) ] , ( D110 `2 ) ] by L536 , L524;
L538: [ ( Hom (C61 , ( dom D108 )) ) , ( Hom (C61 , ( cod D108 )) ) , ( hom (C61 , D108) ) ] = [ ( dom D110 ) , ( cod D110 ) , ( D110 `2 ) ] by L537;
L539: ( hom (C61 , D108) ) = ( D110 `2 ) by L538 , XTUPLE_0:3;
L540: D109 = [ [ ( dom D109 ) , ( cod D109 ) ] , ( D109 `2 ) ] by ENS_1:8;
L541: [ ( dom D109 ) , ( cod D109 ) , ( D109 `2 ) ] = [ [ ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) ) ] , ( hom (C62 , D108) ) ] by L540 , L525;
L542: [ ( dom D109 ) , ( cod D109 ) , ( D109 `2 ) ] = [ ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) ) , ( hom (C62 , D108) ) ] by L541;
L543: ( D109 `2 ) = ( hom (C62 , D108) ) by L542 , XTUPLE_0:3;
L544: ( Hom (( <| C62 ,?> . C62 ) , ( <| C61 ,?> . C62 )) ) <> ( {} ) by L498 , NATTRA_1:def 2;
L545: ( D101 . C62 ) in ( Hom (( <| C62 ,?> . C62 ) , ( <| C61 ,?> . C62 )) ) by L544 , CAT_1:def 5;
L546: ( cod ( D101 . C62 ) ) = ( <| C61 ,?> . C62 ) by L545 , CAT_1:1;
L547: ( dom ( <| C61 ,?> . D108 ) ) = ( ( fDom ( Hom R2 ) ) . ( <| C61 ,?> . D108 ) ) by L477
.= ( dom D110 ) by ENS_1:def 9;
L548: ( dom ( <| C61 ,?> . D108 ) ) = ( ( D110 `1 ) `1 ) by L547 , ENS_1:def 3
.= ( [ ( Hom (C61 , ( dom D108 )) ) , ( Hom (C61 , ( cod D108 )) ) ] `1 ) by L524 , MCART_1:7
.= ( Hom (C61 , ( dom D108 )) );
L549: [ ( <| C61 ,?> . D108 ) , ( D101 . C62 ) ] in ( dom (the Comp of ( EnsHom R2 )) ) by L548 , L470 , L522 , L546 , CAT_1:15;
L550: ( cod ( D101 . C62 ) ) = ( ( fCod ( Hom R2 ) ) . ( D101 . C62 ) ) by L477
.= ( cod D106 ) by ENS_1:def 10;
L551: ( cod D106 ) = ( [ ( Hom (C61 , ( dom D108 )) ) , ( Hom (C61 , ( cod D108 )) ) ] `1 ) by L550 , L470 , L522 , L546
.= ( ( D110 `1 ) `1 ) by L524 , MCART_1:7
.= ( dom D110 ) by ENS_1:def 3;
L552: D108 in ( Hom (C62 , C67) ) by L512 , L521;
L553: ( <| C61 ,?> /. D108 ) = ( <| C61 ,?> . D108 ) by L552 , CAT_3:def 10;
L554: ( Hom (( <| C61 ,?> . C62 ) , ( <| C61 ,?> . C67 )) ) <> ( {} ) by L512 , L521 , CAT_1:84;
L555: ( ( <| C61 ,?> /. D108 ) * ( D101 . C62 ) ) = ( ( <| C61 ,?> . D108 ) (*) (( D101 . C62 ) qua (Morphism of ( EnsHom R2 ))) ) by L554 , L544 , L553 , CAT_1:def 13
.= ( ( fComp ( Hom R2 ) ) . (D110 , D106) ) by L477 , L549 , CAT_1:def 1
.= ( D110 * D106 ) by L551 , ENS_1:def 11
.= [ [ ( dom D106 ) , ( cod D110 ) ] , ( ( D110 `2 ) * ( D106 `2 ) ) ] by L551 , ENS_1:def 6;
L556: ( cod D109 ) = ( ( D109 `1 ) `2 ) by ENS_1:def 4
.= ( [ ( Hom (C62 , ( dom D108 )) ) , ( Hom (C62 , ( cod D108 )) ) ] `2 ) by L525 , MCART_1:7
.= ( dom D104 ) by L507 , L505 , L501 , L523;
L557: ( <| C62 ,?> /. D108 ) = ( <| C62 ,?> . D108 ) by L552 , CAT_3:def 10;
L558: ( Hom (( <| C62 ,?> . C62 ) , ( <| C62 ,?> . C67 )) ) <> ( {} ) by L512 , L521 , CAT_1:84;
L559: ( ( D101 . C67 ) * ( <| C62 ,?> /. D108 ) ) = ( (( D101 . C67 ) qua (Morphism of ( EnsHom R2 ))) (*) ( <| C62 ,?> . D108 ) ) by L558 , L506 , L557 , CAT_1:def 13
.= ( ( fComp ( Hom R2 ) ) . (D104 , D109) ) by L477 , L528 , CAT_1:def 1
.= ( D104 * D109 ) by L556 , ENS_1:def 11
.= [ [ ( dom D109 ) , ( cod D104 ) ] , ( ( D104 `2 ) * ( D109 `2 ) ) ] by L556 , ENS_1:def 6;
L560: ( ( D101 . C67 ) * ( <| C62 ,?> /. D108 ) ) = ( ( <| C61 ,?> /. D108 ) * ( D101 . C62 ) ) by L439 , L497 , L468 , L466 , L454 , L512 , L521 , NATTRA_1:def 8;
L561: [ ( dom D109 ) , ( cod D104 ) , ( ( D104 `2 ) * ( D109 `2 ) ) ] = [ [ ( dom D106 ) , ( cod D110 ) ] , ( ( D110 `2 ) * ( D106 `2 ) ) ] by L560 , L559 , L555;
L562: [ ( dom D109 ) , ( cod D104 ) , ( ( D104 `2 ) * ( D109 `2 ) ) ] = [ ( dom D106 ) , ( cod D110 ) , ( ( D110 `2 ) * ( D106 `2 ) ) ] by L561;
L563: ( ( D104 `2 ) * ( D109 `2 ) ) = ( ( D110 `2 ) * ( D106 `2 ) ) by L562 , XTUPLE_0:3;
L564: ( id C62 ) in ( Hom (C62 , ( cod D103 )) ) by L496 , CAT_1:27;
L565: ( ( hom (D103 , ( id C67 )) ) . C68 ) = ( ( hom (D103 , C67) ) . D107 ) by ENS_1:53
.= ( D107 (*) D103 ) by L496 , L512 , L521 , ENS_1:def 20
.= ( ( D110 `2 ) . ( ( D106 `2 ) . ( id C62 ) ) ) by L535 , L539 , L520 , ENS_1:def 19
.= ( ( ( D104 `2 ) * ( D109 `2 ) ) . ( id C62 ) ) by L489 , L563 , CAT_1:27 , FUNCT_1:13
.= ( ( D104 `2 ) . ( ( hom (C62 , D108) ) . ( id C62 ) ) ) by L543 , L534 , CAT_1:27 , FUNCT_1:13
.= ( ( D104 `2 ) . ( D107 (*) ( id C62 ) ) ) by L535 , L564 , ENS_1:def 19
.= ( ( D104 `2 ) . C68 ) by L496 , L535 , CAT_1:22;
thus L566: thesis by L565;
end;
L567: ( dom ( hom (D103 , C67) ) ) = ( Hom (( cod D103 ) , C67) )
proof
per cases ;
suppose L568: ( Hom (( cod D103 ) , C67) ) = ( {} );

thus L569: thesis by L568;
end;
suppose L570: ( Hom (( cod D103 ) , C67) ) <> ( {} );

L571: ( Hom (C61 , C67) ) <> ( {} ) by L570 , L495 , ENS_1:42;
thus L572: thesis by L571 , L495 , FUNCT_2:def 1;
end;
end;
L574: ( dom ( D104 `2 ) ) = ( dom ( hom (D103 , ( id C67 )) ) ) by L567 , L496 , L512 , ENS_1:53;
L575: ( hom (D103 , ( id C67 )) ) = ( D104 `2 ) by L574 , L519 , FUNCT_1:2;
thus L576: thesis by L575 , L495 , L496 , L501 , L500 , L510 , L113;
end;
L577: <| D103 ,?> = D101 by L499 , L439 , L497 , L468 , L466 , L454 , L495 , L496 , ISOCAT_1:26;
thus L578: thesis by L577 , L438 , L440 , L467 , L471 , L466 , L454 , L495 , L496 , L231;
end;
thus L579: thesis by L433 , L431;
end;
end;
