environ
vocabularies NUMBERS,RELAT_1,XBOOLE_0,ZFMISC_1,TARSKI,RELAT_2,STRUCT_0,FINSET_1,ORDERS_2,CARD_1,CAT_1,YELLOW_0,WELLORD1,NECKLA_2,NECKLACE,SUBSET_1,FUNCT_1,XXREAL_0,SEQM_3,REWRITE1,FINSEQ_1,NAT_1,ARYTM_3,FINSEQ_5,EQREL_1,MSUALG_5,CLASSES2,FUNCOP_1,FUNCT_4,ARYTM_1,NECKLA_3;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,ZFMISC_1,RELAT_1,RELAT_2,RELSET_1,FUNCT_1,PARTFUN1,FUNCT_2,FINSET_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,DOMAIN_1,STRUCT_0,ORDERS_2,WAYBEL_1,FUNCOP_1,CLASSES2,NECKLACE,WAYBEL_0,FUNCT_4,REWRITE1,FINSEQ_1,FINSEQ_5,EQREL_1,MSUALG_5,YELLOW_0,NECKLA_2,WELLORD1;
definitions XBOOLE_0,TARSKI,NECKLACE,RELAT_2,FUNCOP_1,WELLORD1,STRUCT_0;
theorems RELSET_1,NECKLACE,XBOOLE_0,WAYBEL_0,YELLOW_0,FUNCT_1,FUNCT_2,ORDERS_2,RELAT_2,SUBSET_1,ZFMISC_1,XBOOLE_1,TARSKI,MCART_1,CLASSES2,CLASSES1,NECKLA_2,FUNCOP_1,ENUMSET1,RELAT_1,SYSREL,PARTFUN1,GROUP_6,CARD_2,REWRITE1,FINSEQ_1,FINSEQ_3,FINSEQ_5,NAT_1,EQREL_1,MSUALG_6,MSUALG_5,CARD_1,NAT_2,FUNCT_4,FUNCT_3,WAYBEL_1,YELLOW_6,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,NAT_D,STRUCT_0,CKB1;
schemes NAT_1;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FUNCT_2,FUNCOP_1,FINSET_1,XXREAL_0,XREAL_0,NAT_1,CARD_1,FINSEQ_1,REALSET1,STRUCT_0,ORDERS_2,YELLOW_0,NECKLACE,NECKLA_2,ORDINAL1,FUNCT_4,RELSET_1,ZFMISC_1;
constructors XXREAL_0,NAT_1,EQREL_1,CLASSES1,TOLER_1,CLASSES2,FINSEQ_5,REWRITE1,REALSET2,MSUALG_5,ORDERS_3,WAYBEL_1,NECKLACE,NECKLA_2,RELSET_1;
requirements BOOLE,SUBSET,REAL,NUMERALS,ARITHM;
begin
reserve a for set;
reserve b for set;
reserve c for set;
reserve d for set;
theorem
( id { a,b,c,d } ) = { [ a,a ],[ b,b ],[ c,c ],[ d,d ] }
proof
set X = { a,b,c,d };
thus ( id X ) c= { [ a,a ],[ b,b ],[ c,c ],[ d,d ] }
proof
let x being set;
assume A1: x in ( id X );
then consider x1,y1 being set such that A2: x = [ x1,y1 ] and A3: x1 in X and y1 in X by RELSET_1:2;
A4: x1 = y1 by A1,A2,RELAT_1:def 10;
per cases  by A3,ENUMSET1:def 2;
suppose x1 = a;

hence thesis by A2,A4,ENUMSET1:def 2;
end;
suppose x1 = b;

hence thesis by A2,A4,ENUMSET1:def 2;
end;
suppose x1 = c;

hence thesis by A2,A4,ENUMSET1:def 2;
end;
suppose x1 = d;

hence thesis by A2,A4,ENUMSET1:def 2;
end;
end;

let x being set;
assume A5: x in { [ a,a ],[ b,b ],[ c,c ],[ d,d ] };
per cases  by A5,ENUMSET1:def 2;
suppose A6: x = [ a,a ];

a in X by ENUMSET1:def 2;
hence thesis by A6,RELAT_1:def 10;
end;
suppose A7: x = [ b,b ];

b in X by ENUMSET1:def 2;
hence thesis by A7,RELAT_1:def 10;
end;
suppose A8: x = [ c,c ];

c in X by ENUMSET1:def 2;
hence thesis by A8,RELAT_1:def 10;
end;
suppose A9: x = [ d,d ];

d in X by ENUMSET1:def 2;
hence thesis by A9,RELAT_1:def 10;
end;
end;
