environ
vocabularies SUBSET_1,MSAFREE2,FACIRC_1,XBOOLEAN,STRUCT_0,LATTICES,CIRCCOMB,CIRCUIT1,XBOOLE_0,MSUALG_1,FINSEQ_1,TWOSCOMP,FUNCT_4,RELAT_1,PARTFUN1,FSM_1,MARGREL1,FUNCT_1,CIRCUIT2,GLIB_000,ARYTM_3,FSCIRC_1;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,RELAT_1,FUNCT_1,FINSEQ_1,STRUCT_0,MARGREL1,NAT_1,MSUALG_1,MSAFREE2,CIRCUIT1,CIRCUIT2,CIRCCOMB,TWOSCOMP,FACIRC_1,BINARITH,CKB1,CKB2,CKB3,CKB4,CKB5,CKB11,CKB12,CKB28;
definitions CIRCUIT2,FACIRC_1,MSAFREE2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB11,CKB12,CKB28;
theorems TARSKI,ENUMSET1,RELAT_1,FUNCT_1,FINSEQ_2,CIRCUIT1,CIRCUIT2,CIRCCOMB,FACIRC_1,TWOSCOMP,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29;
registrations RELSET_1,CARD_3,STRUCT_0,CIRCCOMB,FACIRC_1,ORDINAL1,FINSEQ_1,FUNCT_1,MSAFREE2;
constructors ENUMSET1,BINARITH,CIRCUIT1,CIRCUIT2,FACIRC_1,TWOSCOMP,NAT_1,RELSET_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB11,CKB12,CKB28;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
(for x,y,c being non pair set holds ( InnerVertices ( BitSubtracterWithBorrowStr (x,y,c) ) ) = ( ( { [ <* x,y *>,( 'xor' ) ],( 2GatesCircOutput (x,y,c,( 'xor' )) ) } \/ { [ <* x,y *>,( and2a ) ],[ <* y,c *>,( and2 ) ],[ <* x,c *>,( and2a ) ] } ) \/ { ( BorrowOutput (x,y,c) ) } ))
proof
let x being non pair set,y being non pair set,c being non pair set;
set S1 = ( 2GatesCircStr (x,y,c,( 'xor' )) );
set S2 = ( BorrowStr (x,y,c) );
A1: (( ( { [ <* x,y *>,( 'xor' ) ],( 2GatesCircOutput (x,y,c,( 'xor' )) ) } \/ { [ <* x,y *>,( and2a ) ],[ <* y,c *>,( and2 ) ],[ <* x,c *>,( and2a ) ] } ) \/ { ( BorrowOutput (x,y,c) ) } ) = ( { [ <* x,y *>,( 'xor' ) ],( 2GatesCircOutput (x,y,c,( 'xor' )) ) } \/ ( { [ <* x,y *>,( and2a ) ],[ <* y,c *>,( and2 ) ],[ <* x,c *>,( and2a ) ] } \/ { ( BorrowOutput (x,y,c) ) } ) ) & ( InnerVertices S1 ) = { [ <* x,y *>,( 'xor' ) ],( 2GatesCircOutput (x,y,c,( 'xor' )) ) }) by FACIRC_1:56,XBOOLE_1:4;
( InnerVertices S2 ) = ( { [ <* x,y *>,( and2a ) ],[ <* y,c *>,( and2 ) ],[ <* x,c *>,( and2a ) ] } \/ { ( BorrowOutput (x,y,c) ) } ) by CKB16:1;
hence thesis by A1,FACIRC_1:27;
end;
