environ
vocabularies NUMBERS,ABIAN,SUBSET_1,ARYTM_3,XXREAL_0,ARYTM_1,CARD_1,TARSKI,FINSEQ_1,RELAT_1,FUNCT_1,NAT_1,XBOOLE_0,GLIB_000,FINSEQ_5,GRAPH_2,INT_1,FINSET_1,RCOMP_1,WAYBEL_0,ZFMISC_1,MSAFREE2,ORDINAL4,GRAPH_1,FUNCT_4,FUNCOP_1,MCART_1,GLIB_001;
notations TARSKI,XBOOLE_0,CARD_1,NUMBERS,SUBSET_1,XCMPLX_0,XXREAL_0,DOMAIN_1,RELAT_1,FUNCT_1,FINSEQ_1,GRAPH_2,FINSEQ_5,RELSET_1,MCART_1,FINSET_1,NAT_1,NAT_D,FUNCOP_1,FUNCT_4,GLIB_000,ABIAN,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39;
definitions FUNCOP_1,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB36,CKB37,CKB38,CKB39;
theorems CARD_1,CARD_2,FUNCOP_1,ENUMSET1,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_4,FINSEQ_5,FINSEQ_6,FINSET_1,FUNCT_1,FUNCT_4,GLIB_000,GRAPH_2,GRAPH_5,INT_1,JORDAN12,MCART_1,NAT_1,NAT_2,PEPIN,RELAT_1,TARSKI,XBOOLE_0,XBOOLE_1,XREAL_1,PRE_CIRC,XXREAL_0,ABIAN,ORDINAL1,NAT_D,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101,CKB102,CKB103;
schemes FINSEQ_1,FUNCT_1,NAT_1,RECDEF_1;
registrations XBOOLE_0,RELAT_1,FUNCT_1,ORDINAL1,FUNCOP_1,FINSET_1,XXREAL_0,XREAL_0,NAT_1,INT_1,FINSEQ_1,GLIB_000,ABIAN,GRAPH_2,GRAPH_3,CARD_1,SUBSET_1,CKB10;
constructors DOMAIN_1,FUNCT_4,NAT_D,RECDEF_1,FINSEQ_5,GLIB_000,ABIAN,GRAPH_2,XXREAL_2,RELSET_1,FINSEQ_2,RAT_1,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB36,CKB37,CKB38,CKB39;
requirements ARITHM,BOOLE,NUMERALS,REAL,SUBSET;
begin
theorem
Lm65: (for G being _Graph holds (for W being (Walk of G) holds (for e,v being set holds (((((W is  Path-like & e Joins ( W .last() ),v,G) & (not e in ( W .edges() ))) & (W is  trivial or W is  open)) & (for n being  odd (Element of ( NAT )) holds ((1 < n & n <= ( len W )) implies ( W . n ) <> v))) implies ( W .addEdge e ) is  Path-like))))
proof
let G being _Graph;
let W being (Walk of G);
let e being set,v being set;
assume that
A1: W is  Path-like
and
A2: e Joins ( W .last() ),v,G
and
A3: (not e in ( W .edges() ))
and
A4: (W is  trivial or W is  open)
and
A5: (for n being  odd (Element of ( NAT )) holds ((1 < n & n <= ( len W )) implies ( W . n ) <> v));
reconsider lenW = ( len W ) as  odd (Element of ( NAT ));
set W2 = ( W .addEdge e );
A6: e in ( ( W .last() ) .edgesInOut() ) by A2,GLIB_000:62;
now
W is  Trail-like by A1,CKB36:def 1;
hence W2 is  Trail-like by A3,A6,CKB99:1;
let m being  odd (Element of ( NAT )),n being  odd (Element of ( NAT ));
assume that
A7: m < n
and
A8: n <= ( len W2 )
and
A9: ( W2 . m ) = ( W2 . n );
now
per cases  by A4;
suppose A10: W is  open;

now
per cases ;
suppose A11: n <= ( len W );

A12: 1 <= m by ABIAN:12;
m <= ( len W ) by A7,A11,XXREAL_0:2;
then m in ( dom W ) by A12,FINSEQ_3:25;
then A13: ( W2 . m ) = ( W . m ) by A2,CKB77:1;
1 <= n by ABIAN:12;
then n in ( dom W ) by A11,FINSEQ_3:25;
then A14: ( W . m ) = ( W . n ) by A2,A9,A13,CKB77:1;
then m = 1 by A1,A7,A11,CKB36:def 1;
then ( W .first() ) = ( W .last() ) by A1,A7,A11,A14,CKB36:def 1;
hence (m = 1 & n = ( len W2 )) by A10,CKB31:def 1;
end;
suppose n > ( len W );

then ( lenW + 1 ) <= n by NAT_1:13;
then ( lenW + 1 ) < n by XXREAL_0:1;
then ( ( lenW + 1 ) + 1 ) <= n by NAT_1:13;
then ( ( len W ) + ( 1 + 1 ) ) <= n;
then A15: ( len W2 ) <= n by A2,CKB76:1;
then n = ( len W2 ) by A8,XXREAL_0:1;
then ( W2 . n ) = ( W2 . ( ( len W ) + 2 ) ) by A2,CKB76:1;
then A16: ( W2 . n ) = v by A2,CKB77:1;
m < ( len W2 ) by A7,A8,A15,XXREAL_0:1;
then m < ( ( len W ) + ( 1 + 1 ) ) by A2,CKB76:1;
then m < ( ( ( len W ) + 1 ) + 1 );
then m <= ( lenW + 1 ) by NAT_1:13;
then m < ( lenW + 1 ) by XXREAL_0:1;
then A17: m <= ( len W ) by NAT_1:13;
1 <= m by ABIAN:12;
then m in ( dom W ) by A17,FINSEQ_3:25;
then A18: ( W . m ) = v by A2,A9,A16,CKB77:1;
now
A19: 1 <= m by ABIAN:12;
assume m <> 1;
then 1 < m by A19,XXREAL_0:1;
hence contradiction by A5,A17,A18;
end;
hence m = 1;
thus n = ( len W2 ) by A8,A15,XXREAL_0:1;
end;
end;
hence (m = 1 & n = ( len W2 ));
end;
suppose W is  trivial;

then (ex v being (Vertex of G) st W = ( G .walkOf v )) by CKB95:1;
then ( len W ) = 1 by FINSEQ_1:39;
then A20: ( len W2 ) = ( 1 + 2 ) by A2,CKB76:1;
A21: ( m + 1 ) <= n by A7,NAT_1:13;
A22: 1 <= m by ABIAN:12;
then ( 1 + 1 ) <= ( m + 1 ) by XREAL_1:7;
then ( 2 * 1 ) <= n by A21,XXREAL_0:2;
then ( 2 * 1 ) < n by XXREAL_0:1;
then A23: ( len W2 ) <= n by A20,NAT_1:13;
then n = ( len W2 ) by A8,XXREAL_0:1;
then ( ( m + 1 ) - 1 ) <= ( 3 - 1 ) by A7,A20,NAT_1:13;
then m < ( 2 * 1 ) by XXREAL_0:1;
then ( m + 1 ) <= 2 by NAT_1:13;
then ( ( m + 1 ) - 1 ) <= ( 2 - 1 ) by XREAL_1:13;
hence (m = 1 & n = ( len W2 )) by A8,A22,A23,XXREAL_0:1;
end;
end;
hence (m = 1 & n = ( len W2 ));
end;
hence thesis by CKB36:def 1;
end;
