environ
vocabularies NUMBERS,XBOOLE_0,NAT_1,FINSEQ_2,MARGREL1,BINARITH,ARYTM_3,POWER,SUBSET_1,ORDINAL4,FINSEQ_1,FUNCOP_1,XBOOLEAN,CARD_1,RELAT_1,REAL_1,FINSEQ_5,EUCLID,XXREAL_0,FUNCT_1,PARTFUN1,ARYTM_1,BINARI_2,ZFMISC_1,INT_1,ABIAN,BINARI_3;
notations XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,REAL_1,XXREAL_0,NAT_1,NAT_D,POWER,ABIAN,SERIES_1,MARGREL1,FUNCT_1,PARTFUN1,FUNCOP_1,FINSEQ_1,FINSEQ_5,FINSEQOP,ZFMISC_1,FINSEQ_2,BINARITH,BINARI_2,EUCLID,CKB25;
definitions FINSEQ_2,EUCLID,XBOOLEAN,CKB25;
theorems TARSKI,NAT_1,NAT_2,MARGREL1,POWER,FUNCOP_1,FINSEQ_1,FINSEQ_2,FINSEQ_4,FINSEQ_5,FINSEQ_6,BINARITH,BINARI_2,XREAL_1,XCMPLX_1,XBOOLEAN,NAT_D,PARTFUN1,XXREAL_0,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30;
schemes NAT_1,NAT_2,FINSEQ_2;
registrations RELSET_1,XREAL_0,NAT_1,XBOOLEAN,MARGREL1,ZFMISC_1,NAT_2,ORDINAL1,XBOOLE_0,FINSEQ_2,INT_1,CARD_1,FINSEQ_1;
constructors XXREAL_0,NAT_1,NAT_D,FINSEQOP,SERIES_1,ZFMISC_1,BINARITH,FINSEQ_5,BINARI_2,ABIAN,EUCLID,BINOP_2,RELSET_1,CKB25;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Lm3: (for n being non  empty Nat holds (for k being Nat holds ((( 2 to_power n ) <= k & k < ( 2 to_power ( n + 1 ) )) implies ( ( n + 1 ) -BinarySequence k ) = ( ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) ^ <* ( TRUE ) *> ))))
proof
let n being non  empty Nat;
let k being Nat;
assume that
A1: ( 2 to_power n ) <= k
and
A2: k < ( 2 to_power ( n + 1 ) );
now
let i being Nat;
reconsider z = i as Nat;
assume A3: i in ( Seg ( n + 1 ) );
then i in ( Seg ( len ( ( n + 1 ) -BinarySequence k ) ) ) by CARD_1:def 7;
then A4: i in ( dom ( ( n + 1 ) -BinarySequence k ) ) by FINSEQ_1:def 3;
now
per cases  by A3,FINSEQ_2:7;
suppose A5: i in ( Seg n );

then A6: 1 <= i by FINSEQ_1:1;
A7: ( 2 * ( 2 to_power ( i -' 1 ) ) ) = ( ( 2 to_power ( i -' 1 ) ) * ( 2 to_power 1 ) ) by POWER:25
.= ( 2 to_power ( ( i -' 1 ) + 1 ) ) by POWER:27
.= ( 2 to_power ( ( i - 1 ) + 1 ) ) by A6,XREAL_1:233
.= ( 2 to_power i );
( 2 to_power ( i -' 1 ) ) > ( 0 ) by POWER:34;
then A8: ( ( 0 ) + 1 ) <= ( 2 to_power ( i -' 1 ) ) by NAT_1:13;
i <= n by A5,FINSEQ_1:1;
then A9: ( 2 * ( 2 to_power ( z -' 1 ) ) ) divides ( 2 to_power n ) by A7,NAT_2:11;
A10:now
per cases ;
suppose A11: ( k div ( 2 to_power ( i -' 1 ) ) ) is  even;

then A12: ( ( k div ( 2 to_power ( i -' 1 ) ) ) mod 2 ) = ( 0 ) by NAT_2:21;
( ( k -' ( 2 to_power n ) ) div ( 2 to_power ( i -' 1 ) ) ) is  even by A1,A8,A9,A11,NAT_2:23;
hence ( ( k div ( 2 to_power ( i -' 1 ) ) ) mod 2 ) = ( ( ( k -' ( 2 to_power n ) ) div ( 2 to_power ( i -' 1 ) ) ) mod 2 ) by A12,NAT_2:21;
end;
suppose A13: ( k div ( 2 to_power ( i -' 1 ) ) ) is  odd;

then A14: ( ( k div ( 2 to_power ( i -' 1 ) ) ) mod 2 ) = 1 by NAT_2:22;
( ( k -' ( 2 to_power n ) ) div ( 2 to_power ( i -' 1 ) ) ) is  odd by A1,A8,A9,A13,NAT_2:23;
hence ( ( k div ( 2 to_power ( i -' 1 ) ) ) mod 2 ) = ( ( ( k -' ( 2 to_power n ) ) div ( 2 to_power ( i -' 1 ) ) ) mod 2 ) by A14,NAT_2:22;
end;
end;
i in ( Seg ( len ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) ) ) by A5,CARD_1:def 7;
then A15: i in ( dom ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) ) by FINSEQ_1:def 3;
thus ( ( ( n + 1 ) -BinarySequence k ) . i ) = ( ( ( n + 1 ) -BinarySequence k ) /. i ) by A4,PARTFUN1:def 6
.= ( IFEQ (( ( k div ( 2 to_power ( i -' 1 ) ) ) mod 2 ),( 0 ),( FALSE ),( TRUE )) ) by A3,CKB25:def 1
.= ( ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) /. i ) by A5,A10,CKB25:def 1
.= ( ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) . i ) by A15,PARTFUN1:def 6
.= ( ( ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) ^ <* ( TRUE ) *> ) . i ) by A15,FINSEQ_1:def 7;
end;
suppose A16: i = ( n + 1 );

hence ( ( ( n + 1 ) -BinarySequence k ) . i ) = ( TRUE ) by A1,A2,CKB30:1
.= ( ( ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) ^ <* ( TRUE ) *> ) . i ) by A16,FINSEQ_2:116;
end;
end;
hence ( ( ( n + 1 ) -BinarySequence k ) . i ) = ( ( ( n -BinarySequence ( k -' ( 2 to_power n ) ) ) ^ <* ( TRUE ) *> ) . i );
end;
hence thesis by FINSEQ_2:119;
end;
