environ
vocabularies TARSKI,XBOOLE_0;
notations TARSKI,CKB2;
definitions CKB2;
theorems TARSKI,CKB2;
schemes TARSKI,CKB1;
constructors TARSKI,CKB2;
begin
reserve Y for set;
reserve x for set;
registration
cluster  empty for set;
existence
proof
defpred P[ set ]
 means
contradiction;
set X = the set;
consider Y such that A1: (x in Y iff (x in X & P[ x ])) from CKB1:sch 1;
take Y;
thus (not (ex x being set st x in Y)) by A1;
end;
end;
