environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,PRE_TOPC,EUCLID,COMPLEX1,XXREAL_0,ARYTM_1,MCART_1,SQUARE_1,ARYTM_3,CARD_1,REAL_1,XBOOLE_0,METRIC_1,SUBSET_1,TOPMETR,TARSKI,XXREAL_1,STRUCT_0,FUNCT_1,BORSUK_1,RELAT_1,TOPS_2,ORDINAL2,RCOMP_1,SUPINF_2,TOPREAL1,JGRAPH_3,JGRAPH_4,PSCOMP_1,SEQ_4,RLTOPSP1,JORDAN6,TOPREAL2,JORDAN5C,PCOMPS_1,VALUED_1,JORDAN3,FUNCT_2;
notations ORDINAL1,NUMBERS,XREAL_0,COMPLEX1,REAL_1,XBOOLE_0,SUBSET_1,TARSKI,RELAT_1,TOPS_2,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,SEQ_4,STRUCT_0,RLVECT_1,RLTOPSP1,EUCLID,TOPMETR,PCOMPS_1,COMPTS_1,METRIC_1,SQUARE_1,RCOMP_1,MEASURE6,PSCOMP_1,BINOP_1,PRE_TOPC,JGRAPH_3,TOPREAL1,JORDAN5C,JORDAN6,TOPREAL2,JGRAPH_4,XXREAL_0;
definitions TARSKI,JORDAN6,SQUARE_1,STRUCT_0,RELAT_1,RLTOPSP1;
theorems TARSKI,XBOOLE_0,XBOOLE_1,RELAT_1,FUNCT_1,FUNCT_2,TOPS_1,TOPS_2,PRE_TOPC,TOPMETR,JORDAN6,EUCLID,JGRAPH_1,SEQ_4,SQUARE_1,PSCOMP_1,METRIC_1,JGRAPH_2,RCOMP_1,COMPTS_1,SETWISEO,BORSUK_1,TOPREAL1,TOPREAL3,TOPREAL5,JGRAPH_3,ABSVALUE,COMPLEX1,JORDAN5A,JORDAN5B,JORDAN7,HEINE,JGRAPH_4,PCOMPS_1,JORDAN5C,XREAL_0,TSEP_1,TOPRNS_1,XCMPLX_1,XREAL_1,XXREAL_0,XXREAL_1,XXREAL_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38;
schemes FUNCT_2,JGRAPH_2;
registrations XBOOLE_0,FUNCT_1,RELSET_1,FUNCT_2,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,PRE_TOPC,METRIC_1,BORSUK_1,EUCLID,TOPMETR,TOPREAL1,BORSUK_3,COMPTS_1,XXREAL_2;
constructors REAL_1,SQUARE_1,COMPLEX1,RCOMP_1,TOPS_2,COMPTS_1,MONOID_0,TOPREAL1,MEASURE6,JORDAN5C,JORDAN6,JGRAPH_3,JGRAPH_4,SEQ_1,PSCOMP_1,XXREAL_2,SEQ_4,BINOP_2,PCOMPS_1;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
theorem
Th39: (for a,b,d,e being Real holds ((a <= b & e > ( 0 )) implies (ex f being (Function of ( Closed-Interval-TSpace (a,b) ),( Closed-Interval-TSpace (( ( e * a ) + d ),( ( e * b ) + d )) )) st (f is  being_homeomorphism & (for r being Real holds (r in [. a,b .] implies ( f . r ) = ( ( e * r ) + d )))))))
proof
let a being Real;
let b being Real;
let d being Real;
let e being Real;
assume that
A1: a <= b
and
A2: e > ( 0 );
set S = ( Closed-Interval-TSpace (a,b) );
defpred P[ set,set ]
 means
(for r being Real holds ($1 = r implies $2 = ( ( e * r ) + d )));
set X = (the carrier of ( Closed-Interval-TSpace (a,b) ));
A3: X = [. a,b .] by A1,TOPMETR:18;
then reconsider B = (the carrier of S) as (Subset of ( R^1 )) by TOPMETR:17;
A4: ( ( R^1 ) | B ) = S by A1,A3,TOPMETR:19;
set T = ( Closed-Interval-TSpace (( ( e * a ) + d ),( ( e * b ) + d )) );
set Y = (the carrier of ( Closed-Interval-TSpace (( ( e * a ) + d ),( ( e * b ) + d )) ));
A5: ( e * a ) <= ( e * b ) by A1,A2,XREAL_1:64;
then A6: Y = [. ( ( e * a ) + d ),( ( e * b ) + d ) .] by TOPMETR:18,XREAL_1:7;
then reconsider C = (the carrier of T) as (Subset of ( R^1 )) by TOPMETR:17;
defpred P1[ set,set ]
 means
(for r being Real holds (r = $1 implies $2 = ( ( e * r ) + d )));
T = ( TopSpaceMetr ( Closed-Interval-MSpace (( ( e * a ) + d ),( ( e * b ) + d )) ) ) by TOPMETR:def 7;
then A7: T is  T_2 by PCOMPS_1:34;
A8: (for x being set holds (x in X implies (ex y being set st (y in Y & P[ x,y ]))))
proof
let x being set;
assume A9: x in X;
then reconsider r1 = x as Real by A3;
set y1 = ( ( e * r1 ) + d );
r1 <= b by A3,A9,XXREAL_1:1;
then ( e * r1 ) <= ( e * b ) by A2,XREAL_1:64;
then A10: y1 <= ( ( e * b ) + d ) by XREAL_1:7;
a <= r1 by A3,A9,XXREAL_1:1;
then ( e * a ) <= ( e * r1 ) by A2,XREAL_1:64;
then ( ( e * a ) + d ) <= y1 by XREAL_1:7;
then ((for r being Real holds (x = r implies y1 = ( ( e * r ) + d ))) & y1 in Y) by A6,A10,XXREAL_1:1;
hence thesis;
end;
(ex f being (Function of X,Y) st (for x being set holds (x in X implies P[ x,( f . x ) ]))) from FUNCT_2:sch 1(A8);
then consider f1 being (Function of X,Y) such that A11: (for x being set holds (x in X implies P[ x,( f1 . x ) ]));
reconsider f2 = f1 as (Function of ( Closed-Interval-TSpace (a,b) ),( Closed-Interval-TSpace (( ( e * a ) + d ),( ( e * b ) + d )) ));
A12: (for r being Real holds (r in [. a,b .] implies ( f2 . r ) = ( ( e * r ) + d ))) by A3,A11;
A13: ( dom f2 ) = (the carrier of S) by FUNCT_2:def 1;
( [#] T ) c= ( rng f2 )
proof
let y being set;
assume A14: y in ( [#] T );
then reconsider ry = y as Real by A6;
ry <= ( ( e * b ) + d ) by A6,A14,XXREAL_1:1;
then ( ( ( e * b ) + d ) - d ) >= ( ry - d ) by XREAL_1:9;
then ( ( b * e ) / e ) >= ( ( ry - d ) / e ) by A2,XREAL_1:72;
then A15: b >= ( ( ry - d ) / e ) by A2,XCMPLX_1:89;
( ( e * a ) + d ) <= ry by A6,A14,XXREAL_1:1;
then ( ( ( e * a ) + d ) - d ) <= ( ry - d ) by XREAL_1:9;
then ( ( a * e ) / e ) <= ( ( ry - d ) / e ) by A2,XREAL_1:72;
then a <= ( ( ry - d ) / e ) by A2,XCMPLX_1:89;
then A16: ( ( ry - d ) / e ) in [. a,b .] by A15,XXREAL_1:1;
then ( f2 . ( ( ry - d ) / e ) ) = ( ( e * ( ( ry - d ) / e ) ) + d ) by A3,A11
.= ( ( ry - d ) + d ) by A2,XCMPLX_1:87
.= ry;
hence thesis by A3,A13,A16,FUNCT_1:3;
end;
then A17: ( rng f2 ) = ( [#] T ) by XBOOLE_0:def 10;
then reconsider f3 = f1 as (Function of S,( R^1 )) by A6,A13,FUNCT_2:2,TOPMETR:17;
(for x1,x2 being set holds (((x1 in ( dom f2 ) & x2 in ( dom f2 )) & ( f2 . x1 ) = ( f2 . x2 )) implies x1 = x2))
proof
let x1 being set;
let x2 being set;
assume that
A18: x1 in ( dom f2 )
and
A19: x2 in ( dom f2 )
and
A20: ( f2 . x1 ) = ( f2 . x2 );
reconsider r2 = x2 as Real by A3,A13,A19;
reconsider r1 = x1 as Real by A3,A13,A18;
( f2 . x1 ) = ( ( e * r1 ) + d ) by A11,A18;
then ( ( ( e * r1 ) + d ) - d ) = ( ( ( e * r2 ) + d ) - d ) by A11,A19,A20
.= ( e * r2 );
then ( ( r1 * e ) / e ) = r2 by A2,XCMPLX_1:89;
hence thesis by A2,XCMPLX_1:89;
end;
then A21: (( dom f2 ) = ( [#] S ) & f2 is  one-to-one) by FUNCT_1:def 4,FUNCT_2:def 1;
A22: (for x being set holds (x in (the carrier of ( R^1 )) implies (ex y being set st (y in (the carrier of ( R^1 )) & P1[ x,y ]))))
proof
let x being set;
assume x in (the carrier of ( R^1 ));
then reconsider rx = x as Real by TOPMETR:17;
reconsider ry = ( ( e * rx ) + d ) as Real;
(for r being Real holds (r = x implies ry = ( ( e * r ) + d )));
hence thesis by TOPMETR:17;
end;
(ex f4 being (Function of (the carrier of ( R^1 )),(the carrier of ( R^1 ))) st (for x being set holds (x in (the carrier of ( R^1 )) implies P1[ x,( f4 . x ) ]))) from FUNCT_2:sch 1(A22);
then consider f4 being (Function of (the carrier of ( R^1 )),(the carrier of ( R^1 ))) such that A23: (for x being set holds (x in (the carrier of ( R^1 )) implies P1[ x,( f4 . x ) ]));
reconsider f5 = f4 as (Function of ( R^1 ),( R^1 ));
A24: (for x being Real holds ( f5 . x ) = ( ( e * x ) + d )) by A23,TOPMETR:17;
A25: ( ( dom f5 ) /\ B ) = ( ( REAL ) /\ B ) by FUNCT_2:def 1,TOPMETR:17
.= B by TOPMETR:17,XBOOLE_1:28;
A26: (for x being set holds (x in ( dom f3 ) implies ( f3 . x ) = ( f5 . x )))
proof
let x being set;
assume A27: x in ( dom f3 );
then reconsider rx = x as Real by A3,A13;
( f4 . x ) = ( ( e * rx ) + d ) by A23,TOPMETR:17;
hence thesis by A11,A27;
end;
( dom f3 ) = B by FUNCT_2:def 1;
then f3 = ( f5 | B ) by A25,A26,FUNCT_1:46;
then A28: f3 is  continuous by A24,A4,TOPMETR:7,TOPMETR:21;
A29: S is  compact by A1,HEINE:4;
( ( R^1 ) | C ) = T by A5,A6,TOPMETR:19,XREAL_1:7;
then f2 is  being_homeomorphism by A21,A17,A28,A29,A7,COMPTS_1:17,TOPMETR:6;
hence thesis by A12;
end;
