environ
vocabularies VECTSP_1,REALSET2,FUNCT_1,MESFUNC1,SUBSET_1,STRUCT_0,RELAT_1,ARYTM_1,ARYTM_3,SUPINF_2,ALGSTR_0,BINOP_1,ZFMISC_1,REALSET3;
notations TARSKI,ZFMISC_1,SUBSET_1,FUNCT_1,FUNCT_2,BINOP_1,STRUCT_0,ALGSTR_0,GROUP_1,RLVECT_1,VECTSP_1,REALSET2,CKB8;
definitions BINOP_1,RLVECT_1,REALSET2,ALGSTR_0,STRUCT_0,CKB8;
theorems FUNCT_2,ZFMISC_1,REALSET2,XBOOLE_0,RLVECT_1,VECTSP_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16;
schemes BINOP_1;
registrations RELSET_1,STRUCT_0,REALSET2;
constructors BINOP_1,REALSET2,RELSET_1,CKB8;
requirements SUBSET,BOOLE;
begin
theorem
(for F being Field holds (for a,b,c being (Element of F) holds (( a + b ) = c iff ( ( osf F ) . (c,a) ) = b)))
proof
let F being Field;
let a being (Element of F),b being (Element of F),c being (Element of F);
set d = ( 0. F );
(( c + d ) = c & ( ( osf F ) . (b,d) ) = b) by CKB16:1,REALSET2:2;
hence thesis by CKB14:1;
end;
