environ
vocabularies VECTSP_1,REALSET2,FUNCT_1,MESFUNC1,SUBSET_1,STRUCT_0,RELAT_1,ARYTM_1,ARYTM_3,SUPINF_2,ALGSTR_0,BINOP_1,ZFMISC_1,REALSET3;
notations TARSKI,ZFMISC_1,SUBSET_1,FUNCT_1,FUNCT_2,BINOP_1,STRUCT_0,ALGSTR_0,GROUP_1,RLVECT_1,VECTSP_1,REALSET2,CKB8,CKB21;
definitions BINOP_1,RLVECT_1,REALSET2,ALGSTR_0,STRUCT_0,CKB8,CKB21;
theorems FUNCT_2,ZFMISC_1,REALSET2,XBOOLE_0,RLVECT_1,VECTSP_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21;
schemes BINOP_1;
registrations RELSET_1,STRUCT_0,REALSET2;
constructors BINOP_1,REALSET2,RELSET_1,CKB8,CKB21;
requirements SUBSET,BOOLE;
begin
theorem
Th29: (for F being Field holds (for x being (Element of ( NonZero F )) holds ( ( ovf F ) . (x,x) ) = ( 1. F )))
proof
let F being Field;
let x being (Element of ( NonZero F ));
thus ( ( ovf F ) . (x,x) ) = ( ( omf F ) . (x,( ( revf F ) . x )) ) by CKB21:def 1
.= ( 1. F ) by REALSET2:def 6;
end;
