environ
vocabularies VECTSP_1,REALSET2,FUNCT_1,MESFUNC1,SUBSET_1,STRUCT_0,RELAT_1,ARYTM_1,ARYTM_3,SUPINF_2,ALGSTR_0,BINOP_1,ZFMISC_1,REALSET3;
notations TARSKI,ZFMISC_1,SUBSET_1,FUNCT_1,FUNCT_2,BINOP_1,STRUCT_0,ALGSTR_0,GROUP_1,RLVECT_1,VECTSP_1,REALSET2,CKB8,CKB21;
definitions BINOP_1,RLVECT_1,REALSET2,ALGSTR_0,STRUCT_0,CKB8,CKB21;
theorems FUNCT_2,ZFMISC_1,REALSET2,XBOOLE_0,RLVECT_1,VECTSP_1,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
schemes BINOP_1;
registrations RELSET_1,STRUCT_0,REALSET2;
constructors BINOP_1,REALSET2,RELSET_1,CKB8,CKB21;
requirements SUBSET,BOOLE;
begin
theorem
(for F being Field holds (for a being (Element of ( NonZero F )) holds (( ( omf F ) . (a,( ( ovf F ) . (( 1. F ),a) )) ) = ( 1. F ) & ( ( omf F ) . (( ( ovf F ) . (( 1. F ),a) ),a) ) = ( 1. F ))))
proof
let F being Field;
let a being (Element of ( NonZero F ));
thus A1: ( ( omf F ) . (a,( ( ovf F ) . (( 1. F ),a) )) ) = ( ( ovf F ) . (( a * ( 1. F ) ),a) ) by CKB23:1
.= ( ( ovf F ) . (a,a) ) by REALSET2:21
.= ( 1. F ) by CKB22:1;
thus ( ( omf F ) . (( ( ovf F ) . (( 1. F ),a) ),a) ) = ( ( ( ovf F ) . (( 1. F ),a) ) * a )
.= ( a * ( ( ovf F ) . (( 1. F ),a) ) )
.= ( 1. F ) by A1;
end;
