environ
vocabularies XBOOLE_0,SUBSET_1,NUMBERS,REAL_1,FUNCT_1,NAT_1,PARTFUN1,ORDINAL1,RELAT_1,TARSKI,XREAL_0,VALUED_1,ORDINAL4,ARYTM_1,COMPLEX1,ARYTM_3,CARD_1,SEQ_1,PBOOLE,XXREAL_0,SEQ_2,ORDINAL2,FCONT_1,SEQFUNC;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,RFUNCT_1,VALUED_1,SEQ_1,SEQ_2,FCONT_1,LIMFUNC1,CKB1,CKB2,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB31;
definitions TARSKI,XBOOLE_0,VALUED_1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB31;
theorems FUNCT_1,PARTFUN1,TARSKI,RFUNCT_1,SEQ_1,SEQ_2,SEQ_4,ZFMISC_1,RFUNCT_2,FCONT_1,FUNCT_2,RELAT_1,XREAL_0,XBOOLE_0,XBOOLE_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,RELSET_1,CKB3,CKB4,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31;
schemes CLASSES1,SEQ_1,CKB5;
registrations XBOOLE_0,ORDINAL1,RELSET_1,NUMBERS,XREAL_0,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,PARTFUN1;
constructors PARTFUN1,FUNCOP_1,REAL_1,COMPLEX1,SEQ_2,RFUNCT_1,FCONT_1,LIMFUNC1,VALUED_1,SEQ_1,RELSET_1,CKB2,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB31;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve D for non  empty set;
reserve n for (Element of ( NAT ));
reserve H for (Functional_Sequence of D,( REAL ));
reserve x for (Element of D);
reserve S1 for Real_Sequence;
reserve S2 for Real_Sequence;
definition
let D;
let H;
let x;
func H # x -> Real_Sequence means 
:Def11: (for n holds ( it . n ) = ( ( H . n ) . x ));
existence
proof
deffunc U((Element of ( NAT ))) = ( ( H . $1 ) . x );
thus (ex f being Real_Sequence st (for n holds ( f . n ) = U(n))) from SEQ_1:sch 1;
end;
uniqueness
proof
let S1;
let S2;
assume that
A1: (for n holds ( S1 . n ) = ( ( H . n ) . x ))
and
A2: (for n holds ( S2 . n ) = ( ( H . n ) . x ));
now
let n;
( S1 . n ) = ( ( H . n ) . x ) by A1;
hence ( S1 . n ) = ( S2 . n ) by A2;
end;
hence thesis by FUNCT_2:63;
end;
end;
