environ
vocabularies ANALMETR,SUBSET_1,DIRAF,ANALOAF,SYMSP_1,CONAFFM;
notations STRUCT_0,ANALOAF,AFF_1,ANALMETR,CKB1,CKB2,CKB3,CKB4,CKB5;
definitions CKB1,CKB2,CKB3,CKB4,CKB5;
theorems AFF_1,ANALMETR,DIRAF,CKB1,CKB2,CKB3,CKB4,CKB5;
registrations ANALMETR;
constructors AFF_1,ANALMETR,CKB1,CKB2,CKB3,CKB4,CKB5;
begin
reserve X for OrtAfPl;
reserve o for (Element of X);
reserve a for (Element of X);
reserve a1 for (Element of X);
reserve b for (Element of X);
reserve b1 for (Element of X);
reserve c for (Element of X);
reserve c1 for (Element of X);
definition
let X;
attr X is  satisfying_LIN1
means
:Def6: (for o holds (for a holds (for a1 holds (for b holds (for b1 holds (for c holds (for c1 holds (((((((((((((((o <> a & o <> a1) & o <> b) & o <> b1) & o <> c) & o <> c1) & a <> b) & o,c _|_ o,c1) & o,a _|_ o,a1) & o,b _|_ o,b1) & (not  LIN o,c,a)) &  LIN o,a,b) &  LIN o,a1,b1) & a,c _|_ a1,c1) & a,a1 // b,b1) implies b,c _|_ b1,c1))))))));
end;
