environ
vocabularies NUMBERS,FINSET_1,CARD_1,XBOOLE_0,ARYTM_3,ARYTM_1,SUBSET_1,XXREAL_0,NAT_1,RELAT_1,FINSEQ_1,ZFMISC_1,FUNCT_1,TARSKI,FUNCT_4,HALLMAR1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,CARD_1,NUMBERS,XCMPLX_0,XXREAL_0,NAT_1,FINSET_1,FINSEQ_1,FUNCT_2,FUNCT_7,CKB7;
definitions TARSKI,XBOOLE_0,CKB7;
theorems CARD_2,SPPOL_1,EULER_1,XBOOLE_1,ZFMISC_1,FUNCT_1,PARTFUN1,FINSET_1,PENCIL_1,CARD_1,TARSKI,NAT_1,XBOOLE_0,FINSEQ_1,FUNCT_7,FINSEQ_3,FINSEQ_5,TAXONOM1,RELAT_1,FUNCT_2,ENUMSET1,FINSEQ_2,REALSET1,XREAL_1,XXREAL_0,ORDINAL1,CKB1,CKB5,CKB7,CKB8;
schemes NAT_1,FUNCT_2,XBOOLE_0,CKB2,CKB3;
registrations SUBSET_1,RELAT_1,FUNCT_1,FINSET_1,XXREAL_0,XREAL_0,FINSEQ_1,CHAIN_1,ORDINAL1,CARD_1,RELSET_1,CKB4,CKB6;
constructors XXREAL_0,REAL_1,NAT_1,FUNCT_7,RELSET_1,CKB7;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
(for F being  finite set holds (for A being (FinSequence of ( bool F )) holds (for J,K being set holds (J c= K implies ( union (A,J) ) c= ( union (A,K) )))))
proof
let F being  finite set;
let A being (FinSequence of ( bool F ));
let J being set,K being set;
assume A1: J c= K;
thus ( union (A,J) ) c= ( union (A,K) )
proof
let a being set;
assume a in ( union (A,J) );
then (ex j being set st ((j in J & j in ( dom A )) & a in ( A . j ))) by CKB7:def 1;
hence thesis by A1,CKB7:def 1;
end;

end;
