environ
vocabularies NUMBERS,SUBSET_1,MARGREL1,FUNCT_1,FINSEQ_2,FINSEQ_1,XBOOLEAN,TWOSCOMP,CARD_1,RELAT_1,ORDINAL4,TARSKI,XBOOLE_0,CLASSES1,FSM_1,FACIRC_1,CIRCUIT2,MSAFREE2,CIRCCOMB,STRUCT_0,GLIB_000,MSUALG_1,FUNCT_4,LATTICES,CIRCUIT1,PARTFUN1,ARYTM_3,GFACIRC1;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,NAT_1,RELAT_1,NUMBERS,STRUCT_0,FUNCT_1,FUNCT_2,FINSEQ_1,FINSEQ_2,MARGREL1,CLASSES1,BINARITH,MSUALG_1,MSAFREE2,CIRCUIT1,CIRCUIT2,CIRCCOMB,FACIRC_1,TWOSCOMP,CKB4,CKB6,CKB8,CKB10,CKB20,CKB21,CKB22,CKB23,CKB24;
definitions TARSKI,XBOOLE_0,CIRCUIT2,FACIRC_1,MSAFREE2,XBOOLEAN,CKB4,CKB6,CKB8,CKB10,CKB20,CKB21,CKB22,CKB23,CKB24;
theorems TARSKI,XBOOLE_0,XBOOLE_1,ZFMISC_1,ENUMSET1,RELAT_1,ORDINAL1,FUNCT_1,FUNCT_2,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_6,BINARITH,CIRCUIT1,CIRCUIT2,CIRCCOMB,FACIRC_1,TWOSCOMP,CIRCCMB2,FACIRC_2,XBOOLEAN,CLASSES1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33;
schemes FUNCT_2,FACIRC_1,CKB1,CKB2,CKB3;
registrations RELAT_1,MARGREL1,FINSEQ_2,CARD_3,STRUCT_0,CIRCCOMB,FACIRC_1,ORDINAL1,FINSEQ_1,FUNCT_1,MSAFREE2;
constructors ENUMSET1,XXREAL_0,CLASSES1,BINARITH,CIRCUIT1,CIRCUIT2,FACIRC_1,TWOSCOMP,NAT_1,RELSET_1,CKB4,CKB6,CKB8,CKB10,CKB20,CKB21,CKB22,CKB23,CKB24;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
theorem
Th22: (for x,y,z being non  pair set holds ( InputVertices ( GFA0CarryStr (x,y,z) ) ) = { x,y,z })
proof
let x being non  pair set;
let y being non  pair set;
let z being non  pair set;
set f1 = ( and2 );
set f2 = ( and2 );
set f3 = ( and2 );
set f4 = ( or3 );
set xy = [ <* x,y *>,f1 ];
set yz = [ <* y,z *>,f2 ];
set zx = [ <* z,x *>,f3 ];
set Cxy = ( 1GateCircStr (<* x,y *>,f1) );
set Cyz = ( 1GateCircStr (<* y,z *>,f2) );
set Czx = ( 1GateCircStr (<* z,x *>,f3) );
set M = ( GFA0CarryStr (x,y,z) );
set MI = ( GFA0CarryIStr (x,y,z) );
set S = ( 1GateCircStr (<* xy,yz,zx *>,f4) );
A1: (( InputVertices Cxy ) = { x,y } & ( InputVertices Cyz ) = { y,z }) by FACIRC_1:40;
A2: ( InputVertices Czx ) = { z,x } by FACIRC_1:40;
A3: ( InputVertices S ) = { xy,yz,zx } by FACIRC_1:42;
A4: ( InnerVertices S ) is Relation by FACIRC_1:38;
A5: (( InnerVertices Cxy ) = { xy } & ( InnerVertices Cyz ) = { yz }) by CIRCCOMB:42;
Cxy tolerates Cyz by CIRCCOMB:47;
then A6: (( InnerVertices Czx ) = { zx } & ( InnerVertices ( Cxy +* Cyz ) ) = ( { xy } \/ { yz } )) by A5,CIRCCOMB:11,CIRCCOMB:42;
( Cxy +* Cyz ) tolerates Czx by CIRCCOMB:47;
then ( InnerVertices MI ) = ( ( { xy } \/ { yz } ) \/ { zx } ) by A6,CIRCCOMB:11
.= ( { xy,yz } \/ { zx } ) by ENUMSET1:1
.= { xy,yz,zx } by ENUMSET1:3;
then A7: ( ( InputVertices S ) \ ( InnerVertices MI ) ) = ( {} ) by A3,XBOOLE_1:37;
A8: (( InputVertices Cxy ) is  without_pairs & ( InputVertices Cyz ) is  without_pairs) by FACIRC_1:41;
then A9: (( InputVertices Czx ) is  without_pairs & ( InputVertices ( Cxy +* Cyz ) ) is  without_pairs) by FACIRC_1:9,FACIRC_1:41;
then ( InputVertices MI ) is  without_pairs by FACIRC_1:9;
then ( InputVertices M ) = ( ( InputVertices MI ) \/ ( ( InputVertices S ) \ ( InnerVertices MI ) ) ) by A4,FACIRC_1:6;
hence ( InputVertices M ) = ( ( InputVertices ( Cxy +* Cyz ) ) \/ ( InputVertices Czx ) ) by A9,A6,A7,FACIRC_1:7
.= ( ( ( InputVertices Cxy ) \/ ( InputVertices Cyz ) ) \/ ( InputVertices Czx ) ) by A8,A5,FACIRC_1:7
.= ( { x,y,y,z } \/ { z,x } ) by A1,A2,ENUMSET1:5
.= ( { y,y,x,z } \/ { z,x } ) by ENUMSET1:67
.= ( { y,x,z } \/ { z,x } ) by ENUMSET1:31
.= ( { x,y,z } \/ { z,x } ) by ENUMSET1:58
.= ( { x,y,z } \/ ( { z } \/ { x } ) ) by ENUMSET1:1
.= ( ( { x,y,z } \/ { z } ) \/ { x } ) by XBOOLE_1:4
.= ( ( { z,x,y } \/ { z } ) \/ { x } ) by ENUMSET1:59
.= ( { z,z,x,y } \/ { x } ) by ENUMSET1:4
.= ( { z,x,y } \/ { x } ) by ENUMSET1:31
.= ( { x,y,z } \/ { x } ) by ENUMSET1:59
.= { x,x,y,z } by ENUMSET1:4
.= { x,y,z } by ENUMSET1:31;
end;
