environ
vocabularies NUMBERS,SUBSET_1,MARGREL1,FUNCT_1,FINSEQ_2,FINSEQ_1,XBOOLEAN,TWOSCOMP,CARD_1,RELAT_1,ORDINAL4,TARSKI,XBOOLE_0,CLASSES1,FSM_1,FACIRC_1,CIRCUIT2,MSAFREE2,CIRCCOMB,STRUCT_0,GLIB_000,MSUALG_1,FUNCT_4,LATTICES,CIRCUIT1,PARTFUN1,ARYTM_3,GFACIRC1;
notations TARSKI,XBOOLE_0,ENUMSET1,SUBSET_1,NAT_1,RELAT_1,NUMBERS,STRUCT_0,FUNCT_1,FUNCT_2,FINSEQ_1,FINSEQ_2,MARGREL1,CLASSES1,BINARITH,MSUALG_1,MSAFREE2,CIRCUIT1,CIRCUIT2,CIRCCOMB,FACIRC_1,TWOSCOMP,CKB4,CKB6,CKB8,CKB10,CKB20,CKB21,CKB22,CKB23,CKB24,CKB39,CKB40,CKB41,CKB49,CKB50,CKB59,CKB60,CKB63,CKB64,CKB65,CKB66,CKB67;
definitions TARSKI,XBOOLE_0,CIRCUIT2,FACIRC_1,MSAFREE2,XBOOLEAN,CKB4,CKB6,CKB8,CKB10,CKB20,CKB21,CKB22,CKB23,CKB24,CKB39,CKB40,CKB41,CKB49,CKB50,CKB59,CKB60,CKB63,CKB64,CKB65,CKB66,CKB67;
theorems TARSKI,XBOOLE_0,XBOOLE_1,ZFMISC_1,ENUMSET1,RELAT_1,ORDINAL1,FUNCT_1,FUNCT_2,FINSEQ_1,FINSEQ_2,FINSEQ_3,FINSEQ_6,BINARITH,CIRCUIT1,CIRCUIT2,CIRCCOMB,FACIRC_1,TWOSCOMP,CIRCCMB2,FACIRC_2,XBOOLEAN,CLASSES1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79;
schemes FUNCT_2,FACIRC_1,CKB1,CKB2,CKB3;
registrations RELAT_1,MARGREL1,FINSEQ_2,CARD_3,STRUCT_0,CIRCCOMB,FACIRC_1,ORDINAL1,FINSEQ_1,FUNCT_1,MSAFREE2;
constructors ENUMSET1,XXREAL_0,CLASSES1,BINARITH,CIRCUIT1,CIRCUIT2,FACIRC_1,TWOSCOMP,NAT_1,RELSET_1,CKB4,CKB6,CKB8,CKB10,CKB20,CKB21,CKB22,CKB23,CKB24,CKB39,CKB40,CKB41,CKB49,CKB50,CKB59,CKB60,CKB63,CKB64,CKB65,CKB66,CKB67;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
theorem
Th61: (for x,y,z being set holds (((x <> [ <* y,z *>,( and2a ) ] & y <> [ <* z,x *>,( and2 ) ]) & z <> [ <* x,y *>,( and2c ) ]) implies (for s being (State of ( GFA1CarryCirc (x,y,z) )) holds (for a1,a2,a3 being (Element of ( BOOLEAN )) holds (((a1 = ( s . x ) & a2 = ( s . y )) & a3 = ( s . z )) implies (((( ( Following (s,2) ) . ( GFA1CarryOutput (x,y,z) ) ) = ( ( ( a1 '&' ( 'not' a2 ) ) 'or' ( ( 'not' a2 ) '&' a3 ) ) 'or' ( a3 '&' a1 ) ) & ( ( Following (s,2) ) . [ <* x,y *>,( and2c ) ] ) = ( a1 '&' ( 'not' a2 ) )) & ( ( Following (s,2) ) . [ <* y,z *>,( and2a ) ] ) = ( ( 'not' a2 ) '&' a3 )) & ( ( Following (s,2) ) . [ <* z,x *>,( and2 ) ] ) = ( a3 '&' a1 )))))))
proof
set f1 = ( and2c );
set f2 = ( and2a );
set f3 = ( and2 );
let x being set;
let y being set;
let z being set;
assume that
A1: ((x <> [ <* y,z *>,f2 ] & y <> [ <* z,x *>,f3 ]) & z <> [ <* x,y *>,f1 ]);
set S = ( GFA1CarryStr (x,y,z) );
reconsider x9 = x,y9 = y,z9 = z as (Vertex of S) by CKB74:1;
let s being (State of ( GFA1CarryCirc (x,y,z) ));
y in ( InputVertices S ) by A1,CKB76:1;
then A2: ( ( Following s ) . y9 ) = ( s . y ) by CIRCUIT2:def 5;
z in ( InputVertices S ) by A1,CKB76:1;
then A3: ( ( Following s ) . z9 ) = ( s . z ) by CIRCUIT2:def 5;
set xy = [ <* x,y *>,f1 ];
set yz = [ <* y,z *>,f2 ];
set zx = [ <* z,x *>,f3 ];
A4: ( Following (s,2) ) = ( Following ( Following s ) ) by FACIRC_1:15;
let a1 being (Element of ( BOOLEAN ));
let a2 being (Element of ( BOOLEAN ));
let a3 being (Element of ( BOOLEAN ));
assume that
A5: ((a1 = ( s . x ) & a2 = ( s . y )) & a3 = ( s . z ));
A6: ( ( Following s ) . zx ) = ( a3 '&' a1 ) by A5,CKB78:1;
(( ( Following s ) . xy ) = ( a1 '&' ( 'not' a2 ) ) & ( ( Following s ) . yz ) = ( ( 'not' a2 ) '&' a3 )) by A5,CKB78:1;
hence ( ( Following (s,2) ) . ( GFA1CarryOutput (x,y,z) ) ) = ( ( ( a1 '&' ( 'not' a2 ) ) 'or' ( ( 'not' a2 ) '&' a3 ) ) 'or' ( a3 '&' a1 ) ) by A4,A6,CKB79:1;
x in ( InputVertices S ) by A1,CKB76:1;
then ( ( Following s ) . x9 ) = ( s . x ) by CIRCUIT2:def 5;
hence thesis by A5,A2,A3,A4,CKB78:1;
end;
