environ
vocabularies WAYBEL_0,SUBSET_1,XBOOLE_0,ORDERS_2,FUNCT_1,RELAT_1,TARSKI,NUMBERS,FUNCT_7,TREES_2,RELAT_2,XXREAL_0,STRUCT_0,ORDINAL2,LATTICES,ORDERS_1,ZFMISC_1,YELLOW_0,EQREL_1,REWRITE1,FUNCOP_1,LATTICE3,SEQM_3,WAYBEL_2,WAYBEL_3,CARD_FIL,SETFAM_1,ARYTM_3,CARD_1,NAT_1,ORDINAL1,YELLOW_8,FINSET_1,INT_2,YELLOW_1,FUNCT_3,LATTICE2,ARYTM_0,WAYBEL_5,PBOOLE,YELLOW_2,FUNCT_6,CARD_3,WAYBEL_6;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,NAT_1,FINSET_1,RELAT_1,ORDINAL1,RELAT_2,ORDERS_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,DOMAIN_1,FUNCOP_1,STRUCT_0,ORDERS_2,CARD_3,LATTICE3,FUNCT_3,FUNCT_6,PBOOLE,YELLOW_0,YELLOW_1,WAYBEL_0,WAYBEL_1,YELLOW_2,YELLOW_4,WAYBEL_2,WAYBEL_3,WAYBEL_4,WAYBEL_5,YELLOW_7,FUNCT_7,XXREAL_0,CKB2,CKB3,CKB12;
definitions TARSKI,RELAT_1,RELAT_2,LATTICE3,WAYBEL_0,WAYBEL_1,WAYBEL_2,WAYBEL_5,FUNCT_1,ORDERS_3,XBOOLE_0,SUBSET_1,STRUCT_0,CKB12;
theorems WAYBEL_3,TARSKI,YELLOW_0,ZFMISC_1,WAYBEL_0,ORDERS_2,WAYBEL_4,FUNCT_2,FUNCT_1,LATTICE3,NAT_1,WAYBEL_1,YELLOW_1,YELLOW_5,WAYBEL_2,YELLOW_2,WAYBEL_5,CARD_3,FUNCT_6,YELLOW_7,ORDERS_1,RELAT_2,FUNCT_3,YELLOW_4,YELLOW_3,FUNCOP_1,RELAT_1,RELSET_1,ORDINAL1,XBOOLE_0,XBOOLE_1,FUNCT_7,CARD_1,PARTFUN1,CKB6,CKB7,CKB8,CKB10,CKB11,CKB12,CKB13,CKB14,CKB16,CKB17;
schemes FUNCT_1,FINSET_1,CLASSES1,NAT_1,FUNCT_2,YELLOW_3,SUBSET_1,CKB1;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,FUNCOP_1,FINSET_1,XREAL_0,PBOOLE,STRUCT_0,ORDERS_2,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_1,WAYBEL_1,YELLOW_4,WAYBEL_2,WAYBEL_3,WAYBEL_5,YELLOW_7,ORDINAL1,RELSET_1,XXREAL_0,CARD_1,CKB4,CKB5,CKB9,CKB15;
constructors SETFAM_1,XXREAL_0,NAT_1,FUNCT_7,BORSUK_1,PRALG_2,ORDERS_3,WAYBEL_1,YELLOW_4,WAYBEL_2,WAYBEL_3,WAYBEL_4,WAYBEL_5,RELSET_1,CKB2,CKB3,CKB12;
requirements NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve x for set;
reserve y for set;
reserve Y for set;
reserve Z for set;
reserve L for LATTICE;
theorem
Th9: (for L being  complete LATTICE holds (for X being  Open  upper (Subset of L) holds (for x being (Element of L) holds (x in ( X ` ) implies (ex m being (Element of L) st (x <= m & m is_maximal_in ( X ` )))))))
proof
let L being  complete LATTICE;
let X being  Open  upper (Subset of L);
let x being (Element of L);
set A = { C where C is (Chain of L): (C c= ( X ` ) & x in C) };
reconsider x1 = { x } as (Chain of L) by ORDERS_2:8;
A1: (for Z being set holds (((Z <> ( {} ) & Z c= A) & Z is  c=-linear) implies ( union Z ) in A))
proof
let Z being set;
assume that
A2: Z <> ( {} )
and
A3: Z c= A
and
A4: Z is  c=-linear;
now
let Y;
assume Y in Z;
then Y in A by A3;
then (ex C being (Chain of L) st ((Y = C & C c= ( X ` )) & x in C));
hence Y c= (the carrier of L);
end;
then reconsider UZ = ( union Z ) as (Subset of L) by ZFMISC_1:76;
(the InternalRel of L) is_strongly_connected_in UZ
proof
let a being set;
let b being set;
assume that
A5: a in UZ
and
A6: b in UZ;
consider az being set such that A7: a in az and A8: az in Z by A5,TARSKI:def 4;
consider bz being set such that A9: b in bz and A10: bz in Z by A6,TARSKI:def 4;
az,bz are_c=-comparable  by A4,A8,A10,ORDINAL1:def 8;
then A11: (az c= bz or bz c= az) by XBOOLE_0:def 9;
bz in A by A3,A10;
then A12: (ex C being (Chain of L) st ((bz = C & C c= ( X ` )) & x in C));
az in A by A3,A8;
then A13: (ex C being (Chain of L) st ((az = C & C c= ( X ` )) & x in C));
reconsider bz as (Chain of L) by A12;
reconsider az as (Chain of L) by A13;
((the InternalRel of L) is_strongly_connected_in az & (the InternalRel of L) is_strongly_connected_in bz) by ORDERS_2:def 7;
hence thesis by A7,A9,A11,RELAT_2:def 7;
end;
then reconsider UZ as (Chain of L) by ORDERS_2:def 7;
A14:now
let Y;
assume Y in Z;
then Y in A by A3;
then (ex C being (Chain of L) st ((Y = C & C c= ( X ` )) & x in C));
hence Y c= ( X ` );
end;
set Y = the (Element of Z);
Y in Z by A2;
then Y in A by A3;
then (ex C being (Chain of L) st ((Y = C & C c= ( X ` )) & x in C));
then A15: x in UZ by A2,TARSKI:def 4;
UZ c= ( X ` ) by A14,ZFMISC_1:76;
hence thesis by A15;
end;
assume x in ( X ` );
then A16: x1 c= ( X ` ) by ZFMISC_1:31;
x in x1 by ZFMISC_1:31;
then x1 in A by A16;
then consider Y1 being set such that A17: Y1 in A and A18: (for Z holds ((Z in A & Z <> Y1) implies (not Y1 c= Z))) by A1,ORDERS_1:67;
consider Y being (Chain of L) such that A19: Y = Y1 and A20: Y c= ( X ` ) and A21: x in Y by A17;
set m = ( sup Y );
m is_>=_than Y by YELLOW_0:32;
then A22: x <= m by A21,LATTICE3:def 9;
A23: m is_>=_than Y by YELLOW_0:32;
A24:now
given y being (Element of L) such that
A25: y in ( X ` )
and
A26: y > m;

A27:now
assume y in Y;
then y <= m by A23,LATTICE3:def 9;
hence contradiction by A26,ORDERS_2:6;
end;
set Y2 = ( Y \/ { y } );
A28: m <= y by A26,ORDERS_2:def 6;
(the InternalRel of L) is_strongly_connected_in Y2
proof
let a being set;
let b being set;
assume A29: (a in Y2 & b in Y2);
per cases  by A29,XBOOLE_0:def 3;
suppose A30: (a in Y & b in Y);

(the InternalRel of L) is_strongly_connected_in Y by ORDERS_2:def 7;
hence thesis by A30,RELAT_2:def 7;
end;
suppose A31: (a in Y & b in { y });

then reconsider a1 = a as (Element of L);
reconsider b1 = b as (Element of L) by A31;
(b1 = y & a1 <= m) by A23,A31,LATTICE3:def 9,TARSKI:def 1;
then a1 <= b1 by A28,ORDERS_2:3;
hence thesis by ORDERS_2:def 5;
end;
suppose A32: (a in { y } & b in Y);

then reconsider a1 = b as (Element of L);
reconsider b1 = a as (Element of L) by A32;
(b1 = y & a1 <= m) by A23,A32,LATTICE3:def 9,TARSKI:def 1;
then a1 <= b1 by A28,ORDERS_2:3;
hence thesis by ORDERS_2:def 5;
end;
suppose A33: (a in { y } & b in { y });

then reconsider a1 = a as (Element of L);
A34: a1 <= a1;
(a = y & b = y) by A33,TARSKI:def 1;
hence thesis by A34,ORDERS_2:def 5;
end;
end;
then reconsider Y2 as (Chain of L) by ORDERS_2:def 7;
{ y } c= ( X ` ) by A25,ZFMISC_1:31;
then A35: Y2 c= ( X ` ) by A20,XBOOLE_1:8;
y in { y } by TARSKI:def 1;
then A36: y in Y2 by XBOOLE_0:def 3;
x in Y2 by A21,XBOOLE_0:def 3;
then Y2 in A by A35;
hence contradiction by A18,A19,A27,A36,XBOOLE_1:7;
end;
now
assume m in X;
then consider y being (Element of L) such that A37: y in X and A38: y << m by CKB12:def 1;
consider d being (Element of L) such that A39: d in Y and A40: y <= d by A21,A38,WAYBEL_3:def 1;
d in X by A37,A40,WAYBEL_0:def 20;
hence contradiction by A20,A39,XBOOLE_0:def 5;
end;
then m in ( X ` ) by XBOOLE_0:def 5;
then m is_maximal_in ( X ` ) by A24,WAYBEL_4:55;
hence thesis by A22;
end;
