environ
vocabularies XBOOLE_0,TARSKI,SUBSET_1,ZFMISC_1,SETFAM_1;
notations TARSKI,XBOOLE_0,ENUMSET1,ZFMISC_1,SUBSET_1,CKB1,CKB13,CKB14,CKB23,CKB24;
definitions TARSKI,XBOOLE_0,SUBSET_1,CKB1,CKB13,CKB14,CKB23,CKB24;
theorems TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ENUMSET1,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24;
schemes XBOOLE_0,SUBSET_1;
registrations XBOOLE_0,SUBSET_1;
constructors TARSKI,ENUMSET1,SUBSET_1,CKB1,CKB13,CKB14,CKB23,CKB24;
requirements SUBSET,BOOLE;
begin
reserve X for set;
reserve Y for set;
reserve Z for set;
reserve Z1 for set;
reserve Z2 for set;
reserve x for set;
reserve SFX for set;
reserve SFY for set;
definition
let SFX;
let SFY;
func DIFFERENCE (SFX,SFY) means 
:Def6: (Z in it iff (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y )))));
existence
proof
defpred X[ set ]
 means
(ex Z being set st ($1 = Z & (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y ))))));
consider XX being set such that A15: (for x holds (x in XX iff (x in ( bool ( union SFX ) ) & X[ x ]))) from XBOOLE_0:sch 1;
take XX;
(for Z holds (Z in XX iff (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y ))))))
proof
let Z;
A16:now
given X,Y such that
A17: X in SFX
and
A18: Y in SFY
and
A19: Z = ( X \ Y );

X c= ( union SFX ) by A17,ZFMISC_1:74;
then Z c= ( union SFX ) by A19,XBOOLE_1:1;
hence Z in XX by A15,A17,A18,A19;
end;
now
assume Z in XX;
then (ex Z1 st (Z = Z1 & (ex X st (ex Y st ((X in SFX & Y in SFY) & Z1 = ( X \ Y )))))) by A15;
hence (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y ))));
end;
hence thesis by A16;
end;
hence thesis;
end;
uniqueness
proof
let Z1 being set;
let Z2 being set;
assume that
A20: (for Z holds (Z in Z1 iff (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y ))))))
and
A21: (for Z holds (Z in Z2 iff (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y ))))));
now
let Z;
(Z in Z1 iff (ex X st (ex Y st ((X in SFX & Y in SFY) & Z = ( X \ Y ))))) by A20;
hence (Z in Z1 iff Z in Z2) by A21;
end;
hence thesis by TARSKI:1;
end;
end;
