environ
vocabularies NUMBERS,CARD_1,ARYTM_3,RELAT_1,XCMPLX_0,ORDINAL1,ARYTM_1,SUBSET_1,COMPLEX1,SQUARE_1,XXREAL_0,COMPLFLD,HAHNBAN1,GROUP_1,SUPINF_2,MESFUNC1,XBOOLE_0,VECTSP_1,HAHNBAN,FUNCT_1,RLVECT_1,ALGSTR_0,MSSUBFAM,STRUCT_0,UNIALG_1,ZFMISC_1,VECTSP10,TARSKI,RLSUB_1,GROUP_6,BILINEAR,XREAL_0,REAL_1,HERMITAN;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,REAL_1,STRUCT_0,ALGSTR_0,FUNCT_1,RLVECT_1,BINOP_1,GROUP_1,VECTSP_1,RELSET_1,FUNCT_2,SQUARE_1,COMPLEX1,VECTSP_4,COMPLFLD,HAHNBAN1,VECTSP10,BILINEAR,GRCAT_1,CKB17,CKB21,CKB26,CKB42,CKB46,CKB48,CKB49,CKB50,CKB58,CKB63,CKB71,CKB92,CKB103,CKB114;
definitions HAHNBAN1,TARSKI,XBOOLE_0,VECTSP_4,VECTSP10,BILINEAR,FUNCT_1,SQUARE_1,BINOP_1,COMPLEX1,VECTSP_1,ALGSTR_0,GRCAT_1,CKB17,CKB26,CKB42,CKB46,CKB48,CKB49,CKB50,CKB71,CKB92,CKB103,CKB114;
theorems COMPLEX1,SQUARE_1,ABSVALUE,COMPLFLD,XREAL_0,FUNCT_2,HAHNBAN1,VECTSP_1,RLVECT_1,VECTSP_4,VECTSP_6,TARSKI,VECTSP10,BILINEAR,DOMAIN_1,ZFMISC_1,FUNCT_1,XCMPLX_1,XREAL_1,BINOP_1,XXREAL_0,FUNCOP_1,STRUCT_0,GRCAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB26,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB71,CKB77,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101,CKB102,CKB103,CKB106,CKB107,CKB108,CKB109,CKB110,CKB111,CKB112,CKB113,CKB114,CKB115;
schemes FUNCT_2,BINOP_1;
registrations XBOOLE_0,RELSET_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,SQUARE_1,MEMBERED,STRUCT_0,VECTSP_1,COMPLFLD,HAHNBAN1,VECTSP10,BILINEAR,CKB18,CKB19,CKB20,CKB22,CKB23,CKB24,CKB25,CKB27,CKB28,CKB29,CKB30,CKB31,CKB44,CKB45,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB59,CKB60,CKB61,CKB62,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB72,CKB73,CKB74,CKB75,CKB76,CKB78,CKB79,CKB104,CKB105,CKB116,CKB117;
constructors REAL_1,SQUARE_1,BINOP_2,BORSUK_1,BILINEAR,FUNCOP_1,SUPINF_1,CKB17,CKB26,CKB42,CKB46,CKB48,CKB49,CKB50,CKB71,CKB92,CKB103,CKB114;
requirements NUMERALS,SUBSET,REAL,BOOLE,ARITHM;
begin
definition
let V being (VectSp of ( F_Complex ));
let W being (VectSp of ( F_Complex ));
let f being (sesquilinear-Form of V,W);
func Q*Form f -> (sesquilinear-Form of ( VectQuot (V,( LKer f )) ),( VectQuot (W,( RKer ( f *' ) )) )) means 
:Def12: (for A being (Vector of ( VectQuot (V,( LKer f )) )) holds (for B being (Vector of ( VectQuot (W,( RKer ( f *' ) )) )) holds (for v being (Vector of V) holds (for w being (Vector of W) holds ((A = ( v + ( LKer f ) ) & B = ( w + ( RKer ( f *' ) ) )) implies ( it . (A,B) ) = ( f . (v,w) ))))));
existence
proof
set K = ( F_Complex );
set L = ( LKer f );
set vq = ( VectQuot (V,L) );
set Cv = ( CosetSet (V,L) );
set aCv = ( addCoset (V,L) );
set mCv = ( lmultCoset (V,L) );
set R = ( RKer ( f *' ) );
set wq = ( VectQuot (W,R) );
set Cw = ( CosetSet (W,R) );
set aCw = ( addCoset (W,R) );
set mCw = ( lmultCoset (W,R) );
defpred P[ set,set,set ]
 means
(for v being (Vector of V) holds (for w being (Vector of W) holds (($1 = ( v + L ) & $2 = ( w + R )) implies $3 = ( f . (v,w) ))));
A1: ( rightker f ) = ( rightker ( f *' ) ) by CKB110:1;
A2:now
let A being (Vector of vq);
let B being (Vector of wq);
consider a being (Vector of V) such that A3: A = ( a + L ) by VECTSP10:22;
consider b being (Vector of W) such that A4: B = ( b + R ) by VECTSP10:22;
take y = ( f . (a,b) );
now
let a1 being (Vector of V);
let b1 being (Vector of W);
assume A = ( a1 + L );
then a in ( a1 + L ) by A3,VECTSP_4:44;
then consider vv being (Vector of V) such that A5: vv in L and A6: a = ( a1 + vv ) by VECTSP_4:42;
vv in (the carrier of L) by A5,STRUCT_0:def 5;
then vv in ( leftker f ) by BILINEAR:def 18;
then A7: (ex aa being (Vector of V) st (aa = vv & (for w0 being (Vector of W) holds ( f . (aa,w0) ) = ( 0. K ))));
assume B = ( b1 + R );
then b in ( b1 + R ) by A4,VECTSP_4:44;
then consider ww being (Vector of W) such that A8: ww in R and A9: b = ( b1 + ww ) by VECTSP_4:42;
ww in (the carrier of R) by A8,STRUCT_0:def 5;
then ww in ( rightker ( f *' ) ) by BILINEAR:def 19;
then A10: (ex bb being (Vector of W) st (bb = ww & (for v0 being (Vector of V) holds ( f . (v0,bb) ) = ( 0. K )))) by A1;
thus y = ( ( ( f . (a1,b1) ) + ( f . (a1,ww) ) ) + ( ( f . (vv,b1) ) + ( f . (vv,ww) ) ) ) by A6,A9,BILINEAR:28
.= ( ( ( f . (a1,b1) ) + ( 0. K ) ) + ( ( f . (vv,b1) ) + ( f . (vv,ww) ) ) ) by A10
.= ( ( ( f . (a1,b1) ) + ( 0. K ) ) + ( ( 0. K ) + ( f . (vv,ww) ) ) ) by A7
.= ( ( f . (a1,b1) ) + ( ( 0. K ) + ( f . (vv,ww) ) ) ) by RLVECT_1:def 4
.= ( ( f . (a1,b1) ) + ( f . (vv,ww) ) ) by RLVECT_1:4
.= ( ( f . (a1,b1) ) + ( 0. K ) ) by A7
.= ( f . (a1,b1) ) by RLVECT_1:def 4;
end;
hence P[ A,B,y ];
end;
consider ff being (Function of [: (the carrier of vq),(the carrier of wq) :],(the carrier of K)) such that A11: (for A being (Vector of vq) holds (for B being (Vector of wq) holds P[ A,B,( ff . (A,B) ) ])) from BINOP_1:sch 3(A2);
reconsider ff as (Form of vq,wq);
A12: Cv = (the carrier of vq) by VECTSP10:def 6;
A13:now
let ww being (Vector of wq);
consider w being (Vector of W) such that A14: ww = ( w + R ) by VECTSP10:22;
set ffw = ( FunctionalSAF (ff,ww) );
now
let A being (Vector of vq);
let r being (Element of K);
consider a being (Vector of V) such that A15: A = ( a + L ) by VECTSP10:22;
A16: ((the lmult of vq) = mCv & ( mCv . (r,A) ) = ( ( r * a ) + L )) by A12,A15,VECTSP10:def 5,VECTSP10:def 6;
thus ( ffw . ( r * A ) ) = ( ff . (( (the lmult of vq) . (r,A) ),ww) ) by BILINEAR:9
.= ( f . (( r * a ),w) ) by A11,A14,A16
.= ( r * ( f . (a,w) ) ) by BILINEAR:31
.= ( r * ( ff . (A,ww) ) ) by A11,A14,A15
.= ( r * ( ffw . A ) ) by BILINEAR:9;
end;
hence ffw is  homogeneous by HAHNBAN1:def 8;
end;
A17: Cw = (the carrier of wq) by VECTSP10:def 6;
A18:now
let vv being (Vector of vq);
consider v being (Vector of V) such that A19: vv = ( v + L ) by VECTSP10:22;
set ffv = ( FunctionalFAF (ff,vv) );
now
let A being (Vector of wq);
let r being (Element of K);
consider a being (Vector of W) such that A20: A = ( a + R ) by VECTSP10:22;
A21: ((the lmult of wq) = mCw & ( mCw . (r,A) ) = ( ( r * a ) + R )) by A17,A20,VECTSP10:def 5,VECTSP10:def 6;
thus ( ffv . ( r * A ) ) = ( ff . (vv,( (the lmult of wq) . (r,A) )) ) by BILINEAR:8
.= ( f . (v,( r * a )) ) by A11,A19,A21
.= ( ( r *' ) * ( f . (v,a) ) ) by CKB47:1
.= ( ( r *' ) * ( ff . (vv,A) ) ) by A11,A19,A20
.= ( ( r *' ) * ( ffv . A ) ) by BILINEAR:8;
end;
hence ffv is  cmplxhomogeneous by CKB17:def 1;
end;
A22:now
let ww being (Vector of wq);
consider w being (Vector of W) such that A23: ww = ( w + R ) by VECTSP10:22;
set ffw = ( FunctionalSAF (ff,ww) );
now
let A being (Vector of vq);
let B being (Vector of vq);
consider a being (Vector of V) such that A24: A = ( a + L ) by VECTSP10:22;
consider b being (Vector of V) such that A25: B = ( b + L ) by VECTSP10:22;
A26: ((the addF of vq) = aCv & ( aCv . (A,B) ) = ( ( a + b ) + L )) by A12,A24,A25,VECTSP10:def 3,VECTSP10:def 6;
thus ( ffw . ( A + B ) ) = ( ff . (( (the addF of vq) . (A,B) ),ww) ) by BILINEAR:9
.= ( f . (( a + b ),w) ) by A11,A23,A26
.= ( ( f . (a,w) ) + ( f . (b,w) ) ) by BILINEAR:26
.= ( ( ff . (A,ww) ) + ( f . (b,w) ) ) by A11,A23,A24
.= ( ( ff . (A,ww) ) + ( ff . (B,ww) ) ) by A11,A23,A25
.= ( ( ffw . A ) + ( ff . (B,ww) ) ) by BILINEAR:9
.= ( ( ffw . A ) + ( ffw . B ) ) by BILINEAR:9;
end;
hence ffw is  additive by GRCAT_1:def 8;
end;
now
let vv being (Vector of vq);
consider v being (Vector of V) such that A27: vv = ( v + L ) by VECTSP10:22;
set ffv = ( FunctionalFAF (ff,vv) );
now
let A being (Vector of wq);
let B being (Vector of wq);
consider a being (Vector of W) such that A28: A = ( a + R ) by VECTSP10:22;
consider b being (Vector of W) such that A29: B = ( b + R ) by VECTSP10:22;
A30: ((the addF of wq) = aCw & ( aCw . (A,B) ) = ( ( a + b ) + R )) by A17,A28,A29,VECTSP10:def 3,VECTSP10:def 6;
thus ( ffv . ( A + B ) ) = ( ff . (vv,( (the addF of wq) . (A,B) )) ) by BILINEAR:8
.= ( f . (v,( a + b )) ) by A11,A27,A30
.= ( ( f . (v,a) ) + ( f . (v,b) ) ) by BILINEAR:27
.= ( ( ff . (vv,A) ) + ( f . (v,b) ) ) by A11,A27,A28
.= ( ( ff . (vv,A) ) + ( ff . (vv,B) ) ) by A11,A27,A29
.= ( ( ffv . A ) + ( ff . (vv,B) ) ) by BILINEAR:8
.= ( ( ffv . A ) + ( ffv . B ) ) by BILINEAR:8;
end;
hence ffv is  additive by GRCAT_1:def 8;
end;
then reconsider ff as (sesquilinear-Form of vq,wq) by A22,A13,A18,CKB46:def 1,BILINEAR:def 11,BILINEAR:def 12,BILINEAR:def 14;
take ff;
thus thesis by A11;
end;
uniqueness
proof
set L = ( LKer f );
set vq = ( VectQuot (V,L) );
set R = ( RKer ( f *' ) );
set wq = ( VectQuot (W,R) );
let f1 being (sesquilinear-Form of vq,wq);
let f2 being (sesquilinear-Form of vq,wq);
assume that
A31: (for A being (Vector of vq) holds (for B being (Vector of wq) holds (for v being (Vector of V) holds (for w being (Vector of W) holds ((A = ( v + L ) & B = ( w + R )) implies ( f1 . (A,B) ) = ( f . (v,w) ))))))
and
A32: (for A being (Vector of vq) holds (for B being (Vector of wq) holds (for v being (Vector of V) holds (for w being (Vector of W) holds ((A = ( v + L ) & B = ( w + R )) implies ( f2 . (A,B) ) = ( f . (v,w) ))))));
now
let A being (Vector of vq);
let B being (Vector of wq);
consider a being (Vector of V) such that A33: A = ( a + L ) by VECTSP10:22;
consider b being (Vector of W) such that A34: B = ( b + R ) by VECTSP10:22;
thus ( f1 . (A,B) ) = ( f . (a,b) ) by A31,A33,A34
.= ( f2 . (A,B) ) by A32,A33,A34;
end;
hence thesis by BINOP_1:2;
end;
end;
