environ
vocabularies NUMBERS,REAL_3,FINSEQ_1,RELAT_1,TARSKI,VALUED_0,ORDINAL1,RFINSEQ,XXREAL_0,ARYTM_1,SUBSET_1,FUNCT_1,ARYTM_3,INT_1,ORDINAL4,XBOOLE_0,NAT_1,VALUED_1,CARD_3,BINOP_2,SETWISEO,BINOP_1,SETWOP_2,CARD_1,FINSOP_1,PARTFUN1,COMPLEX1,INT_2,PARTFUN3,XREAL_0,INT_6;
notations TARSKI,XBOOLE_0,SUBSET_1,INT_1,INT_2,ORDINAL1,NUMBERS,PARTFUN1,PARTFUN3,REAL_3,XXREAL_0,XREAL_0,FUNCT_1,VALUED_0,VALUED_1,BINOP_2,SETWISEO,RFINSEQ,BINOP_1,FINSEQ_1,SETWOP_2,RVSUM_1,XCMPLX_0,NAT_1,FINSOP_1;
definitions INT_2,XCMPLX_0,FINSEQ_1,FUNCT_1;
theorems INT_1,FUNCT_1,FINSEQ_1,RVSUM_1,NAT_1,SETWOP_2,FINSEQ_3,BINOP_2,SETWISEO,TARSKI,NAT_D,INT_2,XCMPLX_0,XCMPLX_1,XREAL_1,RFINSEQ,FINSEQ_5,FINSEQ_2,ABSVALUE,PARTFUN3,XBOOLE_0,XXREAL_0,ORDINAL1,XBOOLE_1,PARTFUN1,XREAL_0,WSIERP_1,VALUED_0,VALUED_1,COMPLEX1,CKB1,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB16,CKB17,CKB18;
schemes FINSEQ_1,NAT_1,INT_1;
registrations NUMBERS,XREAL_0,NAT_1,INT_1,RELAT_1,FINSEQ_1,RVSUM_1,XBOOLE_0,MEMBERED,BINOP_2,ORDINAL1,XXREAL_0,VALUED_0,VALUED_1,FUNCT_1,CARD_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB14,CKB15;
constructors FINSOP_1,RFINSEQ,INT_2,BINOP_2,REAL_1,SETWISEO,SETWOP_2,PARTFUN3,XXREAL_0,RVSUM_1,BINOP_1,RELSET_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
theorem
Th7: (for n,a,b being Integer holds ( ( a - b ) mod n ) = ( ( ( a mod n ) - ( b mod n ) ) mod n ))
proof
let n being Integer;
let a being Integer;
let b being Integer;
per cases ;
suppose A1: n = ( 0 );

hence ( ( a - b ) mod n ) = ( 0 ) by INT_1:def 10
.= ( ( ( a mod n ) - ( b mod n ) ) mod n ) by A1,INT_1:def 10;
end;
suppose A2: n <> ( 0 );

then A3: ( ( b mod n ) + ( ( b div n ) * n ) ) = ( ( b - ( ( b div n ) * n ) ) + ( ( b div n ) * n ) ) by INT_1:def 10;
( ( a mod n ) + ( ( a div n ) * n ) ) = ( ( a - ( ( a div n ) * n ) ) + ( ( a div n ) * n ) ) by A2,INT_1:def 10;
then ( ( a - b ) - ( ( a mod n ) - ( b mod n ) ) ) = ( ( ( a div n ) - ( b div n ) ) * n ) by A3;
then n divides ( ( a - b ) - ( ( a mod n ) - ( b mod n ) ) ) by INT_1:def 3;
then ( a - b ),( ( a mod n ) - ( b mod n ) ) are_congruent_mod n by INT_2:15;
hence thesis by NAT_D:64;
end;
end;
