environ
vocabularies NUMBERS,METRIC_1,SUBSET_1,XBOOLE_0,FUNCT_1,ZFMISC_1,REAL_1,COMPLEX1,ARYTM_1,XXREAL_0,ARYTM_3,PCOMPS_1,CARD_1,RELAT_1,RELAT_2,STRUCT_0,NAT_1,ORDINAL2,XXREAL_2,TARSKI,SEQ_2,SEQ_1,XREAL_0,ORDINAL1,VALUED_0,BHSP_3,METRIC_6;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,NUMBERS,XREAL_0,COMPLEX1,RELAT_1,FUNCT_1,FUNCT_2,DOMAIN_1,REAL_1,NAT_1,STRUCT_0,METRIC_1,SEQ_1,SEQ_2,VALUED_0,PCOMPS_1,TBSP_1,XXREAL_0,RECDEF_1,CKB6,CKB9,CKB10,CKB11,CKB12,CKB16,CKB17;
definitions TBSP_1,TARSKI,CKB6,CKB9,CKB10,CKB11,CKB12,CKB16,CKB17;
theorems ABSVALUE,TARSKI,BINOP_1,METRIC_1,FUNCT_1,FUNCT_2,SEQ_2,NAT_1,PCOMPS_1,SEQM_3,SEQ_4,TBSP_1,SUBSET_1,XREAL_0,XBOOLE_1,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,VALUED_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31;
schemes SEQ_1,BINOP_1;
registrations XBOOLE_0,ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,METRIC_1,VALUED_0,FUNCT_2;
constructors DOMAIN_1,XXREAL_0,REAL_1,NAT_1,COMPLEX1,SEQ_2,PCOMPS_1,BHSP_3,TBSP_1,SEQ_1,VALUED_1,PARTFUN1,RECDEF_1,SETFAM_1,RELSET_1,BINOP_2,RVSUM_1,CKB6,CKB9,CKB11,CKB12,CKB16,CKB17;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve k for (Element of ( NAT ));
reserve n for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
reserve m1 for (Element of ( NAT ));
reserve r for Real;
reserve X for non empty MetrSpace;
reserve S for (sequence of X);
reserve S1 for (sequence of X);
reserve Nseq for  increasing (sequence of ( NAT ));
theorem
((S is  Cauchy & S1 is (subsequence of S)) implies S1 is  Cauchy)
proof
assume that
A1: S is  Cauchy
and
A2: S1 is (subsequence of S);
consider Nseq such that A3: S1 = ( S * Nseq ) by A2,VALUED_0:def 17;
(for r holds (( 0 ) < r implies (ex m st (for n holds (for k holds ((m <= n & m <= k) implies ( dist (( S1 . n ),( S1 . k )) ) < r))))))
proof
let r;
assume ( 0 ) < r;
then consider m1 such that A4: (for n holds (for k holds ((m1 <= n & m1 <= k) implies ( dist (( S . n ),( S . k )) ) < r))) by A1,TBSP_1:def 4;
take m = m1;
(for n holds (for k holds ((m <= n & m <= k) implies ( dist (( S1 . n ),( S1 . k )) ) < r)))
proof
let n;
let k;
assume that
A5: m <= n
and
A6: m <= k;
k <= ( Nseq . k ) by SEQM_3:14;
then A7: m1 <= ( Nseq . k ) by A6,XXREAL_0:2;
( dom S ) = ( NAT ) by FUNCT_2:def 1;
then (( dom Nseq ) = ( NAT ) & ( Nseq . k ) in ( dom S )) by FUNCT_2:def 1;
then k in ( dom ( S * Nseq ) ) by FUNCT_1:11;
then A8: ( S1 . k ) = ( S . ( Nseq . k ) ) by A3,FUNCT_1:12;
( dom S ) = ( NAT ) by FUNCT_2:def 1;
then (( dom Nseq ) = ( NAT ) & ( Nseq . n ) in ( dom S )) by FUNCT_2:def 1;
then n in ( dom ( S * Nseq ) ) by FUNCT_1:11;
then A9: ( S1 . n ) = ( S . ( Nseq . n ) ) by A3,FUNCT_1:12;
n <= ( Nseq . n ) by SEQM_3:14;
then m1 <= ( Nseq . n ) by A5,XXREAL_0:2;
hence thesis by A4,A9,A7,A8;
end;
hence thesis;
end;
hence thesis by TBSP_1:def 4;
end;
