environ
vocabularies XBOOLE_0,ORDERS_2,SUBSET_1,TARSKI,FIN_TOPO,RCOMP_1,MARGREL1,XBOOLEAN,STRUCT_0,FUNCT_1,ZFMISC_1,PRE_TOPC,SETFAM_1,FINTOPO2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,DOMAIN_1,STRUCT_0,FUNCT_1,FUNCT_2,FIN_TOPO,ORDERS_2,PRE_TOPC,MARGREL1,CKB6,CKB7,CKB11,CKB15,CKB19,CKB24,CKB26,CKB27,CKB28,CKB29,CKB31,CKB33,CKB35;
definitions TARSKI,STRUCT_0,XBOOLE_0,SUBSET_1,XBOOLEAN,FIN_TOPO,CKB6,CKB7,CKB11,CKB15,CKB19,CKB26,CKB27,CKB28,CKB29,CKB31,CKB33,CKB35;
theorems TARSKI,SUBSET_1,FIN_TOPO,FUNCT_2,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35;
schemes DOMAIN_1,FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,PRE_TOPC,FIN_TOPO,CKB24,CKB25;
constructors DOMAIN_1,MARGREL1,PRE_TOPC,FIN_TOPO,RELSET_1,CKB6,CKB7,CKB11,CKB15,CKB19,CKB24,CKB26,CKB27,CKB28,CKB29,CKB31,CKB33,CKB35;
requirements SUBSET,BOOLE;
begin
reserve FMT for non  empty FMT_Space_Str;
reserve x for (Element of FMT);
reserve y for (Element of FMT);
reserve A for (Subset of FMT);
reserve V for (Subset of FMT);
theorem
Th23: (x in ( A ^Fos ) iff (x in A & (ex V st (V in ( U_FMT x ) & ( V \ { x } ) misses A))))
proof
thus (x in ( A ^Fos ) implies (x in A & (ex V st (V in ( U_FMT x ) & ( V \ { x } ) misses A))))
proof
assume x in ( A ^Fos );
then (ex y st ((y = x & y in A) & (ex V st (V in ( U_FMT y ) & ( V \ { y } ) misses A))));
hence thesis;
end;

assume (x in A & (ex V st (V in ( U_FMT x ) & ( V \ { x } ) misses A)));
hence thesis;
end;
