environ
vocabularies XBOOLE_0,ORDERS_2,SUBSET_1,TARSKI,FIN_TOPO,RCOMP_1,MARGREL1,XBOOLEAN,STRUCT_0,FUNCT_1,ZFMISC_1,PRE_TOPC,SETFAM_1,FINTOPO2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,DOMAIN_1,STRUCT_0,FUNCT_1,FUNCT_2,FIN_TOPO,ORDERS_2,PRE_TOPC,MARGREL1,CKB6,CKB7,CKB11,CKB15,CKB19,CKB24,CKB26,CKB27,CKB28,CKB29,CKB31,CKB33,CKB35,CKB37;
definitions TARSKI,STRUCT_0,XBOOLE_0,SUBSET_1,XBOOLEAN,FIN_TOPO,CKB6,CKB7,CKB11,CKB15,CKB19,CKB26,CKB27,CKB28,CKB29,CKB31,CKB33,CKB35,CKB37;
theorems TARSKI,SUBSET_1,FIN_TOPO,FUNCT_2,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48;
schemes DOMAIN_1,FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,PRE_TOPC,FIN_TOPO,CKB24,CKB25;
constructors DOMAIN_1,MARGREL1,PRE_TOPC,FIN_TOPO,RELSET_1,CKB6,CKB7,CKB11,CKB15,CKB19,CKB24,CKB26,CKB27,CKB28,CKB29,CKB31,CKB33,CKB35,CKB37;
requirements SUBSET,BOOLE;
begin
reserve FMT for non  empty FMT_Space_Str;
reserve x for (Element of FMT);
reserve A for (Subset of FMT);
theorem
(for x being (Element of FMT) holds (for A being (Subset of FMT) holds (x in ( A ^Fos ) iff (x in A & (not x in ( ( A \ { x } ) ^Fob ))))))
proof
let x being (Element of FMT);
let A being (Subset of FMT);
A1: ((x in A & (not x in ( ( A \ { x } ) ^Fob ))) implies x in ( A ^Fos ))
proof
assume that
A2: x in A
and
A3: (not x in ( ( A \ { x } ) ^Fob ));
consider V9 being (Subset of FMT) such that A4: V9 in ( U_FMT x ) and A5: V9 misses ( A \ { x } ) by A3;
V9 misses ( A /\ ( { x } ` ) ) by A5,SUBSET_1:13;
then ( V9 /\ ( A /\ ( { x } ` ) ) ) = ( {} ) by XBOOLE_0:def 7;
then ( ( V9 /\ ( { x } ` ) ) /\ A ) = ( {} ) by XBOOLE_1:16;
then ( ( V9 \ { x } ) /\ A ) = ( {} ) by SUBSET_1:13;
then ( V9 \ { x } ) misses A by XBOOLE_0:def 7;
hence thesis by A2,A4;
end;
(x in ( A ^Fos ) implies (x in A & (not x in ( ( A \ { x } ) ^Fob ))))
proof
assume A6: x in ( A ^Fos );
then consider V9 being (Subset of FMT) such that A7: V9 in ( U_FMT x ) and A8: ( V9 \ { x } ) misses A by CKB36:1;
( V9 /\ ( { x } ` ) ) misses A by A8,SUBSET_1:13;
then ( ( V9 /\ ( { x } ` ) ) /\ A ) = ( {} ) by XBOOLE_0:def 7;
then ( V9 /\ ( ( { x } ` ) /\ A ) ) = ( {} ) by XBOOLE_1:16;
then V9 misses ( ( { x } ` ) /\ A ) by XBOOLE_0:def 7;
then V9 misses ( A \ { x } ) by SUBSET_1:13;
hence thesis by A6,A7,CKB32:1,CKB36:1;
end;
hence thesis by A1;
end;
