environ
vocabularies PBOOLE,RELAT_1,XBOOLE_0,FUNCT_1,SUBSET_1,CARD_3,TARSKI,STRUCT_0,MSUALG_1,UNIALG_2,FINSEQ_1,MARGREL1,PARTFUN1,FUNCT_2,ZFMISC_1,QC_LANG1,SETFAM_1,EQREL_1,BINOP_1,LATTICES,XXREAL_2,MSUALG_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,STRUCT_0,RELAT_1,FUNCT_1,FUNCT_2,FINSEQ_1,SETFAM_1,FINSEQ_2,LATTICES,BINOP_1,CARD_3,PBOOLE,MSUALG_1,CKB4,CKB5,CKB6,CKB9,CKB10,CKB13,CKB14,CKB16,CKB17,CKB20;
definitions TARSKI,PBOOLE,LATTICES,XBOOLE_0,CKB5,CKB6,CKB9,CKB10,CKB13,CKB14,CKB16,CKB17,CKB20;
theorems TARSKI,FUNCT_1,FINSEQ_1,PBOOLE,CARD_3,MSUALG_1,FUNCT_2,ZFMISC_1,SETFAM_1,BINOP_1,LATTICES,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,FUNCOP_1,PARTFUN1,FINSEQ_2,CKB3,CKB5,CKB6,CKB9,CKB10,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB25;
schemes CLASSES1,BINOP_1,FUNCT_1,XBOOLE_0;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,PBOOLE,STRUCT_0,LATTICES,MSUALG_1,FINSEQ_1,FUNCT_2,PARTFUN1,RELSET_1,CKB1,CKB2,CKB7,CKB8,CKB11,CKB12,CKB22,CKB23,CKB24;
constructors SETFAM_1,BINOP_1,CARD_3,LATTICES,MSUALG_1,RELSET_1,CKB5,CKB6,CKB9,CKB10,CKB13,CKB14,CKB16,CKB17,CKB20;
requirements BOOLE,SUBSET;
begin
reserve x for set;
reserve S for non void non empty ManySortedSign;
reserve U0 for MSAlgebra over S;
reserve U1 for MSAlgebra over S;
reserve U2 for MSAlgebra over S;
theorem
((U0 is (MSSubAlgebra of U1) & U1 is (MSSubAlgebra of U2)) implies U0 is (MSSubAlgebra of U2))
proof
assume that
A1: U0 is (MSSubAlgebra of U1)
and
A2: U1 is (MSSubAlgebra of U2);
reconsider B0 = (the Sorts of U0) as (MSSubset of U1) by A1,CKB20:def 1;
A3: B0 is  opers_closed by A1,CKB20:def 1;
reconsider B1 = (the Sorts of U1) as (MSSubset of U2) by A2,CKB20:def 1;
A4: B1 is  opers_closed by A2,CKB20:def 1;
reconsider B19 = B1 as (MSSubset of U1) by PBOOLE:def 18;
A5: (the Charact of U1) = ( Opers (U2,B1) ) by A2,CKB20:def 1;
(the Sorts of U0) is (MSSubset of U1) by A1,CKB20:def 1;
then A6: (the Sorts of U0) c= (the Sorts of U1) by PBOOLE:def 18;
(the Sorts of U1) is (MSSubset of U2) by A2,CKB20:def 1;
then (the Sorts of U1) c= (the Sorts of U2) by PBOOLE:def 18;
then (the Sorts of U0) c= (the Sorts of U2) by A6,PBOOLE:13;
hence (the Sorts of U0) is (MSSubset of U2) by PBOOLE:def 18;
let B being (MSSubset of U2);
set O = (the Charact of U0);
set P = ( Opers (U2,B) );
A7: (the Charact of U0) = ( Opers (U1,B0) ) by A1,CKB20:def 1;
assume A8: B = (the Sorts of U0);
A9: (for o being (OperSymbol of S) holds B is_closed_on o)
proof
let o being (OperSymbol of S);
A10: B0 is_closed_on o by A3,CKB14:def 1;
A11: B1 is_closed_on o by A4,CKB14:def 1;
A12: ( Den (o,U1) ) = ( ( Opers (U2,B1) ) . o ) by A5,MSUALG_1:def 6
.= ( o /. B1 ) by CKB17:def 1
.= ( ( Den (o,U2) ) | ( ( ( B1 # ) * (the Arity of S) ) . o ) ) by A11,CKB16:def 1;
A13: ( ( ( B0 # ) * (the Arity of S) ) . o ) c= ( ( ( B19 # ) * (the Arity of S) ) . o ) by A6,CKB15:1;
( Den (o,U0) ) = ( ( Opers (U1,B0) ) . o ) by A7,MSUALG_1:def 6
.= ( o /. B0 ) by CKB17:def 1
.= ( ( ( Den (o,U2) ) | ( ( ( B1 # ) * (the Arity of S) ) . o ) ) | ( ( ( B0 # ) * (the Arity of S) ) . o ) ) by A10,A12,CKB16:def 1
.= ( ( Den (o,U2) ) | ( ( ( ( B1 # ) * (the Arity of S) ) . o ) /\ ( ( ( B0 # ) * (the Arity of S) ) . o ) ) ) by RELAT_1:71
.= ( ( Den (o,U2) ) | ( ( ( B0 # ) * (the Arity of S) ) . o ) ) by A13,XBOOLE_1:28;
then ( rng ( ( Den (o,U2) ) | ( ( ( B0 # ) * (the Arity of S) ) . o ) ) ) c= ( Result (o,U0) ) by RELAT_1:def 19;
then ( rng ( ( Den (o,U2) ) | ( ( ( B0 # ) * (the Arity of S) ) . o ) ) ) c= ( ( (the Sorts of U0) * (the ResultSort of S) ) . o ) by MSUALG_1:def 5;
hence thesis by A8,CKB13:def 1;
end;
hence B is  opers_closed by CKB14:def 1;
(for x holds (x in (the carrier' of S) implies ( O . x ) = ( P . x )))
proof
let x;
assume x in (the carrier' of S);
then reconsider o = x as (OperSymbol of S);
A14: B0 is_closed_on o by A3,CKB14:def 1;
A15: B1 is_closed_on o by A4,CKB14:def 1;
A16: ( Den (o,U1) ) = ( ( Opers (U2,B1) ) . o ) by A5,MSUALG_1:def 6
.= ( o /. B1 ) by CKB17:def 1
.= ( ( Den (o,U2) ) | ( ( ( B1 # ) * (the Arity of S) ) . o ) ) by A15,CKB16:def 1;
thus ( O . x ) = ( o /. B0 ) by A7,CKB17:def 1
.= ( ( ( Den (o,U2) ) | ( ( ( B1 # ) * (the Arity of S) ) . o ) ) | ( ( ( B0 # ) * (the Arity of S) ) . o ) ) by A14,A16,CKB16:def 1
.= ( ( Den (o,U2) ) | ( ( ( ( B1 # ) * (the Arity of S) ) . o ) /\ ( ( ( B0 # ) * (the Arity of S) ) . o ) ) ) by RELAT_1:71
.= ( ( Den (o,U2) ) | ( ( ( B # ) * (the Arity of S) ) . o ) ) by A6,A8,CKB15:1,XBOOLE_1:28
.= ( o /. B ) by A9,CKB16:def 1
.= ( P . x ) by CKB17:def 1;
end;
hence thesis by PBOOLE:3;
end;
