environ
vocabularies FUNCT_1,RELAT_1,XBOOLE_0,TARSKI,FUNCT_4,PARTFUN1,SUBSET_1,PBOOLE,STRUCT_0,MSUALG_1,MARGREL1,CATALG_1,PUA2MSS1,TREES_1,FINSEQ_1,INSTALG1,FUNCSDOM,MSUALG_6,PROB_2,CARD_3,ALGSPEC1;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,MSAFREE1,FINSEQ_1,PBOOLE,RELSET_1,PARTFUN1,FINSEQ_2,FUNCT_4,LANG1,FUNCT_2,STRUCT_0,CARD_3,MSUALG_1,PROB_2,PUA2MSS1,CIRCCOMB,MSUALG_6,INSTALG1,CATALG_1,CKB7,CKB24,CKB31,CKB39,CKB50;
definitions TARSKI,FUNCT_1,PARTFUN1,STRUCT_0,MSUALG_1,CIRCCOMB,PUA2MSS1,INSTALG1,XBOOLE_0,FUNCT_2,CKB7,CKB24,CKB31,CKB39,CKB50;
theorems RELAT_1,FUNCT_1,FUNCT_2,FUNCT_3,FUNCT_4,PARTFUN1,GRFUNC_1,FINSEQ_1,PBOOLE,LANG1,PUA2MSS1,FRECHET,INSTALG1,FUNCT_7,CIRCCOMB,RELSET_1,PROB_2,MSAFREE1,XBOOLE_0,XBOOLE_1,FINSEQ_2,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53;
schemes FUNCT_1;
registrations XBOOLE_0,RELAT_1,FUNCT_1,FUNCT_2,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_2,CIRCCOMB,MSUALG_6,INSTALG1,CATALG_1,RELSET_1,CKB38;
constructors MSAFREE1,CIRCCOMB,PUA2MSS1,MSUALG_6,CATALG_1,RELSET_1,CKB7,CKB24,CKB31,CKB39,CKB50;
requirements SUBSET,BOOLE;
begin
theorem
Th50: (for S1,S2 being non empty Signature holds ( S1 +* S2 ) is (Extension of S2))
proof
let S1 being non empty Signature,S2 being non empty Signature;
set S = ( S1 +* S2 );
set f1 = ( id (the carrier of S2) );
set g1 = ( id (the carrier' of S2) );
thus (( dom f1 ) = (the carrier of S2) & ( dom g1 ) = (the carrier' of S2)) by RELAT_1:45;
A1: ( rng g1 ) = (the carrier' of S2) by RELAT_1:45;
A2: (the carrier of S) = ( (the carrier of S1) \/ (the carrier of S2) ) by CIRCCOMB:def 2;
A3: (the carrier' of S) = ( (the carrier' of S1) \/ (the carrier' of S2) ) by CIRCCOMB:def 2;
( rng f1 ) = (the carrier of S2) by RELAT_1:45;
hence (( rng f1 ) c= (the carrier of S) & ( rng g1 ) c= (the carrier' of S)) by A1,A2,A3,XBOOLE_1:7;
A4: (the ResultSort of S) = ( (the ResultSort of S1) +* (the ResultSort of S2) ) by CIRCCOMB:def 2;
( dom (the ResultSort of S2) ) = (the carrier' of S2) by FUNCT_2:def 1;
then (the ResultSort of S2) = ( (the ResultSort of S) | (the carrier' of S2) ) by A4,FUNCT_4:25,GRFUNC_1:23;
then A5: (the ResultSort of S2) = ( (the ResultSort of S) * g1 ) by RELAT_1:65;
( rng (the ResultSort of S2) ) c= (the carrier of S2);
hence ( f1 * (the ResultSort of S2) ) = ( (the ResultSort of S) * g1 ) by A5,RELAT_1:53;
let o being set;
let p being Function;
assume that
A6: o in (the carrier' of S2)
and
A7: p = ( (the Arity of S2) . o );
A8: ( dom (the Arity of S2) ) = (the carrier' of S2) by FUNCT_2:def 1;
then p in ( rng (the Arity of S2) ) by A6,A7,FUNCT_1:def 3;
then p is (FinSequence of (the carrier of S2)) by FINSEQ_1:def 11;
then ( rng p ) c= (the carrier of S2) by FINSEQ_1:def 4;
hence ( f1 * p ) = p by RELAT_1:53
.= ( ( (the Arity of S1) +* (the Arity of S2) ) . o ) by A6,A7,A8,FUNCT_4:13
.= ( (the Arity of S) . o ) by CIRCCOMB:def 2
.= ( (the Arity of S) . ( g1 . o ) ) by A6,FUNCT_1:18;
end;
