environ
vocabularies TARSKI,XBOOLE_0;
notations TARSKI,XBOOLE_0,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
definitions TARSKI,XBOOLE_0,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
theorems TARSKI,XBOOLE_0,XBOOLE_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB98,CKB99,CKB100,CKB101;
schemes XBOOLE_0;
constructors TARSKI,XBOOLE_0,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
begin
reserve x for set;
reserve x1 for set;
reserve x2 for set;
reserve x3 for set;
reserve x4 for set;
reserve x5 for set;
reserve x6 for set;
reserve x7 for set;
reserve x8 for set;
reserve x9 for set;
reserve x10 for set;
theorem
{ x1,x2,x3,x4,x5,x6,x7,x8,x9,x10 } = ( { x1,x2,x3,x4,x5,x6,x7,x8,x9 } \/ { x10 } )
proof
now
let x;
A1: (x in { x10 } iff x = x10) by TARSKI:def 1;
((((((((((x = x1 or x = x2) or x = x3) or x = x4) or x = x5) or x = x6) or x = x7) or x = x8) or x = x9) or x = x10) iff (x in { x1,x2,x3,x4,x5,x6,x7,x8,x9 } or x = x10)) by CKB8:def 1;
hence (x in { x1,x2,x3,x4,x5,x6,x7,x8,x9,x10 } iff x in ( { x1,x2,x3,x4,x5,x6,x7,x8,x9 } \/ { x10 } )) by A1,CKB9:def 1,XBOOLE_0:def 3;
end;
hence thesis by TARSKI:1;
end;
