environ
vocabularies NUMBERS,ABIAN,RELAT_1,CARD_1,ARYTM_3,ORDERS_2,SUBSET_1,TARSKI,ZFMISC_1,FUNCT_1,XXREAL_0,FINSET_1,XBOOLE_0,FINSEQ_1,MCART_1,LATTICES,LATTICE3,PBOOLE,EQREL_1,FINSUB_1,PARTFUN1,HEYTING1,SUBSTLAT,NORMFORM,REALSET1,STRUCT_0,BINOP_1,RELAT_2,ORDINAL4,CAT_1,YELLOW_0,WELLORD1,HEYTING2,REWRITE1,HEYTING3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,RELAT_1,FUNCT_1,ORDERS_2,NAT_1,FINSEQ_1,BINOP_1,FINSET_1,FINSUB_1,PARTFUN1,LATTICES,DOMAIN_1,REALSET1,STRUCT_0,SUBSTLAT,MCART_1,WELLORD1,YELLOW_0,ABIAN,XXREAL_2,LATTICE3,HEYTING2,XXREAL_0,CKB17,CKB22;
definitions TARSKI,LATTICE3,FUNCT_1,XBOOLE_0,BINOP_1,REALSET1,WELLORD1,CKB17,CKB22;
theorems HEYTING2,ZFMISC_1,PARTFUN1,YELLOW_0,LATTICE3,TARSKI,NAT_1,LATTICE5,FINSEQ_1,MCART_1,FUNCT_5,ORDERS_2,YELLOW_5,SUBSTLAT,FINSUB_1,WAYBEL15,LATTICES,GRFUNC_1,RELAT_1,SYSREL,BINOP_1,FUNCT_1,FUNCT_2,XBOOLE_0,XBOOLE_1,ORDINAL1,XREAL_1,XXREAL_0,XXREAL_2,PRE_POLY,ABIAN,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB20,CKB21,CKB22;
schemes LMOD_7,XBOOLE_0,CKB1;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,PARTFUN1,FINSET_1,FINSUB_1,XXREAL_0,NAT_1,MEMBERED,FINSEQ_1,REALSET1,ABIAN,STRUCT_0,LATTICES,LATTICE3,YELLOW_0,YELLOW_1,SUBSTLAT,XXREAL_2,RELAT_1,HEYTING2,CKB3,CKB18,CKB19,CKB23;
constructors BINOP_1,TOLER_1,REALSET1,ABIAN,LATTICE3,YELLOW_0,HEYTING2,VALUED_1,XXREAL_2,RELSET_1,CKB17,CKB22;
requirements SUBSET,BOOLE,NUMERALS,REAL,ARITHM;
begin
definition
let n being (Element of ( NAT ));
let k being (Element of ( NAT ));
func PFCrt (n,k) -> (Element of ( PFuncs (( NAT ),{ k }) ))
means
:Def3: (for x being set holds (x in it iff (ex m being  odd (Element of ( NAT )) st (m <= ( ( 2 * n ) + 1 ) & [ m,k ] = x))));
existence
proof
defpred P[ set ]
 means
(ex m being  odd (Element of ( NAT )) st (m <= ( ( 2 * n ) + 1 ) & [ m,k ] = $1));
consider X being set such that A1: (for x being set holds (x in X iff (x in [: ( NAT ),{ k } :] & P[ x ]))) from XBOOLE_0:sch 1;
A2: X c= [: ( NAT ),{ k } :]
proof
let x being set;
assume x in X;
hence thesis by A1;
end;
then reconsider X9 = X as Function by GRFUNC_1:1;
(( dom X9 ) c= ( NAT ) & ( rng X9 ) c= { k }) by A2,SYSREL:3;
then reconsider X as (Element of ( PFuncs (( NAT ),{ k }) )) by PARTFUN1:def 3;
take X;
let x being set;
thus (x in X implies (ex m being  odd (Element of ( NAT )) st (m <= ( ( 2 * n ) + 1 ) & [ m,k ] = x))) by A1;
given m being  odd (Element of ( NAT )) such that
A3: m <= ( ( 2 * n ) + 1 )
and
A4: [ m,k ] = x;

x in [: ( NAT ),{ k } :] by A4,ZFMISC_1:106;
hence thesis by A1,A3,A4;
end;
uniqueness
proof
defpred P[ set ]
 means
(ex m being  odd (Element of ( NAT )) st (m <= ( ( 2 * n ) + 1 ) & [ m,k ] = $1));
A5: (for X1,X2 being (Element of ( PFuncs (( NAT ),{ k }) )) holds (((for x being set holds (x in X1 iff P[ x ])) & (for x being set holds (x in X2 iff P[ x ]))) implies X1 = X2)) from LMOD_7:sch 1;
let X1 being (Element of ( PFuncs (( NAT ),{ k }) )),X2 being (Element of ( PFuncs (( NAT ),{ k }) ));
assume ((for x being set holds (x in X1 iff P[ x ])) & (for x being set holds (x in X2 iff P[ x ])));
hence thesis by A5;
end;
end;
