environ
vocabularies NUMBERS,RLVECT_1,REAL_1,PARSP_1,ANALOAF,ANALMETR,RELAT_1,ARYTM_3,SUPINF_2,CARD_1,SUBSET_1,STRUCT_0,DIRAF,ARYTM_1,PBOOLE,SYMSP_1,MCART_1,ZFMISC_1,BINOP_1,FUNCT_1,MIDSP_1,XBOOLE_0,GEOMTRAP;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,DOMAIN_1,NUMBERS,XXREAL_0,REAL_1,STRUCT_0,DIRAF,RELSET_1,RLVECT_1,MIDSP_1,AFF_1,ANALOAF,BINOP_1,ANALMETR,CKB1,CKB6,CKB27;
definitions STRUCT_0,RLVECT_1,CKB1,CKB6,CKB27;
theorems RLVECT_1,RELAT_1,DIRAF,ANALOAF,ANALMETR,AFF_1,ZFMISC_1,RLSUB_2,XCMPLX_0,XCMPLX_1,XREAL_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41;
schemes RELSET_1,BINOP_1,BINOP_2;
registrations SUBSET_1,RELSET_1,MEMBERED,STRUCT_0,ANALOAF,DIRAF,ANALMETR;
constructors BINOP_1,DOMAIN_1,XXREAL_0,REAL_1,MEMBERED,MIDSP_1,AFF_1,ANALMETR,CKB1,CKB6,CKB27;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve V for RealLinearSpace;
reserve u for (VECTOR of V);
reserve u1 for (VECTOR of V);
reserve u2 for (VECTOR of V);
reserve v1 for (VECTOR of V);
reserve v2 for (VECTOR of V);
reserve w for (VECTOR of V);
reserve w1 for (VECTOR of V);
reserve y for (VECTOR of V);
reserve a for Real;
reserve b for Real;
theorem
Th30: (for u,u1,u2,v1,v2,t1,t2,w1,w2 being (VECTOR of V) holds (((((u = ( u1 # t1 ) & u = ( u2 # t2 )) & u = ( v1 # w1 )) & u = ( v2 # w2 )) & u1,u2,v1,v2 are_DTr_wrt w,y) implies t1,t2,w1,w2 are_DTr_wrt w,y))
proof
let u being (VECTOR of V);
let u1 being (VECTOR of V);
let u2 being (VECTOR of V);
let v1 being (VECTOR of V);
let v2 being (VECTOR of V);
let t1 being (VECTOR of V);
let t2 being (VECTOR of V);
let w1 being (VECTOR of V);
let w2 being (VECTOR of V);
assume that
A1: (u = ( u1 # t1 ) & u = ( u2 # t2 ))
and
A2: (u = ( v1 # w1 ) & u = ( v2 # w2 ))
and
A3: u1,u2,v1,v2 are_DTr_wrt w,y;
A4: u1,u2 // v1,v2 by A3,CKB27:def 1;
set p = ( u1 # u2 );
set q = ( v1 # v2 );
set r = ( t1 # t2 );
set s = ( w1 # w2 );
A5: ( q # s ) = ( u # u ) by A2,CKB8:1
.= u;
( p # r ) = ( u # u ) by A1,CKB8:1
.= u;
then A6: ( s - r ) = ( - ( q - p ) ) by A5,CKB19:1
.= ( ( - 1 ) * ( q - p ) ) by RLVECT_1:16;
A7: (( u2 - u1 ) = ( - ( t2 - t1 ) ) & ( v2 - v1 ) = ( - ( w2 - w1 ) )) by A1,A2,CKB19:1;
A8: t1,t2 // w1,w2
proof
per cases ;
suppose u1 = u2;

then t1 = t2 by A1,CKB9:1;
hence thesis by ANALOAF:9;
end;
suppose v1 = v2;

then w1 = w2 by A2,CKB9:1;
hence thesis by ANALOAF:9;
end;
suppose (u1 <> u2 & v1 <> v2);

then consider a,b such that A9: (( 0 ) < a & ( 0 ) < b) and A10: ( a * ( u2 - u1 ) ) = ( b * ( v2 - v1 ) ) by A4,ANALOAF:def 1;
( a * ( t2 - t1 ) ) = ( a * ( - ( - ( t2 - t1 ) ) ) ) by RLVECT_1:17
.= ( - ( b * ( - ( w2 - w1 ) ) ) ) by A7,A10,RLVECT_1:25
.= ( b * ( - ( - ( w2 - w1 ) ) ) ) by RLVECT_1:25
.= ( b * ( w2 - w1 ) ) by RLVECT_1:17;
hence thesis by A9,ANALOAF:def 1;
end;
end;
( w2 - w1 ) = ( - ( v2 - v1 ) ) by A2,CKB19:1;
then A11: ( w2 - w1 ) = ( ( - 1 ) * ( v2 - v1 ) ) by RLVECT_1:16;
v1,v2,p,q are_Ort_wrt w,y by A3,CKB27:def 1;
then ( v2 - v1 ),( q - p ) are_Ort_wrt w,y by ANALMETR:def 3;
then ( w2 - w1 ),( s - r ) are_Ort_wrt w,y by A6,A11,ANALMETR:6;
then A12: w1,w2,r,s are_Ort_wrt w,y by ANALMETR:def 3;
( t2 - t1 ) = ( - ( u2 - u1 ) ) by A1,CKB19:1;
then A13: ( t2 - t1 ) = ( ( - 1 ) * ( u2 - u1 ) ) by RLVECT_1:16;
u1,u2,p,q are_Ort_wrt w,y by A3,CKB27:def 1;
then ( u2 - u1 ),( q - p ) are_Ort_wrt w,y by ANALMETR:def 3;
then ( t2 - t1 ),( s - r ) are_Ort_wrt w,y by A6,A13,ANALMETR:6;
then t1,t2,r,s are_Ort_wrt w,y by ANALMETR:def 3;
hence thesis by A8,A12,CKB27:def 1;
end;
