environ
vocabularies SUBSET_1,RELAT_1,XBOOLE_0,FUNCT_1,ZFMISC_1,EQREL_1,RELAT_2,ORDERS_2,STRUCT_0,TARSKI,YELLOW_0,LATTICES,LATTICE3,ORDINAL2,WAYBEL_0,WELLORD1,CAT_1,XXREAL_0,REWRITE1,WAYBEL_1,GROUP_6,SEQM_3,YELLOW_1,WAYBEL_3,PBOOLE,CARD_3,FINSET_1,FUNCT_4,WAYBEL16,WAYBEL_5,BINOP_1,SETFAM_1,WAYBEL20;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,SETFAM_1,RELAT_2,FUNCT_1,PBOOLE,RELSET_1,PARTFUN1,BINOP_1,FUNCT_2,FINSET_1,DOMAIN_1,EQREL_1,FUNCT_3,FUNCT_7,STRUCT_0,ORDERS_2,LATTICE3,QUANTAL1,YELLOW_0,YELLOW_1,YELLOW_2,YELLOW_3,WAYBEL_0,WAYBEL_1,WAYBEL_3,WAYBEL_5,WAYBEL16,CKB3;
definitions TARSKI,RELAT_2,LATTICE3,LATTICE5,YELLOW_0,WAYBEL_0,WAYBEL_1,WAYBEL_3,YELLOW_2,BINOP_1,STRUCT_0;
theorems TARSKI,ZFMISC_1,RELAT_1,RELAT_2,FUNCT_1,FUNCT_2,FUNCT_3,FUNCT_5,FUNCT_7,CARD_3,ORDERS_2,LATTICE3,LATTICE5,QUANTAL1,EQREL_1,YELLOW_0,YELLOW_2,YELLOW_3,YELLOW10,WAYBEL_0,WAYBEL_1,WAYBEL_3,WAYBEL_5,WAYBEL13,WAYBEL15,WAYBEL16,WAYBEL17,XBOOLE_0,XBOOLE_1,PARTFUN1,ORDERS_1,CKB1,CKB2,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23;
schemes YELLOW_0,FUNCT_2,PBOOLE;
registrations XBOOLE_0,SUBSET_1,RELAT_1,PARTFUN1,FUNCT_2,FINSET_1,STRUCT_0,LATTICE3,YELLOW_0,MONOID_0,WAYBEL_0,YELLOW_2,WAYBEL_1,YELLOW_3,WAYBEL_3,WAYBEL10,YELLOW_9,RELSET_1;
constructors DOMAIN_1,FUNCT_7,MONOID_0,QUANTAL1,ORDERS_3,WAYBEL_1,YELLOW_3,WAYBEL16,RELSET_1,CKB3;
requirements SUBSET,BOOLE;
begin
theorem
Th24: (for S,T being  reflexive  antisymmetric non empty RelStr holds (for f being (Function of S,T) holds (f is  filtered-infs-preserving implies f is  monotone)))
proof
let S being  reflexive  antisymmetric non empty RelStr,T being  reflexive  antisymmetric non empty RelStr;
let f being (Function of S,T);
assume A1: f is  filtered-infs-preserving;
let x being (Element of S),y being (Element of S);
assume that
A2: x <= y;
A3: ( dom f ) = (the carrier of S) by FUNCT_2:def 1;
A4: (for b being (Element of S) holds ({ x,y } is_>=_than b implies x >= b)) by YELLOW_0:8;
A5: x <= x;
then A6: { x,y } is_>=_than x by A2,YELLOW_0:8;
then A7:  ex_inf_of { x,y },S by A4,YELLOW_0:31;
(for a,b being (Element of S) holds ((a in { x,y } & b in { x,y }) implies (ex z being (Element of S) st ((z in { x,y } & a >= z) & b >= z))))
proof
let a being (Element of S),b being (Element of S);
assume that
A8: (a in { x,y } & b in { x,y });
take x;
thus x in { x,y } by TARSKI:def 2;
thus thesis by A2,A5,A8,TARSKI:def 2;
end;
then { x,y } is  filtered non empty by WAYBEL_0:def 2;
then A9: f preserves_inf_of { x,y } by A1,WAYBEL_0:def 36;
x = ( inf { x,y } ) by A6,A4,YELLOW_0:31;
then ( inf ( f .: { x,y } ) ) = ( f . x ) by A7,A9,WAYBEL_0:def 30;
then A10: ( f . x ) = ( inf { ( f . x ),( f . y ) } ) by A3,FUNCT_1:60;
( f .: { x,y } ) = { ( f . x ),( f . y ) } by A3,FUNCT_1:60;
then  ex_inf_of { ( f . x ),( f . y ) },T by A7,A9,WAYBEL_0:def 30;
then { ( f . x ),( f . y ) } is_>=_than ( f . x ) by A10,YELLOW_0:def 10;
hence ( f . x ) <= ( f . y ) by YELLOW_0:8;
end;
