environ
vocabularies BINOP_1,VECTSP_1,XBOOLE_0,ALGSTR_0,SUBSET_1,MESFUNC1,RELAT_1,LATTICES,ARYTM_3,FUNCSDOM,VECTSP_2,REAL_1,SUPINF_2,CARD_1,STRUCT_0,RLVECT_1,ARYTM_1,GROUP_1,EQREL_1,TARSKI,SETFAM_1,MSSUBFAM,INT_2,GCD_1;
notations TARSKI,XBOOLE_0,SUBSET_1,REAL_1,NUMBERS,STRUCT_0,ALGSTR_0,RLVECT_1,GROUP_1,VECTSP_2,VECTSP_1,FUNCSDOM,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14;
definitions VECTSP_1,VECTSP_2,XBOOLE_0,CKB8,CKB10,CKB11,CKB14;
theorems TARSKI,WELLORD2,SUBSET_1,VECTSP_1,VECTSP_2,RLVECT_1,XBOOLE_0,XCMPLX_1,GROUP_1,STRUCT_0,CKB7,CKB8,CKB10,CKB11,CKB14,CKB15,CKB16;
schemes SUBSET_1;
registrations XBOOLE_0,SUBSET_1,MEMBERED,STRUCT_0,VECTSP_1,MONOID_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
constructors BINOP_2,VECTSP_2,MONOID_0,CKB8,CKB9,CKB10,CKB11,CKB13,CKB14;
requirements SUBSET,BOOLE;
begin
reserve R for  domRing-like  commutative Ring;
theorem
Th4: (for R being  associative non  empty multLoopStr holds (for a,b,c being (Element of R) holds ((a is_associated_to b & b is_associated_to c) implies a is_associated_to c)))
proof
let R being  associative non  empty multLoopStr;
let A being (Element of R);
let B being (Element of R);
let C being (Element of R);
now
assume A1: (A is_associated_to B & B is_associated_to C);
then (B divides A & C divides B) by CKB11:def 1;
then A2: C divides A by CKB15:1;
(A divides B & B divides C) by A1,CKB11:def 1;
then A divides C by CKB15:1;
hence thesis by A2,CKB11:def 1;
end;
hence thesis;
end;
