environ
vocabularies XBOOLE_0,LATTICES,ORDERS_2,ZFMISC_1,STRUCT_0,TARSKI,SUBSET_1,LATTICE3,RELAT_2,XXREAL_0,YELLOW_0,REWRITE1,ORDINAL2,RELAT_1,MCART_1,EQREL_1,XXREAL_2,WAYBEL_0,WAYBEL_3,RCOMP_1,WAYBEL_8,WAYBEL_6,CARD_FIL,WAYBEL11,WAYBEL_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,DOMAIN_1,STRUCT_0,MCART_1,ORDERS_2,LATTICE3,YELLOW_0,WAYBEL_0,WAYBEL_1,YELLOW_3,YELLOW_4,WAYBEL_2,WAYBEL_3,WAYBEL_6,WAYBEL_8,WAYBEL11,CKB19;
definitions TARSKI,YELLOW_0,LATTICE3,WAYBEL_0,WAYBEL_1,WAYBEL_2,WAYBEL_3,WAYBEL_6,WAYBEL_8,WAYBEL11,XBOOLE_0;
theorems ZFMISC_1,TARSKI,ORDERS_2,YELLOW_0,YELLOW_3,YELLOW_4,WAYBEL_0,WAYBEL_1,WAYBEL_2,WAYBEL_3,WAYBEL_8,MCART_1,FUNCT_5,DOMAIN_1,XBOOLE_0,RELAT_1,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB58,CKB59,CKB60,CKB61;
registrations XBOOLE_0,SUBSET_1,STRUCT_0,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_3,YELLOW_4,WAYBEL_2,WAYBEL_3,WAYBEL_8,WAYBEL14,RELAT_1,CKB1,CKB2,CKB57;
constructors DOMAIN_1,WAYBEL_1,YELLOW_4,WAYBEL_3,WAYBEL_6,WAYBEL_8,WAYBEL11,WAYBEL_2,CKB19;
requirements SUBSET,BOOLE;
begin
theorem
(for S,T being  antisymmetric  up-complete non empty  reflexive RelStr holds (for X being (Subset of S) holds (for Y being (Subset of T) holds ([: X,Y :] is  directly_closed implies ((Y <> ( {} ) implies X is  directly_closed) & (X <> ( {} ) implies Y is  directly_closed))))))
proof
let S being  antisymmetric  up-complete non empty  reflexive RelStr,T being  antisymmetric  up-complete non empty  reflexive RelStr;
let X being (Subset of S);
let Y being (Subset of T);
assume that
A1: (for D being non empty  directed (Subset of [: S,T :]) holds (D c= [: X,Y :] implies ( sup D ) in [: X,Y :]));
hereby
assume A2: Y <> ( {} );
thus X is  directly_closed
proof
consider t being set such that A3: t in Y by A2,XBOOLE_0:def 1;
reconsider t9 = { t } as non empty  directed (Subset of T) by A3,WAYBEL_0:5;
A4: t9 c= Y by A3,ZFMISC_1:31;
let D being non empty  directed (Subset of S);
assume D c= X;
then A5: ( sup [: D,t9 :] ) in [: X,Y :] by A1,A4,ZFMISC_1:96;
 ex_sup_of [: D,t9 :],[: S,T :] by WAYBEL_0:75;
then ( sup [: D,t9 :] ) = [ ( sup ( proj1 [: D,t9 :] ) ),( sup ( proj2 [: D,t9 :] ) ) ] by YELLOW_3:46
.= [ ( sup D ),( sup ( proj2 [: D,t9 :] ) ) ] by FUNCT_5:9
.= [ ( sup D ),( sup t9 ) ] by FUNCT_5:9
.= [ ( sup D ),t ] by A3,YELLOW_0:39;
hence thesis by A5,ZFMISC_1:87;
end;

end;
assume X <> ( {} );
then consider s being set such that A6: s in X by XBOOLE_0:def 1;
reconsider s9 = { s } as non empty  directed (Subset of S) by A6,WAYBEL_0:5;
let D being non empty  directed (Subset of T);
assume that
A7: D c= Y;
 ex_sup_of [: s9,D :],[: S,T :] by WAYBEL_0:75;
then A8: ( sup [: s9,D :] ) = [ ( sup ( proj1 [: s9,D :] ) ),( sup ( proj2 [: s9,D :] ) ) ] by YELLOW_3:46
.= [ ( sup s9 ),( sup ( proj2 [: s9,D :] ) ) ] by FUNCT_5:9
.= [ ( sup s9 ),( sup D ) ] by FUNCT_5:9
.= [ s,( sup D ) ] by A6,YELLOW_0:39;
s9 c= X by A6,ZFMISC_1:31;
then ( sup [: s9,D :] ) in [: X,Y :] by A1,A7,ZFMISC_1:96;
hence thesis by A8,ZFMISC_1:87;
end;
