environ
vocabularies NUMBERS,SUBSET_1,CQC_LANG,QC_LANG1,FINSEQ_1,XBOOLE_0,FINSET_1,FUNCT_1,ORDINAL1,RELAT_1,ARYTM_3,TARSKI,WELLORD2,WELLORD1,CARD_1,NAT_1,CQC_THE1,ORDINAL4,XBOOLEAN,CALCUL_1,CALCUL_2,ARYTM_1,INT_1,XXREAL_0,FUNCT_2,ZFMISC_1,VALUAT_1,ZF_MODEL,MARGREL1,REALSET1,MCART_1,HENMODEL;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,CALCUL_1,RELAT_1,FUNCT_1,ORDINAL1,XCMPLX_0,XXREAL_0,NAT_1,FINSEQ_1,QC_LANG1,CQC_LANG,CQC_THE1,VALUAT_1,FINSET_1,RELSET_1,FUNCT_2,CARD_1,MARGREL1,CQC_SIM1,DOMAIN_1,MCART_1,NUMBERS,FINSEQ_3,CALCUL_2,INT_1,WELLORD1,WELLORD2;
definitions TARSKI,XBOOLE_0,FUNCT_1,FINSEQ_2;
theorems TARSKI,FINSEQ_1,FINSEQ_3,FUNCT_1,VALUAT_1,XBOOLE_0,FINSEQ_2,ZFMISC_1,RELAT_1,QC_LANG3,XBOOLE_1,NAT_1,MARGREL1,FUNCT_2,RELSET_1,FINSET_1,CALCUL_1,CQC_THE1,ORDINAL2,AXIOMS,CALCUL_2,CARD_2,INT_1,ORDINAL1,WELLORD1,WELLORD2,CARD_3,MCART_1,SUBSTUT2,XREAL_1,XXREAL_0,FUNCOP_1,CARD_1,CKB1,CKB2;
schemes FUNCT_1,FINSEQ_1,CLASSES1;
registrations SUBSET_1,FUNCT_1,ORDINAL1,RELSET_1,FINSET_1,XXREAL_0,XREAL_0,INT_1,FINSEQ_1,QC_LANG1,CQC_LANG,FINSEQ_2,CARD_1;
constructors SETFAM_1,WELLORD1,WELLORD2,DOMAIN_1,XXREAL_0,NAT_1,INT_1,FINSEQ_3,CQC_SIM1,SUBSTUT2,CALCUL_1,CALCUL_2,RELSET_1;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve a for set;
reserve b for set;
reserve c for set;
reserve d for set;
reserve X for (Subset of ( CQC-WFF ));
reserve i for (Element of ( NAT ));
reserve k for (Element of ( NAT ));
reserve m for (Element of ( NAT ));
reserve n for (Element of ( NAT ));
reserve f for (FinSequence of ( CQC-WFF ));
reserve g for (FinSequence of ( CQC-WFF ));
reserve C for non  empty set;
theorem
Th3: (for f being (Function of ( NAT ),C) holds (for X being  finite set holds (((for n holds (for m holds (((m in ( dom f ) & n in ( dom f )) & n < m) implies ( f . n ) c= ( f . m )))) & X c= ( union ( rng f ) )) implies (ex k st X c= ( f . k )))))
proof
let f being (Function of ( NAT ),C);
let X being  finite set;
assume that
A1: (for n holds (for m holds (((m in ( dom f ) & n in ( dom f )) & n < m) implies ( f . n ) c= ( f . m ))))
and
A2: X c= ( union ( rng f ) );
A3:now
deffunc F(set) = ( min* { i: $1 in ( f . i ) } );
consider g being Function such that A4: (( dom g ) = X & (for a holds (a in X implies ( g . a ) = F(a)))) from FUNCT_1:sch 3;
reconsider A = ( rng g ) as  finite set by A4,FINSET_1:8;
A5:now
let b;
assume b in A;
then consider a such that A6: (a in ( dom g ) & ( g . a ) = b) by FUNCT_1:def 3;
b = ( min* { i: a in ( f . i ) } ) by A4,A6;
hence b in ( NAT );
end;
assume (not X is  empty);
then (ex c st c in ( dom g )) by A4,XBOOLE_0:def 1;
then reconsider A as non  empty  finite (Subset of ( NAT )) by A5,FUNCT_1:3,TARSKI:def 3;
( union A ) in A by CKB2:1;
then reconsider a = ( union A ) as (Element of ( NAT ));
take a;
thus X c= ( f . a )
proof
let b;
assume A7: b in X;
then consider c such that A8: b in c and A9: c in ( rng f ) by A2,TARSKI:def 4;
consider d such that A10: d in ( dom f ) and A11: ( f . d ) = c by A9,FUNCT_1:def 3;
reconsider d as (Element of ( NAT )) by A10;
d in { i: b in ( f . i ) } by A8,A11;
then reconsider Y = { i: b in ( f . i ) } as non  empty set;
now
let a;
assume a in Y;
then (ex i st (i = a & b in ( f . i )));
hence a in ( NAT );
end;
then reconsider Y as non  empty (Subset of ( NAT )) by TARSKI:def 3;
A12: ( g . b ) = ( min* Y ) by A4,A7;
then reconsider Y9 = ( g . b ) as (Element of ( NAT ));
Y9 in Y by A12,NAT_1:def 1;
then A13: (ex i st (i = ( g . b ) & b in ( f . i )));
A14: ( dom f ) = ( NAT ) by FUNCT_2:def 1;
A15:now
assume Y9 in a;
then Y9 in { k: k < a } by AXIOMS:4;
then (ex k st (k = Y9 & k < a));
then ( f . Y9 ) c= ( f . a ) by A1,A14;
hence thesis by A13;
end;
Y9 in A by A4,A7,FUNCT_1:3;
hence thesis by A13,A15,CKB2:1;
end;

end;
now
assume A16: X is  empty;
take k = ( 0 );
( {} ) c= ( f . k ) by XBOOLE_1:2;
hence thesis by A16;
end;
hence thesis by A3;
end;
