environ
vocabularies GROUP_1,XBOOLE_0,SUBSET_1,GROUP_2,PRE_TOPC,RELAT_1,TARSKI,STRUCT_0;
notations TARSKI,XBOOLE_0,SUBSET_1,STRUCT_0,ALGSTR_0,GROUP_1,GROUP_2,GROUP_3,GROUP_4,CKB12,CKB13,CKB51,CKB52;
definitions XBOOLE_0,GROUP_2,TARSKI,GROUP_4,CKB12,CKB13,CKB51,CKB52;
theorems GROUP_1,GROUP_8,GROUP_2,GROUP_3,XBOOLE_0,XBOOLE_1,GROUP_4,STRUCT_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70;
registrations XBOOLE_0,STRUCT_0,GROUP_1,GROUP_2,GROUP_3;
constructors REALSET2,GROUP_4,CKB12,CKB13,CKB51,CKB52;
requirements SUBSET,BOOLE;
begin
reserve G for Group;
reserve N for (Subgroup of G);
reserve H for (Subgroup of G);
reserve x for (Element of G);
reserve N1 for (Subgroup of G);
reserve N2 for (Subgroup of G);
theorem
(for N1,N2 being  strict  normal (Subgroup of G) holds (ex N being  strict  normal (Subgroup of G) st ((the carrier of N) = ( N1 * N2 ) & ( ( N1 ~ H ) \/ ( N2 ~ H ) ) c= ( N ~ H ))))
proof
let N1 being  strict  normal (Subgroup of G);
let N2 being  strict  normal (Subgroup of G);
consider N being  strict  normal (Subgroup of G) such that A1: (the carrier of N) = ( N1 * N2 ) by CKB8:1;
(N1 is (Subgroup of N) & N2 is (Subgroup of N)) by A1,CKB9:1;
then A2: (( N1 ~ H ) c= ( N ~ H ) & ( N2 ~ H ) c= ( N ~ H )) by CKB61:1;
( ( N1 ~ H ) \/ ( N2 ~ H ) ) c= ( N ~ H )
proof
let x being set;
assume x in ( ( N1 ~ H ) \/ ( N2 ~ H ) );
then (x in ( N1 ~ H ) or x in ( N2 ~ H )) by XBOOLE_0:def 3;
hence thesis by A2;
end;
hence thesis by A1;
end;
