environ
vocabularies NUMBERS,SUBSET_1,REAL_1,SEQ_1,PARTFUN1,FDIFF_1,RELAT_1,CARD_3,FUNCT_1,FINSEQ_1,FINSEQ_2,PDIFF_1,RCOMP_1,TARSKI,ARYTM_1,ARYTM_3,XREAL_0,ORDINAL1,CARD_1,XXREAL_1,VALUED_0,SEQ_2,ORDINAL2,XXREAL_0,NAT_1,FUNCT_2,VALUED_1,XBOOLE_0,COMPLEX1,FCONT_1,PDIFF_2;
notations TARSKI,SUBSET_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,XCMPLX_0,XREAL_0,COMPLEX1,ORDINAL1,NUMBERS,REAL_1,NAT_1,VALUED_0,VALUED_1,SEQ_1,SEQ_2,FINSEQ_1,FINSEQ_2,RCOMP_1,EUCLID,FDIFF_1,XXREAL_0,FCONT_1,PDIFF_1,CKB3;
definitions TARSKI,EUCLID,RCOMP_1,PDIFF_1,CKB3;
theorems TARSKI,XBOOLE_0,XBOOLE_1,XREAL_1,RCOMP_1,SEQ_4,SEQ_1,SEQ_2,FINSEQ_1,FINSEQ_2,RFUNCT_2,RELAT_1,FUNCT_1,FUNCT_2,PARTFUN1,FDIFF_1,VALUED_1,SEQM_3,RFUNCT_1,XCMPLX_0,XCMPLX_1,PDIFF_1,NAT_1,VALUED_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9;
schemes SEQ_1;
registrations RELSET_1,XREAL_0,MEMBERED,FDIFF_1,FUNCT_2,NAT_1,NUMBERS,XBOOLE_0,XXREAL_0,FINSEQ_1,VALUED_0,VALUED_1,ORDINAL1,SEQ_4;
constructors REAL_1,SEQ_2,PARTFUN1,RFUNCT_2,COMPLEX1,RCOMP_1,FDIFF_1,SEQ_1,NAT_1,FCONT_1,PDIFF_1,BHSP_3,VFUNCT_1,SEQM_3,RELSET_1,BINOP_2,RVSUM_1,CKB3;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve x for Real;
reserve x0 for Real;
reserve y0 for Real;
reserve R for REST;
reserve L for LINEAR;
theorem
Th9: (for f being (PartFunc of ( REAL 2 ),( REAL )) holds (for z being (Element of ( REAL 2 )) holds (f is_partial_differentiable_in z,1 iff (ex x0,y0 being Real st (z = <* x0,y0 *> & (ex N being (Neighbourhood of x0) st (N c= ( dom ( SVF1 (1,f,z) ) ) & (ex L st (ex R st (for x holds (x in N implies ( ( ( SVF1 (1,f,z) ) . x ) - ( ( SVF1 (1,f,z) ) . x0 ) ) = ( ( L . ( x - x0 ) ) + ( R . ( x - x0 ) ) ))))))))))))
proof
let f being (PartFunc of ( REAL 2 ),( REAL ));
let z being (Element of ( REAL 2 ));
hereby
assume A1: f is_partial_differentiable_in z,1;
thus (ex x0,y0 being Real st (z = <* x0,y0 *> & (ex N being (Neighbourhood of x0) st (N c= ( dom ( SVF1 (1,f,z) ) ) & (ex L st (ex R st (for x holds (x in N implies ( ( ( SVF1 (1,f,z) ) . x ) - ( ( SVF1 (1,f,z) ) . x0 ) ) = ( ( L . ( x - x0 ) ) + ( R . ( x - x0 ) ) )))))))))
proof
consider x0,y0 such that A2: z = <* x0,y0 *> and A3: ( SVF1 (1,f,z) ) is_differentiable_in x0 by A1,CKB6:1;
(ex N being (Neighbourhood of x0) st (N c= ( dom ( SVF1 (1,f,z) ) ) & (ex L st (ex R st (for x holds (x in N implies ( ( ( SVF1 (1,f,z) ) . x ) - ( ( SVF1 (1,f,z) ) . x0 ) ) = ( ( L . ( x - x0 ) ) + ( R . ( x - x0 ) ) ))))))) by A3,FDIFF_1:def 4;
hence thesis by A2;
end;

end;
assume (ex x0,y0 being Real st (z = <* x0,y0 *> & (ex N being (Neighbourhood of x0) st (N c= ( dom ( SVF1 (1,f,z) ) ) & (ex L st (ex R st (for x holds (x in N implies ( ( ( SVF1 (1,f,z) ) . x ) - ( ( SVF1 (1,f,z) ) . x0 ) ) = ( ( L . ( x - x0 ) ) + ( R . ( x - x0 ) ) )))))))));
then consider x0,y0 such that A4: z = <* x0,y0 *> and A5: (ex N being (Neighbourhood of x0) st (N c= ( dom ( SVF1 (1,f,z) ) ) & (ex L st (ex R st (for x holds (x in N implies ( ( ( SVF1 (1,f,z) ) . x ) - ( ( SVF1 (1,f,z) ) . x0 ) ) = ( ( L . ( x - x0 ) ) + ( R . ( x - x0 ) ) )))))));
( SVF1 (1,f,z) ) is_differentiable_in x0 by A5,FDIFF_1:def 4;
hence thesis by A4,CKB6:1;
end;
