environ
vocabularies NUMBERS,SUBSET_1,REAL_1,NORMSP_1,SEQ_1,NAT_1,PRE_TOPC,RCOMP_1,TARSKI,CARD_1,ARYTM_3,ARYTM_1,XXREAL_0,RELAT_1,FUNCT_1,SEQ_2,ORDINAL2,STRUCT_0,VALUED_0,SUPINF_2,RLVECT_1,VALUED_1,XREAL_0,ORDINAL1,COMPLEX1,XXREAL_2,FDIFF_1,ZFMISC_1,PARTFUN1,FUNCOP_1,FUNCT_2,LOPBAN_1,XBOOLE_0,FCONT_1,RSSPACE,NFCONT_1,CFCONT_1,LOPBAN_2;
notations TARSKI,SUBSET_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,PRE_TOPC,XXREAL_0,XREAL_0,COMPLEX1,ORDINAL1,NUMBERS,REAL_1,NAT_1,RLVECT_1,STRUCT_0,FUNCOP_1,VALUED_0,VALUED_1,SEQ_1,SEQ_2,SQUARE_1,VFUNCT_1,NORMSP_0,NORMSP_1,RSSPACE,LOPBAN_1,LOPBAN_2,NFCONT_1,FDIFF_1,RECDEF_1,CKB6,CKB9,CKB10,CKB21,CKB29,CKB31,CKB39,CKB40,CKB41,CKB45;
definitions TARSKI,XBOOLE_0,NFCONT_1,NORMSP_1,BHSP_3,RLVECT_1,SUBSET_1,VALUED_1,STRUCT_0,CKB6,CKB9,CKB10,CKB21,CKB29,CKB39,CKB40,CKB41,CKB45;
theorems TARSKI,ABSVALUE,XBOOLE_0,XBOOLE_1,SUBSET_1,RELSET_1,RLVECT_1,XCMPLX_0,XCMPLX_1,ZFMISC_1,XREAL_0,FUNCOP_1,SEQ_1,SEQ_2,NAT_1,SEQM_3,RELAT_1,FUNCT_1,VFUNCT_1,FUNCT_2,SEQ_4,NORMSP_1,LOPBAN_1,LOPBAN_2,LOPBAN_3,PARTFUN1,PARTFUN2,NFCONT_1,FDIFF_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,STRUCT_0,VALUED_0,GRCAT_1,NORMSP_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB29,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB48,CKB49,CKB50,CKB51;
schemes NAT_1,SEQ_1,RECDEF_1,FUNCT_2;
registrations FUNCT_1,ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,FDIFF_1,STRUCT_0,LOPBAN_1,LOPBAN_2,VALUED_0,VALUED_1,FUNCT_2,FUNCOP_1,CKB27,CKB28,CKB30,CKB47;
constructors PARTFUN1,REAL_1,SQUARE_1,NAT_1,COMPLEX1,SEQ_2,PARTFUN2,FDIFF_1,BHSP_3,RSSPACE,VFUNCT_1,LOPBAN_3,NFCONT_1,SEQ_1,VALUED_1,RECDEF_1,NORMSP_1,RELSET_1,BINOP_2,RVSUM_1,CKB9,CKB10,CKB21,CKB29,CKB39,CKB40,CKB41,CKB45;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve S for non trivial RealNormSpace;
reserve h for  convergent_to_0 (sequence of S);
theorem
(for f being (PartFunc of S,S) holds (for Z being (Subset of S) holds (((Z is  open & Z c= ( dom f )) & ( f | Z ) = ( id Z )) implies (f is_differentiable_on Z & (for x being (Point of S) holds (x in Z implies ( ( f `| Z ) /. x ) = ( id (the carrier of S) )))))))
proof
set L = ( id (the carrier of S) );
(( R_NormSpace_of_BoundedLinearOperators (S,S) ) = NORMSTR (# ( BoundedLinearOperators (S,S) ),( Zero_ (( BoundedLinearOperators (S,S) ),( R_VectorSpace_of_LinearOperators (S,S) )) ),( Add_ (( BoundedLinearOperators (S,S) ),( R_VectorSpace_of_LinearOperators (S,S) )) ),( Mult_ (( BoundedLinearOperators (S,S) ),( R_VectorSpace_of_LinearOperators (S,S) )) ),( BoundedLinearOperatorsNorm (S,S) ) #) & L is  bounded  bounded (LinearOperator of S,S)) by LOPBAN_1:def 14,LOPBAN_2:3;
then reconsider L as (Point of ( R_NormSpace_of_BoundedLinearOperators (S,S) )) by LOPBAN_1:def 9;
let f being (PartFunc of S,S);
let Z being (Subset of S);
assume that
A1: Z is  open;
reconsider R = ( (the carrier of S) --> ( 0. S ) ) as (PartFunc of S,S);
A2: ( dom R ) = (the carrier of S) by FUNCOP_1:13;
now
let h;
A3:now
let n being Nat;
A4: ( R /. ( h . n ) ) = ( R . ( h . n ) ) by A2,PARTFUN1:def 6
.= ( 0. S ) by FUNCOP_1:7;
A5: ( rng h ) c= ( dom R ) by A2;
A6: n in ( NAT ) by ORDINAL1:def 12;
hence ( ( ( ||. h .|| " ) (#) ( R /* h ) ) . n ) = ( ( ( ||. h .|| " ) . n ) * ( ( R /* h ) . n ) ) by CKB9:def 1
.= ( ( ( ||. h .|| " ) . n ) * ( R /. ( h . n ) ) ) by A6,A5,FUNCT_2:109
.= ( 0. S ) by A4,RLVECT_1:10;
end;
then A7: ( ( ||. h .|| " ) (#) ( R /* h ) ) is  constant by VALUED_0:def 18;
hence ( ( ||. h .|| " ) (#) ( R /* h ) ) is  convergent by CKB22:1;
( ( ( ||. h .|| " ) (#) ( R /* h ) ) . ( 0 ) ) = ( 0. S ) by A3;
hence ( lim ( ( ||. h .|| " ) (#) ( R /* h ) ) ) = ( 0. S ) by A7,CKB22:1;
end;
then reconsider R as (REST of S,S) by CKB29:def 1;
assume that
A8: Z c= ( dom f )
and
A9: ( f | Z ) = ( id Z );
A10:now
let x being (Point of S);
assume A11: x in Z;
then ( ( f | Z ) . x ) = x by A9,FUNCT_1:18;
then ( f . x ) = x by A11,FUNCT_1:49;
hence ( f /. x ) = x by A8,A11,PARTFUN1:def 6;
end;
A12:now
let x0 being (Point of S);
assume A13: x0 in Z;
then consider N being (Neighbourhood of x0) such that A14: N c= Z by A1,CKB2:1;
A15: (for x being (Point of S) holds (x in N implies ( ( f /. x ) - ( f /. x0 ) ) = ( ( L . ( x - x0 ) ) + ( R /. ( x - x0 ) ) )))
proof
let x being (Point of S);
A16: ( R /. ( x - x0 ) ) = ( R . ( x - x0 ) ) by A2,PARTFUN1:def 6
.= ( 0. S ) by FUNCOP_1:7;
assume x in N;
hence ( ( f /. x ) - ( f /. x0 ) ) = ( x - ( f /. x0 ) ) by A10,A14
.= ( x - x0 ) by A10,A13
.= ( L . ( x - x0 ) ) by FUNCT_1:17
.= ( ( L . ( x - x0 ) ) + ( R /. ( x - x0 ) ) ) by A16,RLVECT_1:4;
end;
N c= ( dom f ) by A8,A14,XBOOLE_1:1;
hence f is_differentiable_in x0 by A15,CKB39:def 1;
end;
hence A17: f is_differentiable_on Z by A1,A8,CKB43:1;
let x0 being (Point of S);
assume A18: x0 in Z;
then consider N1 being (Neighbourhood of x0) such that A19: N1 c= Z by A1,CKB2:1;
A20: f is_differentiable_in x0 by A12,A18;
then (ex N being (Neighbourhood of x0) st (N c= ( dom f ) & (ex L being (Point of ( R_NormSpace_of_BoundedLinearOperators (S,S) )) st (ex R being (REST of S,S) st (for x being (Point of S) holds (x in N implies ( ( f /. x ) - ( f /. x0 ) ) = ( ( L . ( x - x0 ) ) + ( R /. ( x - x0 ) ) ))))))) by CKB39:def 1;
then consider N being (Neighbourhood of x0) such that A21: N c= ( dom f );
consider N2 being (Neighbourhood of x0) such that A22: N2 c= N1 and A23: N2 c= N by CKB1:1;
A24: N2 c= ( dom f ) by A21,A23,XBOOLE_1:1;
A25: (for x being (Point of S) holds (x in N2 implies ( ( f /. x ) - ( f /. x0 ) ) = ( ( L . ( x - x0 ) ) + ( R /. ( x - x0 ) ) )))
proof
let x being (Point of S);
A26: ( R /. ( x - x0 ) ) = ( R . ( x - x0 ) ) by A2,PARTFUN1:def 6
.= ( 0. S ) by FUNCOP_1:7;
assume x in N2;
then x in N1 by A22;
hence ( ( f /. x ) - ( f /. x0 ) ) = ( x - ( f /. x0 ) ) by A10,A19
.= ( x - x0 ) by A10,A18
.= ( L . ( x - x0 ) ) by FUNCT_1:17
.= ( ( L . ( x - x0 ) ) + ( R /. ( x - x0 ) ) ) by A26,RLVECT_1:4;
end;
thus ( ( f `| Z ) /. x0 ) = ( diff (f,x0) ) by A17,A18,CKB45:def 1
.= ( id (the carrier of S) ) by A20,A24,A25,CKB40:def 1;
end;
