environ
vocabularies NUMBERS,XBOOLEAN,XXREAL_0,CARD_1,XBOOLE_0,SUBSET_1,FUNCT_2,MARGREL1,FUNCT_1,RELAT_1,TARSKI,FUNCOP_1,PARTIT1,EQREL_1,ZFMISC_1,SETFAM_1,BVFUNC_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,XBOOLEAN,MARGREL1,RELAT_1,FUNCT_1,FUNCT_2,SETFAM_1,EQREL_1,NUMBERS,PARTIT1,XXREAL_0,CKB1,CKB3,CKB4,CKB5,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB36,CKB41,CKB42,CKB55,CKB58,CKB59,CKB60,CKB61;
definitions TARSKI,XBOOLE_0,MARGREL1,XBOOLEAN,CKB1,CKB5,CKB6,CKB8,CKB9,CKB12,CKB13,CKB16,CKB17,CKB20,CKB21,CKB36,CKB41,CKB42,CKB55,CKB60,CKB61;
theorems TARSKI,FUNCT_1,FUNCT_2,MARGREL1,EQREL_1,SETFAM_1,PARTIT1,XBOOLE_0,FUNCOP_1,XBOOLEAN,CKB1,CKB5,CKB6,CKB8,CKB9,CKB12,CKB13,CKB16,CKB17,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66;
schemes DOMAIN_1,FUNCT_2,FUNCT_1,CKB2;
registrations SUBSET_1,XREAL_0,XBOOLEAN,EQREL_1,MARGREL1,FUNCT_1,FUNCT_2,CKB7,CKB14,CKB15,CKB45,CKB46,CKB47;
constructors SETFAM_1,XXREAL_0,XREAL_0,PARTIT1,BINARITH,RELSET_1,CKB3,CKB4,CKB5,CKB6,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB36,CKB41,CKB42,CKB55,CKB58,CKB59,CKB60,CKB61;
requirements REAL,SUBSET,BOOLE,ARITHM;
begin
reserve Y for non  empty set;
theorem
(for a being (Element of ( Funcs (Y,( BOOLEAN )) )) holds ( B_INF (a,( %O Y )) ) = ( B_INF a ))
proof
let a being (Element of ( Funcs (Y,( BOOLEAN )) ));
consider k3 being Function such that A1: ( B_INF (a,( %O Y )) ) = k3 and A2: ( dom k3 ) = Y and ( rng k3 ) c= ( BOOLEAN ) by FUNCT_2:def 2;
consider k4 being Function such that A3: ( B_INF a ) = k4 and A4: ( dom k4 ) = Y and ( rng k4 ) c= ( BOOLEAN ) by FUNCT_2:def 2;
(for y being (Element of Y) holds ( ( B_INF (a,( %O Y )) ) . y ) = ( ( B_INF a ) . y ))
proof
let y being (Element of Y);
A5:now
( EqClass (y,( %O Y )) ) in ( %O Y );
then ( EqClass (y,( %O Y )) ) in { Y } by PARTIT1:def 8;
then A6: ( EqClass (y,( %O Y )) ) = Y by TARSKI:def 1;
assume ((not (for x being (Element of Y) holds ( a . x ) = ( TRUE ))) & (for x being (Element of Y) holds (x in ( EqClass (y,( %O Y )) ) implies ( a . x ) = ( TRUE ))));
hence contradiction by A6;
end;
A7:now
assume that
A8: (not (for x being (Element of Y) holds ( a . x ) = ( TRUE )))
and
A9: (not (for x being (Element of Y) holds (x in ( EqClass (y,( %O Y )) ) implies ( a . x ) = ( TRUE ))));
( B_INF a ) = ( O_el Y ) by A8,CKB41:def 1;
then ( ( B_INF a ) . y ) = ( FALSE ) by CKB20:def 1;
hence thesis by A9,CKB60:def 1;
end;
now
assume that
A10: (for x being (Element of Y) holds ( a . x ) = ( TRUE ))
and
A11: (for x being (Element of Y) holds (x in ( EqClass (y,( %O Y )) ) implies ( a . x ) = ( TRUE )));
( B_INF a ) = ( I_el Y ) by A10,CKB41:def 1;
then ( ( B_INF a ) . y ) = ( TRUE ) by CKB21:def 1;
hence thesis by A11,CKB60:def 1;
end;
hence thesis by A5,A7;
end;
then (for u being set holds (u in Y implies ( k3 . u ) = ( k4 . u ))) by A1,A3;
hence thesis by A1,A2,A3,A4,FUNCT_1:2;
end;
