environ
vocabularies XBOOLE_0,SUBSET_1,TARSKI,ORDERS_2,WAYBEL_0,XXREAL_0,ZFMISC_1,RELAT_1,MCART_1,LATTICE3,RELAT_2,LATTICES,YELLOW_0,EQREL_1,REWRITE1,ORDINAL2,FUNCT_1,STRUCT_0,YELLOW_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,RELAT_2,RELSET_1,MCART_1,DOMAIN_1,FUNCT_2,BINOP_1,STRUCT_0,ORDERS_2,LATTICE3,YELLOW_0,WAYBEL_0,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27;
definitions LATTICE3,RELAT_2,TARSKI,WAYBEL_0,ORDERS_2,CKB18,CKB21;
theorems FUNCT_1,FUNCT_2,FUNCT_5,LATTICE3,MCART_1,ORDERS_2,RELAT_1,RELAT_2,RELSET_1,TARSKI,WAYBEL_0,YELLOW_0,YELLOW_2,ZFMISC_1,XBOOLE_0,BINOP_1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB18,CKB19,CKB21,CKB28,CKB29,CKB30,CKB37,CKB38;
schemes FUNCT_7,RELAT_1,CKB1,CKB14,CKB15,CKB16,CKB17;
registrations XBOOLE_0,SUBSET_1,RELSET_1,STRUCT_0,LATTICE3,YELLOW_0,ORDERS_2,WAYBEL_0,RELAT_1,CKB2,CKB3,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36;
constructors DOMAIN_1,LATTICE3,ORDERS_3,WAYBEL_0,RELSET_1,CKB18,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27;
requirements SUBSET,BOOLE;
begin
theorem
(for X,Y being non empty  reflexive RelStr holds ([: X,Y :] is  antisymmetric implies (X is  antisymmetric & Y is  antisymmetric)))
proof
let X being non empty  reflexive RelStr,Y being non empty  reflexive RelStr;
assume that
A1: [: X,Y :] is  antisymmetric;
(for x,y being (Element of X) holds ((x <= y & y <= x) implies x = y))
proof
set z = the (Element of Y);
A2: z <= z;
let x being (Element of X),y being (Element of X);
assume (x <= y & y <= x);
then ([ x,z ] <= [ y,z ] & [ y,z ] <= [ x,z ]) by A2,CKB28:1;
then [ x,z ] = [ y,z ] by A1,YELLOW_0:def 3;
hence thesis by ZFMISC_1:27;
end;
hence X is  antisymmetric by YELLOW_0:def 3;
(for x,y being (Element of Y) holds ((x <= y & y <= x) implies x = y))
proof
set z = the (Element of X);
A3: z <= z;
let x being (Element of Y),y being (Element of Y);
assume (x <= y & y <= x);
then ([ z,x ] <= [ z,y ] & [ z,y ] <= [ z,x ]) by A3,CKB28:1;
then [ z,x ] = [ z,y ] by A1,YELLOW_0:def 3;
hence thesis by ZFMISC_1:27;
end;
hence thesis by YELLOW_0:def 3;
end;
