environ
vocabularies REAL_1,PARTFUN1,NUMBERS,CARD_1,ARYTM_3,ARYTM_1,SEQ_1,RELAT_1,TARSKI,FUNCT_2,SUBSET_1,FUNCT_1,XBOOLE_0,LIMFUNC1,LIMFUNC2,SEQ_2,ORDINAL2,XXREAL_1,XXREAL_0,NAT_1,LIMFUNC3;
notations TARSKI,SUBSET_1,NUMBERS,XXREAL_0,REAL_1,NAT_1,SEQ_1,SEQ_2,VALUED_0,RCOMP_1,RELSET_1,PARTFUN1,FUNCT_2,LIMFUNC1,LIMFUNC2,LIMFUNC3;
definitions TARSKI,PROB_1,LIMFUNC1;
theorems TARSKI,NAT_1,FUNCT_1,SEQ_4,RCOMP_1,LIMFUNC1,LIMFUNC2,LIMFUNC3,RELAT_1,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_1,FUNCT_2,VALUED_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76;
registrations RELSET_1,MEMBERED,VALUED_0,ORDINAL1,NUMBERS,XBOOLE_0,SEQ_4,FUNCT_2;
constructors PARTFUN1,REAL_1,NAT_1,SEQ_2,SEQM_3,PROB_1,RCOMP_1,RFUNCT_2,LIMFUNC1,LIMFUNC2,LIMFUNC3,SEQ_1,MEMBERED,RELSET_1;
requirements SUBSET,ARITHM,BOOLE;
begin
reserve r for Real;
reserve r1 for Real;
reserve r2 for Real;
reserve g for Real;
reserve g1 for Real;
reserve g2 for Real;
reserve x0 for Real;
reserve f1 for (PartFunc of ( REAL ),( REAL ));
reserve f2 for (PartFunc of ( REAL ),( REAL ));
theorem
((((f1 is_convergent_in x0 & f2 is_right_convergent_in ( lim (f1,x0) )) & (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((r1 < g1 & g1 < x0) & g1 in ( dom ( f2 * f1 ) )) & g2 < r2) & x0 < g2) & g2 in ( dom ( f2 * f1 ) )))))))) & (ex g st (( 0 ) < g & (for r holds (r in ( ( dom f1 ) /\ ( ]. ( x0 - g ),x0 .[ \/ ]. x0,( x0 + g ) .[ ) ) implies ( lim (f1,x0) ) < ( f1 . r )))))) implies (( f2 * f1 ) is_convergent_in x0 & ( lim (( f2 * f1 ),x0) ) = ( lim_right (f2,( lim (f1,x0) )) )))
proof
assume that
A1: f1 is_convergent_in x0
and
A2: f2 is_right_convergent_in ( lim (f1,x0) )
and
A3: (for r1 holds (for r2 holds ((r1 < x0 & x0 < r2) implies (ex g1 st (ex g2 st (((((r1 < g1 & g1 < x0) & g1 in ( dom ( f2 * f1 ) )) & g2 < r2) & x0 < g2) & g2 in ( dom ( f2 * f1 ) )))))));
given g such that
A4: ( 0 ) < g
and
A5: (for r holds (r in ( ( dom f1 ) /\ ( ]. ( x0 - g ),x0 .[ \/ ]. x0,( x0 + g ) .[ ) ) implies ( lim (f1,x0) ) < ( f1 . r )));

A6:now
let s being Real_Sequence;
assume that
A7: (s is  convergent & ( lim s ) = x0)
and
A8: ( rng s ) c= ( ( dom ( f2 * f1 ) ) \ { x0 } );
consider k being (Element of ( NAT )) such that A9: (for n being (Element of ( NAT )) holds (k <= n implies (( x0 - g ) < ( s . n ) & ( s . n ) < ( x0 + g )))) by A4,A7,LIMFUNC3:7;
set q = ( ( f1 /* s ) ^\ k );
A10: ( rng s ) c= ( dom ( f2 * f1 ) ) by A8,CKB4:1;
A11: ( rng s ) c= ( dom f1 ) by A8,CKB4:1;
now
let x being set;
assume x in ( rng q );
then consider n being (Element of ( NAT )) such that A12: ( q . n ) = x by FUNCT_2:113;
A13: ( f1 . ( s . ( n + k ) ) ) = ( ( f1 /* s ) . ( n + k ) ) by A11,FUNCT_2:108
.= x by A12,NAT_1:def 3;
k <= ( n + k ) by NAT_1:12;
then (( x0 - g ) < ( s . ( n + k ) ) & ( s . ( n + k ) ) < ( x0 + g )) by A9;
then ( s . ( n + k ) ) in { g1: (( x0 - g ) < g1 & g1 < ( x0 + g )) };
then A14: ( s . ( n + k ) ) in ]. ( x0 - g ),( x0 + g ) .[ by RCOMP_1:def 2;
A15: ( s . ( n + k ) ) in ( rng s ) by VALUED_0:28;
then (not ( s . ( n + k ) ) in { x0 }) by A8,XBOOLE_0:def 5;
then ( s . ( n + k ) ) in ( ]. ( x0 - g ),( x0 + g ) .[ \ { x0 } ) by A14,XBOOLE_0:def 5;
then ( s . ( n + k ) ) in ( ]. ( x0 - g ),x0 .[ \/ ]. x0,( x0 + g ) .[ ) by A4,LIMFUNC3:4;
then ( s . ( n + k ) ) in ( ( dom f1 ) /\ ( ]. ( x0 - g ),x0 .[ \/ ]. x0,( x0 + g ) .[ ) ) by A11,A15,XBOOLE_0:def 4;
then ( f1 . ( s . ( n + k ) ) ) > ( lim (f1,x0) ) by A5;
then ( f1 . ( s . ( n + k ) ) ) in { g2: ( lim (f1,x0) ) < g2 };
then A16: ( f1 . ( s . ( n + k ) ) ) in ( right_open_halfline ( lim (f1,x0) ) ) by XXREAL_1:230;
( f1 . ( s . ( n + k ) ) ) in ( dom f2 ) by A10,A15,FUNCT_1:11;
hence x in ( ( dom f2 ) /\ ( right_open_halfline ( lim (f1,x0) ) ) ) by A16,A13,XBOOLE_0:def 4;
end;
then A17: ( rng q ) c= ( ( dom f2 ) /\ ( right_open_halfline ( lim (f1,x0) ) ) ) by TARSKI:def 3;
( rng ( f1 /* s ) ) c= ( dom f2 ) by A8,CKB4:1;
then A18: ( f2 /* q ) = ( ( f2 /* ( f1 /* s ) ) ^\ k ) by VALUED_0:27
.= ( ( ( f2 * f1 ) /* s ) ^\ k ) by A10,VALUED_0:31;
A19: ( rng s ) c= ( ( dom f1 ) \ { x0 } ) by A8,CKB4:1;
then A20: ( f1 /* s ) is  convergent by A1,A2,A7,LIMFUNC3:def 4;
( lim ( f1 /* s ) ) = ( lim (f1,x0) ) by A1,A7,A19,LIMFUNC3:def 4;
then A21: ( lim q ) = ( lim (f1,x0) ) by A20,SEQ_4:20;
( lim_right (f2,( lim (f1,x0) )) ) = ( lim_right (f2,( lim (f1,x0) )) );
then A22: ( f2 /* q ) is  convergent by A2,A20,A21,A17,LIMFUNC2:def 8;
hence ( ( f2 * f1 ) /* s ) is  convergent by A18,SEQ_4:21;
( lim ( f2 /* q ) ) = ( lim_right (f2,( lim (f1,x0) )) ) by A2,A20,A21,A17,LIMFUNC2:def 8;
hence ( lim ( ( f2 * f1 ) /* s ) ) = ( lim_right (f2,( lim (f1,x0) )) ) by A22,A18,SEQ_4:22;
end;
hence ( f2 * f1 ) is_convergent_in x0 by A3,LIMFUNC3:def 1;
hence thesis by A6,LIMFUNC3:def 4;
end;
