environ
vocabularies NUMBERS,ZFMISC_1,RELAT_2,REWRITE1,XBOOLE_0,ORDERS_2,PRELAMB,SUBSET_1,IDEAL_1,TARSKI,RELAT_1,STRUCT_0,ARYTM_3,XXREAL_0,WAYBEL_0,LATTICE3,LATTICES,EQREL_1,CARD_FIL,YELLOW_0,ORDINAL2,BINOP_1,FUNCT_1,OPOSET_1,CARD_1,FUNCOP_1,FINSUB_1,YELLOW_1,ARYTM_0,WELLORD2,FINSEQ_1,FUNCT_7,NAT_1,ORDINAL1,ORDINAL4,FINSET_1,FINSEQ_5,ARYTM_1,ABCMIZ_0;
notations TARSKI,XBOOLE_0,ZFMISC_1,RELAT_1,RELAT_2,SUBSET_1,ORDINAL1,FINSUB_1,CARD_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,BINOP_1,FUNCOP_1,FINSET_1,FINSEQ_1,FUNCT_4,ALG_1,FINSEQ_5,NUMBERS,XCMPLX_0,NAT_1,DOMAIN_1,STRUCT_0,ORDERS_2,LATTICE3,REWRITE1,YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_7,XXREAL_0,CKB2,CKB3,CKB5,CKB6,CKB12,CKB13,CKB14,CKB16,CKB18,CKB19,CKB25,CKB29,CKB31,CKB33,CKB35,CKB37,CKB38,CKB45,CKB51,CKB52,CKB54,CKB62,CKB64,CKB68,CKB77,CKB97,CKB98,CKB100,CKB101,CKB102,CKB103,CKB104,CKB105,CKB111,CKB116,CKB119;
definitions TARSKI,XBOOLE_0,RELAT_2,FUNCT_1,FINSEQ_1,LATTICE3,REWRITE1,YELLOW_0,WAYBEL_0,STRUCT_0,RELSET_1,CKB3,CKB5,CKB6,CKB13,CKB16,CKB18,CKB19,CKB29,CKB31,CKB33,CKB35,CKB37,CKB38,CKB45,CKB51,CKB52,CKB54,CKB62,CKB64,CKB68,CKB77,CKB97,CKB100,CKB101,CKB102,CKB103,CKB104,CKB105,CKB111,CKB116,CKB119;
theorems TARSKI,XBOOLE_0,XBOOLE_1,SUBSET_1,FINSUB_1,NAT_1,FINSEQ_1,CARD_1,TREES_1,FINSEQ_5,FINSEQ_6,RELAT_1,RELSET_1,FUNCT_1,FUNCT_2,FUNCT_4,FUNCOP_1,STRUCT_0,ORDERS_2,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_4,YELLOW_7,WAYBEL_6,WAYBEL_8,ZFMISC_1,FINSEQ_2,FINSEQ_3,HILBERT2,REWRITE1,ORDINAL1,XREAL_1,XXREAL_0,PRE_POLY,CKB3,CKB5,CKB6,CKB11,CKB13,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB48,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91,CKB92,CKB93,CKB94,CKB95,CKB96,CKB97,CKB100,CKB101,CKB102,CKB103,CKB104,CKB105,CKB106,CKB107,CKB108,CKB109,CKB110,CKB111,CKB112,CKB113,CKB115,CKB116,CKB118,CKB119,CKB120,CKB122,CKB123,CKB124,CKB125,CKB126,CKB127,CKB128,CKB129,CKB130;
schemes XBOOLE_0,NAT_1,FUNCT_1,FUNCT_2,RECDEF_1,RELSET_1,ORDERS_1,CKB114,CKB121;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_2,FINSET_1,FINSUB_1,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,FINSEQ_5,REWRITE1,STRUCT_0,LATTICE3,YELLOW_0,WAYBEL_0,YELLOW_1,YELLOW_7,YELLOW_9,ORDINAL1,CARD_1,RELSET_1,CKB1,CKB4,CKB7,CKB8,CKB9,CKB10,CKB12,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB47,CKB49,CKB50,CKB65,CKB98,CKB99,CKB117;
constructors FINSUB_1,XXREAL_0,NAT_1,FINSEQ_5,REWRITE1,BORSUK_1,LATTICE3,WAYBEL_0,YELLOW_1,FUNCOP_1,XREAL_0,CKB3,CKB6,CKB12,CKB13,CKB16,CKB18,CKB19,CKB25,CKB29,CKB31,CKB33,CKB37,CKB38,CKB45,CKB51,CKB52,CKB54,CKB62,CKB64,CKB68,CKB77,CKB97,CKB98,CKB100,CKB101,CKB102,CKB104,CKB105,CKB111,CKB116,CKB119;
requirements BOOLE,SUBSET,NUMERALS,REAL,ARITHM;
begin
theorem
Th77: (for T being  Noetherian  adj-structured  reflexive  transitive  antisymmetric  with_suprema non void TAS-structure holds (for t1,t2 being (type of T) holds (( T @--> ) reduces t1,t2 implies (ex A being  finite (Subset of (the adjectives of T)) st (A is_properly_applicable_to t2 & t1 = ( A ast t2 ))))))
proof
let T being  Noetherian  adj-structured  reflexive  transitive  antisymmetric  with_suprema non void TAS-structure;
let t1 being (type of T),t2 being (type of T);
set R = ( T @--> );
given p being (RedSequence of R) such that
A1: ( p . 1 ) = t1
and
A2: t2 = ( p . ( len p ) );

defpred P[ set,set ]
 means
(ex j being (Element of ( NAT )) st (ex a being (adjective of T) st (ex t being (type of T) st (((($2 = a & $1 = j) & ( a ast t ) = ( p . j )) & t = ( p . ( j + 1 ) )) & a is_properly_applicable_to t))));
A3: ( len ( Rev p ) ) = ( len p ) by FINSEQ_5:def 3;
A4: ( ( ( len p ) - 1 ) + 1 ) = ( len p );
A5: ( len p ) >= ( ( 0 ) + 1 ) by NAT_1:13;
then consider i being Nat such that A6: ( len p ) = ( 1 + i ) by NAT_1:10;
reconsider i as (Element of ( NAT )) by ORDINAL1:def 12;
A7:now
let x being set;
assume A8: x in ( Seg i );
then reconsider j = x as (Element of ( NAT ));
A9: j >= 1 by A8,FINSEQ_1:1;
then A10: 1 <= ( j + 1 ) by NAT_1:13;
A11: j <= i by A8,FINSEQ_1:1;
then j < ( len p ) by A6,NAT_1:13;
then A12: j in ( dom p ) by A9,FINSEQ_3:25;
( j + 1 ) <= ( len p ) by A6,A11,XREAL_1:6;
then ( j + 1 ) in ( dom p ) by A10,FINSEQ_3:25;
then A13: [ ( p . j ),( p . ( j + 1 ) ) ] in R by A12,REWRITE1:def 2;
then reconsider q1 = ( p . j ),q2 = ( p . ( j + 1 ) ) as (type of T) by ZFMISC_1:87;
(ex a being (adjective of T) st (((not a in ( adjs q2 )) & a is_properly_applicable_to q2) & ( a ast q2 ) = q1)) by A13,CKB119:def 1;
hence (ex y being set st (y in (the adjectives of T) & P[ x,y ]));
end;
consider f being Function such that A14: (( dom f ) = ( Seg i ) & ( rng f ) c= (the adjectives of T)) and A15: (for x being set holds (x in ( Seg i ) implies P[ x,( f . x ) ])) from FUNCT_1:sch 5(A7);
f is FinSequence by A14,FINSEQ_1:def 2;
then reconsider f as (FinSequence of (the adjectives of T)) by A14,FINSEQ_1:def 4;
A16: ( len f ) = i by A14,FINSEQ_1:def 3;
set r = ( Rev f );
defpred P[ (Element of ( NAT )) ]
 means
(( 1 + $1 ) <= ( len p ) implies ( ( Rev p ) . ( 1 + $1 ) ) = ( ( apply (r,t2) ) . ( 1 + $1 ) ));
A17: ( len r ) = ( len f ) by FINSEQ_5:def 3;
A18:now
let j being (Element of ( NAT ));
assume that
A19: P[ j ];
now
A20: ( j + 1 ) >= 1 by NAT_1:11;
assume A21: ( 1 + ( j + 1 ) ) <= ( len p );
then ( j + 1 ) <= i by A6,XREAL_1:6;
then consider x being Nat such that A22: i = ( ( j + 1 ) + x ) by NAT_1:10;
reconsider x as (Element of ( NAT )) by ORDINAL1:def 12;
A23: ( ( i + 1 ) - ( j + 1 ) ) = ( x + 1 ) by A22;
( j + 1 ) < ( len p ) by A21,NAT_1:13;
then ( j + 1 ) in ( dom ( Rev p ) ) by A3,A20,FINSEQ_3:25;
then A24: ( ( Rev p ) . ( j + 1 ) ) = ( p . ( ( x + 1 ) + 1 ) ) by A6,A23,FINSEQ_5:def 3;
A25: ( ( i + 1 ) - ( 1 + ( j + 1 ) ) ) = x by A22;
( 1 + ( j + 1 ) ) >= 1 by NAT_1:11;
then ( 1 + ( j + 1 ) ) in ( dom ( Rev p ) ) by A3,A21,FINSEQ_3:25;
then A26: ( ( Rev p ) . ( 1 + ( j + 1 ) ) ) = ( p . ( x + 1 ) ) by A6,A25,FINSEQ_5:def 3;
i = ( ( x + 1 ) + j ) by A22;
then A27: i >= ( x + 1 ) by NAT_1:11;
( x + 1 ) >= 1 by NAT_1:11;
then ( x + 1 ) in ( Seg i ) by A27;
then consider k being (Element of ( NAT )),a being (adjective of T),t being (type of T) such that A28: ( f . ( x + 1 ) ) = a and A29: ( x + 1 ) = k and A30: ( a ast t ) = ( p . k ) and A31: t = ( p . ( k + 1 ) ) and a is_properly_applicable_to t by A15;
A32: ( j + 1 ) >= 1 by NAT_1:11;
( j + 1 ) <= i by A22,NAT_1:11;
then A33: ( j + 1 ) in ( dom r ) by A17,A16,A32,FINSEQ_3:25;
then ( r . ( j + 1 ) ) = ( f . ( ( ( len f ) - ( j + 1 ) ) + 1 ) ) by FINSEQ_5:def 3
.= a by A16,A22,A28;
hence ( ( Rev p ) . ( 1 + ( j + 1 ) ) ) = ( ( apply (r,t2) ) . ( 1 + ( j + 1 ) ) ) by A19,A21,A29,A30,A31,A33,A24,A26,CKB64:def 1,NAT_1:13;
end;
hence P[ ( j + 1 ) ];
end;
reconsider A = ( rng f ) as  finite (Subset of (the adjectives of T));
take A;
A34: ( len ( apply (r,t2) ) ) = ( ( len r ) + 1 ) by CKB64:def 1;
1 in ( dom ( Rev p ) ) by A5,A3,FINSEQ_3:25;
then ( ( Rev p ) . 1 ) = t2 by A2,A4,FINSEQ_5:def 3;
then A35: P[ ( 0 ) ] by CKB64:def 1;
A36: (for j being (Element of ( NAT )) holds P[ j ]) from NAT_1:sch 1(A35,A18);
now
let j being Nat;
assume 1 <= j;
then consider k being Nat such that A37: j = ( 1 + k ) by NAT_1:10;
k in ( NAT ) by ORDINAL1:def 12;
hence (j <= ( len p ) implies ( ( Rev p ) . j ) = ( ( apply (r,t2) ) . j )) by A36,A37;
end;
then A38: ( Rev p ) = ( apply (r,t2) ) by A6,A17,A34,A16,A3,FINSEQ_1:14;
then A39: p = ( Rev ( apply (r,t2) ) ) by FINSEQ_6:25;
A40: r is_properly_applicable_to t2
proof
let j being  natural number;
let a being (adjective of T);
let s being (type of T);
assume that
A41: j in ( dom r )
and
A42: a = ( r . j )
and
A43: s = ( ( apply (r,t2) ) . j );
j <= ( len r ) by A41,FINSEQ_3:25;
then consider k being Nat such that A44: ( len r ) = ( j + k ) by NAT_1:10;
A45: ( len r ) = ( len f ) by FINSEQ_5:def 3;
reconsider k as (Element of ( NAT )) by ORDINAL1:def 12;
A46: ( k + 1 ) >= 1 by NAT_1:11;
A47: j >= 1 by A41,FINSEQ_3:25;
then ( k + 1 ) <= i by A16,A44,A45,XREAL_1:6;
then ( ( ( len f ) - j ) + 1 ) in ( Seg i ) by A44,A45,A46;
then consider o being (Element of ( NAT )),b being (adjective of T),u being (type of T) such that A48: ( f . ( ( ( len f ) - j ) + 1 ) ) = b and A49: ( ( ( len f ) - j ) + 1 ) = o and ( b ast u ) = ( p . o ) and A50: u = ( p . ( o + 1 ) ) and A51: b is_properly_applicable_to u by A15;
A52: ( o + 1 ) >= 1 by NAT_1:11;
( i + 1 ) = ( ( k + 1 ) + j ) by A17,A16,A44;
then ( o + 1 ) <= ( len p ) by A6,A44,A45,A47,A49,XREAL_1:6;
then A53: ( o + 1 ) in ( dom p ) by A52,FINSEQ_3:25;
A54: a = b by A41,A42,A48,FINSEQ_5:def 3;
( ( ( len ( apply (r,t2) ) ) - ( o + 1 ) ) + 1 ) = j by A17,A34,A49;
hence thesis by A39,A43,A50,A51,A53,A54,FINSEQ_5:def 3;
end;
thus A is_properly_applicable_to t2
proof
take r;
thus thesis by A40,FINSEQ_5:57;
end;

( rng r ) = A by FINSEQ_5:57;
then ( A ast t2 ) = ( r ast t2 ) by A40,CKB96:1,CKB106:1
.= ( ( apply (r,t2) ) . ( ( len r ) + 1 ) );
hence thesis by A1,A34,A3,A38,FINSEQ_5:62;
end;
