environ
vocabularies REAL_1,FUNCT_1,NUMBERS,DIFF_1,ARYTM_3,CARD_1,NAT_1,RELAT_1,SQUARE_1,ZFMISC_1,ARYTM_1,VALUED_1,VALUED_0,XREAL_0,ORDINAL1,JGRAPH_2,SIN_COS,SIN_COS4;
notations SQUARE_1,ORDINAL1,XCMPLX_0,ZFMISC_1,REAL_1,NAT_1,NUMBERS,FUNCT_1,FUNCT_2,VALUED_1,SEQFUNC,RELAT_1,SIN_COS,DIFF_1,XREAL_0,VALUED_0,FCONT_1,SIN_COS4,FDIFF_9,CKB11,CKB15;
definitions DIFF_1,SIN_COS4,SQUARE_1,SIN_COS,FDIFF_9,CKB11,CKB15;
theorems DIFF_1,XCMPLX_1,SIN_COS4,ZFMISC_1,RFUNCT_1,FCONT_1,FDIFF_8,VALUED_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66;
registrations XREAL_0,RELSET_1,MEMBERED,FUNCT_2,NUMBERS,VALUED_0,VALUED_1;
constructors SQUARE_1,REAL_1,DIFF_1,PARTFUN3,SIN_COS,SIN_COS4,FCONT_1,SEQ_1,FDIFF_9,SEQFUNC,RELSET_1,VALUED_1,CKB11,CKB15;
requirements NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve x0 for Real;
reserve x1 for Real;
theorem
[! ( ( ( sin ) (#) ( cos ) ) (#) ( cos ) ),x0,x1 !] = ( ( ( 1 / 2 ) * ( ( ( cos ( ( x0 + x1 ) / 2 ) ) * ( sin ( ( x0 - x1 ) / 2 ) ) ) + ( ( cos ( ( 3 * ( x0 + x1 ) ) / 2 ) ) * ( sin ( ( 3 * ( x0 - x1 ) ) / 2 ) ) ) ) ) / ( x0 - x1 ) )
proof
set y = ( 3 * x0 );
set z = ( 3 * x1 );
[! ( ( ( sin ) (#) ( cos ) ) (#) ( cos ) ),x0,x1 !] = ( ( ( ( ( ( sin ) (#) ( cos ) ) . x0 ) * ( ( cos ) . x0 ) ) - ( ( ( ( sin ) (#) ( cos ) ) (#) ( cos ) ) . x1 ) ) / ( x0 - x1 ) ) by VALUED_1:5
.= ( ( ( ( ( ( sin ) . x0 ) * ( ( cos ) . x0 ) ) * ( ( cos ) . x0 ) ) - ( ( ( ( sin ) (#) ( cos ) ) (#) ( cos ) ) . x1 ) ) / ( x0 - x1 ) ) by VALUED_1:5
.= ( ( ( ( ( ( sin ) . x0 ) * ( ( cos ) . x0 ) ) * ( ( cos ) . x0 ) ) - ( ( ( ( sin ) (#) ( cos ) ) . x1 ) * ( ( cos ) . x1 ) ) ) / ( x0 - x1 ) ) by VALUED_1:5
.= ( ( ( ( ( sin x0 ) * ( cos x0 ) ) * ( cos x0 ) ) - ( ( ( sin x1 ) * ( cos x1 ) ) * ( cos x1 ) ) ) / ( x0 - x1 ) ) by VALUED_1:5
.= ( ( ( ( 1 / 4 ) * ( ( ( ( sin ( ( x0 + x0 ) - x0 ) ) - ( sin ( ( x0 + x0 ) - x0 ) ) ) + ( sin ( ( x0 + x0 ) - x0 ) ) ) + ( sin ( ( x0 + x0 ) + x0 ) ) ) ) - ( ( ( sin x1 ) * ( cos x1 ) ) * ( cos x1 ) ) ) / ( x0 - x1 ) ) by SIN_COS4:35
.= ( ( ( ( 1 / 4 ) * ( ( sin x0 ) + ( sin ( 3 * x0 ) ) ) ) - ( ( 1 / 4 ) * ( ( ( ( sin ( ( x1 + x1 ) - x1 ) ) - ( sin ( ( x1 + x1 ) - x1 ) ) ) + ( sin ( ( x1 + x1 ) - x1 ) ) ) + ( sin ( ( x1 + x1 ) + x1 ) ) ) ) ) / ( x0 - x1 ) ) by SIN_COS4:35
.= ( ( ( ( 1 / 4 ) * ( ( sin x0 ) - ( sin x1 ) ) ) + ( ( 1 / 4 ) * ( ( sin ( 3 * x0 ) ) - ( sin ( 3 * x1 ) ) ) ) ) / ( x0 - x1 ) )
.= ( ( ( ( 1 / 4 ) * ( 2 * ( ( cos ( ( x0 + x1 ) / 2 ) ) * ( sin ( ( x0 - x1 ) / 2 ) ) ) ) ) + ( ( 1 / 4 ) * ( ( sin y ) - ( sin z ) ) ) ) / ( x0 - x1 ) ) by SIN_COS4:16
.= ( ( ( ( 1 / 2 ) * ( ( cos ( ( x0 + x1 ) / 2 ) ) * ( sin ( ( x0 - x1 ) / 2 ) ) ) ) + ( ( 1 / 4 ) * ( 2 * ( ( cos ( ( y + z ) / 2 ) ) * ( sin ( ( y - z ) / 2 ) ) ) ) ) ) / ( x0 - x1 ) ) by SIN_COS4:16
.= ( ( ( 1 / 2 ) * ( ( ( cos ( ( x0 + x1 ) / 2 ) ) * ( sin ( ( x0 - x1 ) / 2 ) ) ) + ( ( cos ( ( 3 * ( x0 + x1 ) ) / 2 ) ) * ( sin ( ( 3 * ( x0 - x1 ) ) / 2 ) ) ) ) ) / ( x0 - x1 ) );
hence thesis;
end;
