environ
vocabularies XBOOLE_0,ANALOAF,SUBSET_1,DIRAF,PARSP_2,FDIFF_1,SEMI_AF1;
notations STRUCT_0,ANALOAF,DIRAF,CKB1,CKB3,CKB25;
definitions CKB1,CKB25;
theorems PARDEPAP,DIRAF,CKB1,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35;
registrations ANALOAF,STRUCT_0,CKB2;
constructors DIRAF,CKB1,CKB25;
begin
reserve SAS for Semi_Affine_Space;
reserve a for (Element of SAS);
reserve b for (Element of SAS);
reserve c for (Element of SAS);
reserve d for (Element of SAS);
theorem
Th49: (((a <> b & a,b,c is_collinear ) & a,b // c,d) implies a,c // b,d)
proof
assume that
A1: a <> b
and
A2: a,b,c is_collinear 
and
A3: a,b // c,d;
now
A4: a,b // a,c by A2,CKB25:def 1;
then a,b // c,b by CKB10:1;
then c,b // c,d by A1,A3,CKB1:def 1;
then A5: b,c // b,d by CKB10:1;
assume A6: b <> c;
b,c // a,c by A4,CKB10:1;
hence thesis by A6,A5,CKB1:def 1;
end;
hence thesis by A3;
end;
