environ
vocabularies NUMBERS,SUBSET_1,REAL_1,PARTFUN1,SEQFUNC,XREAL_0,ORDINAL1,VALUED_1,RELAT_1,ARYTM_1,MEMBER_1,FUNCT_1,ARYTM_3,TARSKI,XBOOLE_0,CARD_1,NAT_1,VALUED_0,ZFMISC_1,SEQ_1,FUNCOP_1,XXREAL_0,CARD_3,SERIES_1,DIFF_1,FUNCT_2;
notations ORDINAL1,XCMPLX_0,XREAL_0,REAL_1,NAT_1,SERIES_1,XXREAL_0,TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,FUNCT_1,PARTFUN1,VALUED_0,VALUED_1,SEQ_1,FUNCOP_1,NAT_D,NEWTON,MEASURE6,FUNCT_2,RELSET_1,SEQFUNC,CKB1,CKB2,CKB3,CKB5,CKB7,CKB9,CKB10,CKB22,CKB23,CKB31,CKB32;
definitions VALUED_1,CKB1,CKB2,CKB3,CKB5,CKB7,CKB9,CKB22,CKB31;
theorems FUNCT_2,PARTFUN1,SEQFUNC,ORDINAL1,FUNCT_1,SEQ_1,XBOOLE_0,XCMPLX_1,NEWTON,FUNCOP_1,SERIES_1,TARSKI,MEASURE6,RFUNCT_1,ZFMISC_1,VALUED_1,XREAL_1,RELSET_1,CKB1,CKB2,CKB3,CKB5,CKB7,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41;
schemes NAT_1,RECDEF_1,SEQ_1;
registrations XBOOLE_0,RELAT_1,ORDINAL1,PARTFUN1,NUMBERS,XREAL_0,MEMBERED,VALUED_0,VALUED_1,FUNCT_2,RELSET_1,CKB4,CKB6,CKB8;
constructors REAL_1,SEQFUNC,NEWTON,SERIES_1,MEASURE6,NAT_D,PARTFUN3,SEQ_1,FUNCOP_1,RELSET_1,CKB1,CKB2,CKB3,CKB5,CKB7,CKB9,CKB22,CKB31;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve k for (Element of ( NAT ));
reserve h for Real;
reserve x for Real;
reserve f for (Function of ( REAL ),( REAL ));
theorem
( ( ( fdif (f,h) ) . ( ( 2 * n ) + 1 ) ) . x ) = ( ( ( cdif (f,h) ) . ( ( 2 * n ) + 1 ) ) . ( ( x + ( n * h ) ) + ( h / 2 ) ) )
proof
defpred X[ (Element of ( NAT )) ]
 means
(for x holds ( ( ( fdif (f,h) ) . ( ( 2 * $1 ) + 1 ) ) . x ) = ( ( ( cdif (f,h) ) . ( ( 2 * $1 ) + 1 ) ) . ( ( x + ( $1 * h ) ) + ( h / 2 ) ) ));
A1: (for k holds (X[ k ] implies X[ ( k + 1 ) ]))
proof
let k;
assume A2: (for x holds ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . x ) = ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( k * h ) ) + ( h / 2 ) ) ));
let x;
A3: ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + h ) + h ) ) = ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( ( ( x + h ) + h ) + ( k * h ) ) + ( h / 2 ) ) ) by A2
.= ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 2 ) * h ) ) + ( h / 2 ) ) );
A4: ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( x + h ) ) = ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( ( x + h ) + ( k * h ) ) + ( h / 2 ) ) ) by A2
.= ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) );
set r3 = ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( k * h ) ) + ( h / 2 ) ) );
set r2 = ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) );
set r1 = ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 2 ) * h ) ) + ( h / 2 ) ) );
A5: ( ( fdif (f,h) ) . ( 2 * ( k + 1 ) ) ) is (Function of ( REAL ),( REAL )) by CKB12:1;
A6: ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) is (Function of ( REAL ),( REAL )) by CKB33:1;
A7: ( ( cdif (f,h) ) . ( 2 * ( k + 1 ) ) ) is (Function of ( REAL ),( REAL )) by CKB33:1;
A8: ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) is (Function of ( REAL ),( REAL )) by CKB12:1;
A9: ( ( ( cdif (f,h) ) . ( 2 * ( k + 1 ) ) ) . ( x + ( ( k + 1 ) * h ) ) ) = ( ( ( cdif (f,h) ) . ( ( ( 2 * k ) + 1 ) + 1 ) ) . ( x + ( ( k + 1 ) * h ) ) )
.= ( ( cD (( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ),h) ) . ( x + ( ( k + 1 ) * h ) ) ) by CKB31:def 1
.= ( ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) ) - ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) - ( h / 2 ) ) ) ) by A6,CKB15:1
.= ( ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) ) - ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( k * h ) ) + ( h / 2 ) ) ) );
A10: ( ( ( cdif (f,h) ) . ( 2 * ( k + 1 ) ) ) . ( x + ( ( k + 2 ) * h ) ) ) = ( ( ( cdif (f,h) ) . ( ( ( 2 * k ) + 1 ) + 1 ) ) . ( x + ( ( k + 2 ) * h ) ) )
.= ( ( cD (( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ),h) ) . ( x + ( ( k + 2 ) * h ) ) ) by CKB31:def 1
.= ( ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 2 ) * h ) ) + ( h / 2 ) ) ) - ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 2 ) * h ) ) - ( h / 2 ) ) ) ) by A6,CKB15:1
.= ( ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 2 ) * h ) ) + ( h / 2 ) ) ) - ( ( ( cdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) ) );
A11: ( ( ( cdif (f,h) ) . ( ( 2 * ( k + 1 ) ) + 1 ) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) ) = ( ( cD (( ( cdif (f,h) ) . ( 2 * ( k + 1 ) ) ),h) ) . ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) ) by CKB31:def 1
.= ( ( ( ( cdif (f,h) ) . ( 2 * ( k + 1 ) ) ) . ( ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) + ( h / 2 ) ) ) - ( ( ( cdif (f,h) ) . ( 2 * ( k + 1 ) ) ) . ( ( ( x + ( ( k + 1 ) * h ) ) + ( h / 2 ) ) - ( h / 2 ) ) ) ) by A7,CKB15:1
.= ( ( r1 - r2 ) - ( r2 - r3 ) ) by A10,A9;
( ( ( fdif (f,h) ) . ( ( 2 * ( k + 1 ) ) + 1 ) ) . x ) = ( ( fD (( ( fdif (f,h) ) . ( 2 * ( k + 1 ) ) ),h) ) . x ) by CKB9:def 1
.= ( ( ( ( fdif (f,h) ) . ( 2 * ( k + 1 ) ) ) . ( x + h ) ) - ( ( ( fdif (f,h) ) . ( 2 * ( k + 1 ) ) ) . x ) ) by A5,CKB13:1
.= ( ( ( fD (( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ),h) ) . ( x + h ) ) - ( ( ( fdif (f,h) ) . ( ( ( 2 * k ) + 1 ) + 1 ) ) . x ) ) by CKB9:def 1
.= ( ( ( fD (( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ),h) ) . ( x + h ) ) - ( ( fD (( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ),h) ) . x ) ) by CKB9:def 1
.= ( ( ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + h ) + h ) ) - ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( x + h ) ) ) - ( ( fD (( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ),h) ) . x ) ) by A8,CKB13:1
.= ( ( ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( ( x + h ) + h ) ) - ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( x + h ) ) ) - ( ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . ( x + h ) ) - ( ( ( fdif (f,h) ) . ( ( 2 * k ) + 1 ) ) . x ) ) ) by A8,CKB13:1
.= ( ( r1 - r2 ) - ( r2 - r3 ) ) by A2,A3,A4;
hence thesis by A11;
end;
A12: X[ ( 0 ) ]
proof
let x;
( ( ( fdif (f,h) ) . ( ( 2 * ( 0 ) ) + 1 ) ) . x ) = ( ( fD (( ( fdif (f,h) ) . ( 0 ) ),h) ) . x ) by CKB9:def 1
.= ( ( fD (f,h) ) . x ) by CKB9:def 1
.= ( ( f . ( x + h ) ) - ( f . x ) ) by CKB13:1
.= ( ( f . ( ( x + ( h / 2 ) ) + ( h / 2 ) ) ) - ( f . ( ( x + ( h / 2 ) ) - ( h / 2 ) ) ) )
.= ( ( cD (f,h) ) . ( x + ( h / 2 ) ) ) by CKB15:1
.= ( ( cD (( ( cdif (f,h) ) . ( 0 ) ),h) ) . ( x + ( h / 2 ) ) ) by CKB31:def 1
.= ( ( ( cdif (f,h) ) . ( ( 2 * ( 0 ) ) + 1 ) ) . ( ( x + ( ( 0 ) * h ) ) + ( h / 2 ) ) ) by CKB31:def 1;
hence thesis;
end;
(for n holds X[ n ]) from NAT_1:sch 1(A12,A1);
hence thesis;
end;
