environ
vocabularies NUMBERS,XBOOLE_0,PRE_TOPC,METRIC_1,REAL_1,XXREAL_0,CARD_1,ARYTM_3,COMPLEX1,ARYTM_1,SETFAM_1,NATTRA_1,RCOMP_1,SUBSET_1,STRUCT_0,TARSKI,ZFMISC_1,PCOMPS_1,FINSET_1,FUNCT_1,CARD_3,FUNCOP_1,COMPTS_1,RELAT_1,ORDINAL1,RLVECT_3,XREAL_0,CARD_5,NEWTON,FINSEQ_1,PSCOMP_1,ORDINAL2,TOPMETR,TMAP_1,BINOP_1,FUNCT_2,SETWISEO,COH_SP,FINSOP_1,NAT_1,RELAT_2,NAGATA_1;
notations BINOP_1,SETWISEO,TARSKI,XBOOLE_0,SUBSET_1,SETFAM_1,RELAT_1,FUNCT_1,ORDINAL1,COMPLEX1,RELSET_1,FUNCT_2,FINSEQ_1,ZFMISC_1,PCOMPS_1,PRE_TOPC,FINSET_1,CARD_1,XCMPLX_0,NUMBERS,XXREAL_0,XREAL_0,REAL_1,NAT_1,FINSOP_1,VALUED_1,STRUCT_0,TOPS_2,COMPTS_1,METRIC_1,NEWTON,CARD_3,PROB_1,FUNCOP_1,CANTOR_1,DOMAIN_1,TOPMETR,PSCOMP_1,BORSUK_1,TMAP_1,CKB3,CKB20,CKB21,CKB22,CKB23,CKB26,CKB27,CKB28,CKB33,CKB34;
definitions PCOMPS_1,TARSKI,BINOP_1,SUBSET_1,COMPTS_1,PRE_TOPC,STRUCT_0,CKB3,CKB23,CKB26,CKB27,CKB33,CKB34;
theorems FUNCT_1,FUNCT_2,METRIC_1,XREAL_0,XCMPLX_1,ABSVALUE,TOPMETR,TMAP_1,CARD_1,PCOMPS_1,PCOMPS_2,BORSUK_1,XBOOLE_1,TARSKI,SETFAM_1,XBOOLE_0,SUBSET_1,TOPS_1,TOPS_2,PRE_TOPC,REALSET1,COMPTS_1,CARD_3,URYSOHN1,NAT_1,YELLOW_9,FINSEQ_1,CARD_2,FINSOP_1,SETWISEO,NEWTON,TOPREAL6,ZFMISC_1,BINOP_1,SEQ_2,PROB_1,FUNCOP_1,XREAL_1,COMPLEX1,XXREAL_0,PREPOWER,ORDINAL1,VALUED_1,CKB1,CKB2,CKB3,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB16,CKB17,CKB18,CKB19,CKB23,CKB24,CKB26,CKB27,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39;
schemes FUNCT_1,FRAENKEL,FUNCT_2,NAT_1;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,FINSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,FINSEQ_1,CARD_LAR,STRUCT_0,TOPS_1,COMPTS_1,METRIC_1,BORSUK_1,TOPMETR,PSCOMP_1,VALUED_0,VALUED_1,FUNCT_2,CARD_3,FUNCT_1,PRE_TOPC,ZFMISC_1,CKB4,CKB5,CKB15,CKB25,CKB29,CKB30;
constructors SETFAM_1,SETWISEO,REAL_1,SQUARE_1,NAT_1,PROB_1,FUNCOP_1,FINSOP_1,NEWTON,REALSET1,CARD_5,TOPS_2,COMPTS_1,TMAP_1,CANTOR_1,PCOMPS_1,PSCOMP_1,URYSOHN3,CKB3,CKB21,CKB22,CKB23,CKB26,CKB27,CKB33,CKB34;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve T for non empty TopSpace;
reserve A for (Subset of T);
reserve U for  open (Subset of T);
reserve n for (Element of ( NAT ));
theorem
Th18: ((for A holds (for U holds (((A is  closed & U is  open) & A c= U) implies (ex W being (Function of ( NAT ),( bool (the carrier of T) )) st ((A c= ( Union W ) & ( Union W ) c= U) & (for n holds (( Cl ( W . n ) ) c= U & ( W . n ) is  open))))))) implies T is  normal)
proof
assume A1: (for A holds (for U holds (((A is  closed & U is  open) & A c= U) implies (ex W being (Function of ( NAT ),( bool (the carrier of T) )) st ((A c= ( Union W ) & ( Union W ) c= U) & (for n holds (( Cl ( W . n ) ) c= U & ( W . n ) is  open)))))));
(for A,B being (Subset of T) holds (((((A <> ( {} ) & B <> ( {} )) & A is  closed) & B is  closed) & A misses B) implies (ex UA,WB being (Subset of T) st ((((UA is  open & WB is  open) & A c= UA) & B c= WB) & UA misses WB))))
proof
let A being (Subset of T),B being (Subset of T);
assume that
A <> ( {} )
and
B <> ( {} )
and
A2: (A is  closed & B is  closed)
and
A3: A misses B;
set W = ( ( [#] T ) \ B );
A c= ( B ` ) by A3,SUBSET_1:23;
then consider Wn being (Function of ( NAT ),( bool (the carrier of T) )) such that A4: A c= ( Union Wn ) and ( Union Wn ) c= W and A5: (for n holds (( Cl ( Wn . n ) ) c= W & ( Wn . n ) is  open)) by A1,A2;
set U = ( ( [#] T ) \ A );
B c= ( A ` ) by A3,SUBSET_1:23;
then consider Un being (Function of ( NAT ),( bool (the carrier of T) )) such that A6: B c= ( Union Un ) and ( Union Un ) c= U and A7: (for n holds (( Cl ( Un . n ) ) c= U & ( Un . n ) is  open)) by A1,A2;
deffunc UW((Element of ( NAT ))) = ( ( Un . $1 ) \ ( union { ( Cl ( Wn . k ) ) where k is (Element of ( NAT )): k in ( ( Seg $1 ) \/ { ( 0 ) } ) } ) );
defpred E2[ (Element of ( NAT )),set ]
 means
$2 = UW($1);
A8: (for k being (Element of ( NAT )) holds (ex y being (Subset of T) st E2[ k,y ]));
consider FUW being (Function of ( NAT ),( bool (the carrier of T) )) such that A9: (for k being (Element of ( NAT )) holds E2[ k,( FUW . k ) ]) from FUNCT_2:sch 3(A8);
(for n holds ( FUW . n ) is  open)
proof
let n;
set CLn = { ( Cl ( Wn . k ) ) where k is (Element of ( NAT )): k in ( ( Seg n ) \/ { ( 0 ) } ) };
now
let C being set;
assume C in CLn;
then (ex k being (Element of ( NAT )) st (C = ( Cl ( Wn . k ) ) & k in ( ( Seg n ) \/ { ( 0 ) } )));
hence C in ( bool (the carrier of T) );
end;
then reconsider CLn as (Subset-Family of T) by TARSKI:def 3;
deffunc CL((Element of ( NAT ))) = ( Cl ( Wn . $1 ) );
A10: ( ( Seg n ) \/ { ( 0 ) } ) is  finite;
A11: { CL(k) where k is (Element of ( NAT )): k in ( ( Seg n ) \/ { ( 0 ) } ) } is  finite from FRAENKEL:sch 21(A10);
now
let A;
assume A in CLn;
then (ex k being (Element of ( NAT )) st (A = ( Cl ( Wn . k ) ) & k in ( ( Seg n ) \/ { ( 0 ) } )));
hence A is  closed;
end;
then A12: CLn is  closed by TOPS_2:def 2;
( Un . n ) is  open by A7;
then ( ( Un . n ) \ ( union CLn ) ) is  open by A11,A12,CKB38:1,TOPS_2:21;
hence thesis by A9;
end;
then A13: ( Union FUW ) is  open by CKB39:1;
A14: (for n holds B misses ( Cl ( Wn . n ) ))
proof
let n;
( Cl ( Wn . n ) ) c= W by A5;
hence thesis by XBOOLE_1:63,XBOOLE_1:79;
end;
now
let b being set;
assume that
A15: b in B
and
A16: (not b in ( Union FUW ));
consider k being (Element of ( NAT )) such that A17: b in ( Un . k ) by A6,A15,PROB_1:12;
(not b in ( union { ( Cl ( Wn . m ) ) where m is (Element of ( NAT )): m in ( ( Seg k ) \/ { ( 0 ) } ) } ))
proof
assume b in ( union { ( Cl ( Wn . m ) ) where m is (Element of ( NAT )): m in ( ( Seg k ) \/ { ( 0 ) } ) } );
then consider CL being set such that A18: b in CL and A19: CL in { ( Cl ( Wn . m ) ) where m is (Element of ( NAT )): m in ( ( Seg k ) \/ { ( 0 ) } ) } by TARSKI:def 4;
consider m being (Element of ( NAT )) such that A20: CL = ( Cl ( Wn . m ) ) and m in ( ( Seg k ) \/ { ( 0 ) } ) by A19;
B meets ( Cl ( Wn . m ) ) by A15,A18,A20,XBOOLE_0:3;
hence contradiction by A14;
end;
then b in UW(k) by A17,XBOOLE_0:def 5;
then b in ( FUW . k ) by A9;
hence contradiction by A16,PROB_1:12;
end;
then A21: B c= ( Union FUW ) by TARSKI:def 3;
deffunc WU((Element of ( NAT ))) = ( ( Wn . $1 ) \ ( union { ( Cl ( Un . k ) ) where k is (Element of ( NAT )): k in ( ( Seg $1 ) \/ { ( 0 ) } ) } ) );
defpred E1[ (Element of ( NAT )),set ]
 means
$2 = WU($1);
A22: (for k being (Element of ( NAT )) holds (ex y being (Subset of T) st E1[ k,y ]));
consider FWU being (Function of ( NAT ),( bool (the carrier of T) )) such that A23: (for k being (Element of ( NAT )) holds E1[ k,( FWU . k ) ]) from FUNCT_2:sch 3(A22);
A24: ( Union FUW ) misses ( Union FWU )
proof
assume ( Union FUW ) meets ( Union FWU );
then consider f being set such that A25: f in ( Union FUW ) and A26: f in ( Union FWU ) by XBOOLE_0:3;
consider n being (Element of ( NAT )) such that A27: f in ( FUW . n ) by A25,PROB_1:12;
consider k being (Element of ( NAT )) such that A28: f in ( FWU . k ) by A26,PROB_1:12;
A29: (n >= k implies ( FUW . n ) misses ( FWU . k ))
proof
assume that
A30: n >= k
and
A31: ( FUW . n ) meets ( FWU . k );
consider w being set such that A32: w in ( FUW . n ) and A33: w in ( FWU . k ) by A31,XBOOLE_0:3;
w in ( ( Wn . k ) \ ( union { ( Cl ( Un . l ) ) where l is (Element of ( NAT )): l in ( ( Seg k ) \/ { ( 0 ) } ) } ) ) by A23,A33;
then A34: w in ( Wn . k ) by XBOOLE_0:def 5;
(k = ( 0 ) or k in ( Seg k )) by FINSEQ_1:3;
then (k in { ( 0 ) } or (k in ( Seg k ) & ( Seg k ) c= ( Seg n ))) by A30,FINSEQ_1:5,TARSKI:def 1;
then k in ( ( Seg n ) \/ { ( 0 ) } ) by XBOOLE_0:def 3;
then A35: (( Wn . k ) c= ( Cl ( Wn . k ) ) & ( Cl ( Wn . k ) ) in { ( Cl ( Wn . l ) ) where l is (Element of ( NAT )): l in ( ( Seg n ) \/ { ( 0 ) } ) }) by PRE_TOPC:18;
w in ( ( Un . n ) \ ( union { ( Cl ( Wn . l ) ) where l is (Element of ( NAT )): l in ( ( Seg n ) \/ { ( 0 ) } ) } ) ) by A9,A32;
then (not w in ( union { ( Cl ( Wn . l ) ) where l is (Element of ( NAT )): l in ( ( Seg n ) \/ { ( 0 ) } ) } )) by XBOOLE_0:def 5;
hence contradiction by A34,A35,TARSKI:def 4;
end;
(n <= k implies ( FUW . n ) misses ( FWU . k ))
proof
assume that
A36: n <= k
and
A37: ( FUW . n ) meets ( FWU . k );
consider u being set such that A38: u in ( FUW . n ) and A39: u in ( FWU . k ) by A37,XBOOLE_0:3;
u in ( ( Un . n ) \ ( union { ( Cl ( Wn . l ) ) where l is (Element of ( NAT )): l in ( ( Seg n ) \/ { ( 0 ) } ) } ) ) by A9,A38;
then A40: u in ( Un . n ) by XBOOLE_0:def 5;
(n = ( 0 ) or n in ( Seg n )) by FINSEQ_1:3;
then (n in { ( 0 ) } or (n in ( Seg n ) & ( Seg n ) c= ( Seg k ))) by A36,FINSEQ_1:5,TARSKI:def 1;
then n in ( ( Seg k ) \/ { ( 0 ) } ) by XBOOLE_0:def 3;
then A41: (( Un . n ) c= ( Cl ( Un . n ) ) & ( Cl ( Un . n ) ) in { ( Cl ( Un . l ) ) where l is (Element of ( NAT )): l in ( ( Seg k ) \/ { ( 0 ) } ) }) by PRE_TOPC:18;
u in ( ( Wn . k ) \ ( union { ( Cl ( Un . l ) ) where l is (Element of ( NAT )): l in ( ( Seg k ) \/ { ( 0 ) } ) } ) ) by A23,A39;
then (not u in ( union { ( Cl ( Un . l ) ) where l is (Element of ( NAT )): l in ( ( Seg k ) \/ { ( 0 ) } ) } )) by XBOOLE_0:def 5;
hence contradiction by A40,A41,TARSKI:def 4;
end;
hence contradiction by A27,A28,A29,XBOOLE_0:3;
end;
(for n holds ( FWU . n ) is  open)
proof
let n;
set CLn = { ( Cl ( Un . k ) ) where k is (Element of ( NAT )): k in ( ( Seg n ) \/ { ( 0 ) } ) };
now
let C being set;
assume C in CLn;
then (ex k being (Element of ( NAT )) st (C = ( Cl ( Un . k ) ) & k in ( ( Seg n ) \/ { ( 0 ) } )));
hence C in ( bool (the carrier of T) );
end;
then reconsider CLn as (Subset-Family of T) by TARSKI:def 3;
deffunc CL((Element of ( NAT ))) = ( Cl ( Un . $1 ) );
A42: ( ( Seg n ) \/ { ( 0 ) } ) is  finite;
A43: { CL(k) where k is (Element of ( NAT )): k in ( ( Seg n ) \/ { ( 0 ) } ) } is  finite from FRAENKEL:sch 21(A42);
now
let A;
assume A in CLn;
then (ex k being (Element of ( NAT )) st (A = ( Cl ( Un . k ) ) & k in ( ( Seg n ) \/ { ( 0 ) } )));
hence A is  closed;
end;
then A44: CLn is  closed by TOPS_2:def 2;
( Wn . n ) is  open by A5;
then ( ( Wn . n ) \ ( union CLn ) ) is  open by A43,A44,CKB38:1,TOPS_2:21;
hence thesis by A23;
end;
then A45: ( Union FWU ) is  open by CKB39:1;
A46: (for n holds A misses ( Cl ( Un . n ) ))
proof
let n;
( Cl ( Un . n ) ) c= U by A7;
hence thesis by XBOOLE_1:63,XBOOLE_1:79;
end;
now
let a being set;
assume that
A47: a in A
and
A48: (not a in ( Union FWU ));
consider k being (Element of ( NAT )) such that A49: a in ( Wn . k ) by A4,A47,PROB_1:12;
(not a in ( union { ( Cl ( Un . m ) ) where m is (Element of ( NAT )): m in ( ( Seg k ) \/ { ( 0 ) } ) } ))
proof
assume a in ( union { ( Cl ( Un . m ) ) where m is (Element of ( NAT )): m in ( ( Seg k ) \/ { ( 0 ) } ) } );
then consider CL being set such that A50: a in CL and A51: CL in { ( Cl ( Un . m ) ) where m is (Element of ( NAT )): m in ( ( Seg k ) \/ { ( 0 ) } ) } by TARSKI:def 4;
consider m being (Element of ( NAT )) such that A52: CL = ( Cl ( Un . m ) ) and m in ( ( Seg k ) \/ { ( 0 ) } ) by A51;
A meets ( Cl ( Un . m ) ) by A47,A50,A52,XBOOLE_0:3;
hence contradiction by A46;
end;
then a in WU(k) by A49,XBOOLE_0:def 5;
then a in ( FWU . k ) by A23;
hence contradiction by A48,PROB_1:12;
end;
then A c= ( Union FWU ) by TARSKI:def 3;
hence thesis by A21,A24,A13,A45;
end;
hence thesis by COMPTS_1:def 3;
end;
