environ
vocabularies NUMBERS,NAT_1,FUNCT_1,ZFMISC_1,FINSEQ_1,RELAT_1,CARD_3,ARYTM_3,SUBSET_1,XXREAL_0,TARSKI,XBOOLE_0,FINSEQ_2,ARYTM_1,PARTFUN1,BINOP_2,ORDINAL4,CARD_1,FUNCOP_1,PROB_1,MESFUNC2,FUNCT_3,SUPINF_2,PROB_2,MEASURE1,ORDINAL1,XXREAL_2,ORDINAL2,SUPINF_1,XREAL_0,MESFUNC1,VALUED_0,COMPLEX1,SETFAM_1,FINSET_1,FINSOP_1,SETWISEO,INTEGRA1,REAL_1,MESFUNC3;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,ORDINAL1,CARD_1,NUMBERS,XCMPLX_0,NAT_1,REAL_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,XREAL_0,SETWOP_2,FINSEQ_1,SETFAM_1,FUNCOP_1,FINSOP_1,FUNCT_3,FINSET_1,PROB_1,PROB_2,XXREAL_0,XXREAL_2,SUPINF_1,SUPINF_2,MEASURE1,FINSEQOP,FINSEQ_2,BINOP_1,SEQ_1,BINOP_2,RVSUM_1,EXTREAL1,MESFUNC1,MESFUNC2,CKB12;
definitions TARSKI,XBOOLE_0,BINOP_1,SUPINF_2,MESFUNC1,CKB12;
theorems MEASURE1,TARSKI,FUNCT_1,FUNCT_2,NAT_1,SUPINF_2,EXTREAL1,EXTREAL2,ZFMISC_1,FINSEQ_1,FINSEQ_2,FINSEQ_3,FUNCOP_1,FINSEQ_4,PROB_2,FUNCT_3,XBOOLE_0,XBOOLE_1,RELAT_1,RVSUM_1,BINOP_2,MESFUNC2,MEASURE2,FINSOP_1,CARD_2,XREAL_1,XXREAL_0,ORDINAL1,NUMBERS,VALUED_1,XXREAL_2,VALUED_0,XXREAL_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes FINSEQ_1,FINSEQ_2,NAT_1,PARTFUN1,BINOP_1;
registrations SUBSET_1,RELAT_1,ORDINAL1,FUNCT_2,NUMBERS,XXREAL_0,XREAL_0,NAT_1,BINOP_2,MEMBERED,FINSEQ_1,MEASURE1,FINSET_1,VALUED_0,CARD_1,CARD_3,XXREAL_3,RELSET_1;
constructors PARTFUN1,BINOP_1,SETWISEO,REAL_1,NAT_1,FINSEQOP,PROB_2,FINSOP_1,RVSUM_1,MEASURE3,MEASURE6,EXTREAL1,MESFUNC1,BINARITH,MESFUNC2,SEQ_1,BINOP_2,SUPINF_1,RELSET_1,CKB12;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
theorem
Lm2: (for X being non  empty set holds (for S being (SigmaField of X) holds (for f being (PartFunc of X,( ExtREAL )) holds (((f is_simple_func_in S & (for x being set holds (x in ( dom f ) implies ( 0. ) <= ( f . x )))) & (for x being set holds (x in ( dom f ) implies ( 0. ) <> ( f . x )))) implies (ex F being (Finite_Sep_Sequence of S) st (ex a being (FinSequence of ( ExtREAL )) st ((F,a are_Re-presentation_of f & ( a . 1 ) = ( 0. )) & (for n being Nat holds ((2 <= n & n in ( dom a )) implies (( 0. ) < ( a . n ) & ( a . n ) < ( +infty )))))))))))
proof
let X being non  empty set;
let S being (SigmaField of X);
let f being (PartFunc of X,( ExtREAL ));
assume that
A1: f is_simple_func_in S
and
A2: (for x being set holds (x in ( dom f ) implies ( 0. ) <= ( f . x )))
and
A3: (for x being set holds (x in ( dom f ) implies ( 0. ) <> ( f . x )));
consider F1 being (Finite_Sep_Sequence of S) such that A4: ( dom f ) = ( union ( rng F1 ) ) and A5: (for n being Nat holds (for x,y being (Element of X) holds (((n in ( dom F1 ) & x in ( F1 . n )) & y in ( F1 . n )) implies ( f . x ) = ( f . y )))) by A1,MESFUNC2:def 4;
consider G being (Finite_Sep_Sequence of S) such that A6: ( union ( rng F1 ) ) = ( union ( rng G ) ) and A7: (for n being Nat holds (n in ( dom G ) implies (( G . n ) <> ( {} ) & (ex m being Nat st (m in ( dom F1 ) & ( F1 . m ) = ( G . n )))))) by CKB14:1;
set F = ( <* ( {} ) *> ^ G );
(( rng <* ( {} ) *> ) = { ( {} ) } & ( {} ) in S) by FINSEQ_1:38,MEASURE1:7;
then ( rng <* ( {} ) *> ) c= S by ZFMISC_1:31;
then ( ( rng <* ( {} ) *> ) \/ ( rng G ) ) c= S by XBOOLE_1:8;
then ( rng F ) c= S by FINSEQ_1:31;
then reconsider F as (FinSequence of S) by FINSEQ_1:def 4;
(for x,y being set holds (x <> y implies ( F . x ) misses ( F . y )))
proof
let x being set;
let y being set;
assume A8: x <> y;
now
per cases ;
case A9: (x in ( dom F ) & y in ( dom F ));
then reconsider x,y as (Element of ( NAT ));
A10: x in ( Seg ( len ( <* ( {} ) *> ^ G ) ) ) by A9,FINSEQ_1:def 3;
then A11: x <= ( len ( <* ( {} ) *> ^ G ) ) by FINSEQ_1:1;
A12: y in ( Seg ( len ( <* ( {} ) *> ^ G ) ) ) by A9,FINSEQ_1:def 3;
then A13: 1 <= y by FINSEQ_1:1;
A14: y <= ( len ( <* ( {} ) *> ^ G ) ) by A12,FINSEQ_1:1;
A15: 1 <= x by A10,FINSEQ_1:1;
now
per cases ;
case A16: (x = 1 or y = 1);
A17: ( dom <* ( {} ) *> ) = ( Seg 1 ) by FINSEQ_1:38;
now
per cases  by A16;
case A18: x = 1;
then x in ( dom <* ( {} ) *> ) by A17,FINSEQ_1:2,TARSKI:def 1;
then ( F . x ) = ( <* ( {} ) *> . x ) by FINSEQ_1:def 7;
then ( F . x ) = ( {} ) by A18,FINSEQ_1:def 8;
hence thesis by XBOOLE_1:65;
end;
case A19: y = 1;
then y in ( dom <* ( {} ) *> ) by A17,FINSEQ_1:2,TARSKI:def 1;
then ( F . y ) = ( <* ( {} ) *> . y ) by FINSEQ_1:def 7;
then ( F . y ) = ( {} ) by A19,FINSEQ_1:def 8;
hence thesis by XBOOLE_1:65;
end;
end;
hence thesis;
end;
case A20: (x <> 1 & y <> 1);
then 1 < y by A13,XXREAL_0:1;
then ( len <* ( {} ) *> ) < y by FINSEQ_1:40;
then A21: ( F . y ) = ( G . ( y - ( len <* ( {} ) *> ) ) ) by A14,FINSEQ_1:24;
1 < x by A15,A20,XXREAL_0:1;
then ( len <* ( {} ) *> ) < x by FINSEQ_1:40;
then A22: ( F . x ) = ( G . ( x - ( len <* ( {} ) *> ) ) ) by A11,FINSEQ_1:24;
( x - ( len <* ( {} ) *> ) ) <> ( y - ( len <* ( {} ) *> ) ) by A8;
hence thesis by A22,A21,PROB_2:def 2;
end;
end;
hence thesis;
end;
case ((not x in ( dom F )) or (not y in ( dom F )));
then (( F . x ) = ( {} ) or ( F . y ) = ( {} )) by FUNCT_1:def 2;
hence thesis by XBOOLE_1:65;
end;
end;
hence thesis;
end;
then reconsider F as (Finite_Sep_Sequence of S) by PROB_2:def 2;
A23: ( union ( rng F ) ) = ( union ( ( rng <* ( {} ) *> ) \/ ( rng G ) ) ) by FINSEQ_1:31
.= ( union ( { ( {} ) } \/ ( rng G ) ) ) by FINSEQ_1:38
.= ( ( union { ( {} ) } ) \/ ( union ( rng G ) ) ) by ZFMISC_1:78
.= ( ( {} ) \/ ( union ( rng G ) ) ) by ZFMISC_1:25
.= ( dom f ) by A4,A6;
defpred P[ Nat,(Element of ( ExtREAL )) ]
 means
((for x being (Element of X) holds (($1 in ( dom F ) & $1 = 1) implies $2 = ( 0. ))) & (for x being (Element of X) holds ((($1 in ( dom F ) & $1 >= 2) & x in ( F . $1 )) implies $2 = ( f . x ))));
A24: (for k being Nat holds (k in ( Seg ( len F ) ) implies (ex y being (Element of ( ExtREAL )) st P[ k,y ])))
proof
let k being Nat;
assume A25: k in ( Seg ( len F ) );
(ex y being (Element of ( ExtREAL )) st P[ k,y ])
proof
now
per cases ;
case A26: k = 1;
take y = ( 0. );
((for x being (Element of X) holds ((k in ( dom F ) & k = 1) implies y = ( 0. ))) & (for x being (Element of X) holds (((k in ( dom F ) & k >= 2) & x in ( F . k )) implies y = ( f . x )))) by A26;
hence thesis;
end;
case A27: k <> 1;
A28: k <= ( len F ) by A25,FINSEQ_1:1;
then k <= ( ( len <* ( {} ) *> ) + ( len G ) ) by FINSEQ_1:22;
then A29: ( k - ( len <* ( {} ) *> ) ) <= ( len G ) by XREAL_1:20;
1 <= k by A25,FINSEQ_1:1;
then 1 < k by A27,XXREAL_0:1;
then ( 1 + 1 ) <= k by NAT_1:13;
then A30: ( ( len <* ( {} ) *> ) + 1 ) <= k by FINSEQ_1:39;
then consider k2 being Nat such that A31: ( ( ( len <* ( {} ) *> ) + 1 ) + k2 ) = k by NAT_1:10;
reconsider k2 as (Element of ( NAT )) by ORDINAL1:def 12;
( 1 + k2 ) = ( k - ( len <* ( {} ) *> ) ) by A31;
then 1 <= ( 1 + k2 ) by A30,XREAL_1:19;
then ( 1 + k2 ) in ( Seg ( len G ) ) by A31,A29,FINSEQ_1:1;
then A32: ( 1 + k2 ) in ( dom G ) by FINSEQ_1:def 3;
then consider m1 being Nat such that A33: m1 in ( dom F1 ) and A34: ( F1 . m1 ) = ( G . ( 1 + k2 ) ) by A7;
k <= ( ( len <* ( {} ) *> ) + ( len G ) ) by A28,FINSEQ_1:22;
then A35: ( F . k ) = ( G . ( k - ( len <* ( {} ) *> ) ) ) by A30,FINSEQ_1:23
.= ( G . ( 1 + k2 ) ) by A31;
then ( F . k ) <> ( {} ) by A7,A32;
then consider z being set such that A36: z in ( F . k ) by XBOOLE_0:def 1;
take y = ( f . z );
( F . k ) in ( rng F1 ) by A35,A33,A34,FUNCT_1:3;
then ( F . k ) in S;
then reconsider z as (Element of X) by A36;
A37: (for x being (Element of X) holds (((k in ( dom F ) & k >= 2) & x in ( F . k )) implies y = ( f . x )))
proof
let x being (Element of X);
assume that
k in ( dom F )
and
k >= 2
and
A38: x in ( F . k );
z in ( F1 . m1 ) by A35,A36,A34;
hence thesis by A5,A35,A33,A34,A38;
end;
(for x being (Element of X) holds ((k in ( dom F ) & k = 1) implies y = ( 0. ))) by A27;
hence thesis by A37;
end;
end;
hence thesis;
end;
hence thesis;
end;
consider a being (FinSequence of ( ExtREAL )) such that A39: (( dom a ) = ( Seg ( len F ) ) & (for n being Nat holds (n in ( Seg ( len F ) ) implies P[ n,( a . n ) ]))) from FINSEQ_1:sch 5(A24);
A40: ( dom F ) = ( dom a ) by A39,FINSEQ_1:def 3;
A41: (for n being Nat holds (for x being (Element of X) holds (((n in ( dom F ) & n >= 2) & x in ( F . n )) implies ( a . n ) = ( f . x ))))
proof
let n being Nat;
let x being (Element of X);
assume that
A42: n in ( dom F )
and
A43: (n >= 2 & x in ( F . n ));
n in ( Seg ( len F ) ) by A42,FINSEQ_1:def 3;
hence thesis by A39,A42,A43;
end;
A44: (for n being Nat holds ((2 <= n & n in ( dom a )) implies (( 0. ) < ( a . n ) & ( a . n ) < ( +infty ))))
proof
let n being Nat;
assume that
A45: 2 <= n
and
A46: n in ( dom a );
( 1 + 1 ) <= n by A45;
then A47: ( ( len <* ( {} ) *> ) + 1 ) <= n by FINSEQ_1:39;
n <= ( len F ) by A39,A46,FINSEQ_1:1;
then n <= ( ( len <* ( {} ) *> ) + ( len G ) ) by FINSEQ_1:22;
then A48: ( F . n ) = ( G . ( n - ( len <* ( {} ) *> ) ) ) by A47,FINSEQ_1:23
.= ( G . ( n - 1 ) ) by FINSEQ_1:39;
(( dom <* ( {} ) *> ) = { 1 } & 1 <> n) by A45,FINSEQ_1:2,FINSEQ_1:38;
then (not n in ( dom <* ( {} ) *> )) by TARSKI:def 1;
then consider k being Nat such that A49: k in ( dom G ) and A50: n = ( ( len <* ( {} ) *> ) + k ) by A40,A46,FINSEQ_1:25;
n = ( 1 + k ) by A50,FINSEQ_1:39;
then ( F . n ) <> ( {} ) by A7,A48,A49;
then consider x1 being set such that A51: x1 in ( F . n ) by XBOOLE_0:def 1;
A52: ( F . n ) c= ( union ( rng F ) ) by A40,A46,FUNCT_1:3,ZFMISC_1:74;
then x1 in ( dom f ) by A23,A51;
then reconsider x1 as (Element of X);
A53: ( 0. ) <> ( f . x1 ) by A3,A23,A51,A52;
f is  real-valued by A1,MESFUNC2:def 4;
then A54: |. ( f . x1 ) .| < ( +infty ) by A23,A51,A52,MESFUNC2:def 1;
( a . n ) = ( f . x1 ) by A41,A40,A45,A46,A51;
hence thesis by A2,A23,A51,A52,A54,A53,EXTREAL2:10;
end;
take F;
take a;
A55: (for n9 being Nat holds (n9 in ( dom F ) implies (for x being set holds (x in ( F . n9 ) implies ( f . x ) = ( a . n9 )))))
proof
let n9 being Nat;
assume A56: n9 in ( dom F );
now
per cases ;
case A57: n9 = 1;
thus (for x being set holds (x in ( F . n9 ) implies ( f . x ) = ( a . n9 )))
proof
let x being set;
( dom <* ( {} ) *> ) = { 1 } by FINSEQ_1:2,FINSEQ_1:38;
then 1 in ( dom <* ( {} ) *> ) by TARSKI:def 1;
then A58: ( F . 1 ) = ( <* ( {} ) *> . 1 ) by FINSEQ_1:def 7
.= ( {} ) by FINSEQ_1:40;
assume x in ( F . n9 );
hence thesis by A57,A58;
end;

end;
case A59: n9 <> 1;
n9 in ( Seg ( len F ) ) by A56,FINSEQ_1:def 3;
then 1 <= n9 by FINSEQ_1:1;
then 1 < n9 by A59,XXREAL_0:1;
then A60: ( 1 + 1 ) <= n9 by NAT_1:13;
thus (for x being set holds (x in ( F . n9 ) implies ( f . x ) = ( a . n9 )))
proof
let x being set;
assume A61: x in ( F . n9 );
( F . n9 ) in ( rng F ) by A56,FUNCT_1:3;
then ( F . n9 ) in S;
then reconsider x as (Element of X) by A61;
( a . n9 ) = ( f . x ) by A41,A56,A60,A61;
hence thesis;
end;

end;
end;
hence thesis;
end;
( len F ) = ( ( len <* ( {} ) *> ) + ( len G ) ) by FINSEQ_1:22
.= ( 1 + ( len G ) ) by FINSEQ_1:39;
then 1 <= ( len F ) by NAT_1:11;
then 1 in ( Seg ( len F ) ) by FINSEQ_1:1;
hence thesis by A23,A39,A40,A55,A44,CKB12:def 1;
end;
