environ
vocabularies NUMBERS,SUBSET_1,XREAL_0,ORDINAL1,SEQ_1,PARTFUN1,RELAT_1,TARSKI,SEQ_2,ORDINAL2,FUNCT_2,FUNCT_1,XBOOLE_0,XXREAL_0,NAT_1,ARYTM_3,CARD_1,COMPLEX1,ARYTM_1,REAL_1,RCOMP_1,XXREAL_1,VALUED_1,ORDINAL4,ZFMISC_1,VALUED_0,SEQ_4,XXREAL_2,SQUARE_1,SEQM_3,FCONT_1,JGRAPH_2;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,ORDINAL1,ZFMISC_1,NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,REAL_1,NAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,VALUED_0,VALUED_1,SEQ_1,SEQ_2,SEQ_4,SQUARE_1,PARTFUN2,RFUNCT_1,RCOMP_1,RECDEF_1,RFUNCT_2,CKB1,CKB14;
definitions TARSKI,XBOOLE_0,SQUARE_1,RELAT_1,FUNCT_1,VALUED_1,CKB1,CKB14;
theorems TARSKI,ZFMISC_1,NAT_1,FUNCT_1,FUNCT_2,ABSVALUE,SEQ_1,SEQ_2,SEQM_3,SEQ_4,PARTFUN1,XREAL_0,PARTFUN2,RFUNCT_1,RFUNCT_2,RCOMP_1,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,XCMPLX_0,XCMPLX_1,XREAL_1,COMPLEX1,XXREAL_0,ORDINAL1,VALUED_1,XXREAL_1,MEMBERED,XXREAL_2,VALUED_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB20,CKB21,CKB24,CKB28,CKB29;
schemes NAT_1,RECDEF_1,FUNCT_2;
registrations XBOOLE_0,ORDINAL1,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,RCOMP_1,RFUNCT_2,VALUED_0,VALUED_1,FUNCT_2,XXREAL_2,RELAT_1,RFUNCT_1,SEQ_2,FUNCT_1,ZFMISC_1,CKB17,CKB18,CKB19,CKB22,CKB23,CKB25,CKB26,CKB27,CKB30;
constructors PARTFUN1,REAL_1,SQUARE_1,NAT_1,COMPLEX1,VALUED_1,SEQ_2,SEQM_3,SEQ_4,RCOMP_1,PARTFUN2,RFUNCT_1,RFUNCT_2,SEQ_1,RECDEF_1,RELSET_1,CKB1,CKB14;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve X for set;
reserve r for  real number;
reserve s1 for Real_Sequence;
reserve f for (PartFunc of ( REAL ),( REAL ));
theorem
Th21: (for r holds (for X holds (for f holds ((X c= ( dom f ) & ( f | X ) is  continuous) implies ( ( r (#) f ) | X ) is  continuous))))
proof
let r;
let X;
let f;
assume that
A1: X c= ( dom f );
assume A2: ( f | X ) is  continuous;
A3: X c= ( dom ( r (#) f ) ) by A1,VALUED_1:def 5;
now
let s1;
assume that
A4: ( rng s1 ) c= X
and
A5: s1 is  convergent
and
A6: ( lim s1 ) in X;
A7: ( f /* s1 ) is  convergent by A1,A2,A4,A5,A6,CKB15:1;
then A8: ( r (#) ( f /* s1 ) ) is  convergent by SEQ_2:7;
( f . ( lim s1 ) ) = ( lim ( f /* s1 ) ) by A1,A2,A4,A5,A6,CKB15:1;
then ( ( r (#) f ) . ( lim s1 ) ) = ( r * ( lim ( f /* s1 ) ) ) by A3,A6,VALUED_1:def 5
.= ( lim ( r (#) ( f /* s1 ) ) ) by A7,SEQ_2:8
.= ( lim ( ( r (#) f ) /* s1 ) ) by A1,A4,RFUNCT_2:9,XBOOLE_1:1;
hence (( ( r (#) f ) /* s1 ) is  convergent & ( ( r (#) f ) . ( lim s1 ) ) = ( lim ( ( r (#) f ) /* s1 ) )) by A1,A4,A8,RFUNCT_2:9,XBOOLE_1:1;
end;
hence thesis by A3,CKB15:1;
end;
