environ
vocabularies NUMBERS,REAL_1,SUBSET_1,SEQ_1,PARTFUN1,ARYTM_3,XXREAL_1,TARSKI,RELAT_1,ORDINAL2,FUNCT_1,FDIFF_1,CARD_1,RCOMP_1,XXREAL_2,XREAL_0,ORDINAL1,SEQ_4,XXREAL_0,XBOOLE_0,ARYTM_1,VALUED_0,SEQ_2,VALUED_1,FUNCT_2,FUNCOP_1;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,FUNCT_2,NUMBERS,XREAL_0,XXREAL_0,XXREAL_2,REAL_1,RELSET_1,VALUED_0,VALUED_1,SEQ_1,SEQ_2,SEQ_4,PARTFUN1,PARTFUN2,RCOMP_1,FCONT_1,FDIFF_1;
definitions TARSKI,RFUNCT_2,XCMPLX_0;
theorems TARSKI,NAT_1,SEQ_1,SEQ_2,SEQ_4,PARTFUN2,RFUNCT_2,RCOMP_1,FCONT_1,FDIFF_1,ZFMISC_1,FUNCT_1,XREAL_0,XBOOLE_0,XBOOLE_1,XCMPLX_1,FUNCOP_1,XREAL_1,XXREAL_0,VALUED_1,XXREAL_2,XXREAL_1,FUNCT_2,VALUED_0,CKB1,CKB2,CKB3,CKB4,CKB5;
schemes SEQ_1;
registrations XBOOLE_0,RELSET_1,NUMBERS,XXREAL_0,XREAL_0,NAT_1,MEMBERED,RCOMP_1,FDIFF_1,VALUED_0,VALUED_1,FUNCT_2,XXREAL_2,FCONT_1,ORDINAL1;
constructors PARTFUN1,REAL_1,NAT_1,SEQ_2,SEQ_4,RCOMP_1,PARTFUN2,RFUNCT_2,FCONT_1,FDIFF_1,VALUED_1,SEQ_1,XXREAL_2,COMPLEX1,RELSET_1,BINOP_2;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve g for Real;
reserve r for Real;
reserve s for Real;
reserve t for Real;
reserve x for Real;
reserve x0 for Real;
reserve x1 for Real;
reserve f1 for (PartFunc of ( REAL ),( REAL ));
reserve f2 for (PartFunc of ( REAL ),( REAL ));
theorem
(for x holds (for t holds (( 0 ) < t implies (for f1 holds (for f2 holds ((((((([. x,( x + t ) .] c= ( dom f1 ) & [. x,( x + t ) .] c= ( dom f2 )) & ( f1 | [. x,( x + t ) .] ) is  continuous) & f1 is_differentiable_on ]. x,( x + t ) .[) & ( f2 | [. x,( x + t ) .] ) is  continuous) & f2 is_differentiable_on ]. x,( x + t ) .[) & (for x1 holds (x1 in ]. x,( x + t ) .[ implies ( diff (f2,x1) ) <> ( 0 )))) implies (ex s st ((( 0 ) < s & s < 1) & ( ( ( f1 . ( x + t ) ) - ( f1 . x ) ) / ( ( f2 . ( x + t ) ) - ( f2 . x ) ) ) = ( ( diff (f1,( x + ( s * t ) )) ) / ( diff (f2,( x + ( s * t ) )) ) )))))))))
proof
let x;
let t;
assume that
A1: ( 0 ) < t;
let f1;
let f2;
assume that
A2: [. x,( x + t ) .] c= ( dom f1 )
and
A3: [. x,( x + t ) .] c= ( dom f2 )
and
A4: (( f1 | [. x,( x + t ) .] ) is  continuous & f1 is_differentiable_on ]. x,( x + t ) .[)
and
A5: (( f2 | [. x,( x + t ) .] ) is  continuous & f2 is_differentiable_on ]. x,( x + t ) .[)
and
A6: (for x1 holds (x1 in ]. x,( x + t ) .[ implies ( diff (f2,x1) ) <> ( 0 )));
consider x0 such that A7: x0 in ]. x,( x + t ) .[ and A8: ( ( ( f1 . ( x + t ) ) - ( f1 . x ) ) * ( diff (f2,x0) ) ) = ( ( ( f2 . ( x + t ) ) - ( f2 . x ) ) * ( diff (f1,x0) ) ) by A1,A2,A3,A4,A5,CKB5:1,XREAL_1:29;
( ( diff (f2,x0) ) * ( ( ( f1 . ( x + t ) ) - ( f1 . x ) ) / ( diff (f2,x0) ) ) ) = ( ( ( ( f2 . ( x + t ) ) - ( f2 . x ) ) * ( diff (f1,x0) ) ) / ( diff (f2,x0) ) ) by A8,XCMPLX_1:74;
then ( ( ( f1 . ( x + t ) ) - ( f1 . x ) ) / ( ( f2 . ( x + t ) ) - ( f2 . x ) ) ) = ( ( ( ( f2 . ( x + t ) ) - ( f2 . x ) ) * ( ( diff (f1,x0) ) / ( diff (f2,x0) ) ) ) / ( ( f2 . ( x + t ) ) - ( f2 . x ) ) ) by A6,A7,XCMPLX_1:87;
then A9: ( ( ( f1 . ( x + t ) ) - ( f1 . x ) ) / ( ( f2 . ( x + t ) ) - ( f2 . x ) ) ) = ( ( ( ( diff (f1,x0) ) / ( diff (f2,x0) ) ) / ( ( f2 . ( x + t ) ) - ( f2 . x ) ) ) * ( ( f2 . ( x + t ) ) - ( f2 . x ) ) );
take s = ( ( x0 - x ) / t );
x0 in { r: (x < r & r < ( x + t )) } by A7,RCOMP_1:def 2;
then A10: (ex g st ((g = x0 & x < g) & g < ( x + t )));
then ( 0 ) < ( x0 - x ) by XREAL_1:50;
then ( ( 0 ) / t ) < ( ( x0 - x ) / t ) by A1,XREAL_1:74;
hence ( 0 ) < s;
( x0 - x ) < t by A10,XREAL_1:19;
then ( ( x0 - x ) / t ) < ( t / t ) by A1,XREAL_1:74;
hence s < 1 by A1,XCMPLX_1:60;
A11: ( ( s * t ) + x ) = ( ( x0 - x ) + x ) by A1,XCMPLX_1:87;
( 0 ) <> ( ( f2 . ( x + t ) ) - ( f2 . x ) ) by A1,A3,A5,A6,CKB1:1,XREAL_1:29;
hence thesis by A9,A11,XCMPLX_1:87;
end;
