
(in-package :lisp)

(defclass fragment (article)
  ((source-article
    :type (or nil article)
    :initform nil
    :initarg :source-article
    :documentation "The article from which this fragment comes")
   (items
    :type list
    :initform nil
    :initarg :items
    :documentation "The list of items generated by this fragment.")))
