environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,PRE_TOPC,EUCLID,SUPINF_2,COMPLEX1,XXREAL_0,CARD_1,XBOOLE_0,FUNCT_1,TOPMETR,SUBSET_1,ORDINAL2,PARTFUN1,RCOMP_1,REAL_1,TARSKI,STRUCT_0,RELAT_1,ARYTM_3,TOPS_2,ARYTM_1,SQUARE_1,NAT_1,METRIC_1,JORDAN2C,XXREAL_2,PCOMPS_1,MCART_1,FUNCT_4,JGRAPH_4,FUNCT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,NAT_1,REAL_1,COMPLEX1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,DOMAIN_1,STRUCT_0,PARTFUN1,TOPMETR,RLVECT_1,EUCLID,COMPTS_1,TOPS_2,METRIC_1,PCOMPS_1,SQUARE_1,TBSP_1,RCOMP_1,PSCOMP_1,PRE_TOPC,JORDAN2C,FUNCT_4,XXREAL_0;
definitions TARSKI,SQUARE_1,EUCLID,STRUCT_0,PCOMPS_1,ALGSTR_0;
theorems TARSKI,RELAT_1,SUBSET_1,FUNCT_1,FUNCT_2,FUNCT_4,TOPS_1,TOPS_2,PARTFUN1,PRE_TOPC,TOPMETR,JORDAN6,EUCLID,JGRAPH_1,SQUARE_1,PSCOMP_1,METRIC_1,JGRAPH_2,GOBOARD6,GOBOARD9,TBSP_1,TOPREAL6,JGRAPH_3,ABSVALUE,JORDAN2C,TSEP_1,XREAL_0,XBOOLE_0,XBOOLE_1,TOPRNS_1,XCMPLX_0,XCMPLX_1,COMPLEX1,XREAL_1,JORDAN2B,XXREAL_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
schemes FUNCT_2,DOMAIN_1,JGRAPH_2,BINOP_2,JGRAPH_3;
registrations XBOOLE_0,RELAT_1,NUMBERS,XXREAL_0,XREAL_0,SQUARE_1,MEMBERED,STRUCT_0,PRE_TOPC,METRIC_1,EUCLID,TOPMETR,TOPREAL1,PSCOMP_1,FUNCT_2,COMPTS_1,TBSP_1,RELSET_1,FUNCT_1;
constructors FUNCT_4,REAL_1,SQUARE_1,BINOP_2,COMPLEX1,RCOMP_1,TOPS_2,COMPTS_1,TBSP_1,MONOID_0,TOPMETR,PSCOMP_1,JORDAN2C,SEQ_1,FUNCSDOM,PCOMPS_1,RELSET_1;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
reserve p for (Point of ( TOP-REAL 2 ));
reserve q for (Point of ( TOP-REAL 2 ));
theorem
Th12: (for X being non  empty TopSpace holds (for f1 being (Function of X,( R^1 )) holds (f1 is  continuous implies (ex g being (Function of X,( R^1 )) st ((for p being (Point of X) holds (for r1 being  real number holds (( f1 . p ) = r1 implies ( g . p ) = ( abs r1 )))) & g is  continuous)))))
proof
let X being non  empty TopSpace;
let f1 being (Function of X,( R^1 ));
assume f1 is  continuous;
then consider g1 being (Function of X,( R^1 )) such that A1: (for p being (Point of X) holds (for r1 being  real number holds (( f1 . p ) = r1 implies ( g1 . p ) = ( r1 ^2 )))) and A2: g1 is  continuous by CKB7:1;
(for q being (Point of X) holds (ex r being  real number st (( g1 . q ) = r & r >= ( 0 ))))
proof
let q being (Point of X);
reconsider r11 = ( f1 . q ) as Real by TOPMETR:17;
( g1 . q ) = ( r11 ^2 ) by A1;
hence thesis by XREAL_1:63;
end;
then consider g2 being (Function of X,( R^1 )) such that A3: (for p being (Point of X) holds (for r1 being  real number holds (( g1 . p ) = r1 implies ( g2 . p ) = ( sqrt r1 )))) and A4: g2 is  continuous by A2,JGRAPH_3:5;
(for p being (Point of X) holds (for r1 being  real number holds (( f1 . p ) = r1 implies ( g2 . p ) = ( abs r1 ))))
proof
let p being (Point of X);
let r1 being  real number;
assume ( f1 . p ) = r1;
then ( g1 . p ) = ( r1 ^2 ) by A1;
then ( g2 . p ) = ( sqrt ( r1 ^2 ) ) by A3
.= ( abs r1 ) by COMPLEX1:72;
hence thesis;
end;
hence thesis by A4;
end;
