environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,PRE_TOPC,EUCLID,SUPINF_2,COMPLEX1,XXREAL_0,CARD_1,XBOOLE_0,FUNCT_1,TOPMETR,SUBSET_1,ORDINAL2,PARTFUN1,RCOMP_1,REAL_1,TARSKI,STRUCT_0,RELAT_1,ARYTM_3,TOPS_2,ARYTM_1,SQUARE_1,NAT_1,METRIC_1,JORDAN2C,XXREAL_2,PCOMPS_1,MCART_1,FUNCT_4,JGRAPH_4,FUNCT_2;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,NAT_1,REAL_1,COMPLEX1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,DOMAIN_1,STRUCT_0,PARTFUN1,TOPMETR,RLVECT_1,EUCLID,COMPTS_1,TOPS_2,METRIC_1,PCOMPS_1,SQUARE_1,TBSP_1,RCOMP_1,PSCOMP_1,PRE_TOPC,JORDAN2C,FUNCT_4,XXREAL_0,CKB12,CKB19,CKB20,CKB66,CKB67;
definitions TARSKI,SQUARE_1,EUCLID,STRUCT_0,PCOMPS_1,ALGSTR_0,CKB12,CKB19,CKB20,CKB66,CKB67;
theorems TARSKI,RELAT_1,SUBSET_1,FUNCT_1,FUNCT_2,FUNCT_4,TOPS_1,TOPS_2,PARTFUN1,PRE_TOPC,TOPMETR,JORDAN6,EUCLID,JGRAPH_1,SQUARE_1,PSCOMP_1,METRIC_1,JGRAPH_2,GOBOARD6,GOBOARD9,TBSP_1,TOPREAL6,JGRAPH_3,ABSVALUE,JORDAN2C,TSEP_1,XREAL_0,XBOOLE_0,XBOOLE_1,TOPRNS_1,XCMPLX_0,XCMPLX_1,COMPLEX1,XREAL_1,JORDAN2B,XXREAL_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70,CKB71,CKB72,CKB73,CKB74,CKB75,CKB76,CKB77,CKB78,CKB79,CKB80,CKB81,CKB82,CKB83,CKB84,CKB85,CKB86,CKB87,CKB88,CKB89,CKB90,CKB91;
schemes FUNCT_2,DOMAIN_1,JGRAPH_2,BINOP_2,JGRAPH_3,CKB50;
registrations XBOOLE_0,RELAT_1,NUMBERS,XXREAL_0,XREAL_0,SQUARE_1,MEMBERED,STRUCT_0,PRE_TOPC,METRIC_1,EUCLID,TOPMETR,TOPREAL1,PSCOMP_1,FUNCT_2,COMPTS_1,TBSP_1,RELSET_1,FUNCT_1,CKB15;
constructors FUNCT_4,REAL_1,SQUARE_1,BINOP_2,COMPLEX1,RCOMP_1,TOPS_2,COMPTS_1,TBSP_1,MONOID_0,TOPMETR,PSCOMP_1,JORDAN2C,SEQ_1,FUNCSDOM,PCOMPS_1,RELSET_1,CKB12,CKB19,CKB20,CKB66,CKB67;
requirements REAL,NUMERALS,BOOLE,SUBSET,ARITHM;
begin
theorem
Th80: (for cn being Real holds (for p2 being (Point of ( TOP-REAL 2 )) holds ((( - 1 ) < cn & cn < 1) implies (ex K being non  empty  compact (Subset of ( TOP-REAL 2 )) st (K = ( ( cn -FanMorphN ) .: K ) & (ex V2 being (Subset of ( TOP-REAL 2 )) st (((p2 in V2 & V2 is  open) & V2 c= K) & ( ( cn -FanMorphN ) . p2 ) in V2)))))))
proof
reconsider O = ( 0. ( TOP-REAL 2 ) ) as (Point of ( Euclid 2 )) by EUCLID:67;
let cn being Real;
let p2 being (Point of ( TOP-REAL 2 ));
A1: ( the TopStruct of ( TOP-REAL 2 ) ) = ( TopSpaceMetr ( Euclid 2 ) ) by EUCLID:def 8;
( the TopStruct of ( TOP-REAL 2 ) ) = ( TopSpaceMetr ( Euclid 2 ) ) by EUCLID:def 8;
then reconsider V0 = ( Ball (O,( |. p2 .| + 1 )) ) as (Subset of ( TOP-REAL 2 ));
(O in V0 & V0 c= ( cl_Ball (O,( |. p2 .| + 1 )) )) by GOBOARD6:1,METRIC_1:14;
then reconsider K0 = ( cl_Ball (O,( |. p2 .| + 1 )) ) as non  empty  compact (Subset of ( TOP-REAL 2 )) by A1,CKB18:1;
set q3 = ( ( cn -FanMorphN ) . p2 );
reconsider VV0 = V0 as (Subset of ( TopSpaceMetr ( Euclid 2 ) ));
reconsider u2 = p2 as (Point of ( Euclid 2 )) by EUCLID:67;
reconsider u3 = q3 as (Point of ( Euclid 2 )) by EUCLID:67;
A2: ( ( cn -FanMorphN ) .: K0 ) c= K0
proof
let y being set;
assume y in ( ( cn -FanMorphN ) .: K0 );
then consider x being set such that A3: x in ( dom ( cn -FanMorphN ) ) and A4: x in K0 and A5: y = ( ( cn -FanMorphN ) . x ) by FUNCT_1:def 6;
reconsider q = x as (Point of ( TOP-REAL 2 )) by A3;
reconsider uq = q as (Point of ( Euclid 2 )) by EUCLID:67;
( dist (O,uq) ) <= ( |. p2 .| + 1 ) by A4,METRIC_1:12;
then |. ( ( 0. ( TOP-REAL 2 ) ) - q ) .| <= ( |. p2 .| + 1 ) by JGRAPH_1:28;
then |. ( - q ) .| <= ( |. p2 .| + 1 ) by EUCLID:27;
then A6: |. q .| <= ( |. p2 .| + 1 ) by TOPRNS_1:26;
A7: y in ( rng ( cn -FanMorphN ) ) by A3,A5,FUNCT_1:def 3;
then reconsider u = y as (Point of ( Euclid 2 )) by EUCLID:67;
reconsider q4 = y as (Point of ( TOP-REAL 2 )) by A7;
|. q4 .| = |. q .| by A5,CKB85:1;
then |. ( - q4 ) .| <= ( |. p2 .| + 1 ) by A6,TOPRNS_1:26;
then |. ( ( 0. ( TOP-REAL 2 ) ) - q4 ) .| <= ( |. p2 .| + 1 ) by EUCLID:27;
then ( dist (O,u) ) <= ( |. p2 .| + 1 ) by JGRAPH_1:28;
hence thesis by METRIC_1:12;
end;
VV0 is  open by TOPMETR:14;
then A8: V0 is  open by CKB52:1,PRE_TOPC:30;
A9: |. p2 .| < ( |. p2 .| + 1 ) by XREAL_1:29;
then |. ( - p2 ) .| < ( |. p2 .| + 1 ) by TOPRNS_1:26;
then |. ( ( 0. ( TOP-REAL 2 ) ) - p2 ) .| < ( |. p2 .| + 1 ) by EUCLID:27;
then ( dist (O,u2) ) < ( |. p2 .| + 1 ) by JGRAPH_1:28;
then A10: p2 in V0 by METRIC_1:11;
|. q3 .| = |. p2 .| by CKB85:1;
then |. ( - q3 ) .| < ( |. p2 .| + 1 ) by A9,TOPRNS_1:26;
then |. ( ( 0. ( TOP-REAL 2 ) ) - q3 ) .| < ( |. p2 .| + 1 ) by EUCLID:27;
then ( dist (O,u3) ) < ( |. p2 .| + 1 ) by JGRAPH_1:28;
then A11: ( ( cn -FanMorphN ) . p2 ) in V0 by METRIC_1:11;
assume A12: (( - 1 ) < cn & cn < 1);
K0 c= ( ( cn -FanMorphN ) .: K0 )
proof
let y being set;
assume A13: y in K0;
then reconsider q4 = y as (Point of ( TOP-REAL 2 ));
reconsider y as (Point of ( Euclid 2 )) by A13;
(the carrier of ( TOP-REAL 2 )) c= ( rng ( cn -FanMorphN ) ) by A12,CKB91:1;
then q4 in ( rng ( cn -FanMorphN ) ) by TARSKI:def 3;
then consider x being set such that A14: x in ( dom ( cn -FanMorphN ) ) and A15: y = ( ( cn -FanMorphN ) . x ) by FUNCT_1:def 3;
reconsider x as (Point of ( Euclid 2 )) by A14,CKB52:1;
reconsider q = x as (Point of ( TOP-REAL 2 )) by A14;
|. q4 .| = |. q .| by A15,CKB85:1;
then q in K0 by A13,CKB56:1;
hence thesis by A14,A15,FUNCT_1:def 6;
end;
then K0 = ( ( cn -FanMorphN ) .: K0 ) by A2,XBOOLE_0:def 10;
hence thesis by A10,A8,A11,METRIC_1:14;
end;
