environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,XXREAL_0,SUBSET_1,TARSKI,ARYTM_3,XCMPLX_0,RELAT_1,ARYTM_1,CARD_1,SQUARE_1;
notations TARSKI,SUBSET_1,ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,XXREAL_0,CKB2,CKB3,CKB6,CKB9,CKB10,CKB27,CKB28;
definitions TARSKI,XCMPLX_0,CKB6,CKB27;
theorems AXIOMS,XREAL_0,XCMPLX_0,XCMPLX_1,XREAL_1,XXREAL_0,CKB4,CKB5,CKB6,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50;
schemes CKB1;
registrations NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,REAL_1,ORDINAL1,XBOOLE_0,CKB7,CKB8;
constructors NUMBERS,XCMPLX_0,XXREAL_0,XREAL_0,CKB2,CKB3,CKB6,CKB9,CKB10,CKB27,CKB28;
requirements REAL,NUMERALS,SUBSET,BOOLE,ARITHM;
begin
reserve a for  real number;
reserve b for  real number;
theorem
(((( 0 ) <= a & ( 0 ) <= b) & a <> b) implies ( 1 / ( ( sqrt a ) + ( sqrt b ) ) ) = ( ( ( sqrt a ) - ( sqrt b ) ) / ( a - b ) ))
proof
assume that
A1: ( 0 ) <= a
and
A2: ( 0 ) <= b
and
A3: a <> b;
thus ( 1 / ( ( sqrt a ) + ( sqrt b ) ) ) = ( ( ( sqrt a ) - ( sqrt b ) ) / ( ( ( sqrt a ) ^2 ) - ( ( sqrt b ) ^2 ) ) ) by A1,A2,A3,CKB50:1,CKB18:1
.= ( ( ( sqrt a ) - ( sqrt b ) ) / ( a - ( ( sqrt b ) ^2 ) ) ) by A1,CKB27:def 1
.= ( ( ( sqrt a ) - ( sqrt b ) ) / ( a - b ) ) by A2,CKB27:def 1;
end;
