environ
vocabularies NUMBERS,XBOOLE_0,STRUCT_0,SUBSET_1,FINSET_1,NAT_1,GROUP_1,RELAT_1,TARSKI,ALGSTR_0,BINOP_1,REALSET1,ZFMISC_1,FUNCT_1,RLSUB_1,CARD_1,XXREAL_0,NEWTON,SETFAM_1,CQC_SIM1,FINSUB_1,SETWISEO,ARYTM_3,GROUP_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,SETFAM_1,FINSUB_1,FINSET_1,REALSET1,XXREAL_0,CARD_1,NUMBERS,STRUCT_0,ALGSTR_0,GROUP_1,WELLORD2,BINOP_1,SETWISEO,DOMAIN_1,RELAT_1,FUNCT_1,RELSET_1,NAT_1,NAT_D,MCART_1,CKB3,CKB12,CKB13;
definitions FUNCT_1,GROUP_1,STRUCT_0,TARSKI,XBOOLE_0,BINOP_1,REALSET1,SUBSET_1,ALGSTR_0,CKB3,CKB12;
theorems CARD_1,CARD_2,ENUMSET1,FINSET_1,FINSUB_1,FUNCT_1,FUNCT_2,GROUP_1,TARSKI,WELLORD2,ZFMISC_1,RELAT_1,RELSET_1,XBOOLE_0,XBOOLE_1,XCMPLX_1,NAT_D,STRUCT_0,NAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB12,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
schemes FUNCT_1,SUBSET_1,SETWISEO,CLASSES1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FINSET_1,FINSUB_1,MEMBERED,REALSET1,STRUCT_0,GROUP_1,ALGSTR_0,CARD_1,CKB10,CKB11;
constructors SETFAM_1,PARTFUN1,WELLORD2,BINOP_1,SETWISEO,XXREAL_0,NAT_1,NAT_D,MEMBERED,REALSET1,GROUP_1,RELSET_1,CKB3,CKB12,CKB13;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve x for set;
reserve G for non  empty 1-sorted;
reserve G for non  empty multMagma;
reserve g for (Element of G);
reserve g1 for (Element of G);
reserve g2 for (Element of G);
reserve h1 for (Element of G);
reserve h2 for (Element of G);
theorem
( { g1,g2 } * { g } ) = { ( g1 * g ),( g2 * g ) }
proof
thus ( { g1,g2 } * { g } ) c= { ( g1 * g ),( g2 * g ) }
proof
let x;
assume x in ( { g1,g2 } * { g } );
then consider h1,h2 such that A1: x = ( h1 * h2 ) and A2: h1 in { g1,g2 } and A3: h2 in { g };
A4: (h1 = g1 or h1 = g2) by A2,TARSKI:def 2;
h2 = g by A3,TARSKI:def 1;
hence thesis by A1,A4,TARSKI:def 2;
end;

let x;
A5: g2 in { g1,g2 } by TARSKI:def 2;
assume x in { ( g1 * g ),( g2 * g ) };
then A6: (x = ( g1 * g ) or x = ( g2 * g )) by TARSKI:def 2;
(g in { g } & g1 in { g1,g2 }) by TARSKI:def 1,TARSKI:def 2;
hence thesis by A6,A5;
end;
