environ
vocabularies NUMBERS,SUBSET_1,STRUCT_0,FUNCT_1,GLIB_000,XBOOLE_0,FUNCT_5,RELAT_1,PARTFUN1,RELAT_2,FINSET_1,TREES_2,FINSEQ_1,XXREAL_0,ARYTM_3,TARSKI,CARD_1,FUNCT_2,ZFMISC_1,MCART_1,GRAPH_1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,FUNCT_2,FUNCT_5,FINSEQ_1,FINSET_1,PARTFUN1,CARD_1,NUMBERS,NAT_1,MCART_1,XXREAL_0,STRUCT_0,CKB1,CKB2,CKB3,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB23,CKB24,CKB27,CKB28,CKB29,CKB30,CKB32,CKB33,CKB34,CKB36,CKB37,CKB38,CKB39,CKB40,CKB43,CKB45;
definitions FUNCT_1,TARSKI,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB24,CKB27,CKB30,CKB34,CKB36,CKB37,CKB38,CKB39,CKB40,CKB43,CKB45;
theorems FUNCT_2,FUNCT_1,PARTFUN1,FINSEQ_1,NAT_1,ZFMISC_1,MCART_1,TARSKI,RELAT_1,FINSEQ_3,RELSET_1,XBOOLE_0,XBOOLE_1,XREAL_1,XXREAL_0,CARD_1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB22,CKB24,CKB27,CKB30,CKB34,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54;
schemes FUNCT_2,TARSKI,XBOOLE_0,CKB46;
registrations XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,PARTFUN1,FINSET_1,XREAL_0,FINSEQ_1,ORDINAL1,STRUCT_0,CARD_1,FUNCT_2,RELSET_1,CKB1,CKB4,CKB15,CKB16,CKB17,CKB18,CKB25,CKB26,CKB31,CKB35;
constructors PARTFUN1,FUNCT_2,XXREAL_0,XREAL_0,NAT_1,FINSEQ_1,STRUCT_0,FUNCT_5,RELSET_1,CKB1,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB19,CKB20,CKB21,CKB23,CKB24,CKB27,CKB30,CKB34,CKB36,CKB37,CKB38,CKB39,CKB40,CKB43,CKB45;
requirements NUMERALS,REAL,SUBSET,BOOLE,ARITHM;
begin
reserve v for set;
reserve G1 for Graph;
reserve G2 for Graph;
reserve G3 for Graph;
theorem
Th9: (((((((the Source of G1) tolerates (the Source of G2) & (the Target of G1) tolerates (the Target of G2)) & (the Source of G1) tolerates (the Source of G3)) & (the Target of G1) tolerates (the Target of G3)) & (the Source of G2) tolerates (the Source of G3)) & (the Target of G2) tolerates (the Target of G3)) implies ( ( G1 \/ G2 ) \/ G3 ) = ( G1 \/ ( G2 \/ G3 ) ))
proof
assume that
A1: (the Source of G1) tolerates (the Source of G2)
and
A2: (the Target of G1) tolerates (the Target of G2)
and
A3: (the Source of G1) tolerates (the Source of G3)
and
A4: (the Target of G1) tolerates (the Target of G3)
and
A5: (the Source of G2) tolerates (the Source of G3)
and
A6: (the Target of G2) tolerates (the Target of G3);
A7: (for v holds (v in ( ( dom (the Source of ( G1 \/ G2 )) ) /\ ( dom (the Source of G3) ) ) implies ( (the Source of ( G1 \/ G2 )) . v ) = ( (the Source of G3) . v )))
proof
let v;
assume A8: v in ( ( dom (the Source of ( G1 \/ G2 )) ) /\ ( dom (the Source of G3) ) );
then A9: v in ( dom (the Source of G3) ) by XBOOLE_0:def 4;
v in ( dom (the Source of ( G1 \/ G2 )) ) by A8,XBOOLE_0:def 4;
then v in (the carrier' of ( G1 \/ G2 ));
then A10: v in ( (the carrier' of G1) \/ (the carrier' of G2) ) by A1,A2,CKB8:def 1;
A11:now
assume A12: v in (the carrier' of G1);
then v in ( dom (the Source of G1) ) by FUNCT_2:def 1;
then A13: v in ( ( dom (the Source of G1) ) /\ ( dom (the Source of G3) ) ) by A9,XBOOLE_0:def 4;
thus ( (the Source of ( G1 \/ G2 )) . v ) = ( (the Source of G1) . v ) by A1,A2,A12,CKB8:def 1
.= ( (the Source of G3) . v ) by A3,A13,PARTFUN1:def 4;
end;
now
assume A14: v in (the carrier' of G2);
then v in ( dom (the Source of G2) ) by FUNCT_2:def 1;
then A15: v in ( ( dom (the Source of G2) ) /\ ( dom (the Source of G3) ) ) by A9,XBOOLE_0:def 4;
thus ( (the Source of ( G1 \/ G2 )) . v ) = ( (the Source of G2) . v ) by A1,A2,A14,CKB8:def 1
.= ( (the Source of G3) . v ) by A5,A15,PARTFUN1:def 4;
end;
hence thesis by A10,A11,XBOOLE_0:def 3;
end;
A16: (for v holds (v in ( ( dom (the Target of ( G1 \/ G2 )) ) /\ ( dom (the Target of G3) ) ) implies ( (the Target of ( G1 \/ G2 )) . v ) = ( (the Target of G3) . v )))
proof
let v;
assume A17: v in ( ( dom (the Target of ( G1 \/ G2 )) ) /\ ( dom (the Target of G3) ) );
then A18: v in ( dom (the Target of G3) ) by XBOOLE_0:def 4;
v in ( dom (the Target of ( G1 \/ G2 )) ) by A17,XBOOLE_0:def 4;
then v in (the carrier' of ( G1 \/ G2 ));
then A19: v in ( (the carrier' of G1) \/ (the carrier' of G2) ) by A1,A2,CKB8:def 1;
A20:now
assume A21: v in (the carrier' of G1);
then v in ( dom (the Target of G1) ) by FUNCT_2:def 1;
then A22: v in ( ( dom (the Target of G1) ) /\ ( dom (the Target of G3) ) ) by A18,XBOOLE_0:def 4;
thus ( (the Target of ( G1 \/ G2 )) . v ) = ( (the Target of G1) . v ) by A1,A2,A21,CKB8:def 1
.= ( (the Target of G3) . v ) by A4,A22,PARTFUN1:def 4;
end;
now
assume A23: v in (the carrier' of G2);
then v in ( dom (the Target of G2) ) by FUNCT_2:def 1;
then A24: v in ( ( dom (the Target of G2) ) /\ ( dom (the Target of G3) ) ) by A18,XBOOLE_0:def 4;
thus ( (the Target of ( G1 \/ G2 )) . v ) = ( (the Target of G2) . v ) by A1,A2,A23,CKB8:def 1
.= ( (the Target of G3) . v ) by A6,A24,PARTFUN1:def 4;
end;
hence thesis by A19,A20,XBOOLE_0:def 3;
end;
A25: (the Source of ( G1 \/ G2 )) tolerates (the Source of G3) by A7,PARTFUN1:def 4;
A26: (the Target of ( G1 \/ G2 )) tolerates (the Target of G3) by A16,PARTFUN1:def 4;
A27: (for v holds (v in ( ( dom (the Source of G1) ) /\ ( dom (the Source of ( G2 \/ G3 )) ) ) implies ( (the Source of G1) . v ) = ( (the Source of ( G2 \/ G3 )) . v )))
proof
let v;
assume A28: v in ( ( dom (the Source of G1) ) /\ ( dom (the Source of ( G2 \/ G3 )) ) );
then A29: v in ( dom (the Source of G1) ) by XBOOLE_0:def 4;
v in (the carrier' of ( G2 \/ G3 )) by A28;
then v in ( (the carrier' of G2) \/ (the carrier' of G3) ) by A5,A6,CKB8:def 1;
then v in ( (the carrier' of G2) \/ ( dom (the Source of G3) ) ) by FUNCT_2:def 1;
then A30: v in ( ( dom (the Source of G2) ) \/ ( dom (the Source of G3) ) ) by FUNCT_2:def 1;
A31:now
assume A32: v in ( dom (the Source of G2) );
then A33: v in ( ( dom (the Source of G1) ) /\ ( dom (the Source of G2) ) ) by A29,XBOOLE_0:def 4;
thus ( (the Source of ( G2 \/ G3 )) . v ) = ( (the Source of G2) . v ) by A5,A6,A32,CKB8:def 1
.= ( (the Source of G1) . v ) by A1,A33,PARTFUN1:def 4;
end;
now
assume A34: v in ( dom (the Source of G3) );
then A35: v in ( ( dom (the Source of G1) ) /\ ( dom (the Source of G3) ) ) by A29,XBOOLE_0:def 4;
thus ( (the Source of ( G2 \/ G3 )) . v ) = ( (the Source of G3) . v ) by A5,A6,A34,CKB8:def 1
.= ( (the Source of G1) . v ) by A3,A35,PARTFUN1:def 4;
end;
hence thesis by A30,A31,XBOOLE_0:def 3;
end;
A36: (for v holds (v in ( ( dom (the Target of G1) ) /\ ( dom (the Target of ( G2 \/ G3 )) ) ) implies ( (the Target of G1) . v ) = ( (the Target of ( G2 \/ G3 )) . v )))
proof
let v;
assume A37: v in ( ( dom (the Target of G1) ) /\ ( dom (the Target of ( G2 \/ G3 )) ) );
then A38: v in ( dom (the Target of G1) ) by XBOOLE_0:def 4;
v in (the carrier' of ( G2 \/ G3 )) by A37;
then v in ( (the carrier' of G2) \/ (the carrier' of G3) ) by A5,A6,CKB8:def 1;
then v in ( (the carrier' of G2) \/ ( dom (the Target of G3) ) ) by FUNCT_2:def 1;
then A39: v in ( ( dom (the Target of G2) ) \/ ( dom (the Target of G3) ) ) by FUNCT_2:def 1;
A40:now
assume A41: v in ( dom (the Target of G2) );
then A42: v in ( ( dom (the Target of G1) ) /\ ( dom (the Target of G2) ) ) by A38,XBOOLE_0:def 4;
thus ( (the Target of ( G2 \/ G3 )) . v ) = ( (the Target of G2) . v ) by A5,A6,A41,CKB8:def 1
.= ( (the Target of G1) . v ) by A2,A42,PARTFUN1:def 4;
end;
now
assume A43: v in ( dom (the Target of G3) );
then A44: v in ( ( dom (the Target of G1) ) /\ ( dom (the Target of G3) ) ) by A38,XBOOLE_0:def 4;
thus ( (the Target of ( G2 \/ G3 )) . v ) = ( (the Target of G3) . v ) by A5,A6,A43,CKB8:def 1
.= ( (the Target of G1) . v ) by A4,A44,PARTFUN1:def 4;
end;
hence thesis by A39,A40,XBOOLE_0:def 3;
end;
A45: (the Source of G1) tolerates (the Source of ( G2 \/ G3 )) by A27,PARTFUN1:def 4;
A46: (the Target of G1) tolerates (the Target of ( G2 \/ G3 )) by A36,PARTFUN1:def 4;
A47: (the carrier' of ( ( G1 \/ G2 ) \/ G3 )) = ( (the carrier' of ( G1 \/ G2 )) \/ (the carrier' of G3) ) by A25,A26,CKB8:def 1
.= ( ( (the carrier' of G1) \/ (the carrier' of G2) ) \/ (the carrier' of G3) ) by A1,A2,CKB8:def 1
.= ( (the carrier' of G1) \/ ( (the carrier' of G2) \/ (the carrier' of G3) ) ) by XBOOLE_1:4
.= ( (the carrier' of G1) \/ (the carrier' of ( G2 \/ G3 )) ) by A5,A6,CKB8:def 1
.= (the carrier' of ( G1 \/ ( G2 \/ G3 ) )) by A45,A46,CKB8:def 1;
A48: (the carrier of ( ( G1 \/ G2 ) \/ G3 )) = ( (the carrier of ( G1 \/ G2 )) \/ (the carrier of G3) ) by A25,A26,CKB8:def 1
.= ( ( (the carrier of G1) \/ (the carrier of G2) ) \/ (the carrier of G3) ) by A1,A2,CKB8:def 1
.= ( (the carrier of G1) \/ ( (the carrier of G2) \/ (the carrier of G3) ) ) by XBOOLE_1:4
.= ( (the carrier of G1) \/ (the carrier of ( G2 \/ G3 )) ) by A5,A6,CKB8:def 1
.= (the carrier of ( G1 \/ ( G2 \/ G3 ) )) by A45,A46,CKB8:def 1;
A49: ( dom (the Source of ( ( G1 \/ G2 ) \/ G3 )) ) = (the carrier' of ( G1 \/ ( G2 \/ G3 ) )) by A47,FUNCT_2:def 1
.= ( dom (the Source of ( G1 \/ ( G2 \/ G3 ) )) ) by FUNCT_2:def 1;
(for v holds (v in ( dom (the Source of ( ( G1 \/ G2 ) \/ G3 )) ) implies ( (the Source of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Source of ( G1 \/ ( G2 \/ G3 ) )) . v )))
proof
let v;
assume that
A50: v in ( dom (the Source of ( ( G1 \/ G2 ) \/ G3 )) );
( dom (the Source of ( ( G1 \/ G2 ) \/ G3 )) ) = (the carrier' of ( ( G1 \/ G2 ) \/ G3 )) by FUNCT_2:def 1
.= ( (the carrier' of ( G1 \/ G2 )) \/ (the carrier' of G3) ) by A25,A26,CKB8:def 1
.= ( ( (the carrier' of G1) \/ (the carrier' of G2) ) \/ (the carrier' of G3) ) by A1,A2,CKB8:def 1;
then A51: (v in ( (the carrier' of G1) \/ (the carrier' of G2) ) or v in (the carrier' of G3)) by A50,XBOOLE_0:def 3;
A52:now
assume A53: v in (the carrier' of G1);
(the carrier' of G1) c= ( (the carrier' of G1) \/ (the carrier' of G2) ) by XBOOLE_1:7;
then (the carrier' of G1) c= (the carrier' of ( G1 \/ G2 )) by A1,A2,CKB8:def 1;
hence ( (the Source of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Source of ( G1 \/ G2 )) . v ) by A25,A26,A53,CKB8:def 1
.= ( (the Source of G1) . v ) by A1,A2,A53,CKB8:def 1
.= ( (the Source of ( G1 \/ ( G2 \/ G3 ) )) . v ) by A45,A46,A53,CKB8:def 1;
end;
A54:now
assume A55: v in (the carrier' of G2);
(the carrier' of G2) c= ( (the carrier' of G1) \/ (the carrier' of G2) ) by XBOOLE_1:7;
then A56: (the carrier' of G2) c= (the carrier' of ( G1 \/ G2 )) by A1,A2,CKB8:def 1;
(the carrier' of G2) c= ( (the carrier' of G2) \/ (the carrier' of G3) ) by XBOOLE_1:7;
then A57: (the carrier' of G2) c= (the carrier' of ( G2 \/ G3 )) by A5,A6,CKB8:def 1;
thus ( (the Source of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Source of ( G1 \/ G2 )) . v ) by A25,A26,A55,A56,CKB8:def 1
.= ( (the Source of G2) . v ) by A1,A2,A55,CKB8:def 1
.= ( (the Source of ( G2 \/ G3 )) . v ) by A5,A6,A55,CKB8:def 1
.= ( (the Source of ( G1 \/ ( G2 \/ G3 ) )) . v ) by A45,A46,A55,A57,CKB8:def 1;
end;
now
assume A58: v in (the carrier' of G3);
(the carrier' of G3) c= ( (the carrier' of G2) \/ (the carrier' of G3) ) by XBOOLE_1:7;
then A59: (the carrier' of G3) c= (the carrier' of ( G2 \/ G3 )) by A5,A6,CKB8:def 1;
thus ( (the Source of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Source of G3) . v ) by A25,A26,A58,CKB8:def 1
.= ( (the Source of ( G2 \/ G3 )) . v ) by A5,A6,A58,CKB8:def 1
.= ( (the Source of ( G1 \/ ( G2 \/ G3 ) )) . v ) by A45,A46,A58,A59,CKB8:def 1;
end;
hence thesis by A51,A52,A54,XBOOLE_0:def 3;
end;
then A60: (the Source of ( ( G1 \/ G2 ) \/ G3 )) = (the Source of ( G1 \/ ( G2 \/ G3 ) )) by A49,FUNCT_1:2;
A61: ( dom (the Target of ( ( G1 \/ G2 ) \/ G3 )) ) = (the carrier' of ( G1 \/ ( G2 \/ G3 ) )) by A47,FUNCT_2:def 1
.= ( dom (the Target of ( G1 \/ ( G2 \/ G3 ) )) ) by FUNCT_2:def 1;
(for v holds (v in ( dom (the Target of ( ( G1 \/ G2 ) \/ G3 )) ) implies ( (the Target of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Target of ( G1 \/ ( G2 \/ G3 ) )) . v )))
proof
let v;
assume that
A62: v in ( dom (the Target of ( ( G1 \/ G2 ) \/ G3 )) );
( dom (the Target of ( ( G1 \/ G2 ) \/ G3 )) ) = (the carrier' of ( ( G1 \/ G2 ) \/ G3 )) by FUNCT_2:def 1
.= ( (the carrier' of ( G1 \/ G2 )) \/ (the carrier' of G3) ) by A25,A26,CKB8:def 1
.= ( ( (the carrier' of G1) \/ (the carrier' of G2) ) \/ (the carrier' of G3) ) by A1,A2,CKB8:def 1;
then A63: (v in ( (the carrier' of G1) \/ (the carrier' of G2) ) or v in (the carrier' of G3)) by A62,XBOOLE_0:def 3;
A64:now
assume A65: v in (the carrier' of G1);
(the carrier' of G1) c= ( (the carrier' of G1) \/ (the carrier' of G2) ) by XBOOLE_1:7;
then (the carrier' of G1) c= (the carrier' of ( G1 \/ G2 )) by A1,A2,CKB8:def 1;
hence ( (the Target of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Target of ( G1 \/ G2 )) . v ) by A25,A26,A65,CKB8:def 1
.= ( (the Target of G1) . v ) by A1,A2,A65,CKB8:def 1
.= ( (the Target of ( G1 \/ ( G2 \/ G3 ) )) . v ) by A45,A46,A65,CKB8:def 1;
end;
A66:now
assume A67: v in (the carrier' of G2);
(the carrier' of G2) c= ( (the carrier' of G1) \/ (the carrier' of G2) ) by XBOOLE_1:7;
then A68: (the carrier' of G2) c= (the carrier' of ( G1 \/ G2 )) by A1,A2,CKB8:def 1;
(the carrier' of G2) c= ( (the carrier' of G2) \/ (the carrier' of G3) ) by XBOOLE_1:7;
then A69: (the carrier' of G2) c= (the carrier' of ( G2 \/ G3 )) by A5,A6,CKB8:def 1;
thus ( (the Target of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Target of ( G1 \/ G2 )) . v ) by A25,A26,A67,A68,CKB8:def 1
.= ( (the Target of G2) . v ) by A1,A2,A67,CKB8:def 1
.= ( (the Target of ( G2 \/ G3 )) . v ) by A5,A6,A67,CKB8:def 1
.= ( (the Target of ( G1 \/ ( G2 \/ G3 ) )) . v ) by A45,A46,A67,A69,CKB8:def 1;
end;
now
assume A70: v in (the carrier' of G3);
(the carrier' of G3) c= ( (the carrier' of G2) \/ (the carrier' of G3) ) by XBOOLE_1:7;
then A71: (the carrier' of G3) c= (the carrier' of ( G2 \/ G3 )) by A5,A6,CKB8:def 1;
thus ( (the Target of ( ( G1 \/ G2 ) \/ G3 )) . v ) = ( (the Target of G3) . v ) by A25,A26,A70,CKB8:def 1
.= ( (the Target of ( G2 \/ G3 )) . v ) by A5,A6,A70,CKB8:def 1
.= ( (the Target of ( G1 \/ ( G2 \/ G3 ) )) . v ) by A45,A46,A70,A71,CKB8:def 1;
end;
hence thesis by A63,A64,A66,XBOOLE_0:def 3;
end;
hence thesis by A47,A48,A60,A61,FUNCT_1:2;
end;
