environ
vocabularies TARSKI,XBOOLE_0;
notations TARSKI,XBOOLE_0;
definitions TARSKI,XBOOLE_0;
theorems TARSKI,XBOOLE_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22;
registrations XBOOLE_0;
constructors TARSKI,XBOOLE_0;
requirements BOOLE;
begin
reserve x for set;
reserve X for set;
reserve Y for set;
reserve Z for set;
theorem
Th23: ( X /\ ( Y \/ Z ) ) = ( ( X /\ Y ) \/ ( X /\ Z ) )
proof
thus ( X /\ ( Y \/ Z ) ) c= ( ( X /\ Y ) \/ ( X /\ Z ) )
proof
let x;
assume A1: x in ( X /\ ( Y \/ Z ) );
then x in ( Y \/ Z ) by XBOOLE_0:def 4;
then A2: (x in Y or x in Z) by XBOOLE_0:def 3;
x in X by A1,XBOOLE_0:def 4;
then (x in ( X /\ Y ) or x in ( X /\ Z )) by A2,XBOOLE_0:def 4;
hence thesis by XBOOLE_0:def 3;
end;

let x;
assume x in ( ( X /\ Y ) \/ ( X /\ Z ) );
then (x in ( X /\ Y ) or x in ( X /\ Z )) by XBOOLE_0:def 3;
then A3: ((x in X & x in Y) or (x in X & x in Z)) by XBOOLE_0:def 4;
then x in ( Y \/ Z ) by XBOOLE_0:def 3;
hence thesis by A3,XBOOLE_0:def 4;
end;
