environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,MARGREL1,PARTIT1,EQREL_1,TARSKI,BVFUNC_2,FUNCOP_1,FUNCT_1,ZFMISC_1,SETFAM_1,RELAT_1,BVFUNC_1,XBOOLEAN;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,MARGREL1,RELAT_1,SETFAM_1,FUNCT_1,FUNCT_2,EQREL_1,FUNCOP_1,PARTIT1,BVFUNC_1,BVFUNC_2,FUNCT_4;
definitions TARSKI,BVFUNC_1,XBOOLE_0,XBOOLEAN,FUNCOP_1;
theorems TARSKI,FUNCT_1,SETFAM_1,EQREL_1,ZFMISC_1,PARTIT1,BVFUNC_1,BVFUNC_2,ENUMSET1,FUNCT_4,FUNCOP_1,MSSUBFAM,PARTIT_2,BVFUNC_4,XBOOLE_0,XBOOLE_1,XBOOLEAN,MARGREL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11;
registrations XBOOLE_0,FUNCOP_1,FUNCT_4,EQREL_1,MARGREL1;
constructors SETFAM_1,FUNCT_4,XCMPLX_0,BVFUNC_1,BVFUNC_2,RELSET_1;
requirements SUBSET,BOOLE,ARITHM;
begin
reserve Y for non empty set;
reserve a for (Element of ( Funcs (Y,( BOOLEAN )) ));
reserve G for (Subset of ( PARTITIONS Y ));
reserve A for (a_partition of Y);
reserve B for (a_partition of Y);
theorem
( All (( Ex (a,A,G) ),B,G) ) '<' ( Ex (( Ex (a,B,G) ),A,G) )
proof
A1: ( Ex (a,B,G) ) = ( B_SUP (a,( CompF (B,G) )) ) by BVFUNC_2:def 10;
let z being (Element of Y);
assume A2: ( ( All (( Ex (a,A,G) ),B,G) ) . z ) = ( TRUE );
A3:now
assume (not (for x being (Element of Y) holds (x in ( EqClass (z,( CompF (B,G) )) ) implies ( ( Ex (a,A,G) ) . x ) = ( TRUE ))));
then ( ( B_INF (( Ex (a,A,G) ),( CompF (B,G) )) ) . z ) = ( FALSE ) by BVFUNC_1:def 16;
hence contradiction by A2,BVFUNC_2:def 9;
end;
A4: z in ( EqClass (z,( CompF (B,G) )) ) by EQREL_1:def 6;
now
assume (not (ex x being (Element of Y) st (x in ( EqClass (z,( CompF (A,G) )) ) & ( a . x ) = ( TRUE ))));
then ( ( B_SUP (a,( CompF (A,G) )) ) . z ) = ( FALSE ) by BVFUNC_1:def 17;
then ( ( Ex (a,A,G) ) . z ) = ( FALSE ) by BVFUNC_2:def 10;
hence contradiction by A4,A3;
end;
then consider x1 being (Element of Y) such that A5: x1 in ( EqClass (z,( CompF (A,G) )) ) and A6: ( a . x1 ) = ( TRUE );
x1 in ( EqClass (x1,( CompF (B,G) )) ) by EQREL_1:def 6;
then ( ( Ex (a,B,G) ) . x1 ) = ( TRUE ) by A1,A6,BVFUNC_1:def 17;
then ( ( B_SUP (( Ex (a,B,G) ),( CompF (A,G) )) ) . z ) = ( TRUE ) by A5,BVFUNC_1:def 17;
hence thesis by BVFUNC_2:def 10;
end;
