environ
vocabularies XBOOLE_0,SUBSET_1,FUNCT_2,MARGREL1,BVFUNC_1,XBOOLEAN,FUNCT_1,RELAT_1,TARSKI,PARTIT1;
notations TARSKI,XBOOLE_0,SUBSET_1,XBOOLEAN,MARGREL1,RELAT_1,FUNCT_1,FUNCT_2,BVFUNC_1;
definitions BVFUNC_1,XBOOLEAN;
theorems FUNCT_1,FUNCT_2,MARGREL1,BINARITH,BVFUNC_1,BVFUNC_4,XBOOLEAN,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26;
registrations XBOOLE_0,XBOOLEAN,MARGREL1;
constructors BVFUNC_1;
requirements SUBSET,BOOLE;
begin
reserve Y for non empty set;
theorem
(for a,b being (Element of ( Funcs (Y,( BOOLEAN )) )) holds a '<' ( ( ( a '&' b ) 'eqv' ( b '&' a ) ) 'eqv' a ))
proof
let a being (Element of ( Funcs (Y,( BOOLEAN )) )),b being (Element of ( Funcs (Y,( BOOLEAN )) ));
let z being (Element of Y);
assume A1: ( a . z ) = ( TRUE );
A2: ( ( ( a '&' b ) 'eqv' ( a '&' b ) ) . z ) = ( ( ( ( a '&' b ) 'imp' ( a '&' b ) ) '&' ( ( a '&' b ) 'imp' ( a '&' b ) ) ) . z ) by BVFUNC_4:7
.= ( ( ( 'not' ( a '&' b ) ) 'or' ( a '&' b ) ) . z ) by BVFUNC_4:8
.= ( ( I_el Y ) . z ) by BVFUNC_4:6
.= ( TRUE ) by BVFUNC_1:def 11;
( ( ( ( a '&' b ) 'eqv' ( b '&' a ) ) 'eqv' a ) . z ) = ( ( ( ( ( a '&' b ) 'eqv' ( a '&' b ) ) 'imp' a ) '&' ( a 'imp' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) ) . z ) by BVFUNC_4:7
.= ( ( ( ( ( a '&' b ) 'eqv' ( a '&' b ) ) 'imp' a ) . z ) '&' ( ( a 'imp' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) . z ) ) by MARGREL1:def 20
.= ( ( ( ( 'not' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) 'or' a ) . z ) '&' ( ( a 'imp' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) . z ) ) by BVFUNC_4:8
.= ( ( ( ( 'not' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) 'or' a ) . z ) '&' ( ( ( 'not' a ) 'or' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) . z ) ) by BVFUNC_4:8
.= ( ( ( ( 'not' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) . z ) 'or' ( a . z ) ) '&' ( ( ( 'not' a ) 'or' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) . z ) ) by BVFUNC_1:def 4
.= ( ( ( ( 'not' ( ( a '&' b ) 'eqv' ( a '&' b ) ) ) . z ) 'or' ( a . z ) ) '&' ( ( ( 'not' a ) . z ) 'or' ( ( ( a '&' b ) 'eqv' ( a '&' b ) ) . z ) ) ) by BVFUNC_1:def 4
.= ( ( ( 'not' ( ( ( a '&' b ) 'eqv' ( a '&' b ) ) . z ) ) 'or' ( a . z ) ) '&' ( ( ( 'not' a ) . z ) 'or' ( ( ( a '&' b ) 'eqv' ( a '&' b ) ) . z ) ) ) by MARGREL1:def 19
.= ( ( ( FALSE ) 'or' ( a . z ) ) '&' ( ( ( 'not' a ) . z ) 'or' ( TRUE ) ) ) by A2,MARGREL1:11
.= ( ( a . z ) '&' ( ( ( 'not' a ) . z ) 'or' ( TRUE ) ) ) by BINARITH:3
.= ( ( TRUE ) '&' ( a . z ) ) by BINARITH:10
.= ( TRUE ) by A1;
hence thesis;
end;
