environ
vocabularies NUMBERS,INCSP_1,SUBSET_1,CARD_1,XBOOLE_0,ARYTM_3,TARSKI,ORDINAL1,FINSET_1,RELAT_1,ARYTM_1,NAT_1,FUNCT_1,XXREAL_0,FDIFF_1,WELLORD2,ZFMISC_1,ANPROJ_2,AFF_2,MOD_4,FUNCT_2,PRE_POLY,SETFAM_1,COMBGRAS;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,ENUMSET1,ZFMISC_1,SETFAM_1,DOMAIN_1,FINSET_1,RELAT_1,RELSET_1,WELLORD2,CARD_1,NUMBERS,INCSP_1,XXREAL_0,REAL_1,FUNCT_1,FUNCT_2,INCPROJ,NAT_1,CKB11,CKB12;
definitions TARSKI,INCSP_1,INCPROJ,FUNCT_1,RELAT_1,CKB12;
theorems ENUMSET1,TARSKI,ZFMISC_1,XBOOLE_0,XBOOLE_1,XREAL_1,SETFAM_1,PENCIL_1,INCSP_1,WELLORD2,CARD_1,CARD_2,NAT_1,ORDINAL1,CARD_FIL,STIRL2_1,CARD_FIN,XXREAL_0,INCPROJ,FUNCT_1,FUNCT_2,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB12,CKB13;
schemes FUNCT_1,NAT_1,CLASSES1;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,ORDINAL1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,NAT_1,CARD_1,INCSP_1,RELSET_1,CKB10;
constructors SETFAM_1,WELLORD2,DOMAIN_1,XXREAL_0,REAL_1,NAT_1,BINOP_2,INCPROJ,RELSET_1,CKB12;
requirements BOOLE,SUBSET,NUMERALS,ARITHM,REAL;
begin
reserve k for (Element of ( NAT ));
reserve X for set;
theorem
Th11: (for k being (Element of ( NAT )) holds (for X being non  empty set holds ((( 0 ) < k & ( k + 1 ) c= ( card X )) implies ( G_ (k,X) ) is  Vebleian)))
proof
let k being (Element of ( NAT ));
let X being non  empty set;
k <= ( k + 1 ) by NAT_1:11;
then A1: k c= ( k + 1 ) by NAT_1:39;
assume A2: (( 0 ) < k & ( k + 1 ) c= ( card X ));
then A3: (the Points of ( G_ (k,X) )) = { A where A is (Subset of X): ( card A ) = k } by CKB12:def 1;
let A1 being (POINT of ( G_ (k,X) ));
let A2 being (POINT of ( G_ (k,X) ));
let A3 being (POINT of ( G_ (k,X) ));
let A4 being (POINT of ( G_ (k,X) ));
let A5 being (POINT of ( G_ (k,X) ));
let A6 being (POINT of ( G_ (k,X) ));
let L1 being (LINE of ( G_ (k,X) ));
let L2 being (LINE of ( G_ (k,X) ));
let L3 being (LINE of ( G_ (k,X) ));
let L4 being (LINE of ( G_ (k,X) ));
assume that
A4: A1 on L1
and
A5: A2 on L1
and
A6: A3 on L2
and
A7: A4 on L2
and
A8: (A5 on L1 & A5 on L2)
and
A9: A1 on L3
and
A10: A3 on L3
and
A11: A2 on L4
and
A12: A4 on L4
and
A13: ((not A5 on L3) & (not A5 on L4))
and
A14: L1 <> L2;
A15: (A2 c= L1 & A4 c= L2) by A2,A5,A7,CKB13:1;
A16: (A1 <> A3 & A2 <> A4)
proof
assume (A1 = A3 or A2 = A4);
then (({ A1,A5 } on L1 & { A1,A5 } on L2) or ({ A2,A5 } on L1 & { A2,A5 } on L2)) by A4,A5,A6,A7,A8,INCSP_1:1;
hence contradiction by A9,A11,A13,A14,INCSP_1:def 10;
end;
A17: (the Lines of ( G_ (k,X) )) = { L where L is (Subset of X): ( card L ) = ( k + 1 ) } by A2,CKB12:def 1;
(A5 c= L1 & A5 c= L2) by A2,A8,CKB13:1;
then A18: A5 c= ( L1 /\ L2 ) by XBOOLE_1:19;
A5 in (the Points of ( G_ (k,X) ));
then (ex B5 being (Subset of X) st (B5 = A5 & ( card B5 ) = k)) by A3;
then A19: k c= ( card ( L1 /\ L2 ) ) by A18,CARD_1:11;
L2 in (the Lines of ( G_ (k,X) ));
then A20: (ex K2 being (Subset of X) st (K2 = L2 & ( card K2 ) = ( k + 1 ))) by A17;
A3 in (the Points of ( G_ (k,X) ));
then A21: (ex B3 being (Subset of X) st (B3 = A3 & ( card B3 ) = k)) by A3;
A1 in (the Points of ( G_ (k,X) ));
then (ex B1 being (Subset of X) st (B1 = A1 & ( card B1 ) = k)) by A3;
then A22: ( k + 1 ) c= ( card ( A1 \/ A3 ) ) by A21,A16,CKB1:1;
A23: (A1 c= L1 & A3 c= L2) by A2,A4,A6,CKB13:1;
L3 in (the Lines of ( G_ (k,X) ));
then A24: (ex K3 being (Subset of X) st (K3 = L3 & ( card K3 ) = ( k + 1 ))) by A17;
then A25: L3 is  finite;
A4 in (the Points of ( G_ (k,X) ));
then A26: (ex B4 being (Subset of X) st (B4 = A4 & ( card B4 ) = k)) by A3;
A2 in (the Points of ( G_ (k,X) ));
then (ex B2 being (Subset of X) st (B2 = A2 & ( card B2 ) = k)) by A3;
then A27: ( k + 1 ) c= ( card ( A2 \/ A4 ) ) by A26,A16,CKB1:1;
L4 in (the Lines of ( G_ (k,X) ));
then A28: (ex K4 being (Subset of X) st (K4 = L4 & ( card K4 ) = ( k + 1 ))) by A17;
then A29: L4 is  finite;
A30: (A2 c= L4 & A4 c= L4) by A2,A11,A12,CKB13:1;
then ( A2 \/ A4 ) c= L4 by XBOOLE_1:8;
then ( card ( A2 \/ A4 ) ) c= ( k + 1 ) by A28,CARD_1:11;
then ( card ( A2 \/ A4 ) ) = ( k + 1 ) by A27,XBOOLE_0:def 10;
then ( A2 \/ A4 ) = L4 by A28,A30,A29,CARD_FIN:1,XBOOLE_1:8;
then A31: L4 c= ( L1 \/ L2 ) by A15,XBOOLE_1:13;
L1 in (the Lines of ( G_ (k,X) ));
then A32: (ex K1 being (Subset of X) st (K1 = L1 & ( card K1 ) = ( k + 1 ))) by A17;
then ( card ( L1 /\ L2 ) ) in ( k + 1 ) by A20,A14,CKB1:1;
then ( card ( L1 /\ L2 ) ) in ( succ k ) by NAT_1:38;
then ( card ( L1 /\ L2 ) ) c= k by ORDINAL1:22;
then ( card ( L1 /\ L2 ) ) = k by A19,XBOOLE_0:def 10;
then A33: ( card ( L1 \/ L2 ) ) = ( k + ( 2 * 1 ) ) by A32,A20,CKB2:1;
A34: (A1 c= L3 & A3 c= L3) by A2,A9,A10,CKB13:1;
then ( A1 \/ A3 ) c= L3 by XBOOLE_1:8;
then ( card ( A1 \/ A3 ) ) c= ( k + 1 ) by A24,CARD_1:11;
then ( card ( A1 \/ A3 ) ) = ( k + 1 ) by A22,XBOOLE_0:def 10;
then ( A1 \/ A3 ) = L3 by A24,A34,A25,CARD_FIN:1,XBOOLE_1:8;
then L3 c= ( L1 \/ L2 ) by A23,XBOOLE_1:13;
then ( L3 \/ L4 ) c= ( L1 \/ L2 ) by A31,XBOOLE_1:8;
then ( card ( L3 \/ L4 ) ) c= ( k + 2 ) by A33,CARD_1:11;
then ( card ( L3 \/ L4 ) ) in ( succ ( k + 2 ) ) by ORDINAL1:22;
then (( card ( L3 \/ L4 ) ) in ( ( k + 1 ) + 1 ) or ( card ( L3 \/ L4 ) ) = ( k + 2 )) by ORDINAL1:8;
then (( card ( L3 \/ L4 ) ) in ( succ ( k + 1 ) ) or ( card ( L3 \/ L4 ) ) = ( k + 2 )) by NAT_1:38;
then A35: (( card ( L3 \/ L4 ) ) c= ( k + 1 ) or ( card ( L3 \/ L4 ) ) = ( k + 2 )) by ORDINAL1:22;
( k + 1 ) c= ( card ( L3 \/ L4 ) ) by A24,CARD_1:11,XBOOLE_1:7;
then (( card ( L3 \/ L4 ) ) = ( ( k + 1 ) + ( 2 * ( 0 ) ) ) or ( card ( L3 \/ L4 ) ) = ( k + ( 2 * 1 ) )) by A35,XBOOLE_0:def 10;
then k c= ( card ( L3 /\ L4 ) ) by A24,A28,A1,CKB2:1;
then consider B6 being set such that A36: B6 c= ( L3 /\ L4 ) and A37: ( card B6 ) = k by CARD_FIL:36;
A38: ( L3 /\ L4 ) c= L3 by XBOOLE_1:17;
then ( L3 /\ L4 ) c= X by A24,XBOOLE_1:1;
then reconsider A6 = B6 as (Subset of X) by A36,XBOOLE_1:1;
A39: A6 in (the Points of ( G_ (k,X) )) by A3,A37;
( L3 /\ L4 ) c= L4 by XBOOLE_1:17;
then A40: B6 c= L4 by A36,XBOOLE_1:1;
reconsider A6 as (POINT of ( G_ (k,X) )) by A39;
take B6;
(A6 c= B6 & B6 c= L3) by A36,A38,XBOOLE_1:1;
hence thesis by A2,A40,CKB13:1;
end;
