environ
vocabularies NUMBERS,INCSP_1,SUBSET_1,CARD_1,XBOOLE_0,ARYTM_3,TARSKI,ORDINAL1,FINSET_1,RELAT_1,ARYTM_1,NAT_1,FUNCT_1,XXREAL_0,FDIFF_1,WELLORD2,ZFMISC_1,ANPROJ_2,AFF_2,MOD_4,FUNCT_2,PRE_POLY,SETFAM_1,COMBGRAS;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,ENUMSET1,ZFMISC_1,SETFAM_1,DOMAIN_1,FINSET_1,RELAT_1,RELSET_1,WELLORD2,CARD_1,NUMBERS,INCSP_1,XXREAL_0,REAL_1,FUNCT_1,FUNCT_2,INCPROJ,NAT_1,CKB11,CKB12,CKB17,CKB18,CKB19,CKB20,CKB23,CKB24,CKB25,CKB27,CKB29,CKB30,CKB31,CKB32,CKB33,CKB40;
definitions TARSKI,INCSP_1,INCPROJ,FUNCT_1,RELAT_1,CKB12,CKB17,CKB18,CKB19,CKB20,CKB24,CKB25,CKB27,CKB29,CKB30,CKB31,CKB32,CKB33,CKB40;
theorems ENUMSET1,TARSKI,ZFMISC_1,XBOOLE_0,XBOOLE_1,XREAL_1,SETFAM_1,PENCIL_1,INCSP_1,WELLORD2,CARD_1,CARD_2,NAT_1,ORDINAL1,CARD_FIL,STIRL2_1,CARD_FIN,XXREAL_0,INCPROJ,FUNCT_1,FUNCT_2,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48;
schemes FUNCT_1,NAT_1,CLASSES1;
registrations XBOOLE_0,SUBSET_1,FUNCT_1,ORDINAL1,FUNCT_2,FINSET_1,XXREAL_0,XREAL_0,NAT_1,CARD_1,INCSP_1,RELSET_1,CKB10,CKB23;
constructors SETFAM_1,WELLORD2,DOMAIN_1,XXREAL_0,REAL_1,NAT_1,BINOP_2,INCPROJ,RELSET_1,CKB12,CKB17,CKB18,CKB19,CKB20,CKB23,CKB24,CKB25,CKB27,CKB29,CKB30,CKB31,CKB32,CKB33,CKB40;
requirements BOOLE,SUBSET,NUMERALS,ARITHM,REAL;
begin
reserve k for (Element of ( NAT ));
reserve x for set;
reserve X for set;
theorem
Th32: (for k being (Element of ( NAT )) holds (for X being non  empty set holds ((( 0 ) < k & ( k + 3 ) c= ( card X )) implies (for F being IncProjMap over ( G_ (( k + 1 ),X) ),( G_ (( k + 1 ),X) ) holds (F is  automorphism implies (for H being IncProjMap over ( G_ (k,X) ),( G_ (k,X) ) holds ((the line-map of H) = (the point-map of F) implies (for f being (Permutation of X) holds (( the IncProjMap of H ) = ( incprojmap (k,f) ) implies ( the IncProjMap of F ) = ( incprojmap (( k + 1 ),f) ))))))))))
proof
let k being (Element of ( NAT ));
let X being non  empty set;
assume that
A1: ( 0 ) < k
and
A2: ( k + 3 ) c= ( card X );
( k + 1 ) <= ( k + 3 ) by XREAL_1:7;
then ( k + 1 ) c= ( k + 3 ) by NAT_1:39;
then A3: ( k + 1 ) c= ( card X ) by A2,XBOOLE_1:1;
then A4: (the Lines of ( G_ (k,X) )) = { L where L is (Subset of X): ( card L ) = ( k + 1 ) } by A1,CKB12:def 1;
( k + 2 ) <= ( k + 3 ) by XREAL_1:7;
then ( k + 2 ) c= ( k + 3 ) by NAT_1:39;
then A5: ( ( k + 1 ) + 1 ) c= ( card X ) by A2,XBOOLE_1:1;
then A6: (the Points of ( G_ (( k + 1 ),X) )) = { A where A is (Subset of X): ( card A ) = ( k + 1 ) } by CKB12:def 1;
( k + ( 0 ) ) <= ( k + 1 ) by XREAL_1:7;
then A7: k c= ( k + 1 ) by NAT_1:39;
( k + 1 ) <= ( k + 2 ) by XREAL_1:7;
then A8: ( k + 1 ) c= ( k + 2 ) by NAT_1:39;
let F being IncProjMap over ( G_ (( k + 1 ),X) ),( G_ (( k + 1 ),X) );
assume that
A9: F is  automorphism;
A10: F is  incidence_preserving by A9,CKB29:def 1;
let H being IncProjMap over ( G_ (k,X) ),( G_ (k,X) );
assume that
A11: (the line-map of H) = (the point-map of F);
A12: ( dom (the point-map of F) ) = (the Points of ( G_ (( k + 1 ),X) )) by FUNCT_2:52;
let f being (Permutation of X);
assume that
A13: ( the IncProjMap of H ) = ( incprojmap (k,f) );
A14: (for x holds (x in ( dom (the point-map of F) ) implies ( (the point-map of F) . x ) = ( (the point-map of ( incprojmap (( k + 1 ),f) )) . x )))
proof
let x being set;
assume x in ( dom (the point-map of F) );
then consider A being (POINT of ( G_ (( k + 1 ),X) )) such that A15: x = A;
consider A1 being (LINE of ( G_ (k,X) )) such that A16: x = A1 by A4,A6,A15;
( ( incprojmap (k,f) ) . A1 ) = ( f .: A1 ) by A1,A3,CKB40:def 1;
then ( F . A ) = ( ( incprojmap (( k + 1 ),f) ) . A ) by A11,A13,A5,A15,A16,CKB40:def 1;
hence thesis by A15;
end;
A17: (the Lines of ( G_ (( k + 1 ),X) )) = { L where L is (Subset of X): ( card L ) = ( ( k + 1 ) + 1 ) } by A5,CKB12:def 1;
A18: (the point-map of F) is  bijective by A9,CKB29:def 1;
A19: (for x holds (x in ( dom (the line-map of F) ) implies ( (the line-map of F) . x ) = ( (the line-map of ( incprojmap (( k + 1 ),f) )) . x )))
proof
let x being set;
assume x in ( dom (the line-map of F) );
then consider A being (LINE of ( G_ (( k + 1 ),X) )) such that A20: x = A;
x in (the Lines of ( G_ (( k + 1 ),X) )) by A20;
then A21: (ex A11 being (Subset of X) st (x = A11 & ( card A11 ) = ( ( k + 1 ) + 1 ))) by A17;
then consider B1 being set such that A22: B1 c= x and A23: ( card B1 ) = ( k + 1 ) by A8,CARD_FIL:36;
A24: x is  finite by A21;
then A25: ( card ( x \ B1 ) ) = ( ( k + 2 ) - ( k + 1 ) ) by A21,A22,A23,CARD_2:44;
B1 c= X by A21,A22,XBOOLE_1:1;
then B1 in (the Points of ( G_ (( k + 1 ),X) )) by A6,A23;
then consider b1 being (POINT of ( G_ (( k + 1 ),X) )) such that A26: b1 = B1;
consider C1 being set such that A27: C1 c= B1 and A28: ( card C1 ) = k by A7,A23,CARD_FIL:36;
B1 is  finite by A23;
then A29: ( card ( C1 \/ ( x \ B1 ) ) ) = ( k + 1 ) by A27,A28,A24,A25,CARD_2:40,XBOOLE_1:85;
C1 c= x by A22,A27,XBOOLE_1:1;
then A30: ( C1 \/ ( x \ B1 ) ) c= x by XBOOLE_1:8;
then ( C1 \/ ( x \ B1 ) ) c= X by A21,XBOOLE_1:1;
then ( C1 \/ ( x \ B1 ) ) in (the Points of ( G_ (( k + 1 ),X) )) by A6,A29;
then consider b2 being (POINT of ( G_ (( k + 1 ),X) )) such that A31: b2 = ( C1 \/ ( x \ B1 ) );
b2 on A by A5,A20,A30,A31,CKB13:1;
then ( F . b2 ) on ( F . A ) by A10,CKB27:def 1;
then A32: ( F . b2 ) c= ( F . A ) by A5,CKB13:1;
( B1 \/ ( C1 \/ ( x \ B1 ) ) ) c= x by A22,A30,XBOOLE_1:8;
then A33: ( card ( b1 \/ b2 ) ) c= ( k + 2 ) by A21,A26,A31,CARD_1:11;
B1 misses ( x \ B1 ) by XBOOLE_1:79;
then ( card ( ( x \ B1 ) /\ B1 ) ) = ( 0 ) by CARD_1:27,XBOOLE_0:def 7;
then A34: b1 <> b2 by A25,A26,A31,XBOOLE_1:11,XBOOLE_1:28;
then ( ( k + 1 ) + 1 ) c= ( card ( b1 \/ b2 ) ) by A23,A29,A26,A31,CKB1:1;
then ( card ( b1 \/ b2 ) ) = ( k + 2 ) by A33,XBOOLE_0:def 10;
then A35: ( b1 \/ b2 ) = x by A21,A22,A24,A30,A26,A31,CARD_FIN:1,XBOOLE_1:8;
( F . b2 ) in (the Points of ( G_ (( k + 1 ),X) ));
then A36: (ex B12 being (Subset of X) st (( F . b2 ) = B12 & ( card B12 ) = ( k + 1 ))) by A6;
( F . b1 ) in (the Points of ( G_ (( k + 1 ),X) ));
then A37: (ex B11 being (Subset of X) st (( F . b1 ) = B11 & ( card B11 ) = ( k + 1 ))) by A6;
( F . A ) in (the Lines of ( G_ (( k + 1 ),X) ));
then A38: (ex L1 being (Subset of X) st (( F . A ) = L1 & ( card L1 ) = ( ( k + 1 ) + 1 ))) by A17;
then A39: ( F . A ) is  finite;
( F . b1 ) <> ( F . b2 ) by A18,A12,A34,FUNCT_1:def 4;
then A40: ( ( k + 1 ) + 1 ) c= ( card ( ( F . b1 ) \/ ( F . b2 ) ) ) by A37,A36,CKB1:1;
b1 on A by A5,A20,A22,A26,CKB13:1;
then ( F . b1 ) on ( F . A ) by A10,CKB27:def 1;
then A41: ( F . b1 ) c= ( F . A ) by A5,CKB13:1;
then ( ( F . b1 ) \/ ( F . b2 ) ) c= ( F . A ) by A32,XBOOLE_1:8;
then ( card ( ( F . b1 ) \/ ( F . b2 ) ) ) c= ( k + 2 ) by A38,CARD_1:11;
then ( card ( ( F . b1 ) \/ ( F . b2 ) ) ) = ( k + 2 ) by A40,XBOOLE_0:def 10;
then A42: ( ( F . b1 ) \/ ( F . b2 ) ) = ( F . A ) by A41,A32,A38,A39,CARD_FIN:1,XBOOLE_1:8;
A43: ( ( incprojmap (( k + 1 ),f) ) . A ) = ( f .: x ) by A5,A20,CKB40:def 1;
A44: (( ( f .: b1 ) \/ ( f .: b2 ) ) = ( f .: ( b1 \/ b2 ) ) & ( F . b2 ) = ( ( incprojmap (( k + 1 ),f) ) . b2 )) by A12,A14,RELAT_1:120;
(( F . b1 ) = ( ( incprojmap (( k + 1 ),f) ) . b1 ) & ( ( incprojmap (( k + 1 ),f) ) . b1 ) = ( f .: b1 )) by A5,A12,A14,CKB40:def 1;
hence thesis by A5,A20,A35,A42,A43,A44,CKB40:def 1;
end;
A45: (( dom (the line-map of F) ) = (the Lines of ( G_ (( k + 1 ),X) )) & ( dom (the line-map of ( incprojmap (( k + 1 ),f) )) ) = (the Lines of ( G_ (( k + 1 ),X) ))) by FUNCT_2:52;
( dom (the point-map of ( incprojmap (( k + 1 ),f) )) ) = (the Points of ( G_ (( k + 1 ),X) )) by FUNCT_2:52;
then (the point-map of F) = (the point-map of ( incprojmap (( k + 1 ),f) )) by A12,A14,FUNCT_1:def 11;
hence thesis by A45,A19,FUNCT_1:def 11;
end;
