environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,MEASURE6,ARYTM_3,ARYTM_1,RELAT_1,REAL_1,XBOOLE_0,PARTFUN1,COMPLEX1,SUBSET_1,FUNCT_1,PROB_1,MEASURE1,XCMPLX_0,MESFUNC1,VALUED_1,CARD_1,TARSKI,INTEGRA5,MESFUNC5,XXREAL_0,RFUNCT_3,SUPINF_2,POWER,SQUARE_1,PREPOWER,VALUED_0;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,VALUED_1,SUPINF_2,SEQ_1,PREPOWER,POWER,SQUARE_1,MEASURE6,MEASURE1,EXTREAL1,COMSEQ_3,VALUED_0,MESFUNC1,MESFUNC2,PROB_1,MESFUNC5,MESFUNC6,CKB2,CKB20,CKB21,CKB30;
definitions MESFUNC5,MEASURE6,VALUED_1,MESFUNC6,COMPLEX1,XCMPLX_0,VALUED_0,SUPINF_2,CKB2,CKB20,CKB21,CKB30;
theorems TARSKI,PARTFUN1,FUNCT_1,SUPINF_2,EXTREAL1,EXTREAL2,MESFUNC1,XBOOLE_0,XBOOLE_1,XCMPLX_1,HOLDER_1,PREPOWER,MESFUNC2,XREAL_1,MESFUNC5,XXREAL_0,VALUED_1,MESFUNC6,SUBSET_1,COMPLEX1,XREAL_0,RELAT_1,POWER,SQUARE_1,RELSET_1,FINSUB_1,COMSEQ_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42;
schemes SEQ_1;
registrations XBOOLE_0,SUBSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,MEASURE1,VALUED_0,XCMPLX_0,RELAT_1,FUNCT_1,COMSEQ_3,RELSET_1,CKB31,CKB32;
constructors REAL_1,SEQ_1,PREPOWER,POWER,SQUARE_1,COMPLEX1,MEASURE6,EXTREAL1,MESFUNC1,MESFUNC2,MESFUNC5,MESFUNC6,EXTREAL2,SUPINF_1,RELSET_1,ABIAN,BINOP_2,VALUED_0,COMSEQ_3,CKB2,CKB20,CKB21,CKB30;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve X for non empty set;
reserve S for (SigmaField of X);
reserve M for (sigma_Measure of S);
reserve f for (PartFunc of X,( COMPLEX ));
reserve g for (PartFunc of X,( COMPLEX ));
theorem
Th36: ((f is_integrable_on M & g is_integrable_on M) implies (ex E being (Element of S) st (E = ( ( dom f ) /\ ( dom g ) ) & ( Integral (M,( f + g )) ) = ( ( Integral (M,( f | E )) ) + ( Integral (M,( g | E )) ) ))))
proof
assume that
A1: f is_integrable_on M
and
A2: g is_integrable_on M;
A3: ( Re g ) is_integrable_on M by A2,CKB20:def 1;
( Re f ) is_integrable_on M by A1,CKB20:def 1;
then consider E being (Element of S) such that A4: E = ( ( dom ( Re f ) ) /\ ( dom ( Re g ) ) ) and A5: ( Integral (M,( ( Re f ) + ( Re g ) )) ) = ( ( Integral (M,( ( Re f ) | E )) ) + ( Integral (M,( ( Re g ) | E )) ) ) by A3,MESFUNC6:101;
A6: ( f | E ) is_integrable_on M by A1,CKB27:1;
then A7: ( Re ( f | E ) ) is_integrable_on M by CKB20:def 1;
then A8: ( Integral (M,( Re ( f | E ) )) ) < ( +infty ) by MESFUNC6:90;
A9: ( Im ( f | E ) ) is_integrable_on M by A6,CKB20:def 1;
then A10: ( -infty ) < ( Integral (M,( Im ( f | E ) )) ) by MESFUNC6:90;
A11: ( Integral (M,( Im ( f | E ) )) ) < ( +infty ) by A9,MESFUNC6:90;
( -infty ) < ( Integral (M,( Re ( f | E ) )) ) by A7,MESFUNC6:90;
then reconsider R1 = ( Integral (M,( Re ( f | E ) )) ),I1 = ( Integral (M,( Im ( f | E ) )) ) as Real by A8,A10,A11,XXREAL_0:14;
A12: ( dom f ) = ( dom ( Re f ) ) by COMSEQ_3:def 3;
A13: ( Im g ) is_integrable_on M by A2,CKB20:def 1;
( Im f ) is_integrable_on M by A1,CKB20:def 1;
then A14: (ex Ei being (Element of S) st (Ei = ( ( dom ( Im f ) ) /\ ( dom ( Im g ) ) ) & ( Integral (M,( ( Im f ) + ( Im g ) )) ) = ( ( Integral (M,( ( Im f ) | Ei )) ) + ( Integral (M,( ( Im g ) | Ei )) ) ))) by A13,MESFUNC6:101;
A15: ( Integral (M,( ( Im f ) + ( Im g ) )) ) = ( Integral (M,( Im ( f + g ) )) ) by CKB6:1;
A16: ( f + g ) is_integrable_on M by A1,A2,CKB40:1;
then A17: ( Re ( f + g ) ) is_integrable_on M by CKB20:def 1;
then A18: ( Integral (M,( Re ( f + g ) )) ) < ( +infty ) by MESFUNC6:90;
A19: ( Im ( f + g ) ) is_integrable_on M by A16,CKB20:def 1;
then A20: ( -infty ) < ( Integral (M,( Im ( f + g ) )) ) by MESFUNC6:90;
A21: ( Integral (M,( Im ( f + g ) )) ) < ( +infty ) by A19,MESFUNC6:90;
( -infty ) < ( Integral (M,( Re ( f + g ) )) ) by A17,MESFUNC6:90;
then reconsider R = ( Integral (M,( Re ( f + g ) )) ),I = ( Integral (M,( Im ( f + g ) )) ) as Real by A18,A20,A21,XXREAL_0:14;
A22: ( Integral (M,( f + g )) ) = ( R + ( I * ( <i> ) ) ) by A16,CKB21:def 1;
A23: ( dom g ) = ( dom ( Im g ) ) by COMSEQ_3:def 4;
A24: ( g | E ) is_integrable_on M by A2,CKB27:1;
then A25: ( Re ( g | E ) ) is_integrable_on M by CKB20:def 1;
then A26: ( Integral (M,( Re ( g | E ) )) ) < ( +infty ) by MESFUNC6:90;
A27: ( Im ( g | E ) ) is_integrable_on M by A24,CKB20:def 1;
then A28: ( -infty ) < ( Integral (M,( Im ( g | E ) )) ) by MESFUNC6:90;
A29: ( Integral (M,( Im ( g | E ) )) ) < ( +infty ) by A27,MESFUNC6:90;
( -infty ) < ( Integral (M,( Re ( g | E ) )) ) by A25,MESFUNC6:90;
then reconsider R2 = ( Integral (M,( Re ( g | E ) )) ),I2 = ( Integral (M,( Im ( g | E ) )) ) as Real by A26,A28,A29,XXREAL_0:14;
A30: ( dom g ) = ( dom ( Re g ) ) by COMSEQ_3:def 3;
( Integral (M,( ( Re f ) + ( Re g ) )) ) = ( Integral (M,( Re ( f + g ) )) ) by CKB6:1;
then ( Integral (M,( Re ( f + g ) )) ) = ( ( Integral (M,( Re ( f | E ) )) ) + ( Integral (M,( ( Re g ) | E )) ) ) by A5,CKB8:1
.= ( ( Integral (M,( Re ( f | E ) )) ) + ( Integral (M,( Re ( g | E ) )) ) ) by CKB8:1;
then A31: R = ( R1 + R2 ) by SUPINF_2:1;
( dom f ) = ( dom ( Im f ) ) by COMSEQ_3:def 4;
then ( Integral (M,( Im ( f + g ) )) ) = ( ( Integral (M,( Im ( f | E ) )) ) + ( Integral (M,( ( Im g ) | E )) ) ) by A4,A12,A30,A23,A14,A15,CKB8:1;
then ( R_EAL I ) = ( ( R_EAL I1 ) + ( R_EAL I2 ) ) by CKB8:1;
then I = ( I1 + I2 ) by SUPINF_2:1;
then ( Integral (M,( f + g )) ) = ( ( R1 + ( I1 * ( <i> ) ) ) + ( R2 + ( I2 * ( <i> ) ) ) ) by A31,A22;
then ( Integral (M,( f + g )) ) = ( ( Integral (M,( f | E )) ) + ( R2 + ( I2 * ( <i> ) ) ) ) by A6,CKB21:def 1;
then ( Integral (M,( f + g )) ) = ( ( Integral (M,( f | E )) ) + ( Integral (M,( g | E )) ) ) by A24,CKB21:def 1;
hence thesis by A4,A12,A30;
end;
