environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,MEASURE6,ARYTM_3,ARYTM_1,RELAT_1,REAL_1,XBOOLE_0,PARTFUN1,COMPLEX1,SUBSET_1,FUNCT_1,PROB_1,MEASURE1,XCMPLX_0,MESFUNC1,VALUED_1,CARD_1,TARSKI,INTEGRA5,MESFUNC5,XXREAL_0,RFUNCT_3,SUPINF_2,POWER,SQUARE_1,PREPOWER,VALUED_0;
notations TARSKI,XBOOLE_0,SUBSET_1,ORDINAL1,NUMBERS,XXREAL_0,XCMPLX_0,XREAL_0,COMPLEX1,REAL_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,VALUED_1,SUPINF_2,SEQ_1,PREPOWER,POWER,SQUARE_1,MEASURE6,MEASURE1,EXTREAL1,COMSEQ_3,VALUED_0,MESFUNC1,MESFUNC2,PROB_1,MESFUNC5,MESFUNC6,CKB2,CKB20,CKB21,CKB30,CKB53;
definitions MESFUNC5,MEASURE6,VALUED_1,MESFUNC6,COMPLEX1,XCMPLX_0,VALUED_0,SUPINF_2,CKB2,CKB20,CKB21,CKB30,CKB53;
theorems TARSKI,PARTFUN1,FUNCT_1,SUPINF_2,EXTREAL1,EXTREAL2,MESFUNC1,XBOOLE_0,XBOOLE_1,XCMPLX_1,HOLDER_1,PREPOWER,MESFUNC2,XREAL_1,MESFUNC5,XXREAL_0,VALUED_1,MESFUNC6,SUBSET_1,COMPLEX1,XREAL_0,RELAT_1,POWER,SQUARE_1,RELSET_1,FINSUB_1,COMSEQ_3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53;
schemes SEQ_1;
registrations XBOOLE_0,SUBSET_1,NUMBERS,XXREAL_0,XREAL_0,MEMBERED,MEASURE1,VALUED_0,XCMPLX_0,RELAT_1,FUNCT_1,COMSEQ_3,RELSET_1,CKB31,CKB32;
constructors REAL_1,SEQ_1,PREPOWER,POWER,SQUARE_1,COMPLEX1,MEASURE6,EXTREAL1,MESFUNC1,MESFUNC2,MESFUNC5,MESFUNC6,EXTREAL2,SUPINF_1,RELSET_1,ABIAN,BINOP_2,VALUED_0,COMSEQ_3,CKB2,CKB20,CKB21,CKB30,CKB53;
requirements NUMERALS,REAL,BOOLE,SUBSET,ARITHM;
begin
reserve X for non empty set;
reserve S for (SigmaField of X);
reserve M for (sigma_Measure of S);
reserve f for (PartFunc of X,( COMPLEX ));
reserve g for (PartFunc of X,( COMPLEX ));
reserve B for (Element of S);
theorem
(((f is_integrable_on M & g is_integrable_on M) & B c= ( dom ( f + g ) )) implies (( f + g ) is_integrable_on M & ( Integral_on (M,B,( f + g )) ) = ( ( Integral_on (M,B,f) ) + ( Integral_on (M,B,g) ) )))
proof
assume that
A1: f is_integrable_on M
and
A2: g is_integrable_on M
and
A3: B c= ( dom ( f + g ) );
A4: ( Re f ) is_integrable_on M by A1,CKB20:def 1;
then ( ( Re f ) | B ) is_integrable_on M by MESFUNC6:91;
then A5: ( Re ( f | B ) ) is_integrable_on M by CKB8:1;
then A6: ( Integral (M,( Re ( f | B ) )) ) < ( +infty ) by MESFUNC6:90;
A7: ( Im f ) is_integrable_on M by A1,CKB20:def 1;
then ( ( Im f ) | B ) is_integrable_on M by MESFUNC6:91;
then A8: ( Im ( f | B ) ) is_integrable_on M by CKB8:1;
then A9: ( -infty ) < ( Integral (M,( Im ( f | B ) )) ) by MESFUNC6:90;
A10: ( Integral (M,( Im ( f | B ) )) ) < ( +infty ) by A8,MESFUNC6:90;
( -infty ) < ( Integral (M,( Re ( f | B ) )) ) by A5,MESFUNC6:90;
then reconsider R1 = ( Integral (M,( Re ( f | B ) )) ),I1 = ( Integral (M,( Im ( f | B ) )) ) as Real by A6,A9,A10,XXREAL_0:14;
( f | B ) is_integrable_on M by A5,A8,CKB20:def 1;
then A11: ( Integral (M,( f | B )) ) = ( R1 + ( I1 * ( <i> ) ) ) by CKB21:def 1;
A12: ( Im g ) is_integrable_on M by A2,CKB20:def 1;
then ( ( Im g ) | B ) is_integrable_on M by MESFUNC6:91;
then A13: ( Im ( g | B ) ) is_integrable_on M by CKB8:1;
then A14: ( -infty ) < ( Integral (M,( Im ( g | B ) )) ) by MESFUNC6:90;
A15: ( Re g ) is_integrable_on M by A2,CKB20:def 1;
then ( ( Re g ) | B ) is_integrable_on M by MESFUNC6:91;
then A16: ( Re ( g | B ) ) is_integrable_on M by CKB8:1;
then A17: ( Integral (M,( Re ( g | B ) )) ) < ( +infty ) by MESFUNC6:90;
B c= ( dom ( Im ( f + g ) ) ) by A3,COMSEQ_3:def 4;
then A18: B c= ( dom ( ( Im f ) + ( Im g ) ) ) by CKB6:1;
then ( Integral_on (M,B,( ( Im f ) + ( Im g ) )) ) = ( ( Integral_on (M,B,( Im f )) ) + ( Integral_on (M,B,( Im g )) ) ) by A7,A12,MESFUNC6:103;
then A19: ( Integral (M,( ( Im ( f + g ) ) | B )) ) = ( ( Integral (M,( ( Im f ) | B )) ) + ( Integral (M,( ( Im g ) | B )) ) ) by CKB6:1;
A20: ( Integral (M,( Im ( g | B ) )) ) < ( +infty ) by A13,MESFUNC6:90;
( -infty ) < ( Integral (M,( Re ( g | B ) )) ) by A16,MESFUNC6:90;
then reconsider R2 = ( Integral (M,( Re ( g | B ) )) ),I2 = ( Integral (M,( Im ( g | B ) )) ) as Real by A17,A14,A20,XXREAL_0:14;
( g | B ) is_integrable_on M by A16,A13,CKB20:def 1;
then A21: ( Integral (M,( g | B )) ) = ( R2 + ( I2 * ( <i> ) ) ) by CKB21:def 1;
A22: ( Integral (M,( ( Im g ) | B )) ) = I2 by CKB8:1;
( ( Im f ) + ( Im g ) ) is_integrable_on M by A7,A12,A18,MESFUNC6:103;
then A23: ( Im ( f + g ) ) is_integrable_on M by CKB6:1;
then ( ( Im ( f + g ) ) | B ) is_integrable_on M by MESFUNC6:91;
then A24: ( Im ( ( f + g ) | B ) ) is_integrable_on M by CKB8:1;
then A25: ( -infty ) < ( Integral (M,( Im ( ( f + g ) | B ) )) ) by MESFUNC6:90;
B c= ( dom ( Re ( f + g ) ) ) by A3,COMSEQ_3:def 3;
then A26: B c= ( dom ( ( Re f ) + ( Re g ) ) ) by CKB6:1;
then ( Integral_on (M,B,( ( Re f ) + ( Re g ) )) ) = ( ( Integral_on (M,B,( Re f )) ) + ( Integral_on (M,B,( Re g )) ) ) by A4,A15,MESFUNC6:103;
then A27: ( Integral (M,( ( Re ( f + g ) ) | B )) ) = ( ( Integral (M,( ( Re f ) | B )) ) + ( Integral (M,( ( Re g ) | B )) ) ) by CKB6:1;
( ( Re f ) + ( Re g ) ) is_integrable_on M by A4,A15,A26,MESFUNC6:103;
then A28: ( Re ( f + g ) ) is_integrable_on M by CKB6:1;
then ( ( Re ( f + g ) ) | B ) is_integrable_on M by MESFUNC6:91;
then A29: ( Re ( ( f + g ) | B ) ) is_integrable_on M by CKB8:1;
then A30: ( Integral (M,( Re ( ( f + g ) | B ) )) ) < ( +infty ) by MESFUNC6:90;
A31: ( Integral (M,( Im ( ( f + g ) | B ) )) ) < ( +infty ) by A24,MESFUNC6:90;
( -infty ) < ( Integral (M,( Re ( ( f + g ) | B ) )) ) by A29,MESFUNC6:90;
then reconsider R = ( Integral (M,( Re ( ( f + g ) | B ) )) ),I = ( Integral (M,( Im ( ( f + g ) | B ) )) ) as Real by A30,A25,A31,XXREAL_0:14;
A32: ( Integral (M,( ( Re g ) | B )) ) = R2 by CKB8:1;
( Integral (M,( ( Im f ) | B )) ) = I1 by CKB8:1;
then ( R_EAL I ) = ( ( R_EAL I1 ) + ( R_EAL I2 ) ) by A19,A22,CKB8:1;
then A33: I = ( I1 + I2 ) by SUPINF_2:1;
( Integral (M,( ( Re f ) | B )) ) = R1 by CKB8:1;
then ( R_EAL R ) = ( ( R_EAL R1 ) + ( R_EAL R2 ) ) by A27,A32,CKB8:1;
then A34: R = ( R1 + R2 ) by SUPINF_2:1;
( ( f + g ) | B ) is_integrable_on M by A29,A24,CKB20:def 1;
then ( Integral_on (M,B,( f + g )) ) = ( R + ( I * ( <i> ) ) ) by CKB21:def 1
.= ( ( Integral_on (M,B,f) ) + ( Integral_on (M,B,g) ) ) by A34,A33,A11,A21;
hence thesis by A28,A23,CKB20:def 1;
end;
