environ
vocabularies XBOOLE_0,STRUCT_0,MSUALG_1,RELAT_1,PBOOLE,MSAFREE,MSUALG_3,REALSET1,MEMBER_1,FUNCT_6,TARSKI,FUNCT_1,WELLORD1,MSUALG_2,PRALG_2,CARD_3,SUBSET_1,MSUALG_5,MSUALG_4,FUNCOP_1,RLVECT_2,PRALG_1,EQREL_1,CLOSURE2,SETFAM_1,FUNCT_4,ZFMISC_1,GROUP_6,NUMBERS,EQUATION,ZF_MODEL,ZF_LANG,MCART_1,PZFMISC1,MSAFREE2,FINSET_1,BIRKHOFF;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,NUMBERS,SETFAM_1,RELAT_1,MCART_1,STRUCT_0,FUNCT_1,PBOOLE,RELSET_1,PARTFUN1,FUNCT_2,FINSET_1,CARD_3,FUNCT_6,FUNCOP_1,MSUALG_1,MSUALG_2,PRALG_3,MSUALG_3,MSAFREE,MSAFREE2,PRALG_2,MSUALG_4,PZFMISC1,MSSUBFAM,CLOSURE2,MSUALG_5,EQUATION,CKB1;
definitions FUNCT_1,RELAT_1,TARSKI,PBOOLE,MSUALG_3,PRALG_2,MSUALG_4,EQUATION,FUNCOP_1,PZFMISC1,CKB1;
theorems AUTALG_1,CARD_3,CLOSURE2,EXTENS_1,FUNCOP_1,FUNCT_1,FUNCT_2,MCART_1,MSAFREE,MSAFREE2,MSSCYC_1,MSSUBFAM,MSUALG_2,MSUALG_3,MSUALG_4,MSUALG_5,MSUALG_7,MSUALG_9,PBOOLE,PRALG_2,PRALG_3,EQUATION,RELAT_1,ZFMISC_1,SETFAM_1,PARTFUN1,CKB1,CKB2;
schemes DOMAIN_1,PBOOLE,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10;
registrations XBOOLE_0,ORDINAL1,RELSET_1,FUNCT_2,FUNCOP_1,PBOOLE,STRUCT_0,MSUALG_1,MSUALG_2,MSUALG_4,MSAFREE1,MSAFREE2,EXTENS_1,MSUALG_5,CLOSURE2,PRALG_3,MSUALG_9,EQUATION,MSSUBFAM,AUTALG_1;
constructors SETFAM_1,BINOP_1,PZFMISC1,MSSUBFAM,MSUALG_3,MSAFREE2,MSUALG_5,CLOSURE2,PRALG_3,EQUATION,RELSET_1,CKB1;
requirements SUBSET,BOOLE;
begin
scheme AllFinGen { S() -> non empty non void ManySortedSign,X() ->  non-empty MSAlgebra over S(),P[set] } : P[ X() ]
provided
A1: (for B being  strict  non-empty  finitely-generated (MSSubAlgebra of X()) holds P[ B ])
and
A2: (for A,B being  non-empty MSAlgebra over S() holds ((A,B are_isomorphic  & P[ A ]) implies P[ B ]))
and
A3: (for A being  non-empty MSAlgebra over S() holds (for B being  strict  non-empty (MSSubAlgebra of A) holds (P[ A ] implies P[ B ])))
and
A4: (for A being  non-empty MSAlgebra over S() holds (for R being (MSCongruence of A) holds (P[ A ] implies P[ ( QuotMSAlg (A,R) ) ])))
and
A5: (for I being set holds (for F being (MSAlgebra-Family of I,S()) holds ((for i being set holds (i in I implies (ex A being MSAlgebra over S() st (A = ( F . i ) & P[ A ])))) implies P[ ( product F ) ])))
proof
A6: (for A,B being  non-empty MSAlgebra over S() holds ((A,B are_isomorphic  & P[ A ]) implies P[ B ])) by A2;
set T = the  strict  non-empty  finitely-generated (MSSubAlgebra of X());
set CC = { C where C is (Element of ( MSSub X() )): (ex R being  strict  non-empty  finitely-generated (MSSubAlgebra of X()) st R = C) };
T in ( MSSub X() ) by MSUALG_2:def 19;
then T in CC;
then reconsider CC as non empty set;
defpred P[ set,set ]
 means
$1 = $2;
A7: (for c being set holds (c in CC implies (ex j being set st P[ c,j ])));
consider FF being (ManySortedSet of CC) such that A8: (for c being set holds (c in CC implies P[ c,( FF . c ) ])) from PBOOLE:sch 3(A7);
FF is (MSAlgebra-Family of CC,S())
proof
let c being set;
assume A9: c in CC;
then (ex Q being (Element of ( MSSub X() )) st (c = Q & (ex R being  strict  non-empty  finitely-generated (MSSubAlgebra of X()) st R = Q)));
hence thesis by A8,A9;
end;
then reconsider FF as (MSAlgebra-Family of CC,S());
consider prSOR being  strict  non-empty (MSSubAlgebra of ( product FF )) such that A10: (ex BA being (ManySortedFunction of prSOR,X()) st BA is_epimorphism prSOR,X()) by A8,EQUATION:27;
A11: (for A being  non-empty MSAlgebra over S() holds (for R being (MSCongruence of A) holds (P[ A ] implies P[ ( QuotMSAlg (A,R) ) ]))) by A4;
(for i being set holds (i in CC implies (ex A being MSAlgebra over S() st (A = ( FF . i ) & P[ A ]))))
proof
let i being set;
assume A12: i in CC;
then consider Q being (Element of ( MSSub X() )) such that A13: i = Q and A14: (ex R being  strict  non-empty  finitely-generated (MSSubAlgebra of X()) st R = Q);
consider R being  strict  non-empty  finitely-generated (MSSubAlgebra of X()) such that A15: R = Q by A14;
take R;
thus thesis by A1,A8,A12,A13,A15;
end;
then A16: P[ prSOR ] by A3,A5;
thus P[ X() ] from CKB10:sch 1(A10,A16,A6,A11);
end;
