environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,XCMPLX_0,FUNCT_3,SQUARE_1,ARYTM_1,RELAT_1,REAL_1,CARD_1,ARYTM_3,XXREAL_0;
notations ORDINAL1,NUMBERS,XCMPLX_0,XREAL_0,REAL_1,SQUARE_1,XXREAL_0,CKB1;
definitions SQUARE_1,CKB1;
theorems XREAL_0,SQUARE_1,XCMPLX_1,XREAL_1,XXREAL_0,CKB1;
registrations XCMPLX_0,XREAL_0,SQUARE_1,MEMBERED;
constructors SQUARE_1,MEMBERED,CKB1;
requirements REAL,NUMERALS,SUBSET,ARITHM,BOOLE;
begin
reserve a for  real number;
reserve b for  real number;
reserve c for  real number;
registration
let a being  complex number;
let b being  complex number;
let c being  complex number;
cluster ( delta (a,b,c) ) ->  complex;
coherence;
end;
