environ
vocabularies NUMBERS,XBOOLE_0,STRUCT_0,PRE_TOPC,PENCIL_2,PENCIL_1,FUNCT_1,RELAT_1,TARSKI,SUBSET_1,PRALG_1,PBOOLE,ZFMISC_1,RELAT_2,FINSEQ_1,NAT_1,XXREAL_0,ARYTM_3,CARD_1,ARYTM_1,WAYBEL_3,RLVECT_2,CARD_3,INTEGRA1,FUNCT_4,FINSET_1,FDIFF_1,PARSP_1,GRAPH_2,FUNCT_2,CAT_1,RCOMP_1,FUNCOP_1,PENCIL_3;
notations TARSKI,XBOOLE_0,ZFMISC_1,XCMPLX_0,XXREAL_0,NUMBERS,NAT_1,RELAT_1,SUBSET_1,FUNCT_1,FUNCT_2,FUNCOP_1,RELSET_1,CARD_1,FINSET_1,FINSEQ_1,CARD_3,DOMAIN_1,STRUCT_0,PRE_TOPC,PBOOLE,PZFMISC1,T_0TOPSP,PRALG_1,WAYBEL_3,PENCIL_1,FUNCT_7,PENCIL_2,TOPS_2,GRAPH_2;
definitions TARSKI,XBOOLE_0,PBOOLE,FUNCT_1,T_0TOPSP,STRUCT_0,RELAT_1;
theorems XBOOLE_0,ZFMISC_1,FUNCT_1,FINSEQ_1,FINSEQ_3,NAT_1,CARD_3,PBOOLE,PRE_TOPC,FUNCT_7,PRALG_1,PZFMISC1,TARSKI,FUNCT_2,REALSET1,TOPS_2,PENCIL_1,PENCIL_2,CARD_1,XBOOLE_1,PUA2MSS1,FINSET_1,CARD_2,GRAPH_2,FUNCOP_1,RELAT_1,RELSET_1,XREAL_1,XXREAL_0,ORDINAL1,PARTFUN1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17;
schemes TRANSGEO,NAT_1,FINSEQ_2,PENCIL_2,FINSEQ_1,PBOOLE,CLASSES1;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FUNCT_2,XXREAL_0,XREAL_0,NAT_1,CARD_1,PBOOLE,REALSET1,STRUCT_0,PENCIL_1,ORDINAL1,FUNCT_1,RELAT_1,FINSEQ_1,ZFMISC_1,PRE_POLY;
constructors XXREAL_0,PZFMISC1,TOPS_2,REALSET2,T_0TOPSP,GRAPH_2,PENCIL_2,RELSET_1,PBOOLE,FUNCT_7,PRE_POLY;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
theorem
Th18: (for I being non  empty set holds (for A being  PLS-yielding (ManySortedSet of I) holds (for b being  Segre-like non  trivial-yielding (ManySortedSubset of ( Carrier A )) holds (for x being (Point of ( A . ( indx b ) )) holds (ex p being (ManySortedSet of I) st (p in ( product b ) & { (( p +* (( indx b ),x) ) qua set) } = ( product ( b +* (( indx b ),{ x }) ) )))))))
proof
let I being non  empty set;
let A being  PLS-yielding (ManySortedSet of I);
let b1 being  Segre-like non  trivial-yielding (ManySortedSubset of ( Carrier A ));
set i = ( indx b1 );
let x being (Point of ( A . i ));
consider bb being set such that A1: bb in ( product b1 ) by XBOOLE_0:def 1;
A2: (ex bf being Function st ((bf = bb & ( dom bf ) = ( dom b1 )) & (for o being set holds (o in ( dom b1 ) implies ( bf . o ) in ( b1 . o ))))) by A1,CARD_3:def 5;
A3: ( dom b1 ) = I by PARTFUN1:def 2;
then reconsider bb as (ManySortedSet of I) by A2,PARTFUN1:def 2,RELAT_1:def 18;
take p = bb;
thus p in ( product b1 ) by A1;
set bbx = ( bb +* (i,x) );
thus { (( p +* (i,x) ) qua set) } = ( product ( b1 +* (i,{ x }) ) )
proof
thus { (( p +* (i,x) ) qua set) } c= ( product ( b1 +* (i,{ x }) ) )
proof
A4:now
let z being set;
assume z in ( dom ( b1 +* (i,{ x }) ) );
then A5: z in I by PARTFUN1:def 2;
then A6: z in ( dom bb ) by PARTFUN1:def 2;
per cases ;
suppose A7: z = i;

then ( bbx . z ) = x by A6,FUNCT_7:31;
then ( bbx . z ) in { x } by TARSKI:def 1;
hence ( bbx . z ) in ( ( b1 +* (i,{ x }) ) . z ) by A3,A7,FUNCT_7:31;
end;
suppose A8: z <> i;

then ( bbx . z ) = ( bb . z ) by FUNCT_7:32;
then ( bbx . z ) in ( b1 . z ) by A1,A3,A5,CARD_3:9;
hence ( bbx . z ) in ( ( b1 +* (i,{ x }) ) . z ) by A8,FUNCT_7:32;
end;
end;
let o being set;
assume o in { (( p +* (i,x) ) qua set) };
then A9: o = bbx by TARSKI:def 1;
( dom bbx ) = I by PARTFUN1:def 2
.= ( dom ( b1 +* (i,{ x }) ) ) by PARTFUN1:def 2;
hence thesis by A9,A4,CARD_3:9;
end;

let o being set;
assume o in ( product ( b1 +* (i,{ x }) ) );
then consider u being Function such that A10: u = o and A11: ( dom u ) = ( dom ( b1 +* (i,{ x }) ) ) and A12: (for z being set holds (z in ( dom ( b1 +* (i,{ x }) ) ) implies ( u . z ) in ( ( b1 +* (i,{ x }) ) . z ))) by CARD_3:def 5;
A13:now
let z being set;
assume A14: z in ( dom u );
then A15: z in I by A11,PARTFUN1:def 2;
reconsider zz = z as (Element of I) by A11,A14,PARTFUN1:def 2;
A16: ( u . z ) in ( ( b1 +* (i,{ x }) ) . z ) by A11,A12,A14;
per cases ;
suppose A17: zz = i;

then ( u . z ) in { x } by A3,A16,FUNCT_7:31;
then ( u . z ) = x by TARSKI:def 1;
hence ( u . z ) = ( bbx . z ) by A2,A3,A17,FUNCT_7:31;
end;
suppose A18: zz <> i;

then ( b1 . zz ) is non  empty  trivial by PENCIL_1:def 21;
then ( b1 . zz ) is 1 -element;
then consider o being set such that A19: ( b1 . z ) = { o } by ZFMISC_1:131;
( u . z ) in ( b1 . z ) by A16,A18,FUNCT_7:32;
then A20: ( u . z ) = o by A19,TARSKI:def 1;
( bbx . z ) = ( bb . z ) by A18,FUNCT_7:32;
then ( bbx . z ) in { o } by A2,A3,A15,A19;
hence ( u . z ) = ( bbx . z ) by A20,TARSKI:def 1;
end;
end;
( dom u ) = I by A11,PARTFUN1:def 2
.= ( dom bbx ) by PARTFUN1:def 2;
then u = bbx by A13,FUNCT_1:2;
hence thesis by A10,TARSKI:def 1;
end;

end;
