environ
vocabularies TREES_1,FINSEQ_1,NUMBERS,SUBSET_1,ORDINAL4,XBOOLE_0,TARSKI,RELAT_1,XXREAL_0,ARYTM_3,TREES_2,FUNCT_1,TREES_A;
notations TARSKI,XBOOLE_0,SUBSET_1,NUMBERS,XXREAL_0,NAT_1,RELAT_1,FUNCT_1,FINSEQ_1,TREES_1,TREES_2,CKB2;
definitions TARSKI,XBOOLE_0,TREES_1,TREES_2,RELAT_1,CKB2;
theorems TARSKI,FUNCT_1,FINSEQ_1,TREES_1,TREES_2,XBOOLE_0,XBOOLE_1,RELAT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7;
schemes TREES_2;
registrations XBOOLE_0,RELSET_1,MEMBERED,FINSEQ_1,TREES_2;
constructors XXREAL_0,NAT_1,MEMBERED,TREES_2,RELSET_1,FINSEQ_2,CKB2;
requirements NUMERALS,BOOLE,SUBSET;
begin
reserve T for Tree;
reserve T1 for Tree;
reserve P for (AntiChain_of_Prefixes of T);
reserve p for (FinSequence of ( NAT ));
reserve x for set;
theorem
Th7: (P <> ( {} ) implies ( tree (T,P,T1) ) = ( { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } \/ { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P } ))
proof
assume A1: P <> ( {} );
then A2: ( tree (T,P,T1) ) = ( { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_proper_prefix_of t1))) } \/ { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P } ) by CKB3:1;
thus ( tree (T,P,T1) ) c= ( { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } \/ { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P } )
proof
let x being set;
assume x in ( tree (T,P,T1) );
then A3: x in ( { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_proper_prefix_of t1))) } \/ { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P } ) by A1,CKB3:1;
now
per cases ;
suppose A4: x in P;

P c= { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P } by CKB7:1;
hence (x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } or x in { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P }) by A4;
end;
suppose A5: (not x in P);

now
per cases  by A3,XBOOLE_0:def 3;
suppose A6: x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_proper_prefix_of t1))) };

x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) }
proof
assume A7: (not x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) });
( { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_proper_prefix_of t1))) } \ { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } ) = P by CKB6:1;
hence contradiction by A5,A6,A7,XBOOLE_0:def 5;
end;
hence (x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } or x in { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P });
end;
suppose x in { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P };

hence (x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } or x in { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P });
end;
end;
hence (x in { t1 where t1 is (Element of T): (for p holds (p in P implies (not p is_a_prefix_of t1))) } or x in { ( p ^ s ) where p is (Element of T),s is (Element of T1): p in P });
end;
end;
hence thesis by XBOOLE_0:def 3;
end;

thus thesis by A2,CKB4:1,XBOOLE_1:9;
end;
