environ
vocabularies RLVECT_1,ALGSTR_0,XBOOLE_0,SUBSET_1,ARYTM_1,SUPINF_2,ARYTM_3,VECTSP_1,PARSP_1,ZFMISC_1,STRUCT_0,MCART_1,RELAT_1,GROUP_1,MESFUNC1,PARSP_2;
notations ZFMISC_1,SUBSET_1,MCART_1,DOMAIN_1,STRUCT_0,ALGSTR_0,RLVECT_1,GROUP_1,VECTSP_1,PARSP_1;
theorems MCART_1,VECTSP_1,PARSP_1,RLVECT_1,GROUP_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
registrations XBOOLE_0,STRUCT_0,VECTSP_1,PARSP_1;
constructors DOMAIN_1,PARSP_1;
begin
reserve F for Field;
reserve a for (Element of ( MPS F ));
reserve b for (Element of ( MPS F ));
reserve c for (Element of ( MPS F ));
reserve e for (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
reserve f for (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
reserve g for (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
theorem
Th6: (ex a st (ex b st (ex c st (not a,b '||' a,c))))
proof
consider e,f,g being (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]) such that A1: e = [ ( 1_ F ),( 1_ F ),( 0. F ) ] and A2: f = [ ( - ( 0. F ) ),( 1_ F ),( 0. F ) ] and A3: g = [ ( 1_ F ),( - ( 0. F ) ),( 0. F ) ];
A4: (( f `1 ) = ( - ( 0. F ) ) & ( f `2 ) = ( 1_ F )) by A2,MCART_1:43;
A5: (( g `1 ) = ( 1_ F ) & ( g `2 ) = ( - ( 0. F ) )) by A3,MCART_1:43;
(the carrier of ( MPS F )) = [: (the carrier of F),(the carrier of F),(the carrier of F) :] by PARSP_1:10;
then consider a,b,c being (Element of ( MPS F )) such that A6: [ a,b,a,c ] = [ e,f,e,g ];
take a;
take b;
take c;
(( e `1 ) = ( 1_ F ) & ( e `2 ) = ( 1_ F )) by A1,MCART_1:43;
then A7: ( ( ( ( e `1 ) - ( f `1 ) ) * ( ( e `2 ) - ( g `2 ) ) ) - ( ( ( e `1 ) - ( g `1 ) ) * ( ( e `2 ) - ( f `2 ) ) ) ) = ( ( ( ( 1. F ) + ( - ( - ( 0. F ) ) ) ) * ( ( 1. F ) - ( - ( 0. F ) ) ) ) - ( ( ( 1. F ) - ( 1. F ) ) * ( ( 1. F ) - ( 1. F ) ) ) ) by A4,A5,RLVECT_1:def 11
.= ( ( ( ( 1. F ) + ( - ( - ( 0. F ) ) ) ) * ( ( 1. F ) + ( - ( - ( 0. F ) ) ) ) ) - ( ( ( 1. F ) - ( 1. F ) ) * ( ( 1. F ) - ( 1. F ) ) ) ) by RLVECT_1:def 11
.= ( ( ( ( 1. F ) + ( 0. F ) ) * ( ( 1. F ) + ( - ( - ( 0. F ) ) ) ) ) - ( ( ( 1. F ) - ( 1. F ) ) * ( ( 1. F ) - ( 1. F ) ) ) ) by RLVECT_1:17
.= ( ( ( ( 1. F ) + ( 0. F ) ) * ( ( 1. F ) + ( 0. F ) ) ) - ( ( ( 1. F ) - ( 1. F ) ) * ( ( 1. F ) - ( 1. F ) ) ) ) by RLVECT_1:17
.= ( ( ( 1. F ) * ( ( 1. F ) + ( 0. F ) ) ) - ( ( ( 1. F ) - ( 1. F ) ) * ( ( 1. F ) - ( 1. F ) ) ) ) by RLVECT_1:4
.= ( ( ( 1. F ) * ( 1. F ) ) - ( ( ( 1. F ) - ( 1. F ) ) * ( ( 1. F ) - ( 1. F ) ) ) ) by RLVECT_1:4
.= ( ( ( 1. F ) * ( 1. F ) ) - ( ( 0. F ) * ( ( 1. F ) - ( 1. F ) ) ) ) by RLVECT_1:15
.= ( ( ( 1. F ) * ( 1. F ) ) - ( 0. F ) ) by VECTSP_1:12
.= ( ( 1. F ) - ( 0. F ) ) by VECTSP_1:def 8;
now
let e9 being (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
let f9 being (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
let g9 being (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
let h9 being (Element of [: (the carrier of F),(the carrier of F),(the carrier of F) :]);
assume A8: [ e9,f9,g9,h9 ] = [ a,b,a,c ];
then A9: (g9 = e & h9 = g) by A6,MCART_1:29;
(e9 = e & f9 = f) by A6,A8,MCART_1:29;
hence ((( ( ( ( e9 `1 ) - ( f9 `1 ) ) * ( ( g9 `2 ) - ( h9 `2 ) ) ) - ( ( ( g9 `1 ) - ( h9 `1 ) ) * ( ( e9 `2 ) - ( f9 `2 ) ) ) ) <> ( 0. F ) or ( ( ( ( e9 `1 ) - ( f9 `1 ) ) * ( ( g9 `3 ) - ( h9 `3 ) ) ) - ( ( ( g9 `1 ) - ( h9 `1 ) ) * ( ( e9 `3 ) - ( f9 `3 ) ) ) ) <> ( 0. F )) or ( ( ( ( e9 `2 ) - ( f9 `2 ) ) * ( ( g9 `3 ) - ( h9 `3 ) ) ) - ( ( ( g9 `2 ) - ( h9 `2 ) ) * ( ( e9 `3 ) - ( f9 `3 ) ) ) ) <> ( 0. F )) by A7,A9,CKB2:1;
end;
hence thesis by PARSP_1:12;
end;
