environ
vocabularies RLVECT_1,ALGSTR_0,XBOOLE_0,SUBSET_1,ARYTM_1,SUPINF_2,ARYTM_3,VECTSP_1,PARSP_1,ZFMISC_1,STRUCT_0,MCART_1,RELAT_1,GROUP_1,MESFUNC1,PARSP_2;
notations ZFMISC_1,SUBSET_1,MCART_1,DOMAIN_1,STRUCT_0,ALGSTR_0,RLVECT_1,GROUP_1,VECTSP_1,PARSP_1,CKB19,CKB21,CKB23;
definitions CKB19,CKB23;
theorems MCART_1,VECTSP_1,PARSP_1,RLVECT_1,GROUP_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29;
registrations XBOOLE_0,STRUCT_0,VECTSP_1,PARSP_1,CKB20;
constructors DOMAIN_1,PARSP_1,CKB19,CKB23;
begin
reserve FdSp for FanodesSp;
reserve a for (Element of FdSp);
reserve b for (Element of FdSp);
reserve c for (Element of FdSp);
reserve d for (Element of FdSp);
theorem
Th22: (((not a,b,c is_collinear ) & a,b '||' c,d) implies (not a,b,d is_collinear ))
proof
assume that
A1: (not a,b,c is_collinear )
and
A2: a,b '||' c,d;
A3:now
assume that
A4: c <> d
and
A5: a <> d;
(a,c '||' c,a & c <> a) by A1,CKB26:1,PARSP_1:25;
then (not c,d,a is_collinear ) by A1,A2,A4,CKB25:1;
then A6: (not d,c,a is_collinear ) by CKB24:1;
A7: d,a '||' a,d by PARSP_1:25;
(a <> b & d,c '||' a,b) by A1,A2,CKB26:1,PARSP_1:23;
hence thesis by A5,A6,A7,CKB25:1;
end;
now
assume a = d;
then a,b '||' a,c by A2,PARSP_1:23;
hence contradiction by A1,CKB23:def 1;
end;
hence thesis by A1,A3;
end;
