environ
vocabularies NUMBERS,XXREAL_0,XREAL_0,ORDINAL1,SUBSET_1,SEQ_1,NEWTON,ARYTM_1,RELAT_1,SQUARE_1,ARYTM_3,POWER,COMPLEX1,CARD_1,FUNCT_1,SERIES_1,SERIES_3,NAT_1;
notations SUBSET_1,NUMBERS,ORDINAL1,XCMPLX_0,XXREAL_0,XREAL_0,COMPLEX1,NAT_1,SQUARE_1,NEWTON,SEQ_1,POWER,SERIES_1,SERIES_3;
definitions SQUARE_1;
theorems XCMPLX_1,SQUARE_1,SIN_COS2,NEWTON,POWER,XREAL_1,PREPOWER,SERIES_1,SERIES_3,COMPLEX1,ABSVALUE,XXREAL_0,ORDINAL1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58,CKB59,CKB60,CKB61,CKB62,CKB63,CKB64,CKB65,CKB66,CKB67,CKB68,CKB69,CKB70;
schemes NAT_1;
registrations XCMPLX_0,XXREAL_0,XREAL_0,SQUARE_1,NAT_1,MEMBERED,NEWTON,SERIES_3,XBOOLE_0,NUMBERS;
constructors REAL_1,SQUARE_1,NAT_1,BINOP_2,SEQ_1,NEWTON,SERIES_1,SERIES_3,VALUED_1,ABIAN;
requirements REAL,SUBSET,BOOLE,NUMERALS,ARITHM;
begin
reserve n for (Element of ( NAT ));
reserve s for Real_Sequence;
theorem
Th48: ((for n holds ( s . n ) = ( 1 / ( ( n + 1 ) ^2 ) )) implies (for n holds ( ( Partial_Sums s ) . n ) <= ( 2 - ( 1 / ( n + 1 ) ) )))
proof
defpred X[ (Element of ( NAT )) ]
 means
( ( Partial_Sums s ) . $1 ) <= ( 2 - ( 1 / ( $1 + 1 ) ) );
assume A1: (for n holds ( s . n ) = ( 1 / ( ( n + 1 ) ^2 ) ));
A2: (for n holds (X[ n ] implies X[ ( n + 1 ) ]))
proof
let n;
assume ( ( Partial_Sums s ) . n ) <= ( 2 - ( 1 / ( n + 1 ) ) );
then A3: ( ( ( Partial_Sums s ) . n ) + ( 1 / ( ( n + 2 ) ^2 ) ) ) <= ( ( 2 - ( 1 / ( n + 1 ) ) ) + ( 1 / ( ( n + 2 ) ^2 ) ) ) by XREAL_1:7;
( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) > ( ( ( n ^2 ) + ( 3 * n ) ) + 2 ) by XREAL_1:8;
then ( ( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) > ( ( ( n + 2 ) * ( n + 1 ) ) / ( ( ( n + 2 ) ^2 ) * ( n + 1 ) ) ) by XREAL_1:74;
then ( ( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) > ( ( n + 2 ) / ( ( n + 2 ) * ( n + 2 ) ) ) by XCMPLX_1:91;
then ( ( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) > ( ( ( n + 2 ) / ( n + 2 ) ) / ( n + 2 ) ) by XCMPLX_1:78;
then ( ( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) > ( 1 / ( n + 2 ) ) by XCMPLX_1:60;
then ( ( - 1 ) * ( ( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) ) < ( ( - 1 ) * ( 1 / ( n + 2 ) ) ) by XREAL_1:69;
then A4: ( ( - ( ( ( ( n ^2 ) + ( 3 * n ) ) + 3 ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) ) + 2 ) < ( ( - ( 1 / ( n + 2 ) ) ) + 2 ) by XREAL_1:8;
( ( Partial_Sums s ) . ( n + 1 ) ) = ( ( ( Partial_Sums s ) . n ) + ( s . ( n + 1 ) ) ) by SERIES_1:def 1
.= ( ( ( Partial_Sums s ) . n ) + ( 1 / ( ( ( n + 1 ) + 1 ) ^2 ) ) ) by A1;
then ( ( Partial_Sums s ) . ( n + 1 ) ) <= ( 2 - ( ( 1 / ( n + 1 ) ) - ( 1 / ( ( n + 2 ) ^2 ) ) ) ) by A3;
then ( ( Partial_Sums s ) . ( n + 1 ) ) <= ( 2 - ( ( ( 1 * ( ( n + 2 ) ^2 ) ) - ( 1 * ( n + 1 ) ) ) / ( ( n + 1 ) * ( ( n + 2 ) ^2 ) ) ) ) by XCMPLX_1:130;
hence thesis by A4,XXREAL_0:2;
end;
( ( Partial_Sums s ) . ( 0 ) ) = ( s . ( 0 ) ) by SERIES_1:def 1
.= ( 1 / ( ( ( 0 ) + 1 ) ^2 ) ) by A1
.= 1;
then A5: X[ ( 0 ) ];
(for n holds X[ n ]) from NAT_1:sch 1(A5,A2);
hence thesis;
end;
