environ
vocabularies FUNCT_1,PARTFUN1,TARSKI,RELAT_1,SUBSET_1,CARD_1,XBOOLE_0,CARD_5,ORDINAL2,ORDERS_2,WELLORD1,STRUCT_0,WAYBEL_0,XXREAL_0,ZFMISC_1,SETFAM_1,ORDINAL1,CARD_2,FINSET_1,FUNCOP_1,FUNCT_4,NAT_1,ARYTM_3,NUMBERS,WELLFND1;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,CARD_1,NUMBERS,RELAT_1,FUNCT_1,BINOP_1,SETFAM_1,DOMAIN_1,NAT_1,STRUCT_0,RELSET_1,PARTFUN1,FUNCT_2,FUNCT_4,FUNCOP_1,ORDINAL1,WELLORD1,ORDINAL2,FINSET_1,CARD_2,ORDERS_2,CARD_5,RFUNCT_3,WAYBEL_0,CKB7,CKB10,CKB12,CKB14;
definitions TARSKI,RELAT_1,FUNCT_1,WELLORD1,WAYBEL_0,XBOOLE_0,BINOP_1,FUNCOP_1,CKB7,CKB10,CKB12,CKB14;
theorems TARSKI,ENUMSET1,ZFMISC_1,RELAT_1,RELSET_1,FUNCT_1,ORDINAL1,WELLORD1,GRFUNC_1,PARTFUN1,FUNCT_2,ORDINAL2,FUNCOP_1,CARD_1,ORDERS_2,FUNCT_4,CARD_5,WAYBEL_0,XBOOLE_0,XBOOLE_1,REALSET1,BINOP_1,CARD_2,CKB1,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB12,CKB14,CKB16,CKB17,CKB18,CKB19,CKB21;
schemes NAT_1,SUBSET_1,DOMAIN_1,FUNCT_7,BINOP_1,CKB2,CKB20;
registrations XBOOLE_0,SUBSET_1,ORDINAL1,RELSET_1,PARTFUN1,FUNCOP_1,CARD_1,REALSET1,CARD_5,STRUCT_0,WAYBEL_0,FUNCT_1,ZFMISC_1,CKB3,CKB4,CKB11,CKB13,CKB15;
constructors SETFAM_1,WELLORD1,BINOP_1,FUNCT_4,ORDINAL2,NAT_1,CARD_2,REALSET1,CARD_5,RFUNCT_3,WAYBEL_0,RELSET_1,CKB10,CKB12,CKB14;
requirements NUMERALS,SUBSET,BOOLE;
begin
scheme WFInduction { R() -> non empty RelStr,P[set] } : (for x being (Element of R()) holds P[ x ])
provided
A1: (for x being (Element of R()) holds ((for y being (Element of R()) holds ((y <> x & [ y,x ] in (the InternalRel of R())) implies P[ y ])) implies P[ x ]))
and
A2: R() is  well_founded
proof
set c = (the carrier of R());
set r = (the InternalRel of R());
set Z = { x where x is (Element of c): P[ x ] };
now
let x being (Element of c);
assume that
A3: ( r -Seg x ) c= Z;
reconsider x9 = x as (Element of R());
now
let y9 being (Element of R());
assume (y9 <> x9 & [ y9,x9 ] in r);
then y9 in ( r -Seg x9 ) by WELLORD1:1;
then y9 in Z by A3;
then (ex y being (Element of c) st (y = y9 & P[ y ]));
hence P[ y9 ];
end;
then P[ x9 ] by A1;
hence x in Z;
end;
then A4: c c= Z by A2,CKB21:1;
let x being (Element of R());
x in c;
then x in Z by A4;
then (ex x9 being (Element of c) st (x = x9 & P[ x9 ]));
hence thesis;
end;
