environ
vocabularies NUMBERS,NAT_1,SETFAM_1,TREES_2,TARSKI,CARD_1,XBOOLE_0,FINSET_1,PEPIN,XXREAL_0,ORDINAL1,ARYTM_3,ARYTM_1,SUBSET_1,FUNCT_1,RELAT_1,INT_1,PCOMPS_1,PRE_TOPC,TOPDIM_1,WAYBEL23,RCOMP_1,PROB_1,TOPGEN_4,CARD_3,ZFMISC_1,STRUCT_0,RLVECT_3,TOPS_1,MCART_1,METRIZTS,EUCLID,XREAL_0,REAL_1,FINSEQ_1,METRIC_1,FINSEQ_2,RVSUM_1,SQUARE_1,COMPLEX1,RELAT_2,CONNSP_1,T_0TOPSP,FUNCOP_1,FUNCT_4,CARD_2;
notations TARSKI,XBOOLE_0,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,MCART_1,ZFMISC_1,FUNCT_2,CARD_1,CANTOR_1,COMPLEX1,FINSET_1,ORDINAL1,NUMBERS,XXREAL_0,XREAL_0,REAL_1,XXREAL_3,NAT_1,INT_1,SETFAM_1,DOMAIN_1,FUNCOP_1,TOPS_2,STRUCT_0,PRE_TOPC,METRIC_1,PCOMPS_1,CARD_3,PROB_1,KURATO_2,WAYBEL23,TOPS_1,T_0TOPSP,CARD_2,RVSUM_1,FINSEQ_1,FINSEQ_2,EUCLID,BORSUK_1,TOPGEN_4,FUNCT_4,SQUARE_1,CONNSP_1,TOPREAL9,ORDERS_4,METRIZTS,TOPDIM_1,CKB1,CKB4;
definitions STRUCT_0,SQUARE_1,EUCLID,PCOMPS_1,TOPS_1,TARSKI,METRIC_1,XBOOLE_0,TOPS_2,SETFAM_1,SUBSET_1,CARD_3,TOPDIM_1,CKB1,CKB4;
theorems ABSVALUE,FINSEQ_1,FINSEQ_2,FUNCT_1,FUNCT_2,RVSUM_1,TARSKI,XREAL_0,COMPLEX1,XREAL_1,XXREAL_0,FUNCOP_1,ORDINAL1,RELAT_1,PRE_TOPC,TOPMETR,EUCLID,METRIC_1,XBOOLE_0,TOPS_1,TOPS_2,TOPREAL7,PROB_1,ZFMISC_1,NAT_1,KURATO_2,INT_1,TOPGEN_1,XBOOLE_1,MCART_1,CARD_1,TOPGEN_4,SUBSET_1,TSEP_1,TSP_1,SETFAM_1,CARD_4,YELLOW_9,ORDERS_4,BORSUK_1,CARD_3,CARD_2,NECKLACE,BORSUK_3,TOPALG_3,JORDAN2C,TOPREAL9,JORDAN2B,JORDAN,STIRL2_1,FUNCT_4,ENUMSET1,XXREAL_3,CONNSP_1,WELLORD2,METRIZTS,PCOMPS_1,TOPDIM_1,YELLOW14,CKB1,CKB4,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes FUNCT_2,NAT_1,CLASSES1,LMOD_7,BORSUK_2;
registrations REALSET1,PRE_TOPC,PCOMPS_1,NAT_1,XREAL_0,SUBSET_1,STRUCT_0,TOPS_1,XXREAL_0,YELLOW13,CARD_1,XBOOLE_0,FINSET_1,VALUED_0,RELAT_1,FUNCT_1,INT_1,CARD_3,TOPGEN_4,BORSUK_3,MEMBERED,XXREAL_3,METRIZTS,TOPDIM_1,EUCLID,ZFMISC_1,RELSET_1,CKB2,CKB3,CKB5,CKB6;
constructors TOPS_2,BORSUK_1,REAL_1,COMPLEX1,CANTOR_1,TOPGEN_4,WAYBEL23,TOPS_1,SQUARE_1,RVSUM_1,BORSUK_3,CARD_2,TSP_1,CONNSP_1,BINOP_2,TOPREAL9,ORDERS_4,XXREAL_3,METRIZTS,TOPDIM_1,FUNCOP_1,FUNCSDOM,PCOMPS_1,CKB1,CKB4;
requirements REAL,SUBSET,NUMERALS,ARITHM,BOOLE;
begin
reserve n for Nat;
reserve TM for  metrizable TopSpace;
reserve A for (Subset of TM);
reserve B for (Subset of TM);
reserve F for  finite (Subset-Family of TM);
reserve G for  finite (Subset-Family of TM);
reserve I for Integer;
theorem
Th7: (for TM holds ((TM is  second-countable  finite-ind & ( ind TM ) <= I) implies (ex F st ((((F is (Cover of TM) & F is  finite-ind) & ( ind F ) <= ( 0 )) & ( card F ) <= ( I + 1 )) & (for A holds (for B holds (((A in F & B in F) & A meets B) implies A = B)))))))
proof
defpred P[ Nat ]
 means
(for TM holds ((TM is  second-countable  finite-ind & ( ind TM ) <= ( $1 - 1 )) implies (ex F being  finite (Subset-Family of TM) st ((((F is (Cover of TM) & F is  finite-ind) & ( ind F ) <= ( 0 )) & ( card F ) <= $1) & (for A,B being (Subset of TM) holds (((A in F & B in F) & A meets B) implies A = B))))));
let TM;
assume that
A1: TM is  second-countable  finite-ind
and
A2: ( ind TM ) <= I;
( - 1 ) <= ( ind ( [#] TM ) ) by A1,TOPDIM_1:5;
then ( - 1 ) <= I by A2,XXREAL_0:2;
then ( ( - 1 ) + 1 ) <= ( I + 1 ) by XREAL_1:6;
then reconsider i1 = ( I + 1 ) as (Element of ( NAT )) by INT_1:3;
A3: (for n holds (P[ n ] implies P[ ( n + 1 ) ]))
proof
let n;
assume that
A4: P[ n ];
let TM;
assume that
A5: TM is  second-countable
and
A6: TM is  finite-ind
and
A7: ( ind TM ) <= ( ( n + 1 ) - 1 );
consider A,B being (Subset of TM) such that A8: ( [#] TM ) = ( A \/ B ) and A9: A misses B and A10: ( ind A ) <= ( n - 1 ) and A11: ( ind B ) <= ( 0 ) by A5,A6,A7,CKB12:1;
set BB = { B };
(for b being (Subset of TM) holds (b in BB implies (b is  finite-ind & ( ind b ) <= ( 0 )))) by A6,A11,TARSKI:def 1;
then A12: (BB is  finite-ind & ( ind BB ) <= ( 0 )) by TOPDIM_1:11;
set TA = ( TM | A );
( ind TA ) = ( ind A ) by A6,TOPDIM_1:17;
then consider F being  finite (Subset-Family of TA) such that A13: F is (Cover of TA) and A14: F is  finite-ind and A15: ( ind F ) <= ( 0 ) and A16: ( card F ) <= n and A17: (for A,B being (Subset of TA) holds (((A in F & B in F) & A meets B) implies A = B)) by A4,A5,A6,A10;
( [#] TA ) c= ( [#] TM ) by PRE_TOPC:def 4;
then ( bool ( [#] TA ) ) c= ( bool ( [#] TM ) ) by ZFMISC_1:67;
then reconsider F9 = F as  finite (Subset-Family of TM) by XBOOLE_1:1;
take G = ( F9 \/ BB );
A18: ( union F9 ) = ( [#] TA ) by A13,SETFAM_1:45
.= A by PRE_TOPC:def 5;
then ( union G ) = ( A \/ ( union BB ) ) by ZFMISC_1:78
.= ( [#] TM ) by A8,ZFMISC_1:25;
hence G is (Cover of TM) by SETFAM_1:def 11;
(F9 is  finite-ind & ( ind F9 ) = ( ind F )) by A14,TOPDIM_1:29;
hence (G is  finite-ind & ( ind G ) <= ( 0 )) by A12,A15,TOPDIM_1:13;
( card BB ) = 1 by CARD_1:30;
then A19: ( card G ) <= ( ( card F9 ) + 1 ) by CARD_2:43;
( ( card F9 ) + 1 ) <= ( n + 1 ) by A16,XREAL_1:6;
hence ( card G ) <= ( n + 1 ) by A19,XXREAL_0:2;
let a being (Subset of TM);
let b being (Subset of TM);
assume that
A20: (a in G & b in G)
and
A21: a meets b;
per cases  by A20,XBOOLE_0:def 3;
suppose (a in F & b in F);

hence thesis by A17,A21;
end;
suppose A22: (a in F & b in BB);

then b = B by TARSKI:def 1;
hence thesis by A9,A18,A21,A22,XBOOLE_1:63,ZFMISC_1:74;
end;
suppose A23: (a in BB & b in F);

then a = B by TARSKI:def 1;
hence thesis by A9,A18,A21,A23,XBOOLE_1:63,ZFMISC_1:74;
end;
suppose A24: (a in BB & b in BB);

then a = B by TARSKI:def 1;
hence thesis by A24,TARSKI:def 1;
end;
end;
A25: P[ ( 0 ) ]
proof
let TM;
assume that
TM is  second-countable
and
A26: TM is  finite-ind
and
A27: ( ind TM ) <= ( ( 0 ) - 1 );
( ind ( [#] TM ) ) >= ( - 1 ) by A26,TOPDIM_1:5;
then ( ind ( [#] TM ) ) = ( - 1 ) by A27,XXREAL_0:1;
then A28: ( [#] TM ) = ( {} TM ) by A26,TOPDIM_1:6;
reconsider F = ( {} ) as  empty (Subset-Family of TM) by TOPGEN_4:18;
take F;
F c= { ( {} TM ) } by XBOOLE_1:2;
hence thesis by A28,SETFAM_1:def 11,TOPDIM_1:10,ZFMISC_1:2;
end;
(for n holds P[ n ]) from NAT_1:sch 2(A25,A3);
then P[ i1 ];
hence thesis by A1,A2;
end;
