environ
vocabularies XBOOLE_0,FUNCT_1,FUNCT_2,FUNCT_5,ZFMISC_1,RELAT_1,TARSKI,SUBSET_1,MCART_1,CAT_1,GRAPH_1,NATTRA_1,STRUCT_0,CAT_2,FINSEQ_2,PZFMISC1,FUNCOP_1,PARTFUN1,BORSUK_1,ISOCAT_2;
notations TARSKI,XBOOLE_0,ZFMISC_1,SUBSET_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,FUNCOP_1,BINOP_1,FUNCT_3,FUNCT_5,STRUCT_0,GRAPH_1,CAT_1,CAT_2,NATTRA_1,ISOCAT_1,CKB1,CKB10,CKB16,CKB19,CKB24,CKB30,CKB36,CKB40,CKB41,CKB42,CKB45,CKB46,CKB53,CKB57;
definitions TARSKI,FUNCT_1,CAT_1,NATTRA_1,ISOCAT_1,XBOOLE_0,BINOP_1,GRAPH_1,CKB10,CKB16,CKB19,CKB24,CKB30,CKB36,CKB41,CKB42,CKB45,CKB46,CKB53,CKB57;
theorems FUNCT_2,CAT_1,TARSKI,ZFMISC_1,FUNCT_1,DOMAIN_1,CAT_2,FUNCT_3,FUNCOP_1,NATTRA_1,ISOCAT_1,FUNCT_5,RELSET_1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB38,CKB39,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52,CKB53,CKB54,CKB55,CKB56,CKB57,CKB58;
schemes FUNCT_2;
registrations XBOOLE_0,SUBSET_1,RELSET_1,FUNCT_2,STRUCT_0,CKB37;
constructors PARTFUN1,DOMAIN_1,ISOCAT_1,FUNCOP_1,RELSET_1,CKB1,CKB10,CKB16,CKB19,CKB24,CKB30,CKB36,CKB40,CKB41,CKB42,CKB45,CKB46,CKB53,CKB57;
requirements SUBSET,BOOLE;
begin
reserve A for Category;
reserve B for Category;
reserve C for Category;
definition
let A;
let B;
let C;
func distribute (A,B,C) -> (Functor of ( Functors (A,[: B,C :]) ),[: ( Functors (A,B) ),( Functors (A,C) ) :])
means
:Def13: (for F1,F2 being (Functor of A,[: B,C :]) holds (F1 is_naturally_transformable_to F2 implies (for t being (natural_transformation of F1,F2) holds ( it . [ [ F1,F2 ],t ] ) = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 t ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 t ) ] ])));
existence
proof
defpred P[ set,set ]
 means
(for F1,F2 being (Functor of A,[: B,C :]) holds (for t being (natural_transformation of F1,F2) holds ($1 = [ [ F1,F2 ],t ] implies $2 = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 t ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 t ) ] ])));
A1:now
let f being (Morphism of ( Functors (A,[: B,C :]) ));
consider F1 being (Functor of A,[: B,C :]),F2 being (Functor of A,[: B,C :]),s being (natural_transformation of F1,F2) such that A2: F1 is_naturally_transformable_to F2 and ( dom f ) = F1 and ( cod f ) = F2 and A3: f = [ [ F1,F2 ],s ] by CKB9:1;
((the carrier' of ( Functors (A,C) )) = ( NatTrans (A,C) ) & ( Pr2 F1 ) is_naturally_transformable_to ( Pr2 F2 )) by A2,ISOCAT_1:22,NATTRA_1:def 17;
then A4: [ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 s ) ] is (Morphism of ( Functors (A,C) )) by NATTRA_1:32;
((the carrier' of ( Functors (A,B) )) = ( NatTrans (A,B) ) & ( Pr1 F1 ) is_naturally_transformable_to ( Pr1 F2 )) by A2,ISOCAT_1:22,NATTRA_1:def 17;
then [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 s ) ] is (Morphism of ( Functors (A,B) )) by NATTRA_1:32;
then reconsider g = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 s ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 s ) ] ] as (Morphism of [: ( Functors (A,B) ),( Functors (A,C) ) :]) by A4,CAT_2:26;
take g;
thus P[ f,g ]
proof
let G1 being (Functor of A,[: B,C :]),G2 being (Functor of A,[: B,C :]);
let t being (natural_transformation of G1,G2);
assume A5: f = [ [ G1,G2 ],t ];
then [ G1,G2 ] = [ F1,F2 ] by A3,ZFMISC_1:27;
then A6: (G1 = F1 & G2 = F2) by ZFMISC_1:27;
t = s by A3,A5,ZFMISC_1:27;
hence thesis by A6;
end;

end;
consider IT being (Function of (the carrier' of ( Functors (A,[: B,C :]) )),(the carrier' of [: ( Functors (A,B) ),( Functors (A,C) ) :])) such that A7: (for f being (Morphism of ( Functors (A,[: B,C :]) )) holds P[ f,( IT . f ) ]) from FUNCT_2:sch 3(A1);
IT is (Functor of ( Functors (A,[: B,C :]) ),[: ( Functors (A,B) ),( Functors (A,C) ) :])
proof
thus (for c being (Object of ( Functors (A,[: B,C :]) )) holds (ex d being (Object of [: ( Functors (A,B) ),( Functors (A,C) ) :]) st ( IT . ( id c ) ) = ( id d )))
proof
let c being (Object of ( Functors (A,[: B,C :]) ));
reconsider F = c as (Functor of A,[: B,C :]) by CKB8:1;
reconsider d2 = ( Pr2 F ) as (Object of ( Functors (A,C) )) by CKB8:1;
reconsider d1 = ( Pr1 F ) as (Object of ( Functors (A,B) )) by CKB8:1;
take [ d1,d2 ];
( Pr1 ( id F ) ) = ( id ( Pr1 F ) ) by ISOCAT_1:33;
then A8: ( id d1 ) = [ [ ( Pr1 F ),( Pr1 F ) ],( Pr1 ( id F ) ) ] by NATTRA_1:def 17;
( Pr2 ( id F ) ) = ( id ( Pr2 F ) ) by ISOCAT_1:33;
then A9: ( id d2 ) = [ [ ( Pr2 F ),( Pr2 F ) ],( Pr2 ( id F ) ) ] by NATTRA_1:def 17;
( id c ) = [ [ F,F ],( id F ) ] by NATTRA_1:def 17;
hence ( IT . ( id c ) ) = [ ( id d1 ),( id d2 ) ] by A7,A8,A9
.= ( id [ d1,d2 ] ) by CAT_2:31;
end;

A10: (the carrier' of ( Functors (A,C) )) = ( NatTrans (A,C) ) by NATTRA_1:def 17;
A11: (the carrier' of ( Functors (A,B) )) = ( NatTrans (A,B) ) by NATTRA_1:def 17;
thus (for f being (Morphism of ( Functors (A,[: B,C :]) )) holds (( IT . ( id ( dom f ) ) ) = ( id ( dom ( IT . f ) ) ) & ( IT . ( id ( cod f ) ) ) = ( id ( cod ( IT . f ) ) )))
proof
let f being (Morphism of ( Functors (A,[: B,C :]) ));
consider F1 being (Functor of A,[: B,C :]),F2 being (Functor of A,[: B,C :]),s being (natural_transformation of F1,F2) such that A12: F1 is_naturally_transformable_to F2 and A13: ( dom f ) = F1 and A14: ( cod f ) = F2 and A15: f = [ [ F1,F2 ],s ] by CKB9:1;
( Pr1 F1 ) is_naturally_transformable_to ( Pr1 F2 ) by A12,ISOCAT_1:22;
then reconsider f1 = [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 s ) ] as (Morphism of ( Functors (A,B) )) by A11,NATTRA_1:32;
(( dom f1 ) = ( Pr1 F1 ) & ( Pr1 ( id F1 ) ) = ( id ( Pr1 F1 ) )) by ISOCAT_1:33,NATTRA_1:33;
then A16: ( id ( dom f1 ) ) = [ [ ( Pr1 F1 ),( Pr1 F1 ) ],( Pr1 ( id F1 ) ) ] by NATTRA_1:def 17;
( Pr2 F1 ) is_naturally_transformable_to ( Pr2 F2 ) by A12,ISOCAT_1:22;
then reconsider f2 = [ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 s ) ] as (Morphism of ( Functors (A,C) )) by A10,NATTRA_1:32;
(( dom f2 ) = ( Pr2 F1 ) & ( Pr2 ( id F1 ) ) = ( id ( Pr2 F1 ) )) by ISOCAT_1:33,NATTRA_1:33;
then A17: ( id ( dom f2 ) ) = [ [ ( Pr2 F1 ),( Pr2 F1 ) ],( Pr2 ( id F1 ) ) ] by NATTRA_1:def 17;
( id ( dom f ) ) = [ [ F1,F1 ],( id F1 ) ] by A13,NATTRA_1:def 17;
hence ( IT . ( id ( dom f ) ) ) = [ ( id ( dom f1 ) ),( id ( dom f2 ) ) ] by A7,A16,A17
.= ( id [ ( dom f1 ),( dom f2 ) ] ) by CAT_2:31
.= ( id ( dom [ f1,f2 ] ) ) by CAT_2:28
.= ( id ( dom ( IT . f ) ) ) by A7,A15;
(( cod f1 ) = ( Pr1 F2 ) & ( Pr1 ( id F2 ) ) = ( id ( Pr1 F2 ) )) by ISOCAT_1:33,NATTRA_1:33;
then A18: ( id ( cod f1 ) ) = [ [ ( Pr1 F2 ),( Pr1 F2 ) ],( Pr1 ( id F2 ) ) ] by NATTRA_1:def 17;
(( cod f2 ) = ( Pr2 F2 ) & ( Pr2 ( id F2 ) ) = ( id ( Pr2 F2 ) )) by ISOCAT_1:33,NATTRA_1:33;
then A19: ( id ( cod f2 ) ) = [ [ ( Pr2 F2 ),( Pr2 F2 ) ],( Pr2 ( id F2 ) ) ] by NATTRA_1:def 17;
( id ( cod f ) ) = [ [ F2,F2 ],( id F2 ) ] by A14,NATTRA_1:def 17;
hence ( IT . ( id ( cod f ) ) ) = [ ( id ( cod f1 ) ),( id ( cod f2 ) ) ] by A7,A18,A19
.= ( id [ ( cod f1 ),( cod f2 ) ] ) by CAT_2:31
.= ( id ( cod [ f1,f2 ] ) ) by CAT_2:28
.= ( id ( cod ( IT . f ) ) ) by A7,A15;
end;

let f being (Morphism of ( Functors (A,[: B,C :]) )),g being (Morphism of ( Functors (A,[: B,C :]) ));
assume that
A20: ( dom g ) = ( cod f );
consider F1 being (Functor of A,[: B,C :]),F2 being (Functor of A,[: B,C :]),s being (natural_transformation of F1,F2) such that A21: F1 is_naturally_transformable_to F2 and ( dom f ) = F1 and A22: ( cod f ) = F2 and A23: f = [ [ F1,F2 ],s ] by CKB9:1;
consider G1 being (Functor of A,[: B,C :]),G2 being (Functor of A,[: B,C :]),t being (natural_transformation of G1,G2) such that A24: G1 is_naturally_transformable_to G2 and A25: ( dom g ) = G1 and ( cod g ) = G2 and A26: g = [ [ G1,G2 ],t ] by CKB9:1;
reconsider t as (natural_transformation of F2,G2) by A20,A22,A25;
A27: ( g * f ) = [ [ F1,G2 ],( t `*` s ) ] by A20,A22,A23,A25,A26,NATTRA_1:36;
A28: ( Pr2 F1 ) is_naturally_transformable_to ( Pr2 F2 ) by A21,ISOCAT_1:22;
( Pr2 F2 ) is_naturally_transformable_to ( Pr2 G2 ) by A20,A22,A24,A25,ISOCAT_1:22;
then reconsider g2 = [ [ ( Pr2 F2 ),( Pr2 G2 ) ],( Pr2 t ) ],f2 = [ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 s ) ] as (Morphism of ( Functors (A,C) )) by A10,A28,NATTRA_1:32;
A29: ( g2 * f2 ) = [ [ ( Pr2 F1 ),( Pr2 G2 ) ],( ( Pr2 t ) `*` ( Pr2 s ) ) ] by NATTRA_1:36
.= [ [ ( Pr2 F1 ),( Pr2 G2 ) ],( Pr2 ( t `*` s ) ) ] by A20,A21,A22,A24,A25,ISOCAT_1:27;
A30: ( dom g2 ) = ( Pr2 F2 ) by NATTRA_1:33
.= ( cod f2 ) by NATTRA_1:33;
A31: ( Pr1 F1 ) is_naturally_transformable_to ( Pr1 F2 ) by A21,ISOCAT_1:22;
( Pr1 F2 ) is_naturally_transformable_to ( Pr1 G2 ) by A20,A22,A24,A25,ISOCAT_1:22;
then reconsider g1 = [ [ ( Pr1 F2 ),( Pr1 G2 ) ],( Pr1 t ) ],f1 = [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 s ) ] as (Morphism of ( Functors (A,B) )) by A11,A31,NATTRA_1:32;
A32: ( dom g1 ) = ( Pr1 F2 ) by NATTRA_1:33
.= ( cod f1 ) by NATTRA_1:33;
A33: ( IT . f ) = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 s ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 s ) ] ] by A7,A23;
( g1 * f1 ) = [ [ ( Pr1 F1 ),( Pr1 G2 ) ],( ( Pr1 t ) `*` ( Pr1 s ) ) ] by NATTRA_1:36
.= [ [ ( Pr1 F1 ),( Pr1 G2 ) ],( Pr1 ( t `*` s ) ) ] by A20,A21,A22,A24,A25,ISOCAT_1:27;
hence ( IT . ( g * f ) ) = [ ( g1 * f1 ),( g2 * f2 ) ] by A7,A29,A27
.= ( [ g1,g2 ] * [ f1,f2 ] ) by A32,A30,CAT_2:29
.= ( ( IT . g ) * ( IT . f ) ) by A7,A20,A22,A25,A26,A33;
end;
then reconsider IT as (Functor of ( Functors (A,[: B,C :]) ),[: ( Functors (A,B) ),( Functors (A,C) ) :]);
take IT;
let F1 being (Functor of A,[: B,C :]),F2 being (Functor of A,[: B,C :]);
assume that
A34: F1 is_naturally_transformable_to F2;
let t being (natural_transformation of F1,F2);
set f = [ [ F1,F2 ],t ];
f in ( NatTrans (A,[: B,C :]) ) by A34,NATTRA_1:32;
then reconsider f as (Morphism of ( Functors (A,[: B,C :]) )) by NATTRA_1:def 17;
thus ( IT . [ [ F1,F2 ],t ] ) = ( IT . f )
.= [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 t ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 t ) ] ] by A7;
end;
uniqueness
proof
let IT1 being (Functor of ( Functors (A,[: B,C :]) ),[: ( Functors (A,B) ),( Functors (A,C) ) :]),IT2 being (Functor of ( Functors (A,[: B,C :]) ),[: ( Functors (A,B) ),( Functors (A,C) ) :]);
assume that
A35: (for F1,F2 being (Functor of A,[: B,C :]) holds (F1 is_naturally_transformable_to F2 implies (for t being (natural_transformation of F1,F2) holds ( IT1 . [ [ F1,F2 ],t ] ) = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 t ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 t ) ] ])))
and
A36: (for F1,F2 being (Functor of A,[: B,C :]) holds (F1 is_naturally_transformable_to F2 implies (for t being (natural_transformation of F1,F2) holds ( IT2 . [ [ F1,F2 ],t ] ) = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 t ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 t ) ] ])));
now
let f being (Morphism of ( Functors (A,[: B,C :]) ));
consider F1 being (Functor of A,[: B,C :]),F2 being (Functor of A,[: B,C :]),s being (natural_transformation of F1,F2) such that A37: F1 is_naturally_transformable_to F2 and ( dom f ) = F1 and ( cod f ) = F2 and A38: f = [ [ F1,F2 ],s ] by CKB9:1;
thus ( IT1 . f ) = [ [ [ ( Pr1 F1 ),( Pr1 F2 ) ],( Pr1 s ) ],[ [ ( Pr2 F1 ),( Pr2 F2 ) ],( Pr2 s ) ] ] by A35,A37,A38
.= ( IT2 . f ) by A36,A37,A38;
end;
hence IT1 = IT2 by FUNCT_2:63;
end;
end;
