environ
vocabularies NUMBERS,XREAL_0,ORDINAL1,PRE_TOPC,EUCLID,ARYTM_3,MCART_1,XXREAL_0,RLTOPSP1,ARYTM_1,REAL_1,CARD_1,RELAT_1,SUBSET_1,TOPREAL1,FUNCT_1,BORSUK_1,ORDINAL2,TOPS_2,JORDAN3,JGRAPH_6,PSCOMP_1,JORDAN17,JGRAPH_2,STRUCT_0,FUNCT_2,VALUED_1,TARSKI,XBOOLE_0;
notations XBOOLE_0,ORDINAL1,NUMBERS,XCMPLX_0,TARSKI,TOPS_2,RLVECT_1,RLTOPSP1,EUCLID,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,SUBSET_1,STRUCT_0,TOPMETR,PRE_TOPC,JORDAN6,JORDAN17,JGRAPH_2,XREAL_0,TOPREAL1,PSCOMP_1,REAL_1,JGRAPH_6,XXREAL_0;
definitions TARSKI,STRUCT_0,RLTOPSP1;
theorems XBOOLE_0,FUNCT_1,FUNCT_2,TOPS_2,PRE_TOPC,EUCLID,JGRAPH_2,BORSUK_1,TOPREAL1,JORDAN7,JORDAN17,XREAL_0,XCMPLX_1,JGRAPH_6,JORDAN1K,XREAL_1,XXREAL_0,XXREAL_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25,CKB26,CKB27,CKB28,CKB29,CKB30,CKB31,CKB32,CKB33,CKB34,CKB35,CKB36,CKB37,CKB38,CKB39,CKB40,CKB41,CKB42,CKB43,CKB44,CKB45,CKB46,CKB47,CKB48,CKB49,CKB50,CKB51,CKB52;
registrations XBOOLE_0,RELSET_1,FUNCT_2,XREAL_0,MEMBERED,STRUCT_0,BORSUK_1,EUCLID,JGRAPH_2;
constructors REAL_1,RCOMP_1,TOPS_2,TOPMETR,TOPREAL1,SPPOL_2,PSCOMP_1,JORDAN6,JGRAPH_2,JORDAN17,JGRAPH_6,BINOP_2;
requirements REAL,BOOLE,SUBSET,NUMERALS,ARITHM;
begin
theorem
Th53: (for a,b,c,d being  real number holds (for h being (Function of ( TOP-REAL 2 ),( TOP-REAL 2 )) holds (for f being (Function of ( I[01] ),( TOP-REAL 2 )) holds ((((a < b & c < d) & h = ( AffineMap (( 2 / ( b - a ) ),( - ( ( b + a ) / ( b - a ) ) ),( 2 / ( d - c ) ),( - ( ( d + c ) / ( d - c ) ) )) )) & f is  continuous  one-to-one) implies ( h * f ) is  continuous  one-to-one))))
proof
let a being  real number;
let b being  real number;
let c being  real number;
let d being  real number;
let h being (Function of ( TOP-REAL 2 ),( TOP-REAL 2 ));
let f being (Function of ( I[01] ),( TOP-REAL 2 ));
set A = ( 2 / ( b - a ) );
set B = ( - ( ( b + a ) / ( b - a ) ) );
set C = ( 2 / ( d - c ) );
set D = ( - ( ( d + c ) / ( d - c ) ) );
assume that
A1: a < b
and
A2: c < d
and
A3: h = ( AffineMap (A,B,C,D) )
and
A4: f is  continuous  one-to-one;
( d - c ) > ( 0 ) by A2,XREAL_1:50;
then A5: C > ( 0 ) by XREAL_1:139;
( b - a ) > ( 0 ) by A1,XREAL_1:50;
then A > ( 0 ) by XREAL_1:139;
then h is  being_homeomorphism by A3,A5,CKB51:1;
then h is  one-to-one by TOPS_2:def 5;
hence thesis by A3,A4,FUNCT_1:24;
end;
