environ
vocabularies NUMBERS,REAL_1,CFUNCT_1,NORMSP_1,CLVECT_1,PARTFUN1,NFCONT_2,TARSKI,RELAT_1,CARD_1,ARYTM_3,PRE_TOPC,ARYTM_1,STRUCT_0,COMPLEX1,XBOOLE_0,XXREAL_0,VALUED_1,SUPINF_2,FUNCT_1,CFCONT_1,NFCONT_1,SUBSET_1,RCOMP_1,NAT_1,VALUED_0,SEQ_2,ORDINAL2,FCONT_1,FUNCT_2,SEQ_4,CLOPBAN1,ALI2,FUNCOP_1,POWER,RSSPACE3,FUNCT_7;
notations TARSKI,XBOOLE_0,SUBSET_1,NUMBERS,XCMPLX_0,XXREAL_0,COMPLEX1,REAL_1,NAT_1,RELAT_1,FUNCT_1,RELSET_1,PARTFUN1,FUNCT_2,PRE_TOPC,VALUED_0,STRUCT_0,RLVECT_1,FUNCOP_1,VALUED_1,SEQ_2,SEQ_4,FUNCT_7,VFUNCT_1,SQUARE_1,POWER,CFUNCT_1,VFUNCT_2,NORMSP_0,NORMSP_1,CLVECT_1,NFCONT_1,CLOPBAN1,NFCONT_2,NCFCONT1,CSSPACE3,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
definitions RLVECT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
theorems TARSKI,ABSVALUE,XBOOLE_1,RLVECT_1,XCMPLX_1,SEQ_2,NAT_1,RELAT_1,FUNCT_1,VFUNCT_1,FUNCT_2,SEQ_4,NORMSP_1,LOPBAN_3,PARTFUN2,CLVECT_1,CLOPBAN3,VFUNCT_2,NFCONT_1,CLOPBAN1,COMPLEX1,NCFCONT1,NFCONT_2,FUNCOP_1,POWER,CSSPACE3,FUNCT_7,SEQ_1,XREAL_1,XXREAL_0,ORDINAL1,PARTFUN1,VALUED_0,NORMSP_0,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB10,CKB11,CKB12,CKB13,CKB14,CKB15;
schemes FUNCT_2,NAT_1;
registrations XBOOLE_0,FUNCT_1,ORDINAL1,RELSET_1,XXREAL_0,XREAL_0,MEMBERED,STRUCT_0,VALUED_1,FUNCT_2,NUMBERS,VALUED_0,FUNCT_7;
constructors PARTFUN1,REAL_1,SQUARE_1,NAT_1,COMPLEX1,SEQ_2,SEQ_4,PARTFUN2,POWER,FUNCT_7,BHSP_3,VFUNCT_1,LOPBAN_3,CSSPACE3,NFCONT_1,NFCONT_2,CLOPBAN3,VFUNCT_2,NCFCONT1,SEQ_1,VALUED_1,RECDEF_1,NORMSP_1,RELSET_1,CFCONT_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6;
requirements SUBSET,REAL,BOOLE,NUMERALS,ARITHM;
begin
reserve X for set;
reserve r for Real;
reserve s for Real;
reserve z for Complex;
reserve CNS1 for ComplexNormSpace;
reserve CNS2 for ComplexNormSpace;
theorem
Th10: (for f being (PartFunc of CNS1,CNS2) holds (f is_uniformly_continuous_on X implies ( z (#) f ) is_uniformly_continuous_on X))
proof
let f being (PartFunc of CNS1,CNS2);
assume A1: f is_uniformly_continuous_on X;
then X c= ( dom f ) by CKB1:def 1;
hence A2: X c= ( dom ( z (#) f ) ) by VFUNCT_2:def 2;
now
per cases ;
suppose A3: z = ( 0 );

let r;
assume A4: ( 0 ) < r;
then consider s such that A5: ( 0 ) < s and (for x1,x2 being (Point of CNS1) holds (((x1 in X & x2 in X) & ||. ( x1 - x2 ) .|| < s) implies ||. ( ( f /. x1 ) - ( f /. x2 ) ) .|| < r)) by A1,CKB1:def 1;
take s;
thus ( 0 ) < s by A5;
let x1 being (Point of CNS1);
let x2 being (Point of CNS1);
assume that
A6: x1 in X
and
A7: x2 in X
and
||. ( x1 - x2 ) .|| < s;
||. ( ( ( z (#) f ) /. x1 ) - ( ( z (#) f ) /. x2 ) ) .|| = ||. ( ( z * ( f /. x1 ) ) - ( ( z (#) f ) /. x2 ) ) .|| by A2,A6,VFUNCT_2:def 2
.= ||. ( ( 0. CNS2 ) - ( ( z (#) f ) /. x2 ) ) .|| by A3,CLVECT_1:1
.= ||. ( ( 0. CNS2 ) - ( z * ( f /. x2 ) ) ) .|| by A2,A7,VFUNCT_2:def 2
.= ||. ( ( 0. CNS2 ) - ( 0. CNS2 ) ) .|| by A3,CLVECT_1:1
.= ||. ( 0. CNS2 ) .|| by RLVECT_1:13
.= ( 0 ) by NORMSP_0:def 6;
hence ||. ( ( ( z (#) f ) /. x1 ) - ( ( z (#) f ) /. x2 ) ) .|| < r by A4;
end;
suppose A8: z <> ( 0 );

let r;
A9: ( 0 ) < |. z .| by A8,COMPLEX1:47;
assume ( 0 ) < r;
then ( 0 ) < ( r / |. z .| ) by A9,XREAL_1:139;
then consider s such that A10: ( 0 ) < s and A11: (for x1,x2 being (Point of CNS1) holds (((x1 in X & x2 in X) & ||. ( x1 - x2 ) .|| < s) implies ||. ( ( f /. x1 ) - ( f /. x2 ) ) .|| < ( r / |. z .| ))) by A1,CKB1:def 1;
take s;
thus ( 0 ) < s by A10;
let x1 being (Point of CNS1);
let x2 being (Point of CNS1);
assume that
A12: x1 in X
and
A13: x2 in X
and
A14: ||. ( x1 - x2 ) .|| < s;
A15: ||. ( ( ( z (#) f ) /. x1 ) - ( ( z (#) f ) /. x2 ) ) .|| = ||. ( ( z * ( f /. x1 ) ) - ( ( z (#) f ) /. x2 ) ) .|| by A2,A12,VFUNCT_2:def 2
.= ||. ( ( z * ( f /. x1 ) ) - ( z * ( f /. x2 ) ) ) .|| by A2,A13,VFUNCT_2:def 2
.= ||. ( z * ( ( f /. x1 ) - ( f /. x2 ) ) ) .|| by CLVECT_1:9
.= ( |. z .| * ||. ( ( f /. x1 ) - ( f /. x2 ) ) .|| ) by CLVECT_1:def 13;
( |. z .| * ||. ( ( f /. x1 ) - ( f /. x2 ) ) .|| ) < ( ( r / |. z .| ) * |. z .| ) by A9,A11,A12,A13,A14,XREAL_1:68;
hence ||. ( ( ( z (#) f ) /. x1 ) - ( ( z (#) f ) /. x2 ) ) .|| < r by A9,A15,XCMPLX_1:87;
end;
end;
hence thesis;
end;
