environ
vocabularies LATTICES,ROBBINS1,XBOOLE_0,SUBSET_1,ARYTM_3,EQREL_1,ZFMISC_1,PBOOLE,STRUCT_0,BINOP_1,FUNCT_5,RELAT_1,FUNCT_1,SHEFFER1,CARD_1;
notations TARSKI,XBOOLE_0,FUNCT_5,CARD_1,STRUCT_0,LATTICES,BINOP_1,ROBBINS1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB17;
definitions LATTICES,ROBBINS1,STRUCT_0,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB17;
theorems STRUCT_0,ROBBINS1,LATTICES,CARD_1,CKB1,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB11,CKB12,CKB13,CKB14,CKB15,CKB16,CKB17,CKB18,CKB19,CKB20,CKB21,CKB22,CKB23,CKB24,CKB25;
registrations LATTICES,LATTICE6,ROBBINS1,XBOOLE_0,ZFMISC_1,CARD_1,ORDINAL1,STRUCT_0,CKB10;
constructors BINOP_1,ROBBINS1,FUNCT_5,CKB2,CKB3,CKB4,CKB5,CKB6,CKB7,CKB8,CKB9,CKB17;
requirements SUBSET,NUMERALS;
begin
theorem
Th17: (for L being  join-commutative  meet-commutative  meet-absorbing  join-absorbing  join-idempotent  distributive non  empty LattStr holds L is  join-associative)
proof
let L being  join-commutative  meet-commutative  meet-absorbing  join-absorbing  join-idempotent  distributive non  empty LattStr;
let x being (Element of L);
let y being (Element of L);
let z being (Element of L);
A1: ( ( ( y "\/" z ) "\/" x ) "/\" y ) = ( ( y "/\" ( y "\/" z ) ) "\/" ( y "/\" x ) ) by LATTICES:def 11
.= ( ( ( y "/\" y ) "\/" ( y "/\" z ) ) "\/" ( y "/\" x ) ) by LATTICES:def 11
.= ( ( y "\/" ( y "/\" z ) ) "\/" ( y "/\" x ) ) by LATTICES:2
.= ( y "\/" ( y "/\" x ) ) by LATTICES:def 8
.= y by LATTICES:def 8;
A2: ( ( ( x "\/" y ) "\/" z ) "/\" x ) = x by CKB15:1;
( x "\/" ( y "\/" z ) ) = ( ( x "\/" y ) "\/" z )
proof
set A = ( ( ( x "\/" y ) "\/" z ) "/\" ( x "\/" ( y "\/" z ) ) );
A3: A = ( ( ( x "\/" y ) "/\" ( x "\/" ( y "\/" z ) ) ) "\/" ( z "/\" ( x "\/" ( y "\/" z ) ) ) ) by LATTICES:def 11
.= ( ( ( x "\/" y ) "/\" ( x "\/" ( y "\/" z ) ) ) "\/" z ) by CKB15:1
.= ( ( ( x "/\" ( x "\/" ( y "\/" z ) ) ) "\/" ( y "/\" ( x "\/" ( y "\/" z ) ) ) ) "\/" z ) by LATTICES:def 11
.= ( ( x "\/" y ) "\/" z ) by A1,LATTICES:def 9;
A = ( ( ( ( x "\/" y ) "\/" z ) "/\" x ) "\/" ( ( ( x "\/" y ) "\/" z ) "/\" ( y "\/" z ) ) ) by LATTICES:def 11
.= ( x "\/" ( ( ( ( x "\/" y ) "\/" z ) "/\" y ) "\/" ( ( ( x "\/" y ) "\/" z ) "/\" z ) ) ) by A2,LATTICES:def 11
.= ( x "\/" ( y "\/" ( ( ( x "\/" y ) "\/" z ) "/\" z ) ) ) by CKB15:1
.= ( x "\/" ( y "\/" ( ( ( x "\/" y ) "/\" z ) "\/" ( z "/\" z ) ) ) ) by LATTICES:def 11
.= ( x "\/" ( y "\/" ( ( ( x "\/" y ) "/\" z ) "\/" z ) ) ) by LATTICES:2
.= ( x "\/" ( y "\/" z ) ) by LATTICES:def 8;
hence thesis by A3;
end;
hence thesis;
end;
